### PR TITLE
execbuilder,invertedexpr,rowexec,...: add pre-filtering to invertedFi…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…lterer

The optional pre-filtering is passed as an expression in the spec,
and the PreFilterer instantiated in the invertedFilterer using
the invertedidx.NewBoundPreFilterer() factory method.

Pre-filtering is restricted to geometry and geography expressions
that are a single function. But using the expression in the spec
allows for this to be extended without a spec change.

Release note: None

Release justification: The geospatial functionality is
new for this release so this falls under category 2
(low-risk updates to new functionality).

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I haven't added tests since I wanted a quick sanity check first.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-:-MGywHBU3tKEQquEdYgF:b3mpmsq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

**Review by rytaft — COMMENTED** [review]
Looks sane to me :)

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-:-MH3L2Kh1tdWjkhxndmG:b9qo9cs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/expression.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MH3GQvSDyl6yajory2M:-MH3GQvSDyl6yajory2N:bfv3bu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cad524bd83901c188208b945a82b792a0cab355/pkg/sql/opt/invertedexpr/expression.go#L84)):*
> ```Go
> 	Expr opt.ScalarExpr
> 	// VariableCol is the column id of the single variable in the expression.
> 	VariableCol opt.ColumnID
> ```

[nit] I'd just call this `Col` -- it's more consistent with the rest of the optimizer code
___
*[pkg/sql/opt/invertedidx/geo.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MH3ILD81Fh1ov6OuoI5:-MH3ILD81Fh1ov6OuoI6:bg9v55z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cad524bd83901c188208b945a82b792a0cab355/pkg/sql/opt/invertedidx/geo.go#L653)):*
> ```Go
> 	}
> 	name := geoindex.RelationshipReverseMap[relationship]
> 	preFilterExpr := constructFunction(factory, name, funcArgs)
> ```

This is now very similar to what's happening in `joinGeoIndexFromExpr`. Is it possible to extract that code into a helper function and use it here?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

Added test.

> Reviewed 20 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-:-MH85_spCXLhLhP3oXFS:b80ldsg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/expression.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MH3GQvSDyl6yajory2M:-MH7eo4M8UpSoN0_qYfh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cad524bd83901c188208b945a82b792a0cab355/pkg/sql/opt/invertedexpr/expression.go#L84)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I'd just call this `Col` -- it's more consistent with the rest of the optimizer code
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/geo.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MH3ILD81Fh1ov6OuoI5:-MH7yv2U2AZ6IRbmBJKx:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cad524bd83901c188208b945a82b792a0cab355/pkg/sql/opt/invertedidx/geo.go#L653)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is now very similar to what's happening in `joinGeoIndexFromExpr`. Is it possible to extract that code into a helper function and use it here?
</blockquote></details>

Done

**Review by rytaft — COMMENTED** [review]
> Reviewed 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54283)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/opt/invertedidx/geo.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBc8SgCLY7m_7TOGgC:-MHBc8Sh6ZKaFFDeZFRN:b-2fll55) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L448)):*
> ```Go
> 		// Copy the original arguments into a new list, and swap the first two
> 		// arguments.
> 		commutedArgs := make(memo.ScalarListExpr, len(args))
> ```

seems like you might as well put all of this logic with extracting args and constructing the function into `extractInfoFromExpr` too, right? Is there any reason these shouldn't be identical? (don't you also want to support bounding box operations with the prefilter?)
___
*[pkg/sql/opt/invertedidx/geo.go, line 588 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBaAOsBE0wiWkIOM3b:-MHBaAOsBE0wiWkIOM3c:b1t2o1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L588)):*
> ```Go
> 
> // extractInfoFromExpr is a helper used for extracting information from a
> // function represented by expr, with args. The second arg is checked to be
> ```

function -> function or operation 

(assuming you also want to support bounding box operations)
___
*[pkg/sql/opt/invertedidx/geo.go, line 592 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHB_zvt7FUIcQzDIFEQ:-MHB_zvt7FUIcQzDIFER:bj0ctw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L592)):*
> ```Go
> // are checked to be constant. The returned relationship includes the effect
> // of commuteArgs.
> // REQUIRES: the function has at least to args.
> ```

to -> two

I'd change this to "REQUIRES: len(args) >= 2"
___
*[pkg/sql/opt/invertedidx/geo.go, line 608 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBahTj7wkkmOqGLKtF:-MHBahTj7wkkmOqGLKtG:bg4mn6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L608)):*
> ```Go
> 	relationship, ok = GetGeoIndexRelationship(expr)
> 	if !ok {
> 		return
> ```

[nit] I think it's more common and clearer to just return all the args (even though the return vars were predefined). Then you can make clear that a case like this was considered unsuccessful with `return 0, nil, nil, nil, false`
___
*[pkg/sql/opt/invertedidx/geo_test.go, line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBe8aCEWCmXj4_MyVa:-MHBe8aCEWCmXj4_MyVb:b-om3cdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo_test.go#L353)):*
> ```Go
> 			indexOrd:            geomOrd,
> 			ok:                  true,
> 			preFilterExpr:       "function: st_intersects [type=bool]\n ├── const: '0102000000020000000000000000000000000000000000000000000000000000000000000000000040' [type=geometry]\n └── variable: unknown1:1 [type=geometry]\n",
> ```

These expressions are pretty big and ugly, and I'm not sure it's very useful to include the full string here. Maybe just include the function name?
___
*[pkg/sql/opt/invertedidx/geo_test.go, line 494 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBec1QC7SiS3-kEvv_:-MHBec1QC7SiS3-kEvva:bpmg6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo_test.go#L494)):*
> ```Go
> 			indexOrd:            geogOrd,
> 			ok:                  false,
> 			preFilterExpr:       "foo",
> ```

Since `ok` is false, I would just not set these remaining values (since they won't be tested anyway)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54283)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[pkg/sql/opt/invertedidx/geo.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBc8SgCLY7m_7TOGgC:-MHCDqIiCektlXqgUD61:bg33io8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L448)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

seems like you might as well put all of this logic with extracting args and constructing the function into `extractInfoFromExpr` too, right? Is there any reason these shouldn't be identical? (don't you also want to support bounding box operations with the prefilter?)
</blockquote></details>

The two callers of `extractInfoFromExpr` are different enough in this behavior that I thought it would reduce code readability. Specifically, `joinGeoIndexFromExpr` tries to reuse the original expression, and only does the construction when commuting or dealing with bbox operators. The expression there is not for pre-filtering since that will be constructed at execution time.

The invertedFilterer is doing this function construction always, so it naturally handles the bbox operations since it is constructing using the relationship (geo_test.go covers these bbox cases for pre-filtering). I guess we could do a similar lazy construction if we were certain that the `opt.ScalarExpr` expr param would not be mutated -- can I rely on that? 
___
*[pkg/sql/opt/invertedidx/geo.go, line 588 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBaAOsBE0wiWkIOM3b:-MHCFxUM8hRNrP_E2vIc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L588)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

function -> function or operation 

(assuming you also want to support bounding box operations)
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/geo.go, line 592 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHB_zvt7FUIcQzDIFEQ:-MHCFx0j8juJ76_8B336:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L592)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

to -> two

I'd change this to "REQUIRES: len(args) >= 2"
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/geo.go, line 608 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBahTj7wkkmOqGLKtF:-MHCG_XT9BpHg3inQl_D:bcqsrs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L608)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I think it's more common and clearer to just return all the args (even though the return vars were predefined). Then you can make clear that a case like this was considered unsuccessful with `return 0, nil, nil, nil, false`
</blockquote></details>

I was so enjoying living dangerously. Done.
___
*[pkg/sql/opt/invertedidx/geo_test.go, line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBe8aCEWCmXj4_MyVa:-MHCHZHCB1jehhcwV33_:b5t0ilb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo_test.go#L353)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These expressions are pretty big and ugly, and I'm not sure it's very useful to include the full string here. Maybe just include the function name?
</blockquote></details>

when the test fails these give nice multi-line output like the following
```
        	            	+function: st_intersects [type=bool]
        	            	+ ├── const: '0102000000020000000000000000000000000000000000000000000000000000000000000000000040' [type=geometry]
        	            	+ └── variable: unknown1:1 [type=geometry]
        	            	+
```

I like the completeness of the information. Would it be better if I broke the string literals into multiple lines in the code so it would look less big?
___
*[pkg/sql/opt/invertedidx/geo_test.go, line 494 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBec1QC7SiS3-kEvv_:-MHCGng83dfpO9BzuGht:b-u5wnzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo_test.go#L494)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Since `ok` is false, I would just not set these remaining values (since they won't be tested anyway)
</blockquote></details>

copy-paste and forgot to remove (datadriven tests are so much easier to fix). Done.

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54283)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/opt/invertedidx/geo.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBc8SgCLY7m_7TOGgC:-MHD7j3x66SWJ4cUgzwc:b-45p5l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L448)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The two callers of `extractInfoFromExpr` are different enough in this behavior that I thought it would reduce code readability. Specifically, `joinGeoIndexFromExpr` tries to reuse the original expression, and only does the construction when commuting or dealing with bbox operators. The expression there is not for pre-filtering since that will be constructed at execution time.

The invertedFilterer is doing this function construction always, so it naturally handles the bbox operations since it is constructing using the relationship (geo_test.go covers these bbox cases for pre-filtering). I guess we could do a similar lazy construction if we were certain that the `opt.ScalarExpr` expr param would not be mutated -- can I rely on that? 
</blockquote></details>

I think they should be the same (I don't think you always need to construct the function for the inverted filterer case). Optimizer expressions are immutable once they are constructed.
___
*[pkg/sql/opt/invertedidx/geo_test.go, line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBe8aCEWCmXj4_MyVa:-MHD8M8c7g709r_wBT2y:byf2oa9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo_test.go#L353)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

when the test fails these give nice multi-line output like the following
```
        	            	+function: st_intersects [type=bool]
        	            	+ ├── const: '0102000000020000000000000000000000000000000000000000000000000000000000000000000040' [type=geometry]
        	            	+ └── variable: unknown1:1 [type=geometry]
        	            	+
```

I like the completeness of the information. Would it be better if I broke the string literals into multiple lines in the code so it would look less big?
</blockquote></details>

Yea, maybe if you could make it more readable that would help. 

But we're also checking the full info in the data driven tests (so we do have complete info elsewhere), and I think it would be a pain to update this test if we change anything about the formatting (since we don't have the nice `--rewrite` option). If you want to include the full info, maybe it would be best to print each component separately or do something similar to what the `TestTryJoinGeoIndex` test is doing where it doesn't rely on the formatting staying the same.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54283)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[pkg/sql/opt/invertedidx/geo.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBc8SgCLY7m_7TOGgC:-MHSfmmj5hExTvVAUBNa:b-qaxfjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L448)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think they should be the same (I don't think you always need to construct the function for the inverted filterer case). Optimizer expressions are immutable once they are constructed.
</blockquote></details>

The inverted filterer has to construct since it only works with the functions in the `RelationshipReverseMap`.
I've extracted this into `makeExprFromRelationshipAndParams`.
___
*[pkg/sql/opt/invertedidx/geo_test.go, line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBe8aCEWCmXj4_MyVa:-MHSaNb4ErwovwfhH3VL:b-xfu2q7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo_test.go#L353)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea, maybe if you could make it more readable that would help. 

But we're also checking the full info in the data driven tests (so we do have complete info elsewhere), and I think it would be a pain to update this test if we change anything about the formatting (since we don't have the nice `--rewrite` option). If you want to include the full info, maybe it would be best to print each component separately or do something similar to what the `TestTryJoinGeoIndex` test is doing where it doesn't rely on the formatting staying the same.
</blockquote></details>

I've changed to do what TestTryJoinGeoIndex was doing -- it also made the expected output more easy to validate.

**Review by rytaft — COMMENTED** [review]
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54283)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/opt/invertedidx/geo.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBc8SgCLY7m_7TOGgC:-MHT0EZKBCugZn3rrivo:bujm0a7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L448)):*
> it only works with the functions in the RelationshipReverseMap

Why? Aren't we just using the `RelationshipMap` to get the `geoindex.RelationshipType` from the function anyway?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54283)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[pkg/sql/opt/invertedidx/geo.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-MHBc8SgCLY7m_7TOGgC:-MHT78dUCC6ovtB9fHUO:ba70oie) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee6ac32530ecc4223aca5aad3806de21fe4fcc6/pkg/sql/opt/invertedidx/geo.go#L448)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> it only works with the functions in the RelationshipReverseMap

Why? Aren't we just using the `RelationshipMap` to get the `geoindex.RelationshipType` from the function anyway?
</blockquote></details>

You are right. Fixed.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54283#-:-MHTIVAL4MOQJWjGKJil:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

**Comment by sumeerbhola** [comment]
I can't backport this without manually resolving conflicts due to changes in https://github.com/cockroachdb/cockroach/commit/0456df183970026e0a64472a72dbb5bc742122f4

Any opinion on whether to backport to 20.2 or not?

**Comment by rytaft** [comment]
How large is the performance improvement? If it's significant, probably worth backporting. Otherwise, maybe not.

**Pull request merged**
