### PR TITLE
server: no health alert warning on single node clusters

### LINKED ISSUE #26343: server: log spam from health alerts about underreplicated ranges on single node
Every few secs.
```
W180603 16:05:27.213849 167 server/node.go:802  [n1,summaries] health alerts detected: {Alerts:[{StoreID:1 Category:METRICS Description:ranges.underreplicated Value:26}]}
```
I think we already have some logic for single-node clusters that disables some other similar spam?

### PR DESCRIPTION
**Pull request by tbg**
Single node clusters require special UX since they are under-replicated,
and yet we don't want to spam the log.

Fixes #26343.

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]

**Comment by andreimatei** [comment]
Shouldn't we do something more specific to the under-replicated ranges alert, and leave others alone?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26416#-:-LEF_f7u46CEkmcm0bMM:bbqlu84)*

**Comment by tschottdorf** [comment]
@andreimatei somewhere down the line that would be preferrable, but I don't want to work on that right now.

bors r=bdarnell

**Comment by tschottdorf** [comment]
bors r=bdarnell

Not sure if bors means that the build timed out? It doesn't link to a build.

**Comment by knz** [comment]
The bors timed out because of all the nightly queued builds. I bumped your build to the top of the queue.

**Pull request merged**
