### PR TITLE
clusterversion: bump MinSupported to 24.1

### PR DESCRIPTION
**Pull request by RaduBerinde**
The change was more involved than it should have been because I
omitted to add `local-mixed-24.1` to the default configs when I
created the 24.2 versions. To avoid the same mistake in the future, we
update `TestLogicTestMixedVersionConfigs` to verify that the mixed
config is part of the default set.

Epic: REL-1163
Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm, just noticed one test issue

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-:-O3iSH-U2AI5XOjwZWAs:b-2jq000)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @celiala, @DrewKimball, @fqazi, and @RaduBerinde)

___
*[`pkg/sql/catalog/lease/count.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iQw1Y4fsUyNv5lOWR:-O3iQw1Y4fsUyNv5lOWS:bblpzdf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/catalog/lease/count.go#L119)):*
> ```Go
> 		if leasingDescIsSessionBased {
> 			syntheticDescriptors = append(syntheticDescriptors, systemschema.LeaseTable_V23_2())
> 			whereClauseIdx = append(whereClauseIdx, 0)
> ```

@fqazi looks like there was a bug in this logic. does this fix need to be backported to 24.1 or 24.2?
___
*[`pkg/sql/logictest/testdata/logic_test/upgrade_system_table_changes` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iRzrS9aDytv2EgNRs:-O3iRzrT9vvHJbGQCDOG:buz8nw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/logictest/testdata/logic_test/upgrade_system_table_changes#L1)):*
> ```
> # LogicTest: cockroach-go-testserver-24.1
> ```

this test file probably can be removed now
___
*[`pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant` line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iRivs246Uv0bbvBxO:-O3iRivs246Uv0bbvBxP:bc62zzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant#L198)):*
> ```
> /Table/110  90001
> /Table/111  90001
> /Table/112  14400
> ```

these results shouldn't change here. (it uses the `retry` directive, so eventually, `ttlSeconds` would change to `1` for these spans, but using `--rewrite` might have made this change overly eagerly.)

**Review by celiala — APPROVED** [review]
thank you! makes sense at a high-level :lgtm: 

> Reviewed 82 of 83 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-:-O3jA8H8CO4ymgHlkOtS:bxgv7qh)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @DrewKimball, @fqazi, and @RaduBerinde)

**Review by fqazi — APPROVED** [review]
:lgtm: 

> Reviewed 83 of 83 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-:-O3jS6-f8Xhgp6sNtF4_:bg7igkv)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @aadityasondhi, @DrewKimball, @RaduBerinde, and @rafiss)

___
*[`pkg/sql/catalog/lease/count.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iQw1Y4fsUyNv5lOWR:-O3jQPfa23trqpi5nIqY:bqv4zn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/catalog/lease/count.go#L119)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

@fqazi looks like there was a bug in this logic. does this fix need to be backported to 24.1 or 24.2?
</blockquote></details>

Yeah, we should backport it.

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-:-O3lN_Cc5zrY0UgrJ6P1:bz5mair)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @aadityasondhi, @celiala, @DrewKimball, @fqazi, and @rafiss)

___
*[`pkg/sql/catalog/lease/count.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iQw1Y4fsUyNv5lOWR:-O3lLoI905L5tZHVXhVF:bzhe8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/catalog/lease/count.go#L119)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yeah, we should backport it.
</blockquote></details>

I will let you do it (or file an issue for now) since I'm not familiar with this code.
___
*[`pkg/sql/logictest/testdata/logic_test/upgrade_system_table_changes` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iRzrS9aDytv2EgNRs:-O3lKlOvDT-VF_J7ZzJ_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/logictest/testdata/logic_test/upgrade_system_table_changes#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this test file probably can be removed now
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant` line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iRivs246Uv0bbvBxO:-O3lL6zS61T3rYPQnE4n:b-ixktvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant#L198)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

these results shouldn't change here. (it uses the `retry` directive, so eventually, `ttlSeconds` would change to `1` for these spans, but using `--rewrite` might have made this change overly eagerly.)
</blockquote></details>

Nice catch, thanks! Done. It looks like `--rewrite` waits for 2 seconds before running the query, I guess it is not enough here. Not sure what config I used to rewrite it

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128293)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[`pkg/sql/catalog/lease/count.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iQw1Y4fsUyNv5lOWR:-O3nA9tI9dlq0ZrmZXfs:b63cgu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/catalog/lease/count.go#L119)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I will let you do it (or file an issue for now) since I'm not familiar with this code.
</blockquote></details>

Actually this part of the change looks suspicious, why did we need to change this? Both conditions here use the old schema.

**Comment by RaduBerinde** [comment]
*[`pkg/sql/catalog/lease/count.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iQw1Y4fsUyNv5lOWR:-O3nEGWn5WgE_va6RNJN:b-qv6pk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/catalog/lease/count.go#L119)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Actually this part of the change looks suspicious, why did we need to change this? Both conditions here use the old schema.
</blockquote></details>

When a a synthetic descriptor is not used, we are using the schema of the table as it exists in the current cluster version, which is now >=24.1, no? In other words, in 24.1 we can only use the old schema with a synthetic 23.2 descriptor.

There seems to be an existing interop bug here between 24.2 and 24.1 that needs to be investigated. Although it would only show up if someone messes with `sql.catalog.experimental_use_session_based_leasing`.

Btw we really need to add the ability of having multiple names for a column, it would make renaming columns so much easier.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128293)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[`pkg/sql/catalog/lease/count.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iQw1Y4fsUyNv5lOWR:-O3nYXsJ3lDNZ7-FbD58:b-2vgxj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/catalog/lease/count.go#L119)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

When a a synthetic descriptor is not used, we are using the schema of the table as it exists in the current cluster version, which is now >=24.1, no? In other words, in 24.1 we can only use the old schema with a synthetic 23.2 descriptor.

There seems to be an existing interop bug here between 24.2 and 24.1 that needs to be investigated. Although it would only show up if someone messes with `sql.catalog.experimental_use_session_based_leasing`.

Btw we really need to add the ability of having multiple names for a column, it would make renaming columns so much easier.
</blockquote></details>

Right, so I think the reason we needed this change was because the system database descriptor in the 24.1 bootstrap reads as 23.2:

  {"database": {"id": 1, "modificationTime": {}, "name": "system", "privileges": {"ownerProto": "node", "users": [{"privileges": "2048", "userProto": "admin", "withGrantOption": "2048"}, {"privileges": "2048", "userProto": "root", "withGrantOption": "2048"}], "version": 3}, "systemDatabaseSchemaVersion": {"internal": 14, "majorVal": 23, "minorVal": 2}, "version": "1"}}

Let me figure out why that isn't right

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128293)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[`pkg/sql/catalog/lease/count.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iQw1Y4fsUyNv5lOWR:-O3ncUaD70NIzoDyU9HW:b-3nbs80) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/catalog/lease/count.go#L119)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Right, so I think the reason we needed this change was because the system database descriptor in the 24.1 bootstrap reads as 23.2:

  {"database": {"id": 1, "modificationTime": {}, "name": "system", "privileges": {"ownerProto": "node", "users": [{"privileges": "2048", "userProto": "admin", "withGrantOption": "2048"}, {"privileges": "2048", "userProto": "root", "withGrantOption": "2048"}], "version": 3}, "systemDatabaseSchemaVersion": {"internal": 14, "majorVal": 23, "minorVal": 2}, "version": "1"}}

Let me figure out why that isn't right
</blockquote></details>

@fqazi that version is wrong because the version wasn't bumped. previously we had to remember to do that manually, but in 24.2 and later there's an automatic process/test to do it (https://github.com/cockroachdb/cockroach/pull/123084)

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128293)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[`pkg/sql/catalog/lease/count.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iQw1Y4fsUyNv5lOWR:-O3ncyCI1lfo1h-ewzvb:b-yadxur) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/catalog/lease/count.go#L119)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

@fqazi that version is wrong because the version wasn't bumped. previously we had to remember to do that manually, but in 24.2 and later there's an automatic process/test to do it (https://github.com/cockroachdb/cockroach/pull/123084)
</blockquote></details>

Actually this makes sense, the version check against the system database descriptor has to always take into account the dev version. So, this starts to break after the version bump.

**Comment by RaduBerinde** [comment]
*[`pkg/sql/catalog/lease/count.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iQw1Y4fsUyNv5lOWR:-O3peYLh8-B_mtuURg8Y:bm4clvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/catalog/lease/count.go#L119)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Actually this makes sense, the version check against the system database descriptor has to always take into account the dev version. So, this starts to break after the version bump.
</blockquote></details>

The expected system database schema version for 24.1 is 23.2-14.  This is also the minimum supported schema version on master.

**Comment by RaduBerinde** [comment]
*[`pkg/sql/catalog/lease/count.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128293#-O3iQw1Y4fsUyNv5lOWR:-O3pf5tgEE0Fme0ARgHA:b-2end94) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94988779b752a8f87ccfbf5ccbaeb98e13f1fdc/pkg/sql/catalog/lease/count.go#L119)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The expected system database schema version for 24.1 is 23.2-14.  This is also the minimum supported schema version on master.
</blockquote></details>

(as instituted by this PR)

**Pull request merged**
