### PR TITLE
build: perform `bazel clean --expunge` on `make clean`

### PR DESCRIPTION
**Pull request by rickystewart**
Release note: None

### CODE REVIEW

**Review by rail — APPROVED** [review]
LGTM, :shipit:

**Review by ajwerner — APPROVED** [review]
:lgtm: thanks 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62009#-:-MVr04bF53zBhsG0kngB:brfqluw)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by rickystewart** [comment]
`bazel` isn't installed in every context from which we run `make clean`, so I put this behind a conditional.

**Pull request merged**
