### PR TITLE
logictest: make it possible to skip dropping databases, enable udf

### PR DESCRIPTION
**Pull request by ajwerner**
This will enable writing a configuration which does not drop databases to
unblock development on UDFs. The UDF work is somewhat blocked on the inability
to write logic tests. The logic tests today always drop the databases at the
end of the test. The DROP DATABASE logic to drop functions is not yet
implemented. With this change, implementers can make a new config which will
skip this step and, for now, use it for their tests.

The second commit then enables the UDF tests. 

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 2 of 2 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85430#-:-N8QMM3L0ilrREFIdCMd:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/sql/logictest/logictestbase/logictestbase.go` line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85430#-N8QLykQAhJDmVcgHLg-:-N8QLykQAhJDmVcgHLg0:b-mi2eoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5c09bae1f5d64108357e9f4fe47a1f305d8c54/pkg/sql/logictest/logictestbase/logictestbase.go#L462)):*
> ```Go
> 		Name:              "local-udf",
> 		NumNodes:          1,
> 		SkipDropDatabases: true,
> ```

Should we add the other options from `local`:

```
		OverrideDistSQLMode: "off",
		// local is the configuration where we run all tests which have bad
		// interactions with the default test tenant.
		DisableDefaultTestTenant: true,
```

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85430)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan and @mgartner)

___
*[`pkg/sql/logictest/logictestbase/logictestbase.go` line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85430#-N8QLykQAhJDmVcgHLg-:-N8QPQBZ-PCj69iKMlMK:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5c09bae1f5d64108357e9f4fe47a1f305d8c54/pkg/sql/logictest/logictestbase/logictestbase.go#L462)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should we add the other options from `local`:

```
		OverrideDistSQLMode: "off",
		// local is the configuration where we run all tests which have bad
		// interactions with the default test tenant.
		DisableDefaultTestTenant: true,
```

</blockquote></details>

Done.

**Review by chengxiong-ruan — APPROVED** [review]
many thanks.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
