### PR TITLE
cli: make unsafe-remove-dead-replicas work with encrypted stores

### PR DESCRIPTION
**Pull request by sumeerbhola**
Release justification: Low-risk bug fix to existing functionality.
Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69566#-:-MiMEZPrEFwbo_rBwogz:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by tbg — APPROVED** [review]

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69566#-:-MiMgIfc46GqmuSIEqzX:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by aayushshah15** [comment]
Do we have any interest in backporting this to 21.1?

**Pull request merged**
