### PR TITLE
ccl/sqlproxyccl: add private endpoints ACL support

### PR DESCRIPTION
**Pull request by jaylim-crl**
#### ccl/sqlproxyccl: remove the Load field from the Pod proto message 

The Load field has been deprecated for months, and is no longer being used
in production. The tenant directory implementation is no longer emitting pod
loads. This commit addresses an old TODO.

#### ccl/sqlproxyccl: add WatchTenants API to the directory server 

This commit adds a new WatchTenants API to the directory server interface. The
goal is for this API to stream tenant metadata change notifications. At the
same time, this commit adds a new Tenant proto message to represent tenant
fields instead. This would allow us to add more fields to the tenant object
(e.g. IP allowlist and private endpoint entries).

#### ccl/sqlproxyccl: add tenant metadata watcher to the directory cache 

This commits adds a new tenant metadata watcher mechanism to the directory
cache. This will be used to receive notifications about tenants being created,
modified, or deleted. Previously, we were only calling GetTenant once
throughout the lifetime of the tenant entry. In this new model, GetTenant is
only called if the tenant entry isn't valid.

#### ccl/sqlproxyccl: include PrivateEndpoints in the tenant proto message 

This commit includes two new fields in the tenant proto: ConnectivityType and
PrivateEndpoints. The first will be used to indicate how the cluster can be
accessed (i.e. public only, private only, or both), whereas the second will
be used to indicate which endpoints can access the cluster, assuming that the
cluster allows private connectivity.

A subsequent commit will implement the necessary ACLs.

#### ccl/sqlproxyccl: plumb context.Context into the CheckConnection API 

Previously, the CheckConnection API in the AccessController interface took in
a TimeSource object, and that seemed a little awkward. Given that the
timeSource field is only used by the denylist ACL, we will plumb this into
the denylis ACL. At the same time, we plumb context.Context into the
CheckConnection API. Once we add a new PrivateEndpoints ACL, that will have
to use a context.Context object for methods on the directory cache interface.

#### ccl/sqlproxyccl: add private endpoints ACL support 

This commit adds a new PrivateEndpoints ACL support to the access controller.
This ACL will only apply if the cluster allows private connectivity. If the
connection does not have an EndpointID, it is assumed to be a public
connection, and the ACL is a no-op, which is the current behavior. A
subsequent commit will extract the private endpoints from the PROXY header,
and populate the EndpointID for the connection.

#### ccl/sqlproxyccl: parse private endpoint IDs in the PROXY header 

This commit parses the private endpoint IDs within the PROXY header. Doing
this would also mean that the ACL for private endpoints will be enforced under
the right conditions. The parsing logic assumes that there can only be one
type of endpoint ID within the PROXY header (i.e. AWS, GCP, or Azure).

#### ccl/sqlproxyccl: add an interval poller for private endpoint updates 

There is a requirement of automatically disconnecting existing connections if
the ACL rules no longer match the connection's state. For the file-based ACLs,
we poll every 1 minute, read the file, and check on every single connection.

Here, we implement a similar mechanism for private endpoint updates. This is
reasonable for now as:
  1. Calls to LookupTenant are cached most of the time.
  2. This is only applied to existing connections, and a polling interval of
     1 minute isn't too bad.
  3. We are already iterating all the connections for the other types ACLs

That said, this approach isn't efficient and we're limited by the existing
design of AccessController. Checking all the connections each time the watch
ticks isn't ideal. In fact, we're checking three times here, one for each ACL.
The directory cache already knows which tenants were updated through
WatchTenants, and we can definitely do better here. A follow up TODO has been
added to refactor AccessController in a way that allows updates to be batched.
We should also only check connections only for tenants that have been updated.

Release note: None

Epic: none

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103070)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jaylim-crl, @JeffSwenson, and @pjtatlow)

___
*[`pkg/ccl/sqlproxyccl/tenant/directory_cache.go` line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQ8rkT1QrQOIGnLVcF:-NVQ7tml4kwk_xJPNIl7:b-mbsfws) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L33)):*
> ```Go
> 	// ID. If the tenant cannot be found, this will return a GRPC NotFound
> 	// error.
> 	LookupTenant(ctx context.Context, tenantID roachpb.TenantID) (*Tenant, error)
> ```

I thought the plan was to keep Tenant and Pod separate in `tenant.Directory`, but to combine them in the cache? What if we had a `Pods` field in `Tenant` (or maybe a separate `[]*Pod` return value), so that callers don't need to call twice? Or do we expect callers to always care only about one or the other?
___
*[`pkg/ccl/sqlproxyccl/tenant/directory_cache.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQrG3lAmLzCbqG-Rtr:-NVQrG3lAmLzCbqG-Rts:bvphf5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L70)):*
> ```Go
> // SkipTenantWatcher indicates that the directory cache should not run the
> // tenant watcher.
> func SkipTenantWatcher() func(opts *dirOptions) {
> ```

What caller will use this option?
___
*[`pkg/ccl/sqlproxyccl/tenant/directory_cache.go` line 499 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQu7n215EhjzbJh1M6:-NVQu7n215EhjzbJh1M7:bdux45k) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L499)):*
> ```Go
> // tenant's entry to reflect that change.
> func (d *directoryCache) updateTenantPodEntry(ctx context.Context, pod *Pod) {
> 	if pod == nil || pod.Addr == "" || pod.TenantID == 0 {
> ```

When can this be nil? Are you sure it doesn't indicate a bug in the caller if it's ever nil?
___
*[`pkg/ccl/sqlproxyccl/tenant/directory_cache.go` line 574 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQzvo-EqudFW8GfM5F:-NVQzvo-EqudFW8GfM5G:bi6hm6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L574)):*
> ```Go
> 				// them as stale allows LookupTenant to fetch a new right away
> 				// if needed.
> 				d.markAllEntriesInvalid()
> ```

Shouldn't we also do this in `watchPods`? Or is the idea that we'll just rely on `reportFailure` to invalidate pod metadata?
___
*[`pkg/ccl/sqlproxyccl/tenant/entry.go` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQz_Gk5WbkYRVVEESn:-NVQz_Gk5WbkYRVVEESo:b7tqsg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/entry.go#L43)):*
> ```Go
> 		syncutil.Mutex
> 
> 		// pods represents the tenant's SQL pods.
> ```

NIT: can you add a similar comment here that the pods slice is copy-on-write?
___
*[`pkg/ccl/sqlproxyccl/tenant/entry.go` line 251 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQx96h1Jw0fKfL2m1w:-NVQx96h1Jw0fKfL2m1x:bifg2br) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/entry.go#L251)):*
> ```Go
> 	// as nil). When that happens, the tenant watcher may race to update a
> 	// tenant, so we'd have to perform a nil check here.
> 	if (e.mu.valid && e.mu.tenant != nil && tenant.Version >= e.mu.tenant.Version) ||
> ```

NIT: Just a suggestion, feel free to disregard: the "if" logic here is a bit tricky, and also forces you to indent the "meat" of this method. I'd typically choose this instead:
```
// I try not to combine && and || in the same logic statement, b/c it's trickier to understand.
// It also makes comments harder to write, b/c it's often ambiguous which part(s) of the "if" they apply to.
// So I break apart the && into multiple lines like this:
if e.mu.valid {
  if e.mu.tenant == nil || tenant.Version < e.mu.tenant.Version {
    return
  }
}
// And now for the main logic of method, which does not need to be nested b/c we've checked the short-circuit conditions above.
```
___
*[`pkg/ccl/sqlproxyccl/tenantdirsvr/test_static_directory_svr.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQ7JcW0mgZ79cxMRJq:-NVQ7JcW0mgZ79cxMRJr:b-150qqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/98fb3f5a308f7d7a5730ea9eaac6f8a33078b6fe/pkg/ccl/sqlproxyccl/tenantdirsvr/test_static_directory_svr.go#L74)):*
> ```Go
> 		// eventListeners stores a list of listeners that are watching changes
> 		// to pods through WatchPods.
> 		eventListeners *list.List
> ```

NIT: I'd rename to `podEventListeners` now that we two different lists.

**Review by jaylim-crl — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-:-NVRi1nIEpn7_08wpRaX:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @JeffSwenson, and @pjtatlow)

___
*[`pkg/ccl/sqlproxyccl/tenant/directory_cache.go` line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQ8rkT1QrQOIGnLVcF:-NVRg7Zs5uH2yIUIZQ5g:brpbe2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L33)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I thought the plan was to keep Tenant and Pod separate in `tenant.Directory`, but to combine them in the cache? What if we had a `Pods` field in `Tenant` (or maybe a separate `[]*Pod` return value), so that callers don't need to call twice? Or do we expect callers to always care only about one or the other?
</blockquote></details>

If we wanted to combine them together, I think `tenant.Directory` should have combined APIs as well. We might need to look into what the interface would look like. At the moment, callers only care about one or the other. The ACL stuff only needs `LookupTenant`, and the connector needs `LookupTenantPods`. It is possible to refactor such that callers only use `LookupTenant` and `ReportFailure` if you feel strongly otherwise, though I would put it in a follow-up PR. I see two issues:
1. `LookupTenantPods` blocks until there is at least one RUNNING pod, which means that the new API will need to support both sync and async.
2. If the tenant gets invalidated during the cold start path, we may need to perform another Get, even if the connector doesn't need the data.

Due to the above, I'm leaning towards keeping the APIs as-is.
___
*[`pkg/ccl/sqlproxyccl/tenant/directory_cache.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQrG3lAmLzCbqG-Rtr:-NVRdijBATcWonYDyGGJ:b-9zflvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L70)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

What caller will use this option?
</blockquote></details>

I removed it as it's no longer being used. I had it originally for a test.
___
*[`pkg/ccl/sqlproxyccl/tenant/directory_cache.go` line 499 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQu7n215EhjzbJh1M6:-NVRfl0b-lwhQwS9pRvI:b697u9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L499)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

When can this be nil? Are you sure it doesn't indicate a bug in the caller if it's ever nil?
</blockquote></details>

I was somewhat defensive here to avoid panics. You're right that it's a bug in the caller (i.e. the tenant directory) if it's ever nil. I've removed the `nil` checks for both the tenant and pod watchers. That way, if there's a bug, the proxy will panic, and we should know about it.
___
*[`pkg/ccl/sqlproxyccl/tenant/directory_cache.go` line 574 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQzvo-EqudFW8GfM5F:-NVReRn5BpeOV6oMfwft:b-38mzit) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/directory_cache.go#L574)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Shouldn't we also do this in `watchPods`? Or is the idea that we'll just rely on `reportFailure` to invalidate pod metadata?
</blockquote></details>

The idea is correct: since we're relying on the `reportFailure` API, there's no need to explicitly invalidate all pods. To add on, it's likely that some of the pods metadata are valid, and we can continue routing to them without fetching a whole new list of pods. For example, if a tenant has 3 pods, and 1 gets deleted, there's still a 2/3 chance for a cache hit. The pods metadata should only be invalidated if necessary.
___
*[`pkg/ccl/sqlproxyccl/tenant/entry.go` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQz_Gk5WbkYRVVEESn:-NVRePQI2eK1YG8LOObI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/entry.go#L43)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: can you add a similar comment here that the pods slice is copy-on-write?
</blockquote></details>

Done.
___
*[`pkg/ccl/sqlproxyccl/tenant/entry.go` line 251 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQx96h1Jw0fKfL2m1w:-NVReFp05WeUGGMeiPvb:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd88a0d5c512f66e130a76c173eae34c564e209/pkg/ccl/sqlproxyccl/tenant/entry.go#L251)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Just a suggestion, feel free to disregard: the "if" logic here is a bit tricky, and also forces you to indent the "meat" of this method. I'd typically choose this instead:
```
// I try not to combine && and || in the same logic statement, b/c it's trickier to understand.
// It also makes comments harder to write, b/c it's often ambiguous which part(s) of the "if" they apply to.
// So I break apart the && into multiple lines like this:
if e.mu.valid {
  if e.mu.tenant == nil || tenant.Version < e.mu.tenant.Version {
    return
  }
}
// And now for the main logic of method, which does not need to be nested b/c we've checked the short-circuit conditions above.
```
</blockquote></details>

Good point. Done.
___
*[`pkg/ccl/sqlproxyccl/tenantdirsvr/test_static_directory_svr.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVQ7JcW0mgZ79cxMRJq:-NVRdpQfCndAcfQnjftW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98fb3f5a308f7d7a5730ea9eaac6f8a33078b6fe/pkg/ccl/sqlproxyccl/tenantdirsvr/test_static_directory_svr.go#L74)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: I'd rename to `podEventListeners` now that we two different lists.
</blockquote></details>

Done.

**Review by pjtatlow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103070)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jaylim-crl, and @JeffSwenson)

___
*[`pkg/ccl/sqlproxyccl/proxy_handler.go` line 326 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVV-He9BnPOjWafzeDf:-NVV-He9BnPOjWafzeDg:b-cshrtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3e1c2baaaa84c8f087d3a5a12eed82d8e7aba5/pkg/ccl/sqlproxyccl/proxy_handler.go#L326)):*
> ```Go
> 	if handler.RequireProxyProtocol {
> 		var err error
> 		endpointID, err = acl.FindPrivateEndpointID(incomingConn)
> ```

nit: it feels a little strange to have the `FindPrivateEndpointID` function in the `acl` package. I know the ACL is the only one who really cares about the private endpoint stuff, but it's been abstracted away from directly dealing with networking code until now.
___
*[`pkg/ccl/sqlproxyccl/acl/watcher.go` line 319 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVV0C159nJzgVcJ3W00:-NVV0C159nJzgVcJ3W01:b-f5m7ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3e1c2baaaa84c8f087d3a5a12eed82d8e7aba5/pkg/ccl/sqlproxyccl/acl/watcher.go#L319)):*
> ```Go
> 
> // pollAndUpdateChan sends the same access controller object into the returned
> // channel every pollingInterval.
> ```

We should clarify exactly why we're doing this.
___
*[`pkg/ccl/sqlproxyccl/acl/watcher.go` line 328 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVV071X7yo-mItNcx7v:-NVV071X7yo-mItNcx7w:b-mb2naa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3e1c2baaaa84c8f087d3a5a12eed82d8e7aba5/pkg/ccl/sqlproxyccl/acl/watcher.go#L328)):*
> ```Go
> 	result := make(chan AccessController)
> 	go func() {
> 		// TODO(ye): use notification via SIGHUP instead.
> ```

These comments don't apply to this code since it's not watching files.
___
*[`pkg/ccl/sqlproxyccl/tenant/entry.go` line 247 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVV9WTkEmzPowRLrRWE:-NVV9WTkEmzPowRLrRWF:bgvj0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3e1c2baaaa84c8f087d3a5a12eed82d8e7aba5/pkg/ccl/sqlproxyccl/tenant/entry.go#L247)):*
> ```Go
> 	// tenant, so we'd have to perform a nil check here.
> 	if e.mu.valid {
> 		if e.mu.tenant == nil || tenant.Version < e.mu.tenant.Version {
> ```

I am probably misunderstanding this, but if the tenantEntry had a nil tenant, why would we return here rather than using the incoming `*Tenant`?

**Review by jaylim-crl — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-:-NVVdmJj5HFcxH6UcKaB:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @JeffSwenson, and @pjtatlow)

___
*[`pkg/ccl/sqlproxyccl/proxy_handler.go` line 326 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVV-He9BnPOjWafzeDf:-NVVaVCsEb5SJq4vamcg:boz7xt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3e1c2baaaa84c8f087d3a5a12eed82d8e7aba5/pkg/ccl/sqlproxyccl/proxy_handler.go#L326)):*
<details><summary><i>Previously, pjtatlow (PJ Tatlow) wrote…</i></summary><blockquote>

nit: it feels a little strange to have the `FindPrivateEndpointID` function in the `acl` package. I know the ACL is the only one who really cares about the private endpoint stuff, but it's been abstracted away from directly dealing with networking code until now.
</blockquote></details>

I originally thought the same way as well, but I don't see a better place to put that. Putting it into `proxy_handler.go` would mean that it needs to know how to parse endpoint IDs (which isn't the concern of the proxy handler), which is why I put it in `private_endpoints.go` (though I'd imagine `acl/utils.go` could work too). How strongly do you feel about this, or do you have any suggestions?
___
*[`pkg/ccl/sqlproxyccl/acl/watcher.go` line 319 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVV0C159nJzgVcJ3W00:-NVV_kIq67vJLQNWgRov:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3e1c2baaaa84c8f087d3a5a12eed82d8e7aba5/pkg/ccl/sqlproxyccl/acl/watcher.go#L319)):*
<details><summary><i>Previously, pjtatlow (PJ Tatlow) wrote…</i></summary><blockquote>

We should clarify exactly why we're doing this.
</blockquote></details>

Done.
___
*[`pkg/ccl/sqlproxyccl/acl/watcher.go` line 328 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVV071X7yo-mItNcx7v:-NVV_kjiBoTNI8lte-NZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3e1c2baaaa84c8f087d3a5a12eed82d8e7aba5/pkg/ccl/sqlproxyccl/acl/watcher.go#L328)):*
<details><summary><i>Previously, pjtatlow (PJ Tatlow) wrote…</i></summary><blockquote>

These comments don't apply to this code since it's not watching files.
</blockquote></details>

Done.
___
*[`pkg/ccl/sqlproxyccl/tenant/entry.go` line 247 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVV9WTkEmzPowRLrRWE:-NVVdZyb3KdtoXbNok1y:b-1cft6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3e1c2baaaa84c8f087d3a5a12eed82d8e7aba5/pkg/ccl/sqlproxyccl/tenant/entry.go#L247)):*
<details><summary><i>Previously, pjtatlow (PJ Tatlow) wrote…</i></summary><blockquote>

I am probably misunderstanding this, but if the tenantEntry had a nil tenant, why would we return here rather than using the incoming `*Tenant`?
</blockquote></details>

Good point. Done. If `e.mu.valid=true`, and `e.mu.tenant=nil`, it must be the case that the entry was populated when the tenant wasn't created, or the API server is down. In that case, we would want to replace the tenant with a newer version.

**Review by pjtatlow — APPROVED** [review]
LGTM!

> Reviewed 2 of 5 files at r2, 1 of 8 files at r10, 1 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-:-NVVySIQCX6SBlCzxI8n:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @JeffSwenson)

___
*[`pkg/ccl/sqlproxyccl/proxy_handler.go` line 326 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/103070#-NVV-He9BnPOjWafzeDf:-NVVyJ3mCktoXNJEGzEu:b-plk657) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3e1c2baaaa84c8f087d3a5a12eed82d8e7aba5/pkg/ccl/sqlproxyccl/proxy_handler.go#L326)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

I originally thought the same way as well, but I don't see a better place to put that. Putting it into `proxy_handler.go` would mean that it needs to know how to parse endpoint IDs (which isn't the concern of the proxy handler), which is why I put it in `private_endpoints.go` (though I'd imagine `acl/utils.go` could work too). How strongly do you feel about this, or do you have any suggestions?
</blockquote></details>

I don't have a strong opinion, this is probably a good place for it. Just seemed weird at first haha.

**Comment by jaylim-crl** [comment]
TFTR! I'll follow up with a change to include `clusterName` in `LookupTenant` as discussed.

bors r=pjtatlow

**Comment by jaylim-crl** [comment]
Hm, looks like `TestPrivateEndpointsACL` is failing.

bors r-

**Comment by jaylim-crl** [comment]
bors r=pjtatlow

**Pull request merged**
