### PR TITLE
roachpb: Change RangeDescriptor.StickyBit and ReplicaDescriptor.Type to nullable

### LINKED ISSUE #36983: roachtest: tpcc/mixed-headroom/n5cpu16 failed
SHA: https://github.com/cockroachdb/cockroach/commits/df200cbf3f407dbf349aa601ff9036b4dff88e83

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=tpcc/mixed-headroom/n5cpu16 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1252822&tab=buildLog

```
The test failed on release-2.1:
	cluster.go:1329,tpcc.go:168,cluster.go:1667,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1252822-tpcc-mixed-headroom-n5cpu16:5 -- ./workload run tpcc --warehouses=909 --histograms=logs/stats.json  --ramp=5m0s --duration=2h0m0s {pgurl:1-4} returned:
		stderr:
		
		stdout:
		 60.8     79.7     96.5    117.4 newOrder
		     33s        0           19.0           17.0     11.5     17.8     19.9     19.9 orderStatus
		     33s        0          201.8          170.0     37.7     71.3     83.9    104.9 payment
		     33s        0           16.0           17.6     83.9    570.4    570.4    570.4 stockLevel
		     34s        0           22.0           16.1     75.5    121.6    142.6    142.6 delivery
		     34s        0          201.8           92.8     67.1    109.1    113.2    117.4 newOrder
		     34s        0           24.0           17.2     12.1     26.2     31.5     31.5 orderStatus
		     34s        0          205.8          171.0     39.8     67.1     79.7     92.3 payment
		     34s        0           19.0           17.6     92.3    520.1    570.4    570.4 stockLevel
		Error: error in payment: select by customer idfail: ERROR: Expected "ROLLBACK TO SAVEPOINT COCKROACH_RESTART": current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)
		Error:  exit status 1
		: exit status 1
	cluster.go:1688,tpcc.go:178,tpcc.go:267,test.go:1237: Goexit() was called

```

### LINKED ISSUE #38471: storage: RangeDescriptor incompatibility with previous versions
#38147 and #38004 both introduced an incompatibility with old versions of cockroach where RangeDescriptors could no longer be updated. This is because we were using CPut with a proto as the expected value, which is A Bad Idea (see #38302 for why). #38302 tried to fix this by CPut'ing bytes when updating RangeDescriptors. It fixed the new node reading RangeDescriptor written by an old node, but didn't fix an old node reading a RangeDescriptor written by a new node. This means we can't run mixed clusters with old versions of cockroach (splits, replica addition, replica movement, etc are broken).

This is blocking the 19.2.0-alpha.20190701 release

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
On a mixed version cluster, only having #38302 does not guarantee backwards compatibility for non-nullable fields in RangeDescriptor. Suppose the replicas of a range are of mixed version and the current
leaseholder of the range is on newest version. If the leaseholder splits that range and writes to the non-nullable fields in RangeDescriptor and the leaseholder transfers to a node on an older version without #38302, then all CPuts would fail on that node.

We must guarantee that #38302 is on all nodes before making the fields in RangeDescriptor non-nullable.

Fixes #36983.
Fixes #38471.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 12 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/storage/replica_command.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38465#-LiKpjIaA8TChTh5zWd3:-LiKpjIaA8TChTh5zWd4:b-73qnol) ([raw file](https://github.com/cockroachdb/cockroach/blob/2261df9c4f25a15e37e02441d61043a02f8a5226/pkg/storage/replica_command.go#L188)):*
> ```Go
> 	// it to hlc.Timestamp{}. This check ensures that CPuts would not fail on
> 	// older versions.
> 	stickyBitEnabled := r.store.ClusterSettings().Version.IsActive(cluster.VersionStickyBit)
> ```

We will only ever set the sticky bit on an `AdminSplitRequest` to a value that's not its zero value if this is already true, right? In that case, I think we should replace this with a check that the expiration time in the request is not the zero value. The reason for this is that nodes can learn that a cluster version is active at different times and we want to avoid the case where one node starts supplying an expiration value in its `AdminSplitRequest`, expecting this to be respected, while the node that evaluates the request (which hasn't yet learned about the new cluster version) is still dropping the values on the floor.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/storage/replica_command.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38465#-LiKpjIaA8TChTh5zWd3:-LiKtN-f5cpO_ZZkGUVP:bauolku) ([raw file](https://github.com/cockroachdb/cockroach/blob/2261df9c4f25a15e37e02441d61043a02f8a5226/pkg/storage/replica_command.go#L188)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We will only ever set the sticky bit on an `AdminSplitRequest` to a value that's not its zero value if this is already true, right? In that case, I think we should replace this with a check that the expiration time in the request is not the zero value. The reason for this is that nodes can learn that a cluster version is active at different times and we want to avoid the case where one node starts supplying an expiration value in its `AdminSplitRequest`, expecting this to be respected, while the node that evaluates the request (which hasn't yet learned about the new cluster version) is still dropping the values on the floor.
</blockquote></details>

Thanks for the catch!

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 7 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/roachpb/metadata_replicas.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38465#-LiKwNRw36sSaxUD3rQJ:-LiKwNRw36sSaxUD3rQK:b-22oi26) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c534017fd55f9beb92bf01708f4f136c01f4fda/pkg/roachpb/metadata_replicas.go#L49)):*
> ```Go
> 	// Note that the wrapped replicas are sorted first by type.
> 	for i := range d.wrapped {
> 		if d.wrapped[i].Type != nil && *d.wrapped[i].Type == ReplicaType_LEARNER {
> ```

Do you think it would be worth creating and using a method like:
```
func (rt *ReplicaType) Deref() ReplicaType {
    if rt == nil {
        return ReplicaType_VOTER
    }
    return *rt
}
```

It would belong in `pkg/roachpb/metadata.go` if we did.
___
*[pkg/roachpb/metadata_replicas_test.go, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38465#-LiKwnzpBbSDOtlXIlj7:-LiKwnzpBbSDOtlXIlj8:b-i3ki36) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c534017fd55f9beb92bf01708f4f136c01f4fda/pkg/roachpb/metadata_replicas_test.go#L26)):*
> ```Go
> 	tests := [][]ReplicaDescriptor{
> 		{},
> 		{{Type: newReplicaType(ReplicaType_VOTER)}},
> ```

nit: I'd pull these two allocs up and use them in each test case. Something like:
```
func TestVotersLearnersAll(t *testing.T) {
    voter := newReplicaType(ReplicaType_VOTER)
    learner := newReplicaType(ReplicaType_LEARNER)
    ...
```

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/roachpb/metadata_replicas.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38465#-LiKwNRw36sSaxUD3rQJ:-LiKzxFj7CFsTlL4P_qB:bpwhw9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c534017fd55f9beb92bf01708f4f136c01f4fda/pkg/roachpb/metadata_replicas.go#L49)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think it would be worth creating and using a method like:
```
func (rt *ReplicaType) Deref() ReplicaType {
    if rt == nil {
        return ReplicaType_VOTER
    }
    return *rt
}
```

It would belong in `pkg/roachpb/metadata.go` if we did.
</blockquote></details>

Done. I've added a method to `ReplicaDescriptor` similar to what we do with `Generation` for `RangeDescriptor`.

**Review by nvb — APPROVED** [review]
:lgtm: thanks for turning this around so quickly.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38465#-:-LiL13Ip5YC-iKSnhNei:b-krp7n7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

**Comment by jeffrey-xiao** [comment]
Was inspired by the `GetType` change, so I also added `GetStickyBit`.

**Review by nvb — APPROVED** [review]
Still :lgtm:

> Reviewed 7 of 14 files at r5, 1 of 1 files at r6, 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38465#-:-LiL373LARFPtVXoy_EM:b-2pygyf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

**Review by danhhz — COMMENTED** [review]
ReplicaDescriptor.Type stuff lgtm. Thanks for the fix!

**Comment by jeffrey-xiao** [comment]
Seems to be a flake in TeamCity?
bors r+

**Comment by jeffrey-xiao** [comment]
Flake: #38458, #38468 

bors r+

**Pull request merged**
