### PR TITLE
workload/schemachanger: re-enable the schema changer workload

### PR DESCRIPTION
**Pull request by fqazi**
Previously the schema changer workload was disabled because of two intermittent issues:

1.  The workload itself had an issue due to a recent refactor that did not properly detect/handle potential execution errors.  While the set of errors was generated it was never used properly in some cases after a recent refactor
2. Some scenarios involving inserts could fail binding OID's inside the resolveOID code path, specifically this code path does not properly handle dropped descriptors. These changes enforces the old behaviour where the resolution should just *fail*.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
It's still flakey due to at least two other issues I saw:

1) Something about max command size for inverted index entries
2) Integer overflows due to expressions

The second one popped up more regularly. Consider you have a table:

`CREATE TABLE (i INT, INDEX ((i+i));` If `i` is large enough that `2*i` overflows int64, there's a problem. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88085#-:-NCMeR0nBx6evArp3Nhv:be0sku)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by fqazi** [comment]
@ajwerner  For (2) We did have generated expression validation (see validateGeneratedExpressionsForInsert), but some of those errors were in the potential error sets. Let me re-run it a few more times to confirm to make sure it's fully squashed.

**Comment by fqazi** [comment]
I'll see if I can reproduce (1) and address that as well in a separate commit

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88085#-:-NCXwxpN6rhNgvsA6XgR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by fqazi** [comment]
@ajwerner TFTR!

bors r+

**Comment by fqazi** [comment]
@rafiss Yes, it will be merged into master separately.

**Pull request merged**
