### PR TITLE
storage: add additional trace statements for GC; fix counting

### LINKED ISSUE #129419: storage: count of range keys collected by MVCCGarbageCollectRangeKeys is always zero
When garbage collecting range keys, [`MVCCGarbageCollectRangeKeys` will emit a trace line](https://github.com/cockroachdb/cockroach/blame/a430f05f70141e932180a69d153809b37568b062/pkg/storage/mvcc.go#L6599-L6601) indicating the number of keys deleted. 

The `count` variable is never updated, and thus will always log `0`.

As part of this fix, we should also improve the error handling, by capturing / logging any errors encountered along the way that could explain why a range key wasn't cleared.

Found in https://github.com/cockroachlabs/support/issues/3062.

Jira issue: CRDB-41534

Epic CRDB-37617

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, when performing a GC of point or range keys, we log a trace statement at completion of the method. If an error is encountered, it would be useful to surface it.

Update the  point and range key GC methods to print any error encountered during the GC.

Improve the trace statements for both the point and range key methods, indicating the number of incoming point / range keys, and the number of resulting point / range keys that were removed, along with the time taken to perform the GC.

Add additional trace statements for the range key method, logging the range key fragments that were removed.

Fix the `count` in `MVCCGarbageCollectRangeKeys`, capturing the count of range key fragments that were GC'd.

Fix #129419.

Release note: None.

Epic: None.

### CODE REVIEW

**Comment by nicktrav** [comment]
This is a re-do of #129375.

**Comment by nicktrav** [comment]
This is what it looks like with a manual enqueue of a GC following an index drop - clearing the rangekeyset.

Screenshot 2024-08-22 at 11 41 46 AM

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129500#-:-O4xKGHN9hrRIG5cmGwB:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @itsbilal, and @tbg)

**Comment by nicktrav** [comment]
TFTR!

bors r=RaduBerinde

**Pull request merged**
