### PR TITLE
colexec: add mechanism to fallback to disk on OOM error

### LINKED ISSUE #42408: colexec: implement a fallback mechanism for buffering operators
Once we implement #38412, we'll have the option of handling a budget exceeded error. The missing link between noticing that a buffering operator is out of memory and using disk is having the mechanism that performs the transition. We can work on this link independently of having the disk strategies ready.

One idea would be to create a fallback-operator that is always created with an upstream buffering operator. This fallback-aware operator would catch a vectorized panic and handle it depending on whether it is an out of memory error or not. In the initial implementation, we could just propagate this error up. This operator might then delegate to a disk-aware version of the buffering operator, it would be interesting to think about how that would look like.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: add mechanism to fallback to disk on OOM error**

This commit adds the infrastructure to be able to fallback from the
in-memory buffering operator to a disk-backed one. A new interface
'bufferingInMemoryOperator' is introduced that allows for exporting the
already buffered tuples from the in-memory operator to the disk-backed
implementation. The commit also introduces 'diskSpiller' operator that
performs the fallback by catching OOM errors and facilitating the
transfer of already buffered tuples and continuing to exhaust the input
via a newly created 'bufferExportingOperator' (which is responsible for
providing the continuous stream of batches from the two sources).

diskSpiller assumes that if an OOM error is occurred during
initialization, then it cannot fallback and bails on the query.

Here is the diagram of the components involved:

        -------------  input  -----------
       |                ||                | (2nd src)
       |                ||   (1st src)    ↓
       |            ----||---> bufferExportingOperator
       ↓           |    ||                |
    inMemoryOp ----     ||                ↓
       |                ||           diskBackedOp
       |                ||                |
       |                ↓↓                |
        ---------> disk spiller <--------
                        ||
                        ||
                        ↓↓
                      output

Fixes: #42408.

Release note: None

**execinfra: modify OpNode interface**

This commit adds 'verbose' argument to two methods of OpNode interface.
The only operator that currently uses it is diskSpiller which in
non-verbose setting hides its side chains.

Release note: None

**colexec: remove assertions from window functions that are no longer true**

We recently merged a change to use a schema-less zero-length batch to
indicate that an operator is done emitting batches. Previously, window
functions had an assertion that always checked that there are enough
columns so that the window function operator could write into it. It no
longer holds for coldata.ZeroBatch, so it was removed.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
Great to see this

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-:-Lv60HOD9l8oJGfJK_zt:b-bnpd1k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/disk_spiller.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv5v96117ek3evBwymQ:-Lv5v96117ek3evBwymR:b-k9rzav) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/colexec/disk_spiller.go#L97)):*
> ```Go
> 		input:        input,
> 		inMemoryOp:   inMemoryOp,
> 		diskBackedOp: diskBackedOpConstructor(diskBackedOpInput),
> ```

This constructor is a bit confusing, maybe `newOneInputDiskSpiller` deserves a comment?
___
*[pkg/sql/colexec/disk_spiller.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv5YeUP5dRg39G4o4t9:-Lv5YeUP5dRg39G4o4tA:b8xn0p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/colexec/disk_spiller.go#L107)):*
> ```Go
> 	d.initialized = true
> 	// It is possible that Init() calls below will hit an out of memory error,
> 	// but we decide to bail on this query, so we do not catch internal panics.
> ```

This would really only be when we have a huge number of queries running where simply allocating an output batch (which I assume is the largest allocation that happens in `Init`, right?) results in an OOM. I wonder if admission control would kick in before then. Don't think we should worry too much about this.
___
*[pkg/sql/colexec/disk_spiller.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv5ZMSi06tSWxQhY7Jw:-Lv5ZMSi06tSWxQhY7Jx:bnp76tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/colexec/disk_spiller.go#L114)):*
> ```Go
> func (d *oneInputDiskSpiller) Next(ctx context.Context) coldata.Batch {
> 	var batch coldata.Batch
> 	if !d.spilled {
> ```

nit:
```
if d.spilled {
    return d.diskBackedOp.Next(ctx)
}
<if not spilled logic>
```
___
*[pkg/sql/colexec/disk_spiller.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv5zzu4-JDA61y1fF1s:-Lv5zzu4-JDA61y1fF1t:bqagj1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/colexec/disk_spiller.go#L190)):*
> ```Go
> 		return b.secondSource.Next(ctx)
> 	}
> 	batch := b.firstSource.ExportBuffered(b.allocator)
> ```

Why is an allocator needed here?
___
*[pkg/sql/colexec/sort.go, line 424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv6-AqKB6Jx3hBIQ9iy:-Lv6-AqKB6Jx3hBIQ9iz:bwks0sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/colexec/sort.go#L424)):*
> ```Go
> 	for j := 0; j < len(p.inputTypes); j++ {
> 		// We're using the provided Allocator.
> 		allocator.Copy(
> ```

Related to my question about the use of the allocator above, I don't think we want to copy anything here. In the case of the sorter, could we not just return batch by batch what we've buffered and have the external sort operator simply store those on disk? Since the output is buffered, won't it always be the case that the batch returned is safe (i.e. never modified again after the next call to `ExportBuffered`). Not sure if this applies to other cases.
___
*[pkg/sql/logictest/testdata/logic_test/tpch_vec, line 1004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv5W2Ga1ZKsAom-wGtO:-Lv5W2Ga1ZKsAom-wGtP:b-ve0qhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/logictest/testdata/logic_test/tpch_vec#L1004)):*
> ```
> │
> └ Node 1
>   └ *colexec.oneInputDiskSpiller
> ```

Should we put this behind the verbose flag and just print the `sortOp` normally in this case? It might get confusing if not.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42851)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/disk_spiller.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv5v96117ek3evBwymQ:-Lv6wB8hDjzhYq7Q5izO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/colexec/disk_spiller.go#L97)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This constructor is a bit confusing, maybe `newOneInputDiskSpiller` deserves a comment?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/disk_spiller.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv5YeUP5dRg39G4o4t9:-Lv6wGOd5iP1HZeBqkN_:btvjna6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/colexec/disk_spiller.go#L107)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This would really only be when we have a huge number of queries running where simply allocating an output batch (which I assume is the largest allocation that happens in `Init`, right?) results in an OOM. I wonder if admission control would kick in before then. Don't think we should worry too much about this.
</blockquote></details>

Yes, that's possible when we have many queries, and yes, instantiating an output batch should be the largest allocation (some operators also have like intermediate batch that could also get allocated). I agree that we don't need to worry about it.
___
*[pkg/sql/colexec/disk_spiller.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv5ZMSi06tSWxQhY7Jw:-Lv6yRyN0Xr2yIHygphp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/colexec/disk_spiller.go#L114)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit:
```
if d.spilled {
    return d.diskBackedOp.Next(ctx)
}
<if not spilled logic>
```
</blockquote></details>

Done.
___
*[pkg/sql/colexec/disk_spiller.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv5zzu4-JDA61y1fF1s:-Lv71Ye1Eaa3ZRSavJ0y:bf09o6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/colexec/disk_spiller.go#L190)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is an allocator needed here?
</blockquote></details>

Left a TODO.
___
*[pkg/sql/colexec/sort.go, line 424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv6-AqKB6Jx3hBIQ9iy:-Lv720503znCAJjfLlSw:bj2aluq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/colexec/sort.go#L424)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Related to my question about the use of the allocator above, I don't think we want to copy anything here. In the case of the sorter, could we not just return batch by batch what we've buffered and have the external sort operator simply store those on disk? Since the output is buffered, won't it always be the case that the batch returned is safe (i.e. never modified again after the next call to `ExportBuffered`). Not sure if this applies to other cases.
</blockquote></details>

In case of sorter, with the current code it is not possible because the buffered tuples are stored by `allSpooler` in long vectors, and it exposes them all at once, so we need to modify the spooler interface. I agree that copying is expensive and probably can be avoided here, but I'd argue it is a part of a separate PR.
___
*[pkg/sql/logictest/testdata/logic_test/tpch_vec, line 1004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-Lv5W2Ga1ZKsAom-wGtO:-Lv76YPd1zP4qjFUn3Kv:b5x5wk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67adf075e7dfcf766263814fd7f595deb6bedad/pkg/sql/logictest/testdata/logic_test/tpch_vec#L1004)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we put this behind the verbose flag and just print the `sortOp` normally in this case? It might get confusing if not.
</blockquote></details>

In order to fully hide the side chains we will need to modify `execinfra.OpNode` interface so that `ChildCount` method took in a boolean for whether `verbose` is used. I switched the order of children and left TODOs to address that.

On a second thought, it seems like a mechanical change, so I added a second commit to fix this.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r2, 20 of 20 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42851#-:-LvFOyhaCufdroPolh7w:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
