### PR TITLE
distsql: add stat collection to mergeJoiner

### PR DESCRIPTION
**Pull request by asubiotto**
Addresses #25743

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm:

I was wondering why this doesn't have any memory stats. I looked into it and the reason is that we don't keep track of allocations in the merge joiner. We should fix that as well. The culprit is the `streamGroupAccumulator`, which allocates slices for groups as well as copies EncDatumRows.

I think the solution might be to make `EncDatumRowAlloc` itself track memory - that would probably wipe out a lot of missing memory allocation in one fell swoop.

---

Reviewed 5 of 5 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26860#-:-LFT4K-Z-5Ly2w2l13s6:bm9bl1x)*

**Comment by asubiotto** [comment]
Good point, will file an issue
bors r+

**Comment by jordanlewis** [comment]
Hmm I think something's going wrong with this - take a look at the diagram that got generated from a merge join in TPCH (`explain analyze(distsql) select count(*) from lineitem@l_sk join supplier@s_sk on l_suppkey = s_suppkey`):

image


https://cockroachdb.github.io/distsqlplan/decode.html?eJzUU91um0wQvf-eAs1VoiBnf4A1SJ9E26u0il3lR72oUETMlKACa-0uaqLK714BqQzEJiZWK_UOZufMnHNm5ieUMsFFXKCG4CtQsIGBDQ5ENqyVXKHWUtVPbeJF8ggBsSEr15VpwyYzOUIAVSlVggoTsCFBE2d5_R5tIhtWUiEE29R3aaowjY1U56KXDde3l3cXi5uTkJ6CDUr-0JbCOAmsmpQ2cZ5bJiswsOYzSh1HUA02FPGjVWAh1ZNVaUwCixLrU_Yeoo0NsjLPTKOmQIoQuBu7o4Z21OzgehPf53iFcYLqnPTJ5nf6e5hnJWYGiz5dLohPyHxAms_mrusRVpNeViawQj4gue17_2Q9xPqh3zGk0Bj6LITuFbKts2soENKzuvGbhneJKsWPMitRnfOBIfjNnIT07PR_laUP7SfYTdjqmEN-x7rekNqUBjZMbYMvchsDF7LEvXPmU-bc2Um3r-rD8nZxc3e1_HJ9MlhKTggVrj-YspgJSlwu3rKaTo8yO3w16cGryZjPGBED0mzmOtzxxZ9ZzQlCWL-sroXoar3OM1R9IZQQQgYynJnP3WIrgh4lgu0V8Zfuy_mH7uuVGXfuyzv0vpjv-47rvbgvzxecH39eZJzxFeq1LDUORra7MqlHiUmK7XZoWakVflZy1bRpf5cNrgkkqE37Om9_Lsr2qSbYBdMhmHbBrAem08DeOJiN0ubjtPkomIx3do7RPA5-RbM7oTObBvbGwd6oYWLcbTHJ7Wjz368AAAD__zrjOKU=

**Comment by asubiotto** [comment]
Submitted a fix: #26909

**Pull request merged**
