### PR TITLE
ts: Query rewrite part 2

### PR DESCRIPTION
**Pull request by mrtracy**
Two commits, completing the rewrite of the query logic.

+ First commit adds support for "incomplete sample" filtering into the test model and the new query logic, adds tests for "incomplete sample" logic, swaps model tests to use the new query logic exclusively, and adds additional testing for downsampling in the new query logic.
+ Second commit swaps over the TS server to begin using the new query logic and completely removes the old query logic.

### CODE REVIEW

**Comment by mrtracy** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ts/query.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25587#-LCevjtB5zKVXW2fBKJQ:-LD2PVWt5_ivobbm1r2Z:btqqu58) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cec0f59af48c381c5661db09d95159533cdead8/pkg/ts/query.go#L1)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I assume this is just renamed from `query_new.go` without any interesting changes. 
</blockquote></details>

Correct!

---

*[pkg/ts/query_test.go, line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25587#-LCevAt25Mkewe0oBOBS:-LD2PnDK0YXJAYZUqEkr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f967c098375aba81f51f9543444f1044f03b5532/pkg/ts/query_test.go#L579)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove this or complete it (Our lint policy doesn't require comments on test functions)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25587)*

**Comment by mrtracy** [comment]
@bdarnell Through a test failure, I found a rather obvious bug with the way I was pre-allocating space for the result; the result space is no longer pre-allocated, and as a result I have changed the way that the memory monitor grows (moved closer to the allocation point). This might be different enough that you want to take another look.

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25587#-:-LD7Vn5YAIGvWuudStrF:bb6ywmx)*

**Pull request merged**
