### PR TITLE
logictest: swap directives with default config when possible

### PR DESCRIPTION
**Pull request by asubiotto**
A while back, we added the ability to run logic tests without a directive,
which would run all default configs.

Some tests still specified explicit configs even though they could run without
a problem with all default configs. Even though it takes more time, running
with all default configs is preferable, since developers rely on the widespread
usage of the default config for good test coverage of new features.

Additionally, all files affected can also be run in a multitenant configuration
using 3node-tenant. So that TestTenantLogic may run these files, this commit
adds a blocklist directive with an issue number where appropriate for any tests
that fail in 3node-tenant that previously had explicit directives.

Release note: None (testing change)

Addresses #52410

### CODE REVIEW

**Comment by asubiotto** [comment]
Hmm, we probably do not want to do this for the `5node-configs`. @yuzefovich what's your opinion?

**Review by yuzefovich — COMMENTED** [review]
I'm worried that we'll be hitting 30 minutes timeout more often with this change. In particular, `fk` file is huge, so I think it deserves special consideration about which configs to use when running it (all others are quite small, so all default configs should be ok in there).

I think if the file has explicit logic to split and relocate ranges assuming 5 node clusters, then those should not be updated.

> Reviewed 35 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-:-MEYHhCvAKOn0WU4qa6f:bjoj8bi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @nvanbenschoten)

___
*[pkg/sql/logictest/testdata/logic_test/edge, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-MEYGv2_5sKVd4wCiN73:-MEYGv2aCRlNSWB5BtQg:b-x55zsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/44c362600dbed9d58be8daf64558543745698736/pkg/sql/logictest/testdata/logic_test/edge#L2)):*
> ```
> # LogicTest: local-vec-off fakedist-vec-off
> # TODO(yuzefovich): run with all default configs once #40354 is resolved.
> ```

Is this no longer an issue? I wonder what's changed because the issue is still present, I think.
___
*[pkg/sql/logictest/testdata/logic_test/window, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-MEYHUCW1KRnyF-msG1s:-MEYHUCW1KRnyF-msG1t:b-g6gg4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/44c362600dbed9d58be8daf64558543745698736/pkg/sql/logictest/testdata/logic_test/window#L1)):*
> ```
> # LogicTest: default-configs 5node-default-configs
> ```

By deleting this line we will no longer run this test on 5node configs. However, this file doesn't split and relocate ranges, so probably it's ok.

**Review by asubiotto — COMMENTED** [review]
> I'm worried that we'll be hitting 30 minutes timeout more often with this change. In particular, fk file is huge, so I think it deserves special consideration about which configs to use when running it (all others are quite small, so all default configs should be ok in there).

I'm not worried. I prefer running more tests with the default config than trying to stay under a timeout. If the runtime of the logic tests is a problem then I think that should be dealt with separately. The reasons I'm not worried about it is:
1) We removed `3node-tenant` from the default config, removing one run from all files run with the default config so we have breathing space.
2) Pretty soon we'll be reducing the number of default configs (at least the `auto` and `auto-disk` configs).
3) If test runtime does become a problem and we want to solve it by running fewer tests, I prefer a policy of exclusion (i.e. blocking configs we don't see much use in running) to get automatic coverage of additions to the default configs.

I'll take a look at the `TestLogic` runtime on a green run of this PR.

> I think if the file has explicit logic to split and relocate ranges assuming 5 node clusters, then those should not be updated.

I ran all these files with the new configurations and automatically updated the configs if it ran successfully. I think that these kinds of tests would fail with a non-5node config, so shouldn't be updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-:-MEbAIAB-d_ehN9PvwQf:b-h3zl4g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-MEbAT5l4RXS5qFVXuz3:-MEbAT5l4RXS5qFVXuz4:b-65p3wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/44c362600dbed9d58be8daf64558543745698736/pkg/sql/logictest/testdata/logic_test/distsql_join#L1)):*
> ```
> # LogicTest: 5node-default-configs
> ```

What do you think of this removal @yuzefovich? Was there any good reason to use a `5node` config here?
___
*[pkg/sql/logictest/testdata/logic_test/edge, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-MEYGv2_5sKVd4wCiN73:-MEbA_qCCu0gP6mR6wEF:b-wkujxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/44c362600dbed9d58be8daf64558543745698736/pkg/sql/logictest/testdata/logic_test/edge#L2)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Is this no longer an issue? I wonder what's changed because the issue is still present, I think.
</blockquote></details>

Yep, the test ran successfully. Maybe post-processing delegation to the row engine?
___
*[pkg/sql/logictest/testdata/logic_test/interleaved_join, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-MEbB38i9HFicFc9emKX:-MEbB38i9HFicFc9emKY:b-7zkaz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/44c362600dbed9d58be8daf64558543745698736/pkg/sql/logictest/testdata/logic_test/interleaved_join#L1)):*
> ```
> # LogicTest: !local-spec-planning(47473) !fakedist-spec-planning(47473)
> ```

@yuzefovich OOC what was the reason for blocking this test?
___
*[pkg/sql/logictest/testdata/logic_test/window, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-MEYHUCW1KRnyF-msG1s:-MEbBIGx1CpQvqM4vSeL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44c362600dbed9d58be8daf64558543745698736/pkg/sql/logictest/testdata/logic_test/window#L1)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

By deleting this line we will no longer run this test on 5node configs. However, this file doesn't split and relocate ranges, so probably it's ok.
</blockquote></details>

Done.

**Comment by asubiotto** [comment]
`TestLogic` took 22m on this PR, I'm happy with that.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-:-MEcLOS28EmBMzDN1wTS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @nvanbenschoten)

___
*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-MEbAT5l4RXS5qFVXuz3:-MEcLCHgAl8Sq5b_-aZY:bgrgeyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/44c362600dbed9d58be8daf64558543745698736/pkg/sql/logictest/testdata/logic_test/distsql_join#L1)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What do you think of this removal @yuzefovich? Was there any good reason to use a `5node` config here?
</blockquote></details>

I don't see a good reason. I think this file has had 5node configs since its introduction in 2017.
___
*[pkg/sql/logictest/testdata/logic_test/edge, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-MEYGv2_5sKVd4wCiN73:-MEcK_ux-bVjZGthwKXf:bgfu92w) ([raw file](https://github.com/cockroachdb/cockroach/blob/44c362600dbed9d58be8daf64558543745698736/pkg/sql/logictest/testdata/logic_test/edge#L2)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Yep, the test ran successfully. Maybe post-processing delegation to the row engine?
</blockquote></details>

I don't think so. I'll take a look at why this isn't failing anymore.
___
*[pkg/sql/logictest/testdata/logic_test/interleaved_join, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52680#-MEbB38i9HFicFc9emKX:-MEcK7d71v5GkIe9tFWM:b-sklq0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/44c362600dbed9d58be8daf64558543745698736/pkg/sql/logictest/testdata/logic_test/interleaved_join#L1)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

@yuzefovich OOC what was the reason for blocking this test?
</blockquote></details>

When I added support for the joins in the new factory, interleaved joins were planned in an ad-hoc manner (there was no separate `ConstructInterleavedJoin` method, instead, hash or merge joins could be converted into interleaved joins). As a result, the new factory was planning hash or merge joins and not interleaved ones as the test expects. Since then Radu has cleaned things up, and now the new factory correctly falls back to the old path when an interleaved join can be planned.

**Comment by asubiotto** [comment]
TFTR

bors r=yuzefovich

**Comment by yuzefovich** [comment]
`edge` is no longer failing because we now prohibit mixed-type operations with dates (`ERROR: unable to vectorize execution plan: unable to columnarize render expression "_date - 1": dates and timestamp(tz) not supported in mixed-type expressions in the vectorized engine`), so we fallback to row engine on those queries. However, since the root cause is not fixed, I'm not going to close #40354.

**Pull request merged**
