### PR TITLE
metric: clean up Rates and window interval

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9841)

### CODE REVIEW

**Comment by tamird** [comment]
:dog: :+1: but @mberhault should look.

---

Reviewed 18 of 18 files at r1, 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[kv/txn_coord_sender.go, line 249 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-KTjK_t8zfoYU38cTKb9:-KTjK_t8zfoYU38cTKbA:bwzocu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f6c944596e7a6fbbb5bec5f1f465fa26bfb0dc/kv/txn_coord_sender.go#L249)):*
> ```Go
> 			num := durations.TotalCount()
> 
> 			if log.V(1) {
> ```

why did this move all the way down? this seems to be doing a lot more work now if `!log.V(1)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-:-KTjLNuLpN2AYGVv1vpL:b-epnabc)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[kv/txn_coord_sender.go, line 249 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-KTjK_t8zfoYU38cTKb9:-KTjPdiCUy8yhoeXyCKt:b-rvle6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/00f6c944596e7a6fbbb5bec5f1f465fa26bfb0dc/kv/txn_coord_sender.go#L249)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why did this move all the way down? this seems to be doing a lot more work now if `!log.V(1)`
</details>
Yes, but I'm also skeptical that nontrivial work that isn't in the hot path should be hidden away because I wouldn't want new bugs when I turn on `V(1)` (case in point is that there was a panic here in my WIP which I only caught when I actually ran with `V(1)`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841)*

**Comment by mrtracy** [comment]
Are we sure we want the window duration of the histograms to be a full hour?  That seems very unintuitive to me; if we record an outlier max value into one of these histograms, it will be represented as the max in every ten-second sample taken for the next hour.

The primary use case of the windowed histograms is still our internal time series, I'm assuming; isn't the 1-minute rollover more appropriate?  Actually, wouldn't a ten-second window be more appropriate in the case of time series?  We probably need to rethink this in more detail.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-:-KTk5VLyW_NQt0zL8bAv:b-luwvef)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/node.go, line 179 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-KTk7HWFFH54Gt5_Qo_t:-KTk7HWFFH54Gt5_Qo_u:bqq7c1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/188b8b376c013644f75fc59a28e504dd83d63f1d/server/node.go#L179)):*
> ```Go
> 	cfg := storage.StoreConfig{}
> 	cfg.ScanInterval = 10 * time.Minute
> 	cfg.MetricsSampleInterval = time.Hour
> ```

I assume this is an attempt to disable metrics sampling on the bootstrap store?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841)*

**Comment by tschottdorf** [comment]
Yes, a ten-second window is appropriate for time series with the default `METRICS_SAMPLE_INTERVAL=10s`. With `METRICS_SAMPLE_INTERVAL=d`, the appropriate window is `d`, which is what I am (hopefully) achieving with this PR. If that isn't what I'm doing, please let me know. Or perhaps you're confused by the various `time.Hour`s I haphazardly put in seemingly random places - those are just satisfying the assertion that we don't create windowed histograms with zero rollover; I am asserting on that in the metrics package.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-:-KTkJg7SPQft6Ch6VcaP:b-stvuws)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/node.go, line 179 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-KTk7HWFFH54Gt5_Qo_t:-KTkKVV_HAetkZ9bF5bN:bwcdu2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/188b8b376c013644f75fc59a28e504dd83d63f1d/server/node.go#L179)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I assume this is an attempt to disable metrics sampling on the bootstrap store?
</details>
Correct, as are all of the other `= time.Hour` assignments. I should probably make clear what the intention is. Any preference as to how I should do that? Comments on each?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841)*

**Comment by mrtracy** [comment]
The issue I have is that `time.Hour` looks like a considered choice; what we really want is a `time.MaxDuration`, but I guess `Hour` is the longest default duration.  As an alternative, I think it would be fine for the Histograms to treat a *zero* time value as an unlimited value; I think that is often the case in APIs where a zero value makes no sense (for example, when setting timeouts in asynchronous calls, in many libraries a zero disables the timeout entirely).

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-:-KTp1tNYBjzH8BHtVux4:b-1l68ho)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/node.go, line 179 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-KTk7HWFFH54Gt5_Qo_t:-KTp3tNWdRtw99sq5fVx:bh3voh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/188b8b376c013644f75fc59a28e504dd83d63f1d/server/node.go#L179)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Correct, as are all of the other `= time.Hour` assignments. I should probably make clear what the intention is. Any preference as to how I should do that? Comments on each?
</details>
FWIW, `time.Duration` is just an `int64`, so you could really use `math.MaxInt64` here to drive the point home.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841)*

**Comment by tschottdorf** [comment]
I want to keep the assertion, but I introduced `TestSampleInterval` which is now used instead of `time.Hour` and hopefully makes it clear what's going on. Did you have any other comments ir os this LGTM?

---

Review status: 1 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/node.go, line 179 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-KTk7HWFFH54Gt5_Qo_t:-KTpZHMTDOVTJr7Zx8Bk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/188b8b376c013644f75fc59a28e504dd83d63f1d/server/node.go#L179)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> FWIW, `time.Duration` is just an `int64`, so you could really use `math.MaxInt64` here to drive the point home.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-:-KTpZA14FzhKv52NwBL6:b-rvjwpm)*

**Comment by tamird** [comment]
Reviewed 11 of 26 files at r3, 15 of 15 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[util/metric/metric.go, line 41 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-KTp_J0deVR3BzB1QSdx:-KTp_J0deVR3BzB1QSdy:b-kc5zwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5fa25cfce1569c7a0fe296626a0bf274dd4e894/util/metric/metric.go#L41)):*
> ```Go
> 
> 	// TestSampleInterval is passed to histograms during tests which don't
> 	// want to conern themselves with supplying a "correct" interval.
> ```

conern -> concern

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 26 of 27 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9841#-:-KTtuzY72odSYerbZ3sx:bnfp4nl)*

**Pull request merged**
