### PR TITLE
sql: fix or disallow TRUNCATE and concurrent schema changes

### LINKED ISSUE #62842: sql: TRUNCATE and ongoing index builds are broken
**Describe the problem**

In 20.2 we changed the implementation of TRUNCATE to create all new indexes instead of creating a new table (https://github.com/cockroachdb/cockroach/pull/52235). This was wonderful in that it made table IDs stable. Unfortunately, it appears that that PR had some severe logic bugs in the face of concurrent index builds. 

The logic has two bugs around https://github.com/cockroachdb/cockroach/blob/d145e9fc02064a8b6b4179b5af7da5238b192f74/pkg/sql/truncate.go#L221-L227
The first is that it should make the in-progress indexes public prior to calculating the re-mapping. Secondly, it needs to deal with the ongoing jobs. 

**To Reproduce**

Create an index backfill which takes a long time and then truncate the table. The index will become public but this index will contain data from prior to the truncate. The job will also remain in the queue which will prevent subsequent schema changes. 

**Expected behavior**

The index is truncated and made public.

**Additional context**

This affects all current 20.2 versions and 21.1.

### PR DESCRIPTION
**Pull request by ajwerner**
Prior to this change, the truncate implementation since 20.2 was totally
broken. The code creates new indexes for all existing indexes. It also
makes all mutations public. The problem with this is that it makes the
mutations public *after* deciding which indexes to clone. Because of this
it just makes currently being backfilled or validated indexes public. This
leads to inconsistency between the old secondary index and the newly
truncated indexes.

The code is also problematic in that it does not do anything about the mutation
jobs. The code assumes that these jobs will happily continue and detect that
they correspond to no mutations and stop doing things as well as clean
themselves up. Unfortunately, it seems that these changes can lead to certain
failures. For example, new index validation may now fail. Reverting that index
build will now also fail because the index is public. This will leave the
descriptor in a state where it has an orphaned mutation job. We fix this by
only permitting TRUNCATE to run concurrently with mutations we deem safe and
then to fix the behavior for those cases.

Fixes #62842.

Release note (bug fix): Fixed bugs where TRUNCATE concurrent with index
construction and other schema changes could result in corruption.

### CODE REVIEW

**Comment by ajwerner** [comment]
I took a stab at preventing more things. It started conservative and then I added more support. It might still be too liberal. I know there's some lint things to fix but afk for another hour or so. PTAL

**Review by jordanlewis — COMMENTED** [review]
Looks good. I'll do another pass later today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-:-MXHmAc347RkmRCv6zuk:b-npwbwg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/truncate.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-MXHl-gC80e-dd4TpABB:-MXHl-gD7zeoKkFFOfbe:b-f8cs4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/144d6375f610bb8a16eee021ad3c891104b5eb46/pkg/sql/truncate.go#L352)):*
> ```Go
> 			if !m.Adding() {
> 				return unimplemented.Newf(
> 					"TRUNCATE concurrent with ongoing schema change",
> ```

cc @vy-ton, these are the exceptional cases we were talking about. Andrew, Vy and I were also talking about whether it's more clear to prevent all cases like this especially if we're moving more in that direction soon. But I think the point here is that, while we can't instantly cancel all schema changes, it's more user-friendly to have some odd exceptions to the rule than to prevent people from getting themselves out of a jam via TRUNCATE and instantly-droppable schema changes.
___
*[pkg/sql/truncate.go, line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-MXHle7aDtfxUxHOocuM:-MXHle7b64uO6TFE9UrP:bswahpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/144d6375f610bb8a16eee021ad3c891104b5eb46/pkg/sql/truncate.go#L366)):*
> ```Go
> 			case descpb.ConstraintToUpdate_CHECK,
> 				descpb.ConstraintToUpdate_UNIQUE_WITHOUT_INDEX,
> 				descpb.ConstraintToUpdate_NOT_NULL:
> ```

nit: Comment as to why supported would be useful for future debuggers
___
*[pkg/sql/truncate.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-MXHlmQi28HyX1n2f6Eb:-MXHlmQi28HyX1n2f6Ec:bmhie8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/144d6375f610bb8a16eee021ad3c891104b5eb46/pkg/sql/truncate.go#L374)):*
> ```Go
> 						"key constraint change", desc.GetName())
> 			default:
> 				return errors.AssertionFailedf("unknown check constraint type %v on mutation %d in %v", ct, i, desc)
> ```

Nervous that this is brittle - if we introduce a new check constraint type it won't be possible to notice this code, probably, so there will be lurking assertion errors. Suggestion: what if we made these assertion errors unimplemented errors instead? Maybe the user-visible consequence is basically the same, that the TRUNCATE fails, but it'll be less user-unfriendly, and we won't get a sentry report.
___
*[pkg/sql/truncate.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-MXHlRoZ6m_xfH4pK5jl:-MXHlRoZ6m_xfH4pK5jm:b52r3cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/144d6375f610bb8a16eee021ad3c891104b5eb46/pkg/sql/truncate.go#L381)):*
> ```Go
> 				"cannot perform TRUNCATE on %q which has an ongoing primary key "+
> 					"change", desc.GetName())
> 		} else if m.AsComputedColumnSwap() != nil {
> ```

nit: Comment as to why this is supported
___
*[pkg/sql/truncate.go, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-MXHm2yi2sQ0TuHKAL5x:-MXHm2yi2sQ0TuHKAL5y:b-8uxdzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/144d6375f610bb8a16eee021ad3c891104b5eb46/pkg/sql/truncate.go#L384)):*
> ```Go
> 			// supported
> 		} else {
> 			return errors.AssertionFailedf("unknown mutation of type %T for mutation %d in %v", m, i, desc)
> ```

Potentially same comment as  above about assertion vs unimplemented.

**Review by jordanlewis — COMMENTED** [review]
Overall :lgtm:, nice tests!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-:-MXIsVo17GrdIf32Fl1f:bqumb3f)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

**Review by ajwerner — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-:-MXJS6Ex1JZ6kJVCmaSH:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi, @jordanlewis, and @vy-ton)

___
*[pkg/sql/truncate.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-MXHl-gC80e-dd4TpABB:-MXJS3lk0YINFFtPXzlf:bhthz7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/144d6375f610bb8a16eee021ad3c891104b5eb46/pkg/sql/truncate.go#L352)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

cc @vy-ton, these are the exceptional cases we were talking about. Andrew, Vy and I were also talking about whether it's more clear to prevent all cases like this especially if we're moving more in that direction soon. But I think the point here is that, while we can't instantly cancel all schema changes, it's more user-friendly to have some odd exceptions to the rule than to prevent people from getting themselves out of a jam via TRUNCATE and instantly-droppable schema changes.
</blockquote></details>

Yes, exactly that. 
___
*[pkg/sql/truncate.go, line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-MXHle7aDtfxUxHOocuM:-MXIfh0E1m25eejNi_fN:bc52388) ([raw file](https://github.com/cockroachdb/cockroach/blob/144d6375f610bb8a16eee021ad3c891104b5eb46/pkg/sql/truncate.go#L366)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: Comment as to why supported would be useful for future debuggers
</blockquote></details>

Okay, I could see blocking these, they seemed easy to support. Upon thinking a bit more, I think a check constraint could use a user-defined type and yet no columns have to (it's an edge case) and then it's possible that after we track that dependency ( @the-ericwang is working on that) then we'd potentially have a problem. Out of an abundance of caution, I've disabled all of these for now. 
___
*[pkg/sql/truncate.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-MXHlmQi28HyX1n2f6Eb:-MXIflD6AcL3Wz3bH-N_:b-i8036m) ([raw file](https://github.com/cockroachdb/cockroach/blob/144d6375f610bb8a16eee021ad3c891104b5eb46/pkg/sql/truncate.go#L374)):*
We'll need a new version gate if we were to do that. I can put a comment on this enum to go check for usages. 

> Maybe the user-visible consequence is basically the same, that the TRUNCATE fails, but it'll be less user-unfriendly, and we won't get a sentry report.

Is it really less user friendly than an error that says "unimplemented: something unknown is happening concurrently"? I can make this message match that message but I'd really like that sentry report. I updated the message a bit. 
___
*[pkg/sql/truncate.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-MXHlRoZ6m_xfH4pK5jl:-MXIg9uG7-NWsNWqPRQB:b-t6e77w) ([raw file](https://github.com/cockroachdb/cockroach/blob/144d6375f610bb8a16eee021ad3c891104b5eb46/pkg/sql/truncate.go#L381)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: Comment as to why this is supported
</blockquote></details>

It was a column backfill but it turns out to be broken. Glad I added a test. It is now disabled.
___
*[pkg/sql/truncate.go, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62944#-MXHm2yi2sQ0TuHKAL5x:-MXIgBW-8s4ButFIgISs:b-842iwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/144d6375f610bb8a16eee021ad3c891104b5eb46/pkg/sql/truncate.go#L384)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Potentially same comment as  above about assertion vs unimplemented.
</blockquote></details>

I added a comment to the interface to tell future developers to go look for code to update and to add version gates when extending this interface.

**Comment by ajwerner** [comment]
TFTR!

bors r=jordanlewis

**Comment by ajwerner** [comment]
bors r=jordanlewis

**Pull request merged**
