### PR TITLE
rename bulk-io to disaster-recovery in CODEOWNERS

### PR DESCRIPTION
**Pull request by shermanCRL**

### CODE REVIEW

**Comment by shermanCRL** [comment]
The CI failures are lints for the existence of the team `disaster-recovery` -- which is correct. After merging [this blathers PR](https://github.com/cockroachlabs/blathers-bot/pull/91), I’ll change the team name, then we’ll retry here.

**Review by celiala — APPROVED** [review]
:lgtm:

**Comment by celiala** [comment]
I found more mentions of "bulk-io" - I'll push a PR soon that will include the update to CODEOWNERS.

**Comment by celiala** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/pull/88075

**Pull request closed without merging**
