### PR TITLE
opt: add rule to push null-rejecting filter under projection

### PR DESCRIPTION
**Pull request by DrewKimball**
This patch adds a rule that pushes a `col IS NOT NULL` filter below
a projection, like the following:
```
SELECT * FROM
(
  SELECT k*x FROM a
  LEFT JOIN xy ON i = y
) f(p)
WHERE p > 5
=>
SELECT * FROM
(
  SELECT k*x FROM a
  LEFT JOIN xy ON i = y
  WHERE x IS NOT NULL
) f(p)
WHERE p > 5
```
In this example, the left join can now be simplified because of the
null-rejecting filter.

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
The plans for TPC-H queries 17 and 20 changed. The runtime for Q17 is about the same. However, Q20 goes from ~13s to ~18s. I think this is likely due to a similar reason as for #51900; stats are pretty far off for Q20.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDTFzcNDzAiV0OEJV89:-MDTFzcNDzAiV0OEJV8A:b-5rxqgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/837756b2e16acf25dabbf3921ce801f9a873f7d9/pkg/sql/opt/norm/reject_nulls_funcs.go#L248)):*
> ```Go
> 	var projectionsRejectCols opt.ColSet
> 	for i := range projections {
> 		if !opt.OperatorTransmitsNulls(projections[i].Element.Op()) {
> ```

This needs to be a "deep" check that ensures the subtree is composed only of ops that transmit NULL values and variables. A shallow check like this will miss cases where the top-level op transmits NULL values but one or both of its inputs do not.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDTH7JT8hKgM5sxruVb:-MDTH7JU0gAzMizA5JhY:b-tx3ygd) ([raw file](https://github.com/cockroachdb/cockroach/blob/837756b2e16acf25dabbf3921ce801f9a873f7d9/pkg/sql/opt/norm/reject_nulls_funcs.go#L251)):*
> ```Go
> 			continue
> 		}
> 		if projections[i].ScalarProps().OuterCols.Intersects(rejectNullCols) {
> ```

All the projection columns need to NULL reject, or else it's not safe to NULL reject on any. For example, if I have the projections "a * 2" and "a IS NULL", I can't NULL reject on `a`.

**Comment by andy-kimball** [comment]
___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDTH7JT8hKgM5sxruVb:-MDTLJKz2V1Riur16mIB:b-91hvh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/837756b2e16acf25dabbf3921ce801f9a873f7d9/pkg/sql/opt/norm/reject_nulls_funcs.go#L251)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

All the projection columns need to NULL reject, or else it's not safe to NULL reject on any. For example, if I have the projections "a * 2" and "a IS NULL", I can't NULL reject on `a`.
</blockquote></details>

Thinking about this more, this actually should be OK. "ANY" semantics should work, since the null rejecting filter is going to remove the whole row regardless of what else is in it. So disregard this comment.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDTFzcNDzAiV0OEJV89:-MDW4Yc2BIQHEdo74Fhv:b-vycm7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/837756b2e16acf25dabbf3921ce801f9a873f7d9/pkg/sql/opt/norm/reject_nulls_funcs.go#L248)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This needs to be a "deep" check that ensures the subtree is composed only of ops that transmit NULL values and variables. A shallow check like this will miss cases where the top-level op transmits NULL values but one or both of its inputs do not.
</blockquote></details>

Done. I'll add some tests, too.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[pkg/sql/opt/operator.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDVdhso2yM7ALZm3VAn:-MDVdhso2yM7ALZm3VAo:by29w2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/837756b2e16acf25dabbf3921ce801f9a873f7d9/pkg/sql/opt/operator.go#L252)):*
> ```Go
> }
> 
> // OperatorTransmitsNulls returns true if the given operator always returns NULL
> ```

[nit] scalar operator
___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDW9ZQ25LErcTovM38Q:-MDW9ZQ25LErcTovM38R:b-tqegf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1b1fc1ce55fce3365520e3be3beaff2842571ff/pkg/sql/opt/norm/reject_nulls_funcs.go#L280)):*
> ```Go
> 	var canRejectNulls func(opt.Expr) bool
> 	canRejectNulls = func(expr opt.Expr) bool {
> 		if variable, ok := expr.(*memo.VariableExpr); ok {
> ```

We should also tolerate any `IsConstValueOp` leaves (e.g. `a + 1`)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDWChaW7CvughbbMmNZ:-MDWChaW7CvughbbMmN_:bad3uij) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1b1fc1ce55fce3365520e3be3beaff2842571ff/pkg/sql/opt/norm/reject_nulls_funcs.go#L286)):*
> ```Go
> 		}
> 		if !opt.OperatorTransmitsNulls(expr.Op()) {
> 			// In order for condition #1 to be satisfied, we require an unbroken chain
> ```

Interestingly, you could derive a subset of input columns that have to be not-null: all those reached through null-transmitting operators. Probably wouldn't matter much in practice (but might be worth clarifying in the comments that the current approach is making a simplification).

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/operator.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDVdhso2yM7ALZm3VAn:-MDWIE9x7rvUUATbHU4x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/837756b2e16acf25dabbf3921ce801f9a873f7d9/pkg/sql/opt/operator.go#L252)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] scalar operator
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDW9ZQ25LErcTovM38Q:-MDWKIEiAlnqtan4I-0G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1b1fc1ce55fce3365520e3be3beaff2842571ff/pkg/sql/opt/norm/reject_nulls_funcs.go#L280)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should also tolerate any `IsConstValueOp` leaves (e.g. `a + 1`)
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDWChaW7CvughbbMmNZ:-MDWHg4lEtmhlIXQVFn6:bcijfoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1b1fc1ce55fce3365520e3be3beaff2842571ff/pkg/sql/opt/norm/reject_nulls_funcs.go#L286)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Interestingly, you could derive a subset of input columns that have to be not-null: all those reached through null-transmitting operators. Probably wouldn't matter much in practice (but might be worth clarifying in the comments that the current approach is making a simplification).
</blockquote></details>

I'm not sure what you mean; are you saying that all input columns reached by null-transmitting operators could be added to the NullRejectCols set?

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, 2 of 3 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @DrewKimball, and @RaduBerinde)

___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDpsh1S2VKMdzYkwow1:-MDpsh1S2VKMdzYkwow2:bhnk0ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d91d8ff4b3bbf0c05633189ef56b594b79758e6/pkg/sql/opt/norm/reject_nulls_funcs.go#L91)):*
> ```Go
> 			return opt.ColumnID(0)
> 		}
> 		if !opt.ScalarOperatorTransmitsNulls(expr.Op()) && expr.Op() != opt.ConstOp {
> ```

why do you need an explicit check for `ConstOp`?
___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDptHvu6mRAqMc5zLUm:-MDptHvu6mRAqMc5zLUn:bc6p06) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d91d8ff4b3bbf0c05633189ef56b594b79758e6/pkg/sql/opt/norm/reject_nulls_funcs.go#L268)):*
> ```Go
> //
> //   2. One or more of the projection's input columns are in the RejectNullCols
> //      ColSet of the input expression. Note that this condition is not strictly
> ```

This comment got cut off. Also, I don't understand why this is a requirement, but maybe the rest of the comment will explain :)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDpsh1S2VKMdzYkwow1:-MDpyyfy6DkM13b2fYS8:b9hgryj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d91d8ff4b3bbf0c05633189ef56b594b79758e6/pkg/sql/opt/norm/reject_nulls_funcs.go#L91)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why do you need an explicit check for `ConstOp`?
</blockquote></details>

I definitely don't, thanks for catching that. Done.
___
*[pkg/sql/opt/norm/reject_nulls_funcs.go, line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-MDptHvu6mRAqMc5zLUm:-MDpzcDN9ZwOcdMmVA6w:b-fv9q5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d91d8ff4b3bbf0c05633189ef56b594b79758e6/pkg/sql/opt/norm/reject_nulls_funcs.go#L268)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This comment got cut off. Also, I don't understand why this is a requirement, but maybe the rest of the comment will explain :)
</blockquote></details>

Huh, not sure what happened there.... Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52107#-:-MDq1Ior8w8fCk3gluDV:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

**Pull request merged**
