### PR TITLE
rpc: avoid closing connections on failed heartbeats

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8446)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[rpc/context_test.go, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOpXUPdIV7jc6Dx49Qj:-KOpXUPdIV7jc6Dx49Qk:b1yqsr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a601202b6c032fe867c86258ac8473eb4518b789/rpc/context_test.go#L144)):*
> ```Go
> 
> 	// Should be unhealthy in the absence of heartbeats.
> 	if clientCtx.IsConnHealthy(remoteAddr) {
> ```

I'm probably not following the test, but how is this testing transport failure?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[rpc/context_test.go, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOpXUPdIV7jc6Dx49Qj:-KOpYxX1a10XJMrFvhGR:b-6qyjcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a601202b6c032fe867c86258ac8473eb4518b789/rpc/context_test.go#L144)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm probably not following the test, but how is this testing transport failure?
</details>
You're looking at the wrong test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446)*

**Comment by petermattis** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[rpc/context_test.go, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOpXUPdIV7jc6Dx49Qj:-KOpZU_2JYtqT431Pz5Y:b-qttb0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a601202b6c032fe867c86258ac8473eb4518b789/rpc/context_test.go#L144)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> You're looking at the wrong test.
</details>
Huh, I swear reviewable didn't show me the second commit. 

---

*[rpc/context_test.go, line 197 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOpZOg9uHvlWz21ET2K:-KOpZOgAMWDGXoE9drE6:b-pcj7qe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0463049289fa449b7d28f91f37377a238cb9625/rpc/context_test.go#L197)):*
> ```Go
> 	clock := hlc.NewClock(time.Unix(0, 1).UnixNano)
> 
> 	remoteAddr := "not.a.real.addr:1234"
> ```

I seem to recall that there is an explicitly invalid DNS name for uses like this. @bdarnell? Or it might be better to bind a local port but to not listen on it. 

---

*[rpc/context_test.go, line 215 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOp_PbKC4b1Ga47e4So:-KOp_PbKC4b1Ga47e4Sp:b-apdblp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0463049289fa449b7d28f91f37377a238cb9625/rpc/context_test.go#L215)):*
> ```Go
> 
> 	// If our heartbeats were not fail-fast, this RPC would hang indefinitely.
> 	if _, err := heartbeatClient.Ping(ctx, &PingRequest{Addr: clientCtx.Addr}, grpc.FailFast(false)); !grpcutil.IsClosedConnection(err) {
> ```

It's confusing that you're passing `FailFast(false)` here given the comment immediately above. Can you expand that comment to indicate that the non-failfast RPCs are the ones being sent internally and that the use of `heartbeatClient` here is for convenience.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446)*

**Comment by tamird** [comment]
@petermattis I've completely reworked the second commit - it now uses `grpc.FailFast(false)` in the rpc context (partially reverting your original change). See the commit message and PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[rpc/context_test.go, line 197 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOpZOg9uHvlWz21ET2K:-KOpgAb4jaW8PNt-LKWr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0463049289fa449b7d28f91f37377a238cb9625/rpc/context_test.go#L197)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I seem to recall that there is an explicitly invalid DNS name for uses like this. @bdarnell? Or it might be better to bind a local port but to not listen on it. 
</details>
Done.

---

*[rpc/context_test.go, line 215 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOp_PbKC4b1Ga47e4So:-KOpgBTeH1n79-U0kLfh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0463049289fa449b7d28f91f37377a238cb9625/rpc/context_test.go#L215)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> It's confusing that you're passing `FailFast(false)` here given the comment immediately above. Can you expand that comment to indicate that the non-failfast RPCs are the ones being sent internally and that the use of `heartbeatClient` here is for convenience.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-:-KOpgCRT37yvdWXn0vZW:bq1vgg8)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[rpc/context.go, line 311 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOpl7e9pyQQQ5ze2xi5:-KOpl7e9pyQQQ5ze2xi6:b6myut) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7bdd0e641bab40008ede0d7ee6828a8f426ff3/rpc/context.go#L311)):*
> ```Go
> 	goCtx, cancel := context.WithTimeout(context.Background(), ctx.HeartbeatTimeout)
> 	defer cancel()
> 	return heartbeatClient.Ping(goCtx, &request, grpc.FailFast(false))
> ```

But we want a fail-fast RPC in order to detect transport failures. I must be missing something about why this is a good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446)*

**Comment by tamird** [comment]
@petermattis another overhaul. PTAL.

**Comment by petermattis** [comment]
:lgtm: modulo the comment about how long to wait to retry heartbeat rpcs that time out.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[rpc/context.go, line 249 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOq8VMAk4mYa-aMkRnx:-KOq8VMBNSUY9Sf1b9O1:bp1cldv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8043ead3bb2b212dc9c9b8aa430c1ba72f5bc41f/rpc/context.go#L249)):*
> ```Go
> 		response, err := ctx.heartbeat(heartbeatClient, request)
> 		ctx.setConnHealthy(remoteAddr, err == nil)
> 		if err == nil {
> ```

If a heartbeat RPC times out, do we want to wait another `HeartbeatInterval` to send another one or should we send it right away?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-:-KOq9-h5BrMC4MDNa3F1:b-tqznll)*

**Comment by tamird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[rpc/context.go, line 249 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOq8VMAk4mYa-aMkRnx:-KOq9XCae6ecDPXzaUh0:b-l97i80) ([raw file](https://github.com/cockroachdb/cockroach/blob/8043ead3bb2b212dc9c9b8aa430c1ba72f5bc41f/rpc/context.go#L249)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> If a heartbeat RPC times out, do we want to wait another `HeartbeatInterval` to send another one or should we send it right away?
</details>
Good point, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[rpc/context_test.go, line 197 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-KOpZOg9uHvlWz21ET2K:-KOqIUWAW1b9TbtyXSgz:b5nqgl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0463049289fa449b7d28f91f37377a238cb9625/rpc/context_test.go#L197)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Done.
</details>
example.com is supposed to be guaranteed not to exist, but in many cases it resolves anyway. I haven't been able to find a hostname that will consistently produce resolution errors. Instead, my preferred way to generate connection-refused errors is to start a listener on port 0 (to get an unused port) and immediately close it (it will take some time before it could be reused by any other process) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8446#-:-KOqJPioDGGtGvRv5pkx:bnfp4nl)*

**Pull request merged**
