### PR TITLE
colexec: some memory accounting and performance optimizations

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: account for aggregate functions structs**

Previously, we were not accounting for the memory used by aggregate
functions structs. This behavior is acceptable in case of ordered
aggregator (because we will only constant number of such structs), but
it's no bueno for the hash aggregator - we will be creating a separate
struct for each group. This is now fixed by performing the memory
accounting upon creation of these aggregate functions structs.

This commit also adds accounting for `hashAggFuncs` structs in the hash
aggregator.

However, this commit does not address the missing memory accounting of
the Golang's `map` that we use for mapping a hash code to all aggregate
builtins (i.e. "groups") that correspond to that hash code. This is left
as TODO, but we need to address it for 20.2. A note here is that we
might be replacing the usage of this `map` with our vectorized hash
table, so it'll probably make sense to wait for that.

Addresses: #48428.

Release note: None

**colexec: introduce Flush method into aggregateFunc interface**

I was looking at cpu profile with memory intensive hash aggregation, and
it was saying that we spend noticeable amount of time checking whether
aggregation function is `done`. This can be avoided if we refactor the
interface slightly which is what this commit does.

Previously, we used `Compute` method to both compute the aggregation on
non-empty batch and to flush the result of aggregation of the last group
on an empty batch. These two purposes are now split into two functions:
the former is done by the same `Compute` function and the latter is done
by newly-introduced `Flush` function which must be called to "flush" the
result for the last group.

Release note: None

**colexec: generate different structs for two COUNT variants**

In one profile I saw noticeable time spent on an `if` condition that
determines whether we have `count_rows` aggregate or not. This commit
refactors the template to generate two different structs which allows us
to remove that check.

Release note: None

**typeconv: change map usage to family switch**

In a cpu profile I noticed that some time was spent in the accesses to
the map when instantiating aggregate funcs. This can be avoided by
changing the usage of map to a switch on a type family, and the function
should be inlined.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The benchmarks of the first two commits are [here](https://gist.github.com/yuzefovich/15ff27754350f4c2b6b579ccd710ab1d). The TL;DR is that there is at most 10% hit with small group sizes (due to the addition of memory accounting) but also at most 20-30% with big group sizes (due to refactor of `Flush`).

I think we could reduce the hit in the former case if we "batch" the memory accounting (i.e. we would update the memory account on every 1000 of created new aggregate structs or something like that). This is left as TODO.

**Comment by yuzefovich** [comment]
The benchmarks of the fourth commit in isolation show moderate improvement in case of small group sizes:
```
name                                                                                      old speed      new speed      delta
Aggregator/ANY_NOT_NULL/hash/int/groupSize=1/hasNulls=false/numInputBatches=64-24         4.86MB/s ± 2%  5.13MB/s ± 1%   +5.40%  (p=0.000 n=9+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=4/hasNulls=false/numInputBatches=64-24         20.0MB/s ± 4%  21.2MB/s ± 1%   +6.11%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=16/hasNulls=false/numInputBatches=64-24        72.8MB/s ± 3%  81.7MB/s ± 2%  +12.13%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=64/hasNulls=false/numInputBatches=64-24         218MB/s ± 0%   225MB/s ± 2%   +2.91%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=246/hasNulls=false/numInputBatches=64-24        410MB/s ± 0%   405MB/s ± 0%   -1.05%  (p=0.000 n=10+9)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=1024/hasNulls=false/numInputBatches=64-24       546MB/s ± 0%   525MB/s ± 0%   -3.87%  (p=0.000 n=10+9)
Aggregator/ANY_NOT_NULL/hash/decimal/groupSize=1/hasNulls=false/numInputBatches=64-24     4.48MB/s ± 2%  4.63MB/s ± 1%   +3.23%  (p=0.000 n=10+9)
Aggregator/ANY_NOT_NULL/hash/decimal/groupSize=4/hasNulls=false/numInputBatches=64-24     18.4MB/s ± 2%  19.2MB/s ± 1%   +4.23%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/decimal/groupSize=16/hasNulls=false/numInputBatches=64-24    67.1MB/s ± 2%  74.5MB/s ± 4%  +10.99%  (p=0.000 n=9+10)
Aggregator/ANY_NOT_NULL/hash/decimal/groupSize=64/hasNulls=false/numInputBatches=64-24     209MB/s ± 1%   213MB/s ± 1%   +2.06%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/decimal/groupSize=246/hasNulls=false/numInputBatches=64-24    386MB/s ± 1%   387MB/s ± 0%   +0.32%  (p=0.008 n=10+9)
Aggregator/ANY_NOT_NULL/hash/decimal/groupSize=1024/hasNulls=false/numInputBatches=64-24   505MB/s ± 1%   501MB/s ± 0%   -0.70%  (p=0.001 n=8+10)
Aggregator/ANY_NOT_NULL/hash/bytes/groupSize=1/hasNulls=false/numInputBatches=64-24       4.60MB/s ± 2%  4.81MB/s ± 1%   +4.45%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/bytes/groupSize=4/hasNulls=false/numInputBatches=64-24       19.5MB/s ± 1%  20.1MB/s ± 1%   +2.97%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/bytes/groupSize=16/hasNulls=false/numInputBatches=64-24      71.0MB/s ± 2%  77.1MB/s ± 2%   +8.48%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/bytes/groupSize=64/hasNulls=false/numInputBatches=64-24       205MB/s ± 1%   208MB/s ± 0%   +1.18%  (p=0.000 n=10+8)
Aggregator/ANY_NOT_NULL/hash/bytes/groupSize=246/hasNulls=false/numInputBatches=64-24      360MB/s ± 0%   356MB/s ± 1%   -1.14%  (p=0.000 n=10+9)
Aggregator/ANY_NOT_NULL/hash/bytes/groupSize=1024/hasNulls=false/numInputBatches=64-24     457MB/s ± 1%   455MB/s ± 1%   -0.54%  (p=0.010 n=10+9)
```

**Review by asubiotto — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 9 of 9 files at r2, 3 of 3 files at r3, 1 of 25 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48511)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/aggregator.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48511#-M783PY30oDE4Nk8ta2-:-M783PY30oDE4Nk8ta20:b-2qahr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d486b4d1110a95f3fb0d12cc8f3bf11b41b5df/pkg/sql/colexec/aggregator.go#L74)):*
> ```Go
> 
> 	// Compute computes the aggregation on the input batch.
> 	// Note: the implementations should be careful to account for their memory
> ```

Does this node belong on `Compute`? It seems like it's referencing the struct's memory usage, which might be better as an interface-level comment.
___
*[pkg/sql/colmem/allocator.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48511#-M780uFE1-hYd8sqcjh-:-M780uFE1-hYd8sqcjh0:bmvqc69) ([raw file](https://github.com/cockroachdb/cockroach/blob/55c006e614c2627948d5ce439a76bdee9389f147/pkg/sql/colmem/allocator.go#L228)):*
> ```Go
> // UpdateMemoryUsage updates the number of bytes currently allocated through
> // this allocator by delta bytes (which can be both positive or negative).
> func (a *Allocator) UpdateMemoryUsage(delta int64) {
> ```

`UpdateMemoryUsage` is confusing because to me it sounds like an "overwrite". Could we rename this to `AddMemoryUsage`? I don't particularly like that either, so maybe you can think of something better.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48511)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/aggregator.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48511#-M783PY30oDE4Nk8ta2-:-M78_CzTEVF5sRAPyMEz:b-sn9zum) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d486b4d1110a95f3fb0d12cc8f3bf11b41b5df/pkg/sql/colexec/aggregator.go#L74)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does this node belong on `Compute`? It seems like it's referencing the struct's memory usage, which might be better as an interface-level comment.
</blockquote></details>

I wanted to contrast it with `Flush` - since `Compute` can be called multiple times, and it could accumulate arbitrary number of groups, it needs to perform memory accounting, but `Flush` should be called only once, and it'll allocate the memory only for the last group, so the memory accounting can be skipped.
___
*[pkg/sql/colmem/allocator.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48511#-M780uFE1-hYd8sqcjh-:-M78aBrB6aNy-F5Ftqvx:bpv007s) ([raw file](https://github.com/cockroachdb/cockroach/blob/55c006e614c2627948d5ce439a76bdee9389f147/pkg/sql/colmem/allocator.go#L228)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`UpdateMemoryUsage` is confusing because to me it sounds like an "overwrite". Could we rename this to `AddMemoryUsage`? I don't particularly like that either, so maybe you can think of something better.
</blockquote></details>

How about `AdjustMemoryUsage`?

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48511#-:-M78yWad34VvZqwr5jQ8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colmem/allocator.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48511#-M780uFE1-hYd8sqcjh-:-M78yNZU0d_ic3l6MvGA:bvrupqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/55c006e614c2627948d5ce439a76bdee9389f147/pkg/sql/colmem/allocator.go#L228)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

How about `AdjustMemoryUsage`?
</blockquote></details>

`Adjust` seems similar to `Update` but if we can't think of anything better that's fine.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48511#-:-M78yvn44QRoKoC_Y0ld:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colmem/allocator.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48511#-M780uFE1-hYd8sqcjh-:-M78ywft2ZwxHFzBkrUN:b3ib88d) ([raw file](https://github.com/cockroachdb/cockroach/blob/55c006e614c2627948d5ce439a76bdee9389f147/pkg/sql/colmem/allocator.go#L228)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`Adjust` seems similar to `Update` but if we can't think of anything better that's fine.
</blockquote></details>

I agree that `Update` was not an ideal choice because it could mean an "overwrite", but `Adjust` (at least to me) sounds like a "modification" of the current usage by some "delta". I don't like `Add` because it implies the positive change in the account.

**Pull request merged**
