### PR TITLE
util/log: Speed up vmodule support and warn about it in help text

### PR DESCRIPTION
**Pull request by a-robinson**
It's possible that with the second commit the help text change is no longer needed, but I'm curious what you think about that. I haven't tried re-running tpc-c 10k with this, so while I'm pretty sure this is a lot better I don't know how much of a performance hit there still is.

### CODE REVIEW

**Review by petermattis — CHANGES_REQUESTED** [review]
Pro-tip: run with `TESTFLAGS="-count 10"` and then compare the output of the two runs with `benchstat`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29017#-:-LKdcYMZAyYSRNkp6JIY:brp7u6b)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/log/clog.go, line 1401 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29017#-LKdcmfk1COYgg0dF8YC:-LKdcmfk1COYgg0dF8YD:bllk5fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6c894278d1ae0b35bb8d6d3a8f10bb6054532ef/pkg/util/log/clog.go#L1401)):*
> ```Go
> 	// Here is another cheap but safe test to see if vmodule is enabled.
> 	if atomic.LoadInt32(&logging.filterLength) > 0 {
> 		pcs := logging.pcsPool.Get().([1]uintptr)
> ```

I don't see a call to `logging.pcsPool.Put` which makes me suspect that you're allocating on every call here. You can also run with `TESTFLAGS="-benchmem"` to see the number of allocations per iteration. 
___
*[pkg/util/log/clog.go, line 1410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29017#-LKdd-6r6pYX6P114hRB:-LKdd-6r6pYX6P114hRC:b6v7h83) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6c894278d1ae0b35bb8d6d3a8f10bb6054532ef/pkg/util/log/clog.go#L1410)):*
> ```Go
> 			v = logging.setV(pcs[0])
> 		}
> 		logging.mu.Unlock()
> ```

I think there should be a call to `logging.pcsPool.Put(pcs)` here.

**Review by a-robinson — COMMENTED** [review]
Benchstat output with `-count 10`:

```
name                 old time/op    new time/op    delta
VDepthWithVModule-8     790ns ± 1%     254ns ± 6%  -67.83%  (p=0.000 n=9+10)

name                 old alloc/op   new alloc/op   delta
VDepthWithVModule-8     0.00B          0.00B          ~     (all equal)

name                 old allocs/op  new allocs/op  delta
VDepthWithVModule-8      0.00           0.00          ~     (all equal)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29017#-:-LKdp66z6bSfldVdMzBX:b-5ouy1t)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/log/clog.go, line 1401 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29017#-LKdcmfk1COYgg0dF8YC:-LKdkTrPEQ_ViFoX3SY3:boe7saq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6c894278d1ae0b35bb8d6d3a8f10bb6054532ef/pkg/util/log/clog.go#L1401)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't see a call to `logging.pcsPool.Put` which makes me suspect that you're allocating on every call here. You can also run with `TESTFLAGS="-benchmem"` to see the number of allocations per iteration. 
</blockquote></details>

🤦Thanks, fixed.

Oddly enough, `-benchmem` actually doesn't show any allocations without the `Put` calls. Seems like an accounting bug of some sort, although we could just be misunderstanding something.

Including the `Put`s is obviously what we want, though, and it performs 10-20% better than without them so they clearly have some effect.
___
*[pkg/util/log/clog.go, line 1410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29017#-LKdd-6r6pYX6P114hRB:-LKdpCG66EqHJ28w5RmE:bon927n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6c894278d1ae0b35bb8d6d3a8f10bb6054532ef/pkg/util/log/clog.go#L1410)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think there should be a call to `logging.pcsPool.Put(pcs)` here.
</blockquote></details>

Done. And in the early return case.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29017#-:-LKfqS9c6G2nM1P_O4Nr:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
