### PR TITLE
kvnemesis: add support for savepoints

### LINKED ISSUE #97444: kvnemesis: add transaction savepoints
We should extend kvnemesis to use transaction savepoints.

### PR DESCRIPTION
**Pull request by miraradeva**
This patch adds support for generating and validating savepoints in kvnemesis.

Fixes: https://github.com/cockroachdb/cockroach/issues/97444

Release note: None

### CODE REVIEW

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110494)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/kv/kvnemesis/validator.go` line 966 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-Ne9tUA_1cb4GbwwW-9R:-Ne9tUA_1cb4GbwwW-9S:b-c8cekc) ([raw file](https://github.com/cockroachdb/cockroach/blob/40dd180ae6c56d5c858ec772849493c837884c32/pkg/kv/kvnemesis/validator.go#L966)):*
> ```Go
> 					g.Add(sp)
> 				}
> 				if then, now := lastWrites.Slice(), g.Slice(); !reflect.DeepEqual(then, now) {
> ```

This is no longer true with savepoints because what was the last write before may now be a rolled back write.
___
*[`pkg/kv/kvnemesis/validator.go` line 1023 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-Ne9u5f180EFag9RhhxG:-Ne9u5f180EFag9RhhxH:b-7g2ai0) ([raw file](https://github.com/cockroachdb/cockroach/blob/40dd180ae6c56d5c858ec772849493c837884c32/pkg/kv/kvnemesis/validator.go#L1023)):*
> ```Go
> 			// and so we must have a timestamp here. We defer the failure to the next for
> 			// loop, as we will have filled in the read timestamps at that time.
> 			if writeTS.IsEmpty() {
> ```

Now that we have savepoints, we can't simply continue because `writeTS` may be empty (e.g. all writes were rolled back) but we still need to add those intermediate rolled back writes, so any subsequent reads can see them.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110494)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/kv/kvnemesis/testdata/TestValidate/one_deleterange_after_write_missing_write` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NeEWoPw-Wc_Ui76sBcs:-NeEWoPw-Wc_Ui76sBct:b8473dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/testdata/TestValidate/one_deleterange_after_write_missing_write#L10)):*
> ```
> }) // @0.000000001,0 <nil>
> /Table/100/"0000000000000001"/0.000000001,0 @ s1 v1
> committed serializable txn missing write at seq s2: [dr.d]/Table/100/"0000000000000001":missing-><nil>@s2 [dr.s]/Table/100/"000000000000000{1"-3"}:{gap:[<min>, 0.000000001,0),[0.000000001,0, <max>)}->[]
> ```

I'm not sure this is ok/expected. Same with the one below.

**Review by AlexTalks — DISMISSED** [review]
> Reviewed 2 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110494)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`pkg/kv/kvnemesis/applier.go` line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NepO9J_9Ff68cFb_6eP:-NepO9JaEoLG1u34e-nu:bycl7pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/applier.go#L123)):*
> ```Go
> 		*DeleteRangeUsingTombstoneOperation,
> 		*AddSSTableOperation:
> 		applyClientOp(ctx, db, op, false, nil)
> ```

nit: it might be helpful to document these constants with `false /* inTxn */, nil /* savepoints */`
___
*[`pkg/kv/kvnemesis/applier.go` line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NepQ24u8nFePA-ndUq-:-NepQ24u8nFePA-ndUq0:brqf34m) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/applier.go#L140)):*
> ```Go
> 		err := updateZoneConfigInEnv(ctx, env, o.Type)
> 		o.Result = resultInit(ctx, err)
> 	case *ClosureTxnOperation:
> ```

Even though the three savepoint operations don't have meaning outside of a transaction, maybe it would make sense to include them as cases here for completeness?  You can have a shared action (likely a panic) for all three cases, but something that is a bit more specific than the `unknown operation` in the default case.
___
*[`pkg/kv/kvnemesis/generator.go` line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NepRTd61Rcwlima2And:-NepRTd61Rcwlima2Ane:bkvlh17) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/generator.go#L267)):*
> ```Go
> 		Ops:   clientOpConfig,
> 	}
> 	savepointConfig := SavepointConfig{
> ```

nit: might be redundant/obvious, but since this is the configuration, it might make sense to add a comment (here or below in the `ClosureTxnConfig`) about how savepoints are only relevant in txns.
___
*[`pkg/kv/kvnemesis/generator.go` line 996 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NepS6ao3m1yld1qO-6L:-NepS6ap5PGeNtS-gexV:bwye8qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/generator.go#L996)):*
> ```Go
> 		makeClosureTxn(Commit, SSI, &c.TxnClientOps, &c.TxnBatchOps, nil /* commitInBatch*/, &c.SavepointOps), c.CommitSerializable)
> 	addOpGen(allowed,
> 		makeClosureTxn(Commit, SI, &c.TxnClientOps, &c.TxnBatchOps, nil, &c.SavepointOps /* commitInBatch*/), c.CommitSnapshot)
> ```

I think here (and below) the parameter comments (I.e.. `/* commitInBatch */` need to match the parameter they go with.
___
*[`pkg/kv/kvnemesis/generator.go` line 1025 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NepSnmu5nxE_4_-xseh:-NepSnmu5nxE_4_-xsei:b61p6jp) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/generator.go#L1025)):*
> ```Go
> 		g.registerClientOps(&allowed, txnClientOps)
> 		g.registerBatchOps(&allowed, txnBatchOps)
> 		numOps := rng.Intn(10)
> ```

What does this change mean / do? Are we just increasing the number of potential ops in a txn?
___
*[`pkg/kv/kvnemesis/generator.go` line 1030 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NepTfya2GlNhpp_p_Nq:-NepTfya2GlNhpp_p_Nr:b-2lll0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/generator.go#L1030)):*
> ```Go
> 		for i := range ops {
> 			allowedSp := allowed
> 			g.registerSavepointOps(&allowedSp, savepointOps, savepoints, i)
> ```

This feels like it might be leaving some operations out, or else perhaps I'm not following this code properly.  Let's discuss it, and at the very least this feels like it needs some comments documenting the behavior.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110494)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[`pkg/kv/kvnemesis/applier.go` line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NepQ24u8nFePA-ndUq-:-NexY3oe-5zAspmEFImj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/applier.go#L140)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Even though the three savepoint operations don't have meaning outside of a transaction, maybe it would make sense to include them as cases here for completeness?  You can have a shared action (likely a panic) for all three cases, but something that is a bit more specific than the `unknown operation` in the default case.
</blockquote></details>

Done.
___
*[`pkg/kv/kvnemesis/generator.go` line 996 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NepS6ao3m1yld1qO-6L:-NexZ4au81cHw8mMXsCn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/generator.go#L996)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

I think here (and below) the parameter comments (I.e.. `/* commitInBatch */` need to match the parameter they go with.
</blockquote></details>

Done.
___
*[`pkg/kv/kvnemesis/generator.go` line 1025 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NepSnmu5nxE_4_-xseh:-NexZ5oU8wdA0W31YWP7:br19fgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/generator.go#L1025)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

What does this change mean / do? Are we just increasing the number of potential ops in a txn?
</blockquote></details>

Discussed on a call. Let me know if we want to have some justification on the number 10. Also happy to consider other values.
___
*[`pkg/kv/kvnemesis/generator.go` line 1030 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NepTfya2GlNhpp_p_Nq:-NexZD7E4clftzOM0hYz:b8a3c3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/60d0f108a2ebd0aae88d118950aed24a2f0b95f0/pkg/kv/kvnemesis/generator.go#L1030)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

This feels like it might be leaving some operations out, or else perhaps I'm not following this code properly.  Let's discuss it, and at the very least this feels like it needs some comments documenting the behavior.
</blockquote></details>

Discussed on a call. Also added a lot more comments.

**Review by arulajmani — COMMENTED** [review]
Still haven't gone through the validator logic, but flushing comments -- they're mostly nits, this looks quite good so far.

> Reviewed 13 of 25 files at r1, 7 of 9 files at r2, 8 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-:-NkzKZXQDSw5YXt_rKxZ:bxi1sk4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @miraradeva, and @nvanbenschoten)

___
*[`pkg/kv/kvnemesis/applier.go` line 169 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzC9cl4sMtPtQfYYee:-NkzC9cl4sMtPtQfYYef:bd0bx1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/applier.go#L169)):*
> ```Go
> 			// A map of a savepoint id to the corresponding savepoint token that was
> 			// created after applying the savepoint op.
> 			spIdToToken := make(map[int]kv.SavepointToken)
> ```

nit: s/spIdToToken/spIDToToken/g
___
*[`pkg/kv/kvnemesis/applier.go` line 294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzBNaU6Lh3pr2gfCXE:-NkzBNaU6Lh3pr2gfCXF:blk6kg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/applier.go#L294)):*
> ```Go
> 	op *Operation,
> 	inTxn bool,
> 	spIdToToken *map[int]kv.SavepointToken,
> ```

nit: s/spIdToToken/spIDsToToken/g 

(here, and in comments).
___
*[`pkg/kv/kvnemesis/applier.go` line 449 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzB_bzDJSur54rwWfJ:-NkzB_bzDJSur54rwWfK:bupk8m3) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/applier.go#L449)):*
> ```Go
> 	case *SavepointCreateOperation:
> 		// db is a Txn because savepoints are allowed only within transactions.
> 		txn, ok := db.(*kv.Txn)
> ```

nit: consider:

```go
txn, ok := db.(*kv.Txn) // savepoints are only allowed with transactions
``

to avoid starting the sentence with a small letter.
```

___
*[`pkg/kv/kvnemesis/generator.go` line 1405 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzCb9D2UBLp2rs-nu-:-NkzCb9D2UBLp2rs-nu0:b-b5xg4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/generator.go#L1405)):*
> ```Go
> 		g.registerClientOps(&allowed, txnClientOps)
> 		g.registerBatchOps(&allowed, txnBatchOps)
> 		const maxOps = 20
> ```

To confirm, we want to check this in?
___
*[`pkg/kv/kvnemesis/generator.go` line 1410 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzCrCnB2K6Wa6xR1P9:-NkzCrCnB2K6Wa6xR1PA:b7yz7ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/generator.go#L1410)):*
> ```Go
> 		// Stack of savepoint indexes/ids.
> 		// The last element of the slice is the top of the stack.
> 		var spIds []int
> ```

nit: s/spIDs/spIDs/g
___
*[`pkg/kv/kvnemesis/generator.go` line 1414 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzKStE9cUXh2WSasXb:-NkzKStFC2JdNCy_oT8R:b15kdc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/generator.go#L1414)):*
> ```Go
> 			// In each iteration, we start with the allowed non-savepoint ops,
> 			// and we add the valid savepoint ops in registerSavepointOps.
> 			allowedSp := allowed
> ```

nit: "allowedIncludingSavepointOps" might be a bit more descriptive.
___
*[`pkg/kv/kvnemesis/generator.go` line 1471 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzDu0P6xt05p5hjUNz:-NkzDu0P6xt05p5hjUO-:b-qu9k6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/generator.go#L1471)):*
> ```Go
> }
> 
> // Based on the previously selected op, updateSavepoints modifies the slice of
> ```

nit: consider rewording this comment to start with the function's name -- maybe something like "updateSavepoints modifies the slice of existing savepoints based on the previously selected op... . It either: ... "

We have a linter to ensure comments for all public functions start with the function's name. While not strictly required, it's nice to do the same for private functions as well for consistency. 
___
*[`pkg/kv/kvnemesis/generator.go` line 1475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzHWfl1ESGIJ0t6Dan:-NkzHWfl1ESGIJ0t6Dao:b1mrp21) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/generator.go#L1475)):*
> ```Go
> // SavepointCreateOperation, or (2) remove a suffix of savepoints if the
> // previous op was SavepointReleaseOperation or SavepointRollbackOperation.
> func updateSavepoints(existingSp *[]int, prevOp Operation) {
> ```

nit: s/updateSavepoints/maybeUpdateSavepoints/g
___
*[`pkg/kv/kvnemesis/generator.go` line 1480 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzH6U43YCmpBTau2bL:-NkzH6U43YCmpBTau2bM:bmlo6sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/generator.go#L1480)):*
> ```Go
> 		// If the previous selected op was a savepoint creation, add it to the stack
> 		// of existing savepoints.
> 		*existingSp = append(*existingSp, int(op.Id))
> ```

Should we make sure op.ID doesn't already exist in existingSp? 
___
*[`pkg/kv/kvnemesis/generator.go` line 1486 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzGKBJ4SLcW-yefgiE:-NkzGKBK3kkufu4Po35L:bz4p5uo) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/generator.go#L1486)):*
> ```Go
> 		// on the stack. E.g. if the existing savepoints are [1, 2, 3], releasing
> 		// savepoint 2 means savepoint 3 also needs to be released.
> 		index := slices.Index(*existingSp, int(op.Id))
> ```

Should we sanity check the savepoint is found in `existingSp`, and return an error if it isn't? (Here, and below). 

We could also extend `TestUpdateSavepoints` to test these cases.
___
*[`pkg/kv/kvnemesis/operations.proto` line 130 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzGRHU1DxFdijx3lCv:-NkzGRHV0LOvoBtuvYdh:bv7ok28) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/operations.proto#L130)):*
> ```proto
> 
> message SavepointCreateOperation {
>   int32 id = 1;
> ```

nit: we should use `gogoproto.customname=ID` so that the generated struct says "ID" instead of "Id". We tend to do this elsewhere in the code where a protobuf has a field with "ID" in its name.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110494)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @arulajmani, and @nvanbenschoten)

___
*[`pkg/kv/kvnemesis/generator.go` line 1405 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzCb9D2UBLp2rs-nu-:-NlPgrQo8ZgXMeTKulEZ:b452233) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/generator.go#L1405)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

To confirm, we want to check this in?
</blockquote></details>

Yes, it exposed some of the issues we found more easily (i.e. before the nightly tests did).
___
*[`pkg/kv/kvnemesis/generator.go` line 1480 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzH6U43YCmpBTau2bL:-NlPjuBe7e7TVtpdreCF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/generator.go#L1480)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we make sure op.ID doesn't already exist in existingSp?
</blockquote></details>

Done.
___
*[`pkg/kv/kvnemesis/generator.go` line 1486 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NkzGKBJ4SLcW-yefgiE:-NlPnVvkAVkab0HmAuhi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/755211db74aa58dfeda8fb2d4f5af329497ad0b0/pkg/kv/kvnemesis/generator.go#L1486)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we sanity check the savepoint is found in `existingSp`, and return an error if it isn't? (Here, and below). 

We could also extend `TestUpdateSavepoints` to test these cases.
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
:lgtm: modulo nits

> Reviewed 1 of 10 files at r3, 4 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-:-NnL7Dg-A4csiJzMkVK1:b-1p9zor)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @miraradeva, and @nvanbenschoten)

___
*[`pkg/kv/kvnemesis/validator.go` line 245 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NnL0e_zCFhDz9psAKdK:-NnL0e_zCFhDz9psAKdL:b-9fiusz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e52608e620791bc6e8f988ed4511402f35bda567/pkg/kv/kvnemesis/validator.go#L245)):*
> ```Go
> 
> func (*observedScan) observedMarker() {}
> ```

nit: should we strongly type these? Something like:

```go
type savepointType int

const (
  create savepointType = iota
  ...
)
```
___
*[`pkg/kv/kvnemesis/validator.go` line 1725 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110494#-NnL6gzaAVE6g_Tiew2Q:-NnL6gzaAVE6g_Tiew2R:bmqnoby) ([raw file](https://github.com/cockroachdb/cockroach/blob/e52608e620791bc6e8f988ed4511402f35bda567/pkg/kv/kvnemesis/validator.go#L1725)):*
> ```Go
> 		case *observedSavepoint:
> 			opCode := "sp"
> 			if o.Type == release {
> ```

nit: should we have a `+= "(create)"` case as well?

**Comment by miraradeva** [comment]
bors r=arulajmani

**Comment by miraradeva** [comment]
bors r=arulajmani

**Comment by nvanbenschoten** [comment]
bors r=arulajmani

**Comment by nvanbenschoten** [comment]
bors r=arulajmani

**Comment by nvanbenschoten** [comment]
bors r=arulajmani

**Pull request merged**
