### PR TITLE
kv: improve a retry reason

### PR DESCRIPTION
**Pull request by andreimatei**
Also improve some error messages and explain a test that baffled me.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: mod the missing test.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42965#-:-LvI8evO1MKt9jFHLdJX:b-vsguwq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/txn_interceptor_committer_test.go, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42965#-LvI8YDP4djw7yLw29xT:-LvI8YDQ5QYVI9XiiJtb:b-9t0pgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/684dd4488eca425bbfcdf3c20c77fae9e6d32dec/pkg/kv/txn_interceptor_committer_test.go#L418)):*
> ```Go
> 	require.NotNil(t, pErr)
> 	require.IsType(t, &roachpb.TransactionRetryError{}, pErr.GetDetail())
> 	require.Equal(t, roachpb.RETRY_WRITE_TOO_OLD, pErr.GetDetail().(*roachpb.TransactionRetryError).Reason)
> ```

Let's test both cases.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42965)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_committer_test.go, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42965#-LvI8YDP4djw7yLw29xT:-LvID3aa9E2gLHCNRiw5:b-mck1zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/684dd4488eca425bbfcdf3c20c77fae9e6d32dec/pkg/kv/txn_interceptor_committer_test.go#L418)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's test both cases.
</blockquote></details>

added the other case

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42965#-:-LvMlAWT2jcwqZSWlmzf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42965#-:-LvS8KqMA2UD5d4LgN0M:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by andreimatei** [comment]
flake  #43036

bors r+

**Pull request merged**
