### PR TITLE
release: merge baking branch to the release branch

### PR DESCRIPTION
**Pull request by rail**
This PR automates creation of the baking branch merge PR back to the original release branch.

Epic: none
Release note: None

### CODE REVIEW

**Comment by rail** [comment]
I need to test this

**Comment by celiala** [comment]
amazing!! 🚀 🎸 🔥 

I haven't looked at the code yet -- but does it take into account the existence of multiple staging branches?
Concretely:
- v23.1.17 just shipped
- but v23.1.18 is baking right now

So, yesterday's task was to merge the `release-23.1.17-rc`. (but we want to leave `release-23.1.18-rc` as-is.

**Comment by rail** [comment]
Yes, it doesn't touch any branches, except the ones related to the released branch:
```go
	maybeBakingbranches := []string{
		fmt.Sprintf("release-%s-rc", releasedVersion.String()), // e.g. release-23.1.17-rc
		fmt.Sprintf("staging-%s", releasedVersion.Original()),  // e.g. staging-v23.1.17
	}
```

**Review by celiala — APPROVED** [review]
🎉  LGTM!

**Comment by rail** [comment]
bors r=celiala

**Comment by rail** [comment]
With a minor change (added the "origin/" prefix) it worked as expected: https://github.com/crltest/crltest-cockroach/pull/2

**Comment by rail** [comment]
Hmm, I'm not sure I like the PR commit body....

**Comment by rail** [comment]
bors r=celiala

Tweaked a few thing to make sure the PR title/body set properly.

**Pull request merged**
