### PR TITLE
workload/schemachange: add select support for workload

### PR DESCRIPTION
**Pull request by fqazi**
1. Refactor the op interface to allow us to easily support different types of queries
2. Add a new select operation and make interface changes to help support some level of validation
3. Introduce a new connection watch dog, which ensures that connections make progress
4. Limit the CTAS operations size, since with join we can produce extremely large inserts
5. Skip constraint validation when generated columns cannot be evalauted

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
This is looking pretty close. Has anything interesting come from it? 

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-:-N8yjLxf8tIJ-hJPFeaW:b14lf8w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`-- commits` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yj4xb8mnGlLnZ5o88):*
nit: remove this
___
*[`pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go` line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yj05GAXw1tnQmSIa5:-N8yj05GAXw1tnQmSIa6:b-6saqb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce5e0f1191b448855d83f20d3682522c65be5f50/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go#L94)):*
> ```Go
> 	workerFn := func(ctx context.Context, fn func(ctx context.Context) error) func() error {
> 		return func() error {
> 			defer fmt.Printf("FINISHED WORKER %p\n", fn)
> ```

remove these?
___
*[`pkg/workload/schemachange/error_screening.go` line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8ygcv595En6oNcK7rm:-N8ygcv595En6oNcK7rn:b-ni7nt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c8190ffa4dda945c75d82e8d70d04c052e243ef/pkg/workload/schemachange/error_screening.go#L345)):*
> ```Go
> 				continue
> 			}
> 			evalTxn, err := tx.Begin(ctx)
> ```

you should check this error

edit: you do something about this in a later commit
___
*[`pkg/workload/schemachange/error_screening.go` line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8ygbTr5j-5Mqnwkjl5:-N8ygbTr5j-5Mqnwkjl6:b-1owamj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c8190ffa4dda945c75d82e8d70d04c052e243ef/pkg/workload/schemachange/error_screening.go#L347)):*
> ```Go
> 			evalTxn, err := tx.Begin(ctx)
> 			newCols[colInfo.name], err = og.generateColumn(ctx, tx, colInfo, columnsToValues)
> 			evalTxn.Rollback(ctx)
> ```

do you need to check this error?
___
*[`pkg/workload/schemachange/operation_generator.go` line 2562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yhvnu-u0KRWX4A5ZW:-N8yhvnu-u0KRWX4A5ZX:by9o8ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c8190ffa4dda945c75d82e8d70d04c052e243ef/pkg/workload/schemachange/operation_generator.go#L2562)):*
> ```Go
> 			)
> 		}
> 		// FIXME: Operation tracking..
> ```

What is the TODO here?
___
*[`pkg/workload/schemachange/operation_generator.go` line 3334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yi5Dy6F0wHukfZyFx:-N8yi5DzAMEp0C2jZBYI:bjhrh2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/88731efeb20fdb61b881946ba234b34094d8b0b8/pkg/workload/schemachange/operation_generator.go#L3334)):*
> ```Go
> 	const MaxTablesForSelect = 3
> 	const MaxColumnsForSelect = 16
> 	const MaxRowsToConsume = 1
> ```

why export these? should these parameters live in the `og` struct?



_Code quote:_
```Go
	const MaxTablesForSelect = 3
	const MaxColumnsForSelect = 16
	const MaxRowsToConsume = 1
```
___
*[`pkg/workload/schemachange/watch_dog.go` line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yiuOqBH-lO8q6yuv-:-N8yiuOqBH-lO8q6yuv0:b9la1n6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce5e0f1191b448855d83f20d3682522c65be5f50/pkg/workload/schemachange/watch_dog.go#L61)):*
> ```Go
> 	lastActiveQuery := w.activeQuery
> 	if err := sessionInfo.Scan(&w.activeQuery, &w.txnID); err != nil {
> 		fmt.Printf("failed to get session information: %v\n", err)
> ```

should we plumb some sort of logger into this object so we get context? 
___
*[`pkg/workload/schemachange/watch_dog.go` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yiakLBKjfxJIVBu5l:-N8yiakLBKjfxJIVBu5m:bb62i0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce5e0f1191b448855d83f20d3682522c65be5f50/pkg/workload/schemachange/watch_dog.go#L85)):*
> ```Go
> // or a timeout is hit.
> func (w *schemaChangeWatchDog) watchLoop(ctx context.Context) {
> 	const maxTimeOutForDump = 300
> ```

time.Duration? otherwise, change the language to be about iterations?
___
*[`pkg/workload/schemachange/watch_dog.go` line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yimcEBRzlEUpJgHmN:-N8yimcEBRzlEUpJgHmO:bhc99no) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce5e0f1191b448855d83f20d3682522c65be5f50/pkg/workload/schemachange/watch_dog.go#L94)):*
> ```Go
> 			return
> 		case <-time.After(time.Second):
> 			if deadline, ok := ctx.Deadline(); ok {
> ```

why not just use `ctx.Done` to wait for the context deadline?

**Review by fqazi — COMMENTED** [review]
Let me try scale testing with this stuff again. It's been on the back burner while I was digging into the other weird issues.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-:-N9-TEAaEoM2FVkX3EMK:bwg9cu5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go` line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yj05GAXw1tnQmSIa5:-N9-S_dC4IF3KKFb_wF9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce5e0f1191b448855d83f20d3682522c65be5f50/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go#L94)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

remove these?
</blockquote></details>

Done.
___
*[`pkg/workload/schemachange/error_screening.go` line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8ygcv595En6oNcK7rm:-N9-SbAV6XzsaquCxISK:b-t8ng7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c8190ffa4dda945c75d82e8d70d04c052e243ef/pkg/workload/schemachange/error_screening.go#L345)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you should check this error

edit: you do something about this in a later commit
</blockquote></details>

Done.

Yes moved it one commit back
___
*[`pkg/workload/schemachange/error_screening.go` line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8ygbTr5j-5Mqnwkjl5:-N9-SdWU9tiZG-KcYE_W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c8190ffa4dda945c75d82e8d70d04c052e243ef/pkg/workload/schemachange/error_screening.go#L347)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

do you need to check this error?
</blockquote></details>

Done.
___
*[`pkg/workload/schemachange/operation_generator.go` line 2562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yhvnu-u0KRWX4A5ZW:-N9-SiTf55gMxPoaP7uM:bw3q4k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c8190ffa4dda945c75d82e8d70d04c052e243ef/pkg/workload/schemachange/operation_generator.go#L2562)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What is the TODO here?
</blockquote></details>

Ugh left over from development before I fixed the logging stuff.
___
*[`pkg/workload/schemachange/operation_generator.go` line 3334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yi5Dy6F0wHukfZyFx:-N9-SoPsABN_7yYeu6IB:b-tcty78) ([raw file](https://github.com/cockroachdb/cockroach/blob/88731efeb20fdb61b881946ba234b34094d8b0b8/pkg/workload/schemachange/operation_generator.go#L3334)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why export these? should these parameters live in the `og` struct?
</blockquote></details>

Accidentally exported for now, but longer term maybe have something shared with CTAS.
___
*[`pkg/workload/schemachange/watch_dog.go` line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yiuOqBH-lO8q6yuv-:-N9-T4DA06fG4k6c9Lpo:br3v78w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce5e0f1191b448855d83f20d3682522c65be5f50/pkg/workload/schemachange/watch_dog.go#L61)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should we plumb some sort of logger into this object so we get context? 
</blockquote></details>

Done.

Sharing the logger with the worker now, which will allow us to know which connection is having trouble.
___
*[`pkg/workload/schemachange/watch_dog.go` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yiakLBKjfxJIVBu5l:-N9-TAmM5w3IIy8F6ISP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce5e0f1191b448855d83f20d3682522c65be5f50/pkg/workload/schemachange/watch_dog.go#L85)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

time.Duration? otherwise, change the language to be about iterations?
</blockquote></details>

Done.
___
*[`pkg/workload/schemachange/watch_dog.go` line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N8yimcEBRzlEUpJgHmN:-N9-TBZ49iJvP4RsPNpL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce5e0f1191b448855d83f20d3682522c65be5f50/pkg/workload/schemachange/watch_dog.go#L94)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why not just use `ctx.Done` to wait for the context deadline?
</blockquote></details>

Done.

**Review by fqazi — COMMENTED** [review]
There is at least one memory limit error that we are working around, which I don't think makes sense we don't have crazy scale here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-:-N9-TQjZ5__FBFfdXPQI:b-98mc3u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ajwerner — APPROVED** [review]
:lgtm: -- let's be vigilant and see if flakes come out of this

> Reviewed 1 of 5 files at r8, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-:-N92bLgI7pf_FrrE--V4:b-oeruwl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[`pkg/workload/schemachange/error_screening.go` line 348 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N92bDbfCn4otDFRw7L9:-N92bDbfCn4otDFRw7LA:b-el39dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0cc77278874b3d291d1c2667ec91b97d03e9231/pkg/workload/schemachange/error_screening.go#L348)):*
> ```Go
> 			newCols[colInfo.name], err = og.generateColumn(ctx, tx, colInfo, columnsToValues)
> 			if err != nil {
> 				_ = evalTxn.Rollback(ctx)
> ```

Do you need to check the `Rollback` error?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84399)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/workload/schemachange/error_screening.go` line 348 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/84399#-N92bDbfCn4otDFRw7L9:-N94fJYLDl0l38ABwQSe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0cc77278874b3d291d1c2667ec91b97d03e9231/pkg/workload/schemachange/error_screening.go#L348)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Do you need to check the `Rollback` error?
</blockquote></details>

Done.

**Pull request merged**
