### PR TITLE
sql: export planner and plan nodes and use in CCL code.

### PR DESCRIPTION
**Pull request by mberhault**
Release note: None

Export `sql.planner` and `sql.planNode` (and a few other smaller ones) and use in CCL code.

The first 3 commits are mechanical.
4th adds comments on newly exported methods.
5th replaces the PlanHookState with the Planner.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Why is this necessary?

**Comment by mberhault** [comment]
This is to allow the same construction of CCL plan nodes as we have for OSS
plan nodes.

Right now, we have a limited interface given to CCL plan hooks but have to
keep adding individual OSS methods into it. Might as well make as much of
the SQL code reusable as possible and have similar looking plan nodes
across both directories.

**Comment by knz** [comment]
Before we can review this (and settle on a solution) I'd like to discuss the situation so that all stakeholders realize the costs/risks associated with this change. It's not trivial (I'm bordering on requesting a RFC for this even - need to think about it).

**Comment by knz** [comment]
Calling a meeting first thing next Tuesday to discuss.

**Comment by mberhault** [comment]
What's not trivial here? This is merely making OSS code available to CCL code. The end goal being to have CCL plan nodes look at much like OSS plan nodes as possible rather than having to find ways around it all.

We could to piecemeal modifications to the PlanHookState as in [this PR](https://github.com/cockroachdb/cockroach/pull/21020/files#diff-6db18e7c26ddef19927e9f0233c9c036R77), but that's doing some of the work done here.

In general, treating CCL code like a completely separate code base that "hacks" its way into OSS code is just plain gross. We should make writing CCL code as simple as OSS code. There's still more work to do there (eg: switching on parser trees), but this is a start.

**Comment by knz** [comment]
By doing so you are focusing on the code and missing the human dimension. Your change here suggests removing a separation of concerns which was enabling (so far) engineers to look at a part of the code without having to be concerned about what happens in the other part. This separation of concerns is important for productivity and team dynamics. 

A PR that improves code without changing team dynamics is a-OK and can be reviewed locally. A PR that changes team dynamics and effectively shifts the responsibility of entire teams is not a trivial matters and needs to be discussed with multiple parties.

**Comment by petermattis** [comment]
> Before we can review this (and settle on a solution) I'd like to discuss the situation so that all stakeholders realize the costs/risks associated with this change. It's not trivial (I'm bordering on requesting a RFC for this even - need to think about it).
>
> Calling a meeting first thing next Tuesday to discuss.

Is there a reason this can't be discussed in this PR? You're clearly seeing something objectionable to this change that isn't obvious to me. I'm curious to know what that is. By discussing the objection in a meeting I wasn't invited to, I'll remain in the dark. Sure, I can get myself invited, but what about the other lurkers who are curious?

> A PR that improves code without changing team dynamics is a-OK and can be reviewed locally. A PR that changes team dynamics and effectively shifts the responsibility of entire teams is not a trivial matters and needs to be discussed with multiple parties.

I believe this is touching on your concern, but its too abstract for me. What concretely is the concern about exporting `sql.Planner` and `sql.PlanNode`? They were unexported initially because I knee-jerk to not exporting types until we need to export them. Now a need has arisen.

@marc `sql.PlanNode` is relatively tight, but `sql.Planner` has a big fat surface area. Do we really need to expose all of `sql.Planner`? Perhaps `sql.Planner` should be an interface. 

---

Review status: 0 of 149 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21105#-:-L1XeyDEy8lwJOj4a-Au:b-dh6yrf)*

**Comment by mberhault** [comment]
`planHookState` was already the following:
```
-type PlanHookState interface {
 -	EvalContext() tree.EvalContext
 -	ExecCfg() *ExecutorConfig
 -	DistLoader() *DistLoader
 -	TypeAsString(e tree.Expr, op string) (func() (string, error), error)
 -	TypeAsStringArray(e tree.Exprs, op string) (func() ([]string, error), error)
 -	TypeAsStringOpts(
 -		opts tree.KVOptions, valuelessOpts map[string]bool,
 -	) (func() (map[string]string, error), error)
 -	User() string
 -	AuthorizationAccessor
 -	// The role create/drop call into OSS code to reuse plan nodes.
 -	// TODO(mberhault): it would be easier to just pass a planner to plan hooks.
 -	CreateUserNode(
 -		ctx context.Context, nameE, passwordE tree.Expr, ifNotExists bool, isRole bool, opName string,
 -	) (*CreateUserNode, error)
 -	DropUserNode(
 -		ctx context.Context, namesE tree.Exprs, ifExists bool, isRole bool, opName string,
 -	) (*DropUserNode, error)
 -}
```

I added the last two to be able to easily create existing plan nodes from CCL code and I'll be finding myself adding even more very soon.
We could keep exporting more and more planner methods and adding them to the interface but I figured one sweep would make this simpler.

If we only want plan nodes (as opposed to the entire planner), we could split those and only make nodes themselves accessible.
Even then, the planner is the main access point to a lot of functionality to implement a particular plan. If we want to make CCL code relatively painless we need to provide the same functionality we have in OSS land. I see it as an equivalent of the C++ split: OSS code is entirely usable by CCL code, but only a fraction of the OSS code is available to the cgo interface. Granted, this is because we have better granularity of exported vs non-exported but I'm honestly not concerned about people using our sql code willy-nilly.

---

Review status: 0 of 149 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21105#-:-L1XiRzMF7bFyAyWDdYw:bp7bti6)*

**Comment by jordanlewis** [comment]
We also already have an interface `EvalPlanner` that provides access to the planner from `Expr.Eval`, by the way. Perhaps it should be extended and renamed. I would support making a `Planner` interface that both `sql` and `sqlccl` have to use, FWIW.

I agree with Peter that `planNode` itself seems harmless to export.

**Comment by petermattis** [comment]
> Granted, this is because we have better granularity of exported vs non-exported but I'm honestly not concerned about people using our sql code willy-nilly.

I'm not sure where this came from, but I'm not worried about it either. The discussion should be focused on our usage.

> Even then, the planner is the main access point to a lot of functionality to implement a particular plan.

True. You don't seem to be using anything in `sql.Planner` that wasn't already exposed by `PlanHookState`. Did I miss something in this PR? Is there something additional you need access to?

I'm looking at the planhooks code for the first time now. Seems a bit tacked on. Rather than have a list of planhooks, I think there should be a `map[reflect.Type]hook` and all planning should go through hooks. There is a comment in the code about the usage of `reflect`, but that doesn't seem bad to me. Regardless of whether that is changed, it seems like what you want is for code outside of the `sql` package to be able to create `planNodes`. So let's export `sql.planNode` and change plan hooks to return `sql.PlanNode`.

I'm seeing the logic for exporting `sql.Planner` given the above. As I mentioned before, the surface area for `sql.Planner` is huge:

```
~/Development/go/src/github.com/cockroachdb/cockroach/pkg master go doc -u ./sql.planner | grep -E 'planner\) [A-Z]' | wc -l
      98
```

That's 98 exported methods on `sql.Planner`. Most of those are not useful externally as they are implementations of planning for specific statements. 

PS `sql.PlanNode` is already exported using a type alias (`sql/plan.go:132`), so part of this discussion is moot unless I'm missing something.

---

Review status: 0 of 149 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21105#-:-L1Xuiebaht2Z5L7D27j:b-vt1y2z)*

**Comment by benesch** [comment]
I've mentioned this before, but perhaps not so concretely: I see no reason why CCL code needs to create plan nodes at all. Why can't we OSS all the plan nodes, but keep the important implementation bits in CCL?

```go
type backupNode struct {
    ...
}

func (p *planner) Backup() {
    return backupNode{someField: BackupCreateHook(...)}
}

func (n *backupNode) startExec() error {
    return BackupStartHook(...)
}
```

`BackupCreateHook` and `BackupStartHook` would be overridden at init time with CCL symbols if the CCL package is linked in, just like we do with a bunch of other sqlccl functions.

I think this would be a net-neutral change for the backup/restore code. It mostly moves some glue code around.

For nodes like `createUserNode`, where the implementation is sometimes OSS (`CREATE USER`) and sometimes CCL (`CREATE ROLE`), I think this will actually make things clearer:

```go
func (n *createUserNode) startExec() error {
    doSomeCommonStuff();

    if n.createRole {
         CreateRoleHook(...)
    }
    
    return doSomeMoreCommonStuff();
}
```

**Comment by mberhault** [comment]
Quick summary of the discussion today:
We not yet sure where the demarcation between OSS and CCL code should happen w.r.t SQL plans.
This PR assumes plan nodes are created in CCL, but there are very good reasons not to (planning is not a benefit of enterprise code: features are, OSS code should know about a plan but error gracefully if needed hooks are not set, etc...).

The planner separation is a long-term code health issue and must be thought through carefully. The solution may include refactoring similar to that proposed here but this is too early to tell.

Thus, this PR is being closed. @knz, @jordanlewis, @danhhz, @benesch (and perhaps others) will carefully consider any refactoring to be done.

**Pull request closed without merging**
