### PR TITLE
roachtest: various minor perturbation cleanups

### PR DESCRIPTION
**Pull request by andrewbaptist**
Various minor cleanups to the perturbation tests. These changes don't impact anything functional but make it slightly easier to write new perturbations.

### CODE REVIEW

**Comment by andrewbaptist** [comment]
@kvoli - FYI - these changes will make it easier to blacklist failures on tests.

**Review by kvoli — COMMENTED** [review]
Left some questions, otherwise LGTM.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-:-OAJrHzR1Z0Zg4iYCns0:b2qu1lx)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, and @nameisbhaskar)

___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJYWx8Czt45TIcd64X):*
Double checking, this doesn't change the test naming in any way?
___
*[`-- commits` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJZWJb4gOj8l8RkhPd):*
nit: reverses
___
*[`-- commits` line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJp8fm0Hsoe45UukNi):*
nit: except for the aforementioned slow disk test which is mutable.
___
*[`-- commits` line 50 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJpyfD4ETRwFgOfEwW):*
Cleanup comments in which test?
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 238 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJp_qM4Y4CS2KdMgi_:-OAJp_qM4Y4CS2KdMgia:bi12hoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/16db805171a0c770e14a0152a5c5d127353ceb52/pkg/cmd/roachtest/tests/admission_control_latency.go#L238)):*
> ```Go
> func (v variations) makeClusterSpec() spec.ClusterSpec {
> 	opts := []spec.Option{spec.CPU(v.vcpu), spec.SSD(v.disks), spec.Mem(v.mem)}
> 	if reflect.TypeOf(v.perturbation) == reflect.TypeOf(&slowDisk{}) {
> ```

nit: it would be nice to avoid reflection generally in this test, I understand its requirement for a smaller diff here but consider another method which bakes in the opts into the API.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 900 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJqnhaERrzujyzrPDR:-OAJqnhaERrzujyzrPDS:b8dvok6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4984591cd94dbcde59cb75768281b37cd10fe641/pkg/cmd/roachtest/tests/admission_control_latency.go#L900)):*
> ```Go
> 
> // trackedStat is a collection of the relevant values from the histogram. The
> // score is a geometric mean of time per operation per core and blended latency
> ```

Is the geometric mean referring to this?

https://github.com/cockroachdb/cockroach/blob/1d21a080d8deeb6a3ca469ea71ee46af2f04c85d/pkg/cmd/roachtest/tests/admission_control_latency.go#L754-L754

**Review by andrewbaptist — COMMENTED** [review]
TFTR!

I updated the comments. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-:-OAKHfoBAk46B3D2zkDf:b-ac1bib)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @kvoli, and @nameisbhaskar)

___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJYWx8Czt45TIcd64X):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Double checking, this doesn't change the test naming in any way?
</blockquote></details>

Correct, this is only changing the log inside the test.log output.
___
*[`-- commits` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJZWJb4gOj8l8RkhPd):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: reverses
</blockquote></details>

Changed.
___
*[`-- commits` line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJp8fm0Hsoe45UukNi):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: except for the aforementioned slow disk test which is mutable.
</blockquote></details>

Added.
___
*[`-- commits` line 50 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJpyfD4ETRwFgOfEwW):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Cleanup comments in which test?
</blockquote></details>

Added test names.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 238 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJp_qM4Y4CS2KdMgi_:-OAKGYFEATYArH-mBS4I:blxq9ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/16db805171a0c770e14a0152a5c5d127353ceb52/pkg/cmd/roachtest/tests/admission_control_latency.go#L238)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: it would be nice to avoid reflection generally in this test, I understand its requirement for a smaller diff here but consider another method which bakes in the opts into the API.
</blockquote></details>

Agreed. I added a TODO comment to describe this.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 900 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJqnhaERrzujyzrPDR:-OAKHF021CslyAZiJFgH:b-rh4acu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4984591cd94dbcde59cb75768281b37cd10fe641/pkg/cmd/roachtest/tests/admission_control_latency.go#L900)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Is the geometric mean referring to this?

https://github.com/cockroachdb/cockroach/blob/1d21a080d8deeb6a3ca469ea71ee46af2f04c85d/pkg/cmd/roachtest/tests/admission_control_latency.go#L754-L754
</blockquote></details>

Correct, this is a little hard to recognize in this form, and I'm not exactly sure how to name the "ms/ops/core" metric which is one of the values.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-:-OAOZcfr72suGto1g_zz:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, and @nameisbhaskar)

___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 900 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/133365#-OAJqnhaERrzujyzrPDR:-OAOQJPK5_uOSH_3lrYS:b-e6ok6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4984591cd94dbcde59cb75768281b37cd10fe641/pkg/cmd/roachtest/tests/admission_control_latency.go#L900)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Correct, this is a little hard to recognize in this form, and I'm not exactly sure how to name the "ms/ops/core" metric which is one of the values.
</blockquote></details>

Ack -- I don't think this is the geometric mean, or any mean actually, because a mean implies some aggregation, whereas this is a datapoint with pre-aggregated throughput/latency.

The (later) aggregation function is also not a mean afaict, for the score specifically. It is taking the max:

https://github.com/cockroachdb/cockroach/blob/f759a463147c4a5b432e22e1c76d9cd91c2ba47e/pkg/cmd/roachtest/tests/admission_control_latency.go#L921-L935

If it were to be the mean, it would need to look like [this](https://math.stackexchange.com/questions/106700/incremental-averaging) unless the datapoints were retained individually until later. lmk if this sounds off. For geometric, further still, it'd need to be of the form:

```
GeoMean = ( x1 * x2 * ... * xn )^(1/n)
```

Where the samples are equivalent.

All this is to say, I'd remove the geometric mean reference, unless my calcs are off.

**Comment by andrewbaptist** [comment]
@kvoli regarding the geometric mean, its described better in this section: https://docs.google.com/document/d/1oC-FOWSY4LK2es-wGLPOOCe8QZPkzYNu2FcG1RilJ3c/edit?tab=t.0#heading=h.atidkb6sx98l

That said, I'll remove that reference for now. I'm planning on writing a blog post and will refer to that once its done.

**Comment by andrewbaptist** [comment]
TFTR!

bors r=kvoli

**Pull request merged**
