### PR TITLE
colflow: fix emitting of flow stats and simplify the creator a bit

### PR DESCRIPTION
**Pull request by yuzefovich**
We introduced `isGatewayNode` boolean on the flow creator a couple of
months ago which is used to decide whether the last outbox should emit
the flow level memory and disk stats. However, we forget to properly
initialize it in the constructor, and this commit fixes that issue. The
impact though is very limited - we would just emit some redundant stats,
and because they are used for maximum, they would get ignored.

Additionally, this commit simplifies the flow creator by removing
`materializerAdded` field because it is essentially a duplicate of
`isGatewayNode`.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62222)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colflow/vectorized_flow.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62222#-MWP68jn6shQ77YeHw9m:-MWP68jn6shQ77YeHw9n:b-w8z1zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/85f125ff5df2b1ff4bab6b1e069cae18a2d2dead/pkg/sql/colflow/vectorized_flow.go#L461)):*
> ```Go
> 	// node. This field doesn't have to be accessed atomically because all
> 	// writes to it happen before the outboxes' goroutines are started.
> 	numOutboxes int32
> ```

I think it still needs to be accessed atomically because they are different goroutines. Using an atomic value will ensure we flush the CPU cache which will make the updated value available to any following goroutines running on other cores.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62222)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colflow/vectorized_flow.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62222#-MWP68jn6shQ77YeHw9m:-MWQaqs61PM0SUM-xA2c:b-kp835b) ([raw file](https://github.com/cockroachdb/cockroach/blob/85f125ff5df2b1ff4bab6b1e069cae18a2d2dead/pkg/sql/colflow/vectorized_flow.go#L461)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it still needs to be accessed atomically because they are different goroutines. Using an atomic value will ensure we flush the CPU cache which will make the updated value available to any following goroutines running on other cores.
</blockquote></details>

Ok, reverted. I tried searching for documentation of this scenario and didn't find any, do you have some links maybe?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/colflow/vectorized_flow.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62222#-MWP68jn6shQ77YeHw9m:-MWSDkQb59ANvD5e1ayu:bi2cysn) ([raw file](https://github.com/cockroachdb/cockroach/blob/85f125ff5df2b1ff4bab6b1e069cae18a2d2dead/pkg/sql/colflow/vectorized_flow.go#L461)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Ok, reverted. I tried searching for documentation of this scenario and didn't find any, do you have some links maybe?
</blockquote></details>

https://golang.org/ref/mem
http://www.cs.cmu.edu/~410-f10/doc/Intel_Reordering_318147.pdf

In general, you must either use locks (or other synchronization primitives) or `atomic` stuff. Note that `atomic.Store` is not a simple store, it uses `XCHG` which is a "locked" instruction (which flushes the store buffer and ensures a total ordering among all cores w.r.t other locked instructions). (code in `$GOPATH/src/runtime/internal/atomic/asm_amd64.s`).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62222#-:-MWU1uWw4C-MSVaUPHvS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62222#-:-MWUiVLj2qixtLFZfzvA:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colflow/vectorized_flow.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62222#-MWP68jn6shQ77YeHw9m:-MWUiWtV9pha5ZV1EFs7:bhy4tc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/85f125ff5df2b1ff4bab6b1e069cae18a2d2dead/pkg/sql/colflow/vectorized_flow.go#L461)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

https://golang.org/ref/mem
http://www.cs.cmu.edu/~410-f10/doc/Intel_Reordering_318147.pdf

In general, you must either use locks (or other synchronization primitives) or `atomic` stuff. Note that `atomic.Store` is not a simple store, it uses `XCHG` which is a "locked" instruction (which flushes the store buffer and ensures a total ordering among all cores w.r.t other locked instructions). (code in `$GOPATH/src/runtime/internal/atomic/asm_amd64.s`).
</blockquote></details>

Interesting, thanks for the links. My reading is that whenever in doubt, just use the sync things and don't try to be smart :)

**Pull request merged**
