### PR TITLE
sql: introduce array_cat_agg aggregate builtin

### LINKED ISSUE #97502: sql: create new aggregate function array_concat_agg
**Is your feature request related to a problem? Please describe.**
Currently, if you want to aggregate multiple arrays from different rows into a single array, you first need to `unnest` all the arrays, and then re-aggregate them using `array_agg`. This often requires a `LATERAL` join, which may not be possible to decorrelate, resulting in a very inefficient plan. This issue is currently affecting the performance of the statement statistics page in the DB console.

**Describe the solution you'd like**
We should create a new builtin aggregate function called `array_concat_agg`, that allows a user to directly aggregate a set of arrays into a single array.

**Describe alternatives you've considered**
The alternative is to continue using `unnest` + `array_agg`, which as described above, is inefficient.

cc @maryliag

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit introduces a new `array_cat_agg` aggregate builtin function
that takes in an array type as its input, and then unnests each array
and appends all its elements into a single result array. In other
words, it behaves similar to `array_agg(unnest(array_column))`. This
function doesn't have an analogue in Postgres. However, some of our SQL
observability tools need this functionality, and the current workaround
of using a LATERAL JOIN often results in slow apply joins, so this new
builtin should speed things up significantly. In particular,
`crdb_internal.statement_statistics` view is now refactored to use the
new builtin which removes an apply join from it. The choice of this
particular name comes from the fact that we have the `array_cat` builtin
which concatenates two arrays.

Fixes: #97502.

Release note (sql change): New aggregate builtin function
`array_cat_agg` is introduced. It behaves similar to how
`array_agg(unnest(array_column))` would - namely, it takes arrays as its
input, unnests them into the array elements which are then aggregated
into a single result array (i.e. it's similar to concatenating all input
arrays into a single one).

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
cc @maryliag want to make sure that this is the behavior that SQL observability wants, taking an example from #84616:
```sql
create table t (a int, b int, c STRING[]);
insert into t values (1, 1, ARRAY['a', 'b']), (1, 2, ARRAY['c', 'd']), (2, 2, ARRAY['c']), (1, 1, ARRAY['e', 'f']);
```
```
root@127.0.0.1:26257/defaultdb> select a, max(b), array_unnest_agg(c) from t group by a;                                                              
  a | max | array_unnest_agg
----+-----+-------------------
  1 |   2 | {a,b,c,d,e,f}
  2 |   2 | {c}
(2 rows)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-:-NPPp4D76z4NbHO12plh:b6ncy74)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rytaft)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPPonPM4gSpFBa8wmIG):*
I have a slight preference for naming this function `array_unnest_agg` and not `array_concat_agg` as the issue suggests since the former seems more descriptive / intuitive to me, but I can change it if others prefer the latter.

**Comment by maryliag** [comment]
Your example is similar to what I want, so that works, thank you!
Curious, the function combines everything even if we have duplicates? Also wanna make sure it accepts an array being null.

I can share the actual query we want to use this for. On this case we're combining the values of the index_recommendations column (you can use a simplified version of these query to test just that aggregation, but wanted to share the full thing in case you want to compare performance):

```
CREATE VIEW crdb_internal.statement_statistics AS
SELECT
 aggregated_ts,
 fingerprint_id,
 transaction_fingerprint_id,
 plan_hash,
 app_name,
 max(metadata) as metadata,
 crdb_internal.merge_statement_stats(array_agg(DISTINCT statistics)),
 max(sampled_plan),
 aggregation_interval,
 array_remove(array_agg(index_rec), NULL) AS index_recommendations
FROM (
 SELECT
     aggregated_ts,
     fingerprint_id,
     transaction_fingerprint_id,
     plan_hash,
     app_name,
     metadata,
     statistics,
     sampled_plan,
     aggregation_interval,
     index_recommendations
 FROM
     crdb_internal.cluster_statement_statistics
 UNION ALL
     SELECT
         aggregated_ts,
         fingerprint_id,
         transaction_fingerprint_id,
         plan_hash,
         app_name,
         metadata,
         statistics,
         plan,
         agg_interval,
         index_recommendations
     FROM
         system.statement_statistics
)
LEFT JOIN LATERAL unnest(index_recommendations) AS index_rec ON true
GROUP BY
 aggregated_ts,
 fingerprint_id,
 transaction_fingerprint_id,
 plan_hash,
 app_name,
 aggregation_interval
```

**Comment by rytaft** [comment]
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPPonPM4gSpFBa8wmIG):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I have a slight preference for naming this function `array_unnest_agg` and not `array_concat_agg` as the issue suggests since the former seems more descriptive / intuitive to me, but I can change it if others prefer the latter.
</blockquote></details>

The reason I suggested `array_concat_agg` is because there is already a scalar function called `array_concat` that concatenates two arrays (and I've seen other people on the internet use the name `array_concat_agg` for a similar purpose). But I'm open to `array_unnest_agg` if you think that's better.

**Review by yuzefovich — COMMENTED** [review]
> Curious, the function combines everything even if we have duplicates? Also wanna make sure it accepts an array being null.

Yes, the duplicates are kept as well as all NULLs.

Thanks for pointing this view out. I made the change to the view definition to use the new aggregate builtin (I believe it should just be a drop in replacement).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-:-NPQ9gth8zitgQnwZ5Ox:bq4knjc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rytaft)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPPonPM4gSpFBa8wmIG):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The reason I suggested `array_concat_agg` is because there is already a scalar function called `array_concat` that concatenates two arrays (and I've seen other people on the internet use the name `array_concat_agg` for a similar purpose). But I'm open to `array_unnest_agg` if you think that's better.
</blockquote></details>

Ack, let's use `array_concat_agg` then.

**Review by maryliag — APPROVED** [review]
That's awesome!

I'll let someone from SQL Queries to review the implementation itself, but from a usage perspective on the view
:lgtm: 

> Reviewed 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-:-NPSeBMsBac6nnye_j6k:b-kh25i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rytaft)

**Comment by rytaft** [comment]
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPPonPM4gSpFBa8wmIG):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Ack, let's use `array_concat_agg` then.
</blockquote></details>

Ugh I'm totally wrong -- it's array_cat, so `array_cat_agg` is probably what we want. Sorry for the hassle.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @maryliag, and @rytaft)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPPonPM4gSpFBa8wmIG):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ugh I'm totally wrong -- it's array_cat, so `array_cat_agg` is probably what we want. Sorry for the hassle.
</blockquote></details>

Where does this `array_cat` come from? On a quick search I can see that both `array_concat_agg` (e.g. BigQuery) and `array_cat_agg` (e.g. citus) are used. To me `array_concat_agg` seems more intuitive, and since PG doesn't support it anyway, I'd personally choose that version.

**Comment by rytaft** [comment]
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPPonPM4gSpFBa8wmIG):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Where does this `array_cat` come from? On a quick search I can see that both `array_concat_agg` (e.g. BigQuery) and `array_cat_agg` (e.g. citus) are used. To me `array_concat_agg` seems more intuitive, and since PG doesn't support it anyway, I'd personally choose that version.
</blockquote></details>

`array_cat` is a Postgres function that we also support (which concatenates two arrays). But since this aggregate function doesn't exist in Postgres I guess it's up to us. I don't feel too strongly either way...

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 16 of 17 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @yuzefovich)

___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1517 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPUdbceCwobWF7hOplF:-NPUdbceCwobWF7hOplG:b-smychb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac36ff60af6bcf2cfcb5e6c7a1f74dc08139c82/pkg/sql/sem/builtins/aggregate_builtins.go#L1517)):*
> ```Go
> func (a *arrayConcatAggregate) Add(ctx context.Context, datum tree.Datum, _ ...tree.Datum) error {
> 	if datum == tree.DNull {
> 		return a.arr.Append(datum)
> ```

DNull has a nonzero size; should we account for it here?

Also, it seems odd to me that we'd add a `NULL` element when passed a `NULL` argument. For context, `SELECT unnest(NULL::int[])` returns no rows.

**Review by rytaft — COMMENTED** [review]
Awesome! Thanks for doing this!

> Reviewed 16 of 17 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-:-NPY32w19edSb6K6OVfi:bfuptjd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1517 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPUdbceCwobWF7hOplF:-NPY1CXv0xQGZ2LwyU3S:b4r1qhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac36ff60af6bcf2cfcb5e6c7a1f74dc08139c82/pkg/sql/sem/builtins/aggregate_builtins.go#L1517)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

DNull has a nonzero size; should we account for it here?

Also, it seems odd to me that we'd add a `NULL` element when passed a `NULL` argument. For context, `SELECT unnest(NULL::int[])` returns no rows.
</blockquote></details>

+1, would be good to add a test that this aggregate produces the same output as using `array_agg` with `LATERAL ... unnest`

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1517 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPUdbceCwobWF7hOplF:-NPnb6Jr5IvhrdEUi36I:b-2ryzj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac36ff60af6bcf2cfcb5e6c7a1f74dc08139c82/pkg/sql/sem/builtins/aggregate_builtins.go#L1517)):*
> DNull has a nonzero size; should we account for it here?

Indeed, it's non-zero size, but we have a global singleton for it, so it is effectively free. (Side note: I wonder whether we should just change `dNull.Size` to return 0?)

> Also, it seems odd to me that we'd add a NULL element when passed a NULL argument. For context, `SELECT unnest(NULL::int[])` returns no rows.

I followed the behavior or `array_agg` which does include `NULL`s into the result array. In my mind this new aggregate builtin is an aggregate function firstmost, and the closest existing aggregate we have is `array_agg`, so it should be as close to that one as possible. This difference makes it so that `array_concat_agg` is different from `array_agg` with `LATERAL ... unnest`, but it's up to us how we define it. In particular, in the single view where it is now used we are removing all `NULL`s from the result array, so the end result will be the same.

That said, I can also see us not including `NULL`s into the result. Then we'd remove the call to `array_remove` in that view. I'd also probably then rename the aggregate to `array_unnest_agg`.

Let's all agree on the semantics and naming here.

**Comment by rytaft** [comment]
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1517 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPUdbceCwobWF7hOplF:-NPu3tSI-THtMoXDvFio:b7u4gsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac36ff60af6bcf2cfcb5e6c7a1f74dc08139c82/pkg/sql/sem/builtins/aggregate_builtins.go#L1517)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> DNull has a nonzero size; should we account for it here?

Indeed, it's non-zero size, but we have a global singleton for it, so it is effectively free. (Side note: I wonder whether we should just change `dNull.Size` to return 0?)

> Also, it seems odd to me that we'd add a NULL element when passed a NULL argument. For context, `SELECT unnest(NULL::int[])` returns no rows.

I followed the behavior or `array_agg` which does include `NULL`s into the result array. In my mind this new aggregate builtin is an aggregate function firstmost, and the closest existing aggregate we have is `array_agg`, so it should be as close to that one as possible. This difference makes it so that `array_concat_agg` is different from `array_agg` with `LATERAL ... unnest`, but it's up to us how we define it. In particular, in the single view where it is now used we are removing all `NULL`s from the result array, so the end result will be the same.

That said, I can also see us not including `NULL`s into the result. Then we'd remove the call to `array_remove` in that view. I'd also probably then rename the aggregate to `array_unnest_agg`.

Let's all agree on the semantics and naming here.
</blockquote></details>

I agree that if any of the arrays we are aggregating contains a NULL, then we should include that in the output array (this would match `array_agg`). But if the input array itself is NULL, it seems odd to me to treat it the same way as if an element were NULL. 

e.g., given the following rows:
```
[1, 2, 3]
[NULL, 4]
NULL
[5]
```
I would expect the following output (i.e., with one NULL, not two):
```
[1, 2, 3, NULL, 4, 5]
```
But feel free to overrule me if you're convinced otherwise...

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @maryliag, and @rytaft)

___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1517 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPUdbceCwobWF7hOplF:-NPu5scn6HjBV3qdSdcj:b-scvraw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac36ff60af6bcf2cfcb5e6c7a1f74dc08139c82/pkg/sql/sem/builtins/aggregate_builtins.go#L1517)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I agree that if any of the arrays we are aggregating contains a NULL, then we should include that in the output array (this would match `array_agg`). But if the input array itself is NULL, it seems odd to me to treat it the same way as if an element were NULL. 

e.g., given the following rows:
```
[1, 2, 3]
[NULL, 4]
NULL
[5]
```
I would expect the following output (i.e., with one NULL, not two):
```
[1, 2, 3, NULL, 4, 5]
```
But feel free to overrule me if you're convinced otherwise...
</blockquote></details>

I was wrong, this sounds very reasonable, just made this change.

Let's agree on the naming - I have slight preference for `array_concat_agg` (or `array_unnest_agg`), Becca seems to prefer `array_cat_agg`, @DrewKimball I guess your preference is the deciding factor :smiley:

**Comment by DrewKimball** [comment]
>Let's agree on the naming - I have slight preference for array_concat_agg (or array_unnest_agg), Becca seems to prefer array_cat_agg, @DrewKimball I guess your preference is the deciding factor 😃

Wow, so much pressure... I guess I'm in favor of `array_cat_agg` for consistency, but I wish `array_cat` was just `array_concat` instead.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @maryliag, and @rytaft)

___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1517 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPUdbceCwobWF7hOplF:-NPuPhu9BmRJ6aRmBhpK:b-utflba) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac36ff60af6bcf2cfcb5e6c7a1f74dc08139c82/pkg/sql/sem/builtins/aggregate_builtins.go#L1517)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I was wrong, this sounds very reasonable, just made this change.

Let's agree on the naming - I have slight preference for `array_concat_agg` (or `array_unnest_agg`), Becca seems to prefer `array_cat_agg`, @DrewKimball I guess your preference is the deciding factor :smiley: 
</blockquote></details>

Ok, renamed to `array_cat_agg`. Does one of you still think that some test to compare with `LATERAL ... unnest` is needed? (It seems to me like an overkill given the very simple behavior of this aggregate.)

**Comment by DrewKimball** [comment]
>Ok, renamed to array_cat_agg. Does one of you still think that some test to compare with LATERAL ... unnest is needed? (It seems to me like an overkill given the very simple behavior of this aggregate.)

I'm happy. Thanks for doing this!

**Review by rytaft — APPROVED** [review]
:lgtm_strong: thanks for all the iterations on this

> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, 17 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-:-NPPsEccDgcGWOpGKcsN:bra6xlq)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1517 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPUdbceCwobWF7hOplF:-NPwjblW5kSJV5VL60y-:blhm17m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac36ff60af6bcf2cfcb5e6c7a1f74dc08139c82/pkg/sql/sem/builtins/aggregate_builtins.go#L1517)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Ok, renamed to `array_cat_agg`. Does one of you still think that some test to compare with `LATERAL ... unnest` is needed? (It seems to me like an overkill given the very simple behavior of this aggregate.)
</blockquote></details>

I think the current tests are enough (although I added one small suggestion). Thanks!
___
*[`pkg/sql/logictest/testdata/logic_test/aggregate` line 194 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-NPwkQPE74p5Go7j3pEU:-NPwkQPF3MDpKkwuJcFE:b5617kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f47b7455d4c24fa1b2215542f29f4541abcacac/pkg/sql/logictest/testdata/logic_test/aggregate#L194)):*
> ```
> (6, 2, 3, 'b', '1ms', '{6, 2, 3}'),
> (7, 2, 2, 'b', '4 days', '{7, 2, 2}'),
> (8, 4, 2, 'A', '3 years', '{8, 4, 2}')
> ```

nit: consider adding a NULL element inside one of these arrays.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97826#-:-NPx-DANAmhYzfGsx2Df:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rytaft)

**Pull request merged**
