### PR TITLE
storeliveness: react faster to new store additions

### PR DESCRIPTION
**Pull request by miraradeva**
Previously, Store Liveness could wait for up to a heartbeat interval before going through the queue of new stores to add, and starting to heartbeat them. This would result in wait times of over 1s until higher layers can use Store Liveness support.

This commit adds a mechanism to react faster to new store additions.

Part of: #129090

Release note: None

### CODE REVIEW

**Review by iskettaneh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131702)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @miraradeva and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131702#-O8CR66L2hvLxjG0EYWy:-O8CR66L2hvLxjG0EYWz:bmvxdvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174ad97f7ea09c37cf2ff4d1bf70541d680884b/pkg/kv/kvserver/storeliveness/support_manager.go#L214)):*
> ```Go
> 	for {
> 		// NOTE: only listen to the receive queue's signal if we don't already have
> 		// heartbeats to send or support to check. This prevents a constant flow of
> ```

nit: maybe the comment needs an update after the added condition

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131702#-:-O8do3Ug-QTA0uUqT7w3:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`pkg/kv/kvserver/storeliveness/support_manager_test.go` line 409 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131702#-O8dnVc26ArLXm2NvuEW:-O8dnVc26ArLXm2NvuEX:b15hzgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174ad97f7ea09c37cf2ff4d1bf70541d680884b/pkg/kv/kvserver/storeliveness/support_manager_test.go#L409)):*
> ```Go
> // TestSupportManagerHeartbeatNewStore tests that when a store is added (in the
> // first call of SupportFrom), heartbeats are sent to it within one heartbeat
> // interval.
> ```

Is this comment correct? Shouldn't it say the opposite — that heartbeats are sent immediately without waiting for a heartbeat interval? Maybe I'm misinterpreting what you mean by "within".
___
*[`pkg/kv/kvserver/storeliveness/support_manager_test.go` line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131702#-O8dnkUA1VRlWRDCFu-1:-O8dnkUA1VRlWRDCFu-2:b29wrn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174ad97f7ea09c37cf2ff4d1bf70541d680884b/pkg/kv/kvserver/storeliveness/support_manager_test.go#L425)):*
> ```Go
> 	// Set a very large heartbeat interval to ensure heartbeats for new stores are
> 	// sent out before the heartbeat ticker is signalled.
> 	options.HeartbeatInterval = time.Minute
> ```

Under race, `testutils.SucceedsSoon` might wait this long (see `RaceSucceedsSoonDuration`). Let's go longer to completely disable the ticker. ex. `time.Hour`

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131702)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131702#-O8CR66L2hvLxjG0EYWy:-O8hioJyBURq-VA4sK5x:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174ad97f7ea09c37cf2ff4d1bf70541d680884b/pkg/kv/kvserver/storeliveness/support_manager.go#L214)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

nit: maybe the comment needs an update after the added condition
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/support_manager_test.go` line 409 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131702#-O8dnVc26ArLXm2NvuEW:-O8hipv90u_PUa7KihaA:b-vle8kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174ad97f7ea09c37cf2ff4d1bf70541d680884b/pkg/kv/kvserver/storeliveness/support_manager_test.go#L409)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this comment correct? Shouldn't it say the opposite — that heartbeats are sent immediately without waiting for a heartbeat interval? Maybe I'm misinterpreting what you mean by "within".
</blockquote></details>

Yup, "within" was confusing.
___
*[`pkg/kv/kvserver/storeliveness/support_manager_test.go` line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131702#-O8dnkUA1VRlWRDCFu-1:-O8hipKu5eh8xuXIBLVx:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174ad97f7ea09c37cf2ff4d1bf70541d680884b/pkg/kv/kvserver/storeliveness/support_manager_test.go#L425)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Under race, `testutils.SucceedsSoon` might wait this long (see `RaceSucceedsSoonDuration`). Let's go longer to completely disable the ticker. ex. `time.Hour`
</blockquote></details>

Done

**Pull request merged**
