### PR TITLE
storage: eagerly replicate after splits only if not replicated

### LINKED ISSUE #7386: circleci: failed tests: TestReplicaRemovalCampaign
The following test appears to have failed:

[#19440](https://circleci.com/gh/cockroachdb/cockroach/19440):

```
I160622 13:08:51.134679 storage/replica_raftstorage.go:441  generated snapshot for range 1 at index 14 in 857.002µs. encoded size=3558, 31 KV pairs, 4 log entries
I160622 13:08:51.136348 storage/replica_raftstorage.go:533  replica 2 received snapshot for range 1 at index 14. encoded size=3558, 31 KV pairs, 4 log entries
I160622 13:08:51.137428 storage/replica_raftstorage.go:535  replica 2 applied snapshot for range 1 in 988.607µs
I160622 13:08:51.139488 storage/raft_transport.go:215  successfully sent MsgSnap to {2 2 2} at 127.0.0.1:33563
I160622 13:08:51.207575 storage/replica_command.go:2127  initiating a split of range=1 [/Min-/Max) at key "m"
panic: requested entry at index is unavailable

goroutine 8263 [running]:
panic(0x1cdca20, 0xc82017c990)
	/usr/local/go/src/runtime/panic.go:481 +0x3ff
github.com/coreos/etcd/raft.(*raftLog).term(0xc82088b490, 0xa, 0x6181f4, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/log.go:238 +0x1fe
github.com/coreos/etcd/raft.(*raftLog).lastTerm(0xc82088b490, 0xa)
	/go/src/github.com/coreos/etcd/raft/log.go:212 +0x57
github.com/coreos/etcd/raft.newRaft(0xc8216317f0, 0x0)
	/go/src/github.com/coreos/etcd/raft/raft.go:238 +0x114b
github.com/coreos/etcd/raft.NewRawNode(0xc8216317f0, 0x0, 0x0, 0x0, 0x7f6f203d00a8, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/rawnode.go:76 +0xe1
github.com/cockroachdb/cockroach/storage.(*Replica).withRaftGroupLocked(0xc8204cac40, 0xc821631998, 0x0, 0x0)
--
	/go/src/github.com/cockroachdb/cockroach/storage/replica_range_lease.go:118 +0x2c4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask.func1(0xc8205782a0, 0x29eadb6, 0x1e, 0x99, 0xc8208f1d60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:181 +0x74
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:182 +0xdc
FAIL	github.com/cockroachdb/cockroach/storage	17.549s
=== RUN   TestBatchBasics
I160622 13:09:06.512914 storage/engine/rocksdb.go:143  opening in memory rocksdb instance
I160622 13:09:06.515887 storage/engine/rocksdb.go:186  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.02s)
=== RUN   TestBatchRepr
I160622 13:09:06.536341 storage/engine/rocksdb.go:143  opening in memory rocksdb instance
I160622 13:09:06.769199 storage/engine/rocksdb.go:186  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.26s)
=== RUN   TestBatchGet
I160622 13:09:06.791121 storage/engine/rocksdb.go:143  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by petermattis**
---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7396)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica_command.go, line 2317 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7396#-KKsxAAaDF8EIWJZmZin:-KKsxAAaDF8EIWJZmZio:-1705128332) ([raw file](https://github.com/cockroachdb/cockroach/blob/b145b51f6e12a3a497f31a8b2cb78c7510e09f86/storage/replica_command.go#L2317)):*
> ```Go
> 			r.store.replicateQueue.MaybeAdd(r, r.store.Clock().Now())
> 		}
> 		if len(split.NewDesc.Replicas) == 1 {
> ```

This is the key line which avoids replicating if we're also campaigning. Totally unclear to me why replicating while campaigning would be problematic. And note that the replica scanner could decide to replicate anyways so the bug seen in #7386 still exists without this PR, it is just much more rare.

@tschottdorf, @bdarnell I need your guidance here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7396)*

**Comment by petermattis** [comment]
PS I'm in no hurry to merge this. 

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7396#-:-KKsxaarsmy074eofjLA:1313200860)*

**Comment by tschottdorf** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_command.go, line 2317 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7396#-KKsxAAaDF8EIWJZmZin:-KKt9BXRruBN4W_GpALv:1522263809) ([raw file](https://github.com/cockroachdb/cockroach/blob/b145b51f6e12a3a497f31a8b2cb78c7510e09f86/storage/replica_command.go#L2317)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This is the key line which avoids replicating if we're also campaigning. Totally unclear to me why replicating while campaigning would be problematic. And note that the replica scanner could decide to replicate anyways so the bug seen in #7386 still exists without this PR, it is just much more rare.
> 
> @tschottdorf, @bdarnell I need your guidance here. 
</details>
I'm looking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7396)*

**Comment by petermattis** [comment]
This is ready for another look. The first commit is revert of a revert. 

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica_command.go, line 2314 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7396#-KKx87hTgq6wrhEUo29m:-KKx87hTgq6wrhEUo29n:-679319057) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f86ddb86822f198e2666c515ae2a58ddc2a249/storage/replica_command.go#L2314)):*
> ```Go
> 		// both new halves to speed up a potentially necessary replication. See
> 		// #7022.
> 		if len(split.UpdatedDesc.Replicas) == 1 {
> ```

I've decided to leave these restrictions in for now. The address @BramGrunier's concern that we're calling `replicaQueue.MaybeAdd` unnecessarily while still achieve fast replication of the initial ranges.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7396#-:-KKx7z6G6yc8PcznLmQr:-698240183)*

**Comment by tamird** [comment]
:lgtm: except for the "Fixes #7386" bit, since that underlying bug is still present.

---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7396#-:-KKxTqW_FZKYNFLfVRvX:-801949218)*

**Comment by petermattis** [comment]
Yeah, I'll remove that. #7386 was fixed by #7404. 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7396#-:-KKxUvN2tWAE4IhN4MO2:1387222802)*

**Pull request merged**
