### PR TITLE
roachtest: remove sstable-corruption test

### LINKED ISSUE #114010: roachtest: sstable-corruption/table failed
roachtest.sstable-corruption/table [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12562959?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12562959?buildTab=artifacts#/sstable-corruption/table) on release-23.1 @ [a4e0bfde6a520c605276ed73fdcc9bb3db20949c](https://github.com/cockroachdb/cockroach/commits/a4e0bfde6a520c605276ed73fdcc9bb3db20949c):

```
(sstable_corruption.go:169).runSSTableCorruption: workload returned error: 0xc00507a180
test artifacts and logs in: /artifacts/sstable-corruption/table/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12562959/sstable-corruption-table/1699429465560/1699430359992)

</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sstable-corruption/table.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33295

### PR DESCRIPTION
**Pull request by itsbilal**
The sstable-corruption roachtest was initially added to aid in measuring progress of the replica corruption project, that would allow us to more gracefully recover from instances of isolated on-disk corruption. However, for a multitude of reasons we did not embark in that direction, and this roachtest stuck around to test a relatively unhelpful crash case.

Another complicating issue with this roachtest was that the monitor is not ideal at tracking node crashes that happen right at startup, and the workload call with --tolerate-errors would also suppress connection-time errors. Instead of improving this roachtest to track node deaths better, it's more optimal to just delete the roachtest.

Fixes #114010.

Epic: none

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116264#-:-NlUW06H5TjrHHcQwdtc:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @sumeerbhola)

**Comment by itsbilal** [comment]
TFTR!

bors r=RaduBerinde

**Comment by itsbilal** [comment]
blathers backport 23.1

blathers backport 22.2

**Comment by itsbilal** [comment]
blathers backport 23.2

**Pull request merged**
