### PR TITLE
distsql: collect tableReader stats and output to trace

### PR DESCRIPTION
**Pull request by asubiotto**
This PR is split into two commits. The first commit lays the groundwork for stat collection code. The stats are modeled as a proto to be sent over the wire in the future (we will be sending these stats as metadata). The second commit modifies the tableReader to use this InputStatCollector to count the number of rows it reads. Example usage:

```
root@:26257/> SELECT COUNT(*) FROM test.xyz;
+-------+
| count |
+-------+
|     7 |
+-------+
(1 row)

Time: 257.249037ms

root@:26257/> SET tracing = ON;
SET

Time: 362.575µs

root@:26257/> SELECT x,y,z FROM test.xyz ORDER BY x;
+---+---+------+
| x | y |  z   |
+---+---+------+
| 1 | 1 | NULL |
| 1 | 1 |    2 |
| 1 | 1 |    2 |
| 1 | 2 |    1 |
| 2 | 2 |    3 |
| 4 | 5 |    6 |
| 4 | 1 |    6 |
+---+---+------+
(7 rows)

Time: 207.334037ms

root@:26257/> SHOW TRACE FOR SESSION;

... rest of trace elided ...

| 2018-04-05 20:53:01.571467+00:00 | 21s794ms540µs951ns | waiting for read lock                                                    | [n1,s1,r23/1:/Table/5{2-3}]                                |     | /cockroach.roachpb.Internal/Batch |   13 |
| 2018-04-05 20:53:01.777272+00:00 | 22s345µs429ns      | read completed                                                           | [n1,s1,r23/1:/Table/5{2-3}]                                |     | /cockroach.roachpb.Internal/Batch |   13 |
| 2018-04-05 20:53:01.777435+00:00 | 22s508µs797ns      | stat summary for tableReader input                                       | [client=[::1]:64047,user=root,n1,TableReader]              |     | table reader                      |   11 |
|                                  |                    |                                                                          |                                                            |     |                                   |      |
|                                  |                    |  rows read         7                                                     |                                                            |     |                                   |      |

... rest of trace elided ...
```
And then through jaeger:
screen shot 2018-04-05 at 4 53 55 pm

Note that we can't currently run `SHOW TRACE FOR <QUERY>` in distsql mode, which I hope to fix soon (https://github.com/cockroachdb/cockroach/issues/16562)

Any suggestions to improve the output welcome.

cc @knz @jordanlewis

### CODE REVIEW

**Comment by asubiotto** [comment]
I haven't considered any alternatives to the trace output since I'm not too familiar with logging. Thanks for suggesting the tags, I'll try those out.

**Comment by tschottdorf** [comment]
Sounds good! I just want to reiterate that maybe this just won't work very well. But it's worth a quick experiment. (Even if you add tags, you probably *still* want to print it into the text so that it's properly exposed during `SHOW TRACE FOR`).

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/distsqlrun/data.proto, line 265 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-L9QCi4s83yYVtxJwRFp:-L9QCi4s83yYVtxJwRFq:b-wx2ybc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0dafa624e1c1dd36e2e3af21c6893abe4ea2b1/pkg/sql/distsqlrun/data.proto#L265)):*
> ```protobuf
> message InputStats {
>   // name describes the input whose stats were collected.
>   optional string name = 1 [(gogoproto.nullable) = false];
> ```

Streams that connect distsql processors have a `stream_id`. Perhaps that should be used to identify the stats instead of a `name`. @andreimatei Might have opinions about this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529)*

**Comment by asubiotto** [comment]
I think we need to resolve the question of how to send structured stats data back (e.g. to display in `EXPLAIN`). Initially, I was thinking of having these stats sent back as `ProducerMetadata`. The alternative is to, as @tschottdorf suggests, add tags to the processor's span. I'm thinking that an alternative would be to prefix the stats tags with `stats.` and print those out, to not have to care about any other changes in the stats output. This sounds a bit brittle though. @andreimatei, what do you think?

**Comment by asubiotto** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/data.proto, line 265 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-L9QCi4s83yYVtxJwRFp:-L9fXSt0EwXO1p3T2GF3:b-tchoon) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0dafa624e1c1dd36e2e3af21c6893abe4ea2b1/pkg/sql/distsqlrun/data.proto#L265)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Streams that connect distsql processors have a `stream_id`. Perhaps that should be used to identify the stats instead of a `name`. @andreimatei Might have opinions about this.
</blockquote></details>

I was thinking that this `name` would describe what the stats are about, rather than identify the stats (e.g. "left input of hashJoiner"). The identification will be done at a later stage, and I'm not sure `stream_id`s are enough to do that. The goal is to group a bunch of these stats (`InputStats`, `MemoryStats`, etc...) into a `StatsGroup` identified by a unique processor id and a stage in the logical plan.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529)*

**Comment by tschottdorf** [comment]
> The idea of using span tags for this information seems weird to me. If a processor collects 5 stats, would that be on tag or 5? Would they really look nice in the Jaegar UI? One argument I'd maybe buy was if putting them as tags would let any of the tracing services provide structured searching over them. But I doubt it...
> If anything, I think the concept of span baggage items is closer in intent to this use case. But I don't know if tracers render baggage at all.

Could you elaborate on why that seems weird to you? Think of a span like a `struct { messages []string, tags map[string]string }`. You would use a tag for structured information, which this is. And I think you would have a tag for each metric you're collecting. Also, this isn't limited to `DistSQL`. For example, you may want your `SHOW TRACE FOR COUNT(*)` to tell you how many RocksDB tombstones were skipped over. You get a snowball trace bag, and simply add up the corresponding values. How to aggregate could be obvious from the tag name: `count.<anything>`.

For example, if you want to know how many rows you've read, you let every tablereader's span emit a count `count.read` (or whatever). Building something `DistSQL` specific would be unfortunate.

Baggage items are not the right choice here. The storage layer does not need to know how many rows the table reader on top of it has already read.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-:-L9fkyn1AQokxKe00iVt:b-48o7i3)*

**Comment by andreimatei** [comment]
> Could you elaborate on why that seems weird to you? 

My mind is not set on this, so let me ask you a question in return: any log message provides some information (at the very lease its presence/absence is a bit). What nuggets of this information should be tags?

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-:-L9frGRz8C0qrLCYC-PU:b9tiyvl)*

**Comment by asubiotto** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/data.proto, line 265 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-L9QCi4s83yYVtxJwRFp:-L9fnbQA9JRnsRw0xyYh:b-8rqdob) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0dafa624e1c1dd36e2e3af21c6893abe4ea2b1/pkg/sql/distsqlrun/data.proto#L265)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

An "input" is a stream, right? So I think it makes sense to rename this to `StreamStats` and put a `stream_id` in it...
I think the concept of a `StatsGroup` probably makes sense, but I don't think that's in conflict with the `StreamStats`?
</blockquote></details>

TIL, I thought streams were only remote. It's not in conflict, but I'm not sure what we get out of having a `stream_id` here when I'm going to add identifiers for a group of stats later. Also, taking this PR as a specific example, not all `InputStats` will correspond to a stream. Here, the `tableReader` doesn't have an input from a plan perspective but we still want to collect these stats from its interaction with the `rowFetcher`. I think it's better to leave this as it is and there's no harm in keeping it general.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529)*

**Comment by tschottdorf** [comment]
Log messages are meant for human consumption and so their form can change from one day to the next (you don't go around wondering whether changing a `log.Event` will mess up some parsing somewhere else). For span tag keys the semantics are that they are a label for which there is a registry (i.e. you don't just make them up free-form). Span tags are represented by a map so they are used for key lookup while events are not supposed to be searched. I think you'll find that represented in how jaeger and lightstep interpret tags; they are sensitive to certain standard tags.

I don't think that you're seriously suggesting that we don't use tags and instead parse the information out of log messages because well, not having to do that is exactly why tags exist.

See https://github.com/opentracing/specification/blob/master/semantic_conventions.md for some intuition about span tags. Tags are usually something like `component`, `db.statement`, `user`, `http_code`, etc. Using it to propagate information that can be accumulated is not something mentioned there, but it seems a reasonable fit.

Take a look at the tentative API below. We should show the tags in`SHOW TRACE` just before the span closes (because in the ordinary `SHOW TRACE FOR` that's kind of what you want,  you don't want it aggregated -- it's the raw view of the timeline).

```go
const keysRead = 12515 // example
log.CountEvent(ctx, "tablereader.keys", keysRead)
// ^- calls
// (opentracing.Span).SetTag("count.tablereader.keys", fmt.Sprintf("%v", keysRead))
```

But the upside is that you can imagine running (mod syntax bikeshed) `SHOW TRACE (STATS) FOR SELECT COUNT(*) ...` and get something like

```
metric                    | value
--------------------------+---------
count.tablereader.keys    | 12345
count.replicas.contacted  | 591
count.requests.           | 25
count.writes              | 3
...
```

I'm not sure what everyone else's experience is, but I've often wanted to isolate specific information from a trace and that has always been a problem since everything is currently unstructured. Would be good to change that.

This proposal isn't perfect because what if `CountEvent` is called multiple times for a span? We don't necessarily want to have to parse the string, add, and re-encode it. Maybe that's just not something that should be done? But I think some version of that proposal should be feasible, and we would make a central registry of tags and tie it all together that way. I'd prefer that over cooking up some DistSQL-specific mechanism.

Happy to chat about this more and help out if what I'm proposing is determined worth a shot but hits a snag.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-:-L9g-KEm3mzcv6cqY0Ug:b-in7l5e)*

**Comment by andreimatei** [comment]
> you don't go around wondering whether changing a log.Event will mess up some parsing somewhere else

Well, actually, we already have logs that we can't change willy-nilly because of the damn "KV tracing" - those are logs selected by some regex.
I always thought the implementation of KV tracing in particular was a bad idea, but I've also thought that as tracing starts being used for testing more and more (which it already is), we should have a set of messages for which the format string is a constant shared by the code doing the logging and by a "trace comprehension" library.

Anyway, as I was telling you, I am inspired by the idea of doing something for these stats which is not specific to DistSQL and also about a metrics-like API, and I guess that reflecting these things in tags rather than messages makes sense. In fact, I think we should access all the metrics that we already have through such an API so that the metrics that a request contributed to are reflected in that request's trace. "What if CountEvent is called multiple times for a span" is something that we really need to decide on though, as is what we want to aggregate per span and what we want to aggregate across spans too. For example, when I run a `SELECT`, I want to see how many ranges were touched as a top-level summed up value (at least summed up across all KV requests done by a KV fetcher).

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-:-L9gM-zM88KNMTDywAfk:b1nk1bb)*

**Comment by knz** [comment]
@tschottdorf while I am agnostic on whether tags are the best way to do things, I'd like to point out that our current implementation of tags (using a linked list of tag structs implementing the Context interface, which need to be traversed to arrive to the actual context) is not performance-friendly with larger tag sets. 

Until we solve that implementation problem I'd say we shouldn't use tags _unless_ a specific benchmark measures the corresponding overhead.

**Comment by tschottdorf** [comment]
@knz you're talking about the wrong tags 😄 My "tags" are `opentracing` span tags. They are internally backed by a `map[string]string`.

On a related note though, I was thinking what we are really winning by the use of opentracing tags and it's not much. Sure, the various opentracing-compatible tools will allow us to search spans by tag which is nice. But for a metrics-y use case, that seems mostly not very interesting, and being forced into all-strings is pretty terrible for things that are mostly integers.

So what if instead we put a struct with performance counters in (our impl of) span which is then recorded in `RecordedSpan`? I think this means that we need to widen the `opentracing.Span` interface, but that seems acceptable. We won't get the "benefit" of having these counters show up on lightstep or wherever, but that seems OK (and we could emulate it by also writing a tag whenever a counter is used).

@andreimatei, what do you think? This seems relatively straightforward to prototype.

**Comment by asubiotto** [comment]
@tschottdorf I think this `RecordedSpan` idea is the way to go because of the ability to have any layer add its own stats (not just distsql) and keep the benefits of structuring these stats as protos. This PR is in line with the idea of adding these stats to a proto so I don't think there is any extra work to do at this stage. I appreciate the input.

@solongordon, this PR is ready for a review after I resolve the merge conflicts.

**Comment by solongordon** [comment]
:lgtm: Couple quibbles but looks like a good start in general.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsqlrun/stats.go, line 57 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-L9qMK6eA55LT76s2Lug:-L9qMK6eA55LT76s2Luh:b-95l7r0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ac1bb36ad6c5b7973478727858a293e2b987556/pkg/sql/distsqlrun/stats.go#L57)):*
> ```Go
> func (is InputStats) SummarizeStats() string {
> 	var buffer bytes.Buffer
> 	buffer.WriteString(fmt.Sprintf("stat summary for %s\n", is.Name))
> ```

Nit: Do you know what the deal is with the blank line in the trace output?

---

*[pkg/sql/distsqlrun/stats.go, line 58 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-L9qMUpF4zNaOR0iSI80:-L9qMUpF4zNaOR0iSI81:b-45dbh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ac1bb36ad6c5b7973478727858a293e2b987556/pkg/sql/distsqlrun/stats.go#L58)):*
> ```Go
> 	var buffer bytes.Buffer
> 	buffer.WriteString(fmt.Sprintf("stat summary for %s\n", is.Name))
> 	buffer.WriteString(fmt.Sprintf("%10s%10d", "rows read", is.NumRows))
> ```

I would personally find a simple "rows read: 7" format to be more readable, but I'm also happy to wait on bikeshedding this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-:-L9qQE4P0dyT5WU1MT4O:b-nqvjel)*

**Comment by asubiotto** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsqlrun/stats.go, line 57 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-L9qMK6eA55LT76s2Lug:-L9vY3DB2Hq0U3JTtyDB:b-6tjtu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ac1bb36ad6c5b7973478727858a293e2b987556/pkg/sql/distsqlrun/stats.go#L57)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: Do you know what the deal is with the blank line in the trace output?
</blockquote></details>

No idea. I changed to follow the same format as runtime stats:
```
320 I180412 20:25:00.604783 230 server/status/runtime.go:219  [n1] runtime stats: 238 MiB RSS, 163 goroutines, 94 MiB/45 MiB/164 MiB GO alloc/idle/total, 96 MiB/134 MiB CGO alloc/total, 89.70cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (0x)
```

---

*[pkg/sql/distsqlrun/stats.go, line 58 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529#-L9qMUpF4zNaOR0iSI80:-L9vYCFg0a134vhXTb2k:b9ykp6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ac1bb36ad6c5b7973478727858a293e2b987556/pkg/sql/distsqlrun/stats.go#L58)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I would personally find a simple "rows read: 7" format to be more readable, but I'm also happy to wait on bikeshedding this.
</blockquote></details>

Changed the format, I agree with you. Had the width to make more stats easier to read.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24529)*

**Pull request merged**
