### PR TITLE
coldata,workload/tpcc: more allocation savings

### PR DESCRIPTION
**Pull request by danhhz**
Okay, this is all I have for now. See the individual commits for details. Note that we can now generate the ~80MiB dataset for one tpcc warehouse using less than 1MB of allocations, which is pretty cool.

```
name                             old time/op    new time/op    delta
InitialData/tpcc/warehouses=1-8     481ms ± 4%     388ms ± 1%  -19.38%  (p=0.000 n=5+14)

name                             old speed      new speed      delta
InitialData/tpcc/warehouses=1-8   198MB/s ± 4%   284MB/s ± 1%  +43.74%  (p=0.000 n=5+14)

name                             old alloc/op   new alloc/op   delta
InitialData/tpcc/warehouses=1-8    74.6MB ± 0%     0.9MB ± 0%  -98.78%  (p=0.000 n=4+13)

name                             old allocs/op  new allocs/op  delta
InitialData/tpcc/warehouses=1-8     1.48M ± 0%     0.06M ± 0%  -95.91%  (p=0.000 n=5+15)
```

Touches #34809

### CODE REVIEW

**Comment by danhhz** [comment]
Fixed the test, this should be ready to go

**Review by jordanlewis — APPROVED** [review]
:lgtm: nice

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37372#-:-LeTZb6wEDdB5UZ-umYR:bb76hxo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/workload/tpcc/random.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37372#-LeTZLL8E4v3qG3un2Pb:-LeTZLL8E4v3qG3un2Pc:b-8w0oq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd93218e616b00cb4c3d24a43edfb439e4cc767e/pkg/workload/tpcc/random.go#L136)):*
> ```Go
> 
> // See 4.3.2.3.
> func randCLastSyllables(n int, a *bufalloc.ByteAllocator) []byte {
> ```

nit: while you're changing this, a summary would be useful - stared at this to try to understand and had to read the spec.

```
Given a number between 0 and 999, each of the three syllables is determined by the corresponding digit in the three
digit representation of the number. For example, the number 371 generates the name PRICALLYOUGHT, and the
number 40 generates the name BARPRESBAR.
```

**Review by danhhz — COMMENTED** [review]
TFTR!

bors r=jordanlewis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37372#-:-LeTaN6IBcwO2ITV1X3U:b-tsoej1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/workload/tpcc/random.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37372#-LeTZLL8E4v3qG3un2Pb:-LeTaMDw-qaH-RWdpCrR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd93218e616b00cb4c3d24a43edfb439e4cc767e/pkg/workload/tpcc/random.go#L136)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: while you're changing this, a summary would be useful - stared at this to try to understand and had to read the spec.

```
Given a number between 0 and 999, each of the three syllables is determined by the corresponding digit in the three
digit representation of the number. For example, the number 371 generates the name PRICALLYOUGHT, and the
number 40 generates the name BARPRESBAR.
```
</blockquote></details>

Done.

**Comment by danhhz** [comment]
I think bors ignored me.

bors r=jordanlewis

**Comment by danhhz** [comment]
TestLint oom

bors r=jordanlewis

**Comment by danhhz** [comment]
TestLint oom again. Trying this one more time before I start looking into this more closely (wonked teamcity agent or what have you)

bors r=jordanlewis

**Comment by danhhz** [comment]
I think bors just hates this pr

bors r=jordanlewis

**Comment by danhhz** [comment]
🙌

**Pull request merged**
