### PR TITLE
sql: implement SQL syntax for REGIONAL BY ROW ON col

### PR DESCRIPTION
**Pull request by otan**
Implement the syntax and aliases for `REGIONAL BY ROW ON col`, which
return an unimplemented error as they are not yet implemented.

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
cc @andyyang890 what we peer programmed today!

**Review by ajstorm — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58623#-:-MQY8gO02A1DFMTT2FtX:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

**Review by ajstorm — APPROVED** [review]
:lgtm:  this time with feeling.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58623#-:-MQY8pSm0zITHUxK61kc:b-wz5uba)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

**Comment by otan** [comment]
thanks

bors r=ajstorm

**Comment by otan** [comment]
hmm flaky again D:

bors r=ajstorm

**Pull request merged**
