### PR TITLE
types: give REFCURSOR its own type family

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: prepare cursor name generation for REFCURSOR type family

This patch removes the case statement that checks whether a cursor
name is NULL before calling into `plpgsql_gen_cursor_name` because the
builtin already checks whether the argument is NULL, and `REFCURSOR`
will (correctly) not support comparisons after we add a new type family
for it. The return type for the call to `plpgsql_gen_cursor_name` is
also changed from `String` to `Refcursor`.

Informs #111560

Release note: None

#### tree: add REFCURSOR to the list of parsable string types

This patch adds the new `REFCURSOR` data type to the list of types that
a string constant can have. This will allow constant values to avoid
an explicit cast to `REFCURSOR` in cases when the context expects a
`REFCURSOR`, e.g. inserting into a `REFCURSOR` column or calling a
routine with a `REFCURSOR` parameter. Example:
```
CREATE FUNCTION f(curs REFCURSOR) RETURNS REFCURSOR AS $$
  SELECT curs;
$$ LANGUAGE SQL;

-- This cast was necessary before:
SELECT f('foo'::REFCURSOR);

-- Now this works:
SELECT f('foo');
```

Informs #111560

Release note: None

#### types: give REFCURSOR its own type family

Previously, REFCURSOR shared a type family with the string-like types.
However, since it can't be implicitly casted to and from string types in
all cases, it needs to have its own family (since types within a family
must be compatible). This patch adds the new `RefCursorFamily`, and
follows the example of the PG_LSN type in plumbing it throughout the
SQL layer.

Informs #111560

Release note: None

#### tree: disallow and test comparison operators for REFCURSOR

The `REFCURSOR` data type does not support comparisons apart from a
few edge cases like `'foo'::REFCURSOR IS NULL`. Example:
```
postgres=# SELECT 'foo'::REFCURSOR = 'foo'::REFCURSOR;
ERROR:  operator does not exist: refcursor = refcursor
```
The previous commit that added the `RefCursorFamily` type family already
effectively removed support for most comparisons; this commit also
prevents the `IS / IS DISTINCT FROM` variants from being used on a
`REFCURSOR` expression. Note that postgres supports a few cases with
`NULL` as mentioned above. However, this case seems unimportant, so I
leave it as a TODO for now.

This commit also adds tests for various comparisons involving `REFCURSOR`.

Informs #111560

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
The first commit is #111884.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 8 of 27 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111906)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @DrewKimball, @mgartner, and @rharding6373)

___
*[`pkg/sql/sem/tree/parse_string.go` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111906#-Ng4j0QD24-KIdU2A1-L:-Ng4j0QD24-KIdU2A1-M:b5yj33y) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e4e2f44f9eba4f1ec3441a13f138775d2a60c5e/pkg/sql/sem/tree/parse_string.go#L73)):*
> ```Go
> 		d, err = ParseDPGLSN(s)
> 	case types.RefCursorFamily:
> 		return NewDRefCursor(s), false, nil
> ```

nit: in this method we don't return from within the switch stmt, so I wouldn't do it for consistency here too.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111906)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @rharding6373, and @yuzefovich)

___
*[`pkg/sql/sem/tree/parse_string.go` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111906#-Ng4j0QD24-KIdU2A1-L:-Ng5srSwEy7Qg-7e6Xzt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e4e2f44f9eba4f1ec3441a13f138775d2a60c5e/pkg/sql/sem/tree/parse_string.go#L73)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: in this method we don't return from within the switch stmt, so I wouldn't do it for consistency here too.
</blockquote></details>

Done.

**Comment by rharding6373** [comment]
From the tests it looks like there are a few places where the refcursor family is missing or built-in functions haven't been updated to return the new type. Pinging to bring this to your attention in case it isn't something you're looking into already.

**Review by michae2 — COMMENTED** [review]
> Reviewed 30 of 30 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111906)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @DrewKimball, @mgartner, @rharding6373, and @yuzefovich)

___
*[`pkg/util/parquet/testutils.go` line 366 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111906#-Ng6Tptf5VI03hM3ZL33:-Ng6Tptf5VI03hM3ZL34:b2g58yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0199252e529e956c8bc1232e2d6b688110073219/pkg/util/parquet/testutils.go#L366)):*
> ```Go
> 		// REFCURSOR is implemented using DOidWrapper.
> 		if wrapper.Oid != oid.T_refcursor {
> 			return unwrapDatum(wrapper.Wrapped)
> ```

Why is REFCURSOR implemented using DOidWrapper?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111906)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @michae2, @rharding6373, and @yuzefovich)

___
*[`pkg/util/parquet/testutils.go` line 366 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111906#-Ng6Tptf5VI03hM3ZL33:-Ng6hyYOCLg9vrDS_vX0:b-wtt5vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0199252e529e956c8bc1232e2d6b688110073219/pkg/util/parquet/testutils.go#L366)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Why is REFCURSOR implemented using DOidWrapper?
</blockquote></details>

`REFCURSOR` behaves just like a string; the main difference is that it can't be freely casted the way string types can, and that behavior is encoded by the type rather than the underlying datum.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111906)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @michae2, @rharding6373, and @yuzefovich)

___
*[`pkg/util/parquet/testutils.go` line 366 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111906#-Ng6Tptf5VI03hM3ZL33:-Ng6iEkbDaHeXgnNDRy_:b7hfza6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0199252e529e956c8bc1232e2d6b688110073219/pkg/util/parquet/testutils.go#L366)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`REFCURSOR` behaves just like a string; the main difference is that it can't be freely casted the way string types can, and that behavior is encoded by the type rather than the underlying datum.
</blockquote></details>

`DOidWrapper` lets us share the implementation for the datum while also being able to specify type-specific behavior. Up until now it's only been used to change how a type's name is displayed,  but it was intended to be usable for other behavio changes as well.

**Comment by DrewKimball** [comment]
I've moved the commit to allow parsing REFCURSOR constants before the one to add the type family; this decreases the number of test changes that had to be made between commits.

I also added a commit to remove the check for NULL cursor name before calling `plpgsql_gen_cursor_name`, since `plpgsql_gen_cursor_name` already handles that case and `REFCURSOR` doesn't support comparison operators.

**Review by michae2 — APPROVED** [review]
:lgtm: Very nice.

(Don't forget to update the PR description to match the new commit order.)

> Reviewed 38 of 38 files at r9, 35 of 35 files at r10, 33 of 37 files at r11, 3 of 5 files at r12, 3 of 3 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111906#-:-Ng7vtRV81adiGu2hF1T:bjphsxr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rharding6373)

___
*[`pkg/util/parquet/testutils.go` line 366 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111906#-Ng6Tptf5VI03hM3ZL33:-Ng7prt37Rm4Ax3-3G3w:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0199252e529e956c8bc1232e2d6b688110073219/pkg/util/parquet/testutils.go#L366)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`DOidWrapper` lets us share the implementation for the datum while also being able to specify type-specific behavior. Up until now it's only been used to change how a type's name is displayed,  but it was intended to be usable for other behavio changes as well.
</blockquote></details>

Thanks!

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Pull request merged**
