### PR TITLE
sql: attempt to account for memory in crdb_internal.jobs

### PR DESCRIPTION
**Pull request by spaskob**
This is a stop-gap PR to do _some_ memory accounting during the
execution of `crdb_internal.jobs`. It turns out that with hundreds of
databases and hours backups per database, one can easily get to 100k jobs
which are roughly 2-3Kb each. Given the total lack of memory monitoring here,
this situation can lead to OOMs.

Ideally we'd track the memory usage by the internal executor. That's a
bigger change left for later. Also ideally we'd paginate the output.

Touches #44166.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45758)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/sql/crdb_internal.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45758#-M1gmJdh--Em8Gz-sISx:-M1gmJdh--Em8Gz-sISy:bo9xjpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb186ae9369301776724e6a0b92d15e983cbdde1/pkg/sql/crdb_internal.go#L490)):*
> ```Go
> 			for field, d := range r {
> 				// NB: Add the datum size twice to count the fact that we already allocated
> 				// it once and we're about to
> ```

This comment seems to end before it should
___
*[pkg/sql/crdb_internal.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45758#-M1gmBTN4FGfQM8MLlhr:-M1gmBTN4FGfQM8MLlhs:b-qf7uwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb186ae9369301776724e6a0b92d15e983cbdde1/pkg/sql/crdb_internal.go#L493)):*
> ```Go
> 				datumSize := int64(d.Size())
> 				if field == payloadFieldN || field == progressFieldN {
> 					datumSize *= 2
> ```

I don't understand this... why? Also if you insist on doing this, can we just do it after the loop rather than this comparison stuff.

**Review by ajwerner — APPROVED** [review]
:lgtm: mod Jordan's comments. Thanks for writing the test. 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45758#-:-M1grKKt8zZZGlCUZW6l:b-hy1dyc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/crdb_internal.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45758#-M1gmJdh--Em8Gz-sISx:-M1gqq-t1c3jGJIvpKVz:bdwjmek) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb186ae9369301776724e6a0b92d15e983cbdde1/pkg/sql/crdb_internal.go#L490)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This comment seems to end before it should
</blockquote></details>

`... unmarshal it and keep that around.`?
___
*[pkg/sql/crdb_internal.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45758#-M1gmBTN4FGfQM8MLlhr:-M1gqU-_1OjHLpny1dOP:bcrlmna) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb186ae9369301776724e6a0b92d15e983cbdde1/pkg/sql/crdb_internal.go#L493)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't understand this... why? Also if you insist on doing this, can we just do it after the loop rather than this comparison stuff.
</blockquote></details>

I did this. I did it because we unmarshal these fields and keep both the marshaled and unmarshaled bits alive. If we zero'd the row datums after unmarshaling then I'd feel better about not counting it but that seems like too much effort. I'm cool with just doubling the row count.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45758)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @jordanlewis)

___
*[pkg/sql/crdb_internal.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45758#-M1gmBTN4FGfQM8MLlhr:-M1h3fx9BbVOhU9EDLKH:b-kqx1q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb186ae9369301776724e6a0b92d15e983cbdde1/pkg/sql/crdb_internal.go#L493)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I did this. I did it because we unmarshal these fields and keep both the marshaled and unmarshaled bits alive. If we zero'd the row datums after unmarshaling then I'd feel better about not counting it but that seems like too much effort. I'm cool with just doubling the row count. 
</blockquote></details>

Oh I see. Yeah I'd just get rid of the "precise" stuff here with the column integer index constants and double the whole size.

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45758)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/crdb_internal.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45758#-M1gmJdh--Em8Gz-sISx:-M1klkWc6pdM43U89MMT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb186ae9369301776724e6a0b92d15e983cbdde1/pkg/sql/crdb_internal.go#L490)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`... unmarshal it and keep that around.`?
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45758#-M1gmBTN4FGfQM8MLlhr:-M1kmWcf6qcRw5954Cuo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb186ae9369301776724e6a0b92d15e983cbdde1/pkg/sql/crdb_internal.go#L493)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Oh I see. Yeah I'd just get rid of the "precise" stuff here with the column integer index constants and double the whole size. 
</blockquote></details>

Done.

**Pull request merged**
