### PR TITLE
sql: introduce hash group-join operator

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR introduces the hash group-join operator (which combines a hash join followed by a hash aggregation when the join's equality columns are the same as aggregation's grouping columns into a single operator) to the execution engines . The optimizer is currently unaware of this new operator - the changes are plumbed only from the DistSQL physical planning. Naive implementations (which simply use a hash joiner followed by a hash aggregator) are introduced to both engines with the proper disk-spilling. The usage of this new operator is gated behind an experimental session variable.

See each commit for details.

Addresses: #38307.

Epic: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: I'm excited to see how this turns out!

> Reviewed 7 of 7 files at r1, 29 of 29 files at r2, 15 of 15 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-:-NJII_mq7MMzwnD4tCna:bp2u9ur)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 109 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJICmq5-O5irpDQMFqY):*
Could we just reuse the same setting? Since this operator is only planned when a hash aggregate would previously have been planned, anyway.
___
*[`pkg/sql/distsql_physical_planner.go` line 1990 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJHxKZWEm4pP2dECTET:-NJHxKZWEm4pP2dECTEU:bcj66sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3c9706adf2a951b3c1c66ac35d557b32890679/pkg/sql/distsql_physical_planner.go#L1990)):*
> ```Go
> 			}
> 			if len(groupCols) == len(orderedGroupCols) {
> 				// We will plan streaming aggregation.
> ```

[nit] We may want a TODO here to consider whether an ordered aggregation is always better when this is supported in the optimizer. Consider a case where the join produces a huge result set that gets grouped down to very few rows - it might be better to avoid materializing the join result, especially in a distributed setting.
___
*[`pkg/sql/colexec/hash_group_joiner.go` line 113 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJIDreK2f6p4tzkJWcv:-NJIDreK2f6p4tzkJWcw:b-m7ishf) ([raw file](https://github.com/cockroachdb/cockroach/blob/377ca0f2856c1796c15278d89e0df8892f32097b/pkg/sql/colexec/hash_group_joiner.go#L113)):*
> ```Go
> 		return h.hj.ExportBuffered(input)
> 	}
> 	if !h.hjLeftSource.zeroBatchEnqueued {
> ```

[nit] not related to this PR, but should we make this check part of the spilling queue interface for convenience?
___
*[`pkg/sql/colexec/colbuilder/execplan.go` line 1360 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJIHQj46BclMjbIGhiC:-NJIHQj46BclMjbIGhiD:bv3igom) ([raw file](https://github.com/cockroachdb/cockroach/blob/377ca0f2856c1796c15278d89e0df8892f32097b/pkg/sql/colexec/colbuilder/execplan.go#L1360)):*
> ```Go
> 						// TODO(yuzefovich): think through whether the hash
> 						// group-join needs to maintain the ordering.
> 						execinfrapb.Ordering{}, /* outputOrdering */
> ```

Will order-sensitive aggregate functions run into problems here?
___
*[`pkg/sql/colexec/colexecjoin/crossjoiner.go` line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJI9eIF5DMSHnDSamKr:-NJI9eIF5DMSHnDSamKs:b-nha5l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6eef030677eef5f3471140ab7cdaf13154328cfb/pkg/sql/colexec/colexecjoin/crossjoiner.go#L290)):*
> ```Go
> 
> func (c *crossJoiner) Reset(ctx context.Context) {
> 	if r, ok := c.InputOne.(colexecop.Resetter); ok {
> ```

[nit] would it be more convenient to add this logic to the `TwoInputInitHelper`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93483)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`-- commits` line 109 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJICmq5-O5irpDQMFqY):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Could we just reuse the same setting? Since this operator is only planned when a hash aggregate would previously have been planned, anyway.
</blockquote></details>

Yes, I plan to reuse the same setting in the future, but for now it seems ok to not have the ability to disable the input tuples tracking from the left input. Once the optimized implementation is fleshed out, then we'll add the disabling mechanism - right now it seemed mostly like a waste given that it would have to be effectively rewritten for the optimized implementation anyway.

However, I think that we'll implement "streaming" merge group-join for this use case in the future.
___
*[`pkg/sql/distsql_physical_planner.go` line 1990 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJHxKZWEm4pP2dECTET:-NJIRn60DoYL7yD5mtoS:b16si18) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3c9706adf2a951b3c1c66ac35d557b32890679/pkg/sql/distsql_physical_planner.go#L1990)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] We may want a TODO here to consider whether an ordered aggregation is always better when this is supported in the optimizer. Consider a case where the join produces a huge result set that gets grouped down to very few rows - it might be better to avoid materializing the join result, especially in a distributed setting.
</blockquote></details>

Hm, I believe the hash join is not expected to provide any ordering, so I don't think it is actually possible for us to plan the ordered aggregation on top of the hash join. I expanded the comment.
___
*[`pkg/sql/colexec/hash_group_joiner.go` line 113 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJIDreK2f6p4tzkJWcv:-NJIVLnR6jCknkWwPnsM:b-7njitb) ([raw file](https://github.com/cockroachdb/cockroach/blob/377ca0f2856c1796c15278d89e0df8892f32097b/pkg/sql/colexec/hash_group_joiner.go#L113)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] not related to this PR, but should we make this check part of the spilling queue interface for convenience?
</blockquote></details>

`colcontainer.Queue.Enqueue` interface asks for the zero-batch to be always added at the end, and I think it's a fair requirement (so that the queue knows when to flush to disk). However, `SpillingQueue` is a utility wrapper that could easily do this, so I left a TODO.
___
*[`pkg/sql/colexec/colbuilder/execplan.go` line 1360 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJIHQj46BclMjbIGhiC:-NJIVuUv71ToTnyQob2w:b-6qip1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/377ca0f2856c1796c15278d89e0df8892f32097b/pkg/sql/colexec/colbuilder/execplan.go#L1360)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Will order-sensitive aggregate functions run into problems here?
</blockquote></details>

Are you thinking about aggregate functions that support `ORDER BY` clause (i.e. something like `array_agg(c1 ORDER BY c2)`)? That probably shouldn't be affected given that the input is the hash join with arbitrary order (plus such functions are handled internally as window functions).

When I left this comment, I was concerned about a bug that was fixed in #63372 where we had an issue where the external hash aggregator didn't maintain the ordering on the prefix of grouping columns that was already ordered by the input. I believe there shouldn't be a correctness issue on top of the hash join but wanted to remind myself to re-evaluate this later.
___
*[`pkg/sql/colexec/colexecjoin/crossjoiner.go` line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJI9eIF5DMSHnDSamKr:-NJIUyF07UdDUEVMJ8Tp:b-cd4e7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6eef030677eef5f3471140ab7cdaf13154328cfb/pkg/sql/colexec/colexecjoin/crossjoiner.go#L290)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] would it be more convenient to add this logic to the `TwoInputInitHelper`?
</blockquote></details>

Done. I also removed now-redundant references to the input operators in the merge join.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93483)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/colexec/hash_group_joiner.go` line 108 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJIXbz59dkMgmTa8eM4:-NJIXbz6E3AVSBRJhHpR:b-tw8yli) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbab32345d9c908a9659a700cf54324749d1593/pkg/sql/colexec/hash_group_joiner.go#L108)):*
> ```Go
> // perform the export.
> func (h *hashGroupJoiner) ExportBuffered(input colexecop.Operator) coldata.Batch {
> 	if h.ha.ht != nil {
> ```

Added minor improvement here to be in sync with `hashAggregator.ExportBuffered`.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 34 of 34 files at r5, 32 of 32 files at r6, 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-:-NJKBedQ1FfYZC0k8oYK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/colexec/colbuilder/execplan.go` line 1360 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93483#-NJIHQj46BclMjbIGhiC:-NJKAoF4AZiq9Lm2zKWL:by7ao8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/377ca0f2856c1796c15278d89e0df8892f32097b/pkg/sql/colexec/colbuilder/execplan.go#L1360)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Are you thinking about aggregate functions that support `ORDER BY` clause (i.e. something like `array_agg(c1 ORDER BY c2)`)? That probably shouldn't be affected given that the input is the hash join with arbitrary order (plus such functions are handled internally as window functions).

When I left this comment, I was concerned about a bug that was fixed in #63372 where we had an issue where the external hash aggregator didn't maintain the ordering on the prefix of grouping columns that was already ordered by the input. I believe there shouldn't be a correctness issue on top of the hash join but wanted to remind myself to re-evaluate this later.
</blockquote></details>

I think you're right about that, good point.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
