### PR TITLE
kvserver: allow gc of data at timestamp < lease start

### LINKED ISSUE #82954: kvserver: can't gc data with threshold older than current lease time
**Describe the problem**

The `gcTimestamp.Less(lease.Start.ToTimestamp())` bit below looks faulty:

https://github.com/cockroachdb/cockroach/blob/3c395d508f8c33c31a2c422d8f806d2ffe66ac6a/pkg/kv/kvserver/replica_protected_timestamp.go#L135-L164

The code here wants to ensure that the timestamp record we read was read within the current lease interval. If we had a record with protection at now-30d, we'll never GC this data since no current lease will have a start time going that far back. We've seen clusters with PTS record timestamps going this far back.

Jira issue: CRDB-16753

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #82954.

The code here wants to ensure that the timestamp record we read was read within the current lease interval. Consider if we had a record with protection stuck at now()-30d (we've seen this in an internal incident due to a separate bug), we'll never GC this data since no current lease will have a start time going that far back. If the oldest timestamp that was protected for a given keyspan never crossed the current lease start time (i.e. always trailed the lease start time by N hours), we'd never GC.

We found this bug where we had a PTS record with a very old timestamp lying around, and instead of trying to clear out and incur a large volume of MVCC GC all at once, we thought it’d be better to walk up it’s timestamp to the current time in 24h increments to only allow a day’s worth of garbage to be GC-ed at a time. When doing so we were surprised to see that no GC was occurring. Manual enqueuing of replicas surfaced an error about not GC-ing because the timestamp we were trying to GC at was < the lease timestamp, which seemed buggy. This bug has existed since 2019 (when the protected timestamps system was introduced), we didn't see this have production impact as we'd have to get to a regime where the timestamp being protected over a keyspan would have to always trail the lease start time by a fixed amount. In 21.2 and earlier releases, I'm not sure if this was possible in practice. In 22.1 and beyond, we're doing more involved things with PTS records (like chaining them: https://github.com/cockroachdb/cockroach/pull/79976) so it's possible we'd have seen this bug going forward.

Release note (bug): Fix a rare bug where it was possible to accrue MVCC
garbage for much longer than needed.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]

**Review by adityamaru — APPROVED** [review]

**Comment by andreimatei** [comment]
Even though the ship has sailed for the commit message, can we please get a better explanation in the PR description? :)
The issue was that `read.readAt` was being adjusted backwards before being checked against the lease, and this adjustment, while valid for GC purposes, was not valid for the check's purposes? The linked issue does not help much because, if you read it with fresh eyes, you'll notice how terse and unclear it is - even though it also includes superfluous about how there's clusters with pts at `-30 days`. If I understand correctly, there's no need for any dramatic durations here to get the gc to not work right, but just a lease transfer (or node restart or whatever) while a backup is running?

And I think we need to do better with the release note... :) You say "much longer", but is it actually "for ever"? Or until the backup finishes? I think we need to say something about backups in there, right?

**Comment by irfansharif** [comment]
Reworded the PR message + issue text to spell things out a bit more. Does it help? I don't think backups are directly implicated, neither are changefeeds (other user of pts records). The only reason we saw this bug was because of another bug where we let a very old PTS timestamp stick around and attempted to manually walk up the timestamp for the record out of an abundance of caution. I can't think of situations in 21.2 and earlier where _this_ bug would've affected clusters; as I understand it the PTS record would have to always trail the lease start time by a fixed amount, which I'm not sure was possible (@miretskiy or @adityamaru can keep me honest). We suspect this bug _could_ come up more prominently in clusters running 22.1 since we now chain PTS records as part of scheduled backups  (https://github.com/cockroachdb/cockroach/pull/79976), though I don't have a repro or an incident to point to. I still don't understand what the causes are for stuck PTS records, or what in changefeed's current use of PTS could cause the timestamp to fall further and further back.

**Comment by irfansharif** [comment]
> I still don't understand what the causes are for stuck PTS records, or what in changefeed's current use of PTS could cause the timestamp to fall further and further back.

Yevgeniy points me to https://github.com/cockroachdb/cockroach/issues/82834 (applicable only to 21.2 and earlier) and says it's no longer a problem in 22.1 because of our "active PTS management". PTS timestamps now trail the underlying changefeed's frontier timestamp more closely -- whenever changefeed checkpoints to new frontier, we update the protected timestamp, pulling it up to the timestamp of changefeed itself. This update happens once every 10m by default since we don't necessarily want to update PTS records too often.

https://github.com/cockroachdb/cockroach/blob/1634866e44a08d195491cefb4ff16ad9696c6e21/pkg/ccl/changefeedccl/changefeed_processors.go#L1264-L1268

**Comment by andreimatei** [comment]
Thank you!
But for my own edification, I still don't really get it. Is it not the case that, as soon as a lease moves on a range with a protected timestamp, we no longer perform GC on the respective range? Like, if ts 100 is protected, and the lease moves at 200, is it not the case that the bug caused us to not GC the [0-100) window, as we should? Your explanations allude to more conditions being necessary for the bug to be triggered?

**Comment by irfansharif** [comment]
Protected timestamp records don't "stick around" in practice (mod CDC bugs linked above, and in 22.1+ with scheduled backups chaining records together). 

> Like, if ts 100 is protected, and the lease moves at 200, is it not the case that the bug caused us to not GC the [0-100) window, as we should? 

What you'd see instead is that the protection record for ts=100 would soon be dropped, and the GC would happen over [0-100) assuming it's outside the GC TTL.

**Comment by andreimatei** [comment]
> Protected timestamp records don't "stick around" in practice

Protected timestamps can hang around indefinitely if you pause a backup for example, right?
Anyway, sounds like I understood the issue.

**Comment by irfansharif** [comment]
Added a regression test over at #83106 to hopefully help the next fellow.

**Pull request merged**
