### PR TITLE
Bump Go to 1.6

### PR DESCRIPTION
**Pull request by tamird**
- Remove dependency on cockroachdb/yacc
- Use Chromium's bleeding-edge clang; it is needed because of a bug in
  MemorySanitizer (https://llvm.org/bugs/show_bug.cgi?id=24155)

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3563)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM, but is this premature? Go-1.6 is only at beta1. 

---

Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/testdata/distinct, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-K6ohURBxq8G3KLbmScM:-K6ohURBxq8G3KLbmScN:-1175831706) ([raw file](https://github.com/cockroachdb/cockroach/blob/b86d55e7ea0a8d3d5ee8d188d97d750c8a359329/sql/testdata/distinct#L57)):*
What's the reason for this change?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-:-K6ohgUpMhewhURmQ-Au:-391942660)*

**Comment by tamird** [comment]
Maybe so. I'm still trying to get this working in CI (weird cache issues?), but if it does, any reason not to proceed?

---

Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/testdata/distinct, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-K6ohURBxq8G3KLbmScM:-K6oi0PhmjVYQU08xcqV:-1172549546) ([raw file](https://github.com/cockroachdb/cockroach/blob/b86d55e7ea0a8d3d5ee8d188d97d750c8a359329/sql/testdata/distinct#L57)):*
This order was not previously well-defined (since not all values of `y` are distinct) and the result order changed when I bumped to 1.6beta1.

The root cause is probably this bit from the release notes:
> In the sort package, the implementation of Sort has been rewritten to make about 10% fewer calls to the Interface's Less and Swap methods, with a corresponding overall time savings. The new algorithm does choose a different ordering than before for values that compare equal (those pairs for which Less(i, j) and Less(j, i) are false).

> Updating: The definition of Sort makes no guarantee about the final order of equal values, but the new behavior may still break programs that expect a specific order. Such programs should either refine their Less implementations to report the desired order or should switch to Stable, which preserves the original input order of equal values.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-:-K6oiQa1h17yz-0jy5Zv:-1701533206)*

**Comment by petermattis** [comment]
Well, we're working on our own stability so it wouldn't be helpful to be butting up against any stability issues caused by the 1.6 beta. Turning the question around, is there an urgency to switching to go1.6 vs waiting until the actual release (sometime in February)? I think it's great to have tested against go1.6 so we're not surprised by anything in the release, but actually switching development feels premature.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-:-K6oiuRHbcn68fXX-bDP:-829481612)*

**Comment by tamird** [comment]
Fair enough. I'll cherry pick everything but the actual version change into a new PR.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-:-K6okOWwF7ZvwIoHEPWZ:1197202813)*

**Comment by petermattis** [comment]
Cool. I wonder if it would be useful to try the new memory sanitizer support in go1.6: https://tip.golang.org/doc/go1.6#compiler

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-:-K6olRhTY6sglSnQaRrY:-911022233)*

**Comment by tamird** [comment]
Yeah, I'm going to try that once I sort out the CI issues observed here.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-:-K6omX4SeGo3IcnELLE_:920669905)*

**Comment by tamird** [comment]
Well, I got msan support working, but it's spewing a ton of use-of-uninitialized-value warnings which are quite opaque. Not sure how to get useful stack traces from this. Going to put this on hold until 1.6 is out.

**Comment by tamird** [comment]
Current status of this: https://github.com/golang/go/issues/13815

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KAmJMMX2fVPcy5GKY0L:1872650029) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
This seems dangerous. It looks like you're assuming the caller has passed you a buffer (`p`) that is large enough. And you're doing this on every call to `Read`, not just at the beginning of the connection.

Definitely sprinkle some comments in this code as to what is going on and why.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tschottdorf** [comment]
Reviewed 17 of 17 files at r1, 16 of 16 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KAmL7XT4pi3MGh50xPy:636991761) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
yeah, this needs a little bit more state to potentially read the first line in more than one go, though in practice it'll probably never happen.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KAmLYg9UU5KPTRRH5EU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by bdarnell** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KAmLEKTdtnkWiv6dLiz:-1697170858) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
Yeah, you need to drop the TeeReader after the initial read so you don't keep filling up the replay buffer.

I'm fine with the assumption that the http/2 connection prefix comes in one `Read`, although there should be a comment that this probably won't work with a TLS connection (due to 1/n-1 splitting)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tamird** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KAmLpzv6PG1ZD-oohC2:1414356342) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
Oh, to read the line in more than one go? that will definitely never happen in practice, they read around 4k each time.

> Yeah, you need to drop the TeeReader after the initial read so you don't keep filling up the replay buffer.

I'm pretty sure that's not true. Can you elaborate?

> I'm fine with the assumption that the http/2 connection prefix comes in one Read, although there should be a comment that this probably won't work with a TLS connection (due to 1/n-1 splitting)

That comment seems like overkill, there is already a giant comment that says "this assumes we're not in TLS".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by bdarnell** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KAmNJyt3CPbKSyv3KVu:-1527945857) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
In the GRPC case, we switch from `TeeReader` to `MultiReader`. But if the request is HTTP, we continue to use the `TeeReader` and will write an unbounded amount of data into the replay buffer.  The `if bc.hasRead` path needs to bypass `bc.reader` and read directly from the underlying connection. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tamird** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KAmQGU5Ue0Z2HWJkO_c:802570925) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
Ah, yes, good point, though I put that logic in a slightly different place. PTAL.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[build/Dockerfile, line 16 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmTAA5xMRHhOX46CeG:-KAmTAA5xMRHhOX46CeH:2066443520) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/build/Dockerfile#L16)):*
This is only needed for `msan`, right? I think I'd leave this out for now. (how does it even work with our cgo builds, which choose command line flags on the assumption that the compiler is always gcc on linux?)

---

*[gossip/convergence_test.go, line 48 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmSpilvriKP5ZeFmaa:-KAmSpimR_lG-Kp7Q7pu:-451167969) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/gossip/convergence_test.go#L48)):*
Is this test even doing anything useful any more? We keep bumping this threshold up. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-:-KAmTYrFItBeZK1PeluY:676834233)*

**Comment by tamird** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[build/Dockerfile, line 16 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmTAA5xMRHhOX46CeG:-KAmV2hwyNmbNGcWiIuj:1349718163) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/build/Dockerfile#L16)):*
This is only needed for `msan`, right?

Yeah, but it saves from cutting a new image later.

> which choose command line flags on the assumption that the compiler is always gcc on linux

Can you point to where that assumption is made? That's news to me.

---

*[gossip/convergence_test.go, line 48 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmSpilvriKP5ZeFmaa:-KAmUuf0rbjMetRwWKPK:-1430470795) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/gossip/convergence_test.go#L48)):*
Yeah, I don't know enough about it. Spencer wanted to keep it (we bumped it up in the original gRPC PR).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by bdarnell** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[build/Dockerfile, line 16 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmTAA5xMRHhOX46CeG:-KAmVgYDPixr_p3ZkaWu:-320813482) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/build/Dockerfile#L16)):*
It's mainly the linker flags, and I guess the linker is staying the same here. But we do pass `-Wshorten-64-to-32` on all clang-using platforms. 

https://github.com/cockroachdb/c-rocksdb/blob/c0124c907c74b579d9d3d48eb96471bef270bc25/cgo_flags.go#L22-L26

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 2 files at r6, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KAmYnTKhvFnVLArqvMQ:1737721936) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
You should at least add a comment and assertion about `len(p)`.
We have tests that trigger both paths here now, right (I guess that's how we found out this broke).

---

*[util/net.go, line 61 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmY_lZIbANC2lobbKa:-KAmY_lZIbANC2lobbKb:-882155877) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/util/net.go#L61)):*
stale comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KAmZTO3AOvH1Hs-yH-E:-2018086831) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
what's the difference between an assertion and this slicing? If `p`'s too small, slicing it as I do here will panic, won't it?

This didn't break, I added hasRead just as an optimization.

---

*[util/net.go, line 61 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmY_lZIbANC2lobbKa:-KAmZOQ5T36CRcB8XGG-:2063209057) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/util/net.go#L61)):*
Nah, it's still correct.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[util/net.go, line 61 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmY_lZIbANC2lobbKa:-KAm_dx3gKM6ndvJj69C:-1779631983) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/util/net.go#L61)):*
Oh, it could be the underlying connection. I'll remove.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tamird** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[build/Dockerfile, line 16 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmTAA5xMRHhOX46CeG:-KAmo1X0klaLMDEY76qn:-19555762) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/build/Dockerfile#L16)):*
OK, seems safe, then, This seems to be the only divergent case, too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tamird** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KAo68YYyAjH8qMDX_Bb:-538305246) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
Removed this assumption - all reads should be safe now (because they're not implemented by me :)). This got complicated enough that I added a test.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by petermattis** [comment]
LGTM, just some minor nits.

---

Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[util/net.go, line 37 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAosgl0s8i-Id6yaHPB:-KAosgl1tcwi0nVAsaxR:1013710341) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net.go#L37)):*
We don't usually append the type to our variable names. Any reason to be doing that here? (i.e. `s/FirstLineSlice/FirstLine/g`)

---

*[util/net.go, line 59 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAosyIQ9mbwLPSMWQXW:-KAosyIQ9mbwLPSMWQXX:41169966) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net.go#L59)):*
`limitReader.N` is never going to exceed 32-bits, I think it would be mildly cleaner cast it to an `int` rather than casting `len` to an `int64`.

---

*[util/net.go, line 67 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAotR_151hWD1oaXZcS:-KAotR_151hWD1oaXZcT:-1045570840) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net.go#L67)):*
Is this condition ever false?

---

*[util/net_test.go, line 56 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAotkoMbpQw1FtFQvWQ:-KAotkoMbpQw1FtFQvWR:-1003074935) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net_test.go#L56)):*
`ReadAll` is the easy case. If you want to get a bit more paranoid, read the output a byte at a time. 

---

*[util/net_test.go, line 71 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAou0cQaFiZE-I3RZ3C:-KAou0cQaFiZE-I3RZ3D:-735555795) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net_test.go#L71)):*
No need for the else here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-:-KAou5FLAb1LTDMXI6Gl:1722558596)*

**Comment by tamird** [comment]
Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[util/net.go, line 37 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAosgl0s8i-Id6yaHPB:-KAouaibGecJmOtrL0iV:932744117) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net.go#L37)):*
It made the test easier to follow, since there is a mix of slices and strings that are alternatingly used when one or the other is more convenient.

---

*[util/net.go, line 59 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAosyIQ9mbwLPSMWQXW:-KAougswRdGy4d55ZoQp:-1489245314) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net.go#L59)):*
I'll have to disagree - casting to an `int` requires me to think about the safety of the thing. Casting to an `int64` (the type of limitReader.N`) is statically safe.

---

*[util/net.go, line 67 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAotR_151hWD1oaXZcS:-KAouvKlQdnP5VUCpnbZ:-20855504) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net.go#L67)):*
I believe it is false in the nth read (where n > 0) which comes before the call to `replay`.

---

*[util/net_test.go, line 56 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAotkoMbpQw1FtFQvWQ:-KAovR5u4OknkQMSB_8m:-187294081) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net_test.go#L56)):*
Yeah, OK; Done.

---

*[util/net_test.go, line 71 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAou0cQaFiZE-I3RZ3C:-KAovT__kF5RGmHuX-25:885782116) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net_test.go#L71)):*
Removed now that I'm reading one byte at a time.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by petermattis** [comment]
Review status: 1 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[util/net.go, line 67 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAotR_151hWD1oaXZcS:-KAoye4MUufufyZKcCci:-171280008) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net.go#L67)):*
But if `rc.reader == rc.Conn` you never would have entered the `limitReader, ok` branch.

---

*[util/net.go, line 85 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAoyscDFIHzLsq-8MmG:-KAoyscDFIHzLsq-8MmH:108778410) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3e333f8afd8dce705b1fd23d773f0a2208c666/util/net.go#L85)):*
This comment is mildly confusing in that you never replace `rc.reader` with `rc.Conn` is this block.

---

*[util/net_test.go, line 56 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAotkoMbpQw1FtFQvWQ:-KAozZnPfqgb7t2PYV0b:-312535476) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net_test.go#L56)):*
Add a comment about the desirability of this complexity.

---

*[util/net_test.go, line 60 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAozhAVl2tiQRb6JTF3:-KAozhAVl2tiQRb6JTF4:193026943) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3e333f8afd8dce705b1fd23d773f0a2208c666/util/net_test.go#L60)):*
Any reason you didn't want to return a `[]byte` for your `readAll`? This construct is a bit unusual. If you return a `[]byte` then you could do `output := readAll()`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tamird** [comment]
Review status: 1 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[util/net.go, line 67 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAotR_151hWD1oaXZcS:-KAp-1XZmrZo6IPeLc-R:-95964447) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net.go#L67)):*
Ah, good point.

---

*[util/net.go, line 85 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAoyscDFIHzLsq-8MmG:-KAp-cB09O34w2YRGCp3:378290688) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3e333f8afd8dce705b1fd23d773f0a2208c666/util/net.go#L85)):*
Yeesh, you're right. Fixed.

---

*[util/net_test.go, line 56 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAotkoMbpQw1FtFQvWQ:-KAp2-M3tI4lJ6K4P-fw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/91cc94dc74e4a01aa8fb24388f29f1a5cda56e85/util/net_test.go#L56)):*
Done.

---

*[util/net_test.go, line 60 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAozhAVl2tiQRb6JTF3:-KAp1zatUatI5qCw3kC1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3e333f8afd8dce705b1fd23d773f0a2208c666/util/net_test.go#L60)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by petermattis** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[util/net.go, line 88 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAp32FXT7Vi2XaHcK0w:-KAp32FYfN44cZnpzmSy:-1340445606) ([raw file](https://github.com/cockroachdb/cockroach/blob/edef4895905f6fcb1812f534ade189eb9a9f69c4/util/net.go#L88)):*
If you replaced the reader with `rc.Conn`, `err` will be `nil` here, right?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by bdarnell** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[build/Dockerfile, line 16 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmTAA5xMRHhOX46CeG:-KAp5P_8bUlxHX3btY6N:-1761954290) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/build/Dockerfile#L16)):*
But it's still using a different compiler for builds that go through this docker image than for builds from source  using the default configuration. Installing clang into the docker image is fine but I'd rather not set `CC=clang` except in builds where we are enabling `msan`.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KApEDnZpWcUaN-3WNPc:-26145472) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
Another way to avoid making assumptions about `p` would be to look for the preface in `rc.buf`. That might be simpler than adding and subsequently removing a `LimitReader`  (although I like the way you now inject the host header with the `MultiReader`, so maybe it's not a net win). 

---

*[util/net.go, line 64 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KApFSRE_Ok6eOLZnlT7:-KApFSRE_Ok6eOLZnlT8:372387486) ([raw file](https://github.com/cockroachdb/cockroach/blob/edef4895905f6fcb1812f534ade189eb9a9f69c4/util/net.go#L64)):*
`rc.buf` can now be erased.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by tamird** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[build/Dockerfile, line 16 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmTAA5xMRHhOX46CeG:-KApVa-3xvyhboyck005:1307363095) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd967ba9f84c34cadee1443b6bd07f85bb6af6c4/build/Dockerfile#L16)):*
OK, Done.

---

*[util/net.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAmJMMWT5ovkxzVULA3:-KApVRdr3pd5vLIPNYyg:589370339) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd841b6a3ee58d6f6f369359c38fe8d4e560843b/util/net.go#L60)):*
I don't follow how you'd look for the preface in rc.buf without implementing a limited reader, so left it as-is.

---

*[util/net.go, line 64 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KApFSRE_Ok6eOLZnlT7:-KApVR31nDLEL-cX6DJg:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/edef4895905f6fcb1812f534ade189eb9a9f69c4/util/net.go#L64)):*
Done.

---

*[util/net.go, line 88 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-KAp32FXT7Vi2XaHcK0w:-KAp3WAWpnPXIoUzF17B:1210740924) ([raw file](https://github.com/cockroachdb/cockroach/blob/edef4895905f6fcb1812f534ade189eb9a9f69c4/util/net.go#L88)):*
Ah, it might be, but it could also be `io.EOF`, in case the the LimitReader was fully exhausted before we could fail the match. Updated the test to measure the number of `read` calls and changed this to be more naive (mimicking MultiReader).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563#-:-KAq4lUme6A299Z-brBN:676834233)*

**Comment by tschottdorf** [comment]
Reviewed 7 of 7 files at r9, 2 of 7 files at r15, 5 of 5 files at r16.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3563)*

**Pull request merged**
