### PR TITLE
workload: reuse small scratch []byte buffer in many workloads

### LINKED ISSUE #50495: workload: remove redundant allocation step when working with coldata.Bytes
As discussed in https://github.com/cockroachdb/cockroach/pull/50475#pullrequestreview-435147812, we use `bufalloc` in many places in `workload` package (namely in `FillBatch` method) which doesn't appear to be necessary anymore and using some temporary buffer should be sufficient because `coldata.Bytes.Set` performs a deep copy. We should update all workloads to remove the redundant copy on allocation.

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, in many workloads we have used `bufalloc.ByteAllocator` to
allocate fresh `[]byte` slices when populating initial data to be set in
`coldata.Bytes` vectors. I think originally it was necessary because the
first implementation of the vector used `[][]byte` under the hood, so we
could not reuse the same scratch space between different tuples - so we
were allocating a new space for each tuple. However, this is no longer
necessary since `Set` function performs a deep copy itself, so we can
now reuse the same scratch space.

Fixes: #50495.

Release justification: this probably can wait before 20.2 branch is cut.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Hm, I tried restoring tpcc fixture for 100 warehouses, and with this PR it got a little slower (before is like 1m 56s, and after is like 1m 59s), so I'm not sure whether it's worth pursuing this PR.

cc @asubiotto @jordanlewis

**Comment by yuzefovich** [comment]
@asubiotto @jordanlewis WDYT about this PR?

**Comment by asubiotto** [comment]
If we don't see an improvement, I think we should close this PR and the associated issue with a note that this was attempted.

**Comment by yuzefovich** [comment]
Sounds good to me.

**Pull request closed without merging**
