### PR TITLE
fetchpb: extract index fetch spec into a separate package

### PR DESCRIPTION
**Pull request by yuzefovich**
This will allow us to import the index fetch spec into `roachpb` which
is needed for the KV projection pushdown work.

This required changing the custom cast types used in the spec from type
aliases defined in `descpb` to one level lower ones from `catid`.

Epic: CRDB-14837

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I'm extremely supportive of this extraction. One note is that @Xiang-Gu has been contemplating just today pulling some proto enums out into an `enumpb` or `catenumpb` package that is very low dependency. That'd be a good place for this `IndexColumn_ASC`/`DESC` symbol.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the feedback! I extracted out `catenumpb` with a few things in #94160, and I think that commit is beneficial on its own, so we should merge it regardless of whether the index fetch spec will be used in the BatchRequest. I'll keep this PR about moving the index fetch spec. I'll try the spec cache idea before marking this as ready for review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94116#-:-NJvELu53dnC_AfdOX8H:b-vqzmym)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/catalog/fetchpb/index_fetch.proto` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94116#-NJrSHpLHMWQqrPvMrCL-r1-25:-NJvEkvN0W6MGxXfywhO:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d2d5f05b53ff3b33f05c1792500ea6ddff88490/pkg/sql/catalog/fetchpb/index_fetch.proto#L25)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Keep the cast type and drop it to `(gogoproto.casttype) = "[github.com/cockroachdb/cockroach/pkg/sql/sem/catid.ColumnID](http://github.com/cockroachdb/cockroach/pkg/sql/sem/catid.ColumnID)"`
</blockquote></details>

Good point, done.

**Review by ajwerner — APPROVED** [review]
nit: I think it'd be fine or even good to put this not under `sql/catalog`. At this point, it's feeling like the big thing this is doing is saying that rows and column encoding is a shared concept between sql and KV. Maybe put it near `rowenc`? I feel like with minimal effort we could make `keyside` and `valueside` not depend on `sql/catalog` and then pull them out of the sql tree altogether?

Anyways, this :lgtm: as a stand-alone PR. 

> Reviewed 4 of 119 files at r1, 8 of 103 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94116#-:-NKKz99G4bjUR52jpJEJ:b99guxr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava and @rharding6373)

**Comment by yuzefovich** [comment]
Your reasoning sounds good to me, so I left a TODO with that spirit (since I want to not get distracted for now) and will merge as is.

TFTR!

bors r+

**Pull request merged**
