### PR TITLE
sql: consistent aggregated timestamp when flushing sql stats

### PR DESCRIPTION
**Pull request by Azhng**
Previously, when SQL Stats are flushed to system table, the
aggregatedTs column for SQL Stats is calculated for each stats
entry individually. This means that if a flush starts near
the end of each hour, it is possible that different stats
rows will be assigned two different aggregated timestamp.
Currently, flusher flushes statement statistics first, and only
when statement statistics are flushed, transaction statistics
will be flushed into system table. This means that it is likely
the transaction statistics will get assigned a different
aggregatedTs than the statement statistics.
Consequentially, when the frontend fetches SQL Stats through
the CombinedStmtStats handler, the frontend default performs
range scan at 1 hour interval. This triggers a range scan
on the system table for that 1 hour range. This causes the
statement statisitcs that got assigned a different aggregatedTs
to be omitted from the result.

This commit changed the flusher to only compute aggregatedTs once
before the flush actually happen, and assign that aggregatedTs
too *all* stmt/txn stats rows. Statements executed in the same
aggregation interval can be looked up by the corresponding
statement fingerprint ID stored in transaction stats metadata.

Follow up to #71596

Release note: None

### CODE REVIEW

**Review by lindseyjin — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71731)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @lindseyjin)

___
*[pkg/sql/sqlstats/persistedsqlstats/testdata/consistent_flush_timestamp, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71731#-MmTZ3A50qoHYOqrM1M5:-MmTZ3A50qoHYOqrM1M6:bdpib82) ([raw file](https://github.com/cockroachdb/cockroach/blob/f96d3a322b84728149ba67fbce91cf60891b288f/pkg/sql/sqlstats/persistedsqlstats/testdata/consistent_flush_timestamp#L1)):*
> ```
> exec-sql
> ```

Out of curiosity, is this file being used in your above test cases? How does that work? 
Just wondering since I don't see the file name being mentioned anywhere.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71731)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @lindseyjin)

___
*[pkg/sql/sqlstats/persistedsqlstats/datadriven_test.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71731#-MmT_vINCFqglH6SFFqJ:-MmT_vINCFqglH6SFFqK:bgbiwsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f96d3a322b84728149ba67fbce91cf60891b288f/pkg/sql/sqlstats/persistedsqlstats/datadriven_test.go#L66)):*
> ```Go
> //                               (db, implicitTxn, fingerprint) will be sampled
> //                               next time it is being executed.
> func TestSQLStatsDataDriven(t *testing.T) {
> ```

@lindseyjin  this is the test function that executes the datadriven tests. This function would walk through the `testdata/*` directory and it also implements the directive used in the datadriven tests.

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71731)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @lindseyjin)

___
*[pkg/sql/sqlstats/persistedsqlstats/datadriven_test.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71731#-MmT_vINCFqglH6SFFqJ:-MmTaWU09Lv0sQvp-sdL:b-esjoo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f96d3a322b84728149ba67fbce91cf60891b288f/pkg/sql/sqlstats/persistedsqlstats/datadriven_test.go#L66)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

@lindseyjin  this is the test function that executes the datadriven tests. This function would walk through the `testdata/*` directory and it also implements the directive used in the datadriven tests. 
</blockquote></details>

Ohh I see. Thanks!

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71731#-:-Mms7AZ35ar6gLj2z8D6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Pull request merged**
