### PR TITLE
server: sanitize the behavior of runtime stats sampling / dumps for secondary tenants

### LINKED ISSUE #84589: server: extract the call to `startSampleEnvironment()` from StartTenant/StartServer [CRDB-14537 followup]
The function `startSampleEnvironment()` starts the logic that collects goroutine dumps / heap profiles etc.

This logic is process-wide and thus not specific to just 1 tenant.

Currently the call is made from inside `startTenantInternal()` (because the code in `cli/mt_start_sql.go` doesn't have another way to call it). This is illogical.

We need to remove it from there when running multiple tenants in-memory.

Epic: CRDB-14537

Jira issue: CRDB-17752

### PR DESCRIPTION
**Pull request by knz**
Fixes #84589.
Epic: CRDB-14537

See the individual commits for details.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
Overall the code looks reasonable. 

A test here could be hard to make non-flaky, but if we did want to try one, I think the most interesting one to me would be ensuring that we can see the relevant runtime stats from inside the tenant.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

There's already a test in `tenant_vars_test.go` that exercises the runtime stats on the tenant. If that test can be amended to use an in-process tenant, it should cover it.

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96168#-:-NN2KezO2EZA9tyc2VjN:b-fpnld6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
> If that test can be amended to use an in-process tenant, it should cover it.

Great idea. Done.

**Comment by knz** [comment]
bors r=stevendanna,dhartunian

**Pull request merged**
