### PR TITLE
sql: introduce RIGHT SEMI and RIGHT ANTI joins

### LINKED ISSUE #54707: sql: add support for RIGHT SEMI and RIGHT ANTI joins
Here is what we have now:
- rowexec: when executing left semi/anti, we will dynamically decide which side we’re building the hash table from. This decision is done at the runtime based on the number of rows from each side. Note that we try to buffer the rows from both sides hoping one of them is small, but once we buffer up more than 4MB from both sides, we fallback to building the hash table on the right input.
- colexec: we always hash the right side, regardless of the cardinalities.

What we’re missing:
- rowexec: not much, but the code can be simplified a bit if we always hash the right side.
- colexec: we might inefficiently hash the bigger side when the optimizer knows that left side is smaller - because we have the right size as fixed hashing side.

What introduction of RIGHT semi/anti will give us
- both rowexec and colexec will have the built-in assumption of hashing the right side.
- the optimizer will be the one to commute the inputs based on cardinality estimates.
- it now becomes possible to express to colexec 'hey, I need a semi/anti join, but hash the "left" side' (“left” here is on quotes coming from original “A left semi B” - this would be converted to “B right semi A”, and we want A’s rows to be output).

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: introduce RIGHT SEMI and RIGHT ANTI joins**

This commit introduces right semi and right anti joins which will give
an ability to the optimizer to control on which relation we're building
the hash table (in case of the hash join). This will allow us to bake in
the assumption that we're building the hash table on the right side into
the row-execution (we already have this assumption in the vectorized
hash join).

Additionally, this commit adds several assertions to different types of
joiners about which join types they support as well as fixes the
`joinerBase` code to handle the join types that emit only columns from
one side (previously, it just happened to work because the left side
columns were always in the output).

Release note: None

**rowexec: move hash joiner unit tests**

This commit renames "joinerTestCase" to "hashJoinerTestCase" since those
tests are only used by the hash joiner and moves the corresponding code
to hashjoiner_test.go. I believe that originally the intention was to
generalize them to use in several joiners types, but that intention was
never implemented, and since we're moving towards deprecating these
processors, I don't think it ever will.

Release note: None

**rowexec: support right semi and right anti hash joins**

This commit adds support for right semi and right anti hash joins which
turned out to be pretty easy to do. This paves the way for refactoring
the hash joiner code to hard-code that we're always storing the right
side.

Addresses: #54707.

Release note: None

**rowexec: clean up the hash joiner**

This commit cleans up the hash joiner by baking in the assumption that
we're always building the hash table on the right side. The assumption
allows us to remove the buffering logic (which attempted to find
a shorter relation, until a certain threshold), and we will now rely on
the optimizer to request an appropriate join type with the right
relation having smaller cardinality.

Release note: None

**colexec: support right semi and right anti in merge joiner**

This commit adds the support for right semi and right anti merge joins.
This turned out to be relatively easy when following the examples of
left semi and left anti (with the new right cases being simpler because
of not having to worry about set-operation joins which are intertwined
with left semi and left anti joins). The testing is done by "mirroring"
existing test cases for left semi and left anti joins.

Addresses: #54707.

Release note: None

**colexec: support right semi and right anti in the hash joiner**

The support of right semi and right anti in the hash joiner required
extending the idea of tracking whether build rows matched which was
already being done in case of full/right outer joins. Notable difference
is that right semi/anti joins don't emit any output during the probing
phase, so the "collection" simply tracks the matched rows whereas the
output is fully emitted in `hjEmittingRight` phase of the algorithm.
Note that because the external hash joiner falls back to the disk-backed
merge joiner in some cases it is important to point out that the
vectorized merge joiner already supports all join types.

Addresses: #54707.

Release note: None

**rowexec: support right semi and right anti in the merge joiner**

The support of right semi and right anti merge joiner is added via
tracking which rows have been matched on the right side. In case of
right semi we remember that the right row is matched, emit it, and then
make sure to ignore it (to not emit for the second time). In case of
right anti, all unmatched right rows will be emitted (similar to
right/full outer joins). This support was mostly added in order to test
the correctness of the vectorized merge joiner (I don't expect the
optimizer to ever plan right semi/anti merge joins).

Addresses: #54707.

Release note: None

**opt: plan right semi and right anti hash joins**

This commit utilizes the recently added right semi and right anti joins
in the optimizer. Internally, those join types are represented as the
same opt operator with the only changes being switching two input
relations if the left has smaller cardinality when execbuilding the hash
join (with the same change to the costing).

Fixes: #54707.

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
Heh, I need to switch teams if I ever want a spot in the top contributors by LoC list.

**Comment by yuzefovich** [comment]
@irfansharif take a look at this one #50636 :) But also you're welcome to contribute to the vectorized engine - we have very limited support of window functions for example :D

**Comment by yuzefovich** [comment]
I think it is RFAL. This PR adds the full support of right semi/anti joins in the execution, but those join types are not yet planned by the optimizer.

**Comment by yuzefovich** [comment]
@RaduBerinde please take a look at the last commit. (Note that it appears that at the moment github is having some issues, so I might need to force-push later.)

**Review by RaduBerinde — COMMENTED** [review]
Sorry for the delay! Opt changes LGTM. I looked over the rest of the PR and it looks good to me (I did not follow in detail the vectorized execution changes).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-:-MI62iuv73VXqrNBLJpd:b-5cefgc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/catalog/descpb/join_type.proto, line 83 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MJYMsns4BOF5Sjrzofk:-MJYMsns4BOF5Sjrzofl:b-sacmfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5258dc7358ca880957f0f03a4ee360613d164270/pkg/sql/catalog/descpb/join_type.proto#L83)):*
> ```protobuf
>   RIGHT_SEMI = 8;
> 
>   // A right anti join is an "inverted" semi join: it returns the rows from the
> ```

[nit] commuted instead of inverted (an inverted semi join sounds like an anti join to me)
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 430 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MJYNZXj965xpGTpDd7f:-MJYNZXj965xpGTpDd7g:bm6b9vv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5258dc7358ca880957f0f03a4ee360613d164270/pkg/sql/execinfrapb/processors_sql.proto#L430)):*
> ```protobuf
> // - for RIGHT_SEMI, RIGHT_ANTI - the right input columns.
> //
> // Note that, regardless of the join type, an optional on_expr can refer to
> ```

[nit] ON expression instead of `on_expr` (since that doesn't map to the Go name). Same below.

**Review by yuzefovich — COMMENTED** [review]
Thanks for taking a look!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-:-MJYbU17Cqrt1oQ9FGQj:bubxju8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/catalog/descpb/join_type.proto, line 83 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MJYMsns4BOF5Sjrzofk:-MJYaaao-XPDir9RVp1V:bcgdhls) ([raw file](https://github.com/cockroachdb/cockroach/blob/5258dc7358ca880957f0f03a4ee360613d164270/pkg/sql/catalog/descpb/join_type.proto#L83)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] commuted instead of inverted (an inverted semi join sounds like an anti join to me)
</blockquote></details>

Note that it actually is about an anti join (I copy-pasted what we had about left semi/anti and adjusted).

I've updated the comments to be a bit more specific.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54808)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/catalog/descpb/join_type.proto, line 83 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MJYMsns4BOF5Sjrzofk:-MJYgiQF8wxe_58o7KQb:b3p7ao3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5258dc7358ca880957f0f03a4ee360613d164270/pkg/sql/catalog/descpb/join_type.proto#L83)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Note that it actually is about an anti join (I copy-pasted what we had about left semi/anti and adjusted).

I've updated the comments to be a bit more specific.
</blockquote></details>

Ah, sorry, I misread. LGTM.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54808)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/opt/exec/explain/emit.go, line 315 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MJYkzwiCZ63n9_b2CdL:-MJYkzwiCZ63n9_b2CdM:b-xhpqpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/280520b5a48eec919ec5b7fb1b67bd44d80f994b/pkg/sql/opt/exec/explain/emit.go#L315)):*
> ```Go
> 		typ = "full outer"
> 	case descpb.LeftSemiJoin:
> 		typ = "semi"
> ```

Radu, I decided to not change the labels for left semi/anti, what do you think about it?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54808)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/opt/exec/explain/emit.go, line 315 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MJYkzwiCZ63n9_b2CdL:-MJYtvtW5KmGHGanRZ7B:b-hfghm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/280520b5a48eec919ec5b7fb1b67bd44d80f994b/pkg/sql/opt/exec/explain/emit.go#L315)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Radu, I decided to not change the labels for left semi/anti, what do you think about it?
</blockquote></details>

Sounds good

**Comment by yuzefovich** [comment]
@asubiotto friendly ping

**Review by asubiotto — APPROVED** [review]
:lgtm: once it's rebased

> Reviewed 2 of 9 files at r1, 26 of 26 files at r5, 8 of 27 files at r15, 56 of 56 files at r23, 4 of 4 files at r24, 3 of 3 files at r25, 12 of 12 files at r26, 21 of 21 files at r27, 9 of 9 files at r28, 4 of 4 files at r29, 6 of 6 files at r30.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-:-MLSksF72-0CHOUDY9H7:b-cwppq1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/utils_test.go, line 1468 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MLSjyoS7psOA61eUgPB:-MLSjyoS7psOA61eUgPC:b-qi5rs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a2d45bbc18d0a739b276718e7925956f8a82ca/pkg/sql/colexec/utils_test.go#L1468)):*
> ```Go
> }
> 
> // mirror attempts to create a "mirror" test case of tc and returns nil if it
> ```

nit: might be nice to explain this a bit further (i.e. that mirroring is like swapping).
___
*[pkg/sql/rowexec/hashjoiner.go, line 69 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MLSig0tBh_y1eJGPS_Q:-MLSig0tBh_y1eJGPS_R:b5d6ebu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c69610f4588fc93379b1c9598c3a703d7b1d753/pkg/sql/rowexec/hashjoiner.go#L69)):*
> ```Go
> 	disableTempStorage bool
> 	hashTable          rowcontainer.HashRowContainer
> 	hashTableEmpty     bool
> ```

Instead of a boolean, could this be a `HashRowContainer` method? Seems nicer to me.
___
*[pkg/sql/rowexec/hashjoiner.go, line 84 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MLSicjr7JoBXs-bSZYt:-MLSicjr7JoBXs-bSZYu:b-811j88) ([raw file](https://github.com/cockroachdb/cockroach/blob/a79b267469fa1d8dd9f8e0bd8184ab2f883da765/pkg/sql/rowexec/hashjoiner.go#L84)):*
> ```Go
> 	// TODO(yuzefovich): remove buffering stage from the hash joiner and always
> 	// build from the right stream.
> 	initialBufferSize int64
> ```

Great to see this go :clap: 
___
*[pkg/sql/rowexec/hashjoiner.go, line 115 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MLSilH668DhLaHGXDJn:-MLSilH668DhLaHGXDJo:b-pmx0fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c69610f4588fc93379b1c9598c3a703d7b1d753/pkg/sql/rowexec/hashjoiner.go#L115)):*
> ```Go
> 		rightSource:        rightSource,
> 		nullEquality:       spec.Type.IsSetOpJoin(),
> 		disableTempStorage: disableTempStorage,
> ```

We should probably remove the cluster setting to disable temp storage for this and other things (in another PR).
___
*[pkg/sql/rowexec/mergejoiner_test.go, line 694 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MLSkcch79SjuAsVfhDe:-MLSkcch79SjuAsVfhDf:b-ne4pc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fd4e5c1a29607ed55bcb96e0fcb063046ebfffb/pkg/sql/rowexec/mergejoiner_test.go#L694)):*
> ```Go
> 			// join type accordingly.
> 			mirroringCase := c
> 			mirroringCase.spec.Type, mirroringCase.spec.OnExpr = mirrorJoinTypeAndOnExpr(c.spec.Type, c.spec.OnExpr)
> ```

Can you reuse what you wrote for colexec here or extract it into a method like you did there?

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-:-MLU2y9ID-c-wIrTjwLp:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/rowexec/hashjoiner.go, line 69 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MLSig0tBh_y1eJGPS_Q:-MLTPKa1COx6gdeGnxpU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c69610f4588fc93379b1c9598c3a703d7b1d753/pkg/sql/rowexec/hashjoiner.go#L69)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Instead of a boolean, could this be a `HashRowContainer` method? Seems nicer to me.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/hashjoiner.go, line 115 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MLSilH668DhLaHGXDJn:-MLTS9L85m9pbektSNp4:b-s316sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c69610f4588fc93379b1c9598c3a703d7b1d753/pkg/sql/rowexec/hashjoiner.go#L115)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We should probably remove the cluster setting to disable temp storage for this and other things (in another PR).
</blockquote></details>

Actually the cluster setting has already been removed, and I kept the disabling knob for tests, but now with the removal of initial buffering phases the disabling seems no longer necessary. Removed.
___
*[pkg/sql/rowexec/mergejoiner_test.go, line 694 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/54808#-MLSkcch79SjuAsVfhDe:-MLTSejTDB3reNk6hn_J:b-gqvyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fd4e5c1a29607ed55bcb96e0fcb063046ebfffb/pkg/sql/rowexec/mergejoiner_test.go#L694)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can you reuse what you wrote for colexec here or extract it into a method like you did there?
</blockquote></details>

It's not that easy - the test cases in the rowexec are different structs for hash and merge joins and in the colexec they are yet another struct (shared between hash and merge joins though). If we wanted to reuse the whole mirroring logic, we probably would need to extract a base join test case struct from both packages which will require updating hundreds of the unit tests. I think it's not worth the effort since we're unlikely to add more unit tests in the rowexec, and some code duplication seems ok to me in this case.

**Pull request merged**
