### PR TITLE
coldata: batch-allocate columns of the same type

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit improves `NewMemBatchWithCapacity` method to batch-allocate underlying storage for columns of the same type. If we see multiple vectors use the same canonical type, we can allocate a huge backing slice that is divided between columns. Similar idea is applied to how we allocate nulls. This can noticeably reduce the number (but not the size) of allocations.

Kudos to Marcus for the idea.

Macro-benchmark:
```
name                                           old time/op    new time/op    delta
ScanWideTable/Cockroach-24                       7.56ms ± 1%    7.52ms ± 1%   -0.49%  (p=0.035 n=10+10)
ScanWideTable/SharedProcessTenantCockroach-24    7.64ms ± 1%    7.56ms ± 1%   -1.06%  (p=0.000 n=10+10)
ScanWideTable/MultinodeCockroach-24              8.13ms ± 1%    8.04ms ± 1%   -1.15%  (p=0.002 n=10+10)

name                                           old alloc/op   new alloc/op   delta
ScanWideTable/Cockroach-24                       3.04MB ± 0%    3.04MB ± 0%   +0.08%  (p=0.000 n=10+9)
ScanWideTable/SharedProcessTenantCockroach-24    3.05MB ± 0%    3.05MB ± 0%   +0.11%  (p=0.000 n=10+10)
ScanWideTable/MultinodeCockroach-24              3.32MB ± 0%    3.33MB ± 1%     ~     (p=0.481 n=10+10)

name                                           old allocs/op  new allocs/op  delta
ScanWideTable/Cockroach-24                        1.17k ± 0%     0.77k ± 0%  -33.83%  (p=0.000 n=10+10)
ScanWideTable/SharedProcessTenantCockroach-24     1.22k ± 1%     0.82k ± 1%  -32.57%  (p=0.000 n=10+10)
ScanWideTable/MultinodeCockroach-24               2.97k ± 1%     2.43k ± 1%  -18.15%  (p=0.000 n=9+9)
```
Micro-benchmark:
```
NewMemBatchWithCapacity/oneInt/len=1-24           204ns ± 6%     215ns ± 7%   +5.60%  (p=0.005 n=10+10)
NewMemBatchWithCapacity/threeInts/len=1-24        409ns ± 3%     422ns ± 6%     ~     (p=0.082 n=9+10)
NewMemBatchWithCapacity/allOnce/len=1-24         1.39µs ± 8%    1.33µs ±11%     ~     (p=0.072 n=10+10)
NewMemBatchWithCapacity/allThrice/len=1-24       3.96µs ± 9%    4.43µs ± 7%  +11.79%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/oneInt/len=32-24          300ns ±10%     365ns ±10%  +21.58%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/threeInts/len=32-24       596ns ±10%     665ns ± 9%  +11.65%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allOnce/len=32-24        2.91µs ± 6%    2.59µs ±11%  -11.01%  (p=0.000 n=8+10)
NewMemBatchWithCapacity/allThrice/len=32-24      7.98µs ±13%    7.99µs ±23%     ~     (p=0.796 n=10+10)
NewMemBatchWithCapacity/oneInt/len=1024-24       3.28µs ±16%    4.12µs ±27%  +25.60%  (p=0.001 n=10+10)
NewMemBatchWithCapacity/threeInts/len=1024-24    7.39µs ±11%    5.98µs ±24%  -19.07%  (p=0.002 n=10+10)
NewMemBatchWithCapacity/allOnce/len=1024-24      36.9µs ± 9%    31.2µs ±13%  -15.39%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allThrice/len=1024-24    91.6µs ±19%    87.6µs ±23%     ~     (p=0.631 n=10+10)

name                                           old alloc/op   new alloc/op   delta
NewMemBatchWithCapacity/oneInt/len=1-24            208B ± 0%      208B ± 0%     ~     (all equal)
NewMemBatchWithCapacity/threeInts/len=1-24         448B ± 0%      480B ± 0%   +7.14%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allOnce/len=1-24         2.28kB ± 0%    2.27kB ± 0%   -0.35%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allThrice/len=1-24       6.71kB ± 0%    6.68kB ± 0%   -0.48%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/oneInt/len=32-24           700B ± 0%      700B ± 0%     ~     (all equal)
NewMemBatchWithCapacity/threeInts/len=32-24      1.43kB ± 0%    1.48kB ± 0%   +3.64%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allOnce/len=32-24        8.48kB ± 0%    8.48kB ± 0%   +0.05%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allThrice/len=32-24      24.8kB ± 0%    24.8kB ± 0%   -0.08%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/oneInt/len=1024-24       16.7kB ± 0%    16.7kB ± 0%     ~     (all equal)
NewMemBatchWithCapacity/threeInts/len=1024-24    33.5kB ± 0%    33.6kB ± 0%   +0.14%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allOnce/len=1024-24       204kB ± 0%     204kB ± 0%     ~     (all equal)
NewMemBatchWithCapacity/allThrice/len=1024-24     595kB ± 0%     581kB ± 0%   -2.29%  (p=0.000 n=10+10)

name                                           old allocs/op  new allocs/op  delta
NewMemBatchWithCapacity/oneInt/len=1-24            7.00 ± 0%      7.00 ± 0%     ~     (all equal)
NewMemBatchWithCapacity/threeInts/len=1-24         13.0 ± 0%      10.0 ± 0%  -23.08%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allOnce/len=1-24           37.0 ± 0%      27.0 ± 0%  -27.03%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allThrice/len=1-24          103 ± 0%        44 ± 0%  -57.28%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/oneInt/len=32-24           7.00 ± 0%      7.00 ± 0%     ~     (all equal)
NewMemBatchWithCapacity/threeInts/len=32-24        13.0 ± 0%      10.0 ± 0%  -23.08%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allOnce/len=32-24          37.0 ± 0%      27.0 ± 0%  -27.03%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allThrice/len=32-24         103 ± 0%        44 ± 0%  -57.28%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/oneInt/len=1024-24         7.00 ± 0%      7.00 ± 0%     ~     (all equal)
NewMemBatchWithCapacity/threeInts/len=1024-24      13.0 ± 0%      10.0 ± 0%  -23.08%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allOnce/len=1024-24        37.0 ± 0%      27.0 ± 0%  -27.03%  (p=0.000 n=10+10)
NewMemBatchWithCapacity/allThrice/len=1024-24       103 ± 0%        44 ± 0%  -57.28%  (p=0.000 n=10+10)
```
Note that there is some slowdown when allocating columns of small capacity, but the absolute speed is still pretty high. My hypothesis is that reduced number of objects would reduce impact of GC which should counteract this slowdown, making this change neutral or beneficial overall (depending on the type schema and column capacity).

Informs: #117546.
Epic: CRDB-35243

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
I think it might be worth batching allocations in a few more places, but this :lgtm: if you just want to leave that as a TODO (or explain why it's a bad idea :)).

> Reviewed 2 of 2 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121315#-:-NuSnGEs95ZmpXFyZVFZ:b8pfy90)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/col/coldata/bytes.go` line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121315#-NuSiEiR2tF1ehYZEdkO:-NuSiEiR2tF1ehYZEdkP:b-svqq2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/620f6f07e49174c872e1db5b50b5cea273f9e3fa/pkg/col/coldata/bytes.go#L180)):*
> ```Go
> //gcassert:inline
> func newBytes(elements []element) *Bytes {
> 	return &Bytes{elements: elements}
> ```

Would it be helpful to amortize the `Bytes` struct allocations as well? I might be mis-remembering, but I think many of the allocations in the profiles that motivate this change were due to this struct. (Maybe same for any other wrapping structs)
___
*[`pkg/col/coldataext/extended_column_factory.go` line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121315#-NuSkAbN8NqT9vI_wfMG:-NuSkAbN8NqT9vI_wfMH:buvuv1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/620f6f07e49174c872e1db5b50b5cea273f9e3fa/pkg/col/coldataext/extended_column_factory.go#L58)):*
> ```Go
> 		// try to batch-allocate columns for different types. For now, we just
> 		// don't use this ability.
> 		colexecerror.InternalError(errors.AssertionFailedf("batch-allocation of datum vectors is unsupported"))
> ```

Why can't we do slices of `[]tree.Datum`?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the suggestions! The numbers are improved a bit further.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121315#-:-NuVhTw80BbzLyCSwuLN:btsow5l)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/col/coldataext/extended_column_factory.go` line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121315#-NuSkAbN8NqT9vI_wfMG:-NuVh8aM0LuCPvBA58c3:bktssvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/620f6f07e49174c872e1db5b50b5cea273f9e3fa/pkg/col/coldataext/extended_column_factory.go#L58)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Why can't we do slices of `[]tree.Datum`?
</blockquote></details>

We can - I was just being somewhat lazy. Datum-backed vectors need special handling to set the actual type (i.e. we can have `types.TSVector, types.TSQuery, etc` batch-allocated together, but then we need to update each vector with its type. Done.
___
*[`pkg/col/coldata/bytes.go` line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121315#-NuSiEiR2tF1ehYZEdkO:-NuV_qde6054vX7FLRiE:b74w1ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/620f6f07e49174c872e1db5b50b5cea273f9e3fa/pkg/col/coldata/bytes.go#L180)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Would it be helpful to amortize the `Bytes` struct allocations as well? I might be mis-remembering, but I think many of the allocations in the profiles that motivate this change were due to this struct. (Maybe same for any other wrapping structs)
</blockquote></details>

Very good point, done.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice!

> Reviewed 8 of 8 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121315#-:-NuVo9Vk3_lra9jDf2ob:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
