### PR TITLE
grpcutil: respect verbose logging

### PR DESCRIPTION
**Pull request by tbg**
During a recent debugging session on v20.1, we had no way to get verbose
gRPC logging without a custom build.

Upon revisiting this code on `master`, I was pleasantly surprised that
it had already been improved significantly. Still, there were some
improvements I made:

- rename file to `grpc_log.go` so that we can `--vmodule=grpc_log=3`
  which is less confusing than the previously required
  `--vmodule=log=3`.
- rename `logger` to `grpcLogger` and use that as the receiver name as
  well.
- `SetSeverity` was renamed to `LowerSeverity` and respects the
  `GRPC_GO_LOG_{SEVERITY,VERBOSITY}_LEVEL` variables. For example, a
  call `LowerSeverity(log.SEVERITY_Warning)` with the env var
  `GRPC_GO_LOG_SEVERITY_LEVEL=info` would keep the level at INFO,
  where it was previously (due to init-time reading of the env var).
- when any verbosity is active, don't supress certain warnings we
  consider spammy.
- similarly, when any verbosity is active, log at all severities.
  We do this because our only runtime knob is the verbosity; we don't
  have a facility to change the severity separately.
- `(*grpcLogger).V() takes into account the
  `GRPC_GO_LOG_VERBOSITY_LEVEL`; if that is more permissive, it
  overrides our loggers response to `V()`.
- Refactored code a little bit for easier testing and added some
  tests.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: I think, though it was a little hard to line up each of the changes in the second commit with the commit message due to the file rename. Unfortunately, it looks like too much changed for git to consider the movement a rename.

> Reviewed 2 of 2 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56857#-:-MMTYnF36A3M_qYypAuy:b2l3itw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by tbg** [comment]
TFTR! Apologies about the messy history, I could've easily split these out but did not.

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Comment by tbg** [comment]
Fixed the remaining lint failure too

bors single on
bors r=nvanbenschoten

**Pull request merged**
