### PR TITLE
GLOCKFILE: update dependencies

### PR DESCRIPTION
**Pull request by tamird**
See individual commits.

Note that the update to `golint` has given it opinions regarding the position of "context" arguments; this change brings us in line with those opinions.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10031)

### CODE REVIEW

**Comment by dt** [comment]
Unless there's something important upstream we need to pick up, I'd rather land #9900 since it's green and has a few LGTMs rather than rebase it again over a dep change.

**Comment by tamird** [comment]
The rebase seems trivial, so I'm not sure how much weight I'm going to give that particular argument.

**Comment by tschottdorf** [comment]
:lgtm: (with  zero weight on which change should go in first), though I didn't review the monster diff at the end thoroughly (if there's anything else in there other than moving `ctx` first, please point it out).

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 41 of 41 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[build/style_test.go, line 563 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ02Qkc_tU_OVTqYRc:-KUJ02Qkc_tU_OVTqYRd:bb76mu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0d7320248281502f83417f96854979c11732f6/build/style_test.go#L563)):*
> ```Go
> 			stream.Sort(),
> 			stream.Uniq(),
> 			stream.GrepNot(`cockroach/pkg/cmd/`),
> ```

Why?

---

*[pkg/cmd/glock-diff-parser/main.go, line 1 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ-m4AiDf9w4j3ujj2:-KUJ-m4AiDf9w4j3ujj3:bb6ht2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0d7320248281502f83417f96854979c11732f6/pkg/cmd/glock-diff-parser/main.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

2016

---

*[pkg/cmd/glock-diff-parser/main.go, line 27 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ-sCk6Si8k_uWp3iJ:-KUJ-sCk6Si8k_uWp3iK:bv5qr3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0d7320248281502f83417f96854979c11732f6/pkg/cmd/glock-diff-parser/main.go#L27)):*
> ```Go
> )
> 
> func main() {
> ```

Document it in this file.

---

*[pkg/storage/store_test.go, line 718 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ0mbOUG4So0Z0Gn5N:-KUJ0mbOUG4So0Z0Gn5O:b-gko5wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab8922c623471c69f317d6a245f828374516b8e/pkg/storage/store_test.go#L718)):*
> ```Go
> 
> 	// Try a successful get request.
> 	if _, pErr := client.SendWrapped(context.Background(), store.testSender(), &gArgs); pErr != nil {
> ```

Aren't we doing `.TODO()` in tests? Wasn't going to comment on the existing ones, but these are "new".

---

*[pkg/util/tracing/tracer.go, line 221 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ-Yf_JHAErUedNC30:-KUJ-Yf_JHAErUedNC31:bgcf8c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a8540c8aa3be70fdb904487be7e6752e40f48b/pkg/util/tracing/tracer.go#L221)):*
> ```Go
> 			AccessToken:    lightstepToken,
> 			MaxLogsPerSpan: maxLogsPerSpan,
> 			UseGRPC:        true,
> ```

Doesn't this fix some issue (data races b/c of Thrift)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-:-KUJ0tvBGsDv_SRE6s1V:b1m2ea9)*

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[build/style_test.go, line 563 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ02Qkc_tU_OVTqYRc:-KUJ2IxvMJIwcX4kL4eD:bol9rme) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0d7320248281502f83417f96854979c11732f6/build/style_test.go#L563)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Why?
</details>
Because I wanted to use `log.Fatal` in the new command and then decided that commands generally should do whatever they want.

---

*[pkg/cmd/glock-diff-parser/main.go, line 1 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ-m4AiDf9w4j3ujj2:-KUJ30iA_tZef5F5ryV6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0d7320248281502f83417f96854979c11732f6/pkg/cmd/glock-diff-parser/main.go#L1)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> 2016
</details>
Done.

---

*[pkg/cmd/glock-diff-parser/main.go, line 27 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ-sCk6Si8k_uWp3iJ:-KUJ31-7VYb2wVSIThGs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0d7320248281502f83417f96854979c11732f6/pkg/cmd/glock-diff-parser/main.go#L27)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Document it in this file.
</details>
Done.

---

*[pkg/storage/store_test.go, line 718 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ0mbOUG4So0Z0Gn5N:-KUJ2UukuYR4bVQioDh0:b911n6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab8922c623471c69f317d6a245f828374516b8e/pkg/storage/store_test.go#L718)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Aren't we doing `.TODO()` in tests? Wasn't going to comment on the existing ones, but these are "new".
</details>
I'll wait for @raduberinde to weigh in. ISTM that it doesn't matter since it's trivial to boil the ocean either way.

---

*[pkg/util/tracing/tracer.go, line 221 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ-Yf_JHAErUedNC30:-KUJ2bqOuVHWv4oOTiyq:b-bk9sxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a8540c8aa3be70fdb904487be7e6752e40f48b/pkg/util/tracing/tracer.go#L221)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Doesn't this fix some issue (data races b/c of Thrift)?
</details>
Beats me? Would be great if you could find it so I could point to it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r7, 2 of 3 files at r9, 41 of 41 files at r10.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[build/style_test.go, line 563 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ02Qkc_tU_OVTqYRc:-KUJ7pXOs-LmcPlaKPM3:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0d7320248281502f83417f96854979c11732f6/build/style_test.go#L563)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Because I wanted to use `log.Fatal` in the new command and then decided that commands generally should do whatever they want.
</details>
Ack.

---

*[pkg/cmd/glock-diff-parser/main.go, line 15 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ801L5-qja6kcSmhp:-KUJ801MxaK3LI4hDy62:b-mpnlfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ff421ce744be8d6ecedda6830fc39f178a2d58/pkg/cmd/glock-diff-parser/main.go#L15)):*
> ```Go
> // permissions and limitations under the License.
> 
> // This utility is useful when auditing dependency updates. Sample invocation:
> ```

Still, what does it do? Maybe just give example output (before `xargs`).

---

*[pkg/storage/store_test.go, line 718 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ0mbOUG4So0Z0Gn5N:-KUJ87s9JHmmDjB8bmuB:b-ruw5o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab8922c623471c69f317d6a245f828374516b8e/pkg/storage/store_test.go#L718)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'll wait for @raduberinde to weigh in. ISTM that it doesn't matter since it's trivial to boil the ocean either way.
</details>
Yeah, no need to block this on that question.

---

*[pkg/util/tracing/tracer.go, line 221 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ-Yf_JHAErUedNC30:-KUJ8Aj6IztrsW9KDRwY:bwwbgfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a8540c8aa3be70fdb904487be7e6752e40f48b/pkg/util/tracing/tracer.go#L221)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Beats me? Would be great if you could find it so I could point to it here.
</details>
https://github.com/cockroachdb/cockroach/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20thrift

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031)*

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/util/tracing/tracer.go, line 221 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUIt0SSjK2xEyCEHNSi:-KUIt0SSjK2xEyCEHNSj:b-49lzma) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a8540c8aa3be70fdb904487be7e6752e40f48b/pkg/util/tracing/tracer.go#L221)):*
> ```Go
> 			AccessToken:    lightstepToken,
> 			MaxLogsPerSpan: maxLogsPerSpan,
> 			UseGRPC:        true,
> ```

Why is this not the default upstream? Is there any worry about stability?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-:-KUJZSZcWVjdrQjow5ql:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 2 of 46 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/cmd/glock-diff-parser/main.go, line 15 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ801L5-qja6kcSmhp:-KUJcMt0w6sXFgBWDL6k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5ff421ce744be8d6ecedda6830fc39f178a2d58/pkg/cmd/glock-diff-parser/main.go#L15)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Still, what does it do? Maybe just give example output (before `xargs`).
</details>
Done.

---

*[pkg/util/tracing/tracer.go, line 221 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ-Yf_JHAErUedNC30:-KUJbrdtnj9w_fGcIhr0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a8540c8aa3be70fdb904487be7e6752e40f48b/pkg/util/tracing/tracer.go#L221)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> https://github.com/cockroachdb/cockroach/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20thrift
</details>
Done.

---

*[pkg/util/tracing/tracer.go, line 221 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUIt0SSjK2xEyCEHNSi:-KUJcHozte9TnZe4-Eli:b-oqj6cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a8540c8aa3be70fdb904487be7e6752e40f48b/pkg/util/tracing/tracer.go#L221)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Why is this not the default upstream? Is there any worry about stability?
</details>
No idea, but we'll find out, I would imagine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 46 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/storage/store_test.go, line 718 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUJ0mbOUG4So0Z0Gn5N:-KUJcAFZUgmfd4RcfzRg:b-ti0q3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab8922c623471c69f317d6a245f828374516b8e/pkg/storage/store_test.go#L718)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Yeah, no need to block this on that question.
</details>
Yeah we're doing `TODO`s in tests for now (we're still flirting with the idea of having some infrastructure for test contexts, e.g. to capture entire tests in traces). Not terribly important though, if we ever do that we'll probably have to search for `Background`s anyway. Way easier to find than `nil` :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031)*

**Comment by tschottdorf** [comment]
Reviewed 44 of 44 files at r11, 1 of 1 files at r12, 2 of 3 files at r14, 41 of 41 files at r15.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/util/tracing/tracer.go, line 221 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-KUIt0SSjK2xEyCEHNSi:-KUKAreuYV7OwoCwV8PI:bm2y4l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a8540c8aa3be70fdb904487be7e6752e40f48b/pkg/util/tracing/tracer.go#L221)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> No idea, but we'll find out, I would imagine.
</details>
That's not terribly reassuring, but ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031)*

**Comment by dt** [comment]
:lgtm: I'm fine rebasing vendor PR

---

Review status: 2 of 46 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10031#-:-KUL1jJTV0HZq77zBd6A:b-41qorj)*

**Pull request merged**
