### PR TITLE
distsql: add stat collection to aggregators

### PR DESCRIPTION
**Pull request by asubiotto**
Addresses #25743 

Release note: None

screen shot 2018-06-12 at 12 58 40 pm

### CODE REVIEW

**Comment by jordanlewis** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/aggregator.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26645#-LEpHxIZ0lvmoq1Vbrol:-LEpHxIZ0lvmoq1Vbrom:bstsawo) ([raw file](https://github.com/cockroachdb/cockroach/blob/511d771ff36f8ace0c4add02230ce43e0d5a3b02/pkg/sql/distsqlrun/aggregator.go#L125)):*
> ```Go
> 	// shared flow monitor to separate memory allocations that the aggregator
> 	// makes from the rest of the flow.
> 	memMonitor *mon.BytesMonitor
> ```

It seems a shame to have to do this dance, considering we already have a BoundAccount available unconditionally. Maybe we should have BoundAccounts also track their max usage?

But in this case, it doesn't seem like we ever shrink our BoundAccount significantly. (the only time is in stringarena.UnsafeReset, but i'm not too sure how important that is) So can we just return the currently allocated bytes of the account instead of having to make a new monitor?

---

*[pkg/sql/distsqlrun/aggregator.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26645#-LEpKKbt-423hzGUDe7E:-LEpKKbt-423hzGUDe7F:brv8gox) ([raw file](https://github.com/cockroachdb/cockroach/blob/511d771ff36f8ace0c4add02230ce43e0d5a3b02/pkg/sql/distsqlrun/aggregator.go#L235)):*
> ```Go
> // StatsForQueryPlan implements the DistSQLSpanStats interface.
> func (as *AggregatorStats) StatsForQueryPlan() []string {
> 	return []string{
> ```

This looks pretty similar to the other StatsForQueryPlan implementation. Should we make a function that does this? Maybe InputStats should have a method that returns the first two.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26645)*

**Comment by asubiotto** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/aggregator.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26645#-LEpHxIZ0lvmoq1Vbrol:-LEzdSfUE4VCHc8M5KN0:b-nhh2ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/511d771ff36f8ace0c4add02230ce43e0d5a3b02/pkg/sql/distsqlrun/aggregator.go#L125)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It seems a shame to have to do this dance, considering we already have a BoundAccount available unconditionally. Maybe we should have BoundAccounts also track their max usage?

But in this case, it doesn't seem like we ever shrink our BoundAccount significantly. (the only time is in stringarena.UnsafeReset, but i'm not too sure how important that is) So can we just return the currently allocated bytes of the account instead of having to make a new monitor?
</blockquote></details>

As we discussed offline tracking that in a `BoundAccount` would mean that we would be incrementing a counter every time we would `Grow` it (while we do block allocations to amortize these at the memory monitor level). Additionally, users (although not in this case) usually have different accounts for different allocation patterns and you would want to report the aggregate usage anyway. What we would want to do is to create a memory monitor per processor anyway (it seems like a good idea to separate processor allocations from the general flow monitor), but I won't do that in this PR.

---

*[pkg/sql/distsqlrun/aggregator.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26645#-LEpKKbt-423hzGUDe7E:-LEzmbx1BIRDhsxplo0u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/511d771ff36f8ace0c4add02230ce43e0d5a3b02/pkg/sql/distsqlrun/aggregator.go#L235)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This looks pretty similar to the other StatsForQueryPlan implementation. Should we make a function that does this? Maybe InputStats should have a method that returns the first two.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26645)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r2, 5 of 5 files at r3.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26645#-:-LF3Nvs1ENx-aexwJ_mu:bnfp4nl)*

**Pull request merged**
