### PR TITLE
sql: Introduce VirtualSchema infrastructure

### PR DESCRIPTION
**Pull request by nvb**
Related to #7965.

This PR introduces the `VirtualSchema` infrastructure into the SQL layer. This new structure allows static virtual descriptors to be used for non-distributed read-only SQL relations, and provides a means to mock out the results of selecting from tables within these schemas.

This is the initial step towards supporting `information_schema` and `pg_catalog`.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8119)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: though someone else should give it a more thorough review. The approach matches what I was expecting. 

---

Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/data_source.go, line 205 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KNyPMBmVbUPkQO2fRDM:-KNyPMBmVbUPkQO2fRDN:1214366990) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/data_source.go#L205)):*
> ```Go
> 
> 		// Check for a virtual table.
> 		virtual, err := getVirtualTable(t)
> ```

If someone has created a database named `information_schema` prior to this change, they will no longer be able to access it. Probably acceptable, but we'll likely want to call this out in the release notes. Be sure to highlight it in the commit message if it isn't already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-:-KNyQ7AzBvSj8m3xkYMn:1743008439)*

**Comment by andreimatei** [comment]
LGTM

---

Review status: 0 of 18 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[sql/information_schema.go, line 54 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6RrvCb0wOr6ZpG9Jn:-KO6RrvD44PDowVNjAWG:-2091041595) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/information_schema.go#L54)):*
> ```Go
> );`,
> 	populate: func(p *planner, addRow func(...parser.Datum)) error {
> 		// TODO(nvanbenschoten) This isn't actually the correct implementation
> ```

instead, say that not all fields all filled in.
Also nit: ':' after TODO(nvanbenschoten)

---

*[sql/virtual_schema.go, line 98 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6Cqsv8BXQ6rnnIiWW:-KO6CqswbSArdA71aE2T:1031481215) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d963d87d465d4796592d65bd659821747131064/sql/virtual_schema.go#L98)):*
> ```Go
> // checkVirtualDatabaseDesc checks if the provided name matches a virtual database,
> // and if so, returns that database's descriptor.
> func checkVirtualDatabaseDesc(name string) *sqlbase.DatabaseDescriptor {
> ```

s/checkVirtualDBDesc/getVirtualDBDesc ?

---

*[sql/virtual_schema.go, line 103 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6D2UBE5BQShWrc_uS:-KO6D2UBE5BQShWrc_uT:962052096) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d963d87d465d4796592d65bd659821747131064/sql/virtual_schema.go#L103)):*
> ```Go
> 
> // isVirtualDatabase checks if the provided name corresponds to a virtual database.
> func isVirtualDatabase(name string) bool {
> ```

really necessary?

---

*[sql/virtual_schema.go, line 42 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6Tu1WViBvqBb4o6ZI:-KO6Tu1WViBvqBb4o6ZJ:1351722298) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L42)):*
> ```Go
> type virtualSchemaTable struct {
> 	schema   string
> 	populate func(p *planner, addRow func(...parser.Datum)) error
> ```

wasn't the previous definition nicer? And in fact can't we make it more specific - can't it return a... `ValuesNode`?

---

*[sql/virtual_schema.go, line 74 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6UTca5sF6mqL9JwOK:-KO6UTca5sF6mqL9JwOL:-1991500825) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L74)):*
> ```Go
> }
> 
> type virtualTableEntry struct {
> ```

do we really need struct separately from `virtualSchemaTable`?

---

*[sql/virtual_schema.go, line 79 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6NXy1Sv_F37S7NKLz:-KO6NXy1Sv_F37S7NKM-:-1177933017) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L79)):*
> ```Go
> }
> 
> func (e virtualTableEntry) getPlanNode(p *planner) (planNode, error) {
> ```

this method deserves a comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-:-KO6U_eoDptwtDsN1vt_:676834233)*

**Comment by nvanbenschoten** [comment]
Thanks for the reviews. I added in a final commit which has the real implementation for `information_schema.tables`. I figured this wouldn't be suitable for merging until that was added in.

---

Review status: 0 of 19 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/data_source.go, line 205 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KNyPMBmVbUPkQO2fRDM:-KO6iCyQsmV3qGSo_wJN:935736739) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/data_source.go#L205)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> If someone has created a database named `information_schema` prior to this change, they will no longer be able to access it. Probably acceptable, but we'll likely want to call this out in the release notes. Be sure to highlight it in the commit message if it isn't already.
</details>
Yes, that's a good point that I meant to highlight. My feeling was that anyone who previously had an `information_schema` database had created it to hack around our lack of support, and therefore it would be fine to "shadow" their previous database now that we are providing real support. Still, we should call this out in the release notes and I noted it in the first commit message.

---

*[sql/information_schema.go, line 54 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6RrvCb0wOr6ZpG9Jn:-KO6j2yBNI0IMlDsXd7E:522460571) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/information_schema.go#L54)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> instead, say that not all fields all filled in.
> Also nit: ':' after TODO(nvanbenschoten)
</details>
See final commit.

---

*[sql/virtual_schema.go, line 98 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6Cqsv8BXQ6rnnIiWW:-KO6kNPIFutoma2j2eo5:359437299) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d963d87d465d4796592d65bd659821747131064/sql/virtual_schema.go#L98)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> s/checkVirtualDBDesc/getVirtualDBDesc ?
</details>
This was addressed in the next commit.

---

*[sql/virtual_schema.go, line 103 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6D2UBE5BQShWrc_uS:-KO6kYGwwuRewEUO5wh7:-248053009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d963d87d465d4796592d65bd659821747131064/sql/virtual_schema.go#L103)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> really necessary?
</details>
No, but it adds a layer of abstraction so that other parts of `sql` dont need to know about the details of `virtualSchemaMap`.

---

*[sql/virtual_schema.go, line 42 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6Tu1WViBvqBb4o6ZI:-KO6j6ZI4zB4DJU3x4HP:392638635) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L42)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> wasn't the previous definition nicer? And in fact can't we make it more specific - can't it return a... `ValuesNode`?
</details>
I made the change because all of these tables are going to be doing the same thing:
- Creating a `ValuesNode`
- Populating the `ValuesNode.Column` from the table descriptor
- Populating rows

This new signature allows step 1 and 2 above to be collapsed into `getPlanNode`, and also allows common assertions like `len(columns per row) == len(valuesNode.columns)` to be shared.

---

*[sql/virtual_schema.go, line 74 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6UTca5sF6mqL9JwOK:-KO6jmhHFFmBqHYK156K:-931920670) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L74)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> do we really need struct separately from `virtualSchemaTable`?
</details>
I'm going for a clear distinction between the programmer interface of virtualSchemas (see `virtualSchema`, `virtualSchemaTable`, and `virtualSchemas` and how they are used in `information_schema.go`) from the statically generated data structures. Both of the descriptors are statically generated during `init`, so it makes things much clearer if they are stored in the generated entry objects.

---

*[sql/virtual_schema.go, line 79 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6NXy1Sv_F37S7NKLz:-KO6mrZ1tg-MiZONtmsh:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L79)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> this method deserves a comment
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-:-KO6hwTaQOVJHxmcQAXj:1331464847)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/virtual_schema.go, line 42 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6Tu1WViBvqBb4o6ZI:-KO78JswzbLZpIdEVMYo:1878284033) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I made the change because all of these tables are going to be doing the same thing:
> - Creating a `ValuesNode`
> - Populating the `ValuesNode.Column` from the table descriptor
> - Populating rows
> 
> This new signature allows step 1 and 2 above to be collapsed into `getPlanNode`, and also allows common assertions like `len(columns per row) == len(valuesNode.columns)` to be shared.
</details>
OK. But how about extracting steps 1 and 2 into a helper, and leaving a single method on the struct.
If not, a more minor suggestion - can we make populate take a `ValuesNode`, instead of the callback (and make the assertion into a loop over the results)?

---

*[sql/virtual_schema.go, line 74 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6UTca5sF6mqL9JwOK:-KO77q9xwWQAjWwNdI4X:-302787314) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I'm going for a clear distinction between the programmer interface of virtualSchemas (see `virtualSchema`, `virtualSchemaTable`, and `virtualSchemas` and how they are used in `information_schema.go`) from the statically generated data structures. Both of the descriptors are statically generated during `init`, so it makes things much clearer if they are stored in the generated entry objects.
</details>
to be honest, I already got confused between the two types. I think the random future reader will not make much of your distinction. Particularly with `getPlanNode()` being split from `populate()` in different structs.
No strong opinions.

---

*[sql/virtual_schema.go, line 79 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6NXy1Sv_F37S7NKLz:-KO77LlqbIG8NPWZp0zB:1864531297) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L79)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Done.
</details>
can you change the return type to `ValuesNode` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-:-KO79DqgbogOFFs1SHjf:1417088721)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 19 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/virtual_schema.go, line 42 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6Tu1WViBvqBb4o6ZI:-KO7AjCOXiWdDF1Z0U_k:425641779) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L42)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> OK. But how about extracting steps 1 and 2 into a helper, and leaving a single method on the struct.
> If not, a more minor suggestion - can we make populate take a `ValuesNode`, instead of the callback (and make the assertion into a loop over the results)?
> 
</details>
I really don't see the benefit in that. The current approach makes the purpose of the `populate` function more directed, and it means that the instances of `populate` can ignore the specifics of `ValuesNode` completely. It also means that the instances are not allowed to manipulate any fields in `ValuesNode`, which is desirable.

All future efforts towards supporting `information_schema` will be creating `virtualSchemaTable` objects, like in the last commit in this PR. There will be about 30 of these, which is why minimizing the scope of this interface is so important. With this structure, the only thing these objects will need to worry about is mapping a `planner` to a set of rows. Importantly, they wont need to worry about their own `TableDescriptors` or setting up `valuesNode`, because this approach hides that all within `virtualSchema`. 

Are there any disadvantages to this approach that we should try to address?

---

*[sql/virtual_schema.go, line 74 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6UTca5sF6mqL9JwOK:-KO7G57WQZxbKHmhbxdl:293606886) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L74)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> to be honest, I already got confused between the two types. I think the random future reader will not make much of your distinction. Particularly with `getPlanNode()` being split from `populate()` in different structs.
> No strong opinions.
</details>
Yeah I see where you're coming from. I added a few comments to try to clear up the confusion.

I also un-embedded `virtualSchemaTable` from `virtualTableEntry` to make their respective purposes a bit more concrete. This also had the nice effect that `virtualTableEntry` no longer has a `populate` field directly on it.

---

*[sql/virtual_schema.go, line 79 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6NXy1Sv_F37S7NKLz:-KO7EbBvMim46eIwXY88:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L79)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> can you change the return type to `ValuesNode` ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119)*

**Comment by andreimatei** [comment]
Review status: 0 of 19 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/virtual_schema.go, line 42 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6Tu1WViBvqBb4o6ZI:-KOAvdLOkRvglH_Tjzio:1051863717) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I really don't see the benefit in that. The current approach makes the purpose of the `populate` function more directed, and it means that the instances of `populate` can ignore the specifics of `ValuesNode` completely. It also means that the instances are not allowed to manipulate any fields in `ValuesNode`, which is desirable.
> 
> All future efforts towards supporting `information_schema` will be creating `virtualSchemaTable` objects, like in the last commit in this PR. There will be about 30 of these, which is why minimizing the scope of this interface is so important. With this structure, the only thing these objects will need to worry about is mapping a `planner` to a set of rows. Importantly, they wont need to worry about their own `TableDescriptors` or setting up `valuesNode`, because this approach hides that all within `virtualSchema`. 
> 
> Are there any disadvantages to this approach that we should try to address?
</details>
OK, if there's so many of these virtual tables than I'll shut up.

---

*[sql/virtual_schema.go, line 74 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119#-KO6UTca5sF6mqL9JwOK:-KOAvrVfR0LzcdUU4EDv:-1221266418) ([raw file](https://github.com/cockroachdb/cockroach/blob/7694193d55d3c9f37b8badde25fa4d7b304bb5ed/sql/virtual_schema.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Yeah I see where you're coming from. I added a few comments to try to clear up the confusion.
> 
> I also un-embedded `virtualSchemaTable` from `virtualTableEntry` to make their respective purposes a bit more concrete. This also had the nice effect that `virtualTableEntry` no longer has a `populate` field directly on it.
</details>
thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8119)*

**Pull request merged**
