### PR TITLE
geo/geos: compile geo/geos package on Windows

### PR DESCRIPTION
**Pull request by otan**
This commits adds support for pkg/geo/geos to be compiled on Windows
platforms without separating by OS. This stops the split from
geos_unix.go and geos_windows.go (all back into geos.go). We've done
some #define magic for dlopen/dlsym/dlclose/dlerror to use the
equivalent windows functions.

This should stop any pesky skews between the Windows and Unix build.
Note that GEOS is not compiled in the Makefile, so this isn't tested.
What's important for now is that everything builds without skew in
a path that will commonly change.

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
bleeding edge: https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster&branch_Cockroach=48501&tab=buildTypeStatusDiv

**Review by petermattis — COMMENTED** [review]
Very nice that you figured out this magic. Did you test that the resulting binary works? I believe Bram and Darin have Windows environments they can test this on.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-:-M6gSAucB6cJu-2-MVCP:bx9dt2g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @petermattis)

___
*[pkg/geo/geos/geos.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-M6gS1l65UDy4r3QbzWW:-M6gS1l71HsFRoCn5Ghb:b-s1uj6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/422e5d260149e8263399aa1bb9a19b7b0cfefc5f/pkg/geo/geos/geos.go#L47)):*
> ```Go
> )
> 
> // maxArrayLen is the maximum safe length for this architecture.
> ```

I assume everything below is code movement from `geos_unix.go`. Reviewable is showing this as new code. If there are any additions or changes, can you highlight them?
___
*[pkg/geo/geos/geos.cc, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-M6gR7JcCRcPbbqTNJsU:-M6gR7Jd4RRjEJzkqRB8:bq4ctt) ([raw file](https://github.com/cockroachdb/cockroach/blob/422e5d260149e8263399aa1bb9a19b7b0cfefc5f/pkg/geo/geos/geos.cc#L34)):*
> ```cpp
> #define FREELIBRARY dlclose
> #define LIBRARYTYPE void*
> #endif // #if _WIN32
> ```

Would it be cleaner to provide the #defines only on Windows? Something like:

```
#if _WIN32
#define dlopen(x,y) LoadLibrary(x)
#define dlsym GetProcAddress
#define dlclose FreeLibrary
#define dlerror() "failed to execute dlsym"
typedef HMODULE dlhandle;
#else 
typedef void* dlhandle;
#endif 
```

Then the only thing that needs to change below is `s/void*/dlhandle/g`.

**Review by otan — COMMENTED** [review]
> Did you test that the resulting binary works? I believe Bram and Darin have Windows environments they can test this on.

I haven't tried it yet. Was planning on solving that down the line (I had a hard time getting the build/builder.sh thing to work with Window) - do we think we should before this goes in? (I can get my trusty Windows machine out to give it a whirl on Friday perhaps and then we can claim geo to work with windows :') )

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-:-M6h8M_uEvzVbXtgef_o:bfnvakm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/geo/geos/geos.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-M6gS1l65UDy4r3QbzWW:-M6h8Dpg82qjN9N4eX59:bmiobnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/422e5d260149e8263399aa1bb9a19b7b0cfefc5f/pkg/geo/geos/geos.go#L47)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I assume everything below is code movement from `geos_unix.go`. Reviewable is showing this as new code. If there are any additions or changes, can you highlight them?
</blockquote></details>

Only one.
___
*[pkg/geo/geos/geos.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-M6h8Fic1397XK6qQcSR:-M6h8Fic1397XK6qQcSS:b-q83218) ([raw file](https://github.com/cockroachdb/cockroach/blob/422e5d260149e8263399aa1bb9a19b7b0cfefc5f/pkg/geo/geos/geos.go#L95)):*
> ```Go
> 	case "darwin":
> 		ext = "dylib"
> 	case "windows":
> ```

(the only change was here)
___
*[pkg/geo/geos/geos.cc, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-M6gR7JcCRcPbbqTNJsU:-M6h9jQu4hH9Wyvh0rck:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/422e5d260149e8263399aa1bb9a19b7b0cfefc5f/pkg/geo/geos/geos.cc#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Would it be cleaner to provide the #defines only on Windows? Something like:

```
#if _WIN32
#define dlopen(x,y) LoadLibrary(x)
#define dlsym GetProcAddress
#define dlclose FreeLibrary
#define dlerror() "failed to execute dlsym"
typedef HMODULE dlhandle;
#else 
typedef void* dlhandle;
#endif 
```

Then the only thing that needs to change below is `s/void*/dlhandle/g`. 
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
> I haven't tried it yet. Was planning on solving that down the line (I had a hard time getting the build/builder.sh thing to work with Window) - do we think we should before this goes in? (I can get my trusty Windows machine out to give it a whirl on Friday perhaps and then we can claim geo to work with windows :') )

I think we can merge this without testing on Windows as it should prevent bleeding-edge build breakage. But let's try to get that testing done soon. I'd ping @darinpp to see if he can help. All we really need to do is to make sure the Cockroach binary starts.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-:-M6iyVrH4BuZW9X3ROTe:bgbowmf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geos/geos.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-M6h8Fic1397XK6qQcSR:-M6iyPKC37Kt65zp1KmB:bbpax04) ([raw file](https://github.com/cockroachdb/cockroach/blob/422e5d260149e8263399aa1bb9a19b7b0cfefc5f/pkg/geo/geos/geos.go#L95)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(the only change was here)
</blockquote></details>

Ack. Thanks. Looks good.
___
*[pkg/geo/geos/geos.cc, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-M6iyKQiA0WAiBnUXb35:-M6iyKQiA0WAiBnUXb36:bnxcysw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29e4a4873b81957be2c58ede83a7dda91b80dbc/pkg/geo/geos/geos.cc#L93)):*
> ```cpp
> 
> const char* dlopenFailError = "failed to execute dlopen";
> const char* dlsymFailError = "failed to execute dlsym";
> ```

I think this is now unused.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48501)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @petermattis)

___
*[pkg/geo/geos/geos.cc, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48501#-M6iyKQiA0WAiBnUXb35:-M6jT_p0D5DpmbUC9iNX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29e4a4873b81957be2c58ede83a7dda91b80dbc/pkg/geo/geos/geos.cc#L93)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this is now unused.
</blockquote></details>

Done.

**Comment by otan** [comment]
TFTR! 

bors r=petermattis

**Pull request merged**
