### PR TITLE
clusterversion: create 24.3 version

### LINKED ISSUE #128747: kv: panic in HandleRaftUncoalescedRequest in mixed cluster
While working on adding 24.3 versions (#128616), I noticed the `version-upgrade` roachtest failing, with one node crashing here:
```
runtime error: index out of range [24] with length 24
*   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleRaftUncoalescedRequest
```
Code:
```go
	s.metrics.RaftRcvdMessages[req.Message.Type].Inc(1)
```

Two new message types were added after 24.2 branched in #128426

~Looks like this problem is in 24.1 as well, which will be problematic in 24.1 -> 24.3 upgrades.~ Edit: actually, if this was true, we would have seen failures on upgrades test on master and on 24.2. To be investigated some more

Jira issue: CRDB-41178

### PR DESCRIPTION
**Pull request by RaduBerinde**
- [x] Add version key constant for new release (e.g. `V24.2`), equal to `Latest`
- [x] Update `PreviousRelease` constant
- [x] Add start version (e.g. `V24.2Start` with version `24.1-2`)
- [x] Update `pkg/build/version.txt` to the new version (e.g. `v24.2.0-alpha.00000000`)
- [x] Add mixed version logictest config for the replaced version
- [x] Update the `scplan` rules in `pkg/sql/schemachanger/scplan/internal/rules`
- [x] Create new roachtest fixtures for the previous version
- [x] Create new SQL bootstrap data
- [x] Update releases file

Epic: REL-1163
Release note: None
Fixes #128747

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128616)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @celiala, @RaduBerinde, and @renatolabs)

___
*[`pkg/clusterversion/cockroach_versions.go` line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128616#-O3x8v770-K8fyUtE1Zz:-O3x8v770-K8fyUtE1_-:b-bnzsur) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a58bac2b43b145eb00d3ad06b4bd6ef88348c3a/pkg/clusterversion/cockroach_versions.go#L334)):*
> ```Go
> 	V24_2_TenantRates:                 {Major: 24, Minor: 1, Internal: 8},
> 	V24_2_DeleteTenantSettingsVersion: {Major: 24, Minor: 1, Internal: 10},
> 	V24_2_LeaseMinTimestamp:           {Major: 24, Minor: 1, Internal: 12},
> ```

I don't think we should change `V24_2_LeaseMinTimestamp`. I only piggybacked off it in https://github.com/cockroachdb/cockroach/pull/128647. It was introduced before and is used elsewhere. It exists on `release-24.2`, so I imagine making this change would cause issues.

Instead, we should leave this as is, and introduce a new `V24_3_StoreLivenessEnabled` version after `V24_3Start`. Then, if we use this in replica_store_liveness.go, I think all tests should pass. I had some words around this in this TODO:
https://github.com/cockroachdb/cockroach/blob/167047ee3007557d4d1184b3524cace4672becf6/pkg/kv/kvserver/replica_store_liveness.go#L75-L78

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128616)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @celiala, and @renatolabs)

___
*[`pkg/clusterversion/cockroach_versions.go` line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128616#-O3x8v770-K8fyUtE1Zz:-O3xRQymE5DAq3uZctNs:b-jifd3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a58bac2b43b145eb00d3ad06b4bd6ef88348c3a/pkg/clusterversion/cockroach_versions.go#L334)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't think we should change `V24_2_LeaseMinTimestamp`. I only piggybacked off it in https://github.com/cockroachdb/cockroach/pull/128647. It was introduced before and is used elsewhere. It exists on `release-24.2`, so I imagine making this change would cause issues.

Instead, we should leave this as is, and introduce a new `V24_3_StoreLivenessEnabled` version after `V24_3Start`. Then, if we use this in replica_store_liveness.go, I think all tests should pass. I had some words around this in this TODO:
https://github.com/cockroachdb/cockroach/blob/167047ee3007557d4d1184b3524cace4672becf6/pkg/kv/kvserver/replica_store_liveness.go#L75-L78
</blockquote></details>

Ohh I see now. I had thought I looked at the `release-24.2`branch and didn't see the gate but I must have messed something up. This makes a lot more sense now. Done. Thanks!!

**Review by arulajmani — APPROVED** [review]
StoreLiveness related changes :lgtm: 

> Reviewed 2 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128616#-:-O3xqsnjC71SnfEhNGEw:b2tqspt)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @celiala, @RaduBerinde, and @renatolabs)

___
*[`pkg/clusterversion/cockroach_versions.go` line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128616#-O3x8v770-K8fyUtE1Zz:-O3xqeJBBz2MYwhdRDiI:b-lpddzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a58bac2b43b145eb00d3ad06b4bd6ef88348c3a/pkg/clusterversion/cockroach_versions.go#L334)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ohh I see now. I had thought I looked at the `release-24.2`branch and didn't see the gate but I must have messed something up. This makes a lot more sense now. Done. Thanks!!
</blockquote></details>

Thanks, and sorry for the trouble my hack to merge that PR caused you.
___
*[`pkg/clusterversion/cockroach_versions.go` line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128616#-O3xqEBq1ookGCvmBqc_:-O3xqEBq1ookGCvmBqca:b9d4sb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b70eb66773edf938b177ee58bee9104869b8430b/pkg/clusterversion/cockroach_versions.go#L278)):*
> ```Go
> 	V24_3_Start
> 
> 	// V24_3_StoreLivenessEnabled TODO
> ```

nit: V24_3_StoreLivenessEnabled is the earliest version which supports the use of the StoreLiveness fabric.

**Review by celiala — APPROVED** [review]
thank you! LGTM

(modulo reverting V24_2_LeaseMinTimestamp back to original value, as discussed)

> Reviewed 43 of 49 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128616#-:-O3zH-FrC44McLjFuJ9a:bqhlcsl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @renatolabs)

___
*[`pkg/clusterversion/cockroach_versions.go` line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128616#-O3zGCR95u5zUv2vEKBl:-O3zGCR95u5zUv2vEKBm:b-vyd0ht) ([raw file](https://github.com/cockroachdb/cockroach/blob/b70eb66773edf938b177ee58bee9104869b8430b/pkg/clusterversion/cockroach_versions.go#L346)):*
> ```Go
> 	V24_2_LeaseMinTimestamp:           {Major: 24, Minor: 2, Internal: 12},
> 
> 	V24_2: {Major: 24, Minor: 2, Internal: 0},
> ```

oops. I added this to release-24.2 but forgot to also add this to master. sorry, my bad (noted in my runbook for next time).x//.x.

**Comment by RaduBerinde** [comment]
*[`pkg/clusterversion/cockroach_versions.go` line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128616#-O3zGCR95u5zUv2vEKBl:-O3zKmv73O1qQfbwn2P2:bxnrviv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b70eb66773edf938b177ee58bee9104869b8430b/pkg/clusterversion/cockroach_versions.go#L346)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

oops. I added this to release-24.2 but forgot to also add this to master. sorry, my bad (noted in my runbook for next time).x//.x.
</blockquote></details>

No, it wouldn't have worked - we can't have an internal=0 as the latest version of master (a dev branch). I think it always needs to be done together with starting the new release versions.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128616)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @celiala, and @renatolabs)

___
*[`pkg/clusterversion/cockroach_versions.go` line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128616#-O3xqEBq1ookGCvmBqc_:-O3zs4hAD2VvWhelYtF1:bohi7pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b70eb66773edf938b177ee58bee9104869b8430b/pkg/clusterversion/cockroach_versions.go#L278)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: V24_3_StoreLivenessEnabled is the earliest version which supports the use of the StoreLiveness fabric.
</blockquote></details>

Oops, thanks, done!

**Review by renatolabs — APPROVED** [review]
LGTM!

**Comment by RaduBerinde** [comment]
Correction: this was [REL-1045](https://cockroachlabs.atlassian.net/browse/REL-1045)

**Pull request merged**
