### PR TITLE
sql: disable unimplemented interval production

### PR DESCRIPTION
**Pull request by eisenstatdavid**

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
Thanks! Hmm, maybe we should also add a logic test to remind us to actually think about what this should do when someone decides to re-enable it?

**Comment by eisenstatdavid** [comment]
I think we can assume that whoever reenables this syntax will write a test, and if they don't, then their reviewer will force them to.

**Comment by jordanlewis** [comment]
Fair enough.

Actually, on further consideration, would it be strictly better to change this rule to behave exactly as the precisionless interval rule?

That would match our behavior for other similar things, such as the precision of integer types small than `int8`.

**Comment by eisenstatdavid** [comment]
I'm not keen on that behavior, but I think that it's more defensible for small int types, where the observable behavior is the same for values that don't overflow.

Regardless of what we decide, my main concern is that we not have syntax that parses but `.Serialize`s to something that cannot be parsed.

**Comment by jordanlewis** [comment]
Okay, makes sense. This LGTM. I'm irrationally nervous that there is someone out there using this (incorrectly evaluated) syntax who will be sorely disappointed that their app doesn't work anymore post 1.0. This is admittedly super unlikely, but I just wanted to get it out of my head.

**Pull request merged**
