### PR TITLE
security: update the TLS cipher suite list

### LINKED ISSUE #80483: Add CHACHA ciphers for TLS 1.2
Please add support for the following ciphers in TLS 1.2
- TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
- TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

### PR DESCRIPTION
**Pull request by knz**
Fixes #80483 

This does not really change the list, it merely explains more clearly
how it was built.

Release note: None

### CODE REVIEW

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80476)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @knz)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-N0WVmhE91SvkyYQTmKp):*
Do not say that TLS 1.2 is deprecated; we're still a long way from starting that process (and it's not really our call. TLS 1.1 was deprecated by RFC 8996, and I expect we'll follow a similar IETF-led process when it's time to drop 1.2).
___
*[`pkg/security/tls.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-N0WXZJWDEOsbE3Dz1pF:-N0WXZJWDEOsbE3Dz1pG:b78oafg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f2866e057cac03c23fa713441c16ecee1adf50/pkg/security/tls.go#L162)):*
> ```Go
> 		//   include at least one cipher higher in the priority list, but
> 		//   there's also no reason to keep it around)
> 		// - AES is always prioritized over ChaCha20. Go makes this decision
> ```

While you're here, this point can be removed. In current versions of go, the order of this list is ignored and the implementation will reorder AES vs ChaCha20 automatically. 
___
*[`pkg/security/tls.go` line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-N0WX-Cd1Bgbno1OaAoK:-N0WX-Cd1Bgbno1OaAoL:b56b6u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f2866e057cac03c23fa713441c16ecee1adf50/pkg/security/tls.go#L184)):*
> ```Go
> 			tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
> 			tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
> 			tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
> ```

These constants with the SHA256 suffixes are equal to the preceding ones without SHA256; there's no reason to have both in the list (see [this commit](https://github.com/golang/go/commit/e2cac315082a9267135e96249b537d0bd0703175)).

The SHA256 names are the official ones, so it's good to change from the deprecated aliases to the proper names, but we're not adding any new ciphers to the list and therefore we don't need to document anything in release notes. 
___
*[`pkg/security/tls.go` line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-N0WXOyb5Xtek4idxKVa:-N0WXOyb5Xtek4idxKVb:b-68z97t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f2866e057cac03c23fa713441c16ecee1adf50/pkg/security/tls.go#L194)):*
> ```Go
> 			tls.TLS_RSA_WITH_AES_128_CBC_SHA,
> 			tls.TLS_RSA_WITH_AES_256_CBC_SHA,
> 			// NB: no need to add TLS 1.3 ciphers here. As per the
> ```

Thanks for this comment; it's a common point of confusion.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80476)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @knz)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-N0WVmhE91SvkyYQTmKp):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Do not say that TLS 1.2 is deprecated; we're still a long way from starting that process (and it's not really our call. TLS 1.1 was deprecated by RFC 8996, and I expect we'll follow a similar IETF-led process when it's time to drop 1.2).
</blockquote></details>

Done.
___
*[`pkg/security/tls.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-N0WXZJWDEOsbE3Dz1pF:-N0jSC-Y0-wSF85wiOsX:bw95xad) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f2866e057cac03c23fa713441c16ecee1adf50/pkg/security/tls.go#L162)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

While you're here, this point can be removed. In current versions of go, the order of this list is ignored and the implementation will reorder AES vs ChaCha20 automatically. 
</blockquote></details>

I went to the source code and I don't see what you say. I still see the code that pulls AES up if supported in hardware, but it's not unconditional?
___
*[`pkg/security/tls.go` line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-N0WX-Cd1Bgbno1OaAoK:-N0jSHoe8QwIUCUR-kB1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f2866e057cac03c23fa713441c16ecee1adf50/pkg/security/tls.go#L184)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

These constants with the SHA256 suffixes are equal to the preceding ones without SHA256; there's no reason to have both in the list (see [this commit](https://github.com/golang/go/commit/e2cac315082a9267135e96249b537d0bd0703175)).

The SHA256 names are the official ones, so it's good to change from the deprecated aliases to the proper names, but we're not adding any new ciphers to the list and therefore we don't need to document anything in release notes. 
</blockquote></details>

Done.

**Review by bdarnell — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-:-N14hebCCJCbCxr8NvI0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @knz)

___
*[`pkg/security/tls.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-N0WXZJWDEOsbE3Dz1pF:-N14g0mJ9ly-M9ePbqSu:brb41pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f2866e057cac03c23fa713441c16ecee1adf50/pkg/security/tls.go#L162)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I went to the source code and I don't see what you say. I still see the code that pulls AES up if supported in hardware, but it's not unconditional?
</blockquote></details>

In older versions of Go, `Config.CipherSuites` is treated as a static ordered list (i.e. it uses the input order to prioritize ciphers), but if `Config.CipherSuites` the defaults would be computed dynamically to prioritize AES or ChaCha based on hardware capabilities. This comment was referring to the fact that the dynamic prioritization was lost if any CipherSuites were specified.

In newer versions of Go, `Config.CipherSuites` is treated as an unordered set and the `crypto/tls` library will apply the dynamic prioritization order to that set, so we no longer lose anything by passing in ciphers. 

https://github.com/golang/go/commit/9d0819b27ca248f9949e7cf6bf7cb9fe7cf574e8

**Review by knz — COMMENTED** [review]
TFYR

bors r=bdarnell

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-:-N19oUY35xAdiB25_vnG:bmy2ss7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @knz)

___
*[`pkg/security/tls.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80476#-N0WXZJWDEOsbE3Dz1pF:-N19oOLV4VmkAJOKOu6x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2f2866e057cac03c23fa713441c16ecee1adf50/pkg/security/tls.go#L162)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In older versions of Go, `Config.CipherSuites` is treated as a static ordered list (i.e. it uses the input order to prioritize ciphers), but if `Config.CipherSuites` the defaults would be computed dynamically to prioritize AES or ChaCha based on hardware capabilities. This comment was referring to the fact that the dynamic prioritization was lost if any CipherSuites were specified.

In newer versions of Go, `Config.CipherSuites` is treated as an unordered set and the `crypto/tls` library will apply the dynamic prioritization order to that set, so we no longer lose anything by passing in ciphers. 

https://github.com/golang/go/commit/9d0819b27ca248f9949e7cf6bf7cb9fe7cf574e8
</blockquote></details>

Done.

**Pull request merged**
