### PR TITLE
sql: obey table descriptor lease expiration in transactions

### LINKED ISSUE #6050: sql: prevent sql transactions from committing after the descriptor leases they've used have expired
The method `client.Txn.CommitBy` was added in #3028 to address #2820, which said that this functionality was needed to support table leases. However, this method was never used outside of tests; we still need to actually use this functionality when committing sql transactions to ensure that the transactions stay within the bounds of their table lease. Or if this is no longer necessary for correctness at the sql level, we could consider deprecating and removing the functionality.

### PR DESCRIPTION
**Pull request by vivekmenezes**
Replaced CommitBy() with SetDeadline() in the txn API because it
fits well with the use case.

Fixes #6050

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6418)

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 660 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc3gh_wXqHxYdFDj2Q:-KGc3ghai-crW2VfYpaS:1113468496) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/client/txn.go#L660)):*
Transaction deadlines refer to the transaction's commit timestamp, not wall time. The deadline should be compared to the timestamp in the batch header; see `storage.isEndTransactionExceedingDeadline`. 

This branch (`elideEndTxn`) is only taken for read-only transactions; I don't think there's any other way for read-only transactions to generate a `TransactionAbortedError`. Is this check necessary for read-only transactions?

---

*[sql/lease.go, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc56lz7Ai_crUGZnaq:-KGc56lz7Ai_crUGZnar:870626109) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease.go#L55)):*
Can you put this in `LeaseManagerTestingKnobs` instead?

---

*[sql/lease_test.go, line 572 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc6m5sbWNLjHdl05eQ:-KGc6m5sbWNLjHdl05eR:1159143860) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L572)):*
This is likely to be flaky on circleci: this command may not be able to complete before the 5ms lease expires. Can you test this instead with a manual clock, and advance it instead of sleeping to expire the lease?

---

*[sql/lease_test.go, line 579 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc7JpEuggmkvzECaRV:-KGc7JpEuggmkvzECaRW:1118508738) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L579)):*
Are there interesting differences between the different commands here? I could see doing a read-only and read-write command, but I'm not sure what you gain by trying all the different write commands.

---

*[sql/lease_test.go, line 579 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc7Zb1GUTB3jJTOz9f:-KGc7Zb1GUTB3jJTOz9g:2081951809) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L579)):*
These tests use a lease which is expired from the time it is acquired. It is perhaps more interesting (and closer to the intended use case of the commit deadline) to do a test in which the lease was valid when the transaction started but expired before it committed (or the transaction was pushed into the future past its lease expiration)

---

*[sql/lease_test.go, line 592 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc65bdoqCQEjPhOzqT:-KGc65bdoqCQEjPhOzqU:499901550) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L592)):*
`sql.DB` doesn't guarantee that you'll always use the same connection. Transactions need to go through the `DB.Begin()` method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by vivekmenezes** [comment]
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 660 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc3gh_wXqHxYdFDj2Q:-KGiuZwpxjkiXuKCbSzb:170443016) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/client/txn.go#L660)):*
The batch header is not available at this point in the code.

I think this code should probably be removed and I think we're being overly paranoid here. It's a situation where a table descriptor version is picked for the transaction and expires before the transaction timestamp for the transaction is picked. I don't see how that's possible.

---

*[sql/lease_test.go, line 579 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc7JpEuggmkvzECaRV:-KGiyCEhGcL6pQzGbWoT:1428819348) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L579)):*
Just in case they start using their own code path later and someone forgets to apply the deadline on that path.

---

*[sql/lease_test.go, line 579 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc7Zb1GUTB3jJTOz9f:-KGiyNNZjnZAc04Qxv9v:-391333460) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L579)):*
Yeah, I did try opening a transaction and delaying it, but the transaction used the initial timestamp picked before the delay, and so it's deadline was not expiring.  I believe if the transaction gets pushed it gets restarted and picks up a new lease, so I don't see how I can simulate it that way too. But I agree it makes sense to create a practical example, or else, how do we justify this change. I just don't know how to create it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by bdarnell** [comment]
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 660 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc3gh_wXqHxYdFDj2Q:-KGktiUPXT53RwtOhT3I:482702112) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/client/txn.go#L660)):*
Yeah, I think it's fine to remove this check. I'm wary of arguments that "these two timestamps won't be *that* far apart", but since our table leases last so long (`MinLeaseDuration` is 1m currently) it seems safe enough.

If we did want to enforce it, we'd need to introduce a new option `MaxInitialTimestamp` (like `MinInitialTimestamp`) to let the SQL layer communicate the lease expiration timestamp down to the sql layer. 

---

*[sql/lease_test.go, line 579 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc7Zb1GUTB3jJTOz9f:-KGkwpnj8_2reNxnn4K8:1710570474) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L579)):*
`SNAPSHOT` transactions can be pushed without restarting (Is that the only time when this matters? If we did more caching of prepared plans it might come up in more situations). So I think what we need is to start a snapshot transaction and do a write, advance the clock to expire the lease, do a read from a separate transaction to push the first transaction's timestamp, then try to commit the first transaction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by vivekmenezes** [comment]
Review status: 2 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[client/txn.go, line 660 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc3gh_wXqHxYdFDj2Q:-KGlV00PdrXU1pFUjCK1:-895907901) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/client/txn.go#L660)):*
removed. I've also removed the support for returning an error in 1PC txns when they exceed the deadline. Exceeding the deadline in that case is also impossible..

---

*[sql/lease_test.go, line 572 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc6m5sbWNLjHdl05eQ:-KGmjtKtPG7VYyUhMsC5:-546390631) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L572)):*
I've not used the manual clock, but instead increased the lease expiration to 50ms and use Clock.Update() to speed up the testing, effectively making it a manual clock.

---

*[sql/lease_test.go, line 579 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc7Zb1GUTB3jJTOz9f:-KGmZvmz0VY4qNeabjAc:1384259260) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L579)):*
Done as you've suggested. In doing so I uncovered a bug. We were originally comparing the deadline supplied to the one in the request header, we now check the deadline against the timestamp in the txn record, which is the right thing to do because the pushed timestamp is only available in the txn record.

---

*[sql/lease_test.go, line 592 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc65bdoqCQEjPhOzqT:-KGmZRseUTh7V-Ex0jYD:-467915377) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L592)):*
fixed

---

*[sql/lease.go, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc56lz7Ai_crUGZnaq:-KGmZmOZLSfhPldZku9v:-1787734878) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease.go#L55)):*
not needed any more

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by tschottdorf** [comment]
Review status: 2 of 8 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[sql/lease_test.go, line 572 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc6m5sbWNLjHdl05eQ:-KGmt_Gz3RZiXFseLUIK:-2018325679) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L572)):*
I have not checked the 

---

*[storage/replica.go, line 1802 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuEHorwjiaPgN67IF:-KGmuEHpI8teA3LUsPEK:-885227919) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ab801227e182c1aa2cbcd22f2a5f6cd4d9a07c/storage/replica.go#L1802)):*
The check should still run. A 1PC txn still has a deadline which needs to be checked - the deadline could have expired as the txn restarted (and came back as 1PC).

---

*[storage/replica_command.go, line 442 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuS0PiowDYrHNDJsD:-KGmuS0PiowDYrHNDJsE:-732396412) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c465325d47c17c39c0bc317c2a492e0aa1890d/storage/replica_command.go#L442)):*
This changed behaviour unfortunately requires a migration and deserves a test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by vivekmenezes** [comment]
Review status: 2 of 8 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1802 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuEHorwjiaPgN67IF:-KGn0hCblzdYIxjTOGLt:952939316) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ab801227e182c1aa2cbcd22f2a5f6cd4d9a07c/storage/replica.go#L1802)):*
I can obviously put it back in but I'd like to put in a SQL layer test to ensure that we actually hit this functionality at that level. Any ideas would be appreciated.

---

*[storage/replica_command.go, line 442 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuS0PiowDYrHNDJsD:-KGn0tN-zGNkOlUJesne:1854558739) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c465325d47c17c39c0bc317c2a492e0aa1890d/storage/replica_command.go#L442)):*
I will add a test similar to the SQL test using snapshot isolation. What do you mean by a migration?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by vivekmenezes** [comment]
*[storage/replica_command.go, line 442 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuS0PiowDYrHNDJsD:-KGn7x7kzQQHiLha8IXU:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c465325d47c17c39c0bc317c2a492e0aa1890d/storage/replica_command.go#L442)):*
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by vivekmenezes** [comment]
Review status: 1 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/lease_test.go, line 572 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGc6m5sbWNLjHdl05eQ:-KGnCdMI20xP49_h5EEI:-546934934) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb69dbbfa322a90df8b82f9db9ce4a97fcbf2ab/sql/lease_test.go#L572)):*
I've adopted this mechanism because there isn't an existing mechanism to pass in a ManualClock into a TestServer. Adding it will mean some churn to one of the APIs. Since we don't really need a manual clock I'd rather not do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by tschottdorf** [comment]
Review status: 1 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 1802 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuEHorwjiaPgN67IF:-KGnPBbnTcKQjIam5Dok:1579800584) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ab801227e182c1aa2cbcd22f2a5f6cd4d9a07c/storage/replica.go#L1802)):*
I think it's important to get the unit tests right first and then think about high-level functionality. This is a KV feature, it should work and be tested in KV. Higher-level SQL tests with a lot of moving parts may be hard to construct for this particular thing and, while nice, I really just want the unit test to be there.

---

*[storage/replica_command.go, line 442 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuS0PiowDYrHNDJsD:-KGnOlCtFhmn5DkWysxV:1013390126) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c465325d47c17c39c0bc317c2a492e0aa1890d/storage/replica_command.go#L442)):*
We should have unit tests for this and if none of them broke, I'd be good if you could update them so that they would break with the old version of your code.
Building SQL-level tests when that lower-level functionality isn't tested is taking step two too early.

By migration I meant that you're changing code downstream of Raft, and so upgrading across that version of Cockroach is nontrivial. We can hopefully merge the Freeze/Unfreeze PR soon though, which would address that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by bdarnell** [comment]
Reviewed 4 of 7 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/lease_test.go, line 554 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGng8g4o7gbUpTNbOUY:-KGng8g5h09qwpQfKCuu:-403101607) ([raw file](https://github.com/cockroachdb/cockroach/blob/254b92f43608074951e151a46860ca4e8ea2bb65/sql/lease_test.go#L554)):*
Remove this.

---

*[sql/lease_test.go, line 586 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGngWJJhuZ3ghcoff1R:-KGngWJJhuZ3ghcoff1S:726863419) ([raw file](https://github.com/cockroachdb/cockroach/blob/254b92f43608074951e151a46860ca4e8ea2bb65/sql/lease_test.go#L586)):*
That sounds like a problem that needs to be fixed. Shouldn't it be getting a new lease and a new deadline on the retry?

---

*[storage/replica_command.go, line 442 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuS0PiowDYrHNDJsD:-KGngoh9j_o7ncn82WD4:49714641) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c465325d47c17c39c0bc317c2a492e0aa1890d/storage/replica_command.go#L442)):*
I'm fine letting this in without a migration because `EndTransactionRequest.Deadline` was not actually used anywhere before this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by vivekmenezes** [comment]
This PR is ready for another review. I'd like to include a SQL test for the 1PC case before I can merge this, so that we understand why we need it. We got rid of deadlines for read-only transactions because we couldn't imagine how their leases could expire.

---

Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[sql/lease_test.go, line 554 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGng8g4o7gbUpTNbOUY:-KGo6dDOjnsjfIA_VyW0:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/254b92f43608074951e151a46860ca4e8ea2bb65/sql/lease_test.go#L554)):*
done

---

*[sql/lease_test.go, line 586 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGngWJJhuZ3ghcoff1R:-KGo7Dvo64YZ7yJjL3x0:1757310970) ([raw file](https://github.com/cockroachdb/cockroach/blob/254b92f43608074951e151a46860ca4e8ea2bb65/sql/lease_test.go#L586)):*
This entire comment was outdated. I've rephrased it. 

It does get a new lease and deadline on the retry. In this test I'd originally handed out expired leases to test that the transactions aborted, and when they were single statement they would retry indefinitely because we would keep handing out expired lease. The test is now quite different from that original implementation.

---

*[storage/replica.go, line 1802 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuEHorwjiaPgN67IF:-KGo7xT3z6SF9UcvLl_p:1375962466) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ab801227e182c1aa2cbcd22f2a5f6cd4d9a07c/storage/replica.go#L1802)):*
Oh yes I've left it in there, but I'd like to create a SQL test to exercise this code, or else what's the point of it. 

---

*[storage/replica_command.go, line 442 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuS0PiowDYrHNDJsD:-KGoACybfg8m-uLERM0C:1750401144) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c465325d47c17c39c0bc317c2a492e0aa1890d/storage/replica_command.go#L442)):*
The tests test this change and break without it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-:-KGoAk74q022uA-63YQ6:1840863732)*

**Comment by bdarnell** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/lease_test.go, line 586 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGngWJJhuZ3ghcoff1R:-KGqJNLg3Kt5zODdi8cw:-1628342066) ([raw file](https://github.com/cockroachdb/cockroach/blob/254b92f43608074951e151a46860ca4e8ea2bb65/sql/lease_test.go#L586)):*
Doesn't look like you've pushed the new version.

---

*[storage/replica_command.go, line 442 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuS0PiowDYrHNDJsD:-KGqJVV2j56Sm7NDSxUN:564646535) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c465325d47c17c39c0bc317c2a492e0aa1890d/storage/replica_command.go#L442)):*
Yes, I mean it was not used anywhere in production.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by vivekmenezes** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/lease_test.go, line 586 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGngWJJhuZ3ghcoff1R:-KGqs_Em8q5Lk_ggEJXS:-1007662675) ([raw file](https://github.com/cockroachdb/cockroach/blob/254b92f43608074951e151a46860ca4e8ea2bb65/sql/lease_test.go#L586)):*
pushed a new version. Sorry!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by bdarnell** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1802 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuEHorwjiaPgN67IF:-KGqwn4BN9DypnOeGxW3:1276942763) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ab801227e182c1aa2cbcd22f2a5f6cd4d9a07c/storage/replica.go#L1802)):*
It's going to be tricky to test this reliably at the SQL layer since 1PC transactions are kind of a black box. You'd either need to introduce some new testing hooks or rely on two operations racing against each other. 

However, it's relatively easy to test at the KV layer, and since this is a KV feature we should make sure it works there even if it doesn't come up in practice with SQL queries. This also argues for enforcing deadlines on read-only transactions, but that would require implementing a new low-priority feature, while for 1PC transactions we just have to avoid breaking something that's already there (assuming what's already there works, and I'm not sure it does - I think the timestamp cache may push the transaction's commit timestamp after we've already checked the deadline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1802 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuEHorwjiaPgN67IF:-KGrWIG0cIirWPkFuM2c:1079774363) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ab801227e182c1aa2cbcd22f2a5f6cd4d9a07c/storage/replica.go#L1802)):*
One thing to keep in mind is that I think we we disable 1pc txns in sql tests here
https://github.com/cockroachdb/cockroach/blob/220846bcecd76b0f90079d4e5377d6ecb81f7035/sql/main_test.go#L196

I think it's probably a bad thing we do :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1802 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-KGmuEHorwjiaPgN67IF:-KGr_PVsKsWehPYYh3Y8:-728194630) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ab801227e182c1aa2cbcd22f2a5f6cd4d9a07c/storage/replica.go#L1802)):*
created an issue for that https://github.com/cockroachdb/cockroach/issues/6468

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418)*

**Comment by vivekmenezes** [comment]
I've added a commit which forces a panic when a 1pc or read-only txn exceeds its deadline. I feel it's the right approach given what we know.

---

Review status: 2 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-:-KGsBEI1U1DdLb5o-h5t:1472025406)*

**Comment by bdarnell** [comment]
Why break the 1PC functionality that was already there and tested? It wasn't perfect (if my understanding of the timestamp cache push is accurate), but it's better to keep it in than to turn it into a panic. A panic is a pretty harsh response to an error like this; read-only transactions would be better off with an error than panicking the server.

---

Review status: 2 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-:-KGscRRy5tgcY2SXnkOl:-252731218)*

**Comment by vivekmenezes** [comment]
Sounds good. I agree that it's pretty harsh. Ill change them to errors

**Comment by vivekmenezes** [comment]
I removed the commit that adds the two panics and added a new commit that ensures that a read-only transaction does not violate its deadline. 1PC transactions behave the same way. There are no tests at the SQL level for the 1PC and read-only case.

---

Review status: 2 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6418#-:-KGtXmBrKxv8F3HN7YUb:924286328)*

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
