### PR TITLE
distsql: consult liveness during physical planning

### PR DESCRIPTION
**Pull request by tbg**
The recent PR #22658 introduced a regression in
`(*rpcContext).ConnHealth` which caused DistSQL to continue planning on
unavailable nodes for about an hour (`ttlNodeDescriptorGossip`) if the
leaseholder cache happened to not be updated by other non-DistSQL
requests.

Instead, consult node liveness and avoid planning on dead nodes. This
reduces the problem to a <10s window. The defunct `ConnHealth` mechanism
still protects against planning in some of cases (supposedly due to a
once-per-second reconnection policy) and is retained for that reason,
with issue #23829 filed to decide its future.

NB: I'm not putting a release note since this was introduced after 1.1.
We released it in a beta, though, so it may be worth calling out there.

Touches #23601. (Not fixing it because this issue should only close
when there's a roachtest).

Release note (bug fix): NB: this fixes a regression introduced in
2.0-beta, and not present in 1.1: Avoid planning DistSQL errors against
unavailable nodes.

### CODE REVIEW

**Comment by tschottdorf** [comment]
@solongordon with this change I'm unable to repro any planning errors (sleeping 10s after the kill to make liveness time out). Could you give it a spin too to make sure I'm not messing this up (again)?

**Comment by solongordon** [comment]
Yup, I'm also unable to repro the error with this patch (except within 10s of killing the node).

**Comment by andreimatei** [comment]
:lgtm:

Thanks Tobias. You also did DistSender improvements elsewhere, right?

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 530 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23834#-L7e3U7V1qjqAFMbJi6i:-L7e3U7V1qjqAFMbJi6j:bfchfd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/712962305ab608f6060909ab0fa917410facca4d/pkg/sql/distsql_physical_planner.go#L530)):*
> ```Go
> 	//
> 	// TODO(tschottdorf): it's not clear that this adds anything to the liveness
> 	// check below. The node descriptor TTL is an hour at the time of writing.
> ```

nit nit: i prefer "as of 03/2018"

---

*[pkg/sql/distsql_physical_planner.go, line 561 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23834#-L7e3frRxIyj4R_k15ra:-L7e3frRxIyj4R_k15rb:bosk88j) ([raw file](https://github.com/cockroachdb/cockroach/blob/712962305ab608f6060909ab0fa917410facca4d/pkg/sql/distsql_physical_planner.go#L561)):*
> ```Go
> 	}
> 
> 	// NB: not all tests populate a NodeLiveness. Everything using the
> ```

I'm not a fan of this comment. Better say on the field definition "can be nil for tests", and remove the panic from the ctor too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23834#-:-L7e3wAvlzJef-u3K_it:b-gr1wp2)*

**Comment by tschottdorf** [comment]
PTAL, added rudimentary unit testing.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 530 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23834#-L7e3U7V1qjqAFMbJi6i:-L7eON5o9HwZeGsewz4t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/712962305ab608f6060909ab0fa917410facca4d/pkg/sql/distsql_physical_planner.go#L530)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit nit: i prefer "as of 03/2018"
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 561 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23834#-L7e3frRxIyj4R_k15ra:-L7eOOL7AEVrfTreo1Lf:b-oik6mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/712962305ab608f6060909ab0fa917410facca4d/pkg/sql/distsql_physical_planner.go#L561)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm not a fan of this comment. Better say on the field definition "can be nil for tests", and remove the panic from the ctor too.
</blockquote></details>

No, that increases the risk that production code passes a `nil` node liveness as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23834#-:-L7eOZD8qqfbIbh-DdQa:bjt9sb8)*

**Comment by andreimatei** [comment]
:lgtm: but why no roachtest? Still working on it?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23834#-:-L7eqjugVjvxOwAp4Y7M:b7hqhkt)*

**Comment by tschottdorf** [comment]
TFTR!

**Pull request merged**
