### PR TITLE
roachtest: add a variant of tpch_concurrency with no admission control

### PR DESCRIPTION
**Pull request by yuzefovich**
Informs: #74836.

Release note: None

### CODE REVIEW

**Review by michae2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75764)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75764#-MumdBLHDQnr9q67mk1d:-MumdBLHDQnr9q67mk1e:b-whemrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e3ea0631fddf6b9cf699024d7b1049f5897589/pkg/cmd/roachtest/tests/tpch_concurrency.go#L196)):*
> ```Go
> 
> 	for _, disableTxnStatsSampling := range []bool{false, true} {
> 		for _, disableAdmissionControl := range []bool{false, true} {
> ```

Do we need to multiply these configurations by each other? Does disabling both sampling and admission control at the same time tell us something different than disabling each individually?

What I'm getting at is: if these options are orthogonal to each other, then it seems like busywork to test all combinations of {on,off} for all options. Better to test each option disabled by itself, and then we can compare with the default configuration to know the effect of each option.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75764)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75764#-MumdBLHDQnr9q67mk1d:-Mumjl4A-irDBgIjYyVc:b-4m698r) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e3ea0631fddf6b9cf699024d7b1049f5897589/pkg/cmd/roachtest/tests/tpch_concurrency.go#L196)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Do we need to multiply these configurations by each other? Does disabling both sampling and admission control at the same time tell us something different than disabling each individually?

What I'm getting at is: if these options are orthogonal to each other, then it seems like busywork to test all combinations of {on,off} for all options. Better to test each option disabled by itself, and then we can compare with the default configuration to know the effect of each option.
</blockquote></details>

That's true; however, I do not intend to keep all these options around for long - at the moment I'm just curious in several more datapoints for the Streamer work, and I don't think these configs are that useful on their own. I'll probably remove `no_sampling` option entirely too since the performance dashboards seem to be about the same, so it's not providing much value either.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75764)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[pkg/cmd/roachtest/tests/tpch_concurrency.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75764#-MumdBLHDQnr9q67mk1d:-MumlUHZ8Ho8E1m5iWhO:bnyw1rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e3ea0631fddf6b9cf699024d7b1049f5897589/pkg/cmd/roachtest/tests/tpch_concurrency.go#L196)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

That's true; however, I do not intend to keep all these options around for long - at the moment I'm just curious in several more datapoints for the Streamer work, and I don't think these configs are that useful on their own. I'll probably remove `no_sampling` option entirely too since the performance dashboards seem to be about the same, so it's not providing much value either.
</blockquote></details>

Removed the case when both are disabled.

**Review by michae2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75764#-:-MummSGv670HeCDnqSZz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by msirek — APPROVED** [review]
+1

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75764#-:-Mun5Fhm2Dno_PTfXefq:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Pull request merged**
