### PR TITLE
grunning: improve some tests

### PR DESCRIPTION
**Pull request by irfansharif**
Release note: None
Release justification: test-only changes

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86185#-:-N9aoN993YDtp7Os2BFR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[`pkg/util/grunning/enabled_test.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86185#-N9ano-j1-xICmUEiZ7r:-N9ano-j1-xICmUEiZ7s:b6inhd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f68fc35711c564c535e4e6db7e7ef6a17fa7595/pkg/util/grunning/enabled_test.go#L143)):*
> ```Go
> 	defer runtime.GOMAXPROCS(runtime.GOMAXPROCS(1))
> 
> 	// Create a CPU hog.
> ```

Maybe something like the following?
// Create a CPU hog. It makes the two goroutines that want to cycle between running and waiting also have to wait in runnable state, until the CPU hog is finished with its time slice.
___
*[`pkg/util/grunning/enabled_test.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86185#-N9anHbN7X0kcInLgtWr:-N9anHbN7X0kcInLgtWs:b-faiuco) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f68fc35711c564c535e4e6db7e7ef6a17fa7595/pkg/util/grunning/enabled_test.go#L165)):*
> ```Go
> 		}
> 		pingern = grunning.Time().Nanoseconds()
> 		close(stop)
> ```

// Stop the CPU hog.
___
*[`pkg/util/grunning/enabled_test.go` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86185#-N9anPdQ5CjR3SsKYvWY:-N9anPdQ5CjR3SsKYvWZ:bxsqfax) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f68fc35711c564c535e4e6db7e7ef6a17fa7595/pkg/util/grunning/enabled_test.go#L176)):*
> ```Go
> 	}()
> 	ping <- true // start ping-pong
> 	<-stop       // wait for the pinger to finish
> ```

// wait until the pinger tells the CPU hog to finish

(the <-done are waiting for the pinger, ponger and CPU hog to actually finish, IIUC)

**Comment by irfansharif** [comment]
I don't really understand the "No pass/skip/fail event found for test" failure in the extended CI but I think it's optional. The Github CI + Bazel Essential CI pass so I'm just going to bors this.

bors r+

**Pull request merged**
