### PR TITLE
sql: fix the multidimensional array telemetry

### PR DESCRIPTION
**Pull request by knz**
This was largely incomplete.
Found via SQLAlchemy tests.

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35681#-:-L_rHsaXBQwSJxANIK4l:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @knz, and @mjibson)

___
*[pkg/sql/logictest/testdata/logic_test/array, line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35681#-L_rHO-J-kGccH6u7DqE:-L_rHO-J-kGccH6u7DqF:bt1x8jv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa998aa1c0035070fe93a1363810d375eb79116/pkg/sql/logictest/testdata/logic_test/array#L0)):*
We should move the wonky characters to their own file, them being in here makes reviewable think this is a binary file, and it refuses to show the diff.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35681#-:-L_rJau0CFyUNF6sskb1:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @mjibson)

___
*[pkg/sql/logictest/testdata/logic_test/array, line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35681#-L_rHO-J-kGccH6u7DqE:-L_rJ2XlBkQL1RsTNzDR:b1vvwkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa998aa1c0035070fe93a1363810d375eb79116/pkg/sql/logictest/testdata/logic_test/array#L)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

We should move the wonky characters to their own file, them being in here makes reviewable think this is a binary file, and it refuses to show the diff.
</blockquote></details>

Agreed, or change those characters altogether, I don't know what `\x10` is testing that's not tested already (e.g. by `\n`).

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35681)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @mjibson)

___
*[pkg/sql/logictest/testdata/logic_test/array, line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35681#-L_rHO-J-kGccH6u7DqE:-L_rSsMc9dENGuwrs6nZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa998aa1c0035070fe93a1363810d375eb79116/pkg/sql/logictest/testdata/logic_test/array#L)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Agreed, or change those characters altogether, I don't know what `\x10` is testing that's not tested already (e.g. by `\n`).
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYRs!

bors r+

**Pull request merged**
