### PR TITLE
opt: improve coster, constrain lookup join index scan

### PR DESCRIPTION
**Pull request by rytaft**
This commit has two elements:

1. Add an exploration rule to push a filter down into the
   index scan of a lookup join as a constraint. As part of this
   change, this commit fixes a small bug in optgen.

2. Improve the coster to use cost estimates for CPU, sequential
   I/O, and random I/O. Previously, the coster was using various
   numbers that were randomly chosen to make certain tests work
   as expected. This change preserves the behavior of those tests,
   but uses a more principled approach to costing.

Given both of these elements, we show that the coster correctly
chooses a constrained lookup join index scan when it makes sense.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:
Very nice, just a few small comments. Exciting to have a basic coster in place. I suspect this will do a pretty good job, as long as our row count estimates are decent. The more we improve those, the more we improve our costs.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/xform/coster.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBcLItq0C0CElkHSGdq:-LBcLItq0C0CElkHSGdr:b-mefi3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/911dfec1e7952c13643062054e202e6b24913f68/pkg/sql/opt/xform/coster.go#L126)):*
> ```Go
> 	// The filter has to be evaluated on each input row.
> 	inputRowCount := c.mem.BestExprLogical(candidate.Child(0)).Relational.Stats.RowCount
> 	cost := memo.Cost(inputRowCount) * cpuCost
> ```

If we're adding a cpucost for select, shouldn't we do so for groupby, set ops, etc? Why not just exclude linear costs for now, and only worry about NlogN, N**2, etc. costs? Or, if we want linear costs, maybe add TODO for other ops.

---

*[pkg/sql/opt/xform/coster.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBcMFh60XQnR_MoitSl:-LBcMBpK6fZIFbsFikug:b-thj6qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/911dfec1e7952c13643062054e202e6b24913f68/pkg/sql/opt/xform/coster.go#L137)):*
> ```Go
> 	leftRowCount := c.mem.BestExprLogical(candidate.Child(0)).Relational.Stats.RowCount
> 	rightRowCount := c.mem.BestExprLogical(candidate.Child(1)).Relational.Stats.RowCount
> 	cost := memo.Cost(leftRowCount+rightRowCount) * cpuCost
> ```

Maybe add comment that the joins are always implemented using a `HashJoin` physical operator, and why the cost function corresponds to that.

---

*[pkg/sql/opt/xform/rules/select.opt, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBcN5rpCOXVT-0vrxBM:-LBcN5rpCOXVT-0vrxBN:b9q927s) ([raw file](https://github.com/cockroachdb/cockroach/blob/911dfec1e7952c13643062054e202e6b24913f68/pkg/sql/opt/xform/rules/select.opt#L17)):*
> ```
> (ConstrainScan $filter $def)
> 
> [ConstrainLookupJoinIndexScan, Explore]
> ```

This rule needs a comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-:-LBcOQ380-J0NVP-c5TA:bsajvhp)*

**Comment by petermattis** [comment]
Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/coster.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBcjmZiBw-ZBi5gz8jA:-LBcjmZiBw-ZBi5gz8jB:be4tlfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/911dfec1e7952c13643062054e202e6b24913f68/pkg/sql/opt/xform/coster.go#L57)):*
> ```Go
> const (
> 	// These costs have been copied from the Postgres optimizer:
> 	// https://github.com/postgres/postgres/blob/master/src/include/optimizer/cost.h
> ```

Didn't we read a paper indicating that these constants are out of date.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300)*

**Comment by RaduBerinde** [comment]
Nice!

I think we need some more tests for the new rule (with various types of remaining filters)

---

Review status: 0 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/memo/testdata/memo, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfVl0Z8P9bXxSJaCUn:-LBfVl0Z8P9bXxSJaCUo:b-j4yajf) ([raw file](https://github.com/cockroachdb/cockroach/blob/911dfec1e7952c13643062054e202e6b24913f68/pkg/sql/opt/memo/testdata/memo#L31)):*
> ```
>  ├── stats: [rows=10]
>  ├── cost: 12062.34
>  ├── ordering: +2
> ```

Do we care about costs in these tests (under `memo`)? If not, would be better to hide them and avoid these diffs

---

*[pkg/sql/opt/xform/coster.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfSPiU7YhEnRDX7mey:-LBfSPiU7YhEnRDX7mez:b-kbp4ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/911dfec1e7952c13643062054e202e6b24913f68/pkg/sql/opt/xform/coster.go#L108)):*
> ```Go
> 	var cost memo.Cost
> 	if rowCount > 0 {
> 		cost = memo.Cost(rowCount*math.Log2(rowCount)) * cpuCost
> ```

I think `cpuCost` should be a function (`cpuCost(rowCount*math.Log2(rowCount))`). We can rename the factor to `cpuCostFactor`.

We could provide more complex wrappers too, for example, a functioin that takes a number of rows and returns the estimated cost of putting those rows in a disk container (which is a sum of cpu and I/O costs). That would be useful here, and for hash join.

---

*[pkg/sql/opt/xform/coster.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBcMFh60XQnR_MoitSl:-LBfTOV28vHKtq2JuEgo:b-twona4) ([raw file](https://github.com/cockroachdb/cockroach/blob/911dfec1e7952c13643062054e202e6b24913f68/pkg/sql/opt/xform/coster.go#L137)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Maybe add comment that the joins are always implemented using a `HashJoin` physical operator, and why the cost function corresponds to that.
</blockquote></details>

Maybe rename to `computeHashJoinCost`

---

*[pkg/sql/opt/xform/explorer.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfV2b2DkRZF3dvC7Xi:-LBfV2b2DkRZF3dvC7Xj:bnq84nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/911dfec1e7952c13643062054e202e6b24913f68/pkg/sql/opt/xform/explorer.go#L284)):*
> ```Go
> 
> // constrainedScanOpDef tries to push a filter into a scanOpDef as a
> // constraint.
> ```

Need to explain the `ok`

---

*[pkg/sql/opt/xform/explorer.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfU70H4epIayOC6D-P:-LBfU70H4epIayOC6D-Q:bvg3xq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/911dfec1e7952c13643062054e202e6b24913f68/pkg/sql/opt/xform/explorer.go#L375)):*
> ```Go
> //  - if the filter cannot be converted to constraints, does and returns
> //    nothing.
> //
> ```

Ideally we want to:
 - push constraints in the scan
 - put whatever part of the remaining filter that uses just index columns into a select above the index scan (and below the lookup join)
 - put what is left of the filter on top of the lookup join

Can be a TODO

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-:-LBfVUfI3bABbP6o1j_E:b-majp69)*

**Comment by rytaft** [comment]
Review status: 0 of 22 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/opt/memo/testdata/memo, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfVl0Z8P9bXxSJaCUn:-LBrWPxEB7lxghq4J614:bt7hx9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/memo/testdata/memo#L31)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we care about costs in these tests (under `memo`)? If not, would be better to hide them and avoid these diffs
</blockquote></details>

Seems like we probably don't need them - @andy-kimball, any opinion?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300)*

**Comment by andy-kimball** [comment]
Review status: 0 of 22 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/memo/testdata/memo, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfVl0Z8P9bXxSJaCUn:-LBsgNULCTIDU9INx1x8:b2rwppa) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/memo/testdata/memo#L31)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like we probably don't need them - @andy-kimball, any opinion?
</blockquote></details>

I think it'd be fine to exclude them.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300)*

**Comment by rytaft** [comment]
TFTRs! @RaduBerinde I agree we definitely needed more tests.  When adding the tests, I realized that we needed to add support for `LookupJoinOp` in the logical properties and stats code in order to handle the remaining filter case (the lookup join gets reconstructed in a new memo group). I've added another commit with these changes. PTAL.

---

Review status: 0 of 23 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/opt/memo/testdata/memo, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfVl0Z8P9bXxSJaCUn:-LBvpN8_5pcaEJ-0aFIC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/memo/testdata/memo#L31)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think it'd be fine to exclude them.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/coster.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBcjmZiBw-ZBi5gz8jA:-LBvtBbn2u9Y9B_VZ51G:b-ndpy4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/xform/coster.go#L57)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Didn't we read a paper indicating that these constants are out of date.
</blockquote></details>

"How Good are Query Optimizers, Really?" says that the PostgreSQL ratio between CPU and I/O is probably unrealistic in modern systems since much of the data can be cached in memory. In that paper, they updated the cost model for a main-memory database, and multiplied CPU by a factor of 50 -- making the CPU cost factor 0.5 instead of 0.01.  

Is this the paper you were thinking of?

Since CockroachDB is not a main-memory database, I think a CPU cost factor of 0.5 is probably a bit too aggressive. Although 0.01 is probably too far in the other direction. Perhaps we should run a few experiments on a representative cluster?

---

*[pkg/sql/opt/xform/coster.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfSPiU7YhEnRDX7mey:-LBvpRTBCgkXEMv3Gx7R:btq83fs) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/xform/coster.go#L108)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think `cpuCost` should be a function (`cpuCost(rowCount*math.Log2(rowCount))`). We can rename the factor to `cpuCostFactor`.

We could provide more complex wrappers too, for example, a functioin that takes a number of rows and returns the estimated cost of putting those rows in a disk container (which is a sum of cpu and I/O costs). That would be useful here, and for hash join.
</blockquote></details>

I renamed `cpuCost` to `cpuCostFactor`, but I don't see much benefit to creating a separate function - can you explain? We'd still need to cast to `memo.Cost` or `float64` in order for the function to work both here and below.

Not sure I understand the second suggestion -- based on my understanding, the current CockroachDB sort implementation is memory-based, not disk-based. The I/O cost comes from the children cost -- it would already be accounted for by the scan.  Is the hash join disk-based?

---

*[pkg/sql/opt/xform/coster.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBcLItq0C0CElkHSGdq:-LBvoUb2-Ir2GVjmITPh:b-rmuy6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/xform/coster.go#L126)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

If we're adding a cpucost for select, shouldn't we do so for groupby, set ops, etc? Why not just exclude linear costs for now, and only worry about NlogN, N**2, etc. costs? Or, if we want linear costs, maybe add TODO for other ops.
</blockquote></details>

Added a TODO above

---

*[pkg/sql/opt/xform/coster.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBcMFh60XQnR_MoitSl:-LBvoXR50Tn97VYx3y9w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/xform/coster.go#L137)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe rename to `computeHashJoinCost`
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/explorer.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfV2b2DkRZF3dvC7Xi:-LBvoZR35YHrizc3q0nV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/xform/explorer.go#L284)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Need to explain the `ok`
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/explorer.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfU70H4epIayOC6D-P:-LBvp174D5rxcc2HyzPr:bkd5ega) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/xform/explorer.go#L375)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ideally we want to:
 - push constraints in the scan
 - put whatever part of the remaining filter that uses just index columns into a select above the index scan (and below the lookup join)
 - put what is left of the filter on top of the lookup join

Can be a TODO
</blockquote></details>

Added a TODO

---

*[pkg/sql/opt/xform/rules/select.opt, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBcN5rpCOXVT-0vrxBM:-LBvpJAR8zZkfcrPBH-e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/xform/rules/select.opt#L17)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This rule needs a comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-:-LBvwxLnBAXxT512t2m7:b-jnptz7)*

**Comment by andy-kimball** [comment]
Reviewed 1 of 10 files at r3.
Review status: 1 of 23 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBwtVVV6Hogjp95AIy2:-LBwtVVV6Hogjp95AIy3:b1id491) ([raw file](https://github.com/cockroachdb/cockroach/blob/7758f43c24b8aa2c2534d919e2ef76357a8438c0/pkg/sql/opt/memo/logical_props_builder.go#L268)):*
> ```Go
> 	*props.Relational = *inputProps
> 
> 	md := ev.Metadata()
> ```

This code looks virtually identical to `buildScan`. It might make more sense to factor out part of it, maybe with a helper function like `func populatePropsFromTable(props *LogicalProps, tab opt.Table, cols opt.ColSet)`.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 286 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBwtEHE0zbLm0LccOF-:-LBwtEHE0zbLm0LccOF0:bd91eaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7758f43c24b8aa2c2534d919e2ef76357a8438c0/pkg/sql/opt/memo/logical_props_builder.go#L286)):*
> ```Go
> 
> 	// Add weak keys from the table schema.
> 	tableWeakKeys := md.TableWeakKeys(def.Table)
> ```

You should be able to assign `md.TableWeakKeys` directly to `props.Relational.WeakKeys`. The `filterWeakKeys` method takes care of copying it if necessary (with current code, you'd be triggering an extra unnecessary copy).

---

*[pkg/sql/opt/memo/statistics_builder.go, line 743 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBwvTBP3hNBaU-cMahM:-LBwvTBP3hNBaU-cMahN:b-y993pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7758f43c24b8aa2c2534d919e2ef76357a8438c0/pkg/sql/opt/memo/statistics_builder.go#L743)):*
> ```Go
> 	// Some of the requested columns may be from the input index.
> 	reqInputCols := colSet.Intersection(inputCols)
> 	if reqInputCols.Len() > 0 {
> ```

Better (here and below) is `!reqInputCols.Empty()`. The `Len` code is more complex, since it needs to count bits.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 767 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBwy-bn4TFYEdCbu-zV:-LBwwb2eBHRUiYuwLAwC:bqa3ls2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7758f43c24b8aa2c2534d919e2ef76357a8438c0/pkg/sql/opt/memo/statistics_builder.go#L767)):*
> ```Go
> 		)
> 
> 		colStat.DistinctCount *= joinedTableColStat.DistinctCount
> ```

Can you explain why multiplying the distinct counts is the right thing to do in this case, ideally in the form of a comment?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/xform/coster.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfSPiU7YhEnRDX7mey:-LBx1ZY141bQSpu3lDzK:b-ha639h) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/xform/coster.go#L108)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I renamed `cpuCost` to `cpuCostFactor`, but I don't see much benefit to creating a separate function - can you explain? We'd still need to cast to `memo.Cost` or `float64` in order for the function to work both here and below.

Not sure I understand the second suggestion -- based on my understanding, the current CockroachDB sort implementation is memory-based, not disk-based. The I/O cost comes from the children cost -- it would already be accounted for by the scan.  Is the hash join disk-based?
</blockquote></details>

The distsql sorter and hashjoiner use disk (a temp RocksDB store) once a certain amount of memory is used.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300)*

**Comment by rytaft** [comment]
Review status: 0 of 23 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBwtVVV6Hogjp95AIy2:-LBzyZelENmqvetkW090:b-6ddy3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7758f43c24b8aa2c2534d919e2ef76357a8438c0/pkg/sql/opt/memo/logical_props_builder.go#L268)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This code looks virtually identical to `buildScan`. It might make more sense to factor out part of it, maybe with a helper function like `func populatePropsFromTable(props *LogicalProps, tab opt.Table, cols opt.ColSet)`.
</blockquote></details>

I didn't want to get rid of the weak keys logic (see below), but I refactored the not-null cols logic.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 286 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBwtEHE0zbLm0LccOF-:-LBzyfKNAYwkGNlGzGE_:bx0vtru) ([raw file](https://github.com/cockroachdb/cockroach/blob/7758f43c24b8aa2c2534d919e2ef76357a8438c0/pkg/sql/opt/memo/logical_props_builder.go#L286)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

You should be able to assign `md.TableWeakKeys` directly to `props.Relational.WeakKeys`. The `filterWeakKeys` method takes care of copying it if necessary (with current code, you'd be triggering an extra unnecessary copy).
</blockquote></details>

I don't want to overwrite in case there are some weak keys from the input index (doesn't matter now, but it will once we start joining indexes from different tables). Added a comment to make this clearer.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 743 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBwvTBP3hNBaU-cMahM:-LBzyzYI8X4CznB-heYn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7758f43c24b8aa2c2534d919e2ef76357a8438c0/pkg/sql/opt/memo/statistics_builder.go#L743)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Better (here and below) is `!reqInputCols.Empty()`. The `Len` code is more complex, since it needs to count bits.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/statistics_builder.go, line 767 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBwy-bn4TFYEdCbu-zV:-LBzz-VqAmuqVAmmLZVI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7758f43c24b8aa2c2534d919e2ef76357a8438c0/pkg/sql/opt/memo/statistics_builder.go#L767)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can you explain why multiplying the distinct counts is the right thing to do in this case, ideally in the form of a comment?
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/coster.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBcjmZiBw-ZBi5gz8jA:-LBzz0qbBPyVoX_3m_k1:bddtif9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/xform/coster.go#L57)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

"How Good are Query Optimizers, Really?" says that the PostgreSQL ratio between CPU and I/O is probably unrealistic in modern systems since much of the data can be cached in memory. In that paper, they updated the cost model for a main-memory database, and multiplied CPU by a factor of 50 -- making the CPU cost factor 0.5 instead of 0.01.  

Is this the paper you were thinking of?

Since CockroachDB is not a main-memory database, I think a CPU cost factor of 0.5 is probably a bit too aggressive. Although 0.01 is probably too far in the other direction. Perhaps we should run a few experiments on a representative cluster?
</blockquote></details>

Added a TODO for now...

---

*[pkg/sql/opt/xform/coster.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LBfSPiU7YhEnRDX7mey:-LBzz3qEBGWHOjOCqfG-:byc1gcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9e23dfb2be10687e175a2efa7f9f9ed2570808/pkg/sql/opt/xform/coster.go#L108)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The distsql sorter and hashjoiner use disk (a temp RocksDB store) once a certain amount of memory is used.
</blockquote></details>

Ah ok cool. I added a TODO for now, since I think we should probably add a condition for the estimated amount of memory used. I guess we'll need to update the stats to include the average record size...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300)*

**Comment by rytaft** [comment]
bors r+

---

Review status: 0 of 23 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-:-LCAQ4_i9WBatSXMRWLQ:b-ydi9ay)*

**Comment by rytaft** [comment]
I had to make a number of changes for the rebase. I'd appreciate one more quick look, @RaduBerinde and @andy-kimball. Thanks!

---

Review status: 0 of 24 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-:-LCAwNC7CCdLMU-OxbPk:b-fzizru)*

**Comment by andy-kimball** [comment]
Review status: 0 of 24 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/opt/norm/rule_props_builder.go, line 140 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LCB-zP5AxuymtqtiulA:-LCB-zP5AxuymtqtiulB:b-59qqg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7cce8fb8fcd061d7a1631273f3e4458f822107e/pkg/sql/opt/norm/rule_props_builder.go#L140)):*
> ```Go
> 
> func (b *rulePropsBuilder) buildLookupJoinProps(ev memo.ExprView) {
> 	relational := ev.Logical().Relational
> ```

I don't think we'll ever be pruning columns projected by the LookupJoin, since it's parent will always be an "alternate" expression in the memo. Also, if you return a non-empty set to prune, then you'd need to add a rule to actually do the pruning (like a rule that passes through the pruned cols to the input).

At this point, `buildLookupJoinProps` should just be empty, with a comment explaining that its column will never need to be pruned.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/norm/rule_props_builder.go, line 140 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-LCB-zP5AxuymtqtiulA:-LCEVh6K9d5RyISngu_G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7cce8fb8fcd061d7a1631273f3e4458f822107e/pkg/sql/opt/norm/rule_props_builder.go#L140)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I don't think we'll ever be pruning columns projected by the LookupJoin, since it's parent will always be an "alternate" expression in the memo. Also, if you return a non-empty set to prune, then you'd need to add a rule to actually do the pruning (like a rule that passes through the pruned cols to the input).

At this point, `buildLookupJoinProps` should just be empty, with a comment explaining that its column will never need to be pruned.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300)*

**Comment by rytaft** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25300#-:-LCEojdo8p9NchzlMYOI:b-ydi9ay)*

**Pull request merged**
