### PR TITLE
opt: inverted-index accelerate queries with filters in the form `json_col ->'field' IN (...)`

### LINKED ISSUE #87856: opt: inverted-index accelerate queries with filters in the form json->'a' IN (...)
For a query like `SELECT * FROM t WHERE json_col->'field' IN ('"val1"', '"val2"')`, the optimizer should explore using an inverted index scan on an `INVERTED INDEX (json_col)`, if it one exists.

We should also handle filters like `json_col->0 IN (...)`.

Epic: CRDB-24501
Jira issue: CRDB-19574

### PR DESCRIPTION
**Pull request by Shivs11**
Previously, the optimizer did not plan inverted index scans for queries consisting of the IN operator.

To address this, we now build JSON arrays from fetch value expressions consisting of both integers and strings. Each entity present inside of the tuple following the IN operator has it's own seperate JSON array being created. From these JSON arrays, inverted spans are built. Each inverted span generated is `OR'ed` together to replicate the functionality of the `IN` operator. In other words, a filter of the form: `j->0 IN ('1', '2')` is thought of as `(j->0 = '1') OR (j->0 = '2')` and the generated inverted span replicates this behaviour.

Epic: CRDB-3301
Fixes: #87856

Release note (performance improvement): The optimizer now plans inverted index scans for queries that filter by JSON fetch value operators (->), consisting of both string and integer index values, alongside the IN operator, e.g, `json_col->0 IN ('1', '2')` and `json_col->'a' IN ('1', '2')`

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice work!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-:-NNJWx115m2t-w-0F0Ql:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @Shivs11)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJTg2m8u4RaLsafvcs):*
Not just JSON arrays, right? I'd just say JSON objects, since that is more general.
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJTp4qEOTaiS7l2hjz):*
nit: it's -> its
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJUYIA0qIsepMjUGIz:-NNJUYIA0qIsepMjUGJ-:b6h3ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc441a6aed7abbec4fe39dae5966041a68df459f/pkg/sql/opt/invertedidx/json_array.go#L396)):*
> ```Go
> 		}
> 	case *memo.InExpr:
> 		if fetch, ok := t.Left.(*memo.FetchValExpr); ok {
> ```

I think you should also check if `t.Right` has type `*memo.TupleExpr`. It's possible that it could be something else (e.g., a subquery) and the logic below would fail. (You should also add some tests for this)
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJV1a0-GFj4BSpHMGm:-NNJV1a0-GFj4BSpHMGn:befduo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc441a6aed7abbec4fe39dae5966041a68df459f/pkg/sql/opt/invertedidx/json_array.go#L434)):*
> ```Go
> 	tuple := right.Child(0)
> 	tupleLen := tuple.ChildCount()
> 	for index := 0; index < tupleLen; index++ {
> ```

nit: I'd just use `i` instead of `index`, since `index` is more verbose and doesn't improve clarity
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJVK6RCAUBJ_ffamaT:-NNJVK6RCAUBJ_ffamaU:bh7xfn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc441a6aed7abbec4fe39dae5966041a68df459f/pkg/sql/opt/invertedidx/json_array.go#L439)):*
> ```Go
> 		if invertedExpr == nil {
> 			invertedExpr = expr
> 		}
> ```

this should be an `else`
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJVQ4t7mhzdEMah7Dk:-NNJVQ4t7mhzdEMah7Dl:bk9n37q) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc441a6aed7abbec4fe39dae5966041a68df459f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1201)):*
> ```
> {"a": {"b": []}}
> 
> #Testing the IN operator
> ```

nit: add a space after #. Also, make this comment a bit more specific (e.g., "Tests for FetchVal with the IN operator)

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJTg2m8u4RaLsafvcs):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Not just JSON arrays, right? I'd just say JSON objects, since that is more general.
</blockquote></details>

Done!
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJTp4qEOTaiS7l2hjz):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: it's -> its
</blockquote></details>

Done!
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJUYIA0qIsepMjUGIz:-NNbbJvqDHyogelWst2P:b-8nou7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc441a6aed7abbec4fe39dae5966041a68df459f/pkg/sql/opt/invertedidx/json_array.go#L396)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you should also check if `t.Right` has type `*memo.TupleExpr`. It's possible that it could be something else (e.g., a subquery) and the logic below would fail. (You should also add some tests for this)
</blockquote></details>

Done! Thank you for spotting this. I now understand that such expressions, consisting of sub-queries, are mapped using the `ANY` operator instead of `IN`.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJV1a0-GFj4BSpHMGm:-NNb_7uG2WUxIagJuIor:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc441a6aed7abbec4fe39dae5966041a68df459f/pkg/sql/opt/invertedidx/json_array.go#L434)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: I'd just use `i` instead of `index`, since `index` is more verbose and doesn't improve clarity
</blockquote></details>

Done!
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJVK6RCAUBJ_ffamaT:-NNb_8rE7iDXjPXv345B:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc441a6aed7abbec4fe39dae5966041a68df459f/pkg/sql/opt/invertedidx/json_array.go#L439)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this should be an `else`
</blockquote></details>

Done!
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNJVQ4t7mhzdEMah7Dk:-NNb_AEX7RD4P9FY9tso:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc441a6aed7abbec4fe39dae5966041a68df459f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1201)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: add a space after #. Also, make this comment a bit more specific (e.g., "Tests for FetchVal with the IN operator)
</blockquote></details>

Done!

**Review by rytaft — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @Shivs11)

___
*[`pkg/sql/opt/invertedidx/json_array.go` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNdGgLMBnYQxGQY4g5N:-NNdGgLMBnYQxGQY4g5O:b-enc5kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/opt/invertedidx/json_array.go#L398)):*
> ```Go
> 		if fetch, ok := t.Left.(*memo.FetchValExpr); ok {
> 			if _, ok := t.Right.(*memo.TupleExpr); ok {
> 				invertedExpr = j.extractJSONInCondition(ctx, evalCtx, fetch, t.Right)
> ```

nit: you could change `extractJSONInCondition` to take a `TupleExpr` instead of a `ScalarExpr` to make it strongly typed. Then you could pass in the result of the type assertion above (i.e. replace the `_` with a variable), and inside `extractJSONInCondition`, you can directly iterate through the `Elems` of the `TupleExpr` instead of calling `Child` and `ChildCount`.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 444 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNcx-UO3LVO4mgMIxMB:-NNcx-UO3LVO4mgMIxMC:b3zm9zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/opt/invertedidx/json_array.go#L444)):*
> ```Go
> 			invertedExpr = inverted.Or(invertedExpr, expr)
> 		}
> ```

nit: remove extra blank line
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNcx4nr2ew65im2F51A:-NNcx4nr2ew65im2F51B:b-qorz7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1201)):*
> ```
> {"a": {"b": []}}
> 
> # Testing the FetchVAL with the IN operator
> ```

nit: end comments with a period.
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNdFYqQ-h6iiEE-IARU:-NNdFYqQ-h6iiEE-IARV:blv2tz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1201)):*
> ```
> {"a": {"b": []}}
> 
> # Testing the FetchVAL with the IN operator
> ```

You should also add a few similar tests in `sql/opt/exec/execbuilder/testdata/inverted_index` to show the query plans
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNdFI0h-55cQ1CfqiFN:-NNdFI0h-55cQ1CfqiFO:boax95n) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1277)):*
> ```
> ----
> [[0, 1, 2], {"b": "c"}]
> [[0, [1, 2]]]
> ```

can you also add some tests where some of the elements of the tuple are not constant?

e.g., `WHERE j->0 IN ('1', k::json)` or `WHERE j->0 IN (j->1, k::json)`

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/invertedidx/json_array.go` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNdGgLMBnYQxGQY4g5N:-NNgYPgc21jcESEm1SbL:byutye4) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/opt/invertedidx/json_array.go#L398)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: you could change `extractJSONInCondition` to take a `TupleExpr` instead of a `ScalarExpr` to make it strongly typed. Then you could pass in the result of the type assertion above (i.e. replace the `_` with a variable), and inside `extractJSONInCondition`, you can directly iterate through the `Elems` of the `TupleExpr` instead of calling `Child` and `ChildCount`.
</blockquote></details>

I was under the assumption we can't directly iterate through the `Elems` of the tuple since they are private members of the struct? And due to this fact, we can only use the implementations of the interface, such as `ChildCount` and `Child` to get the respective elements from the `Elems` right?

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/invertedidx/json_array.go` line 444 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNcx-UO3LVO4mgMIxMB:-NNgZMh24jHQifDMdX1A:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/opt/invertedidx/json_array.go#L444)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: remove extra blank line
</blockquote></details>

Done!
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNcx4nr2ew65im2F51A:-NNgZaAb7eHzfm22_IS4:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1201)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: end comments with a period.
</blockquote></details>

Done!
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNdFI0h-55cQ1CfqiFN:-NNgwNLl05iQkBcSncKR:b-upbfs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1277)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you also add some tests where some of the elements of the tuple are not constant?

e.g., `WHERE j->0 IN ('1', k::json)` or `WHERE j->0 IN (j->1, k::json)`
</blockquote></details>

I tried running these tests and noticed that they don't work since we we use the function `extractJSONFetchValEqCondition` as a helper to make an expression with `IN` look like multiple `OR` statements with `=`. Now, the function extractJSONFetchValEqCondition` seems to require a constant `JSON` value to the right of it thereby making the test to fail.

@mgartner also mentioned that it would be difficult, with the current approach, to index accelerate queries of this type.

**Review by rytaft — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @Shivs11)

___
*[`pkg/sql/opt/invertedidx/json_array.go` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNdGgLMBnYQxGQY4g5N:-NNhkCD_7TuPX6uRhOu2:bv8bdmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/opt/invertedidx/json_array.go#L398)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

I was under the assumption we can't directly iterate through the `Elems` of the tuple since they are private members of the struct? And due to this fact, we can only use the implementations of the interface, such as `ChildCount` and `Child` to get the respective elements from the `Elems` right?
</blockquote></details>

`Elems` is not private -- in go, capitalized data members are public. But to access it, the compiler needs to know that you have a `*TupleExpr` and not just a `ScalarExpr`. So I would change this block to look like this:
```
		if fetch, ok := t.Left.(*memo.FetchValExpr); ok {
			if tuple, ok := t.Right.(*memo.TupleExpr); ok {
				invertedExpr = j.extractJSONInCondition(ctx, evalCtx, fetch, tuple)
```
and `extractJSONInCondition` to look like this:
```
func (j *jsonOrArrayFilterPlanner) extractJSONInCondition(
	ctx context.Context, evalCtx *eval.Context, left *memo.FetchValExpr, right *memo.TupleExpr,
) inverted.Expression {
```
Then you'll be able to access `right.Elems`. Does this make sense?
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNdFI0h-55cQ1CfqiFN:-NNhl6e2-1bZ9V8ypilG:bfrlvii) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1277)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

I tried running these tests and noticed that they don't work since we we use the function `extractJSONFetchValEqCondition` as a helper to make an expression with `IN` look like multiple `OR` statements with `=`. Now, the function extractJSONFetchValEqCondition` seems to require a constant `JSON` value to the right of it thereby making the test to fail.

@mgartner also mentioned that it would be difficult, with the current approach, to index accelerate queries of this type.
</blockquote></details>

Right -- I don't mean that they should be index accelerated, but you should add the tests to still show that they return the correct results and don't err (and in execbuilder, that they use the correct plan).

Looks like you've added some tests already, which look good.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/inverted_index` line 1705 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNhlRZ2E3G-ybXKASJp:-NNhlRZ2E3G-ybXKASJq:bl7d7we) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7036fc14c2d7b2c457e6bc8b80341b4325a5d07/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L1705)):*
> ```
> # the fetch value's index position.
> query T
> EXPLAIN (VERBOSE) SELECT b FROM d WHERE b->'a' IN (b->0, '"a"')
> ```

nit: add a comment to explain why this is not index-accelerated
___
*[`pkg/sql/opt/invertedidx/json_array_test.go` line 1019 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNhlvstAaoZo_lXTYFD:-NNhlvsuDbU97hTSmcUq:b-deyil5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7036fc14c2d7b2c457e6bc8b80341b4325a5d07/pkg/sql/opt/invertedidx/json_array_test.go#L1019)):*
> ```Go
> 		},
> 		{
> 			filters:  `j->0 IN (j->0, j->1)`,
> ```

nit: add a comment to explain these test cases

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/invertedidx/json_array.go` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNdGgLMBnYQxGQY4g5N:-NNlbeno4H7DJnwZh6b-:b8bviwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/opt/invertedidx/json_array.go#L398)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

`Elems` is not private -- in go, capitalized data members are public. But to access it, the compiler needs to know that you have a `*TupleExpr` and not just a `ScalarExpr`. So I would change this block to look like this:
```
		if fetch, ok := t.Left.(*memo.FetchValExpr); ok {
			if tuple, ok := t.Right.(*memo.TupleExpr); ok {
				invertedExpr = j.extractJSONInCondition(ctx, evalCtx, fetch, tuple)
```
and `extractJSONInCondition` to look like this:
```
func (j *jsonOrArrayFilterPlanner) extractJSONInCondition(
	ctx context.Context, evalCtx *eval.Context, left *memo.FetchValExpr, right *memo.TupleExpr,
) inverted.Expression {
```
Then you'll be able to access `right.Elems`. Does this make sense?
</blockquote></details>

Oh I see, I was unaware of the fact that capitalized data members are public. I should have tried accessing it in the first place. Thank you for such a well documented tip, it makes a lot of sense.

I have made the changes!
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNdFYqQ-h6iiEE-IARU:-NNhIDU0EGVS36b4vc79:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1201)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You should also add a few similar tests in `sql/opt/exec/execbuilder/testdata/inverted_index` to show the query plans
</blockquote></details>

Done!
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNdFI0h-55cQ1CfqiFN:-NNlcqzx7K06APU_CRyB:bm4zn3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d04210a8cd9a5e00f0c6d529e970f16f3dcb3f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1277)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Right -- I don't mean that they should be index accelerated, but you should add the tests to still show that they return the correct results and don't err (and in execbuilder, that they use the correct plan).

Looks like you've added some tests already, which look good.
</blockquote></details>

Sorry for misunderstanding your previous comment, but yes the tests have been added!
___
*[`pkg/sql/opt/exec/execbuilder/testdata/inverted_index` line 1705 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNhlRZ2E3G-ybXKASJp:-NNldh8W3AQy6u7C9dCx:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7036fc14c2d7b2c457e6bc8b80341b4325a5d07/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L1705)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: add a comment to explain why this is not index-accelerated
</blockquote></details>

Done!
___
*[`pkg/sql/opt/invertedidx/json_array_test.go` line 1019 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNhlvstAaoZo_lXTYFD:-NNle3O7Evin12xjKIfq:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7036fc14c2d7b2c457e6bc8b80341b4325a5d07/pkg/sql/opt/invertedidx/json_array_test.go#L1019)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: add a comment to explain these test cases
</blockquote></details>

Done!

**Review by rytaft — APPROVED** [review]
:lgtm:, just one minor nit below

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-:-NNn16PE0ioTHQn4UKfv:bjeqhue)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @Shivs11)

___
*[`pkg/sql/opt/invertedidx/json_array.go` line 434 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNn0lhJ5aknS6j_-kxy:-NNn0lhJ5aknS6j_-kxz:b-gff734) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8ab5c2d902278172cc4bef6c92dac450026af3/pkg/sql/opt/invertedidx/json_array.go#L434)):*
> ```Go
> 	}
> 	var invertedExpr inverted.Expression
> 	for i := 0; i < len(right.Elems); i++ {
> ```

nit: can just do:
```
for i := range right.Elems {
```

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/invertedidx/json_array.go` line 434 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NNn0lhJ5aknS6j_-kxy:-NNsY_cj3c6gAJEyn2le:bs7wub4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8ab5c2d902278172cc4bef6c92dac450026af3/pkg/sql/opt/invertedidx/json_array.go#L434)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: can just do:
```
for i := range right.Elems {
```
</blockquote></details>

Done!

**Review by mgartner — APPROVED** [review]
:lgtm: Nicely done!

Looks like the linter is failing your build:

```
pkg/sql/opt/invertedidx/json_array.go:435:21: type assertion to the same type: right.Elems[i] already has type opt.ScalarExpr (S1040)
```

> Reviewed 1 of 5 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-:-NOAdYko52jmXuJ5TntL:b-qbspyn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Shivs11)

___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NOAcOJf7M0jwpT_FaPA):*
nit: wrap commit message bodies at 72 characters.
___
*[`-- commits` line 22 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-NOAcZmo1dMq3DnGnOr_):*
nit: missing period at the end of the sentence

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Shivs11)

**Review by Shivs11 — COMMENTED** [review]
Fixed the nits below too @mgartner !

Thank you once again for the reviews and the guidance on this! @mgartner @rytaft 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96471#-:-NOGOKLV6rdefsVHos6X:b-yojf81)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

**Pull request merged**
