### PR TITLE
roachtest: fix liquibase roachtest

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note: None

### CODE REVIEW

**Review by otan — APPROVED** [review]

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67575)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/cmd/roachtest/tests/liquibase.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67575#-MeX-wox7YqpDxahH9n9:-MeX-wox7YqpDxahH9nA:b-q0obx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8460ed9553d7a64f20d1bf05b9aadce46370325e/pkg/cmd/roachtest/tests/liquibase.go#L98)):*
> ```Go
> 		// to be run.
> 		if err = c.RunE(ctx, node,
> 			`cd /mnt/data1/liquibase-test-harness/ && mvn test -Dtest=LiquibaseHarnessSuiteTest -DdbName=cockroachdb -DdbVersion=20.2`,
> ```

should dbVersion be 21.1 now? hmm idk, maybe better to do separately?

**Comment by RichardJCai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67575)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)
> 
> _[pkg/cmd/roachtest/tests/liquibase.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67575#-MeX-wox7YqpDxahH9n9:-MeX-wox7YqpDxahH9nA:b-q0obx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8460ed9553d7a64f20d1bf05b9aadce46370325e/pkg/cmd/roachtest/tests/liquibase.go#L98)):_
> 
> > ```go
> > 		// to be run.
> > 		if err = c.RunE(ctx, node,
> > 			`cd /mnt/data1/liquibase-test-harness/ && mvn test -Dtest=LiquibaseHarnessSuiteTest -DdbName=cockroachdb -DdbVersion=20.2`,
> > ```
> 
> should dbVersion be 21.1 now? hmm idk, maybe better to do separately?

Yeah let's do this separately, I think the liquibase team still runs their CI against 20.2.

**Comment by RichardJCai** [comment]
bors r=otan

**Comment by otan** [comment]
bors r-

lint failure

**Comment by RichardJCai** [comment]
fixed, thanks
bors r=otan

**Pull request merged**
