### PR TITLE
Make Gossip.GetNodeDescriptor use a cache of node descriptors.

### PR DESCRIPTION
**Pull request by petermattis**
The perf benefits were more modest than I was led to believe by
profiles, but then the change was also simpler. Only showing the scan
benchmarks as the others were showing similarly small benefits.

```
name                   old time/op    new time/op    delta
Scan1_Cockroach-8         183µs ± 1%     181µs ± 1%  -0.84%  (p=0.001 n=10+10)
Scan10_Cockroach-8        222µs ± 1%     220µs ± 0%  -1.02%    (p=0.000 n=9+9)
Scan100_Cockroach-8       597µs ± 3%     599µs ± 3%    ~     (p=0.631 n=10+10)

name                   old allocs/op  new allocs/op  delta
Scan1_Cockroach-8           292 ± 0%       285 ± 0%  -2.53%   (p=0.000 n=10+8)
Scan10_Cockroach-8          382 ± 0%       375 ± 0%  -1.88%  (p=0.000 n=10+10)
Scan100_Cockroach-8       1.12k ± 0%     1.11k ± 0%  -0.64%   (p=0.000 n=9+10)
```

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4169)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip.go, line 481 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-K9nRkOdmbBYJwdJsJNe:-K9nRkOdmbBYJwdJsJNf:-1705057262) ([raw file](https://github.com/cockroachdb/cockroach/blob/59f19cdce6778f69e18e21c5b2dad3f5f78d5d4d/gossip/gossip.go#L481)):*
inline this into the `if`

---

*[kv/dist_sender_test.go, line 166 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-K9nR9K8uPr3u2CevKyl:-K9nR9K8uPr3u2CevKym:1880806304) ([raw file](https://github.com/cockroachdb/cockroach/blob/59f19cdce6778f69e18e21c5b2dad3f5f78d5d4d/kv/dist_sender_test.go#L166)):*
`expAddrs` should be a `[]roachpb.NodeID`. there will be more fallout from that, though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip.go, line 481 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-K9nRkOdmbBYJwdJsJNe:-K9nU28Nh5ec5w3xERh8:825847708) ([raw file](https://github.com/cockroachdb/cockroach/blob/59f19cdce6778f69e18e21c5b2dad3f5f78d5d4d/gossip/gossip.go#L481)):*
Yep. This moved a bit during development before finally ending on this very simple addition. Fixed.

---

*[kv/dist_sender_test.go, line 166 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-K9nR9K8uPr3u2CevKyl:-K9nUeu4JYU9pvT3m8C1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/59f19cdce6778f69e18e21c5b2dad3f5f78d5d4d/kv/dist_sender_test.go#L166)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip.go, line 443 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-K9nUdSDzEHEXsRE5i5H:-K9nUdSDzEHEXsRE5i5I:-2057236181) ([raw file](https://github.com/cockroachdb/cockroach/blob/59f19cdce6778f69e18e21c5b2dad3f5f78d5d4d/gossip/gossip.go#L443)):*
This method of checking whether the entry existed is more performant then the other more traditional one you are replacing?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip.go, line 443 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-K9nUdSDzEHEXsRE5i5H:-K9nV2SR8qK3oadJQFGU:-1746893443) ([raw file](https://github.com/cockroachdb/cockroach/blob/59f19cdce6778f69e18e21c5b2dad3f5f78d5d4d/gossip/gossip.go#L443)):*
No. But with this new code I'm always updating `g.nodeDescs` so since I'm doing so I can check to see whether `g.nodeDescs` grew to know if a new node was seen.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169)*

**Comment by tamird** [comment]
LGTM

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-:-K9nW-haNfNYwLBJJJHM:676834233)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip.go, line 450 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-K9nW5oWB5pEKItFT1Xz:-K9nW5oWB5pEKItFT1Y-:-942219525) ([raw file](https://github.com/cockroachdb/cockroach/blob/4501d265a8877b4f0184d3c04cbdb904824aee46/gossip/gossip.go#L450)):*
nit: you could extract this local `len(g.nodeDescs)`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip.go, line 450 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-K9nW5oWB5pEKItFT1Xz:-K9nWmocWDlddjC0Iidi:-1555740751) ([raw file](https://github.com/cockroachdb/cockroach/blob/4501d265a8877b4f0184d3c04cbdb904824aee46/gossip/gossip.go#L450)):*
For what purpose? `len(g.nodeDescs)` should be read as `g.nodeDescs.Length`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip.go, line 450 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-K9nW5oWB5pEKItFT1Xz:-K9nX7M_sxf2mzYnw9zM:1377578740) ([raw file](https://github.com/cockroachdb/cockroach/blob/4501d265a8877b4f0184d3c04cbdb904824aee46/gossip/gossip.go#L450)):*
I find that style easier to read, since it draws attention to the other places a common variable is referenced.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169)*

**Comment by tschottdorf** [comment]
LGTM, with ever so slight OCD that there's nothing that ever gets these things out of the cache..

**Comment by petermattis** [comment]
@tschottdorf The lack of eviction would bother me more if large growth were expected, but this table is limited by `O(num-nodes)` in the lifetime of the cluster. Am I missing some other concern about the size this cache can grow to?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip.go, line 450 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-K9nW5oWB5pEKItFT1Xz:-K9nnKE0HCA71J_YZaED:2063909274) ([raw file](https://github.com/cockroachdb/cockroach/blob/4501d265a8877b4f0184d3c04cbdb904824aee46/gossip/gossip.go#L450)):*
We'll have to agree to disagree about that. We certainly are not following that style consistently in the code base. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4169#-:-K9nnYYC5Xr6ZOemEPQ_:-956787965)*

**Pull request merged**
