### PR TITLE
kvstreamer: fix pathological behavior in InOrder mode

### LINKED ISSUE #133043: kvstreamer: super-linear increase in latency and number of gPRC calls in InOrder mode
See the reproduction here: https://gist.github.com/mgartner/6163ac9079c64ca0d46592ff85f115ce

This reproduction runs 3 queries, index-joining ~10k, ~20k, and ~30k rows each. The latency and number of gRPC calls for each index-join grows super-linearly.

image

This seems related to #113729. That issue was addressed by #113809, however, I could not improve the performance of this new reproduction with any setting of `streamer_in_order_eager_memory_usage_fraction` - I tried as low as `0.05` and as high as `0.95`.

I believe the code/comment here may be relevant: https://github.com/cockroachdb/cockroach/blob/c83c57d354741ac36740894f7387c014eb6c09fe/pkg/kv/kvclient/kvstreamer/streamer.go#L1106-L1127

Jira issue: CRDB-43434

### PR DESCRIPTION
**Pull request by yuzefovich**
**kvstreamer: fix TestStreamerVaryingResponseSizes**

Previously the test was fooling itself - the regex for `KV gRPC calls` line was incorrect, so it was never matched, and we ended up with unset counter (which happened to pass the test); this is now fixed.

Release note: None

**kvstreamer: fix pathological behavior in InOrder mode**

This commit fixes the case of pathological behavior by the streamer in the InOrder mode in some cases. Namely, when ordering needs to be maintained, the streamer needs to prioritize sub-requests that have higher "urgency" to be served (i.e. those that are closer to the head of the line). This "urgency" is represented by the values in `singleRangeBatch.positions` slice where the smaller the value, the higher the urgency, and the value at the zeroth index is used as the priority for the whole single-range batch. It is assumed that the values in this slice are increasing, but this assumption could previously be violated when multiple ranges were touched (when the original batch fit within a single range, we have a separate fast-path that is unaffected by this bug). This was the case because we used `mustPreserveOrder = false` when instantiating the batch truncation helper. As a result, all sub-requests within the single-range batch would get reordered according to the start key of each request, and the original order wouldn't be restored by the batch truncation helper. This, in turn, would result in the streamer evaluating the requests with effectively random urgency which would then consume the working budget. In the extreme, we would use up all available budget for random requests, buffer them, and would keep on doing so until we get lucky to get the next head-of-the-line request randomly. This is now fixed by restoring the order of `positions` by the truncation helper when the streamer is in the InOrder mode. This commit also adds a test-only assertion for ensuring the ascending invariant is maintained.

Here is a concrete example of the behavior. Say, we have two ranges [a - f) and [f - ...) and requests
- 0: Get(c)
- 1: Get(e)
- 2: Get(d)
- 3: Get(f)
- 4: Get(a)
- 5: Get(b)

The batch truncation helper will first order all requests by the start key, so it'll process them in the order 4 - 5 - 0 - 2 - 1 - 3. When truncating to the first range [a - f), it'll populate `positions` as `[4, 5, 0, 2, 1]` (request 3 is outside of the range, so it'll stop). This slice is what we would previously include into `singleRangeBatch.positions`, so we would first evaluate the 4th request, then the 5th, etc. Previously, we would also incorrectly compare `singleRangeBatch`es between each other for "in order" priority.

AFAICT this bug has been present since the introduction of the batch truncation helper in https://github.com/cockroachdb/cockroach/commit/645c1543e231668d7ea048b9d6b1692c5124f835. The assumption of the InOrder mode was already there, in the comment, but wasn't enforced and was overlooked.

Fixes: #133043.

Release note (bug fix): Previously, when executing queries with index / lookup joins when the ordering needs to be maintained, CockroachDB in some cases could get into a pathological behavior which would lead to increased query latency, possibly by several orders of magnitude. This bug was introduced in 22.2 and is now fixed.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice job finding this!

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134132#-:-OAtToUE-vvRqiuMjThL:b-xqam7f)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
bors retry

**Review by mgartner — COMMENTED** [review]
Thanks for tracking this one down!

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134132#-:-OB0oTkp-dyD76j-u3AC:bwm9sqr)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1379 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134132#-OB0oBvk8qFstiQ8H5i7:-OB0oBvk8qFstiQ8H5i8:bx2rvam) ([raw file](https://github.com/cockroachdb/cockroach/blob/05879b8efca0e6fd961086697252c26eb5f23d9d/pkg/kv/kvclient/kvstreamer/streamer.go#L1379)):*
> ```Go
> 					for i := range req.positions[:len(req.positions)-1] {
> 						if req.positions[i] >= req.positions[i+1] {
> 							w.s.results.setError(errors.AssertionFailedf(
> ```

Great idea to add this assertion!

**Pull request merged**
