### PR TITLE
all: fix various badness when resuscitating a node

### PR DESCRIPTION
**Pull request by petermattis**
Prior to this PR, `zerosum` would experience a significant hiccup when
restarting a node:

```
chaos: starting node 1
     35s      9425       26203    789.3       15        0        0        6              2 6 5 5
     36s      9430       26319    115.4       42        0        0        6              2 6 5 5
     37s      9430       26319      0.0       42        0        0        6              2 6 5 5
     38s      9430       26319      0.0       42        0        0        6              2 6 5 5
     39s      9430       26319      0.0       43        0        0       -1              0 0 0 0
     40s      9430       26319      0.0       43        0        0        6              2 6 5 5
     41s      9430       26319      0.0       43        0        0        6              2 6 5 5
     42s      9430       26319      0.0       43        0        0        6              2 6 5 5
     43s      9430       26319      0.0       43        0        0        6              2 6 5 5
     44s      9430       26319      0.0       43        0        0        6              2 6 5 5
     45s      9444       26528    208.7       43        0        0        6              2 6 5 5
     46s      9480       27312    783.9       43        0        0        6              2 6 5 5
```

And now:

```
chaos: starting node 1
     35s      9399       24615    873.5        6        0        0        6              4 5 5 4
     36s      9399       24663     47.8        6        0        0        6              4 5 5 4
     37s      9399       24663      0.0        6        0        0        6              4 5 5 4
     38s      9425       25124    460.9        7        0        0       -1              0 0 0 0
     39s      9463       25890    765.9        7        0        0        6              4 5 5 4
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8163)

### CODE REVIEW

**Comment by tamird** [comment]
I don't understand what the first commit is doing.

In the third commit: s/following/fouling/

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[cmd/zerosum/cluster.go, line 182 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-KO2DXpBgXqbYPTBHEe5:-KO2DXpBgXqbYPTBHEe6:-1007799884) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f69bd7bfc76c2a389942f442c32d7657b8941a1/cmd/zerosum/cluster.go#L182)):*
> ```Go
> 	if err != nil {
> 		if log.V(1) {
> 			log.Infof(context.Background(), "scan failed: %s", err)
> ```

this looks unrelated, and i can't tell why it's being changed from the commit message

---

*[kv/dist_sender.go, line 205 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-KO2C_QjALH9PpAO3nzF:-KO2C_QktWSGiMi_byUS:151235307) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cb5bac77c263b5c1fd063ba580659aea349b02f/kv/dist_sender.go#L205)):*
> ```Go
> 					var desc roachpb.RangeDescriptor
> 					if err := value.GetProto(&desc); err != nil {
> 						log.Errorf(context.Background(),
> ```

extract a local context?

also, this needs a test. ah, i see you filed an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-:-KO2CJAMU_2fU1qlTEUj:-986722)*

**Comment by petermattis** [comment]
The first commit is fixing a silliness Spencer introduced in `RaftSender.SendAsync` where it was retrieving a gRPC connection on every call instead of only when a queue is being created.

---

Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[cmd/zerosum/cluster.go, line 182 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-KO2DXpBgXqbYPTBHEe5:-KO2EGwkqxCjxvuHczjW:989299200) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f69bd7bfc76c2a389942f442c32d7657b8941a1/cmd/zerosum/cluster.go#L182)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this looks unrelated, and i can't tell why it's being changed from the commit message
</details>
`internal/client` operations now fail-fast instead of retrying until they hit a deadline. 

---

*[kv/dist_sender.go, line 205 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-KO2C_QjALH9PpAO3nzF:-KO2EuoK0W2maqo9b3av:2018048283) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cb5bac77c263b5c1fd063ba580659aea349b02f/kv/dist_sender.go#L205)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> extract a local context?
> 
> also, this needs a test. ah, i see you filed an issue.
</details>
Sure on the local context. 

I tried valiantly to test this, but the test infrastructure in `dist_sender_test.go` beat me down.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-:-KO2F-uMeM4-pt1FUPrF:1960594572)*

**Comment by tamird** [comment]
Right, but why does that matter?

---

Reviewed 4 of 4 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-:-KO2FUQoL6qymO2IuSkM:-2130127286)*

**Comment by petermattis** [comment]
It doesn't matter for correctness, just something I noticed. Why should we retrieve the connection when the active queue already has the connection? When the connection closes the associated streams will be closed closing the queue and the next time `RaftSender.SendAsync` is called we'll re-open the connection.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-:-KO2GRUkYVFNNg3z8XMC:1713910447)*

**Comment by tamird** [comment]
Ah, I see. Could you expand the comment?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-:-KO2GzVUqe3qfxByxusX:1815200487)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-:-KO2I9KxVsaGMQPMl6BC:1417088721)*

**Comment by petermattis** [comment]
Expanded the first commit message. I also reverted the usage of fail-fast by `client.sender`. The acceptance tests are currently relying on `fail-fast=false`. 

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-:-KO2ZVBiDNWg5ySWoWgE:1734505224)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 5 of 5 files at r6, 2 of 2 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8163#-:-KO2c-1iA-tB2rqOrFes:1417088721)*

**Pull request merged**
