### PR TITLE
grpcutil: fix broken debouncing logic

### PR DESCRIPTION
**Pull request by tamird**
Avoid `defer` and anonymous function and just lock multiple times.
This is safe because each key is only ever used by one goroutine.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/grpcutil/log.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348#-KibGUxhJk3z9wQzYV83:-KibGUxiAtFTXpeYlmqs:b1hf6fy) ([raw file](https://github.com/cockroachdb/cockroach/blob/94bb67af9b93d52d380ee666b8cf32c3eb3ccfc8/pkg/util/grpcutil/log.go#L95)):*
> ```Go
> 					spamMu.gids[gid] = timeutil.Now()
> 					spamMu.Unlock()
> 					break
> ```

The double-locking seems weird. I think this would be simpler if this method returned `true` or `false` and the caller invoked `log.InfofDepth`, but this should work. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348#-:-KibHPHpdFwWQV8_qFJV:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/grpcutil/log.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348#-KibGUxhJk3z9wQzYV83:-KibHxyzLcbuFXVB2YRg:bkrjypu) ([raw file](https://github.com/cockroachdb/cockroach/blob/94bb67af9b93d52d380ee666b8cf32c3eb3ccfc8/pkg/util/grpcutil/log.go#L95)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The double-locking seems weird. I think this would be simpler if this method returned `true` or `false` and the caller invoked `log.InfofDepth`, but this should work. 
</blockquote></details>

Yeah, it's weird, but safe as explained in the commit message.

Extracted out a call to `Now()` to reduce the number of time calls by one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/grpcutil/log.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348#-KibGUxhJk3z9wQzYV83:-KieBg-b6bOMW7TNUKaF:b-jml4l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/94bb67af9b93d52d380ee666b8cf32c3eb3ccfc8/pkg/util/grpcutil/log.go#L95)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Yeah, it's weird, but safe as explained in the commit message.

Extracted out a call to `Now()` to reduce the number of time calls by one.
</blockquote></details>

If you restructured as I'm suggesting you could more easily add a test without having to capture the output of `log.InfofDepth`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/grpcutil/log.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348#-KibGUxhJk3z9wQzYV83:-KieajRy9mLCaWulrDYJ:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/94bb67af9b93d52d380ee666b8cf32c3eb3ccfc8/pkg/util/grpcutil/log.go#L95)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If you restructured as I'm suggesting you could more easily add a test without having to capture the output of `log.InfofDepth`. 
</blockquote></details>

Good point, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348)*

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/util/grpcutil/log.go, line 103 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348#-Kievaeh-7DYnX7xFBDY:-Kievaeh-7DYnX7xFBDZ:biivsp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/783182f2daf9036c5d42e274d9def454f050ccb8/pkg/util/grpcutil/log.go#L103)):*
> ```Go
> 					spamMu.Lock()
> 					t, ok := spamMu.gids[gid]
> 					doPrint := !(ok && now.Sub(t) < freq)
> ```

No need for the `ok` because if `!ok` then `t == time.Time{}`: `doPrint := now.Sub(t) >= freq`

---

*[pkg/util/grpcutil/log_test.go, line 25 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348#-KievqWv9duPCAWdG5Ro:-KievqWwXydIQA-94J0l:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/783182f2daf9036c5d42e274d9def454f050ccb8/pkg/util/grpcutil/log_test.go#L25)):*
> ```Go
> )
> 
> func TestShouldPrint(t *testing.T) {
> ```

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348)*

**Comment by tamird** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/util/grpcutil/log.go, line 103 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348#-Kievaeh-7DYnX7xFBDY:-KiewIlykSAF_rhWXt7W:b-pwiltu) ([raw file](https://github.com/cockroachdb/cockroach/blob/783182f2daf9036c5d42e274d9def454f050ccb8/pkg/util/grpcutil/log.go#L103)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

No need for the `ok` because if `!ok` then `t == time.Time{}`: `doPrint := now.Sub(t) >= freq`
</blockquote></details>

Heh, I still like being explicit here, if it's the same to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15348)*

**Pull request merged**
