### PR TITLE
colexec: add memory accounting logic to Allocator

### LINKED ISSUE #38412: exec: add memory accounting to BatchAllocator
When callers request or append to batches from `BatchAllocator`, the allocator should measure the size of the new data and draw down from its memory budget.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: add AppendColumn method to Allocator**

This commit adds AppendColumn method to Allocator and prohibits usage of
coldata.Batch.AppendCol within sql/colexec and sql/colflow packages.
coldata.Batch interface has been slightly adjusted so that AppendCol
takes in a given coldata.Vec (already allocated by the caller) instead
of taking in a coltype and allocating it on the fly.

Release note: None

**colexec: add memory accounting logic to Allocator**

This commit adds the memory accounting logic to Allocator using
mon.BoundAccount. All allocations related to coldata.Batches and
coldata.Vecs will be accounted for through the Allocator.

Also, StaticMemoryOperator interface has been modified so that it
reflects only the "static memory" which is defined as the internal
memory of an Operator not related to coldata. Currently only bufferOp,
caseOp, and merge join Operators implement this interface.

Addresses: #38412.

Release note: None

**colexec: use separate memory accounts for buffering components**

This commits adds the separate memory monitors and memory accounts for
all buffering vectorized components (hash router, hash aggregator, hash
joiner, merge joiner when non-streaming, sorter, sort chunks, and sorts
needed for window functions). Each monitor is started using 'workmem'
limit and is dedicated to a particular component with a single memory
account bound to the monitor. These monitors and accounts are
accumulated into the FlowCtx and are closed on FlowBase.Cleanup().

Fixes: #38412.

Release note (sql change): Previously, all buffering operators (like
hash and merge joins, sorts) when executed via the vectorized engine
could use arbitrary amounts of memory which could lead to OOM panics.
Now the memory accounting has been added, and each buffering operator
will use at most 'sql.distsql.temp_storage.workmem' memory (which is
64MB by default).

### CODE REVIEW

**Comment by yuzefovich** [comment]
I've just pushed a second commit which removes the static memory estimation, but I'm not sure whether we actually want to do that. On one hand, it would be nice if this memory estimation was only performed by the `Allocator`, but on the other hand, `Allocator` should not burden itself with details of some operators (like an extra selection vector). Thoughts?

**Comment by yuzefovich** [comment]
I think it is RFAL.

In regards to the question I asked about static memory: I think we need to redefine what "static memory" means here. I now think of it as all internal things (like separate selection vectors or a circular buffer) that an Operator needs which are unrelated to `coldata`. An Operator should know exactly how much of "static memory" it will use upon its creation. All memory that is related to `coldata` will be tracked via the `Allocator` and will not be included into this "static" memory.

**Comment by yuzefovich** [comment]
Running TPCH queries locally on a single node cluster with the default `workmem` setting I see several "memory budget exceeded" errors:
```
E191115 23:31:50.944114 1 workload/cli/run.go:444  [q1]: pq: hash-aggregator-limited: memory budget exceeded: 460800 bytes requested, 63897600 currently allocated, 64000000 bytes in budget
E191115 23:31:52.000811 1 workload/cli/run.go:444  [q3]: pq: hash-joiner-limited: memory budget exceeded: 716800 bytes requested, 63385600 currently allocated, 64000000 bytes in budget
E191115 23:32:16.585633 1 workload/cli/run.go:444  [q8]: pq: hash-joiner-limited: memory budget exceeded: 10240 bytes requested, 64000000 currently allocated, 64000000 bytes in budget
E191115 23:32:38.012302 1 workload/cli/run.go:444  [q9]: pq: hash-joiner-limited: memory budget exceeded: 10240 bytes requested, 64000000 currently allocated, 64000000 bytes in budget
E191115 23:32:51.286986 1 workload/cli/run.go:444  [q19]: pq: hash-joiner-limited: memory budget exceeded: 3901440 bytes requested, 62545920 currently allocated, 64000000 bytes in budget
```

**Review by asubiotto — CHANGES_REQUESTED** [review]
There is also extra variable memory that isn't related to `coldata` (e.g. internal hash table slices) that we'll probably also want to somehow account for. One option there is to actually convert these to be `coldata`.

> Reviewed 26 of 26 files at r1, 57 of 57 files at r2, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-:-Lu-KwTqE0zF8P-ME0A9:bv5l7c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/allocator.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-AjnH85rGUjzKJErx:-Lu-AjnH85rGUjzKJEry:b-7qm6s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colexec/allocator.go#L86)):*
> ```Go
> 	var delta int64
> 	if dest.Type() == coltypes.Bytes {
> 		destBytes, srcBytes := dest.Bytes(), args.Src.Bytes()
> ```

Can we delegate getting the number of bytes to the `Bytes` implementation? Then it would be easier to calculate the delta as:
```
before := dest.SizeBytes()
dest.Append(args)
after := dest.SizeBytes()
delta := after - before
```
For other types, we could do the same as above but passing in `dest.Length()` to `estimateBatchSizeBytes`?
___
*[pkg/sql/colexec/allocator.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-Bo3s1Iif3-C5QD4_:-Lu-Bo3s1Iif3-C5QD4a:b-p8wwoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colexec/allocator.go#L107)):*
> ```Go
> }
> 
> // TODO(yuzefovich): Vec.Copy and execgen.SET need to also go through the
> ```

I think we need to carefully think of this `SET` case to not introduce unnecessary overhead. There actually don't seem to be too many uses of `execgen.SET`:
```
pkg/col/coldata/vec_tmpl.go
101:				execgen.SET(toCol, int(selIdx), v)
103:				execgen.SET(toCol, i+int(args.DestIdx), v)
114:		execgen.SET(toCol, int(selIdx), v)
116:		execgen.SET(toCol, i+int(args.DestIdx), v)
205:		execgen.SET(target, int(rowIdx), newVal)

pkg/sql/colexec/execgen/cmd/execgen/data_manipulation_gen.go
38:		templatePlaceholder: "execgen.SET",

pkg/sql/colexec/execgen/cmd/execgen/cast_gen.go
44:	// replace the _TO_TYPE_SET's with execgen.SET's of the correct type
45:	s = strings.Replace(s, "_TO_TYPE_SET", "execgen.SET", -1)

pkg/sql/colexec/const_tmpl.go
103:			execgen.SET(col, int(i), c.constVal)
108:			execgen.SET(col, i, c.constVal)

pkg/sql/colexec/min_max_agg_tmpl.go
152:		execgen.SET(a.vec, a.curIdx, a.curAgg)
209:			execgen.SET(a.vec, a.curIdx, a.curAgg)

pkg/sql/colexec/cast_tmpl.go
59:// This will be replaced with execgen.SET.

pkg/sql/colexec/vec_comparators_tmpl.go
125:		execgen.SET(c.vecs[dstVecIdx], int(dstIdx), v)

pkg/sql/colexec/mergejoiner_tmpl.go
681:							execgen.SET(outCol, outStartIdx, val)
814:						// TODO(yuzefovich): think about making execgen.SET set both the
823:						execgen.SET(outCol, outStartIdx, v)
831:						execgen.SET(outCol, outStartIdx, v)

pkg/sql/colexec/rowstovec_tmpl.go
74:			execgen.SET(col, i, castV)
```

I wonder if we could introduce deferred accounting in this case? i.e. "If you use `SET`, you *must* call `allocator.UpdateAccount`" or something like that, which would just recalculate what was used. It would be deferred per batch, which would limit our misaccounting drift. What do you think?
___
*[pkg/sql/colexec/hashjoiner_test.go, line 925 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-K2ZFAQp4_l-McQEf:-Lu-K2ZFAQp4_l-McQEg:bd3z4c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f47bc8c34b96aeac8f16238d1201ef8ecee83b8/pkg/sql/colexec/hashjoiner_test.go#L925)):*
> ```Go
> 			runTestsWithTyps(t, inputs, typs, tc.expectedTuples, unorderedVerifier, func(sources []Operator) (Operator, error) {
> 				spec := createSpecForHashJoiner(tc)
> 				result, err := NewColOperator(ctx, flowCtx, spec, sources, &testMemAcc)
> ```

I wonder if it would be better to plumb some testing knob through to use an existing monitor instead of creating a new one (so that we can just rely on the global monitor cleanup for tests),
___
*[pkg/sql/colexec/operator.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-FYb5AnLsCx4gJ0cs:-Lu-FYb5AnLsCx4gJ0ct:b-f1rtrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colexec/operator.go#L125)):*
> ```Go
> 
> // StaticMemoryOperator is an interface that operators which use static memory
> // need to implement.	"Static memory" is defined as memory that is internal to
> ```

nit: a couple extra spaces
___
*[pkg/sql/colexec/utils_test.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-G2qI7OAqmA882tAl:-Lu-G2qI7OAqmA882tAm:b-ymki15) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colexec/utils_test.go#L97)):*
> ```Go
> 
> 	// testMemMonitor and testMemAcc are started below in init() method and
> 	// closed within TestMain function in colexec/main_test.go.
> ```

Why don't we define them here and set them in `TestMain`? It seems brittle to separate the instantiation and cleanup
___
*[pkg/sql/colflow/vectorized_flow_space_test.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-I5Q74c_wnAxx0qzz:-Lu-I5Q74c_wnAxx0r--:bpq9trf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e78a2b657574e3842cd8fd50ed92d0411a9bffef/pkg/sql/colflow/vectorized_flow_space_test.go#L109)):*
> ```Go
> 		},
> 		{
> 			desc: "aggregation",
> ```

Can we keep these other cases in the test?
___
*[pkg/sql/colflow/vectorized_panic_propagation_test.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-IDi44iYxXAEsmTnb:-Lu-IDi5BI1dI9CvNzWJ:buyomxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colflow/vectorized_panic_propagation_test.go#L48)):*
> ```Go
> 	acc := memMonitor.MakeBoundAccount()
> 	defer acc.Close(ctx)
> 	testAllocator := colexec.NewAllocator(ctx, &acc)
> ```

I think it might be worth doing this `TestMain` setup everywhere you have to at least type two of these identical groups of statements (especially for adding tests in the future)
___
*[pkg/sql/execinfra/testutils.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-I_T25iwoCY96A4A-:-Lu-I_T25iwoCY96A4A0:bcipi5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/execinfra/testutils.go#L83)):*
> ```Go
> // MakeTestMemMonitor creates a new memory monitor to be used in tests.
> func MakeTestMemMonitor(ctx context.Context, st *cluster.Settings) *mon.BytesMonitor {
> 	memMonitor := mon.MakeMonitor(
> ```

Interesting we didn't have this before. I think the `MakeTestingEvalCtx` does something like this. Maybe we should call this from there as well.

**Review by yuzefovich — COMMENTED** [review]
Yes, that memory is what I would define as "static", and we'll need to audit all operators to make sure they implement `StaticMemoryOperator` interface.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-:-Lu5DEzL6ooV9NIk7kos:bpkg61q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/allocator.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-AjnH85rGUjzKJErx:-Lu4soO95wDE80xoCD35:bdy0821) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colexec/allocator.go#L86)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we delegate getting the number of bytes to the `Bytes` implementation? Then it would be easier to calculate the delta as:
```
before := dest.SizeBytes()
dest.Append(args)
after := dest.SizeBytes()
delta := after - before
```
For other types, we could do the same as above but passing in `dest.Length()` to `estimateBatchSizeBytes`?
</blockquote></details>

True, that would be simpler but then we could violate the memory limit - we could append more than we're allowed since we would be accounting after the append occurred.
___
*[pkg/sql/colexec/allocator.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-Bo3s1Iif3-C5QD4_:-Lu4x9DS4BLDlJB8X2Rg:bakxg7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colexec/allocator.go#L107)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we need to carefully think of this `SET` case to not introduce unnecessary overhead. There actually don't seem to be too many uses of `execgen.SET`:
```
pkg/col/coldata/vec_tmpl.go
101:				execgen.SET(toCol, int(selIdx), v)
103:				execgen.SET(toCol, i+int(args.DestIdx), v)
114:		execgen.SET(toCol, int(selIdx), v)
116:		execgen.SET(toCol, i+int(args.DestIdx), v)
205:		execgen.SET(target, int(rowIdx), newVal)

pkg/sql/colexec/execgen/cmd/execgen/data_manipulation_gen.go
38:		templatePlaceholder: "execgen.SET",

pkg/sql/colexec/execgen/cmd/execgen/cast_gen.go
44:	// replace the _TO_TYPE_SET's with execgen.SET's of the correct type
45:	s = strings.Replace(s, "_TO_TYPE_SET", "execgen.SET", -1)

pkg/sql/colexec/const_tmpl.go
103:			execgen.SET(col, int(i), c.constVal)
108:			execgen.SET(col, i, c.constVal)

pkg/sql/colexec/min_max_agg_tmpl.go
152:		execgen.SET(a.vec, a.curIdx, a.curAgg)
209:			execgen.SET(a.vec, a.curIdx, a.curAgg)

pkg/sql/colexec/cast_tmpl.go
59:// This will be replaced with execgen.SET.

pkg/sql/colexec/vec_comparators_tmpl.go
125:		execgen.SET(c.vecs[dstVecIdx], int(dstIdx), v)

pkg/sql/colexec/mergejoiner_tmpl.go
681:							execgen.SET(outCol, outStartIdx, val)
814:						// TODO(yuzefovich): think about making execgen.SET set both the
823:						execgen.SET(outCol, outStartIdx, v)
831:						execgen.SET(outCol, outStartIdx, v)

pkg/sql/colexec/rowstovec_tmpl.go
74:			execgen.SET(col, i, castV)
```

I wonder if we could introduce deferred accounting in this case? i.e. "If you use `SET`, you *must* call `allocator.UpdateAccount`" or something like that, which would just recalculate what was used. It would be deferred per batch, which would limit our misaccounting drift. What do you think?
</blockquote></details>

Hm, if we do this deferred accounting, then we can get into the same situation as above that the memory limit has been "breached." Also we would either have to track the previous memory footprint of each batch in the `Allocator` or the operators that use `execgen.SET` would need to calculate the delta themselves. I don't like either of the options.

Maybe a two step process would work better - something like:
```
allocator.PrepareForSetting(vec, numberOfElementsToSet)
...
for ... // do all SETs
...
allocator.FinishSetting(vec)
```
In the "prepare" step we would estimate the usage and update the account; we would also memorize how much we "allocated.". Then after all `SET`s are done, we will update the account to reflect the actual usage. This way the performance hit is minimal, and the operators don't need to know anything about the memory accounting. We still could over- or underestimate the actual usage though :/
___
*[pkg/sql/colexec/hashjoiner_test.go, line 925 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-K2ZFAQp4_l-McQEf:-Lu534vm3W6mDvP3IdI_:bepscqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f47bc8c34b96aeac8f16238d1201ef8ecee83b8/pkg/sql/colexec/hashjoiner_test.go#L925)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wonder if it would be better to plumb some testing knob through to use an existing monitor instead of creating a new one (so that we can just rely on the global monitor cleanup for tests),
</blockquote></details>

Done. I also thought about it initially and wasn't sure whether we'd want to plumb the testing knob into `NewColOperator`, but it doesn't look that bad.
___
*[pkg/sql/colexec/operator.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-FYb5AnLsCx4gJ0cs:-Lu53Tun8H3UnWm-Tcha:b-ssls2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colexec/operator.go#L125)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: a couple extra spaces
</blockquote></details>

Done (actually it was a tab in there :) ).
___
*[pkg/sql/colexec/utils_test.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-G2qI7OAqmA882tAl:-Lu54nlk2LUwjVUO1j0k:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colexec/utils_test.go#L97)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why don't we define them here and set them in `TestMain`? It seems brittle to separate the instantiation and cleanup
</blockquote></details>

Good point, done.
___
*[pkg/sql/colflow/vectorized_flow_space_test.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-I5Q74c_wnAxx0qzz:-Lu55Zdg9YlRNxjWz_K5:bajsc91) ([raw file](https://github.com/cockroachdb/cockroach/blob/e78a2b657574e3842cd8fd50ed92d0411a9bffef/pkg/sql/colflow/vectorized_flow_space_test.go#L109)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we keep these other cases in the test?
</blockquote></details>

This test originally was written to check that the static memory usage respects the memory limit. We have redefined what "static memory" means in the vectorized engine, so - currently - only the merge joiner and  the case operators implement `StaticMemoryOperator` interface, and both of them are tested. The deleted cases will error out when the `Allocator` will refuse to give out a batch.

I guess we should have a separate test that makes sure that the refusal by the `Allocator` does take place. I left a TODO.
___
*[pkg/sql/colflow/vectorized_panic_propagation_test.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-IDi44iYxXAEsmTnb:-Lu5AfvBEBN9QbnKPEJA:brkno94) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colflow/vectorized_panic_propagation_test.go#L48)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it might be worth doing this `TestMain` setup everywhere you have to at least type two of these identical groups of statements (especially for adding tests in the future)
</blockquote></details>

I agree, done.
___
*[pkg/sql/execinfra/testutils.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-I_T25iwoCY96A4A-:-Lu5Bwn2EzULQH5MvrlX:bj5x8xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/execinfra/testutils.go#L83)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Interesting we didn't have this before. I think the `MakeTestingEvalCtx` does something like this. Maybe we should call this from there as well.
</blockquote></details>

I tried, and it created an import cycle between `execinfra` and `tree`, so I left another TODO.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colflow/vectorized_panic_propagation_test.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-IDi44iYxXAEsmTnb:-Lu5S3f_9hP-PI21IOAZ:b-j0rm3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colflow/vectorized_panic_propagation_test.go#L48)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I agree, done.
</blockquote></details>

Actually, in multiple-concurrency setups it is not possible to share the same memory account between different components because it leads to data races, so I'll need to bring separate accounts back into a few places. I'll fix it tomorrow.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/allocator.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu-AjnH85rGUjzKJErx:-Lu9J4tnCkFE08f9MMXt:byg433c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f502a77d93f38790594b33d4c0c512338b68113f/pkg/sql/colexec/allocator.go#L86)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

True, that would be simpler but then we could violate the memory limit - we could append more than we're allowed since we would be accounting after the append occurred.
</blockquote></details>

Refactored.

**Review by asubiotto — CHANGES_REQUESTED** [review]
But that's confusing because it isn't "static" right? It's variable non-coldata memory

> Reviewed 62 of 62 files at r4, 33 of 57 files at r5, 40 of 40 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-:-Lu9Pf3Y3n6uX_v8_H_r:b-47uf4u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/colserde/main_test.go, line 40 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9Qj_x7ZtuNjHCY6qe:-Lu9Qj_x7ZtuNjHCY6qf:bl96vwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/col/colserde/main_test.go#L40)):*
> ```Go
> 	ctx := context.Background()
> 	testMemMonitor = execinfra.NewTestMemMonitor(ctx, cluster.MakeTestingClusterSettings())
> 	defer testMemMonitor.Stop(ctx)
> ```

These `defer`s will not get executed because of `os.Exit`, so you'll need to call `m.Run` separately (maybe through some anonymous function):
```
os.Exit(func() error {
    // Do setup
    defer cleanup()
    m.Run()
}())
```
___
*[pkg/sql/colexec/allocator.go, line 100 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9RA__CsI3N8c0fYdw:-Lu9RA__CsI3N8c0fYdx:b-1ry1y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colexec/allocator.go#L100)):*
> ```Go
> 	}
> 	delta = after - before
> 	if err := a.acc.Grow(a.ctx, delta); err != nil {
> ```

Is it valid to call `Grow` with a negative delta?
___
*[pkg/sql/colexec/execplan.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9R_omAX3-HdsfOktG:-Lu9R_omAX3-HdsfOktH:bqv8vfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colexec/execplan.go#L660)):*
> ```Go
> 				bufferingMemAccount := result.BufferingOpMemMonitor.MakeBoundAccount()
> 				result.BufferingOpMemAccount = &bufferingMemAccount
> 				sortChunksMemAccount = &bufferingMemAccount
> ```

Would it be possible to factor out the creation of these monitors/accounts into a helper function?
___
*[pkg/sql/colexec/main_test.go, line 43 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9Ruim0uyQ4bHotSjP:-Lu9Ruim0uyQ4bHotSjQ:bmdzise) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colexec/main_test.go#L43)):*
> ```Go
> 	memAcc := testMemMonitor.MakeBoundAccount()
> 	testMemAcc = &memAcc
> 	testAllocator = NewAllocator(ctx, testMemAcc)
> ```

Same comment as other package
___
*[pkg/sql/colflow/vectorized_flow_shutdown_test.go, line 102 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9SJ8O387daYuUqLe5:-Lu9SJ8O387daYuUqLe6:b-val3t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colflow/vectorized_flow_shutdown_test.go#L102)):*
> ```Go
> // TODO(yuzefovich): the test doesn't behave as described when another remote
> // node is added because the inboxes are instantiated with the local context.
> // Fix this.
> ```

Does it fail if you do it?
___
*[pkg/sql/colflow/vectorized_flow_space_test.go, line 30 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9SZLL8XlfFN2lp0lJ:-Lu9SZLL8XlfFN2lp0lK:b-3wmd5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colflow/vectorized_flow_space_test.go#L30)):*
> ```Go
> 
> // TODO(yuzefovich): write a test to verify that the Allocator respects the
> // memory limit.
> ```

I think that should be part of this PR

**Review by yuzefovich — COMMENTED** [review]
Yes, it is not "static", it's dynamic internal memory of an operator. How about we call it "internal memory" then?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-:-Lu9_a5C9smwT7Ad5LtN:b6m097g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/colserde/main_test.go, line 40 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9Qj_x7ZtuNjHCY6qe:-Lu9mvk60pNNvpfZu0Dl:bp938ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/col/colserde/main_test.go#L40)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

These `defer`s will not get executed because of `os.Exit`, so you'll need to call `m.Run` separately (maybe through some anonymous function):
```
os.Exit(func() error {
    // Do setup
    defer cleanup()
    m.Run()
}())
```
</blockquote></details>

Thanks, you're right. Done. (Although it appeared to be working since the whole process exits, and everything will have to get cleaned up.)
___
*[pkg/sql/colexec/allocator.go, line 100 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9RA__CsI3N8c0fYdw:-Lu9brWY562pLReW99TU:b-8pfvge) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colexec/allocator.go#L100)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is it valid to call `Grow` with a negative delta?
</blockquote></details>

Yes, it is valid to do that, but it seems like in such case the "freed" memory is not returned to the pool of the monitor, and I think it is ok. I refactored the code anyway.
___
*[pkg/sql/colexec/execplan.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9R_omAX3-HdsfOktG:-Lu9fdV3DAg6aH-Bzb8Y:b-jshy3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colexec/execplan.go#L660)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Would it be possible to factor out the creation of these monitors/accounts into a helper function?
</blockquote></details>

Yes, good point, done.
___
*[pkg/sql/colexec/main_test.go, line 43 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9Ruim0uyQ4bHotSjP:-Lu9fg_V0uxwO6i5lp0Q:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colexec/main_test.go#L43)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Same comment as other package
</blockquote></details>

Thanks, done.
___
*[pkg/sql/colflow/vectorized_flow_shutdown_test.go, line 102 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9SJ8O387daYuUqLe5:-Lu9filRDTm_TLwEdSdG:bpvrfo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colflow/vectorized_flow_shutdown_test.go#L102)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does it fail if you do it?
</blockquote></details>

I don't think it will fail, but I haven't tried refactoring the test since it shouldn't be a part of this PR. I just noticed the mismatch while thinking whether we could reuse the same memory accounts, so I left a TODO.
___
*[pkg/sql/colflow/vectorized_flow_space_test.go, line 30 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9SZLL8XlfFN2lp0lJ:-Lu9mnTF2XzOXcCB3oMg:b4rk6jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colflow/vectorized_flow_space_test.go#L30)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think that should be part of this PR
</blockquote></details>

I agree (I was just being lazy, thanks for the nudge). Done.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colflow/vectorized_flow_shutdown_test.go, line 102 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-Lu9SJ8O387daYuUqLe5:-LuFOUfWBLvJVWOwZTw8:b-yycd5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/01ccc4992da46e9ebca4a9ae8c3571f073f81cc4/pkg/sql/colflow/vectorized_flow_shutdown_test.go#L102)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think it will fail, but I haven't tried refactoring the test since it shouldn't be a part of this PR. I just noticed the mismatch while thinking whether we could reuse the same memory accounts, so I left a TODO.
</blockquote></details>

Actually, I think I was wrong - the test is set up correctly. I removed TODO.

**Review by asubiotto — APPROVED** [review]
Internal memory could apply to both static and dynamic, maybe there should also be something about "primitive" (i.e. primitive static memory vs primitive dynamic memory vs coldata memory). :lgtm: anyway, we can bikeshed this later, great work!

> Reviewed 2 of 72 files at r7, 29 of 57 files at r8, 43 of 43 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42468#-:-LuHwvYO1mZuYtIoSB0r:bm6m9w3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
