### PR TITLE
workload: Add a workload option for spanning queries

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Adds a query to the kv workload that touches all the ranges in the
kv table as well ask every key in each range. This is useful when
testing load based splitting

Release note: None

### CODE REVIEW

**Review by m-schneider — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31938)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/kv/kv.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31938#-LQ-NhzD9zk2jrq7Pzfg:-LQ-NhzD9zk2jrq7Pzfh:builk6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d387b8e557dd29ed47e13a87a65c1b217a2c5cda/pkg/workload/kv/kv.go#L236)):*
> ```Go
> 	writeStmtStr := buf.String()
> 
> 	// Spanning statement
> ```

Span statement would be more inline with the other two comments.
___
*[pkg/workload/kv/kv.go, line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31938#-LQ-O3sj3mgN3gVgwxkL:-LQ-O3sj3mgN3gVgwxkM:b9rhoru) ([raw file](https://github.com/cockroachdb/cockroach/blob/d387b8e557dd29ed47e13a87a65c1b217a2c5cda/pkg/workload/kv/kv.go#L300)):*
> ```Go
> 		return rows.Err()
> 	}
> 	if o.g.rand().Intn(100) < o.config.spanPercent {
> ```

I think that if you want span percentage to be a percentage of all queries you need to refactor this a bit. Cause right now P(spanStmt) = (1-readPercent)*spanPercent.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31938)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/kv/kv.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31938#-LQ-NhzD9zk2jrq7Pzfg:-LQ-S0bh7pBLV93K-Cp-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d387b8e557dd29ed47e13a87a65c1b217a2c5cda/pkg/workload/kv/kv.go#L236)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Span statement would be more inline with the other two comments.
</blockquote></details>

Done.
___
*[pkg/workload/kv/kv.go, line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31938#-LQ-O3sj3mgN3gVgwxkL:-LQ-S3_h9REXrEN4b6Hz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d387b8e557dd29ed47e13a87a65c1b217a2c5cda/pkg/workload/kv/kv.go#L300)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I think that if you want span percentage to be a percentage of all queries you need to refactor this a bit. Cause right now P(spanStmt) = (1-readPercent)*spanPercent.
</blockquote></details>

Done.

**Review by m-schneider — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31938)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/kv/kv.go, line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31938#-LQ-O3sj3mgN3gVgwxkL:-LQ-UVDyAWavD7TD4P4P:b-svnga4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d387b8e557dd29ed47e13a87a65c1b217a2c5cda/pkg/workload/kv/kv.go#L300)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I know what you're doing, but I think a comment would be super helpful for this because it's not total intuitive what you're doing.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31938)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/kv/kv.go, line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31938#-LQ-O3sj3mgN3gVgwxkL:-LQ-WeAxAv4lF2xlGHnq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d387b8e557dd29ed47e13a87a65c1b217a2c5cda/pkg/workload/kv/kv.go#L300)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I know what you're doing, but I think a comment would be super helpful for this because it's not total intuitive what you're doing.
</blockquote></details>

Done.

**Comment by m-schneider** [comment]
:lgtm:

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31938#-:-LQ02iaS-kzUmGvgwWzB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/kv/kv.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31938#-LQ02dLxCLF7ELGtZcqw:-LQ02dLxCLF7ELGtZcqx:b-g7qm8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a2ded8657f5d1181cd19a40d15b3a2d0289172c/pkg/workload/kv/kv.go#L308)):*
> ```Go
> 		_, err := o.spanStmt.Exec(ctx)
> 		elapsed := timeutil.Since(start)
> 		o.hists.Get(`count(v)`).Record(elapsed)
> ```

s/`count(v)`/`span`/

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31938)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/workload/kv/kv.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31938#-LQ02dLxCLF7ELGtZcqw:-LQ0TT536_3qG7xABkm7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a2ded8657f5d1181cd19a40d15b3a2d0289172c/pkg/workload/kv/kv.go#L308)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/`count(v)`/`span`/
</blockquote></details>

Done.

**Pull request merged**
