### PR TITLE
backupccl: fix bug in cleanup of restored databases with types or sch…

### PR DESCRIPTION
**Pull request by thoszhang**
…emas

While cleaning up a database that we attempted to restore, if the
database has any child tables, types, or schemas, we preserve the
database as-is instead of deleting it. The problem was that while we
correctly disregarded tables we tried to restore in the same operation,
we didn't do the same for types and schemas, so the presence of any
types or schemas in the database would prevent a failed database RESTORE
from being cleaned up. This commit fixes that bug.

Release note (bug fix): Fixes a bug where the presence of types or
schemas in a database to be restored would prevent the database from
being cleaned up on restore failure.

### CODE REVIEW

**Comment by lucy-zhang** [comment]
Preventing orphaned child tables/types of cleaned up schemas will happen in a separate PR.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54993#-:-MITsuKU7V3UYwE0Rcot:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

**Review by pbardea — APPROVED** [review]

**Comment by lucy-zhang** [comment]
TFTRs

bors r+

**Comment by lucy-zhang** [comment]
Hmm, we hit this flake:

```
------- Stdout: -------
=== RUN   TestLogic/local-vec-auto/distsql_expr
=== PAUSE TestLogic/local-vec-auto/distsql_expr
=== CONT  TestLogic/local-vec-auto/distsql_expr
        --- FAIL: TestLogic/local-vec-auto/distsql_expr (11.47s)
            logic.go:1410: 
                :0: error while processing
            logic.go:1410: pq: setting updated but timed out waiting to read new value
```

**Pull request merged**
