### PR TITLE
sql: expose an ability to request redacted stmt bundles

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit extends the stmt bundle collection infrastructure to support requesting redacted stmt bundles. Previously, this was only possible via an explicit `EXPLAIN ANALYZE (DEBUG, REDACT)` stmt, but this commit adds the support via overloads to `crdb_internal.request_statement_bundle` builtin as well as the server API. This paves the way for requesting the redacted bundles via the DB Console, but it'll be done separately.

To support this we need to add another boolean column to `system.statement_diagnostics_requests` table to indicate whether a request is for the redacted bundle or not. This requires adding a migration in which we populate the existing rows with all `false` values.

In order to reduce the amount of code churn and simplify this change, this commit repurposes some of the existing code that we introduced the last time we added a migration for plan-gist matching in stmt bundles. In other words, this commit simultenously removes some stale code and handles the new column.

Epic: CRDB-37839

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice, thanks for tackling this!

> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-:-Nxug3g1-6bxUfjs0bdw:bajwsfw)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/instrumentation.go` line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-NxuXRXr-ql4jf69iuDN:-NxuXRXr-ql4jf69iuDO:b-p7vv8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddec74da590efc1fd714ae6ec444f07efdb77add/pkg/sql/instrumentation.go#L635)):*
> ```Go
> 				// explicitly. We also need to set RedactValues when this bundle
> 				// is being collected for the request that asked for redaction.
> 				ih.explainFlags.RedactValues = true
> ```

[nit] Should we do this in `Setup` and `setupWithPlanGist` when `ih.diagRequest` is first set?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-:-NxxK96VB_M7A2pYxkLa:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/instrumentation.go` line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-NxuXRXr-ql4jf69iuDN:-NxxK66bAYa8M8-b5Htg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddec74da590efc1fd714ae6ec444f07efdb77add/pkg/sql/instrumentation.go#L635)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Should we do this in `Setup` and `setupWithPlanGist` when `ih.diagRequest` is first set?
</blockquote></details>

Done.

**Review by mgartner — COMMENTED** [review]
Nicely done! 

> Reviewed 26 of 31 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-:-NxxunuQ6OBQx_pbbpMb:bog2maa)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/upgrade/upgrades/redacted_stmt_diagnostics_requests.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-Nxxu9qq-SR_FKqAQgPm:-Nxxu9qrBbwwrX5GkVyj:bbu4vp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cea88a65a9e80a39c51b755cd0f675ac574c0/pkg/upgrade/upgrades/redacted_stmt_diagnostics_requests.go#L31)):*
> ```Go
> 
> 	createCompletedIdx = `
> CREATE INDEX completed_idx ON system.statement_diagnostics_requests (completed, ID)
> ```

nit: Should this be named with a `_v3` suffix for future migrations? Or did you consider that a bad pattern?
___
*[`pkg/sql/logictest/testdata/logic_test/gen_test_objects` line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-NxxuXjrEL7MTl7m5N4j:-NxxuXjrEL7MTl7m5N4k:b-hmjah0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cea88a65a9e80a39c51b755cd0f675ac574c0/pkg/sql/logictest/testdata/logic_test/gen_test_objects#L210)):*
> ```
> protected_ts_meta      "vers
> ion"               bigint
> "ran gelog"            "%rangeID"               bigint
> ```

Any idea what happened here?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123859)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/upgrade/upgrades/redacted_stmt_diagnostics_requests.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-Nxxu9qq-SR_FKqAQgPm:-NxxvAeyAk-lcE1mdb4Q:b1qcosc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cea88a65a9e80a39c51b755cd0f675ac574c0/pkg/upgrade/upgrades/redacted_stmt_diagnostics_requests.go#L31)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Should this be named with a `_v3` suffix for future migrations? Or did you consider that a bad pattern?
</blockquote></details>

I thought it would be cleaner to just have `completed_idx`. We've modified this index a few times in the past, and I think every time it was `v -> v2` or `v2 -> v` transition. At this point it would have been probably `v6` or something if we simply incremented it every time. I don't really have an opinion here, just `v` seems cleanest to me. It don't think I've seen any guidelines for migrations in general either, perhaps it might be worth writing up a quick style guide?
___
*[`pkg/sql/logictest/testdata/logic_test/gen_test_objects` line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-NxxuXjrEL7MTl7m5N4j:-Nxxw0CF2wDYa0OsW1Yk:btvvpx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cea88a65a9e80a39c51b755cd0f675ac574c0/pkg/sql/logictest/testdata/logic_test/gen_test_objects#L210)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Any idea what happened here?
</blockquote></details>

IIUC `planner.GenerateTestObjects` (which powers `crdb_internal.generate_test_objects` builtin) uses system descriptors, and since we changed the descriptor for a system table, the output of the builtin also changed.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123859)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/upgrade/upgrades/redacted_stmt_diagnostics_requests.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-Nxxu9qq-SR_FKqAQgPm:-Nxy1c2G7JYDjJcs46rr:b8a615g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cea88a65a9e80a39c51b755cd0f675ac574c0/pkg/upgrade/upgrades/redacted_stmt_diagnostics_requests.go#L31)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I thought it would be cleaner to just have `completed_idx`. We've modified this index a few times in the past, and I think every time it was `v -> v2` or `v2 -> v` transition. At this point it would have been probably `v6` or something if we simply incremented it every time. I don't really have an opinion here, just `v` seems cleanest to me. It don't think I've seen any guidelines for migrations in general either, perhaps it might be worth writing up a quick style guide?
</blockquote></details>

Eh, probably not worth a style guide. Just a drive-by comment. I don't have a strong opinion either.
___
*[`pkg/sql/logictest/testdata/logic_test/gen_test_objects` line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123859#-NxxuXjrEL7MTl7m5N4j:-Nxy1s-S90kz2xfsEn2e:b90hs62) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c3cea88a65a9e80a39c51b755cd0f675ac574c0/pkg/sql/logictest/testdata/logic_test/gen_test_objects#L210)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

IIUC `planner.GenerateTestObjects` (which powers `crdb_internal.generate_test_objects` builtin) uses system descriptors, and since we changed the descriptor for a system table, the output of the builtin also changed.
</blockquote></details>

Ahh thanks for the info!

**Pull request merged**
