### PR TITLE
admission: improve granter logs

### PR DESCRIPTION
**Pull request by tbg**
To the uninitiated, they were previously difficult to understand.
Now it's clearer what each number means just from looking at the
output.

While rebasing this PR on top of #80480, I realized how hard it
was (at least for me) to keep track of the many quantities involved. The
way the updates to the state were computed (were the old struct is
updated incrementally in-place) additionally made me worried
that bugs could easily be introduced. Some quantities are cumulative,
some are for the current interval but contain other quantities, etc - it
all melted my brain with ease.

I decided to at least try to make it easier for the next newcomer to
this codebase to get their bearings by constructing all of the updates
first, and then overwriting the old state. I additionally renamed all
of the variables according to a fixed pattern so that it is now clear
which ones are for the current interval or cumulative, and added
commentary to (hopefully) clarify which quantities contain each other.
Additionally, all quantities are now stored for posterity, so in
principle it's now straightforward to write a test case on any of the
intermediate quantities for any desired inputs.

More could be done here but I feel that this leaves things in a good
place. There's a chance that I have written equally intricate code but
happen to like it more because I wrote it. I trust my reviewers to keep
me honest.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80859)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

___
*[`pkg/util/admission/granter.go` line 1727 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N16fdW2B5M6EUaPNIec:-N16fdW2B5M6EUaPNIed:b-o6yrri) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0bd62fba1fc840204ca75925efd45bf6ea57bce/pkg/util/admission/granter.go#L1727)):*
> ```Go
> 		}
> 		if doLog {
> 			avgAdded := bytesAdded / int64(admitted)
> ```

thanks for doing this. Is this something you wanted to backport to 22.1 and 21.2?
I ask since the log statement is changing with the byte tokens PR https://github.com/cockroachdb/cockroach/blob/81aa87db7cd995bd81cbac5158d4cadd596e5b9a/pkg/util/admission/granter.go#L1832
It still lacks the humanized formatting, so something that will need to be fixed there too.

**Review by tbg — COMMENTED** [review]
Big update, PTAL. I realize this may make it harder to backport later changes (if we're not backporting this one as well). If you're concerned about that let's discuss dropping this PR.

Please review carefully, I am still worried I messed something up here though the test diffs seem to indicate that I haven't.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-:-N1AK9kUE8l1mM59EkdG:bcw9laq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/util/admission/granter.go` line 1727 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N16fdW2B5M6EUaPNIec:-N1AJxJF7oRGV8eNtSZA:b-h90x7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0bd62fba1fc840204ca75925efd45bf6ea57bce/pkg/util/admission/granter.go#L1727)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

thanks for doing this. Is this something you wanted to backport to 22.1 and 21.2?
I ask since the log statement is changing with the byte tokens PR https://github.com/cockroachdb/cockroach/blob/81aa87db7cd995bd81cbac5158d4cadd596e5b9a/pkg/util/admission/granter.go#L1832
It still lacks the humanized formatting, so something that will need to be fixed there too.
</blockquote></details>

I'll defer to you in terms of backporting. I'm not sure how good the test coverage here is. I don't seem to have introduced any changes (please carefully review) but there is now a large diff. Then again, not backporting may make it impossible to backport later changes. If you think that it is too risky to make a refactor of the size I'm doing here, I'm happy to hold off, though there isn't typically a better time in the cycle to do so and so it might mean the improvements here won't happen.

I think if this bakes for some time we could probably backport it to 22.1, at least if we're also backporting the bytes change. (Not sure what the plan there was).

**Comment by tbg** [comment]
Rebased, PTAL after Infest.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 7 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-:-N2CIkeR2mKj1g3Trhx8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

___
*[`pkg/util/admission/granter.go` line 1626 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2C6mjpAFubeEdPLcKT:-N2C6mjqCmqcYYSy-m0o:b-qg797s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f3c06f5f2c26bc84705430a3622f92ec1444e9d/pkg/util/admission/granter.go#L1626)):*
> ```Go
> 	// represents what has been given out. The units is bytes.
> 	totalTokens     int64
> 	tokensAllocated int64
> ```

all of these are moved into `ioLoadListenerState`, yes? I like the comments and better names.
___
*[`pkg/util/admission/granter.go` line 1750 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2C9dgc2v0KWjUQK4jH:-N2C9dgc2v0KWjUQK4jI:b-baq625) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/granter.go#L1750)):*
> ```Go
> 
> 	intL0CompactedBytes         int64
> 	smoothedIntL0CompactedBytes float64
> ```

is this smoothed value the same as in ioLoadListenerState? Same question for the two other Smoothed* members in this struct.
___
*[`pkg/util/admission/granter.go` line 1812 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2CFV8v8oJ1LyWX1uJB:-N2CFV8v8oJ1LyWX1uJC:b-iui2fh) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/granter.go#L1812)):*
> ```Go
> 	// intIngestedBytes are the bytes ingested since the last token adjustment. Bytes
> 	// tracked here are also tracked in intAdmittedBytes.
> 	intIngestedBytes := cumAdmissionStats.ingestedBytes - prev.cumAdmissionStats.ingestedBytes
> ```

s/intIngestedBytes/intIngestedAccountedBytes/
___
*[`pkg/util/admission/granter.go` line 1860 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2CBmu65UrRJYR8EZ_L:-N2CBmu65UrRJYR8EZ_M:b-4nrefa) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/granter.go#L1860)):*
> ```Go
> 		// Keep the old smoothed value around, i.e. don't update it with a zero and
> 		// don't zero it out.
> 		// TODO(during review): why?
> ```

we've not had work flow through admission control, so we don't have any reasonable interval data to update our previous estimates.
___
*[`pkg/util/admission/granter.go` line 1864 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2CD1KM6skhelynnSS7:-N2CD1KM6skhelynnSS8:bit93rq) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/granter.go#L1864)):*
> ```Go
> 	}
> 
> 	// TODO(during review): aren't we double-penalizing here? Let's say 1GB was
> ```

I think what you are suggesting is potentially a higher fidelity model, but I maybe misunderstanding what you are saying.
We are currently taking all the unaccounted bytes that landed into L0 (ingests or flush) and spreading them evenly over what was admitted. This will then be fed into `storeRequestEstimates.workByteAddition` which is used by WorkQueue for both regular writes and ingests.

I don't understand the "penalize ingestions" question. The `l0BytesIngestedFraction` is solely based on what was reported by the WorkQueue. That is, `intIngestedBytes` is not from the Pebble metrics. This fraction calculation is only to minimize the error in the interval between Admit and AdmittedWorkDone: if there a 1MB ingest, we want to make a reasonable guess on how many tokens to deduct based on past observations, and then we will fix any error in AdmittedWorkDone. So this is not saying anything about what silently bypassed admission control.
Renaming `intIngestedBytes` to `intIngestedAccountedBytes` would make this clearer.
___
*[`pkg/util/admission/granter.go` line 1907 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2CGVHwA0PhxaOtw_Sn:-N2CGVHwA0PhxaOtw_So:b-zg86sy) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/granter.go#L1907)):*
> ```Go
> 		}
> 	} else {
> 		// Under the threshold. Maintain a smoothedNumTokens based on what was
> ```

Maintain a smoothedTotalNumByteTokens ...
___
*[`pkg/util/admission/work_queue.go` line 1650 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2CHYGP03OlE8bVO6fv:-N2CHYGP03OlE8bVO6fw:b-qgv53a) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/work_queue.go#L1650)):*
> ```Go
> 			q.mu.stats.admittedBytes += uint64(h.writeBytes)
> 			if h.ingestRequest {
> 				q.mu.stats.ingestedBytes += uint64(h.writeBytes)
> ```

ingestedAccountedBytes?
Though by definition, all the `WorkQueue` stats are accounted.

**Review by tbg — COMMENTED** [review]
> Dismissed @sumeerbhola from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80859)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/util/admission/granter.go` line 1626 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2C6mjpAFubeEdPLcKT:-N2Fp9CG1FnHgWCfRMb7:b2nhswv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f3c06f5f2c26bc84705430a3622f92ec1444e9d/pkg/util/admission/granter.go#L1626)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

all of these are moved into `ioLoadListenerState`, yes? I like the comments and better names.
</blockquote></details>

Yep
___
*[`pkg/util/admission/granter.go` line 1750 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2C9dgc2v0KWjUQK4jH:-N2Fq7E-8uDoJLlErE1L:b-ue35n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/granter.go#L1750)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this smoothed value the same as in ioLoadListenerState? Same question for the two other Smoothed* members in this struct.
</blockquote></details>

Good catch. I accidentally duplicated some of these fields. Cleaned this
___
*[`pkg/util/admission/granter.go` line 1812 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2CFV8v8oJ1LyWX1uJB:-N2FpOOn64N_TvPHLah2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/granter.go#L1812)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/intIngestedBytes/intIngestedAccountedBytes/
</blockquote></details>

Done.
___
*[`pkg/util/admission/granter.go` line 1860 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2CBmu65UrRJYR8EZ_L:-N2Fo9S5-9WwWHjfCXkY:b-sqh41f) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/granter.go#L1860)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we've not had work flow through admission control, so we don't have any reasonable interval data to update our previous estimates.
</blockquote></details>

Updated with this comment.
Still, is this the right thing to do? You'd expect us to "always measure/update" but just not throttle when admission control is off. Is this just reflecting the fact that when admission control was introduced, we wanted the "off" switch to completely disable most code related to it? As is, it seems that once admission control kicks in again after a long period of being below threshold, we'll initially start out with a mostly bogus smoothed value here. I think this is fine, just trying to deeply understand the rationale here.
___
*[`pkg/util/admission/granter.go` line 1864 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2CD1KM6skhelynnSS7:-N2Ft9jE1YppzA0ry-h5:b-5l3kv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/granter.go#L1864)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think what you are suggesting is potentially a higher fidelity model, but I maybe misunderstanding what you are saying.
We are currently taking all the unaccounted bytes that landed into L0 (ingests or flush) and spreading them evenly over what was admitted. This will then be fed into `storeRequestEstimates.workByteAddition` which is used by WorkQueue for both regular writes and ingests.

I don't understand the "penalize ingestions" question. The `l0BytesIngestedFraction` is solely based on what was reported by the WorkQueue. That is, `intIngestedBytes` is not from the Pebble metrics. This fraction calculation is only to minimize the error in the interval between Admit and AdmittedWorkDone: if there a 1MB ingest, we want to make a reasonable guess on how many tokens to deduct based on past observations, and then we will fix any error in AdmittedWorkDone. So this is not saying anything about what silently bypassed admission control.
Renaming `intIngestedBytes` to `intIngestedAccountedBytes` would make this clearer.
</blockquote></details>

I hadn't understood this properly, with your explanation it makes sense.
___
*[`pkg/util/admission/granter.go` line 1907 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2CGVHwA0PhxaOtw_Sn:-N2FoUkaCjpO4Tf6U-r1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/granter.go#L1907)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Maintain a smoothedTotalNumByteTokens ...
</blockquote></details>

Done.
___
*[`pkg/util/admission/work_queue.go` line 1650 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80859#-N2CHYGP03OlE8bVO6fv:-N2Fowf05eel-GRxbaLi:bynhi5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/88616e4a96d95151b60f9f48580ee1e52a82dccc/pkg/util/admission/work_queue.go#L1650)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ingestedAccountedBytes?
Though by definition, all the `WorkQueue` stats are accounted.
</blockquote></details>

If we're going to do the `accounted` infix (and it looks like we are), then it's better to have it everywhere. Made sure it's present in all of the `storeAdmissionStats` byte counters.

**Pull request merged**
