### PR TITLE
builtins: implement regr_count

### PR DESCRIPTION
**Pull request by mneverov**
builtins: implement regr_count

See #41274

Release note (sql change): implement regr_count.

### CODE REVIEW

**Comment by mneverov** [comment]
@yuzefovich could you please help me out with this?
The problem with current implementation is that logic_test fails when evaluate:
```
select regr_count(1, 1)
from kv
```
It returns NULL instead of 0. I think this is because one of the optimization/normalization rules which creates a default result and based on some info about an aggregate function decides that it is possible to skip evaluation and return early. And I failed to find such a rule.
I found normalization rule in [groupby.opt](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/norm/rules/groupby.opt#L383) for count operation. After adding the similar rule for regr_count the query mentioned above returns 0, but the following query still returns NULL:
```
select regr_count(1, 1)
from kv
```

**Review by yuzefovich — COMMENTED** [review]
Hm, I'm not sure, my guess is that something is off in `pkg/sql/opt/operator.go`, but I don't see it. @raduberinde could you PTAL at the question above?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-:-MMRcqKx4RBV291D0Gqz:b-506epp)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by mneverov** [comment]
thanks, I forgot to mention that the same SQL returns 0 (which is expected value) and `local-vec-off`, `fakedist-vec-off`, `fakedist-metadata` tests passes.

**Comment by yuzefovich** [comment]
Oh, then it might be a problem with the vectorized engine, I'll take a look.

**Comment by yuzefovich** [comment]
Yeah, the problem is definitely in the vectorized engine, I'll open up a PR later today.

**Comment by yuzefovich** [comment]
I think if you rebase on top of #56875, then the build should be green.

**Comment by mneverov** [comment]
@yuzefovich could you please take a look?
I added [one normalization rule ](https://github.com/cockroachdb/cockroach/pull/56822/files#diff-6fb17a8bc864de3a29dc3fbd11556a4bda71f9bf7e908047ae172d17a5d1400fR404)which seems to be applicable to `regr_count`.
I also added several tests for normalization rules, but not sure if there other tests that will be useful to add

**Review by yuzefovich — APPROVED** [review]
:lgtm: but I'd like for @raduberinde to take a quick look too.

> Reviewed 13 of 14 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-:-MMX6lI0ENo1eG4mpV32:bixpfwi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mneverov)

___
*[pkg/sql/opt/operator.go, line 423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MMX4JCX6Q9NifIRT0Q2:-MMX4JCX6Q9NifIRT0Q3:b-qj2qj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c844de19acf72c453befa966564802142819a857/pkg/sql/opt/operator.go#L423)):*
> ```Go
> 		// Only SumIntOp can be used here because SumOp outputs a decimal value,
> 		// while CountOp and CountRowsOp both output int values.
> 		return outer == SumIntOp
> ```

I think this might need to change, cc @raduberinde 
___
*[pkg/sql/opt/norm/rules/groupby.opt, line 407 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MMX5erV-Z-dbZ2q0GjK:-MMX5erV-Z-dbZ2q0GjL:b-dz3idm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c844de19acf72c453befa966564802142819a857/pkg/sql/opt/norm/rules/groupby.opt#L407)):*
> ```
> # performed on a non-null expression with a CountRows operator. CountRows is
> # significantly faster to execute than RegressionCount.
> [ConvertRegressionCountToCountRows, Normalize]
> ```

This looks good to me, Radu could you please take a look at this too?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56822)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mneverov and @yuzefovich)

___
*[pkg/sql/opt/operator.go, line 423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MMX4JCX6Q9NifIRT0Q2:-MMXW6haD9Ly4f20s3uq:b9ivcgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c844de19acf72c453befa966564802142819a857/pkg/sql/opt/operator.go#L423)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think this might need to change, cc @raduberinde 
</blockquote></details>

This doesn't look right. I think this entire thing only makes sense for single-arg operators anyway, I'd move it to the `return false` case
___
*[pkg/sql/opt/norm/rules/groupby.opt, line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MMXX-Ih-t3As9_79U11:-MMXX-Ih-t3As9_79U12:bui6cgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c844de19acf72c453befa966564802142819a857/pkg/sql/opt/norm/rules/groupby.opt#L412)):*
> ```
>     $aggregations:[
>         ...
>         $item:(AggregationsItem (RegressionCount $arg:*)) &
> ```

I don't understand this rule.. RegressionCount has two arguments no? If they are both never NULL, then we can convert to CountRows, but this rule only checks the first one. If only one arg is never NULL, we can convert to `Count(otherArg)` (though that rule would be very important)

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56822)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mneverov, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/opt/operator.go, line 423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MMX4JCX6Q9NifIRT0Q2:-MMZIJIj5KX5vxlP4qwU:b-g0q03n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c844de19acf72c453befa966564802142819a857/pkg/sql/opt/operator.go#L423)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This doesn't look right. I think this entire thing only makes sense for single-arg operators anyway, I'd move it to the `return false` case
</blockquote></details>

Moved, thanks. 
It seems it is possible to merge regression aggregate functions (Postgres):
```
SELECT float8_regr_combine('{3,60,200,750,20000,2000}'::float8[],
                           '{2,180,200,740,57800,-3400}'::float8[]);
```
I think the [regressionAccumulatorBase](https://github.com/cockroachdb/cockroach/blob/609cad52785f49338f7ceff289486b87db4cecb6/pkg/sql/sem/builtins/aggregate_builtins.go#L1804) can be used for that with additional merge function like [here](https://github.com/postgres/postgres/blob/49407dc32a2931550e4ff1dea314b6a25afdfc35/src/backend/utils/adt/float.c#L3401).
___
*[pkg/sql/opt/norm/rules/groupby.opt, line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MMXX-Ih-t3As9_79U11:-MMZcjHT7JM-LXhrFWL9:b-j5mr0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c844de19acf72c453befa966564802142819a857/pkg/sql/opt/norm/rules/groupby.opt#L412)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't understand this rule.. RegressionCount has two arguments no? If they are both never NULL, then we can convert to CountRows, but this rule only checks the first one. If only one arg is never NULL, we can convert to `Count(otherArg)` (though that rule would be very important)
</blockquote></details>

Fixed the rule to have two arguments and convert to `Count(otherArg)`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56822)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mneverov and @yuzefovich)

___
*[pkg/sql/opt/norm/rules/groupby.opt, line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MMXX-Ih-t3As9_79U11:-MMaRG62DnDhvUaVr6rH:b2fo2ci) ([raw file](https://github.com/cockroachdb/cockroach/blob/c844de19acf72c453befa966564802142819a857/pkg/sql/opt/norm/rules/groupby.opt#L412)):*
<details><summary><i>Previously, mneverov (Max Neverov) wrote…</i></summary><blockquote>

Fixed the rule to have two arguments and convert to `Count(otherArg)`.
</blockquote></details>

This looks good, except that there's no reason to only do it for the first arg..  We could have two separate rules but that isn't great (and adds more overhead). We could have a `SingleRegressionCountArgument` function that checks if either arg is non-null and returns the other one (or `nil` if neither is non-null). The rule would look like:
```
(GroupBy | ScalarGroupBy
    $input:*
    $aggregations:[
        ...
        $item:(AggregationsItem
                (RegressionCount $arg1:* $arg2:*)
            ) &
            (Succeeded $newArg:(SingleRegressionCountArgument $arg1 $arg2))
        ...
    ]
    $groupingPrivate:*
)
=>
((OpName)
    $input
    (ReplaceAggregationsItem
        $aggregations
        $item
        (Count $newArg)
    )
    $groupingPrivate
)
```

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56822)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mneverov and @yuzefovich)

___
*[pkg/sql/opt/operator.go, line 423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MMX4JCX6Q9NifIRT0Q2:-MMdhMYj3hGYhBnXSwAu:blyxm1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c844de19acf72c453befa966564802142819a857/pkg/sql/opt/operator.go#L423)):*
<details><summary><i>Previously, mneverov (Max Neverov) wrote…</i></summary><blockquote>

Moved, thanks. 
It seems it is possible to merge regression aggregate functions (Postgres):
```
SELECT float8_regr_combine('{3,60,200,750,20000,2000}'::float8[],
                           '{2,180,200,740,57800,-3400}'::float8[]);
```
I think the [regressionAccumulatorBase](https://github.com/cockroachdb/cockroach/blob/609cad52785f49338f7ceff289486b87db4cecb6/pkg/sql/sem/builtins/aggregate_builtins.go#L1804) can be used for that with additional merge function like [here](https://github.com/postgres/postgres/blob/49407dc32a2931550e4ff1dea314b6a25afdfc35/src/backend/utils/adt/float.c#L3401).
</blockquote></details>

I understand this as merge for multi-arg operators is not possible.
___
*[pkg/sql/opt/norm/rules/groupby.opt, line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MMXX-Ih-t3As9_79U11:-MMdhA1l8jyawacd-wfy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c844de19acf72c453befa966564802142819a857/pkg/sql/opt/norm/rules/groupby.opt#L412)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This looks good, except that there's no reason to only do it for the first arg..  We could have two separate rules but that isn't great (and adds more overhead). We could have a `SingleRegressionCountArgument` function that checks if either arg is non-null and returns the other one (or `nil` if neither is non-null). The rule would look like:
```
(GroupBy | ScalarGroupBy
    $input:*
    $aggregations:[
        ...
        $item:(AggregationsItem
                (RegressionCount $arg1:* $arg2:*)
            ) &
            (Succeeded $newArg:(SingleRegressionCountArgument $arg1 $arg2))
        ...
    ]
    $groupingPrivate:*
)
=>
((OpName)
    $input
    (ReplaceAggregationsItem
        $aggregations
        $item
        (Count $newArg)
    )
    $groupingPrivate
)
```

</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
Opt part looks great, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-:-MMsdgxl5yhfujXAIQkK:bbpc2u6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mneverov and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
Last nit from me.

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-:-MNMVgrp27tqtZsrSQHA:b4830gc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mneverov and @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/groupby.opt, line 408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MNMVTt77APLYFVNSgVG:-MNMVTt77APLYFVNSgVH:bjdu0vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e754b432185c12fb44805cc57d7a557ca4bfcb8d/pkg/sql/opt/norm/rules/groupby.opt#L408)):*
> ```
> # normalized again to CountRows which is significantly faster to execute
> # than RegressionCount.
> [ConvertRegressionCountToCountRows, Normalize]
> ```

nit: did you mean to rename it to `ConvertRegressionCountToCount` too?
___
*[pkg/sql/opt/norm/testdata/rules/groupby, line 3475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MNMVai_1zNESiiE1ihs:-MNMVai_1zNESiiE1iht:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/e754b432185c12fb44805cc57d7a557ca4bfcb8d/pkg/sql/opt/norm/testdata/rules/groupby#L3475)):*
> ```
> 
> # ScalarGroupBy cases.
> norm expect=ConvertRegressionCountToCountRows
> ```

ditto

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56822)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/opt/norm/testdata/rules/groupby, line 3475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-MNMVai_1zNESiiE1ihs:-MNMqrDk89UeqK9s_w15:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e754b432185c12fb44805cc57d7a557ca4bfcb8d/pkg/sql/opt/norm/testdata/rules/groupby#L3475)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the contribution!

bors r=yuzefovich,raduberinde

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56822#-:-MNOsDJl0Yvd6OkiELY0:b-96dgkr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Pull request merged**
