### PR TITLE
jobs,sql,server: add structured job execution failure log to job info

### PR DESCRIPTION
**Pull request by ajwerner**
This commit adds the structured information about job execution to the
crdb_internal table in addition to the flattened string array. It then
leverages this information in the admin server API.

Informs #69170

As an example of crdb_internal.jobs for a retrying reverting job, you'll
see:

```
> select json_array_elements(execution_events) from crdb_internal.jobs where job_id = 731484911676784641;
                                                                                                                                             json_array_elements
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  {"executionEndMicros": "1643301928919757", "executionStartMicros": "1643301927541336", "instanceId": 1, "status": "reverting", "truncatedError": "scan with start key /Table/54/1/13110: root: memory budget exceeded: 532480 bytes requested, 133939200 currently allocated, 134217728 bytes in budget"}
  {"executionEndMicros": "1643302029260612", "executionStartMicros": "1643302028024034", "instanceId": 1, "status": "reverting", "truncatedError": "scan with start key /Table/54/1/13110: root: memory budget exceeded: 532480 bytes requested, 133867520 currently allocated, 134217728 bytes in budget"}
  {"executionEndMicros": "1643302255024877", "executionStartMicros": "1643302253353781", "instanceId": 1, "status": "reverting", "truncatedError": "scan with start key /Table/54/1/13110: root: memory budget exceeded: 532480 bytes requested, 133898240 currently allocated, 134217728 bytes in budget"}
```

The setup to make this example was to run a cluster with a small
`--max-sql-memory=128MiB` and then create a table:

```sql
create table foo (i int primary key, j int default (unique_rowid()) unique, b string);
insert into foo(i, b) select i, repeat('a', 1<<12) from generate_series(1, 100000) as t(i);
set sql_safe_updates=false;
alter table foo add column bb string as (i::string || b) stored unique, drop column j; -- retries forever
```

Release note (sql change): The crdb_internal.jobs table now has a new column
`execution_events` which is a structured json form of `execution_errors`.

### CODE REVIEW

**Comment by ajwerner** [comment]
@miretskiy this is in support of [this design (internal)](https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/20.1_obsrv_db-console-jobs?node-id=2011%3A9921).

**Review by miretskiy — CHANGES_REQUESTED** [review]
Would be nice to include new output example in PR description.  Probably would help doc writes too.

> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-:-MuNt6DI7R2CyeMD7ZtS:bp9ssv8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jocrl)

___
*[pkg/jobs/jobs.go, line 1068 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-MuNtRmOExF_NGbw_lo_:-MuNtRmOExF_NGbw_loa:bibuyge) ([raw file](https://github.com/cockroachdb/cockroach/blob/280525aabd18bdcfb9927cec2ac40bf32509e20f/pkg/jobs/jobs.go#L1068)):*
> ```Go
> 		}
> 		msg, err := protoreflect.MessageToJSON(&ev, protoreflect.FmtFlags{
> 			EmitDefaults: false,
> ```

Do we want to also set `EmitRedacted: true`? (this would probably make Parse method not work ... but presumably we should try to redact?
___
*[pkg/server/serverpb/admin.proto, line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-MuNu4Cj1QtYHaIbvdnr:-MuNu4Cj1QtYHaIbvdns:bfvs2ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/280525aabd18bdcfb9927cec2ac40bf32509e20f/pkg/server/serverpb/admin.proto#L635)):*
> ```protobuf
>   // ExecutionFailures is a log of execution failures of the job. It is not
>   // guaranteed to contain all execution failures and some execution failures
>   // may not contain an error or end.
> ```

are these truncated at some point?
___
*[pkg/sql/crdb_internal.go, line 849 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-MuNuCKG6RE_zvx6yK7y:-MuNuCKG6RE_zvx6yK7z:b3qhqa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/280525aabd18bdcfb9927cec2ac40bf32509e20f/pkg/sql/crdb_internal.go#L849)):*
> ```Go
> 				if payload != nil {
> 					executionErrors = jobs.FormatRetriableExecutionErrorLogToStringArray(
> 						ctx, payload.RetriableExecutionFailureLog,
> ```

do we want to show all? or perhaps truncate?

**Review by ajwerner — COMMENTED** [review]
I'll collect some example of the output and write a test in the jobs package. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-:-MuNv-89AEDl41p8Zth9:bkwqf0p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl and @miretskiy)

___
*[pkg/jobs/jobs.go, line 1068 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-MuNtRmOExF_NGbw_lo_:-MuNuj7MED3PqgFOCRUx:bv2l7tv) ([raw file](https://github.com/cockroachdb/cockroach/blob/280525aabd18bdcfb9927cec2ac40bf32509e20f/pkg/jobs/jobs.go#L1068)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we want to also set `EmitRedacted: true`? (this would probably make Parse method not work ... but presumably we should try to redact?
</blockquote></details>

I don't think we want to redact it. We don't redact other jobs errors shown in the table or UI.
___
*[pkg/server/serverpb/admin.proto, line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-MuNu4Cj1QtYHaIbvdnr:-MuNumrd8LBu2-lCQFdy:b-mni6yy) ([raw file](https://github.com/cockroachdb/cockroach/blob/280525aabd18bdcfb9927cec2ac40bf32509e20f/pkg/server/serverpb/admin.proto#L635)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

are these truncated at some point?
</blockquote></details>

Yes, they are truncated already before we store them. 
___
*[pkg/sql/crdb_internal.go, line 849 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-MuNuCKG6RE_zvx6yK7y:-MuNupUGCsDgRSR8crn_:b-fc1b71) ([raw file](https://github.com/cockroachdb/cockroach/blob/280525aabd18bdcfb9927cec2ac40bf32509e20f/pkg/sql/crdb_internal.go#L849)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we want to show all? or perhaps truncate?
</blockquote></details>

We already truncate them before storing them. https://github.com/cockroachdb/cockroach/blob/b64fe37f6d83f3feae5181c0fc99b1cb0105362f/pkg/jobs/jobs.go#L617-L622

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jocrl, and @miretskiy)

___
*[pkg/jobs/jobs.go, line 1068 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-MuNtRmOExF_NGbw_lo_:-MuQXrHR1_c3ptCdF4D9:br2d7va) ([raw file](https://github.com/cockroachdb/cockroach/blob/280525aabd18bdcfb9927cec2ac40bf32509e20f/pkg/jobs/jobs.go#L1068)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think we want to redact it. We don't redact other jobs errors shown in the table or UI.
</blockquote></details>

Okay; I suspect this will have to change at some point.

**Review by ajwerner — COMMENTED** [review]
I updated the message with some examples. There's definitely more we can do with this log, but I'm not doing more now. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-:-MuRTGos0C1r5N0yVnFi:bjvix1u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl and @miretskiy)

___
*[pkg/jobs/jobs.go, line 1068 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-MuNtRmOExF_NGbw_lo_:-MuRTC6v9QkFdUCyBKiy:b-9dvas4) ([raw file](https://github.com/cockroachdb/cockroach/blob/280525aabd18bdcfb9927cec2ac40bf32509e20f/pkg/jobs/jobs.go#L1068)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Okay; I suspect this will have to change at some point.
</blockquote></details>

we do hide rows based on the user who is logged in, so maybe that helps? 
https://github.com/cockroachdb/cockroach/blob/fa93c68218af8094f24f421d233ee9d344b7303c/pkg/sql/crdb_internal.go#L775-L782

**Review by jocrl — APPROVED** [review]
Thank you!! lgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-:-MuRcWJ-565xky5wb2Ga:be4xgls)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[pkg/server/serverpb/admin.proto, line 625 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-MuRc7Ic9OwyFTtYLlLn:-MuRc7Ic9OwyFTtYLlLo:bvafq9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8358c6028c661c264c9a2990ac49a297b3c25d03/pkg/server/serverpb/admin.proto#L625)):*
> ```protobuf
>   message ExecutionFailure {
>     // Status is the status of the job during the execution.
>     string status = 1;
> ```

Just out of curiosity, will the per-error status always be "failed"?

**Review by ajwerner — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-:-MuRfUvc06XlI7Gw2n18:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl and @miretskiy)

___
*[pkg/server/serverpb/admin.proto, line 625 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75556#-MuRc7Ic9OwyFTtYLlLn:-MuRf5IC9nvNmF5a7qS_:bpyewpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8358c6028c661c264c9a2990ac49a297b3c25d03/pkg/server/serverpb/admin.proto#L625)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Just out of curiosity, will the per-error status always be "failed"?
</blockquote></details>

No, it'll always be either `running` or `reverting` corresponding to https://github.com/cockroachdb/cockroach/blob/af4b5dbf97c89f7faa11de10d0fe63558990824e/pkg/jobs/jobs.go#L165-L211

**Pull request merged**
