### PR TITLE
sql: add telemetry reporting for inverted and hash sharded indexes

### PR DESCRIPTION
**Pull request by rohany**
Release justification: low risk changes
Release note (sql change): This PR adds telemetry reporting
for usages of inverted and hash sharded indexes.

### CODE REVIEW

**Review by otan — APPROVED** [review]
LGTM, not sure it answers "Number of indexes used per query" though (but I don't think you can with the telemetry stuff we have today, unless you do bucketing)

**Comment by rohany** [comment]
Yeah, it only handles the number of created inverted and hash sharded indexes

bors r=otan

**Comment by otan** [comment]
ah, but you mentioned this PR in the telemetry spreadsheet :)

**Comment by rohany** [comment]
typo lol

**Pull request merged**
