### PR TITLE
sql/parser: Add new DOidWrapper type and use for OID and Name types

### LINKED ISSUE #12207: sql: pgwire behavior for string arrays is partially incorrect
Sequelize queries various `pg_catalog` tables to assemble an array of column names, using the following query:

```
SELECT i.relname AS name,
       ix.indisprimary AS PRIMARY,
       ix.indisunique AS UNIQUE,
       ix.indkey AS indkey,
       ARRAY_AGG(a.attnum) AS column_indexes,
       ARRAY_AGG(a.attname) AS column_names,
       pg_get_indexdef(ix.indexrelid) AS definition
FROM pg_class t,
     pg_class i,
     pg_index ix,
     pg_attribute a
WHERE t.oid = ix.indrelid
AND   i.oid = ix.indexrelid
AND   a.attrelid = t.oid
AND   t.relkind = 'r'
AND   t.relname = 'customers' -- this query is run once for each table
GROUP BY i.relname,
         ix.indexrelid,
         ix.indisprimary,
         ix.indisunique,
         ix.indkey
ORDER BY i.relname
```

One of the return values is the result of `ARRAY_AGG(a.attname)`, which we treat as an array of strings. We return arrays of strings as strings that look like this: `{'foo','bar','baz'}`.

Sequelize fails to parse the representation of this array that we send over the pg wire protocol for two separate reasons.

1. Sequelize expects that the strings inside the array are not quoted, and in fact postgres returns string arrays that look like `{foo,bar,baz}` unless a string has a `,` character in it in which case it'll be `{foo,"bar,",baz}`.
2. Sequelize expects that the type we report for this array over pgwire is `1003`, corresponding to an array of `name` types. We report that this array is of type `1009`, or an array of `text` types. If we report `1009`, Sequelize actually blows up while trying to parse the returned array.

It shouldn't be too hard to solve the first one. The second one is a little bit more involved - we'll need to make a `Datum` type for column name literal values, as well as a corresponding type for arrays of those. Then we'll need to change the relevant column definitions in `pg_catalog` to use this new type.

### PR DESCRIPTION
**Pull request by nvb**
Replaces #12281.
Resolves #12207.

This change adds the `parser.DOidWrapper` and `parser.tOidWrapper`
types, which wrap Datums and Types respectively, allowing custom Oid
values to be attached. The reason the types were introduced was to
permit the introduction of Datum types with new Object IDs while
maintaining identical behavior to current Datum types. Specifically,
it obviates the need to:
- define a new `parser.Datum` type.
- define a new `parser.Type` type.
- support operations and functions for the new Type.
- support mixed-type operations between the new Type and the old Type.

Instead, DOidWrapper allows a standard Datum to be wrapped with a new Oid.
This approach provides two major advantages:
- performance of the existing Datum types are not affected because they
  do not need to have custom oid.Oids added to their structure.
- the introduction of new Datum aliases is straightforward and does not
  require
  additions to typing rules or type-dependent evaluation behavior.

Types that currently benefit from DOidWrapper are:
- `DOid  => DOidWrapper(*DInt,    oid.T_oid)`
- `DName => DOidWrapper(*DString, oid.T_name)`

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12641)

### CODE REVIEW

**Comment by knz** [comment]
Quite a good job. Well done. 

I assume that you have checked the output of `git grep '.(\*parser.D'` and `git grep '.(\*D'` to see if there any remaining casts.

I wonder if pursuant to #12145 and #12530, the types `int2`  `int4` etc shouldn't also be wrapped types around `int`. Same for `text` around `string`. What do you think?

---

Reviewed 6 of 6 files at r1, 29 of 29 files at r2, 16 of 16 files at r3, 17 of 17 files at r4, 1 of 1 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[pkg/sql/analyze.go, line 1435 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YfDOvJPsiFvSumsby:-K_YfDOwk4bNmM23UvA2:b64kho7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/analyze.go#L1435)):*
> ```Go
> 			// a LIKE 'foo%' -> a >= "foo" AND a < "fop"
> 			if d, ok := right.(parser.Datum); ok {
> 				if s, ok := parser.AsDString(d); ok {
> ```

You could simplify this by making `AsDString` accept an `Expr`. 

---

*[pkg/sql/limit.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Yf_VNw1vt_N2LhEm0:-K_Yf_VNw1vt_N2LhEm1:b-mmkj34) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/limit.go#L118)):*
> ```Go
> 			// folding prior to type checking.
> 			if d, ok := datum.src.(parser.Datum); ok {
> 				if i, ok := parser.AsDInt(d); ok {
> ```

Same as earlier, `AsDInt` could take `Expr` as argument.

---

*[pkg/sql/pg_catalog.go, line 868 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YismKJuSpCjK-50Y6:-K_YismLV2qysW-5X8MH:b9i1gjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d29020dd662b9e2e7774b5a31eed9f7d64a009/pkg/sql/pg_catalog.go#L868)):*
> ```Go
> CREATE TABLE pg_catalog.pg_namespace (
> 	oid INT,
> 	nspname NAME NOT NULL,
> ```

I don't understand why you removed the DEFAULT - or perhaps why the DEFAULT clause was there in the first place :)

---

*[pkg/sql/pg_catalog.go, line 1262 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YjXe_-QC48f7mcKNr:-K_YjXe_-QC48f7mcKNs:b-9t4g5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d29020dd662b9e2e7774b5a31eed9f7d64a009/pkg/sql/pg_catalog.go#L1262)):*
> ```Go
> CREATE TABLE pg_catalog.pg_type (
> 	oid INT,
> 	typname NAME NOT NULL,
> ```

see my previous comment

---

*[pkg/sql/parser/datum.go, line 238 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Yg8U-IXh9X49ifDyi:-K_Yg8U-IXh9X49ifDyj:b-3u78im) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L238)):*
> ```Go
> // be used instead of direct type assertions wherever a *DInt wrapped by a
> // *DOidWrapper is possible.
> func AsDInt(d Datum) (DInt, bool) {
> ```

If I were you I would use the name `AsDInt` for what you currently call `MustBeDInt`
Then rename the other one `MaybeDInt` 

(Same for `AsDString` / `MaybeDString`).

---

*[pkg/sql/parser/datum.go, line 1894 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Ygts6tGt46JmkDpnQ:-K_Ygts6tGt46JmkDpnR:bd820pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1894)):*
> ```Go
> 		panic("cannot wrap DNull with an Oid")
> 	case *DOidWrapper:
> 		// Assure that *DOidWrappers never nest, meaning that unwrapping
> ```

Like in my other comments I'd suggest erroring out if this ever happens instead of accepting it silently.

---

*[pkg/sql/parser/datum.go, line 1900 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Yh1L3YcJAMZwTxTLW:-K_Yh1L4rtk0-XLFAOSl:b-bflymg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1900)):*
> ```Go
> 	case *DString:
> 	default:
> 		panic("currently only *DInt and *DString are hooked up to work with *DOidWrapper. " +
> ```

Put the explanation in a comment and use a simpler panic message. The person encountering the panic can then look at the code where it was triggered.

---

*[pkg/sql/parser/datum.go, line 1931 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YhY47ZyvSwcuDVhJa:-K_YhY47ZyvSwcuDVhJb:b-q8nkfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1931)):*
> ```Go
> 		return 1
> 	}
> 	v, ok := other.(*DOidWrapper)
> ```

The inverse condition reads simpler:
```go
if v, ok := other.(*DOidWrapper); ok {
    return d.Wrapped.Compare(v.Wrapped)
}
return d.Wrapped.Compare(other)
```

---

*[pkg/sql/parser/datum.go, line 1941 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Yhmgo0WXqkh4hzrUC:-K_YhmgpRMwM9SOp6jfH:ba6i1t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1941)):*
> ```Go
> func (d *DOidWrapper) Prev() (Datum, bool) {
> 	if prev, ok := d.Wrapped.Prev(); ok {
> 		return wrapWithOid(prev, d.Oid), true
> ```

Make `wrapWithOid` return `nil` if its 1st argument is `nil`, then you can simply write `prev, ok := d.Wrapped.Prev(); return wrapWithOid(prev, d.Oid), ok`

---

*[pkg/sql/parser/datum.go, line 1987 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Yi5Yp2D16F_u8Gidd:-K_Yi5Yp2D16F_u8Gide:bzeksn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1987)):*
> ```Go
> // Size implements the Datum interface.
> func (d *DOidWrapper) Size() uintptr {
> 	return unsafe.Sizeof(*d)
> ```

`unsafe.Sizeof(*d) + d.Wrapped.Size()`

---

*[pkg/sql/parser/eval.go, line 2385 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YiMLFdMAxw7OnItmo:-K_YiMLGFL-xphcw8qJ2:bvkmrxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/eval.go#L2385)):*
> ```Go
> 	}
> 
> 	// TODO(nvanbenschoten) This should be a switch on the ResolvedType of d.
> ```

Why not changing it right away then?

---

*[pkg/sql/parser/type.go, line 410 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YbtVGhkZuIvZKiHiv:-K_YbtVGhkZuIvZKiHiw:b-cgosfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ce8873dba93e69a1a7987e1fc6c7972dc4a7be/pkg/sql/parser/type.go#L410)):*
> ```Go
> 	case TypeString:
> 		return oid.T__text
> 	case TypeAny:
> ```

I think `T_anyarray` can be returned in the `default` case. For example pg's `array_agg` returns T_anyarray always.

---

*[pkg/sql/parser/type.go, line 449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YdXb5P5R9y8FHNK2O:-K_YdXb5P5R9y8FHNK2P:bt86r01) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ce8873dba93e69a1a7987e1fc6c7972dc4a7be/pkg/sql/parser/type.go#L449)):*
> ```Go
> // Oid implements the Type interface.
> func (TTable) Oid() oid.Oid {
> 	panic("TODO(knz) unknown Oid for TTable")
> ```

`return oid.T_anyelement` (see the advertised return type for `unnest` in `pg_proc`)

---

*[pkg/sql/parser/type.go, line 502 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YekRilF3LB-gJe-f9:-K_YekRjC7KmxisHXq-7:b5vdwu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/type.go#L502)):*
> ```Go
> 		panic("cannot wrap TypeAny with an Oid")
> 	case tOidWrapper:
> 		// Assure that tOidWrappers never nest, meaning that unwrapping
> ```

I'm not sure it even makes sense to re-wrap a type by calling `wrapTypeWithOid` on a `tOidWrapper`. Instead of accepting this case silently I'd suggest a panic to check that it indeed never happens.

---

*[pkg/sql/parser/type.go, line 110 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Ymid16J6yo5JjrHXp:-K_Ymid16J6yo5JjrHXq:bw29fo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e03bc43526f0993506887f46a14514f146bb48d/pkg/sql/parser/type.go#L110)):*
> ```Go
> 	// PGOIDType in expr.go.
> 	// TODO(nvanbenschoten) This should be fixed.
> 	TypePGOID = wrapTypeWithOid(TypeInt, oid.T_oid)
> ```

In the intermediate commit(s) where both `TypePGOID` and `TypeOid` still exist side by side, please also add a comment to explain that `TypePGOID` is superseded by `TypeOid` and will be removed in a subsequent commit.

---

*[pkg/sql/pgwire/types.go, line 614 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YkAPotkNq6f3TtiWW:-K_YkAPpJ3ZC5mwqiDYg:b6yue9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d29020dd662b9e2e7774b5a31eed9f7d64a009/pkg/sql/pgwire/types.go#L614)):*
> ```Go
> 			return d, errors.Errorf("unsupported name format code: %d", code)
> 		}
> 	case oid.T_bytea:
> ```

And what about `T_oid` here.

---

*[pkg/sql/sqlbase/structured.proto, line 42 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YkNJ3DgeauUK-BGx8:-K_YkNJ3DgeauUK-BGx9:b-k2rdlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d29020dd662b9e2e7774b5a31eed9f7d64a009/pkg/sql/sqlbase/structured.proto#L42)):*
> ```protobuf
>     TIMESTAMPTZ = 9;
>     COLLATEDSTRING = 10;  // Collated STRING, CHAR, and VARCHAR
>     NAME = 11;
> ```

Given the amount of redundancy caused by STRING and NAME existing side by side, or INT and OID, I would suggest investigating if we could have one field in the column type with its "behavior type" (the code that runs) and another one with its "advertised type". Have the latter nullable so that if it doesn't exist yet it defaults to the behavior type, for backward compatibility.

Either in this PR or file a followup issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-:-K_Yl5tDfKOrMsq-gJ1R:b38wr58)*

**Comment by jordanlewis** [comment]
Reviewed 6 of 6 files at r1, 29 of 29 files at r2, 16 of 16 files at r3, 17 of 17 files at r4, 1 of 1 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[pkg/sql/pg_catalog.go, line 868 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YismKJuSpCjK-50Y6:-K__9CV1jTgiSpzTs4s1:buha1kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d29020dd662b9e2e7774b5a31eed9f7d64a009/pkg/sql/pg_catalog.go#L868)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't understand why you removed the DEFAULT - or perhaps why the DEFAULT clause was there in the first place :)
</blockquote></details>

I did something similar in my NAME patch - agreed that there was no reason to have this in the first place. We have no name literal syntax, so the default doesn't work.

---

*[pkg/sql/parser/datum.go, line 238 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Yg8U-IXh9X49ifDyi:-K__9ZmPLdSpk5zzp7k_:b-toir93) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L238)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

If I were you I would use the name `AsDInt` for what you currently call `MustBeDInt`
Then rename the other one `MaybeDInt` 

(Same for `AsDString` / `MaybeDString`).
</blockquote></details>

I'm personally happy about the `Must` naming. I think a `panic` is a bad enough consequence that it warrants naming a function that could do so something like `Must` or `FooOrPanic`.

---

*[pkg/sql/parser/datum.go, line 1876 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K__B2YjZTYYzdsiP4Jq:-K__B2Ykzu2cZd26LQrN:b5dusvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1876)):*
> ```Go
> // TODO during review: other option would be to keep tOidWrapper but create new Datum
> // types for DOid and DName. The benefit would be that we could avoid needing to attach
> // an Oid onto each Datum instance and that methods like String could be overridden for
> ```

Being able to override `String` seems like it will likely come up at one point or another, but I don't like the downsides you mention, which seem to erase most of the gains that you've achieved with this factorization.

Couldn't we still modify the `String` behavior based on the inner datum type by modifying what the wrapper's `String` does based on the inner `OID`?

---

*[pkg/sql/parser/datum.go, line 1894 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Ygts6tGt46JmkDpnQ:-K__BVFyWIBfmpPqh0x1:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1894)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Like in my other comments I'd suggest erroring out if this ever happens instead of accepting it silently.
</blockquote></details>

+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641)*

**Comment by cuongdo** [comment]
@nvanbenschoten Any chance you can progress this soon? It'd be great to get further along with our Sequelize support.

**Comment by nvanbenschoten** [comment]
@cuongdo yep, I'm hoping to get this in by early next week.

**Comment by nvanbenschoten** [comment]
Thanks for the reviews!

---

Review status: 0 of 38 files reviewed at latest revision, 18 unresolved discussions.

---

*[pkg/sql/analyze.go, line 1435 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YfDOvJPsiFvSumsby:-KajZzfWwOdRmfllLmMs:bombmv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/analyze.go#L1435)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You could simplify this by making `AsDString` accept an `Expr`. 
</blockquote></details>

Good call. Done.

---

*[pkg/sql/limit.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Yf_VNw1vt_N2LhEm0:-Kaj_UrBfwUWitrW1b2j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/limit.go#L118)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Same as earlier, `AsDInt` could take `Expr` as argument.
</blockquote></details>

Done.

---

*[pkg/sql/pg_catalog.go, line 868 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YismKJuSpCjK-50Y6:-KajsTOuATETl-vOAvWE:bzevavm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d29020dd662b9e2e7774b5a31eed9f7d64a009/pkg/sql/pg_catalog.go#L868)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I did something similar in my NAME patch - agreed that there was no reason to have this in the first place. We have no name literal syntax, so the default doesn't work.
</blockquote></details>

Yeah, I was looking at Jordan's change when I removed DEFAULT. He had correctly recognized that the DEFAULT clause was useless. It was there because I was much more strict about information_schema tables when they were originally implemented (I tried to get the CREATE TABLE results to match with MySQL). Since then it has become clear that identical schemas are unnecessary.

---

*[pkg/sql/parser/datum.go, line 1876 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K__B2YjZTYYzdsiP4Jq:-KajZGGSbrvQeROJR-rN:b-dzbiug) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1876)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Being able to override `String` seems like it will likely come up at one point or another, but I don't like the downsides you mention, which seem to erase most of the gains that you've achieved with this factorization.

Couldn't we still modify the `String` behavior based on the inner datum type by modifying what the wrapper's `String` does based on the inner `OID`?
</blockquote></details>

Ah great point! We could do pretty much exactly what we do for `tOidWrapper.String`. Added a comment in `Datum.Format` to stress that point.

---

*[pkg/sql/parser/datum.go, line 1894 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Ygts6tGt46JmkDpnQ:-KajcMMPbBNlk1ZE_qJ2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1894)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---

*[pkg/sql/parser/datum.go, line 1900 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Yh1L3YcJAMZwTxTLW:-Kaj_uPspy7I8Ne7dkAR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1900)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Put the explanation in a comment and use a simpler panic message. The person encountering the panic can then look at the code where it was triggered.
</blockquote></details>

Done.

---

*[pkg/sql/parser/datum.go, line 1931 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YhY47ZyvSwcuDVhJa:-Kaja-yg4_CoOrXr65Et:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1931)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The inverse condition reads simpler:
```go
if v, ok := other.(*DOidWrapper); ok {
    return d.Wrapped.Compare(v.Wrapped)
}
return d.Wrapped.Compare(other)
```
</blockquote></details>

Done.

---

*[pkg/sql/parser/datum.go, line 1941 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Yhmgo0WXqkh4hzrUC:-Kajbb7BUDKIn48tB0om:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1941)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Make `wrapWithOid` return `nil` if its 1st argument is `nil`, then you can simply write `prev, ok := d.Wrapped.Prev(); return wrapWithOid(prev, d.Oid), ok`
</blockquote></details>

Done.

---

*[pkg/sql/parser/datum.go, line 1987 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Yi5Yp2D16F_u8Gidd:-Kajbg4CvPoCe5kSZ3J3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/datum.go#L1987)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`unsafe.Sizeof(*d) + d.Wrapped.Size()`
</blockquote></details>

Done.

---

*[pkg/sql/parser/eval.go, line 2385 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YiMLFdMAxw7OnItmo:-KajluqQsebbvQP2wpkb:bc409hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/eval.go#L2385)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why not changing it right away then?
</blockquote></details>

Added as the new first commit.

---

*[pkg/sql/parser/type.go, line 410 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YbtVGhkZuIvZKiHiv:-KajYkt4u-w175TawVLw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ce8873dba93e69a1a7987e1fc6c7972dc4a7be/pkg/sql/parser/type.go#L410)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think `T_anyarray` can be returned in the `default` case. For example pg's `array_agg` returns T_anyarray always.
</blockquote></details>

Done.

---

*[pkg/sql/parser/type.go, line 449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YdXb5P5R9y8FHNK2O:-KajYnKvmb1BTc-Y73tv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ce8873dba93e69a1a7987e1fc6c7972dc4a7be/pkg/sql/parser/type.go#L449)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`return oid.T_anyelement` (see the advertised return type for `unnest` in `pg_proc`)
</blockquote></details>

Done.

---

*[pkg/sql/parser/type.go, line 502 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YekRilF3LB-gJe-f9:-KajcIbkn8c6okgfN-Jn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe2729307677440fe5bf801a06fd17ce9d3290db/pkg/sql/parser/type.go#L502)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm not sure it even makes sense to re-wrap a type by calling `wrapTypeWithOid` on a `tOidWrapper`. Instead of accepting this case silently I'd suggest a panic to check that it indeed never happens.
</blockquote></details>

Done.

---

*[pkg/sql/parser/type.go, line 110 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_Ymid16J6yo5JjrHXp:-KajtmQJ8rzMYIL6OdMl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e03bc43526f0993506887f46a14514f146bb48d/pkg/sql/parser/type.go#L110)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

In the intermediate commit(s) where both `TypePGOID` and `TypeOid` still exist side by side, please also add a comment to explain that `TypePGOID` is superseded by `TypeOid` and will be removed in a subsequent commit.
</blockquote></details>

Done.

---

*[pkg/sql/pgwire/types.go, line 614 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YkAPotkNq6f3TtiWW:-Kajto8nMKaQcgEWm2hX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d29020dd662b9e2e7774b5a31eed9f7d64a009/pkg/sql/pgwire/types.go#L614)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

And what about `T_oid` here.
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/structured.proto, line 42 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YkNJ3DgeauUK-BGx8:-KajuKJebkIdoxTr-B3x:b-d7qd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d29020dd662b9e2e7774b5a31eed9f7d64a009/pkg/sql/sqlbase/structured.proto#L42)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Given the amount of redundancy caused by STRING and NAME existing side by side, or INT and OID, I would suggest investigating if we could have one field in the column type with its "behavior type" (the code that runs) and another one with its "advertised type". Have the latter nullable so that if it doesn't exist yet it defaults to the behavior type, for backward compatibility.

Either in this PR or file a followup issue.
</blockquote></details>

That's actually exactly how I initially implemented this, but it quickly became apparent that the approach caused more issues than it solved. To demonstrate why this is, take a look at all references to `ColumnType_OID`.  Out of the 7 places that the value is used, 5 of them would need special handling for DOids (either calling `parser.NewDOid` or returning `parser.TypeOid`). Adding a new "advertised type" field would mean that we would need to break these "flat" enumeration switch statements into nested switches, which makes the code less readable and less pleasant to work with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-:-Kaju1Ep13WbP74Tf9bi:b-hlc8bm)*

**Comment by knz** [comment]
Reviewed 1 of 29 files at r2, 31 of 33 files at r7, 1 of 16 files at r8, 14 of 19 files at r9, 1 of 1 files at r10, 4 of 5 files at r11, 1 of 1 files at r12.
Review status: 37 of 38 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 1564 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-Kb5Z_pk0rkAuSASsEut:-Kb5Z_plMK4JLydhczcf:bywff3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e48b6a37e8e6446a42735003f41bb78dd7951a6a/pkg/sql/parser/builtins.go#L1564)):*
> ```Go
> 		},
> 	},
> 	"pg_catalog.format_type": {
> ```

I don't get how this format_type() built-in belongs to this PR. Where is it used?

---

*[pkg/sql/sqlbase/structured.proto, line 42 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-K_YkNJ3DgeauUK-BGx8:-Kb5Wx3E5GIpFr-ke3b0:bz9f547) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d29020dd662b9e2e7774b5a31eed9f7d64a009/pkg/sql/sqlbase/structured.proto#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That's actually exactly how I initially implemented this, but it quickly became apparent that the approach caused more issues than it solved. To demonstrate why this is, take a look at all references to `ColumnType_OID`.  Out of the 7 places that the value is used, 5 of them would need special handling for DOids (either calling `parser.NewDOid` or returning `parser.TypeOid`). Adding a new "advertised type" field would mean that we would need to break these "flat" enumeration switch statements into nested switches, which makes the code less readable and less pleasant to work with.
</blockquote></details>

Well one would argue that the current state with all this redundancy is not especially pleasant to work with either.
Let's still investigate this further: #13045

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641)*

**Comment by knz** [comment]
LGTM except the change to builtins.go which I don't understand.

---

Review status: 37 of 38 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-:-Kb5ZhPArtoMUBDWd4Q2:b-4qzxrs)*

**Comment by nvanbenschoten** [comment]
TFTR!

---

Review status: 12 of 38 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/parser/builtins.go, line 1564 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-Kb5Z_pk0rkAuSASsEut:-KbEKvT8sN6zT_Q9OTpP:bar77mj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e48b6a37e8e6446a42735003f41bb78dd7951a6a/pkg/sql/parser/builtins.go#L1564)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't get how this format_type() built-in belongs to this PR. Where is it used?
</blockquote></details>

I think what you're seeing is the result of a rebase. I didn't add this in here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641#-:-KbEL-SzFF0IQAHMrEsn:b-814g8k)*

**Comment by knz** [comment]
Reviewed 9 of 9 files at r13.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12641)*

**Pull request merged**
