### PR TITLE
jobsprofiler: annotate backup DSP diagram with per-proc progress

### PR DESCRIPTION
**Pull request by adityamaru**
This change teaches `SHOW JOB <jobID> WITH EXECUTION DETAILS`
when run against a backup job to annotate the latest DSP diagram
stored for the backup with per-node, per-processor progress
information. This annotated diagram is then re-serialized and
stored as the most up-to-date DSP diagram for that job.

The backup job is the first of its kind to annotate a DSP diagram
with per-node, per-proc progress information and so this change
adds some logic to deserialize a flow diagram from a URL and
annotate the diagram's processors with progress information.

Informs: https://github.com/cockroachdb/cockroach/issues/100488

Release note (sql change): `SHOW JOB WITH EXECUTION DETAILS` for
a backup job will regenerate the DistSQL plan diagram with per-node,
per-processor progress information. This will help better understand
the state of a running backup job.

### CODE REVIEW

**Comment by adityamaru** [comment]
first 3 commits are from - https://github.com/cockroachdb/cockroach/pull/102308

**Comment by adityamaru** [comment]
This is the output in the SQL shell:

```
root@localhost:26257/defaultdb> show job 867995665675059201 with execution details;
        job_id       | job_type |                                    description                                     | statement | user_name |  status   | running_status |          created
          |          started           |          finished          |          modified          | fraction_completed | error | coordinator_id |      trace_id       |          last_run
      |          next_run          | num_runs | execution_errors |
                                                                                                                plan_diagram
                                                                                                                                                                          |
                        plan_diagram
---------------------+----------+------------------------------------------------------------------------------------+-----------+-----------+-----------+----------------+-----------------
----------+----------------------------+----------------------------+----------------------------+--------------------+-------+----------------+---------------------+----------------------
------+----------------------------+----------+------------------+--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------
------------------------------------------------------------------------------
  867995665675059201 | BACKUP   | BACKUP TABLE foo INTO '/2023/05/24-205415.38' IN 'nodelocal://1/bar' WITH detached |           | root      | succeeded | NULL           | 2023-05-24 20:54
:15.38363 | 2023-05-24 20:54:41.089845 | 2023-05-24 20:54:41.296625 | 2023-05-24 20:54:41.296665 |                  1 |       |              1 | 1094942245856281543 | 2023-05-24 20:54:41.0
89846 | 2023-05-24 20:55:11.089846 |        1 | NULL             | https://cockroachdb.github.io/distsqlplan/decode.html#eJyMkE1P8zAQhO_vr6j27Lyx0-bLN6CXCgEVLacqQo6zDYE0Dl5XBUX57ygJiA8JieP
OrGcebwf0XIOER5PLJIrTNIyiMIpDHqYBF8CgMQVeqwMSyB0IyBi01mgkMnaQunFhVbyA5Ayqpj26Qc4YaGMRZAeucjWChPOzi8u7tc-BQYFOVfWYuGlVQ7OdyOTM36q8Rl_whd8JL-hhrCotEsmZ-M85ZD0Dc3SfHeRUiSDFF6jVEiTv2d-5bpFa0xB
-4_qtif9o8kSfMcCixOkYZI5W49oaPe5O480YNAoFkptcMQ2r5sMiZ1EdJvyMwb42p_uqAAlBsdeRELmXJHnqLTCMvDTWc09hqOcxch0kOQwPVEnDxzYP5jTGbl_bAWuvakIGV-oJl-jQHqqmIlfpd6fv_70FAAD__-E6pJ0= | {"flow_id:<2dfc6
11b-88b9-4e56-97c3-ae5c37e0c28b> type:PROCESSOR id:0 sql_instance_id:1 ": 1}
(1 row)

Time: 95ms total (execution 95ms / network 0ms)
```

and this is an example of how the diagrams are annotated:
Screenshot 2023-05-12 at 2 34 46 PM
Screenshot 2023-05-12 at 2 35 29 PM (1)

**Review by dt — APPROVED** [review]

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103145#-:-NWfmecM6RwpljgsGRDj:be8rotp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[`pkg/sql/jobs_execution_details.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103145#-NWflbUyC5jaiD1Gf_CH:-NWflbUz0seK6VATiuiO:bajxi7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5eec5741ad95422154cbd78cb3616156ae9494a/pkg/sql/jobs_execution_details.go#L143)):*
> ```Go
> 			flowDiag.UpdateComponentFractionProgressed(perComponentProgress)
> 
> 			// Re-serialize and write the update DistSQL diagram.
> ```

nit: `s/update/updated/g`.
___
*[`pkg/sql/delegate/show_jobs.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103145#-NWflv9G0Pup-C4pFNiE:-NWflv9G0Pup-C4pFNiF:bl2558n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5eec5741ad95422154cbd78cb3616156ae9494a/pkg/sql/delegate/show_jobs.go#L36)):*
> ```Go
> 		if n.Options.ExecutionDetails {
> 			baseQuery.WriteString(`, NULLIF(crdb_internal.job_execution_details(job_id)->>'plan_diagram'::STRING, '') AS plan_diagram`)
> 			baseQuery.WriteString(`, NULLIF(crdb_internal.job_execution_details(job_id)->>'per_component_fraction_progressed'::STRING, '') AS plan_diagram`)
> ```

nit: these two columns have the same `AS` name, is this ok?

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103145)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`pkg/sql/delegate/show_jobs.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103145#-NWflv9G0Pup-C4pFNiE:-NXpDn-Z2d8Ilr3B3PLY:b-s88kco) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5eec5741ad95422154cbd78cb3616156ae9494a/pkg/sql/delegate/show_jobs.go#L36)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: these two columns have the same `AS` name, is this ok?
</blockquote></details>

nope, thats an oversight. Thanks for catching, fixed.

**Comment by adityamaru** [comment]
@yuzefovich a lot of our tests match against the flow diagram URL. I think my change to include the `FlowID` / `ProcessorID` in the URL encoding is resulting in unique diagram URLs being generated on every run. I'm thinking maybe I add a testing knob that zeros out the FlowID/ProcessorIDs and set that knob to true in all these tests?

**Comment by yuzefovich** [comment]
Yeah, that sounds reasonable. We do already have `MakeDeterministic` flag - can you piggy-back on that?

**Comment by adityamaru** [comment]
Extended CI failing with https://github.com/cockroachdb/cockroach/issues/104660

TFTR!

bors r=dt,yuzefovich

**Pull request merged**
