### PR TITLE
sql: some preliminary changes for output parameter support in procedures

### PR DESCRIPTION
**Pull request by yuzefovich**
See each commit for details.

Addresses: #100405.
Epic: CRDB-30611

### CODE REVIEW

**Comment by yuzefovich** [comment]
Note that some of the newly added test cases currently return incorrect results that I need to investigate, but it's pretty large PR already, so the TODOs for them can be addressed separately.

**Comment by yuzefovich** [comment]
Nevermind my previous comment - I addressed all the TODOs that I wanted.

**Review by mgartner — APPROVED** [review]
:lgtm: Nice work! Might be good for @DrewKimball to take a look too.

> Reviewed 30 of 30 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 29 of 29 files at r6, 20 of 25 files at r7, 9 of 9 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-:-Nsjp_ha2lSASZ9PInij:bhrp7s0)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/sem/tree/type_check.go` line 1164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NsjnHzBCxEMCpN6MnNr:-NsjnHzBCxEMCpN6MnNs:b-6tde8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/abbd40ca5083adc69a6f812213e95d1be5939180/pkg/sql/sem/tree/type_check.go#L1164)):*
> ```Go
> 			semaCtx.Properties.Reject(RejectProcedures)
> 			return func() {
> 				semaCtx.Properties.Restore(origProperties)
> ```

Why do we restore the derived properties in this case? Isn't it important that expressions about this func know whether or not we encountered an aggregate, generator, or window func?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/procedure_params` line 19 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-Nsjp1fa2tafBjWOoo7w:-Nsjp1fa2tafBjWOoo7x:b1ydv6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea8505c2f13a554b4b2adc1640493259fddcb1f/pkg/ccl/logictestccl/testdata/logic_test/procedure_params#L19)):*
> ```
> # Argument expressions for OUT parameters shouldn't be evaluated.
> query I colnames
> CALL p(1 // 0);
> ```

interesting behavior, great find!

**Review by DrewKimball — APPROVED** [review]
:lgtm: Very thorough!

> Reviewed 30 of 30 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 29 of 29 files at r6, 20 of 25 files at r7, 2 of 9 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-:-Nsk1ZpF1c201PB5vMad:b6ocgbs)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 45 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NsjpG_t3CEUfV1X1obL):*
What's with the doubled commit messages? Is it just an artifact of reviewable?
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 732 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NsjlHgf-rchb3-b6Y-6:-Nsjl6NIBeN6JjLroRmk:bi4y3ur) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68dce8ab6da67e50da204e9ef2340806a336750/pkg/sql/catalog/funcdesc/func_desc.go#L732)):*
> ```Go
> 	}
> 	ret.ReturnType = tree.FixedReturnType(desc.ReturnType.Type)
> 	ret.ReturnsRecordType = types.IsRecordType(desc.ReturnType.Type)
> ```

Maybe doesn't have to be fixed here, but `ReturnsRecordType` probably shouldn't be set when there are OUT parameters. It's used to indicate that the routine has to be called with a column definition list if used as a data source.
___
*[`pkg/sql/sem/tree/type_check.go` line 1154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NsjjG9G10f7bt40-TFV:-NsjjG9G10f7bt40-TFW:b8acu95) ([raw file](https://github.com/cockroachdb/cockroach/blob/abbd40ca5083adc69a6f812213e95d1be5939180/pkg/sql/sem/tree/type_check.go#L1154)):*
> ```Go
> 		resolver = semaCtx.FunctionResolver
> 		origProperties := semaCtx.Properties
> 		setProperties = func() func() {
> ```

[nit] How would you feel instead using a function like this:
```
func typeCheckWithFuncAncestor(semaCtx *SemaContext, fn func() error) error {
  defer semaCtx.Properties.Restore(semaCtx.Properties)

  // We'll need to remember we are in a function application to
  // generate suitable errors in checkFunctionUsage().
  semaCtx.Properties.Ancestors.Push(FuncExprAncestor)
  if expr.WindowDef != nil {
    semaCtx.Properties.Ancestors.Push(WindowFuncAncestor)
  }
  // Disallow procedures in function arguments.
  semaCtx.Properties.Reject(RejectProcedures)

  return fn()
}
```
___
*[`pkg/ccl/logictestccl/testdata/logic_test/procedure_params` line 64 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NsjwqXg9felMqNW3Suy:-NsjwqXh3onf2jsgq1ij:bk3m6tc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea8505c2f13a554b4b2adc1640493259fddcb1f/pkg/ccl/logictestccl/testdata/logic_test/procedure_params#L64)):*
> ```
> 
> statement ok
> CREATE PROCEDURE p(INOUT param INT) AS $$ BEGIN SELECT 'hello'; END $$ LANGUAGE PLpgSQL;
> ```

Did you mean for this to be RETURN?
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_params` line 53 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-Nsk-Yjq2iZ4pQLcFDp5:-Nsk-Yjq2iZ4pQLcFDp6:bxdrnn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea8505c2f13a554b4b2adc1640493259fddcb1f/pkg/sql/logictest/testdata/logic_test/procedure_params#L53)):*
> ```
> 
> # This procedure returns VOID type, so this result should be empty.
> query I empty
> ```

Isn't this still tested without adding an `empty` directive?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120029)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 45 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NsjpG_t3CEUfV1X1obL):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

What's with the doubled commit messages? Is it just an artifact of reviewable?
</blockquote></details>

Yeah, something is up with the reviewable - there are 5 commits in the PR, but for some reason the commit message for the third commit is duplicated here.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 732 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NsjlHgf-rchb3-b6Y-6:-Nsk5vBq0Ifwrppb6soK:b-qpn966) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68dce8ab6da67e50da204e9ef2340806a336750/pkg/sql/catalog/funcdesc/func_desc.go#L732)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Maybe doesn't have to be fixed here, but `ReturnsRecordType` probably shouldn't be set when there are OUT parameters. It's used to indicate that the routine has to be called with a column definition list if used as a data source.
</blockquote></details>

Hm, I think you're right, I left a TODO for this.
___
*[`pkg/sql/sem/tree/type_check.go` line 1154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NsjjG9G10f7bt40-TFV:-NskETkl8lHf5505IHJi:b-86mr6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/abbd40ca5083adc69a6f812213e95d1be5939180/pkg/sql/sem/tree/type_check.go#L1154)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] How would you feel instead using a function like this:
```
func typeCheckWithFuncAncestor(semaCtx *SemaContext, fn func() error) error {
  defer semaCtx.Properties.Restore(semaCtx.Properties)

  // We'll need to remember we are in a function application to
  // generate suitable errors in checkFunctionUsage().
  semaCtx.Properties.Ancestors.Push(FuncExprAncestor)
  if expr.WindowDef != nil {
    semaCtx.Properties.Ancestors.Push(WindowFuncAncestor)
  }
  // Disallow procedures in function arguments.
  semaCtx.Properties.Reject(RejectProcedures)

  return fn()
}
```
</blockquote></details>

I like it, done.
___
*[`pkg/sql/sem/tree/type_check.go` line 1164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NsjnHzBCxEMCpN6MnNr:-NskEVNV2gBNfSoadV8K:b-we7uwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/abbd40ca5083adc69a6f812213e95d1be5939180/pkg/sql/sem/tree/type_check.go#L1164)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why do we restore the derived properties in this case? Isn't it important that expressions about this func know whether or not we encountered an aggregate, generator, or window func?
</blockquote></details>

These properties describe what we've seen in the ancestor expressions during type checking. When type-checking FuncExpr itself (i.e. the main "function") we need to use the original properties, but when type-checking any sub-expressions of FuncExpr (i.e. its descendants) we need to have properties be updated according to what FuncExpr wants. Restoring the properties after having type-checked a sub-expression gives us this behavior.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/procedure_params` line 19 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-Nsjp1fa2tafBjWOoo7w:-Nsk6Cc139Lr80eG7eu6:b-jje64l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea8505c2f13a554b4b2adc1640493259fddcb1f/pkg/ccl/logictestccl/testdata/logic_test/procedure_params#L19)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

interesting behavior, great find!
</blockquote></details>

This was mentioned in PG docs :)
___
*[`pkg/ccl/logictestccl/testdata/logic_test/procedure_params` line 64 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NsjwqXg9felMqNW3Suy:-Nsk6WwD96zTjN34ux50:bdxpfnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea8505c2f13a554b4b2adc1640493259fddcb1f/pkg/ccl/logictestccl/testdata/logic_test/procedure_params#L64)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Did you mean for this to be RETURN?
</blockquote></details>

This was an existing test that was added when we added the parser support that I didn't change. I think it's ok to keep this as is.
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_params` line 53 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-Nsk-Yjq2iZ4pQLcFDp5:-Nsk9_8v6z1b9iCZRxHB:bterlxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea8505c2f13a554b4b2adc1640493259fddcb1f/pkg/sql/logictest/testdata/logic_test/procedure_params#L53)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Isn't this still tested without adding an `empty` directive?
</blockquote></details>

Yes, but currently the logic test framework assumes that `query` directive always has non-optional `<type-string>` argument (like `IT` which specifies the types of the expected output), yet when no rows are produced, the DB driver tells us that 0 columns are created, so we get an error. I adjusted the change a bit to make `query empty` another variation of `query` directive (rather than an optional argument).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120029)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/catalog/schemadesc/schema_desc.go` line 565 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NskFqEVDkomMsrUctvy:-NskFqEVDkomMsrUctvz:bdtb7g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e7d14285656a9f6d491169fe8fd181d89a68ff8/pkg/sql/catalog/schemadesc/schema_desc.go#L565)):*
> ```Go
> 		overload.Types = paramTypes
> 		if sig.IsProcedure {
> 			// TODO(100405): if a procedure is created on 23.2 version, then it
> ```

What are your thoughts on this TODO? Do we care to preserve backwards-compatibility with procedures created on 23.2? I think currently due to this TODO, some procedure resolution that only uses IN parameters would be broken if the procedure was created on 23.2 - I'm guessing it's ok since the feature was only in preview, right?

Alternatively, we could probably write a simple migration to update the descriptors to populate this new field.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120029)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/catalog/schemadesc/schema_desc.go` line 565 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NskFqEVDkomMsrUctvy:-NskMu5E2X-zPb9fCm8x:b-yz52tc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e7d14285656a9f6d491169fe8fd181d89a68ff8/pkg/sql/catalog/schemadesc/schema_desc.go#L565)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

What are your thoughts on this TODO? Do we care to preserve backwards-compatibility with procedures created on 23.2? I think currently due to this TODO, some procedure resolution that only uses IN parameters would be broken if the procedure was created on 23.2 - I'm guessing it's ok since the feature was only in preview, right?

Alternatively, we could probably write a simple migration to update the descriptors to populate this new field.
</blockquote></details>

Hmm... would it be possible to instead add an `OutputTypes` field to the proto struct, and maintain that alongside `InputTypes`? Then, procedure could check both fields to determine the signature. Pre-existing procedure wouldn't have `OutputTypes` set, but they wouldn't need it anyway since they don't have OUT params. What do you think?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120029)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/catalog/schemadesc/schema_desc.go` line 565 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-NskFqEVDkomMsrUctvy:-NskOYV49tdE2Idml6EX:bnvk0gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e7d14285656a9f6d491169fe8fd181d89a68ff8/pkg/sql/catalog/schemadesc/schema_desc.go#L565)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Hmm... would it be possible to instead add an `OutputTypes` field to the proto struct, and maintain that alongside `InputTypes`? Then, procedure could check both fields to determine the signature. Pre-existing procedure wouldn't have `OutputTypes` set, but they wouldn't need it anyway since they don't have OUT params. What do you think?
</blockquote></details>

I'll think some more about it. Additionally, I now realize that the reason for why #119937 happens (where we return the incorrect error code when attempting to `CALL` a function) is that perhaps we don't want to include OUT parameters into the signature of a procedure by default, and only require OUT parameters being specified in the CALL invocation. If so, we might not need this new `InputTypes` field - I'll look into this tomorrow.

**Comment by yuzefovich** [comment]
Please ignore this PR for now - I'm working on an alternative approach.

**Comment by yuzefovich** [comment]
I refactored the fourth commit to have the same "signature" for both UDFs and procedures which simplified many things. This required some adjustment to the type-checking logic, but it seems cleaner overall to me. The only downside of this approach that I can see currently is what I called out in the slack - there is a minor deviation in how DROP PROCEDURE works when no parameter types specify the parameter class.

PTAL.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Looks great!

> Reviewed 1 of 3 files at r17, 1 of 2 files at r18, 18 of 28 files at r19, 15 of 15 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-:-Nssv8VF0UEWuAWR2-ZW:b-2t11ox)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/catalog/descpb/structured.proto` line 1574 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-Nssw1K2AwvdtmlMkuPp:-Nssw1K2AwvdtmlMkuPq:b-o1sxpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be8fd8bb2f387b4d37392f763918fe37f953324/pkg/sql/catalog/descpb/structured.proto#L1574)):*
> ```proto
>     // all parameters to their ordinal in ArgTypes - OUT parameters get a
>     // special value of -1.
>     repeated int32 to_input_param_ordinal = 6;
> ```

[nit] Have you considered tracking out param ordinals instead?  If we did that, pre-24.1 procedures would be no different from post-24.1, since the field would be unset for procs without out params. We could also use `intsets.Fast` in non-proto structs, which might simplify some things.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120029)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/catalog/descpb/structured.proto` line 1574 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-Nssw1K2AwvdtmlMkuPp:-NstTNCs2956lKWECH7P:basrui9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be8fd8bb2f387b4d37392f763918fe37f953324/pkg/sql/catalog/descpb/structured.proto#L1574)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Have you considered tracking out param ordinals instead?  If we did that, pre-24.1 procedures would be no different from post-24.1, since the field would be unset for procs without out params. We could also use `intsets.Fast` in non-proto structs, which might simplify some things.
</blockquote></details>

That's an interested idea. I just pushed an extra commit that implements it. The only downside is that we need to come up with "CALL param ordinal to input param ordinal" mapping (which is what I originally included in the proto) so that we can correctly access the input parameters for type checking - the current approach has complexity `P * O` where `P` is the total number of parameters and `O` is the number of OUT parameters in an overload. This seems acceptable. I probably lean towards using this idea - WDYT? If you like it too, I'll squash it into the fourth commit.

**Comment by DrewKimball** [comment]
>the current approach has complexity P * O where P is the total number of parameters and O is the number of OUT parameters in an overload. This seems acceptable. I probably lean towards using this idea - WDYT? If you like it too, I'll squash it into the fourth commit.

I think that's probably fine. We could also add some "RangeCount" method to `intsets.Fast`, that would probably work well.

Looking at it again though, I do have a question - why aren't we looking at OUT params as well for overload type checking? For example, what happens if I do this?
```
postgres=# create procedure p(out x int) language plpgsql as $$ begin x := 1; return; end $$;
CREATE PROCEDURE

postgres=# call p(null::text);
ERROR:  procedure p(text) does not exist
LINE 1: call p(null::text);
             ^
HINT:  No procedure matches the given name and argument types. You might need to add explicit type casts.
```

**Review by yuzefovich — COMMENTED** [review]
Ah, that's a good catch. The [docs](https://www.postgresql.org/docs/current/xfunc-sql.html#XFUNC-OUTPUT-PARAMETERS-PROC) do say that the OUT argument must be implicitly coercible to the specified type. I'll need to think a bit more then.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120029#-:-NsteFZI2cKCpssZ3RCY:bqponhd)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

**Comment by yuzefovich** [comment]
I'm currently thinking that my initial version was on the right path (that all parameters are included into the signature for procedures) and that I incorrectly introduced complexity about "DROP or REPLACE" context where only the procedure input parameters matter. I'll revive that approach, but since this PR has too many revisions already, I'll merge first 3 non-controversial commits and will open a new PR with the update.

TFTRs!

bors r+

**Pull request merged**
