### PR TITLE
Cube root implementation based on Ken Turkowski paper

### PR DESCRIPTION
**Pull request by bogdanbatog**
Part of #4311

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4776)

### CODE REVIEW

**Comment by tamird** [comment]
Looks like `gofmt`/`goimports` failed.

**Comment by nvanbenschoten** [comment]
Awesome, thanks for the help here @bogdanbatog! I just had a couple of comments. Also, make sure you are running `make check` before pushing changes, as that will catch issues with forgetting to run `gofmt/goimports`

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[util/decimal/const.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtJQQqrS9ebQmEN1ns:-KBtJQQrxFrldKadlMwN:-1010310990) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/const.go#L30)):*
We should be able to do `inf.NewDec(125, 3)` here.

---

*[util/decimal/const.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtJaC18hKBdG7FwKRu:-KBtJaC18hKBdG7FwKRv:-200097192) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/const.go#L56)):*
I'm a little wary of these magic numbers. Will they work with arbitrary scales?

Also, do you mind pulling out the string representations into constant strings (like `strE`) and adding a comment to them, preferably linking to where they are from and what their purpose is.

---

*[util/decimal/decimal.go, line 256 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtFaOEpldLIPvrPPRd:-KBtFaOEpldLIPvrPPRe:1938224374) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal.go#L256)):*
It doesn't look like we're actually saving an allocation if `z` is provided. Instead of allocating `r`, can we use `z` throughout the computation.

This will probably mean we need to handle the case when `z == x`. See how `Sqrt` handles that.

---

*[util/decimal/decimal.go, line 273 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtGBpKe_luvpol4Wyx:-KBtGBpKe_luvpol4Wyy:1851509145) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal.go#L273)):*
Can we link to the paper here? Also, we try to write all comments like sentences with correct capitalization and punctuation. See https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences.

---

*[util/decimal/decimal.go, line 277 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtH5EMjz02SrwbkISO:-KBtH5EMjz02SrwbkISP:533800703) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal.go#L277)):*
A comment like the paper has `/* 0.125 <= r < 1.0 */` would help explain this a little better.

---

*[util/decimal/decimal.go, line 305 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtHNnRlWWRIwJVlDQT:-KBtHNnS14OsAY3TuOn9:1068954415) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal.go#L305)):*
Delete?

---

*[util/decimal/decimal.go, line 312 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtKLKZIERLPAoLu9Yk:-KBtKLKZIERLPAoLu9Yl:-661870603) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal.go#L312)):*
These `QuoRound`s should probably use a slightly higher scale to avoid rounding errors during computation. Try `s+2`.

---

*[util/decimal/decimal_test.go, line 328 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtI-kiIdjKEINoqgs5:-KBtI-kiIdjKEINoqgs6:-1592146600) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal_test.go#L328)):*
Can we split this test into two that test scales `16` and `32` like the other tests?

---

*[util/decimal/decimal_test.go, line 345 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtI6UBYC9w6P7khWe_:-KBtI6UBYC9w6P7khWea:-1163638) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal_test.go#L345)):*
Do you mind adding a benchmark like `BenchmarkDecimalSqrt` and including the results in this PR?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-:-KBtJ-YChoKjtX7M0St7:-1117099850)*

**Comment by bogdanbatog** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[util/decimal/const.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtJQQqrS9ebQmEN1ns:-KBvfhRUihsgxUhulahH:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/const.go#L30)):*
Done.

---

*[util/decimal/const.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtJaC18hKBdG7FwKRu:-KBvjxaFnuMP_THltRN1:1505790629) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/const.go#L56)):*
The magic numbers are only used to estimate the initial approximation. Worst case, it will be a performance issue, not a correctness one. But the initial benchmark looks good, `Cbrt` is about 30% faster than `Sqrt`.

---

*[util/decimal/decimal.go, line 256 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtFaOEpldLIPvrPPRd:-KBvkYx42YXPP9_yAh6H:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal.go#L256)):*
Done.

---

*[util/decimal/decimal.go, line 273 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtGBpKe_luvpol4Wyx:-KBvk_YY9PvZLC6XYuOs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal.go#L273)):*
Done.

---

*[util/decimal/decimal.go, line 277 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtH5EMjz02SrwbkISO:-KBvkax9MUscuSfvol4B:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal.go#L277)):*
Done.

---

*[util/decimal/decimal.go, line 305 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtHNnRlWWRIwJVlDQT:-KBvkbYE99oXOaeRVsti:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal.go#L305)):*
Done.

---

*[util/decimal/decimal.go, line 312 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtKLKZIERLPAoLu9Yk:-KBvkc88EWYnfU7cPdqc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal.go#L312)):*
Done.

---

*[util/decimal/decimal_test.go, line 328 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtI-kiIdjKEINoqgs5:-KBvkd5jOUcX3vSWvdYz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal_test.go#L328)):*
Done.

---

*[util/decimal/decimal_test.go, line 345 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtI6UBYC9w6P7khWe_:-KBvkeO4vN0HQ25nxPDJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/decimal_test.go#L345)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776)*

**Comment by bogdanbatog** [comment]
Speed benchmark for `Cbrt`
```
BenchmarkDecimalMod 	 1000000	      1244 ns/op
BenchmarkDecimalSqrt	   50000	     31343 ns/op
BenchmarkDecimalLog 	   10000	    181436 ns/op
BenchmarkDecimalCbrt	   50000	     22977 ns/op
```

**Comment by guanqun** [comment]
Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[util/decimal/const.go, line 79 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBvtT10KwvfKQmLjKIu:-KBvtT10KwvfKQmLjKIv:-978016557) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/const.go#L79)):*
s/Coeficients/Coefficients  :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776)*

**Comment by nvanbenschoten** [comment]
Looks really good :+1: I think we're ready to push this once the spelling mistake gets cleaned up. Thanks again for the help!

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/decimal/const.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBtJaC18hKBdG7FwKRu:-KBx1DSetm5lrF_N9NYP:-1863361581) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ef4c153555004b8c8a020e2e84ae1784eab505e/util/decimal/const.go#L56)):*
Ok great, thanks for clearing that up.

Based on those numbers, it might make sense to go back in after this change and see if we can improve the initial approximation of `Sqrt`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-:-KBx2XtST37Ion9SETe-:-1217806387)*

**Comment by RaduBerinde** [comment]
LGTM, thanks for the change!  Just a couple of minor comments.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[util/decimal/decimal.go, line 274 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBx5VVLzH7PTMODt6Je:-KBx5VVLzH7PTMODt6Jf:-969704901) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/decimal.go#L274)):*
Add a comment explaining that `z = x * 8^ex`. Also could have a better name, maybe `exp8`.

---

*[util/decimal/decimal.go, line 291 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBx4oKMDdYLEgyoWrDe:-KBx4oKMDdYLEgyoWrDf:-425938705) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/decimal.go#L291)):*
approximate

---

*[util/decimal/decimal.go, line 292 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBx4weYpxZb8AHJJT-1:-KBx4weYpxZb8AHJJT-2:-890779599) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/decimal.go#L292)):*
[nit] can add a comment that this serves as a starting point and the accuracy of this only makes a difference performance-wise.

---

*[util/decimal/decimal.go, line 299 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBx5MXvh2ThQNHXmZFf:-KBx5MXvh2ThQNHXmZFg:-1909819849) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/decimal.go#L299)):*
`for ; ex < 0; ex++ {`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-:-KBx79yeg-2n3QJ-UTq9:1233880724)*

**Comment by RaduBerinde** [comment]
*[util/decimal/decimal.go, line 274 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBx5VVLzH7PTMODt6Je:-KBx7bMk_JVK9zdps204:-2056374378) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/decimal.go#L274)):*
Heh it's actually `x = z * 8^ex`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776)*

**Comment by bogdanbatog** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[util/decimal/const.go, line 79 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBvtT10KwvfKQmLjKIu:-KC-u214d8jnRGpLmEIu:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/const.go#L79)):*
Done.

---

*[util/decimal/decimal.go, line 274 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBx5VVLzH7PTMODt6Je:-KC0-6YKWVvcHYeUKEoK:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/decimal.go#L274)):*
Done.

---

*[util/decimal/decimal.go, line 291 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBx4oKMDdYLEgyoWrDe:-KC-tfLDZNLubFBSxR43:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/decimal.go#L291)):*
Done.

---

*[util/decimal/decimal.go, line 292 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBx4weYpxZb8AHJJT-1:-KC0-8MdTRZQZia1QjoX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/decimal.go#L292)):*
Done.

---

*[util/decimal/decimal.go, line 299 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-KBx5MXvh2ThQNHXmZFf:-KC-tsfZ1sIQnO4U1jJp:-1798764395) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb0938a888846e5aa2cf85f29fc6249a73f6187/util/decimal/decimal.go#L299)):*
Done. This could be implemented in log(exp8) steps or even O(1), but probably it's not worth the trouble.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776)*

**Comment by nvanbenschoten** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4776#-:-KC1ZEmrBwyXPHwpskQg:980077423)*

**Pull request merged**
