### PR TITLE
sql: restore a table in multiple txns

### PR DESCRIPTION
**Pull request by danhhz**
Also quiet an annoying log line.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9954)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/backup.go, line 375 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzJDjiuoTKqsr_Mw9u:-KTzJDjiuoTKqsr_Mw9v:b-idq74m) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L375)):*
> ```Go
> 	resultErr := struct {
> 		syncutil.Mutex
> 		err error
> ```

Does it make sense to use a multierror here?

---

*[pkg/sql/backup.go, line 397 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzJ2iIw33TZr0xLaYb:-KTzJ2iJ6LbOyHLYuQLR:bw7edf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L397)):*
> ```Go
> 					log.Error(ctx, err)
> 					resultErr.Lock()
> 					defer resultErr.Unlock()
> ```

Can we just put the unlock 3 lines down? No need for a defer.

---

*[pkg/sql/backup.go, line 414 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzJaAUtW7LFfaBMaW7:-KTzJaAUtW7LFfaBMaW8:b-w8oxwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L414)):*
> ```Go
> 	table.ID = newTableID
> 	return db.Txn(ctx, func(txn *client.Txn) error {
> 		// Pass the descriptors by value keep this idempotent.
> ```

grammar error, missing "to"?

---

*[pkg/sql/backup.go, line 426 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzKCaJwhl4wEAOsF4H:-KTzKCaJwhl4wEAOsF4I:b-v4gq8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L426)):*
> ```Go
> ) error {
> 	var err error
> 	if table.ParentID, err = getDescriptorID(txn, tableKey{name: database.Name}); err != nil {
> ```

Why can't we use the result from getDescriptorID above?

---

*[pkg/sql/backup.go, line 454 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzJy2AVekJRrhfjg6x:-KTzJy2AVekJRrhfjg6y:b135its) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L454)):*
> ```Go
> 	// Write the new descriptors. First the ID -> TableDescriptor for the new
> 	// table, then flip (or initialize) the name -> ID entry so any new queries
> 	// will use the new one. If there was an exiting table, it can now be
> ```

existing

---

*[pkg/sql/backup.go, line 540 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzHRF7MmMFxoS7tDAF:-KTzHRF7MmMFxoS7tDAG:b-5npb6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L540)):*
> ```Go
> 	}
> 
> 	// TODO(dan): This uses one giant transaction for the entire restore, which
> ```

Can remove this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/backup.go, line 409 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzKck1scujyjO1DLPP:-KTzKck1scujyjO1DLPQ:b-udhxl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L409)):*
> ```Go
> 	// All concurrent accesses have finished, we don't need the lock anymore.
> 	if resultErr.err != nil {
> 		return resultErr.err
> ```

Probably want a comment here about why we're ok just leaving the written but now forgotten data here. Or do a last-ditch attempt (without checking errors) to delete the range.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954)*

**Comment by paperstreet** [comment]
Thanks for the review! RFAL

---

Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/sql/backup.go, line 375 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzJDjiuoTKqsr_Mw9u:-KUIm5WtewnlNw_4dqkI:b-w3g9rb) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L375)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Does it make sense to use a multierror here?
</details>
how about this?

---

*[pkg/sql/backup.go, line 397 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzJ2iIw33TZr0xLaYb:-KUIlPqP3WL3DD4hyrJE:bua6vmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L397)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Can we just put the unlock 3 lines down? No need for a defer.
</details>
pick your reason : - ) 1) this is the pattern we use elsewhere 2) it's less cognitive overhead, once you see the defer, you can stop reading 3) this is resilient to the lines in the lock section changing and 4) we haven't seen this show up on a benchmarks, so it's premature optimization to worry about the defer

---

*[pkg/sql/backup.go, line 409 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzKck1scujyjO1DLPP:-KUIlP0w-seS_uwxiVez:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L409)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Probably want a comment here about why we're ok just leaving the written but now forgotten data here. Or do a last-ditch attempt (without checking errors) to delete the range.
</details>
Done.

---

*[pkg/sql/backup.go, line 414 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzJaAUtW7LFfaBMaW7:-KUIl2WS1yL5JoD7BS2s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L414)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> grammar error, missing "to"?
</details>
Done.

---

*[pkg/sql/backup.go, line 426 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzKCaJwhl4wEAOsF4H:-KUIlz6cH4pGB6MDUBOd:b-l4396t) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L426)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Why can't we use the result from getDescriptorID above?
</details>
Added a comment

---

*[pkg/sql/backup.go, line 454 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzJy2AVekJRrhfjg6x:-KUIl-S_4qnXz5O_OO91:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L454)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> existing
</details>
Done.

---

*[pkg/sql/backup.go, line 540 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KTzHRF7MmMFxoS7tDAF:-KUIkwZgvSv8bma72hKd:b6zrrkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff5892c57654380dcf2f6305c25df61cab49ad8/pkg/sql/backup.go#L540)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Can remove this.
</details>
Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-:-KUIoxXOQ8JRC6D6StmT:b-6sx6b6)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/backup.go, line 411 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KUJ7JO3mDSIfPuaz2eD:-KUJ7JO4PqkxqUV34TPD:b4x1usw) ([raw file](https://github.com/cockroachdb/cockroach/blob/63504eb0cbeb4ca6c95fcc3bd16799bfc5de9382/pkg/sql/backup.go#L411)):*
> ```Go
> 	// All concurrent accesses have finished, we don't need the lock anymore.
> 	if result.firstErr != nil {
> 		// This leaves the data that did get imported in case the user wants to
> ```

Is this comment accurate? It implies that the partial data here can be used for another attempt. But with another attempt new table IDs will be generated, so this data will remain unused. Or are we going to build a tool that can resume a failed restore without new table ids?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-:-KUJ9fnmCzjkZliVJEXS:bnfp4nl)*

**Comment by paperstreet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/backup.go, line 411 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954#-KUJ7JO3mDSIfPuaz2eD:-KUJC-foNa6EIp5ScVdk:b-1ewwr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/63504eb0cbeb4ca6c95fcc3bd16799bfc5de9382/pkg/sql/backup.go#L411)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Is this comment accurate? It implies that the partial data here can be used for another attempt. But with another attempt new table IDs will be generated, so this data will remain unused. Or are we going to build a tool that can resume a failed restore without new table ids?
</details>
Only the latter would really be "resuming". I don't think it's a priority, but seems like a reasonable tool to eventually build

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9954)*

**Pull request merged**
