### PR TITLE
sql: introduce EXPLAIN ANALYZE (PLAN)

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: introduce EXPLAIN ANALYZE (PLAN)

This change introduces a new variant of `EXPLAIN ANALYZE` which
executes the query and returns the execution plan (in the future,
annotated with stats from execution).

Note that `(PLAN)` is the default mode for the regular `EXPLAIN`.
Currently `EXPLAIN ANALYZE` defaults to `(DISTSQL)` mode, but we plan
to switch that default to the `(PLAN)` version once it is fully
implemented.

Release note (sql change): Added a new variant of explain: EXPLAIN
ANALYZE (PLAN).

#### sql: add planning and execution time to EXPLAIN ANALYZE (PLAN)

This commit adds planning and execution time as top-level fields in
EXPLAIN ANALYZE (PLAN). We also plumb a testing knob to allow these
fields to be deterministic in tests.

Release note: None

image

### CODE REVIEW

**Comment by awoods187** [comment]
So exciting!!

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56524)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/conn_executor_exec.go, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56524#-MLqwLUTEbBNA34n2pxm:-MLqwLUTEbBNA34n2pxn:b-pne655) ([raw file](https://github.com/cockroachdb/cockroach/blob/657ebdb71f5b6bf3eab489ae2981d6d82999c320/pkg/sql/conn_executor_exec.go#L351)):*
> ```Go
> 			ih.SetOutputMode(explainAnalyzeDebugOutput, explain.Flags{})
> 		} else {
> 			flags := explain.MakeFlags(&e.ExplainOptions)
> ```

Should we increment `sqltelemetry.ExplainAnalyzeUseCounter` here?
___
*[pkg/sql/exec_util.go, line 834 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56524#-MLqy3Ys860x02bcKiBS:-MLqy3Ys860x02bcKiBT:b-e27vtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/65197bfdcc681f385cdffc1a45710139d0793e51/pkg/sql/exec_util.go#L834)):*
> ```Go
> 	// EXPLAIN ANALYZE (PLAN) that can vary between runs (like elapsed times).
> 	// Should be set together with execinfra.TestingKnobs.DeterministicStats.
> 	DeterministicExplainAnalyze bool
> ```

Should we phase out `DeterministicStats` in favor of this one?
___
*[pkg/sql/instrumentation.go, line 302 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56524#-MLqzOomBNpsC85vUU8L:-MLqzOomBNpsC85vUU8M:b7bpod3) ([raw file](https://github.com/cockroachdb/cockroach/blob/65197bfdcc681f385cdffc1a45710139d0793e51/pkg/sql/instrumentation.go#L302)):*
> ```Go
> // planRows generates the plan tree as a list of strings (one for each line).
> // Used in explainAnalyzePlanOutput mode.
> func (ih *instrumentationHelper) planRows(phaseTimes *phaseTimes) []string {
> ```

nit: if this is only used for explain analyze, what do you think of renaming this method to `planRowsForExplainAnalyze` similar to `planStringForBundle` above?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56524#-:-MLsUdLX3-eSrrRn1OB2:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/conn_executor_exec.go, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56524#-MLqwLUTEbBNA34n2pxm:-MLsToaQAk66h4XvuW9j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/657ebdb71f5b6bf3eab489ae2981d6d82999c320/pkg/sql/conn_executor_exec.go#L351)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we increment `sqltelemetry.ExplainAnalyzeUseCounter` here?
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 834 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56524#-MLqy3Ys860x02bcKiBS:-MLsTppd2uajPjgcqJXK:b-v0lzs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/65197bfdcc681f385cdffc1a45710139d0793e51/pkg/sql/exec_util.go#L834)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we phase out `DeterministicStats` in favor of this one?
</blockquote></details>

I'd like there to be only one too, but they're knobs for different layers. I added a TODO for now.
___
*[pkg/sql/instrumentation.go, line 302 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56524#-MLqzOomBNpsC85vUU8L:-MLsU32i1-EV_ekgDgyN:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/65197bfdcc681f385cdffc1a45710139d0793e51/pkg/sql/instrumentation.go#L302)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: if this is only used for explain analyze, what do you think of renaming this method to `planRowsForExplainAnalyze` similar to `planStringForBundle` above?
</blockquote></details>

Good idea, done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56524#-:-MLw6iE25Db9dSz5nVfq:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Pull request merged**
