### PR TITLE
geo: store geo types as protobuf rather than ewkb

### PR DESCRIPTION
**Pull request by otan**
This commit changes the serialization of Geometry/Geography types as a
protobuf stored as `geopb.SpatialType`. The geopb.SpatialType
denormalizes the SRID and Shape, and later bounding boxes.

To facilitate this refactor, a number of changes have been made:
* `geo.NewGeo*` functions now take in `geopb.SpatialObject`s instead.
* `geo.Parse*` functions have become `geo.spatialObjectFrom*`, replaced
by `geo.ParseGeo*From*` such that SpatialObject is abit more hidden.
* `geo.NewGeo*FromUnvalidatedEWKB` has become `geo.ParseGeo*FromEWKBRaw`
to make the intention clearer than "unvalidated ewkb".

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geo.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6AbRhH9_aHCmb1B89_:-M6AbRhH9_aHCmb1B89a:byi4imy) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31f4111658a4285912e73d4f354ed009893d1/pkg/geo/geo.go#L30)):*
> ```Go
> // without doing any SRID based checks.
> // You most likely want SpatialObjectFromEWKB instead.
> func SpatialObjectFromEWKBRaw(in geopb.EWKB) (geopb.SpatialObject, error) {
> ```

will this be called from outside the package?
___
*[pkg/geo/geo.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6Abtqo608QPPtwxY5p:-M6Abtqo608QPPtwxY5q:b-71rv8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31f4111658a4285912e73d4f354ed009893d1/pkg/geo/geo.go#L95)):*
> ```Go
> 
> // MustGeometryFromEWKBRaw behaves as GeometryFromEWKBRaw, but panics if an error occurs.
> func MustGeometryFromEWKBRaw(ewkb geopb.EWKB) *Geometry {
> ```

MustBeGeometryFromEWKBRaw

(datum.go follows a similar style) 
___
*[pkg/geo/parse.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6AcaQD3h6kpzfEuCLQ:-M6AcaQD3h6kpzfEuCLR:b-q8o6dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31f4111658a4285912e73d4f354ed009893d1/pkg/geo/parse.go#L50)):*
> ```Go
> // SpatialObjectFromEWKBHex takes a given str assumed to be in EWKB hex and transforms it
> // into a SpatialObject.
> func SpatialObjectFromEWKBHex(str string, defaultSRID geopb.SRID) (geopb.SpatialObject, error) {
> ```

I prefer the original naming of these functions. The return type is sufficient to document what `Parse*()` is returning and these are parsing functions (and they live in `parse.go`)
___
*[pkg/geo/geopb/geopb.proto, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6AdMjg4Uc52DW9owiD:-M6AdMjg4Uc52DW9owiE:bn73j34) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31f4111658a4285912e73d4f354ed009893d1/pkg/geo/geopb/geopb.proto#L37)):*
> ```protobuf
> 
> // SpatialObject represents a serialization of a Geospatial type.
> message SpatialObject {
> ```

can you add a comment for ewkb and srid.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geo.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6AbRhH9_aHCmb1B89_:-M6AjnyZCWmg203IdrV4:b-892szy) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31f4111658a4285912e73d4f354ed009893d1/pkg/geo/geo.go#L30)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

will this be called from outside the package?
</blockquote></details>

Yeah - there are some cases this is desirable (e.g. avro.go)
___
*[pkg/geo/geo.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6Abtqo608QPPtwxY5p:-M6Ajqve3fxix2RHZGqM:bno8ucg) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31f4111658a4285912e73d4f354ed009893d1/pkg/geo/geo.go#L95)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

MustBeGeometryFromEWKBRaw

(datum.go follows a similar style) 
</blockquote></details>

I think datum.go is the style 'breaker' here - most places i've seen has `Must<X>` where <X> is original function name (go stdlib just has `Must` in front of the regexp stuff, template package has just `Must` instead of `New`). Happy to go either way, but prefer this naming.
___
*[pkg/geo/parse.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6AcaQD3h6kpzfEuCLQ:-M6AkZHQ6CUj_J8SGqUv:b-laq1sn) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31f4111658a4285912e73d4f354ed009893d1/pkg/geo/parse.go#L50)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I prefer the original naming of these functions. The return type is sufficient to document what `Parse*()` is returning and these are parsing functions (and they live in `parse.go`)
</blockquote></details>

My motivation behind changing the `Parse` naming is that the return type doesn't quite match what is being returned -- it kind of conflicts with `ParseGeometry` / `ParseGeography`, which is clearer. So thinking I prefer this.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geo.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6Abtqo608QPPtwxY5p:-M6Apnm5DpVuriXHBrgE:b-eo4sgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31f4111658a4285912e73d4f354ed009893d1/pkg/geo/geo.go#L95)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I think datum.go is the style 'breaker' here - most places i've seen has `Must<X>` where <X> is original function name (go stdlib just has `Must` in front of the regexp stuff, template package has just `Must` instead of `New`). Happy to go either way, but prefer this naming.
</blockquote></details>

Based on `$ git grep Must` what I mostly see are grammatically correct phrases like MustGetSQLCounter, MustParse, MustCompile, MustExist, so I would really prefer something like that -- it also makes the function name more self-documenting since one is not left wondering "must geometry what?"
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6AsX9G8kh7YqYhyJAC:-M6AsX9G8kh7YqYhyJAD:bqcrbgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/591c0ee45a0ccd8a97e29ffaa980863a1150b894/pkg/sql/sem/builtins/geo_builtins.go#L50)):*
> ```Go
> 	stringOverload1(
> 		func(_ *tree.EvalContext, s string) (tree.Datum, error) {
> 			g, err := geo.SpatialObjectFromEWKT(geopb.EWKT(s), geopb.DefaultGeometrySRID, geo.DefaultSRIDIsHint)
> ```

I overlooked this in an earlier review, but the refactoring in this PR raises the question on why any code outside `pkg/geo/...` should know about `SpatialObject` or these renamed parse functions, or details like `DefaultSRIDIsHint`/`DefaultSRIDShouldOverwrite`.
It also exposes the fact that we are using the same proto for both geography and geometry. 
The details of the geo implementation are starting to spread to other parts of the code base. Shouldn't these be functions like `geo.ParseGeometryFromWKT, geo.ParseGeometryFromEWKT, ...`?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geo.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6Abtqo608QPPtwxY5p:-M6BKf0D9a5HkJiuD62s:b295l1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31f4111658a4285912e73d4f354ed009893d1/pkg/geo/geo.go#L95)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Based on `$ git grep Must` what I mostly see are grammatically correct phrases like MustGetSQLCounter, MustParse, MustCompile, MustExist, so I would really prefer something like that -- it also makes the function name more self-documenting since one is not left wondering "must geometry what?"
</blockquote></details>

Ah, in a grammar sense. Ok, changes will be made.
___
*[pkg/geo/geopb/geopb.proto, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6AdMjg4Uc52DW9owiD:-M6BLP7k7lthE-z0M734:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31f4111658a4285912e73d4f354ed009893d1/pkg/geo/geopb/geopb.proto#L37)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment for ewkb and srid.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-M6AsX9G8kh7YqYhyJAC:-M6BKAmP7W3N126JHAr5:be6r68n) ([raw file](https://github.com/cockroachdb/cockroach/blob/591c0ee45a0ccd8a97e29ffaa980863a1150b894/pkg/sql/sem/builtins/geo_builtins.go#L50)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I overlooked this in an earlier review, but the refactoring in this PR raises the question on why any code outside `pkg/geo/...` should know about `SpatialObject` or these renamed parse functions, or details like `DefaultSRIDIsHint`/`DefaultSRIDShouldOverwrite`.
It also exposes the fact that we are using the same proto for both geography and geometry. 
The details of the geo implementation are starting to spread to other parts of the code base. Shouldn't these be functions like `geo.ParseGeometryFromWKT, geo.ParseGeometryFromEWKT, ...`?
</blockquote></details>

hnng yeah i was thinking about this whilst writing it. we can do that in this PR. my issue at the time was lots of code duplication.
We'll still expose SpatialObject from encoding/decoding though, at least for now...

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48181#-:-M6GxGD5DTlwNHmpGr3n:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
thanks!

bors r=sumeerbhola

**Pull request merged**
