### PR TITLE
c-deps: bump rocksdb to revert compaction snapshot refresh

### PR DESCRIPTION
**Pull request by ajkr**
Picks up cockroachdb/rocksdb#56.

Release justification: This feature can cause a corruption where keys
deleted by range tombstones reappear (see #38772 and #40213), so it's
important we revert it.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM

I think there are a number of bugs this fixes, such as #38772. Unclear which of those can be closed, though since they also run into problems with the replica ID fix @ajwerner is working on. Perhaps just add "See #38772" to the commit.

**Comment by ajkr** [comment]
Done.

**Comment by ajkr** [comment]
Looks unrelated:

```
[acceptance/gossip/restart] test artifacts and logs in: artifacts/acceptance/gossip/restart/run_1
	gossip.go:221,gossip.go:286,acceptance.go:69,test_runner.go:689: pq: result is ambiguous (error=unable to dial n4: breaker open [exhausted])
```

bors r+

**Pull request merged**
