### PR TITLE
sql: add a regression test for virtual table generation hang

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds a regression test for #99753 that verifies that virtual table generation doesn't hang when the worker goroutine returns the query canceled error.

Informs #99753

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Seems like a flake.

bors r+

**Comment by mgartner** [comment]
blathers backport 23.1.0

**Comment by mgartner** [comment]
Ignore the backport to 23.1.0 - didn't realize we were waiting for 23.1.1 for backporting this.

**Pull request merged**
