### PR TITLE
go.mod: bump Pebble to fa6015b124ab

### PR DESCRIPTION
**Pull request by jbowens**
Changes:

 * [`fa6015b1`](https://github.com/cockroachdb/pebble/commit/fa6015b1) db: reformat TestLevelIterSeek output
 * [`dc7dd36c`](https://github.com/cockroachdb/pebble/commit/dc7dd36c) db: tweak test tableNewIters implementations
 * [`2a5e6e9b`](https://github.com/cockroachdb/pebble/commit/2a5e6e9b) compaction: consolidate tombstone elision tests
 * [`28ba8053`](https://github.com/cockroachdb/pebble/commit/28ba8053) manifest: more accurate in-use key ranges
 * [`1d378656`](https://github.com/cockroachdb/pebble/commit/1d378656) db: better printing of bounds in TestCompactionInuseKeyRanges
 * [`d688abce`](https://github.com/cockroachdb/pebble/commit/d688abce) manifest: use UserKeyBounds for in use ranges
 * [`4f713577`](https://github.com/cockroachdb/pebble/commit/4f713577) github: automatically add storage team to PRs
 * [`dbdcab4f`](https://github.com/cockroachdb/pebble/commit/dbdcab4f) db: avoid levelIter's unnecessary opening of range deletion iterator
 * [`6fa3fe9d`](https://github.com/cockroachdb/pebble/commit/6fa3fe9d) db: support changing directions of exhausted levelIter
 * [`42de76ba`](https://github.com/cockroachdb/pebble/commit/42de76ba) db: fix levelIter tests to obey bounds
 * [`68aad6a2`](https://github.com/cockroachdb/pebble/commit/68aad6a2) compact: minor cleanup to iterator test
 * [`bfa84cab`](https://github.com/cockroachdb/pebble/commit/bfa84cab) compact: fix iterator test
 * [`032ddd40`](https://github.com/cockroachdb/pebble/commit/032ddd40) manifest: move CalculateInuseKeyRanges test
 * [`01000f24`](https://github.com/cockroachdb/pebble/commit/01000f24) manifest: rename intervalKey.isLargest
 * [`f460ac95`](https://github.com/cockroachdb/pebble/commit/f460ac95) db: simplify mergingIter direction switching
 * [`aa165e57`](https://github.com/cockroachdb/pebble/commit/aa165e57) manifest: fix LevelIterator.SeekGE semantics
 * [`7704193e`](https://github.com/cockroachdb/pebble/commit/7704193e) internal/keyspan: support interleaving end keys
 * [`22ee9c56`](https://github.com/cockroachdb/pebble/commit/22ee9c56) internal/keyspan: add InterleavingIterOpts field
 * [`f034c46e`](https://github.com/cockroachdb/pebble/commit/f034c46e) db: fix up a few more tests
 * [`b7e1a8ce`](https://github.com/cockroachdb/pebble/commit/b7e1a8ce) db: remove compaction.disableSpanElision
 * [`5bcf51bf`](https://github.com/cockroachdb/pebble/commit/5bcf51bf) internal/{arenaskl,batchskl}: adjust behavior at bounds
 * [`0be5a746`](https://github.com/cockroachdb/pebble/commit/0be5a746) db: add variants of memtable iterator benchmarks with bounds
 * [`85321d0b`](https://github.com/cockroachdb/pebble/commit/85321d0b) internal/batchskl: remove iterAdapter
 * [`e7c4ec2e`](https://github.com/cockroachdb/pebble/commit/e7c4ec2e) manifest: show iterator command in output
 * [`3a02db68`](https://github.com/cockroachdb/pebble/commit/3a02db68) manifest: fix some tests that have split keys
 * [`446a0811`](https://github.com/cockroachdb/pebble/commit/446a0811) db: move obsolete files code
 * [`f1311686`](https://github.com/cockroachdb/pebble/commit/f1311686) db: rename cleanup.go to obsolete_files.go
 * [`57ee5be2`](https://github.com/cockroachdb/pebble/commit/57ee5be2) sstable: remove ExternalFormatVersion
 * [`5b3f94f1`](https://github.com/cockroachdb/pebble/commit/5b3f94f1) db: minor cleanup of compaction code
 * [`a1e8dbd9`](https://github.com/cockroachdb/pebble/commit/a1e8dbd9) compact: move iterator arguments into a struct
 * [`36521833`](https://github.com/cockroachdb/pebble/commit/36521833) internal/keyspan: fix interleaving iter intermediary state
 * [`e751b780`](https://github.com/cockroachdb/pebble/commit/e751b780) internal/keyspan: refactor interleaving iterator tests
 * [`17a96020`](https://github.com/cockroachdb/pebble/commit/17a96020) db: extract level checker's handling of point keys
 * [`3cd41226`](https://github.com/cockroachdb/pebble/commit/3cd41226) db: update newIters callers to use new interface
 * [`cd567320`](https://github.com/cockroachdb/pebble/commit/cd567320) compact: move out compaction iterator
 * [`78b10dfd`](https://github.com/cockroachdb/pebble/commit/78b10dfd) compact: add Snapshots type
 * [`b62bb7f0`](https://github.com/cockroachdb/pebble/commit/b62bb7f0) base: move some test utils to base
 * [`e0c6d173`](https://github.com/cockroachdb/pebble/commit/e0c6d173) keyspan: remove no longer used Fragmenter code
 * [`a1a8d68e`](https://github.com/cockroachdb/pebble/commit/a1a8d68e) db: remove fragmenters from compactionIter

Release note: none.
Epic: none.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Review by itsbilal — APPROVED** [review]

**Comment by jbowens** [comment]
TFTRs!

bors r+

**Comment by jbowens** [comment]
This is blocked on some CI failures. I haven't had an opportunity to investigate yet

**Comment by jbowens** [comment]
```
dev test pkg/kv/kvserver/batcheval -f TestResolveLocalLocks
```

```
--- FAIL: TestResolveLocalLocks (0.01s)
    test_log_scope.go:170: test logs captured to: /tmp/cockroach/_tmp/534984b8b0c2420fd6951b9c0f160913/logTestResolveLocalLocks2472963276
    test_log_scope.go:81: use -show-logs to present logs inline
    --- FAIL: TestResolveLocalLocks/Ranged_locks_with_max_keys (0.00s)
        cmd_end_transaction_test.go:1667:
            	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_end_transaction_test.go:1667
            	Error:      	Not equal:
            	            	expected: 3
            	            	actual  : 5
            	Test:       	TestResolveLocalLocks/Ranged_locks_with_max_keys
    --- FAIL: TestResolveLocalLocks/Ranged_span_with_target_bytes (0.00s)
        cmd_end_transaction_test.go:1667:
            	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_end_transaction_test.go:1667
            	Error:      	Not equal:
            	            	expected: 3
            	            	actual  : 5
            	Test:       	TestResolveLocalLocks/Ranged_span_with_target_bytes
```

**Comment by RaduBerinde** [comment]
@jbowens I narrowed this down to 5bcf51bf internal/{arenaskl,batchskl}: adjust behavior at bounds

I posted https://github.com/cockroachdb/cockroach/pull/123247 that bumps master to the one before that commit for now.

**Comment by jbowens** [comment]
Nice, I'll close this one out.

**Pull request closed without merging**
