### PR TITLE
 build, ui: add font sourcing scripts

### PR DESCRIPTION
**Pull request by couchand**
Previously, we were relying on WOFF font files committed to
our repository, without information on the source.  This clears
up any licensing questions by sourcing the fonts from
Google and then scripting the conversion.

Fixes: #32568
Release note: None

### CODE REVIEW

**Comment by couchand** [comment]
@benesch I'm well aware that the makefile changes are a little brute force.  Happy to help clean it up if given pointers.

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32598#-:-LSG5J3aCjcN4GAwKOeq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[Makefile, line 1134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32598#-LSG4t0I22jMeaK5KUX_:-LSG4t0I22jMeaK5KUXa:b-9kyt7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/2417e31665b45580352d713d3e4a6035bf6a062c/Makefile#L1134)):*
> ```Makefile
> 	rm -rf pkg/ui/fonts/Lato
> 	rm -f pkg/ui/dist/fonts.zip
> 	curl 'https://fonts.google.com/download?family=Lato|Inconsolata' > pkg/ui/dist/fonts.zip
> ```

nit: `curl -fsSL` is our generally-accepted practice for scripting
___
*[Makefile, line 1145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32598#-LSG53FZ4TzHTa1_3CrA:-LSG53FZ4TzHTa1_3CrB:b-s5qwte) ([raw file](https://github.com/cockroachdb/cockroach/blob/2417e31665b45580352d713d3e4a6035bf6a062c/Makefile#L1145)):*
> ```Makefile
> 	rm -rf pkg/ui/fonts/Inconsolata
> 	rm -rf pkg/ui/fonts/Lato
> 	rm -f pkg/ui/dist/fonts.zip
> ```

My only request is that you package this all into a script (`scripts/font-gen`?) to avoid cluttering the Makefile. Otherwise I quite like how explicit this is.

**Review by couchand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32598)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[Makefile, line 1134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32598#-LSG4t0I22jMeaK5KUX_:-LSH8clE5p7dMXXYQ73H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2417e31665b45580352d713d3e4a6035bf6a062c/Makefile#L1134)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

nit: `curl -fsSL` is our generally-accepted practice for scripting
</blockquote></details>

Done.
___
*[Makefile, line 1145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32598#-LSG53FZ4TzHTa1_3CrA:-LSH8bcX4qQx-BMN9-m6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2417e31665b45580352d713d3e4a6035bf6a062c/Makefile#L1145)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

My only request is that you package this all into a script (`scripts/font-gen`?) to avoid cluttering the Makefile. Otherwise I quite like how explicit this is.
</blockquote></details>

Done.

**Comment by couchand** [comment]
Oh goodness, apparently the WOFF2 generation isn't deterministic:

```
17:35:55 ~/go/src/github.com/cockroachdb/cockroach/pkg/ui (chore/fonts+) $ git diff --cached --binary
diff --git a/pkg/ui/fonts/Inconsolata-Regular.woff2 b/pkg/ui/fonts/Inconsolata-Regular.woff2
index 1ebb0aa4df42df7923d8ec1450c4932222b621fd..bde78389a54e70cb21e93b8bb8ba086f9b4186d5 100644
GIT binary patch
delta 20
bcmZpf$=WiLbwWL>v9Xn@X=BUM7DgWcN}~qe

delta 20
bcmZpf$=WiLbwWL>k%g79Wn;_I7DgWcO4bJC

diff --git a/pkg/ui/fonts/Lato-Bold.woff2 b/pkg/ui/fonts/Lato-Bold.woff2
index 7dbf622af08b29c7f6e2e52e3e80bba2aaf46241..9152a09d6ff001caff272b5413e1404ade924ec4 100644
GIT binary patch
delta 18
acmcaGiTT1L<_QZ~jg75LO*bxEbpilL)(6x8

delta 18
acmcaGiTT1L<_QZ~jV!E;EjKP(bpilL{Ri3r

diff --git a/pkg/ui/fonts/Lato-Regular.woff2 b/pkg/ui/fonts/Lato-Regular.woff2
index c74da70b1f06de765e66f1ea60e783a710892cb6..6fe80e85376430fe17a97f48700720823d4cdd91 100644
GIT binary patch
delta 18
acmZ3yk$Le(<_XJLjg75LO*gLjejNZu#|R(*

delta 18
acmZ3yk$Le(<_XJLjV!E;EjO<DejNZu?g%CT

17:35:56 ~/go/src/github.com/cockroachdb/cockroach/pkg/ui (chore/fonts+) $ git diff --binary
diff --git a/pkg/ui/fonts/Inconsolata-Regular.woff2 b/pkg/ui/fonts/Inconsolata-Regular.woff2
index bde78389a54e70cb21e93b8bb8ba086f9b4186d5..afcfe85949da64c38c415e469ad6c9c8838468b0 100644
GIT binary patch
delta 19
acmZpf$=WiLbwUG+sg;pIW6RPOMjrq~^9H2=

delta 19
acmZpf$=WiLbwUG+v6ZQ5W6RPOMjrr08V0KX

diff --git a/pkg/ui/fonts/Lato-Bold.woff2 b/pkg/ui/fonts/Lato-Bold.woff2
index 9152a09d6ff001caff272b5413e1404ade924ec4..c8debfeb7a2ed40cf2d1b9c052cfcb61428e2b66 100644
GIT binary patch
delta 17
ZcmcaGiTT1L<_U{fOs$LzHZEIr0sunr2b%x@

delta 17
ZcmcaGiTT1L<_U{fjIB&fH!fRs0sun`2cZA}

diff --git a/pkg/ui/fonts/Lato-Regular.woff2 b/pkg/ui/fonts/Lato-Regular.woff2
index 6fe80e85376430fe17a97f48700720823d4cdd91..454c28a44bcfea75e6861e761faec5a9ff73bf45 100644
GIT binary patch
delta 17
ZcmZ3yk$Le(<_RlUOs$LzHm>=89RNZ12j>6)

delta 17
ZcmZ3yk$Le(<_RlUjIB&fH?H}99RNZS2kig=
```

Well that's not a showstopper but it is unfortunate.

**Review by knz — APPROVED** [review]
Thank you!

no comment further than what Nikhil said.

**Comment by couchand** [comment]
A convenient side-effect of this change that I just noticed is that the fonts go from being a non-trivial portion of our bundle to being completely trivial.  Hooray!

fonts-bundle-changes

**Pull request merged**
