### PR TITLE
server: use settings for updates and reporting url

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/server/updates.go, line 42 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-KiCdIMRVScErzoraGmW:-KiCdIMRVScErzoraGmX:bw9te7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d000d04a6e20103c8fda50a85bd88a5e523423/pkg/server/updates.go#L42)):*
> ```Go
> 
> var updatesURL = settings.RegisterStringSetting(
> 	"updatechecks.url",
> ```

why not prefix with diagnostics?

---

*[pkg/server/updates.go, line 158 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-KiCcmvY5v0vtKytbzlo:-KiCcmvY5v0vtKytbzlp:b65hgmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d000d04a6e20103c8fda50a85bd88a5e523423/pkg/server/updates.go#L158)):*
> ```Go
> 	defer span.Finish()
> 
> 	parsed, err := url.Parse(updatesURL.Get())
> ```

you forgot to do something with this error.

---

*[pkg/server/updates.go, line 264 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-KiCd5vJ1Xass_2UT7H7:-KiCd5vJ1Xass_2UT7H8:b-tfa83o) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d000d04a6e20103c8fda50a85bd88a5e523423/pkg/server/updates.go#L264)):*
> ```Go
> 	}
> 
> 	parsed, err := url.Parse(reportingURL.Get())
> ```

check this error?

---

*[pkg/server/updates.go, line 269 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-KiCd7aT-9fvLgIdF3KN:-KiCd7aT-9fvLgIdF3KO:b7vkjyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d000d04a6e20103c8fda50a85bd88a5e523423/pkg/server/updates.go#L269)):*
> ```Go
> 	q.Set("uuid", s.node.ClusterID.String())
> 	parsed.RawQuery = q.Encode()
> ```

remove this newline while you're here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233)*

**Comment by dt** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/updates.go, line 42 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-KiCdIMRVScErzoraGmW:-KiCh0PzZm9eYYWNLsIT:b-is3tzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d000d04a6e20103c8fda50a85bd88a5e523423/pkg/server/updates.go#L42)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not prefix with diagnostics?
</blockquote></details>

So far we've been distinguishing between sharing metrics about the cluster (capacity, usage, etc)  -- which we're standardizing on calling 'diagnostics' now -- and simply checking for updates e.g. the diagnostics reporting opt-in/opt-out doesn't affect update checks. Given that, I think it makes sense to use a separate prefix.

---

*[pkg/server/updates.go, line 158 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-KiCcmvY5v0vtKytbzlo:-KiCgeA2_UdqytNQ_5mw:byy1q1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d000d04a6e20103c8fda50a85bd88a5e523423/pkg/server/updates.go#L158)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

you forgot to do something with this error.
</blockquote></details>

Whoops, thanks.
Done.

---

*[pkg/server/updates.go, line 264 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-KiCd5vJ1Xass_2UT7H7:-KiCgfbd7mg4kxKrhTD-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d000d04a6e20103c8fda50a85bd88a5e523423/pkg/server/updates.go#L264)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

check this error?
</blockquote></details>

Done.

---

*[pkg/server/updates.go, line 269 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-KiCd7aT-9fvLgIdF3KN:-KiCgxht0MZ1TukdQI0n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d000d04a6e20103c8fda50a85bd88a5e523423/pkg/server/updates.go#L269)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove this newline while you're here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-:-KiCkbdSFObuH2U7dHs_:bnfp4nl)*

**Comment by dt** [comment]
TFTR!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-:-KiClpAZ6P1jJvHeQTr5:b-814g8k)*

**Comment by bdarnell** [comment]
Do these really make sense as settings? Users might want to turn off the checks, but there's no reason for them to change the URL. Our environment variables were hidden and undocumented for a reason; we don't want to expose things as settings just because we can. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-:-KiD1omsVsunPmX4nf3Y:b-7j0ach)*

**Comment by dt** [comment]
It seems like it might be nice to be able to point the diagnostics collector at a different URL -- e.g. if we later offer an on-prem diagnostics aggregator (for fire-walled deployments) ?

**Comment by bdarnell** [comment]
I think it makes more sense to wait to introduce the setting until we have a more concrete use case (or at least concrete plans to build one).

**Comment by knz** [comment]
Reviewed 2 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/updates.go, line 44 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233#-KiEv8zDHo4-RVmt6d_8:-KiEv8zEhGZ2LRjBI5Tm:b-1g2l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f1ba414c14c1be18b2428a0ea7af820ca09d4fa/pkg/server/updates.go#L44)):*
> ```Go
> 	"updatechecks.url",
> 	"URL of the check-for-updates endpoint",
> 	envutil.EnvOrDefaultString("COCKROACH_UPDATE_CHECK_URL", baseUpdatesURL),
> ```

Argh, I'm rather confident this is not what we want. I was thinking hard about this pattern the entire week and came to the conclusion it's a bad idea to use an env var as settings default. 
See https://github.com/cockroachdb/cockroach/issues/15242

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15233)*

**Comment by dt** [comment]
@bdarnell makes sense. #15244.

**Pull request merged**
