### PR TITLE
storage: Key RaftTransport stream by ReplicaIdent, not ReplicaDescriptor

### PR DESCRIPTION
**Pull request by bdarnell**
ReplicaDescriptor does not include the RangeID, so collisions were
possible and errors from one range could cause messages for another to
be dropped or delayed.

Discovered in #8111
Updates #7732

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8162)

### CODE REVIEW

**Comment by tamird** [comment]
I think you forgot to regenerate embedded.go in your first commit.

:lgtm:

---

Reviewed 8 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/raft_transport_test.go, line 113 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO20g3KUVlErSvLLN2_:-KO20g3KUVlErSvLLN2a:-427936065) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab1e317ba3f2b5078c4cce4f40a5a1e6cff3015/storage/raft_transport_test.go#L113)):*
> ```Go
> 	}
> 	transport := storage.NewRaftTransport(storage.GossipAddressResolver(rttc.gossip),
> 		grpcServer, rttc.nodeRPCContext)
> ```

nit: can you arrange this so that the final closing paren is indented inline with the line containing the opening paren? that probably means a trailing comma here.

---

*[storage/raft_transport_test.go, line 158 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO20uJ5qcLZ-bYMqghu:-KO20uJ5qcLZ-bYMqghv:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab1e317ba3f2b5078c4cce4f40a5a1e6cff3015/storage/raft_transport_test.go#L158)):*
> ```Go
> 				rttc.t.Fatal(err)
> 			}
> 		})
> ```

ditto

---

*[storage/raft_transport_test.go, line 65 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO21LhqPUbdXxnZ_0B1:-KO21LhqPUbdXxnZ_0B2:801930024) ([raw file](https://github.com/cockroachdb/cockroach/blob/a14988d882724361da8b36fdc83ff3366d167831/storage/raft_transport_test.go#L65)):*
> ```Go
> 	}
> 	if s.brokenRange != 0 && s.brokenRange == req.RangeID {
> 		return errors.Errorf("broken range")
> ```

this is a little too terse. it's so terse that i'm worried about it accidentally matching something unintended.

it's probably not possible to use a `var` here and compare directly, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-:-KO20QbfRw-uglAjCfjE:1816608104)*

**Comment by petermattis** [comment]
I didn't look at the test code, but the change to `raft_transport.go` :lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[roachpb/metadata.proto, line 52 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO2Dleg40l0oK9dGypb:-KO2Dleg40l0oK9dGypc:-2089319806) ([raw file](https://github.com/cockroachdb/cockroach/blob/a14988d882724361da8b36fdc83ff3366d167831/roachpb/metadata.proto#L52)):*
> ```protobuf
> 
> // ReplicaIdent uniquely identifies a specific replica.
> message ReplicaIdent {
> ```

Does this need to be a proto? We're never encoding it. Adding a `replicaIdent` struct in `storage/raft_transport.go` would be more localized and less (generated) code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-:-KO2EVCOFVr7S5YGOxbb:-2010622678)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[roachpb/metadata.proto, line 52 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO2Dleg40l0oK9dGypb:-KO2EmlZekYFKmt1tr0V:-552230450) ([raw file](https://github.com/cockroachdb/cockroach/blob/a14988d882724361da8b36fdc83ff3366d167831/roachpb/metadata.proto#L52)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Does this need to be a proto? We're never encoding it. Adding a `replicaIdent` struct in `storage/raft_transport.go` would be more localized and less (generated) code.
</details>
It's being made a proto in https://github.com/cockroachdb/cockroach/pull/7684 anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162)*

**Comment by bdarnell** [comment]
We need to hook embedded.go into `make protobuf`

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/raft_transport_test.go, line 113 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO20g3KUVlErSvLLN2_:-KO2inaAc_ciLIq9rltF:-926330240) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab1e317ba3f2b5078c4cce4f40a5a1e6cff3015/storage/raft_transport_test.go#L113)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: can you arrange this so that the final closing paren is indented inline with the line containing the opening paren? that probably means a trailing comma here.
</details>
Ew. Why? 

---

*[storage/raft_transport_test.go, line 65 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO21LhqPUbdXxnZ_0B1:-KO2iai4xDC0vUBSA7B0:1438733490) ([raw file](https://github.com/cockroachdb/cockroach/blob/a14988d882724361da8b36fdc83ff3366d167831/storage/raft_transport_test.go#L65)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is a little too terse. it's so terse that i'm worried about it accidentally matching something unintended.
> 
> it's probably not possible to use a `var` here and compare directly, right?
</details>
Made the message longer and extracted it to a string `const` (the original `error` object doesn't come through)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-:-KO2iXDtqH1vw9xgrrTo:135564556)*

**Comment by tamird** [comment]
`make protobuf` isn't supposed to be the silver bullet - `go generate ./...` is.

---

Reviewed 3 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/raft_transport_test.go, line 113 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO20g3KUVlErSvLLN2_:-KO2lotxY3WjoHcm1Gbm:-2006326554) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab1e317ba3f2b5078c4cce4f40a5a1e6cff3015/storage/raft_transport_test.go#L113)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Ew. Why? 
</details>
I don't feel strongly about the trailing comma, but the alignment of the close paren cues the end of the expression. In this particular case, I'd probably put each argument to `NewRaftTransport` on its own line, but if you feel strongly against that style (or the style I originally suggested) , I won't insist.

---

*[storage/raft_transport_test.go, line 67 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO2mtVh-6D0pOMwl3jd:-KO2mtVh-6D0pOMwl3je:-520454648) ([raw file](https://github.com/cockroachdb/cockroach/blob/e63a65ea4f3fc1f3e9b931b5f342b3a81183a2db/storage/raft_transport_test.go#L67)):*
> ```Go
> 	}
> 	if s.brokenRange != 0 && s.brokenRange == req.RangeID {
> 		return errors.Errorf(channelServerBrokenRangeMessage)
> ```

.New?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-:-KO2mO8SnZKqc-LvrSSt:1342906395)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/raft_transport_test.go, line 113 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO20g3KUVlErSvLLN2_:-KO4pxkHpKgdmhkfmaMH:1144297708) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab1e317ba3f2b5078c4cce4f40a5a1e6cff3015/storage/raft_transport_test.go#L113)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I don't feel strongly about the trailing comma, but the alignment of the close paren cues the end of the expression. In this particular case, I'd probably put each argument to `NewRaftTransport` on its own line, but if you feel strongly against that style (or the style I originally suggested) , I won't insist.
</details>
I'm fine (stylistically) with Ben's original code. We haven't insisted on any particular style for multi-line function calls. I don't see a good reason to start now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/raft_transport_test.go, line 67 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO2mtVh-6D0pOMwl3jd:-KO6RyTHuhkPC8l5sN68:101835658) ([raw file](https://github.com/cockroachdb/cockroach/blob/e63a65ea4f3fc1f3e9b931b5f342b3a81183a2db/storage/raft_transport_test.go#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> .New?
</details>
Could be, but not worth a CI cycle.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/raft_transport_test.go, line 67 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO2mtVh-6D0pOMwl3jd:-KO6SNGLzJpa6WUH533j:-1703843008) ([raw file](https://github.com/cockroachdb/cockroach/blob/e63a65ea4f3fc1f3e9b931b5f342b3a81183a2db/storage/raft_transport_test.go#L67)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Could be, but not worth a CI cycle.
</details>
Actually it looks like I have to update the branch anyway because of something just merged, so done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162)*

**Comment by tamird** [comment]
Reviewed 2 of 4 files at r7, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/raft_transport_test.go, line 67 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO2mtVh-6D0pOMwl3jd:-KO6YIAWbQEjokt3dehk:-650063418) ([raw file](https://github.com/cockroachdb/cockroach/blob/e63a65ea4f3fc1f3e9b931b5f342b3a81183a2db/storage/raft_transport_test.go#L67)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Actually it looks like I have to update the branch anyway because of something just merged, so done.
</details>
I'm not seeing it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport_test.go, line 67 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162#-KO2mtVh-6D0pOMwl3jd:-KO6bzHL_7lC-XP_jTp-:895808811) ([raw file](https://github.com/cockroachdb/cockroach/blob/e63a65ea4f3fc1f3e9b931b5f342b3a81183a2db/storage/raft_transport_test.go#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm not seeing it?
</details>
Oops, I got distracted by a merge conflict and forgot to actually make the change after writing that. Oh well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8162)*

**Pull request merged**
