### PR TITLE
scripts/drtprod: add side-eye agent setup script

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Thank you for doing it!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123069#-:-NwLbcD551FQRHl3cdFN:b-j1xque)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @sudomateo)

___
*[`scripts/drtprod` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123069#-NwLbCn06Deu950b9YJw:-NwLbCn18cmXewlGLqtL:bjwlwho) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ef15096dacc13fbbb1bc389a494d74e23a2bf5/scripts/drtprod#L60)):*
> ```
>     roachprod ssh $cluster -- "curl https://sh.exray.dev/ | sh -s - -t ${key}"
>     echo "configuring side-eye on $cluster..."
>     roachprod ssh $cluster -- "sudo snap set exray-agent environment=${cluster} && sudo snap restart exray-agent"
> ```

I've made it so that the environment and token can be passed in via environment variables which is a bit clearer and I've updated the URLs. Try this:

```
roachprod ssh $cluster -- "curl https://sh.side-eye.io/ | SIDE_EYE_API_TOKEN=${key} SIDE_EYE_ENVIRONMENT=${cluster} sh"
```

**Review by sudomateo — CHANGES_REQUESTED** [review]
Installation looks good. Just one requested change on the conditional check for a key.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123069#-:-NwLhNTCDsggc8xsEgNT:b-4ou2rp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[`scripts/drtprod` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123069#-NwLhBgfBHAwj0fUKqe8:-NwLhBgfBHAwj0fUKqe9:b-exjjnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ef15096dacc13fbbb1bc389a494d74e23a2bf5/scripts/drtprod#L55)):*
> ```
>     key="$(gcloud secrets versions access latest --secret='side-eye-key')"
>     if [[ -z "${key}" ]]; then
>       echo "no key"
> ```

We should exit non-zero if we don't have a key to abandon execution.



_Suggestion:_
```
      echo "no key"
      exit 1
```

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123069)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @sudomateo)

___
*[`scripts/drtprod` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123069#-NwLhBgfBHAwj0fUKqe8:-NwM2vQi4PwlN0Gn9Li4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ef15096dacc13fbbb1bc389a494d74e23a2bf5/scripts/drtprod#L55)):*
<details><summary><i>Previously, sudomateo (Matthew Sanabria) wrote…</i></summary><blockquote>

We should exit non-zero if we don't have a key to abandon execution.
</blockquote></details>

Done.
___
*[`scripts/drtprod` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123069#-NwLbCn06Deu950b9YJw:-NwM2vcf-egYt4muVsP9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26ef15096dacc13fbbb1bc389a494d74e23a2bf5/scripts/drtprod#L60)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I've made it so that the environment and token can be passed in via environment variables which is a bit clearer and I've updated the URLs. Try this:

```
roachprod ssh $cluster -- "curl https://sh.side-eye.io/ | SIDE_EYE_API_TOKEN=${key} SIDE_EYE_ENVIRONMENT=${cluster} sh"
```
</blockquote></details>

Done.

**Review by sudomateo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123069#-:-NwM39TrCmj04OKGpiHN:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
