### PR TITLE
asim: rework gossip component

### PR DESCRIPTION
**Pull request by kvoli**
This series of commits reworks the gossip component in `asim` to more accurately reflect reality. See individual commit messages.

part of #83990 

Release note: None

### CODE REVIEW

**Review by AlexTalks — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93945)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @nvanbenschoten)

___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJq_5oh2Rd8iXt-pTXV):*
This `store.go / store_gossip.go` split is a good initial separation, though I wonder if further logical separation might be even better? (Perhaps not now, but it may be worth a `TODO`).
E.g. something like

```
type StoreGossip struct {
  cfg StoreConfig
  ...other things needed by StoreGossip...
}

...

type Store struct {
  StoreGossip
  ...rest of store...
}
```

Right now these are likely too tightly coupled for this I think, however.
___
*[`pkg/kv/kvserver/store_gossip.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqYmnx7uRX6mojkU8_:-NJqYmnx7uRX6mojkU8a:bwfeg8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/196c421cfdfb54e828f17d6e65baf079dec24a34/pkg/kv/kvserver/store_gossip.go#L16)):*
> ```Go
> 	"context"
> 	fmt "fmt"
> 	math "math"
> ```

nit: why are these aliases necessary?



_Code quote:_
```Go
	fmt "fmt"
	math "math"
```
___
*[`pkg/kv/kvserver/store_gossip.go` line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqa85q-uParMvE3F-B:-NJqa85q-uParMvE3F-C:b948bgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ec698739d644689fd418bc60df2de91a1bae581/pkg/kv/kvserver/store_gossip.go#L40)):*
> ```Go
> 	DefaultGossipWhenCapacityDeltaExceedsFraction = 0.05
> 
> 	//GossipWhenLeaseCountDeltaExceeds specifies the absolute change from the
> ```

nit: formatting
___
*[`pkg/kv/kvserver/store_gossip.go` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqaAYt-5BpeKdCOy9f:-NJqaAYt-5BpeKdCOy9g:b948bgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ec698739d644689fd418bc60df2de91a1bae581/pkg/kv/kvserver/store_gossip.go#L52)):*
> ```Go
> 	GossipWhenRangeCountDeltaExceeds = 10
> 
> 	//GossipWhenLoadDeltaExceedsFraction specifies the fraction from the last
> ```

nit: formatting
___
*[`pkg/kv/kvserver/store_gossip.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqamnIC4jD1ngcZvTJ:-NJqamnIC4jD1ngcZvTK:b4elswn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ec698739d644689fd418bc60df2de91a1bae581/pkg/kv/kvserver/store_gossip.go#L310)):*
> ```Go
> 
> 	const minAbsoluteChange = 100
> 	updateForQPS := (newQPS < oldQPS*GossipWhenLoadDeltaExceedsFraction || newQPS > oldQPS*(1+GossipWhenLoadDeltaExceedsFraction)) &&
> ```

It might be more readable to wrap this calculation in a function, for use for QPS and WPS.
___
*[`pkg/kv/kvserver/asim/gossip/gossip.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqcPZ_0dNX8fTMZI_Z:-NJqcPZ_0dNX8fTMZI__:banx725) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/gossip.go#L29)):*
> ```Go
> 	// Tick checks for completed gossip updates and triggers new gossip
> 	// updates if needed.
> 	Tick(time.Time, state.State)
> ```

It might be nice if there was a single asim Ticker interface that was uniform, I.e.
```
type Ticker interface {
  Tick(ctx context.Context, tick time.Time, s state.State)
}
```
If that makes sense to do now, that would be great, but at least it would be good to follow the same interface as the other Tick functions I'd guess, no?
___
*[`pkg/kv/kvserver/asim/gossip/gossip.go` line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqcq1_6W2vjQ92JTKw:-NJqcq1_6W2vjQ92JTKx:bx8o5bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/gossip.go#L35)):*
> ```Go
> }
> 
> type storeGossip struct {
> ```

nit: Comment.
___
*[`pkg/kv/kvserver/asim/gossip/gossip.go` line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqcvLT5JJB7C0WW4Vm:-NJqcvLT5JJB7C0WW4Vn:byybf3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/gossip.go#L47)):*
> ```Go
> }
> 
> func newStoreGossip(settings *config.SimulationSettings) *storeGossip {
> ```

Any reason for a separate function?  If it's so `newStoreGossip(..)` can return a pointer to the concrete type for use in tests, why not just return the pointer from the `NewStoreGossip` exported method, as you can still ensure the compiler checking for interface conformity with `var _ Gossip = &storeGossip{}` ?
___
*[`pkg/kv/kvserver/asim/gossip/gossip.go` line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqd_Xa3S5Z7cANTUiE:-NJqd_Xa3S5Z7cANTUiF:b-j88onl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/gossip.go#L123)):*
> ```Go
> }
> 
> func (g *storeGossip) shouldGossipOnCapacityChange(s state.State, storeID state.StoreID) bool {
> ```

Shouldn't this function reuse code from `store_gossip.go` so we don't duplicate the same logic here?  The same should likely go for `shouldGossipOnInterval`...
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqeMcg9v4E8m4jcv6L:-NJqeMcg9v4E8m4jcv6M:bkb5gds) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/state/impl.go#L174)):*
> ```Go
> 
> // StoreDescriptors returns the descriptors for all stores that exist in
> // this state.
> ```

I realize this was preexisting, but shouldn't the comment (or function name) describe that this function actually mutates the state with `s.updateStoreCapacity(storeID)`?
___
*[`pkg/kv/kvserver/asim/gossip/exchange.go` line 22 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqbWb32wlw9Lkm9JK1:-NJqbWb32wlw9Lkm9JK2:b-liewgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/exchange.go#L22)):*
> ```Go
> )
> 
> type exchangeInfo struct {
> ```

Comment this, as well as the other uncommented structs/functions in this file.
___
*[`pkg/kv/kvserver/asim/gossip/exchange.go` line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqc1rq0PYb2ROn0gNA:-NJqc1rq0PYb2ROn0gNB:b-7he2gz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/exchange.go#L52)):*
> ```Go
> // given tick.
> func makeStoreDetail(desc *roachpb.StoreDescriptor, tick time.Time) *storepool.StoreDetail {
> 	detail := storepool.StoreDetail{}
> ```

nit: why not fill in the values below in the struct initialization?

**Comment by kvoli** [comment]
Thanks for the review, I'll add in those changes tomorrow.

Re the ticker - it might be time. There's a todo for it that has been sitting for some time.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93945)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @nvanbenschoten)

___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJq_5oh2Rd8iXt-pTXV):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

This `store.go / store_gossip.go` split is a good initial separation, though I wonder if further logical separation might be even better? (Perhaps not now, but it may be worth a `TODO`).
E.g. something like

```
type StoreGossip struct {
  cfg StoreConfig
  ...other things needed by StoreGossip...
}

...

type Store struct {
  StoreGossip
  ...rest of store...
}
```

Right now these are likely too tightly coupled for this I think, however.
</blockquote></details>

I think so too, i've added a  TODO here.
___
*[`pkg/kv/kvserver/store_gossip.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqYmnx7uRX6mojkU8_:-NJuNWH_11DuUrVB3EXL:bmejfwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/196c421cfdfb54e828f17d6e65baf079dec24a34/pkg/kv/kvserver/store_gossip.go#L16)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: why are these aliases necessary?
</blockquote></details>

Not necessary, editor malfunction  - fixed.
___
*[`pkg/kv/kvserver/store_gossip.go` line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqa85q-uParMvE3F-B:-NJuNj_Z10rIvyOHoYmN:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ec698739d644689fd418bc60df2de91a1bae581/pkg/kv/kvserver/store_gossip.go#L40)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: formatting
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/store_gossip.go` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqaAYt-5BpeKdCOy9f:-NJuNkKU-oKd_ue83jXq:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ec698739d644689fd418bc60df2de91a1bae581/pkg/kv/kvserver/store_gossip.go#L52)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: formatting
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/store_gossip.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqamnIC4jD1ngcZvTJ:-NKKWybb5Mv-fmS6gaiE:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ec698739d644689fd418bc60df2de91a1bae581/pkg/kv/kvserver/store_gossip.go#L310)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

It might be more readable to wrap this calculation in a function, for use for QPS and WPS.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/gossip/gossip.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqcPZ_0dNX8fTMZI_Z:-NKKXuWvE0TV7bqzRBl0:b32azvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/gossip.go#L29)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

It might be nice if there was a single asim Ticker interface that was uniform, I.e.
```
type Ticker interface {
  Tick(ctx context.Context, tick time.Time, s state.State)
}
```
If that makes sense to do now, that would be great, but at least it would be good to follow the same interface as the other Tick functions I'd guess, no?
</blockquote></details>

Updated to follow a more uniform interface.
___
*[`pkg/kv/kvserver/asim/gossip/gossip.go` line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqcq1_6W2vjQ92JTKw:-NKKYs9fDQK_41XOqpaS:b-7tfmjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/gossip.go#L35)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: Comment.
</blockquote></details>

added
___
*[`pkg/kv/kvserver/asim/gossip/gossip.go` line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqcvLT5JJB7C0WW4Vm:-NKKYt-IEkDn-Hqgnmnk:b-cypxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/gossip.go#L47)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Any reason for a separate function?  If it's so `newStoreGossip(..)` can return a pointer to the concrete type for use in tests, why not just return the pointer from the `NewStoreGossip` exported method, as you can still ensure the compiler checking for interface conformity with `var _ Gossip = &storeGossip{}` ?
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/asim/gossip/gossip.go` line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqd_Xa3S5Z7cANTUiE:-NKKYvYnDYalQ8t-t9Lb:b-e57dd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/gossip.go#L123)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Shouldn't this function reuse code from `store_gossip.go` so we don't duplicate the same logic here?  The same should likely go for `shouldGossipOnInterval`...
</blockquote></details>

That's a fair point. I've refactored the methods to use the underlying store_gossip here.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqeMcg9v4E8m4jcv6L:-NKKZ3I45zQilx0c1fA8:b4j6cwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/state/impl.go#L174)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

I realize this was preexisting, but shouldn't the comment (or function name) describe that this function actually mutates the state with `s.updateStoreCapacity(storeID)`?
</blockquote></details>

Updated.gg
___
*[`pkg/kv/kvserver/asim/gossip/exchange.go` line 22 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqbWb32wlw9Lkm9JK1:-NKKXahL9eSWkbkYu9ba:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/exchange.go#L22)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Comment this, as well as the other uncommented structs/functions in this file.
</blockquote></details>

done
___
*[`pkg/kv/kvserver/asim/gossip/exchange.go` line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NJqc1rq0PYb2ROn0gNA:-NKKXsiG2dQQ7vyW1GNf:b-cypxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ff531aa8e4e94363042bc4823a4cded07a88a4/pkg/kv/kvserver/asim/gossip/exchange.go#L52)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: why not fill in the values below in the struct initialization?
</blockquote></details>

updated.

**Review by AlexTalks — CHANGES_REQUESTED** [review]
Had a couple (mostly minor) comments here, I think this is mostly looking good though!

> Reviewed 15 of 15 files at r4, 24 of 24 files at r5, 15 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-:-NL9JSj0EzeFhUw2LQ-8:be1aatg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/store_gossip.go` line 77 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL98zEy5yvc8McMdiY2:-NL98zEy5yvc8McMdiY3:b-n23gxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L77)):*
> ```Go
> // to gossip accordingly.
> //
> // TODO(kvoli): Refactor this function to sit on the store gossip struct,
> ```

tiny nit: could use the term `StoreGossip` to be more precise.
___
*[`pkg/kv/kvserver/store_gossip.go` line 247 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL999rB1LmEoItVw1sE:-NL999rB1LmEoItVw1sF:bs0nsft) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L247)):*
> ```Go
> }
> 
> // StoreGossipTestingKnobs... TODO(kvoli):
> ```

nit: add minor comment here.
___
*[`pkg/kv/kvserver/store_gossip.go` line 268 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL99IXC2iwLX6dlIiij:-NL99IXC2iwLX6dlIiik:b-nt5fki) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L268)):*
> ```Go
> func DefaultStoreGossipTestingKnobs() StoreGossipTestingKnobs {
> 	return StoreGossipTestingKnobs{
> 		GossipWhenCapacityDeltaExceedsFraction: defaultGossipWhenCapacityDeltaExceedsFraction,
> ```

Shouldn't testing knobs be entirely overrides, such that a zero-value `TestingKnobs` struct has no effect?  It seems bad to incorporate a non-zero default value like `GossipWhenCapacityDeltaExceedsFraction: defaultGossipWhenCapacityDeltaExceedsFraction`, as that seems more like a config than a testing knob.  

I realize that the existing `GossipWhenCapacityDeltaExceedsFraction` is a testing knob that gets set with exactly this default value, but it seems like an anti-pattern to me.  Let me know if you feel differently.
___
*[`pkg/kv/kvserver/store_gossip.go` line 306 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9ALcxA66_fY4FLRKU:-NL9ALcxA66_fY4FLRKV:b-yv74uy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L306)):*
> ```Go
> }
> 
> // StoreDescriptorGetter provides a method to access the store descriptor.
> ```

minor: feel free to ignore this comment, but maybe `StoreDescriptorResolver` or `StoreDescriptorProvider`?
___
*[`pkg/kv/kvserver/store_gossip.go` line 314 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9BCCZ6oeUlICf3y9W:-NL9BCCZ6oeUlICf3y9X:b-bw2zix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L314)):*
> ```Go
> 
> // GossipInfoAdder provides a method to add a message to gossip.
> type GossipInfoAdder interface {
> ```

nit: Maybe it wouldn't be terrible to incorporate `AddInfo` to the interface and call it `Gossiper` or `InfoGossiper`?  Also, it would be great to apply these interfaces to the existing structs, e.g. `var _ InfoGossiper = &Gossip{}`, to help enforce interface conformance?  (This might be just helpful for GoLand users!)
___
*[`pkg/kv/kvserver/store_gossip.go` line 351 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9DC4lAy62qpz5qBmf:-NL9DC4lAy62qpz5qBmg:bk5mcr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L351)):*
> ```Go
> 	// block direct calls to GossipStore, rather capacity triggered gossip
> 	// outlined in the methods below.
> 	s.gossipOngoing.Set(true)
> ```

This seems better, I assume this is to avoid the race case we discussed?  Would using a `singleflight.Group` help at all here?  (I assume possibly not because you don't want to block direct `GossipStore(..)` calls...)
___
*[`pkg/kv/kvserver/store_gossip.go` line 421 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9ENI2-e5b2s0Sxgcg:-NL9ENI2-e5b2s0Sxgch:buqf9jx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L421)):*
> ```Go
> 
> 	if shouldGossip, reason := s.shouldGossipOnCapacityDelta(); shouldGossip {
> 		if s.gossipOngoing.Get() {
> ```

Why is it needed to check `gossipOngoing` each time (here and elsewhere) if it's also checked in `shouldGossipOnCapacityDelta()`?  It would seem to make more sense to keep the logic on if you should gossip or not encapsulated there.

(Also, if the answer is that the value might become out of date by the time the `cachedCapacity` lock is obtained there, why not just perform the check after obtaining the lock, or using a `RWMutex`?)
___
*[`pkg/kv/kvserver/store_gossip.go` line 500 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9FRFh5yXy9MYUZ_Re:-NL9FRFh5yXy9MYUZ_Rf:b-p4kuca) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L500)):*
> ```Go
> // returning true if the delta exceeds the threshold to gossip.
> func deltaExceedsThreshold(
> 	old, new, requiredMinDelta, requiredDeltaFraction float64,
> ```

nit: `new` seems like a bad keyword to use, does our linter allow this?
___
*[`pkg/kv/kvserver/asim/gossip/gossip.go` line 72 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9HwQI7d87j2Tc6T4K:-NL9HwQLAY5jVH98XcVz:b-955zj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/132bab832202c6f2a3a95adf0d34379a23d2b103/pkg/kv/kvserver/asim/gossip/gossip.go#L72)):*
> ```Go
> // if info couldn't be added.
> func (sg *storeGossiper) AddInfoProto(key string, msg protoutil.Message, ttl time.Duration) error {
> 	desc, ok := msg.(*roachpb.StoreDescriptor)
> ```

nit: this'll panic if you just do `desc := msg.(*roachpb.StoreDescriptor)` and have the wrong type (you don't need to change this if you don't want to, just mentioning)

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93945)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @kvoli)

___
*[`pkg/kv/kvserver/store_gossip.go` line 77 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL98zEy5yvc8McMdiY2:-NLNgWXM4C0MUhvi7hDq:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L77)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

tiny nit: could use the term `StoreGossip` to be more precise.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/store_gossip.go` line 247 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL999rB1LmEoItVw1sE:-NLNggTB71HrL6OEZ3I0:b-t948zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L247)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: add minor comment here.
</blockquote></details>

added.
___
*[`pkg/kv/kvserver/store_gossip.go` line 268 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL99IXC2iwLX6dlIiij:-NLNi4ezBsetW_RUfM3p:b-ipx8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L268)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Shouldn't testing knobs be entirely overrides, such that a zero-value `TestingKnobs` struct has no effect?  It seems bad to incorporate a non-zero default value like `GossipWhenCapacityDeltaExceedsFraction: defaultGossipWhenCapacityDeltaExceedsFraction`, as that seems more like a config than a testing knob.  

I realize that the existing `GossipWhenCapacityDeltaExceedsFraction` is a testing knob that gets set with exactly this default value, but it seems like an anti-pattern to me.  Let me know if you feel differently.
</blockquote></details>

Updated to be an override that is checked but defaults to 0.
___
*[`pkg/kv/kvserver/store_gossip.go` line 306 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9ALcxA66_fY4FLRKU:-NLNk6WoC5d8OEb100YF:b7wa5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L306)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

minor: feel free to ignore this comment, but maybe `StoreDescriptorResolver` or `StoreDescriptorProvider`?
</blockquote></details>

Updated to `StoreDescriptorProvider`.
___
*[`pkg/kv/kvserver/store_gossip.go` line 314 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9BCCZ6oeUlICf3y9W:-NLNkyz89kq4ySvv-Ezq:b-7frje0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L314)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: Maybe it wouldn't be terrible to incorporate `AddInfo` to the interface and call it `Gossiper` or `InfoGossiper`?  Also, it would be great to apply these interfaces to the existing structs, e.g. `var _ InfoGossiper = &Gossip{}`, to help enforce interface conformance?  (This might be just helpful for GoLand users!)
</blockquote></details>

I applied the interfaces to the existing structs. 

The `AddInfo` method isn't being used in the refactor so I opted not to add it.
___
*[`pkg/kv/kvserver/store_gossip.go` line 351 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9DC4lAy62qpz5qBmf:-NLNlWkF9vW0UL0X9oXf:b5zb0ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L351)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

This seems better, I assume this is to avoid the race case we discussed?  Would using a `singleflight.Group` help at all here?  (I assume possibly not because you don't want to block direct `GossipStore(..)` calls...)
</blockquote></details>

That's right -  I don't want to block direct calls, only prevent calling AsyncGossip when there is an inflight gossip request.
___
*[`pkg/kv/kvserver/store_gossip.go` line 421 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9ENI2-e5b2s0Sxgcg:-NLNm5rsASCAQb3qhXvw:bvl6vkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L421)):*
> Why is it needed to check gossipOngoing each time (here and elsewhere) if it's also checked in shouldGossipOnCapacityDelta()?  It would seem to make more sense to keep the logic on if you should gossip or not encapsulated there.

It was a small optimization / slight fear of the above. I don't think it is a serious risk - moved to just the single call.
___
*[`pkg/kv/kvserver/store_gossip.go` line 500 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9FRFh5yXy9MYUZ_Re:-NLNmeob2qZ3LN46vFOs:b9fb0dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbab4f17e7da66ce53b4b728dbbf56fa48df2b26/pkg/kv/kvserver/store_gossip.go#L500)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: `new` seems like a bad keyword to use, does our linter allow this?
</blockquote></details>

It does, updated to cur.
___
*[`pkg/kv/kvserver/asim/gossip/gossip.go` line 72 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-NL9HwQI7d87j2Tc6T4K:-NLNnSbhDCuUwzeTYk2A:b6jiljm) ([raw file](https://github.com/cockroachdb/cockroach/blob/132bab832202c6f2a3a95adf0d34379a23d2b103/pkg/kv/kvserver/asim/gossip/gossip.go#L72)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: this'll panic if you just do `desc := msg.(*roachpb.StoreDescriptor)` and have the wrong type (you don't need to change this if you don't want to, just mentioning)
</blockquote></details>

That seems better, updated.

**Review by AlexTalks — APPROVED** [review]
:lgtm:

It's difficult to review a PR this large in Reviewable but things look pretty good to me.  Apologies for not checking this again sooner!

> Reviewed 18 of 20 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93945#-:-NM51c8k479nVkMwGisW:bb9dd2d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by kvoli** [comment]
TYFTR

bors r=alextalks

**Pull request merged**
