### PR TITLE
sql/opt/optbuilder: minor allocation reduction

### PR DESCRIPTION
**Pull request by petermattis**
Chunk allocate scopes and add an exprTransformCtx to Builder.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28597)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/groupby.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28597#-LJv8_7REh_Ks6dZ7v2-:-LJv8_7REh_Ks6dZ7v20:b-b69fis) ([raw file](https://github.com/cockroachdb/cockroach/blob/117c5f9849df3d22029a4c75207e51f7f62bd3fb/pkg/sql/opt/optbuilder/groupby.go#L99)):*
> ```Go
> 	}
> 
> 	b.exprTransformCtx = transform.ExprTransformContext{}
> ```

I'm not sure if this is necessary or if this part of the change is copacetic. Is this method ever called recursively? It doesn't look like it, but I'm not familiar with this code.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28597)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/groupby.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28597#-LJv8_7REh_Ks6dZ7v2-:-LJxcBxxDZCulVPw-95h:b-t5dq4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/117c5f9849df3d22029a4c75207e51f7f62bd3fb/pkg/sql/opt/optbuilder/groupby.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure if this is necessary or if this part of the change is copacetic. Is this method every called recursively? It doesn't look like it, but I'm not familiar with this code. 
</blockquote></details>

This seems fine to me, but @rytaft should confirm.

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28597#-:-LJxoGVBAEuQGt1kM5JW:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28597#-LJv8_7REh_Ks6dZ7v2-:-LJxmtnZ8Fo4D4OL8iOo:b-xczfb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/117c5f9849df3d22029a4c75207e51f7f62bd3fb/pkg/sql/opt/optbuilder/groupby.go#L99)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This seems fine to me, but @rytaft should confirm.
</blockquote></details>

It's only called once per select clause. Shouldn't be a problem.
___
*[pkg/sql/opt/optbuilder/scope.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28597#-LJxnZ3MDzSpFm1MQ7t7:-LJxnZ3MDzSpFm1MQ7t8:bjdo6o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/117c5f9849df3d22029a4c75207e51f7f62bd3fb/pkg/sql/opt/optbuilder/scope.go#L103)):*
> ```Go
> // push creates a new scope with this scope as its parent.
> func (s *scope) push() *scope {
> 	r := s.builder.allocScope()
> ```

Do you want to add this at the root level too? See `Build()` in `builder.go`.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28597)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28597#-LJv8_7REh_Ks6dZ7v2-:-LJySQMb6Jb78L5UkgNS:brjmcgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/117c5f9849df3d22029a4c75207e51f7f62bd3fb/pkg/sql/opt/optbuilder/groupby.go#L99)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It's only called once per select clause. Shouldn't be a problem.
</blockquote></details>

Something else I was curious about is whether clear `exprTransformCtx` is necessary here. I think the answer is yes, but wanted to get a second (informed) opinion.
___
*[pkg/sql/opt/optbuilder/scope.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28597#-LJxnZ3MDzSpFm1MQ7t7:-LJyRpdH6jG2VkSOJCzd:b-93mggs) ([raw file](https://github.com/cockroachdb/cockroach/blob/117c5f9849df3d22029a4c75207e51f7f62bd3fb/pkg/sql/opt/optbuilder/scope.go#L103)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you want to add this at the root level too? See `Build()` in `builder.go`.
</blockquote></details>

Yes, thanks for the pointer. Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28597)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28597#-LJv8_7REh_Ks6dZ7v2-:-LJyYbdX96uxPIteefTE:b-thexr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/117c5f9849df3d22029a4c75207e51f7f62bd3fb/pkg/sql/opt/optbuilder/groupby.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Something else I was curious about is whether clear `exprTransformCtx` is necessary here. I think the answer is yes, but wanted to get a second (informed) opinion.
</blockquote></details>

Actually it's probably not necessary to clear it. Inside the `AggregateInExpr` function is this call: `defer t.isAggregateVisitor.Reset()`.

So I think the state is reset after each call. Good catch!

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28597)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28597#-LJv8_7REh_Ks6dZ7v2-:-LJy_NGKAaXMl4rhmlm1:bnfrfow) ([raw file](https://github.com/cockroachdb/cockroach/blob/117c5f9849df3d22029a4c75207e51f7f62bd3fb/pkg/sql/opt/optbuilder/groupby.go#L99)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Actually it's probably not necessary to clear it. Inside the `AggregateInExpr` function is this call: `defer t.isAggregateVisitor.Reset()`.

So I think the state is reset after each call. Good catch!
</blockquote></details>

Thanks for pointing that out. I've removed the clearing here and in `assertNoAggregationOrWindowing`. I've also removed the defer in `AggregateInExpr`  as it seems cleaner to ensure the state is cleared before using `IsAggregateVisitor` and defers have a small but real expense.

**Comment by petermattis** [comment]
bors r=rytaft,RaduBerinde

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28597)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28597#-LJv8_7REh_Ks6dZ7v2-:-LJysEI-98x98LxoYxaD:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/117c5f9849df3d22029a4c75207e51f7f62bd3fb/pkg/sql/opt/optbuilder/groupby.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Thanks for pointing that out. I've removed the clearing here and in `assertNoAggregationOrWindowing`. I've also removed the defer in `AggregateInExpr`  as it seems cleaner to ensure the state is cleared before using `IsAggregateVisitor` and defers have a small but real expense.
</blockquote></details>

:thumbsup:

**Pull request merged**
