### PR TITLE
kvserver: use wrapped btree for replicasByKey

### PR DESCRIPTION
**Pull request by tbg**
`(Store).mu.replicasByKey` is a btree holding `*Replica` and
`*ReplicaPlaceholders` keyed by their `StartKey`. Since the
wrapping in and unwrapping of interfaces necessary to use a
btree library was done ad-hoc, the code was generally fairly
messy.

This commit gathers all of this code in a wrapper, `storeReplicaBTree`,
and gives it the right methods which callers can "simply use".

In the course of doing so, I discovered a bug in `VisitReplicasByKey`.
In adjusting the start key to match up with an item's start key (to
avoid missing the start key's item during the walk), it could
erroneously change the start key to point into an item that did not
itself overlap the original start key, and was thus visited in error.

Luckily, this didn't seem to have caused any real problems since (before
this PR) VisitReplicasByKey was only invoked to add RangeInfos to
BatchResponses, and including extra information there is benign.  This
code was also simplified with the comfortable getters that are now
available, with one notable change being that - for reasons unknown to
me - we were picking up placeholders for inclusion in RangeInfo, and
avoid that now.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM with a :question: about panic/recover somewhere.

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-:-MS2qJia6opxhDpOWBZT:b20ryty)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen, @irfansharif, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/helpers_test.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS2pWXUEKbg9v6zZd6z:-MS2pWXUEKbg9v6zZd7-:bcyvoys) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/helpers_test.go#L225)):*
> ```Go
> 	s.mu.RLock()
> 	defer s.mu.RUnlock()
> 	s.mu.replicas.Range(func(_ int64, p unsafe.Pointer) bool {
> ```

not this PR, but for here and other interfaces like this:
1. add a `ctx` arg to `Range` and the callback argument's signature
2. inside the `Range()` function use `logtags.AddTag` to document which range/replica is being operated on

this way the logging that happens inside the callback documents what range/replica is being worked on.
___
*[pkg/kv/kvserver/replica_raftstorage.go, line 769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS2pmvV7m_aK4_KWg79:-MS2pmvV7m_aK4_KWg7A:b2rfcke) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/replica_raftstorage.go#L769)):*
> ```Go
> 	defer func() {
> 		if r := recover(); r != nil {
> 			panic(r)
> ```

I don't understand this: recover+panic is no-op?

**Review by nvb — APPROVED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59472)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen, @irfansharif, @knz, and @tbg)

___
*[pkg/kv/kvserver/helpers_test.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5YwNF2uau-77_owyj:-MS5YwNF2uau-77_owyk:bopx2hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/helpers_test.go#L235)):*
> ```Go
> 		// point acquiring repl.raftMu is unnecessary.
> 		if repl.IsInitialized() {
> 			if rbkRepl := s.mu.replicasByKey.LookupReplica(context.Background(), repl.Desc().StartKey); rbkRepl != repl {
> ```

We don't want to pass the shiny new `ctx` we just annotated?
___
*[pkg/kv/kvserver/replica_raftstorage.go, line 769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS2pmvV7m_aK4_KWg79:-MS5ZFMmDRZ99V-OuEOS:b-7coiks) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/replica_raftstorage.go#L769)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't understand this: recover+panic is no-op?
</blockquote></details>

Was this left-over debugging code?
___
*[pkg/kv/kvserver/store.go, line 2010 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5Ztu-CE3WJDvtJSev:-MS5Ztu-CE3WJDvtJSew:bwjzvwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store.go#L2010)):*
> ```
> iterutil.IterationDone
> ```

This symbol doesn't quite exit, which makes a grep of it confusing. Consider saying `// can return iterutil.Done`.
___
*[pkg/kv/kvserver/store.go, line 2204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5_daPB4BDv_TYISSL:-MS5_daPB4BDv_TYISSM:blb2jni) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store.go#L2204)):*
> ```Go
> 
> // getOverlappingKeyRangeLocked returns an item from Store.mu.replicasByKey
> // overlapping the given descriptor (or nil if no such keyRange exists).
> ```

Didn't you just remove the `keyRange` type?
___
*[pkg/kv/kvserver/store_create_replica.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5_hVU-xDRoSERVaAo:-MS5_hVU-xDRoSERVaAp:b-sf6342) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_create_replica.go#L252)):*
> ```Go
> // addReplicaInternalLocked adds the replica to the replicas map and the
> // replicasByKey btree. Returns an error if a replica with
> // the same Range ID or a keyRange that overlaps has already been added to
> ```

Same question. Isn't `keyRange` gone?
___
*[pkg/kv/kvserver/store_replica_btree.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5_DdsCewMQpCDLVIt:-MS5_DdtBYl60DO3PTZm:bmek7d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L37)):*
> ```Go
> // Exactly one of these two fields is set. The zero item represents no
> // value.
> type item struct {
> ```

It's a little unfortunate to add a type named `item` in `kvserver`. Can we qualify it at all? Maybe `rangeItem`?
___
*[pkg/kv/kvserver/store_replica_btree.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5aVv24rg8QHb3JwRY:-MS5aVv24rg8QHb3JwRZ:budj2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L64)):*
> ```Go
> func (b *storeReplicaBTree) LookupReplica(ctx context.Context, key roachpb.RKey) *Replica {
> 	var repl *Replica
> 	b.mustDescendLessOrEqual(context.Background(), key, func(_ context.Context, it item) error {
> ```

Throughout this file: did you mean to pass the provided `ctx`s?
___
*[pkg/kv/kvserver/store_replica_btree.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5ap1P8ehjmhkpaEaJ:-MS5ap1P8ehjmhkpaEaK:bmhhtzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L94)):*
> ```
> store.mu is held during the visiting.
> ```

It's a little strange to see locking comments around the implementation of this btree, as opposed to around its usage. Should we place it with a comment on `Store`'s `replicasByKey` field that all access requires the `store.mu` to be held?
___
*[pkg/kv/kvserver/store_replica_btree.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5cJ04BRtFPL73_0uN:-MS5cJ04BRtFPL73_0uO:b-bva1xi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L140)):*
> ```Go
> 		})
> 
> 	// Iterate though overlapping replicas.
> ```

"through"
___
*[pkg/kv/kvserver/store_replica_btree.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5chQiCh_cOoOqO_x_:-MS5chQiCh_cOoOqO_xa:b-jjlskn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L169)):*
> ```
> DeletePlaceholder deletes
> ```
___
*[pkg/kv/kvserver/store_replica_btree.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5csppByNGYHwx9DNB:-MS5csppByNGYHwx9DNC:brctpib) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L176)):*
> ```Go
> 
> // ReplaceOrInsertReplica inserts a *Replica into the btree. If it replaces an
> // existing element, that element is returned.
> ```

nit: s/element/item/ in some of these comments?
___
*[pkg/kv/kvserver/store_replica_btree.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5dFXeBORkI7_hMbg4:-MS5dFXf6XVsknnD50So:b-iogg6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L201)):*
> ```Go
> ) error {
> 	var err error
> 	(*btree.BTree)(b).DescendLessOrEqual(rangeBTreeKey(startKey), func(it btree.Item) (more bool) {
> ```

nit: there's a lot of `(*btree.BTree)(b)` in here, which is pretty distracting. It's also hard to understand the order of operations on first glance because of the parenthesis plus mix of prefix/postfix operators. Consider a method like `func (b *storeReplicaBTree) tree() *btree.BTree { ... }` to make these methods less verbose.
___
*[pkg/kv/kvserver/store_replica_btree.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5eKw2-Hv_-oVBrnhj:-MS5eKw2-Hv_-oVBrnhk:b-jfatdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L246)):*
> ```Go
> }
> 
> // rangeKeyItem is a common interface for roachpb.Key, *btreeReplica, and
> ```

`roachpb.RKey`

Also, `s/btreeReplica/Replica/`?

**Review by tbg — COMMENTED** [review]
TFTRs!

> Dismissed @knz from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-:-MS8Vr347tIFBjp1TE5V:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen, @irfansharif, and @knz)

___
*[pkg/kv/kvserver/replica_raftstorage.go, line 769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS2pmvV7m_aK4_KWg79:-MS8S5212M1UwvL5LOWp:bcj3h84) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/replica_raftstorage.go#L769)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Was this left-over debugging code?
</blockquote></details>

I removed this, but basically when you panic with the mutex held, you may have `err == nil` and you'll deadlock during `GetReplicaDescriptor`. Arguably the problem is that we're not `defer`-unlocking the mutex though, which I'm fixing in the follow-up PRs.
___
*[pkg/kv/kvserver/store_replica_btree.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5_DdsCewMQpCDLVIt:-MS8SzO10jJpIgoEqw9O:b-u7e5f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's a little unfortunate to add a type named `item` in `kvserver`. Can we qualify it at all? Maybe `rangeItem`?
</blockquote></details>

Went for `replicaOrPlaceholder`. It's a bit sad that there's no real option to limit the visibility of what should be internals. I'd put this into a small package but it's referencing *Replica, so you'd have to put *Replica into its own package first :rip:
___
*[pkg/kv/kvserver/store_replica_btree.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5ap1P8ehjmhkpaEaJ:-MS8TgzC0Xk_sAFwPaOY:b4laba0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L94)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> store.mu is held during the visiting.
> ```

It's a little strange to see locking comments around the implementation of this btree, as opposed to around its usage. Should we place it with a comment on `Store`'s `replicasByKey` field that all access requires the `store.mu` to be held?
</blockquote></details>

replicasByKey is in store.mu, so I don't think that is necessary. The comment here originated on a method on `*Store`, it doesn't make sense any more, I removed the locking part.
___
*[pkg/kv/kvserver/store_replica_btree.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5csppByNGYHwx9DNB:-MS8U2-kDdP1qoVXJz8z:b-5x1w38) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L176)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: s/element/item/ in some of these comments?
</blockquote></details>

Since the wrapper is no longer named `item`, sticking consistently to item or element both seem fine. I kept it as element.
___
*[pkg/kv/kvserver/store_replica_btree.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS5eKw2-Hv_-oVBrnhj:-MS8Um_o41ehUfM21F2e:b-ybyc6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b9f50628977f53bd99589b5891d52e569c1c32a/pkg/kv/kvserver/store_replica_btree.go#L246)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`roachpb.RKey`

Also, `s/btreeReplica/Replica/`?
</blockquote></details>

No, btreeReplica implements rangeKeyItem. *Replica intentionally no longer does, there is no need for a `Less` method on it.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-:-MS8kI8H9HxPB1w7Y7ll:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @angelapwen, @irfansharif, @knz, and @tbg)

___
*[pkg/kv/kvserver/queue_test.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS8jr8M4fj8RbX5yIPB:-MS8jr8M4fj8RbX5yIPC:b-jrrkhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a86630b3b70923b71f0ede5c4035d20d149b114a/pkg/kv/kvserver/queue_test.go#L152)):*
> ```Go
> 	heap.Init(&pq)
> 
> 	// Insert a new replicaOrPlaceholder and then modify its priority.
> ```

Bad global replace?

**Review by tbg — COMMENTED** [review]
bors r=nvanbenschoten,knz

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-:-MS91B9g7ZnMDfEGZzBp:b-c7a0zx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angelapwen, @irfansharif, and @knz)

___
*[pkg/kv/kvserver/queue_test.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59472#-MS8jr8M4fj8RbX5yIPB:-MS919js6ftE14WInnc5:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a86630b3b70923b71f0ede5c4035d20d149b114a/pkg/kv/kvserver/queue_test.go#L152)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Bad global replace?
</blockquote></details>

Fixed.

**Comment by ajstorm** [comment]
Hey @tbg.  A bad merge on my part borked your bors run.  I'll resubmit.

bors r=nvanbenschoten,knz

**Pull request merged**
