### PR TITLE
roachtest: deflake decomm-mixed-versions roachtest

### LINKED ISSUE #51334: roachtest: decommission/mixed-versions failed
[(roachtest).decommission/mixed-versions failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2081789&tab=buildLog) on [release-20.1@a36656a9f66ef1bd61873cfbaed6d1ea8e4b75a8](https://github.com/cockroachdb/cockroach/commits/a36656a9f66ef1bd61873cfbaed6d1ea8e4b75a8):

```
The test failed on branch=release-20.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/decommission/mixed-versions/run_1
	cluster.go:1827,versionupgrade.go:226,versionupgrade.go:305,versionupgrade.go:167,mixed_version_decommission.go:126,mixed_version_decommission.go:284,test_runner.go:757: cluster.Put: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod put teamcity-2081789-1594448116-04-n4cpu4:2 /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 ./cockroach returned: exit status 1
		(1) attached stack trace
		  | main.(*cluster).PutE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1842
		  | main.(*cluster).Put
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1826
		  | main.(*versionUpgradeTest).uploadVersion
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:226
		  | main.binaryUpgradeStep.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:305
		  | main.(*versionUpgradeTest).run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:167
		  | main.runDecommissionMixedVersions
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/mixed_version_decommission.go:126
		  | main.registerDecommissionMixedVersion.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/mixed_version_decommission.go:284
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:757
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1373
		Wraps: (2) cluster.Put
		Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod put teamcity-2081789-1594448116-04-n4cpu4:2 /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 ./cockroach returned
		  | stderr:
		  |
		  | stdout:
		  | teamcity-2081789-1594448116-04-n4cpu4: putting (dist) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 ./cockroach
		  |
		  |    2: ~ scp -r -C -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa -i /root/.ssh/google_compute_engine /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 ubuntu@35.184.251.100:./cockroach
		  | scp: ./cockroach: Text file busy
		  | : exit status 1
		  | I200711 06:19:13.859909 1 cluster_synced.go:1162  put /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach.linux-2.6.32-gnu-amd64 failed
		Wraps: (4) exit status 1
		Error types: (1) *withstack.withStack (2) *errutil.withMessage (3) *main.withCommandDetails (4) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/decommission/mixed-versions](https://teamcity.cockroachdb.com/viewLog.html?buildId=2081789&tab=artifacts#/decommission/mixed-versions)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Adecommission%2Fmixed-versions.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #51365: roachtest: decommission/mixed-versions failed
[(roachtest).decommission/mixed-versions failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2084629&tab=buildLog) on [master@12b58af06d9104bc585bc0773bbe29d68ff2d826](https://github.com/cockroachdb/cockroach/commits/12b58af06d9104bc585bc0773bbe29d68ff2d826):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/decommission/mixed-versions/run_1
	cluster.go:1827,versionupgrade.go:226,versionupgrade.go:305,versionupgrade.go:167,mixed_version_decommission.go:126,mixed_version_decommission.go:284,test_runner.go:757: cluster.Put: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod put teamcity-2084629-1594620495-13-n4cpu4:1-4 /home/agent/temp/buildTmp/cockroach-v20.1.3.linux-amd64 ./cockroach-20.1.3 returned: exit status 1
		(1) attached stack trace
		  | main.(*cluster).PutE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1842
		  | main.(*cluster).Put
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1826
		  | main.(*versionUpgradeTest).uploadVersion
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:226
		  | main.binaryUpgradeStep.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:305
		  | main.(*versionUpgradeTest).run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/versionupgrade.go:167
		  | main.runDecommissionMixedVersions
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/mixed_version_decommission.go:126
		  | main.registerDecommissionMixedVersion.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/mixed_version_decommission.go:284
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:757
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1373
		Wraps: (2) cluster.Put
		Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod put teamcity-2084629-1594620495-13-n4cpu4:1-4 /home/agent/temp/buildTmp/cockroach-v20.1.3.linux-amd64 ./cockroach-20.1.3 returned
		  | stderr:
		  |
		  | stdout:
		  | teamcity-2084629-1594620495-13-n4cpu4: putting (dist) /home/agent/temp/buildTmp/cockroach-v20.1.3.linux-amd64 ./cockroach-20.1.3
		  | .............
		  |    1: done
		  |    2: ~ scp -r -C -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa -i /root/.ssh/google_compute_engine /home/agent/temp/buildTmp/cockroach-v20.1.3.linux-amd64 ubuntu@199.223.234.19:./cockroach-20.1.3
		  | scp: ./cockroach-20.1.3: Text file busy
		  | : exit status 1
		  |    3: ~ scp -r -C -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa -i /root/.ssh/google_compute_engine ubuntu@35.226.206.197:./cockroach-20.1.3 ubuntu@35.222.209.24:./cockroach-20.1.3
		  | scp: ./cockroach-20.1.3: Text file busy
		  | : exit status 1
		  |    4: done
		  | I200713 06:12:51.630902 1 cluster_synced.go:1162  put /home/agent/temp/buildTmp/cockroach-v20.1.3.linux-amd64 failed
		Wraps: (4) exit status 1
		Error types: (1) *withstack.withStack (2) *errutil.withMessage (3) *main.withCommandDetails (4) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/decommission/mixed-versions](https://teamcity.cockroachdb.com/viewLog.html?buildId=2084629&tab=artifacts#/decommission/mixed-versions)
Related:
- #51334 roachtest: decommission/mixed-versions failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-20.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Adecommission%2Fmixed-versions.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #51365.
Fixes #51334.

Given the randomized nature of this test, could be trying to remove the
binary that's still currently being run. This can fail on linux with
'Text file busy' errors.

```go
  // We upgrade a subset of the cluster to v20.2 (these may end up
  // resolving to the same node).
  binaryUpgradeStep(c.Node(pinnedUpgrade), mainVersion),
  binaryUpgradeStep(c.Node(getRandNode()), mainVersion),
```

This commit changes binaryUpgradeStep to first stop all the nodes and
only then upload the binary (making it a no-op effectively), which I was
expecting to be the contract.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
Nice fix!

**Comment by irfansharif** [comment]
I'm not sure what the failure being observed is. Filed #52523 and retrying. I think it's unrelated to this PR (though version-upgrade makes use of this helper).

**Comment by irfansharif** [comment]
PTAL, that was buggy, we weren't doing rolling upgrades anymore, we simply stopped everything. Woops 🙈

**Review by tbg — APPROVED** [review]

**Pull request merged**
