### PR TITLE
sql: add voting_replicas, non_voting_replicas columns to SHOW RANGES

### LINKED ISSUE #93508: sql: add voting_replicas, non_voting_replicas columns to SHOW RANGES
Some of the multitenant admin functions accept `VOTERS`, `NONVOTERS` as input.

Add `voting_replicas`, `non_voting_replicas` columns to `SHOW RANGE(S)` to make working with the admin functions easier.

Jira issue: CRDB-22394

Epic CRDB-16746

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #93508

Some of the multitenant admin functions accept VOTERS, NONVOTERS as input.

Add voting_replicas, non_voting_replicas columns to SHOW RANGE(S) to make working with the admin functions easier.

Release note (sql change): Add voting_replicas, non_voting_replicas columns to output of SHOW RANGE(S) statements.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
Assuming the powers who decide what columns are added to `SHOW RANGES` are happy with this, the change itself looks sane. 

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-:-NJBDbQoEkqnJKVahcO7:b-1khqct)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @ecwall, @knz, and @rafiss)

___
*[`pkg/sql/show_ranges_test.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJBDJZYEEEHtDCMFmkR:-NJBDJZYEEEHtDCMFmkS:b2fr51h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce3954e13502158d35fe7518e90c95cce3b97a08/pkg/sql/show_ranges_test.go#L148)):*
> ```Go
> }
> 
> func TestShowRangesColumns(t *testing.T) {
> ```

Could we write this using a LogicTest instead?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @knz, and @rafiss)

___
*[`pkg/sql/show_ranges_test.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJBDJZYEEEHtDCMFmkR:-NJBj3xi7wA9c2RLtCmr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce3954e13502158d35fe7518e90c95cce3b97a08/pkg/sql/show_ranges_test.go#L148)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could we write this using a LogicTest instead? 
</blockquote></details>

Done.

**Review by arulajmani — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @ecwall, @knz, and @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 3410 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHEoDx35P3_7mdliwx:-NJHEoDx35P3_7mdliwy:b8sf4dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/logic.go#L3410)):*
> ```Go
> 				for i, v := range vals {
> 					colT := query.colTypes[i]
> 					// Ignore column - useful for non-deterministic output
> ```

Do we need this? Could we not instead construct the query such that the column isn't included?
___
*[`pkg/sql/sqltestutils/sql_test_utils.go` line 129 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHE5tK4XE_37SwCblf:-NJHE5tK4XE_37SwCblg:bjd9dz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/sqltestutils/sql_test_utils.go#L129)):*
> ```Go
> }
> 
> func ArrayStringToSlice(t *testing.T, array string, message ...string) []string {
> ```

nit: comment
___
*[`pkg/sql/logictest/testdata/logic_test/ranges` line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHDTGu24bmv-mJXSdU:-NJHDTGu24bmv-mJXSdV:b-hcvhl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/testdata/logic_test/ranges#L155)):*
> ```
> ALTER INDEX d.c@c_i_idx SPLIT AT VALUES (0)
> 
> # hex encode start_key, end_key so that text is UTF-8 compatible
> ```

What's the motivation behind this?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @knz, and @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 3410 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHEoDx35P3_7mdliwx:-NJHHb9o8xfHht1GkqvQ:b-7thuyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/logic.go#L3410)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we need this? Could we not instead construct the query such that the column isn't included?
</blockquote></details>

I think it is useful to have the tests I added in this PR fail if columns are added/removed to indicate that the existing test case should be updated instead of adding something new.
___
*[`pkg/sql/sqltestutils/sql_test_utils.go` line 129 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHE5tK4XE_37SwCblf:-NJHJ9fE0VCtkDp0f7j4:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/sqltestutils/sql_test_utils.go#L129)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: comment
</blockquote></details>

Added.



_Code quote:_
```Go
ArrayStringToSlice
```
___
*[`pkg/sql/logictest/testdata/logic_test/ranges` line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHDTGu24bmv-mJXSdU:-NJHGZ3N-uCHCkGI0E44:b-452vsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/testdata/logic_test/ranges#L155)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

What's the motivation behind this? 
</blockquote></details>

`git` (including GitHub) can't diff this file because it has non-UTF-8 characters in it (these don't render in reviewable, but you can see them in GoLand). The problem still exists in this PR because the "before" file still contains these characters, but it will be fixed going forward.

```
diff --git a/pkg/sql/logictest/testdata/logic_test/ranges b/pkg/sql/logictest/testdata/logic_test/ranges
index b1b1342c71..9b4fb03bbd 100644
Binary files a/pkg/sql/logictest/testdata/logic_test/ranges and b/pkg/sql/logictest/testdata/logic_test/ranges differ
```

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @knz, and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/ranges` line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHDTGu24bmv-mJXSdU:-NJHLKp44qnxazuzHn5R:bfmq6o2) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/testdata/logic_test/ranges#L155)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

`git` (including GitHub) can't diff this file because it has non-UTF-8 characters in it (these don't render in reviewable, but you can see them in GoLand). The problem still exists in this PR because the "before" file still contains these characters, but it will be fixed going forward.

```
diff --git a/pkg/sql/logictest/testdata/logic_test/ranges b/pkg/sql/logictest/testdata/logic_test/ranges
index b1b1342c71..9b4fb03bbd 100644
Binary files a/pkg/sql/logictest/testdata/logic_test/ranges and b/pkg/sql/logictest/testdata/logic_test/ranges differ
```
</blockquote></details>

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @ecwall, @knz, and @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 3410 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHEoDx35P3_7mdliwx:-NJHWyoG5U9j2Zse_JIy:b2leqwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/logic.go#L3410)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

I think it is useful to have the tests I added in this PR fail if columns are added/removed to indicate that the existing test case should be updated instead of adding something new.
</blockquote></details>

Even then, if all you want to do is verify column names, couldn't you achieve the same thing by doing something like: 


```
SELECT * FROM [SHOW RANGES FROM TABLE tbl;] LIMIT 0;
```
___
*[`pkg/sql/logictest/testdata/logic_test/ranges` line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHDTGu24bmv-mJXSdU:-NJHU5N_1ldwL23hJjAX:bodd5mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/testdata/logic_test/ranges#L155)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>


</blockquote></details>

I see, thanks for making the change! Consider saying the same in the comment, given it's not completely obvious why we're doing this.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @knz, and @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 3410 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHEoDx35P3_7mdliwx:-NJHaDQ63DMteU6Pqfg3:bo3b2q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/logic.go#L3410)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Even then, if all you want to do is verify column names, couldn't you achieve the same thing by doing something like: 


```
SELECT * FROM [SHOW RANGES FROM TABLE tbl;] LIMIT 0;
```

</blockquote></details>

I thought it would be useful to have a row also to make sure it is populated.

For some reason `SHOW RANGES FROM DATABASE` does not show any rows even if a table is added to it so I left it as is. There is a comment above that it is populated async so I don't think it should be verified here.
___
*[`pkg/sql/logictest/testdata/logic_test/ranges` line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHDTGu24bmv-mJXSdU:-NJHaAjV2KlN5gebHn89:b-2ymw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/testdata/logic_test/ranges#L155)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I see, thanks for making the change! Consider saying the same in the comment, given it's not completely obvious why we're doing this. 
</blockquote></details>

Good idea, added.

**Review by arulajmani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @ecwall, @knz, and @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 3410 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHEoDx35P3_7mdliwx:-NJLetEj4IB9JucDCmtj:btfsj8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/logic.go#L3410)):*
> For some reason SHOW RANGES FROM DATABASE does not show any rows even if a table is added to it so I left it as is.

Isn't that because there's no table inside the database? 

> There is a comment above that it is populated async so I don't think it should be verified here.

Yeah, given this, I'm not sure it's worth adding this new "_" symbol to the logic test grammar. It doesn't seem generally valuable, given one could just decide to omit columns they're not interested in fetching. 

For our particular test case, all we're deterministically testing is the column names, which we can do using a `LIMIT 0`. If all we care about is this command returns rows, then we should just do a count(*). 

If you feel strongly about adding this '_' symbol however, I won't stand in your way. Just add a comment about it up top in `logic.go` where the other symbols are described.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 3410 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHEoDx35P3_7mdliwx:-NJLpwII5t8jz_Hrxxy0:b-8vym2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/logic.go#L3410)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> For some reason SHOW RANGES FROM DATABASE does not show any rows even if a table is added to it so I left it as is.

Isn't that because there's no table inside the database? 

> There is a comment above that it is populated async so I don't think it should be verified here.

Yeah, given this, I'm not sure it's worth adding this new "_" symbol to the logic test grammar. It doesn't seem generally valuable, given one could just decide to omit columns they're not interested in fetching. 

For our particular test case, all we're deterministically testing is the column names, which we can do using a `LIMIT 0`. If all we care about is this command returns rows, then we should just do a count(*). 

If you feel strongly about adding this '_' symbol however, I won't stand in your way. Just add a comment about it up top in `logic.go` where the other symbols are described. 

</blockquote></details>

SHOW RANGES FROM DATABASE is broken currently. I'm working on it.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 3410 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93513#-NJHEoDx35P3_7mdliwx:-NJLnJX18VC7kT0goUHs:bar16bf) ([raw file](https://github.com/cockroachdb/cockroach/blob/13dd10ad2ddaf5adbd7afad7e11a169f83a4ece2/pkg/sql/logictest/logic.go#L3410)):*
> Isn't that because there's no table inside the database?

Even after I added a table it did not have any records until I added a split to the table. `SHOW RANGES FROM TABLE` shows a record for a table even without a split.

> If you feel strongly about adding this '_' symbol however, I won't stand in your way. Just add a comment about it up top in logic.go where the other symbols are described.

Comment added.

**Comment by ecwall** [comment]
bors r=arulajmani

**Comment by ecwall** [comment]
bors r=arulajmani

**Pull request merged**
