### PR TITLE
sql: ensure that a table cannot be read before its creation time

### PR DESCRIPTION
**Pull request by vivekmenezes**

### CODE REVIEW

**Comment by knz** [comment]
I think you also need to set ModificationTime on the descriptor created by createViewNode.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17378#-:-KqX2lj7mVx523Ghsy4C:b-ujdted)*

**Comment by vivekmenezes** [comment]
Good point! I'll rework this PR to take care of that, but doesn't bode well for how we're organizing the code!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17378#-:-KqY93A4oBZ2GTYbyogd:b-obwsnn)*

**Comment by knz** [comment]
The correct way to do this is to capture the common logic in an API, i.e. move forward on #17188 and solve this problem there.

**Comment by vivekmenezes** [comment]
@andreimatei this is ready for review. Thanks!

**Comment by knz** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create.go, line 628 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17378#-Kqw25v5Xei59Z2GJtOo:-Kqw25v6ICblq0_xWs06:b-ex4d0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c0f12d1ac5698371b9771106fee7141dd4553f5/pkg/sql/create.go#L628)):*
> ```Go
> 
> 	// Initialize ModificationTime to the creation time.
> 	desc.ModificationTime = creationTime
> ```

Instead, please make all 3 functions makeTableDescIfAs, MakeTableDesc and makeViewTableDesc call your new function `initTableDescriptor`.
This way you don't need this line here. Also this way we're much more immune to inconsistent descriptors if in the future we implement other statements that create descriptors.

---

*[pkg/sql/create.go, line 1226 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17378#-Kqw3Ac-f4P7azKFuT46:-Kqw3Ac0pGxIFpq7EpAR:b-jigwxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c0f12d1ac5698371b9771106fee7141dd4553f5/pkg/sql/create.go#L1226)):*
> ```Go
> 	var creationTime hlc.Timestamp
> 	if txn != nil {
> 		creationTime = txn.OrigTimestamp()
> ```

I strongly recommend extending the prototype of `MakeTableDesc` with the timestamp and let the caller decide the timestamp, instead of using txn != nil. For example for the new bulk I/O functionality there is no transaction but there should be a single timestamp common to all the descriptors being created (`pkg/ccl/sqlccl/load.go` and `parseCSVTableDescriptor` in `csv.go`). Speak to @mjibson.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17378)*

**Comment by vivekmenezes** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/create.go, line 628 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17378#-Kqw25v5Xei59Z2GJtOo:-KqxFsdIzG7Bg1Hz9PFi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0155a2c8252b58882efa7f745de42df244bc4ea/pkg/sql/create.go#L628)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Instead, please make all 3 functions makeTableDescIfAs, MakeTableDesc and makeViewTableDesc call your new function `initTableDescriptor`.
This way you don't need this line here. Also this way we're much more immune to inconsistent descriptors if in the future we implement other statements that create descriptors.
</blockquote></details>

Done.

---

*[pkg/sql/create.go, line 1226 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17378#-Kqw3Ac-f4P7azKFuT46:-KqxLMuqhrxps4SLF-0P:b-khlzq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0155a2c8252b58882efa7f745de42df244bc4ea/pkg/sql/create.go#L1226)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I strongly recommend extending the prototype of `MakeTableDesc` with the timestamp and let the caller decide the timestamp, instead of using txn != nil. For example for the new bulk I/O functionality there is no transaction but there should be a single timestamp common to all the descriptors being created (`pkg/ccl/sqlccl/load.go` and `parseCSVTableDescriptor` in `csv.go`). Speak to @mjibson.
</blockquote></details>

Done. I've added a new commit to this PR for further work. I'll ask @mjibson help me figure out what timestamp I aught to pass in here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17378)*

**Comment by knz** [comment]
LGTM but let's take some input from a member of the bulk i/o team.

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/sqlccl/csv.go, line 164 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17378#-KqxMg2460K0F_EZb97N:-KqxMg2460K0F_EZb97O:b-bjast3) ([raw file](https://github.com/cockroachdb/cockroach/blob/90d7372ad5917d8dcacddfe2a99b548d83c26ba3/pkg/ccl/sqlccl/csv.go#L164)):*
> ```Go
> 		parentID,
> 		tableID,
> 		hlc.Timestamp{},
> ```

Maybe add a TODO comment here and below. Unless Matt has a suggestion straight away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17378#-:-KqxMr5_64_SZtw2812Z:b-9c4olx)*

**Comment by vivekmenezes** [comment]
@mjibson I'd like your input on what value to pass in as the creation timestamp for the tables being restored. This PR is blocked on that. Thanks!

**Comment by mjibson** [comment]
We should pass in the start time of the backup descriptor.

**Comment by vivekmenezes** [comment]
@mjibson I've merged this PR. Let us resolve #17526 separately.

**Pull request merged**
