### PR TITLE
Rework Metrics Part 2

### PR DESCRIPTION
**Pull request by mberhault**
- add MetricMetadata to all metrics. Contains name/help string.
- don't automatically add metrics to registries
- replace all Registry.X methods to create/add new metrics with NewX
- "pseudo" metrics are a group that expands into individual metrics
- optional label pairs on registries (storeID only for now)
- registries can no longer be added to registries

A few things I would still like to do:
- make registries just hold a slice. sorting them would allow reasonable
  searching (used in tests only) and keep the vars page sorted (easier
  refresh)
- remove registries from big objects, instead just keep the metrics. The
  metric/registry pattern is not the same everywhere.
- fill in help strings and audit names. this is part 3.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8479)

### CODE REVIEW

**Comment by mberhault** [comment]
Review status: 0 of 31 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 118 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8479#-KOv22B3sAyOtbL_3q-p:-KOvfbAJDzPypIwl0PRe:b-480lph) ([raw file](https://github.com/cockroachdb/cockroach/blob/673ce51166f2be92e9e5e0152f3694ac6998643d/kv/txn_coord_sender.go#L118)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I would prefer to use a suffix of "Group" or "Rates" instead of simply "Prefix".  The relationship is more nuanced than string construction.
</details>
Changed to Rates/Histograms/Histogram ending.

---

*[server/status/runtime.go, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8479#-KOvBann7L4VcgXaFnZQ:-KOveMjJDSzo3D4LZHRG:bhgkun9) ([raw file](https://github.com/cockroachdb/cockroach/blob/673ce51166f2be92e9e5e0152f3694ac6998643d/server/status/runtime.go#L112)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> The one thing I don't like here is that there is more opportunity for a newly added metric to be omitted from the registry; "create-then-add" opens the door to bugs if the second line is not added.  It would be nice to have something here verifying that all created metrics are present in the registry.
> 
> This could either be tests, or perhaps augmenting `AddMetric` to use reflection and accept an interface (inspecting a struct for Metric fields).
</details>
I have the same concern. We already have metrics that are intentionally not added to the registry (they never were). eg: gossip has some both client and server side metrics that are only used for logging.

Those should probably be rolled into a global metric (if we want to avoid per-node metrics) or use something else if it's just for logging to stderr (which isn't too useful).

I still want to clarify the interface between metrics and registries. I may very well move back to a automatic add, or at the very least a checking system as you mentioned. Is it cool if I leave it TBD for now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8479)*

**Comment by mberhault** [comment]
New commit: this adds `registry.AddStruct` which adds all metric fields of a struct to the registry. This is not used everywhere (except for `gossip.{incoming,outgoing}.gauge`). All metric fields must be exported.

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 38 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8479#-:-KP-ZcFTHmEzxL2VYB0y:bnfp4nl)*

**Comment by tamird** [comment]
Merge skew, master now red.

**Comment by mberhault** [comment]
oops. Did I get bit by the gocheck status code return thing? I could have
sworn I ran it manually and it was happy.
Anyway, fixing...

**Pull request merged**
