### PR TITLE
backupccl: add full cluster backup

### PR DESCRIPTION
**Pull request by pbardea**
Support the new syntax `BACKUP TO <location>` to backup all relevant
system tables as well as all user data in a cluster.

Release note (enterprise change): support full cluster backup to allow
the backup of all of the user tables in a cluster and the relevant
system tables.

### CODE REVIEW

**Review by dt — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-LxxBYTsDs9lMTD9b3Q6:-LxxBYTsDs9lMTD9b3Q7:b-507x0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c999c3165a0c41f54006870fe4bf0ed7d2c9f/pkg/ccl/backupccl/backup.go#L80)):*
> ```Go
> )
> 
> // The order of the tables list here is important. It is the order in which
> ```

my brain is having trouble squaring this this comment's emphasis on order with the very non-ordered `map` type -- maybe clarify in the comment that the order they are restored is important, and that order is documented as the order they _appear_ here or something?

I think we should also have a TODO (or for extra credit a link to an issue) tracking that we really need to move to a model whereby new system tables have to decide if they want to be included or not. 
___
*[pkg/ccl/backupccl/backup.go, line 712 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-Ly-OFJw1k0VwVmNaDOo:-Ly-OFJw1k0VwVmNaDOp:b-74f09i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c92c0042afa3beef998695a43d7dc0e208afdb6/pkg/ccl/backupccl/backup.go#L712)):*
> ```Go
> 		if dbDesc := desc.GetDatabase(); dbDesc != nil {
> 			if dbDesc.ID == sqlbase.SystemDB.ID {
> 				// Do not include the system database itself in the backup.
> ```

I could also see just including these and making skipping them a RESTORE-time decision. If for any reason we later realize we needed something in them -- say grants or something -- it might be nice if they happened to already be in the backups?
___
*[pkg/ccl/backupccl/backup.proto, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-LxxBCZy2dB_ui9rtJQ-:-LxxBCZy2dB_ui9rtJQ0:bbsgmjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c999c3165a0c41f54006870fe4bf0ed7d2c9f/pkg/ccl/backupccl/backup.proto#L105)):*
> ```protobuf
>   repeated string locality_kvs = 20 [(gogoproto.customname) = "LocalityKVs"];
>   repeated sql.stats.TableStatisticProto statistics = 21;
>   int32 table_coverage = 22;
> ```

we could customtype this to the `tree` alias to clean up the casts, right? (it'd also help document what it means).
___
*[pkg/sql/sem/tree/backup.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-LxxAJweD_5E18xy1-QJ:-LxxAJweD_5E18xy1-QK:byxath7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c999c3165a0c41f54006870fe4bf0ed7d2c9f/pkg/sql/sem/tree/backup.go#L22)):*
> ```Go
> 	// to have complete table coverage unless it was created by a BACKUP TO
> 	// command.
> 	Partial TableCoverage = iota
> ```

.02¢: the call sites, like the CDC one above, would read better, to me, if these were `tree.RequestedTables` and `tree.AllTables` or something like that --  on its own if you don't also know its type just seeing "tree.Partial" is a bit vague (though I suppose we mostly all use type-annotating editors so maybe it doesn't matter?).

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/backupccl/backup.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-LxxBYTsDs9lMTD9b3Q6:-Ly-hnte80NhdUV3opIS:b-e2gu9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c999c3165a0c41f54006870fe4bf0ed7d2c9f/pkg/ccl/backupccl/backup.go#L80)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

my brain is having trouble squaring this this comment's emphasis on order with the very non-ordered `map` type -- maybe clarify in the comment that the order they are restored is important, and that order is documented as the order they _appear_ here or something?

I think we should also have a TODO (or for extra credit a link to an issue) tracking that we really need to move to a model whereby new system tables have to decide if they want to be included or not. 
</blockquote></details>

Ah - apologies for the confusion. The comment comes from the full backup RESTORE patch which changes this to a list. Going to make it a list here for now, but introduce the comment in the full backup RESTORE pr. Updated with a comment linking to an issue to move to a model where system tables opt-{in,out} whether to be included in a full cluster backup.
___
*[pkg/ccl/backupccl/backup.go, line 712 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-Ly-OFJw1k0VwVmNaDOo:-Ly-mFCTAw3DqYjtQxIO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c92c0042afa3beef998695a43d7dc0e208afdb6/pkg/ccl/backupccl/backup.go#L712)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I could also see just including these and making skipping them a RESTORE-time decision. If for any reason we later realize we needed something in them -- say grants or something -- it might be nice if they happened to already be in the backups?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup.proto, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-LxxBCZy2dB_ui9rtJQ-:-Ly-lwWg6kB5bkTwIUKh:bxxvbym) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c999c3165a0c41f54006870fe4bf0ed7d2c9f/pkg/ccl/backupccl/backup.proto#L105)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

we could customtype this to the `tree` alias to clean up the casts, right? (it'd also help document what it means).
</blockquote></details>

Yep - went with a `gogoproto.castttype`, but it does clean up the casts nicely and still points to the original enum.
___
*[pkg/sql/sem/tree/backup.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-LxxAJweD_5E18xy1-QJ:-Ly-lfdO2bYvZNXsofqe:bgjc3x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c999c3165a0c41f54006870fe4bf0ed7d2c9f/pkg/sql/sem/tree/backup.go#L22)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

.02¢: the call sites, like the CDC one above, would read better, to me, if these were `tree.RequestedTables` and `tree.AllTables` or something like that --  on its own if you don't also know its type just seeing "tree.Partial" is a bit vague (though I suppose we mostly all use type-annotating editors so maybe it doesn't matter?).
</blockquote></details>

I agree. I went with `tree.RequestedDescriptors` and `tree.AllDescriptors` to include that particular databases can be requested (including empty databases).

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/sql/sem/tree/backup.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-LxxAJweD_5E18xy1-QJ:-Ly00g459f3yhL2N7gBi:b-55xah7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c999c3165a0c41f54006870fe4bf0ed7d2c9f/pkg/sql/sem/tree/backup.go#L22)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I agree. I went with `tree.RequestedDescriptors` and `tree.AllDescriptors` to include that particular databases can be requested (including empty databases).
</blockquote></details>

Also going to rename `TableCoverage` to `DescriptorCoverage` for the same reason.

**Review by dt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/backupccl/backup.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-LxxBYTsDs9lMTD9b3Q6:-Ly0-Y_pBZKN1NSsLOyD:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c999c3165a0c41f54006870fe4bf0ed7d2c9f/pkg/ccl/backupccl/backup.go#L80)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Ah - apologies for the confusion. The comment comes from the full backup RESTORE patch which changes this to a list. Going to make it a list here for now, but introduce the comment in the full backup RESTORE pr. Updated with a comment linking to an issue to move to a model where system tables opt-{in,out} whether to be included in a full cluster backup.
</blockquote></details>

:thumbsup: 
___
*[pkg/ccl/backupccl/backup.go, line 712 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-Ly-OFJw1k0VwVmNaDOo:-Ly0-rHD4YVVVkU5e-At:b1gb9k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c92c0042afa3beef998695a43d7dc0e208afdb6/pkg/ccl/backupccl/backup.go#L712)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Does this mean we can delete `defaultUserDBs` above ?
___
*[pkg/sql/sem/tree/backup.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-LxxAJweD_5E18xy1-QJ:-Ly00ZfX8Kq3DeC1z5aV:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c999c3165a0c41f54006870fe4bf0ed7d2c9f/pkg/sql/sem/tree/backup.go#L22)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I agree. I went with `tree.RequestedDescriptors` and `tree.AllDescriptors` to include that particular databases can be requested (including empty databases).
</blockquote></details>

:thumbsup:

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/backupccl/backup.proto, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43767#-LxxBCZy2dB_ui9rtJQ-:-Ly002OZ-89ora40i1eC:b-rnqzpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c999c3165a0c41f54006870fe4bf0ed7d2c9f/pkg/ccl/backupccl/backup.proto#L105)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Yep - went with a `gogoproto.castttype`, but it does clean up the casts nicely and still points to the original enum.
</blockquote></details>

Ah, even better!

**Comment by pbardea** [comment]
Thanks for the review!
bors r+

**Pull request merged**
