### PR TITLE
streamingccl: refining client API

### PR DESCRIPTION
**Pull request by dt**
This updates the streamclient API based on discussions between bulk and cdc
teams about how we want to handle state across cluster-to-cluster streams and
in particular multi-partition streams.

The first significant change here is that a consumer starts by asking
the producer to create a stream, which the client can then interact
with, specifically consume from it, update the point from which
consumption may resume in the future, and destroy it. This is done so
that the producer can potentially reserve or release resources, such as
setting down a protected timestamp, moving that timestamp up based on
those updates as to how far back consumption might resume, expire-out
a stream that has not been updated after some period, etc.

The second significant change is that a parition is no longer uniquely
identified and defined by a "parition address". Instead, when a client
asks the producer to "plan" the current stream and gets back a topology,
the partitions in that topology include an opaque "subscription token"
which is meaningful only to the producer of that stream, when presented
to its Subscribe() method. The topology still includes an address for
that parition, however it is now just a suggested address a consumer of
that partition may wish to use when creating their client.(In practice,
this subscription token is expected to be a serialization of a fragment
of a physical plan i.e. a serialized set of spans grouped to a given
node in the producing cluster, but that is up to the implementation of
the client and its backing producing cluster's API.)

A follow-up change is expected to also introduce opaque CheckpointTokens
which, like the opaque subscription tokens are intended to encapsulate
the state about what still needs to be emitted by the producer, rather
than having the whole API speak in terms of resolved timestamps. This is
to extend support for backfill checkpoints, without leaking that complexity
into the consumer. Additionally we expect to introduce a Subscription type
returned by the subscribe method, rather than raw channels, to make it
easier to manage lifecycle. These future changes are sketched in comments
in client.go.

Release note: none.

### CODE REVIEW

**Comment by miretskiy** [comment]
Informs #70927

**Comment by dt** [comment]
we have a worked example just to see how this might look:
```go

----------------------------------------------------------------------------- 

Everything below here was just a worked example, to play with the library and
see how checkpoint handling works in practice.

----------------------------------------------------------------------------- 

// This is the coordinator.
func MockConsumerJob(s Subscription) {
	out := make(chan producerMeta)

	var prog KVStreamFrontier
	var ingested hlc.Timestamp
	var cuttingOverTo hlc.Timestamp

	s := CreateStream("localhost:123", "tenant 3")

	// heartbeater tells src we're alive and advances our PTS there.
	go func() {
		for {
			s.Heartbeat(prog.MinTS())
			time.Sleep(30)
		}
	}()
	
	// progress-updater: Process updates from our consumer processors.
	go func() {
		for update := range out {
			prog.Advance(DecodeKVStreamFrontier(update.Checkpoint))
			ingested.Advance(update.maxIngestedTS)
		}
	}()
	
	// Run the actual consumers.
	for {
		p := s.Plan()
		var distFlow []func()
		for parition := range p {
			distFlow = append(flow,	
				partitionConsumerProc(out, consumerProcSpec{from: p.Src.Addr, p.SubscriptionToken, prog.Encode()}))
		}
		distflow.Run()
	}

	if cuttingOverTo.Less(ingested) {
		// we need to RevertRange()
	}
	// done!
}

type producerMeta struct {
	checkpoint CheckpointToken
	maxIngestedTS hlc.Timestamp
}

type consumerProcSpec struct {
	from util.UnresolvedAddr
	token []byte
	frontier EncodedKVStreamFrontier
}

// partitionConsumerProc models a distsql processor that runs consumption for 
// a kvstream partition. here the the work of "consuming" is counting the kvs.
// To model ingestion, incoming kvs are in a buffered count that is only flushed
// to the total from time to time.
func partitionConsumerProc(coord chan<- ProducerMeta, args consumerProcSpec) func() {
  return func() {
		var total int
		var buf []roachpb.KeyValue
		var bufTS, ingestedTS hlc.Timestamp
		
		sub := Subscribe(args.from, args.token, args.frontier)
		defer sub.Close() // Handle error
		
		var lastCheckpoint []byte
		for {
			select {
			case ev, ok := <-sub.Events:
				if !ok {
					// handle sub.Err -- it should be non-nil
					return
				}
				switch ev := ev.(type) {
				case StreamKVs: 
					buf = append(buf, ev.Payload...)
								bufTS.Forward(ev.MaxTS())
					buffered += 1
					// no checkpoint forwarded to coord
				case StreamCheckpoint: 
					lastCheckpoint = ev
				}
    		case <-ticker.Ch:			
			}
			
			if bufferd > 5 || time.Since(lastFlush) > time.Minute {
				// "flush" buffered kvs to our counter.
				total += len(buf)
				buf = buf[:0]
				maxTS.Forward(bufTS)
				lastFlush = time.Now()
				out <- ProducerMeta{lastCheckpoint, maxTS}
			}
		}		
	}
}
```

**Review by miretskiy — COMMENTED** [review]
> Reviewed 8 of 17 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71213)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/ccl/streamingccl/streamclient/client.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71213#-Mm-__bgBJIzN7BW13sq:-Mm-__bh-iTSRc7EXbAr:bbzul2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/adcfc0f2d56b7f4312e1567cd9949758da2cda83/pkg/ccl/streamingccl/streamclient/client.go#L27)):*
> ```Go
> // StreamID identifies a stream across both its producer and consumer. It is
> // used when the consumer wishes to interact with the stream's producer.
> type StreamID uint64
> ```

perhaps just int64?
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71213#-Mm-azqH0Ys6uw9iRUaN:-Mm-azqH0Ys6uw9iRUaO:b-p2v5ja) ([raw file](https://github.com/cockroachdb/cockroach/blob/adcfc0f2d56b7f4312e1567cd9949758da2cda83/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L45)):*
> ```Go
> 	}
> 
> 	// TODO(dt): if there is an existing stream ID, reconnect to it.
> ```

Presumably, we'd do this via some sort of Create options, as we discussed.

Come to think of it, we kinda have to support this anyway -- in case of ingesting job restarting, we need to restart with the old
streamID.  We kinda have to support this almost immediately.

**Review by dt — COMMENTED** [review]
I'm feeling like I want to merge what we got here pretty soon and then I or others can iterate on the remaining suggested API changes later, but I might not be able to do much more here in the next few weeks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71213#-:-MmPd8sl3u9TIP-pUaLl:b5111b2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/streamingccl/streamclient/client.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71213#-Mm-__bgBJIzN7BW13sq:-MmPcFmn6wSAY0PCjaEy:bvlxbd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/adcfc0f2d56b7f4312e1567cd9949758da2cda83/pkg/ccl/streamingccl/streamclient/client.go#L27)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

perhaps just int64?
</blockquote></details>

eh, do we really want it to be able to be negative?
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71213#-Mm-azqH0Ys6uw9iRUaN:-MmPcYnz2AYc5LFqYKRO:b-anfpad) ([raw file](https://github.com/cockroachdb/cockroach/blob/adcfc0f2d56b7f4312e1567cd9949758da2cda83/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L45)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Presumably, we'd do this via some sort of Create options, as we discussed.

Come to think of it, we kinda have to support this anyway -- in case of ingesting job restarting, we need to restart with the old
streamID.  We kinda have to support this almost immediately.
</blockquote></details>

I think we can actually just try to use the old ID to Plan() and see if it works -- worst case we get told it isn't valid (because it expired) and we make a new ID. But we'd want to then Plan() that new ID with our old Checkpoint token, to resume form the same timestamp? I dunno.

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71213)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/streamingccl/streamclient/client.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71213#-MlL5tkBN7NjrBoZuxdH-r2-65:-MmSWQr-BTAC9eLAZLtM:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce1d0fdc79bbcd3ecbe1dbdf15c320fe177500c/pkg/ccl/streamingccl/streamclient/client.go#L65)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

yeah, there's a TODO and I left the sketched out type in the comment. I just wanted to stop here, with SubscriptionToken implemented, since there's a lot of churn.
</blockquote></details>

Ack.
___
*[pkg/ccl/streamingccl/streamclient/client.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71213#-Mm-__bgBJIzN7BW13sq:-MmSVQld5zJLeLvcNMlQ:bsewsv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/adcfc0f2d56b7f4312e1567cd9949758da2cda83/pkg/ccl/streamingccl/streamclient/client.go#L27)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

eh, do we really want it to be able to be negative?
</blockquote></details>

Just my old c++ habits of not using uints unless representing bits.  "You should not use the unsigned integer types such as uint32_t, unless there is a valid reason such as representing a bit pattern rather than a number, or you need defined overflow modulo 2^N. In particular, do not use unsigned types to say a number will never be negative. Instead, use assertions for this." from https://google.github.io/styleguide/cppguide.html#Integer_Types
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71213#-Mm-azqH0Ys6uw9iRUaN:-MmSWWqL5QCqZTUHMUhn:b-e6aldn) ([raw file](https://github.com/cockroachdb/cockroach/blob/adcfc0f2d56b7f4312e1567cd9949758da2cda83/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L45)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think we can actually just try to use the old ID to Plan() and see if it works -- worst case we get told it isn't valid (because it expired) and we make a new ID. But we'd want to then Plan() that new ID with our old Checkpoint token, to resume form the same timestamp? I dunno.
</blockquote></details>

Ack.  Maybe we'll change that to CreateOrConnect at some point.

**Pull request merged**
