### PR TITLE
kv: lie better about commits that are really rollbacks

### LINKED ISSUE #28554: kv: client already committed or rolled back the transaction errors
I'm seeing these error when running a modified `loadgen/kv`:

```
2018/08/13 20:09:40 pq: TransactionStatusError: client already committed or rolled back the transaction (REASON_UNKNOWN)
```

Reproduction steps:
1. apply the following patch to `loadgen`:
```
diff --git a/kv/main.go b/kv/main.go
index 3e02375..1f78614 100644
--- a/kv/main.go
+++ b/kv/main.go
@@ -420,7 +420,7 @@ func setupCockroach(dbURLs []string) (database, error) {
        }

        buf.Reset()
-       buf.WriteString(`UPSERT INTO test.` + *tableName + ` (k, v) VALUES`)
+       buf.WriteString(`INSERT INTO test.` + *tableName + ` (k, v) VALUES`)

        for i := 0; i < *batch; i++ {
                j := i * 2
@@ -429,6 +429,7 @@ func setupCockroach(dbURLs []string) (database, error) {
                }
                fmt.Fprintf(&buf, ` ($%d, $%d)`, j+1, j+2)
        }
+       buf.WriteString(` ON CONFLICT DO NOTHING`)

        writeStmt, err := db.Prepare(buf.String())
        if err != nil {
```
2. run two instances of `kv` with the same seed: `./kv --read-percent=0 --seed=1234`
3. observe errors almost immediately

### LINKED ISSUE #28796: roachtest: interleavedpartitioned failure: client already committed or rolled back
#28795 fixes up the test setup for `interleavedpartitioned` which seems to have been masking failures. Now when I run it I frequently see failures like:

```
central: Error: pq: TransactionStatusError: client already committed or rolled back the transaction (REASON_UNKNOWN)
central: Error:  Process exited with status 1
```

This fails the `central` workload which in turn fails the test.

@andreimatei for triage.

### PR DESCRIPTION
**Pull request by andreimatei**
When a client tries to commit a txn that has performed writes at an old
epoch but has only done reads at the current epoch, one of the
TxnCoordSender interceptors turns the commit into a rollback (for
reasons described in the code).
This patch completes that interceptor's lie by updating the txn status
upon success to COMMITTED instead of ABORTED. Since a commit is what the
client asked for, it seems sane to pretend as best we can that that's
what it got. In particular, this is important for the sql module, where
the ConnExecutor looks at the txn proto's status to discriminate between
cases where a "1pc planNode" already committed an implicit txn versus
situations where it needs to commit it itself. This was causing the
executor to think the txn was not committed and to attempt to commit
again, which resulted in an error.
I don't know if we like the ConnExecutor looking at the proto status,
but I'll leave that alone.

Fixes #28554
Fixes #28796

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28872#-:-LKPDNlGAXisFeAA3OLT:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/kv/txn_interceptor_heartbeat.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28872#-LKPDI2-EzNdMLI86A1w:-LKPDI2-EzNdMLI86A1x:b-9f9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba2f8ccaff613e5fcb239335eb7b257045696bc6/pkg/kv/txn_interceptor_heartbeat.go#L285)):*
> ```Go
> 		// Note: if we sent an EndTransaction and got back a successful response, we
> 		// expect br.Txn to be filled.
> 		br.Txn.Status = roachpb.COMMITTED
> ```

Do we need to clone the `txn`?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28872)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/kv/txn_interceptor_heartbeat.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28872#-LKPDI2-EzNdMLI86A1w:-LKPHSoj8njrwS8V0tUd:b9c6dxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba2f8ccaff613e5fcb239335eb7b257045696bc6/pkg/kv/txn_interceptor_heartbeat.go#L285)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to clone the `txn`?
</blockquote></details>

hmm interesting question. I don't think so?
Like, is the txn inside the `BatchResponse` supposed to be shared like the one in the `BatchRequest`?

Seems that the server sometimes clones the txn before putting it in the br:
https://github.com/cockroachdb/cockroach/blob/4004c1e37f6bf9dcd1024cff7f00ed606e771f44/pkg/storage/replica.go#L5915

but sometimes doesn't:
https://github.com/cockroachdb/cockroach/blob/4004c1e37f6bf9dcd1024cff7f00ed606e771f44/pkg/storage/replica.go#L6377
https://github.com/cockroachdb/cockroach/blob/4004c1e37f6bf9dcd1024cff7f00ed606e771f44/pkg/storage/store.go#L2985

In this latter case, the store proceeds to mutate the txn itself... That's bad, isn't it?
I wonder who should be in charge of the cloning... I'm starting to hate the txn in the response even more than before.


(note to self - we mutate br.Txn similarly above too)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28872)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/kv/txn_interceptor_heartbeat.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28872#-LKPDI2-EzNdMLI86A1w:-LKSUM6O37xCkHTks7vd:b-5cmhgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba2f8ccaff613e5fcb239335eb7b257045696bc6/pkg/kv/txn_interceptor_heartbeat.go#L285)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

hmm interesting question. I don't think so?
Like, is the txn inside the `BatchResponse` supposed to be shared like the one in the `BatchRequest`?

Seems that the server sometimes clones the txn before putting it in the br:
https://github.com/cockroachdb/cockroach/blob/4004c1e37f6bf9dcd1024cff7f00ed606e771f44/pkg/storage/replica.go#L5915

but sometimes doesn't:
https://github.com/cockroachdb/cockroach/blob/4004c1e37f6bf9dcd1024cff7f00ed606e771f44/pkg/storage/replica.go#L6377
https://github.com/cockroachdb/cockroach/blob/4004c1e37f6bf9dcd1024cff7f00ed606e771f44/pkg/storage/store.go#L2985

In this latter case, the store proceeds to mutate the txn itself... That's bad, isn't it?
I wonder who should be in charge of the cloning... I'm starting to hate the txn in the response even more than before.


(note to self - we mutate br.Txn similarly above too)
</blockquote></details>

sprinkled some cloning. PTAL

**Review by nvb — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28872#-:-LKSUe2F58I7oSOo-Q-G:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by andreimatei** [comment]
spurious url lint failure...?

bors r+

**Pull request merged**
