### PR TITLE
jobs: add a COMPLETE JOB control job query

### LINKED ISSUE #57407: streaming: introduce a new jobs action to conclude ingestion job
The ingestion job needs a signal in order to know it should stop ingesting the stream and revert back to a consistent. In the prototype implementation, this was done OnFailOrCancel. However, we should provide a first-class way to conclude an ingestion job.

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds `COMPLETE JOB job_id` as a new control job query that
allows for a job to go through a new lifecycle:

`COMPLETE_REQUESTED` -> `COMPLETING` -> `COMPLETED`

The motivation for this new control query is the stream ingestion job
being developed as a part of cluster to cluster streaming. We need to
provide the user a way to "cutover", i.e. bring the destination cluster
being ingested to a consistent state, thereby making it ready to
serve traffic.

We needed a way to inform the ingestion job to stop ingesting data, and
revert the ingested data to a consistent ts, before declaring the
cluster as usable. The existing `CANCEL JOB` was not sufficient for this
because if the ingestion job fails, or is cancelled, we want to
ClearRange all the ingested data and not revert it to a consistent
state. Note, none of these stream ingestion job changes are in this PR,
this is just to give the motivation behind this change.

The semantics of `COMPLETE JOB` are very similar to `CANCEL JOB`. The
job is first moved into a `CompleteRequested` state by the node on which
the control query is executed. The node running the job either adopts
this `CompleteRequested` job, or wait for a progress update to raise a
sentinel error, before stopping the executing job, and moving it to a
`Completing` state. This is where the hook is called, after which the jo
b is moved into a `Completed` state.

The interaction of this state with other control commands can be better
understood by the tests added in this PR.

Fixes: #57407

Release note (sql change): Added `COMPLETE JOB` control job query to
allow for specific logic to be executed once the job is "completed".

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59878)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @miretskiy, and @pbardea)

___
*[pkg/jobs/registry.go, line 1256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-MT106jv2HIRV_uLoVIT:-MT106jwAO4_RIithjvU:b-hjwv8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d14fc66dd7b71f8a348b98248d60cbdb076c40b/pkg/jobs/registry.go#L1256)):*
> ```Go
> 			defer jm.CurrentlyRunning.Dec(1)
> 			if cr, ok := resumer.(CompleteRequester); ok {
> 				fmt.Println("COMING HERE")
> ```

nit: leftover debugging println

**Review by pbardea — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59878)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/jobs/adopt.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-MT2kALh-0onS-xi7AmH:-MT2kALh-0onS-xi7AmI:b-pugeo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d14fc66dd7b71f8a348b98248d60cbdb076c40b/pkg/jobs/adopt.go#L292)):*
> ```Go
> 					// Set the FinalResumeError to the special "user canceled job" error.
> 					// This is used as a sentinel value when unpausing a job to determine
> 					// the state the job should be resumed into.
> ```

nit: can we move this comment and the one in StatusCompleting 1 line below where it is since it's not referring to the error set on the immediately following line.
___
*[pkg/jobs/jobs.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-MT2kFwyB_aoHZL2lAQq:-MT2kFwyB_aoHZL2lAQr:b-okgro3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d14fc66dd7b71f8a348b98248d60cbdb076c40b/pkg/jobs/jobs.go#L546)):*
> ```Go
> // completeRequested sets the status of the tracked job to complete-requested.
> // It does not directly mark the job as completed; it expects the node that runs
> // the job will actively cancel it when it notices that it is in state
> ```

Should this read it expects the node that runs the job will actively _complete_ it when it notices...?
___
*[pkg/jobs/jobs.go, line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-MT2kK6K-rM6xSgaPWiG:-MT2kK6K-rM6xSgaPWiH:b-1zlctt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d14fc66dd7b71f8a348b98248d60cbdb076c40b/pkg/jobs/jobs.go#L552)):*
> ```Go
> ) error {
> 	return j.Update(ctx, func(txn *kv.Txn, md JobMetadata, ju *JobUpdater) error {
> 		if md.Payload.Noncancelable {
> ```

Should this be `!md.Payload.Completable`?

I wonder with TestRegistryLifecycle didn't catch this?
___
*[pkg/jobs/jobs.go, line 733 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-MT2kRfI6UXWupYzk7y8:-MT2kRfI6UXWupYzk7y9:b-fhwpv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d14fc66dd7b71f8a348b98248d60cbdb076c40b/pkg/jobs/jobs.go#L733)):*
> ```Go
> 		md.Payload.FinishedMicros = timeutil.ToUnixMicros(j.registry.clock.Now().GoTime())
> 		ju.UpdatePayload(md.Payload)
> 		// TODO(adityamaru): Should we update progress to 1, as in succeeded?
> ```

I think that would be good.
___
*[pkg/jobs/registry.go, line 1225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-MT2kl_V5iiBtoPh4kpX:-MT2kl_V5iiBtoPh4kpY:b-ir514r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d14fc66dd7b71f8a348b98248d60cbdb076c40b/pkg/jobs/registry.go#L1225)):*
> ```Go
> 		if jobErr != nil {
> 			return errors.NewAssertionErrorWithWrappedErrf(jobErr,
> 				"job %d: successful bu unexpected error provided", *job.ID())
> ```

nit: (and unrelated `s/bu/but`)
___
*[pkg/jobs/registry.go, line 1230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-MT2k_iG4Ox9ZCW7bjIk:-MT2k_iG4Ox9ZCW7bjIl:bc3bc81) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d14fc66dd7b71f8a348b98248d60cbdb076c40b/pkg/jobs/registry.go#L1230)):*
> ```Go
> 			// If it didn't succeed, we consider the job as failed and need to go
> 			// through reverting state first.
> 			// TODO(spaskob): this is silly, we should remove the OnSuccess hooks and
> ```

nit: Not related to this PR but since we're here... aren't these `OnSuccess` hooks removed? If so, I think we can remove this TODO.
___
*[pkg/jobs/registry.go, line 1242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-MT2kVXG6mT0lO3SUiug:-MT2kVXH0A7eo43Hbp9Z:b-i0biol) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d14fc66dd7b71f8a348b98248d60cbdb076c40b/pkg/jobs/registry.go#L1242)):*
> ```Go
> 			return errors.Wrapf(err, "job %d: could not mark as completed: %v", *job.ID(), jobErr)
> 		}
> 		// TODO(adityamaru): Should we return nil instead?
> ```

Completing a job should leave it in a successful state I think? Does it make sense to step the job through `StatusSucceeded` rather than the `StatusCompleted` state?
___
*[pkg/jobs/registry.go, line 1248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-MT2lQJ4Ahpee0YXXIpc:-MT2lQJ4Ahpee0YXXIpd:b-suobg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d14fc66dd7b71f8a348b98248d60cbdb076c40b/pkg/jobs/registry.go#L1248)):*
> ```Go
> 			// If we can't transactionally mark the job as completing then it will be
> 			// restarted during the next adopt loop and it will be retried.
> 			return errors.Wrapf(err, "job %d: could not mark as completing: %s", *job.ID(), jobErr)
> ```

nit: I think `%+v` will give a more rich description of the error, which could be nice here for debugging/error reporting.

**Review by pbardea — CHANGES_REQUESTED** [review]
Looking good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-:-MT2mLzQApkdCIEYC24i:br2sbr6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/jobs/jobs_test.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59878#-MT2m0ywES4TGQAHpwZP:-MT2m0ywES4TGQAHpwZQ:bcpwlr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d14fc66dd7b71f8a348b98248d60cbdb076c40b/pkg/jobs/jobs_test.go#L101)):*
> ```Go
> 		Username:      payload.UsernameProto.Decode(),
> 		Progress:      progressDetail,
> 		Completable:   payload.Completable,
> ```

Do we have a test that tried to complete a non completable job, I might have missed it? But if not, that would be a good one to add too.

**Comment by miretskiy** [comment]
@adityamaru Still working through this PR.

**Comment by miretskiy** [comment]
I'm a bit worried about adding a brand new job control statement, plus transitions, etc.
Too much complexity and quite a big hammer.

We want to signal to the resumer that it should exit it's "infinite loop".  Can we accomplish this by e.g.
creating a sentinel cluster setting (say an int), loading this int when resumer starts, then starting a go routine
that periodically polls that setting.  Exit if value is initial plus 1?

**Comment by adityamaru** [comment]
> I'm a bit worried about adding a brand new job control statement, plus transitions, etc.
> Too much complexity and quite a big hammer.
> 
> We want to signal to the resumer that it should exit it's "infinite loop". Can we accomplish this by e.g.
> creating a sentinel cluster setting (say an int), loading this int when resumer starts, then starting a go routine
> that periodically polls that setting. Exit if value is initial plus 1?

For what it's worth only a stream ingestion job will be `Completable`, so there is little risk of accidentally "completing" a job that shouldn't be. I started off skeptical, but the implementation was surprisingly painless to reason about. It seems like the state transitions are well tested and we are implementing a close copy of reverting except with a different hook. To me, a well-tested control statement that _could_ be reused by future job types to wrap up their work seems like a better option? Curious where your main concern lies considering the state transition logic is almost identical to the OnFailOrCancel logic.

**Comment by adityamaru** [comment]
An alternate approach is being worked on at #60291.

**Comment by adityamaru** [comment]
Closing in favour of #60291.

**Pull request closed without merging**
