### PR TITLE
statusccl: fix flaky TestTenantStatusAPI txn_id_resolution

### PR DESCRIPTION
**Pull request by j82w**
The txn resolution add a txn id to the cache, and 
then in a separate call updates the txn id with the 
fingerprint. The test previously assumed if there 
was a record it would always have a valid fingerprint, 
but that is not true. The test is modified to add retry 
logic to wait for the fingerprint to be updated. The 
retry time was set to always be 1 minute, because  
SucceedsSoon only waits 5 seconds for race scenario 
which is not enough time for the resolution to complete.

Epic: none
part of: #99770

Release note: none

Epic: CRDB-25476

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100817#-NSMLfym-U91m6L6JyaZ:-NSMLfym-U91m6L6Jya_:b-qn6qwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49c1df22b81867cdd79b9957ab7ae5c9f54d8b8/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L1231)):*
> ```Go
> 			}
> 			return nil
> 		}, 1*time.Minute)
> ```

Is there a concern this wait time could increase too much the time of the test and it could cause issue under stress? Should this test be skipped under stress?

**Comment by j82w** [comment]
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100817#-NSMLfym-U91m6L6JyaZ:-NSMXzZxCTMhkgsHYWnh:b-uvx6po) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49c1df22b81867cdd79b9957ab7ae5c9f54d8b8/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L1231)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

It's already skipped.
https://github.com/cockroachdb/cockroach/blob/659b90b812cfdcfdd976f4da9d1348fe7c6e50ae/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L59
</blockquote></details>

The extended time is probably not necessary now that it actually retries on default fingerprint, but I made the change to be on the safe side.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100817#-:-NSNTmPR3qve6eMP0F1x:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

**Pull request merged**
