### PR TITLE
sql: fix Usage privilege on Tables/DBs after upgrading from 20.1

### PR DESCRIPTION
**Pull request by RichardJCai**
In 20.2, I made a mistake when introducing USAGE privilege by
adding it before ZONECONFIG privilege in the bitfield.
Due to this, when updating from 20.1 to 20.2, ZONECONFIG privilege will be
interpretted as USAGE.

Fortunately, ZONECONFIG was only a valid privilege on tables and databases
while USAGE is invalid on both those objects. Due to this, whenever we encounter
USAGE on a privilege descriptor versioned 20.1 (InitialVersion) we can fix
this by removing the bit for USAGE and adding the bit for ZONECONFIG on the
privilege descriptor.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Can you go back and create a 20.1 backup that you restore in the style of https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/restore_old_versions_test.go#L31 to make sure that post-restore everything works as you might expect?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-:-M_SAhbqErzAXspzRAi4:b-4xbmkn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/catalog/descpb/privilege.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_S9w4iEeR540cZMQUk:-M_S9w4iEeR540cZMQUl:b-un0cb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6004f1f9dbcc9be0a03a2cdc220347dee97550e/pkg/sql/catalog/descpb/privilege.go#L226)):*
> ```Go
> 	// InitialVersion is for descriptors that were created in versions 20.1 and
> 	// earlier.
> 	if p.Version == InitialVersion {
> ```

What happens if you create a descriptor in 20.1 and grant ZONCONFIG in 20.1 and then set an owner in 20.2?

**Review by RichardJCai — COMMENTED** [review]
Will do

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-:-M_SEpyfEiwU0GxfnWg9:bebrt1w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/descpb/privilege.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_S9w4iEeR540cZMQUk:-M_SErBpBn9nkrXAVoW9:bjeu1ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6004f1f9dbcc9be0a03a2cdc220347dee97550e/pkg/sql/catalog/descpb/privilege.go#L226)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What happens if you create a descriptor in 20.1 and grant ZONCONFIG in 20.1 and then set an owner in 20.2?
</blockquote></details>

Is it wrong to assume that this would be called before you try to set an owner in 20.2? I thought you'd have to retrieve the descriptor which then would be fixed before an owner is set.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/catalog/descpb/privilege.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_S9w4iEeR540cZMQUk:-M_SGX_X-TbKbWB-Hil8:b-4fz4is) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6004f1f9dbcc9be0a03a2cdc220347dee97550e/pkg/sql/catalog/descpb/privilege.go#L226)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Is it wrong to assume that this would be called before you try to set an owner in 20.2? I thought you'd have to retrieve the descriptor which then would be fixed before an owner is set.
</blockquote></details>

I mean 20.2 before this patch release. I'm asking whether you can have `Version == OwnerVersion` and still have the wrong bit set.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/descpb/privilege.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_S9w4iEeR540cZMQUk:-M_SIxo-9fR0y6HTS6Wg:b-abksve) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6004f1f9dbcc9be0a03a2cdc220347dee97550e/pkg/sql/catalog/descpb/privilege.go#L226)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I mean 20.2 before this patch release. I'm asking whether you can have `Version == OwnerVersion` and still have the wrong bit set. 
</blockquote></details>

Ah I see what you mean. If they're on a 20.2 patch release before this version, if the descriptor is corrupted, it would have to have been created in 20.1 (we don't actually update the Version field) and have Version == InitialVersion.

We never actually update the Version field so I believe this is fine.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/catalog/descpb/privilege.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_S9w4iEeR540cZMQUk:-M_SO7J54YhBE7jLqEal:b45zxhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6004f1f9dbcc9be0a03a2cdc220347dee97550e/pkg/sql/catalog/descpb/privilege.go#L226)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Ah I see what you mean. If they're on a 20.2 patch release before this version, if the descriptor is corrupted, it would have to have been created in 20.1 (we don't actually update the Version field) and have Version == InitialVersion.

We never actually update the Version field so I believe this is fine.
</blockquote></details>

If we don't upgrade it, what does it mean?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/descpb/privilege.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_S9w4iEeR540cZMQUk:-M_SPAKX8jWPqbqElBgG:b-bpumhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6004f1f9dbcc9be0a03a2cdc220347dee97550e/pkg/sql/catalog/descpb/privilege.go#L226)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

If we don't upgrade it, what does it mean?
</blockquote></details>

When I first added ownership, instead of deciding to migrate all table descriptors to have owners, I added a version field to determine if having an empty owner would be valid.

https://github.com/RichardJCai/cockroach/blob/0faf0a1a168105551c0d6d126eff25068e865e01/pkg/sql/authorization.go#L117

The version field is only used currently to validate if having an empty owner is valid
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/catalog/descpb/privilege.go#L299

**Review by ajwerner — COMMENTED** [review]
:lgtm: mod a backup test 

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-:-M_SUWnV2sCjC1pE76Ru:b-v8z3tw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/catalog/descpb/privilege.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_S9w4iEeR540cZMQUk:-M_SUEj7ATZKupirLHDx:bg4z8vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6004f1f9dbcc9be0a03a2cdc220347dee97550e/pkg/sql/catalog/descpb/privilege.go#L226)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

When I first added ownership, instead of deciding to migrate all table descriptors to have owners, I added a version field to determine if having an empty owner would be valid.

https://github.com/RichardJCai/cockroach/blob/0faf0a1a168105551c0d6d126eff25068e865e01/pkg/sql/authorization.go#L117

The version field is only used currently to validate if having an empty owner is valid
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/catalog/descpb/privilege.go#L299
</blockquote></details>

Cool, I’m satisfied. Nit:early return if the version is new enough. Also add more commentary indicating that the version doesn’t get upgraded today and we’ll have fixed this bug by the time we ever do want to do the upgrade.

**Comment by RichardJCai** [comment]
Added a backup test and some logic some restore works. cc @cockroachdb/bulk-io and @pbardea for review

**Review by pbardea — APPROVED** [review]
Restore change LGTM

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-:-M_Y86NXATilQEbkjDbS:b-8ceaer)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nihalpednekar, @pbardea, and @RichardJCai)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_Y80iA78Fg50VSQcz6:-M_Y80iA78Fg50VSQcz7:btminz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5125ab95a4db318184db8580f508223a66206fbd/pkg/ccl/backupccl/restore_old_versions_test.go#L208)):*
> ```Go
> 		err := os.Symlink(exportDir, filepath.Join(tmpDir, "foo"))
> 		require.NoError(t, err)
> 		sqlDB.Exec(t, `RESTORE FROM $1`, LocalFoo)
> ```

A comment mentioning that this only affects cluster restores since database restores reset privileges on the descriptor wouldn't hurt
___
*[pkg/ccl/backupccl/testdata/restore_old_versions/create_with_privileges.sql, line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_Y7OiwBexA5MMX_OW-:-M_Y7OiwBexA5MMX_OW0:b-w985r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5125ab95a4db318184db8580f508223a66206fbd/pkg/ccl/backupccl/testdata/restore_old_versions/create_with_privileges.sql#L2)):*
> ```TSQL
> -- The below SQL is used to create the data that is then exported with BACKUP
> -- finish this comment
> ```

Looks like this comment needs to be finished, but it'd be good to mention the version that you ran this against to generate the backup

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65010)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nihalpednekar, @pbardea, and @RichardJCai)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_Y80iA78Fg50VSQcz6:-M_aEyOi85Sf5g12v1sa:b-jb8fm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5125ab95a4db318184db8580f508223a66206fbd/pkg/ccl/backupccl/restore_old_versions_test.go#L208)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

A comment mentioning that this only affects cluster restores since database restores reset privileges on the descriptor wouldn't hurt
</blockquote></details>

Added it to the function header comment
___
*[pkg/ccl/backupccl/testdata/restore_old_versions/create_with_privileges.sql, line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65010#-M_Y7OiwBexA5MMX_OW-:-M_aF1OtCUkEOFq8xYm8:b-p4ybu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5125ab95a4db318184db8580f508223a66206fbd/pkg/ccl/backupccl/testdata/restore_old_versions/create_with_privileges.sql#L2)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Looks like this comment needs to be finished, but it'd be good to mention the version that you ran this against to generate the backup
</blockquote></details>

Oops, fixed.

**Comment by RichardJCai** [comment]
Thanks for reviewing!

bors r+

**Pull request merged**
