### PR TITLE
sql: builtins implement missing trig builtins

### PR DESCRIPTION
**Pull request by lancerutkin**
`sql: break out math builtins to separate file from builtins`
    
Previously, the math builtins were all in the master builtins file.
The builtins file was too large.
This patch moves the math builtins to a separate file to make builtins more manageable.
    
Release note: None

`sql: add degree trig and hyperbolic trig builtins`
    
Previously, only radian trig builtins were supported.
All trig builtins were also previously untested.
Adds the missing trig builtins and adds tests for all trig builtins

Release note: None

### CODE REVIEW

**Comment by lancerutkin** [comment]
@jordanlewis blathers couldn't find you, but cc'ing you here for issue #47545

**Review by jordanlewis — COMMENTED** [review]
This is great - thanks, Lance! Annoying ask, but do you happen to still have your commit history in your `git reflog` for the move and for the additions, separated out? It's a lot easier that way. I'm going to hold off on reviewing this until you push those two commits, or let me know you don't have them separated out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47627#-:-M5AMAybC9SGCbWUji_P:bpy0t54)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lancerutkin)

___
*[pkg/sql/sem/tree/testdata/eval/trig, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47627#-M5AMRAKDpJv__RS0m_p:-M5AMRAL44zHpTa2HfZ0:b-r76xsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4d2d23525175b70298a5b972d8bceaa35de2a6f/pkg/sql/sem/tree/testdata/eval/trig#L111)):*
> ```
> atanh(0)
> ----
> 0.0
> ```

small nit: we like to always have a newline at the end of these files

**Comment by lancerutkin** [comment]
Not a problem at all, Jordan. I've broken those commits out and made the nit fix, let me know if you need anything other updates. 2 issues I'd like to point out:

1. some interesting behavior I noticed when I was adding tests. Notably, when a query like `acos(cos(1.0))` is run, it won't return 1.0, but instead 0.99999998 (I may be off on a sigfig or two. With `acosd(cosd(1.0))`, the precision is even worse. Maybe documentation should be updated somewhere?

2. I noticed there are some custom errors for certain math builtins, sqrt(-1), for instance. Maybe we'd like to add custom errors for inverse sine/cosine outside of the bounds [-1, 1]?

Let me know on either front. Happy to add that to this PR.

**Review by jordanlewis — COMMENTED** [review]
Hi - this :lgtm:, thanks for including both commits. It looks like there's something wrong with the generated docs though. Can you try running `make generate` and including the diffs from that?

> Reviewed 1 of 7 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47627#-:-M5Q18Ot1gTW4ndOPHfi:bd2s8up)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @lancerutkin)

**Review by jordanlewis — COMMENTED** [review]
Looks good, thanks. I think this needs one more rebase on top of master, hopefully we can merge later today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47627#-:-M5X-gMeAEZRO-I_atAB:bkr90hk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @lancerutkin)

**Comment by jordanlewis** [comment]
Thank you!

bors r+

**Comment by lancerutkin** [comment]
Jordan, wondering if you can offer any guidance on the build failure? Looks like `roachtest` failed. Since my last successful build, I just resolved the merge conflicts that existed with master. Any pointers welcome.

**Comment by jordanlewis** [comment]
It looks like some infrastructure flaked. I think we're good to go here, thanks for rebasing again - I'll try to merge again now.

bors r+

**Comment by SWDevAngel** [comment]
@lancerutkin Hi Lance. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)

**Pull request merged**
