### PR TITLE
sql: checksum backup/restore files

### PR DESCRIPTION
**Pull request by danhhz**
First commit is https://github.com/cockroachdb/cockroach/pull/9375.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9378)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/backup.go, line 245 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9378#-KRhwMewQ11Amjcn2llR:-KRhwMex1tRyhzSP9WtN:b-ipfptz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b0d33414488f48b77863dee62810da0b8832e6/sql/backup.go#L245)):*
> ```Go
> 	// is non-zero, it'll have to be derived from startKey and endKey.
> 
> 	f, err := os.Open(path)
> ```

need a `defer f.Close()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9378)*

**Comment by paperstreet** [comment]
@RaduBerinde, is this the fast crc?

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/backup.go, line 245 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9378#-KRhwMewQ11Amjcn2llR:-KRiI2jZtzGse58WTbsl:b-o0x3kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b0d33414488f48b77863dee62810da0b8832e6/sql/backup.go#L245)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> need a `defer f.Close()`
</details>
Good catch. Done here and the other one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9378#-:-KRiILfCLIB5vZYzD7mR:bccdpvq)*

**Comment by mjibson** [comment]
It's the fast CRC: https://github.com/golang/go/commits/master/src/hash/crc32

:lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9378#-:-KRiQ0ZEo_lvRNiZ0-aq:b-gcjhv8)*

**Comment by RaduBerinde** [comment]
No, Castagnoli is faster than IEEE

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9378#-:-KRi_iO3y6Tu2SWHxdZX:bv68eif)*

**Comment by RaduBerinde** [comment]
Well, at least it will be in go1.8 :)

Benchmarks here: https://gist.github.com/RaduBerinde/6b6c6257a056259f03038531b329b2cb

Truth be told, they're both pretty damn fast with recent Intel archs.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9378#-:-KRiaL_kaCEc2ymgUubG:b-ym7uie)*

**Comment by paperstreet** [comment]
Switched to crc32-c

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9378#-:-KRieteqZbiaGhL31rl5:b-tur29g)*

**Comment by RaduBerinde** [comment]
CRC32-C change LGTM

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9378#-:-KRigDcU2bRLh2zu_fvR:b-8nzguw)*

**Comment by paperstreet** [comment]
TFTRs!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9378#-:-KRilk8XeH_t3zNx98_K:bz5mair)*

**Pull request merged**
