### PR TITLE
sql: require enterprise license when creating UDF or SP with PL/pgSQL

### LINKED ISSUE #114602: sql: make PL/pgSQL and SP enterprise-only
We've been asked to make PL/pgSQL and SP enterprise-only in 23.2. This ticket tracks that work.

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit introduces an enterprise license check when we attempt to create a function using PL/pgSQL language. Most of the changes in this commit are about moving existing logic tests from `pkg/sql/logictest` path into `pkg/ccl/logictestccl` - some files are moved fully while for a few only the necessary contents are moved.

Co-authored by @michae2.

Fixes: #114602.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
For some reason I could no longer push to michae2/plpgsqlccl branch after closing #114260, so I created the PR from a branch in my fork.

**Review by rharding6373 — COMMENTED** [review]
I think this needs a new test in pkg/sql/logictest/testdata/logic_test like https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/multi_region#L1, which verifies that using PL/pgSQL results in the expected CCL error.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115657#-:-NkwGipLDky0PzqP1nsc:bao14dr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
Good point, done.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work on the heavy lifting!

I think that Michael or another responsible party should also take a look before merging (I was just passing through...).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115657#-:-NkwTBo33v_xPARBLluV:bema7x8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_license` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115657#-NkwSCSb0K8-OQWafGPx:-NkwSCSb0K8-OQWafGPy:b3uh1ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb416e1062c8a101fdf4551c1ff07899a6540ec/pkg/sql/logictest/testdata/logic_test/plpgsql_license#L4)):*
> ```
> 
> statement error pgcode XXC01 pq: using PL/pgSQL requires a CCL binary
> CREATE OR REPLACE FUNCTION f() RETURNS RECORD AS $$
> ```

Add another test for `CREATE PROCEDURE ... LANGUAGE PLpgSQL`, too.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115657)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_license` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115657#-NkwSCSb0K8-OQWafGPx:-NkxB6_V7a_n2VbA2kLW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb416e1062c8a101fdf4551c1ff07899a6540ec/pkg/sql/logictest/testdata/logic_test/plpgsql_license#L4)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Add another test for `CREATE PROCEDURE ... LANGUAGE PLpgSQL`, too.
</blockquote></details>

Done.

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you for picking this up!

> Reviewed 50 of 53 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115657#-:-NkxhzBr4cPe2HS389Li:b-k522n4)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373)

**Comment by yuzefovich** [comment]
blathers backport 23.2

**Pull request merged**
