### PR TITLE
jobs: gate reading created_by field on cluster version

### PR DESCRIPTION
**Pull request by dt**
Release note (bug fix): fix a bug where a jobs could fail to run during version upgrades

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
tyvm, :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52475#-:-ME469Cp90SSOa8JGURW:bb4y9xb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52475#-:-ME48jr82hoTM71soaK1:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @miretskiy)

**Review by spaskob — COMMENTED** [review]
Is this going to work correctly if a cluster is upgraded but not finalized and an upgraded node runs the scheduler which tries to insert a scheduled job?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52475#-:-ME8kvPa1BeIoUCuKqIj:b-2lxj7i)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @miretskiy)

**Review by dt — COMMENTED** [review]
I think the schedule creation paths and schedule executor _should_ be gated on the same setting to avoid creating schedules that won't get run, but I'm more concerned about this one for now, since it can crash the job-adoption loop.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52475#-:-MEQGfL-8oPyyOY0edaN:b-9xe0vs)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @miretskiy)

**Review by spaskob — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52475#-:-MER4lUO95AdT72Lb5XD:b-1m4vin)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @miretskiy)

**Pull request merged**
