### PR TITLE
colrpc: add a comment about runnerCtx check in sendBatches

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
I think it's good to program defensively like this unless there are negative effects. Should we instead change it to a panic? Or why do we even need the `runnerCtx` field? Can we remove it and just use the passed in `ctx`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59835#-:-MT0TGKr4xMjg3e6vno3:b-lu24nn)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
The negative side of having this `if` condition that is always false is that it's confusing.

I switched to using an assertion.

The `runnerCtx` was added in #40334, and I'm guessing it was needed to avoid having the streamID tag in inputs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59835#-:-MT1mHZ90M1Ggx_R5vuJ:bmlqgwr)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59835#-:-MT53f5E5T2NuEn7vi-A:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
Turns out, the check is needed by the test, so I reverted the change and left a comment instead.

TFTR!

bors r+

**Pull request merged**
