### PR TITLE
server: explain and simplify the ReadyFn handling in (*Server).Start.

### PR DESCRIPTION
**Pull request by tbg**
Explain and simplify the ReadyFn handling in `(*Server).Start`.

Tangentially related to #48273.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
I like this, it is more readable.

(this may want a backport too)

**Comment by tbg** [comment]
@bdarnell can I get your opinion here? With this change, we signal readiness when the server really is truly ready to serve requests, which in particular means it was able to write to KV (write sync node status). This means that when restarting nodes while a majority is down with `--background` will block, as is demonstrated by the failure of `acceptance/cli/node-status` on this PR. It's unclear to me what we actually want out of this flag, but if users are supposed to be using this from systemd, it seems reasonable to assume that the process would fork into the background even when KV is unavailable. This in turn suggests walking back the main thing in this change, and returning before any blocking KV requests were made. WDYT?

**Comment by knz** [comment]
I can help here. The `--background` flag is going to be phased out. It only exists for convenience in demo sessions, and has been largely obsoleted by the introduction of `cockroach demo`.

Systemd and other integrations (k8s etc) don't use it. They launch the process and do their own process management; for them it's appropriate if the process blocks until the node is ready to accept requests.

**Comment by tbg** [comment]
`--background` is synonymous with the systemd readiness protocol though, isn't it? So the same problem remains: if you try to sequentially restart a down cluster while waiting for processes to become ready in turn, it will just hang forever on the first one.

**Comment by bdarnell** [comment]
> --background is synonymous with the systemd readiness protocol though, isn't it? So the same problem remains: if you try to sequentially restart a down cluster while waiting for processes to become ready in turn, it will just hang forever on the first one.

Yeah. Sequentially starting multiple nodes with systemd doesn't sound like a common use case to me, but it's hard to say for sure. 

> It's unclear to me what we actually want out of this flag

For the purposes of systemd readiness and `--background`, a node is ready when connections to it will not fail with "connection refused" or any sort of "server not ready" error. However, it's fine if connections are delayed arbitrarily while other initialization work happens. (for example, in a simple server, you could signal readiness after you bind your socket but before you start your accept loop). 

As much as possible, readiness should be a local decision - I'd rather not depend on distributed KV operations to declare a node ready. We delayed readiness until after `init` because we swap out the acceptor at that point which would orphan any existing connections, but other than that we'd ideally just let incoming pgwire connections queue up until KV is healthy.

**Comment by tbg** [comment]
Thanks Ben, that matches with my thinking. I moved the call before starting the node (=first time KV usage). I have some more reworkings of this in flight but they're not ready yet.

bors r=knz

**Comment by tbg** [comment]
bors r=knz

Apparently bors and preemptible VMs = failed builds  cc @bobvawter

**Comment by tbg** [comment]
Same issue, made CI use non-preemptible instances again.

bors r=knz

**Pull request merged**
