### PR TITLE
upgrademanager: audit tests that use MakeTestingClusterSettingsWithVersions

### PR DESCRIPTION
**Pull request by rafiss**
informs https://github.com/cockroachdb/cockroach/issues/100552

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Comment by rafiss** [comment]
flake fixed by https://github.com/cockroachdb/cockroach/pull/100895

bors r+

**Comment by nvanbenschoten** [comment]
In https://github.com/cockroachdb/cockroach/pull/100900, we saw `TestConcurrentMigrationAttempts` (touched here) hit a [timeout](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9497269?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true). There's no history of this test failing, so some flakiness may have been uncovered by these changes.

**Pull request merged**
