### PR TITLE
changefeedccl: pubsub sink refactor to batching sink

### PR DESCRIPTION
**Pull request by samiskin**
Epic: https://cockroachlabs.atlassian.net/browse/CRDB-13237

This change is a followup to https://github.com/cockroachdb/cockroach/pull/99086 which moves the Pubsub sink to the batching sink framework.

The changes involve:
1. Moves the Pubsub code to match the `SinkClient` interface, moving to using the lower level v1 pubsub API that lets us publish batches manually
3. Removing the extra call to json.Marshal
4. Moving to using the `pstest` package for validating results in unit tests
5. Adding topic handling to the batching sink, where batches are created per-topic
6. Added a pubsub_sink_config since it can now handle Retry and Flush config settings
7. Added metrics even to the old pubsub for the purpose of comparing the two versions

At default settings, this resulted in a peak of 90k messages per second on a single node with throughput at 27.6% cpu usage, putting it at a similar level to kafka.

Running pubsub v2 across all of TPCC (nodes ran out of ranges at different speeds):
Screenshot 2023-03-30 at 3 38 25 PM

Running pubsub v1 (barely visible, 2k messages per second) followed by v2 on tpcc.order_line (in v2 only 2 nodes ended up having ranges assigned to them):
Screenshot 2023-04-04 at 12 53 45 PM

In the following graphs from the cloud console, where v1 was ran followed by v2, you can see how the main reason v1 was slow was that it wasn't able to batch different keys together.
Screenshot 2023-04-04 at 12 59 51 PM

Publish requests remained the same despite way more messages in v2
Screenshot 2023-04-04 at 1 46 51 PM

Release note (performance improvement): pubsub sink changefeeds can now support higher throughputs by enabling the changefeed.new_pubsub_sink_enabled cluster setting.

### CODE REVIEW

**Comment by miretskiy** [comment]
Do you have any graphs on perf comparisson?

**Comment by samiskin** [comment]
@miretskiy Added the comparison graphs.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100188)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @samiskin, and @smg260)

___
*[`pkg/ccl/changefeedccl/sink.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100188#-NSCSN409LoWR05wVh54:-NSCSN409LoWR05wVh55:b-2k9j50) ([raw file](https://github.com/cockroachdb/cockroach/blob/a951ec0345eb49e48bc499fcf5c950db0518c2bb/pkg/ccl/changefeedccl/sink.go#L171)):*
> ```Go
> // NewPubsubSinkEnabled determines whether or not the refactored Webhook sink
> // or the deprecated sink should be used.
> var NewPubsubSinkEnabled = settings.RegisterBoolSetting(
> ```

Almost read it as a function NewXXX() ...
Maybe rename to `PubsubV2Enabled` or some such?
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100188#-NSCSyUd4YYSukvR-m1t:-NSCSyUeAdBIje8II8bv:b-7s4sr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a951ec0345eb49e48bc499fcf5c950db0518c2bb/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L203)):*
> ```Go
> 		var buffer bytes.Buffer
> 		keyPrefix := "{\"Key\":"
> 		valInfix := ",\"Value\":"
> ```

consi
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100188#-NSCSryiDLTfQ7i-LMhj:-NSCSryiDLTfQ7i-LMhk:b-avv4tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a951ec0345eb49e48bc499fcf5c950db0518c2bb/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L204)):*
> ```Go
> 		keyPrefix := "{\"Key\":"
> 		valInfix := ",\"Value\":"
> 		topicSuffix := fmt.Sprintf(",\"Topic\":\"%s\"}", psb.topic)
> ```

if you care about performance, you'd avoid Sprintf...
Probably costs you more than whatever buffer.Grow will save you.
```
buffer.WriteString(`"Topic": "`)
buffer.WriteString(psb.topic)
buffer.Write(`"`)
```
Also, it's a bit unfortunate that you have to decleare those keyPrefix/Infix... I just don't think it's necessary.
Something like the following would do well enough, imo:
```
var scratch [128]byte. // we have 30 bytes of metadata... so, kinda guess key/value/topic lengths. 
buffer := bytes.NewBuffer(scratch[:0])
bytes.WriteString(`{"Key": "`)
bytes.WriteString(key)
bytes.WriteString(`, "Value": `)
bytes.WriteString(value)
bytes.WriteString(`, "Topic": "`)
bytes.WriteString(psb.topic)
bytes.WriteString(`"}`)
```

Note, you can probably create create bytes.Buffer once -- if you still worried about allocations (you really shouldn't in this case).

Also.. what are the guarantees around topic containing double quotes?
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100188#-NSCVDmm3rE5SXEM8VjV:-NSCVDmm3rE5SXEM8VjW:bydzr6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a951ec0345eb49e48bc499fcf5c950db0518c2bb/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L208)):*
> ```Go
> 		buffer.Grow(len(keyPrefix) + len(key) + len(valInfix) + len(value) + len(topicSuffix))
> 		buffer.WriteString(keyPrefix)
> 		buffer.Write(key)
> ```

are you missing closing quote after key?

**Review by samiskin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100188)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @miretskiy, and @smg260)

___
*[`pkg/ccl/changefeedccl/sink.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100188#-NSCSN409LoWR05wVh54:-NSCg4CUAfGFhTMVX5FW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a951ec0345eb49e48bc499fcf5c950db0518c2bb/pkg/ccl/changefeedccl/sink.go#L171)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Almost read it as a function NewXXX() ...
Maybe rename to `PubsubV2Enabled` or some such?
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100188#-NSCSyUd4YYSukvR-m1t:-NSCg5_AE3JDvJb1Z4nU:bu97t0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a951ec0345eb49e48bc499fcf5c950db0518c2bb/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L203)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

consi
</blockquote></details>

Removed the variables entirely
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100188#-NSCSryiDLTfQ7i-LMhj:-NSCiLMw0aRLgFJ5i-_-:bmjcwzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a951ec0345eb49e48bc499fcf5c950db0518c2bb/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L204)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

if you care about performance, you'd avoid Sprintf...
Probably costs you more than whatever buffer.Grow will save you.
```
buffer.WriteString(`"Topic": "`)
buffer.WriteString(psb.topic)
buffer.Write(`"`)
```
Also, it's a bit unfortunate that you have to decleare those keyPrefix/Infix... I just don't think it's necessary.
Something like the following would do well enough, imo:
```
var scratch [128]byte. // we have 30 bytes of metadata... so, kinda guess key/value/topic lengths. 
buffer := bytes.NewBuffer(scratch[:0])
bytes.WriteString(`{"Key": "`)
bytes.WriteString(key)
bytes.WriteString(`, "Value": `)
bytes.WriteString(value)
bytes.WriteString(`, "Topic": "`)
bytes.WriteString(psb.topic)
bytes.WriteString(`"}`)
```

Note, you can probably create create bytes.Buffer once -- if you still worried about allocations (you really shouldn't in this case).

Also.. what are the guarantees around topic containing double quotes?
</blockquote></details>

I added the `buffer.Grow` after noticing the flamegraph show the underlying growths having visible cpu cost (I don't remember exactly how much it was).

I switched it to `buffer.Grow(26 /* Key/Value/Topic keys */ + len(key) + len(value) + len(psb.topicEncoded))` just now. I don't think reusing a scratch works since we can't have successive Appends writing over previous ones being stored in the `pb.PubsubMessage`array being built up.

I also made the topic value go through a per-batch `json.FromString(topic).Format`
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100188#-NSCVDmm3rE5SXEM8VjV:-NSCjsd-93Q93-2amBGw:b-77oa4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a951ec0345eb49e48bc499fcf5c950db0518c2bb/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L208)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

are you missing closing quote after key?
</blockquote></details>

The key bytes are already encoded with quotes

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100188)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @samiskin, and @smg260)

___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100188#-NSCSryiDLTfQ7i-LMhj:-NSClFnIAJ14RNyAByo0:b-ia4jw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a951ec0345eb49e48bc499fcf5c950db0518c2bb/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L204)):*
<details><summary><i>Previously, samiskin (Shiranka Miskin) wrote…</i></summary><blockquote>

I added the `buffer.Grow` after noticing the flamegraph show the underlying growths having visible cpu cost (I don't remember exactly how much it was).

I switched it to `buffer.Grow(26 /* Key/Value/Topic keys */ + len(key) + len(value) + len(psb.topicEncoded))` just now. I don't think reusing a scratch works since we can't have successive Appends writing over previous ones being stored in the `pb.PubsubMessage`array being built up.

I also made the topic value go through a per-batch `json.FromString(topic).Format`
</blockquote></details>

well, local scratch buffer definitely works because successive Appends will have their own buffer.  THe goal is to avoid
allocation at all -- in the common case.
You won't be able to share the buffer though -- for the reason you mention above.

Can we add some specific tests around this function -- to verify that the encoding is good (i.e to test that your json.FromString stuff works)...
I don't doubt that it does -- but I want to make sure we don't have silly mistakes.
You might find it easier to pull the guts of this method (buffer.Write) into some helper and writing specific tests around that.
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100188#-NSCVDmm3rE5SXEM8VjV:-NSCkYBh2Ht0fFzqUWkd:brarzdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a951ec0345eb49e48bc499fcf5c950db0518c2bb/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L208)):*
<details><summary><i>Previously, samiskin (Shiranka Miskin) wrote…</i></summary><blockquote>

The key bytes are already encoded with quotes
</blockquote></details>

Comment?

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100188)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @samiskin, and @smg260)

**Comment by samiskin** [comment]
Added a test using the name randomizer as table names for the pubsub sink, which includes stuff like quotes and slashes and emojis

**Pull request merged**
