### PR TITLE
ui: fix timescale for rolling window

### PR DESCRIPTION
**Pull request by maryliag**
The change introduced on #105157 had an undesired
change on the Metrics page. We want to show the end period
of the select, but when the fixed window end for that this
caused the Metrics page to stop loading new data.
We want the metrics page to keep updating when any of the
rolling windows is selected, and we also want to know
the time a time period was requested, so it can be used
to provide more information on SQL Activity pages.

This commit remove the setting of the fixedWindowEnd, since
that was not the best approach and instead creates a value
on local storage for the requestTime, that can be used to create
the label for the timescale, without interferring on
Metrics page (or any other that have an automatic update).

Epic: none

Release note (bug fix): Fix the Metrics page that was not
updating automatically on rolling window options.

Release note (bug fix): Statement Diagnostics not always 
showing is now fixed and they show for the correct time period selected.

### CODE REVIEW

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_5f7M8DAFdwrvhHXt1:byh77ly) (no related file):*
Should `requestTime` be a part of `timeScale` at all? 
My assumption that:
- it is a part of SQL Activity redux state where we can track the time last request/response was made and have dedicated selector to show this value on UI.
- `timeScale` is aware about selected options and overloading it with custom cases like this might lead to more regressions. IMO TimeScale and date picker is very fragile for any changes

___

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_5jbv02ZwbExDG7o8G:bungp2q) (no related file):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Should `requestTime` be a part of `timeScale` at all? 
My assumption that:
- it is a part of SQL Activity redux state where we can track the time last request/response was made and have dedicated selector to show this value on UI.
- `timeScale` is aware about selected options and overloading it with custom cases like this might lead to more regressions. IMO TimeScale and date picker is very fragile for any changes
</blockquote></details>

My idea was that this parameter was saving the time you changed the option, and this can be used in more pages then just SQL Activity, also Insights, Index Details, and so on, so is the responsibility of the component using the timescale to decide if that value is required or not and what it should be. But the component itself is just preparing to receive and do the proper label formatting for this case. 
This way this value doesn't affect at all the behaviour of the component, is just about having a label, but at the same time is uniform against all usage.


 

___

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_5kMFb2nptVlMg9bT_:bpttzx9) (no related file):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

My idea was that this parameter was saving the time you changed the option, and this can be used in more pages then just SQL Activity, also Insights, Index Details, and so on, so is the responsibility of the component using the timescale to decide if that value is required or not and what it should be. But the component itself is just preparing to receive and do the proper label formatting for this case. 
This way this value doesn't affect at all the behaviour of the component, is just about having a label, but at the same time is uniform against all usage.


 
</blockquote></details>

I can update the name if there is something more appropriate, such as "selectionTime", since that is what it means anyway.

___

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_5p9-kETPvqujuNq3u:b-w6fi97) (no related file):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I can update the name if there is something more appropriate, such as "selectionTime", since that is what it means anyway.
</blockquote></details>

It is stored in [src/redux/timeScale.ts](https://github.com/cockroachdb/cockroach/pull/106623/files#diff-fe207fa11fc6c36454a56680fae19196478cfabeb56a3509b4de555edf65521c "pkg/ui/workspaces/db-console/src/redux/timeScale.ts") as a single value so it cannot be reused in multiple places.
When `requestTime` is set on SQL Activity page, it will be updated on other pages as well because `timeScale` is a global thing.

___

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_5t5D29KaPnJclvbiE:bkef6go) (no related file):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

It is stored in [src/redux/timeScale.ts](https://github.com/cockroachdb/cockroach/pull/106623/files#diff-fe207fa11fc6c36454a56680fae19196478cfabeb56a3509b4de555edf65521c "pkg/ui/workspaces/db-console/src/redux/timeScale.ts") as a single value so it cannot be reused in multiple places.
When `requestTime` is set on SQL Activity page, it will be updated on other pages as well because `timeScale` is a global thing.
</blockquote></details>

By reuse I just meant the feature itself, not the we would have several values. Sorry about the confusion. 
Seems like that solution was causing more confusion, so I switched to store the value on local storage instead. 
PTAL

___

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_8qpHt6m-girqxFUjc:b-n8wxww) (no related file):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

By reuse I just meant the feature itself, not the we would have several values. Sorry about the confusion. 
Seems like that solution was causing more confusion, so I switched to store the value on local storage instead. 
PTAL
</blockquote></details>

I thought `timeScale` should already have correct `end` value for non-custom options (ie it is set to current time)? If it's true then it can be used directly?
Maybe I'm missing something important in current logic of date range selector, need to learn how it works rn.

___

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_9C8FwDB7nltE8PECk:b1pshmi) (no related file):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I thought `timeScale` should already have correct `end` value for non-custom options (ie it is set to current time)? If it's true then it can be used directly?
Maybe I'm missing something important in current logic of date range selector, need to learn how it works rn.
</blockquote></details>

For non-custom, the end value was always null, which allow rolling window to keep going (Past 1h keep getting the end updated to "now").
What I have done previously was setting up a value for the end value even for those cases, since we pause the requests on SQL Activity page. The problem was that this also made the rolling window pause on the Metrics page, and we don't want that. So my attempt to reuse the end parameter was not correct, so I had to move away from it.
I tried to keep using something still inside TimeScale but seems to be causing more confusion, so I used something separate, and should be good now!

___

**Review by THardy98 — COMMENTED** [review]
> Reviewed 15 of 28 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_AHYCD6XxRFp57rR24:b-a294mx) (no related file):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

For non-custom, the end value was always null, which allow rolling window to keep going (Past 1h keep getting the end updated to "now").
What I have done previously was setting up a value for the end value even for those cases, since we pause the requests on SQL Activity page. The problem was that this also made the rolling window pause on the Metrics page, and we don't want that. So my attempt to reuse the end parameter was not correct, so I had to move away from it.
I tried to keep using something still inside TimeScale but seems to be causing more confusion, so I used something separate, and should be good now!


</blockquote></details>

Generally, I think I like the idea of separating the request time from the timescale. Why is it that we want different request times for statements/transactions pages? I thought the idea more generally was to keep the same time window for both ?

___

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @THardy98)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_AIKNZ9msLmlI3dSlg:b-btuc4g) (no related file):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Generally, I think I like the idea of separating the request time from the timescale. Why is it that we want different request times for statements/transactions pages? I thought the idea more generally was to keep the same time window for both ?
</blockquote></details>

The requests don't always align, if you refresh Transaction not necessarily updates the Statement, so I want to make it clear the values for each one.
To clarify this PR doesn't change anything about when/how the requests are made. Is only storing when they were made so we can then surface on the UI.

___

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_AKfc85OBlORWLkUiq:b-cdlrub) (no related file):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

The requests don't always align, if you refresh Transaction not necessarily updates the Statement, so I want to make it clear the values for each one.
To clarify this PR doesn't change anything about when/how the requests are made. Is only storing when they were made so we can then surface on the UI.
</blockquote></details>

Ah ok. So for these pages, the timescale is moreso acting as a starting time, and the end time is the request time (in the default, non-custom case).

___

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @THardy98)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_AMOTK8LrvpKhBhw2T:b-n9wnwc) (no related file):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Ah ok. So for these pages, the timescale is moreso acting as a starting time, and the end time is the request time (in the default, non-custom case).
</blockquote></details>

Yes, that's correct (since we stopped auto refreshing those pages)

___

**Review by THardy98 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106623)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh and @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/106623#-N_5f7M7CpWEYQ2BTNbm:-N_AOh4cBKfiFYABNljm:b-8wry3u) (no related file):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Yes, that's correct (since we stopped auto refreshing those pages)
</blockquote></details>

Cool, then :lgtm: to me!
Thanks for the fix!

___

**Comment by theodore-hyman** [comment]
Hello, I have a customer that is still facing this UI issue and it is getting to the point where its impacting their ability to further develop their app and troubleshoot issues as they arise, if this drags on much longer its going to impact the production timeline and the overall customer confidence, reqeusting a follow up on when this UI issue will get fixed, thank you

@maryliag @THardy98 CC @brenda-crl

**Comment by theodore-hyman** [comment]
Not seeing that this github issue is linked to the Zendesk ticket so dropping this link here to the ticket in case it is helpful: https://cockroachdb.zendesk.com/agent/tickets/18003

Seems this pull request has been merged but the issue is still happening ... unclear what's happening .. maybe this is already fixed but the serverless cluster they're running is not on the proper version yet? ... Requesting details to understand when this is expected to be fixed as this is starting to drag .. thank you 

CC @world2mark

**Comment by maryliag** [comment]
This fix is not yet on Serverless cluster, make take a few more days to get there. I can update the ticket once is available there.

**Pull request merged**
