### PR TITLE
sql: introduce multi-region zone config extension descriptor changes

### PR DESCRIPTION
**Pull request by nvb**
This PR introduces lightweight zone configuration extensions, which provide flexibility to [multi-region abstractions](https://www.cockroachlabs.com/docs/stable/multiregion-overview.html) and are loosely based on the design described in [this doc](https://docs.google.com/document/d/1EiAT1BUOTaXoJy3CMzrKiP73bMfOAFiPrOPne5dtadU/edit#).

```sql
ALTER DATABASE db ALTER LOCALITY REGIONAL CONFIGURE ZONE USING ...

ALTER DATABASE db ALTER LOCALITY REGIONAL IN "us-east1" CONFIGURE ZONE USING ...

ALTER DATABASE db ALTER LOCALITY GLOBAL CONFIGURE ZONE USING ...
```

Zone config extensions represents per-locality zone configurations that influence the zone configurations derived for corresponding objects. A locality type's associated extension acts as a targeted set of rewrite rules for its associated objects' (database, table, partition) derived zone configurations.

"Extending" a zone config means having the extension inherit any missing fields from the zone config while replacing any set fields. This uses the existing zone configuration inheritance rules.

### Rules (implemented in pkg/sql/region_util.go):
```
1. database-level zone configs are extended first using the regional zone
   config extension and then with the regional_in[<primary_region>] zone
   config extension. In doing so, REGIONAL [ IN PRIMARY REGION ] tables can
   continue to inherit from the database level zone config.
2. table-level zone configs use the extension associated with their locality
   type.
 2a. GLOBAL tables are extended with the global zone config extension.
 2b. REGIONAL IN <region> tables are extended first using the regional zone
     config extension and then with the regional_in[<affinity_region>] zone
     config extension.
3. partition-level zone configs are extended first using the regional zone
   config extension and then with the regional_in[<partition_region>] zone
   config extension.
```

The PR contains only the descriptor changes and the logic to interpret zone config extensions during multi-region zone config synthesis. It does not contain the logic to set the extensions. As a result, it may be contained enough to fit into the v22.1.0 release, allowing the rest of the code to land in a later point release.

cc. @ajstorm @awoods187

### CODE REVIEW

**Review by postamar — COMMENTED** [review]
I noticed a few things in the first commit that should be straightforward to address.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-:-MySWtXD51gnJMq5332f:b-m7fyq4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @postamar)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MySOZxqCYShxY5zY44y:-MySOZxqCYShxY5zY44z:bmp6ktj) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/catalog/descpb/structured.proto#L1337)):*
> ```protobuf
>   // tables and partitions, according to affinity region.
>   map<string, config.zonepb.ZoneConfig> regional_in = 3 [(gogoproto.nullable) = false,
>     (gogoproto.castkey)="github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb.RegionName"];
> ```

What happens here when we drop a region with `ALTER DATABASE ... DROP REGION`? Shouldn't this map be updated as a result? I don't see any code to that effect, but perhaps that's out of scope for this commit. 

I thought about renaming regions as well but from what I can tell from the docs that's not possible.
___
*[pkg/sql/catalog/descpb/structured.proto, line 1462 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MySRQ6D8yVgCyHGzgG9:-MySRQ6D8yVgCyHGzgGA:b6evdro) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/catalog/descpb/structured.proto#L1462)):*
> ```protobuf
>     // ZoneConfigExtensions represents per-locality zone configurations that
>     // influence the zone configurations derived for corresponding objects.
>     optional ZoneConfigExtensions zone_config_extensions = 3 [(gogoproto.nullable) = false];
> ```

I'm grateful that you've added a boatload of tests to check that this field are valid within the region config. I don't think it's enough though, in this commit you'll also need to add some descriptor validation checks as well as some test cases for this field. The one important thing that comes to my mind is to verify that the keys in `regional_in` map to a subset of the type descriptor's enum values. 

This kind of cross-reference check is invaluable to preventing descriptor corruption, in this case one which might have been triggered by a DROP REGION.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MySPAhWBeVvH8-xg8Lp:-MySPAhWBeVvH8-xg8Lq:bt5hm80) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/catalog/typedesc/type_desc.go#L290)):*
> ```Go
> 	if desc.Kind != descpb.TypeDescriptor_MULTIREGION_ENUM {
> 		return descpb.ZoneConfigExtensions{}, errors.AssertionFailedf(
> 			"can not get the zone config extensions of a non multi-region enum %d", desc.ID,
> ```

nit: Add type name in error message? The prevailing pattern is `%q (%d)` with respectively `desc.Name(), desc.GetID()`.

**Review by awoods187 — APPROVED** [review]
This is great! I'm pro merging it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-:-Mygpa860xLk_PxFknCp:b-je362n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @postamar)

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 4 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78044)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @nvanbenschoten, and @postamar)

___
*[-- commits, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MymWzG78ZOomNoaotcj):*
Can you explain the motivation for the nested inheritance of the `REGIONAL BY ROW` tables?  Confessing that I haven't thought this through completely, on the surface it seems as though RBR is different enough from RBT that we wouldn't want to inherit.  Or put another way, if we want to make the extension a characteristic of the region, does it make sense to have the RBR level at all (and instead just lean more heavily on REGIONAL IN)?

Quite possible that I'm missing something though.
___
*[pkg/sql/region_util.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-Mymd6RJ8UEkMUOqUg3-:-Mymd6RJ8UEkMUOqUg30:bh7ea5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/region_util.go#L243)):*
> ```Go
> 	if regionConfig.IsMemberOfExplicitSuperRegion(partitionRegion) {
> 		addConstraintsForSuperRegion(&zc, regionConfig, partitionRegion)
> 	} else if !regionConfig.RegionalInTablesInheritConstraints(partitionRegion) {
> ```

This branching seems to imply that you can either be in a super region OR you can use the zone config extensions.  This seems reasonable to me, but @awoods187 should confirm that this is what he's expecting too.
___
*[pkg/sql/catalog/multiregion/region_config.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MymaplL6ZgybHJgIfyL:-MymaplL6ZgybHJgIfyM:b-cveonr) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/catalog/multiregion/region_config.go#L183)):*
> ```Go
> // replica constraints from their database zone configuration, or whether they
> // must set these constraints themselves.
> func (r *RegionConfig) GlobalTablesInheritConstraints() bool {
> ```

Nit: Should this be called `GlobalTablesInheritDatabaseConstraints()`?  Might be marginally clearer that way (as opposed to inheriting the default constraints).  Same comment for the functions below.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78044)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, @nvanbenschoten, and @postamar)

___
*[-- commits, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MymWzG78ZOomNoaotcj):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can you explain the motivation for the nested inheritance of the `REGIONAL BY ROW` tables?  Confessing that I haven't thought this through completely, on the surface it seems as though RBR is different enough from RBT that we wouldn't want to inherit.  Or put another way, if we want to make the extension a characteristic of the region, does it make sense to have the RBR level at all (and instead just lean more heavily on REGIONAL IN)?

Quite possible that I'm missing something though.
</blockquote></details>

Yeah, I should have been more explicit about this aspect of the design. The idea here is to not draw a distinction between `REGIONAL BY TABLE` and `REGIONAL BY ROW`. `REGIONAL` as it is used for zone config extensions is in reference to "localized data", not in reference to one of the two localization granularities. I don't see a situation where one would want to make such a distinction, defining one set of zone configs to localized data in region X when that data is in a RBR partition and another set of zone configs to localized data in region X when that data is in a RBT table. If we think of these extensions as attributes of a given region, then we'd want them to apply to any localized data in that region, whether it's localized at the table level or at the row level.

So starting there (if you buy that), we would have just the `regional_in[<affinity_region>]` extensions (`ALTER DATABASE db ALTER LOCALITY REGIONAL IN "us-east1" CONFIGURE ZONE USING ...`).

We then add a `regional_in[*]` extension (`ALTER DATABASE db ALTER LOCALITY REGIONAL CONFIGURE ZONE USING ...`) which applies to any localized data, regardless of which region it is localized in. The idea for this actually came from your comment in https://docs.google.com/document/d/1EiAT1BUOTaXoJy3CMzrKiP73bMfOAFiPrOPne5dtadU/edit?disco=AAAAUpz6Y7o.
___
*[pkg/sql/region_util.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-Mymd6RJ8UEkMUOqUg3-:-Mymi3SG3aj5vIBCuVu3:b9zb2ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/region_util.go#L243)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This branching seems to imply that you can either be in a super region OR you can use the zone config extensions.  This seems reasonable to me, but @awoods187 should confirm that this is what he's expecting too.
</blockquote></details>

This branch isn't precluding the application of a zone config extension to the current partition, regardless of whether super regions are used or not. See the call to `ApplyZoneConfigExtensionForRegionalIn` below. Rather, it's explicitly setting replica constraints when the replica constraints on the database can't be trusted to be set properly for inheritance, because the database's primary region has its own zone config extensions. It could use a comment.
___
*[pkg/sql/catalog/descpb/structured.proto, line 1337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MySOZxqCYShxY5zY44y:-Mymifcp-VZqM7xO9xeg:bfid9mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/catalog/descpb/structured.proto#L1337)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

What happens here when we drop a region with `ALTER DATABASE ... DROP REGION`? Shouldn't this map be updated as a result? I don't see any code to that effect, but perhaps that's out of scope for this commit. 

I thought about renaming regions as well but from what I can tell from the docs that's not possible.
</blockquote></details>

Yes, absolutely. These are the kinds of interactions we'll need to nail down before we'd want to expose this. So I'd say its in scope of the second commit here, which we're not trying to merge with this PR.
___
*[pkg/sql/catalog/descpb/structured.proto, line 1462 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MySRQ6D8yVgCyHGzgG9:-Mymizv-479ojsiUac1f:bgwm1ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/catalog/descpb/structured.proto#L1462)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm grateful that you've added a boatload of tests to check that this field are valid within the region config. I don't think it's enough though, in this commit you'll also need to add some descriptor validation checks as well as some test cases for this field. The one important thing that comes to my mind is to verify that the keys in `regional_in` map to a subset of the type descriptor's enum values. 

This kind of cross-reference check is invaluable to preventing descriptor corruption, in this case one which might have been triggered by a DROP REGION.
</blockquote></details>

Good point. I'll add this kind of validation.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78044)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @nvanbenschoten, and @postamar)

___
*[-- commits, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MymWzG78ZOomNoaotcj):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, I should have been more explicit about this aspect of the design. The idea here is to not draw a distinction between `REGIONAL BY TABLE` and `REGIONAL BY ROW`. `REGIONAL` as it is used for zone config extensions is in reference to "localized data", not in reference to one of the two localization granularities. I don't see a situation where one would want to make such a distinction, defining one set of zone configs to localized data in region X when that data is in a RBR partition and another set of zone configs to localized data in region X when that data is in a RBT table. If we think of these extensions as attributes of a given region, then we'd want them to apply to any localized data in that region, whether it's localized at the table level or at the row level.

So starting there (if you buy that), we would have just the `regional_in[<affinity_region>]` extensions (`ALTER DATABASE db ALTER LOCALITY REGIONAL IN "us-east1" CONFIGURE ZONE USING ...`).

We then add a `regional_in[*]` extension (`ALTER DATABASE db ALTER LOCALITY REGIONAL CONFIGURE ZONE USING ...`) which applies to any localized data, regardless of which region it is localized in. The idea for this actually came from your comment in https://docs.google.com/document/d/1EiAT1BUOTaXoJy3CMzrKiP73bMfOAFiPrOPne5dtadU/edit?disco=AAAAUpz6Y7o.
</blockquote></details>

That SGTM. While it's not in the context of this commit, the syntax is what was throwing me off here.  Using the term `LOCALITY` here leads me to think about the table localities.  In the doc we called this `ALTER ALL REGIONS` which, to me at least, draws out the ALL vs SINGLE aspect of this change.  Internally, we might want to refer to things as `AllRegions` vs `SpecifcRegion` to make this clearer.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78044)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, @nvanbenschoten, and @postamar)

___
*[-- commits, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MymWzG78ZOomNoaotcj):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

That SGTM. While it's not in the context of this commit, the syntax is what was throwing me off here.  Using the term `LOCALITY` here leads me to think about the table localities.  In the doc we called this `ALTER ALL REGIONS` which, to me at least, draws out the ALL vs SINGLE aspect of this change.  Internally, we might want to refer to things as `AllRegions` vs `SpecifcRegion` to make this clearer.
</blockquote></details>

The tricky part about an "all" vs "specific" classifier is that it makes the extensions specific to GLOBAL tables awkward. That's what made me think it would be natural to tie this to locality "classes" (regional vs. global). We could scrap the GLOBAL table extensions, but then we're either left with no ability to extend the zone configs of GLOBAL table or using the primary region's zone config extension for GLOBAL tables, neither of which seem great.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78044)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @nvanbenschoten, and @postamar)

___
*[-- commits, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MymWzG78ZOomNoaotcj):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The tricky part about an "all" vs "specific" classifier is that it makes the extensions specific to GLOBAL tables awkward. That's what made me think it would be natural to tie this to locality "classes" (regional vs. global). We could scrap the GLOBAL table extensions, but then we're either left with no ability to extend the zone configs of GLOBAL table or using the primary region's zone config extension for GLOBAL tables, neither of which seem great.
</blockquote></details>

What about the following?

`ALTER DATABASE db ALTER REGION CONFIGURE ZONE USING ...`
`ALTER DATABASE db ALTER ALL REGIONS CONFIGURE ZONE USING ...`
`ALTER DATABASE db ALTER GLOBAL [ TABLES ] CONFIGURE ZONE USING ...`

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78044)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @nvanbenschoten, @otan, @postamar, and @RichardJCai)

___
*[-- commits, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MymWzG78ZOomNoaotcj):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

What about the following?

`ALTER DATABASE db ALTER REGION CONFIGURE ZONE USING ...`
`ALTER DATABASE db ALTER ALL REGIONS CONFIGURE ZONE USING ...`
`ALTER DATABASE db ALTER GLOBAL [ TABLES ] CONFIGURE ZONE USING ...`
</blockquote></details>

That syntax also sounds fine to me. We also don't need to decide now. The important part for this PR and the backport is that we're ok with the data model in the descriptor (`message ZoneConfigExtensions`) which this leads to. It sounds like we are, so I'll go ahead and polish off the first commit in this PR and then loop @richardjcai and @otan in for a review of that commit.

**Comment by nvanbenschoten** [comment]
@RichardJCai and @otan, now that we're pretty sure we have the data model right here, I've stripped out the second commit so that this PR is left with just the descriptor changes and the logic to interpret zone config extensions during multi-region zone config synthesis. It does not contain the logic to set the extensions. As a result, it should be contained enough to fit into the v22.1.0 release, allowing the rest of the code to land in a later point release.

Do you mind giving it a review when you get a chance? You two are the resident experts in this area.

**Review by RichardJCai — APPROVED** [review]
Looks pretty great to me overall. Thanks for cleaning up a lot of the code here.

There's still some review comments to be addressed here and also we definitely do want to add more validation.

> Reviewed 3 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-:-MzpnJEo6I_zi1TVDFRa:b50cl2m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @nvanbenschoten, @otan, @postamar, and @RichardJCai)

___
*[pkg/sql/region_util.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-Mymd6RJ8UEkMUOqUg3-:-MzpgJ1F7R7rOeSXYaIW:b-8kmr2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/region_util.go#L243)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This branch isn't precluding the application of a zone config extension to the current partition, regardless of whether super regions are used or not. See the call to `ApplyZoneConfigExtensionForRegionalIn` below. Rather, it's explicitly setting replica constraints when the replica constraints on the database can't be trusted to be set properly for inheritance, because the database's primary region has its own zone config extensions. It could use a comment.
</blockquote></details>

+1 to adding comment
___
*[pkg/sql/region_util.go, line 176 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MzpkdLIAZYOnPtXMsP6:-MzpkdLIAZYOnPtXMsP7:b-pubdl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f4c77f6d740b66e0c1bfae9659b9da72c3c6630/pkg/sql/region_util.go#L176)):*
> ```Go
> // that every replica is guaranteed to be constrained to a region within the
> // super region.
> // Requires: regionConfig.IsMemberOfExplicitSuperRegion(affinityRegion).
> ```

Should we codify this check and error if this isn't true?
___
*[pkg/sql/region_util.go, line 206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MzpkN-_BqoA_tLq5kky:-MzpkN-_BqoA_tLq5kkz:barh3ti) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec4ccc95407d8d48899ec6000bdaa67d0bea38c/pkg/sql/region_util.go#L206)):*
> ```Go
> 	zc.Constraints = nil
> 	zc.InheritedConstraints = false
> 	zc.InheritedLeasePreferences = false
> ```

What was the reason for removing this here?

**Comment by otan** [comment]
changes bar review comments LGTM, but lmk if you want another look with that in

**Review by nvb — COMMENTED** [review]
> Please don't omit the validation logic to check that the RegionalIn keys map to region enum values. This should be pretty easy to add in multiregion.ValidateRegionConfig, and straightforward to modify a couple of your unit test cases.

Done.

TFTRs! I think I addressed all of the comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-:-N-6oNtTDnxa1JTvkgeR:b-khg9ww)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, @otan, @postamar, and @RichardJCai)

___
*[pkg/sql/region_util.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-Mymd6RJ8UEkMUOqUg3-:-N-6goDR5_trZHxnVXP7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/region_util.go#L243)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

+1 to adding comment
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 176 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MzpkdLIAZYOnPtXMsP6:-N-6esze64Vi4TJydX9k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f4c77f6d740b66e0c1bfae9659b9da72c3c6630/pkg/sql/region_util.go#L176)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Should we codify this check and error if this isn't true?
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MzpkN-_BqoA_tLq5kky:-N-6ezgB6td9udvwwy9b:b73ogp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec4ccc95407d8d48899ec6000bdaa67d0bea38c/pkg/sql/region_util.go#L206)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

What was the reason for removing this here?
</blockquote></details>

`addConstraintsForSuperRegion` only deals with constraints, not leaseholder preferences. The handling of leaseholder preferences is performed at the callers of this function (who already set this field). So we didn't need the line and it also felt misplaced.
___
*[pkg/sql/catalog/multiregion/region_config.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MymaplL6ZgybHJgIfyL:-N-6f_1Q2ntSkx3nVTjS:b-ydonir) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/catalog/multiregion/region_config.go#L183)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Should this be called `GlobalTablesInheritDatabaseConstraints()`?  Might be marginally clearer that way (as opposed to inheriting the default constraints).  Same comment for the functions below.
</blockquote></details>

Done. Good idea.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78044#-MySPAhWBeVvH8-xg8Lp:-N-6gPnG24S9V_5eCRrr:b-snh328) ([raw file](https://github.com/cockroachdb/cockroach/blob/24920542b762c3b6b9f06dfab1557893b02c7437/pkg/sql/catalog/typedesc/type_desc.go#L290)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: Add type name in error message? The prevailing pattern is `%q (%d)` with respectively `desc.Name(), desc.GetID()`.
</blockquote></details>

Done here and elsewhere.

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Comment by nvanbenschoten** [comment]
@ZhouXing19 https://github.com/nvanbenschoten/cockroach/commit/e3cb336f9c6c5a9d3451135db13a7fc2b1eb4e8d is an incomplete prototype of the SQL frontend for this feature. It's a useful place to start to see how the plumbing might work.

**Pull request merged**
