### PR TITLE
stmtdiagnostics: add CancelRequest API

### LINKED ISSUE #73863: Cancel statement diagnostics
**Is your feature request related to a problem? Please describe.**
We want the ability to cancel statement diagnostics that are still waiting on a result. This will be later surfaced in the frontend statement diagnostics pages. 

**Additional context**
Blocks cancellation flows for: https://github.com/cockroachdb/cockroach/issues/57634

https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=4722%3A123327

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds an API for a stmt diagnostics request to be canceled
based on the query fingerprint. Internally, we choose to achieve that by
marking the request (if found) as expired because this allows any
ongoing query traces to write their bundles. The API is only available
once 22.1 migrations have been completed, otherwise it'll error. This
commit uses gossip with a separate key to tell other nodes about the
cancellation of a request.

Fixes: #73863.
Informs: #57634.

Paired with @lindseyjin to implement this.

Release note: None

### CODE REVIEW

**Review by matthewtodd — APPROVED** [review]
This :lgtm: but it's worth getting others who know more than me to weigh in. :sweat_smile: 

> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-:-Mr2p6wU8HRMdlhyzCEj:b1dgilo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lindseyjin, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr2oALv8DMGZtCTrUNS:-Mr2oALv8DMGZtCTrUNT:bho806z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3cee6bfc8cc3d10dfc8385db68f2ff1dcb594c/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L187)):*
> ```Go
> 			// Poll the data.
> 			// TODO(yuzefovich): it seems ok to just delete the pending request
> 			// without having to poll the data from scratch.
> ```

Is there more to do here? The comment makes it sound like there isn't, but the TODO label threw me off.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73882)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lindseyjin, @RaduBerinde, and @yuzefovich)

___
*[pkg/server/status.go, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr2xaJt37hM7Kv8HuOO:-Mr2xaJt37hM7Kv8HuOP:b-b57l2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3cee6bfc8cc3d10dfc8385db68f2ff1dcb594c/pkg/server/status.go#L430)):*
> ```Go
> 	// for tracing a query with the given fingerprint to be expired (thus,
> 	// canceling any new tracing for it).
> 	CancelRequest(ctx context.Context, fprint string) error
> ```

small nit: how do you feel about`s/fprint/stmtFingerprint/` ? `fprint` threw me off a bit and made me think that it's some sort of formatting string 
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr2xqkO0LCkm-2T6xPk:-Mr2xqkO0LCkm-2T6xPl:b-iapp62) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3cee6bfc8cc3d10dfc8385db68f2ff1dcb594c/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L399)):*
> ```Go
> 	row, err := r.ie.QueryRowEx(ctx, "stmt-diag-cancel-request", nil, /* txn */
> 		sessiondata.InternalExecutorOverride{
> 			User: security.RootUserName(),
> ```

quick question, do we have a guideline on when to use `RootUserName()` vs `NodeUserName()` for internalEx? 
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr2y_ey4giAYaBXT1g3:-Mr2y_ey4giAYaBXT1g4:b-a46281) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3cee6bfc8cc3d10dfc8385db68f2ff1dcb594c/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L415)):*
> ```Go
> 		// There is no pending diagnostics request with the given fingerprint,
> 		// so there is nothing to cancel.
> 		return nil
> ```

Should we be returning an error here? stating that the user is cancelling an non-existent request ? 
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr2y7pw0B5RRk33U8kl:-Mr2y7pw0B5RRk33U8km:bvvxwj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3cee6bfc8cc3d10dfc8385db68f2ff1dcb594c/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L417)):*
> ```Go
> 		return nil
> 	}
> 	reqID := RequestID(*row[0].(*tree.DInt))
> ```

small nit: should we use `tree.MustBeDInt` here ?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73882)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @lindseyjin, @matthewtodd, and @RaduBerinde)

___
*[pkg/server/status.go, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr2xaJt37hM7Kv8HuOO:-Mr3KQBEBorXG2CakD8G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3cee6bfc8cc3d10dfc8385db68f2ff1dcb594c/pkg/server/status.go#L430)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

small nit: how do you feel about`s/fprint/stmtFingerprint/` ? `fprint` threw me off a bit and made me think that it's some sort of formatting string 
</blockquote></details>

Done.
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr2oALv8DMGZtCTrUNS:-Mr38rT9AzqWit7RE6tH:b-a8yloi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3cee6bfc8cc3d10dfc8385db68f2ff1dcb594c/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L187)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Is there more to do here? The comment makes it sound like there isn't, but the TODO label threw me off.
</blockquote></details>

I'd like to get the opinion from @raduberinde here - my take is that we don't have to poll when a request is canceled. IIUC polling reloads the registry from scratch, but in case of a canceled request, we've just removed that request from the registry anyway, so I think it should be ok to not poll. I copied the polling from above when a new request is added, and typing this comment out made me realize that adding a new request is different since we have to get the state of that request (fingerprint, min latency, etc), and that's why we have to reload the whole registry. Removed the TODO.
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr2xqkO0LCkm-2T6xPk:-Mr3KaQ0-NJ3AVp5FmaD:b-gnet3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3cee6bfc8cc3d10dfc8385db68f2ff1dcb594c/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L399)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

quick question, do we have a guideline on when to use `RootUserName()` vs `NodeUserName()` for internalEx? 
</blockquote></details>

I'm not aware of such guidelines. I think that originally all internally-executed queries ran under `root`, but some time later we introduced an argument to identify the user while keeping all the existing usages running under `root`. We use `root` for other internal queries in this file, so I think it's ok to do that here as well.
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr2y_ey4giAYaBXT1g3:-Mr3JdMr5z8Fs1xjjmiI:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3cee6bfc8cc3d10dfc8385db68f2ff1dcb594c/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L415)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Should we be returning an error here? stating that the user is cancelling an non-existent request ? 
</blockquote></details>

Good point, done.
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr2y7pw0B5RRk33U8kl:-Mr3KGff8GoDhn4H28yp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3cee6bfc8cc3d10dfc8385db68f2ff1dcb594c/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L417)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

small nit: should we use `tree.MustBeDInt` here ?
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
cc @andreimatei in case you're interested

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73882)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @lindseyjin, @matthewtodd, @RaduBerinde, and @yuzefovich)

___
*[pkg/server/serverpb/status.proto, line 1729 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr4C_CZ6IVfp_A9tjcC:-Mr4C_CZ6IVfp_A9tjcD:byoim1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b7489536e60e67fbcc068ce9ff6cefb0d99507/pkg/server/serverpb/status.proto#L1729)):*
> ```protobuf
>   rpc CancelStatementDiagnosticsReport(CancelStatementDiagnosticsReportRequest) returns (CancelStatementDiagnosticsReportResponse) {
>     option (google.api.http) = {
>       post: "/_status/stmtdiagcancel"
> ```

is it possible to support this as a `DELETE` verb on `_status/stmtdiagreports` to make this a bit more HTTP-friendly and clarify the link between the create endpoint?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73882)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @dhartunian, @lindseyjin, @matthewtodd, and @RaduBerinde)

___
*[pkg/server/serverpb/status.proto, line 1729 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr4C_CZ6IVfp_A9tjcC:-Mr507ox5gC5eGqltlzM:b-21l41r) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b7489536e60e67fbcc068ce9ff6cefb0d99507/pkg/server/serverpb/status.proto#L1729)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is it possible to support this as a `DELETE` verb on `_status/stmtdiagreports` to make this a bit more HTTP-friendly and clarify the link between the create endpoint?
</blockquote></details>

Done. I'm assuming that I don't need to make any other changes, right? (I only had to delete `body`.)

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73882)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @lindseyjin, @matthewtodd, and @RaduBerinde)

___
*[pkg/server/serverpb/status.proto, line 1729 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr4C_CZ6IVfp_A9tjcC:-Mr5ce-EE_WBQREOVs0B:bvwt6sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b7489536e60e67fbcc068ce9ff6cefb0d99507/pkg/server/serverpb/status.proto#L1729)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Done. I'm assuming that I don't need to make any other changes, right? (I only had to delete `body`.)
</blockquote></details>

Ah sorry maybe this was a bad idea. Thanks for trying it out!
If `DELETE` does not appear to support a request body I'm not sure how we would transmit the request's fingerprint if it's not in the URL. If we have IDs that can be put in the request URL instead of the fingerprint it might be a decent idea.

@matthewtodd @azhng I'll leave this with y'all. My motivation was to prevent the number of API endpoints from growing here but maybe it's not practical.

Maybe a reasonable middle ground is to go with `/_status/stmtdiagreports/cancel` just to clearly group this endpoint under the create one in the hierarchy.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73882)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lindseyjin, @matthewtodd, and @RaduBerinde)

___
*[pkg/server/serverpb/status.proto, line 1729 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr4C_CZ6IVfp_A9tjcC:-MrNcPlg41a-z2RJTBT-:b-x4kqiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b7489536e60e67fbcc068ce9ff6cefb0d99507/pkg/server/serverpb/status.proto#L1729)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Ah sorry maybe this was a bad idea. Thanks for trying it out!
If `DELETE` does not appear to support a request body I'm not sure how we would transmit the request's fingerprint if it's not in the URL. If we have IDs that can be put in the request URL instead of the fingerprint it might be a decent idea.

@matthewtodd @azhng I'll leave this with y'all. My motivation was to prevent the number of API endpoints from growing here but maybe it's not practical.

Maybe a reasonable middle ground is to go with `/_status/stmtdiagreports/cancel` just to clearly group this endpoint under the create one in the hierarchy.
</blockquote></details>

I played around with it a little bit and managed to get it to build by changing the Makefile a bit to support DELETE with body by adding `allow_delete_body=true` to `--grpc-gateway_out` flag.


```

diff --git a/Makefile b/Makefile
index 1ddff7216b..9cc828c00d 100644
--- a/Makefile
+++ b/Makefile
@@ -1296,8 +1296,8 @@ bin/.go_protobuf_sources: $(GO_PROTOS) $(GOGOPROTO_PROTO) $(ERRORS_PROTO) bin/.b

 bin/.gw_protobuf_sources: $(GW_SERVER_PROTOS) $(GW_TS_PROTOS) $(GO_PROTOS) $(GOGOPROTO_PROTO) $(ERRORS_PROTO) bin/.bootstrap
        $(FIND_RELEVANT) -type f -name '*.pb.gw.go' -exec rm {} +
-               buf protoc -Ipkg -I$(GOGO_PROTOBUF_PATH) -I$(ERRORS_PATH) -I$(COREOS_PATH) -I$(PROMETHEUS_PATH) -I$(GRPC_GATEWAY_GOOGLEAPIS_PATH) --grpc-gateway_out=logtostderr=true,request_context=true:./pkg $(GW_SERVER_PROTOS)
-               buf protoc -Ipkg -I$(GOGO_PROTOBUF_PATH) -I$(ERRORS_PATH) -I$(COREOS_PATH) -I$(PROMETHEUS_PATH) -I$(GRPC_GATEWAY_GOOGLEAPIS_PATH) --grpc-gateway_out=logtostderr=true,request_context=true:./pkg $(GW_TS_PROTOS)
+               buf protoc -Ipkg -I$(GOGO_PROTOBUF_PATH) -I$(ERRORS_PATH) -I$(COREOS_PATH) -I$(PROMETHEUS_PATH) -I$(GRPC_GATEWAY_GOOGLEAPIS_PATH) --grpc-gateway_out=logtostderr=true,request_context=true,allow_delete_body=true:./pkg $(GW_SERVER_PROTOS)
+               buf protoc -Ipkg -I$(GOGO_PROTOBUF_PATH) -I$(ERRORS_PATH) -I$(COREOS_PATH) -I$(PROMETHEUS_PATH) -I$(GRPC_GATEWAY_GOOGLEAPIS_PATH) --grpc-gateway_out=logtostderr=true,request_context=true,allow_delete_body=true:./pkg $(GW_TS_PROTOS)
        gofmt -s -w $(GW_SOURCES)
        @# TODO(jordan,benesch) This can be removed along with the above TODO.
        goimports -w $(GW_SOURCES)
diff --git a/pkg/server/serverpb/status.proto b/pkg/server/serverpb/status.proto
index 92952ce9ff..adb8b6779c 100644
--- a/pkg/server/serverpb/status.proto
+++ b/pkg/server/serverpb/status.proto
@@ -1727,6 +1727,7 @@ service Status {
   rpc CancelStatementDiagnosticsReport(CancelStatementDiagnosticsReportRequest) returns (CancelStatementDiagnosticsReportResponse) {
     option (google.api.http) = {
       delete: "/_status/stmtdiagreports"
+      body: "*"
     };
   }
   rpc StatementDiagnosticsRequests(StatementDiagnosticsReportsRequest) returns (StatementDiagnosticsReportsResponse) {
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73882)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lindseyjin, @matthewtodd, and @RaduBerinde)

___
*[pkg/server/serverpb/status.proto, line 1729 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-Mr4C_CZ6IVfp_A9tjcC:-MrNvy63BBIRbI9hv0Zq:b-rwnl2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b7489536e60e67fbcc068ce9ff6cefb0d99507/pkg/server/serverpb/status.proto#L1729)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I played around with it a little bit and managed to get it to build by changing the Makefile a bit to support DELETE with body by adding `allow_delete_body=true` to `--grpc-gateway_out` flag.


```

diff --git a/Makefile b/Makefile
index 1ddff7216b..9cc828c00d 100644
--- a/Makefile
+++ b/Makefile
@@ -1296,8 +1296,8 @@ bin/.go_protobuf_sources: $(GO_PROTOS) $(GOGOPROTO_PROTO) $(ERRORS_PROTO) bin/.b

 bin/.gw_protobuf_sources: $(GW_SERVER_PROTOS) $(GW_TS_PROTOS) $(GO_PROTOS) $(GOGOPROTO_PROTO) $(ERRORS_PROTO) bin/.bootstrap
        $(FIND_RELEVANT) -type f -name '*.pb.gw.go' -exec rm {} +
-               buf protoc -Ipkg -I$(GOGO_PROTOBUF_PATH) -I$(ERRORS_PATH) -I$(COREOS_PATH) -I$(PROMETHEUS_PATH) -I$(GRPC_GATEWAY_GOOGLEAPIS_PATH) --grpc-gateway_out=logtostderr=true,request_context=true:./pkg $(GW_SERVER_PROTOS)
-               buf protoc -Ipkg -I$(GOGO_PROTOBUF_PATH) -I$(ERRORS_PATH) -I$(COREOS_PATH) -I$(PROMETHEUS_PATH) -I$(GRPC_GATEWAY_GOOGLEAPIS_PATH) --grpc-gateway_out=logtostderr=true,request_context=true:./pkg $(GW_TS_PROTOS)
+               buf protoc -Ipkg -I$(GOGO_PROTOBUF_PATH) -I$(ERRORS_PATH) -I$(COREOS_PATH) -I$(PROMETHEUS_PATH) -I$(GRPC_GATEWAY_GOOGLEAPIS_PATH) --grpc-gateway_out=logtostderr=true,request_context=true,allow_delete_body=true:./pkg $(GW_SERVER_PROTOS)
+               buf protoc -Ipkg -I$(GOGO_PROTOBUF_PATH) -I$(ERRORS_PATH) -I$(COREOS_PATH) -I$(PROMETHEUS_PATH) -I$(GRPC_GATEWAY_GOOGLEAPIS_PATH) --grpc-gateway_out=logtostderr=true,request_context=true,allow_delete_body=true:./pkg $(GW_TS_PROTOS)
        gofmt -s -w $(GW_SOURCES)
        @# TODO(jordan,benesch) This can be removed along with the above TODO.
        goimports -w $(GW_SOURCES)
diff --git a/pkg/server/serverpb/status.proto b/pkg/server/serverpb/status.proto
index 92952ce9ff..adb8b6779c 100644
--- a/pkg/server/serverpb/status.proto
+++ b/pkg/server/serverpb/status.proto
@@ -1727,6 +1727,7 @@ service Status {
   rpc CancelStatementDiagnosticsReport(CancelStatementDiagnosticsReportRequest) returns (CancelStatementDiagnosticsReportResponse) {
     option (google.api.http) = {
       delete: "/_status/stmtdiagreports"
+      body: "*"
     };
   }
   rpc StatementDiagnosticsRequests(StatementDiagnosticsReportsRequest) returns (StatementDiagnosticsReportsResponse) {
```
</blockquote></details>

Thanks Archer for trying this out, but do you think it's worth modifying the Makefile for it? I'm concerned that we might introduce some subtle regression for not much benefit. Additionally, we probably would need to modify something bazel-related, and I didn't immediately find where we would do that.

I reverted to POST and used David's suggestion for the naming.

**Review by Azhng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73882#-:-MrOc62J4PHaMstRi_eS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @lindseyjin, @matthewtodd, and @RaduBerinde)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Comment by yuzefovich** [comment]
Looks like CI is red, I'll need to take a closer look.

bors r-

**Comment by yuzefovich** [comment]
There were two possible scenarios for flakes, I figured out one of them but don't understand another. In both cases I added `SucceedsSoon` that should make the unit tests not-flakey (in one scenario the usage of `SucceedsSoon` is warranted). I'll go ahead and merge since the second scenario doesn't seem critical to figure out right now.

bors r+

**Pull request merged**
