### PR TITLE
sql: group heap-allocated local variables in `execStmtInOpenState`

### PR DESCRIPTION
**Pull request by mgartner**
Local variables in `execStmtInOpenState` that escape to the heap are now
grouped in a single `localVars` struct so that just one heap allocation
is necessary for all of them.

Informs #135908

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
`BenchmarkEndToEnd/kv-read` shows the minor improvement:

```
name                                     old time/op    new time/op    delta
EndToEnd/kv-read/vectorize=on/Simple        440µs ± 8%     432µs ± 7%    ~     (p=0.548 n=5+5)
EndToEnd/kv-read/vectorize=on/Prepared      287µs ± 4%     285µs ± 6%    ~     (p=0.841 n=5+5)
EndToEnd/kv-read/vectorize=off/Simple       430µs ± 5%     430µs ± 4%    ~     (p=0.548 n=5+5)
EndToEnd/kv-read/vectorize=off/Prepared     278µs ± 3%     277µs ± 4%    ~     (p=0.690 n=5+5)

name                                     old alloc/op   new alloc/op   delta
EndToEnd/kv-read/vectorize=on/Simple       36.7kB ± 1%    36.7kB ± 1%    ~     (p=0.886 n=4+4)
EndToEnd/kv-read/vectorize=on/Prepared     25.2kB ± 1%    25.1kB ± 2%    ~     (p=0.286 n=4+4)
EndToEnd/kv-read/vectorize=off/Simple      39.5kB ±16%    39.6kB ±17%    ~     (p=0.841 n=5+5)
EndToEnd/kv-read/vectorize=off/Prepared    26.3kB ± 2%    26.6kB ± 4%    ~     (p=1.000 n=5+5)

name                                     old allocs/op  new allocs/op  delta
EndToEnd/kv-read/vectorize=on/Simple          329 ± 0%       326 ± 0%  -0.84%  (p=0.029 n=4+4)
EndToEnd/kv-read/vectorize=on/Prepared        243 ±13%       239 ±14%    ~     (p=0.278 n=5+5)
EndToEnd/kv-read/vectorize=off/Simple         322 ± 0%       318 ± 0%  -1.09%  (p=0.029 n=4+4)
EndToEnd/kv-read/vectorize=off/Prepared       225 ± 0%       222 ± 0%  -1.44%  (p=0.000 n=5+4)
```

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136212#-:-OCddf1XBuu6k3UOaNLB:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/conn_executor_exec.go` line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136212#-OCdcuI-1FhxJHz1_0rD:-OCdcuI-1FhxJHz1_0rE:b-onge1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c4d301b5392918d5aaa21cf28dbac63acabdf1/pkg/sql/conn_executor_exec.go#L377)):*
> ```Go
> 	}
> 
> 	var queryID clusterunique.ID
> ```

Does this variable not escape? Should we use `//gcassert:noescape` for all stack-allocated vars in this function?
___
*[`pkg/sql/conn_executor_exec.go` line 765 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136212#-OCdccUR1wM8HoREitKY:-OCdccUR1wM8HoREitKZ:b-nhv8qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c4d301b5392918d5aaa21cf28dbac63acabdf1/pkg/sql/conn_executor_exec.go#L765)):*
> ```Go
> 	dispatchToExecEngine := false
> 
> 	// resErr is used to capture the error returned by the result of the
> ```

nit: leftover comment.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136212)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`pkg/sql/conn_executor_exec.go` line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136212#-OCdcuI-1FhxJHz1_0rD:-OCe7qra6T_-UJSOB3D9:b-drirab) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c4d301b5392918d5aaa21cf28dbac63acabdf1/pkg/sql/conn_executor_exec.go#L377)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Does this variable not escape? Should we use `//gcassert:noescape` for all stack-allocated vars in this function?
</blockquote></details>

It doesn't, according to heap profiles. We could add the assertion, but that'd be tedious...
___
*[`pkg/sql/conn_executor_exec.go` line 765 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136212#-OCdccUR1wM8HoREitKY:-OCe7nwt5j5yVv6WcFBs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c4d301b5392918d5aaa21cf28dbac63acabdf1/pkg/sql/conn_executor_exec.go#L765)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: leftover comment.
</blockquote></details>

Done.
___
*[`pkg/sql/conn_executor_exec.go` line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136212#-OCe81435SOnuqqYr1WY:-OCe81435SOnuqqYr1WZ:b-ykl5bc) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c4d301b5392918d5aaa21cf28dbac63acabdf1/pkg/sql/conn_executor_exec.go#L288)):*
> ```Go
> 		ast                    tree.Statement
> 		stmt                   Statement
> 		updateRetErrAndPayload func(err error, payload fsm.EventPayload)
> ```

I removed `updateRetErrAndPayload` from `localVars` because it doesn't appear to help, upon further inspection. I'll revist the associatied allocations in the future.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
