### PR TITLE
storage: annotate contexts instead of manually logging

### PR DESCRIPTION
**Pull request by tamird**
Ideally Add, MaybeAdd should take contexts, but I didn't feel like
pulling on that thread.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10549)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/queue.go, line 284 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10549#-KW4I3PfwHyEwvAYAJvs:-KW4I3PfwHyEwvAYAJvt:b1uqn60) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff6caf725dd53a80137b233f6aea7e01f1fae6cf/pkg/storage/queue.go#L284)):*
> ```Go
> 	bq.mu.Lock()
> 	defer bq.mu.Unlock()
> 	ctx := bq.AnnotateCtx(repl.AnnotateCtx(context.TODO()))
> ```

the `bq` context will have the queue name. We probably want that to show up first, so we should annotate in the opposite order

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10549#-:-KW4IL6azZiav1H8i60A:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/queue.go, line 284 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10549#-KW4I3PfwHyEwvAYAJvs:-KW4JmWIuuQc9WCqTpP9:b-8hn1ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff6caf725dd53a80137b233f6aea7e01f1fae6cf/pkg/storage/queue.go#L284)):*
Seems like this stuff gets added inside-out? This is the log line I see:

> `E161108 14:03:25.806700 92 storage/queue.go:579  [n1,replicate,s1,r3/1:/Table/1{2-3}] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10549)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/queue.go, line 284 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10549#-KW4I3PfwHyEwvAYAJvs:-KW4MoY8OB20XvOsAo5_:bv2fr1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff6caf725dd53a80137b233f6aea7e01f1fae6cf/pkg/storage/queue.go#L284)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Seems like this stuff gets added inside-out? This is the log line I see:
> 
> > `E161108 14:03:25.806700 92 storage/queue.go:579  [n1,replicate,s1,r3/1:/Table/1{2-3}] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster`
</details>
Nope, I'm just dumb. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10549)*

**Comment by RaduBerinde** [comment]
:lgtm_strong: 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10549#-:-KW4MwDppBPjsDIfmX6p:b-uwkowd)*

**Pull request merged**
