### PR TITLE
sql: Update pgjdbc blocklist

### LINKED ISSUE #85882: roachtest: pgjdbc failed
roachtest.pgjdbc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6034844?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6034844?buildTab=artifacts#/pgjdbc) on master @ [f53c21f9fe0fe07ba32d2f28ac4bd2c4bc2ed50b](https://github.com/cockroachdb/cockroach/commits/f53c21f9fe0fe07ba32d2f28ac4bd2c4bc2ed50b):

```
test artifacts and logs in: /artifacts/pgjdbc/run_1
	orm_helpers.go:191,orm_helpers.go:117,java_helpers.go:220,pgjdbc.go:207,pgjdbc.go:219,test_runner.go:896: 
		Tests run on Cockroach v22.2.0-alpha.00000000-2390-gf53c21f9fe
		Tests run against pgjdbc REL42.3.3
		5792 Total Tests Run
		5039 tests passed
		753 tests failed
		72 tests skipped
		178 tests ignored
		33 tests passed unexpectedly
		0 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testUnterminatedLiteral - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testResultSetClosed - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testDoubleClose - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testUnterminatedComment - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testExecuteUpdateFailsOnMultiStatementSelect - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testEmptyQuery - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testSetQueryTimeout - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testEscapeProcessing - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testCancelQueryWithBrokenNetwork - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testClose - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testPreparedFunction - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testShortQueryTimeout - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testStringFunctions - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testResultSetTwice - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testLongQueryTimeout - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testSystemFunctions - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testUnterminatedDollarQuotes - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testDollarInComment - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testDollarInCommentTwoComments - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testSideStatementFinalizers - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testMultipleCancels - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testSetQueryTimeoutWithSleep - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testUnbalancedParensParseError - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testWarningsAreCleared - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testParsingDollarQuotes - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testUnterminatedNamedDollarQuotes - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testSetQueryTimeoutWithoutExecute - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testUnterminatedIdentifier - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testSetQueryTimeoutOnPrepared - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testJavascriptFunction - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testDateFuncWithParam - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testExecuteUpdateFailsOnSelect - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		--- PASS: org.postgresql.test.jdbc2.StatementTest.testMultiExecute - https://github.com/cockroachdb/cockroach/issues/17511 (unexpected)
		For a full summary look at the pgjdbc artifacts 
		
		An updated blocklist (pgjdbcBlockList22_2) is available in the artifacts' pgjdbc log
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgjdbc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18476

### PR DESCRIPTION
**Pull request by e-mbrown**
Closes #85882

Release justification: Non-production code changes
Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
i think now would be a good time for us to just have one blocklist, rather than having one per version.

could you rename `pgjdbcBlockList22_1` to just ` pgjdbcBlockList`, then delete the lists for the other versions?

**Review by rafiss — CHANGES_REQUESTED** [review]
you need to update the usages of `pgjdbcBlocklists` and the other variables you removed so it points to the new name you are using now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86695#-:-NAQ8rY27NqryE3Imkqs:b-12x126)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rafiss — CHANGES_REQUESTED** [review]
needs an update at

```
        pkg/cmd/roachtest/tests/blocklist_test.go:37:19: undeclared name: pgjdbcBlockList20_2 (compile)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86695#-:-NAjEO69-81qJdJKmFd8:b-vyx609)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/cmd/roachtest/tests/pgjdbc.go` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86695#-NAjEX2sDfgPWgDMorw8:-NAjEX2sDfgPWgDMorw9:bqttgdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cdab3c87cd71e6c88b8df7c8d44e5eb1a219c71/pkg/cmd/roachtest/tests/pgjdbc.go#L152)):*
> ```Go
> 
> 		blocklistName := "pgjdbcBlocklist"
> 		ignorelistName := "pgjdbcIgnorelist"
> ```

the two names can be a `const`

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86695)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/cmd/roachtest/tests/pgjdbc_blocklist.go` line 0 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86695#-NAoW2rvDnZelTDL0Pc6:-NAoW2rvDnZelTDL0Pc7:bd7qy0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49bf5e0ef7a374bd6567a293514140b90249e6c/pkg/cmd/roachtest/tests/pgjdbc_blocklist.go#L0)):*
i think there are more tests to be removed from the list. where did you get this new list from?

you can go to the artifacts at https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6300492?buildTab=artifacts#%2Fpgjdbc%2Frun_1%2Fartifacts.zip

then open test.log. at the bottom, there is a new blocklist that you can copy+paste (ctrl+f for `new pgjdbc blocklist`)

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86695)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/cmd/roachtest/tests/pgjdbc_blocklist.go` line  at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86695#-NAoW2rvDnZelTDL0Pc6:-NAohckv-jps93MMHCh3:bmps6qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49bf5e0ef7a374bd6567a293514140b90249e6c/pkg/cmd/roachtest/tests/pgjdbc_blocklist.go#L)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think there are more tests to be removed from the list. where did you get this new list from?

you can go to the artifacts at https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6300492?buildTab=artifacts#%2Fpgjdbc%2Frun_1%2Fartifacts.zip

then open test.log. at the bottom, there is a new blocklist that you can copy+paste (ctrl+f for `new pgjdbc blocklist`)
</blockquote></details>

Ah okay, I missed that

**Review by rafiss — APPROVED** [review]
lgtm!

**Comment by e-mbrown** [comment]
Yay!

bors r=rafiss

**Pull request merged**
