### PR TITLE
parser: teach locality syntax to CREATE TABLE

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): Added the ability to CREATE TABLE with
LOCALITY set.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57419)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57419#-MNa9CGM35OPRg4Jc9_e:-MNa9CGM35OPRg4Jc9_f:bkohpig) ([raw file](https://github.com/cockroachdb/cockroach/blob/caea310ddf846708d0619aa618ea949961b57758/pkg/sql/logictest/testdata/logic_test/multiregion#L125)):*
> ```
> 
> statement error implementation pending
> CREATE TABLE regional_test3_table (a int) LOCALITY REGIONAL BY TABLE IN "test3"
> ```

Can we get a testcase for REGIONAL BY TABLE?
___
*[pkg/sql/parser/parse_test.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57419#-MNa9JJw91oYS_ByEHoo:-MNa9JJx5DkFp4h7XHTz:b-13c0ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/caea310ddf846708d0619aa618ea949961b57758/pkg/sql/parser/parse_test.go#L352)):*
> ```Go
> 
> 		{`CREATE TABLE a (a INT4) LOCALITY GLOBAL`},
> 		{`CREATE TABLE a (a INT4) LOCALITY REGIONAL BY TABLE IN "us-west1"`},
> ```

Can we test REGIONAL BY TABLE?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57419)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57419#-MNa9CGM35OPRg4Jc9_e:-MNawoLEDjjF_uHYkS_W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caea310ddf846708d0619aa618ea949961b57758/pkg/sql/logictest/testdata/logic_test/multiregion#L125)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Can we get a testcase for REGIONAL BY TABLE?
</blockquote></details>

Done.
___
*[pkg/sql/parser/parse_test.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57419#-MNa9JJw91oYS_ByEHoo:-MNawoi13m8Sft6KNDUQ:b-ew10j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/caea310ddf846708d0619aa618ea949961b57758/pkg/sql/parser/parse_test.go#L352)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Can we test REGIONAL BY TABLE?
</blockquote></details>

See TestParse2.

**Review by ajstorm — APPROVED** [review]
Nice!  :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57419#-:-MNcwt8v75qL9kXSNrW3:b-ac1xez)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/parser/parse_test.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57419#-MNa9JJw91oYS_ByEHoo:-MNcwp4_Cc-MWR1xPjpj:b-71wdp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/caea310ddf846708d0619aa618ea949961b57758/pkg/sql/parser/parse_test.go#L352)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

See TestParse2.
</blockquote></details>

oops, I see it

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
