### PR TITLE
rangefeed: don't discard ref count for txn after intent abort

### LINKED ISSUE #34600: roachtest: cdc/crdb-chaos/rangefeed=true failed
SHA: https://github.com/cockroachdb/cockroach/commits/82026117d83262e87873aad52b8eca2dd0bea335

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=cdc/crdb-chaos/rangefeed=true PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1126329&tab=buildLog

```
The test failed on provisional_201902052032_v2.2.0-alpha.20190211:
	test.go:748,cdc.go:744,cdc.go:215,cdc.go:433: max latency was more than allowed: 21m15.099334977s vs 10m0s

```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #34600.

Before this commit, rangefeed made the assumption that an aborted intent
implied an aborted transaction (after the rangefeed was in a steady-state).
It used this assumption to eagerly discard the bookkeeping for a transaction
after its first MVCCAbortIntent operation was seen as an optimization.

This was incorrect. A transaction can "abort" an intent even if it commits.
This is possible if the intent was only written at a previous epoch and not
written in the epoch that ended up finalizing the transaction. This commit
removes this assumption, which I confirmed fixes the resolved timestamp
regression using the new assertion from #35772.

I believe this could have two effects:
- it could trigger the assertion failure from #34600 if the transaction
  experiencing the incorrect assumption was the oldest being tracked at
  the time of the assumption.
- it could cause resolved timestamp stalls and prevent all future forward
  progress of resolved timestamps if the transaction experiencing the incorrect
  assumption was not the oldest being tracked at the time of the assumption.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35777#-:-La-pJlX2DsyOELZ8N7o:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

**Review by danhhz — APPROVED** [review]
Great find! I'm curious, any theories why this would have become more frequent recently?

**Comment by nvanbenschoten** [comment]
> I'm curious, any theories why this would have become more frequent recently?

An increase in transaction retries is the only thing I can think of. https://github.com/cockroachdb/cockroach/issues/34600 was failing so reliably for other reasons though. Do you think it is safe to say that this became more frequent recently or was it just hidden?

bors r+

**Comment by nvanbenschoten** [comment]
Flake due to #34081.

bors r+

**Comment by nvanbenschoten** [comment]
Flaked due to https://github.com/cockroachdb/cockroach/issues/35484.

bors r+

**Comment by nvanbenschoten** [comment]
Same issue. I'm debugging now in https://github.com/cockroachdb/cockroach/issues/35549.

bors r+

**Pull request merged**
