### PR TITLE
roachtest: don't terminate suite when single test hangs after timeout

### PR DESCRIPTION
**Pull request by tbg**
Previously, when a single test went over timeout & failed to terminate
within a grace period (as can happen when one forgets to put the right
context cancellation everywhere, etc), we would return an error to the
worker running the test which the worker would treat as fatal, causing
the entire roachtest suite to stop.

With this commit, the suite continues. The cluster is not re-used in
this case, since we failed the test and thus hit line 528 below:

https://github.com/cockroachdb/cockroach/blob/25f1ad82d4431939f706577dfdaf6d76f832da6a/pkg/cmd/roachtest/test_runner.go#L510-L530

and so the goroutines that are sticking around from the failed test,
while annoying, are benign.

Found this problem while looking at failed nightly build [3123385].

[3123385]: https://teamcity.cockroachdb.com/viewLog.html?buildId=3123385&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=buildLog&_focus=4756

Release note: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66948)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/66948#-MdN_0XBAwh7g96QNwUQ:-MdN_0XBAwh7g96QNwUR:b-66cgrm) (no related file):*
I think this is reasonable.  Thanks for including a reference to the calling code :D.  We should still be able to hunt down these missing context issues since the test will be marked as failed, so not failing the rest of the tests makes sense to me.

---
___
*[pkg/cmd/roachtest/test_runner.go, line 831 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66948#-MdNYCNNDSpQG5O9a52X:-MdNYCNO8oLBEIJJGtEl:b-yoj12q) ([raw file](https://github.com/cockroachdb/cockroach/blob/58f269f79bfaa048fc1ae77605bd15a8f97ec708/pkg/cmd/roachtest/test_runner.go#L831)):*
> ```Go
> 			// We really shouldn't get here unless the test code somehow managed
> 			// to deadlock without blocking on anything remote - since we killed
> 			// everything.
> ```

Your commit message indicates that maybe this case is a bit more comment than we thought, worth updating the comment here?

**Comment by tbg** [comment]
When a timeout occurs, roachtest dumps the stacks to the artifacts of the test that timed out. In the latest example on the master nightly GCE roachtests, it's this one:

```
goroutine 39 [syscall, 588 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x6f14, 0xc0004f1850, 0x1000004, 0x0, 0x0, 0xc001bdca20, 0x4be4740, 0xc000825400)
	/usr/local/go/src/syscall/asm_linux_amd64.s:43 +0x5
os.(*Process).blockUntilWaitable(0xc000a52ea0, 0x5, 0x5, 0x203000)
	/usr/local/go/src/os/wait_waitid.go:32 +0x9e
os.(*Process).wait(0xc000a52ea0, 0x488b7c0, 0x5421818, 0x5421820)
	/usr/local/go/src/os/exec_unix.go:22 +0x39
os.(*Process).Wait(...)
	/usr/local/go/src/os/exec.go:129
os/exec.(*Cmd).Wait(0xc002ec91e0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:507 +0x65
os/exec.(*Cmd).Run(0xc002ec91e0, 0xc001074810, 0xc002ec91e0)
	/usr/local/go/src/os/exec/exec.go:341 +0x5f
os/exec.(*Cmd).CombinedOutput(0xc002ec91e0, 0x47, 0xc000f18a90, 0x4, 0x7, 0xc002ec91e0)
	/usr/local/go/src/os/exec/exec.go:567 +0x91
main.execCmdWithBuffer(0x625b7d8, 0xc000f72140, 0xc000138a20, 0xc000f18a80, 0x5, 0x8, 0x4, 0x8, 0x1f, 0x7f4634f5fb58, ...)
	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:568 +0x1c5
main.(*clusterImpl).RunWithBuffer(0xc0006e4d80, 0x625b7d8, 0xc000f72140, 0xc000138a20, 0xc001576090, 0x1, 0x1, 0xc0011187b0, 0x1, 0x1, ...)
	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2039 +0x24e
main.registerActiveRecord.func1(0x625b7d8, 0xc000f72140, 0x639a908, 0xc000cb2240, 0x63b17b0, 0xc0006e4d80)
	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/activerecord.go:181 +0x14de
main.(*testRunner).runTest.func2(0xc00164a420, 0xc000cb2240, 0x625b7d8, 0xc000f72140, 0xc0006e4d80)
	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:758 +0xba
created by main.(*testRunner).runTest
	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:745 +0x551
```

This does have the context, so not sure what's going on:

https://github.com/cockroachdb/cockroach/blob/07ea22254be6f0efafa79a0414a036433a9195b7/pkg/cmd/roachtest/activerecord.go#L179-L184

**Comment by tbg** [comment]
Oh or maybe not. I think roachtest might intentionally not actually be cancelling the context proactively on the fatal error. Let me fix that.

**Comment by tbg** [comment]
No, I looked wrong. The context should have been canceled just fine.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66948)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/66948#-MdN_0XBAwh7g96QNwUQ:-MdR3ZMN0BdxOF2E6DWr:bd7dzug) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I think this is reasonable.  Thanks for including a reference to the calling code :D.  We should still be able to hunt down these missing context issues since the test will be marked as failed, so not failing the rest of the tests makes sense to me.
</blockquote></details>

TFTR!

bors r=stevendanna

---
___
*[pkg/cmd/roachtest/test_runner.go, line 831 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66948#-MdNYCNNDSpQG5O9a52X:-MdR38T1AL6aceFkbPfP:b-hpq9xy) ([raw file](https://github.com/cockroachdb/cockroach/blob/58f269f79bfaa048fc1ae77605bd15a8f97ec708/pkg/cmd/roachtest/test_runner.go#L831)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Your commit message indicates that maybe this case is a bit more comment than we thought, worth updating the comment here?
</blockquote></details>

Not sure, I think the vastly common case is that we don't get here.

I added a second commit that dumps the stacks again, to make it "clear" (to the degree that this is possible, since multiple tests are likely running) which goroutine(s) blocked test termination.

**Pull request merged**
