### PR TITLE
roachtest/test: rename test_interface.go.go to test_interface.go

### PR DESCRIPTION
**Pull request by otan**
Release note: None

### CODE REVIEW

**Comment by otan** [comment]
https://www.youtube.com/watch?v=pIgZ7gMze7A

**Review by tbg — APPROVED** [review]
Jitterbug

**Comment by tbg** [comment]
(This is also in my open PR but anyway)

**Comment by otan** [comment]
haha didn't see that

bors r=tbg

**Comment by tbg** [comment]
Beat you to it in the end https://github.com/cockroachdb/cockroach/pull/66930/commits

**Pull request closed without merging**
