### PR TITLE
allocator2: unit test and bug fixes for storeIDPostingList

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs https://github.com/cockroachdb/cockroach/issues/103320

Epic: [CRDB-25222](https://cockroachlabs.atlassian.net/browse/CRDB-25222)

Release note: None

### CODE REVIEW

**Comment by sumeerbhola** [comment]
First commit is from https://github.com/cockroachdb/cockroach/pull/103325

**Review by kvoli — APPROVED** [review]
2nd commit :lgtm: 

> Reviewed 4 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103437#-:-NVe3ccn-0jzC01zxSlV:b-ypy3ry)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1534 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103437#-NVe3NNIBFA1gcL55IFl:-NVe3NNIBFA1gcL55IFm:bi0ropr) ([raw file](https://github.com/cockroachdb/cockroach/blob/057b6c66bdb58cc8a6637d64013dee2f600b4181/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1534)):*
> ```Go
> 	n := len(a)
> 	var pos int
> 	for pos = 0; pos < len(a); pos++ {
> ```

nit: reuse length var `n` to be `pos < n`.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint_test.go` line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103437#-NVe1d9-APaDLM6Zph7-:-NVe1d9-APaDLM6Zph70:b3u3kdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/057b6c66bdb58cc8a6637d64013dee2f600b4181/pkg/kv/kvserver/allocator/allocator2/constraint_test.go#L195)):*
> ```Go
> 					}
> 					if forceAllocation {
> 						plX = plX[:len(plX):cap(plX)]
> ```

I don't think this is forcing allocation, since the resulting slice will have identical capacity. Should it instead be:

```go
pl[:len(pl):len(pl)]
```

Like the other instances in this test?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103437#-:-NVeaCC1AbJEk_q50_RB:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1534 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103437#-NVe3NNIBFA1gcL55IFl:-NVe_zZSETEWGNTqnJ3M:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/057b6c66bdb58cc8a6637d64013dee2f600b4181/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1534)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: reuse length var `n` to be `pos < n`.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint_test.go` line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103437#-NVe1d9-APaDLM6Zph7-:-NVea6kf8XZoS2Y6-gnM:b669eu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/057b6c66bdb58cc8a6637d64013dee2f600b4181/pkg/kv/kvserver/allocator/allocator2/constraint_test.go#L195)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I don't think this is forcing allocation, since the resulting slice will have identical capacity. Should it instead be:

```go
pl[:len(pl):len(pl)]
```

Like the other instances in this test?
</blockquote></details>

Ah yes. Fixed.

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
