### PR TITLE
pgwire: apply LDAP roles to SQL user during login

### LINKED ISSUE #130780: ldap: Authorize users to CRDB
**Is your feature request related to a problem? Please describe.**
As of 24.2, we support LDAP authentication. However, we are yet to support authorization.

**Describe the solution you'd like**
Post a successful authentication, the groups assigned to the user in the AD server need to be fetched (#125087) and be matched to the corresponding roles within CRDB. The matching needs to be happen via an exact string comparison. The roles and users are assumed to be created beforehand, as a pre-requisite.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Jira issue: CRDB-42231

Epic CRDB-33829

### PR DESCRIPTION
**Pull request by rafiss**
### pgwire: simplify Authorizer in AuthBehaviors

There's no need to have a separate GrantRole hook, since we can do
everything we need in the authorizer.

---

### ldapccl: mark ldap_test_utils.go as a test file

---

### pgwire: apply LDAP roles to SQL user during login

After successful authentication with LDAP, CRDB will now also fetch the
LDAP groups from the server. These groups are used as the sole source of
truth for role memberships within CRDB. If a group does not have a
corresponding SQL role, then the login will fail.

Release note (security update): Added support for configuring
authorization using LDAP. During login, the list of groups that a user
belongs to are fetched from the LDAP server. These groups are mapped to
SQL roles by extracting the common name (CN) from the group. After
authenticating the user, the login flow grants these roles to the user,
and revokes any other roles that are not returned by the LDAP server.

The groups given by the LDAP server are treated as the sole source of
truth for role memberships, so any roles that were manually granted to
the user will not remain in place.

---

fixes https://github.com/cockroachdb/cockroach/issues/130780
Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
Still working on testing this

**Review by souravcrl — COMMENTED** [review]
I had some clarifying questions for `EnsureUserOnlyBelongsToRoles`, otherwise LGTM.

> Reviewed 3 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-:-O7DR13t7ZSX2PnDtn14:bq38tri)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/authorization.go` line 725 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DNZol-IeGcCAFvaMi:-O7DNZol-IeGcCAFvaMj:b-r9z16n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/authorization.go#L725)):*
> ```Go
> 		// Compute the differences between the current roles and the
> 		// desired roles to determine which roles need to granted or revoked.
> 		rolesToRevoke := make([]username.SQLUsername, 0, len(currentRoles))
> ```

Can't we revoke all `currentRoles` that are assigned to the user and then assign back fetched roles? Just wanted to know if this being done as that would be an expensive operation.
___
*[`pkg/sql/authorization.go` line 728 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DOBQ9DHk90PIBLuP2:-O7DOBQA2SNrImWyWvos:b-uaprnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/authorization.go#L728)):*
> ```Go
> 		rolesToGrant := make([]username.SQLUsername, 0, len(roles))
> 		for role := range currentRoles {
> 			if !slices.Contains(roles, role) {
> ```

There could be some roles which are not synced from AD. Should we have a check here for not revoking roles that are non-AD-synced?
___
*[`pkg/sql/authorization.go` line 733 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DOc8RD_kVA8Ss_7x4:-O7DOc8RD_kVA8Ss_7x5:b19oodf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/authorization.go#L733)):*
> ```Go
> 		}
> 		for _, role := range roles {
> 			if _, ok := currentRoles[role]; !ok {
> ```

Similarly here, not all AD roles will have a role user on CRDB, should we have some check to prune those out?
___
*[`pkg/sql/pgwire/auth_methods.go` line 1019 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DPFFYBwX74QuVJOUv:-O7DPFFYBwX74QuVJOUw:bknb9sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/pgwire/auth_methods.go#L1019)):*
> ```Go
> 				// Extract the CN from the LDAP group DN to use as the SQL role.
> 				var sqlRoleString string
> 			rdn_loop:
> ```

nit: should we move this CN retrieval logic to a separate utility in`pkg/security/distinguishedname/parse.go` pkg as in `distinguishedname.ParseCN(*ldap.DN) (commonName string,err error)`? I can also take this up in a separate PR if we don't want to do it here.

**Review by souravcrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/pgwire/auth_behaviors.go` line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7IhKhMBUAgoXPpyF0L:-O7IhKhMBUAgoXPpyF0M:b-qjdnj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c1f94754b7fb41a95f25e2e2cc895bd328c53b/pkg/sql/pgwire/auth_behaviors.go#L123)):*
> ```Go
> // MaybeAuthorize delegates to the Authorizer passed to SetAuthorizer and if
> // successful obtains the grants using RoleGranter passed to SetRoleGranter.
> func (b *AuthBehaviors) MaybeAuthorize(
> ```

Another discussion I feel is needed for MaybeAuthorize. If this is unsuccessful should the auth fail which happens now or should we just log and continue with auth? External authorization can fail for variety of reasons and should we just continue with previously synced authZ information since that could be useful when LDAP/external system is experiencing failures. Link to error handling logic:
https://github.com/cockroachdb/cockroach/blob/eb674313fbedd5dab66adff4ba89dcfb330a2e5e/pkg/sql/pgwire/auth.go#L197-L205
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7IglCwAGL6SHrWfS5c:-O7IglCwAGL6SHrWfS5d:b-ned4fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c1f94754b7fb41a95f25e2e2cc895bd328c53b/pkg/sql/pgwire/auth_behaviors.go#L138)):*
> ```Go
> // GrantRole delegates to the RoleGranter passed to SetRoleGranter or
> // returns an error if SetRoleGranter has not been called.
> func (b *AuthBehaviors) GrantRole(
> ```

One advantage I saw with the previous logic was that the same GrantRole could be reused for multiple auth_methods as grant role logic should be common once we have the all groups for which we want to grant the memberships for the role.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dikshant and @souravcrl)

___
*[`pkg/sql/authorization.go` line 725 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DNZol-IeGcCAFvaMi:-O896kfl5knMWsed7LyQ:b-xy8ist) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/authorization.go#L725)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Can't we revoke all `currentRoles` that are assigned to the user and then assign back fetched roles? Just wanted to know if this being done as that would be an expensive operation.
</blockquote></details>

yeah, that's exactly the reason -- doing that every time would be expensive. i will add a comment.
___
*[`pkg/sql/authorization.go` line 728 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DOBQ9DHk90PIBLuP2:-O8971X42pYMv0VnqMpV:bvwwhax) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/authorization.go#L728)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

There could be some roles which are not synced from AD. Should we have a check here for not revoking roles that are non-AD-synced?
</blockquote></details>

hm, it seemed safer to me that this should cause a failure, but this is actually more of a product question. let me check with @dikshant 
___
*[`pkg/sql/authorization.go` line 733 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DOc8RD_kVA8Ss_7x4:-O897BCD1UXsNZ3f3NH0:b-fwflfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/authorization.go#L733)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Similarly here, not all AD roles will have a role user on CRDB, should we have some check to prune those out?
</blockquote></details>

also is a product question
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7IhKhMBUAgoXPpyF0L:-O897DWG8SHOioU1DWOl:b-o1kvlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c1f94754b7fb41a95f25e2e2cc895bd328c53b/pkg/sql/pgwire/auth_behaviors.go#L123)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Another discussion I feel is needed for MaybeAuthorize. If this is unsuccessful should the auth fail which happens now or should we just log and continue with auth? External authorization can fail for variety of reasons and should we just continue with previously synced authZ information since that could be useful when LDAP/external system is experiencing failures. Link to error handling logic:
https://github.com/cockroachdb/cockroach/blob/eb674313fbedd5dab66adff4ba89dcfb330a2e5e/pkg/sql/pgwire/auth.go#L197-L205
</blockquote></details>

this also is a product question
___
*[`pkg/sql/pgwire/auth_methods.go` line 1019 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DPFFYBwX74QuVJOUv:-O896zph9wr_7ThR5ACM:b-6ejtjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/pgwire/auth_methods.go#L1019)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

nit: should we move this CN retrieval logic to a separate utility in`pkg/security/distinguishedname/parse.go` pkg as in `distinguishedname.ParseCN(*ldap.DN) (commonName string,err error)`? I can also take this up in a separate PR if we don't want to do it here.
</blockquote></details>

this is a good idea; i'll take care of it

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dikshant and @souravcrl)

___
*[`pkg/sql/pgwire/auth_behaviors.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7IglCwAGL6SHrWfS5c:-O898Be9-EFKW8b2yHEL:b-4y589) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c1f94754b7fb41a95f25e2e2cc895bd328c53b/pkg/sql/pgwire/auth_behaviors.go#L138)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

One advantage I saw with the previous logic was that the same GrantRole could be reused for multiple auth_methods as grant role logic should be common once we have the all groups for which we want to grant the memberships for the role.
</blockquote></details>

i think we can always add in that separate hook when the need arises. i would rather avoid premature abstractions, since right now, LDAP is the only method that needs this authorization step.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dikshant and @souravcrl)

___
*[`pkg/sql/authorization.go` line 728 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DOBQ9DHk90PIBLuP2:-O8Dta_R13njg7FwZrTl:b2gnzsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/authorization.go#L728)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, it seemed safer to me that this should cause a failure, but this is actually more of a product question. let me check with @dikshant
</blockquote></details>

the decision was that LDAP is the sole source of truth
___
*[`pkg/sql/authorization.go` line 733 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DOc8RD_kVA8Ss_7x4:-O8DtiKy9BgkBAfwtDAA:b-632y7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/authorization.go#L733)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

also is a product question
</blockquote></details>

similar to above
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7IhKhMBUAgoXPpyF0L:-O8DtkuG92Aj5B0lhPDK:b7i157m) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c1f94754b7fb41a95f25e2e2cc895bd328c53b/pkg/sql/pgwire/auth_behaviors.go#L123)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this also is a product question
</blockquote></details>

since LDAP is the source of truth, it is safer to error here when LDAP is not available.

**Review by souravcrl — APPROVED** [review]
:lgtm:

> Reviewed 8 of 10 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-:-O8Fq2ra05ouhHyh7HyE:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dikshant, @rafiss, and @spilchen)

___
*[`pkg/sql/authorization.go` line 728 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7DOBQ9DHk90PIBLuP2:-O8FjRiW-vjeTIJlyznL:b-xo8snn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb01cfa4c71e022bbc62c63e34964de5bfe9406/pkg/sql/authorization.go#L728)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the decision was that LDAP is the sole source of truth
</blockquote></details>

makes sense now. It would be confusing otherwise.
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7IhKhMBUAgoXPpyF0L:-O8FjYx_2vPM-OPLcjhW:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c1f94754b7fb41a95f25e2e2cc895bd328c53b/pkg/sql/pgwire/auth_behaviors.go#L123)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since LDAP is the source of truth, it is safer to error here when LDAP is not available.
</blockquote></details>

:+1: 
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O7IglCwAGL6SHrWfS5c:-O8FjiPT1zwX49KY-yRR:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c1f94754b7fb41a95f25e2e2cc895bd328c53b/pkg/sql/pgwire/auth_behaviors.go#L138)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we can always add in that separate hook when the need arises. i would rather avoid premature abstractions, since right now, LDAP is the only method that needs this authorization step.
</blockquote></details>

:+1:

**Review by souravcrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131043)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dikshant, @rafiss, and @spilchen)

___
*[`pkg/ccl/ldapccl/authorization_ldap_test.go` line 178 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O8FsgQL2NyaVIh5UuUF:-O8FsgQL2NyaVIh5UuUG:bibjb51) ([raw file](https://github.com/cockroachdb/cockroach/blob/34cbec2f94f9abb1f8d36acbb88d419052aa8b1d/pkg/ccl/ldapccl/authorization_ldap_test.go#L178)):*
> ```Go
> 		"ldapsearchattribute": "uid",
> 		"ldapsearchfilter":    "(memberOf=cn=users,ou=groups,dc=localhost)",
> 		"ldapgrouplistfilter": "(objectCategory=cn=Group,cn=Schema,cn=Configuration,DC=crlcloud,DC=dev)",
> ```

nit: we can abstract out the actual configuration 



_Suggestion:_
```Go
		"ldapgrouplistfilter": "(objectCategory=cn=Group,cn=Schema,cn=Configuration,DC=example,DC=com)",
```

**Review by rafiss — COMMENTED** [review]
tftr!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-:-O8I5T4S9V3yb8ddPnG-:bjpalj3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dikshant, @souravcrl, and @spilchen)

___
*[`pkg/ccl/ldapccl/authorization_ldap_test.go` line 178 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/131043#-O8FsgQL2NyaVIh5UuUF:-O8I5R_TAU1vhtVL1ZBt:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/34cbec2f94f9abb1f8d36acbb88d419052aa8b1d/pkg/ccl/ldapccl/authorization_ldap_test.go#L178)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

nit: we can abstract out the actual configuration
</blockquote></details>

done

**Pull request merged**
