### PR TITLE
storage: allow for disabling sstable compression

### LINKED ISSUE #122991: storage: support disabling sstable compression
The new (in 24.1) `storage.sstable.compression_algorithm` cluster setting configures the compression algorithm used when compressing sstable blocks within the storage engine. Today the only permissible values are 'snappy' or 'zstd'. We could consider adding a 'none' value for deployments that make use of filesystem-level compression, like that provided by ZFS. At least in the case of ZFS, the ARC cache holds compressed data which means it should function equivalently to the page cache in an ext4 deployment with CockroachDB compression.

Jira issue: CRDB-38156

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, the supported compression algorithms are snappy and zstd. There are usecases where a cluster may benefit from disabling compression (e.g. if the underlying filesystem is also performing compression).

Add the "none" compression algorithm, which maps to `pebble.CompressionNone`, disabling compression. This new type is supported for each of the three existing cluster settings - storage, backup-storage, and backup-transport.

Closes #122991.

Release note (general change): An additional compression option, "none", was added to allow for the disabling of SSTable compression. This can be used with any of the three existing cluster settings that control SSTable compression.

### CODE REVIEW

**Comment by nicktrav** [comment]
Evidence of this working as intended, using the new metrics from #126330.

Screenshot 2024-07-01 at 9 49 17 AM

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126508#-:-O0joqL0BI2TWldpXUOr:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi and @nicktrav)

___
*[`pkg/storage/pebble.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126508#-O0jof7W77_DOxGoFGbf:-O0jof7W77_DOxGoFGbg:bw8mr75) ([raw file](https://github.com/cockroachdb/cockroach/blob/717613c0f15d2ffde7094ded6db532205615084c/pkg/storage/pebble.go#L235)):*
> ```Go
> 		// value from within a tenant building an sstable for AddSSTable.
> 		settings.SystemVisible, name,
> 		desc+` supported values: `+supportedCompressionValues(),
> ```

The enum setting already adds the possible values to the description

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126508)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi)

___
*[`pkg/storage/pebble.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126508#-O0jof7W77_DOxGoFGbf:-O0kKITv51s00ty-jVVs:bfj4low) ([raw file](https://github.com/cockroachdb/cockroach/blob/717613c0f15d2ffde7094ded6db532205615084c/pkg/storage/pebble.go#L235)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The enum setting already adds the possible values to the description
</blockquote></details>

Perfect. I'll just rip this out then.

**Comment by nicktrav** [comment]
TFTR!

bors r=RaduBerinde

**Pull request merged**
