### PR TITLE
docs: RFC on resource usage boundaries.

### PR DESCRIPTION
**Pull request by knz**
(Work done on the way to #3292, because #7572 hits all over the place)

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7657)

### CODE REVIEW

**Comment by knz** [comment]
cc @dt @petermattis

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[docs/RFCS/resource_usage.md, line 146 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7657#-KM0hewt6bIptQzctGR6:-KM0hewt6bIptQzctGR7:-1835778230) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4603cdb81d97fc736d00c1c6dfcfff8748cf4a7/docs/RFCS/resource_usage.md#L146)):*
> ```Markdown
> 	- the set of aggregate functions being computed in groupNode;
> 	- the set of in-memory right-side rows in joinNode;
> 	- the copy of the result set held in `Executor.execStmt()` until
> ```

From my read of the protocol docs I think we can eliminate this as a possibility. Since all our sql nodes support the Next() call (right?), and the pgwire stuff sends each row as a separate thing but can also send an error at any time. Thus, we can return the sql node to the pgwire package instead of the enumerated results. The only problem I can think of is about retryable operations. We currently have code that retries things when it can. If we do this, we can no longer do that and have to pass that choice up to the user because we've already returned rows to them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7657)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/resource_usage.md, line 10 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7657#-KM1tQFIMPS9pzarrp8G:-KM1tQFIMPS9pzarrp8H:-2026774474) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4603cdb81d97fc736d00c1c6dfcfff8748cf4a7/docs/RFCS/resource_usage.md#L10)):*
> ```Markdown
> # Summary
> 
> We need to bound the resources (time, memory) used by SQL
> ```

There are other resources: client connections, cpu, network. I don't think these need to be addressed here, but you might want to mention them as areas for future work. In addition to strict bounds (which this RFC is targeting), we may eventually want to have throttling (i.e. for cpu  and network). This is definitely outside the scope of this RFC.

---

*[docs/RFCS/resource_usage.md, line 253 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7657#-KM1swM3snkBhRH7eCBX:-KM1swM3snkBhRH7eCBY:1171034382) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4603cdb81d97fc736d00c1c6dfcfff8748cf4a7/docs/RFCS/resource_usage.md#L253)):*
> ```Markdown
> 
> - take the total amount of physical memory available in the system M,
>   excluding swap.
> ```

I'm anxious about using the physical memory for this. Note that the vast majority of memory used by cockroach is the RocksDB block cache which doesn't show up in the Go runtime stats. (We do know what that memory usage number is, though).

We want to use the available memory, but I think we want this to be explicitly limited. I'd prefer taking some fraction of the `--cache-size` to reserve for query execution. 

---

*[docs/RFCS/resource_usage.md, line 291 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7657#-KM1uANp1qDNTglusEBz:-KM1uANqxTSADfVHrGbA:305769971) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4603cdb81d97fc736d00c1c6dfcfff8748cf4a7/docs/RFCS/resource_usage.md#L291)):*
> ```Markdown
> not sure
> 
> Allow swap or not? Proposal is to compute M without swap. Swap yields
> ```

Not (IMO). Performance is horrible when you start swapping. Better to figure out how to explicitly limit memory and switch to disk-based algorithms. For example, it is much better to use a disk sort than to assume infinite memory and use a memory sort + swap. On the other hand, we could use a cache oblivious sort...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7657)*

**Comment by knz** [comment]
PTAL to section "Alternatives" specifically.

cc @RaduBerinde @andreimatei @dt.

**Pull request closed without merging**
