### PR TITLE
sql: bugfixes in FULL and RIGHT OUTER JOIN

### LINKED ISSUE #12311: sql: joinPredicate filter evalution does not take outer joins into consideration
An outer join should return all rows from both tables, even those that do not match the join predicate. We currently exhibit this behavior for unmatched join indices, but we do not respect it for filters on outer joins. This leads to the following behavior, which I think is new because it is suddenly blocking Hibernate:

```
create table a (i int);
create table b (i int, b bool);
insert into a values (1), (2), (3);
insert into b values (1, false), (2, false), (3, true);

root@:26257> SELECT a.i, b.b FROM a LEFT JOIN b ON (a.i = b.i AND b.b = true);
+---+------+
| i |  b   |
+---+------+
| 3 | true |
+---+------+
(1 row)
```

The final query should instead return something like:
```
+---+------+
| i |  b   |
+---+------+
| 1 | NULL |
| 2 | NULL |
| 3 | true |
+---+------+
```

I believe the code that is causing this issue is https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/join.go#L511.

### LINKED ISSUE #12329: sql: panic in `RIGHT JOIN`
Found a simple panic in `RIGHT JOIN` while investigating #12311.

Setup:
```
create table a (i int);
create table b (i int, b bool);
insert into a values (1), (2), (3);
insert into b values (1, false), (2, false), (3, true);
```

Panic:
```
root@:26257> SELECT a.i, b.b FROM a RIGHT JOIN b ON a.i=b.i;
panic: invalid setNeededColumns argument (len 2 instead of 3): [true false] [recovered]
        panic: SELECT a.i, b.i FROM a RIGHT JOIN b ON a.i = b.i;: invalid setNeededColumns argument (len 2 instead of 3): [true false] [recovered]

goroutine 184 [running]:
panic(0x527cba0, 0xc420200e00)
        /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4202ae000)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x527cba0, 0xc420200e00)
        /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc4207fb0da, 0x31)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:446 +0x149
panic(0x5236600, 0xc420200de0)
        /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*scanNode).setNeededColumns(0xc420166700, 0xc420200db8, 0x2, 0x8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/scan.go:311 +0x25c
github.com/cockroachdb/cockroach/pkg/sql.(*joinNode).setNeededColumns(0xc4204c5a40, 0xc420200db0, 0x5, 0x5)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/join.go:273 +0xb1
github.com/cockroachdb/cockroach/pkg/sql.(*selectNode).expandPlan(0xc4209c6b00, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/select.go:412 +0x196
github.com/cockroachdb/cockroach/pkg/sql.(*selectTopNode).expandPlan(0xc420bcd2c0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/select_top.go:77 +0x61
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc4207ce170, 0x5d5b0a0, 0xc420c1d3e0, 0x28f5b901, 0x6241ae0, 0xc420bddf38, 0x4343102, 0xecfe26809)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:232 +0xd0
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc420276840, 0x5d5b0a0, 0xc420c1d3e0, 0xc4207ce170, 0xc420bde101, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1283 +0xa3
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc420276840, 0x5d5b0a0, 0xc420c1d3e0, 0xc4207ce170, 0x101, 0xc4207ce068, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1090 +0x2c2
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc420276840, 0xc420200bc0, 0x1, 0x1, 0xc4207ce170, 0xc4207ce068, 0x101, 0x6, 0xc420bdebf8, 0x404ad2a, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:836 +0x7cd
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc420276840, 0xc4207ce170, 0x1, 0xc4207ce068, 0xc420200c00, 0xc420200bc0, 0x1, 0x1, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:755 +0xeb
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func2(0xc4209c69a0, 0xc420200c00, 0x4000000000000000, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:609 +0x22f
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc4209c69a0, 0xc420c50101, 0xc4204a0a00, 0xc420c520c0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:520 +0x215
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420276840, 0xc4207ce000, 0xc4207fb0da, 0x31, 0x0, 0x0, 0x0, 0x0, 0xc420a69400)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:631 +0x572
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420276840, 0xc4207ce000, 0xc4207fb0da, 0x31, 0x0, 0x0, 0x0, 0x0, 0xc4207fb000)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:452 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc4201f2400, 0x954d5c0, 0xc420a04030, 0xc4207fb0da, 0x31, 0x0, 0x0, 0x0, 0x0, 0x4658301, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:746 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc4201f2400, 0x954d5c0, 0xc420a04030, 0xc4201f2428, 0x36, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:420 +0xb3
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc4201f2400, 0x954d5c0,
<snip>
```

### PR DESCRIPTION
**Pull request by jordanlewis**
This PR solves a couple of issues with our implementation of `JOIN`.

`RIGHT OUTER JOIN` no longer swaps the `JOIN` operands and performs a `LEFT OUTER JOIN` - this simplifies the implementation by removing the `swapped` field from the `joinNode` along with its associated swapping logic. Previously there was a panicking bug in the swap logic that caused `RIGHT JOIN` to fail.

`FULL OUTER JOIN` now behaves correctly when the buckets in our hash join implementation contain more than one row apiece. Previously this caused `RIGHT` and `FULL OUTER JOIN` to fail to output all of the unmatched rows on the right side of the join.

Fixes #12311.
Fixes #12329.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12364)

### CODE REVIEW

**Comment by knz** [comment]
cc @RaduBerinde @irfansharif

**Comment by knz** [comment]
Well so much for wasting two hours yesterday with a monstrosity of a fix :)
This is good! Thanks for tackling it.

---

Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/join.go, line 95 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ1S6-TzQLcflxxlMmg:-KZ1S6-UgUO4jPVI5ECr:b-s9069p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3fab3af226e337049581443064d29728df0eb4/pkg/sql/join.go#L95)):*
> ```Go
> func (b *buckets) InitSeen() {
> 	for _, bucket := range b.buckets {
> 		bucket.seen = make([]bool, len(bucket.rows))
> ```

Register these allocations against `bucketMemAcc`.

---

*[pkg/sql/join.go, line 576 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ1SJmxkNZKaL9x1xXc:-KZ1SJmypPMaNsfQtQAP:b-seg2rs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3fab3af226e337049581443064d29728df0eb4/pkg/sql/join.go#L576)):*
> ```Go
> 					return false, err
> 				}
> 				b.MarkSeen(idx)
> ```

Why do you mark it seen here?

(Also perhaps use the same condition `wantLeftNulls`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-:-KZ1RTslgLnqjFnamqno:bmz10lr)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/join.go, line 95 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ1S6-TzQLcflxxlMmg:-KZ21IEL0s-qmSOpXJMJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3fab3af226e337049581443064d29728df0eb4/pkg/sql/join.go#L95)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Register these allocations against `bucketMemAcc`.
</blockquote></details>

Done.

---

*[pkg/sql/join.go, line 576 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ1SJmxkNZKaL9x1xXc:-KZ2256vnLPljqRtLSco:bign4oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3fab3af226e337049581443064d29728df0eb4/pkg/sql/join.go#L576)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why do you mark it seen here?

(Also perhaps use the same condition `wantLeftNulls`)
</blockquote></details>

Yeah this is unnecessary now - thanks for catching it. Removed. The condition is unnecessary, FWIW, because this whole block is wrapped with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-:-KZ28NX-iU9vbOu2oegj:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/join.go, line 351 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ26-1DA5LMD9isc9sX:-KZ26-1DA5LMD9isc9sY:b-bkrx9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c8f3647ad3ddf85bfb08e76c9e1d2995175063/pkg/sql/join.go#L351)):*
> ```Go
> 	// join predicate fails to match.
> 	if n.joinType != joinTypeInner {
> 		n.emptyRight = make(parser.DTuple, len(n.right.plan.Columns()))
> ```

Do we need `emptyLeft` for `joinTypeLeftOuter`? Likewise, do we need `emptyRight` for `joinTypeRightOuter`?

---

*[pkg/sql/join.go, line 538 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ26jNH9C1d8fxDEkfj:-KZ26jNH9C1d8fxDEkfk:btawfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c8f3647ad3ddf85bfb08e76c9e1d2995175063/pkg/sql/join.go#L538)):*
> ```Go
> 		if !foundMatch && n.joinType != joinTypeInner && n.joinType != joinTypeRightOuter {
> 			// If none of the rows matched the filter and we are computing a
> 			// left or full outer join, we need to add an row with an empty
> ```

`s/an row/a row/`

---

*[pkg/sql/join.go, line 543 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ28tmbPVEx9NZarHvC:-KZ28tmbPVEx9NZarHvD:b-xqgnke) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf9d43786df7617b9fb79b174c016a2c485435/pkg/sql/join.go#L543)):*
> ```Go
> 
> 			n.pred.prepareRow(n.output, lrow, rrow)
> 			if wantLeftNulls {
> ```

Does commit 3 compile? This isnt defined until commit 4

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-:-KZ295o7N1h0HwvYOBfS:bnfp4nl)*

**Comment by RaduBerinde** [comment]
:lgtm_strong:  Great stuff, thanks for fixing!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/join.go, line 423 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ2IfB0wHzwY4I79dks:-KZ2IfB1Mc2shvoDDtyD:b-y16epu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb09d8acea201bb84a90f6fbc13d292753455bdc/pkg/sql/join.go#L423)):*
> ```Go
> 	}
> 
> 	wantRightNulls := n.joinType == joinTypeLeftOuter || n.joinType == joinTypeFullOuter
> ```

`wantRightNulls` is a bit confusing, maybe `wantUnmatchedLeft` instead?

---

*[pkg/sql/join.go, line 104 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ2J-JPwZS629_x6jPV:-KZ2J-JPwZS629_x6jPW:b-y19j9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ef4aa13cc90ec7427703e4933f6cd1d2bc250c/pkg/sql/join.go#L104)):*
> ```Go
> 		nRows += len(bucket.rows)
> 	}
> 	acc.Grow(len(b.buckets)*sizeOfBoolSlice + nRows*sizeOfBool)
> ```

are we ignoring an error here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-:-KZ2J9rOoqE2JchdG2S8:bcgygj2)*

**Comment by irfansharif** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/testdata/join, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ2KFujKRUX4_sD3HS1:-KZ2KFukqLSQQVlMbYBG:bg82tvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c8f3647ad3ddf85bfb08e76c9e1d2995175063/pkg/sql/testdata/join#L104)):*
> ```
>   44
> 
> query I colnames
> ```

If I'm not mistaken, there should be a `rowsort` directive here. Hash joins are non-deterministic in their row ordering. Ditto for all tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364)*

**Comment by jordanlewis** [comment]
Thanks for all the reviews!

---

Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/join.go, line 351 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ26-1DA5LMD9isc9sX:-KZ2AYgou0vbwN1Nsz_8:bh5hsdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c8f3647ad3ddf85bfb08e76c9e1d2995175063/pkg/sql/join.go#L351)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need `emptyLeft` for `joinTypeLeftOuter`? Likewise, do we need `emptyRight` for `joinTypeRightOuter`?
</blockquote></details>

Nope - fixed.

---

*[pkg/sql/join.go, line 538 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ26jNH9C1d8fxDEkfj:-KZ2Awn-3DT3wPZ-FlkO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c8f3647ad3ddf85bfb08e76c9e1d2995175063/pkg/sql/join.go#L538)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/an row/a row/`
</blockquote></details>

Done.

---

*[pkg/sql/join.go, line 543 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ28tmbPVEx9NZarHvC:-KZ2Av3zHiBAna_GmN5I:b-2h7f5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dcf9d43786df7617b9fb79b174c016a2c485435/pkg/sql/join.go#L543)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does commit 3 compile? This isnt defined until commit 4
</blockquote></details>

Reordered these two commits to fix the issue, whoops.

---

*[pkg/sql/join.go, line 423 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ2IfB0wHzwY4I79dks:-KZ2LpKaLPZ1g0CiIr5Y:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb09d8acea201bb84a90f6fbc13d292753455bdc/pkg/sql/join.go#L423)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`wantRightNulls` is a bit confusing, maybe `wantUnmatchedLeft` instead?
</blockquote></details>

Good idea, done.

---

*[pkg/sql/join.go, line 104 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ2J-JPwZS629_x6jPV:-KZ2Lna2-bnfXZZYYBbf:b60r506) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ef4aa13cc90ec7427703e4933f6cd1d2bc250c/pkg/sql/join.go#L104)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

are we ignoring an error here?
</blockquote></details>

Yes, done.

---

*[pkg/sql/testdata/join, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ2KFujKRUX4_sD3HS1:-KZ2QJuQ8VIohCp0rS-W:bnhmn39) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c8f3647ad3ddf85bfb08e76c9e1d2995175063/pkg/sql/testdata/join#L104)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

If I'm not mistaken, there should be a `rowsort` directive here. Hash joins are non-deterministic in their row ordering. Ditto for all tests.
</blockquote></details>

Good point. I agree in theory, but I can't seem to reproduce this non-determinism. I'm going to leave this alone for now because this PR is big enough already - I'll revisit if necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-:-KZ2Rx57E2Man-Zv_ztF:bd36oot)*

**Comment by irfansharif** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/testdata/join, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ2KFujKRUX4_sD3HS1:-KZ2SVjtdaIWDIlC8i4C:b-1s5rq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c8f3647ad3ddf85bfb08e76c9e1d2995175063/pkg/sql/testdata/join#L104)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Good point. I agree in theory, but I can't seem to reproduce this non-determinism. I'm going to leave this alone for now because this PR is big enough already - I'll revisit if necessary.
</blockquote></details>

I mean this will cause flaky tests depending on the machine running these tests, we didn't run into this before with our nested loop implementation because it *was* deterministic. @knz thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/testdata/join, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ2KFujKRUX4_sD3HS1:-KZ2U9F4tMiSm9gwIz5z:bc8mvlo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c8f3647ad3ddf85bfb08e76c9e1d2995175063/pkg/sql/testdata/join#L104)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I mean this will cause flaky tests depending on the machine running these tests, we didn't run into this before with our nested loop implementation because it *was* deterministic. @knz thoughts?
</blockquote></details>

Yeah the simplest is to add an ORDER BY clause.
(For some reason I'm not sure we can use both "colnames" and "rowsort" and the test must absolutely test column names.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/testdata/join, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ2KFujKRUX4_sD3HS1:-KZ2U7v1jqs4sHhIczZK:bviuuez) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c8f3647ad3ddf85bfb08e76c9e1d2995175063/pkg/sql/testdata/join#L104)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yeah the simplest is to add an ORDER BY clause.
(For some reason I'm not sure we can use both "colnames" and "rowsort" and the test must absolutely test column names.)
</blockquote></details>

We are preserving the order of the left rows. So there would be nondeterminism if multiple right rows match any left row, or on right/full outers IF we have more than one unmatched right row.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-:-KZ2WB86iDQacrb_9Jth:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/testdata/join, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364#-KZ2KFujKRUX4_sD3HS1:-KZ2lyBWYw03DgQJB53Y:b-86lsts) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c8f3647ad3ddf85bfb08e76c9e1d2995175063/pkg/sql/testdata/join#L104)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We are preserving the order of the left rows. So there would be nondeterminism if multiple right rows match any left row, or on right/full outers IF we have more than one unmatched right row.
</blockquote></details>

Added some more tests for the second case, and added an `ORDER BY` to the test that was hitting the first case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12364)*

**Pull request merged**
