### PR TITLE
colexec: give each router output its own disk account

### LINKED ISSUE #46216: colexec: TestHashRouterRandom fails
I saw it on one of CI [builds](https://teamcity.cockroachdb.com/viewLog.html?buildId=1814084&buildTypeId=Cockroach_UnitTests) and it can be easily reproduced under stress.
```
Yahors-MacBook-Pro:cockroach yuzefovich$ make stress PKG=./pkg/sql/colexec TESTS=TestHashRouterRandom
Running make with -j16
GOPATH set to /Users/yuzefovich/go
GOFLAGS= go test   -exec 'stress ' -tags ' make x86_64_apple_darwin19.3.0' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=v20.1.0-alpha.20191118-3237-g1139489888" -X "github.com/cockroachdb/cockroach/pkg/build.rev=1139489888fb15258efd7df01159f6ee3bd0bf49" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-apple-darwin19.3.0"  ' -run "TestHashRouterRandom" -timeout 0 ./pkg/sql/colexec  -v -args -test.timeout 20m

I200317 20:05:12.239051 1 rand.go:85  Random seed: -5198129252426211048
coldata.BatchSize() is set to 1024
=== RUN   TestHashRouterRandom
=== RUN   TestHashRouterRandom/numOutputs=18/blockedThreshold=831/outputSize=2962/totalInputSize=600/hashCols=[0_1]/cancel=false/memoryLimit=0_B
=== RUN   TestHashRouterRandom/numOutputs=18/blockedThreshold=831/outputSize=2962/totalInputSize=600/hashCols=[0_1]/cancel=false/memoryLimit=0_B/batchSize=1/sel=false
=== RUN   TestHashRouterRandom/numOutputs=18/blockedThreshold=831/outputSize=2962/totalInputSize=600/hashCols=[0_1]/cancel=false/memoryLimit=0_B/batchSize=1/sel=true
=== RUN   TestHashRouterRandom/numOutputs=18/blockedThreshold=831/outputSize=2962/totalInputSize=600/hashCols=[0_1]/cancel=false/memoryLimit=0_B/batchSize=2/sel=false
panic: test-disk: no bytes in account to release, current 581, free 661

goroutine 121 [running]:
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink(0xc0002f4560, 0x69f49e0, 0xc0000f8008, 0x295)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:568 +0x1a9
github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Close(0xc00010d7a0, 0x69f49e0, 0xc0000f8008, 0xc0008e3e88, 0x582dcc2)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:428 +0x23d
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*spillingQueue).close(0xc0003a23c0, 0x69f49e0, 0xc0000f8008, 0x40312f1, 0x660d898)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/spilling_queue.go:263 +0x73
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).closeLocked(0xc000030ea0, 0x69f49e0, 0xc0000f8008)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:225 +0x4b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).Next(0xc000030ea0, 0x69f49e0, 0xc0000f8008, 0x0, 0x0)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:218 +0x23b
github.com/cockroachdb/cockroach/pkg/sql/colexec.TestHashRouterRandom.func1.1.1(0xc00010cea0, 0x12, 0x12, 0x69f49e0, 0xc0000f8008, 0xc0002ae3f8, 0xc0001901b0, 0x12, 0x12, 0xc0002ae8e0, ...)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers_test.go:835 +0x79
created by github.com/cockroachdb/cockroach/pkg/sql/colexec.TestHashRouterRandom.func1.1
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers_test.go:833 +0x67c


ERROR: exit status 2

2 runs completed, 1 failures, over 3s
context canceled
```

I believe the problem is that although monitors can be accessed concurrently, accounts cannot - each router output needs to have its own disk account.

### LINKED ISSUE #46218: sql/logictest: TestLogic failed
[(sql/logictest).TestLogic failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1814099&tab=buildLog) on [master@92b232044615a647d22fb220efcf53707cc0e4c7](https://github.com/cockroachdb/cockroach/commits/92b232044615a647d22fb220efcf53707cc0e4c7):

Fatal error:
```
panic: hash-router-[8,13,18,23,28]: no bytes in account to release, current 339, free 524 [recovered]
	panic: hash-router-[8,13,18,23,28]: no bytes in account to release, current 339, free 524

```

Stack:
```
goroutine 9822297 [running]:
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror.CatchVectorizedRuntimeError.func1(0xc006dcfe60)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:62 +0x566
panic(0x34f19e0, 0xc0093259f0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink(0xc08917bfa0, 0x426e080, 0xc0510fdf80, 0x20c)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:568 +0x1a9
github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Close(0xc03b5c3b00, 0x426e080, 0xc0510fdf80, 0x6a173c, 0xc0014f92b8)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:428 +0x23d
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*spillingQueue).close(0xc0019752c0, 0x426e080, 0xc0510fdf80, 0x692a0c, 0xc006dcfcd8)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/spilling_queue.go:263 +0x73
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).closeLocked(0xc046d58b40, 0x426e080, 0xc0510fdf80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:225 +0x4b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).Next(0xc046d58b40, 0x426e080, 0xc0510fdf80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:218 +0x23b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init.func1.1()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:136 +0x5a
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror.CatchVectorizedRuntimeError(0xc006712c90, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:95 +0x5f
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init.func2(0xc01f568640, 0xc06b44cb30, 0x427e100, 0xc046d58b40, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:156 +0xd7
created by github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:144 +0x1e5

```

<details><summary>Log preceding fatal error</summary><p>

```
=== RUN   TestLogic/5node-dist-disk/distsql_union/Except
--- done: testdata/logic_test/distsql_numtables with config 5node-dist-disk: 27 tests, 0 failures
--- total progress: 106277 statements/queries
--- done: testdata/logic_test/distsql_union with config 5node-dist-disk: 50 tests, 0 failures
rewrote:
CREATE TABLE abc (a INT8 PRIMARY KEY, b INT8, c INT8, FAMILY (a), FAMILY (b), FAMILY (c));


rewrote:
CREATE TABLE t (a INT8 PRIMARY KEY, b INT8, FAMILY (a, b));


rewrote:
CREATE TABLE wxyz (w INT8 PRIMARY KEY, x INT8, y INT8, z INT8, FAMILY (w, x), FAMILY (z, y));


--- done: testdata/logic_test/distsql_distinct_on with config 5node-dist-disk: 15 tests, 0 failures
--- done: testdata/logic_test/window with config 5node-dist-disk: 373 tests, 0 failures
--- progress: testdata/logic_test/distsql_agg: 18 statements/queries
rewrote:
CREATE TABLE one (k INT8 PRIMARY KEY, v INT8, FAMILY (v), FAMILY (k));


rewrote:
CREATE TABLE two (k INT8 PRIMARY KEY, v INT8, FAMILY (k), FAMILY (v));



```

</p></details>

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestLogic PKG=./pkg/sql/logictest TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestLogic.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #46221: sql/colexec: TestHashRouterRandom failed
[(sql/colexec).TestHashRouterRandom failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1814066&tab=buildLog) on [master@1139489888fb15258efd7df01159f6ee3bd0bf49](https://github.com/cockroachdb/cockroach/commits/1139489888fb15258efd7df01159f6ee3bd0bf49):

```
=== RUN   TestHashRouterRandom/numOutputs=30/blockedThreshold=7088/outputSize=10836/totalInputSize=6673/hashCols=[0]/cancel=false/memoryLimit=0_B/batchSize=3601/sel=false
==================
WARNING: DATA RACE
Read at 0x00c0002dc1c8 by goroutine 119:
  github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Grow()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:553 +0x4d
  github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).writeFooterAndFlush()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:491 +0x25d
  github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Dequeue()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:664 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*spillingQueue).dequeue()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/spilling_queue.go:178 +0x4af
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).Next()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:205 +0x449
  github.com/cockroachdb/cockroach/pkg/sql/colexec.TestHashRouterRandom.func1.1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers_test.go:835 +0xfc

Previous write at 0x00c0002dc1c8 by goroutine 24:
  github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Grow()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:560 +0x94
  github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).writeFooterAndFlush()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:491 +0x25d
  github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Dequeue()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:664 +0x8d6
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*spillingQueue).dequeue()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/spilling_queue.go:178 +0x4af
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).Next()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:205 +0x449
  github.com/cockroachdb/cockroach/pkg/sql/colexec.TestHashRouterRandom.func1.1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers_test.go:835 +0xfc

Goroutine 119 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/colexec.TestHashRouterRandom.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers_test.go:833 +0x96c
  github.com/cockroachdb/cockroach/pkg/sql/colexec.runTestsWithFn.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/utils_test.go:486 +0x412
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 24 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/colexec.TestHashRouterRandom.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers_test.go:833 +0x96c
  github.com/cockroachdb/cockroach/pkg/sql/colexec.runTestsWithFn.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/utils_test.go:486 +0x412
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
FAIL	github.com/cockroachdb/cockroach/pkg/sql/colexec	1018.094s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestHashRouterRandom PKG=./pkg/sql/colexec TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestHashRouterRandom.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
Release justification: bug fix.

Monitoring infrastructure has a subtle detail: while monitors are safe
to be used concurrently, bound accounts are not. Previously, we were
giving each routerOutputOp of the hash router the same disk account, but
those components run concurrently, so they could interfere with each
other accounting. Now this is fixed by giving each output its own disk
account.

Fixes: #46216.
Fixes: #46218.
Fixes: #46221.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I wonder whether in `diskQueue.Close` we want to lean on the safe side and add this before shrinking the account:
```
if totalSize > d.diskAcc.Used() {
  totalSize = d.diskAcc.Used()
}
d.diskAcc.Shrink(ctx, totalSize)
```
I don't see any problems with accounting now, so that might hide problems if there are any.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46220#-:-M2h-LaBBbdb_0fg5zUS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

**Review by asubiotto — COMMENTED** [review]
I don't see why not.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46220#-:-M2h-TV65H2LICM6OxBq:b-evftsk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

**Comment by asubiotto** [comment]
I'll merge as is since it seems to be failing quite often, we can do any follow-up changes after this PR.

bors r=asubiotto

**Review by Azhng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46220#-:-M2i0Bup4N-lMnyiyfRd:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng)

**Pull request merged**
