### PR TITLE
vendor: bump Pebble to 485b137631bc

### PR DESCRIPTION
**Pull request by bananabrick**
485b1376 ci: test against go1.19
9de3a89f .*: make MaxConcurrentCompactions dynamically changeable
9f3e4216 internal/keyspan: avoid buffering empty span during DefragmentingIter seeks
a4f88b79 sstable: disallow identical point keys

Release note: None

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85496#-:-N8VyLgo8dT8cle1GuR4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick)

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85496)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick)

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85496)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick)

**Comment by dt** [comment]
Don't we need to change the actual setting default to false, not just toggle it in the test? Isn't the test telling us we have a real error here otherwise?

**Review by bananabrick — COMMENTED** [review]
That's probably right.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85496#-:-N8_c5h717MWPi4ysDK7:bomryav)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rhu713)

**Review by bananabrick — COMMENTED** [review]
Flipping to default false to see if anything breaks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85496#-:-N8_d_MrCUwZFSWCS-Nz:b8dlpte)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rhu713)

**Comment by dt** [comment]
Can probably remove the test changes too then just to keep it closer to representative of the real behavior

**Pull request closed without merging**
