### PR TITLE
Admin API: Augment {Database|Table}Details

### PR DESCRIPTION
**Pull request by mrtracy**
Add additional information to the DatabaseDetails and TableDetails response
messages from the AdminAPI.
- Add DescriptorID for both DatabaseDetails and TableDetails. This will allow
  client-side filtering of Events relevant to a specific table or database.
- Add ZoneConfig information to DatabaseDetails. This was previously available
  in TableDetails, but not DatabaseDetails.

Commit also repairs an issue where incoming database names were being improperly
escaped by the Admin API.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8962)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 415 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KQSGxy6M5VZVHcxCe_T:-KQSGxy6M5VZVHcxCe_U:b41eozd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc861da179f6c285133b9086960c234ff8539654/server/admin.go#L415)):*
> ```Go
> 
> 	// Range and ZoneConfig information is not applicable to virtual schemas.
> 	if !sql.IsVirtualDatabase(req.Database) {
> ```

I assume this is the bug fix you were referring to. Can you put it in a separate commit please?

---

*[server/serverpb/admin.proto, line 73 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KQSG1aOBSXvJJwqg6Oa:-KQSG1aOBSXvJJwqg6Ob:b-ib32e0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc861da179f6c285133b9086960c234ff8539654/server/serverpb/admin.proto#L73)):*
> ```protobuf
>   // database.
>   repeated string table_names = 2;
>   // descriptor_id is an identifier used by the backend to uniquely identify
> ```

is this a typical comment style - that is, why does this discuss "the backend"? couldn't you just say it's the database's ID?

---

*[server/serverpb/admin.proto, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KQSGBww1yCSe7r0CsL_:-KQSGBww1yCSe7r0CsLa:b-19llk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc861da179f6c285133b9086960c234ff8539654/server/serverpb/admin.proto#L153)):*
> ```protobuf
>   // The level at which this object's zone configuration is set.
>   ZoneConfigurationLevel zone_config_level = 7;
>   // descriptor_id is an identifier used by the backend to uniquely identify
> ```

ditto, except that this is the table's ID, not the database's.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962)*

**Comment by maxlang** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-:-KQWghJdl-JNiVQAWjDv:bnfp4nl)*

**Comment by mrtracy** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/admin.go, line 415 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KQSGxy6M5VZVHcxCe_T:-KR55MUC6mV5k0bBfDbC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc861da179f6c285133b9086960c234ff8539654/server/admin.go#L415)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I assume this is the bug fix you were referring to. Can you put it in a separate commit please?
</details>
Done.

---

*[server/serverpb/admin.proto, line 73 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KQSG1aOBSXvJJwqg6Oa:-KR56QnmlVrteiYwhEF9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc861da179f6c285133b9086960c234ff8539654/server/serverpb/admin.proto#L73)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this a typical comment style - that is, why does this discuss "the backend"? couldn't you just say it's the database's ID?
</details>
Done.

---

*[server/serverpb/admin.proto, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KQSGBww1yCSe7r0CsL_:-KR56R7Kce2foUIRpTVZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc861da179f6c285133b9086960c234ff8539654/server/serverpb/admin.proto#L153)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> ditto, except that this is the table's ID, not the database's.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[server/admin_test.go, line 288 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KR57ivEsGdvD6Y00MHn:-KR57ivEsGdvD6Y00MHo:bloyuxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed4eccd304ad77450229a0c8b3fac9ba96728cf/server/admin_test.go#L288)):*
> ```Go
> 	}
> 
> 	// Verify Descriptor ID.
> ```

value judgement: remove this comment.

---

*[server/admin_test.go, line 483 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KR57kpBT6wtb00Ypydt:-KR57kpCQpr4bMUWGbg1:bloyuxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed4eccd304ad77450229a0c8b3fac9ba96728cf/server/admin_test.go#L483)):*
> ```Go
> 	}
> 
> 	// Verify Descriptor ID.
> ```

value judgement: remove this comment.

---

*[server/admin_test.go, line 610 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KR57tWt4jZx3EY6J0PB:-KR57tWt4jZx3EY6J0PC:bogmyti) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed4eccd304ad77450229a0c8b3fac9ba96728cf/server/admin_test.go#L610)):*
> ```Go
> 	// Function to verify the zone for database "test" as returned by the Admin
> 	// API.
> 	verifyDbZone := func(
> ```

please return an error from this rather than calling t.Error/Fatal directly. The line numbers produced by failures of functions like this one are inscrutable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-:-KR589PImFb0KGjMsZ3t:bnfp4nl)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/admin_test.go, line 288 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KR57ivEsGdvD6Y00MHn:-KR5DRx-5ENZ0V-pRvcl:b-lm6eci) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed4eccd304ad77450229a0c8b3fac9ba96728cf/server/admin_test.go#L288)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> value judgement: remove this comment.
</details>
I disagree; it fits in with all of the comments in every other section of this code.  Test code is often "flat" like this, with the body of the function containing multiple distinct assertions. In my opinion, comments like this help to delineate the boundaries between these assertions.

---

*[server/admin_test.go, line 483 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KR57kpBT6wtb00Ypydt:-KR5EAlKRZ8fkLPPi_RH:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed4eccd304ad77450229a0c8b3fac9ba96728cf/server/admin_test.go#L483)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> value judgement: remove this comment.
</details>
Ditto.

---

*[server/admin_test.go, line 610 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KR57tWt4jZx3EY6J0PB:-KR5F8ey7MnrCBxwxRDa:b-1ktavk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed4eccd304ad77450229a0c8b3fac9ba96728cf/server/admin_test.go#L610)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> please return an error from this rather than calling t.Error/Fatal directly. The line numbers produced by failures of functions like this one are inscrutable.
</details>
The arguments to the verify functions are unique in every call, the failure location can be inferred from those arguments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/admin_test.go, line 610 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KR57tWt4jZx3EY6J0PB:-KR5HVP_IfpfFXO6GU-7:bu51blu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed4eccd304ad77450229a0c8b3fac9ba96728cf/server/admin_test.go#L610)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> The arguments to the verify functions are unique in every call, the failure location can be inferred from those arguments.
</details>
As someone who has had to dig into these tests more than the average developer, I'm going to insist that these errors _suck_ to work with with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/admin_test.go, line 610 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962#-KR57tWt4jZx3EY6J0PB:-KR5LwKijmCGtICf7pMI:b-gq9q60) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ed4eccd304ad77450229a0c8b3fac9ba96728cf/server/admin_test.go#L610)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> As someone who has had to dig into these tests more than the average developer, I'm going to insist that these errors _suck_ to work with with.
</details>
As someone who has had to write multiple tests that do complicated assertions on a state that evolves in several steps over a complex scenario; it sucks to write code like that.  A lot of these type of assertions intentionally user `Errorf` instead of `Fatalf` because there are different things that can be wrong simultaneously; it's difficult to express that as a single returned error without adding a lot of string construction code.

It would be nice if there were SkipFrames options on the output.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8962)*

**Comment by tamird** [comment]
Couldn't you just always use `t.Fatal` and call it a day?

**Comment by mrtracy** [comment]
You could, but then you might end up re-running the same test several times exposing different failures on the same object. There are also situations where a certain combination of errors raises a more specific suspicion than an individual failure.  It's valuable.

I understand the value of the golang error pointing to the exact line of code, but that's not even always possible; think of the number of loop-based tests we have, which necessarily feature a "case number" in the error output.  A "case" number can also be added to this style of assertion (I have done so before in the time series tests), but in this test the total number of assertions is low enough (and the arguments always unique) that I feel it's understandable as is.

**Pull request merged**
