### PR TITLE
doctor: add examine and recreate commands

### LINKED ISSUE #62459: sql: tool to inject descriptors from a debug.zip into a cluster or a demo
We semi-frequently see problems with schema descriptors that require us to analyze debug.zips and provide commands to clear the corruption. One problem is that we don't have an easy way to get a local environment into the same state that the debug.zip is.

This tool should consume a debug zip and inject the descriptors inside of it into an existing database cluster.

### PR DESCRIPTION
**Pull request by postamar**
doctor: add verbose flag
    
    This commit adds a --verbose flag to the debug doctor CLI command
    which increases output verbosity.
    
    Release note (cli change): added --verbose flag to debug doctor command.

    doctor: fix string comparison bug
    
    Previously, doctor could panic when outputting validation failures with
    error messages under a certain length. This commit fixes this by using
    the proper string prefix comparison function, strings.HasPrefix.
    
    Release note: None

    sql: add checks in unsafe_upsert_descriptor
    
    Previously, it was quite easy to cause a node to crash by passing an
    invalid descriptor argument to the crdb_internal.unsafe_upsert_descriptor
    repair function. This commit makes this function more resilient to
    invalid inputs by changing the descpb.GetDescriptorMetadata function to
    return errors instead of panicking.
    
    Release note: None

    doctor: add examine and recreate commands
    
    The doctor tool can be very helpful for troubleshooting schema
    corruption issues. These investigations often involve loading the
    corrupted descriptor(s) into a local test environment to either better
    understand the root cause or to craft a valid descriptor for a repair.
    In any case, until now this required taking the descriptor hex encodings
    from the debug.zip and updating the system.descriptor table. This can be
    tedious and error-prone. Recent improvements to descriptor validation
    logic have also made it harder to deliberately corrupt descriptors,
    which has unfortunate side-effects in this use case.
    
    This commit changes the doctor CLI commands, adding the 'examine' and
    'recreate' commands. The former did what doctor used to do, the latter
    will output a series of SQL statements. When executed on an empty cluster
    these will populate it with all of the non-system descriptors and
    namespace table entries.
    
    These descriptors are almost as they were, except:
    - the version counter is reset to 1,
    - the modification time is unset,
    - the create-as-of time is unset (tables only).
    Maintaining the original values would violate too many assumptions to be
    safe.
    
    Fixes #62459.
    
    Release note (cli change): The doctor debug tool now has new 'examine'
    and 'recreate' commands. The new 'debug doctor examine' invocation
    replaces the old 'debug doctor' invocation. The new
    'debug doctor recreate' invocation prints SQL statements which will
    recreate the descriptor and namespace state when run in a new, empty
    cluster.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63656)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/cli/doctor.go, line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYdOsaM7NWi-f_b9Zct:-MYdOsaM7NWi-f_b9Zcu:b9rauke) ([raw file](https://github.com/cockroachdb/cockroach/blob/01a5ef5d35caf0c4cf0fd8310b1f3e05ba2a7496/pkg/cli/doctor.go#L57)):*
> ```Go
> 	Short: "examine system tables for inconsistencies",
> 	Long: `
> Run doctor tool to examine system tables and perform validation checks.
> ```

Run the doctor tool ...
___
*[pkg/cli/doctor.go, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYdOqPB5Hf4FpcAI6MG:-MYdOqPB5Hf4FpcAI6MH:b9rauke) ([raw file](https://github.com/cockroachdb/cockroach/blob/01a5ef5d35caf0c4cf0fd8310b1f3e05ba2a7496/pkg/cli/doctor.go#L70)):*
> ```Go
> 	Short: "prints SQL that tries to recreate system table state",
> 	Long: `
> Run doctor tool to examine system tables and generate SQL statements that,
> ```

Run the doctor tool ...
___
*[pkg/cli/doctor.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYdOhz0Ef6ZJi7mAWJB:-MYdOhz13na5wTKutbo-:bouffad) ([raw file](https://github.com/cockroachdb/cockroach/blob/01a5ef5d35caf0c4cf0fd8310b1f3e05ba2a7496/pkg/cli/doctor.go#L85)):*
> ```Go
> 		Short: "run doctor tool on data from a directory unzipped from debug.zip",
> 		Long: `
> Run doctor tool on system data from directory	created by unzipping debug.zip.
> ```

Run the doctor tool ...
from the directory ...
(also, please remove the stray extra spaces)
___
*[pkg/cli/doctor.go, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYdOmhyBTHAT2exJ5SF:-MYdOmhyBTHAT2exJ5SG:b-4zccgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/01a5ef5d35caf0c4cf0fd8310b1f3e05ba2a7496/pkg/cli/doctor.go#L101)):*
> ```Go
> 	return &cobra.Command{
> 		Use:   "cluster --url=<cluster connection string>",
> 		Short: "run doctor tool on live cockroach cluster",
> ```

Run the doctor tool ...
on a live ...
___
*[pkg/cli/doctor.go, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYdOyAeClJA_5Hr4e0J:-MYdOyAeClJA_5Hr4e0K:b9rauke) ([raw file](https://github.com/cockroachdb/cockroach/blob/01a5ef5d35caf0c4cf0fd8310b1f3e05ba2a7496/pkg/cli/doctor.go#L103)):*
> ```Go
> 		Short: "run doctor tool on live cockroach cluster",
> 		Long: `
> Run doctor tool reading system data from a live cluster specified by --url.
> ```

Run the doctor tool ...

**Comment by knz** [comment]
(I'm not reviewing the "meat" of this PR)

**Comment by postamar** [comment]
Thanks @knz. I reworked the documentation strings a bit.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 15 files at r5, 1 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63656)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @postamar)

___
*[pkg/cli/doctor.go, line 51 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYexPWi9LxVZrl5K9Vw:-MYexPWi9LxVZrl5K9Vx:ba4piw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec03fb83ccdf55a521d803a109e178b41bf9ebb/pkg/cli/doctor.go#L51)):*
> ```Go
> debug.zip.
> `,
> 	Args: cobra.MinimumNArgs(1),
> ```

Is this right? Shouldn't it just not accept any args?
___
*[pkg/cli/doctor.go, line 62 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYexTG00ryMxi3Xw4d1:-MYexTG00ryMxi3Xw4d2:b-xggnpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec03fb83ccdf55a521d803a109e178b41bf9ebb/pkg/cli/doctor.go#L62)):*
> ```Go
> debug.zip.
> `,
> 	Args: cobra.MinimumNArgs(1),
> ```

why not exactly one arg?
___
*[pkg/cli/doctor.go, line 65 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYexH0k4SbwVLG9S5EU:-MYexH0k4SbwVLG9S5EV:b-7h6ap4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec03fb83ccdf55a521d803a109e178b41bf9ebb/pkg/cli/doctor.go#L65)):*
> ```
> 	PersistentPreRun: func(cmd *cobra.Command, args []string) {
> 	},
> ```
why?
___
*[pkg/cli/doctor.go, line 76 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYexVDB9SoNwx21GGCM:-MYexVDB9SoNwx21GGCN:b-xggnpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec03fb83ccdf55a521d803a109e178b41bf9ebb/pkg/cli/doctor.go#L76)):*
> ```Go
> tables are queried either from a live cluster or from an unzipped debug.zip.
> `,
> 	Args: cobra.MinimumNArgs(1),
> ```

why not exactly one arg?
___
*[pkg/cli/doctor.go, line 158 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYexe9w5mBgHUtUA_-t:-MYexe9w5mBgHUtUA_-u:b-1b03m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec03fb83ccdf55a521d803a109e178b41bf9ebb/pkg/cli/doctor.go#L158)):*
> ```Go
> 		err = doctor.DumpSQL(out, descTable, namespaceTable)
> 	default:
> 		err = errors.New("invalid command")
> ```

Can you reach this case? I'm not so keen on this breaking change. Instead should we make it so that the default command is the same as examine to not break existing workflows?

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63656)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @postamar)

___
*[pkg/cli/doctor.go, line 51 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYexPWi9LxVZrl5K9Vw:-MYf3ALo7XzwQ-Eg2NYX:bjtqxk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec03fb83ccdf55a521d803a109e178b41bf9ebb/pkg/cli/doctor.go#L51)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is this right? Shouldn't it just not accept any args?
</blockquote></details>

No, it's not right, it's garbage I committed by mistake, and which I didn't notice. Sorry about this.
Same applies to all but the last of your comments.
___
*[pkg/cli/doctor.go, line 158 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYexe9w5mBgHUtUA_-t:-MYf3Iym0mExfGj2RoUL:bth5oku) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec03fb83ccdf55a521d803a109e178b41bf9ebb/pkg/cli/doctor.go#L158)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you reach this case? I'm not so keen on this breaking change. Instead should we make it so that the default command is the same as examine to not break existing workflows?
</blockquote></details>

I now made "examine" the default, if that's what you meant.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 9 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63656)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @postamar)

___
*[pkg/cli/debug.go, line 1310 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfJAog-g5BdQb_YndV:-MYfJAog-g5BdQb_YndW:b-i1r9zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/28ffab697f24fd84045be5fb343013127caf0696/pkg/cli/debug.go#L1310)):*
> ```Go
> 		f.BoolVarP(&doctorOptions.Verbose, "verbose", "v", doctorOptions.Verbose,
> 			"verbose output")
> 	}
> ```

should you also do `debugDoctorCmd.AddCommand(doctorExaminClusterCmd, doctorExamineZipDirCmd)`?
___
*[pkg/cli/doctor.go, line 50 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfIch252M6d59AC_op:-MYfIch252M6d59AC_oq:bjv657p) ([raw file](https://github.com/cockroachdb/cockroach/blob/28ffab697f24fd84045be5fb343013127caf0696/pkg/cli/doctor.go#L50)):*
> ```Go
> System tables are queried either from a live cluster or from an unzipped 
> debug.zip.
> `,
> ```

Shouldn't this carry a very similar `Run` to `examine
___
*[pkg/cli/doctor.go, line 136 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfIMsB1oqf6Px8HMI8:-MYfIMsCB5eGIXUN3ysz:b-aevz2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/28ffab697f24fd84045be5fb343013127caf0696/pkg/cli/doctor.go#L136)):*
> ```Go
> 		err = doctor.DumpSQL(out, descTable, namespaceTable)
> 	default:
> 		fallthrough // Default to "examine".
> ```

the linter does not like this. Looking at it, I think that makes sense. I don't really get how you end up here with `""` or really anything else. I'd think it'd be `doctor` that'd be the parent that you want to fallthrough to `Examine` on and then leave `default` as an error that should be unreachable.
___
*[pkg/cli/testdata/doctor/test_examine_cluster, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfJlun7EEyk9np-twx:-MYfJlun7EEyk9np-twy:b-uxhnry) ([raw file](https://github.com/cockroachdb/cockroach/blob/c36e908e18c5a7de399bc6e84d9e957f3cd5ec54/pkg/cli/testdata/doctor/test_examine_cluster#L1)):*
> ```
> debug doctor examine cluster
> ```

can you add some testing to ensure that without `examine` it still works. A test that also runs it with some garbage like `debug doctor asdf` that ensures we get a sane error would be good.

**Comment by postamar** [comment]
Will do. It seems like I misunderstood your earlier comment. I understand now.

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63656)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @postamar)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfpE0k1P9sY0D-2yun:-MYfpE0k1P9sY0D-2yuo:bxndbe9) (no related file):*
Thanks for the review. I believe I've addressed all points.

---
___
*[pkg/cli/debug.go, line 1310 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfJAog-g5BdQb_YndV:-MYfogyD6aiVNkziPZ4i:b-xgh75m) ([raw file](https://github.com/cockroachdb/cockroach/blob/28ffab697f24fd84045be5fb343013127caf0696/pkg/cli/debug.go#L1310)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should you also do `debugDoctorCmd.AddCommand(doctorExaminClusterCmd, doctorExamineZipDirCmd)`?
</blockquote></details>

I did something to that effect.
___
*[pkg/cli/doctor.go, line 50 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfIch252M6d59AC_op:-MYfodoWE38kMUOpg97f:bv1xb8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/28ffab697f24fd84045be5fb343013127caf0696/pkg/cli/doctor.go#L50)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Shouldn't this carry a very similar `Run` to `examine
</blockquote></details>

I believe it does.
___
*[pkg/cli/doctor.go, line 136 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfIMsB1oqf6Px8HMI8:-MYfop8r1ykghNWr70JE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28ffab697f24fd84045be5fb343013127caf0696/pkg/cli/doctor.go#L136)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

the linter does not like this. Looking at it, I think that makes sense. I don't really get how you end up here with `""` or really anything else. I'd think it'd be `doctor` that'd be the parent that you want to fallthrough to `Examine` on and then leave `default` as an error that should be unreachable.
</blockquote></details>

Done.
___
*[pkg/cli/testdata/doctor/test_examine_cluster, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfJlun7EEyk9np-twx:-MYfoqnAEHYFgI-_ESWE:b-reuwfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c36e908e18c5a7de399bc6e84d9e957f3cd5ec54/pkg/cli/testdata/doctor/test_examine_cluster#L1)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you add some testing to ensure that without `examine` it still works. A test that also runs it with some garbage like `debug doctor asdf` that ensures we get a sane error would be good. 
</blockquote></details>

Done. I tried adding a garbage command test but the `--rewrite` flag gets in the way of making the test data-driven, so I decided against it in the end.

**Review by ajwerner — APPROVED** [review]
:lgtm: mod nits

> Reviewed 1 of 6 files at r15, 1 of 9 files at r16, 5 of 7 files at r17.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-:-MYfucKxEFNWcn5brmW3:b-tkmfg9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @postamar)

___
*[pkg/cli/flags.go, line 841 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYftw6aDFeps69N4doR:-MYftw6aDFeps69N4doS:b6i8m5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c04c8f2bf3080422d300ec07ea7e78b8e9a5e7/pkg/cli/flags.go#L841)):*
> ```Go
> 			f := c.Flags()
> 			boolFlag(f, &debugCtx.verbose, cliflags.Verbose)
> ```

nit: stray line
___
*[pkg/sql/catalog/lease/lease.go, line 1725 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfuF7M8oAiFY4xAfvl:-MYfuF7M8oAiFY4xAfvm:b40sjit) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c04c8f2bf3080422d300ec07ea7e78b8e9a5e7/pkg/sql/catalog/lease/lease.go#L1725)):*
> ```
> 
> 					panic(err)
> 				}
> ```
I don't know about these panics. `log.Fatalf` so we get a crash report? A panic from a different goroutine that isn't caught will just exit the process and we'll never know.

(yes, I get that it was already panicking, but it's better to not let somebody cargo cult this bad behavior in the future)

**Review by postamar — COMMENTED** [review]
Will address. Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-:-MYjGO9O4Bkrucj_cObU:b23midl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @postamar)

___
*[pkg/cli/flags.go, line 841 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYftw6aDFeps69N4doR:-MYjFxmv90H1a3U60WkY:b-1ofb7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c04c8f2bf3080422d300ec07ea7e78b8e9a5e7/pkg/cli/flags.go#L841)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: stray line
</blockquote></details>

Will do. Sorry for the sloppiness.
___
*[pkg/sql/catalog/lease/lease.go, line 1725 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/63656#-MYfuF7M8oAiFY4xAfvl:-MYjG9Ai7eMTLPvz-nBI:b-46b0np) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c04c8f2bf3080422d300ec07ea7e78b8e9a5e7/pkg/sql/catalog/lease/lease.go#L1725)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 					panic(err)
> 				}
> ```
I don't know about these panics. `log.Fatalf` so we get a crash report? A panic from a different goroutine that isn't caught will just exit the process and we'll never know.

(yes, I get that it was already panicking, but it's better to not let somebody cargo cult this bad behavior in the future)
</blockquote></details>

Will do! This dates to just before I read @knz's error style guide.

**Pull request merged**
