### PR TITLE
cli: improve unsafe-remove-dead-replicas

### PR DESCRIPTION
**Pull request by tbg**
Update the commentary to reflect how we simply cannot tell at a glance
whether the tool is safe to use in a given situation.

Also, fix a straight-up bug that would make a bad situation worse: Prior
to this commit, `unsafe-remove-dead-replicas` did not take into account
the existence of learners, and it would simply pick the highest storeID
as the designated survivor.  Consider a range in which s1 is a voter, s2
is dead, and s3 is demoting. s3 would be picked as the designated
survivor, but all it can then do is to turn itself into a learner,
resulting in a range with no voters (if s3 was a learner to begin with,
skip that intermediate step).  Now, the tool picks the designated
survivor as the max storeID of a current or incoming voter, so it would
pick s1 instead.

Also, improve the logging to also report on replicas for which no action
is taken. This is in response to an internal support ticket
(support#1206) in which the tool took no action for a range despite it
containing a member marked as dead.

Release note (bug fix): The `cockroach debug
unsafe-remove-dead-replicas` tool was improved to handle the existence
of learners. It will now produce the desired results in more
circumstances. The tool remains dangerous and can irrevocably corrupt
a cluster.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cli/debug.go, line 1143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70251#-MjiXUIEBKT6d1sW7D-O:-MjiXUIFEmXGX-9LZpsY:b1691o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b5d565994cfe7367dcdde2d17e7eb55d68303f/pkg/cli/debug.go#L1143)):*
> ```Go
> 		}
> 
> 		// If the replica thinks it can make progress anyway, so we leave it alone.
> ```

Typo: If...so is wrong.
___
*[pkg/cli/debug.go, line 1260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70251#-MjiYBLj8fRf1l6ubdhR:-MjiYBLj8fRf1l6ubdhS:b-opr87t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b5d565994cfe7367dcdde2d17e7eb55d68303f/pkg/cli/debug.go#L1260)):*
> ```Go
> 			// descriptors are), and so multiple replicas of a range may declare
> 			// themselves the designated survivor. Long story short, use of this tool
> 			// with our without the presence of an intent can - in theory - really
> ```

s/our/or

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70251#-Mjin2cTBhQjCsFAFmOE):*
Consider taking the opportunity to update the comments that insist on the tool being used with all the nodes stopped. Perhaps mention the situation where a valid lease is held by a removed replica, which confuses the code

**Review by tbg — COMMENTED** [review]
TFTR!
bors r=erikgrinaker

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70251#-:-Mk2J-221m8sTZ0FNpo_:b-xx1ktn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @erikgrinaker)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70251#-Mjin2cTBhQjCsFAFmOE):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Consider taking the opportunity to update the comments that insist on the tool being used with all the nodes stopped. Perhaps mention the situation where a valid lease is held by a removed replica, which confuses the code 
</blockquote></details>

Done.
___
*[pkg/cli/debug.go, line 1143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70251#-MjiXUIEBKT6d1sW7D-O:-Mk2IwCpDe2Jfai7EbQZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b5d565994cfe7367dcdde2d17e7eb55d68303f/pkg/cli/debug.go#L1143)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Typo: If...so is wrong.
</blockquote></details>

Done.
___
*[pkg/cli/debug.go, line 1260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70251#-MjiYBLj8fRf1l6ubdhR:-Mk2IyiM1VeiJBavZOgr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b5d565994cfe7367dcdde2d17e7eb55d68303f/pkg/cli/debug.go#L1260)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

s/our/or
</blockquote></details>

Done.

**Comment by tbg** [comment]
Not my test failure

 bors r=erikgrinaker

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by tbg** [comment]
blathers backport 21.1

**Pull request merged**
