### PR TITLE
sql: unify descriptor version of primary key and secondary index

### LINKED ISSUE #72711: catalog/descpb,tabledesc: IndexDescriptorVersion is not applied uniformly to all new indexes
**Is your feature request related to a problem? Please describe.**

In https://github.com/cockroachdb/cockroach/pull/66599, we added a new index descriptor version, but we started to only apply this version to primary indexes and not to secondary indexes. The logic at the time was that the version only affected primary indexes. This, in retrospect, seems like a bit of a divergence from the intended usage of version, which was intended to be applied to all new indexes at a certain point in code.

Like, version primarily exists to inform different layers how to act in the face of different index state. In particular, if I understand correctly, we wanted to capture differences in the format of the encoded data (and a bit less about the descriptor).  Later versions have had more to do with the invariants of the descriptor itself (and thus have been more amenable to migration).

What I can't figure out is how secondary indexes marked as `PrimaryIndexWithStoredColumnsVersion` would behave differently at all from ones labeled `StrictIndexColumnIDGuaranteesVersion`.

**Describe the solution you'd like**

My vote is that we don't touch anything about existing ones, but we stop this pattern of separating how we label index versions. 

**Additional context**

In #72694 we codified the present status quo. This issue asks that we break this status quo and go back to having a single current index version which will apply to all new indexes.

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes: #72711

Added logic in `maybeUpgradeSecondaryIndexFormatVersion` to promote
descriptor version to `PrimaryIndexWithStoredColumnsVersion` if current
version is `StrictIndexColumnIDGuaranteesVersion`. Existing migrations
should be able to just fix it when they are run. For example, the
`runRemoveInvalidDatabasePrivileges` migration.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
It'd be nice to see a test (could be an extension of the existing test) where we have tables with the old version and then make sure that after it's been upgraded, that we see that there are no more indexes with that version. Another idea is to validate (given the cluster settings), that the version is not the now-removed version once the version with the migration is active. 

> Reviewed 10 of 24 files at r1, 1 of 2 files at r2, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76465#-:-MvtHiLr3bqyS2jDvSpN:burdlke)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @postamar)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 1745 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76465#-MvtGw375_oHvygBLs5S:-MvtGw375_oHvygBLs5T:bt2f0zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f28119e89a28eb1e9541fd72f8935e25b756185/pkg/sql/catalog/tabledesc/structured.go#L1745)):*
> ```Go
> 					primaryIndex.Name = args.NewPrimaryIndexName
> 				}
> 				if primaryIndex.Version == descpb.StrictIndexColumnIDGuaranteesVersion {
> ```

Do we need this? Can we comment it if we do?

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 1745 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76465#-MvtGw375_oHvygBLs5S:-MvtbS_V9jNrfjcJEzhL:b-iafibi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f28119e89a28eb1e9541fd72f8935e25b756185/pkg/sql/catalog/tabledesc/structured.go#L1745)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Do we need this? Can we comment it if we do?
</blockquote></details>

This is needed for alter primary key where the new primary index is initially created as a secondary index before being swapped to be a primary index. Will add a comment.

**Review by chengxiong-ruan — COMMENTED** [review]
A simple test added!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76465#-:-MvtuNyRDWgglsn3x2Zs:bevz0ed)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 1745 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76465#-MvtGw375_oHvygBLs5S:-Mvtudc82b3Sftdytqvx:b-qcxdq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f28119e89a28eb1e9541fd72f8935e25b756185/pkg/sql/catalog/tabledesc/structured.go#L1745)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

This is needed for alter primary key where the new primary index is initially created as a secondary index before being swapped to be a primary index. Will add a comment.
</blockquote></details>

comment added!

**Review by ajwerner — APPROVED** [review]
May I request that you file an issue to validate the index descriptor version. Otherwise, :lgtm: mod one small testing suggestion 

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76465#-:-MvtvfAI28SRwhPFKAiJ:b-rlc68k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @postamar)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 1745 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76465#-MvtGw375_oHvygBLs5S:-MvtvXTYEMmecdyfxL6z:b-yeofjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f28119e89a28eb1e9541fd72f8935e25b756185/pkg/sql/catalog/tabledesc/structured.go#L1745)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

comment added!
</blockquote></details>

It shouldn't be needed in 22.2, right? Maybe say that here?
___
*[pkg/sql/catalog/tabledesc/index_test.go, line 573 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76465#-Mvtvmfr1YPl7riHvjE0:-Mvtvmfr1YPl7riHvjE1:b-5p500k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d387fe162e1efa241d03dd781592fedbf39e1137/pkg/sql/catalog/tabledesc/index_test.go#L573)):*
> ```Go
> 				Version:             descpb.StrictIndexColumnIDGuaranteesVersion,
> 			},
> 		},
> ```

put an index in a mutation as well

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76465)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 1745 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76465#-MvtGw375_oHvygBLs5S:-Mvu43h9Bfdi5WD3J8xH:b-7tfmjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f28119e89a28eb1e9541fd72f8935e25b756185/pkg/sql/catalog/tabledesc/structured.go#L1745)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It shouldn't be needed in 22.2, right? Maybe say that here?
</blockquote></details>

added
___
*[pkg/sql/catalog/tabledesc/index_test.go, line 573 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76465#-Mvtvmfr1YPl7riHvjE0:-Mvu46j91NQ1bYlvdQsn:b-7tfmjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d387fe162e1efa241d03dd781592fedbf39e1137/pkg/sql/catalog/tabledesc/index_test.go#L573)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

put an index in a mutation as well 
</blockquote></details>

added

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Comment by chengxiong-ruan** [comment]
TFTR again!
bors r+

**Pull request merged**
