### PR TITLE
opt: reorder joins (off by default)

### PR DESCRIPTION
**Pull request by justinj**
This PR introduces the AssociateJoin rule, which, if the appropriate
session variable is set, will explore additional join orderings.

This commit is presented as a first step - it's not remotely
production-ready (i.e., nobody should be turning on the flag).

Release note (sql change): introduced the experimental_reorder_joins
flags which will (slowly) attempt to find better join orderings for a
query. Not practical for real-world usage today.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
Cool! Can you add some description to the commit message about what the next step is? 

> Reviewed 8 of 8 files at r1, 4 of 4 files at r2, 10 of 10 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-:-LWwP45YAiK0JASm4amP:b-o8b5uf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/join.opt, line 485 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWwO9PUC047YLX49iQ7:-LWwMh7Q7lWWN3RszUxC:bd3kykg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/norm/rules/join.opt#L485)):*
> ```
>         $left
>         $innerLeft
>         (SortFilters (ExtractBoundConditions $on (OutputCols2 $left $innerLeft)))
> ```

Seems like you can let the `SortFiltersInJoin` rule take care of sorting here, right?
___
*[pkg/sql/opt/norm/rules/join.opt, line 488 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWwMozr-SwPPupRKrZl:-LWwMozr-SwPPupRKrZm:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/norm/rules/join.opt#L488)):*
> ```
>     )
>     $innerRight
>     (SortFilters
> ```

ditto
___
*[pkg/sql/opt/testutils/opt_tester.go, line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWwKBxoDgHyzID7nBOb:-LWwKBxp-ccwU-0WCC_U:biq3fl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d33aae885d337838685b14594b29a852d502ac63/pkg/sql/opt/testutils/opt_tester.go#L235)):*
> ```Go
> 		defer func() {
> 			ot.evalCtx.SessionData.ReorderJoins = oldValue
> 		}()
> ```

[nit] can rewrite this as:
```
defer func(oldValue bool) {
    ot.evalCtx.SessionData.ReorderJoins = oldValue
}(ot.evalCtx.SessionData.ReorderJoins)
ot.evalCtx.SessionData.ReorderJoins = true
```
___
*[pkg/sql/opt/xform/rules/join.opt, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWwLr5i47Az6Ee82WUW:-LWwLr5i47Az6Ee82WUX:b-9eqd1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/xform/rules/join.opt#L103)):*
> ```
> #   A JOIN (B JOIN C ON B.x = C.x) ON A.y = B.y
> # to the logically equivalent expression:
> #   (A JOIN B ON A.y = B.y) JOIN C ON B.x = C.x
> ```

I think the rule now converts left-deep plans to right-deep
___
*[pkg/sql/opt/xform/rules/join.opt, line 105 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWwLR6qE2ufsx_01ZeW:-LWwLR6rChcPT-jWyufr:bsegyhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/xform/rules/join.opt#L105)):*
> ```
> #   (A JOIN B ON A.y = B.y) JOIN C ON B.x = C.x
> # It applies as long as the outer predicate is not True (we want to avoid
> # pushing cross joins down), and the outer predicate only references one of
> ```

Update comment since you allow cross joins and references to both relations

**Review by RaduBerinde — APPROVED** [review]
Nice stuff!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-:-LX--8Kc8nTZW9JVdbYz:brkjuz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

___
*[pkg/sql/opt/exec/execbuilder/testdata/join_order, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWzyC1Q6YxlkoipHs_w:-LWzyC1Q6YxlkoipHs_x:b-98vrh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/exec/execbuilder/testdata/join_order#L62)):*
> ```
> 
> query TTTTT
> EXPLAIN (VERBOSE) SELECT * FROM abc, bx, cy WHERE a = 1 AND abc.b = bx.b AND abc.c = cy.c
> ```

This is very cool!
___
*[pkg/sql/opt/memo/memo.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWzydXT4kGhHVyPAXG0:-LWzydXT4kGhHVyPAXG1:b-xlwn2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/fffc58f132f980a16d26140265fa2f742a38c5db/pkg/sql/opt/memo/memo.go#L149)):*
> ```Go
> 
> 	// curID is the highest currently in-use scalar expression ID.
> 	curID int
> ```

[nit] would be good if these were a specific type with some documentation as opposed to `int`, since we have all sorts of IDs
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1458 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWzysSoCWS_qh0BSj87:-LWzysSoCWS_qh0BSj88:bubb00l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b2d0299431a95cac077dd644da59e9cf64591a/pkg/sql/opt/norm/custom_funcs.go#L1458)):*
> ```Go
> // IsFiltersSorted determines whether the expressions in a FiltersExpr are
> // ordered by their expression IDs.
> func (c *CustomFuncs) IsFiltersSorted(f memo.FiltersExpr) bool {
> ```

[nit] AreFiltersSorted or FiltersInOrder
___
*[pkg/sql/opt/norm/rules/join.opt, line 453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWzz71p83AwLjUTHS3f:-LWzz71p83AwLjUTHS3g:b-bimvso) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b2d0299431a95cac077dd644da59e9cf64591a/pkg/sql/opt/norm/rules/join.opt#L453)):*
> ```
> # SortFiltersInJoin ensures that any filters in an inner join are canonicalized
> # by sorting them.
> [SortFiltersInJoin, Normalize]
> ```

Can you explain a bit (maybe in the commit) why having the filters sorted is useful?
___
*[pkg/sql/opt/norm/rules/join.opt, line 466 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWzzL9G6_La34FB5TbG:-LWzzL9G6_La34FB5TbH:biv6m5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/norm/rules/join.opt#L466)):*
> ```
> )
> 
> # NormalizeInnerJoinToLeftDeep rearranges inner joins to a left deep tree, where every right child
> ```

[nit] wrap comments at 80
___
*[pkg/sql/opt/norm/rules/join.opt, line 469 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWzzj0m43_mxQc6n3YD:-LWzzj0m43_mxQc6n3YE:bxlcvtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/norm/rules/join.opt#L469)):*
> ```
> # is not an inner join.
> #
> # This rule is needed to make exploration via AssociateJoin not require the merging of groups.
> ```

I know this is a pain but it would be awesome if there was an example (with an initial tree and how it would lead to merging, and then with the left-deep version and how that doesn't require merging)

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34170)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

___
*[pkg/sql/opt/xform/rules/join.opt, line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LX-TZalBgPg9z9oHVW9:-LX-TZalBgPg9z9oHVWA:b-bqfdhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/xform/rules/join.opt#L122)):*
> ```
> (InnerJoin
>     $innerLeft
>     (InnerJoin
> ```

When this rule constructs this InnerJoin, won't the `NormalizeInnerJoinToLeftDeep` rule kick in? This means that all the variants we generate can only have a left-deep tree as the right child of the root no?

**Review by justinj — COMMENTED** [review]
Added some more explanation to the commit message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-:-LX4hO-pBKctUr2DhO6A:b-a271cp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/memo.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWzydXT4kGhHVyPAXG0:-LX-gqBEDFca26jP3knl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fffc58f132f980a16d26140265fa2f742a38c5db/pkg/sql/opt/memo/memo.go#L149)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] would be good if these were a specific type with some documentation as opposed to `int`, since we have all sorts of IDs
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1458 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWzysSoCWS_qh0BSj87:-LX0il-z8HuWLpP4E4uH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b2d0299431a95cac077dd644da59e9cf64591a/pkg/sql/opt/norm/custom_funcs.go#L1458)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] AreFiltersSorted or FiltersInOrder
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/join.opt, line 453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWzz71p83AwLjUTHS3f:-LX0m40F4eE2vK93A0IN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b2d0299431a95cac077dd644da59e9cf64591a/pkg/sql/opt/norm/rules/join.opt#L453)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you explain a bit (maybe in the commit) why having the filters sorted is useful?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/join.opt, line 469 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWzzj0m43_mxQc6n3YD:-LX0m5imCzGMIVep7fDZ:b-lzuitd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/norm/rules/join.opt#L469)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I know this is a pain but it would be awesome if there was an example (with an initial tree and how it would lead to merging, and then with the left-deep version and how that doesn't require merging)
</blockquote></details>

Hrm, I think I got confused: it seems if we have this "naive" version of AssociateJoin we can safely remove this rule. I'm cautiously going to do so.
___
*[pkg/sql/opt/norm/rules/join.opt, line 485 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWwO9PUC047YLX49iQ7:-LX0mRNA-zdArDrBYQ80:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/norm/rules/join.opt#L485)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like you can let the `SortFiltersInJoin` rule take care of sorting here, right?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/join.opt, line 488 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWwMozr-SwPPupRKrZl:-LX0mRow87eDSdk34VnV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/norm/rules/join.opt#L488)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/opt_tester.go, line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWwKBxoDgHyzID7nBOb:-LX0mu7z1g_TkhqBdZUf:bwhafgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d33aae885d337838685b14594b29a852d502ac63/pkg/sql/opt/testutils/opt_tester.go#L235)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] can rewrite this as:
```
defer func(oldValue bool) {
    ot.evalCtx.SessionData.ReorderJoins = oldValue
}(ot.evalCtx.SessionData.ReorderJoins)
ot.evalCtx.SessionData.ReorderJoins = true
```
</blockquote></details>

nice! that's clever.
___
*[pkg/sql/opt/xform/rules/join.opt, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWwLr5i47Az6Ee82WUW:-LX4bY--6FMll3DjmaiK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/xform/rules/join.opt#L103)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think the rule now converts left-deep plans to right-deep
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/join.opt, line 105 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LWwLR6qE2ufsx_01ZeW:-LX4bYVaDQvBesWm1nLA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/xform/rules/join.opt#L105)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Update comment since you allow cross joins and references to both relations
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/join.opt, line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-LX-TZalBgPg9z9oHVW9:-LX4c-FG2s_FYniKIZFK:bicouxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167b8faf1f2d1f7f613446de25d8f5ad25154c7/pkg/sql/opt/xform/rules/join.opt#L122)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

When this rule constructs this InnerJoin, won't the `NormalizeInnerJoinToLeftDeep` rule kick in? This means that all the variants we generate can only have a left-deep tree as the right child of the root no?
</blockquote></details>

I've tentatively removed that rule, so not an issue anymore, but I don't quite understand this point—only as the normalized expression (i.e., the first one in the group), right? And then exploration would introduce other forms?

**Review by rytaft — APPROVED** [review]
:lgtm:

Regarding how to limit explorations, it seems like you could also limit to some number of applications of the rule, right?

> Reviewed 3 of 20 files at r5, 3 of 4 files at r6, 8 of 10 files at r7, 6 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34170#-:-LX5LKCf933V-3EbIXOm:b-fhxp08)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

**Comment by justinj** [comment]
TFTRs, going to merge this for the time being to get something in, we can iterate on the strategy for its use afterward. @andy-kimball mentioned thinking we should also impose an total ordering on relational expressions too, and I think that will be important for more complex changes, but since this is in a workable state right now I'm going to save that for a future iteration.

bors r+

**Pull request merged**
