### PR TITLE
sql: use schema desc ID for OIDs in vtables

### PR DESCRIPTION
**Pull request by rafiss**
The OIDs for schemas in the information_schema and pg_catalog tables are all now the same as the descriptor ID. For virtual schemas, the IDs are hardcoded.

No release note since OIDs are not really meant to be used externally, and we've changed these in the past without fanfare.

Release note: None
Epic: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
I guess this just works, doesn't it? That's great. At first I was thinking it was bad that the virtual schemas in different databases have the same OID, but OIDs are database-scoped in pg_catalog, so it's fine, right?

Will this mean we can more or less trivially add an index on pg_namespace?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90793#-:-NFPszguCqgR0i_ukTwb:bcyahvm)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rafiss** [comment]
> OIDs are database-scoped in pg_catalog, so it's fine, right?

that was my thought as well. it should just work!

> Will this mean we can more or less trivially add an index on pg_namespace?

yeah. my motivation was to fix the perf problem i ran into in https://github.com/cockroachdb/cockroach/pull/90649

**Comment by rafiss** [comment]
bors r=ajwerner

**Pull request merged**
