### PR TITLE
sql/importer: use desc's PK ID to sort KVs by index

### LINKED ISSUE #76196: importccl: condition to push keys into PKAdder or IndexAdder is incorrect
While ingesting keys during an import, we segregate the primary key index KVs and secondary index KVs into different bulk adders. These adders are configured differently to account for the frequency with which we expect both buffers to flush during an import. Currently, we strip each KV of its indexID, and use that to check if it is a PK or secondary index, this is incorrect. If a table has undergone an `ALTER PRIMARY KEY`, the PK index may no longer have an index ID == 1.

https://github.com/cockroachdb/cockroach/blob/4623d758bdbe2cc66320353f8ce03117a5bb35c1/pkg/ccl/importccl/import_processor.go#L517-L517

Jira issue: CRDB-13022

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

Fixes: #76196.

Release justification: low-risk bug fix.

### CODE REVIEW

**Review by DarrylWong — APPROVED** [review]
Maybe someone else should also take a look but it looks good to me. Basically just using the table descriptors to figure out if it's a PK or not right? If so seems in line with what Aditya discussed with me.

**Review by adityamaru — APPROVED** [review]
Thanks!

**Comment by adityamaru** [comment]
Can close https://github.com/cockroachdb/cockroach/issues/76196 once it merges.

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
