### PR TITLE
logictestccl: make multi-region tests run in tenant mode

### LINKED ISSUE #67236: multiregionccl: multi-region and tenant test TODO list
- [ ] ADDing and changing primary regions
- [ ] different tenants with default PRIMARY REGION settings (see #67168)

### PR DESCRIPTION
**Pull request by otan**
Reconfig logic tests to start one SQL tenant per node, then enable
multi-region tests for files that pass. Some of the multi_region tests
had to be split into multi_region_zone_config as setting certain
settings do not work under multi_tenant.

Resolves #67236

The following tests are excluded:
* Excludes the import_export logictest as that relies on local storage,
  which is unavailable.
* Excludes the tpcc logictest as that fails in the optimizer layer. Will
  file a follow up issue.

Release justification: test only change

Release note: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhrVLj7A1KN8JUx19V8:-MhrVLj7A1KN8JUx19V9:bp4scxy) (no related file):*
The TestServerArgs changes look fine.  It would be nice if there wasn't so much duplication required whenever we want to set a new option in a test, but we can boil that ocean some other day.

---
___
*[pkg/sql/logictest/logic.go, line 1460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhrSptG2aSpH6DoVnHZ:-MhrSptG2aSpH6DoVnH_:b2nhoia) ([raw file](https://github.com/cockroachdb/cockroach/blob/159b5e957c6b95354adaf5e4b8a808cdc287ceb3/pkg/sql/logictest/logic.go#L1460)):*
> ```Go
> 
> 			// Prevent a logging assertion that the server ID is initialized multiple times.
> 			log.TestingClearServerIdentifiers()
> ```

TIL

**Review by arulajmani — COMMENTED** [review]
> Reviewed 10 of 13 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhrVLj7A1KN8JUx19V8:-MhyHgLGCXXCIWrwuDN9:b-6xlc5d) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

The TestServerArgs changes look fine.  It would be nice if there wasn't so much duplication required whenever we want to set a new option in a test, but we can boil that ocean some other day.
</blockquote></details>

Mostly looks good. See my comment inline, but can we enable `regional_by_row` (or a part of it) in multi-tenancy? 

---
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region, line 1086 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyGIjX3HRqC8_s1yaM:-MhyGIjX3HRqC8_s1yaN:bpooquc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d1148c134b22e4baee51519c1a978e83e4de9b5/pkg/ccl/logictestccl/testdata/logic_test/multi_region#L1086)):*
> ```
> 
> statement ok
> CREATE TABLE global_table_custom_gc_ttl () LOCALITY GLOBAL;
> ```

Should we be able to turn the `sql.zone_configs.experimental_allow_for_secondary_tenant.enabled` setting on and bring this test back into this file? 

Edit: Maybe the file you've moved  them to (`multi_region_zone_config`) is where this should've been written in to begin with. Feel free to disregard. 
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region, line 1301 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyGZqRB1My37u_JQ51:-MhyGZqRB1My37u_JQ52:bs8jjxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d1148c134b22e4baee51519c1a978e83e4de9b5/pkg/ccl/logictestccl/testdata/logic_test/multi_region#L1301)):*
> ```
> 
> statement ok
> CREATE DATABASE gc_ttl_predefined_db
> ```

Same comment as above. 
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_tpcc, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyFulwAqf2ayTb4oIW:-MhyFulwAqf2ayTb4oIX:biz1trs) ([raw file](https://github.com/cockroachdb/cockroach/blob/92e6db9acee77ac19b6165012d8e0fb1a53c9876/pkg/ccl/logictestccl/testdata/logic_test/multi_region_tpcc#L249)):*
> ```
>                       label: buffer 1
> 
> # Regression test for #62269. Ensure that locality optimized search results in
> ```

I'm not sure that this is the right file to move this test in. How about creating a new`multi_region_system_tenant` file as a dumping ground? Or, alternatively, if you want to be more targeted, you could create a `multi_region_locality_optimized_search` file and put this in there? 
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyHC0u7f8fwsdz2Tuo:-MhyHC0u7f8fwsdz2Tup:b81ksq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/92e6db9acee77ac19b6165012d8e0fb1a53c9876/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L3)):*
> ```
> # LogicTest: multiregion-9node-3region-3azs multiregion-9node-3region-3azs-vec-off
> # TODO(#69265): enable multiregion-9node-3region-3azs-tenant
> ```

Does this file work if you turn `sql.zone_configs.experimental_allow_for_secondary_tenant.enabled` on? The issue you reference here is specific to locality optimized search -- maybe we could move targeted tests out of this file instead of disabling the whole thing?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @stevendanna)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region, line 1086 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyGIjX3HRqC8_s1yaM:-Mhz16K_A8VIuBRf_H-w:bq9lqlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d1148c134b22e4baee51519c1a978e83e4de9b5/pkg/ccl/logictestccl/testdata/logic_test/multi_region#L1086)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we be able to turn the `sql.zone_configs.experimental_allow_for_secondary_tenant.enabled` setting on and bring this test back into this file? 

Edit: Maybe the file you've moved  them to (`multi_region_zone_config`) is where this should've been written in to begin with. Feel free to disregard. 
</blockquote></details>

boundaries are abstract :) i think they belong there anyway
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region, line 1301 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyGZqRB1My37u_JQ51:-Mhz19_OAcHk6G3eLIAC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d1148c134b22e4baee51519c1a978e83e4de9b5/pkg/ccl/logictestccl/testdata/logic_test/multi_region#L1301)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same comment as above. 
</blockquote></details>

Done.
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_tpcc, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyFulwAqf2ayTb4oIW:-Mhz1Ad51aWC2XnyGe4f:b-ls46r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/92e6db9acee77ac19b6165012d8e0fb1a53c9876/pkg/ccl/logictestccl/testdata/logic_test/multi_region_tpcc#L249)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'm not sure that this is the right file to move this test in. How about creating a new`multi_region_system_tenant` file as a dumping ground? Or, alternatively, if you want to be more targeted, you could create a `multi_region_locality_optimized_search` file and put this in there? 
</blockquote></details>

i think it is. it's using a tpcc style table, and this file exclusively tests optimiser things anyway.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyHC0u7f8fwsdz2Tuo:-MhzBZL4EOgW2OX263Wo:bb7lgjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/92e6db9acee77ac19b6165012d8e0fb1a53c9876/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L3)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Does this file work if you turn `sql.zone_configs.experimental_allow_for_secondary_tenant.enabled` on? The issue you reference here is specific to locality optimized search -- maybe we could move targeted tests out of this file instead of disabling the whole thing?
</blockquote></details>

nope
___
*[pkg/sql/logictest/logic.go, line 1460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhrSptG2aSpH6DoVnHZ:-Mhz1F8F8Mek_jXEiyTa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/159b5e957c6b95354adaf5e4b8a808cdc287ceb3/pkg/sql/logictest/logic.go#L1460)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

TIL
</blockquote></details>

Done.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @stevendanna)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region, line 1086 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyGIjX3HRqC8_s1yaM:-Mi1zR7a-IMg1vDe7HHR:bs51s3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d1148c134b22e4baee51519c1a978e83e4de9b5/pkg/ccl/logictestccl/testdata/logic_test/multi_region#L1086)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

boundaries are abstract :) i think they belong there anyway
</blockquote></details>

I agree. I think it's better placeed there as well. 
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_tpcc, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyFulwAqf2ayTb4oIW:-Mi1zL0y7uxAV8j8OhHU:bb8mit5) ([raw file](https://github.com/cockroachdb/cockroach/blob/92e6db9acee77ac19b6165012d8e0fb1a53c9876/pkg/ccl/logictestccl/testdata/logic_test/multi_region_tpcc#L249)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think it is. it's using a tpcc style table, and this file exclusively tests optimiser things anyway.
</blockquote></details>

I don't think "promos" is a tpcc table, is it? 
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyHC0u7f8fwsdz2Tuo:-Mi1yzD58hEDoCdUhY7V:b-qhtwb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/92e6db9acee77ac19b6165012d8e0fb1a53c9876/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L3)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nope
</blockquote></details>

Briefly looking at this file everything except for the optimizer plans that assert locality optimized search should work. Would you mind filing an issue with whatever else about `REGIONAL BY ROW` tables doesn't work for tenants?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @otan, and @stevendanna)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyHC0u7f8fwsdz2Tuo:-Mi4-MF14J8gLZ0VTkIB:b-4v2xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/92e6db9acee77ac19b6165012d8e0fb1a53c9876/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L3)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Briefly looking at this file everything except for the optimizer plans that assert locality optimized search should work. Would you mind filing an issue with whatever else about `REGIONAL BY ROW` tables doesn't work for tenants? 
</blockquote></details>

that was a pain, but done! see second commit.
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_tpcc, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyFulwAqf2ayTb4oIW:-Mi4-JxS1FEI8lFN9A_H:b-inuql5) ([raw file](https://github.com/cockroachdb/cockroach/blob/92e6db9acee77ac19b6165012d8e0fb1a53c9876/pkg/ccl/logictestccl/testdata/logic_test/multi_region_tpcc#L249)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't think "promos" is a tpcc table, is it? 
</blockquote></details>

/shrug renamed to `query_behavior`

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-:-Mi6zIXz7YGkehycp7kp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @otan, and @stevendanna)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69267#-MhyHC0u7f8fwsdz2Tuo:-Mi6ye7y-SbnSOe1G15F:b-q21ywd) ([raw file](https://github.com/cockroachdb/cockroach/blob/92e6db9acee77ac19b6165012d8e0fb1a53c9876/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L3)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

that was a pain, but done! see second commit.
</blockquote></details>

Yeah, thanks for making the change. I'm glad we're running our non-locality optimized search tests for multiple tenants. It'll also make it easier when we swap out the `SystemConfigSpan` in the optimizer as all the explain tests are in one place now!

**Comment by otan** [comment]
bors r=arulajmani

**Comment by otan** [comment]
bors r=arulajmani

**Comment by otan** [comment]
bors r=arulajmani

**Pull request merged**
