### PR TITLE
support SHOW SCHEMAS WITH COMMENT

### LINKED ISSUE #126010: add SHOW SCHEMAS WITH COMMENT
**Is your feature request related to a problem? Please describe.**
Currently we do not have a `SHOW SCHEMAS WITH COMMENT` statement and this is inconsistent with `SHOW TABLES WITH COMMENT` and `SHOW DATABASES WITH COMMENT`.

**Describe the solution you'd like**
Make it work similar to show tables with comment:
```
demo@127.0.0.1:26257/demoapp/movr> show tables with comment;                                                                                                                                                                                       
  schema_name |         table_name         | type  | owner | estimated_row_count | locality |   comment
--------------+----------------------------+-------+-------+---------------------+----------+---------------
  public      | promo_codes                | table | demo  |                1000 | NULL     |
  public      | rides                      | table | demo  |                 500 | NULL     |
  public      | roach_table                | table | demo  |                   0 | NULL     | test-comment
  public      | user_promo_codes           | table | demo  |                   5 | NULL     |
  public      | users                      | table | demo  |                  50 | NULL     |
  public      | vehicle_location_histories | table | demo  |                1000 | NULL     |
  public      | vehicles                   | table | demo  |                  15 | NULL     |
(7 rows)

Time: 42ms total (execution 42ms / network 0ms)
```

Jira issue: CRDB-39725

### PR DESCRIPTION
**Pull request by pranavshenoy**
Previously `SHOW SCHEMAS WITH COMMENT` and
`SHOW SCHEMAS FROM databasename WITH COMMENT` were missing
for show schemas, this is inconsistent with show databases
and show tables.  The code changes in this PR make show schemas
work similar to show tables and show databases.

Fixes: https://github.com/cockroachdb/cockroach/issues/126010
Release note (sql change): Added `SHOW SCHEMAS WITH COMMENT`
and `SHOW SCHEMAS FROM databasename WITH COMMENT` functionality
similar to show tables and show databases.

**OUTPUT:**
Screenshot 2024-07-28 at 3 52 49 PM

### CODE REVIEW

**Comment by Dedej-Bergin** [comment]
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-O3-LHNo6EMQKLb1R0Y-):*
Thanks for your code changes @pranavshenoy , this is the format that we use for our commit messages: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#GitCommitMessages-Committitle

I went ahead and updated your commit message since it only took a minute. In the future if the above format/guidelines is followed it can help get your PR approved faster.

**Review by Dedej-Bergin — CHANGES_REQUESTED** [review]
Thanks for your code changes @pranavshenoy ! They look good, I just have a few minor comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-:-O3-Q8c-8-ccEDudE-x8:bh0yg5w)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pranavshenoy)

___
*[`pkg/sql/parser/sql.y` line 9059 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-O3-PCAT1CCjnp9UCclp:-O3-PCAT1CCjnp9UCclq:b-64gbup) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb18b9b0aac8aa3b4f18a76b34a28811e2982b8/pkg/sql/parser/sql.y#L9059)):*
> ```Yacc
> // %Text: SHOW SCHEMAS [FROM <databasename> ] [WITH COMMENT]
> show_schemas_stmt:
>   SHOW SCHEMAS FROM name with_comment
> ```

We need to add a parser test for these new statements.  Here is an example of a parser test added for another parser/sql.y newly added statement.  If it is too much of a hassle I'll add the parser test for you tomorrow, but we cannot approve these code changes without the parser tests.

**Comment by pranavshenoy** [comment]
> _[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-O3-LHNo6EMQKLb1R0Y-):_ Thanks for your code changes @pranavshenoy , this is the format that we use for our commit messages: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#GitCommitMessages-Committitle
> 
> I went ahead and updated your commit message since it only took a minute. In the future if the above format/guidelines is followed it can help get your PR approved faster.

Thanks @Dedej-Bergin . Will make the changes

**Comment by pranavshenoy** [comment]
@Dedej-Bergin  have added the the tests in /comment and in /show. Let me know if there are anything else to be done for this PR. 

Thanks for reviewing the PR. 😄

**Comment by Dedej-Bergin** [comment]
Screenshot 2024-07-29 at 10 07 43 PM
There was this failing test case I saw earlier for check_generated_code... if it still gives an error you can run ./dev gen or ./dev generate and it will generate some files for you... git add the files and push them on here. If it's still failing by tomorrow I can run ./dev gen on my side to fix it. Thank you!

**Comment by pranavshenoy** [comment]
> Screenshot 2024-07-29 at 10 07 43 PM There was this failing test case I saw earlier for check_generated_code... if it still gives an error you can run ./dev gen or ./dev generate and it will generate some files for you... git add the files and push them on here. If it's still failing by tomorrow I can run ./dev gen on my side to fix it. Thank you!

ok

**Comment by pranavshenoy** [comment]
@Dedej-Bergin seeing a syntax error  in the parser test. Not sure what am I doing wrong. 

`    parse_test.go:61: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/parser/parser_test_/parser_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/parser/testdata/comment:107
        unexpected error when reparsing without literals: at or near "_": syntax error
        (1) source SQL:
          | COMMENT ON SCHEMA foo IS _
          |                          ^
        Wraps: (2) attached stack trace
          -- stack trace:
          | github.com/cockroachdb/cockroach/pkg/sql/parser.PopulateErrorDetails
          | 	github.com/cockroachdb/cockroach/pkg/sql/parser/lexer.go:427
          | github.com/cockroachdb/cockroach/pkg/sql/parser.(*lexer).populateErrorDetails
          | 	github.com/cockroachdb/cockroach/pkg/sql/parser/lexer.go:450
          | [...repeated from below...]
        Wraps: (3) at or near "_"
        Wraps: (4) candidate pg code: 42601
        Wraps: (5) attached stack trace
`

https://mesolite.cluster.engflow.com/invocations/default/907579c8-ba25-4b78-97e8-9ab370a4bfd7

**Review by Dedej-Bergin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127816)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @DarrylWong, @dt, @kyle-a-wong, @nameisbhaskar, and @pranavshenoy)

___
*[`pkg/sql/delegate/show_schemas.go` line 31 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-O33CGUt7_lgHqyRiyT8:-O33CGUt7_lgHqyRiyT9:b-y4rsbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4704688351ed82a0d6b75bb31a871bc472289914/pkg/sql/delegate/show_schemas.go#L31)):*
> ```Go
> 		return nil, err
> 	}
> 	getSchemasQuery := `SELECT nspname AS schema_name, rolname AS owner`
> ```

This is great! Thanks for your contribution!

As a cleanup could you have the delegateShowSchemas method look like this:



_Code snippet:_
```Go
func (d *delegator) delegateShowSchemas(n *tree.ShowSchemas) (tree.Statement, error) {
	name, err := d.getSpecifiedOrCurrentDatabase(n.Database)
	if err != nil {
		return nil, err
	}

	commentColumn, commentJoin := ``, ``

	if n.WithComment {
		commentColumn = `, comment`

		commentJoin = fmt.Sprintf(`
			LEFT JOIN
				(
					SELECT 
						object_id, type, comment
					FROM
						system.comments
					WHERE
						type = %d
				) c
			ON
				c.object_id = n.oid`, catalogkeys.SchemaCommentType)
	}

	getSchemasQuery := fmt.Sprintf(`
			SELECT n.nspname AS schema_name, r.rolname AS owner%[1]s
      FROM %[2]s.information_schema.schemata i
      INNER JOIN %[2]s.pg_catalog.pg_namespace n ON (n.nspname = i.schema_name)
      LEFT JOIN %[2]s.pg_catalog.pg_roles r ON (n.nspowner = r.oid)
			%s
      WHERE catalog_name = %s
			ORDER BY schema_name`,
		commentColumn, name.String(), commentJoin, lexbase.EscapeSQLString(string(name)),
	)

	return d.parse(getSchemasQuery)
}
```
___
*[`pkg/sql/parser/testdata/comment` line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-O33BRajAPPuX3Z6TaJ6:-O33BRajAPPuX3Z6TaJ7:b-72l31h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4704688351ed82a0d6b75bb31a871bc472289914/pkg/sql/parser/testdata/comment#L107)):*
> ```
> COMMENT ON TYPE _ IS NULL -- identifiers removed
> 
> parse
> ```

Hi @pranavshenoy it seems this is causing a test failure and I'm not sure why.  But since your syntax addition is not comment on schema, we can just remove these COMMENT ON SCHEMA foo IS 'a' and COMMENT ON SCHEMA foo is NULL tests and I can dig into why they're not working and add them in a later PR.

**Review by Dedej-Bergin — COMMENTED** [review]
I looked into it a bit and I'm not sure why. But since your syntax addition is not comment on schema, we can just remove these COMMENT ON SCHEMA foo IS 'a' and COMMENT ON SCHEMA foo is NULL tests and I can dig into why they're not working and add them in a later PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-:-O33EP7QCkC51OJ8sBF-:b-l51vlb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @DarrylWong, @dt, @kyle-a-wong, @nameisbhaskar, and @pranavshenoy)

**Comment by Dedej-Bergin** [comment]
To fix the lint failing testcase _GitHub Actions Essential CI / lint (pull_request)_ you have to run crlfmt in the bin directory.  (github.com/cockroachdb/cockroach/bin/crlfmt) Let me know if you can't get crlfmt to work I don't remember the exact flags it needs off the top of my head but I can figure them out if it's giving you trouble. Thanks

**Comment by pranavshenoy** [comment]
Sure. Thanks. Will work on these changes

**Comment by rafiss** [comment]
The guide here has more information and links about using `crlfmt`: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072641/What+is+a+Good+CockroachDB+PR

Thanks for your work on this!

**Comment by pranavshenoy** [comment]
have made all the changes  except crlfmt. Will read about it.

**Comment by pranavshenoy** [comment]
ran crlfmt

**Review by Dedej-Bergin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127816)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pranavshenoy and @rafiss)

___
*[`pkg/sql/delegate/show_schemas.go` line 15 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-O34NIf75OuToZLvTl1U:-O34NIf82v3t1GDxyFs7:b7fyqsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/16a2870386f4bfbf0724f61b87b5752d8c51b81d/pkg/sql/delegate/show_schemas.go#L15)):*
> ```Go
> import (
> 	"fmt"
> 	"github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkeys"
> ```

The lint test is still failing, it looks like the whole problem is the spacing here. The imports should look like this:



_Code snippet:_
```Go
import (
	"fmt"

	"github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkeys"
	"github.com/cockroachdb/cockroach/pkg/sql/lexbase"
	"github.com/cockroachdb/cockroach/pkg/sql/opt/cat"
	"github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
	"github.com/cockroachdb/cockroach/pkg/sql/sqltelemetry"
)
```

**Comment by pranavshenoy** [comment]
@Dedej-Bergin reran crlfmt and looks like the spacing issue is fixed.


Thanks for the help.

**Comment by pranavshenoy** [comment]
@Dedej-Bergin 
I have already signed the CLA. Not sure why its saying not signed yet. Is there anything else that I have to do in order to mark it complete?
Thanks

**Review by Dedej-Bergin — APPROVED** [review]
Great work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-:-O387lJNALT6YkCq8Pxf:b-9dwnzc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pranavshenoy and @rafiss)

**Review by Dedej-Bergin — CHANGES_REQUESTED** [review]
I forgot one thing, we need to have a test that checks that `SHOW SCHEMAS WITH COMMENT` and `SHOW SCHEMAS FROM databasename WITH COMMENT` actually shows the correct comments in the results.

We can add a logic test for this to the comment_on at this location /pkg/sql/logictest/testdata/logic_test/comment_on , underneath line 54 could be good just after adding a comment to a schema.


Something that looks like this would work, underneath the ---- we need the expected output. This output can be autogenerated for you if you run ./dev testlogic --files=comment_on --rewrite

query TTT colnames,rowsort
SHOW SCHEMAS WITH COMMENT
\----

query TTT colnames,rowsort
SHOW SCHEMAS FROM db WITH COMMENT
\----

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-:-O388iMj96UbFwTZGSj6:b-aw8h2u)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pranavshenoy and @rafiss)

**Comment by pranavshenoy** [comment]
have added the test case. Thanks for pointing it out.

**Review by Dedej-Bergin — APPROVED** [review]
Great work, thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-:-O39XXkjBNte3cBrcJ56:b-nv8j63)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pranavshenoy and @rafiss)

**Comment by pranavshenoy** [comment]
@Dedej-Bergin The CLA status is still "Pending" even though I have signed it. Is there anything I need to do to update it?
Thanks

**Review by Dedej-Bergin — COMMENTED** [review]
I think the CLA is failing because your github account email is not the same as the git commit email.
Try running this command to change the git commit email to your github email 

git commit --amend --author="Author Name <author@example.com>"




> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127816#-:-O3D3N-C62t8Rilj1-Fh:b-sdcx8b)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pranavshenoy and @rafiss)

**Comment by pranavshenoy** [comment]
> Contributor

have updated the email id. Thanks

**Comment by Dedej-Bergin** [comment]
Thanks again for your work @pranavshenoy! Hopefully this will get merged soon.

**Comment by pranavshenoy** [comment]
> Thanks again for your work @pranavshenoy! Hopefully this will get merged soon.

Thanks for all the inputs!

**Pull request merged**
