### PR TITLE
sql: add PAUSE JOB/RESUME JOB/CANCEL [JOB|QUERY] syntax skeleton

### PR DESCRIPTION
**Pull request by benesch**
Add support for `PAUSE JOB`, `RESUME JOB`, and `CANCEL [JOB|QUERY]` to the parser and planner. For now, their implementations simply return an unimplemented error, but this skeleton will allow us to implement these operations for backups/restores, schema changes, and long-running queries in parallel.

### CODE REVIEW

**Comment by benesch** [comment]
Wanted to toss this up for whichever project (backups/restores, schema changes, long-running queries) needs this first.

**Comment by jordanlewis** [comment]
Looking good!

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/operations.go, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7h84_M4Dk57fa0F0r:-Km7h84_M4Dk57fa0F0s:b-zbfj9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/parser/operations.go#L2)):*
> ```Go
> // Copyright 2017 The Cockroach Authors.
> //
> ```

naming nit: operations.go doesn't seem very clear to me - jobs.go? joboperations? jobcontrol? runcontrol? I know there's a query one as well, but nevertheless I think calling this something with 'jobs' in the filename would be clearer. I can definitely see myself checking out what is in `operations.go` since it sounds like something else.

---

*[pkg/sql/parser/sql.y, line 1098 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7jBHbpzQoNNSTPpvU:-Km7jBHcfRcH6ZG_8sMD:b-w53mxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/parser/sql.y#L1098)):*
> ```Yacc
> // CANCEL [JOB|QUERY] id
> cancel_stmt:
>   CANCEL JOB var_value
> ```

Why not allow these to be full expressions? Then we could do `CANCEL JOB (SELECT id FROM crdb_internal.jobs WHERE ...)` kinda stuff

---

*[pkg/sql/testdata/logic_test/operations, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7jif7_7j4KS0doRP6:-Km7jif7_7j4KS0doRP7:blnsns7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/testdata/logic_test/operations#L1)):*
> ```
> # LogicTest: default parallel-stmts distsql
> ```

If you decide to rename operations.go rename this too :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-:-Km7jowKpV2TZ-aKXNKU:br2sbr6)*

**Comment by itsbilal** [comment]
:lgtm: save for the naming of `operations.go`

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/operations.go, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7h84_M4Dk57fa0F0r:-Km7kOCojcKVGM-RBjiv:bpg4ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/parser/operations.go#L2)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

naming nit: operations.go doesn't seem very clear to me - jobs.go? joboperations? jobcontrol? runcontrol? I know there's a query one as well, but nevertheless I think calling this something with 'jobs' in the filename would be clearer. I can definitely see myself checking out what is in `operations.go` since it sounds like something else.
</blockquote></details>

I agree, operations.go is very generic. jobcontrol or even the pause_resume_cancel mouthful would probably be a better idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-:-Km7meANJqLsBGATfOLv:bjkz1wr)*

**Comment by benesch** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/operations.go, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7h84_M4Dk57fa0F0r:-Km7m0PPI-OHqS4jvc3j:b-xb6bix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/parser/operations.go#L2)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

naming nit: operations.go doesn't seem very clear to me - jobs.go? joboperations? jobcontrol? runcontrol? I know there's a query one as well, but nevertheless I think calling this something with 'jobs' in the filename would be clearer. I can definitely see myself checking out what is in `operations.go` since it sounds like something else.
</blockquote></details>

Yeah, `jobs` didn't seem right because that implies `system.jobs`-related stuff. `operations.go` is a bad name, though, I'll grant you that. `run_control.go` isn't bad! I'll also throw out `op_control.go` or `operation_control.go`.

---

*[pkg/sql/parser/sql.y, line 1098 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7jBHbpzQoNNSTPpvU:-Km7maRnl36ldv9KFJrT:bw4cnv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/parser/sql.y#L1098)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why not allow these to be full expressions? Then we could do `CANCEL JOB (SELECT id FROM crdb_internal.jobs WHERE ...)` kinda stuff
</blockquote></details>

Good call. Failure of imagination on my part. Though that means the most straightforward implementation would require something like `CANCEL JOB VALUES (1)`, no? I.e., assuming the production is `CANCEL JOB select_stmt`.

---

*[pkg/sql/testdata/logic_test/operations, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7jif7_7j4KS0doRP6:-Km7mqq9BBM6ja_fo-DJ:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/testdata/logic_test/operations#L1)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

If you decide to rename operations.go rename this too :)
</blockquote></details>

Ack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405)*

**Comment by jordanlewis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/operations.go, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7h84_M4Dk57fa0F0r:-Km7nnXoPt813YezSZj6:bln5dr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/parser/operations.go#L2)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, `jobs` didn't seem right because that implies `system.jobs`-related stuff. `operations.go` is a bad name, though, I'll grant you that. `run_control.go` isn't bad! I'll also throw out `op_control.go` or `operation_control.go`.
</blockquote></details>

I'm fine with either run_control or operation_control.

---

*[pkg/sql/parser/sql.y, line 1098 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7jBHbpzQoNNSTPpvU:-Km7nWnsBhetfOpiO7vA:b-ilkjcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/parser/sql.y#L1098)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Good call. Failure of imagination on my part. Though that means the most straightforward implementation would require something like `CANCEL JOB VALUES (1)`, no? I.e., assuming the production is `CANCEL JOB select_stmt`.
</blockquote></details>

Hmm I think you wouldn't want to use `select_stmt` - rather you'd want to use `a_expr` which I believe contains any normal expression as well as subqueries like (SELECT id from ..)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405)*

**Comment by benesch** [comment]
PTAL!

Also, is there anyone else who should review this?

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/parser/run_control.go, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7h84_M4Dk57fa0F0r:-Km86PJI-J7iygICIrMN:b-wtcdbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/parser/run_control.go#L2)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm fine with either run_control or operation_control.
</blockquote></details>

Went with `run_control`.

---

*[pkg/sql/parser/sql.y, line 1098 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-Km7jBHbpzQoNNSTPpvU:-Km86QvRg-FpwOZcPKaY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e65912b7840e397121feb5fe852b045cb6a5b0f/pkg/sql/parser/sql.y#L1098)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm I think you wouldn't want to use `select_stmt` - rather you'd want to use `a_expr` which I believe contains any normal expression as well as subqueries like (SELECT id from ..)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-:-Km86O3hpxSYU6m-eavB:bwdx7yx)*

**Comment by jordanlewis** [comment]
:lgtm:, @knz's feedback as always would be valuable

---

Reviewed 4 of 12 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-:-Km8URnyXEJbkGaQN8iL:b-8z5g7a)*

**Comment by knz** [comment]
I'm good with the change
but I think it is strange policy to add unused code in the product.
I simply do not understand the wisdom of merging this change now before the first step of the implementation is done. You could have left a branch open for someone to pick up as a foundation when the functional commit is ready to go to.
If this were the norm I also have a plethora of embryos for features I plan to add later. Would you, imagine, want to see all my burgeoning but yet immature excrescences all over the place when you're reading code?

---

Reviewed 4 of 12 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-:-KmE778f0ATFF6-PlLsE:b-pwvon4)*

**Comment by jordanlewis** [comment]
For one it reduces the burden of reviewing! Personally, I welcome PRs like this - they're easy to review and I know that next time someone will get to build on this foundation rather than do it all from scratch and force a larger review at that point.

**Comment by knz** [comment]
This argument doesn't hold water for me either. Reviewable allows you to review a PR commit by commit. That's the entire point of splitting a larger change into multiple sub-commits that each address a small part. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-:-KmGDiIakEEIVjDt0F--:b-scqeyu)*

**Comment by petermattis** [comment]
I find smaller PRs reduce the burden of reviewing for the reviewer and the burden of addressing comments for the author. Yeah, reviewable does allow you to review commit by commit, but don't you find that a super large commit eventually becomes overwhelming? Or is that just me?

The big challenge with multiple PRs is understanding where the author is headed, but in this case it is obvious given the recent RFC and the functionality being introduced.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16405#-:-KmHo2bFf3cV0xfSfd7n:b-9gyhcb)*

**Comment by benesch** [comment]
The benefit for the submitter is preventing code rot. Rebases get far more difficult as the number of commits in the PR increases. As expected, this is already conflicting with `pkg/sql/parser/sql.go`.

I was hesitant to call this change mergeable—it is _awfully_ small—and you can see my brief flirtation with the `do-not-merge` label up at the top of the activity log. I don't have strong feelings on whether this particular PR merges as-is or hangs out until @jordanlewis, @itsbilal, or I build on top of it.

**Comment by vivekmenezes** [comment]
I feel it is better for this PR to merge given that it is backed by an RFC.
I agree that we've had an unofficial policy of merging many commits
together that produce a working implementation for a feature, but I think
the RFC provides the documentation for this PR. It allows folks to work
independently on the same RFC.

Thanks

**Comment by knz** [comment]
Well then do not let me get in the way.
I'll remember this lesson next time I start working on a large-ish project.

**Comment by knz** [comment]
Please however add the "/* SKIP DOC */" marker on the grammar rules until the corresponding features are implemented.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
