### PR TITLE
 sql: only create real spans when session tracing/sampling

### LINKED ISSUE #59424: roachtest: tpccbench/nodes=3/cpu=16 failed
[(roachtest).tpccbench/nodes=3/cpu=16 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2615395&tab=buildLog) on [master@d86781c07065421f4a4d8bf5d988900ab07fdce5](https://github.com/cockroachdb/cockroach/commits/d86781c07065421f4a4d8bf5d988900ab07fdce5):

```
		Error types: (1) *main.withCommandDetails (2) *exec.ExitError

	cluster.go:1666,context.go:140,cluster.go:1655,test_runner.go:848: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2615395-1611644173-19-n4cpu16 --oneshot --ignore-empty-nodes: exit status 1 4: skipped
		3: dead
		2: dead
		1: 12227
		Error: UNCLASSIFIED_PROBLEM: 3: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) secondary error attachment
		  | 2: dead
		  | (1) attached stack trace
		  |   -- stack trace:
		  |   | main.glob..func14
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  |   | main.wrap.func1
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  |   | github.com/spf13/cobra.(*Command).execute
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  |   | github.com/spf13/cobra.(*Command).ExecuteC
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  |   | github.com/spf13/cobra.(*Command).Execute
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  |   | main.main
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1852
		  |   | runtime.main
		  |   | 	/usr/local/go/src/runtime/proc.go:204
		  |   | runtime.goexit
		  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		  | Wraps: (2) 2: dead
		  | Error types: (1) *withstack.withStack (2) *errutil.leafError
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1852
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (4) 3: dead
		Error types: (1) errors.Unclassified (2) *secondary.withSecondaryError (3) *withstack.withStack (4) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/tpccbench/nodes=3/cpu=16](https://teamcity.cockroachdb.com/viewLog.html?buildId=2615395&tab=artifacts#/tpccbench/nodes=3/cpu=16)
Related:
- #55802 roachtest: tpccbench/nodes=3/cpu=16 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [T-bulkio](https://api.github.com/repos/cockroachdb/cockroach/labels/T-bulkio) [branch-release-20.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.1)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpccbench%2Fnodes%3D3%2Fcpu%3D16.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by irfansharif**
This drastically reduces the memory overhead for tracing we're observing
in #59424. This commit does a few disparate things to make it happen:

1. We now access the tracing span through txnState.Ctx exclusively. This
   gives us a single point to hijack, which we'll later do. By default
   txn's are initialized with a no-op span. If later on session tracing is
   enabled, we'll create a real (verbose) span and swap it out with the
   txn's no-op one. This gives us the same semantics as earlier, and on the
   plus side, we're not re-using the same tracing span when session tracing
   is toggled.
2. Hard tracing methods to work with no-op spans. Specifically
   GetRecording and TraceID.
3. Remove a crash vector through crdb_internal.trace_id. It was
   previously reaching into the first recording to retrieve a trace ID. But
   it's not guaranteed that recordings are non-empty. This could be used to
   induce panics in the server.

This PR will need to get backported to 21.1. Fixes #59424.

Release note: None

---

+cc @cockroachdb/kv-east.

### CODE REVIEW

**Comment by asubiotto** [comment]
Looking just at the `testrace` failure. Looks like it's hitting a testing assertion:
```
panic: unhandled field in local meta or all fields are nil

goroutine 516368 [running]:
github.com/cockroachdb/cockroach/pkg/sql/execinfrapb.LocalMetaToRemoteProducerMeta(0x7fb4fe0, 0xc0c7050750, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/data.go:317 +0x5d9
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).sendMetadata(0xc0b69d5860, 0x7fb4fe0, 0xc0c7050750, 0x7f8a255f57d0, 0xc0b1784e40, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:312 +0x3be
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).runWithStream(0xc0b69d5860, 0x7fb4fe0, 0xc0c7050750, 0x7f8a255f57d0, 0xc0b1784e40, 0xc0b3605bf0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:351 +0x18d
github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Outbox).Run(0xc0b69d5860, 0x7fb4f20, 0xc0a1c60dc0, 0x7f1ad40, 0xc0b72fd620, 0x88c8b94d00000001, 0x8c0168ba99459d87, 0xce1e8947, 0xd, 0xc0b3605bf0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/outbox.go:194 +0x431
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRemoteOutputStream.func1(0x7fb4f20, 0xc0a1c60dc0, 0xc0b36056f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:663 +0x255
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1(0xc0c70504e0, 0x7fb4f20, 0xc0a1c601c0, 0xc0b36056f0, 0xc0b5b69520)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1291 +0x52
created by github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1290 +0x87
```

My first guess is that a `ProducerMetadata` object is created somewhere and  a component tries to set the `TraceData` field with the assumption that that will be non-nil but your change breaks that assumption.

**Comment by irfansharif** [comment]
Heh, I saw your comment too late. I was just about to ask for your (or @yuzefovich's) second pair of eyes. I don't think the colflow outbox code correctly deals with the possibility that the span available to it is a no-op one.

https://github.com/cockroachdb/cockroach/pull/61777/files#diff-d71b6d7d7e13687ca705600b9ecb837ed0f445f80ceb78a8b939504e0d6caa36R757-R763

What do you suppose should be done? Does it make sense to force real span creation at outboxes? I suppose not, which is exactly the behavior #61380 looks to change.

**Comment by irfansharif** [comment]
https://github.com/cockroachdb/cockroach/blob/70dd87782c64e855150352a7506425b97c818ad2/pkg/sql/flowinfra/outbox.go#L310-L316

This fellow?

**Comment by irfansharif** [comment]
https://github.com/cockroachdb/cockroach/blob/70dd87782c64e855150352a7506425b97c818ad2/pkg/sql/execinfrapb/data.go#L254-L255

Is where the empty TraceData is being set.

**Comment by irfansharif** [comment]
Looks like we were willing to propagate empty traces before. We'll need the following diff, I think:

```diff
diff --git a/pkg/sql/colflow/colrpc/outbox.go b/pkg/sql/colflow/colrpc/outbox.go
index f9395956b0..b97d494943 100644
--- a/pkg/sql/colflow/colrpc/outbox.go
+++ b/pkg/sql/colflow/colrpc/outbox.go
@@ -298,7 +298,7 @@ func (o *Outbox) sendMetadata(ctx context.Context, stream flowStreamClient, errT
                        o.span.RecordStructured(s)
                }
        }
-       if trace := execinfra.GetTraceData(ctx); trace != nil {
+       if trace := execinfra.GetTraceData(ctx); trace != nil && len(trace) != 0 {
                msg.Data.Metadata = append(msg.Data.Metadata, execinfrapb.RemoteProducerMetadata{
                        Value: &execinfrapb.RemoteProducerMetadata_TraceData_{
                                TraceData: &execinfrapb.RemoteProducerMetadata_TraceData{
```

**Comment by yuzefovich** [comment]
>  I don't think the colflow outbox code correctly deals with the possibility that the span available to it is a no-op one.

I'm not sure what to say here yet, but I'd encourage you to take a look at modifying `execinfra.ProcessorSpan` and `execinfra.GetTraceData` methods rather than adjusting different components (like `colrpc.Outbox`) in isolation since those methods are used by *most* components in the execution flows (the exception is `ProcessorBase.moveToTrailingMeta` where we call `GetRecording` explicitly).

> What do you suppose should be done? Does it make sense to force real span creation at outboxes? I suppose not, which is exactly the behavior #61380 looks to change.

Also I'm not quite sure how remote child spans deal interact with root spans, but I imagine we do need to have "real" spans in the outboxes when the execution stats are being collected. Yeah, #61380 was trying to avoid doing that but also to fix the misuse of the API (where we started and stopped spans only for the purposes of the stats propagation). Overall, I think I might not have the right terminology and understanding of the impact here, possibly Alfonso will have some suggestions/clarifications.

**Comment by irfansharif** [comment]
This should now be ready for a real look. It's  surprisingly small diff, but it was a bit unwieldy to get right (most of sql is unfamiliar to me). Given we're hoping to backport this to release-21.1, we should give this a close look and maybe let it bake for a few days.

**Review by tbg — COMMENTED** [review]
Looks good to me, but I'm not an expert on the SQL so my LGTM is really just for the tracing package changes.

> Reviewed 1 of 1 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-:-MVbA_Il2-m5jdsiw3IQ:b-jukpff)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @yuzefovich)

___
*[pkg/sql/exec_util.go, line 1656 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbTkts782nlK-DnVd1:-MVbTkts782nlK-DnVd2:bnd1fwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f278b1fdbd16dc5a9626edd6c65e67ece4b967de/pkg/sql/exec_util.go#L1656)):*
> ```Go
> 			"session tracing", tracing.WithForceRealSpan())
> 		sp.SetVerbose(true)
> 		st.ex.state.Ctx = newTxnCtx
> ```

Does it make sense to use a `ctxHolder` here instead of overwriting the ctx directly?
___
*[pkg/sql/instrumentation.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbQdqLA9JG9ESBdDLO:-MVbQdqLA9JG9ESBdDLP:bh90z6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/be5014148ecb7bd9b78072a7df8151f242444aea/pkg/sql/instrumentation.go#L171)):*
> ```Go
> 	if sp := tracing.SpanFromContext(ctx); sp != nil {
> 		ih.sp = sp
> 		ih.finishSpan = false
> ```

I don't think we want to remove `finishSpan` here. cc @yuzefovich. The case I'm thinking about specifically is when statement tracing threshold is enabled. A span is created at a higher level so the instrumentation helper should not Finish it, but it is still worth it to get the span's recording and record the stats. We should probably add a regression test for this case to `instrumentation_test.go`
___
*[pkg/sql/logictest/testdata/logic_test/contention_event, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbUCFy7ovmBhmlKWgE:-MVbUCFy7ovmBhmlKWgF:b-mkp5wo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f278b1fdbd16dc5a9626edd6c65e67ece4b967de/pkg/sql/logictest/testdata/logic_test/contention_event#L30)):*
> ```
> 
> statement ok
> SET TRACING = on
> ```

This is more of a macro question but I thought that the idea of the background tracing work was that we would always have some sort of tracing enabled, so having to turn on session tracing to get contention events feels wrong. How should I think about this?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @irfansharif)

___
*[pkg/sql/instrumentation.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbQdqLA9JG9ESBdDLO:-MVbbogqDzZpi5Ry8N8r:b-rc6z9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/be5014148ecb7bd9b78072a7df8151f242444aea/pkg/sql/instrumentation.go#L171)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think we want to remove `finishSpan` here. cc @yuzefovich. The case I'm thinking about specifically is when statement tracing threshold is enabled. A span is created at a higher level so the instrumentation helper should not Finish it, but it is still worth it to get the span's recording and record the stats. We should probably add a regression test for this case to `instrumentation_test.go`
</blockquote></details>

Note that the first commit is the revert of #61532 which introduced `finishSpan`.

AFAICT the only remaining piece from that PR is few changes in `execCmd`. The revert looks good to me, but I wonder why  you chose to do a "by-hand" revert?

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/exec_util.go, line 1656 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbTkts782nlK-DnVd1:-MVbfy0p8FhfPLt1omko:bsv28iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f278b1fdbd16dc5a9626edd6c65e67ece4b967de/pkg/sql/exec_util.go#L1656)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does it make sense to use a `ctxHolder` here instead of overwriting the ctx directly?
</blockquote></details>

Originally I didn't want to avoid a larger diff than necessary, but meh, done. PTAL.
___
*[pkg/sql/instrumentation.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbQdqLA9JG9ESBdDLO:-MVbdB233Vgi1wk4-kpR:bsm7w45) ([raw file](https://github.com/cockroachdb/cockroach/blob/be5014148ecb7bd9b78072a7df8151f242444aea/pkg/sql/instrumentation.go#L171)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Note that the first commit is the revert of #61532 which introduced `finishSpan`.

AFAICT the only remaining piece from that PR is few changes in `execCmd`. The revert looks good to me, but I wonder why  you chose to do a "by-hand" revert?
</blockquote></details>

I probably caused more confusion than deserved. I wanted to keep the comments introduced in that commit, everything else was mechanical. So if I'm reading everything correctly, I don't think there's any thing to do with this review thread?
___
*[pkg/sql/logictest/testdata/logic_test/contention_event, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbUCFy7ovmBhmlKWgE:-MVbg4bSAjVd_5F8L53h:blxac6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f278b1fdbd16dc5a9626edd6c65e67ece4b967de/pkg/sql/logictest/testdata/logic_test/contention_event#L30)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This is more of a macro question but I thought that the idea of the background tracing work was that we would always have some sort of tracing enabled, so having to turn on session tracing to get contention events feels wrong. How should I think about this?
</blockquote></details>

The way to think about it now is that we'll only get contention events for sampled statements/txns. The `sql.txn_stats.sample_rate` knob lets us traverse a spectrum of going between "always on tracing" as you're thinking of it, and "always off". For these tests SET TRACING = on is effectively doing the same thing as `sql.txn_stats.sample_rate = 1.0`

**Comment by irfansharif** [comment]
https://www.githubstatus.com Github is down, and my latest fixups aren't showing up in this PR.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/instrumentation.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbQdqLA9JG9ESBdDLO:-MVbjA9i36l9v_lGC4Qz:btarxkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/be5014148ecb7bd9b78072a7df8151f242444aea/pkg/sql/instrumentation.go#L171)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I probably caused more confusion than deserved. I wanted to keep the comments introduced in that commit, everything else was mechanical. So if I'm reading everything correctly, I don't think there's any thing to do with this review thread?
</blockquote></details>

Yeah, I think the only thing that might be worth doing is explicitly mentioning the desire to keep the comments in the revert commit message.

**Comment by irfansharif** [comment]
> @blathers-crl blathers-crl bot added the O-community label

Did I get fired?

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 11 of 11 files at r3, 11 of 11 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-:-MVc-NBpCG3h8h9T17D8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/sql/instrumentation.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbQdqLA9JG9ESBdDLO:-MVbzoLi7sErpYQ_qCvT:b-p5hd78) ([raw file](https://github.com/cockroachdb/cockroach/blob/be5014148ecb7bd9b78072a7df8151f242444aea/pkg/sql/instrumentation.go#L171)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I probably caused more confusion than deserved. I wanted to keep the comments introduced in that commit, everything else was mechanical. So if I'm reading everything correctly, I don't think there's any thing to do with this review thread?
</blockquote></details>

OK. So we should re-introduce finish span in another PR.
___
*[pkg/sql/logictest/testdata/logic_test/contention_event, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbUCFy7ovmBhmlKWgE:-MVbzyjm-OuzzWOnFl_c:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f278b1fdbd16dc5a9626edd6c65e67ece4b967de/pkg/sql/logictest/testdata/logic_test/contention_event#L30)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

The way to think about it now is that we'll only get contention events for sampled statements/txns. The `sql.txn_stats.sample_rate` knob lets us traverse a spectrum of going between "always on tracing" as you're thinking of it, and "always off". For these tests SET TRACING = on is effectively doing the same thing as `sql.txn_stats.sample_rate = 1.0`
</blockquote></details>

:+1:

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61777)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/sql/instrumentation.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbQdqLA9JG9ESBdDLO:-MVbjA9i36l9v_lGC4Qz:b-oy3e03) ([raw file](https://github.com/cockroachdb/cockroach/blob/be5014148ecb7bd9b78072a7df8151f242444aea/pkg/sql/instrumentation.go#L171)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

OK. So we should re-introduce finish span in another PR.
</blockquote></details>

Yeah, I think the only thing that might be worth doing is explicitly mentioning the desire to keep the comments in the revert commit message.

Alfonso, which "finish span" are you thinking about? `finishSpan` boolean was introduced in #61532 only because `ih.sp` could be of two flavours - the txn span (which we don't want to finish) and and the sampling span (which we explicitly created in `Setup` and want to finish).

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61777)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/sql/instrumentation.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbQdqLA9JG9ESBdDLO:-MVcCnu94FbKixp7GIiO:b2dmzj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/be5014148ecb7bd9b78072a7df8151f242444aea/pkg/sql/instrumentation.go#L171)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, I think the only thing that might be worth doing is explicitly mentioning the desire to keep the comments in the revert commit message.

Alfonso, which "finish span" are you thinking about? `finishSpan` boolean was introduced in #61532 only because `ih.sp` could be of two flavours - the txn span (which we don't want to finish) and and the sampling span (which we explicitly created in `Setup` and want to finish).
</blockquote></details>

Right, and I think we still have a case where we want to collect stats from a higher level span without finishing it. Concretely, when tracing is enabled for the statement or txn threshold cases. So in the if statement below, we want to set `ih.sp`, return `needsFinish=true` but set `finishSpan=false`. Does that make sense? I feel like all this state can probably be simplified.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61777)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/sql/instrumentation.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-MVbQdqLA9JG9ESBdDLO:-MVcDy27516SVUg3ky2l:b-5hy91m) ([raw file](https://github.com/cockroachdb/cockroach/blob/be5014148ecb7bd9b78072a7df8151f242444aea/pkg/sql/instrumentation.go#L171)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Right, and I think we still have a case where we want to collect stats from a higher level span without finishing it. Concretely, when tracing is enabled for the statement or txn threshold cases. So in the if statement below, we want to set `ih.sp`, return `needsFinish=true` but set `finishSpan=false`. Does that make sense? I feel like all this state can probably be simplified.
</blockquote></details>

I see, yeah, it makes sense, but that would be a new behavior, so I think it is orthogonal to the revert commit and the main commit of this PR.

**Review by irfansharif — COMMENTED** [review]
Looks like the txnState's Ctx lifetime is such that it's cleaned up before SessionTracing is. Specifically, we `finishSQLTxn` before we `StopTracing`:

https://github.com/cockroachdb/cockroach/blob/1b6c7f9ea0b976dbfd4d9c1f1b6bd97c0fb27dc3/pkg/sql/conn_executor.go#L832

https://github.com/cockroachdb/cockroach/blob/1b6c7f9ea0b976dbfd4d9c1f1b6bd97c0fb27dc3/pkg/sql/conn_executor.go#L882-L884 

> Does it make sense to use a ctxHolder here instead of overwriting the ctx directly?

The above makes this unwieldy. Yes, ideally we'd like to "unhijack" the context we just injected. But given it's cleaned up before we get to it, we won't have anything to clean up. This isn't try for the other usage of ctxHolder, where its lifetime is tied only to SessionTracer. For that reason, I'll keep things as was before and hijack Ctx directly instead of doing it through a ctxHolder. In the future, we can probably clean up the SessionTracer's lifecycle before we `finishSQLTxn`. When we do so, we can start using a ctxHolder instead. I'm not doing that in this PR to keep the blast radius as small as possible.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61777#-:-MVcxO1uAchD1ov7k9lG:bsi8ppr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

**Comment by irfansharif** [comment]
Github statuses are being goofy, and bors is confused.

bors r+

**Pull request merged**
