### PR TITLE
sql,jobs: add an empty type change job resumer

### PR DESCRIPTION
**Pull request by rohany**
This PR adds an empty type change job resumer. This resumer will be used
to manage changes on types, and will mimic the structure of the schema
change resumer. Here we just add plumbing and register this resumer so
that future work on the resumer doesn't need to do this as well.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I think I'm cool with this approach but I sort of want to understand our end-game a bit better. In practice isn't this just another one of those jobs that waits for a version then writes another version?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50104#-:-M9ZI4BX4nAVJ5DuSC9u:b-mhtwga)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

**Review by ajwerner — COMMENTED** [review]
The main thing I want to think about is how this sort of schema change will ultimately interact with transactions when, in the next version, we try to realize this transactional schema change vision such that you could use the new enum type in the transaction that adds it. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50104#-:-M9ZIJ2W2KLZHybQJZT_:b-royvzl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Comment by rohany** [comment]
> isn't this just another one of those jobs that waits for a version then writes another version?

Yeah. I'm planning on it to mirror the `SchemaChanger`, so it'll handle namespace draining (for rename + drop), descriptor cleanup (for drop), version waiting for ad hoc changes, and the mini state machine for enum value additions.

**Comment by rohany** [comment]
Going to close this and open a new PR with more stuff

**Pull request closed without merging**
