### PR TITLE
sql: refactor SynthesizeRegionConfig usages

### PR DESCRIPTION
**Pull request by otan**
Use the option method instead to decide to read from the cache.

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
This may break the following (contrived) scenario:

- Client 1: ALTER DATABASE ... DROP REGION "us-east"
- Client 2: CREATE TABLE t() LOCALITY REGIONAL BY ROW
- Client 3, which (say) has version v-1 of the type descriptor, `validate_multi_region_zone_configs()` <--- Fails because it expects t to have a partition for "us-east"

This is because on version v-1 "us-east" is public, so we'll validate for it. Granted, this is quite contrived, but maybe one round-trip is a fair enough price to pay here for our sanity? Wdyt?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63512#-:-MYHylPpDszvQBPOCMr3:bhltc70)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by otan** [comment]
I would think client 3 in this case would also have v1 of the zone config.

**Review by arulajmani — COMMENTED** [review]
Maybe I'm missing something, but aren't we reading zone configs from the system.zone table? 

Also, independent of round trip/no round trip, I like the way this PR cleans up the code so we should get it in in some form. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63512#-:-MYI1s8LAXzRdyh5Uozs:bfjyeez)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by otan** [comment]
Would've thought leasing would also mean the reads would be at an earlier timestamp when reading system.zones, but maybe I'm jumping too many hurdles. I'll revert the round-trip bit for now, but keep the refactor for SynthesizeRegionConfig

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63512#-:-MYLm-wY3g3ohBiaxxm0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/region_util.go, line 889 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63512#-MYLlwst-hs5m5sQMHFB:-MYLlwsu7eSvmTom4sQ4:b-sm7v5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aca38fab2ed4066a5bac6c5f7b601ae7b767a4a/pkg/sql/region_util.go#L889)):*
> ```Go
> // CurrentDatabaseRegionConfig is part of the tree.EvalDatabase interface.
> // CurrentDatabaseRegionConfig uses the cache to synthesize the RegionConfig
> // and as such is intended for DML use. It returns an nil
> ```

nit: s/returns an nil/returns nil/g

**Comment by otan** [comment]
bors r=arulajmani

**Pull request merged**
