### PR TITLE
Updating required Go version in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jseldess**
Fixes https://github.com/cockroachdb/cockroach/issues/7206

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7214)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
LGTM

**Comment by tamird** [comment]
LGTM but would be good to somehow not mention the version in this document since it's really asking for rot =/

**Comment by jseldess** [comment]
@tamird, how often to we upgrade Go? If not often, I'd say we just try to flag the next time this changes and I'll make the update here, since it mean once less link for contributes to click to get themselves set up.

**Comment by tamird** [comment]
~6 times a year, I'd guess.

**Comment by bdarnell** [comment]
We could reduce the duplication a little bit by linking from CONTRIBUTING.md to the "build from source" section of the docs. 

We could also relax our go version check - we want to make sure that our release builds use the latest version, but for development any 1.6.x should be fine.

**Comment by jseldess** [comment]
I really like the idea of relaxing our go version check, if that's not a problem to do. Then, here and elsewhere, we could just use `1.6.x`, as Ben mentions, and not have to update further until we're on `1.7`. Ben, should I open another issue for that?

**Comment by tamird** [comment]
The version check was introduced to avoid "works on my machine" problems in development. I'm against relaxing it.

**Comment by jseldess** [comment]
Ah, ok. For now, I'll just merge this and expect to manually update these versions when necessary. But I like the idea of redirecting people from `CONTRIBUTIN.md` to the build a source section of the install page in the docs. I'll work on that separately.

**Comment by tamird** [comment]
I have a slight preference for directing to CONTRIBUTING.md from the build a source section (or embed something from CONTRIBUTING.md there) because we can update CONTRIBUTING.md atomically with version bumps.

**Comment by jseldess** [comment]
@tamird, I wouldn't want general users (not contributors) who happen to be building from source to have to go to `CONTRIBUTING.md` to get all the details. But I'm definitely interested in your embed idea. If there is a way to include content from one repo in a file in another, that'd be great.

**Comment by tamird** [comment]
Well, there is and there isn't. The github homies have decided not to allow includes https://github.com/github/markup/issues/172#issuecomment-33241601

**Comment by andreimatei** [comment]
Can I hijack this for a second and ask why we've incremented the min compiler ver? Generally people strive to be compatible with the most compilers, not the fewest.
(I agree that we should build the binaries we ourselves distribute with the latest one)

**Comment by tamird** [comment]
The downside of of increasing the number of compilers we support is obvious; what's the downside?

**Comment by andreimatei** [comment]
What the obvious downside? I'm not suggesting we do anything special to support old version (like not using new code syntax or working around compiler bugs), but I don't think that was the case here?

The upside is more people would be able to build and run this thing without having to update their compiler first... If you don't necessarily care about the latest theoretical code optimization, you shouldn't care about the compiler version.
Even for me personally it was a distraction to figure out how I had installed the compiler and how I'm supposed to upgrade it. I'm not upset about that, you could argue that for the core team it is important we all run exactly the same thing, etc. But I don't know if this translates exactly to the random Joe who just wants to have a good time.

In the C++ world, at least, I've never seen projects ask me to get a super new compiler to build them. In fact quite the contrary, some jump through hoops to support old ones.

**Comment by tamird** [comment]
It's not just about optimizations; Go version increments sometimes ship minor breaking changes. Comparing the Go compiler to gcc is unwise; they require vastly different amounts of yak shaving to install and use.

I'd agree if you suggested that we pay some overhead to support gccgo as well as gc, but support multiple versions of gc seems to carry virtually zero benefit.

**Comment by bdarnell** [comment]
> Go version increments sometimes ship minor breaking changes. 

Can you point to any? My impression is that compatibility is very good between minor versions; the risk of failure because some people run 1.6.1 while others run 1.6.2 is small (case in point: it took us a while to upgrade to 1.6.2 on CI while most of us were running that version locally) and the inconvenience of getting everyone to upgrade in lockstep is real.

**Comment by tamird** [comment]
I don't think there were any in the 1.6 cycle. I think there were some in
1.5 cycle at the periphery (e.g. `vet` behaviour changed slightly).

**Pull request merged**
