### PR TITLE
sql/sem/tree: bugfix in handling unary negatives

### LINKED ISSUE #38780: sql: incorrect handling of negatives
`select -1/1` incorrectly returns `1`. It is believed to have been introduced by f4658b4. It is present in 2.1 and 19.1.

### PR DESCRIPTION
**Pull request by rafiss**
When performing constant folding, we will now always evaluate unary
negatives right away. To facilitate this, this commit extracts a NumExpr
interface that is implemented by *NumVal. The new interface has methods
to access the constant.Value of the *NumVal, and this accessor always
will perform the necessary unary negation operator.

This works because unary negation has high precedence (only preceded by
the typecast operation).

This change requires us to inspect the Negative flags of both the Expr
and inner Decimal value when resolving a NumExpr that contains a
Decimal, since on some operations like division, the negative value will
now get folded into the Decimal.

Many eval tests are added to ensure compatibility with Postgres.

To make it harder to mess up the interpretation of the value inside the NumVal
struct, the fields of NumVal are no longer exported. Now in order to access the
value, you must use the AsConstantValue() or AsConstantInt() functions (when
using the struct outside of the tree package).

The next step would be to move NumVal to its own package, which is quite
complicated due to its usages. NumVal implements interfaces that are
defined in the tree package, and tree depends on NumVal, so it's hard
to avoid a cyclic dependency.

fixes #38780

Release note (bug fix): unary negatives in constant arithmetic expressions
are no longer ignored.

### CODE REVIEW

**Comment by rafiss** [comment]
The thing I'm most unsure about here is the new interface I added. The idea was to make it harder to forget to handle the Negative as @jordanlewis and @mjibson suggested in the linked issue. If you have any tips about making a better type hierarchy for this golang noob, please review! 😄

**Review by knz — COMMENTED** [review]
I don't have enough paged-in knowledge to effectively review this, so I'll trust jordan and Matt. I haven't seen anything obviously out of place though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-:-LlDrhTN48dEIefLY079:bor2n1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @mjibson)

**Review by jordanlewis — COMMENTED** [review]
I suggested IRL that we could avoid the problem of people touching `.Value` directly by moving the `NumVal` and `StrVal` structs (and any associated relevant stuff) to a new package, unexporting `.Value`, and leaving only `AsValue` (which would then have to be exported, of course).

I think investigating this would probably be worthwhile, to at least determine if it would be way too onerous to go through with. Having these in a new package would definitely be a clean idea - just not clear at this point whether it's worth it to go through with at this point.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-:-LlE0Gvm7Q3ddZnXEu6F:bdy0fw6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mjibson, and @rafiss)

___
*[pkg/sql/sem/tree/expr.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-LlDx_f_5Jo4E63Qqulu:-LlDx_f_5Jo4E63Qqulv:b-yhdnsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c51ff4eced0043be08565a9a8645137d70f35b4/pkg/sql/sem/tree/expr.go#L85)):*
> ```Go
> var _ VariableExpr = &ColumnItem{}
> 
> // NumExpr is an Expr that has a numerical constant.
> ```

Should this say that *is* a numerical constant?
___
*[pkg/sql/sem/tree/expr.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-LlDxmF7-ly4mNEcYqQW:-LlDxmF7-ly4mNEcYqQX:b-qbbdlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c51ff4eced0043be08565a9a8645137d70f35b4/pkg/sql/sem/tree/expr.go#L86)):*
> ```Go
> 
> // NumExpr is an Expr that has a numerical constant.
> type NumExpr interface {
> ```

Does this need to be exported? It doesn't look like it - and if it doesn't, just make it `numExpr` to simplify our lives a little.

I also don't immediately see why you needed to introduce this interface at all - isn't `NumVal` still the only thing that implements `asConstantInt` and so on? Or are there things that embed `NumVal`?
___
*[pkg/sql/sem/tree/expr.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-LlDxj00BAh0tGvTiHuC:-LlDxj00BAh0tGvTiHuD:b-qgru20) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c51ff4eced0043be08565a9a8645137d70f35b4/pkg/sql/sem/tree/expr.go#L89)):*
> ```Go
> 	Expr
> 	asValue() constant.Value
> 	asConstantInt() (constant.Value, bool)
> ```

You should add comments to these to explain what they do, especially in the case where there's an extra return parameter that isn't self explanatory.

**Review by rafiss — COMMENTED** [review]
i'm going to look into doing that package refactor

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-:-LlHnRF-7TYIaxLvffDV:b-9us2qk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mjibson, and @rafiss)

___
*[pkg/sql/sem/tree/expr.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-LlDx_f_5Jo4E63Qqulu:-LlHnAf32Puu8X7qtwc8:bi0dl5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c51ff4eced0043be08565a9a8645137d70f35b4/pkg/sql/sem/tree/expr.go#L85)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Should this say that *is* a numerical constant?
</blockquote></details>

probably not going to keep the interface around
___
*[pkg/sql/sem/tree/expr.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-LlDxmF7-ly4mNEcYqQW:-LlHmpVV3OJwds3f-pnx:b-v3h58z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c51ff4eced0043be08565a9a8645137d70f35b4/pkg/sql/sem/tree/expr.go#L86)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Does this need to be exported? It doesn't look like it - and if it doesn't, just make it `numExpr` to simplify our lives a little.

I also don't immediately see why you needed to introduce this interface at all - isn't `NumVal` still the only thing that implements `asConstantInt` and so on? Or are there things that embed `NumVal`?
</blockquote></details>

yeah, the interface seems kind of pointless. my goal was to make people use the interface instead of the struct, so they have to use the accessor function, but that can't be enforced unless the struct moves to a different package. so, the real solution is to move it, and we wouldn't need the interface then.
___
*[pkg/sql/sem/tree/expr.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-LlDxj00BAh0tGvTiHuC:-LlHnFAh7NZ5w-y3AcXt:b5fmko2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c51ff4eced0043be08565a9a8645137d70f35b4/pkg/sql/sem/tree/expr.go#L89)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You should add comments to these to explain what they do, especially in the case where there's an extra return parameter that isn't self explanatory.
</blockquote></details>

will do, if i keep the interface. (i forgot to do it, since the function implementations were documented)

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39245)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mjibson, and @rafiss)

___
*[pkg/sql/sem/tree/expr.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-LlDxmF7-ly4mNEcYqQW:-LlHnrBA5lZZkJyhkGxT:bd4abq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c51ff4eced0043be08565a9a8645137d70f35b4/pkg/sql/sem/tree/expr.go#L86)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

yeah, the interface seems kind of pointless. my goal was to make people use the interface instead of the struct, so they have to use the accessor function, but that can't be enforced unless the struct moves to a different package. so, the real solution is to move it, and we wouldn't need the interface then.
</blockquote></details>

Ah, hmm, well wait a minute, could you consider changing the types that people have available to be `NumExpr` then instead of `NumVal`? Or are there too many places to change? I think that has the potential to fix the issue without having to make a new package etc.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39245)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mjibson, and @rafiss)

___
*[pkg/sql/sem/tree/expr.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-LlDxmF7-ly4mNEcYqQW:-LlHoREB6wNf0vplHNrT:b-tnhkn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c51ff4eced0043be08565a9a8645137d70f35b4/pkg/sql/sem/tree/expr.go#L86)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Ah, hmm, well wait a minute, could you consider changing the types that people have available to be `NumExpr` then instead of `NumVal`? Or are there too many places to change? I think that has the potential to fix the issue without having to make a new package etc.
</blockquote></details>

there is a fair amount of places to change, but it's doable. but the issue is most of the usages of `NumVal` are in the `tree` package anyway, so in the future, it's pretty likely that someone would just end up using `NumVal` when we don't want them to. (am i correct in my understanding that Go has no "private" type visibility like Java's? the most is just package-private?)

**Comment by mjibson** [comment]
We have already done the "move a misused type to its own package so it can't be misused in the future" with, for example, dates. This was a very nice exercise and is a clean solution to this kind of problem. Based on my read of the discussion above, I recommend doing that. If it is its own package, we indeed should not have an interface, just a struct, but with perhaps no exported properties, only methods. See https://godoc.org/github.com/cockroachdb/cockroach/pkg/util/timeutil/pgdate#Date for reference.

**Review by jordanlewis — APPROVED** [review]
:lgtm: nice work and tests.

@rafiss would you summarize our offline discussion here as to why it was too difficult to try to move the constant stuff out to a new package, just for posterity?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-:-LlZuuon9sJiRcnteZ3j:b-pkt4nw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @rafiss)

___
*[pkg/sql/sem/tree/expr.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-LlDxmF7-ly4mNEcYqQW:-LlZugOSC4ERdV70BJrY:b3ymr47) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c51ff4eced0043be08565a9a8645137d70f35b4/pkg/sql/sem/tree/expr.go#L86)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

there is a fair amount of places to change, but it's doable. but the issue is most of the usages of `NumVal` are in the `tree` package anyway, so in the future, it's pretty likely that someone would just end up using `NumVal` when we don't want them to. (am i correct in my understanding that Go has no "private" type visibility like Java's? the most is just package-private?)
</blockquote></details>

Yeah, there's just package-private-ness, unfortunately for us.

**Comment by mjibson** [comment]
Here's another good solution: after #39159 merges, write a linter that looks for misuse of this struct.

**Review by rafiss — COMMENTED** [review]
@jordanlewis yes certainly. i added a separate commit to this PR that has that rationale, but i forgot that the new commit message won't go into this issue automatically.

@mjibson amazing! the linter seems like it would be great here; i'll keep an eye out for that merging

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39245#-:-LlbRNe84CUwlV-t8pfF:bdjqme7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @rafiss)

**Comment by rafiss** [comment]
thanks all

bors r+

**Pull request merged**
