### PR TITLE
engine: report safe errors via dictionary

### PR DESCRIPTION
**Pull request by tbg**
This should put us ahead of the curve far enough so that we can make sense of
most RocksDB errors that get reported via sentry.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/rocksdb_error.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023#-L10PJHO-JYHgQSvwO5K:-L10PJHO-JYHgQSvwO5L:bf7phz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e69f031cc60eb023a9eb846e7a7f18ae024db740/pkg/storage/engine/rocksdb_error.go#L1)):*
> ```Go
> // Copyright 2014 The Cockroach Authors.
> ```

`s/2014/2017/g` (there is at least one other file this applies to as well)

---

*[pkg/storage/engine/rocksdb_error.go, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023#-L10P9q5aku6uNpsha_b:-L10P9q5aku6uNpsha_c:boxfyar) ([raw file](https://github.com/cockroachdb/cockroach/blob/e69f031cc60eb023a9eb846e7a7f18ae024db740/pkg/storage/engine/rocksdb_error.go#L39)):*
> ```Go
> func (err RocksDBError) SafeMessage() string {
> 	var out []string
> 	cleanRE := regexp.MustCompile(`[^a-zA-Z]+`)
> ```

The previous code had a comment about the format of RocksDB error messages. Can you include that here or otherwise describe what you're parsing?

---

*[pkg/storage/engine/rocksdb_error_dict.go, line 2312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023#-L10Q7JAyifr2KHO_RoI:-L10Q7JAyifr2KHO_RoJ:bdhzpus) ([raw file](https://github.com/cockroachdb/cockroach/blob/e69f031cc60eb023a9eb846e7a7f18ae024db740/pkg/storage/engine/rocksdb_error_dict.go#L2312)):*
> ```Go
> 	"zstd":                         struct{}{},
> 	"zu":                           struct{}{},
> 	"zzz":                          struct{}{},
> ```

This is a pretty gigantic dict. Is the size any concern?

Also, I think you've grabbed too much. `git grep "zzz"` reveals that string only occurs in `*_test.cc` and `*_example.cc` files. I think you should exclude the latter as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023)*

**Comment by tschottdorf** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/engine/rocksdb_error.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023#-L10PJHO-JYHgQSvwO5K:-L1JBzBZ0S1qb_epTxYW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e69f031cc60eb023a9eb846e7a7f18ae024db740/pkg/storage/engine/rocksdb_error.go#L1)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/2014/2017/g` (there is at least one other file this applies to as well)
</blockquote></details>

Done.

---

*[pkg/storage/engine/rocksdb_error.go, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023#-L10P9q5aku6uNpsha_b:-L1JCqG4FHM01lkoCiPH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e69f031cc60eb023a9eb846e7a7f18ae024db740/pkg/storage/engine/rocksdb_error.go#L39)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The previous code had a comment about the format of RocksDB error messages. Can you include that here or otherwise describe what you're parsing?
</blockquote></details>

Done.

---

*[pkg/storage/engine/rocksdb_error_dict.go, line 2312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023#-L10Q7JAyifr2KHO_RoI:-L1JCqxsfpf2weXWaVIh:b-m8bcs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e69f031cc60eb023a9eb846e7a7f18ae024db740/pkg/storage/engine/rocksdb_error_dict.go#L2312)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is a pretty gigantic dict. Is the size any concern?

Also, I think you've grabbed too much. `git grep "zzz"` reveals that string only occurs in `*_test.cc` and `*_example.cc` files. I think you should exclude the latter as well.
</blockquote></details>

Good point, I've sharpened the filters a bit. The dictionary now has 1.1k entries (down from >2k), which I don't find concerning, but perhaps I'm missing something. I don't expect this dict to grow much more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023)*

**Comment by jordanlewis** [comment]
Without reviewing, I think this is a good idea - I think the RocksDB errors are quite obtuse. Trying to make them more understandable seems like a good idea.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/engine/rocksdb_error_dict.go, line 2312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023#-L10Q7JAyifr2KHO_RoI:-L1KaYNIfMbVQVYMpnkV:b5qblp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e69f031cc60eb023a9eb846e7a7f18ae024db740/pkg/storage/engine/rocksdb_error_dict.go#L2312)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Good point, I've sharpened the filters a bit. The dictionary now has 1.1k entries (down from >2k), which I don't find concerning, but perhaps I'm missing something. I don't expect this dict to grow much more.
</blockquote></details>

The trimming looks good. Another quick inspection reveals that this dict contains % formatters. For example, `git grep -w zu` seems to indicate that it is one of those funky posix integer printf format specifiers.

The dictionary certainly looks better now. Before it seemed to be full of junk, but a quick skim now reveals actual words and terms.

---

*[pkg/storage/engine/rocksdb_error_dict.go, line 23 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023#-L1KbA9JKErrKw_N9RZl:-L1KbA9JKErrKw_N9RZm:baadil2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4141bc318df675b43a599c42e116e0b836f32a5a/pkg/storage/engine/rocksdb_error_dict.go#L23)):*
> ```Go
> 	-a -not -name '*_test*' \
> 	-a -not -name '*_bench*' \
> 	-a -not -name '*_example*' |
> ```

Perhaps add `*_tool*`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21023#-:-L1KcDqnSN8pOmBWwz4k:bnfp4nl)*

**Comment by tschottdorf** [comment]
TFTR! I worked on the regexes a bunch more which resulted in a further noticeable trimming of detritus, including `zu`.

**Pull request merged**
