### PR TITLE
admission: elastic tokens for L0 compaction bandwidth

### PR DESCRIPTION
**Pull request by sumeerbhola**
Currently we start shaping traffic at 5 sublevels (tokens are 2x the compaction bandwidth), and stabilize close to 10 sublevels (tokens are equal to compaction bandwidth). This token calculation is under the assumption that stabilizing at 10 sublevels represents an acceptably high utilization point for the resource, and can be sustained indefinitely. We know this assumption is incorrect in two ways:
- Having 10 sublevels results in worse performance for reads, so it isn't necessarily acceptable.
- This throughput can't be sustained indefinitely, since compaction debt is increasing.

We have ongoing work to increase the duration we can sustain this throughput (bullet 2), since in the general case we may have such load due to multiple tenants, or a combination of regular-priority and high-priority traffic. And the increased duration will allow the allocator to shift load.

Here we take a complementary approach to the ongoing work, which addresses both bullets above for the case where the resource saturation is being caused by lower priority (elastic traffic). This can happen for MVCC GC, index backfills etc. We generate a different set of tokens that start shaping when sublevels are 1 or greater (1.25 the compaction bandwidth at 1 sublevel). These tokens are deducted from for all traffic priorities, but elastic traffic must block if these tokens are unavailable. This earlier shaping causes L0 sublevels to stabilize around 3, and compaction debt to become flat at a reasonable backlog.

Epic: none

Release note: None

### CODE REVIEW

**Comment by sumeerbhola** [comment]
Experiments run with single node cluster:
```
roachprod create -n 2 --clouds gce --gce-machine-type n2-standard-8 --local-ssd=false sumeer-io
roachprod put sumeer-io:1 /Users/sumeer/go/src/github.com/cockroachdb/cockroach/artifacts/cockroach ./cockroach
roachprod put sumeer-io:2 /Users/sumeer/go/src/github.com/cockroachdb/cockroach/artifacts/workload ./workload
roachprod start sumeer-io:1 --args '--vmodule=io_load_listener=2'

roachprod run sumeer-io:2 -- ./workload run kv --init --histograms=perf/stats.json --concurrency=100 --splits=1000 --duration=30m0s --read-percent=0 --min-block-bytes=65536 --max-block-bytes=65536 --max-rate=250 --tolerate-errors {pgurl:1-1}

roachprod run sumeer-io:2 -- ./workload run kv --init --histograms=perf/stats.json --concurrency=512 --splits=1000 --duration=30m0s --read-percent=0 --min-block-bytes=65536 --max-block-bytes=65536 --background-qos=true --tolerate-errors {pgurl:1-1}
```
The background-qos work was started after running regular work for a while such that L3 is Lbase. The regular work has --max-rate=250, and consumes a good amount of bandwidth, but does not overload the LSM. The background work is not shaped (and very high concurrency) so will overload the LSM.

Things to note in the graphs below, with this PR:
- Lower sublevel count.
- Flat compaction debt after some time.
- L0 compaction score is more competitive with the other levels.
 
On master:
Screenshot 2023-08-18 at 3 05 03 PM
With this PR:
Screenshot 2023-08-19 at 11 02 07 AM

On master:
Screenshot 2023-08-18 at 3 04 41 PM
With this PR:
Screenshot 2023-08-19 at 11 01 44 AM

**Review by bananabrick — COMMENTED** [review]
> Reviewed 3 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109085)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @sumeerbhola)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcP29-XDE8Hl9V5O4PO):*
nit: Is it assured that the compaction debt is increasing? Could it stabilize at a higher threshold? I've seen the Lbase to L5 scores stabilize at some score usually. The score after the elastic work starts just happens to be larger than the score before any elastic work starts.
___
*[`pkg/util/admission/granter.go` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcPDurf5cjQjUlBAV-g:-NcPDurf5cjQjUlBAV-h:b-k9cz6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5caa3f3e66e9f0cb9e5c553961e0456db21cc014/pkg/util/admission/granter.go#L317)):*
> ```Go
> 	// computing startingIOTokens-availableIOTokens.
> 	startingIOTokens                int64
> 	startingElasticIOTokens         int64
> ```

This is only set and not used.
___
*[`pkg/util/admission/granter.go` line 562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcPFM5D0x490lhJ6Rz9:-NcPFM5D0x490lhJ6RzA:b-ajqjz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5caa3f3e66e9f0cb9e5c553961e0456db21cc014/pkg/util/admission/granter.go#L562)):*
> ```Go
> 	if lastTick {
> 		sg.coordMu.availableElasticIOTokens = max(sg.coordMu.availableElasticIOTokens, 0)
> 		if sg.coordMu.availableElasticIOTokens > sg.coordMu.availableIOTokens {
> ```

nit: If we've defined a max function, we could also define min for this. It would definitely make this function easier to look at.
___
*[`pkg/util/admission/io_load_listener.go` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcPP56N0qfk_hRiF3XS:-NcPP56N0qfk_hRiF3XT:b-y4esfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5caa3f3e66e9f0cb9e5c553961e0456db21cc014/pkg/util/admission/io_load_listener.go#L203)):*
> ```Go
> 	byteTokensAllocated int64
> 	// Used tokens can be negative if some tokens taken in one interval were
> 	// returned in another, but that will be extremely rare.
> ```

Unrelated, but did we experimentally observe that this is rare?
___
*[`pkg/util/admission/io_load_listener.go` line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcPWWJQ6-pnWd4FyCZ_:-NcPWWJQ6-pnWd4FyCZa:b-eiv8vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5caa3f3e66e9f0cb9e5c553961e0456db21cc014/pkg/util/admission/io_load_listener.go#L904)):*
> ```Go
> 
> 	totalNumElasticByteTokens := int64(unlimitedTokens)
> 	if score >= 0.1 {
> ```

nit: Maybe we can write a note on why a score of 0.1 is equivalent to one sublevel.

```
score == (# sublevel / 20) * 2.
 #sublevel / 10 >= 0.1 => #sublevel >= 1. So we start restricting when we have one sublevel.
```
___
*[`pkg/util/admission/io_load_listener.go` line 910 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcPZZLEA4VLVEOQKjGA:-NcPZZLF6A4kZD41sHKe:bt71s8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5caa3f3e66e9f0cb9e5c553961e0456db21cc014/pkg/util/admission/io_load_listener.go#L910)):*
> ```Go
> 		// will be 0.75*compaction-bandwidth.
> 		totalNumElasticByteTokens = int64(1.25*float64(smoothedIntL0CompactedBytes) -
> 			1.25*(score-0.1)*float64(smoothedIntL0CompactedBytes))
> ```

If score >= 1.1, which is 11 sublevels, then we're going to admit practically 0 elastic work. Is that intended?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

I'll ping after adding tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-:-NcTGT0456WPiMwH1g7M:bnhn1m8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @irfansharif)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcP29-XDE8Hl9V5O4PO):*
> Could it stabilize at a higher threshold?

Yes, it is very possible. And at the level it stabilizes, it may be that the L0 compaction bandwidth has significantly reduced.
___
*[`pkg/util/admission/granter.go` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcPDurf5cjQjUlBAV-g:-NcT8qgk7mC39fzL38yC:bvfcruz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5caa3f3e66e9f0cb9e5c553961e0456db21cc014/pkg/util/admission/granter.go#L317)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

This is only set and not used.
</blockquote></details>

Removed (leftover experiment debugging state)
___
*[`pkg/util/admission/granter.go` line 562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcPFM5D0x490lhJ6Rz9:-NcT9WTs3ynRaM5MQlM8:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5caa3f3e66e9f0cb9e5c553961e0456db21cc014/pkg/util/admission/granter.go#L562)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: If we've defined a max function, we could also define min for this. It would definitely make this function easier to look at.
</blockquote></details>

Done
___
*[`pkg/util/admission/io_load_listener.go` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcPP56N0qfk_hRiF3XS:-NcT9iCA-_RM9X1HdhJ8:bkwjagr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5caa3f3e66e9f0cb9e5c553961e0456db21cc014/pkg/util/admission/io_load_listener.go#L203)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Unrelated, but did we experimentally observe that this is rare?
</blockquote></details>

The negative value is rare -- I've never seen it in the periodic log statement. But before replication admission control, the sequence of events for a work was:
- IO admission (deduct B)
- CPU admission
- Locking and latching
- Proposal evaluation and replication
- Compute actual B', and take B'-B

The last step is where tokens could be returned if B'-B was negative. And there could be queueing for CPU admission and latching and locking, which could be arbitrarily long, so could cross a 15s interval boundary.

But with replication admission control, all the IO admission happens after proposal evaluation, and we're deducting B', so fewer things can cross that boundary.
___
*[`pkg/util/admission/io_load_listener.go` line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcPWWJQ6-pnWd4FyCZ_:-NcTCl3KApXOxr1qswt5:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5caa3f3e66e9f0cb9e5c553961e0456db21cc014/pkg/util/admission/io_load_listener.go#L904)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: Maybe we can write a note on why a score of 0.1 is equivalent to one sublevel.

```
score == (# sublevel / 20) * 2.
 #sublevel / 10 >= 0.1 => #sublevel >= 1. So we start restricting when we have one sublevel.
```
</blockquote></details>

Done
___
*[`pkg/util/admission/io_load_listener.go` line 910 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcPZZLEA4VLVEOQKjGA:-NcTEKbmAiZiMakysnSP:b-jmzqxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5caa3f3e66e9f0cb9e5c553961e0456db21cc014/pkg/util/admission/io_load_listener.go#L910)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

If score >= 1.1, which is 11 sublevels, then we're going to admit practically 0 elastic work. Is that intended?
</blockquote></details>

Yes, intended. I've added a comment.

**Review by sumeerbhola — COMMENTED** [review]
Tests are ready.

Also added a roachtest, whose output looks like:
```
18:24:30 admission_control_elastic_io.go:78: test status: running workload
18:24:30 cluster.go:2158: running cmd `./workload run kv --init --...` on nodes [:2]; details in run_182430.487580000_n2_workload-run-kv-init.log
18:24:31 monitor.go:177: Monitor event: n1: cockroach process is running (PID: 11946)
18:27:00 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 2.000000
18:27:30 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 3.000000
18:28:00 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 4.000000
18:28:30 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 4.000000
18:29:00 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 3.000000
18:29:31 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 2.000000
18:30:01 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 2.000000
18:30:31 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 4.000000
18:31:01 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 4.000000
18:31:31 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 2.000000
18:32:01 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 2.000000
18:32:31 admission_control_elastic_io.go:107: storage_l0_sublevels(store=1): 2.000000
...
```

> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-:-NcTWSwA0y4f9SdnvsIw:b7b2pc2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @irfansharif)

**Review by bananabrick — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 10 files at r1, 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-:-NcdE14nCInMcv_vG4uY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif, @renatolabs, @smg260, and @sumeerbhola)

___
*[`pkg/cmd/roachtest/tests/admission_control_elastic_io.go` line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcdE7rN-Sr0WTduO0G-:-NcdE7rN-Sr0WTduO0G0:b-p2t1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b543e75cea9a03840556cb2f0349b5054ff88/pkg/cmd/roachtest/tests/admission_control_elastic_io.go#L115)):*
> ```Go
> 				now := timeutil.Now()
> 				endTime := now.Add(duration)
> 				const subLevelThreshold = 7
> ```

Why did we pick 7?
___
*[`pkg/util/admission/io_load_listener_test.go` line 369 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcdDsFb0lZuZQjayQDX:-NcdDsFb0lZuZQjayQDY:b-zaq6n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b543e75cea9a03840556cb2f0349b5054ff88/pkg/util/admission/io_load_listener_test.go#L369)):*
> ```Go
> 	maxIOTokens int64,
> 	maxElasticIOTokens int64,
> 	maxElasticTokens int64,
> ```

nit: can call this`maxElasticDiskBandwidthTokens`.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109085)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick, @irfansharif, @renatolabs, and @smg260)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcP29-XDE8Hl9V5O4PO):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> Could it stabilize at a higher threshold?

Yes, it is very possible. And at the level it stabilizes, it may be that the L0 compaction bandwidth has significantly reduced.
</blockquote></details>

(for the record) We now know that the debt doesn't stabilize as discussed in https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1692828798943989?thread_ts=1692819492.618039&cid=CAC6K3SLU
___
*[`pkg/cmd/roachtest/tests/admission_control_elastic_io.go` line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcdE7rN-Sr0WTduO0G-:-NcdRbufAoHXRMjP5dYp:b-sj6wig) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b543e75cea9a03840556cb2f0349b5054ff88/pkg/cmd/roachtest/tests/admission_control_elastic_io.go#L115)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Why did we pick 7?
</blockquote></details>

Added a comment
```
// We typically see fluctuations from 1 to 5 sub-levels because the  
// elastic IO token logic gives 1.25\*compaction-bandwidth tokens at 1  
// sub-level and 0.75\*compaction-bandwidth at 5 sub-levels, with 5  
// sub-levels being very rare. We leave some breathing room and pick a  
// threshold of greater than 7 to fail the test. If elastic tokens are  
// not working, the threshold of 7 will be easily breached, since  
// regular tokens allow sub-levels to exceed 10.
```
___
*[`pkg/util/admission/io_load_listener_test.go` line 369 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109085#-NcdDsFb0lZuZQjayQDX:-NcdWQYcAeGJ9rYI7rIJ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b543e75cea9a03840556cb2f0349b5054ff88/pkg/util/admission/io_load_listener_test.go#L369)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: can call this`maxElasticDiskBandwidthTokens`.
</blockquote></details>

Done

**Comment by sumeerbhola** [comment]
bors r=bananabrick

**Pull request merged**
