### PR TITLE
sql: refactor deps tests to use bazel

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit refactors most `VerifyNoImports` dependency tests in the sql
folder to use the newly introduced bazel test utilities.

Release note: None

Jira issue: CRDB-14814

### CODE REVIEW

**Review by rickystewart — APPROVED** [review]
Nice!

**Comment by ajwerner** [comment]
Your flake, womp womp: `        (53100) in-mem temp storage: disk budget exceeded: 1048576 bytes requested, 104857600 currently allocated, 104857600 bytes in budget
`

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/4795705?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Are there features regarding prefixes or `allowed` package which would make this easier or better?

**Comment by michae2** [comment]
Newbie question: why do we disallow these imports? Is it to prevent layer violations in the vectorized engine?

**Comment by yuzefovich** [comment]
The flake appears to be known (#74554).

> Are there features regarding prefixes or `allowed` package which would make this easier or better?

I don't think so - all tests that are converted in this PR didn't use those features, and it was pretty simple to convert them to the new format. One thing I noticed is that some of the prohibited dependencies would form import cycles if they were actual dependencies, so I guess I could have trimmed down the lists a bit, but I decided to not think too much and converted things as is. There were a couple of failures though, so I had to adjust the lists. Still, the process was quite straightforward, thanks for setting it up!

TFTRs!

bors r+

**Comment by yuzefovich** [comment]
> Newbie question: why do we disallow these imports? Is it to prevent layer violations in the vectorized engine?

No, mostly to make the packages that are imported in many places lightweight - recent example, a change in `roachpb` up until recently forced rebuilding of `execgen` which forced regeneration all of the vectorized code, so the build times would sky-rocket.

**Comment by rickystewart** [comment]
> There were a couple of failures though, so I had to adjust the lists. 

It would be very helpful if you could provide a list of the deps you had to delete to get these tests to pass. Would be great if we could drill down on the forbidden imports that got introduced due to bitrot and start addressing them.

**Comment by yuzefovich** [comment]
>> There were a couple of failures though, so I had to adjust the lists.

> It would be very helpful if you could provide a list of the deps you had to delete to get these tests to pass. Would be great if we could drill down on the forbidden imports that got introduced due to bitrot and start addressing them.

Sorry, I should have been more specific. I don't think any of the dependencies were bad - the tests were broken when they were introduced. A couple of examples: `colexecproj/dep_test.go` was "asserting" that `colexecbase` is not imported, but in fact it is, and that's ok; `execgen` was asserting that `sql/tree` is not imported - such package doesn't exist, it should have been `sql/sem/tree`. All the changes in this PR were not concerning at all.

**Comment by michae2** [comment]
> > Newbie question: why do we disallow these imports? Is it to prevent layer violations in the vectorized engine?
> 
> No, mostly to make the packages that are imported in many places lightweight - recent example, a change in `roachpb` up until recently forced rebuilding of `execgen` which forced regeneration all of the vectorized code, so the build times would sky-rocket.

Makes sense, thank you!

**Comment by ajwerner** [comment]
The way I see it, this test is primarily about enforcing dependency graph hygiene.

**Pull request merged**
