### PR TITLE
opt: fix strict UDFs with subquery arguments

### LINKED ISSUE #101516: sql: inlining UDF leads to a potentially invalid query plan
roachtest.sqlsmith/setup=rand-tables/setting=no-mutations [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9599051?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9599051?buildTab=artifacts#/sqlsmith/setup=rand-tables/setting=no-mutations) on master @ [8e6cdbd8b3d12ba5d65db101a3abfeb2cb1bf470](https://github.com/cockroachdb/cockroach/commits/8e6cdbd8b3d12ba5d65db101a3abfeb2cb1bf470):

```
							NULL,
							'0104000020E61000000300000001010000004AE5D0E6ED5760403CFD7998187448C00101000000741FE78AB8F762C064891EC2FD10534001010000008D55756D240C61C064FA356C6AF03340':::GEOGRAPHY
						),
						(
							'0106000060E6100000020000000103000040010000000D000000A77D3BEFAAF865C0D0D43CF4149119C06E8A914232B3FDC1EE32A108EB1E64C068C6C153089B25C09874723BEA8AFC41420F86B9E56052C01CE0EEAA6FDC32C0B44C2CF322FFFB41D0BEFBECE3E0454040ABF9A619C739C0A0EBC6C147A8FF41DCF7A40D30D958402FB991E18AD743C01E102F41A843E0C1ACFCDC7065865340006C66440911E93FE68F5B1B0BE6F8418093D3F627C25B400048A45B0B19A9BF926A84B403CBF5416EFF6F593CF76340E49738906C7745403259058D1598F441C8DCBDE405CB33C0C474EB7EC5A64140AA970F86BB27F741EC4CBD14532643C002E9D334046E5440FCF2BC613E57F141615D6882338650C0ECA03F245FDE48408933F71518A6F6C12548D3E991C265C01865B8C6A8084540F646A445A181F341A77D3BEFAAF865C0D0D43CF4149119C06E8A914232B3FDC10103000040010000000600000021DBE90A6B3363C0350068D506B944C0E65630774BDFF3C1E819BF49CFF66240B4F69800E571454012EFDF8CCA9C024224815B8057EE494074E33A8A27974840A0A5FFB37FAFF6C18608FF8D268A6340042002DE3474544098FDF19C9A9FEB41E0AC6EFDE1AA61C072C99FEDC68F5440ACCA9AB99C1DEC4121DBE90A6B3363C0350068D506B944C0E65630774BDFF3C1':::GEOGRAPHY,
							'01040000A0E61000000900000001010000806BF81F0E7CA65AC0CEDB48C4A8754FC0BC65FCAD0B84FA41010100008064CDE19DE18C5640264976B14A1B544018431A5AA197DC4101010000800CC4A52BC1386440804AFE6091944C40889023DE89E1D9C101010000803C6F8DD650D243C000AA77BC048523408656E32FA129F0410101000080BEF0666E883266C05C9B49EFDBB63940C0E56B11F096BEC10101000080683E7AC0A21C6340AED0D9C7CC9D51C0D57E059D418EF1C10101000080A0C7D7DDC08D3DC0880BE63B3C865040FE1E678CECC0FFC10101000080F8193C1E4AFA3E4000674FA0C4DCF93F9EFDC3CECFEBF1410101000080F8B2D1CF241F66C0405213DE70080DC039FEF93710C0F4C1':::GEOGRAPHY
						),
						(
							'0107000020E6100000020000000103000020E6100000010000000D000000606AC5312F2F26C0808CED6B79AF00C000BE4AF8E8A22FC0F80BB817D6B526C088A490E8CB76494093929F437A2B50C00000836999A4594076D343C5659950C06CA706E4ECDB60405064A8E750411EC038325ACB2EE46240B0252DBA019742408C323A44383E5E40883CDA1B58E3454080D256CF4BE82BC0E4B08913DBD04440CA12554039D74CC0DA62351721075240F640076BFEFB57C0584E5D5311F9464012D2EF8AA9C465C028AECC1384CE3C40061943ECA19056C034DB2BCC880A3440606AC5312F2F26C0808CED6B79AF00C00101000020E6100000C84E2D5A432864C004858D38AA773D40':::GEOGRAPHY,
							'0105000020E61000000600000001020000000300000034BB398975ED5040AD09C98911E749C05A55A2E70A276340F5BC04EC0C9153C0205AE0BC51545E40820DA12A9E05524001020000000300000000CFA63F3D101640901210B9A77951C004F9AD5A51B561405425229FC4453C404A42FFD2FAD562400C3CAFD1584A4A40010200000008000000C07968388AB10BC000498CB7860444C050A3E078810E4F4074519F54C71152C0FC468265A5785E404CEC5A1204EE4EC0886B4C7B295C5A409269BBBEEDE545C0B4B891E231C35A40394C73441ACB40C0547781244C2864404AA024EE7674524016319476FD9F6240028FC7FDCE165240408CBBB70C512B4098915A6F4A3D4A40010200000003000000FDEC6C06D41E51C07148560B3AC142C0D630063015344DC094969A16D1A039C0E0AB3E6154313D40CDBB68ECE67151C0010200000003000000605ECF682F12244087230C0B212353C0A455589378485840984EBC53178339C0640B08882BC74440EAAB05E2F7025340010200000009000000A925571689F762C0BDC7E4B1A38146C0625D1E1CC6CB5EC04B66E9CD1EB254C080B404771EF30AC0563CD9189B634AC010669D1E517463403A432CE2EF7251C060C43A2BD10F2C40A0D52BFEDB9E3A401A5C5463BA6752C0B45E882AB7A04B40FECC38416F0763C07044EC6BFEF43F40CF12D336863C63C0B087A0C1B2761F40FA68BFFDD27060C04853202DEDCA29C0':::GEOGRAPHY
						)
				)
					AS tab14862 ("c
ol35125", c͓ol😊35126)
		),
	"witH4621" ("c*o̝l35127")
		AS (
			SELECT
				*
			FROM
				(
					VALUES
						(COALESCE('\x3ba51c44afa320':::BYTES, '\x3de8825870b0bbb24c':::BYTES)),
						('\xf46fd857e595':::BYTES),
						('\xb0f1732bad':::BYTES)
				)
					AS "tab14863" ("c*o̝l35127")
		)
SELECT
	"ta%pb14865".col2_1 AS "co\rl 35129",
	'19:32:11.540327':::TIME AS col35130,
	'rV':::STRING AS "co%ql35131",
	"tab14864".col1_4 AS col35132,
	"tab14864".col1_3 AS ",c͊ol35133",
	"tab14864".col1_5 AS "'col35134",
	'BOX(-0.4286228811461901 -1.8964545833981756,0.684610815294362 1.1142289400585454)':::BOX2D
		AS "co\\x33l\\U000A24E235135",
	NULL AS col35136,
	'24:00:00-15:59':::TIMETZ AS col35137,
	6226.565714040426329:::DECIMAL AS "c%vol35138",
	3391816648:::OID AS "\vcol35139",
	'01040000000400000001010000004CF6A80C2C33F6C1FB7352886958F0C1010100000000CD9F6D8368C141A5E024846F9CF1C10101000000AEAA6DD7F02100C2929F0DA9B478F1410101000000A8C179D9AAF5F9C112D813B0CE99E3C1':::GEOMETRY
		AS col35140
FROM
	defaultdb.public.table1@[0] AS "tab14864"
	JOIN defaultdb.public.table2@[0] AS "ta%pb14865" ON
			("tab14864".crdb_internal_mvcc_timestamp) = ("ta%pb14865".crdb_internal_mvcc_timestamp)
			AND ("tab14864".col1_5) = ("ta%pb14865"."co'l2_0")
WHERE
	st_ispolygoncw("f	u%3enc310"("tab14864"."col😈1_\\u82FB9"::NAME, 2.70799997137696369E+29:::DECIMAL::DECIMAL, B'0010010001011001100'::BIT(19), "ta%pb14865".col2_2::TIMESTAMPTZ, '60 years 7 mons 645 days 01:33:43.823806':::INTERVAL::INTERVAL, (SELECT "tab14864".col1_4 AS "c ol😘35128" FROM defaultdb.public.table2 AS tab14866 JOIN defaultdb.public.table2 AS """t̐ab14867" ON (tab14866.col2_2) = ("""t̐ab14867".col2_2) ORDER BY """t̐ab14867".col2_6, tab14866.col2_6 LIMIT 1:::INT8)::FLOAT4, "ta%pb14865".col2_7::INTERVAL, 'pqf':::rand_typ_0::rand_typ_0, '1987-11-30':::DATE::DATE)::GEOMETRY::GEOMETRY)::BOOL;
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26983

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: fix strict UDFs with subquery arguments

Previously, we wrapped all strict UDFs with a `CASE` expression to
prevent the UDF from being invoked when any of the arguments were
`NULL`. This was required in order to inline strict UDFs (see #94797).

Unfortunately, wrapping the arguments in a `CASE` expression caused
problems when the arguments were subqueries. The subqueries would be
duplicated in the optimizer expression, one copy used in the `CASE`
expression and another as an argument to the UDF`, with each copy
containing the same table and column IDs. Normalization rules could then
transform these subqueries into apply-joins that would have intersecting
columns in their left and right children. This caused optimizer
assertion failures in debug builds and could cause incorrect results in
release builds.

This commit implements a temporary fix which removes the synthesized
`CASE` expression entirely. The logic for returning `NULL` immediately
when a strict UDF is invoked with a `NULL` argument has been added back
into `planner.EvalRoutineExpr`, and strict UDFs are not longer inlined.

We should be able to inline strict UDFs by adding the `CASE` expression
during the `InlineUDF` normalization rule, as long as the arguments are
not complex expressions (e.g., only variables, constants, or
placeholders). This is left for a future commit.

Fixes #101516

Release note (bug fix): A bug has been fixed that could cause incorrect
results for queries invoking `STRICT` user-defined functions. This bug
was only present in pre-release versions of 23.1.

#### opt: add strict field to UDF expression format

Release note: None

#### opt: simplify description of ExprFmtFlags

The description of ExprFmtFlags has been simplified. It previously
contained a very detailed description of bitmasks and iota, which
probably isn't warranted because it is such a common pattern in the
codebase.

#### opt: inline strict UDFs

This commit inlines strict UDFs by wrapping the generated subquery
expression with a `CASE` expression. The `CASE` expression results in
`NULL` if any of the arguments of the UDF are `NULL`.

Note that even though the subquery is wrapped in a `CASE` expression, it
may still be evaluated due to the fact that non-correlated subqueries
are eagerly evaluated, see #20298. This should be fine because these
inlined UDFs shouldn't have side-effects - we don't inline volatile
UDFs.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
This turned out to be a nice simplification of some of the logic for strict UDFs. @rharding6373 I'm hoping it will simplify some of the UDF-as-a-datasource changes you've been working on, but I'm not sure. I think all this is safe to backport to 23.1.0, but if we want to play it safe, we can backport just the first (or first and second) commits. Curious to hear your thoughts @rharding6373 @DrewKimball.

**Review by rharding6373 — APPROVED** [review]
Thank you for the fix, it looks good! Since the logic forming the CASE statement stayed the same when moving from one location to another, I think it's not so risky and all commits are fine to backport.

> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-:-NTQYHxv0nqBmY9qCq0A:bgie0br)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/norm/inline_funcs.go` line 423 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-NTQX_Ev8gqbLL54XsOf:-NTQX_Ev8gqbLL54XsOg:b-tsoxvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/107bb759f15cf2db20a9e6860b93b9da1cbf896b/pkg/sql/opt/norm/inline_funcs.go#L423)):*
> ```Go
> // it and it's arguments non-volatile. So, if UDFs can be inlined in some other
> // way, or the subquery can be eliminated with normalization rules, we may be
> // able to inline volatile UDFs.
> ```

We should add to this comment that if (1) is loosened, then we need to reevaluate the usage of the CASE statement for the strict case, since as you mentioned in the commit message the subqueries may be eagerly evaluated.
___
*[`pkg/sql/opt/norm/testdata/rules/inline` line 1223 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-NTQ_ETpATpQf7fqiHkA:-NTQ_ETpATpQf7fqiHkB:b-l68go8) ([raw file](https://github.com/cockroachdb/cockroach/blob/107bb759f15cf2db20a9e6860b93b9da1cbf896b/pkg/sql/opt/norm/testdata/rules/inline#L1223)):*
> ```
>                      └── (column1:1 + 1,)
> 
> # A strict non-set-returning UDF used as a datasource is inlined.
> ```

I still don't think we'll be able to inline UDFs that are data sources because subqueries can only return 1 column, but I'll deal with that in that PR. This is ok given the current UDF behavior.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice fix! I agree with Rachael that this seems low-risk enough to backport.

> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-:-NTR77M16I4ORsKwYFy9:b5vwzpg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-NTQs7SOAAIOt1C9Kf8-):*
[nit] `has been fix` -> `has been fixed`
___
*[`-- commits` line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-NTR4OKZBeOVbS8C0yMW):*
We only wrap in the case expression when there are arguments, so won't the subquery always be correlated?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101867)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`-- commits` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-NTQs7SOAAIOt1C9Kf8-):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `has been fix` -> `has been fixed`
</blockquote></details>

Done.
___
*[`-- commits` line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-NTR4OKZBeOVbS8C0yMW):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

We only wrap in the case expression when there are arguments, so won't the subquery always be correlated?
</blockquote></details>

Good point... I've removed this paragraph.
___
*[`pkg/sql/opt/norm/inline_funcs.go` line 423 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-NTQX_Ev8gqbLL54XsOf:-NTUBPE6DhGGpn3E4yKQ:bb7djdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/107bb759f15cf2db20a9e6860b93b9da1cbf896b/pkg/sql/opt/norm/inline_funcs.go#L423)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

We should add to this comment that if (1) is loosened, then we need to reevaluate the usage of the CASE statement for the strict case, since as you mentioned in the commit message the subqueries may be eagerly evaluated.
</blockquote></details>

I've removed that paragraph from the commit message because it was incorrect. Let me know if you think I should still change something here.
___
*[`pkg/sql/opt/norm/testdata/rules/inline` line 1223 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-NTQ_ETpATpQf7fqiHkA:-NTUAxLH2gXVazrm0Ndc:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/107bb759f15cf2db20a9e6860b93b9da1cbf896b/pkg/sql/opt/norm/testdata/rules/inline#L1223)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I still don't think we'll be able to inline UDFs that are data sources because subqueries can only return 1 column, but I'll deal with that in that PR. This is ok given the current UDF behavior.
</blockquote></details>

:+1:

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101867#-:-NTUTyLB7nn11qyL0f0N:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
