### PR TITLE
kvserver: port TestRaftCheckQuorum to use leader leases  

### PR DESCRIPTION
**Pull request by arulajmani**
Epic: none

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Nice!

> Reviewed 2 of 2 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-:-OAIxIch4YD-TsacAydg:b-83sjoh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @nameisbhaskar, and @vidit-bhat)

___
*[`pkg/kv/kvserver/store.go` line 1169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAIvTORE4Aq2Gns113i:-OAIvTORE4Aq2Gns113j:b14oivn) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b7b626fc91db14ee61fb1b79e2f17690c9742f/pkg/kv/kvserver/store.go#L1169)):*
> ```Go
> 
> 	StoreLivenessTransport      *storeliveness.Transport
> 	StoreLivenessSupportManager *storeliveness.SupportManager
> ```

Is this part of the diff still needed?
___
*[`pkg/kv/kvserver/storeliveness/unreliable_store_liveness_handler.go` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAIvhPR8mDy1F04nLBC:-OAIvhPR8mDy1F04nLBD:bw6r9ob) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b7b626fc91db14ee61fb1b79e2f17690c9742f/pkg/kv/kvserver/storeliveness/unreliable_store_liveness_handler.go#L20)):*
> the specified storeID

This comment needs to be updated.
___
*[`pkg/testutils/testcluster/testcluster.go` line 1149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAIvmwm1Qbf7_uIWncz:-OAIvmwm1Qbf7_uIWnd-:b-5j8tkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b7b626fc91db14ee61fb1b79e2f17690c9742f/pkg/testutils/testcluster/testcluster.go#L1149)):*
> ```Go
> }
> 
> func (tc *TestCluster) WaitForLeaseUpgradeToLeaderLease(
> ```

Is `WaitForLeaseUpgrade` not enough? We could get rid of the `require.Equal(t, int64(1), l.Epoch)`. The point is just to wait until the lease is no longer expiration-based.
___
*[`pkg/kv/kvserver/client_raft_helpers_test.go` line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAIwZC676j2enKoxo4L:-OAIwZC676j2enKoxo4M:bhdjhf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b7b626fc91db14ee61fb1b79e2f17690c9742f/pkg/kv/kvserver/client_raft_helpers_test.go#L440)):*
> ```Go
> 		rep, ok := desc.GetReplicaDescriptorByID(id)
> 		if !ok {
> 			t.Fatal("replica not found in range descriptor")
> ```

nit: want to print the descriptor and storeID in this message?

**Review by arulajmani — COMMENTED** [review]
Thanks, RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-:-OAJGLRX7DayChltH0AV:bruwovn)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nameisbhaskar, @nvanbenschoten, and @vidit-bhat)

___
*[`pkg/kv/kvserver/store.go` line 1169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAIvTORE4Aq2Gns113i:-OAJECCa-w2xawHpY-Vp:bscuzze) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b7b626fc91db14ee61fb1b79e2f17690c9742f/pkg/kv/kvserver/store.go#L1169)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this part of the diff still needed?
</blockquote></details>

No, not after `TestingStoreLivenessMessageHandler`. Thanks for the catch.
___
*[`pkg/kv/kvserver/storeliveness/unreliable_store_liveness_handler.go` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAIvhPR8mDy1F04nLBC:-OAJEbmP0EiMhdh-91zN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b7b626fc91db14ee61fb1b79e2f17690c9742f/pkg/kv/kvserver/storeliveness/unreliable_store_liveness_handler.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> the specified storeID

This comment needs to be updated.
</blockquote></details>

Done.
___
*[`pkg/testutils/testcluster/testcluster.go` line 1149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAIvmwm1Qbf7_uIWncz:-OAJFHxJ0Np9Qz9-VXBt:b-xltnq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b7b626fc91db14ee61fb1b79e2f17690c9742f/pkg/testutils/testcluster/testcluster.go#L1149)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is `WaitForLeaseUpgrade` not enough? We could get rid of the `require.Equal(t, int64(1), l.Epoch)`. The point is just to wait until the lease is no longer expiration-based.
</blockquote></details>

It was the `require.Equal(t, int64(1), l.Epoch)` bit; fixed.
___
*[`pkg/kv/kvserver/client_raft_helpers_test.go` line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAIwZC676j2enKoxo4L:-OAJGDgoE1I7milfXMgq:b14wn6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b7b626fc91db14ee61fb1b79e2f17690c9742f/pkg/kv/kvserver/client_raft_helpers_test.go#L440)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: want to print the descriptor and storeID in this message?
</blockquote></details>

I think you meant replicaID, not storeID, right?

**Review by nvb — COMMENTED** [review]
> Reviewed 13 of 13 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133499)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @nameisbhaskar, and @vidit-bhat)

___
*[`go.mod` line 251 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAJKBgu4BG7PuL0LQjc:-OAJKBgu4BG7PuL0LQjd:b-jzubxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bed401e1843727b4087d40893e869d0d4a3a8736/go.mod#L251)):*
> ```XML
> 	go.opentelemetry.io/otel/trace v1.17.0
> 	go.opentelemetry.io/proto/otlp v0.11.0
> 	go.uber.org/atomic v1.10.0
> ```

Looks like we're using the wrong "atomic" package in `client_raft_test_epoch_leases.go`.
___
*[`pkg/kv/kvserver/store.go` line 1169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAIvTORE4Aq2Gns113i:-OAJKRL22rY0LoxCSIlW:bp1kary) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b7b626fc91db14ee61fb1b79e2f17690c9742f/pkg/kv/kvserver/store.go#L1169)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

No, not after `TestingStoreLivenessMessageHandler`. Thanks for the catch.
</blockquote></details>

Mind removing the rest of the diff around here. Just removing the newlines and gofmt.

**Review by arulajmani — COMMENTED** [review]
A bit puzzled by the TestStaticCheck failures here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-:-OAJmnMo8GLrHNtEE746:b6rmyli)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nameisbhaskar, @nvanbenschoten, and @vidit-bhat)

___
*[`pkg/kv/kvserver/store.go` line 1169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAIvTORE4Aq2Gns113i:-OAJmT6c1P7-bmmMWix4:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/75b7b626fc91db14ee61fb1b79e2f17690c9742f/pkg/kv/kvserver/store.go#L1169)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Mind removing the rest of the diff around here. Just removing the newlines and gofmt.
</blockquote></details>

Done. 
___
*[`go.mod` line 251 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAJKBgu4BG7PuL0LQjc:-OAJmUlq47DuqDdSApeJ:b-lx4fj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bed401e1843727b4087d40893e869d0d4a3a8736/go.mod#L251)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like we're using the wrong "atomic" package in `client_raft_test_epoch_leases.go`.
</blockquote></details>

Fixed.

**Review by nvb — COMMENTED** [review]
> Reviewed 13 of 14 files at r5, 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133499)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @nameisbhaskar, and @vidit-bhat)

___
*[`go.mod` line 251 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-OAJKBgu4BG7PuL0LQjc:-OAJqBt_0r2ni5b0IAj_:b-z5si2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/bed401e1843727b4087d40893e869d0d4a3a8736/go.mod#L251)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Can we gen this file in the first commit so that there's no diff in `go.mod` in either of these commits?

**Comment by arulajmani** [comment]
🤞

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133499#-:-OANnDeRANq5CDsD9xCs:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @nameisbhaskar, and @vidit-bhat)

**Comment by arulajmani** [comment]
Thanks!

bors r=nvanbenschoten

**Pull request merged**
