### PR TITLE
 changfeedccl: Support filter over primary key span.

### PR DESCRIPTION
**Pull request by miretskiy**
Extend changfeeds to support a filtering expression over primary key
span via `primary_key_filter` option.

When specified, this option is treated as an SQL filter expression
over primary key columns.  This filter can then be used to constrain
the spans that's watched by changefeed only to those that satisfy
the expression.  The use of this filter restricted only to the
changefeeds over a single table.

Release Notes (enterprise change): `primary_filter_filter` option can be used
to restrict the span watched by changefeed only to the portion that
satisfies the filtering predicate.

### CODE REVIEW

**Review by HonoreDB — COMMENTED** [review]
Very cool! I like this iterative approach. Product question, but maybe this should just be "WHERE" and the not implemented error is "where clauses for changefeeds currently must be satisfiable using only primary key values"?

Also, reiterating what I said in a line comment: this should be part of a ChangefeedTargetSpecification, not a WITH option. It doesn't look like this would complicate the code at all, and this is semantically the same type of thing as a family (in fact, at the KV level a family kind of is a primary key constraint).

> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 3 of 3 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0XC76wBRWIikKfLAd6:b-askgz9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @HonoreDB, and @miretskiy)

___
*[`-- commits` line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0XIUvR8QYPvRZkN7XH):*
`primary_key_filter`
___
*[`pkg/ccl/changefeedccl/alter_changefeed_stmt.go` line 674 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0XBXnlEOljw1ysDHjr:-N0XBXnlEOljw1ysDHjs:bnqapwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f5c5deb01b9911f410bb2616bba00fb85a94c8b/pkg/ccl/changefeedccl/alter_changefeed_stmt.go#L674)):*
> ```Go
> 
> 	for _, d := range descs {
> 		primarySpans = append(primarySpans, d.(catalog.TableDescriptor).PrimaryIndexSpan(p.ExtendedEvalContext().Codec))
> ```

Should de-duplicate here.
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0X8y2EDe-qlQO44N1Q:-N0X8y2EDe-qlQO44N1R:b-35ecta) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f5c5deb01b9911f410bb2616bba00fb85a94c8b/pkg/ccl/changefeedccl/changefeed_dist.go#L123)):*
> ```Go
> 		}
> 
> 		if filterExpr, isSet := details.Opts[changefeedbase.OptPrimaryKeyFilter]; isSet {
> ```

Does it simplify anything other than syntax to have this restriction? I'd think we could do

`CREATE CHANGEFEED FOR TABLE foo [FAMILY fname] [WHERE expr], TABLE baz [FAMILY fname] [WHERE expr]` and have the predicate be part of the ChangefeedTargetSpecification rather than a global option. In fact I'd argue for this syntax anyway. It's more extendable into the multi-target case later, and makes it clearer that we're not doing joins.
___
*[`pkg/sql/constraint.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0X7HKg0CXpdiEct6Le:-N0X7HKg0CXpdiEct6Lf:b-s6uuch) ([raw file](https://github.com/cockroachdb/cockroach/blob/584f34adc62d621c034c80fdd2ca802e2e992979/pkg/sql/constraint.go#L112)):*
> ```Go
> 
> 	if ic.Constraint().IsContradiction() {
> 		return nil, errors.Newf("filter %q is a contradiction", filter)
> ```

Maybe also error on tautologies more complicated than "true"? Like `if .IsUnconstrained() return nil, errors.Newf("filter %q is vacuous, use 'true' or omit constraint for the full table")`.

**Review by miretskiy — COMMENTED** [review]
Answer to the above question inline.  Let me know what you think

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0XXZKmEQO08wEaAh9S:b-hgkc90)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, and @HonoreDB)

___
*[`-- commits` line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0XIUvR8QYPvRZkN7XH):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

`primary_key_filter`
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/alter_changefeed_stmt.go` line 674 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0XBXnlEOljw1ysDHjr:-N0XQSu48G9nzhJDVnDI:bqm4n50) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f5c5deb01b9911f410bb2616bba00fb85a94c8b/pkg/ccl/changefeedccl/alter_changefeed_stmt.go#L674)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Should de-duplicate here.
</blockquote></details>

Hmm... Good point; also, bunch of no longer needed arguments removed.
___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0X8y2EDe-qlQO44N1Q:-N0XQsctEKsgpv_4uxTd:b-7b2z2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f5c5deb01b9911f410bb2616bba00fb85a94c8b/pkg/ccl/changefeedccl/changefeed_dist.go#L123)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Does it simplify anything other than syntax to have this restriction? I'd think we could do

`CREATE CHANGEFEED FOR TABLE foo [FAMILY fname] [WHERE expr], TABLE baz [FAMILY fname] [WHERE expr]` and have the predicate be part of the ChangefeedTargetSpecification rather than a global option. In fact I'd argue for this syntax anyway. It's more extendable into the multi-target case later, and makes it clearer that we're not doing joins.
</blockquote></details>

I agree that we could do this; I have chosen not to at this point.  Here is why:

The reasons is that... walk before run approach.  I honestly don't know yet, how multiple where
clauses would play out.  I eliminated the possibility of multiple tables almost immediately.
The code doesn't have any support for scoping or aliasing (yet) -- so, these expressions would necessarily
need to get more complex -- something I wanted to avoid at least initially.

The second option, is to have where clause as you have it -- per family.  At this point, it's not clear to me
why you'd want to have the same changefeed, over multiple families, each with different clause?  Perhaps it makes sense; but it just wasn't clear to me at this point.

Finally, and perhaps more importantly, I want to leave the full "where" clause support until later -- when we have full predicate/filtering support.  We don't have a full picture yet of what we would want to support.
For example, where clause allow sub-selects -- and it's a question if we should/should not.
Regardless, putting in a full where clause now would make it hard to take back later -- so I wanted to postpone
this decision until we get a better picture.

To be clear, and to re-iterate, I don't think what you propose is a bad idea.  It's just that I'm afraid to commit
right now.
___
*[`pkg/sql/constraint.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0X7HKg0CXpdiEct6Le:-N0XXUW5EHIfV7QE_UUT:b-laxiwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/584f34adc62d621c034c80fdd2ca802e2e992979/pkg/sql/constraint.go#L112)):*
> filter %q is vacuous
Good idea; added this check + expanded unit tests.

**Review by HonoreDB — COMMENTED** [review]
Responded inline. Also, what happens on schema changes? Could just call validatePrimaryKeyFilterExpression in the ValidateTargets method the schema feed calls, I think.

> Reviewed 2 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0XjfBi4laSbPdo2RUC:b-5y2bw5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @HonoreDB, and @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0X8y2EDe-qlQO44N1Q:-N0X_yyiDh6iqgaFogKF:bo94xgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f5c5deb01b9911f410bb2616bba00fb85a94c8b/pkg/ccl/changefeedccl/changefeed_dist.go#L123)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I agree that we could do this; I have chosen not to at this point.  Here is why:

The reasons is that... walk before run approach.  I honestly don't know yet, how multiple where
clauses would play out.  I eliminated the possibility of multiple tables almost immediately.
The code doesn't have any support for scoping or aliasing (yet) -- so, these expressions would necessarily
need to get more complex -- something I wanted to avoid at least initially.

The second option, is to have where clause as you have it -- per family.  At this point, it's not clear to me
why you'd want to have the same changefeed, over multiple families, each with different clause?  Perhaps it makes sense; but it just wasn't clear to me at this point.

Finally, and perhaps more importantly, I want to leave the full "where" clause support until later -- when we have full predicate/filtering support.  We don't have a full picture yet of what we would want to support.
For example, where clause allow sub-selects -- and it's a question if we should/should not.
Regardless, putting in a full where clause now would make it hard to take back later -- so I wanted to postpone
this decision until we get a better picture.

To be clear, and to re-iterate, I don't think what you propose is a bad idea.  It's just that I'm afraid to commit
right now.
</blockquote></details>

I agree that having a global predicate over all tables would add complexity. Whether we should call this "primary_key_filter" or "where" is a product question; I'm weakly in favor of "where" but I agree that will create inexorable pressure toward more and more predicate support.

What I feel more strongly about is that the syntax should be per target, not a with option. Your `ConstrainPrimaryIndexSpanByExpr` method already works for this--it takes a table desc and an expr, validates that the expr can be evaluated using only the primary key columns of the table desc, and returns a set of spans. It doesn't need to know if it's being called for multiple tables, each with their own expr. And downstream we're just passing spans, right?

I don't know of a specific use case for having different predicates per family, but different predicates per table in a multi-table feed seems guaranteed to be a request.

**Comment by miretskiy** [comment]
How would you specify this? As a per target string?
At any rate, there was at least initially, a question whether something
like this could be backported.
With sql.y changes -- that sort of closes the door for this.

**Comment by miretskiy** [comment]
> What I feel more strongly about is that the syntax should be per target, not a with option. Your ConstrainPrimaryIndexSpanByExpr method already works for this

I understand the sentiment.  And I also understand that ConstrainPrimaryIndexSpanByExpr would work fine.
I would like to postpone this, nonetheless, for the following additional reasons:
  1. Editing sql.y would almost certainly doom possibility of backport (not a strong reason, but a reason nonetheless).
  2. Most importantly: currently, targets are defined as TABLE x FAMILY y.  To extend it to support arbitrary clauses is a significant departure from existing syntax.  One so significant, that it probably ought to be tacked on its own.
  3.  Not only that, putting WITH clause, and having potential multiple with clause is not w/out pitfalls (i.e. it might produce ambiguous grammas).  
  4. I want to delay this until full predicates.  Basically, with full predicate demo, I feel that the changefeed statement stopped looking like an one-off bespoke system, and became more sql-y looking.  It's a good thing.  I have not had a chance to try extending this to support per family clauses.  However, what I would really like is not to make things worse and more confusing.  If there is a way to build a new sql statement that looks and behaves like a regular SQL -- i'd love to give it a try.
  5. Finally, this option going in as is, does not preclude changing it.  We still have 6 months or so before 22.2

**Review by sherman-grewal — COMMENTED** [review]
Just caught up on this thread, another benefit with using an option over editing the SQL syntax is that the ALTER CHANGEFEED statement would work with this option without having to make any major changes. That being said, I do see the benefits of editing the syntax instead of introducing a new option.

On that note, have you tested that changefeeds will filter when a user introduces the option through ALTER CHANGEFEED? Perhaps this change warrants a test added to `alter_changefeed_test.go`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0bRkzd50zS3hPJpiiU:b-qlxk5h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @HonoreDB, @miretskiy, and @rytaft)

**Review by mgartner — COMMENTED** [review]
> Also, what happens on schema changes?

I'm also curious how schema changes will be handled, especially PK changes.

> Reviewed 2 of 5 files at r2, 1 of 3 files at r3, 7 of 7 files at r6, 4 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0fYsJ54O9MFQ-RwokX:b-lfvsl5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @miretskiy, and @rytaft)

___
*[`pkg/sql/constraint_test.go` line 62 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0fXtW07bITsE7gHAz5:-N0fXtW07bITsE7gHAz6:b-d9vpcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d56fdce75c99dbb7c7942b4994c24b45940bf4/pkg/sql/constraint_test.go#L62)):*
> ```Go
> 
> 	sqlDB := sqlutils.MakeSQLRunner(db)
> 	sqlDB.Exec(t, `CREATE TABLE foo (a INT, b int, c STRING, CONSTRAINT "pk" PRIMARY KEY (a, b))`)
> ```

nit: might not hurt to throw a secondary index on `c` and test that something like `c = 10` doesn't produce any spans.

Another "fun" test would be filters that reduce to simpler spans, like `a > 10 AND a > 5` and `a > 10 OR a > 5`.

**Review by sherman-grewal — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 1 of 3 files at r3, 7 of 7 files at r6, 4 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @miretskiy, and @rytaft)

___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 198 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0fdzNdCte9KA58xEHY:-N0fdzNe0RezikgQMcX1:bd4fd1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f3c010da35a16a41c45c1967270d813cd2f63ef/pkg/ccl/changefeedccl/changefeed_dist.go#L198)):*
> ```Go
> 	ctx context.Context, execCtx sql.JobExecContext, filterStr string, descr catalog.TableDescriptor,
> ) ([]roachpb.Span, error) {
> 	if filterStr == "" {
> ```

Nit: Can we move these validations to `validateDetails`? That way we can catch these invalid options when a user tries to perform a CREATE/ALTER changefeed statement (instead of when the changefeed starts to run).

Also extend `TestChangefeedErrors` to include examples of invalid filter statements.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @miretskiy, @rytaft, and @sherman-grewal)

___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 198 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0fdzNdCte9KA58xEHY:-N0fiKi3ERfF4w4ViEM0:bcxgrp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f3c010da35a16a41c45c1967270d813cd2f63ef/pkg/ccl/changefeedccl/changefeed_dist.go#L198)):*
<details><summary><i>Previously, sherman-grewal (Sherman) wrote…</i></summary><blockquote>

Nit: Can we move these validations to `validateDetails`? That way we can catch these invalid options when a user tries to perform a CREATE/ALTER changefeed statement (instead of when the changefeed starts to run).
</blockquote></details>

I tried doing this (i..e have the entire validation inside validateDetails).  But that resulted in duplicated code when I actually need to compute constrained spans -- something I didn't really like.  So, I wound up with this function which only does the  handling of the span constraints; and then validation helper built on top (that deals with empty string values, etc).  I hope it's okay by you.

**Review by miretskiy — COMMENTED** [review]
> I'm also curious how schema changes will be handled, especially PK changes.

@mgartner  currently the story is: changefeed will fail when this happens.

I think we will have to work harder in the upcoming release to make sure we can detect and prevent some of those
schema changes (for example, by having chagnefeeds have descriptors, so that schema changes can return an indication to the end user that their schema change may break the changefeed).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0fjFD94sqgmd2H_PuD:b-1vrrzo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @mgartner, @miretskiy, @rytaft, and @sherman-grewal)

___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 198 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0fdzNdCte9KA58xEHY:-N0ftuO35FzK2JV0JZds:bvxh3r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f3c010da35a16a41c45c1967270d813cd2f63ef/pkg/ccl/changefeedccl/changefeed_dist.go#L198)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I tried doing this (i..e have the entire validation inside validateDetails).  But that resulted in duplicated code when I actually need to compute constrained spans -- something I didn't really like.  So, I wound up with this function which only does the  handling of the span constraints; and then validation helper built on top (that deals with empty string values, etc).  I hope it's okay by you.
</blockquote></details>

Also, a bit more reason: to validate expression, I need access to planner, and target descriptors; something validate details doesn't have.  However, the call to validate filter happens when you create jobs record, so, alter statement gets this validation.

I have added a test where you try to alter with invalid expression.
___
*[`pkg/sql/constraint_test.go` line 62 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0fXtW07bITsE7gHAz5:-N0fjczB2jVckuB9OBXx:bw0v07h) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d56fdce75c99dbb7c7942b4994c24b45940bf4/pkg/sql/constraint_test.go#L62)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: might not hurt to throw a secondary index on `c` and test that something like `c = 10` doesn't produce any spans.

Another "fun" test would be filters that reduce to simpler spans, like `a > 10 AND a > 5` and `a > 10 OR a > 5`.
</blockquote></details>

Great idea.  Added.

**Review by mgartner — APPROVED** [review]
The optimizer-related code LGTM.

> Reviewed 13 of 13 files at r10, 8 of 8 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0gCN7PBj4qHu2zSFR9:bz1284o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @mgartner, @miretskiy, @rytaft, and @sherman-grewal)

**Review by HonoreDB — APPROVED** [review]
Just to be clear, my proposed syntax is about allowing multiple targets per changefeed. Families are just a special case of target. I would do `CREATE CHANGEFEED FOR TABLE riders WHERE id = 5, TABLE drivers WHERE id IN (5,10), TABLE accounts`, and add a predicate string to ChangefeedTargetSpecification. If that causes parsing ambiguity there could be parentheses or quotes or something. But I get the argument that adding a parsing change is harder to backport or change later, adding a WITH option is lighter weight. Not a blocker by any means. Code LGTM, modulo a schema change test.

> Reviewed 4 of 13 files at r10, 9 of 9 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0hEO7A53GnZCnyDZR-:b-cfccar)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @HonoreDB, @mgartner, @miretskiy, @rytaft, and @sherman-grewal)

**Review by rytaft — APPROVED** [review]
Optimizer stuff also :lgtm: mod one question and a few nits

> Reviewed 4 of 13 files at r10, 9 of 9 files at r12, 9 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0kQNy210pFA7IOKr9g:bsirik5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @mgartner, @miretskiy, and @sherman-grewal)

___
*[`pkg/sql/constraint.go` line 38 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0kLhHa03TWPoxa8mpo:-N0kLhHa03TWPoxa8mpp:b-s0lmyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9820dd5b24e5e4f50fa6dcc68a2831562c92f/pkg/sql/constraint.go#L38)):*
> ```Go
> 	// Expression is required to specify constraints over unqualified primary key columns only.
> 	// The expression must evaluate to a boolean value.
> 	// If the expression is a contradiction, returns an error.
> ```

nit: limit comments to <= 80 columns wide
___
*[`pkg/sql/constraint.go` line 49 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0kP8_z7YzWFJnSjUCm:-N0kP8_z7YzWFJnSjUCn:b-jpmnl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9820dd5b24e5e4f50fa6dcc68a2831562c92f/pkg/sql/constraint.go#L49)):*
> ```Go
> 
> // ConstrainPrimaryIndexSpanByExpr implements SpanConstrainer
> func (p *planner) ConstrainPrimaryIndexSpanByExpr(
> ```

Cool! Exciting to see that `ScalarBuilder` etc. worked so well for this use case :)
___
*[`pkg/sql/constraint.go` line 60 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0kMCy59I35MfJNjFP1:-N0kMCy59I35MfJNjFP2:bh2krkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9820dd5b24e5e4f50fa6dcc68a2831562c92f/pkg/sql/constraint.go#L60)):*
> ```Go
> 	oc.reset()
> 
> 	tbl, err := newOptTable(desc, oc.codec(), nil /*stats */, emptyZoneConfig)
> ```

super nit: add a space after `/*`
___
*[`pkg/sql/constraint.go` line 77 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0kMccz-c_XZoRnB3qx:-N0kMccz-c_XZoRnB3qy:b-3ly7nz) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9820dd5b24e5e4f50fa6dcc68a2831562c92f/pkg/sql/constraint.go#L77)):*
> ```Go
> 	if root.DataType() != types.Bool {
> 		return nil, errors.AssertionFailedf(
> 			"expected boolean expression, found expression of type %s", root.DataType())
> ```

Should this be an assertion failure? What if the user passes a non-boolean expression?
___
*[`pkg/sql/constraint.go` line 95 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0kO4e33Q5yTZMYScev:-N0kO4e33Q5yTZMYScew:b6kt5su) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9820dd5b24e5e4f50fa6dcc68a2831562c92f/pkg/sql/constraint.go#L95)):*
> ```Go
> 	var notNullIndexCols opt.ColSet
> 	for i, colID := range primary.IndexDesc().KeyColumnIDs {
> 		indexCols[i] = opt.OrderingColumn(colID)
> ```

nit: you're doing this twice -- I think you can just remove this line

**Review by sherman-grewal — APPROVED** [review]
LGTM, great work on this!! :raised_hands: 

> Reviewed 4 of 13 files at r10, 9 of 9 files at r12, 9 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0kXf4tDOylYfNezQQY:bhrnoct)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @mgartner, and @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_dist.go` line 198 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0fdzNdCte9KA58xEHY:-N0kXQEM5ni2oeaHmxIe:bdtxh3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f3c010da35a16a41c45c1967270d813cd2f63ef/pkg/ccl/changefeedccl/changefeed_dist.go#L198)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Also, a bit more reason: to validate expression, I need access to planner, and target descriptors; something validate details doesn't have.  However, the call to validate filter happens when you create jobs record, so, alter statement gets this validation.

I have added a test where you try to alter with invalid expression.
</blockquote></details>

ahhh ok, thanks for sharing. the new changes look great to me!

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @mgartner, @miretskiy, and @rytaft)

___
*[`pkg/sql/constraint.go` line 49 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0kP8_z7YzWFJnSjUCm:-N0krG6v8JMA2Gdi5byC:bb6sh25) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9820dd5b24e5e4f50fa6dcc68a2831562c92f/pkg/sql/constraint.go#L49)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Cool! Exciting to see that `ScalarBuilder` etc. worked so well for this use case :)
</blockquote></details>

Ack!
___
*[`pkg/sql/constraint.go` line 77 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0kMccz-c_XZoRnB3qx:-N0krJzN5ybccSF41N0y:b-tfr58b) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9820dd5b24e5e4f50fa6dcc68a2831562c92f/pkg/sql/constraint.go#L77)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Should this be an assertion failure? What if the user passes a non-boolean expression?
</blockquote></details>

I think it is an assertion failure.  Callers also assume it's... basically a where clause.
Does any other type make sense?
___
*[`pkg/sql/constraint.go` line 95 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0kO4e33Q5yTZMYScev:-N0krVfsCFVSjJiGrn5l:b-har60n) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9820dd5b24e5e4f50fa6dcc68a2831562c92f/pkg/sql/constraint.go#L95)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: you're doing this twice -- I think you can just remove this line
</blockquote></details>

Ahh.. Sorry, good catch -- it's a leftover where I tried to "x *= -1" but that didn't work, so I switched
to if/else, and forgot to remove this line.  Thanks.

**Review by rytaft — COMMENTED** [review]
> Reviewed 10 of 10 files at r14, 9 of 9 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @gh-casper, @mgartner, and @miretskiy)

___
*[`pkg/sql/constraint.go` line 77 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-N0kMccz-c_XZoRnB3qx:-N0kuYiQ9ZBAO4wJQgev:b-4je8yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9820dd5b24e5e4f50fa6dcc68a2831562c92f/pkg/sql/constraint.go#L77)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think it is an assertion failure.  Callers also assume it's... basically a where clause.
Does any other type make sense?
</blockquote></details>

Well if we know that a user can trigger this error message, then it shouldn't be an assertion. Assertion failures should be reserved for things that indicate we have a bug in the database. If we hit this error, it will cause a sentry failure, GitHub issue to be opened, etc. I would think it should just be a normal error like you have below (`errors.Newf`, etc).

Are you already checking elsewhere that it's a boolean expression?

**Comment by miretskiy** [comment]
> Well if we know that a user can trigger this error message, then it shouldn't be an assertion. Assertion failures should be reserved for things that indicate we have a bug in the database. If we hit this error, it will cause a sentry failure, GitHub issue to be opened, etc. I would think it should just be a normal error like you have below (errors.Newf, etc).

I could try replacing it with pgerror of some sort.

> Are you already checking elsewhere that it's a boolean expression?
No; just the expectation that it will be a boolean expression.  I'm going to switch error message.

**Comment by rytaft** [comment]
yea pgerror 22023 `InvalidParameterValue` or something is probably good

**Comment by miretskiy** [comment]
I did `return nil, pgerror.Newf(pgcode.DatatypeMismatch,
			"expected boolean expression, found expression of type %s", root.DataType())`
@rytaft looks reasonable?

**Review by rytaft — APPROVED** [review]
:lgtm: thanks!

> Reviewed 10 of 10 files at r16, 9 of 9 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80499#-:-N0lJOwk61KbeUl3lOyi:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @gh-casper, @mgartner, and @miretskiy)

**Comment by miretskiy** [comment]
@HonoreDB as discussed offline: I added a check (and updated tests) to ensure that schema change policy set to "stop" when using primary key filter option.

**Pull request merged**
