### PR TITLE
storage: misc fixes after excise cluster setting addition

### PR DESCRIPTION
**Pull request by itsbilal**
This change addresses some follow-up code review points from #111437. One of these was to update a cluster setting's description to better reflect its interaction with another cluster setting, and another is to address one missing guard in cluster versions when ratcheting forward.

Epic: none

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111678)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 507 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111678#-NfrM16-7YBDDZgdc4Y7:-NfrM16-7YBDDZgdc4Y8:b33ht8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dbc08041c6e73730b902dab8e5c3f78f7ff7b9f/pkg/kv/kvserver/store_snapshot.go#L507)):*
> ```Go
> 	keyRanges := rditer.MakeReplicatedKeySpans(header.State.Desc)
> 
> 	// NB: V23_2_StmtDiagForPlanGist is one after V23_2_PebbleFormatVirtualSSTables
> ```

This is ugly.. If I understand correctly, we should have reserved 2 versions?

I would add a const `V23_2_PebbleFormatVirtualSSTablesDone` (or whatever) in `clusterversion` and make it equal to `V23_2_PebbleFormatVirtualSSTables + 1` and explain in the comment why it's defined like this (we didn't want to shift the keys). Though I don't think shifting the 23_2 keys should be a problem. Or if we can define it at the end, that'd be better too.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111678)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 507 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111678#-NfrM16-7YBDDZgdc4Y7:-NfvDPQW5hQgPuFzFs7A:b5wap13) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dbc08041c6e73730b902dab8e5c3f78f7ff7b9f/pkg/kv/kvserver/store_snapshot.go#L507)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is ugly.. If I understand correctly, we should have reserved 2 versions?

I would add a const `V23_2_PebbleFormatVirtualSSTablesDone` (or whatever) in `clusterversion` and make it equal to `V23_2_PebbleFormatVirtualSSTables + 1` and explain in the comment why it's defined like this (we didn't want to shift the keys). Though I don't think shifting the 23_2 keys should be a problem. Or if we can define it at the end, that'd be better too.
</blockquote></details>

I could define it at the end but I prefer the alias approach a little more, so that's what I did. @jbowens what do you think?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111678)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @RaduBerinde)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 507 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111678#-NfrM16-7YBDDZgdc4Y7:-NfvUirw3ddCeTDedUMz:b9k2myk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dbc08041c6e73730b902dab8e5c3f78f7ff7b9f/pkg/kv/kvserver/store_snapshot.go#L507)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I could define it at the end but I prefer the alias approach a little more, so that's what I did. @jbowens what do you think?
</blockquote></details>

I do think a separate cluster version is preferable so that each new cluster version is only enabling 1 new piece of functionality.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111678)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @RaduBerinde)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 507 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111678#-NfrM16-7YBDDZgdc4Y7:-Nfvl1V5CntzbSbqBR0Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dbc08041c6e73730b902dab8e5c3f78f7ff7b9f/pkg/kv/kvserver/store_snapshot.go#L507)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I do think a separate cluster version is preferable so that each new cluster version is only enabling 1 new piece of functionality.
</blockquote></details>

Done.

**Review by jbowens — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111678#-:-NfwEJeo87zMrPq8qvIK:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by itsbilal** [comment]
TFTR!

bors r=jbowens

**Pull request merged**
