### PR TITLE
upgrades: delete V22_2SystemPrivilegesTable upgrade and version gates

### PR DESCRIPTION
**Pull request by andyyang890**
This patch deletes the `V22_2SystemPrivilegesTable` upgrade since its
associated unit test starts to fail when the bootstrap schema for the
`system.privileges` table is updated. This is safe to do since the
release engineering team has previously stated they will bump
`binaryMinSupportedVersion` before cutting the branch for 23.1.

Epic: None

Release note: None

### CODE REVIEW

**Review by ecwall — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @dt, @rafiss, and @rhu713)

___
*[`pkg/ccl/backupccl/restore_planning.go` line 1236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJ7QVDN6X8u7jGWgjvx:-NJ7QVDN6X8u7jGWgjvy:b-fp6gy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d78a524c5e505b5db5b0f4c926f98dc72ed4d/pkg/ccl/backupccl/restore_planning.go#L1236)):*
> ```Go
> 		) == nil
> 
> 		if requiresRestoreSystemPrivilege && hasRestoreSystemPrivilege {
> ```

This isn't the part you changed, but this conditional seems kind of strange. I think it is easier to read as this to be more consistent with other code
```
if requiresRestoreSystemPrivilege {
  if err := p.CheckPrivilegeForUser(
    ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.RESTORE, p.User()
  ); err != nil {
    return pgerror.Newf(pgcode.InsufficientPrivilege,
      "only users with the admin role or the RESTORE system privilege are allowed to perform"+
      " a cluster restore")
  }
  return checkRestoreDestinationPrivileges(ctx, p, from)
}
```
___
*[`pkg/ccl/backupccl/restore_planning.go` line 1258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJ7RxBR-S8wa4blKXQC:-NJ7RxBR-S8wa4blKXQD:b-7u9ew6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d78a524c5e505b5db5b0f4c926f98dc72ed4d/pkg/ccl/backupccl/restore_planning.go#L1258)):*
> ```Go
> 	}
> 
> 	if hasRestoreSystemPrivilege {
> ```

`hasRestoreSystemPrivilege` isn't used anywhere else so `return checkRestoreDestinationPrivileges(ctx, p, from)` can be moved into `if len(restoreStmt.Targets.Databases) > 0 { ... }`.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @ecwall, @rafiss, and @rhu713)

___
*[`pkg/ccl/backupccl/restore_planning.go` line 1236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJ7QVDN6X8u7jGWgjvx:-NJ9TB851_i59oKAPble:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d78a524c5e505b5db5b0f4c926f98dc72ed4d/pkg/ccl/backupccl/restore_planning.go#L1236)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

This isn't the part you changed, but this conditional seems kind of strange. I think it is easier to read as this to be more consistent with other code
```
if requiresRestoreSystemPrivilege {
  if err := p.CheckPrivilegeForUser(
    ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.RESTORE, p.User()
  ); err != nil {
    return pgerror.Newf(pgcode.InsufficientPrivilege,
      "only users with the admin role or the RESTORE system privilege are allowed to perform"+
      " a cluster restore")
  }
  return checkRestoreDestinationPrivileges(ctx, p, from)
}
```
</blockquote></details>

Done.
___
*[`pkg/ccl/backupccl/restore_planning.go` line 1258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJ7RxBR-S8wa4blKXQC:-NJ9TBmt7u_xtG2S-CkP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03d78a524c5e505b5db5b0f4c926f98dc72ed4d/pkg/ccl/backupccl/restore_planning.go#L1258)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

`hasRestoreSystemPrivilege` isn't used anywhere else so `return checkRestoreDestinationPrivileges(ctx, p, from)` can be moved into `if len(restoreStmt.Targets.Databases) > 0 { ... }`.
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @dt, @ecwall, and @rhu713)

___
*[`pkg/ccl/backupccl/backup_planning.go` line 391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJBM3DeDGbs2X1VDnwn:-NJBM3DeDGbs2X1VDnwo:b-p384m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a59e57637827602ac175c89d21479f5db2dc054/pkg/ccl/backupccl/backup_planning.go#L391)):*
> ```Go
> 
> 		if requiresBackupSystemPrivilege {
> 			if p.CheckPrivilegeForUser(
> ```

nit: this part should be
```
			if err := p.CheckPrivilegeForUser(
				ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.BACKUP, p.User(),
			); err != nil {
				return pgerror.Wrapf(
					err,
					pgcode.InsufficientPrivilege,
					"only users with the admin role or the BACKUP system privilege are allowed to perform full cluster backups")
			}
```
___
*[`pkg/ccl/backupccl/restore_planning.go` line 1236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJBMXL903z296NDolu4:-NJBMXL903z296NDolu5:btgzb2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a59e57637827602ac175c89d21479f5db2dc054/pkg/ccl/backupccl/restore_planning.go#L1236)):*
> ```Go
> 				ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.RESTORE, p.User(),
> 			); err != nil {
> 				return pgerror.Newf(pgcode.InsufficientPrivilege,
> ```

nit: use pgerror.Wrapf
___
*[`pkg/ccl/backupccl/restore_planning.go` line 1251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJBMiaH65mk8-6zyFyo:-NJBMiaH65mk8-6zyFyp:b-dkqt73) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a59e57637827602ac175c89d21479f5db2dc054/pkg/ccl/backupccl/restore_planning.go#L1251)):*
> ```Go
> 	// options.
> 	if len(restoreStmt.Targets.Databases) > 0 &&
> 		p.CheckPrivilegeForUser(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.RESTORE, p.User()) == nil {
> ```

hm, we don't need to return the error here if it fails? perhaps check with the DR team
___
*[`pkg/sql/syntheticprivilege/README.md` line 345 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJBNA6MAN68-6Yu0n37:-NJBNA6MAN68-6Yu0n38:b-e5e3j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a59e57637827602ac175c89d21479f5db2dc054/pkg/sql/syntheticprivilege/README.md#L345)):*
> ```Markdown
> 				return err
> 			}
> 			if !hasModify && !hasView {
> ```

thanks for keeping the README up to date!

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @ecwall, @rafiss, and @rhu713)

___
*[`pkg/ccl/backupccl/backup_planning.go` line 391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJBM3DeDGbs2X1VDnwn:-NJBQqAA8epx-ZGWtFcJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a59e57637827602ac175c89d21479f5db2dc054/pkg/ccl/backupccl/backup_planning.go#L391)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this part should be
```
			if err := p.CheckPrivilegeForUser(
				ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.BACKUP, p.User(),
			); err != nil {
				return pgerror.Wrapf(
					err,
					pgcode.InsufficientPrivilege,
					"only users with the admin role or the BACKUP system privilege are allowed to perform full cluster backups")
			}
```
</blockquote></details>

Done.
___
*[`pkg/ccl/backupccl/restore_planning.go` line 1236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJBMXL903z296NDolu4:-NJBQvGt3NcTkChCctNp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a59e57637827602ac175c89d21479f5db2dc054/pkg/ccl/backupccl/restore_planning.go#L1236)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: use pgerror.Wrapf
</blockquote></details>

Done.
___
*[`pkg/ccl/backupccl/restore_planning.go` line 1251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJBMiaH65mk8-6zyFyo:-NJBR-0T4VkOijzn6RZs:bim2pwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a59e57637827602ac175c89d21479f5db2dc054/pkg/ccl/backupccl/restore_planning.go#L1251)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, we don't need to return the error here if it fails? perhaps check with the DR team
</blockquote></details>

Ok, will do.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @ecwall, @rafiss, and @rhu713)

___
*[`pkg/ccl/backupccl/restore_planning.go` line 1251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-NJBMiaH65mk8-6zyFyo:-NJGshWj6bHBRVUjz69u:b-oveshj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a59e57637827602ac175c89d21479f5db2dc054/pkg/ccl/backupccl/restore_planning.go#L1251)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Ok, will do.
</blockquote></details>

Talked to DR team on Slack and they're okay with filing an issue to fix that later. See https://github.com/cockroachdb/cockroach/issues/93630.

**Comment by andyyang890** [comment]
Hmmm something weird happened with the latest rebase, need to fix it before it's ready for review again

**Review by rafiss — APPROVED** [review]
thanks!

> Reviewed 14 of 21 files at r1, 1 of 2 files at r3, 5 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93281#-:-NJH_gsTCpOTckWkCirj:bd5l6mr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @dt, @ecwall, and @rhu713)

**Comment by andyyang890** [comment]
TFTR!

bors r=rafiss

**Pull request merged**
