### PR TITLE
storage: respect the marker in the leaked Raft entries migration

### PR DESCRIPTION
**Pull request by spencerkimball**
Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: but I'm confused. How was this still passing `TestStoreInitAndBootstrap`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31643#-:-LPChkXIDh7o6osNdlNR:bw4vvb9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by nvb — COMMENTED** [review]
Oh, we were just always running the migration, weren't we?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31643#-:-LPCiCly2lEsC_P9gUMV:bvevtyt)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by spencerkimball — COMMENTED** [review]
Yes, someone just forgot to remove a line probably added for local testing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31643#-:-LPCjXX45Njm6GCGXnyf:bq7knfi)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
> Yes, someone just forgot to remove a line probably added for local testing.

I wonder who that was.

Thanks for catching this. It deserves to be backported to 2.1.

**Pull request merged**
