### PR TITLE
sql: reject aggregate functions in GROUP BY.

### LINKED ISSUE #7034: Aggregate functions shouldn't be allowed in the GROUP BY clause.
Found by @dt and @knz pursuant of https://github.com/cockroachlabs/registration/issues/23: our SQL dialect currently allows grouping by an aggregate, which is not standard SQL and has dubious semantics. Probably we should outright disallow it.

e.g. `SELECT v, COUNT(DISTINCT w) FROM kv GROUP BY v, COUNT(DISTINCT w)` is currently accepted but doesn't make sense.

### PR DESCRIPTION
**Pull request by knz**
Fixes #7034.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7035)

### CODE REVIEW

**Comment by dt** [comment]
I'd include revert of #7033 in here --IIRC, since aggfuncs get replaced by the extractor, they shouldn't ever need to be eval'ed directly so they shouldn't have an `fn`.

also, I'd want to check for changes in age benchmarks (or work the check into the existing agg extract walk as suggested in inline note).

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> #### sql: reject aggregate functions in GROUP BY\.
> 
> Fixes #7034.
> 
> 
> 
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/group.go, line 65 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-KJMMGNQeVDUwNwDFq5_:-KJMMGNQeVDUwNwDFq5a:1346112561) ([raw file](https://github.com/cockroachdb/cockroach/blob/edc8ab9ca0958b764588ac16090f1c038823dd15/sql/group.go#L65)):*
> ```Go
> 	// expressions.
> 	for i := range groupBy {
> 		if p.aggregateInExpr(groupBy[i]) {
> ```

A little sad that this means we'll need to walk the expr's twice with the extract visitor... could we do this durning extract instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-:-KJMLmWoT5OqTg2zuFMr:-498316119)*

**Comment by dt** [comment]
er, scratch that last part (see inline)

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I'd include revert of #7033 in here --IIRC, since aggfuncs get replaced by the extractor, they shouldn't ever need to be eval'ed directly so they shouldn't have an `fn`.
> 
> also, I'd want to check for changes in age benchmarks (or work the check into the existing agg extract walk as suggested in inline note).
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/group.go, line 65 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-KJMMGNQeVDUwNwDFq5_:-KJMMqYeUBnVfnwWKgeP:655939828) ([raw file](https://github.com/cockroachdb/cockroach/blob/edc8ab9ca0958b764588ac16090f1c038823dd15/sql/group.go#L65)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> A little sad that this means we'll need to walk the expr's twice with the extract visitor... could we do this durning extract instead?
</details>
oh, wait, nvm me, we don't currently walk the GROUP BY exprs. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-:-KJMMxndqXWlIObRRals:-1024979957)*

**Comment by tamird** [comment]
let's revert the change to COUNT's `fn` here.

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> er, scratch that last part (see inline)
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-:-KJMTzMqHkLXkD0hfqL9:394850589)*

**Comment by knz** [comment]
Done.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> let's revert the change to COUNT's `fn` here.
</details>


---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-:-KJMaF6L51v0j9n5rlER:-499146009)*

**Comment by dt** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/builtins.go, line 1095 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-KJMeClE9w_AGJgRIpCC:-KJMeClE9w_AGJgRIpCD:465654846) ([raw file](https://github.com/cockroachdb/cockroach/blob/9036286b00d06131425814292e57921f084eb463/sql/parser/builtins.go#L1095)):*
> ```Go
> 			// need a real function.
> 			impure: true,
> 			fn: func(_ *EvalContext, _ DTuple) (Datum, error) {
> ```

*if* you want this to be an error, it should be `util.Errorf` since it is our mistake, not the users'.

That said, I'm not convinced -- a panic when code we believe is unreachable is somehow reached makes it very clear and loud that our assumptions have been violated and there's (at least one) bug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035)*

**Comment by dt** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/builtins.go, line 1095 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-KJMeClE9w_AGJgRIpCC:-KJMf6HeqMLcaA0wyC1U:-1616608668) ([raw file](https://github.com/cockroachdb/cockroach/blob/9036286b00d06131425814292e57921f084eb463/sql/parser/builtins.go#L1095)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> *if* you want this to be an error, it should be `util.Errorf` since it is our mistake, not the users'.
> 
> That said, I'm not convinced -- a panic when code we believe is unreachable is somehow reached makes it very clear and loud that our assumptions have been violated and there's (at least one) bug.
</details>
The assumption is that aggregate functions aren't directly evaluated (since that doesn't make any sense), so there's no reason for them to have an `fn` -- note that the other agg funcs (sum, stddev, variance, etc) also don't have fn's, so special casing `count` like this seems odd. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/builtins.go, line 1095 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-KJMeClE9w_AGJgRIpCC:-KJMhQ8iebdOOD_44obt:841126582) ([raw file](https://github.com/cockroachdb/cockroach/blob/9036286b00d06131425814292e57921f084eb463/sql/parser/builtins.go#L1095)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> The assumption is that aggregate functions aren't directly evaluated (since that doesn't make any sense), so there's no reason for them to have an `fn` -- note that the other agg funcs (sum, stddev, variance, etc) also don't have fn's, so special casing `count` like this seems odd. 
</details>
+1, let's simply remove this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035)*

**Comment by knz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 1095 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-KJMeClE9w_AGJgRIpCC:-KJMhLSxerWa9OaZgmyq:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9036286b00d06131425814292e57921f084eb463/sql/parser/builtins.go#L1095)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> +1, let's simply remove this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035)*

**Comment by dt** [comment]
:lgtm:

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Done.
</details>


---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035#-:-KJMkXrQ3OlMRWn9ap-T:1417088721)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7035)*

**Pull request merged**
