### PR TITLE
cli: teach merge-logs to capture filter subgroups

### PR DESCRIPTION
**Pull request by tbg**
See the test cases for motivation. I'm kind of tired of staring at

```
	cluster.go:1688,tpcc.go:841,tpcc.go:527,test.go:1237: unexpected node event: 4: dead
	cluster.go:953,context.go:90,cluster.go:942,asm_amd64.s:522,panic.go:397,test.go:785,test.go:771,cluster.go:1688,tpcc.go:841,tpcc.go:527,test.go:1237: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1234680-tpccbench-nodes-6-cpu-16-multi-az --oneshot --ignore-empty-nodes: exit status 1 3: skipped
		4: dead
		5: 3404
		7: 3458
		1: 3416
		6: 3540
		2: 3462
		Error:  4: dead
```

Feels like roachtest should tell us what might have happened.

Now that I've written this code I'm not sure that a clever `roachprod
logs` invocation can really deliver on that promise, but the
functionality seems useful anyway.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Another thing that could be cool would be to pass in an expansion template for https://golang.org/pkg/regexp/#Regexp.Expand which would allow a user to both use named capture groups and to re-arrange captured data but that's probably not for this PR. 

> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36794#-:-LcH0IexCa6gKzFhyaVu:b-f10hfd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, and @tbg)

___
*[pkg/cli/debug_merge_logs.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36794#-LcH-XLkD8PFXYu6VG9q:-LcH-XLl8KaABlAsPNgp:b10agyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/22957b0b82aa885a8ff1b76fa14e65e5e11aab98/pkg/cli/debug_merge_logs.go#L123)):*
> ```Go
> 						var submatches [][]byte
> 						for _, b := range matches[1:] {
> 							b = append([]byte(nil), b...) // make a copy
> ```

Do you really need to make a copy? The truncate call is just shorten the len of the underlying buffer but isn't going to zero the data contained in later parts. Given you know that at most you're going to write the full string back it seems safe to not copy out the data.

I'd love to not need to do allocations on every iteration of this loop.
___
*[pkg/cli/debug_merge_logs.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36794#-LcGzUCi7-r-mQRCov17:-LcGzUCi7-r-mQRCov18:b-qb8j8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/22957b0b82aa885a8ff1b76fa14e65e5e11aab98/pkg/cli/debug_merge_logs.go#L133)):*
> ```Go
> 						pending.WriteByte('\n')
> 					} else {
> 						// Matched, but there aren't any capturing groups in
> ```

The linter is not happy about this empty branch.

**Review by tbg — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36794#-:-LcVu7oEBqU_31ZK4uJB:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @bobvawter)

___
*[pkg/cli/debug_merge_logs.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36794#-LcH-XLkD8PFXYu6VG9q:-LcVpFC46XU0ndLEREw0:b-q16znk) ([raw file](https://github.com/cockroachdb/cockroach/blob/22957b0b82aa885a8ff1b76fa14e65e5e11aab98/pkg/cli/debug_merge_logs.go#L123)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Do you really need to make a copy? The truncate call is just shorten the len of the underlying buffer but isn't going to zero the data contained in later parts. Given you know that at most you're going to write the full string back it seems safe to not copy out the data.

I'd love to not need to do allocations on every iteration of this loop.
</blockquote></details>

I've added usage of a scratch buffer here. TBH I think what you're suggesting is safe (and it was the code at some point) but I didn't like making this too complicated to think about.
___
*[pkg/cli/debug_merge_logs.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36794#-LcGzUCi7-r-mQRCov17:-LcVpQ4mDvElpLrI4Xil:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22957b0b82aa885a8ff1b76fa14e65e5e11aab98/pkg/cli/debug_merge_logs.go#L133)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The linter is not happy about this empty branch.
</blockquote></details>

Done.

**Review by bobvawter — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/cli/debug_merge_logs.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36794#-LcH-XLkD8PFXYu6VG9q:-LcW3WBG962troprsJn5:b-6b4ba3) ([raw file](https://github.com/cockroachdb/cockroach/blob/22957b0b82aa885a8ff1b76fa14e65e5e11aab98/pkg/cli/debug_merge_logs.go#L123)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I've added usage of a scratch buffer here. TBH I think what you're suggesting is safe (and it was the code at some point) but I didn't like making this too complicated to think about.
</blockquote></details>

I agree that the scratch buffer is easier to reason about.

**Comment by tbg** [comment]
TFTR!

bors r=bobvawter

**Comment by danhhz** [comment]
This PR description was a rollercoaster of emotion

**Comment by tbg** [comment]
bors r=bobvawter

**Pull request merged**
