### PR TITLE
server: expose RangeState in _status/raft endpoint

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7253)

### CODE REVIEW

**Comment by BramGruneir** [comment]
Unit tests?

---

Reviewed 2 of 2 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7253#-:-KKKuZ6ynFDLQ5jAJCm6:1797240341)*

**Comment by tschottdorf** [comment]
Not really much to test, but I've added a sanity check that makes sure that the field is populated.

**Comment by BramGruneir** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7253#-:-KKL0hAMHumDagrhvqH_:1417088721)*

**Comment by tschottdorf** [comment]
TFTR!

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 10 of 10 files at r4, 10 of 10 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/status.go, line 673 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7253#-KKLIB--YtaCdkl5G6u-:-KKLIB--YtaCdkl5G6u0:5174391) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b98c51f311ef8040dc572f98d65e23ab1a07fa8/server/status.go#L673)):*
> ```Go
> 				}
> 				state := rep.State()
> 				state.Desc = nil // already have a pretty desc
> ```

ew

---

*[storage/storagebase/range.proto, line 59 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7253#-KKLI5T3xk0s3hy0YE0U:-KKLI5T3xk0s3hy0YE0V:1204342806) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b98c51f311ef8040dc572f98d65e23ab1a07fa8/storage/storagebase/range.proto#L59)):*
> ```protobuf
>   RangeState state = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
>   // The highest (and last) index in the Raft log.
>   uint64 lastIndex = 2;
> ```

is this ever populated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7253)*

**Pull request merged**
