### PR TITLE
go.mod: bump Pebble to 91e718bff565

### PR DESCRIPTION
**Pull request by itsbilal**
Changes:

 * [`91e718bf`](https://github.com/cockroachdb/pebble/commit/91e718bf) block: compact representation of synthetic prefix and suffix
 * [`1f1fede2`](https://github.com/cockroachdb/pebble/commit/1f1fede2) block: move transforms definitions to separate file
 * [`4607f616`](https://github.com/cockroachdb/pebble/commit/4607f616) metamorphic: increase L0StopWritesThreshold
 * [`44308bec`](https://github.com/cockroachdb/pebble/commit/44308bec) metamorphic: deduplicate prefixes in key_manager for external objs
 * [`13f37fac`](https://github.com/cockroachdb/pebble/commit/13f37fac) block: remove unnecessary CompressAndChecksum allocation
 * [`a685eea4`](https://github.com/cockroachdb/pebble/commit/a685eea4) crdbtest: port back Cockroach KeySchema edits
 * [`5e687eb6`](https://github.com/cockroachdb/pebble/commit/5e687eb6) colblk: add a KeySchema-specific header
 * [`ad898ed6`](https://github.com/cockroachdb/pebble/commit/ad898ed6) sstable: remove ResetForReuse
 * [`11ff3b6c`](https://github.com/cockroachdb/pebble/commit/11ff3b6c) crdbtest: reorganize testdata
 * [`5f50eae3`](https://github.com/cockroachdb/pebble/commit/5f50eae3) crdbtest: move benchmarks to separate file
 * [`3e0511d7`](https://github.com/cockroachdb/pebble/commit/3e0511d7) crdbtest: rename go files
 * [`5288b4da`](https://github.com/cockroachdb/pebble/commit/5288b4da) sstable: pass KeySchema by pointer
 * [`fcb941e0`](https://github.com/cockroachdb/pebble/commit/fcb941e0) compact: cap overlap ratio of tombstone density compactions
 * [`ced78c34`](https://github.com/cockroachdb/pebble/commit/ced78c34) colblk: cache KeyspanDecoder in block metadata
 * [`696f508a`](https://github.com/cockroachdb/pebble/commit/696f508a) colblk: cache KeySeeker in the block metadata
 * [`dacffe5b`](https://github.com/cockroachdb/pebble/commit/dacffe5b) sstable: perf improvement for ResetForReuse
 * [`24d6d754`](https://github.com/cockroachdb/pebble/commit/24d6d754) colblk: don't use require.NoError in BenchmarkRandSeekInSST hot path
 * [`78801b2f`](https://github.com/cockroachdb/pebble/commit/78801b2f) objstorage: optimize MemObj.NewReadHandle

Release note: none.
Epic: none.

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
> -   [`5288b4da`](https://github.com/cockroachdb/pebble/commit/5288b4da) sstable: pass KeySchema by pointer

This change will require a code change in pkg/storage

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133164#-:-O9pFzKH0h5lg0TxKdFI:bie90r5)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by RaduBerinde — COMMENTED** [review]
Thanks for doing this! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133164#-:-O9tg-QD4yLeFwtx6-eX:bkqkww5)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/storage/pebble_key_schema.go` line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133164#-O9tflXj3c7XDvGm0Nca:-O9tflXj3c7XDvGm0Ncb:b-zbbw0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b6faad5652bb5c1041dc61cfcd377f231f62f5/pkg/storage/pebble_key_schema.go#L164)):*
> ```Go
> 	case 0:
> 		// No-op.
> 		kw.suffixTypes |= hasNonMVCCSuffixes
> ```

hasEmptySuffixes (I just noticed this bug in the pebble code which I am fixing)
___
*[`pkg/storage/pebble_key_schema.go` line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133164#-O9tfpsD3vqSXqD1F1Uy:-O9tfpsD3vqSXqD1F1Uz:bfou8ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b6faad5652bb5c1041dc61cfcd377f231f62f5/pkg/storage/pebble_key_schema.go#L176)):*
> ```Go
> 	default:
> 		// Not a MVCC timestamp.
> 		kw.suffixTypes |= hasEmptySuffixes
> ```

`hasNonMVCCSuffixes`
___
*[`pkg/storage/pebble_key_schema.go` line 295 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133164#-O9tfuvx6f4N4YVUA7GA:-O9tfuvx6f4N4YVUA7GB:br94m5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b6faad5652bb5c1041dc61cfcd377f231f62f5/pkg/storage/pebble_key_schema.go#L295)):*
> ```Go
> 
> // Init is part of the KeySeeker interface.
> func (ks *cockroachKeySeeker) Init(d *colblk.DataBlockDecoder) error {
> ```

Chang this to `init()` with no `error`

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133164#-:-O9tmcvG9D1Rx_TLSa5D:b-814g8k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/storage/pebble_key_schema.go` line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133164#-O9tflXj3c7XDvGm0Nca:-O9tmdqH6RUYDf21UKS-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b6faad5652bb5c1041dc61cfcd377f231f62f5/pkg/storage/pebble_key_schema.go#L164)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

hasEmptySuffixes (I just noticed this bug in the pebble code which I am fixing)
</blockquote></details>

Done.
___
*[`pkg/storage/pebble_key_schema.go` line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133164#-O9tfpsD3vqSXqD1F1Uy:-O9tmg-c6jqK8B9Q6Mdi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b6faad5652bb5c1041dc61cfcd377f231f62f5/pkg/storage/pebble_key_schema.go#L176)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`hasNonMVCCSuffixes`
</blockquote></details>

Done.
___
*[`pkg/storage/pebble_key_schema.go` line 295 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133164#-O9tfuvx6f4N4YVUA7GA:-O9tmh5F-0XKV-Gzo0GD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b6faad5652bb5c1041dc61cfcd377f231f62f5/pkg/storage/pebble_key_schema.go#L295)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Chang this to `init()` with no `error`
</blockquote></details>

Done.

**Comment by itsbilal** [comment]
TFTR!

bors r=RaduBerinde

**Pull request merged**
