### PR TITLE
sql: move ConvertBatchError to sqlbase

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12986)

### CODE REVIEW

**Comment by tamird** [comment]
Seems premature. Can this happen wen distsql is ready to use it? This
acquires the `git blame` for no tangible benefit.

**Comment by RaduBerinde** [comment]
LGTM

**Comment by vivekmenezes** [comment]
It's easy to review and a reasonable change with or without the other change. Even if we decide not to do the other change it eliminates this sql/errors.go file that hardly serves any purpose. This change moves the two functions in that file to more appropriate homes.

**Comment by tamird** [comment]
Sure, that's nice and all, but now the git history of this file is lost.
`git blame` will show "move ..." instead of anything interesting.

**Comment by vivekmenezes** [comment]
I love this to be great for git blame. How should I have made this PR without necessarily making the other distsql PR? I'd like more folks to be able to make these kinds of simpler move PRs without having to wait on another bigger one. Thanks!

**Comment by dt** [comment]
@tamird I thought doing the move in a standalone commit (i.e. so that `git diff -M` reports it as a rename) was what makes `blame` work across moves?

**Comment by tamird** [comment]
@dt maybe if you strictly rename, but in this case, a file was removed and its content moved into another existing file.

@vivekmenezes there is no way to do that as far as I'm aware.

**Pull request merged**
