### PR TITLE
Add the timestamp's Logical field to check for unicity in the datetim…

### LINKED ISSUE #5302: sql: test flakiness in TestLogic / datetime
Exposed by #5037.

### PR DESCRIPTION
**Pull request by knz**
…e test.

Fixes #5302.

@petermattis can you cherry-pick this and check if that helps with your setup?

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5305)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

**Comment by tschottdorf** [comment]
By the way, it's still completely possible for two transactions to get
assigned the same timestamp (not at the same node, but nevertheless).

**Comment by knz** [comment]
@tschottdorf but would they get the same value for `Logical` as well?

**Comment by tschottdorf** [comment]
Sorry, yes, that's what I mean.

If we have two nodes with individual clocks and with no incoming hlc events, then the timestamp is basically just the walltime and zero logical. If a transaction gets started at the exact same walltime on each node, they'll have the same timestamp.

**Comment by knz** [comment]
@petermattis my intuition about why you were observing a failed test breaks down in the face of toby's answer. Any chance I could reproduce your test failure?

**Comment by tschottdorf** [comment]
just to be clear, on a single node this can't happen. You need two nodes. Haven't looked closely, but your fix does look like it'd apply here.

**Comment by knz** [comment]
@tschottdorf the problem is that peter is observing the same timestamp (up to nanosecond precision) in different transactions in TestLogic. I am not sure how this can happen. It doesn't reproduce locally on my machine and didn't reproduce on CI. I thought the timestamps were really different but only in the `Logical` field. But now you're saying they can really be the same, which means that I can't remove the flakiness this way. Also I still need to investigate whether this is real flakiness or perhaps a bug introduced in #5037.

**Comment by tschottdorf** [comment]
This is a single-node test, so what I'm saying is that the logical ticks won't be the same if the walltime is.
Getting the same walltime is expected if something adds a timestamp ahead of the physical clock into the HLC (as we do in a few places; it's kind of sketchy).

For example, if the clock is at 10.0 (and physical time is 10) and receives an event at 20.0, it'll go to 20.0. Now if you query the clock, you'll get 20.1, 20.2, .... until the physical clock reaches 21, at which point you'll get 21.0.

**Comment by knz** [comment]
Oh right then my fix was the right way to go, yay :)

**Pull request merged**
