### PR TITLE
cli: walk directories in debug merge-logs

### PR DESCRIPTION
**Pull request by tbg**
This is a UX improvement. Instead of typing out

`./cockroach debug merge-logs nodes/*/logs/*.log`

(as one does for each `debug.zip` or roachtest investigation),
you can now simply use

`./cockroach debug merge-logs .`.

Additionally, default the program filter to disabled.

The program filter is what matches the `<program>.<host>.<morestuff>.log` in
the log files handed to `merge-logs`. The default is generally a reasonable
choice but when you have an oddly named binary (does happen) merge-logs
completely stops doing anything and time is wasted figuring out why.
`merge-logs` is already very unlikely to pick up stray files since its default
`file-pattern` matches the entire logging file format (it delegates only
matching of `<program>` to the program-filter), so turning the program filter
off by default seems right.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/63783#-MYP1BBn8CSmgIwhemlG:-MYP1BBn8CSmgIwhemlH:brps4k7) (no related file):*
Overall this looks like a nice quality of life change to me, but I haven't used this command much yet.

I left some comments but none of them are blocking.

---
___
*[pkg/cli/debug_merge_logs.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63783#-MYOwQbbCH5yK4qyl_U6:-MYOwQbbCH5yK4qyl_U7:bw5f9yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66a346653e85267c948b89bf1226d5c6211f6e8/pkg/cli/debug_merge_logs.go#L338)):*
> ```Go
> 	var wg sync.WaitGroup
> 	for _, p := range paths {
> 		filepath.Walk(p, func(p string, info os.FileInfo, err error) error {
> ```

We can't do it now, but when we move to Go 1.16 we should consider changing this to filepath.WalkDir, which will avoid calling stat on every path that gets walked.
___
*[pkg/cli/debug_merge_logs.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63783#-MYP0YHv0qo_5lW6Y7BJ:-MYP0YHv0qo_5lW6Y7BK:b-j1sybw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66a346653e85267c948b89bf1226d5c6211f6e8/pkg/cli/debug_merge_logs.go#L348)):*
> ```Go
> 			// We're looking at a file.
> 			wg.Add(1)
> 			go func(p string) {
> ```

I mildly wonder if it is actually worth distributing these regular expression matches.
___
*[pkg/cli/debug_merge_logs.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63783#-MYP-AZFB4tH5_mzOlwx:-MYP-AZFB4tH5_mzOlwy:b-d95nof) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66a346653e85267c948b89bf1226d5c6211f6e8/pkg/cli/debug_merge_logs.go#L369)):*
> ```Go
> 		close(fileChan)
> 	}()
> 	files := make([]fileInfo, 0, len(fileChan))
> ```

Before fileChan would have all entries at this point, now len(fileChan) could be anything between 0 and cap(fileChan).  If we still want to pre-allocate this, cap(fileChan) might make more sense, although we would be possibly over-allocating by a lot in the case where the user has given us exact paths.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/63783#-MYP1BBn8CSmgIwhemlG:-MYnK6JyCWBQzp0S6MVT:b-814g8k) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Overall this looks like a nice quality of life change to me, but I haven't used this command much yet.

I left some comments but none of them are blocking.
</blockquote></details>

TFTR!

---
___
*[pkg/cli/debug_merge_logs.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63783#-MYOwQbbCH5yK4qyl_U6:-MYnIyqo8t12Tkwx9oMi:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66a346653e85267c948b89bf1226d5c6211f6e8/pkg/cli/debug_merge_logs.go#L338)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

We can't do it now, but when we move to Go 1.16 we should consider changing this to filepath.WalkDir, which will avoid calling stat on every path that gets walked.
</blockquote></details>

Ack.
___
*[pkg/cli/debug_merge_logs.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63783#-MYP0YHv0qo_5lW6Y7BJ:-MYnJ4WF49yRarDIaEoA:b-r4dmz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66a346653e85267c948b89bf1226d5c6211f6e8/pkg/cli/debug_merge_logs.go#L348)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I mildly wonder if it is worth distributing these regular expression matches.
</blockquote></details>

Probably not, especially now that we're calling `Stat()` on the main goroutine. I ripped it out, nice simplification.
___
*[pkg/cli/debug_merge_logs.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63783#-MYP-AZFB4tH5_mzOlwx:-MYnJARN3TsAtYYXiNr7:bil67ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66a346653e85267c948b89bf1226d5c6211f6e8/pkg/cli/debug_merge_logs.go#L369)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Before fileChan would have all entries at this point, now len(fileChan) could be anything between 0 and cap(fileChan).  If we still want to pre-allocate this, cap(fileChan) might make more sense, although we would be possibly over-allocating by a lot in the case where the user has given us exact paths.
</blockquote></details>

This is not an issue any more as the concurrency in this method has been removed.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by tbg** [comment]
bors r=stevendanna

**Comment by tbg** [comment]
bors r=stevendanna

Failed on something unrelated in logictest

**Pull request merged**
