### PR TITLE
storage: fill snapshot reservations in Store.HandleSnapshot

### PR DESCRIPTION
**Pull request by petermattis**
Previously we were filling reservations in Replica.applySnapshot(), but
that could leave dangling a reservation if we never reached that method
because the snapshot could not be applied.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10391)

### CODE REVIEW

**Comment by petermattis** [comment]
This fixes the reservation leak I was seeing when trying to recover after a down node, but the recovery is making very slow progress so it doesn't completely fix https://github.com/cockroachlabs/production/issues/157.

**Comment by tamird** [comment]
:lgtm: but looks like we're missing some test coverage, unless the addition to TestStoreRangeRebalance reliably fails without this change.

---

Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10391#-:-KV_T6Aqz1_HZAA6erRw:b-o6jp0n)*

**Comment by petermattis** [comment]
Agreed about the lack of test coverage. I'll file an issue. 

---

Review status: 4 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10391#-:-KV_TR4xKatjRUXg3aAs:bvq5utz)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/reservation.go, line 257 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10391#-KV_TqGES9TzGPz3tKta:-KV_TqGES9TzGPz3tKtb:b-4v8iri) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4826a692149d0628e217f1d991aef807a94d7e9/pkg/storage/reservation.go#L257)):*
> ```Go
> 		var timeoutTimer timeutil.Timer
> 		defer timeoutTimer.Stop()
> 		ctx := context.TODO()
> ```

I think this one can be .Background() since it's a background worker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10391)*

**Comment by petermattis** [comment]
Added another commit which normalizes log messages. Guess I could have sent that as a separate PR, but my fingers have a mind of their own. PTAL.

**Review by jordanlewis — APPROVED** [review]
The change LGTM. I can look at adding test coverage for this.

**Comment by tamird** [comment]
Because I'm sneaky, I've already reviewed that second commit. Still LGTM but left a comment.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10391#-:-KV_WFYE9MkiAli7mRcS:b-s8nyl5)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/reservation.go, line 257 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10391#-KV_TqGES9TzGPz3tKta:-KV_WvdjzX5kEc4GQRWd:bj6uyfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4826a692149d0628e217f1d991aef807a94d7e9/pkg/storage/reservation.go#L257)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I think this one can be .Background() since it's a background worker.
</details>
True, but I'm going to send another PR shortly that removes this goroutine. So I'm going to leave this as-is for now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10391)*

**Comment by BramGruneir** [comment]
:lgtm:  And as discussed, queue can be removed as well.
At some point, this should be renamed from reservation and bookie to something more appropriate, perhaps `funnel`?  

---

Reviewed 5 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10391#-:-KV_e8qo2c1gJGiFC89l:bzgujeh)*

**Pull request merged**
