### PR TITLE
all: custom protoc-gen binary

### PR DESCRIPTION
**Pull request by tamird**
Re-proposing #1317.

In addition to the benefits originally mentioned, this also makes `String()` faster and more descriptive, and gives us more consistent treatment of enums.

At this point, I don't really see the downsides.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3357)

### CODE REVIEW

**Comment by bdarnell** [comment]
I'm OK with the custom binary, but I prefer the enum prefixes to be on by default. Only some of our enums are named with the assumption that they will live in the package-level namespace.

Can you post before-and-after String() results? We don't really care about speed here so reflection seems like the way to go unless the alternate format is a real improvement.

**Comment by tamird** [comment]
>  I prefer the enum prefixes to be on by default. Only some of our enums are named with the assumption that they will live in the package-level namespace.

That's true, but still the names make sense. Was there a case in particular that you find to be worse without its prefix?

> Can you post before-and-after String() results? We don't really care about speed here so reflection seems like the way to go unless the alternate format is a real improvement.

Sure. Example:
```go
	fmt.Printf("Value: %s\n", ErrorDetail{})
	fmt.Printf("Pointer: %s\n", &ErrorDetail{})
```

Before:
```
Value: {<nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}
Pointer:
```

After:
```
Value: {<nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}
Pointer: &ErrorDetail{NotLeader:<nil>,RangeNotFound:<nil>,RangeKeyMismatch:<nil>,ReadWithinUncertaintyInterval:<nil>,TransactionAborted:<nil>,TransactionPush:<nil>,TransactionRetry:<nil>,TransactionStatus:<nil>,WriteIntent:<nil>,WriteTooOld:<nil>,OpRequiresTxn:<nil>,ConditionFailed:<nil>,LeaseRejected:<nil>,NodeUnavailable:<nil>,Send:<nil>,}
```

**Comment by bdarnell** [comment]
> Was there a case in particular that you find to be worse without its prefix?

All of the ones touched by this change. `wire.NONE` no longer has any apparent relation to compression; `roachpb.IMMEDIATE` and friends were more clear with the `TransactionRestart` prefix, and the two different "type" enums with value `INT` are saved only by being in different Go packages. 

The new string format seems like a step backwards for union types (which I for one see a lot of in raft logs). The old string method prints whichever member of the union is set while the new one buries it in a bunch of irrelevant nils (and the almost-but-not-quite go literal syntax is odd).

**Comment by tamird** [comment]
One thing to remember about these union types is that they are not unions in the `oneof` sense; they are defined as a series of optionals.

Anyhow, I'll back out the last two commits.

**Comment by tamird** [comment]
PTAL

**Comment by bdarnell** [comment]
Please don't add unrelated changes into a branch once the review has started. The new second commit is risky. We have places where we type-assert from `error` to pointers like `(*roachpb.ConditionFailedError)`. There is currently no ambiguity, because only a pointer to `ConditionFailedError` can be an `error`, but with this change the `error` could be either a pointer or a value, so we lose type-safety.

**Comment by tamird** [comment]
That's a good point. I'll split that commit out into a new PR; the original motivation was the impact of `nil` errors having `Error()` implementations that printed something other than "<nil>" on the `ErrorDetail` example I posted.

**Comment by bdarnell** [comment]
This is essentially the same as `protoc-gen-gogofaster`. The only difference is the removal of getters, which doesn't seem like enough reason to build a custom binary. Let's just use `protoc-gen-gogofaster` and avoid the additional complexity. This will have the side benefit of discouraging exploration of more tweaks of questionable value.

**Comment by tamird** [comment]
I fixed the dependency problem; `go generate ./....` will now bootstrap before building protos.

**Comment by tamird** [comment]
This also removes unrecognized fields.

>  This will have the side benefit of discouraging exploration of more tweaks of questionable value.

You're passing a value judgement on future exploration; I disagree with the blanket statement that discouraging it is a benefit.

**Comment by bdarnell** [comment]
`gogofast` generates marshaler, sizer, and unmarshaler; `gogofaster` does that plus turning off unrecognized fields (and something about extensions).

> You're passing a value judgement on future exploration

This thread has provided evidence for this judgement.

**Comment by tamird** [comment]
protoc-gen-gogofaster does not work because of https://github.com/gogo/protobuf/blob/master/protoc-gen-gogofaster/main.go#L45.

The result is `ERROR: field Datum.BoolVal cannot be in an oneof and a non-nullable field` on `sql/driver/wire.proto`, as well as various type mismatches where pointers have become values.

**Comment by bdarnell** [comment]
Ah, I misread what that line did because of the mention of extensions. LGTM.

**Pull request merged**
