### PR TITLE
rpc: enable server-side gRPC keepalive

### LINKED ISSUE #20536: teamcity: failed tests on master: test/TestGRPCKeepaliveFailureFailsInflightRPCs, testrace/TestGRPCKeepaliveFailureFailsInflightRPCs
The following tests appear to have failed:

[#433491](https://teamcity.cockroachdb.com/viewLog.html?buildId=433491):

```
--- FAIL: test/TestGRPCKeepaliveFailureFailsInflightRPCs (0.030s)
context_test.go:750: initial connection heartbeat failed: rpc error: code = Unavailable desc = transport is closing
--- FAIL: testrace/TestGRPCKeepaliveFailureFailsInflightRPCs (0.270s)

------- Stdout: -------
E171206 20:14:01.801355 733 testutils/net.go:243  error closing server conn: close tcp 127.0.0.1:40410->127.0.0.1:40551: use of closed network connectioncontext_test.go:750: initial connection heartbeat failed: rpc error: code = Unavailable desc = transport is closing

```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #20536.

We've seen privately reported issues of uni-directional partitions that have
caused serious issues with Cockroach. Notably, a bug in Ubuntu 14.04 running on
EC2 caused TCP writes to hang for up to 15 minutes (for more, see
https://github.com/cockroachdb/docs/issues/2268). Naively one would expect that
client-side keepalive would have detected this case and closed the connection,
but as some of the testing performed here demonstrates, that intuition is not
always true.

This change adds server-side keepalive policies to all RPC connections with the
same timeouts as our current client-side keepalive policy. This is all done
through gRPC, which exposes this as a simple `grpc.ServerOption`.

The test then improves our existing `TestGRPCKeepaliveFailureFailsInflightRPCs`
test to test all variations of uni and bi-directional partitions and asserts the
behavior we expect to see with and without client and server-side keepalive. To
some extent, this is still a smoketest for gRPC keepalive, but it's nice to test
this all explicitly.

Release note (bug fix): Use server-side RPC keepalive in addition to
client-side RPC keepalive to detect and properly handle certain
variations of network partitions.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/rpc/heartbeat.proto, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20707#-L0KvX1pMJ7LplYHFrDK:-L0KvX1qd1NlHmIUChRI:b-oxddze) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31a72bf8b8bfa9e688a289bccd319f0b921c84e/pkg/rpc/heartbeat.proto#L67)):*
> ```protobuf
>   rpc Ping (PingRequest) returns (PingResponse) {}
> }
> service HeartbeatStream {
> ```

s/HeartbeatStream/TestingPingStream/? It doesn't appear to be used outside of tests. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20707#-:-L0Kx2ajBZyu7SCTCM8J:bnfp4nl)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/rpc/context_test.go, line 825 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20707#-L0LC0zdkGATkScjk3SA:-L0LC0zdkGATkScjk3SB:bk3jm90) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31a72bf8b8bfa9e688a289bccd319f0b921c84e/pkg/rpc/context_test.go#L825)):*
> ```Go
> 
> 				// Create the heartbeat client.
> 				unlockedHeartbeatClient, err := NewHeartbeatStreamClient(conn).PingStream(ctx)
> ```

would you mind providing a comment at the top of the test about why exactly we're using a streaming RPC?

---

*[pkg/rpc/heartbeat.proto, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20707#-L0KvX1pMJ7LplYHFrDK:-L0LAUMkvdGGt40o8XeU:bubq2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31a72bf8b8bfa9e688a289bccd319f0b921c84e/pkg/rpc/heartbeat.proto#L67)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/HeartbeatStream/TestingPingStream/? It doesn't appear to be used outside of tests. 
</blockquote></details>

yup, please give a hint about what the deal with this weird creature is

---

*[pkg/rpc/keepalive.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20707#-L0LAFJe-OQ5MRF5zDhq:-L0LAFJe-OQ5MRF5zDhr:b-kk5wvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31a72bf8b8bfa9e688a289bccd319f0b921c84e/pkg/rpc/keepalive.go#L58)):*
> ```Go
> // The aggressively low timeout we set here makes the connection very
> // flaky for any RPC use, particularly when running under stress with -p
> // 100. This test can't expect any RPCs to succeed reliably.
> ```

"this test"? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20707#-:-L0LC7mpA7qxdB-m7JVU:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/rpc/context_test.go, line 825 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20707#-L0LC0zdkGATkScjk3SA:-L0L_4H8qpixdEJJpkKm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31a72bf8b8bfa9e688a289bccd319f0b921c84e/pkg/rpc/context_test.go#L825)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

would you mind providing a comment at the top of the test about why exactly we're using a streaming RPC?
</blockquote></details>

Done.

---

*[pkg/rpc/heartbeat.proto, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20707#-L0KvX1pMJ7LplYHFrDK:-L0L_jOuY4y3a8AvvyMq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31a72bf8b8bfa9e688a289bccd319f0b921c84e/pkg/rpc/heartbeat.proto#L67)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

yup, please give a hint about what the deal with this weird creature is
</blockquote></details>

Done.

---

*[pkg/rpc/keepalive.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20707#-L0LAFJe-OQ5MRF5zDhq:-L0L_tABozV3zkh7nsoB:b-dokb79) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31a72bf8b8bfa9e688a289bccd319f0b921c84e/pkg/rpc/keepalive.go#L58)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

"this test"? 
</blockquote></details>

Copied the wrong comment for this. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20707)*

**Comment by jordanlewis** [comment]
Performing a Major Act of Thread Necromancy: why did we choose to set the `Timeout` on this option at 3 seconds? This is a very low value, and its easily hit if a node encounters a temporary network or CPU blip. What happens if the timeout is reached is that the underlying transport is Closed, which actually calls `cancel()` on all of the transport's streams: 
https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L1040
https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L1083-L1085

This causes problems for long-running DistSQL queries, and likely other long-running jobs, which are not currently resilient to their gRPC streams getting canceled. Usually, this will manifest as a "mysterious context canceled" like we've seen in issues like https://github.com/cockroachlabs/support/issues/915

I'd propose doubling this timeout, but I don't know if that would cause other issues. What do you all think?

**Comment by andreimatei** [comment]
> This causes problems for long-running DistSQL queries, and likely other long-running jobs, which are not currently resilient to their gRPC streams getting canceled. 

I don't really believe in "network blips", but i believe in CPU starvation. What I believe in even more, though, is stream window starvation. Unless the flows in question don't actually transfer any data because they're exports?

**Comment by jordanlewis** [comment]
Correct, the flows in question don't actually transfer any data. They are exports.

**Comment by nvanbenschoten** [comment]
The 3 second network timeout dates back to https://github.com/cockroachdb/cockroach/commit/633579ffaaf10b41e81b67fcfb56a2819267a86b#diff-45b72a31cc78f66ffa3a665cf089409d030ba41a8efeb41189adb81ef5cdbc0dR39. I don't know where it came from or why that number was chosen, but it doesn't seem crazy to me. I'd imagine that it has some weak relation to our 9 second lease timeout. Maybe @bdarnell has more context here.

So the concern is that an export request is sent to a node, that node becomes overloaded for 3+ seconds, misses an RPC heartbeat, the connection drops, and the export request is canceled? It's an interesting dilemma. My gut reaction is that if a node is overloaded to the point of missing heartbeats for 3+ seconds, giving it another 3 seconds to respond isn't going to be a real fix. The node must be having a very bad time.

> This causes problems for long-running DistSQL queries, and likely other long-running jobs, which are not currently resilient to their gRPC streams getting canceled. 

I don't know about long-running DistSQL queries, but long-running jobs are supposed to be resilient to transient failures, right? So are we missing some logic to retry on network errors like this? Is the problem that a context cancellation doesn't look like a transient network failure?

> I don't know if that would cause other issues

I think the issues it could cause are that requests to a dead node with an unclean connection shutdown could hang for up to 6 seconds before moving on to the next candidate instead of hanging for up to 3 seconds.

**Comment by bdarnell** [comment]
3s was chosen more or less arbitrarily because it seemed like plenty of time for a network timeout (if anything, it feels too high to me). We did not anticipate non-network factors playing a significant role here. 

> What I believe in even more, though, is stream window starvation. Unless the flows in question don't actually transfer any data because they're exports?

GRPC keepalives use HTTP/2 ping frames, which are exempt from the stream window mechanism. There are two heartbeat mechanisms here: GRPC keepalives which use HTTP pings so they won't fail in window starvation situations but when they do fail, in-flight rpcs will error out, and our own heartbeat rpcs which are subject to the flow control window but should only prevent new RPCs without affecting in-flight ones.

> My gut reaction is that if a node is overloaded to the point of missing heartbeats for 3+ seconds, giving it another 3 seconds to respond isn't going to be a real fix. The node must be having a very bad time.

I agree. We need to understand how we can go 3s without getting scheduled enough to process a heartbeat. I don't think it's a good idea to paper over the problem by increasing the timeout (and reducing our ability to detect real failures). 

It sounds to me like we may be running into problems related to the fact that the go 1.13 scheduler (used in CRDB 20.2) was not preemptive, so we may have managed to write a function that does a ton of work without opportunities for context switching. Upgrading Go may fix the problem.

**Comment by jordanlewis** [comment]
> I don't know about long-running DistSQL queries, but long-running jobs are supposed to be resilient to transient failures, right? So are we missing some logic to retry on network errors like this? Is the problem that a context cancellation doesn't look like a transient network failure?

The long-running jobs might be fine in general. EXPORT is weird because it's just a regular DistSQL query. But it's coming up as a crucial problem for some customers. We have no mechanism to restart a DistSQL stream right now, and making one would be a lot of work.

> It sounds to me like we may be running into problems related to the fact that the go 1.13 scheduler (used in CRDB 20.2) was not preemptive, so we may have managed to write a function that does a ton of work without opportunities for context switching. Upgrading Go may fix the problem.

Vectorized has a lot of tight loops that probably are non-preemptible in Go 1.13. But in this particular example, the nodes in question were not running any SQL at the time. They were churning on some CDC (with lots of JSON decoding which has ample preemptible spots) and these export requests (which read data and send S3 payloads, also ample opportunities).

> I agree. We need to understand how we can go 3s without getting scheduled enough to process a heartbeat. I don't think it's a good idea to paper over the problem by increasing the timeout (and reducing our ability to detect real failures).

Any ideas? Another clue for you that may or may not help: Node Liveness fails at the same time as these heartbeats time out, and the failure is visible in the DB Console liveness graphs.

**Comment by dt** [comment]
@jordanlewis already mentioned this, but just to be extra clear: the issue here is a long-running SQL query, that happens to include ExportCSV processors in its flow, but not `ExportRequest`s which are confusingly not related to EXPORT but are how BACKUP asks KV to export data to files. Also, ExportCSV processors _do_ emit rows back to the gateway periodically, with the names of the csv files they wrote to the sink, so there is at least _some_ minimal traffic between the processors in the flow.

**Pull request merged**
