### PR TITLE
sql: change lease acquisition methods to return error instead of pErr

### PR DESCRIPTION
**Pull request by andreimatei**
It's a mechanical change. One more step towards de-pErr-ifying sql.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6508)

### CODE REVIEW

**Comment by tamird** [comment]
btw this change might be worthy of a mailing list announcement

**Comment by knz** [comment]
LGTM

**Comment by tschottdorf** [comment]
LGTM, didn't see anything controversial. That doesn't mean I missed anything, right? :-)

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/scan.go, line 224 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6508#-KH-n4v_3WCZMq5_xvlu:-KH-n4v_3WCZMq5_xvlv:-7658714) ([raw file](https://github.com/cockroachdb/cockroach/blob/2976c6d98e6aea24ce601a3195e9fe164c9187db/sql/scan.go#L224)):*
[nit] I would move `n.Perr = ` inside `if err != nil`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6508#-:-KH-nR-UYoqWaXkizSq8:1417088721)*

**Comment by andreimatei** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/scan.go, line 224 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6508#-KH-n4v_3WCZMq5_xvlu:-KH0UJGEpfmxEF2Cn_9Q:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2976c6d98e6aea24ce601a3195e9fe164c9187db/sql/scan.go#L224)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6508)*

**Comment by andreimatei** [comment]
@tschottdorf nothing controversial. It should be fair weather from now on.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6508#-:-KH0UTUEQ-EXSYhgTGTU:1114616917)*

**Pull request merged**
