### PR TITLE
roachprod: adding unit test and renaming ssh.go

### LINKED ISSUE #65928: Roachprod: adding unit test and renaming ssh.go
We need to refactor ssh.go (as one type structure is in use, we cannot remove it completely).

So we are refactoring ssh.go and change its name to io.go and only keeping ProgressWriter struct and function.
Also we are adding some unit testing for this new go file.

### PR DESCRIPTION
**Pull request by alan-mas**
Third part of #47567 and fixes #65928 where we need to refactor `ssh.go` (as one type structure is in use, we cannot remove it completely).

So we are refactoring ssh.go and change its name to `io.go` and only keeping `ProgressWriter` struct and function.
Also we are adding some unit testing for this new `go` file.

Release note: None

### CODE REVIEW

**Review by jlinder — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64156#-:-MeWe10A-jB2j8zQfPek:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @alan-mas)

**Review by jlinder — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64156)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @alan-mas)

___
*[pkg/cmd/roachprod/ssh/io_test.go, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64156#-MgQlW_c6Vi6Kz3Wbdwv:-MgQlW_c6Vi6Kz3Wbdww:buxnxp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c5b9e4c00a350e562b7968e46aeac55870d9c75/pkg/cmd/roachprod/ssh/io_test.go#L54)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	defer func() {
> 		if err := os.Remove(output.Name()); err != nil {
> 			t.Fatal(err)
> 		}
> 	}()
> ```
</details>

Please put this right under the `defer output.Close()` near the beginning of this function.

**Review by jlinder — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64156)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @alan-mas and @jlinder)

___
*[pkg/cmd/roachprod/ssh/io_test.go, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64156#-MgR7xgx3Bqucf7mq2Mf:-MgR7xgy2hGtebVSB9OH:b-iqtvjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8518dd2bb679412c6d628d610425e00d20d235e/pkg/cmd/roachprod/ssh/io_test.go#L25)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	fmt.Println(output.Name())
> ```

Why output the name of the file?

**Review by alan-mas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64156)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jlinder)

___
*[pkg/cmd/roachprod/ssh/io_test.go, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64156#-MgQlW_c6Vi6Kz3Wbdwv:-MgRAMQS7c2d7yREpmri:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c5b9e4c00a350e562b7968e46aeac55870d9c75/pkg/cmd/roachprod/ssh/io_test.go#L54)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

> ```
> 	defer func() {
> 		if err := os.Remove(output.Name()); err != nil {
> 			t.Fatal(err)
> 		}
> 	}()
> ```
Please put this right under the `defer output.Close()` near the beginning of this function.
</blockquote></details>

Done
___
*[pkg/cmd/roachprod/ssh/io_test.go, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64156#-MgR7xgx3Bqucf7mq2Mf:-MgRAN88617rpFTeXzZ1:b-vq95u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8518dd2bb679412c6d628d610425e00d20d235e/pkg/cmd/roachprod/ssh/io_test.go#L25)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Why output the name of the file? 
</blockquote></details>

Sorry for that I was printing the name to ensure the code was actually removing (so after running the test I can try to `cat` to file) and forgot to removing it. Just did it now.

**Review by jlinder — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64156#-:-MghbcywCRSAlRQlYczD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @alan-mas)

**Pull request merged**
