### PR TITLE
server,ui: show tables in UDS's in data dist page

### LINKED ISSUE #54957: sql,ui: update Data Distribution page to work with user-defined schemas
The Data Distribution page currently only shows tables that are in the public schema:

https://github.com/cockroachdb/cockroach/blob/eaad551ed717949562b58758b3d5ab6e11d423a4/pkg/server/admin.go#L1775

The backend and frontend should change to allow tables in all schemas to be inspected.

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #54957.

Previously, the data distribution page in the admin ui didn't contain
any tables from user-defined schemas due to an oversight.

This commit resolves the issue.

Release note (admin ui change): include tables within user-defined
schema in the data distribution page of the admin ui.

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
Looks good to me! I wasn't sure if there was a different way the frontend is supposed to hierarchically show schema names, but glad this fix was simpler.

Are there tests for this sort of thing? unit tests on the `DataDistribution` endpoint would be nice, but if they don't exist already then no need to make it now i suppose. e2e frontend integration tests would be cool but sounds harder

**Comment by jordanlewis** [comment]
We could have added hierarchy to the view, but I think it's probably overkill for now. It seems more than likely that people will not need to filter their view on particular schemas here, to me. 

Good point about the tests - needed to update one anyway. I added some test cases for user defined schemas.

**Review by rafiss — APPROVED** [review]
noice!

**Pull request merged**
