### PR TITLE
cli: update the dependency on readline.

### LINKED ISSUE #8788: cli: interactive sql shell acts weird on kubernetes
When running CockroachDB on a local Kubernetes cluster, typing in the sql moves the cursor to the top. It's weird. 

Steps to reproduce:

1. Install and start Kubernetes cluster: http://kubernetes.io/docs/getting-started-guides/minikube/.
2. Run this scrip, which creates persistent volumes and runs the yaml configuration that creates the cockroach resources: https://github.com/a-robinson/kubernetes/blob/33c8885eba8c69c1107f641241cd2f08ed15d5ec/examples/cockroachdb/cockroachdb-petset.yaml.
3. Start a bash session in one of the pods and star the sql shell:

   ```
   $ kubectl exec -it cockroachdb-0 bash
   root@cockroachdb-0:/cockroach# ./cockroach sql --host $(hostname)
   # Welcome to the cockroach SQL interface.
   # All statements must be terminated by a semicolon.
   # To exit: CTRL + D.
   root@cockroachdb-0:26257>
   ```
4. Type some statements in the shell.

Screencast of what happens: https://asciinema.org/a/d19gmvzket2wno57sbhfi0fhr

### PR DESCRIPTION
**Pull request by knz**
Fixes #8788.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9097)

### CODE REVIEW

**Comment by tamird** [comment]
Can you update the commit message to reference upstream changes?

**Comment by knz** [comment]
Done

**Comment by tamird** [comment]
Can you please include the full link? Currently you're linking to #71 in
CRDB.

https://github.com/chzyer/readline/pull/71

**Comment by knz** [comment]
Ah good call. You're definitely the right man to review this PR!

**Comment by tamird** [comment]
LGTM

**Pull request merged**
