### PR TITLE
kvserver: improve Store comment

### PR DESCRIPTION
**Pull request by tbg**
This incorporates post-merge feedback on #72745.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73792#-:-MquYlRg7i30fB0PRDjt:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/kvserver/store.go, line 529 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73792#-MquWylY00v3HdkiYx3I:-MquWylY00v3HdkiYx3J:byuey84) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfd625ef1d4d9d9fcc8b1d28f5a43d57088233bc/pkg/kv/kvserver/store.go#L529)):*
> ```Go
> of individual log entries; see WriteInitialReplicaState).
> 
> An uninitialized Replica has has no notion of ts active RangeDescriptor yet, has
> ```

... Replica has no notion of its active ...

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73792#-:-MqwLcYJ4W9ACoQxLLuE:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/addressing.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73792#-MqwJ7Ej7cYaQv5IDflr:-MqwJ7Ej7cYaQv5IDfls:b-rciscd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfd625ef1d4d9d9fcc8b1d28f5a43d57088233bc/pkg/kv/kvserver/addressing.go#L56)):*
> ```Go
> // for the descriptor. These are copies of the range descriptor but keyed by the
> // EndKey (for historical reasons relating to ReverseScan not having been
> // available); we may use the StartKey if starting from scratch today). While
> ```

nit: extra paren in here.
___
*[pkg/kv/kvserver/addressing.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73792#-MqwJaAH3MMbs6a46ivQ:-MqwJaAH3MMbs6a46ivR:b-hhlper) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfd625ef1d4d9d9fcc8b1d28f5a43d57088233bc/pkg/kv/kvserver/addressing.go#L63)):*
> ```Go
> // up-replication to "repair" the meta copies of the descriptor as a by-product.
> //
> // The fact that the meta2 ranges can split is the source of considerable
> ```

I haven't thought about this in a while, but I thought this was because the last meta2 range can span the meta2 and user keyspaces, not because meta2 ranges can split.

**Review by tbg — COMMENTED** [review]
> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73792)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
bors r=[nvanbenschoten,sumeerbhola]
Thanks!

**Pull request merged**
