### PR TITLE
ui: add reload button for Loading component

### LINKED ISSUE #68602: SQL activity pages (sessions, transactions and statements) are empty during an active workload
CC dedicated clusters show no activity in the Statements, Sessions, or Transactions pages within the CC console. There’s only a red info icon with no text. This was during an active workload (TPCC).

Note these pages were working after initially creating the cluster.  Screenshot:

image

### PR DESCRIPTION
**Pull request by Azhng**
Resolves #68602

https://user-images.githubusercontent.com/9267198/138362614-96f15559-9761-4c4b-8a47-2843cad7978d.mov

Release note (ui change): when an error is encoutered in the statement/
transaction/session page, user can now click on reload button to reload
the page.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
Can we improve the error message to something more clear, instead of the "Injected Error"?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71846#-:-MmZoa_sDQQFaTLpReDV:b-gl5e2v)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by maryliag — COMMENTED** [review]
The issue describe the error message to use:
https://github.com/cockroachdb/cockroach/issues/68602#issuecomment-933805324

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71846#-:-MmZpg8R-A9UlJnAzzv5:b-xf2cug)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by Azhng — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71846#-:-MmZr5-U9t1yOVoFxT4S:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by maryliag — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71846)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/loading/loading.tsx, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71846#-MmZs66Y1ijBk1HAIG2F:-MmZs66Y1ijBk1HAIG2G:b-8i5g8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a66ef69be502ebb92482f03c8b043b9c6bbd075/pkg/ui/workspaces/cluster-ui/src/loading/loading.tsx#L32)):*
> ```XML
>   errorClassName?: string;
>   loadingClassName?: string;
>   statsType: string;
> ```

nit: we list all required items first, followed by the optional

also, this component is used on several other locations, you are be missing this new parameter on all those other locations

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71846)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/loading/loading.tsx, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71846#-MmZs66Y1ijBk1HAIG2F:-MmZt4n79IHYUEi56WoO:b-fur0ew) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a66ef69be502ebb92482f03c8b043b9c6bbd075/pkg/ui/workspaces/cluster-ui/src/loading/loading.tsx#L32)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: we list all required items first, followed by the optional

also, this component is used on several other locations, you are be missing this new parameter on all those other locations
</blockquote></details>

Oh hmm .. my goland usage lookup seems to have failed me :facepalm:

**Review by Azhng — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71846#-:-Mm_D1oYCYOhi7lgk3Pb:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Review by maryliag — COMMENTED** [review]
> Reviewed 3 of 10 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71846)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/sqlActivity/errorMsg.tsx, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71846#-MmclCUp6hibD-u5HVir:-MmclCUp6hibD-u5HVis:b-ljggo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2568cedd06baee88b8fec79939ef7870c5431c16/pkg/ui/workspaces/cluster-ui/src/sqlActivity/errorMsg.tsx#L1)):*
> ```XML
> // Copyright 2021 The Cockroach Authors.
> ```

nit: the name of the file is a little misleading, since this provides not only the message but also the reload option, maybe a better name could be errorRetry, errorComponent, errorHandler, something along those lines or even just error

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71846)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/sqlActivity/errorMsg.tsx, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71846#-MmclCUp6hibD-u5HVir:-MmcqjH_Afcbyeb5elaq:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2568cedd06baee88b8fec79939ef7870c5431c16/pkg/ui/workspaces/cluster-ui/src/sqlActivity/errorMsg.tsx#L1)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: the name of the file is a little misleading, since this provides not only the message but also the reload option, maybe a better name could be errorRetry, errorComponent, errorHandler, something along those lines or even just error
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 10 files at r3, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71846#-:-MmeFpBb-8SN9ik_-M5c:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Comment by Azhng** [comment]
blathers backport 21.2

**Pull request merged**
