### PR TITLE
sql: require license to use READ COMMITTED and SNAPSHOT

### LINKED ISSUE #117822: sql: make Read Committed enterprise-license only
Read Committed can only be used with enterprise licensing. 

Jira issue: CRDB-35379

Epic CRDB-34172

### PR DESCRIPTION
**Pull request by rafiss**
This required also making sure the tests that use different isolation
levels can pass the license check.

I'm omitting SNAPSHOT from the release note since it is not yet a public feature.

fixes https://github.com/cockroachdb/cockroach/issues/117822
Release note (enterprise change): The READ COMMITTED isolation level now requires the cluster to have a valid enterprise license.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 65 of 65 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120154)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

___
*[`pkg/cmd/generate-logictest/main.go` line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoGSCuAInNMy9tkl4L:-NsoGSCuAInNMy9tkl4M:b-54he3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/534b4a963c8302b8743e6b76f9c06c825a5b7200/pkg/cmd/generate-logictest/main.go#L365)):*
> ```Go
> 			RunCCLConfigs:   true,
> 		}
> 		err = t.addCclLogicTests("TestReadCommittedCCLLogic", readCommittedCalc)
> ```

nit: Should this be `LogicCCL` like it is below?
___
*[`pkg/sql/conn_executor.go` line 1134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoG_JL1cu5rjwUoVOy:-NsoG_JL1cu5rjwUoVOz:b-y29ia1) ([raw file](https://github.com/cockroachdb/cockroach/blob/534b4a963c8302b8743e6b76f9c06c825a5b7200/pkg/sql/conn_executor.go#L1134)):*
> ```Go
> 				displayLevel = tree.SnapshotIsolation
> 			}
> 			log.Warningf(ctx, msgFmt, displayLevel)
> ```

Should we wrap this in a `log.Every(10 * time.Second)` or something like that to avoid log spam? Same question below with the other calls to `log.Warningf`.
___
*[`pkg/sql/conn_executor.go` line 3506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoIKzcEKqwtnkrrBLP:-NsoIKzd6Yz0Naf7Ryts:b-3faex6) ([raw file](https://github.com/cockroachdb/cockroach/blob/534b4a963c8302b8743e6b76f9c06c825a5b7200/pkg/sql/conn_executor.go#L3506)):*
> ```Go
> 				upgraded = true
> 				ret = isolation.Serializable
> 				if allowReadCommitted && !hasLicense {
> ```

Do we need the `!hasLicense` condition here? Isn't `if allowReadCommitted {` enough? Same question below? Feel free to ignore if you think this redundancy improves code clarity.
___
*[`pkg/sql/set_session_characteristics.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoHTAuDVJa3VvtDcPQ:-NsoHTAuDVJa3VvtDcPR:b-hrzrzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/534b4a963c8302b8743e6b76f9c06c825a5b7200/pkg/sql/set_session_characteristics.go#L117)):*
> ```Go
> 	if upgradedLevel {
> 		if f := p.sessionDataMutatorIterator.upgradedIsolationLevel; f != nil {
> 			f(ctx, originalLevel, !hasLicense && (allowSnapshot || allowReadCommitted))
> ```

What if `originalLevel == tree.ReadCommittedIsolation && !hasLicense && allowSnapshot && !allowReadCommitted`. That will be promoted because of `!allowReadCommitted`, but we'll log a notice making it sound like the license check was the reason for the upgrade. Maybe this doesn't matter, though you could imagine users using these cluster settings to silence the notices/warnings.

Consider pulling out a `disallowedDueToLicense` bool that you set to `disallowedDueToLicense = allowReadCommitted` in the upgrade paths above.
___
*[`pkg/sql/vars.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoIaza8yut9xkX0eaN:-NsoIaza8yut9xkX0eaO:b-cpz9mk) ([raw file](https://github.com/cockroachdb/cockroach/blob/534b4a963c8302b8743e6b76f9c06c825a5b7200/pkg/sql/vars.go#L446)):*
> ```Go
> 			if upgraded {
> 				if f := m.upgradedIsolationLevel; f != nil {
> 					f(ctx, originalLevel, !hasLicense && (allowSnapshot || allowReadCommitted))
> ```

Same question as in `pkg/sql/set_session_characteristics.go`.
___
*[`pkg/ccl/testccl/sqlccl/read_committed_test.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoJ01XDhI15TpWsCf8:-NsoJ01XDhI15TpWsCf9:b-uilvaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e78a278e9e9e4a81ff7703180df71edfbf907f79/pkg/ccl/testccl/sqlccl/read_committed_test.go#L1)):*
> ```Go
> // Copyright 2023 The Cockroach Authors.
> ```

`2024`

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120154)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @nvanbenschoten)

___
*[`pkg/cmd/generate-logictest/main.go` line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoGSCuAInNMy9tkl4L:-NssIEEN1H7bGPLe1DOL:b-cuz540) ([raw file](https://github.com/cockroachdb/cockroach/blob/534b4a963c8302b8743e6b76f9c06c825a5b7200/pkg/cmd/generate-logictest/main.go#L365)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Should this be `LogicCCL` like it is below?
</blockquote></details>

that makes sense. currently it's using `CCLLogic` since that's what the line before this one had
___
*[`pkg/sql/conn_executor.go` line 1134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoG_JL1cu5rjwUoVOy:-NssIPh320o-8lBvuxKu:bntfktk) ([raw file](https://github.com/cockroachdb/cockroach/blob/534b4a963c8302b8743e6b76f9c06c825a5b7200/pkg/sql/conn_executor.go#L1134)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we wrap this in a `log.Every(10 * time.Second)` or something like that to avoid log spam? Same question below with the other calls to `log.Warningf`.
</blockquote></details>

sounds good. do you know if we need to be worried about mutex contention if we make a global `log.Every(...)` object?
___
*[`pkg/sql/conn_executor.go` line 3506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoIKzcEKqwtnkrrBLP:-NssIUA9Cp3TWfPns--Z:b1syo96) ([raw file](https://github.com/cockroachdb/cockroach/blob/534b4a963c8302b8743e6b76f9c06c825a5b7200/pkg/sql/conn_executor.go#L3506)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need the `!hasLicense` condition here? Isn't `if allowReadCommitted {` enough? Same question below? Feel free to ignore if you think this redundancy improves code clarity.
</blockquote></details>

yeah, i think it makes it a bit more clear
___
*[`pkg/sql/set_session_characteristics.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoHTAuDVJa3VvtDcPQ:-NssIiq-1rmbWM6n2zv4:b8nk1n6) ([raw file](https://github.com/cockroachdb/cockroach/blob/534b4a963c8302b8743e6b76f9c06c825a5b7200/pkg/sql/set_session_characteristics.go#L117)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What if `originalLevel == tree.ReadCommittedIsolation && !hasLicense && allowSnapshot && !allowReadCommitted`. That will be promoted because of `!allowReadCommitted`, but we'll log a notice making it sound like the license check was the reason for the upgrade. Maybe this doesn't matter, though you could imagine users using these cluster settings to silence the notices/warnings.

Consider pulling out a `disallowedDueToLicense` bool that you set to `disallowedDueToLicense = allowReadCommitted` in the upgrade paths above.
</blockquote></details>

good catch; fixed
___
*[`pkg/sql/vars.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoIaza8yut9xkX0eaN:-NssIqyA9iJ-w5079r60:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/534b4a963c8302b8743e6b76f9c06c825a5b7200/pkg/sql/vars.go#L446)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same question as in `pkg/sql/set_session_characteristics.go`.
</blockquote></details>

done
___
*[`pkg/ccl/testccl/sqlccl/read_committed_test.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsoJ01XDhI15TpWsCf8:-NssIpua9Rf211GQ_uqj:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e78a278e9e9e4a81ff7703180df71edfbf907f79/pkg/ccl/testccl/sqlccl/read_committed_test.go#L1)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`2024`
</blockquote></details>

done

**Review by michae2 — COMMENTED** [review]
@petermattis are you still ok with this?

@rafiss, in a mixed 23.2 - 24.1 cluster without a license but with `sql.txn.read_committed_isolation.enabled` set, will the nodes with the 23.2 binary still be able to run RC transactions? Seems fine, just making sure we don't need a version check.

> Reviewed 12 of 65 files at r1, 3 of 5 files at r3, 10 of 28 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-:-Nssx3bTC2IzeSKEHs73:bvgcxo)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/sql/conn_executor.go` line 1132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NssugrL8rryfv1bwBSf:-NssugrMCPCOFN_pYtyO:b-6p6vhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df5f1415b1143a0226100f74770dac78feb96/pkg/sql/conn_executor.go#L1132)):*
> ```Go
> 		ex.metrics.ExecutedStatementCounters.TxnUpgradedCount.Inc(1)
> 		if requiresNotice {
> 			const msgFmt = "%s isolation level is not allowed without an enterprise license"
> ```

nit: It might be worth adding something like "upgrading to serializable isolation" to explain the consequence.
___
*[`pkg/sql/conn_executor.go` line 1142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsszSS_A4DC5HHfMZOm:-NsszSS_A4DC5HHfMZOn:b-n5tnyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df5f1415b1143a0226100f74770dac78feb96/pkg/sql/conn_executor.go#L1142)):*
> ```Go
> 				log.Warningf(ctx, msgFmt, displayLevel)
> 			}
> 			ex.planner.BufferClientNotice(ctx, pgnotice.Newf(msgFmt, displayLevel))
> ```

Suppose someone upgrades from 23.2 without a license, but with `sql.txn.read_committed_isolation.enabled` set and with `ALTER ROLE foo SET default_transaction_isolation = 'read committed';`. Will this notice fire on every BEGIN and every single-statement implicit txn?

(I'm not sure this is wrong, just trying to understand behavior around upgrades.)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120154)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @nvanbenschoten)

___
*[`pkg/sql/conn_executor.go` line 1132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NssugrL8rryfv1bwBSf:-NstBppS5pt0sN0ryRUT:b7anmnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df5f1415b1143a0226100f74770dac78feb96/pkg/sql/conn_executor.go#L1132)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: It might be worth adding something like "upgrading to serializable isolation" to explain the consequence.
</blockquote></details>

good call
___
*[`pkg/sql/conn_executor.go` line 1142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsszSS_A4DC5HHfMZOm:-NstBz2iEZGphWqkyQ7i:b-9uqy2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df5f1415b1143a0226100f74770dac78feb96/pkg/sql/conn_executor.go#L1142)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Suppose someone upgrades from 23.2 without a license, but with `sql.txn.read_committed_isolation.enabled` set and with `ALTER ROLE foo SET default_transaction_isolation = 'read committed';`. Will this notice fire on every BEGIN and every single-statement implicit txn?

(I'm not sure this is wrong, just trying to understand behavior around upgrades.)
</blockquote></details>

no, the notice/log message would would fire once during the initialization of the session when the default value is applied here: https://github.com/cockroachdb/cockroach/blob/c347625475b9344c8c44e5692d704ed8d15e2900/pkg/sql/conn_executor.go#L817

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 20 of 65 files at r1, 1 of 1 files at r2, 1 of 5 files at r3, 17 of 28 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-:-NstZ3J35xh6BLS0Ba4I:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/sql/conn_executor.go` line 1142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120154#-NsszSS_A4DC5HHfMZOm:-NstVYvC2bHCQARW4esV:b-nff86g) ([raw file](https://github.com/cockroachdb/cockroach/blob/485df5f1415b1143a0226100f74770dac78feb96/pkg/sql/conn_executor.go#L1142)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

no, the notice/log message would would fire once during the initialization of the session when the default value is applied here: https://github.com/cockroachdb/cockroach/blob/c347625475b9344c8c44e5692d704ed8d15e2900/pkg/sql/conn_executor.go#L817
</blockquote></details>

Ah, thank you!

**Comment by rafiss** [comment]
> in a mixed 23.2 - 24.1 cluster without a license but with sql.txn.read_committed_isolation.enabled set, will the nodes with the 23.2 binary still be able to run RC transactions?

i missed that before. yes, the 23.2 nodes will still be able to use RC. i don't know of a way to avoid that

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
