### PR TITLE
Add fuse dependency

### PR DESCRIPTION
**Pull request by mberhault**

### CODE REVIEW

**Comment by bdarnell** [comment]
This seems like a good reason to develop examples like this outside of the main repo.

**Comment by mberhault** [comment]
ultimately, you may be right. However, this will make examples that much more likely to rot.

**Comment by bdarnell** [comment]
Whether they're in the main repo or not, they'll rot if they don't have tests. And examples should be using our public interfaces (with the possible exception of things like StartTestServer), which we should really avoid breaking (eventually we'll have non-go examples too!)

**Comment by tamird** [comment]
@bdarnell not quite true: `errcheck` type checks everything, so the rot will be less than if they were out of tree.

**Pull request closed without merging**
