### PR TITLE
sql: Provide more info on panic for NULL value in non-nullable column

### PR DESCRIPTION
**Pull request by lgo**
Previously the panic was not very verbose. This will improve it so that
the user can pinpoint the row that was causing the issue. An example of
the panic is:

    panic: Non-nullable column "bad:id" with no value! Scanning index
    was "primary". The index key columns (id) had the values (1)

### CODE REVIEW

**Comment by justinj** [comment]
:lgtm: modulo merge conflicts

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20038#-:-KyvFy3NBqhmpz1frKRc:b-gcbo1u)*

**Comment by lego** [comment]
Welp, I just stumbled on https://github.com/cockroachdb/cockroach/issues/16379 where an explicit decision was made to not provide additional info in the panic due to sensitive information. This problem did not occur to me. I think the best course of action here would be to revert this, and if we want 1) add a log statement to provide this information instead and 2) mention the choice a comment. cc: @vivekmenezes 

(fortunately, this didn't make it into an alpha release yet)

**Comment by justinj** [comment]
huh, I thought all our messages sent to sentry were anonymized automatically? it's not immediately clear to me peeking through the slack channel, but perhaps that's only for `log.*`s?  perhaps this can just be replaced with a `log.Fatal`? @dt is the authoritative source I think.

**Comment by vivekmenezes** [comment]
I'm pretty sure we should not panic with this sensitive information, so we will need to fix this to log the output. @dt knows more.

**Comment by dt** [comment]
We redact panics to sentry unless they're log.Safe'ed, so you shouldn't need to worry about it

**Pull request merged**
