### PR TITLE
kvserver: hook up the tenant rate limiter

### PR DESCRIPTION
**Pull request by ajwerner**
This commit demonstrates a straw-man for adopting the tenant
rate-limit functionality from `tenantrate`. It is glaringly missing tests
and uses wildly naive assumptions about what to limit and how to
calculate it.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
That was surprisingly well isolated! Exciting to see this all plugged in.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-:-ME-9yjdCzU6zjpz6j96:b-w5o6pr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/replica_backpressure.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-ME-7fu59wrLENrM1md4:-ME-7fu59wrLENrM1md5:b6i8m5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/59636319e9416b939621b4523dff084266fa8e46/pkg/kv/kvserver/replica_backpressure.go#L181)):*
> ```Go
> 		}
> 	}
> ```

nit: stray line
___
*[pkg/kv/kvserver/replica_rate_limit.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-ME-85gSDC_d6K0Kx1Bm:-ME-85gT5RyVxxianh_A:b9ya9wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/59636319e9416b939621b4523dff084266fa8e46/pkg/kv/kvserver/replica_rate_limit.go#L23)):*
> ```Go
> // on the tenantRateLimiter.
> //
> // TODO(ajwerner,tbg): When we have client information in the context, we'd like
> ```

We do have client information in the context now. You should be able to pull this out with `roachpb.TenantFromContext(ctx)`
___
*[pkg/kv/kvserver/replica_rate_limit.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-ME-9T8R0oA7GpODQzFA:-ME-9T8SE6sSq-EXt9pC:b-lk9gpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/59636319e9416b939621b4523dff084266fa8e46/pkg/kv/kvserver/replica_rate_limit.go#L31)):*
> ```Go
> 	}
> 
> 	return r.tenantLimiter.Wait(ctx, bytesWrittenFromRequest(ba))
> ```

Should we avoid this for Admin batches?
___
*[pkg/kv/kvserver/replica_rate_limit.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-ME-8hGZ7BZ7v5M_EP_y:-ME-8hGZ7BZ7v5M_EP_z:b-5g90tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/59636319e9416b939621b4523dff084266fa8e46/pkg/kv/kvserver/replica_rate_limit.go#L37)):*
> ```Go
> // written by a batch request.
> //
> // TODO(ajwerner): Come up with a better methodology to compute the write
> ```

Yes, we should probably introduce a pair of optional interfaces that `Request` / `Response` types can implement. Something along the lines of:
```
type SizedWriteRequest interface {
    Request
    WriteBytes() int64
}

type SizedReadResponse interface {
    Response
    ReadBytes() int64
}
```
Or something along these lines that pulls this logic into `roachpb`.
___
*[pkg/kv/kvserver/replica_rate_limit.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-ME-9fEP2mFvB_DY4P2N:-ME-9fEP2mFvB_DY4P2O:bt4cw3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/59636319e9416b939621b4523dff084266fa8e46/pkg/kv/kvserver/replica_rate_limit.go#L52)):*
> ```Go
> // TODO(ajwerner): Consider whether this needs to only run on batch requests
> // for which canBackpressure is true.
> func (r *Replica) maybeRecordRead(ctx context.Context, br *roachpb.BatchResponse) {
> ```

nit: change this name to be more specific to rate-limiting but less specific to reads. Something like `recordImpactOnRateLimit`.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52331)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rate_limit.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-ME-8hGZ7BZ7v5M_EP_y:-ME-IjZREEI9t9kAshr0:bxlrtpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/59636319e9416b939621b4523dff084266fa8e46/pkg/kv/kvserver/replica_rate_limit.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes, we should probably introduce a pair of optional interfaces that `Request` / `Response` types can implement. Something along the lines of:
```
type SizedWriteRequest interface {
    Request
    WriteBytes() int64
}

type SizedReadResponse interface {
    Response
    ReadBytes() int64
}
```
Or something along these lines that pulls this logic into `roachpb`.
</blockquote></details>

I started doing this and think it's totally reasonable on the writes but for the reads I found implementing it to be rather unsatisfying. For one, read responses don't have keys. For two, things like CPut should probably pay for their reads but we don't have the data. We added the NumBytes header and there is a TODO to populate it for more than `ScanResponse` and `ReverseScanResponse`.

My current thinking is maybe I'll make this interface as suggested and implement it on `*ResponseHeader` to just return `NumBytes`. Then I'll make another commit to populate it underneath batcheval for a few more requests and call it a day. Thoughts?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52331)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

___
*[pkg/kv/kvserver/replica_rate_limit.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-ME-8hGZ7BZ7v5M_EP_y:-ME-LJwm2A2Ex0lU1xsk:b-hs26c) ([raw file](https://github.com/cockroachdb/cockroach/blob/59636319e9416b939621b4523dff084266fa8e46/pkg/kv/kvserver/replica_rate_limit.go#L37)):*
> My current thinking is maybe I'll make this interface as suggested and implement it on *ResponseHeader to just return NumBytes. Then I'll make another commit to populate it underneath batcheval for a few more requests and call it a day. Thoughts?

I guess you don't even need an interface if you're just going to add it to `ResponseHeader`. 

Using `NumBytes` seems fine for now, but I think we'll eventually want to expose richer per-request metrics on the response header. For instance, `NumBytes` represents how many bytes are returned, not how many bytes were touched, so we'd probably want to track the latter as well. @tbg and I were talking about this earlier today in the context of categorized per-request wait times. It seems like it would make a lot of sense to drive rate-limits from these same per-request metrics.

**Review by ajwerner — COMMENTED** [review]
still need to type testing

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-:-MEdvTtN8qYdiDp2Hnwu:b-gi2zku)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rate_limit.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-ME-85gSDC_d6K0Kx1Bm:-MEdu31A7m7clD-rIHOb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59636319e9416b939621b4523dff084266fa8e46/pkg/kv/kvserver/replica_rate_limit.go#L23)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We do have client information in the context now. You should be able to pull this out with `roachpb.TenantFromContext(ctx)`
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_rate_limit.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-ME-9T8R0oA7GpODQzFA:-MEdu4-B6GA3H2WFRwFH:b8uhlth) ([raw file](https://github.com/cockroachdb/cockroach/blob/59636319e9416b939621b4523dff084266fa8e46/pkg/kv/kvserver/replica_rate_limit.go#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we avoid this for Admin batches?
</blockquote></details>

I was thinking that'd be covered by the tenant from the context. Certainly don't want to rate limit things underneath the queues. I feel less clear about things like `ALTER TABLE ... SPLIT AT` and the splitting performed by certain bulk operations.

**Review by nvb — COMMENTED** [review]
> still need to type testing

Yeah, I think we'll want two forms of tests to start:
1. issue a few requests and verify that the impact on the rate limiter is as expected.
2. issue a few requests to get rate limited. Use a manual clock so that nothing moves until you want it to. Add some quota using the clock. Watch the requests complete.
2b. Consider doing the same thing with the system tenant and verifying that it never gets blocked in the first place.

> Reviewed 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-:-MEx4VK-EyWAYwo69xtn:b-zbmhh4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rate_limit.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-ME-9T8R0oA7GpODQzFA:-MEx3zFG4_6AGXw-QO_j:bnjre7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/59636319e9416b939621b4523dff084266fa8e46/pkg/kv/kvserver/replica_rate_limit.go#L31)):*
> I was thinking that'd be covered by the tenant from the context

Good point. We no longer allow tenants to perform Admin operations. So this should be fine.
___
*[pkg/roachpb/api.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MEx4Pvp32iTfUpDqlws:-MEx4Pvp32iTfUpDqlwt:b7yt3nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/441d7c559643451ff40465cd0b4dd33dcb254da8/pkg/roachpb/api.go#L232)):*
> ```Go
> 
> // WriteBytes makes ConditionalPutRequest implement SizedWriteRequest.
> func (r *ConditionalPutRequest) WriteBytes() int64 {
> ```

We seem to be missing `InitPut` in this list.

**Review by ajwerner — COMMENTED** [review]
> issue a few requests and verify that the impact on the rate limiter is as expected.
> issue a few requests to get rate limited. Use a manual clock so that nothing moves until you want it to. Add some quota using the clock. Watch the requests complete.
> 2b. Consider doing the same thing with the system tenant and verifying that it never gets blocked in the first place


Alright I added some testing, which, as it does, revealed the need for some more changes. See the new commits to fix some bugs. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-:-MExeBCQEpHvWfzghSo8:b-f9ad7h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rate_limit.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MExeJT84hcQJSISzujX:-MExeJT84hcQJSISzujY:b-a7cmb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/441d7c559643451ff40465cd0b4dd33dcb254da8/pkg/kv/kvserver/replica_rate_limit.go#L27)):*
> ```Go
> 	}
> 	tenantID, ok := roachpb.TenantFromContext(ctx)
> 	if !ok || tenantID == roachpb.SystemTenantID {
> ```

I think this line is the biggest remaining problem as we'll end up not recording any metrics anywhere. We've got the infrastructure to record system tenant traffic into a limiter that just updates metrics. I'd like to hook that up in a separate PR if that's okay with you.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, 1 of 2 files at r4, 15 of 15 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 10 of 10 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-:-MEyZY-oEsRibNij7idE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/client_tenant_test.go, line 139 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MEyZJUu9-3M0zsN6VRS:-MEyZJUu9-3M0zsN6VRT:bds3i2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9881946cc2b81f47a6414d3982f4ca37a7325e1b/pkg/kv/kvserver/client_tenant_test.go#L139)):*
> ```Go
> }
> 
> // TestTenantRateLimiter ensures that the rate limiter is hooked up properly
> ```

Nice test.
___
*[pkg/kv/kvserver/replica_rate_limit.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MExeJT84hcQJSISzujX:-MEyZH8l1rJoaYCU1f5R:b-3v7n86) ([raw file](https://github.com/cockroachdb/cockroach/blob/441d7c559643451ff40465cd0b4dd33dcb254da8/pkg/kv/kvserver/replica_rate_limit.go#L27)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this line is the biggest remaining problem as we'll end up not recording any metrics anywhere. We've got the infrastructure to record system tenant traffic into a limiter that just updates metrics. I'd like to hook that up in a separate PR if that's okay with you.
</blockquote></details>

Yes, that seems fine.
___
*[pkg/kv/kvserver/testing_knobs.go, line 34 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MEyZPx95BgN1G4BI85W:-MEyZPxAE8KMNqgNAQKt:b-1og4yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9881946cc2b81f47a6414d3982f4ca37a7325e1b/pkg/kv/kvserver/testing_knobs.go#L34)):*
> ```Go
> 	TxnWaitKnobs            txnwait.TestingKnobs
> 	ConsistencyTestingKnobs ConsistencyTestingKnobs
> 	TenantRateKnobs         *tenantrate.TestingKnobs
> ```

nit: any reason to make this a pointer? That doesn't seem to be common with testing knobs.
___
*[pkg/roachpb/api.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MEx4Pvp32iTfUpDqlws:-MEyYgIQ0RCO7bevpkZz:b-jw6ndx) ([raw file](https://github.com/cockroachdb/cockroach/blob/441d7c559643451ff40465cd0b4dd33dcb254da8/pkg/roachpb/api.go#L232)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We seem to be missing `InitPut` in this list.
</blockquote></details>

nit: Keep these in the same order as their other uses in this file.
___
*[pkg/util/quotapool/config.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MEyXyC68fvgZrC7reY1:-MEyXyC68fvgZrC7reY2:bj08950) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cade41d6c817d93650c9b9e2a43b93dd9777b70/pkg/util/quotapool/config.go#L80)):*
> ```Go
> 
> // WithCloser allows the client to provide a channel which will lead to the
> // closer being closed.
> ```

The "quotapool being closed"?

**Review by ajwerner — COMMENTED** [review]
TFTR! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-:-MEyiIdy5DaSByk-xAMs:bz5m8k4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvserver/testing_knobs.go, line 34 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MEyZPx95BgN1G4BI85W:-MEyh6AC36GawId0REHv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9881946cc2b81f47a6414d3982f4ca37a7325e1b/pkg/kv/kvserver/testing_knobs.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: any reason to make this a pointer? That doesn't seem to be common with testing knobs.
</blockquote></details>

Done.
___
*[pkg/roachpb/api.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MEx4Pvp32iTfUpDqlws:-MEyhddODPgD_ByLzQH_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/441d7c559643451ff40465cd0b4dd33dcb254da8/pkg/roachpb/api.go#L232)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Keep these in the same order as their other uses in this file.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r13, 2 of 2 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 10 of 10 files at r17.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-:-MEzeZMuEI8syP37RcuY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/util/quotapool/quotapool.go, line 268 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MEzeU8p62UHYCbdfl57:-MEzeU8p62UHYCbdfl58:b-gf473x) ([raw file](https://github.com/cockroachdb/cockroach/blob/9881946cc2b81f47a6414d3982f4ca37a7325e1b/pkg/util/quotapool/quotapool.go#L268)):*
> ```Go
> 	}
> 	tryAcquire := func() (fulfilled bool) {
> 		stopTryAgainTimer()
> ```

Why did this change? Do we need to pull this into the `fulfilled` branch?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52331)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/util/quotapool/quotapool.go, line 268 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/52331#-MEzeU8p62UHYCbdfl57:-MF0oOBGAGAplXFXJtqa:bwk6gzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9881946cc2b81f47a6414d3982f4ca37a7325e1b/pkg/util/quotapool/quotapool.go#L268)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why did this change? Do we need to pull this into the `fulfilled` branch?
</blockquote></details>

no, it's deferred. This was a bug that wouldn't have shown up because nothing was using the quotapool as a token bucket before this. There was no need to call it. I do think given I'm looking at it this morning that we want to set the channel to nil as we might have been notified in another way. If we're fulfilled, we'll cancel the timer. If we're not, we will reset it if it is non-nil.

**Comment by ajwerner** [comment]
bors r=nvanbenschoten

**Pull request merged**
