### PR TITLE
sql: add trace_id to show sessions

### LINKED ISSUE #117625: sql: SHOW SESSIONS exposes traceID and goroutineID
**Is your feature request related to a problem? Please describe.**
Exposing the traceID and goroutineID of a session in the `SHOW SESSIONS` output can aid in investigations to help filter down profile and log output.

**Describe the solution you'd like**
Output of `SHOW SESSIONS` should include 2 new columns `trace_id` and `goroutine_id` that map to that session's trace and goroutine.

Jira issue: CRDB-35277

Epic CRDB-35278

### PR DESCRIPTION
**Pull request by maryliag**
Add the column trace_id to the result of `SHOW SESSIONS`.
Also adding the column to the views:
`crdb_internal.node_sessions` and `crdb_internal.cluster_sessions`.

Part Of #117625

Release note (sql change): Add column `trace_id` to the response of the `SHOW SESSIONS` command.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118002#-:-Non7kX71lCN0Sw0BQFi:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by dhartunian — APPROVED** [review]
:lgtm: just a nit and a question, not blocking.

> Reviewed 7 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118002#-:-NonRqN_Dc-FWCrKBsL-:bft0syn)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[`pkg/server/serverpb/status.proto` line 1057 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118002#-Nom8YnPEcfHwEwvJQbS:-Nom8YnPEcfHwEwvJQbT:b-30avnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f94b2c038e6bc6951e6a1dd9abd685e4bfed4562/pkg/server/serverpb/status.proto#L1057)):*
> ```proto
>   uint32 pg_backend_pid = 19 [ (gogoproto.customname) = "PGBackendPID" ];
> 
>   // The ID the session's trace.
> ```

nit: ID of the session's trace
___
*[`pkg/sql/conn_executor.go` line 4163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118002#-NonRFGv0uZ3nwtcL-KK:-NonRFGv0uZ3nwtcL-KL:bj2rkgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bbd85e90039cc774925d23f4bd49fc649af5ab6/pkg/sql/conn_executor.go#L4163)):*
> ```Go
> 		TotalActiveTime:            sessionActiveTime,
> 		PGBackendPID:               ex.planner.extendedEvalCtx.QueryCancelKey.GetPGBackendPID(),
> 		TraceID:                    uint64(ex.planner.extendedEvalCtx.Tracing.connSpan.TraceID()),
> ```

weird that we have to plumb so far to get the trace. there's no context that we could extract the trace from? that's how most of the other code works.

or does the caller already have a handle on a span that could be passed in?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118002)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dhartunian, @fqazi, and @xinhaoz)

___
*[`pkg/server/serverpb/status.proto` line 1057 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118002#-Nom8YnPEcfHwEwvJQbS:-NoqwSuq9XNXwPLME9tN:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f94b2c038e6bc6951e6a1dd9abd685e4bfed4562/pkg/server/serverpb/status.proto#L1057)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: ID of the session's trace
</blockquote></details>

Done
___
*[`pkg/sql/conn_executor.go` line 4163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118002#-NonRFGv0uZ3nwtcL-KK:-NoqvgW64Zg32CHh2AiW:b-l467p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bbd85e90039cc774925d23f4bd49fc649af5ab6/pkg/sql/conn_executor.go#L4163)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

weird that we have to plumb so far to get the trace. there's no context that we could extract the trace from? that's how most of the other code works.

or does the caller already have a handle on a span that could be passed in?
</blockquote></details>

In this case we need to go this far. You can notice something similar happens on the line right above for the pg backend PID. The function I'm calling already handles the case when the tracing is on/off, is the span was closed, etc. It might be complicated to use something else and having to handle all of that again.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118002)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @maryliag and @xinhaoz)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant` line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118002#-Nor8qXR7CoORLyRESTs:-Nor8qXR7CoORLyRESTt:b-7s3t6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/43072c2ae08576860c56a7720abd154a4ccf5ed5/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant#L266)):*
> ```
> id  node_id  session_id  start  txn_string  application_name  num_stmts  num_retries  num_auto_retries  last_auto_retry_reason  isolation_level  priority  quality_of_service
> 
> query ITTTTTTTTTTTTTTTI colnames
> ```

Why does this new column have an `I` here? The `pg_backend_pid` is also an int, right? but here it's a `T` which I think implies Text.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118002)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dhartunian and @xinhaoz)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant` line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118002#-Nor8qXR7CoORLyRESTs:-NorFpaa51CRT61dwKdw:b-4mb5gp) ([raw file](https://github.com/cockroachdb/cockroach/blob/43072c2ae08576860c56a7720abd154a4ccf5ed5/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant#L266)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Why does this new column have an `I` here? The `pg_backend_pid` is also an int, right? but here it's a `T` which I think implies Text.
</blockquote></details>

I added an I since is an INT, the same way there is an I for the node_id, maybe the T on others were an oversight or the format itself didn't matter.
I have a following PR where I'm adding one more column, so I can use that and align all columns with the correct types.

**Pull request merged**
