### PR TITLE
sql: add to_date, to_timestamp

### PR DESCRIPTION
**Pull request by yznming**
look at #3781.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7975)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
@yznming thanks for the help here! I have a few comments below, and this change could also use some testing in the `/testdata/builtin_function` file.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/parser/builtins.go, line 997 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7975#-KNV804eNeJYHLd-P-kX:-KNV804eNeJYHLd-P-kY:-762806477) ([raw file](https://github.com/cockroachdb/cockroach/blob/0210313b7e2ae98bff3ab6c131d9f670311839f3/sql/parser/builtins.go#L997)):*
> ```Go
> 	"to_date": {
> 		Builtin{
> 			Types:      ArgTypes{TypeString, TypeString},
> ```

Are we simply ignoring the second parameter here (and below)? It looks like we should be using it as a template pattern for parsing. See https://www.postgresql.org/docs/8.1/static/functions-formatting.html#FUNCTIONS-FORMATTING-DATETIME-TABLE

---

*[sql/parser/builtins.go, line 1009 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7975#-KNV7gYrUQolFq9jMiow:-KNV7gYrUQolFq9jMiox:-1279073975) ([raw file](https://github.com/cockroachdb/cockroach/blob/0210313b7e2ae98bff3ab6c131d9f670311839f3/sql/parser/builtins.go#L1009)):*
> ```Go
> 		Builtin{
> 			Types:      ArgTypes{TypeString, TypeString},
> 			ReturnType: TypeTimestamp,
> ```

`s/TypeTimestamp/TypeTimestampTZ/`

---

*[sql/parser/builtins.go, line 1012 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7975#-KNV7fuHmf45HUG88vfD:-KNV7fuHmf45HUG88vfE:-1635952554) ([raw file](https://github.com/cockroachdb/cockroach/blob/0210313b7e2ae98bff3ab6c131d9f670311839f3/sql/parser/builtins.go#L1012)):*
> ```Go
> 			fn: func(ctx *EvalContext, args DTuple) (Datum, error) {
> 				s := string(*args[0].(*DString))
> 				return ParseDTimestamp(s, ctx.GetLocation(), time.Nanosecond)
> ```

`s/ParseDTimestamp/ParseDTimestampTZ`

---

*[sql/parser/builtins.go, line 1017 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7975#-KNV7cDqISHHdyvRT0ud:-KNV7cDrwbckerj-fHG7:1131249292) ([raw file](https://github.com/cockroachdb/cockroach/blob/0210313b7e2ae98bff3ab6c131d9f670311839f3/sql/parser/builtins.go#L1017)):*
> ```Go
> 		Builtin{
> 			Types:      ArgTypes{TypeFloat},
> 			ReturnType: TypeTimestamp,
> ```

`s/TypeTimestamp/TypeTimestampTZ/`. Based on the docs, both of these functions should be working with the `timestamp with time zone` type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7975#-:-KNV6tz6pyKm2W5CSF2L:452243597)*

**Comment by yznming** [comment]
@nvanbenschoten thanks for you review.

**Comment by yznming** [comment]
@nvanbenschoten by the way, what kind of pattern do we use? "YYYY MM DD" in pg ? Or "2006 01 02" implemented in cockroachdb?

**Comment by nvanbenschoten** [comment]
@yznming If we are going to support PG-extension builtin functions in CockroachDB, we should aim to expose as similar of an interface as possible. In practice here that would mean supporting an identical (sub-)set of [Template Patterns for Date/Time Formatting](https://www.postgresql.org/docs/8.1/static/functions-formatting.html#FUNCTIONS-FORMATTING-DATETIME-TABLE).

**Comment by mjibson** [comment]
Can you rebase this onto the develop branch and squish it all into one commit then force push it back up here? It's very messy to look at right now.

**Pull request closed without merging**
