### PR TITLE
sql: add cost estimate and distribution to telemetry logging

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds two new fields to the `SampledQuery` structure used for
telemetry logging. We now collect telemetry on the cost for the query
as estimated by the optimizer, as well as the distribution of the DistSQL
plan for the query (local, full, or partial).

Informs #71666

Release note (sql change): The structured payloads used for telemetry
logs now include two new fields: `CostEstimate` and `Distribution`.
`CostEstimate` is the cost of the query as estimated by the optimizer,
and `Distribution` is the distribution of the DistSQL query plan
(local, full, or partial).

### CODE REVIEW

**Comment by vy-ton** [comment]
Will this only apply to the new event logging telemetry or stmtstats as well?

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73278)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rytaft, and @vy-ton)

___
*[pkg/sql/plan_opt.go, line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73278#-MpiJwgkBLrIAqNZRCcm:-MpiJwgkBLrIAqNZRCcn:b-arodrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d92f3c544c0a52fecdfd13b19634059fa89c45b7/pkg/sql/plan_opt.go#L609)):*
> ```Go
> 		planTop.instrumentation.planGist = gf.PlanGist()
> 	}
> 	planTop.instrumentation.costEstimate = float32(mem.RootExpr().(memo.RelExpr).Cost())
> ```

What prompted the choice of `float32` and not `float64`?

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73278)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @vy-ton)

___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73278#-MpkkWur84JdseFf8oCW:-MpkkWus9quj_VvJSoMY:bjea2wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d92f3c544c0a52fecdfd13b19634059fa89c45b7/pkg/util/log/eventpb/sql_audit_events.proto#L45)):*
> ```protobuf
>   // The sequence number of the SQL transaction inside its session.
>   uint32 txn_counter = 9 [(gogoproto.jsontag) = ",omitempty"];
>   // Cost of the query as estimated by the optimizer.
> ```

If the requirement is to include this data in telemetry events only, why put them in CommonSQLExecDetails? Why not just in SampledQuery?

**Review by rytaft — COMMENTED** [review]
> Will this only apply to the new event logging telemetry or stmtstats as well?

This only applies to telemetry. Is there a need to add this to stmtstats too?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73278#-:-MplG8tkDLIrLSeAipVJ:bai5tyc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @vy-ton, and @yuzefovich)

___
*[pkg/sql/plan_opt.go, line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73278#-MpiJwgkBLrIAqNZRCcm:-MplI9h23dT13ZoDCgH5:b-ir0lwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d92f3c544c0a52fecdfd13b19634059fa89c45b7/pkg/sql/plan_opt.go#L609)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

What prompted the choice of `float32` and not `float64`?
</blockquote></details>

I just didn't realize I needed to use "double" in the proto. Fixed.
___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73278#-MpkkWur84JdseFf8oCW:-MplIG_I8oYaFnVTNg29:bqq6vuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d92f3c544c0a52fecdfd13b19634059fa89c45b7/pkg/util/log/eventpb/sql_audit_events.proto#L45)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

If the requirement is to include this data in telemetry events only, why put them in CommonSQLExecDetails? Why not just in SampledQuery?
</blockquote></details>

It seemed to fit well into CommonSQLExecDetails, but you're right that it's only needed in telemetry. Moved out to SampledQuery only.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73278#-:-MplYyLO02VJfKjX1fjl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @vy-ton)

**Comment by rytaft** [comment]
TFTRs! Going to go ahead and merge this. Any additional requirements can be supported in a follow-on PR.

bors r+

**Comment by vy-ton** [comment]
> This only applies to telemetry. Is there a need to add this to stmtstats too?

Let me check on the current status of telemetry and get back here

**Comment by rytaft** [comment]
blathers backport 21.2

**Pull request merged**
