### PR TITLE
testing: fix flaky range split and relocate logic test in distsql_distinct_on

### PR DESCRIPTION
**Pull request by richardwu**
Fixes: #20999

Release notes: none

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Oo, this is great! LGTM

**Comment by benesch** [comment]
Hmm, this actually makes me a little nervous. Every query that needs to be retried in a logic test is a query that clients will need to retry (beyond the usual transactional retry stuff you have to worry about). I'm worried folks might abuse this functionality. I know in this case `TESTING_RELOCATE` is internal-only, but even still I think the right place for the retry loop is inside `TestingRelocateRange`.

I don't feel strongly though.

**Comment by RaduBerinde** [comment]
@benesch I see this as a short term test fix, the command shouldn't fail like that.. We should keep an issue open to track that (if there isn't one already).

**Comment by benesch** [comment]
Ok, the flaky test at hand has been fixed in #21012!

You guys work with the logic tests a lot more than I do, so I'll rescind my earlier argument. I'm 💯 okay with retries if they're meant as a short-term stopgap for something like this. Thanks for putting this together, @richardwu!

**Comment by RaduBerinde** [comment]
If the issue was fixed, I don't think we should add support for `repeat` until we actually need it.

**Pull request closed without merging**
