### PR TITLE
util/tracing: remove references between spans

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Comment by andreimatei** [comment]
First 3 commits are #71170

**Review by andreimatei — COMMENTED** [review]
hold off on the review; I've made further progress here and it's all best reviewed together I think

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-:-MlX4QUPELTjg3Gs-x15:bs7tlkg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

**Review by andreimatei — COMMENTED** [review]
ready for review

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-:-MlpWNoD3XLJyy3DqZJb:b-mfwrtb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 1 of 20 files at r9, 4 of 8 files at r16, 1 of 3 files at r20, 1 of 2 files at r22, 2 of 7 files at r23, 7 of 11 files at r24, 2 of 4 files at r25, 6 of 6 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-:-MlqQP0oAO65WhqBr6P6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/util/tracing/crdbspan.go, line 83 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqNHwVDVG9yDaXISBJ:-MlqNHwVDVG9yDaXISBK:b-ioog6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f98cc744359c901ba5f20880734e418d257df58/pkg/util/tracing/crdbspan.go#L83)):*
> ```Go
> 		// that were manually imported, as well as recordings from local children
> 		// that Finish()ed.
> 		finishedChildren []tracingpb.RecordedSpan
> ```

Would it be cleaner to have a single slice of a struct that contains a `*cdrbSpan` and a `RecordedSpan` and only one can be set? It might simplify some things, like not having to remove from one to add to the other. I guess `RecordedSpan` is pretty big, we don't want to allocate that memory unless we're actually recording?
___
*[pkg/util/tracing/crdbspan.go, line 122 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqMOoe4I1Agj0BbrPk:-MlqMOoe4I1Agj0BbrPl:bshdl5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f98cc744359c901ba5f20880734e418d257df58/pkg/util/tracing/crdbspan.go#L122)):*
> ```Go
> 
> // finish marks the span as finished. Further operations on the span are not
> // allowed. Returns false if the span was already finished.
> ```

Ha, the second sentence is not really compatible with the first :)
___
*[pkg/util/tracing/crdbspan.go, line 490 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqMmlu4fIi-jbTl8tN:-MlqMmlu4fIi-jbTl8tO:bk07ci7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f98cc744359c901ba5f20880734e418d257df58/pkg/util/tracing/crdbspan.go#L490)):*
> ```Go
> 			continue
> 		}
> 		s.mu.recording.openChildren[i] = s.mu.recording.openChildren[l-1]
> ```

Do we not care to maintain the relative ordering of the children? I assume that ordering makes its way into the recording (maybe it doesn't matter because ultimately we only care about the timestamps?)
___
*[pkg/util/tracing/tracer.go, line 189 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqOLiI2R9rDC_JpUHw:-MlqOLiI2R9rDC_JpUHx:b-hfi298) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c36ccd00cca57fe8c9ae44f79d9c8895688b75/pkg/util/tracing/tracer.go#L189)):*
> ```Go
> 	mu struct {
> 		syncutil.Mutex
> 		m map[uint64]*crdbSpan
> ```

[nit] comment that the key is the spanID (or better, make it a specific type)
___
*[pkg/util/tracing/tracer.go, line 212 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqOinR2UJtdTRmOP0j:-MlqOinR2UJtdTRmOP0k:bemquxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c36ccd00cca57fe8c9ae44f79d9c8895688b75/pkg/util/tracing/tracer.go#L212)):*
> ```Go
> 	// Ensure that the registry does not grow unboundedly in case there
> 	// is a leak. When the registry reaches max size, each new span added
> 	// kicks out some old span. We rely on map iteration order here to
> ```

[nit] `some old span` -> `an arbitrary existing span`
___
*[pkg/util/tracing/tracer.go, line 215 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqOvBfEga_lMzVN4HS:-MlqOvBfEga_lMzVN4HT:b4a2vrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c36ccd00cca57fe8c9ae44f79d9c8895688b75/pkg/util/tracing/tracer.go#L215)):*
> ```Go
> 	// make this cheap.
> 	if toDelete := len(r.mu.m) - maxSpanRegistrySize + 1; toDelete > 0 {
> 		for k := range r.mu.m {
> ```

[nit] the toDelete counter seems unnecessary given that this is the only place we insert, we could just break in the first iteration
___
*[pkg/util/tracing/tracer.go, line 252 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqPPst4jgtBgiC-VaB:-MlqPPst4jgtBgiC-VaC:beuv8b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0da237ede7cb669dffd73104729e1870ab3e5d/pkg/util/tracing/tracer.go#L252)):*
> ```Go
> }
> 
> func (r *spanRegistry) all() []*crdbSpan {
> ```

[nit] comment needed here, mentioning the arbitrary ordering
___
*[pkg/util/tracing/tracer.go, line 262 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqPche7FIis5GqVi0-:-MlqPche7FIis5GqVi00:b-ret5rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0da237ede7cb669dffd73104729e1870ab3e5d/pkg/util/tracing/tracer.go#L262)):*
> ```Go
> }
> 
> // swap atomically swaps the span
> ```

more words here, maybe "atomically removes the given span and adds all unfinished children from the slice"

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71291)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @RaduBerinde)

___
*[pkg/util/tracing/crdbspan.go, line 83 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqNHwVDVG9yDaXISBJ:-MlzA5IS2xpFBcDiB2Zc:b8rdsfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f98cc744359c901ba5f20880734e418d257df58/pkg/util/tracing/crdbspan.go#L83)):*
> I guess RecordedSpan is pretty big, we don't want to allocate that memory unless we're actually recording?

This is true, but I don't think we'd necessarily end up allocating space for `RecordedSpans` because `finishedChildren` contains grandchildren too (whereas `openChildren` doesn't); when a child finishes it can result in multiple `finishedChildren` entries. So, to go with your union idea, the union would be between a `*crdbSpan` and a `[]RecordedSpan`. And then it becomes harder to traverse this nested structure, and also to pre-allocate space for the `RecordedSpans` (we don't currently preallocate space for the `RecordedSpans`, but we might in the future). I dunno, I don't think I'd end up with simpler code if I combine them.
___
*[pkg/util/tracing/crdbspan.go, line 122 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqMOoe4I1Agj0BbrPk:-MlznQm4AczNbA028Su8:bq2qutg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f98cc744359c901ba5f20880734e418d257df58/pkg/util/tracing/crdbspan.go#L122)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ha, the second sentence is not really compatible with the first :)
</blockquote></details>

well, technically something can be disallowed and still have a specified behavior :)
But yeah, the struggle is real because, for now, there are actually some use-after-finish, and we tolerate it. I'll be working on catching this in test mode as much as possible. For now, I've added a TODO here with more words.
___
*[pkg/util/tracing/crdbspan.go, line 490 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqMmlu4fIi-jbTl8tN:-MlzD7tZ5Qjbmd3T8Z48:b-govvwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f98cc744359c901ba5f20880734e418d257df58/pkg/util/tracing/crdbspan.go#L490)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we not care to maintain the relative ordering of the children? I assume that ordering makes its way into the recording (maybe it doesn't matter because ultimately we only care about the timestamps?)
</blockquote></details>

I don't care about the ordering... For one, `finishedChildren` are not particularly ordered anyway, and the `finishedChildren` and `finishedChildren` are inter-mixed in recordings. I'd rather have all the consumers/renderers of recordings make no assumptions about the raw data, and have them sort it.
___
*[pkg/util/tracing/tracer.go, line 189 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqOLiI2R9rDC_JpUHw:-MlzeUvu6nIkdkbpogD9:bmdz79q) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c36ccd00cca57fe8c9ae44f79d9c8895688b75/pkg/util/tracing/tracer.go#L189)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] comment that the key is the spanID (or better, make it a specific type)
</blockquote></details>

made spanid and traceid dedicated types and boiled the ocean in a new commit
___
*[pkg/util/tracing/tracer.go, line 212 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqOinR2UJtdTRmOP0j:-MlziUPdCbpK6PKYAL0U:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c36ccd00cca57fe8c9ae44f79d9c8895688b75/pkg/util/tracing/tracer.go#L212)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `some old span` -> `an arbitrary existing span`
</blockquote></details>

done
___
*[pkg/util/tracing/tracer.go, line 215 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqOvBfEga_lMzVN4HS:-Mlzionw6P-IOAMmXKqj:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c36ccd00cca57fe8c9ae44f79d9c8895688b75/pkg/util/tracing/tracer.go#L215)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] the toDelete counter seems unnecessary given that this is the only place we insert, we could just break in the first iteration
</blockquote></details>

done
___
*[pkg/util/tracing/tracer.go, line 252 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqPPst4jgtBgiC-VaB:-MlzmBYx8sO3q9n-O0BN:b-nc66ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0da237ede7cb669dffd73104729e1870ab3e5d/pkg/util/tracing/tracer.go#L252)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] comment needed here, mentioning the arbitrary ordering
</blockquote></details>

done. Also renamed to `testingAll()` and explained that it's just for tests.
___
*[pkg/util/tracing/tracer.go, line 262 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MlqPche7FIis5GqVi0-:-MlzjA5BAp8krp5dtriD:b-b5lwuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e0da237ede7cb669dffd73104729e1870ab3e5d/pkg/util/tracing/tracer.go#L262)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

more words here, maybe "atomically removes the given span and adds all unfinished children from the slice"
</blockquote></details>

yeah I had left this comment unfinished. Fixed.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-:-Mm-i2Wl6CvleJtPhc0Y:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, and @RaduBerinde)

___
*[pkg/util/tracing/tracer.go, line 255 at r45](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-Mm-hykqDE-Q1EBt5PQO:-Mm-hykqDE-Q1EBt5PQP:b-w2ffe6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bef7fcdfac5edc341257270666c4c199267f642b/pkg/util/tracing/tracer.go#L255)):*
> ```Go
> }
> 
> // testingAll returns (pointers to) all the spans in the registry, in a random
> ```

[supernit] "in arbitrary order"
___
*[pkg/util/tracing/tracer.go, line 666 at r45](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-Mm-huOK54ZcrmjjSZZt:-Mm-huOK54ZcrmjjSZZu:b-wu7j48) ([raw file](https://github.com/cockroachdb/cockroach/blob/bef7fcdfac5edc341257270666c4c199267f642b/pkg/util/tracing/tracer.go#L666)):*
> ```Go
> 	traceID := opts.parentTraceID()
> 	if traceID == 0 {
> 		traceID = tracingpb.TraceID(uint64(rand.Int63()))
> ```

[nit] unnecessary `uint64`

**Review by aayushshah15 — APPROVED** [review]
Apologies for holding this up (and thanks for waiting for me to digest this). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-:-MmO_3CRE7xRmr2y-niG:b-hnfq2a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, and @RaduBerinde)

___
*[pkg/util/ring/ring_buffer.go, line 36 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MmOKTD58FVv1qZcNyDM:-MmOKTD58FVv1qZcNyDN:b-abjpod) ([raw file](https://github.com/cockroachdb/cockroach/blob/e476a4f0f08417b9fab497928a864cf430982aa8/pkg/util/ring/ring_buffer.go#L36)):*
> ```Go
> // included elements and available capacity.
> func MakeBuffer(scratch []interface{}) Buffer {
> 	return Buffer{buffer: scratch[:cap(scratch)]}
> ```

What would be the difference between this and just writing `buffer: scratch`? Is it just written this way to make it explicit to the reader that we're "taking over" the entire backing array?

**Review by andreimatei — COMMENTED** [review]
TFTRs !!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-:-MmZJtCP6RNgFqpOS1qP:b-ppj9ni)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @RaduBerinde)

___
*[pkg/util/ring/ring_buffer.go, line 36 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-MmOKTD58FVv1qZcNyDM:-MmZEDVk0PEukTl1c3PW:b-j48mz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e476a4f0f08417b9fab497928a864cf430982aa8/pkg/util/ring/ring_buffer.go#L36)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

What would be the difference between this and just writing `buffer: scratch`? Is it just written this way to make it explicit to the reader that we're "taking over" the entire backing array?
</blockquote></details>

you're right, I don't know why I wrote it like that. Changed.
___
*[pkg/util/tracing/tracer.go, line 255 at r45](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-Mm-hykqDE-Q1EBt5PQO:-MmZEQy-83pODpjdN-9_:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bef7fcdfac5edc341257270666c4c199267f642b/pkg/util/tracing/tracer.go#L255)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[supernit] "in arbitrary order"
</blockquote></details>

done
___
*[pkg/util/tracing/tracer.go, line 666 at r45](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-Mm-huOK54ZcrmjjSZZt:-MmZEeF7DjAY4SfbzJg-:b-7rl0kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bef7fcdfac5edc341257270666c4c199267f642b/pkg/util/tracing/tracer.go#L666)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] unnecessary `uint64`
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71291#-:-MmZd5Sg1zWzUZdSX_1b:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @RaduBerinde)

**Pull request merged**
