### PR TITLE
sql: add SHOW JOB <jobid>

### PR DESCRIPTION
**Pull request by spaskob**
SHOW JOB <jobid> complements SHOW JOBs by allowing to show the status of
a single job.

Release note (sql change): SHOW JOB <jobid>

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Good for a first iteration! Well done.
However before this can commit you can add a 2nd commit on top of this which extends the definition to accept any scalar expression, not just literal integers. 
You'll want to look at the example of CANCEL JOB.

Arguably, I'd even recommend/suggest that you extend `tree.ControlJobs` instead of adding a new node type. make a new `tree.ShowJobs` value of type `JobCommand` (`run_control.go`) and implement the SHOW logic by extending `sql/control_jobs.go`.

This will buy you:
- the ability to specify job IDs as a computed expression
- the ability to SHOW multiple jobs at once using a subquery

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39035#-:-LkT6jR_BNaVFuQsVL8O:b-gvdqiw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Review by knz — COMMENTED** [review]
If you do that I'd even recommend replacing the current AST definition for SHOW JOBS (without an ID) entirely, and replace it by ControlJobs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39035#-:-LkT7nkp0LTjjga55cMt:bi2tpw6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by knz** [comment]
Discussed with @dt - I understand this PR is on the way to better/improved behavior.

Nonetheless, I still think that for an "in-between solution that offers marginal utility", the marginal utility is not achieved by accepting just a literal integer. I think it's worth at least supporting scalar expressions by means of `a_expr` (similar logic to handle the expression as CANCEL). Also, looking at this will provide a worthwhile learning experience.

**Comment by knz** [comment]
@spaskob I'll leave you to think with @dt of a more comprehensive commit message. You've made several choices together which diverge from how we'd achieve this specific bit of functionality in a more "idiomatic" manner. Although these choices are well-motivated, you have not included that motivation in the commit message. Including the motivation upfront would save up some back-and-forth convos.

**Comment by RaduBerinde** [comment]
Note that the planning of `SHOW JOBS` is very different than the other `ControlJobs` variants. `SHOW JOBS` is just sugar for a select statement; `ControlJobs` commands don't return any data. Some of the code decides what planning path to take based on the AST node type so conflating them would make that more complicated.

I also disagree with putting them together from a conceptual standpoint ("control" means changing something, the opposite of "show").

**Comment by RaduBerinde** [comment]
I do agree that we shouldn't need a new AST type. Other similar cases simply use the general version and manufacture a Values statement:
```
cancel_jobs_stmt:
  CANCEL JOB a_expr
  {
    $$.val = &tree.ControlJobs{
      Jobs: &tree.Select{
        Select: &tree.ValuesClause{Rows: []tree.Exprs{tree.Exprs{$3.expr()}}},
      },
      Command: tree.CancelJob,
    }
  }
```

```
  CANCEL QUERY a_expr
  {
    $$.val = &tree.CancelQueries{
      Queries: &tree.Select{
        Select: &tree.ValuesClause{Rows: []tree.Exprs{tree.Exprs{$3.expr()}}},
      },
      IfExists: false,
    }
  }
```

**Comment by dt** [comment]
@RaduBerinde `SHOW` is expected to expand beyond short-hand for a SELECT, by adding an optional flag to use a blocking, polling loop (polling for now -- later ideally a channel to the registry). 

I went back and forth on if these should be grouped or not, and I think I came down sharing: yes, `SHOW` is not "Control" but it is interaction, and all the job _interaction_ statements do have some commonality, so I ended up thinking grouping is okay even if it isn't strictly "control".

We're also planning on making pause and cancel multi-step processes that actually check that their intention is carried out, so the current "control" statements aren't all going to be exact templates anyway. We could jump straight to making individual plan nodes for each of them, but keeping them grouped seemed like it might be conceptually easier since it would be "this is the node that interacts with a job" ?

**Comment by RaduBerinde** [comment]
Using the same plan node for two things with very different mechanics is not a good approach. In one case (CANCEL JOBS), we have an input node from which we read values, and our node returns nothing; in another case (SHOW JOBS) we have no input node but we do return results. This will just turn into a mess of `if`s everywhere and it will make it hard to just read the "flow" for either case.

Note that in all other cases I can think of `SHOW` does not imply any interaction, it just implies retrieving some information. Maybe the variant that waits shouldn't be a `SHOW` variant at all but a new statement like `WAIT`.

In any case, any new variant that has a relational input will need special support in the optimizer. I can do that part after the fact (we can still fall back on the heuristic planner).

**Comment by knz** [comment]
Just to clarify this recent back and forth, let's be clear that there are two separate points:
- whether to use a single AST node or two (this is a trade-off, I say it's not clear cut but I'd tend to suggest we should use just one)
- whether to use a single planNode or two (here the answer is 100% clear and we must use two separate planNodes).

**Comment by RaduBerinde** [comment]
In terms of syntax of `SHOW JOBS`, if we were starting over, I would suggest the following variants:
 - `SHOW JOBS ALL`: shows info about all non-automatic jobs
 - `SHOW JOBS AUTOMATIC`: shows info about all automatic jobs
 - `SHOW JOBS <select-statement>`: shows info about given jobs
 - `SHOW JOB <expr>`: shows info about given job.

Internally these would all be built as the general `SHOW JOBS` with a suitable select statement.

Of course, we have a backward compatibility concern so perhaps a more realistic option would be to keep the current `SHOW [AUTOMATIC] JOBS` and add a `SHOW JOBS FROM <select>` (with a `SHOW JOB <expr>` version).

For the wait versions, I would add separate statements:
 - `WAIT FOR JOBS <select>`
 - `WAIT FOR JOB <expr>`
These will need a special planNode. In the AST, these could be represented as a `JobControl` variant.

**Comment by dt** [comment]
The only part of @RaduBerinde's suggestion I'm not sure about is making WAIT a separate statement: a) the reason you'd wait is almost certainly to get the result, so I'd rather send it than ask you to turn around and send a SHOW after b) I think it is more discoverable under `SHOW JOB` than on its own (I'm thinking of the syntax help, diagrams, etc as well as my eventual hope for grammar-driven tab completion)?

**Comment by RaduBerinde** [comment]
Sorry I wasn't explicit - WAIT would still return the info (it's the same as the proposed statement, just different name).

One detail to consider - can you have this statement inside a view? I'd say no..

**Comment by RaduBerinde** [comment]
I will defer to @jordanlewis on the syntax.

**Comment by knz** [comment]
Spas I think you messed up a rebase. Can you try again?

**Pull request closed without merging**
