### PR TITLE
opt: fix SKIP LOCKED under Read Committed isolation

### LINKED ISSUE #121917: `SELECT FOR UPDATE SKIP LOCKED` skips unlocked rows sometimes?
**Describe the problem**

I'm working on a job queue system backed by CRDB and I've run into a situation I don't understand. I'm hoping someone can shed some light on it for me.

**To Reproduce**

1. Set up a CRDB Serverless cluster.
2. Clone the repro code in [this repo](https://github.com/asg0451/crdbtestjobs).
3. Run with `DATABASE_URL="<db conn str>" NUM_WORKERS=2 go run .`

The program sets up a jobs table (see [schema.sql](https://github.com/asg0451/crdbtestjobs/blob/master/schema.sql)), seeds it with a few jobs, then runs some workers that poll for work using `SELECT FOR UPDATE SKIP LOCKED` [here](https://github.com/asg0451/crdbtestjobs/blob/05356fb1b86ad24fe56dae7b371b250814d0025b/query.sql#L2) 

**Expected behavior**

I expect each worker to grab a job, "process" it, then grab a new one, until no jobs remain. However, observing the log output, you can see that frequently workers fail to find jobs. In fact, It seems like after the first job each gets, it fails to see a new job while the other is working one one. Why is this?

Example run (annotated):
```
time=2024-04-08T00:29:46.725-04:00 level=DEBUG msg="running schema.sql"
time=2024-04-08T00:29:47.175-04:00 level=DEBUG msg="resetting jobs"
time=2024-04-08T00:29:48.629-04:00 level=INFO msg="job found" worker=1 job="{String:a Valid:true}"
time=2024-04-08T00:29:48.673-04:00 level=INFO msg="job found" worker=0 job="{String:b Valid:true}" // See here they both got jobs
time=2024-04-08T00:29:53.888-04:00 level=INFO msg="job finished" worker=0 job="{ID:{Bytes:[42 4 203 147 205 42 74 144 146 202 156 73 71 160 90 207] Valid:true} Name:{String:b Valid:true} CreatedAt:{Time:2024-04-08 04:29:47.29262 +0000 UTC InfinityModifier:finite Valid:true} CompletedAt:{Time:2024-04-08 04:29:48.443138 +0000 UTC InfinityModifier:finite Valid:true} CompletedBy:{String:cc/crdbtestjobs 0 Valid:true}}"
time=2024-04-08T00:29:53.888-04:00 level=INFO msg="job finished" worker=1 job="{ID:{Bytes:[24 96 114 86 121 83 76 129 168 179 161 17 215 75 124 18] Valid:true} Name:{String:a Valid:true} CreatedAt:{Time:2024-04-08 04:29:47.29262 +0000 UTC InfinityModifier:finite Valid:true} CompletedAt:{Time:2024-04-08 04:29:48.422372 +0000 UTC InfinityModifier:finite Valid:true} CompletedBy:{String:cc/crdbtestjobs 1 Valid:true}}"
time=2024-04-08T00:29:54.371-04:00 level=INFO msg="no job found" worker=0  // but now worker 0 can't find any while 1 is working on its
time=2024-04-08T00:29:54.371-04:00 level=INFO msg="job found" worker=1 job="{String:d Valid:true}"
time=2024-04-08T00:29:54.848-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:29:55.349-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:29:55.800-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:29:56.251-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:29:56.739-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:29:57.176-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:29:57.656-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:29:58.117-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:29:58.586-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:29:59.029-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:29:59.475-04:00 level=INFO msg="job finished" worker=1 job="{ID:{Bytes:[98 32 63 71 154 255 64 96 191 82 227 157 177 117 4 16] Valid:true} Name:{String:d Valid:true} CreatedAt:{Time:2024-04-08 04:29:47.29262 +0000 UTC InfinityModifier:finite Valid:true} CompletedAt:{Time:2024-04-08 04:29:54.199079 +0000 UTC InfinityModifier:finite Valid:true} CompletedBy:{String:cc/crdbtestjobs 1 Valid:true}}"
time=2024-04-08T00:29:59.484-04:00 level=INFO msg="no job found" worker=0 // ditto
time=2024-04-08T00:29:59.938-04:00 level=INFO msg="job found" worker=1 job="{String:c Valid:true}"
time=2024-04-08T00:29:59.939-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:00.412-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:00.875-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:01.346-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:01.799-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:02.235-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:02.745-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:03.181-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:03.655-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:04.124-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:04.538-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:04.969-04:00 level=INFO msg="no job found" worker=0
time=2024-04-08T00:30:05.029-04:00 level=INFO msg="job finished" worker=1 job="{ID:{Bytes:[143 160 240 141 130 52 77 159 151 19 223 198 14 146 153 33] Valid:true} Name:{String:c Valid:true} CreatedAt:{Time:2024-04-08 04:29:47.29262 +0000 UTC InfinityModifier:finite Valid:true} CompletedAt:{Time:2024-04-08 04:29:59.789133 +0000 UTC InfinityModifier:finite Valid:true} CompletedBy:{String:cc/crdbtestjobs 1 Valid:true}}"
time=2024-04-08T00:30:05.400-04:00 level=INFO msg="job found" worker=0 job="{String:f Valid:true}" // worker 0 wins the race this time and now worker 1 can't find a job!
time=2024-04-08T00:30:05.431-04:00 level=INFO msg="no job found" worker=1
time=2024-04-08T00:30:05.850-04:00 level=INFO msg="no job found" worker=1
time=2024-04-08T00:30:06.246-04:00 level=INFO msg="no job found" worker=1
time=2024-04-08T00:30:06.655-04:00 level=INFO msg="no job found" worker=1
(ctrl-c for brevity)
```

Contrast this with postgres's behaviour under the same code:
```
time=2024-04-08T02:42:40.602-04:00 level=DEBUG msg="running schema.sql"
time=2024-04-08T02:42:41.026-04:00 level=DEBUG msg="resetting jobs"
time=2024-04-08T02:42:42.392-04:00 level=INFO msg="job found" worker=2 job="{String:a Valid:true}"
time=2024-04-08T02:42:42.392-04:00 level=INFO msg="job found" worker=0 job="{String:c Valid:true}"
time=2024-04-08T02:42:42.392-04:00 level=INFO msg="job found" worker=1 job="{String:b Valid:true}"
time=2024-04-08T02:42:47.547-04:00 level=INFO msg="job finished" worker=2 job="{ID:{Bytes:[123 153 228 234 250 118 67 31 188 172 62 47 39 114 235 127] Valid:true} Name:{String:a Valid:true} CreatedAt:{Time:2024-04-07 23:42:41.218606 +0000 UTC InfinityModifier:finite Valid:true} CompletedAt:{Time:2024-04-07 23:42:42.258571 +0000 UTC InfinityModifier:finite Valid:true} CompletedBy:{String:cc/crdbtestjobs 2 Valid:true}}"
time=2024-04-08T02:42:47.547-04:00 level=INFO msg="job finished" worker=0 job="{ID:{Bytes:[55 177 105 201 234 84 68 211 134 237 144 62 45 182 176 121] Valid:true} Name:{String:c Valid:true} CreatedAt:{Time:2024-04-07 23:42:41.218606 +0000 UTC InfinityModifier:finite Valid:true} CompletedAt:{Time:2024-04-07 23:42:42.258597 +0000 UTC InfinityModifier:finite Valid:true} CompletedBy:{String:cc/crdbtestjobs 0 Valid:true}}"
time=2024-04-08T02:42:47.620-04:00 level=INFO msg="job finished" worker=1 job="{ID:{Bytes:[217 121 73 159 166 146 79 234 140 118 76 52 225 118 36 173] Valid:true} Name:{String:b Valid:true} CreatedAt:{Time:2024-04-07 23:42:41.218606 +0000 UTC InfinityModifier:finite Valid:true} CompletedAt:{Time:2024-04-07 23:42:42.258517 +0000 UTC InfinityModifier:finite Valid:true} CompletedBy:{String:cc/crdbtestjobs 1 Valid:true}}"
time=2024-04-08T02:42:47.982-04:00 level=INFO msg="job found" worker=0 job="{String:d Valid:true}"
time=2024-04-08T02:42:47.987-04:00 level=INFO msg="job found" worker=2 job="{String:e Valid:true}"
time=2024-04-08T02:42:48.034-04:00 level=INFO msg="job found" worker=1 job="{String:f Valid:true}"
time=2024-04-08T02:42:53.091-04:00 level=INFO msg="job finished" worker=0 job="{ID:{Bytes:[174 45 184 28 42 93 76 98 145 129 73 191 190 117 226 255] Valid:true} Name:{String:d Valid:true} CreatedAt:{Time:2024-04-07 23:42:41.218606 +0000 UTC InfinityModifier:finite Valid:true} CompletedAt:{Time:2024-04-07 23:42:47.938799 +0000 UTC InfinityModifier:finite Valid:true} CompletedBy:{String:cc/crdbtestjobs 0 Valid:true}}"
time=2024-04-08T02:42:53.091-04:00 level=INFO msg="job finished" worker=2 job="{ID:{Bytes:[76 229 28 127 149 214 68 210 174 220 73 184 30 206 11 105] Valid:true} Name:{String:e Valid:true} CreatedAt:{Time:2024-04-07 23:42:41.218606 +0000 UTC InfinityModifier:finite Valid:true} CompletedAt:{Time:2024-04-07 23:42:47.935604 +0000 UTC InfinityModifier:finite Valid:true} CompletedBy:{String:cc/crdbtestjobs 2 Valid:true}}"
time=2024-04-08T02:42:53.111-04:00 level=INFO msg="job finished" worker=1 job="{ID:{Bytes:[151 115 250 132 130 210 75 164 130 102 233 183 252 28 183 50] Valid:true} Name:{String:f Valid:true} CreatedAt:{Time:2024-04-07 23:42:41.218606 +0000 UTC InfinityModifier:finite Valid:true} CompletedAt:{Time:2024-04-07 23:42:48.009649 +0000 UTC InfinityModifier:finite Valid:true} CompletedBy:{String:cc/crdbtestjobs 1 Valid:true}}"
time=2024-04-08T02:42:53.540-04:00 level=INFO msg="no job found" worker=1
time=2024-04-08T02:42:53.540-04:00 level=INFO msg="no job found" worker=2
time=2024-04-08T02:42:53.551-04:00 level=INFO msg="no job found" worker=0
(they actually did them all)
```

As you can see, postgres does not have this issue at all.

**Additional data / screenshots**
Everything is in the linked repo

**Environment:**
 - CockroachDB version: Serverless, AWS v23.2.3
 - Server OS: ?
 - Client app golang crdbpgxv5
 

Jira issue: CRDB-37619

EDIT: All of a sudden this stopped happening for NUM_WORKERS=2 -- both of them reliably got jobs. Running with NUM_WORKERS=3 exhibits the issue again. Idk what changed.

### PR DESCRIPTION
**Pull request by michae2**
**opt: do not push LIMIT or OFFSET below locking with SKIP LOCKED**

We were always building the new Lock operator after building Limit
and/or Offset operators in the same SELECT. This is incorrect when the
Lock operator uses SKIP LOCKED, as the Lock might filter out locked rows
that should not count toward a limit or offset.

Instead, build the new Lock operator as input to Limit and/or Offset,
and then use normalization rules to push the Limit and/or Offset below
the Lock if it does not use SKIP LOCKED.

Fixes: #121917

Release note (bug fix): Fix a bug in which SELECT FOR UPDATE or SELECT
FOR SHARE queries using SKIP LOCKED and a LIMIT and/or an OFFSET could
return incorrect results under Read Committed isolation. This bug was
present when support for SKIP LOCKED under Read Committed isolation was
introduced in v24.1.0.

---

**opt: add skip-locked to unlocked scans below SKIP LOCKED**

When using the new Lock operator to implement FOR UPDATE and FOR SHARE,
we build unlocked scans that are then followed by a final Lock
operation. If the Lock operator uses SKIP LOCKED, however, these
unlocked scans still need to be flagged with the skip-locked wait policy
to avoid blocking, even if they do not take locks themselves.

Fixes: #121917

Release note (bug fix): Fix a bug in which some SELECT FOR UPDATE or
SELECT FOR SHARE queries using SKIP LOCKED could still block on locked
rows when using optimizer_use_lock_op_for_serializable under
Serializable isolation. This bug was present when
optimizer_use_lock_op_for_serializable was introduced in v23.2.0.

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
Nicely done! Are there higher level logic (or other) tests we should add that fully exercise the behaviors fixed here. I suspect the second commit would be hard to test, but maybe the first one is easier since it caused incorrect results?

> Reviewed 5 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-:-O2joqPp3H8Ay9oFiIm6:b-7dpid6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2jmgI-4HsPz0W6kt0L):*
> This is incorrect when the Lock operator uses SKIP LOCKED, as the Lock might filter out rows that should not count toward a limit or offset.

Did you mean something like: "... as the Limit might filter out rows that may be locked, and therefore should not count toward the limit or offset"?
___
*[`pkg/sql/opt/norm/testdata/rules/lock` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2jn8Dm2DoZpidYVQIG:-O2jn8Dm2DoZpidYVQIH:buj1imb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c62cb780558c10f63a692e0517253b7055dffd87/pkg/sql/opt/norm/testdata/rules/lock#L1)):*
> ```
> exec-ddl
> ```

nit: We usually put norm rule tests in the file with the same name as the file they are defined (minus the ".opt" suffix), so `limit` in this case.
___
*[`pkg/sql/opt/norm/testdata/rules/lock` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2jnVJ7369NlKjoGhto:-O2jnVJ7369NlKjoGhtp:b-clzdcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c62cb780558c10f63a692e0517253b7055dffd87/pkg/sql/opt/norm/testdata/rules/lock#L19)):*
> ```
> 
> opt set=optimizer_use_lock_op_for_serializable=true expect=PushLimitIntoLock
> SELECT * FROM abcde WHERE d IS NULL LIMIT 1 FOR UPDATE
> ```

nit: `SELECT a` here and below would remove the index join in the test slightly, making it less verbose.

**Review by DrewKimball — APPROVED** [review]
Nice work! :lgtm: once Marcus' comments are addressed.

> Reviewed 5 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-:-O2kCxahCyIkbw3pf847:byzubjy)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/opt/locking.go` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2kAmaV5fNiasb8z_bT:-O2kAmaV5fNiasb8z_bU:b-cl6kbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/93466469973042f842cc375c283aefbc8f74d18a/pkg/sql/opt/locking.go#L94)):*
> ```Go
> // row-level locking mode or (b) the receiver is configured to skip over locks
> // even if not using a row-level locking mode.
> func (l Locking) UsesLockTable() bool {
> ```

[nit] Could we reverse this, and do something like `IsNoLocking`?
___
*[`pkg/sql/opt/norm/testdata/rules/lock` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2jnVJ7369NlKjoGhto:-O2kCpKRCNLdJ0oV5BLV:bobsnn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c62cb780558c10f63a692e0517253b7055dffd87/pkg/sql/opt/norm/testdata/rules/lock#L19)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `SELECT a` here and below would remove the index join in the test slightly, making it less verbose.
</blockquote></details>

Let's keep at least some of them this way, since it shows that the index-join also gets the skip-locked property.

**Comment by mgartner** [comment]
*[`pkg/sql/opt/norm/testdata/rules/lock` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2jnVJ7369NlKjoGhto:-O2kLYLN7cgB1QXBcL9k:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c62cb780558c10f63a692e0517253b7055dffd87/pkg/sql/opt/norm/testdata/rules/lock#L19)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Let's keep at least some of them this way, since it shows that the index-join also gets the skip-locked property.
</blockquote></details>

:+1:

**Review by michae2 — COMMENTED** [review]
TFTRs!

> Are there higher level logic (or other) tests we should add that fully exercise the behaviors fixed here.

Good point! Added some cases to a logic test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-:-O3-fWqNCxP4gTgQra0Z:b-cv0llb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2jmgI-4HsPz0W6kt0L):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> This is incorrect when the Lock operator uses SKIP LOCKED, as the Lock might filter out rows that should not count toward a limit or offset.

Did you mean something like: "... as the Limit might filter out rows that may be locked, and therefore should not count toward the limit or offset"?
</blockquote></details>

It's the Lock operator that is filtering out rows, due to the SKIP LOCKED wait policy. I added the word "locked", maybe that helps?
___
*[`pkg/sql/opt/locking.go` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2kAmaV5fNiasb8z_bT:-O3-kgs52ZeWO2vuE76Y:bxzz1vn) ([raw file](https://github.com/cockroachdb/cockroach/blob/93466469973042f842cc375c283aefbc8f74d18a/pkg/sql/opt/locking.go#L94)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Could we reverse this, and do something like `IsNoLocking`?
</blockquote></details>

How about `IsNonZeroLocking`?
___
*[`pkg/sql/opt/norm/testdata/rules/lock` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2jn8Dm2DoZpidYVQIG:-O3-lS5l-cVdu2X0qn8z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c62cb780558c10f63a692e0517253b7055dffd87/pkg/sql/opt/norm/testdata/rules/lock#L1)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: We usually put norm rule tests in the file with the same name as the file they are defined (minus the ".opt" suffix), so `limit` in this case.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/testdata/rules/lock` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2jnVJ7369NlKjoGhto:-O3-lSwx2kdKl3py2Q75:b-u0jz7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c62cb780558c10f63a692e0517253b7055dffd87/pkg/sql/opt/norm/testdata/rules/lock#L19)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

I tried `SELECT a` but it actually made the plans larger, due to https://github.com/cockroachdb/cockroach/issues/127771. So I've left them as they are.

**Review by DrewKimball — APPROVED** [review]
> Reviewed 1 of 10 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127718)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/opt/locking.go` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2kAmaV5fNiasb8z_bT:-O3039cKA68acF2G-ReJ:b-ctmbbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/93466469973042f842cc375c283aefbc8f74d18a/pkg/sql/opt/locking.go#L94)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

How about `IsNonZeroLocking`?
</blockquote></details>

I'm good with that, too. Another option could be `IsDefault`. Or be more descriptive and say `IsLockingOrSkipLocked`

**Comment by michae2** [comment]
@mgartner do you want to take another look at this one?

**Comment by michae2** [comment]
I'm going to go ahead, and we can look again during backports. TFTRs!

bors r=DrewKimball

**Comment by mgartner** [comment]
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127718#-O2jmgI-4HsPz0W6kt0L):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

It's the Lock operator that is filtering out rows, due to the SKIP LOCKED wait policy. I added the word "locked", maybe that helps?
</blockquote></details>

Oh ya.. ignore me. I was confused.

**Comment by mgartner** [comment]
>@mgartner do you want to take another look at this one?

Sorry I'm so slow. Looks great!

**Pull request merged**
