### PR TITLE
sql/schemachanger: Deprecate ALTER COLUMN TYPE rewrite in the legacy schema changer

### PR DESCRIPTION
**Pull request by spilchen**
This change deprecates the legacy schema changer for ALTER COLUMN TYPE operations that require a column rewrite. While the legacy schema changer remains available for mixed-version clusters, starting in version 25.1, these operations must use the declarative schema changer.

Additionally, this update includes the following improvements:
- Updated error messages for blocking conditions to clarify that they apply only when the ALTER COLUMN TYPE requires a column rewrite. Each error now includes a hint for resolving the issue.
- Enforce that the sql_safe_updates setting must be disabled to perform operations requiring a column rewrite. This is necessary to prevent potential data loss when converting between DECIMAL or TIMESTAMP data types or when applying a USING expression.

Epic: CRDB-25314
Informs: #49329
Release note (sql change): The sql_safe_updates setting must be disabled to perform ALTER COLUMN TYPE operations that require a column rewrite.

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 18 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136110)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @asg0451, @nameisbhaskar, @spilchen, and @vidit-bhat)

___
*[`pkg/sql/alter_column_type.go` line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136110#-OCZ5pMy6iYRo0NkQzyt:-OCZ5pMy6iYRo0NkQzyu:b2xtlln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7ecf83fa10ee11bd923cf14791d2b9582d81d1a/pkg/sql/alter_column_type.go#L238)):*
> ```Go
> 	// to ensure consistent error messages for scenarios that overlap with the DSC.
> 	if params.p.execCfg.Settings.Version.IsActive(ctx, clusterversion.V25_1) {
> 		return pgerror.New(pgcode.FeatureNotSupported,
> ```

Can you confirm that we don't have any fallbacks for regional by row tables with the declarative schema changer? Trying to make sure we don't expose any regression here.
___
*[`pkg/ccl/changefeedccl/cdctest/row.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136110#-OCZ5ajX4_CP9y0prcEN:-OCZ5ajX4_CP9y0prcEO:bm93zwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7ecf83fa10ee11bd923cf14791d2b9582d81d1a/pkg/ccl/changefeedccl/cdctest/row.go#L35)):*
> ```Go
> 	t testing.TB, execCfgI interface{}, desc catalog.TableDescriptor,
> ) (func(t testing.TB) *kvpb.RangeFeedValue, func()) {
> 	reader, cleanup := MakeRangeFeedValueReaderExtended(t, execCfgI, desc)
> ```

This seems unrelated?

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136110)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @asg0451, @fqazi, @nameisbhaskar, and @vidit-bhat)

___
*[`pkg/ccl/changefeedccl/cdctest/row.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136110#-OCZ5ajX4_CP9y0prcEN:-OCZp5Fz0BOXte_gcoKT:bp51k2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7ecf83fa10ee11bd923cf14791d2b9582d81d1a/pkg/ccl/changefeedccl/cdctest/row.go#L35)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This seems unrelated?
</blockquote></details>

This change is related to the test update in `event_test.go`. With the legacy schema changer now blocked, the test needed adjustment. Since a column rewrite involves dropping the old column, it triggered a delete range event that the test wasn’t accounting for. This update enables the test to detect and handle delete range events by returning the relevant state.
___
*[`pkg/sql/alter_column_type.go` line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136110#-OCZ5pMy6iYRo0NkQzyt:-OCZomj8-xLFlt6ZpjBe:bj909oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7ecf83fa10ee11bd923cf14791d2b9582d81d1a/pkg/sql/alter_column_type.go#L238)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Can you confirm that we don't have any fallbacks for regional by row tables with the declarative schema changer? Trying to make sure we don't expose any regression here.
</blockquote></details>

I confirmed that there are no fallbacks. Since I couldn’t find any existing tests, I added a logic test.

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 19 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136110#-:-OCZt-5GEXoVVE4-xcYn:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @asg0451, @nameisbhaskar, and @vidit-bhat)

**Comment by spilchen** [comment]
TFTR!

bors r+

**Pull request merged**
