### PR TITLE
sql: introduce SHOW [SESSION] KV TRACE [FOR ...]

### PR DESCRIPTION
**Pull request by knz**
Needed for #15948

This patch introduces the two statement variants:

    SHOW SESSION KV TRACE
    SHOW KV TRACE FOR ...

This filters the output of the session trace to focus on K/V
events. For example:

```
root@localhost:26257/> SELECT age, message FROM [SHOW KV TRACE FOR SELECT * from t.kv];
+------------+----------------------------------------------------------+
|    age     |                         message                          |
+------------+----------------------------------------------------------+
| 0s         | querying next range at /Table/64/1                       |
| 50µs142ns  | r311: sending batch 1 Scan to (n1,s1):1                  |
| 348µs775ns | fetched: /kv/primary/1/w -> /248515719827193857          |
| 359µs826ns | output row: [1 NULL 248515719827193857 NULL]             |
| 367µs707ns | fetched: /kv/primary/12/v/w -> /444/242235410454642689   |
| 371µs977ns | output row: [12 444 242235410454642689 NULL]             |
| 378µs886ns | fetched: /kv/primary/13/v/w -> /123/242235410454708225   |
| 382µs966ns | output row: [13 123 242235410454708225 NULL]             |
| 389µs133ns | fetched: /kv/primary/1234/v/w -> /456/253631669707800577 |
| 396µs154ns | output row: [1234 456 253631669707800577 NULL]           |
+------------+----------------------------------------------------------+
```

Additionally, the patch also makes `SHOW TRACE` use window functions
to ensure each row has a copy of the `operation` field and an `age`
field.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/show.go, line 598 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn58UIXvLD_qSVIOalv:-Kn58UIXvLD_qSVIOalw:b-oa8sso) ([raw file](https://github.com/cockroachdb/cockroach/blob/943d882e8e8aaaef3c40f79228b992e4707fe150/pkg/sql/show.go#L598)):*
> ```Go
> 	if n.OnlyKVTrace {
> 		whereClause = `
> WHERE message LIKE 'fetched: %'
> ```

These seem pretty fragile, though I don't have a good alternative. Could we start these messages with a special prefix `KV:` and check for that?

---

*[pkg/sql/show.go, line 643 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5AcVGWJe3aIwG3goT:-Kn5AcVGWJe3aIwG3goU:b-9qt259) ([raw file](https://github.com/cockroachdb/cockroach/blob/943d882e8e8aaaef3c40f79228b992e4707fe150/pkg/sql/show.go#L643)):*
> ```Go
> 	// inject the tracePlan inside the SHOW query plan.
> 	done := false
> 	if s, ok := plan.(*sortNode); ok {
> ```

I understand what's going on here but it's pretty hairy. It would be cleaner if `traceNode` would internally:
 - first run a wrapped plan, and generate `output row: ` events
 - then, run a separate query plan that's supposed to read from `crdb_internal.session_trace` and process it in some way (this would replace the direct call to `n.p.session.Tracing.generateSessionTraceVTable`)

Another thought is changing the `traceNode` to return no results, and make the outer query always be a `UNION` between the traceNode and the query on `session_trace` (though this is tricky because it relies on unionNode running the two plans in a certain order).

---

*[pkg/sql/show.go, line 657 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn59QYc7tiZ6X7-YMDA:-Kn59QYc7tiZ6X7-YMDB:b4lksuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/943d882e8e8aaaef3c40f79228b992e4707fe150/pkg/sql/show.go#L657)):*
> ```Go
> 							r.source.plan.Close(ctx)
> 							r.source.plan = tracePlan
> 							done = true
> ```

can just `return plan, nil`

---

*[pkg/sql/trace.go, line 84 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn57qd9OlN80FQf6lYA:-Kn57qd9OlN80FQf6lYB:b-s7t0m4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c0366b27e21d123b415c2dd276fbc2ba9450e8e/pkg/sql/trace.go#L84)):*
> ```Go
> 	if n.p.session.Tracing.Enabled() {
> 		// Start has already ran and enabled tracing. Stop it.
> 		_ = stopTracing(n.p.session)
> ```

seems like we should at least log any error here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622)*

**Comment by knz** [comment]
Review status: 0 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/show.go, line 598 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn58UIXvLD_qSVIOalv:-Kn5GVeX_RnG5WcAGX62:b-fwjxly) ([raw file](https://github.com/cockroachdb/cockroach/blob/943d882e8e8aaaef3c40f79228b992e4707fe150/pkg/sql/show.go#L598)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

These seem pretty fragile, though I don't have a good alternative. Could we start these messages with a special prefix `KV:` and check for that?
</blockquote></details>

1) This is tested. If the strings change, the tests will fail.

2) Some of these messages are not KV-specific but useful/necessary to understand a KV trace, for example "fast path" or "execution failed". I would find it confusing/detrimental to see a "kv:" prefix there whereas the operations have nothing to do with KV. If you have another idea of prefix, I can think about it some more.

---

*[pkg/sql/show.go, line 643 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5AcVGWJe3aIwG3goT:-Kn5GvpQk-DqI6nUsSkp:bwxbyaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/943d882e8e8aaaef3c40f79228b992e4707fe150/pkg/sql/show.go#L643)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I understand what's going on here but it's pretty hairy. It would be cleaner if `traceNode` would internally:
 - first run a wrapped plan, and generate `output row: ` events
 - then, run a separate query plan that's supposed to read from `crdb_internal.session_trace` and process it in some way (this would replace the direct call to `n.p.session.Tracing.generateSessionTraceVTable`)

Another thought is changing the `traceNode` to return no results, and make the outer query always be a `UNION` between the traceNode and the query on `session_trace` (though this is tricky because it relies on unionNode running the two plans in a certain order).
</blockquote></details>

Both your suggestions are currently not possible because of the way Andrei designed this code.
The root problem is that we can't (currently) create the vtable reader for the session trace before the last event in the trace which we want to observe in the vtable.

I do not want to solve that problem in this PR: I do not understand that code well, and it is an orthogonal issue anyway. My path here is set to remove EXPLAIN(DEBUG), and both SHOW TRACE FOR and EXPLAIN(DEBUG) are historically fragile anyway -- it doesn't matter because we (crdb developers) are the only audience (so far).

I propose to keep this approach here until that other problem is solved (by Andrei, as a clean-up).

---

*[pkg/sql/show.go, line 657 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn59QYc7tiZ6X7-YMDA:-Kn5Fr7lpEuKCULVusXc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/943d882e8e8aaaef3c40f79228b992e4707fe150/pkg/sql/show.go#L657)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

can just `return plan, nil`
</blockquote></details>

Done.

---

*[pkg/sql/trace.go, line 84 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn57qd9OlN80FQf6lYA:-Kn5FtsOMPNnPMLL95If:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c0366b27e21d123b415c2dd276fbc2ba9450e8e/pkg/sql/trace.go#L84)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

seems like we should at least log any error here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 18 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show.go, line 643 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5AcVGWJe3aIwG3goT:-Kn5Q-DyzMU9ew9ionvi:b11tif3) ([raw file](https://github.com/cockroachdb/cockroach/blob/943d882e8e8aaaef3c40f79228b992e4707fe150/pkg/sql/show.go#L643)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Both your suggestions are currently not possible because of the way Andrei designed this code.
The root problem is that we can't (currently) create the vtable reader for the session trace before the last event in the trace which we want to observe in the vtable.

I do not want to solve that problem in this PR: I do not understand that code well, and it is an orthogonal issue anyway. My path here is set to remove EXPLAIN(DEBUG), and both SHOW TRACE FOR and EXPLAIN(DEBUG) are historically fragile anyway -- it doesn't matter because we (crdb developers) are the only audience (so far).

I propose to keep this approach here until that other problem is solved (by Andrei, as a clean-up).
</blockquote></details>

Sure, maybe leave a TODO somewhere outlining the alternatives.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-:-Kn5Q2IjecrdNm8fR_qT:bnfp4nl)*

**Comment by knz** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/show.go, line 643 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5AcVGWJe3aIwG3goT:-Kn5Sq0VVLXh6cknff3W:b-peafp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/943d882e8e8aaaef3c40f79228b992e4707fe150/pkg/sql/show.go#L643)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Sure, maybe leave a TODO somewhere outlining the alternatives.
</blockquote></details>

:+1: 

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622)*

**Comment by knz** [comment]
TFYR! 

I'll merge this now to advance on #15948. Andrei feel free to follow-up with improvement/clean-up suggestions.

**Comment by andreimatei** [comment]
Good stuff, but:

1) I think the syntax `SHOW [SESSION] TRACE(KV)  [FOR ...]` might be better; analogous to `EXPLAIN(METADATA)`

2) The way we've added logging around calls to `Batch` methods seems really nasty to me... Some of them already existed (which scared me), and you've added more. There's got to be a better way. I think we should resume the PR or the discussions around: https://github.com/cockroachdb/cockroach/pull/9169

3) I think we should find a better way to identify and set in stone the messages that are part of "KV" traces.

---

Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show.go, line 585 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5vIqnf5_Dm5jfZJeC:-Kn5vIqo545sEEFcp76n:b-atl4n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b3018436d62dcbcd74c6f2219ed067c0ba298f/pkg/sql/show.go#L585)):*
> ```Go
>        span
>   FROM (SELECT timestamp,
>                regexp_replace(message, e'^.*\\[[^]]*\\] ', '') AS message,
> ```

I don't know what these two lines do :) 

---

*[pkg/sql/show.go, line 596 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5sVrzgHRrjnZp69li:-Kn5sVrzgHRrjnZp69lj:b-xzxa0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b3018436d62dcbcd74c6f2219ed067c0ba298f/pkg/sql/show.go#L596)):*
> ```Go
> 	if n.OnlyKVTrace {
> 		whereClause = `
> WHERE message LIKE 'fetched: %'
> ```

this is going to rot... I was thinking that all messages that get used in tracing tests (or, even more so, in tracing-relating external functionality, like this one), should be listed in a central place, or be identified by constants with some prefix.

---

*[pkg/sql/show.go, line 651 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5vst4lE2MctorkxzH:-Kn5vst4lE2MctorkxzI:b-p2c0nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b3018436d62dcbcd74c6f2219ed067c0ba298f/pkg/sql/show.go#L651)):*
> ```Go
> 	// Unfortunately, neither is currently possible because the plan for
> 	// the query on session_trace cannot be constructed until the trace
> 	// is complete. If we want to enable EXPLAIN [SHOW TRACE FOR ...],
> ```

I don't understand this... Why does the tracing need to be complete for the plan of the query on the vtable to be constructed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-:-Kn5rRbVbtBJ9Yxm8i_K:b-ae5jxr)*

**Comment by knz** [comment]
1. the syntax `EXPLAIN(XXX)` will soon go away too. Also, options-between-parentheses are a bitch to support cleanly.

2. yes I wasn't happy by the solution either, but I didn't know how to do better for now and I really need to get this explain(Debug) replacement going. I do not fully understand the discussion around #9169 but when I tried to do something similar yesterday I realized I needed to plumb tracing flags through the KV interface to the internal/client code, which is super hard to do cleanly. The existing logging code in SQL was added by peter to troubleshoot important stuff, I am kinda expecting he also didn't find a better/nicer way.

3. ok, care to provide concrete suggestions? For now, those I have used are exercised in tests, so any fragility will be caught up in case of surreptitious changes.

---

Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show.go, line 585 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5vIqnf5_Dm5jfZJeC:-Kn6DTD6_kufUcY1PFIn:b-sh9pyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b3018436d62dcbcd74c6f2219ed067c0ba298f/pkg/sql/show.go#L585)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't know what these two lines do :) 
</blockquote></details>

a message has the form `filename:linenum [some logging tags] message`
These two lines extract the part "`filename:linenum [some logging tags]`" as a separate field `context` and remove it from the message.

---

*[pkg/sql/show.go, line 596 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5sVrzgHRrjnZp69li:-Kn6DdTpsS8k2CKxgj3d:bykg9zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b3018436d62dcbcd74c6f2219ed067c0ba298f/pkg/sql/show.go#L596)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this is going to rot... I was thinking that all messages that get used in tracing tests (or, even more so, in tracing-relating external functionality, like this one), should be listed in a central place, or be identified by constants with some prefix.
</blockquote></details>

It's exercised in tests, that's pretty much the definition of rot resistance.

---

*[pkg/sql/show.go, line 651 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5vst4lE2MctorkxzH:-Kn6Dig35_Pp2T7JT0HY:bsq86sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b3018436d62dcbcd74c6f2219ed067c0ba298f/pkg/sql/show.go#L651)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't understand this... Why does the tracing need to be complete for the plan of the query on the vtable to be constructed?
</blockquote></details>

What about you try to do it the way you want and after that we talk?

You already have multiple times argued that SHOW TRACE FOR should work in a different way. I tried, and I failed, and I even explained you why. Whether you disagree or not you should trust me that I did the best I could. So if you want better, teach me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-:-Kn6CmVHO9kyhhnq0ezc:bzhddy9)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/show.go, line 651 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622#-Kn5vst4lE2MctorkxzH:-KnA2gScYEaLKef-qSEA:btpypse) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b3018436d62dcbcd74c6f2219ed067c0ba298f/pkg/sql/show.go#L651)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What about you try to do it the way you want and after that we talk?

You already have multiple times argued that SHOW TRACE FOR should work in a different way. I tried, and I failed, and I even explained you why. Whether you disagree or not you should trust me that I did the best I could. So if you want better, teach me.
</blockquote></details>

I think it's a valid question - I thought the virtual table stuff was under a `delayedNode` and nothing happened until we actually `Start` the plan (though I'll admit I'm not very familiar with how delayed nodes work). If we're missing something it would be good to know what that is before one of us wastes time going down the same path. Main reason I'm asking is that we may need to refactor some of this to allow `SHOW TRACE FOR ...` to  work with distsql, depending on the approach we choose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16622)*

**Pull request merged**
