### PR TITLE
github: add bulk-io owners rules

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Comment by knz** [comment]
did you want to include cli/dump.go and cli/dump_test.go as well?

**Review by pbardea — APPROVED** [review]

**Comment by dt** [comment]
TFTRs, and thanks for catching dump too!

bors r+

**Comment by RaduBerinde** [comment]
Is this working? We've had `sql-opt-prs` set up similarly but it seems to have stopped working recently (it doesn't get added to PRs anymore).

**Comment by knz** [comment]
I'm also surprised at the notation "@cockroachdb/teams/bulk-prs"  -- I'd have expected "@cockroachdb/bulk-prs"  which is what I use to notify in comments.

**Pull request merged**
