### PR TITLE
build: remove pointless rebuilds of cluster-ui

### PR DESCRIPTION
**Pull request by jordanlewis**
Since 60916fb31b1, any change to any file in any subdirectory of pkg/ui
would cause a full rebuild of pkg/ui/cluster-ui, which would then cause
a full rebuild of pkg/ui as well.

Now, pkg/ui/cluster-ui's source files are tracked separately, so changes
to pkg/ui/ that don't touch cluster-ui won't force a rebuild of
cluster-ui.

This should save a lot of time, hopefully. Touching a single .tsx file
in pkg/ui/src used to cause 30+ seconds of build time due to this issue,
now it is significantly faster since the various webpack caches can
actually be used again.

Release note: None

cc @cockroachdb/cluster-ui-prs @cockroachdb/sql-observability

### CODE REVIEW

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68038#-:-MfY9a6mAL8HQjQC40YX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @koorosh)

___
*[Makefile, line 1351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68038#-MfY71V1-hK3a4IFbdGB:-MfY71V1-hK3a4IFbdGC:b88jdn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf146032a6a81166e983a7987b57855f297bea2e/Makefile#L1351)):*
> ```Makefile
> .SECONDARY: $(CLUSTER_UI_JS)
> 
> $(CLUSTER_UI_JS): pkg/ui/yarn.installed $(shell find pkg/ui/cluster-ui/src -type f | grep -v " ")
> ```

This grep caught my attention, so I went looking to see how many files it would exclude. It turns out it's just a couple of font files, nbd. Would it be worth a comment here? (Alternatively (nerd snipe alert), is there a way to escape the spaces? Like printf %q or something?)

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68038)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @koorosh and @matthewtodd)

___
*[Makefile, line 1351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68038#-MfY71V1-hK3a4IFbdGB:-MfYA5Ar86K-YiEUchLP:b-obe32t) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf146032a6a81166e983a7987b57855f297bea2e/Makefile#L1351)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

This grep caught my attention, so I went looking to see how many files it would exclude. It turns out it's just a couple of font files, nbd. Would it be worth a comment here? (Alternatively (nerd snipe alert), is there a way to escape the spaces? Like printf %q or something?)
</blockquote></details>

Added a comment. I couldn't figure out how to deal with this :( https://stackoverflow.com/questions/9838384/can-gnu-make-handle-filenames-with-spaces

**Review by matthewtodd — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68038)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @koorosh)

**Pull request merged**
