### PR TITLE
storage: simplify scatter implementation

### LINKED ISSUE #17612: storage: 17 replicas on a range configured for 3
Noticed on `sky` that after creating 1m ranges we have 9m replicas. Chose a random range (1000) and found 17 replicas. Looks like the replicate queue is churning away removing replicas, but how did we get into this situation. Seems like the `AllocatorRemove` action is preferred over `AllocatorNoop`, though there is this one oddity:

```
	liveReplicas, deadReplicas := a.storePool.liveAndDeadReplicas(rangeInfo.Desc.RangeID, rangeInfo.Desc.Replicas)
	if len(liveReplicas) < quorum {
		// Do not take any removal action if we do not have a quorum of live
		// replicas.
		return AllocatorNoop, 0
	}
```

### PR DESCRIPTION
**Pull request by petermattis**
Rather than using custom logic in Replica.adminScatter, call into
replicateQueue.processOneChange until no further action needs to be
taken. This fixes a major caveat with the prior implementation: replicas
were not removed synchronously leading to conditions where an arbitrary
number of replicas could be added to a range via scattering.

Fixes #17612

### CODE REVIEW

**Comment by petermattis** [comment]
All of the tests still pass, which makes me suspect that scatter isn't well tested.

@benesch I'm curious if you can run this on restore workloads to see if it has any negative impact. My suspicion is that it will be fine, but I'd prefer to be cautious at this time in the cycle.

**Comment by petermattis** [comment]
I should mention that I've been testing this on `sky` and it provides near ideal scattering in my testing. And the implementation seems easier to understand conceptually. In effect, it temporarily provides a dedicated goroutine to the replicate queue for the specified replica.

**Comment by benesch** [comment]
Yes, the one scatter test (see split_at_test.go) is currently disabled
because it's too flaky to be useful. The only tests that exercise the code
path in any useful fashion are the restore production tests.

**Comment by a-robinson** [comment]
LGTM. I like the simplicity of this much more than what was there before, but I'd wait on @benesch to test how it works for restore in practice (and perhaps double check what was causing problems in the original scatter implementation). This still suffers from the problems in #17341, but that's a feature more than a bug at this point in the release cycle.

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17644#-:-KrYskTXbjiNs9ipR-qz:b8qtz3a)*

**Comment by petermattis** [comment]
This might actually speed up RESTORE as now we'll only ever be restoring into 3 replicas while previously we could be restoring into 6. 🤞

**Comment by benesch** [comment]
Running restore tests now!

**Comment by benesch** [comment]
Well, this is odd:

screenshot 2017-08-15 11 02 17

**Comment by petermattis** [comment]
@benesch Can you try running again with `set cluster setting kv.allocator.stat_based_rebalancing.enabled = false`?

**Comment by benesch** [comment]
For posterity, the whole thing took 28m. It usually takes about 15m, I think. Here's the final state:

screenshot 2017-08-15 11 23 06

Rerunning without stats rebalancing now.

**Comment by benesch** [comment]
Bingo. Though now I don't know whether to be happy or worried.

screenshot 2017-08-15 11 54 55

If you don't mind, I want to run two controls before stamping this.

**Comment by petermattis** [comment]
Yep, take your time.

@a-robinson This is evidence towards #17645 or that stats-based rebalancing still needs tuning.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_command.go, line 3995 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17644#-KragAA5A_R1p9fMEard:-KragAA5A_R1p9fMEare:bpoj6m6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb145a0eaea2842aa857993848602d4276cc8d8d/pkg/storage/replica_command.go#L3995)):*
> ```Go
> 	var allowLeaseTransfer bool
> 	for re := retry.StartWithCtx(ctx, retryOpts); re.Next(); {
> 		canTransferLease := func() bool { return false }
> ```

You can do `canTransferLease := func() bool { return allowLeaseTransfer }` outside the loop (but I guess that forces a heap allocation? If that's significant here add a comment so someone doesn't try to simplify it in the future). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17644#-:-KragYA81H3EWSniT3ME:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica_command.go, line 3995 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17644#-KragAA5A_R1p9fMEard:-KragsGVQ23DlJGaPU_S:b-k1j6uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb145a0eaea2842aa857993848602d4276cc8d8d/pkg/storage/replica_command.go#L3995)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

You can do `canTransferLease := func() bool { return allowLeaseTransfer }` outside the loop (but I guess that forces a heap allocation? If that's significant here add a comment so someone doesn't try to simplify it in the future). 
</blockquote></details>

Clever. I can't imagine the heap allocation is problematic here. Changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17644)*

**Comment by benesch** [comment]
Ok, seems to match TPCH10 on a recent master (301e5fc) without stats-based rebalancing:

screenshot 2017-08-15 12 50 10

Things seem _really_ broken with stats-based rebalancing:

screenshot 2017-08-15 13 20 53

In both cases the restore took about 22m. Turns out there's a default cluster setting limiting the RESTORE write rate to 30MB/s, which is why these aren't taking the 15m I was expecting. 

So: LGTM! 🎉

**Review by benesch — APPROVED** [review]

**Comment by benesch** [comment]
@petermattis, we should shrink the test you've been running on Sky and turn it into an acceptance test for scatter.

**Comment by petermattis** [comment]
@benesch Yes, scatter needs better testing. The test would essentially be `kv --concurrency 512 --splits 1000000 --max-ops 1`. Question is how to determine whether scatter worked well. I suppose we could look at the number of replicas vs ranges and the balance across the cluster.

**Comment by benesch** [comment]
Yeah, I think the criteria for success is actually straightforward to measure. I'll file an issue.

**Comment by benesch** [comment]
Never mind. I just saw #17660.

**Pull request merged**
