### PR TITLE
workload/schemachange: fix unique constraint validation on inserts

### LINKED ISSUE #125751: pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [duplicate key value violates unique constraint]
pkg/ccl/testccl/workload/schemachange/schemachange_test.TestWorkload [failed](https://tanzanite.cluster.engflow.com/invocations/default/d69323ef-e091-4fed-90c4-28a75281fe8b?testReportRun=21&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL3Rlc3RjY2wvd29ya2xvYWQvc2NoZW1hY2hhbmdlOnNjaGVtYWNoYW5nZV90ZXN0) on release-24.1.2-rc @ [35c3e0c133c56c91399e730f49bc488cf6dd4c11](https://github.com/cockroachdb/cockroach/commits/35c3e0c133c56c91399e730f49bc488cf6dd4c11):

```
   },
   {
    "query": "SELECT ARRAY[parent.table_schema, parent.table_name, quote_ident(parent.column_name), quote_ident(child.column_name)] FROM (SELECT conname, conkey, confkey, conrelid, confrelid FROM pg_constraint WHERE (contype = 'f') AND (conrelid = 'schema_w0_26.table_w1_16'::REGCLASS::INT8)) AS con JOIN (SELECT column_name, ordinal_position, column_default FROM information_schema.columns WHERE (table_schema = 'schema_w0_26') AND (table_name = 'table_w1_16')) AS child ON conkey[1] = child.ordinal_position JOIN (SELECT pc.oid, cols.table_schema, cols.table_name, cols.column_name, cols.ordinal_position FROM pg_class AS pc JOIN pg_namespace AS pn ON pc.relnamespace = pn.oid JOIN information_schema.columns AS cols ON ((pc.relname = cols.table_name) AND (pn.nspname = cols.table_schema))) AS parent ON ((con.confkey[1] = parent.ordinal_position) AND (con.confrelid = parent.oid)) WHERE child.column_name != 'rowid'",
    "result": null
   }
  ],
  "previousStatements": [
   "CREATE SEQUENCE IF NOT EXISTS schema_w1_13.seq_w1_15",
   "CREATE TABLE schema_w0_26.table_w1_16 (col16_w1_17 BYTES NOT NULL, col16_w1_18 BOOL, \"col1'6_w1_19\" STRING COLLATE de_DE NOT NULL, \"co!l16_w1_20\" FLOAT8 NOT NULL, col16_w1_21 OID NULL, \"co l16_w1_22\" \"char\" NULL, col16_w1_23 OID, col16_w1_24 NAME NOT NULL, \"c!ol16_w1_25\" JSONB NULL, \"/co\"\"l16_w1_26\" INT4 NULL, \"col16'_w1_27\" FLOAT8 NOT NULL, col16_w1_28 GEOMETRY NOT NULL, col16_w1_29 BYTES, col16_w1_30 INTERVAL, \"col16\\\\xa4_w1_31\" JSONB NOT NULL, \"c̍ol\r16_w1_32\" INT8 NULL, col16_w1_33 FLOAT4 NULL, UNIQUE ((\"c̍ol\r16_w1_32\" + \"/co\"\"l16_w1_26\") ASC), INDEX (col16_w1_21 ASC) STORING (col16_w1_18, \"co l16_w1_22\", col16_w1_24, col16_w1_28, col16_w1_29, col16_w1_30, \"col16\\\\xa4_w1_31\", col16_w1_33) VISIBILITY 0.35, UNIQUE (col16_w1_21, col16_w1_33 ASC, \"co l16_w1_22\", \"co!l16_w1_20\", col16_w1_24, \"/co\"\"l16_w1_26\" ASC, col16_w1_23 DESC, \"c!ol16_w1_25\", \"col1'6_w1_19\" ASC, col16_w1_29 ASC, \"col16'_w1_27\" DESC, col16_w1_30 DESC) STORING (\"c̍ol\r16_w1_32\"), INDEX (\"/co\"\"l16_w1_26\" DESC) VISIBILITY 0.78, UNIQUE (\"co!l16_w1_20\" DESC) STORING (\"col1'6_w1_19\", \"co l16_w1_22\", col16_w1_23, \"c!ol16_w1_25\", col16_w1_29, \"c̍ol\r16_w1_32\", col16_w1_33), UNIQUE (\"c̍ol\r16_w1_32\", \"c!ol16_w1_25\" ASC) STORING (col16_w1_18, col16_w1_21, \"co l16_w1_22\", col16_w1_23, \"col16'_w1_27\", col16_w1_29), UNIQUE (col16_w1_17 ASC, col16_w1_23 DESC, \"/co\"\"l16_w1_26\", (\"co!l16_w1_20\" + col16_w1_33) ASC, \"c̍ol\r16_w1_32\" DESC, col16_w1_30 ASC, \"col1'6_w1_19\" DESC, col16_w1_18 ASC, col16_w1_33, \"co l16_w1_22\" DESC, col16_w1_21 DESC, col16_w1_24, \"col16\\\\xa4_w1_31\"), INDEX (((col16_w1_33 + \"co!l16_w1_20\") + \"col16'_w1_27\") DESC, col16_w1_17 DESC) STORING (\"co!l16_w1_20\", \"co l16_w1_22\", \"c!ol16_w1_25\", \"/co\"\"l16_w1_26\", col16_w1_28, col16_w1_30, \"col16\\\\xa4_w1_31\", \"c̍ol\r16_w1_32\", col16_w1_33), FAMILY (col16_w1_28), FAMILY (\"c!ol16_w1_25\", \"/co\"\"l16_w1_26\", \"col1'6_w1_19\"), FAMILY (col16_w1_17, \"co!l16_w1_20\", \"c̍ol\r16_w1_32\"), FAMILY (col16_w1_23), FAMILY (\"col16'_w1_27\", col16_w1_33, col16_w1_18), FAMILY (col16_w1_29, col16_w1_21, col16_w1_30, \"co l16_w1_22\"), FAMILY (\"col16\\\\xa4_w1_31\", col16_w1_24))",
   "INSERT INTO schema_w0_26.table_w1_16 (col16_w1_17,col16_w1_18,\"col1'6_w1_19\",\"co!l16_w1_20\",col16_w1_21,\"co l16_w1_22\",col16_w1_23,col16_w1_24,\"c!ol16_w1_25\",\"/co\"\"l16_w1_26\",\"col16'_w1_27\",col16_w1_28,col16_w1_29,col16_w1_30,\"col16\\\\xa4_w1_31\",\"c̍ol\r16_w1_32\",col16_w1_33) VALUES ('\\x023ced01':::BYTES,false,e'\\U000EB4C9\\U000736C7\\U000099C0\\U000921E5\\U00045705' COLLATE de_DE,0.0:::FLOAT8,3615:::OID,'r'::\"char\",90000:::OID,e'\\x1b\u003eb\\'\\x1a'::NAME:::NAME,'[{\"1hv\": 0.38380800823336125, \"7WxqdP4AB\": null, \"baz\": [null, null, \"foobar\"], \"foo\": 0.907397094710884, \"ugRAfVWU\": {\"JQJcy\": {\"a\": null, \"bar\": 3.002055136213273, \"baz\": null, \"c\": true, \"nGgF\": 2.17228485738689}, \"b\": 4.230072051680517, \"c\": null}}, [{\"SUakUeu3\": true, \"foo\": null}, true, true, \"40Trg\"], [true, \"Q7\"], 1.5442406476676414, false]':::JSONB,37:::INT8,0.03362331446017158:::FLOAT8,'01030000400100000009000000304B18C62C5BFEC14264212D9682E5C1ACE2193BAAC0E9C17890B0335096F3C1945BFC082192DCC1CC133593BEC3FB41D29EC1A5C5F5EAC1F0B6A0765CEDFAC1BC637B436FCCFCC1806F3BC1D4D8CAC170CE868D214DDEC1B26E314677B7E8C1181495FB3FB3FC41E029FDF0E578F1419E82ECF1A49702C2845C6BED763CE2C1386212840ADDD841E44EA06D06CCFCC1F204676B0AF7F7C1E67DDCA38677FA413CC0E76D70F9DBC1F777FC922135FEC14C56870AB8E2F64150F683983E32F041304B18C62C5BFEC14264212D9682E5C1ACE2193BAAC0E9C1':::GEOMETRY,'\\x':::BYTES,'-46 years -5 mons -223 days -05:40:23.327262':::INTERVAL,'{\"M67m\": [\"uO\"], \"QlAJ8\": 0.2984358503836573, \"bar\": false, \"baz\": [false, true]}':::JSONB,35:::INT8,NULL),('\\xfbd8549fcb4aaefc':::BYTES,false,e'\\U0009C42B\\U00085B2A\\U000C744F\\U000E4FDF\\U0002BB56\\U000A35F5\\U000426AC\\U000A9710\\U00090456' COLLATE de_DE,(-0.0):::FLOAT8,25:::OID,e'\\t'::\"char\",25:::OID,'xv'::NAME:::NAME,'{\"Vbd7hGv\": null, \"b\": false, \"foo\": null, \"foobar\": true, \"xGb\": [true, \"F7S31Rn\", null]}':::JSONB,(-14):::INT8,(-0.0):::FLOAT8,'010300000001000000040000005E8185305D1FFBC16EB241EE4693F9C10C7AD3BEE23EFC410275525CE3AE004250C11B155577DB41C88EE1720F1EF9415E8185305D1FFBC16EB241EE4693F9C1':::GEOMETRY,'\\x8fa9d3':::BYTES,'22 years 7 mons 766 days 21:10:49.653636':::INTERVAL,'{\"baz\": null, \"ekOJV\": \"baz\", \"foobar\": [{\"WT5\": \"ivo\", \"c\": \"ZjK\", \"pvrkZrlV4\": null}, 0.1520572319319641]}':::JSONB,80:::INT8,(-0.5707768797874451):::FLOAT8),('\\x4a865ab00cdb26':::BYTES,true,e'\\U000544BC\\U00034862\\U00002365\\U000D1477\\U00014352\\U0007CE3F\\U00012D93\\U000CED2B\\U000B2E39' COLLATE de_DE,0.565243544913826:::FLOAT8,23:::OID,NULL,1042:::OID,e'W,a\\x14oDzEs'::NAME:::NAME,'{\"TaspG7Xh\": null, \"Wp4ACJz\": [true, false], \"foo\": false}':::JSONB,(-92):::INT8,(-0.6868296594875365):::FLOAT8,'0104000040070000000101000040ACE6E1B8B953EB41F5745416CC32F2C180A1B2C83E87BE410101000040E81D08607E98DEC1FA67C4BC84C4FFC14C71DCEC952EEA4101010000400003AB4BC52EAEC1C28E8A14C92901C2A6F239AC41B7ECC10101000040F0B8E7A76A4FCB4146674AC6E246FFC1429E28587AA6FBC101010000401ED2ED63E2C200C214B7ABD0CC19E4415844B6500516EA410101000040F69ED0814A16E2C190DB9023B8D2EE41ECEDCD117894F4C101010000405076B681EA99F0C1F85A8036D74AF1416E4E1EDAED980242':::GEOMETRY,'\\x99de039695':::BYTES,'-60 years -6 mons -67 days -22:19:34.49658':::INTERVAL,'{\"CNUC\": [\"foobar\", false], \"J6kVDa5sR\": 1.1159178169162471, \"PpU1S\": [0.8765462788257372, null, 2.5343532601068546], \"c\": {\"1gnkJe\": true, \"a\": 0.09615373174932818, \"bar\": [[{\"bB\": false}, true], true, {\"c\": 2.0295542174376866, \"foobar\": 0.2833705668899665}, 2.8665298085920394, true], \"prrOQpZ\": false}}':::JSONB,125:::INT8,(-0.6805527806282043):::FLOAT8)"
  ]
 }
}
    schema_change_external_test.go:132: 
        	Error Trace:	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:132
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: duplicate key value violates unique constraint "table_w1_16_co!l16_w1_20_key" (SQLSTATE 23505)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2)
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*opStmt).executeStmt
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:3120
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:511
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:605
        	            	  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.TestWorkload.func4.func6
        	            	  | 	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:121
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1695
        	            	Wraps: (4) ***UNEXPECTED ERROR; Received an unexpected execution error.
        	            	Wraps: (5) ERROR: duplicate key value violates unique constraint "table_w1_16_co!l16_w1_20_key" (SQLSTATE 23505)
        	            	Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.withPrefix (5) *pgconn.PgError
        	Test:       	TestWorkload
Schema Workload Stats
Total Schema Statements Executed = 36
Total Schema Statements Succeeded = 36
Total Schema Statement Expected Failures = 0
Total Transactions Committed = 21
Total Transactions Rolled Back = 43
Total Transactions Executed = 64
    schema_change_external_test.go:98: backup, tracing data, and system table dumps in /var/lib/engflow/worker/work/1/exec/bazel-out/k8-fastbuild/testlogs/pkg/ccl/testccl/workload/schemachange/schemachange_test/run_21_of_25/test.outputs/logTestWorkload2109485748
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestWorkload2109485748
--- FAIL: TestWorkload (11.98s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=21</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-39611

### LINKED ISSUE #127134: roachtest: schemachange/mixed-versions failed [duplicate key value violates unique constraint]
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16065584?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16065584?buildTab=artifacts#/schemachange/mixed-versions) on release-24.2 @ [d4ef0343f38a35fb781b6343697b57a58131c68e](https://github.com/cockroachdb/cockroach/commits/d4ef0343f38a35fb781b6343697b57a58131c68e):

```
(mixedversion.go:620).Run: mixed-version test failure while running step 20 (run "run schemachange workload and validation in mixed version"): full command output in run_062938.632294620_n4_COCKROACHRANDOMSEED3.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/mixed-versions/cpu_arch=arm64/run_1
```

Parameters:
 - <code>ROACHTEST_arch=arm64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16065584/schemachange-mixed-versions/1720938092773/1720938771293)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #126883 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-24.1]
- #126374 roachtest: schemachange/mixed-versions failed [existing descriptors that still need to be dropped] [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-master]
- #125379 roachtest: schemachange/mixed-versions failed [attempting to append refresh spans after the tracked timestamp has moved forward] [C-test-failure O-roachtest O-robot T-sql-queries branch-release-23.2]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40290

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the unique constraint validation during an insert would attempt to join between the existing rows on the table and the new row. If a floating point generated expression was used then this join could potentially return incorrect results, because the optimizer could remove constants and simplify arithmetic. For example if the expression was simply "col1 + 0.1", then the optimizer could remove the increment and check if col1 is equal on both sides. With integer arithmetic this would be valid, but with floating point its possible for us to miss rows and assume a value is unique (i.e. after adding 0.1 and due to floating point imprecision, its possible the inserted value would be equal). To address this, the unique constraint violation query will use CTEs for the existing values and new value we are inserting, which will prevent this optimization from kicking in.

Fixes: #125751
Fixes: https://github.com/cockroachdb/cockroach/issues/127134

Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126753)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, and @srosenberg)

___
*[`pkg/workload/schemachange/error_screening.go` line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126753#-O1O2tqe4QsVn1i7BJfd:-O1O2tqe4QsVn1i7BJfe:b-io8xae) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b16ea2b2745d292ad3a554f4332c7c845f2b3f3/pkg/workload/schemachange/error_screening.go#L394)):*
> ```Go
> 			// Note: We could have done a join query instead, but the optimizer can be clever
> 			// and potentially optimize out constants, which could lead to failures as
> 			// seen in #125751, for floating point values.
> ```

let's make sure someone from SQL Queries takes a look, so they can decide to leave that issue open to track the bug, or if this is considered expected.

**Review by rafiss — APPROVED** [review]
lgtm, as long as Queries is aware too

**Comment by fqazi** [comment]
@rafiss TFTR! Yes, this was on their channel and I'll follow up with them. 

bors r+

**Comment by fqazi** [comment]
bors retry

**Review by michae2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126753)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

___
*[`pkg/workload/schemachange/error_screening.go` line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126753#-O1O2tqe4QsVn1i7BJfd:-O1u0Ffl4V_XOIfh32NX:bltnczu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b16ea2b2745d292ad3a554f4332c7c845f2b3f3/pkg/workload/schemachange/error_screening.go#L394)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

let's make sure someone from SQL Queries takes a look, so they can decide to leave that issue open to track the bug, or if this is considered expected.
</blockquote></details>

@fqazi would it be ok with you if I reopen #125751 to be about the optimizer folding away those constants?

**Comment by rafiss** [comment]
I reopened https://github.com/cockroachdb/cockroach/issues/125751 for you and moved it to SQL Queries.

**Pull request merged**
