### PR TITLE
sql,util: add keys for empty arrays to array inverted indexes

### PR DESCRIPTION
**Pull request by rytaft**
Prior to this commit, empty arrays were not stored in inverted indexes on
arrays. In order to add support for inverted joins with array inverted
indexes in a future commit, it is necessary to add a key encoding for an
empty array. As of this commit, empty arrays will now be stored in inverted
indexes, keyed by the newly added key for empty arrays. Note that the type
is not stored in the key, so this encoding is not round-trippable.

This commit adds a complication for users upgrading from a prior version
of CockroachDB who already have inverted indexes built on some of their
array columns. These indexes will either need to be updated to index any
pre-existing empty arrays in the column, or any new functionality depending
on the existence of empty arrays in the index cannot be used on those indexes.

To handle this complication, this commit adds a new `IndexDescriptorVersion`
`EmptyArraysInInvertedIndexesVersion`, as well as a new cluster version,
`VersionEmptyArraysInInvertedIndexes`. New functionality depending on the
existence of empty arrays in inverted indexes will need to check whether
the index version is at least `EmptyArraysInInvertedIndexesVersion`.

Release note (backward-incompatible change): Previously, empty arrays
were not contained in inverted indexes on array columns. Now, rows containing
an empty array in the indexed column will have an entry in the inverted index.
This change is backward-incompatible because prior versions of the database
will not be able to recognize and decode the key for the empty array. Note
that rows containing NULL in the indexed column will still not be included
in the inverted index.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Just want to make sure I understand the motivation: If we are doing an inverted join with `x @> y`, where `y` is the lookup column and `x` is the indexed column, and happen to encounter a `y` that is the empty array, we need to include the `x` which is an empty array in the result. If the expression happened to also have a conjunction with another function involving `x` that provided a constraint that excluded the empty array, we would not have had this problem.
In this case, the expression `x @> y` has reduced to true, so we need to scan the whole inverted index. So the index is worthless for the lookup of this left row. But it might be helpful for the other left rows, which is why we planned an inverted join.
Is my understanding correct?
Do our stats include how many `y` rows are an empty array? It may give us a more accurate cost. Though I am guessing this is going to be a rare case. 
 

> Reviewed 19 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-:-MKe7UYdD6csmWE6M27A:b9fqzgj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/catalog/descpb/structured.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-MKe43jB5r1uhngVGI7n:-MKe43jB5r1uhngVGI7o:bwd5k2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e56253294cc82f313af5a15bb116f23aae773a/pkg/sql/catalog/descpb/structured.go#L106)):*
> ```Go
> 	// that is identical to SecondaryIndexFamilyFormatVersion, but also includes a key encoding
> 	// for empty arrays in array inverted indexes.
> 	EmptyArraysInInvertedIndexesVersion
> ```

Can the version of an existing index be changed to this, or does it require creating a new index?
___
*[pkg/sql/rowenc/index_encoding.go, line 794 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-MKe4m966lv1zM27RglL:-MKe4m966lv1zM27RglM:b-7c8t5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e56253294cc82f313af5a15bb116f23aae773a/pkg/sql/rowenc/index_encoding.go#L794)):*
> ```Go
> 	switch val.ResolvedType().Family() {
> 	case types.JsonFamily:
> 		return json.EncodeInvertedIndexKeys(inKey, val.(*tree.DJSON).JSON)
> ```

The same empty encoding issue apply to JSON arrays, too, yes? But we don't need to pass this parameter since JSON arrays were already encoding the empty array? Could you add a code comment -- it is odd to see a general-sounding `version` parameter being only passed to one of the encoding functions.
___
*[pkg/sql/sem/builtins/builtins.go, line 4106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-MKe6Ptk3Lh3zuEsOdZ9:-MKe6Ptk3Lh3zuEsOdZA:b-jc3muy) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e56253294cc82f313af5a15bb116f23aae773a/pkg/sql/sem/builtins/builtins.go#L4106)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Int),
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				// The version argument is currently ignored for JSON inverted indexes.
> ```

Could you add a sentence to say why.

**Review by rytaft — COMMENTED** [review]
> Just want to make sure I understand the motivation ...

Yep, exactly. The stats should tell us when the input column includes the empty array, and in that case we should avoid planning an inverted join since, as you noted, it will require a full index scan. But if the stats are stale or a user forces an inverted join with the INVERTED join hint, we should still return correct results (even though the performance will be very bad). There are also other join predicates that will return the empty array with good performance (e.g., `x <@ y`, once I implement logic for using "is contained by" with inverted joins).

> Do our stats include how many y rows are an empty array?

The inverted index histograms do include this, but we need to improve the stats code to teach it that empty arrays will cause a full table scan with "contains" predicates. I plan to do this in a future PR during this release.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-:-MKeDc8zCpi-qnYgZzwp:b-tx1igy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/catalog/descpb/structured.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-MKe43jB5r1uhngVGI7n:-MKeGhaQ8xpVylf4bF7r:bncbcrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e56253294cc82f313af5a15bb116f23aae773a/pkg/sql/catalog/descpb/structured.go#L106)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can the version of an existing index be changed to this, or does it require creating a new index?
</blockquote></details>

I don't think there is a way to change the version after index creation.
___
*[pkg/sql/rowenc/index_encoding.go, line 794 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-MKe4m966lv1zM27RglL:-MKeS3MR7skKYdjBbkUx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e56253294cc82f313af5a15bb116f23aae773a/pkg/sql/rowenc/index_encoding.go#L794)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The same empty encoding issue apply to JSON arrays, too, yes? But we don't need to pass this parameter since JSON arrays were already encoding the empty array? Could you add a code comment -- it is odd to see a general-sounding `version` parameter being only passed to one of the encoding functions.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 4106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-MKe6Ptk3Lh3zuEsOdZ9:-MKeTTfUA2eJs27baKsG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73e56253294cc82f313af5a15bb116f23aae773a/pkg/sql/sem/builtins/builtins.go#L4106)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you add a sentence to say why.
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-:-MKg5NJl90frqgphfU02:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @sumeerbhola)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 10 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55970)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @rytaft, and @sumeerbhola)

___
*[pkg/sql/rowenc/index_encoding_test.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-MKjPne21QN8NziwPOnh:-MKjPne21QN8NziwPOni:boc1nl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c905879156624a424683e223f915ab9184d9b061/pkg/sql/rowenc/index_encoding_test.go#L294)):*
> ```Go
> 		value                           tree.Datum
> 		expectedKeys                    int
> 		expectedKeysExcludingEmptyArray int
> ```

This test made me look again at `encodeArrayInvertedIndexTableKeys` and I must be misreading something, because I don't see how it is handling nested arrays -- the single loop calls `EncodeTableKey` which returns a single key. What am I missing?

Also, I tried the following on postgres 12.1
```
select array[[1],[2]] @> array[1] as val;
 val 
-----
 t
(1 row)

select array[[1],[2]] @> array[1,7] as val;
 val 
-----
 f
(1 row)
```
It looks like it is ok with different levels of nesting.
On the other PR comment, your postgres query had returned an error -- which version are you running.

**Comment by rytaft** [comment]
___
*[pkg/sql/rowenc/index_encoding_test.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-MKjPne21QN8NziwPOnh:-MKjRxfi6tKJalfzcp3V:b5ri1f2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c905879156624a424683e223f915ab9184d9b061/pkg/sql/rowenc/index_encoding_test.go#L294)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This test made me look again at `encodeArrayInvertedIndexTableKeys` and I must be misreading something, because I don't see how it is handling nested arrays -- the single loop calls `EncodeTableKey` which returns a single key. What am I missing?

Also, I tried the following on postgres 12.1
```
select array[[1],[2]] @> array[1] as val;
 val 
-----
 t
(1 row)

select array[[1],[2]] @> array[1,7] as val;
 val 
-----
 f
(1 row)
```
It looks like it is ok with different levels of nesting.
On the other PR comment, your postgres query had returned an error -- which version are you running.

</blockquote></details>

I don't think I was running that on Postgres -- CockroachDB returns an error with those queries:
```
demo@127.0.0.1:61517/movr> select array[[1],[2]] @> array[1] as val;
ERROR: unsupported comparison operator: <int[][]> @> <int[]>
SQLSTATE: 22023

demo@127.0.0.1:61517/movr> select array[[1],[2]] @> array[1,7] as val;
ERROR: unsupported comparison operator: <int[][]> @> <int[]>
SQLSTATE: 22023
```

Looks like we aren't fully compatible with Postgres in this case, but if we want to fix the compatibility issues I think that should be a separate PR...

**Comment by rytaft** [comment]
___
*[pkg/sql/rowenc/index_encoding_test.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-MKjPne21QN8NziwPOnh:-MKjV6bQ6CuUGm-YSeFK:b-w78cwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c905879156624a424683e223f915ab9184d9b061/pkg/sql/rowenc/index_encoding_test.go#L294)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think I was running that on Postgres -- CockroachDB returns an error with those queries:
```
demo@127.0.0.1:61517/movr> select array[[1],[2]] @> array[1] as val;
ERROR: unsupported comparison operator: <int[][]> @> <int[]>
SQLSTATE: 22023

demo@127.0.0.1:61517/movr> select array[[1],[2]] @> array[1,7] as val;
ERROR: unsupported comparison operator: <int[][]> @> <int[]>
SQLSTATE: 22023
```

Looks like we aren't fully compatible with Postgres in this case, but if we want to fix the compatibility issues I think that should be a separate PR...
</blockquote></details>

Also, CockroachDB doesn't support nested arrays as a column type:
```
demo@127.0.0.1:61644/movr> create table t as values (array[[1],[2],[]]), (array[array[]::int[]]);
ERROR: nested array unsupported as column type: int[][]
```

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 21 files at r1, 5 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-:-MKjc3IV6ERT1eXNFzkZ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @rytaft, and @sumeerbhola)

___
*[pkg/sql/rowenc/index_encoding_test.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55970#-MKjPne21QN8NziwPOnh:-MKjbJgCARpDjZ6XwjJj:bll9qb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c905879156624a424683e223f915ab9184d9b061/pkg/sql/rowenc/index_encoding_test.go#L294)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Also, CockroachDB doesn't support nested arrays as a column type:
```
demo@127.0.0.1:61644/movr> create table t as values (array[[1],[2],[]]), (array[array[]::int[]]);
ERROR: nested array unsupported as column type: int[][]
```
</blockquote></details>

That makes a lot more sense.

**Comment by rytaft** [comment]
TFTRs!

bors r+

**Pull request merged**
