### PR TITLE
server: retry session creation if session isn't ready

### LINKED ISSUE #98452: kv/kvserver: TestSnapshotAfterTruncationWithUncommittedTail failed
kv/kvserver.TestSnapshotAfterTruncationWithUncommittedTail [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9021047?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9021047?buildTab=artifacts#/) on master @ [95684388bfbb372ac8c7e1a8ebd4a0d6f447e147](https://github.com/cockroachdb/cockroach/commits/95684388bfbb372ac8c7e1a8ebd4a0d6f447e147):

Fatal error:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3f54197]

```
Stack: 

```
goroutine 37281265 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0x3?, {0x7405278, 0xc012b35c50})
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:229 +0x6a
panic({0x55274a0, 0xa421860})
	GOROOT/src/runtime/panic.go:884 +0x212
github.com/cockroachdb/cockroach/pkg/server.(*refreshInstanceSessionListener).OnSessionDeleted.func1({0xc009955400, 0x0})
	github.com/cockroachdb/cockroach/pkg/server/server_sql.go:472 +0x117
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestSnapshotAfterTruncationWithUncommittedTail
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestSnapshotAfterTruncationWithUncommittedTail2652869066
    test_log_scope.go:79: use -show-logs to present logs inline
*
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:884
*   | runtime.panicmem
*   | 	GOROOT/src/runtime/panic.go:260
*   | runtime.sigpanic
*   | 	GOROOT/src/runtime/signal_unix.go:835
*   | github.com/cockroachdb/cockroach/pkg/server.(*refreshInstanceSessionListener).OnSessionDeleted.func1
*   | 	github.com/cockroachdb/cockroach/pkg/server/server_sql.go:472
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
*   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
*   | runtime.goexit
*   | 	GOROOT/src/runtime/asm_amd64.s:1594
* Wraps: (2) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) runtime.errorString
*
```
</p>
</details>
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/replication
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSnapshotAfterTruncationWithUncommittedTail.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25276

### LINKED ISSUE #98734: server: server can drop out of instance table if session recreation fails
There is [a hook in the `refreshInstanceSessionListener` struct in server_sql.go](https://github.com/dt/cockroach/blob/e550952ddcba82ee9c44531064a79c7debb97b55/pkg/server/server_sql.go#L463) that re-runs liveness session creation and then instance row creation on liveness session loss. 

If you are a running, happy sql server, you _need_ to have a row recording your presence in the instances table: this is how other sql servers will discover you, send you distsql plans, have you help run backups, do your share of ttl work, etc. We are going to rely on the fact that a running sql server == a row in the instance table, so we need to ensure this is true at all times.

Now if a sql server loses its liveness session, then its row in that instance table is eligible for, and will be subject to, deletion by any other node immediately. Of course this is intentional, since the server could have crashed, but it can also happen while the server is still up due to any sort of ephemeral issue with the network, the nodes hosting the liveness range, etc. So if a server notices that it lost its liveness session, it will run this hook and try to a new one, and this hook is where we can ensure that the server puts itself back in the instance table, where it is required to be, once it has recreated its liveness session. Specifically, the hook calls the blocking function `Session()` to wait for the new session to be created, then uses that session to recreate the instance row. It was written under the assumption that `Session()` always block until a new session has been acquired.  

Now a recent crash in an unrelated test indicated that it is possible for Session() to return an error rather than a non-nil session, after which the hook crashes since it de-references the nil session in trying to create the instance row. This indicates that the hook obviously should not proceed to try to make an instance row when Session() fails, but that leaves us in a bind: we still need to remake an instance row, since we're obligated to have one if we're a running server.

Thus it appears we need to place the body of this hook in a retry loop that will run indefinitely until either a) the server once again has a valid session, at which time it should also have an instance row, or b) the server is stopped.

Jira issue: CRDB-25478

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

Fixes #98452.
Fixes #98734.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @erikgrinaker)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQbeAXg4LF_AGST2hxd:bra9l1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
> ```Go
> ) (createAnotherSession bool) {
> 	if err := r.cfg.stopper.RunAsyncTask(ctx, "refresh-instance-session", func(context.Context) {
> 		for ctx.Err() == nil {
> ```

1) can you add a check of stopper.ShouldQuiesce in here otherwise it will get stuck if requesting shutdown while this loop is active.

2) what problem are you solving here?

The non-loopy behavior of this code (that you are removing here) was actually helping with another problem we don't have a better solution for yet: #83650.
(My PR #96144 will fix that more durably, but until then the keyspace error we encounter here if the tenant keyspace is not ready is the next best thing)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @knz)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQbj90HByTUEx4nBIN2:bdbl9to) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
> what problem are you solving here?

Well, there's proximate problem around nils and error checks, but the fact it happened pointed to a deeper problem.

But before we get to either of those, let's look at why we have this code: if you are a running, happy sql server, you need to have a row recording your presence in the instances table: this is how other servers will discover you, send you distsql plans, backups, ttl work, etc. We are going to _rely_ on the fact that a running sql server == a row in the instance table, so we need to ensure it is tune.

Now if a sql server loses its session, its row in that instance table is eligible for and will be subject to deletion by any other node. So if you lost your session and got a new one, you _need_ to put yourself back in the instance table. That's what the block of code in this hook is doing: it calls the blocking function `Session()` to wait for the new session to be created, then uses that session to recreate the instance row. 

Now back to the change at hand: previously you will see that if we failed to get a new session from `Session()`, we logged the error but then continued to try to use the session we didn't get to make the row leading to a nilptr crash. So if we fail to get a session, we obviously need to _not_ proceed to try to create the instance row. But that raises the deeper issue: even if we failed to get a session, we still _need_ to remake an instance row, since we're obligated to have one if we're a running server. So just bailing out if `Session()` errors isn't an option. Thus the loop.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @knz)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQbqdaSDjkDQK8BuynZ:bs7vqng) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

> what problem are you solving here?

Well, there's proximate problem around nils and error checks, but the fact it happened pointed to a deeper problem.

But before we get to either of those, let's look at why we have this code: if you are a running, happy sql server, you need to have a row recording your presence in the instances table: this is how other servers will discover you, send you distsql plans, backups, ttl work, etc. We are going to _rely_ on the fact that a running sql server == a row in the instance table, so we need to ensure it is tune.

Now if a sql server loses its session, its row in that instance table is eligible for and will be subject to deletion by any other node. So if you lost your session and got a new one, you _need_ to put yourself back in the instance table. That's what the block of code in this hook is doing: it calls the blocking function `Session()` to wait for the new session to be created, then uses that session to recreate the instance row. 

Now back to the change at hand: previously you will see that if we failed to get a new session from `Session()`, we logged the error but then continued to try to use the session we didn't get to make the row leading to a nilptr crash. So if we fail to get a session, we obviously need to _not_ proceed to try to create the instance row. But that raises the deeper issue: even if we failed to get a session, we still _need_ to remake an instance row, since we're obligated to have one if we're a running server. So just bailing out if `Session()` errors isn't an option. Thus the loop.
</blockquote></details>

(re: 1: added stopper+ctx doneness checking)

**Review by knz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @erikgrinaker)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQbqwvQ2ZWR811AyN23:bt0ajmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

(re: 1: added stopper+ctx doneness checking)
</blockquote></details>

Please duplicate your explanation above into an issue and cc me on it. I need to add it to our MT weekly review.
___
*[`pkg/server/server_sql.go` line 478 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbrAq_CU87ny3u_PUX:-NQbrAq_CU87ny3u_PUY:bj85sf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e550952ddcba82ee9c44531064a79c7debb97b55/pkg/server/server_sql.go#L478)):*
> ```Go
> 			if err != nil {
> 				log.Warningf(ctx, "failed to get new liveness session ID: %v", err)
> 				continue
> ```

may i suggested a jittered wait to avoid a busy loop here.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @knz)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQbvVLxCThURo62IaSM:b-l3dye9) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Please duplicate your explanation above into an issue and cc me on it. I need to add it to our MT weekly review.
</blockquote></details>

https://github.com/cockroachdb/cockroach/issues/98734
___
*[`pkg/server/server_sql.go` line 478 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbrAq_CU87ny3u_PUX:-NQbshKYBuDQ95hni95p:b-bk6u3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e550952ddcba82ee9c44531064a79c7debb97b55/pkg/server/server_sql.go#L478)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

may i suggested a jittered wait to avoid a busy loop here.
</blockquote></details>

Added retry w/backoff up to 5s.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @knz)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQbw7_vEPwW-DdWl7iQ:bu0rkx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/issues/98734
</blockquote></details>

re: service mode and server controller: how does this make the service mode change case worse? does it just loop forever? 

I think most worried right now about a single sql server for system tenant in a kv node, i.e. classic/legacy/whatever case: the panic fixed here is real, if rare, and the the obligation to be in the instance table is there too once #98527 lands.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @knz)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQbx0G6-FjFjHamzZmk:b-xwzn4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

re: service mode and server controller: how does this make the service mode change case worse? does it just loop forever? 

I think most worried right now about a single sql server for system tenant in a kv node, i.e. classic/legacy/whatever case: the panic fixed here is real, if rare, and the the obligation to be in the instance table is there too once #98527 lands.
</blockquote></details>

actually, the obligation is already there since jobs started relying on the instance table being accurate even for single-proc single-system-tenant clusters already to get locality info. So we really can't let this hook _not_ succeed if a server isn't shutting down.

**Review by erikgrinaker — APPROVED** [review]
FWIW, this LGTM, but I'll let Raphael wrap up the discussion.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQdsFhBBfpq8RXN03Tr:bu8ntr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
> we really can't let this hook not succeed if a server isn't shutting down.

could you manually check (no need for unit test) that if a server startup is indeed hung up on this loop, that it's still possible to abort the startup entirely by removing its service mode (setting it to NONE)?  If that indeed works we're out of the woods -- I just want to avoid this being a source of deadlocks during emergency shutdown.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQeJPZy4xv2NeDPuutL:b-3co9wt) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

> we really can't let this hook not succeed if a server isn't shutting down.

could you manually check (no need for unit test) that if a server startup is indeed hung up on this loop, that it's still possible to abort the startup entirely by removing its service mode (setting it to NONE)?  If that indeed works we're out of the woods -- I just want to avoid this being a source of deadlocks during emergency shutdown.
</blockquote></details>

Any ideas on _how_ to get hung in this loop?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQeLNSUAjRiUzJ4uDjz:bbm7lxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Any ideas on _how_ to get hung in this loop?
</blockquote></details>

for testing purposes only? I'd say change the code to `if nodeID == 2 { log.Warningf(ctx, "fake error"); continue }`
and make it a 3 node cluster?
or some other manual code change that injects an error.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/server/server_sql.go` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-NQbeAXg4LF_AGST2hxc:-NQfx3_-4tNsOQYxwz5P:bm4px9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/70bf8729bd9ef5a9fc27c97a4014d482a142fb70/pkg/server/server_sql.go#L466)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

for testing purposes only? I'd say change the code to `if nodeID == 2 { log.Warningf(ctx, "fake error"); continue }`
and make it a 3 node cluster?
or some other manual code change that injects an error.
</blockquote></details>

with @knz's help offline, I ran through this test in both `demo` and `roachprod`, with that patch running on a 5 node cluster, created a tenant in shared mode, in that tenant ran `delete from system.sql_instances where true; delete from system.sqlliveness where true;`, verified the row for the node with the special-case didn't reappear and found the stack where it was sitting in the retry loop. Then ran `roachprod stop --sig 15 local` and observed the node that was in the loop exit.

**Review by knz — APPROVED** [review]
nice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98716#-:-NQfyz0oDorXg1x0bsDz:b-7m74ok)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
