### PR TITLE
opt: split disjunctions into DistinctOn and UnionAll

### PR DESCRIPTION
**Pull request by mgartner**
This commit changes the behavior of the SplitDisjunction and
SplitDisjunctionAddKey exploration rules to create an expression with a
DistinctOn and UnionAll. Previously, a Union was used for the same
purpose.

This results in a significant improvement in query latency in cases
where non-key columns of the expression are wide, such as a long string
column. During execution, the Union expression has to store and compare
all columns when de-duplicating rows from each side of the Union. Under
the new implementation, UnionAll does not de-duplicate rows from the
left and right when they are merged. The de-duplication occurs in the
DistinctOn expression, during which only the key columns need to be
stored and compared.

Also, the EliminateUnionAllLeft and EliminateUnionAllRight rules were
modified to only project columns on the left or right side of the union
that are not in the output columns. Any columns that are in the child
expressions and the output are included in the Project's passthrough
column set.

This was necessary now that SplitDisjunction and SplitDisjunctionAddKey
reuse the input expression's column ids in the left and output column
lists. Without changing this behavior of EliminateUnionAllLeft and
EliminateUnionAllRight, the optimizer could generate a query plan with a
Project that projects a column that is passed-through.

Release note (performance improvement): The query optimizer now uses a
more efficient plan when splitting disjunctions into multiple
sub-queries.

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47617)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58IE0T4Z76khCvdY2C:-M58IE0UCR9hhka4p97I:b-tus0wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/norm/custom_funcs.go#L1395)):*
> ```Go
> 	out := set.OutCols.ToSet()
> 	left := set.LeftCols.ToSet()
> 	return out.Intersection(left)
> ```

I couldn't decide whether to convert these columns to sets and intersect them (maybe a little cleaner?) or to create a bespoke helper to iterate over the lists and generate the ColSet, like projectColMapSide above (maybe a little more efficient?). Any opinions?
___
*[pkg/sql/opt/xform/testdata/rules/select, line 2646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58ItNC9OExaA51w-LW:-M58ItNDBBVVXjnJwGFB:b-2j6pkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/xform/testdata/rules/select#L2646)):*
> ```
>                 └── v:3
> 
> # Columns are passed-through correctly when EliminateUnionAllLeft is applied.
> ```

This is the only way I could think of to test the changes to EliminateUnionAllLeft. I would like to create tests for the new behavior in `norm/testdata/rules/set`, where they belong, but AFAIK `SplitDisjunction` and `SplitDisjunctionAddKey` are the only ways to create a UnionAll with column IDs  in the left and output column lists. 

I don't think I can manufacture this case with `exprnorm` because AFAIK you can't specific column IDs.

So the best I could think of was to add two tests here (one for SplitDisjunction, one for SplitDisjunctionAddKey) which cover the EliminateUnionAllLeft behavior. However, the new behavior of EliminateUnionAllRight is untested, which I don't love.

Any better ideas?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-:-M594t3e04J4q21eiEMd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M593ET4ABXP_cxSEkr6:-M593ET4ABXP_cxSEkr7:bpypwvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/norm/custom_funcs.go#L1381)):*
> ```Go
> 	for idx, fromCol := range fromList {
> 		toCol := toList[idx]
> 		if fromCol != toCol {
> ```

[nit] This needs a short explanation (that we allow some or all col ids to stay the same)
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58IE0T4Z76khCvdY2C:-M594kdl2sCddnv6O9Ok:b4r9rdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/norm/custom_funcs.go#L1395)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I couldn't decide whether to convert these columns to sets and intersect them (maybe a little cleaner?) or to create a bespoke helper to iterate over the lists and generate the ColSet, like projectColMapSide above (maybe a little more efficient?). Any opinions?
</blockquote></details>

This should be fine, Sets are very fast in most cases

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-:-M595YeL05qutwbHcWnQ:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/metadata.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58scIk6E-USpqZRgp3:-M58scIk6E-USpqZRgp4:b-uuca4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/metadata.go#L97)):*
> ```Go
> //    Column ids in the left and output of the generated UnionAll are reused from the
> //    original input expression. This is safe because the columns from the
> //    left side of the union as essentially passed-through to the parent
> ```

as -> are
___
*[pkg/sql/opt/metadata.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58silG2a9Dor5l2-Jm:-M58silH4tyytjeJN_ZC:b1u3ars) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/metadata.go#L102)):*
> ```Go
> //  - Uncorrelated sub-expressions
> //
> //    This is safe because columns within correlated sub-expressions cannot
> ```

correlated -> uncorrelated?
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58IE0T4Z76khCvdY2C:-M595aDR2rLccSQ6ibuX:bm54j1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/norm/custom_funcs.go#L1395)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be fine, Sets are very fast in most cases
</blockquote></details>

Agreed, but you could also avoid an allocation by doing:
```
out := set.OutCols.ToSet()
out.IntersectionWith(set.LeftCols.ToSet())
return out
```
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M592I4H8UvEXVEnGLvL:-M592I4H8UvEXVEnGLvM:b8f6bzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/norm/custom_funcs.go#L1400)):*
> ```Go
> // ProjectPassthroughRight returns a ColSet that contains the columns that can
> // be passed-through from the right side in a SetPrivate when eliminating a set
> // operation, like in EliminateUnionAllLeft. Columns in both the output
> ```

EliminateUnionAllLeft -> EliminateUnionAllRight
___
*[pkg/sql/opt/norm/rules/set.opt, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M592WksELnbkR_KkJh-:-M592WksELnbkR_KkJh0:bf6m7op) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/norm/rules/set.opt#L30)):*
> ```
> #
> # See the comment above EliminateUnionAllLeft which describes when columns are
> # projects vs. passed-through.
> ```

[nit] projects -> projected
___
*[pkg/sql/opt/xform/testdata/rules/select, line 2646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58ItNC9OExaA51w-LW:-M594LN10EiI4YiULYzN:b-up92cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/xform/testdata/rules/select#L2646)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is the only way I could think of to test the changes to EliminateUnionAllLeft. I would like to create tests for the new behavior in `norm/testdata/rules/set`, where they belong, but AFAIK `SplitDisjunction` and `SplitDisjunctionAddKey` are the only ways to create a UnionAll with column IDs  in the left and output column lists. 

I don't think I can manufacture this case with `exprnorm` because AFAIK you can't specific column IDs.

So the best I could think of was to add two tests here (one for SplitDisjunction, one for SplitDisjunctionAddKey) which cover the EliminateUnionAllLeft behavior. However, the new behavior of EliminateUnionAllRight is untested, which I don't love.

Any better ideas?
</blockquote></details>

I think you could also add this test to `norm/testdata/rules/set`, and just change the directive to `expect= EliminateUnionAllLeft`.

One option is to only make the change to `EliminateUnionAllLeft` and leave `EliminateUnionAllRight` as it was. But I think it's also fine to leave it untested since it's pretty clearly symmetric.

I'm not sure whether you can create column ids with `exprnorm` -- maybe @raduberinde knows?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47617)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/metadata.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58scIk6E-USpqZRgp3:-M5Spwj84NY-ia98RLFR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/metadata.go#L97)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

as -> are
</blockquote></details>

Done.
___
*[pkg/sql/opt/metadata.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58silG2a9Dor5l2-Jm:-M5Sq0mu8UU5IkcwGb-q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/metadata.go#L102)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

correlated -> uncorrelated?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M593ET4ABXP_cxSEkr6:-M5Sr75y5LFbUzqcX0DG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/norm/custom_funcs.go#L1381)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This needs a short explanation (that we allow some or all col ids to stay the same)
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58IE0T4Z76khCvdY2C:-M5SrOMa0RV41u0VJegU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/norm/custom_funcs.go#L1395)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Agreed, but you could also avoid an allocation by doing:
```
out := set.OutCols.ToSet()
out.IntersectionWith(set.LeftCols.ToSet())
return out
```
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M592I4H8UvEXVEnGLvL:-M5SrVUhDHHN5tTseDWU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/norm/custom_funcs.go#L1400)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

EliminateUnionAllLeft -> EliminateUnionAllRight
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/set.opt, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M592WksELnbkR_KkJh-:-M5Sr_vB0LYYXrpHTVAO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/norm/rules/set.opt#L30)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] projects -> projected
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 2646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58ItNC9OExaA51w-LW:-M5SrhKd5B6Va6Q__3S9:b-p59y44) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/xform/testdata/rules/select#L2646)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you could also add this test to `norm/testdata/rules/set`, and just change the directive to `expect= EliminateUnionAllLeft`.

One option is to only make the change to `EliminateUnionAllLeft` and leave `EliminateUnionAllRight` as it was. But I think it's also fine to leave it untested since it's pretty clearly symmetric.

I'm not sure whether you can create column ids with `exprnorm` -- maybe @raduberinde knows? 
</blockquote></details>

I didn't think that `norm` applies exploration rules. If it does, I can add the same tests there and add `expect=EliminateUnionAllLeft` as you suggest.

**Review by rytaft — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47617)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/xform/testdata/rules/select, line 2646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47617#-M58ItNC9OExaA51w-LW:-M5X6u1JEcTRgRrsNDRO:b-95d0d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a36f4a07444f3e6f7430c1a750f30d10bd66f1b/pkg/sql/opt/xform/testdata/rules/select#L2646)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I didn't think that `norm` applies exploration rules. If it does, I can add the same tests there and add `expect=EliminateUnionAllLeft` as you suggest.
</blockquote></details>

Ah you're right. I think it's fine to just test it here.

**Pull request merged**
