### PR TITLE
Check value of gc.ttlseconds before rendering to prevent TypeError

### PR DESCRIPTION
**Pull request by nathanstilwell**
In a reported case from a customer, `zone_config.gc` is undefined and
accessing `ttl_seconds` on a null threw an error that stopped page
rendering.

```
bundle.js:49 TypeError: Cannot read property 'ttl_seconds' of null
    at t.e.renderZone (bundle.js:83)
    at t.value (bundle.js:83)
    at Xi (bundle.js:49)
    at $i (bundle.js:49)
    at Ts (bundle.js:49)
    at Cc (bundle.js:49)
    at Pc (bundle.js:49)
    at wc (bundle.js:49)
    at bundle.js:49
    at t.unstable_runWithPriority (bundle.js:57)
```

I'm adding a lodash/get call here with `null` as a default return to
prevent a TypeError. This is generally a good idea whenever you are
accessing anything that could be undefined in javascript.

### CODE REVIEW

**Review by koorosh — COMMENTED** [review]
@nathanstilwell my concern is about the correctness of displaying `null` in this case.
Screenshot 2020-08-13 at 2 05 17 PM

According [documentation](https://www.cockroachlabs.com/docs/stable/configure-zone.html), the default value for `gc.ttlseconds` is `90000` (25 hours) so that's a correct value in case of omited value.
I suggest we shouldn't display the entire assignment of `gc.ttlseconds`:

```jsx
{ zoneConfig.gc?.ttl_seconds &&
  <span className="hljs-label">gc.ttlseconds = </span>
  <span className="hljs-built_in">{`${zoneConfig.gc.ttl_seconds},`}</span>
  <br />
}
```

By the way, instead of using `lodash#get` function, it is possible to use [Typescript's optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) to make null assertions cleaner.

PS: I tried to check if it possible to set NULL to "gc.ttlseconds" and it fails to execute such statement:
```sql
root@127.0.0.1:49549/movr> ALTER DATABASE movr CONFIGURE ZONE USING gc.ttlseconds = NULL;
ERROR: unsupported NULL value for "gc.ttlseconds"
SQLSTATE: 22023
```

Looks like, it's a common issue for other parameters here as well, but the current solution fixes UI crash and might be considered as a hot-fix.

**Comment by nathanstilwell** [comment]
@koorosh I agree with your concern. This fix was very hasty, and I realize now that we don't (yet) have a way to hotfix the admin ui. 

So I am also confused about how `gc.ttlseconds` became _null or undefined_ (according to the error) so there is certainly a deeper issue there. But in terms of the making the UI more resilient, I think you are correct that we should omit display of the `gc.ttlseconds` if it isn't a numeric value. I had forgotten about the optional chaining operator, thank you for the reminder.

**Review by vladlos — APPROVED** [review]

**Comment by elkmaster** [comment]
I am still not sure what exactly we should show in this case, so lets file additional ticket to not forget find out it. As a hotfix LGTM.

**Pull request merged**
