### PR TITLE
roachtest: add manual cdc/tpcc-1000/sink=msk test

### PR DESCRIPTION
**Pull request by andyyang890**
See individual commits

Informs #124432

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
Nice roachtest!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129899#-:-O5V5iOP5YyvDP3sVfrC:b-8bsp24)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @DarrylWong, and @nameisbhaskar)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129899#-O5V5cMHDDcPlhuK8UFg:-O5V5cMHDDcPlhuK8UFh:bvytbhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/021d5f3f14143ad346a0204a7a18283cb98f6393/pkg/cmd/roachtest/tests/cdc.go#L1423)):*
> ```Go
> 				targets:  allTpccTargets,
> 				// This currently doesn't do anything other than add the updated option.
> 				// TODO(yang): Add order validation once we have more msk tests.
> ```

Doesn't this arg enable order validation?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129899)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @nameisbhaskar, and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129899#-O5V5cMHDDcPlhuK8UFg:-O5ViKdjA_byHJEYBOUl:b-srj7ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/021d5f3f14143ad346a0204a7a18283cb98f6393/pkg/cmd/roachtest/tests/cdc.go#L1423)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Doesn't this arg enable order validation?
</blockquote></details>

It only works for `kafkaSink` right now:
https://github.com/cockroachdb/cockroach/blob/021d5f3f14143ad346a0204a7a18283cb98f6393/pkg/cmd/roachtest/tests/cdc.go#L240

This test is marked as `mskSink` so it wouldn't apply.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129899)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @nameisbhaskar, and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129899#-O5V5cMHDDcPlhuK8UFg:-O5VikO81PleXV2Noc_G:bjv6mtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/021d5f3f14143ad346a0204a7a18283cb98f6393/pkg/cmd/roachtest/tests/cdc.go#L1423)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

It only works for `kafkaSink` right now:
https://github.com/cockroachdb/cockroach/blob/021d5f3f14143ad346a0204a7a18283cb98f6393/pkg/cmd/roachtest/tests/cdc.go#L240

This test is marked as `mskSink` so it wouldn't apply.
</blockquote></details>

I added it so that the `updated` option would be specified so that we can directly compare emitted bytes with the `cdc/tpcc-1000/sink=kafka`. I can see that it's confusing though, I can change the test to manually set the `updated` option instead.

**Comment by andyyang890** [comment]
TFTR!

bors r=rharding6373

**Pull request merged**
