### PR TITLE
catalog: remove the chart catalog

### LINKED ISSUE #54178: catalog: auto-generate grafana dashboards [deprecated]
**Is your feature request related to a problem? Please describe.**
We over-rely on our built-in AdminUI. Production users are supposed to use Prometheus or one of its siblings (Graphite, etc). But - we have no good dashboards to give them other than what CC uses at any given point in time (and that we don't distributed proactively).
This makes for a poor story.

**Describe the solution you'd like**

We should use the catalog:

https://github.com/cockroachdb/cockroach/blob/e43acc9b020fa117d5ca10249f6108602061e346/pkg/ts/catalog/chart_catalog.go#L32

to auto-generate Grafana dashboards.

**Describe alternatives you've considered**
I don't see an obvious better alternative. We can continue doing little, but it seems sub par.

**Additional context**
Lots of great synergy here with https://github.com/cockroachdb/cockroach/issues/46103, which also relies on Grafana. We look at timeseries quite a lot during debugging, and I'm sure this would see use and would help us dog food the catalog's organization to make sure it's helpful.

Epic: CRDB-25656
Jira issue: CRDB-3789

### LINKED ISSUE #78232: server: TestChartCatalogMetrics failed
server.TestChartCatalogMetrics [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4634571&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4634571&tab=artifacts#/) on release-22.1 @ [ec0a78bbf61f7d71fe4222cc1c11d262936df2e3](https://github.com/cockroachdb/cockroach/commits/ec0a78bbf61f7d71fe4222cc1c11d262936df2e3):

```
=== RUN   TestChartCatalogMetrics
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/ab5462d2cb3989e2a33018db970f23de/logTestChartCatalogMetrics1147682324
    test_log_scope.go:80: use -show-logs to present logs inline
    status_test.go:1014: The following metrics need are no longer present and need to be removed
        			from the chart catalog (pkg/ts/catalog/chart_catalog.go):[schedules.scheduled-row-level-ttl-executor.succeeded schedules.scheduled-row-level-ttl-executor.started schedules.scheduled-row-level-ttl-executor.failed schedules.scheduled-sql-stats-compaction-executor.started schedules.scheduled-sql-stats-compaction-executor.succeeded schedules.scheduled-sql-stats-compaction-executor.failed]
    panic.go:642: -- test log scope end --
--- FAIL: TestChartCatalogMetrics (0.25s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestChartCatalogMetrics.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-14025

### LINKED ISSUE #81035: metrics: generate dashboards from a Go struct or JSON definition
## Problem

Our DB console dashboards are maintained in the frontend code. There is friction for a DB-Eng to make adjustments to the dashboards, such as adding graphs, fixing up help texts, etc.
As a result of this friction, the dashboards are effectively unmaintained. The frontend teams that have the expertise to easily adjust these graphs have no expertise on the graphs, and so a hand-off is necessary for many changes.

For a personal example, I have spent so many hours looking at this graph, which mixes two time series that operate at vastly different scales (1-20 vs hundreds), effectively hiding the smaller timeseries:

image

I never went and fixed this. There are tons of things like this. Most metrics don't have help texts; we do have help texts in the backend and while they aren't perfect either, they *exist*. Nobody will transcribe them into the frontend.

Dashboards are poorly organized and for the same reasons as mentioned above, this isn't improving.

As a result of, I'm finding myself using custom charts most of the time when I'm running experiments.

## (Partial) Solution

All charts should be powered by custom charts code from a definition served by a CRDB endpoint.
The custom charts are generated from a json definition ([here's a sample](https://gist.github.com/tbg/1010112fbfde68f1d75012dd1c2c6863)) and if we added titles and legends and hover help texts to that, it seems like it could render the same thing as the main metric pages. The upshot could be that we could generate the json from the [chart catalog](https://github.com/cockroachdb/cockroach/blob/3582a90c8787c6b5c6f8a1e65087af4f33d9e106/pkg/ts/catalog/chart_catalog.go#L32-L3192) that we have already, so we'd be very close to unifying with https://github.com/cockroachdb/cockroach/issues/54178, where the goal is (likely) to similarly create grafana dashboards from the same chart catalog.
I think in due time we'd also get better dashboards and ownership, since the friction to rearranging them would drop quite dramatically, as engineers could do it without touching the frontend.

cc @thtruo 

Jira issue: CRDB-15382

### LINKED ISSUE #99791: metric: remove chart catalog
The chart catalog was introduced to ultimately encode the layout of the db console dashboards. It's not gonna happen.

It's not worth forcing each addition/removal of a metric through additional CI cycles as engineers get told that they have to make a manual edit to the chart catalog.

Tracking under REPL since I've got a PR to remove it: https://github.com/cockroachdb/cockroach/pull/99788

Jira issue: CRDB-26082

### PR DESCRIPTION
**Pull request by tbg**
Roughly the following, all in the same commit (sorry - discovered what needed to be done as I went, if reviewers find it hard to grok I can try to chop it into commits):

- tsdump: simplify code a bit
- tsdump: query AllMetricMetadata endpoint to get all timeseries names
  (rather than filling it server-side in the TSDB, which doesn't
  really have access to it now)
- tsdump: return error instead of filling in metric names
- serverpb: add GetInternalTimeSeriesNamesFromServer, this is code that
  essentially lived in `catalog`, but with some cleanups.
  We need this to go from "metric name" to "actual name the TSDB stores this
  under in KV" because that's what `tsdump` operates on.
- catalog: return a flat mock stub in GenerateCatalog
- catalog: pretty much delete everything else, including that
  list of metrics that needed to be manually adjusted every time
  a metric was added or removed.

A 23.1 cli will fail to fetch the timeseries from a 23.2+ host, but the error
message is informative and I don't think additional complexity to smoothen
mixed-version deploys is warranted. A 23.2+ cli will work fine with older
releases.

Closes https://github.com/cockroachdb/cockroach/issues/99791.

Tidy up a few issues that had to do with auto-generating Grafana dashboards
from the catalog:

Closes https://github.com/cockroachdb/cockroach/issues/54178.
Closes https://github.com/cockroachdb/cockroach/issues/78232.
Closes https://github.com/cockroachdb/cockroach/issues/81035.

Epic: none
Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
@dhartunian honestly I think this can be reviewed and merged, I can file an issue about the customcharts endpoint since I won't be able to deal with it anyway.

I'm going to rebase if you agree that now's a good time to push this over the line.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

@tbg customcharts is completely unused and can be removed separately. yeah we should probably go through a bit of ceremony if it is part of our v1 api.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99788#-:-NTTymS99Tm1UnCHGaMJ:b-8lvr2w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
bors r=dhartunian

**Comment by tbg** [comment]
bors r=dhartunian

**Pull request merged**
