### PR TITLE
sql/distsqlrun: refactor {aggregator,noopProcessor} to implement RowSource

### PR DESCRIPTION
**Pull request by petermattis**
* sql/distsqlrun: refactor aggregator to implement RowSource
* sql/distsqlrun: fix small bug in tableReader.Next
* sql/distsqlrun: add RowSource helper utilities to processorBase
* sql/distsqlrun: add processorBase.flowCtx
* sql/distsqlrun: refactor noopProcessor to implement RowSource

### CODE REVIEW

**Comment by petermattis** [comment]
FYI, the follow-on PR which recovers the small performance loss in `BenchmarkGrouping` addresses #20756.

**Comment by arjunravinarayan** [comment]
:LGTM:. Took me a while to catchup on all the PRs I missed.

Nit: Add release note to commit 1 as well?

---

Reviewed 2 of 2 files at r1, 14 of 14 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/processors.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147#-L1rWgzig7YMghkSWHD0:-L1rWgzig7YMghkSWHD1:b-4a9s9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b8cd07209f63c9fa8a3bc2a445fe274e2cfbd1f/pkg/sql/distsqlrun/processors.go#L388)):*
> ```Go
> 	// consumerStatus is used by the RowSource interface to signal that the
> 	// consumer is done accepting rows or is no longer accepting data.
> 	consumerStatus ConsumerStatus
> ```

Why does `noopProcessor` need to persist this state in its struct? I believe you are cargo-culting from `distinct`, which only does so because it has the strange behavior of continuing to consume its entire input after it is closed from downstream, rather than just passing on the `consumerClosed` state. `noopProcessor` does not need this behavior (and other processors do not persist it either).

---

*[pkg/sql/distsqlrun/processors.go, line 373 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147#-L1rkYb0s_3rAVOFavVB:-L1rkYb0s_3rAVOFavVC:b-6zeqo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/82b65f720ebe13f24da90ef129940dcd70a488e1/pkg/sql/distsqlrun/processors.go#L373)):*
> ```Go
> 	// consumerStatus is used by the RowSource interface to signal that the
> 	// consumer is done accepting rows or is no longer accepting data.
> 	consumerStatus ConsumerStatus
> ```

I'm mixed on adding `consumerStatus` to `processorBase`. Only `distinct` and the ur-producers of rows (`tableReader` + `valuesProcessor`) need to persist this state. I'll leave it up to you on whether you want to move this to `processorBase`. Currently the other processors don't set this either when they get a `ConsumerClosed.

I suppose I would be happy if you changed the comment to add something like 'some processors need to do cleanup work after receiving this signal, and thus need to persist the status'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147#-:-L1rjn6z670rghkUKFaX:banacfe)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/processors.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147#-L1rWgzig7YMghkSWHD0:-L1rweFquLN-EWg8_lXD:b-jzer3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b8cd07209f63c9fa8a3bc2a445fe274e2cfbd1f/pkg/sql/distsqlrun/processors.go#L388)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Why does `noopProcessor` need to persist this state in its struct? I believe you are cargo-culting from `distinct`, which only does so because it has the strange behavior of continuing to consume its entire input after it is closed from downstream, rather than just passing on the `consumerClosed` state. `noopProcessor` does not need this behavior (and other processors do not persist it either).
</blockquote></details>

I think I cargo-culted from `valuesProcessor`. When implementing `RowSource`, do we want to rely on the input properly obeying `ConsumerDone`? I was assuming no. You're suggesting yes.

---

*[pkg/sql/distsqlrun/processors.go, line 373 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147#-L1rkYb0s_3rAVOFavVB:-L1s-M9Q4Ezao8DUN-HR:b67qnwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/82b65f720ebe13f24da90ef129940dcd70a488e1/pkg/sql/distsqlrun/processors.go#L373)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I'm mixed on adding `consumerStatus` to `processorBase`. Only `distinct` and the ur-producers of rows (`tableReader` + `valuesProcessor`) need to persist this state. I'll leave it up to you on whether you want to move this to `processorBase`. Currently the other processors don't set this either when they get a `ConsumerClosed.

I suppose I would be happy if you changed the comment to add something like 'some processors need to do cleanup work after receiving this signal, and thus need to persist the status'.
</blockquote></details>

See my other reply: do we want processors implementing `RowSource.ConsumerDone` to assume that the calling `ConsumerDone` on the input works. I was assuming "no", but there is simplification here if we answer "yes".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147)*

**Comment by arjunravinarayan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/processors.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147#-L1rWgzig7YMghkSWHD0:-L1sNjYIIu5zuIFvgGBw:b-3nwtns) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b8cd07209f63c9fa8a3bc2a445fe274e2cfbd1f/pkg/sql/distsqlrun/processors.go#L388)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think I cargo-culted from `valuesProcessor`. When implementing `RowSource`, do we want to rely on the input properly obeying `ConsumerDone`? I was assuming no. You're suggesting yes.
</blockquote></details>

Yes.

My thoughts are that:
1. Sending a `ConsumerDone` through a goroutine is asynchronous, and thus you may get more rows after you send the signal. Thus, the `processor` implementation of `Run` needs to stop fetching rows. Since this is a "pull" interface, the `Run` implementations can just stop pulling. This is the current behavior.
2. Calling `Next` is done by direct function call, and thus all callers of `Next` can be relied upon to not ignore a returned `ConsumerDone`. We should insist on this behavior, as it makes the code simpler. There is no asynchrony that can cause extra calls of `Next`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147)*

**Comment by petermattis** [comment]
> Nit: Add release note to commit 1 as well?

Done.

---

Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsqlrun/processors.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147#-L1rWgzig7YMghkSWHD0:-L1sW6-KtZXSHwXUrp3O:bwxtlby) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b8cd07209f63c9fa8a3bc2a445fe274e2cfbd1f/pkg/sql/distsqlrun/processors.go#L388)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Yes.

My thoughts are that:
1. Sending a `ConsumerDone` through a goroutine is asynchronous, and thus you may get more rows after you send the signal. Thus, the `processor` implementation of `Run` needs to stop fetching rows. Since this is a "pull" interface, the `Run` implementations can just stop pulling. This is the current behavior.
2. Calling `Next` is done by direct function call, and thus all callers of `Next` can be relied upon to not ignore a returned `ConsumerDone`. We should insist on this behavior, as it makes the code simpler. There is no asynchrony that can cause extra calls of `Next`.
</blockquote></details>

Added another commit which moves `processorBase.consumerStatus` into a new `rowSourceBase` struct. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147#-:-L1sWNFQiTmtQDf-EADk:b7xwaig)*

**Comment by arjunravinarayan** [comment]
:lgtm:
I am happy with this design.

---

Reviewed 5 of 5 files at r11.
Review status: 5 of 15 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21147#-:-L1siXVNyYmD_kzpI1KF:b36feec)*

**Pull request merged**
