### PR TITLE
row: fix the memory accounting in txnKVFetcher in some cases

### PR DESCRIPTION
**Pull request by yuzefovich**
Currently, we have a problem with memory accounting in `txnKVFetcher`
when `Fetcher.StartScan` is used. Namely, the issue is as follows:
1. in `Fetcher.StartScan` we first create a new `txnKVFetcher`. In the
constructor method, if memory account is provided, we register the
memory usage of spans with the account
2. then we call `Fetcher.StartScanFrom`. There, if it's not the first
call to this method, we close the old `KVFetcher` which will in turn
close old `txnKVFetcher`. Closing of the latter clears the same memory
account (since we're reusing it), so we end up unregistering the memory
we registered in step 1.

This commit makes it so that we shrink the account in step 2 only by the
amount of allocations made by the old fetcher.

This commit additionally cleans up the way we use the account throughout
the fetches.

Found when working on #75468.

Release note: None

### CODE REVIEW

**Review by michae2 — COMMENTED** [review]
If the lifetime of the passed-in `BoundAccount` is wider than the lifetime of the `txnKVFetcher`, then it also seems wrong to call `f.acc.Clear` in `makeKVBatchFetcher`. Seems like we should either call `f.acc.Resize(f.spansAccountedFor + f.batchResponseAccountedFor, 0)` in `txnKVFetcher.close` or create a new `BoundAccount` just for the lifetime of the `txnKVFetcher` so that we're not clearing someone else's allocations.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79922#-:-N-Zu54A6krGOtONgF1V:b-q0h8sf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

**Comment by yuzefovich** [comment]
Fair point, I made the change to shrink the account only by the amount of allocations of the old fetcher when that fetcher is closed.

Creating a separate account for each new `txnKVFetcher` seems a bit suboptimal since we can have many `txnKVFetcher`s throughout lifetime of `row.Fetcher` and would require some changes in plumbing (we'd need to provide a monitor). Thus, I preferred the other option.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79922#-:-N-crI6s4ITFpFrEJoOS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by michae2 — APPROVED** [review]
Makes sense! Thanks! :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79922#-:-N-ctuHy6eJNCcnwIf9Y:bylmvwh)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Comment by yuzefovich** [comment]
Hm, I'm a bit unsure whether to backport this or not - I only ran into this when randomizing `rowinfra.DefaultBatchBytesLimit`, and I couldn't find any sentry reports about this problem, but in theory the problem could occur with default values too. I guess I'm leaning towards backporting this, but after a couple of weeks of baking on master. Thoughts?

**Comment by michae2** [comment]
Seems ok to me.

**Pull request merged**
