### PR TITLE
server,sql,kv: various context improvements

### PR DESCRIPTION
**Pull request by knz**
Informs #58938.

Connects more async goroutines to the tracer.

Also fixes various defects I introduced in #72638 and #72605.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72836)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper and @RaduBerinde)

**Comment by tbg** [comment]
LGTM on the kv change.

**Comment by knz** [comment]
TFYRs!

bors r=miretskiy,tbg

**Comment by knz** [comment]
bors r=miretskiy,tbg

**Comment by knz** [comment]
bors r=miretskiy,tbg

**Comment by knz** [comment]
bors r=miretskiy,tbg

**Pull request merged**
