### PR TITLE
kvserver: fix leak of tracked requests

### LINKED ISSUE #61590: roachtest: cdc/crdb-chaos failed
[(roachtest).cdc/crdb-chaos failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2751365&tab=buildLog) on [master@15a185606d5e80b47d9fdd0ed4f54cfe29c527c6](https://github.com/cockroachdb/cockroach/commits/15a185606d5e80b47d9fdd0ed4f54cfe29c527c6):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/cdc/crdb-chaos/run_1
	cdc.go:1383,cdc.go:209,cdc.go:640,test_runner.go:767: max latency was more than allowed: 15m59.227392403s vs 5m0s

```

<details><summary>More</summary><p>

Artifacts: [/cdc/crdb-chaos](https://teamcity.cockroachdb.com/viewLog.html?buildId=2751365&tab=artifacts#/cdc/crdb-chaos)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Acdc%2Fcrdb-chaos.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by andreimatei**
We were forgetting to untrack a request from the closedts tracker in an
edge case, resulting in the closed timestamp for the respective range
freezing.

Fixes #61590

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Nice find!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61759#-:-MVSsCOzA-bqHBkpEyX8:bdkgtm2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 570 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61759#-MVSrTHYEXBt3Vitmjpp:-MVSrTHZ9PHNX7wIMVok:b-owqm28) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8d6638aeaba772b0ba08127643bc8a9c29aaa4/pkg/kv/kvserver/replica_proposal_buf.go#L570)):*
> ```Go
> 				log.VEventf(ctx, 2, "not proposing lease acquisition because we're not the leader; replica %d is",
> 					leaderInfo.leader)
> 				p.tok.doneLockedMaybe(ctx)
> ```

It's strange that we mark the token as done _before_ rejecting it here, but mark it as done _after_ registering it below. That's a red flag to me, as it points to unclear lifetimes of the tokens. Does it matter in either case? Can we be consistent here?
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61759#-MVSrWix5hELshvv83yJ:-MVSrWix5hELshvv83yK:bvxorzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8d6638aeaba772b0ba08127643bc8a9c29aaa4/pkg/kv/kvserver/replica_proposal_buf.go#L851)):*
> ```Go
> }
> 
> func (t *TrackedRequestToken) doneLocked(ctx context.Context) {
> ```

Any reason to keep this method? And also `DoneIfNotMoved`? There's a lot of overlap here. Do we just need a `DoneIfNotMoved` and `DoneIfNotMovedLocked`?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61759)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 570 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61759#-MVSrTHYEXBt3Vitmjpp:-MVSxn75DzbUh1ozf9Jn:b39mv9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8d6638aeaba772b0ba08127643bc8a9c29aaa4/pkg/kv/kvserver/replica_proposal_buf.go#L570)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's strange that we mark the token as done _before_ rejecting it here, but mark it as done _after_ registering it below. That's a red flag to me, as it points to unclear lifetimes of the tokens. Does it matter in either case? Can we be consistent here?
</blockquote></details>

Well, it's all done under `r.mu`, so the order doesn't *really* matter.
In the case below, I've moved the `done()` down because there's a sort of passing of responsibility to `registerProposalLocked` - in the sense that a proposal in the map blocks the side transport from closing anything.
Here there's no equivalent. But still, I've moved it down.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61759#-MVSrWix5hELshvv83yJ:-MVTXGfp3fL1aN46qag4:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef8d6638aeaba772b0ba08127643bc8a9c29aaa4/pkg/kv/kvserver/replica_proposal_buf.go#L851)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any reason to keep this method? And also `DoneIfNotMoved`? There's a lot of overlap here. Do we just need a `DoneIfNotMoved` and `DoneIfNotMovedLocked`?
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61759#-:-MVTcpvf8vsLfvQIvpHz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 851 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61759#-MVTcbA849KnleJuX-rs:-MVTcbA849KnleJuX-rt:b-jqypaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89948dbbf1b4fdf6e17ff1ed03662118f19fff3/pkg/kv/kvserver/replica_proposal_buf.go#L851)):*
> ```Go
> }
> 
> // doneIfNotMovedLocked is like doneLocked, but it tolerates being called on a
> ```

This comment is now referring to a method that no longer exists.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61759)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 851 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61759#-MVTcbA849KnleJuX-rs:-MVTmIqSDXHKnhQRMP3w:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89948dbbf1b4fdf6e17ff1ed03662118f19fff3/pkg/kv/kvserver/replica_proposal_buf.go#L851)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment is now referring to a method that no longer exists.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61759#-:-MVUNymCCsqcGWk-baRL:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61759#-:-MVX7YdwE2plsdjTonEk:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
