### PR TITLE
[DNM] opt: initial prototype for distribution-awareness

### PR DESCRIPTION
**Pull request by rytaft**
This commit serves as a proposal for one way to make the optimizer
more aware of how data is distributed.

# Summary

The main changes are as follows:

- The catalog now has methods to get information about all the nodes in the
  cluster. At the moment this info only includes `Locality` and `Attributes`,
  which are needed to determine whether a node satisfies zone constraints.
  In the future we may also want to include pairwise latency between each
  node and every other node.

- The catalog index interface now has methods to return information about
  partitions defined on the index. Specifically, it includes the range of
  keys in each partition, and the zone configuration for the partition. We
  can use the node info from the catalog to determine which nodes satisfy
  the zone configuration for each partition.

- We can use the information about index partitions to determine which nodes
  may be involved in a particular index scan. The advantage of collecting
  the key ranges for each partition is that we may be able to eliminate
  some partitions for constrained scans. By intersecting the constraint with
  the key ranges, we can determine which subset of nodes may be involved in
  the scan.

- The coster can use the information about which nodes may be scanned to
  better estimate the cost of scans and index joins. This is especially
  useful for index joins if it's also possible to narrow down which nodes
  are needed from the primary index. At the moment the coster logic is
  extremely simple, and only checks whether the nodes match. We will need to
  update this to either compare localities between nodes or use latency info
  to estimate the cost.

The benefit of this change can be seen with a simple example in the test file
`pkg/sql/opt/xform/testdata/coster/partitioning`. This example includes a
table `abcd` with columns `(a, b, c, d)`, the primary index on `(a, b, c)`, and a
secondary index on `(c)`. A query such as `SELECT * FROM abcd WHERE a=1 AND c=1`
can either use a filtered constrained scan of the primary index, or a
constrained scan of the secondary index followed by an index join.

If both indexes are local (i.e., on the same node as the gateway), the index
join is a better choice. However, if the primary index is local and the
secondary index is remote, then the filtered primary index scan is better. If
the indexes are partitioned, then the locality depends on the values of `a`
and `c` in the query. The test file shows how changing the values result in
the following four different options and corresponding best plan (assuming
a single remote machine):
```
                   | primary local | primary remote
  -----------------+---------------+-------------------
  secondary local  | index join    | index join
  secondary remote | filtered scan | index join
```

# Extensions

In this commit, a `Partitioning` physical property is added as a field in the
`Scan` operator. To enable the coster to take distribution into account
throughout the query tree, we will need to propagate the physical property
up the tree to other operators. An open question is where the partitioning
property should be stored. With the current design it cannot be stored in the
`ProvidedPhysical` properties, since it is needed by the coster for the current
expression.

This commit shows how partitioning information can be used to better cost
scans and index joins. We can also use partitioning info to cost many different
types of joins. For lookup joins, we can do something similar to how index
joins are costed in this commit. For other types of joins, we'll probably
need to separate out the data shuffle stage from the join stage as a separate
operator. Then we can cost the data shuffle stage based on the before and
after partitioning. This will also allow us to consider new types of joins not
yet implemented in the execution engine such as broadcast join.

# Alternatives

There are a few alternatives to the approach in this commit that may be worth
considering:

- Instead of using the zone configuration defined on the index and/or index
  partitions, we could get the actual mapping of Ranges to nodes using
  the following code in opt_catalog.go:
  ```
    span := oi.tab.desc.IndexSpan(oi.desc.ID)
    ranges, err := ScanMetaKVs(ctx, planner.Txn(), span)
  ```
  This would allow the optimizer to take data distribution into account even
  when no zone configuration is defined. It would also allow us to pin down
  more precisely which nodes are involved in a query (zone configurations
  only identify the possible subset of nodes).

  The problem with this approach, however, is that the ranges returned by
  `ScanMetaKVs` cannot be easily converted to a form that the optimizer can
  use. At the moment no function exists to convert `roachpb.RKeys` to
  `tree.Datums`. Furthermore, it makes plan caching more complicated, since we
  would need to invalidate the cache each time a replica or leaseholder moved.

- Instead of storing nodes in the Partitioning property, we could simply store
  localities. This has the advantage that node information is not required, and
  the plan does not become invalid when nodes join or leave the cluster.
  I decided to store nodes, though, because they can be easily identified by
  a single integer, and they already contain the locality info anyway. Storing
  nodes allows us more flexibility and precision with costing: We can easily
  switch to costing with latency instead of locality. Also, a plan involving
  two nodes should have a different cost than a plan with one node, even if
  both nodes have the same locality.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
> At the moment no function exists to convert roachpb.RKeys to tree.Datums.

I'm not sure if there is a specific function for this, but this functionality exists somewhere in SQL execution. I'm not advocating for using the mapping of ranges to nodes as I think that is problematic for the other reasons you state, just noting that this reason shouldn't be a significant impediment.

**Comment by RaduBerinde** [comment]
Awesome work! I need to spend a lot more time looking at this, but a couple of high-level thoughts I have so far:

 - I don't think the `Nodes` stuff belongs in the catalog. An instance of the catalog is associated with a specific session, whereas the cluster configuration is "global". It is also a lot of data to move around and e.g. copy into the Metadata for each query. I think there should be another interface, similar to Catalog but with a single implementation for the entire cluster. It would be easier to do caching, keep track of latencies, etc from a single instance.

 - On storing nodes vs localities: We should introduce a new concept inside the optimizer for the entity at which level we are doing distribution awareness. The optimizer wouldn't care if one of these things is a node, an AZ, a region, or anything in-between; then we would be free to choose dynamically depending on cluster (e.g. it can be nodes in a single-region cluster and regions in a massive geodistributed cluster). This logic could live inside the singleton object mentioned above. We will likely need to avoid dealing with individual nodes for large clusters and doing this later would be a pain.

**Review by justinj — COMMENTED** [review]
This is really cool, and seems like approximately the perfect amount of functionality for a v1! Only had some minor comments on my first read through, and agreed with Radu's high-level comments.

> Reviewed 18 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43831#-:-LyADTBp2y6WLA9LQLoU:b-62pgvx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/props/physical/partitioning.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43831#-LyAXQA75IqeGsHPCHd-:-LyAXQA75IqeGsHPCHd0:b-cqyw8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0928d1c3437c0cc3e3d9a7c944a66f392483f8/pkg/sql/opt/props/physical/partitioning.go#L22)):*
> ```Go
> 
> // Partitioning represents the physical partitioning of data for a relational
> // operator.
> ```

nit: consider expanding this comment a bit, I think it's a little unclear what "for a relational operator" means, does this only apply to scans?
___
*[pkg/sql/opt/props/physical/partitioning.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43831#-LyAXJcv3bDbie4tRbZX:-LyAXJcw9kVclB2PyJzR:b-adhewm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0928d1c3437c0cc3e3d9a7c944a66f392483f8/pkg/sql/opt/props/physical/partitioning.go#L33)):*
> ```Go
> type partition struct {
> 	// ranges defines the subset of rows in this partition.
> 	ranges constraint.Constraint
> ```

nit: consider calling this `constraints` to avoid confusion with kv-level ranges?

**Review by rytaft — COMMENTED** [review]
Thanks for the feedback and info!

I'll iterate on this PR to move `Node` out of the catalog and generalize the unit of distribution. Not sure I fully understand yet how this "distribution entity" would work yet, but I think I can take a stab, anyway.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43831#-:-LyBAd5hApCPx-q63gws:b-tv41gu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/props/physical/partitioning.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43831#-LyAXQA75IqeGsHPCHd-:-LyBA--B5prr4fKJ-RhQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0928d1c3437c0cc3e3d9a7c944a66f392483f8/pkg/sql/opt/props/physical/partitioning.go#L22)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: consider expanding this comment a bit, I think it's a little unclear what "for a relational operator" means, does this only apply to scans?
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/physical/partitioning.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43831#-LyAXJcv3bDbie4tRbZX:-LyBAEhTDqUGlndOvbnU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0928d1c3437c0cc3e3d9a7c944a66f392483f8/pkg/sql/opt/props/physical/partitioning.go#L33)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: consider calling this `constraints` to avoid confusion with kv-level ranges?
</blockquote></details>

Done.

**Review by andy-kimball — COMMENTED** [review]
I had envisioned distribution-awareness working only at the level of static zone configurations, like the current (little bit) of latency awareness we have today. One big reason is that I don't think we want to invalidate plans each time a range moves from one node to another (would be expensive to know when to invalidate, as well as to re-optimize every time we got invalidated). When I did the latency awareness I started with something close to what you have here, but then moved over to static zone config analysis for this reason. I'm not sure about that, though - definitely should analyze and discuss more.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43831#-:-LyBL-J1AYZy8nMHgmZV:bhvqd9h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

**Comment by rytaft** [comment]
This implementation wouldn't require invalidating plans each time a range moves (that was the alternative I considered using `ScanMetaKVs` but didn't end up implementing). It would only require invalidation if a node joins or leaves the cluster, or if the node locality or attributes change. The reason is that the partitions in this prototype don't map key ranges to individual nodes, instead they map key ranges to the set of nodes that might contain the range based on the zone config.

**Review by andy-kimball — COMMENTED** [review]
I see. Isn't "mapping to the set of nodes that might contain the range based on the zone config" equivalent to "mapping to localities"? In other words, we already know what localities might contain a range, so what's the need for introducing the concept of nodes into the optimizer? My assumption is that at some lower level, we could keep a table of "average latencies from each locality to each other locality", and abstract away the need for dealing with nodes in the optimizer.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43831#-:-LyBi7JKBI2h86IyB12L:bk0lpp7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Comment by rytaft** [comment]
I could be wrong, but my gut instinct is that a plan spanning three nodes should have a different cost than a plan spanning one node, even if they are all in the same locality.  But if we go with Radu's suggestion of adding a layer of abstraction over the "distribution entity", we can easily change the granularity between nodes, localities, zones, etc, and the optimizer doesn't need to know the difference.

**Review by RaduBerinde — COMMENTED** [review]
I am wondering if we can fully separate the concept of a `Constraint / ConstraintSet` from the optimizer. The Zone interface could return sets of nodes/neighborhoods and the coster would rely on hood-to-hood latencies. We would have an initial implementation of the latency "map" which emulates the current behavior (or close to it).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43831#-:-Lyj5-UhDF9G8j6hN4lO:blnekeh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Comment by rytaft** [comment]
I've just added a new commit to replace the node concept with "neighborhoods", and moved it out of the catalog. Please take a look at the new commit message and code changes, and let me know what you think.

> I am wondering if we can fully separate the concept of a Constraint / ConstraintSet from the optimizer.

Sounds like that could work! The functions `neighborhoodsFromZone` and `leasePrefFromZone` that are currently in `props/physical/partitioning.go` could be moved to `optCatalog`.

**Comment by rytaft** [comment]
I don't think there's much value to leaving this PR open anymore. Closing.

**Pull request closed without merging**
