### PR TITLE
sql: use BulkNormalPri for index backfiller transactions

### PR DESCRIPTION
**Pull request by stevendanna**
Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
Opened this based on a slack conversation.  Not sure if this is the right priority to use.

**Review by erikgrinaker — APPROVED** [review]
LGTM, thanks! Haven't looked for any other call sites, but this is essentially it?

**Comment by erikgrinaker** [comment]
We'll need to get this in before 22.1, so adding the GA blocker label.

**Comment by dt** [comment]
I believe the label needs to be on an issue vs a pr? in any case, let's merge this.

bors r=dt

**Review by dt — APPROVED** [review]

**Comment by erikgrinaker** [comment]
blathers backport 22.1.0

**Comment by erikgrinaker** [comment]
>I believe the label needs to be on an issue vs a pr?

Probably true, wishful thinging. Opened #80464.

**Pull request merged**
