### PR TITLE
release-upload: upload race binaries

### PR DESCRIPTION
**Pull request by tamird**
Refactor to upload binaries as soon as they are built and highlight
various idiosyncrasies.

Still running through a manual test run of this locally, but wanted to get this out for review since I have to step out for a bit.

### CODE REVIEW

**Comment by benesch** [comment]
LGTM.

**Comment by benesch** [comment]
Now that I think about it, how do you prevent linux-gnu and linux-musl from polluting each others caches?

**Comment by tamird** [comment]
They have separate installsuffixes.

**Comment by tamird** [comment]
Couple minor updates. Will merge this tomorrow.

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cmd/release-upload/main.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15487#-KitOqYGTKFuUUFIyOJK:-KitOqYGTKFuUUFIyOJL:b-tnhzle) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f95668e42db6cd7e63da8f2b5bb00c91039750/pkg/cmd/release-upload/main.go#L117)):*
> ```Go
> 
> 	if !isHead {
> 		for _, releaseVersionStr := range releaseVersionStrs {
> ```

Why is it preferable to push the "-latest" source archive even if the code doesn't build / pass tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15487#-:-KitQ0kb0B4MFPECtbAL:bnfp4nl)*

**Comment by tamird** [comment]
Thanks for the review! At the time this code executes, the code has already
passed tests. I'd be ok with moving this down to the end, but then do we
also want to stop uploading binaries as they're built, to get
all-or-nothing semantics?

**Comment by a-robinson** [comment]
We can never get all-or-nothing semantics, since any upload could fail. If we've already built/tested the code before running this step, then it LGTM as is.

**Comment by a-robinson** [comment]
(i.e. my stance is that partial uploads are acceptable, broken uploads aren't)

**Comment by tamird** [comment]
Cool. FWIW, here's where you can see that the release build (i.e. this code) depends on CI having passed: https://teamcity.cockroachdb.com/admin/editDependencies.html?id=buildType:Cockroach_MergeToMaster.

**Pull request merged**
