### PR TITLE
eventpb,sql: lay some foundation for redactable statement strings

### PR DESCRIPTION
**Pull request by knz**
Informs #65401.
Needed as prerequisite for  #66359. 

Prior to this change, the centralized structured logging logic and the
query logging mechanism were both assuming that the entirety of the
statement string was unsafe for reporting.

We want in a later change to introduce some nuance into this. However,
the structured event logging encoding did not know anything else than
strings that were either completely-safe or completely-unsafe.

This patch introduces the possibility for a structured event to
contain a string of go type `redact.RedactableString`, where the
caller has already taken responsibility for placing redaction markers.

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @rauchenstein, and @THardy98)

___
*[pkg/sql/event_log.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66431#-McAr5HJ4AhweMU8_X3Y:-McAr5HJ4AhweMU8_X3Z:b-efbfks) ([raw file](https://github.com/cockroachdb/cockroach/blob/e94ff7be24a2288975d76bc07f65472814c4765e/pkg/sql/event_log.go#L486)):*
> ```Go
> 		// In the system.eventlog table, we do not use redaction markers.
> 		// (compatibility with previous versions of CockroachDB.)
> 		infoBytes = infoBytes.StripMarkers()
> ```

I'm not following this part. Why do you need to append the marker if you will remove right after?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, @rauchenstein, and @THardy98)

___
*[pkg/sql/event_log.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66431#-McAr5HJ4AhweMU8_X3Y:-McAsCAQD-3oYfQYt1sI:b-ipzlnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e94ff7be24a2288975d76bc07f65472814c4765e/pkg/sql/event_log.go#L486)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I'm not following this part. Why do you need to append the marker if you will remove right after?
</blockquote></details>

The problem is that the `json.Marshal` code that was there prior to this PR does not work with fields that have type `redact.RedactableString` - it takes the redaction markers as part of the JSON serialization.

The consumers of `system.eventlog` require all the strings to never contain redaction markers.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, @rauchenstein, and @THardy98)

___
*[pkg/sql/event_log.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66431#-McAr5HJ4AhweMU8_X3Y:-McAsVHSC0IapFPcFwo8:b-7s6o71) ([raw file](https://github.com/cockroachdb/cockroach/blob/e94ff7be24a2288975d76bc07f65472814c4765e/pkg/sql/event_log.go#L486)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The problem is that the `json.Marshal` code that was there prior to this PR does not work with fields that have type `redact.RedactableString` - it takes the redaction markers as part of the JSON serialization.

The consumers of `system.eventlog` require all the strings to never contain redaction markers.
</blockquote></details>

It's also incorrect/unsafe to use StripMarkers (or equivalent logic) on the output of `json.Marshal`, because that would break events that contain a unicode character as part of a SQL literal, and the unicode character happens to be the same as a redaction marker (e.g. `INSERT INTO ... VALUES('›')` )

**Review by maryliag — APPROVED** [review]
Thank you for this!
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66431#-:-McAtI5u47KqUAyBJz63:b-o2v4jq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @rauchenstein, and @THardy98)

___
*[pkg/sql/event_log.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66431#-McAr5HJ4AhweMU8_X3Y:-McAt4LR-FwRVVsV_pZ1:b-4hvi0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e94ff7be24a2288975d76bc07f65472814c4765e/pkg/sql/event_log.go#L486)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

It's also incorrect/unsafe to use StripMarkers (or equivalent logic) on the output of `json.Marshal`, because that would break events that contain a unicode character as part of a SQL literal, and the unicode character happens to be the same as a redaction marker (e.g. `INSERT INTO ... VALUES('›')` )
</blockquote></details>

Got it!

**Review by dhartunian — COMMENTED** [review]
:lgtm: thx for adding me on this. it was a helpful example to understand.

> Reviewed 6 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66431#-:-McGmO6zBAulCZ3hLa9E:b-zesz7a)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @knz, @rauchenstein, and @THardy98)

**Comment by knz** [comment]
TFYRs!

bors r=maryliag,dhartunian

**Pull request merged**
