### PR TITLE
Tiny comment fix to processRaft():

### PR DESCRIPTION
**Pull request by kkaneda**
processes read/write commands -> processes write commands

[ci skip]

### CODE REVIEW

**Comment by kkaneda** [comment]
Btw, I'm wondering if there is a specific reason for processing all write commands sequentially. I guess we could process commands for different ranges in parallel (especially when there is no membership change). Is this mostly because sequential writes to RocksDB can perform better?

**Comment by tschottdorf** [comment]
LGTM. I think the execution of Raft commands could be parallelized, but the way MultiRaft is set up you wind up with sort of a "global log". Moving away from that gives you more complexity in `processRaft`, though. It could be something to look into when rewriting MultiRaft, but that's not going to happen anytime soon. @bdarnell might have something to add.

**Comment by bdarnell** [comment]
LGTM. We serialize everything even across different ranges because all the ranges on a store are ultimately competing for the same IO resources (and because it's simpler and we haven't done much performance work at this level yet). It may turn out that we can get better performance by processing writes for different ranges in parallel (e.g. for the read halves of ConditionalPut or Increment operations), in which case we may want to split things up by range. On the other hand, the simple serialized version may make other optimizations easier, such as hoisting rocksdb batches up to a higher level so we can commit commands in multiple ranges with a single fsync.

**Comment by kkaneda** [comment]
I see. Thanks for the detailed explanation, @tschottdorf , @bdarnell !

**Pull request merged**
