### PR TITLE
rpc: extend TestInternalClientAdapterRunsInterceptors to mux rangefeed

### PR DESCRIPTION
**Pull request by wenyihu6**
This patch adapts the test TestInternalClientAdapterRunsInterceptors to mux
rangefeed so that we don’t lose test coverage when removing non-mux rangefeed
code in the future commits.

Part of: #125666
Release note: none

### CODE REVIEW

**Comment by wenyihu6** [comment]
The first commit is from https://github.com/cockroachdb/cockroach/pull/125663.

**Comment by nvanbenschoten** [comment]
I had one comment in https://github.com/cockroachdb/cockroach/pull/125665#pullrequestreview-2118756001 which applies to this PR.

**Comment by wenyihu6** [comment]
Replied in https://github.com/cockroachdb/cockroach/pull/125665#pullrequestreview-2118896202.

**Comment by wenyihu6** [comment]
Closing in favour of https://github.com/cockroachdb/cockroach/pull/125665 - that pr has a stamp on both commits.

**Pull request closed without merging**
