### PR TITLE
[wip] object pooling in the distsql planning path

### PR DESCRIPTION
**Pull request by jordanlewis**
This PR pools many of the expensive top-level objects during DistSQL physical planning and flow setup. I haven't cleaned it up - comments are missing, things might be misplaced, tests might fail - but I was iterating on this to try to get rid of some of the discrepancy performance-wise between auto and 2.0-auto on the `kv95` workload. But pushing up for early feedback on the approach. Take a look at the `Release` and `Reset` methods and when they're called in the object lifecycles.

I saw some pretty good results on this.

```
name                           old time/op    new time/op    delta
FlowSetup/distribute=false-24    18.4µs ± 7%    15.2µs ± 3%  -17.52%  (p=0.000 n=9+9)

name                           old alloc/op   new alloc/op   delta
FlowSetup/distribute=false-24    32.3kB ± 0%    24.1kB ± 0%  -25.34%  (p=0.000 n=10+10)

name                           old allocs/op  new allocs/op  delta
FlowSetup/distribute=false-24       299 ± 0%       243 ± 0%  -18.75%  (p=0.000 n=10+10)
```

Note that this PR is based on #30464 - ignore those commits.

cc @nvanbenschoten @andreimatei

### CODE REVIEW

**Review by rjnn — COMMENTED** [review]
Great job! R1 and R2 are in a separate PR, and I'd advocate for you sending R3, R4, and R5+R6 in 3 separate PRs as well to get this merged as smoothly as possible.

I'm surprised that pooling the allocations is this much of a win. Can you please refresh my memory as to how much of an overall win this is? What fraction of our time is spent in flow setup?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30556#-:-LNAyL0iAAoBoOgJUpsf:b4ief7y)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
> I'm surprised that pooling the allocations is this much of a win. Can you please refresh my memory as to how much of an overall win this is? What fraction of our time is spent in flow setup?

The overall win-ness of this is still up for debate. It takes GC pressure off the system, for sure, but that doesn't always manifest as a throughput improvement.

Flow setup and DistSQL planning are the main extra work steps between the local execution engine and the DistSQL execution engine, though, so it follows that improving their performance should help alleviate the performance difference.

**Comment by arjunravinarayan** [comment]
I guess this is a separate conversation, but we need to drill down on _why_ GC pressure reductions are hard to benchmark, especially given that GC time is such a large fraction of CPU time in our profiles. 

I otherwise buy the argument that this improvement is good, and we should get it merged. What are your thoughts on its backport-worthiness?

**Comment by jordanlewis** [comment]
Doesn't feel particularly backport worthy, unless for some reason we're desperate for extra performance.

**Comment by arjunravinarayan** [comment]
Great, that makes me feel more comfortable with this change. I am now emphatically in favor of this!

**Comment by asubiotto** [comment]
Could you share some kv throughput numbers as well?

**Comment by bobvawter** [comment]
[CLA assistant check](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=30556) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=30556) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=30556) it.</sub>

**Pull request closed without merging**
