### PR TITLE
cli: identify log source more easily when running merge-logs

### LINKED ISSUE #55395: cli: debug merge-logs output should include node id to ensure uniqueness
**Describe the problem**
The merge-log output is prefixed by short machine name which may not be unique. If more than 1 node has the same short machine name, you will not be able to easily determine which node produced a log message.

This issue was discovered using the debug.zip of a 15 node cluster which used three of the same short machine names.

**To Reproduce**

(1) Create a cluster with nodes with the same short machine names. For example,
```
node  machine-name
1      cockroachdb-0.db.us1.example.dev
2      cockroachdb-1.db.us1.example.dev
3      cockroachdb-2.db.us1.example.dev
4      cockroachdb-0.db.us2.example.dev
5      cockroachdb-1.db.us2.example.dev
6      cockroachdb-2.db.us2.example.dev
```

(2) Generate a debug.zip for the cluster. For testing purposes, you can use: 
[sample_debug.zip](https://github.com/cockroachdb/cockroach/files/5357154/sample_debug.zip)

(3) Unzip the debug.zip file 
(4) Grep the logs for "running on machine". Notice that the log files from multiple nodes in the debug zip will have the same short machine name (not the fully qualified name). For example, nodes 1 and 4 will have `cockroachdb-0`:

```
Florences-MBP:nodes florencemorris$ grep "running on machine" */logs/*
1/logs/cockroach.cockroachdb-0.root.2020-09-30T23_02_25Z.000001.log:I200930 23:02:25.482846 29002615 util/log/sync_buffer.go:49  [config] running on machine: cockroachdb-0
4/logs/cockroach.cockroachdb-0.root.2020-10-02T19_09_03Z.000001.log:I201002 19:09:03.549656 268864616 util/log/sync_buffer.go:49  [config] running on machine: cockroachdb-0
```

(4) Merge the log files:

```
Florences-MBP:nodes florencemorris$ cockroach debug merge-logs */logs/*
```

(5) In the merge-log output, notice that the lines are prefixed by short machine name, so you can not quickly determine which node the line is from. For example, the line below can be from either node 1 or 4:

```
Florences-MBP:nodes florencemorris$ cockroach debug merge-logs */logs/*
cockroachdb-0> I200930 23:02:25.482846 29002615 util/log/sync_buffer.go:49  [config] running on machine: cockroachdb-0
cockroachdb-0> I201002 19:09:03.549656 268864616 util/log/sync_buffer.go:49  [config] running on machine: cockroachdb-0
```

**Expected behavior**

merge-logs output prefix includes node ID which is unique. For example,

```
Florences-MBP:nodes florencemorris$ cockroach debug merge-logs */logs/*
cockroachdb-0(n1)> I200930 23:02:25.482846 29002615 util/log/sync_buffer.go:49  [config] running on machine: cockroachdb-0
cockroachdb-0(n4)> I201002 19:09:03.549656 268864616 util/log/sync_buffer.go:49  [config] running on machine: cockroachdb-0
```

**Additional data / screenshots**
Workaround:
grep logs for timestamp, such as  `I200930 23:02:25.482846`, to determine the exact log file and node message came from.

**Environment:**
 - CockroachDB version 20.1.6
 - Server OS: Mac
 - Client app  `cockroach debug merge-logs`

**Additional context**
What was the impact?
makes troubleshooting large clusters difficult

### PR DESCRIPTION
**Pull request by jtsiros**
resolves  #55395

Previously, merge-logs output was prefixed by short machine name by default which made it difficult to identify the originating node when looking at the merged results.

This change adds support for ${fpath} in the template when using the --prefix arg to include unique file path contents as part of the prefix. The file path prefix excludes common tokens across all file paths and tokens that contain specific delimiters.

Release note (cli change): adds support for "${fpath}" in --prefix arg

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 26 of 41 files at r1, 24 of 28 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jtsiros)

___
*[pkg/cli/prefixer.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MlhiVbKAWFS0NtzN-Ie:-MlhiVbLBJE7P8honSx2:bix3pe4) ([raw file](https://github.com/cockroachdb/cockroach/blob/380b956031136f018b44601dfe95eca2242b166c/pkg/cli/prefixer.go#L31)):*
> ```Go
> }
> 
> //lint:ignore U1001,U1000 used for overriding default values
> ```

why is this linter exemption needed?

**Comment by ajwerner** [comment]
This seems a heck of a lot less flexible. Not everybody has their logs from a debug zip. This seems to hard code the assumption that you're only using this thing with a debug zip. How about instead you let users specify a regexp with capture groups over the path as opposed to just the filename and then change the log here for what goes in the `prefix` flag by default?

**Review by jtsiros — COMMENTED** [review]
Agreed. I reverted the removal of the --prefix flag and added support for an optional ${fpath} arg in the template. @knz mentioned that he was OK with the default behavior, so I didn't update the default arg. Let me know if you think it should be included by default.

> Reviewed 41 of 41 files at r1, 25 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-:-MmJL9WuCoWpCEinfjl0:b-ylwn0p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jtsiros, and @knz)

**Review by rauchenstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 54 files at r5, 1 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jtsiros, and @knz)

___
*[pkg/cli/debug.go, line 1366 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMaLz58cqRpc1W7eQY:-MmMaLz6-8X7Jk2LGGkw:b-2c276d) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/debug.go#L1366)):*
> ```Go
> }
> 
> type prefixer interface {
> ```

Given that only one type implements it, the interface doesn't seem necessary.
___
*[pkg/cli/debug_merge_logs.go, line 329 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMeL0a8Sa8B8wJZz0z:-MmMeL0a8Sa8B8wJZz1-:bvp0xrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/debug_merge_logs.go#L329)):*
> ```Go
> type fileInfo struct {
> 	path    string
> 	prefix  []byte
> ```

I'd think this should be a string.  (Just cast the return value from the regexp library.)
___
*[pkg/cli/prefixer.go, line 23 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMRIye0ZS8yLgWn68B:-MmMRIye0ZS8yLgWn68C:b8c9qq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer.go#L23)):*
> ```Go
> var defaultFilePrefixerOptions = filePrefixerOptions{
> 	Delimiters: []string{"/", ".", "-"},
> 	Splitter:   regexp.MustCompile(`[/\\]+`),
> ```

Do we need the flexibility of regexp Splitters?  Is filepath.SplitList not suitable?
___
*[pkg/cli/prefixer.go, line 58 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMcFYE9khCAaMFYDSX:-MmMcFYE9khCAaMFYDSY:b-li2h44) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer.go#L58)):*
> ```Go
> // delimiters and template.
> //
> func newFilePrefixer(opts ...filePrefixerOption) filePrefixer {
> ```

Outside of tests, this is only ever called with withTemplate.  Unless more flexibility is actually needed at some later point, just `newFilePrefixer(template string)` seems sufficient.
___
*[pkg/cli/prefixer.go, line 70 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMWTAs1lRAuIqffvdL:-MmMWTAs1lRAuIqffvdM:be9grv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer.go#L70)):*
> ```Go
> }
> 
> // Prefix generates a prefix for each file path directory given a
> ```

Populating fields on the input slice is a non-obvious way to return results.  Document it in the comment, and perhaps name the function something like PopulatePrefixes.
___
*[pkg/cli/prefixer.go, line 91 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMUmT7Ex2aJdSKDX25:-MmMUYyWBbHE73H6Xw_N:b-oey37n) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer.go#L91)):*
> ```Go
> // See [debug_merge_logs_test.go, prefixer_test.go] for additional examples.
> //
> func (f filePrefixer) Prefix(logFiles []fileInfo) {
> ```

This algorithm doesn't handle tokens appearing multiple times in the same path.  Given the two files
```
a/a/foo.log
b/c/b/bar.log
```
it would identify "a" and "b" as common tokens.

Related would be a case like
```
a/b/foo.log
b/a/bar.log
```
___
*[pkg/cli/prefixer.go, line 138 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMSW1y1MABtd_ynYmP:-MmMSW1y1MABtd_ynYmQ:b773a92) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer.go#L138)):*
> ```Go
> }
> 
> func hasDelimiters(token string, del []string) bool {
> ```

Maybe this should be a method of filePrefixer?
___
*[pkg/cli/prefixer_test.go, line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMfb0T1AhbDz-aWh-q:-MmMfb0T1AhbDz-aWh-r:b-n5kzdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer_test.go#L24)):*
> ```Go
> var (
> 	fileRE = regexp.MustCompile(logFilePattern)
> 	fInfo  = func(path string, fileRE *regexp.Regexp) fileInfo {
> ```

Why a package-scope variable lambda instead of a normal func or a lambda inside the test function?

**Review by jtsiros — COMMENTED** [review]
> Reviewed 54 of 54 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jtsiros, @knz, and @rauchenstein)

___
*[pkg/cli/debug.go, line 1366 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMaLz58cqRpc1W7eQY:-MmOClKa1Ea5987kxuWH:b-tz1bdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/debug.go#L1366)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Given that only one type implements it, the interface doesn't seem necessary.
</blockquote></details>

I'll change it - thanks!
___
*[pkg/cli/debug_merge_logs.go, line 329 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMeL0a8Sa8B8wJZz0z:-MmOA_4KCmHK_I_gZctD:bdfkbvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/debug_merge_logs.go#L329)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

I'd think this should be a string.  (Just cast the return value from the regexp library.)
</blockquote></details>

I originally had this as a string, but was casting the value twice (return value from regexp, then back to []byte for log.FormatLegacyEntryPrefix). Let me know if you still prefer it to be a string.
___
*[pkg/cli/prefixer.go, line 23 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMRIye0ZS8yLgWn68B:-MmOBgDB2zAzeW2gD0F1:bc2t7v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer.go#L23)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Do we need the flexibility of regexp Splitters?  Is filepath.SplitList not suitable?
</blockquote></details>

It probably is now: this was intended to handle multiple split tokens to pick up the file name before we discussed preserving existing functionality. 
___
*[pkg/cli/prefixer.go, line 70 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMWTAs1lRAuIqffvdL:-MmOCMveB83h7zRzt97R:bhy9ot6) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer.go#L70)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Populating fields on the input slice is a non-obvious way to return results.  Document it in the comment, and perhaps name the function something like PopulatePrefixes.
</blockquote></details>

Will do.
___
*[pkg/cli/prefixer.go, line 138 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMSW1y1MABtd_ynYmP:-MmODvuSCC0hohuB02F9:bhy9ot6) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer.go#L138)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Maybe this should be a method of filePrefixer?
</blockquote></details>

Will do.
___
*[pkg/cli/prefixer_test.go, line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMfb0T1AhbDz-aWh-q:-MmOEiZwDlFKNlLMlg2M:b-ywsobj) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer_test.go#L24)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Why a package-scope variable lambda instead of a normal func or a lambda inside the test function?
</blockquote></details>

I originally had multiple tests and consolidated them into a test table. I'll move it.

**Review by jtsiros — COMMENTED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @rauchenstein)

___
*[pkg/cli/prefixer.go, line 58 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMcFYE9khCAaMFYDSX:-MmOWEVm4LR-KjtdcdUd:b7fvc0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer.go#L58)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Outside of tests, this is only ever called with withTemplate.  Unless more flexibility is actually needed at some later point, just `newFilePrefixer(template string)` seems sufficient.
</blockquote></details>

Generally, I agree. I removed the delimiter configuration for now. I do prefer this pattern as it makes it easily extendable (by adding additional `withX` methods as needed) and avoids conditional logic in `newFilePrefixer` for default values.

**Review by rauchenstein — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jtsiros, @knz, and @rauchenstein)

___
*[pkg/cli/debug_merge_logs.go, line 329 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMeL0a8Sa8B8wJZz0z:-MmOwfoAE0vy0WYCd4Rr:b-fqehlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/debug_merge_logs.go#L329)):*
<details><summary><i>Previously, jtsiros (Jon Tsiros) wrote…</i></summary><blockquote>

I originally had this as a string, but was casting the value twice (return value from regexp, then back to []byte for log.FormatLegacyEntryPrefix). Let me know if you still prefer it to be a string.
</blockquote></details>

Nope, that sounds like good justification.
___
*[pkg/cli/prefixer.go, line 91 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-MmMUmT7Ex2aJdSKDX25:-MmOqkpQ-tt-QRFVdM4b:bcb56sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ec576d7fd3d77450066f82b4be79fd9e66e44f/pkg/cli/prefixer.go#L91)):*
<details><summary><i>Previously, jtsiros (Jon Tsiros) wrote…</i></summary><blockquote>

It handles tokens appearing multiple times in the same path by checking "seen" when iterating over the tokens (see line 25). Tokens aren't counted more than once.
</blockquote></details>

Well, I'm blind -- I was thinking that exactly what you already did would be a reasonable fix, yet I still missed it.

**Review by cameronnunez — APPROVED** [review]

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71254#-:-MmTPkgu0FWw5BL1xtWl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jtsiros, @knz, and @rauchenstein)

**Pull request merged**
