### PR TITLE
roachprod: classify dns errors

### PR DESCRIPTION
**Pull request by herkolategan**
Previously DNS errors were not marked making it hard to classify these errors
later on. This change marks all DNS related errors in order to better report on
the errors.

roachtest then classifies these errors as infra flake to help with triaging.

Epic: None
Release Note: None

### CODE REVIEW

**Review by smg260 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, @rachitgsrivastava, and @renatolabs)

___
*[`pkg/cmd/roachtest/github.go` line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110831#-NedAZvv-swPLfmLgKcY:-NedAZvv-swPLfmLgKcZ:bkof4t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b672649da11909bc5adb55867046386c420e3155/pkg/cmd/roachtest/github.go#L155)):*
> ```Go
> 		messagePrefix = fmt.Sprintf("test %s was skipped due to ", testName)
> 		infraFlake = true
> 	case failureContainsError(firstFailure, rperrors.ErrSSH255):
> ```

These 2 cases can probably be collapsed into one. Might be good to add a test case for this. (There are already a bunch).

Also this will result in a brand new umbrella github issue for just `dns_problem` (if that's the way we want to go)
___
*[`pkg/roachprod/vm/gce/dns.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110831#-NedABMsCHKOHVvo5vLE:-NedABMsCHKOHVvo5vLF:bxo8x7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/78cb7371809511c3db0ec10529be18363df5cc2f/pkg/roachprod/vm/gce/dns.go#L271)):*
> ```Go
> // markDNSOperationError should be used to mark any external DNS API or Google
> // Cloud DNS CLI errors as DNS operation errors.
> func markDNSOperationError(err error) error {
> ```

nit: not sure this needs to be a separate function

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/github.go` line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110831#-NedAZvv-swPLfmLgKcY:-NegaKTD8y9_VHYnyHN5:b-au0z6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b672649da11909bc5adb55867046386c420e3155/pkg/cmd/roachtest/github.go#L155)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

These 2 cases can probably be collapsed into one. Might be good to add a test case for this. (There are already a bunch).

Also this will result in a brand new umbrella github issue for just `dns_problem` (if that's the way we want to go)
</blockquote></details>

Yes, we want a new umbrella issue, as intermittent network issues seem to be causing some failures and we want to track it. I like to have the cases explicit as it's easier to reference.
I'll add a test.
___
*[`pkg/roachprod/vm/gce/dns.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110831#-NedABMsCHKOHVvo5vLE:-NegdX8k9mrkfZNDjnWz:bry8tfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/78cb7371809511c3db0ec10529be18363df5cc2f/pkg/roachprod/vm/gce/dns.go#L271)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

nit: not sure this needs to be a separate function
</blockquote></details>

Probably not, but I felt like it made wrapping the errors a bit cleaner and easier to see what's going on.

**Review by smg260 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, and @renatolabs)

**Review by smg260 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, and @renatolabs)

**Comment by herkolategan** [comment]
TFTR!
bors r=smg260

**Comment by herkolategan** [comment]
bors r=smg260

**Pull request merged**
