### PR TITLE
vendor: bump Pebble to a1e7a77e1845

### PR DESCRIPTION
**Pull request by jbowens**
```
a1e7a77e db: avoid unnecessary key comparisons during iteration
1c415c00 *: update range-key masking docs
5a2941fb db: use block properties for efficient range-key masking
245afda9 db: add FormatMinTableFormatPebblev1 format major version
d3b3fb83 db: introduce a minimum table format for each format major version
```

Release note: None

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85468#-:-N8UJJ1x0gMHbeiat0le:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85468)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

___
*[`pkg/storage/testdata/mvcc_histories/sst_writer` line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85468#-N8UURn6A5dgA-NPOcPC:-N8UURn6A5dgA-NPOcPD:bn9lg3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b41357cebc00f67fefdfc51a85fa1a82aec6a24/pkg/storage/testdata/mvcc_histories/sst_writer#L46)):*
> ```
> error: (*withstack.withStack:) invalid range key {f-c}/1.000000000,0: start key "f" is at or after end key "c"
> 
> # Writing the same key multiple times (in different SSTs). Iteration sees the
> ```

Did one of the commits result in a test failure here?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85468)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nicktrav)

___
*[`pkg/storage/testdata/mvcc_histories/sst_writer` line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85468#-N8UURn6A5dgA-NPOcPC:-N8UVLjG5FYkZEjYbeEN:b-yq4dt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b41357cebc00f67fefdfc51a85fa1a82aec6a24/pkg/storage/testdata/mvcc_histories/sst_writer#L46)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Did one of the commits result in a test failure here?
</blockquote></details>

Yep, it's not legal to add identical keys to an sstable via `Writer.Set`, because the resulting keys have identical sequence numbers. This test was relying on undefined behavior, which just happened to return the first kv pair added to the sstable.

Going to prevent this in cockroachdb/pebble#1843.

**Comment by jbowens** [comment]
TFTR!

bors r=nicktrav

**Pull request merged**
