### PR TITLE
clusterversion: rename obsolete gates

### PR DESCRIPTION
**Pull request by RaduBerinde**
Prepend `TODODelete_` to the remaining pre-23.2 gates.

Epic: REL-696
Release note: None

### CODE REVIEW

**Review by celiala — APPROVED** [review]
:lgtm: 

> Reviewed 50 of 50 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122244#-:-NvEFeww0bUTEtpi7CgG:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @andyyang890, @DarrylWong, @dt, @nkodali, and @renatolabs)

**Review by andyyang890 — APPROVED** [review]

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Comment by dt** [comment]
In previous releases we've had a policy of waiting until zero release blockers / the final cluster version is minted on the release branch before we start make sweeping refactors/changes on master, since those kinds of changes are likely to cause merge conflicts and those slow down anyone working on a release-unblocking/ga-unblocking change. This can just be something that slows down/delays those changes just by nature of being big, sweeping changes that cause lots of conflicts, but also particularly if the change is only done on master, release-unblocking changes that need backport may then see that that change does not backport cleanly if it was developed on top of such refactors.

Did we intentionally decide to break from this policy with this change and https://github.com/cockroachdb/cockroach/pull/121775 ?

**Comment by RaduBerinde** [comment]
Last release I felt it was late because we had multiple folks asking when they can add a gate on master. I agree maybe this time it was too early (especially the clean-up part). I can update the runbooks - I think a good compromise would be to wait until the beta ships, does that sound good?

**Comment by dt** [comment]
I thought it was supposed to be first RC, ie when we don’t have any known work that is holding up the release and could be delayed — delaying the release in turn — by a refactor?

**Comment by dt** [comment]
I agree waiting until the release is _done_ is too late (last release was also anomalous in how long it was delayed) but I can see the argument for waiting until we hit 0 ga blockers ?

**Comment by RaduBerinde** [comment]
RC1 make sense. BTW I would think that sizable changes after beta would be developed on the release branch first (in any case it would be good to reduce friction no matter the porting direction).

**Pull request merged**
