### PR TITLE
sql: implement the CREATE SCHEMA command

### PR DESCRIPTION
**Pull request by rohany**
Built off of #49523.

This PR adds the ability to create schemas. Note that we don't support
qualification in the `CREATE SCHEMA` statement, and this is in line with
Postgres.

Release note: None

### CODE REVIEW

**Review by thoszhang — APPROVED** [review]
> Note that we don't support qualification in the `CREATE SCHEMA` statement, and this is in line with Postgres.

What exactly happens when there's no current database set for the connection?

I think this makes sense for now, but it doesn't seem that unreasonable to support qualified `db.schema` names in the future, since we already offer more support for qualified table names than Postgres does (in Postgres 3-part names are syntactically supported but will produce an error if the database isn't the current database, IIRC).

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50613#-:-MB-KOJT9bPVfa0QELA4:b-olce45)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by rohany** [comment]
> What exactly happens when there's no current database set for the connection?

In what case would you be creating a schema in this state?

I'd prefer to not have to extend past what postgres supports, because then we run into weird unintended cases. We can reevaluate this choice in the future though surely.

**Comment by lucy-zhang** [comment]
> In what case would you be creating a schema in this state?

This shouldn't be possible. I was just wondering what error we return.

**Comment by rohany** [comment]
> This shouldn't be possible. I was just wondering what error we return.

Oh i see -- I believe we'd return a database not found error. I'll update this to return a better error in that case.

**Comment by rohany** [comment]
TFTR!

bors r=lucy-zhang

**Pull request merged**
