### PR TITLE
backupccl: fix bug where cluster backups were exporting opt-out system tables

### PR DESCRIPTION
**Pull request by adityamaru**
This change fixes a bug that was introduced where we would include
revisions for descriptors that are not supposed to be backed up
egs: system tables that are opted out. This was introduced in
https://github.com/cockroachdb/cockroach/pull/68983 when we fixed
cluster backup to include dropped database descriptors.

The test would previously fail with an error that the descriptors table (an
opt out system table) did not have a span covering the time between the
`EndTime` of the first backup and second backup, since there are no revisions
to it between those backups.

Fixes: #71277

Release note (bug fix): Fix a bug where cluster backups were
backing up opt-out system tables unexpectedly.

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Review by stevendanna — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71288)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @stevendanna)

___
*[pkg/ccl/backupccl/system_schema.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71288#-MlTqqGoAkCkCdNPhNdE:-MlTqqGoAkCkCdNPhNdF:bj3ucqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b72d843f264a53583727e8b751ad8558dfd68a13/pkg/ccl/backupccl/system_schema.go#L375)):*
> ```Go
> }
> 
> // GetSystemTablesToIncludeInClusterBackup returns a set of system table ids
> ```

s/GetSystemTablesToIncludeInClusterBackup/GetSystemTableIDsToIncludeInClusterBackup/
___
*[pkg/ccl/backupccl/targets.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71288#-MlTwYGZ7IOoWo1B3rtH:-MlTwYGZ7IOoWo1B3rtI:b-wdsbwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b72d843f264a53583727e8b751ad8558dfd68a13/pkg/ccl/backupccl/targets.go#L82)):*
> ```Go
> 		return nil, err
> 	}
> 	isExcludedDescriptor := func(id descpb.ID) bool {
> ```

Maybe `isExcludedSystemTable` since this only knows about system tables.
___
*[pkg/ccl/backupccl/targets.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71288#-MlTrGwV12pAQAdJHjaq:-MlTrGwV12pAQAdJHjar:b-pih7sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b72d843f264a53583727e8b751ad8558dfd68a13/pkg/ccl/backupccl/targets.go#L92)):*
> ```Go
> 		// We're interested in changes to all descriptors if we're targeting all
> 		// descriptors except for the system database itself.
> 		if descriptorCoverage == tree.AllDescriptors && !isExcludedDescriptor(id) {
> ```

I'm occasionally boolean-impaired so apologies in advance if this is off base, but it isn't clear to me that this is correct and I think the test failures suggest that perhaps something is off here. 

Previously,  this condition ensured that `isInterestingID()` returned `true` for any non-system table when `descriptorCoverage == tree.AllDescriptors`. Now, it will never return true for non-system tables.

In `isExcludedDescriptor`,  `isOptInSystemTable` will be `false` for a non-system table since it won't be in our systemTableIDsToBackup map. `!isOptInSystemTable` will then be `true`, so `isExcludedDescriptor(id)` will be `true` for every non-system table.  

Perhaps this is OK because of the other inputs of this function. Is the rest of isInterestingID() is guaranteed to return `true` for non-system descriptors in the `descriptorCoverage == tree.AllDescriptors` case?

If this new behaviour is OK, then perhaps updating the comment above this condition might be good.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71288)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/ccl/backupccl/system_schema.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71288#-MlTqqGoAkCkCdNPhNdE:-MlV7G_85yjCiR9UJCr0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b72d843f264a53583727e8b751ad8558dfd68a13/pkg/ccl/backupccl/system_schema.go#L375)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

s/GetSystemTablesToIncludeInClusterBackup/GetSystemTableIDsToIncludeInClusterBackup/
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/targets.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71288#-MlTwYGZ7IOoWo1B3rtH:-MlVEzYJ-9nJdnyaAQeh:b-12kfhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b72d843f264a53583727e8b751ad8558dfd68a13/pkg/ccl/backupccl/targets.go#L82)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Maybe `isExcludedSystemTable` since this only knows about system tables.
</blockquote></details>

It also includes the system database descriptor as well so I decided to give it a more generic name. I'm happy to rename it if you feel strongly about it.
___
*[pkg/ccl/backupccl/targets.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71288#-MlTrGwV12pAQAdJHjaq:-MlVFC0C-Y25fJwkE1RT:b-nzgzlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b72d843f264a53583727e8b751ad8558dfd68a13/pkg/ccl/backupccl/targets.go#L92)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I'm occasionally boolean-impaired so apologies in advance if this is off base, but it isn't clear to me that this is correct and I think the test failures suggest that perhaps something is off here. 

Previously,  this condition ensured that `isInterestingID()` returned `true` for any non-system table when `descriptorCoverage == tree.AllDescriptors`. Now, it will never return true for non-system tables.

In `isExcludedDescriptor`,  `isOptInSystemTable` will be `false` for a non-system table since it won't be in our systemTableIDsToBackup map. `!isOptInSystemTable` will then be `true`, so `isExcludedDescriptor(id)` will be `true` for every non-system table.  

Perhaps this is OK because of the other inputs of this function. Is the rest of isInterestingID() is guaranteed to return `true` for non-system descriptors in the `descriptorCoverage == tree.AllDescriptors` case?

If this new behaviour is OK, then perhaps updating the comment above this condition might be good.
</blockquote></details>

This is a great catch thanks! I'm glad we had a test that failed.

We want to include all IDs except opt-out system table IDs and the system database ID.
The previous condition was incorrect, and so I've changed it to correctly represent the above statement.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71288)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71288#-MlYftry4wd90tMZ4ann:-MlYftry4wd90tMZ4ano:b-yxwa99) (no related file):*
:lgtm: 

The issue with system tables in tenants is interesting.  It might be nice if we had a list of which tables we expect to be missing from a tenant.  But, that could be done at a later date if we think it is valuable.

---
___
*[pkg/ccl/backupccl/system_schema.go, line 390 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71288#-MlYflmvC4zLtX0shSny:-MlYflmvC4zLtX0shSnz:bmstsr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/be3553888816ad55f3bba62cbfcb90b35f685201/pkg/ccl/backupccl/system_schema.go#L390)):*
> ```Go
> 				}
> 				if !found {
> 					log.Warningf(ctx, "could not find system table descriptor %s", systemTableName)
> ```

A comment on why we might expect some to not be found could be useful.

**Comment by adityamaru** [comment]
>The issue with system tables in tenants is interesting. It might be nice if we had a list of which tables we expect to be missing from a tenant. But, that could be done at a later date if we think it is valuable.

Agreed, wouldn't be hard to add to the config.

**Pull request merged**
