### PR TITLE
server: add metadata for cloud provider region to diagnostics

### PR DESCRIPTION
**Pull request by sploiselle**
Track the name of the cloud provider's region where nodes are located at
`/_status/diagnostics/local`. Include functions to capture this data for
VMs running on AWS, GCP, and Azure. All other platforms return empty
strings.

Also refactor prior PR (#37272) with a more modular/extensible design.

### CODE REVIEW

**Review by dt — APPROVED** [review]
LGTM, though I'm always a little bit wary of adding non-const string fields, but I don't know if/how that would be a problem here (unless some cloud let you define custom region names or something) so probably fine. cc @bdarnell though in case I'm missing something.

**Review by bdarnell — APPROVED** [review]

**Comment by ajkr** [comment]
Oops this rolled back our RocksDB upgrade.

**Comment by ajkr** [comment]
I'll fixup c-deps/rocksdb. c-deps/libedit also changed -- was it intended?

**Comment by sploiselle** [comment]
@ajkr Not at all. This must have been a fat finger on my final rebase.

**Pull request merged**
