### PR TITLE
roachtest: cleanup and fix bug in restore roachtest framework

### PR DESCRIPTION
**Pull request by adityamaru**
Please refer to individual commits.

Informs: https://github.com/cockroachdb/cockroach/issues/112539

### CODE REVIEW

**Comment by adityamaru** [comment]
I want to run a few tests just to make sure I don't cause havoc in the nightlies but this should be ready for a look. I would like to consider backporting this especially cause it fixes a bug in our 32tb weeklies but if you're not convinced theres a smaller patch that can be whipped up for that too.

**Review by msbutler — APPROVED** [review]
Thanks for doing this! Fine to backport to 23.2 after a nightly run.

**Comment by adityamaru** [comment]
going to pick this up and merge on monday. I want to avoid doing anything on a friday and cause weekend full of failures.

**Review by msbutler — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=msbutler

For posterity our current restore roachtests:

```
restore/nodeShutdown/coordinator [disaster-recovery]
restore/nodeShutdown/worker [disaster-recovery]
restore/pause/tpce/15GB/aws/nodes=4/cpus=8 [disaster-recovery]
restore/tpce/15GB/aws/nodes=4/cpus=8 [disaster-recovery]
restore/tpce/32TB/aws/inc-count=400/nodes=15/cpus=16 [disaster-recovery]
restore/tpce/32TB/aws/nodes=15/cpus=16 [disaster-recovery]
restore/tpce/32TB/gce/inc-count=400/nodes=15/cpus=16 [disaster-recovery]
restore/tpce/400GB/aws/inc-count=48/nodes=4/cpus=8 [disaster-recovery]
restore/tpce/400GB/aws/nodes=4/cpus=16 [disaster-recovery]
restore/tpce/400GB/aws/nodes=4/cpus=8 [disaster-recovery]
restore/tpce/400GB/aws/nodes=8/cpus=8 [disaster-recovery]
restore/tpce/400GB/aws/nodes=9/cpus=8/zones=us-east-2b,us-west-2b,eu-west-1b [disaster-recovery]
restore/tpce/400GB/gce/nodes=4/cpus=8 [disaster-recovery]
restore/tpce/400GB/gce/nodes=4/cpus=8/lowmem [disaster-recovery]
restore/tpce/8TB/aws/nodes=10/cpus=8 [disaster-recovery]
```

**Comment by adityamaru** [comment]
blathers backport 23.2

**Pull request merged**
