### PR TITLE
go.mod: bump Pebble to 030afd266b2d

### PR DESCRIPTION
**Pull request by jbowens**
Note this commit includes manual changes to use the new KeySchema configuration API.

Changes:

 * [`030afd26`](https://github.com/cockroachdb/pebble/commit/030afd26) colblk: use UnsafeOffsets.At2 in another instance
 * [`b3993ff6`](https://github.com/cockroachdb/pebble/commit/b3993ff6) db: persist Experimental.EnableColumnarBlocks in OPTIONS file
 * [`c719c4e5`](https://github.com/cockroachdb/pebble/commit/c719c4e5) db: support multiple KeySchemas

Release note: none.
Epic: none.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Comment by jbowens** [comment]
The MVCC metamorphic tests failed 😬

**Comment by RaduBerinde** [comment]
I don't get it, we're not even enabling the new format.. I looked at the code around `opts.Experimental.EnableColumnarBlocks` again and it seems fine..

**Comment by RaduBerinde** [comment]
They pass with this patch to `options.go`:
```diff
                        case "comparer":
-                               o.Comparer, err = parseComparer(value)
+                               var comparer *Comparer
+                               comparer, err = parseComparer(value)
+                               if comparer != nil {
+                                       o.Comparer = comparer
+                               }
```

**Comment by jbowens** [comment]
Superseded by #132849

**Pull request closed without merging**
