### PR TITLE
opt: refactor used indexes

### PR DESCRIPTION
**Pull request by mgartner**
I noticed the unnecessary usage of strings to track index usage in some
CPU/heap profiles. I attempted to eliminate this entirely, but
unfortunately these strings are persisted, making modification of the
type difficult, and I had difficulty following the thread from their
creation all the way to their consumption - I think someone with more
expertise in the observability part of the code base would be required
to untangle this.

So for now I've settled for refactoring the creation of "used indexes" to
avoid using strings until later on during instrumentation. This has the
minor benefit possible de-duplicating the indexes before generating the
strings, if an index is used multiple times in a query.

I've also replaced the expensive usage of `fmt.Sprintf` for generating
the strings to the faster `+` concatenation (benchmarks for this are
at: https://gist.github.com/mgartner/28a9d52e54e91691d0a7617164aa3157).

Epic: None

Release note: None

### CODE REVIEW

**Comment by angles-n-daemons** [comment]
After a bit of consultation, it seems as if the protobuf in question (SampledQuery) is used to surface sql execution details to an ICP search index. In such a search index, the table / index name seems like the best representation for this information - does this track?

https://www.cockroachlabs.com/docs/v24.2/log-sql-statistics-to-datadog.html

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132365#-:-O9M-pJO5m9XgoohEA97:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons)

**Review by angles-n-daemons — APPROVED** [review]
:lgtm: also looks good, lmk if a ticket to modify the insights struct types would be useful

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132365#-:-O9PjvG1E9nfO5GQYtGz:b4f3l98)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
>The first (SampledQuery) [is used to surface sql execution details to an ICP search index](https://www.cockroachlabs.com/docs/v24.2/log-sql-statistics-to-datadog.html). In such a search index, the table / index name seems like the best representation for this information - does this track?

I agree the table and index name are useful. Instead of creating a string with integer IDs, not names, in the form `<table_id>@<index_id>`, we should track them as two `uint64`s up until the point where they are converted to table name and index name strings. I think an issue to track that would be great!

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
