### PR TITLE
Add roachtest for pgx

### PR DESCRIPTION
**Pull request by apantel**
#40724 

Run pgx's test suite against a cockroach cluster.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
Thanks for getting this in!

Could you squash these all into one commit, and force-push the PR? In general, it is definitely fine (and sometimes encouraged) to have multiple commits in a PR, but we still want each commit to be able to stand alone as an independent chunk of work. A common reason to break up a PR into multiple commits is to make it easier to review.

Also, take a look at the commit message requirements: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages The big one is to make sure the commit (not just the PR) has release notes in it; in this case it would be `Release notes: None`. You should see a commit message template whenever creating a new commit. Or take a look at some recent commits in the repo to see other examples.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-:-LuEfdWj00QoTjaL0afS:bq8tn7z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel and @rafiss)

___
*[pkg/cmd/roachtest/pgx.go, line 93 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-LuEgrUv5R5viQ134pDI:-LuEgrUv5R5viQ134pDJ:bwixr1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4d7531130b44cc7f084cccc4725a68a19801a0e/pkg/cmd/roachtest/pgx.go#L93)):*
> ```Go
> 		}
> 
> 		// This is expected to fail because the feature is unsupported by Cockroach, but pgx expects it.
> ```

in the comment, could you link to the github issue that describes the failure reason?
___
*[pkg/cmd/roachtest/pgx.go, line 118 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-LuEhSh3622ZCfk7pNik:-LuEhSh3622ZCfk7pNil:bpjacj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4d7531130b44cc7f084cccc4725a68a19801a0e/pkg/cmd/roachtest/pgx.go#L118)):*
> ```Go
> 	r.Add(testSpec{
> 		Name:    "pgx",
> 		Cluster: makeClusterSpec(1),
> ```

i think we should throw in `MinVersion: "v19.2.0",` in here
___
*[pkg/cmd/roachtest/pgx_blacklist.go, line 14 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-LuEhdB787dkV-WsULvC:-LuEhdB787dkV-WsULvD:b-mwc5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4d7531130b44cc7f084cccc4725a68a19801a0e/pkg/cmd/roachtest/pgx_blacklist.go#L14)):*
> ```Go
> 
> var pgxBlacklists = blacklistsForVersion{
> 	{"v20.1", "pgxBlacklist20_1", pgxBlackList20_1, "pgxIgnoreList20_1", pgxIgnoreList20_1},
> ```

let's also add a blacklist for v19.2. for now, it will be the exact same as the 20.1 blacklist, but over time some fixes will go into one release but not the other, so we should have two separate lists.
___
*[pkg/cmd/roachtest/pgx_blacklist.go, line 33 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-LuEhtDH-pCXSI16_wTz:-LuEhtDH-pCXSI16_wU-:bh9acl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4d7531130b44cc7f084cccc4725a68a19801a0e/pkg/cmd/roachtest/pgx_blacklist.go#L33)):*
> ```Go
> 	"v4.TestConnQueryDatabaseSQLDriverValuerWithAutoGeneratedPointerReceiver": "5807",
> 	"v4.TestConnQueryDeferredError":                                           "31632",
> 	"v4.TestConnQueryErrorWhileReturningRows":                                 "unknown", // error not returned
> ```

let's try to triage together all the unknown ones before merging this

**Review by apantel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/cmd/roachtest/pgx.go, line 93 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-LuEgrUv5R5viQ134pDI:-LuIlfkL2WHqz0UWCaHT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4d7531130b44cc7f084cccc4725a68a19801a0e/pkg/cmd/roachtest/pgx.go#L93)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in the comment, could you link to the github issue that describes the failure reason?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/pgx.go, line 118 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-LuEhSh3622ZCfk7pNik:-LuIlgfb5VX9myTCSwtF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4d7531130b44cc7f084cccc4725a68a19801a0e/pkg/cmd/roachtest/pgx.go#L118)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we should throw in `MinVersion: "v19.2.0",` in here
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/pgx_blacklist.go, line 14 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-LuEhdB787dkV-WsULvC:-LuIlj-AAblq8TtJmouP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4d7531130b44cc7f084cccc4725a68a19801a0e/pkg/cmd/roachtest/pgx_blacklist.go#L14)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

let's also add a blacklist for v19.2. for now, it will be the exact same as the 20.1 blacklist, but over time some fixes will go into one release but not the other, so we should have two separate lists.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/pgx_blacklist.go, line 33 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-LuEhtDH-pCXSI16_wTz:-LuIlkJF4dNVxk8JDkwC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4d7531130b44cc7f084cccc4725a68a19801a0e/pkg/cmd/roachtest/pgx_blacklist.go#L33)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

let's try to triage together all the unknown ones before merging this
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
thank you for triaging everything! this lgtm apart from a few suggestions about comments, so i'm going to approve and then you can merge whenever it's fixed

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-:-LuK0LvY4OWxp7rSQKQn:b-xztr0e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel and @rafiss)

___
*[pkg/cmd/roachtest/pgx.go, line 49 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-LuJz0IM68LMyBEWbD1X:-LuJz0IM68LMyBEWbD1Y:b-x0gdws) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c97806a237fe482d40b9401bc595502e41bf8e/pkg/cmd/roachtest/pgx.go#L49)):*
> ```Go
> 		installLatestGolang(ctx, t, c, node)
> 
> 		// Using apantel's fork of pgx as a temporary solution to flakiness. Revert to jackc's when fixed.
> ```

start this comment with `TODO(apantel):`, just so that there's an owner / it's easy to find out who to ask about this.
___
*[pkg/cmd/roachtest/pgx.go, line 100 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42623#-LuK0DLQ72HpC00tv_0c:-LuK0DLQ72HpC00tv_0d:b-xu24sk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4c97806a237fe482d40b9401bc595502e41bf8e/pkg/cmd/roachtest/pgx.go#L100)):*
> ```Go
> 		)
> 
> 		// Change the path from apantel to jackc when the flakiness is fixed.
> ```

nit: add a `TODO(apantel)`

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel and @rafiss)

**Pull request merged**
