### PR TITLE
opt: fold constant IS {NOT,} NULL scalar exprs

### PR DESCRIPTION
**Pull request by justinj**
Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/norm/rules/scalar.opt, line 142 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24644#-L9lQV0N9QLr2kjkTihI:-L9lQV0N9QLr2kjkTihJ:b-359hvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6172910ceea81c0dfa67fea6d1264434fe1b3f0c/pkg/sql/opt/norm/rules/scalar.opt#L142)):*
> ```
> (Null (BoolType))
> 
> # FoldIsNull replaces NULL IS NULL with True.
> ```

Can you move these rules into `comp.opt`? I've consolidated all `Comparison` operator rules there.

---

*[pkg/sql/opt/norm/rules/scalar.opt, line 148 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24644#-L9lQnBUEvPkG9oG_AO3:-L9lQnBUEvPkG9oG_AO4:b-z1pvze) ([raw file](https://github.com/cockroachdb/cockroach/blob/6172910ceea81c0dfa67fea6d1264434fe1b3f0c/pkg/sql/opt/norm/rules/scalar.opt#L148)):*
> ```
> # FoldNonNullIsNull replaces x IS NULL with False where x is a non-Null constant.
> [FoldNonNullIsNull, Normalize]
> (Is ^(Null) & (ConstValue) (Null)) => (False)
> ```

NIT: I'd flip this rule to be like this, and format it like this:
```
(Is
  (ConstValue) & ^(Null)
  (Null)
)
=>
(False)
```
The reasons are:
1. It's slightly better to put the most selective filters first. A value is less likely to be a Const than to be non-Null.
2. When I have rules with multiple operands using `&`, I put each operand on a separate line for clarity. Otherwise, it's harder to follow.

---

*[pkg/sql/opt/norm/rules/scalar.opt, line 156 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24644#-L9lTQyO03yP-byTbv0B:-L9lTQyO03yP-byTbv0C:b-ir1mjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6172910ceea81c0dfa67fea6d1264434fe1b3f0c/pkg/sql/opt/norm/rules/scalar.opt#L156)):*
> ```
> # FoldNonNullIsNotNull replaces x IS NOT NULL with True where x is a non-Null constant.
> [FoldNonNullIsNotNull, Normalize]
> (IsNot ^(Null) & (ConstValue) (Null)) => (True)
> ```

Consider adding a rule like:
```
[CommuteNullIs]
(Is | IsNot
  $left:(Null)
  $right:^(Null)
)
=>
((OpName) $right $left)
```
This will allow the `FoldNonNullIsNull`, etc. rules to match either way. It will also make it easy to match `IS NULL` cases in other rules.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24644)*

**Comment by rytaft** [comment]
:lgtm: once you address Andy's comments

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24644#-:-L9ox6Tv3FvK1_DbPUSF:bln53mx)*

**Comment by justinj** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/norm/rules/scalar.opt, line 142 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24644#-L9lQV0N9QLr2kjkTihI:-L9p8HKA41zgzhmGwdOH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6172910ceea81c0dfa67fea6d1264434fe1b3f0c/pkg/sql/opt/norm/rules/scalar.opt#L142)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can you move these rules into `comp.opt`? I've consolidated all `Comparison` operator rules there.
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/scalar.opt, line 148 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24644#-L9lQnBUEvPkG9oG_AO3:-L9pIgAg8rR2aBqwizdx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6172910ceea81c0dfa67fea6d1264434fe1b3f0c/pkg/sql/opt/norm/rules/scalar.opt#L148)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: I'd flip this rule to be like this, and format it like this:
```
(Is
  (ConstValue) & ^(Null)
  (Null)
)
=>
(False)
```
The reasons are:
1. It's slightly better to put the most selective filters first. A value is less likely to be a Const than to be non-Null.
2. When I have rules with multiple operands using `&`, I put each operand on a separate line for clarity. Otherwise, it's harder to follow.
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/scalar.opt, line 156 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24644#-L9lTQyO03yP-byTbv0B:-L9pBYKACrsVThvGOItR:bymjr1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/6172910ceea81c0dfa67fea6d1264434fe1b3f0c/pkg/sql/opt/norm/rules/scalar.opt#L156)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Consider adding a rule like:
```
[CommuteNullIs]
(Is | IsNot
  $left:(Null)
  $right:^(Null)
)
=>
((OpName) $right $left)
```
This will allow the `FoldNonNullIsNull`, etc. rules to match either way. It will also make it easy to match `IS NULL` cases in other rules.
</blockquote></details>

Done, and added a test case which checks it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24644)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24644#-:-L9pMHiq-CK6l5DTYj9H:bnfp4nl)*

**Comment by justinj** [comment]
TFTRs!

bors r+

**Pull request merged**
