### PR TITLE
kvpb,kvserver: add range id, span to BatchTimestampBeforeGCError

### LINKED ISSUE #131256: kv: add start/end key to kvpb.BatchTimestampBeforeGCError
Today, kvpb.BatchTimestampBeforeGCError produces an error like "batch timestamp %v must be after replica GC threshold %v". It would be useful if this error message also included information about the range affected (e.g., start/end key), since it's difficult to tell which table was affected by GC.

Jira issue: CRDB-42460

Epic CRDB-37617

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, debugging a `BatchTimestampBeforeGCError` is difficult, as there information is lacking as to replica / range tried to touch underneath the GC threshold.

Add the range ID and span to the error message.

Fixes #131256.

Release note: None.

### CODE REVIEW

**Review by andyyang890 — APPROVED** [review]
Nice, thanks!

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131545)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nicktrav)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131545#-O82yq6tAuFKTE34QV7E):*
nit: s/kvp/kvpb/

**Review by stevendanna — APPROVED** [review]
This would have been super helpful in a number of places.

**Comment by nicktrav** [comment]
TFTRs!

bors r+

**Comment by arulajmani** [comment]
blathers backport 24.2 24.1 23.2

**Pull request merged**
