### PR TITLE
server: introduce the `Migration` service

### PR DESCRIPTION
**Pull request by irfansharif**
The upcoming migration manager (prototyped in #56107) will want to
execute a few known RPCs on every node in the cluster. Part of being the
"migration infrastructure", we also want authors of individual
migrations to be able to define arbitrary node-level operations to
execute on each node in the system.

To this end we introduce a `Migration` service, and populate it with the
two known RPCs the migration manager will want to depend on:
- ValidateTargetClusterVersion: used to verify that the target node is
  running a binary that's able to support the given cluster version.
- BumpClusterVersion: used to inform the target node about a (validated)
  cluster version bump.

Both these RPCs are not currently wired up to anything, and
BumpClusterVersion will be fleshed out just a tiny bit further in a
future PR, but they'll both be used to propagate cluster version bumps
across the crdb cluster through direct RPCs, supplanting our existing
gossip based distribution mechanism. This will let the migration manager
bump version gates in a more controlled fashion. See #56107 for what
that will end up looking like, and see the long-running migrations RFC
(#48843) for the motivation.

Like we mentioned earlier, we expect this service to pick up more RPCs
over time to service specific migrations.

Release note: None

---

Ignore the first four commits. They're from #56368 and #56474

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56476)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/server/migration.go, line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlUCCX6KTHNjWUrmMc:-MLlUCCX6KTHNjWUrmMd:b-y07r6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L31)):*
> ```Go
> 	server *Server
> 
> 	// We used this mutex to serialize attempts to bump the cluster version.
> ```

We use
___
*[pkg/server/migration.go, line 48 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlTGiD8ycUCeu4QzvA:-MLlTGiE6GeOIuEh9IVZ:b-p3uxz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L48)):*
> ```Go
> 	// We're validating the following:
> 	//
> 	//   node's minimum supported version <= target version <= node's binary version
> ```

Why does the min supported version even come into play? Aren't we also validating that we're not winding back the cluster version (I guess leaving it at the same place is necessary for idempotence), i.e. why isn't this

```go
if targetVersion.Less(versionSetting.ActiveVersion())
```

The active version is >= the binary min supported, so this is just a stricter check.
___
*[pkg/server/migration.go, line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlU2xY7BWvFF0ZGyB8:-MLlU2xY7BWvFF0ZGyB9:bb7luxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L68)):*
> ```Go
> 
> // BumpClusterVersion implements the MigrationServer interface. It's used to
> // inform us a cluster version bump. Here we're responsible for durably
> ```

of a
___
*[pkg/server/migration.go, line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlUJgkEEr1jnuzwmsv:-MLlUJgkEEr1jnuzwmsw:b1c8ad6) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L90)):*
> ```Go
> 		}
> 
> 		m.Lock()
> ```

Shouldn't `BumpClusterVersion` in its entirety be under this lock? `prevCV` might've changed by the time you get here.
___
*[pkg/server/migration.go, line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlU_Ib0PwT1I7i3u1i:-MLlU_Ib0PwT1I7i3u1j:btnl20z) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L94)):*
> ```Go
> 
> 		// TODO(irfansharif): We should probably capture this pattern of
> 		// "persist the cluster version first" and only then bump the
> ```

Do we? This will be the only place that adjusts the cluster version, so keeping it explicitly as two steps carried out in a certain order (with a comment) seems totally fine.
___
*[pkg/server/migration.go, line 107 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlUpJXCmDrKYPcXrmf:-MLlUpJXCmDrKYPcXrmg:bn5j1yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L107)):*
> ```Go
> 		// gate here. On 21.1 nodes we'll no longer be using gossip to propagate
> 		// cluster version bumps. We'll still have probably disseminate it
> 		// through gossip (do we actually have to?), but we won't listen to it.
> ```

I don't think we do! I mean, we kind of will anyway, at least as long as the version setting is hooked up and updated, simply because it's not worth avoiding to do so.
___
*[pkg/server/migration_test.go, line 37 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlUy80B4Z_g8lZdtDi:-MLlUy80B4Z_g8lZdtDj:b7jjpnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration_test.go#L37)):*
> ```Go
> 		binaryMinSupportedVersion roachpb.Version
> 		targetVersion             roachpb.Version
> 		expErrMatch               string // Empty if expecting a nil error.
> ```

super nit: the old thing about lowercase and no punctuation in inline comments
___
*[pkg/server/serverpb/migration.proto, line 42 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlVZWiAoLwHaO6cYrX:-MLlVZWj7GZPVCJzP8Ir:b-8t62m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/serverpb/migration.proto#L42)):*
> ```protobuf
>    // Specifically:
>    //
>    //   node's minimum supported version <= version <= node's binary version
> ```

see my other comment, this here may need an update as well if we change the impl
___
*[pkg/server/serverpb/migration.proto, line 53 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlVkLWEs2QDW9KuzPU:-MLlVkLWEs2QDW9KuzPV:bbf18a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/serverpb/migration.proto#L53)):*
> ```protobuf
>    // that would be able to support the intended version bump.
>    //
>    // NB: We should note that this validation is a best-effort one. Albeit
> ```

This is why we discussed noop-versions before any real version. The first version bump will be into v21.2.0-1noop. If the 21.1 node sneaks in  there, it won't do any harm because that version bump does by definition not change behavior in the 21.2 nodes. Any further bump will include the 21.1 node and will thus fail.
If the 21.1 node tries to show up after 21.2.0-1noop is active, it can't join.

If you don't mind, update that comment to reflect this.

This may also be a good place (for now) to write the comment about how the migration manager will load the list of nodes, roll out, load the list again, and roll out again if anything changed (until the node list stabilizes), which prevents a cluster version from becoming active without having been pushed to all nodes. This would reference the join RPC (which propagates the active version) and also the fact that the cluster version becomes "active" only after it has been "bumped" across the cluster using this RPC.

Perhaps the comment will eventually move elsewhere, but it does seem super relevant to write it early.

**Review by tbg — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 5 files at r2, 2 of 3 files at r3, 1 of 3 files at r4, 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56476)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

**Review by knz — COMMENTED** [review]
no more comment besides what Tobias already provided.

> Reviewed 2 of 3 files at r1, 1 of 5 files at r2, 2 of 3 files at r3, 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-:-MLmP4L07htw3VXK8AAe:bqg7loa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/server/migration_test.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLmOqRd9AWnRuysIjMb:-MLmOqRd9AWnRuysIjMc:bs7xog1) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration_test.go#L65)):*
> ```Go
> 	}
> 
> 	//   node's minimum supported version <= target version <= node's binary version
> ```

nit: comment should be a sentence.

**Review by irfansharif — COMMENTED** [review]
Thanks for the reviews y'all.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-:-MLp1mkC22gI5GUXnVM4:by9jgd4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/server/migration.go, line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlUCCX6KTHNjWUrmMc:-MLou18L3ufz95fsa00A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L31)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

We use
</blockquote></details>

Done.
___
*[pkg/server/migration.go, line 48 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlTGiD8ycUCeu4QzvA:-MLp-lFqDrEedE4Svnnl:b-9gr8ob) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L48)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why does the min supported version even come into play? Aren't we also validating that we're not winding back the cluster version (I guess leaving it at the same place is necessary for idempotence), i.e. why isn't this

```go
if targetVersion.Less(versionSetting.ActiveVersion())
```

The active version is >= the binary min supported, so this is just a stricter check.
</blockquote></details>

I don't really have a super good reason here I'll try anyway: I think my inclination here to think in terms of binary versions comes from the fact that the errors here, if any, are going to be bubbled up to the user directly during improper cluster upgrade attempts. I think during these attempts it's much more understandable to talk in terms of the binaries they're running (and not running), rather than the active version any given binary is running.

The structure here also resembles the `validateBinaryVersions` check we have for cluster version settings, and yes we're making sure that we're not regressing on the cluster version elsewhere.
___
*[pkg/server/migration.go, line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlU2xY7BWvFF0ZGyB8:-MLoyGSl26yUdcDrutmR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L68)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

of a
</blockquote></details>

Done.
___
*[pkg/server/migration.go, line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlUJgkEEr1jnuzwmsv:-MLoyHJECjxxCUMsPLeu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L90)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Shouldn't `BumpClusterVersion` in its entirety be under this lock? `prevCV` might've changed by the time you get here.
</blockquote></details>

Done.
___
*[pkg/server/migration.go, line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlU_Ib0PwT1I7i3u1i:-MLoyIJJ97V0VsIv5SsN:bwyvh12) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L94)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Do we? This will be the only place that adjusts the cluster version, so keeping it explicitly as two steps carried out in a certain order (with a comment) seems totally fine.
</blockquote></details>

It happens in two other spots during node start up:
- when joining an existing cluster and receiving a target cluster version.
- when bootstrapping, where we initialize at the binary version and also persist it.

I'm not sure that I'll do much here soon, but there's definitely some drive by clean up to be had.
___
*[pkg/server/migration.go, line 107 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlUpJXCmDrKYPcXrmf:-MLoyyyD4H6HKwlDcJvu:bi00jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration.go#L107)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't think we do! I mean, we kind of will anyway, at least as long as the version setting is hooked up and updated, simply because it's not worth avoiding to do so.
</blockquote></details>

Yea, excited to see us introduce dedicated syntax for versions soon so we can strip it all out entirely.
___
*[pkg/server/migration_test.go, line 37 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlUy80B4Z_g8lZdtDi:-MLoz6Mh0Q3qz4J5vT7J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/migration_test.go#L37)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

super nit: the old thing about lowercase and no punctuation in inline comments
</blockquote></details>

Done.
___
*[pkg/server/serverpb/migration.proto, line 53 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56476#-MLlVkLWEs2QDW9KuzPU:-MLoz8NN6u6dRxvfL5EH:b-ko6ht9) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c25888ba7e4c118441904363274508e096cc03/pkg/server/serverpb/migration.proto#L53)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This is why we discussed noop-versions before any real version. The first version bump will be into v21.2.0-1noop. If the 21.1 node sneaks in  there, it won't do any harm because that version bump does by definition not change behavior in the 21.2 nodes. Any further bump will include the 21.1 node and will thus fail.
If the 21.1 node tries to show up after 21.2.0-1noop is active, it can't join.

If you don't mind, update that comment to reflect this.

This may also be a good place (for now) to write the comment about how the migration manager will load the list of nodes, roll out, load the list again, and roll out again if anything changed (until the node list stabilizes), which prevents a cluster version from becoming active without having been pushed to all nodes. This would reference the join RPC (which propagates the active version) and also the fact that the cluster version becomes "active" only after it has been "bumped" across the cluster using this RPC.

Perhaps the comment will eventually move elsewhere, but it does seem super relevant to write it early.
</blockquote></details>

Done. Thanks for spelling it out, I feel like it's the third time this has clicked for me; I keep forgetting it.

**Pull request merged**
