### PR TITLE
roachtest: add support for subtests

### LINKED ISSUE #23915: roachtest: Reuse clusters across test families
Our jepsen test suite currently runs 70 permutations of test+nemesis. In porting this to roachtest, these would ideally each be their own `testSpec`, but since each `testSpec` gets a new cluster this would cause the cluster setup time to dominate (including both VM creation and installing java and other dependencies that aren't used by our other tests). We should be able to have a cluster that is shared across all jepsen tests to amortize this cost.

The workaround is to make the entire jepsen test suite a single "test", but this has limitations for error reporting.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #23915

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
The first two commits are #25394. Feel free to review the whole kit and caboodle here. 

I haven't been able to successfully run this remotely due to current wifi conditions.

**Comment by petermattis** [comment]
PS 
```
~ roachtest run -n jepsen | grep RUN | wc -l
      78
```

**Comment by petermattis** [comment]
Fixed a bunch of small bugs this morning. Seems to be working. At least, I can run `roachtest run jepsen/sequential` and have only the `sequential` jepsen test run with the various nemeses and it only creates the cluster once.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[pkg/cmd/roachtest/jepsen.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25408#-LCFO1U907WB7GxHEy5B:-LCFO1U907WB7GxHEy5C:b-7fm362) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2db84ece2acbd7a989ba2b20fc2a44ff4fdceb5/pkg/cmd/roachtest/jepsen.go#L135)):*
> ```Go
> 	// work around JSCH auth error: https://github.com/jepsen-io/jepsen/blob/master/README.md
> 	for _, ip := range workerIPs {
> 		host, _, err := net.SplitHostPort(ip)
> ```

`InternalIP` includes the port number? That's confusing.  The method should be renamed to `InternalAddr` instead of `InternalIP`. Why didn't you need this for `nodeFlags` above?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25408#-:-LCFPfLp6mUzz-q-yC_v:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cmd/roachtest/jepsen.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25408#-LCFO1U907WB7GxHEy5B:-LCFcBOB2Iq-RMZFw8K6:bu52h7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2db84ece2acbd7a989ba2b20fc2a44ff4fdceb5/pkg/cmd/roachtest/jepsen.go#L135)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

`InternalIP` includes the port number? That's confusing.  The method should be renamed to `InternalAddr` instead of `InternalIP`. Why didn't you need this for `nodeFlags` above?
</blockquote></details>

I did need something similar for `nodeFlags`. I think you saw the output of a messed up rebased which accidentally dropped this from `nodeFlags`. I had a similar thought about `InternalAddr` when driving around just now. I've made that change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25408)*

**Comment by petermattis** [comment]
bors r=bdarnell

**Pull request merged**
