### PR TITLE
ui: fix generated protos.d.ts

### PR DESCRIPTION
**Pull request by petermattis**
Apparently something upstream changed causing the generated protos.d.ts
to change.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8373)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

Very random update https://github.com/SINTEF-9012/Proto2TypeScript/pull/13

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8373#-:-KOeQaPQ_PuYQ-m9bnV7:bppb92i)*

**Comment by petermattis** [comment]
Why did that update affect us without us upgrading dependencies?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8373#-:-KOeR6Cq1w38EXwZFquU:bfefmyg)*

**Comment by tamird** [comment]
Because we don't shrinkwrap those dependencies (the ones in build/).

**Comment by petermattis** [comment]
> Because we don't shrinkwrap those dependencies (the ones in build/).

Why not?

**Comment by tamird** [comment]
Upstream is usually dormant, so I didn't feel the need. I'll send a PR
after this goes in.

**Pull request closed without merging**
