### PR TITLE
storage: fix maintenance of TimestampCache.bytes

### LINKED ISSUE #15950: storage: timestampCache "bad reqSize" panic
https://sentry.io/cockroach-labs/cockroachdb/issues/274120395/

Looks to be this code:

```go
		if tc.bytes < reqSize {
			panic(fmt.Sprintf("bad reqSize: %d < %d", tc.bytes, reqSize))
		}
```

```
*errors.errorString: string timestamp_cache.go:207
  File "github.com/cockroachdb/cockroach/pkg/storage/timestamp_cache.go", line 207, in func1
  File "github.com/cockroachdb/cockroach/pkg/util/cache/cache.go", line 289, in removeElement
  File "github.com/cockroachdb/cockroach/pkg/util/cache/cache.go", line 259, in DelEntry
  File "github.com/cockroachdb/cockroach/pkg/storage/timestamp_cache.go", line 304, in add
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 412, in leasePostApply
...
(9 additional frame(s) were not displayed)

string timestamp_cache.go:207
```

### PR DESCRIPTION
**Pull request by petermattis**
We were failing to update TimestampCache.bytes correctly when performing
in-place modifications of cache entries.

Fixes #15950

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/timestamp_cache.go, line 312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503#-KmXmoWd2zk7hRoZI5y_:-KmXmoWd2zk7hRoZI5ya:b-on346v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40be245bc463226afb2ed138da664cf1bf322e0/pkg/storage/timestamp_cache.go#L312)):*
> ```Go
> 					// Old:
> 					tcache.DelEntry(entry)
> 					continue // deleted the current entry, don't update tc.bytes
> ```

Maybe it's because I'm looking at this in diff form, but this seems really strange. Isn't this exactly where we want to do `tc.bytes -= oldSize`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503#-:-KmXo7F93YaW1vCcJU-w:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/timestamp_cache.go, line 312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503#-KmXmoWd2zk7hRoZI5y_:-KmXoW0FmodZr9vsTj-O:be6mz38) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40be245bc463226afb2ed138da664cf1bf322e0/pkg/storage/timestamp_cache.go#L312)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Maybe it's because I'm looking at this in diff form, but this seems really strange. Isn't this exactly where we want to do `tc.bytes -= oldSize`? 
</blockquote></details>

`DelEntry` causes the `onEvicted` function to get invoked which adjusts `tc.bytes`. The `continue` is necessary so we don't adjust `tc.bytes` twice for the same entry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503)*

**Comment by tschottdorf** [comment]
I think you mentioned having discovered this in a test, but I don't see testing coverage added here. Could you explain? LGTM otherwise.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/timestamp_cache.go, line 282 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503#-KmXpJGCAvpDbZwnOz2Z:-KmXpJGCAvpDbZwnOz2_:b62bgkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40be245bc463226afb2ed138da664cf1bf322e0/pkg/storage/timestamp_cache.go#L282)):*
> ```Go
> 			// Some of the cases below adjust cv and key in-place (in a manner that
> 			// maintains the IntervalCache invariants). These in-place modifications
> 			// due change the size of the entry. To capture all of these
> ```

s/due/do? or remove?

---

*[pkg/storage/timestamp_cache.go, line 312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503#-KmXmoWd2zk7hRoZI5y_:-KmXpUEzDmB9sKZUqWm_:b1lfy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40be245bc463226afb2ed138da664cf1bf322e0/pkg/storage/timestamp_cache.go#L312)):*
Your comment here makes a lot more sense to me than the inline comment. How about

> // DelEntry adjusted tc.bytes, don't do it again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503#-:-KmXpsRii4AW1A9EXFff:b-xvarbs)*

**Comment by petermattis** [comment]
The tweaks to `TestTimestampCacheLayeredIntervals` allowed the existing assertions when `TimestampCache.Clear` was invoked to catch the problem. That test is already trying to exercise the various code paths in `TimestampCache.add`.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/timestamp_cache.go, line 282 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503#-KmXpJGCAvpDbZwnOz2Z:-KmXrVMcBcaq32M91gBX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40be245bc463226afb2ed138da664cf1bf322e0/pkg/storage/timestamp_cache.go#L282)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

s/due/do? or remove?
</blockquote></details>

Done.

---

*[pkg/storage/timestamp_cache.go, line 312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503#-KmXmoWd2zk7hRoZI5y_:-KmXritfsS25cLRBqluz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40be245bc463226afb2ed138da664cf1bf322e0/pkg/storage/timestamp_cache.go#L312)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Your comment here makes a lot more sense to me than the inline comment. How about

> // DelEntry adjusted tc.bytes, don't do it again.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503#-:-KmXrkYHKONuexWWcR9h:b-533mzp)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/timestamp_cache.go, line 311 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503#-KmXuEa5pePvDRhAWXpf:-KmXuEa5pePvDRhAWXpg:b-z3fl30) ([raw file](https://github.com/cockroachdb/cockroach/blob/c208d83634db92f3ad9b8bae83674414bf089e2a/pkg/storage/timestamp_cache.go#L311)):*
> ```Go
> 					// Old:
> 					tcache.DelEntry(entry)
> 					continue // DelEntry adjusted tc.bytes, don't do it again.
> ```

miniscule nit that I set myself up for: no dot at the end for inline comments. Don't think it's worth eating CI for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16503)*

**Comment by petermattis** [comment]
This should go into 1.0.3.

**Pull request merged**
