### PR TITLE
bulk: Add metrics to bulk mem monitor for better visualisation

### PR DESCRIPTION
**Pull request by adityamaru27**
This change reworks how we want to use memory monitors for bulk
operations.

We have a single `bulkMonitor` which is a child of the
root sql memory monitor. Each bulk operation will further create a
child of the `bulkMonitor` which will be used to control memory
growth of the bulk adder.
A new class of metrics has been hooked up to the `bulkMonitor`
which allows for visualization of total memory usage in the
admin UI.

Release note: None

### CODE REVIEW

**Comment by adityamaru27** [comment]
Screen Shot 2019-08-19 at 5 42 20 PM

A quick test on TPCC-100 allowing cockroach to use 50% of my total memory (8 GiB), shows that the bulk memory monitor reports a max of 2.3GiB was reserved at one point by the 9 concurrent imports. This is well below the max an import could grow to (128*9 + 512*9 ~ 5.5GiB) but I would assume the statements completed well before they needed such memory demands. It is promising to see that all the bytes are released once the import has completed.

I'll run some more tests on larger imports and post my findings.

**Comment by dt** [comment]
I don't really know much about the monitors or their API so I'll defer review to someone who does. is that @knz?

**Comment by adityamaru27** [comment]
@knz I was also a little confused about why we record the logarithmic value of the high watermark of bytes allocated in a monitor. (https://github.com/cockroachdb/cockroach/blob/master/pkg/util/mon/bytes_usage.go#L404)

I consulted your comment but can you give me some intuition as to why we would not record the actual value instead?

**Review by knz — APPROVED** [review]
> I consulted your comment but can you give me some intuition as to why we would not record the actual value instead?

Back then the plotting facility in the web UI was not able to plot with a log scale on the y-axis. Given that the sizes of memory allocations follow a power law distribution, the visual result would be a few spikes at a dozen megabyte+ sizes, with the bulk of allocations (<1000 bytes) completely squashed along the x axis.


your implementation LGTM

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39754#-:-Lmi-n0HD-wAsdjfTCJ9:bh06ljz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27)

___
*[pkg/util/mon/bytes_usage.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39754#-Lmi-KoBChvsEA7R2QuW:-Lmi-KoBChvsEA7R2QuX:benkxaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cfb2a328f2cde928a5f919be4a68937cb81d4b3/pkg/util/mon/bytes_usage.go#L218)):*
> ```Go
> 	noteworthyUsageBytes int64
> 
> 	curBytesCount *metric.Gauge
> ```

These two fields are missing a comment. Please explain what they are and what is their purpose; otherwise the review is difficult.

**Comment by knz** [comment]
> Back then the plotting facility in the web UI was not able to plot

Note: I do not know whether this has changed. It may still well be the case.

**Review by adityamaru27 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39754)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/mon/bytes_usage.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39754#-Lmi-KoBChvsEA7R2QuW:-LmjV0SD0LJkgVdvJ8Ud:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cfb2a328f2cde928a5f919be4a68937cb81d4b3/pkg/util/mon/bytes_usage.go#L218)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

These two fields are missing a comment. Please explain what they are and what is their purpose; otherwise the review is difficult.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39754)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by adityamaru27** [comment]
TFTR
bors r+

**Pull request merged**
