### PR TITLE
mixedversion: introduce longer delays in concurrent steps

### PR DESCRIPTION
**Pull request by renatolabs**
When a sequence of steps runs concurrently in a mixedversion test, the
framework adds a random, artificial delay between each step to explore
different interleavings of the steps. However, the duration of these
random delays was fairly short: prior to this commit, the delay would
be no longer than 500ms.

Since a lot (maybe most) mixedversion tests running every night have
fairly long running mixed-version hooks (in the order of minutes), it
makes sense to introduce longer delays between steps, to simulate
things happening in the middle of a certain step, as opposed to its
first moments.

In this commit, we update the range of possible delays from 0 (no
delay) to 3 minutes.

**mixedversion: include version running on gateway node in SQL methods**
A small debugging improvement: we are able to quickly see what version
is running on the gateway node without having to check the test plan
or the header of the current log file.

**mixedversion: simplify step that waits for migrations to finish**
This changes the wording on that step's description to mention that we
are waiting for a specific cluster version. This makes it a little
less tied to the actual implementation of the step, and highlights the
actual cluster version the cluster should be at by the time the step
ends.

### CODE REVIEW

**Comment by renatolabs** [comment]
Just grouping together a few small improvements I had in a note. Each commit is a fairly small change.

**Comment by renatolabs** [comment]
[Mixed-version tests](https://teamcity.cockroachdb.com/viewLog.html?buildId=13743405&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv&branch_Cockroach_Nightlies=118333) pass on this branch.

**Review by DarrylWong — APPROVED** [review]
LGTM besides one small fix

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118333#-:-NpQGPq15j9CgdDCTUxA:b-hub7l8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 1058 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118333#-NpQEUTG3M63vCMCpJvC:-NpQEUTG3M63vCMCpJvD:b-3qi74b) ([raw file](https://github.com/cockroachdb/cockroach/blob/adcee3cf432278adbc0633e530e926f051207d43/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L1058)):*
> ```Go
> // don't want to spend too much time waiting in that context.
> func pickRandomDelay(rng *rand.Rand, isLocal bool, durations []time.Duration) time.Duration {
> 	dur := possibleDelays[rng.Intn(len(possibleDelays))]
> ```

I think you meant to use `durations` instead of `possibleDelays`. Looks like `randomConcurrencyDelay` passes in `possibleDelays` anyway.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118333)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 1058 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118333#-NpQEUTG3M63vCMCpJvC:-NpQkmHUA8k5serhThQI:bps0g5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/adcee3cf432278adbc0633e530e926f051207d43/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L1058)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

I think you meant to use `durations` instead of `possibleDelays`. Looks like `randomConcurrencyDelay` passes in `possibleDelays` anyway.
</blockquote></details>

:scream: 

For a minute, I was wondering: how did the tests not fail?! But then I realized that, in the mess of rebasing and fixing conflicts, I forgot to update this part of the code to call `pickRandomDelay`, which was the main point of creating this function to begin with (to reuse this "divide by 10 in local runs" logic):

https://github.com/cockroachdb/cockroach/blob/815e757e8d39f9e56cd98ebb6054b4e4114abb00/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L386-L393

Great catch, thank you!

**Comment by renatolabs** [comment]
TFTR!

bors r=DarrylWong

**Comment by renatolabs** [comment]
bors retry

**Pull request merged**
