### PR TITLE
update lodash

### PR DESCRIPTION
**Pull request by maxlang**
Update to lodash 4.

Mostly a convenience since looking at the docs was getting annoying.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4618)

### CODE REVIEW

**Comment by tamird** [comment]
why did this require changing it from bower to npm?

**Comment by maxlang** [comment]
lodash 4 dropped support for bower

**Comment by tamird** [comment]
(1) citation needed, preferably included in the commit message
(2) remove lodash from bower.json

**Comment by mrtracy** [comment]
LGTM

**Pull request merged**
