### PR TITLE
sql: move ComponentStats to execinfrapb

### PR DESCRIPTION
**Pull request by RaduBerinde**
This proto belongs in execinfrapb. For example, we should be able to
store ProcessorID/StreamIDs in it if necessary.

The differences in the proto file are due to proto2/proto3. The
DistSQL version doesn't need bumping, the messages are different
(because of the package change) and unknown messages will just be
ignored.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
I assume that the logic tests will need to be updated, but the change :lgtm:

> Reviewed 35 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56842#-:-MMOnJdu3c1Aq1Ka3eUA:b3sk3us)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by RaduBerinde — COMMENTED** [review]
TFTR!  Why would logic tests need updating? Functionally nothing should change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56842#-:-MMOqwBH4lIk4Zpgwlzd:b-lrpmb1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
I thought that encoding would change because of proto3 and proto2 change 🤷

**Pull request merged**
