### PR TITLE
distsql: add stats collection to sorterBase

### PR DESCRIPTION
**Pull request by asubiotto**
Addresses #25743

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/distsqlrun/sorter.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26899#-LFYToeZ06ulnSQcFcE_:-LFYToeZ06ulnSQcFcEa:b-p66lix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83653ad0046216e14bb42434b3f0014738d9a08c/pkg/sql/distsqlrun/sorter.go#L41)):*
> ```Go
> 	count int64
> 
> 	diskMonitor *mon.BytesMonitor
> ```

I would put a comment here saying that this isn't always set, to prevent confusion.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26899#-:-LFYTt7K2R710WV-gTnx:bnfp4nl)*

**Comment by asubiotto** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/sorter.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26899#-LFYToeZ06ulnSQcFcE_:-LFYUlLC-TiAB7-BcLfr:bau1hwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/83653ad0046216e14bb42434b3f0014738d9a08c/pkg/sql/distsqlrun/sorter.go#L41)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would put a comment here saying that this isn't always set, to prevent confusion.
</blockquote></details>

It is always set, the comment on outputStatsToTrace was stale so updated that. Strategies apart from sortAll will not use disk yet but I thought it would be good to already give them a `diskMonitor` in preparation for my change to make the strategies fall back to disk.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26899)*

**Comment by jordanlewis** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/distsqlrun/sorter.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26899#-LFYToeZ06ulnSQcFcE_:-LFYXsbKEZe_2ExvLJmg:b7cpf5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/83653ad0046216e14bb42434b3f0014738d9a08c/pkg/sql/distsqlrun/sorter.go#L41)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It is always set, the comment on outputStatsToTrace was stale so updated that. Strategies apart from sortAll will not use disk yet but I thought it would be good to already give them a `diskMonitor` in preparation for my change to make the strategies fall back to disk.
</blockquote></details>

Oh yeah, sorry I thought this was part of processorbase.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26899)*

**Pull request merged**
