### PR TITLE
sql: udf logic tests not to skip dropping databases

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Now that we support drop functions in legacy schema changer
and declarative schema changer falls back to legacy when seeing
any function descriptor, we can move udf logic tests back
to normal configs.

Release note: None.
Release justification: test only change.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: :tada: 

> Reviewed 9 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86278#-:-N9dfnoe-gKO-nT_bRUl:by6fmpn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/opt/exec/execbuilder/tests/fakedist/BUILD.bazel` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86278#-N9dfwa1C8bCmVy2Z2EK:-N9dfwa1C8bCmVy2Z2EL:b7ydod7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b755c145bfa75fa8a52627f0234c1a6cacf8dfe8/pkg/sql/opt/exec/execbuilder/tests/fakedist/BUILD.bazel#L12)):*
> ```Starlark
>         "//pkg/sql/opt/exec/execbuilder:testdata",  # keep
>     ],
>     shard_count = 2,
> ```

`dev generate` generated this change. My guess is that we were at the edge of some threshold on the number of tests.

**Comment by ajwerner** [comment]
The shards are min(num_tests_in_config, 16)

**Comment by chengxiong-ruan** [comment]
> The shards are min(num_tests_in_config, 16)

heh. I made a mistake, I should have just used `local` config for executor tests instead of removing the config from the test file which trigger all these changes :(

**Comment by chengxiong-ruan** [comment]
udf expressions are built into new `RoutineExpr`s. For now we need to skip DistSQL for any `RoutineExpr` before we plumb a function resolver into DistSQL or maybe [this todo](https://github.com/cockroachdb/cockroach/blob/f0c8bfd29cd747a64e645bf26067efb26207097c/pkg/sql/sem/tree/function_definition.go#L90-L90) can be done.

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
