### PR TITLE
workload: add workload to trigger insight scenarios

### LINKED ISSUE #90977: Add workload to trigger insights scenarios
To make it easier to demo and test a new workload should be added that triggers the insights to capture the queries. 

Jira issue: CRDB-21056

### PR DESCRIPTION
**Pull request by j82w**
This is adding a new workload that is designed to
run several bad queries that will be detected by the
insights. This workload is not public.

The list of bad queries:
1. Order by on a non-indexed column
2. Transaction updates multiple rows with a delay
3. Join on a non-indexed column
4. Contention in update by blocking a txn in the app

Release note: none

closes #90977

Release note: none

### CODE REVIEW

**Review by matthewtodd — COMMENTED** [review]
Thanks so much for doing this, Jake, I love it! I just had a couple of questions to help me understand the code better.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90048#-:-NEb34NA7Ue_V_ipaDh2:bqms5si)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/workload/insights/insights.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90048#-NEb-0x46tvVx4RupB3I:-NEb-0x59_1xxa0OL3ZA:bljk5jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c5f89ca17367acff4d433e90c7644857a767d0f/pkg/workload/insights/insights.go#L1)):*
> ```Go
> // Copyright 2017 The Cockroach Authors.
> ```

nit: 2022 here & in the other new files
___
*[`pkg/workload/insights/insights.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90048#-NEb-4403ii0ZkBke37p:-NEb-4403ii0ZkBke37q:b-admiji) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c5f89ca17367acff4d433e90c7644857a767d0f/pkg/workload/insights/insights.go#L64)):*
> ```Go
> var insightsMeta = workload.Meta{
> 	Name:         `insights`,
> 	Description:  `This workload executes queries that will be detected by cockroach db insights`,
> ```

nit: there's probably some official spelling / casing of cockroach db, maybe "CockroachDB?" Or maybe drop the "cockroach db" altogether?
___
*[`pkg/workload/insights/insights.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90048#-NEb-mJV0OSZlte9VNYR:-NEb-mJV0OSZlte9VNYS:bewqvsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c5f89ca17367acff4d433e90c7644857a767d0f/pkg/workload/insights/insights.go#L221)):*
> ```Go
> 		rng := rand.New(rand.NewSource(b.seed))
> 		hists := reg.GetHandle()
> 		workerFn := func(ctx context.Context) error {
> ```

nit: I think it would help me to delineate (either with comments or maybe extracted functions?) the work this worker's doing, and how it creates the conditions we're trying to detect with insights.
___
*[`pkg/workload/insights/insights.go` line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90048#-NEb-LdC5yTU6jYX3hRG:-NEb-LdD-rkgoQ0dvE2o:b-ocxdvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c5f89ca17367acff4d433e90c7644857a767d0f/pkg/workload/insights/insights.go#L237)):*
> ```Go
> 			from := rng.Intn(b.rows)
> 			to := rng.Intn(b.rows - 1)
> 			for from == to && b.rows != 1 {
> ```

nit: This logic took me a little while to parse, maybe comment it once you're wrapping up the coding?
___
*[`pkg/workload/insights/insights.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90048#-NEb0st82ohFpkpOb6gQ:-NEb0st82ohFpkpOb6gR:biw6j0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c5f89ca17367acff4d433e90c7644857a767d0f/pkg/workload/insights/insights.go#L284)):*
> ```Go
> }
> 
> func randStringLetters(rng rand.Source, buf []byte) {
> ```

nit: Can you say more about what you're going for with this function? I'm wondering if something simpler would suffice.

**Comment by j82w** [comment]
*[`pkg/workload/insights/insights.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90048#-NEb0st82ohFpkpOb6gQ:-NEgGmKP9tlXPYFPn6-W:b767gv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c5f89ca17367acff4d433e90c7644857a767d0f/pkg/workload/insights/insights.go#L284)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Can you say more about what you're going for with this function? I'm wondering if something simpler would suffice.
</blockquote></details>

I'll work on cleaning this up in the next iteration. This will likely get removed. I was thinking there might be a scenario for doing a like operation.

**Comment by j82w** [comment]
*[`pkg/workload/insights/insights.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90048#-NEb-mJV0OSZlte9VNYR:-NEgHaIC9xmWfIz_SZSx:b-jtdzd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c5f89ca17367acff4d433e90c7644857a767d0f/pkg/workload/insights/insights.go#L221)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: I think it would help me to delineate (either with comments or maybe extracted functions?) the work this worker's doing, and how it creates the conditions we're trying to detect with insights.
</blockquote></details>

I agree, and will separate it out to new functions for each scenario.

**Review by matthewtodd — APPROVED** [review]
Nice! All I see is needing to update the 2017 copyright dates.

**Comment by j82w** [comment]
blathers backport 22.2

**Pull request merged**
