### PR TITLE
sql/sem: fix negative floats + formatting of numeric datums

### LINKED ISSUE #28078: sql: formatters for negative decimals and floats are wrong
Like `DInt`, `DDecimal` and `DFloat` need to surround their output with parens if `fmtDisambiguateDatumTypes`  is active, since the `-` binds more tightly than the `:::`.

### PR DESCRIPTION
**Pull request by knz**
Fixes #28078.

Prior to this patch, there was confusion about when to include
disambiguating parentheses and type annotations. This patch clarifies
it (and fixes some bugs) as follows:

- `FmtParsableNumerics` ensures that parentheses are present if the
  value is negative or if `fmtDisambiguateDatumTypes` is set.
- the type annotation is only added if and only if
  `fmtDisambiguateDatumTypes` is set.
- the behavior is made consistent across DECIMAL, FLOAT and INT.

In addition, the prior behavior had a bug in that it didn't preserve
negative zeros in floats properly. The corresponding logic
test (`logic_test/testdata/zero`) was containing an incorrect test and
thus was failing to detect this error.

After correcting this error, it appeared that the special handling of
unary negation that I introduced yesterday (#28520 /
93a8fe3) was incorrect too, because
it relied on the conversion from `constant.Value` to `float` to
preserve the sign bit. Unfortunately, `constant.Value` is
incorrect/unsuitable because it improperly normalizes `-0` to `+0`
even for floats, which may be swell for Go but incorrect in SQL. This
patch fixes it by processing the sign bit at the end of the conversion
from `constant.Value` to `Datum` instead of early.

Release note (bug fix): CockroachDB now handles negative FLOAT zeros
properly in more cases.

### CODE REVIEW

**Review by jordanlewis — CHANGES_REQUESTED** [review]
Very nice work! This cleans up the wart of having to write the type annotation within the type's format method - I didn't like that at all.

:lgtm: 

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28569#-:-LJt64lB0VpoPa6CIkql:b-2qvodw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/datum.go, line 665 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28569#-LJt5yV7ALxXIU4tkIoA:-LJt5gL0CrhtdlMgC9Tj:bmtspfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4658b45b60e3afe61e39c99d4fb315b1012e9b4/pkg/sql/sem/tree/datum.go#L665)):*
> ```Go
> 
> // AmbiguousFormat implements the Datum interface.
> func (*DFloat) AmbiguousFormat() bool { return true }
> ```

yay, as it should be!

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28569)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/datum.go, line 665 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28569#-LJt5yV7ALxXIU4tkIoA:-LJt6CF3BGho2LSEkro8:b-dkyqzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4658b45b60e3afe61e39c99d4fb315b1012e9b4/pkg/sql/sem/tree/datum.go#L665)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

yay, as it should be!
</blockquote></details>

Oops I didn't mean to make this "blocking"

**Comment by knz** [comment]
thanks

bors r+

**Comment by knz** [comment]
resetting the PR title

bors r-

**Comment by knz** [comment]
reset the PR title

bors r+

**Pull request merged**
