### PR TITLE
sql/cli: restore the current database after a reconnect

### PR DESCRIPTION
**Pull request by knz**
Before:
```
root@26257/> set database=t;

<server restart happens here>

root@26257/t> select * from kv;
connection lost; opening new connection and resetting session parameters...

root@26257/> select * from kv;
pq: table "kv" does not exist
```

After:
```
root@26257/> set database=t;

<server restart happens here>

root@26257/t> select * from kv;
connection lost; opening new connection: all session settings will be lost
root@26257/t> select * from kv;
...
(10 rows)
```

### CODE REVIEW

**Comment by jordanlewis** [comment]
Haven't reviewed, but 💯 on resetting the database upon reconnect - this bothers me every time!

**Comment by bdarnell** [comment]
Resetting the current database certainly solves a recurring annoyance, but it seems like a slippery slope. Despite what the log message says, we don't restore other session parameters, and people might expect those to be restored too. An alternative would be to encourage the use of the `-d` command-line parameter (which is shorter to type than `SET DATABASE=`) or the `COCKROACH_DATABASE` environment variable (and similarly introduce CLI flags for any other session-level settings).  I'm not going to insist on purity here though since I've been tripped up by this many times in the past.

**Comment by knz** [comment]
The word "resetting" is from a previous commit - it is/was intended to mean "resetting to defaults", not "reset to previously set value". I can see how my patch is now making this confusing ("if that is re-set to the previously known values, why aren't the other settings not also re-set?") I have added a patch to clarify the message.

**Comment by mjibson** [comment]
Everything except the node ID in prompt LGTM. I'm not sure what problem that solves.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cli/sql.go, line 447 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589#-Kn1MTZFbbUrHgw0vJib:-Kn1MTZGMh2ccP-Tx5-r:b-ldvi9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee5c18633b910cad3bc111885e833593d6b33544/pkg/cli/sql.go#L447)):*
> ```Go
> 	}
> 
> 	dbVal, hasVal := c.getServerValue("node ID",
> ```

This function is now called three times every time the prompt is displayed. Over a slow connection this can get pretty laggy. If we do decide to add this ID stuff, could we aggregate these three calls into one multi-query statement?

---

*[pkg/cli/sql_util.go, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589#-Kn0XEB_eFMhPqfFpX_i:-Kn0XEBc54fOOsERFlf1:baiujoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5121ed23fa39ed39c5b32ca1839975c382be3465/pkg/cli/sql_util.go#L125)):*
> ```Go
> 	}
> 	_, err := c.conn.Exec(query, args)
> 	if err == driver.ErrBadConn {
> ```

Could we add a test for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589#-:-Kn1M8F-J2RX_Ubu__AE:b-yo6a8j)*

**Comment by andreimatei** [comment]
As to what problem that solves - no earlier than today @mberhault asked me how to figure out the node the cli is connected to, after going through a balancer.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589#-:-Kn1d8vxrEigXNgA7asP:bkv0t3p)*

**Comment by mberhault** [comment]
It's nice to be able to tell which node we're connected to, but I don't think the cli is the right place for this. It's rare enough to want this information, so on-demand would be better. Some sql statement to show the server info?

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589#-:-Kn1pzFaD99yHCZYmBVV:b-6l4eur)*

**Comment by mjibson** [comment]
The implementation here shows how to do that: `SELECT node_id FROM crdb_internal.node_build_info`

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589#-:-Kn2FsnPfzdJCIq5VVC1:b-e2is4g)*

**Comment by knz** [comment]
I am punting the commit that adds nodeID reporting to a separate PR:  #16615.

**Comment by knz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cli/sql.go, line 447 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589#-Kn1MTZFbbUrHgw0vJib:-Kn3mQDr2hM3omN0-mtK:bjk7nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee5c18633b910cad3bc111885e833593d6b33544/pkg/cli/sql.go#L447)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This function is now called three times every time the prompt is displayed. Over a slow connection this can get pretty laggy. If we do decide to add this ID stuff, could we aggregate these three calls into one multi-query statement?
</blockquote></details>

I moved the nodeID to a separate PR. The transaction status and the db name have to be done separately though, because it's invalid to request the db name if the current txn status is aborted or in "retry wait" mode.

---

*[pkg/cli/sql_util.go, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589#-Kn0XEB_eFMhPqfFpX_i:-Kn3mP7MNHFCLRYIjlb6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5121ed23fa39ed39c5b32ca1839975c382be3465/pkg/cli/sql_util.go#L125)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Could we add a test for this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cli/sql_util.go, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589#-Kn0XEB_eFMhPqfFpX_i:-KnB6f_g76TzmsJkcsRY:b-km5zjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5121ed23fa39ed39c5b32ca1839975c382be3465/pkg/cli/sql_util.go#L125)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That was much more work than I anticipated :/. Thanks for doing that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16589#-:-KnBGWOeXG-AcO1U5gmL:bnfp4nl)*

**Comment by knz** [comment]
:smile_cat: thank you!

**Pull request merged**
