### PR TITLE
sql: support APPLICATION_NAME variable

### LINKED ISSUE #10694: sql: support APPLICATION_NAME variable
Several SQL clients that support postgres [(including the popular SQL Workbench/J](http://www.sql-workbench.net/)) try to set the `APPLICATION_NAME` variable when they start up to improve query logging on the server. Cockroach does not recognize the existence of this variable, leading these clients to fail to connect.

It would be nice if most database clients that work with postgres also work with Cockroach. We should add support for `APPLICATION_NAME`, even if it's practically a write-only variable that doesn't affect any internals.

### PR DESCRIPTION
**Pull request by yznming**
Fixes #10694.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10725)

### CODE REVIEW

**Comment by knz** [comment]
You need to add a test.

**Comment by yznming** [comment]
@knz done

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10725#-:-KWhukL4CW1fxaCP9iBM:b-bxjwka)*

**Comment by knz** [comment]
Please accept my apologies for not being specific earlier.

1) to test this you can simply add a new pair of lines in the file `pkg/sql/testdata/set`; no need to create a new go source file:

```
statement ok
SET APPLICATION_NAME = 'hello'
```

2) I notice that a similar test is missing for `EXTRA_FLOAT_DIGITS`. It would be very nice if you could add it there too.

**Comment by yznming** [comment]
@knz done

**Comment by knz** [comment]
LGTM 

Very good, thanks for your contribution!

You can merge the PR now. (If you don't have permission I can do it for you)

**Comment by yznming** [comment]
@knz I don't have the permission. pls help to merge the code, thx a lot :)

**Comment by knz** [comment]
For docs: perhaps mention that `application_name` and `extra_float_digits` are recognized as valid arguments for `SET` for compatibility with pg but that they are currently ignored (they have no effect).

**Pull request merged**
