### PR TITLE
sql/schemachanger: support the MVCC-compliant index backfill protocol 

### PR DESCRIPTION
**Pull request by ajwerner**
This change reworks the logic for schema changes which need to create new
indexes such that they use the MVCC-compliant offline backfill and merge
protocol.

Release note: None

### CODE REVIEW

**Review by postamar — APPROVED** [review]
:lgtm: modulo very minor comments.

Nicely done! Being somewhat of a pessimist I was expecting a more messy diff, to be honest.

> Reviewed 28 of 28 files at r1, 15 of 15 files at r2, 55 of 56 files at r3, 3 of 69 files at r4, 13 of 15 files at r5, 56 of 56 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-:-N3PRcHy-uh8l2qGgvns:br4ejdr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @rhu713, and @stevendanna)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3P8yyK82gLvTigLb_V):*
Good call. I was becoming a bit worried about the maintainability of this code. In hindsight, the presence of tests in this boilerplate package should have been a giveaway.
___
*[`pkg/server/server_sql.go` line 908 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3P77eRE8ce54GlDnuV:-N3P77eS5R1-ziTmoN2Q:bz02y9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8df84fcf38743abdd12126569086767a6745a8e/pkg/server/server_sql.go#L908)):*
> ```Go
> 	distSQLServer.ServerConfig.SessionBoundInternalExecutorFactory = ieFactory
> 	jobRegistry.SetSessionBoundInternalExecutorFactory(ieFactory)
> 	execCfg.IndexBackfiller = sql.NewIndexBackfiller(execCfg)
> ```

This begs the question: do we want to give this some similarly contrived name like `NewIndexBackfillerBackfillPlanner`? More consistent, but this reeks of `AbstractAbstractBaseClassFactoryVisitor`java-style verbosity.

I've struggled with naming these things, if you can't tell.
___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 270 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PGHHR8BY3bB6MnE_P:-N3PGHHR8BY3bB6MnE_Q:b-ttbqi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scbuild/builder_state.go#L270)):*
> ```Go
> 	for i, colID := range index.KeyColumnIDs {
> 		scpb.ForEachColumnName(b, func(_ scpb.Status, _ scpb.TargetStatus, cn *scpb.ColumnName) {
> 			if cn.TableID != index.TableID || cn.ColumnID != colID {
> ```

Oh whoops.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go` line 199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PMNJjDxfw9nQUS91-:-N3PMNJkBZNcQjYJOvUA:bcqylfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L199)):*
> ```Go
> 	index.SourceIndexID = source.IndexID
> 	index.IndexID = nextRelationIndexID(b, relation)
> 	index.TemporaryIndexID = index.IndexID + 1
> ```

uber nit: why not call `nextRelationIndexID` again here and use `index.TemporaryIndexID` as the source of truth for the temp index ID? Seems less brittle somehow.
___
*[`pkg/sql/schemachanger/scexec/backfiller/tracker.go` line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PAgdlEJNyp4psH1-O:-N3PAgdlEJNyp4psH1-P:blo6bpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d9893adefa808d8836b5abdca7cdb48c5667ac3/pkg/sql/schemachanger/scexec/backfiller/tracker.go#L131)):*
> ```Go
> 			})
> 		},
> 	}
> ```

This is fine but it makes me wish for proper dependency injection at the jobs level. 
___
*[`pkg/sql/schemachanger/scexec/backfiller/tracker.go` line 177 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PFsST08H0K7p5KEOW:-N3PFsST08H0K7p5KEOX:b87p8fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scexec/backfiller/tracker.go#L177)):*
> ```Go
> 		return scexec.MergeProgress{
> 			Merge:          m,
> 			CompletedSpans: make([][]roachpb.Span, len(m.SourceIndexIDs)),
> ```

Why is this?
___
*[`pkg/sql/schemachanger/scop/mutation.go` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PFOPEC1slkzouIm8k:-N3PFOPEC1slkzouIm8l:b-ug0knz) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scop/mutation.go#L52)):*
> ```Go
> 	IsSecondaryIndex   bool
> 	IsDeletePreserving bool
> }
> ```

Should we rename this op to `MakeAddedTempIndexDeleteOnly` and remove the `IsDeletePreserving` field which is known to always be true? Or do we have a use-case for adding a regular index but not backfilling? I'm suspecting the latter but still, it feels worth asking.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_partitioning.go` line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PE9at6BK7pO4tq2Hi:-N3PE9at6BK7pO4tq2Hj:bfqg392) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_partitioning.go#L28)):*
> ```Go
> 	//
> 	// Note that for correctness, we'll apply the partitioning in the same stage
> 	// as the index entering DELETE_ONLY.
> ```

Why is that? It's worth adding more commentary, I think.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_partitioning.go` line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PGkeJ7Bt_jAA0JaKQ:-N3PGkeJ7Bt_jAA0JaKR:b3y5cb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ebc6c8e2f4f78434741c791b19b74d2250ba294/pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_partitioning.go#L39)):*
> ```Go
> 				emit(func(this *scpb.IndexPartitioning) scop.Op {
> 					return notImplemented(this)
> 				}),
> ```

Any chance we can leave this `notImplemented` call in? From experience I've found these to be more robust than TODO messages when it comes to tracking code gaps to fill.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_secondary_index.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PK1XkC6RORrjGPE-i:-N3PK1XkC6RORrjGPE-j:b-1a68vh) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scplan/internal/opgen/opgen_secondary_index.go#L71)):*
> ```Go
> 				emit(func(this *scpb.SecondaryIndex) scop.Op {
> 					// TODO(ajwerner): Should this say something other than
> 					// ValidateUniqueIndex for a non-unique index?
> ```

It seems this is readily addressable: `this` should know if it's unique; if it isn't `return nil` instead. I'm guessing that this code simply predates the optional-op `emit` implementation.

Perhaps this belongs in a separate PR idk.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/register.go` line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PKiHHCrYRzVR3vPqv:-N3PKiHHCrYRzVR3vPqw:b-y9akui) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scplan/internal/opgen/register.go#L72)):*
> ```Go
> 	}
> 	return populateTransientAbsent(toAbsent, transient)
> }
> ```

Nicely done. I like it.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go` line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PL8wQ-Or20gYcjZYI:-N3PL8wQ-Or20gYcjZYJ:bm958pc) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go#L77)):*
> ```Go
> 
> 	(&depRuleSpec{
> 		ruleName:         "index partitioning is applied in the same stage temporary index comes to exist",
> ```

nit: `partitioning set right after temp index existence`?

There's a premium on keeping these rule names short, especially in the graphviz rendering.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go` line 420 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PLadI-nAFcNBPh3s-:-N3PLadI-nAFcNBPh3s0:b6xapii) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go#L420)):*
> ```Go
> 		return columnInList(from.ColumnID, idx.KeyColumnIDs) ||
> 			columnInList(from.ColumnID, idx.StoringColumnIDs) ||
> 			columnInList(from.ColumnID, idx.KeySuffixColumnIDs)
> ```

Much nicer, thanks.
___
*[`pkg/ccl/schemachangerccl/testdata/end_to_end/create_index` line 585 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3POjfa1QdwKgFtKk3G:-N3POjfa1QdwKgFtKk3H:b-v60enm) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/ccl/schemachangerccl/testdata/end_to_end/create_index#L585)):*
> ```
>   +  version: "8"
> write *eventpb.FinishSchemaChange to event log for descriptor 104
> create job #2 (non-cancelable: true): "GC for "
> ```

Seems like we _still_ don't have the GC job descriptions right, ugh.
___
*[`pkg/ccl/schemachangerccl/testdata/end_to_end/create_index` line 590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3POsCb2ihsUGHLTR_k:-N3POsCb2ihsUGHLTR_l:b-zapoaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/ccl/schemachangerccl/testdata/end_to_end/create_index#L590)):*
> ```
> commit transaction #11
> notified job registry to adopt jobs: [2]
> # end PostCommitPhase
> ```

I actually combed through this and it all seems correct to me.
___
*[`pkg/sql/logictest/testdata/logic_test/add_geometry_column` line 21 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PP8ez7QLoIp0gkVB4:-N3PP8ez7QLoIp0gkVB5:bm8uthp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cac7c072dd35c773e7b96b49bc0bc6da3641547e/pkg/sql/logictest/testdata/logic_test/add_geometry_column#L21)):*
> ```
>    geom2 GEOMETRY(POINT,4326) NULL,
>    CONSTRAINT my_spatial_table_pkey PRIMARY KEY (k ASC)
> )
> ```

What's up with this change?
___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 885 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PMxeA1WBlK9901-82:-N3PMxeA1WBlK9901-83:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/schemachanger_test.go#L885)):*
> ```Go
> 	require.NoError(t, err)
> 	val.SetTagAndData(wrapper.Value)
> 	require.Equal(t, "/TUPLE/2:2:Int/100", val.PrettyPrint())
> ```

Nice!

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81444)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @postamar, @rhu713, and @stevendanna)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3P8yyK82gLvTigLb_V):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Good call. I was becoming a bit worried about the maintainability of this code. In hindsight, the presence of tests in this boilerplate package should have been a giveaway.
</blockquote></details>

Done.
___
*[`pkg/server/server_sql.go` line 908 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3P77eRE8ce54GlDnuV:-N3QVK8z-XanOXCuzXy1:b-svt3xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8df84fcf38743abdd12126569086767a6745a8e/pkg/server/server_sql.go#L908)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This begs the question: do we want to give this some similarly contrived name like `NewIndexBackfillerBackfillPlanner`? More consistent, but this reeks of `AbstractAbstractBaseClassFactoryVisitor`java-style verbosity.

I've struggled with naming these things, if you can't tell.
</blockquote></details>

I'm inclined to leave it for now. 
___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 270 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PGHHR8BY3bB6MnE_P:-N3QVJCp1oGybO9IbYZO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scbuild/builder_state.go#L270)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Oh whoops.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go` line 199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PMNJjDxfw9nQUS91-:-N3Po3u62Y5eIU5WBIau:b-4qgmql) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L199)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

uber nit: why not call `nextRelationIndexID` again here and use `index.TemporaryIndexID` as the source of truth for the temp index ID? Seems less brittle somehow.
</blockquote></details>

`nextRelationIndexID` doesn't increment anything. I'd have to add the index before I could compute the next one. It's a bit of a chicken-and-egg sort of problem. 
___
*[`pkg/sql/schemachanger/scexec/backfiller/tracker.go` line 177 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PFsST08H0K7p5KEOW:-N3QViNG-z7sxFzEFjec:bwupvhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scexec/backfiller/tracker.go#L177)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Why is this?
</blockquote></details>

It was panicking in MergeIndexes without it. I added commentary and a constructor as well as error checking around the place where the panic had occurred.
___
*[`pkg/sql/schemachanger/scop/mutation.go` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PFOPEC1slkzouIm8k:-N3QMR3n9JdQs5VZ3IE9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scop/mutation.go#L52)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Should we rename this op to `MakeAddedTempIndexDeleteOnly` and remove the `IsDeletePreserving` field which is known to always be true? Or do we have a use-case for adding a regular index but not backfilling? I'm suspecting the latter but still, it feels worth asking.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_partitioning.go` line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PE9at6BK7pO4tq2Hi:-N3QLYMS0dBTEFFJzpUi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_partitioning.go#L28)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Why is that? It's worth adding more commentary, I think.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_partitioning.go` line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PGkeJ7Bt_jAA0JaKQ:-N3QKqKsAW3UR7ZBH2Nz:bdxvers) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ebc6c8e2f4f78434741c791b19b74d2250ba294/pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_partitioning.go#L39)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Any chance we can leave this `notImplemented` call in? From experience I've found these to be more robust than TODO messages when it comes to tracking code gaps to fill.
</blockquote></details>

It causes problems when rolling back now that it's set in a revertible phase. We need to set the index partitioning early on, before the index backfill occurs so that zone configs can take effect. This is sort of wrong because we don't currently deal with setting the zone configs properly, but we will. I'd prefer leaving this and doing `ALTER INDEX ... PARTITION BY` sooner rather than later. 
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_secondary_index.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PK1XkC6RORrjGPE-i:-N3QKUYYEYfzU9WD-pnj:b-wzsntx) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scplan/internal/opgen/opgen_secondary_index.go#L71)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

It seems this is readily addressable: `this` should know if it's unique; if it isn't `return nil` instead. I'm guessing that this code simply predates the optional-op `emit` implementation.

Perhaps this belongs in a separate PR idk.
</blockquote></details>

Yeah, the naming is bad but the logic is actually right. We today and have forever validated even non-unique secondary indexes. I'm leaving this for later. 
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go` line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PL8wQ-Or20gYcjZYI:-N3QKRyJ5VhlkuMepiCF:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go#L77)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: `partitioning set right after temp index existence`?

There's a premium on keeping these rule names short, especially in the graphviz rendering.
</blockquote></details>

done.
___
*[`pkg/ccl/schemachangerccl/testdata/end_to_end/create_index` line 585 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3POjfa1QdwKgFtKk3G:-N3Qd6J_EUsEJP0VxXpF:bms5u8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/ccl/schemachangerccl/testdata/end_to_end/create_index#L585)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Seems like we _still_ don't have the GC job descriptions right, ugh.
</blockquote></details>

I'll fix this in a follow-up
___
*[`pkg/sql/logictest/testdata/logic_test/add_geometry_column` line 21 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PP8ez7QLoIp0gkVB4:-N3PisxUBBPZCTlzI8Ty:bj7stt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/cac7c072dd35c773e7b96b49bc0bc6da3641547e/pkg/sql/logictest/testdata/logic_test/add_geometry_column#L21)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

What's up with this change?
</blockquote></details>

I extracted this from some other test because that test was failing and this helped me debug it. Removed.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81444)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @postamar, @rhu713, and @stevendanna)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go` line 199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PMNJjDxfw9nQUS91-:-N3Ql7n1Dj9Yt_Pfa8Qd:b-y0qzbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go#L199)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`nextRelationIndexID` doesn't increment anything. I'd have to add the index before I could compute the next one. It's a bit of a chicken-and-egg sort of problem. 
</blockquote></details>

I added a defensive check that we guessed correctly.

**Review by postamar — COMMENTED** [review]
I have no more complaints.

> Reviewed 1 of 69 files at r7, 14 of 15 files at r8, 54 of 56 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-:-N3QnJZt6QT0jtLRpRPd:b-pl28qq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @postamar, @rhu713, and @stevendanna)

___
*[`pkg/sql/schemachanger/scop/mutation.go` line 46 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3Qm7-8-6KANW9Ku9Wx:-N3Qm7-8-6KANW9Ku9Wy:b-6m73fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/933daffe84d15f965735520168eecb1f5f56b8be/pkg/sql/schemachanger/scop/mutation.go#L46)):*
> ```Go
> 
> // MakeAddedTempIndexDeleteOnly adds a non-existent index to the
> // table in the DELETE_ONLY state.
> ```

nit: if the opportunity presents itself, consider updating the commentary also.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_partitioning.go` line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PE9at6BK7pO4tq2Hi:-N3QmFu80s8Se9wNvDGk:b-wsvasg) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_partitioning.go#L28)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks for the explanation!
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_secondary_index.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3PK1XkC6RORrjGPE-i:-N3QmMjJ2uFedlzO9_qT:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/defa4e4143049e3f7ee2d5094048a99764198fb2/pkg/sql/schemachanger/scplan/internal/opgen/opgen_secondary_index.go#L71)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yeah, the naming is bad but the logic is actually right. We today and have forever validated even non-unique secondary indexes. I'm leaving this for later. 
</blockquote></details>

:+1: 
___
*[`pkg/sql/schema_changer_test.go` line 3530 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/81444#-N3QnE2e6bdaZ9rp9CQ4:-N3QnE2e6bdaZ9rp9CQ5:b652cl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/933daffe84d15f965735520168eecb1f5f56b8be/pkg/sql/schema_changer_test.go#L3530)):*
> ```Go
> // This test in its current form is stale regarding its use of schema changes.
> // It makes low level assumptions about how the legacy schema changer works.
> // TODO(ajwerner): Rework this test for the declarative schema changer.
> ```

Relates to https://github.com/cockroachdb/cockroach/issues/78028 and https://github.com/cockroachdb/cockroach/issues/77150

**Comment by ajwerner** [comment]
I filed sql/schemachanger: proper job description for GC Job dropping temporary index #82169 for the gc job description

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
