### PR TITLE
colexec: add bytes read information to the vectorized stats

### PR DESCRIPTION
**Pull request by yuzefovich**
**colconv: move vec_to_datum conversion to a new separate package**

This commit extract `vec_to_datum.eg.go` file into a separate package
`colconv` in order to break dependency of `colfetcher` package on
`colexec` package.

Release justification: low risk, high benefit change.

Release note: None

**colexec: add bytes read information to the vectorized stats**

This commit adds the propagation of "bytes read" information from
`ColBatchScan` and `joinReader` to `EXPLAIN ANALYZE` diagram. This
required a little bit of plumbing.

Release justification: low-risk, high benefit change.

Release note (sql change): EXPLAIN ANALYZE diagrams now contain "bytes
read" information for table readers and lookup joins when the queries are
executed via the vectorized engine.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Note that I created `colconv` package anticipating `*colfetcher.ColBatchScan` assertion in `colexec` package, so I needed to break the import cycle, but later I decided to propagate the bytes read information in a slightly different manner (they could be other operators planned on top of ColBatchScan, so it was easier to explicitly pass it in `execplan.go`), yet I think that move is beneficial, so I decided to keep that commit.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 27 of 27 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53371#-:-MG2sf2OB9KIZarKBCnS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 631 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53371#-MG2sUIv12fQ8uqLSWHC:-MG2sUIv12fQ8uqLSWHD:b-3v6a0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d57a0aeb4126b6e38e7e07095e6b69d1014803/pkg/sql/colexec/colbuilder/execplan.go#L631)):*
> ```Go
> 			}
> 			result.Op, result.IsStreaming = scanOp, true
> 			result.IOReadingOp = scanOp
> ```

What's the story for lookup joins?

**Review by yuzefovich — COMMENTED** [review]
Please take another quick look since I added the support for joinReader core.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53371#-:-MG4M8pcC90fiqD1SWnJ:b-etg79j)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 631 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53371#-MG2sUIv12fQ8uqLSWHC:-MG4LuytEETpkhQWzNSt:b7afi1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d57a0aeb4126b6e38e7e07095e6b69d1014803/pkg/sql/colexec/colbuilder/execplan.go#L631)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What's the story for lookup joins?
</blockquote></details>

Good point, forgot about those, added the support for them. The diagrams now look quite nice [now](https://cockroachdb.github.io/distsqlplan/decode.html#eJyclu9u2zYXxr-_V3HA90PlglNI6q8FFJCzOJ03x-5sd2u3GYZiHXhaZEmlqC1GkMvaDezKBlmKK0-JWvsbeQ4f6pxfzsP4geSfYuKR4Yd348FoAoPJYPzxlyFoV6P5Yv7juAfz4Xj47QLyYqvFK7xXmIQYZjJaYw8uwNEZDOYQ_LlZ7TCQ8Q6uZ9MbiKMEI4VbClkgFfz83XA2BE3TslW5v8MdvIH4ad2DweQKtGx1K4MkhDfw6rJc_F8Yr3qH3DpNVBAlKMv8zfAKLqcfDul49akIEhWpHfxWMGasQavLZrqA12V5jTO94xrr6uJGaYcyez1CSZKGOAm2mBPvV8LJkpJMpmvM81SWoYf9gVF4TzxGSZRkhSrDS0rWqUTiPRAVqRiJRxbBbYwzDEKUF4xQEqIKonh_bfk9P5PRNpA7Qsk8C5Lcg28IJddRrFB6oPnmERrP8-aL2WjytmbgO00yn7OEkmmhPPA59U3qO4SS20Ctf8cc0kJlZYoLg1CiiixuBAUzCSWjKahoix4YtqMLV2zzUr9TmIPEIPRAuHATXZLlIyWVsu49V8EGiccf6dfz-T6NkhoPP8bz9Lfy41V2RygZp-ldkcEfaZRAmpTNNdsU1Df2zVpVvzL961DuvqtcBXF8aMzVuWnvG4uSEO-hcdxmrnuIN1WOpRuiErVoWm2Y9T0Hmq6jO9xowxTwQwdMcSZM8QLMz_PW4mlS324i5fyYY91QE4lpObppiBNBmo6tO4Z5NklLGDrn_RZKrrudLI1TWA42G4mbQKXywjhmWQ2eDFFiWI_hYPJxNZkuVpP347Hm89KAg5_ear4oV7Py-ZQe-OI104Xnedfj6WDh0kraAvCSLfEe14WK0qSmIJj1z9_5i82aZw6OeaILxbMutL9kwb7j6obLT5wcbuuMnz03gusus9oOZHbn2FhnkrROt6BB_VI1nYDP2dP_teZD92VLcp0x3ufOqWBtnfXd59GyNlrLdZpkuWvoQrQfN9fod6K1z3SkfYx2_v6mdt3Ba_zC0dnBa1_nM_6cy_pdJnNOqX-GeZYmOR7V_tLN7HFJCYYbrH5u5Gkh1_hOpuv9Z6rtdK_bB0LMVZXl1WaUVKmywKaYd4pFt1h0io1usdEpNrvFZqfY6hZbnWK7W2x3ip3_iJeP__s3AAD__2kCjzw=).

**Comment by yuzefovich** [comment]
I also added the info from wrapped `rowexec.tableReader`.

However, now it becomes a little more annoying to decide whether we want to display `IO time` or `execution time`. I added a simple heuristic according to which in the vectorized diagram we will be showing `IO time` only for `ColBatchScan`, but wrapped `joinReader` and `tableReader` will see `execution time` (I think `joinReader` is a lot more likely to be planned). Thoughts?

**Review by asubiotto — APPROVED** [review]
:lgtm: I agree that it's confusing to display `IO/execution` at the same time and I like what you did in `NewVectorizedStatsCollector`

> Reviewed 14 of 14 files at r3, 14 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53371#-:-MG7tAPV7ssdx5-jRv3w:b-dc0bt4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
