### PR TITLE
docs: add anchors to generated tables

### LINKED ISSUE #36733: docs: Add anchors to each setting's name in `settings.html` for direct linking
In the docs, we'd like to be able to link to specific settings, as discussed during the review on https://github.com/cockroachdb/docs/pull/4635

It can be done by manually adding anchors to the settings file copy in the docs repo.  However, that file is auto-generated in this repo and then copied over periodically, so making edits via the docs repo would lead to conflicts that would need to be manually tracked and resolved.

Therefore this feature request is to add anchor tags to each setting in `docs/generated/settings/settings.html` so they can be linked to directly in the documentation.  A solution (verified to work in the PR linked above) would be to add an anchor with the same name as the setting, e.g.

```html
<tr><td><a name="sql.stats.automatic_collection.min_stale_rows"></a><code>sql.stats.automatic_collection.min_stale_rows</code></td><td>integer</td><td><code>500</code></td><td>target minimum number of stale rows per table that will trigger a statistics refresh</td></tr>
```

### PR DESCRIPTION
**Pull request by arberiii**
This patch creates `<a name>` anchors to the tables generated for
built-in functions, settings etc. The goal is to facilitate
linking from other doc pages.

Fixes #36733

### CODE REVIEW

**Comment by arberiii** [comment]
I'm not sure why is failing, I made the change locally, ran the command make, then commit the changes.

**Comment by nvanbenschoten** [comment]
Thanks for the PR @arberiii! I think CI is failing because you never checked in the updates to generated files after you ran `make build`. For instance, CI expects to see an update to the `docs/generated/sql/window_functions.md` file.

@rmloveland I'll defer to you for sign off because you wrote https://github.com/cockroachdb/cockroach/issues/36733.

**Review by rmloveland — APPROVED** [review]
LGTM @arberiii once you get it building in CI using the steps Nathan described.

(I went and manually tested adding anchors in this way and it works well.  Super excited to have this change, thank you!)

**Comment by knz** [comment]
Thank you for your contribution!

bors r+

**Pull request merged**
