### PR TITLE
ui: e2e tests, improved cypress test for tsx, overview and db page

### PR DESCRIPTION
**Pull request by nanduu04**
Previously, only visual regression tests were written

Wrote cypress tests using the cypress-testing-library

[CRDB-2388](https://cockroachlabs.atlassian.net/browse/CRDB-2388?atlOrigin=eyJpIjoiOWIzNzY0ZjkzY2RhNGU3ZTgyZTUyOTY5MjE4ZmM5YmIiLCJwIjoiaiJ9)

Release note: None

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
Great start!

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-:-MXsKtZV2tc8pcDI0QAC:b-8oelpl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nanduu04)

___
*[pkg/ui/cypress/integration/databases/databases.visual.spec.ts, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsJTcgEBtyi7YRQb0r:-MXsJTcgEBtyi7YRQb0s:b1e27yh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/databases/databases.visual.spec.ts#L16)):*
> ```XML
>     cy.findAllByText("Databases").should("exist");
>     cy.findAllByText("defaultdb").should("exist");
>     cy.findAllByText("postgres").should("exist");
> ```

Seems odd to check for the `postgres` database in a CRDB test :smile:
___
*[pkg/ui/cypress/integration/databases/databases.visual.spec.ts, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsJkak7QCqG3hbbnbd:-MXsJkak7QCqG3hbbnbe:bqlz9d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/databases/databases.visual.spec.ts#L23)):*
> ```XML
>   it("renders the view for databases/tables view", () => {
>     cy.visit("#/databases/tables");
>     cy.exec('cockroach sql --insecure --execute="create table test (id int)";');
> ```

I recommend using `create table if not exists` so that this test can be run multiple times on the same DB, or execute a `drop` operation at the end of the test.
___
*[pkg/ui/cypress/integration/databases/databases.visual.spec.ts, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsK3Wy61KRsgOyWHeu:-MXsK3Wy61KRsgOyWHev:b-w2283c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/databases/databases.visual.spec.ts#L34)):*
> ```XML
>     cy.findAllByText("public.test").should("exist");
>     cy.findAllByText("public.test1").should("exist");
>     cy.findAllByText("public.test2").should("exist");
> ```

Can you add a test for loading table stats as well? This is the button you can click to see detailed statistics on individual db tables. It loads data asynchronously. 
___
*[pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsKH0Y4auqN7o-Zq9u:-MXsKH0Y4auqN7o-Zq9v:b-k87a8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts#L18)):*
> ```XML
> });
> 
> describe("Transactions - Check check whether the transactions have been exectuted properly", () => {
> ```

nit: The naming on this test should be more specific. We're testing that transaction *statistics* show up properly, not that the transaction executes.
sp: executed
___
*[pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsKWZOEesEfht7cVsl:-MXsKWZOEesEfht7cVsm:blptu7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts#L24)):*
> ```XML
>       'cockroach sql --insecure --execute="BEGIN; CREATE TABLE cypress_test (id int); INSERT INTO cypress_test VALUES (234); INSERT INTO cypress_test VALUES (234); SELECT * FROM cypress_test; COMMIT;"'
>     );
>     cy.findAllByPlaceholderText("Search transactions")
> ```

Do you need `findAll` here if you're targeting a single element? Would `findByPlaceholderText` work?
___
*[pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsKS3D9dOCakSc2Rlm:-MXsKS3D9dOCakSc2Rln:b5qv5t1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts#L26)):*
> ```XML
>     cy.findAllByPlaceholderText("Search transactions")
>       .should("exist")
>       .click()
> ```

Do you need to click in order to type in the field?
___
*[pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsKdEh5T2FO7pkXHS5:-MXsKdEh5T2FO7pkXHS6:brh71cs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts#L28)):*
> ```XML
>       .click()
>       .type("CREATE TABLE cypress_test");
>     cy.findAllByRole("button", "Enter").eq(0).click();
> ```

There should only be a single "Enter" button on the page. Can we do it without `findAll` and without `eq(0)`?
___
*[pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsKmA6BIhYWWx8buN_:-MXsKmA6BIhYWWx8buNa:b-7xdoxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts#L36)):*
> ```XML
>     cy.findAllByText("CREATE TABLE cypress_test").should("exist");
>     cy.findAllByText("INSERT INTO cypress_test").should("exist");
>     cy.findAllByText("SELECT FROM cypress_test").should("exist");
> ```

Can you add a test that clicks on the Transaction into the Transaction details page and verifies that each statement fingerprint within the transaction shows up individually as well.

**Review by nanduu04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63401)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @nanduu04)

___
*[pkg/ui/cypress/integration/databases/databases.visual.spec.ts, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsJTcgEBtyi7YRQb0r:-MYHaDqg0-y_hN_Bp_MZ:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/databases/databases.visual.spec.ts#L16)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Seems odd to check for the `postgres` database in a CRDB test :smile:
</blockquote></details>

Removed
___
*[pkg/ui/cypress/integration/databases/databases.visual.spec.ts, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsJkak7QCqG3hbbnbd:-MYHaFdq1BOnh_Rt0KwX:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/databases/databases.visual.spec.ts#L23)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I recommend using `create table if not exists` so that this test can be run multiple times on the same DB, or execute a `drop` operation at the end of the test.
</blockquote></details>

Done
___
*[pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsKH0Y4auqN7o-Zq9u:-MYHaIQm16KuIuyK6sXn:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts#L18)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: The naming on this test should be more specific. We're testing that transaction *statistics* show up properly, not that the transaction executes.
sp: executed
</blockquote></details>

Done
___
*[pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsKWZOEesEfht7cVsl:-MYHaJS94-EmRJ5yeMbG:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts#L24)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Do you need `findAll` here if you're targeting a single element? Would `findByPlaceholderText` work?
</blockquote></details>

Removed
___
*[pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsKS3D9dOCakSc2Rlm:-MYHaKpIAicedHFVkYZg:b-rsrrar) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts#L26)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Do you need to click in order to type in the field?
</blockquote></details>

Yep, we need to click to type
___
*[pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-MXsKdEh5T2FO7pkXHS5:-MYHaOB-4tRlgoX0V0up:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2611f87a22f83219336cedab83282dbebc071fcb/pkg/ui/cypress/integration/transactions/transactions.visual.spec.ts#L28)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

There should only be a single "Enter" button on the page. Can we do it without `findAll` and without `eq(0)`?
</blockquote></details>

removed

**Review by dhartunian — APPROVED** [review]
> ui: e2e tests, improved cypress test for transactions, overview  and database page

this line is too long. truncate to "ui: e2e tests for txns, overview, db pages" or something like that.


:lgtm: otherwise, feel free to merge after fixing the commit message title (make sure to update it to match the PR title as well)

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63401#-:-MYKzS0X2QooDuOTA3B2:bfovl6e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nanduu04)

**Pull request merged**
