### PR TITLE
sql: separate groupNode post-renders into a renderNode

### LINKED ISSUE #12525: sql: rework the pre and post renderings for groupNode, remove identAggregator
```sql
CREATE DATABASE t;
CREATE TABLE t.t(x INT);
INSERT INTO t.t(x) VALUES (42);
SELECT 1 + count(*) FROM t.t; -- this works
TRUNCATE t.t;
SELECT 1 + count(*) FROM t.t; -- this panics!
```

```
panic: interface conversion: parser.Datum is nil, not *parser.DInt [recovered]
        panic: SELECT 1 + count(*) FROM t.t;: interface conversion: parser.Datum is nil, not *parser.DInt [recovered]
        panic: SELECT 1 + count(*) FROM t.t;: interface conversion: parser.Datum is nil, not *parser.DInt

goroutine 297 [running]:
panic(0x17da0a0, 0xc4203f5090)
        /mnt/kena/go1.7.3/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420499dd0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x17da0a0, 0xc4203f5090)
        /mnt/kena/go1.7.3/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc420942000, 0x1d)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:455 +0x149
panic(0x180a580, 0xc420cadac0)
        /mnt/kena/go1.7.3/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/parser.glob..func133(0xc420aee1a8, 0x0, 0x0, 0x255ca20, 0xc4203f5068, 0x0, 0xc420211ec0, 0xc421620ea0, 0x2526cf0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/eval.go:249 +0xdc
github.com/cockroachdb/cockroach/pkg/sql/parser.(*BinaryExpr).Eval(0xc42090fc80, 0xc420aee1a8, 0xc42169bc30, 0xc4203f5040, 0x1, 0x1)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/eval.go:1858 +0x1a8
github.com/cockroachdb/cockroach/pkg/sql.(*groupNode).computeAggregates(0xc420a86c60, 0xc42090fc00, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/group.go:403 +0x287
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
We move the group renders into a separate node, which simplifies the `groupNode`.
`HAVING` is also separated into a `filterNode` (which sits between the `groupNode`
and the "post" `renderNode`).

We no longer need to put `aggregateFuncHolders` inside post-render expressions;
these nodes now become just IndexedVars in the post-renderNode.  The `groupNode`
code is also improved to use less memory: instead of first emitting all rows to
a `RowContainer`, we emit them directly from the buckets.

This also simplifies the distsql planning code a lot: we can now easily convert a
`groupNode` to an `aggregator` without having to rewrite expressions. We also get
support for `HAVING` in distsql for free. Adding support for `FILTER` should
also be much easier now (to be done in a separate change).

Fixes #12525.

CC @arjunravinarayan for the distsql parts.

### CODE REVIEW

**Comment by knz** [comment]
Thank you for taking this on. At last! This is great.

Some nits remaining.

---

Reviewed 9 of 12 files at r1.
Review status: 9 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/group.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhatYTlgec_y4LxGuu:-KjhatYUYJ6sGGvjJXG8:bop98xb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L41)):*
> ```Go
> // post-processing nodes according to grouping functions or clauses.
> //
> // The bottom of the complex is always a groupNode which initially wraps the given
> ```

bottom -> data source 
which initially wraps -> which initially uses the given renderNode as its own data source

---

*[pkg/sql/group.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-Kjhb0q-Ay8Idt9baxCy:-Kjhb0q-Ay8Idt9baxCz:b-8q0u00) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L45)):*
> ```Go
> // renderNode is optimized out).
> //
> // On top of the groupNode there is normally a renderNode which renders
> ```

"the visible node from the consumer side is a renderNode which ..."

---

*[pkg/sql/group.go, line 49 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhbDxISkUHeVZhPQSl:-KjhbDxISkUHeVZhPQSm:b7jvwyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L49)):*
> ```Go
> // in-between them.
> //
> // The top planNode and bottom groupNode the node complex are returned; if there
> ```

" the constructor returns both the consumer-side planNode and the main groupNode ..."

---

*[pkg/sql/group.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhcnPlvp5xi0kP-HBH:-KjhcnPlvp5xi0kP-HBI:b-9wygtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L226)):*
> ```Go
> 	}
> 
> 	postRender.source.info = &dataSourceInfo{sourceColumns: group.columns}
> ```

This misses the `sourceAliases` field. Taking care of this should fix the problem with table names being unnamed (_) 
I think the proper way to do this is to construct a proper `sourceAliases` field which uses anonymousTableName for renders that derive from aggregate functions, and the proper table name for renders that directly derive from a column in the source. I can try to construct an example if you don't see what I mean.

---

*[pkg/sql/group.go, line 395 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-Kjhd7smGRUkJaSSr80X:-Kjhd7smGRUkJaSSr80Y:b-g3hfv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L395)):*
> ```Go
> 	var bucket string
> 	// Pick an arbitrary bucket.
> 	for bucket = range n.buckets {
> ```

(My kingdom for std::ordered_map... think of the mean optimizations we could do here with ORDER BY)

---

*[pkg/sql/testdata/logic_test/aggregate, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhQrRroYwkHHK1syAo:-KjhQrRsUBc2BJ0j8iRd:bywqi5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/testdata/logic_test/aggregate#L11)):*
> ```
> )
> 
> # query ITTTTT
> ```

Why did you add this query-in-comment?

---

*[pkg/sql/testdata/logic_test/explain_debug, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhQ6dDD7kkLD7d_Ap9:-KjhQ6dE5owDeYbjudmY:burqalp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/testdata/logic_test/explain_debug#L176)):*
> ```
> 4  /ab/primary/2/6  NULL  BUFFERED
> 5  /ab/primary/3/9  NULL  BUFFERED
> 0  NULL             (9)   ROW
> ```

Curious: what just happened here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-:-KjhRPb_wZP2Aq1vZSyA:bwst7pn)*

**Comment by RaduBerinde** [comment]
Thanks for reviewing so quickly!

---

Review status: 6 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/group.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhatYTlgec_y4LxGuu:-Kjht8x09USfEsifOpVp:blx65w9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L41)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

bottom -> data source 
which initially wraps -> which initially uses the given renderNode as its own data source
</blockquote></details>

By bottom I mean the lowest node we are creating (the data source is below that).

Fixed the second.

---

*[pkg/sql/group.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-Kjhb0q-Ay8Idt9baxCy:-KjhukMTmQWRGqIA3H9k:b-oinloe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L45)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"the visible node from the consumer side is a renderNode which ..."
</blockquote></details>

Done. Also added some "diagrams".

---

*[pkg/sql/group.go, line 49 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhbDxISkUHeVZhPQSl:-Kjhumu3zSNHBAXNRMl_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L49)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

" the constructor returns both the consumer-side planNode and the main groupNode ..."
</blockquote></details>

Done.

---

*[pkg/sql/group.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhcnPlvp5xi0kP-HBH:-KjhwkcXZGFIHub8Ke4u:bz6wo6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L226)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This misses the `sourceAliases` field. Taking care of this should fix the problem with table names being unnamed (_) 
I think the proper way to do this is to construct a proper `sourceAliases` field which uses anonymousTableName for renders that derive from aggregate functions, and the proper table name for renders that directly derive from a column in the source. I can try to construct an example if you don't see what I mean.
</blockquote></details>

Thanks, this did feel hacky. I *think* I did what you suggested, PTAL.

---

*[pkg/sql/testdata/logic_test/aggregate, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhQrRroYwkHHK1syAo:-KjhskBAKdRw9a-TRgrN:bq1qvz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/testdata/logic_test/aggregate#L11)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why did you add this query-in-comment?
</blockquote></details>

It is a testament of my sloppiness :) Thanks for catching it, removed (I used it once while debugging and forgot about it).

---

*[pkg/sql/testdata/logic_test/explain_debug, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhQ6dDD7kkLD7d_Ap9:-Kjhsu-8Kt5dPnz-zONf:bw3vyyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/testdata/logic_test/explain_debug#L176)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Curious: what just happened here?
</blockquote></details>

We were serving the results from a valuesNode which puts the row idx in the key column. We don't do that anymore. We could keep a counter and do the same but it's not very useful (I did it as a "why not" for valuesNode because it was readily available).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-:-KjhtNFSzc4xk2wYbKLt:b-evay7o)*

**Comment by knz** [comment]
Reviewed 3 of 3 files at r2.
Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/group.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhatYTlgec_y4LxGuu:-Kji6LlSgUICInzV6JW1:b-cdds5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L41)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

By bottom I mean the lowest node we are creating (the data source is below that).

Fixed the second.
</blockquote></details>

The thing is I am not sure the idea of "top" and "bottom" really makes sense, because nowhere we really ever formalize the fact that there is a vertical direction in a query plan.

In particular what's misleading is that the output of our EXPLAIN places the root at the top, whereas the Volcano paper and the distsql query plan visualizer both place the root at the bottom.

I think it would be a general improvement to all comments throughout the source base to stop relying on a vertical order and start talking about source/sink/direction instead.

---

*[pkg/sql/group.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhcnPlvp5xi0kP-HBH:-Kji6kpTuEwpB8x22Mb2:bdtm25o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L226)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Thanks, this did feel hacky. I *think* I did what you suggested, PTAL.
</blockquote></details>

Yes that will help already. 
The only thing I am slightly curious about is this: `SELECT a.x FROM a, b GROUP BY y` (when both `a` and `b` have a column named `x`).
Without propagating the table names, we can't distinguish the column in the render. I'm not feeling strongly about this, but I am curious about what pg does.

---

*[pkg/sql/testdata/logic_test/explain_debug, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhQ6dDD7kkLD7d_Ap9:-Kji7XVKhCrL4pz6UC-h:b2nhpa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/testdata/logic_test/explain_debug#L176)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We were serving the results from a valuesNode which puts the row idx in the key column. We don't do that anymore. We could keep a counter and do the same but it's not very useful (I did it as a "why not" for valuesNode because it was readily available).
</blockquote></details>

Thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/group.go, line 226 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhcnPlvp5xi0kP-HBH:-Kji88pKQtU3Y6arnBgr:b-975bn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L226)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes that will help already. 
The only thing I am slightly curious about is this: `SELECT a.x FROM a, b GROUP BY y` (when both `a` and `b` have a column named `x`).
Without propagating the table names, we can't distinguish the column in the render. I'm not feeling strongly about this, but I am curious about what pg does.
</blockquote></details>

But we never try to look up or resolve columns from these nodes, so I don't think it would matter?

I tried a similar query to yours, it works fine and this is the explain:

```
root@:26257/test> EXPLAIN (VERBOSE) SELECT a.x FROM a, b GROUP BY a.x;
+-------+--------+-------------+-------------+---------------------------------------------------------------------------+----------+
| Level |  Type  |    Field    | Description |                                  Columns                                  | Ordering |
+-------+--------+-------------+-------------+---------------------------------------------------------------------------+----------+
|     0 | group  |             |             | (x)                                                                       |          |
|     0 |        | aggregate 0 | test.a.x    |                                                                           |          |
|     1 | render |             |             | (x)                                                                       |          |
|     1 |        | render 0    | test.a.x    |                                                                           |          |
|     2 | join   |             |             | (x, rowid[hidden,omitted], x[omitted], y[omitted], rowid[hidden,omitted]) |          |
|     2 |        | type        | cross       |                                                                           |          |
|     3 | scan   |             |             | (x, rowid[hidden,omitted])                                                |          |
|     3 |        | table       | a@primary   |                                                                           |          |
|     3 |        | spans       | ALL         |                                                                           |          |
|     3 | scan   |             |             | (x[omitted], y[omitted], rowid[hidden,omitted])                           |          |
|     3 |        | table       | b@primary   |                                                                           |          |
|     3 |        | spans       | ALL         |                                                                           |          |
+-------+--------+-------------+-------------+---------------------------------------------------------------------------+----------+
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/group.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjhatYTlgec_y4LxGuu:-KjiGmj-zNLZIOOppP9k:b-1gz6p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85858897a1db765fbb284064825b924af1ce683/pkg/sql/group.go#L41)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The thing is I am not sure the idea of "top" and "bottom" really makes sense, because nowhere we really ever formalize the fact that there is a vertical direction in a query plan.

In particular what's misleading is that the output of our EXPLAIN places the root at the top, whereas the Volcano paper and the distsql query plan visualizer both place the root at the bottom.

I think it would be a general improvement to all comments throughout the source base to stop relying on a vertical order and start talking about source/sink/direction instead.
</blockquote></details>

Good point, there was definitely confusion about the vertical direction. Rephrased and removed other references to top and bottom.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r3.
Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796)*

**Comment by knz** [comment]
LGTM for the first - I'll let someone else review the distsql part.

**Comment by arjunravinarayan** [comment]
A decent amount of :dog: overall, but :lgtm: on the DistSQL part. The change is clear from looking at the explain output in the distsql_agg logic test, so next time would be useful to add the test in a first commit with the old output, and then the effect of the change with the change itself? I hand-rolled that myself and it was instantly clear, which helped understanding a great deal.

---

Reviewed 7 of 12 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/distsql_agg, line 417 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjngHbXKCVn1wj38ccX:-KjngHbXKCVn1wj38ccY:b-ncaa78) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa58822373b3de80933b92adc1aa7389912f572e/pkg/sql/testdata/logic_test/distsql_agg#L417)):*
> ```
> 1000
> 
> statement error memory budget exceeded
> ```

I had to check what these queries produced prior to this change, but looking at that, this is great reduction in complexity!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-:-KjndaQT-lfIndxwkByK:b-jhlb6h)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/distsql_agg, line 417 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjngHbXKCVn1wj38ccX:-KjnihL-By1k8kKnNDwM:b-tcfbp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa58822373b3de80933b92adc1aa7389912f572e/pkg/sql/testdata/logic_test/distsql_agg#L417)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I had to check what these queries produced prior to this change, but looking at that, this is great reduction in complexity!
</blockquote></details>

Not sure I understand what you mean. HAVING was not supported, so all these would have been errors.. Was that not the case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/testdata/logic_test/distsql_agg, line 417 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjngHbXKCVn1wj38ccX:-KjnkIiEPAoAji9m4XHF:bdb7ftx) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa58822373b3de80933b92adc1aa7389912f572e/pkg/sql/testdata/logic_test/distsql_agg#L417)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Not sure I understand what you mean. HAVING was not supported, so all these would have been errors.. Was that not the case?
</blockquote></details>

I just checked, indeed these don't work at all without this change (`pq: group with having not supported yet`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796)*

**Comment by arjunravinarayan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/distsql_agg, line 417 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796#-KjngHbXKCVn1wj38ccX:-Kjnjm0ul2DcXsYMSUKT:b-7cbomv) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa58822373b3de80933b92adc1aa7389912f572e/pkg/sql/testdata/logic_test/distsql_agg#L417)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I just checked, indeed these don't work at all without this change (`pq: group with having not supported yet`).
</blockquote></details>

Sorry I  was confused. The changed tests were all in `test_data/aggregate`, and I reran many of them myself after pulling your PR because I was reviewing some outdated commit deltas.

The reduction in complexity I was talking about was the removal of the render nodes in the regular `EXPLAIN` code, making everything simpler to understand.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15796)*

**Pull request merged**
