### PR TITLE
sql: ensure that Upsert will never update the same row twice

### LINKED ISSUE #44466: Multi-record UPSERT inserts duplicate values in PRIMARY KEY, resulting in inconsistent results
Consider the following testcase:

```sql
CREATE TABLE t0(c0 INT PRIMARY KEY, c1 BOOL, c2 INT UNIQUE);
INSERT INTO t0(c0) VALUES (0);
UPSERT INTO t0(c2, c0) VALUES (0, 0), (1, 0);
SELECT * FROM t0; -- {0 | NULL | 1}
```
A single row is fetched, while the following query fetches two records with a duplicate value for c0:

```sql
SELECT c0 FROM t0; -- {0, 0}
```
I found this issue in CockroachDB based on commit `1917a12003daad100b491e2b0195d7df5909e63f`.

### PR DESCRIPTION
**Pull request by andy-kimball**
Previously, there were cases where an UPSERT or INSERT..ON CONFLICT
statement could operate on the same row more than once. This is a
problem because these statements are designed to read once to get
existing rows, and then to insert or update based on that information.
They don't expect that previous writes for the same statement will
affect the correctness of subsequent writes. This can lead to index
corruption in cases where a row "moves" from one location to another
when one of its index keys changes. See issue #44466 for an example.

This PR fixes the problem by introducing a new variation of the
DistinctOn operator that ensures that the input to the Upsert
operator never has duplicates. It differs from the regular DistinctOn
operator in two ways:

  1. Null behavior: UpsertDistinctOn treats NULL values as not equal
     to one another for purposes of grouping. Two rows having a NULL-
     valued grouping column will be placed in different groups. This
     differs from DistinctOn behavior, where the two rows would be
     grouped together. This behavior difference reflects SQL semantics,
     in which a unique index key still allows multiple NULL values.

  2. Duplicate behavior: UpsertDistinctOn raises an error if any
     distinct grouping contains more than one row. It has "input must
     be distinct" semantics rather than "make the input distinct"
     semantics. This is used to ensure that no row will be updated
     more than once.

The optbuilder now wraps the input to the Upsert operator with this
new UpsertDistinctOn operator. In addition, there are several commits
that add optimization rules designed to remove these distinct operators
when they can be proven to not be necessary.

Fixes #44466

### CODE REVIEW

**Comment by andy-kimball** [comment]
@jordanlewis, not sure who on your team should review the SQL execution changes (part of the 1st commit). I added @yuzefovich as a guess.

**Review by rytaft — APPROVED** [review]
:lgtm: very nice!

> Reviewed 39 of 39 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-:-M0xLmRZ9mZQ0TPbrT4l:bhnhlex)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/opt/norm/groupby.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0xC842-1SEd_5JojRX:-M0xC842-1SEd_5JojRY:bj351gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6527c9fbd1e3b4a93676cf4bec8a50b487ec1cf2/pkg/sql/opt/norm/groupby.go#L23)):*
> ```Go
> 
> // RemoveGroupingCols returns a new grouping private struct with the given
> // columns removed from the window partition column set.
> ```

window partition -> grouping
___
*[pkg/sql/opt/norm/groupby.go, line 222 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0xHUnyEzJIPRWR9g2u:-M0xHUnyEzJIPRWR9g2v:beblz4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f6a36fee944bc7003a60498d4b10c1262fecc2b/pkg/sql/opt/norm/groupby.go#L222)):*
> ```Go
> }
> 
> // MakeRowsDistinct tries to ensure that the given rows are unique with respect
> ```

MakeRowsDistinct -> areRowsDistinct

Also need to change the rest of the text in this comment
___
*[pkg/sql/opt/norm/groupby.go, line 247 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0xIcZ9BMzmYOanhHwl:-M0xIcZ9BMzmYOanhHwm:b-e159ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f6a36fee944bc7003a60498d4b10c1262fecc2b/pkg/sql/opt/norm/groupby.go#L247)):*
> ```Go
> 
> 		forceDistinct := false
> 		for iCol, colID := range cols {
> ```

[nit] Why not just use `i` instead of `iCol`?
___
*[pkg/sql/opt/norm/rules/groupby.opt, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0x384L1BH80mMAKkth:-M0x384L1BH80mMAKkti:bx73w9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6959f661aa290cbc1f7c59766f08149a5ab036af/pkg/sql/opt/norm/rules/groupby.opt#L120)):*
> ```
> #
> # Note that this rule does not apply to UpsertDistinctOn, since that will raise
> # error if there are duplicate rows.
> ```

raise error -> raise an error
___
*[pkg/sql/opt/norm/testdata/rules/groupby, line 1347 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0xLZySCoTAeTMa5amX:-M0xLZySCoTAeTMa5amY:ba9hxqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f6a36fee944bc7003a60498d4b10c1262fecc2b/pkg/sql/opt/norm/testdata/rules/groupby#L1347)):*
> ```
>            └── variable: column1 [type=int]
> 
> # DistinctOn treats NULL values as distinct, so it can't be eliminated.
> ```

Isn't it the opposite?
___
*[pkg/sql/opt/norm/testdata/rules/groupby, line 1362 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0xLanM5sf4lo_Deavf:-M0xLanM5sf4lo_Deavg:ba9hxqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f6a36fee944bc7003a60498d4b10c1262fecc2b/pkg/sql/opt/norm/testdata/rules/groupby#L1362)):*
> ```
>       └── (NULL,) [type=tuple{unknown}]
> 
> # UpsertDistinctOn treats NULL values as not distinct, so it can be eliminated.
> ```

Isn't it the opposite?
___
*[pkg/sql/opt/optbuilder/insert.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0x4czx4ypFqxWZUe53:-M0x4czx4ypFqxWZUe54:b-q8dxii) ([raw file](https://github.com/cockroachdb/cockroach/blob/6959f661aa290cbc1f7c59766f08149a5ab036af/pkg/sql/opt/optbuilder/insert.go#L139)):*
> ```Go
> //     CASE WHEN fetch_a IS NULL ins_c ELSE fetch_c END AS ups_c,
> //   FROM (
> //     SELECT DISTINCT ON (ins_a) *
> ```

would help to emphasize somewhere below that this is not a normal distinct on (or somehow make that clear with syntax here)
___
*[pkg/sql/rowexec/distinct.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0x7QSz6aCC2J2ITYm3:-M0x7QSz6aCC2J2ITYm4:b-txvd0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6959f661aa290cbc1f7c59766f08149a5ab036af/pkg/sql/rowexec/distinct.go#L179)):*
> ```Go
> 		// row.
> 		if d.nullsAreDistinct && d.lastGroupKey[colIdx].IsNull() {
> 			return false, err
> ```

return false, nil

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45372)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/norm/groupby.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0xC842-1SEd_5JojRX:-M0xtB7r3uKpq9QM0LKG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6527c9fbd1e3b4a93676cf4bec8a50b487ec1cf2/pkg/sql/opt/norm/groupby.go#L23)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

window partition -> grouping
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/groupby.go, line 222 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0xHUnyEzJIPRWR9g2u:-M0xu-mw89VQjqGRol-3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f6a36fee944bc7003a60498d4b10c1262fecc2b/pkg/sql/opt/norm/groupby.go#L222)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

MakeRowsDistinct -> areRowsDistinct

Also need to change the rest of the text in this comment
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/groupby.go, line 247 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0xIcZ9BMzmYOanhHwl:-M0xu3nO4lt4vnz-kvTK:bkfrhrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f6a36fee944bc7003a60498d4b10c1262fecc2b/pkg/sql/opt/norm/groupby.go#L247)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] Why not just use `i` instead of `iCol`?
</blockquote></details>

At one point, I had an `iRow` as well. Fixed.
___
*[pkg/sql/opt/norm/rules/groupby.opt, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0x384L1BH80mMAKkth:-M0xugVvE0nlpP7EMuGB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6959f661aa290cbc1f7c59766f08149a5ab036af/pkg/sql/opt/norm/rules/groupby.opt#L120)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

raise error -> raise an error
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/groupby, line 1347 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0xLZySCoTAeTMa5amX:-M0xv9MpAccvv-33JY-F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f6a36fee944bc7003a60498d4b10c1262fecc2b/pkg/sql/opt/norm/testdata/rules/groupby#L1347)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Isn't it the opposite?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/groupby, line 1362 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0xLanM5sf4lo_Deavf:-M0xvIUuBVI4ygoe6tDM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f6a36fee944bc7003a60498d4b10c1262fecc2b/pkg/sql/opt/norm/testdata/rules/groupby#L1362)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Isn't it the opposite?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0x4czx4ypFqxWZUe53:-M0xvmmaAoNby9v_8yhC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6959f661aa290cbc1f7c59766f08149a5ab036af/pkg/sql/opt/optbuilder/insert.go#L139)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would help to emphasize somewhere below that this is not a normal distinct on (or somehow make that clear with syntax here)
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/distinct.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0x7QSz6aCC2J2ITYm3:-M0xwBjmCcGaIyvZuM4u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6959f661aa290cbc1f7c59766f08149a5ab036af/pkg/sql/rowexec/distinct.go#L179)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

return false, nil
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
Shouldn't this PR also close #37880?

How does it relate to #44434? Do we support IGNORE?

The execution stuff looks good, I just have a few comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-:-M0yRkZ4EvafuPuzduRv:b-6mqbpm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/distinct.go, line 50 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0yQfcTC2S5p5KEWvTb:-M0yQfcTC2S5p5KEWvTc:b-qsplol) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fd3784e045d93d4675160ed2e80e0c9e55e237b/pkg/sql/distinct.go#L50)):*
> ```Go
> 	// A distinct operation on column "c" will result in one output row if
> 	// nullsAreDistinct is false, or two output rows if true.
> 	nullsAreDistinct bool
> ```

Could you include some context in this comment? We tend to grow lots of flags like this one over time that change the behavior of the operators significantly. Code readers tend to want to know what the flags are for. Example:

"For ordinary SQL DISTINCT, this flag is true/false. It's set to false/true when doing XYZ, for example"
___
*[pkg/sql/distinct.go, line 55 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0yRFuw16Nq2At0kR-p:-M0yRFux9bzhEAZG_Ave:bx15msn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fd3784e045d93d4675160ed2e80e0c9e55e237b/pkg/sql/distinct.go#L55)):*
> ```Go
> 	// the distinct operation finds two rows with duplicate grouping column
> 	// values. This is used to implement the UPSERT and INSERT..ON CONFLICT
> 	// statements, both of which prohibit the same row from being changed twice.
> ```

This is a good example of the context I was looking for in the first comment. Maybe just duplicate it above?
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 287 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0yRRsxBePGLK82-tc2:-M0yRRsxBePGLK82-tc3:b6p82vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fd3784e045d93d4675160ed2e80e0c9e55e237b/pkg/sql/execinfrapb/processors_sql.proto#L287)):*
> ```protobuf
>   //
>   // A distinct operation on column "c" will result in one output row if
>   // NullsAreDistinct is false, or two output rows if true.
> ```

ditto on the context comment from above
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 1077 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0yTfSc4t8u7R0vj8cT:-M0yTfSc4t8u7R0vj8cU:b-hy7m8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fd3784e045d93d4675160ed2e80e0c9e55e237b/pkg/sql/logictest/testdata/logic_test/upsert#L1077)):*
> ```
> # Ensure this test stays synchronized to the EXPLAIN in exec/execbuilder/upsert,
> # so that use of streaming group-by is confirmed.
> # ------------------------------------------------------------------------------
> ```

I know we do this all over, but it's fragile. Can you also add unit tests to `rowexec/distinct_test.go`? That file probably could use more tests in general, but also it'll let you test the functionality you added to the execution engine more tightly. 
___
*[pkg/sql/opt/exec/execbuilder/testdata/upsert, line 289 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0ySRK3Ek7A7FtItkM7:-M0ySRK3Ek7A7FtItkM8:bwghzg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fd3784e045d93d4675160ed2e80e0c9e55e237b/pkg/sql/opt/exec/execbuilder/testdata/upsert#L289)):*
> ```
>  WHERE operation != 'dist sender send'
> ----
> join reader                           Scan /Table/57/1/2{-/#}
> ```

Why did these change?

**Review by rytaft — APPROVED** [review]
> Reviewed 8 of 21 files at r5, 4 of 9 files at r7, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45372)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @RaduBerinde, and @yuzefovich)

**Review by andy-kimball — COMMENTED** [review]
This PR does not handle the `DO NOTHING` case. That's a separate PR that will follow, but will use some of the machinery that this PR introduces. #44434 is just a duplicate of #37880, so the follow-on PR will close them both. 

Note that the two cases are related but different: the index corruption bug is caused because duplicate rows *are not* raising an error. The DO NOTHING bug is caused because duplicate rows *are* raising an error. Implementation-wise, both will use `UpsertDistinctOp`. But `DO NOTHING` will set `ErrorOnDup=False`, whereas `ON CONFLICT DO UPDATE` will set `ErrorOnDup=True`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-:-M0yeaVJEhRUlGLYfIzK:b1aumf8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/distinct.go, line 50 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0yQfcTC2S5p5KEWvTb:-M0yfUEYESdUQuAhrXt-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fd3784e045d93d4675160ed2e80e0c9e55e237b/pkg/sql/distinct.go#L50)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Could you include some context in this comment? We tend to grow lots of flags like this one over time that change the behavior of the operators significantly. Code readers tend to want to know what the flags are for. Example:

"For ordinary SQL DISTINCT, this flag is true/false. It's set to false/true when doing XYZ, for example"
</blockquote></details>

Done.
___
*[pkg/sql/distinct.go, line 55 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0yRFuw16Nq2At0kR-p:-M0yfUjo67zuDZKEenUn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fd3784e045d93d4675160ed2e80e0c9e55e237b/pkg/sql/distinct.go#L55)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is a good example of the context I was looking for in the first comment. Maybe just duplicate it above?
</blockquote></details>

Done.
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 287 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0yRRsxBePGLK82-tc2:-M0yfVkL0dqV4FgwTkGA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fd3784e045d93d4675160ed2e80e0c9e55e237b/pkg/sql/execinfrapb/processors_sql.proto#L287)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto on the context comment from above
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/upsert, line 1077 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0yTfSc4t8u7R0vj8cT:-M0yrlYg2Whqc2LUh1HR:bqfzvrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fd3784e045d93d4675160ed2e80e0c9e55e237b/pkg/sql/logictest/testdata/logic_test/upsert#L1077)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I know we do this all over, but it's fragile. Can you also add unit tests to `rowexec/distinct_test.go`? That file probably could use more tests in general, but also it'll let you test the functionality you added to the execution engine more tightly. 
</blockquote></details>

Ah, I didn't notice those. Added some tests.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45372)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/upsert, line 289 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M0ySRK3Ek7A7FtItkM7:-M0yul_Z-UgqTLY03-B8:b-xqt9u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fd3784e045d93d4675160ed2e80e0c9e55e237b/pkg/sql/opt/exec/execbuilder/testdata/upsert#L289)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why did these change?
</blockquote></details>

Just intra-commit change. No overall change. There was an extra distinct operator in the mix, until a later commit added an optimization to get rid of it.

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-:-M0z02xD10dkiLUD6fsN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

**Review by RaduBerinde — COMMENTED** [review]
Late to the party - but this is great stuff! Obviously was a lot of work, but I think it's a pretty clean solution. Just have one question below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-:-M11pykV3sXFa1QMhEYt:bo1irpx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/norm/groupby.go, line 216 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M11pQOe9pGp2_q_NPwf:-M11pQOe9pGp2_q_NPwg:b-tnar6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f65459d5e276a8f65ff1d5931d94532c82e7516/pkg/sql/opt/norm/groupby.go#L216)):*
> ```Go
> 	case *memo.LeftJoinExpr:
> 		if groupingCols.SubsetOf(t.Left.Relational().OutputCols) {
> 			return c.AreValuesDistinct(t.Left, groupingCols, nullsAreDistinct)
> ```

Why is this ok? A left join could duplicate the value from the left side (unless the eq columns are a key, which is probably the case we care about).

**Comment by andy-kimball** [comment]
___
*[pkg/sql/opt/norm/groupby.go, line 216 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/45372#-M11pQOe9pGp2_q_NPwf:-M13E_WM2v8wqWkcNmZW:bj6qhst) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f65459d5e276a8f65ff1d5931d94532c82e7516/pkg/sql/opt/norm/groupby.go#L216)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why is this ok? A left join could duplicate the value from the left side (unless the eq columns are a key, which is probably the case we care about).
</blockquote></details>

You're absolutely right. My mind was stuck on thinking of this like a semi-join, which it basically is in this particular upsert case (since the right side always has a key that's part of join). I'll post another PR to fix.

**Pull request merged**
