### PR TITLE
[DNM] sql: add unique_unordered_rowid builtin

### PR DESCRIPTION
**Pull request by ajwerner**
This is a strawman proposal with no intention of being merged as is. I just
want initial feedback on the idea. I hear frequently people complaining about
not wanting to rekey databases that assume a 64-bit integer key. Our default
for that use-case incurs a write hot-spot which scares off customers. This
solution has no ordering but the same uniqueness properties. I imagine we
could have some way to make this the default `rowid` function and as a
`serial_normalization`.

Release note: Added a new sql builtin which generates a globally unique
64-bit integer that does not have ordering.

### CODE REVIEW

**Comment by ajwerner** [comment]
@bdarnell I'm curious to hear your take on this idea. I think I'd prefer to see people reaching for this by default than for hash-sharded indexes.

**Comment by bdarnell** [comment]
Yes, unordered IDs are better than hash-sharded indexes unless you specifically need the order. 

I'm fine with introducing this. I still think people would generally be better off switching to UUIDs (no risk of collisions when the node IDs get high enough, no issues with JSON rounding them off to 53 bits), but if they insist on using int64 IDs it's reasonable to give them this option.

`unique_rowid` and `unordered_unique_rowid` (note that you spell it differently in the commit message and the code) each guarantee uniqueness compared to other IDs generated by the same function. Can we say anything about what happens if you switch from one to the other with existing data? Collisions seem unlikely but it's difficult to quantify. Flipping the high bit of the node ID portion (or all the bits?) for unordered IDs would guarantee that ordered and unordered IDs don't collide until you have node IDs in the thousands.

How much can we trust the distribution of the low bits of the timestamp? (reminder that the low bit of this timestamp component represents 10μs, and we track the previous timestamp and add 1 if there were multiple ids generated in the last 10μs) There still seems some potential for clustering. For example, if the system clock is low precision and always returns zeros for the 10μs digit, then the ranges with zeros in the high bit would have a lot more traffic than the ones with ones (which would only be used when we had multiple IDs generated per clock tick). Clock precision is platform-dependent (the clock functions are said to be lower-precision on windows than on linux, although it's not clear to me what the real-world values are on any platform)

**Comment by jordanlewis** [comment]
This is an interesting idea - I like where it's going quite a bit.

**Comment by awoods187** [comment]
I'm really excited about this. I think we'd need some performance analysis here with various workloads. Of course the first thing would be to try to get people to switch to UUIDs, but where they are unwilling, unable, or simply don't know to do so, I think we should have a better default experience. Could we get this to be the default? 

cc @vy-ton

**Comment by rafiss** [comment]
One UX improvement I'd like to plug as long as we are considering changing the `rowid` function is to account for how the function interacts with SERIAL4 and SERIAL2. The current behavior is that even if you use SERIAL4 or SERIAL2, but you have `serial_normalization=rowid`, then the value returned is a 64-bit integer, which is confusing at best and at worst could break a tool trying to read the data.

see #55864 for example

**Comment by ajwerner** [comment]
> One UX improvement I'd like to plug as long as we are considering changing the `rowid` function is to account for how the function interacts with SERIAL4 and SERIAL2. The current behavior is that even if you use SERIAL4 or SERIAL2, but you have `serial_normalization=rowid`, then the value returned is a 64-bit integer, which is confusing at best and at worst could break a tool trying to read the data.
> 
> see #55864 for example

What should we do there? We could always use a sequence for those small ones given that's all we can guarantee with regards to correctness if we want to respect the width.

-----

While you're playing with this, which I think is a good idea, I want to alert you to https://github.com/cockroachdb/cockroach/pull/56954 which I also think is a good idea.

**Comment by rafiss** [comment]
replaced by https://github.com/cockroachdb/cockroach/pull/70338

**Pull request closed without merging**
