### PR TITLE
CODEOWNERS: replace admin-ui-prs with cluster-ui-prs

### PR DESCRIPTION
**Pull request by dhartunian**
Release justification: non-production code changes

This new group will also get notified on PRs for cluster-ui package in
the ui repository.

Release notes: None

### CODE REVIEW

**Review by nkodali — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61022)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61022)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
