### PR TITLE
storage: enable usage of RocksDB DeleteRange by default

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14391)

### CODE REVIEW

**Review by tamird — APPROVED** [review]

**Comment by petermattis** [comment]
The `TestStopServer` failure is reproducible and worrisome. Happens very quickly using`make stress PKG=./testutils/testcluster/ TESTS=TestStopServer`.

**Comment by bdarnell** [comment]
It doesn't look like we've been running with this enabled on the test clusters either (at least not in the currently checked-in configs). Should we try setting that environment variable on a few clusters before making it the default?

**Comment by petermattis** [comment]
> Should we try setting that environment variable on a few clusters before making it the default?

Hmm, we were running this on `blue` for a while. When did that change?

**Comment by petermattis** [comment]
Figured out the test failure (see #14416). We should definitely enable `COCKROACH_ENABLE_FAST_CLEAR_RANGE` on the test clusters for a while before merging this PR.

**Comment by petermattis** [comment]
`COCKROACH_ENABLE_FAST_CLEAR_RANGE` was enabled on 3 test clusters and it looks good so far. I plan to merge this PR after this week's beta goes out.

**Pull request merged**
