### PR TITLE
sql: Implement ALTER DATABASE ... ADD REGION

### PR DESCRIPTION
**Pull request by ajstorm**
This commit implements ALTER DATABASE ... ADD REGION, which allows users
to add regions to a multi-region database.  To add a region, the
database must already have a PRIMARY REGION.

Release note (sql change): Adds support for ALTER DATABASE ... ADD
REGION.

### CODE REVIEW

**Review by otan — COMMENTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ9342eEEO1KXYmrSOc:-MQ9342f33BrcK3Eh0JT:bia89hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L138)):*
> ```Go
> 
> 	// If we get to this point and the RegionConfig is nil, it means that the database doesn't
> 	// yet have a primary region.  Since we need a primary region before we can add a region,
> ```

nit: looks like a double space here.
___
*[pkg/sql/alter_database.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ93H3PBK-uTZezavL9:-MQ93H3PBK-uTZezavLA:ba342q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L140)):*
> ```Go
> 	// yet have a primary region.  Since we need a primary region before we can add a region,
> 	// return an error here.
> 	if n.desc.RegionConfig == nil {
> ```

nit: use `IsMultiRegion`
also does that mean someone has to use some other syntax to add a PRIMARY REGION first? can adding the first region implicitly make it a PRIMARY REGION with a HINT displayed to the user indicating as such?
___
*[pkg/sql/alter_database.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ936zjD84QPjVInlOt:-MQ936zjD84QPjVInlOu:bw1kcqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L142)):*
> ```Go
> 	if n.desc.RegionConfig == nil {
> 		return pgerror.Newf(pgcode.InvalidDatabaseDefinition,
> 			"cannot add region %q to database %q.  Please add primary region first.",
> ```

nit: double space here.
___
*[pkg/sql/alter_database.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ93CEFEROE_KqKvzuJ:-MQ93CEFEROE_KqKvzuK:b-bv7ae9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L147)):*
> ```Go
> 	}
> 
> 	// Add the region to the database descriptor.  This function validates that the region
> ```

nit: double space here
___
*[pkg/sql/alter_database.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ93__b2mbiyGpwHiNp:-MQ93__b2mbiyGpwHiNq:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L163)):*
> ```Go
> 	}
> 
> 	// Get the type descriptor for the multi-region enum
> ```

nit: missing period.
___
*[pkg/sql/alter_database.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ93b9e6nwVUaHbWWgo:-MQ93b9e6nwVUaHbWWgp:b-szafvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L172)):*
> ```Go
> 	}
> 
> 	// Add the new region value to the enum.  This function adds the value to the enum and
> ```

nit: double space
___
*[pkg/sql/alter_database.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94QnHBxDCSuNQ2MpK:-MQ94QnI32aBuLdbEsux:b-6axq92) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L181)):*
> ```Go
> 			NewVal:      tree.EnumValue(n.n.Region),
> 			IfNotExists: false,
> 			Placement:   nil},
> ```

can we add in alphabetical order?
___
*[pkg/sql/descriptor.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ93s_07Jh-BTGQp6Nx:-MQ93s_07Jh-BTGQp6Ny:b-2bgj90) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/descriptor.go#L288)):*
> ```Go
> 	regionConfig := desc.RegionConfig
> 
> 	// Ensure region we're adding is currently active.
> ```

super nit: comment seems extra (or comment the other stuff in here)
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94m8X-3MhrCpO_YtL:-MQ94m8X-3MhrCpO_YtM:brtz9fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/logictest/testdata/logic_test/multiregion#L320)):*
> ```
> 
> statement ok
> ALTER DATABASE region_test_db ADD REGION "test2"
> ```

can we add a test adding a region out-of-order?

**Review by ajstorm — COMMENTED** [review]
@otan TFTR!  All comments addressed below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-:-MQCxDcp2r643tDAzkWO:bn6pg0p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/alter_database.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ9342eEEO1KXYmrSOc:-MQCn7McCzGeUa_b3u5u:b-8xm5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L138)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: looks like a double space here.
</blockquote></details>

Yeah, I'm a double-spacer.  I'm assuming the convention is for single spaces?  I can make this change.
___
*[pkg/sql/alter_database.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ93H3PBK-uTZezavL9:-MQCoc003HQBv1K_5CX2:b-tc0jj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L140)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: use `IsMultiRegion`
also does that mean someone has to use some other syntax to add a PRIMARY REGION first? can adding the first region implicitly make it a PRIMARY REGION with a HINT displayed to the user indicating as such?
</blockquote></details>

Changed to use `IsMultiRegion`.  

Yes, the user will have to explicitly specify the PRIMARY region first.  I thought that this is what we agreed to, as we wanted to be super-explicit about the PRIMARY REGION in all cases (for example, we don't support CREATE DATABASE ... REGIONS "us-east" and default that to the PRIMARY REGION.

demo@127.0.0.1:26257/movr> create database blah2 regions "us-west1";
ERROR: PRIMARY REGION must be specified if REGIONS are specified
SQLSTATE: 42P12
___
*[pkg/sql/alter_database.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ936zjD84QPjVInlOt:-MQCnny98Dba86e9PtGf:bkusgnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L142)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: double space here.
</blockquote></details>

Done.  This habit is going to be hard to break.  Look forward to many more corrections of this going forward ;-).
___
*[pkg/sql/alter_database.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ93CEFEROE_KqKvzuJ:-MQCpHUx5kRuRW5Eeb8l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L147)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: double space here
</blockquote></details>

Done.
___
*[pkg/sql/alter_database.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ93__b2mbiyGpwHiNp:-MQCpLOJBaTrEw6bcj1r:busc7sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L163)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: missing period.
</blockquote></details>

Fixed`.`
___
*[pkg/sql/alter_database.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94QnHBxDCSuNQ2MpK:-MQCpe266npwSe-rGFsj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L181)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we add in alphabetical order?
</blockquote></details>

Done.
___
*[pkg/sql/descriptor.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ93s_07Jh-BTGQp6Nx:-MQCqLmeB87MQGmOEolr:boryf3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/descriptor.go#L288)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

super nit: comment seems extra (or comment the other stuff in here)
</blockquote></details>

Be careful what you ask for.  I added comments throughout, and made sure to use only one space after periods (unlike what I've done here).
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94m8X-3MhrCpO_YtL:-MQCx0yw9ogOi6ml_dJ7:b-z05y8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/logictest/testdata/logic_test/multiregion#L320)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we add a test adding a region out-of-order?
</blockquote></details>

Yup.  Done.

**Review by ajstorm — COMMENTED** [review]
Please also note the change I made to add validation of the type descriptor.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-:-MQD3X-Y2l5NCchLDyMX:b-h4gsob)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/alter_database.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQD3dGNDW88Cm7IzcTF:-MQD3dGO9SI9HN3LowAg:bxl9l8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef1224128211dc84479b39efee8abb95d789d41/pkg/sql/alter_database.go#L187)):*
> ```Go
> 	}
> 
> 	// Validate the type descriptor after the changes. We have to do this explicitly here, because
> ```

Please also note this new call I added after @otan's first review.  I realized that the type descriptor validation was only occurring in the `startExec()` call and we're calling `addEnumValue` directly so we need to validate here.

**Review by otan — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ9342eEEO1KXYmrSOc:-MQO85Bq1d93tuQ02ICS:b-17ffym) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L138)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Yeah, I'm a double-spacer.  I'm assuming the convention is for single spaces?  I can make this change.
</blockquote></details>

Yeah haven't seen that before :P 
___
*[pkg/sql/alter_database.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94QnHBxDCSuNQ2MpK:-MQO7EQQ6A9oapATxWq8:bz8vwf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L181)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ooft, I meant `Placement` needs to be set for the ENUM values to be in alphabetical order!
Can you also add a SHOW ENUMS test too to check the values are in order.
Wonder if it is worth validating
___
*[pkg/sql/alter_database.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQD3dGNDW88Cm7IzcTF:-MQO8B686iJ4X3_Lkv4R:b2nhiht) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef1224128211dc84479b39efee8abb95d789d41/pkg/sql/alter_database.go#L187)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Please also note this new call I added after @otan's first review.  I realized that the type descriptor validation was only occurring in the `startExec()` call and we're calling `addEnumValue` directly so we need to validate here.
</blockquote></details>

LG!

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/alter_database.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94QnHBxDCSuNQ2MpK:-MQOLIVP7vqbV007M2zj:b-ldyej0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L181)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Ooft, I meant `Placement` needs to be set for the ENUM values to be in alphabetical order!
Can you also add a SHOW ENUMS test too to check the values are in order.
Wonder if it is worth validating
</blockquote></details>

I didn't know we wanted to keep the regions in alphabetical order in the MR enum type, but if that is the case, we should def be validating it.  
___
*[pkg/sql/alter_database.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQOLjVR4PZN-UdhUFv5:-MQOLjVR4PZN-UdhUFv6:bok4cvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef1224128211dc84479b39efee8abb95d789d41/pkg/sql/alter_database.go#L145)):*
> ```Go
> 			"cannot add region %q to database %q. Please add primary region first.",
> 			n.n.Region.String(),
> 			n.n.Name.String())
> ```

nit: closing brace on the next line. 
___
*[pkg/sql/alter_database.go, line 168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQOKjva1W3h4LsPei2j:-MQOKjva1W3h4LsPei2k:bnc93n6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef1224128211dc84479b39efee8abb95d789d41/pkg/sql/alter_database.go#L168)):*
> ```Go
> 		params.ctx,
> 		params.p.txn,
> 		n.desc.RegionConfig.RegionEnumID)
> ```

nit: closing brace on next line
___
*[pkg/sql/alter_database.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQOJrHWBJjS3AFEOdIc:-MQOJrHWBJjS3AFEOdId:bi2nhxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef1224128211dc84479b39efee8abb95d789d41/pkg/sql/alter_database.go#L179)):*
> ```Go
> 		params.ctx,
> 		typeDesc,
> 		&tree.AlterTypeAddValue{
> ```

I'd prefer if we could avoid creating this dangling AST node here. Instead, maybe we could refactor `addEnumValue` to take these as individual params.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94QnHBxDCSuNQ2MpK:-MQRwm2eEJdG4L3hQJ4I:b-64hlvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L181)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I didn't know we wanted to keep the regions in alphabetical order in the MR enum type, but if that is the case, we should def be validating it.  
</blockquote></details>

I was going to do this originally, but erroneously concluded that it wouldn't work (as I thought that it would mess up the physical representations).  Now that I've debugged it and concluded that it's possible, I'm wondering what the motivation is for maintaining things in alpha-order?  Are you hoping that it allows us to early-out when searching for values?  Do we just want this for general cleanliness?  

I'm fine doing it, but we should have a compelling reason to do so, as it requires code in a bunch of places to make it happen (on original create, add value to enum, validation, etc) which adds complexity.  
___
*[pkg/sql/alter_database.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQOJrHWBJjS3AFEOdIc:-MQRtMFkE7DCX3urbNol:b-3w8c5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef1224128211dc84479b39efee8abb95d789d41/pkg/sql/alter_database.go#L179)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'd prefer if we could avoid creating this dangling AST node here. Instead, maybe we could refactor `addEnumValue` to take these as individual params. 
</blockquote></details>

Let me know how emphatically you feel about this.  I contemplated that idea, but initially rejected it because it seemed to make the call to `addEnumValue` (especially the original call) look messier.  I'm of the opinion that if there's a way to pass in a bunch of values neatly with a node struct, especially since that's the natural way to do it in one case, then we should do it that way.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/alter_database.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQOJrHWBJjS3AFEOdIc:-MQSvWXEEokam0gFsoco:b-7igxcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef1224128211dc84479b39efee8abb95d789d41/pkg/sql/alter_database.go#L179)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Let me know how emphatically you feel about this.  I contemplated that idea, but initially rejected it because it seemed to make the call to `addEnumValue` (especially the original call) look messier.  I'm of the opinion that if there's a way to pass in a bunch of values neatly with a node struct, especially since that's the natural way to do it in one case, then we should do it that way.
</blockquote></details>

I agree with you in general, but my hesitation is specifically because an AST node struct has special meaning. I'll leave it to your  judgement.

**Comment by otan** [comment]
___
*[pkg/sql/alter_database.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94QnHBxDCSuNQ2MpK:-MQTQdqWBT1kz4dDZkth:b-qcgcl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L181)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I was going to do this originally, but erroneously concluded that it wouldn't work (as I thought that it would mess up the physical representations).  Now that I've debugged it and concluded that it's possible, I'm wondering what the motivation is for maintaining things in alpha-order?  Are you hoping that it allows us to early-out when searching for values?  Do we just want this for general cleanliness?  

I'm fine doing it, but we should have a compelling reason to do so, as it requires code in a bunch of places to make it happen (on original create, add value to enum, validation, etc) which adds complexity.  
</blockquote></details>

I'm not strictly attached to it, I don't remember why I just know it is at the moment!
If we decide not to, do you mind filing an issue to get rid of this sort on create (or just get rid of it in this commit).

**Comment by otan** [comment]
___
*[pkg/sql/alter_database.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94QnHBxDCSuNQ2MpK:-MQTWQWG6YKiWpF5F_OZ:b-dzxpz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L181)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I'm not strictly attached to it, I don't remember why I just know it is at the moment!
If we decide not to, do you mind filing an issue to get rid of this sort on create (or just get rid of it in this commit).
</blockquote></details>

(reference here https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/descriptor.go#L331-L332)

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94QnHBxDCSuNQ2MpK:-MQTaAlbDPfgal0Ai2VH:b-15gv95) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L181)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(reference here https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/descriptor.go#L331-L332)
</blockquote></details>

I actually think there may be value in keeping things sorted in the RegionConfig (especially since we have it that way already now) as that's the single source of truth for the region list.  Keeping it sorted allows for a simplified validation that the regions in the type descriptor match those in the database descriptor, provided that we keep both of them sorted (which is the case today, but we're not validating it today).

My concern with the ENUM is that (a) it's not sorted today, and (b) doing so is more difficult because you can't just re-sort the ENUM after you add a value, you have to determine the placement and then pass that down through to the alterTypeAddValue() function.  
___
*[pkg/sql/alter_database.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQOJrHWBJjS3AFEOdIc:-MQT_X1t4NAspE3Wc1NP:b-nxva1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ef1224128211dc84479b39efee8abb95d789d41/pkg/sql/alter_database.go#L179)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I agree with you in general, but my hesitation is specifically because an AST node struct has special meaning. I'll leave it to your  judgement.
</blockquote></details>

After discussing this with @arulajmani, I'm going to keep the code as-is.  There are other places in sql where we fake out an AST node (like in `indexDefFromDescriptor()`), and it's easiest to do it that way here too.

**Comment by otan** [comment]
___
*[pkg/sql/alter_database.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94QnHBxDCSuNQ2MpK:-MQTcVuT5E6fh0DdWmBE:b1jn3zh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L181)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I actually think there may be value in keeping things sorted in the RegionConfig (especially since we have it that way already now) as that's the single source of truth for the region list.  Keeping it sorted allows for a simplified validation that the regions in the type descriptor match those in the database descriptor, provided that we keep both of them sorted (which is the case today, but we're not validating it today).

My concern with the ENUM is that (a) it's not sorted today, and (b) doing so is more difficult because you can't just re-sort the ENUM after you add a value, you have to determine the placement and then pass that down through to the alterTypeAddValue() function.  
</blockquote></details>

I thought the ENUM is sorted on create because it uses the results of the sort linked above to do so.

binary searching for the position of the current region using `sort.Search` and using the previous/next value as `Placement` doesn't seem too bad for me.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQ94QnHBxDCSuNQ2MpK:-MQX8LKvDz5mrB2a5pUJ:b69tlcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb9f572e85949354b245d886a458dd048272c28e/pkg/sql/alter_database.go#L181)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I thought the ENUM is sorted on create because it uses the results of the sort linked above to do so.

binary searching for the position of the current region using `sort.Search` and using the previous/next value as `Placement` doesn't seem too bad for me.
</blockquote></details>

Made the change and we're all sorted now.  Was a _bit_ trickier than I'd anticipated because I didn't realize that some `Name`'s are double-double quoted, which screwed up the ordering in my first implementation, but once I figure that out it was pretty straightforward to get this right.  Of note is the fact that I changed the multi-region testcase to use regions that (a) are more representative of what a customer might see, and (b) include `-`'s, as those are what trigger the double-double quoting, which has the potential to screw up the ordering.

PTAL, and thanks for the suggestion (it was a great learning experience).

**Review by otan — APPROVED** [review]
Sad there's no AU region

> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-:-MQiSe9M8fnbyWQ9qdwQ:bpo86tc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/logictest/logic.go, line 608 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQiSWTrAUqkQj7NrnVU:-MQiSWTrAUqkQj7NrnVV:b3lzy68) ([raw file](https://github.com/cockroachdb/cockroach/blob/3246d7e01ef6343f5d8fc739dcae4af0aaee93cd/pkg/sql/logictest/logic.go#L608)):*
> ```Go
> 				Tiers: []roachpb.Tier{
> 					{Key: "region", Value: "ca-central1"},
> 					{Key: "availability-zone", Value: "az1"},
> ```

adding the `-` was deliberate to test escaping for AZs. I'd rather keep it, but up to you.

**Review by ajstorm — COMMENTED** [review]
Ask, and you shall receive.  I replaced europe-west1 with ap-southeast-2.  

TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-:-MQlXqdO-lzSDjHE9T1s:bsqc4ml)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/logictest/logic.go, line 608 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58233#-MQiSWTrAUqkQj7NrnVU:-MQlXXTL6w7QE9MQx3qq:byybhzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3246d7e01ef6343f5d8fc739dcae4af0aaee93cd/pkg/sql/logictest/logic.go#L608)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

adding the `-` was deliberate to test escaping for AZs. I'd rather keep it, but up to you.
</blockquote></details>

Added the "-"'s back.  Didn't realize they were deliberate.  Also added a comment  so that people won't accidentally remove them again.

**Comment by ajstorm** [comment]
bors r=otan,arulajmani

**Comment by ajstorm** [comment]
Missed a rebase conflict.  Trying again... 

bors r=otan,arulajmani

**Comment by ajstorm** [comment]
Third time's a charm 🤞 

bors r=otan,arulajmani

**Pull request merged**
