### PR TITLE
build: fix bricked ci

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]

**Comment by tschottdorf** [comment]
image

**Comment by dt** [comment]
fwiw, I don't think this will fix it until `local` is killed too

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17718)*

**Comment by benesch** [comment]
Turns out the container needs to run as root. I have a more targeted approach coming.

**Pull request closed without merging**
