### PR TITLE
sql: add catalog.Mutation interface for table mutations

### PR DESCRIPTION
**Pull request by postamar**
Previously, catalog.TableDescriptor had a method, GetMutations, which
returned a slice of descpb.DescriptorMutation structs, which in turn
contain descpb.IndexDescriptor and descpb.ColumnDescriptor types. This
is an obstacle to our ongoing effort to virtualize column and index
descriptors.

This commit therefore wraps descpb.DescriptorMutation in an interface
type, catalog.Mutation, and also wraps the remaining mutation descriptor
field types:
    - ConstraintToUpdate,
    - PrimaryKeySwap,
    - ComputedColumnSwap,
    - MaterializedViewRefresh.

Release justification: This commit is safe for this release because it
is a low-risk refactor.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I'm thinking we wait for the branch cut on monday. I could see an argument about backports. Have not yet reviewed. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60695#-:-MUqHeW-3skQPTnwcZE9:b-3s7zap)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by postamar** [comment]
Yes this absolutely can wait.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60695#-:-MVPaDOYArJuFPhfnBqd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/sql/catalog/tabledesc/mutation.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60695#-MVP_DLY3nh07dFHffNa:-MVP_DLY3nh07dFHffNb:b-j4ql7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9c8635fafc2181f19e3cd74ed699f8d1a38d94c/pkg/sql/catalog/tabledesc/mutation.go#L131)):*
> ```Go
> // AsColumn returns the corresponding Column if the mutation is on a column,
> // nil otherwise.
> func (m mutation) AsColumn() catalog.Column {
> ```

I look forward to the day that we have the time to really dive deeply into benchmarks to litigate the various tradeoffs of pointer methods for this struct which is gigantic and this method which cannot be inlined because it's called through an interface. That day is likely far away from now. I know it's wrong to worry about it but I can't help it sometimes.

**Review by postamar — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60695#-:-MVWe5wN2kO0WVuacN_h:b-9qdoz3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/sql/catalog/tabledesc/mutation.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60695#-MVP_DLY3nh07dFHffNa:-MVWe7wb6gyR5D5FPE_B:b95d45f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9c8635fafc2181f19e3cd74ed699f8d1a38d94c/pkg/sql/catalog/tabledesc/mutation.go#L131)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I look forward to the day that we have the time to really dive deeply into benchmarks to litigate the various tradeoffs of pointer methods for this struct which is gigantic and this method which cannot be inlined because it's called through an interface. That day is likely far away from now. I know it's wrong to worry about it but I can't help it sometimes. 
</blockquote></details>

I agree, though I suspect you mistook `catalog.Column` with `descpb.ColumnDescriptor` here. In this case this method returns the former, which is backed by a small struct wrapping a pointer to  a `descpb.ColumnDescriptor`, tl;dr `AsColumn` and the like effectively return pointers.

**Pull request merged**
