### PR TITLE
roachprod: improve AWS zone placement

### PR DESCRIPTION
**Pull request by stevendanna**
The fix in cb030cf2 resulted in AWS clusters using the default
configuration being distributed across different zones, whereas
previously such clusters would be placed in a single zone.

Further, for clusters that contained fewer than 3 nodes, the zone
placement code would panic with a divide-by-zero error.

```
panic: runtime error: integer divide by zero
goroutine 80 [running]:
github.com/cockroachdb/cockroach/pkg/roachprod/vm.ZonePlacement(...)
  /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/roachprod/vm/vm.go:416
github.com/cockroachdb/cockroach/pkg/roachprod/vm/aws.(*Provider).Create(0x90e6620, {0xc000455d40, 0x0, 0x2}, {{0xc0006242d0, 0x25}, 0x274a48a78000, 0x0, 0x0, {0xc0018660c0, ...}, ...}, ...)
  /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/roachprod/vm/aws/aws.go:429 +0x7ca
github.com/cockroachdb/cockroach/pkg/roachprod/cloud.CreateCluster.func1({0x64b12d8, 0x90e6620})
  /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/roachprod/cloud/cluster_cloud.go:268 +0x162
github.com/cockroachdb/cockroach/pkg/roachprod/vm.ForProvider({0x7ffc8ca3cc4d, 0x3}, 0xc000748580)
  /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/roachprod/vm/vm.go:372 +0x74
github.com/cockroachdb/cockroach/pkg/roachprod/vm.ProvidersParallel.func1()
  /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/roachprod/vm/vm.go:385 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
  /home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
  /home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x92
```

Here, we make ZonePlacement robust to the case where numNodes <
numZones and also attempt to restore the previous zone-placement
semantics for clusters using the default configuration.

To facilitate this, we no longer set the CreateZones field on the
providerOpts struct and instead rely on the code in Create to use the
default zones when appropriate.

Further, SetupSSH now obtains the required zones from the cluster it
is operating on rather than relying on the provider options.

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
I've tested this locally and it seems to be working for single-cloud clusters.  I'm hitting a problem trying to create a multi-cloud cluster, but it isn't clear to me that the problems I'm hitting (SetupSSH stalls forever at the "scanning hosts" step).

**Comment by tbg** [comment]
Thanks! This is honestly all new code to me so I'm going to try out this branch locally before I review to get a feel for things.

**Comment by tbg** [comment]
Can confirm that multi-cloud doesn't work, filed an issue for dev-inf. https://github.com/cockroachdb/cockroach/issues/74081

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod and @stevendanna)

___
*[pkg/roachprod/vm/aws/aws.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74080#-MrN4O2y7v8b8qSHSzqO:-MrN4O2zAZT9TluFr1tv:b-w90php) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d30f9c037528e3eca74fa04f21d0c2723dde91e/pkg/roachprod/vm/aws/aws.go#L400)):*
> ```Go
> 	}
> 
> 	// We need to make sure that the SSH keys have been distributed to all regions
> ```

nit and I know you just copy pasted that: .

**Comment by stevendanna** [comment]
bors r=tbg

**Pull request merged**
