### PR TITLE
release-19.2: storage: make queue timeouts controllable, snapshot sending queues dynamic

### PR DESCRIPTION
**Pull request by ajwerner**
Backport:
  * 2/2 commits from "storage: make queue timeouts dynamic and add cluster setting for snapshots" (#42686)
  * 2/2 commits from "storage: make queue timeouts controllable, snapshot sending queues dynamic" (#44809)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM. However: 
- on the one    hand I appreciate that you don't want to advertise these change as a user-facing feature in release notes
- OTOH the motivation for back-porting this is that there are real problem in deployments that this is intending to solve. At the very least you should produce a blurb of explanation towards the support engineer, what are the symptoms of the problem and how to apply your solution in practice.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44952#-:-M-oA-OQ2WXGE4DyyVon:bv6rpt5)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — APPROVED** [review]
Maybe put this explanation in the PR description? Both this one and the original one that got merged. I know that TSEs go and look at PRs when they want to understand a change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44952#-:-M-oAJNzBI-2pfrKJAF8:b2e0ebx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
@rmloveland what's the best way for me to document this for backport? Help on how to word the release note would additionally be appreciated.

**Comment by rmloveland** [comment]
ajwerner <notifications@github.com> writes:

> @rmloveland what's the best way for me to document this for backport?

By "document this for backport" do you mean "get this added to the 19.2 docs"?

If so please create an issue and assign it to me at

https://github.com/cockroachdb/docs/issues/new

(Generally, an issue should be automatically created for me by a script that will run once the PR is merged - however you need to add release note comments to the commit messages for that script to pick them up. Also, I'm not 100% confident in the freshness of the data provided by the Github API - I don't think it always picks up things that have been edited / changed.)

> Help on how to word the release note would additionally be appreciated.

I took a shot at it based on scanning the commit messages.  I don't know if two release note messages are needed, but I kind of read them as "separate but related" changes.  However, that may not be true.  You will probably need to edit these for technical accuracy:

- Added a cluster setting `XXX.XXX` to control the timeout for several storage system queues: the Raft snapshot queue, the replication queue, and the merge queue. Setting this to a higher value can be helpful in cases where a queue gets stuck due to e.g. very large ranges, very slow send rates, or a combination of both.

- Fixed a bug where large ranges with slow send rates would hit the timeout in several storage system queues by making the timeout dynamic based on the current rate limit and the size of the data being sent. This affects several storage system queues: the Raft snapshot queue, the replication queue, and the merge queue.

**Comment by ajwerner** [comment]
I added the second release note to the last commit. The setting is not public, so for the moment I'd like to punt on documenting it. I suspect that having it not be public isn't great but it's an escape hatch we shouldn't need to use. If we find ourselves using it, then we should document it.

**Pull request merged**
