### PR TITLE
storage/raft_transport: implement error handling

### PR DESCRIPTION
**Pull request by tamird**
This implements the description of #5789 but doesn't yet use those errors to GC forgotten replicas - I'll do that in a follow-up PR.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7534)

### CODE REVIEW

**Comment by petermattis** [comment]
I'm mildly anxious about the increase in goroutines due to per-replica streams. Did you consider making the `MultiRaft` service stream responses as well? Seems like that could be used to "return" a `RaftMessageResponse` containing an error. I'm still reviewing this change, but wanted to get this thought out there so you could ponder it.

---

Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport.go, line 36 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLW9QXwKJRs2x3riJZs:-KLW9QXxP4tB_YG4PU3v:-1277317088) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L36)):*
> ```Go
> )
> 
> const (
> ```

Can you add some commentary here about this file to guide subsequent readers? I'm thinking of something that explains the purpose of `RaftTransport` (i.e. why we are queueing stuff at all) and the setup of per-replica streams (which implies per-replica pair goroutines). 

---

*[storage/raft_transport.go, line 39 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWAzY56RLcGwg9GbDk:-KLWAzY56RLcGwg9GbDl:1885459334) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L39)):*
> ```Go
> 	// Outgoing messages are queued per-replica on a channel of this size.
> 	raftSendBufferSize = 100
> 	// When no message has been sent to a Node for this duration, the
> ```

`s/Node/Replica/g`

---

*[storage/raft_transport.go, line 41 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWB1JcjrOyfk5TN0LA:-KLWB1JcjrOyfk5TN0LB:689637464) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L41)):*
> ```Go
> 	// When no message has been sent to a Node for this duration, the
> 	// corresponding instance of processQueue will shut down.
> 	raftIdleTimeout = time.Minute
> ```

`s/raftIdle/replicaIdle/g`

I wonder how beneficial it is 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLWAvUfhzYSiLee_QBH:1896170497)*

**Comment by tamird** [comment]
Yeah; I've thought about doing that (FSVO "that"). There are two proposals here:
- Add error information to `RaftMessageResponse` without changing the service definition.
- Add error information to `RaftMessageResponse` and make the stream bidirectional.

If we do the former (without moving to per-replica streams) we will be closing streams (and dropping the associated queues) more often than necessary. If we do the latter, we may need a migration plan to avoid breaking backwards-compatibility (I'm not sure, we might not).

Finally, there might be a throughput advantage to per-replica streams: if gRPC streams wait for an ack on each outgoing message (seems likely, in-order delivery is guaranteed), we are needlessly serializing all messages headed for a given node, while Raft requires only that all messages to a replica are well-ordered.

Happy to discuss more in person, but for now I'm inclined to proceed with per-replica streams.

---

Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport.go, line 36 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLW9QXwKJRs2x3riJZs:-KLWZqP6Z8Uhvtjcr3C1:66581091) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L36)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Can you add some commentary here about this file to guide subsequent readers? I'm thinking of something that explains the purpose of `RaftTransport` (i.e. why we are queueing stuff at all) and the setup of per-replica streams (which implies per-replica pair goroutines). 
</details>
Will do once we settle on how we wish to proceed.

---

*[storage/raft_transport.go, line 39 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWAzY56RLcGwg9GbDk:-KLWZYDqDnGAocYb3T3G:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L39)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/Node/Replica/g`
</details>
Done.

---

*[storage/raft_transport.go, line 41 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWB1JcjrOyfk5TN0LA:-KLWZYqbqzHEIJFcykpb:-203073877) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L41)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/raftIdle/replicaIdle/g`
> 
> I wonder how beneficial it is 
</details>
Yeah, I've thought about removing it in the past but @bdarnell objected IIRC.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLWaCFci28kPBf2nJ-h:-1157737690)*

**Comment by tschottdorf** [comment]
:lgtm:

Can we work on visibility into queues a bit with this change? For example, count the number of times a message was dropped because the queue had filled up. We could keep a stupid counter on `*Replica` which is exposed via `(*Replica).State()`. Everything that's exposed there could be used relatively easily for computing a "badness" of the replica which could be used by, say, the Raft endpoint to move "interesting" ranges up (and even while we don't do that, looking at this number will be more helpful than grep-counting through logs for a noisy message).

---

Reviewed 9 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 5 of 5 files at r7, 5 of 5 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 5 of 5 files at r11, 6 of 6 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 2 of 2 files at r16, 1 of 1 files at r17, 5 of 5 files at r18.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1168 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWks2ePgkHQyb3e5HM:-KLWks2fm6drxxMebjBY:2115339411) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18fcfbf876637794b41f1c4766722c1510cdaad/storage/client_raft_test.go#L1168)):*
> ```Go
> 		}
> 	}).SendAsync(&storage.RaftMessageRequest{
> 		RangeID:     0, // TODO(bdarnell): wtf is this testing?
> ```

I would file this.

---

*[storage/client_raft_test.go, line 1494 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWlA_gfYAhgZ7dMIMe:-KLWlA_hut_dmlfEyUkl:-1661017600) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18fcfbf876637794b41f1c4766722c1510cdaad/storage/client_raft_test.go#L1494)):*
> ```Go
> 	// Simulate an election triggered by the removed node.
> 	mtc.transports[0].MakeSender(func(err error, _ roachpb.ReplicaDescriptor) {
> 		if !testutils.IsError(err, "older than NextReplicaID") {
> ```

If you wait here for that error, can't you remove the Sleep below?

---

*[storage/raft_transport.go, line 264 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLTCRNv2E0rxNpvC_OA:-KLTCRNv2E0rxNpvC_OB:852617136) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d8a9962dbca1b4207d8e5bec375b7bc63adb4b/storage/raft_transport.go#L264)):*
> ```Go
> 		return nil
> 	default:
> 		return errors.Errorf("outbound raft transport queue for %s is full", req.ToReplica)
> ```

I think the ReplicaDescriptor doesn't contain the RangeID, so the message is going to be a little useless.

---

*[storage/raft_transport.go, line 238 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWljGCoI8GQy5p8iDW:-KLWljGCoI8GQy5p8iDX:889135085) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18fcfbf876637794b41f1c4766722c1510cdaad/storage/raft_transport.go#L238)):*
> ```Go
> // SendAsync sends a message to the recipient specified in the request. It
> // returns false if the outgoing queue is full and calls the completion
> // handler when the recipient closes the stream.
> ```

Error handler above, completion handler here. Explain the semantics - is the handler always called on close, can a stream only close with an error, ...?

---

*[storage/raft_transport.go, line 41 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWB1JcjrOyfk5TN0LA:-KLWlU_bxF53jTaw3m-L:-2042547155) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L41)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, I've thought about removing it in the past but @bdarnell objected IIRC.
</details>
Doesn't hurt for a world in which most replicas are idle (if nothing else, to clean up the goroutine view).

---

*[storage/store.go, line 2121 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLTD77XG3AKtXYdfqr_:-KLTD77XG3AKtXYdfqra:-107635885) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d8a9962dbca1b4207d8e5bec375b7bc63adb4b/storage/store.go#L2121)):*
> ```Go
> 		// If getOrCreateReplicaLocked returns an error, log it at V(1)
> 		// instead of returning it (where the caller will log it as
> 		// Error). Errors here generally mean that the sender is out of
> ```

Good place for a TODO for the follow-up change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLWmhz3lVn8IjRv56cU:1376073926)*

**Comment by tamird** [comment]
Sounds good to me; any reason to piggyback on this change? Seems like we can do this in a follow-up using the facilities introduced here.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[storage/client_raft_test.go, line 1168 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWks2ePgkHQyb3e5HM:-KLWwTj0DdActh2geFBg:-64288136) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18fcfbf876637794b41f1c4766722c1510cdaad/storage/client_raft_test.go#L1168)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I would file this.
</details>
Will do after this lands.

---

*[storage/client_raft_test.go, line 1494 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWlA_gfYAhgZ7dMIMe:-KLWtHdZ8Wimz-CZa6OR:-1459681663) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18fcfbf876637794b41f1c4766722c1510cdaad/storage/client_raft_test.go#L1494)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> If you wait here for that error, can't you remove the Sleep below?
</details>
This is a callback, remember?

---

*[storage/raft_transport.go, line 264 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLTCRNv2E0rxNpvC_OA:-KLWw7IAXk3Rl909TJpO:1358448907) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d8a9962dbca1b4207d8e5bec375b7bc63adb4b/storage/raft_transport.go#L264)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I think the ReplicaDescriptor doesn't contain the RangeID, so the message is going to be a little useless.
</details>
Not sure what you mean; the caller knows the range ID (this error is returned synchronously).

---

*[storage/raft_transport.go, line 238 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWljGCoI8GQy5p8iDW:-KLWtRu0btgY5zb_nFLp:2102021310) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18fcfbf876637794b41f1c4766722c1510cdaad/storage/raft_transport.go#L238)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Error handler above, completion handler here. Explain the semantics - is the handler always called on close, can a stream only close with an error, ...?
</details>
Done. The stream closes with an error which may be nil.

---

*[storage/raft_transport.go, line 41 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWB1JcjrOyfk5TN0LA:-KLWvz8xAJL0X8BYBNB0:-557150455) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L41)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Doesn't hurt for a world in which most replicas are idle (if nothing else, to clean up the goroutine view).
</details>
Yep, will add this to the comment @petermattis requested.

---

*[storage/store.go, line 2121 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLTD77XG3AKtXYdfqr_:-KLWwMT14EZfsSuBVwTf:-97064443) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d8a9962dbca1b4207d8e5bec375b7bc63adb4b/storage/store.go#L2121)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Good place for a TODO for the follow-up change?
</details>
Nah, this code is moving around a bit more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLWwrR5T4HSzxf98lHV:2019627583)*

**Comment by tschottdorf** [comment]
Fine by me, as long as it happens. This change might cause new problems as soon as it lands (who knows), that's why I suggested the basic facilities (especially since there's some rearranging that would likely be involved).

---

Reviewed 6 of 6 files at r19, 1 of 1 files at r20, 1 of 1 files at r21, 1 of 1 files at r22, 2 of 2 files at r23, 1 of 1 files at r24, 5 of 5 files at r25.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/client_raft_test.go, line 1494 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWlA_gfYAhgZ7dMIMe:-KLXI6dXLf2vK58ql1Wg:1740059800) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18fcfbf876637794b41f1c4766722c1510cdaad/storage/client_raft_test.go#L1494)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> This is a callback, remember?
</details>
But in the presence of an error (as there should be here (?)), wouldn't you be able to check for it? Won't the completion handler be called in this case?

---

*[storage/raft_transport.go, line 264 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLTCRNv2E0rxNpvC_OA:-KLXIOez-O8G91K2JezC:-1630782482) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d8a9962dbca1b4207d8e5bec375b7bc63adb4b/storage/raft_transport.go#L264)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Not sure what you mean; the caller knows the range ID (this error is returned synchronously).
</details>
good point, I think I thought this was simply being `Warningf`ed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLXHe0Q1atVE9NCeMqQ:1195187018)*

**Comment by arjunravinarayan** [comment]
:lgtm:

Can you expand the commit message? It took me a while to figure out what was going on. #5789's description is a little circuitous, and this PR isn't implementing all of it. The comment @petermattis asked for would also probably help.

---

Reviewed 4 of 9 files at r1, 1 of 1 files at r21, 4 of 5 files at r25.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLXZOszwZgLKpHCNhup:1291582307)*

**Comment by tamird** [comment]
Which commit message?

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/client_raft_test.go, line 1494 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWlA_gfYAhgZ7dMIMe:-KLXdqlYaw6pNMorsEbY:-575128626) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18fcfbf876637794b41f1c4766722c1510cdaad/storage/client_raft_test.go#L1494)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> But in the presence of an error (as there should be here (?)), wouldn't you be able to check for it? Won't the completion handler be called in this case?
</details>
Indeed, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLXdmbJ3RFle90hEIiy:79286745)*

**Comment by arjunravinarayan** [comment]
Sorry, the PR description itself.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLXesiQdKPMT23UAOrv:-1555420624)*

**Comment by tamird** [comment]
Review status: 4 of 10 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport.go, line 36 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLW9QXwKJRs2x3riJZs:-KLYNH403Qm7eiaRgdUB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L36)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Will do once we settle on how we wish to proceed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534)*

**Comment by tschottdorf** [comment]
Thanks for adding the dropped message counter, still :lgtm_strong: 

---

Reviewed 6 of 6 files at r26, 1 of 1 files at r27, 1 of 1 files at r28, 1 of 1 files at r29, 2 of 2 files at r30, 1 of 1 files at r31, 5 of 5 files at r32, 7 of 7 files at r33, 1 of 1 files at r34, 1 of 1 files at r35, 1 of 1 files at r36, 2 of 2 files at r37, 1 of 1 files at r38, 5 of 5 files at r39, 7 of 7 files at r40, 1 of 1 files at r41.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 1631 \[r40\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLYP8tde4vAhuPD8kUL:-KLYP8tde4vAhuPD8kUM:-1316530200) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bb56da82de5802ea13d6247044fce140c0cbb9/storage/replica.go#L1631)):*
> ```Go
> 		r.mu.Unlock()
> 		if err := r.withRaftGroup(func(raftGroup *raft.RawNode) error {
> 			raftGroup.ReportUnreachable(msg.To)
> ```

I know you have it on the radar, but could you add a TODO here? Reporting unreachable may not be what we want to do in case of congestion (or on some random errors).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLYPSIFdafHaSzcK71g:687902168)*

**Comment by tamird** [comment]
Review status: 15 of 16 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 1631 \[r40\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLYP8tde4vAhuPD8kUL:-KLYQVtN-TLX9ii6QUll:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bb56da82de5802ea13d6247044fce140c0cbb9/storage/replica.go#L1631)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I know you have it on the radar, but could you add a TODO here? Reporting unreachable may not be what we want to do in case of congestion (or on some random errors).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534)*

**Comment by petermattis** [comment]
Review status: 15 of 16 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1633 \[r42\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLYwzyIm4WMR66HlJMG:-KLYwzyJpNpsJr0xzAPH:478575616) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d747b8e095c08629239c758a4ed5fa05a04cae/storage/replica.go#L1633)):*
> ```Go
> 		// TODO(tamird): is this the right thing to do? What does it mean to
> 		// "report unreachable"? Now that we have richer error semantics, do
> 		// we want to be more careful about doing this?
> ```

FWIW, the etcd transport code seems to call `ReportUnreachable` when it drops messages.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534)*

**Comment by bdarnell** [comment]
> Finally, there might be a throughput advantage to per-replica streams: if gRPC streams wait for an ack on each outgoing message (seems likely, in-order delivery is guaranteed), we are needlessly serializing all messages headed for a given node, while Raft requires only that all messages to a replica are well-ordered.

Guaranteeing in-order delivery doesn't imply an waiting for an ack for each message (look at TCP windows). Ultimately everything is getting serialized by the single HTTP/2 connection anyway, so I think the performance a single stream should roughly the same as per-replica streams.

I'm also very nervous about the number of goroutines here. Except for the issue of migration, I'd prefer a single stream for all responses. Do we know what the backwards-compatibility story is for adding a streaming response to an existing RPC? (I'm guessing it's not good, but we should check). 

---

Reviewed 3 of 9 files at r1, 1 of 7 files at r33, 1 of 1 files at r35, 3 of 5 files at r39, 6 of 7 files at r40, 1 of 1 files at r41, 1 of 1 files at r42.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[storage/raft.go, line 127 \[r42\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLm7SBRzaSByXUE-I6A:-KLm7SBRzaSByXUE-I6B:1400478164) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d747b8e095c08629239c758a4ed5fa05a04cae/storage/raft.go#L127)):*
> ```Go
> 		logRaftReadyMu.Lock()
> 		defer logRaftReadyMu.Unlock()
> 		log.Infof("store %s: group %s raft ready", storeID, rangeID)
> ```

s/group/range/ in the log message as well.

---

*[storage/raft_transport.go, line 41 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWB1JcjrOyfk5TN0LA:-KLmCtQIqNAcgA595XZb:575309158) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L41)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yep, will add this to the comment @petermattis requested.
</details>
This could be shorter (and probably should, with so many goroutines now), but removing it entirely would probably mean that we'd be creating a new goroutine, etc on almost every message (and does recreating GRPC streams imply extra round-trips? Maybe we'd want to cache the stream but stop the goroutine immediately).

---

*[storage/replica.go, line 1632 \[r42\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLm8N1fmH0x2yXlh5UU:-KLm8N1goEZqFdKXp5uC:-1176065284) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d747b8e095c08629239c758a4ed5fa05a04cae/storage/replica.go#L1632)):*
> ```Go
> 
> 		// TODO(tamird): is this the right thing to do? What does it mean to
> 		// "report unreachable"? Now that we have richer error semantics, do
> ```

We may have richer error semantics, but raft doesn't. `ReportUnreachable` is the only way we can tell raft that something went wrong, and it's the right thing to do any time we can determine that a message raft asked us to send will (probably) not be received. (it shifts raft from an "optimistic" to "pessimistic" mode for that replica. In optimistic mode raft will generate `Append` messages that are smaller because they assume that all prior `Appends` have been processed. Pessimistic mode sends complete `Appends` and waits for an ack before continuing (and switching back to optimistic mode).

---

*[storage/store.go, line 2056 \[r42\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLmCWIYWXaximQkXj1J:-KLmCWIYWXaximQkXj1K:-1618784547) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b3c5d497f4b33c8abdc279c7f7c6f12586b5b1/storage/store.go#L2056)):*
> ```Go
> // tempting to move handleRaftMessage off the processRaft goroutine
> // and rely on processRaftMu instead. However, the interaction with
> // the stopper is tricky. Run handleRaftMessage as a task and we see
> ```

Have these stopper issues been addressed? I think this comment predates the move to streaming RPCs so it may be OK, but we should make sure that the storage package still works under `make stress`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLmEMkR4lZL1fMrOiPx:104928441)*

**Comment by tamird** [comment]
> Do we know what the backwards-compatibility story is for adding a streaming response to an existing RPC?

Don't know yet, but there doesn't seem to be a big advantage to investigating that now - let's cross that scalability bridge when we get to it.

Ditto for the goroutine count concerns - they're valid, but let's deal with that when we get there.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[storage/raft.go, line 127 \[r42\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLm7SBRzaSByXUE-I6A:-KLvcBYld-5kDG6krUHg:967945428) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d747b8e095c08629239c758a4ed5fa05a04cae/storage/raft.go#L127)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/group/range/ in the log message as well.
</details>
https://github.com/cockroachdb/cockroach/pull/7617

---

*[storage/raft_transport.go, line 41 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLWB1JcjrOyfk5TN0LA:-KLvcEw_fS1imtlNjQVC:1301789871) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2100e257e6fa0290cdad1dc9fd2c0d6e0a2ac08/storage/raft_transport.go#L41)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This could be shorter (and probably should, with so many goroutines now), but removing it entirely would probably mean that we'd be creating a new goroutine, etc on almost every message (and does recreating GRPC streams imply extra round-trips? Maybe we'd want to cache the stream but stop the goroutine immediately).
</details>
caching the stream indefinitely seems bad as well. We can investigate stop-gaps if we discover that they're needed, but I'd like to keep the goalpost at "evented" for now.

---

*[storage/replica.go, line 1632 \[r42\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLm8N1fmH0x2yXlh5UU:-KLvcoj32-Um9qfsKJ5l:967945429) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d747b8e095c08629239c758a4ed5fa05a04cae/storage/replica.go#L1632)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> We may have richer error semantics, but raft doesn't. `ReportUnreachable` is the only way we can tell raft that something went wrong, and it's the right thing to do any time we can determine that a message raft asked us to send will (probably) not be received. (it shifts raft from an "optimistic" to "pessimistic" mode for that replica. In optimistic mode raft will generate `Append` messages that are smaller because they assume that all prior `Appends` have been processed. Pessimistic mode sends complete `Appends` and waits for an ack before continuing (and switching back to optimistic mode).
</details>
https://github.com/cockroachdb/cockroach/pull/7618

---

*[storage/store.go, line 2056 \[r42\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-KLmCWIYWXaximQkXj1J:-KLvcq1gJ62uNA2BrHtn:297884919) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7b3c5d497f4b33c8abdc279c7f7c6f12586b5b1/storage/store.go#L2056)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Have these stopper issues been addressed? I think this comment predates the move to streaming RPCs so it may be OK, but we should make sure that the storage package still works under `make stress`. 
</details>
Yep, I believe they have - this change got its own commit; the commit message addresses that directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7534#-:-KLvd0NFOEFdTku0nBrx:1067892386)*

**Pull request merged**
