### PR TITLE
build: encode LDFLAGS into target toolchains

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by tamird** [comment]
cc @tschottdorf

**Comment by benesch** [comment]
:lgtm:

Out of curiosity, where do we actually build with TYPE=musl? I grepped and found nothing.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14860#-:-KhYnJh3DOVRhbyM9L2y:b-wnno9p)*

**Comment by tamird** [comment]
Nowhere, except when @tschottdorf does it manually (https://github.com/cockroachdb/cockroach/issues/14837)

**Comment by benesch** [comment]
Ha! Sounds good.

**Pull request merged**
