### PR TITLE
opt: rework cascade execbuilder tests

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: add cascade_opt execbuilder test

Copy the `cascade` test file. In a subsequent commit, `cascade` will test the
legacy path and `cascade_opt` will test the opt-driven path (similar to the
logictests).

Release note: None

#### opt: rework cascade execbuilder tests

Reworking the cascade_opt tracing tests to work with the new path.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49212#-:-M7nOKuwApsvlmxKEx9z:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/testdata/cascade_opt, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49212#-M7nNYQ03OwPU5QJ4x4A:-M7nNBLL94jI71A1mzfZ:b-k2a61j) ([raw file](https://github.com/cockroachdb/cockroach/blob/72f49bd6bdf64e2b74b44c3d96be45886d7b9802/pkg/sql/opt/exec/execbuilder/testdata/cascade_opt#L28)):*
> ```
>   id STRING PRIMARY KEY,
>   delete_cascade STRING NOT NULL REFERENCES a ON DELETE CASCADE,
>   FAMILY (id, delete_cascade)
> ```

why do you need FAMILY here but not in the legacy path? Maybe add a comment.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49212#-:-M7nRGHJAIdtHFoTi7mV:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/cascade_opt, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49212#-M7nNYQ03OwPU5QJ4x4A:-M7nRHbo1fsM9BogaKwv:b-z9s66m) ([raw file](https://github.com/cockroachdb/cockroach/blob/72f49bd6bdf64e2b74b44c3d96be45886d7b9802/pkg/sql/opt/exec/execbuilder/testdata/cascade_opt#L28)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why do you need FAMILY here but not in the legacy path? Maybe add a comment.
</blockquote></details>

The old test was just counting the number of `cascading` messages (which are per-row in the legacy path). Our testcases here include the actual KV operations which depend on families.

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49212)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/opt/exec/execbuilder/testdata/cascade_opt, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49212#-M7nNYQ03OwPU5QJ4x4A:-M7nSlMR9-nX5mtZ7VR5:b-p8mkwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/72f49bd6bdf64e2b74b44c3d96be45886d7b9802/pkg/sql/opt/exec/execbuilder/testdata/cascade_opt#L28)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The old test was just counting the number of `cascading` messages (which are per-row in the legacy path). Our testcases here include the actual KV operations which depend on families.
</blockquote></details>

Ok makes sense - thanks.

**Pull request merged**
