### PR TITLE
kv: fix deadlock when running with --verbosity=2

### PR DESCRIPTION
**Pull request by tamird**
See individual commits.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6181)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[kv/range_cache.go, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6181#-KFounP94F1VRKI0lA4w:-KFounP94F1VRKI0lA4x:444884226) ([raw file](https://github.com/cockroachdb/cockroach/blob/8acaf086d54d78f1ad304dcc829adfe23e8bf95c/kv/range_cache.go#L284)):*
I don't think this is correct. I'm almost positive it introduces a race condition where multiple requests can miss the cache but not join the same request. Do you mind explaining your reasoning here?

You can see Ben and my discussion about this locking [here](https://github.com/cockroachdb/cockroach/pull/5627).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6181)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[kv/range_cache.go, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6181#-KFounP94F1VRKI0lA4w:-KFoyYUQgOsR8tqypyUi:1941642379) ([raw file](https://github.com/cockroachdb/cockroach/blob/8acaf086d54d78f1ad304dcc829adfe23e8bf95c/kv/range_cache.go#L284)):*
Reverted this bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6181)*

**Comment by bdarnell** [comment]
LGTM

**Comment by nvanbenschoten** [comment]
LGTM

**Pull request merged**
