### PR TITLE
sql: limit virtual tables to current database

### PR DESCRIPTION
**Pull request by jordanlewis**
In postgres, the contents of tables in the `pg_catalog` and `information_schema` databases are limited to entries relating to the current database and system databases. This commit limits our implementation of these tables in the same way, unless the current user is root.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11694)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/information_schema.go, line 540 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KXl_R51-iHj6okr-g6s:-KXl_R520QgLpGcJc-g5:b-b7u1jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/359a118492dcd1c4d72fd7740268b8a11d93abd4/pkg/sql/information_schema.go#L540)):*
> ```Go
> 		_ tableLookupFn,
> 	) error {
> 		if db.Name == p.evalCtx.Database ||
> ```

How do we want this to behave if a user has no current database set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694)*

**Comment by jordanlewis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/information_schema.go, line 540 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KXl_R51-iHj6okr-g6s:-KXlbWHFqFHdmiFxamPD:bvogswc) ([raw file](https://github.com/cockroachdb/cockroach/blob/359a118492dcd1c4d72fd7740268b8a11d93abd4/pkg/sql/information_schema.go#L540)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How do we want this to behave if a user has no current database set?
</blockquote></details>

It seems reasonable to me that only system tables will be returned. I believe this is the current behavior.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/information_schema.go, line 540 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KXl_R51-iHj6okr-g6s:-KXzT6MGhY_2e2YTwKS4:bemq2g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/359a118492dcd1c4d72fd7740268b8a11d93abd4/pkg/sql/information_schema.go#L540)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It seems reasonable to me that only system tables will be returned. I believe this is the current behavior.
</blockquote></details>

Ok, do we assert this behavior in tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694)*

**Comment by jordanlewis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/information_schema.go, line 540 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KXl_R51-iHj6okr-g6s:-KXzlXuQa3QH6NzYJbQW:b-69x836) ([raw file](https://github.com/cockroachdb/cockroach/blob/359a118492dcd1c4d72fd7740268b8a11d93abd4/pkg/sql/information_schema.go#L540)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Ok, do we assert this behavior in tests?
</blockquote></details>

Good point, done. This testing actually uncovered some issues with the patch. I moved this check into `forEachTableDescWithTableLookup` so that `pg_constraint` and `pg_depend` and some tables from `information_schema` also behave correctly. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694)*

**Comment by jordanlewis** [comment]
Rebased (and reworked) this on top of #10196. I decided the easiest way to unify these two patches was a combination of temporarily setting the current database in the `SHOW` statements to the target database, and allowing the root user to see every row in the system tables - not just those from the current database. PTAL.

**Comment by knz** [comment]
I may be confused about what we're doing here, but it seems that the crux of the visibility criterion is whether the target database is the current database in the session. 

What prevents a user from using "SET DATABASE = 'XXX'" to a database where the user has no permission and then seeing all its schema? Is that compatible with what you're trying to achieve?

---

Reviewed 3 of 6 files at r5.
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/information_schema.go, line 558 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJnuWN4tJhVDroSVaf:-KYJnuWNErB4jxzj8uie:b-utfg00) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6f048ab85b9ac67ab26b8a2bf9fa86ecfc2be3d/pkg/sql/information_schema.go#L558)):*
> ```Go
> // isSystemDatabaseName returns true if the input name is not a user db name.
> func isSystemDatabaseName(name string) bool {
> 	return name == informationSchemaName || name == pgCatalogName || name == sqlbase.SystemDB.Name
> ```

I'd see a switch here or a loop with a table rather than this disjunction which is bound to become larger and unwieldable.

---

*[pkg/sql/information_schema.go, line 640 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJo1q96_XXUCAqcmZT:-KYJo1q92ohl7JtPFL_M:b-5atpuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6f048ab85b9ac67ab26b8a2bf9fa86ecfc2be3d/pkg/sql/information_schema.go#L640)):*
> ```Go
> 	sort.Strings(dbNames)
> 	for _, dbName := range dbNames {
> 		if p.session.User != security.RootUser &&
> ```

I'd capture this entire condition in a helper function `(*planner).isDatabaseVisible(dbName)`.

---

*[pkg/sql/testdata/information_schema, line 641 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJoK9UEhQn1jiWTSHS:-KYJoK9U5BR0flANWUfQ:b-154jp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6f048ab85b9ac67ab26b8a2bf9fa86ecfc2be3d/pkg/sql/testdata/information_schema#L641)):*
> ```
> def                 constraint_column  primary          def            constraint_column  t3          rowid        1                 NULL
> 
> # TODO(nvanbenschoten) blocked on #8497.
> ```

I think #8497 has been solved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-:-KYJoii87LU_viSUinBY:b-89i7d5)*

**Comment by knz** [comment]
LGTM otherwise btw. 

---

Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-:-KYJp3Y88WE_MQU29wnm:bgvikuc)*

**Comment by jordanlewis** [comment]
There's nothing preventing a user from doing that right now, but it's still compatible with the goal of this patch, which is enabling sufficient compatibility with postgres behavior to allow OID casts to work consistently. In postgres, I don't think users can connect to arbitrary databases, FWIW.

TFTR!

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/information_schema.go, line 558 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJnuWN4tJhVDroSVaf:-KYJqGCKDElP4ObILiMC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6f048ab85b9ac67ab26b8a2bf9fa86ecfc2be3d/pkg/sql/information_schema.go#L558)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd see a switch here or a loop with a table rather than this disjunction which is bound to become larger and unwieldable.
</blockquote></details>

Done.

---

*[pkg/sql/information_schema.go, line 640 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJo1q96_XXUCAqcmZT:-KYJrQor8sS7YinTW40P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6f048ab85b9ac67ab26b8a2bf9fa86ecfc2be3d/pkg/sql/information_schema.go#L640)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd capture this entire condition in a helper function `(*planner).isDatabaseVisible(dbName)`.
</blockquote></details>

Done.

---

*[pkg/sql/testdata/information_schema, line 641 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJoK9UEhQn1jiWTSHS:-KYJrUSjAtS3TAakN_l3:b-u3f05f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6f048ab85b9ac67ab26b8a2bf9fa86ecfc2be3d/pkg/sql/testdata/information_schema#L641)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think #8497 has been solved.
</blockquote></details>

I fixed this in a different PR. I'll pick up in a rebase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-:-KYJpb-O92hcXj0Jv7qe:b87a8iy)*

**Comment by jordanlewis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/testdata/information_schema, line 641 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJoK9UEhQn1jiWTSHS:-KYJtGB4CDPW9HNEXFHV:bbj5jex) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6f048ab85b9ac67ab26b8a2bf9fa86ecfc2be3d/pkg/sql/testdata/information_schema#L641)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I fixed this in a different PR. I'll pick up in a rebase.
</blockquote></details>

Err, no I didn't. Fixed - thanks for catching this!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r7, 5 of 7 files at r8.
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/information_schema.go, line 558 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJnuWN4tJhVDroSVaf:-KYJuEVWCKGlA4hyjv9b:b735d5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6f048ab85b9ac67ab26b8a2bf9fa86ecfc2be3d/pkg/sql/information_schema.go#L558)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about:
```go
switch name {
   case informationSchemaName:
   case pgCatalogName:
   case sqlbase.SystemDB.Name:
   default:
     return false
}
return true
```

---

*[pkg/sql/logic_test.go, line 402 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJuUex4eIZ7tNWgEpc:-KYJuUexE3bNsth5Whah:b-9nm5ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/a63b8bf46d4b2af2eec8d97b2f6fc6a7eb910a64/pkg/sql/logic_test.go#L402)):*
> ```Go
> 			if inDBName != outDBName {
> 				// Propagate the DATABASE setting to the newly-live connection.
> 				if _, err := t.db.Exec(fmt.Sprintf("SET DATABASE = '%s'", inDBName)); err != nil {
> ```

I don' think this change is useful/necessary. (If you really care about escaping special chars in the db name then you'd need sqlEscape or something.
(or this perhaps a base change? Hard to tell.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694)*

**Comment by jordanlewis** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/information_schema.go, line 558 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJnuWN4tJhVDroSVaf:-KYJvHKs4UdJ8YllUmb_:bb0hth2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6f048ab85b9ac67ab26b8a2bf9fa86ecfc2be3d/pkg/sql/information_schema.go#L558)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What about:
```go
switch name {
   case informationSchemaName:
   case pgCatalogName:
   case sqlbase.SystemDB.Name:
   default:
     return false
}
return true
```
</blockquote></details>

Much better thanks!

---

*[pkg/sql/logic_test.go, line 402 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694#-KYJuUex4eIZ7tNWgEpc:-KYJvIW9Ce0jytcnCM2B:bklzpio) ([raw file](https://github.com/cockroachdb/cockroach/blob/a63b8bf46d4b2af2eec8d97b2f6fc6a7eb910a64/pkg/sql/logic_test.go#L402)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don' think this change is useful/necessary. (If you really care about escaping special chars in the db name then you'd need sqlEscape or something.
(or this perhaps a base change? Hard to tell.)
</blockquote></details>

The reason this is necessary is that the database name can be empty in tests. If that's the case, this line will fail without the extra quoting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11694)*

**Comment by knz** [comment]
oh okthx

**Pull request merged**
