### PR TITLE
roachtest: schemachange/mixed-versions: check version for JSON types

### LINKED ISSUE #101274: roachtest: schemachange/mixed-versions failed
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9554109?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9554109?buildTab=artifacts#/schemachange/mixed-versions) on master @ [582880ae2bb5d08e83a9871735deeeb3ed892e7d](https://github.com/cockroachdb/cockroach/commits/582880ae2bb5d08e83a9871735deeeb3ed892e7d):

```
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
(cluster.go:1981).Run: output in run_055007.099947692_n1_workload-run-schemac: ./workload run schemachange --verbose=1 --max-ops 100 --concurrency 5 {pgurl:1-4} returned: parallel execution failure: COMMAND_PROBLEM: ssh verbose log retained in ssh_055007.882704340_n1_workload-run-schemac.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-26888

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the mixed version test could generate SQL not valid in a mixed version state with JSON types in indexes. To address this, this patch adds a version check for validating that these indexes are supported.

Fixes: #101274, #101409, #101514

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Can you also make this commit fix #101409 and #101514 please?

**Comment by fqazi** [comment]
> Can you also make this commit fix #101409 and #101514 please?

Done @renatolabs

**Review by chengxiong-ruan — APPROVED** [review]

**Comment by renatolabs** [comment]
> > Can you also make this commit fix #101409 and #101514 please?
> 
> Done @renatolabs

Sadly GitHub's syntax for closing multiple issues requires repeating the `fixes` or `resolves` keyword (source: <https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword>).

**Comment by fqazi** [comment]
TFTR @chengxiong-ruan @renatolabs 

bors r+

**Pull request merged**
