### PR TITLE
sql: Add full support for RANGE mode for window frames.

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds support for 'value' PRECEDING and 'value' FOLLOWING types
of bounds for window frames.

Incremental change towards: #27100.

Release note (sql change): CockroachDB now fully supports
RANGE mode for specification of window frames.

### CODE REVIEW

**Comment by yuzefovich** [comment]
cc @solongordon @asubiotto if you guys are interested.

**Comment by yuzefovich** [comment]
PostgreSQL doesn't implement these options, so I had no example to look at in terms of expected behavior for some types of queries. Namely, I think it only makes sense if we use RANGE mode with values only if rows are sorted foremost in ascending order on the column over which aggregation takes place (if such ordering is not provided, I believe we should return an error).

This check is currently incomplete (I do not verify whether ordering is on that required column) because I couldn't figure that out :/ Any advice on how to approach that would be very appreciated.

**Comment by knz** [comment]
I currently don't have time for a detailed code review but a few general thoughts come to mind:

1. if postgres doesn't support this, any idea why? we could perhaps learn something important if the choice was based on some reasoning.
2. what other SQL engines do support this feature? If any do, please refer to them in the release note. If none do, please indicate this is a CockroachDB-specific extension in the release note.
3. this PR is adding a new feature to support. Yet the distributed execution mechanisms are not yet implemented for window functions. Is this PR the right thing to do now? It adds complexity in the distsql implementation task even though that task has not yet been started.

**Comment by yuzefovich** [comment]
Thanks for the questions. Here are my thoughts:

1. PG decided not to include support full support of RANGE mode in Release 9 due to buggy implementation and shortage of time before release, so they cut this feature out. There is a big discussion went on in here: https://www.postgresql.org/message-id/flat/e08cc0400912310149me7150cek3c9aa92e4d396ac3%40mail.gmail.com

However, they intend on fully supporting window functions according to SQL:2011 standard in Release 11 (3rd quarter of 20180, see https://www.postgresql.org/about/news/1855/ In SQL:2011 new mode GROUPS and frame_exclusion clause were introduced (https://www.postgresql.org/docs/11/static/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS).

Regarding the question about requiring ordering on the column, it seems that both PG and Oracle require that the ordering be on a single column over which aggregation takes place which is basically what I was suggesting.

2. According to Wikipedia, "Only Oracle, DB2, Spark/Hive, and Google Big Query fully implement" window functions. I'll make sure to update the release note if we decide to proceed with PR.

3. I think this feature won't make the distsql implementation significantly more difficult, but I agree with you that we should probably leave this PR for now, and I should switch to distsql. I worked on this as my free Friday project and wanted to get some input from you guys. But this can wait. Is there a label I should attach to this PR to indicate that it is currently being "postponed"?

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-:-LG5ugY17gaWEbHrsKUf:b84efye)*

**Comment by knz** [comment]
Thanks for mentioning the free Friday thing and the story with pg. I think it's actually all right to proceed with this PR if you're confident the distsql work will not be impeded significantly, especially if you're volunteering to ensure this yourself 😁

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yuzefovich** [comment]
Currently, it seems to me that I should be able to extract all window function logic from local to distsql relatively easily (at least with the obvious approach I want to implement first when a node will get all the rows in the partition, i.e. without considering inter-partition distribution) since the node on which execution of a window function is scheduled will have access to all the same data as if it were performing local sql execution.

Since we want to merge two execution engines into one, I think it might make sense actually not to merge this PR as a part of local engine but, instead, use it in distsql right away. In any case, the reviews would be beneficial, but they are not urgent.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-:-LG6M4AK3vGwupv8A86W:buaak7l)*

**Comment by nvanbenschoten** [comment]
The amount of new code here really isn't bad. I'd suggest we push forward with this.

---

Reviewed 6 of 7 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/window.go, line 745 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LGOCqfg67ztIocAD0Um:-LGOCqfg67ztIocAD0Un:bhh88vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319132e91e530ff9342f9fab5c30e33f4734722/pkg/sql/window.go#L745)):*
> ```Go
> 				// so we actually don't require a particular ordering.
> 				if windowFn.columnOrdering == nil ||
> 					windowFn.columnOrdering[0].Direction != encoding.Ascending {
> ```

We could support a descending sort order fairly trivially, right? It would just require threading in that information to the correct place. Might not be worth it.

---

*[pkg/sql/sem/tree/window_funcs.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LGOBwPIAi7sonOB-sOL:-LGOBwPIAi7sonOB-sOM:b9es3ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319132e91e530ff9342f9fab5c30e33f4734722/pkg/sql/sem/tree/window_funcs.go#L59)):*
> ```Go
> 	case *DDecimal:
> 		value := &DDecimal{}
> 		tmpDec := &DDecimal{}
> ```

Can these be the same `DDecimal`?

---

*[pkg/sql/sem/tree/window_funcs.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LGOCiJeAq_Omj7JeLvm:-LGOCiJeAq_Omj7JeLvn:b-p5j6r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319132e91e530ff9342f9fab5c30e33f4734722/pkg/sql/sem/tree/window_funcs.go#L64)):*
> ```Go
> 		return value, err
> 	default:
> 		return DNull, pgerror.NewErrorf(pgerror.CodeWindowingError, "non-numerical column provided for windowing with logical offset in RANGE mode")
> ```

Is this a restriction PG will have when they release RANGE support?

---

*[pkg/sql/sem/tree/window_funcs.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LGOC665BvKX7_PbWUTw:-LGOC666BMntTYeuGidz:b5m2gq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319132e91e530ff9342f9fab5c30e33f4734722/pkg/sql/sem/tree/window_funcs.go#L85)):*
> ```Go
> 				panic(fmt.Sprintf("error received: %v", err))
> 			}
> 			low, high := 0, wfr.RowIdx
> ```

Can `sort.Search` be used here to perform the binary search?

Same question for the 3 other cases below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-:-LGOC_QyEYCbPyUrKx_0:b3lrog)*

**Comment by yuzefovich** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/window.go, line 745 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LGOCqfg67ztIocAD0Um:-LGQWRzm7bzY2xx0jpuH:b-t2488u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319132e91e530ff9342f9fab5c30e33f4734722/pkg/sql/window.go#L745)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We could support a descending sort order fairly trivially, right? It would just require threading in that information to the correct place. Might not be worth it.
</blockquote></details>

Yes, we could (and I think PG will support that), but I'm having trouble understanding what would that mean in `value PRECEDING/FOLLOWING` context. For example, we have three rows in DESC order, say with values 3, 2, 1. Current row is 2, and frame start is `1 PRECEDING`. Would that include row with 3 in the frame (in a sense we would have negative offset)? Or would frame start from the row with 1, but then it would not be 'preceding' per se. I didn't find any relevant info about that in PG docs and the specification. Also, there is an option of ordering `USING operator`, but it looks like we don't support that.

---

*[pkg/sql/sem/tree/window_funcs.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LGOBwPIAi7sonOB-sOL:-LGQJftX7Fh8JiNtiBX1:bp0rmc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319132e91e530ff9342f9fab5c30e33f4734722/pkg/sql/sem/tree/window_funcs.go#L59)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can these be the same `DDecimal`?
</blockquote></details>

Yes, I believe so.

---

*[pkg/sql/sem/tree/window_funcs.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LGOCiJeAq_Omj7JeLvm:-LGQM0kN1Ox028WK9dDT:b-8lx1ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319132e91e530ff9342f9fab5c30e33f4734722/pkg/sql/sem/tree/window_funcs.go#L64)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this a restriction PG will have when they release RANGE support?
</blockquote></details>

No, apparently datetime and interval are also possible columns over which RANGE can work. If the column type is either of those, then logical offset "shall be an interval type that may be added to or subtracted from the declared type of SK [sort key]" (per spec SQL:2003). I need to add support for that as well.

---

*[pkg/sql/sem/tree/window_funcs.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LGOC665BvKX7_PbWUTw:-LGQTUWx8RP4tq-1Q10k:b-n9exl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319132e91e530ff9342f9fab5c30e33f4734722/pkg/sql/sem/tree/window_funcs.go#L85)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can `sort.Search` be used here to perform the binary search?

Same question for the 3 other cases below.
</blockquote></details>

Indeed, it can. Thanks for the suggestion :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022)*

**Comment by knz** [comment]
@yuzefovich are you still wanting to merge this eventually? anything I/we should help you with?

**Review by yuzefovich — COMMENTED** [review]
Yes, I definitely want to merge this by the end of my internship, but I decided to postpone work on this for now to work on DistSQL window functions. As far as I can see right now, very minor modifications will be required in DistSQL. I plan to get back to this probably some time next week; in the meantime, if you have time to review this PR, I'd would appreciate it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-:-LI6PiV49mbYLNZ9vBzl:b-szufqi)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
The overall approach LGTM. I'll look again after the rebase and associated fixups.

> Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-:-LI6SJlk2mR9EIQsx37w:b-g68tzn)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
The first commit is in a separate PR, so please ignore it here - I needed those changes to proceed on this one.

I added support for all date-time related calculations. Still question remains whether we want to allow `DESC` ordering of the rows - I do not understand what offsets would mean in that case.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-:-LIqfLZ7-uxVj9JmWBZ2:b-kon2cf)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
@knz @nvanbenschoten I think it is finally ready for review!

**Comment by yuzefovich** [comment]
I finally got a hold of Beta PG 11 with full support of frame specification, so I copied their behavior in case of `DESC` ordering.

I found two discrepancies in the tests from my expectations:
1. PG returns output for query `SELECT sum(price) OVER (ORDER BY ptime RANGE BETWEEN '-1 days' PRECEDING AND '1 days' FOLLOWING) FROM products;`, but not for `SELECT sum(price) OVER (ORDER BY ptime RANGE BETWEEN '-1 hours' PRECEDING AND '1 hours' FOLLOWING) FROM products`. It seems like they take into account that `TIME` is only "up to hours", so negative days have no effect. Not sure whether we want to copy this behavior.
2. PG doesn't output many zeros when printing a value of `DATE` type (unlike we do). Probably it is known difference.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/window, line 1909 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEKkSX5QHzBJCOiAMS:-LJEKkSX5QHzBJCOiAMT:b-66q6kj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/logictest/testdata/logic_test/window#L1909)):*
> ```
>   pDate DATE,
>   pTime TIME,
>   pTimeTZ TIMETZ,
> ```

I saw an issue or a PR to remove support of `TimeTZ`. Should I get rid off it as well?

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-:-LJEvl8V8MINZ3e9VDxF:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/window.go, line 683 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEshcy-fKRtP_Hire9:-LJEshcy-fKRtP_HireA:b-i4e9xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/window.go#L683)):*
> ```Go
> 			if frameRun.RequiresOrdering() {
> 				if len(windowFn.columnOrdering) != 1 {
> 					// TODO: This check is done during type checking. Should we panic?
> ```

It's kind of a weird check to perform during type checking. Perhaps it should only live here. I don't have strong feelings about it.
___
*[pkg/sql/logictest/testdata/logic_test/window, line 1909 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEKkSX5QHzBJCOiAMS:-LJEt1CP2yoWr91ExDDJ:b-euxijm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/logictest/testdata/logic_test/window#L1909)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I saw an issue or a PR to remove support of `TimeTZ`. Should I get rid off it as well?
</blockquote></details>

I'm not sure. @knz?
___
*[pkg/sql/sem/tree/window_funcs.go, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEuR2o27XZ8maJDupg:-LJEuR2o27XZ8maJDuph:bom2gnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/sem/tree/window_funcs.go#L21)):*
> ```Go
> 	"fmt"
> 	"sort"
> ```

nit: remove stray line
___
*[pkg/sql/sem/tree/window_funcs.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEvKxw8DzLyiyiq1tw:-LJEvKxw8DzLyiyiq1tx:b-9sve3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/sem/tree/window_funcs.go#L207)):*
> ```Go
> 			}
> 			if idx < wfr.RowIdx {
> 				// This case is possible when offset == 0.
> ```

Does this mean we're binary searching a larger number of values than we need to?
___
*[pkg/sql/sem/tree/window_funcs_test.go, line 263 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEvWClBKTzRZNhjvEg:-LJEvWClBKTzRZNhjvEh:b8y8qe0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/sem/tree/window_funcs_test.go#L263)):*
> ```Go
> 	partition := indexedRows{rows: make([]indexedRow, count)}
> 	s := rand.NewSource(timeutil.Now().UnixNano())
> 	r := rand.New(s)
> ```

nit: collapse all

```
r := rand.New(rand.NewSource(timeutil.Now().UnixNano()))
```

into 

```
r := rand.New(rand.NewSource(timeutil.Now().UnixNano()))
```

**Review by yuzefovich — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-:-LJF7XDo86uH5hjf3wwu:b-9qdoz3)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 683 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEshcy-fKRtP_Hire9:-LJF49HI1uLjaB5CyRW9:bxkayg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/window.go#L683)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's kind of a weird check to perform during type checking. Perhaps it should only live here. I don't have strong feelings about it.
</blockquote></details>

We need to do type checking based on the ordering column in `RANGE` mode, so we need to make sure there is at least one column, might as well do check for exactly one column. I'll keep the check in `type_check.go` and remove the duplicate check from `window.go`.
___
*[pkg/sql/sem/tree/window_funcs.go, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEuR2o27XZ8maJDupg:-LJF5icp-Ly8SEHc_QfG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/sem/tree/window_funcs.go#L21)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: remove stray line
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/window_funcs.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEvKxw8DzLyiyiq1tw:-LJF6NaaBitD_0Te-9GP:b-y67x86) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/sem/tree/window_funcs.go#L207)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this mean we're binary searching a larger number of values than we need to?
</blockquote></details>

Yes - as far as I understand, there is no way to tell `sort.Search` to start searching from some index other than zero, we can specify only upper bound.

This case is possible when current row has several peers, and with zero offset, the search will find the index of the first peer; however, to the best of my understanding, `value FOLLOWING` cannot offset backwards, so I update it manually. I expanded the comment.
___
*[pkg/sql/sem/tree/window_funcs_test.go, line 263 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEvWClBKTzRZNhjvEg:-LJF7Myl3ad-_39lFjc3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/sem/tree/window_funcs_test.go#L263)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: collapse all

```
r := rand.New(rand.NewSource(timeutil.Now().UnixNano()))
```

into 

```
r := rand.New(rand.NewSource(timeutil.Now().UnixNano()))
```
</blockquote></details>

Done.

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/window_funcs.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEvKxw8DzLyiyiq1tw:-LJF9uva3PLNXxCBdxVc:b-2bhqxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/sem/tree/window_funcs.go#L207)):*
> Yes - as far as I understand, there is no way to tell sort.Search to start searching from some index other than zero, we can specify only upper bound.

But you can do something like:

```
offset := 10
idx = sort.Search(wfr.PartitionSize()-offset, func(i int) bool { return wfr.valueAt(i+offset).Compare(evalCtx, value) >= 0 })
idx += offset
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/window_funcs.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEvKxw8DzLyiyiq1tw:-LJFE1r0E3cXnXuYAFDq:b-10lvoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/sem/tree/window_funcs.go#L207)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Yes - as far as I understand, there is no way to tell sort.Search to start searching from some index other than zero, we can specify only upper bound.

But you can do something like:

```
offset := 10
idx = sort.Search(wfr.PartitionSize()-offset, func(i int) bool { return wfr.valueAt(i+offset).Compare(evalCtx, value) >= 0 })
idx += offset
```
</blockquote></details>

Great suggestion - I didn't think of it.

**Review by nvb — APPROVED** [review]

**Review by yuzefovich — COMMENTED** [review]
@knz @jordanlewis Please let me know if you guys expect to have bandwidth to review this PR this week.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-:-LJo5J_H8HZCs4Y4RoQ-:bo66zx8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 1909 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEKkSX5QHzBJCOiAMS:-LJo5A1PDTOi340DFHqi:bw8ttv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/logictest/testdata/logic_test/window#L1909)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm not sure. @knz?
</blockquote></details>

`TimeTZ` was removed, so I got rid off it as well.

**Review by jordanlewis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 1909 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJEKkSX5QHzBJCOiAMS:-LJp2fFNDYqY5wNwdi_9:b-l9x97j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2b0b099a7578f1759b18de52197709295ae538/pkg/sql/logictest/testdata/logic_test/window#L1909)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`TimeTZ` was removed, so I got rid off it as well.
</blockquote></details>

Yes, get rid of it
___
*[pkg/sql/sem/tree/window_funcs.go, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJp3RjdErHGYWXuje8g:-LJp3RjdErHGYWXuje8h:b-h37dg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e78b60bde42e53d4b5cdc533069bec90ffd22bdd/pkg/sql/sem/tree/window_funcs.go#L74)):*
> ```Go
> 	var ok bool
> 	switch v := wfr.valueAt(wfr.RowIdx).(type) {
> 	case *DInt:
> ```

You can likely avoid all of this code by using the `BinaryExpr` and `BinOp` code. This same pattern is already implemented. I think what you can do is look up the correct BinOp at plan time and reuse it again and again here.

You can do that by creating a `BinaryExpr` with the proper types during planning, running `TypeCheck` on it, and using the `.fn` attribute of that `BinaryExpr`. That attribute is a `BinOp` that has a function inside called `fn` that takes a left and a right datum and evaluates a binary operation. LMK if you have questions on this.

If it's too annoying we can just merge this now and fix later - but add a TODO if you do that.
___
*[pkg/sql/sem/tree/window_funcs.go, line 380 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJp6VWL5DsUCw3Zcqhu:-LJp6VWL5DsUCw3Zcqhv:b-win66r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e78b60bde42e53d4b5cdc533069bec90ffd22bdd/pkg/sql/sem/tree/window_funcs.go#L380)):*
> ```Go
> // do only in RANGE mode with 'value' PRECEDING/FOLLOWING types of bounds.
> func (wfr WindowFrameRun) RequiresOrdering() bool {
> 	return wfr.Frame.Mode == RANGE &&
> ```

Yikes this is an insane condition - I would break it up into a few nested ifs please!

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/window_funcs.go, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJp3RjdErHGYWXuje8g:-LJt0t2T9LSxSXUrx-qY:b-4zz65p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e78b60bde42e53d4b5cdc533069bec90ffd22bdd/pkg/sql/sem/tree/window_funcs.go#L74)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You can likely avoid all of this code by using the `BinaryExpr` and `BinOp` code. This same pattern is already implemented. I think what you can do is look up the correct BinOp at plan time and reuse it again and again here.

You can do that by creating a `BinaryExpr` with the proper types during planning, running `TypeCheck` on it, and using the `.fn` attribute of that `BinaryExpr`. That attribute is a `BinOp` that has a function inside called `fn` that takes a left and a right datum and evaluates a binary operation. LMK if you have questions on this.

If it's too annoying we can just merge this now and fix later - but add a TODO if you do that.
</blockquote></details>

Great suggestion! That part was definitely redundant, and I'm glad there was a way to remove that.
___
*[pkg/sql/sem/tree/window_funcs.go, line 380 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-LJp6VWL5DsUCw3Zcqhu:-LJpCJYL7igfup98KqpK:b-klehzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e78b60bde42e53d4b5cdc533069bec90ffd22bdd/pkg/sql/sem/tree/window_funcs.go#L380)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yikes this is an insane condition - I would break it up into a few nested ifs please!
</blockquote></details>

I added a few methods - this method should now be pretty clear.

**Review by jordanlewis — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 12 files at r3, 11 of 16 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27022#-:-LJt5BJj8Mobs1fO-vs0:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Comment by yuzefovich** [comment]
Thanks for all the comments!

bors r+

**Pull request merged**
