### PR TITLE
importccl: add row_limit option for importing CSVs

### PR DESCRIPTION
**Pull request by mokaixu**
A row_limit option for importing CSVs was added to allow users to specify a fixed
number of rows to import. This provides the ability to do a quick test run for
an import. This functionality is useful for identifying surface level errors without
waiting for a complex import to catch it a long time later.

Now, users can specify `WITH row_limit="2"` to only import 2 rows.

Release Note (sql change): Added `WITH row_limit="{$num}"` option for importing
CSVs to allow users to do a quick test run on an import of $num rows.
Ex. `IMPORT TABLE test ... CSV DATA ... WITH row_limit="3";`

### CODE REVIEW

**Review by mokaixu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/ccl/importccl/read_import_base.go, line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKkOQlu4MuUlBWxOVXT:-MKkOQlu4MuUlBWxOVXU:b-mft00i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a98e8a7bfe46da2d6bed3c6c1a87ba81f9b129e8/pkg/ccl/importccl/read_import_base.go#L555)):*
> ```Go
> 			// Stop when we have processed row limit number of rows.
> 			numRowsToProcess := count - numSkipped
> 			if fileCtx.rowLimit!= 0 && numRowsToProcess > int64(fileCtx.rowLimit) {
> ```

Not sure what to use as the sentinel value for if rowLimit is not configured. There is an error message that shows up if the user puts in a value <=0 so 0 would never be a value unless it's unspecified.

**Review by adityamaru — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @mokaixu)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 1297 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu4F2G-PBZIwFeFgaZ:-MKu4F2G-PBZIwFeFga_:b-qknxlu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/import_stmt_test.go#L1297)):*
> ```Go
> 	sqlDB := sqlutils.MakeSQLRunner(conn)
> 
> 	tests := []struct {
> ```

nice tests!
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu3IlP1a1h_RRqL1AM:-MKu3IlP1a1h_RRqL1AN:bloljkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/import_stmt_test.go#L1362)):*
> ```Go
> 
> 	for _, test := range tests {
> ```

nit: delete \n
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu3_Ef9AAaPzQw244s:-MKu3_Ef9AAaPzQw244t:bloljkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/import_stmt_test.go#L1380)):*
> ```Go
> 				sqlDB.CheckQueryResults(t, test.verifyQuery, test.expected)
> 				sqlDB.Exec(t, `DROP TABLE t`)
> ```

nit: delete \n
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1382 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu3bFk-AMNzg0ehiL9:-MKu3bFk-AMNzg0ehiLA:bloljkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/import_stmt_test.go#L1382)):*
> ```Go
> 
> 			}
> ```

nit: delete \n
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1386 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu3oSP4WFT5-zVFQA9:-MKu3oSP4WFT5-zVFQAA:bpbl9ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/import_stmt_test.go#L1386)):*
> ```Go
> 	}
> 
> 	t.Run("row limit multiple csv", func(t *testing.T) {
> ```

maybe we can have both the CSV files have different length CSV data? might make it more interesting ... or not, up to you :slightly_smiling_face: 
___
*[pkg/ccl/importccl/read_import_base.go, line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKkOQlu4MuUlBWxOVXT:-MKu1xJuEBZqLwFyJhFK:b-gdhgpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a98e8a7bfe46da2d6bed3c6c1a87ba81f9b129e8/pkg/ccl/importccl/read_import_base.go#L555)):*
<details><summary><i>Previously, mokaixu (Monica Xu) wrote…</i></summary><blockquote>

Not sure what to use as the sentinel value for if rowLimit is not configured. There is an error message that shows up if the user puts in a value <=0 so 0 would never be a value unless it's unspecified.
</blockquote></details>

I'm okay with this, it makes sense to me considering we are checking that rowlimit has to be a non-zero positive value.
___
*[pkg/ccl/importccl/read_import_base.go, line 411 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKtzTek7H8WPSCdWCWr:-MKtzTek7H8WPSCdWCWs:b-pdkxin) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/read_import_base.go#L411)):*
> ```
> uint32
> ```
any reason this is a uint32 and not an int64 like skip?
___
*[pkg/ccl/importccl/read_import_base.go, line 411 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu2QvrE3BZHxoZuYjO:-MKu2QvrE3BZHxoZuYjP:b-mx68kj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/read_import_base.go#L411)):*
> ```
> Number of records to process
> ```
nit: Number of records to process before we stop importing from a file.
___
*[pkg/ccl/importccl/read_import_base.go, line 554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu1Qjb8Ba58bsM911y:-MKu1Qjb8Ba58bsM911z:bfyq0nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/read_import_base.go#L554)):*
> ```Go
> 
> 			// Stop when we have processed row limit number of rows.
> 			numRowsToProcess := count - numSkipped
> ```

can we rename this variable to `rowBeingProcessed` or something since it represents the index of the row in the file being processed.
___
*[pkg/roachpb/io-formats.proto, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu-pDE2hHcti9hTGsa:-MKu-pDE2hHcti9hTGsb:bkuojyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/roachpb/io-formats.proto#L61)):*
> ```
> limit the number of rows to import.
> ```
Can we expand this comment to explain the semantics a little more - "If set to a non-zero positive number, this indicates the number of rows that we will import per CSV file"

I think we should pull this option out of the individual file format options considering we are going to support it for all formats. I'll let @miretskiy chime in about what he thinks!

**Comment by adityamaru** [comment]
we can remove the WIP, I think the PR is in good shape!

**Review by mokaixu — COMMENTED** [review]
sgtm :D

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-:-MKuVeZW-qMrPGtj8qOt:b-1pgunc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @miretskiy, and @mokaixu)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 1362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu3IlP1a1h_RRqL1AM:-MKuRGKTDkJDkg1HagLn:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/import_stmt_test.go#L1362)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: delete \n
</blockquote></details>

done
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu3_Ef9AAaPzQw244s:-MKuRIX1CHvaeZWTzzQh:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/import_stmt_test.go#L1380)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: delete \n
</blockquote></details>

done
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1382 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu3bFk-AMNzg0ehiL9:-MKuRJz4846HFZM6fEiV:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/import_stmt_test.go#L1382)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: delete \n
</blockquote></details>

done
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1386 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu3oSP4WFT5-zVFQA9:-MKuSs935Gp8SGiZL6Hf:b-3slly3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/import_stmt_test.go#L1386)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

maybe we can have both the CSV files have different length CSV data? might make it more interesting ... or not, up to you :slightly_smiling_face: 
</blockquote></details>

done! added another csv file to keep things different 
___
*[pkg/ccl/importccl/read_import_base.go, line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKkOQlu4MuUlBWxOVXT:-MKuUuNX3NyOV-byJjVh:bpkgse6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a98e8a7bfe46da2d6bed3c6c1a87ba81f9b129e8/pkg/ccl/importccl/read_import_base.go#L555)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

I'm okay with this, it makes sense to me considering we are checking that rowlimit has to be a non-zero positive value.
</blockquote></details>

awesome
___
*[pkg/ccl/importccl/read_import_base.go, line 411 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKtzTek7H8WPSCdWCWr:-MKuTjRp9YIiqu61hq0p:b-wx9kxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/read_import_base.go#L411)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> uint32
> ```
any reason this is a uint32 and not an int64 like skip?
</blockquote></details>

My intuition to keep unsigned because I thought it would never be negative or super large. 

If that's not the case, should I change it to in64?
___
*[pkg/ccl/importccl/read_import_base.go, line 411 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu2QvrE3BZHxoZuYjO:-MKuUPkl4BnD49ZDQlNr:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/read_import_base.go#L411)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> Number of records to process
> ```
nit: Number of records to process before we stop importing from a file.
</blockquote></details>

done
___
*[pkg/ccl/importccl/read_import_base.go, line 554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu1Qjb8Ba58bsM911y:-MKuUkgf6PWlRFXbos1H:b-3kf74o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/ccl/importccl/read_import_base.go#L554)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

can we rename this variable to `rowBeingProcessed` or something since it represents the index of the row in the file being processed.
</blockquote></details>

yup! that name makes a lot more sense. I modified it to `rowBeingProcessedIdx` to make it clearer it's an index.
___
*[pkg/roachpb/io-formats.proto, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56080#-MKu-pDE2hHcti9hTGsa:-MKuVRK_78fuFd9Y6hQb:bc1fbee) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bc3fb9af6d2f9ac56ff16255be7267f59fc56af/pkg/roachpb/io-formats.proto#L61)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> limit the number of rows to import.
> ```
Can we expand this comment to explain the semantics a little more - "If set to a non-zero positive number, this indicates the number of rows that we will import per CSV file"

I think we should pull this option out of the individual file format options considering we are going to support it for all formats. I'll let @miretskiy chime in about what he thinks!
</blockquote></details>

done! should we pull this out of individual file format options in this PR, or the next one which will also include DELIMITED and AVRO?

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @miretskiy, and @mokaixu)

**Review by adityamaru — APPROVED** [review]

**Comment by mokaixu** [comment]
bors=adityamaru,miretskiy

**Comment by mokaixu** [comment]
bors r=adityamaru,miretskiy

**Comment by mokaixu** [comment]
bors r=adityamaru,miretskiy

**Pull request merged**
