### PR TITLE
roachtest: re-enable cdc/bank

### LINKED ISSUE #72904: roachtest: cdc/bank failed
roachtest.cdc/bank [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3754493&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3754493&tab=artifacts#/cdc/bank) on master @ [2364527e5d5f4df36dfa9bd275601c6305380283](https://github.com/cockroachdb/cockroach/commits/2364527e5d5f4df36dfa9bd275601c6305380283):

```
		(1) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.kafkaManager.createTopic
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:1491
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runCDCBank
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:329
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerCDC.func9
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:840
		  | main.(*testRunner).runTest.func2
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:777
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1581
		Wraps: (2) admin client
		Wraps: (3) kafka: controller is not available
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.errorString

	cluster.go:1952,cdc.go:1415,panic.go:1038,test_impl.go:284,test_impl.go:259,cdc.go:330,cdc.go:840,test_runner.go:777: output in run_101732.031421718_n4_rm: cluster.RunL: context canceled
		(1) attached stack trace
		  -- stack trace:
		  | main.(*clusterImpl).RunE
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2042
		  | [...repeated from below...]
		Wraps: (2) output in run_101732.031421718_n4_rm
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*clusterImpl).RunL
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2050
		  | main.(*clusterImpl).RunE
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2029
		  | main.(*clusterImpl).Run
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1950
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.kafkaManager.stop
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:1415
		  | runtime.gopanic
		  | 	/usr/local/go/src/runtime/panic.go:1038
		  | main.(*testImpl).fatalfInner
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_impl.go:284
		  | main.(*testImpl).Fatal
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_impl.go:259
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runCDCBank
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:330
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerCDC.func9
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cdc.go:840
		  | main.(*testRunner).runTest.func2
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:777
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1581
		Wraps: (4) cluster.RunL
		Wraps: (5) context canceled
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *errors.errorString
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #70386 roachtest: cdc/bank failed [C-test-failure O-roachtest O-robot T-cdc branch-release-21.2]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/bank.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Epic CRDB-11732

Jira issue: CRDB-11339

### PR DESCRIPTION
**Pull request by renatolabs**
This commit re-enables the `cdc/bank` roachtest. This test started
timing out in Nov 29, 2021 (see related issue), and was skipped at the
time. Since then, the test would time out, i.e., it would never reach
the desired number of resolved timestamps in the 30 minutes
allocated. This time out happens even when running the test locally,
so infrastructure is not the bottleneck.

In #69197, this test was re-enabled and was taking less than 10
minutes to run locally. By doing a bisection between that point and
when this test started failing again, it's possible to find out that
pull request #73265 introduced the change that brought this test back
to a failing state.

This commit re-enables the `cdc/bank` roachtest by changing the
`min_checkpoint_frequency` setting to `10s`, following what the tests
under `cdcBasicTest` do. Given the lack of a unified way to create
changefeeds in roachtests (often resorting to error-prone copying and
pasting), this commit also encapsulates the process of creating a
changefeed into a new struct that is now shared across all CDC
roachtests.

Note: some CDC tests were also setting the following settings:

* `changefeed.experimental_poll_interval`
* `kv.closed_timestamp.target_duration`

As these settings were found to have no bearing on whether the test
passes or fails, they were removed in favour of using default settings
unless necessary.

Fixes #72904.

Release justification: test-only change.
Release note: None.

### CODE REVIEW

**Comment by renatolabs** [comment]
I also expected the `min_checkpoint_frequency` option to be documented here: https://www.cockroachlabs.com/docs/stable/create-changefeed.html. Do we know why it's not?

**Review by miretskiy — APPROVED** [review]

**Comment by renatolabs** [comment]
bors r=miretskiy

TFTR!

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86468#-:-NA79HSF9YMpxQob50Xm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1765 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86468#-NA798fcABk9OBu5fAE_:-NA798fcABk9OBu5fAEa:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c251fbbaa3219d94ba12c62449b9bc85e044309f/pkg/cmd/roachtest/tests/cdc.go#L1765)):*
> ```Go
> // changefeedCreator wraps the process of creating a changefeed with
> // different options and sinks
> type changefeedCreator struct {
> ```

Nice!

**Comment by srosenberg** [comment]
> min_checkpoint_frequency

It's a system-only setting [1], and those are not included [2] in the public manual.

[1] https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/streamingccl/settings.go#L49
[2] https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/gen.go#L222

**Pull request merged**
