### PR TITLE
roachtest: add cdc/kafka-auth test

### PR DESCRIPTION
**Pull request by stevendanna**
This new test creates changefeeds using Kafka sinks with TLS and SASL
enabled. To do this, we generate the required TLS certificates and
rewrite the Kafka configuration.

To make it faster to iterate locally, the confluent download now
checks for an existing tarball first. The test is still rather
slow (30s) because of the kafka startup and shutdown time.

The goal of adding this test is to make it easier to accept changes
for new SASL authentication mechanisms.

Release note: None

### CODE REVIEW

**Comment by HonoreDB** [comment]
___
*[pkg/cmd/roachtest/cdc.go, line 1033 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59797#-MSi0AV306JVKx7q863x:-MSi0AV44wbe2glC7U0s:b-mzngmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d64f43895d7c6139eb8df575faef6ae6a7735a0/pkg/cmd/roachtest/cdc.go#L1033)):*
> ```Go
> 	}
> 
> 	err = k.c.PutString(ctx, testCerts.KafkaCert, kafkaCertPath, 0600)
> ```

Duplicate write of the KafkaCert here. Might be worth DRYing this block.

**Comment by stevendanna** [comment]
___
*[pkg/cmd/roachtest/cdc.go, line 1033 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59797#-MSi0AV306JVKx7q863x:-MSi2JcVDo84XW5VTcyF:b-oha9n6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d64f43895d7c6139eb8df575faef6ae6a7735a0/pkg/cmd/roachtest/cdc.go#L1033)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Duplicate write of the KafkaCert here. Might be worth DRYing this block.
</blockquote></details>

:+1: Good call.

**Review by HonoreDB — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59797)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by HonoreDB — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59797#-:-MT2M0lV3G_A2N5VHP6P:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by stevendanna** [comment]
bors r=HonoreDB

**Pull request merged**
