### PR TITLE
bench/ddl_analysis: add a test framework to verify benchmark results

### PR DESCRIPTION
**Pull request by ajwerner**
We have these great benchmarks but nothing to ensure that they don't change in a negative way. This test does just that.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
cc @jordanlewis I think you'll like this.

**Comment by ajwerner** [comment]
@rafiss maybe I can tempt you into reviewing this?

**Review by jordanlewis — COMMENTED** [review]
Looks fine, but we didn't merge something just like this before because we got complaints that failures in these tests are too incomprehensible.

I'm fine with merging this if you add instructions for how to fix it, and include in the instructions some description of when it would and would not be okay to just bump the maximum.

**Comment by jordanlewis** [comment]
Actually I think the tests are more than fine - they are great! Thank you for writing this. Just please address this issue of test updatability.

**Comment by ajwerner** [comment]
Spruced the test up a good bit. The outcome on failure looks like:

```
    validate_benchmark_data_test.go:92: expected VirtualTableQueries/select_crdb_internal.invalid_objects_with_1_fk result in [7, 7], got 8
    validate_benchmark_data_test.go:76: see the --rewrite flag to re-run the benchmarks and adjust the expectations
```

**Review by rafiss — APPROVED** [review]
lgtm! just an optional comment about wording of the error message

this test will be really useful for preventing many problems. thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57660#-:-MO4Ep7FC9p7NIhDFJSv:b-jr5kl8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @solongordon)

___
*[pkg/bench/ddl_analysis/validate_benchmark_data_test.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57660#-MO4EAPe586pKEF29G56:-MO4EAPe586pKEF29G57:brxdqi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/035a3c7b4711676448b600c4a731d0d6472e478d/pkg/bench/ddl_analysis/validate_benchmark_data_test.go#L92)):*
> ```Go
> 		}
> 		if exp.min > r.result || exp.max < r.result {
> 			t.Errorf("expected %s result in [%d, %d], got %d", r.name, exp.min, exp.max, r.result)
> ```

nit: to help readers who haven't seen this test, can the error say something like "expected x KV lookups, got y". that is, instead of "result" specify that the test is looking at number of KV lookups

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r=rafiss

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57660#-:-MO6rdu98FOr3tfwLBfL:b-p9z5el)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/bench/ddl_analysis/validate_benchmark_data_test.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57660#-MO4EAPe586pKEF29G56:-MO6rY-nDN7a9Zq6_Won:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/035a3c7b4711676448b600c4a731d0d6472e478d/pkg/bench/ddl_analysis/validate_benchmark_data_test.go#L92)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: to help readers who haven't seen this test, can the error say something like "expected x KV lookups, got y". that is, instead of "result" specify that the test is looking at number of KV lookups
</blockquote></details>

Done.

**Pull request merged**
