### PR TITLE
sql: gate DateStyle behind datestyle_enabled session variable 

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/exec_util.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68352#-MgELdFn3AwOIal_EQ-r:-MgELdFn3AwOIal_EQ-s:bgfn7cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfbe0fe295cabb3d2e9a7e5bf197391f83310b0b/pkg/sql/exec_util.go#L549)):*
> ```Go
> // always enabled.
> var dateStyleEnabled = settings.RegisterBoolSetting(
> 	"sql.defaults.datestyle.enabled",
> ```

should we not add new "default value for session setting" cluster settings now that we will allow people to have global defaults with `ALTER ROLE ALL SET datestyle_enabled = true`?
___
*[pkg/sql/sem/tree/casts.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68352#-MgEMWbJ00mgwFnCv_3E:-MgEMWbKE9HKlevyp_l2:b-4eu3au) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d847979ab1732bfe3010383b904deeaee3b5e33/pkg/sql/sem/tree/casts.go#L190)):*
> ```Go
> 		volatility: VolatilityStable,
> 		volatilityHint: "TIMESTAMPTZ to STRING casts depend on the current timezone; consider " +
> 			"using to_char_with_style((t AT TIME ZONE 'UTC')::STRING) instead.",
> ```

i think `::STRING` should be removed from this hint

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/exec_util.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68352#-MgELdFn3AwOIal_EQ-r:-MgEx9ayEoBX3XNHGlxM:b-ifhcxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfbe0fe295cabb3d2e9a7e5bf197391f83310b0b/pkg/sql/exec_util.go#L549)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should we not add new "default value for session setting" cluster settings now that we will allow people to have global defaults with `ALTER ROLE ALL SET datestyle_enabled = true`?
</blockquote></details>

hmm, up to you. i rather they all be one or the other tbh, if we decide to do this can it be a later PR? intervalstyle_enabled may deserve the same treatment.
___
*[pkg/sql/sem/tree/casts.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68352#-MgEMWbJ00mgwFnCv_3E:-MgEx98DEx8MCgllBLHr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d847979ab1732bfe3010383b904deeaee3b5e33/pkg/sql/sem/tree/casts.go#L190)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think `::STRING` should be removed from this hint
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm! we can remove/migrate the `sql.defaults` cluster settings for the 22.1 release

**Comment by otan** [comment]
thanks 

bors r=rafiss

**Pull request merged**
