### PR TITLE
sql: fix partial index and foreign key bugs

### LINKED ISSUE #55672: Partial index in combination with foreign keys is broken
**To Reproduce**

1. Set up CockroachDB cluster `20.2-rc.1`.
2. Create two tables with fk reference
```sql
CREATE TABLE a (a INT PRIMARY KEY, delete_time TIMESTAMPTZ DEFAULT NULL, UNIQUE INDEX a (a)
    WHERE delete_time is NULL);
CREATE TABLE b (b INT PRIMARY KEY, a INT NOT NULL, CONSTRAINT fk FOREIGN KEY (a) REFERENCES a(a))
```
3. Insert value into `a`
```sql
INSERT INTO a(a) VALUES (1);
```
4. The next one produces an error
```sql
INSERT INTO b(b,a) VALUES (1,1);
```
`SQL Error [42703]: ERROR: column "delete_time" does not exist`

**Environment:**
 - CockroachDB version `20.2-rc.1`

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: build partial index predicates only when all table columns are in scope

This commit fixes a panic induced by trying to build partial index
predicate expressions without all of a table's columns in-scope. Some
scans, like scans built for foreign key checks, do not include all of a
table's column in their scope. For such scans, optbuilder no longer
attempts to build a partial index predicate because the predicate may
reference a column that is not in scope.

As a result of this change, `opt.TableMeta` may not have a predicate
expression for all partial indexes. The `memo.PartialIndexPredicate`
function which retrieves the predicate expressions has been updated to
account for this case.

Fixes #55672

Release justification: This is a critical bug fix for a new feature,
partial indexes.

Release note (bug fix): An INSERT into a table with a foreign key
reference to a table with a partial index no longer causes an error.

#### sql: disqualify partial unique indexes as foreign key reference indexes

Release justification: This is a critical bug fix for a new feature,
partial indexes.

Release note (bug fix): Foreign keys can no longer reference columns
that are only indexed by a partial unique index. A partial unique index
does not guarantee uniqueness in the entire table, therefore the column
indexed is not guaranteed to be a unique key.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:  Thanks for the quick investigation and fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55702#-:-MK10d_wB5lOW6unKDA8:b-5mfolq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/select.go, line 531 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55702#-MK10AqrE3JNGpYR8K4Y:-MK10AqrE3JNGpYR8K4Z:b-6hxijg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7d2daf60e727846f38943c01278708d7a9fe277/pkg/sql/opt/optbuilder/select.go#L531)):*
> ```Go
> 		// index predicates cannot be built because they may reference columns
> 		// not in outScope.
> 		containsAllOrdinaryTableColumns := true
> ```

[nit] We could skip the loop if we have tab.ColmnCount() columns (which I believe is the common case)

**Comment by andy-kimball** [comment]
If the customer that ran into this issue creates a full index on the column (in addition to existing partial index), would it "fix" their issue? Can we tell them to workaround the problem by doing this?

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55702#-:-MK12RE_EagqvSQrnzGT:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/memo/expr.go, line 909 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55702#-MK10INVE-P8CGYaNgFY:-MK10INW6LeMMbQIKw1r:b-ikc3sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/86bbe7dc3e2a6da21112a0eac1241e1c266455a6/pkg/sql/opt/memo/expr.go#L909)):*
> ```Go
> // Note that TableMeta.PartialIndexPredicates is not initialized for mutation
> // queries. This function will never return ok=true in the context of a mutation.
> func PartialIndexPredicate(
> ```

[nit] Do you need this function anymore? Doesn't seem like it's adding much on top of `TableMeta.PartialIndexPredicates`...

**Comment by RaduBerinde** [comment]
No, they already had one (the PK).

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55702)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/memo/expr.go, line 909 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55702#-MK10INVE-P8CGYaNgFY:-MK1703L8LjEO95fh-yJ:b-8unv5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/86bbe7dc3e2a6da21112a0eac1241e1c266455a6/pkg/sql/opt/memo/expr.go#L909)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] Do you need this function anymore? Doesn't seem like it's adding much on top of `TableMeta.PartialIndexPredicates`...
</blockquote></details>

Good point. It's also used far less with the recent changes to `scanIndexIter`. I've removed it here, but will not remove it in the backport to minimize changes.
___
*[pkg/sql/opt/optbuilder/select.go, line 531 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55702#-MK10AqrE3JNGpYR8K4Y:-MK15Jak-4S716Jo6XaC:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7d2daf60e727846f38943c01278708d7a9fe277/pkg/sql/opt/optbuilder/select.go#L531)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] We could skip the loop if we have tab.ColmnCount() columns (which I believe is the common case)
</blockquote></details>

Good idea. Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 6 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55702#-:-MK1Ahwv5-DYFCmfFwj2:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/optbuilder/select.go, line 531 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55702#-MK1AUq_9NRSVOYIiHRu:-MK1AUq_9NRSVOYIiHRv:byvczhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee3d650f7d038affb91910bc2629e308e130542/pkg/sql/opt/optbuilder/select.go#L531)):*
> ```Go
> 		// index predicates cannot be built because they may reference columns
> 		// not in outScope. In the most common case, the outScope has the same
> 		// number of columns as the table and we can skip checking the each
> ```

[nit] the each -> that each

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55702)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/optbuilder/select.go, line 531 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55702#-MK1AUq_9NRSVOYIiHRu:-MK1FUmc3mZiQwpi0DPm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee3d650f7d038affb91910bc2629e308e130542/pkg/sql/opt/optbuilder/select.go#L531)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] the each -> that each
</blockquote></details>

Done.

**Pull request merged**
