### PR TITLE
storage: fix Pebble.DeleteDirAndFiles

### PR DESCRIPTION
**Pull request by petermattis**
Fix `Pebble.DeleteDirAndFiles` to actually delete the specified
directory. Previously it was only recursively deleting the directory's
contents. Not deleting the directory was causing the `TestDiskQueue` and
`TestSpillingQueue` tests to fail which assert that the queue directory
does not exist at the end of the test.

This fix also addresses a TODO to use a `RemoveAll` function which has
been implemented in `pebble/vfs.FS` for a while.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@asubiotto Does this matter in practice, or does it only affect tests?

**Comment by petermattis** [comment]
> @asubiotto Does this matter in practice, or does it only affect tests?

That is, should this be backported?

**Comment by petermattis** [comment]
CI failure for `TestEngineFSFileNotFoundError`. `Pebble.DeleteDirAndFiles` is not returning an error if the specified directory does not exist.

**Review by itsbilal — APPROVED** [review]
:lgtm: thanks for catching this!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48144#-:-M6581U27nk5Dba6WV-i:b-gglx13)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by petermattis** [comment]
TFTR!

> thanks for catching this!

Thank the unit tests.

bors r+

**Comment by asubiotto** [comment]
> @asubiotto Does this matter in practice, or does it only affect tests?

This does not matter in practice because the flow cleans up leftover directories on `Cleanup`.

**Pull request merged**
