### PR TITLE
authors: add annaw2193 to authors

### PR DESCRIPTION
**Pull request by annaw2193**
Epic: None
Release note: None

### CODE REVIEW

**Review by jlinder — CHANGES_REQUESTED** [review]
The change is good. A few comments on the PR body and commit message.

- The `Release Note` line should be last in the commit message. The parser for them is greedy and takes everything after it as part of the release note. Could you update the commit message to place it last? The [Updating PRs during review](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/2647261318/Updating+PRs+during+review) page discusses how to do this.
- Did one of the linters ask for the `Release justification` line in the PR description? That should only be needed for backport PRs.

Also, this PR looks ready to be moved out of Draft mode. Normally, we used draft mode here to indicate that a PR isn't ready for review yet.

**Comment by annaw2193** [comment]
> The change is good. A few comments on the PR body and commit message.
> 
> * The `Release Note` line should be last in the commit message. The parser for them is greedy and takes everything after it as part of the release note. Could you update the commit message to place it last? The [Updating PRs during review](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/2647261318/Updating+PRs+during+review) page discusses how to do this.
> * Did one of the linters ask for the `Release justification` line in the PR description? That should only be needed for backport PRs.
> 
> Also, this PR looks ready to be moved out of Draft mode. Normally, we used draft mode here to indicate that a PR isn't ready for review yet.

* Sounds good, I will update the commit message. The ordering of the release note line was based on the document provided for the first PR, should I update this document with the `Release note` line last in the commit message instead to reflect this?

* I think I added it because I wasn't sure if it was necessary or not, but no problem I can remove it and I will keep that in mind for future reference

**Review by jlinder — APPROVED** [review]
LGTM 🎉 

> The ordering of the release note line was based on the document provided for the first PR, should I update this document with the Release note line last in the commit message instead to reflect this?

Ah. I see. These guides are updateable. How about putting in a change suggestion on that doc to correct the ordering?

**Comment by annaw2193** [comment]
> LGTM 🎉
> 
> > The ordering of the release note line was based on the document provided for the first PR, should I update this document with the Release note line last in the commit message instead to reflect this?
> 
> Ah. I see. These guides are updateable. How about putting in a change suggestion on that doc to correct the ordering?

sounds good! I've made some suggestions in the doc to reflect this

**Comment by annaw2193** [comment]
r+

**Review by rickystewart — APPROVED** [review]

**Pull request merged**
