### PR TITLE
cli: fix the process exit status codes

### PR DESCRIPTION
**Pull request by knz**
Found by @jbowens in #70637.
We'll want to backport this. cc @joshimhoff 

Release note (bug fix): The exit status of the `cockroach` command
did not follow the previously-documented table of exit status codes
when an error occurred during the command start-up. (Only errors
occuring after startup were reported using the correct code.)
This defect has been fixed. This bug had existed ever since reference
exit status codes had been introduced.

### CODE REVIEW

**Comment by knz** [comment]
blathers backport 21.2

**Comment by knz** [comment]
blathers backport 21.1

**Review by jbowens — APPROVED** [review]
:lgtm: thanks!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70673#-:-MkNLxQDBGV08ZRjZm_D:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

**Comment by knz** [comment]
TFYR!

bors r=jbowens

**Pull request merged**
