### PR TITLE
pgwire: change sql.defaults.results_buffer.size default to 512KiB

### LINKED ISSUE #124049: sql: increase sql.defaults.results_buffer.size default size
The default for `sql.defaults.results_buffer.size` is **16KiB**. This is pretty small. Overflowing this buffer can prevent a transaction from auto-retrying, which is a strong motivation to increase the buffer size, especially under Read Committed transactions which don't expect to see retry errors and aren't prepared to handle them.

We should increase the default value for this setting to something larger, like **512KiB**.

Jira issue: CRDB-38679

Epic CRDB-37763

### PR DESCRIPTION
**Pull request by rafiss**
When this setting was added in PR #32366, the default value did not receive much scrutiny. Using a bigger value is beneficial since it will reduce the chance for clients using READ COMMITTED transactions to hit errors that cannot automatically be retried within CockroachDB. (The reason being that if results were already sent back to the client since the buffer filled up, it's not safe to retry that operation.)

512KiB is still pretty small, but should prevent more errors than the old default of 16KiB.

fixes https://github.com/cockroachdb/cockroach/issues/124049
Release note (sql change): The default value of the sql.defaults.results_buffer.size cluster setting was changed from 16KiB to 512KiB.

### CODE REVIEW

**Comment by rafiss** [comment]
I'm only planning to backport to 24.1 since the main motivation is to make it less likely for READ COMMITTED transactions to hit retryable errors, and 24.1 is the first GA release for READ COMMITTED.

**Review by fqazi — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124580#-:-NyX-TEV917eCO1NOzPJ:b-uwkowd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r+

**Comment by rafiss** [comment]
tftr!

bors r+

**Comment by rafiss** [comment]
fixed up the logic tests, which needed updating since they report the default value

bors r+

**Pull request merged**
