### PR TITLE
ui: migrate statement diagnostics requests to use sql-over-http endpoint

### PR DESCRIPTION
**Pull request by THardy98**
Part of: #89429

Addresses: #90273, #90274, #90275

Blocked from resolving by https://github.com/cockroachdb/cockroach/issues/80789

DB-Console Demo: https://www.loom.com/share/d74c02eb3dfb41fc913577d0e8992441
CC-Console Demo: https://www.loom.com/share/2adba8a53b8c48ac9f031e4481f284cf

This change migrates the existing statement diagnostics requests to use the sql-over-http endpoint on our apiV2, making these requests tenant-scoped once the sql-over-http endpoint is scoped to tenants (this should be the case when #91323 is completed).

### CODE REVIEW

**Review by matthewtodd — APPROVED** [review]
Nice! :lgtm:

> Reviewed 1 of 1 files at r1, 16 of 16 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-:-NGWvW9h8eOKY2XIvqA5:be8rotp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-NGWtUXE3xDAUTwz8Y6p:-NGWtUXE3xDAUTwz8Y6q:bd2ip51) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef369b6333a64914e490b9c3e2147199c277df1/pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts#L43)):*
> ```XML
> 			expires_at
> 		FROM
> 			system.statement_diagnostics_requests
> ```

I'm noticing the tabs here and wondering if we'd want to convert to spaces? (I know tabs for Go, but I think spaces for JS?)
___
*[`pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-NGWs9cXBpm4RBfb810h:-NGWs9cXBpm4RBfb810i:b-nlpqeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef369b6333a64914e490b9c3e2147199c277df1/pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts#L113)):*
> ```XML
>              VALUES (${placeHolders}) RETURNING id as stmt_diag_req_id;`,
>     arguments: args,
>   };
> ```

I like this way of building up the query. Do we have enough other uses that it might be interesting to try to extract some common code for setting up `args`, `cols`, and `placeHolders`? (Though, as I think about it, it might want to turn into a full-blown query builder, which might be ridiculous?)

Not for this PR, just noticing a future direction we could take.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-NGWtsNp4otq90s-rYK5:-NGWtsNp4otq90s-rYK6:b-789r8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef369b6333a64914e490b9c3e2147199c277df1/pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts#L143)):*
> ```XML
> 					completed = false AND
> 					statement_fingerprint = $1 AND
> 					(expires_at IS NULL OR expires_at > now())`,
> ```

Ditto tabs?
___
*[`pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/activateStatementDiagnosticsModal.tsx` line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-NGWunbU-ytX7s-yxu6U:-NGWunbU-ytX7s-yxu6V:b-dvbdbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/87cf790613bf5049fe248bef65f636666a07619a/pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/activateStatementDiagnosticsModal.tsx#L11)):*
> ```XML
> // licenses/APL.txt.
> 
> import { Alert, Button, Checkbox, Divider, Input, Radio, Select } from "antd";
> ```

Yay alphabetizing!

**Review by maryliag — APPROVED** [review]
Great! Just one small nit that you might get a lint error, otherwise :lgtm: 

> Reviewed 1 of 1 files at r1, 16 of 16 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-:-NGX2f8x-x_ycVIg45wp:bqa1qys)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-NGX1R1v-TptkfEDCig_:-NGX1R1v-TptkfEDCiga:b4906mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/87cf790613bf5049fe248bef65f636666a07619a/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts#L19)):*
> ```XML
> import * as protos from "@cockroachlabs/crdb-protobuf-client";
> import { RequestError } from "src/util";
> import {StatementDiagnosticsReport} from "../api";
> ```

I'm surprise you're not getting a lint error here with the missing spaces between `{ StatementDiagnosticReport }`.  Better fix so it doesn't catch on another run after it's merged

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91081)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @maryliag and @matthewtodd)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-NGWtUXE3xDAUTwz8Y6p:-NGXMcQ55EovYZft7PPO:b-n639iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef369b6333a64914e490b9c3e2147199c277df1/pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts#L43)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I'm noticing the tabs here and wondering if we'd want to convert to spaces? (I know tabs for Go, but I think spaces for JS?)
</blockquote></details>

changed to spaces :)
___
*[`pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-NGWs9cXBpm4RBfb810h:-NGXMg1qDxH6jpTFB-eT:bw68lbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef369b6333a64914e490b9c3e2147199c277df1/pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts#L113)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I like this way of building up the query. Do we have enough other uses that it might be interesting to try to extract some common code for setting up `args`, `cols`, and `placeHolders`? (Though, as I think about it, it might want to turn into a full-blown query builder, which might be ridiculous?)

Not for this PR, just noticing a future direction we could take.
</blockquote></details>

Not sure how many uses yet, but I imagine as we continue to leverage the sql-over-http endpoint, a simple function to build a `SqlStatement` that handles placeholders/args would be pretty useful and likely not too difficult.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-NGWtsNp4otq90s-rYK5:-NGXMzNd3U0huJz3V3Db:btzs18r) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef369b6333a64914e490b9c3e2147199c277df1/pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts#L143)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Ditto tabs?
</blockquote></details>

using spaces now :)
___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91081#-NGX1R1v-TptkfEDCig_:-NGXN0xi4QYfbFIgHgMp:bltb7ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/87cf790613bf5049fe248bef65f636666a07619a/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts#L19)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I'm surprise you're not getting a lint error here with the missing spaces between `{ StatementDiagnosticReport }`.  Better fix so it doesn't catch on another run after it's merged
</blockquote></details>

Turns out there's a `/* eslint-disable prettier/prettier */` comment at the top of the file, fixed anyways :)

**Comment by THardy98** [comment]
TYFR :)

**Pull request merged**
