### PR TITLE
Revert "closedts: shorten target_duration from 30s to 5s"

### PR DESCRIPTION
**Pull request by ajwerner**
This reverts commit 3e97e57eef939719d240957d2c8144931fd9b8a3.

The last couple of weeks of experience show that tests become flakey with
the target_duration set to 5s. This isn't overly surprising given that updates
to table descriptors observe their own timestamp and thus can never be
refreshed.

See https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/structured.go#L1496-L1509

References #39643.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
LGTM

**Review by andy-kimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40527#-:-Lo2XOWj7FrdyAMwC1Xb:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
bors r=andy-kimball

**Comment by ajwerner** [comment]
TFTR

**Pull request merged**
