### PR TITLE
sql: add ability to specify computed columns

### PR DESCRIPTION
**Pull request by justinj**
Release note: None

This commit does not include actually inserting or updating computed
columns, and just disallows any writes which involve them. Writing to
them will be in a future PR.

I have a branch where they work, just putting this out first in the interest of splitting it up.

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm: this is great stuff!

---

Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/create_table.go, line 1148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-L3Z8--JlLJAd330Ckae:-L3Z8--KV97x1giN_Klg:bhwo4ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/be66a7deaf5cb1841e37a32efd47022330dd1fea/pkg/sql/create_table.go#L1148)):*
> ```Go
> }
> 
> func iterColDescriptors(
> ```

mention something about expr in this method name. when I read it in context, I expect it to iterate over the columns in `desc` (and so the expr is confusing)

---

*[pkg/sql/create_table.go, line 1207 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-L3Z8Ilkf3B0Ev-gbug0:-L3Z8Ilkf3B0Ev-gbug1:b-wqzgok) ([raw file](https://github.com/cockroachdb/cockroach/blob/be66a7deaf5cb1841e37a32efd47022330dd1fea/pkg/sql/create_table.go#L1207)):*
> ```Go
> 	}
> 
> 	// TODO(justin,bram): allow depending on columns like this.
> ```

include in this TODO why it doesn't work now

---

*[pkg/sql/create_table.go, line 1228 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-L3Z8YB0rNWr7jUz1Smr:-L3Z8YB0rNWr7jUz1Sms:bclnbax) ([raw file](https://github.com/cockroachdb/cockroach/blob/be66a7deaf5cb1841e37a32efd47022330dd1fea/pkg/sql/create_table.go#L1228)):*
> ```Go
> 	}
> 
> 	// We replace column references with typed dummies to allow typechecking.
> ```

super nit: The first two times I read this comment, I saw "We replaced" and didn't understand where that happened. How about "Replace column ..."

---

*[pkg/sql/sqlbase/table.go, line 223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-L3Z9ZHRnAKR2PcZJXBi:-L3Z9ZHRnAKR2PcZJXBj:b-jdw13) ([raw file](https://github.com/cockroachdb/cockroach/blob/be66a7deaf5cb1841e37a32efd47022330dd1fea/pkg/sql/sqlbase/table.go#L223)):*
> ```Go
> 	}
> 
> 	if d.IsComputed() {
> ```

why does the code for columns with DEFAULT have to do typechecking, normalization, etc here but we dont?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-:-L3ZA-yu2JbxJe0zYXxn:b-gl6cot)*

**Comment by justinj** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create_table.go, line 1148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-L3Z8--JlLJAd330Ckae:-L3cxjhQEzn8ilCqfkS5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be66a7deaf5cb1841e37a32efd47022330dd1fea/pkg/sql/create_table.go#L1148)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

mention something about expr in this method name. when I read it in context, I expect it to iterate over the columns in `desc` (and so the expr is confusing)
</blockquote></details>

Done.

---

*[pkg/sql/create_table.go, line 1207 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-L3Z8Ilkf3B0Ev-gbug0:-L3cyf8SFnVyid2XUoNF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be66a7deaf5cb1841e37a32efd47022330dd1fea/pkg/sql/create_table.go#L1207)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

include in this TODO why it doesn't work now
</blockquote></details>

Done.

---

*[pkg/sql/create_table.go, line 1228 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-L3Z8YB0rNWr7jUz1Smr:-L3cykX0lmv8OF7NWKfN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be66a7deaf5cb1841e37a32efd47022330dd1fea/pkg/sql/create_table.go#L1228)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

super nit: The first two times I read this comment, I saw "We replaced" and didn't understand where that happened. How about "Replace column ..."
</blockquote></details>

Done.

---

*[pkg/sql/sqlbase/table.go, line 223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-L3Z9ZHRnAKR2PcZJXBi:-L3czTW1sUZstEhOaNNP:b-pq3e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/be66a7deaf5cb1841e37a32efd47022330dd1fea/pkg/sql/sqlbase/table.go#L223)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

why does the code for columns with DEFAULT have to do typechecking, normalization, etc here but we dont?
</blockquote></details>

Typechecking and normalization for computed columns is actually more similar to that for `CHECK` constraints, since we have to be able to resolve column references like they do. That code lives in `sql/create_table.go` alongside the `CHECK` stuff. But this assertion should actually live there rather than here, good point!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586)*

**Comment by danhhz** [comment]
Reviewed 12 of 15 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586)*

**Comment by jordanlewis** [comment]
:lgtm: Does this properly ban subqueries and other-table statement sources from the computed expression? If so, then I think you're missing some tests for that.

---

Reviewed 9 of 15 files at r1, 1 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-:-L3dT60K1Tj7M01lSGJ_:bjzj8sn)*

**Comment by jordanlewis** [comment]
:thumbsup: 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21586#-:-L3dcAQOcKmlpk4czc5n:b4c9lyr)*

**Pull request merged**
