### PR TITLE
allocator: safe format allocator log messages

### LINKED ISSUE #102948: allocator: implement safe format for all logging
The allocator logging does not implement `SafeFormat` for any log messages in the respective sub-packages.

**Describe the solution you'd like**

This issue is to update logging to implement `SafeFormat` for all associated messages so that these log lines will not be redacted in an redacted log file.

**Additional context**
See https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1824817806/Log+and+error+redactability#API-Basics.

Jira issue: CRDB-27752

### PR DESCRIPTION
**Pull request by kvoli**
See individual commit messages.

Note stringer tests are added in earlier PRs in order to assert against regressions.

Resolves: https://github.com/cockroachdb/cockroach/issues/102948
Release note:  None

### CODE REVIEW

**Review by andrewbaptist — CHANGES_REQUESTED** [review]
Thanks for cleaning this all up! Only once question/concern about whether constraints are considered sensitive, otherwise it all looks good.

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 5 of 5 files at r4, 4 of 4 files at r5, 2 of 2 files at r6, 5 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116295#-:-Nm2nvy96gRIu0BV0WkJ:b5rnp0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 442 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/116295#-Nm2mhwi23ITTOcdfmER:-Nm2mhwi23ITTOcdfmES:b-y9t0rf) ([raw file](https://github.com/cockroachdb/cockroach/blob/54faa163121cdf88adc1aa7927e358dd0badcbb3/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L442)):*
> ```Go
> 		}
> 		b.SafeRune('{')
> 		b.Print(ae.constraints[i])
> ```

I'm concerned that constraints may be considered sensitive data.  We consider database and table names as sensitive data, but this is a little less clear. Who is the right person to make this call?
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer_test.go` line 1677 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/116295#-Nm2kdFa0vaInkgHfvb_:-Nm2kdFa0vaInkgHfvba:bwt02tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bfd79f7a2cd54dddf7f3fe70c40eefbe07b9a93/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer_test.go#L1677)):*
> ```Go
> 		cl = append(cl, candidate{
> 			store:           roachpb.StoreDescriptor{StoreID: roachpb.StoreID(i)},
> 			valid:           i%2 == 0,
> ```

nit: No need to change this, but it might have been easier for all these `i%2` cases to instead have 12 different candidates, and each of them only change one parameter (e.g. - i%12 == 5). The advantage of that approach would be if there were "cross-wired" mappings it would be very obvious.

**Review by kvoli — COMMENTED** [review]
TYFTR -- replied below re: constraints being considered sensitive.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116295#-:-Nm32n71A791-ayvgzyN:bx4wsbw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 442 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/116295#-Nm2mhwi23ITTOcdfmER:-Nm31dBj5D9-qqv7kYbN:b-xn8m1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/54faa163121cdf88adc1aa7927e358dd0badcbb3/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L442)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I'm concerned that constraints may be considered sensitive data.  We consider database and table names as sensitive data, but this is a little less clear. Who is the right person to make this call?
</blockquote></details>

These will be redacted -- as they do not implement a `SafeFormat` or `SafeValue` method which `Print` here checks for.

https://github.com/cockroachdb/cockroach/blob/6fae6a751337e6e3c1f6432f7c31b15d0ba820ac/pkg/roachpb/span_config.go#L139

This behavior hasn't changed, just that the parts around the constraints won't be redacted now.

**Comment by kvoli** [comment]
Should be good for another review round @andrewbaptist.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

**Comment by kvoli** [comment]
TYFTR

bors r=andrewbaptist

**Pull request merged**
