### PR TITLE
roachpb: initial redaction for *roachpb.Error

### PR DESCRIPTION
**Pull request by tbg**
This is a bigger project due to the fact that we need to make
each ErrorDetail a SafeFormatter. This commit sets us up to
mechanically do so without worrying too much about the interplay
with *roachpb.Error any more.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54746)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/roachpb/errors.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54746#-MI-LSWX4AesN-GOXf4D:-MI-LSWZ9Ddp3xqMOfEI:bzfqqmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/658ab04939b26df0d4c3742704e2c8c70c5dde62/pkg/roachpb/errors.go#L163)):*
> ```Go
> func (e *Error) SafeFormat(s redact.SafePrinter, _ rune) {
> 	if e == nil {
> 		s.Print(redact.SafeString("<nil>"))
> ```

This special case might not be needed any more. Have you tried without?
(maybe `SafeFormat` is not even called if the object is nil)
___
*[pkg/roachpb/errors.go, line 863 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54746#-MI-LiWd2P_hYlE_OnVc:-MI-LiWd2P_hYlE_OnVd:b-jhf8bw) ([raw file](https://github.com/cockroachdb/cockroach/blob/658ab04939b26df0d4c3742704e2c8c70c5dde62/pkg/roachpb/errors.go#L863)):*
> ```Go
> 	for i, ot := range observedTimestampSlice(e.ObservedTimestamps) {
> 		if i > 0 {
> 			s.Print(' ')
> ```

s.SafeByte ?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54746)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/roachpb/errors.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54746#-MI-LSWX4AesN-GOXf4D:-MIT5aW2D6r_A6mlNlAB:b-58syu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/658ab04939b26df0d4c3742704e2c8c70c5dde62/pkg/roachpb/errors.go#L163)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This special case might not be needed any more. Have you tried without?
(maybe `SafeFormat` is not even called if the object is nil)
</blockquote></details>

It seems to be needed. When I return early here, I get the empty string out. But I changed it to `s.Print(nil)` which looks a bit more idiomatic.
___
*[pkg/roachpb/errors.go, line 863 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54746#-MI-LiWd2P_hYlE_OnVc:-MIT5oYXCQioW0UCUDCQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/658ab04939b26df0d4c3742704e2c8c70c5dde62/pkg/roachpb/errors.go#L863)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s.SafeByte ?
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54746)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tbg** [comment]
Mind giving this another look? Had another infinite recursion to take care of.

**Review by knz — APPROVED** [review]
Nice catch. I agree we should probably look at #54746 soon.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54746#-:-MIT_Nk97oTyMUzxuv2G:bryzjj2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tbg** [comment]
bors r=knz

**Pull request merged**
