### PR TITLE
sql: deflake TestLogic//crdb_internal/max_retry_counter

### LINKED ISSUE #38062: teamcity: failed test: TestLogic
The following tests appear to have failed on master (test): TestLogic/fakedist: TestLogic/fakedist/crdb_internal, TestLogic/fakedist, TestLogic/fakedist: TestLogic/fakedist/crdb_internal: TestLogic/fakedist/crdb_internal/max_retry_counter, TestLogic

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestLogic).

[#1327655](https://teamcity.cockroachdb.com/viewLog.html?buildId=1327655):

```
TestLogic/fakedist: TestLogic/fakedist/crdb_internal
--- FAIL: test/TestLogic: TestLogic/fakedist: TestLogic/fakedist/crdb_internal (2.170s)

------- Stdout: -------
=== PAUSE TestLogic/fakedist/crdb_internal



TestLogic
--- FAIL: test/TestLogic (428.390s)

------- Stdout: -------
    test_log_scope.go:79: test logs captured to: /tmp/logTestLogic244295760
    test_log_scope.go:60: use -show-logs to present logs inline



TestLogic/fakedist: TestLogic/fakedist/crdb_internal: TestLogic/fakedist/crdb_internal/max_retry_counter
--- FAIL: test/TestLogic: TestLogic/fakedist: TestLogic/fakedist/crdb_internal: TestLogic/fakedist/crdb_internal/max_retry_counter (0.020s)

------- Stdout: -------
--- done: testdata/logic_test/crdb_internal with config fakedist: 78 tests, 1 failures
=== CONT  TestLogic/fakedist/collatedstring_uniqueindex2
=== CONT  TestLogic/fakedist/inet
                logic.go:2336: 
                     
                    testdata/logic_test/crdb_internal:434: SELECT key, (max_retries > 1), flags LIKE '!%' AS f
                      FROM crdb_internal.node_statement_statistics
                     WHERE application_name = 'test_max_retry'
                    ORDER BY key, f
                    expected:
                        SELECT crdb_internal.force_retry(_)  true  false
                        SELECT crdb_internal.force_retry(_)  true  true
                        SET application_name = DEFAULT       false false
                    but found (query options: "") :
                        SELECT crdb_internal.force_retry(_)  false  false
                        SELECT crdb_internal.force_retry(_)  false  true
                        SET application_name = DEFAULT       false  false
                        
                    



TestLogic/fakedist
--- FAIL: test/TestLogic: TestLogic/fakedist (0.850s)





```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by knz**
Fixes #38062.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
half a second seems... not great to me. I think it's time to introduce an overload that generates an error non-conditionally, and use a sequence and `next_val()` to have the statement only be retried once. What do you think?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38397#-:-LiEEbGk7eU51vjckEl3:bf8dkxw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by knz** [comment]
What I think is that it sounds reasonable, but then don't you think I should also edit the tests in `txn` and `manual_retry` to do the same?

**Comment by andreimatei** [comment]
by all means :)

**Comment by knz** [comment]
Done.
PTAL

**Comment by andreimatei** [comment]
LGTM

thanks!

**Comment by knz** [comment]
TFYR!
bors r+

**Pull request merged**
