### PR TITLE
go.mod: bump Pebble to faa0ea57dbc3

### PR DESCRIPTION
**Pull request by RaduBerinde**
Also update the cockroach KeySchema to the latest version in Pebble (including the fix in https://github.com/cockroachdb/pebble/pull/4107, which was detected by the keyschema tests in pkg/storage).

Changes:

 * [`faa0ea57`](https://github.com/cockroachdb/pebble/commit/faa0ea57) metamorphic: tweak L0StopWritesThreshold in case of small files
 * [`efa54018`](https://github.com/cockroachdb/pebble/commit/efa54018) crdb: better seek, fix untyped versions bug
 * [`d2480d71`](https://github.com/cockroachdb/pebble/commit/d2480d71) db: avoid repeated lookups into IterStatsCollector's map
 * [`cd6ba1c8`](https://github.com/cockroachdb/pebble/commit/cd6ba1c8) sstable: shard categorized iterator stats
 * [`8bf23da7`](https://github.com/cockroachdb/pebble/commit/8bf23da7) crdb: fix untyped version seek
 * [`c2d024da`](https://github.com/cockroachdb/pebble/commit/c2d024da) crdbtest: add tests
 * [`8e36a201`](https://github.com/cockroachdb/pebble/commit/8e36a201) colblk: don't require the header size for KeySchemaHeader
 * [`6cca117f`](https://github.com/cockroachdb/pebble/commit/6cca117f) colblk: fix IndexIter.Close, add a defensive assertion in IndexIter
 * [`d9f71916`](https://github.com/cockroachdb/pebble/commit/d9f71916) crdbtest: move crdb rowlbk benchmarks
 * [`bcf1585f`](https://github.com/cockroachdb/pebble/commit/bcf1585f) colblk: move Cockroach-specific tests to crdbtest

Release note: none.
Epic: none.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133409)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[`docs/generated/metrics/metrics.html` line 725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133409#-OA03mm9DatPNXu0s4j7:-OA03mmA41OI96JzpKmz:bmc3ydd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6d006a830399607cb65b23aa85273db2f95f83/docs/generated/metrics/metrics.html#L725)):*
> ```HTML
> <tr><td>STORAGE</td><td>storage.iterator.block-load.cached-bytes</td><td>Bytes loaded by storage engine iterators from the block cache. See storage.AggregatedIteratorStats for details.</td><td>Bytes</td><td>COUNTER</td><td>BYTES</td><td>AVG</td><td>NON_NEGATIVE_DERIVATIVE</td></tr>
> <tr><td>STORAGE</td><td>storage.iterator.block-load.read-duration</td><td>Cumulative time storage engine iterators spent loading blocks from durable storage. See storage.AggregatedIteratorStats for details.</td><td>Nanoseconds</td><td>COUNTER</td><td>NANOSECONDS</td><td>AVG</td><td>NON_NEGATIVE_DERIVATIVE</td></tr>
> <tr><td>STORAGE</td><td>storage.iterator.category-batch-eval.block-load.bytes</td><td>Bytes loaded by storage sstable iterators (possibly cached).</td><td>Bytes</td><td>COUNTER</td><td>BYTES</td><td>AVG</td><td>NON_NEGATIVE_DERIVATIVE</td></tr>
> ```

I'm not sure why these only showed up now?

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133409#-:-OA0DN9H3RJ3jeqm9cbr:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`docs/generated/metrics/metrics.html` line 725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133409#-OA03mm9DatPNXu0s4j7:-OA0Csil4b9EJCdj0yiA:b-dl2h2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6d006a830399607cb65b23aa85273db2f95f83/docs/generated/metrics/metrics.html#L725)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm not sure why these only showed up now?
</blockquote></details>

I think that was my change to reduce mutex contention. We started to construct a CategoryStats for a unique category any time an iterator was created, even if it never read any sstable bytes.

**Comment by RaduBerinde** [comment]
*[`docs/generated/metrics/metrics.html` line 725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133409#-OA03mm9DatPNXu0s4j7:-OA178_n73tH7PRkODCD:bdjev7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6d006a830399607cb65b23aa85273db2f95f83/docs/generated/metrics/metrics.html#L725)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think that was my change to reduce mutex contention. We started to construct a CategoryStats for a unique category any time an iterator was created, even if it never read any sstable bytes.
</blockquote></details>

It looks like now it's not deterministic now.. I'm not sure how these are generated but I guess it runs a cockroach process and harvests them somehow?

**Comment by RaduBerinde** [comment]
The problem is that we do [AddMetricStruct](https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/metrics.go#L4142) lazily, so these metrics will only show up when we update them. `metrics.html` is generated by running the binary with `gen metric-list".

This is not easy to fix because of the design of `Category` which is an arbitrary string without a centralized list of possible values.

**Pull request merged**
