### PR TITLE
tracing: refactor "logging" components of the API

### PR DESCRIPTION
**Pull request by irfansharif**
..to use the "recording" terminology instead, and simplify it to avoid
exposing opentracing symbols from this package. 

While here, we also pull out span types into their own files. There's too much
inter-mingling happening here which makes it a bit tedious to pull out the
various span types into their own packages. But separate files makes it a bit
easier to navigate, and can make do for now.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58509)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by tbg** [comment]
I want to just point out that we do need a better API than just `Record(string)` in the future, as we will want redactability for tracing in general (both for structured payloads and free-form messages). I think this means that `Record` should take `(fmt string, args ...interface{})` but @knz should weigh in. Internally it would do something very similar to what's done here:

https://github.com/cockroachdb/cockroach/blob/bb26998d007a6a06aa5b61a0b4aa19701d0fa439/pkg/util/log/log_entry.go#L140-L151

We don't *have* to do this now, but it seems easy and I think we should.

**Review by knz — COMMENTED** [review]
Thanks Tobias for pinging me.
Here's a couple of consideration. Considerations 1 and 2 are the most important for this PR, so I'd prefer if the PR would find some solution to that in any case. The other 3 considerations are about redactability and could be considered in a later PR.

1) Regardless of redactability, it's ugly to call `fmt.Sprintf` and then `Record` on the result. That incurs the cost of the string formatting even when we're not recording in the end. So regardless of redactability, we need the API to provide side-by-side two variants, one for direct strings and one with format/args parameters (`Recordf()`?).

2) Tobias linked to some source code in the comment above. The idea to use the same function for both the formatting and non-formatting case is a legacy case in our logging package and is, in fact, a dangerous footgun and bad example to follow. (In our own log package, `log.Info("%v")` with no additional parameters prints just "%v" in the output. What a sane API would do would be to print an error that %v was not provisioned with a positional argument. We really need to remove that special case, it's ugly.)


3) then separately, we can talk about redactability. Before anything I'd like to point out that until we extend the linter to ensure that the format argument for the `Recordf()` is a literal constant string, we can't implement redactability properly. FWIW the code for that linter is in `pkg/testutils/lint/passes/fmtsafe`


4) Then we want to ask ourselves what do we want for the non-formatting variant `Record()` which takes a simple string. Should that string be considered safe for reporting or not? It depends on whether we can guarantee that any existing and future use will be restricted to use constant literal strings (via the linter mentioned above). Here's a story for you:

   - originally, our `log.Info()` (not `Infof`) function was considering its string as unsafe
   - we quickly realized this was undesirable, because the majority of uses were in fact safe literal strings. So we implemented a linter to enforce that (aforementioned), and converted the few call sites that were using a variable to use `Infof("%s", msg)` instead (or a redact.StringBuilder instead)
   - however, we also have something called the "log bridge", so that calls to Go's stdlib's `log` calls are redirected to our own. We can't lint uses of that API, so we're forced to consider all the calls made via the stdlib as unsafe.

5) this last bullet item leads me to this: if/when you start caring about redactability, please ensure that there's a boolean *in every trace entry* that indicates whether the string is redactable or not. This is because it's likely that (now or later) we'll see APIs used by 3rd party packages that add unsafe strings in a trace, without using our redact package. 


All to say that I'd like to see the analysis in the commit message:
- what is the API exactly?
- what is safe, what is not?
- where is the linter for the safe literal strings?
- are there 3rd party uses because we're overloading an existing tracing API here?
- how is *redactability* (not redaction markers) encoded in a trace event?

> Reviewed 7 of 7 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58509#-:-MQS1lp65GYc2sp3qLVD:b-egdbw)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by irfansharif — COMMENTED** [review]
> Regardless of redactability, it's ugly to call fmt.Sprintf and then Record on the result. That incurs the cost of the string formatting even when we're not recording in the end. So regardless of redactability, we need the API to provide side-by-side two variants, one for direct strings and one with format/args parameters (Recordf()?).

Done. Thanks for the tip!

> In our own log package, log.Info("%v") with no additional parameters prints just "%v" in the output. What a sane API would do would be to print an error that %v was not provisioned with a positional argument.

I'm not really sure how I would go about checking that the passed in string isn't an unescaped format modifier. I didn't find any helpers lying around to let me do this, did I miss any? Anyway, I've added a TODO here I'll get to in a second pass.

> Before anything I'd like to point out that until we extend the linter to ensure that the format argument for the Recordf() is a literal constant string, we can't implement redactability properly. FWIW the code for that linter is in pkg/testutils/lint/passes/fmtsafe

Done, thanks for the pointer.

> are there 3rd party uses because we're overloading an existing tracing API here?

We're not actually overloading an existing API here. There's no way for 3rd party packages code to call these functions, this is for crdb internal usage only.

> what is the API exactly?
> how is redactability (not redaction markers) encoded in a trace event?
> what is safe, what is not?

I'll give this area a second pass in a follow up PR, and address the redactability concerns then. The existing "Record" calls are all safe (we weren't redacting anything previously anyway, but I also checked to see that they're all safe). We'll definitely need to address this when we start surfacing structured events around contention (which may want to encode the contended user keys). I've added TODOs and documentation in the code itself instead of the commit message.

Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58509#-:-MQUHKfZ7L7HUFQO_-8e:b-e5760h)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by irfansharif** [comment]
CI tripped up on https://github.com/cockroachdb/cockroach/issues/57759.

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 5 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58509)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/util/tracing/grpc_interceptor.go, line 138 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58509#-MQWq2Ul6aATePmrRk_2:-MQWq2Um0NZPXhqIAbOS:b-as9rrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e36fe0f2c70d9547547ddf9e4e97d8e01400780/pkg/util/tracing/grpc_interceptor.go#L138)):*
> ```Go
> 		if err != nil {
> 			SetSpanTags(serverSpan, err, false)
> 			serverSpan.Recordf("error: %s", err)
> ```

May I suggest an additional `Errorf` side-by-side with Recordf.

My rationale is that it's likely we'll want a tracing mode which doesn't record anything but errors (to troubleshoot problems in large,c omplex queries) so having a different method will enable us to have a metadata annotation inside the payload to indicate error vs non-error.
___
*[pkg/util/tracing/span.go, line 340 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58509#-MQWqL3D8awz7PUe51-q:-MQWqL3D8awz7PUe51-r:b28y4bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e36fe0f2c70d9547547ddf9e4e97d8e01400780/pkg/util/tracing/span.go#L340)):*
> ```Go
> // additional parameters would just record "%v" in the trace. What a sane API
> // would do would be to print an error that %v was not provisioned with a
> // positional argument.
> ```

You misunderstood my comment (and this TODO doesn't have a place here).
My comment is that the `log` API is defective _because_ it allows `log.Infof("%v")`, emphasis on the "f" here.

`log.Info("%v")` (notice: no "f") is fine, and so would be `Record("%v")` here in your code. No special case needed.

**Pull request merged**
