### PR TITLE
roachtest: dump stacks when test times out

### PR DESCRIPTION
**Pull request by tbg**
I've recently seen a number of very opaque test failures in the
acceptance tests, for example `bank/cluster-recovery`. In those
cases there was next to nothing in the logs, and the CRDB logs
looked fine. It will be helpful in this case to have an artifact
in the test directory containing roachtest's stacks, which is
what this commit achieves.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Haha, roachtest/acceptance/cluster-recovery timed out **on this PR**, so I have this stack trace pointing at

```
	// Delete table created by a prior instance of a test.
	if _, err := db.ExecContext(ctx, `DROP TABLE IF EXISTS bank.accounts`); err != nil {
		t.Fatal(err)
	}
```

That's already useful, suggests that CRDB is indeed the problem here, not the test.

This reminds me of https://github.com/cockroachdb/cockroach/issues/45792, though unclear if that's it. It would be nice of we got stack traces from the CRDB processes too in this case, but I'll leave that for another PR.

```
goroutine 60 [IO wait, 10 minutes]:
internal/poll.runtime_pollWait(0x7ff9dee22c98, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0007b2d18, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0007b2d00, 0xc000692000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0007b2d00, 0xc000692000, 0x1000, 0x1000, 0xc000867360, 0x7d3131, 0xc0007b2d00)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000100a0, 0xc000692000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
bufio.(*Reader).Read(0xc0006b8cc0, 0xc000286020, 0x5, 0x200, 0xc000286020, 0x28, 0x200)
	/usr/local/go/src/bufio/bufio.go:226 +0x26a
io.ReadAtLeast(0x4cb1bc0, 0xc0006b8cc0, 0xc000286020, 0x5, 0x200, 0x5, 0x200, 0x28, 0x0)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).recvMessage(0xc000286000, 0xc000867500, 0x200, 0x28, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:939 +0x103
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).recv1Buf(0xc000286000, 0xc000867500, 0x22)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:990 +0x39
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).recv1(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:1015
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).simpleExec(0xc000286000, 0x43eaece, 0x22, 0xc000867590, 0x70bbb8, 0x10, 0x3ee5ac0, 0xc0004bc901, 0xc000260190)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:613 +0x1bc
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).Exec(0xc000286000, 0x43eaece, 0x22, 0x74768b8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn.go:867 +0x2a1
github.com/cockroachdb/cockroach/vendor/github.com/lib/pq.(*conn).ExecContext(0xc000286000, 0x4d40640, 0xc00064a940, 0x43eaece, 0x22, 0x74768b8, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/lib/pq/conn_go18.go:42 +0x1aa
database/sql.ctxDriverExec(0x4d40640, 0xc00064a940, 0x7ff9decee350, 0xc000286000, 0x0, 0x0, 0x43eaece, 0x22, 0x74768b8, 0x0, ...)
	/usr/local/go/src/database/sql/ctxutil.go:31 +0x227
database/sql.(*DB).execDC.func2()
	/usr/local/go/src/database/sql/sql.go:1519 +0x1db
database/sql.withLock(0x4cf4d80, 0xc0007b2d80, 0xc000867a60)
	/usr/local/go/src/database/sql/sql.go:3184 +0x6d
database/sql.(*DB).execDC(0xc00002aa80, 0x4d40640, 0xc00064a940, 0xc0007b2d80, 0xc000867b60, 0x43eaece, 0x22, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/database/sql/sql.go:1514 +0x4b2
database/sql.(*DB).exec(0xc00002aa80, 0x4d40640, 0xc00064a940, 0x43eaece, 0x22, 0x0, 0x0, 0x0, 0x1, 0x4cfb140, ...)
	/usr/local/go/src/database/sql/sql.go:1499 +0x139
database/sql.(*DB).ExecContext(0xc00002aa80, 0x4d40640, 0xc00064a940, 0x43eaece, 0x22, 0x0, 0x0, 0x0, 0x4cfb140, 0xc0001d0720, ...)
	/usr/local/go/src/database/sql/sql.go:1477 +0xde
main.(*bankState).initBank(0xc0009d0540, 0x4d40640, 0xc00064a940, 0xc0004f4480, 0xc0005be3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/bank.go:123 +0x1de
main.runBankClusterRecovery(0x4d40640, 0xc00064a940, 0xc0004f4480, 0xc0005be3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/bank.go:426 +0x2ab
main.registerAcceptance.func1(0x4d40640, 0xc00064a940, 0xc0004f4480, 0xc0005be3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/acceptance.go:84 +0x4d
main.(*testRunner).runTest.func2(0xc0006906c0, 0xc0004f4480, 0x4d40640, 0xc00064a940, 0xc0005be3c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:747 +0xde
created by main.(*testRunner).runTest
	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:736 +0x55c
```

**Comment by tbg** [comment]
Hmm, no "have been waiting" messages here.

**Comment by tbg** [comment]
Ah duh, I have goroutines in the debug zip. Ok here we go @nvanbenschoten 

```
goroutine 1700 [select, 14 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.(*lockTableWaiterImpl).WaitOn(0xc000d0ae40, 0x4a002a0, 0xc00511e960, 0xc005120fc0, 0x15f9691acc7602c8, 0x0, 0x0, 0x0, 0xc00502c680, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_waiter.go:119 +0x19f
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.(*managerImpl).sequenceReqWithGuard(0xc000631e40, 0x4a002a0, 0xc00511e960, 0xc000616af0, 0xc0051210e0, 0x15f9691acc7602c8, 0x0, 0x0, 0x0, 0xc00502c680, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/concurrency_manager.go:170 +0x43e
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.(*managerImpl).SequenceReq(0xc000631e40, 0x4a002a0, 0xc00511e960, 0xc000616af0, 0xc0051210e0, 0x15f9691acc7602c8, 0x0, 0x0, 0x0, 0xc00502c680, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/concurrency_manager.go:121 +0xfb
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries(0xc0007c0e00, 0x4a002a0, 0xc00511e960, 0xc00502c780, 0x430ebd0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:192 +0x270
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendWithRangeID(0xc0007c0e00, 0x4a002a0, 0xc00511e930, 0x1a, 0xc00502c780, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:98 +0x2f3
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).Send(0xc0007c0e00, 0x4a002a0, 0xc00511e930, 0x15f9691acc7602c8, 0x0, 0x100000001, 0x1, 0x0, 0x1a, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:36 +0x91
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Send(0xc000892700, 0x4a002a0, 0xc00511e8d0, 0x15f9691acc7602c8, 0x0, 0x100000001, 0x1, 0x0, 0x1a, 0x0, ...)

....

github.com/cockroachdb/cockroach/pkg/sql/sqlbase.LookupDatabaseID(...)
```

From n1's stacks.

**Comment by nvanbenschoten** [comment]
Thanks for getting the stacks. From that trace, it does look the same as https://github.com/cockroachdb/cockroach/issues/38257#issuecomment-595501254. I have a fix in the works that should be out shortly.

**Review by nvb — APPROVED** [review]
:lgtm: by the way, this is a very nice improvement.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45746#-:-M1nUFl6CzQG_dxuqkNS:b-75nh4y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Pull request merged**
