### PR TITLE
opt: avoid repeatedly computing LCP of orderings

### PR DESCRIPTION
**Pull request by mgartner**
Calculating the longest common prefix between interesting orderings of a
relational expression and required orderings is expensive when
optimizing complex queries. Prior to the commit the optimizer was
repeatedly computing the LCP with the same inputs. We now calculate the
LCP once for the optimization of each group, and reuse it while
enforcing the properties of each member of the group. This is possible
because interesting orderings are the same for all members of a group,
and therefore the LCP is the same for all members of a group w.r.t. a
specific required ordering.

Epic: None

Release note (performance improvement): Planning time for complex
queries has been reduced.

### CODE REVIEW

**Comment by mgartner** [comment]
This provides some nice gains for the slow queries benchmarks:

```
name                                     old time/op    new time/op    delta
SlowQueries/slow-query-1/reorder-join-0    1.31ms ±12%    1.20ms ± 1%   -8.56%  (p=0.032 n=5+5)
SlowQueries/slow-query-1/reorder-join-8    15.9ms ± 4%    15.0ms ± 1%   -6.09%  (p=0.008 n=5+5)
SlowQueries/slow-query-2/reorder-join-0    2.44ms ± 3%    2.40ms ±13%     ~     (p=0.151 n=5+5)
SlowQueries/slow-query-2/reorder-join-8     292ms ± 3%     246ms ±10%  -15.98%  (p=0.008 n=5+5)
SlowQueries/slow-query-3/reorder-join-0    55.3ms ± 1%    55.1ms ± 1%     ~     (p=0.310 n=5+5)
SlowQueries/slow-query-3/reorder-join-8    58.9ms ± 2%    60.5ms ± 5%     ~     (p=0.690 n=5+5)
SlowQueries/slow-query-4/reorder-join-0    70.9ms ± 8%    68.5ms ± 1%   -3.31%  (p=0.032 n=5+5)
SlowQueries/slow-query-4/reorder-join-8    70.4ms ± 6%    68.7ms ± 1%     ~     (p=0.222 n=5+5)
SlowQueries/slow-query-5/reorder-join-0    49.8ms ± 4%    48.0ms ± 0%   -3.65%  (p=0.008 n=5+5)
SlowQueries/slow-query-5/reorder-join-8     823ms ± 3%     791ms ± 4%   -3.91%  (p=0.032 n=5+5)
SlowQueries/slow-query-6/reorder-join-0    27.4ms ± 1%    26.8ms ± 0%   -2.15%  (p=0.008 n=5+5)
SlowQueries/slow-query-6/reorder-join-8     1.25s ± 1%     1.11s ± 4%  -11.02%  (p=0.008 n=5+5)
SlowQueries/slow-query-7/reorder-join-0    38.7ms ± 3%    38.0ms ± 2%     ~     (p=0.421 n=5+5)
SlowQueries/slow-query-7/reorder-join-8     1.64s ± 6%     1.46s ± 2%  -10.82%  (p=0.008 n=5+5)

name                                     old alloc/op   new alloc/op   delta
SlowQueries/slow-query-1/reorder-join-0     693kB ± 0%     691kB ± 0%   -0.23%  (p=0.008 n=5+5)
SlowQueries/slow-query-1/reorder-join-8    6.85MB ± 0%    6.68MB ± 0%   -2.57%  (p=0.008 n=5+5)
SlowQueries/slow-query-2/reorder-join-0     992kB ± 1%     973kB ± 1%   -1.97%  (p=0.008 n=5+5)
SlowQueries/slow-query-2/reorder-join-8    61.4MB ± 0%    51.1MB ± 0%  -16.70%  (p=0.016 n=5+4)
SlowQueries/slow-query-3/reorder-join-0    40.4MB ± 0%    40.3MB ± 0%     ~     (p=0.095 n=5+4)
SlowQueries/slow-query-3/reorder-join-8    42.6MB ± 0%    42.7MB ± 1%     ~     (p=0.548 n=5+5)
SlowQueries/slow-query-4/reorder-join-0    30.7MB ± 0%    30.7MB ± 0%     ~     (p=0.841 n=5+5)
SlowQueries/slow-query-4/reorder-join-8    30.7MB ± 0%    30.7MB ± 0%     ~     (p=0.413 n=4+5)
SlowQueries/slow-query-5/reorder-join-0    33.6MB ± 0%    33.5MB ± 0%   -0.32%  (p=0.016 n=5+4)
SlowQueries/slow-query-5/reorder-join-8     258MB ± 0%     256MB ± 0%   -1.06%  (p=0.008 n=5+5)
SlowQueries/slow-query-6/reorder-join-0    10.6MB ± 0%    10.5MB ± 0%   -0.27%  (p=0.008 n=5+5)
SlowQueries/slow-query-6/reorder-join-8     484MB ± 0%     429MB ± 0%  -11.46%  (p=0.008 n=5+5)
SlowQueries/slow-query-7/reorder-join-0    14.1MB ± 0%    14.0MB ± 0%   -0.31%  (p=0.016 n=5+4)
SlowQueries/slow-query-7/reorder-join-8     605MB ± 0%     534MB ± 0%  -11.74%  (p=0.008 n=5+5)

name                                     old allocs/op  new allocs/op  delta
SlowQueries/slow-query-1/reorder-join-0     3.89k ± 0%     3.87k ± 0%   -0.53%  (p=0.008 n=5+5)
SlowQueries/slow-query-1/reorder-join-8     69.9k ± 0%     65.9k ± 0%   -5.71%  (p=0.000 n=4+5)
SlowQueries/slow-query-2/reorder-join-0     4.42k ± 2%     4.02k ± 1%   -9.04%  (p=0.008 n=5+5)
SlowQueries/slow-query-2/reorder-join-8      478k ± 0%      265k ± 0%  -44.49%  (p=0.016 n=5+4)
SlowQueries/slow-query-3/reorder-join-0      304k ± 0%      303k ± 0%     ~     (p=0.111 n=5+4)
SlowQueries/slow-query-3/reorder-join-8      324k ± 0%      325k ± 1%     ~     (p=0.651 n=5+5)
SlowQueries/slow-query-4/reorder-join-0      167k ± 0%      167k ± 0%     ~     (p=0.397 n=5+5)
SlowQueries/slow-query-4/reorder-join-8      167k ± 0%      167k ± 0%     ~     (p=0.921 n=4+5)
SlowQueries/slow-query-5/reorder-join-0      212k ± 0%      211k ± 0%   -0.40%  (p=0.016 n=5+4)
SlowQueries/slow-query-5/reorder-join-8     4.52M ± 0%     4.43M ± 0%   -1.89%  (p=0.008 n=5+5)
SlowQueries/slow-query-6/reorder-join-0      111k ± 0%      110k ± 0%   -0.64%  (p=0.008 n=5+5)
SlowQueries/slow-query-6/reorder-join-8     8.59M ± 0%     6.93M ± 0%  -19.28%  (p=0.008 n=5+5)
SlowQueries/slow-query-7/reorder-join-0      177k ± 0%      175k ± 0%   -0.68%  (p=0.016 n=5+4)
SlowQueries/slow-query-7/reorder-join-8     12.3M ± 0%     10.2M ± 0%  -17.22%  (p=0.008 n=5+5)
```

And no change for the other Explore benchmarks:

```
name                                                 old time/op    new time/op    delta
Phases/kv-read/Simple/Explore                          27.1µs ± 2%    26.8µs ± 1%    ~     (p=0.310 n=5+5)
Phases/kv-read-const/Simple/Explore                    27.8µs ±10%    26.7µs ± 1%  -3.99%  (p=0.032 n=5+5)
Phases/tpcc-new-order/Simple/Explore                   72.1µs ± 0%    72.2µs ± 1%    ~     (p=1.000 n=5+5)
Phases/tpcc-delivery/Simple/Explore                    57.8µs ± 1%    58.1µs ± 0%    ~     (p=0.056 n=5+5)
Phases/tpcc-delivery/Prepared/Explore                  19.3µs ± 0%    19.5µs ± 0%  +1.15%  (p=0.008 n=5+5)
Phases/tpcc-stock-level/Simple/Explore                  255µs ± 3%     253µs ± 0%    ~     (p=1.000 n=5+5)
Phases/tpcc-stock-level/Prepared/Explore               99.3µs ± 1%   100.0µs ± 1%    ~     (p=0.056 n=5+5)
Phases/many-columns-and-indexes-a/Simple/Explore        290µs ± 0%     291µs ± 0%    ~     (p=0.056 n=5+5)
Phases/many-columns-and-indexes-a/Prepared/Explore      258µs ± 0%     259µs ± 0%    ~     (p=0.222 n=5+5)
Phases/many-columns-and-indexes-b/Simple/Explore        316µs ± 0%     317µs ± 0%    ~     (p=0.421 n=5+5)
Phases/many-columns-and-indexes-b/Prepared/Explore      267µs ± 2%     265µs ± 0%    ~     (p=0.056 n=5+5)
Phases/many-columns-and-indexes-c/Simple/Explore        194ms ± 1%     193ms ± 1%    ~     (p=0.421 n=5+5)
Phases/many-columns-and-indexes-c/Prepared/Explore      189ms ± 1%     190ms ± 1%    ~     (p=0.310 n=5+5)
Phases/many-columns-and-indexes-d/Simple/Explore       17.7ms ± 0%    17.8ms ± 1%    ~     (p=0.310 n=5+5)
Phases/many-columns-and-indexes-d/Prepared/Explore     16.1ms ± 1%    16.5ms ± 5%    ~     (p=0.151 n=5+5)
Phases/single-col-histogram-range/Simple/Explore       79.5µs ± 0%    80.0µs ± 2%    ~     (p=0.421 n=5+5)
Phases/single-col-histogram-range/Prepared/Explore     34.8µs ± 0%    35.0µs ± 2%    ~     (p=0.151 n=5+5)
Phases/json-insert/Simple/Explore                      16.6µs ± 1%    16.8µs ± 1%  +0.97%  (p=0.008 n=5+5)
Phases/batch-insert-one/Simple/Explore                 70.9µs ± 0%    71.6µs ± 1%  +0.98%  (p=0.008 n=5+5)
Phases/batch-insert-many/Simple/Explore                5.02ms ± 0%    5.09ms ± 3%    ~     (p=0.056 n=5+5)
Phases/ored-preds-100/Simple/Explore                   2.50ms ± 0%    2.51ms ± 0%    ~     (p=0.095 n=5+5)
Phases/ored-preds-using-params-100/Simple/Explore      2.36ms ± 1%    2.36ms ± 0%    ~     (p=0.548 n=5+5)
Phases/ored-preds-using-params-100/Prepared/Explore     947µs ± 0%     917µs ± 1%  -3.19%  (p=0.016 n=4+5)

name                                                 old alloc/op   new alloc/op   delta
Phases/kv-read/Simple/Explore                          16.0kB ± 0%    16.0kB ± 0%    ~     (all equal)
Phases/kv-read-const/Simple/Explore                    16.1kB ± 0%    16.1kB ± 0%    ~     (all equal)
Phases/tpcc-new-order/Simple/Explore                   34.0kB ± 0%    34.0kB ± 0%    ~     (p=0.762 n=5+5)
Phases/tpcc-delivery/Simple/Explore                    28.2kB ± 0%    28.2kB ± 0%    ~     (p=0.611 n=5+5)
Phases/tpcc-delivery/Prepared/Explore                  13.3kB ± 0%    13.3kB ± 0%    ~     (p=0.952 n=5+5)
Phases/tpcc-stock-level/Simple/Explore                  131kB ± 0%     131kB ± 0%  -0.08%  (p=0.008 n=5+5)
Phases/tpcc-stock-level/Prepared/Explore               60.1kB ± 0%    60.0kB ± 0%  -0.16%  (p=0.008 n=5+5)
Phases/many-columns-and-indexes-a/Simple/Explore       44.4kB ± 0%    44.4kB ± 0%    ~     (p=1.000 n=5+5)
Phases/many-columns-and-indexes-a/Prepared/Explore     5.76kB ± 0%    5.76kB ± 0%    ~     (all equal)
Phases/many-columns-and-indexes-b/Simple/Explore       51.2kB ± 0%    51.2kB ± 0%    ~     (p=0.254 n=5+5)
Phases/many-columns-and-indexes-b/Prepared/Explore     8.28kB ± 0%    8.28kB ± 0%    ~     (p=0.238 n=5+4)
Phases/many-columns-and-indexes-c/Simple/Explore        107MB ± 0%     107MB ± 0%    ~     (p=0.690 n=5+5)
Phases/many-columns-and-indexes-c/Prepared/Explore      106MB ± 0%     106MB ± 0%    ~     (p=0.421 n=5+5)
Phases/many-columns-and-indexes-d/Simple/Explore       11.7MB ± 0%    11.7MB ± 0%  -0.00%  (p=0.008 n=5+5)
Phases/many-columns-and-indexes-d/Prepared/Explore     10.7MB ± 0%    10.7MB ± 0%  -0.01%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/Explore       30.4kB ± 0%    30.4kB ± 0%    ~     (all equal)
Phases/single-col-histogram-range/Prepared/Explore     13.2kB ± 0%    13.2kB ± 0%    ~     (all equal)
Phases/json-insert/Simple/Explore                      16.3kB ± 0%    16.3kB ± 0%    ~     (all equal)
Phases/batch-insert-one/Simple/Explore                 69.2kB ± 0%    69.2kB ± 0%    ~     (p=1.000 n=5+5)
Phases/batch-insert-many/Simple/Explore                3.99MB ± 0%    3.99MB ± 0%    ~     (p=0.214 n=5+5)
Phases/ored-preds-100/Simple/Explore                    992kB ± 0%     992kB ± 0%    ~     (p=0.690 n=5+5)
Phases/ored-preds-using-params-100/Simple/Explore       963kB ± 0%     963kB ± 0%    ~     (p=0.548 n=5+5)
Phases/ored-preds-using-params-100/Prepared/Explore     741kB ± 0%     741kB ± 0%    ~     (p=0.198 n=5+5)

name                                                 old allocs/op  new allocs/op  delta
Phases/kv-read/Simple/Explore                            94.0 ± 0%      94.0 ± 0%    ~     (all equal)
Phases/kv-read-const/Simple/Explore                      94.0 ± 0%      94.0 ± 0%    ~     (all equal)
Phases/tpcc-new-order/Simple/Explore                      173 ± 0%       173 ± 0%    ~     (all equal)
Phases/tpcc-delivery/Simple/Explore                       179 ± 0%       179 ± 0%    ~     (all equal)
Phases/tpcc-delivery/Prepared/Explore                    76.0 ± 0%      76.0 ± 0%    ~     (all equal)
Phases/tpcc-stock-level/Simple/Explore                    706 ± 0%       705 ± 0%  -0.20%  (p=0.008 n=5+5)
Phases/tpcc-stock-level/Prepared/Explore                  342 ± 0%       341 ± 0%  -0.29%  (p=0.008 n=5+5)
Phases/many-columns-and-indexes-a/Simple/Explore         81.0 ± 0%      81.0 ± 0%    ~     (all equal)
Phases/many-columns-and-indexes-a/Prepared/Explore       32.0 ± 0%      32.0 ± 0%    ~     (all equal)
Phases/many-columns-and-indexes-b/Simple/Explore          135 ± 0%       135 ± 0%    ~     (all equal)
Phases/many-columns-and-indexes-b/Prepared/Explore       50.0 ± 0%      50.0 ± 0%    ~     (all equal)
Phases/many-columns-and-indexes-c/Simple/Explore         667k ± 0%      667k ± 0%  -0.01%  (p=0.016 n=5+5)
Phases/many-columns-and-indexes-c/Prepared/Explore       663k ± 0%      663k ± 0%  -0.01%  (p=0.008 n=5+5)
Phases/many-columns-and-indexes-d/Simple/Explore         202k ± 0%      202k ± 0%  -0.01%  (p=0.008 n=5+5)
Phases/many-columns-and-indexes-d/Prepared/Explore       200k ± 0%      200k ± 0%  -0.01%  (p=0.008 n=5+5)
Phases/single-col-histogram-range/Simple/Explore          521 ± 0%       521 ± 0%    ~     (all equal)
Phases/single-col-histogram-range/Prepared/Explore        251 ± 0%       251 ± 0%    ~     (all equal)
Phases/json-insert/Simple/Explore                        98.0 ± 0%      98.0 ± 0%    ~     (all equal)
Phases/batch-insert-one/Simple/Explore                    333 ± 0%       333 ± 0%    ~     (all equal)
Phases/batch-insert-many/Simple/Explore                 29.4k ± 0%     29.4k ± 0%    ~     (p=1.000 n=5+5)
Phases/ored-preds-100/Simple/Explore                    5.13k ± 0%     5.13k ± 0%    ~     (p=0.333 n=5+4)
Phases/ored-preds-using-params-100/Simple/Explore       4.53k ± 0%     4.53k ± 0%    ~     (all equal)
Phases/ored-preds-using-params-100/Prepared/Explore     2.89k ± 0%     2.89k ± 0%    ~     (all equal)
```

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128049)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/xform/optimizer.go` line 524 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128049#-O3ADU1f5bphNiEiyETU:-O3ADU1f5bphNiEiyETV:b-b2553z) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f4897a89f4aa2b2dc2cac822eb95a58a710be0/pkg/sql/opt/xform/optimizer.go#L524)):*
> ```Go
> 	// of the deriving the longest common prefix. The closure allows lazily
> 	// deriving the longest common prefix only when needed.
> 	var cachedLCP struct {
> ```

[nit] Why not make it a ruleprop like `InterestingOrderings`? Ruleprops already have a way to indicate they're populated, and we could just check if `OrderingChoice.Columns` is empty to know if there was a common prefix.

**Comment by mgartner** [comment]
*[`pkg/sql/opt/xform/optimizer.go` line 524 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128049#-O3ADU1f5bphNiEiyETU:-O3D8iwf4wmBOZrmjksv:b-7m6lt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f4897a89f4aa2b2dc2cac822eb95a58a710be0/pkg/sql/opt/xform/optimizer.go#L524)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Why not make it a ruleprop like `InterestingOrderings`? Ruleprops already have a way to indicate they're populated, and we could just check if `OrderingChoice.Columns` is empty to know if there was a common prefix.
</blockquote></details>

We could, but it'd have to be a `map[*physical.Required]props.OrderingChoice` since this LCP is a function of the required ordering, and the same group may be optimized w.r.t. different required orderings. I thought this was a bit simpler.

I also steered away from this approach because this property isn't associated with a specific rule or set of rules, like the other Rule props are. I suppose you could consider the optimizer's built-in exploration of sort enforcers as a kind of rule, and then it would make sense.

Happy to make the change, if you think it's still better after those considerations.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice improvements!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128049#-:-O3DylMb0HSJJiL6A8ul:bdyovjk)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/xform/optimizer.go` line 524 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128049#-O3ADU1f5bphNiEiyETU:-O3DyKS6EV3vy8btEVuE:b9tugbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/38f4897a89f4aa2b2dc2cac822eb95a58a710be0/pkg/sql/opt/xform/optimizer.go#L524)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We could, but it'd have to be a `map[*physical.Required]props.OrderingChoice` since this LCP is a function of the required ordering, and the same group may be optimized w.r.t. different required orderings. I thought this was a bit simpler.

I also steered away from this approach because this property isn't associated with a specific rule or set of rules, like the other Rule props are. I suppose you could consider the optimizer's built-in exploration of sort enforcers as a kind of rule, and then it would make sense.

Happy to make the change, if you think it's still better after those considerations.
</blockquote></details>

Thanks for the explanation, that makes sense.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
