### PR TITLE
opt: add rules to simplify and/or

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### datadriven: show position when panic occurs

If a testcase hits a panic, we don't know which case it was, unless in
verbose mode. Adding a function that catches any panic, prints out the
position information, and rethrows it.

Release note: None

#### opt: add rules to simplify and/or

Adding rules to remove True children of And ops, and False children of
Or ops. This is useful when trimming down filters after removing index
constraints.

Also, elide an Or op with a single child. We don't yet do this for And
because we currently assume filters always start with an AndOp.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/factory.go, line 175 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5iYPr0-j1o9msRsw3_:-L5iYPr0-j1o9msRsw3a:bg0b5rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0933a3c3a1b4b7bfa45112b494e6ff3f8470243/pkg/sql/opt/xform/factory.go#L175)):*
> ```Go
> 
> // isSingletonList returns true if the list has exactly one element.
> func (f *factory) isSingletonList(list opt.ListID) bool {
> ```

NIT: can you add these two list functions to a new section called "List Functions"? Eventually, I'll want to break out different sections into their own files, but for now I want to at least keep different groups of functions organized by category.

---

*[pkg/sql/opt/xform/factory.go, line 180 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5iYesfyhH_CpnZ-2qt:-L5iYesgIdwxzv7Qa7yi:b2kz7fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0933a3c3a1b4b7bfa45112b494e6ff3f8470243/pkg/sql/opt/xform/factory.go#L180)):*
> ```Go
> 
> // listFirst returns the first element from a list.
> func (f *factory) listFirst(list opt.ListID) opt.GroupID {
> ```

NIT: How about `firstListItem`? That would fit better with other naming I'm planning, like `removeListItem` and `replaceListItem`.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5iYtkKDkLcLxD1jR9F:-L5iYtkKDkLcLxD1jR9G:b-wllnwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0933a3c3a1b4b7bfa45112b494e6ff3f8470243/pkg/sql/opt/xform/rules/bool.opt#L67)):*
> ```
> # an And.
> 
> # ElideOr replaces an Or node with a single condition with that condition.
> ```

NIT: I've been using `Eliminate` rather than `Elide`. How about `EliminateSingletonOr`?

---

*[pkg/testutils/datadriven/datadriven.go, line 72 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5i_3Cve13J4kBhm0TN:-L5i_3Cve13J4kBhm0TO:b-dcwv3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0933a3c3a1b4b7bfa45112b494e6ff3f8470243/pkg/testutils/datadriven/datadriven.go#L72)):*
> ```Go
> 			defer func() {
> 				if r := recover(); r != nil {
> 					fmt.Printf("\npanic during %s:\n%s\n", d.Pos, d.Input)
> ```

NIT: Will this preserve the original stack trace so we can debug easily?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/xform/factory.go, line 175 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5iYPr0-j1o9msRsw3_:-L5iesS_sf-pyd_jOI9n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0933a3c3a1b4b7bfa45112b494e6ff3f8470243/pkg/sql/opt/xform/factory.go#L175)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: can you add these two list functions to a new section called "List Functions"? Eventually, I'll want to break out different sections into their own files, but for now I want to at least keep different groups of functions organized by category.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/factory.go, line 180 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5iYesfyhH_CpnZ-2qt:-L5iessH_7U30qNMi_u9:b3vdtpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0933a3c3a1b4b7bfa45112b494e6ff3f8470243/pkg/sql/opt/xform/factory.go#L180)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: How about `firstListItem`? That would fit better with other naming I'm planning, like `removeListItem` and `replaceListItem`.
</blockquote></details>

Yeah, sounds better.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5iYtkKDkLcLxD1jR9F:-L5iev-QRF5Qb9t24MZE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0933a3c3a1b4b7bfa45112b494e6ff3f8470243/pkg/sql/opt/xform/rules/bool.opt#L67)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: I've been using `Eliminate` rather than `Elide`. How about `EliminateSingletonOr`?
</blockquote></details>

Done.

---

*[pkg/testutils/datadriven/datadriven.go, line 72 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5i_3Cve13J4kBhm0TN:-L5if1HiF3-yVn5Cfy4a:bey3vsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0933a3c3a1b4b7bfa45112b494e6ff3f8470243/pkg/testutils/datadriven/datadriven.go#L72)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Will this preserve the original stack trace so we can debug easily?
</blockquote></details>

Yes, I checked that - it extends that stack trace with this frame.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5ihqotnaRcv2Tj0TeQ:-L5ihqotnaRcv2Tj0TeR:b-liqkgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4070ce1e745033c6135071b3d7a68231ac5abd4b/pkg/sql/opt/xform/rules/bool.opt#L64)):*
> ```
> (SimplifyOr $conditions)
> 
> # TODO(radu): we don't yet elide Ands because we assume filters are alays under
> ```

elide -> eliminate (to be consistent)
alays -> always

In the tests you've added there are lots of cases where the filters are not under an AND. Is this rule going to be added later?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-:-L5ijwjId5KSoKu74SBY:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTRs!

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5ihqotnaRcv2Tj0TeQ:-L5il5pYOjMyJxxOM8c-:blteh2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4070ce1e745033c6135071b3d7a68231ac5abd4b/pkg/sql/opt/xform/rules/bool.opt#L64)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

elide -> eliminate (to be consistent)
alays -> always

In the tests you've added there are lots of cases where the filters are not under an AND. Is this rule going to be added later?
</blockquote></details>

Done.

Good point, I thought it happened during build. Anyway, @andy-kimball and I have been talking about this and I think we'll just bring back the `FiltersOp` to avoid this kind of special handling around `AndOp`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-:-L5ilVTxdVjZcGVDQWBQ:bz5mair)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5ihqotnaRcv2Tj0TeQ:-L5ilu9KyP6FWh0orWh5:bdhewiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4070ce1e745033c6135071b3d7a68231ac5abd4b/pkg/sql/opt/xform/rules/bool.opt#L64)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.

Good point, I thought it happened during build. Anyway, @andy-kimball and I have been talking about this and I think we'll just bring back the `FiltersOp` to avoid this kind of special handling around `AndOp`.
</blockquote></details>

It still says alays :)

Re: `FiltersOp` - sounds good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806)*

**Comment by RaduBerinde** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806#-L5ihqotnaRcv2Tj0TeQ:-L5impiQYQIRHZhvQ23l:b-p4ybu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4070ce1e745033c6135071b3d7a68231ac5abd4b/pkg/sql/opt/xform/rules/bool.opt#L64)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It still says alays :)

Re: `FiltersOp` - sounds good
</blockquote></details>

Oops, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22806)*

**Pull request merged**
