### PR TITLE
backupccl: add basic backup support for user defined types

### PR DESCRIPTION
**Pull request by rohany**
Work for #48689.

This PR adds basic support and tests for backup and restore when user defined
types are in the cluster and used in tables that are part of the backup.
It takes the first step in the process to allow restoration of these
backups, but will error out if a type being restored already exists in
the cluster. Future work will add the ability to attempt to use existing
types in the cluster.

Release note: None

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
Took a first pass, the approach so far looks reasonable to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-:-M9YjcckEBCvhq9OXPIz:b-oln8ol)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @pbardea, and @rohany)

___
*[pkg/ccl/backupccl/backup_test.go, line 1480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9YdY8A2Iro5M4Rp7Dq:-M9YdY8B0SwQqvVW2UaT:b-ftps63) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/backup_test.go#L1480)):*
> ```Go
> INSERT INTO d2.t2 VALUES (ARRAY['howdy']), (ARRAY['hi']);
> `)
> 		// TODO (rohany): I can't quite get full cluster backup restore to work,
> ```

If you want to test it out temporarily, see `full_cluster_backup_restore_test.go` which creates a fresh cluster that shares the data directory.
___
*[pkg/ccl/backupccl/backup_test.go, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9WYJcrE9xYoX0IZpj-:-M9WYJcrE9xYoX0IZpj0:b-8dam8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/backup_test.go#L1562)):*
> ```Go
> 
> 	// TODO (rohany): Can I not use the same data directory as the first backup for a different backup?
> 	//  I get an error like "x is not a backup of y" when trying.
> ```

If you create a backup to the exact same location, it will try to create an incremental backup on top of the previous backup to that location. You should be able to backup to a different file in the same data directory (e.g. `nodelocal://0/new_backup`).
___
*[pkg/ccl/backupccl/restore_job.go, line 781 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9Yk-Zz2gkgsWTN1YqG:-M9Yk-Zz2gkgsWTN1YqH:b4aicer) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_job.go#L781)):*
> ```Go
> // skip_missing_foreign_keys was set, we should have aborted the RESTORE and
> // returned an error prior to this.
> // TODO (rohany): Does this need to be updated for type descriptors?
> ```

I don't think we'd need any changes here since types are descriptors.
___
*[pkg/ccl/backupccl/restore_job.go, line 1111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9Ygj0z8H81iLOAibci:-M9Ygj0z8H81iLOAibcj:bpu5nix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_job.go#L1111)):*
> ```Go
> 
> // publishTables updates the RESTORED tables status from OFFLINE to PUBLIC.
> // TODO (rohany): Does something similar need to happen here for types?
> ```

We used to just write the descriptors at the end of restore, but we changed it to create the descriptors at the start (by leveraging the `state` of the table). You can see [this PR](https://github.com/cockroachdb/cockroach/pull/37338) for more info on the pros/cons of that. I don't see any reason off the top of my head why adding the type descriptors only at the end of the restore would be an issue. 

So, we probably don't need to mark the types as public, but we should add the types to the descriptor table here.
___
*[pkg/ccl/backupccl/restore_planning.go, line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9YhigA5_v6NhDmznsy:-M9YhigA5_v6NhDmznsz:bo0jfn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_planning.go#L212)):*
> ```Go
> 
> 		// TODO (rohany): Should we verify that all types in the descriptor are found?
> 		//  That seems more like an assertion failure however.
> ```

Yep, that sounds reasonable. I'm not sure it necessarily needs to be done here. My first thought is that it would look something like `maybeFilterMissingViews`.
___
*[pkg/ccl/backupccl/restore_planning.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9WbD1I1aEJAXXb8pFr:-M9WbD1J0hCWNGCq90yI:b-lvmgun) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_planning.go#L363)):*
> ```Go
> 				needsNewParentIDs[targetDB] = append(needsNewParentIDs[targetDB], typ.ID)
> 			} else if descriptorCoverage == tree.AllDescriptors {
> 				// TODO (rohany): Not sure I understand this comment yet (copied from above).
> ```

When the descriptorCoverage is set to AllDescriptors, we're doing a full cluster restore. When we do a full cluster restore, we want to restore the system tables into a temporary db we create since we can't just overwrite the existing system table ranges' SSTs. All other tables' parentID should be unchanged. We'd only need to worry about this if the system tables had types, which would be more complicated to restore.
___
*[pkg/ccl/backupccl/restore_planning.go, line 577 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9YlkfD-JnCZoVPseM9:-M9YlkfD-JnCZoVPseMA:bo8e56o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_planning.go#L577)):*
> ```Go
> // TODO (rohany): I'm not sure what is a scalable way of ensuring that if new
> //  expressions are added to table descriptors that they are then given rewrite
> //  rules here, otherwise we could end up with corrupted backups.
> ```

What do you mean by new expressions added to table descriptors?
___
*[pkg/ccl/backupccl/targets.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9WeHqP7zM5CSfaAD2v:-M9WeHqP7zM5CSfaAD2w:b-v3dp86) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/targets.go#L350)):*
> ```Go
> // a descriptor the the ID by which it was previously known (e.g pre-TRUNCATE).
> // TODO (rohany): I'm not sure whats going on this function, and how type
> //  descriptors may or may not interact with it.
> ```

This function is used during revision history backups. The revisions that it produces are used to determine what spans we need to backup. It's interested in table truncations (where the ID is changed), creations and deletions. So we'd probably want to look at the type descriptor changes that happened and include any types that have been dropped since the `startTime`. (I don't think we need to worry about a type getting assigned a different ID, right?). We'll also want to make sure that we capture all versions of a type in case it was modified since `startTime`.
___
*[pkg/sql/sqlbase/structured.go, line 1208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9YjDaDEtG0ddZQbt63:-M9YjDaDEtG0ddZQbt64:b-om8baq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/sql/sqlbase/structured.go#L1208)):*
> ```Go
> 	}
> 	// TODO (rohany): I'm not sure if we should look at mutations -- does that
> 	//  make sense in the context of backup/restore?
> ```

Yep - the way we handle mutations right now is that we attempt to synthesize a schema change job based on the mutations of the imported tables. So, it does make sense to look at the mutations.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50064)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 1480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9YdY8A2Iro5M4Rp7Dq:-M9jWbjDCAisx2zcgMwW:b-bx4ot5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/backup_test.go#L1480)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

If you want to test it out temporarily, see `full_cluster_backup_restore_test.go` which creates a fresh cluster that shares the data directory.
</blockquote></details>

Thanks, that worked.
___
*[pkg/ccl/backupccl/backup_test.go, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9WYJcrE9xYoX0IZpj-:-M9jMCdX-eUkK1liNgo4:b-p6w9ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/backup_test.go#L1562)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

If you create a backup to the exact same location, it will try to create an incremental backup on top of the previous backup to that location. You should be able to backup to a different file in the same data directory (e.g. `nodelocal://0/new_backup`).
</blockquote></details>

I see, thanks for the clarification!
___
*[pkg/ccl/backupccl/restore_job.go, line 781 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9Yk-Zz2gkgsWTN1YqG:-M9jO6TL6hCE9ZCHc0jG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_job.go#L781)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I don't think we'd need any changes here since types are descriptors.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 1111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9Ygj0z8H81iLOAibci:-M9jOIDLCzzy7Bw2v7zt:b-lr1juf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_job.go#L1111)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

We used to just write the descriptors at the end of restore, but we changed it to create the descriptors at the start (by leveraging the `state` of the table). You can see [this PR](https://github.com/cockroachdb/cockroach/pull/37338) for more info on the pros/cons of that. I don't see any reason off the top of my head why adding the type descriptors only at the end of the restore would be an issue. 

So, we probably don't need to mark the types as public, but we should add the types to the descriptor table here.
</blockquote></details>

I see. I've written the types into the descriptor table earlier where we do tables, but I think I'll update this to spawn the type change jobs (when we have them). I don't think that we will have a public/non-public notion for types yet, but if we do I'll update that here.
___
*[pkg/ccl/backupccl/restore_planning.go, line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9YhigA5_v6NhDmznsy:-M9jQ-mQ0Wm4AUEXaUzR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_planning.go#L212)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Yep, that sounds reasonable. I'm not sure it necessarily needs to be done here. My first thought is that it would look something like `maybeFilterMissingViews`.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_planning.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9WbD1I1aEJAXXb8pFr:-M9jQ9Rq-tdaQybjTzW-:b-oqntn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_planning.go#L363)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

When the descriptorCoverage is set to AllDescriptors, we're doing a full cluster restore. When we do a full cluster restore, we want to restore the system tables into a temporary db we create since we can't just overwrite the existing system table ranges' SSTs. All other tables' parentID should be unchanged. We'd only need to worry about this if the system tables had types, which would be more complicated to restore.
</blockquote></details>

I see. There aren't any prebuilt "system" types, so I don't think I need this check.
___
*[pkg/ccl/backupccl/restore_planning.go, line 577 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9YlkfD-JnCZoVPseM9:-M9jQJQ8-vYmNi_8zfTp:b-ayrmdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_planning.go#L577)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

What do you mean by new expressions added to table descriptors?
</blockquote></details>

Certain schema elements cause serialized expressions to be stored in table descriptors. For a while we had just default columns, computed columns and check expressions. Now partial indexes have been added, which are another way that an expression can be stored in a descriptor.
___
*[pkg/ccl/backupccl/targets.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9WeHqP7zM5CSfaAD2v:-M9jQpvFAtTjSQBJoDGh:b-7sh59s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/targets.go#L350)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

This function is used during revision history backups. The revisions that it produces are used to determine what spans we need to backup. It's interested in table truncations (where the ID is changed), creations and deletions. So we'd probably want to look at the type descriptor changes that happened and include any types that have been dropped since the `startTime`. (I don't think we need to worry about a type getting assigned a different ID, right?). We'll also want to make sure that we capture all versions of a type in case it was modified since `startTime`.
</blockquote></details>

Yeah, I don't think there will be any reassignments of a type ID. Alright, this will just have to be touched again once we start to track modification time on type descriptors.
___
*[pkg/sql/sqlbase/structured.go, line 1208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9YjDaDEtG0ddZQbt63:-M9jR2Dr8LtnMZ8sy6UA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/sql/sqlbase/structured.go#L1208)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Yep - the way we handle mutations right now is that we attempt to synthesize a schema change job based on the mutations of the imported tables. So, it does make sense to look at the mutations.
</blockquote></details>

Done.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50064)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 577 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9YlkfD-JnCZoVPseM9:-M9xSLaw3adQAofi3nUO:b-c85ltt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/restore_planning.go#L577)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Certain schema elements cause serialized expressions to be stored in table descriptors. For a while we had just default columns, computed columns and check expressions. Now partial indexes have been added, which are another way that an expression can be stored in a descriptor.
</blockquote></details>

I've cleaned up this TODO in a PR stacked on top of this.

**Review by pbardea — COMMENTED** [review]
Generally LGTM - added a couple of suggestions of interesting test cases.

> Reviewed 2 of 20 files at r1, 3 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-:-M9zNMR48zGthjeEhtAV:bsxnexc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @pbardea, and @rohany)

___
*[pkg/ccl/backupccl/backup_test.go, line 1267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9zGIl812v2lagkm8hN:-M9zGIl812v2lagkm8hO:b9391tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f988272f91f08d23beb301aaa051f773e0bda1e/pkg/ccl/backupccl/backup_test.go#L1267)):*
> ```Go
> }
> 
> func TestBackupRestoreUserDefinedTypes(t *testing.T) {
> ```

Nice tests! I also think it would be good to see tests with revision_history - I think the existing ones can be modified to include UDTs.  I think that this will be more interesting with DROP types, so a TODO may suffice for now.
___
*[pkg/ccl/backupccl/backup_test.go, line 1371 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9zFRd_-f5b_TWsVJih:-M9zFRd_-f5b_TWsVJii:b9yv2rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f988272f91f08d23beb301aaa051f773e0bda1e/pkg/ccl/backupccl/backup_test.go#L1371)):*
> ```Go
> 
> 	// Test backup/restore of a single table.
> 	t.Run("table", func(t *testing.T) {
> ```

Can we also add a test for multiple tables that reference the same type as well as backing up all tables of a database (`BACKUP d.* TO`). Maybe also a table that only references the array type and not the type itself?
___
*[pkg/ccl/backupccl/backup_test.go, line 1384 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9zBDlL8AwO3cEfuzuN:-M9zBDlL8AwO3cEfuzuO:bpr29jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f988272f91f08d23beb301aaa051f773e0bda1e/pkg/ccl/backupccl/backup_test.go#L1384)):*
> ```Go
> 		sqlDB.Exec(t, `BACKUP TABLE d.t TO 'nodelocal://0/test/'`)
> 
> 		// Create a new database to backup the table into.
> ```

Should this be "_restore_ the table into"?
___
*[pkg/ccl/backupccl/restore_planning.go, line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9zLzEC8RgtzOttPWd-:-M9zLzEC8RgtzOttPWd0:b9obey5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f988272f91f08d23beb301aaa051f773e0bda1e/pkg/ccl/backupccl/restore_planning.go#L629)):*
> ```Go
> 			}
> 			// Rewrite the index's partial expression, if it has one.
> 			if index.IsPartial() {
> ```

Can you add a TODO to add tests for this?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50064)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 1267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9zGIl812v2lagkm8hN:-M9zh44o0mgZlH3Q435w:b-e5oioz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f988272f91f08d23beb301aaa051f773e0bda1e/pkg/ccl/backupccl/backup_test.go#L1267)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Nice tests! I also think it would be good to see tests with revision_history - I think the existing ones can be modified to include UDTs.  I think that this will be more interesting with DROP types, so a TODO may suffice for now.
</blockquote></details>

Agreed, I'm holding off on looking into incremental backups and the like until types can change. I'll drop a todo for now. I'm going to create a few issues tracking remaining work once this goes in.
___
*[pkg/ccl/backupccl/backup_test.go, line 1371 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9zFRd_-f5b_TWsVJih:-M9zlIB3-M9--X-qXCu3:b-cq63ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f988272f91f08d23beb301aaa051f773e0bda1e/pkg/ccl/backupccl/backup_test.go#L1371)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we also add a test for multiple tables that reference the same type as well as backing up all tables of a database (`BACKUP d.* TO`). Maybe also a table that only references the array type and not the type itself?
</blockquote></details>

Done. I had tested the array type only in `targets_test.go`, but its good to have many layers of tests.
___
*[pkg/ccl/backupccl/backup_test.go, line 1384 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9zBDlL8AwO3cEfuzuN:-M9zibAq2dsyiLLQWEb-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f988272f91f08d23beb301aaa051f773e0bda1e/pkg/ccl/backupccl/backup_test.go#L1384)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Should this be "_restore_ the table into"?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_planning.go, line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9zLzEC8RgtzOttPWd-:-M9zlOD36qjuL5PWqQ5z:b-xuwxpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f988272f91f08d23beb301aaa051f773e0bda1e/pkg/ccl/backupccl/restore_planning.go#L629)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can you add a TODO to add tests for this?
</blockquote></details>

Yeah. I'll have to come back to it once partial indexes are in a testable state.

**Review by pbardea — APPROVED** [review]

**Comment by rohany** [comment]
TFTR!

bors r=pbardea

**Review by dt — COMMENTED** [review]
> Reviewed 12 of 20 files at r1, 4 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50064)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/targets.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50064#-M9WeHqP7zM5CSfaAD2v:-M9ucbJz0-M8G7CMfb4M:b-3btzwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f26b4cc912ad0ec73c105d6a1aa4edce757909af/pkg/ccl/backupccl/targets.go#L350)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Yeah, I don't think there will be any reassignments of a type ID. Alright, this will just have to be touched again once we start to track modification time on type descriptors.
</blockquote></details>

We don't need to track modification times manually -- this does it based on the mvcc timestamps from the descriptor's key for table desc and db desc already, so that should work for type descs too.

**Pull request merged**
