### PR TITLE
roachtest: fix a recently-introduced logging bug

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Review by a-robinson — COMMENTED** [review]
Ah, was this the cause of all the nil pointer exception roachtest failures this afternoon?

**Review by benesch — APPROVED** [review]

**Comment by benesch** [comment]
The roach test run takes 16h or so. It's last night's run that you're seeing.

**Comment by benesch** [comment]
Never mind. It's the "nightly" build that Alex kicked off to test rc2.

**Pull request merged**
