### PR TITLE
roachtest: allow tests to specify a cockroach binary to use 

### LINKED ISSUE #104729: roachtest: allow tests to specify which cockroach binaries they need
Currently, most (or all) roachtests need to manually copy the `cockroach` binaries they need using the `Put` API. This is the main `./cockroach` binary (`--cockroach` flag) for the vast majority of tests, and additionally other binaries in mixed-version tests. This behavior leads to a lot of duplicated code (the same `Put` calls exist in pretty much every test) and is also wasteful: roachtest uploads its own `./cockroach-default` binary in order to reliably collect artifacts on test failures, as the framework does not know which binaries are used by a test [1].

We should support an API where test authors declare which cockroach binaries they want. This would remove the need for `Put` calls in every test, and reduce copying the same binary twice in most cases as is done today.

[1] #97814

Jira issue: CRDB-28699

### PR DESCRIPTION
**Pull request by DarrylWong**
Currently, roachtests must manually upload their own cockroach binary if needed through the Put API.
However, almost all roachtests upload the standard t.Cockroach() binary to ./cockroach on all nodes,
resulting in the same Put code being duplicated at the start of most tests. Additionally, to collect artifacts
we still need a cockroach binary at a discoverable path, leading to the same binary being copied twice in many
cases, see: https://github.com/cockroachdb/cockroach/pull/97814

This change adds a TestSpec option which lets tests specify a cockroach binary to use. If one is not specified,
we now upload the t.Cockroach() binary to ./cockroach. This lets us remove cockroach-default logic for artifacts,
and removes the need to manually upload binaries at the start of each test.

Release note: None
Fixes: https://github.com/cockroachdb/cockroach/issues/104729

### CODE REVIEW

**Comment by DarrylWong** [comment]
[Nightly Run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12422478?hideProblemsFromDependencies=false&hideTestsFromDependencies=false)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

This is fantastic, the double copy was very annoying. Nice job!! :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-:-Nieqk6SCrLU7H6OBBiQ:b7mlfsp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster.go` line 1839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-NiepTxS7r5w6_DEl0qf:-NiepTxS7r5w6_DEl0qg:bpqw61k) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdd2b4054e4b4c785653b3d101ce583877e299d0/pkg/cmd/roachtest/cluster.go#L1839)):*
> ```Go
> // runtime assertions enabled. Note that we upload to all nodes even if they
> // don't use the binary, so that the test runner can always fetch logs.
> func (c *clusterImpl) PutCockroach(ctx context.Context, l *logger.Logger, t *testImpl) error {
> ```

[nit] this feels like it belongs with `testImpl` rather than `clusterImpl`
___
*[`pkg/cmd/roachtest/cluster.go` line 1848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-NiepmgW16oW0mM8-Yq6:-NiepmgW16oW0mM8-Yq7:b-qrg1kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdd2b4054e4b4c785653b3d101ce583877e299d0/pkg/cmd/roachtest/cluster.go#L1848)):*
> ```Go
> 		return c.PutE(ctx, l, t.RuntimeAssertionsCockroach(), test.DefaultCockroachPath, c.All())
> 	default:
> 		return errors.Errorf("Specified cockroach binary does not exist.")
> ```

[nit] error is confusing, sounds like a binary is missing, maybe "unknown CockroachBinary value %v"
___
*[`pkg/cmd/roachtest/registry/test_spec.go` line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-NieqJYdAs8RN4I0GHo6:-NieqJYdAs8RN4I0GHo7:b7x0fj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdd2b4054e4b4c785653b3d101ce583877e299d0/pkg/cmd/roachtest/registry/test_spec.go#L434)):*
> ```Go
> // ClusterCockroachBinary is the cockroach binary that will be uploaded
> // to every node in the cluster at the start of the test. We upload to
> // every node so that we can fetch logs in the case of a failure.
> ```

[nit] It's important to mention the default value when it's not specified.

**Comment by renatolabs** [comment]
Very exciting to see all these `c.Put` calls going away!

Nit: can we make the PR title match the commit?

Thought: should we make `t.Cockroach()` private? Is there still a legitimate use for it?

The thinking is that muscle memory plays a strong role in roachtest, and it's only a matter of time before this `c.Put` call is added back to new or existing tests. A compilation failure would be a pretty good indication that that should not be done anymore.

Doesn't have to be part of this PR, just wanted to ask the question.

**Review by renatolabs — APPROVED** [review]
> Reviewed 111 of 111 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113301)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @RaduBerinde, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster.go` line 1839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-NiepTxS7r5w6_DEl0qf:-NifCFJD6_-JudvFytwO:b-ynhhel) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdd2b4054e4b4c785653b3d101ce583877e299d0/pkg/cmd/roachtest/cluster.go#L1839)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this feels like it belongs with `testImpl` rather than `clusterImpl`
</blockquote></details>

Not sure about that; this function is uploading a file to the cluster. Most other functions that do this live in the cluster level (e.g., `PutLibraries`, `PutString`, `Put` itself, `Stage`, etc.)

**Review by DarrylWong — COMMENTED** [review]
Argh, just noticed a few `t.Cockroach()` slipped through because they call `c.PutE`. Will have to rerun those but since they just upload cockroach to every node I'm confident there shouldn't be any issue with them.

>Nit: can we make the PR title match the commit?

Done.

> should we make `t.Cockroach()` private? Is there still a legitimate use for it?

The `autoupgrade` and `schemachange/mixed-versions` still use it. The latter should be ported  to the new mixed-version framework though so not sure if it will be still using it then. Besides those two, it's not being called anywhere else in roachtests so yes I think we could make it private if autoupgrade is addressed. 

I didn't dig too deeply into it, but is there a reason why we can't port `autoupgrade` to the new framework? I see it has the warning at the top to not use it for mixed-version but it doesn't explain why.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-:-NifCSBhErXx8F57U-n3:b3p0tos)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster.go` line 1839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-NiepTxS7r5w6_DEl0qf:-NifGYw7AM1FCZMIlkGI:b-l8l8bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdd2b4054e4b4c785653b3d101ce583877e299d0/pkg/cmd/roachtest/cluster.go#L1839)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Not sure about that; this function is uploading a file to the cluster. Most other functions that do this live in the cluster level (e.g., `PutLibraries`, `PutString`, `Put` itself, `Stage`, etc.)
</blockquote></details>

I'm content with either location but yeah Renato's logic is why I originally had it in clusterImpl.
___
*[`pkg/cmd/roachtest/registry/test_spec.go` line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-NieqJYdAs8RN4I0GHo6:-Nif8Tk52YEYz_DgEUj3:blo6j92) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdd2b4054e4b4c785653b3d101ce583877e299d0/pkg/cmd/roachtest/registry/test_spec.go#L434)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] It's important to mention the default value when it's not specified.
</blockquote></details>

Done but also moved it along with other parts of the comment to the TestSpec struct to better reflect how the other comments are.

**Comment by RaduBerinde** [comment]
*[`pkg/cmd/roachtest/cluster.go` line 1839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-NiepTxS7r5w6_DEl0qf:-NifXlnO9B5tvs55OCHe:bj9afm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdd2b4054e4b4c785653b3d101ce583877e299d0/pkg/cmd/roachtest/cluster.go#L1839)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

I'm content with either location but yeah Renato's logic is why I originally had it in clusterImpl.
</blockquote></details>

Well.. this function is deciding which binary to upload and then calls `Put` to upload. Is the cluster or the test responsible for that decision?

More generally - should `clusterImpl` have to understand anything about `testImpl`?  If it's not necessary, it shouldn't. I know there are a few uses of `testImpl` already but they are pretty small and easily fixable.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113301)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @RaduBerinde, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster.go` line 1839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-NiepTxS7r5w6_DEl0qf:-NifZXzsD4ep8W_j5GSJ:b-18v2m4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdd2b4054e4b4c785653b3d101ce583877e299d0/pkg/cmd/roachtest/cluster.go#L1839)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Well.. this function is deciding which binary to upload and then calls `Put` to upload. Is the cluster or the test responsible for that decision?

More generally - should `clusterImpl` have to understand anything about `testImpl`?  If it's not necessary, it shouldn't. I know there are a few uses of `testImpl` already but they are pretty small and easily fixable.
</blockquote></details>

IMO, there's no decision being made here. The cluster is reading the option chosen by the user, if any, and calling `Put` based on that. In case the choice is randomized, the actual choosing logic _is_ in the `testImpl`.

**Comment by RaduBerinde** [comment]
*[`pkg/cmd/roachtest/cluster.go` line 1839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-NiepTxS7r5w6_DEl0qf:-Nifa8oG4tklmrlLPomd:b-puqm9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdd2b4054e4b4c785653b3d101ce583877e299d0/pkg/cmd/roachtest/cluster.go#L1839)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

IMO, there's no decision being made here. The cluster is reading the option chosen by the user, if any, and calling `Put` based on that. In case the choice is randomized, the actual choosing logic _is_ in the `testImpl`.
</blockquote></details>

Fine with me either way (always the case with nits).

**Review by renatolabs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113301#-:-NijS6VC8MP_Ybvc_6lj:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong and @srosenberg)

**Comment by renatolabs** [comment]
Looks good, thanks @DarrylWong!

**Comment by DarrylWong** [comment]
TFTRs!!!

bors r=renatolabs, RaduBerinde

**Comment by rafiss** [comment]
no need to rush, but i just wanted to check if this is getting backported to 23.1? if so, i will wait on it before merging https://github.com/cockroachdb/cockroach/pull/114197

**Comment by DarrylWong** [comment]
Yes but the backport is dependent on #113894 being backported and the plan for that is to wait until we can shake out all the runtime assertion flakes. Given the amount of flakes we've seen so far, I don't think we're in a rush to but someone else feel free to correct me.

Maybe it's worth it to just stick a `c.Put()` in there for the backport if you think the additional few weeks of test coverage is worth it? I can always remove it as part of this backport and worst case it wouldn't break anything if forgotten about.

**Comment by rafiss** [comment]
> Maybe it's worth it to just stick a c.Put() in there for the backport if you think the additional few weeks of test coverage is worth it? 

sounds good! i will do that

**Pull request merged**
