### PR TITLE
kvserver: add deadline to ClearRange

### PR DESCRIPTION
**Pull request by dt**
In many cases we would like to quickly and cheaply empty a key-range
and then make it available for SQL traffic. ClearRange is good at
quickly and cheaply emptying a key-range, but currently fears that
a copy of a ClearRange request could get replayed later make us fear
using it on a span which will later be sent writes -- if that replay
were to happen after writes resume, we could accidentally clear those
writes.

This change adds a Deadline parameter to ClearRange which the caller
can set to a timestamp to instruct the server to refuse to execute the
ClearRange request at or after that time. Thus if a caller sends the
ClearRanges with some deadline X, it can then wait until X (plus the
max clock offset) and then resume writing to the span it cleared. If
for any reason one of its ClearRange requests got stuck and a copy
pops out of a buffer after the deadline, it will have no effect.

Release note: none.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: this seems good. I'm curious how you picture people using it though. Where will the "unsafe to reuse until X" state be stored in those cases?

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52739#-:-MEcOKk65pNAquGRms12:buqvn16)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range_test.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52739#-MEcO-sS6pVVZAijX27d:-MEcO-sS6pVVZAijX27e:bhl5c9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a7b2172bd63232eaef3478646a3c7bdab3bba0f/pkg/kv/kvserver/batcheval/cmd_clear_range_test.go#L187)):*
> ```Go
> 	// no deadline
> 	args.Deadline = hlc.Timestamp{}
> 	if _, err := ClearRange(ctx, batch, cArgs, &roachpb.ClearRangeResponse{}); err != nil {
> ```

nit: make an assertion about what the error is, not just that there is an error.

**Comment by dt** [comment]
I was expecting the cleanup op to pick a "notOnlineBefore" time as e.g. now()+10s, then send its clearranges with that time, then when it moves on to the "bring this span back online" op, wait until at least that time. 
We _could_ persist the not-online-before time in the cleanup job progress, but I don't think we actually need to: as long as this whole block does not persist progress, if it is killed and resumes again later, it'll pick a new notOnlineBefore time even further in the future, run more (now maybe noop) clear-ranges, then sleep until that time, so we should be fine.

**Comment by dt** [comment]
We _could_ persist a "reject MVCC writes until" time in the range desc and ratchet it up to Deadline when executing ClearRange instead, but I'm fine with saying this is still on the caller for now.

**Comment by nvanbenschoten** [comment]
> I was expecting the cleanup op to pick a "notOnlineBefore" time as e.g. now()+10s, then send its clearranges with that time, then when it moves on to the "bring this span back online" op, wait until at least that time.

This SGTM.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52739)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range_test.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52739#-MEcO-sS6pVVZAijX27d:-MEd7Qnq4ZiQL-gnkLbD:b-yf6zkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a7b2172bd63232eaef3478646a3c7bdab3bba0f/pkg/kv/kvserver/batcheval/cmd_clear_range_test.go#L187)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: make an assertion about what the error is, not just that there is an error.
</blockquote></details>

Good point -- I turned the error into `ConditionFailedError` so we can actually test the error type in our caller to know if we need to try again with an extended deadline.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52739)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @nvanbenschoten)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range_test.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52739#-MEcO-sS6pVVZAijX27d:-MEd8U0V7AOV5yPPxLbD:bwnumoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a7b2172bd63232eaef3478646a3c7bdab3bba0f/pkg/kv/kvserver/batcheval/cmd_clear_range_test.go#L187)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Good point -- I turned the error into `ConditionFailedError` so we can actually test the error type in our caller to know if we need to try again with an extended deadline.
</blockquote></details>

Hold on, that should not be a `ConditionFailedError`. A condition failed error has a very specific meaning and there's no reason to generalize it so we can use it here. Either introduce a new error type or just match on the string if we just want this for tests. I'd recommend the latter.

**Comment by dt** [comment]
heh, okay. I was thinking I could make the case that the exec time is a condition which must be fulfilled to execute, and that condition failed here so we couldn't exec it, so this error type is appropriate. I could make a more general "PreconditionFailed" error too but then I wasn't sure how you'd differentiate conditionfailed?

I'm fine doing a plain string though. I really didn't want to add a new error type and mess with all the unions and whatnot if I could avoid it (though that is what andrei suggested).

**Comment by dt** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
