### PR TITLE
Adds a health reducer and a disconnected banner

### PR DESCRIPTION
**Pull request by maxlang**
Missing a few simple tests for the health reducer.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7149)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[ui/next/app/containers/layout.tsx, line 10 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJJAhDgpHJiZijlGF:-KJrJJAio1h3Ehco7cL2:1185964102) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/layout.tsx#L10)):*
> ```XML
> import Header from "../components/layoutHeader";
> import TimeWindowManager from "../containers/timewindow";
> import Banner from "../containers/banner/bannerContainer";
> ```

should that directory be called banners? also, doesn't seem like we capitalize filenames. also, is bannerContainer the right name? perhaps "base"?

---

*[ui/next/app/containers/banner/banner.tsx, line 19 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJZG4FSjmCUCpyW5S:-KJrJZG4FSjmCUCpyW5T:-713221218) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/banner/banner.tsx#L19)):*
> ```XML
>  */
> export default class extends React.Component<BannerProps, {}> {
> ```

nit: how come there is a newline here? i've left this comment before, but the convention isn't clear to me (there's no newline in the interface above).

---

*[ui/next/app/containers/banner/banner.tsx, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJh1aYKKU9XtE_ZJE:-KJrJh1aYKKU9XtE_ZJF:-497571702) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/banner/banner.tsx#L25)):*
> ```XML
>     visible: false,
>   };
> ```

double newline

---

*[ui/next/app/containers/banner/banner.tsx, line 42 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJhtn_Vxp68qowVQ2:-KJrJhtoMC_E4fKiTNpK:408057437) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/banner/banner.tsx#L42)):*
> ```XML
>     </div>;
>   }
> }
> ```

missing newline =/

---

*[ui/next/app/containers/banner/disconnectedBanner.tsx, line 54 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJq-UIMeul65qaK2D:-KJrJq-UIMeul65qaK2E:-97877707) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/banner/disconnectedBanner.tsx#L54)):*
> ```XML
> )(DisconnectedBanner);
> 
> export default disconnectedBannerConnected;
> ```

missing newline

---

*[ui/next/app/util/api.ts, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrK4D5XgPM-yK4LwKW:-KJrK4D5XgPM-yK4LwKX:-97877707) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/util/api.ts#L157)):*
> ```XML
> export function getHealth(req: HealthRequest = {}): Promise<HealthResponseMessage> {
>   return Fetch(serverpb.HealthResponse, `${API_PREFIX}/health`);
> }
> ```

missing newline

---

*[ui/styl/partials/layout.styl, line 335 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrKJ9q3zEkoDaOiqm_:-KJrKJ9q3zEkoDaOiqma:1313663657) ([raw file](https://github.com/cockroachdb/cockroach/blob/349d83fd8d031968f3361c317fde787a5b0c9231/ui/styl/partials/layout.styl#L335)):*
> ```Stylus
>   position relative
> 
>   &.helpus
> ```

what's this about?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149)*

**Comment by maxlang** [comment]
Review status: 5 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[ui/next/app/containers/layout.tsx, line 10 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJJAhDgpHJiZijlGF:-KK2cqp46y2FfhcxI5g3:971775965) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/layout.tsx#L10)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> should that directory be called banners? also, doesn't seem like we capitalize filenames. also, is bannerContainer the right name? perhaps "base"?
</details>
We capitalize `clusterOverview` and `metricsDataProvider` but I'm not sure we have an official convention. 

The "Banner" which here is `bannerContainer` holds all the other banners which optionally appear depending on internal criteria. Previously it was in `banner.ts` -  I'm not sure what the appropriate name is, but I'm open to suggestions.

---

*[ui/next/app/containers/banner/banner.tsx, line 19 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJZG4FSjmCUCpyW5S:-KK2dp1jN3w_ytdehgSt:1609070309) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/banner/banner.tsx#L19)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: how come there is a newline here? i've left this comment before, but the convention isn't clear to me (there's no newline in the interface above).
</details>
I'm not sure there is a convention here. I deleted the newline here.

---

*[ui/next/app/containers/banner/banner.tsx, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJh1aYKKU9XtE_ZJE:-KK2cTagyXAtmoVAeTvk:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/banner/banner.tsx#L25)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> double newline
</details>
Done.

---

*[ui/next/app/containers/banner/banner.tsx, line 42 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJhtn_Vxp68qowVQ2:-KK2cXk_-RSkNeC6-1gi:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/banner/banner.tsx#L42)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> missing newline =/
</details>
Done.

---

*[ui/next/app/containers/banner/disconnectedBanner.tsx, line 54 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJq-UIMeul65qaK2D:-KK2cYnJ6MrGyshc3h_b:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/banner/disconnectedBanner.tsx#L54)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> missing newline
</details>
Done.

---

*[ui/next/app/util/api.ts, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrK4D5XgPM-yK4LwKW:-KK2cZY1ol1k_I8aJkAB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/util/api.ts#L157)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> missing newline
</details>
Done.

---

*[ui/styl/partials/layout.styl, line 335 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrKJ9q3zEkoDaOiqm_:-KK2cbFhnyJ-yCsHWl3k:-49352768) ([raw file](https://github.com/cockroachdb/cockroach/blob/349d83fd8d031968f3361c317fde787a5b0c9231/ui/styl/partials/layout.styl#L335)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what's this about?
</details>
I'm now using `.expanded` and `.hidden` for all banners, not just the `.helpus` banner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149)*

**Comment by mrtracy** [comment]
Review status: 5 of 10 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[ui/next/app/containers/banner/disconnectedBanner.tsx, line 26 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK560e2bxJQ-QBMPrRE:-KK560e2bxJQ-QBMPrRF:873319789) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbf3c6e1cce0545f0329474ac823eed0bc41cb7/ui/next/app/containers/banner/disconnectedBanner.tsx#L26)):*
> ```XML
>     props.refreshHealth();
>     if (props.health.valid && !props.health.lastError) {
>       this.setState({ dismissed: false });
> ```

This doesn't appear to be truly dismissible.  It appears that it will come back every ten seconds until the connection to the cluster is restored.  Is that intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149)*

**Comment by maxlang** [comment]
Review status: 5 of 10 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[ui/next/app/containers/banner/disconnectedBanner.tsx, line 26 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK560e2bxJQ-QBMPrRE:-KK7Udy2Nqo9RDImPTF6:990876340) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbf3c6e1cce0545f0329474ac823eed0bc41cb7/ui/next/app/containers/banner/disconnectedBanner.tsx#L26)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> This doesn't appear to be truly dismissible.  It appears that it will come back every ten seconds until the connection to the cluster is restored.  Is that intentional?
</details>
When testing this out locally it appears to work. The code specifies that the data must be `valid` and that there can't be a `lastError`. This will only be true if a request has succeeded, which should only happen if the server is actually reachable. Notably, in the reducer, only `RECEIVE` - a successful response - clears our `lastError`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149)*

**Comment by maxlang** [comment]
Review status: 5 of 12 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[ui/next/app/containers/layout.tsx, line 10 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KJrJJAhDgpHJiZijlGF:-KK7_4gkQ979YEHL3fJE:1676013605) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3dd8720fe3d6e6f4938b7470c809c81dd35730/ui/next/app/containers/layout.tsx#L10)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> We capitalize `clusterOverview` and `metricsDataProvider` but I'm not sure we have an official convention. 
> 
> The "Banner" which here is `bannerContainer` holds all the other banners which optionally appear depending on internal criteria. Previously it was in `banner.ts` -  I'm not sure what the appropriate name is, but I'm open to suggestions.
</details>
I should add that I called the folder `banner` because there's it contains all the code for the `banner` component which appears at the top of the page, even though there might be a bunch of different content that appears in that space. You could consider those all to be separate "banners" or a single "banner" which holds different information depending on the application state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149)*

**Comment by tamird** [comment]
quick reminder to squash these commits before merging

<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> #### Adds a health reducer and a disconnected banner
> 
> Missing a few simple tests for the health reducer.
> 
> 
> 
</details>


---

Reviewed 4 of 5 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[ui/next/app/containers/banner/disconnectedBanner.tsx, line 39 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8gZ7viB5YphkVqz02:-KK8gZ7viB5YphkVqz03:1342907272) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5aa675b237a7bbe80def0238b3b4749abdd0f/ui/next/app/containers/banner/disconnectedBanner.tsx#L39)):*
> ```XML
> }
> 
> let health = (state: any): HealthState => state && state.health && state.health;
> ```

can we stop using `any` this way? Seems like we could have a narrow interface to define legal states for these components.

---

*[ui/next/app/redux/health.spec.ts, line 42 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8h4J9rDKdvhU4KzEV:-KK8h4J9rDKdvhU4KzEW:-669290164) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5aa675b237a7bbe80def0238b3b4749abdd0f/ui/next/app/redux/health.spec.ts#L42)):*
> ```XML
>     it("should correctly dispatch requestHealth", function () {
>       state = reducer(state, health.requestHealth());
>       let expected = {
> ```

nit: most existing tests don't have this intermediate, they pass a literal to deepEqual.

---

*[ui/next/app/redux/health.spec.ts, line 50 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8gKz8FWIUmYxSTzPi:-KK8gKz8FWIUmYxSTzPj:677459241) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5aa675b237a7bbe80def0238b3b4749abdd0f/ui/next/app/redux/health.spec.ts#L50)):*
> ```XML
> 
>     it("should correctly dispatch receiveHealth", function () {
>       let e = new protos.cockroach.server.serverpb.HealthResponse();
> ```

`e`?

---

*[ui/next/app/redux/health.spec.ts, line 57 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8gyTNGBALDEjbEnve:-KK8gyTNGBALDEjbEnvf:2016847414) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5aa675b237a7bbe80def0238b3b4749abdd0f/ui/next/app/redux/health.spec.ts#L57)):*
> ```XML
>         valid: true,
>         data: e,
>         lastError: <any>null,
> ```

why the type annotation?

---

*[ui/next/app/util/api.spec.ts, line 407 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8ftm7KYLkkFH_O3Un:-KK8ftm7KYLkkFH_O3Uo:-869362443) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5aa675b237a7bbe80def0238b3b4749abdd0f/ui/next/app/util/api.spec.ts#L407)):*
> ```XML
>   });
> 
>   describe("health request", function() {
> ```

metacomment: there is a lot of repetition in these tests, testing a bunch of functions that are really identical. we should be testing makefetch rather than every one of its return values =/

---

*[ui/next/app/util/api.spec.ts, line 408 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8fkES7vU8mWhIYQtq:-KK8fkES7vU8mWhIYQtr:-1984774107) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5aa675b237a7bbe80def0238b3b4749abdd0f/ui/next/app/util/api.spec.ts#L408)):*
> ```XML
> 
>   describe("health request", function() {
>     let healthUrl = `^${api.API_PREFIX}/health`;
> ```

there's no need for this to be a regex

---

*[ui/next/app/util/api.spec.ts, line 435 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8fVT_VJjdcJ482x7K:-KK8fVT_VJjdcJ482x7L:-1123203789) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5aa675b237a7bbe80def0238b3b4749abdd0f/ui/next/app/util/api.spec.ts#L435)):*
> ```XML
>       fetchMock.mock(healthUrl, "get", (url: string, requestObj: RequestInit) => {
>         assert.isUndefined(requestObj.body);
>         return { status: 500 };
> ```

you should use `throws` - this only happens to work because JSON parsing will fail on a 500 with no body.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-:-KK8hNwUlqDNi3yTtO8O:-401536121)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[ui/next/app/containers/banner/disconnectedBanner.tsx, line 26 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK560e2bxJQ-QBMPrRE:-KK9TYSlqEqrt-AHqhrR:-1281782259) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbf3c6e1cce0545f0329474ac823eed0bc41cb7/ui/next/app/containers/banner/disconnectedBanner.tsx#L26)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> When testing this out locally it appears to work. The code specifies that the data must be `valid` and that there can't be a `lastError`. This will only be true if a request has succeeded, which should only happen if the server is actually reachable. Notably, in the reducer, only `RECEIVE` - a successful response - clears our `lastError`.
</details>
Yeah, I misread it.

---

*[ui/next/app/containers/banner/disconnectedBanner.tsx, line 39 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8gZ7viB5YphkVqz02:-KK9TahmN2CiKRAjne0X:2121509163) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5aa675b237a7bbe80def0238b3b4749abdd0f/ui/next/app/containers/banner/disconnectedBanner.tsx#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can we stop using `any` this way? Seems like we could have a narrow interface to define legal states for these components.
</details>
There is a big comment in `app.tsx` about this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149)*

**Comment by mrtracy** [comment]
:lgtm:

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> quick reminder to squash these commits before merging
</details>


---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-:-KK9TmSiMjhRxa0CwNnR:1417088721)*

**Comment by maxlang** [comment]
Squashed.

<details><summary><i>Previously, mrtracy wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 10 of 15 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[ui/next/app/redux/health.spec.ts, line 42 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8h4J9rDKdvhU4KzEV:-KK9eKLZyreHtI_kbo8T:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d64ec463f41b8279961a949da669d689713c1e/ui/next/app/redux/health.spec.ts#L42)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: most existing tests don't have this intermediate, they pass a literal to deepEqual.
</details>
Done.

---

*[ui/next/app/redux/health.spec.ts, line 50 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8gKz8FWIUmYxSTzPi:-KK9dscnEmo89ixLA8Qh:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d64ec463f41b8279961a949da669d689713c1e/ui/next/app/redux/health.spec.ts#L50)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `e`?
</details>
Done.

---

*[ui/next/app/redux/health.spec.ts, line 57 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8gyTNGBALDEjbEnve:-KK9e5hh8J6v-vkRrjJt:1272557296) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d64ec463f41b8279961a949da669d689713c1e/ui/next/app/redux/health.spec.ts#L57)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why the type annotation?
</details>
I'm creating an object literal. If I don't specify `expected`'s type, `lastError`'s type would be implicitly `any`. I'll move these inline like you wanted and it should go away.

---

*[ui/next/app/util/api.spec.ts, line 407 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8ftm7KYLkkFH_O3Un:-KK9ezS6TfQi_tTai-kB:-2140365362) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d64ec463f41b8279961a949da669d689713c1e/ui/next/app/util/api.spec.ts#L407)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> metacomment: there is a lot of repetition in these tests, testing a bunch of functions that are really identical. we should be testing makefetch rather than every one of its return values =/
</details>
I might not have the best testing philosophy, but my understanding was that it's ok to have a lot of repetition in tests.

I agree we should test makeFetch as well, but shouldn't we also test each endpoint?

---

*[ui/next/app/util/api.spec.ts, line 408 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8fkES7vU8mWhIYQtq:-KK9ez5ZL6Ap78UwLCxe:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d64ec463f41b8279961a949da669d689713c1e/ui/next/app/util/api.spec.ts#L408)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there's no need for this to be a regex
</details>
Done.

---

*[ui/next/app/util/api.spec.ts, line 435 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8fVT_VJjdcJ482x7K:-KK9iQodTSNcfnXYIlmY:-1620543529) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d64ec463f41b8279961a949da669d689713c1e/ui/next/app/util/api.spec.ts#L435)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> you should use `throws` - this only happens to work because JSON parsing will fail on a 500 with no body.
</details>
Done. And fixed elsewhere in the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-:-KK9iUXb9t2XA1qH7dS3:-1852829109)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[ui/next/app/redux/metrics.spec.ts, line 231 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK9qHXpS1PqIbydY_iq:-KK9qHXpS1PqIbydY_ir:-2027832325) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f85b6a6be19f58ab39c6dbaee8ab28fde70f442/ui/next/app/redux/metrics.spec.ts#L231)):*
> ```XML
> 
>           if (successSent) {
>             return { status: 500, throws: new Error() };
> ```

throughout: you don't need both status and throws - the status does nothing in this case

---

*[ui/next/app/util/api.spec.ts, line 407 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8ftm7KYLkkFH_O3Un:-KK9qXhY_MIDE4E-az8k:961802787) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d64ec463f41b8279961a949da669d689713c1e/ui/next/app/util/api.spec.ts#L407)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I might not have the best testing philosophy, but my understanding was that it's ok to have a lot of repetition in tests.
> 
> I agree we should test makeFetch as well, but shouldn't we also test each endpoint?
</details>
I mean, ok, you can have repetition, but you may as well have a `testFetch` helper that is generic the same way that `makeFetch` is - there's no reason for there to be more repetition in tests than there is in app code =/

---

*[ui/next/app/util/api.spec.ts, line 439 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK9qW1jUX2sTWFDrpil:-KK9qW1jUX2sTWFDrpim:5174872) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f85b6a6be19f58ab39c6dbaee8ab28fde70f442/ui/next/app/util/api.spec.ts#L439)):*
> ```XML
> 
>       api.getHealth().then((result) => {
>         console.log("HERE");
> ```

uh

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149)*

**Comment by maxlang** [comment]
Review status: 11 of 15 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[ui/next/app/redux/metrics.spec.ts, line 231 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK9qHXpS1PqIbydY_iq:-KKBQoEZSS1BwIm2HMsF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d674c15fdb05085de38e9f1f6c00c11f3d2e66f/ui/next/app/redux/metrics.spec.ts#L231)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> throughout: you don't need both status and throws - the status does nothing in this case
</details>
Done.

---

*[ui/next/app/util/api.spec.ts, line 407 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK8ftm7KYLkkFH_O3Un:-KKBOf2TQIX4eDRDQmmn:1737567527) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d64ec463f41b8279961a949da669d689713c1e/ui/next/app/util/api.spec.ts#L407)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I mean, ok, you can have repetition, but you may as well have a `testFetch` helper that is generic the same way that `makeFetch` is - there's no reason for there to be more repetition in tests than there is in app code =/
</details>
I'm going to work on removing a lot of the code that is currently duplicated in the new UI (the reducers and database pages have a lot of copy paste) in a future PR.

I actually thought it was ok to have more copy-paste in test code vs app code, the idea being that tests should be testing something simple and doing it explicitly. That said, I can agree there's too much repetition here.

---

*[ui/next/app/util/api.spec.ts, line 439 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149#-KK9qW1jUX2sTWFDrpil:-KKBOcyiHU3sfBG4C1dH:-1716163591) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d674c15fdb05085de38e9f1f6c00c11f3d2e66f/ui/next/app/util/api.spec.ts#L439)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> uh
</details>
Whoops. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7149)*

**Pull request merged**
