### PR TITLE
storage: add a bench that uses block properties to find old data

### PR DESCRIPTION
**Pull request by sumeerbhola**
This may be useful for scans that look for expired data based
on TTL where this data is all in L6, so is not amenable to
optimization based on file level time bounds, but block level
time bounds could be useful. See the comment in the benchmark for
key decoding considerations.

```
BenchmarkMVCCIncrementalIteratorForOldData/valueSize=100/useTBI=true-16         	     643	   1918341 ns/op
BenchmarkMVCCIncrementalIteratorForOldData/valueSize=100/useTBI=false-16        	    1015	   1241755 ns/op
BenchmarkMVCCIncrementalIteratorForOldData/valueSize=500/useTBI=true-16         	    1339	    785697 ns/op
BenchmarkMVCCIncrementalIteratorForOldData/valueSize=500/useTBI=false-16        	     690	   1748273 ns/op
BenchmarkMVCCIncrementalIteratorForOldData/valueSize=1000/useTBI=true-16        	    2427	    511270 ns/op
BenchmarkMVCCIncrementalIteratorForOldData/valueSize=1000/useTBI=false-16       	     558	   2064947 ns/op
BenchmarkMVCCIncrementalIteratorForOldData/valueSize=2000/useTBI=true-16        	    2522	    468096 ns/op
BenchmarkMVCCIncrementalIteratorForOldData/valueSize=2000/useTBI=false-16       	     297	   4267396 ns/op
```

The slowdown in the first case is because we have to use 2 iterators in
MVCCIncrementalIterator to avoid finding non-existent keys (even though
they are rare). About 55% of the incremental iterator cpu is spent on
MVCCIncrementalIterator.iter in these benchmarks so if one were
willing to admit false positives, and make the case of not finding the
key when actually doing the expiry a noop, the speedups can be even more
significant.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
cc @otan (in case it has a bearing on the ongoing TTL work), @dt 

the benchmark is uniformly distributing the old keys, which makes it harder to skip blocks, until the (key+value) size becomes larger  -- it is unclear to me how representative that is.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74089#-:-MrNvsfeEatHIIg3yj8q:b-tpdo8e)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74089#-:-MrTQaMTCfTZw9giUTMR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by sumeerbhola** [comment]
TFTR!

**Pull request merged**
