### PR TITLE
sql: refactor StatementStatistics and add network messages

### PR DESCRIPTION
**Pull request by asubiotto**
Please take a look at individual commits for details.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60787#-:-MTvzFaE4iZxVGYrUSia:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by asubiotto** [comment]
TFTR

bors r=RaduBerinde

**Comment by asubiotto** [comment]
These test failures look like flakes unrelated to this PR (e.g. changefeedccl timeout to be skipped https://github.com/cockroachdb/cockroach/issues/57754) so will rerun bors.

bors r=RaduBerinde

**Comment by asubiotto** [comment]
Woops, forgot to update UI code.

**Review by dhartunian — APPROVED** [review]
:lgtm: I did notice the similarities in the protos while looking at other stuff today, thx for making this change!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60787#-:-MUBFdMc4asb9sDmZJSI:b-my9v4x)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Comment by asubiotto** [comment]
TFTRs!

bors r=RaduBerinde,dhartunian

**Pull request merged**
