### PR TITLE
sql: hack to support date offsets missing zero-padding

### LINKED ISSUE #7865: sql: DATE values cannot be parsed from JDBC-generated DATE string inputs
Hi, 

Im trying to insert a date using a prepared statement, however all the approaches I tried result in errors: 

```
ERROR: error in argument for $3: could not parse string "2016-7-17 -4:0:0" as date
```

Below is a simple example of the error (added date to the example from website).

```sql
CREATE TABLE accounts (id INT PRIMARY KEY, balance INT, cdate DATE)'
```

```java
PreparedStatement prepareStatement = db.prepareStatement("INSERT INTO accounts (id, balance, cdate) VALUES ( ?, ?, ? )");

prepareStatement.setObject(1, 1);
prepareStatement.setObject(2, 1000);
prepareStatement.setObject(3, new java.sql.Date(System.currentTimeMillis()));
// works: prepareStatement.setObject(3, "2011-01-11" );

prepareStatement.execute();
```

### PR DESCRIPTION
**Pull request by dt**
Fixes #7865

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7929)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[acceptance/java_test.go, line 117 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3z-h3K8d4dNVX2GKS:-KN3z-h3K8d4dNVX2GKT:-1120936214) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/acceptance/java_test.go#L117)):*
> ```Go
> 		stmt.setObject(3, new java.sql.Date( System.currentTimeMillis() ) );
> 
> 		stmt.executeUpdate();
> ```

Should we check the result of this?

---

*[sql/parser/datum.go, line 662 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3z8rDMzV_Pc_e5n8b:-KN3z8rDMzV_Pc_e5n8c:-802713806) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/parser/datum.go#L662)):*
> ```Go
> var dateFormats = []string{
> 	dateFormat,
> 	dateFormat + " -07:00:00",
> ```

It would be easier to understand what's going on if these were well named constants.

---

*[sql/parser/datum.go, line 679 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3z_Nd0AydXjv0ce-l:-KN3z_Nd0AydXjv0ce-m:-1786745696) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/parser/datum.go#L679)):*
> ```Go
> 
> 	// HACK: go doesn't handle offsets that are not zero-padded from psql/jdbc.
> 	// Thus, if we see `2015-10-05 +0:0:0` we need to change it to `+00:00:00`.
> ```

Would there ever be a need to handle mixed zero padding (ie. `+0:00:0`)?

---

*[sql/parser/datum.go, line 680 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3znSMWfZMh8yoxJmq:-KN3znSMWfZMh8yoxJmr:-133964482) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/parser/datum.go#L680)):*
> ```Go
> 	// HACK: go doesn't handle offsets that are not zero-padded from psql/jdbc.
> 	// Thus, if we see `2015-10-05 +0:0:0` we need to change it to `+00:00:00`.
> 	if l := len(s); l > 6 && s[l-2] == ':' && s[l-4] == ':' && (s[l-6] == '+' || s[l-6] == '-') {
> ```

If this is a common case (I'm not sure if it actually is), we might want to catch it before allowing the parse error. It will avoid multiple calls to `time.Parse`, and will avoid the `error` allocation.

---

*[sql/parser/eval_test.go, line 143 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3zQiBNyu1_TIBrsMV:-KN3zQiCq9A1RzeCEKNG:-1986427436) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/parser/eval_test.go#L143)):*
> ```Go
> 		{`'2015-10-01'::date = '2015-10-02'::date`, `false`},
> 		{`'2015-10-01'::date = '2015-10-01'::date`, `true`},
> 		{`'2016-7-19 +0:0:0'::date = '2016-07-19'::date`, `true`},
> ```

Do we need a test for both new date formats?

---

*[sql/pgwire/types.go, line 630 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN4-6NN7jc7iNEXVRSR:-KN4-6NN7jc7iNEXVRSS:341296048) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/pgwire/types.go#L630)):*
> ```Go
> 			ts, err := parseTs(string(b))
> 			if err != nil {
> 				if res, err := parser.ParseDDate(string(b), time.UTC); err == nil {
> ```

This could use a comment. We might also want to move the logic into `parseTs`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929)*

**Comment by dt** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[acceptance/java_test.go, line 117 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3z-h3K8d4dNVX2GKS:-KN4-wQoey3XgztiteNT:149002748) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/acceptance/java_test.go#L117)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Should we check the result of this?
</details>
it'll throw if it fails so it should be fine without checking that it returned `1`?

---

*[sql/parser/datum.go, line 679 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3z_Nd0AydXjv0ce-l:-KN406KNyVlmoq77ECxr:-715876226) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/parser/datum.go#L679)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Would there ever be a need to handle mixed zero padding (ie. `+0:00:0`)?
</details>
I don't _think_ so, but I really don't know.

This approach is obviously brittle -- if it turns out we need to be even more flexible, we might need to just make/maintain our own first-class time parser (or fork time.Parse and go from there).

---

*[sql/parser/datum.go, line 680 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3znSMWfZMh8yoxJmq:-KN415H-ZBUa4izCT0FD:-1858998004) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/parser/datum.go#L680)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> If this is a common case (I'm not sure if it actually is), we might want to catch it before allowing the parse error. It will avoid multiple calls to `time.Parse`, and will avoid the `error` allocation.
</details>
i guess we could do this if and just replace the str before the loop -- i was thinking I only wanted to mess with it once we were otherwise resigned to failure since it is a kinda dirty hack, but that might hurt a high-qps JDBC client that hits this path all the time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929)*

**Comment by dt** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/parser/datum.go, line 662 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3z8rDMzV_Pc_e5n8b:-KN43GpXTGUczKb7ycw2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/parser/datum.go#L662)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> It would be easier to understand what's going on if these were well named constants.
</details>
Done.

---

*[sql/parser/datum.go, line 680 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3znSMWfZMh8yoxJmq:-KN42Ig2xmxvE0THutjh:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/parser/datum.go#L680)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> i guess we could do this if and just replace the str before the loop -- i was thinking I only wanted to mess with it once we were otherwise resigned to failure since it is a kinda dirty hack, but that might hurt a high-qps JDBC client that hits this path all the time.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929)*

**Comment by nvanbenschoten** [comment]
:lgtm: mod the `parseTs` comment. It would be more straightforward to encapsulate all parsing in the `parseTs` function if possible.

---

Reviewed 1 of 1 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-:-KN4d4vOh989BHlsSM5N:-1322538935)*

**Comment by tamird** [comment]
Reviewed 1 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[acceptance/java_test.go, line 115 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN5EjwQb6VbOeQvieJZ:-KN5EjwRNxkHLBLsLAwW:-2000923467) ([raw file](https://github.com/cockroachdb/cockroach/blob/978e71f73e8ef96f46d903b533549e56df2f56a1/acceptance/java_test.go#L115)):*
> ```Go
> 		stmt.setObject(1, 1);
> 		stmt.setObject(2, 1000);
> 		stmt.setObject(3, new java.sql.Date( System.currentTimeMillis() ) );
> ```

what's with all the spaces?

---

*[acceptance/java_test.go, line 117 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN5EvM3Ae_pqJvXqrSd:-KN5EvM3Ae_pqJvXqrSe:-1984871584) ([raw file](https://github.com/cockroachdb/cockroach/blob/978e71f73e8ef96f46d903b533549e56df2f56a1/acceptance/java_test.go#L117)):*
> ```Go
> 		stmt.setObject(3, new java.sql.Date( System.currentTimeMillis() ) );
> 
> 		stmt.executeUpdate();
> ```

no check on the return value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929)*

**Comment by dt** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[acceptance/java_test.go, line 115 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN5EjwQb6VbOeQvieJZ:-KN8ZoqoMhAKg80Y_j7i:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/978e71f73e8ef96f46d903b533549e56df2f56a1/acceptance/java_test.go#L115)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what's with all the spaces?
</details>
Done.

---

*[acceptance/java_test.go, line 117 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN5EvM3Ae_pqJvXqrSd:-KN7ijK62CqJIkLq99nC:477570712) ([raw file](https://github.com/cockroachdb/cockroach/blob/978e71f73e8ef96f46d903b533549e56df2f56a1/acceptance/java_test.go#L117)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> no check on the return value?
</details>
it's Java -- it throws exceptions when it doesn't work.

---

*[sql/parser/eval_test.go, line 143 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN3zQiBNyu1_TIBrsMV:-KN8ZyGCtEMB5Jxr1vqO:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/parser/eval_test.go#L143)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Do we need a test for both new date formats?
</details>
Done.

---

*[sql/pgwire/types.go, line 630 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-KN4-6NN7jc7iNEXVRSR:-KN8_2BIlqtmVkojWzid:1147034021) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74d9e493fcbaff925a104eb198bf192b34118b1/sql/pgwire/types.go#L630)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> This could use a comment. We might also want to move the logic into `parseTs`.
</details>
I'm starting to also think it might be nice to unify pgwire time parsing and parser time parsing, but I think I want to let @paperstreet chime in on that, and do so, if we decide to, in a followup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929)*

**Comment by dt** [comment]
commented inline, but originally those were separate because we thought maybe we'd have to parse different things in wire protocol (like some binary format someday) than the strings at the parser level. I'm thinking maybe it makes sense to unify and be willing to parse anything anywhere, but I want to let @mjibson and @paperstreet chime in on that, and I think it can be a standalone follow-up change if we do go that route.

---

Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-:-KN8cpDTKHRURdgU-p14:1242468159)*

**Comment by mjibson** [comment]
I'm in favor of unifying these implementations in a followup PR. I don't see a whole lot of benefit to having one be stricter than another.

---

Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7929#-:-KN8fsMZ7lYBGwS82WAN:-742948145)*

**Pull request merged**
