### PR TITLE
OWNERS,TEAMS: small fixes

### PR DESCRIPTION
**Pull request by tbg**
I went through some team-less test flakes and noticed a few that automation
could handle properly.

Epic: None
Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail and @tbg)

___
*[`TEAMS.yaml` line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBlZn4D3YQIG66xp_v:-NZBlZn4D3YQIG66xp_w:b-v623fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L35)):*
> ```YAML
>     cockroachdb/sql-optimizer: other
>     cockroachdb/sql-opt-prs: other
>   triage_column_id: 13549252
> ```

label: T-sql-queries
___
*[`TEAMS.yaml` line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBl4fy0QFcVeNZXNCr:-NZBl4fy0QFcVeNZXNCs:b-95uaps) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L37)):*
> ```YAML
>   triage_column_id: 13549252
> cockroachdb/cluster-observability:
>   triage_column_id: 12618343
> ```

label: T-cluster-observability
___
*[`TEAMS.yaml` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBl76-CqGmWBC9AX94:-NZBl76-CqGmWBC9AX95:bh60z3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L50)):*
> ```YAML
>   label: T-kv-replication
> cockroachdb/spatial:
>   triage_column_id: 9487269
> ```

label: T-spatial
___
*[`TEAMS.yaml` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBl8RVAjiKSRkJNob0:-NZBl8RVAjiKSRkJNob1:b567e1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L52)):*
> ```YAML
>   triage_column_id: 9487269
> cockroachdb/dev-inf:
>   triage_column_id: 10210759
> ```

label: T-dev-inf
___
*[`TEAMS.yaml` line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBlA1DBCFZT9uFKdwS:-NZBlA1DBCFZT9uFKdwT:bj9v57x) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L56)):*
> ```YAML
>   triage_column_id: 11926170
> cockroachdb/storage:
>   triage_column_id: 6668367
> ```

label: T-storage
___
*[`TEAMS.yaml` line 81 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBlKzu6VqtnE_xX-zT:-NZBlKzv76vuLE5VLcve:b-s3s07t) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L81)):*
> ```YAML
>   aliases:
>     cockroachdb/admin-ui-prs: other
>   triage_column_id: 6598672
> ```

label: T-observability-inf
___
*[`TEAMS.yaml` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBlU1_8dCH7d8UgmWG:-NZBlU1_8dCH7d8UgmWH:b-s3s07t) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L85)):*
> ```YAML
>   aliases:
>     cockroachdb/http-api-prs: other
>   triage_column_id: 14196277
> ```

label: T-observability-inf

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rail)

___
*[`TEAMS.yaml` line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBlZn4D3YQIG66xp_v:-NZBn2z20ro42Ktam9oF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L35)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

label: T-sql-queries
</blockquote></details>

Done.
___
*[`TEAMS.yaml` line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBl4fy0QFcVeNZXNCr:-NZBn2k-A7_-MkMazMwq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L37)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

label: T-cluster-observability
</blockquote></details>

Done.
___
*[`TEAMS.yaml` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBl76-CqGmWBC9AX94:-NZBnXdA9wofKuDOibu-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L50)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

label: T-spatial
</blockquote></details>

Done.
___
*[`TEAMS.yaml` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBl8RVAjiKSRkJNob0:-NZBnXsv-ZyZ3YDdmcZM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L52)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

label: T-dev-inf
</blockquote></details>

Done.
___
*[`TEAMS.yaml` line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBlA1DBCFZT9uFKdwS:-NZBnYHJ81LSxQZN9xmL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L56)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

label: T-storage
</blockquote></details>

Done.
___
*[`TEAMS.yaml` line 81 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBlKzu6VqtnE_xX-zT:-NZBnMaG34jpdP-y5waN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L81)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

label: T-observability-inf
</blockquote></details>

Done.
___
*[`TEAMS.yaml` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105881#-NZBlU1_8dCH7d8UgmWG:-NZBnOxpE8YmAzzZvTaz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a3daff78512cfd9ad6de46f21e9ea5485e4969/TEAMS.yaml#L85)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

label: T-observability-inf
</blockquote></details>

Done.

**Review by rickystewart — APPROVED** [review]

**Comment by tbg** [comment]
bors r=knz,rickystewart
TFTRs!

**Comment by tbg** [comment]
bors r=rickystewart,rail

**Pull request merged**
