### PR TITLE
row: minor refactor to reuse already allocated memory

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
@BramGruneir PTAL - does the lifetime of this scratch variable make sense?

**Comment by asubiotto** [comment]
Friendly ping

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir and @yuzefovich)

___
*[pkg/sql/row/fk_existence_batch.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37096#-Lgf8_qnAqkPR8_IZFni:-Lgf8_qp-cs6ybEG2pt1:bq70u26) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c5c1d6c4874fe4329f6663b579a78be12d2584/pkg/sql/row/fk_existence_batch.go#L110)):*
> ```Go
> 			// If we're inserting, then there's a violation if the scan found nothing.
> 			if fk.rf.kvEnd {
> 				if cap(f.fkValuesScratch) < fk.prefixLen {
> ```

fk.prefixLen is constant throughout the lifetime of fkExistenceBatchChecker. You can pre-allocate fkValuesScratch once in `makeFkExistenceCheckBaseHelper`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir and @knz)

___
*[pkg/sql/row/fk_existence_batch.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37096#-Lgf8_qnAqkPR8_IZFni:-LgmwdO41VMpTpWSVykQ:b-ucrsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c5c1d6c4874fe4329f6663b579a78be12d2584/pkg/sql/row/fk_existence_batch.go#L110)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

fk.prefixLen is constant throughout the lifetime of fkExistenceBatchChecker. You can pre-allocate fkValuesScratch once in `makeFkExistenceCheckBaseHelper`.
</blockquote></details>

Done, thanks. I wasn't 100% certain that it was constant.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37096#-:-LgnBMTz7F0fc62DBiw7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
