### PR TITLE
storage: don't recheck CanCreateTxnRecord on txn epoch bump

### PR DESCRIPTION
**Pull request by nvb**
This is an expected fix to an increase in transaction abort errors
that we're seeing on adriatic.

Before this change, each BeginTxn request that wrote a transaction
record would check CanCreateTxnRecord. This caused epoch bumps, which
result (unnecessarily) in BeginTxn requests with incremented epochs,
to be vulnerable to lease transfers and GCs. CanCreateTxnRecord only
needs to be called when a transaction record is missing, not when one
is being updated, so we can fix this by simply restricting the cases
that we check it in when evaluting BeginTxn requests.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
Update to reviewers: this didn't seem to fix the issues on adriatic, so the 2.2 alpha is now being tested with a revert for 8143b45814590ef5d98d4ef65614e799938cb66c, which seems to have done the trick

**Comment by nvanbenschoten** [comment]
Yeah, that's unfortunate. This is still a clear win though, as the new test cases demonstrate. No particular urgency here, although @andreimatei feel free to adapt and/or merge as you see fit if there's a chance this might fix any test flakiness.

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33651)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Pull request merged**
