### PR TITLE
release-21.2: server: extend the HTTP endpoint definitions

### PR DESCRIPTION
**Pull request by knz**
This is a scaled down version of #75852, which focuses on tighter checks on the SQL/debug endpoints.

### CODE REVIEW

**Comment by knz** [comment]
(I haven't yet backported the corresponding unit test fixes. Will do this after CI tells me which unit tests need to be fixed in this branch.)

**Review by dhartunian — APPROVED** [review]
:lgtm: thanks for the fix and for the easily-reviewable commits. just a tiny q about modified import.

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76066#-:-Mv4aRRhDsY4gld2hY3X:bnjd4vb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[pkg/server/server.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76066#-Mv4UWksC2Dmdms1zXHu:-Mv4UWksC2Dmdms1zXHv:b-1cal48) ([raw file](https://github.com/cockroachdb/cockroach/blob/a679f11270de1acb4b4730da9214b012231c0ffd/pkg/server/server.go#L112)):*
> ```Go
> 	"google.golang.org/grpc/metadata"
> 	grpcstatus "google.golang.org/grpc/status"
> 	yaml "gopkg.in/yaml.v2"
> ```

nit: why is this change made?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76066)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @stevendanna)

___
*[pkg/server/server.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76066#-Mv4UWksC2Dmdms1zXHu:-Mv4dOQy7kdzUOv2IxGq:bcmqi4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a679f11270de1acb4b4730da9214b012231c0ffd/pkg/server/server.go#L112)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: why is this change made?
</blockquote></details>

my editor does this automatically when the package path and name are different.

**Comment by knz** [comment]
will wait until #75852 is merged before I merge this.

**Pull request merged**
