### PR TITLE
sql, sqlstats: create temporary stats container for all txns

### LINKED ISSUE #81470: Transaction Details page has an empty statements table, caused by the transaction fingerprint ID for most statements not being populated in the endpoint response (and possibly deeper)
**Describe the problem**
First reported by @dbist.

The first symptom is that the Statements table in the Transactions Details page is empty, but all other parts of the page are populated.

Upon further inspection, it turns out that for the statements involved, the `transaction_fingerprint_id` column in the `statement_statistics` table is 0 instead of the transaction id. Accordingly, in the endpoint `key.key_data.transaction_fingerprint_id` is 0 instead of the transaction id.
image

This is is despite that in the endpoint response `transactions -> index 5 -> stats_data -> statement_fingerprint_ids` is correctly populated with statement_fingerprint_ids.

**To Reproduce**

This is the case in the roachprod cluster on 22.1-rc linked in [this slack thread](https://cockroachlabs.slack.com/archives/C0159JK877C/p1652897560746299?thread_ts=1652804809.406559&cid=C0159JK877C) (the cluster might be gone/a different version later). With Redux devtools installed, go to the transactions details page and check `cachedData -> statements -> data -> statements -> the statement at index 5 -> key -> key_data -> transaction_fingerprint_id`, and that should be "0". The slack thread also contains an attachment of the Redux state.

This is not reproducible by checking out `5b78463ed2e7106a8477b63fa837564ad02bb510` (`22.1-rc`), building it, and running the demo database.

**Additional data / screenshots**
Note that as of reporting we currently only have a repro on a customer cluster, so be wary of screenshots.

**Environment:**
 - CockroachDB version: 22.1-rc, roachprod

Jira issue: CRDB-15168

### PR DESCRIPTION
**Pull request by xinhaoz**
# Commit 1
### sql: add txn_fingerprint_id to node_statement_statistics

This commit adds the `txn_fingerprint_id` column to
`crdb_internal.node_statement_statistics`.

Release note (sql): `txn_fingerprin_id` has been added to
`crdb_internal.node_statement_statistics`. The type of the
column is NULL or STRING.

------------------------------
# Commit 2
### sql, sqlstats: create temporary stats container for all txns

Fixes: #81470

Previously, the stats collector followed different procedures for stats
collection depending on whether or not the txn was explicit.

For explicit transactions, all the stmts in the txn must be recorded with
the same `transactionFingerprintID`, which is  only known after all stmts
in the txn have been executed. In order to record the correct
txnFingerprintID, a temporary stats container was created for stmts in the
current transaction. The `transactionFingerprintID` was then populated for
all stmts in the temp container, and the temp container was merged with
the parent.

For implict transactions, the assumption was there would only be a single
stmt in the txn, and so no temporary container was created, with stmts
being written directly to the application stats.

This assumption was incorrect, as it is possible for implicit txns to have
multiple stmts, such as stmts sent in a batch.

This commit ensures that stats are properly collected for implicit txns
with multiple stmts. The stats collector now follows the same procedure
for both explicit and implicit txns, creating a temporary container for
local txn stmts and merging on txn finish.

Release note (bug fix): Statement and transaction stats are now properly
recorded for implicit txns with multiple stmts.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice! the connExecutor changes lgtm. the `sqlstats` package changes also lgtm, but i haven't read that code before

and just to confirm, the second commit can be backported to v22.1, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83616#-:-N5q78-P0gamMhfm9d2i:b-pej9fr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @xinhaoz)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83616#-N5q636s5sDTNBoIOrWq):*
nit: typo in the name

**Review by maryliag — APPROVED** [review]
:lgtm: 
And the goal is indeed backport this to 22.1

> Reviewed 4 of 4 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83616#-:-N5q9bWb28nArVT0bLo2:b-tdjqe9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
One test case in the 2nd commit needs the first commit. To clarify, it's okay to backport both right? Or are we aiming for just the 2nd one with the test case removed?

**Review by matthewtodd — APPROVED** [review]
Nice! Thank you for making this code simpler and easier to understand!

Re: what to backport, are these 2 commits here together because they're related? FWICT, it doesn't seem that they are. Is it to avoid a second (long!) CI cycle? Given the user-visible new column in the first commit, it seems better to me to just backport the second one (modifying the test), but maybe @maryliag can weigh in on whether that hygiene's worth the extra effort.

**Comment by xinhaoz** [comment]
I'll bors and check with Marylia to confirm backports. Thank you for the reviews!
bors r+

**Pull request merged**
