### PR TITLE
sql: produce mock ContentionEvents and display contention time in EXPLAIN ANALYZE

### LINKED ISSUE #56612: rowexec/colexec: add cumulative contention time to EXPLAIN ANALYZE
Actual contention events will be implemented in #55583, but in the meantime we can introduce a testing cluster setting that will produce mock contention events that follow the same structure as that defined by the issue.

This issue also tracks building the SQL execution infrastructure around those contention events. To start with, we'll want to surface how much contention happened in any operators that use disk. This should be a sum of the duration of each contention event.

### PR DESCRIPTION
**Pull request by asubiotto**
Please take a look at individual commits for details

Release note: None

Closes #56612 

@tbg could you take a look at the first commit which defines a `ContentionEvent` protobuf? It's close to what's described in #55583 (minus some fields that can be added later).

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
First commit looks good!

**Review by RaduBerinde — APPROVED** [review]
:lgtm: This is very cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56906#-:-MMXoqna4Yl9JLoDknvZ:bppal8x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/colexec/op_creation.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56906#-MMXnpkW5j1PK4E2Kuds:-MMXnpkW5j1PK4E2Kudt:b-icnb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/68eda8a88e000b01f380de80abb1daa3f4c3a00c/pkg/sql/colexec/op_creation.go#L81)):*
> ```Go
> type NewColOperatorResult struct {
> 	Op              colexecbase.Operator
> 	KVReader        execinfra.KVReader
> ```

Nice change :)
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56906#-MMXnvcU0VHqU8sbnjt9:-MMXnvcU0VHqU8sbnjtA:b-i2ymxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/68eda8a88e000b01f380de80abb1daa3f4c3a00c/pkg/sql/colfetcher/colbatch_scan.go#L135)):*
> ```Go
> // GetCumulativeContentionTime is part of the execinfra.KVReader interface.
> func (s *ColBatchScan) GetCumulativeContentionTime() time.Duration {
> 	var totalContentionTime time.Duration
> ```

I found that sometimes (maybe in error cases, or other early termination situation), s.rf.fetcher might be `nil` here. I'm adding a check in `GetBytesRead` in 56929, we should check here too.
___
*[pkg/sql/execinfrapb/component_stats.proto, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56906#-MMXoVe7B5bB8Cl4j8LI:-MMXoVe7B5bB8Cl4j8LJ:b-8v1sqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/68eda8a88e000b01f380de80abb1daa3f4c3a00c/pkg/sql/execinfrapb/component_stats.proto#L92)):*
> ```protobuf
> 
>   // ContentionTime is the cumulative time a KV request spent contending with
>   // other transactions. This time is a subset of KVTime above.
> ```

[nit] s/is a subset/accounts for a portion of

**Comment by asubiotto** [comment]
TFTRs! The CI failure should be fixed by #56951. Will wait for that to rebase, address comments, and update this PR.

**Comment by asubiotto** [comment]
TFTR

bors r=RaduBerinde,tbg

**Pull request merged**
