### PR TITLE
sql: enable configuration of the default time zone

### LINKED ISSUE #16029: sql: default time zone should be customizable
cockroach version : 1.0
when cockroach started, default time zone is wrong.
my mac's default time zone is UTC+8
cockroach's default time zone is UTC

I170519 06:05:59.177794 1 util/log/clog.go:1011  [config] file created at: 2017/05/19 06:05:59
I170519 06:05:59.177794 1 util/log/clog.go:1011  [config] running on machine: df-macpro-home
I170519 06:05:59.177794 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0 (darwin amd64, built 2017/05/18 21:50:42, go1.8.1)
I170519 06:05:59.177794 1 util/log/clog.go:1011  [config] arguments: [cockroach start --insecure --host=localhost]

### PR DESCRIPTION
**Pull request by knz**
This patch makes it possible to configure the default SQL session
time zone, using a new command-line flag `--sql-time-zone`.

This choice of mechanism is motivated by two factors:

- the configuration should not be dynamic beyond node start-up,
  because clients would react poorly to a change in the default across
  an automatic reconnect; and
- we can't use a cluster setting, because these are not guaranteed
  to propagate early and be available when the defaults are loaded.

Fixes  #16029.

### CODE REVIEW

**Comment by dt** [comment]
hmm, I worry that a per-node flag presents a pretty massive foot-gun: you could easily end up with different values on different nodes, then have query return different results depending on what backend the load balancer picks? I could see that being very confusing and hard to figure out.

Thus, *IF* we need this, I think a cluster setting does actually make sense: yes, if you change it, clients will behave different after reconnect, but forcing a rolling restart of your cluster to set it doesn't change that, it just adds operational overhead. 

As far as not having the correct value on startup: well, you need to connect to gossip to serve traffic anyway, so we _should_ have the value. There's a theoretical race, since we don't actually wait for the first gossip-delivered settings to be applied before serving, but that could be fixed pretty easily in server.go.

**Comment by dt** [comment]
Oh, also, my usual "non-zero session offsets make lots of functions, casts and coercions harder to  reason about and easier to get wrong -- we should actively discourage them, and encourage localizing timestamps in application logic" position applies. Supporting setting a non-zero *default* makes it much easier for an application to end up with an offset it isn't expecting (since it didn't explicitly set it), and then run into that host of gotchas.

**Comment by knz** [comment]
> There's a theoretical race, since we don't actually wait for the first
> gossip-delivered settings to be applied before serving, but that could
> be fixed pretty easily in server.go.

That's what I observed when I tried with a cluster setting first.

Can you explain how to synchronize?

**Comment by dt** [comment]
@knz off the top of my head, I'd probably go for the nonblocking write to a `chan struct{}` in settingsworker.go, the add a read (maybe w/timeout) to the startup path in server (maybe wrapped in a helper). could also go with a waitgroup if you made sure to only call Done the first time, or a cond var? not a perf-sensitive code path, so I would probably take simple over fast.

**Comment by bdarnell** [comment]
I agree with David that this definitely shouldn't be a flag. It should be a cluster setting (assuming we can solve the node startup problem), or remain unconfigurable.

@dt Can you point to specific examples about how non-zero offsets make things error prone? (and then ask some of the users requesting this feature whether they find that argument persuasive) Are these problems more severe in CockroachDB than in other databases? Plenty of people seem to use non-zero offsets in other databases without (too much) trouble.

**Comment by knz** [comment]
Holding onto this until #17032 is solved.

**Comment by dt** [comment]
@bdarnell my concern is mainly what happens when we're parsing received timestamps that don't include explicit offsets -- one team or project changing the cluster-wide default could cause subtle and hard to notice changes in behavior to other apps that don't set a session offset. You're right though that that this isn't new or unique to Cockroach and other DBs offer this, so I guess I'm being overly paranoid. Objection withdrawn, thought I'd still suggest a warning in docs that if you have existing applications in production, you should probably ensure they're setting an explicit session offset before you change the default.

**Comment by bdarnell** [comment]
Yeah, it's going to be extremely rare to change the default time zone after one-time initialization (IIRC Google set all their databases to PST instead of UTC and regretted the choice but were unable to change it, at least for many years). The main use of the database default time zone is probably for ad-hoc sql sessions instead of programmatic use (in a program you'll usually get the raw timestamp and do all time-zone-aware logic in the application), so it's at least a little easier to swallow disruptions there for the rare cases when you do want to change it.

**Pull request closed without merging**
