### PR TITLE
add log in client.Batch

### PR DESCRIPTION
**Pull request by a6802739**
@paperstreet, please look at #8324 and tell me if I done it in a right direction.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9169)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[internal/client/batch.go, line 23 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KR43_WKuzEg_hCfK46u:-KR43_WKuzEg_hCfK46v:b-auojws) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac1033b5595e7a259fd14eb2da2f6abf39a07a18/internal/client/batch.go#L23)):*
> ```Go
> 
> 	"github.com/cockroachdb/cockroach/roachpb"
> 	"github.com/cockroachdb/cockroach/util/log"
> ```

you should set up your editor to use `goimports` to automatically format these (golang.org/... goes above and in a separate group)

---

*[internal/client/batch.go, line 295 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KR433jL9Sp4S6qaGk2V:-KR433jMwOWtvzthIjv2:b-165trr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac1033b5595e7a259fd14eb2da2f6abf39a07a18/internal/client/batch.go#L295)):*
> ```Go
> }
> 
> func (b *Batch) logRequest(arg roachpb.Request) {
> ```

1. We need to be able to pass a proper context.Context. Unfortunately I don't know if we can easily change `appendReqs`. Instead of doing it this way, it may make more sense to simply add conditional logging in `client.Txn.Run` - basically logging the batch when we run it, not when we construct it.

2. We have the ability to turn on the verbosity independently for each source file that issues logs (using --vmodule). We want the verbosity of the caller to apply, not that of `client/batch.go`. We have `log.VDepth` for that, which gets passed how many levels up is the caller that matters.

1. We should just do `if !log.VDepth(..) { return }` instead of replicating that check everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by tamird** [comment]
On Wed, Sep 7, 2016 at 10:43 AM, RaduBerinde <notifications@github.com>
wrote:

> We need to be able to pass a proper context.Context. Unfortunately I don't
> know if we can easily change appendReqs. Instead of doing it this way, it
> may make more sense to simply add conditional logging in client.Txn.Run -
> basically logging the batch when we run it, not when we construct it.
>

However, you're still gonna want the log line to point to the site of
construction rather than execution, I think.

**Comment by RaduBerinde** [comment]
^I don't know if that was important, I would think the contents of the batch really matter, it should be relatively straightforward to figure on what lines it was created, depending on the operation. @paperstreet should know the usecase best though

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-:-KR4rAT7jp5NoSC1FcHR:b-fpc2tq)*

**Comment by paperstreet** [comment]
I haven't found it always straightforward, so I think the log line pointing to where the `Put`, for example, got called is important. @a6802739, you can do this with log.InfofDepth

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[internal/client/batch.go, line 295 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KR433jL9Sp4S6qaGk2V:-KR5-4ipDwb_J1b5Ybfw:b5jjad8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac1033b5595e7a259fd14eb2da2f6abf39a07a18/internal/client/batch.go#L295)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> 1. We need to be able to pass a proper context.Context. Unfortunately I don't know if we can easily change `appendReqs`. Instead of doing it this way, it may make more sense to simply add conditional logging in `client.Txn.Run` - basically logging the batch when we run it, not when we construct it.
> 
> 2. We have the ability to turn on the verbosity independently for each source file that issues logs (using --vmodule). We want the verbosity of the caller to apply, not that of `client/batch.go`. We have `log.VDepth` for that, which gets passed how many levels up is the caller that matters.
> 
> 1. We should just do `if !log.VDepth(..) { return }` instead of replicating that check everywhere.
</details>
Yeah, it's important to get the story of how we handle contexts right in this commit. I haven't thought it through enough to have a solid answer, though. If we want the logging to point at where an operation is added, as I mention above I think we do, I guess our choices are at Batch construction or at each call to `Put` etc. @RaduBerinde any thoughts on which?

Agreed on 2 and 3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-:-KR4zhjUypPm97vVsMCt:b-g8bsmb)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[internal/client/batch.go, line 295 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KR433jL9Sp4S6qaGk2V:-KR51HstgLLyu-1lfTE4:b-kuz1ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac1033b5595e7a259fd14eb2da2f6abf39a07a18/internal/client/batch.go#L295)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Yeah, it's important to get the story of how we handle contexts right in this commit. I haven't thought it through enough to have a solid answer, though. If we want the logging to point at where an operation is added, as I mention above I think we do, I guess our choices are at Batch construction or at each call to `Put` etc. @RaduBerinde any thoughts on which?
> 
> Agreed on 2 and 3
> 
> 
</details>
To pass a context correctly, we either need to pass contexts to batch functions (which sounds like a big change), or your original idea of using a batch interface and another implementation that embeds a Batch and adds logging around each call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by paperstreet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[internal/client/batch.go, line 295 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KR433jL9Sp4S6qaGk2V:-KR52SxtUJ0pwcBhOhkc:b864gro) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac1033b5595e7a259fd14eb2da2f6abf39a07a18/internal/client/batch.go#L295)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> To pass a context correctly, we either need to pass contexts to batch functions (which sounds like a big change), or your original idea of using a batch interface and another implementation that embeds a Batch and adds logging around each call.
</details>
Or `NewBatch`? There's 108 calls to it (54 not in tests), which is a lot but not crazy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[internal/client/batch.go, line 295 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KR433jL9Sp4S6qaGk2V:-KR53LxCFQE9VGuE17X9:b-dew703) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac1033b5595e7a259fd14eb2da2f6abf39a07a18/internal/client/batch.go#L295)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Or `NewBatch`? There's 108 calls to it (54 not in tests), which is a lot but not crazy
</details>
Ah, yeah, we could store the context in the batch. We could leave `NewBatch`as is  and add a `NewBatchWithCtx` and use that in the handful of cases we actually care about the context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by paperstreet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[internal/client/batch.go, line 295 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KR433jL9Sp4S6qaGk2V:-KR53lKyS0QLqddUrpIr:bfocpjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac1033b5595e7a259fd14eb2da2f6abf39a07a18/internal/client/batch.go#L295)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah, yeah, we could store the context in the batch. We could leave `NewBatch`as is  and add a `NewBatchWithCtx` and use that in the handful of cases we actually care about the context.
</details>
Oh yeah, I like that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[internal/client/batch.go, line 295 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KR433jL9Sp4S6qaGk2V:-KR53jUqMHrUJxUwCb0Z:b-erooe4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac1033b5595e7a259fd14eb2da2f6abf39a07a18/internal/client/batch.go#L295)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Oh yeah, I like that
</details>
Ah, it's even easier.. `Txn.NewBatch` already has access to `txn.Context`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by a6802739** [comment]
@RaduBerinde, @paperstreet , I have pass `context` from `txn` to `Batch`.

**Comment by RaduBerinde** [comment]
Great, the context stuff LGTM, thanks!

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[internal/client/batch.go, line 301 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KR8qgFI3zG--ol4D8h3:-KR8qgFI3zG--ol4D8h4:b-8un649) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38ef9e0c1bf6629e65735aae0f19495047d65ab/internal/client/batch.go#L301)):*
> ```Go
> 	case *roachpb.GetRequest:
> 		if log.V(2) {
> 			log.InfofDepth(b.Context, 1, "Get %s", req.Key)
> ```

depth of 1 means the reported line would be the caller (appendReqs). We want the caller of the caller of appendReq (e.g. `sql code -> Get -> appendReq`), but in some instances we want the caller of that (sql code -> Put -> put -> appendReq). I think we need to pass the depth to `appendReq`.

Also the level of the verbosity check should match, use `log.VDepth(<level>, 2)`. And we should check that first and return, to avoid duplicating that check everywhere and doing the type switch if there's no need.

You should be able to test this by running
`make test PKG=./sql TESTS=Logic TESTFLAGS='-v --vmodule=rowwriter=2'`

You should see logs that are similar to [those in rowwriter](https://github.com/cockroachdb/cockroach/blob/develop/sql/rowwriter.go#L195). Those should be removed once this works BTW.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-:-KR8rblcPlS3aHsF3CW9:b-lpytq0)*

**Comment by a6802739** [comment]
@RaduBerinde , thanks for your advice. However, how should I pass the parameter `level` to `logRequest`?

**Comment by RaduBerinde** [comment]
Yeah, to `logRequest` and `appendReq`s. No, the number in the `vmodule` flag is the verbosity. `level` identifies the caller (file:line) we display. I suggest playing with a few `log.InfoDepth` statements in a test somewhere and trying different levels to see the difference.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-:-KR9L4BQRwrOX4hbrLz5:b-kets56)*

**Comment by a6802739** [comment]
@RaduBerinde , If I pass `depth` from `appendReqs` to `logRequest `, I have to add parameter `depth` in function `AddRawRequest`, there are a lot of place use this function.

**Comment by RaduBerinde** [comment]
We wouldn't add a `level` argument to the methods in the interface of batch (the exported ones, including `AddRawRequest`). These methods would pass a level of 1 to identify their caller.

The usual convention with level is that if function `X` calls function Y(level), it wants whatever `Y` ends up logging to reflect the caller that is `level` above `X`. So `level=1` means X's caller, `level=2` means X's caller's caller. A good example is the [logging code itself](https://github.com/cockroachdb/cockroach/blob/0cee5fa91868456d1e45a8b817b27d6033f0a4ba/util/log/log.go#L107).

Ok, so in our case, `appendReqs` would take a `level`. It would call `logRequest(level+1)`, and `logRequest` would in turn calll `VDepth` and `InfofDepth` with `level+1` (which is 2 more than the level that was passed to `appendReqs`).

AddRawRequest would call appendReqs with level=1, meaning it wants whoever called `AddRawRequest` to show up in  the log. All "top-level" functions that call `appendReqs` directly would do the same. Functions like `put` would call `appendReqs` with level=2, so that we show the caller's caller, i.e. the caller of `Put/Putinline`.

Hope this helps. Thanks!

**Comment by a6802739** [comment]
@RaduBerinde, yes, it's quite clear now. thanks a lot!
I know how to set `depth` in ` log.InfofDepth(b.Context, depth, "Get %s", req.Key)`.
However,  I can't understand the parameter `level` in `log.VDepth(<level>, 2)`, is it same to `depth`?

**Comment by RaduBerinde** [comment]
Yes, exactly the same.

**Comment by a6802739** [comment]
@RaduBerinde, got it. But from the defination 
```
// VDepth reports whether verbosity at the call site is at least the requested
// level.
func VDepth(level level, depth int) bool {
	// This function tries hard to be cheap unless there's work to do.
	// The fast path is two atomic loads and compares.

	// Here is a cheap but safe test to see if V logging is enabled globally.
	if logging.verbosity.get() >= level {
		return true
	}
```

I think it should be `log.Depth(2, depth)`, right?

**Comment by RaduBerinde** [comment]
Yes, that's right. Sorry for confusing you, I used `level` above when I had `depth` in my mind, my bad. Yeah the level is the "verbosity level". Using `--verbosity X` means all logs with level at most X will show up, and using `--vmodule=file=X` means all logs with level at most X originating in the given file will show up (and `depth` controls what "originating" means, in terms of stack depth).

Yes, we should remove the ctx parameter. In fact we can now remove the functions altogether and define them inline, eg

```
var putFn func(b *Batch, k *Key, v *Value)
if ignoreConflicts {
  putFn = func(b *Batch, k *Key, v *Value) { b. Put(..) }
} else {
  putFn = func(b *Batch, k *Key, v *Value) { b. CPut(..) }
}
```

**Comment by tamird** [comment]
Friendly reminder to squash all commits before merging. Thanks for taking this on!

---

Reviewed 3 of 3 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[internal/client/batch.go, line 43 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFDhGcyf34WMzg-F-t:-KRFDhGcyf34WMzg-F-u:b-964bkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae80b17456fd79e5dcadf54dc3d59237bf1d4fa6/internal/client/batch.go#L43)):*
> ```Go
> 	// was not created via Txn.NewBatch.
> 	txn     *Txn
> 	Context context.Context //must not be nil
> ```

I don't think this needs to be exported, and the "must not be nil" comment isn't helpful since it is never legal for `context.Context` to be nil.

`ctx context.Context` should be fine here.

---

*[internal/client/batch.go, line 333 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFECeTAsfNA_CkGOER:-KRFECeU92HUJo7-A6mx:b-i18bn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae80b17456fd79e5dcadf54dc3d59237bf1d4fa6/internal/client/batch.go#L333)):*
> ```Go
> 		log.InfofDepth(b.Context, level, "HeartbeatTxn %s at %v", req.Key, req.Now)
> 	case *roachpb.GCRequest:
> 		log.InfofDepth(b.Context, level, "GC from %s to ", req.Key, req.EndKey)
> ```

missing %s on the end here

---

*[internal/client/batch.go, line 352 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFDtbnim2elCDibO4_:-KRFDtboGhc0meWvZH4w:b-59li6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae80b17456fd79e5dcadf54dc3d59237bf1d4fa6/internal/client/batch.go#L352)):*
> ```Go
> 	case *roachpb.ChangeFrozenRequest:
> 		log.InfofDepth(b.Context, level, "ChangeFrozen from %s to %s", req.Key, req.EndKey)
> 	default:
> ```

can you log something here? perhaps:

`log.InfofDepth(b.ctx, level, "%T <unknown>", req)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-:-KRFEtDer-ZBMGYnaA24:b-mucfqn)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by a6802739** [comment]
@RaduBerinde, @tamird , I will change it right now.

**Comment by RaduBerinde** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[internal/client/batch.go, line 297 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFKIYx36jnajsFSFYL:-KRFKIYx36jnajsFSFYM:b-6l7izz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7291ff5d91ede9532e74db310b7aec016b59abc2/internal/client/batch.go#L297)):*
> ```Go
> }
> 
> func (b *Batch) logRequest(arg roachpb.Request, level int) {
> ```

Let's call this `depth`, sorry, I know it's because of me :)

---

*[internal/client/batch.go, line 357 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFKTvEq5otrloPeDgN:-KRFKTvEq5otrloPeDgO:b-7rrciq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7291ff5d91ede9532e74db310b7aec016b59abc2/internal/client/batch.go#L357)):*
> ```Go
> }
> 
> func (b *Batch) appendReqs(level int, args ...roachpb.Request) {
> ```

depth

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[internal/client/batch.go, line 43 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFDhGcyf34WMzg-F-t:-KRFL32NKXfN4Xer2QOH:bv4bsmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae80b17456fd79e5dcadf54dc3d59237bf1d4fa6/internal/client/batch.go#L43)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I don't think this needs to be exported, and the "must not be nil" comment isn't helpful since it is never legal for `context.Context` to be nil.
> 
> `ctx context.Context` should be fine here.
</details>
Agreed it should be `ctx`

On the `nil` part - I don't think this is true right now. There are many places where `Batch`es are constructed, especially in tests. We are definitely not setting the context in all cases. We can either fix that (which may be a daunting task), or we could allow `nil` contexts and handle it when logging (either skipping the logging altogether in that case, or using `context.Background()`).
If we go with the latter, we should rename it to something more specific, like `logCtx`

Make sure to run `make test TESTFLAGS=''--verbosity 2"` to verify there are no crashes when verbosity is up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/rowwriter.go, line 197 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFMDIx0D7kKcnpQLLT:-KRFM0nX5f_M7TsXfwyw:br6mjfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e979083cfd9a7af0009fb5dcbd5e23411c7a42/sql/rowwriter.go#L197)):*
> ```Go
> 	}
> 
> 	var putFn func(b *client.Batch, key *roachpb.Key, value *roachpb.Value)
> ```

we need to keep the old code here (and actually, we need something slightly more clever). Essentially, we need to increase the depth by 1 when going through a construct like this (we want to see the caller to `putFn`, not  `b.Put` and `b.CPut` below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/rowwriter.go, line 197 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFMDIx0D7kKcnpQLLT:-KRFO4RNo1ppKxl1y76Y:b-twaunv) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e979083cfd9a7af0009fb5dcbd5e23411c7a42/sql/rowwriter.go#L197)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> we need to keep the old code here (and actually, we need something slightly more clever). Essentially, we need to increase the depth by 1 when going through a construct like this (we want to see the caller to `putFn`, not  `b.Put` and `b.CPut` below.
</details>
Unfortunately, I think that means we need to introduce a family of `Depth` functions on `Batch` instead of the current approach.

So for instance the current `(*Batch).Put` becomes `(*Batch).PutDepth` and a new function `(*Batch).Put(...)` would call `(*Batch).PutDepth(..., 1)`

@raduberinde WDYT?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[sql/rowwriter.go, line 197 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFMDIx0D7kKcnpQLLT:-KRFNE5uwpSjjnzGCKSQ:bd9jjqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e979083cfd9a7af0009fb5dcbd5e23411c7a42/sql/rowwriter.go#L197)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Unfortunately, I think that means we need to introduce a family of `Depth` functions on `Batch` instead of the current approach.
> 
> So for instance the current `(*Batch).Put` becomes `(*Batch).PutDepth` and a new function `(*Batch).Put(...)` would call `(*Batch).PutDepth(..., 1)`
> 
> @raduberinde WDYT?
</details>
I see two other options:
 - just do `if ignoreConflicts` in the three places where we're actually using this. I have a feeling that might have been the original code anyway if we didn't also have the logging code (@paperstreet - what do you think?)
 - add a ``Batch.PutIfNil` (or `CPutIfNil?`) method which is equivalent to `CPut(k, v, nil)`. Then we can do:
```
var putFn func(*Batch, *Key, *Value)
if ignoreConflicts {
  putFn = (*Batch).Put
} else {
  putFn = (*Batch).PutIfNil
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by paperstreet** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[sql/rowwriter.go, line 197 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFMDIx0D7kKcnpQLLT:-KRFUHlAQ2DZuYaRnC6h:bebpos0) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e979083cfd9a7af0009fb5dcbd5e23411c7a42/sql/rowwriter.go#L197)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I see two other options:
>  - just do `if ignoreConflicts` in the three places where we're actually using this. I have a feeling that might have been the original code anyway if we didn't also have the logging code (@paperstreet - what do you think?)
>  - add a ``Batch.PutIfNil` (or `CPutIfNil?`) method which is equivalent to `CPut(k, v, nil)`. Then we can do:
> ```
> var putFn func(*Batch, *Key, *Value)
> if ignoreConflicts {
>   putFn = (*Batch).Put
> } else {
>   putFn = (*Batch).PutIfNil
> }
> ```
</details>
I vote we just switch the 3 callsites back to ifs and remove the putFn var

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[sql/rowwriter.go, line 197 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFMDIx0D7kKcnpQLLT:-KRFVgKULnwlIYi-YR6d:b-9yh3l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e979083cfd9a7af0009fb5dcbd5e23411c7a42/sql/rowwriter.go#L197)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I vote we just switch the 3 callsites back to ifs and remove the putFn var
</details>
Another benefit of the `*Depth` functions is that they're more type-safe. They avoid the "unknown" case in that giant `switch` we have now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[sql/rowwriter.go, line 197 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFMDIx0D7kKcnpQLLT:-KRFWBvSzDqm9DWc3ZdZ:bh6ujx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e979083cfd9a7af0009fb5dcbd5e23411c7a42/sql/rowwriter.go#L197)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Another benefit of the `*Depth` functions is that they're more type-safe. They avoid the "unknown" case in that giant `switch` we have now.
</details>
Huh? Whether we do logging in a single switch (inside `appendReqs`) or pepper each top-level method with logs is perpendicular to whether we export `*Depth` variants or not

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[sql/rowwriter.go, line 197 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFMDIx0D7kKcnpQLLT:-KRFWtRNRb8nEHJtJYqc:bat38re) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e979083cfd9a7af0009fb5dcbd5e23411c7a42/sql/rowwriter.go#L197)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Huh? Whether we do logging in a single switch (inside `appendReqs`) or pepper each top-level method with logs is perpendicular to whether we export `*Depth` variants or not
</details>
You're right, of course.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[internal/client/batch.go, line 43 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFDhGcyf34WMzg-F-t:-KRJPLs2y8elDbWWl1-p:b-7jn3ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae80b17456fd79e5dcadf54dc3d59237bf1d4fa6/internal/client/batch.go#L43)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Agreed it should be `ctx`
> 
> On the `nil` part - I don't think this is true right now. There are many places where `Batch`es are constructed, especially in tests. We are definitely not setting the context in all cases. We can either fix that (which may be a daunting task), or we could allow `nil` contexts and handle it when logging (either skipping the logging altogether in that case, or using `context.Background()`).
> If we go with the latter, we should rename it to something more specific, like `logCtx`
> 
> Make sure to run `make test TESTFLAGS=''--verbosity 2"` to verify there are no crashes when verbosity is up.
</details>
We could export a new API `(*Batch).EnableLogging(ctx)`. Whatever caller is interested in verbose logging calls this, and this sets the internal `logCtx`. We can remove the `VDepth` checks and replace them with `if logCtx != nil`; the caller can do `if V(2) { batch.EnableLogging(ctx)`. This may be closer to the original intent and it's nice to give each layer more control - I don't know if we actually want all the batches everywhere to be logged when we run with `--verbosity 2`.

I think this leads to a pretty clean interface without having to make sure we always have a ctx set in the batch. And I like that it's clear the context is only set and used for logging; if it's a general context that is always set, that leads to the legitimate question: which ctx is used when a Batch is sent - the one in the Batch or the one in Txn?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by RaduBerinde** [comment]
Reviewed 1 of 3 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[internal/client/batch.go, line 43 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169#-KRFDhGcyf34WMzg-F-t:-KRJbNdC6csld2MFdHmA:b5z43n8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae80b17456fd79e5dcadf54dc3d59237bf1d4fa6/internal/client/batch.go#L43)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We could export a new API `(*Batch).EnableLogging(ctx)`. Whatever caller is interested in verbose logging calls this, and this sets the internal `logCtx`. We can remove the `VDepth` checks and replace them with `if logCtx != nil`; the caller can do `if V(2) { batch.EnableLogging(ctx)`. This may be closer to the original intent and it's nice to give each layer more control - I don't know if we actually want all the batches everywhere to be logged when we run with `--verbosity 2`.
> 
> I think this leads to a pretty clean interface without having to make sure we always have a ctx set in the batch. And I like that it's clear the context is only set and used for logging; if it's a general context that is always set, that leads to the legitimate question: which ctx is used when a Batch is sent - the one in the Batch or the one in Txn?
</details>
Ah, sorry, the API I proposed doesn't work if we want to log direct calls to `(*Txn).Get/Put` etc. Never mind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9169)*

**Comment by a6802739** [comment]
@RaduBerinde ,@tamird , @paperstreet  I'm a little confusing now. So I write a function `PutDepth`.

If it's ok , I will add other functions is a same way.

**Comment by tamird** [comment]
@a6802739 looks good to me, but if we're going to add `fooDepth` methods, we should get rid of `logRequest` and just log directly in the `fooDepth` methods.

**Pull request closed without merging**
