### PR TITLE
opt: normalize self-comparisons to IS [NOT] NULL

### PR DESCRIPTION
**Pull request by justinj**
I was perusing the Postgres 11 changelog and saw this rule that looked
nice and simple and like an easy win. Turned into a bit of a yak shave
but I think there are probably situations in which it's valuable as I've
seen this idiom for null checking before.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Hm, but `NULL == NULL` is `NULL`, whereas `NULL IS NOT NULL` is `FALSE`.

```
radu=> select x = x from (values (1), (null)) as t(x);
 ?column? 
----------
 t
 
(2 rows)
```

I found the release note, it says "Optimize var = var to var IS NOT NULL *where equivalent*". Maybe we want to only do this for things that are under `Filters`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28663#-:-LJzLBBR5tGHOt4MxyST:bg6b3fa)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
BTW I found the PG commit, it sounds like it's only in WHERE clauses https://github.com/postgres/postgres/commit/8ec5429e2f422f4d570d4909507db0d4ca83bbac

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28663#-:-LJzNm3g1cIfs9ZFmvod:bga99d1)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28663)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 991 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28663#-LJzOAAOCJlcUf9NmDDX:-LJzOAAOCJlcUf9NmDDY:b-5bj4fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c03edcb0f43e2fdb981e78c000e22ac08a63a5e/pkg/sql/opt/norm/custom_funcs.go#L991)):*
> ```Go
> 		return c.f.ConstructIsNot(group, nullVal)
> 	case opt.NeOp, opt.LtOp, opt.GtOp:
> 		return c.f.ConstructIs(group, nullVal)
> ```

I don't think this is right (even for filters). `i <> i` is never true, it's either FALSE or NULL

**Comment by justinj** [comment]
Ah, you're right. Given proximity to code freeze just gonna close this for now.

**Pull request closed without merging**
