### PR TITLE
build: try to propagate exit codes from failing checks

### PR DESCRIPTION
**Pull request by tamird**
Currently, we only return 0 or 1.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8493)

### CODE REVIEW

**Comment by jordanlewis** [comment]
LGTM

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/check-style.sh, line 182 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493#-KOvxNUWR6UPexwcG88o:-KOvxNUWR6UPexwcG88p:b2s7h2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e13fc1fc50c247debbdfecd0d5bc52478c21db2/build/check-style.sh#L182)):*
> ```Shell
>   for i in $tests; do
>     set +e
>     runcheck $i
> ```

could just do `runcheck "$i" || exit_status=$?`   (wouldn't even need the `set +/-e` stuff)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493#-:-KOvyp1f7871ht0pKSal:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/check-style.sh, line 182 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493#-KOvxNUWR6UPexwcG88o:-KOxbarz8tiNv7B67zsD:b-jnvz6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e13fc1fc50c247debbdfecd0d5bc52478c21db2/build/check-style.sh#L182)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> could just do `runcheck "$i" || exit_status=$?`   (wouldn't even need the `set +/-e` stuff)
</details>
Awesome, TIL. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/check-style.sh, line 182 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493#-KOvxNUWR6UPexwcG88o:-KOyvW8V5OATUEVlbZjs:bwzmu3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e13fc1fc50c247debbdfecd0d5bc52478c21db2/build/check-style.sh#L182)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Awesome, TIL. Done.
</details>
We may be setting `exit_status` to an empty `check_status`. We can set `exit_status` directly if it's ok to return the last non-zero result instead of the first, or initialize `check_status=0` before runcheck.

Can you make sure to test the script with a failure and without parallel?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/check-style.sh, line 182 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493#-KOvxNUWR6UPexwcG88o:-KOyzRzngK6lBuQZM1dP:b-pz0hsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e13fc1fc50c247debbdfecd0d5bc52478c21db2/build/check-style.sh#L182)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We may be setting `exit_status` to an empty `check_status`. We can set `exit_status` directly if it's ok to return the last non-zero result instead of the first, or initialize `check_status=0` before runcheck.
> 
> Can you make sure to test the script with a failure and without parallel?
</details>
Actually this problem would show up when there are no failures

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/check-style.sh, line 182 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493#-KOvxNUWR6UPexwcG88o:-KOyzalzqBnrX89Xia7o:b-hixesd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e13fc1fc50c247debbdfecd0d5bc52478c21db2/build/check-style.sh#L182)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Actually this problem would show up when there are no failures
</details>
Ah, you're right. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/check-style.sh, line 175 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493#-KOz1s_BibG1wjwxtaal:-KOz1s_CdQ_PbnnJQFTi:b-4vu7ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/c353e0cc07125c56452cc084f36304e099fa114a/build/check-style.sh#L175)):*
> ```Shell
>   parallel runcheck {} ::: $tests || exit_status=$?
> else
>   check_status=0
> ```

I would move it inside the `for`. I know it still works but it's easier to read the code if `check_status` is simply the result of the current check (it's currently the last non-zero result..)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493#-:-KOz1hOkTXauhA3N5hXT:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/check-style.sh, line 175 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493#-KOz1s_BibG1wjwxtaal:-KOz4teaBHLpJybvrEGi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c353e0cc07125c56452cc084f36304e099fa114a/build/check-style.sh#L175)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I would move it inside the `for`. I know it still works but it's easier to read the code if `check_status` is simply the result of the current check (it's currently the last non-zero result..)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8493)*

**Pull request merged**
