### PR TITLE
storage: Record the reasons behind allocator actions in the range log

### LINKED ISSUE #9025: storage: More visibility into rebalance decisions
The test clusters are performing rebalance operations almost once a second in the steady state. This seems way too high, but it's difficult to see why the rebalancer is doing what it's doing. There's some V(2) logging, but it's inconvenient to use. There should be a more visible way to see what the rebalancer is doing. An EventLog is the simplest solution, although dedicated support in the UI will probably be a good idea at some point.

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #9025

This makes for range log info fields that can be somewhat lengthy, so
let me know if you'd prefer a different approach. Here are some
examples:

```
{"UpdatedDesc":{"range_id":12,"start_key":"mQ==","end_key":"mg==","replicas":[{"node_id":1,"store_id":1,"replica_id":1},{"node_id":4,"store_id":4,"replica_id":2},{"node_id":2,"store_id":2,"replica_id":3}],"next_replica_id":4},"NewDesc":null,"AddReplica":{"node_id":2,"store_id":2,"replica_id":3},"RemovedReplica":null,"Reason":"range under-replicated","Details":"{\"Target\":\"s2, valid:true, constraint:0.00, converges:0, balance:0.00(ranges=0, bytes=0.00, writes=0.00), rangeCount:8, logicalBytes:207 KiB, writesPerSecond:0.00, details:(diversity=0.00, preferred=0)\",\"RangeBytes\":0,\"RangeWritesPerSecond\":38.35988883691482}"}
{"UpdatedDesc":{"range_id":5,"start_key":"iA==","end_key":"kw==","replicas":[{"node_id":1,"store_id":1,"replica_id":1},{"node_id":2,"store_id":2,"replica_id":2},{"node_id":4,"store_id":4,"replica_id":3},{"node_id":3,"store_id":3,"replica_id":4}],"next_replica_id":5},"NewDesc":null,"AddReplica":{"node_id":3,"store_id":3,"replica_id":4},"RemovedReplica":null,"Reason":"rebalance","Details":"{\"Target\":\"s3, valid:true, constraint:0.00, converges:1, balance:1.50(ranges=0, bytes=0.50, writes=1.00), rangeCount:10, logicalBytes:304 KiB, writesPerSecond:5.34, details:(diversity=0.00, preferred=0)\",\"Existing\":\"[\\ns2, valid:true, constraint:0.00, converges:1, balance:1.00(ranges=0, bytes=0.00, writes=1.00), rangeCount:14, logicalBytes:449 KiB, writesPerSecond:15.54, details:(diversity=0.00, preferred=0)\\ns1, valid:true, constraint:0.00, converges:0, balance:0.50(ranges=0, bytes=0.00, writes=0.50), rangeCount:17, logicalBytes:418 KiB, writesPerSecond:41.27, details:(diversity=0.00, preferred=0)\\ns4, valid:true, constraint:0.00, converges:0, balance:-1.00(ranges=0, bytes=0.00, writes=-1.00), rangeCount:13, logicalBytes:465 KiB, writesPerSecond:327.66, details:(diversity=0.00, preferred=0)]\",\"RangeBytes\":7565,\"RangeWritesPerSecond\":3.9615655603960067}"}
{"UpdatedDesc":{"range_id":5,"start_key":"iA==","end_key":"kw==","replicas":[{"node_id":1,"store_id":1,"replica_id":1},{"node_id":2,"store_id":2,"replica_id":2},{"node_id":3,"store_id":3,"replica_id":4}],"next_replica_id":5},"NewDesc":null,"AddReplica":null,"RemovedReplica":{"node_id":4,"store_id":4,"replica_id":3},"Reason":"range over-replicated","Details":"{\"Target\":\"s4, valid:true, constraint:0.00, converges:0, balance:-1.00(ranges=0, bytes=0.00, writes=-1.00), rangeCount:13, logicalBytes:465 KiB, writesPerSecond:327.66, details:(diversity=0.00, preferred=0)\",\"RangeBytes\":7565,\"RangeWritesPerSecond\":4.014823776984506}"}
```

The rangelog portion of the range debug page now looks like:

screen shot 2017-08-18 at 5 29 14 pm

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/allocator.go, line 338 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17755#-KrwIese05YwlsU0CZLt:-KrwIese05YwlsU0CZLu:b-7a8a2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ad36a82760cdd85ac06a95f52a96fbb9b3937e3/pkg/storage/allocator.go#L338)):*
> ```Go
> 		}
> 		details, err := json.Marshal(struct {
> 			Target               string
> ```

This struct should probably be defined as a named type since it's used several times. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17755#-:-KrwM9I_fCImA6ks5Km3:bnfp4nl)*

**Comment by petermattis** [comment]
I only skimmed the change, but capturing this additional detail :lgtm:. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17755#-:-Krx6jI8kjwxeftn5yLo:bbv3a7)*

**Comment by BramGruneir** [comment]
Nice work.  This will be very helpful.

1) Will this work when viewing the range log using an older version of cockroach.  As in, 1.1 is running on most servers, but the admin ui is still 1.0.  Will the range page still display?  I think it will, but we should probably check.  (And vice versa too!)

2) This is adding more to the json (err... string) column in the table.  Perhaps we should add a work item to normalize this table.  And add indexes too.

---

Reviewed 21 of 22 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/log.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17755#-Ks46vzOl40nxsrTusDA:-Ks46vzOl40nxsrTusDB:b-hl5qwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ad36a82760cdd85ac06a95f52a96fbb9b3937e3/pkg/storage/log.go#L35)):*
> ```Go
> 
> // The set of possible reasons for range events to happen.
> const (
> ```

Would it makes sense to turn this into a proto enum?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17755#-:-Ks480jHGz0WlcKake5X:b-drt5ct)*

**Comment by a-robinson** [comment]
1. It'll work when viewing the range log via SQL, but not in the UI (since it won't be getting returned in the `RangeResponse_RangeLog_PrettyInfo` struct. That's ok though, it's just debug info after all.
2. Sure, I've opened #17780.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator.go, line 338 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17755#-KrwIese05YwlsU0CZLt:-Ks4GGnT21moQ8C98PDE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ad36a82760cdd85ac06a95f52a96fbb9b3937e3/pkg/storage/allocator.go#L338)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This struct should probably be defined as a named type since it's used several times. 
</blockquote></details>

Done.

---

*[pkg/storage/log.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17755#-Ks46vzOl40nxsrTusDA:-Ks4DYcFnkKnhKucKAnc:bwqt5ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ad36a82760cdd85ac06a95f52a96fbb9b3937e3/pkg/storage/log.go#L35)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Would it makes sense to turn this into a proto enum?
</blockquote></details>

I did that originally because it does seem like it'd be nicer, but then the fields only print as numbers in the output JSON, which makes them significantly more annoying to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17755#-:-Ks4GNMSF5wWn-rgNfnE:bx5kke0)*

**Comment by BramGruneir** [comment]
LGTM

---

Reviewed 1 of 22 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17755#-:-Ks4QKnWURs7upqY1OMX:bb6ywmx)*

**Pull request merged**
