### PR TITLE
sql: unify pgwire/datum timestamp parsing code

### LINKED ISSUE #16044: Play Framework Slick Evolutions Apparently Not Working with CRDB
**BUG REPORT**
Trying to use Play Framework's Slick integration with evolutions against cockroach. Works when connection string is switched to point to postgres. Appears to actually cause play to crash.

I setup a sample project that demonstrates the problem.

1. Clone https://github.com/patwhite/play-scala-cockroach
2. With Scala and SBT installed, in the root of the project run: sbt run
3. Try clicking the "Apply this script now" button

It crashes, but appears to just drop you on the same page. There will be a table created "play_evolutions", but the users table will not be created, and as near as I can tell no relevant logs obviously show up in crdb's logs or play's.

Logs:
CockroachDB node starting at 2017-05-20 16:27:45.854528319 +0000 UTC
build:      CCL v1.0 @ 2017/05/10 13:19:57 (go1.8.1)
admin:      http://roach1:8080
sql:        postgresql://root@roach1:26257?sslmode=disable
logs:       /cockroach/cockroach-data/logs
store[0]:   path=/cockroach/cockroach-data
status:     initialized new cluster
clusterID:  cd6a74ab-576f-476d-9c30-dc4c4154a5fa
nodeID:     1

### LINKED ISSUE #16047: sql/pgwire: parsing of text format datums during BIND differs from normal datum parsing
The parsing code for text-format inputs in `pgwire/types.decodeOidDatum` is not identical to the ordinary constant parsing code in `constant.go`'s `ResolveAsType` methods. This results in inconsistent behavior when executing prepared statements via pgwire, which is the only codepath that uses `decodeOidDatum`.

For instance, #16044 was caused by `parseTs` (via `decodeOidDatum`) failing to parse the string `2017-05-20 22:32:03.006000 -04:00:00` as a timestamp. However, that string is perfectly parseable by `ParseDTimestamp`, the method that's used to parse timestamps in every other context.

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, pgwire had a separate timestamp parsing routine from the one
used by normal datum parsing. This produced inconsistencies where some
timestamps could be parsed in normal SQL execution but not pgwire
prepared statement execution.

Now, pgwire delegates to `ParseDTimestamp` and `ParseDTimestampTZ`
instead of its own parser.

Also, minor fix to `DatumTypeToColumnType`, which was missing handling
for oid wrapped types.

Fixes #16044.
Fixes #16047.

### CODE REVIEW

**Comment by mjibson** [comment]
I'm unconvinced about the change to nanoseconds. Is that for a specific reason?

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/update.go, line 196 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-Kkltd9_EIZIfq8aedU7:-Kkltd9_EIZIfq8aedU8:bzghylx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3968fa7838448695714e1a426f21f9e36ec142e/pkg/sql/update.go#L196)):*
> ```Go
> 
> // addOrMergeExpr inserts an Expr into a renderNode, attempting to reuse
> // previous renders if possible by using render.addOrReuseRender, returning the
> ```

Should this be included in this PR?

---

*[pkg/sql/parser/col_types.go, line 517 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KkltfO08eLXRi_UI9oN:-KkltfO08eLXRi_UI9oO:b-9mo62g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3968fa7838448695714e1a426f21f9e36ec142e/pkg/sql/parser/col_types.go#L517)):*
> ```Go
> 			return arrayOf(elemTyp, Exprs(nil))
> 		}
> 		if w, ok := t.(tOidWrapper); ok {
> ```

Should this be included in this PR? If it's a self-contained commit, seems like we should add a test? But mostly I think it should be in another PR.

---

*[pkg/sql/pgwire/types.go, line 408 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KklvLEe6pwbINU28d3k:-KklvLEe6pwbINU28d3l:b-5bwn5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e68800f6b47c22e142b48fdb390a0e5d249a8cf/pkg/sql/pgwire/types.go#L408)):*
> ```Go
> 	// CockroachDB send in responses, so this allows roundtripping of the encoded
> 	// timestamps that we send.
> 	return pq.ParseTimestamp(nil, str)
> ```

Does the addition of timestampPgwireFormat fully cover the removal of this function?

---

*[pkg/sql/pgwire/types.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KkluZOSMl9ab7hNOcRW:-KkluZOSMl9ab7hNOcRX:bpl0hpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3968fa7838448695714e1a426f21f9e36ec142e/pkg/sql/pgwire/types.go#L477)):*
> ```Go
> 			return nil, errors.Errorf("unsupported bytea encoding: %q", b)
> 		case oid.T_timestamp:
> 			d, err := parser.ParseDTimestamp(string(b), time.Nanosecond)
> ```

Why did this and the one below switch to nanoseconds?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-:-Kklvjc2m3690ONQ7mAB:boqlcee)*

**Comment by jordanlewis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/pgwire/types.go, line 408 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KklvLEe6pwbINU28d3k:-KlPtZcNVkO_9nZHF1hB:b-ce4d88) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e68800f6b47c22e142b48fdb390a0e5d249a8cf/pkg/sql/pgwire/types.go#L408)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Does the addition of timestampPgwireFormat fully cover the removal of this function?
</blockquote></details>

Yes, and I added tests for that in datum_test.go.

---

*[pkg/sql/pgwire/types.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KkluZOSMl9ab7hNOcRW:-KlPtUMXFZbaAendif4y:bp8k9ek) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3968fa7838448695714e1a426f21f9e36ec142e/pkg/sql/pgwire/types.go#L477)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why did this and the one below switch to nanoseconds?
</blockquote></details>

Because the pgwire format has enough digits for nanonsecond precision.

---

*[pkg/sql/update.go, line 196 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-Kkltd9_EIZIfq8aedU7:-KlPtX_6FCvXW-s6YhgM:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3968fa7838448695714e1a426f21f9e36ec142e/pkg/sql/update.go#L196)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Should this be included in this PR?
</blockquote></details>

Removed.

---

*[pkg/sql/parser/col_types.go, line 517 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KkltfO08eLXRi_UI9oN:-KlPtYLpzuAZ5NhxKwtz:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3968fa7838448695714e1a426f21f9e36ec142e/pkg/sql/parser/col_types.go#L517)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Should this be included in this PR? If it's a self-contained commit, seems like we should add a test? But mostly I think it should be in another PR.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049)*

**Comment by tamird** [comment]
Reviewed 2 of 7 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/datum_test.go, line 397 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KlQ1Q8GgxrE7zMrx7Qh:-KlQ1Q8GgxrE7zMrx7Qi:b2ew1w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/826f3fc311d458b0d875b2df6cc1a507b211a090/pkg/sql/parser/datum_test.go#L397)):*
> ```Go
> 		actual, err := ParseDTimestampTZ(td.str, time.UTC, time.Nanosecond)
> 		if err != nil {
> 			t.Errorf("unexpected error while parsing TIMESTAMPTZ %s: %s", td.str, err)
> ```

sub-test with a Fatal instead?

---

*[pkg/sql/pgwire/types.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KkluZOSMl9ab7hNOcRW:-KlQ18K95rGSWL0lCjuA:bx121t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3968fa7838448695714e1a426f21f9e36ec142e/pkg/sql/pgwire/types.go#L477)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Because the pgwire format has enough digits for nanonsecond precision.
</blockquote></details>

Do these need comments? A citation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/pgwire/types.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KkluZOSMl9ab7hNOcRW:-KlQ0u1qC6Xjn_y7YR8d:bn32s61) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3968fa7838448695714e1a426f21f9e36ec142e/pkg/sql/pgwire/types.go#L477)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Do these need comments? A citation?
</blockquote></details>

It does? In all of our observations we've only seen microseconds being parsed and produced by postgres. Unless things have changed, supporting nanoseconds is a bad idea because we always round to microseconds when returning results over pgwire (I'm certain this is correct because some drivers error if we return nanoseconds). If there were nanoseconds in the database but micros being returned, then a user would not be able to select that row correctly since the data they saw was different than what was actually there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049)*

**Comment by jordanlewis** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/pgwire/types.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KkluZOSMl9ab7hNOcRW:-KlQDYYPLNIE6lko2OCL:bnez9mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3968fa7838448695714e1a426f21f9e36ec142e/pkg/sql/pgwire/types.go#L477)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

It does? In all of our observations we've only seen microseconds being parsed and produced by postgres. Unless things have changed, supporting nanoseconds is a bad idea because we always round to microseconds when returning results over pgwire (I'm certain this is correct because some drivers error if we return nanoseconds). If there were nanoseconds in the database but micros being returned, then a user would not be able to select that row correctly since the data they saw was different than what was actually there.
</blockquote></details>

Okay, reverted. I was just cargo culting what lib/pq does for an output format.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049)*

**Comment by jordanlewis** [comment]
Argh, this is still not quite finished. It looks like `pgjdbc` also generates timestamps of the form `2017-5-30 0:0:0.466000` when the hours, minutes or seconds field would be `00` in a sane output format.

So we need to add parsing for that. This kind of thing makes me think that we should abandon trying to use golang's time parser altogether and implement a hand-rolled parser the way Postgres did for all of their timestamp/timestamptz/date input formats.

**Comment by jordanlewis** [comment]
@mjibson PTAL

---

Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-:-KlUbw2LPj28Gf6jf_M4:bwfg4we)*

**Comment by mjibson** [comment]
LGTM. My comments can be ignored if you feel strongly.

---

Review status: 4 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/datum.go, line 1081 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KlUpaPR5ANpcvAXVKdx:-KlUpaPSsv9KtN__Fazy:b-ekjpyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/237a75ba07cdc979817d940557de4f3b6056e4f6/pkg/sql/parser/datum.go#L1081)):*
> ```Go
> 	timestampWithOffsetSecondsZoneFormat  = timestampWithOffsetMinutesZoneFormat + ":00"
> 	timestampWithNamedZoneFormat          = timestampFormat + " MST"
> 	timestampRFC3339NanoWithoutZoneFormat = dateFormat + "T15:04:05"
> ```

Why is this called nano even though it doesn't have nanoseconds?

---

*[pkg/sql/parser/datum.go, line 1112 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KlUpquzPg9wUIx0daIY:-KlUpquzPg9wUIx0daIZ:b-4w82vm) ([raw file](https://github.com/cockroachdb/cockroach/blob/237a75ba07cdc979817d940557de4f3b6056e4f6/pkg/sql/parser/datum.go#L1112)):*
> ```Go
> }
> 
> var tzMatch = regexp.MustCompile(` [+-]`)
> ```

maybe use a single `var ( ... )` block for these three

---

*[pkg/sql/parser/datum.go, line 1123 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KlUq0PkoBUD7JYdGqB_:-KlUq0PkoBUD7JYdGqBa:b-eflv3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/237a75ba07cdc979817d940557de4f3b6056e4f6/pkg/sql/parser/datum.go#L1123)):*
> ```Go
> 	// Thus, if we see `2015-10-05 3:0:50 +0:0:0` we need to change it to
> 	// `... 3:00:50 +00:00:00`.
> 	s = loneZeroRMatch.ReplaceAllString(s, ":00${1}")
> ```

I'm not thrilled about using two regex replacements during parsing of all incoming timestamps. Does it make sense to only do the replacement if it failed to find a match, and then try all the formats again? Maybe it doesn't matter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-:-KlV385xDKo3CYH1eTrS:blaice4)*

**Comment by jordanlewis** [comment]
Okay, looks like timestamps of the form `2017-5-31 21:8:35.752000` are also emitted. So the rule needs to be adjusted to handle single-digit M/H/S specifiers by prefixing them with 0s.

---

Review status: 4 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/datum.go, line 1081 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KlUpaPR5ANpcvAXVKdx:-KlVAf3JKZst7Hud0N-P:b2l5xxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/237a75ba07cdc979817d940557de4f3b6056e4f6/pkg/sql/parser/datum.go#L1081)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why is this called nano even though it doesn't have nanoseconds?
</blockquote></details>

No idea. Done.

---

*[pkg/sql/parser/datum.go, line 1112 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KlUpquzPg9wUIx0daIY:-KlVGjEZLtjmTs64ZzAG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/237a75ba07cdc979817d940557de4f3b6056e4f6/pkg/sql/parser/datum.go#L1112)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

maybe use a single `var ( ... )` block for these three
</blockquote></details>

Done.

---

*[pkg/sql/parser/datum.go, line 1123 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KlUq0PkoBUD7JYdGqB_:-KlVAxeHUL04tyM42bAE:b-3k6uur) ([raw file](https://github.com/cockroachdb/cockroach/blob/237a75ba07cdc979817d940557de4f3b6056e4f6/pkg/sql/parser/datum.go#L1123)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I'm not thrilled about using two regex replacements during parsing of all incoming timestamps. Does it make sense to only do the replacement if it failed to find a match, and then try all the formats again? Maybe it doesn't matter.
</blockquote></details>

Eh... that would mean we'd be systematically making JDBC timestamp inputs slower than the rest. The approach we use here is already super inefficient - surely this will not make it too much worse. Ideally we should hand write this parser.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-:-KlVO9TW1wBrZnjF9o7s:b-597bm0)*

**Comment by mjibson** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/datum.go, line 1123 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049#-KlUq0PkoBUD7JYdGqB_:-KlW86cCPcEmANSzYD8P:b32wtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/237a75ba07cdc979817d940557de4f3b6056e4f6/pkg/sql/parser/datum.go#L1123)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Eh... that would mean we'd be systematically making JDBC timestamp inputs slower than the rest. The approach we use here is already super inefficient - surely this will not make it too much worse. Ideally we should hand write this parser.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16049)*

**Comment by jordanlewis** [comment]
Should we include this in 1.0.2? Users can't parse various timestamps because of it. cc @mjibson

**Comment by mjibson** [comment]
I think it should be in 1.0.2. I'm going to include another grammar change to add READ ONLY/WRITE to BEGIN for a similar reason. I think Ben will chime in if you CC the release group in a cherrypick PR, and he can veto if he thinks it's a bad choice.

**Pull request merged**
