### PR TITLE
sql/schemachanger: add enum type values as an element

### PR DESCRIPTION
**Pull request by fqazi**
Previously, our decomposition of enum types only included
an element for the type itself. This was inadequate because
for multi-region support we need to be able to iterate over
the values for an enum. This patch adds further decomposition
for enums.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
:lgtm: other than the testdata file I don't think you meant to add 

> This was inadequate because
> for multi-region support we need to be able to iterate over
> the values for an enum.

We'll need this for adding and dropping enum values too. 

> Reviewed 24 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83802#-:-N6DP1346cqP5_qj5gpi:b-mlpaq1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[`pkg/sql/schemachanger/testdata/drop` line 1683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83802#-N6DPgHbB_jMRFB-NyP1:-N6DPgHbB_jMRFB-NyP2:b4xpq05) ([raw file](https://github.com/cockroachdb/cockroach/blob/716286befc63948c5fbd97e95651546fa16952dc/pkg/sql/schemachanger/testdata/drop#L1683)):*
> ```
> # end PostCommitPhase
> 
> setup
> ```

does this need to be split into multiple files / is this adding back a deleted file?



_Code quote:_
```
setup
CREATE DATABASE db1;
CREATE SCHEMA db1.sc1;
CREATE SEQUENCE db1.public.sq1;
CREATE SEQUENCE db1.sc1.sq1;
CREATE TABLE db1.sc1.t1 (id INT PRIMARY KEY, name varchar(256), val int DEFAULT nextval('db1.sc1.sq1'));
CREATE TABLE db1.public.t1 (id INT PRIMARY KEY, name varchar(256), val int DEFAULT nextval('db1.public.sq1'));
CREATE TABLE db1.public.ttl (id INT PRIMARY KEY) WITH (ttl_expire_after = '10 minutes');
CREATE VIEW db1.sc1.v1 AS (SELECT name FROM db1.sc1.t1);
CREATE VIEW db1.sc1.v2 AS (SELECT name AS n1, name AS n2 FROM db1.sc1.v1);
CREATE VIEW db1.sc1.v3 AS (SELECT name, n1 FROM db1.sc1.v1, db1.sc1.v2);
CREATE VIEW db1.sc1.v4 AS (SELECT n2, n1 FROM db1.sc1.v2);
CREATE TYPE db1.sc1.typ AS ENUM('a');
CREATE VIEW db1.sc1.v5 AS (SELECT 'a'::db1.sc1.typ::string AS k, n2, n1 from db1.sc1.v4);
----
...
+database {0 0 db1} -> 111
+schema {111 0 public} -> 112
+schema {111 0 sc1} -> 113
+object {111 112 sq1} -> 114
+object {111 113 sq1} -> 115
+object {111 113 t1} -> 116
+object {111 112 t1} -> 117
+object {111 112 ttl} -> 118
+object {111 113 v1} -> 119
+object {111 113 v2} -> 120
+object {111 113 v3} -> 121
+object {111 113 v4} -> 122
+object {111 113 typ} -> 123
+object {111 113 _typ} -> 124
+object {111 113 v5} -> 125

test
DROP DATABASE db1 CASCADE
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83802)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[`pkg/sql/schemachanger/testdata/drop` line 1683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83802#-N6DPgHbB_jMRFB-NyP1:-N6DYs405BIX9Wbp81D-:b-9mo4rv) ([raw file](https://github.com/cockroachdb/cockroach/blob/716286befc63948c5fbd97e95651546fa16952dc/pkg/sql/schemachanger/testdata/drop#L1683)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

does this need to be split into multiple files / is this adding back a deleted file?
</blockquote></details>

This was accidentally re-added. Dropping it from here
Done.

**Comment by ajwerner** [comment]
```
        -## StatementPhase stage 1 of 1 with 17 MutationType ops
        +## StatementPhase stage 1 of 1 with 14 MutationType ops
 ```
 
 Seems you need a rewrite

**Comment by fqazi** [comment]
@ajwerner TFTR!

bors r+

**Pull request merged**
