### PR TITLE
build: decrease duplication and interdependence of Makefiles

### PR DESCRIPTION
**Pull request by benesch**
See individual commit messages. @tamird, I believe this pretty neatly solves the issue of depending on yarn.installed in both pkg/ui/Makefile and build/protobuf.mk. Apologies this diff is so large; I did my best to separate everything that wasn't a straight copy/paste into build/common.mk into a separate commit.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14520)

### CODE REVIEW

**Comment by tamird** [comment]
:woman_scientist: :dog:  on the second commit, but :lgtm:, i think.

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[Makefile, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_in9uTU258C0poaVX:-Kg_in9uTU258C0poaVY:b-x2cphy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/Makefile#L19)):*
> ```Makefile
> # Author: Spencer Kimball (spencer.kimball@gmail.com)
> 
> # Variables to be overridden on the command line, e.g.
> ```

keep the word "only" and perhaps even explicitly call out that they can't be overridden in the env.

---

*[Makefile, line 77 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_ivkK-H7Dunwy1ZBi:-Kg_ivkK-H7Dunwy1ZBj:b-ngx2j5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/Makefile#L77)):*
> ```Makefile
> export MACOSX_DEPLOYMENT_TARGET=10.9
> 
> override .DEFAULT_GOAL := all
> ```

same questions about `override`

---

*[Makefile, line 79 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_kkNxfkIgyK7jetIp:-Kg_kkNxfkIgyK7jetIq:bsc6oa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/Makefile#L79)):*
> ```Makefile
> override .DEFAULT_GOAL := all
> override REPO_ROOT := .
> include build/common.mk
> ```

`$(REPO_ROOT)/` for consistency

---

*[build/common.mk, line 21 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hn3cJTsXLumRK4oJ:-Kg_hn3cJTsXLumRK4oK:b4n58ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L21)):*
> ```Makefile
> # the root of the repository before including this file.
> 
> # Variables to be control executable names. These can be overridden in the
> ```

"to be control"?

---

*[build/common.mk, line 30 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hsXG4WujdzOFJp_i:-Kg_hsXG4WujdzOFJp_j:bgpsozn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L30)):*
> ```Makefile
> 
> # Convenience variables for important paths.
> override ORG_ROOT  := $(REPO_ROOT)/..
> ```

too many spaces. why are these override?

---

*[build/common.mk, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hyLs8o3sSG8AFOsL:-Kg_hyLs8o3sSG8AFOsM:b-moqb65) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L36)):*
> ```Makefile
> # Ensure we we have an unambiguous in GOPATH.
> export GOPATH := $(realpath $(ORG_ROOT)/../../..)
> #                                     ^   ^  ^~ GOPATH
> ```

these should be indented one more space to be unambiguous

---

*[build/common.mk, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_iAUlmBCjmakM_eEB:-Kg_iAUlmBCjmakM_eEC:b-g6h0p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L43)):*
> ```Makefile
> # on the path. This ensures that we get the versions that we go install or yarn
> # install.
> export PATH := $(GOPATH)/bin:$(UI_ROOT)/node_modules/.bin:$(PATH)
> ```

let's remove node_modules from here, and replace all the invocations of tools in there with `yarn run foo`.

---

*[build/common.mk, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_j_-AFM1YZboWyWXn:-Kg_j_-AFM1YZboWyWXo:b-gj64ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L57)):*
> ```Makefile
> endif
> 
> # make-lazy converts a recursive variable, which is evaluated every time it's
> ```

why not just use "simple" variables (`:=`) here instead?

---

*[build/common.mk, line 75 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_jketo1Wa9aTgHW_9:-Kg_jketo1Wa9aTgHW_A:bl72g7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L75)):*
> ```Makefile
> $(call make-lazy,SED_INPLACE)
> 
> # We used to check the Go version in a .PHONY .go-version target, but the error
> ```

might want to put this above the various shell command executions you have above

---

*[build/protobuf.mk, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_iLykY2AictIG56uT:-Kg_iLykY2AictIG56uU:bo085o6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/protobuf.mk#L19)):*
> ```Makefile
> # This file is evaluated in the repo's parent directory. See main.go's
> # go:generate invocation.
> override .DEFAULT_GOAL := protos
> ```

why override?

---

*[build/protobuf.mk, line 20 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_iNfwr5iuStAyWBHe:-Kg_iNfwr5iuStAyWBHf:bkd75eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/protobuf.mk#L20)):*
> ```Makefile
> # go:generate invocation.
> override .DEFAULT_GOAL := protos
> override REPO_ROOT := ./cockroach
> ```

is this `override` so specifying it manually does nothing? is that better? seems more surprising, not less.

---

*[build/protobuf.mk, line 99 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_if0Xx4_sxa07eXDZ:-Kg_if0Xx4_sxa07eXD_:b7hcnyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/protobuf.mk#L99)):*
> ```Makefile
> 	# Add comment recognized by reviewable.
> 	echo '// GENERATED FILE DO NOT EDIT' > $@
> 	pbjs -t static-module -w es6 --strict-long --keep-case --path $(ORG_ROOT) --path $(GOGO_PROTOBUF_PATH) --path $(COREOS_PATH) --path $(GRPC_GATEWAY_GOOGLEAPIS_PATH) $(GW_PROTOS) >> $@
> ```

e.g. here: `yarn run pbjs ...`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-:-Kg_hdx-Nl_0T2toKk1n:btd1eud)*

**Comment by benesch** [comment]
Review status: 0 of 5 files reviewed at latest revision, 12 unresolved discussions.

---

*[Makefile, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_in9uTU258C0poaVX:-Kg_uh8ITh9aTSPyeCXs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/Makefile#L19)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

keep the word "only" and perhaps even explicitly call out that they can't be overridden in the env.
</blockquote></details>

Done.

---

*[Makefile, line 77 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_ivkK-H7Dunwy1ZBi:-Kg_rOWC5tf8DzLPYcvA:b-pnhr4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/Makefile#L77)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

same questions about `override`
</blockquote></details>

See below.

---

*[Makefile, line 79 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_kkNxfkIgyK7jetIp:-Kg_nmMWCVBaJVoRhhw5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/Makefile#L79)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`$(REPO_ROOT)/` for consistency
</blockquote></details>

Done.

---

*[build/common.mk, line 21 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hn3cJTsXLumRK4oJ:-Kg_np_sUvgky6Y3Noe5:b-dtkdrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L21)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"to be control"?
</blockquote></details>

Done, thanks.

---

*[build/common.mk, line 30 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hsXG4WujdzOFJp_i:-Kg_rQB_vpbmOHX7d7yQ:bl1p0ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L30)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

too many spaces. why are these override?
</blockquote></details>

Done. See below about override.

---

*[build/common.mk, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hyLs8o3sSG8AFOsL:-Kg_nv8a6Vabqk_8mp9z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L36)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

these should be indented one more space to be unambiguous
</blockquote></details>

Done.

---

*[build/common.mk, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_iAUlmBCjmakM_eEB:-Kg_nyODQkCAeseTjL0c:blthj9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L43)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

let's remove node_modules from here, and replace all the invocations of tools in there with `yarn run foo`.
</blockquote></details>

Done. Just a heads up that means a `cd $(UI_ROOT) && yarn run`, and `yarn run` has an annoying habit of printing out the (potentially very long) command before it runs it.

---

*[build/common.mk, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_j_-AFM1YZboWyWXn:-Kg_oM772J28HJLQaUdT:b-b0f8xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L57)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not just use "simple" variables (`:=`) here instead?
</blockquote></details>

These lazy variables have the handy property that they're not evaluated if they're not needed. So we won't pay the cost of e.g. figuring out the appropriate sed invocation unless the sed-using target in protobuf.mk is invoked.

---

*[build/common.mk, line 75 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_jketo1Wa9aTgHW_9:-Kg_ogOir7L-1lhV0ZPD:b-ej7z9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L75)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

might want to put this above the various shell command executions you have above
</blockquote></details>

If we keep those variables lazy we don't actually invoke the shell until those variables are expanded.

---

*[build/protobuf.mk, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_iLykY2AictIG56uT:-Kg_q-rkxO-wgLUfYkwE:b-pnhr4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/protobuf.mk#L19)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why override?
</blockquote></details>

See below.

---

*[build/protobuf.mk, line 20 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_iNfwr5iuStAyWBHe:-Kg_rhLfEDZd2GLckxY9:bbrze76) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/protobuf.mk#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this `override` so specifying it manually does nothing? is that better? seems more surprising, not less.
</blockquote></details>

I was trying to keep them out of build/variables.mk so that users would see an error if they specified them on the command line. Unfortunately, our variable whitelist can't actually warn you if you use an overridden variable, because the origin of that variable is never "command line"; it's always "file".

So you're right. This is more surprising. I've removed the `override` from all the variables I touched. If someone wants to shoot themselves in the foot by specifying REPO_ROOT, that's their prerogative, I suppose.

---

*[build/protobuf.mk, line 99 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_if0Xx4_sxa07eXDZ:-Kg_pyodB_AZmJQSua4A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/protobuf.mk#L99)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

e.g. here: `yarn run pbjs ...`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r4, 1 of 1 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[Makefile, line 23 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_wKONU1b32GGpA1hH:-Kg_wKONU1b32GGpA1hI:b21yhyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7330807691551a74c349e5e5240de4e077b612/Makefile#L23)):*
> ```Makefile
> #   make test PKG=./pkg/storage TESTFLAGS=--vmodule=raft=1
> #
> # Note that environment variables overrides are intentionally ignored.
> ```

s/variables/variable/?

---

*[build/common.mk, line 30 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hsXG4WujdzOFJp_i:-Kg_wxRo1U9yS_KNz0LG:b-7s86ji) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L30)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Done. See below about override.
</blockquote></details>

must've missed it. where?

---

*[build/common.mk, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hyLs8o3sSG8AFOsL:-Kg_wUaEMpU4pcm_Vo4l:b-ddssvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L36)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the leftmost one still points to the slash, move it one more space

---

*[build/common.mk, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_iAUlmBCjmakM_eEB:-Kg_wbbv73xmFNwuAL6h:b-5gwonu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L43)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Done. Just a heads up that means a `cd $(UI_ROOT) && yarn run`, and `yarn run` has an annoying habit of printing out the (potentially very long) command before it runs it.
</blockquote></details>

Fair. Make does that too, so we could `@` those commands to avoid the duplication.

---

*[build/common.mk, line 56 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_wnk-38JT6ED1xOj8:-Kg_wnk-38JT6ED1xOj9:b-n5au48) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7330807691551a74c349e5e5240de4e077b612/build/common.mk#L56)):*
> ```Makefile
> endif
> 
> GIT_DIR = $(shell git rev-parse --git-dir 2> /dev/null)
> ```

how come you de-lazied this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520)*

**Comment by benesch** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[Makefile, line 23 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_wKONU1b32GGpA1hH:-Kga0BkNnqzyWF_k-CM3:bmi03t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7330807691551a74c349e5e5240de4e077b612/Makefile#L23)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/variables/variable/?
</blockquote></details>

:anguished: fixed.

---

*[build/common.mk, line 30 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hsXG4WujdzOFJp_i:-Kga1FdkNpL5rQh__2qI:b-2m0zm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L30)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

must've missed it. where?
</blockquote></details>

omg reviewable. https://reviewable.io/reviews/cockroachdb/cockroach/14520#-Kg_iNfwr5iuStAyWBHe

---

*[build/common.mk, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hyLs8o3sSG8AFOsL:-Kga0Jaru6TOeVeNZfdO:b-ihntiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L36)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

the leftmost one still points to the slash, move it one more space
</blockquote></details>

Wow, sorry. My editor italicizes comments and it is impossible to get this right. I checked with `cat` this time.

---

*[build/common.mk, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_iAUlmBCjmakM_eEB:-Kga0Od7JO5bMKgtdafa:b6jl7sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L43)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Fair. Make does that too, so we could `@` those commands to avoid the duplication.
</blockquote></details>

Oh, good call. I like that a lot. Done.

---

*[build/common.mk, line 56 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_wnk-38JT6ED1xOj8:-Kga0dI8mX3qep99jpb7:b6gn6ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7330807691551a74c349e5e5240de4e077b612/build/common.mk#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come you de-lazied this?
</blockquote></details>

I realize it's always expanded below to compute the prereqs of `.bootstrap`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[build/common.mk, line 30 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hsXG4WujdzOFJp_i:-Kga1upFnA3Ckkb_HMQ1:btcjzh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L30)):*
Oh. I did read that, but I thought the outcome was removing the `override`, which is not what happened here?

> I was trying to keep them out of build/variables.mk so that users would see an error if they specified them on the command line. Unfortunately, our variable whitelist can't actually warn you if you use an overridden variable, because the origin of that variable is never "command line"; it's always "file".

> So you're right. This is more surprising. I've removed the override from all the variables I touched. If someone wants to shoot themselves in the foot by specifying REPO_ROOT, that's their prerogative, I suppose.

---

*[build/common.mk, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hyLs8o3sSG8AFOsL:-Kga1zlbj9Lr3tilrGMX:b-cv3a6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L36)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Wow, sorry. My editor italicizes comments and it is impossible to get this right. I checked with `cat` this time.
</blockquote></details>

Looks unchanged?

---

*[build/common.mk, line 56 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_wnk-38JT6ED1xOj8:-Kga1hq5I7UfuJqD5y9T:b-a46zwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7330807691551a74c349e5e5240de4e077b612/build/common.mk#L56)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I realize it's always expanded below to compute the prereqs of `.bootstrap`. 
</blockquote></details>

But then don't you want to make it simple with `:=`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520)*

**Comment by benesch** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[build/common.mk, line 30 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hsXG4WujdzOFJp_i:-Kga5y_JWBSdQbQk6hE8:b-em8zeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L30)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Oh. I did read that, but I thought the outcome was removing the `override`, which is not what happened here?

> I was trying to keep them out of build/variables.mk so that users would see an error if they specified them on the command line. Unfortunately, our variable whitelist can't actually warn you if you use an overridden variable, because the origin of that variable is never "command line"; it's always "file".

> So you're right. This is more surprising. I've removed the override from all the variables I touched. If someone wants to shoot themselves in the foot by specifying REPO_ROOT, that's their prerogative, I suppose.
</blockquote></details>

Herpaderp. How about now?

---

*[build/common.mk, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hyLs8o3sSG8AFOsL:-Kga5oxtuO_B4abDlRqM:b-3qnnyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L36)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Looks unchanged?
</blockquote></details>

This is what I see

```
export GOPATH := $(realpath $(ORG_ROOT)/../../..)
#                                       ^  ^  ^~ GOPATH
#                                       |  |~ GOPATH/src
#                                       |~ GOPATH/src/github.com


```

which seems right?

---

*[build/common.mk, line 56 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_wnk-38JT6ED1xOj8:-Kga5nLAzWIEbDA03AkD:bily6mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7330807691551a74c349e5e5240de4e077b612/build/common.mk#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

But then don't you want to make it simple with `:=`?
</blockquote></details>

Yes. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/common.mk, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-Kg_hyLs8o3sSG8AFOsL:-Kga6Da3Wo8FwlFUkkr-:b2e5tk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2863b308a51acfac52eb097e6cde89c3db0af713/build/common.mk#L36)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This is what I see

```
export GOPATH := $(realpath $(ORG_ROOT)/../../..)
#                                       ^  ^  ^~ GOPATH
#                                       |  |~ GOPATH/src
#                                       |~ GOPATH/src/github.com


```

which seems right?
</blockquote></details>

I think reviewable hid the whitespace diff. Classic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520)*

**Comment by benesch** [comment]
Tests failed because we had to cd to get `yarn run` to work, which broke the relativeness of `$@`. Solved with a subshell, but I think the old approach of including node_modules/.bin might have been cleaner. Thoughts, @tamird?

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-:-KgaDa9VgWyV8nXILFyv:b-bowb44)*

**Comment by benesch** [comment]
Including node_modules/.bin in the PATH. (How are these comments not editable urgh.)

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-:-KgaDn_7FTJ5hOJKvvIi:bna2jmm)*

**Comment by benesch** [comment]
Actually, using `yarn run` in protobuf.mk is enough of a nightmare that I think we should go back to the old approach. That work for you, @tamird?

---

Review status: 2 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-:-KgalMJxCIil9F6C0ZO3:b-2bh4mv)*

**Comment by tamird** [comment]
Hm, what's so bad about the subshell? I'm happy to take your word for it, but I do dislike putting random things on the PATH.

---

Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/common.mk, line 42 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-KgawXgVWildYcRClenO:-KgawXgVWildYcRClenP:bk90ood) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbae8f775d2fc9b18d9020306f3b08d4f08bb979/build/common.mk#L42)):*
> ```Makefile
> # Prefer tools we've installed with go install and Yarn to those elsewhere on
> # the path.
> export PATH := $(GOPATH)/bin:$(UI_ROOT)/node_modules/.bin:$(PATH)
> ```

let's put node modules at the end, not the front?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14520#-:-KgawQ4RZlwLUDMQFU5k:bvdqmk0)*

**Comment by benesch** [comment]
We want to prefer our pbjs to a system installed pbjs, no?

The trouble stems from using $@ inside a (cd $(UI_ROOT) && yarn run
pbjs...) subshell. $@ is relative so it's incorrect once you've cd'd. Since
we control our package.json and thus exactly what goes into
node_modules/.bin, I'm not too worried.

Apologies for formatting; on my phone.

**Comment by tamird** [comment]
Ah, you sold me. Carry on but consider adding a comment describing your
findings.

**Pull request merged**
