### PR TITLE
sql: remove selectTopNode.

### PR DESCRIPTION
**Pull request by knz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13192)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Fantastic! :lgtm_strong: 

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/testdata/needed_columns, line 165 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13192#-KbVDmN03UDsKbtkSuKu:-KbVDmN03UDsKbtkSuKv:b6vyq0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/eedb6e9fedbb151cdeac4a8af6973af03113c554/pkg/sql/testdata/needed_columns#L165)):*
> ```
> 0          render 0  1
> 1  scan                          (k[omitted], v[omitted])  +k,unique
> 1          table     kv@primary
> ```

Can you help me understand where this improvement is coming from? Why wasn't the elision in exepandRenderNode happening before - was it because of the "not yet expanded" case in setNeededColumns (we were first trying to do the elision and then marking the columns as omitted?)

Also, [nit] I think there's a missing newline at the end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13192#-:-KbVDf8VvSDv9Z12l3iF:bkj6hvn)*

**Comment by knz** [comment]
Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/testdata/needed_columns, line 165 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13192#-KbVDmN03UDsKbtkSuKu:-KbVVZuVgcHGPDTN5hcP:b-t20rsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/eedb6e9fedbb151cdeac4a8af6973af03113c554/pkg/sql/testdata/needed_columns#L165)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you help me understand where this improvement is coming from? Why wasn't the elision in exepandRenderNode happening before - was it because of the "not yet expanded" case in setNeededColumns (we were first trying to do the elision and then marking the columns as omitted?)

Also, [nit] I think there's a missing newline at the end.
</blockquote></details>

Yes that is correct -- the "blind spot" in setNeededColumns has now disappeared.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13192)*

**Comment by knz** [comment]
TFYR

**Comment by jordanlewis** [comment]
Nice work!

**Comment by knz** [comment]
😸
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
