### PR TITLE
vendor: bump pebble to 58fbf96a8f51843163a39ca14410f8a4d81762f4

### PR DESCRIPTION
**Pull request by petermattis**
Picks up the fix for the reverse scan bug, as well as other enhancements
and optimizations.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[Gopkg.lock, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42126#-LsqcO_o6mr96xEdnuHP:-LsqcO_o6mr96xEdnuHQ:bc0ycmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/659d8fb2884c764fe7b5b733ffc36b4c7f324130/Gopkg.lock#L490)):*
> ```TOML
>   ]
>   pruneopts = "UT"
>   revision = "58fbf96a8f51843163a39ca14410f8a4d81762f4"
> ```

I matched this with a commit hash. Where do the digest and subproject commit come from?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[Gopkg.lock, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42126#-LsqcO_o6mr96xEdnuHP:-Lsqiv1L4u-ByNPcAahx:b1qtbsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/659d8fb2884c764fe7b5b733ffc36b4c7f324130/Gopkg.lock#L490)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I matched this with a commit hash. Where do the digest and subproject commit come from?
</blockquote></details>

`digest` is something that the `dep` tool produces. The `submodule` commit comes from running `bin/dep ensure` and then going into the `vendor` directory, creating a branch with the changes, and pushing that branch. There are instructions somewhere on how to do this. I'll track them down if you're interested.

**Comment by petermattis** [comment]
TFTR!

bors r+

**Comment by petermattis** [comment]
Unrelated CI failure (`TestMergeJoinerAgainstProcessor`).

bors r+

**Pull request merged**
