### PR TITLE
sql: fix assignment of global typDelim var

### PR DESCRIPTION
**Pull request by rafiss**
refs https://github.com/cockroachdb/cockroach/pull/82304

This fixes a bug that caused tests to fail under stress.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82526#-:-N3yv6E71HTFscu6O7Z-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[`pkg/sql/pg_catalog.go` line 2803 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82526#-N3yv45WDcJrWnGM9wHs:-N3yv45WDcJrWnGM9wHt:b-t6tp9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebce2ec2f978984d608a677a45c6fc892724809/pkg/sql/pg_catalog.go#L2803)):*
> ```Go
> 	_ = typCategoryBitString
> 
> 	commaTypDelim = tree.NewDString(",")
> ```

can this be const?

**Comment by rafiss** [comment]
unfortunately  no, since `tree.NewDString` doesn't  allow that

bors p=1000 r=andreimatei

**Comment by rafiss** [comment]
bors p=10000

**Comment by rafiss** [comment]
lol one more try

bors merge p=10000

**Review by ecwall — APPROVED** [review]

**Review by otan — COMMENTED** [review]
sorry for missing this on review & thanks for fixing it!

**Pull request merged**
