### PR TITLE
sql docs: fix keyword comments in parser

### PR DESCRIPTION
**Pull request by couchand**
Just cleaning up the comments that refer to `kwlist.h` since that file doesn't exist.

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Comment by knz** [comment]
thank you!

**Comment by knz** [comment]
(you need to regenerate sql.go)

**Comment by couchand** [comment]
Of course @knz, forgot that the comments persist to the generated file.

**Comment by knz** [comment]
TC is slightly grumpy like every morning, let it do its thing then restart just the remaining failing test

**Comment by couchand** [comment]
Oh I see, it doesn't actually persist the comments, but it does change the line numbers.

**Comment by knz** [comment]
there you go, TC did its thing (there was a stuck agent, I euthanized it)

**Pull request merged**
