### PR TITLE
workload/tpcc: add multiregion TPC-C setup

### PR DESCRIPTION
**Pull request by otan**
Introduce a tpcc workload for multi-region, which can be triggered by
specifying `--regions comma-separated-list-of-regions`. I've preserved
the existing TPC-C options in case we want to test legacy
configurations.

The schema creation was changed to something using the options pattern
which makes it a lot cleaner to specify the schema.

Release note: None

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Sorry for the delay.  Could have sworn I wrapped this up on Friday :frowning: 

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-:-Mb1O-d2EaMzfwh06zp7:bpjpugq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)

___
*[pkg/cmd/roachtest/tpcc.go, line 352 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1L7CvB1ldWs6susOs:-Mb1L7CvB1ldWs6susOt:b-tweuq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c972190c143808c1db297f03da3279d73d1fe444/pkg/cmd/roachtest/tpcc.go#L352)):*
> ```Go
> 	})
> 
> 	for _, survivalGoal := range []string{"az", "region"} {
> ```

Nit: az->zone?
___
*[pkg/cmd/roachtest/tpcc.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1Lkuq4ftoHNK88jHn:-Mb1LkurDIG1753jt0md:b66zt6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c972190c143808c1db297f03da3279d73d1fe444/pkg/cmd/roachtest/tpcc.go#L365)):*
> ```Go
> 			Owner:      OwnerMultiRegion,
> 			MinVersion: "v21.1.0",
> 			Cluster:    makeClusterSpec(10, geo(), zones(strings.Join(zs, ","))),
> ```

Why 10 nodes?  Is the extra one for the client?  Could you add a comment explaining the rationale here?
___
*[pkg/cmd/roachtest/tpcc.go, line 377 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1MVjJ3c0THlA9Zpbv:-Mb1MVjJ3c0THlA9Zpbw:b5ir1kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c972190c143808c1db297f03da3279d73d1fe444/pkg/cmd/roachtest/tpcc.go#L377)):*
> ```Go
> 				// on each node of a cluster, instead of one node using a workload on all clusters.
> 				runTPCC(ctx, t, c, tpccOptions{
> 					Warehouses:     9,
> ```

Nit: Make this a function of the number of nodes?
___
*[pkg/workload/tpcc/ddls.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1JjTW0oyiAJHwfQ-w:-Mb1JjTW0oyiAJHwfQ-x:b-hpimd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/ddls.go#L233)):*
> ```Go
> }
> 
> func maybeAddLocalityRegionalByRow(
> ```

Might be worth adding a comment here to describe what we're doing.  It took me a few minutes to realize that `%%` meant that we were modding the warehouse number by the number of regions.  We also might want to note here that if the number of warehouses is ever increased after the partitioning is applied, this will break (or at least, that's my understanding).
___
*[pkg/workload/tpcc/partition.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mai63XN4V-mr_h63YzT:-Mai63XN4V-mr_h63YzU:b6tpeao) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/partition.go#L122)):*
> ```Go
> 
> const (
> 	survivalGoalAZ survivalGoal = iota
> ```

Nit: `survivalGoalZone`?  To match the terminology we use in SHOW DATABASES?
___
*[pkg/workload/tpcc/partition.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mai6psI8eK7XWr7cWdy:-Mai6psI8eK7XWr7cWdz:beschuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/partition.go#L130)):*
> ```Go
> 	switch s {
> 	case survivalGoalAZ:
> 		return "az"
> ```

Nit: zone?
___
*[pkg/workload/tpcc/tpcc.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-MaocvltCrppV_jo-qHw:-Maocvlu1YSi6Vg3JSpF:b-3cv1r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L204)):*
> ```Go
> 			`is that the URLs are distributed evenly over the partitions`)
> 		g.flags.Var(&g.zoneCfg.strategy, `partition-strategy`, `Partition tables according to which strategy [replication, leases]`)
> 		g.flags.StringSliceVar(&g.zoneCfg.zones, "zones", []string{}, "Zones for partitioning, the number of zones should match the number of partitions and the zones used to start cockroach.")
> ```

Should we be removing zones?  Is there any reason why someone would want to use zones now that we have regions?
___
*[pkg/workload/tpcc/tpcc.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-MaodM44CfD63JGZCgn3:-MaodM44CfD63JGZCgn4:bwp91jx) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L277)):*
> ```Go
> 
> 				if len(w.multiRegionCfg.regions) > 0 && (len(w.multiRegionCfg.regions) != w.partitions) {
> 					return errors.Errorf(`--regions should have the same length as --partitions.`)
> ```

Can we infer partitions in the case where regions is specified?
___
*[pkg/workload/tpcc/tpcc.go, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-MaoeA8d5lyKA2DjAnSs:-MaoeA8d5lyKA2DjAnSt:bqgnv33) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L367)):*
> ```Go
> 				var stmt string
> 				if i == 0 {
> 					stmt = fmt.Sprintf(`alter database %s set primary region %q`, dbName, region)
> ```

Seems like we're implying here the first specified is the primary region.  We should either document that, or, what might make the logic here simpler is if you also add a --primary-region flag.
___
*[pkg/workload/tpcc/tpcc.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-MaoeWZV1OHnIZ3AgZJl:-MaoeWZV1OHnIZ3AgZJm:bub9eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L387)):*
> ```Go
> 				panic("unexpected")
> 			}
> 			stmts = append(stmts, fmt.Sprintf(`alter database %s survive %s`, dbName, survivalGoal))
> ```

Nit: we should only need to do this for region, right?  Or is it possible that the database already exists at the time of this call?

Also, do we need to check that there are 3 regions before setting region survivability?
___
*[pkg/workload/tpcc/tpcc.go, line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1Hi4805YkpOaNeWbh:-Mb1Hi4805YkpOaNeWbi:by0e3an) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L437)):*
> ```Go
> 					}
> 				}
> 				// Set GLOBAL only after data is loaded to speed up initialization time.
> ```

Can you remind me again why this is needed?  Is it because we're inserting here, instead of IMPORTing?  Does it make sense to call out that rationale here?  Or better yet, change this to use IMPORT?
___
*[pkg/workload/tpcc/tpcc.go, line 445 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1IA5O7rVCvTeHwele:-Mb1IA5O7rVCvTeHwelf:b-ez0gp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L445)):*
> ```Go
> 			}
> 
> 			if len(w.multiRegionCfg.regions) != 0 {
> ```

This is to preserve the old behaviour too, if regions aren't specified?  If so, might be worth including a comment here, for future readers.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65600)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @nvanbenschoten)

___
*[pkg/cmd/roachtest/tpcc.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1Lkuq4ftoHNK88jHn:-Mb3qh-M471CCWrHC2u0:bm77ulk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c972190c143808c1db297f03da3279d73d1fe444/pkg/cmd/roachtest/tpcc.go#L365)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Why 10 nodes?  Is the extra one for the client?  Could you add a comment explaining the rationale here?
</blockquote></details>

Yeah, it's standard through all the roachtest setups here.
___
*[pkg/cmd/roachtest/tpcc.go, line 377 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1MVjJ3c0THlA9Zpbv:-Mb3qlxtCYQUMRN-E1Fx:b-wf2dtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c972190c143808c1db297f03da3279d73d1fe444/pkg/cmd/roachtest/tpcc.go#L377)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Make this a function of the number of nodes?
</blockquote></details>

i think we can make this arbitrarily large/small and not based on the number of nodes, so i'm hesitant to make it a function for now.
___
*[pkg/workload/tpcc/ddls.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1JjTW0oyiAJHwfQ-w:-Mb3rIAZ3mwg7q_W5sCi:b-hqkp7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/ddls.go#L233)):*
> modding the warehouse number by the number of regions

modding the ID (primary key) by the number of partitions.

> We also might want to note here that if the number of warehouses is ever increased after the partitioning is applied, this will break (or at least, that's my understanding).

where did you get that impression?
___
*[pkg/workload/tpcc/tpcc.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-MaocvltCrppV_jo-qHw:-Mb3rnbXAe1LB356azWn:b-1xva7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L204)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Should we be removing zones?  Is there any reason why someone would want to use zones now that we have regions?
</blockquote></details>

Seems like some legacy tests still use it, I'm not up for gutting everything atm.
___
*[pkg/workload/tpcc/tpcc.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-MaodM44CfD63JGZCgn3:-Mb3rz2SCA97Np2IKWwm:bo2wrng) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L277)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can we infer partitions in the case where regions is specified?
</blockquote></details>

I'm following the same code as for --zones, so i'm going to let this be for now.
___
*[pkg/workload/tpcc/tpcc.go, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-MaoeA8d5lyKA2DjAnSs:-Mb3sCwa11PSMQp03RiU:b-6q4yrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L367)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Seems like we're implying here the first specified is the primary region.  We should either document that, or, what might make the logic here simpler is if you also add a --primary-region flag.
</blockquote></details>

I'll do documenting for now.
___
*[pkg/workload/tpcc/tpcc.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-MaoeWZV1OHnIZ3AgZJl:-Mb3sEt16HCdNIRiaRtB:b-ip6r5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L387)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: we should only need to do this for region, right?  Or is it possible that the database already exists at the time of this call?

Also, do we need to check that there are 3 regions before setting region survivability?
</blockquote></details>

I think it's safe for this to do "idempotency" and do it regardless.

Added validation for 3 regions, but the database checks for us anyway.
___
*[pkg/workload/tpcc/tpcc.go, line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1Hi4805YkpOaNeWbh:-Mb3sdFR9HAcaYkWQCfU:b-h4q2zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L437)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can you remind me again why this is needed?  Is it because we're inserting here, instead of IMPORTing?  Does it make sense to call out that rationale here?  Or better yet, change this to use IMPORT?
</blockquote></details>

I thought IMPORT didn't work.

Regardless, INSERT is slow so yes we defer it. Commented extra.
___
*[pkg/workload/tpcc/tpcc.go, line 445 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1IA5O7rVCvTeHwele:-Mb3t53m4JmTiNJow6p8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L445)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This is to preserve the old behaviour too, if regions aren't specified?  If so, might be worth including a comment here, for future readers.
</blockquote></details>

Done.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65600)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)

___
*[pkg/cmd/roachtest/tpcc.go, line 377 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1MVjJ3c0THlA9Zpbv:-Mb6TZjk00T3xBqPLFoi:beyeauh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c972190c143808c1db297f03da3279d73d1fe444/pkg/cmd/roachtest/tpcc.go#L377)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think we can make this arbitrarily large/small and not based on the number of nodes, so i'm hesitant to make it a function for now.
</blockquote></details>

Does it warrant a comment in some way?  I'd think that we'd need to make this a multiple of the number of nodes or else the warehouse count will be unbalanced.
___
*[pkg/workload/tpcc/ddls.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1JjTW0oyiAJHwfQ-w:-Mb6TqrrC65Wexw0ow8L:bksla73) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/ddls.go#L233)):*
> where did you get that impression?

Sorry, I was unclear.  If we add more regions to the database (which presumably would imply more warehouses as well, but isn't strictly required), won't the static hashing of partition number to region break?  That's what I was suggesting we comment.  

Or maybe I'm still confused.
___
*[pkg/workload/tpcc/tpcc.go, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-MaoeA8d5lyKA2DjAnSs:-Mb6VYq5EELeTSvow5Pp:b-vs1pr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L367)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I'll do documenting for now.
</blockquote></details>

Looks good.
___
*[pkg/workload/tpcc/tpcc.go, line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1Hi4805YkpOaNeWbh:-Mb6Vt3H1BhLOgKJPzpq:b-2aa4ve) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L437)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I thought IMPORT didn't work.

Regardless, INSERT is slow so yes we defer it. Commented extra.
</blockquote></details>

IMPORT works for GLOBAL and REGIONAL BY TABLE tables, just not for RBR.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65600)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @nvanbenschoten)

___
*[pkg/cmd/roachtest/tpcc.go, line 377 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1MVjJ3c0THlA9Zpbv:-Mb8KSMgEE-GLD8YcXEA:bh4jx4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c972190c143808c1db297f03da3279d73d1fe444/pkg/cmd/roachtest/tpcc.go#L377)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Does it warrant a comment in some way?  I'd think that we'd need to make this a multiple of the number of nodes or else the warehouse count will be unbalanced.
</blockquote></details>

hmm, you have convinced me.
___
*[pkg/workload/tpcc/ddls.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1JjTW0oyiAJHwfQ-w:-Mb8KWgtDD-EKO0dX1uK:ba15frj) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/ddls.go#L233)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

> where did you get that impression?

Sorry, I was unclear.  If we add more regions to the database (which presumably would imply more warehouses as well, but isn't strictly required), won't the static hashing of partition number to region break?  That's what I was suggesting we comment.  

Or maybe I'm still confused.
</blockquote></details>

ah yes, you are correct. i'll add that comment.
___
*[pkg/workload/tpcc/tpcc.go, line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-Mb1Hi4805YkpOaNeWbh:-Mb8Jypz-LBDuNcx-Gyk:bxadn1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/501ebd460a2d1a02d76f32c94fcfa560d77760ca/pkg/workload/tpcc/tpcc.go#L437)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

IMPORT works for GLOBAL and REGIONAL BY TABLE tables, just not for RBR.
</blockquote></details>

ah, well the roachtest currently works with init we're going with this
for IMPORT, this should be idempotent anyway.

**Review by ajstorm — APPROVED** [review]
Thanks for making the changes.  :lgtm: 

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65600#-:-Mb9O8ZyA_EWnNtiUxKJ:b-m4vhzm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by otan — COMMENTED** [review]
bors r=ajstorm

**Pull request merged**
