### PR TITLE
sql: alter gc ttl on sql stats tables to 1h

### LINKED ISSUE #100138: improve mvcc garbage on sql stats tables
Reduce the gc ttl of sql stats system tables.

Jira issue: CRDB-26271

### PR DESCRIPTION
**Pull request by maryliag**
Fixes #100138

Every 10min data is flushed to system tables
`statement_statistics` and `transactions_statistics`,
then every hour data gets deleted from it. This process
can generate a lot of garbage and make selects on those
tables take a long time, specially for users who
generate a large amount of data.
In 23.1 the GC TTL was changed to 4hrs, but all clusters
created before that have a value of 25h.

This commit updates the GC TTL to 1h on those two tables, and
2 new tables being created based on the prior 2 ones.
The focus is for Self Hosted and Dedicated, and no changes
are done for Serverless, which already has a 1.25h GC TTL.

Expected behaviour with this change:
- Pre 23.1 SH/Dedicated that haven't run this migration will
have GC TTL as 25h
- Pre 23.1 SH/Dedicate and new 23.1 cluster with system tenant
will run this migration and have the GC TTL value set to 1h
- Serverless will continue to have GC TTL as 1.25h
- New 23.1 clusters using secondary tenants will use the
default value of 4h and won't run this migration

Release note (sql change): Changr GC TTL on SQL Stats table to 1h
on CC Dedicated and Self-Hosted Clusters. This change is not
applicable to Serverless and 23.1 with secondary tenants.

### CODE REVIEW

**Review by j82w — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100141#-:-NRnHP5a8t9cSzOueiWN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @celiala)

**Review by celiala — APPROVED** [review]
Version gate placement LGTM!

**Comment by maryliag** [comment]
flaky tests
bors r+

**Comment by maryliag** [comment]
bors p=99 single on r+

**Comment by maryliag** [comment]
bors p=99 single on r+

**Review by knz — COMMENTED** [review]
I have reviewed this further. This is mostly good to go, as long as we clarify the narrative in the commit message.

> Reviewed 1 of 5 files at r1, 2 of 24 files at r4, 1 of 5 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100141#-:-NRsQDUkDduKKQz5UT0m:b-z3a6cq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w and @maryliag)

___
*[`-- commits` line 6 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/100141#-NRsQKxz3zeW-XAEnMBX):*
I think this commit message should have more words about "why" we are doing this change, what was the previous situation and what is the new situation.

In particular, the idea used to limit the change to the system tenant is counter to our engineering goal to *stop making special cases about the system tenant in 23.1*.
As determined through this internal discussion, this choice is legitimate here, but because it is an exception the exception needs to be explained in the commit message.

The commit message should thus say something about this be only needed for SH customers and CC Dedicated clusters created prior to 23.1; which have A) only a system tenant B) a default GCC TTL of 25 hours.

In particular the PR doesn't do anything about secondary tenants.
- in CC Serverless tenants already have a 1.25h GC TTL configured as per CC-7128
- in CC Dedicated / SH post-23.1 which will use secondary tenants ("unified architecture"), the new default of 4 hours will be applicable, which obviates the need for this PR as well.

As a result (and that is worth highlighting in the commit message) once this PR goes in we will see a bunch of special cases popping up in production:

- pre-23.1 SH/Dedicated clusters that have not yet run this migration  will still have the TTL set to 25h
- CC Serverless will never run this migration and have a TTL set to 1.25h
- new 23.1 clusters using secondary tenants will use the new default TTL of 4h, and will not run this migration ever
- only pre-23.1 SH/Dedicated clusters that run this migration, or new 23.1 clusters which are configured to use only a system tenant, will also run the migration and see their TTL lowered further to 1h.

(I personally think this proliferation of TTL values will sadden us during troubleshooting; but there's not much this PR can do here.)
___
*[`-- commits` line 9 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/100141#-NRsPnhF7xON7jIgVJlP):*
This release note is incomplete. It should state that the change applies only to CC Dedicated and Self-hosted clusters. Serverless clusters using secondary tenants are not going to see this change since you've limited it to only the system tenant.

**Pull request merged**
