### PR TITLE
*: standardize all sub-benchmarks on key=value format

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Review by tbg — APPROVED** [review]
LGTM. Skimmed this only.

**Comment by tamird** [comment]
I'd like to get everyone's "ack" on this, at least, since new benchmarks should be written in this style as well.

**Comment by petermattis** [comment]
:lgtm:

Might want to drop a page on the github wiki explaining (briefly) why this is useful/important.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/sorter_test.go, line 245 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830#-Ko-d0i5nSF_8_auaLiX:-Ko-d0i5nSF_8_auaLiY:b-50dgjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe610d56a6cb3e108591a09d9349e970241815e4/pkg/sql/distsqlrun/sorter_test.go#L245)):*
> ```Go
> 
> 	for _, inputSize := range []int{0, 1 << 2, 1 << 4, 1 << 8, 1 << 12, 1 << 16} {
> 		b.Run(fmt.Sprintf("InputSize=%d", inputSize), func(b *testing.B) {
> ```

Moving the `b.Run` call might affect the timing. I imagine the timer only starts when `b.Run` is called. I think I'd revert this part of the change unless you had a strong reason for doing so.

PS We're not consistent in capitalization for these "keys". Does that matter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830#-:-Ko-dSJhtveiAdBubGgQ:bx4w6qp)*

**Comment by tamird** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/sorter_test.go, line 245 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830#-Ko-d0i5nSF_8_auaLiX:-Ko1sgNwBEl1skPDs86h:b-jujz5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe610d56a6cb3e108591a09d9349e970241815e4/pkg/sql/distsqlrun/sorter_test.go#L245)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Moving the `b.Run` call might affect the timing. I imagine the timer only starts when `b.Run` is called. I think I'd revert this part of the change unless you had a strong reason for doing so.

PS We're not consistent in capitalization for these "keys". Does that matter?
</blockquote></details>

Ah, I moved the call to `b.Run` so that failures here would only tank the sub-bench rather than the top-level one.

Looking at this more, are we intentionally measuring the time taken by `rowSource.Reset`? @arjunravinarayan @asubiotto 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830)*

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/sorter_test.go, line 245 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830#-Ko-d0i5nSF_8_auaLiX:-Ko2CqZp3HXThvSYie56:bdl2wzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe610d56a6cb3e108591a09d9349e970241815e4/pkg/sql/distsqlrun/sorter_test.go#L245)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Ah, I moved the call to `b.Run` so that failures here would only tank the sub-bench rather than the top-level one.

Looking at this more, are we intentionally measuring the time taken by `rowSource.Reset`? @arjunravinarayan @asubiotto 
</blockquote></details>

`rowSource.Reset` is trivial (it sets an index). I doubt the `b.Fatal` ever fired. I'd move the placement of `b.Run` back in this PR and let @arjunravinarayan and @asubiotto sort it out in a follow-on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830)*

**Comment by tamird** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsqlrun/sorter_test.go, line 245 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830#-Ko-d0i5nSF_8_auaLiX:-Ko9ng2KbcAvPB9cqEkd:b-1ve8eo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe610d56a6cb3e108591a09d9349e970241815e4/pkg/sql/distsqlrun/sorter_test.go#L245)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`rowSource.Reset` is trivial (it sets an index). I doubt the `b.Fatal` ever fired. I'd move the placement of `b.Run` back in this PR and let @arjunravinarayan and @asubiotto sort it out in a follow-on.
</blockquote></details>

I went with a more explicit call to `b.ResetTimer()`; PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830)*

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/sorter_test.go, line 245 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830#-Ko-d0i5nSF_8_auaLiX:-KoHtLsqkmCyvfA3igz0:b96mcoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe610d56a6cb3e108591a09d9349e970241815e4/pkg/sql/distsqlrun/sorter_test.go#L245)):*
> We're not consistent in capitalization for these "keys". Does that matter?

Ping.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830)*

**Comment by tamird** [comment]
Ah sorry, missed that. Doesn't matter.

**Comment by arjunravinarayan** [comment]
Skimmed, new convention looks fine. :lgtm:
Did not look closely.

---

Reviewed 1 of 9 files at r2, 3 of 9 files at r3.
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/sorter_test.go, line 245 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830#-Ko-d0i5nSF_8_auaLiX:-KoI8BlXncDY0Mjre5h_:bfkl892) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe610d56a6cb3e108591a09d9349e970241815e4/pkg/sql/distsqlrun/sorter_test.go#L245)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

> We're not consistent in capitalization for these "keys". Does that matter?

Ping.
</blockquote></details>

I'll let @asubiotto authoritatively answer this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830#-:-KoI81OVtY2OkgOreFPn:bi8vobq)*

**Comment by asubiotto** [comment]
:lgtm: Might be nice to make capitalization of the keys consistent but I have no strong feelings about it.

---

Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/sorter_test.go, line 245 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830#-Ko-d0i5nSF_8_auaLiX:-KoI9fLWkHY9Gkrhws86:b-h2axaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe610d56a6cb3e108591a09d9349e970241815e4/pkg/sql/distsqlrun/sorter_test.go#L245)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I'll let @asubiotto authoritatively answer this.
</blockquote></details>

This call to `ResetTimer` is fine. I don't think there's a need to have this change in a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16830#-:-KoI9OMlY6ogDcIPNkDW:bzennrm)*

**Pull request merged**
