### PR TITLE
sql: SHOW QUERIES lazily interpolates placeholders

### PR DESCRIPTION
**Pull request by jordanlewis**
SHOW QUERIES (and crdb_internal.node_queries, cluster_queries)
interpolates placeholder values into the statement so that it is
possible to see the placeholder values of a prepared statement - but it
used to do this unconditionally during statement execution.

This is an expensive process that spends a lot of CPU for little reason,
since the interpolation was happening in the hot path of every query.

Now, we include the placeholder values as a separate array in the
internal representation of active queries, and interpolate the values
only when they're being pulled out to examine, to avoid the
unconditional runtime interpolation costs.

As a side effect of this change, the original comments in a query are
now included in SHOW QUERIES and the two active queries tables.

Release note (sql change): the query field in the
crdb_internal.node_queries, crdb_internal.cluster_queries, and SHOW
QUERIES commands now includes the original comments in the queries.

Informs CRDB-17299

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice improvements! both changes need tests

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-:-NAREKaF1xxo9nBVzaeH:b9f01sp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[`pkg/sql/conn_executor.go` line 3163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-NARDuOv260C2mep5PGC:-NARDuOv260C2mep5PGD:b-lchjgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f3778139a4e359c3eb195e989fde600dc62caf0/pkg/sql/conn_executor.go#L3163)):*
> ```Go
> 		placeholders := make([]string, nPlaceholders)
> 		for i := range placeholders {
> 			placeholders[i] = query.placeholders.Values[i].String()
> ```

nit: maybe use `tree.AsStringWithFlags(..., tree.FmtPgwireText)` here
___
*[`pkg/sql/crdb_internal.go` line 1894 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-NARDRjy9uYzPlIkwTJP:-NARDRjy9uYzPlIkwTJQ:b-dtxdl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f3778139a4e359c3eb195e989fde600dc62caf0/pkg/sql/crdb_internal.go#L1894)):*
> ```Go
> 				return err
> 			}
> 			arr := tree.NewDArray(types.String)
> ```

nit: name it `placeholders` instead of `arr`
___
*[`pkg/sql/crdb_internal.go` line 1897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-NARDNVKAhLWWK55dv8f:-NARDNVKAhLWWK55dv8g:b-tcq90f) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f3778139a4e359c3eb195e989fde600dc62caf0/pkg/sql/crdb_internal.go#L1897)):*
> ```Go
> 			arr.Array = make(tree.Datums, len(query.Placeholders))
> 			for i, v := range query.Placeholders {
> 				arr.Array[i] = tree.NewDString(v)
> ```

does this need to use `(*Darray).Append`?

**Review by rafiss — CHANGES_REQUESTED** [review]
the first commit needs new tests, and fixes to existing ones

**Comment by jordanlewis** [comment]
Yes, sorry, it's not ready for review yet.

**Comment by jordanlewis** [comment]
I reworked this to lazily interpolate the output of crdb_internal.cluster_statements etc as well as SHOW QUERIES, to avoid changing the API. If we want to change the API we can do it later. Now, we still gain the performance enhancements because we avoid having to unconditionally interpolate during the hot path - instead, we interpolate just when printing the active queries on the other end.

**Comment by jordanlewis** [comment]
PTAL @rafiss

**Review by rafiss — APPROVED** [review]
this lgtm! just had one optional comment about testing.

does the first commit mean that we will get comments in telemetry logging?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-:-NEwoJthD-ycwJ7_V44q:b-3hasf8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`pkg/sql/show_test.go` line 735 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-NEwp3Na20_zzOFJxphb:-NEwp3NbDvyDnVpeSWhS:b-n42qu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af162a236d241be8893302c8b3de5c158aeca18/pkg/sql/show_test.go#L735)):*
> ```Go
> 		},
> 		{
> 			"SELECT /* test */ 'hi'::string",
> ```

what if there are two comments?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`-- commits` line 28 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-NEwryAN3iTgb_vTAipP):*
this release note is old

**Comment by jordanlewis** [comment]
> does the first commit mean that we will get comments in telemetry logging?

Yes, I believe so.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 28 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-NEwryAN3iTgb_vTAipP):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this release note is old
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal.go` line 1897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-NARDNVKAhLWWK55dv8f:-NARIXayBunwiJUrsw0P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f3778139a4e359c3eb195e989fde600dc62caf0/pkg/sql/crdb_internal.go#L1897)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this need to use `(*Darray).Append`?
</blockquote></details>

Done.
___
*[`pkg/sql/show_test.go` line 735 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-NEwp3Na20_zzOFJxphb:-NFKQyEk-DJR77z7S3xi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af162a236d241be8893302c8b3de5c158aeca18/pkg/sql/show_test.go#L735)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what if there are two comments?
</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
@rafiss PTAL

**Review by rafiss — APPROVED** [review]
lgtm! rebase to fix the TestComposeGSSPython failure

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86968#-:-NFPL9rO-0PhwPki1Be1:bzhtudk)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
TFTR! I will just bors it I think that should get past the flake right?

bors r+

**Comment by jordanlewis** [comment]
Unrelated flake

bors r+

**Pull request merged**
