### PR TITLE
plpgsql: add support for sql exec and INTO statements

### LINKED ISSUE #105252: plpgsql: implement SELECT INTO variable
This issue tracks adding `SELECT INTO` support for PLpgSQL. `SELECT ... INTO <var>` allows a variable to be assigned the result of evaluating a SQL statement that returns one row: https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-ASSIGNMENT

This should be relatively simple, since variable assignments like `var := expr` already assign the result of evaluating a SQL expression to a variable.

Epic: CRDB-799

Jira issue: CRDB-28941

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: add parser support for sql exec statements

This patch adds support in the parser for directly executing SQL statements
in a PLpgSQL routine. Note that postgres disallows this syntax for statements
that return rows, but we allow it because execution can handle row-returning
statements and it allows running statements like `IMPORT`, which returns rows.

SQL statements with an `INTO` clause are also supported; `INTO` allows for
the result of a SQL statement to be assigned to one or more PLpgSQL
variables. It cannot be used with a statement that does not return rows.

Example:
```
CREATE FUNCTION f() RETURNS INT AS $$
  DECLARE
    i INT;
  BEGIN
    SET testing_optimizer_disable_rule_probability = 0;
    INSERT INTO xy VALUES (1, 2);
    SELECT 1 + 1;
    SELECT 100 INTO i;
    SELECT max(x) INTO i FROM xy;
    INSERT INTO xy VALUES (10, 10) RETURNING x INTO i;
    RETURN i;
  END
$$ LANGUAGE PLpgSQL;
```

Informs #105252

Release note: None

#### plpgsql: raise end-of-function error during runtime

This commit moves the end-of-function error from compile-time to
run-time, using a RAISE statement to throw the error. This more
closely mirrors postgres behavior, where it's possible to define
a function that is not guaranteed to terminate. Example:
```
CREATE OR REPLACE FUNCTION f(a INT, b INT) RETURNS INT AS $$
  BEGIN
    IF a < b THEN
      RETURN a;
    END IF;
  END
$$ LANGUAGE PLpgSQL;

root@localhost:26257/defaultdb> SELECT f(1, 2);
  f
-----
  1
(1 row)

Time: 25ms total (execution 24ms / network 0ms)

root@localhost:26257/defaultdb> SELECT f(2, 1);
ERROR: control reached end of function without RETURN
SQLSTATE: 2F005
```

This commit also refactors some of the PLpgSQL routine-building logic
to simplify building multiple body statements.

Epic: CRDB-799

Release note: None

#### plpgsql: add support for sql exec and INTO statements

This patch adds execution support for executing SQL statements within
PLpgSQL routines, both for the case when the result is discarded and when
`INTO` syntax is used to assign the result to a set of target variables.
The former case is handled by building the SQL statement into one of the
first body statements of a routine; this captures the result-discarding
behavior, but ensures any side effects still occur. The latter case is
handled by aliasing the output columns of the SQL statement to the target
variable names; this is done in the last body statement of the routine,
since the result of the query is needed.

Examples:
```
CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$
  BEGIN
    INSERT INTO xy VALUES (1000, 1000);
    DELETE FROM xy WHERE x = 1000;
    RETURN 0;
  END
$$ LANGUAGE PLpgSQL;

CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$
  DECLARE
    i INT;
  BEGIN
    SELECT x INTO i FROM xy ORDER BY x DESC;
    RETURN i;
  END
$$ LANGUAGE PLpgSQL;
```

Fixes #105252

Release note (sql change): Added support for executing SQL statements
directly within PLpgSQL routines. Note that this currently only applies
to the subset of statements that can be executed within SQL UDFs, so
`CREATE TABLE` is not supported, for example. INTO syntax is also
supported, e.g. `SELECT * INTO a, b FROM xy;`.

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]
Parser change looks fantastic.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 1213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-NarXmtL-ljohAECp3cm:-NarXmtL-ljohAECp3cn:b-cwj9dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef17a056a2a934085cddac1abc22013a96ddf1c8/pkg/sql/plpgsql/parser/plpgsql.y#L1213)):*
> ```Yacc
> stmt_execsql_start:
>   IMPORT
> | INSERT
> ```

Should we also support UPDATE, UPSERT, and DELETE here?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1055 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-NbGXE-J-pTfM8u69rEO:-NbGXE-J-pTfM8u69rEP:b3w3iws) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c520751b454ee1448dd355f2de30ed241a9b22c/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1055)):*
> ```
> 
> statement ok
> INSERT INTO xy VALUES (1, 2), (3, 4);
> ```

Would be interesting to test `SELECT f()` again after this insert.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-NbG_Lwy3KSod4i72S01:-NbG_Lwy3KSod4i72S02:b-o2dlyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c520751b454ee1448dd355f2de30ed241a9b22c/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1159)):*
> ```
> 104  204
> 
> # If there are more INTO targets than output columns, the left over variables
> ```

Could you add the following tests?
*  A test with >1 target columns that is successful?
* Using a declared variable inside the SQL queries (e.g., inside a WHERE clause)
* The above, but also assign into the same variable in the same statement, e.g.:
```
CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$                                                              
DECLARE  
  i INT;                                                                                                               
BEGIN                                                                                                                    
  SELECT x INTO i FROM xy ORDER BY x DESC;  
  SELECT x INTO i FROM xy WHERE y = i;                                                                             
  RETURN i;                                                                                                            
END                                                                                                                  
$$ LANGUAGE PLpgSQL;
```

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 1213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-NarXmtL-ljohAECp3cm:-NbMCqh655ajrU6295pw:b-lilahz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef17a056a2a934085cddac1abc22013a96ddf1c8/pkg/sql/plpgsql/parser/plpgsql.y#L1213)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should we also support UPDATE, UPSERT, and DELETE here?
</blockquote></details>

We don't have to, I think because those aren't considered keywords in the PLpgSQL grammar. Those can still be parsed, but they don't need to be special-cased.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1055 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-NbGXE-J-pTfM8u69rEO:-NbMG97d5ekEGUytbgqW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c520751b454ee1448dd355f2de30ed241a9b22c/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1055)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Would be interesting to test `SELECT f()` again after this insert.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-NbG_Lwy3KSod4i72S01:-NbR6rBX61WKT35V828f:b-pov76i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c520751b454ee1448dd355f2de30ed241a9b22c/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1159)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you add the following tests?
*  A test with >1 target columns that is successful?
* Using a declared variable inside the SQL queries (e.g., inside a WHERE clause)
* The above, but also assign into the same variable in the same statement, e.g.:
```
CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$                                                              
DECLARE  
  i INT;                                                                                                               
BEGIN                                                                                                                    
  SELECT x INTO i FROM xy ORDER BY x DESC;  
  SELECT x INTO i FROM xy WHERE y = i;                                                                             
  RETURN i;                                                                                                            
END                                                                                                                  
$$ LANGUAGE PLpgSQL;
```
</blockquote></details>

Great ideas. You also gave me the idea to assign to the same variable twice, which the logic couldn't handle. I've just made that an unimplemented error since it doesn't seem worth worrying about right now. I also added some optbuilder tests.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-:-Nc45R5dAGJ1NStO8AFe:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 1213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-NarXmtL-ljohAECp3cm:-Nc44S0L7uYXVRmjih5V:b-54avio) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef17a056a2a934085cddac1abc22013a96ddf1c8/pkg/sql/plpgsql/parser/plpgsql.y#L1213)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

We don't have to, I think because those aren't considered keywords in the PLpgSQL grammar. Those can still be parsed, but they don't need to be special-cased.
</blockquote></details>

Ok, thanks.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-NbG_Lwy3KSod4i72S01:-Nc459UrE-THH6S4sk-R:bkkra11) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c520751b454ee1448dd355f2de30ed241a9b22c/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1159)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Great ideas. You also gave me the idea to assign to the same variable twice, which the logic couldn't handle. I've just made that an unimplemented error since it doesn't seem worth worrying about right now. I also added some optbuilder tests.
</blockquote></details>

:thumbsup: Thanks!

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Review by mgartner — COMMENTED** [review]
Finally got around to taking a peek at this. Great work!

> Reviewed 11 of 15 files at r1, 1 of 6 files at r4, 8 of 8 files at r7, 6 of 6 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-:-Nd1Y5Vj8RIrjQJfCWng:bnd9p2q)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 447 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/107920#-Nd1X7qvA2qbz-wiZrSn:-Nd1X7qvA2qbz-wiZrSo:bksedo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0034d185217c3f9cb73c508dd09f50cc2e9b24b/pkg/sql/opt/optbuilder/plpgsql.go#L447)):*
> ```Go
> 						panic(unimplemented.New(
> 							"duplicate INTO target",
> 							"assigning to a variable more than once in the same INTO statement is not supported",
> ```

Interestingly, Postgres seems to support this:

```
marcus=# CREATE FUNCTION f() RETURNS INT LANGUAGE plpgsql AS $$
  DECLARE
    i INT;
    j INT;
  BEGIN
    SELECT 1, 2 INTO i, i;
    RETURN i + i;
  end;
$$;
CREATE FUNCTION

marcus=# SELECT f();
 f
---
 4
(1 row)
```

This is probably a fine limitation though, since it's likely a bug in the PLpgSQL program.

**Pull request merged**
