### PR TITLE
opt: add stats version of tpce tests

### PR DESCRIPTION
**Pull request by DrewKimball**
This PR adds a TPC-E stats test fixture with stats taken after running
TPC-E with 5000 customers on a 3-node cluster. This PR also adds
a version of the TPC-E opt plan tests that uses the stats.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Looks like there are duplicate stats for the same columns in the file (with different "created at" times). We should only keep the latest one.

[nit] maybe append _c5000 to the stats file in case we'll have other versions (like we have w10 and w100 for tpcc).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-:-MF7Ac-qDrTg9D70JEQ_:b6wkr6s)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rytaft — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53069)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/xform/testdata/external/tpce, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFBa7LT6-Ym7nI8vV0w:-MFBa7LT6-Ym7nI8vV0x:bnmshvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L4)):*
> ```
> ----
> 
> import file=tpce_stats_c5000
> ```

Did any plans change with the stats?
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFBXeB-EbQfQ23IIHSP:-MFBXeB03-glx6cm3Z1V:b-rru702) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L843)):*
> ```
> # Q1 Version 2
> #
> # This is a manually optimized version of Q1.
> ```

Is this still faster than the automatically optimized version? Any ideas about how we could improve the optimizer to get this plan?
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 3223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFB_MZ-0sASwbvuzjsk:-MFB_MZ05E_ahoeFhl2_:b-z46h7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L3223)):*
> ```
> # Q1 Version 2
> #
> # This is a manually optimized version of Q1
> ```

Same question as above
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 3722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFB_qgz3ZN7HatwjK9l:-MFB_qh-3u2o2YbwUb0Q:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L3722)):*
> ```
> # Q10 Version 2
> #
> # This is a manually optimized version of Q10.
> ```

ditto
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 3725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFB_oKR6yanXcoutQLx:-MFB_oKS4i-3xm-BPLXZ:b65451q) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L3725)):*
> ```
> #
> opt
>            SELECT t_id,
> ```

formatting is kind of weird here -- why is it indented so far?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53069)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rytaft)

___
*[pkg/sql/opt/xform/testdata/external/tpce, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFBa7LT6-Ym7nI8vV0w:-MFC78Es6mGGU0LezvL4:bgaa7fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L4)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Did any plans change with the stats?
</blockquote></details>

Yes, a lot of the more complex queries changed. Are there any in particular you want to the diffs for?
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFBXeB-EbQfQ23IIHSP:-MFC7Oi9CaU6Yd2hI2LS:b-ajxpuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L843)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this still faster than the automatically optimized version? Any ideas about how we could improve the optimizer to get this plan?
</blockquote></details>

I actually forgot to run these against one another, so I'm not sure. Another problem is that the optimality of these plans may be different depending on the number of customers used, so if I did run them my results might only hold for ~5000 customers. I'm thinking it may be better to simply remove version 2 from this with-stats version.
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 3223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFB_MZ-0sASwbvuzjsk:-MFC89_SEi9CmammQry2:b-diivp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L3223)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Same question as above
</blockquote></details>

Similar deal. Do you think I should remove these second versions?
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 3725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFB_oKR6yanXcoutQLx:-MFC8W1k4yVG6R9M2LxB:buq8t41) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L3725)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

formatting is kind of weird here -- why is it indented so far?
</blockquote></details>

I'm not sure, that's odd. I'll change it. Done.

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53069)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/xform/testdata/external/tpce, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFBa7LT6-Ym7nI8vV0w:-MFC_gtA9QCZZjT17uSu:bikyj6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L4)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Yes, a lot of the more complex queries changed. Are there any in particular you want to the diffs for?
</blockquote></details>

Nah just curious
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFBXeB-EbQfQ23IIHSP:-MFC_jTK69ukxU-QGyi_:b-lqnu6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L843)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I actually forgot to run these against one another, so I'm not sure. Another problem is that the optimality of these plans may be different depending on the number of customers used, so if I did run them my results might only hold for ~5000 customers. I'm thinking it may be better to simply remove version 2 from this with-stats version.
</blockquote></details>

How did you construct the manually optimized plan? Unless you have a reason to believe that it's the optimal plan in most cases, probably not worth keeping it
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 3223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFB_MZ-0sASwbvuzjsk:-MFCa-yeDg1P5N633fRn:b1faaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L3223)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Similar deal. Do you think I should remove these second versions?
</blockquote></details>

Yea, unless you think it's probably better than v1
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 3725 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFB_oKR6yanXcoutQLx:-MFCaDMU-MHFHoHIqAUK:bcopkjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L3725)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I'm not sure, that's odd. I'll change it. Done.
</blockquote></details>

Looks like all the v2 plans actually have a weird whitespace issue. Although no worries if you're going to remove them anyway

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53069)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rytaft)

___
*[pkg/sql/opt/xform/testdata/external/tpce, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFBXeB-EbQfQ23IIHSP:-MFCtDtW2tks9XTqOe_A:b-2c30ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L843)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

How did you construct the manually optimized plan? Unless you have a reason to believe that it's the optimal plan in most cases, probably not worth keeping it
</blockquote></details>

I just stole it from Nathan.
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 3223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-MFB_MZ-0sASwbvuzjsk:-MFCtHMK5xDDcLno0tiv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6259287681a74f9bb0b35075d5f94e6631d268bf/pkg/sql/opt/xform/testdata/external/tpce#L3223)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea, unless you think it's probably better than v1
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53069#-:-MFDTBZ7-3bxZc4Hd0iT:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by DrewKimball** [comment]
TFTR!

**Pull request merged**
