### PR TITLE
ui/next: move tests to karma

### PR DESCRIPTION
**Pull request by tamird**
This paves the way for (testable) protobuf-over-HTTP.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7165)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Totally unrelated, but looks like we could also auto-generate UI screenshots using PhantomJS?

**Comment by tamird** [comment]
Yep, that's doable. Next friday.

For now this is blocked on the NodeJS version we're using in the builder,
which I'll have to bump.

On Sat, Jun 11, 2016 at 1:12 AM, Tobias Schottdorf <notifications@github.com

**Comment by tamird** [comment]
At long last, this is green.

**Comment by tschottdorf** [comment]
:lgtm: (science dog)

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> At long last, this is green.
</details>


---

Reviewed 9 of 9 files at r1, 11 of 11 files at r2, 1 of 1 files at r3, 13 of 13 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7165#-:-KK0T0RzxxXyTexdj0rc:349035458)*

**Comment by mrtracy** [comment]
I am in disbelief that it works, but it does. What is even compiling the typescript in the test run?  The "jspm" framework?

Regardless, LGTM.

Before you commit, could you install the latest version of pug instead of jade?

**Comment by tamird** [comment]
Yeah all the loading is done by SystemJS, just like in the browser.

**Pull request merged**
