### PR TITLE
sql: support expression evaluation on ENUM types

### PR DESCRIPTION
**Pull request by rohany**
This PR enables expressions on ENUM types. It allows for comparisons
and casts to and from ENUM values.

This is accomplished by loading type metadata into the types.T
object upon name resolution, and then use that information during
evaluation.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Depends on #48086. Please take a look at the second commit! The first commit might go through some changes as it is still under review.

cc @ajwerner @lucy-zhang

**Comment by rohany** [comment]
This is ready for a review.

**Review by jordanlewis — COMMENTED** [review]
Nice!

We should add support for the related builtins too, there's just  4 and they're all easy. I'm cool if you do it in this PR or a different one, they should be trivial. https://www.postgresql.org/docs/12/functions-enum.html

Also we need to add pg_enum, but I guess that can't come yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-:-M6hBlVs4hBDxrjo202F:bwbjij2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @otan, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/enums, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6h99DcDK811cxoc7P1:-M6h99DcDK811cxoc7P2:btl4hg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/logictest/testdata/logic_test/enums#L42)):*
> ```
> 
> query TTT
> SELECT 'hello'::greeting, 'howdy'::greeting, 'hi'::greeting
> ```

So cool! User defined types :pogchamp:

Hmm, can you test the `'hello'::public.greeting` format here and make sure you can't do like `pg_catalog.greeting`?
___
*[pkg/sql/logictest/testdata/logic_test/enums, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6h9MmaC-iAivhHrtwq:-M6h9Mmb2YxTVpdLgqT-:b-3xv8af) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/logictest/testdata/logic_test/enums#L93)):*
> ```
> 
> statement error pq: value type greeting cannot be used for table columns
> CREATE TABLE bad (x greeting)
> ```

Can you test an enum with:

1. duplicate names (should fail?)
2. duplicate names with different capitalization (should work? or fail?)
3. empty name?

Something like `CREATE TYPE int AS ENUM('fail')` should fail

Also, can you test ::: type annotations?

We also need to test that this works across distsql. Normally the eval tests wil automatically do this. WIthout them, I think you need something like `select 'hello'::greeting from t` where `t` has some rows, and do it in the fakedist configuration which is enabled by default.
___
*[pkg/sql/pgwire/types.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hADeyBibTnrPzs9Pw:-M6hADeyBibTnrPzs9Px:b1w20rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/pgwire/types.go#L181)):*
> ```Go
> 		b.writeLengthPrefixedDatum(v)
> 
> 	case *tree.DEnum:
> ```

Is there no binary serialization for enums?
___
*[pkg/sql/pgwire/types.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hAFkLEXaSkUoUEhfp:-M6hAFkLEXaSkUoUEhfq:bke3ftu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/pgwire/types.go#L183)):*
> ```Go
> 	case *tree.DEnum:
> 		// Enums are serialized with their logical representation.
> 		b.writeLengthPrefixedString(v.LogicalRep)
> ```

Can you add a pgwire datadriven test for this serialization and check it against postgres?
___
*[pkg/sql/sem/tree/datum.go, line 3746 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hAKWwATh6mAErvuZw:-M6hAKWwATh6mAErvuZx:bqf15z4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/sem/tree/datum.go#L3746)):*
> ```Go
> type DEnum struct {
> 	EnumTyp     *types.T
> 	PhysicalRep []byte
> ```

Comments on these please!
___
*[pkg/sql/sem/tree/expr.go, line 1572 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hAnkt3XzFbtSF-_fl:-M6hAnkt3XzFbtSF-_fm:b51zxcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/sem/tree/expr.go#L1572)):*
> ```Go
> 		return ret
> 	case types.EnumFamily:
> 		// TODO (rohany): we need a copy like the array case??
> ```

I don't think so, and that copy seems super bogus. I think you could delete it. The only caller of this thing throws the results away immediately, and nobody mutates arrayCastTypes...
___
*[pkg/sql/sqlbase/structured.proto, line 1018 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hB2HcECTHZJapkS_1:-M6hB2HcECTHZJapkS_2:b-pi9877) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/sqlbase/structured.proto#L1018)):*
> ```protobuf
> 
>   // The fields below are used only when this type is an ENUM type.
>   // TODO (rohany): Leaving this empty until we actually store enum values.
> ```

remove todo

**Comment by rohany** [comment]
> We should add support for the related builtins too, there's just 4 and they're all easy. I'm cool if you do it in this PR or a different one, they should be trivial.

Yeah, I'm tracking these in #48358

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48455)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @otan)

___
*[pkg/sql/logictest/testdata/logic_test/enums, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6h99DcDK811cxoc7P1:-M6hDAS85-GlK3SsnBd3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/logictest/testdata/logic_test/enums#L42)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

So cool! User defined types :pogchamp:

Hmm, can you test the `'hello'::public.greeting` format here and make sure you can't do like `pg_catalog.greeting`?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/enums, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6h9MmaC-iAivhHrtwq:-M6hDB0G24hVejH3Hy41:b-icl9th) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/logictest/testdata/logic_test/enums#L93)):*
Just added the test with duplicate names.
duplicate names with different capitalization will work (checked with pg)

> Something like CREATE TYPE int AS ENUM('fail') should fail

Why would this fail? This creates a type "int" in the public schema, which is different from the "int" in "pg_catalog".

added annotation tests.

I think this already is testing across distsql (i had to add some encodings for this to pass distsql). Either way, I'm not supporting inserting into tables in this PR.
___
*[pkg/sql/pgwire/types.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hADeyBibTnrPzs9Pw:-M6hETYa5n3LgbcolgVC:b-clqxkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/pgwire/types.go#L181)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is there no binary serialization for enums?
</blockquote></details>

What do you mean? Our binary format is for internal use only.
___
*[pkg/sql/pgwire/types.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hAFkLEXaSkUoUEhfp:-M6hFysD2Ak7uQmQilj-:b-6tldyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/pgwire/types.go#L183)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you add a pgwire datadriven test for this serialization and check it against postgres?
</blockquote></details>

I'm unfamiliar with the pgwire testing. I see some datadriven tests in pkg/sql/pgwire/testdata/pgtest/, is that what you mean? How do I check it against postgres?
___
*[pkg/sql/sem/tree/datum.go, line 3746 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hAKWwATh6mAErvuZw:-M6hEqfP5obgL4NKhljo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/sem/tree/datum.go#L3746)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Comments on these please!
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/expr.go, line 1572 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hAnkt3XzFbtSF-_fl:-M6hFItQ2kndiGy7IraV:b-o9rqz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/sem/tree/expr.go#L1572)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't think so, and that copy seems super bogus. I think you could delete it. The only caller of this thing throws the results away immediately, and nobody mutates arrayCastTypes...
</blockquote></details>

done -- looking at the history there used to be some sneakiness going on with including the argument type in the returned array.
___
*[pkg/sql/sqlbase/structured.proto, line 1018 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hB2HcECTHZJapkS_1:-M6hFfUa7V5_n8Y4oDhA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/sqlbase/structured.proto#L1018)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

remove todo
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48455)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @otan, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/enums, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6h9MmaC-iAivhHrtwq:-M6hK-rN2rGe_7DJ2vpq:bw621ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/logictest/testdata/logic_test/enums#L93)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Just added the test with duplicate names.
duplicate names with different capitalization will work (checked with pg)

> Something like CREATE TYPE int AS ENUM('fail') should fail

Why would this fail? This creates a type "int" in the public schema, which is different from the "int" in "pg_catalog".

added annotation tests.

I think this already is testing across distsql (i had to add some encodings for this to pass distsql). Either way, I'm not supporting inserting into tables in this PR.
</blockquote></details>

Oh wow, that makes sense... scary 

You don't have to test insert into tables to test this thing I'm talking about. Make a table with some normal columns. Then select an enum literal "from" the table. Like

```
create table t (a int primary key); insert into t values(1)
select some_constant_enum from t
```
___
*[pkg/sql/pgwire/types.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hADeyBibTnrPzs9Pw:-M6hKhen4PQ8QIFCBHDf:b-v9cqwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/pgwire/types.go#L181)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

What do you mean? Our binary format is for internal use only.
</blockquote></details>

That's not true. Postgres supports 2 serialization types, binary and text. You can pick your protocol when you connect to the server. We also support this.
___
*[pkg/sql/pgwire/types.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hAFkLEXaSkUoUEhfp:-M6hKpM70kR_H6ieZmS-:bufww1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/pgwire/types.go#L183)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I'm unfamiliar with the pgwire testing. I see some datadriven tests in pkg/sql/pgwire/testdata/pgtest/, is that what you mean? How do I check it against postgres?
</blockquote></details>

Yes, that's what I mean. See thread here: https://cockroachlabs.slack.com/archives/C04U1BTF8/p1588627833369200?thread_ts=1588626290.366800&cid=C04U1BTF8

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48455)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @otan)

___
*[pkg/sql/logictest/testdata/logic_test/enums, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6h9MmaC-iAivhHrtwq:-M6jR8DL3Lwr1hKAv0Gg:b7emkgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/logictest/testdata/logic_test/enums#L93)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Oh wow, that makes sense... scary 

You don't have to test insert into tables to test this thing I'm talking about. Make a table with some normal columns. Then select an enum literal "from" the table. Like

```
create table t (a int primary key); insert into t values(1)
select some_constant_enum from t
```
</blockquote></details>

That isn't gonna work yet -- for that to work we need to be able to do the resolution of enums on remote nodes and such, which is work of a future PR.
___
*[pkg/sql/pgwire/types.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hADeyBibTnrPzs9Pw:-M6jWrPoE77Fu4Og5gOr:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/pgwire/types.go#L181)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

That's not true. Postgres supports 2 serialization types, binary and text. You can pick your protocol when you connect to the server. We also support this.
</blockquote></details>

done
___
*[pkg/sql/pgwire/types.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6hAFkLEXaSkUoUEhfp:-M6jWqNFEv7gm4lvtKJz:b-7dfc1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb80e0a85b5ec5d17cb37bb4284b113cc6758f96/pkg/sql/pgwire/types.go#L183)):*
> That's not true. Postgres supports 2 serialization types, binary and text. You can pick your protocol when you connect to the server. We also support this.
done

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48455)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/sql/types/types.go, line 2116 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6keW-94DelbHHwsLld:-M6keW-A41FYxm06uLH5:b-yj9fz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/17f35fd16214e44b7e7dbda1847d6c1207831006/pkg/sql/types/types.go#L2116)):*
> ```Go
> 		}
> 	}
> 	panic("could not match physical enum representation")
> ```

Can we return an error here instead of panicking? Similar to the function below.

**Comment by rohany** [comment]
> Can we return an error here instead of panicking? Similar to the function below.

It would be real pain to plumb errors through all of the datum functions -- I'd rather not. Also, not matching the physical representation is really a "panic" situation, because we've found an enum we don't know how to decode.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48455)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/sql/types/types.go, line 2116 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/48455#-M6keW-94DelbHHwsLld:-M6ljS1qAFvMFAnprQRD:bv1rpwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/17f35fd16214e44b7e7dbda1847d6c1207831006/pkg/sql/types/types.go#L2116)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can we return an error here instead of panicking? Similar to the function below.
</blockquote></details>

Fair enough. Can we then include some more details? Imagine we get this in Sentry - what are we going to do to debug it?

**Comment by rohany** [comment]
Thats a good point. I'll update it to dump the enum metadata + requested byte slice.

**Pull request merged**
