### PR TITLE
gossip: fix data race in clientStatus

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7836)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/gossip.go, line 365 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836#-KMeOcxvInMTgyaahf0o:-KMeOcxw5POFOY1g8hLT:1653483067) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd4ebfb4ea60726cce92af3a4523901e475e0ecf/gossip/gossip.go#L365)):*
> ```Go
> 	var buf bytes.Buffer
> 
> 	g.mu.Lock()
> ```

What was the race here? Could you add the response to the commit message?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/gossip.go, line 365 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836#-KMeOcxvInMTgyaahf0o:-KMePFPLMLaxXEvY7aVm:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd4ebfb4ea60726cce92af3a4523901e475e0ecf/gossip/gossip.go#L365)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> What was the race here? Could you add the response to the commit message?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/gossip.go, line 365 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836#-KMeOcxvInMTgyaahf0o:-KMePobklpjNuEvJhdS8:1854938681) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd4ebfb4ea60726cce92af3a4523901e475e0ecf/gossip/gossip.go#L365)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Done.
</details>
Oh wow, that's awkward.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836#-:-KMePqQb5te3QtxFnivC:1417088721)*

**Comment by tschottdorf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[gossip/gossip.go, line 139 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836#-KMePtLYaumnnXJjXSsY:-KMePtLYaumnnXJjXSsZ:1116736000) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd4ebfb4ea60726cce92af3a4523901e475e0ecf/gossip/gossip.go#L139)):*
> ```Go
> 	bootstrapInfo BootstrapInfo       // BootstrapInfo proto for persistent storage
> 	bootstrapping map[string]struct{} // Set of active bootstrap clients
> 	clientsMu     struct {
> ```

Add a comment here about that awkwardness.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[gossip/gossip.go, line 139 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836#-KMePtLYaumnnXJjXSsY:-KMeSh3E1yeJw0P_tUz5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd4ebfb4ea60726cce92af3a4523901e475e0ecf/gossip/gossip.go#L139)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Add a comment here about that awkwardness.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836#-:-KMeWOiWrW8n6eAh77ba:1417088721)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[gossip/gossip.go, line 139 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836#-KMePtLYaumnnXJjXSsY:-KMf0yiaIj6SwqR9txg_:406603414) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd4ebfb4ea60726cce92af3a4523901e475e0ecf/gossip/gossip.go#L139)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Done.
</details>
Lovely. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7836)*

**Pull request merged**
