### PR TITLE
sql: add information about which KV nodes served read requests

### LINKED ISSUE #91774: Add the KV node id to the TableReader process in the distsql.html file
**Is your feature request related to a problem? Please describe.**
A statement bundle contains the distsql.html file.  In this file are sometimes TableReader processes.

Currently, these sections don't show the node that was consulted for KV reads giving the false impression that another node was not involved in the entire execution of the query.

**Describe the solution you'd like**
Add the id of the node that was consulted in the KV look-up.

**Describe alternatives you've considered**
Alternatives include finding this information in the trace text files but they are more difficult to consult.

Jira issue: CRDB-21420

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR exposes information in EXPLAIN ANALYZE output about which KV nodes participated in evaluating read requests.

See each commit for details.

Fixes: #91774.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
Internal changes :lgtm:

> Reviewed 6 of 6 files at r1, 35 of 35 files at r2, 16 of 16 files at r3, 51 of 51 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124681#-:-Nz1TVTi1J_PLkDy0qAy:b-k3io3d)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124681#-Nz0UdYO49kVvILOaXWH):*
It seems like this change will mean we won't be able to show which nodes were involved for pre-existing statement statistics in the db console, is that right?

___
*[`pkg/sql/execstats/stats.go` line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124681#-Nz1Sg3I2wKsq_pWD6b_:-Nz1Sg3I2wKsq_pWD6ba:b-j32r3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b259077e70599fa97cf1240ed1b5249f45430469/pkg/sql/execstats/stats.go#L98)):*
> ```Go
> 	l.mu.ScanStats.numReverseScans += ss.NumReverseScans
> 	if idx, found := slices.BinarySearch(l.mu.ScanStats.nodeIDs, int32(ss.NodeID)); !found {
> 		l.mu.ScanStats.nodeIDs = slices.Insert(l.mu.ScanStats.nodeIDs, idx, int32(ss.NodeID))
> ```

[nit] Think it's worth adding something like `util.InsertUnique` for cases like this?
___
*[`pkg/sql/execstats/traceanalyzer.go` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124681#-Nz0PjoED2bivRZ1fqAi:-Nz0PjoED2bivRZ1fqAj:b-c9jgkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ba82391a107237613840a5c39c931da601fb35/pkg/sql/execstats/traceanalyzer.go#L326)):*
> ```Go
> 	}
> 	// Finalize max memory and max disk usages.
> 	for _, maxMemUsage := range maxMemoryUsageGroupedByNode {
> ```

[nit] Worth aggregating these in the loop above as well?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124681)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`-- commits` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124681#-Nz0UdYO49kVvILOaXWH):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

It seems like this change will mean we won't be able to show which nodes were involved for pre-existing statement statistics in the db console, is that right?

</blockquote></details>

Yes. I just set up a mixed version cluster to confirm this behavior and observed the following: before this patch the encoded JSON has `nodes` field which is what older binaries will attempt to access when displaying `Nodes` attribute on `SQL Activity` pages, after this patch we have `sqlInstanceIds` attribute which newer binaries will attempt to access. This patch will make it so that all existing statement statistics will have empty `Nodes` attribute on servers running newer binary (it'll still be visible on older binaries), and eventually the accumulated JSON will be updated to have `sqlInstanceIds` field. This all because of the `Nodes []int64 -> SQLInstanceIDs []int32` change in `appstatspb.StatementStatistics` proto. I couldn't quite find where the change to `insights.Statement` would show up (I was using TPCH workload).
___
*[`pkg/sql/execstats/stats.go` line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124681#-Nz1Sg3I2wKsq_pWD6b_:-Nz572Ye--57g0NNxGQU:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b259077e70599fa97cf1240ed1b5249f45430469/pkg/sql/execstats/stats.go#L98)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Think it's worth adding something like `util.InsertUnique` for cases like this?
</blockquote></details>

Good point, done.
___
*[`pkg/sql/execstats/traceanalyzer.go` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124681#-Nz0PjoED2bivRZ1fqAi:-Nz58EyN3fR7f-GSBQQV:br209yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ba82391a107237613840a5c39c931da601fb35/pkg/sql/execstats/traceanalyzer.go#L326)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Worth aggregating these in the loop above as well?
</blockquote></details>

Indeed, I dunno why I didn't realize that these max usages are also easily replaceable. Done.

**Comment by yuzefovich** [comment]
I decided to pull out the commit about DB Console changes into a separate PR to make things easier (both for reviewing and possibly backporting to 24.1), so now this PR (mostly) contains DB changes only. Will merge on the green CI.

TFTR Drew!

**Comment by yuzefovich** [comment]
I actually pulled out all changes to DB Console for `kv_node_ids` too, to be reviewed by Observability team separately.

bors r+

**Comment by yuzefovich** [comment]
Oh, actually, some changes to DB Console are required, I'll add them back.

**Comment by yuzefovich** [comment]
Rebased on top of latest master.

**Pull request merged**
