### PR TITLE
opt: use computed columns to improve FDs and remove uniqueness checks

### LINKED ISSUE #57720: opt: eliminate uniqueness checks for REGIONAL BY ROW tables with computed region
As described in #57682, we will enable customers to specify a computed column expression for the region based on other columns in their schema. If the computed column expression depends only on the columns in the logical primary key, the optimizer should be able to eliminate uniqueness checks on the primary key when rows are inserted or updated. 

For example, consider the example of TPC-C. The schema might be specified as `CREATE TABLE warehouse (w_id INT PRIMARY KEY, ...) REGIONAL BY ROW AS (CASE WHEN w_id < 5 THEN 'us-east1' ELSE 'us-west2' END)`. As described in #57718, the `PRIMARY KEY` designation will be syntactic sugar for `PRIMARY KEY (region, w_id), UNIQUE WITHOUT INDEX (w_id)`. 

Normally, the optimizer would need to plan uniqueness checks on `w_id` any time a row is inserted. But since the `region` column is functionally dependent on `w_id`, the unique index on `(region, w_id)` (i.e., the primary index) should be sufficient to guarantee uniqueness. Therefore, the uniqueness check can be eliminated. This issue covers the work to use functional dependencies in the optimizer to eliminate unnecessary uniqueness checks.

### PR DESCRIPTION
**Pull request by rytaft**
**opt: use computed columns to build functional dependencies**

This commit updates `MakeTableFuncDep` so that it adds equivalencies
or synthesized columns to the table FDs for each of the computed
columns available in the metadata. This will be necessary to support
removing uniqueness checks in some cases in a future commit.

Release justification: This commit is a low risk, high benefit change
to existing functionality.

Release note (performance improvement): The optimizer now infers
additional functional dependencies based on computed columns in tables.
This may enable additional optimizations and lead to better query plans.

**opt: remove uniqueness checks when uniqueness inferred through FDs**

This commit removes uniqueness checks for columns that can be
inferred to be unique through functional dependencies. This is
relevant in particular for `REGIONAL BY ROW` tables with a computed
region column that depends on the primary key. In this case,
uniqueness checks are never needed on the primary key, since
uniqueness is already guaranteed by the primary index.

Fixes #57720

Release justification: This commit is a low-risk, high benefit
update to new functionality.

Release note (performance improvement): Removed uniqueness checks
on the primary key for REGIONAL BY ROW tables with a computed
region column that is a function of the primary key columns.
Uniqueness checks are not necessary in this case since uniqueness
can be suitably guaranteed by the primary index. Removing these
checks improves performance of INSERT, UPDATE, and UPSERT
statements.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice!

> Reviewed 12 of 12 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-:-MULqjB4ETio76u_y7pO:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/memo/testdata/logprops/scan, line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-MULmafS7czB4GzcjiXW:-MULmafS7czB4GzcjiXX:bh0dssr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ab9adb30aac0fcf837e2e6d2e9449d26f873b8a/pkg/sql/opt/memo/testdata/logprops/scan#L401)):*
> ```
>       └── interesting orderings: (+1) (+3,+1)
> 
> # Test FDs for computed columns.
> ```

[nit] explain what we expect: s=c_s, d=c_d, i->c_i_expr; and not d->c_d_expr
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-MULp9FD6PXOQrGOcaeT:-MULp9FEB4ay3ADu7fjr:b4x80s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/272cf445b3e435a705d0847ee237c273d8fcae21/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L222)):*
> ```Go
> 	// Check that the columns in the unique constraint aren't already known to
> 	// form a lax key. This can happen if there are computed columns that are
> 	// known to form a lax key that depend on these columns.
> ```

I found the last sentence very confusing. I'd say - this can happen if there is a unique index on a superset of these columns, where all other columns are computed columns that depend only on our columns. This is especially important for multi-region when the region column is computed.

**Review by mgartner — APPROVED** [review]
:lgtm: :100: 

> Reviewed 12 of 12 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-:-MUM37H-BrN1u7qMx6Tp:bbie1ho)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 1075 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-MUM0z8c1ov5MuoaMy9V:-MUM0z8c1ov5MuoaMy9W:b-11w5eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/272cf445b3e435a705d0847ee237c273d8fcae21/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L1075)):*
> ```
>                       label: buffer 1
> 
> # TODO(rytaft): Update this error message to remove crdb_region (see #59504).
> ```

[nit] you can make this a `TODO(mgartner)` - I'll be working on #59504. feel free to leave as-is too
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-MULp9FD6PXOQrGOcaeT:-MUM2DBO-_5NS6Dt5Qez:b-rabiy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/272cf445b3e435a705d0847ee237c273d8fcae21/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L222)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I found the last sentence very confusing. I'd say - this can happen if there is a unique index on a superset of these columns, where all other columns are computed columns that depend only on our columns. This is especially important for multi-region when the region column is computed.
</blockquote></details>

:woozy_face: maybe an example would help too?

**Review by rytaft — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-:-MUOLYZ19_9eA2Zwayfu:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 1075 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-MUM0z8c1ov5MuoaMy9V:-MUOFtrZAXXuYnJK6BRk:b7w8d47) ([raw file](https://github.com/cockroachdb/cockroach/blob/272cf445b3e435a705d0847ee237c273d8fcae21/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L1075)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] you can make this a `TODO(mgartner)` - I'll be working on #59504. feel free to leave as-is too
</blockquote></details>

Great - thanks! Done. 
___
*[pkg/sql/opt/memo/testdata/logprops/scan, line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-MULmafS7czB4GzcjiXW:-MUOHfWuBSHZopItpA86:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ab9adb30aac0fcf837e2e6d2e9449d26f873b8a/pkg/sql/opt/memo/testdata/logprops/scan#L401)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] explain what we expect: s=c_s, d=c_d, i->c_i_expr; and not d->c_d_expr
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-MULp9FD6PXOQrGOcaeT:-MUOKkxi3ijok4B_mbmR:byed8lo) ([raw file](https://github.com/cockroachdb/cockroach/blob/272cf445b3e435a705d0847ee237c273d8fcae21/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L222)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

:woozy_face: maybe an example would help too?
</blockquote></details>

Done - thanks!

**Review by mgartner — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61097)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-MULp9FD6PXOQrGOcaeT:-MUPXy3a5fZiyZMgeUXL:bd3ynpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/272cf445b3e435a705d0847ee237c273d8fcae21/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L222)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Done - thanks!
</blockquote></details>

this explanation is great :100:

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-:-MUPjtWf6g2zPS96PsXg:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61097#-MULp9FD6PXOQrGOcaeT:-MUPjql77nN7EUKlRafD:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/272cf445b3e435a705d0847ee237c273d8fcae21/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L222)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

this explanation is great :100: 
</blockquote></details>

Thanks!

**Pull request merged**
