### PR TITLE
base: ensure that a SQL instance ID is not set to conflicting value

### PR DESCRIPTION
**Pull request by knz**
Informs #58938.
First commit from #72607.

Prior to this patch, a SQL instance ID container could be
assigned successively different values. This would make it possible
for erroneous code to mistakenly initialize the instance ID twice,
without any evidence that something was amiss.

This patch fixes this by using the same prevention logic that we
already use for node IDs.

### CODE REVIEW

**Review by rimadeodhar — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[-- commits, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72608#-MoA37ZFAlDuwZTtRzOa):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>   Prior to this patch, a SQL instance ID container could be
>   assigned successively different values. This would make it possible
>   for erroneous code to mistakenly initialize the instance ID twice,
>   without any evidence that something was amiss.
> 
> ```
</details>

Interesting! What sequence of events can cause this to happen and how did we detect this?
___
*[pkg/base/node_id.go, line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72608#-MoA3i2V6BUXqxpzjbb6:-MoA3i2V6BUXqxpzjbb7:bam0g8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5a471608710d896bea98db2f2902b6149722c02/pkg/base/node_id.go#L223)):*
> ```Go
> 	}
> 
> 	c.sqlInstanceID = sqlInstanceID
> ```

Nit: We can delete this, right? Seems like we are already setting c.sqlInstanceID at
`oldVal := atomic.SwapInt32((*int32)(&c.sqlInstanceID), int32(sqlInstanceID))`.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RaduBerinde, and @rimadeodhar)

___
*[-- commits, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72608#-MoA37ZFAlDuwZTtRzOa):*
> What sequence of events can cause this

A bug in the code.

> how did we detect this?

When it happened for node IDs, we detected it by being confused about why the same log file would report different node IDs in different log messages. Then we added the assertion and saw a bunch of unit tests fail.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rimadeodhar)

___
*[pkg/base/node_id.go, line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72608#-MoA3i2V6BUXqxpzjbb6:-MoDmGuc974LqB2ggREf:b-gyblho) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5a471608710d896bea98db2f2902b6149722c02/pkg/base/node_id.go#L223)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: We can delete this, right? Seems like we are already setting c.sqlInstanceID at
`oldVal := atomic.SwapInt32((*int32)(&c.sqlInstanceID), int32(sqlInstanceID))`.
</blockquote></details>

Oops yes you're right. fixed.

**Comment by knz** [comment]
TFYR!

bors r=rimadeodhar

**Pull request merged**
