### PR TITLE
sql: simplify the role option formatting logic

### PR DESCRIPTION
**Pull request by knz**
Release note: None

### CODE REVIEW

**Review by RichardJCai — APPROVED** [review]

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72567)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/sql/roleoption/role_option.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72567#-Mo4izHq8wknJ507ktnd:-Mo4izHr07S4sdXWUf9s:bdwz6mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbda7e3e503f117967b70478adf84b095222ae90/pkg/sql/roleoption/role_option.go#L97)):*
> ```Go
> 	"LOGIN":                  LOGIN,
> 	"NOLOGIN":                NOLOGIN,
> 	"VALID UNTIL":            VALIDUNTIL,
> ```

@richardjcai could you confirm that this part of the change is backwards-compatible? i.e., is this string used as a value in system.role_options ?

**Comment by RichardJCai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72567)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)
> 
> _[pkg/sql/roleoption/role_option.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72567#-Mo4izHq8wknJ507ktnd:-Mo4izHr07S4sdXWUf9s:bdwz6mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbda7e3e503f117967b70478adf84b095222ae90/pkg/sql/roleoption/role_option.go#L97)):_
> 
> > ```go
> > 	"LOGIN":                  LOGIN,
> > 	"NOLOGIN":                NOLOGIN,
> > 	"VALID UNTIL":            VALIDUNTIL,
> > ```
> 
> @RichardJCai could you confirm that this part of the change is backwards-compatible? i.e., is this string used as a value in system.role_options ?

IIUC this is only for formatting and won't be stored in `system.role_members`. 

The part that's written to disk is unchanged here and lives in this map

```
var toSQLStmts = map[Option]string{
	CREATEROLE:             `UPSERT INTO system.role_options (username, option) VALUES ($1, 'CREATEROLE')`,
	NOCREATEROLE:           `DELETE FROM system.role_options WHERE username = $1 AND option = 'CREATEROLE'`,
	LOGIN:                  `DELETE FROM system.role_options WHERE username = $1 AND option = 'NOLOGIN'`,
	NOLOGIN:                `UPSERT INTO system.role_options (username, option) VALUES ($1, 'NOLOGIN')`,
	VALIDUNTIL:             `UPSERT INTO system.role_options (username, option, value) VALUES ($1, 'VALID UNTIL', $2::timestamptz::string)`,
	CONTROLJOB:             `UPSERT INTO system.role_options (username, option) VALUES ($1, 'CONTROLJOB')`,
	NOCONTROLJOB:           `DELETE FROM system.role_options WHERE username = $1 AND option = 'CONTROLJOB'`,
	CONTROLCHANGEFEED:      `UPSERT INTO system.role_options (username, option) VALUES ($1, 'CONTROLCHANGEFEED')`,
	NOCONTROLCHANGEFEED:    `DELETE FROM system.role_options WHERE username = $1 AND option = 'CONTROLCHANGEFEED'`,
	CREATEDB:               `UPSERT INTO system.role_options (username, option) VALUES ($1, 'CREATEDB')`,
	NOCREATEDB:             `DELETE FROM system.role_options WHERE username = $1 AND option = 'CREATEDB'`,
	CREATELOGIN:            `UPSERT INTO system.role_options (username, option) VALUES ($1, 'CREATELOGIN')`,
	NOCREATELOGIN:          `DELETE FROM system.role_options WHERE username = $1 AND option = 'CREATELOGIN'`,
	VIEWACTIVITY:           `UPSERT INTO system.role_options (username, option) VALUES ($1, 'VIEWACTIVITY')`,
	NOVIEWACTIVITY:         `DELETE FROM system.role_options WHERE username = $1 AND option = 'VIEWACTIVITY'`,
	CANCELQUERY:            `UPSERT INTO system.role_options (username, option) VALUES ($1, 'CANCELQUERY')`,
	NOCANCELQUERY:          `DELETE FROM system.role_options WHERE username = $1 AND option = 'CANCELQUERY'`,
	MODIFYCLUSTERSETTING:   `UPSERT INTO system.role_options (username, option) VALUES ($1, 'MODIFYCLUSTERSETTING')`,
	NOMODIFYCLUSTERSETTING: `DELETE FROM system.role_options WHERE username = $1 AND option = 'MODIFYCLUSTERSETTING'`,
}
```

**Review by rafiss — APPROVED** [review]
thanks for confirming, and thanks for this change

**Comment by knz** [comment]
TFYRs!

bors r=rafiss,RichardJCai

**Pull request merged**
