### PR TITLE
cli,storage: add --shared-storage cli flag, thread through to pebble

### PR DESCRIPTION
**Pull request by itsbilal**
This change adds a new cli flag `--shared-storage` that creates a new cloud.ExternalStorage and passes it through to pebble in a newly-added option in cockroachdb/pebble#2312, along with related store-specific metrics around bytes read/written. The format of this --shared-storage flag is similar to that specified for BACKUPS, and obeys vendor-specific url norms.

Epic: PEBBLE-15

Release note: None.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-:-NNn3IbwEBMzvP_QObrx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[`pkg/cli/cliflags/flags.go` line 998 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-NNn21G90HL74n6JlOIs:-NNn21G90HL74n6JlOIt:b-aq6kgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/85eb5e1c2283d89e50ed96cbe9d99f6b23efb503/pkg/cli/cliflags/flags.go#L998)):*
> ```Go
> 
> 	SharedStorage = FlagInfo{
> 		Name: "shared-storage",
> ```

[nit] maybe make it `--experimental-shared-storage` so people know not to mess with it
___
*[`pkg/server/config.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-NNn2Ha37ywfvVS1960x:-NNn2Ha37ywfvVS1960y:bpyyj6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/85eb5e1c2283d89e50ed96cbe9d99f6b23efb503/pkg/server/config.go#L28)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/base"
> 	"github.com/cockroachdb/cockroach/pkg/base/serverident"
> 	cloudstorage "github.com/cockroachdb/cockroach/pkg/cloud"
> ```

[nit] why the renaming?
___
*[`pkg/storage/shared_storage.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-NNn2OH3895izZ_Xnv2Q:-NNn2OH3895izZ_Xnv2R:bj4r9uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/85eb5e1c2283d89e50ed96cbe9d99f6b23efb503/pkg/storage/shared_storage.go#L22)):*
> ```Go
> )
> 
> type externalStorageReader struct {
> ```

[nit] can use a comment. Also a type assertion below to show that it implements `shared.Storage`
___
*[`pkg/storage/shared_storage.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-NNn2yClDgBfdPXe_yv9:-NNn2fHm7xHbue6fBQoX:b8kvn7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/85eb5e1c2283d89e50ed96cbe9d99f6b23efb503/pkg/storage/shared_storage.go#L54)):*
> ```Go
> 
> type externalStorageWrapper struct {
> 	p   *Pebble
> ```

[nit] This could use a comment, having a `Pebble` reference here seems very strange. Maybe even a TODO to extract an interface for updating stats. Or maybe these stats should be inside Pebble (I assume we'll want more stats related to shared storage, which won't be available here).

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96821)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @RaduBerinde)

___
*[`pkg/cli/cliflags/flags.go` line 998 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-NNn21G90HL74n6JlOIs:-NNnBmeK8yHOgy_NoOJA:b-xwtf04) ([raw file](https://github.com/cockroachdb/cockroach/blob/85eb5e1c2283d89e50ed96cbe9d99f6b23efb503/pkg/cli/cliflags/flags.go#L998)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe make it `--experimental-shared-storage` so people know not to mess with it
</blockquote></details>

I wonder if it's possible to hide it from the 23.1 build somehow? I suppose we could always just remove it in the 23.1 release branch once it's cut.

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-:-NNrBvdaC1wVeLk0u0AX:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[`pkg/cli/cliflags/flags.go` line 998 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-NNn21G90HL74n6JlOIs:-NNrBwXK8Y4Hsxx3GbEa:b-hv4tbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/85eb5e1c2283d89e50ed96cbe9d99f6b23efb503/pkg/cli/cliflags/flags.go#L998)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I wonder if it's possible to hide it from the 23.1 build somehow? I suppose we could always just remove it in the 23.1 release branch once it's cut.
</blockquote></details>

Yeah that's a good point. I can't see a way to hide something from the help text either. Let's just remember to take this off the 23.1 branch.

I've changed this to `--experimental-shared-storage` and turns out this isn't the first `--experimental-*` flag anyway, so there's precedence for this.
___
*[`pkg/server/config.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-NNn2Ha37ywfvVS1960x:-NNrBs2k39uv2QRpTQ2V:b-78lkch) ([raw file](https://github.com/cockroachdb/cockroach/blob/85eb5e1c2283d89e50ed96cbe9d99f6b23efb503/pkg/server/config.go#L28)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] why the renaming?
</blockquote></details>

Oops, unintentional. Undone.
___
*[`pkg/storage/shared_storage.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-NNn2OH3895izZ_Xnv2Q:-NNrDWlm-zUsB_3PNRXn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85eb5e1c2283d89e50ed96cbe9d99f6b23efb503/pkg/storage/shared_storage.go#L22)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] can use a comment. Also a type assertion below to show that it implements `shared.Storage`
</blockquote></details>

Done.
___
*[`pkg/storage/shared_storage.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-NNn2yClDgBfdPXe_yv9:-NNrCHJe46vzFRe72xpk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85eb5e1c2283d89e50ed96cbe9d99f6b23efb503/pkg/storage/shared_storage.go#L54)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This could use a comment, having a `Pebble` reference here seems very strange. Maybe even a TODO to extract an interface for updating stats. Or maybe these stats should be inside Pebble (I assume we'll want more stats related to shared storage, which won't be available here).
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-:-NNrpi8iE9DXn2cG8IYu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by itsbilal** [comment]
bors r=raduberinde

**Comment by RaduBerinde** [comment]
*[`pkg/storage/pebble.go` line 1030 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96821#-NOR0zruCaVto8QX52N-:-NOR0zruCaVto8QX52N0:b-zgtsx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb99e69c951e963a80f14476736803c0e939948/pkg/storage/pebble.go#L1030)):*
> ```Go
> 	if cfg.SharedStorage != nil {
> 		esWrapper := &externalStorageWrapper{p: p, es: cfg.SharedStorage, ctx: ctx}
> 		cfg.Opts.Experimental.SharedStorage = esWrapper
> ```

Hi @itsbilal - we should be modifying `opts` here instead of `cfg.Opts`. This was probably due to rebasing against #96770. I can sneak in a fix here in #97054. Just FYI in case you don't see this working as expected.

**Pull request merged**
