### PR TITLE
sql: add "implicit" column to SHOW INDEXES and info_schem.statistics

### LINKED ISSUE #5230: sql: Show Index does not show implicit columns
It can get confusing which index will be selected for a given select because it is not always clear what implicit columns are included in an index. The SHOW INDEX command should identify implicit indexes on columns (preferably distinguished from explicit columns). Additionally, EXPLAIN SELECT should include these implicit indexes on its pretty printed spans.

### PR DESCRIPTION
**Pull request by nvb**
Closes #5230.

This change adds a new column to `information_schema.statistics` and
SHOW INDEXES called "implicit". The field is meant for implicit columns
that are part of the index. These implicit columns make up half of the
columns stored in `IndexDescriptor.ExtraColumnIDs`, with the other half
being "storing" columns that are already present in 'SHOW INDEXES' and the
corresponding meta table.

The original plan was to replace the "storing" column with an enumeration
for special types of index columns, but this design went against the
convention for 'information_schema' table schemas. Instead
'information_schema' (and by consequence, SHOW statements) prefer
boolean columns, even if not all are orthogonal to one another.

@cuongdo for the `SortStructs` change in commit 3.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12801)

### CODE REVIEW

**Comment by jordanlewis** [comment]
The implementation :lgtm:. I think it's worth discussing whether we should be making this change as such, though - the `Implicit` column is not present in the MySQL implementation of `information_schema.statistics`, so it seems like we're treading new ground here. I suppose there's nothing wrong with that since we're not changing the semantics of existing fields, but perhaps we should explicitly call this out for documentation. We'll want to make sure that all of the non-standard fields we export from information_schema and pg_catalog are well-documented.

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 24 of 24 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12801#-:-KaDSHp2-lwZjrJLJAMP:b-12hg2e)*

**Comment by nvanbenschoten** [comment]
TFTR @jordanlewis! You're completely right that this will be a Cockroach-specific extension to `information_schema.statistics`, and that it should be documented as so. That said, implementation-specific columns are par for the course when it comes to the `information_schema`. Postgres does it, MySQL [does it](http://dev.mysql.com/doc/refman/5.7/en/columns-table.html), and we do it. In fact, the `Storing` column directly beside this new column is also CockroachDB specific.

I think we're in agreement that we need to make this a bit more clear in our docs, perhaps by having a small Cockroach logo next to non-standard fields. What do you think? cc. @sploiselle

**Comment by sploiselle** [comment]
@nvanbenschoten Calling it out as Cockroach specific is great. It's simple to do by just stating it on the line with the description––something like `<column descrtiption>. *(This column is specific to CockroachDB's information_schema.)*`

**Comment by nvanbenschoten** [comment]
@sploiselle That approach sounds great. I've opened https://github.com/cockroachdb/docs/issues/993 to continue following that task.

**Comment by bdarnell** [comment]
This change broke the tests in https://github.com/cockroachdb/cockroachdb-python: SQLAlchemy's test suite validates the results of `SHOW INDEXES` and doesn't expect any implicit columns to be present. Can we make the inclusion of implicit indexes opt-in somehow, or should we just disable that test?

**Comment by bdarnell** [comment]
Nevermind, that `SHOW INDEXES` call comes from our own code, so we can change it. (we can't use the upstream index introspection code because we don't have the `pg_table_is_visible` function yet). The real query we need to support for unmodified SQLAlchemy is

```
              SELECT
                  i.relname as relname,
                  ix.indisunique, ix.indexprs, ix.indpred,
                  a.attname, a.attnum, NULL, ix.indkey%s,
                  %s, am.amname
              FROM
                  pg_class t
                        join pg_index ix on t.oid = ix.indrelid
                        join pg_class i on i.oid = ix.indexrelid
                        left outer join
                            pg_attribute a
                            on t.oid = a.attrelid and %s
                        left outer join
                            pg_am am
                            on i.relam = am.oid
              WHERE
                  t.relkind IN ('r', 'v', 'f', 'm')
                  and t.oid = :table_oid
                  and ix.indisprimary = 'f'
              ORDER BY
                  t.relname,
                  i.relname
```

I don't know whether that will show implicit columns or not.

**Pull request merged**
