### PR TITLE
sql: add a new observer statement to show last query statistics

### PR DESCRIPTION
**Pull request by arulajmani**
Adds a new observer statement `SHOW LAST QUERY STATISTICS` which
returns service, latency, planning, and parsing timigns for the last
executed statement. By exposing these timings this PR builds a bridge
towards providing more in-depth metrics to improve timings displayed by
the CLI.

Note that this new statement should probably not be exposed to users,
and should only be used for internal use (and therefore I'm leaving
the release note blank here). This is because the CLI issues some
"under the hood" queries (eg. retriving the current db so that it can
be displayed). If a user would use this statement without insight into
these "under the hood" queries it could prove to be confusing.

Informs #49450

Release note: none

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
Looks good in general! Left some minor comments. Could you also think about adding a simple logic test for this? Don't need exact assertions for the results, just that the statement works and returns values in a reasonable range.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-:-MAbBaNgCM1ok2QB4l1v:b-gc0mw8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/conn_executor_exec.go, line 1159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MAb7s0I-yk2yph1Dhr0:-MAb7s0I-yk2yph1Dhr1:b-rfkze7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a3a9a9929e519b187c759b2aa0ea19aaad1820/pkg/sql/conn_executor_exec.go#L1159)):*
> ```Go
> 
> 	return res.AddRow(ctx,
> 		tree.Datums{tree.NewDInterval(duration.FromFloat64(svcLat), types.DefaultIntervalTypeMetadata),
> ```

Nit: This code would read better if you added a newline after the `{` and before the `}`.
___
*[pkg/sql/exec_util.go, line 2129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MAb8SguD0_LB8dpM-3r:-MAb8SguD0_LB8dpM-3s:b-j8ibch) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a3a9a9929e519b187c759b2aa0ea19aaad1820/pkg/sql/exec_util.go#L2129)):*
> ```Go
> 	phaseTimes phaseTimes
> 	// previousPhaseTimes tracks the session-level phase times for the previous
> 	//query.
> ```

Nit: missing space

Could you also specify what this is used for?
___
*[pkg/sql/executor_statement_metrics.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MAb9PK0EY3P3HBqFi4S:-MAb9PK0EY3P3HBqFi4T:bujvi5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a3a9a9929e519b187c759b2aa0ea19aaad1820/pkg/sql/executor_statement_metrics.go#L64)):*
> ```Go
> // and transaction-level phase times.
> type phaseTimes struct {
> 	internalPhaseTimes internalPhaseTimes
> ```

This wrapper isn't really buying us anything yet is it? I would say let's hold off on refactoring this until you separate out the session and statement times.
___
*[pkg/sql/sqlbase/result_columns.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MAbB0tyBzJBjnW8iB4h:-MAbB0tyBzJBjnW8iB4i:bb2ouxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a3a9a9929e519b187c759b2aa0ea19aaad1820/pkg/sql/sqlbase/result_columns.go#L204)):*
> ```Go
> 	{Name: "query_exec_time", Typ: types.Interval},
> 	{Name: "planning_time", Typ: types.Interval},
> 	{Name: "parsing_time", Typ: types.Interval},
> ```

If you'll allow me to bikeshed a bit, how about ordering these in the order they happen? Also maybe "latency" is clearer than time.
```
parse_latency
plan_latency
exec_latency
service_latency
```

**Review by arulajmani — COMMENTED** [review]
Couldn't add logic tests because we don't support this statement as a statement source, so I've added a local test that sets up a test server and checks the values are in reasonable bounds. RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-:-MB034oL0a09cSAEhYNo:b-tt9uyo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/executor_statement_metrics.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MAb9PK0EY3P3HBqFi4S:-MAg3E_4-MbLUJoYxVfw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a3a9a9929e519b187c759b2aa0ea19aaad1820/pkg/sql/executor_statement_metrics.go#L64)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This wrapper isn't really buying us anything yet is it? I would say let's hold off on refactoring this until you separate out the session and statement times.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/result_columns.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MAbB0tyBzJBjnW8iB4h:-MAg8ZWoEQ0q6NXmikS8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8a3a9a9929e519b187c759b2aa0ea19aaad1820/pkg/sql/sqlbase/result_columns.go#L204)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

If you'll allow me to bikeshed a bit, how about ordering these in the order they happen? Also maybe "latency" is clearer than time.
```
parse_latency
plan_latency
exec_latency
service_latency
```
</blockquote></details>

Done.

**Review by solongordon — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50575)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/sql/conn_executor_show_statistics_test.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MBFtMP2Aod0DS7aAvn8:-MBFtMP3DH37Hw_ZA1Wa:b-d9dujp) ([raw file](https://github.com/cockroachdb/cockroach/blob/16a2c79d8ea6db5182e86646fcadc185d88c7a3f/pkg/sql/conn_executor_show_statistics_test.go#L68)):*
> ```Go
> 	}
> 
> 	if parseInterval.AsFloat64() <= 0 || parseInterval.AsFloat64() > 0.001 {
> ```

I'm thinking let's increase the acceptable bounds to at least a full second if not more. It would be annoying for this test to flakily fail when the system is under load or something. We just want to check that the value is relatively sane. Also I'm thinking that the lower bound should be exclusive of 0.

Same applies for the remaining checks.

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50575)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/sql/conn_executor_show_statistics_test.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MBG2BL608_sMWewpaH9:-MBG2BL608_sMWewpaHA:bpu2e5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/16a2c79d8ea6db5182e86646fcadc185d88c7a3f/pkg/sql/conn_executor_show_statistics_test.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

Nit: You could just add this to `conn_executor_test.go` rather than creating a new test file.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50575)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/conn_executor_show_statistics_test.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MBG2BL608_sMWewpaH9:-MBaBR6KDJElagIAVJOi:bwhglds) ([raw file](https://github.com/cockroachdb/cockroach/blob/16a2c79d8ea6db5182e86646fcadc185d88c7a3f/pkg/sql/conn_executor_show_statistics_test.go#L1)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: You could just add this to `conn_executor_test.go` rather than creating a new test file.
</blockquote></details>

Moved.
___
*[pkg/sql/conn_executor_show_statistics_test.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MBFtMP2Aod0DS7aAvn8:-MBaBb2U9Q7_OUAesSo0:bnw390i) ([raw file](https://github.com/cockroachdb/cockroach/blob/16a2c79d8ea6db5182e86646fcadc185d88c7a3f/pkg/sql/conn_executor_show_statistics_test.go#L68)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'm thinking let's increase the acceptable bounds to at least a full second if not more. It would be annoying for this test to flakily fail when the system is under load or something. We just want to check that the value is relatively sane. Also I'm thinking that the lower bound should be exclusive of 0.

Same applies for the remaining checks. 
</blockquote></details>

Changed all the upper bounds to 1s, which should leave quite a buffer. I don't think we should make the lower bound exclusive of zero though. Zero is the default value which `SHOW LAST QUERY STATISTICS` returns if the previous query hasn't updated the phase times/there is no previous query to return phase times for -- both of these cases should fail this test. I think having zero inclusive adds value to this test.

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50575)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/conn_executor_show_statistics_test.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50575#-MBFtMP2Aod0DS7aAvn8:-MBdd3ZZErEr33IyY_VA:bobhin9) ([raw file](https://github.com/cockroachdb/cockroach/blob/16a2c79d8ea6db5182e86646fcadc185d88c7a3f/pkg/sql/conn_executor_show_statistics_test.go#L68)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Changed all the upper bounds to 1s, which should leave quite a buffer. I don't think we should make the lower bound exclusive of zero though. Zero is the default value which `SHOW LAST QUERY STATISTICS` returns if the previous query hasn't updated the phase times/there is no previous query to return phase times for -- both of these cases should fail this test. I think having zero inclusive adds value to this test.  
</blockquote></details>

Oh sorry, I totally agree. I misread the test and thought that 0 would pass.

**Comment by arulajmani** [comment]
TFTR! 

bors r=solongordon

**Comment by arulajmani** [comment]
Didn't realize CI was failing because of a lint failure -- fixed that, should be good to merge now! 

bors r=solongordon

**Comment by arulajmani** [comment]
There's a help test missing too 

bors r-

**Comment by arulajmani** [comment]
bors r=solongordon

**Pull request merged**
