### PR TITLE
storage/raft_transport: use a separate queue for each message type

### PR DESCRIPTION
**Pull request by tamird**
@cuongdo can you try this to see if it mitigates #7258? If it does, I'll clean the code up some before merging.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7299)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/raft_transport.go, line 218 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKQIMK52eHxP3FlxRgZ:-KKQIMK52eHxP3FlxRg_:-863820943) ([raw file](https://github.com/cockroachdb/cockroach/blob/eefa98263e2909588838db031c0721772c1a7dcc/storage/raft_transport.go#L218)):*
> ```Go
> 	t.rpcContext.Stopper.RunTask(func() {
> 		t.rpcContext.Stopper.RunWorker(func() {
> 			// NB: only one error will ever be read from this channel. That's fine,
> ```

Remove this comment now that it's just a single error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-:-KKQIZgVWO-1Z7PDUnXK:1417088721)*

**Comment by cuongdo** [comment]
Nice! I see no unmarshal errors on any nodes using a custom build with your changes thus far. Previously, it was trivial to trigger this error with substantial snapshot load.

**Comment by tamird** [comment]
Great! Now if only I could figure out why TestSendAndReceive is hanging...

**Comment by tschottdorf** [comment]
What is the change here that makes the error go away? Is code like this the problem?

```go
stream1, _ := client.RaftMessage(ctx)
stream2, _ := client.RaftMessage(ctx)
// use stream{1,2} concurrently
```

**Comment by tamird** [comment]
Nah, it's that we were using stream2 concurrently - each snapshot was in an async task on the same stream.

**Comment by tschottdorf** [comment]
gotcha, thanks.

On Thu, Jun 16, 2016 at 10:54 PM Tamir Duberstein <notifications@github.com>
wrote:

> Nah, it's that we were using stream2 concurrently - each snapshot was in
> an async task on the same stream.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7299#issuecomment-226668462>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135Fyr49C-gPRpAVULLZyLjcA6Hvvjks5qMgxqgaJpZM4I33Zd>
> .
>
-- 

-- Tobias

**Comment by tamird** [comment]
OK, this is ready for another look.

**Comment by cuongdo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport.go, line 175 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTZwXzEc15C_3g2z6r:-KKTZwXzEc15C_3g2z6s:7667158) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L175)):*
> ```Go
> 
> 	ctx, cancel := context.WithCancel(context.TODO())
> 	defer cancel()
> ```

Why are you going back to always calling `cancel()` when this method returns? What if there are in-flight snapshots when a Raft transport error or idle timeout occurs? 

---

*[storage/raft_transport.go, line 222 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTfp-5P8px05a4m7y6:-KKTfp-5P8px05a4m7y7:-1606193126) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L222)):*
> ```Go
> 	if !ok {
> 		queues = make(map[roachpb.NodeID]chan *RaftMessageRequest)
> 		t.mu.queues[req.Message.Type] = queues
> ```

This assumes that there's never a case where two goroutines are trying to stream the same type of Raft message to the same node. Is that true in practice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport.go, line 175 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTZwXzEc15C_3g2z6r:-KKTjLVNkqOOjbtN9F4E:854285992) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L175)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> Why are you going back to always calling `cancel()` when this method returns? What if there are in-flight snapshots when a Raft transport error or idle timeout occurs? 
</details>
Nothing here is asynchronous any more; neither condition can occur while anything is in flight.

---

*[storage/raft_transport.go, line 222 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTfp-5P8px05a4m7y6:-KKTjTWx5qxCKAGsdYuc:629943706) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L222)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> This assumes that there's never a case where two goroutines are trying to stream the same type of Raft message to the same node. Is that true in practice?
</details>
Why does it assume that? We're holding the lock here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport.go, line 76 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTkpINTJd_UMjtBEZo:-KKTkpINTJd_UMjtBEZp:-689748769) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L76)):*
> ```Go
> 		sync.Mutex
> 		handlers map[roachpb.StoreID]raftMessageHandler
> 		queues   map[raftpb.MessageType]map[roachpb.NodeID]chan *RaftMessageRequest
> ```

Previously we were using one queue for `MsgSnap` and another queue for everything else. Now there is a queue per message type. Is that problematic? I don't know enough about raft. An alternative to this would be to model this as:

```
map[bool]map[roachpb.NodeID]chan *RaftMessageRequest
```

And then access it as `t.mu.queues[req.Message.Type == raftpb.MsgSnap]`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport.go, line 76 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTkpINTJd_UMjtBEZo:-KKTlSDPmfQv29ojbbaj:-1183080347) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L76)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Previously we were using one queue for `MsgSnap` and another queue for everything else. Now there is a queue per message type. Is that problematic? I don't know enough about raft. An alternative to this would be to model this as:
> 
> ```
> map[bool]map[roachpb.NodeID]chan *RaftMessageRequest
> ```
> 
> And then access it as `t.mu.queues[req.Message.Type == raftpb.MsgSnap]`. 
</details>
Yeah, that's an option. There are about 13-14 message types. Do you think it really matters?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport.go, line 76 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTkpINTJd_UMjtBEZo:-KKTltWwKjqhgBZhHifW:1955626550) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L76)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, that's an option. There are about 13-14 message types. Do you think it really matters?
</details>
I have no idea if it matters. My suggestion was motivated by trying to be more conservative with this change and only fixing the known problem of accessing the snapshot stream concurrently. One problem with using a queue per message type is that each queue will require goroutines on the reading side. Is that increase a problem? I don't know. Is the differing flow control (which could reorder messages) a problem? I don't know. 

@bdarnell?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299)*

**Comment by cuongdo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport.go, line 222 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTfp-5P8px05a4m7y6:-KKTkA7Zb01FqgJWwVzz:-664822032) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L222)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Why does it assume that? We're holding the lock here.
</details>
I was worried about the `ch<-req`below being called from different goroutines and streamed asynchronously, but I hadn't realized you'd made `processQueue` process each message synchronously within each queue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/raft_transport.go, line 76 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTkpINTJd_UMjtBEZo:-KKTocCw885spzbNpqFN:1300038443) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L76)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I have no idea if it matters. My suggestion was motivated by trying to be more conservative with this change and only fixing the known problem of accessing the snapshot stream concurrently. One problem with using a queue per message type is that each queue will require goroutines on the reading side. Is that increase a problem? I don't know. Is the differing flow control (which could reorder messages) a problem? I don't know. 
> 
> @bdarnell?
</details>
Changed to the more conservative thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-:-KKTw8Kqh6zY1w2F__Fe:1417088721)*

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-:-KKU2kYfi3tZsnev39iR:1417088721)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/raft_transport.go, line 76 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTkpINTJd_UMjtBEZo:-KKU3f6Sv1Iv-lFGYCQZ:949220826) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L76)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Changed to the more conservative thing.
</details>
Yeah, raft performance suffers if messages get reordered, so it's better to use one queue for all non-snapshot messages.  (I'm not sure if there are issues with cross-type reordering but we've definitely seen it with MsgApp getting reordered)

Needs a comment about what true and false mean, and why we're doing this in the first place (all the comments about snapshots not blocking other messages have been lost).

---

*[storage/raft_transport_test.go, line 119 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKU990xaEhu9LM-mgx8:-KKU990yWFCNENyNAiYw:-1758518444) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a1bf7bfa433e7180ed5038c11f45b679208585/storage/raft_transport_test.go#L119)):*
> ```Go
> 
> 		transports[nodeID] = storage.NewRaftTransport(storage.GossipAddressResolver(g), grpcServer, nodeRPCContext)
> 		// This channel is nominally unbuffered, but it is also normally serviced
> ```

s/nominally/normally/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-:-KKU9IVGIz7X1H28SSpu:1417088721)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/raft_transport.go, line 76 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKTkpINTJd_UMjtBEZo:-KKUAk-3X5ZKCe4TYW1a:-1619554646) ([raw file](https://github.com/cockroachdb/cockroach/blob/62bb4434c115670168d1f0950d25810dff050eea/storage/raft_transport.go#L76)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Yeah, raft performance suffers if messages get reordered, so it's better to use one queue for all non-snapshot messages.  (I'm not sure if there are issues with cross-type reordering but we've definitely seen it with MsgApp getting reordered)
> 
> Needs a comment about what true and false mean, and why we're doing this in the first place (all the comments about snapshots not blocking other messages have been lost).
</details>
Added a comment at the use-site.

---

*[storage/raft_transport_test.go, line 119 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299#-KKU990xaEhu9LM-mgx8:-KKUB0Sou5kAXZ9In0Qi:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a1bf7bfa433e7180ed5038c11f45b679208585/storage/raft_transport_test.go#L119)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/nominally/normally/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7299)*

**Pull request merged**
