### PR TITLE
sqlccl: add sanity/debugging info to backup proto

### LINKED ISSUE #15231: sqlccl: backups should keep track of the creating cluster's ID
We should be able to report an error if a user specifies `BACKUP... INCREMENTAL FROM foo` where `foo` is a backup (potentially of identical tables) from a different cluster.

### LINKED ISSUE #15232: backup: include version info in backup desc
we should include server version, cluster id and "backup version" (e.g. 0 for now, identifying the file format) in the proto.

### PR DESCRIPTION
**Pull request by dt**
We'd really like to be writing these fields as of 1.0 even if we don't use or even read them yet.

Unti #14219 is resolved or we actually start using the info somehow, I'm not sure there's a great way to test this?

Fixes #15232.
Fixes #15231.

### CODE REVIEW

**Comment by benesch** [comment]
Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.proto, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315#-KiYIAJ0YSOolR1mPUT1:-KiYIAJ0YSOolR1mPUT2:bdaoxs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5fb7fd7c8d0d9b1449e077c016286b160b174cd/pkg/ccl/sqlccl/backup.proto#L50)):*
> ```protobuf
>   uint32 format_version = 8;
> 
>   bytes cluster_id = 10 [(gogoproto.nullable) = false, (gogoproto.customname) = "ClusterID",
> ```

Did you mean to skip a number here?

---

*[pkg/ccl/sqlccl/backup.proto, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315#-KiYIOKlSv2CfYxK7bA3:-KiYIOKlSv2CfYxK7bA4:bf5js7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5fb7fd7c8d0d9b1449e077c016286b160b174cd/pkg/ccl/sqlccl/backup.proto#L56)):*
> ```protobuf
>   int32 node_id = 11 [(gogoproto.customname) = "NodeID",
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/roachpb.NodeID"];
>   build.Info buildInfo = 12 [(gogoproto.nullable) = false];
> ```

`build_info`, no? And if so, in the comment above as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315)*

**Comment by dt** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.proto, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315#-KiYIAJ0YSOolR1mPUT1:-KiYKmyEff_mGwFTx1YK:bxyvu2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5fb7fd7c8d0d9b1449e077c016286b160b174cd/pkg/ccl/sqlccl/backup.proto#L50)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Did you mean to skip a number here?
</blockquote></details>

yes, but not for a particularly compelling technical reason.

---

*[pkg/ccl/sqlccl/backup.proto, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315#-KiYIOKlSv2CfYxK7bA3:-KiYKuLAL_pb7VbIH6vt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5fb7fd7c8d0d9b1449e077c016286b160b174cd/pkg/ccl/sqlccl/backup.proto#L56)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`build_info`, no? And if so, in the comment above as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315)*

**Comment by dt** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.proto, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315#-KiYIAJ0YSOolR1mPUT1:-KiYPGs8TpgQq6AtV_f6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5fb7fd7c8d0d9b1449e077c016286b160b174cd/pkg/ccl/sqlccl/backup.proto#L50)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

yes, but not for a particularly compelling technical reason.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315)*

**Comment by tamird** [comment]
i think you can squash these commits.

---

Reviewed 5 of 5 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.proto, line 53 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315#-KiZ2ao9NnQVzLbCo9M_:-KiZ2ao9NnQVzLbCo9Ma:bma6cc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2e0b9710b469eeb23cf4e9f45252d685132bc6/pkg/ccl/sqlccl/backup.proto#L53)):*
> ```protobuf
>     (gogoproto.customtype) = "github.com/cockroachdb/cockroach/pkg/util/uuid.UUID"];
> 
>   // node_id and build_info for the gateway node (which writes the descriptor).
> ```

s/for/of/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315#-:-KiZ2rTs4X6HBlwYDzbJ:b-hjemvf)*

**Comment by dt** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.proto, line 53 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315#-KiZ2ao9NnQVzLbCo9M_:-Ki_27SodcPsppTiC_GW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2e0b9710b469eeb23cf4e9f45252d685132bc6/pkg/ccl/sqlccl/backup.proto#L53)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/for/of/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15315)*

**Pull request merged**
