### PR TITLE
[CRDB-45638] go: upgrade golang.org/x/crypto

### PR DESCRIPTION
**Pull request by pritesh-lahoti**
The existing version of golang.org/x/crypto is prone to critical vulnerabilities.
Ref - https://github.com/cockroachdb/cockroach/security/dependabot/550, https://github.com/cockroachdb/cockroach/security/dependabot/551.

This PR updates the library version. There does not seem to be any backwards incompatibility as part of the version upgrade. Verified the same through kerberos roachtest.

Fixes: CRDB-45638

Release note: None

### CODE REVIEW

**Review by sanchit-CRL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137539)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`DEPS.bzl` line 11522 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137539#-OEHtw9B4gFgQ4iAB542:-OEHtw9B4gFgQ4iAB543:bu9ierd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9504caa1553802d361134a1f3f43e2e5813b3ee/DEPS.bzl#L11522)):*
> ```Starlark
>         build_file_proto_mode = "disable_global",
>         importpath = "golang.org/x/crypto",
>         # TODO: mirror this repo (to fix, run `./dev generate bazel --mirror`)
> ```

Seems like ./dev gen bazel needs to be run

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137539)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sanchit-CRL)

___
*[`DEPS.bzl` line 11522 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137539#-OEHtw9B4gFgQ4iAB542:-OEI4lWT13Y-_R5rtRAb:b-1jl013) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9504caa1553802d361134a1f3f43e2e5813b3ee/DEPS.bzl#L11522)):*
<details><summary><i>Previously, sanchit-CRL wrote…</i></summary><blockquote>

Seems like ./dev gen bazel needs to be run
</blockquote></details>

Fixed. Thank you!

**Review by sanchit-CRL — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137539)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

**Comment by pritesh-lahoti** [comment]
bors r=sanchit-CRL

**Comment by pritesh-lahoti** [comment]
bors cancel

**Comment by pritesh-lahoti** [comment]
bors r=sanchit-CRL

**Comment by pritesh-lahoti** [comment]
blathers backport 24.2 24.3

**Pull request merged**
