### PR TITLE
opt: fix inverted scan FDs

### LINKED ISSUE #122225: opt: incorrect functional dependencies for inverted index scans
The functional dependencies for scans over inverted indexes are copied from the functional dependencies of the table. As a result, the functional dependencies for these scans are incorrect. Most notable, they will have FD keys of the primary key columns, which are not keys in inverted indexes, where multiple tuples map to a single logical row.

For example:

```sql
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT[],
  INVERTED INDEX (a)
);

EXPLAIN (OPT, VERBOSE)
SELECT * FROM t WHERE a @> ARRAY[1, 2];
--                                                 info
-- -----------------------------------------------------------------------------------------------------
--   index-join t
--    ├── columns: k:1 a:2
--    ├── immutable
--    ├── stats: [rows=12.22222]
--    ├── cost: 608.915556
--    ├── key: (1)
--    ├── fd: (1)-->(2)
--    ├── distribution: us-east1
--    ├── prune: (1)
--    └── inverted-filter
--         ├── columns: k:1
--         ├── inverted expression: /5
--         │    ├── tight: true, unique: true
--         │    ├── union spans: empty
--         │    └── INTERSECTION
--         │         ├── span expression
--         │         │    ├── tight: true, unique: true
--         │         │    └── union spans: ["\x89", "\x89"]
--         │         └── span expression
--         │              ├── tight: true, unique: true
--         │              └── union spans: ["\x8a", "\x8a"]
--         ├── stats: [rows=111.1111]
--         ├── cost: 139.151111
--         ├── key: (1)
--         ├── distribution: us-east1
--         └── scan t@t_a_idx
--              ├── columns: k:1 a_inverted_key:5
--              ├── inverted constraint: /5/1
--              │    └── spans: ["\x89", "\x8b")
--              ├── stats: [rows=111.1111, distinct(1)=111.111, null(1)=0, distinct(5)=100, null(5)=0]
--              ├── cost: 138.02
--              ├── key: (1)
--              ├── fd: (1)-->(5)
--              └── distribution: us-east1
-- (34 rows)

```

Notice the `key: (1)` in the scan expression. `k` is not a key in this scan, so this is incorrect.

There are no known correctness bugs caused by this, and I think the existence of such a bug is unlikely because the inverted filter expression de-duplicates on primary key columns, and there are no rules that re-order or manipulate inverted filter expressions. So the incorrect FDs do not propagate or trigger incorrect optimizations.

We should fix this by:

1. Not copying FDs from underlying table in inverted index scans.
2. Making PK columns keys in inverted expressions.

Note that there is a special case we should watch out for: the PK columns are keys in the scan if a single value is scanned. For example, the `key: (1)` in the scan below is correct:

```sql
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT[],
  INVERTED INDEX (a)
);

EXPLAIN (OPT, VERBOSE)
SELECT * FROM t WHERE a @> ARRAY[1];
--                               info
-- ----------------------------------------------------------------
--   index-join t
--    ├── columns: k:1 a:2
--    ├── immutable
--    ├── stats: [rows=110]
--    ├── cost: 807.962222
--    ├── key: (1)
--    ├── fd: (1)-->(2)
--    ├── distribution: us-east1
--    ├── prune: (1)
--    └── scan t@t_a_idx
--         ├── columns: k:1
--         ├── inverted constraint: /5/1
--         │    └── spans: ["\x89", "\x89"]
--         ├── stats: [rows=111.1111, distinct(5)=100, null(5)=0]
--         ├── cost: 135.797778
--         ├── key: (1)
--         └── distribution: us-east1
-- (17 rows)
```

Jira issue: CRDB-37760

### PR DESCRIPTION
**Pull request by mgartner**
Inverted index scans can produce multiple tuples for a single logical
row in the table. Therefore, it is incorrect for them to inherit FD keys
from the underlying table, as was the case prior to this commit.

This commit fixes the incorrect FDs by:

1. Making inverted scans only inherit underlying table FDs and partial
   index FDs if they scan a single inverted key. This is the only case
   where the table's FDs are guaranteed to be upheld during an inverted
   scan.
2. Adding the PK columns of the underlying table as a strict key of
   inverted filters. Inverted filters deduplicate the tuples such that
   there is a single output tuple per logical row. Therefore, the strict
   key can be added back in the inverted filter expression to maintain
   the correct FDs.

There are no known correctness bugs caused by the incorrect FDs, and it
is unlikely that any such bugs exist because, as mentioned above, the
inverted filter expression de-duplicates on primary key columns (so the
output tuples conform to the FDs) and there are no rules that re-order
or manipulate inverted filter expressions. The incorrect FDs should not
have propagated or triggered incorrect optimizations.

Despite these incorrect FDs not causing a bug, it is important to fix
them to prevent them from contributing to future bugs.

Fixes #122225

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

By the way, do we have a similar problem for inverted joins? https://github.com/cockroachdb/cockroach/blob/b5af72e1decb324ed0d8c937186f0966f57048b0/pkg/sql/opt/memo/logical_props_builder.go#L2255

> Reviewed 16 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129867#-:-O5UvzaLEb447Q_5qRK8:b4zy8b2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129867#-O5Uwyj56bd6wgQhBf2Y:-O5Uwyj56bd6wgQhBf2Z:b-t930wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f733ea6ab2c557e161c1ed7bc717b0a67be46ea/pkg/sql/opt/memo/logical_props_builder.go#L144)):*
> ```Go
> 		// Add FDs from the partial index predicate if the scan is over a
> 		// non-inverted index, or a single key in an inverted index.
> 		if pred != nil && (!scan.IsInvertedScan(md) || singleKeyInvertedScan) {
> ```

Wouldn't any filters still apply? Like, `x > 5` is true even if `x` gets duplicated.

**Review by mgartner — COMMENTED** [review]
> By the way, do we have a similar problem for inverted joins?

:thinking: Good question. I don't think we have the _same_ problem. But the FDs for the first join in a paired join are suspicious. In the example below, I'm not sure the `(12)-->(17)` correct...

```sql
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT[],
  INVERTED INDEX i (a)
);

CREATE TABLE s (
  k INT PRIMARY KEY,
  a INT[],
  b INT,
  INDEX (b)
);

EXPLAIN (OPT, VERBOSE)
SELECT *
FROM s
LEFT JOIN t ON s.a @> t.a
WHERE s.b = 10;
--                                      info
-- -------------------------------------------------------------------------------
--   left-join (lookup t)
--    ├── columns: k:1 a:2 b:3 k:6 a:7
--    ├── key columns: [12] = [6]
--    ├── lookup columns are key
--    ├── second join in paired joiner
--    ├── immutable
--    ├── stats: [rows=100]
--    ├── cost: 1113.79001
--    ├── key: (1,6)
--    ├── fd: ()-->(3), (1)-->(2), (6)-->(7)
--    ├── distribution: us-east1
--    ├── prune: (1,6)
--    ├── left-join (inverted t@i)
--    │    ├── columns: s.k:1 s.a:2 b:3 t.k:12 continuation:17
--    │    ├── first join in paired joiner; continuation column: continuation:17
--    │    ├── inverted-expr
--    │    │    └── t.a:13 <@ s.a:2
--    │    ├── stats: [rows=100, distinct(12)=95.6179, null(12)=0]
--    │    ├── cost: 500.760005
--    │    ├── key: (1,12)
--    │    ├── fd: ()-->(3), (1)-->(2), (12)-->(17)
--    │    ├── distribution: us-east1
--    │    ├── index-join s
--    │    │    ├── columns: s.k:1 s.a:2 b:3
--    │    │    ├── stats: [rows=10, distinct(3)=1, null(3)=0]
--    │    │    ├── cost: 89.7400007
--    │    │    ├── key: (1)
--    │    │    ├── fd: ()-->(3), (1)-->(2)
--    │    │    ├── distribution: us-east1
--    │    │    ├── prune: (1,2)
--    │    │    └── scan s@s_b_idx
--    │    │         ├── columns: s.k:1 b:3
--    │    │         ├── constraint: /3/1: [/10 - /10]
--    │    │         ├── stats: [rows=10, distinct(3)=1, null(3)=0]
--    │    │         ├── cost: 28.8200001
--    │    │         ├── key: (1)
--    │    │         ├── fd: ()-->(3)
--    │    │         └── distribution: us-east1
--    │    └── filters (true)
--    └── filters
--         └── s.a:2 @> t.a:7 [outer=(2,7), immutable]
-- (41 rows)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129867#-:-O5ZS5w5Br3kIdXhlGks:b-ld487q)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129867#-O5Uwyj56bd6wgQhBf2Y:-O5ZQEe60hb4fyYt3mL3:b-f6nk8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f733ea6ab2c557e161c1ed7bc717b0a67be46ea/pkg/sql/opt/memo/logical_props_builder.go#L144)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Wouldn't any filters still apply? Like, `x > 5` is true even if `x` gets duplicated.
</blockquote></details>

Great catch, there's no need to change the partial index logic here. The keys add below are fine too since they include the inverted key columns, e.g., for a scan of `INVERTED INDEX (j) WHERE ...` the key `(j_inverted_key, <pk-cols>)` will be added.

I reverted this change and I also added a TODO above that mentions how we could add a key including the inverted key columns and PK columns to multi-key inverted index scans. I don't see any need to do that now though.

**Comment by DrewKimball** [comment]
>I actually see no problems with inverted joins. @DrewKimball lmk if you disagree, if not I'll merge.

Sounds good, LGTM

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
