### PR TITLE
stop,log: tracing improvements

### PR DESCRIPTION
**Pull request by andreimatei**
Improvements around making the traces of long-running background processes look better. See individual commits.

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @aayushshah15

**Comment by tbg** [comment]
Going to leave the review to @abarganier but feel free to loop me into specific parts of the review where I can be helpful.

**Review by abarganier — COMMENTED** [review]
The tracing changes overall lgtm, just a couple small comments, but I'd also like to hear from someone better versed in KV about the changes to the Stopper usage. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-:-MkJTMDx2lKSLmr0vE5c:bmx4rre)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @andreimatei)

___
*[pkg/util/stop/stopper.go, line 161 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-MkJSwPJ67kXgF9FT-QG:-MkJSwPJ67kXgF9FT-QH:bzqxxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c92ecb9c37a61999b87b09486cae14ad3ab4e85b/pkg/util/stop/stopper.go#L161)):*
> ```
> 	tracer   *tracing.Tracer   // tracer used to create spans for tasks
> ```
Does this need to be protected by a mutex if we're going to expose methods like `SetTracer()`?
___
*[pkg/util/tracing/tracer.go, line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-MkJRa4JEm1xeFiUI9gN:-MkJRa4JEm1xeFiUI9gO:b-4b9mba) ([raw file](https://github.com/cockroachdb/cockroach/blob/c92ecb9c37a61999b87b09486cae14ad3ab4e85b/pkg/util/tracing/tracer.go#L293)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> type registry struct {
> 	mu struct {
> 		syncutil.Mutex
> 		spansPerTrace map[uint64]traceInfo
> 	}
> }
> 
> type traceInfo struct {
> 	rootName   string
> 	remoteRoot bool
> 	spans      int
> }
> ```
</details>

nit: can we add some comments about the purpose of this registry?

**Comment by andreimatei** [comment]
First two commits are #70850.

I've reworked much of this; decided to go a different way. I've reduced the control one has at the point where it creates a child span, in favor of affording a new option at the point where a parent span is created. I've introduced the concept of a span that cannot have any children, to model a long-running task. Long-running operations getting children leads to too many problems.
This time, I'd like to kindly ask @aayushshah15 for a review.

**Review by aayushshah15 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-:-MkyOw104O00YJ69mL62:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @abarganier, and @andreimatei)

___
*[pkg/kv/kvserver/replica_range_lease.go, line 359 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-MkyM7kq-RTiJc-O8Qeu:-MkyM7kq-RTiJc-O8Qev:b6rvwua) ([raw file](https://github.com/cockroachdb/cockroach/blob/213bc1755dad735b85b2b9520d1821d5b6e07c59/pkg/kv/kvserver/replica_range_lease.go#L359)):*
> ```Go
> 			// acquisition's trace in all of them, but let's at least include it in
> 			// the request that triggered it.
> 			SpanOpt: stop.ChildSpan,
> ```

This isn't necessarily related to this patch, but could you explain why this isn't a `FollowsFromSpan` relationship instead? 

Your comment above the `FollowsFromSpan` `SpanOption` says the following:
```
	// Use this when the caller will not wait for the task to finish, but a
	// relationship between the caller and the task might still be useful to
	// visualize in a trace collector. Generally avoid using this for tasks
```
___
*[pkg/util/tracing/span.go, line 270 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-MkyHJP19u7n7m-MJ85y:-MkyHJP19u7n7m-MJ85z:b-5qu734) ([raw file](https://github.com/cockroachdb/cockroach/blob/590bb4943d74f87f99634f572d8e3453e9ed0943/pkg/util/tracing/span.go#L270)):*
> ```Go
> 	// Note that this field is unlike all the other in that it doesn't make it
> 	// across the wire through a carrier. As can be seen in
> 	// Tracer.InjectMetaInto(carrier), is sterile is set, then we don't propagate
> ```

nit: `s/is sterile/if sterile`

**Review by andreimatei — COMMENTED** [review]
I've verified with `BenchmarkTracing` that this patch does not regress performance. In fact, it seems to marginally help it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-:-MlRCpyt5iPNWcynb9bE:b9tf3z9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @abarganier)

___
*[pkg/kv/kvserver/replica_range_lease.go, line 359 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-MkyM7kq-RTiJc-O8Qeu:-MlRA-hn-T2iGCtMWouU:b-jq4r9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/213bc1755dad735b85b2b9520d1821d5b6e07c59/pkg/kv/kvserver/replica_range_lease.go#L359)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

This isn't necessarily related to this patch, but could you explain why this isn't a `FollowsFromSpan` relationship instead? 

Your comment above the `FollowsFromSpan` `SpanOption` says the following:
```
	// Use this when the caller will not wait for the task to finish, but a
	// relationship between the caller and the task might still be useful to
	// visualize in a trace collector. Generally avoid using this for tasks
```
</blockquote></details>

`FollowsFromSpan` is not appropriate here because, even though the parent doesn't necessarily wait for the child, it does wait for the child in the normal path. And if you're looking at a trace for the parent, you want to see the lease acquisition in it. That's what the comment above is trying to say.
___
*[pkg/util/stop/stopper.go, line 161 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-MkJSwPJ67kXgF9FT-QG:-MkNUyB-DFLXLrDqk8wB:b-gsog8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c92ecb9c37a61999b87b09486cae14ad3ab4e85b/pkg/util/stop/stopper.go#L161)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> 	tracer   *tracing.Tracer   // tracer used to create spans for tasks
> ```
Does this need to be protected by a mutex if we're going to expose methods like `SetTracer()`?
</blockquote></details>

Well `SetTracer` is documented as not allowing calls concurrent with starting tasks.
The tracer is supposed to be passed before the stopper starts being generally used. I have tried making `WithTracer` the only way to supply it but, alas, I've failed because of the intricate way in which our `Server` is built up; the `Stopper` is instantiated by the `cli` layer, etc. I've tried to untangle the spaghetti, but failed.
___
*[pkg/util/tracing/span.go, line 270 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-MkyHJP19u7n7m-MJ85y:-MlRCmlPBpRiWjso89QD:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/590bb4943d74f87f99634f572d8e3453e9ed0943/pkg/util/tracing/span.go#L270)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

nit: `s/is sterile/if sterile`
</blockquote></details>

done
___
*[pkg/util/tracing/tracer.go, line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-MkJRa4JEm1xeFiUI9gN:-MkNVlbLDNkQ6ToBASwX:bekibcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c92ecb9c37a61999b87b09486cae14ad3ab4e85b/pkg/util/tracing/tracer.go#L293)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> type registry struct {
> 	mu struct {
> 		syncutil.Mutex
> 		spansPerTrace map[uint64]traceInfo
> 	}
> }
> 
> type traceInfo struct {
> 	rootName   string
> 	remoteRoot bool
> 	spans      int
> }
> ```
nit: can we add some comments about the purpose of this registry?
</blockquote></details>

This was unused debugging code. Deleted, thanks.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70370#-:-MlVDOYGAE8fD0uNTC44:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @abarganier)

**Pull request merged**
