### PR TITLE
raft: add raft fortification metrics

### PR DESCRIPTION
**Pull request by iskettaneh**
This commit sets the basis for metrics inside Raft. It links them
with the store registry. Future commits add some raft metrics.

This adds the following raft metrics:

**1) raft.fortification_resp.accepted:** Reports the number of fortification responses that are accepted.
**2) raft.fortification_resp.rejected:** Reports the number of fortification responses that are rejected.
**3) raft.fortification.skipped_no_support:** Reports the number of fortification requests that were skipped due to the lack of store liveness support.

References: #132754

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
:lgtm: modulo minor comments.

> Reviewed 9 of 9 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134543#-:-OC9Cn1IEarF8uwHHPfJ:bf2xk7o)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @iskettaneh, and @srosenberg)

___
*[`pkg/kv/kvserver/store.go` line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134543#-OC9BRS3578sg_1ntKR5:-OC9BRS48DIfOic3hOvI:bp8dgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2503cacdb74f825b7e2a1dde8d0e341846e7138/pkg/kv/kvserver/store.go#L391)):*
> ```Go
> 	logger raftlogger.Logger,
> 	storeLiveness raftstoreliveness.StoreLiveness,
> 	raftMetrics *raft.Metrics,
> ```

nit: s/raftMetrics/metrics/g
___
*[`pkg/raft/metrics.go` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134543#-OC9C4UJ11FUfqS-eJEO:-OC9C4UJ11FUfqS-eJEP:barp55h) ([raw file](https://github.com/cockroachdb/cockroach/blob/18fb61737ba2ac03c1b347a181bdb5e51c662aab/pkg/raft/metrics.go#L20)):*
> ```Go
> func NewMetrics() *Metrics {
> 	return &Metrics{
> 		AcceptedFortificationResponses: metric.NewCounter(
> ```

nit: instead of instantiating these in-line, consider following the pattern here: https://github.com/cockroachdb/cockroach/blob/9887452d54c30a1e10ce9de8c650cf0bc082727e/pkg/kv/kvserver/metrics.go#L42-L49

We use this in ~most places for metrics.
___
*[`pkg/raft/metrics.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134543#-OC9CRtZEBmzr96RClbu:-OC9CRtZEBmzr96RClbv:bl11i9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/18fb61737ba2ac03c1b347a181bdb5e51c662aab/pkg/raft/metrics.go#L23)):*
> ```Go
> 			metric.Metadata{
> 				Name:        "raft.fortification_resp.accepted",
> 				Help:        "The number of accepted fortification responses",
> ```

nit: "fortification responses. Calculated on the raft leader"

(same below)
___
*[`pkg/raft/metrics.go` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134543#-OC9Cd-S0WmQlKzEl3sZ:-OC9Cd-S0WmQlKzEl3s_:bn63udq) ([raw file](https://github.com/cockroachdb/cockroach/blob/18fb61737ba2ac03c1b347a181bdb5e51c662aab/pkg/raft/metrics.go#L41)):*
> ```Go
> 			metric.Metadata{
> 				Name: "raft.fortification.skipped_no_support",
> 				Help: "The number of fortification requests that were skipped due to lack of store" +
> ```

nit: "skipped (not sent)"

**Comment by iskettaneh** [comment]
TFTR!

bors r+

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134543#-:-OCAeIkDAAL--DV0H_ap:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @iskettaneh, and @srosenberg)

**Comment by iskettaneh** [comment]
TFTR!

bors r+

**Comment by arulajmani** [comment]
blathers backport 24.3

**Pull request merged**
