### PR TITLE
storage: compute correct heartbeat interval for node liveness

### PR DESCRIPTION
**Pull request by spencerkimball**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12232)

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by spencerkimball** [comment]
This fix broke two unittests. I added comments explaining the breakages and the fixes.

**Comment by tamird** [comment]
Looks like you only updated one test?

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/client_raft_test.go, line 1656 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-KYnclGGd4lFZ9xAmRIs-r1-1656:-KYngGtAWF8S7axqBtrx:b-2rbain) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5acebe63ec02eba6d1efe6ac20bce8f72dc04be/pkg/storage/client_raft_test.go#L1656)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

This test was previously relying on the too-frequent heartbeating to force the range to realize that the follower replica is unreachable.
</blockquote></details>

What does it mean to "realize" the follower was lost? I thought that's what the ticks below were for.

---

*[pkg/storage/node_liveness.go, line 204 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-KY_XgYh7XKXvRPEmbyD-r1-204:-KYngczLpT2zZjnthsrr:b-t9zuwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5acebe63ec02eba6d1efe6ac20bce8f72dc04be/pkg/storage/node_liveness.go#L204)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

We need to add in max offset or else nodes will be considered not live sooner than expected for very small heartbeat intervals, assuming the max offset stays at 250ms.
</blockquote></details>

should probably be a comment in the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-:-KYnghE6GQiEjhtejqXq:b7q7x83)*

**Comment by tamird** [comment]
Looks like you need a rebase to pick up #12269.

**Comment by spencerkimball** [comment]
Only one test needed updating. The other was the fix in `node_liveness.go` to add `Clock.MaxOffset()` to the expiration duration.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/client_raft_test.go, line 1656 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-KYnclGGd4lFZ9xAmRIs-r1-1656:-KYo9sTwBNikuOrozHF6:b2a8hbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5acebe63ec02eba6d1efe6ac20bce8f72dc04be/pkg/storage/client_raft_test.go#L1656)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

What does it mean to "realize" the follower was lost? I thought that's what the ticks below were for.
</blockquote></details>

Raft needs to discover it can't reach a follower due to the circuit breaker having tripped, which it will only do when it tries to propose a command. Otherwise it will quiesce before the heartbeat can be tested, which breaks the test. I've updated the comment.

---

*[pkg/storage/node_liveness.go, line 204 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-KY_XgYh7XKXvRPEmbyD-r1-204:-KYoBBnCHw6gbUPEOz9A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5acebe63ec02eba6d1efe6ac20bce8f72dc04be/pkg/storage/node_liveness.go#L204)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

should probably be a comment in the code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-:-KYo9jgyzc2SRlSAdpMm:bjsfnuy)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/client_raft_test.go, line 1656 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-KYnclGGd4lFZ9xAmRIs-r1-1656:-KYoCuYyFUs2F8-G3TkW:b-fvd0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5acebe63ec02eba6d1efe6ac20bce8f72dc04be/pkg/storage/client_raft_test.go#L1656)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

Raft needs to discover it can't reach a follower due to the circuit breaker having tripped, which it will only do when it tries to propose a command. Otherwise it will quiesce before the heartbeat can be tested, which breaks the test. I've updated the comment.
</blockquote></details>

cc @petermattis: @spencerkimball and I discussed this in person, and according to @spencerkimball, in the absence of this increment, the range quiesces during the `for` loop below - this seems sketchy to me because quiesence is implemented by sending a special heartbeat, and unreachability of any node during this heartbeat prevents quiesence (https://github.com/cockroachdb/cockroach/blob/b1357d0e487d065b69b4f24a64c1150ab14e33ea/pkg/storage/replica.go#L2907-L2912).

However, if the `Quiesce: true` is already in flight by the time the circuit breaker is tripped above, then this increment serves to unquiesce the range, and thus fix the test. In other words I think this comment should read "Send a command to unquiesce the range in case it has quiesced, which would prevent ...".

Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-:-KYoFTYzqygFfTAOQiw2:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/client_raft_test.go, line 1656 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-KYnclGGd4lFZ9xAmRIs-r1-1656:-KYoGTc39-F2JqvegIqF:b-8yljwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5acebe63ec02eba6d1efe6ac20bce8f72dc04be/pkg/storage/client_raft_test.go#L1656)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

cc @petermattis: @spencerkimball and I discussed this in person, and according to @spencerkimball, in the absence of this increment, the range quiesces during the `for` loop below - this seems sketchy to me because quiesence is implemented by sending a special heartbeat, and unreachability of any node during this heartbeat prevents quiesence (https://github.com/cockroachdb/cockroach/blob/b1357d0e487d065b69b4f24a64c1150ab14e33ea/pkg/storage/replica.go#L2907-L2912).

However, if the `Quiesce: true` is already in flight by the time the circuit breaker is tripped above, then this increment serves to unquiesce the range, and thus fix the test. In other words I think this comment should read "Send a command to unquiesce the range in case it has quiesced, which would prevent ...".

Thoughts?
</blockquote></details>

Either comment is fine. @tamird's proposed comment is inaccurate in that the range might not have quiesced yet so the increment will only prevent quiescence in the future. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-:-KYoGnTNZVo_4aWh7Pj3:bnfp4nl)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/client_raft_test.go, line 1656 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-KYnclGGd4lFZ9xAmRIs-r1-1656:-KYoHH9vChrE9q9ttjzz:bdjicc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5acebe63ec02eba6d1efe6ac20bce8f72dc04be/pkg/storage/client_raft_test.go#L1656)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Either comment is fine. @tamird's proposed comment is inaccurate in that the range might not have quiesced yet so the increment will only prevent quiescence in the future. 
</blockquote></details>

The increment can't "prevent quiescence" because if the range is not yet quiesced at this point, it will not be able to quiesce because of the unreachability of the follower.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/client_raft_test.go, line 1656 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232#-KYnclGGd4lFZ9xAmRIs-r1-1656:-KYoJBzABBokMh1UWZ1k:bgyoqoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5acebe63ec02eba6d1efe6ac20bce8f72dc04be/pkg/storage/client_raft_test.go#L1656)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

The increment can't "prevent quiescence" because if the range is not yet quiesced at this point, it will not be able to quiesce because of the unreachability of the follower.
</blockquote></details>

We could also explicitly disable quiescence for this test. It isn't terribly important to be testing quiescence here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12232)*

**Pull request merged**
