### PR TITLE
sql: Improve efficiency of sorting queries in the presence of limiting

### PR DESCRIPTION
**Pull request by nvb**
We can improve the efficiency of in-memory sorting for `sortNodes` in both
the presence of a hard limit and the presence of a soft limit. This is accomplished
by adding two new sorting strategies to the `sortNode`, the first sorting only the
top-k when given a hard limit, and the second streaming the sort so that it can
terminate when a soft limit is reached at a higher `planNode`.

Given a query with `n` returned rows and a limit to `k` rows...
##### Example:

`SELECT DISTINCT v FROM kv ORDER BY v LIMIT 10`
##### Strategy:

Use a streaming heap sort, which can terminate once the soft limit is reached
by a wrapping `planNode`. This is achieved by using a min-heap to sort a
`valuesNode`. The heap is heapified initially, and for each call to `sortNode.Next`,
the next value is popped off the top of the heap and returned.
##### Time complexity:

The worst case time complexity of this approach remains `O(n log(n))`, but the average
time complexity of the sorting improves by a factor of `n/k`.
##### Space complexity:

The space complexity of the new approach will remain `O(n)`.
##### Example:

`SELECT v FROM kv ORDER BY v LIMIT 10`
##### Strategy:

Use a max-heap to keep track of the top `k` values as we iterate through the incoming
values from the wrapped `planNode`. We only need to make a copy of the values if the
new value is "less" than the value on the top of the heap. In this case, we can replace
the top value, keeping the max heap at size `k`. If a new value is not less than the
value at the top of the heap, we car drop it on the floor without making a deep copy and
without adding it to the `valuesNode`. At the end, we pop all values off the top of
the heap, which will sort the values in-place in the underlying slice.
##### Time complexity:

The worst case time complexity of this approach improves to `O(n log(k))`. This is
because all sorting operations work only on the size `k` heap.
##### Space complexity:

The space complexity of the new approach improves to `O(k)` because the `valuesNode` will
only ever grow to size `k`. The worst case number of values deep copies is still `n` times
if the incoming values are sorted in reverse and the heap is replaced each time. However,
on average the number of these deep copies will be reduced dramatically.
### Performance gains:

Note that below, `BenchmarkSort100000Limit10_Cockroach` will use a hard limit and
`BenchmarkSort100000Limit10Distinct_Cockroach` will use a soft limit.

```
name                                   old time/op    new time/op    delta
Sort100000Limit10_Cockroach-4             908ms ± 6%     815ms ± 7%  -10.31%  (p=0.000 n=8+8)
Sort100000Limit10Distinct_Cockroach-4     917ms ± 1%     810ms ± 6%  -11.67%  (p=0.001 n=6+8)

name                                   old alloc/op   new alloc/op   delta
Sort100000Limit10_Cockroach-4             143MB ± 0%     126MB ± 0%  -12.20%  (p=0.001 n=8+6)
Sort100000Limit10Distinct_Cockroach-4     143MB ± 0%     143MB ± 0%     ~     (p=0.081 n=8+6)

name                                   old allocs/op  new allocs/op  delta
Sort100000Limit10_Cockroach-4             1.81M ± 0%     1.75M ± 0%   -3.33%  (p=0.001 n=8+6)
Sort100000Limit10Distinct_Cockroach-4     1.81M ± 0%     1.81M ± 0%   -0.00%  (p=0.043 n=8+7)
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5318)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I made a number of pretty substantial changes here, including getting `explain (debug)` working by splitting the sorting types into their own `sortingStrategy` interface which allows iterative value population. This will allow us to play around with more efficient sorting algorithms in relative isolation later. PTAL.

**Comment by RaduBerinde** [comment]
This is awesome. The change looks great! Just some minor comments. We also need query tests for all strategies (you are probably working on that).

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/sort.go, line 237 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4Jde5mQdY2EDirZk3:-KD4Jde5mQdY2EDirZk4:1584165349) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L237)):*
I am not sure this will always the case. Mabe if we somehow have a LIMIT inside a LIMIT we may want to have the outer limit trickle through and that would involve calling it twice (of course, still before the first Next). I would just remember the limit and initialize the strategy on the first Next (we're already doing a bit of initialization there).

---

*[sql/sort.go, line 347 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD3v-5Sc0XPnUnuMlnV:-KD3v-5TPdg3hIenzrr5:-983519564) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L347)):*
Add a comment explaining that through this interface we either retrieve values from a sorting strategy or from the planNode we wrap

---

*[sql/sort.go, line 362 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD3vN_gLDX82wkGn7mk:-KD3vN_gLDX82wkGn7ml:1298361681) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L362)):*
This usually comes first

---

*[sql/sort.go, line 405 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4KP41s5wxi_N-3Xw-:-KD4KP41s5wxi_N-3Xw0:-683792871) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L405)):*
I would just say "If the underlying node provides n rows and we produce k rows, the time complexity is O(n + k log n)".

---

*[sql/sort.go, line 471 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4L8FdcWJXsLZQsZXW:-KD4L8Fek0Ji_6_24N7M:-1448997782) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L471)):*
linear

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-:-KD4LXqqfsPL4cuUHohL:2024856499)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 1 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[sql/bench_test.go, line 674 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4MysFnEcFOohdKIvk:-KD4MysFnEcFOohdKIvl:-1002498122) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d712d35c92a60840b9044e9cb664598cf38367/sql/bench_test.go#L674)):*
something about the grammar here

---

*[sql/bench_test.go, line 697 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4N5iz2iQjFGIBynAU:-KD4N5iz2iQjFGIBynAV:381926458) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d712d35c92a60840b9044e9cb664598cf38367/sql/bench_test.go#L697)):*
you can hoist a lot of this out of the loop

also maybe just `var dist string` on this line

---

*[sql/sort.go, line 360 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4aEX6QhdmOOIrATBV:-KD4aEX6QhdmOOIrATBW:1169787613) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L360)):*
s/guarantees/guaranteed/ but also perhaps indicate that it should not be called more than once since this doc is for both implementers and consumers of this API.

---

*[sql/sort.go, line 366 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4aWjkUXdSMLvbTo7k:-KD4aWjkUXdSMLvbTo7l:733953765) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L366)):*
s/a quicksort/sort.Sort/

---

*[sql/sort.go, line 450 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4amYmIht6ruUOgzuU:-KD4amYmIht6ruUOgzuV:989614043) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L450)):*
nit: strconv.Itoa is more performant

---

*[sql/values.go, line 143 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4WjXFhKcic-1o_ozv:-KD4WjXFhKcic-1o_ozw:1414368453) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/values.go#L143)):*
how come exported?

---

*[sql/values.go, line 170 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4XJSlb0njidskJxqp:-KD4XJSlb0njidskJxqq:1943953574) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/values.go#L170)):*
you should add a static assertion `var _ heap.Interface = (*valuesNode)(nil)`

---

*[sql/values.go, line 177 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4XBggRQRSqskTcX7y:-KD4XBggRQRSqskTcX7z:1414368453) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/values.go#L177)):*
how come exported?

---

*[sql/values.go, line 194 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4XANfMlkrdrAKLoG6:-KD4XANfMlkrdrAKLoG7:1414368453) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/values.go#L194)):*
how come exported?

---

*[sql/values.go, line 200 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4XEIowKH5z8c6_2Z1:-KD4XEIowKH5z8c6_2Z2:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/values.go#L200)):*
ditto

---

*[sql/values.go, line 206 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4XF53uTzy9DEEg6uX:-KD4XF53uTzy9DEEg6uY:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/values.go#L206)):*
ditto

---

*[sql/values.go, line 212 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4XFooBp-EdBP5oNMc:-KD4XFooBp-EdBP5oNMd:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/values.go#L212)):*
ditto

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318)*

**Comment by nvanbenschoten** [comment]
I addressed the comments and added a sorting strategy indicator to the `sortNode`'s ExplainPlan output. I also stubbed out an `onDiskSortStrategy` implementation of `sortingStrategy` to extract @petermattis's TODO.

---

Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[sql/bench_test.go, line 674 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4MysFnEcFOohdKIvk:-KD5MD_U1KDIOWAzYZNb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d712d35c92a60840b9044e9cb664598cf38367/sql/bench_test.go#L674)):*
Done.

---

*[sql/bench_test.go, line 697 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4N5iz2iQjFGIBynAU:-KD5MRvZnoAuUiQT2eZX:920560637) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9d712d35c92a60840b9044e9cb664598cf38367/sql/bench_test.go#L697)):*
Hoisted here and above where applicable.

---

*[sql/sort.go, line 237 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4Jde5mQdY2EDirZk3:-KD5O31q7DmaSCoeysS5:-661098942) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L237)):*
Good point, we can get rid of that check. Either way, it's still works to initialize here and not maintain even more state.

---

*[sql/sort.go, line 347 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD3v-5Sc0XPnUnuMlnV:-KD5OwyycHI83e2hVHpp:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L347)):*
Done.

---

*[sql/sort.go, line 360 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4aEX6QhdmOOIrATBV:-KD5P8tz9_YITAolB1bs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L360)):*
Done.

---

*[sql/sort.go, line 362 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD3vN_gLDX82wkGn7mk:-KD5OIUcNJ8DKarrUslb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L362)):*
Done.

---

*[sql/sort.go, line 366 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4aWjkUXdSMLvbTo7k:-KD5PTcRwUhCxFaufyAC:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L366)):*
Done.

---

*[sql/sort.go, line 405 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4KP41s5wxi_N-3Xw-:-KD5PyvXoXNav5yyFs_h:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L405)):*
Done.

---

*[sql/sort.go, line 450 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4amYmIht6ruUOgzuU:-KD5Q4XNtSANESUvnkQ7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L450)):*
Done.

---

*[sql/sort.go, line 471 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4L8FdcWJXsLZQsZXW:-KD5Q5VBMbtb2WkUkhhv:-1857471228) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L471)):*
linear sorting time? I'm listening...

---

*[sql/values.go, line 170 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4XJSlb0njidskJxqp:-KD5QMEeGQbusr8GSuVC:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/values.go#L170)):*
Done.

---

*[sql/values.go, line 177 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4XBggRQRSqskTcX7y:-KD5QPg8Xkhr141HwrT1:383091082) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/values.go#L177)):*
Discussed in person. Because this is an unexpected type, exporting the methods that are part of the external API is ok.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-:-KD5Tl8KNs-dE8XppHgD:1933954382)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2, 2 of 3 files at r3, 1 of 3 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/sort.go, line 350 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD5YFvJApaIX7YY7rU4:-KD5YFvKdSeYDnwH-4hr:-352685740) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1411f118da3da9482043f9ac6fbb4d29cefe0c/sql/sort.go#L350)):*
you could (should?) make this explicit by embedding this interface in the planNode and putting those method comments here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318)*

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/sort.go, line 471 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD4L8FdcWJXsLZQsZXW:-KD5ZRytTpyzhAIJqegK:941605631) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c509f6c648d5edb1c17c4ffb626b6176c91ffb/sql/sort.go#L471)):*
ah haha didn't read carefully and didn't realize 'linearithmic' is a word, thought it was a typo :) don't mind me

---

*[sql/sort.go, line 230 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD5YCwZePieWHI0p-8_:-KD5YCwZePieWHI0p-8a:-643825748) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1411f118da3da9482043f9ac6fbb4d29cefe0c/sql/sort.go#L230)):*
I just realized, this name is very confusing. "Streaming" algorithms in general refers to algorithms that operate on streams and which maintain some kind of state which usually is less than the size of the stream. So it's actually the *other* strategy that I would call "streaming".

By the way - we could always use this strategy when there is no limit. Is there a reason to keep the "regular" sort? I guess the built-in sort is probably faster than the "vanilla" heap-sort we would end up doing?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/sort.go, line 536 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD6GYL2GxEXSxpTkuOP:-KD6GYL2GxEXSxpTkuOQ:18349283) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1411f118da3da9482043f9ac6fbb4d29cefe0c/sql/sort.go#L536)):*
Mind extending this with: `There is no point in doing this while we're buffering the entire result set in memory. If/when we start streaming results back to the client we should revisit.`

I think it is fine to leave the `type onDiskSortStrategy struct{}` commented out and remove all of the methods. No use in requiring others to keep those method signatures up to date while they aren't being used.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/sort.go, line 230 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD5YCwZePieWHI0p-8_:-KD6P1UMVQnYYmYQr8jq:-651236970) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1411f118da3da9482043f9ac6fbb4d29cefe0c/sql/sort.go#L230)):*
Yeah it's unfortunate that the term "streaming" is so overloaded. What I meant here was that we're sorting iteratively during each call to `Next` instead of all performing the entire sort upfront. Do you have any suggestions for a better name? `iterativeSortStrategy`?

And you're right in both accounts with regards to using the strategy without a limit. It is certainly possible and would work fine, but it is also substantially slower than the heavily optimized QuickSort/ShellSort/InsertionSort/HeapSort hybrid found in [`sort.Sort`](https://golang.org/pkg/sort/#Sort).

---

*[sql/sort.go, line 350 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD5YFvJApaIX7YY7rU4:-KD6N2jbW3jhmXQrGAiK:1410676646) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1411f118da3da9482043f9ac6fbb4d29cefe0c/sql/sort.go#L350)):*
I think it's ok to allow duck typing to enforce this interface equivalence without needing any explicit inheritance. It's a compile time check so it's seems safe to me, and I also think it makes the abstraction's purpose clearer in the given context (similar to why an anonymous interface would be used). That said, if we need this abstraction in other `planNode`s later, then it would make sense to reconsider.

---

*[sql/sort.go, line 536 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD6GYL2GxEXSxpTkuOP:-KD6Oukix_IGEdjHwYIf:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1411f118da3da9482043f9ac6fbb4d29cefe0c/sql/sort.go#L536)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/sort.go, line 230 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD5YCwZePieWHI0p-8_:-KD8xO-LI1fxnUFno6IF:503662108) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1411f118da3da9482043f9ac6fbb4d29cefe0c/sql/sort.go#L230)):*
If the built-in sort is substantially faster than heapsort, maybe it's worth trying out the selection solution (which would use the built-in sort for the top k). 

I worked on it today - here is some code that moves the top k elements to front. It's based on the randomized selection algorithm.
https://github.com/RaduBerinde/cockroach/pull/2

This could be used for both cases. For the hard limit, we call `moveTopKToFront` and throw away the rest of the rows every time we have >= 2K rows. For the soft limit, after getting all the rows we can call `moveTopKToFront`once and sort the first K rows. If we need more rows than that, we call it again for the next 2K rows and sort those. And so on.

You can try it out if you want. If you think it's useful, I can work on making it into a real change and merge it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318)*

**Comment by nvanbenschoten** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/sort.go, line 230 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-KD5YCwZePieWHI0p-8_:-KDBJ2F91S34Ol9QJP99:-1562035104) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1411f118da3da9482043f9ac6fbb4d29cefe0c/sql/sort.go#L230)):*
Renamed `streamingSortStrategy` to `iterativeSortStrategy`. 

Moving the rest of this discussion to #5387.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5318#-:-KDB_WtGO05e094oAaAW:1417088721)*

**Pull request merged**
