### PR TITLE
kvcoord: avoid concurrent rollbacks when making parallel commits explicit

### LINKED ISSUE #68643: kv: async rollback failed: concurrent txn use detected
Seen in #68641, this shouldn't really happen as concurrent txn use is disallowed. Possible fallout from #65592.

```
I210810 12:22:16.921367 43557 sql/distsql_running.go:426 ⋮ [n3,client=‹10.12.27.29:49614›,hostnossl,user=root] 403  ‹client rejected when attempting to run DistSQL plan›: ‹TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_CLIENT_REJECT): "sql txn" meta={id=ff7a9548 key=/Table/54/1/1811/6/0 pri=0.01768759 epo=1 ts=1628598132.825983727,2 min=1628598125.728719600,0 seq=1} lock=true stat=PENDING rts=1628598129.683572747,2 wto=false gul=1628598126.228719600,0›
I210810 12:22:19.042810 45155 sql/distsql_running.go:426 ⋮ [n3,client=‹10.12.27.29:50466›,hostnossl,user=root] 404  ‹client rejected when attempting to run DistSQL plan›: ‹TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_CLIENT_REJECT): "sql txn" meta={id=66f3e10b key=/Table/54/1/2057/7/0 pri=0.04311875 epo=4 ts=1628598134.239248724,2 min=1628598110.200107081,0 seq=1} lock=true stat=PENDING rts=1628598132.772955506,2 wto=false gul=1628598110.700107081,0›
I210810 12:22:20.491238 44838 sql/distsql_running.go:426 ⋮ [n3,client=‹10.12.27.29:50338›,hostnossl,user=root] 405  ‹client rejected when attempting to run DistSQL plan›: ‹TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_CLIENT_REJECT): "sql txn" meta={id=57703863 key=/Table/54/1/521/9/0 pri=0.04525804 epo=3 ts=1628598136.378263270,2 min=1628598117.245551919,0 seq=1} lock=true stat=PENDING rts=1628598135.122949963,2 wto=false gul=1628598117.745551919,0›
I210810 12:22:26.437085 529 2@util/log/event_log.go:32 ⋮ [n3] 406 ={"Timestamp":1628598146437083218,"EventType":"runtime_stats","MemRSSBytes":14263345152,"GoroutineCount":7793,"MemStackSysBytes":409829376,"GoAllocBytes":1798487688,"GoTotalBytes":3673110728,"GoStatsStaleness":0.07168167,"HeapFragmentBytes":602431864,"HeapReservedBytes":670654464,"HeapReleasedBytes":75366400,"CGoAllocBytes":8742897680,"CGoTotalBytes":10692587520,"CGoCallRate":42937.785,"CPUUserPercent":1510.8174,"CPUSysPercent":59.281063,"GCPausePercent":0.06172096,"GCRunCount":724,"NetHostRecvBytes":100127756,"NetHostSendBytes":105433854}
I210810 12:22:36.440265 529 2@util/log/event_log.go:32 ⋮ [n3] 407 ={"Timestamp":1628598156440263350,"EventType":"runtime_stats","MemRSSBytes":14286200832,"GoroutineCount":8520,"MemStackSysBytes":498794496,"GoAllocBytes":2057548656,"GoTotalBytes":3664599240,"GoStatsStaleness":0.07483672,"HeapFragmentBytes":367938704,"HeapReservedBytes":548610048,"HeapReleasedBytes":83877888,"CGoAllocBytes":8744091520,"CGoTotalBytes":10739941376,"CGoCallRate":45537.72,"CPUUserPercent":1502.9221,"CPUSysPercent":60.180862,"GCPausePercent":0.07044873,"GCRunCount":732,"NetHostRecvBytes":102667530,"NetHostSendBytes":107410237}
I210810 12:22:37.908512 10662767 kv/txn.go:817 ⋮ [n3] 408  async rollback failed: concurrent txn use detected. ba: EndTxn(commit:false) [‹/Table/54/1/605/4/0›], [txn: bf99f2af]
I210810 12:22:37.944303 10663206 kv/txn.go:817 ⋮ [n3] 409  async rollback failed: concurrent txn use detected. ba: EndTxn(commit:false) [‹/Table/54/1/914/6/0›], [txn: 049fd86d]
I210810 12:22:37.957563 10663130 kv/txn.go:817 ⋮ [n3] 410  async rollback failed: concurrent txn use detected. ba: EndTxn(commit:false) [‹/Table/54/1/524/6/0›], [txn: f4ba4c49]
```

### PR DESCRIPTION
**Pull request by erikgrinaker**
`TxnCoordSender` allows `EndTxn(commit=false)` rollback requests even if
the transaction state is finalized, since clients can send multiple
rollbacks (e.g. due to context cancellation). However, it allowed this
even when the transaction was committed. This could pass the request
through while the `txnCommitter` was asynchronously making an implicit
commit explicit, which would violate the `txnLockGatekeeper` requirement
that transaction requests are synchronous (non-concurrent) which would
return an unexpected error for the rollback.

This patch rejects additional `EndTxn(commit=false)` requests if the
finalized transaction is known to be committed, to prevent this race
condition. If rejected, the returned error is of the same type that
would be returned by `EndTxn` evaluation, although with a different
message string.

Note that even though the returned error should really have
`REASON_TXN_COMMITTED` in this case, which is also what `txn.Rollback()`
expects in order to omit logging, the current `EndTxn` code incorrectly
returns `REASON_TXN_UNKNOWN` in this case. This behavior is retained to
minimize the change, but should be corrected separately.

Resolves #68643.
Informs #69965.

Release justification: fixes for high-priority or high-severity bugs in existing functionality
Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Opened #69965 to fix the invalid error reason. As outlined on the issue, I think we should consider combining all of these related status errors into a single status error that contains the actual txn status.

**Review by nvb — APPROVED** [review]
:lgtm: nice find! Do you intend to backport this to previous release branches as well?

> As outlined on the issue, I think we should consider combining all of these related status errors into a single status error that contains the actual txn status. Wdyt?

Cleaning up the treatment of `TransactionStatusError` would be lovely. It seems to be used in a handful of different situations, and only a few actually expect the error to be structured In many other places, it's hardly more than a transaction-related `errors.AssertionFailedf`. The place to start might be to switch some of the uses over to `errors.AssertionFailedf` and then get rid of `REASON_UNKNOWN` in the remaining ones by introducing new reasons.

I'm less sure about merging `TransactionAbortedError` into `TransactionStatusError`. `TransactionAbortedError` has a more well-defined meaning and is an important part of the transaction retry story. The `Reason` field it carries is also important to clients. So I don't imagine it being particularly easy to switch over, especially given migration concerns. It's also not clear to me that the finished state would be cleaner than what we have today if it meant that clients would need to peek inside `TransactionStatusError`s to detect aborts.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69966#-:-MjGuyls2TxYS71gF8rn:bofj4c2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by erikgrinaker — COMMENTED** [review]
>Do you intend to backport this to previous release branches as well?

Yes, to 21.2. It does not apply to 21.1 and earlier, since they explicitly allow concurrent `EndTxn(commit=false)` requests -- the bug fix that serialized them was not backported.

>Cleaning up the treatment of `TransactionStatusError` would be lovely. It seems to be used in a handful of different situations, and only a few actually expect the error to be structured In many other places, it's hardly more than a transaction-related `errors.AssertionFailedf`. The place to start might be to switch some of the uses over to `errors.AssertionFailedf` and then get rid of `REASON_UNKNOWN` in the remaining ones by introducing new reasons.

Good idea, I'll add this to the issue and do a pass.

>I'm less sure about merging `TransactionAbortedError` into `TransactionStatusError`. `TransactionAbortedError` has a more well-defined meaning and is an important part of the transaction retry story. The `Reason` field it carries is also important to clients. So I don't imagine it being particularly easy to switch over, especially given migration concerns. It's also not clear to me that the finished state would be cleaner than what we have today if it meant that clients would need to peek inside `TransactionStatusErrors` to detect aborts.

Sure, might be more trouble than it's worth.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69966#-:-MjTFy9C6ZcKvwTr0Xfs:bki904q)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69966#-:-MjUhJGi6dgVrVwSJQVg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by erikgrinaker** [comment]
bors r=nvanbenschoten

TFTR!

**Review by andreimatei — COMMENTED** [review]
I've read https://github.com/cockroachdb/cockroach/issues/68643#issuecomment-915276136, but do you mind explaining to me how the rollback is sent if the `makeTxnCommitExplicitAsync()` point was reached? It seems to me that the `ConnExecutor` should consider the txn to be committed, so I'm surprised that a rollback is sent. I understand that there's a ctx cancellation at play, I'd expect that if `makeTxnCommitExplicitAsync()` is reached then cancellation should not play a role.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69966#-:-MjUnNqVCj4lJIGBFfZs:b1m9yfb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by erikgrinaker — COMMENTED** [review]
I'm not too familiar with `connExecutor` and haven't looked closely at the failure modes there. However, it doesn't seem entirely implausible that a context cancellation while the response is in flight could cause a race where a rollback is sent. It's also the only explanation I could find for the log messages in the original issue, but it's absolutely possible that there are other failure modes that I haven't found yet. If you think it's worthwhile I can spend some time to dig through the `connExecutor` code and see if I find an explanation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69966#-:-MjUw9ON0frhbutBpJuv:bkgabtw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69966)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go, line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69966#-MjVA39fDJCI3jfudI_A:-MjVA39fDJCI3jfudI_B:b-7id8dg) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a94c89e23cc4cfa2dc3565126752bc27107a74/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L440)):*
> ```Go
> 	<-readyC
> 
> 	// From the TxnCoordSender's point of view, the txn is implicitly committed,
> ```

I'd remove the talk of the `connExecutor` here since it's not clear that the `connExecutor` behaves as this implies.

**Review by erikgrinaker — COMMENTED** [review]
Canceled to add stack traces for the unexpected `EndTxn(commit=false)` requests as well, at @andreimatei's request.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69966#-:-MjVGFRW2jMnK1p-bKbn:bcal9uf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go, line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69966#-MjVA39fDJCI3jfudI_A:-MjVAhMu-lg_hoWajisH:b-s3f4d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a94c89e23cc4cfa2dc3565126752bc27107a74/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L440)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd remove the talk of the `connExecutor` here since it's not clear that the `connExecutor` behaves as this implies.
</blockquote></details>

Done.

I see that `Txn.Rollback()` can be called indirectly in a handful of other places as well, mainly during `COPY` operations and range merges -- it's worth giving these a closer look.

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69966#-:-MjVH4Xb4Iaj0cDmeE1j:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

**Comment by erikgrinaker** [comment]
bors r=nvanbenschoten,andreimatei

TFTRs!

**Comment by erikgrinaker** [comment]
Failure seems unrelated, even though the same test failed for both bors runs (`acceptance/cli/node-status`). It passes locally. It's failing on `master` as well, see #70169.

bors r=nvanbenschoten,andreimatei

**Pull request merged**
