### PR TITLE
util/log: split test logs by default into multiple files

### PR DESCRIPTION
**Pull request by knz**
All commits but the last from #69955 and prior.
Informs #69765 (point 1).

In the simple case when `-show-logs` is NOT used, when a test fails
all the logging output is merged into a single log file.

This makes investigations somewhat difficult because the combined
output from all channels is extremely verbose.

This patch changes this to ensure that multiple files are used
instead. It redirects the STORAGE and HEALTH channel in this
default, "silent" case to their own separate files.

We also include a copy of the events at severity WARNING or higher
into the default log file used by all other channels.

Release justification: non-production code changes

### CODE REVIEW

**Review by rauchenstein — DISMISSED** [review]
> Reviewed 30 of 31 files at r1, 3 of 35 files at r2, 1 of 4 files at r3, 28 of 31 files at r4, 4 of 6 files at r5, 2 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69958)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @rauchenstein)

___
*[pkg/util/log/clog.go, line 347 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjH4aK6-0d4e3PiTPrM:-MjH4aK6-0d4e3PiTPrN:b-que07v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f0de81781201f0a079b7e33313248548035ef44/pkg/util/log/clog.go#L347)):*
> ```Go
> 		// goroutine). These asynchronous log calls are concurrent with
> 		// the stderrSinkInfo update in (*TestLogScope).Close().
> 		if entry.sev < s.threshold[int(entry.ch)].Get() || !s.sink.active() {
> ```

Maybe threshold should be of a new type with a type-safe accessor instead of casting channels to int everywhere?
___
*[pkg/util/log/logconfig/config.go, line 741 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjGrHzr4C83yCmXVDT3:-MjGrHzr4C83yCmXVDT4:b-hof0un) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f0de81781201f0a079b7e33313248548035ef44/pkg/util/log/logconfig/config.go#L741)):*
> ```Go
> // FilterChannels is a constructor for ChannelFilters that
> // helps in tests.
> func FilterChannels(chs ...logpb.Channel) ChannelFilters {
> ```

Confusing name -- makes a new ChannelFilters, doesn't filter channels.  NewChannelFilters?
___
*[pkg/util/log/logconfig/config.go, line 782 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjGrVuHEVgUUAYNPupo:-MjGrVuHEVgUUAYNPupp:b-gyiasx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f0de81781201f0a079b7e33313248548035ef44/pkg/util/log/logconfig/config.go#L782)):*
> ```Go
> // severity by the proposed default; it also propagates the user
> // configuration into the other accessor fields.
> func (c *ChannelFilters) Update(defSev logpb.Severity) error {
> ```

I'd suggest decomposing this into

* a part which does the map transpose, filling out AllChannels and ChannelFilters (which can happen at unmashalling time, so that the presence of Severity_UNKNOWN is the ONLY way a freshly unmashalled value is invalid rather than having unset fields), and
* a function that can generally remap one severity to another, which we'd use to remap UNKNOWN to the default (and remove the entries from AllChannels if remapping to NONE).

As is, I also don't like the name "Update".  "Validate" is probably better.
___
*[pkg/util/log/logconfig/config.go, line 842 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjH-WM2ArAdJF5S3cF1:-MjH-WM35Nk1wQ2bJVuf:bunwk84) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f0de81781201f0a079b7e33313248548035ef44/pkg/util/log/logconfig/config.go#L842)):*
> ```Go
> // AllFiltered returns true if there are no channels listed or
> // all of them are filtered at level NONE.
> func (c ChannelFilters) AllFiltered() bool {
> ```

I sort of expected AllFiltered to return a list of all the filtered channels.  Perhaps IsAllFiltered or AreAllFiltered or FiltersAll.
___
*[pkg/util/log/logconfig/validate.go, line 189 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjGnPl0CM7b_0elRybq:-MjGnPl0CM7b_0elRybr:byell20) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f0de81781201f0a079b7e33313248548035ef44/pkg/util/log/logconfig/validate.go#L189)):*
> ```Go
> 		// have a filter yet.
> 		if err := fc.Channels.Update(fc.Filter); err != nil {
> 			fmt.Fprintf(&errBuf, "fluent server %q: %v\n", sinkName, err)
> ```

fluent -> http

**Review by knz — COMMENTED** [review]
Your review comments belong on #69715. I will answer them there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-:-MjUG4x0A9cQUX48JE2a:b8bgu0g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @rauchenstein)

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-:-MjUibZE-ftENL90056t:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @rauchenstein)

___
*[pkg/util/log/test_log_scope.go, line 188 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjUgKmH1kIrFycJLdMl:-MjUgKmH1kIrFycJLdMm:brysy86) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb9fbbb8ab2bb5e4e5e3e4eeec979bd717bfadfc/pkg/util/log/test_log_scope.go#L188)):*
> ```Go
> // getTestConfig initialize the logging configuration to parameters
> // suitable for use in tests.
> func getTestConfig(fileDir *string) (testConfig logconfig.Config, err error) {
> ```

consider taking the opportunity to write a comment for fileDir.

Also, I find it surprising that this can return an error. If that only happens for failure to validate the config that this function produces, and in turn if that can only happen because of static conditions, consider taking the opportunity to turn the validation into an assertion (panic) and remove the error return.
___
*[pkg/util/log/test_log_scope.go, line 232 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjUgxTv2JimSS1dQ5_0:-MjUgxTv2JimSS1dQ5_1:bizqzaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb9fbbb8ab2bb5e4e5e3e4eeec979bd717bfadfc/pkg/util/log/test_log_scope.go#L232)):*
> ```Go
> 		// Split the STORAGE and HEALTH channels into separate files.
> 		testConfig.Sinks.FileGroups = map[string]*logconfig.FileSinkConfig{
> 			"storage": {
> ```

I'd use channel.STORAGE, channel.HEALTH for the file group names.
___
*[pkg/util/log/test_log_scope.go, line 275 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjUhzTAEwWZ11sAfRs8:-MjUhzTAEwWZ11sAfRs9:b-vln5ht) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb9fbbb8ab2bb5e4e5e3e4eeec979bd717bfadfc/pkg/util/log/test_log_scope.go#L275)):*
> ```
> ensure all the logging output gets redirected to one file.
> ```

consider hinting at the default that this overrides. Also consider hinting at why a test might want to do this (is it only for tests of the logging system itself?)
___
*[pkg/util/log/test_log_scope.go, line 283 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjUhhOq9vzIXF1kgTtU:-MjUhhOq9vzIXF1kgTtV:bsuwlmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb9fbbb8ab2bb5e4e5e3e4eeec979bd717bfadfc/pkg/util/log/test_log_scope.go#L283)):*
> ```Go
> // log.ScopeWithoutShowLogs().
> func (l *TestLogScope) SetupSingleFileLogging(
> 	t interface{ Fatal(...interface{}) },
> ```

Consider panicking instead of taking this `t`.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 31 files at r10, 2 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69958)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @knz, and @rauchenstein)

___
*[pkg/util/log/test_log_scope.go, line 188 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjUgKmH1kIrFycJLdMl:-Mj_4nYd-Jbo2GDERkGE:b-o2ms94) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb9fbbb8ab2bb5e4e5e3e4eeec979bd717bfadfc/pkg/util/log/test_log_scope.go#L188)):*
> consider taking the opportunity to write a comment for fileDir.

done

>  If that only happens for failure to validate the config that this function produces, and in turn if that can only happen because of static conditions, consider taking the opportunity to turn the validation into an assertion (panic) and remove the error return.

Nice idea. Done.
___
*[pkg/util/log/test_log_scope.go, line 232 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjUgxTv2JimSS1dQ5_0:-Mj_6AuL1ZequxjEZrZn:b-mk8uei) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb9fbbb8ab2bb5e4e5e3e4eeec979bd717bfadfc/pkg/util/log/test_log_scope.go#L232)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd use channel.STORAGE, channel.HEALTH for the file group names.
</blockquote></details>

the strings here are the output file names.

"channel.STORAGE" is an int. Calling `.String()` on it doens't add any value engineering-wise.
___
*[pkg/util/log/test_log_scope.go, line 275 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjUhzTAEwWZ11sAfRs8:-Mj_6bqI5Yas_jh-VDlE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb9fbbb8ab2bb5e4e5e3e4eeec979bd717bfadfc/pkg/util/log/test_log_scope.go#L275)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> ensure all the logging output gets redirected to one file.
> ```

consider hinting at the default that this overrides. Also consider hinting at why a test might want to do this (is it only for tests of the logging system itself?)

</blockquote></details>

Done.
___
*[pkg/util/log/test_log_scope.go, line 283 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/69958#-MjUhhOq9vzIXF1kgTtU:-Mj_6auL3NIe_MNvVILk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb9fbbb8ab2bb5e4e5e3e4eeec979bd717bfadfc/pkg/util/log/test_log_scope.go#L283)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Consider panicking instead of taking this `t`.
</blockquote></details>

Done.

**Review by rauchenstein — COMMENTED** [review]
> Reviewed 26 of 31 files at r10, 4 of 16 files at r15, 4 of 10 files at r16, 1 of 8 files at r18, 3 of 3 files at r19, 3 of 3 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69958)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @rauchenstein)

**Review by rauchenstein — APPROVED** [review]
> Reviewed 12 of 16 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69958)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @rauchenstein)

**Comment by knz** [comment]
TFYR!

bors r=andreimatei,rauchenstein

**Pull request merged**
