### PR TITLE
opt: fix race caused by shared table annotations

### LINKED ISSUE #34904: opt: race in AssignPlaceholders
SHA: https://github.com/cockroachdb/cockroach/commits/acba091f04f3d8ecabf51009bf394951fbd3643c

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=scaledata/jobcoordinator/nodes=6 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1137872&tab=buildLog

```
The test failed on master:
	cluster.go:1585,scaledata.go:126,scaledata.go:53,test.go:1212: unexpected node event: 2: dead

```

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: test reproducing detached memo race

Test that reproduces #34904. Writing the test exposed a problem in the
`CopyAndReplace` API: there was no way to recursively copy a subtree
when creating an internal node. The API was reverted to the first
iteration Andy had in his PR.

Release note: None

#### opt: replace ColumnMeta.TableMeta with a TableID

The TableMeta field is problematic: it needs to be fixed up when
copying Metadata; and since it points into a slice that we append to,
it may or may not be aliased with the corresponding entry in `tables`.
Avoiding these complication by just storing the TabeID. The `md`
backpointer is also removed and QualifiedAlias is moved to Metadata.

Release note: None

#### opt: fix race caused by shared table annotations

When we assign placeholders on a detached memo, we copy the metadata.
However, this does a shallow copy of table annotations; this is
problematic for the statistics annotation which is a mutable object.

The fix is to register a copy function for each type of table
annotation as part of `NewTableAnnID`.

Fixes #34904.

Release note (bug fix): Fixed a crash related to cached plans.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 5 of 5 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-:-LZ6aVCm87AZR73PY4p1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/norm/factory.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ6_zw77PLwtBN67q-I:-LZ6_zw77PLwtBN67q-J:b-conylq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddacd90c36742973a7ca1993149d1a3f7417b713/pkg/sql/opt/norm/factory.go#L171)):*
> ```Go
> // CopyAndRplaceDefault. Note that if it's constructing a non-leaf node, that
> // node's inputs
> //
> ```

This comment got messed up
___
*[pkg/sql/opt/testutils/build.go, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ6aN-QBmRVpkAqiI4_:-LZ6aN-QBmRVpkAqiI4a:btnj08c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddacd90c36742973a7ca1993149d1a3f7417b713/pkg/sql/opt/testutils/build.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

[nit] 2019

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-:-LZ6byHf9RMB2C7Sp_jc:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/norm/factory.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ6_zw77PLwtBN67q-I:-LZ6bab_2d1N_82qKFEX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddacd90c36742973a7ca1993149d1a3f7417b713/pkg/sql/opt/norm/factory.go#L171)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This comment got messed up
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/build.go, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ6aN-QBmRVpkAqiI4_:-LZ6bx9OCurkFFeDk-4R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddacd90c36742973a7ca1993149d1a3f7417b713/pkg/sql/opt/testutils/build.go#L1)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] 2019
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 12 files at r4, 4 of 5 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35027)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/norm/factory.go, line 172 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ6e0F41kY4LSl98dLq:-LZ6e0F41kY4LSl98dLr:b-w2q67n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c27cdab8ee8a4f8dc39804987bbf5c72619aab8/pkg/sql/opt/norm/factory.go#L172)):*
> ```Go
> // children returned by recursive calls to the replace callback. Note that if a
> // non-leaf replacement node is constructed, its inputs must be copied using
> // CopyAndReplaceDefault
> ```

[nit] missing period.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35027)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/table_meta.go, line 205 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ7ErWo1qVPoXEpuG5Y:-LZ7ErWo1qVPoXEpuG5Z:bftntn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0aefbad4f4260ef9d81805850ff074a57d82e9/pkg/sql/opt/table_meta.go#L205)):*
> ```Go
> //
> // See the TableAnnID comment for more details and a usage example.
> func NewTableAnnID(copyFn CopyTableAnnFn) TableAnnID {
> ```

How necessary is it to do the copying of annotations rather than allowing them to be re-derived? I bet most of the cost of creating stats is creating the stats objects, which has to happen even in the copy case. And the FD set is probably fairly quick to create as well.

I guess my default would be to just re-derive, unless one of our benchmarks showed a tempting improvement as a result of doing the copying. Can you run our `bench_test.go` tests with and without copying enabled to see if it makes a diff?
___
*[pkg/sql/opt/norm/factory.go, line 169 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ6zOjH4WwnHYlMy7uR:-LZ6zOjH4WwnHYlMy7uS:bz4r4y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0aefbad4f4260ef9d81805850ff074a57d82e9/pkg/sql/opt/norm/factory.go#L169)):*
> ```Go
> // in the "from" subtree, and has the choice of constructing an arbitrary
> // replacement node, or delegating to the default behavior by calling
> // CopyAndRelaceDefault, which constructs a copy of the source operator using
> ```

NIT: sp: CopyAndReplace

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/table_meta.go, line 205 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ7ErWo1qVPoXEpuG5Y:-LZARZcsDFd37Hg1C2Vu:b-mkkse7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0aefbad4f4260ef9d81805850ff074a57d82e9/pkg/sql/opt/table_meta.go#L205)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How necessary is it to do the copying of annotations rather than allowing them to be re-derived? I bet most of the cost of creating stats is creating the stats objects, which has to happen even in the copy case. And the FD set is probably fairly quick to create as well.

I guess my default would be to just re-derive, unless one of our benchmarks showed a tempting improvement as a result of doing the copying. Can you run our `bench_test.go` tests with and without copying enabled to see if it makes a diff?
</blockquote></details>

I will run some benchmarks. What's the downside of keeping the FD annotation though? (we don't need to copy it so it should avoid an allocation).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35027)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/table_meta.go, line 205 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ7ErWo1qVPoXEpuG5Y:-LZAWC3u1I54VhkaT3ul:beoerin) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0aefbad4f4260ef9d81805850ff074a57d82e9/pkg/sql/opt/table_meta.go#L205)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I will run some benchmarks. What's the downside of keeping the FD annotation though? (we don't need to copy it so it should avoid an allocation).
</blockquote></details>

Great intuition - it looks like it's actually slower to copy it (note that we're still reusing the FD annotation in both cases):
```
Phases/kv-read/Parse               2.76ns ± 0%  2.78ns ± 1%     ~     (p=0.171 n=4+4)
Phases/kv-read/OptBuild            7.04µs ± 3%  7.54µs ± 0%   +7.17%  (p=0.029 n=4+4)
Phases/kv-read/Normalize           7.05µs ± 2%  7.64µs ± 1%   +8.39%  (p=0.029 n=4+4)
Phases/kv-read/Explore             11.9µs ± 1%  12.6µs ± 1%   +5.52%  (p=0.029 n=4+4)
Phases/kv-read/ExecBuild           12.9µs ± 4%  13.8µs ± 2%   +6.75%  (p=0.029 n=4+4)
Phases/kv-read-no-prep/Parse       11.5µs ± 2%  11.2µs ± 1%   -2.85%  (p=0.029 n=4+4)
Phases/kv-read-no-prep/OptBuild    31.4µs ± 2%  31.9µs ± 2%     ~     (p=0.200 n=4+4)
Phases/kv-read-no-prep/Normalize   31.0µs ± 2%  31.9µs ± 1%   +2.90%  (p=0.029 n=4+4)
Phases/kv-read-no-prep/Explore     39.3µs ± 3%  40.2µs ± 1%     ~     (p=0.114 n=4+4)
Phases/kv-read-no-prep/ExecBuild   40.6µs ± 3%  40.9µs ± 2%     ~     (p=0.886 n=4+4)
Phases/kv-read-const/Parse         2.78ns ± 0%  2.79ns ± 1%     ~     (p=0.657 n=4+4)
Phases/kv-read-const/OptBuild       143ns ± 1%   144ns ± 0%     ~     (p=0.657 n=4+4)
Phases/kv-read-const/Normalize      137ns ± 1%   140ns ± 3%     ~     (p=0.086 n=4+4)
Phases/kv-read-const/Explore        149ns ± 1%   148ns ± 3%     ~     (p=0.257 n=4+4)
Phases/kv-read-const/ExecBuild      654ns ± 1%   665ns ± 3%     ~     (p=0.371 n=4+4)
Phases/tpcc-new-order/Parse        2.79ns ± 1%  2.78ns ± 0%     ~     (p=0.971 n=4+4)
Phases/tpcc-new-order/OptBuild     12.9µs ± 1%  13.8µs ± 2%   +7.30%  (p=0.029 n=4+4)
Phases/tpcc-new-order/Normalize    12.9µs ± 0%  13.8µs ± 1%   +6.73%  (p=0.029 n=4+4)
Phases/tpcc-new-order/Explore      36.8µs ± 1%  38.8µs ± 2%   +5.49%  (p=0.029 n=4+4)
Phases/tpcc-new-order/ExecBuild    39.5µs ± 2%  42.2µs ± 1%   +6.85%  (p=0.029 n=4+4)
Phases/tpcc-delivery/Parse         2.77ns ± 0%  2.80ns ± 1%     ~     (p=0.057 n=4+4)
Phases/tpcc-delivery/OptBuild      11.7µs ± 1%  12.5µs ± 2%   +7.02%  (p=0.029 n=4+4)
Phases/tpcc-delivery/Normalize     11.8µs ± 1%  12.9µs ± 2%   +9.21%  (p=0.029 n=4+4)
Phases/tpcc-delivery/Explore       24.7µs ± 2%  25.6µs ± 1%   +3.66%  (p=0.029 n=4+4)
Phases/tpcc-delivery/ExecBuild     26.8µs ± 1%  28.1µs ± 3%   +4.74%  (p=0.029 n=4+4)
Phases/tpcc-stock-level/Parse      2.77ns ± 0%  2.79ns ± 1%     ~     (p=0.257 n=4+4)
Phases/tpcc-stock-level/OptBuild   49.1µs ± 0%  51.8µs ± 2%   +5.57%  (p=0.029 n=4+4)
Phases/tpcc-stock-level/Normalize  48.1µs ± 1%  52.9µs ± 9%   +9.83%  (p=0.029 n=4+4)
Phases/tpcc-stock-level/Explore     124µs ± 3%   138µs ± 5%  +11.73%  (p=0.029 n=4+4)
Phases/tpcc-stock-level/ExecBuild   136µs ± 1%   141µs ± 5%   +3.92%  (p=0.029 n=4+4)
Exec/kv-read/ExecPlan               143µs ± 3%   156µs ± 2%   +8.94%  (p=0.029 n=4+4)
Exec/kv-read/ExecOpt                141µs ± 1%   145µs ± 6%     ~     (p=0.343 n=4+4)
Exec/kv-read-no-prep/ExecPlan       230µs ± 0%   227µs ± 3%     ~     (p=0.343 n=4+4)
Exec/kv-read-no-prep/ExecOpt        223µs ± 1%   218µs ± 3%     ~     (p=0.200 n=4+4)
Exec/kv-read-const/ExecPlan         144µs ± 2%   157µs ± 8%     ~     (p=0.114 n=4+4)
Exec/kv-read-const/ExecOpt          119µs ± 1%   120µs ± 4%     ~     (p=0.686 n=4+4)
Exec/tpcc-new-order/ExecPlan        205µs ± 1%   197µs ± 2%   -4.24%  (p=0.029 n=4+4)
Exec/tpcc-new-order/ExecOpt         202µs ± 3%   198µs ± 1%     ~     (p=0.533 n=4+2)
```

I updated the change to only retain the FDs.
___
*[pkg/sql/opt/norm/factory.go, line 172 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ6e0F41kY4LSl98dLq:-LZARtlF4hVbUFRdfTNh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c27cdab8ee8a4f8dc39804987bbf5c72619aab8/pkg/sql/opt/norm/factory.go#L172)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] missing period.
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 3 of 11 files at r8, 4 of 5 files at r9, 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35027)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35027)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/table_meta.go, line 205 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ7ErWo1qVPoXEpuG5Y:-LZAkki3CMfd3OIsWU3l:b-lkadjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0aefbad4f4260ef9d81805850ff074a57d82e9/pkg/sql/opt/table_meta.go#L205)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Great intuition - it looks like it's actually slower to copy it (note that we're still reusing the FD annotation in both cases):
```
Phases/kv-read/Parse               2.76ns ± 0%  2.78ns ± 1%     ~     (p=0.171 n=4+4)
Phases/kv-read/OptBuild            7.04µs ± 3%  7.54µs ± 0%   +7.17%  (p=0.029 n=4+4)
Phases/kv-read/Normalize           7.05µs ± 2%  7.64µs ± 1%   +8.39%  (p=0.029 n=4+4)
Phases/kv-read/Explore             11.9µs ± 1%  12.6µs ± 1%   +5.52%  (p=0.029 n=4+4)
Phases/kv-read/ExecBuild           12.9µs ± 4%  13.8µs ± 2%   +6.75%  (p=0.029 n=4+4)
Phases/kv-read-no-prep/Parse       11.5µs ± 2%  11.2µs ± 1%   -2.85%  (p=0.029 n=4+4)
Phases/kv-read-no-prep/OptBuild    31.4µs ± 2%  31.9µs ± 2%     ~     (p=0.200 n=4+4)
Phases/kv-read-no-prep/Normalize   31.0µs ± 2%  31.9µs ± 1%   +2.90%  (p=0.029 n=4+4)
Phases/kv-read-no-prep/Explore     39.3µs ± 3%  40.2µs ± 1%     ~     (p=0.114 n=4+4)
Phases/kv-read-no-prep/ExecBuild   40.6µs ± 3%  40.9µs ± 2%     ~     (p=0.886 n=4+4)
Phases/kv-read-const/Parse         2.78ns ± 0%  2.79ns ± 1%     ~     (p=0.657 n=4+4)
Phases/kv-read-const/OptBuild       143ns ± 1%   144ns ± 0%     ~     (p=0.657 n=4+4)
Phases/kv-read-const/Normalize      137ns ± 1%   140ns ± 3%     ~     (p=0.086 n=4+4)
Phases/kv-read-const/Explore        149ns ± 1%   148ns ± 3%     ~     (p=0.257 n=4+4)
Phases/kv-read-const/ExecBuild      654ns ± 1%   665ns ± 3%     ~     (p=0.371 n=4+4)
Phases/tpcc-new-order/Parse        2.79ns ± 1%  2.78ns ± 0%     ~     (p=0.971 n=4+4)
Phases/tpcc-new-order/OptBuild     12.9µs ± 1%  13.8µs ± 2%   +7.30%  (p=0.029 n=4+4)
Phases/tpcc-new-order/Normalize    12.9µs ± 0%  13.8µs ± 1%   +6.73%  (p=0.029 n=4+4)
Phases/tpcc-new-order/Explore      36.8µs ± 1%  38.8µs ± 2%   +5.49%  (p=0.029 n=4+4)
Phases/tpcc-new-order/ExecBuild    39.5µs ± 2%  42.2µs ± 1%   +6.85%  (p=0.029 n=4+4)
Phases/tpcc-delivery/Parse         2.77ns ± 0%  2.80ns ± 1%     ~     (p=0.057 n=4+4)
Phases/tpcc-delivery/OptBuild      11.7µs ± 1%  12.5µs ± 2%   +7.02%  (p=0.029 n=4+4)
Phases/tpcc-delivery/Normalize     11.8µs ± 1%  12.9µs ± 2%   +9.21%  (p=0.029 n=4+4)
Phases/tpcc-delivery/Explore       24.7µs ± 2%  25.6µs ± 1%   +3.66%  (p=0.029 n=4+4)
Phases/tpcc-delivery/ExecBuild     26.8µs ± 1%  28.1µs ± 3%   +4.74%  (p=0.029 n=4+4)
Phases/tpcc-stock-level/Parse      2.77ns ± 0%  2.79ns ± 1%     ~     (p=0.257 n=4+4)
Phases/tpcc-stock-level/OptBuild   49.1µs ± 0%  51.8µs ± 2%   +5.57%  (p=0.029 n=4+4)
Phases/tpcc-stock-level/Normalize  48.1µs ± 1%  52.9µs ± 9%   +9.83%  (p=0.029 n=4+4)
Phases/tpcc-stock-level/Explore     124µs ± 3%   138µs ± 5%  +11.73%  (p=0.029 n=4+4)
Phases/tpcc-stock-level/ExecBuild   136µs ± 1%   141µs ± 5%   +3.92%  (p=0.029 n=4+4)
Exec/kv-read/ExecPlan               143µs ± 3%   156µs ± 2%   +8.94%  (p=0.029 n=4+4)
Exec/kv-read/ExecOpt                141µs ± 1%   145µs ± 6%     ~     (p=0.343 n=4+4)
Exec/kv-read-no-prep/ExecPlan       230µs ± 0%   227µs ± 3%     ~     (p=0.343 n=4+4)
Exec/kv-read-no-prep/ExecOpt        223µs ± 1%   218µs ± 3%     ~     (p=0.200 n=4+4)
Exec/kv-read-const/ExecPlan         144µs ± 2%   157µs ± 8%     ~     (p=0.114 n=4+4)
Exec/kv-read-const/ExecOpt          119µs ± 1%   120µs ± 4%     ~     (p=0.686 n=4+4)
Exec/tpcc-new-order/ExecPlan        205µs ± 1%   197µs ± 2%   -4.24%  (p=0.029 n=4+4)
Exec/tpcc-new-order/ExecOpt         202µs ± 3%   198µs ± 1%     ~     (p=0.533 n=4+2)
```

I updated the change to only retain the FDs.
</blockquote></details>

The downside of keeping the FD is more complex code. It's worth it if we see an actual speedup, but if not, it's just simpler or more maintainable to zero out the annotations instead. Do you see a difference in perf in you reuse the FD?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35027)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

___
*[pkg/sql/opt/table_meta.go, line 205 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ7ErWo1qVPoXEpuG5Y:-LZAqAGUDVYYQZ7ZIRvV:bf26v53) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0aefbad4f4260ef9d81805850ff074a57d82e9/pkg/sql/opt/table_meta.go#L205)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The downside of keeping the FD is more complex code. It's worth it if we see an actual speedup, but if not, it's just simpler or more maintainable to zero out the annotations instead. Do you see a difference in perf in you reuse the FD?
</blockquote></details>

I kind of like that it forces any user of annotations to explicitly think about what should happen on a metadata copy. Anyway, the benchmark results have been inconsistent, I'll rerun on a gceworker and report back.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35027)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/table_meta.go, line 205 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35027#-LZ7ErWo1qVPoXEpuG5Y:-LZBZEAH1W6qvP94GAF2:bl691i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0aefbad4f4260ef9d81805850ff074a57d82e9/pkg/sql/opt/table_meta.go#L205)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I kind of like that it forces any user of annotations to explicitly think about what should happen on a metadata copy. Anyway, the benchmark results have been inconsistent, I'll rerun on a gceworker and report back.
</blockquote></details>

I made quite a few runs on a gceworker and couldn't see a difference above the noise. If anything zeroing them out is somehow faster. I simplified the change.

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35027)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Pull request merged**
