### PR TITLE
lint: extend TestVet with more printf-like functions

### PR DESCRIPTION
**Pull request by knz**
Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35894#-:-LaHz7jPDwYv87YL1UBO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/testutils/lint/lint_test.go, line 1285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35894#-LaHyt5z6a3hZldNlgx7:-LaHyt5z6a3hZldNlgx8:b-uo0iwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8dd3cee8fecf077c91716c8454929967d727e02/pkg/testutils/lint/lint_test.go#L1285)):*
> ```Go
> 		// as follows: (comment taken from the source of `go vet`)
> 		//
> 		// // A function may be a Printf or Print wrapper if its last argument is ...interface{}.
> ```

[nit] extra // (I know you're pasting a comment but I'd still remove it)
___
*[pkg/testutils/lint/lint_test.go, line 1310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35894#-LaHz2hdDRtWogD14Ip1:-LaHz2hdDRtWogD14Ip2:b5d6kdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8dd3cee8fecf077c91716c8454929967d727e02/pkg/testutils/lint/lint_test.go#L1310)):*
> ```Go
> 				"VEvent",
> 				"VEventf",
> 				"NewErrorf",
> ```

duplicate

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35894)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/testutils/lint/lint_test.go, line 1285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35894#-LaHyt5z6a3hZldNlgx7:-LaLEO-pCEUYaaOJnjga:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8dd3cee8fecf077c91716c8454929967d727e02/pkg/testutils/lint/lint_test.go#L1285)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] extra // (I know you're pasting a comment but I'd still remove it)
</blockquote></details>

Done.
___
*[pkg/testutils/lint/lint_test.go, line 1310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35894#-LaHz2hdDRtWogD14Ip1:-LaLElbm7aSXxCm--Rx4:b-fsfswj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8dd3cee8fecf077c91716c8454929967d727e02/pkg/testutils/lint/lint_test.go#L1310)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

duplicate
</blockquote></details>

Solved by sorting the lines.

**Comment by knz** [comment]
TFYR!

bors r+

**Comment by jordanlewis** [comment]
If this needs a rebuild, can you disable its t.Parallel() since we see this OOM a lot in TestLint?

**Comment by knz** [comment]
OK will do when I'm back assuming nobody did earlier.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
