### PR TITLE
node_rac2: add AdmittedPiggybacker and use in RaftTransport

### PR DESCRIPTION
**Pull request by sumeerbhola**
AdmittedPiggybacker implements the existing
replica_rac2.AdmittedPiggybacker interface, for adding msgs to be piggybacked, and the new node_rac2.PiggybackMsgReader which is for use by RaftTransport.

Informs #128309

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I owe a test for the changes to RaftTransport, but this is ready for a look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129081#-:-O4MWYkk-Dr4LvKc2o53:bs23gb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by sumeerbhola — COMMENTED** [review]
added the test for the `RaftTransport` changes, which lifts most code from the existing `TestFlowControlRaftTransport`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129081#-:-O4N-Vk77uVAGCKyB6sO:b-kfwbyn)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 23 of 24 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129081#-:-O4Qd23c4PmPmHXqx5Ia:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/raft_transport.go` line 1154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129081#-O4N1L4W4ypuJJjMM7H0:-O4N1L4W4ypuJJjMM7H1:b-dcdcbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6653fe62a47fb78234750fbb75617cb82c591d56/pkg/kv/kvserver/raft_transport.go#L1154)):*
> ```Go
> 		t.metrics.FlowTokenDispatchesDropped.Inc(int64(len(pendingDispatches)))
> 	}
> 	now := time.Now()
> ```

nit: timeutil.Now() is preferred.
___
*[`pkg/kv/kvserver/kvflowcontrol/node_rac2/admitted_piggybacker.go` line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129081#-O4QbJLA6ecp4fHTf0y-:-O4QbJLA6ecp4fHTf0y0:b-ubz1el) ([raw file](https://github.com/cockroachdb/cockroach/blob/0df51645b10223e7cb2405376ef45927477c81dd/pkg/kv/kvserver/kvflowcontrol/node_rac2/admitted_piggybacker.go#L116)):*
> ```Go
> const gcTimeDuration time.Duration = time.Minute
> 
> func (ap *AdmittedPiggybacker) NodesWithMsgs(t time.Time) []roachpb.NodeID {
> ```

nit: now might be clearer than t.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129081#-:-O4QjQsK14d8Te_Y8HvD:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/raft_transport.go` line 1154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129081#-O4N1L4W4ypuJJjMM7H0:-O4QhxZd-xKqDMie6pRH:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6653fe62a47fb78234750fbb75617cb82c591d56/pkg/kv/kvserver/raft_transport.go#L1154)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: timeutil.Now() is preferred.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/node_rac2/admitted_piggybacker.go` line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129081#-O4QbJLA6ecp4fHTf0y-:-O4Qiuwf5saskFmPEHkM:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0df51645b10223e7cb2405376ef45927477c81dd/pkg/kv/kvserver/kvflowcontrol/node_rac2/admitted_piggybacker.go#L116)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: now might be clearer than t.
</blockquote></details>

Done

**Review by kvoli — APPROVED** [review]

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
