### PR TITLE
importccl: persist bulk op summary during execution

### LINKED ISSUE #67987: import: job summary is sometimes inaccurate
When running an IMPORT job it will return a summary of the amount of data that the job wrote. However, this summary may be inaccurate if the job internally retried in the face of node-restarts.

Before the addition of internal retries, IMPORT jobs would fail if a node in the cluster went down. Now it automatically retries, but a consequence of this is that the internally maintained summary of the number of written rows (tracked in memory on the coordinator node) is no longer accurate.

One solution here is to persist the summary as we persist progress updates to the job. This may also have a nice side-effect of being able to expose these summaries for detached jobs as well as jobs that have been retried when the coordinator failed in a follow up.

Epic CRDB-8816

### PR DESCRIPTION
**Pull request by pbardea**
Fixes #67987.
Fixes https://github.com/cockroachdb/cockroach/issues/67987.

Release note (bug fix): Fix a bug where the summary displayed after an
IMPORT command would sometimes be inaccurate due to retries.

Release justification: Bug fix. Fix a bug where the summary displayed after an
IMPORT command would sometimes be inaccurate due to retries.

### CODE REVIEW

**Comment by michae2** [comment]
@dt @adityamaru just a friendly ping, wondering if you can take a look this week, since this is blocking https://github.com/cockroachdb/cockroach/pull/67106

**Review by dt — APPROVED** [review]

**Comment by michae2** [comment]
@pbardea thanks again for working on this, I really appreciate it! 🙂

**Comment by pbardea** [comment]
Hoping to get this merged this aft! Fighting rebases and flakes, but I'm hoping this next push should do the trick.

**Comment by pbardea** [comment]
There seems to be an issue with running the bazel import tests under race on master. Going to merge this as is and file an issue for that separately.
bors r+

**Pull request merged**
