### PR TITLE
roachtest: fix sqlalchemy to install pip

### LINKED ISSUE #80454: roachtest: sqlalchemy failed
roachtest.sqlalchemy [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4984179&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4984179&tab=artifacts#/sqlalchemy) on master @ [911ebee04c0230f1145375340f81745931727162](https://github.com/cockroachdb/cockroach/commits/911ebee04c0230f1145375340f81745931727162):

```
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.repeatRunE
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/canary.go:138
		  | [...repeated from below...]
		Wraps: (2) all attempts failed for install pip
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*clusterImpl).RunE
		  | 	main/pkg/cmd/roachtest/cluster.go:1962
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.repeatRunE
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/canary.go:131
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runSQLAlchemy
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/sqlalchemy.go:87
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerSQLAlchemy.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/sqlalchemy.go:46
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:876
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (4) output in run_093249.881256177_n1_curl
		Wraps: (5)
		  | 		curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.7
		  | 	 returned
		  | stderr:
		  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
		  |                                  Dload  Upload   Total   Spent    Left  Speed
		  | 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 78 2596k   78 2031k    0     0  14.2M      0 --:--:-- --:--:-- --:--:-- 14.2M
100 2596k  100 2596k    0     0  17.2M      0 --:--:-- --:--:-- --:--:-- 17.1M
		  | Traceback (most recent call last):
		  |   File "<stdin>", line 33324, in <module>
		  |   File "<stdin>", line 135, in main
		  |   File "<stdin>", line 111, in bootstrap
		  |   File "<stdin>", line 92, in monkeypatch_for_cert
		  |   File "/tmp/tmpw6afabc2/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>
		  |   File "/tmp/tmpw6afabc2/pip.zip/pip/_internal/cli/base_command.py", line 15, in <module>
		  |   File "/tmp/tmpw6afabc2/pip.zip/pip/_internal/cli/cmdoptions.py", line 23, in <module>
		  |   File "/tmp/tmpw6afabc2/pip.zip/pip/_internal/cli/parser.py", line 12, in <module>
		  |   File "/tmp/tmpw6afabc2/pip.zip/pip/_internal/configuration.py", line 26, in <module>
		  |   File "/tmp/tmpw6afabc2/pip.zip/pip/_internal/utils/logging.py", line 27, in <module>
		  |   File "/tmp/tmpw6afabc2/pip.zip/pip/_internal/utils/misc.py", line 39, in <module>
		  |   File "/tmp/tmpw6afabc2/pip.zip/pip/_internal/locations/__init__.py", line 14, in <module>
		  |   File "/tmp/tmpw6afabc2/pip.zip/pip/_internal/locations/_distutils.py", line 9, in <module>
		  | ModuleNotFoundError: No module named 'distutils.cmd'
		  |
		  | stdout:
		Wraps: (6) COMMAND_PROBLEM
		Wraps: (7) Node 1. Command with error:
		  | ``````
		  | curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.7
		  | ``````
		Wraps: (8) exit status 1
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *cluster.WithCommandDetails (6) errors.Cmd (7) *hintdetail.withDetail (8) *exec.ExitError
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlalchemy.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by ZhouXing19**
fixes #80454

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice, thanks for fixing!

**Comment by ZhouXing19** [comment]
TFTR!
bors r=rafiss

**Comment by rafiss** [comment]
blathers backport 22.1.0

**Comment by rafiss** [comment]
blathers backport 21.2

**Pull request merged**
