### PR TITLE
vendor: bump Pebble to 639dfcee

### PR DESCRIPTION
**Pull request by sumeerbhola**
639dfcee db: enhance Iterator with limited iteration mode

Release note: None

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62077#-:-MVw77Sv1AP5L4Lslkae:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62077#-:-MVw84tS4VJi6R2YDMtA:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by sumeerbhola** [comment]
schemachange_test.TestWorkload failure looks unrelated

**Pull request merged**
