### PR TITLE
kvserver: don't refuse to fwd lease proposals in some edge cases

### LINKED ISSUE #57798: roachtest: acceptance/bank/node-restart flake
https://teamcity.cockroachdb.com/viewLog.html?buildId=2510921&buildTypeId=Cockroach_UnitTests

```
test artifacts and logs in: artifacts/acceptance/bank/node-restart/run_1
	bank.go:354,bank.go:469,acceptance.go:104,test_runner.go:760: after 33.7s: pq: query execution canceled due to statement timeout
		(1) attached stack trace
		  -- stack trace:
		  | main.(*bankClient).transferMoney
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/bank.go:74
		  | main.(*bankState).transferMoney
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/bank.go:158
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (2) after 33.7s
		Wraps: (3) pq: query execution canceled due to statement timeout
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *pq.Error
```

### PR DESCRIPTION
**Pull request by andreimatei**
This patch backpedals a little bit on the logic introduced in #55148.
That patch said that, if a leader is known, every other replica refuses
to propose a lease acquisition. Instead, the replica in question
redirects whomever was triggering the lease acquisition to the leader,
thinking that the leader should take the lease.
That patch introduced a deadlock: some replicas refuse to take the lease
because they are not VOTER_FULL (see CheckCanReceiveLease()). To fix the
deadlock, this patch incorporates that check in the proposal buffer's
decision about whether or not to reject a proposal: if the leader is
believed to refuse to take the lease, then we again forward our own
lease request.

An edge case to the edge case is when the leader is not even part of the
proposer's range descriptor. This can happen if the proposer is far
behind. In this case, we assume that the leader is eligible. If it
isn't, the deadlock will resolve once the proposer catches up.

A future patch will relax the conditions under which a replica agrees to
take the lease. VOTER_INCOMING replicas should take the lease.
VOTER_DEMOTING are more controversial.

Fixes #57798

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58722)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx26RQ2D5nZcGdQYrm:-MQx26RQ2D5nZcGdQYrn:b-z7uatl) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L163)):*
> ```Go
> 	leaderKnown bool
> 
> 	leader roachpb.ReplicaID
> ```

Might as well give this a comment, mentioning the value of this field when `!leaderKnown`.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx3IxHAkbdyzlGBF1F:-MQx3IxHAkbdyzlGBF1G:b-vzvxrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L168)):*
> ```Go
> 	// leaderIneligibleForLease is set if the leader is known, but its type of
> 	// replica prevents it from acquiring a lease.
> 	leaderIneligibleForLease bool
> ```

nit: Invert this condition to avoid the double-negative down below.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 178 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx1nLYCr19cnAnduj5:-MQx1nLYCr19cnAnduj6:b-55pmoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L178)):*
> ```Go
> 	replicaID() roachpb.ReplicaID
> 	leaderStatusRLocked(raftGroup proposerRaft) leaderInfo
> ```

stray line?
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx2QoXAavnzbzam3I7:-MQx2QoXAavnzbzam3I8:b-o4e438) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L446)):*
> ```Go
> 	buf := b.arr.asSlice()[:used]
> 	ents := make([]raftpb.Entry, 0, used)
> 	var leaderInfo leaderInfo
> ```

nit: move this down to where the other variable declarations use to live. No need to mix it up with these slices of entries.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 501 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx2hASBp85UcSgsQZp:-MQx2hASBp85UcSgsQZq:bjcfj7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L501)):*
> ```Go
> 		// A special case is when the leader is known, but is ineligible to get the
> 		// lease. In that case, we have no choice but to continue with the proposal.
> 		if !leaderInfo.iAmTheLeader && p.Request.IsLeaseRequest() {
> ```

We may need to extend this check even more. In https://github.com/cockroachdb/cockroach/pull/58904/commits/91f58afa5f6063befb2aa1a3fc21ede56d87f66a, I noticed that we are rejecting lease extensions when we are the current leaseholder if we haven't yet grabbed raft leadership. That seems wrong.

No need to do anything here. 
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 503 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx3Qev85tCIkNO-b15:-MQx3Qev85tCIkNO-b16:b-gqad8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L503)):*
> ```Go
> 		if !leaderInfo.iAmTheLeader && p.Request.IsLeaseRequest() {
> 			proposeAnyway := leaderInfo.leaderIneligibleForLease || b.testing.allowLeaseProposalWhenNotLeader
> 			if leaderInfo.leaderKnown && !proposeAnyway {
> ```

This grouping seems odd to me. We're saying `leader known && (either leader eligible || not testing allow when not leader)`. So if `leaderKnown && !leaderIneligibleForLease`, aren't we rejecting, regardless of the testing knob? I don't think that's the intention. I think we want to group the first two conditions together like:
```
leaderKnownAndEligible := ...
if leaderKnownAndEligible && !b.testing.allowLeaseProposalWhenNotLeader {
    ...
}
```
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 764 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx4LHtDgn0CI3gvptd:-MQx4LHtDgn0CI3gvpte:bxzy751) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L764)):*
> ```Go
> }
> 
> func (rp *replicaProposer) leaderStatusRLocked(raftGroup proposerRaft) leaderInfo {
> ```

Keep this in order with the interface. Either pull this all the way up above `destroyed()` (but don't do that) or shuffle the interface def. Ideally, this would go right above `rejectProposalWithRedirectLocked` in the declaration and the definition.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 775 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx4ls7EwibtTwoCmC8:-MQx4ls8C8Vv2KEle2yK:b-kexrgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L775)):*
> ```Go
> 	if leaderKnown {
> 		// Figure out if the leader is eligible for getting a lease. Only VOTER_FULL
> 		// replicas are eligible.
> ```

This seems like the kind of comment that is going to rot. How should we avoid that?
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 785 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx4ao-1uzkkH-yji5O:-MQx4ao0CBOsc2iVhJC9:bevcnh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L785)):*
> ```Go
> 			leaderIneligibleForLease = false
> 		} else {
> 			err := batcheval.CheckCanReceiveLease(leaderRep, *rangeDesc)
> ```

nit: Seems like we should just pass the descriptor by pointer, since that's what every caller wants and that's generally how we interact with RangeDescriptors.
___
*[pkg/kv/kvserver/replica_proposal_buf_test.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx5BVv4k86bQu6hHiu:-MQx5BVv4k86bQu6hHiv:b-c51u65) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf_test.go#L59)):*
> ```Go
> }
> 
> func (t *testProposer) leaderStatusRLocked(raftGroup proposerRaft) leaderInfo {
> ```

Why define this method in such a random place? I know these kinds of comments seem like nits, but a few of these changes in a row and the entire structure of a piece of code falls apart and we're left with chaos! And then a month later, we'll decide that we need to rewrite everything because the code is jumbled and hard to read. And then we introduce a bug during the rewrite. And then data gets corrupted in an important deployment. And then a SpaceX satellite falls out of the sky. And then SpaceX goes bankrupt due to a lawsuit. And we never make it to Mars. Don't you want to go to Mars??
___
*[pkg/kv/kvserver/batcheval/cmd_lease.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx184T55vJMG-D8hOE:-MQx184T55vJMG-D8hOF:b-s66l77) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23fff1a791566a9091fc5da504d4344b6c94f98/pkg/kv/kvserver/batcheval/cmd_lease.go#L45)):*
> ```
> // If we decide to start using long-lived learners at some point, that math may change.
> ```

If we decide?
___
*[pkg/kv/kvserver/batcheval/cmd_lease.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx1NU_10fTZKbpzM4W:-MQx1NU_10fTZKbpzM4X:b7lbo3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23fff1a791566a9091fc5da504d4344b6c94f98/pkg/kv/kvserver/batcheval/cmd_lease.go#L47)):*
> ```Go
> // point, that math may change.
> func checkCanReceiveLease(
> 	newLeaseholer roachpb.ReplicaDescriptor, rngDesc roachpb.RangeDescriptor,
> ```

Should `rngDesc` be a pointer?
___
*[pkg/kv/kvserver/batcheval/cmd_lease.go, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx1bVYAq5L0bDsLzIR:-MQx1bVYAq5L0bDsLzIS:b-aved9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/batcheval/cmd_lease.go#L46)):*
> ```Go
> // out the edge cases. If we decide to start using long-lived learners at some
> // point, that math may change.
> func CheckCanReceiveLease(
> ```

Want to add a unit test around this here in `pkg/kv/kvserver/batcheval/cmd_lease.go`?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58722)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx26RQ2D5nZcGdQYrm:-MR1n8Ay1y9spz4s98wd:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L163)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Might as well give this a comment, mentioning the value of this field when `!leaderKnown`.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 178 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx1nLYCr19cnAnduj5:-MR1nDeO6_3iGB-GWjeP:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L178)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

stray line?
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx2QoXAavnzbzam3I7:-MR1nR30DODrQy8hQaUP:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L446)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move this down to where the other variable declarations use to live. No need to mix it up with these slices of entries.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 503 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx3Qev85tCIkNO-b15:-MR1pswCEzxzx31UMDdz:bbjn4fs) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L503)):*
> So if leaderKnown && !leaderIneligibleForLease, aren't we rejecting, regardless of the testing knob? I don't think that's the intention.

This was, in fact, the intention. The testing knob is kinda crap, and is only used by one rando. I wanted to keep the scope of the knob as small as possible - i.e. only apply it in the most regular situation (when the leader is eligible). In particular, I don't want the knob to introduce the possibility of the deadlock.
WDYT
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 764 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx4LHtDgn0CI3gvptd:-MR1r7HhDNKa-K2vw6Vw:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L764)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Keep this in order with the interface. Either pull this all the way up above `destroyed()` (but don't do that) or shuffle the interface def. Ideally, this would go right above `rejectProposalWithRedirectLocked` in the declaration and the definition.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 775 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx4ls7EwibtTwoCmC8:-MR1rNk_-Q55D3FVvZfA:bwl6j06) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L775)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This seems like the kind of comment that is going to rot. How should we avoid that?
</blockquote></details>

I've deleted it :P
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 785 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx4ao-1uzkkH-yji5O:-MR1rXJ57m5TbPnsshef:b-y2c3lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L785)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Seems like we should just pass the descriptor by pointer, since that's what every caller wants and that's generally how we interact with RangeDescriptors.
</blockquote></details>

yeah... I had made it a value for symmetry with the `ReplicaDescriptor` arg, where we do use values more. Changed.
___
*[pkg/kv/kvserver/replica_proposal_buf_test.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx5BVv4k86bQu6hHiu:-MR1s-dODeingFS-mDjv:botnuan) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf_test.go#L59)):*
> Don't you want to go to Mars??

https://www.youtube.com/watch?v=KDXbl54HpQE
___
*[pkg/kv/kvserver/batcheval/cmd_lease.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx184T55vJMG-D8hOE:-MR1sVL96PYGY73tojXc:b-2atmq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23fff1a791566a9091fc5da504d4344b6c94f98/pkg/kv/kvserver/batcheval/cmd_lease.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> // If we decide to start using long-lived learners at some point, that math may change.
> ```

If we decide?
</blockquote></details>

well I'm just moving a comment around

But yeah, I've deleted it. Cause we have decided, but the math is not changing (as far as learners go)
___
*[pkg/kv/kvserver/batcheval/cmd_lease.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx1NU_10fTZKbpzM4W:-MR1snAS6vScxaGXYvpb:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23fff1a791566a9091fc5da504d4344b6c94f98/pkg/kv/kvserver/batcheval/cmd_lease.go#L47)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should `rngDesc` be a pointer?
</blockquote></details>

done
___
*[pkg/kv/kvserver/batcheval/cmd_lease.go, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx1bVYAq5L0bDsLzIR:-MR20Ynp6IjaqwKrQBpt:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/batcheval/cmd_lease.go#L46)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Want to add a unit test around this here in `pkg/kv/kvserver/batcheval/cmd_lease.go`?
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm: though there are still a few minor tweaks to make in that inner condition to unravel it a little.

We should get more eyes on this too, since I assume we're planning for another backport attempt.

> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-:-MR338cm3itYfBJNVwHo:b-rpzrqx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx3IxHAkbdyzlGBF1F:-MR31wBt8j7zdOOO7m9Y:bnicf2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L168)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Invert this condition to avoid the double-negative down below.
</blockquote></details>

I still think this would be an improvement.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 503 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx3Qev85tCIkNO-b15:-MR32Kqk4RspVUjpu7ZF:b-ezs4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L503)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> So if leaderKnown && !leaderIneligibleForLease, aren't we rejecting, regardless of the testing knob? I don't think that's the intention.

This was, in fact, the intention. The testing knob is kinda crap, and is only used by one rando. I wanted to keep the scope of the knob as small as possible - i.e. only apply it in the most regular situation (when the leader is eligible). In particular, I don't want the knob to introduce the possibility of the deadlock.
WDYT




</blockquote></details>

I think this makes the knob super hard to reason about. I'd be in favor of broadening it to just disable this entire rejection mechanism. That's the effect it had before.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58722)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/kv/kvserver/replica_proposal_buf_test.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx5BVv4k86bQu6hHiu:-MR8DD-cBAGpZciY-WMN:bnbz31c) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf_test.go#L59)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> Don't you want to go to Mars??

https://www.youtube.com/watch?v=KDXbl54HpQE
</blockquote></details>

https://www.youtube.com/watch?v=qoHU57KtUws

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58722)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx3IxHAkbdyzlGBF1F:-MRfLsmdD-nEMHAYsvnu:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L168)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I still think this would be an improvement.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 503 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx3Qev85tCIkNO-b15:-MRfMrZQ-04vTGy_73XB:b-2ojg2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L503)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think this makes the knob super hard to reason about. I'd be in favor of broadening it to just disable this entire rejection mechanism. That's the effect it had before.
</blockquote></details>

ok, done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-:-MRlKNd6BBK5UA328IQW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 501 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MQx2hASBp85UcSgsQZp:-MRlK5pC6pX8504zd3Qt:byh8wp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/383e6a80ac853bffcb0898c9b50c1c112cab8e0c/pkg/kv/kvserver/replica_proposal_buf.go#L501)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We may need to extend this check even more. In https://github.com/cockroachdb/cockroach/pull/58904/commits/91f58afa5f6063befb2aa1a3fc21ede56d87f66a, I noticed that we are rejecting lease extensions when we are the current leaseholder if we haven't yet grabbed raft leadership. That seems wrong.

No need to do anything here. 
</blockquote></details>

By the way, this is now tracked in #59179.

**Review by tbg — APPROVED** [review]
> Reviewed 6 of 6 files at r7, 3 of 3 files at r8, 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58722)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @bdarnell)

___
*[pkg/kv/kvserver/batcheval/cmd_lease.go, line 51 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MRtaAjX1dpCEZWbeaPu:-MRtaAjX1dpCEZWbeaPv:b4orgox) ([raw file](https://github.com/cockroachdb/cockroach/blob/e94acddca7dd169eadf1e8f8a8ed4bfb980955c5/pkg/kv/kvserver/batcheval/cmd_lease.go#L51)):*
> ```Go
> 	wouldbeLeaseholer roachpb.ReplicaDescriptor, rngDesc *roachpb.RangeDescriptor,
> ) error {
> 	repDesc, ok := rngDesc.GetReplicaDescriptorByID(wouldbeLeaseholer.ReplicaID)
> ```

Leasehol**d**er

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58722)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_lease.go, line 51 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-MRtaAjX1dpCEZWbeaPu:-MRuXC3m4-Ukghlo98bP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e94acddca7dd169eadf1e8f8a8ed4bfb980955c5/pkg/kv/kvserver/batcheval/cmd_lease.go#L51)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Leasehol**d**er
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58722#-:-MRuo3wP-aFwBpEmitlv:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @nvanbenschoten, and @tbg)

**Pull request merged**
