### PR TITLE
sql: Add information_schema.collations table

### PR DESCRIPTION
**Pull request by mneverov**
sql: Add information_schema.collations table

The `collations` table contains the collations available in the current database.
Since CockroachDB does not support collation creation or change the only
collation schema returned is `pg_catalog`
Related to: #8675

Release note (sql change): Added collations table to the information_schema.

### CODE REVIEW

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57609)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, @otan, and @rafiss)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/57609#-MNoTS7r0rJrJqOBzDYl:-MNoTS7s94Zdyz-Y4Y8O:b8n703u) (no related file):*
To the reviewer:
alter collation is not possible:
demo@127.0.0.1:26257/movr> create schema foo;
CREATE SCHEMA

demo@127.0.0.1:26257/movr> alter collation "de-u-co-phonebk" set schema foo;
invalid syntax: statement ignored: at or near "collation": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
alter collation "de-u-co-phonebk" set schema foo

demo@127.0.0.1:26257/movr> \h alter
Command:     ALTER
Syntax:
ALTER TABLE, ALTER INDEX, ALTER VIEW, ALTER SEQUENCE, ALTER DATABASE, ALTER USER, ALTER ROLE

therefore the only collation schema is `pg_catalog` with the current DB.
I checked the open issues and could not find anything about `alter collation`.

Also, no docs url added as there is no collations section in https://www.cockroachlabs.com/docs/stable/information-schema.html.

---

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57609)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, @otan, and @rafiss)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/57609#-MNoTS7r0rJrJqOBzDYl:-MNsFztvDEnNEp-9bo3h:b9zl8is) (no related file):*
<details><summary><i>Previously, mneverov (Max Neverov) wrote…</i></summary><blockquote>

To the reviewer:
alter collation is not possible:
demo@127.0.0.1:26257/movr> create schema foo;
CREATE SCHEMA

demo@127.0.0.1:26257/movr> alter collation "de-u-co-phonebk" set schema foo;
invalid syntax: statement ignored: at or near "collation": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
alter collation "de-u-co-phonebk" set schema foo

demo@127.0.0.1:26257/movr> \h alter
Command:     ALTER
Syntax:
ALTER TABLE, ALTER INDEX, ALTER VIEW, ALTER SEQUENCE, ALTER DATABASE, ALTER USER, ALTER ROLE

therefore the only collation schema is pg_catalog with current DB.
I checked the open issues and could not find anything about `alter collation`.

Also, no docs url added as there is no collations section in https://www.cockroachlabs.com/docs/stable/information-schema.html.
</blockquote></details>

I also added `information_schema.collation_character_set_applicability` table to this PR as they are closely related.
Please let me know if I need to create a separate PR for that or squash the commits. 

---

**Review by otan — APPROVED** [review]
LGTM
thanks!

bors r+

**Comment by Amruta-Ranade** [comment]
Hello! Thank you for contributing to CockroachDB this year. As a token of our appreciation, we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) @Amruta so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please contact me as soon as possible :)

**Pull request merged**
