### PR TITLE
ctxgroup,*: change GoCtx to catch panics

### PR DESCRIPTION
**Pull request by adityamaru**
This commit implements the changes to methods in ctxgroup as
outlined in https://github.com/cockroachdb/cockroach/issues/76734. Please
refer to the issue for details.

Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
Review list:

- [ ] Commit 1: @dt / @ajwerner: Only changes to `ctxgroup` need attention. The rest of the changes are passing in a default value of `""` as the op. I have held off on sniffing for `pgerrors` and wrapping the error returned by `f` with the `op` for now since it causes test failures, and I think it is better suited as a follow-up.

- [ ] Commit 2: @dt: all bulk op labels

- [ ] Commit 3 (and maybe 6): @ajwerner : all sql op labels

- [ ] Commit 4: @miretskiy: all cdc op labels

- [ ] Commit 5: all kv op labels

If y'all want me to rename any op labels I'm happy to, I've just picked them based on whatever context I could gather as a first pass.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77012)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @dt)

___
*[-- commits, line 5 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77012#-MwnaHqh6eRebvDlPSJs):*
I do feel this solution is a bit heavy weight; Personally, I think we shouldn't panic :) ...
But I guess that's hard to control...
What do you think about taking a bit lighter touch approach and just swap the order of the function arguments?
GoCtx(fn func() error,  labels ... SafeString)?
Perhaps no need to change all of the call sites? Provide some reasonable default if nothing specified...

**Review by knz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77012)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @dt)

___
*[pkg/util/ctxgroup/ctxgroup.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77012#-MwvCbCUEXq0yXGNwOWO:-MwvCbCUEXq0yXGNwOWP:b-bznt9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/13b74efa9cd11cb492e06ab14343e23b844b4f06/pkg/util/ctxgroup/ctxgroup.go#L175)):*
> ```Go
> 				err = errors.Wrapf(r, "failed to %s", op)
> 			default:
> 				err = errors.AssertionFailedf("failed to %s: %v", op, r)
> ```

I think this is incorrect. We should let the panic propagate in that case (and also use logcrash.ReportPanic)


Use `errorutil.ShouldCatch()` instead.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77012)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @dt)

___
*[pkg/util/ctxgroup/ctxgroup.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77012#-MwvCbCUEXq0yXGNwOWO:-Mx4hVdo2s6rRiWAqV26:b-i5cftq) ([raw file](https://github.com/cockroachdb/cockroach/blob/13b74efa9cd11cb492e06ab14343e23b844b4f06/pkg/util/ctxgroup/ctxgroup.go#L175)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think this is incorrect. We should let the panic propagate in that case (and also use logcrash.ReportPanic)


Use `errorutil.ShouldCatch()` instead.
</blockquote></details>

see #77212

**Pull request closed without merging**
