### PR TITLE
geo: enforce Shape and SRID matching during casts

### PR DESCRIPTION
**Pull request by otan**
This commit aims to enforce that when casting or storing geospatial
types that the shape and srids matches the desired type. This is
primarily enforced by calling "GeospatialTypeFitsColumnMetadata".

We've had to change types.go and the parser to no longer take SRID =
geopb.DefaultGeographySRID as the default SRID for Geography types to be
in line with PostGIS. It is the responsibility of Geography parsers to
ensure that SRIDs of 0 become 4326 -- the SRID 0 is reserved in the type
definition (the typmod) to allow "any SRID". Without this change,
casting SRID 4004 to a geography type with no SRID typmod (e.g.
'SRID=4004;POINT(1.0 1.0)'::geography) would fail the SRID validation
check.

Also change SRID 3857 examples to SRID 4004, as SRID 3857 is not a
longlat projection.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/sem/tree/eval.go, line 3713 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49195#-M7d6Ch2999UVWRgsbx-:-M7d6Ch2999UVWRgsbx0:b1y1pnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e432b4712646cd2fce0d325da51b9a901e225f38/pkg/sql/sem/tree/eval.go#L3713)):*
> ```Go
> 			// A Geometry with SRID 0 will convert to geopb.DefaultGeographySRID.
> 			// As such, fool the spatial type check that we're also converting to 0.
> 			if d.Geometry.SRID() == 0 {
> ```

this is confusing
- GeospatialTypeFitsColumnMetadata does not care about DefaultGeographySRID, so why do we need this special casing
- isn't this code equivalent to
```
if !d.Geometry.SRID() == 0 {
  if err := geo.GeospatialTypeFitsColumnMetadata(
	d.Geometry,
	toSRID,
	t.InternalType.GeoMetadata.Shape,
	); err != nil {
	return nil, err
  }
}
```
___
*[pkg/sql/sqlbase/column_type_properties.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49195#-M7d7XX_5zKMHfgEBWJW:-M7d7XX_5zKMHfgEBWJX:b-uz75vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e432b4712646cd2fce0d325da51b9a901e225f38/pkg/sql/sqlbase/column_type_properties.go#L151)):*
> ```Go
> 			return tree.NewDInterval(in.Duration, itm), nil
> 		}
> 	case types.GeometryFamily:
> ```

it is odd that this code is appearing in a function called `LimitValueWidth` -- minimally we need an updated function comment.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/sql/sem/tree/eval.go, line 3713 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49195#-M7d6Ch2999UVWRgsbx-:-M7dLe-41_E6QzHqgbJc:bjlklv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e432b4712646cd2fce0d325da51b9a901e225f38/pkg/sql/sem/tree/eval.go#L3713)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is confusing
- GeospatialTypeFitsColumnMetadata does not care about DefaultGeographySRID, so why do we need this special casing
- isn't this code equivalent to
```
if !d.Geometry.SRID() == 0 {
  if err := geo.GeospatialTypeFitsColumnMetadata(
	d.Geometry,
	toSRID,
	t.InternalType.GeoMetadata.Shape,
	); err != nil {
	return nil, err
  }
}
```
</blockquote></details>

We have to check SHAPE as well. I've moved this check to after its been casted to prevent confusion
___
*[pkg/sql/sqlbase/column_type_properties.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49195#-M7d7XX_5zKMHfgEBWJW:-M7dLqac0HEm58rN5u4V:b-a6hro0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e432b4712646cd2fce0d325da51b9a901e225f38/pkg/sql/sqlbase/column_type_properties.go#L151)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

it is odd that this code is appearing in a function called `LimitValueWidth` -- minimally we need an updated function comment.
</blockquote></details>

Yes, I've updated the function naming and comments.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49195#-:-M7jB-Ws2xI21iUUBAkx:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
tftr!

bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
flake

bors r=sumeerbhola

**Pull request merged**
