### PR TITLE
pkg: Add support for user specified target cols in IMPORT INTO

### PR DESCRIPTION
**Pull request by adityamaru27**
This change adds the ability for users to specify a subset of the columns of an existing table to import into, from a CSV data source. 
(Part of the larger roadmap #26834)

### CODE REVIEW

**Review by dt — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 11 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39023)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27 and @dt)

___
*[pkg/ccl/importccl/import_stmt.go, line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39023#-LkPqyUj6Bb_JPOLuWKY:-LkPqyUj6Bb_JPOLuWKZ:bt4q7qk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0d807db9578c005f016c352595873d2ddb9eaa1/pkg/ccl/importccl/import_stmt.go#L440)):*
> ```Go
> 				intoCols = append(intoCols, name.String())
> 			}
> 			tableDetails = []jobspb.ImportDetails_Table{{Desc: &importing, IsNew: false, TargetCols: intoCols}}
> ```

should we be checking that the named cols are actually valid here?

I think we also want to validate that every column is not targetted has a default if we support filling defaults or has an implicit null default and is nullable, otherwise there is no point in starting the import, right?
___
*[pkg/ccl/importccl/import_stmt.go, line 631 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39023#-Lk_YsYy4qzYI3D7votj:-Lk_YsYy4qzYI3D7votk:b-tzsazz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0d807db9578c005f016c352595873d2ddb9eaa1/pkg/ccl/importccl/import_stmt.go#L631)):*
> ```Go
> 	parentID sqlbase.ID,
> 	tables map[string]*sqlbase.TableDescriptor,
> 	targetCols map[string]*distsqlpb.ReadImportDataSpec_TargetColList,
> ```

minor nit here/throughout: as a reader, I had a little trouble with this type and knowing what it was/how to read it at first glance. I think I managed to figure it out but the parts I struggled with were what are the keys (string could be anything) and then, is it the same as the `tables` map right above it? if so, should we just be changing that to contain structs? if not, when/why is it different? also, if `*distsqlpb.ReadImportDataSpec_TargetColList` is just a long-winded `[]string` maybe we could use that for internal calls and just wrap it in the proto message when building the spec proto.

Anyway, this is all just personal preference / style opinion, and I realize you've spent more time in here figuring what you need to plumb though than I have, so I'm fine with it as-is if you are.
___
*[pkg/sql/row/row_converter.go, line 231 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39023#-Lk_cmMT5vki6UYaCaqq:-Lk_cmMT5vki6UYaCaqr:b-9sz0up) ([raw file](https://github.com/cockroachdb/cockroach/blob/adabb7b08295c91b3a92147972a34820089a73c1/pkg/sql/row/row_converter.go#L231)):*
> ```Go
> 
> 	var txCtx transform.ExprTransformContext
> 	// Although we don't yet support DEFAULT expressions on visible columns,
> ```

can you update this comment to clarify how targeting fewer columns works w.r.t. defaults?

I think I gather that we don't support DEFAULT yet (we should for non-targeted cols) but what does that mean?

**Review by adityamaru27 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39023)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/importccl/import_stmt.go, line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39023#-LkPqyUj6Bb_JPOLuWKY:-LkjNb41EO5XBlvS5Y-C:b-gmix05) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0d807db9578c005f016c352595873d2ddb9eaa1/pkg/ccl/importccl/import_stmt.go#L440)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

should we be checking that the named cols are actually valid here?

I think we also want to validate that every column is not targetted has a default if we support filling defaults or has an implicit null default and is nullable, otherwise there is no point in starting the import, right?
</blockquote></details>

Done. Added a validity check for named cols, also added a check to disallow DEFAULT expressions and non-nullable non-target columns.
___
*[pkg/ccl/importccl/import_stmt.go, line 631 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39023#-Lk_YsYy4qzYI3D7votj:-LkeVgYz6M3ZRh5_0JP4:bk129nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0d807db9578c005f016c352595873d2ddb9eaa1/pkg/ccl/importccl/import_stmt.go#L631)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

minor nit here/throughout: as a reader, I had a little trouble with this type and knowing what it was/how to read it at first glance. I think I managed to figure it out but the parts I struggled with were what are the keys (string could be anything) and then, is it the same as the `tables` map right above it? if so, should we just be changing that to contain structs? if not, when/why is it different? also, if `*distsqlpb.ReadImportDataSpec_TargetColList` is just a long-winded `[]string` maybe we could use that for internal calls and just wrap it in the proto message when building the spec proto.

Anyway, this is all just personal preference / style opinion, and I realize you've spent more time in here figuring what you need to plumb though than I have, so I'm fine with it as-is if you are.



</blockquote></details>

Thanks for this suggestion, the map tables and targetCols did have a 1:1 relation so I just made tables have structs instead. This allowed us to avoid plumbing the TargetColList separately and made it cleaner.
___
*[pkg/sql/row/row_converter.go, line 231 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39023#-Lk_cmMT5vki6UYaCaqq:-Lkf1J0jDXzW-_XLq-qq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adabb7b08295c91b3a92147972a34820089a73c1/pkg/sql/row/row_converter.go#L231)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

can you update this comment to clarify how targeting fewer columns works w.r.t. defaults?

I think I gather that we don't support DEFAULT yet (we should for non-targeted cols) but what does that mean?
</blockquote></details>

Done.

**Comment by adityamaru27** [comment]
@dt RFAL. Addressed comments and added some more tests to ensure we do not support DEFAULT expression, or non-nullable non-target columns.

**Review by dt — APPROVED** [review]

**Comment by adityamaru27** [comment]
TFTR!
bors r+

**Pull request merged**
