### PR TITLE
storage/engine: add EncryptedFS and FileCipherStreamCreator for encrypted files in Pebble

### PR DESCRIPTION
**Pull request by sumeerbhola**
The EncryptedFS uses FileCipherStreamCreator to create a FileStream that does
encryption/decryption. The fileCipherStream implementation of FileStream does
AES in CTR mode. The FileCipherStreamCreator wraps a PebbleKeyManager to
lookup keys by id or to get the active key.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
Please ignore the key_manager files. I am unclear on how to hide files from one PR included in another PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-:-Ls3Nql856jlNvyRx0TG:b-nnq816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

**Review by petermattis — COMMENTED** [review]
> Please ignore the key_manager files. I am unclear on how to hide files from one PR included in another PR.

You can't. The best you can do is put them in a separate commit and let the reviewer know.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-:-Ls3PxYk3b74n8-PlQIG:bcbx29)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3SXRQ2F4TTc8wcRpc:-Ls3SXRQ2F4TTc8wcRpd:b-upel1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L27)):*
> ```Go
> type FileCipherStreamCreator struct {
> 	envType enginepb.EnvType
> 	// Set keyManager when creating, but do not use it.
> ```

The `do not use it` comment is a bit strange in Go. Perhaps you should provide a "constructor" function for `FileCipherStreamCreator`.
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3X_nE0HtbGSyYDSyr:-Ls3X_nE0HtbGSyYDSys:b-8tcw0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L111)):*
> ```Go
> }
> 
> func (s *fileCipherStream) Encrypt(fileOffset int64, data []byte) {
> ```

The corresponding code which does this in C++ is in crypto++, right? Do you have a pointer to the actual loop. I wanted to verify we're handling partial blocks identically.
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3TW2UDDNoAw7vAiKl:-Ls3TW2UDDNoAw7vAiKm:b-a42xvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L118)):*
> ```Go
> 	blockOffset := int(fileOffset % int64(ctrBlockSize))
> 	dataScratch := make([]byte, ctrBlockSize)
> 	ivScratch := make([]byte, ctrBlockSize)
> ```

One allocation is better than two. Here are some tricks:

```
var buf struct {
  dataScratch [ctrBlockSize]byte
  ivScratch [ctrBlockSize]byte
}
```

You can use arrays rather than `make` because `ctrBlockSize` is a constant. By placing the arrays in a struct, a single allocation will be performed.

Can you add a `TODO` that we might want to use `sync.Pool` allocation here for these temporary buffers. Otherwise we're doing memory allocation on every call to `Encrypt` and `Decrypt` which will be bad for performance. If we do pool allocation, we'll need to be careful about zeroing (see below).
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3WhY26CBiO3FOBl-0:-Ls3WhY26CBiO3FOBl-1:b-ewntwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L128)):*
> ```Go
> 		if byteCount < int(ctrBlockSize) {
> 			// Need to copy into dataScratch, starting at blockOffset.
> 			copy(dataScratch[blockOffset:blockOffset+byteCount], data[:byteCount])
> ```

There is something that is subtly correct here: `dataScratch[blockOffset+byteCount:ctrBlockSize]` needs to be zeroed. The only reason that is zeroed is because we'll only hit this code path once and `dataScratch` is initialized via `make` which guarantees it zeroes data. I'd feel better if we added a line before the copy like:

```
  dataScratch = [ctrBlockSize]byte{}
```

Note this is presuming that you change `dataScratch` to be defined as `var dataScratch [ctrBlockSize]byte`.
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3WNBw0lfCPi51B6ju:-Ls3WNBw0lfCPi51B6jv:b-vkhno7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L130)):*
> ```Go
> 			copy(dataScratch[blockOffset:blockOffset+byteCount], data[:byteCount])
> 			s.bcs.transform(blockIndex, dataScratch, ivScratch)
> 			// Copy the encrypted data back into data.
> ```

Nit: perhaps `s/encrypted/transformed/g` as this routine is also used for decryption.
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3V1rA0BUKkW7S4wPy:-Ls3V1rA0BUKkW7S4wPz:b28z7db) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L149)):*
> ```Go
> type cTRBlockCipherStream struct {
> 	key     *enginepbccl.SecretKey
> 	nonce   []byte
> ```

I wonder if this should be `[ctrNonceSize]byte` so that it doesn't share the same memory with `Settings.Nonce`. I'm suggesting this for defensive purposes against bugs which accidentally write to `nonce`.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3XuaX6U3VcDfwVYlZ:-Ls3XuaX6U3VcDfwVYl_:b-l3bv8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L57)):*
> ```Go
> // keys are "plain".
> //
> // For query path spilling to disk: we want to use encryption, but the registries do not need
> ```

`query path` is an unusual term in the CRDB code base. Perhaps `query execution`.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3aw8W1xmwaHdkRQhE:-Ls3aw8W1xmwaHdkRQhF:b-58gebh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L69)):*
> ```Go
> 
> // EncryptedFile implements vfs.File.
> type EncryptedFile struct {
> ```

Does this need to be exported? I suppose I could have asked that question for many of the types in these PRs.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3beKi1iGWcY70tMd6:-Ls3beKi1iGWcY70tMd7:b-r0y37n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L70)):*
> ```Go
> // EncryptedFile implements vfs.File.
> type EncryptedFile struct {
> 	file    vfs.File
> ```

If `EncryptedFile` is unexported, you can change this field to "embed" `vfs.File`:

```
type encryptedFile struct {
  vfs.File
}
```

The benefit of doing this is that `encryptedFile` automatically "inherits" any `vfs.File` methods except for the ones you redefine. This would allow you to get rid of `Close()`, `Stat()`, and `Sync()`. It also has a more subtle benefit in that `vfs.SyncingFile` should still work efficiently as `encryptedFile.Fd()` will be exposed. 
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3bTNf3tKqzAYavZKg:-Ls3bTNf3tKqzAYavZKh:b-a1nrq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L98)):*
> ```Go
> 	f.mu.Lock()
> 	defer f.mu.Unlock()
> 	n, err = f.file.ReadAt(p, f.mu.rOffset)
> ```

Could this be `f.ReadAt(p, f.mu.rOffset)`? Doing that would capture the decryption without needing to repeat it here.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3dbca7K7vnfFK37EU:-Ls3dbca7K7vnfFK37EV:b-a5xn10) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L197)):*
> ```Go
> 		return err
> 	}
> 	return fs.fileRegistry.MaybeDeleteEntry(name)
> ```

Not for this PR: seeing how these file registry methods are used makes me think they should be named `Delete`, `Rename`, `Create`, `Link`, etc.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3cKU_3_G7J4936H2D:-Ls3cKU_3_G7J4936H2E:b-ss7tg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L220)):*
> ```Go
> }
> 
> // Everything below just forwards to the underlying fs.
> ```

See my comments about `encryptedFile`. Same applies to embedding `vfs.FS` in `encryptedFS` so you don't have to do this forwarding.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs_test.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3c_mlAm9eJZO9J1TC:-Ls3c_mlAm9eJZO9J1TD:b7a07sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L53)):*
> ```Go
> 	fs := &EncryptedFS{fs: memFS, fileRegistry: fileRegistry, streamCreator: streamCreator}
> 
> 	// Style (and most code) is from Pebble's mem_fs_test.go. We are mainly testing the integration of
> ```

Note that code was inherited for go-leveldb. I don't particularly mind this style, though `datadriven` would be better in both instances.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41934)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3SXRQ2F4TTc8wcRpc:-LsCjiIe0BgH_6t6e-Eh:bawk4vm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L27)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The `do not use it` comment is a bit strange in Go. Perhaps you should provide a "constructor" function for `FileCipherStreamCreator`.
</blockquote></details>

I think this is me halfway between C++ and Go. With package private members of a `type Foo struct`, it isn't typically clear when they can be directly accessed within the package and when other things in the package should only access via the functions defined on `Foo`. This was an attempt to clarify this, but I don't see it being done in Pebble, so I am assuming this is unnecessary so I've just removed the comment. Defining a "constructor" would not have eliminated the purpose of the comment.
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3X_nE0HtbGSyYDSyr:-LsCm7UpEOLQH3VJPv1_:b-4ynsjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L111)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The corresponding code which does this in C++ is in crypto++, right? Do you have a pointer to the actual loop. I wanted to verify we're handling partial blocks identically.
</blockquote></details>

It is in `c-deps/libroach/rocksdbutils/env_encryption.cc` in `BlockAccessCipherStream::Encrypt()` (the C++ code has more layers of abstraction so one has to jump around more -- some of it maybe because we need to conform to the RocksDB interfaces).
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3TW2UDDNoAw7vAiKl:-LsCp2Ao65jG5LfpGiUv:b-hdx5va) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L118)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

One allocation is better than two. Here are some tricks:

```
var buf struct {
  dataScratch [ctrBlockSize]byte
  ivScratch [ctrBlockSize]byte
}
```

You can use arrays rather than `make` because `ctrBlockSize` is a constant. By placing the arrays in a struct, a single allocation will be performed.

Can you add a `TODO` that we might want to use `sync.Pool` allocation here for these temporary buffers. Otherwise we're doing memory allocation on every call to `Encrypt` and `Decrypt` which will be bad for performance. If we do pool allocation, we'll need to be careful about zeroing (see below).
</blockquote></details>

Thanks for the suggestion. Done. I'm guessing that most calls to Encrypt() will pass large enough `data` (like a 32KB ssblock) that the cost of the single allocation will not be significant.
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3WhY26CBiO3FOBl-0:-LsCqOTiBUBcIu-lr2Vz:b-qlebmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L128)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

There is something that is subtly correct here: `dataScratch[blockOffset+byteCount:ctrBlockSize]` needs to be zeroed. The only reason that is zeroed is because we'll only hit this code path once and `dataScratch` is initialized via `make` which guarantees it zeroes data. I'd feel better if we added a line before the copy like:

```
  dataScratch = [ctrBlockSize]byte{}
```

Note this is presuming that you change `dataScratch` to be defined as `var dataScratch [ctrBlockSize]byte`.
</blockquote></details>

I didn't understand why anything needs to be zeroed. We only care about the bytes that we are copying in and out of `dataScratch` -- the other bytes, that we don't care about, will also be operated on by `Transform()` but their values don't matter. 
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3WNBw0lfCPi51B6ju:-LsCr3Rj5fyGAtRTYNRW:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L130)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: perhaps `s/encrypted/transformed/g` as this routine is also used for decryption.
</blockquote></details>

Done
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3V1rA0BUKkW7S4wPy:-LsCsO_b-oTDZivV-75Z:b-fohime) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L149)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if this should be `[ctrNonceSize]byte` so that it doesn't share the same memory with `Settings.Nonce`. I'm suggesting this for defensive purposes against bugs which accidentally write to `nonce`.
</blockquote></details>

Good point -- done.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3XuaX6U3VcDfwVYlZ:-LsCsnHJ555aDmR119V9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L57)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`query path` is an unusual term in the CRDB code base. Perhaps `query execution`.
</blockquote></details>

Done.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3aw8W1xmwaHdkRQhE:-LsCt2TnCfxwA2scVlPK:b-psekw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L69)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does this need to be exported? I suppose I could have asked that question for many of the types in these PRs.
</blockquote></details>

Changed to not export. I wasn't sure which package the integration code would live in so I exported them -- but I should have not exported them and changed to export if needed. I'll make a pass when writing the integration code to fix that.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3beKi1iGWcY70tMd6:-LsCvjHMDxy1QyKFQn6G:bpkt8i2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L70)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If `EncryptedFile` is unexported, you can change this field to "embed" `vfs.File`:

```
type encryptedFile struct {
  vfs.File
}
```

The benefit of doing this is that `encryptedFile` automatically "inherits" any `vfs.File` methods except for the ones you redefine. This would allow you to get rid of `Close()`, `Stat()`, and `Sync()`. It also has a more subtle benefit in that `vfs.SyncingFile` should still work efficiently as `encryptedFile.Fd()` will be exposed. 
</blockquote></details>

Done. I had not noticed earlier how `SyncingFile` works with `Fd()`.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3bTNf3tKqzAYavZKg:-LsCwywi-YmCFiO0YCd2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L98)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Could this be `f.ReadAt(p, f.mu.rOffset)`? Doing that would capture the decryption without needing to repeat it here.
</blockquote></details>

Done.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3dbca7K7vnfFK37EU:-LsCx3212rdUFsCu0Qnw:bfmc3e1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L197)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Not for this PR: seeing how these file registry methods are used makes me think they should be named `Delete`, `Rename`, `Create`, `Link`, etc.
</blockquote></details>

Ack. I think the link and rename cases will return an error from the wrapped `FS` call if the `oldname` does not exist and so we won't call `FileRegistry`. Not sure what happens in the `FS.Remove()`.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3cKU_3_G7J4936H2D:-LsCzZnx-FGPkH8fEjPA:b24yh9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L220)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

See my comments about `encryptedFile`. Same applies to embedding `vfs.FS` in `encryptedFS` so you don't have to do this forwarding.
</blockquote></details>

Done. It is much better now.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs_test.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3c_mlAm9eJZO9J1TC:-LsDYVa18z6mYcBDryfO:bf3e760) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L53)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Note that code was inherited for go-leveldb. I don't particularly mind this style, though `datadriven` would be better in both instances.
</blockquote></details>

Ack. I am assuming you are ok with not converting this to `datadriven`.

**Review by petermattis — APPROVED** [review]
:lgtm: modulo a small comment about type aliases.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-:-LsDe2Pe9M0jJWf6usLF:b-ydq1ht)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3SXRQ2F4TTc8wcRpc:-LsDdezLEtJRvB0-8glk:bmay29) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L27)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this is me halfway between C++ and Go. With package private members of a `type Foo struct`, it isn't typically clear when they can be directly accessed within the package and when other things in the package should only access via the functions defined on `Foo`. This was an attempt to clarify this, but I don't see it being done in Pebble, so I am assuming this is unnecessary so I've just removed the comment. Defining a "constructor" would not have eliminated the purpose of the comment.
</blockquote></details>

Yeah, commenting the access to members typically done in Go. Perhaps that is to our detriment.
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3X_nE0HtbGSyYDSyr:-LsDbqyM49Dw0G3v3P57:b-5kbawn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L111)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It is in `c-deps/libroach/rocksdbutils/env_encryption.cc` in `BlockAccessCipherStream::Encrypt()` (the C++ code has more layers of abstraction so one has to jump around more -- some of it maybe because we need to conform to the RocksDB interfaces).
</blockquote></details>

Thanks for the pointer.
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3TW2UDDNoAw7vAiKl:-LsDbsGCA66qxvj6zSMj:b-kzyewa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L118)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Thanks for the suggestion. Done. I'm guessing that most calls to Encrypt() will pass large enough `data` (like a 32KB ssblock) that the cost of the single allocation will not be significant.
</blockquote></details>

Ok. Looks fine for now.
___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3WhY26CBiO3FOBl-0:-LsDbuUy0xFrO6nYzFRd:bopi69a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L128)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand why anything needs to be zeroed. We only care about the bytes that we are copying in and out of `dataScratch` -- the other bytes, that we don't care about, will also be operated on by `Transform()` but their values don't matter. 
</blockquote></details>

Ah, I was incorrectly assuming that the block cipher was considering all of the input bytes. But we're in CTR mode which means we're encrypting the nonce+counter and then xor'ing that with the data. 
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3aw8W1xmwaHdkRQhE:-LsDcfagCM6EtfAs8ns7:b-kraain) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L69)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Changed to not export. I wasn't sure which package the integration code would live in so I exported them -- but I should have not exported them and changed to export if needed. I'll make a pass when writing the integration code to fix that.
</blockquote></details>

The integration with ccl code is interesting. It is fine for ccl code to call non-ccl code directly, but not vice-versa. The way this often works is that the non-ccl code provides some sort of hook, which the ccl populates.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-LsDd4k14E27PYpPCFrg:-LsDd4k14E27PYpPCFrh:btr63oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/318014f1957603a1c126cb1bf1382178db2e453b/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L67)):*
> ```Go
> // - The data-FS wraps a base-FS for reading/writing data.
> 
> type vfsFile = vfs.File
> ```

This type alias isn't doing much. The ones in Pebble are often exposing types defined in `internal` packages which otherwise aren't available. That's not needed here. The `encryptedFile` methods can access methods on the embedded `vfs.File` as `f.File.Write`, etc.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs_test.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3c_mlAm9eJZO9J1TC:-LsDdaUi8e30iIXGPdEh:b-m6m7zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L53)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Ack. I am assuming you are ok with not converting this to `datadriven`.
</blockquote></details>

Yeah, this is fine for now.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41934)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/ctr_stream.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-Ls3WhY26CBiO3FOBl-0:-LsHmOs53aaVpctqrNAJ:bj6wed6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a96c1d8399fbec76dac116af7c914f3d44f00dae/pkg/ccl/storageccl/engineccl/ctr_stream.go#L128)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ah, I was incorrectly assuming that the block cipher was considering all of the input bytes. But we're in CTR mode which means we're encrypting the nonce+counter and then xor'ing that with the data. 
</blockquote></details>

I added a comment here and at `FileStream`.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-LsDd4k14E27PYpPCFrg:-LsHmicRDCI-YzaiQO_o:b-2sddf) ([raw file](https://github.com/cockroachdb/cockroach/blob/318014f1957603a1c126cb1bf1382178db2e453b/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L67)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This type alias isn't doing much. The ones in Pebble are often exposing types defined in `internal` packages which otherwise aren't available. That's not needed here. The `encryptedFile` methods can access methods on the embedded `vfs.File` as `f.File.Write`, etc.
</blockquote></details>

I was not able to get `f.vfs.File.Write` to work so I thought I needed to do this. Fixed.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41934)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41934#-:-LsIX9Y52lMTMlZZ0zwE:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @sumeerbhola)

**Pull request merged**
