### PR TITLE
timeutil: embed time zone data into CockroachDB

### LINKED ISSUE #31978: sql: tzinfo can be inconsistent across nodes
CockroachDB relies on each node's tzinfo data for resolving named timezones like `America/New_York` and for applying daylight-savings rules.  This can lead to inconsistent results across a cluster when coercing date/time strings into temporal types.

The desired solution is to store tzinfo data as a system table, to be bootstrapped and maintained by a tzinfo distribution baked into the cockroach binary.

This would also make it easier to implement #31710 to support (custom) timezone abbreviations.

### LINKED ISSUE #36864: sql: stop relying on `time.LoadLocation` for time zone data
### Summary of the problem

CockroachDB uses the Go language's idea of where time zones are defined, and this is non-standard. This breaks time zone support in some environments, most notably Windows.

### Workarounds

- run on an OS platform where Go has proper timezone support (e.g. Linux)
- get a copy of `zoneinfo.zip` from the Go sources and set the env var ZONEINFO to point to it
- install the Go sources and set `GOROOT` to point to them

Note: since 20.1 a node will refuse to start up  (#45680) if the tzdata is not available. It is possible to forcefully start a node (and cause inconsistent time results in SQL) via the env var `COCKROACH_INCONSISTENT_TIME_ZONES`.

### Description of the problem

CockroachDB currently uses Go's standard `time.LoadLocation` to load time zone data.

However Go's standard `time` package is very simple/dumb. It takes the time zone name given as a file name, tries to open that in the system-wide tzdata directory, and satisfies itself with what it finds there. If the file does not exist (as would happen if the given string is mis-cased), tough luck.

There are multiple problems with this design:

- it doesn't recognize time zone names if the casing of the provided string does not match the casing of the file name.  #36847
- on some platforms (eg Windows) the file names are not the same as on POSIX. #32415
- different system underlying different nodes in the same CockroachDB cluster can have different versions / names for the time zone files.  #31978
- in general, one should never take a user-provided string and use that to open a file -- for example on Windows, the current Go library code would enable the user of an app like CockroachDB to deadlock the process, by requesting e.g. the time zone `con` or `com1` or one of the special windows file names.

**Solution**

CockroachDB should:

- embed its own copy of a time zone database (like postgres does? I'm not sure)
- it should only accept time zone names that are known to be valid/exist when cockroachdb was built (to avoid trying to open a file with a special name)
- it should provide its own custom time zone loader, which knows how to find time zone names case-insensitively.

Another approach would be to scan the system-wide timezone database upon process start-up and then normalize the name cases in an in-RAM cache.

### PR DESCRIPTION
**Pull request by otan**
* Use 4d63.com/tz to embed timezone data.
* Modify timeutil.LoadLocation to use this data.
* Remove cli checks for tzdata.
* Add lint rule to use timeutil.LoadLocation

The binary size changes by ~1MB here.

full credits to @gliptak for linking.
Informs #36864 
Refs #31978 

Release note (general change): The timezone data is now built in to the
CockroachDB binary, thus no longer relying on the system tzdata for
locations.

### CODE REVIEW

**Comment by knz** [comment]
Sorry I don't get it - why did you opt for a 3rd party package instead of using the facility we get for free in go 1.15?

**Comment by otan** [comment]
I recall we're waiting for Go 1.16 before an upgrade.

**Review by knz — APPROVED** [review]
I think this PR as-is is a good intermediate step even if go 1.15 makes it even simpler in the future
:lgtm_strong: 

Also @awoods187 @bdarnell motion to backport this to 20.2? The change seems minimal.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55377#-:-MJD7IPu0f1KLHkwOn7Q:b1mplaz)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
> do you think we could consider go 1.15 for crdb v21.1 if 1.16 is not there on time?

Yes, this is what we had decided upon when we switched back to go 1.13. We're going to switch to go 1.15 early in the next release cycle (a week or two after v20.2 is out the door). go 1.16 won't be released until 2021, so it's not clear whether it will land in time for us to use it in v21.1.

**Comment by otan** [comment]
I think i'm still in favour of this solution as it is patchable to allow lower case time zone comparisons (https://github.com/cockroachdb/cockroach/issues/36847), as well as a good safety net in case go 1.15's partial fix does not work out and we need to go back to 1.13.

(also backportable to 20.2 if we chose to)

**Comment by knz** [comment]
Yes your PR is good to go as-is. Your argument is sound.

**Comment by bdarnell** [comment]
The go 1.15 tzdata package is used as a fallback - if external time zone data is found on this system, it will be used instead. This package uses the embedded data as the sole source. That means you lose the ability to update the tzdata package as updates occur, which is sometimes significant as governments like to change DST rules on short notice. (and it appears that this package tracks the zoneinfo files as embedded in Go, rather than the upstream sources from IANA). 

This feels like a significant regression to me, although maybe it's not one in practice since docker makes it impractical to manage tzdata updates in the traditional way and I've not heard of anyone who cares or even notices. 

Neither this change nor the go 1.15 solution completely solve #31978. With external tzdata, there is a window of inconsistency when a new version of the tzdata package is rolled out, but this is a low-risk change so it (can be) done rapidly across the fleet. Embedding tzdata in the binary means that your time zone data is inconsistent for the duration of your CRDB canary and upgrade process, which can be quite long. 

>  it is patchable to allow lower case time zone comparisons

But the author does not intend to keep updating it after go 1.16 is released, so this would put us on the hook for future maintenance. 

So I'm 👎  on backporting this to 20.2, although it would have the nice side effect of letting us more easily use `ubi-minimal` in #54812.

**Comment by knz** [comment]
ok so maybe this PR should not be marked to solve #31978 - there would be more work needed afterwards (store the tzdata in-db to ensure it's consistent across all nodes)

**Comment by knz** [comment]
@bdarnell regardless of whether we adopt this PR or adopt go 1.15, what do you think the future looks like?

It seems to be that we are committed to running CockroachDB inside containers, and that goes with keeping the system image immutable at run-time.

So the only way to "pick up the latest IANA changes" is to re-bake the container base image, while keeping the CockroachDB version constant.

So do you think that's going to be our process (in theory)?
1. every X months, re-bake the system image, pick up OS-level dependency changes
2. push that new docker image to our users so they can pick up changes

If we were to recommend this, why do you think it's better to depend on system-level tzdata, instead of an archive we'd inject ourself at step (1)?

Finally, what do you recommend should be a good next step for @otan here?

**Comment by otan** [comment]
We could introduce an env variable to use a tzdata from a user compiled archive instead of our embedded version if we so choose (or even the system one). I think a user can mount this onto each docker image (or in the case of k8s use a config map) if they wanted to pursue this avenue. 

Alternatively, we could make using the system one the default and falling back to the embedded version in 20.2 if we so choose (of course, we should log this in cli/start or demo). 

(To fully solve #31978 it sounds like tzdata should be stored in the database as part of a system table, which is also gross as updating it with IANA sounds like a painful primitive and needing to use internal executors everywhere to fetch this metadata. I suppose that solution fixes this too but I'm not sure if this is viable. )

**Comment by otan** [comment]
> So I'm 👎 on backporting this to 20.2, although it would have the nice side effect of letting us more easily use ubi-minimal in #54812.

Looks like #55467 takes care of that.

I guess that just leaves the remaining question of whether this is "better" than having the tzdata behaviour depend on the system.

**Comment by otan** [comment]
alrighty, since we're going to go1.15 soon, i'll leave this alone

**Pull request closed without merging**
