### PR TITLE
storage: refactor txn status checks to use switch statements

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7159)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_command.go, line 408 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159#-KJw-md_gNYC-LNBhbTR:-KJw-md_gNYC-LNBhbTS:-1718788642) ([raw file](https://github.com/cockroachdb/cockroach/blob/20915732c915cded9388f5017171678a3bb4a20b/storage/replica_command.go#L408)):*
> ```Go
> 
> 		default:
> 			return reply, roachpb.NewTransactionStatusError(
> ```

this should be in the commited case - the default should be "unknown status" or nothing at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_command.go, line 408 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159#-KJw-md_gNYC-LNBhbTR:-KK18hnZRLXVAse53Zs_:-567052921) ([raw file](https://github.com/cockroachdb/cockroach/blob/20915732c915cded9388f5017171678a3bb4a20b/storage/replica_command.go#L408)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this should be in the commited case - the default should be "unknown status" or nothing at all.
</details>
the committed case fallthrough to this. I tried to consolidate it into a single error. The default case should be an error; is there a problem with this error? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_command.go, line 408 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159#-KJw-md_gNYC-LNBhbTR:-KK1A3heEM4JZEPs0zL7:-1308188312) ([raw file](https://github.com/cockroachdb/cockroach/blob/20915732c915cded9388f5017171678a3bb4a20b/storage/replica_command.go#L408)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> the committed case fallthrough to this. I tried to consolidate it into a single error. The default case should be an error; is there a problem with this error? 
</details>
This error is appropriate for roachpb.COMMITTED, but not for some yet-unintroduced variant, which is what this `default` style is typically used for (including in this very commit where you return `fmt.Sprintf("bad txn status: %s", reply.Txn)`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica_command.go, line 408 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159#-KJw-md_gNYC-LNBhbTR:-KK6_AX1JBD1O9waLaxM:-976924270) ([raw file](https://github.com/cockroachdb/cockroach/blob/20915732c915cded9388f5017171678a3bb4a20b/storage/replica_command.go#L408)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> This error is appropriate for roachpb.COMMITTED, but not for some yet-unintroduced variant, which is what this `default` style is typically used for (including in this very commit where you return `fmt.Sprintf("bad txn status: %s", reply.Txn)`).
</details>
I've changed it to return an error for COMMITTED and return a new error for the default clause. Is this what you wanted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_command.go, line 410 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159#-KKBHJytHTWFRPLAuajh:-KKBHJytHTWFRPLAuaji:-425559926) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7c90b60c0ee1f7361189be54fc734b12f1b14b/storage/replica_command.go#L410)):*
> ```Go
> 
> 		default:
> 			return reply, roachpb.NewTransactionStatusError(
> ```

why not do exactly what you have below?
```
return reply, roachpb.NewTransactionStatusError(
			fmt.Sprintf("bad txn status: %s", txn))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica_command.go, line 410 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159#-KKBHJytHTWFRPLAuajh:-KKBWT5nUirCQeGi3hO_:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7c90b60c0ee1f7361189be54fc734b12f1b14b/storage/replica_command.go#L410)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why not do exactly what you have below?
> ```
> return reply, roachpb.NewTransactionStatusError(
> 			fmt.Sprintf("bad txn status: %s", txn))
> ```
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> #### storage: refactor txn status checks to use switch statements
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7159#-:-KKBXKmePPfSZ4ToGwzm:1417088721)*

**Pull request merged**
