### PR TITLE
sql: add support for logging full table/index scans to slow query log

### LINKED ISSUE #45616: sql: add option to log queries resulting in full table scans
We have received several requests to have some way to log which queries are resulting in table scans in order to help users identify where they have missing indexes. Ideally this would function as a toggle for the slow query log, so that queries resulting in table scans appeared alongside long running statements. Note that queries resulting in full table scans would _not_ need to meet the slow query threshold in order to be logged. A related setting to set a floor on the number of rows scanned would help with avoiding tables with very few records where indexes are not necessary. 

MySQL has a similar configuration option for their slow query log. See the `log_queries_not_using_indexes` parameter [here](https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html#slow-query-log-parameters). They also offer an option to rate limit the collection of queries without indexes to avoid runaway slow query log file growth. They also mention that they distinguish between [full table scans and queries without indexes](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_log_queries_not_using_indexes). 

We have had several users request this functionality because it enables them to test new deployments and catch table scans in test environments that may have little data, resulting in relatively quick full table scans. These scans can then cause issues when deployed to larger data sets in production environments.

### PR DESCRIPTION
**Pull request by arulajmani**
This commit adds support for logging queries that perform a full table
or index scan to the slow query log via an opt-in cluster setting
`sql.log.slow_query.full_table_scans.enabled`.

Previously, queries were only logged to the slow query log if their
duration was over a configured threshold. As now queries can be logged
because they perform a full table/index scan as well, prescence of a
log entry no longer implies the reason it was logged. Thus we also add
a new MECE column to log the reason why a query was logged. The reason
can be one of: `{LATENCY THRESHOLD + FULL TABLE SCAN}`,
`{LATENCY THRESHOLD}`, or `{FULL TABLE/INDEX SCAN}`.

The criteria for queries being logged is that the query performs an
unconstrained scan on either the whole table or one of it's secondary
indexes. Once we support partial indexes, an unconstrained scan on a
partial index will also be logged.

Informs #49617
Closes #45616

Release note (cli change): Adds a new opt-in setting to log queries
that perform full table/secondary index scans to the slow query log.
Users can opt in in using:
`SET CLUSTER SETTING sql.log.slow_query.full_table_scans.enabled=true`.

### CODE REVIEW

**Comment by rohany** [comment]
This looks like what I had in mind. I think it makes sense here to make this state on the `execFactory` and `distsqlSpecExecFactory`. That way we don't need to reset this state in different places. It also feels better that `containsFullScan` is a "result" of building the query rather than another field on the planner. However, this is all moot if you have to add the field onto the planner anyway to get the result over to the logger.

**Review by arulajmani — COMMENTED** [review]
I don't think we can get around having the state accessible from the `planner` one way or the other -- what we can do though is have the state on both the exec factories and extract that state and put it on `planner.curPlan` instead of having it on the `planner` itself. `curPlan` is specific to the "current plan", so that allows us to get rid of the reset stuff happening right now. Does this sound more favourable? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51441#-:-MCEwMhADpwEe5duq2xK:bs7ifq5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

**Comment by rohany** [comment]
Putting it on the planTop sounds good to me.

**Comment by andreimatei** [comment]
There was some nuance about "full table scans" discussed here; maybe keep it in mind:
https://cockroachlabs.slack.com/archives/C8HD41C82/p1583337105033800?thread_ts=1583244432.026800&cid=C8HD41C82

**Comment by arulajmani** [comment]
@andreimatei thanks for pointing me to the Slack thread, I hadn't seen those discussions before. In the current incarnation, this would define "full table scans" as any scan that doesn't limit rows when scanning an index, or the PK of a table. Observations about a couple other things brought up:
- partial indexes: We currently do a constrained scan on partial indexes, so a query that goes over all entries in a partial index will not be logged. 
-  index scan excluding NULLs: I don't see how this is different from scanning an index and then filtering NULLs, so this would be logged. IIUC NULLLs for index columns are encoded, so they will be scanned. 

Considering the scope of this task is to simply log such events when an opt-in cluster setting is enabled, I think it's okay to call out the nuances in the release notes and proceed with the current definition of a full table/index scan (as used by distSQL to recommend if a plan should be distributed or not) . Thoughts?

**Comment by arulajmani** [comment]
Correction on my comment about partial indexes above -- Just talked to @mgartner, and turns out we don't generate a constraint when doing a full scan of a partial index. This would mean that an unconstrained partial index scan is logged as well.

**Comment by arulajmani** [comment]
We could also distinguish between a full secondary index scan and a full primary index scan in the logs if we want. I'm gonna move this discussion to the issue #49617

**Comment by arulajmani** [comment]
@rohany un-WIP-ing this!

**Comment by arulajmani** [comment]
Closing this cuz the full table/index scan detection logic was added in #52278 and this branch is quite out of date now.

**Pull request closed without merging**
