### PR TITLE
roachtest: include some cluster configs in test failure reports

### LINKED ISSUE #80799: roachtest: surface cluster config. params when filing an issue
A new failed roachtest will result in creating a fresh github issue. (If it's a repeat failure, then a new comment is added.)
The issue description doesn't capture essential information pertaining to the cluster configuration. This could lead to wasted (developer) cycles; e.g., see https://github.com/cockroachdb/cockroach/issues/68976#issuecomment-925763750
Some tests randomly enable zfs, encryption, etc.–this context should also be propagated to the issue.

Each roachtest is associated with a `TestSpec` [1] which contains a `ClusterSpec` [2]. The latter can be used to extract the cloud provider, instance type, node count, etc., including whether or not zfs was used. (Determining whether or not encryption is enabled is a separate issue [3]; it needs some refactoring to lift it into `ClusterSpec`.)
The test runner's `maybePostGithubIssue` already receives `TestSpec`; the rest is a matter of choosing a compact while descriptive format to capture the additional (cluster) configuration parameters in order to make it easier for the reader.

[1] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/test/test_interface.go#L20
[2] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/spec/cluster_spec.go#L41
[3] https://github.com/cockroachdb/cockroach/issues/79265#issuecomment-1086380406

Jira issue: CRDB-15509

### PR DESCRIPTION
**Pull request by renatolabs**
This commit changes the 'Parameters' section of a test
failure. Previously, it would only include the contents of the `TAGS`
and `GOFLAGS` environment variables. It now adds cluster configuration
values obtained from the `ClusterSpec`. These parameters are prefixed
with `ROACHTEST` (e.g., `ROACHTEST_cloud`).

For now, just the cloud name, number of CPUs and SSDs are included. In
the future, we can expand this work to support other relevant cluster
configuration values as needed to debug test failures.

Resolves: #80799.

Release note: None.

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed 29 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81845#-:-N32_5Zo76L_XMS_6v1C:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @tbg)

___
*[`pkg/cmd/internal/issues/formatter_unit.go` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81845#-N32UuzL67STmWvpLCE4:-N32UuzL67STmWvpLCE5:b-it30nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb03cebaf81136d83182c4a13f0e6ebee0900cb/pkg/cmd/internal/issues/formatter_unit.go#L84)):*
> ```Go
> 				r.Escaped("Parameters: ")
> 				for i, name := range params {
> 					if i > 0 {
> ```

FIY. A less common pattern removes the conditional, and in some cases might be a tiny bit more efficient,

```
r.Escaped("Parameters: ")
separator := ""

for _, name := range params {
    r.printf(separator)
    r.Code(fmt.Sprintf("%s=%s", name, data.Parameters[name]))
    separator = r.Escaped(", ")
}
```

Personally, I prefer the above because of readability. In terms of performance, there isn't much gain owing to branch prediction; although, maybe the omission of the index variable could help with register allocation pressure on arm64. :)

Fun fact, I learned this style from Rustan Leino [1] while working on proving functional correctness.

[1] http://leino.science/
___
*[`pkg/cmd/internal/issues/issues_test.go` line 360 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81845#-N32ZeYi1QFmM1tNSOn8:-N32ZeYi1QFmM1tNSOn9:byaixvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb03cebaf81136d83182c4a13f0e6ebee0900cb/pkg/cmd/internal/issues/issues_test.go#L360)):*
> ```Go
> 	params := map[string]string{
> 		"GOFLAGS":    "-race_test",
> 		"TEST_cloud": "test",
> ```

should these be fed into `roachtestParam` for consistency?

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81845)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @srosenberg and @tbg)

___
*[`pkg/cmd/internal/issues/formatter_unit.go` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81845#-N32UuzL67STmWvpLCE4:-N3KSPMa-rAwlDnBlDr1:b-pml4f2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb03cebaf81136d83182c4a13f0e6ebee0900cb/pkg/cmd/internal/issues/formatter_unit.go#L84)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

FIY. A less common pattern removes the conditional, and in some cases might be a tiny bit more efficient,

```
r.Escaped("Parameters: ")
separator := ""

for _, name := range params {
    r.printf(separator)
    r.Code(fmt.Sprintf("%s=%s", name, data.Parameters[name]))
    separator = r.Escaped(", ")
}
```

Personally, I prefer the above because of readability. In terms of performance, there isn't much gain owing to branch prediction; although, maybe the omission of the index variable could help with register allocation pressure on arm64. :)

Fun fact, I learned this style from Rustan Leino [1] while working on proving functional correctness.

[1] http://leino.science/
</blockquote></details>

Nice, I don't think I've seen this style before. Even though this path isn't performance sensitive, I updated the code anyway to have this pattern in the codebase.
___
*[`pkg/cmd/internal/issues/issues_test.go` line 360 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81845#-N32ZeYi1QFmM1tNSOn8:-N3KSlHC72Y_-fFWLw4d:bk6kbbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb03cebaf81136d83182c4a13f0e6ebee0900cb/pkg/cmd/internal/issues/issues_test.go#L360)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

should these be fed into `roachtestParam` for consistency?
</blockquote></details>

`roachtestParam` was defined in the test runner. The idea is that the test runner is the component responsible for defining the `ROACHTEST_*` pattern, and the internal "issues" module is unaware of such patterns. So calling that function from this test would not be possible. Since this specific test exists mostly to test the issue reporter end to end (using an actual GitHub token), I think this is fine.

I updated the hardcoded params to use `ROACHTEST_` instead of `TEST_` though since roachtest is (to my understanding) the "main" client of the `issues` package, making the test more representative.

**Review by tbg — APPROVED** [review]
Looks good to me, once the `params` map is moved to `PostRequest` (or an argument has been made why that's a bad idea) :thumbsup: 

> Reviewed 27 of 30 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81845#-:-N3KcMUHEe6qM_coHNd4:b-gxaiuv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/internal/issues/issues.go` line 447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81845#-N3KbLuI2U4SyEh0-U9L:-N3KbLuI2U4SyEh0-U9M:b2lszrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/732144a3a62678dec44929ef73fdea0a2ea39fed/pkg/cmd/internal/issues/issues.go#L447)):*
> ```Go
> // will be returned.
> func Post(
> 	ctx context.Context, formatter IssueFormatter, req PostRequest, params map[string]string,
> ```

Why is `params` not in `PostRequest`? That seems like the canonical place. There's no reason to assume that if you re-used a Poster that one would use the same params for multiple PostRequests.
___
*[`pkg/cmd/internal/issues/testdata/post/failure-matching-and-related-issue.txt` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81845#-N3Kc3751Pjee93RvW1Z:-N3Kc3751Pjee93RvW1_:buck9x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/732144a3a62678dec44929ef73fdea0a2ea39fed/pkg/cmd/internal/issues/testdata/post/failure-matching-and-related-issue.txt#L35)):*
> ```help
> 
> 
> Rendered: https://github.com/cockroachdb/cockroach/issues/new?body=storage.TestReplicateQueueRebalance+%5Bfailed%5D%28https%3A%2F%2Fteamcity.example.com%2FbuildConfiguration%2Fnightly123%2F8008135%3FbuildTab%3Dlog%29+on+release-0.1+%40+%5Babcd123%5D%28https%3A%2F%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fcommits%2Fabcd123%29%3A%0A%0A%0A%60%60%60%0A%09%3Cautogenerated%3E%3A12%3A+storage%2Freplicate_queue_test.go%3A103%2C+condition+failed+to+evaluate+within+45s%3A+not+balanced%3A+%5B10+1+10+1+8%5D%0A%60%60%60%0A%3Cdetails%3E%3Csummary%3EHelp%3C%2Fsummary%3E%0A%3Cp%3E%0A%0ASee+also%3A+%5BHow+To+Investigate+a+Go+Test+Failure+%5C%28internal%5C%29%5D%28https%3A%2F%2Fcockroachlabs.atlassian.net%2Fl%2Fc%2FHgfXfJgM%29%0AParameters%3A+%3Ccode%3EGOFLAGS%3Drace%3C%2Fcode%3E%0A%2C+%3Ccode%3ETEST%3Ddeadlock%3C%2Fcode%3E%0A%2C+%3Ccode%3Ecloud%3Dgce%3C%2Fcode%3E%0A%3C%2Fp%3E%0A%3C%2Fdetails%3E%0A%3Cdetails%3E%3Csummary%3ESame+failure+on+other+branches%3C%2Fsummary%3E%0A%3Cp%3E%0A%0A-+%2331+boom+related+%5BC-test-failure+O-robot+release-0.2%5D%0A%3C%2Fp%3E%0A%3C%2Fdetails%3E%0A%3Csub%3E%0A%0A%5BThis+test+on+roachdash%5D%28https%3A%2F%2Froachdash.crdb.dev%2F%3Ffilter%3Dstatus%3Aopen%2520t%3A.%2ATestReplicateQueueRebalance.%2A%26sort%3Dtitle%2Bcreated%26display%3Dlastcommented%2Bproject%29+%7C+%5BImprove+this+report%21%5D%28https%3A%2F%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Ftree%2Fmaster%2Fpkg%2Fcmd%2Finternal%2Fissues%29%0A%3C%2Fsub%3E%0A&title=%3Ccomment%3E
> ```



Doesn't look quite right. Also, this is still tucked away under the Help menu, I wonder if it's worth promoting it so that it's always visible.



_Code quote:_
```help
https://github.com/cockroachdb/cockroach/issues/new?body=storage.TestReplicateQueueRebalance+%5Bfailed%5D%28https%3A%2F%2Fteamcity.example.com%2FbuildConfiguration%2Fnightly123%2F8008135%3FbuildTab%3Dlog%29+on+release-0.1+%40+%5Babcd123%5D%28https%3A%2F%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fcommits%2Fabcd123%29%3A%0A%0A%0A%60%60%60%0A%09%3Cautogenerated%3E%3A12%3A+storage%2Freplicate_queue_test.go%3A103%2C+condition+failed+to+evaluate+within+45s%3A+not+balanced%3A+%5B10+1+10+1+8%5D%0A%60%60%60%0A%3Cdetails%3E%3Csummary%3EHelp%3C%2Fsummary%3E%0A%3Cp%3E%0A%0ASee+also%3A+%5BHow+To+Investigate+a+Go+Test+Failure+%5C%28internal%5C%29%5D%28https%3A%2F%2Fcockroachlabs.atlassian.net%2Fl%2Fc%2FHgfXfJgM%29%0AParameters%3A+%3Ccode%3EGOFLAGS%3Drace%3C%2Fcode%3E%0A%2C+%3Ccode%3ETEST%3Ddeadlock%3C%2Fcode%3E%0A%2C+%3Ccode%3Ecloud%3Dgce%3C%2Fcode%3E%0A%3C%2Fp%3E%0A%3C%2Fdetails%3E%0A%3Cdetails%3E%3Csummary%3ESame+failure+on+other+branches%3C%2Fsummary%3E%0A%3Cp%3E%0A%0A-+%2331+boom+related+%5BC-test-failure+O-robot+release-0.2%5D%0A%3C%2Fp%3E%0A%3C%2Fdetails%3E%0A%3Csub%3E%0A%0A%5BThis+test+on+roachdash%5D%28https%3A%2F%2Froachdash.crdb.dev%2F%3Ffilter%3Dstatus%3Aopen%2520t%3A.%2ATestReplicateQueueRebalance.%2A%26sort%3Dtitle%2Bcreated%26display%3Dlastcommented%2Bproject%29+%7C+%5BImprove+this+report%21%5D%28https%3A%2F%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Ftree%2Fmaster%2Fpkg%2Fcmd%2Finternal%2Fissues%29%0A%3C%2Fsub%3E%0A&title=%3Ccomment%3E
```

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81845)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @srosenberg and @tbg)

___
*[`pkg/cmd/internal/issues/issues.go` line 447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81845#-N3KbLuI2U4SyEh0-U9L:-N3LUo46ENuyUpbl6a_D:b-lzc16m) ([raw file](https://github.com/cockroachdb/cockroach/blob/732144a3a62678dec44929ef73fdea0a2ea39fed/pkg/cmd/internal/issues/issues.go#L447)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why is `params` not in `PostRequest`? That seems like the canonical place. There's no reason to assume that if you re-used a Poster that one would use the same params for multiple PostRequests.
</blockquote></details>

These parameters are partly defined at the roachtest runner level (e.g., the cluster configuration parameters themselves), and partly in the `issues` package (e.g., branch/tag/stuff read from environment variables). That was the reason I ended up deciding to pass this as an argument.

That said, I agree it makes more sense as part of `PostRequest`. I named it `ExtraParams` (similar to the existing `ExtraLabels`), to make it explicit that default labels (those read from the environment) exist.
___
*[`pkg/cmd/internal/issues/testdata/post/failure-matching-and-related-issue.txt` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81845#-N3Kc3751Pjee93RvW1Z:-N3LVLZN3t6KAo5TUNQI:b-7hr9n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/732144a3a62678dec44929ef73fdea0a2ea39fed/pkg/cmd/internal/issues/testdata/post/failure-matching-and-related-issue.txt#L35)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>



Doesn't look quite right. Also, this is still tucked away under the Help menu, I wonder if it's worth promoting it so that it's always visible.
</blockquote></details>

Ugh, I had tested it without the "See also" section, and it formats properly in that case. I didn't realize having a "help command" would break formatting of the parameters. The ultimate reason is that the behaviour of newlines is different in a "Markdown" context vs in an HTML context, and it's not possible to know which formatting is active when calling the renderer's functions. Not sure if that makes sense, I can try to explain it better if not.

There are at least two possible alternatives: allow for a `Collapsed` block to have multiple paragraphs (currently everything is forced into a single paragraph); or make the Parameters list more visible, as you suggested. I opted for the latter, including the list of parameters under the Message block, outside of the collapsible "Help".

**Review by srosenberg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81845)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @srosenberg and @tbg)

**Comment by renatolabs** [comment]
bors r=srosenberg

**Pull request merged**
