### PR TITLE
ui: update lodash to 4.17.19

### PR DESCRIPTION
**Pull request by nathanstilwell**
Resolve dependabot alerts about lodash

Release note: None

### CODE REVIEW

**Review by koorosh — APPROVED** [review]
LGTM

Could you create PR for `yarn-vendored` as well?
https://github.com/cockroachdb/yarn-vendored/tree/nathanstilwell/lodash-update-4.17.19

**Comment by nathanstilwell** [comment]
> LGTM
> 
> Could you create PR for `yarn-vendored` as well?
> https://github.com/cockroachdb/yarn-vendored/tree/nathanstilwell/lodash-update-4.17.19

Thanks for the reminder.

**Comment by nathanstilwell** [comment]
`yarn-vendored` PR - https://github.com/cockroachdb/yarn-vendored/pull/25

**Pull request merged**
