### PR TITLE
sqlccl: refactor distributed CSV import

### PR DESCRIPTION
**Pull request by madelynnblue**
Previously, there was one SST writer created per split. With large
CSV inputs, that could create upward of 1000+ splits, which translated
into a huge number of distsql processors and streams. Our tests were
OOMing due to this, we believe.

Refactor the distributed CSV import to instead create one SST writer
per node, and assign various splits to it. This limits both the number
of processors and streams. It has the added benefit of naturally
throttling CSV resource usage since now only one SST will be created
and uploaded at once per node (and per IMPORT statement).

To achieve this, change the distsql range router slightly. It now is
able to specify the destination stream, instead of inferring it from
the index of the span spec. This means the previous functionality is
just a special case of the new functionality. Since dist CSV is the
only user of the range router, it should be safe to change here.

We have not documented how to use dist CSV import, so no users should
be affected by this change.

See #19635

Example diagram of the new distsql plan:

ss

### CODE REVIEW

**Comment by a-robinson** [comment]
Nice, @mjibson! Let me know when you think it's ready for me to test on bigger data sets.

**Comment by arjunravinarayan** [comment]
:lgtm:
I'd like to see some large tests to make sure this design doesn't get bottlenecked on something we don't anticipate.

---

Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv.go, line 1536 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-L-Y88N479eVVadmS_hG:-L-Y88N479eVVadmS_hH:b77eb6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b917a897d719e6bd5cde7a06e330736c39754a2/pkg/ccl/sqlccl/csv.go#L1536)):*
> ```Go
> 		}
> 		kv.Key.Key = iter.UnsafeKey()
> 		if bytes.Compare(kv.Key.Key, end) >= 0 {
> ```

why are you using `bytes.Compare` as opposed to `key.Less`? Probably less brittle to not break that abstraction (it uses `bytes.Compare` underneath...).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-:-L-Y8zmuQNq9DUSnmK3C:b-q4xc69)*

**Comment by mjibson** [comment]
Do you mean large CSV IMPORT tests? As soon as this goes in we're going to start testing large sf factors again to see what happens. Is that sufficient, or do you mean large tests in a _test.go file that runs every time?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-:-L-YH2mlqDwxFA9S5XE-:b2depei)*

**Comment by arjunravinarayan** [comment]
I mean a large `CSV IMPORT` test. I don't think unit tests are an appropriate place for large long running tests. What we have right now is sufficient for unit testing.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-:-L-YI4fwEG3m8uLQUNQ6:bz7vlhe)*

**Comment by arjunravinarayan** [comment]
(So yes, that is sufficient)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-:-L-YINVfE1WuHGaNJPkX:bo6qus)*

**Comment by mjibson** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/sqlccl/csv.go, line 1536 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-L-Y88N479eVVadmS_hG:-L-YZ-HM-i0FNr807ELS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b917a897d719e6bd5cde7a06e330736c39754a2/pkg/ccl/sqlccl/csv.go#L1536)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

why are you using `bytes.Compare` as opposed to `key.Less`? Probably less brittle to not break that abstraction (it uses `bytes.Compare` underneath...).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408)*

**Comment by arjunravinarayan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408)*

**Comment by dt** [comment]
:lgtm:

---

Reviewed 8 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-:-L-YZswaUbEhBl4dyvs8:bnfp4nl)*

**Comment by RaduBerinde** [comment]
LGTM, nice.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv_test.go, line 617 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-L-YsqVV5maQQL7WKMZe:-L-YsqVV5maQQL7WKMZf:b-94q01g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b43b4bebda0209d82c3724b3839d8403bb9b3b70/pkg/ccl/sqlccl/csv_test.go#L617)):*
> ```Go
> 	} {
> 		t.Run(tc.name, func(t *testing.T) {
> 			i++
> ```

[nit] Should increment this right before it is used. I had to look around for a bit to figure out what it's for.

---

*[pkg/sql/distsqlrun/data.proto, line 156 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-L-Yt1Rg-vEt0bxmDrkP:-L-Yt1Rg-vEt0bxmDrkQ:b-3utgps) ([raw file](https://github.com/cockroachdb/cockroach/blob/b43b4bebda0209d82c3724b3839d8403bb9b3b70/pkg/sql/distsqlrun/data.proto#L156)):*
> ```protobuf
>       optional bytes start = 1;
>       optional bytes end = 2;
>       optional int32 stream = 3 [(gogoproto.nullable) = false];
> ```

A comment would be good, explaining it's an index (0 to #of streams coming out of that router).

---

*[pkg/sql/distsqlrun/processors.proto, line 480 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-L-YtRv3HhTjAWtxRInh:-L-YtRv3HhTjAWtxRIni:bx1i8o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b43b4bebda0209d82c3724b3839d8403bb9b3b70/pkg/sql/distsqlrun/processors.proto#L480)):*
> ```protobuf
> // for implementation.
> message SSTWriterSpec {
>   message SpanWriter {
> ```

This struct and/or the field deserves a comment. Also, the name is off, it's not a "writer".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-:-L-YupE6gi7zXCFpesp8:b-6ynlgc)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv_test.go, line 617 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-L-YsqVV5maQQL7WKMZe:-L-_QT5xZ-9hsd9yyRoz:b-84jwdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b43b4bebda0209d82c3724b3839d8403bb9b3b70/pkg/ccl/sqlccl/csv_test.go#L617)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Should increment this right before it is used. I had to look around for a bit to figure out what it's for.
</blockquote></details>

It is used on the next line to create a unique database.

---

*[pkg/sql/distsqlrun/data.proto, line 156 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-L-Yt1Rg-vEt0bxmDrkP:-L-_R2_TvWEyVxRHKOhw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b43b4bebda0209d82c3724b3839d8403bb9b3b70/pkg/sql/distsqlrun/data.proto#L156)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

A comment would be good, explaining it's an index (0 to #of streams coming out of that router).
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.proto, line 480 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408#-L-YtRv3HhTjAWtxRInh:-L-_RoUqjv_oUWz6PZ7z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b43b4bebda0209d82c3724b3839d8403bb9b3b70/pkg/sql/distsqlrun/processors.proto#L480)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This struct and/or the field deserves a comment. Also, the name is off, it's not a "writer".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20408)*

**Pull request merged**
