### PR TITLE
go.mod: switch to gogoproto fork

### LINKED ISSUE #134805: deps: switch to using our gogoproto fork
The https://github.com/gogo/protobuf package is no longer being maintained. In order to make improvements to it, we will need to switch to https://github.com/cockroachdb/gogoproto

The repository is used for three different aspects:
 1. Protos: importing `gogo.proto` that define the gogoproto-specific options from `.proto` files
 2. Code generation: Go code for generating pb.go files, used by `protoc-gen-gogoroach`
 3. Runtime: Go packages used by `.pb.go` files, like github.com/cockroachdb/gogoproto/proto

There are a few other `gogo` packages that depend on `gogo/protobuf`. I believe that we can't switch over the runtime aspect without forking these repositories as well.

Switching over just the code generation aspect is not very hard and should be sufficient to allow improving generated code without any new options. It is attempted in #129182

The next step would be to switch over the protos aspect as well, which would enable us to use new options defined only in our fork (we have one: `gogoproto.omitempty`).

Jira issue: CRDB-44258

### PR DESCRIPTION
**Pull request by RaduBerinde**
Use `github.com/cockroachdb/gogoproto` instead of
`github.com/gogo/protobuf`. The former already has a new `omitempty`
option that can clean up some existing hacks, and we want to make more
improvements to the generated code.

Fixes #134805
Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Is there a world here in which we don't need a version in the replace directive? The moment you pin a version, you basically bypass version requirement resolution. I would love to get rid of the replace line for protobuf, which I seem to remember is causing us a lot of trouble and this is also somehow related to gogoproto (it isn't compatible with v2 protobuf?)
I know this isn't _exactly_ in your critical path, but I think we have a little dependency hell here. Forking gogoproto can _probably_ help here, but if we're pinning a version it could also go the other way. Could we get a sense of how deep the pit is? I'm happy to team up on that.

**Comment by tbg** [comment]
Nevermind, we have to provide a version on the right: https://go.dev/ref/mod#go-mod-file-replace
But it seems possible to specify a version on the _left_, which could let us opt out of letting dependencies that use gogoproto see the replacement. I don't know if that is helpful at all but it would reduce the amount of lying.

Re: protobuf, we have `require 	github.com/gogo/protobuf v1.3.2` but then `replace google.golang.org/protobuf => google.golang.org/protobuf v1.29.1`, so we're straight-up lying about which version of googleproto we see. And I think we need that because (something something gogoproto not compatible with newer googleproto). That would be good to lift if we can.

**Review by rickystewart — APPROVED** [review]

**Pull request merged**
