### PR TITLE
opt: lookup joins execution and costing

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change implements the execution path for lookup joins and enables
them by implementing a cost function.

The execution path is distsql-only. For local execution, I temporarily
added a kludge to reuse the hash join code (with a full table scan on
the lookup side).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
@solongordon - if you can take a look over the distsql planning code, that would be great.

**Comment by RaduBerinde** [comment]
CC @asubiotto and @jordanlewis (see the new `lookupJoinNode`)

**Review by andy-kimball — DISMISSED** [review]
:LGTM:, for `opt` related stuff. Looks like we're using `LookupJoin` in appropriate cases, so costing seems like it's working out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-:-LHAhn_X-HravXYT-f9h:b-qf8e0p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/factory.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-LHAbmtr05YBbuKlhWM5:-LHAbmtr05YBbuKlhWM6:blqyejw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cde2408640dfd13ae56a42b11f25e5de9ebfe99/pkg/sql/opt/exec/factory.go#L129)):*
> ```Go
> 	) (Node, error)
> 
> 	// ConstructLookupJoin returns a node that preforms a lookup join.
> ```

NIT: performs
___
*[pkg/sql/opt/exec/execbuilder/testdata/join, line 991 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-LHAeKuSDgzAkGbgOLDD:-LHAeKuSDgzAkGbgOLDE:bd3e6hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cde2408640dfd13ae56a42b11f25e5de9ebfe99/pkg/sql/opt/exec/execbuilder/testdata/join#L991)):*
> ```
> CREATE TABLE r (a INT PRIMARY KEY)
> 
> query TTTTT
> ```

There's an even better plan available here. We should be recognizing that `a` is an equality column and so rejects NULL values on the right side of the join. That allows us to map the `left-join` to `inner-join`, at which point we'd push down the `a = 3` to both sides, and use a simple merge join. Maybe add a comment so we don't forget?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/exec/execbuilder/testdata/join, line 991 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-LHAeKuSDgzAkGbgOLDD:-LHAzRXr9D6BKODfaRNO:b-5wnpw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cde2408640dfd13ae56a42b11f25e5de9ebfe99/pkg/sql/opt/exec/execbuilder/testdata/join#L991)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

There's an even better plan available here. We should be recognizing that `a` is an equality column and so rejects NULL values on the right side of the join. That allows us to map the `left-join` to `inner-join`, at which point we'd push down the `a = 3` to both sides, and use a simple merge join. Maybe add a comment so we don't forget?
</blockquote></details>

That doesn't sound right.. a refers to the "merged" column (defined as COALESCE (l.a, r.a), equivalent to l.a in the left join case).

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/exec/execbuilder/testdata/join, line 991 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-LHAeKuSDgzAkGbgOLDD:-LHBH2t4C7pNmTMCt18Y:bcbxrmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cde2408640dfd13ae56a42b11f25e5de9ebfe99/pkg/sql/opt/exec/execbuilder/testdata/join#L991)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

But you're right, the filter can be pushed to both sides, even if it is a lookup join. I thought the new rules added by @rytaft would do this.
</blockquote></details>

*even if it is a left join

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27409)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/join, line 991 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-LHAeKuSDgzAkGbgOLDD:-LHBZyFS8yrMzMlHkJ6v:b-tbx3pc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cde2408640dfd13ae56a42b11f25e5de9ebfe99/pkg/sql/opt/exec/execbuilder/testdata/join#L991)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

*even if it is a left join
</blockquote></details>

Some more info - the heuristic planner does push down to both sides in this case. This is the PR which added it: https://github.com/cockroachdb/cockroach/pull/20866. The idea is that we can add the remapped filter (`r.a = 3` in this case) to the ON condition without changing the result, and that gets pushed down to the right side.

Also note the issue fixed by that PR: https://github.com/cockroachdb/cockroach/issues/20765  It sounds like this is important for Hibernate.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-:-LHDxIyY4gpPbnCBDjBR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/testdata/join, line 991 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-LHAeKuSDgzAkGbgOLDD:-LHDuBtFBGSCMeNgbXgB:b-nlrx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cde2408640dfd13ae56a42b11f25e5de9ebfe99/pkg/sql/opt/exec/execbuilder/testdata/join#L991)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Some more info - the heuristic planner does push down to both sides in this case. This is the PR which added it: https://github.com/cockroachdb/cockroach/pull/20866. The idea is that we can add the remapped filter (`r.a = 3` in this case) to the ON condition without changing the result, and that gets pushed down to the right side.

Also note the issue fixed by that PR: https://github.com/cockroachdb/cockroach/issues/20765  It sounds like this is important for Hibernate.
</blockquote></details>

Hmm the problem is that the equality is part of the ON condition, not part of the Select filter. We'll need to use the FDs of the input as well as the filter to do the mapping (and also add back a couple of the rules I deleted previously). I can make that change in a separate PR. Filed #27431.

**Review by solongordon — COMMENTED** [review]
The physical planning looks reasonable to me. Few questions that came to mind:
- I noticed you aren't using `JoinReaderSpec.IndexFilterExpr`, which I originally had to add to get the left join logic working properly. Is that no longer necessary, maybe because filters are pushed down differently by the optimizer? (Oh, just saw the discussion relating to this, so maybe this will come into play in https://github.com/cockroachdb/cockroach/issues/27431.)
- Are you handling the "non-covering secondary index" case, where I think we would now want to plan a lookup join followed by an index join? Didn't see this in the test cases.
- Looks like there is still logic to disable the optimizer when the experimental lookup join flag is set. Can that go away now? Or if not, should we at least stop setting that flag in the `distsql_lookup_join` logic tests for the optimizer?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-:-LHE0ifRERBMtv6NjQf8:bvio5il)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
Thanks @solongordon, good points!

1. We are pushing the filters into the ON condition of the lookup join.. In other words, IndexFilterExpr can be merged into the OnCond, even for left joins. Let me know if you disagree.

2. We don't do the non-covering index case yet. Indeed it will be planned as a lookup join on top of a lookup join.

3. The difference with the flag is that the lookup joins get planned whenever possible; with the optimizer it only happens when the optimizer thinks it's cheaper. I think it's ok to keep the flag for a little while just in case. On the logic tests, thanks for pointing that out, I meant to remove the flag and go through the cases and add conditions as necessary to make the optimizer choose lookup joins but it slipped my mind.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-:-LHE5SWA6iFMd-2M7jAr:bleevjo)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Review by solongordon — APPROVED** [review]
Great, :lgtm: once the logic tests are revisited.

Just using `OnCond` sounds good to me. `IndexFilterExpr` is a bit more efficient because it allows filtering out lookup rows before they are joined to the input, but I think it's a modest enough difference that we shouldn't worry about it now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-:-LHE9bF40qKEvVaveSck:b1kxj4z)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale)

**Comment by RaduBerinde** [comment]
I went back and forth for a while trying to decide what to do about the `distsql_lookup_join` tests. I considered supporting the experimental "force lookup join" flag in the optimizer but it would be the first optimizer "knob" which we managed to avoid so far; I don't want to start this practice now, before we got a chance to decide on a general solution around query hints.

I decided to "fork" the tests; the old tests are still verifying the old planner and the experimental flag and they will go away at some point. The new `lookup_join` tests are cleaned up and modified versions which ensure that a lookup join is the cheapest plan. Note that these tests are not really distsql-centric anymore, though we still look at a few distributed plans in the execbuilder tests.

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 17 files at r2, 18 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-:-LHZb7zx7o6Vzfz45cuH:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 254 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-LHZ_sMaACxl-XnOzTRN:-LHZ_sMaACxl-XnOzTRO:b-lmux8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c655e0d708713095d12bf62803a2b507c9c9a3a4/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L254)):*
> ```
> 
> query T
> SELECT "URL" FROM [EXPLAIN (DISTSQL) SELECT * FROM authors INNER JOIN books ON books.edition = 1 WHERE books.title = authors.book]
> ```

Is this supposed to be a lookup join?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27409)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 254 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27409#-LHZ_sMaACxl-XnOzTRN:-LHZcwSy1TPeJOGKajf4:bicil50) ([raw file](https://github.com/cockroachdb/cockroach/blob/c655e0d708713095d12bf62803a2b507c9c9a3a4/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L254)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is this supposed to be a lookup join?
</blockquote></details>

Good catch, it was supposed to use `books2`, fixed.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27409)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale)

**Pull request merged**
