### PR TITLE
plpgsql: allow assigning to an element of a composite-typed variable

### LINKED ISSUE #132627: plpgsql: support assigning to an element of a composite-typed variable
In Postgres, it is possible to assign a value to a specific named element of a composite-typed variable. Here's an example:
```
postgres=# CREATE FUNCTION f(val xy) RETURNS xy AS $$
  BEGIN
    val.x := (val).x + 100;
    RETURN val;
  END
$$ LANGUAGE PLpgSQL;
CREATE FUNCTION
postgres=# SELECT f(ROW(1, 2));
    f
---------
 (101,2)
(1 row)
```
We should support this syntax. It's useful for triggers as well, for users that want to modify the row in a row-level BEFORE trigger like this:
```
CREATE FUNCTION f() RETURNS TRIGGER AS $$
  BEGIN
    NEW.x = 1000;
    RETURN NEW;
  END
$$ LANGUAGE PLpgSQL;

CREATE TRIGGER t BEFORE INSERT ON xy FOR EACH ROW EXECUTE FUNCTION f();
```

Jira issue: CRDB-43185

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql/parser: parse assign statements with indirection

This commit add support in the PL/pgSQL parser for an assignment
statement that assigns to an element of a variable, like `a.b := 5`.

Informs #132627

Release note: None

#### plpgsql: allow assigning to an element of a composite-typed variable

This patch adds support for assign statements that assign to an element of
a composite-typed variable, rather than just to the variable itself. Under
the hood, the other elements of the variable are copied into a new tuple
with the assigned value, and the result used to update the variable. This
is particularly useful for trigger functions, since users may want to update
rows in row-level BEFORE triggers like this example:
```
CREATE FUNCTION f() RETURNS TRIGGER AS $$
  BEGIN
    NEW.x = 100;
    RETURN NEW;
  END
$$ LANGUAGE PLpgSQL;

CREATE TRIGGER t BEFORE INSERT ON xy FOR EACH ROW EXECUTE FUNCTION f();
```
With this example, all inserts to table `xy` will now set `x` to 100.

Fixes #132627

Release note (sql change): It is now possible to assign to an element
of a composite typed varialbe in PL/pgSQL. For example, given a variable
`foo` with two integer elements `x` and `y`, the following assignment
statement is allowed: `foo.x := 100;`.

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Very nice!

> Reviewed 3 of 3 files at r1, 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132628#-:-O9Lh23L16iHQGR2oxpW:b-kerl87)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 788 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132628#-O9LV19mBwIhwJzGTCaW:-O9LV19mBwIhwJzGTCaX:brsojbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bca62a668ffe8b87981be4faa1f7342cf34f1bef/pkg/sql/plpgsql/parser/plpgsql.y#L788)):*
> ```Yacc
>     }
>   }
> | IDENT '.' IDENT assign_operator expr_until_semi ';'
> ```

Postgres supports nested composite types. Might be good to add a TODO that this will need to be an arbitrary-length list of identifiers, so that we remember to fix it for #91779.

**Review by mw5h — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132628#-:-O9LsTE1ALHsIfm6XfNU:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132628#-O9LrDDy25cK3hL2BgFb:-O9LrDDy25cK3hL2BgFc:bvqvmzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/992bdfe1a4d5b870d3c3ea996eebe9ab5be69566/pkg/sql/opt/optbuilder/plpgsql.go#L1151)):*
> ```Go
> 	colName := scopeColName(ident)
> 	var scalar opt.ScalarExpr
> 	if indirection != "" {
> ```

noIndirection?

**Review by DrewKimball — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132628#-:-O9MJe4G7H0M2xhIE7S5:bz5mair)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mw5h)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132628#-O9LrDDy25cK3hL2BgFb:-O9MJ0yq64zAyBGEPxJw:b-4pj5my) ([raw file](https://github.com/cockroachdb/cockroach/blob/992bdfe1a4d5b870d3c3ea996eebe9ab5be69566/pkg/sql/opt/optbuilder/plpgsql.go#L1151)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

noIndirection?
</blockquote></details>

Nice, done.
___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 788 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132628#-O9LV19mBwIhwJzGTCaW:-O9MIbax6uyD5dYkq75q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bca62a668ffe8b87981be4faa1f7342cf34f1bef/pkg/sql/plpgsql/parser/plpgsql.y#L788)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Postgres supports nested composite types. Might be good to add a TODO that this will need to be an arbitrary-length list of identifiers, so that we remember to fix it for #91779.
</blockquote></details>

Done.

**Pull request merged**
