### PR TITLE
kvserver: export secondary cache counter metrics

### LINKED ISSUE #110899: Export secondary cache metrics
Export metrics added at https://github.com/cockroachdb/pebble/pull/2760.

Jira issue: CRDB-31667

### PR DESCRIPTION
**Pull request by joshimhoff**
Fixes https://github.com/cockroachdb/cockroach/issues/110899.

**kvserver: export secondary cache counter metrics**

This commits exports counter metrics regarding the secondary cache added at https://github.com/cockroachdb/pebble/pull/2760. This commit doesn't export the histogram metrics added in that PR. While working on this one, I have realized a follow up PR is needed to export the bucketing scheme to CRDB.

Release note: None.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @joshimhoff)

___
*[`pkg/kv/kvserver/metrics.go` line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110818#-Nef1SdSBMNHg3tN52bS:-Nef1SdSBMNHg3tN52bT:b2uepf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39f2cd61dba5dea7b52372ad0529d843c82f03f/pkg/kv/kvserver/metrics.go#L772)):*
> ```Go
> 	}
> 	metaSecondaryCacheSize = metric.Metadata{
> 		Name:        "storage.shared-storage.cache.size",
> ```

Let's name these `storage.secondary-cache.*`.
___
*[`pkg/kv/kvserver/metrics.go` line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110818#-Nef1l-E3ErhqlHnM8Po:-Nef1l-E3ErhqlHnM8Pp:boi68ep) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39f2cd61dba5dea7b52372ad0529d843c82f03f/pkg/kv/kvserver/metrics.go#L773)):*
> ```Go
> 	metaSecondaryCacheSize = metric.Metadata{
> 		Name:        "storage.shared-storage.cache.size",
> 		Help:        "The number of sstable bytes stored in the cache",
> ```

"in the secondary cache" (same below)

**Review by joshimhoff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[`pkg/kv/kvserver/metrics.go` line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110818#-Nef1SdSBMNHg3tN52bS:-NehogRy7XIBeIPWBti-:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39f2cd61dba5dea7b52372ad0529d843c82f03f/pkg/kv/kvserver/metrics.go#L772)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Let's name these `storage.secondary-cache.*`.
</blockquote></details>

Done!
___
*[`pkg/kv/kvserver/metrics.go` line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110818#-Nef1l-E3ErhqlHnM8Po:-NehoizG6me6mnExWCli:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39f2cd61dba5dea7b52372ad0529d843c82f03f/pkg/kv/kvserver/metrics.go#L773)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

"in the secondary cache" (same below)
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110818#-:-Nei3BGi7jCiL_6i5nIz:b9benhj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by joshimhoff** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
bors r-

This needs `./dev gen docs`.

**Comment by nvanbenschoten** [comment]
bors r-

This is failing `CheckGeneratedCode/dev_generate`. You'll need to run `dev gen`.

```
------- Stderr: -------
On branch staging
Your branch is up to date with 'origin/staging'.
You are in a sparse checkout with 100% of tracked files present.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  modified:   docs/generated/metrics/metrics.html
no changes added to commit (use "git add" and/or "git commit -a")
diff --git a/docs/generated/metrics/metrics.html b/docs/generated/metrics/metrics.html
index 84e75fb6ca8..9ff027dc5f6 100644
--- a/docs/generated/metrics/metrics.html
+++ b/docs/generated/metrics/metrics.html
@@ -653,6 +653,16 @@
 <tr><td>STORAGE</td><td>storage.l6-level-size</td><td>Size of the SSTables in level 6</td><td>Bytes</td><td>GAUGE</td><td>BYTES</td><td>AVG</td><td>NONE</td></tr>
 <tr><td>STORAGE</td><td>storage.marked-for-compaction-files</td><td>Count of SSTables marked for compaction</td><td>SSTables</td><td>GAUGE</td><td>COUNT</td><td>AVG</td><td>NONE</td></tr>
 <tr><td>STORAGE</td><td>storage.queue.store-failures</td><td>Number of replicas which failed processing in replica queues due to retryable store errors</td><td>Replicas</td><td>COUNTER</td><td>COUNT</td><td>AVG</td><td>NON_NEGATIVE_DERIVATIVE</td></tr>
+<tr><td>STORAGE</td><td>storage.secondary-cache.count</td><td>The count of cache blocks in the secondary cache (not sstable blocks)</td><td>Cache items</td><td>GAUGE</td><td>COUNT</td><td>AVG</td><td>NONE</td></tr>
+<tr><td>STORAGE</td><td>storage.secondary-cache.evictions</td><td>The number of times a cache block was evicted from the secondary cache</td><td>Num evictions</td><td>GAUGE</td><td>COUNT</td><td>AVG</td><td>NONE</td></tr>
+<tr><td>STORAGE</td><td>storage.secondary-cache.reads-full-hit</td><td>The number of reads where all data returned was read from the secondary cache</td><td>Num reads</td><td>GAUGE</td><td>COUNT</td><td>AVG</td><td>NONE</td></tr>
```

**Comment by joshimhoff** [comment]
Thanks! Apologies.

**Pull request merged**
