### PR TITLE
opt: normalize CollateExpr Locale

### LINKED ISSUE #65343: opt: optimizer should use index on virtual COLLATED columns
In the example below, the optimizer should realize that the secondary index can be used to satisfy the query:

```
demo@127.0.0.1:26257/defaultdb> SHOW CREATE TABLE t;
  table_name |                       create_statement
-------------+----------------------------------------------------------------
  t          | CREATE TABLE public.t (
             |     s STRING NULL,
             |     c STRING COLLATE en_US NULL AS (s COLLATE en_US) VIRTUAL,
             |     rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
             |     CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
             |     INDEX t_c_idx (c ASC),
             |     FAMILY "primary" (s, rowid)
             | )
(1 row)

Time: 7ms total (execution 7ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> EXPLAIN SELECT * FROM t WHERE s COLLATE "en_US" = 'foo' COLLATE "en_US";
                         info
-------------------------------------------------------
  distribution: full
  vectorized: true

  • render
  │
  └── • filter
      │ filter: s COLLATE en_US = 'foo' COLLATE en_US
      │
      └── • scan
            missing stats
            table: t@primary
            spans: FULL SCAN
(12 rows)
```

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: format CollateExpr.Locale in opt trees

Formatted opt trees now include the `Locale` field of `CollateExpr`s.
Previously, the `Locale` was never shown.

Release note: None

#### opt: normalize CollateExpr Locale

This commit normalizes the `Locale` string of a `CollateExpr` when the
expression is built in optbuilder. Normalization of this string ensures
that collated string expressions with different but equivalent locales
are considered equal. For example, the expressions `s COLLATE "en_us"`
and `s COLLATE "en-US"` are equivalent, but prior to this commit they
would be considered non-equivalent.

This change allows crucial optimizer rules to apply in more cases, like
`GenerateConstrainedScans`.

Consider the table:

    CREATE TABLE t (
      s STRING,
      c STRING COLLATE en_US AS (s COLLATE en_US) VIRTUAL,
      INDEX (c)
    )

None of the following queries would perform a constrained scan on the
secondary index because the collated expressions on the left side of the
`=` were not considered equal to the virtual column expression.

    SELECT * FROM t WHERE s COLLATED "en_US" = 'foo' COLLATE en_US
    SELECT * FROM t WHERE s COLLATED "en-US" = 'foo' COLLATE en_US
    SELECT * FROM t WHERE s COLLATED "en-us" = 'foo' COLLATE en_US

The locale is normalized in optbuild rather than in a normalization rule
for the sake of efficiency. A normalization rule would have to check
that a locale is not already normalized to prevent an infinite
normalization loop. This would require normalizing the locale multiple
times: at least once to normalize and at least once more in the
recursive call to `ConstructCollate` to detect if the locale was already
normalized. Normalizing the locale in optbuilder requires only
normalizing the locale once.

Fixes #65343

Release note (performance improvement): The optimizer now generates
query plans that scan indexes on virtual collated string columns,
regardless of the casing or formatting of the collated locale in the
query.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65437#-:-Ma0sCKJBnaC2D5ew0qO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/testdata/scalar, line 1194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65437#-Ma0s6i0ChwcqZsYNX7z:-Ma0s6i0ChwcqZsYNX8-:b-65mjpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e88b4d524930347c27beebc54ccd33b50dd1d3/pkg/sql/opt/optbuilder/testdata/scalar#L1194)):*
> ```
> collate locale='en_US' [type=collatedstring{en_US}]
>  └── variable: a:1 [type=string]
> ```

Can you add a test with an invalid locale?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65437)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/optbuilder/testdata/scalar, line 1194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65437#-Ma0s6i0ChwcqZsYNX7z:-Ma0z3Dd5jEJXdyczjR0:bv6z8wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e88b4d524930347c27beebc54ccd33b50dd1d3/pkg/sql/opt/optbuilder/testdata/scalar#L1194)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you add a test with an invalid locale?
</blockquote></details>

Done. Unfortunately it doesn't exercise the new code path - type checking returns an error before `buildScalar` is called.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65437#-:-Ma5HR8VCiAq8mHg9UpL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
