### PR TITLE
ui next: UIData reducer.

### PR DESCRIPTION
**Pull request by mrtracy**
Create reducer for storing persisted UIData to the server. The reducer is very
simple, but includes the important `saveUIData` and `loadUIData` asynchronous
action creators. These action creates are responsible for properly encoding and
decoding UIData for storage on the server.

Commit also adds admin server protos into the compiled javascript protobuf set.
Due to an unexpected syntax incompatibility with typescript, one field in the
protobuf definition had to be renamed from `default` to `default_value`
("default" being a reserved word in typescript).

Commit also has a locally updated typings definition for ByteBuffer.js, which is
exactly the same change previously made to Long.js. These changes will
eventually be pushed back to DefinitelyTyped, but are locally referenced to
avoid being blocked.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6744)

### CODE REVIEW

**Comment by mrtracy** [comment]
@maxlang This commit includes the same (default -> default_value) change as your outstanding PR.  If you merge your commit first, i'll just revert the changes in this PR and rebase onto yours.

**Comment by maxlang** [comment]
I'm concerned `ByteBuffer` won't work correctly vs `atob` and `btoa`. That said, I don't understand all of the magic that the proto builders are performing.

If you could double check these values show up correctly in the sql client I'd appreciate it.

```
root@:26257> SELECT * FROM SYSTEM.UI;
+---------------------------+-------+----------------------------------------+
|            key            | value |              lastUpdated               |
+---------------------------+-------+----------------------------------------+
| registration_synchronized | true  | 2016-05-10 18:43:21.962099 +0000 +0000 |
+---------------------------+-------+----------------------------------------+
```

Otherwise :lgtm: 

<details><summary><i>Previously, mrtracy wrote…</i></summary>
> @maxlang This commit includes the same (default -> default_value) change as your outstanding PR.  If you merge your commit first, i'll just revert the changes in this PR and rebase onto yours.</details>


---

Reviewed 12 of 12 files at r1.
Review status: 12 of 13 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[server/admin_test.go, line 387 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwnrG0K_C61aqxgJL4:-KHwnrG0K_C61aqxgJL5:878384784) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/server/admin_test.go#L387)):*
> ```Go
> 		{Name: "default2", Type: "INT", Nullable: true, DefaultValue: "2"},
> 		{Name: "string_default", Type: "STRING", Nullable: true, DefaultValue: "'default_string'"},
> 		{Name: "rowid", Type: "INT", Nullable: false, DefaultValue: "unique_rowid()"},
> ```

Forgot to add this to my change - just rerunning the tests now.

---

*[ui/next/app/redux/uiData.spec.ts, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwpI6MuEE9Eu1BRTnp:-KHwpI6MuEE9Eu1BRTnq:1525537319) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.spec.ts#L26)):*
> ```XML
>     it("fetchCompleteUIData() creates the correct action type.", function() {
>       assert.equal(uidata.fetchCompleteUIData().type, uidata.FETCH_COMPLETE);
>     });
> ```

Random thought - I wonder how we could automatically ensure every action creator was tested.

Also, we should track coverage (once this is all done.)

---

*[ui/next/app/redux/uiData.spec.ts, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwxXy4rPg9JtWy1pX9:-KHwxXy5vGfBquagrFnq:883342495) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.spec.ts#L80)):*
> ```XML
> 
>       dispatch(uidata.setUIData("num", 4));
>       assert.isNull(state.error);
> ```

This brings up a good point - we might eventually want to track per value errors. In this example, if I try to save my registration data and there's an error, but then I dismiss the "update to the latest version" banner, that error message would be overwritten.

---

*[ui/next/app/redux/uiData.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwptsr-2K9x9mrxcD5:-KHwptsr-2K9x9mrxcD6:-1540364963) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.ts#L21)):*
> ```XML
>   inFlight = 0;
>   error: Error;
>   data: {[key: string]: any} = {};
> ```

Fine for now, but we probably could make certain definitive statements about the shape of this object going forward. At some point we can tackle what that would mean for `SET`. Honestly we only have maybe 10 values we use right now, so ultimately we could just be explicit (ie `SET_USERNAME` or `SET_BANNER_DISMISSED`) though that might not scale well.fr

---

*[ui/next/app/redux/uiData.ts, line 114 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwsYc85dm8RChOS8II:-KHwsYc85dm8RChOS8IJ:-1677558468) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.ts#L114)):*
> ```XML
>     _.each(values, (kv) => {
>       let stringifiedValue = JSON.stringify(kv.value);
>       request.key_values.set(kv.key, ByteBuffer.fromUTF8(stringifiedValue));
> ```

Is this equivalent to `btoa` when combined with `encodeJSON`?

---

*[ui/next/app/redux/uiData.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwt9cKiudMQJ7HDs4f:-KHwt9cKiudMQJ7HDs4g:2090409244) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.ts#L130)):*
> ```XML
>     }).then(() => {
>       // SetUIDataResponse is empty. A positive return indicates success.
>       _.each(values, (kv) => dispatch(setUIData(kv.key, kv.value)));
> ```

I'm wondering if we'll need to store a local version for some things. For example, would form data populated from the state get reset to the old values when there's an error?

We can address this as necessary.

---

*[ui/next/app/redux/uiData.ts, line 152 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwu1oDG8xYpm1XUCPP:-KHwu1oDG8xYpm1XUCPQ:2054804296) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.ts#L152)):*
> ```XML
>     return fetch("/_admin/v1/uidata?" + queryStr)
>     .then((response) => {
>       return response.json() as Promise<cockroach.server.GetUIDataResponse>;
> ```

Why is `response.json()` a `Promise`?

---

*[ui/next/app/redux/uiData.ts, line 160 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwvfju15zgKT-CYKfv:-KHwvfjv_C_144h7d2cV:360060060) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.ts#L160)):*
> ```XML
>         let decoded: any = null;
>         let bb = val.getValue();
>         let str = bb.readString(bb.limit);
> ```

Any reason you chose using `ByteBuffer` over `atob` and `btoa`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-:-KHwwLokpAlHb4E5_S4a:2029138738)*

**Comment by maxlang** [comment]
Review status: 12 of 13 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[ui/next/app/redux/uiData.ts, line 152 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwu1oDG8xYpm1XUCPP:-KHxLHrhoiUADzWAH3e7:55296286) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.ts#L152)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Why is `response.json()` a `Promise`?</details>
Nevermind, I see it's part of the spec

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744)*

**Comment by mrtracy** [comment]
The generated protocol buffer classes use ByteBuffer for byte fields.  I am *relatively* certain that the end result is the same; if it turns out to be different, we'll work around it then.

<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I'm concerned `ByteBuffer` won't work correctly vs `atob` and `btoa`. That said, I don't understand all of the magic that the proto builders are performing.
> 
> If you could double check these values show up correctly in the sql client I'd appreciate it.
> 
> ```
> root@:26257> SELECT * FROM SYSTEM.UI;
> +---------------------------+-------+----------------------------------------+
> |            key            | value |              lastUpdated               |
> +---------------------------+-------+----------------------------------------+
> | registration_synchronized | true  | 2016-05-10 18:43:21.962099 +0000 +0000 |
> +---------------------------+-------+----------------------------------------+
> ```
> 
> Otherwise :lgtm: 
> </details>


---

Review status: 4 of 6 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[ui/next/app/redux/uiData.spec.ts, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwxXy4rPg9JtWy1pX9:-KI-5dzAgh6t1rjoRcAi:610536025) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.spec.ts#L80)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> This brings up a good point - we might eventually want to track per value errors. In this example, if I try to save my registration data and there's an error, but then I dismiss the "update to the latest version" banner, that error message would be overwritten.</details>
I'm not sure what the best granularity is for handling errors is yet, i'm sort of putting that off for later.  Right now, I basically want enough granularity to display the "Error connecting to server" banner.

---

*[ui/next/app/redux/uiData.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwptsr-2K9x9mrxcD5:-KI-6OgVIPXxe8GRhQAq:1377947813) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.ts#L21)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Fine for now, but we probably could make certain definitive statements about the shape of this object going forward. At some point we can tackle what that would mean for `SET`. Honestly we only have maybe 10 values we use right now, so ultimately we could just be explicit (ie `SET_USERNAME` or `SET_BANNER_DISMISSED`) though that might not scale well.fr</details>
This was my initial design, and I really hated it.  It was very hard to read, and I don't think it bought us anything - the objects are untyped on the server, and if we need types on the client side, we can access them via Selectors instead of accessing state directly.  We can also add action creator functions (i.e. `saveBannerDismissed`) without adding additional action types; `saveBannerDismissed` could just call `saveUIData`.

---

*[ui/next/app/redux/uiData.ts, line 114 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwsYc85dm8RChOS8II:-KI-88LADOExEsDRM6AW:-249247826) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.ts#L114)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Is this equivalent to `btoa` when combined with `encodeJSON`?</details>
I think so.  We will find out soon enough.

---

*[ui/next/app/redux/uiData.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwt9cKiudMQJ7HDs4f:-KI-8DgJIoMQzeSSlokH:1902464676) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.ts#L130)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I'm wondering if we'll need to store a local version for some things. For example, would form data populated from the state get reset to the old values when there's an error?
> 
> We can address this as necessary.</details>
We can store temporary unsaved values in a separate reducer, or probably just in react component state.

---

*[ui/next/app/redux/uiData.ts, line 160 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-KHwvfju15zgKT-CYKfv:-KI-8Pxz55VUwFtBosUo:-890435363) ([raw file](https://github.com/cockroachdb/cockroach/blob/c39c659f29dc6090476f912689b7b8655eedff69/ui/next/app/redux/uiData.ts#L160)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Any reason you chose using `ByteBuffer` over `atob` and `btoa`?</details>
Because the generated protobuffer field is already a ByteBuffer - there is no choice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6744#-:-KI-8sd03pvmN2-zTcgf:711026314)*

**Pull request merged**
