### PR TITLE
[WIP] roachtest/workload: Queue-like workload

### PR DESCRIPTION
**Pull request by mrtracy**
Initial creation of a "queue-like" workload and a simple roachtest which
utilizes the new workload.

Release note: None

### CODE REVIEW

**Comment by mrtracy** [comment]
Very simple to start with, would just like some confirmation that this workload is correct in its basic form.

**Review by petermattis — CHANGES_REQUESTED** [review]
The basic form looks good. I've got a question about the workload itself. I think the pattern we tend to see from users is N writers and 1 deleter. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-:-LHOtRep8fS_r25TV6Hv:b-hpxcqd)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/queue.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOrXHo0ijpn5roa-nN:-LHOrXHo0ijpn5roa-nO:b-qw1wy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/queue.go#L28)):*
> ```Go
> 
> 	r.Add(testSpec{
> 		Name:    fmt.Sprintf("queueWorkload/nodes=%d", numNodes),
> ```

`s/Workload//g` (none of the other roachtests specify `Workload` in their name).
___
*[pkg/cmd/roachtest/queue.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOri6o0ln54-UEQTTP:-LHOri6o0ln54-UEQTTQ:b-iskj1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/queue.go#L29)):*
> ```Go
> 	r.Add(testSpec{
> 		Name:    fmt.Sprintf("queueWorkload/nodes=%d", numNodes),
> 		Nodes:   nodes(numNodes),
> ```

You've cargo-culted this, but not followed the recipe precisely. The `kv` roachtests create 4-node clusters where 3-nodes are used for cockroach and the 4th node is used to run `workload`. 
___
*[pkg/cmd/roachtest/queue.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOrQi9-NM-uRaOdzRP:-LHOrQi9-NM-uRaOdzRQ:b-97yujz) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/queue.go#L30)):*
> ```Go
> 		Name:    fmt.Sprintf("queueWorkload/nodes=%d", numNodes),
> 		Nodes:   nodes(numNodes),
> 		Timeout: 5 * time.Hour,
> ```

There is no need to specify a `Timeout` as the default one (derived from the cluster expiration) suffices for most purposes.
___
*[pkg/cmd/roachtest/registry.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOryNu-zUxzVYaBsGV:-LHOryNu-zUxzVYaBsGW:b68h7gd) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/registry.go#L52)):*
> ```Go
> 	registerVersion(r)
> 	registerEncryption(r)
> 	registerQueueWorkload(r)
> ```

My eyes cannot believe the disorder of these last 2 `register*()` calls!
___
*[pkg/workload/queue/queue.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOsBPcDZoTF1omWp1i:-LHOsBPcDZoTF1omWp1j:b67g1yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L1)):*
> ```Go
> // Copyright 2017 The Cockroach Authors.
> ```

`s/2017/2018/g`
___
*[pkg/workload/queue/queue.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOsXwqDjWd3__xWLPI:-LHOsXwqDjWd3__xWLPJ:b-tebrxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L104)):*
> ```Go
> 
> 	// Generate queue deletion statement.
> 	deleteStmt, err := db.Prepare(`DELETE FROM queue WHERE ts >= $1 AND ts < $2`)
> ```

My understanding is that this will perform better than the simpler `WHERE ts < $2` because it doesn't have to scan over the empty ranges or all of the tombstones for the earliest non-empty range. 
___
*[pkg/workload/queue/queue.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOt4zp29UIRyOU9TSy:-LHOt4zp29UIRyOU9TSz:bjj7ick) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L156)):*
> ```Go
> 	o.hists.Get("write").Record(timeutil.Since(startTime))
> 
> 	// Delete batch which was just written.
> ```

This feels a bit strange to me. I'd rather see something that always inserts at the end and then periodically deletes everything older than some timestamp. The older than timestamp would keep ratcheting up (i.e. it would be a value shared by all of the workers).

**Review by bdarnell — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27506)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/queue/queue.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOsXwqDjWd3__xWLPI:-LHUOwGg4Gtcq-curz31:b-w1iq34) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L104)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

My understanding is that this will perform better than the simpler `WHERE ts < $2` because it doesn't have to scan over the empty ranges or all of the tombstones for the earliest non-empty range. 
</blockquote></details>

I think for the purposes of this test we want the version without a lower bound. We want this test to exhibit the performance degradation of this query over time so we have a target to fix. 
___
*[pkg/workload/queue/queue.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOt4zp29UIRyOU9TSy:-LHUOUvKBYaFNg86c9IE:brv6x14) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L156)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This feels a bit strange to me. I'd rather see something that always inserts at the end and then periodically deletes everything older than some timestamp. The older than timestamp would keep ratcheting up (i.e. it would be a value shared by all of the workers).
</blockquote></details>

There are two major variants of the queue-like workload:
- Work queue with many inserters and many workers/deleters. Deleting the batch that was just inserted is a decent approximation of this workload, but instead of a ranged delete it should be a select by timestamp range and then a delete by id.
- Expiration with many inserters and one (ranged) deleter.

For now, I don't think we need two versions of this test because they share the major issue of accumulating tombstones. Once we've taken care of that we can consider whether we want to test the two cases separately.

**Review by tbg — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27506)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/queue.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHXmCsd3etCjxECq10O:-LHXmCsd3etCjxECq10P:bhlem17) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/queue.go#L27)):*
> ```Go
> 	const numNodes = 3
> 
> 	r.Add(testSpec{
> ```

Since we're after storage-level tombstones here which doesn't have much to do with distributed systems, I think we could even start with a single node version of this test. I'd be interested in seeing the performance degradation here (the concurrency should be set so that the cluster is initially not overwhelmed). You're going to need to add some failure condition. Perhaps query the node statement statistics and make sure the average latency of the query remains below some cutoff. (This will depend on the size of the cluster and, unfortunately, on hardware to some extent, but the degradation can hopefully become pretty bad within a reasonable amount of time).
___
*[pkg/workload/queue/queue.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOsXwqDjWd3__xWLPI:-LHXlCooEQFYOjxUmoBL:bfn8q84) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L104)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think for the purposes of this test we want the version without a lower bound. We want this test to exhibit the performance degradation of this query over time so we have a target to fix. 
</blockquote></details>

Yes, I was also thinking that this would be intentionally doing the naive thing (with a comment).
___
*[pkg/workload/queue/queue.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOt4zp29UIRyOU9TSy:-LHXlMFl1FsaMgTaYQOU:b-i76l9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L156)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

There are two major variants of the queue-like workload:
- Work queue with many inserters and many workers/deleters. Deleting the batch that was just inserted is a decent approximation of this workload, but instead of a ranged delete it should be a select by timestamp range and then a delete by id.
- Expiration with many inserters and one (ranged) deleter.

For now, I don't think we need two versions of this test because they share the major issue of accumulating tombstones. Once we've taken care of that we can consider whether we want to test the two cases separately. 
</blockquote></details>

What Ben said. When I suggested this form, I just wanted the one that was simplest to scale. We need to generate a lot of tombstones quickly, and having the same mix of insertions vs deletions seemed like a good way to (plus easy to build) get that while also being close enough to a real workload.

**Review by mrtracy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27506)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/queue.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHXmCsd3etCjxECq10O:-LHZxLk_38ypfhE1037H:b886pl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/queue.go#L27)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Since we're after storage-level tombstones here which doesn't have much to do with distributed systems, I think we could even start with a single node version of this test. I'd be interested in seeing the performance degradation here (the concurrency should be set so that the cluster is initially not overwhelmed). You're going to need to add some failure condition. Perhaps query the node statement statistics and make sure the average latency of the query remains below some cutoff. (This will depend on the size of the cluster and, unfortunately, on hardware to some extent, but the degradation can hopefully become pretty bad within a reasonable amount of time).
</blockquote></details>

So should this test be failing initially on commit?  Now that I've made the adjustments, the delete time rises continuously as expected as the process continues to run.
___
*[pkg/cmd/roachtest/queue.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOrXHo0ijpn5roa-nN:-LHZwkaP6fNzqbb4tEwT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/queue.go#L28)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/Workload//g` (none of the other roachtests specify `Workload` in their name).
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/queue.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOri6o0ln54-UEQTTP:-LHZwi53BvjlHe4o95zF:b-78x6qe) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/queue.go#L29)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You've cargo-culted this, but not followed the recipe precisely. The `kv` roachtests create 4-node clusters where 3-nodes are used for cockroach and the 4th node is used to run `workload`. 
</blockquote></details>

Done, made this a little clearer what's going on with comments.
___
*[pkg/cmd/roachtest/queue.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOrQi9-NM-uRaOdzRP:-LHZxTbU2kLoMogKhZcq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/queue.go#L30)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

There is no need to specify a `Timeout` as the default one (derived from the cluster expiration) suffices for most purposes.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/registry.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOryNu-zUxzVYaBsGV:-LHZwu9X7guZ14_Paifa:bf5et4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/registry.go#L52)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

My eyes cannot believe the disorder of these last 2 `register*()` calls!
</blockquote></details>

Looked at the last entry and assumed they were in creation order rather than alphabetical. I'm innocent!

Fixed.
___
*[pkg/workload/queue/queue.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOsBPcDZoTF1omWp1i:-LHZxT8-3T4YkiThV5Zk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L1)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/2017/2018/g`
</blockquote></details>

Done.
___
*[pkg/workload/queue/queue.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOsXwqDjWd3__xWLPI:-LHZxUMn3JgQ0ZlAK-S2:b-n3bx31) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L104)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Yes, I was also thinking that this would be intentionally doing the naive thing (with a comment).
</blockquote></details>

I've removed the lower bound, but i've addressed the issue of multiple/single consumers in the comment chain below.
___
*[pkg/workload/queue/queue.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOt4zp29UIRyOU9TSy:-LHZxBE3EnwMp24_amxi:b1ufcne) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L156)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

What Ben said. When I suggested this form, I just wanted the one that was simplest to scale. We need to generate a lot of tombstones quickly, and having the same mix of insertions vs deletions seemed like a good way to (plus easy to build) get that while also being close enough to a real workload.
</blockquote></details>

For this initial commit, would an acceptable compromise be to remove the lower bound on the DELETE but keep it so that every concurrent op is both a producer and a consumer?

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27506)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/registry.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOryNu-zUxzVYaBsGV:-LHcsXVf5gSJYPfz_wPa:b-ucfkn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/registry.go#L52)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Looked at the last entry and assumed they were in creation order rather than alphabetical. I'm innocent!

Fixed.
</blockquote></details>

Thanks.
___
*[pkg/workload/queue/queue.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOt4zp29UIRyOU9TSy:-LHcsa5vB592h0su_INu:b-g26xmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L156)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

For this initial commit, would an acceptable compromise be to remove the lower bound on the DELETE but keep it so that every concurrent op is both a producer and a consumer?
</blockquote></details>

As long as this load reproduces the problem then I'm fine with it for now.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-:-LHnJSgp06-glrjZTgZC:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/queue.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHXmCsd3etCjxECq10O:-LHnI6lK9r3y8SlC6TiT:b-aovo1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/cmd/roachtest/queue.go#L27)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

So should this test be failing initially on commit?  Now that I've made the adjustments, the delete time rises continuously as expected as the process continues to run.
</blockquote></details>

Yeah, I think we should merge this as unstable and in a version that fails (this is what I did with the drop and quiesce roachtests, both of which pass now). The hope is that we have enough momentum to actually make fixes soon enough.
___
*[pkg/cmd/roachtest/queue.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHnIlTo1A0uwc8j8IPl:-LHnIlTo1A0uwc8j8IPm:btwychy) ([raw file](https://github.com/cockroachdb/cockroach/blob/99a358edd00e28fcaaee47f5f932a27dc55078ba/pkg/cmd/roachtest/queue.go#L48)):*
> ```Go
> 	m.Go(func(ctx context.Context) error {
> 		concurrency := ifLocal("", " --concurrency="+fmt.Sprint(dbNodeCount*64))
> 		duration := " --duration=10m"
> ```

10 minutes seems too short. Does it really get that bad in that timeframe already?
___
*[pkg/workload/queue/queue.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOt4zp29UIRyOU9TSy:-LHnIXJS58J3lFi5-Zhu:b-4pgwts) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L156)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

As long as this load reproduces the problem then I'm fine with it for now. 
</blockquote></details>

:thumbsup: A comment here to justify this choice would be good because it does look a little weird to the uninitiated eye.
___
*[pkg/workload/queue/queue.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHnIz8h9rJa3z9V5C10:-LHnIz8h9rJa3z9V5C11:bh2f71q) ([raw file](https://github.com/cockroachdb/cockroach/blob/99a358edd00e28fcaaee47f5f932a27dc55078ba/pkg/workload/queue/queue.go#L49)):*
> ```Go
> 	Name: `queue`,
> 	Description: `Batched writes and deletes from a queue-like table.` +
> 		`sequence, deletions from beginning of sequence.`,
> ```

I don't understand this line.
___
*[pkg/workload/queue/queue.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHnISVl4LG7lqvYOyA8:-LHnISVl4LG7lqvYOyA9:b-qnn0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/99a358edd00e28fcaaee47f5f932a27dc55078ba/pkg/workload/queue/queue.go#L104)):*
> ```Go
> 
> 	// Generate queue deletion statement.
> 	deleteStmt, err := db.Prepare(`DELETE FROM queue WHERE ts < $1`)
> ```

Add a comment that this is intentionally the naive form.

**Review by mrtracy — COMMENTED** [review]
PTAL, I've added pass criteria for this - the test runs the queue workload for a short period and then samples the baseline time to scan the queue table. It then runs the workload for a much longer period and computes the scan time again - if the scan time after is more than 30x the original scan time (an arbitrary threshold), the test fails.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-:-LHoxXJc2XZF3YMOR5tm:btjd0gu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/queue.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHnIlTo1A0uwc8j8IPl:-LHn_bZq6W1r2j-acmXP:blucymm) ([raw file](https://github.com/cockroachdb/cockroach/blob/99a358edd00e28fcaaee47f5f932a27dc55078ba/pkg/cmd/roachtest/queue.go#L48)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

10 minutes seems too short. Does it really get that bad in that timeframe already?
</blockquote></details>

It appears to get bad in linear fashion.  I've extended the time to 30m, but I think 10m suffices for now.
___
*[pkg/workload/queue/queue.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHOt4zp29UIRyOU9TSy:-LHoX8md0WATnxU62K-Z:b41fkcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b88a7d340eaa7c11b34c00ecaf6f003d78da8f/pkg/workload/queue/queue.go#L156)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

:thumbsup: A comment here to justify this choice would be good because it does look a little weird to the uninitiated eye.
</blockquote></details>

Added a comment to queueOp.
___
*[pkg/workload/queue/queue.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHnIz8h9rJa3z9V5C10:-LHoWcogBhYp7FoYWkR1:b1jx1gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/99a358edd00e28fcaaee47f5f932a27dc55078ba/pkg/workload/queue/queue.go#L49)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I don't understand this line.
</blockquote></details>

Ah, looks like I messed it up. Fixed.
___
*[pkg/workload/queue/queue.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LHnISVl4LG7lqvYOyA8:-LHoWpbX7163yLcND5rx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99a358edd00e28fcaaee47f5f932a27dc55078ba/pkg/workload/queue/queue.go#L104)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Add a comment that this is intentionally the naive form.
</blockquote></details>

Done.

**Review by tbg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27506)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/queue.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LIBZN4X7tL4SHIk8i-T:-LIBZN4X7tL4SHIk8i-U:b7m1dpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2e236120aa4705eba16c3981bb46bb82008c567/pkg/cmd/roachtest/queue.go#L80)):*
> ```Go
> 		for i := 0; i < sampleCount; i++ {
> 			startTime := timeutil.Now()
> 			_, err := db.Exec("DELETE FROM queue.queue WHERE ts < 1000")
> ```

Why isn't this an actual scan?

**Review by mrtracy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27506)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/queue.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-LIBZN4X7tL4SHIk8i-T:-LIHs1iB8UizgfhPrZHW:bru1xdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2e236120aa4705eba16c3981bb46bb82008c567/pkg/cmd/roachtest/queue.go#L80)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Why isn't this an actual scan?
</blockquote></details>

No reason, it's just what I was already using. I've changed it to a `SELECT count(*)` instead, which still seems to easily reproduce the behavior (after 10 minutes, speed has slowed down by a factor of about 100).

**Comment by mrtracy** [comment]
I think this is adequate for a first draft, there are options we can add in later (specifically, TTL deletions and different scan operations).

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27506#-:-LIKUPle7zP7lZRFykwM:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by tbg — APPROVED** [review]
Actually the one thing I would add is a gc TTL for that table's zone of 1 minute. Otherwise, we really don't expect it to ever be able to do much better than now (unless we go all-out on generational storage, but that will be a lot more work than will be happening soon).

**Pull request merged**
