### PR TITLE
opt: create inverted index constraint iterator

### PR DESCRIPTION
**Pull request by mgartner**
The current implementation of inverted index constraints generation
relies heavily on the logic that builds standard index constraints. It
shares many of the same functions and data structures. However, the
inherent differences between inverted and standard indexes make this
implementation unnecessarily complex and inefficient.

This commit adds InvertedIndexConstraintIterator to the idxconstraint
package. The goals of this iterator are to provide:

  1. A cleaner interface for generating inverted index constraints.
  2. A more productive environment for improving support for inverted
     indexes that is not closely coupled with standard indexes.
  3. A more efficient method of generating inverted index constraints.
  4. Simplification of the code that generates standard index
     constraints.
  5. The ability to full test all constraints that can be generated for
     a FiltersExpr and an inverted index.

The GenerateInvertedIndexScans and GenerateInvertedZigZagIndexJoins are
the only two exploration rules that require inverted index constraints.
GenerateInvertedIndexScans currently uses only the first constraint
found. GenerateInvertedIndexZigZagIndexJoins enumerates all possible
constraints, but only uses the first two.

With an iterator-style implementation, the consumer of the iterator is
free to enumerate exactly the number of constraints required for each
use case.

The tests from the current implementation have been copied to the new
test suite, with a few additional tests added for '[]', '{}', and
disjunctions (not yet supported by either implementation).

Note that this new construct is not yet utilized for generating inverted
index scans. It does not interact with the rest of the code base as of
this commit. There are a number of follow-up tasks including:

  1. Add support for inverted indexes on arrays.
  2. Add test support to validate all constraints generated.
  3. Benchmark the new iterator vs. the previous implementation.
  4. Integrate with xform/custom_functions.go.
  5. Remove the old implementation from
     idxconstraint/index_constraints.go.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
Oops. There’s some more motivations for this I want to add to the commit
message and include an explanation of current usage of inverted index
constraints.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47734)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5TR-WmBev1dlb9Q2lx:-M5TR-WmBev1dlb9Q2ly:blfp0bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L39)):*
> ```Go
> //     tight := iter.IsTight()
> //     remainingFilter := iter.RemainingFilters()
> //   }
> ```

This description should explain what these constraints are in relationship with one another. I assume that a row must satisfy all constraints for it to satisfy the filter?

What do tightness and remaining filters mean here exactly? Any single constraint can't be tight unless it's the only one, right? Shouldn't there be only one tightness and remaining filter rather than one per constraint? 
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5TSTQYB5AYpj2svfQb:-M5TSTQYB5AYpj2svfQc:b6lt08s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L49)):*
> ```Go
> //   a @> '{"a": 1}' AND a @> '{"b": 2}'
> //
> // This expression cannot generate a constraint over an inverted index with
> ```

I would remove this paragraph (we wouldn't have multiple spans for a regular index in this case either, AND intersects the spans of each conjunct).

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47734)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5TR-WmBev1dlb9Q2lx:-M5TvNOmDwkZ8OY8Bu44:b-q3drt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L39)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This description should explain what these constraints are in relationship with one another. I assume that a row must satisfy all constraints for it to satisfy the filter?

What do tightness and remaining filters mean here exactly? Any single constraint can't be tight unless it's the only one, right? Shouldn't there be only one tightness and remaining filter rather than one per constraint? 
</blockquote></details>

Agreed. Tightness isn't really relevant in the context of inverted indexes, and looking more at the current implementation, it's not actually needed to generate index scans. This is a relic from the current implementation that I should be able to remove.

In an ideal world, where all possible constraints are enumerated, the RemainingFilters returns a FiltersExpr for each constraint enumerated, that must be applied as a filter after an index scan to ensure correct results are emitted.

However, I think it may become complicated to generate all possible constraints over an index with arbitrary expressions trees, handling both conjunctions and disjunctions. 

As I'm thinking more about how to deal with disjunctions and inverted index constraints, I'm thinking this implementation is a bit flawed. I'm going to mull it over a bit more, but I'm not sure if it makes sense to enumerate all possible constraints. Maybe there's a better representation of multiple constraints that encapsulates the special cases for inverted indexes better.

My thinking was that it might be necessary to do so in order to find the optimal constraints to constrain a scan once inverted index statistics are added. For example, with the expression `j @> '{"a": 1}' AND j @> '{"b": 2}'`, you'd want to produce two separate plans, one that scans the index for `'{"a": 1}'` and filters by `'{"b": 2}'`, and another that scans the index for `'{"b": 2}'` and filters by `'{"a": 1}'`.

**Comment by RaduBerinde** [comment]
Take a look at the rule that generates zig zag joins for inverted indexes - any new API should take that usecase into consideration. That is the only way I can think of where we can use multiple constraints at the same time.

**Comment by mgartner** [comment]
Ya that's the rule that also helped inspire the iterator. But I think this iterator overcomplicates things, and I'm going to rework this whole PR to avoid going down a rabbit hole.

Constraints for inverted index scans get particularly tricky when dealing with multiple conjunctions and disjunctions. Here are some examples (assume `A`, `B`, and `C` are JSON contains statements with different constants over the same column like `j @> '{"a": 1}'`.

`A and (B or C)` — This expression could produce a constraint with a span for `A` with `B or C` as the remaining filter, or a constraint with a spans for `B` and `C`, with `A` as the remaining filter and a distinct operator added to eliminate potential duplicates.

`A or (B and C)` — As far as I can tell, no constrained scan is possible in this case.

`A or (B or C)` — Ideally this produces a constraint with spans for `A`, `B`, and `C` with a distinct operator added and no remaining filters.

`A and (B and C)` — There's lots of different possibilities here, especially when you consider the possibility of using a ZigZag join.

Now assume that `A'`, `B'`, and `C'` have multiple paths, e.g. `j @> '{"a": 1, "b": 2}'`.

`A' or B'` — To perform a constrained scan with such a filter would contain spans for the first path in `A'` and `B'`, and a remaining filter that looks like `otherPaths(A') OR otherPaths(B')` where `otherPaths` are the paths not in the spans. There could also be duplicate rows retrieved the by two spans, so a distinct operator would also be necessary.

I think this rabbit hole goes deep. So here's what I propose for now.

When generating constraints for an inverted index scan:

- We will traverse conjunctions and multiple JSON paths to find a single span to constrain the scan.
- If all the expressions in the FiltersExpr are disjunctions and contains expressions with a single JSON path, then we will generate a constraint with a span for each contains expr, and add a distinct operator after the index scan to eliminate duplicates.

When generating constraints for a inverted index zigzag join:

- We will traverse conjunctions and multiple JSON paths to find the first two spans that can constrain the zigzag join.

I'm still wrapping my head around the possibilities for "remaining filters", but I'd like to keep it simple for now. Our current implementation is already lacking, so I think for now we aim for the same bar to keep things manageble. For example, GenerateInvertedIndexZigZagJoins reuses the entire input filter.

**Comment by RaduBerinde** [comment]
Thanks for the writeup, it helps.

> A or (B and C) — As far as I can tell, no constrained scan is possible in this case.

We can constrain to spans A,B (and keep the filter), or similarly to spans A,C.

> Now assume that A', B', and C' have multiple paths, e.g. j @> '{"a": 1, "b": 2}'.

I'm not supercomfortable with json semantics, but any reason we can't split up all the paths and normalize this to `j @> '{"a": 1} AND j @> '{"b":2}'`?

> We will traverse conjunctions and multiple JSON paths to find the first two spans that can constrain the zigzag join.

I want to note that the execution operator supports any number of tables, not just 2. It's just our opt operator that right now only supports 2.

For remaining filters, I think the most important thing would be to to recognize simple cases when the constraints are exactly equivalent to the filter (aka "tightness") so we can remove the filter.

**Review by rytaft — COMMENTED** [review]
Nice work! I think you and Radu have already discussed most of the issues above, but it does seem like a big issue right now is how you'd get the correct remaining filter in the case of a zig zag join.

As Radu mentioned above, currently the optimizer only plans zig zag joins with 2 single-span constraints. But I think in the future we might also want to support intersecting the results of multiple constraints, each with multiple spans (not sure if the execution operator for zig zag join supports that, but we could still support it using set operations if need be).

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-:-M5YXi9pA0xtJEGnKYX8:b-54ox1i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YE2M_93V0syBGeb7Z:-M5YE2M_93V0syBGeb7_:b-85rtgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L90)):*
> ```Go
> 
> 	// filtersItemIdx is the index of the top-level FiltersItem within the input
> 	// FiltersExpr that is currently being search. When a constraintResult is
> ```

search -> searched
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YE9wB5c1AQKcG6kFT:-M5YE9wB5c1AQKcG6kFU:b-c1dxcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L111)):*
> ```Go
> 
> // constraintResult is a struct representing a constraint that has been
> // generated by the iterator. It store the constraint struct, a tight boolean,
> ```

store -> stores
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YEMeT8wUhJ_jISXGb:-M5YEMeT8wUhJ_jISXGc:b-ckt3zk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L153)):*
> ```Go
> 
> // Constraint returns the current constraint found by the iterator. Returns nil
> // if there is not current constraint.
> ```

not current -> no current
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YEiGU5DQGM8vfP-6T:-M5YEiGU5DQGM8vfP-6U:b-4gsfoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L207)):*
> ```Go
> //   @1 @> '{"a": 1, "b": 2}'
> //
> // If there is no currently enumerate constraint, an empty FiltersExpr is
> ```

enumerate -> enumerated ?
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YFVoL0nKUAr4YzSa9:-M5YFVoMDLOAQnDX8c-b:b-eo2zl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L254)):*
> ```Go
> //
> // Next will enumerate any previously collected constraints in iter.results.
> // Multiple constraint results may be previously collect by exploration of a single
> ```

collect -> collected
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YGVitDPjk2mPFA2JI:-M5YGVitDPjk2mPFA2JJ:b4z0myr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L326)):*
> ```Go
> 	switch t := e.(type) {
> 	case *memo.FiltersItem:
> 		// Increment filtersItemIdx every time a new FiltersItem in encountered.
> ```

in -> is
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YZPAK4M_LAZ6lU4xN:-M5YZPAK4M_LAZ6lU4xO:b-8wsh1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L335)):*
> ```Go
> 	case *memo.AndExpr:
> 		return iter.collectResultsForAndExpr(t)
> 	}
> ```

Maybe add a TODO for supporting multiple spans in case of OR?
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YHIeS2-L8FXQspcqu:-M5YHIeT4UBEn4bcYqj9:brjp3j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L389)):*
> ```Go
> 	}
> 
> 	log.Errorf(context.TODO(), "unexpected type in inverted index: %s", rightDatum.ResolvedType())
> ```

Typically we use `panic(errors.AssertionFailedf(...))` for these sorts of errors. But if we're not handling some known cases (e.g. Arrays?), this could create a lot of log spam.
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YIbKpEGTaF0-TU-QI:-M5YIbKpEGTaF0-TU-QJ:b1vl20t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L406)):*
> ```Go
> // collecting any results.
> //
> // The contains expressions is attached to any resulting constraints, so that
> ```

expressions -> expression
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 464 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YJjDz5ef5eK2iCCS0:-M5YJjE-60fE4xzimLvT:b-p748el) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L464)):*
> ```Go
> 	// A scalar on the right side of the @> operator indicates that scalars and
> 	// arrays must be found that contain that value. In order to do so, two
> 	// logical spans are generated, one for the original scalar and on for
> ```

on -> one
___
*[pkg/sql/opt/idxconstraint/inverted_index_constraints.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47734#-M5YJkTIDkRJ37lX-sTk:-M5YJkTIDkRJ37lX-sTl:b-co0v4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c429398f12cbbe33a94cd577c7b21abf06844410/pkg/sql/opt/idxconstraint/inverted_index_constraints.go#L465)):*
> ```Go
> 	// arrays must be found that contain that value. In order to do so, two
> 	// logical spans are generated, one for the original scalar and on for
> 	// arrasy containing the scalar. In this case this is valid and these two
> ```

arrasy -> arrays

**Comment by mgartner** [comment]
> We can constrain to spans A,B (and keep the filter), or similarly to spans A,C.

Doh, you're right. Good catch.

> I'm not supercomfortable with json semantics, but any reason we can't split up all the paths and normalize this to j @> '{"a": 1} AND j @> '{"b":2}'?

I think it's possible, but I'd have to do more research on if it'd work with deeply nested JSON objects. I don't _think_ it simplifies things a whole lot or is necessary, but I'll keep it on my TODO list.

> I want to note that the execution operator supports any number of tables, not just 2. It's just our opt operator that right now only supports 2.

This is good to know. I'll add a bonus task on my "TODO" list to see if we can get it working with N tables.

I wrote up a quick-and-dirty document to get some more of my thoughts down on paper. I expanded on some of the examples above to derive what I think are correct algorithms for generating constraints. It was non-obvious to me so I documented them in psuedo-code.

If you're interested, the doc is [here](https://gist.github.com/mgartner/72dc7d2c4d759735c4beb50fa3cfd3e2). It's probably not necessary to look at, but if you're curious what I've been thinking about, it's mostly there. Apologies if it's not the easiest text to consume.

Closing this, in favor of the new approach described in the doc linked above.

**Pull request closed without merging**
