### PR TITLE
.github/CODEOWNERS: update to latest attributions

### PR DESCRIPTION
**Pull request by knz**
This involves the following teams in more accurate places:
- SQL experience
- SQL observability
- Obs Infra
- Product security
- Multi-tenant

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
Regarding SQL Observability updates: :lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82810#-:-N4SB4Ac3ueOLXz3SuFV:b-hn03ex)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @catj-cockroach, @dhartunian, and @rafiss)

**Comment by knz** [comment]
@otan @tbg I'm getting a failure in github-post, `TestListFailures`. I'm not sure what the test failure is telling me; my change here is not touching the team assignments for the packages exercised by the test.

**Review by catj-cockroach — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82810)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @dhartunian, and @rafiss)

**Comment by otan** [comment]
> I'm getting a failure in github-post, TestListFailures.

maybe it did accidentally by, e.g. multi-tenant not being set earlier, or a new package definition later overriding something earlier. if it fails again lmk.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82810)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @knz, and @rafiss)

___
*[`.github/CODEOWNERS` line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82810#-N4SeKC56n7s4qBUV7v7:-N4SeKC56n7s4qBUV7v8:bbmwsjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb88567fa75a9ef60b5f85bf4f74a5595d7bf9d8/.github/CODEOWNERS#L117)):*
> ```CODEOWNERS
> /pkg/server/                             @cockroachdb/server-prs
> /pkg/server/addjoin*.go                  @cockroachdb/server-prs  @cockroachdb/prodsec
> /pkg/server/admin*.go                    @cockroachdb/obs-inf-prs @cockroachdb/server-prs
> ```

general question about the "dual" owners here, I feel like it typically dilutes accountability for the code review. (Or least it leads me to not prioritize). Is this a case where we require reviews from both owners? If not, what do you think about just having a single team?
___
*[`.github/CODEOWNERS` line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82810#-N4Sdofl96oxVdguITYh:-N4Sdofl96oxVdguITYi:b41psc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb88567fa75a9ef60b5f85bf4f74a5595d7bf9d8/.github/CODEOWNERS#L119)):*
> ```CODEOWNERS
> /pkg/server/admin*.go                    @cockroachdb/obs-inf-prs @cockroachdb/server-prs
> /pkg/server/api_v2*.go                   @cockroachdb/obs-inf-prs @cockroachdb/server-prs
> /pkg/server/authentication*.go           @cockroachdb/obs-inf-prs @cockroachdb/server-prs @cockroachdb/prodsec
> ```

@knz I'm a bit nervous about Obs Infra owning any auth stuff. This isn't an area of expertise for us and seems orthogonal to other observability functionality.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82810)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @dhartunian, and @rafiss)

___
*[`.github/CODEOWNERS` line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82810#-N4SeKC56n7s4qBUV7v7:-N4Si54f07hR3TBR9yNC:b-6roezf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb88567fa75a9ef60b5f85bf4f74a5595d7bf9d8/.github/CODEOWNERS#L117)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

general question about the "dual" owners here, I feel like it typically dilutes accountability for the code review. (Or least it leads me to not prioritize). Is this a case where we require reviews from both owners? If not, what do you think about just having a single team?
</blockquote></details>

the server team is currently unstaffed, so for now I guess the situation is clear.
___
*[`.github/CODEOWNERS` line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82810#-N4Sdofl96oxVdguITYh:-N4SiNG9Bhw7bvqGKVUc:b-3vwib5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb88567fa75a9ef60b5f85bf4f74a5595d7bf9d8/.github/CODEOWNERS#L119)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

@knz I'm a bit nervous about Obs Infra owning any auth stuff. This isn't an area of expertise for us and seems orthogonal to other observability functionality.
</blockquote></details>

The server team is currently unstaffed, and the prodsec team is currently not carrying any actual engineering responsibilities (they only want to audit changes/discussions).

What would be a better choice?

**Review by knz — COMMENTED** [review]
yes it passes now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82810#-:-N4TBWMV4U61yDyD31Br:b-tiikvy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @dhartunian, and @rafiss)

**Review by knz — COMMENTED** [review]
I've reverted the authn-related changes pending discussion with the identity team. PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82810#-:-N4TNEMHCAiAnkXhn0J7:b-rz5e5t)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @catj-cockroach, @dhartunian, @maryliag, and @rafiss)

___
*[`.github/CODEOWNERS` line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82810#-N4SeKC56n7s4qBUV7v7:-N4TNBv9DojY1yJLfJzp:bn345n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb88567fa75a9ef60b5f85bf4f74a5595d7bf9d8/.github/CODEOWNERS#L117)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

the server team is currently unstaffed, so for now I guess the situation is clear.
</blockquote></details>

I've changed it back.
___
*[`.github/CODEOWNERS` line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82810#-N4Sdofl96oxVdguITYh:-N4TNCyPCZJekmLXLGRk:b-swf2kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb88567fa75a9ef60b5f85bf4f74a5595d7bf9d8/.github/CODEOWNERS#L119)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The server team is currently unstaffed, and the prodsec team is currently not carrying any actual engineering responsibilities (they only want to audit changes/discussions).

What would be a better choice?
</blockquote></details>

I've changed this back.

**Comment by knz** [comment]
I'm going to go ahead and merge this. We can always revisit in a subsequent PR.

bors r=maryliag,catj-cockroach

**Review by dhartunian — COMMENTED** [review]
sgtm @knz, thx for reverting the authn stuff.

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82810#-:-N4XrFYl1tBAppnKAvtD:b-iofzsf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @catj-cockroach, @dhartunian, @maryliag, and @rafiss)

**Comment by knz** [comment]
bors r=maryliag,catj-cockroach,dhartunian

**Pull request merged**
