### PR TITLE
sql: Make all sql.defaults cluster settings public

### PR DESCRIPTION
**Pull request by CNeenan**
Closes issue: https://github.com/cockroachdb/cockroach/issues/62174

### CODE REVIEW

**Comment by CNeenan** [comment]
The checks are failing with the following, not sure if this should be done within this pull request?

[21:25:43][Ensure generated code is up-to-date] Some automatically generated code is not up to date.
[21:25:43][Ensure generated code is up-to-date] Run `make generate` to automatically regenerate these.
[21:25:43][Ensure generated code is up-to-date] Process exited with code 1

**Review by arulajmani — COMMENTED** [review]
The change looks good, thanks for taking it on! I think these cluster settings affect generated code, so getting CI to pass will entail running `make generate` and including what's generated in your commit. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66688#-:-MdHwZhq4fBTlkdVobem:b-5hqd41)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by CNeenan** [comment]
Added the generated code, sorry about the multiple bot comments, was trying to squash the commits as instructed but had never used that command before

**Review by arulajmani — COMMENTED** [review]
Thanks for doing the change. The only thing that's missing here is the commit message with a summary of your change. We have a template for this in our wiki (https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages), but the TLDR is that the commit message title should be prefixed by the package name the change was in (in this case sql). The commit body should have a small note on what the change was. As this particular change is user facing, we probably want to include a `Release Note` here as well, which says that all the sql level cluster settings have been made public. Lastly, we also reference the github issue in the commit message -- that way once the PR goes in, the issue will automatically be closed. 

Sorry for dumping a bunch of commit message info on you, but once you've updated the commit message this should be ready to merge! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66688#-:-MdJCkiW9Y4DikzgZTq_:bq334cf)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by CNeenan** [comment]
I have updated the commit message using the guide, thank you

**Review by arulajmani — APPROVED** [review]
Thanks for updating the commit message and your contribution! This looks good to go :lgtm: 

bors r=arulajmani

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66688#-:-MdN3rPlC0kTviNcF6Pv:bdmtk2q)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by CNeenan** [comment]
Do you know why the Gitlab CI passed but then failed on the merge?

**Comment by arulajmani** [comment]
I think it's a merge skew in the auto-generated code. You might need to rebase your branch against master, re-generate using `make generate`, amend your commit, and then push again.

**Comment by CNeenan** [comment]
Thank you, pushed that up so hopefully will pass now

**Comment by CNeenan** [comment]
Now the Bazel CI is failing but says optional, what should I do?

**Review by arulajmani — COMMENTED** [review]
I think it's fine considering CI is passing. I'll try and merge this again. 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66688#-:-MdSJA7VA35cjgK5u_zy:b-s3k2xg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
