### PR TITLE
docs: remove reference to RoachNode

### PR DESCRIPTION
**Pull request by spencerkimball**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9649)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/design.md, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWXdpP4dbHN5Uf8Sg:-KSwWXdpP4dbHN5Uf8Sh:b-1i6hds) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L86)):*
> ```Markdown
> Ranges
> 
> Each physical node exports two RPC-based key value API: one for
> ```

s/API/APIs/

---

*[docs/design.md, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWbsQ0uFkQ99hmUYT:-KSwWbsQ0uFkQ99hmUYU:bn9ox4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L88)):*
> ```Markdown
> Each physical node exports two RPC-based key value API: one for
> external clients and one for internal clients (exposing sensitive
> operational features). Both services accept batches of KV requests and
> ```

s/KV//g from this sentence.

---

*[docs/design.md, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWfqeSo8aeiODLhB1:-KSwWfqeSo8aeiODLhB2:bqqjoy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L90)):*
> ```Markdown
> operational features). Both services accept batches of KV requests and
> return batches of KV responses. Nodes are symmetric in capabilties and
> exported interfaces. Each has the same binary and may assume any
> ```

s/. E/; e/

---

*[docs/design.md, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWjX67P8Xh8SeAfIO:-KSwWjX67P8Xh8SeAfIP:b1mdxd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L91)):*
> ```Markdown
> return batches of KV responses. Nodes are symmetric in capabilties and
> exported interfaces. Each has the same binary and may assume any
> roles.
> ```

s/roles/role/

---

*[docs/design.md, line 616 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWv43BS_mtiTexNhX:-KSwWv43BS_mtiTexNhY:b8ls2v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L616)):*
> ```Markdown
> 
> Nodes maintain a separate instance of RocksDB for each disk. Each
> RocksDB instance hosts any number of ranges. RPCs arriving at a node
> ```

s/range/replicas/

---

*[docs/design.md, line 617 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWyh3sRgghiOgduQY:-KSwWyh3sRgghiOgduQZ:b-ad34p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L617)):*
> ```Markdown
> Nodes maintain a separate instance of RocksDB for each disk. Each
> RocksDB instance hosts any number of ranges. RPCs arriving at a node
> are multiplexed based on the disk name to the appropriate RocksDB
> ```

s/multiplexed/routed/ and remove "disk name" lies

---

*[docs/design.md, line 869 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwXGlDxPpx7yjy0T1Y:-KSwXGlDxPpx7yjy0T1Z:b-sxcjao) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L869)):*
> ```Markdown
> (or a range of keys) that the command accesses and (2) the ID of a
> range which the key(s) belongs to. When receiving a command, a node
> looks up a range by the specified Range ID and checks if the range is
> ```

so much inaccuracy here :(

---

*[docs/design.md, line 1352 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwXQtarANpRKquuJxZ:-KSwXQtbEgfBmXtNtdxX:bv269g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L1352)):*
> ```Markdown
> distributed cluster.
> 
> In addition to the gateway for external DB client traffic, each Node provides the full key/value API (including all internal methods) via
> ```

wrap while you're here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-:-KSwXSZZlMa4KpMaVQuy:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/design.md, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWXdpP4dbHN5Uf8Sg:-KSwXn1iDvah8ZcHCJtu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L86)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/API/APIs/
</details>
Done.

---

*[docs/design.md, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWbsQ0uFkQ99hmUYT:-KSwXp6U14HbCnUSVKIo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L88)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/KV//g from this sentence.
</details>
Done.

---

*[docs/design.md, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWfqeSo8aeiODLhB1:-KSwXs2Pxzudxo2r8ZQg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L90)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/. E/; e/
</details>
Done.

---

*[docs/design.md, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWjX67P8Xh8SeAfIO:-KSwXtWpwRKuC_kcXp1m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L91)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/roles/role/
</details>
Done.

---

*[docs/design.md, line 616 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWv43BS_mtiTexNhX:-KSwXyuqfx4I47mD12Hc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L616)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/range/replicas/
</details>
Done.

---

*[docs/design.md, line 617 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwWyh3sRgghiOgduQY:-KSwYB2NVNzwWDsElxwr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L617)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/multiplexed/routed/ and remove "disk name" lies
</details>
Done.

---

*[docs/design.md, line 869 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwXGlDxPpx7yjy0T1Y:-KSwYCdwQvBhSsRyJf5B:b-tinaj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L869)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> so much inaccuracy here :(
</details>
This is another section which needs updating. I was thinking we give it to @nvanbenschoten

---

*[docs/design.md, line 1352 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwXQtarANpRKquuJxZ:-KSwYNuGbm_35g0DLrf4:b-b1csit) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L1352)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> wrap while you're here
</details>
This section is gone now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-:-KSwYsqa5uUXUe1IkpL9:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/design.md, line 869 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649#-KSwXGlDxPpx7yjy0T1Y:-KSwbQJLSvUDCq6fPzF1:b-9q1xve) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f596c727d179462ec034aca2dba23881c7d0f6/docs/design.md#L869)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> This is another section which needs updating. I was thinking we give it to @nvanbenschoten
</details>
Sure, I'll take this section.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9649)*

**Comment by tamird** [comment]
Squash plz

**Comment by spencerkimball** [comment]
What do I do to squash?

**Pull request merged**
