### PR TITLE
opt: ensure validation of unique constraints is efficient

### LINKED ISSUE #56201: sql, opt: validating the unique constraint must be efficient for partitioned unique indexes
As discussed offline with @RaduBerinde:

When we create a partitioned unique index, we need to validate that we don't have duplicates on the unique column(s). If we write down a validation query for that today, it would likely end up being a hash aggregation on the full table, which is not acceptable. Instead, we would want to separate the scans between the regions so that each scan is ordered, and union them (keeping order) into a streaming aggregation.

To achieve this, we may be able to extend `SplitScanIntoUnionScans` (as described in https://github.com/cockroachdb/cockroach/issues/55156). Additionally, we currently only apply the rule when there's a limit, but we could add a corresponding rule for aggregations.

### PR DESCRIPTION
**Pull request by rytaft**
**opt: ensure validation of unique constraints is efficient**

This commit adds two new exploration rules: `SplitGroupByScanIntoUnionScans`
and `SplitGroupByFilteredScanIntoUnionScans`.

`SplitGroupByScanIntoUnionScans` splits a non-inverted scan under a `GroupBy`,
`DistinctOn`, or `EnsureUpsertDistinctOn` into a union-all of scans, where each
scan is ordered on the grouping columns. This ordering is then maintained by
the union-all operation and passed on to the grouping operation. Ordering on
the grouping columns is important since it enables the grouping operation to
execute in a streaming fashion, which is more efficient. Example:
```
   CREATE TABLE tab (
     region STRING NOT NULL CHECK (region IN ('ASIA', 'EUROPE')),
     data INT NOT NULL,
     INDEX (region, data)
   );

   SELECT DISTINCT data
   FROM tab;

   =>

   SELECT DISTINCT data
   FROM (SELECT * FROM tab WHERE region='ASIA')
   UNION ALL (SELECT * FROM tab WHERE region='EUROPE');
```
This rule does not actually build the streaming grouping operation, but it
allows another rule, `GenerateStreamingGroupBy`, to fire and use the new
interesting orderings provided by the `UnionAll` of scans to build a streaming
operation.

`SplitGroupByFilteredScanIntoUnionScans` is like `SplitGroupByScanIntoUnionScans`,
but the scan is wrapped in a Select.

These transformations are important for ensuring that validation of the
unique constraint in an implicitly-partitioned unique index is efficient. The
validation query to verify that `(a, b)` is UNIQUE on table `tbl` looks like this:
```
   SELECT a, b
   FROM tbl
   WHERE a IS NOT NULL AND b IS NOT NULL
   GROUP BY a, b
   HAVING count(*) > 1
   LIMIT 1;
```
Without `SplitGroupByFilteredScanIntoUnionScans`, this query would require an
inefficient and memory-intensive hash group by operation. Note that the
previous rule, `SplitGroupByScanIntoUnionScans`, is also needed since it would
apply in cases where `a` and `b` are not nullable.

Fixes #56201

Release note (performance improvement): Validation of a new UNIQUE index in a
REGIONAL BY ROW table no longer requires an inefficient and memory-intensive
hash aggregation query. The optimizer can now plan the validation query so
that it uses all streaming operations, which are much more efficient.

**opt: move splitScanIntoUnionScans to general_funcs.go**

This commit moves `splitScanIntoUnionScans` and all helper functions
into `general_funcs.go` since it's now used in both `limit_funcs.go` and
`groupby_funcs.go`. This is a separate commit for ease of reviewing.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
Please ignore the first commit; it's from #65350.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Nicely done!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-:-M_xjMTrAsTjExOAqDEL:b-o11ew6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/limit_funcs.go, line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-M_xiFC650rN0EnxVt5W:-M_xiFC650rN0EnxVt5X:bb0x2h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/64d445a4ddc446932acf735281eed84a1b394b59/pkg/sql/opt/xform/limit_funcs.go#L215)):*
> ```Go
> // SplitScanIntoUnionScans returns a UnionAll of Scan operators (with an
> // optional hard limit) that each scan over a single key from the original
> // Scan's constraints. If no such UnionAll of Scans can be found, ok=false is
> ```

[nit] returns a UnionAll [..] if the scans can provide the given ordering, and if the statistics suggest that splitting the scan could be beneficial.
___
*[pkg/sql/opt/xform/limit_funcs.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-M_xiYhB9aM3LE5xTLE9:-M_xiYhB9aM3LE5xTLEA:bbnjjbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/64d445a4ddc446932acf735281eed84a1b394b59/pkg/sql/opt/xform/limit_funcs.go#L263)):*
> ```Go
> 
> 	if scan.Relational().Stats.Available &&
> 		float64(scanCount*limit*threshold) >= scan.Relational().Stats.RowCount {
> ```

[nit] I would put all the code that is limit specific inside an `if limit > 0`. It's more or less luck that it all works out with 0, better to not have to think about it.
___
*[pkg/sql/opt/xform/limit_funcs.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-M_xiLv00uu6N8-j_4qd:-M_xiLv00uu6N8-j_4qe:bpda92v) ([raw file](https://github.com/cockroachdb/cockroach/blob/64d445a4ddc446932acf735281eed84a1b394b59/pkg/sql/opt/xform/limit_funcs.go#L272)):*
> ```Go
> 	// The index ordering must have a prefix of columns of length keyLength
> 	// followed by the ordering columns either in order or in reverse order.
> 	hasLimitOrderingSeq, reverse := indexHasOrderingSequence(
> ```

[nit] hasOrderingSeq
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-M_xgMPS1fJqOuevhUs_:-M_xgMPS1fJqOuevhUsa:b-enrkmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/64d445a4ddc446932acf735281eed84a1b394b59/pkg/sql/opt/xform/rules/groupby.opt#L163)):*
> ```
> )
> =>
> ((OpName) $unionScans $aggs $private)
> ```

After this rule runs, we are relying on the existing exploration rules to generate a streaming GroupBy, correct?

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-:-Ma-3e7r-BTHVICDazt-:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/xform/limit_funcs.go, line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-M_xiFC650rN0EnxVt5W:-M_zykdyBPjx_DQfyKRR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64d445a4ddc446932acf735281eed84a1b394b59/pkg/sql/opt/xform/limit_funcs.go#L215)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] returns a UnionAll [..] if the scans can provide the given ordering, and if the statistics suggest that splitting the scan could be beneficial.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/limit_funcs.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-M_xiYhB9aM3LE5xTLE9:-M_zzMdC3FuddoV-Sq3R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64d445a4ddc446932acf735281eed84a1b394b59/pkg/sql/opt/xform/limit_funcs.go#L263)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would put all the code that is limit specific inside an `if limit > 0`. It's more or less luck that it all works out with 0, better to not have to think about it.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/limit_funcs.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-M_xiLv00uu6N8-j_4qd:-M_zzOYFAudaIe7ufsCh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64d445a4ddc446932acf735281eed84a1b394b59/pkg/sql/opt/xform/limit_funcs.go#L272)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] hasOrderingSeq
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-M_xgMPS1fJqOuevhUs_:-M_zzSVCEIOT6kE7tWg0:b2sgzws) ([raw file](https://github.com/cockroachdb/cockroach/blob/64d445a4ddc446932acf735281eed84a1b394b59/pkg/sql/opt/xform/rules/groupby.opt#L163)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

After this rule runs, we are relying on the existing exploration rules to generate a streaming GroupBy, correct?
</blockquote></details>

Yep! Added a comment.

**Review by mgartner — APPROVED** [review]
[nit] the PR description is missing the second commit

Looks great! :lgtm: 

> Reviewed 5 of 7 files at r2, 2 of 2 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-:-Ma-LVLI4V4leY1pmSbK:b-68sbiz)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rytaft)

___
*[pkg/sql/opt/xform/groupby_funcs.go, line 213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-Ma-QwSb4uuT96JuupeE:-Ma-QwSb4uuT96JuupeF:bv86s9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce840042f4eef38e6e61fd8c7f6b17903e2a6a16/pkg/sql/opt/xform/groupby_funcs.go#L213)):*
> ```Go
> 	scan memo.RelExpr, sp *memo.ScanPrivate, private *memo.GroupingPrivate,
> ) (_ memo.RelExpr, ok bool) {
> 	cons, ok := c.getKnownScanConstraint(sp)
> ```

[nit] move the definition of `getKnownScanConstraint` from `limit_funcs.go` to `general_funcs.go` (probably in a separate commit)
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-Ma-NpApDyoh4lmLSwb7:-Ma-NpApDyoh4lmLSwb8:b-iaw3i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce840042f4eef38e6e61fd8c7f6b17903e2a6a16/pkg/sql/opt/xform/rules/groupby.opt#L185)):*
> ```
> # inefficient and memory-intensive hash group by operation. Note that the
> # previous rule, SplitGroupByScanIntoUnionScans, is also needed since it would
> # apply in cases where a and b are not nullable.
> ```

[nit] It might be nice to expand this sentence a bit more—"are not nullable" confused me a bit when I read it because I thought it should read "are nullable". Something like "it would apply in cases where a and b are not nullable **(the `IS NOT NULL` filters would be eliminated during normalization)**". (Or is it that the `IS NOT NULL` filters are not part of the query to begin with?)

**Review by DrewKimball — APPROVED** [review]
Really cool!

It might be nice to have a comment explaining why zero is passed as the limit to `SplitScanIntoUnionScans`.

**Review by rytaft — COMMENTED** [review]
TFTRs!

> [nit] the PR description is missing the second commit

Done.

> It might be nice to have a comment explaining why zero is passed as the limit to SplitScanIntoUnionScans.

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-:-Ma1AEYiDSNf6RZiGFqf:b-e2d57q)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/xform/groupby_funcs.go, line 213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-Ma-QwSb4uuT96JuupeE:-Ma3nvtL0CITPFJQ2xC4:b-5sp78f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce840042f4eef38e6e61fd8c7f6b17903e2a6a16/pkg/sql/opt/xform/groupby_funcs.go#L213)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] move the definition of `getKnownScanConstraint` from `limit_funcs.go` to `general_funcs.go` (probably in a separate commit)
</blockquote></details>

It was moved in the second commit.
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-Ma-NpApDyoh4lmLSwb7:-Ma3oMX443Mqo2_eKrhj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce840042f4eef38e6e61fd8c7f6b17903e2a6a16/pkg/sql/opt/xform/rules/groupby.opt#L185)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] It might be nice to expand this sentence a bit more—"are not nullable" confused me a bit when I read it because I thought it should read "are nullable". Something like "it would apply in cases where a and b are not nullable **(the `IS NOT NULL` filters would be eliminated during normalization)**". (Or is it that the `IS NOT NULL` filters are not part of the query to begin with?)
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-:-Ma4JgVD4MzTbK-KlW9N:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/xform/groupby_funcs.go, line 213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-Ma-QwSb4uuT96JuupeE:-Ma4Jalo1fh17pYhlWy2:b-339axv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce840042f4eef38e6e61fd8c7f6b17903e2a6a16/pkg/sql/opt/xform/groupby_funcs.go#L213)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It was moved in the second commit.
</blockquote></details>

Ahh I missed that...

**Review by rytaft — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65355#-:-Ma4Une81XOc6wTmS788:b-voiyyw)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Pull request merged**
