### PR TITLE
build: clean up various scripts

### PR DESCRIPTION
**Pull request by tamird**
Last commit is the big one.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13155)

### CODE REVIEW

**Comment by petermattis** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 21 of 21 files at r4, 1 of 1 files at r5, 6 of 6 files at r6, 10 of 10 files at r7.
Review status: 24 of 30 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[build/Dockerfile, line 1 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNM9fzZxqZTCpyrxvP:-KbNM9g-pofRENxcfMqI:b-c51b7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/44079ee0c3422e1864b38283d7729401d2852749/build/Dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:xenial-20170119
> ```

What effect does this have on the size of our builder image? Just curious. And not being docker-fluent, what image is `golang:1.7.4` based on?

---

*[build/bootstrap/bootstrap-debian.sh, line 59 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLjBORaErEb-vJrtS:-KbNLjBORaErEb-vJrtT:bwgk1ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/build/bootstrap/bootstrap-debian.sh#L59)):*
> ```Shell
> echo "add-auto-load-safe-path ${HOME}/goroot/src/runtime/runtime-gdb.py" >> ~/.gdbinit
> 
> go get -d github.com/cockroachdb/cockroach
> ```

I'm not a fan of getting rid of all of this. Having to log into the worker and then use a builder is awkward. Feels like a step backward and orthogonal to the builder image change that is the main portion of this commit. 

---

*[scripts/gceworker.sh, line 9 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLI7hfluwFNC9SbbX:-KbNLI7hfluwFNC9SbbY:bf5bjpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/scripts/gceworker.sh#L9)):*
> ```Shell
> GOVERSION=${GOVERSION-1.7.4}
> 
> name=${GCEWORKER_NAME-gceworker$(echo "${GOVERSION}" | tr -d '.')}
> ```

Why this change? I'll have to set `GCEWORKER_NAME` to log into my worker. Or recreate it. Seems orthogonal to the rest of the commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155)*

**Comment by tamird** [comment]
Review status: 24 of 30 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[build/Dockerfile, line 1 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNM9fzZxqZTCpyrxvP:-KbNMOGWqsziITAn8mMO:bhrfow7) ([raw file](https://github.com/cockroachdb/cockroach/blob/44079ee0c3422e1864b38283d7729401d2852749/build/Dockerfile#L1)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What effect does this have on the size of our builder image? Just curious. And not being docker-fluent, what image is `golang:1.7.4` based on?
</blockquote></details>

This takes us from 1.04 GB to 1.33 GB. `golang:1.7.4` is based on `debian:jessie`, which weighs in at 123 MB compared to `ubuntu:xenial-20170119` at 129 MB, so the increase in the builder image is mostly not due to the base image change, and probably has more to do with the other additions (newer compilers, the instrumented libc++, etc.).

---

*[build/bootstrap/bootstrap-debian.sh, line 59 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLjBORaErEb-vJrtS:-KbNNB8qG4BNGusKOfhU:b-fanrzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/build/bootstrap/bootstrap-debian.sh#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not a fan of getting rid of all of this. Having to log into the worker and then use a builder is awkward. Feels like a step backward and orthogonal to the builder image change that is the main portion of this commit. 
</blockquote></details>

Well, it is and it isn't - the point of this PR was to reorganize and reduce duplication in the various tools we have. What's the downside to using the container on the worker? I bet I could get `gceworker.sh ssh` to land you straight into the container, if the ergonomics are the sticking point.

---

*[scripts/gceworker.sh, line 9 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLI7hfluwFNC9SbbX:-KbNNfetvUtglmtrYS88:bsgwwgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/scripts/gceworker.sh#L9)):*
The commit message states:

> This also removes the need to have versioned gce/az workers, so that "configuration" is removed as well.

You're right that there's a migration here, but the previous pattern requires a migration every time we bump the go version, which this no longer will.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155)*

**Comment by petermattis** [comment]
Review status: 24 of 30 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[build/Dockerfile, line 1 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNM9fzZxqZTCpyrxvP:-KbQpYoqcLC954yUibMG:b-v056lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/44079ee0c3422e1864b38283d7729401d2852749/build/Dockerfile#L1)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This takes us from 1.04 GB to 1.33 GB. `golang:1.7.4` is based on `debian:jessie`, which weighs in at 123 MB compared to `ubuntu:xenial-20170119` at 129 MB, so the increase in the builder image is mostly not due to the base image change, and probably has more to do with the other additions (newer compilers, the instrumented libc++, etc.).
</blockquote></details>

Ok, that sounds fine.

---

*[build/bootstrap/bootstrap-debian.sh, line 59 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLjBORaErEb-vJrtS:-KbQpdAVNr25R35JdiLX:bdq2uu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/build/bootstrap/bootstrap-debian.sh#L59)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Well, it is and it isn't - the point of this PR was to reorganize and reduce duplication in the various tools we have. What's the downside to using the container on the worker? I bet I could get `gceworker.sh ssh` to land you straight into the container, if the ergonomics are the sticking point.
</blockquote></details>

The ergonomics as well as the disruption. I'm going to have to learn a new workflow, which isn't too bad, but multiply by all of the engineers. The reason for the change isn't urgent either. I'd prefer if this part of the PR was reverted.

---

*[scripts/gceworker.sh, line 9 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLI7hfluwFNC9SbbX:-KbQpw2DmfuvMHjdnqM7:b-i7gm0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/scripts/gceworker.sh#L9)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

The commit message states:

> This also removes the need to have versioned gce/az workers, so that "configuration" is removed as well.

You're right that there's a migration here, but the previous pattern requires a migration every time we bump the go version, which this no longer will.
</blockquote></details>

I believe whoever added this did so because it allowed easily creating and bootstrapping workers with different go versions installed. And when the Go version change, my habit is to nuke and recreate my worker. I think this part of the PR should be reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155)*

**Review by a-robinson — COMMENTED** [review]
Unless you think you specifically need my eyes on this, I'll let @petermattis handle the review. I scanned through and didn't notice anything too scary, but I'm a pretty bad sysadmin.

**Comment by tamird** [comment]
Review status: 24 of 30 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[build/bootstrap/bootstrap-debian.sh, line 59 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLjBORaErEb-vJrtS:-KbR-49yjetpPnvO344W:b97fww3) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/build/bootstrap/bootstrap-debian.sh#L59)):*
> The ergonomics as well as the disruption. I'm going to have to learn a new workflow, which isn't too bad, but multiply by all of the engineers.

I'd like to measure the number of people affected by this, but apparently there's no way to tell who has GCE machines provisioned that are billed to our account?

> The reason for the change isn't urgent either.

When do we make changes like this, then?

---

*[scripts/gceworker.sh, line 9 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLI7hfluwFNC9SbbX:-KbR-X_qXEjm9KdmPu1b:b-j5p52x) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/scripts/gceworker.sh#L9)):*
> I believe whoever added this did so because it allowed easily creating and bootstrapping workers with different go versions installed.

I agree, but the point I'm making is that it will no longer be necessary to do so.

I think what's missing from this PR is the ergonomics to allow SSHing directly into the container, and also controlling the version of the builder container that is used (to address the case of switching go versions).

I'm going to think about that a bit more later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 24 of 30 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[build/bootstrap/bootstrap-debian.sh, line 59 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLjBORaErEb-vJrtS:-KbR18q86jzUDIISvsSD:b8ktg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/build/bootstrap/bootstrap-debian.sh#L59)):*
> When do we make changes like this, then?

I don't have a good answer to that. My objection to doing so in this PR is that it is unrelated to supporting musl-based builds. And a bit of a distraction. And if you pulled it out into a separate PR my reaction would probably be "why are you moving my cheese?". How do I benefit from it?

---

*[scripts/gceworker.sh, line 9 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLI7hfluwFNC9SbbX:-KbR0xK5CQEO2ReTplLq:brgjf64) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/scripts/gceworker.sh#L9)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> I believe whoever added this did so because it allowed easily creating and bootstrapping workers with different go versions installed.

I agree, but the point I'm making is that it will no longer be necessary to do so.

I think what's missing from this PR is the ergonomics to allow SSHing directly into the container, and also controlling the version of the builder container that is used (to address the case of switching go versions).

I'm going to think about that a bit more later.

</blockquote></details>

The ergonomics is one bit, but how would you have one worker configured for Go 1.7.4 and another configured for Go 1.8.0?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-:-KbR24sXGJt9Utx6fJua:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 24 of 30 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[build/bootstrap/bootstrap-debian.sh, line 59 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLjBORaErEb-vJrtS:-KbR2fkdqY9zYL207dxb:blvyelg) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/build/bootstrap/bootstrap-debian.sh#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

> When do we make changes like this, then?

I don't have a good answer to that. My objection to doing so in this PR is that it is unrelated to supporting musl-based builds. And a bit of a distraction. And if you pulled it out into a separate PR my reaction would probably be "why are you moving my cheese?". How do I benefit from it?
</blockquote></details>

I can move it to the musl PR if you prefer; 6 of one, half a dozen of the other, as far as I'm concerned.

---

*[scripts/gceworker.sh, line 9 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155#-KbNLI7hfluwFNC9SbbX:-KbR2mWGE2RnPiIbJKdu:b-rbqvaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d0d249e073e77486d2f05f77a8af253bdff764/scripts/gceworker.sh#L9)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The ergonomics is one bit, but how would you have one worker configured for Go 1.7.4 and another configured for Go 1.8.0?
</blockquote></details>

Is that a real use case that you've had? I would imagine you'd have a single worker with perhaps two containers.

Right now we don't version the go cache, but we could, if indeed this is a use case we wanted to support. Anyhow, I've removed this commit, and I'll move it to the musl PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13155)*

**Pull request merged**
