### PR TITLE
kvserver: add load-based rebalancing metrics to the allocator

### PR DESCRIPTION
**Pull request by aayushshah15**
This commit adds some sorely needed metrics around the allocator's load-based rebalancing decisions that will hopefully help us diagnose potential issues without having to resort to enabling vmodules.

Release note: None

### CODE REVIEW

**Comment by aayushshah15** [comment]
Friendly ping.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76405#-:-MyhiC3u4hsPYVlB5VNP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/allocator.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76405#-Myhhp6QDAFpxSXoMz0L:-Myhhp6QDAFpxSXoMz0M:b-xpfrxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd4f181b8333029490ffc9218a44e7c6cf31a30b/pkg/kv/kvserver/allocator.go#L451)):*
> ```Go
> }
> 
> type loadBasedReplicaRebalancingMetrics struct {
> ```

nit: should this be `Rebalance` instead of `Rebalancing` for symmetry with `Transfer` above.

**Review by aayushshah15 — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76405#-:-MymmKUp4_3AqTJLU20A:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76405#-Myhhp6QDAFpxSXoMz0L:-MymmG5ECoSuvYghWmU6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd4f181b8333029490ffc9218a44e7c6cf31a30b/pkg/kv/kvserver/allocator.go#L451)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: should this be `Rebalance` instead of `Rebalancing` for symmetry with `Transfer` above.
</blockquote></details>

Done.

**Comment by aayushshah15** [comment]
bors r-

(didn't realize there were merge conflicts to `master`, sorry)

**Pull request merged**
