### PR TITLE
jobs: introduce jobspb.JobID

### LINKED ISSUE #61121: jobs: introduce JobID type
We should introduce this in `jobs` or `jobspb`:

```go
type JobID int64

const InvalidJobID JobID = 0
```

Replacing all the existing usages will be mechanical but annoying. A good start would be to just replace the IDs in the jobs packages themselves, though we use job IDs in many other places, including in proto messages (for table descriptors, etc.).

### PR DESCRIPTION
**Pull request by thoszhang**
This commit introduces a `jobspb.JobID` int64 type and uses it in most
places where we were previously using an int64.

Closes #61121.

Release justification: Low-risk change to existing functionality.

Release note: None

### CODE REVIEW

**Comment by lucy-zhang** [comment]
I wasn't originally planning to do this right now, but I got too deep into it. There are probably still some tests that need to be fixed.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 69 of 69 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61128#-:-MUPZBjUCsyQyMqn810j:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @pbardea)

**Comment by lucy-zhang** [comment]
TFTR

bors r+

**Pull request merged**
