### PR TITLE
sql: implement `COMMENT ON TABLE`

### PR DESCRIPTION
**Pull request by hueypark**
Informs  #19472.

This patch introduces support for table comments.

The syntax to set or delete a comment is the same as postgres:
`COMMENT ON TABLE ... IS ...`. See:
https://postgresql.org/docs/9.1/sql-comment.html

This also makes `pg_catalog.pg_description` and `obj_description()` do
the right thing for compatibility with 3rd party clients.

This is supported by a new system table `system.comments`, which is
extensible to support comments on other database objects than tables:

- its `type` column indicates the type of object, to distinguish
  between db, table, column and others. For now just one type is
  defined.
- `object_id`: table or database ID, relative to the `type`.
- `sub_id`: when a comment is placed on an object "inside" another, eg
  a column inside a table.
- `comment`: the comment proper.

This design of `system.comments` mimics pg's own `pg_description`
which uses the same schema.

Release note (sql change): CockroachDB now supports associating
comments to SQL tables using PostgreSQL's `COMMENT ON TABLE`
syntax. This also provides proper support for pg's
`pg_catalog.pg_description` and built-in function `obj_description()`.

Release note (sql change): The `SHOW TABLES` statement
now supports printing out table comments using the optional phrase
`WITH COMMENT`, e.g `SHOW TABLES FROM mydb WITH COMMENT`.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Ok so your change overall is valid and achieves the functionality. Thank you for taking a look.

That being said it is creating a "special case" for table comments. If we wanted to generalize this PR to also support database comments, we would need a separate field on database descriptors. Then if we wanted to support column comments, we would need to add separate fields on column descriptors. And so on.

All these new fields would increase the overa;l memory usage by descriptors. Not to count that all the updates will need different code paths to flush the descriptor caches, query them in introspection, etc.

This is the pitfall that Bram was pointing out in https://github.com/cockroachdb/cockroach/issues/19472#issuecomment-438351936:  the more extensible approach is to **store the comments in a system table**.

The system table would be created like this:
```sql
CREATE TABLE system.comments (
   type INT NOT NULL, -- type of object, to distinguish between db and non-db objects
   object_id INT NOT NULL, -- main object ID, this will be usually db/table desc ID
   sub_id INT, -- sub-ID for columns inside table, NULL for other types
   comment STRING, -- the comment
   UNIQUE (type, object_id, sub_id)
)
```

Then `COMMENT ON TABLE db.x` would be translated (and planned as)

```sql
UPSERT INTO system.comments (type, object_id, comment)
  VALUES('table', tbl_id, comment)
```

And we would need to be careful during TRUNCATE (which generates new table IDs) to issue an UPDATE on `system.comments` as well.

Does this make sense to you?

> Reviewed 16 of 16 files at r1, 5 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-:-LRl5GTU8QCI661FFB2w:b-tjqgt9)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by hueypark** [comment]
I understand. I'll be back with improved implementation soon.

**Review by knz — COMMENTED** [review]
This is very good! I have looked at the PR and this goes all in the right direction.

To complete the reviews we are going to work in two steps. First I will make general high-level comments, and we can iterate on that. Once we have addressed high-level comments I will make more detailed / fine comments.

The first high level comments:

1) please include a unit test in `pkg/sql` that adds a comment on a table, then verifies via `pg_description` that it is visible/available. Then include another unit test that verifies that a comment can be erased.

2) you have chosen to place postgres OIDs (`h.TableOid()`) directly in the `system.comment` table.  I think for now, we would prefer to not use postgres-specific logic (e.g. the OID computation) in the system tables. So I think it would be better to store the CockroachDB table IDs / column IDs inside `system.comments` and compute the postgres OID only when `pg_description` is queried.

Regarding this point, however, I would also like some advice from @jordanlewis: the OID computation (`oidHasher.TableOid`) currently uses table descriptors as input. However the proposed change here will populate just the table ID in the `system.comments` table. So we would need to look up the descriptor before we can produce an Oid. This seems wasteful: why cannot we compute a table Oid from the table ID directly?

3) this point is related to point 1 above. You need to explain (in English, in the commit message) what is the **data model** you are using in this change. The data model is an explanation of the data structure used to represent comments, with examples. Your explanation must state:

- how the `system.comment` table is holding comments for tables.
- what happens when new tables are added, existing tables are deleted or renamed.
- it should also suggest how we can add support for database and column comments in the future.

4) you need to extend your PR to also support TRUNCATE. In CockroachDB, truncate is equivalent to a DROP + CREATE, so the table ID changes. Your PR must extend the TRUNCATE logic to move the comment from the old ID to the new ID. This also must be exercised in a unit test.

5) I think you also need to extend the PR to support DROP TABLE (so that it also removes the comment). This also needs a test.

6) it would be useful to include the table comment as an additional column in the output of SHOW TABLES (this is optional - do not feel obliged to do this. It is "nice to have". If you choose to do this, consider using a LEFT OUTER JOIN to populate this column.) It is interesting to think about this problem because it can help think about points 2 and 3 above.

> Reviewed 18 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-:-LSELOik6hOxpLFxP7Kw:b3vcs6c)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/keys/constants.go, line 334 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSELM1hBaA-7indnbpV:-LSELM1hBaA-7indnbpW:b-pdurpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/672b4e8e06ccbfd94b7741babde5fb3204bb6dd9/pkg/keys/constants.go#L334)):*
> ```Go
> 
> 	// CommentType is type for system.comments
> 	TableCommentType = 1
> ```

Can you explain to me what this value is for?

**Comment by hueypark** [comment]
@knz
Thank you for your kind review.
I will follow your comments.

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/keys/constants.go, line 334 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSELM1hBaA-7indnbpV:-LSK4xVZ3oW3DySLlFUM:bpdks9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/672b4e8e06ccbfd94b7741babde5fb3204bb6dd9/pkg/keys/constants.go#L334)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you explain to me what this value is for?
</blockquote></details>

That's for comment type.
If I can separate comment(database, table, column, ...) by unique id or something, I don't need them.

**Comment by knz** [comment]
ok let me know when you are ready for another review.

**Comment by hueypark** [comment]
@knz This PR's ready for the next review.

**Review by knz — COMMENTED** [review]
Wow your work is *very* good. At first sight I do not see anything significant any more. Very well done!

I have a question below. I will then look at smaller details later this week, and then this will be good to go. Thank you so much!

> Reviewed 34 of 34 files at r6, 18 of 18 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-:-LSlFpls88dvHf1zgjuP:b-liq0bf)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_tables.go, line 56 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSlFLpd1z-Rp7omvQvC:-LSlFLpe3Bt-oTLx0o6A:b8xoqnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/afd5aabbd3c445ab39c8c852c611120df9dc1c5f/pkg/sql/show_tables.go#L56)):*
> ```Go
> WHERE
> 	table_schema = %[2]s
> 	AND (t.state = %[3]s OR t.state IS NULL)
> ```

can you explain to me why you are filtering on the state here?

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_tables.go, line 56 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSlFLpd1z-Rp7omvQvC:-LSnsTbg0KUOqsFzB4iE:b4xp2dg) ([raw file](https://github.com/cockroachdb/cockroach/blob/afd5aabbd3c445ab39c8c852c611120df9dc1c5f/pkg/sql/show_tables.go#L56)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

can you explain to me why you are filtering on the state here?
</blockquote></details>

We need that filtering for crdb_internal.tables for validation.

If I do not check `PUBLIC` case, we got `DROP` state rows,
and if I do not check NULL case SHOW TABLES FROM crdb_internal will return 0 row.

**Review by knz — COMMENTED** [review]
Thank you again. I only have very few minor comments below.

For your information (if you contribute again) you can update the tests automatically when the output changes using `make logictest TESTFLAGS=-rewrite-results-in-testfiles`. For the logical plan tests there is also another flag `make test PKG=./pkg/sql/opt/... TESTFLAGS=-rewrite`. 

Finally, I have discussed this with other team members and we think that printing comments by default in the output of SHOW TABLE is confusing for users because so few tables will have comments in practice. So probably it will be better to make the printing of comments optional. We can proceed as follows, you can choose which way is most comfortable for you:

- we can move forward and merge your PR as-is. Then someone else in our team will change SHOW TABLES to make the printing of comments conditional. For example by supporting an alternate syntax `SHOW TABLES WITH COMMENTS ...`
- we can help you update the PR to make the comment printing conditional.

Let us know which way you think is best / most comfortable for you.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-:-LSyW3RuES7BfouefTyN:bykvu3x)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/comment_on_table.go, line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSyUFlL8kThZ7yP_0A-:-LSyUFlM6LCoYL-kzznc:b-k4invj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ecedf2ec3e0d1c3d43b1db3678646eea65fb00c/pkg/sql/comment_on_table.go#L39)):*
> ```Go
> 		return nil, err
> 	}
> 	if tableDesc == nil {
> ```

Since you have specified `requireTableDesc` above, tableDesc can never be `nil`. You can remove this case here.
___
*[pkg/sql/show_tables.go, line 56 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSlFLpd1z-Rp7omvQvC:-LSyPFYb6dryDLYKmUSH:be23eou) ([raw file](https://github.com/cockroachdb/cockroach/blob/afd5aabbd3c445ab39c8c852c611120df9dc1c5f/pkg/sql/show_tables.go#L56)):*
<details><summary><i>Previously, hueypark (Jaewan Park) wrote…</i></summary><blockquote>

We need that filtering for crdb_internal.tables for validation.

If I do not check `PUBLIC` case, we got `DROP` state rows,
and if I do not check NULL case SHOW TABLES FROM crdb_internal will return 0 row.
</blockquote></details>

Thank you for your explanation. 
Can you check again though? With LEFT JOIN the non-matching rows will not be eliminated. I have tried manually and I think the same results can be obtained without the check on `state`.
(The check would be necessary if you used an inner join. But outer joins work differently.)
___
*[pkg/sql/truncate.go, line 278 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSyV8H756vG4ULhYh49:-LSyV8H8EDMo45-e-AFp:bnvjlxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ecedf2ec3e0d1c3d43b1db3678646eea65fb00c/pkg/sql/truncate.go#L278)):*
> ```Go
> 	}
> 
> 	// Reassign comment.
> ```

Please group the comment update in a separate function and call it from here.

**Comment by hueypark** [comment]
@knz 
Let me know how can I make the comment printing conditional.

**Comment by knz** [comment]
First step is to extend the SHOW TABLES syntax with an optional "WITH COMMENT" clause. Here is how you can do this.

Here:

https://github.com/cockroachdb/cockroach/blob/91b11dae416f3d9b55fadd2a4b096e94d874176c/pkg/sql/sem/tree/show.go#L200-L202

add a `WithComment` boolean field

Then here: https://github.com/cockroachdb/cockroach/blob/91b11dae416f3d9b55fadd2a4b096e94d874176c/pkg/sql/sem/tree/show.go#L207

add `if xxx.WithComment { ctx.WriteString(" WITH COMMENT") }`

Then in this area:

https://github.com/cockroachdb/cockroach/blob/91b11dae416f3d9b55fadd2a4b096e94d874176c/pkg/sql/parser/sql.y#L3371-L3392

change things like `SHOW TABLES { $$.val = &tree.ShowTables{} }` to

`SHOW TABLES with_comment { $$.val = &tree.ShowTables{WithComment: $3.bool()} }`

Then below add:

```
with_comment:
  WITH COMMENT { $$.val = true }
| /* EMPTY */  { $$.val = false }
```

Then at the top here:

https://github.com/cockroachdb/cockroach/blob/91b11dae416f3d9b55fadd2a4b096e94d874176c/pkg/sql/parser/sql.y#L821

add `with_comment` to the line with `%type <bool>`

Then add a test for the new syntax here:

https://github.com/cockroachdb/cockroach/blob/91b11dae416f3d9b55fadd2a4b096e94d874176c/pkg/sql/parser/parse_test.go#L373

Once you have support for the syntax, you can change the code here:

https://github.com/hueypark/cockroach/blob/1ecedf2ec3e0d1c3d43b1db3678646eea65fb00c/pkg/sql/show_tables.go#L42

To add `if n.WithComment { ... } else { ... }`

Then you can revert the tests for SHOW TABLES like I indicated above (`TESTFLAGS=-rewrite-results-in-testfiles`)

Then you can add one new logic test for `SHOW TABLES WITH COMMENT`

Finally you can add a release note in the commit message to document the new feature.

Please let me know if you need more information.

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/comment_on_table.go, line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSyUFlL8kThZ7yP_0A-:-LT-gNKw0t6DCRS8k1Xe:btewzi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ecedf2ec3e0d1c3d43b1db3678646eea65fb00c/pkg/sql/comment_on_table.go#L39)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Since you have specified `requireTableDesc` above, tableDesc can never be `nil`. You can remove this case here.
</blockquote></details>

Ok, I will remove the unnecessary check.
___
*[pkg/sql/show_tables.go, line 56 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSlFLpd1z-Rp7omvQvC:-LT2aTj85wJk7RcnqD-q:bydf1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/afd5aabbd3c445ab39c8c852c611120df9dc1c5f/pkg/sql/show_tables.go#L56)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Thank you for your explanation. 
Can you check again though? With LEFT JOIN the non-matching rows will not be eliminated. I have tried manually and I think the same results can be obtained without the check on `state`.
(The check would be necessary if you used an inner join. But outer joins work differently.)

</blockquote></details>

I still think we need that check. Examples follow,

Before the start we need preparation.

```sql
CREATE TABLE foo (a INT);
TRUNCATE foo;
```

1. If I do not check PUBLIC case, we got DROP state rows,

```sql
SELECT
	i.table_name, c.comment
FROM
	huey.information_schema.tables AS i
	LEFT JOIN crdb_internal.tables AS t
	ON
		i.table_name = t.name
		AND i.table_catalog = t.database_name
	LEFT JOIN system.comments AS c
	ON t.table_id = c.object_id
WHERE
	table_schema = 'public'
	AND (t.state = 'PUBLIC' OR t.state IS NULL)
	AND (t.database_name = 'huey' OR t.database_name IS NULL)
ORDER BY
	table_schema, table_name;
---
table_name comment
foo NULL
```

If I remove 'PUBLIC' state check,

```sql
SELECT
	i.table_name, c.comment
FROM
	huey.information_schema.tables AS i
	LEFT JOIN crdb_internal.tables AS t
	ON
		i.table_name = t.name
		AND i.table_catalog = t.database_name
	LEFT JOIN system.comments AS c
	ON t.table_id = c.object_id
WHERE
	table_schema = 'public'
	--AND (t.state = 'PUBLIC' OR t.state IS NULL)
	AND (t.database_name = 'huey' OR t.database_name IS NULL)
ORDER BY
	table_schema, table_name;
---
table_name comment
foo NULL
foo NULL
```

2. and if I do not check NULL case SHOW TABLES FROM crdb_internal will return 0 row.

```sql
SELECT
	i.table_name, c.comment
FROM
	huey.information_schema.tables AS i
	LEFT JOIN crdb_internal.tables AS t
	ON
		i.table_name = t.name
		AND i.table_catalog = t.database_name
	LEFT JOIN system.comments AS c
	ON t.table_id = c.object_id
WHERE
	table_schema = 'crdb_internal'
	AND (t.state = 'PUBLIC' OR t.state IS NULL)
	AND (t.database_name = 'huey' OR t.database_name IS NULL)
ORDER BY
	table_schema, table_name;
---
many rows...
```

If I remove NULL state check,

```sql
SELECT
	i.table_name, c.comment
FROM
	huey.information_schema.tables AS i
	LEFT JOIN crdb_internal.tables AS t
	ON
		i.table_name = t.name
		AND i.table_catalog = t.database_name
	LEFT JOIN system.comments AS c
	ON t.table_id = c.object_id
WHERE
	table_schema = 'crdb_internal'
	AND (t.state = 'PUBLIC')-- OR t.state IS NULL)
	AND (t.database_name = 'huey' OR t.database_name IS NULL)
ORDER BY
	table_schema, table_name;
---
no row
```
___
*[pkg/sql/truncate.go, line 278 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSyV8H756vG4ULhYh49:-LT2aO5X7vmjCnzFqt86:b-6pr1vu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ecedf2ec3e0d1c3d43b1db3678646eea65fb00c/pkg/sql/truncate.go#L278)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please group the comment update in a separate function and call it from here.
</blockquote></details>

Ok, I will follow your advice.

**Review by hueypark — COMMENTED** [review]
Thanks! I will do that soon.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-:-LT2cxnG2TdC6-kQpblS:b-8zb857)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
Thank you for making the extra step!

There is just one simplification needed and then this will be good to go.

I also kindly request that you squash all the commits into one before we merge. The various release notes must appear under each other in the (single) commit message.

Thank you again

> Reviewed 1 of 2 files at r8, 15 of 25 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-:-LT93F09CVZXfrO0C7QS:b6dplrs)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/import_stmt_test.go, line 457 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LT91qcX5_TfShddv5Cf:-LT91qcX5_TfShddv5Cg:b-u1a9i4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f235c857e8253af109b7d405fc9ac4c2a225aaa/pkg/ccl/importccl/import_stmt_test.go#L457)):*
> ```Go
> 			data: testPgdumpFk,
> 			query: map[string][][]string{
> 				`SHOW TABLES WITH COMMENT`: {{"cities", "NULL"}, {"weather", "NULL"}},
> ```

I think in this test it is better to remove `with comment` and come back to the original code.
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 13 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LT92Gwg4luccCX4IHfT:-LT92Gwg4luccCX4IHfU:bq6wrgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f235c857e8253af109b7d405fc9ac4c2a225aaa/pkg/sql/logictest/testdata/logic_test/crdb_internal#L13)):*
> ```
> 
> query TT
> SHOW TABLES FROM crdb_internal WITH COMMENT
> ```

please remove `with comment` here and revert the test to the original code.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 809 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LT92KGz4A0sCZF0mKtz:-LT92KGz4A0sCZF0mKu-:bxk1zk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f235c857e8253af109b7d405fc9ac4c2a225aaa/pkg/sql/logictest/testdata/logic_test/fk#L809)):*
> ```
> # refers is not visible because it is in the ADD state.
> query TT
> SHOW TABLES FROM test WITH COMMENT
> ```

ditto here and all the other logic test files.
___
*[pkg/sql/logictest/testdata/logic_test/show_source, line 142 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LT936l22KtgNdM3zXOH:-LT936l22KtgNdM3zXOI:b73hq0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f235c857e8253af109b7d405fc9ac4c2a225aaa/pkg/sql/logictest/testdata/logic_test/show_source#L142)):*
> ```
> 
> query TT colnames
> SELECT * FROM [SHOW TABLES FROM system WITH COMMENT]
> ```

This is the only test file where you are going to keep WITH COMMENT.

However, it should test both variants: one test with "WITH COMMENT", and one test without.

**Review by knz — COMMENTED** [review]
You can also rebase your branch on top of `master` to resolve the conflicts.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-:-LT944naBJaR1SYKBti_:b-wb73t2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/show_source, line 142 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LT936l22KtgNdM3zXOH:-LT9eZph0rGtv7Jahljh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f235c857e8253af109b7d405fc9ac4c2a225aaa/pkg/sql/logictest/testdata/logic_test/show_source#L142)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is the only test file where you are going to keep WITH COMMENT.

However, it should test both variants: one test with "WITH COMMENT", and one test without.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 457 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LT91qcX5_TfShddv5Cf:-LT9bX4s4FXeZBnX3h76:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f235c857e8253af109b7d405fc9ac4c2a225aaa/pkg/ccl/importccl/import_stmt_test.go#L457)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think in this test it is better to remove `with comment` and come back to the original code.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal, line 13 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LT92Gwg4luccCX4IHfT:-LT9c7S58LzAUFOKQV9V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f235c857e8253af109b7d405fc9ac4c2a225aaa/pkg/sql/logictest/testdata/logic_test/crdb_internal#L13)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please remove `with comment` here and revert the test to the original code.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 809 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LT92KGz4A0sCZF0mKtz:-LT9cJJe38jr9LdXuS2S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f235c857e8253af109b7d405fc9ac4c2a225aaa/pkg/sql/logictest/testdata/logic_test/fk#L809)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto here and all the other logic test files.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: - thank you so much for your contribution.

> Reviewed 28 of 28 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-:-LTJFbxU0Ad5wiJ97EI6:bqq4fxs)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/show_tables.go, line 56 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32442#-LSlFLpd1z-Rp7omvQvC:-LTJCuT576tIJIdD4hq-:b-o0i8ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/afd5aabbd3c445ab39c8c852c611120df9dc1c5f/pkg/sql/show_tables.go#L56)):*
<details><summary><i>Previously, hueypark (Jaewan Park) wrote…</i></summary><blockquote>

I still think we need that check. Examples follow,

Before the start we need preparation.

```sql
CREATE TABLE foo (a INT);
TRUNCATE foo;
```

1. If I do not check PUBLIC case, we got DROP state rows,

```sql
SELECT
	i.table_name, c.comment
FROM
	huey.information_schema.tables AS i
	LEFT JOIN crdb_internal.tables AS t
	ON
		i.table_name = t.name
		AND i.table_catalog = t.database_name
	LEFT JOIN system.comments AS c
	ON t.table_id = c.object_id
WHERE
	table_schema = 'public'
	AND (t.state = 'PUBLIC' OR t.state IS NULL)
	AND (t.database_name = 'huey' OR t.database_name IS NULL)
ORDER BY
	table_schema, table_name;
---
table_name comment
foo NULL
```

If I remove 'PUBLIC' state check,

```sql
SELECT
	i.table_name, c.comment
FROM
	huey.information_schema.tables AS i
	LEFT JOIN crdb_internal.tables AS t
	ON
		i.table_name = t.name
		AND i.table_catalog = t.database_name
	LEFT JOIN system.comments AS c
	ON t.table_id = c.object_id
WHERE
	table_schema = 'public'
	--AND (t.state = 'PUBLIC' OR t.state IS NULL)
	AND (t.database_name = 'huey' OR t.database_name IS NULL)
ORDER BY
	table_schema, table_name;
---
table_name comment
foo NULL
foo NULL
```

2. and if I do not check NULL case SHOW TABLES FROM crdb_internal will return 0 row.

```sql
SELECT
	i.table_name, c.comment
FROM
	huey.information_schema.tables AS i
	LEFT JOIN crdb_internal.tables AS t
	ON
		i.table_name = t.name
		AND i.table_catalog = t.database_name
	LEFT JOIN system.comments AS c
	ON t.table_id = c.object_id
WHERE
	table_schema = 'crdb_internal'
	AND (t.state = 'PUBLIC' OR t.state IS NULL)
	AND (t.database_name = 'huey' OR t.database_name IS NULL)
ORDER BY
	table_schema, table_name;
---
many rows...
```

If I remove NULL state check,

```sql
SELECT
	i.table_name, c.comment
FROM
	huey.information_schema.tables AS i
	LEFT JOIN crdb_internal.tables AS t
	ON
		i.table_name = t.name
		AND i.table_catalog = t.database_name
	LEFT JOIN system.comments AS c
	ON t.table_id = c.object_id
WHERE
	table_schema = 'crdb_internal'
	AND (t.state = 'PUBLIC')-- OR t.state IS NULL)
	AND (t.database_name = 'huey' OR t.database_name IS NULL)
ORDER BY
	table_schema, table_name;
---
no row
```


</blockquote></details>

Yes I see it now. Thank you.

**Comment by knz** [comment]
@bdarnell I have decided to keep the comment output of `SHOW TABLES` optional in the first iteration because it is rather disruptive to a lot of tests, and we have made 3rd party tools (dbeaver) very unhappy recently by changing the schema.

I suggest we postpone the change "make comment visible always"  until later in the cycle when we enter the QA process of verifying compatibility.

**Pull request merged**
