### PR TITLE
tracing: make `span` a union type

### PR DESCRIPTION
**Pull request by tbg**
Clarify that a `span` is anywhere between zero to three subspans:

- net/trace,
- external opentracing Tracer, and
- crdb-internal trace span,

where zero subspans corresponds to what is today noopSpan (not
implemented yet, but TODO added).

Lots of threads to pull, but this is a good checkpoint since
everything compiles and the diff is mechanical and small enough
to actually review.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> where zero subspans corresponds to what is today noopSpan (not
> implemented yet, but TODO added).

Let's pull on this this and remove the `noopSpan` type. Otherwise I'm fairly confused about what the possible types of spans are.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-:-MIfHxA4C9ExUYIyU-nk:b25203s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/util/tracing/tracer_span.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MIfDjmCAd-2cDAUgGQl:-MIfDjmDCPGGVArHPtT0:b64ojag) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab8aeabef4624957e219ba3303d1dbac2d12a49/pkg/util/tracing/tracer_span.go#L163)):*
> ```Go
> 
> type otSpan struct {
> 	// TODO(tbg): see if we can lose the shadowTr here and rely on shadowSpan.Tracer().
> ```

I think so...
___
*[pkg/util/tracing/tracer_span.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MIfFWlJBN-XBMtthQOd:-MIfFWlJBN-XBMtthQOe:bol36yp) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab8aeabef4624957e219ba3303d1dbac2d12a49/pkg/util/tracing/tracer_span.go#L171)):*
> ```Go
> 
> type span struct {
> 	crdbSpan // can be zero
> ```

Can it really be zero? Doesn't it need to have at least a tracer in it? I'm thinking it should have a tracer in it so that users just need a span in order to create other spans, not a span and a tracer. I guess in that world the `noopSpan` would become a per-tracer instance.
If it does always have a tracer in it, should we hang our `*Tracer` from `span` instead of from `crdbSpan`? The `crdbSpan` could really be zero.
___
*[pkg/util/tracing/tracer_span.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MIfDzGX7u0pbyGx8tvn:-MIfDzGX7u0pbyGx8tvo:b26fsdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab8aeabef4624957e219ba3303d1dbac2d12a49/pkg/util/tracing/tracer_span.go#L182)):*
> ```Go
> 
> func (s *span) isBlackHole() bool {
> 	return !s.crdbSpan.isRecording() && s.netTr == nil && s.otSpan == (otSpan{})
> ```

why aren't we testing `crdbSpan == span{}` ? Or in fact `span{}`
___
*[pkg/util/tracing/tracer_span.go, line 683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MIfEQku-4YVSQFxQv0L:-MIfEQku-4YVSQFxQv0M:b2u4bid) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab8aeabef4624957e219ba3303d1dbac2d12a49/pkg/util/tracing/tracer_span.go#L683)):*
> ```Go
> // tracing-related work that would be discarded anyway.
> func IsBlackHoleSpan(s opentracing.Span) bool {
> 	// There are two types of black holes: instances of noopSpan and, when tracing
> ```

what's the plan here? `noopSpan` goes away?

**Review by tbg — COMMENTED** [review]
Added a commit that removes noopSpan. I'll do more clean-ups but in another PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-:-MJ71O8HB1t24hTVXIzj:b6jg7sk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/util/tracing/tracer_span.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MIfDjmCAd-2cDAUgGQl:-MJ71T8MCAvcEYhTqwbs:b-v8eak5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab8aeabef4624957e219ba3303d1dbac2d12a49/pkg/util/tracing/tracer_span.go#L163)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think so...
</blockquote></details>

Will pull on this separately.
___
*[pkg/util/tracing/tracer_span.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MIfFWlJBN-XBMtthQOd:-MJ75Yqt7tIw5sTVsTrH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab8aeabef4624957e219ba3303d1dbac2d12a49/pkg/util/tracing/tracer_span.go#L171)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Can it really be zero? Doesn't it need to have at least a tracer in it? I'm thinking it should have a tracer in it so that users just need a span in order to create other spans, not a span and a tracer. I guess in that world the `noopSpan` would become a per-tracer instance.
If it does always have a tracer in it, should we hang our `*Tracer` from `span` instead of from `crdbSpan`? The `crdbSpan` could really be zero.
</blockquote></details>

Done.
___
*[pkg/util/tracing/tracer_span.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MIfDzGX7u0pbyGx8tvn:-MJ75dmK2k5e4ILWxk6B:b-lbut5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab8aeabef4624957e219ba3303d1dbac2d12a49/pkg/util/tracing/tracer_span.go#L182)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why aren't we testing `crdbSpan == span{}` ? Or in fact `span{}`
</blockquote></details>

What do you mean?
___
*[pkg/util/tracing/tracer_span.go, line 683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MIfEQku-4YVSQFxQv0L:-MJ76l-w1dyWGsw9Sjv5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab8aeabef4624957e219ba3303d1dbac2d12a49/pkg/util/tracing/tracer_span.go#L683)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's the plan here? `noopSpan` goes away?
</blockquote></details>

Done.

**Comment by tbg** [comment]
I need to fix up the "remove noop span" commit so that we're turning all operations on it into noops. Luckily the race detector caught this in CI.

**Comment by tbg** [comment]
I will probably add another commit that makes the noop span have a `nil` crdbSpan instead of a zero one. This makes sure any attempts to accidentally reach into a noopSpan will be NPEs.

**Review by knz — APPROVED** [review]
Yep that's clear. Thanks

**Review by knz — COMMENTED** [review]
LGTM up to and including r13, but I'd like Andrei to review the last commit r14.

> Reviewed 5 of 5 files at r1, 3 of 3 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, 4 of 4 files at r7, 26 of 26 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 5 of 5 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-:-MJQsEeKBkY13__kSE0q:bu32vlk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/util/tracing/tracer_span.go, line 703 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJQrRyN-Mm-CdUqVuYd:-MJQrRyN-Mm-CdUqVuYe:b4ho4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/dde499dbb19223296222b800bfcedae66457e069/pkg/util/tracing/tracer_span.go#L703)):*
> ```Go
> func (s *crdbSpan) ImportRemoteSpans(remoteSpans []tracingpb.RecordedSpan) error {
> 	if !s.isRecording() {
> 		return errors.New("adding Raw Spans to a span that isn't recording")
> ```

looks like this should be `errors.AssertionFailedf`

**Comment by tbg** [comment]
Friendly ping @andreimatei. I have more work to do here still but the pile only keeps growing.

**Review by andreimatei — APPROVED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-:-MJh0geB3WKu5rQ-WnHX:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/sql/distsql/server.go, line 208 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgulwH2v_sEHvDumpm:-MJgulwH2v_sEHvDumpn:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fac690360b32bc0ec50eb5c960fe70823c01496/pkg/sql/distsql/server.go#L208)):*
> ```Go
> 		//  If that field is unset, we might still want to create a child span if
> 		//  this flow is run synchronously.
> 		sp = ds.Tracer.(*tracing.Tracer).StartChildSpan(opName, parentSpan.(*tracing.Span).SpanContext(), logtags.FromContext(ctx), false /* separateRecording */)
> ```

long line
___
*[pkg/util/tracing/tracer.go, line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgmqhA3p4Op8vfe9pK:-MJgmqhA3p4Op8vfe9pL:bjjcert) ([raw file](https://github.com/cockroachdb/cockroach/blob/9745fc7c40570f956596122b5022fc0fd05f29d7/pkg/util/tracing/tracer.go#L92)):*
> ```Go
> // state.
> type Tracer struct {
> 	// Preallocated noopSpan, used to avoid creating spans when we are not using
> ```

comment is stale
___
*[pkg/util/tracing/tracer.go, line 248 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgzPGW2pw-YsceS6Xv:-MJgzPGW2pw-YsceS6Xw:bmug7j1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fac690360b32bc0ec50eb5c960fe70823c01496/pkg/util/tracing/tracer.go#L248)):*
> ```Go
> 		}
> 		parentType = r.Type
> 		// Note that the logic around here doesn't support spans with multiple
> ```

let's assert that it stays the case
___
*[pkg/util/tracing/tracer.go, line 340 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgwscl7PegWDHhCvrf:-MJgwscl7PegWDHhCvrg:b2a25sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fac690360b32bc0ec50eb5c960fe70823c01496/pkg/util/tracing/tracer.go#L340)):*
> ```Go
> 		parentContext.TraceID == 0 &&
> 		parentContext.recordingType == NoRecording &&
> 		!bool(recordable) {
> ```

I think `recordable == NonRecordableSpan` is much better - so that the constants can be flipped
___
*[pkg/util/tracing/tracer.go, line 369 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgxNRFDeKgDNzizeGq:-MJgxNRFDeKgDNzizeGr:b-3c3g62) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fac690360b32bc0ec50eb5c960fe70823c01496/pkg/util/tracing/tracer.go#L369)):*
> ```Go
> 	s.crdb.SpanID = uint64(rand.Int63())
> 
> 	// We use the shadowTr from the parent context over that of our
> ```

I'd rather not think about this case... How about checking `parentContext.shadowTr ==  t.getShadowTracer()` and, if they're not the same, not using either?
Besides requiring less thinking, it also seems the right thing to do from the perspective of the previous shadowTracer - if I've unlinked it, I want to stop using it as soon as possible.
And it's also better when transitioning from no shadowTracer to some shadowTracer - I probably don't want to have children with no parent in the newly-linked tracer.
___
*[pkg/util/tracing/tracer_span.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MIfDzGX7u0pbyGx8tvn:-MJh0I8Y8saeCbn7oJpI:b2ni8w0) ([raw file](https://github.com/cockroachdb/cockroach/blob/dab8aeabef4624957e219ba3303d1dbac2d12a49/pkg/util/tracing/tracer_span.go#L182)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

nvm
___
*[pkg/util/tracing/tracer_span.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgqGAy-uSryOSK74vl:-MJgqGAy-uSryOSK74vm:b78km5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9745fc7c40570f956596122b5022fc0fd05f29d7/pkg/util/tracing/tracer_span.go#L168)):*
> ```Go
> type otSpan struct {
> 	// TODO(tbg): see if we can lose the shadowTr here and rely on shadowSpan.Tracer().
> 	// Probably not - but worth checking.
> ```

why not?
___
*[pkg/util/tracing/tracer_span.go, line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgtD-pBbnfYb2fPtuN:-MJgtD-q6TSYH5-nTtlQ:b-km4oom) ([raw file](https://github.com/cockroachdb/cockroach/blob/9745fc7c40570f956596122b5022fc0fd05f29d7/pkg/util/tracing/tracer_span.go#L192)):*
> ```Go
> 	// Special case: trace id zero implies that everything else,
> 	// with the exception of the tracer, is also zero.
> 	return s.isBlackHole() && s.crdbSpan.TraceID == 0
> ```

pls comment `isNoop` and `isBlackhole` - in particular the difference between them
___
*[pkg/util/tracing/tracer_span.go, line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgtXesBPH-PGL6Jjqx:-MJgtXesBPH-PGL6Jjqy:bkcoqwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9745fc7c40570f956596122b5022fc0fd05f29d7/pkg/util/tracing/tracer_span.go#L192)):*
> ```Go
> 	// Special case: trace id zero implies that everything else,
> 	// with the exception of the tracer, is also zero.
> 	return s.isBlackHole() && s.crdbSpan.TraceID == 0
> ```

If we could do something else other than looking at `TraceID`, I think it'd be better. I hope we can get rid of `TraceID`; I don't think we do anything with it.
___
*[pkg/util/tracing/tracer_span.go, line 111 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgtzTkCe6pT1az8os9:-MJgtzTkCe6pT1az8osA:b-3rcbjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c708ef34e7ad56308e02f23336dee5878dca3993/pkg/util/tracing/tracer_span.go#L111)):*
> ```Go
> 	//
> 	// TODO(tbg): there's ChildSpanSeparateRecording which avoids sharing
> 	// the recording with the parent. I hope we can remove it.
> ```

I don't know if we can remove it... I'd strike this part of the comment or expand it.
I think the idea is that in DistSQL we want the recording of different parts of the trace (each processor) to be collected separately, and we don't want the parent's recording to also include them (right?). And the child recordings might be collected even after the parent's (?). 
___
*[pkg/util/tracing/tracer_span.go, line 795 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgvq-j9VdAyq4UlCzw:-MJgvq-j9VdAyq4UlCzx:b-8x9687) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fac690360b32bc0ec50eb5c960fe70823c01496/pkg/util/tracing/tracer_span.go#L795)):*
> ```Go
> }
> 
> // TODO(tbg): these are temporary to get things to compile without larger
> ```

ummm I don't really know what's going on here, but I'd rather do the mechanical refactors, or just make the types exported for now. There's so many types of spans going around that one more spelling difference can't help.

**Review by tbg — COMMENTED** [review]
TFTRs! I'll try to get this PR passing (a bunch of tests are highlighting what are likely bugs I introduced outside the tracing package's coverage) and follow up with more cleanups.

It looks like the main next step is to rid us of our internal use of the opentracing interfaces. I tried making some changes I considered worthwhile without getting into that, but there's always a blocker.

> Dismissed @andreimatei from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-:-MJlbEcl39CxsvmVNW7m:b-nkpflb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @irfansharif, @knz, and @TheSamHuang)

___
*[pkg/sql/distsql/server.go, line 208 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgulwH2v_sEHvDumpm:-MJktCyPDhWqimNTDJIX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fac690360b32bc0ec50eb5c960fe70823c01496/pkg/sql/distsql/server.go#L208)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[pkg/util/tracing/tracer.go, line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgmqhA3p4Op8vfe9pK:-MJkvWmd4gS83SScfK-z:b-yckype) ([raw file](https://github.com/cockroachdb/cockroach/blob/9745fc7c40570f956596122b5022fc0fd05f29d7/pkg/util/tracing/tracer.go#L92)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

comment is stale
</blockquote></details>

But it's... not? What would you change?
___
*[pkg/util/tracing/tracer.go, line 248 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgzPGW2pw-YsceS6Xv:-MJkvwhO0unRgaOpSdc3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fac690360b32bc0ec50eb5c960fe70823c01496/pkg/util/tracing/tracer.go#L248)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

let's assert that it stays the case
</blockquote></details>

Done.
___
*[pkg/util/tracing/tracer.go, line 340 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgwscl7PegWDHhCvrf:-MJkwzRv33JZ71iMI6zo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fac690360b32bc0ec50eb5c960fe70823c01496/pkg/util/tracing/tracer.go#L340)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think `recordable == NonRecordableSpan` is much better - so that the constants can be flipped
</blockquote></details>

Done.
___
*[pkg/util/tracing/tracer.go, line 369 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgxNRFDeKgDNzizeGq:-MJkzhZ0EklR4kvm1qmw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fac690360b32bc0ec50eb5c960fe70823c01496/pkg/util/tracing/tracer.go#L369)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd rather not think about this case... How about checking `parentContext.shadowTr ==  t.getShadowTracer()` and, if they're not the same, not using either?
Besides requiring less thinking, it also seems the right thing to do from the perspective of the previous shadowTracer - if I've unlinked it, I want to stop using it as soon as possible.
And it's also better when transitioning from no shadowTracer to some shadowTracer - I probably don't want to have children with no parent in the newly-linked tracer.
</blockquote></details>

Done.
___
*[pkg/util/tracing/tracer_span.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgqGAy-uSryOSK74vl:-MJlYB2O6G9g2CqPE2_C:buwr7oq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9745fc7c40570f956596122b5022fc0fd05f29d7/pkg/util/tracing/tracer_span.go#L168)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why not?
</blockquote></details>

Because `shadowSpan.Tracer()` gives you the `opentracing.Tracer`, but you need the surrounding `shadowTracer` that can give you the type.

There's probably still a way to get rid of this once more of this "shadow" business unravels, but right now, we have to keep this. This all ties in with spanContext as well so I will pull on that first..
___
*[pkg/util/tracing/tracer_span.go, line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgtD-pBbnfYb2fPtuN:-MJlYUGY5GiWUsFO81V1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9745fc7c40570f956596122b5022fc0fd05f29d7/pkg/util/tracing/tracer_span.go#L192)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment `isNoop` and `isBlackhole` - in particular the difference between them
</blockquote></details>

Done.
___
*[pkg/util/tracing/tracer_span.go, line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgtXesBPH-PGL6Jjqx:-MJlYVHX3hGWXoGA3BhP:bximjzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9745fc7c40570f956596122b5022fc0fd05f29d7/pkg/util/tracing/tracer_span.go#L192)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If we could do something else other than looking at `TraceID`, I think it'd be better. I hope we can get rid of `TraceID`; I don't think we do anything with it.
</blockquote></details>

One step at a time. I agree that TraceID isn't used in our case, but let me hold off on removing it until I am a bit better oriented.
___
*[pkg/util/tracing/tracer_span.go, line 703 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJQrRyN-Mm-CdUqVuYd:-MJlYzo_3rh-FcUsV2BH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dde499dbb19223296222b800bfcedae66457e069/pkg/util/tracing/tracer_span.go#L703)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

looks like this should be `errors.AssertionFailedf`
</blockquote></details>

Done.
___
*[pkg/util/tracing/tracer_span.go, line 111 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgtzTkCe6pT1az8os9:-MJkzl_L0baViwcBaaYC:btclph1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c708ef34e7ad56308e02f23336dee5878dca3993/pkg/util/tracing/tracer_span.go#L111)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't know if we can remove it... I'd strike this part of the comment or expand it.
I think the idea is that in DistSQL we want the recording of different parts of the trace (each processor) to be collected separately, and we don't want the parent's recording to also include them (right?). And the child recordings might be collected even after the parent's (?). 
</blockquote></details>

I think recordings should be tied to the span in which they occur and should not be shared with the parent, period (or if so, to grab the "transitive" recording from a parent is the non-normal case that requires a special option). This sharing business requires the user to keep track of who's a child of who to make sure the recordings all pan out. It's a pretty ugly contract.
___
*[pkg/util/tracing/tracer_span.go, line 795 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgvq-j9VdAyq4UlCzw:-MJlbBMRE1UF9wEl8Xyv:bysw9po) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fac690360b32bc0ec50eb5c960fe70823c01496/pkg/util/tracing/tracer_span.go#L795)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ummm I don't really know what's going on here, but I'd rather do the mechanical refactors, or just make the types exported for now. There's so many types of spans going around that one more spelling difference can't help.
</blockquote></details>

Done. V satisfying.

**Review by andreimatei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54737)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @irfansharif, @knz, @tbg, and @TheSamHuang)

___
*[pkg/util/tracing/tracer_span.go, line 111 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgtzTkCe6pT1az8os9:-MJmd10XD5QYV8sowgEx:br03jp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c708ef34e7ad56308e02f23336dee5878dca3993/pkg/util/tracing/tracer_span.go#L111)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think recordings should be tied to the span in which they occur and should not be shared with the parent, period (or if so, to grab the "transitive" recording from a parent is the non-normal case that requires a special option). This sharing business requires the user to keep track of who's a child of who to make sure the recordings all pan out. It's a pretty ugly contract.
</blockquote></details>

I don't think I agree with this. Tracing is all about recursion and connections between spans. If today I get some information from a span, and tomorrow I chunk of some of that span's work into a sub-span, I don't want to lose any information I was previously getting (au contraire, I wand to get **more** info).
This is not to say that I like this `ChildSeparateRecording` option - in fact I very much dislike it. It's an artifact of the way our trace collection works that doesn't work well with the opentracing concepts. I too hope we can get rid of it somehow - perhaps by never collecting the recording of the parent span that creates all the child DistSQL spans that end up being collected, or by clearing the children's recording when they get collected like I think you've suggested elsewhere.

As a matter of style, I would still remove the "I hope we can remove it." comment, or expand it. It's just troll bait as it stands.

**Review by knz — COMMENTED** [review]
I finished re-reviewing the PR after the rebase and then the additional commit.
No further comment other than what andrei already raised.

Tobias, a kind request to not rebase / amend this further until the end of the review and instead use fixup commits if necessary; otherwise the reviewable experience will become unbereable. At the end of the review whene verything is approved you can then autosquash the fixup commits if you made any.

> Reviewed 29 of 29 files at r15, 3 of 3 files at r16, 2 of 2 files at r17, 1 of 1 files at r18, 4 of 4 files at r19, 4 of 4 files at r20, 26 of 26 files at r21, 2 of 2 files at r22, 1 of 1 files at r23, 1 of 1 files at r24, 1 of 1 files at r25, 1 of 1 files at r26, 5 of 5 files at r27, 1 of 1 files at r28, 1 of 1 files at r29, 1 of 1 files at r30, 1 of 1 files at r31, 8 of 8 files at r32, 2 of 2 files at r33, 2 of 2 files at r34.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-:-MJmhqTH7NsNapWYCPqz:b-h42b32)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @irfansharif, @knz, @tbg, and @TheSamHuang)

**Review by tbg — COMMENTED** [review]
Good point Raphael, thanks for the suggestion. No major changes in these last fixups, just greening CI.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-:-MKDrQR58nIyfl0F3TM5:bxzgd5n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @irfansharif, @knz, and @TheSamHuang)

___
*[pkg/util/tracing/tracer_span.go, line 111 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/54737#-MJgtzTkCe6pT1az8os9:-MKDrFME8FDY-bHdSGqv:b1oxfly) ([raw file](https://github.com/cockroachdb/cockroach/blob/c708ef34e7ad56308e02f23336dee5878dca3993/pkg/util/tracing/tracer_span.go#L111)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think I agree with this. Tracing is all about recursion and connections between spans. If today I get some information from a span, and tomorrow I chunk of some of that span's work into a sub-span, I don't want to lose any information I was previously getting (au contraire, I wand to get **more** info).
This is not to say that I like this `ChildSeparateRecording` option - in fact I very much dislike it. It's an artifact of the way our trace collection works that doesn't work well with the opentracing concepts. I too hope we can get rid of it somehow - perhaps by never collecting the recording of the parent span that creates all the child DistSQL spans that end up being collected, or by clearing the children's recording when they get collected like I think you've suggested elsewhere.

As a matter of style, I would still remove the "I hope we can remove it." comment, or expand it. It's just troll bait as it stands.
</blockquote></details>

Done. We'll continue to discuss recordings outside of this PR.

**Comment by tbg** [comment]
Choo choo goes the merge train. Thanks folks!
bors r=knz,andreimatei

**Pull request merged**
