### PR TITLE
sql: disambiguate float,decimal formatting

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, the FmtParsable directive wouldn't produce a parsable
representation for some floats and decimals, in the context of other
expressions. In particular, negative floats and decimals would format
like `-10.0:::FLOAT`. This seems fine, but since the `:::` operator
binds more closely than the `-` operator, an expression like
`(-10.0:::FLOAT)::STRING` would get formatted to
`-10.0:::FLOAT::STRING`, which is of course invalid as there's no unary
negative operator for the string datatype.

Now, floats and decimals are marked as unambiguously formatted datatypes
and take care of disambiguating themselves with a type annotation if
necessary, as well as further-disambiguating parentheses if the numbers
are nuegative.

Release note (bug fix): correct the round-trip formatting of negative
floats and decimals in the context of other expressions when executing
in a distributed flow.

### CODE REVIEW

**Comment by knz** [comment]
can you double check the failing logic tests and fix the handling of NaN, then I'll have another look

**Comment by jordanlewis** [comment]
Done, PTAL.

**Comment by knz** [comment]
Please add a new series of tests dedicated to your new format flag in format_test.go, with infinities and nans too.

LGTM otherwise
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jordanlewis** [comment]
Done. TFTR!

**Pull request merged**
