### PR TITLE
opt: Support check constraints

### PR DESCRIPTION
**Pull request by andy-kimball**
Check constraints are user-defined expressions that restrict the values
in each row of a table. For example:

  CREATE TABLE abc (a INT CHECK (a > 0))

If a row is inserted or updated, this check constraint ensures that the
value of column "a" will always be positive.

This commit adds support for check constraints to the cost-based optimizer
by appending boolean columns to the input expression of each mutation
operator, one for each check constraint defined on the table. The SQL
execution operators will then check these columns at runtime; if any
value is false, it will report a constraint violation error.

Incorporating check constraints into the input expression allows the
constraint expressions to be globally optimized. For example, if an
INSERT expression inserts constant values, then a check constraint
might be validated statically, at compile-time.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 8 of 8 files at r2, 22 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34118)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @dt, @RaduBerinde, @rytaft, and @vivekmenezes)

___
*[pkg/sql/opt/ops/statement.opt, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXAizNBiScHwTo1QyG:-LWXAizO1UBSihQUKB5f:briinl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/ops/statement.opt#L92)):*
> ```
>     UpdateCols ColList
> 
>     # CheckCols are columns from the Input expression that contain boolean values
> ```

I think it's a little confusing what these columns are, are they columns whose value are the check expressions themselves?
___
*[pkg/sql/opt/ops/statement.opt, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXAsXG06-3gQEWIOZp:-LWXAsXG06-3gQEWIOZq:b1qdo8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/ops/statement.opt#L104)):*
> ```
>     #
>     # Since the check constraint for column "a" can be statically proved to be
>     # true, CheckCols would contain [0, id-b].
> ```

what does `id-b` mean?
___
*[pkg/sql/opt/optbuilder/insert.go, line 532 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXAyQjC5_U2LDhkvMC:-LWXAyQjC5_U2LDhkvMD:bf55elz) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/optbuilder/insert.go#L532)):*
> ```Go
> 
> // buildInsert constructs an Insert operator, possibly wrapped by a Project
> // operators that corresponds to the given RETURNING clause.
> ```

`s/by a Project operators/by Project operators/`?
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXBjuW6AIvDr_JBkeb:-LWXBjuW6AIvDr_JBkec:b-iwe7yx) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/optbuilder/mutation_builder.go#L84)):*
> ```Go
> 	// boolean results of evaluating check constraint expressions defined on the
> 	// target table. Its length is always equal to the number of check constraints
> 	// on the table (see opt.Table.CheckCount), assuming there is at least one.
> ```

Even if there aren't any, right? Since `nil` is technically an empty list.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1259 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXCxKY3IWeT-5Kd-pH:-LWXCxKY3IWeT-5Kd-pI:bnhdyde) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/optbuilder/testdata/insert#L1259)):*
> ```
>  │    ├──  column1:4 => a:1
>  │    ├──  column2:5 => b:2
>  │    └──  column3:6 => c:3
> ```

Can you add the check columns to this output?
___
*[pkg/sql/sqlbase/check.go, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXKVRcC_WoRsqEX1zN:-LWXKVRcC_WoRsqEX1zO:b-3mhoiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/sqlbase/check.go#L46)):*
> ```Go
> // evaluation.
> //
> // In the Input mode, calles should call NewInputCheckHelper to initialize a new
> ```

nit: `callers`
___
*[pkg/sql/sqlbase/check.go, line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXLoJ2D504rjaKyZqz:-LWXLoJ2D504rjaKyZr-:b-nk2a5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/sqlbase/check.go#L136)):*
> ```Go
> 		return len(c.Exprs)
> 	}
> 	return c.checkSet.Len()
> ```

Is there any chance that we'll reuse a render and the number of check columns will be fewer than the number of `check` expressions defined? Could that cause problems?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-:-LWagQ6k7bLHP2ChvxCr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @dt, @rytaft, and @vivekmenezes)

___
*[pkg/sql/opt/optbuilder/testdata/insert, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWaewQYDUPLGsVScG_6:-LWaewQYDUPLGsVScG_7:bshc7we) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/optbuilder/testdata/insert#L73)):*
> ```
> )
> ----
> TABLE checks
> ```

We should probably print out the check expressions here
___
*[pkg/sql/row/fk.go, line 164 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWagwLC6YmbTwE2DfhL:-LWagwLC6YmbTwE2DfhM:bfzza99) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/row/fk.go#L164)):*
> ```Go
> }
> 
> // TablesNeededForFKs populates a map of TableLookupsByID for all the
> ```

Should we generalize this function name since it's not only about FKs?
___
*[pkg/sql/row/fk.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWagrXN5j_1Jb6K5KzE:-LWagrXN5j_1Jb6K5KzF:bkhndz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/row/fk.go#L168)):*
> ```Go
> // and/or insert operations. It uses the passed in lookup function to perform
> // the actual lookup. The AnalyzeExpr function, if provided, is used to
> // initialize the CheckHelper, and this requires that the TableLookupFunction
> ```

This comment needs updating (this function no longer initializes the CheckHelper).
___
*[pkg/sql/sqlbase/check.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWagWq95dvLHXD4lYwX:-LWagWq95dvLHXD4lYwY:b97kvsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/sqlbase/check.go#L29)):*
> ```Go
> 
> // CheckHelper validates check constraints on rows, on INSERT and UPDATE.
> // CheckHelper has two different modes for executing check constraints:
> ```

Nice description!

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 8 of 8 files at r2, 22 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-:-LWqO82g3xyTgVA0jF5L:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball, @dt, and @vivekmenezes)

___
*[pkg/sql/logictest/testdata/planner_test/upsert, line 167 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWqMA01CkNCog2ow0ib:-LWqMA01CkNCog2ow0ic:b-z5sxuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/logictest/testdata/planner_test/upsert#L167)):*
> ```
> # The CBO behaves differently than the HP and PG in this case. It only checks
> # constraints if an insert or update actually occurs. In this case, the DO
> # NOTHING clause skips the update, so there is no need to check the constraint.
> ```

[nit] This comment is a bit confusing since this is the planner test. I was scratching my head for a bit...
___
*[pkg/sql/opt/ops/statement.opt, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWqHANXD_TkN9HTYkPq:-LWqHANY9wJSOyfzUzY2:bp1fb9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/ops/statement.opt#L103)):*
> ```
>     #   UPDATE abc SET a=1, b=b+1
>     #
>     # Since the check constraint for column "a" can be statically proved to be
> ```

[nit] proved -> proven
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 382 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWqIN8nBO4FbyeM0AeE:-LWqIN8nBO4FbyeM0AeF:bdwt9o6) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/optbuilder/mutation_builder.go#L382)):*
> ```Go
> 
> 			alias := fmt.Sprintf("check%d", i+1)
> 			texpr := mb.outScope.resolveType(expr, types.Bool)
> ```

Should this be `resolveAndRequireType`?
___
*[pkg/sql/sqlbase/check.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWqNLKOAE3QDAi6VfV-:-LWqNLKOAE3QDAi6VfV0:b-wf8zug) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/sqlbase/check.go#L207)):*
> ```Go
> }
> 
> // CheckInput expects checkEvals to already contain the boolean result of
> ```

checkEvals -> checkVals?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34118)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dt, @justinj, @RaduBerinde, @rytaft, and @vivekmenezes)

___
*[pkg/sql/logictest/testdata/planner_test/upsert, line 167 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWqMA01CkNCog2ow0ib:-LWqQY64EvNJTKn_g9bj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/logictest/testdata/planner_test/upsert#L167)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] This comment is a bit confusing since this is the planner test. I was scratching my head for a bit...
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/statement.opt, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXAizNBiScHwTo1QyG:-LWqJQzJ9GfPMorVLvqv:b-3uhaer) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/ops/statement.opt#L92)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think it's a little confusing what these columns are, are they columns whose value are the check expressions themselves?
</blockquote></details>

Yes. I rewrote the comment a bit to hopefully make it more clear.
___
*[pkg/sql/opt/ops/statement.opt, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWqHANXD_TkN9HTYkPq:-LWqQaC-4TbNkn7_sIgj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/ops/statement.opt#L103)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] proved -> proven
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/statement.opt, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXAsXG06-3gQEWIOZp:-LWqJxM2CZIpZQ5MOqla:b-3nalbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/ops/statement.opt#L104)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

what does `id-b` mean?
</blockquote></details>

The id of the "b" column. I changed it to be `b_colid`.
___
*[pkg/sql/opt/optbuilder/insert.go, line 532 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXAyQjC5_U2LDhkvMC:-LWqK7vZDAn5cd7W8Bcd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/optbuilder/insert.go#L532)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

`s/by a Project operators/by Project operators/`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXBjuW6AIvDr_JBkeb:-LWqKhSS6K1XMoDQxl3U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/optbuilder/mutation_builder.go#L84)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Even if there aren't any, right? Since `nil` is technically an empty list.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 382 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWqIN8nBO4FbyeM0AeE:-LWqQqg1-cXAlSC6LCxI:bc7yzkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/optbuilder/mutation_builder.go#L382)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should this be `resolveAndRequireType`?
</blockquote></details>

It's checked when the table schema is built, but doesn't hurt to do it here as well.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWaewQYDUPLGsVScG_6:-LWqQBPXADkL71841km5:b-ho5wpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/optbuilder/testdata/insert#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should probably print out the check expressions here
</blockquote></details>

Agreed. Done.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1259 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXCxKY3IWeT-5Kd-pH:-LWqR5Zb3B7_kf9U3mjv:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/99aa4e374807d9be3f904bb51d51273d7a957044/pkg/sql/opt/optbuilder/testdata/insert#L1259)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Can you add the check columns to this output?
</blockquote></details>

Good idea. Done.
___
*[pkg/sql/sqlbase/check.go, line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWXLoJ2D504rjaKyZqz:-LWqW2RK3ACFj7qhyf2F:b-ddt0gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/sqlbase/check.go#L136)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Is there any chance that we'll reuse a render and the number of check columns will be fewer than the number of `check` expressions defined? Could that cause problems?
</blockquote></details>

In `relational_builder.go`, I make a separate column for each check constraint, so that should not be possible.
___
*[pkg/sql/sqlbase/check.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWqNLKOAE3QDAi6VfV-:-LWqWOID2pnowee6ZRlF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/sqlbase/check.go#L207)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

checkEvals -> checkVals?
</blockquote></details>

Done.
___
*[pkg/sql/row/fk.go, line 164 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWagwLC6YmbTwE2DfhL:-LWqUFn1CPiFV1VkoXhR:b-pixqus) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/row/fk.go#L164)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should we generalize this function name since it's not only about FKs?
</blockquote></details>

Someone refactored this entire file. But I don't want to change names right now, since my hope is that all of this will eventually be changed more fundamentally once we incorporate FK's into the optimizer.
___
*[pkg/sql/row/fk.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWagrXN5j_1Jb6K5KzE:-LWqVmov0WjhvGxBpMY_:b-woo5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/91ac82a1ebe70968062f27f9cb2ece738514568d/pkg/sql/row/fk.go#L168)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This comment needs updating (this function no longer initializes the CheckHelper).
</blockquote></details>

Done (in a new file now).

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 31 files at r4, 11 of 11 files at r5, 23 of 23 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-:-LWqoNJJ5BSJPXfFHB-z:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @dt, @justinj, @RaduBerinde, and @vivekmenezes)

___
*[pkg/sql/row/fk_existence_prepare.go, line 28 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWqnxai7UPD3Z3zGDUY:-LWqnxajBbrR0COQhQsb:b-l67tmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc6697bf0160839dcbe0e2917f9121a1641b8a7/pkg/sql/row/fk_existence_prepare.go#L28)):*
> ```Go
> // the actual lookup. The caller is expected to create the CheckHelper for the
> // given mutatedTable. However, if cascading is required, then the FK code will
> // need to create additional CheckHelpers. It does this using the AnalyzeExpr
> ```

[nit] for consistency, I'd make this `AnalyzeExprFunction,`

**Review by rytaft — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-:-LWqoamE7LCuvHy127Zx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @dt, @justinj, @RaduBerinde, and @vivekmenezes)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34118)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dt, @justinj, @RaduBerinde, @rytaft, and @vivekmenezes)

___
*[pkg/sql/row/fk_existence_prepare.go, line 28 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34118#-LWqnxai7UPD3Z3zGDUY:-LWrn-ms5Yp3R1CzNu2_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc6697bf0160839dcbe0e2917f9121a1641b8a7/pkg/sql/row/fk_existence_prepare.go#L28)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] for consistency, I'd make this `AnalyzeExprFunction,`
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34118)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dt, @justinj, @RaduBerinde, and @vivekmenezes)

**Pull request merged**
