### PR TITLE
kv/rangefeed: reduce size of event struct from 200 bytes to 72 bytes

### PR DESCRIPTION
**Pull request by nvb**
This commit restructures the event struct and reduces its size from 200 bytes to 72 bytes. This is accomplished primarily by pushing large, infrequently used struct fields into pointers. This is mostly just a drive-by cleanup found while working on #77724.

Release justification: None. Don't merge yet.

Release note: None.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Nice, thanks!

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88308#-:-NCUfZnp8JA67TGtE4eM:b-wdj8zi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88308#-NCUeiDwBRpoRKYMqq83:-NCUeiDwBRpoRKYMqq84:b-pkmz92) ([raw file](https://github.com/cockroachdb/cockroach/blob/385a6052cfafb70461759d3a5b70b448f6fb4885/pkg/kv/kvserver/rangefeed/processor.go#L164)):*
> ```Go
> 
> type ctEvent struct {
> 	hlc.Timestamp
> ```

nit: why not `type ctEvent hlc.Timestamp`?
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88308#-NCUeVHc6w9oxBlzaY5h:-NCUeVHc6w9oxBlzaY5i:b-iyn9y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/385a6052cfafb70461759d3a5b70b448f6fb4885/pkg/kv/kvserver/rangefeed/processor.go#L177)):*
> ```Go
> type syncEvent struct {
> 	c chan struct{}
> 	// This setting is used in conjunction with syncC in tests in order to ensure
> ```

nit: update to refer to `c` rather than `syncC`.

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88308#-:-NCWSXSM7Kd3qQqvHwCG:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88308#-NCUeiDwBRpoRKYMqq83:-NCWRsJf8-YdKd684x2E:bjhaylm) ([raw file](https://github.com/cockroachdb/cockroach/blob/385a6052cfafb70461759d3a5b70b448f6fb4885/pkg/kv/kvserver/rangefeed/processor.go#L164)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: why not `type ctEvent hlc.Timestamp`?
</blockquote></details>

That's what I had initially, but `type ctEvent hlc.Timestamp` does not inherit methods while embedding the timestamp does, so this made some code less verbose.

For instance, this allows:
```go
	case !e.ct.IsEmpty():
		p.forwardClosedTS(ctx, e.ct.Timestamp)
```
instead of:
```go
	case !hlc.Timestamp(e.ct).IsEmpty():
		p.forwardClosedTS(ctx, hlc.Timestamp(e.ct))
```
Happy to change it if you feel strongly though.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88308#-NCUeVHc6w9oxBlzaY5h:-NCWSKrgD8DwkHq-HdFe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/385a6052cfafb70461759d3a5b70b448f6fb4885/pkg/kv/kvserver/rangefeed/processor.go#L177)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: update to refer to `c` rather than `syncC`.
</blockquote></details>

Done.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88308)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88308#-NCUeiDwBRpoRKYMqq83:-NCWT4879zB4FG_FGyox:b-fh3m7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/385a6052cfafb70461759d3a5b70b448f6fb4885/pkg/kv/kvserver/rangefeed/processor.go#L164)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That's what I had initially, but `type ctEvent hlc.Timestamp` does not inherit methods while embedding the timestamp does, so this made some code less verbose.

For instance, this allows:
```go
	case !e.ct.IsEmpty():
		p.forwardClosedTS(ctx, e.ct.Timestamp)
```
instead of:
```go
	case !hlc.Timestamp(e.ct).IsEmpty():
		p.forwardClosedTS(ctx, hlc.Timestamp(e.ct))
```
Happy to change it if you feel strongly though.
</blockquote></details>

Not at all, this is fine.

**Pull request merged**
