### PR TITLE
colfetcher,row: decode only needed columns when tracing is enabled

### LINKED ISSUE #73745: sql: kv tracing crashes on not null virtual computed columns
**To Reproduce**
```sql
create table t (
x int primary key,
y int not null,
z int not null as ((y*2)) virtual
);

insert into t values (1,2),(3,4),(5,6);

\set auto_trace=on,kv;

select * from t; --uh oh
```
you'd get an error like 
```
non-nullable column "t:z" with no value! Index scanned was "t_pkey" with the index key columns (x) and the values (1)
```

**Expected behavior**
We probably need to ignore virtual columns in `cFetcher.fillNulls()` method

### PR DESCRIPTION
**Pull request by yuzefovich**
**colfetcher: minor optimization when decoding the value part**

Release note: None

**colfetcher: fix recent bug of using wrong column with tracing in some cases**

A couple of months ago when we taught the cFetcher to operate only on
needed columns, we refactored the meaning of `ColIdxMap` - now it
returns for the given ColumnID the ordinal of the column among all
needed columns whereas previously it would return the ordinal among all
columns in the table. In tracing we were relying on the old behavior to
append the column name to the key part, and we mistakenly used the
"needed" ordinal when accesing the "whole table" columns. This is now
fixed. I noticed it while working on the next commit.

Release note: None

**colfetcher,row: decode only needed columns when tracing is enabled**

In a recent change we made it so that the cFetcher would treat all
columns present in the index as "needed" when the KV tracing is enabled.
This led to some bugs (like reading of a virtual column that doesn't
exist in the index) but is also not very meaningful since the goal of
the tracing is to show what the cFetcher is doing without tracing. This
commit starts treating the KV tracing as the request to log all needed
operations without doing anything extra (like decoding unnecessary
columns).

A similar change is applied to the `row.Fetcher` as well.

Fixes: #73745.

Release note (sql change): The KV tracing of SQL queries (that could be
obtained with `\set auto_trace=on,kv`) has been adjusted slightly.
Previously, we would fully decode the key part of each key-value pair
even if some part of the key would not be decoded when tracing is
enabled. Now, we won't perform any extra decoding, and parts of the key
that aren't decoded are replaced with `?`.

**colfetcher: find needed columns upfront**

Previously, the two users of the `cFetcher` (`ColBatchScan` and
`ColIndexJoin`) had different ways of figuring out which columns are
actually needed to be fetched (that information is needed to not decode
parts of the KV pairs unnecessarily). In one case we explicitly
propagated the information through the spec, and in another we did some
pre-processing to find the information.

This overall was more complicated than necessary (because we had complex
code path for pruning "unaccessible" columns from the secondary index
while keeping track of the ordinal mapping) as well as suboptimal (in
some cases `TableReaderSpec.NeededColumns` contained ordinals of the
columns that weren't actually needed by the post-processing stage), so
this commit unifies both ways into one addressing both of these
shortcomings.

Now, in order to find the set of needed columns, we examine the
post-processing spec all the time, but we do it in an efficient manner:
- we make sure to deserialize render expressions early
- we use a `tree.Visitor` rather than a heavy-weight `ExprHelper`.

As a result, we can remove `TableReaderSpec.NeededColumns` field as well
as not decode some columns in a handful of cases.

Release note: None

**sql: log undecoded values as <undecoded> in tracing**

Previously, if the value part of a key-value pair wasn't needed, we
would log it as `NULL`. However, that can be confusing whether an actual
`NULL` value was decoded or not. This commit replaces the undecoded
values with `<undecoded>` reducing the confusion (given that the
likelihood of the value actually being equal to `<undecoded>` is
negligible).

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-:-Mrbg5w6BUyFiIKDnBZB:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-Mrbcj9t6QAQmuctIpz8):*
nit: "doing in without" => "doing without"
___
*[-- commits, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-Mrbcr0S4vMVEIYNDuH7):*
I'm not sure if any users rely on tracing details like this, but it might be worth mentioning in a release note for our internal team members incase they notice the change in behavior while debugging and are confused by it.
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MrbeZqbCSdEHG1UmLXs:-MrbeZqbCSdEHG1UmLXt:b6isyp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/387d847f6880aa3c7d6098c92e5b0bb4f23ad937/pkg/sql/colfetcher/cfetcher_setup.go#L183)):*
> ```Go
> // post is updated accordingly to refer to new ordinals of columns. The method
> // also populates tableArgs.ColIdxMap.
> func keepOnlyNeededColumns(
> ```

It seems like now were doing a lot of unnecessary work in `populateTableArgs` to first populate a bunch of columns regardless of whether or not they are needed and pruning them in the case of a secondary index fetch, and then further pruning them here in `keepOnlyNeededColumns`.

Could we not remove `keepOnlyNeededColumns` entirely and do something like the psuedo-code below in `populateTableArgs`, getting rid of the special code for secondary indexes and system columns:

```
for _, col := range table.AllColumns() {
  if neededColumns.Contains(col) {
    cols = append(cols, col)
  }
}
```

**Review by yuzefovich — COMMENTED** [review]
I think I addressed all test failures, but there are a couple of questions that I want to answer first before merging this:

1. there is a regression in usability of tracing in some cases, in particular in `regional_by_row_query_behavior` file where we no longer show the region in the key part of the fetched KV. The query uses `SELECT *`, so I'm guessing that the optimizer is smart to know that the region column is not needed to be decoded because it was encoded in a span constraint, or something like that? Is this an acceptable regression? I can't immediately think of a simple workaround here.
2. there is a confusion between actual `NULL` value and a value that didn't have to be decoded (which we show as `NULL`). I think this problem existed before, so it might be not a big deal. Some improvements I have in mind is showing the value part that didn't have to be decoded as `?` as well as not showing the value part at all when reading of a secondary index with no stored columns. Thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-:-Mredx68DIj6b2ebqegQ:b-4bof3w)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MrbeZqbCSdEHG1UmLXs:-MrebxxD-eF4x1SLS8R4:b-6miget) ([raw file](https://github.com/cockroachdb/cockroach/blob/387d847f6880aa3c7d6098c92e5b0bb4f23ad937/pkg/sql/colfetcher/cfetcher_setup.go#L183)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It seems like now were doing a lot of unnecessary work in `populateTableArgs` to first populate a bunch of columns regardless of whether or not they are needed and pruning them in the case of a secondary index fetch, and then further pruning them here in `keepOnlyNeededColumns`.

Could we not remove `keepOnlyNeededColumns` entirely and do something like the psuedo-code below in `populateTableArgs`, getting rid of the special code for secondary indexes and system columns:

```
for _, col := range table.AllColumns() {
  if neededColumns.Contains(col) {
    cols = append(cols, col)
  }
}
```
</blockquote></details>

You're right that in the case when `cFetcher` is used by the `ColBatchScan` (i.e. simple table reader) we could simplify this logic. This is easy to do because we know the set of needed columns since it's included in `TableReaderSpec`. However, for the index join (which also uses `cFetcher`) we don't know the needed columns up front, and in some cases we have to know the `types.T` schema of available columns in order to calculate that needed columns set: https://github.com/cockroachdb/cockroach/blob/8c1528fff5c132b971428bc7f18bf0ea5eb16799/pkg/sql/colfetcher/index_join.go#L441

That was the reason for why I broke this process down into two steps.

If the optimizer can propagate the set of needed columns for the index joins, then we could simplify things, but that would be a separate change.

**Comment by RaduBerinde** [comment]
Does the row fetcher also decode unnecessary columns when tracing? If so we should fix that too for consistency

**Review by yuzefovich — COMMENTED** [review]
> Does the row fetcher also decode unnecessary columns when tracing? If so we should fix that too for consistency

Thanks for the nudge here. In the row fetcher with tracing we now decode exactly the same things as without tracing (after some minor changes in the third commit).

There are some differences between the vectorized and row-by-row fetchers where in the former only the necessary parts of the key are decoded whereas in the latter the whole key is decoded if at least one part of the key is needed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-:-MryJ-5H2v-ZaOD6Gr1P:b-dh3ngb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MrbeZqbCSdEHG1UmLXs:-MryHTJoAAs-ZbphL-GE:b-nthrfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/387d847f6880aa3c7d6098c92e5b0bb4f23ad937/pkg/sql/colfetcher/cfetcher_setup.go#L183)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

You're right that in the case when `cFetcher` is used by the `ColBatchScan` (i.e. simple table reader) we could simplify this logic. This is easy to do because we know the set of needed columns since it's included in `TableReaderSpec`. However, for the index join (which also uses `cFetcher`) we don't know the needed columns up front, and in some cases we have to know the `types.T` schema of available columns in order to calculate that needed columns set: https://github.com/cockroachdb/cockroach/blob/8c1528fff5c132b971428bc7f18bf0ea5eb16799/pkg/sql/colfetcher/index_join.go#L441

That was the reason for why I broke this process down into two steps.

If the optimizer can propagate the set of needed columns for the index joins, then we could simplify things, but that would be a separate change.
</blockquote></details>

Radu's nudge to look closer in the row-by-row fetcher made me realize that the cFetcher might be decoding more things than necessary in some cases, so I ended up refactoring the way we figure out the set of needed columns, and eventually the code looks similar to what you were suggesting. PTAL.

**Review by yuzefovich — COMMENTED** [review]
Fixed a silly mistake, RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-:-MryZQ5uDuL6sAQn5wID:b-1x009i)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rharding6373)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rharding6373, and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 149 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MsDZPHqCXikgvlvpJUL:-MsDZPHqCXikgvlvpJUM:b-7gujfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/12d337794751e3c191f8756979c878e7deeff10c/pkg/sql/execinfrapb/processors_sql.proto#L149)):*
> ```protobuf
>   optional bool has_system_columns = 14 [(gogoproto.nullable) = false];
> 
>   reserved 15;
> ```

This requires a DistSQL version bump, no? (alternatively, we could still populate it until the cluster has the right version)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @rharding6373)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 149 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MsDZPHqCXikgvlvpJUL:-MsXUAsG9PN4PmDmZb6S:b-xd4xl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/12d337794751e3c191f8756979c878e7deeff10c/pkg/sql/execinfrapb/processors_sql.proto#L149)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This requires a DistSQL version bump, no? (alternatively, we could still populate it until the cluster has the right version)
</blockquote></details>

Yes, that's a good catch, fixed. Note that this wasn't strictly necessary because we've already had some bumps of the distsql version in 22.1 cycle and haven't released any binaries yet, still it's better to be explicit.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Had a minor nit and a clarification question. Probably best to wait for another lgtm from someone who's been following along.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-:-MsaI1RM2s85TB8qy95w:b-kzetms)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, @rharding6373, and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 1570 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MsaCLSy7oToZIHvAgAf:-MsaCLSy7oToZIHvAgAg:bc5arx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d270b46dd6f03a2f05024ad47c7a141391e5d93/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L1570)):*
> ```
>           spans: [/'foo' COLLATE en_US - /'foo' COLLATE en_US]
> 
> # Regression test for the cFetcher trying to fetch virtual computed columns from
> ```

nit: Include what the expectation for the test is, e.g. `Regression test for #73745. The cFetcher should not fetch virtual computed columns from a primary index.`
___
*[pkg/sql/opt/exec/execbuilder/testdata/window, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MsaB8RTCKexb3h7f6Vu:-MsaB8RTCKexb3h7f6Vv:blqph2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d270b46dd6f03a2f05024ad47c7a141391e5d93/pkg/sql/opt/exec/execbuilder/testdata/window#L34)):*
> ```
>  ORDER BY message LIKE 'fetched:%' DESC, ordinality ASC
> ----
> fetched: /kv/kv_pkey/1/v -> /2
> ```

Could you explain how the tracing changes affected the results to this test? Why are some of the keys shorter (e.g., /v/w/f/b to /v)? Are the `NULL`s due to the confusion between actual `NULL`s and non-decoded values? I don't understand why some keys in the trace had values before but now have `NULL`...

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @rharding6373)

___
*[pkg/sql/opt/exec/execbuilder/testdata/window, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MsaB8RTCKexb3h7f6Vu:-MsaS6pc0pr2cikhJapK:b4mjfsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d270b46dd6f03a2f05024ad47c7a141391e5d93/pkg/sql/opt/exec/execbuilder/testdata/window#L34)):*
Some keys have gotten shorter because we no longer decode the full key but only the needed part from it. Note that decoding the whole key was introduced recently in 8e40f1ce9ccc5e5b9aa00c48f5369ab50bfae156.

> Are the `NULL`s due to the confusion between actual `NULL`s and non-decoded values? I don't understand why some keys in the trace had values before but now have `NULL`...

Yes, this is the case. This is one of the questions that I want to get answered before merging this (https://github.com/cockroachdb/cockroach/pull/74236#pullrequestreview-839728826).

For example,
```
fetched: /kv/kv_pkey/1/s -> 'a'
```
is transformed into
```
fetched: /kv/kv_pkey/1 -> NULL
```
because `s` column is not needed, so we don't write the name of the column into the key part and keep the value part undecoded, so we log it as `NULL`.

**Review by mgartner — APPROVED** [review]
Nice! :lgtm: 

> Reviewed 10 of 10 files at r2, 1 of 1 files at r3, 9 of 13 files at r4, 19 of 19 files at r7, 18 of 18 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-:-MspKovW7Kzz-8bDtXnz:bfd61qr)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, @rharding6373, and @yuzefovich)

___
*[pkg/sql/colfetcher/cfetcher.go, line 1206 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MspERFi3jTGtl4y6xRF:-MspERFi3jTGtl4y6xRG:bsvism9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c41b14e86445779a266a24d4bdc6dffab8d393f4/pkg/sql/colfetcher/cfetcher.go#L1206)):*
> ```Go
> 	if idx, ok := table.ColIdxMap.Get(colID); ok {
> 		if rf.traceKV {
> 			prettyKey = fmt.Sprintf("%s/%s", prettyKey, table.cols[idx].GetName())
> ```

nit: update the description of `ColIdxMap` to be more clear:

https://github.com/cockroachdb/cockroach/blob/3dad24ea3497c13789043b78c20309774fe218a7/pkg/sql/colfetcher/cfetcher_setup.go#L32-L33

Something like: "ColIdxMap is a mapping from ColumnID to the ordinal of the corresponding column within the cols field. Only needed columns are present".
___
*[pkg/sql/colfetcher/cfetcher.go, line 1044 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MspFdUW23hLQQUlY5sF:-MspFdUW23hLQQUlY5sG:bf5ov4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/de68601a71ed86ed0400f35f6ff210e738825f14/pkg/sql/colfetcher/cfetcher.go#L1044)):*
> ```Go
> // specified by colOrdinals. -1 in colOrdinals indicates that a column wasn't
> // actually decoded (this is represented as "?" in the result). separator is
> // inserted between each two consequent decoded column values (but not before
> ```

super nit: "consequent" => "subsequent"
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 82 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MspHfna1dfIKkGxaTEC:-MspHfna1dfIKkGxaTED:b-1byrd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f55231807b4a1f2a46842aec7f4f42894b3e526/pkg/sql/colfetcher/cfetcher_setup.go#L82)):*
> ```Go
> // - neededColumns is a set containing the ordinals of all columns that need to
> // be fetched. These ordinals are based on the schema of the whole table rather
> // than only among the needed columns.
> ```

nit: Not sure you need the "rather than only among the needed columns". If it were the set of ordinals in needed columns, it would simply be the set of all ordinals in `[0, n)` where `n` is the number of needed columns, right?
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 139 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MspIFht7HxPRGVKTlFF:-MspIFht7HxPRGVKTlFG:bxk78bv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f55231807b4a1f2a46842aec7f4f42894b3e526/pkg/sql/colfetcher/cfetcher_setup.go#L139)):*
> ```Go
> 	if neededColumns.Len() != len(cols) {
> 		idxMap := make([]int, len(cols))
> 		neededColIdx := 0
> ```

nit: `keepColIdx` might make it more clear that this variable is related to `cols` not `neededColumns`.
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 185 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MspJc8M8u5U2PftidFY:-MspJc8M8u5U2PftidFZ:bew2n5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f55231807b4a1f2a46842aec7f4f42894b3e526/pkg/sql/colfetcher/cfetcher_setup.go#L185)):*
> ```Go
> 		for _, expr := range post.RenderExprs {
> 			ivarSeen = colexecutils.MaybeAllocateBoolArray(ivarSeen, numColumns)
> 			ivars := findIVarsInRange(expr.LocalExpr, 0 /* start */, numColumns, ivarSeen)
> ```

Why do we need to pass a `start` and `end` here? In what cases would the expression contain indexed vars outside of this range?
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 191 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MspIwr79qvRspGLeqHt:-MspIwr79qvRspGLeqHu:bf5ov4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f55231807b4a1f2a46842aec7f4f42894b3e526/pkg/sql/colfetcher/cfetcher_setup.go#L191)):*
> ```Go
> 			if neededColumns.Len() == numColumns {
> 				// All columns are needed, so we can stop processing the
> 				// consequent render expressions.
> ```

super nit: "consequent" => "subsequent"
___
*[pkg/sql/opt/exec/execbuilder/testdata/window, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MsaB8RTCKexb3h7f6Vu:-MspGwdMDDvibZRGfts6:b-hlymhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d270b46dd6f03a2f05024ad47c7a141391e5d93/pkg/sql/opt/exec/execbuilder/testdata/window#L34)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Some keys have gotten shorter because we no longer decode the full key but only the needed part from it. Note that decoding the whole key was introduced recently in 8e40f1ce9ccc5e5b9aa00c48f5369ab50bfae156.

> Are the `NULL`s due to the confusion between actual `NULL`s and non-decoded values? I don't understand why some keys in the trace had values before but now have `NULL`...

Yes, this is the case. This is one of the questions that I want to get answered before merging this (https://github.com/cockroachdb/cockroach/pull/74236#pullrequestreview-839728826).

For example,
```
fetched: /kv/kv_pkey/1/s -> 'a'
```
is transformed into
```
fetched: /kv/kv_pkey/1 -> NULL
```
because `s` column is not needed, so we don't write the name of the column into the key part and keep the value part undecoded, so we log it as `NULL`.
</blockquote></details>

I think this is mostly fine. One minor improvement would be to log undecoded values as `<undecoded>` or `?` instead of `NULL`.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-:-MspobUI-Qst2NLrwgYs:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @RaduBerinde, and @rharding6373)

___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 82 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MspHfna1dfIKkGxaTEC:-MspjxO0AXGpY4Qb5IiS:bs2vhuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f55231807b4a1f2a46842aec7f4f42894b3e526/pkg/sql/colfetcher/cfetcher_setup.go#L82)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Not sure you need the "rather than only among the needed columns". If it were the set of ordinals in needed columns, it would simply be the set of all ordinals in `[0, n)` where `n` is the number of needed columns, right?
</blockquote></details>

Good point, removed.
___
*[pkg/sql/colfetcher/cfetcher_setup.go, line 185 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MspJc8M8u5U2PftidFY:-MsplJi96p2Ot8sCCUYg:b-2rq6xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f55231807b4a1f2a46842aec7f4f42894b3e526/pkg/sql/colfetcher/cfetcher_setup.go#L185)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why do we need to pass a `start` and `end` here? In what cases would the expression contain indexed vars outside of this range?
</blockquote></details>

This was a remnant of the past when `findIVarsInRange` was introduced. You're right that we don't need this, and I refactored the code to get rid off this method altogether.
___
*[pkg/sql/opt/exec/execbuilder/testdata/window, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MsaB8RTCKexb3h7f6Vu:-MspodJM7fwqVhVJRnlU:b-4djtpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d270b46dd6f03a2f05024ad47c7a141391e5d93/pkg/sql/opt/exec/execbuilder/testdata/window#L34)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think this is mostly fine. One minor improvement would be to log undecoded values as `<undecoded>` or `?` instead of `NULL`.
</blockquote></details>

I like the suggestion with `<undecoded>`, so I implemented that in a separate commit.

**Review by mgartner — APPROVED** [review]
> Reviewed 28 of 28 files at r9, 13 of 13 files at r10, 18 of 18 files at r11, 12 of 12 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rharding6373)

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-:-Msq25PP72rika-rEKeh:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/window, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74236#-MsaB8RTCKexb3h7f6Vu:-Msq2-4P-MsNRRvsKNdf:bpbn86k) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d270b46dd6f03a2f05024ad47c7a141391e5d93/pkg/sql/opt/exec/execbuilder/testdata/window#L34)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I like the suggestion with `<undecoded>`, so I implemented that in a separate commit.
</blockquote></details>

The `<undecoded>` is nice.

**Comment by yuzefovich** [comment]
Fixed up a couple of places I originally forgot to update based on the `<undecoded>` change, CI should be green now.

bors r+

**Pull request merged**
