### PR TITLE
Use Query for explain. Fixes #4052

### LINKED ISSUE #4052: explain (debug) in sql console returns OK and no output rows
This used to work, is it the intended behavior?

```
root@:15432> select * from spam;
+----+----------+
| ID |   text   |
+----+----------+
|  1 | "tobias" |
|  2 | "jaja"   |
+----+----------+
root@:15432> explain (debug) select * from spam;
OK
```

### PR DESCRIPTION
**Pull request by mberhault**
anything else I'm missing?

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4054)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM. Maybe add a test case while you're at it.

**Comment by mberhault** [comment]
explain is a little odd to test since we can change it at any time. @petermattis, how annoying would a output example be for `EXPLAIN`? is it likely to change much?

**Comment by petermattis** [comment]
@mberhault There are plenty of examples in the `sql/testdata` directory which examine the output of both `EXPLAIN` and `EXPLAIN (DEBUG)`. I think another test case here is well worth it. If the output of `EXPLAIN` changes the test will break and we'll fix it.

**Comment by mberhault** [comment]
updated `cli_test.go:Example_sql` to use `SHOW` and `EXPLAIN`.

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/sql_util.go, line 33 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4054#-K9SinHA5LMK0g7XZfQo:-K9SinHBcp_B7VMfKrtQ:-554648270) ([raw file](https://github.com/cockroachdb/cockroach/blob/71904d6328c6bee054be11251d5f89d2ec99d544/cli/sql_util.go#L33)):*
Why aren't we always using `DB.Query`? There is probably a reason, but I just looked in the code for a comment and didn't find one.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4054)*

**Comment by mberhault** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/sql_util.go, line 33 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4054#-K9SinHA5LMK0g7XZfQo:-K9SlSChhN9J4I2b3No9:479703325) ([raw file](https://github.com/cockroachdb/cockroach/blob/71904d6328c6bee054be11251d5f89d2ec99d544/cli/sql_util.go#L33)):*
when I moved over to the `pq` driver, issuing a query on a statement would crash the client. I can check again.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4054)*

**Comment by mberhault** [comment]
The cli_test examples definitely work, and my poking at the sql shell also works. I don't remember exactly what was broken, I could have sworn it was in the `pq` driver.

**Comment by petermattis** [comment]
LGTM

**Pull request merged**
