### PR TITLE
partialidx: reduce remaining filters of semantically equivalent expressions

### PR DESCRIPTION
**Pull request by mgartner**
#### partialidx: reduce remaining filters of semantically equivalent expressions

This commit reduces the remaining filters returned from the Implicator
in cases where expressions in the filter are semantically equivalent to
expression in the predicate, but not syntactically equivalent.

For example:

    (a::INT > 17)
    =>
    (a::INT >= 18)

Prior to this commit, `(a > 17)` would remain as a filter to be applied
after a partial index scan. However, this filter is unnecessary, because
there are no integers between `17` and `18`. With this change,
`(a > 17)` is removed from the remaining filters.

Release justification: Low risk update to new functionality, partial
indexes.

Release note (performance improvement): The optimizer reduces filters
applied after partial index scans in more cases where the filters are
implicitly applied by the partial index predicate. This could lead to
more efficient query plans in some cases.

#### partialidx: add safer set operations for tracking exact matches

This commit adds a typed set for tracking filter expressions that are
exact matches of predicate expressions. This will help prevent a common
developer mistake of not checking whether or not the set it `nil` before
manipulating it, such as the bug fixed by #53222.

Benchmarks show performance improvements of the Implicator for some
cases as a result of this change.

    name                                               old time/op  new time/op  delta
    Implicator/single-exact-match-16                   81.2ns ± 1%  77.8ns ± 1%  -4.24%  (p=0.008 n=5+5)
    Implicator/single-inexact-match-16                  916ns ± 1%   914ns ± 0%    ~     (p=0.254 n=5+5)
    Implicator/range-inexact-match-16                  2.40µs ± 0%  2.46µs ± 1%  +2.56%  (p=0.008 n=5+5)
    Implicator/single-exact-match-extra-filters-16      313ns ± 0%   305ns ± 1%  -2.74%  (p=0.008 n=5+5)
    Implicator/single-inexact-match-extra-filters-16   3.85µs ± 1%  3.85µs ± 1%    ~     (p=0.952 n=5+5)
    Implicator/multi-column-and-exact-match-16         90.0ns ± 1%  84.3ns ± 1%  -6.29%  (p=0.008 n=5+5)
    Implicator/multi-column-and-inexact-match-16       1.99µs ± 0%  2.02µs ± 1%  +1.53%  (p=0.016 n=4+5)
    Implicator/multi-column-or-exact-match-16          82.3ns ± 3%  78.1ns ± 1%  -5.10%  (p=0.008 n=5+5)
    Implicator/multi-column-or-exact-match-reverse-16  1.72µs ± 1%  1.74µs ± 2%    ~     (p=0.397 n=5+5)
    Implicator/multi-column-or-inexact-match-16        2.23µs ± 2%  2.31µs ± 3%  +3.74%  (p=0.008 n=5+5)
    Implicator/and-filters-do-not-imply-pred-16        3.61µs ± 1%  3.63µs ± 4%    ~     (p=0.548 n=5+5)
    Implicator/or-filters-do-not-imply-pred-16          916ns ± 2%   905ns ± 2%    ~     (p=0.095 n=5+5)
    Implicator/many-columns-exact-match10-16            305ns ± 1%   278ns ± 1%  -8.97%  (p=0.008 n=5+5)
    Implicator/many-columns-inexact-match10-16         12.9µs ± 1%  12.9µs ± 1%    ~     (p=0.841 n=5+5)
    Implicator/many-columns-exact-match100-16          21.3µs ± 1%  19.2µs ± 2%  -9.94%  (p=0.008 n=5+5)
    Implicator/many-columns-inexact-match100-16         502µs ± 1%   503µs ± 1%    ~     (p=0.421 n=5+5)

Release justification: Low risk update to new functionality, partial
indexes.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53507#-:-MFgl9t8CQtjHDnl9fvq:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/partialidx/implicator.go, line 459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53507#-MFgiv1oDjEVz5zgiWar:-MFgiv1pA1qFs18tfjFg:b3cu0fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d3cdab45b68212214ae97772548cbf286228b1/pkg/sql/opt/partialidx/implicator.go#L459)):*
> ```Go
> 
> // atomImpliesAtom returns true if the predicate atom expression, pred, contains
> // atom expression a, meaning that all values for variables in which e evaluates
> ```

atom expression a -> atom expression e
___
*[pkg/sql/opt/partialidx/implicator.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53507#-MFgjgDB7cpuBh_G4O55:-MFgjgDB7cpuBh_G4O56:b-ym3qvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d3cdab45b68212214ae97772548cbf286228b1/pkg/sql/opt/partialidx/implicator.go#L465)):*
> ```Go
> // if one expression contains another, handling many types of expressions
> // including comparison operators, IN operators, and tuples.
> func (im *Implicator) atomImpliesAtom(
> ```

[nit] add an explanation about what the `exactMatches` parameter is
___
*[pkg/sql/opt/partialidx/implicator.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53507#-MFgkGVm9zIV-DrcLQHb:-MFgkGVm9zIV-DrcLQHc:b-qf30u2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6788ca0de33d678c1b89b039e3f03dc4e3fa8e3/pkg/sql/opt/partialidx/implicator.go#L179)):*
> ```Go
> 	// If no exact match was found, recursively check the sub-expressions of the
> 	// filters and predicate. Use exactMatches to keep track of expressions in
> 	// filters that exactly matches expressions in pred, so that the can be
> ```

exactly matches -> exactly match
so that the -> so that they

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53507)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/partialidx/implicator.go, line 459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53507#-MFgiv1oDjEVz5zgiWar:-MFgrAoe7iaoYyn0VexK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d3cdab45b68212214ae97772548cbf286228b1/pkg/sql/opt/partialidx/implicator.go#L459)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

atom expression a -> atom expression e
</blockquote></details>

Done.
___
*[pkg/sql/opt/partialidx/implicator.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53507#-MFgjgDB7cpuBh_G4O55:-MFgrMsn29Oqryjvcrzb:b-87ds5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d3cdab45b68212214ae97772548cbf286228b1/pkg/sql/opt/partialidx/implicator.go#L465)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] add an explanation about what the `exactMatches` parameter is
</blockquote></details>

`exactMatches` is an argument in a handful of these functions, and it's already explained in the docs for the Implicator struct. If I add an explanation here, I'd want to add one to every function that has the argument, and that feels redundant.
___
*[pkg/sql/opt/partialidx/implicator.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53507#-MFgkGVm9zIV-DrcLQHb:-MFgr7GhBUeGerUDv_Qc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6788ca0de33d678c1b89b039e3f03dc4e3fa8e3/pkg/sql/opt/partialidx/implicator.go#L179)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

exactly matches -> exactly match
so that the -> so that they
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
Signing off on the change as long as you get the final LGTM

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53507#-:-MFh96x1EAFv8-qKUY0r:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/partialidx/implicator.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53507#-MFgjgDB7cpuBh_G4O55:-MFh8zer5igNN-PvcjB3:b2ni9b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d3cdab45b68212214ae97772548cbf286228b1/pkg/sql/opt/partialidx/implicator.go#L465)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`exactMatches` is an argument in a handful of these functions, and it's already explained in the docs for the Implicator struct. If I add an explanation here, I'd want to add one to every function that has the argument, and that feels redundant.
</blockquote></details>

ok!

**Comment by mgartner** [comment]
TFTR!

bors r=rytaft

**Pull request merged**
