### PR TITLE
log: add a channel for SQL errors

### PR DESCRIPTION
**Pull request by otan**
Release note (ops change, cli change): Added a SQL_ERRORS logging
channel that logs errors encountered from SQL statements.

### CODE REVIEW

**Comment by knz** [comment]
Why a separate logging channel instead of relying on the regular SQL statement log and filtering on errors in the log collector? What is the linked jira epic and user story?

**Comment by otan** [comment]
> relying on the regular SQL statement log and filtering on errors in the log collector?

can you say more about how this works? i've made this based on a few instances where we are debugging third party tools and having a hard time reconciling queries being run on the database and any erorrs that may occur (third party tools can be opaque with these errors). I only know of the `vmodule=conn_executor=2` way of remediating this at the moment, but if there's already a better way i'm happy to close this.

> What is the linked jira epic and user story?

i don't exactly have one, but i can get you one if you wish.

**Comment by knz** [comment]
> can you say more about how this works? i've made this based on a few instances where we are debugging third party tools and having a hard time reconciling queries being run on the database and any erorrs that may occur (third party tools can be opaque with these errors). 

1. Enable sql query logging with cluster setting `sql.trace.log_statement_execute`. This produces all statements **and their errors** to logging channel SQL_EXEC with a structured payload
2. configure a sink for that channel to go wherever you want (files or fluent or http)
3. in that location, add filtering to only collect the queries that have failed with an error. For each error result, there's a separate JSON field for SQLSTATE and the error message.

**Comment by knz** [comment]
>>  What is the linked jira epic and user story?

> i don't exactly have one, but i can get you one if you wish.

I'm not the one who wishes this. As per february all changes that are user-facing should be linked to an issue (or a jira epic) so that the doc writer has context (use case, user journey) to work with.

**Comment by otan** [comment]
> Enable sql query logging with cluster setting sql.trace.log_statement_execute. This produces all statements and their errors to logging channel SQL_EXEC with a structured payload

Ah, it would appear it fails to catch two scenarios parse errors (important for us to debug unimpl syntax) and COPY.

> I'm not the one who wishes this. As per february all changes that are user-facing should be linked to an issue (or a jira epic) so that the doc writer has context (use case, user journey) to work with.

Missed that memo. Cheers.

**Comment by knz** [comment]
> it would appear it fails to catch two scenarios parse errors (important for us to debug unimpl syntax) and COPY.

That's a legitimate ask. Why not enhance the existing logging facility to add those cases, so that all log mechanisms we already have  start to handle these cases?

**Pull request closed without merging**
