### PR TITLE
logictest: add distsql configs to mutation tests

### PR DESCRIPTION
**Pull request by jordanlewis**
And disable some tests that are failing due to #28716.

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
LGTM after you remove the 5node-dist config (we talked offline and determined it was not necessary)

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28717#-:-LKRow28ETr1-N6NXL5V:b-t6m4ro)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by arjunravinarayan** [comment]
LGTM :shipit:

**Comment by knz** [comment]
please consider a backport

**Pull request merged**
