### PR TITLE
mixedversion: introduce `upgradePlan` data structure and plan stages

### PR DESCRIPTION
**Pull request by renatolabs**
This organizes steps specific to each upgrade in a plan in its own struct, `upgradePlan`. It makes easier for us, in the future, reason about the test's behaviour based on each upgrade that is happening.

In addition, we also introduce `Stage` as a context field. The upgrade stage indicates the phase in the upgrade process a step is situated in (e.g., during the first binary upgrade, during a rollback, while upgrade migrations are running, etc).

These changes set the stage for a future internal API to change test plans based on existing steps and the context in which they run.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
### Context: mixedversion test mutators

This PR is part of a larger effort to introduce the concept of plan _mutators_ to the mixedversion framework. For initial discussion, see [internal thread](https://cockroachlabs.slack.com/archives/C01UDP33CCS/p1700252725103829).

In short, mutators are components that modify (i.e., mutate) the original test plan generated by the mixedversion planner. These changes are supposed to introduce new test scenarios in ways that do not interfere with the vast majority of tests. Tests will have the ability to individually enable or disable specific mutators as necessary; by default, all mutators will apply under some probability.

There is a working implementation of the entire idea in the [rc/mixedversion-plan-mutators](https://github.com/renatolabs/cockroach/tree/rc/mixedversion-plan-mutators) branch, in case it is helpful to see parts of the entire picture. That branch includes the proposed mutator API and an implementation of a mutator that, when merged, will close #111595.

The idea is to break down the changes on that branch into multiple, easier to digest PRs. This is the first such PR.

**Review by DarrylWong — COMMENTED** [review]
I think I want to poke around the rc/mixedversion-plan-mutators branch just a bit more, but in a vacuum this PR looks good to me. Left a few small comments though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-:-Nl-1lqyA02tTbXyp0K2:b-arj8yr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nkzqy6ZDhu_wzrmC5w1:-Nkzqy6ZDhu_wzrmC5w2:bgxpw2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L425)):*
> ```Go
> // concurrently.
> func (t *Test) InMixedVersion(desc string, fn userFunc) {
> 	var lastUpgradeStage UpgradeStage
> ```

nit: `lastUpgradeStage` read to me as `finalUpgradeStage` at first. `prevUpgradeStage` might be a little more clear?
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl-6XIBDeR26liXaupE:-Nl-6XIBDeR26liXaupF:bgffmf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L119)):*
> ```Go
> 
> 		performingRollback := p.shouldRollback(toVersion)
> 		firstUpgradeStage := FinalUpgradeStage
> ```

nit: Might be worth rewriting this as an if else loop to avoid `firstUpgradeStage` vs `InitialUpgradeStage` and `firstUpgradeStage = FinalUpgradeStage` all together. Was a bit confusing to me first read through. Or think of a different name, but I don't have any ideas.

I don't think it's *that* confusing though, so up to you. 

i.e:



_Code snippet:_
```Go
		if p.shouldRollback(toVersion) {
			plan.Add(p.upgradeSteps(InitialUpgradeStage, fromVersion, toVersion))
			// next -> previous (rollback)
			plan.Add(p.downgradeSteps(toVersion, fromVersion))

			// previous -> current
			plan.Add(p.upgradeSteps(FinalUpgradeStage, fromVersion, toVersion))
		} else {
			plan.Add(p.upgradeSteps(FinalUpgradeStage, fromVersion, toVersion))
		}
```
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl-2hDnEP5L2BF_7xd_:-Nl-2hDnEP5L2BF_7xda:b-bnluyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L400)):*
> ```Go
> 		// Include debug information if we are in debug mode.
> 		var debugInfo string
> 		if debug {
> ```

Thoughts on exposing this debug option beyond just the data driven tests? i.e. an env variable the user can specify?

Just the stage probably isn't that helpful but maybe in the future if you add more debug only prints.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl-0nKM-nBucILJZJC_:-Nl-0nKM-nBucILJZJCa:b7utamg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages#L1)):*
> ```
> # Test that steps have the expected upgrade stage associated to their
> ```

This test doesn't hit the `after-upgrade-finished` stage. Might be worth throwing an `afterUpgradeFinalized` hook in there too.

**Review by herkolategan — APPROVED** [review]
Exciting enhancements, including those on the way! Overall looks great, left a few minor nits and questions of my own.

> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-:-Nl3AT9V7J7GrCP5_WGD:b-t27ay7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl3BYTg0PeCuDzNprkL:-Nl3BYTg0PeCuDzNprkM:bhz897g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L32)):*
> ```Go
> 		// background functions, etc.
> 		initSteps []testStep
> 		// startClusterID is step ID after which the cluster should be
> ```

Nit: 'the' step ID...
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl39O6x8RkUUWQShqaR:-Nl39O6x8RkUUWQShqaS:bvl1clq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L75)):*
> ```Go
> 	// runs, so that we are able to select, for example, "stages after
> 	// rollback" by doing `stage > RollbackUpgrade`.
> 	ClusterSetupStage = UpgradeStage(iota)
> ```

Nit: Referring to the style guide "Only group related declarations. Do not group declarations that are unrelated." (https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Group-Similar-Declarations) It might be my personal preference to make a separate const block with the relating type declared right above it.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl3DnPb7bJar0OvkIyw:-Nl3DnPb7bJar0OvkIyx:b-stxmbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L127)):*
> ```Go
> 		plan.Add(p.upgradeSteps(firstUpgradeStage, fromVersion, toVersion))
> 		if performingRollback {
> 			// next -> previous (rollback)
> ```

ultra nit: I'm still divided on full sentences in comments everywhere, and here it might not really make sense, but maybe with Darryl's suggestion there could be a bigger comment above the whole block explaining the steps. The comments are clear though and make the code easier to follow, so honestly I'm not convinced on full sentences (always?).
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl34sKEAMbZqn9Lzu98:-Nl34sKEAMbZqn9Lzu99:b-f8i1tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L430)):*
> ```Go
> }
> 
> func (u UpgradeStage) String() string {
> ```

Nit: Stringer: Not promoting stringer or specifically suggesting a swap to it, but would like to know why you have chosen not to use it here (on type declaration)?

**Review by DarrylWong — APPROVED** [review]
Got a chance to see how it interacts w/ the mutators and it LGTM!

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115118)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nkzqy6ZDhu_wzrmC5w1:-NlP27wL9CPVnKli60Zy:b-86mr6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L425)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

nit: `lastUpgradeStage` read to me as `finalUpgradeStage` at first. `prevUpgradeStage` might be a little more clear?
</blockquote></details>

I like it, done.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl3BYTg0PeCuDzNprkL:-NlP29oB4tXTF5gL5lx7:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L32)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Nit: 'the' step ID...
</blockquote></details>

Fixed.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl39O6x8RkUUWQShqaR:-NlP2B5f9veLYvwm7YCi:b-ysqq0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L75)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Nit: Referring to the style guide "Only group related declarations. Do not group declarations that are unrelated." (https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Group-Similar-Declarations) It might be my personal preference to make a separate const block with the relating type declared right above it.
</blockquote></details>

Huh, TIL. I thought I had addressed that with a newline to split the groups + a comment introducing the `UpgradeStage` constants. IMO, that's good enough but to stay compliant, I split the const groups as it's not a bad idea anyway.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl-6XIBDeR26liXaupE:-NlP2Rl8882uNXt3E8g9:bakosi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L119)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

nit: Might be worth rewriting this as an if else loop to avoid `firstUpgradeStage` vs `InitialUpgradeStage` and `firstUpgradeStage = FinalUpgradeStage` all together. Was a bit confusing to me first read through. Or think of a different name, but I don't have any ideas.

I don't think it's *that* confusing though, so up to you. 

i.e:
</blockquote></details>

I did it that way to avoid the minor duplication in the u`upgradeSteps` call, but I agree this reads better. Updated.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl3DnPb7bJar0OvkIyw:-NlP2by_24kSKROFtlen:b-df3zpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L127)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

ultra nit: I'm still divided on full sentences in comments everywhere, and here it might not really make sense, but maybe with Darryl's suggestion there could be a bigger comment above the whole block explaining the steps. The comments are clear though and make the code easier to follow, so honestly I'm not convinced on full sentences (always?).
</blockquote></details>

I'm not changing this for now because the function documentation already includes a step by step description of what the function does. I felt like including inline documentation would duplicate that effort. That said as this function evolves, it might come a time when being more explicit in inline documentation will be necessary, so I'll keep this in mind.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl-2hDnEP5L2BF_7xd_:-NlP32XP0LpMoexw3URm:b-totok9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L400)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

Thoughts on exposing this debug option beyond just the data driven tests? i.e. an env variable the user can specify?

Just the stage probably isn't that helpful but maybe in the future if you add more debug only prints.
</blockquote></details>

It might be useful in the future, but I think it will serve us better to only do it when we have a use-case for it.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl34sKEAMbZqn9Lzu98:-NlP3AW56ZcwXrA6qckg:b-d5aiyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L430)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Nit: Stringer: Not promoting stringer or specifically suggesting a swap to it, but would like to know why you have chosen not to use it here (on type declaration)?
</blockquote></details>

Not sure I understand the comment -- are you asking why we make `UpgradeStage` an int rather than leave it abstract with `fmt.Stringer`? If so, the comment on `UpgradeStage` should answer that: mostly so that we are able to compare stages based on the time they happen (e.g., `InitialUpgrade < FinalUpgrade`).

If that's not what you asked, could you please clarify?
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-Nl-0nKM-nBucILJZJC_:-NlP3Y_V7JpnQPz3kJq_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6a3347bc627634ff410aad74bc09e3ef2036d6b/pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages#L1)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

This test doesn't hit the `after-upgrade-finished` stage. Might be worth throwing an `afterUpgradeFinalized` hook in there too.
</blockquote></details>

Done.

**Comment by renatolabs** [comment]
`backup-restore/mixed-version` failed on this branch [1] but I don't believe the failure is caused by this PR. I let the DR team know about this.

TFTRs!

bors r=herkolategan,DarrylWong

[1] https://teamcity.cockroachdb.com/viewLog.html?buildId=13083589&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv&branch_Cockroach_Nightlies=115118

**Review by srosenberg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-:-NlPtmjc9E6UXDu17GhH:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @renatolabs)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-NlPrBiL0AS38FOKupa2:-NlPrBiM79e9DJMxNZU5:buivvvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af0c8e2c6157e581099ba10f64d9516343153/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L62)):*
> ```Go
> 		from           *clusterupgrade.Version
> 		to             *clusterupgrade.Version
> 		sequentialStep sequentialRunStep
> ```

I had to pause here and go read the planner code... in hindsight, `consecutive` might be better than `sequential` since some of the `testStep`s may end up being `concurrentRunStep`s. Methinks my conceptual entanglement is not seeing an explicit separation between state transitions (of the upgrade FSM) and steps or actions executed either sequentially or concurrently with the state transitions.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-NlPeeoS413t5wt1mH9Y:-NlPeeoS413t5wt1mH9Z:ba5mz92) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af0c8e2c6157e581099ba10f64d9516343153/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L74)):*
> ```Go
> 
> const (
> 	// Upgrade stages are defined in the order they happen during test
> ```

This order is _partial_ or total? E.g., conceptually BackgroundStage can be delayed until virtually any of the subsequent stages. At some point, it might be instructive to describe the state machine in terms of stages. For now, leaving it underspecified seems fine.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-NlPixCoDf6d4h6EioIP:-NlPixCoDf6d4h6EioIQ:b-f9yirt) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af0c8e2c6157e581099ba10f64d9516343153/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L127)):*
> ```Go
> 			// previous -> next
> 			plan.Add(p.upgradeSteps(FinalUpgradeStage, fromVersion, toVersion))
> 		} else {
> ```

Nit: can drop `else` since `FinalUpgradeStage` is common to both.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-NlPjYkw9OgUtPjeMneq:-NlPjYkw9OgUtPjeMner:b5plvf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af0c8e2c6157e581099ba10f64d9516343153/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L136)):*
> ```Go
> 
> 		// wait for upgrade to finalize
> 		plan.Add(p.finalUpgradeSteps(fromVersion, toVersion))
> ```

Nit: I find these helpers sounding confusingly similar: `p.upgradeSteps(FinalUpgradeStage,...`, `p.finalizeUpgradeSteps`, `p.finalUpgradeSteps`. Have you considered encoding state transitions as an FSM? E.g., `TxnStateTransitions` (in `conn_fsm.go`) is not necessarily more readable, but it groups all state transitions in one place, as well as makes it easy to extract the full FSM spec.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115118)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-NlPrBiL0AS38FOKupa2:-NlUHMoVDmhyVlj-62UG:b-2lk4yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af0c8e2c6157e581099ba10f64d9516343153/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L62)):*
> better than `sequential` since some of the `testStep`s may end up being `concurrentRunStep`s

I think it depends on the granularity you're looking at? If steps `{A, B, C}` are sequential, they are still sequential relative to one another even if, if you look inside it, you find out that B does 3 things in parallel.

> explicit separation between state transitions (of the upgrade FSM) and steps or actions executed either sequentially or concurrently with the state transitions

I'm still digesting this and trying to understand what this would mean in more concrete terms. It's also not immediately obvious to me what states we would to model in this package -- logical versions? cluster versions? binary versions?
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-NlPeeoS413t5wt1mH9Y:-NlUJnXH0dzv6z8ajAYG:bzdsser) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af0c8e2c6157e581099ba10f64d9516343153/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L74)):*
It's a total order if we define it to mean "time at which the stage _starts_".  The only reason the definition has to be tweaked to say "starts" instead of "runs" is indeed because of background steps. My opinion is that, in practice, this is pretty sufficient for our current needs, since the ordering does apply for all other stages.

> At some point, it might be instructive to describe the state machine in terms of stages

The documentation for `(*testPlanner).Plan()` includes documentation for the (very simple) upgrade path these tests take (what I understand you mean by state machine in this case). I updated the comments to reflect the stages that each step correspond to. Let me know if this helps.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-NlPixCoDf6d4h6EioIP:-NlUNI4i6FI4Oda2Xtc6:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af0c8e2c6157e581099ba10f64d9516343153/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L127)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: can drop `else` since `FinalUpgradeStage` is common to both.
</blockquote></details>

Good point, done.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-NlPjYkw9OgUtPjeMneq:-NlUNLPpBmeRTZc__9Ei:b-i2nb5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af0c8e2c6157e581099ba10f64d9516343153/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L136)):*
I agree the naming is confusing, I'm open to suggestions! `FinalUpgradeStage` is probably unfortunate. Maybe `LastUpgradeStage`? All I mean is that we won't attempt a rollback after upgrading the nodes.

I also see the problem with `finalUpgradeSteps`, especially given the other two "finals". Maybe `afterUpgradeSteps`? `postUpgradeSteps`?

> Have you considered encoding state transitions as an FSM?

Hrm, I can think about this, but I don't see an immediate win, especially given that the "events" would be all coming from within the package. I would need to prototype the change to get a better sense of the pros and cons.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115118)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115118#-NlPjYkw9OgUtPjeMneq:-NlV7DutAed0lyu7Ed_o:bwpcku1) ([raw file](https://github.com/cockroachdb/cockroach/blob/246af0c8e2c6157e581099ba10f64d9516343153/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L136)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I agree the naming is confusing, I'm open to suggestions! `FinalUpgradeStage` is probably unfortunate. Maybe `LastUpgradeStage`? All I mean is that we won't attempt a rollback after upgrading the nodes.

I also see the problem with `finalUpgradeSteps`, especially given the other two "finals". Maybe `afterUpgradeSteps`? `postUpgradeSteps`?

> Have you considered encoding state transitions as an FSM?

Hrm, I can think about this, but I don't see an immediate win, especially given that the "events" would be all coming from within the package. I would need to prototype the change to get a better sense of the pros and cons.
</blockquote></details>

Renamed a few things that I _believe_ should make it a little clearer:

* `InitialUpgradeStage` was renamed to `TemporaryUpgradeStage` to indicate that the upgrade is temporary (will be rolled back). Better name because it also allows us to use this stage to encode multiple rollbacks if we wanted (`Initial` being a less flexible name)
* `FinalUpgradeStage` renamed to `LastUpgradeStage`, since the actual meaning of this stage is that it won't be rolled back. Also eliminates any confusion with upgrade finalization.
* `finalUpgradeSteps` renamed to `afterUpgradeSteps` and changed to focus only on running `AfterUpgradeFinalized` user-provided steps.

Let me know if this makes sense!

**Comment by renatolabs** [comment]
Merging. FYI, this series of PRs will be put on pause during the holidays. I'll resume starting from part 2 next year. 🎅 

TFTRs!

bors r=herkolategan,DarrylWong,srosenberg

**Comment by renatolabs** [comment]
blathers backport 23.2 23.1

**Pull request merged**
