### PR TITLE
storage: remove slow path for MVCCResolveWriteIntentRange

### PR DESCRIPTION
**Pull request by sumeerbhola**
We no longer have physically interleaved intents, that needed the
slow path.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81063#-:-N1LPKJH39oPwt5dWOGf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 3369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81063#-N1LOmSf3uImLyRnAqt_:-N1LOmSf3uImLyRnAqta:b74clfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bed344e1d45658e98ab72be8adaeb302d7bd005/pkg/storage/mvcc.go#L3369)):*
> ```Go
> 			num++
> 		}
> 		if max > 0 && num == max {
> ```

Do we want to move this up right before `// Parse the MVCCMetadata to see if it is a relevant intent.`? Generally, resume spans start at the first key that could not be returned/processed, not at the key following the last key which was returned/processed. This avoids returning a resume span in cases where the limit exactly matches the number of keys in the span.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81063#-:-N1QLbfe9WFi270w8Xxm:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/storage/mvcc.go` line 3369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81063#-N1LOmSf3uImLyRnAqt_:-N1QLaVl14uEqWyd_Ryo:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bed344e1d45658e98ab72be8adaeb302d7bd005/pkg/storage/mvcc.go#L3369)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to move this up right before `// Parse the MVCCMetadata to see if it is a relevant intent.`? Generally, resume spans start at the first key that could not be returned/processed, not at the key following the last key which was returned/processed. This avoids returning a resume span in cases where the limit exactly matches the number of keys in the span.
</blockquote></details>

Done

**Review by nvb — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81063)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/storage/mvcc.go` line 3369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81063#-N1LOmSf3uImLyRnAqt_:-N1QMyZ69zwCQpHpID5A:b56slxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bed344e1d45658e98ab72be8adaeb302d7bd005/pkg/storage/mvcc.go#L3369)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Done
</blockquote></details>

We're still returning `lastResolvedKey.Next()`. Do we want to? Can we return `sepIter.Key().Key` (the key of the first unprocessed intent, if there is one)?

Also, can we move this after the `if intent.Txn.ID != meta.Txn.ID {` block?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81063)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/storage/mvcc.go` line 3369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81063#-N1LOmSf3uImLyRnAqt_:-N1cxDXo-21eV4fGaKWo:bun4tpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bed344e1d45658e98ab72be8adaeb302d7bd005/pkg/storage/mvcc.go#L3369)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're still returning `lastResolvedKey.Next()`. Do we want to? Can we return `sepIter.Key().Key` (the key of the first unprocessed intent, if there is one)?

Also, can we move this after the `if intent.Txn.ID != meta.Txn.ID {` block?
</blockquote></details>

- I wanted to keep the same non-allocation behavior that was there before this change (may not be important).
- The max checking happens after the previous intent has been resolved and `sepIter` has been stepped once. So from a wasted work perspective when resuming, returning `lastResolvedKey.Next()` or `sepIter.Key().Key` are equivalent, since seeking to either will place the iter in the same position.
- If we moved the max checking to after `if intent.Txn.ID != meta.Txn.ID` we would definitely want to use `sepIter.Key().Key` to avoid wasting work when resuming. Given that there have been PRs (e.g.`ExportRequest` using `ResourceLimiter`) to bound the work performed in a KV request, I'm a bit wary of continuing doing work after the max has been reached. I realize that the current code is insufficient since there could already have been a large amount of iteration over other txns intents until we reached max.

The code prior to this refactor, for both the slow and fast path, would return a resume span even if the iterator was exhausted, which is why TestEvaluateBatch/ranged_intent_resolution_with_MaxSpanRequestKeys=3 failed. Now fixed.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81063#-:-N1dAje02-1yzfvudeXt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by erikgrinaker** [comment]
Failed on `TestChangefeedBackfillCheckpoint`, but I stressed it for 500 runs locally without fail, so it's likely unrelated flake.

bors retry

**Comment by erikgrinaker** [comment]
Different flake, `TestInitRaftGroupOnRequest` this time (which I'm on the hook for). Third time's the charm!

bors retry

**Comment by erikgrinaker** [comment]
`TestChangefeedBackfillCheckpoint` again. It's possible there's something to look into here, since I'm not seeing it flake a lot elsewhere. Will stop pestering bors about this for now.

**Comment by sumeerbhola** [comment]
Maybe it was unrelated, since CI is green now.

**Comment by sumeerbhola** [comment]
bors r=nvanbenschoten

**Comment by sumeerbhola** [comment]
flake in TestComposeGSSPython https://github.com/cockroachdb/cockroach/issues/76547

**Comment by sumeerbhola** [comment]
bors retry

**Comment by sumeerbhola** [comment]
another flake in TestComposeGSSPython

**Comment by sumeerbhola** [comment]
bors retry

**Pull request merged**
