### PR TITLE
libroach: extract headers for mvccScanner

### PR DESCRIPTION
**Pull request by tbg**
I'm probably doing this all wrong, but I want to unit test `mvccScanner`
(from `db_test.cc`) and that does not seem to be feasible when it's
declared inside of `db.cc`. Open for suggestions on the right way.

I would go a step further and pull `mvccScanner` into its own file if
folks think that that's a good idea.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Isn't `mvccScanner` adequately tested from Go code? Curious what additional you want to test.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[c-deps/libroach/db.h, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608#-L3LG2B3VHurA0u_9vVE:-L3LG2B4Gn0Qe95DRBTK:b-80iabn) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa882afdb5f14322d0d929a7f8b9eb4966e590b8/c-deps/libroach/db.h#L38)):*
> ```objc
> // ordering as these keys do not sort lexicographically correctly.
> std::string EncodeKey(DBKey k);
> std::string EncodeKey(const rocksdb::Slice& s, int64_t wall_time, int32_t logical);
> ```

This 

---

*[c-deps/libroach/db.hpp, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608#-L3LGBIKGpTd2--8mr3i:-L3LGBIKGpTd2--8mr3j:b834751) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa882afdb5f14322d0d929a7f8b9eb4966e590b8/c-deps/libroach/db.hpp#L17)):*
> ```cpp
> #include "protos/storage/engine/enginepb/mvcc.pb.h"
> 
> template <bool reverse> class mvccScanner {
> ```

Multiple things to comment on here. First, the `.hpp` isn't a style we use. C++ code can go in a `.h` file. I'd probably place this in an `mvcc.h` file. Next, you've made everything in the class public, which probably wasn't your intention. Lastly, the class in the `.h` file is generally considered the public definition where another engineer might look for documentation. So all of the doc comments should be here.

Because `mvccScanner` is a templated class, you can copy all of it as-is from `db.cc` to `mvcc.h`. C++ compilers are generally smart enough to not inline large template class functions now. The one concern is if bits of `mvccScanner` use functions from `db.cc` that are not specified in `.h` files.  But the right answer is to probably move those definitions to appropriate `.h` files as well (e.g. `DBIterator` will likely need to move to `db.h`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608#-:-L3LHJ4WwZdW8slR_UG2:b-8pggk4)*

**Comment by tschottdorf** [comment]
> Isn't mvccScanner adequately tested from Go code? Curious what additional you want to test.

Code I'm adding in a generational MVCC prototype. I *could* exercise that from Go as well, but that doesn't feel right, and it's a good enough excuse for me to try to figure out how this actually works.

Do you agree that we generally want to massage the C++ code a little bit? I don't want to waste my time here but it seems that over time we're going to get more C++ than we have today and there already is a surprising amount of logic without a matching amount of tests.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608#-:-L3LlzNESxaAeyGW2TMO:b-pipv8u)*

**Comment by tschottdorf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[c-deps/libroach/db.hpp, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608#-L3LGBIKGpTd2--8mr3i:-L3LmjZq4WoLA0LMwVoD:b-ucbmqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa882afdb5f14322d0d929a7f8b9eb4966e590b8/c-deps/libroach/db.hpp#L17)):*
Thanks! I didn't know about the [problems with templated classes when their methods aren't declared in the header](https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl). It seems to work alright here (probably because of the typedefs at the bottom)?

You also find it *better* for some reason to have everything inline in a header file in this case? I'm just double checking because that goes against what little intuition I have.

> Next, you've made everything in the class public, which probably wasn't your intention.

Correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608)*

**Comment by tschottdorf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[c-deps/libroach/db.hpp, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608#-L3LGBIKGpTd2--8mr3i:-L3ONzVPi-2f-pYWtoPl:b-2vxyk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa882afdb5f14322d0d929a7f8b9eb4966e590b8/c-deps/libroach/db.hpp#L17)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Thanks! I didn't know about the [problems with templated classes when their methods aren't declared in the header](https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl). It seems to work alright here (probably because of the typedefs at the bottom)?

You also find it *better* for some reason to have everything inline in a header file in this case? I'm just double checking because that goes against what little intuition I have.

> Next, you've made everything in the class public, which probably wasn't your intention.

Correct.
</blockquote></details>

Ah, found https://google.github.io/styleguide/cppguide.html#Self_contained_Headers. I'll try to do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608)*

**Comment by tschottdorf** [comment]
PTAL. Moved `mvccScanner` to `mvcc.h`, and also moved a lot of these small helper functions from `db.cc` to `dbhelper.cc`.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[c-deps/libroach/db.h, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608#-L3LG2B3VHurA0u_9vVE:-L3OXgc09qfIcOi34pPN:bxm2ln7) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa882afdb5f14322d0d929a7f8b9eb4966e590b8/c-deps/libroach/db.h#L38)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This 
</blockquote></details>

Looks like you were going to say more, but this has since moved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608#-:-L3OXpzhSMtV1WURqcPd:b-y3jiqk)*

**Comment by tschottdorf** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[c-deps/libroach/dbhelper.h, line 14 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608#-L3OnQfL6bn02YcXNCG6:-L3Oty0VKryvYzvdsi0K:bqnjhxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a357b961b65d8eebb612ec9bad60036a3775cf/c-deps/libroach/dbhelper.h#L14)):*
Just to double check, do you also not see the point in having `dbhelper.cc` (or are you suggesting having only `db.h` but keep `db{,helper}.cc`)? As you pointed out `db.cc` is a huge grab bag and so I was gonna try to pull some of the smaller bits out of it, even if it's not quite principled yet.

>  I'm not sure if it is worth your time to fix it up

Navigating these huge files has been costing me a lot of time (I assume that'll get better with experience, but still...), so I'm comfortable investing some of it into cleanup. Would be good to have reasonable modularity in the C++ codebase as well.

I was thinking that in some future version of the code there would be files for the various `DBEngine` derivatives, the merge stuff, the custom comparator, merge operators, the SSTable userinfo stuff (for time bounded iters), MVCC logic, compaction, and encoding. At the moment I don't feel qualified to make these organizational calls, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/dbhelper.h, line 14 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608#-L3OnQfL6bn02YcXNCG6:-L3P9jh217pjgMs7wjDk:bbi08yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a357b961b65d8eebb612ec9bad60036a3775cf/c-deps/libroach/dbhelper.h#L14)):*
> Just to double check, do you also not see the point in having dbhelper.cc (or are you suggesting having only db.h but keep db{,helper}.cc)? As you pointed out db.cc is a huge grab bag and so I was gonna try to pull some of the smaller bits out of it, even if it's not quite principled yet.

I'm suggesting not having `dbhelper.{cc,h}` at all. Some bits in `db.cc` need to have declarations in `db.h` and then you'd have to "export" (i.e. move out of the unnamed namespace) those functions in `db.cc`. My objection to `dbhelper.{cc,h}` is that I can't see exactly what would exist in it long term.

> Navigating these huge files has been costing me a lot of time (I assume that'll get better with experience, but still...), so I'm comfortable investing some of it into cleanup. Would be good to have reasonable modularity in the C++ codebase as well.

Heh, I can understand that. The C++ codebase is definitely not well organized. `db.cc` is a particular mess. 

> I was thinking that in some future version of the code there would be files for the various DBEngine derivatives, the merge stuff, the custom comparator, merge operators, the SSTable userinfo stuff (for time bounded iters), MVCC logic, compaction, and encoding. At the moment I don't feel qualified to make these organizational calls, though.

`db.cc` definitely deserves to be split up. Would you like me to take a stab at doing so?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21608)*

**Pull request closed without merging**
