### PR TITLE
workload: add TPC-DS queries and workload

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds TPC-DS queries and a simple workload to run them. The dataset
must be imported manually prior to running the workload. Some
queries need modifications before they can be parsed by CRDB, so
they are disabled.

Addresses: #37436.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Note that the queries were generated for scale factor 1 (I forgot about that :/ ), but I think still it'll be useful to merge this since we're performing terrible even on 1 GB dataset on some queries (#37464).

**Review by danhhz — COMMENTED** [review]
I didn't really look at any of the individual queries in queries.go, but everything else looks pretty good. Just a few comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-:-LenKNHE26QMZ_3gcqgU:b-55nndd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @yuzefovich)

___
*[pkg/workload/tpcds/import.sql, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenGvXYC8ZV4s4FuZ5C:-LenGvXYC8ZV4s4FuZ5D:b-kt2nx) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/import.sql#L5)):*
> ```SQLPL
> -- 10 - about 1GB and 10GB respectively - are available at the moment):
> --
> --   RESTORE DATABASE tpcds FROM 'gs://cockroach-fixtures/workload/tpcds/scalefactor=1/backup';
> ```

Can you include info here about how these were generated?
___
*[pkg/workload/tpcds/tpcds.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenHV2tDZqu0024plcF:-LenHV2tDZqu0024plcG:b-gaz2yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L67)):*
> ```Go
> 		g.flags.StringVar(&g.queriesToRunRaw, `queries`,
> 			``,
> 			`Queries to run. Use a comma separated list of query numbers. If omitted, all queries are run`)
> ```

I'd document in one of these two flags what the precedence is if a query is in both of them
___
*[pkg/workload/tpcds/tpcds.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenHzx-CsVqjMZ0ji1T:-LenHzx-CsVqjMZ0ji1U:b-3o6bj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L127)):*
> ```Go
> 
> // Tables implements the Generator interface.
> func (w *tpcds) Tables() []workload.Table { return []workload.Table{} }
> ```

hmm, I haven't tested it but I think if you tried to run a `workload init`, `workload fixtures make`, or `workload fixtures import`, this would look like it succeeded when really it did nothing. I think if you define the tables with only names and schemas (but leave InitialRows unset), it'll make those tools return a helpful error
___
*[pkg/workload/tpcds/tpcds.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenIoj0-3j5RDNQOGw2:-LenIoj0-3j5RDNQOGw3:boypmid) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L170)):*
> ```Go
> 	start := timeutil.Now()
> 	if w.config.queryTimeLimit > 0 {
> 		ch := make(chan interface{}, 2)
> ```

ctxgroup is awesome for stuff like this

```
g := ctxgroup.WithContext(ctx)
g.GoCtx(func (ctx context.Context) error) {
    rows, err = w.db.QueryContext(ctx, query)
    return err
})
g.GoCtx(func (ctx context.Context) error {
    select {
    case <-ctx.Done():
        return nil
    case <- time.After(w.config.queryTimeLimit)
        return errors.Errorf(`query %d timed out`, queryNum)
    }
})
if err := g.Wait(); err != nil {
    return err
}
```

If any of the GoCtx calls return an error, it will cancel the context passed to the rest of them. The QueryContext method on db will turn that into cancelling your query. I think you also want a time.Timer instead of the time.After so you can Stop it when the query is successful, but I don't recall how you use it offhand
___
*[pkg/workload/tpcds/tpcds.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenK3IJ9TZi0D59fHMX:-LenK3IJ9TZi0D59fHMY:b3pz2ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L202)):*
> ```Go
> 		return err
> 	}
> 	elapsed := timeutil.Since(start)
> ```

don't you want a histogram here?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/workload/tpcds/import.sql, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenGvXYC8ZV4s4FuZ5C:-LeoK7ft2ghcynJLRv1Y:b-aptiv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/import.sql#L5)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Can you include info here about how these were generated?
</blockquote></details>

I wrote up my steps on a confluence page (https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/122290457/DRAFT+Generating+TPC-DS+dataset). I added a short comment about that page.
___
*[pkg/workload/tpcds/tpcds.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenHV2tDZqu0024plcF:-LeoLQz8BBEShp8VpqAZ:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L67)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I'd document in one of these two flags what the precedence is if a query is in both of them
</blockquote></details>

Good point, done.
___
*[pkg/workload/tpcds/tpcds.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenHzx-CsVqjMZ0ji1T:-LeofqxY9j5mtMyadTvp:b-1lyirn) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L127)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

hmm, I haven't tested it but I think if you tried to run a `workload init`, `workload fixtures make`, or `workload fixtures import`, this would look like it succeeded when really it did nothing. I think if you define the tables with only names and schemas (but leave InitialRows unset), it'll make those tools return a helpful error
</blockquote></details>

You were right that previously it would silently or with little text do nothing that could look like a success, so I added the schemas as suggested. Now, `workload init` still silently does nothing, `workload fixtures make` gives a helpful `Error: make fixture is not supported for workload tpcds` while `workload fixtures import` gives weird `Error: importing fixture: importing table web_sales: pq: syntax error at or near ")"` (with the name of the table being randomly chosen). Any suggestions on how to improve the errors further?
___
*[pkg/workload/tpcds/tpcds.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenIoj0-3j5RDNQOGw2:-LeoXlpl8ZFG7bV22bXk:b68ssfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L170)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

ctxgroup is awesome for stuff like this

```
g := ctxgroup.WithContext(ctx)
g.GoCtx(func (ctx context.Context) error) {
    rows, err = w.db.QueryContext(ctx, query)
    return err
})
g.GoCtx(func (ctx context.Context) error {
    select {
    case <-ctx.Done():
        return nil
    case <- time.After(w.config.queryTimeLimit)
        return errors.Errorf(`query %d timed out`, queryNum)
    }
})
if err := g.Wait(); err != nil {
    return err
}
```

If any of the GoCtx calls return an error, it will cancel the context passed to the rest of them. The QueryContext method on db will turn that into cancelling your query. I think you also want a time.Timer instead of the time.After so you can Stop it when the query is successful, but I don't recall how you use it offhand
</blockquote></details>

Hm, that doesn't seem to work - the query isn't getting cancelled. I ran through Goland debugger, and the second goroutine correctly returns error after the timeout, but `g.Wait` appears to be blocked until all goroutines return. Also, the running query shows up in `SHOW QUERIES`. I also tried `timeoutCtx, cancel := context.WithCancel`, passing `timeoutCtx` into `ctxgroup.WithContext`, and cancelling `timeoutCtx` in the second goroutine, but that didn't seem to do anything.
___
*[pkg/workload/tpcds/tpcds.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenK3IJ9TZi0D59fHMX:-LeoWZRq9F7u9OvntI4h:b-mognm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L202)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

don't you want a histogram here?
</blockquote></details>

I think that histograms are useful when the queries perform about the same amount of work and we want to see the different percentiles of latency with different concurrency settings. Here, however, I think the most useful information is simply how long a particular query took to run, and the queries have very different running times (some finish in less than a second, some don't complete in 15-20 minutes), so at the moment I see a single message from a single query run (whether it's an error or the time it took to complete the query) as the most useful information with histograms only cluttering the output.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @yuzefovich)

___
*[pkg/workload/tpcds/tpcds.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenHzx-CsVqjMZ0ji1T:-Leqiy7T1V2QwHhxE7VS:bmxdip7) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L127)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

You were right that previously it would silently or with little text do nothing that could look like a success, so I added the schemas as suggested. Now, `workload init` still silently does nothing, `workload fixtures make` gives a helpful `Error: make fixture is not supported for workload tpcds` while `workload fixtures import` gives weird `Error: importing fixture: importing table web_sales: pq: syntax error at or near ")"` (with the name of the table being randomly chosen). Any suggestions on how to improve the errors further?
</blockquote></details>

Ah. The fixtures make error is coming from https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/workloadccl/fixture.go#L243-L249. Mind incorporting that same check into https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/workloadccl/fixture.go#L287? That will fix fixtures import.

Looks like init is trying to be too smart about this. Let's remove the `NumBatches == 0` and `continue` part of this `if`: https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/workload.go#L469-L471

Sorry about that, thought this has all already been fixed.
___
*[pkg/workload/tpcds/tpcds.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenIoj0-3j5RDNQOGw2:-Leqk-ip9mFcVjxd_x0Q:b-5iy60f) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L170)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, that doesn't seem to work - the query isn't getting cancelled. I ran through Goland debugger, and the second goroutine correctly returns error after the timeout, but `g.Wait` appears to be blocked until all goroutines return. Also, the running query shows up in `SHOW QUERIES`. I also tried `timeoutCtx, cancel := context.WithCancel`, passing `timeoutCtx` into `ctxgroup.WithContext`, and cancelling `timeoutCtx` in the second goroutine, but that didn't seem to do anything.
</blockquote></details>

Yeah, g.Wait is supposed to block until all goroutines return. Looks like ctx cancellation still isn't hooked up through pgwire on a QueryContext call, so you'll have to do this the annoying way. Somewhere you'll have to grab the query id out of SHOW QUERIES and then make the `case <- time.After(` branch call CANCEL QUERY. That should work.

the `context.WithCancel` you added is unnecessary. returning a non-nil error from any of the GoCtx closures will do that for you
___
*[pkg/workload/tpcds/tpcds.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenK3IJ9TZi0D59fHMX:-Leql-zm0uvQmOz4b0G6:b-lpfg8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L202)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think that histograms are useful when the queries perform about the same amount of work and we want to see the different percentiles of latency with different concurrency settings. Here, however, I think the most useful information is simply how long a particular query took to run, and the queries have very different running times (some finish in less than a second, some don't complete in 15-20 minutes), so at the moment I see a single message from a single query run (whether it's an error or the time it took to complete the query) as the most useful information with histograms only cluttering the output.
</blockquote></details>

hmm, i think the percentiles would still be useful, but i agree that the histogram would currently print out too often and would be spammy. mind leaving this as a TODO?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/workload/tpcds/tpcds.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenHzx-CsVqjMZ0ji1T:-LesUrnn6eU0tgdHaaUn:b2u0147) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L127)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Ah. The fixtures make error is coming from https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/workloadccl/fixture.go#L243-L249. Mind incorporting that same check into https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/workloadccl/fixture.go#L287? That will fix fixtures import.

Looks like init is trying to be too smart about this. Let's remove the `NumBatches == 0` and `continue` part of this `if`: https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/workload.go#L469-L471

Sorry about that, thought this has all already been fixed.
</blockquote></details>

Thanks for the pointers, now the errors are helpful :) 
___
*[pkg/workload/tpcds/tpcds.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenIoj0-3j5RDNQOGw2:-Lewj1IA2qBDAyGbO2h6:blx93tv) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L170)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Yeah, g.Wait is supposed to block until all goroutines return. Looks like ctx cancellation still isn't hooked up through pgwire on a QueryContext call, so you'll have to do this the annoying way. Somewhere you'll have to grab the query id out of SHOW QUERIES and then make the `case <- time.After(` branch call CANCEL QUERY. That should work.

the `context.WithCancel` you added is unnecessary. returning a non-nil error from any of the GoCtx closures will do that for you
</blockquote></details>

As it turns out, there is an extremely easy way to enforce time limit - with `statement_timeout` session variable, so no need for any of these complications we were considering.
___
*[pkg/workload/tpcds/tpcds.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenK3IJ9TZi0D59fHMX:-LesVKAJ7QnxCSWKCYq_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L202)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

hmm, i think the percentiles would still be useful, but i agree that the histogram would currently print out too often and would be spammy. mind leaving this as a TODO?
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/testutils/lint/lint_test.go, line 972 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-Lewm1ge5TY3lVsCVeLT:-Lewm1ge5TY3lVsCVeLU:btwo2fj) ([raw file](https://github.com/cockroachdb/cockroach/blob/73f553d841621b1765313eb6dd914ef3638f6473/pkg/testutils/lint/lint_test.go#L972)):*
> ```Go
> 			stream.GrepNot(`.*\.lock`),
> 			stream.GrepNot(`^storage\/engine\/rocksdb_error_dict\.go$`),
> 			stream.GrepNot(`^workload/tpcds/tpcds.go$`),
> ```

There is a spelling error in `tpcdsStoreSchema` - "s_tax_precentage", so I disabled the misspelling check on the file.

**Review by danhhz — COMMENTED** [review]
:lgtm: two last comments. feel free to merge without another review from me once you've addressed them. great work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-:-LewouIh1CBiPugNbedd:bmd39a1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @yuzefovich)

___
*[pkg/workload/tpcds/tpcds.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenIoj0-3j5RDNQOGw2:-Lewnmmi6cNmIlmZ-kuw:b27wl8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L170)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

As it turns out, there is an extremely easy way to enforce time limit - with `statement_timeout` session variable, so no need for any of these complications we were considering.
</blockquote></details>

oh nice! as always, there's a hiccup. the database/sql.DB object you're using here pools connections, so there's nothing to guarantee that your SET runs on the same connection as your query. _maybe_ the SetMaxOpenConns/SetMaxIdleConns means this does actually always work, but even if so, it's really brittle.

However, the good news is you can pass SET parameters as part of your connection string, so just stick this into your gosql.Open call above instead. I think you have to add it to each of the urls that go into the strings.Join call
___
*[pkg/workload/tpcds/tpcds.go, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LewojedESoXNLD47Zw2:-LewojedESoXNLD47Zw3:b404a51) ([raw file](https://github.com/cockroachdb/cockroach/blob/73f553d841621b1765313eb6dd914ef3638f6473/pkg/workload/tpcds/tpcds.go#L300)):*
> ```Go
> 	log.Infof(ctx, "[Q%d] return %d rows after %4.2f seconds",
> 		queryNum, numRows, elapsed.Seconds())
> 	return rows.Close()
> ```

defer this instead so it gets called in the various error paths
___
*[pkg/workload/tpch/tpch.go, line 211 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-Lewos0h6KsWV53js4iC:-Lewos0h6KsWV53js4iD:b-y0j55z) ([raw file](https://github.com/cockroachdb/cockroach/blob/73f553d841621b1765313eb6dd914ef3638f6473/pkg/workload/tpch/tpch.go#L211)):*
> ```Go
> 	log.Infof(ctx, "[%s] return %d rows after %4.2f seconds:\n  %s",
> 		queryName, numRows, elapsed.Seconds(), query)
> 	return rows.Close()
> ```

ditto. good catch by the way!

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37465)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz)

___
*[pkg/workload/tpcds/tpcds.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LenIoj0-3j5RDNQOGw2:-Lex-eUjDz9yD2Ojco-E:b-rrbatr) ([raw file](https://github.com/cockroachdb/cockroach/blob/33f6143bac9ce065f54ae98e4332b8c603e4293c/pkg/workload/tpcds/tpcds.go#L170)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

oh nice! as always, there's a hiccup. the database/sql.DB object you're using here pools connections, so there's nothing to guarantee that your SET runs on the same connection as your query. _maybe_ the SetMaxOpenConns/SetMaxIdleConns means this does actually always work, but even if so, it's really brittle.

However, the good news is you can pass SET parameters as part of your connection string, so just stick this into your gosql.Open call above instead. I think you have to add it to each of the urls that go into the strings.Join call
</blockquote></details>

Thanks, this does the trick.
___
*[pkg/workload/tpcds/tpcds.go, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-LewojedESoXNLD47Zw2:-Lex-kmz5Zf3R1xHcTWI:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/73f553d841621b1765313eb6dd914ef3638f6473/pkg/workload/tpcds/tpcds.go#L300)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

defer this instead so it gets called in the various error paths
</blockquote></details>

Thanks, done.
___
*[pkg/workload/tpch/tpch.go, line 211 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37465#-Lewos0h6KsWV53js4iC:-Lex-mz80b6yKr6ef60I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73f553d841621b1765313eb6dd914ef3638f6473/pkg/workload/tpch/tpch.go#L211)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

ditto. good catch by the way!
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Thanks for the reviews and suggestions!

bors r+

**Pull request merged**
