### PR TITLE
roachtest: add perturbation tests

### PR DESCRIPTION
**Pull request by andrewbaptist**
Adds a new latency sensitive test and a framework to run them in. Specifically it does a few things:
1) Gathers all the latency results back at the "roachtest client" rather than at the workload nodes by utilizing UDP to aggregate the results.
2) Steps the load back to 30% of the original load by measuring during the fill and then using that as a baseline to calculate from.
3) Collects selective profiles and adds them to the artifacts as part of the test run.

As of today, this test doesn't fail in the case of high latency as I'm working out the details of where to draw the threshold, but it has all the data so we can make that decision once we have more of these tests written.

### CODE REVIEW

**Comment by renatolabs** [comment]
> Should I consider moving these functions into the Cluster package

It looks like the functions should already be ready to be consumed as-is (every test lives in the `tests` package). If you want/prefer, you could also create a specific package in `roachtestutil` for a separate namespace. I'd avoid adding even more functions to the cluster or test "interfaces" as they are already very large and we don't need functions at that level to enable sharing of functionality.

**Review by kvoli — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, 12 of 12 files at r5, 3 of 3 files at r6, 7 of 7 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124636)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`-- commits` line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-NyzkFz537arKBS6FfLK):*
download



_Code quote:_
```
Download
```
___
*[`pkg/cmd/roachtest/tests/util.go` line 272 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-Nz4jCQB0dpkFBd0qeX6:-Nz4jCQB0dpkFBd0qeX7:b-sfolsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d492357c94363ffd1a5463ae0e53b1d85c8f57a/pkg/cmd/roachtest/tests/util.go#L272)):*
> ```Go
> 
> 	// The minimum number of occurances of the statement for it to be included in profiling.
> 	minFrequency := .001
> ```

Isn't this the random sampling frequency, rather than a minimum?
___
*[`pkg/workload/cli/run.go` line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-NyzjG1k5D-eNQVW250z:-NyzjG1k5D-eNQVW251-:bb7mqkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/931803248dcf37d123b1dad4da011f59dcb93809/pkg/workload/cli/run.go#L79)):*
> ```Go
> 
> // individualOperationReceiverAddr is the address we send individual latency
> // measurements to. By default it sends the operations to poer 12345 on
> ```

port
___
*[`pkg/workload/histogram/histogram.proto` line 17 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-Nz4h4ZL4kDV96AD8Li1:-Nz4h4ZL4kDV96AD8Li2:b-g5khzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5620bfaa07c70ed68dafd0ddd459245aede8c96b/pkg/workload/histogram/histogram.proto#L17)):*
> ```proto
> message Latency {
>   string operation = 1;
>   uint32 duration = 2;
> ```

It would be worth commenting the duration here, or naming the duration in the unit used e.g.`duration_nanos`

**Review by andrewbaptist — COMMENTED** [review]
Sounds good, I added a utility method for this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-:-O-hQi55Dml1i-OOVloS:bbbxhyk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-NyzkFz537arKBS6FfLK):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

download
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/util.go` line 272 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-Nz4jCQB0dpkFBd0qeX6:-O-hJCSv3rv9hxbDNsuj:b-1rn41i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d492357c94363ffd1a5463ae0e53b1d85c8f57a/pkg/cmd/roachtest/tests/util.go#L272)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Isn't this the random sampling frequency, rather than a minimum?
</blockquote></details>

Yes - updated
___
*[`pkg/workload/cli/run.go` line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-NyzjG1k5D-eNQVW250z:-O-hQdMaBB4FT5qKyDXI:b5jbds) ([raw file](https://github.com/cockroachdb/cockroach/blob/931803248dcf37d123b1dad4da011f59dcb93809/pkg/workload/cli/run.go#L79)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

port
</blockquote></details>

I cleaned up this comment.
___
*[`pkg/workload/histogram/histogram.proto` line 17 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-Nz4h4ZL4kDV96AD8Li1:-O-hLsoB4yUKSpdI-yxh:b31a7as) ([raw file](https://github.com/cockroachdb/cockroach/blob/5620bfaa07c70ed68dafd0ddd459245aede8c96b/pkg/workload/histogram/histogram.proto#L17)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It would be worth commenting the duration here, or naming the duration in the unit used e.g.`duration_nanos`
</blockquote></details>

I changed the type to a standard duration.

**Review by kvoli — APPROVED** [review]
:lgtm: with the header file updated.

> Reviewed 13 of 13 files at r12, 3 of 3 files at r13, 7 of 7 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-:-O1MjGF44V1mKlDIM8L2:be4y0am)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`-- commits` line 70 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1MhobL-9XFHN-j-VhN):*
nit: consider including the full test names in the commit message for searchability.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 38 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1MhvCqEzZr28s1DOFo:-O1MhvCqEzZr28s1DOFp:b-zco4q1) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L38)):*
> ```Go
> 
> // variations specifies the different variations to use.
> // TODO: Add a diagram here.
> ```

nit: TODO(andrewbaptist)
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 47 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1Mi6M-9L6oNGwkV_sd:-O1Mi6M-9L6oNGwkV_se:bm1px9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L47)):*
> ```Go
> // T5: End the test.
> // The latency from T2-T3 is the baseline.
> // The latency is measured from T3-T4 and T4-T5 and compared to the baseline.
> ```

nit: consider adding another sentence comment which describes what the test is trying to accomplish (why).
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 86 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1Mhyk402LBucOdhItP:-O1Mhyk402LBucOdhItQ:b-2mchzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L86)):*
> ```Go
> 
> func (v variations) String() string {
> 	return fmt.Sprintf("seed: %d, fill: %s, validation: %s, perturbation: %s, splits: %d, stable: %d, target: %d, workload: %d, crdb: %d,  lease: %s, udp: %s:%d, nodes: %d, vcpu: %d, disks: %d",
> ```

nit: consider wrapping.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 332 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1MiUGaBnZ9MzyK8ol7:-O1MiUGaBnZ9MzyK8ol8:btyvhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L332)):*
> ```Go
> 	v.startNoBackup(ctx, l, v.cluster.Node(v.targetNode))
> 	// Wait out the time until the store is no longer suspect.
> 	waitDuration(ctx, 11*time.Second)
> ```

Where did 11s come from? Is this based off of liveness heartbeat intervals?
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 361 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1MiddJD4bysqXulpSX:-O1MiddJD4bysqXulpSY:bm8bo0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L361)):*
> ```Go
> 	startTime := timeutil.Now()
> 	l.Printf("draining target node")
> 	v.cluster.Run(ctx, option.WithNodes(v.cluster.Node(v.targetNode)), fmt.Sprintf("./cockroach node drain --self --certs-dir=%s --port={pgport:%d}", install.CockroachNodeCertsDir, v.targetNode))
> ```

nit: consider wrapping, same below.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 380 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1Mik6m01FUANLGKKs6:-O1Mik6m01FUANLGKKs7:b-khropk) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L380)):*
> ```Go
> // waitForRebalanceToStop polls the system.rangelog every second to see if there
> // have been any transfers in the last 5 seconds. It returns once the system
> // stops transferring ranges.
> ```

nit: transferring replicas.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 604 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1Mitre5Ya5APUcmQFR:-O1Mitre5Ya5APUcmQFS:butovc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L604)):*
> ```Go
> const acceptableP999Increase = 3.0 // this can have higher variations and not part of what we are trying to solve short term.
> 
> // isAcceptableChange determines if a change from the baseline is acceptable.
> ```

Nice, showing all the multiples on failure will be helpful and its good that the test is checking across the distribution.
___
*[`pkg/cmd/roachtest/tests/util.go` line 274 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1Mhjai8xMoWM7Tyz36:-O1Mhjai8xMoWM7Tyz37:b-kkesg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/90cde79d9522699c8b1c388061b4837d48d2ff95/pkg/cmd/roachtest/tests/util.go#L274)):*
> ```Go
> 
> 	// The probability that a statement will be included in the profile.
> 	probabilityToInclude := .001
> ```

nit : should this be updated in the prior commit, instead of this one?
___
*[`pkg/workload/histogram/udp_test.go` line 1 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1MhJmrDZB7lZXY3BQ8:-O1MhJmrDZB7lZXY3BQ9:bb6ht39) ([raw file](https://github.com/cockroachdb/cockroach/blob/8631bd9268e837d6ae90679d8e8904a421b9f2b6/pkg/workload/histogram/udp_test.go#L1)):*
> ```Go
> // Copyright 2023 The Cockroach Authors.
> ```

2024

**Review by andrewbaptist — COMMENTED** [review]
Thanks! Updated. I will get this merged later today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-:-O1MoeKs1T94KiptVN0S:b250zhw)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 70 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1MhobL-9XFHN-j-VhN):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider including the full test names in the commit message for searchability.
</blockquote></details>

Done - Also I renamed the prefix of the tests from hitless to perturbation.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 38 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1MhvCqEzZr28s1DOFo:-O1MpLNP0Qy3_QrAvEaG:bk8evqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L38)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: TODO(andrewbaptist)
</blockquote></details>

Done (and fixed the other todos as well)
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 86 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1Mhyk402LBucOdhItP:-O1Mr4L50_oYRJ8EujbQ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L86)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider wrapping.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 332 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1MiUGaBnZ9MzyK8ol7:-O1Mr54NEtlw36z4FDtK:b-jcsqmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L332)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Where did 11s come from? Is this based off of liveness heartbeat intervals?
</blockquote></details>

I added a comment on this.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 361 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1MiddJD4bysqXulpSX:-O1Mr6h712vjGGmxZmHd:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L361)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider wrapping, same below.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 380 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1Mik6m01FUANLGKKs6:-O1Mr7R18GfTVDHSeTTG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L380)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: transferring replicas.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 604 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1Mitre5Ya5APUcmQFR:-O1Mr8Pw9XC0P10AY6fA:bdr8j95) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a184f899da7f16e8eff4fdb22362e63ea668c2/pkg/cmd/roachtest/tests/admission_control_latency.go#L604)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Nice, showing all the multiples on failure will be helpful and its good that the test is checking across the distribution.
</blockquote></details>

Right! Originally I was just showing the first failure and it didn't have enough context.
___
*[`pkg/cmd/roachtest/tests/util.go` line 274 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1Mhjai8xMoWM7Tyz36:-O1MrSiECFnwF2JmXPmq:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/90cde79d9522699c8b1c388061b4837d48d2ff95/pkg/cmd/roachtest/tests/util.go#L274)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit : should this be updated in the prior commit, instead of this one?
</blockquote></details>

Fixed
___
*[`pkg/workload/histogram/udp_test.go` line 1 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/124636#-O1MhJmrDZB7lZXY3BQ8:-O1Ms0tX7MseIe-ynDHi:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8631bd9268e837d6ae90679d8e8904a421b9f2b6/pkg/workload/histogram/udp_test.go#L1)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

2024
</blockquote></details>

Done

**Comment by andrewbaptist** [comment]
@srosenberg This is the set of tests that measure the latency impacts from different perturbations.

**Comment by andrewbaptist** [comment]
TFTR!

bors r=kvoli

**Pull request merged**
