### PR TITLE
kv: don't update transaction proto directly from heartbeat loop

### LINKED ISSUE #35144: roachtest: interleavedpartitioned failed
SHA: https://github.com/cockroachdb/cockroach/commits/46d1ab4c06edfd37d875114972c55b44105acd83

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=interleavedpartitioned PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1147903&tab=buildLog

```
The test failed on master:
	cluster.go:1226,interleavedpartitioned.go:71,interleavedpartitioned.go:133,test.go:1211: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1147903-interleavedpartitioned:7 -- ./workload init interleavedpartitioned --east-zone-name us-east4-b --west-zone-name us-west1-b --central-zone-name us-central1-a --drop --locality east --init-sessions 1000 returned:
		stderr:
		
		stdout:
		Error: could not create table: queries: pq: invalid foreign key: missing table=53 index=1: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_ABORT_SPAN): "sql txn" id=7758e727 key=/Table/SystemConfigSpan/Start rw=true pri=0.02954844 stat=ABORTED epo=0 ts=1550826919.855744662,0 orig=1550826919.855744662,0 max=1550826920.355744662,0 wto=false seq=5
		Error:  exit status 1
		: exit status 1

```

### LINKED ISSUE #39652: teamcity: failed test: TestConcurrentRaftSnapshots
The following tests appear to have failed on master (testrace): TestConcurrentRaftSnapshots

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestConcurrentRaftSnapshots).

[#1437952](https://teamcity.cockroachdb.com/viewLog.html?buildId=1437952):

```
TestConcurrentRaftSnapshots
...iled: result is ambiguous (server shutdown)
I190814 05:35:42.953318 100587 internal/client/txn.go:619  async rollback failed: node unavailable; try another peer
W190814 05:35:42.938309 98532 storage/store.go:1535  [s2,r1/2:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
I190814 05:35:42.954053 100529 util/stop/stopper.go:542  quiescing; tasks left:
1      mtc send
I190814 05:35:42.955682 100417 internal/client/txn.go:619  async rollback failed: result is ambiguous (server shutdown)
W190814 05:35:42.957766 98877 storage/store.go:1535  [s4,r1/4:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
I190814 05:35:42.977813 100489 internal/client/txn.go:619  async rollback failed: result is ambiguous (server shutdown)
W190814 05:35:43.001811 98685 storage/store.go:1535  [s3,r1/3:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
W190814 05:35:43.017634 99383 storage/raft_transport.go:294  unable to accept Raft message from (n4,s4):?: no handler registered for (n1,s1):?
W190814 05:35:43.046216 99309 storage/store.go:3547  [s4] raft error: node 1 claims to not contain store 1 for replica (n1,s1):?: store 1 was not found
W190814 05:35:43.046671 99364 storage/raft_transport.go:620  while processing outgoing Raft queue to node 1: store 1 was not found:
W190814 05:35:43.049448 98877 storage/store.go:1535  [s4,r1/4:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
W190814 05:35:43.050723 98407 gossip/gossip.go:1522  [n1] first range unavailable; trying remaining resolvers
I190814 05:35:43.070898 100668 gossip/client.go:124  [n1] started gossip client to 127.0.0.1:36661
W190814 05:35:43.128152 98685 storage/store.go:1535  [s3,r1/3:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
W190814 05:35:43.187793 99157 gossip/gossip.go:1522  [n5] first range unavailable; trying remaining resolvers
I190814 05:35:43.186614 98623 gossip/client.go:129  [n3] closing client to n1 (127.0.0.1:37147): stopping outgoing client to n1 (127.0.0.1:37147); already have incoming
W190814 05:35:43.204717 98708 gossip/gossip.go:1522  [n3] first range unavailable; trying remaining resolvers
I190814 05:35:43.210250 100654 gossip/client.go:124  [n5] started gossip client to 127.0.0.1:37147
I190814 05:35:43.225293 100714 gossip/client.go:124  [n3] started gossip client to 127.0.0.1:36977
W190814 05:35:43.229673 98877 storage/store.go:1535  [s4,r1/4:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
I190814 05:35:43.414295 100528 util/stop/stopper.go:542  quiescing; tasks left:
10     rpc heartbeat
I190814 05:35:43.417655 100528 util/stop/stopper.go:542  quiescing; tasks left:
9      rpc heartbeat
W190814 05:35:43.419049 99582 storage/raft_transport.go:620  while processing outgoing Raft queue to node 3: rpc error: code = Unavailable desc = transport is closing:
I190814 05:35:43.428275 100528 util/stop/stopper.go:542  quiescing; tasks left:
8      rpc heartbeat
W190814 05:35:43.429368 99273 storage/raft_transport.go:620  while processing outgoing Raft queue to node 1: EOF:
W190814 05:35:43.430436 100122 storage/raft_transport.go:620  while processing outgoing Raft queue to node 4: rpc error: code = Canceled desc = grpc: the client connection is closing:
W190814 05:35:43.432401 98428 gossip/gossip.go:1517  [n2] no incoming or outgoing connections
W190814 05:35:43.432661 99242 storage/raft_transport.go:620  while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = grpc: the client connection is closing:
W190814 05:35:43.440940 98827 gossip/gossip.go:1517  [n4] no incoming or outgoing connections
    client_raft_test.go:1119: change replicas of r1 failed: TransactionStatusError: client already committed or rolled back the transaction. Trying to execute: EndTransaction(commit:true) [/Min] (REASON_UNKNOWN)




```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #39661: teamcity: failed test: TestConcurrentRaftSnapshots
The following tests appear to have failed on master (testrace): TestConcurrentRaftSnapshots

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestConcurrentRaftSnapshots).

[#1438837](https://teamcity.cockroachdb.com/viewLog.html?buildId=1438837):

```
TestConcurrentRaftSnapshots
...to all 4 replicas failed; last error: (err: node unavailable; try another peer) <nil>
W190814 14:36:22.952605 103654 internal/client/txn.go:509  [liveness-hb] failure aborting transaction: node unavailable; try another peer; abort caused by: node unavailable; try another peer
W190814 14:36:22.953295 103654 storage/node_liveness.go:484  [liveness-hb] failed node liveness heartbeat: node unavailable; try another peer
I190814 14:36:22.972668 105719 internal/client/txn.go:619  async rollback failed: node unavailable; try another peer
W190814 14:36:22.975256 103477 storage/store.go:1535  [s1,r1/1:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
W190814 14:36:22.975718 103973 storage/store.go:1535  [s4,r1/4:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
I190814 14:36:22.977749 105566 internal/client/txn.go:619  async rollback failed: failed to send RPC: sending to all 4 replicas failed; last error: (err: node unavailable; try another peer) <nil>
W190814 14:36:22.989950 103738 storage/store.go:1535  [s3,r1/3:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
W190814 14:36:23.035861 103738 storage/store.go:1535  [s3,r1/3:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
W190814 14:36:23.040239 103601 storage/store.go:1535  [s2,r1/2:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
W190814 14:36:23.052669 103973 storage/store.go:1535  [s4,r1/4:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
W190814 14:36:23.158153 103973 storage/store.go:1535  [s4,r1/4:/M{in-ax}] could not gossip first range descriptor: node unavailable; try another peer
I190814 14:36:23.417779 105685 util/stop/stopper.go:542  quiescing; tasks left:
12     rpc heartbeat
I190814 14:36:23.419183 105685 util/stop/stopper.go:542  quiescing; tasks left:
11     rpc heartbeat
W190814 14:36:23.423125 104049 gossip/gossip.go:1517  [n5] no incoming or outgoing connections
I190814 14:36:23.440370 105685 util/stop/stopper.go:542  quiescing; tasks left:
10     rpc heartbeat
W190814 14:36:23.442608 105064 storage/raft_transport.go:620  while processing outgoing Raft queue to node 4: rpc error: code = Canceled desc = grpc: the client connection is closing:
W190814 14:36:23.444194 104677 storage/raft_transport.go:620  while processing outgoing Raft queue to node 3: rpc error: code = Canceled desc = grpc: the client connection is closing:
W190814 14:36:23.444518 105701 storage/raft_transport.go:620  while processing outgoing Raft queue to node 5: rpc error: code = Canceled desc = grpc: the client connection is closing:
W190814 14:36:23.450638 103653 gossip/gossip.go:1517  [n2] no incoming or outgoing connections
W190814 14:36:23.453525 104389 storage/raft_transport.go:620  while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = grpc: the client connection is closing:
W190814 14:36:23.457033 103696 gossip/gossip.go:1517  [n3] no incoming or outgoing connections
W190814 14:36:23.457366 104320 storage/raft_transport.go:620  while processing outgoing Raft queue to node 1: rpc error: code = Unavailable desc = transport is closing:
W190814 14:36:23.458003 104008 gossip/gossip.go:1517  [n4] no incoming or outgoing connections
W190814 14:36:23.458338 104471 storage/raft_transport.go:620  while processing outgoing Raft queue to node 1: rpc error: code = Canceled desc = grpc: the client connection is closing:
I190814 14:36:23.461581 105685 util/stop/stopper.go:542  quiescing; tasks left:
6      rpc heartbeat
I190814 14:36:23.462412 105685 util/stop/stopper.go:542  quiescing; tasks left:
5      rpc heartbeat
    client_raft_test.go:1119: change replicas of r1 failed: TransactionStatusError: client already committed or rolled back the transaction. Trying to execute: EndTransaction(commit:true) [/Min] (REASON_UNKNOWN)




```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #39652.
Fixes #39661.
Fixes #35144.

This commit fixes the referenced issues by eliminating the practice of updating
the transaction coordinator's proto directly from its heartbeat loop. This was
problematic because of the race described in
https://github.com/cockroachdb/cockroach/blob/dc3686f79b3750500efaff7092c81a3e5ce6d02c/pkg/kv/txn_interceptor_heartbeater.go#L357-L364

The heartbeat loop doesn't know if it's racing with an EndTransaction request
and it could incorrectly interpret a missing transaction record if it is. The
safest thing to do is to limit the path in which it informs the TxnCoordSender
of updates.

This limits the responsibility of the heartbeat loop. Its job is now
only to:
1. update the transaction record to maintain liveness
2. eagerly clean up a transaction if it is found to be aborted
3. inform the transaction coordinator about an aborted transaction
   record IF the transaction coordinator is continuing to send requests
   through the interceptor.

Notably, the heartbeat loop no longer blindly updates the transaction
coordinator's transaction proto. There wasn't a strong reason for it to be able
to do so, especially now that we no longer push transactions or ratchet their
priority frequently. Moreover, even if those were still frequent occurrences,
updating the proto from the heartbeat loop prevented usual restart handling from
being used. For instance, doing so might prevent us from refreshing the
transaction. All in all, allowing this didn't seem worth the complexity.

This commit also includes some cleanup. For instance, it removes a confusing
dependency where the txnHeartbeater called back into the TxnCoordSender. It also
addresses a longstanding TODO to actually unit test the txnHeartbeater.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39699)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/txn_interceptor_heartbeater.go, line 175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOguVM9FdIgKJO-2Jf:-LmOguVM9FdIgKJO-2Jg:b2suffk) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e34a3535bd6f8476d5f189ec7c8c465bd29f4f/pkg/kv/txn_interceptor_heartbeater.go#L175)):*
> ```Go
> func (h *txnHeartbeater) epochBumpedLocked() {}
> 
> // closeLocked is part of the txnInteceptor interface.
> ```

txnInterceptor
___
*[pkg/kv/txn_interceptor_heartbeater.go, line 197 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOh0Km6b_jjezrWKRJ:-LmOh0Km6b_jjezrWKRK:b-sh3its) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e34a3535bd6f8476d5f189ec7c8c465bd29f4f/pkg/kv/txn_interceptor_heartbeater.go#L197)):*
> ```Go
> 	case roachpb.COMMITTED:
> 		err = roachpb.NewTransactionCommittedStatusError()
> 	case roachpb.ABORTED:
> ```

If the heartbeat "erroneously" discovers an aborted txn even though it has committed, then we know that before this codepath is hit, the client has already learned that the txn has committed, and so this method should never be called, right? It seems that observing a successful commit/abort should also set the finalizedStatus.
___
*[pkg/kv/txn_interceptor_heartbeater_test.go, line 280 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOi-RP4xh_RKFhLR2d:-LmOi-RP4xh_RKFhLR2e:b-1xtzs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e34a3535bd6f8476d5f189ec7c8c465bd29f4f/pkg/kv/txn_interceptor_heartbeater_test.go#L280)):*
> ```Go
> 	th.mu.Unlock()
> 	waitForHeartbeatLoopToStop(t, &th)
> }
> ```

Check here what happens if a request is sent through the heartbeater.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 469 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOg6lK9lbOdbTfNc_V:-LmOg6lK9lbOdbTfNc_W:b-jlmcj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5beb210905ba0810b338991afb872fa355d34322/pkg/kv/txn_interceptor_pipeliner.go#L469)):*
> ```Go
> 
> 	// Similarly, if the transaction is now finalized, we don't need to
> 	// accurately updated the write tracking.
> ```

update
___
*[pkg/roachpb/data.go, line 986 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOe2gl4ZKM7CaxRJ8k:-LmOe2gm94aPbvqea6yC:bowwki9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b4086552332d9df2a83d3c38144a59c43b1b133/pkg/roachpb/data.go#L986)):*
> ```Go
> 		return
> 	} else if t.ID != o.ID {
> 		log.Warningf(context.Background(), "updating txn %v with different txn %v", t, o)
> ```

Yeah, yikes, I really don't hope to see that one. How burdensome would it be to return an error from `Update`? Not suggesting to do that now.
___
*[pkg/sql/distsql_running_test.go, line 48 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOiGnB1msYHXvpG8aB:-LmOiGnB1msYHXvpG8aC:b-imae4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e34a3535bd6f8476d5f189ec7c8c465bd29f4f/pkg/sql/distsql_running_test.go#L48)):*
> ```Go
> func TestDistSQLRunningInAbortedTxn(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	t.Skip(`WIP: need to figure out what to do with GetTxnCoordMetaOrRejectClient.
> ```

Beats me. Who knows this these days? @jordanlewis?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39699)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, @nvanbenschoten, @tbg, and @yuzefovich)

___
*[pkg/sql/distsql_running_test.go, line 48 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOiGnB1msYHXvpG8aB:-LmboaaW7eX6lUQOyC2R:b-7xcgmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e34a3535bd6f8476d5f189ec7c8c465bd29f4f/pkg/sql/distsql_running_test.go#L48)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Beats me. Who knows this these days? @jordanlewis?
</blockquote></details>

@asubiotto or @yuzefovich would be a good candidate to deal with this. @andreimatei would probably know whether or not this is actually important. I would imagine that it's important judging by the comment, no?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39699)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, @nvanbenschoten, @tbg, and @yuzefovich)

___
*[pkg/roachpb/data.go, line 986 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOe2gl4ZKM7CaxRJ8k:-Lmfkw91-5nAqi-KaRdw:baxieik) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b4086552332d9df2a83d3c38144a59c43b1b133/pkg/roachpb/data.go#L986)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yeah, yikes, I really don't hope to see that one. How burdensome would it be to return an error from `Update`? Not suggesting to do that now.
</blockquote></details>

how about crashing?
___
*[pkg/sql/distsql_running_test.go, line 48 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOiGnB1msYHXvpG8aB:-LmfluJR6nUi79Fp6hMX:b-hxcd1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e34a3535bd6f8476d5f189ec7c8c465bd29f4f/pkg/sql/distsql_running_test.go#L48)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

@asubiotto or @yuzefovich would be a good candidate to deal with this. @andreimatei would probably know whether or not this is actually important. I would imagine that it's important judging by the comment, no?
</blockquote></details>

I don't think it's important :P
I believe the thing that does not work is sending a flow for execution with an aborted txn proto in it. As long as we don't do that, it's otherwise ok to start flows in transactions that are (unbeknownst to the flow) aborted.

So, I believe the call site to this function should remain; we should protect against sending out flows in aborted txns just like the `TxnCoordSender` rejects requests once the txn is known to be aborted.
This test should find a way to test that. If we keep the heartbeater's information contained to the heartbeater, then the way the TCS finds out about the aborted txn has to be through a different request.

I know we've talked about this, but now that I think about it again... Would it be bad for the TCS to reach into the heartbeater when deciding whether to "reject a client" or not (in addition to checking the proto status)? Or the opposite - the heartbeater notifying the TCS through some channel (another, narrower channel then the proto, since that channel proved troublesome)?
Cause it doesn't seem bad to me now, and it would keep this test working :P

**Review by nvb — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-:-LmoHih64p0GlzwenEB6:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @tbg, and @yuzefovich)

___
*[pkg/kv/txn_interceptor_heartbeater.go, line 175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOguVM9FdIgKJO-2Jf:-Lmkd6Ab3zzRxx6Ab44c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e34a3535bd6f8476d5f189ec7c8c465bd29f4f/pkg/kv/txn_interceptor_heartbeater.go#L175)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

txnInterceptor
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_heartbeater.go, line 197 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOh0Km6b_jjezrWKRJ:-LmkdCkL3Hh1HNB-G8og:b-skkf7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e34a3535bd6f8476d5f189ec7c8c465bd29f4f/pkg/kv/txn_interceptor_heartbeater.go#L197)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

If the heartbeat "erroneously" discovers an aborted txn even though it has committed, then we know that before this codepath is hit, the client has already learned that the txn has committed, and so this method should never be called, right? It seems that observing a successful commit/abort should also set the finalizedStatus.
</blockquote></details>

That's true, but I don't think this field should make any attempt at determining the real finalized status of the transaction. Instead, it should represent the finalized state of the last heartbeat request and let the txn coord sender remain the source of truth on this matter.

I added more words to the field's comment.

EDIT: in fact, I removed this entire check. See below.
___
*[pkg/kv/txn_interceptor_heartbeater_test.go, line 280 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOi-RP4xh_RKFhLR2d:-Lmkimb56XCVvv_y0M_M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e34a3535bd6f8476d5f189ec7c8c465bd29f4f/pkg/kv/txn_interceptor_heartbeater_test.go#L280)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Check here what happens if a request is sent through the heartbeater.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_pipeliner.go, line 469 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOg6lK9lbOdbTfNc_V:-Lmkj0NX7JbBDIsPLppv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5beb210905ba0810b338991afb872fa355d34322/pkg/kv/txn_interceptor_pipeliner.go#L469)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

update
</blockquote></details>

Done.
___
*[pkg/roachpb/data.go, line 986 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOe2gl4ZKM7CaxRJ8k:-LmlDhrID40so6ocnvxj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b4086552332d9df2a83d3c38144a59c43b1b133/pkg/roachpb/data.go#L986)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how about crashing?
</blockquote></details>

Done.
___
*[pkg/sql/distsql_running_test.go, line 48 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-LmOiGnB1msYHXvpG8aB:-LmoGNqj3U7BaLs_mgaK:brvg8uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/59e34a3535bd6f8476d5f189ec7c8c465bd29f4f/pkg/sql/distsql_running_test.go#L48)):*
> I know we've talked about this, but now that I think about it again... Would it be bad for the TCS to reach into the heartbeater when deciding whether to "reject a client" or not (in addition to checking the proto status)? Or the opposite - the heartbeater notifying the TCS through some channel (another, narrower channel then the proto, since that channel proved troublesome)?

I ended up doing this. The heartbeater no longer rejects requests directly. Instead, the finalized status it observes it used in `TxnCoordSender.maybeRejectClientLocked` to conditionally reject clients with `TxnAbortedErrors`.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-:-LmodXzV3mDyRpv6RUzB:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @nvanbenschoten, @tbg, and @yuzefovich)

___
*[pkg/kv/txn_coord_sender.go, line 920 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-Lmocymt3vGrfoJdk1tf:-Lmocymt3vGrfoJdk1tg:b-yleaj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc881680c4fc7dfbc890d9e5b438a1bef00f183/pkg/kv/txn_coord_sender.go#L920)):*
> ```Go
> 		// The transaction proto is in an unexpected state.
> 		return roachpb.NewErrorf(
> 			"(see issue #37866) unexpected txn state: %s; heartbeat observed status: %s",
> ```

I think the bug reference should go away.
We are now bug free.

**Review by nvb — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-:-Lmpvotg5ShQ-DLakbHW:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @asubiotto, @tbg, and @yuzefovich)

___
*[pkg/kv/txn_coord_sender.go, line 920 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39699#-Lmocymt3vGrfoJdk1tf:-LmpvtO28lf8E6f5Op3r:b-dt6r7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc881680c4fc7dfbc890d9e5b438a1bef00f183/pkg/kv/txn_coord_sender.go#L920)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think the bug reference should go away.
We are now bug free.

</blockquote></details>

Done. Somehow I keep forgetting about the bug free thing.

**Pull request merged**
