### PR TITLE
pkg: Split CTAS execution between user txn and SchemaChanger.

### PR DESCRIPTION
**Pull request by adityamaru27**
As a first step in improving the performance and scalability of the `CTAS` command,
(issue #25828) we needed to split the responsibility of creating a new
`TableDescriptor`, and executing the `AS` query to backfill the new table.

While the user txn continues to create and store the new desc, the
execution of the `AS` query has been made async by moving the logic to the
SchemaChanger.

### CODE REVIEW

**Comment by adityamaru27** [comment]
I have realized that some work will be needed to accommodate more general selection clauses. I was under the impression that `selection clause == SELECT stmt` but it can also be a list of values or an existing table as well.

**Review by dt — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27, @dt, and @lucy-zhang)

___
*[pkg/sql/create_table.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38061#-LghhP4t-84x9IAFUto9:-LghhP4u4axCTo2cNWrF:b-s2cd3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f2470f358e638f526a07495bfd11f1805c135a8/pkg/sql/create_table.go#L152)):*
> ```Go
> 	}
> 
> 	if desc.Adding() {
> ```

why delete this? don't we still want it for normal tables? maybe it should just move to the else block?
that said, this code is also just kinda weird -- I don't know why we scan over it after the fact and unset Add when we could just check them as we resolve when we decide to set Add in the first place. Lucy might have some insight here?
___
*[pkg/sql/create_table.go, line 185 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38061#-Lghhm8iBdiRFd8-GADg:-Lghhm8iBdiRFd8-GADh:b-gufez6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e69ca2f73d3fce90bf0ca23640adfb5f5500b9d/pkg/sql/create_table.go#L185)):*
> ```Go
> 
> 	// Ensure desc is in ADD state so that it is queued as a SchemaChange.
> 	desc.State = sqlbase.TableDescriptor_ADD
> ```

this seems like it should be in the if block above?
___
*[pkg/sql/create_table.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38061#-Lghh3ff4AC_ErGoWtvg:-Lghh3ff4AC_ErGoWtvh:b6zhg1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f2470f358e638f526a07495bfd11f1805c135a8/pkg/sql/create_table.go#L212)):*
> ```Go
> 	}
> 
> 	if n.n.As() {
> ```

I wonder: should we keep this code around for CTAS _when run inside an explicit txn_ (and then not put it in ADD)?

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27, @dt, and @lucy-zhang)

___
*[pkg/sql/create_table.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38061#-LghhP4t-84x9IAFUto9:-Lh2BsDZ7unlQun1NLeh:buz6x2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f2470f358e638f526a07495bfd11f1805c135a8/pkg/sql/create_table.go#L152)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

why delete this? don't we still want it for normal tables? maybe it should just move to the else block?
that said, this code is also just kinda weird -- I don't know why we scan over it after the fact and unset Add when we could just check them as we resolve when we decide to set Add in the first place. Lucy might have some insight here?
</blockquote></details>

It might be easier to do it here just because `FindAllReferences` includes both FKs and interleaved tables, but I don't see any reason why we would have to do it here.
___
*[pkg/sql/create_table.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38061#-Lghh3ff4AC_ErGoWtvg:-Lh2E-c0-JgBbFP5aiUj:b-y6eu4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f2470f358e638f526a07495bfd11f1805c135a8/pkg/sql/create_table.go#L212)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I wonder: should we keep this code around for CTAS _when run inside an explicit txn_ (and then not put it in ADD)?
</blockquote></details>

I thought we decided not to support referencing the just-created table later in the same transaction? But I would be in favor of keeping it, if possible.

**Review by adityamaru27 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/sql/create_table.go, line 185 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38061#-Lghhm8iBdiRFd8-GADg:-LhBAs87Bi_gUh5PCY1E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e69ca2f73d3fce90bf0ca23640adfb5f5500b9d/pkg/sql/create_table.go#L185)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

this seems like it should be in the if block above?
</blockquote></details>

Done.

**Review by adityamaru27 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lucy)

___
*[pkg/sql/create_table.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38061#-LghhP4t-84x9IAFUto9:-LhBGnxP2CAhavoOIYxr:bdtp0gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f2470f358e638f526a07495bfd11f1805c135a8/pkg/sql/create_table.go#L152)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

It might be easier to do it here just because `FindAllReferences` includes both FKs and interleaved tables, but I don't see any reason why we would have to do it here.
</blockquote></details>

Moved the check for normal tables to the else clause for now.
@lucy-zhang where do you think is the appropriate place for this check to occur? 
___
*[pkg/sql/create_table.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38061#-Lghh3ff4AC_ErGoWtvg:-LgjG09Y7XX1LoeehZjO:b-4t0kgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f2470f358e638f526a07495bfd11f1805c135a8/pkg/sql/create_table.go#L212)):*
> I wonder: should we keep this code around for CTAS when run inside an explicit txn (and then not put it in ADD)?
Done.

**Comment by adityamaru27** [comment]
One missing piece is the logic related to supporting placeholders in CTAS. Since the SchemaChanger uses its own `InternalPlanner` it cannot rely on the placeholder info which was gathered by the original txn. Currently, I am passing forward `planner.semaCtx.Placeholders` to the `SchemaChanger` but this will fail if the SchemaChange is executed by a node different from the one the original txn runs on.
Still exploring the best way to solve this.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy, and @lucy-zhang)

___
*[pkg/sql/create_table.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38061#-LghhP4t-84x9IAFUto9:-LhprxeF37VR4HfFjFhG:boo13vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f2470f358e638f526a07495bfd11f1805c135a8/pkg/sql/create_table.go#L152)):*
<details><summary><i>Previously, adityamaru27 (Aditya Maru) wrote…</i></summary><blockquote>

Moved the check for normal tables to the else clause for now.
@lucy where do you think is the appropriate place for this check to occur? 
</blockquote></details>

I think keeping it here is fine.

**Review by dt — APPROVED** [review]
> Reviewed 10 of 16 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38061)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by thoszhang — APPROVED** [review]

**Comment by adityamaru27** [comment]
TFTR!
bors r+

**Pull request merged**
