### PR TITLE
docs: fix eventlog.md

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release justification: no code changes

Release note: None

I have no idea where the discrepancy comes from, and more importantly how it got through bors..

### CODE REVIEW

**Review by knz — APPROVED** [review]
huh that is concerning indeed

thanks

**Comment by RaduBerinde** [comment]
Looks like bors runs are failing, slamming this in.

bors n=9999 r=knz

**Comment by RaduBerinde** [comment]
bors p=9999 r=knz

**Comment by RaduBerinde** [comment]
subquery_retry_multinode flake :/

bors r+ p=9999 single on

**Comment by RaduBerinde** [comment]
I did see one build on master pass before the fix: https://teamcity.cockroachdb.com//viewLog.html?buildId=2719447&buildTypeId=Cockroach_MergeToMaster

Maybe whether the file gets regenerated during CI is non-deterministic? FWIW I noticed that `make docs/generated/eventlog.md` doesn't do anything unless I delete the file first.

**Pull request merged**
