### PR TITLE
types: switch from []types.T to []*types.T

### LINKED ISSUE #36909: distsql: Investigating using []*types.T rather than []types.T
This issue came out of discussion on #36710.

There are many distsql-related methods and protobuf structs that construct and pass around `[]types.T`. The `types.T` struct is 128+ bytes, so constantly copying them by value into slices is a potential perf and memory usage concern.

The alternative is using `[]*types.T`. Much of the time, types are singleton instances that are stored once globally (e.g. `types.String`, `types.Int`), so this would reduce memory usage and copying to 8 byte pointer values.

One concern with switching to `[]*types.T` is that the default protobuf `Unmarshal` code would allocate a new object for each `types.T` in a slice, vs. embedding them by value in a single slice. This could be a problem when these slices are passed from machine to machine by distsql.

The only way to know for sure if something should be done here is doing some additional investigation that includes some testing/benchmarking.

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit switches the usage of `[]types.T` to `[]*types.T` throughout
the code base. Previously, we would use a single pointer (i.e.
`*types.T`) and slice of values (i.e. `[]types.T`), and now we will only
be using pointers to types.

The motivation for this change is removing the necessity to copy
`types.T` struct whenever we're adding it into a slice (so possible
performance improvements) and eliminating a potential source of subtle
bugs. One example of a bug that I ran into was the following: when
iterating over a slice of types and passing in a reference to a single
type into another method like this:
```
	for i, t := range types {
		b.b[i] = NewMemColumn(&t, size)
	}
```
we can end up in a "type corruption" scenario if the method captures
that reference, but the iteration would reuse the same `types.T` struct
`t` for all types, so in the end in this example all columns would be
considered of the same type.

All protobuf messages have been updated to operate to contain
`[]*types.T` and `*types.T` as well. We also simplified the protos
to remove `customtype` tag.

The following proto files have been modified:
- `sql/execinfrapb/data.proto`
- `sql/execinfrapb/processors_sql.proto`
- `sql/stats/histogram.proto`
- `sql/sqlbase/structured.proto`
- `sql/types/types.proto`

There was a concern about potential performance hit due to increased
number of allocations during the protobuf unmarshaling, but they
appeared to be unfounded - running TPCC benchmark on 6 node cluster
doesn't show any performance difference.

Fixes: #36909.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I bumped the distsql version, but are there any concerns with backwards-compatibility? Maybe of backups?

**Comment by RaduBerinde** [comment]
> I bumped the distsql version, but are there any concerns with backwards-compatibility?

Did anything actually change on the wire?

**Comment by yuzefovich** [comment]
Hm, maybe there is no change in actual serialized bytes being sent.

There are some difference in `pb.go` files, for example, in `structured.pb.go`:
```
 func (m *Descriptor) XXX_Unmarshal(b []byte) error {
        return m.Unmarshal(b)
@@ -4257,14 +4257,16 @@ func (m *ColumnDescriptor) MarshalTo(dAtA []byte) (int, error) {
        dAtA[i] = 0x10
        i++
        i = encodeVarintStructured(dAtA, i, uint64(m.ID))
-       dAtA[i] = 0x1a
-       i++
-       i = encodeVarintStructured(dAtA, i, uint64(m.Type.Size()))
-       n1, err := m.Type.MarshalTo(dAtA[i:])
-       if err != nil {
-               return 0, err
+       if m.Type != nil {
+               dAtA[i] = 0x1a
+               i++
+               i = encodeVarintStructured(dAtA, i, uint64(m.Type.Size()))
+               n1, err := m.Type.MarshalTo(dAtA[i:])
+               if err != nil {
+                       return 0, err
+               }
+               i += n1
        }
-       i += n1
        dAtA[i] = 0x20
        i++
        if m.Nullable {
```

So this means we don't even need to bump the distsql version and there are no backwards-compatibility concerns?

**Comment by RaduBerinde** [comment]
From that code, it looks like it's equivalent as long as m.Type is not nil, right?

**Comment by yuzefovich** [comment]
Yeah, that's my understanding.

**Comment by yuzefovich** [comment]
I'll factor out important changes in separate commits in a few minutes.

**Comment by yuzefovich** [comment]
I extracted the important changes to protobufs into two separate commits (one of each is in a separate PR) and all remaining changes are in the third commit. I also removed the bump to distsql version since that doesn't seem necessary.

**Comment by yuzefovich** [comment]
Some manual testing confirms that the cluster behaves well in mixed-version state (i.e. one node running master, one node running master + this PR), so the bump to distsql appears to be unnecessary.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48279)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/execinfrapb/data.proto, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48279#-M6UQltF8ZCnwNHVqjzo:-M6UQltF8ZCnwNHVqjzp:bdbat20) ([raw file](https://github.com/cockroachdb/cockroach/blob/a481ee62aba2ca146c3c90155f393beaa591ddda/pkg/sql/execinfrapb/data.proto#L130)):*
> ```protobuf
> 
>   // Schema for the streams entering this synchronizer.
>   repeated sql.sem.types.T column_types = 4 [(gogoproto.nullable) = false];
> ```

Why are we removing the `nullable` property? As far as I understand, I think we want to keep it.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48279)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/execinfrapb/data.proto, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48279#-M6UQltF8ZCnwNHVqjzo:-M6VE3cK4rg3u0bZU_vw:b-dh5oii) ([raw file](https://github.com/cockroachdb/cockroach/blob/a481ee62aba2ca146c3c90155f393beaa591ddda/pkg/sql/execinfrapb/data.proto#L130)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why are we removing the `nullable` property? As far as I understand, I think we want to keep it.
</blockquote></details>

I was also confused by this a bit. When reading the docs, I thought `nullable` determines whether the "whole" field could be nullable (i.e. `column_types` in this case), but if we do keep `nullable`, then we get this in the generated proto code:
```
	ColumnTypes []types.T `protobuf:"bytes,4,rep,name=column_types,json=columnTypes" json:"column_types"`
```
which is not what we want. I'm guessing that the usage of `repeated` changes the meaning of `nullable`.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48279#-:-M6Ziu-1AR8zyUx-gWi5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
