### PR TITLE
sql: make jobs that involve dropping enum values cancellable

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, all type schema change jobs were non-cancellable. In 20.2
these jobs were purely metadata operations that completed fairly
quickly. With the introduction of `ALTER TYPE ... DROP VALUE`, which can
take an arbitrarily long time to validate type usages, this no longer
holds true. To that effect, this patch marks all type schema change jobs
which include a `DROP VALUE` in them as cancellable.

Release justification: Low risk change to exisitng functionality.
Release note (sql change): TYPE SCHEMA CHANGE jobs which include a DROP
VALUE in them are now cancellable. All other jobs remain non-cancellable.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61663)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/type_change.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ51r_4WVDYmkEMFai:-MVJ51r_4WVDYmkEMFaj:b-qlfh2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change.go#L123)):*
> ```Go
> 		if err := job.SetNonCancelable(ctx, p.txn,
> 			func(ctx context.Context, nonCancelable bool) bool {
> 				// If the job is already non-cancelable, then it should stay as such
> ```

hmm i might be getting confused by the number of negations here, but shouldn't the comment say "If the job is already NOT non-cancelable..." ? or "is already cancelable..."
___
*[pkg/sql/type_change.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ-Kx2-kZS9ecl4jV8:-MVJ-Kx2-kZS9ecl4jV9:b-r76i4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change.go#L149)):*
> ```Go
> 			// Type change jobs in general are not cancelable, unless they include
> 			// a transition that drops an enum member.
> 			NonCancelable: !beingDropped,
> ```

this is an unrelated gripe to your PR, since it looks like it's been this way for a while, but it always is confusing to me when a boolean variable name has a negation _inside_ the name: now we have to read this as "NOT cancelable is assigned to the value of `NOT beingDropped`" ... same as "canceltable is assigned to the value of `beingDropped`"

anyway just complaining -- doesn't seem like the time to change this now :) 
___
*[pkg/sql/type_change_test.go, line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ0Uy72PSQ2hJnOhLP:-MVJ0Uy72PSQ2hJnOhLQ:beaocse) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change_test.go#L479)):*
> ```Go
> 		desc        string
> 		query       string
> 		cancellable bool
> ```

nit: earlier in the code it's spelled "cancelable" and here it is "cancellable". i dont actually know which is correct hahah
___
*[pkg/sql/type_change_test.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ3AVN7jMSBa6hXmB7:-MVJ3AVO2wDAKYRK4WtS:b-lfxw3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change_test.go#L516)):*
> ```Go
> 			typeSchemaChangeStarted := make(chan struct{})
> 			block := make(chan struct{})
> 			finished := make(chan struct{})
> ```

i wonder if it's a bit more readable by using `WaitGroup`s rather than raw channels-- what do you think? i'm feeling that since it seems more declarative to call the `Wait()` and `Done()` functions but this could just be my preference
___
*[pkg/sql/type_change_test.go, line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ1LKN6VKK-RAuJZnt:-MVJ1LKN6VKK-RAuJZnu:bisvefk) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change_test.go#L555)):*
> ```Go
> 
> 			if !tc.cancellable && !testutils.IsError(err, "not cancelable") {
> 				t.Fatalf("expected type schema change job to be not cancellable; found %v ", err)
> ```

nit: altered spellings here too

**Review by arulajmani — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-:-MVJNRa7-V6UOvm69U_p:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[pkg/sql/type_change.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ51r_4WVDYmkEMFai:-MVJJD6WCvkHfFuok1xX:b-ytq42h) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change.go#L123)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hmm i might be getting confused by the number of negations here, but shouldn't the comment say "If the job is already NOT non-cancelable..." ? or "is already cancelable..."
</blockquote></details>

ugh you're right, my bad, fixed. 
___
*[pkg/sql/type_change.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ-Kx2-kZS9ecl4jV8:-MVJIkdD6_3ZCJzknrpP:b-9lz4a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change.go#L149)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is an unrelated gripe to your PR, since it looks like it's been this way for a while, but it always is confusing to me when a boolean variable name has a negation _inside_ the name: now we have to read this as "NOT cancelable is assigned to the value of `NOT beingDropped`" ... same as "canceltable is assigned to the value of `beingDropped`"

anyway just complaining -- doesn't seem like the time to change this now :) 
</blockquote></details>

I hear you, I'm not too thrilled about this thing either :) 

Doubt this can ever change though, considering this proto is written to the jobs table.
___
*[pkg/sql/type_change_test.go, line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ0Uy72PSQ2hJnOhLP:-MVJJQo84r1qR56bi0B5:b-5oveo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change_test.go#L479)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: earlier in the code it's spelled "cancelable" and here it is "cancellable". i dont actually know which is correct hahah
</blockquote></details>

Google tells me that both are correct, though "cancellable" is the more common spelling. I think I defaulted to cancelable earlier, as that's what the proto field was called, but I reverted back to the more "natural" spelling here. I can switch it here to be more in line with the proto, though something about seeing "cancelable" bothers me.
___
*[pkg/sql/type_change_test.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ3AVN7jMSBa6hXmB7:-MVJN7AV0E8M9rXm7zpj:b-5wi36k) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change_test.go#L516)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i wonder if it's a bit more readable by using `WaitGroup`s rather than raw channels-- what do you think? i'm feeling that since it seems more declarative to call the `Wait()` and `Done()` functions but this could just be my preference
</blockquote></details>

I don't have a strong preference, switched it to use WaitGroups.

**Review by rafiss — APPROVED** [review]
lgtm!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-:-MVKCk2P-GKGcp2y6urd:b-nzoorr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[pkg/sql/type_change_test.go, line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ0Uy72PSQ2hJnOhLP:-MVKCPDSE9aGcwoz5fQE:bheah8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change_test.go#L479)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Google tells me that both are correct, though "cancellable" is the more common spelling. I think I defaulted to cancelable earlier, as that's what the proto field was called, but I reverted back to the more "natural" spelling here. I can switch it here to be more in line with the proto, though something about seeing "cancelable" bothers me.
</blockquote></details>

lol thank you for embarking i=on this journey for me
___
*[pkg/sql/type_change_test.go, line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-MVJ3AVN7jMSBa6hXmB7:-MVKCeoa7W1qWMpBCUME:bx7gjui) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f066396b42c377d76818b7f5a1abbf60e940dc/pkg/sql/type_change_test.go#L516)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't have a strong preference, switched it to use WaitGroups. 
</blockquote></details>

i do find the new way easier to understand! thank you

**Review by rafiss — COMMENTED** [review]
note: needs a backport to release-21.1 now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61663#-:-MVKCmJ33PVxtoPJJ9oU:b-5mxp5i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

**Comment by arulajmani** [comment]
Gonna wait for the other one to go in so that I don't bors conflict with myself

**Pull request merged**
