### PR TITLE
opt: increase unknownRowCount

### PR DESCRIPTION
**Pull request by RaduBerinde**
When a table has no stats, we assume it has 1,000 rows. This can be
very bad if the table is large and other tables have stats (which in
practice can happen if the auto stats take a long time on a large
table with no prior stats; we saw this in #39103).

This change increases the unknownRowCount to 1,000,000 rows. Most of
the plans when none of the tables have stats aren't affected much,
with the exception of TPC-H (where we can't expect good perf without
stats anyway).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
This is a proposal - I'd like to hear your thoughts on it.

**Comment by awoods187** [comment]
Do we have any tpc-c comparisons with the change on vs. off? What about or other workloads?

**Review by andy-kimball — COMMENTED** [review]
Seems like we just kick the can down the road. Won't the problem will probably still happen with 1B rows?

It would be nice if we could compile the query with stats only if every table in the query had stats. However, I can't think quite how we'd do that, since we don't know up-front whether they do.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39114#-:-LkiYb6aEfKUsEJbD4H0:bvbj90m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @rytaft)

**Comment by RaduBerinde** [comment]
> Seems like we just kick the can down the road. Won't the problem will probably still happen with 1B rows?

I'm not sure.. It would at least make it a lot less likely in common scenarios.

I have also seen some customers using 2.1 (no stats) having issues with this value (IIRC we had some queries with LIMIT and once the LIMIT hit 500, it switched to a full table scan+sort instead of using an index).

**Comment by rytaft** [comment]
I don't really have any objections to this...

But another idea is that we can determine the default value to use based on the stats for other tables that have already been calculated. For example, the stats cache could maintain an average row count across all tables, and if there are no stats for a given table, we can use the average value instead.

**Comment by RaduBerinde** [comment]
I will close this, given the tepid feedback.

> It would be nice if we could compile the query with stats only if every table in the query had stats. However, I can't think quite how we'd do that, since we don't know up-front whether they do.

Given that it's a (hopefully) rare case, we could set a flag and rebuild everything (using the `CopyAndReplace` infrastructure) at the end.

**Pull request closed without merging**
