### PR TITLE
storage: verify preemptive snapshot metrics

### LINKED ISSUE #7593: storage: test that preemptive snapshots are actually working
See #7468. My current thought is to add per-replica counters for preemptive and normal snapshots which we could examine after initial replication is complete. Anyone have a better idea?

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #7593.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7616)

### CODE REVIEW

**Comment by petermattis** [comment]
@cuongdo We'll want to graph these new metrics on the UI as well, probably along side the existing range events as long as that doesn't get overwhelming. 

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 571 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvOFj95voQLxa6S0Jl:-KLvOFj95voQLxa6S0Jm:1533425072) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/store.go#L571)):*
> ```Go
> 		rangeSnapshotsGenerated:         storeRegistry.Counter("range.snapshots.generated"),
> 		rangeSnapshotsApplied:           storeRegistry.Counter("range.snapshots.applied"),
> 		rangeSnapshotsPreemptiveApplied: storeRegistry.Counter("range.snapshots.preemptive-applied"),
> ```

Currently, `rangeSnapshotsApplied` counts all snapshots while `rangeSnapshotsPreemptiveApplied` counts only preemptive snapshots. I could instead make `rangeSnapshotsApplied` only count non-preemptive snapshots. I'm not sure what the right thing to do from a metrics collection perspective is. @mrtracy? @cuongdo?

---

*[storage/store.go, line 2109 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvO_oTIU43ByJLdTII:-KLvO_oTIU43ByJLdTIJ:-1012072086) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/store.go#L2109)):*
> ```Go
> 			// operation that can be performed on a replica before it is part of the
> 			// raft group.
> 			r.store.metrics.rangeSnapshotsPreemptiveApplied.Inc(1)
> ```

Should there be error counts for the various range operations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-:-KLvOiEex9NsVyLCmurn:-1137256107)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1336 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvR8YupktOJfWPzU3e:-KLvR8YupktOJfWPzU3f:-1038759871) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/client_raft_test.go#L1336)):*
> ```Go
> 		preemptive += r.GetCounter("range.snapshots.preemptive-applied").Count()
> 	}
> 	if generated != applied {
> ```

check that these are non-zero.

---

*[storage/replica_raftstorage.go, line 299 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvQshc0sT5vCijRdqb:-KLvQshc0sT5vCijRdqc:442352567) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/replica_raftstorage.go#L299)):*
> ```Go
> 			case ch <- snapData:
> 			case <-time.After(r.store.ctx.AsyncSnapshotMaxAge):
> 				// If raft decides it doesn't need this snapshot any more (or
> ```

do we want a count of these as well? (or the inverse, above)

---

*[storage/replica_raftstorage.go, line 525 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvR-pRdzWDXSdg4u2F:-KLvR-pRdzWDXSdg4u2G:-261286162) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/replica_raftstorage.go#L525)):*
> ```Go
> 	defer batch.Close()
> 
> 	r.store.metrics.rangeSnapshotsApplied.Inc(1)
> ```

even in the error case?

---

*[storage/store.go, line 571 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvQY_dIC5WYhE1dxPn:-KLvQY_eemOGgCszD_Sk:-115611557) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/store.go#L571)):*
> ```Go
> 		rangeSnapshotsGenerated:         storeRegistry.Counter("range.snapshots.generated"),
> 		rangeSnapshotsApplied:           storeRegistry.Counter("range.snapshots.applied"),
> 		rangeSnapshotsPreemptiveApplied: storeRegistry.Counter("range.snapshots.preemptive-applied"),
> ```

Do you also want `rangeSnapshotsPreemptiveGenerated`?

---

*[storage/store.go, line 2109 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvO_oTIU43ByJLdTII:-KLvQcrmV686FxJjitzm:141397309) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/store.go#L2109)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Should there be error counts for the various range operations?
</details>
It'd be nice to have something more than simple counts for errors, though I don't know how we'd model it given our current tools.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-:-KLvRJmY3wwXlErdiLEL:1417088721)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1336 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvR8YupktOJfWPzU3e:-KLvVxQRdnka2OWpn90y:981282020) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/client_raft_test.go#L1336)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> check that these are non-zero.
</details>
Added a check that `generated` is not equal to zero.

---

*[storage/replica_raftstorage.go, line 299 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvQshc0sT5vCijRdqb:-KLvW0pQ7fRKIe_fKC7Y:1334917062) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/replica_raftstorage.go#L299)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> do we want a count of these as well? (or the inverse, above)
</details>
Yeah, see my other comment about counting errors as well as successes. Would appreciate some thoughts for the metrics folks, @mrtracy and @cuongdo. We currently aren't counting errors for other range operations such as splits and merges. Perhaps we should.

---

*[storage/replica_raftstorage.go, line 525 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvR-pRdzWDXSdg4u2F:-KLvWDHfitARlV-WD6RR:993052115) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/replica_raftstorage.go#L525)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> even in the error case?
</details>
Yeah, I'm not sure about that.

---

*[storage/store.go, line 571 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvQY_dIC5WYhE1dxPn:-KLvWHydHex63Ev2qf9H:1955795051) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/store.go#L571)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Do you also want `rangeSnapshotsPreemptiveGenerated`?
</details>
Maybe. I was mainly motivated by adding a test that preemptive snapshots are being applied. Again, I'd be interested in what @mrtracy and @cuongdo feel should be done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[storage/replica_raftstorage.go, line 299 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvQshc0sT5vCijRdqb:-KLvUSdZ45bz9C1bHE_Y:436442268) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/replica_raftstorage.go#L299)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> do we want a count of these as well? (or the inverse, above)
</details>
I wouldn't add one for now. I think we still need to be cautious about adding too many store-level metrics. 

---

*[storage/replica_raftstorage.go, line 525 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvR-pRdzWDXSdg4u2F:-KLvTkDBKo-FoL50lh_g:28730155) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/replica_raftstorage.go#L525)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> even in the error case?
</details>
The error case currently turns into a panic, but I agree it would be better for this metric to only count successful snapshots. We could introduce a separate error metric when we have a non-panicking error path.

---

*[storage/store.go, line 571 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvOFj95voQLxa6S0Jl:-KLvUeVcVlORkmOq5cwO:-1067789177) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/store.go#L571)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Currently, `rangeSnapshotsApplied` counts all snapshots while `rangeSnapshotsPreemptiveApplied` counts only preemptive snapshots. I could instead make `rangeSnapshotsApplied` only count non-preemptive snapshots. I'm not sure what the right thing to do from a metrics collection perspective is. @mrtracy? @cuongdo?
</details>
The goal of these metrics (aside from testing) is to make sure that non-preemptive snapshots are rare. That currently requires comparing two metrics; it would be better to have the metrics be non-preemptive and total instead of preemptive and total.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-:-KLvWR6akaWBU_5r9X1C:1417088721)*

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 525 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvR-pRdzWDXSdg4u2F:-KLvcdb9APYIkAFw6Awc:-1922425478) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/replica_raftstorage.go#L525)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The error case currently turns into a panic, but I agree it would be better for this metric to only count successful snapshots. We could introduce a separate error metric when we have a non-panicking error path.
</details>
I've moved the metric tracking to the end and added a `typ snapshotType` parameter so that we only increment either `rangeSnapshotsApplied` or `rangeSnapshotsPreemptiveApplied`, but not both.

---

*[storage/store.go, line 571 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvOFj95voQLxa6S0Jl:-KLvcq2EKmTgFBiF6Qsw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/store.go#L571)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The goal of these metrics (aside from testing) is to make sure that non-preemptive snapshots are rare. That currently requires comparing two metrics; it would be better to have the metrics be non-preemptive and total instead of preemptive and total.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1333 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvdeYogfKY-svIijYq:-KLvdeYogfKY-svIijYr:-1243105204) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e43e7f75ee8b4876e38c373089694c259dcaba6/storage/client_raft_test.go#L1333)):*
> ```Go
> 		r := s.Registry()
> 		generated += r.GetCounter("range.snapshots.generated").Count()
> 		applied += r.GetCounter("range.snapshots.applied").Count()
> ```

s/applied/normalApplied/

---

*[storage/client_raft_test.go, line 1334 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvdh8PbQTJn0NM-fDm:-KLvdh8PbQTJn0NM-fDn:-435092480) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e43e7f75ee8b4876e38c373089694c259dcaba6/storage/client_raft_test.go#L1334)):*
> ```Go
> 		generated += r.GetCounter("range.snapshots.generated").Count()
> 		applied += r.GetCounter("range.snapshots.applied").Count()
> 		preemptive += r.GetCounter("range.snapshots.preemptive-applied").Count()
> ```

s/preemptive/preemptiveApplied/

---

*[storage/replica_raftstorage.go, line 661 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvdU3SaiyAhrcBaPu_:-KLvdU3SaiyAhrcBaPua:330294194) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e43e7f75ee8b4876e38c373089694c259dcaba6/storage/replica_raftstorage.go#L661)):*
> ```Go
> 		r.store.metrics.rangeSnapshotsPreemptiveApplied.Inc(1)
> 	default:
> 		panic("not reached")
> ```

paranoid: `log.Warningf("....")`

---

*[storage/store.go, line 571 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvOFj95voQLxa6S0Jl:-KLvdJb7Qk9D-1D4nZgS:1194058150) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/store.go#L571)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Done.
</details>
can you name this `rangeSnapshotsNormalApplied`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[storage/client_raft_test.go, line 1333 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvdeYogfKY-svIijYq:-KLvo4-RFgxNA5fF029s:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e43e7f75ee8b4876e38c373089694c259dcaba6/storage/client_raft_test.go#L1333)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/applied/normalApplied/
</details>
Done.

---

*[storage/client_raft_test.go, line 1334 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvdh8PbQTJn0NM-fDm:-KLvo4LqnL0V8_jT7SHq:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e43e7f75ee8b4876e38c373089694c259dcaba6/storage/client_raft_test.go#L1334)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/preemptive/preemptiveApplied/
</details>
Done.

---

*[storage/replica_raftstorage.go, line 661 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvdU3SaiyAhrcBaPu_:-KLvo7-2TJVZViAfzajz:-1689459562) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e43e7f75ee8b4876e38c373089694c259dcaba6/storage/replica_raftstorage.go#L661)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> paranoid: `log.Warningf("....")`
</details>
And yet this should never ever be reached as it would indicate a programmer error. 

---

*[storage/store.go, line 571 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvOFj95voQLxa6S0Jl:-KLvoJU3Xvn4nmimkREy:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/store.go#L571)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you name this `rangeSnapshotsNormalApplied`?
</details>
Done.

---

*[storage/store.go, line 2109 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvO_oTIU43ByJLdTII:-KLvoXJDzHIGZN3qMG3I:-868454492) ([raw file](https://github.com/cockroachdb/cockroach/blob/427902e031b7b9bd4441a61a6cf5839ae3d2b79e/storage/store.go#L2109)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> It'd be nice to have something more than simple counts for errors, though I don't know how we'd model it given our current tools.
</details>
Per @bdarnell's comment, I'm not going to do anything with errors for the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 661 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvdU3SaiyAhrcBaPu_:-KLvqIwlNLo9kTwpK7S4:-79824363) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e43e7f75ee8b4876e38c373089694c259dcaba6/storage/replica_raftstorage.go#L661)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> And yet this should never ever be reached as it would indicate a programmer error. 
</details>
Right, but that programmer error can occur subsequent to this change. I'd err on the side of not panicking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 661 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvdU3SaiyAhrcBaPu_:-KLvxheOz7nj8hHEqq3_:-1337332726) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e43e7f75ee8b4876e38c373089694c259dcaba6/storage/replica_raftstorage.go#L661)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Right, but that programmer error can occur subsequent to this change. I'd err on the side of not panicking.
</details>
That argument applies to most any panic. And this isn't some convoluted control flow. The caller must have not passed one of `{preemptive,normal}Snapshot`. If we log a warning we could easily ignore that warning during a test and thus have a bug in our snapshot metrics. That seems less desirable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 661 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvdU3SaiyAhrcBaPu_:-KLvzD6rPvgZYQepHVCK:-1483841010) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e43e7f75ee8b4876e38c373089694c259dcaba6/storage/replica_raftstorage.go#L661)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> That argument applies to most any panic. And this isn't some convoluted control flow. The caller must have not passed one of `{preemptive,normal}Snapshot`. If we log a warning we could easily ignore that warning during a test and thus have a bug in our snapshot metrics. That seems less desirable.
</details>
Yeah, that's a fair point. We can return an error here, though.

In general, I think we are greatly overusing panics - I think we should basically never panic, except for cases where things are corrupted and we want to end the process.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica_raftstorage.go, line 661 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616#-KLvdU3SaiyAhrcBaPu_:-KLwDBjV2iYEyU6GcunP:-1704320375) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e43e7f75ee8b4876e38c373089694c259dcaba6/storage/replica_raftstorage.go#L661)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, that's a fair point. We can return an error here, though.
> 
> In general, I think we are greatly overusing panics - I think we should basically never panic, except for cases where things are corrupted and we want to end the process.
</details>
Seems reasonable to panic on some impossible conditions. Data structures come to mind. We certainly shouldn't be panic'ing on user input or data that could be corrupted. Neither is the case here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7616)*

**Pull request merged**
