### PR TITLE
pgwire: allow per-connection control of result buffer size

### PR DESCRIPTION
**Pull request by danhhz**
Recently #32366 added a cluster setting that changes the default pgwire
result buffer size for all future connections. A TODO was left to allow
controlling it on a connection basis and this commit resolves that TODO.

Adding something like "?results_buffer_size=1KiB" to the connection
string will set the pgwire result buffer size for that connection,
overriding the default specified in the cluster setting. Users may want
to set this to a larger value to get more auto-retries or to a smaller
value with the (still experimental) core version of changefeeds.

Also switch the changefeed unit tests to use this instead of the cluster
setting.

Release note (sql change): pgwire result buffer size can now be
controlled on a per-connection basis with the results_buffer_size
connection string param

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
Can't we have a session variable - the thing you set with `SET <foo>=<bar>` (that being the normal way to control session settings)? I believe all session variables can also be specified in the connection string.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34385#-:-LXUZRYpAnbkl5GM5WMG:b-33a2vs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by danhhz** [comment]
Dunno, I've never seen any of this before in my life. I was doing exactly what @knz suggested in https://github.com/cockroachdb/cockroach/pull/32366#pullrequestreview-175711059

> If it was just me I would have went the route of a client status parameter (a new case in parseOptions(), pgwire/server.go), so that the buffer can be set to a different value per session.

Hmm, I looked at making this a new sessionVar. The bit that hooks them to parseOptions depends on a `Set` method being implemented, but I don't see a good way to make them work with a `SET` statement without doing some plumbing.

Anyway, even if that could work, it's a much bigger rabbit hole than I was planning on going down here. This PR is quite straightforward and seems better than what we had before. I'd prefer to stick with it if possible.

**Review by andreimatei — COMMENTED** [review]
> The bit that hooks them to parseOptions depends on a Set method being implemented, but I don't see a good way to make them work with a SET statement without doing some plumbing.

Wouldn't the `set()` just be setting `ConnResultsBufferSize` on some object? Is there some extra difficulty?

Session variables are the way we have for adding this kind of session configuration. That method you're changing that parses the connection string only handles the user name, which I guess is somehow special. I'm very surprised @knz just referred to that connection string parsing method in isolation (particularly since I believe he's done work to unify the handling of connection strings and session variables); maybe he can defend it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34385#-:-LXUm6fQ6kraqku7NuLr:b-7idbdh)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by danhhz** [comment]
All of the Set impls that I spot checked are changing things in SessionData. It looks like conn has access to SessionDefaults but not to SessionData. There is a SessionDefaults inside sessionDataMutator, but it seems like it's supposed to be read-only. SessionArgs seems like the natural candidate for your "Wouldn't the set() just be setting ConnResultsBufferSize on some object" but it's passed around by value everywhere. This is the plumbing issue. Do you have a specific proposal for what I should do here?

@knz can you weigh in on this?

**Review by andreimatei — COMMENTED** [review]
I think the way it's supposed to work is for the `parseOptions` function to put something into `SessionDefaults`, and from there `resetSessionVars` is going to copy them into `SessionData` through the `SessionDataMutator`.
The new variable to be introduced here should behave just like any of the others, for example `SessionData.Database`. Which I believe works like I've described above based on my superficial tracing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34385#-:-LXUxTyeAquUANT6-ECc:b-mkbo8m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by danhhz** [comment]
And how does `(c *conn).maybeFlush` get access to that?

**Review by andreimatei — COMMENTED** [review]
I guess through a new `ClientComm.SetBufferingPolicy(...)` interface method, implemented by the `conn`. And the `SessionDataMutator` would either get access to a `ClientComm` or a callback akin to `sessionFataMutator.applicationNameChanged`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34385#-:-LXV-e1h-lKTVxMQz2-H:b-p901fw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by andreimatei — COMMENTED** [review]
And while this work is very nice on its own, I still think that for the use case of CDC, the SQL layer should get in the business of explicitly flushing results once the initial snapshot is done and new updates arrive to be streamed out (irrespective of any configured buffering).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34385#-:-LXV0GEC8X5kQQPjPyqX:b-8c9v3b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — COMMENTED** [review]
I think we do not have enough bandwidth today to make this a setting that can be customized using SET after a session has started already. In particular there is not enough bandwidth on Dan's part to write all the associated tests and on ours to verify them. Also there's no clear user need (the customers are currently happy customizing this only in the URL.

We may be able to support SET later (and I agree with Andrei that we probably  should) but the risk is too high to do this now. So, please don't. (And therefore, your initial approach with parsing the setting in pgwire is OK.)

Please however add the accessor to retrieve the session var with SHOW (and in introspection). Otherwise it's going to be super hard for users to verify that the setting they pass in the URL was actually accepted by the server.

The rest of the code looks overall good to me. Thank you!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34385#-:-LXV5uDhAOBO5jhgksd7:b-qcgze0)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by andreimatei** [comment]
> Also there's no clear user need

There's no "clear user need" at all, in my opinion; that's why I made the comment about what I think CDC should be doing.

> Please however add the accessor to retrieve the session var with SHOW (and in introspection). 

See, that's what I was afraid off. We like session variables, but we don't like them enough to put in a little bit extra effort to keep them nice. That's how you get spaghetti.

But I won't block anything.

**Review by knz — COMMENTED** [review]
Maybe Dan would be so kind as to file a follow-up "clean up" issue to support SET and place that issue on the incoming list of the sql front-end team. I can have a look at this later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34385#-:-LXV8XQDE3hw4Jp9yRvo:b-bw01v6)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by danhhz** [comment]
Thanks @knz! Update with SHOW support incoming.

> Maybe Dan would be so kind as to file a follow-up "clean up" issue to support SET and place that issue on the incoming list of the sql front-end team. I can have a look at this later.

Happily!

**Comment by danhhz** [comment]
@knz updated with `SHOW` support and filed https://github.com/cockroachdb/cockroach/issues/34423

**Comment by danhhz** [comment]
Thanks for the reviews! @knz I'm going to assume you're off for the night and won't get a chance to check the SHOW revision I added until tomorrow. In the meantime, I'm going to go ahead and merge this to get PM acceptance testing started. Happy to address any issues in a followup.

bors r=knz

**Pull request merged**
