### PR TITLE
generate-test-suites: don't query `pkg/ui` directory for go tests

### LINKED ISSUE #70398: bazel: bug in `build_bazel_rules_nodejs` prevents `make bazel-generate`
`make bazel-generate` has recently started failing:

```
INFO: Repository npm instantiated at:
  /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/WORKSPACE:67:13: in <toplevel>
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:890:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "v", line 786, col
umn 36, in _yarn_install_impl
                is_windows_host = is_windows_os(repository_ctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/common/os_name.bzl", line 65, column 19, in
 is_windows_os
                return os_name(rctx) == OS_NAMES[0]
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/common/os_name.bzl", line 62, column 9, in
os_name
                fail("Unsupported operating system {} architecture {}".format(os_name, arch))
Error in fail: Unsupported operating system freebsd architecture amd64
```

Epic CRDB-8036

### PR DESCRIPTION
**Pull request by rickystewart**
Closes #70398.

Release note: None

### CODE REVIEW

**Review by koorosh — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70836)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rail and @rickystewart)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/70836#-MkhJ5Lg3aj73e83VRBo:-MkhJ5Lg3aj73e83VRBp:bg7igkv) (no related file):*
:lgtm: 

---

**Review by koorosh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70836)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rail)

**Comment by rickystewart** [comment]
bors r=koorosh

**Comment by knz** [comment]
yes I confirm I can now run `make bazel-generate` without error.

**Pull request merged**
