### PR TITLE
build: avoid duplication of GOFLAGS for nightly stress

### LINKED ISSUE #34004: workload/ycsb: package failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/0c7e491a76142a67750649facbce798442f74d25

Parameters:
```
TAGS=
GOFLAGS=-race
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=(unknown) PKG=github.com/cockroachdb/cockroach/pkg/workload/ycsb TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1094320&tab=buildLog

```
github.com/cockroachdb/cockroach/vendor/github.com/kr/pretty
github.com/cockroachdb/cockroach/pkg/util/retry
github.com/cockroachdb/cockroach/pkg/util/stringencoding
github.com/cockroachdb/cockroach/pkg/sql/privilege
github.com/cockroachdb/cockroach/pkg/util/pretty
github.com/cockroachdb/cockroach/pkg/util/ring
github.com/cockroachdb/cockroach/pkg/util/timeofday
github.com/cockroachdb/cockroach/vendor/golang.org/x/text/internal/tag
github.com/cockroachdb/cockroach/vendor/golang.org/x/text/language
github.com/cockroachdb/cockroach/pkg/util/treeprinter
github.com/cockroachdb/cockroach/vendor/github.com/prometheus/client_golang/prometheus
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc
github.com/cockroachdb/cockroach/vendor/golang.org/x/text/internal/colltab
github.com/cockroachdb/cockroach/vendor/golang.org/x/text/collate
github.com/cockroachdb/cockroach/vendor/github.com/prometheus/client_golang/prometheus/graphite
github.com/cockroachdb/cockroach/vendor/github.com/lightstep/lightstep-tracer-go/collectorpb
github.com/cockroachdb/cockroach/vendor/github.com/lightstep/lightstep-tracer-go
github.com/cockroachdb/cockroach/vendor/github.com/Shopify/sarama
github.com/cockroachdb/cockroach/vendor/github.com/openzipkin-contrib/zipkin-go-opentracing
github.com/cockroachdb/cockroach/pkg/util/tracing
github.com/cockroachdb/cockroach/pkg/util/log
github.com/cockroachdb/cockroach/pkg/util/hlc
github.com/cockroachdb/cockroach/pkg/util/protoutil
github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror
github.com/cockroachdb/cockroach/pkg/util/interval
github.com/cockroachdb/cockroach/pkg/util/metric
github.com/cockroachdb/cockroach/pkg/util/ipaddr
github.com/cockroachdb/cockroach/pkg/server/telemetry
github.com/cockroachdb/cockroach/pkg/sql/sessiondata
github.com/cockroachdb/cockroach/pkg/sql/sem/types
github.com/cockroachdb/cockroach/pkg/util/timeutil/pgdate
github.com/cockroachdb/cockroach/pkg/storage/engine/enginepb
github.com/cockroachdb/cockroach/pkg/sql/lex
github.com/cockroachdb/cockroach/pkg/util/encoding
github.com/cockroachdb/cockroach/pkg/util/cache
github.com/cockroachdb/cockroach/pkg/sql/coltypes
github.com/cockroachdb/cockroach/pkg/util/json
github.com/cockroachdb/cockroach/pkg/roachpb
github.com/cockroachdb/cockroach/pkg/util/stop
github.com/cockroachdb/cockroach/pkg/settings/cluster
github.com/cockroachdb/cockroach/pkg/keys
github.com/cockroachdb/cockroach/pkg/security
github.com/cockroachdb/cockroach/pkg/util/mon
github.com/cockroachdb/cockroach/pkg/base
github.com/cockroachdb/cockroach/pkg/internal/client
github.com/cockroachdb/cockroach/pkg/sql/sem/tree
github.com/cockroachdb/cockroach/pkg/sql/sem/transform
github.com/cockroachdb/cockroach/pkg/sql/opt/cat
github.com/cockroachdb/cockroach/pkg/sql/parser
github.com/cockroachdb/cockroach/pkg/config
github.com/cockroachdb/cockroach/pkg/sql/sqlbase
github.com/cockroachdb/cockroach/pkg/sql/exec/types
github.com/cockroachdb/cockroach/pkg/sql/exec/execgen/cmd/execgen
execgen pkg/sql/exec/avg_agg.eg.go
execgen pkg/sql/exec/any_not_null_agg.eg.go
execgen pkg/sql/exec/hashjoiner.eg.go
execgen pkg/sql/exec/distinct.eg.go
execgen pkg/sql/exec/colvec.eg.go
execgen pkg/sql/exec/projection_ops.eg.go
execgen pkg/sql/exec/rowstovec.eg.go
execgen pkg/sql/exec/quicksort.eg.go
execgen pkg/sql/exec/selection_ops.eg.go
execgen pkg/sql/exec/sort.eg.go
execgen pkg/sql/exec/sum_agg.eg.go
go test -race -exec 'stress -maxruns 100 -maxfails 1 -stderr -p 4' -tags ' make x86_64_pc_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=v2.2.0-alpha.20181217-600-g0c7e491" -X "github.com/cockroachdb/cockroach/pkg/build.rev=0c7e491a76142a67750649facbce798442f74d25" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-pc-linux-gnu"  ' -run "." -timeout 0 github.com/cockroachdb/cockroach/pkg/workload/ycsb  -v -args -test.timeout 40m
go test: race flag may be set only once
run "go help test" or "go help testflag" for more information
Makefile:860: recipe for target 'stress' failed
make: *** [stress] Error 2

```

### PR DESCRIPTION
**Pull request by petermattis**
Clear the `GOFLAGS` env variable for the nightly stress invocations. As
of go1.11, `go` interprets that variable and errors out if certain flags
are duplicated in both the environment variable and on the command
line (e.g. `-race`).

Fixes #34004

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Pretty sure this will fix the nightly stress runs. I haven't figured out how to easily fix the underlying problem of specifying `GOFLAGS` in the environment but getting `make` to not pass that to `go`. The various approaches I've tried so far have become overly complex.

**Comment by petermattis** [comment]
Ugh, this isn't quite correct. Hold on.

**Comment by petermattis** [comment]
Ok, I figured out how to do this in the `Makefile` by changing the `xgo` variable. I've also changed it so that this variable cannot be set from the command line (it is internal to the `Makefile`). This is ready for a look.

**Review by jordanlewis — APPROVED** [review]
:lgtm: though I'm not confident that this won't break other things that use that `xgo` definition... wouldn't this have problems if someone expects `GOFLAGS` to properly work in those cases? Perhaps we don't have any such cases so it doesn't matter.

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34013#-:-LWIAxUh-F8CqqjkLjkd:b6mo7ym)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34013#-:-LWIBKWr0uKBNZetTv6W:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Pull request merged**
