### PR TITLE
builtins: fix pg_function_is_visible to work with UDFs

### LINKED ISSUE #89546: sql: pg_function_is_visible is not correct for UDFs
**Describe the problem**

This builtin was added in 2019. The assumptions from back then no longer hold. See:

https://github.com/cockroachdb/cockroach/blob/1ca61aee52cd32c6cada5de981058d0026cfa7eb/pkg/sql/sem/builtins/pg_builtins.go#L1178-L1195

**Expected behavior**
Match the Postgres implementation, and take into account the schemas on the search path. Maybe it also takes into account privileges?

Also, the current implementation is needlessly slow. I hope we can improve the speed of it too.

**Environment:**
 - CockroachDB v22.2.0-beta

cc @chengxiong-ruan @mgartner 

Jira issue: CRDB-20297

Epic CRDB-19147

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/89546

### builtins: fix pg_function_is_visible to work with UDFs

Release note (bug fix): The pg_function_is_visible function now
correctly reports visibility based on the functions that are visible on
the current search_path.

### builtins: use pg_type to implement pg_type_is_visible

This saves us from having to maintain the old code, which I personally
found to be a bit hard to work with. Using the internal executor like
this should be faster than it used to be, since there is an index on
pg_type(oid) that will avoid any lookups for builtin types.

### sessiondata: consolidate logic for searching the search_path

### CODE REVIEW

**Review by e-mbrown — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90657#-:-NJ61V889ez31k1TJOAK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
tftr!

bors r=e-mbrown

**Comment by rafiss** [comment]
bors r=e-mbrown

**Comment by rafiss** [comment]
bors r=e-mbrown

**Pull request merged**
