### PR TITLE
bulk: send splits when running as a tenant as well

### LINKED ISSUE #74856: bulk: enable split and scatter calls in bulk processes in tenants
Once the initial change in #74389 lands (e.g. in https://github.com/cockroachdb/cockroach/pull/74835), Bulk code which explicitly avoided calling the previously disallowed APIs should be updated to remove those extra cases and start sending those calls, behind a cluster version gate or handling the errors in the mixed version case.

Epic CRDB-11739

### PR DESCRIPTION
**Pull request by dt**
Fixes #74856.

### CODE REVIEW

**Comment by dt** [comment]
(will need to wait for https://github.com/cockroachdb/cockroach/pull/74835 to merge first)

**Comment by dt** [comment]
Also, I did think about it and I don't think we need a cluster version check in this for #74835 since we have an invariant that tenant pod binary version is always <= host binary version.

**Comment by dt** [comment]
Okay, rebased on the now merged #74835 and ready to go

**Review by adityamaru — APPROVED** [review]

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
