### PR TITLE
sql: make interfaces for string and timestamp Datums

### PR DESCRIPTION
**Pull request by eisenstatdavid**
This refactoring change anticipates future PRs that improve overload
resolution for generic functions (including the elimination of the
duplicate function definitions for DTimestamp and DTimestampTZ) and
introduce DCollatedString.

Renames DString to DUTF8String and introduces the interface DString,
which will be used to operate generically on
DUTF8String/DCollatedString.

Renames DTimestamp to DTimestampNoTZ and introduces the interface
DTimestamp, which will be used to operate generically on
DTimestampTZ/DTimestampNoTZ.

Fixes a panic arising from mixed-type comparisons of
DTimestamp/DTimestampTZ inside tuples.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10378)

### CODE REVIEW

**Comment by dt** [comment]
we went though some de-interface'ing rounds of changes with Datums a while back to cut on allocations -- can you double check that there are no benchmark changes here, particularly as introducing the `.Contents()` calls could de-inline things --  and include the benchstat results for some of the sql benchmarks in commit message?

**Comment by knz** [comment]
Like @dt I am very wary of the performance impact.
Meanwhile I also recognize that not doing this would cause a lot of code repetition.

Wouldn't be nice to be writing this in a language with support for proper generics?

cc @nvanbenschoten can you also participate in the review since you've been paying attention to this a lot.

**Comment by dt** [comment]
You might also be best off just ignoring DTimestamp[TZ], as it is my goal to have only one timestamp type (that is session aware as most people expect) within the next couple weeks.

**Comment by eisenstatdavid** [comment]
I think I'm going to withdraw this PR -- thought of an alternative approach
where the overload resolver attaches the necessary shims to the string
implementations that already exist.

**Pull request closed without merging**
