### PR TITLE
tsdb: add tenant-level store metrics to tsdb

### LINKED ISSUE #99228: tsdb: include TenantStorageMetrics per-tenant
**Is your feature request related to a problem? Please describe.**
`TenantStorageMetrics` appears to [record storage level metrics at the tenant level](https://github.com/cockroachdb/cockroach/blob/f33f404ebaa6c6f092c4ef47a36380c00236f341/pkg/kv/kvserver/metrics.go#L2088-L2115). However, our recent work to [update the MetricsRecorder with tenant registries](https://github.com/cockroachdb/cockroach/blob/d6fb82dc5fd7f2657c5dee856076723fc716f8f0/pkg/server/status/recorder.go#L146) does not capture these metrics. 

These metrics [neither exist in the the store level registries within the recorder](https://github.com/cockroachdb/cockroach/blob/d6fb82dc5fd7f2657c5dee856076723fc716f8f0/pkg/server/status/recorder.go#L142), because the `TenantStorageMetrics` [exist outside of the StoreMetrics registry](https://github.com/cockroachdb/cockroach/blob/f33f404ebaa6c6f092c4ef47a36380c00236f341/pkg/kv/kvserver/metrics.go#L1751-L1756). 

As it stands today, [when we register store-level metrics with the MetricsRecorder](https://github.com/cockroachdb/cockroach/blob/d6fb82dc5fd7f2657c5dee856076723fc716f8f0/pkg/server/status/recorder.go#L237-L244), we don't include any of these TenantStorageMetrics from what I can tell.

Because of this, tenant-level storage metrics that a tenant would naturally want to see, such as `livebytes`, `keybytes`, etc. are not available in TSDB (and therefore, neither in DB Console). 

An app tenant will naturally want to know how much live data they have in their tenant DB, so we will need to find a way to record this information into TSDB so it can be exposed in DB Console.

**Describe the solution you'd like**
Find a way to get these tenant-level storage metrics into TSDB, so that app tenants can view metrics such as `livebytes` in DB Console.

Jira issue: CRDB-25773

### PR DESCRIPTION
**Pull request by abarganier**
Previously, while we had the ability to show tenant-level store metrics in the `/_status/vars` page, these metrics were never written to tsdb.

This is despite the changes in https://github.com/cockroachdb/cockroach/pull/98077, which did a great job at writing all the metrics in the tenant-specific metric registries, but didn't pull the tenant-specific store metrics out of the store registries. This is because these metrics exist as *child* metrics on the store registry metrics, and we did not previously have logic to individually pick these metrics out of their parent AggGauge/Counter metrics.

This patch adds the logic to do so. Now, for each tenant ID that exists in the recorder's `tenantRegistries` map, we will attempt to pick that tenant's individual child metric & values from all the metrics that exist in TenantsStorageMetrics. This will limit the writing of these tenant-level metrics to only happen in deployments where multiple tenants are running in-process, as environments such as serverless clusters are expected to have an empty `tenantRegistries` map in this recorder.

This is necessary because if we're going to support multi-tenant tsdb, app tenants should be able to see core storage information about their logical cluster, such as `livebytes` which indicates how much live active data exists for the cluster.

Release note: none

Fixes: https://github.com/cockroachdb/cockroach/issues/99228

### CODE REVIEW

**Review by aadityasondhi — APPROVED** [review]
:lgtm: this is actually pretty cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99860#-:-NS6TcbF21GHSZGWoBq5:bor5nn4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by abarganier — COMMENTED** [review]
TFTR! I realized I was pulling the tenantMetricsSet with each store iteration, which was unnecessary, so I moved it outside the store registry loop.

CI was in a rough state when I originally put up this PR, so let's see if things are in a better state now. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99860#-:-NSBi6ot2M6B0rtnFHq3:b3lk6jx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

**Comment by abarganier** [comment]
(fixed an import cycle)

**Comment by abarganier** [comment]
bors r=aadityasondhi

**Pull request merged**
