### PR TITLE
sql, sem, opt, explain, memo, kv: audit bit-flag-checking helpers

### PR DESCRIPTION
**Pull request by michae2**
@mgartner's [comment](https://github.com/cockroachdb/cockroach/pull/118931#pullrequestreview-1870386752) on #118931 inspired me to audit all the other helper functions that check whether a flag is set in a bitfield. I might have found a couple bugs.

See individual commits for details.

Epic: None
Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice!

> Reviewed 6 of 6 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119035#-:-NqF8dH979JQ56qua06G:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @michae2)

___
*[`-- commits` line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119035#-NqF8fgk5ynb5lnNnxWN):*
Note: this could hypothetically induce a plan regression, although I don't think it's too likely. Adjusting the join hint would be a workaround if it were to happen.

**Review by mgartner — APPROVED** [review]
Thanks for looking into this! 
:lgtm:

> Reviewed 6 of 6 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119035#-:-NqT9CGCBRBX2oK4PoT8:bhmuu0n)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @arulajmani and @michae2)

___
*[`-- commits` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119035#-NqT7VLV-ceL3hR7CH3C):*
Can we add a test for this that shows the correct behavior?

**Comment by michae2** [comment]
I'm going to try to merge this in time for v24.3.

**Comment by mgartner** [comment]
*[`-- commits` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119035#-NqT7VLV-ceL3hR7CH3C):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can we add a test for this that shows the correct behavior?
</blockquote></details>

A test that shows the fix:

```
statement ok
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT,
  b INT,
  INDEX (a, b)
)

query T
EXPLAIN (OPT, VERBOSE)
SELECT * FROM (VALUES (1, 10), (2, 20), (3, 30)) as v(x, y)
INNER STRAIGHT JOIN t ON a > x
----
```

This no longer plans a lookup join, as expected - we wouldn't normally plan a lookup join here without the hint, and the `STRAIGHT` hint should not allow us to. Only a `LOOKUP` hint should.

**Comment by michae2** [comment]
TFTRs!

bors r=DrewKimball,mgartner

**Comment by mgartner** [comment]
Do you want to backport to 24.3 @michae2?

**Comment by michae2** [comment]
Sure!

blathers backport 24.3

**Pull request merged**
