### PR TITLE
colexec: clean up meta components handling

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: plumb statsCollectors directly in most cases**

This commit is mostly a mechanical change which replaces `getStats`
functions with using the stats collectors directly for the root
materializer and the hash routers. The outbox still expects a callback
because of the need to append flow-level stats on the last outbox.

Additionally, the drain helper of the materializer has been updated so
that the stats are retrieved before the metadata sources are drained.
This will be an invariant enforced by the checkers in the follow-up
commits.

Release note: None

**colexecargs: tightly couple root op with metadata sources and closers**

This commit introduces a utility struct `OpWithMetaInfo` that has a root
operator as well as the metadata sources and closers present in the tree
handling of which (draining and closing, respectively) hasn't been
claimed yet. The struct will be the same (and will replace)
`opDAGWithMetaSources` and `SynchronizerInput` by the follow-up commit.

The motivation behind this change is that we want to attribute stats
collectors, metadata sources, and - why not - closers to the tree of
operators in which they are present.

Release note: None

**colexec: clean up stats collection from wrapped processors**

Previously, if we had wrapped row-execution processors in the vectorized
flow, during the stats collection two `ComponentStats` objects would get
emitted for each wrapped processor - one by the processor itself and
another by the vectorized stats collector that is wrapping the
columnarizer. Both stats objects would have the same ComponentID, so
they would get Unioned. This commit cleans up the situation by making
the columnarizer "hijack" the `ExecStatsForTrace` function from the
wrapped processor.

This required a bit of plumbing, namely, we need to:
- track the "root" columnarizer separately in `NewColOperator` call so
that later the vectorized stats collectors could augment the
ComponentStats object created by the wrapped processor with additional
information
- provide an interface for the columnarizer to hijack the stats
function.

Release note: None

**colexec: finish stats collection refactor**

This commit plumbs the stats collectors into `OpWithMetaInfo` object
which allows us to get rid of separate `opDAGWithMetaSources` and
`SynchronizerInput` structs as well as more clealy define the ownership
of the stats collectors. Now all components can drain their input trees
are also responsible for collecting the stats, if applicable, before
draining. This invariant will be enforced by the follow-up commit.

Notable changes are to the synchronizers - now all of them (ordered,
serial unordered, parallel unordered) will be collecting stats. This
required creating a tracing span on the first call to `Next` so that we
had a way to propagate stats. That a-bit-hacky logic will be removed
once the `Operator` interface is updated to take in the context object
in `Init`.

Release note: None

**colflow: enforce stats collection before drain meta**

This commit introduces a dummy vectorized stats collector that is also
a metadata source that simply checks that `GetStats` has been called
before `DrainMeta` and returns an error as a metadata if not. This stats
invariants checker is now planned whenever `util.CrdbTestBuild` is true
(which is when `TAGS=crdb_test` was specified).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think this is RFAL.

A more detailed motivation behind this change is [here](https://github.com/cockroachdb/cockroach/pull/62255#issuecomment-802991768), but the gist of the change is introducing the following struct
```
type OpWithMetaInfo struct {
  Root colexecop.Operator
  StatsCollectors []colexecop.VectorizedStatsCollector
  MetadataSources execinfrapb.MetadataSources
  ToClose colexecop.Closers
}
```
to tightly couple stats collectors and metadata sources which simplifies the tracking of which components belong to which input tree. Closers are added because why not. The only component that doesn't use this new struct is an outbox because it requires special handling of stats collection in order to emit the flow-level stats on the last outbox on a remote node.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: but there is a lot here I'm not familiar with. Maybe @jordanlewis can take a look as well.

> Reviewed 17 of 41 files at r2, 22 of 29 files at r3, 24 of 25 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-:-MYLCa-W9zTooXF4Zs7W:bpyja7k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/colexec/columnarizer.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYLBmGi1N__5FYY50qb:-MYLBmGi1N__5FYY50qc:b-y80lb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/307ec27a56faeadf51f41c99e2ef9653a696d429/pkg/sql/colexec/columnarizer.go#L48)):*
> ```Go
> // chunk into a coldata.Batch column by column.
> type Columnarizer struct {
> 	execinfra.ProcessorBase
> ```

Unrelated, but I find it strange that these are embedding ProcessorBase (given that they're not processors). It may pay off to think about what functionality exactly do they need and if we can extract that out into something smaller.
___
*[pkg/sql/colexec/columnarizer.go, line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYLAy_I0Z3cIvKeGc6v:-MYLAy_I0Z3cIvKeGc6w:b-21u163) ([raw file](https://github.com/cockroachdb/cockroach/blob/307ec27a56faeadf51f41c99e2ef9653a696d429/pkg/sql/colexec/columnarizer.go#L159)):*
> ```Go
> 		c.input.Start(c.ctx)
> 		c.initStatus = colexecop.OperatorInitialized
> 		if pb, ok := c.input.(execinfra.ExecStatsForTraceHijacker); ok {
> ```

[nit] I know that `pb` here is from "processor base", but it's kind of cryptic
___
*[pkg/sql/colexec/materializer.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYKyoZ35bVLIAtwg0l7:-MYKyoZ35bVLIAtwg0l8:bu6sy1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f19327a97d89c369fdf6a79da061c0acf18fad7/pkg/sql/colexec/materializer.go#L123)):*
> ```Go
> 	if len(d.statsCollectors) > 0 {
> 		// If statsCollectors is non-nil, then the drainHelper is responsible
> 		// for attaching the execution statistics to the span, yet we don't get
> ```

I have trouble understanding this comment. What does "we don't get the recording from the span" mean?
___
*[pkg/sql/colflow/stats.go, line 243 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYLCH9S37cpWvXJpszL:-MYLCH9S37cpWvXJpszM:b-15e9aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/237f8b852b0fda84d8d06606e233afe995c53c28/pkg/sql/colflow/stats.go#L243)):*
> ```Go
> }
> 
> func maybeAddStatsInvariantChecker(op *colexecargs.OpWithMetaInfo) {
> ```

[nit] could use a short comment
___
*[pkg/sql/rowexec/aggregator.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYL8uoI-F89xTiesL_5:-MYL8uoI-F89xTiesL_6:b-6d405g) ([raw file](https://github.com/cockroachdb/cockroach/blob/307ec27a56faeadf51f41c99e2ef9653a696d429/pkg/sql/rowexec/aggregator.go#L157)):*
> ```Go
> // interface.
> func (ag *aggregatorBase) HijackExecStatsForTrace() func() *execinfrapb.ComponentStats {
> 	return ag.ProcessorBase.HijackExecStatsForTrace()
> ```

Why do we need these wrappers, don't we inherit the function from ProcessorBase anyway?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the review! @jordanlewis could you take a look from higher level perspective?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-:-MYRtIO70tzj2fztFHGh:b-ob93v4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/colexec/columnarizer.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYLBmGi1N__5FYY50qb:-MYRqz02C5MUgNVe782P:b5bfip8) ([raw file](https://github.com/cockroachdb/cockroach/blob/307ec27a56faeadf51f41c99e2ef9653a696d429/pkg/sql/colexec/columnarizer.go#L48)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Unrelated, but I find it strange that these are embedding ProcessorBase (given that they're not processors). It may pay off to think about what functionality exactly do they need and if we can extract that out into something smaller.
</blockquote></details>

Fair point, left a TODO to think about it.
___
*[pkg/sql/colexec/materializer.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYKyoZ35bVLIAtwg0l7:-MYRdjWvCuzmxTg02EM5:b-478up3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f19327a97d89c369fdf6a79da061c0acf18fad7/pkg/sql/colexec/materializer.go#L123)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I have trouble understanding this comment. What does "we don't get the recording from the span" mean?
</blockquote></details>

Updated the comment, let me know if it makes sense.
___
*[pkg/sql/rowexec/aggregator.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYL8uoI-F89xTiesL_5:-MYRps7fBx_v-6LKS84D:b-sxuke) ([raw file](https://github.com/cockroachdb/cockroach/blob/307ec27a56faeadf51f41c99e2ef9653a696d429/pkg/sql/rowexec/aggregator.go#L157)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why do we need these wrappers, don't we inherit the function from ProcessorBase anyway?
</blockquote></details>

Hm, when I was writing this code originally, I ran into some issues (namely, a processor (hidden behind `RowSource` interface) couldn't be converted to `ExecStatsForTraceHijacker` - I assumed it was because all processors embed `ProcessorBase` by value, by the method implementation must have a pointer receiver so that the ProcessorBase is updated accordingly when execStats func is hijacked. As a result, I was running in incomplete EXPLAIN ANALYZE diagrams.

However, now I removed these wrappers, and things seem to be fine. Not sure what changed, but I've removed them.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62221)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/rowexec/aggregator.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYL8uoI-F89xTiesL_5:-MYf5KOw1ZslUM9vOEoj:b-8b3o9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/307ec27a56faeadf51f41c99e2ef9653a696d429/pkg/sql/rowexec/aggregator.go#L157)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, when I was writing this code originally, I ran into some issues (namely, a processor (hidden behind `RowSource` interface) couldn't be converted to `ExecStatsForTraceHijacker` - I assumed it was because all processors embed `ProcessorBase` by value, by the method implementation must have a pointer receiver so that the ProcessorBase is updated accordingly when execStats func is hijacked. As a result, I was running in incomplete EXPLAIN ANALYZE diagrams.

However, now I removed these wrappers, and things seem to be fine. Not sure what changed, but I've removed them.
</blockquote></details>

If A embeds Base, *A implements any interface that *Base implements (and A does not) https://play.golang.org/p/l8THFK7DW-y

**Review by yuzefovich — COMMENTED** [review]
@jordanlewis please give this at least a high level review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-:-MYqfZLT17-sNhKV6PmV:bvfv6kt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/rowexec/aggregator.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYL8uoI-F89xTiesL_5:-MYqfXkJ8eIahJasCuwM:bg2j5h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/307ec27a56faeadf51f41c99e2ef9653a696d429/pkg/sql/rowexec/aggregator.go#L157)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If A embeds Base, *A implements any interface that *Base implements (and A does not) https://play.golang.org/p/l8THFK7DW-y
</blockquote></details>

Makes sense, thanks!

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> Reviewed 1 of 29 files at r3, 64 of 66 files at r6, 41 of 41 files at r7, 29 of 30 files at r8, 40 of 40 files at r9, 17 of 17 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-:-MYrVdweCo0k3ru3qGG_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/colexecop/operator.go, line 347 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYrUxCv8NE1274Uyz5C:-MYrUxCv8NE1274Uyz5D:byetl0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ddf4699eab419c11a6e1d876c8487f3e3de5f/pkg/sql/colexecop/operator.go#L347)):*
> ```Go
> }
> 
> // VectorizedStatsCollector is the common interface implemented by collectors.
> ```

nit: it is not clear at least to me what "Collectors" are from this context, a better comment would help. Also perhaps some commentary on GetStats - is it the stats just for the operator, or for its children, etc?
___
*[pkg/sql/colflow/stats.go, line 247 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYrVVkE-GTt6pWFhT8e:-MYrVVkE-GTt6pWFhT8f:bjrjxy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842b70eadc8a159673344c28f05fbac2408d887/pkg/sql/colflow/stats.go#L247)):*
> ```Go
> // specified. See comment on statsInvariantChecker for the kind of invariants
> // checked.
> func maybeAddStatsInvariantChecker(op *colexecargs.OpWithMetaInfo) {
> ```

Nice, I like this idea

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-:-MYrs0cI9S370qGd5sEB:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/colexecop/operator.go, line 347 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYrUxCv8NE1274Uyz5C:-MYrrxKMDJ5UP2_PmOrA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ddf4699eab419c11a6e1d876c8487f3e3de5f/pkg/sql/colexecop/operator.go#L347)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: it is not clear at least to me what "Collectors" are from this context, a better comment would help. Also perhaps some commentary on GetStats - is it the stats just for the operator, or for its children, etc?
</blockquote></details>

Done.
___
*[pkg/sql/colflow/stats.go, line 247 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/62221#-MYrVVkE-GTt6pWFhT8e:-MYrrzE82CQ1ZPX7llL8:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5842b70eadc8a159673344c28f05fbac2408d887/pkg/sql/colflow/stats.go#L247)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Nice, I like this idea
</blockquote></details>

:)

**Pull request merged**
