### PR TITLE
sql,catalogkv: cleanup to virtual table descriptor resolution

### PR DESCRIPTION
**Pull request by ajwerner**
See individual commits. Enables validation of type descriptors (a rather wild oversight). Before this PR we didn't validate type descriptors on read the way we validate the other descriptors.

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
These changes LGTM, but why did removing the schema descriptor lookup enable type descriptor validation? Were the lookups circular before?

I think this is also slightly related to #57619. Maybe `GetAllDescriptors` and `GetAllDescriptorsUnvalidated` will eventually return virtual "descriptors" as well, which would simplify some things.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 9 files at r3, 7 of 9 files at r4, 3 of 3 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57543#-:-MP7Fmeb2YdGp-JONq8W:b-3lfupe)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
The type validation is totally unrelated. At least, I didn’t intend for it to be related. I just noticed we weren’t doing it on the branch and decided to put it here. I can make a different pr with that commit if you prefer.

**Review by thoszhang — APPROVED** [review]
Unless you're planning to backport some of these changes (and I don't think you are), I'm fine with a single PR. Maybe update the PR comment to make that clearer?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57543#-:-MP7Loq6EXguk1i6fDMJ:b-66wg5l)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
TFTR!

bors r=lucy-zhang

**Pull request merged**
