### PR TITLE
docs: IO SQL diagrams

### PR DESCRIPTION
**Pull request by lnhsingh**
Release justification: low-risk update to SQL diagrams for docs
Release notes: none

### CODE REVIEW

**Comment by miretskiy** [comment]
not sure where to see how these look like...
Also, there is a special `FOR SCHEDULE(s)` clause in SHOW JOBS.  Perhaps
you should also update/include this

**Comment by lnhsingh** [comment]
The updated diagrams will eventually show up in my docs PR:
https://github.com/cockroachdb/docs/pull/8245 (idk how to view them
otherwise though). I checked and the JOBS statements seem to have already
been updated with the new SCHEDULES clause, so no updates were needed. I
just regenerated those diagrams for docs.

**Review by miretskiy — APPROVED** [review]

**Comment by lnhsingh** [comment]
@miretskiy do you know what i should do to get my build to pass?

**Comment by knz** [comment]
- the roachtest failure is not yours. I suggest rebasing to pick up a fix.
- The lint failure is because you did not include "Release justification"

```
[23:28:24]W:		 [Ensure commit message contains a release justification] Build Failed. No Release justification in the commit message or in the PR description.
```

**Comment by lnhsingh** [comment]
@knz can you help me again? I'm not sure what else I need to do to get the tests to pass-- I rebased and also added the release justification note.

**Comment by knz** [comment]
the build of `diagrams.go` is failing:

```
[16:20:18] :		 [Ensure generated code is up-to-date] pkg/cmd/docgen/diagrams.go:1221:77: syntax error: unexpected newline, expecting comma or }
```

did you run `make bin/docgen` to check whether it builds locally?

**Comment by knz** [comment]
The code is fine, but you forgot to commit the new generated files that came at the end as a result.

**Comment by lnhsingh** [comment]
@knz thanks for your help! I noticed that too and just committed them.

**Pull request merged**
