### PR TITLE
sql: add point insert and update enforce_home_region support

### LINKED ISSUE #99580: opt: INSERT statements do not seem to respect enforce_home_region
Simple `INSERT` statements using `VALUES` do not seem to respect the `enforce_home_region` setting. Other DML statements (including `UPSERT` and `INSERT ON CONFLICT`) fail with an error if they would cross regions, but `INSERT` does not seem to. Here's a repro using `cockroach demo --global --nodes 9 --multitenant=false --insecure`:

```sql
CREATE DATABASE d PRIMARY REGION "us-east1" REGIONS "europe-west1", "us-west1";
SHOW CREATE DATABASE d;
USE d;

CREATE TABLE xy (
  x INT PRIMARY KEY,
  y INT
);
ALTER TABLE xy ADD COLUMN region crdb_internal_region AS (
  CASE WHEN x = 0 THEN 'europe-west1'
       WHEN x = 1 THEN 'us-east1'
       WHEN x = 2 THEN 'us-west1'
       WHEN x = 3 THEN 'us-west1'
  END
) STORED;
ALTER TABLE xy ALTER COLUMN region SET NOT NULL;
ALTER TABLE xy SET LOCALITY REGIONAL BY ROW AS region;
SHOW CREATE TABLE xy;

INSERT INTO xy (x, y) VALUES (0, 0), (1, 1), (2, 2);
SELECT * FROM xy;

SET enforce_home_region = on;
SET enforce_home_region_follower_reads_enabled = on;

-- assuming gateway locality is us-east1
SHOW LOCALITY;

-- these statements all fail with the error:
-- "Query is not running in its home region. Try running the query from region 'us-west1'."
SELECT * FROM xy WHERE x = 2;
UPDATE xy SET y = 12 WHERE x = 2;
DELETE FROM xy WHERE x = 2;
UPSERT INTO xy (x, y) VALUES (2, 22);
INSERT INTO xy (x, y) VALUES (2, 32) ON CONFLICT (x) DO UPDATE SET y = 32;
-- including these
UPSERT INTO xy (x, y) VALUES (3, 3);
INSERT INTO xy (x, y) VALUES (3, 3) ON CONFLICT (x) DO UPDATE SET y = 33;

-- but a plain INSERT succeeds, even though it crosses regions
INSERT INTO xy (x, y) VALUES (3, 3);
```

This is on `v23.1.0-alpha.8-dev`.

Jira issue: CRDB-25950

### PR DESCRIPTION
**Pull request by msirek**
This adds missing support for erroring out insert, fast-path insert and
update when the enforce_home_region setting is on and we're attempting
to write a row to a remote region. Note that delete is already handled  
by code handling the scan it performs and upsert is handled by code     
handling the locality-optimized join (or regular join in the case of    
non-RBR tables) it performs.  

Epic: none
Fixes: #99580

Release note (bug fix): Support has been added for erroring out point
inserts and updates which write to a remote region of a table created
with the REGIONAL BY ROW AS clause.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @msirek)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NSh1Z9KCWMFQP7UrEKK):*
What about DELETEs and UPSERTs? If they are different and don't need to be modified, consider adding the explanation into the commit message.
___
*[`pkg/sql/update.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NSh2ehu013ACW0sDkYh:-NSh2ehu013ACW0sDkYi:b6nuwhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0726bde3a79ea742f9082cd1403a975c88685caa/pkg/sql/update.go#L129)):*
> ```Go
> 	// regionMustBeLocalColID indicates the id of the column which must insert a
> 	// home region matching the gateway region in a REGIONAL BY ROW table.
> 	regionMustBeLocalColID descpb.ColumnID
> ```

nit: this logic is duplicated. Should we extract a helper struct that would contain these two fields and have a single `setupEnforceHomeRegion` method, and then we'd just embed it into `insertRun` and `updateRun`?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NSh31ZK0Tb9-MmAwjJS:-NSh31ZK0Tb9-MmAwjJT:b9iub4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0726bde3a79ea742f9082cd1403a975c88685caa/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L50)):*
> ```
> 
> statement ok
> ALTER TABLE xy ADD COLUMN z INT;
> ```

nit: is there a reason that this column is added separately from `CREATE TABLE` statement? Do we need this `z` column at all?

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NSh1Z9KCWMFQP7UrEKK):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

What about DELETEs and UPSERTs? If they are different and don't need to be modified, consider adding the explanation into the commit message.
</blockquote></details>

The reason is, DELETEs are handled by scans:
```sql
EXPLAIN DELETE FROM xy WHERE x=2;

            distribution: local
            vectorized: true
            ·
            • delete
            │ from: xy
            │ auto commit
            │
            └── • filter
                │ filter: x = 2
                │
                └── • scan
                      missing stats
                      table: xy@xy_pkey
                      spans: [/'us-east-1' - /'us-east-1']
```

and UPSERTs are handled by locality-optimized join:
```sql
EXPLAIN UPSERT INTO xy (x,y,z) VALUES (2,2,2);

            distribution: local
            vectorized: true
            ·
            • upsert
            │ into: xy(x, y, rowid, region, z)
            │ auto commit
            │ arbiter constraints: xy_pkey
            │
            └── • render
                │
                └── • lookup join (left outer)
                    │ table: xy@xy_pkey
                    │ equality cols are key
                    │ lookup condition: (region = 'ap-southeast-2') AND (rowid_default = rowid)
                    │ remote lookup condition: (region IN ('ca-central-1', 'us-east-1')) AND (rowid_default = rowid)
                    │
                    └── • distinct
                        │ estimated row count: 1
                        │ distinct on: rowid_default
                        │ nulls are distinct
                        │ error on duplicate
                        │
                        └── • values
                              size: 5 columns, 1 row
```

I've updated the commit message regarding these cases.
___
*[`pkg/sql/update.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NSh2ehu013ACW0sDkYh:-NSweMyP423gCmzcZ0qp:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0726bde3a79ea742f9082cd1403a975c88685caa/pkg/sql/update.go#L129)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this logic is duplicated. Should we extract a helper struct that would contain these two fields and have a single `setupEnforceHomeRegion` method, and then we'd just embed it into `insertRun` and `updateRun`?
</blockquote></details>

Done
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NSh31ZK0Tb9-MmAwjJS:-NSweQ4K2YxGh2jSM9GI:bcc8c92) ([raw file](https://github.com/cockroachdb/cockroach/blob/0726bde3a79ea742f9082cd1403a975c88685caa/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L50)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: is there a reason that this column is added separately from `CREATE TABLE` statement? Do we need this `z` column at all?
</blockquote></details>

I want to test an altered table case which might not have the default mapping of column IDs to ordinals. I've added an additional DROP COLUMN and ADD COLUMN to maybe shuffle the mapping a bit.

RFAL

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @msirek)

___
*[`pkg/sql/insert.go` line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NTGIurt2t4G9isBGUfh:-NTGIurt2t4G9isBGUfi:b1hhwtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/96ddcf52eff15decdde0521f4a437c973c23f6f6/pkg/sql/insert.go#L101)):*
> ```Go
> type regionLocalInfoType struct {
> 
> 	// regionMustBeLocalColID indicates the id of the column which must insert a
> ```

nit: to me something sounds a bit off in "must insert a home region", perhaps "must use a home region"?
___
*[`pkg/sql/insert.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NTGTMCd84EJ1oc_veEW:-NTGTMCd84EJ1oc_veEX:bxhbs8) ([raw file](https://github.com/cockroachdb/cockroach/blob/96ddcf52eff15decdde0521f4a437c973c23f6f6/pkg/sql/insert.go#L139)):*
> ```Go
> // the row's locality doesn't match the gateway region.
> func (r *regionLocalInfoType) checkHomeRegion(row tree.Datums) error {
> 	if r.regionMustBeLocalColID != 0 {
> ```

Is it possible that the zero column ID is a valid value? Perhaps it'd be more bullet-proof to have an explicit boolean that indicates whether the enforcement of `regionLocalInfoType` is taking place?
___
*[`pkg/sql/insert.go` line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NTGTpdDBJjv5owNkG1e:-NTGTpdDBJjv5owNkG1f:b6e77hs) ([raw file](https://github.com/cockroachdb/cockroach/blob/96ddcf52eff15decdde0521f4a437c973c23f6f6/pkg/sql/insert.go#L140)):*
> ```Go
> func (r *regionLocalInfoType) checkHomeRegion(row tree.Datums) error {
> 	if r.regionMustBeLocalColID != 0 {
> 		if regionColIdx, ok := r.colIDtoRowIndex.Get(r.regionMustBeLocalColID); ok {
> ```

nit: IIUC we'd get `!ok` here if the region column is NULL, is it ever possible to be so? I wonder whether we should be stricter here, although IIRC the `enforce_home_region` is on a best effort basis, so perhaps the current approach makes sense.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NSh31ZK0Tb9-MmAwjJS:-NTGUNUSDiO8aHdsU3i1:bcs4235) ([raw file](https://github.com/cockroachdb/cockroach/blob/0726bde3a79ea742f9082cd1403a975c88685caa/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L50)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I want to test an altered table case which might not have the default mapping of column IDs to ordinals. I've added an additional DROP COLUMN and ADD COLUMN to maybe shuffle the mapping a bit.

RFAL
</blockquote></details>

nit: perhaps mention this reasoning in a comment in the test?

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/insert.go` line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NTGIurt2t4G9isBGUfh:-NTGVYv7AxT7qwPC08iR:b435755) ([raw file](https://github.com/cockroachdb/cockroach/blob/96ddcf52eff15decdde0521f4a437c973c23f6f6/pkg/sql/insert.go#L101)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: to me something sounds a bit off in "must insert a home region", perhaps "must use a home region"?
</blockquote></details>

Made the change.



_Code quote:_
```Go
regionMustBeLocalColID indicates the id of the column which must insert a
```
___
*[`pkg/sql/insert.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NTGTMCd84EJ1oc_veEW:-NTGa7hbA4OcZh28sZCl:bvbawvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/96ddcf52eff15decdde0521f4a437c973c23f6f6/pkg/sql/insert.go#L139)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is it possible that the zero column ID is a valid value? Perhaps it'd be more bullet-proof to have an explicit boolean that indicates whether the enforcement of `regionLocalInfoType` is taking place?
</blockquote></details>

We fail an assertion if a zero column ID is used:
https://github.com/cockroachdb/cockroach/blob/34da13988a93e59e43e9c251f92a1c1d432f32c1/pkg/sql/opt/colset.go#L55-L61

This should be bullet-proof enough.
___
*[`pkg/sql/insert.go` line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NTGTpdDBJjv5owNkG1e:-NTGbcEm6MKMzquuX7RA:b-c1lxl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/96ddcf52eff15decdde0521f4a437c973c23f6f6/pkg/sql/insert.go#L140)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: IIUC we'd get `!ok` here if the region column is NULL, is it ever possible to be so? I wonder whether we should be stricter here, although IIRC the `enforce_home_region` is on a best effort basis, so perhaps the current approach makes sense.
</blockquote></details>

It is not allowed to create a REGIONAL BY ROW table on a nullable region column:
`cockroach demo --global --nodes 9 --multitenant=false --insecure`

```sql
CREATE DATABASE d PRIMARY REGION "us-east1" REGIONS "europe-west1", "us-west1";
SHOW CREATE DATABASE d;
USE d;

CREATE TABLE xy (
  x INT PRIMARY KEY,
  y INT
);
ALTER TABLE xy ADD COLUMN region crdb_internal_region AS (
  CASE WHEN x = 0 THEN 'europe-west1'
       WHEN x = 1 THEN 'us-east1'
       WHEN x = 2 THEN 'us-west1'
       WHEN x = 3 THEN 'us-west1'
  END
) STORED;
ALTER TABLE xy SET LOCALITY REGIONAL BY ROW AS region;                                                                                                                    
ERROR: cannot use column region for REGIONAL BY ROW table as it may contain NULL values
SQLSTATE: 42P16
HINT: Add the NOT NULL constraint first using ALTER TABLE xy ALTER COLUMN region SET NOT NULL.

ALTER TABLE xy ALTER COLUMN region SET NOT NULL;
ALTER TABLE xy SET LOCALITY REGIONAL BY ROW AS region;                                                                                                                    
NOTICE: LOCALITY changes will be finalized asynchronously; further schema changes on this table may be restricted until the job completes
ALTER TABLE SET LOCALITY

Time: 29.627s total (execution 29.626s / network 0.000s)

ALTER TABLE xy ALTER COLUMN region DROP NOT NULL;                                                                                                                         
ERROR: column "region" is in a primary index
SQLSTATE: 42P16
```
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-NSh31ZK0Tb9-MmAwjJS:-NTGdbTN7ogdgIZA4i-6:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0726bde3a79ea742f9082cd1403a975c88685caa/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L50)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps mention this reasoning in a comment in the test?
</blockquote></details>

Done

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-:-NTGhrIA900FbYlimj5u:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by msirek — COMMENTED** [review]
TFTR!
bors r=yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100967#-:-NTGiLyo-FHR3j_A0XNB:b-87rjax)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Pull request merged**
