### PR TITLE
ui: show correct zone config

### LINKED ISSUE #57896: DB Console: Databases page is showing incorrect  zone configuration values
*Observation*. When a user edits zone configurations for a database or a table, those updated attributes are not reflected in the {{Databases}} page. What’s currently shown in the DB Console UI is incorrect.

*Repo steps*. Define new zone configs for a table and notice that {{Databases}} page does not update to reflect that change. I have a test {{bank}} database with a table called {{orders}}

* SHOW ZONE CONFIGURATION FOR TABLE orders;
** !Image 2020-11-19 at 11.58.56 AM.png|width=757,height=215!

* ALTER TABLE orders CONFIGURE ZONE USING num_replicas = *5*, gc.ttlseconds = *180000*;
* SHOW ZONE CONFIGURATION FOR TABLE orders;
** !Image 2020-11-19 at 11.59.35 AM.png|width=759,height=213!

* See corresponding {{Databases}} page - the page does not show the updated values (it continues to show the {{RANGE default}} values)
** !Image 2020-11-19 at 12.01.14 PM.png|width=1307,height=825!

*Expectation*. After a user edits zone configurations, the DB Console UI should match the output of {{SHOW ZONE CONFIGURATION FOR database or table}}.

----

From [Slack](https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1605798640073100?thread_ts=1605734735.071500&cid=CHKQGKYEM): 

> It looks like from the output of {{show all zone configurationson}} that you altered the zone config for {{range default}}. Then it seems you created a table without changing the zone configs on the database/table itself. Our zone configurations apply in a cascading fashion (see this [issue](https://github.com/cockroachdb/cockroach/issues/31398] for details). It looks like we have both some work to do in the SQL shell to show inheritance for zone configs and also to update the UI to properly reflect inheritance.

cc \[~accountid:5bd8d5d73aa82432ce72c0e5) for awareness who investigated the issue

### PR DESCRIPTION
**Pull request by nkodali**
Previously on the table detail page in DB Console,
the default zone config for the db was shown, rather
than any table level settings. Additionally,
constraints and lease preferences were not being
serialized properly, displaying as
"...Object object..." This fixes both of those bugs.

The display for the zone configuration statement is
additionally updated to show the actual SQL statement
to replicate the zone config in the SQL shell.
Previously an invalid statement "CONFIGURE ZONE USING..."
was displayed.

Resolves #57896.
See also: https://github.com/cockroachlabs/support/issues/737.
See also: https://github.com/cockroachlabs/support/issues/727.

Release note (bug fix): Fixed a bug introduced in v20.1 in
DB Console where incorrect zone configuration values were
shown on the table details page and constraints and lease
preferences were not displayed.

Release note (ui change): Updates the table details page
to show table specific zone configuration values when set,
show constraints and lease preferences, and display
a valid statement to re-configure zone configuration
for that table.

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
Thank you for making this fix! I tested with the other support issue we had and it does fix it as well! Just added a note to also fix some of the zone config serialization while you're at it.

Run eslint and make sure Goland is configured to autoformat w/ it.

I'd add a second release note for db console. My understanding is that it's fine to have multiple release note entries if your PR covers multiple categories. 

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59196#-:-MRXCNOs7JmgCQFsnSDe:b-qu65x4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nkodali)

___
*[pkg/ui/src/views/shared/components/sql/highlight.tsx, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59196#-MRXGnfU1BmrBqgcUUXT:-MRXGnfU1BmrBqgcUUXU:b-13tses) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52a02527befa02cd47c6176893b3db4b07ae180/pkg/ui/src/views/shared/components/sql/highlight.tsx#L65)):*
> ```XML
>         <br />
>         <span className="hljs-label">constraints = ['</span>
>         <span className="hljs-built_in">{String(zoneConfig.constraints)}</span>
> ```

Could we update this to print the proper constraints instead of `constraints = ['[object Object],[object Object]'],`. There are only two fields here and it should look like:

```
demo@127.0.0.1:26257/movr> SHOW ZONE CONFIGURATION FOR TABLE users;
    target    |                           raw_config_sql
--------------+---------------------------------------------------------------------
  TABLE users | ALTER TABLE users CONFIGURE ZONE USING
              |     range_min_bytes = 16777216,
              |     range_max_bytes = 67108864,
              |     gc.ttlseconds = 9000,
              |     num_replicas = 3,
              |     constraints = '{+region=us-east1: 1, +region=us-west1: 1}',
              |     lease_preferences = '[[+region=us-east1], [+region=us-west1]]'
(1 row)
```
___
*[pkg/ui/src/views/shared/components/sql/highlight.tsx, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59196#-MRXGxRe1m9jXTd-gsR3:-MRXGxRfEzfCt6Me_uck:b-7nogr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52a02527befa02cd47c6176893b3db4b07ae180/pkg/ui/src/views/shared/components/sql/highlight.tsx#L70)):*
> ```XML
>         <span className="hljs-label">lease_preferences = [['</span>
>         <span className="hljs-built_in">
>           {String(zoneConfig.lease_preferences)}
> ```

Same comment here as above, would be nice to get the serialization bug out of the way as well here. Example up above.

**Review by dhartunian — APPROVED** [review]
:lgtm: thanks for doing this!

> Reviewed 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59196#-:-MS3YWHf0vP34Mv9gD2O:bw3kg2j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @nkodali)

___
*[pkg/server/admin.go, line 612 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59196#-MS3Y9zpDgQbIRYgIKM-:-MS3Y9zq6Eafc5jDjlJl:b-77zfy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f04322f0b92fd35e4b44eddc8772ebe7d432b44d/pkg/server/admin.go#L612)):*
> ```Go
> 		const rawConfigSqlColName = "raw_config_sql"
> 		if len(rows) != 1 {
> 			return nil, s.serverErrorf("show zone configuration not available.")
> ```

Is it possible that we could have a perfectly valid table with an empty zone config?

**Review by nkodali — COMMENTED** [review]
TFTR. Updated to more gracefully handle empty zone config.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59196#-:-MS4RzqYBgafrvZsTI_R:b-rbjzmh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

___
*[pkg/server/admin.go, line 612 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59196#-MS3Y9zpDgQbIRYgIKM-:-MS4R_z-9aeTWURG8_bU:b-w37dly) ([raw file](https://github.com/cockroachdb/cockroach/blob/f04322f0b92fd35e4b44eddc8772ebe7d432b44d/pkg/server/admin.go#L612)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Is it possible that we could have a perfectly valid table with an empty zone config?
</blockquote></details>

My limited understanding of zone configs is that there is always a default. Despite that, I think it's safer to return empty string in the case this query gives no results, rather than a server error.  Updated to do that.
___
*[pkg/ui/src/views/shared/components/sql/highlight.tsx, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59196#-MRXGnfU1BmrBqgcUUXT:-MS4RuKP-dvcug5x8kTe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52a02527befa02cd47c6176893b3db4b07ae180/pkg/ui/src/views/shared/components/sql/highlight.tsx#L65)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Could we update this to print the proper constraints instead of `constraints = ['[object Object],[object Object]'],`. There are only two fields here and it should look like:

```
demo@127.0.0.1:26257/movr> SHOW ZONE CONFIGURATION FOR TABLE users;
    target    |                           raw_config_sql
--------------+---------------------------------------------------------------------
  TABLE users | ALTER TABLE users CONFIGURE ZONE USING
              |     range_min_bytes = 16777216,
              |     range_max_bytes = 67108864,
              |     gc.ttlseconds = 9000,
              |     num_replicas = 3,
              |     constraints = '{+region=us-east1: 1, +region=us-west1: 1}',
              |     lease_preferences = '[[+region=us-east1], [+region=us-west1]]'
(1 row)
```
</blockquote></details>

Done.
___
*[pkg/ui/src/views/shared/components/sql/highlight.tsx, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59196#-MRXGxRe1m9jXTd-gsR3:-MS4Rv4R-Yd2vzEoI4oF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52a02527befa02cd47c6176893b3db4b07ae180/pkg/ui/src/views/shared/components/sql/highlight.tsx#L70)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Same comment here as above, would be nice to get the serialization bug out of the way as well here. Example up above.
</blockquote></details>

Done.

**Comment by dhartunian** [comment]
You've got a frontend TS error:

```
16:07:00
    src/views/databases/containers/databaseTables/databaseTables.fixtures.ts(47,3): error TS2322: Type '{ detailsAndStatsLoaded: () => true; name: string; id: number; numColumns: number; numIndices: number; rangeCount: number; createStatement: string; grants: { user: string; privileges: string[]; }[]; numReplicas: number; mvccSize: { ...; }; physicalSize: number; }[]' is not assignable to type 'TableInfo[]'.
16:07:00
      Property 'configureZoneStatement' is missing in type '{ detailsAndStatsLoaded: () => true; name: string; id: number; numColumns: number; numIndices: number; rangeCount: number; createStatement: string; grants: { user: string; privileges: string[]; }[]; numReplicas: number; mvccSize: { ...; }; physicalSize: number; }' but required in type 'TableInfo'.
```

**Comment by nkodali** [comment]
bors r=dhartunian

**Comment by nkodali** [comment]
bors r=dhartunian

**Pull request merged**
