### PR TITLE
cli: support OpenMetrics in tsdump

### LINKED ISSUE #97120: cli: make tsdump compatible with prometheus
**Is your feature request related to a problem? Please describe.**

Today, many L2 escalations come with a `tsdump` (in `raw`, i.e. CRDB-internal format) that is hosted on an ephemeral roachprod instance.

For various reasons[^1], the DB platform teams would prefer standardizing on prometheus as an observability stack. We'd like tsdumps to be added to a central, always-on prometheus instance.

**Describe the solution you'd like**

There should be a way to add tsdumps to a prometheus instance. This has two parts (which must be compatible with each other): conversion into a suitable format, and ingestion into prometheus.

Whatever format we can hand to prometheus, the conversion is likely straightforward and we don't need to add a new wire encoding to the `tsdump` command. Instead, we can internally use the `raw` format and transcode to whatever we need, maybe even after the fact. So the workflow could be

`./cockroach debug tsdump ... --format=raw tsdump.gob`

`./cockroach debug tsdump2prom tsdump.gob{,.yaml} > somethingelse.xyz`

`./something import tsdump [...] somethingelse.xyz --label support_issue=1234`

I haven't revisited which prometheus deployment is a good choice here and how to import timeseries into its backing storage. I remember that at least a few years ago it was difficult to backfill historical data into an existing prometheus instance. But I'm hopeful this can be achieved today as the ecosystem has advanced.

**Describe alternatives you've considered**

There are variations of the above plan, but I don't think there is a real alternative.

[^1]: less work for the TSEs, easier to build custom dashboards, easier to share and save custom dashboards which can in turn be used to improve our built-in dashboards, can use advanced features such as annotations which are very useful, grafana is just much nicer to use than our built-in stuff

Jira issue: CRDB-24526
Epic: CRDB-25656

### PR DESCRIPTION
**Pull request by koorosh**
**This PR duplicates initial work in #111654** with additional change that adds tests and small fixes.
Last commit can be reviewed only.
The only reason for new PR is that I couldn't push additional changes to former one.

----
This PR continues #97411 from @tbg.

Fixes https://github.com/cockroachdb/cockroach/issues/97120.

See individual commit messages for details.

----
*From #97411 on the first two commits:*

Touches https://github.com/cockroachdb/cockroach/issues/97120.

    $ cockroach debug tsdump --insecure --format=openmetrics > tsdump.om

    $ tail -n 3 tsdump.om
    valcount{store="1"} 9841.000000 1677012190.0
    valcount{store="1"} 9847.000000 1677012200.0
    # EOF

    $ docker run -v $PWD/tsdump.om:/tsdump.om -v $PWD/data:/data --entrypoint /bin/promtool prom/prometheus tsdb create-blocks-from openmetrics /tsdump.om /data
    BLOCK ULID                  MIN TIME       MAX TIME       DURATION     NUM SAMPLES  NUM CHUNKS   NUM SERIES   SIZE
    01GSTVJG4QMBSQ4ACPK80FFDJ9  1676544540000  1676544940001  6m40.001s    10598        1514         1514         261097
    01GSTVJGWM2CX1AA56QSSZ9T2R  1677009150000  1677009590001  7m20.001s    68130        1514         1514         305952
    01GSTVJHT2TWTZGCPE52AE1T95  1677009600000  1677012200001  43m20.001s   394093       4542         1514         692053

    $ ls data
    01GSTVJG4QMBSQ4ACPK80FFDJ9	01GSTVJGWM2CX1AA56QSSZ9T2R	01GSTVJHT2TWTZGCPE52AE1T95

    $ docker run -p 9090:9090 -v $PWD/data:/data prom/prometheus --storage.tsdb.path=/data --web.enable-admin-api --config.file=/etc/prometheus/prometheus.yml

image

----

Second commit, convert existing raw tsdump and look at it through Grafana/prom:

`./cockroach debug tsdump --format=openmetrics tsdump.gob > tsdump.om`

For demonstration purposes one can then:

- clone dockprom[^1]
- add `uid: v9Zz2K6nz` to the prometheus datasource[^2]
- run:

  ```
  for d in grafana_data prometheus_data; do
    docker volume create --driver local --opt type=none --opt device=$PWD/$d--opt o=bind $d
  done
  promtool tsdb create-blocks-from openmetrics tsdump.om prometheus_data/
  docker-compose up -d
  ```
- http://localhost:3000 admin/admin
- import the L2 dashboard[^3]
- view the tsdump![^4]

Note that all of the histograms are missing because the internal timeseries
data doesn't support histograms (records just a few quantiles).

[^1]: https://github.com/stefanprodan/dockprom
[^2]: grafana/provisioning/datasources/datasource.yml
[^3]: https://grafana.testeng.crdb.io/d/CAvWxELVz/l2-drill-down?orgId=1&from=now-1h&to=now&refresh=1m&var-cluster=grinaker-231&var-instances=All
[^4]: image

----
*re: additons to #97411:*

The last two commits enable tsdump raw -> openmetrics conversion offline and add additional labels to the metrics, for parity with cloud metrics.

With a single-node, insecure cluster:

```
➜  cockroach git:(tsdump-openmetrics) ./cockroach debug tsdump --insecure --host=localhost:26258 --format=raw --from="2023-09-29 15:27:03" --to="2023-09-29 20:57:03" > tsdump.gob
 
... shut down cluster...

➜  cockroach git:(tsdump-openmetrics) ✗ ./cockroach debug tsdump --format=openmetrics tsdump.gob --cluster-label="my-cluster" > tsdump_converted.om
➜  cockroach git:(tsdump-openmetrics) ✗ open ./tsdump_converted.om

``` 

```
admission_admitted_elastic_cpu{instance="",organization_id="",organization_label="",node_id="1",sla_type="",tenant_id="",cluster="my-cluster",cluster_type="SELF_HOSTED",job="cockroachdb",region="local",node=""} 0.000000 1696013730.0
admission_admitted_elastic_cpu{instance="",organization_id="",organization_label="",node_id="1",sla_type="",tenant_id="",cluster="my-cluster",cluster_type="SELF_HOSTED",job="cockroachdb",region="local",node=""} 0.000000 1696013740.0
admission_admitted_elastic_cpu{instance="",organization_id="",organization_label="",node_id="1",sla_type="",tenant_id="",cluster="my-cluster",cluster_type="SELF_HOSTED",job="cockroachdb",region="local",node=""} 0.000000 1696013750.0
....

Epic: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
Thanks for adding tests @koorosh :pray: - A couple comments on the 2nd commit (I know it wasn't you that wrote it, but I think we should clean it up a little) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-:-Nhbb1rb03-5Au34duQo:b-t1hms6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, and @maryliag)

___
*[`pkg/cli/tsdump.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-NhbRFWiEt3HmYKt3Dys:-NhbRFWiEt3HmYKt3Dyt:b6578co) ([raw file](https://github.com/cockroachdb/cockroach/blob/355f8c396b0e0ed167caf9a2ff9ff061d50ac0a6/pkg/cli/tsdump.go#L62)):*
> ```Go
> 		defer finish()
> 
> 		names, err := serverpb.GetInternalTimeseriesNamesFromServer(ctx, conn)
> ```

Hmm, not sure we want to remove this :thinking: - this makes `names` in the `DumpRequest` constructed below undefined. Seems like it's fixed in the following commit, though. Similar to the other comment, let's either merge the commits or make them both function independently. 
___
*[`pkg/cli/tsdump.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-NhbPUmY4QjXdCb3eO4Q:-NhbPUmY4QjXdCb3eO4R:b6p7v2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1ece30104258ca2bc9ae299da536d75665785e3/pkg/cli/tsdump.go#L74)):*
> ```Go
> 		}
> 		var w tsWriter
> 		switch debugTimeSeriesDumpOpts.format {
> ```

I'm having trouble reading this switch statement :thinking: - this doesn't compile..? I wonder if it was accidentally never closed? Or maybe it was meant to be part of the switch down below? It's a mystery :sweat_smile: 

EDIT: Ah! I think this is fixed in the following commit. We should probably either merge the two, or fix this one so that it can function on its own. 
___
*[`pkg/cli/tsdump.go` line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-NhbZcbF18HhLYZlBIM8:-NhbZcbF18HhLYZlBIM9:biybnx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1ece30104258ca2bc9ae299da536d75665785e3/pkg/cli/tsdump.go#L153)):*
> ```Go
> 				var data *tspb.TimeSeriesData
> 				dumper := ts.DefaultDumper{Send: func(d *tspb.TimeSeriesData) error {
> 					data = d
> ```

nit: I wonder if initializing a new DefaultDumper for each call of `decodeOne` is necessary. Can we just initialize a single one and reuse it in each call? 
___
*[`pkg/cli/tsdump.go` line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-NhbZyCOARtxuznACVSz:-NhbZyCOARtxuznACVT-:bfj0tas) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1ece30104258ca2bc9ae299da536d75665785e3/pkg/cli/tsdump.go#L164)):*
> ```Go
> 			ch := make(chan tup, 4096)
> 			go func() {
> 				defer close(ch)
> ```

Does this goroutine ever return/exit? Seems like it will just loop forever, until the CLI process exits. Maybe that's ok :man_shrugging: If so let's just add a comment noting that it's intentional.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @maryliag)

___
*[`pkg/cli/tsdump.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-NhbRFWiEt3HmYKt3Dys:-NhbjMUt-TWuoU3qBC4I:b56qff4) ([raw file](https://github.com/cockroachdb/cockroach/blob/355f8c396b0e0ed167caf9a2ff9ff061d50ac0a6/pkg/cli/tsdump.go#L62)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Hmm, not sure we want to remove this :thinking: - this makes `names` in the `DumpRequest` constructed below undefined. Seems like it's fixed in the following commit, though. Similar to the other comment, let's either merge the commits or make them both function independently.
</blockquote></details>

Squashed all commits as it all related to single change.
___
*[`pkg/cli/tsdump.go` line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-NhbZcbF18HhLYZlBIM8:-NhbcGr77lFrz8K0n3l4:bf38mqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1ece30104258ca2bc9ae299da536d75665785e3/pkg/cli/tsdump.go#L153)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: I wonder if initializing a new DefaultDumper for each call of `decodeOne` is necessary. Can we just initialize a single one and reuse it in each call?
</blockquote></details>

It won't work that way. We initialise `DefaultDumper` here to have available `data` variable in scope and reassign it from within provided Send function.
___
*[`pkg/cli/tsdump.go` line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-NhbZyCOARtxuznACVSz:-NhbhuAqC3MGHTS3l1ao:b-dfdqjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1ece30104258ca2bc9ae299da536d75665785e3/pkg/cli/tsdump.go#L164)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Does this goroutine ever return/exit? Seems like it will just loop forever, until the CLI process exits. Maybe that's ok :man_shrugging: If so let's just add a comment noting that it's intentional.
</blockquote></details>

You're right, it doesn't make any difference and put here "just in case" to make sure the channel will be closed. Will add a comment.

**Review by abarganier — APPROVED** [review]
:lgtm: - thank you for driving this home @koorosh! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-:-NhgLvkjCSqlZ_kW2Q8k:bupey3o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, and @maryliag)

___
*[`pkg/cli/tsdump.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-NhbRFWiEt3HmYKt3Dys:-NhgLnG74t9ZG6CEE_Q-:b-f7l6ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/355f8c396b0e0ed167caf9a2ff9ff061d50ac0a6/pkg/cli/tsdump.go#L62)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Squashed all commits as it all related to single change.
</blockquote></details>

Looks good, thanks! 
___
*[`pkg/cli/tsdump.go` line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-NhbZcbF18HhLYZlBIM8:-NhgLpt03Xm2ZmH0u1oG:blvotkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1ece30104258ca2bc9ae299da536d75665785e3/pkg/cli/tsdump.go#L153)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

It won't work that way. We initialise `DefaultDumper` here to have available `data` variable in scope and reassign it from within provided Send function.
</blockquote></details>

I see, thanks for explaining. LGTM.
___
*[`pkg/cli/tsdump.go` line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113037#-NhbZyCOARtxuznACVSz:-NhgLsRf15uRpMaAx9AV:b-9755fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1ece30104258ca2bc9ae299da536d75665785e3/pkg/cli/tsdump.go#L164)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

You're right, it doesn't make any difference and put here "just in case" to make sure the channel will be closed. Will add a comment.
</blockquote></details>

Thank you!

**Comment by koorosh** [comment]
TFTR!
bors r+

**Pull request merged**
