### PR TITLE
release-20.1: kv: introduce a rate limiter for the range consistency checker

### LINKED ISSUE #47290: kv/kvserver: better throttling/pacing of the consistency queue for bigger disks
The consistency checker queue periodically loops over all of the replicas on a node, and for each replica that the node holds the lease for, it initiates a consistency check operation. The consistency check operation involves computing a SHA 512 checksum for the data in the range at a particular point in time on all replicas. This is somewhat expensive in terms of both CPU and IO, but has been immensely valuable in tracking down bugs.

Right now there is a single knob to control the consistency checker pacing: `server.consistency_check.interval`. This setting defaults to `24h`. So every `24h` we expect to scan over all of the data in a cluster. With 1 TB of data on a node, we expect this scanning to produce a steady hum of 12 MB/sec of disk read traffic. That is already high, but perhaps tolerable. With 10 TB of data on a node, this scanning would produce a roar of 120 MB/sec of disk read traffic.

Screen Shot 2020-04-09 at 2 19 11 PM

Note the drop-off in disk read traffic when the consistency check interval was turned much higher (`10000h`) at 18:03.

The graph above was from a cluster doing a large import and each node had ~1.7 TB of data. The read traffic is higher than expected. I believe, but haven't proven, that is due to another deficiency of the consistency queue: it tends to queue and process new ranges immediately when they are created during splits, rather than spreading out their checking over the check interval.

In order to handle 10 TB of data per node, we need to significantly reduce the background read traffic of consistency checks. I suspect we'd be better served by a knob which throttles the rate rather than one that controls the frequency.

### PR DESCRIPTION
**Pull request by lunevalex**
Backport 4/4 commits from #49763, #50111, #50273, #50402

/cc @cockroachdb/release

---

Closes #47290

This commit introduces a new flag server.consistency_check.max_rate to control the rate at which the consistency checker may scan through the range to compute it's checksum. Without a rate limit in place the checker cmay overwhelm the cluster with sufficiently large nodes. For example on a 10B node the checker is expected to produce 120MB/second of disk reads. The flag is defined as bytes/second and set to 8MB/s by default. We expect the customers to continue to use it in conjunction with server.consistency_check.interval, which will givem the ability to control both the frequency and speed of checks.

Release note (performance improvement): Introduce a new flag server.consistency_check.max_rate expressed in bytes/second to throttle the rate at which cockroach scans through the disk to perform a consistency check. This control is necessary to ensure smooth performance on a cluster with large node sizes (i.e. in the 10TB+ range)

### CODE REVIEW

**Comment by tbg** [comment]
Let's hold off on this until we've figured out the flake in #48251.

**Comment by tbg** [comment]
@lunevalex you can cherry-pick the fix and then this is good to go.

**Comment by lunevalex** [comment]
@tbg added the cherry picks to make this work.

**Comment by tbg** [comment]
LGTM

**Review by tbg — APPROVED** [review]

**Pull request merged**
