### PR TITLE
roachtest: bump PredecessorVersion(20.1) to 19.2.6

### PR DESCRIPTION
**Pull request by nathanstilwell**
Release note: Increase predecessor version after 19.2 release

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Just curious, why?

**Comment by nathanstilwell** [comment]
@tbg There's a line in the [Release process](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-11.Tagtherelease) _"8. If applicable, update the map that roachtests use to map a version to a previous version, to reference the newly tagged version."_ I took that to mean that the predecessor should be the latest 19.2.x version. Is that not true?

**Comment by nathanstilwell** [comment]
bors r=tbg

**Comment by tbg** [comment]
It's true! It's just that I've never ever seen anyone actually do it. Props
to you.

**Comment by tbg** [comment]
(usually folks bump it because they need the higher patch version to avoid
some flake).

**Pull request merged**
