### PR TITLE
sql: improve error message for Test{Active,Idle}CancelSession

### LINKED ISSUE #33415: teamcity: failed test: TestActiveCancelSession
The following tests appear to have failed on master (test): TestActiveCancelSession

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestActiveCancelSession).

[#1075102](https://teamcity.cockroachdb.com/viewLog.html?buildId=1075102):

```
TestActiveCancelSession
...:26.508024 99872 server/node.go:696  [n?] connecting to gossip network to verify cluster ID...
I181231 14:38:26.508511 99872 server/node.go:721  [n?] node connected via gossip and verified as part of cluster "9549a22c-f001-439a-95f0-7e2b8b8dd898"
I181231 14:38:26.512107 100406 gossip/server.go:231  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:35063}
I181231 14:38:26.543376 99872 server/node.go:424  [n?] new node allocated ID 2
I181231 14:38:26.544287 99872 gossip/gossip.go:391  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:35063" > attrs:<> locality:<> ServerVersion:<major_val:2 minor_val:1 patch:0 unstable:3 > build_tag:"v2.2.0-alpha.20181217-315-ga8afcab" started_at:1546267106543815492 
I181231 14:38:26.546128 99872 storage/stores.go:243  [n2] read 0 node addresses from persistent storage
I181231 14:38:26.546654 99872 storage/stores.go:262  [n2] wrote 1 node addresses to persistent storage
I181231 14:38:26.553946 100003 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I181231 14:38:26.578881 99872 server/node.go:671  [n2] bootstrapped store [n2,s2]
I181231 14:38:26.581394 99872 server/node.go:545  [n2] node=2: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I181231 14:38:26.583938 99872 server/status/recorder.go:610  [n2] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I181231 14:38:26.588603 99872 server/server.go:1832  [n2] Could not start heap profiler worker due to: directory to store profiles could not be determined
I181231 14:38:26.591401 99872 server/server.go:1534  [n2] starting https server at 127.0.0.1:36449 (use: 127.0.0.1:36449)
I181231 14:38:26.591612 99872 server/server.go:1536  [n2] starting grpc/postgres server at 127.0.0.1:35063
I181231 14:38:26.591681 99872 server/server.go:1537  [n2] advertising CockroachDB node at 127.0.0.1:35063
I181231 14:38:26.599426 99872 server/server.go:1590  [n2] done ensuring all necessary migrations have run
I181231 14:38:26.599624 99872 server/server.go:1593  [n2] serving sql connections
I181231 14:38:26.758994 100513 server/server_update.go:66  [n2] no need to upgrade, cluster already at the newest version
I181231 14:38:26.773483 100516 sql/event_log.go:131  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:35063} Attrs: Locality: ServerVersion:2.1-3 BuildTag:v2.2.0-alpha.20181217-315-ga8afcab StartedAt:1546267106543815492 LocalityAddress:[]} ClusterID:9549a22c-f001-439a-95f0-7e2b8b8dd898 StartedAt:1546267106543815492 LastUp:1546267106543815492}
I181231 14:38:26.880849 100040 gossip/gossip.go:1513  [n1] node has connected to cluster via gossip
I181231 14:38:26.881992 100040 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I181231 14:38:27.856151 100596 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181231 14:38:27.858934 100595 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] transport racer
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181231 14:38:27.867779 100595 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] transport racer
1      [async] closedts-subscription
I181231 14:38:27.868734 100595 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] transport racer
I181231 14:38:27.869177 100596 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
I181231 14:38:27.929860 100597 rpc/nodedialer/nodedialer.go:90  [ct-client] unable to connect to n2: context canceled
I181231 14:38:27.965510 100111 kv/transport_race.go:113  transport race promotion: ran 49 iterations on up to 317 requests
I181231 14:38:27.978001 100579 rpc/nodedialer/nodedialer.go:90  [ct-client] unable to connect to n1: context canceled



TestActiveCancelSession
...
I181231 14:17:41.399136 105127 server/status/recorder.go:610  [n2] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I181231 14:17:41.399175 105127 server/server.go:1832  [n2] Could not start heap profiler worker due to: directory to store profiles could not be determined
I181231 14:17:41.399233 105127 server/server.go:1534  [n2] starting https server at 127.0.0.1:37041 (use: 127.0.0.1:37041)
I181231 14:17:41.399254 105127 server/server.go:1536  [n2] starting grpc/postgres server at 127.0.0.1:45517
I181231 14:17:41.399265 105127 server/server.go:1537  [n2] advertising CockroachDB node at 127.0.0.1:45517
I181231 14:17:41.400811 105127 server/server.go:1590  [n2] done ensuring all necessary migrations have run
I181231 14:17:41.400841 105127 server/server.go:1593  [n2] serving sql connections
I181231 14:17:41.418756 105664 rpc/nodedialer/nodedialer.go:90  [n1] unable to connect to n2: unable to look up descriptor for n2
I181231 14:17:41.428826 105184 server/server_update.go:66  [n2] no need to upgrade, cluster already at the newest version
I181231 14:17:41.430068 105130 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I181231 14:17:41.438474 105651 sql/event_log.go:131  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:45517} Attrs: Locality: ServerVersion:2.1-3 BuildTag:v2.2.0-alpha.20181217-315-ga8afcab StartedAt:1546265861397205509 LocalityAddress:[]} ClusterID:85e8fbdb-d985-4e83-a16f-b16e0db17dbc StartedAt:1546265861397205509 LastUp:1546265861397205509}
I181231 14:17:42.163428 105680 storage/replica_consistency.go:126  [n1,consistencyChecker,s1,r1/1:/M{in-ax}] triggering stats recomputation to resolve delta of {ContainsEstimates:true LastUpdateNanos:1546265861445053529 IntentAge:0 GCBytesAge:0 LiveBytes:-49708 LiveCount:-1018 KeyBytes:-48120 KeyCount:-1018 ValBytes:-1588 ValCount:-1018 IntentBytes:0 IntentCount:0 SysBytes:0 SysCount:0}
I181231 14:17:43.050133 105486 gossip/gossip.go:1513  [n2] node has connected to cluster via gossip
I181231 14:17:43.050352 105486 storage/stores.go:262  [n2] wrote 1 node addresses to persistent storage
I181231 14:17:43.182431 105215 gossip/gossip.go:1513  [n1] node has connected to cluster via gossip
I181231 14:17:43.182650 105215 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I181231 14:17:51.146597 105376 server/status/runtime.go:464  [n1] runtime stats: 194 MiB RSS, 688 goroutines, 27 MiB/61 MiB/109 MiB GO alloc/idle/total, 18 MiB/54 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (733x), 6.9 MiB/6.9 MiB (r/w)net
W181231 14:17:51.153953 105378 server/node.go:885  [n1,summaries] health alerts detected: {Alerts:[{StoreID:1 Category:METRICS Description:ranges.underreplicated Value:1}]}
I181231 14:17:51.401195 105619 server/status/runtime.go:464  [n2] runtime stats: 195 MiB RSS, 688 goroutines, 0 B/0 B/0 B GO alloc/idle/total, 19 MiB/55 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (733x), 7.5 MiB/7.5 MiB (r/w)net
E181231 14:17:51.419416 105980 sql/distsqlrun/flow_registry.go:233  [intExec=read orphaned table leases] flow id:ee9df3d0-46e0-4f1a-ab23-5a248e4ea0fd : 1 inbound streams timed out after 10s; propagated error throughout flow
I181231 14:17:51.738964 106036 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181231 14:17:51.739163 106035 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
W181231 14:17:51.740975 105486 gossip/gossip.go:1499  [n2] no incoming or outgoing connections
I181231 14:17:51.741221 106036 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
I181231 14:17:51.744347 106035 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription




```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #33419: sql: TestIdleCancelSession failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/a8afcabd753eff930f2f1fef5e79718439fbf65a

Parameters:
```
TAGS=
GOFLAGS=
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=TestIdleCancelSession PKG=github.com/cockroachdb/cockroach/pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1075315&tab=buildLog

```
I190101 06:20:16.745694 105516 server/status/recorder.go:610  [n2] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I190101 06:20:16.745717 105516 server/server.go:1832  [n2] Could not start heap profiler worker due to: directory to store profiles could not be determined
I190101 06:20:16.745771 105516 server/server.go:1534  [n2] starting https server at 127.0.0.1:39931 (use: 127.0.0.1:39931)
I190101 06:20:16.745784 105516 server/server.go:1536  [n2] starting grpc/postgres server at 127.0.0.1:38215
I190101 06:20:16.745794 105516 server/server.go:1537  [n2] advertising CockroachDB node at 127.0.0.1:38215
I190101 06:20:16.746594 105516 server/server.go:1590  [n2] done ensuring all necessary migrations have run
I190101 06:20:16.746698 105516 server/server.go:1593  [n2] serving sql connections
I190101 06:20:16.755891 105830 rpc/nodedialer/nodedialer.go:90  [n1] unable to connect to n2: unable to look up descriptor for n2
I190101 06:20:16.756275 105519 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I190101 06:20:16.760652 105929 server/server_update.go:66  [n2] no need to upgrade, cluster already at the newest version
I190101 06:20:16.809256 105932 sql/event_log.go:131  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:38215} Attrs: Locality: ServerVersion:2.1-3 BuildTag:v2.2.0-alpha.20181217-315-ga8afcab StartedAt:1546323616743408444 LocalityAddress:[]} ClusterID:ffd52fb9-a3e1-49bb-9945-1cc90917dadc StartedAt:1546323616743408444 LastUp:1546323616743408444}
I190101 06:20:17.561278 106127 storage/replica_consistency.go:126  [n1,consistencyChecker,s1,r1/1:/M{in-ax}] triggering stats recomputation to resolve delta of {ContainsEstimates:true LastUpdateNanos:1546323616758068240 IntentAge:0 GCBytesAge:0 LiveBytes:-49708 LiveCount:-1018 KeyBytes:-48120 KeyCount:-1018 ValBytes:-1588 ValCount:-1018 IntentBytes:0 IntentCount:0 SysBytes:0 SysCount:0}
I190101 06:20:18.190206 105604 gossip/gossip.go:1513  [n1] node has connected to cluster via gossip
I190101 06:20:18.190350 105604 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I190101 06:20:18.588450 105917 gossip/gossip.go:1513  [n2] node has connected to cluster via gossip
I190101 06:20:18.588597 105917 storage/stores.go:262  [n2] wrote 1 node addresses to persistent storage
I190101 06:20:26.542268 105765 server/status/runtime.go:464  [n1] runtime stats: 187 MiB RSS, 684 goroutines, 28 MiB/59 MiB/107 MiB GO alloc/idle/total, 17 MiB/47 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (742x), 6.4 MiB/6.4 MiB (r/w)net
W190101 06:20:26.609652 105767 server/node.go:885  [n1,summaries] health alerts detected: {Alerts:[{StoreID:1 Category:METRICS Description:ranges.underreplicated Value:1}]}
I190101 06:20:26.747722 106040 server/status/runtime.go:464  [n2] runtime stats: 188 MiB RSS, 684 goroutines, 33 MiB/54 MiB/107 MiB GO alloc/idle/total, 18 MiB/48 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (742x), 6.2 MiB/6.2 MiB (r/w)net
E190101 06:20:26.757718 106407 sql/distsqlrun/flow_registry.go:233  [intExec=read orphaned table leases] flow id:c96335f9-98c0-4a9a-a535-0072a4762188 : 1 inbound streams timed out after 10s; propagated error throughout flow
I190101 06:20:27.048809 106446 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I190101 06:20:27.048866 106447 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
W190101 06:20:27.060213 105917 gossip/gossip.go:1499  [n2] no incoming or outgoing connections
I190101 06:20:27.060649 106447 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
I190101 06:20:27.060844 106446 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
--- FAIL: TestIdleCancelSession (10.57s)
	run_control_test.go:321: expected 2 sessions but found 3

```

### PR DESCRIPTION
**Pull request by petermattis**
When the number of sessions differs from the number expected, output the
sessions.

Fixes #33419
Fixes #33415

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Note that I don't think this actually fixes the linked issues, but I'm unable to reproduce the failure there and would prefer to close them out rather than leave them open indefinitely. I've been `roachprod-stress`-ing those tests for 20 min with no failures seen so far.

Also: `maxtrix`?

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34063#-:-LWNBgXE7TwHFt5rFF2d:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
well without looking at anything I can bet what the failure is - some background crap like the thing that periodically adopts jobs. Peter, use your weight to get that stuff out of `show queries / sessions`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34063#-:-LWNByTTA5M49ihHctMZ:bz13byw)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by petermattis** [comment]
> well without looking at anything I can bet what the failure is - some background crap like the thing that periodically adopts jobs. Peter, use your weight to get that stuff out of show queries / sessions.

Hmm, perhaps it is the background deletion of orphaned leases that I just worked on last week. I didn't actually remove that, but it is hard to trigger. That gives me an idea for making it easier to trigger this failure. Thanks!

**Comment by petermattis** [comment]
Ok, it is almost certainly the internal session used for deleting orphaned leases. One of the test failures has this in its logs:

`E181231 14:17:51.419416 105980 sql/distsqlrun/flow_registry.go:233  [intExec=read orphaned table leases] flow id:ee9df3d0-46e0-4f1a-ab23-5a248e4ea0fd : 1 inbound streams timed out after 10s; propagated error throughout flow`

That error is surprising for this test, though it explains why the test failure occurred. @andreimatei Do you have any thoughts about the cause of this error?

Seems straightforward to exclude internal sessions from the `SHOW CLUSTER SESSIONS` query for this test.

**Comment by andreimatei** [comment]
> That error is surprising for this test, though it explains why the test failure occurred. @andreimatei Do you have any thoughts about the cause of this error?

No, not in the context of this test. Very curious. It'd be fantastic if you could reproduce and tell @ajwerner.

> Seems straightforward to exclude internal sessions from the SHOW CLUSTER SESSIONS query for this test.

I think we should exclude them from `show sessions` by default, test or not test.

**Comment by petermattis** [comment]
> No, not in the context of this test. Very curious. It'd be fantastic if you could reproduce and tell @ajwerner.

No luck reproducing so far.

> I think we should exclude them from show sessions by default, test or not test.

Yeah, let me open an issue about that.

**Comment by petermattis** [comment]
> Yeah, let me open an issue about that.

I started to write up the issue, then decided to "just do it".

@knz I'm looping you into this. My rationale for hiding internal queries/sessions by default is that we're not doing this right in tests, so it seems likely users won't be expecting these queries either. 

Note that this is still a WIP. I haven't added tests for this new functionality yet, and it is possible I've broken other tests. I want to get sign-off that this is desirable before proceeding further.

**Review by knz — COMMENTED** [review]
LGTM modulo understanding that the match should be on "^$ " and not "^$ internal-". See my comment below.

> Reviewed 2 of 2 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34063#-:-LWRiGeeCkZl5uAVYKSi:b-l5m8vk)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_queries.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34063#-LWRhnlF3Jgd-e03aL97:-LWRhnlHEexWqGBDQK_n:brpr05) ([raw file](https://github.com/cockroachdb/cockroach/blob/9046a8376e04c16922fa2ea3a51635bbf734be8f/pkg/sql/show_queries.go#L31)):*
> ```Go
> 	var filter string
> 	if !n.All {
> 		filter = " WHERE application_name NOT LIKE '$ internal-%'"
> ```

Use `sql.InternalAppNamePrefix` and avoid matching the string `internal-`: the contract internal/external is on the `InternalAppNamePrefix`, the `"internal-`" part that comes afterwards is arbitrary and a current implementation artifact.
___
*[pkg/sql/show_sessions.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34063#-LWRiEGn8lqv4WJp_EaR:-LWRiEGn8lqv4WJp_EaS:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/9046a8376e04c16922fa2ea3a51635bbf734be8f/pkg/sql/show_sessions.go#L31)):*
> ```Go
> 	var filter string
> 	if !n.All {
> 		filter = " WHERE application_name NOT LIKE '$ internal-%'"
> ```

ditto

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34063)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_queries.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34063#-LWRhnlF3Jgd-e03aL97:-LWRjhS-2FsvidUmfLzm:bqgn5cl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9046a8376e04c16922fa2ea3a51635bbf734be8f/pkg/sql/show_queries.go#L31)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Use `sql.InternalAppNamePrefix` and avoid matching the string `internal-`: the contract internal/external is on the `InternalAppNamePrefix`, the `"internal-`" part that comes afterwards is arbitrary and a current implementation artifact.
</blockquote></details>

Hmm, I added the `internal-` bit because I noticed that the SQL shell gets the application name `$ cockroach sql`. That isn't an internal connection and I don't think we'd want to strip it out of `SHOW SESSIONS` by default.

Hmm, `cli/sql_util.go` is doing:

```
	if options.Get("application_name") == "" && appName != "" {
		options.Set("application_name", sql.InternalAppNamePrefix+appName)
	}
```

Should it be including `sql.InternalAppNamePrefix`?

Perhaps I should add another column to the `crdb_internal.{node,cluster}_{queries,sessions}` tables that indicates that the session is internal. Thoughts?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34063)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_queries.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34063#-LWRhnlF3Jgd-e03aL97:-LWRmAf19urP6jFNiYqq:b-h2c3a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9046a8376e04c16922fa2ea3a51635bbf734be8f/pkg/sql/show_queries.go#L31)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Hmm, I added the `internal-` bit because I noticed that the SQL shell gets the application name `$ cockroach sql`. That isn't an internal connection and I don't think we'd want to strip it out of `SHOW SESSIONS` by default.

Hmm, `cli/sql_util.go` is doing:

```
	if options.Get("application_name") == "" && appName != "" {
		options.Set("application_name", sql.InternalAppNamePrefix+appName)
	}
```

Should it be including `sql.InternalAppNamePrefix`?

Perhaps I should add another column to the `crdb_internal.{node,cluster}_{queries,sessions}` tables that indicates that the session is internal. Thoughts?
</blockquote></details>

There is something nice about using `$ ` as an indicator that a session should be hidden by default: it gives users the ability to create hidden sessions, similar to the way files prefixed with `.` are hidden in directory listings by default.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34063)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_queries.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34063#-LWRhnlF3Jgd-e03aL97:-LWRmmf28h-QCYn220-z:berwumj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9046a8376e04c16922fa2ea3a51635bbf734be8f/pkg/sql/show_queries.go#L31)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

There is something nice about using `$ ` as an indicator that a session should be hidden by default: it gives users the ability to create hidden sessions, similar to the way files prefixed with `.` are hidden in directory listings by default.
</blockquote></details>

`cockroach demo` has a similar issue: the application name shows up as `$ cockroach demo`.

**Comment by knz** [comment]
For context the primary consumer of the $ was envisioned to be the web UI (hiding stuff, although i believe it's not implemented yet) 


HOWEVER the actual current main user is telemetry: we scrub app names for telemetry unless they are prefixed by $.

That's why the CLI commands do it: this is an independent change/choice (by Jordan IIRC) after $ was introduced to ensure we can track SQL usage by CLI commands in telemetry.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by petermattis** [comment]
@knz Thanks for the additional context. How would you feel about a separate control for determining whether an application name should be scrubbed? I don't have a good though on how to put this control into the application name, but perhaps it can be another session setting. Something like `SET scrub_application_name = false` (the default would be true).

Or perhaps we should hard code not scrubbing the app names `cockroach {sql,demo}`. I mention this option because it is somewhat odd that a user might accidentally prefix their app name with `$ ` and then suddenly it isn't scrubbed.

Cc @jordanlewis

**Comment by knz** [comment]
> Thanks for the additional context. How would you feel about a separate control for determining whether an application name should be scrubbed? I don't have a good though on how to put this control into the application name, but perhaps it can be another session setting. Something like SET scrub_application_name = false (the default would be true).

Yes this seems entirely reasonable to me.

> Or perhaps we should hard code not scrubbing the app names cockroach {sql,demo}. I mention this option because it is somewhat odd that a user might accidentally prefix their app name with $ and then suddenly it isn't scrubbed.

My concern with this is that I can see cases where users put the word "cockroach" in their app name because they're eg. comparing their app with crdb vs their app for pg or something.

**Comment by petermattis** [comment]
> My concern with this is that I can see cases where users put the word "cockroach" in their app name because they're eg. comparing their app with crdb vs their app for pg or something.

My proposal is to only whitelist the exact names `cockroach demo` and `cockroach sql`. Any other app name containing `cockroach` would be scrubbed.

**Comment by knz** [comment]
we probably still want the SQL sent by `cockroach user`, `cockroach dump`, and in general all CLI commands that use SQL.

**Comment by petermattis** [comment]
> we probably still want the SQL sent by cockroach user, cockroach dump, and in general all CLI commands that use SQL.

You've got a good point. I missed that there were more application names being used from the cli. Perhaps the session variable is the way to go. Let me think on this for a bit.

**Comment by petermattis** [comment]
> You've got a good point. I missed that there were more application names being used from the cli. Perhaps the session variable is the way to go. Let me think on this for a bit.

This PR fell off my radar. I haven't had a chance to think about whether a session variable is the way to go. @knz Do you have a strong opinion?

**Comment by knz** [comment]
I'll patch up your PR, give me a minute

**Pull request closed without merging**
