### PR TITLE
kvserver: fixes to BenchmarkFlowControlV2Basic

### PR DESCRIPTION
**Pull request by sumeerbhola**
Fixed a bug that was using incorrect number of iterations. And made the benchmark more stable, and useful for smaller number of iterations, by using OverrideTokenDeduction to deduct 1MiB of tokens for tiny writes.

Informs #128033

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135121#-:-OBfH9FKDNPl6JefRsd4:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Comment by rafiss** [comment]
blathers backport 24.3

**Pull request merged**
