### PR TITLE
SQL: Reset database zone configuration builtin

### LINKED ISSUE #66855: multiregionccl: create a builtin to repair multi-region zone configurations
**Is your feature request related to a problem? Please describe.**
This is a followup to  #66637 which was a bug where we were not correctly setting the (table locality implied) zone configuration on an index. This, and other possible bugs where the zone configuration isn't correctly set for multi-region primitives, can lead to a poor experience as they violate user expectations. Furthermore, it's impossible to distinguish the case when users have legitimately modified zone configurations from a bug. This renders a possible migration impossible. The alternative, manual zone configuration surgery, is error prone and cumbersome. 

**Describe the solution you'd like**
The proposal here is to create a builtin that can alleviate some of this manual migration pain. Zone configurations can be fully re-generated using descriptor state. Let's introduce `crdb_internal.repair_multi_region_zone_configs` to do so. It might be worth creating two versions of this builtin -- one that operates on tables and another that operates on the entire database (including objects in the database). The builtin would wholesale regenerate and update zone configurations, independent of if a multi-region field was modified or not. This will allow users to quickly repair tables (or their entire database).

### PR DESCRIPTION
**Pull request by ajstorm**
The new(ish) multi-region syntax introduced in 21.1 sets a zone
configuration at the database level. This zone configuration
can diverge from its original state either because the user has
manually overridden it, or because the system hasn't kept it up
to date as the database has evolved (though there are no known
issues where this occurs). In either case, the user may wish to
revert the zone configurations for a given databases back to its
original state.

The new builtin takes a database ID, and resets its underlying zone
configuration to its original state (as specified by the underlying
RegionConfig). For non-multi-region databases, the builtin no-ops.

Resolves #66855.

Release note (sql change): Creates a builtin to reset the zone configuration
of a multi-region database. This builtin can be helpful in
cases where the user has overridden the zone configuration for a given
database and wishes to revert back to the original system-specified
state.

### CODE REVIEW

**Comment by ajstorm** [comment]
WIP status was a typo that's since been corrected.  This is ready for review.

**Review by arulajmani — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68280)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @nihalpednekar, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 1632 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68280#-Mft-DGU3nZV5YecPXhF:-Mft-DGU3nZV5YecPXhG:brkd301) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c5854e22f4297b95c552f1d6e451634856aa62/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L1632)):*
> ```
> 
> statement ok
> CREATE DATABASE "rebuild_zc_db" primary region "ca-central-1" regions "ap-southeast-2", "us-east-1"
> ```

You might need to `USE rebuild_zc_db` for the call to `validate_multi_region_zone_configs` further down?
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 1719 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68280#-Mft0NwWDDsZs30yzisE:-Mft0NwWDDsZs30yzisF:b-rguh9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c5854e22f4297b95c552f1d6e451634856aa62/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L1719)):*
> ```
>  voter_constraints = '[+region=ca-central-1]',
>  lease_preferences = '[[+region=ca-central-1]]'
> ```

Let's add a test to ensure thing thing errors if given a table ID? 
___
*[pkg/sql/region_util.go, line 875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68280#-Mft-xr_5rVWccMyaoKp:-Mft-xr_5rVWccMyaoKq:bhkwqtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c5854e22f4297b95c552f1d6e451634856aa62/pkg/sql/region_util.go#L875)):*
> ```Go
> 	}
> 
> 	if err := multiregion.ValidateRegionConfig(regionConfig); err != nil {
> ```

I think we can remove this call because `SynthesizeRegionConfig` validates the thing before returning. 
___
*[pkg/sql/region_util.go, line 914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68280#-Mft06P1DDxGS2l4jKQ6:-Mft06P1DDxGS2l4jKQ7:b3zr23d) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c5854e22f4297b95c552f1d6e451634856aa62/pkg/sql/region_util.go#L914)):*
> ```Go
> 	}
> 
> 	if err := multiregion.ValidateRegionConfig(regionConfig); err != nil {
> ```

Same comment as above about validation.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68280)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @nihalpednekar, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 1632 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68280#-Mft-DGU3nZV5YecPXhF:-MgBguWm98JummOHgrhw:bqllwh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c5854e22f4297b95c552f1d6e451634856aa62/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L1632)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

You might need to `USE rebuild_zc_db` for the call to `validate_multi_region_zone_configs` further down?
</blockquote></details>

Great catch!  Added.
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 1719 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68280#-Mft0NwWDDsZs30yzisE:-MgBkSd64VNo-ygsz-AL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c5854e22f4297b95c552f1d6e451634856aa62/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L1719)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's add a test to ensure thing thing errors if given a table ID? 
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68280#-Mft-xr_5rVWccMyaoKp:-MgBoV7ODU-TcPoFL9Hk:b59lpme) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c5854e22f4297b95c552f1d6e451634856aa62/pkg/sql/region_util.go#L875)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think we can remove this call because `SynthesizeRegionConfig` validates the thing before returning. 
</blockquote></details>

Interesting.  I borrowed this from a call in ALTER DATABASE.  I've added an additional commit to pull that one out too.
___
*[pkg/sql/region_util.go, line 914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68280#-Mft06P1DDxGS2l4jKQ6:-MgBppod3rKOTIhVmRrk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39c5854e22f4297b95c552f1d6e451634856aa62/pkg/sql/region_util.go#L914)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same comment as above about validation. 
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68280#-:-MgBv6Ok9Ov4dLmqntiI:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nihalpednekar and @otan)

**Comment by ajstorm** [comment]
TFTR!

bors  r=arulajmani

**Pull request merged**
