### PR TITLE
storage: bump Pebble and fix Comparer

### LINKED ISSUE #127914: storage: Compare can return incorrect results when only suffixes are compared
The Compare code below handles the case where only suffixes are compared. However, `normalizeEngineKeyVersionForCompare` will later be called without the sentinel byte and it will not function properly, since its logic is based on the length.

https://github.com/cockroachdb/cockroach/blob/e8e4cce43547c18c7cb988c42c3f2b7065717f51/pkg/storage/pebble.go#L414

This could in principle result in an incorrect result when a suffix has the synthetic bit or zero logical timestamp. In practice, it might not be an issue - we compare "bare" suffixes for range keys and range keys all use just the 8-byte wall time which is already normalized.

Jira issue: CRDB-40669

### PR DESCRIPTION
**Pull request by RaduBerinde**
The `EngineComparer` has a bug when comparing bare suffixes - we call
the normalization function on a slice without the sentinel byte; that
function's logic is based on length so it will not function properly.

Currently, I don't think this bug can manifest in any visible problems
in practice - we compare bare suffixes only for range keys and those
suffixes never have a logical component or synthetic bit. It is
conceivable that we compare those with some actual key suffix (e.g.
when applying masking) but that would only matter if a range key
prefix and an existing key in that range have the same timestamp,
which should never happen.

We now have a separate `CompareSuffixes` function which is used for
bare suffixes. This simplifies the implementation, allows us to add
more assertions, and allows testing the `Compare` function (since the
result can be derived from `Split` and `CompareSuffixes`).

We also improve the comparer testing to include these special cases of
version bytes that must be ignored, and we use the new Pebble
`CheckComparer` test to verify the internal consistency of the
comparer.

Thanks to the more strict checks, several cases of passing
`roachpb.Key`s unencoded (i.e. without the sentinel byte) were found
and fixed.

Pebble changes:

 * [`1b22d0b7`](https://github.com/cockroachdb/pebble/commit/1b22d0b7) base: add CompareSuffixes to Comparer
 * [`bcbe8d78`](https://github.com/cockroachdb/pebble/commit/bcbe8d78) keyspan: use slices.Sort functions
 * [`8af904fa`](https://github.com/cockroachdb/pebble/commit/8af904fa) sstable/block: move Compress, Decompress, DecompressedLen
 * [`21672e31`](https://github.com/cockroachdb/pebble/commit/21672e31) sstable/block: move blockType to block.CompressionIndicator
 * [`c73ffdb8`](https://github.com/cockroachdb/pebble/commit/c73ffdb8) sstable/block: move Compression enum from sstable
 * [`e3782de2`](https://github.com/cockroachdb/pebble/commit/e3782de2) colblk: add keyspan block writer, reader, iterator
 * [`ad3a2f0b`](https://github.com/cockroachdb/pebble/commit/ad3a2f0b) manifest: fix incorrect Annotator pointer aggregation
 * [`4589d053`](https://github.com/cockroachdb/pebble/commit/4589d053) sstable: implement Writer.DeleteRange using RawWriter.EncodeSpan
 * [`6e60d6ba`](https://github.com/cockroachdb/pebble/commit/6e60d6ba) internal/{rangedel,rangekey}: take Span by value
 * [`0ef38b39`](https://github.com/cockroachdb/pebble/commit/0ef38b39) sstable: remove WriterOption
 * [`9cbad0b5`](https://github.com/cockroachdb/pebble/commit/9cbad0b5) db: Add BenchmarkPointDeletedSwath
 * [`e326a015`](https://github.com/cockroachdb/pebble/commit/e326a015) sstable: clean up use-filter-block logic
 * [`ce28942d`](https://github.com/cockroachdb/pebble/commit/ce28942d) sstable: twoLevelIterator: unembed singleLevelIterator
 * [`b6400d63`](https://github.com/cockroachdb/pebble/commit/b6400d63) sstable: rename NewIterWithBlockPropertyFiltersAndContextEtc
 * [`a6580b19`](https://github.com/cockroachdb/pebble/commit/a6580b19) sstable: remove compaction iterator wrappers
 * [`1cc8f4c9`](https://github.com/cockroachdb/pebble/commit/1cc8f4c9) sstable: remove NewIterWithBlockPropertyFilters
 * [`3fded19e`](https://github.com/cockroachdb/pebble/commit/3fded19e) sstable: improve TrivialReaderProvider
 * [`034fd8ef`](https://github.com/cockroachdb/pebble/commit/034fd8ef) db: remove IterOptions.TableFilter
 * [`cde3df0f`](https://github.com/cockroachdb/pebble/commit/cde3df0f) manifest: clean up Level
 * [`368636f0`](https://github.com/cockroachdb/pebble/commit/368636f0) sstable: show filenum when metadata is corrupted
 * [`f8e117d3`](https://github.com/cockroachdb/pebble/commit/f8e117d3) db: fix missing close in TestOverlappingIngestedSSTs
 * [`d3209700`](https://github.com/cockroachdb/pebble/commit/d3209700) deps: update snappy to 43d5d4c
 * [`f0a0e2bb`](https://github.com/cockroachdb/pebble/commit/f0a0e2bb) sstable: split Writer into Writer and RawWriter
 * [`ed42fb43`](https://github.com/cockroachdb/pebble/commit/ed42fb43) db: don't load large filter blocks for flushable ingests
 * [`ca2b210f`](https://github.com/cockroachdb/pebble/commit/ca2b210f) db: strictly enforce prefix in [flushable]BatchIter.SeekPrefixGE
 * [`44e5fb43`](https://github.com/cockroachdb/pebble/commit/44e5fb43) db: store *Comparer on Batch
 * [`e36d078a`](https://github.com/cockroachdb/pebble/commit/e36d078a) manifest: improve `Annotator` interface with generics
 * [`1cedb60f`](https://github.com/cockroachdb/pebble/commit/1cedb60f) sstable: don't skipBackward past empty blocks with hideObsolete
 * [`4cf4f852`](https://github.com/cockroachdb/pebble/commit/4cf4f852) colblk: clarify PrefixBytes comments
 * [`2752abb9`](https://github.com/cockroachdb/pebble/commit/2752abb9) keyspan: add contexts to keyspan iterators
 * [`54e5ba64`](https://github.com/cockroachdb/pebble/commit/54e5ba64) db: use testkeys comparer in TestTracing
 * [`0e232926`](https://github.com/cockroachdb/pebble/commit/0e232926) db: convert TestTracing to datadriven
 * [`89e5644a`](https://github.com/cockroachdb/pebble/commit/89e5644a) db: Add BenchmarkQueueWorkload
 * [`72c3f550`](https://github.com/cockroachdb/pebble/commit/72c3f550) base: make Compare more restrictive
 * [`4f01ec48`](https://github.com/cockroachdb/pebble/commit/4f01ec48) sstable: plumb context to range iterator constructors
 * [`de0e731a`](https://github.com/cockroachdb/pebble/commit/de0e731a) colblk: add facility for cloning an Array to a []T
 * [`a2f6d39a`](https://github.com/cockroachdb/pebble/commit/a2f6d39a) colblk: randomize BundleSizes in block writer randomized test
 * [`b26e6326`](https://github.com/cockroachdb/pebble/commit/b26e6326) colblk: implement a common interface across column data accessors
 * [`6492e866`](https://github.com/cockroachdb/pebble/commit/6492e866) colblk: make decoder function signatures consistent
 * [`dbf9ab67`](https://github.com/cockroachdb/pebble/commit/dbf9ab67) compact: remove unused parameter in pickAutoLPositive

Release note: none.
Fixes: #127914

### CODE REVIEW

**Comment by RaduBerinde** [comment]
*[`pkg/storage/pebble.go` line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128043#-O3DKGSa61jEzxwhjK1W:-O3DKGSa61jEzxwhjK1X:bq22gw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/323ceb50397527ed9ff18a9b6449fa1235d3cc62/pkg/storage/pebble.go#L448)):*
> ```Go
> // could be MVCC timestamps).
> func EngineKeyCompare(a, b []byte) int {
> 	// TODO(radu): Pebble sometimes passes empty "keys" and we have to tolerate
> ```

Unfortunately there were too many instances of this in Pebble to fix right now.

**Review by jbowens — APPROVED** [review]
:lgtm_strong: 

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128043#-:-O3DQW7cD3jFZy0Djdo7:b-uwkowd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

___
*[`pkg/storage/pebble.go` line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128043#-O3DO96v66VX4trG-0Xs:-O3DO3KA-uT8oWXlzGy8:brdtt2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/323ceb50397527ed9ff18a9b6449fa1235d3cc62/pkg/storage/pebble.go#L425)):*
> ```Go
> func EngineKeySplit(k []byte) int {
> 	// TODO(radu): Pebble sometimes passes empty "keys" and we have to tolerate
> 	// them until we fix that.
> ```

dang, even when an empty "key" has never been committed? :(
___
*[`pkg/storage/pebble.go` line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128043#-O3DP6Xt9ZDKVdAdt-Hj:-O3DP6Xt9ZDKVdAdt-Hk:b-14y65h) ([raw file](https://github.com/cockroachdb/cockroach/blob/323ceb50397527ed9ff18a9b6449fa1235d3cc62/pkg/storage/pebble.go#L478)):*
> ```Go
> 	return bytes.Compare(
> 		normalizeEngineSuffixForCompare(b[bSuffixStart:]),
> 		normalizeEngineSuffixForCompare(a[aSuffixStart:]),
> ```

these `Split` and `Compare` implementations are much easier to read now too :100: 
___
*[`pkg/storage/pebble.go` line 529 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128043#-O3DPU771UjOtG3e6Vlb:-O3DPU771UjOtG3e6Vlc:b-rk0cv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/323ceb50397527ed9ff18a9b6449fa1235d3cc62/pkg/storage/pebble.go#L529)):*
> ```Go
> 
> // normalizeEngineSuffixForCompare takes a non-empty key suffix (including the
> // trailing sentinel byte) and returns a prefix of the buffer that should be
> ```

should this say "version length byte"? I thought the "sentinel byte" always referred to the zero byte that delimits the prefix and the suffix.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128043#-:-O3DcczG6oJCJRSOLZ2V:b-814g8k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/storage/pebble.go` line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128043#-O3DO96v66VX4trG-0Xs:-O3DbbNE9TRXQ2A-B-8S:b-dcruhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/323ceb50397527ed9ff18a9b6449fa1235d3cc62/pkg/storage/pebble.go#L425)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

dang, even when an empty "key" has never been committed? :(
</blockquote></details>

Yup, here's an incomplete list so far:
https://github.com/cockroachdb/pebble/compare/master...RaduBerinde:no-empty-key-cmp?expand=1
___
*[`pkg/storage/pebble.go` line 529 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128043#-O3DPU771UjOtG3e6Vlb:-O3DcC7fAdjCYK8_oaRJ:b-50ima0) ([raw file](https://github.com/cockroachdb/cockroach/blob/323ceb50397527ed9ff18a9b6449fa1235d3cc62/pkg/storage/pebble.go#L529)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

should this say "version length byte"? I thought the "sentinel byte" always referred to the zero byte that delimits the prefix and the suffix.
</blockquote></details>

Done.

I used "suffix length byte". We use "version" (as in `EngineKey.Version`) for the suffix without that byte.

**Pull request merged**
