### PR TITLE
storage: fix two bugs around parallel commit state transitions

### PR DESCRIPTION
**Pull request by nvb**
This PR commits two issues I've noticed over the past week with parallel commits. The first is more severe but I've never actually seen it cause any issues. The second is less severe and materializes as a scary sounding error message when nothing wrong actually happened.

The two bugs are:
1. we weren't checking for retry errors when re-staging a transaction record
2. we weren't considering that a transaction push could observe an outdated parallel commit attempt

Both of these bugs are now fixed. See the individual commits for more details.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I pulled the first commit 8ac3af58610f991928dd28bd7c6e8a0abbc60e6a (moving transaction related unit tests to replica_txn_text.go) out of this PR because it was causing `TestMergeQueue` to be stressed with a short timeout in CI, which the test doesn't appear to like now or in the past (at least as far back as 725b1160ef87c34ec4433a070fb51509d821c1df). It is also making this painful to keep cleanly based on `master`.

**Review by tbg — APPROVED** [review]
Oof, good catch! That line looked pretty harmless.

> 1. re-staging a transaction record in a single epoch
> 2. staging a transaction record in an epoch after a previous epoch
>    had already staged a transaction record before restarting

Could you brush up the commit message to make the bug (and potential fallout) more obvious? Strawman below

> When an `EndTransaction` request hit a `STAGING` existing record, we were failing to call `isEndTransactionTriggeringRetryError`, which could in principle allow transactional anomalies. For example, xxx

I'm not sure enough of how this could've gone wrong to put into words. Are you thinking of the case in which a txn stages, gets a retry error, refreshes, stages again and succeeds despite now needing to get another retry error? Couldn't that only happen if a write got pushed, and wouldn't the outcome of the stage not matter in that case? And your other example, are you worried about a lower-epoch overwriting a higher-epoch? It isn't clear to me from the wording whether you're worried about that or whether a txn restart is just one way to get into the stage where there's already some staging txn record present.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-:-LhZblGN0Q1DMZvR_oKt:b-8ktro6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_committer.go, line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-LhZdFpFDzEzwk6w5Qm5:-LhZdFpFDzEzwk6w5Qm6:b-gsdola) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d0e270e890d4a0c1d1a7ba12ddd332bd9e6b615/pkg/kv/txn_interceptor_committer.go#L231)):*
> ```Go
> 	// This also has the side-effect of kicking off intent resolution.
> 	mergedIntentSpans, _ := mergeIntoSpans(et.IntentSpans, et.InFlightWrites)
> 	tc.makeTxnCommitExplicitAsync(ctx, br.Txn, mergedIntentSpans, et.NoRefreshSpans)
> ```

Is this change material for the bug fixed in this PR? Not passing it would just disable that optimization, right? (I'm fine with a drive-by fix, just trying to understand where it's coming from).
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-LhZeAByDXYdfHzjKkKc:-LhZeAByDXYdfHzjKkKd:b-834n6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5256fedbc4dd97e2c65989fe8173e777d17045f/pkg/storage/batcheval/cmd_end_transaction.go#L271)):*
> ```Go
> 		// If the transaction is still PENDING, determine whether the commit
> 		// should be rejected.
> 		if reply.Txn.Status == roachpb.PENDING {
> ```

Oops.
___
*[pkg/storage/batcheval/cmd_end_transaction_test.go, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-LhZk_IB4ehRdXQ8Uq8M:-LhZk_IB4ehRdXQ8Uq8N:bauzbju) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d0e270e890d4a0c1d1a7ba12ddd332bd9e6b615/pkg/storage/batcheval/cmd_end_transaction_test.go#L193)):*
> ```Go
> 			// Standard case where a transaction record is created during a
> 			// parallel commit when all writes are still in-flight.
> 			name: "record missing, can create, try stage without intents",
> ```

I went looking for the corresponding `with intents` case. Don't we want to see what would happen regardless of that not being a thing? Or do we even send `IntentSpans` if some writes return before the EndTxn goes out?
___
*[pkg/storage/batcheval/cmd_end_transaction_test.go, line 764 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-LhZp8owADELy7DpMjVu:-LhZp8owADELy7DpMjVv:b-obwm84) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d0e270e890d4a0c1d1a7ba12ddd332bd9e6b615/pkg/storage/batcheval/cmd_end_transaction_test.go#L764)):*
> ```Go
> 			// parallel commit attempt. The re-stage will fail because of the
> 			// pushed timestamp.
> 			name: "record staging, try re-stage at pushed timestamp",
> ```

Nice testing.
___
*[pkg/storage/batcheval/cmd_end_transaction_test.go, line 828 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-LhZmwFM0kXxMBAK9n3q:-LhZmwFM0kXxMBAK9n3r:bqkbm5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d0e270e890d4a0c1d1a7ba12ddd332bd9e6b615/pkg/storage/batcheval/cmd_end_transaction_test.go#L828)):*
> ```Go
> 		},
> 		{
> 			// Standard case where a transaction record is created during a
> ```

Not that it matters, but is this a standard case?

**Comment by tbg** [comment]
(and apologies for taking so long)

**Review by nvb — COMMENTED** [review]
TFTR!

> Could you brush up the commit message to make the bug (and potential fallout) more obvious?

How's that?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-:-LhaMwn1CmATLT79yTb_:bmk32qa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/txn_interceptor_committer.go, line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-LhZdFpFDzEzwk6w5Qm5:-LhaJKWiCNvYojVUI57E:bqy08vv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d0e270e890d4a0c1d1a7ba12ddd332bd9e6b615/pkg/kv/txn_interceptor_committer.go#L231)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is this change material for the bug fixed in this PR? Not passing it would just disable that optimization, right? (I'm fine with a drive-by fix, just trying to understand where it's coming from).
</blockquote></details>

This is important to ensure that we don't get a retry error when making the txn commit explicit in the case where we previously hit this optimization when entering the implicit commit state. That is actually the reason why I added the incorrect line in `cmd_end_transaction.go` in the first place. 

The "unexpected retry error when making commit explicit" log would fire without this. I just made that line a fatal in race builds to ensure we catch any regressions.
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-LhZeAByDXYdfHzjKkKc:-LhaK6Wc1bKOeesNMV7N:b-tmuyzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5256fedbc4dd97e2c65989fe8173e777d17045f/pkg/storage/batcheval/cmd_end_transaction.go#L271)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Oops.
</blockquote></details>

:see_no_evil: 
___
*[pkg/storage/batcheval/cmd_end_transaction_test.go, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-LhZk_IB4ehRdXQ8Uq8M:-LhaKx9G5yhVPbx0xNpV:b-fw107k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d0e270e890d4a0c1d1a7ba12ddd332bd9e6b615/pkg/storage/batcheval/cmd_end_transaction_test.go#L193)):*
The `with intents` case is just `"record missing, can create, try stage"`. Does that answer your question or was there more to it?

> Or do we even send IntentSpans if some writes return before the EndTxn goes out?

Right, we'll only send `IntentSpans` during a txn stage if the writes have already returned before the EndTxn goes out.
___
*[pkg/storage/batcheval/cmd_end_transaction_test.go, line 828 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38117#-LhZmwFM0kXxMBAK9n3q:-LhaKdnLCJCBCjaC4iEp:bkb0aoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d0e270e890d4a0c1d1a7ba12ddd332bd9e6b615/pkg/storage/batcheval/cmd_end_transaction_test.go#L828)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Not that it matters, but is this a standard case?
</blockquote></details>

Done for a number of these.

**Comment by nvanbenschoten** [comment]
bors r=tbg

**Review by tbg — APPROVED** [review]
> Reviewed 4 of 4 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38117)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
