### PR TITLE
ui: add Networking metrics dashboard

### PR DESCRIPTION
**Pull request by tbg**
This has #99191 as a prerequisite.

This moves a few existing network-related metrics to their own dashboard. It
also adds metrics for healthy and unhealthy connections, which are now more
functional thanks to the work on the RPC package carried out in the previous
commits.

Epic: None
Release note (ui change): the DB Console metrics dashboard now has a
"Networking" tab, and a few metrics previously displayed on the Hardware tab
have moved there.

### CODE REVIEW

**Review by koorosh — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104394#-:-NXk-dyN-IKOrU6C0iwg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Comment by tbg** [comment]
bors r=koorosh
TFTR!

**Comment by tbg** [comment]
bors r=koorosh

**Comment by tbg** [comment]
bors single on
bors r=koorosh

**Pull request merged**
