### PR TITLE
sql: extend tenantStatusServer to return stmt/txn stats

### PR DESCRIPTION
**Pull request by Azhng**
Previously, tenantStatusServer does not have ability to report
statement/transaction statistics. This commit extends the SQLStatusServer
interface to enable tenantStatusServer to gain this ability.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
Nice! Did you run a local tenant instance and pull up the DB Console? Would be good to see these changes. cc @jordanlewis 

> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62625#-:-MWiprmY1nz8Fb5JObGN:b-i8ugno)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62625#-MWiphs80k-Jmv2QFqFc:-MWiphs80k-Jmv2QFqFd:bk1gl0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/618d13257247d433b6888d8893a342f926f70c7b/pkg/ccl/serverccl/tenant_status_test.go#L100)):*
> ```Go
> 	request := &serverpb.StatementsRequest{}
> 
> 	tenantStats, err := tenantStatusServer.Statements(ctx, request)
> ```

I think it might be worth it to check that we actually have expected `StatementsResponse`s. IIUC, we would currently pass this test if there are no responses returned.
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62625#-MWiox255EzxDhxeX0EC:-MWiox255EzxDhxeX0ED:bobryio) ([raw file](https://github.com/cockroachdb/cockroach/blob/618d13257247d433b6888d8893a342f926f70c7b/pkg/ccl/serverccl/tenant_status_test.go#L110)):*
> ```Go
> 	for _, tenantStmt := range tenantStats.Statements {
> 		for _, nonTenantStmt := range nonTenantStats.Statements {
> 			if reflect.DeepEqual(tenantStmt, nonTenantStmt) {
> ```

I think you can use `require.Equal` to collapse these two lines into one (there's a msg arg).
___
*[pkg/server/statements.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62625#-MWinzYf-rHGi2KHOCMn:-MWinzYf-rHGi2KHOCMo:bb1x9ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/618d13257247d433b6888d8893a342f926f70c7b/pkg/server/statements.go#L91)):*
> ```Go
> }
> 
> func statementLocal(
> ```

nit: `s/statementLocal/statementsLocal`

**Review by Azhng — COMMENTED** [review]
I don't think the tenant SQL pod has the ability to serve its own DB Console yet. Currently it's only capable of serving some [basic HTTP information](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/tenant.go#L114) like /debug and /health

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62625#-:-MWj50mh2MnjpKEdYgey:b-i8ivc7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62625#-MWiphs80k-Jmv2QFqFc:-MWjD0tW2TCDcJKcfWoB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/618d13257247d433b6888d8893a342f926f70c7b/pkg/ccl/serverccl/tenant_status_test.go#L100)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it might be worth it to check that we actually have expected `StatementsResponse`s. IIUC, we would currently pass this test if there are no responses returned.
</blockquote></details>

Done.
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62625#-MWiox255EzxDhxeX0EC:-MWjD02rAV9yP2NVR_EK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/618d13257247d433b6888d8893a342f926f70c7b/pkg/ccl/serverccl/tenant_status_test.go#L110)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think you can use `require.Equal` to collapse these two lines into one (there's a msg arg).
</blockquote></details>

Done.

**Comment by knz** [comment]
> I don't think the tenant SQL pod has the ability to serve its own DB Console yet

This is planned for the 21.2 cycle (with a likely backport). I'd say end of April.

**Review by asubiotto — APPROVED** [review]
:lgtm: minus nit

> Reviewed 1 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62625#-:-MWyOtKD6C8yDaDgfdQg:bkrnie2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62625#-MWyNqhF4hC4SqQDloWy:-MWyNqhF4hC4SqQDloWz:b-rwozrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dcfb862110f87d12d80b8260e0590d3200be49e/pkg/ccl/serverccl/tenant_status_test.go#L53)):*
> ```Go
> 	type testCase struct {
> 		stmt          string
> 		fingerprinted string
> ```

nit: `s/fingerprinted/fingerprint. Is there a function you can call to get the fingerprint for the statement rather than typing it out?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62625)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62625#-MWyNqhF4hC4SqQDloWy:-MWyapE80HEEiu6wZtrA:b-4p4ao7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dcfb862110f87d12d80b8260e0590d3200be49e/pkg/ccl/serverccl/tenant_status_test.go#L53)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/fingerprinted/fingerprint. Is there a function you can call to get the fingerprint for the statement rather than typing it out?
</blockquote></details>

I think all the existing tests just hardcode the statement fingerprints for the test cases. The function used to create statement fingerprint is `tree.AsStringWithFlags` which required a parsed AST, I think my preference here is to keep the fingerprint hardcoded.

**Comment by Azhng** [comment]
bors r=asubiotto

**Pull request merged**
