### PR TITLE
gossip: fix propagation of unchanging gossip entries

### PR DESCRIPTION
**Pull request by petermattis**
The gossip client and server code register callbacks that matches all
gossip keys in order to propagate those gossip entries to other
nodes. These callbacks need to fire even if the value is unchanging in
order to properly propagate updated expiration timestamps.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
This fixes the problem @jordanlewis was seeing with the gossip connectivity map changing. Definitely needs a test before merging.

**Comment by petermattis** [comment]
Test added which fails without the changes to `gossip/{client,server}.go` and succeeds with them.

**Comment by petermattis** [comment]
FYI, this was broken by https://github.com/cockroachdb/cockroach/pull/28963.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29603#-:-LLiG5fp85qQUvSSfQDj:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by petermattis** [comment]
bors r=tschottdorf

**Pull request merged**
