### PR TITLE
sql: remove some allocation-heavy closures

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously multiSourceInfo.findColumn used a closure to do some commonly
repeated work. Allocating this closure accounted for around 2.5% of the
total allocations recorded during a short run of TPCC. It's totally
pointless to keep it around, so extract it into its own function.

Also, typeCheckSameTypedExprs used a lot of closures to do its work. Create a
state object to pass around the arguments to avoid this problem, similar
to the strategy employed by typeCheckOverloadedExprs.

```
name         old time/op    new time/op    delta
TypeCheck-8    15.1µs ± 1%    14.2µs ± 1%   -5.59%  (p=0.000 n=10+10)

name         old alloc/op   new alloc/op   delta
TypeCheck-8    1.26kB ± 0%    0.68kB ± 0%  -45.86%  (p=0.000 n=10+10)

name         old allocs/op  new allocs/op  delta
TypeCheck-8      38.0 ± 0%      32.0 ± 0%  -15.79%  (p=0.000 n=10+10)
```

### CODE REVIEW

**Comment by knz** [comment]
:lgtm:

What's really sad to me is that a proper compiler should be able to extract closures into a static function automatically if they are known to not escape their scope... The algorithm to do so is known since the early 1990's.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19078#-:-Kvl0-C0Yf6Dg70Mi3sr:b6rb6gb)*

**Comment by jordanlewis** [comment]
Added a benchmark for completeness.

```
name         old time/op    new time/op    delta
TypeCheck-8    15.1µs ± 1%    14.2µs ± 1%   -5.59%  (p=0.000 n=10+10)

name         old alloc/op   new alloc/op   delta
TypeCheck-8    1.26kB ± 0%    0.68kB ± 0%  -45.86%  (p=0.000 n=10+10)

name         old allocs/op  new allocs/op  delta
TypeCheck-8      38.0 ± 0%      32.0 ± 0%  -15.79%  (p=0.000 n=10+10)
```

**Comment by knz** [comment]
Yay :tada: :100:

**Comment by jordanlewis** [comment]
TFTR!

**Pull request merged**
