### PR TITLE
kvserver: don't use marshaled proto for liveness CPut

### LINKED ISSUE #38308: stop using protos as the expected value in CPut
#38147 and #38004 each introduced a regression that broke RangeDescriptor updates (replica changes, splits, merges) after a cluster was upgraded from a prior version because of a bad interaction between CPut and protos.

Both bugs where the same general idea: A non-nullable field was added to RangeDescriptor (or ReplicaDescriptor, which is stored on RangeDescriptor). If a RangeDescriptor was written by an old version of cockroach, it wouldn't have the new field. Whenever we update RangeDescriptor, we do it with CPut to catch races. So a new binary would read the old serialized descriptor from kv (which doesn't have the new field), parse it into a RangeDescriptor, compute the update, then try to CPut the new RangeDescriptor. Proto2 includes all fields in the serialization, including ones with the default value, so it would include the new field. This wouldn't match what was in kv and the CPut would return a ConditionFailedError.

We could work around these two bugs by adding the fields as nullable, but that has an allocation cost. Worse though, the proto spec is pretty explicit about not relying on serialization of a given message to always produce exactly the same bytes. From https://developers.google.com/protocol-buffers/docs/encoding#implications

        Do not assume the byte output of a serialized message is stable.

Instead, what we should do is fetch the raw roachpb.Value from kv for the old RangeDescriptor, parse it into a RangeDescriptor and use that to compute the update, but also pass along the actual roachpb.Value we got. Then the CPut will use the roachpb.Value, which is guaranteed to match. If we need to do any equality of protos, we should be doing it using the Equal method on the parsed versions.

Further, there are more places where we CPut using a parsed proto message as the expected value, which are also footguns waiting to happen. We'll fix all of them and prevent future occurrences by changing the signature of CPut to accept a `*roachpb.Value` instead of `interface{}` for the expected value.

### PR DESCRIPTION
**Pull request by andreimatei**
Fixes #38308

Updates to the liveness records are done as CPuts. Before this patch,
the CPuts' expected value was the re-marshaled proto with the previous
version. As #38308 explains, that's a bad practice since it prevents the
proto's encoding to change in any way (e.g. fields can't be removed).
Instead, this patch moves to keeping track of the raw bytes that have
been read from the DB, besides the unmarshalled liveness protos. The raw
bytes are used as the expected values.

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/node_liveness.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7cynQ55oNyog0AIspu:-M7cynQ55oNyog0AIspv:b-kfix2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L182)):*
> ```Go
> // update to the liveness record: the raw value will act as the expected value.
> // This way the proto's encoding can change without the CPut failing.
> type LivenessRecordEx struct {
> ```

nit: just `LivenessRecord`? 
___
*[pkg/kv/kvserver/node_liveness.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7cz-Ek2jxVBEhPM8px:-M7cz-Ek2jxVBEhPM8py:bz6fnan) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L324)):*
> ```Go
> 			return false, errors.Wrap(err, "invalid liveness record")
> 		}
> 		//if (oldLiveness == storagepb.Liveness{}) {
> ```

Remove or uncomment this? (remove, I think)
___
*[pkg/kv/kvserver/node_liveness.go, line 777 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7czeaFB3GU6DhwZP9L:-M7czeaFB3GU6DhwZP9M:bexjla6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L777)):*
> ```Go
> // the database has for this liveness record in addition to the decoded liveness
> // proto.
> func (nl *NodeLiveness) GetLivenessEx(nodeID roachpb.NodeID) (LivenessRecordEx, error) {
> ```

Do we really need two different versions of these methods? I'd rather just use the version that includes the raw value everywhere. 
___
*[pkg/kv/kvserver/node_liveness.go, line 950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7d-srQ0_NfgCT8RizM:-M7d-srQ0_NfgCT8RizN:b-1clv46) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L950)):*
> ```Go
> 			log.Fatalf(ctx, "failed to marshall proto: %s", err)
> 		}
> 		// Make a copy of the expected value. We can't pass oldRaw because b.CPut()
> ```

Really? Eww.

**Review by tbg — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @nvanbenschoten)

___
*[pkg/kv/kvserver/node_liveness.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7g0Kg012GxW9YieoM6:-M7g0Kg012GxW9YieoM7:b-6bog9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L408)):*
> ```Go
> // liveness record. It has both the new and the old version of the proto.
> type livenessUpdate struct {
> 	new storagepb.Liveness
> ```

how about "updated"? Using keywords (`new`) tickles my OCD. It also tends to throw off syntax highlighters, as it does in reviewable.
___
*[pkg/kv/kvserver/node_liveness.go, line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7g0h08ClzsJX0SX_v_:-M7g0h08ClzsJX0SX_va:ba66wf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L419)):*
> ```Go
> 	// if they don't correspond, the CPut is considered to have failed.
> 	//
> 	// When ignoreCache is set, oldLRaw needs to be set as well.
> ```

`oldRaw`
___
*[pkg/kv/kvserver/node_liveness.go, line 777 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7czeaFB3GU6DhwZP9L:-M7g0rKP0fTJ_3TZUQWt:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L777)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Do we really need two different versions of these methods? I'd rather just use the version that includes the raw value everywhere. 
</blockquote></details>

+1
___
*[pkg/kv/kvserver/node_liveness.go, line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7g15xm2dsRatQIWceY:-M7g15xm2dsRatQIWceZ:bagxbry) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L814)):*
> ```Go
> // another successful heartbeat, and a second increment to come in
> // after that)
> func (nl *NodeLiveness) IncrementEpoch(ctx context.Context, liveness storagepb.Liveness) error {
> ```

shouldn't this one be the augmented one with the raw bytes?
___
*[pkg/kv/kvserver/node_liveness.go, line 950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7d-srQ0_NfgCT8RizM:-M7g1fIE5EbqF9_l_1rW:b-4fkv60) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L950)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Really? Eww.
</blockquote></details>

Is it this?

https://github.com/cockroachdb/cockroach/blob/f80ec9c292d43676d739fffabc847fb8b3195396/pkg/kv/batch.go#L456

That seems like bad code we would want to go away. I wonder why we need to clear the checksum - doesn't the checksum match `expVal`?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/node_liveness.go, line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7g15xm2dsRatQIWceY:-M7hF12R5pudddpZpA-L:bib67he) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L814)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

shouldn't this one be the augmented one with the raw bytes?
</blockquote></details>

That's what I wanted initially, but the thing is that this is called from the lease handling code, which has a `storagepb.LeaseStatus`. That guy is a proto (for no good reason) and currently doesn't include the raw bytes. I've considered changing that, but... I dunno. There's a bunch of stuff to change, and it's not really necessary given that this code doesn't set `ignoreCache` - so we check the cache anyway, which has the raw bytes.
Thoughts?

**Review by irfansharif — COMMENTED** [review]
(Unsolicited) LGTM. Was looking around changing the liveness proto for random reasons and stumbled by this.

> Reviewed 3 of 10 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-:-M7igIVi6HqTR2x6OYrI:bnhb8g2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @nvanbenschoten, and @tbg)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/node_liveness.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7cynQ55oNyog0AIspu:-M7h_Ei95hGX5cVsoX7Q:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L182)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

nit: just `LivenessRecord`? 
</blockquote></details>

done
___
*[pkg/kv/kvserver/node_liveness.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7cz-Ek2jxVBEhPM8px:-M7h_IB0EHeNg0r2ei7U:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L324)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove or uncomment this? (remove, I think)
</blockquote></details>

done
___
*[pkg/kv/kvserver/node_liveness.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7g0Kg012GxW9YieoM6:-M7h_RlO8O6kB2dGx9bt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L408)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

how about "updated"? Using keywords (`new`) tickles my OCD. It also tends to throw off syntax highlighters, as it does in reviewable.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/node_liveness.go, line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7g0h08ClzsJX0SX_v_:-M7h_SMnDZrjjMG0PmDm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L419)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

`oldRaw`
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/node_liveness.go, line 777 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7czeaFB3GU6DhwZP9L:-M7iC13x6oPO18yPJymf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L777)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/node_liveness.go, line 950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7d-srQ0_NfgCT8RizM:-M7j99cT7QaZBksTgOoc:b-rfx5rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L950)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is it this?

https://github.com/cockroachdb/cockroach/blob/f80ec9c292d43676d739fffabc847fb8b3195396/pkg/kv/batch.go#L456

That seems like bad code we would want to go away. I wonder why we need to clear the checksum - doesn't the checksum match `expVal`?
</blockquote></details>

Yeah, this has bothered me greatly too. I spent some time digging.
So `Batch.CPut()` takes an expected `Value`. The value has a checksum, which includes the key corresponding to the respective key-value pair. So, if you read `val` from `k1` and then try to used it as the expected value for key `k2`, the checksum needs to change.
At the moment, as we've seen, the `CPut` code wipes the checksum that was given to it and recomputes it. I've tried to change it to deal with already-populated checksums by asserting that they're correct for the key currently being written - so then the contract would be that if you pass a value with a filled-in checksum to cput as the expected val, then it must have been read from the key you're currently trying to write. The caller would have the option to clear the checksum, in which case the CPut code will compute a good one.

This hit a problem because the liveness record values we're using for these CPuts often come from gossip, and gossip, alas, uses different damn keys when it broadcasts the liveness records (different from the keys where the records are in the db). So, in order to keep these gossiped liveness records immutable, we'd have to recompute their checksums when a node receives them. Which is doable, but pretty gross too.

So I'm taking opinions about what the right thing to do here is. Is a `*roachpb.Value` even the right type for the expected val in the `CPut` interface, or should it be simply `[]byte` (with no checksum)? The `*roachpb.Value` has the advantage that it has a nice interface for encoding any type into it. 

@petermattis I'm also curious if you have any insight into why gossip uses its own keys, different from the database keys (i.e. stuff in `gossip/keys.go`).

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/node_liveness.go, line 950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7d-srQ0_NfgCT8RizM:-M7jPLtQ9UIPOk8_-4a3:b-6d0kgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L950)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Yeah, this has bothered me greatly too. I spent some time digging.
So `Batch.CPut()` takes an expected `Value`. The value has a checksum, which includes the key corresponding to the respective key-value pair. So, if you read `val` from `k1` and then try to used it as the expected value for key `k2`, the checksum needs to change.
At the moment, as we've seen, the `CPut` code wipes the checksum that was given to it and recomputes it. I've tried to change it to deal with already-populated checksums by asserting that they're correct for the key currently being written - so then the contract would be that if you pass a value with a filled-in checksum to cput as the expected val, then it must have been read from the key you're currently trying to write. The caller would have the option to clear the checksum, in which case the CPut code will compute a good one.

This hit a problem because the liveness record values we're using for these CPuts often come from gossip, and gossip, alas, uses different damn keys when it broadcasts the liveness records (different from the keys where the records are in the db). So, in order to keep these gossiped liveness records immutable, we'd have to recompute their checksums when a node receives them. Which is doable, but pretty gross too.

So I'm taking opinions about what the right thing to do here is. Is a `*roachpb.Value` even the right type for the expected val in the `CPut` interface, or should it be simply `[]byte` (with no checksum)? The `*roachpb.Value` has the advantage that it has a nice interface for encoding any type into it. 

@petermattis I'm also curious if you have any insight into why gossip uses its own keys, different from the database keys (i.e. stuff in `gossip/keys.go`).
</blockquote></details>

There's also the option of having the `CPut` code clear the checksum without a fuss if it's not correct for the key.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/node_liveness.go, line 950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7d-srQ0_NfgCT8RizM:-M7nn0PF4lc3IBIe6hEH:b-94q803) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L950)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

There's also the option of having the `CPut` code clear the checksum without a fuss if it's not correct for the key.
</blockquote></details>

I've discussed this offline with @bdarnell; I'm going to change the CPut interface to simply take a read-only `[]byte` for the expected val, so that we don't need to worry about checksums any more.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @irfansharif, @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/node_liveness.go, line 871 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M8lWj-Q1K6_MLgGCtow:-M8lWj-Q1K6_MLgGCtox:bx6fjjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/80686e82825bd940040274f039f0861056810f27/pkg/kv/kvserver/node_liveness.go#L871)):*
> ```Go
> // cache.
> func (nl *NodeLiveness) updateLiveness(
> 	ctx context.Context, update livenessUpdate, handleCondFailed func(actual LivenessRecord) error,
> ```

Does this `handleCondFailed` callback need a `LivenessRecord` type, or could it to with a vanilla `storagepb.Liveness`? I don't think the callers use the raw bytes.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @irfansharif, @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/node_liveness.go, line 950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M7d-srQ0_NfgCT8RizM:-MA8iKo68qOKtTzD7T24:b-p8biee) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0f02aed0fa2b59ac1c9e8385d5812b1d177ccf/pkg/kv/kvserver/node_liveness.go#L950)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I've discussed this offline with @bdarnell; I'm going to change the CPut interface to simply take a read-only `[]byte` for the expected val, so that we don't need to worry about checksums any more.
</blockquote></details>

The change changing the CPut API is https://github.com/cockroachdb/cockroach/pull/50408. Let's agree on that one and come back.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @irfansharif, @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/node_liveness.go, line 871 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-M8lWj-Q1K6_MLgGCtow:-MAlputs9kKg9BoTdogX:b-zho36a) ([raw file](https://github.com/cockroachdb/cockroach/blob/80686e82825bd940040274f039f0861056810f27/pkg/kv/kvserver/node_liveness.go#L871)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Does this `handleCondFailed` callback need a `LivenessRecord` type, or could it to with a vanilla `storagepb.Liveness`? I don't think the callers use the raw bytes.
</blockquote></details>

they do; the callback calls `maybeUpdate()` (not new).
I've tried to make the callbacks not call `maybeUpdate()`, and instead return the `actual` from `updateLiveness()` (since that caller needs to sometimes call `maybeUpdate()` anyway), but it gets a bit gnarly because the callback can return errors too, and then it becomes unclear when the caller of `updateLiveness` should call `maybeUpdate` and when it shouldn't. So I've left `updateLiveness()` return an empty `LivenessRecord` when `handleCondFailed()` is called.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49135#-:-MB-UsAV34vB9PgHh4vF:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @irfansharif, @nvanbenschoten, @petermattis, and @tbg)

**Pull request merged**
