### PR TITLE
kv: don't let pusher win when pushing STAGING txn with equal priority

### LINKED ISSUE #101721: kv/kvnemesis: TestKVNemesisMultiNode failed
kv/kvnemesis.TestKVNemesisMultiNode [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9661034?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9661034?buildTab=artifacts#/) on master @ [1cd507a7c6582fd91bb56123e62bd4fde45c4d22](https://github.com/cockroachdb/cockroach/commits/1cd507a7c6582fd91bb56123e62bd4fde45c4d22):

```
=== RUN   TestKVNemesisMultiNode
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisMultiNode1865204116
    test_log_scope.go:79: use -show-logs to present logs inline
    kvnemesis_test.go:180: seed: 7605291541804074861
    kvnemesis_test.go:124: kvnemesis logging to /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2082477957
    kvnemesis.go:165: range 65 (/Table/100/"00532edf314db371") RANGE_CONSISTENT_STATS_INCORRECT:
        stats: {ContainsEstimates:0 LastUpdateNanos:1681814839621095004 IntentAge:0 GCBytesAge:13445 LiveBytes:212 LiveCount:4 KeyBytes:435 KeyCount:11 ValBytes:290 ValCount:17 IntentBytes:0 IntentCount:0 SeparatedIntentCount:0 RangeKeyCount:1 RangeKeyBytes:51 RangeValCount:1 RangeValBytes:10 SysBytes:10401 SysCount:20 AbortSpanBytes:1199}
        delta (stats-computed): {ContainsEstimates:0 LastUpdateNanos:1681814839621095004 IntentAge:0 GCBytesAge:0 LiveBytes:0 LiveCount:0 KeyBytes:0 KeyCount:0 ValBytes:0 ValCount:0 IntentBytes:0 IntentCount:0 SeparatedIntentCount:0 RangeKeyCount:0 RangeKeyBytes:0 RangeValCount:0 RangeValBytes:0 SysBytes:-6 SysCount:0 AbortSpanBytes:0}
    kvnemesis.go:165: range 78 (/Table/100/"0d1b2742d6b6062f") RANGE_CONSISTENT_STATS_INCORRECT:
        stats: {ContainsEstimates:0 LastUpdateNanos:1681814839812403396 IntentAge:0 GCBytesAge:41393 LiveBytes:53 LiveCount:1 KeyBytes:750 KeyCount:14 ValBytes:583 ValCount:38 IntentBytes:0 IntentCount:0 SeparatedIntentCount:0 RangeKeyCount:1 RangeKeyBytes:51 RangeValCount:1 RangeValBytes:10 SysBytes:2488 SysCount:21 AbortSpanBytes:1199}
        delta (stats-computed): {ContainsEstimates:0 LastUpdateNanos:1681814839812403396 IntentAge:0 GCBytesAge:0 LiveBytes:0 LiveCount:0 KeyBytes:0 KeyCount:0 ValBytes:0 ValCount:0 IntentBytes:0 IntentCount:0 SeparatedIntentCount:0 RangeKeyCount:0 RangeKeyBytes:0 RangeValCount:0 RangeValBytes:0 SysBytes:6 SysCount:0 AbortSpanBytes:0}
    kvnemesis.go:185: failures(verbose): /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2082477957/failures
        repro steps: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2082477957/repro.go
        rangefeed KVs: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2082477957/kvs-rangefeed.txt
        scan KVs: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2082477957/kvs-scan.txt
    kvnemesis_test.go:207: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:207
        	            				github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:160
        	Error:      	Should be zero, but was 2
        	Test:       	TestKVNemesisMultiNode
        	Messages:   	kvnemesis detected failures
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisMultiNode1865204116
--- FAIL: TestKVNemesisMultiNode (70.36s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #101048 kv/kvnemesis: TestKVNemesisMultiNode failed [C-test-failure O-robot T-kv branch-release-22.2]
- #100417 kv/kvnemesis: TestKVNemesisMultiNode failed [C-test-failure O-robot T-kv branch-release-23.1]
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestKVNemesisMultiNode.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27104

Epic CRDB-27234

### LINKED ISSUE #105330: kvserver: unhandled TransactionPushError when push finds STAGING but known-uncommitted Read Committed transaction
**Describe the problem**

In https://github.com/cockroachdb/cockroach/pull/97779 we're introducing reproposals and reproposal errors in kvnemesis.

For some reason, under stress, kvnemesis will now sometimes find a `*TransactionPushError` bubble up from `db.Get` and `db.Scan` (and likely other methods), which should not be possible.

@arulajmani is looking at this in https://cockroachlabs.slack.com/archives/G01G8LK77DK/p1687356168950489.

Jira issue: CRDB-28983

### PR DESCRIPTION
**Pull request by nvb**
Fixes #105330.
Fixes #101721.

This commit updates the transaction push logic to stop pushes from completing successfully when the pushee is STAGING and the pusher has equal priority. Prior to this change, the pusher would win in these cases when using a PUSH_TIMESTAMP if at least one of the two transactions involved used a weak isolation level.

This had two undesirable effects:
- if the pushee was still possibly committable and requiring recovery (`!(knownHigherTimestamp || knownHigherEpoch)` in the code) then the pusher would immediately begin parallel commit recovery, attempting to disrupt the commit and abort the pushee. This is undesirable because the pushee may still be in progress and in cases of equal priority, we'd like to wait for the parallel commit to complete before kicking off recovery, deferring recovery to only the cases where the pushee/committers's heartbeat has expired.
- if the pushee was known to be uncommittable (`knownHigherTimestamp || knownHigherEpoch` in the code), then txn recovery was not kicked off but the pusher still could not perform the PUSH_TIMESTAMP (see e40c1b4e), so it would return a `TransactionPushError`. This confused logic in `handleTransactionPushError`, allowing the error to escape to the client.

This commit resolves both issues by considering the pushee's transaction status in `txnwait.ShouldPushImmediately`.

Release note: None

### CODE REVIEW

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107882)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table_waiter.go` line 1304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-Nah3RS_3y2dLnz47sRT:-Nah3RS_3y2dLnz47sRU:bree255) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d4907902a52759d1c17cb37d49fa63168ac6f8a/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L1304)):*
> ```Go
> 	// to push. A push may determine that the pushee is STAGING or has already
> 	// been finalized.
> 	pusheeStatus := roachpb.PENDING
> ```

Is it worth querying the actual pushee status here? If it's already finalized or staging, it can save us a push request?
___
*[`pkg/kv/kvserver/txnwait/queue_test.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-Nah4hACCkyEucl_2dyz:-Nah4hACCkyEucl_2dz-:b-ocy7xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d4907902a52759d1c17cb37d49fa63168ac6f8a/pkg/kv/kvserver/txnwait/queue_test.go#L227)):*
> ```Go
> func testCanPushWithPriorityPushTimestamp(t *testing.T) {
> 	t.Run("pusheeStatus="+roachpb.PENDING.String(), testCanPushWithPriorityPushTimestampPusheePending)
> 	t.Run("pusheeStatus="+roachpb.STAGING.String(), testCanPushWithPriorityPushTimestampPusheeStaging)
> ```

These capture a lot of the cases from your spreadsheet. I think only the abort push type is missing, but maybe that's already done elsewhere? I think it would be great to have one massive test for all cases.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107882)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`pkg/kv/kvserver/concurrency/lock_table_waiter.go` line 1304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-Nah3RS_3y2dLnz47sRT:-NahD4JA81bp8yxgPVO1:bbsf6ko) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d4907902a52759d1c17cb37d49fa63168ac6f8a/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L1304)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Is it worth querying the actual pushee status here? If it's already finalized or staging, it can save us a push request?
</blockquote></details>

A push request and a query request will cost the same, so I don't think there's much to be gained from querying for the status in order to avoid a push.
___
*[`pkg/kv/kvserver/txnwait/queue_test.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-Nah4hACCkyEucl_2dyz:-NahDAm_84SzXJBilBm7:bdp62p2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d4907902a52759d1c17cb37d49fa63168ac6f8a/pkg/kv/kvserver/txnwait/queue_test.go#L227)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

These capture a lot of the cases from your spreadsheet. I think only the abort push type is missing, but maybe that's already done elsewhere? I think it would be great to have one massive test for all cases.
</blockquote></details>

The abort push type is captured in `testCanPushWithPriorityPushAbort`, which is another subtest of `TestCanPushWithPriority`.

**Comment by nvanbenschoten** [comment]
@miraradeva I've improved the testing in this PR by adding an integration test that reproduces #105330 and then demonstrating that the fix here corrects the behavior in the test. This should now be good for a look.

**Review by miraradeva — COMMENTED** [review]
> Reviewed 1 of 8 files at r2, 7 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107882)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`-- commits` line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-Nava9oYCwWafMdD5YYO):*
too -> to
___
*[`pkg/kv/kvserver/batcheval/cmd_push_txn.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-NavbrpK7wqhbHyZTQgS:-NavbrpK7wqhbHyZTQgT:b-ugh45t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5107cff82ac54c1e9c244a1f5d3bdd2ff2e64e43/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L296)):*
> ```Go
> 	// transaction recovery procedure always finalizes target transactions, even
> 	// if initiated by a PUSH_TIMESTAMP.
> 	if pusheeStaging /* => pusheeStagingFailed */ && pushType == kvpb.PUSH_TIMESTAMP {
> ```

How does `pusheeStaging => pusheeStagingFailed`? Isn't it the opposite: `pusheeStagingFailed => pusheeStaging`? So maybe here we want `if  pusheeStagingFailed && ...`? It matches the comment and the previous code. Also, it would be nice if this logic can be closer to the other STAGING logic 10-ish lines above.

Is this logic tested anywhere?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107882)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`-- commits` line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-Nava9oYCwWafMdD5YYO):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

too -> to
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/batcheval/cmd_push_txn.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-NavbrpK7wqhbHyZTQgS:-Naw8wukA3oWFDzq7EMP:b-6sbx0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5107cff82ac54c1e9c244a1f5d3bdd2ff2e64e43/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L296)):*
> How does `pusheeStaging => pusheeStagingFailed`?

`pusheeStaging` implies `pusheeStagingFailed` because `pusheeStaging && !pusheeStagingFailed` would have hit one of the two previous branches. Either `pusherWins`, is which case we would have returned an `IndeterminateCommitError`, or `!pusherWins`, in which case we would have returned a `TransactionPushError`.

I wrote it like this because I want it to be clear to readers that if a push does succeed on a STAGING txn, it will have a pushType of `PUSH_ABORT`.

> Is this logic tested anywhere?

It is tested by `TestTxnRecordLifecycleTransitions` and `TestTxnRecoveryFromStagingWithHighPriority`.

**Review by miraradeva — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107882)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/batcheval/cmd_push_txn.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-NavbrpK7wqhbHyZTQgS:-NawP8Z67F4rLBJqqPzU:b-nbbyi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5107cff82ac54c1e9c244a1f5d3bdd2ff2e64e43/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L296)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> How does `pusheeStaging => pusheeStagingFailed`?

`pusheeStaging` implies `pusheeStagingFailed` because `pusheeStaging && !pusheeStagingFailed` would have hit one of the two previous branches. Either `pusherWins`, is which case we would have returned an `IndeterminateCommitError`, or `!pusherWins`, in which case we would have returned a `TransactionPushError`.

I wrote it like this because I want it to be clear to readers that if a push does succeed on a STAGING txn, it will have a pushType of `PUSH_ABORT`.

> Is this logic tested anywhere?

It is tested by `TestTxnRecordLifecycleTransitions` and `TestTxnRecoveryFromStagingWithHighPriority`.
</blockquote></details>

Ok, I see. It's not super easy to understand with all the cases , in particular if someone wants to add an extra condition to one of these cases (like when I played around with wait policies). This is also not great but a bit more explicit:



_Code snippet:_
```Go
if pusheeStaging && !pusheeStagingFailed && (pusherWins || recoverOnFailedPush) {
	// 	kvpb.NewIndeterminateCommitError
}
if pusheeStagingFailed && pusherWins && pushType == kvpb.PUSH_TIMESTAMP {
	pushType = kvpb.PUSH_ABORT
}
if !pusherWins {
	// kvpb.NewTransactionPushError
}
```

**Review by miraradeva — APPROVED** [review]
Just one potential alternative but otherwise :lgtm:

> Reviewed 1 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-:-NawSiy0Ea3_iCtrROc4:b-3w9eyz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
TFTR!

bors r=miraradeva

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-:-NawdF95EeyxEzO__EeT:b4520s7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvserver/batcheval/cmd_push_txn.go` line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107882#-NavbrpK7wqhbHyZTQgS:-NawczLLB49EeDKW7o6N:b-yasyoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5107cff82ac54c1e9c244a1f5d3bdd2ff2e64e43/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L296)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Ok, I see. It's not super easy to understand with all the cases , in particular if someone wants to add an extra condition to one of these cases (like when I played around with wait policies). This is also not great but a bit more explicit:
</blockquote></details>

Good idea! I adopted the structure and made one small change to your suggestion using Erik's new `must` assertion library.

**Pull request merged**
