### PR TITLE
build: remove outdated CIRCLECI workaround

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10002)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

**Comment by petermattis** [comment]
FYI, the same hack exists in `pkg/acceptance/cluster/docker.go`.

**Comment by tschottdorf** [comment]
Added.

**Review by petermattis — APPROVED** [review]
LGTM

**Pull request merged**
