### PR TITLE
opt: don't use inverted histograms in applyFilter

### LINKED ISSUE #50596: roachtest: sqlsmith/setup=seed/setting=no-mutations failed
[(roachtest).sqlsmith/setup=seed/setting=no-mutations failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2034317&tab=buildLog) on [master@e85ac5f2d70542523a61f430f1fc354023b6c7e4](https://github.com/cockroachdb/cockroach/commits/e85ac5f2d70542523a61f430f1fc354023b6c7e4):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=seed/setting=no-mutations/run_1
	sqlsmith.go:169,sqlsmith.go:199,test_runner.go:753: error: pq: internal error: unsupported comparison: bytes to jsonb
		stmt:
		SELECT
			(-1.9208989143371582):::FLOAT8 AS col_15025, tab_6146._jsonb AS col_15026
		FROM
			defaultdb.public.seed@seed__int8__float8__date_idx AS tab_6146
		WHERE
			(('1':::JSONB IS NOT DISTINCT FROM tab_6146._jsonb) AND true)
		LIMIT
			78:::INT8;

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=seed/setting=no-mutations](https://teamcity.cockroachdb.com/viewLog.html?buildId=2034317&tab=artifacts#/sqlsmith/setup=seed/setting=no-mutations)
Related:
- #49251 roachtest: sqlsmith/setup=seed/setting=no-mutations failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-20.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Dseed%2Fsetting%3Dno-mutations.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #50596

Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
Is this the best way to fix this currently? It's unclear to me the correct function call that should be doing this.

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50670)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50670#-MAhZyIV3l3kS-N9YN_i:-MAhZyIV3l3kS-N9YN_j:b-7un03v) ([raw file](https://github.com/cockroachdb/cockroach/blob/28cea471f5eca9f793c9ceac49f43f4d029fbcc3/pkg/sql/opt/memo/statistics_builder.go#L2734)):*
> ```Go
> 		constrainedCols.UnionWith(scalarProps.OuterCols)
> 		// Don't attempt to fetch histograms for inverted index types.
> 		if scalarProps.Constraints != nil && sqlbase.ColumnTypeIsInvertedIndexable(conjunct.Condition.DataType()) {
> ```

I feel like this would fit better in the `shouldUseHistogram` function. Then at least you can still get the distinct count of the json column.

Would that work?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50670)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50670#-MAhZyIV3l3kS-N9YN_i:-MB01xqg7L6N-9BoSed8:b-buzjeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/28cea471f5eca9f793c9ceac49f43f4d029fbcc3/pkg/sql/opt/memo/statistics_builder.go#L2734)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I feel like this would fit better in the `shouldUseHistogram` function. Then at least you can still get the distinct count of the json column.

Would that work?
</blockquote></details>

I didn't want to because it required adding a parameter to it, but yeah I think this is better?

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50670#-:-MB0d6ll5Hy1WGJGMVxQ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50670#-MAhZyIV3l3kS-N9YN_i:-MB0c_W72UuOgcN5AQHz:bh9kcxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/28cea471f5eca9f793c9ceac49f43f4d029fbcc3/pkg/sql/opt/memo/statistics_builder.go#L2734)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I didn't want to because it required adding a parameter to it, but yeah I think this is better?
</blockquote></details>

Yea, seems cleaner this way - thanks!

**Pull request merged**
