### PR TITLE
colexec: add "recursive" merging to external sort

### LINKED ISSUE #45043: colexec: fix memory accounting in external sorter
While working on #44901 I noticed that there is a problem with the way we reuse in-memory sorter in the external sorter with resetting of the memory account. We cannot just "clear" the memory monitor, and we need to have a more fine-grained approach.

```
	// TODO(yuzefovich): usage of a.acc.Clear method is not compatible with our
	// PerformOperation. Consider the following scenario:
	// 1. we allocate []int64 Vec with 1024 capacity, this memory is registered
	// with the allocator (8192 bytes).
	// 2. then we Clear() the allocator, now the memory account says that we use
	// 0 bytes, but the actual memory is not released.
	// 3. we reuse the Vec and append into it 1024 int64 values. Because there
	// was enough capacity to accommodate it, no new memory is allocated.
	// 4. when we called PerformOperation to account for that memory, we computed
	// "before" and "after" memory estimates, and in both cases they equal 8192
	// bytes, so "delta" is 0, and the allocator continues to think that 0 bytes
	// have been registered with it, but it is not the case.
	// I think "adding disk queue to hash router" PR has more fine-grained
	// methods for working with memory. Consider reusing them here.
```

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: add "recursive" merging to external sort**

Previously, external sorter was merging all partitions at once (i.e.
there was a single merger). This is problematic because each partition
uses some amount of RAM for its buffer, we want to make sure that all
partitions together do not exceed the memory limit.

Now this is addressed by splitting previous "merging" stage into three:
1. new "repeated merging" stage is now responsible for merging all
current partitions and spilling new partitions to disk until only one is
left. This might be performed while we're still consuming the input.
2. new "final merging" stage that sets up an emitter that can merge all
the remaining partitions. This occurs only when the input has been fully
consumed and we can merge all the partitions at once, without having to
spill to disk.
3. new " emitting" stage that simply emits the output.

Addresses: #44727.

Release note: None

**colexec: fix external sorter memory accounting**

Previously, there was a problem with inputPartitioningOperator (which
divides up the input into "partitions" once the partition exceeds the
provided memory limit) because usage of Allocator.Clear is not
compatible with Allocator.PerformOperation. Now this problem is fixed by
explicitly tracking the memory used by the input batches with
RetainBatch against a "standalone" allocator. We're using standalone
budget for that to avoid double counting for the memory of the batch
(they are accounted already with unlimitedAllocator of the sorter).

Fixes: #45043.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/external_sort.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-kT5Iz3rqRYxNc-vmb:-M-kT5Iz3rqRYxNc-vmc:b-5cexxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f4aea2f65307ff4ccf35124a907c336789d636f/pkg/sql/colexec/external_sort.go#L28)):*
> ```Go
> // TODO(asubiotto): figuring out this value should be a part of implementing
> // Partitioner.
> const maxNumberActivePartitions = 64
> ```

This shouldn't be a constant and should be determined semi dynamically instead using the buffer size of a `DiskQueueCfg`. It might make sense to wait for #44776 to merge. Even though a single batch is read from a partition, that partition will be using the preconfigured amount of memory to buffer reads so as a caller you can merge the number of partitions once that constant multiplied by the number of partitions created exceeds some memory limit.

**Comment by asubiotto** [comment]
#44776 has merged, so I think this PR should be updated.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_sort.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-kT5Iz3rqRYxNc-vmb:-M-v1td44iqlzV9f1lS1:bevftus) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f4aea2f65307ff4ccf35124a907c336789d636f/pkg/sql/colexec/external_sort.go#L28)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This shouldn't be a constant and should be determined semi dynamically instead using the buffer size of a `DiskQueueCfg`. It might make sense to wait for #44776 to merge. Even though a single batch is read from a partition, that partition will be using the preconfigured amount of memory to buffer reads so as a caller you can merge the number of partitions once that constant multiplied by the number of partitions created exceeds some memory limit.
</blockquote></details>

Done, PTAL.

**Review by asubiotto — CHANGES_REQUESTED** [review]
I like the direction this is going but I think we need to change the state transitions. Currently it seems like we spill as many partitions as possible before reducing the number of these partitions until we get them under the maximum. The problem with this is that these `n` partitions will each use `BufferSizeBytes`, which could be pretty high. I think we need to change the transitions to spill the maximum number of partitions, and if we see that there is still more input, transition to reducing those partitions into 1 and repeat these steps until the input is done. This way we have a true upper bound on the memory use.

> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-:-M-vNHfMD0B8jQunagDl:bf7halc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/allocator.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vNETy-98-khL-R1QW:-M-vNETy-98-khL-R1QX:bxk0yg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/allocator.go#L158)):*
> ```Go
> // Clear clears up the memory account of the allocator.
> func (a *Allocator) Clear() {
> 	// TODO(yuzefovich): usage of a.acc.Clear method is not compatible with our
> ```

Could you create an issue for this to track?
___
*[pkg/sql/colexec/external_sort.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vFv-527HwYOIXsI7h:-M-vFv-527HwYOIXsI7i:b-71y9hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort.go#L117)):*
> ```Go
> // uses some amount of RAM for its buffer. This is determined by
> // numberActivePartitions variable.
> // 2. We want to make sure that the merger stays within the provided memory
> ```

Isn't the merger going to use a small but virtually constant amount of memory? I think we should be calling `ReleaseBatch` when enqueuing to a partition (when we actually use disk) and not worrying about any memory growth since the memory used will be accounted for by the ordered synchronizer (for the output) as well as the pre-reserved memory for the partitions (for the input to the unordered synchronizer).
___
*[pkg/sql/colexec/external_sort.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vK_F724Y-UGsR42oN:-M-vK_F82iZhQMRnw4FH:b5p71um) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort.go#L122)):*
> ```Go
> // that manually. We do so by estimating the amount of memory used by the
> // merger (which will be reading a batch from all of its input simultaneously)
> // with some margin of error (0.8 at the moment). For every partition we count
> ```

This I'm not sure I understand. In the merge step, the actual memory used will always be constant == the number of partitions. This means that we have to transition to merging all the accumulated partitions once this number reaches `maxNumberActivePartitions`. Once we do that, we can proceed with `externalSorterNewPartition` and do this until the input is exhausted. Only then can we move to the merge step.
___
*[pkg/sql/colexec/external_sort.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vEivGEau5jNR4T5gl:-M-vEivGEau5jNR4T5gm:by1t8yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort.go#L194)):*
> ```Go
> 		// it a portion of the available memory and the rest will be used by the
> 		// mergers.
> 		numberActivePartitions = int(float64(memoryLimit)*externalSorterActivePartitionsMemFraction) / cfg.BufferSizeBytes
> ```

Should we make sure that this number does not fall below some number, for example 2? What would currently happen if we can only create one partition?
___
*[pkg/sql/colexec/external_sort_test.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vMdlj3w7M9nsMnD4q:-M-vMdlj3w7M9nsMnD4r:bo40dg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort_test.go#L66)):*
> ```Go
> 						sorter, accounts, monitors, err := createDiskBackedSorter(
> 							ctx, flowCtx, input, tc.logTypes, tc.ordCols, func() {},
> 							2, /* numberActivePartitions */
> ```

nit: maybe extract this into a const and `s/numberActivePartitions/maxNumberActivePartitions`

**Review by yuzefovich — COMMENTED** [review]
I see, I didn't think about this. Changed. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-:-M0SosAS1mBw4tSpwGY2:bo2e858)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/allocator.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vNETy-98-khL-R1QW:-M-vomuO5nWILoKQKaEZ:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/allocator.go#L158)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you create an issue for this to track?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_sort.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vFv-527HwYOIXsI7h:-M0Smgk1CTy4CztTM-Sf:b-xs8ymu) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort.go#L117)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Isn't the merger going to use a small but virtually constant amount of memory? I think we should be calling `ReleaseBatch` when enqueuing to a partition (when we actually use disk) and not worrying about any memory growth since the memory used will be accounted for by the ordered synchronizer (for the output) as well as the pre-reserved memory for the partitions (for the input to the unordered synchronizer).
</blockquote></details>

Hm, I might be confused here, but here is my understanding:
- ordered synchronizer will read a batch from its every input
- the inputs to ordered synchronizer are `partitionerToOperator`s for every partition that we're merging
- those adapters hold onto a single batch of memory
- so the memory usage of the whole "merging" infrastructure is a batch from from every partition plus a batch for the output.

I agree that the merger itself will use little memory, but the whole machinery can use arbitrary amount. And that machinery is instantiated using `unlimitedAllocator`, so we as a caller are responsible for estimating the memory footprint. We might not need all the "estimation" code I added here - we could just use the estimation that is registered with the unlimited allocator when we're instantiating new `partitionerToOperator`.
___
*[pkg/sql/colexec/external_sort.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vK_F724Y-UGsR42oN:-M0SoefL7YpZLT4KI_5-:b-8st8v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort.go#L122)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This I'm not sure I understand. In the merge step, the actual memory used will always be constant == the number of partitions. This means that we have to transition to merging all the accumulated partitions once this number reaches `maxNumberActivePartitions`. Once we do that, we can proceed with `externalSorterNewPartition` and do this until the input is exhausted. Only then can we move to the merge step.
</blockquote></details>

I had a different mental model for it, but I see your point, changed.
___
*[pkg/sql/colexec/external_sort.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vEivGEau5jNR4T5gl:-M0QxP3eEUsgjj4lQEnM:b-7kkho9) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort.go#L194)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we make sure that this number does not fall below some number, for example 2? What would currently happen if we can only create one partition?
</blockquote></details>

Added a safety override, but we always merge at least 2 partitions (this override happens within `Next` method, when we're calculating `numPartitionsToMerge`).
___
*[pkg/sql/colexec/external_sort_test.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vMdlj3w7M9nsMnD4q:-M0SmWcUAJqQ3xn2gh6r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort_test.go#L66)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: maybe extract this into a const and `s/numberActivePartitions/maxNumberActivePartitions`
</blockquote></details>

Done.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/external_sort.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vFv-527HwYOIXsI7h:-M0TgUdn4mRreFIni1qw:blqlivw) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort.go#L117)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, I might be confused here, but here is my understanding:
- ordered synchronizer will read a batch from its every input
- the inputs to ordered synchronizer are `partitionerToOperator`s for every partition that we're merging
- those adapters hold onto a single batch of memory
- so the memory usage of the whole "merging" infrastructure is a batch from from every partition plus a batch for the output.

I agree that the merger itself will use little memory, but the whole machinery can use arbitrary amount. And that machinery is instantiated using `unlimitedAllocator`, so we as a caller are responsible for estimating the memory footprint. We might not need all the "estimation" code I added here - we could just use the estimation that is registered with the unlimited allocator when we're instantiating new `partitionerToOperator`.
</blockquote></details>

I think there's a misunderstanding. As far as I understand you're estimating the memory usage of each partition in order to check if it exceeds a certain threshold and if it does, recursively partition. My point is that there is no need to estimate anything. Once you've exceeded the maximum number of partitions as determined in the constructor, you need to repartition since that number is determined using available memory (i.e. if you don't exceed the number of partitions, you don't exceed available memory). The single batch per partition should just be accounted for, but there's no need to do any estimation. Let me know if you want to discuss this offline.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_sort.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vFv-527HwYOIXsI7h:-M0TsEHMAzajjPZW5E2M:bcxugsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort.go#L117)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think there's a misunderstanding. As far as I understand you're estimating the memory usage of each partition in order to check if it exceeds a certain threshold and if it does, recursively partition. My point is that there is no need to estimate anything. Once you've exceeded the maximum number of partitions as determined in the constructor, you need to repartition since that number is determined using available memory (i.e. if you don't exceed the number of partitions, you don't exceed available memory). The single batch per partition should just be accounted for, but there's no need to do any estimation. Let me know if you want to discuss this offline.
</blockquote></details>

Yeah, let's talk offline about this.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_sort.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M-vFv-527HwYOIXsI7h:-M0Y-01Z2Cbumhtdu2Lt:bwaoaf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/53681d6fae6c7b95aacefeb2c5ad155212b23bef/pkg/sql/colexec/external_sort.go#L117)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yeah, let's talk offline about this.
</blockquote></details>

Updated the code as we discussed. Currently because we're using dummy queues we need to allocate batches in `partitionerToOperator`, but once we have disk-backed queues, then we will be able to simply divide the available RAM (minus some memory for an output batch for mergers) by `BufferSizeBytes` and get the max number of partitions as you were describing.

**Comment by yuzefovich** [comment]
Added another commit to fix the memory accounting bug.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Looks great! Happy that the memory accounting issue is fixed!

> Reviewed 5 of 5 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-:-M0YO6ABDBa1VSJjDo0u:bom8flv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/allocator.go, line 161 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M0YNLka73ErayZAAMmy:-M0YNLka73ErayZAAMmz:b13gd60) ([raw file](https://github.com/cockroachdb/cockroach/blob/c476147427d4ba34c7e52df839c60588637a10a2/pkg/sql/colexec/allocator.go#L161)):*
> ```Go
> // ReleaseBatch.
> func (a *Allocator) Clear() {
> 	a.acc.Shrink(a.ctx, a.acc.Used())
> ```

Why change this to shrink? Seems like `Clear` closes the account, so it makes sense to me, but just curious.
___
*[pkg/sql/colexec/execplan.go, line 771 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M0YNlvTC7xGpAarD_eE:-M0YNlvTC7xGpAarD_eF:bj9hyjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c476147427d4ba34c7e52df839c60588637a10a2/pkg/sql/colexec/execplan.go#L771)):*
> ```Go
> 							))
> 						standaloneAllocator := NewAllocator(
> 							ctx, result.createStandaloneMemAccount(
> ```

Instead of creating a monitor etc... Is it possible to just call `NewAllocator(ctx, mon.MakeStandaloneBudget(math.MaxInt64)`?
___
*[pkg/sql/colexec/execplan.go, line 772 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M0YNYSeCwWTucna4DW2:-M0YNYSf7yVOUcHXOj9Z:b-789x8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/c476147427d4ba34c7e52df839c60588637a10a2/pkg/sql/colexec/execplan.go#L772)):*
> ```Go
> 						standaloneAllocator := NewAllocator(
> 							ctx, result.createStandaloneMemAccount(
> 								ctx, flowCtx, monitorNamePrefix,
> ```

Do we want to use a special prefix?

**Review by yuzefovich — COMMENTED** [review]
Same! I'm happy that this solution seems to work and is quite simple.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-:-M0YgSLN5DzC4lBq76_k:bdhzwrd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/allocator.go, line 161 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M0YNLka73ErayZAAMmy:-M0YfaTd3peg5mMjLlzO:bwppnqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c476147427d4ba34c7e52df839c60588637a10a2/pkg/sql/colexec/allocator.go#L161)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why change this to shrink? Seems like `Clear` closes the account, so it makes sense to me, but just curious.
</blockquote></details>

`Clear` does close the account, but we don't want that - we want to prime the allocator for reuse, so we want to keep the account open and just reset it's `used` field to 0. `Empty` also doesn't work, I think shrinking is the only way to do that at the moment.
___
*[pkg/sql/colexec/execplan.go, line 771 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M0YNlvTC7xGpAarD_eE:-M0YfsqF2Z6pAriFqngR:b-tu1907) ([raw file](https://github.com/cockroachdb/cockroach/blob/c476147427d4ba34c7e52df839c60588637a10a2/pkg/sql/colexec/execplan.go#L771)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Instead of creating a monitor etc... Is it possible to just call `NewAllocator(ctx, mon.MakeStandaloneBudget(math.MaxInt64)`?
</blockquote></details>

I tried that first, but the problem is that `MakeStandaloneBudget` instantiates a monitor that "uses" the passed-in capacity, but we want to have "reserved" as the capacity and "used" 0. There appears nothing like this in the API, and all callers to `MakeStandaloneBudget` actually instantiate monitors.
___
*[pkg/sql/colexec/execplan.go, line 772 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M0YNYSeCwWTucna4DW2:-M0YgEsf61hmD8AsDIqF:b5qb85y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c476147427d4ba34c7e52df839c60588637a10a2/pkg/sql/colexec/execplan.go#L772)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we want to use a special prefix?
</blockquote></details>

`createStandaloneMemAccount` will add a suffix to the name internally, I think this addresses your concern.

**Review by asubiotto — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-:-M0YmXxL1z8fvFK5GqXS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/allocator.go, line 161 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M0YNLka73ErayZAAMmy:-M0Ylw3Y4Yvm6ELFdeek:byixukr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c476147427d4ba34c7e52df839c60588637a10a2/pkg/sql/colexec/allocator.go#L161)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`Clear` does close the account, but we don't want that - we want to prime the allocator for reuse, so we want to keep the account open and just reset it's `used` field to 0. `Empty` also doesn't work, I think shrinking is the only way to do that at the moment.
</blockquote></details>

To clarify, it makes sense for me to use `Shrink`, I guess my question is: why was it working with `Clear`?
___
*[pkg/sql/colexec/execplan.go, line 771 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M0YNlvTC7xGpAarD_eE:-M0Ym2ZQ95e_tlZmzCU-:b-ufsv4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c476147427d4ba34c7e52df839c60588637a10a2/pkg/sql/colexec/execplan.go#L771)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I tried that first, but the problem is that `MakeStandaloneBudget` instantiates a monitor that "uses" the passed-in capacity, but we want to have "reserved" as the capacity and "used" 0. There appears nothing like this in the API, and all callers to `MakeStandaloneBudget` actually instantiate monitors.
</blockquote></details>

Every time I look at the memory monitoring code, I get scared. It's so complicated and I'm not sure it's necessary. I guess we can keep it like this then.
___
*[pkg/sql/colexec/execplan.go, line 772 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M0YNYSeCwWTucna4DW2:-M0YmDeC5MlxreM4pEEi:bchryk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c476147427d4ba34c7e52df839c60588637a10a2/pkg/sql/colexec/execplan.go#L772)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`createStandaloneMemAccount` will add a suffix to the name internally, I think this addresses your concern.
</blockquote></details>

Yup! Thanks.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44901)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/allocator.go, line 161 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44901#-M0YNLka73ErayZAAMmy:-M0YwYjy-xDXM-T7fw8a:b-arnim8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c476147427d4ba34c7e52df839c60588637a10a2/pkg/sql/colexec/allocator.go#L161)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

To clarify, it makes sense for me to use `Shrink`, I guess my question is: why was it working with `Clear`?
</blockquote></details>

Actually, I think I saw a problem with `Clear` *because* I tried instantiating standalone budget without a monitor, and it actually seems to work correctly now. I reverted the change back to see what CI says, but I think "shrinking" here is more correct logically, so I'll revert the revert and will merge.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
