### PR TITLE
Proper r/w operations during the addition or deletion of an index

### PR DESCRIPTION
**Pull request by vivekmenezes**
https://github.com/cockroachdb/cockroach/issues/2845

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3106)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Ready for another review. Thanks

**Comment by vivekmenezes** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[sql/update.go, line 200 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3106#-K3GyyAJe2sxUCJzSUec)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/update.go#L200)):</sup>
I've added a comment that we do this to keep this simple and efficient for the common case.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3106)

**Comment by tamird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[sql/update.go, line 200 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3106#-K3GyyAJe2sxUCJzSUec)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/update.go#L200)):</sup>
I don't follow. Not touching indexes unless they've changed would be more efficient, and the added complexity is effectively nothing (slight rearrangement in the iteration over `tableDesc.Mutations`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3106)

**Comment by vivekmenezes** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[sql/update.go, line 200 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3106#-K3GyyAJe2sxUCJzSUec)** ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/update.go#L200)):</sup>
I've reedited this comment and hope it's better. We do not compute the new values for these indexes because we don't write them, and a side effect is we have nothing to compare against. We could by computing the new values, but see little need to do so. I hope it's clearer this time.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3106)

**Pull request merged**
