### PR TITLE
kvserver: add `WholeRowsOfSize` request parameter for scans

### LINKED ISSUE #73618: kvserver: request option to prevent splitting rows in responses
SQL rows can be split across multiple KV pairs. During range splits, we take this into account at the MVCC level to prevent splitting a row across multiple ranges by decoding the KV pairs:

https://github.com/cockroachdb/cockroach/blob/2e038a1d13b1b42ed50a1ff222f53e64126686f1/pkg/storage/mvcc.go#L3881-L3892

However, when doing limited scans (with `MaxSpanRequestKeys` or `TargetBytes` limits), the response can end up returning a partial row, causing the client to either have to discard it or run another request to complete the row. This is particularly relevant for the streaming client API in #68430.

We should add a `Header` parameter that prevents these limits from splitting rows. Since these limits are now strict limits (i.e. we will discard the last value that exceeds `TargetBytes`), this implies that we'll discard these partial rows to keep below the limits _unless_ it is the first row in the result. This needs to be plumbed down into MVCC where the limits are applied:

https://github.com/cockroachdb/cockroach/blob/0ee3bbd6647174d215143609f0d7e577a85077ca/pkg/storage/pebble_mvcc_scanner.go#L714-L719

Note that even though this option will currently only apply to `Scan` and `ReverseScan` requests, we add it to `Header` since that is where the related limits are configured.

### PR DESCRIPTION
**Pull request by erikgrinaker**
**roachpb: rename `TargetBytesAllowEmpty` to `AllowEmpty`**

The `TargetBytesAllowEmpty` parameter currently only applies to
`TargetBytes` limits, but will shortly apply to `MaxSpanRequestKeys` as
well (when the scan API becomes SQL row-aware and may discard the first
row if it's incomplete).

This patch therefore renames the parameter to `AllowEmpty`, to make it
limit-agnostic. There are no behavioral changes.

Release note: None

**storage: add benchmark support for SQL row data**

Release note: None

**kvserver: add `WholeRowsOfSize` request parameter for scans**

This patch adds a `WholeRowsOfSize` parameter to request headers, and a
corresponding `ScanWholeRows` version gate, which prevents scan requests
from including partial SQL rows at the end of the result. See
`api.proto` for details.

This implementation requires the maximum row size to be plumbed down
from SQL. This is a performance optimization which allows use of a
fixed-size ring buffer to keep track of the last KV byte offsets in
`pebbleMVCCScanner`. Two alternative implementations were attempted:
keeping track of all KV byte offsets while scanning, and decoding every
key's row prefix while scanning to track the last row's starting offset.
Both of these alternatives predictably had significant overhead (~10%).

However, this patch comes with a 2-3% performance penalty for scans even
when `WholeRowsOfSize` is disabled, due to code restructuring and
additional checks. Efforts to recover this performance have stalled.

```
name                                                    old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64-24         4.25µs ± 1%    4.26µs ± 1%    ~     (p=0.406 n=16+16)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64-24        6.10µs ± 1%    6.13µs ± 1%    ~     (p=0.065 n=16+14)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64-24       36.4µs ± 1%    37.3µs ± 1%  +2.57%  (p=0.000 n=16+15)
MVCCScan_Pebble/rows=100/versions=10/valueSize=64-24       122µs ± 2%     123µs ± 1%    ~     (p=0.068 n=16+13)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64-24     2.29ms ± 1%    2.36ms ± 1%  +3.08%  (p=0.000 n=16+16)
MVCCScan_Pebble/rows=10000/versions=10/valueSize=64-24    9.15ms ± 1%    9.22ms ± 1%  +0.75%  (p=0.000 n=16+16)
```

Enabling `WholeRowsOfSize` has an additional 0-1.5% penalty for large
scans, as seen below. However, notice that single-key scans with
`versions=10` can have penalties as high as 7%. This is because rows may
omit column families that are all `NULL`, so in order to know whether
the single key is a complete row or not the scan must continue to the
next key. This additional scan can be relatively expensive for
single-key scans if there is a lot of MVCC garbage. However, if the last
row contains the final column family when the limit is hit, this penalty
can be avoided: compare how `rows=3/columnFamilies=3` and
`rows=1/columnFamilies=3` change from `versions=1` to `versions=10`.

```
name                                                                             old time/op    new time/op    delta
MVCCScan_PebbleSQLRows/rows=1/columnFamilies=1/versions=1/valueSize=64-24          4.38µs ± 1%    4.40µs ± 1%     ~     (p=0.075 n=16+14)
MVCCScan_PebbleSQLRows/rows=1/columnFamilies=1/versions=10/valueSize=64-24         6.22µs ± 1%    6.18µs ± 1%   -0.66%  (p=0.004 n=14+15)
MVCCScan_PebbleSQLRows/rows=1/columnFamilies=3/versions=1/valueSize=64-24          4.39µs ± 1%    4.33µs ± 1%   -1.20%  (p=0.000 n=16+16)
MVCCScan_PebbleSQLRows/rows=1/columnFamilies=3/versions=10/valueSize=64-24         6.16µs ± 1%    6.54µs ± 1%   +6.12%  (p=0.000 n=15+16)
MVCCScan_PebbleSQLRows/rows=1/columnFamilies=10/versions=1/valueSize=64-24         4.38µs ± 1%    4.35µs ± 1%   -0.64%  (p=0.000 n=16+14)
MVCCScan_PebbleSQLRows/rows=1/columnFamilies=10/versions=10/valueSize=64-24        6.08µs ± 1%    6.50µs ± 1%   +6.88%  (p=0.000 n=16+16)
MVCCScan_PebbleSQLRows/rows=3/columnFamilies=1/versions=1/valueSize=64-24          5.35µs ± 2%    5.36µs ± 1%     ~     (p=0.277 n=16+15)
MVCCScan_PebbleSQLRows/rows=3/columnFamilies=1/versions=10/valueSize=64-24         9.33µs ± 1%    9.33µs ± 1%     ~     (p=0.904 n=16+16)
MVCCScan_PebbleSQLRows/rows=3/columnFamilies=3/versions=1/valueSize=64-24          5.34µs ± 1%    5.46µs ± 1%   +2.14%  (p=0.000 n=14+16)
MVCCScan_PebbleSQLRows/rows=3/columnFamilies=3/versions=10/valueSize=64-24         9.32µs ± 2%    9.45µs ± 2%   +1.41%  (p=0.000 n=16+16)
MVCCScan_PebbleSQLRows/rows=3/columnFamilies=10/versions=1/valueSize=64-24         5.32µs ± 1%    5.18µs ± 1%   -2.50%  (p=0.000 n=16+15)
MVCCScan_PebbleSQLRows/rows=3/columnFamilies=10/versions=10/valueSize=64-24        9.22µs ± 1%    9.45µs ± 1%   +2.54%  (p=0.000 n=16+15)
MVCCScan_PebbleSQLRows/rows=100/columnFamilies=1/versions=1/valueSize=64-24        35.9µs ± 1%    35.7µs ± 1%   -0.70%  (p=0.001 n=15+15)
MVCCScan_PebbleSQLRows/rows=100/columnFamilies=1/versions=10/valueSize=64-24        117µs ± 1%     117µs ± 1%     ~     (p=0.323 n=16+16)
MVCCScan_PebbleSQLRows/rows=100/columnFamilies=3/versions=1/valueSize=64-24        36.7µs ± 1%    37.0µs ± 1%   +0.82%  (p=0.000 n=15+16)
MVCCScan_PebbleSQLRows/rows=100/columnFamilies=3/versions=10/valueSize=64-24        118µs ± 1%     119µs ± 1%   +0.89%  (p=0.000 n=16+16)
MVCCScan_PebbleSQLRows/rows=100/columnFamilies=10/versions=1/valueSize=64-24       35.9µs ± 0%    36.3µs ± 2%   +1.26%  (p=0.000 n=13+15)
MVCCScan_PebbleSQLRows/rows=100/columnFamilies=10/versions=10/valueSize=64-24       116µs ± 1%     117µs ± 1%   +0.77%  (p=0.000 n=15+16)
MVCCScan_PebbleSQLRows/rows=10000/columnFamilies=1/versions=1/valueSize=64-24      2.41ms ± 1%    2.41ms ± 1%     ~     (p=0.094 n=16+16)
MVCCScan_PebbleSQLRows/rows=10000/columnFamilies=1/versions=10/valueSize=64-24     9.11ms ± 1%    9.10ms ± 1%     ~     (p=0.822 n=14+16)
MVCCScan_PebbleSQLRows/rows=10000/columnFamilies=3/versions=1/valueSize=64-24      2.52ms ± 1%    2.53ms ± 1%     ~     (p=0.591 n=14+15)
MVCCScan_PebbleSQLRows/rows=10000/columnFamilies=3/versions=10/valueSize=64-24     9.28ms ± 1%    9.33ms ± 1%   +0.54%  (p=0.010 n=16+16)
MVCCScan_PebbleSQLRows/rows=10000/columnFamilies=10/versions=1/valueSize=64-24     2.44ms ± 1%    2.46ms ± 1%   +0.96%  (p=0.000 n=15+13)
MVCCScan_PebbleSQLRows/rows=10000/columnFamilies=10/versions=10/valueSize=64-24    9.13ms ± 1%    9.18ms ± 1%   +0.59%  (p=0.006 n=15+16)
```

Resolves #73618.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@yuzefovich Enabling `WholeRowsOfSize` will prevent `ResumeNextBytes` from being returned. The assumption is that a caller who enables this won't be interested in the size of the next omitted KV pair, but rather the size of the next omitted SQL row, but obtaining the full size of the entire row will require scanning further ahead to find any remaining KV pairs that belong to the row.

I'm guessing this is something you'd need, and which might be worth the additional overhead? If so, let me know, and I'll add it to the PR.

**Comment by erikgrinaker** [comment]
Please hold off on reviewing this -- I found another fairly severe performance regression that will require restructuring the code.

**Comment by erikgrinaker** [comment]
>Please hold off on reviewing this -- I found another fairly severe performance regression that will require restructuring the code.

Afraid this regression can't be avoided in all cases -- since rows can omit `NULL` column families, we sometimes can't know whether a row is complete or not without scanning to the next key. However, I did implement a fast path for when the last row contains the final column family ID. See PR description for details.

**Review by yuzefovich — APPROVED** [review]
Nice work! It'd be beneficial if someone from storage reviewed as well, but it :lgtm:

> Enabling `WholeRowsOfSize` will prevent `ResumeNextBytes` from being returned. The assumption is that a caller who enables this won't be interested in the size of the next omitted KV pair, but rather the size of the next omitted SQL row, but obtaining the full size of the entire row will require scanning further ahead to find any remaining KV pairs that belong to the row.

> I'm guessing this is something you'd need, and which might be worth the additional overhead? If so, let me know, and I'll add it to the PR.

Without any evidence I feel like we don't want to scan more keys to provide the size of the whole row, so it seems ok to me to relax the meaning of `ResumeNextBytes` so that it provides a lower-bound estimate on the size of the next row. This way we can share all sizing information available to us without any overhead.

Re: performance regression when `WholeRowsOfSize` is disabled: it seems a bit unfortunate, but the only way of getting the performance back I can think of is by using code generation - similar to what we do with the vectorized templates, we'd perform a check of `wholeRows` only once and choose the appropriate scanner object from two options. I'd guess that this is a complexity that we wouldn't want to add, right?

> Reviewed 10 of 10 files at r1, 3 of 3 files at r2, 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-:-Mt42H9J7LghfKWVVdLC:b927zrs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/storage/pebble_mvcc_scanner.go, line 904 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-Mt4-36l5KR3VHSfQfMt:-Mt4-36m8JfwyUVSFgaE:bylhjig) ([raw file](https://github.com/cockroachdb/cockroach/blob/a73016560da7a91db3371430db1116535d802a0d/pkg/storage/pebble_mvcc_scanner.go#L904)):*
> ```Go
> 		p.resumeReason = roachpb.RESUME_BYTE_LIMIT
> 		p.resumeNextBytes = int64(p.results.sizeOf(len(rawKey), len(val)))
> ```

nit: seems like unnecessary new line.
___
*[pkg/kv/kvserver/batcheval/cmd_scan_test.go, line 244 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-Mt41WNjE_6IzzAaKuOo:-Mt41WNjE_6IzzAaKuOp:b-nxafz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a73016560da7a91db3371430db1116535d802a0d/pkg/kv/kvserver/batcheval/cmd_scan_test.go#L244)):*
> ```Go
> }
> 
> // makeRowKey makes a key for a SQL row for use in benchmarks, using the system
> ```

nit: should we drop mention of "benchmarks" since it is now also used in the unit tests?

**Review by erikgrinaker — COMMENTED** [review]
TFTQR!

>Without any evidence I feel like we don't want to scan more keys to provide the size of the whole row, so it seems ok to me to relax the meaning of `ResumeNextBytes` so that it provides a lower-bound estimate on the size of the next row. This way we can share all sizing information available to us without any overhead.

Yeah, I think that makes sense. Changed it to always return the size of the next KV pair, and made a note of it in API comments.

>Re: performance regression when WholeRowsOfSize is disabled: it seems a bit unfortunate, but the only way of getting the performance back I can think of is by using code generation - similar to what we do with the vectorized templates, we'd perform a check of wholeRows only once and choose the appropriate scanner object from two options. I'd guess that this is a complexity that we wouldn't want to add, right?

I think I'd rather avoid that, at least when the regression isn't worse than it is. It's possible that this won't end up mattering that much when the data has to pass through the whole stack. Will have a look at the nightly roachperf runs once it merges.

Maybe @cockroachdb/storage have opinions here, or better yet, some optimization tricks up their sleeve.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-:-Mt4EOTx6-mUU3PLaKYP:b-w70zwq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/storage/pebble_mvcc_scanner.go, line 904 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-Mt4-36l5KR3VHSfQfMt:-Mt4DqH18y6KN0E2W0In:bvwtsjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a73016560da7a91db3371430db1116535d802a0d/pkg/storage/pebble_mvcc_scanner.go#L904)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: seems like unnecessary new line.
</blockquote></details>

I have a slight preference for it, since I feel like it gives some visual separation between the byte and key limits -- it gets pretty dense otherwise.
___
*[pkg/kv/kvserver/batcheval/cmd_scan_test.go, line 244 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-Mt41WNjE_6IzzAaKuOo:-Mt4E8pZ7hw80Ec5QGyB:ba2mb8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a73016560da7a91db3371430db1116535d802a0d/pkg/kv/kvserver/batcheval/cmd_scan_test.go#L244)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we drop mention of "benchmarks" since it is now also used in the unit tests?
</blockquote></details>

Yes, thanks -- this was left behind after copying the function.

**Comment by erikgrinaker** [comment]
@sumeerbhola Would you, or anyone from storage, mind giving this a quick look? I'll be OOO for the next week, and would like to get this merged.

**Comment by yuzefovich** [comment]
I rebased on top master to fix the merge skew in the first commit.

**Comment by sumeerbhola** [comment]
@erikgrinaker, sorry I missed your previous ping.

I haven't looked carefully at the code, but I am curious about the following since based on past experience with `intentInterleavingIter` these small scans are dominant in our roachtest workloads.

> However, notice that single-key scans with
versions=10 can have penalties as high as 7%. This is because rows may
omit column families that are all NULL, so in order to know whether
the single key is a complete row or not the scan must continue to the
next key. This additional scan can be relatively expensive for
single-key scans if there is a lot of MVCC garbage. 

- Do you have a cpu profile that you could share (profile file is preferable to a screenshot)? I am curious whether the cost is the work happening in `advanceKey` (and what exactly under there, since we have some ideas for a `NextPrefix` optimization), or the extra work in `continuesFirstRow` or something else.
- Do we expect this to effect kv95, tpcc etc., or do they not use column families or not expected to have many versions?

**Comment by erikgrinaker** [comment]
OOO this week and not at a computer, but when I looked at this last I believe I found the overhead to be due to advanceKey. Also, the overhead appears to increase with the amount of MVCC garbage, which further points to advanceKey since getAndAdvance is never called for MVCC garbage.

This shouldn't affect most workloads (apart from the general 3% scan overhead), as I believe use of column families is rare. I was planning on looking at the nightly roachtest runs after merging this, but I can do some kv95/tpcc runs when I'm back next week if necessary.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 2 of 10 files at r1, 2 of 22 files at r5, 1 of 3 files at r6, 18 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-:-MtoJaTE5v4qQOM8yDN6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @yuzefovich)

___
*[pkg/storage/pebble_mvcc_scanner.go, line 149 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-MtoG29TBFbDbdxUytIh:-MtoG29TBFbDbdxUytIi:b-hazgad) ([raw file](https://github.com/cockroachdb/cockroach/blob/da6c0da54d23577303638d28c1a111f803ab71be/pkg/storage/pebble_mvcc_scanner.go#L149)):*
> ```Go
> // key could not be decoded. repr must be a valid, non-empty KV representation,
> // otherwise this may panic.
> func (p *pebbleResults) extractKey(repr []byte) roachpb.Key {
> ```

does `extractKey` need a `pebbleResults` receiver? it appears to be a pure function of `repr`
___
*[pkg/storage/pebble_mvcc_scanner.go, line 160 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-MtoGHTL7Ww-A7-ln9zS:-MtoGHTL7Ww-A7-ln9zT:b-eujt00) ([raw file](https://github.com/cockroachdb/cockroach/blob/da6c0da54d23577303638d28c1a111f803ab71be/pkg/storage/pebble_mvcc_scanner.go#L160)):*
> ```Go
> // getRowPrefix decodes a SQL row prefix from the given key. Returns nil if the
> // key is not a valid SQL row, or if the prefix is the entire key.
> func (p *pebbleResults) getRowPrefix(key roachpb.Key) []byte {
> ```

same question about the `pebbleResults` receiver.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74602)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @jbowens and @yuzefovich)

___
*[pkg/storage/pebble_mvcc_scanner.go, line 149 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-MtoG29TBFbDbdxUytIh:-MtsJrNM-kA2mearnWDi:b573wl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/da6c0da54d23577303638d28c1a111f803ab71be/pkg/storage/pebble_mvcc_scanner.go#L149)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

does `extractKey` need a `pebbleResults` receiver? it appears to be a pure function of `repr`
</blockquote></details>

Not really, I just made it a method because it's specific to the `pebbleResults` binary encoding. Changed it into a function `extractResultKey()`, ditto with `getRowPrefix()`.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 160 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74602#-MtoGHTL7Ww-A7-ln9zS:-MtsKDvc0XXHzD6u3X4X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da6c0da54d23577303638d28c1a111f803ab71be/pkg/storage/pebble_mvcc_scanner.go#L160)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

same question about the `pebbleResults` receiver.
</blockquote></details>

Done.

**Comment by erikgrinaker** [comment]
TFTRs!

bors r+

**Comment by erikgrinaker** [comment]
>This shouldn't affect most workloads (apart from the general 3% scan overhead), as I believe use of column families is rare. I was planning on looking at the nightly roachtest runs after merging this

Don't see any significant effect on roachperf nightlies.

**Pull request merged**
