### PR TITLE
pgwire: transmit 24:00 correctly for Time/TimeTZ

### LINKED ISSUE #44548: lib/pq handling of 24:00:00 is broken
lib/pq prints 24:00 time as `0001-01-01 00:00:00`, which is indistinguishable from '00:00'. This is because time is represented as a time.Time in lib/pq. 

```

root@127.0.0.1:51083/movr> select '24:00'::timetz;
            time
-----------------------------
  0000-01-01 00:00:00+00:00
(1 row)

Time: 320µs

root@127.0.0.1:51083/movr> select '24:00'::timetz::string;
    text
------------
  24:00:00
(1 row)

root@127.0.0.1:51083/movr> select '00:00'::timetz;
            time
-----------------------------
  0000-01-01 00:00:00+00:00
(1 row)

Time: 263µs
```

This breaks anything requiring a switch on `time.Time` to parse back into `DTimeTZ` (and `DTime`). 

I think as a result, backups for `time`/`timetz` columns are broken if someone encoded 24:00 time in the database, since backups use lib/pq formatting.

Furthermore, this prevents us from using `TestCopyRandom` for `24:00` values for Time/TimeTZ.

### PR DESCRIPTION
**Pull request by otan**
We previously relied on golang's time.Time library to return 24:00 time
for us; however, time.Time does not parse 24:00 well, nor does it print
24:00 as on the same day (it uses the next day).

As such, when parsing or emitting time.Time, we have to be super weary
of how we output 24:00 time. Two major changes:
* update lib/pq to pick up https://github.com/lib/pq/pull/944 such that
it can parse 24:00 time externally.
* update places where time.Time is parsed from a go driver or lib/pq to
correctly handle 24:00 cases.

Resolves #44548.

Release note (sql change, bug fix): 24:00 time now displays correctly in
the cli, returning `0001-01-02 00:00:00`. Furthermore, backups correctly
emit and read in 24:00 time properly.

### CODE REVIEW

**Comment by rohany** [comment]
Whats the reason for adding a new function here that allows 24:00? Why can't we just update existing cases to handle it?

**Comment by otan** [comment]
Because existing functions will overflow 24:00 to 00:00. This needs to be explicit and that's only from parsing and reading from disk.

**Review by rohany — APPROVED** [review]
LGTM, i would just make that more explicit then -- I can imagine a month or two from now I wouldn't remember which one to use where.

**Comment by otan** [comment]
tftr!

bors r=rohany

**Pull request merged**
