### PR TITLE
sql: support SHOW GRANTS ON PROCEDURE

### PR DESCRIPTION
**Pull request by mgartner**
Epic: CRDB-25388

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111598#-:-Nfly_Vn-udo50MpwuFV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111598#-:-NfmFyJd8YNNq6a0u6Tb:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111598#-:-NfmOcymEr0ieek_nIBg:bnfp4nl)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/procedure_privileges` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111598#-NfmOWZE5B7MUA1hXKAR:-NfmOWZE5B7MUA1hXKAS:bs9fud3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff716d959a65d0cdd102b3c9af14273e8a1de0d/pkg/sql/logictest/testdata/logic_test/procedure_privileges#L42)):*
> ```
> 
> query TTTTTTB colnames,rowsort
> SHOW GRANTS ON PROCEDURE test_priv_p1(), test_priv_p2(INT), test_priv_p3()
> ```

Would a test with a nonexistent signature be interesting? Like `test_priv_p2(STRING)`.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111598)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/logictest/testdata/logic_test/procedure_privileges` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111598#-NfmOWZE5B7MUA1hXKAR:-NfqgAlO5lvM_5aeroYz:bynmu5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff716d959a65d0cdd102b3c9af14273e8a1de0d/pkg/sql/logictest/testdata/logic_test/procedure_privileges#L42)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Would a test with a nonexistent signature be interesting? Like `test_priv_p2(STRING)`.
</blockquote></details>

Yes, good idea. Done.

**Pull request merged**
