### PR TITLE
crosscluter/logical: fix source-side table name parsing 

### LINKED ISSUE #127194: ldr: Unable to resolve fully qualified table name
When starting up LDR using a qualified tablename such as `public.users` an error will be returned that the relation does not exist.

Error Case
```
demo@127.0.0.1:26258/demoapp/movr> CREATE LOGICAL REPLICATION STREAM FROM TABLES (public.users) on                                                                                       
                                -> 'postgresql://demo:demo16099@127.0.0.1:26257/movr?options=-ccluster%3Ddemoapp&sslmode=require&sslrootcert=%2FUsers%2Fjeremyyang%2F.cockroach-demo%2Fca
                                -> .crt' INTO TABLES (public.users) WITH CURSOR = '2024-07-12T19:36:15Z';                                                                                
ERROR: ERROR: crdb_internal.start_replication_stream_for_tables(): relation "public.users" does not exist (SQLSTATE 42P01)
```

Successful case
```
demo@127.0.0.1:26258/demoapp/movr> CREATE LOGICAL REPLICATION STREAM FROM TABLES (users) on                                                                                              
                                -> 'postgresql://demo:demo16099@127.0.0.1:26257/movr?options=-ccluster%3Ddemoapp&sslmode=require&sslrootcert=%2FUsers%2Fjeremyyang%2F.cockroach-demo%2Fca
                                -> .crt' INTO TABLES (public.users) WITH CURSOR = '2024-07-12T19:36:15Z'; 
        job_id
----------------------
  985473379668623361
```

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, we were not correctly parsing the schema name on the
source cluster.

Fixes https://github.com/cockroachdb/cockroach/issues/127194
Release note: None

### CODE REVIEW

**Review by Jeremyyang920 — APPROVED** [review]

**Comment by stevendanna** [comment]
@dt for a look at the last commit here.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127242)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

___
*[`pkg/ccl/crosscluster/producer/event_stream.go` line 545 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127242#-O20C2zo6Q7pZFgpVB-G:-O20C2zo6Q7pZFgpVB-H:b-mviia1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d786d47f1b936a556ebfc3aaec806f2318f8c20/pkg/ccl/crosscluster/producer/event_stream.go#L545)):*
> ```Go
> 	}
> 	if !evalCtx.TxnImplicit {
> 		return nil, pgerror.Newf(pgcode.InvalidParameterValue,
> ```

just curious: is this going to work in a multi-statement implicit transaction? those occur if multiple statements are all sent in one string, separated by semicolons. if not, then the check should also include `TxnIsSingleStmt`.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127242)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[`pkg/ccl/crosscluster/producer/event_stream.go` line 545 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127242#-O20C2zo6Q7pZFgpVB-G:-O20UdRy9k9uuyN4VonO:b-wdvlp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d786d47f1b936a556ebfc3aaec806f2318f8c20/pkg/ccl/crosscluster/producer/event_stream.go#L545)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just curious: is this going to work in a multi-statement implicit transaction? those occur if multiple statements are all sent in one string, separated by semicolons. if not, then the check should also include `TxnIsSingleStmt`.
</blockquote></details>

Good call. Thanks.  I changed this and also moved these checks to before we attempt to commit the transaction as that just felt a bit better to me.

**Comment by stevendanna** [comment]
blathers backport 24.2

**Pull request merged**
