### PR TITLE
server: add /_status/certificates endpoint.

### PR DESCRIPTION
**Pull request by mberhault**
Work towards #15027

Lists certificates currently active on the requested node.
CA and node certificates only (client certificates aren't used
on the node) but leave room to expand.

This will be used by a debug page.

### CODE REVIEW

**Comment by mberhault** [comment]
grr! embedded.go making the reviewers thing terrible.
@BramGruneir: you've done a lot of status stuff recently.
@a-robinson: for security things. I may switch the bytes to be a re-marshalled version of the already-decoded certificates, but I'm not sure that's much better.

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/security/certificate_manager.go, line 431 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkp_y3N6x7WU4WUAXhN:-Kkp_y3N6x7WU4WUAXhO:b-6paw23) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/security/certificate_manager.go#L431)):*
> ```Go
> 	defer cm.mu.RUnlock()
> 
> 	if !cm.initialized {
> ```

can this be moved about the lock?

---

*[pkg/server/status.go, line 211 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkpa2v8rCjjZK-dN1_K:-Kkpa2v8rCjjZK-dN1_L:blco9m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/server/status.go#L211)):*
> ```Go
> 	}
> 
> 	if s.cfg.Insecure {
> ```

Move this to the top of the function?  No need to parse the node id or dial a node if we're in insecure mode.

---

*[pkg/server/status_test.go, line 626 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkpc5eDlmrKjYazDWEd:-Kkpc5eDlmrKjYazDWEe:b-heae9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/server/status_test.go#L626)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	ts := startServer(t)
> 	defer ts.Stopper().Stop(context.TODO())
> ```

nit context.Background() I think is the correct choice now

---

*[pkg/server/serverpb/status.proto, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-KkpbKjPsX-AsXpoxXCk:-KkpbKjPsX-AsXpoxXCl:b-6xif0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/server/serverpb/status.proto#L55)):*
> ```protobuf
>   string error_message = 2;
>   // data is the raw file contents of the certificate. This means PEM-encoded DER data.
>   bytes data = 3;
> ```

Why not include some of the other details from the certInfo?  (Perhaps I'm just ignorant if security concerns).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-:-KkpcWP9SC4fwIMc8APu:bnfp4nl)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/security/certificate_manager.go, line 431 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkp_y3N6x7WU4WUAXhN:-KkpffU01zHOuJ8ZD6Ro:brwnpht) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/security/certificate_manager.go#L431)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

can this be moved about the lock?
</blockquote></details>

uh. no, this is set inside the lock alongside the variables we're examining here.

---

*[pkg/server/status.go, line 211 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkpa2v8rCjjZK-dN1_K:-Kkpghx9qNOPyDOT-c1G:b-ar9vjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/server/status.go#L211)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Move this to the top of the function?  No need to parse the node id or dial a node if we're in insecure mode.
</blockquote></details>

Moved to before the `dial`. A bad node ID format is still an error regardless of the secure mode.

---

*[pkg/server/status_test.go, line 626 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkpc5eDlmrKjYazDWEd:-Kkpg6h1ApHa-5o4ilnV:b5cctti) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/server/status_test.go#L626)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

nit context.Background() I think is the correct choice now
</blockquote></details>

we seem to still be using `context.TODO` for all test.

---

*[pkg/server/serverpb/status.proto, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-KkpbKjPsX-AsXpoxXCk:-Kkpg9j_X01J7wZiBalZ:b-9kjysp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/server/serverpb/status.proto#L55)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not include some of the other details from the certInfo?  (Perhaps I'm just ignorant if security concerns).
</blockquote></details>

We definitely don't want the key, Type and error are included, the parsed certificates don't help (we would have to marshal them again). Name and ExpirationTime are inside the certificates.
The only potentially useful one if the filename, but not that much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067)*

**Comment by BramGruneir** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/security/certificate_manager.go, line 431 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkp_y3N6x7WU4WUAXhN:-KkpijL0LPEtKbbroRhE:b9ryjuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/security/certificate_manager.go#L431)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

uh. no, this is set inside the lock alongside the variables we're examining here.
</blockquote></details>

Ah, so shouldn't the field be cm.mu.initialized? 

---

*[pkg/server/status_test.go, line 626 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkpc5eDlmrKjYazDWEd:-KkpisEmhrQrv1xXIsx6:b-62ltm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/server/status_test.go#L626)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

we seem to still be using `context.TODO` for all test.
</blockquote></details>

Yeah, I thought the consensus on this was to move to `.background` for tests, and only use todo in places were we haven't setup context plumbing yet.  Not a big deal. 

---

*[pkg/server/serverpb/status.proto, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-KkpbKjPsX-AsXpoxXCk:-Kkpj9e8ATyJDYPTV_53:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/server/serverpb/status.proto#L55)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

We definitely don't want the key, Type and error are included, the parsed certificates don't help (we would have to marshal them again). Name and ExpirationTime are inside the certificates.
The only potentially useful one if the filename, but not that much.
</blockquote></details>

SGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067)*

**Comment by mberhault** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/security/certificate_manager.go, line 431 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkp_y3N6x7WU4WUAXhN:-KkpjxB9hRVNwUATwKxt:b-ojrz5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/security/certificate_manager.go#L431)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Ah, so shouldn't the field be cm.mu.initialized? 
</blockquote></details>

`mu` is just a plain variable, not a struct-with-embedded-mutex.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067)*

**Comment by a-robinson** [comment]
You say "this will be used by a debug page", but I thought debug pages typically just displayed what was returned from the status endpoint verbatim. Is the contents of the cert files actually interesting to look at in its raw form?

---

Reviewed 4 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/server/status.go, line 236 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkpl5v1Lqr8H5IVDTQa:-Kkpl5v1Lqr8H5IVDTQb:btktyan) ([raw file](https://github.com/cockroachdb/cockroach/blob/89098f791e67162aa6cbe802abde7a8607915c98/pkg/server/status.go#L236)):*
> ```Go
> 			details.Type = serverpb.CertificateDetails_NODE
> 		default:
> 			// Ignore client certificates for now.
> ```

Minor, but it's more future-proof to have an explicit case for client certificates and to have a panic or `log.Fatal` in the default case.

---

*[pkg/server/status_test.go, line 626 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkpc5eDlmrKjYazDWEd:-KkplMFfbayVqPDf4bkk:ba3zo2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a37deaa3ea692b0dd59f5abef8ce76a93b4de2b9/pkg/server/status_test.go#L626)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Yeah, I thought the consensus on this was to move to `.background` for tests, and only use todo in places were we haven't setup context plumbing yet.  Not a big deal. 
</blockquote></details>

There wasn't a consensus, last I knew. A couple of us tried to create a consensus on `context.Background` but got outvoted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-:-KkploPcb0cPM6Jbg690:brigh5b)*

**Comment by mberhault** [comment]
debug pages massage the data quite a lot (see `pkg/server/debug_range.go` for example).
I'm not going to have a proto to mimic the contents of certificates, there's just too much stuff in there. If we really want to have javascript use this endpoing, there are pem and asn1 libraries out there.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-:-KkpogHqG6RX-3NXnfS2:b-us4wbd)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/status.go, line 236 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067#-Kkpl5v1Lqr8H5IVDTQa:-KkqLyMrrZZOIL1Csvdo:b-moxkq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d746f25ffeb6b1b577e1feadf24ff31af42ea3/pkg/server/status.go#L236)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Minor, but it's more future-proof to have an explicit case for client certificates and to have a panic or `log.Fatal` in the default case.
</blockquote></details>

adding a noop case for `Client`, but switching to an error return on `default:`. We should have tests for this that will catch it, and even if it slips by, I'd rather have an error (which gets written to the status/debug pages) than crash.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16067)*

**Pull request merged**
