### PR TITLE
sql: remove an UnexpectedWithIssueErrorf

### PR DESCRIPTION
**Pull request by andreimatei**
Since the respective issue has been closed.
Touches #12876

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30563#-:-LNB9ssHES2eccUtHNNR:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by madelynnblue — APPROVED** [review]

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30563#-:-LNCyuKuDXcT_mP4j1BK:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30563#-:-LNCzzpY8kocy5jyCoZK:b-ydi9aw)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30563#-:-LNDKSQZC_yI-sp4aZuw:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
