### PR TITLE
util/timeutil: remove fake time support 

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by petermattis** [comment]
@knz or @bdarnell Is `COCKROACH_SIMULATED_OFFSET` used by the Jepsen tests?

**Comment by knz** [comment]
The Jepsen tests tweak the system clock and do not use this.

**Comment by knz** [comment]
I do not recall ever seeing this env var being used, FWIW. It was introduced when we introduced the timeutil package.

**Comment by bdarnell** [comment]
:lgtm:

I also don't remember ever seeing this used.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18553#-:-KuLJoID0szGjEQmcEqs:b-ap65m8)*

**Comment by petermattis** [comment]
Roger. I can't find any references to `COCKROACH_SIMULATED_OFFSET` in our other repos. I'm going to merge. We can always revert if it turns out this was being used somewhere.

**Pull request merged**
