### PR TITLE
randgen: ensure template does not become stale

### PR DESCRIPTION
**Pull request by postamar**
This commit adds a unit test that ensures that the hard-coded table template is not stale in the face of RunPostDeserializationChanges.

Informs #94026.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/catalog/randgen/templates.go` line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94840#-NL7bOJzC4FWjJtTGBKz:-NL7bOJzC4FWjJtTGBL-:b-8exubs) ([raw file](https://github.com/cockroachdb/cockroach/blob/42552ad93834a61ac052207ff06ee3de3c440bc9/pkg/sql/catalog/randgen/templates.go#L200)):*
> ```Go
> 		Version: 1,
> 		State:   descpb.DescriptorState_PUBLIC,
> 		Privileges: catpb.NewCustomSuperuserPrivilegeDescriptor(
> ```

I am confused by this. Why is this needed?
in `tables.go` line 177, the privileges are being overwritten.

**Comment by postamar** [comment]
It's needed to pass the test? It's nice to know that the hardcoded template hasn't rotted.

**Review by knz — APPROVED** [review]

**Comment by knz** [comment]
thanks

**Comment by postamar** [comment]
Thanks for the review!

bors r+

**Pull request merged**
