### PR TITLE
logictest: fix user cmd to respect nodeidx

### PR DESCRIPTION
**Pull request by andyyang890**
logictest: change logicTest to store per-node clients for users

This patch changes the `clients` field within `logicTest` from type
`map[string]*gosql.DB` to `map[string]map[int]*gosql.DB` in order to
store per-node clients for each user. This allows the `user` cmd in
logic tests to fetch a client for the specified node instead of the
previously used node.

Release note: None

----

logictest: move paragraph in comment that got separated

Release note: None

----

logictest: fix user cmd to respect nodeidx for cockroach-go testserver

This patch fixes the client creation for logic tests that use the
cockroach-go testserver to use the specified nodeidx when connecting.

Release note: None

----

Informs #92342

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96282#-NNCRXUs2VVOHCQG8vk9):*
i don't think i entirely understand what this is fixing - could you give an example? or also, i don't quite understand how it worked before
___
*[`pkg/sql/logictest/logic.go` line 3883 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96282#-NNCQsv15qAa5a-Fa61I:-NNCQsv15qAa5a-Fa61J:bmpme89) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ea938ead63b3dfe042a1fb6c1e3879b1716619/pkg/sql/logictest/logic.go#L3883)):*
> ```Go
> 			if err := c.Close(); err != nil {
> 				t.Fatalf("failed to close connection to node %d for user %s: %v", i, username, err)
> 			}
> ```

does this loop also need to do `delete(userClients, i)`
___
*[`pkg/sql/logictest/testdata/logic_test/testserver_upgrade_node` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96282#-NNAYkzp3amvgCQQ3CkW:-NNAYkzp3amvgCQQ3CkX:bja1rb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/729ed634c7e7a6078bcd4800729468c02d55229f/pkg/sql/logictest/testdata/logic_test/testserver_upgrade_node#L39)):*
> ```
> false
> 
> user root nodeidx=0
> ```

nice test! i think a comment could help explain what this is testing. maybe it could be like 

```
# start of test <description>

the test code

# end of test for <description>
```

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96282#-NNCRXUs2VVOHCQG8vk9):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think i entirely understand what this is fixing - could you give an example? or also, i don't quite understand how it worked before
</blockquote></details>

Previously, if you use the `user` directive with a user that was already previously used while also specifying a new nodeidx (e.g. `user root nodeidx=1`), the new nodeidx would not be honored because the `setUser` function short circuits here:
https://github.com/cockroachdb/cockroach/blob/de9128ef00da226607c328d3b4762dccaa17b988/pkg/sql/logictest/logic.go#L1141-L1147

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 3883 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96282#-NNCQsv15qAa5a-Fa61I:-NNFdkYj0QrqXh6f9lyk:bj3q2sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ea938ead63b3dfe042a1fb6c1e3879b1716619/pkg/sql/logictest/logic.go#L3883)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this loop also need to do `delete(userClients, i)`
</blockquote></details>

I think it's unnecessary because the `userClients` map is immediately discarded in the `delete(t.clients, username)` call that follows
___
*[`pkg/sql/logictest/testdata/logic_test/testserver_upgrade_node` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96282#-NNAYkzp3amvgCQQ3CkW:-NNFmUxy5k_J1LmmeUgr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/729ed634c7e7a6078bcd4800729468c02d55229f/pkg/sql/logictest/testdata/logic_test/testserver_upgrade_node#L39)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nice test! i think a comment could help explain what this is testing. maybe it could be like 

```
# start of test <description>

the test code

# end of test for <description>
```
</blockquote></details>

Done.

**Review by andyyang890 — COMMENTED** [review]
Ready for another look! Also I moved the refactoring for the user connection creation code out of this PR. Will put up a new PR that also fixes the issue of not persisting any connections created within `execQuery` to `t.clients`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96282#-:-NNFyEgr4ROFJEjT3hcK:b-y8j4ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]
nice fixes!

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96282#-:-NNITzvw23g9NyOc_SZK:b-x50kxw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

**Comment by andyyang890** [comment]
TFTR!

bors r=rafiss

**Pull request merged**
