### PR TITLE
cli: remove auto-init with `cockroach start` without `--join`

### LINKED ISSUE #44116: cli: remove auto-init for `start` without `--join`.
The auto-init behavior of `cockroach start` without `--join` was marked as deprecated in 19.2. Remove it in 20.1.

Informs (and simplifies) #26722

### PR DESCRIPTION
**Pull request by knz**
Fixes #44116. 
Informs #24118.

Release note (backward-incompatible change): A CockroachDB node
started with `cockroach start` without the `--join` flag no
longer automatically initializes the cluster. The `cockrach init`
command is now mandatory. The auto-initialization behavior had
been deprecated in version 19.2.

### CODE REVIEW

**Comment by knz** [comment]
I'm expecting a bunch of tests to fail, and I'll fix them.

**Comment by knz** [comment]
Some items identified by the CI failures:

- [ ] `github.com/cockroachdb/cockroach-go/testserver` must be changed to always use `init`
- [ ] bump the dep in `example-orms` to pick up the first change
- [ ] change `roachprod` to use `init`

**Comment by danhhz** [comment]
Ooo, this might make things a little less messy in #44249. Any guesses on timeline for this merging?

**Comment by knz** [comment]
I'd say end of February unless re-prioritized 
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by knz** [comment]
Superseded by #51245

**Pull request closed without merging**
