### PR TITLE
opt: Add missing functionality to Optgen

### PR DESCRIPTION
**Pull request by andy-kimball**
Optgen has several limitations that this PR addresses:

1. Allow multiple op matchers for the same op child:

  (Not $input:(Comparison) & ^(Contains))

Currently, any matchers beyond the first must be custom matchers that
call out to Go code. This prevents useful patterns like the above.
Fixing this required some big changes to the Optgen grammar. Now the
grammar doesn't distinguish between op matchers and custom match
functions - they can be freely intermixed. When the compiler does
semantic analysis, it decides which kind of matcher it is based on
the name. If it's a custom match function, the compiler now creates a
CustomFuncExpr so that the code generator can easily recognize it.

2. Allow the (OpName) builtin function to be used in match patterns:

  (Binary $left:* (Null) & ^(HasNullableArgs (OpName))

Previously, the (OpName) function was only supported in replace patterns.
This change resulted in merging the codegen for custom match functions
with that for replace patterns, since it's very similar.

The PR also changes two of our existing rules, as a showcase and test of
the new functionality. There are also some constant folding patterns
coming soon that will need the new functionality (that's what triggered
this work).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/optgen/lang/expr.go, line 76 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23266#-L6Wq6ZId8-nacD0OvcX:-L6Wq6ZId8-nacD0OvcY:b-e0r7ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35fbee8d356c32fa77ed8331d685d9a9dc8e853/pkg/sql/opt/optgen/lang/expr.go#L76)):*
> ```Go
> 	// example:
> 	//
> 	//   myVisitFunc := func(e Expr) Expr {
> ```

[nit] this would not build, need a separate `var myVisitFunc func(e Expr) Expr` before

---

*[pkg/sql/opt/xform/rules/bool.opt, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23266#-L6WjH_NkgtnXmy9eIQI:-L6WjH_NkgtnXmy9eIQJ:b-ccgcf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35fbee8d356c32fa77ed8331d685d9a9dc8e853/pkg/sql/opt/xform/rules/bool.opt#L80)):*
> ```
> # comparisons can be negated except for Contains.
> [NegateComparison, Normalize]
> (Not $input:(Comparison $left:* $right:*) & ^(Contains))
> ```

Nice!
Can more be added? Would `^(Contains | JSONExists)` work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23266#-:-L6X9A13JhnrkCFqwBG8:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/optgen/lang/expr.go, line 76 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23266#-L6Wq6ZId8-nacD0OvcX:-L6XBkVS76s9z8owc7I5:bje2m3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35fbee8d356c32fa77ed8331d685d9a9dc8e853/pkg/sql/opt/optgen/lang/expr.go#L76)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this would not build, need a separate `var myVisitFunc func(e Expr) Expr` before
</blockquote></details>

Good point, I just made it a standalone function.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23266#-L6WjH_NkgtnXmy9eIQI:-L6X9yfvRo5SR45rBcDX:bau03t4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35fbee8d356c32fa77ed8331d685d9a9dc8e853/pkg/sql/opt/xform/rules/bool.opt#L80)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Nice!
Can more be added? Would `^(Contains | JSONExists)` work?
</blockquote></details>

Yes, that would work fine today.  More generally, I'd like to enable full boolean expressions to work, so that this would also work:
```
(Comparison & ^(Contains | JSONExists)
  $left:*
  $right:*
)
```
But there are grammar issues that I'd need to work out, since parentheses would then be overloaded. They would both create matchers and establish boolean precedence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23266)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 16 of 17 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/optgen/cmd/langgen/exprs_gen.go, line 193 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23266#-L6X07yg4sCOgiUZwNGP:-L6X07yg4sCOgiUZwNGQ:b-8pck5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35fbee8d356c32fa77ed8331d685d9a9dc8e853/pkg/sql/opt/optgen/cmd/langgen/exprs_gen.go#L193)):*
> ```Go
> 
> // func (e *SomeExpr) Visit(visit VisitFunc) Expr {
> //   children := visitExprChildren*(e, visit)
> ```

visitExprChildren -> visitChildren

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23266#-:-L6XJUtXYq7dQkugHUgG:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: 13 of 17 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/optgen/cmd/langgen/exprs_gen.go, line 193 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23266#-L6X07yg4sCOgiUZwNGP:-L6bwQmhZA6geVgWgo5B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a35fbee8d356c32fa77ed8331d685d9a9dc8e853/pkg/sql/opt/optgen/cmd/langgen/exprs_gen.go#L193)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

visitExprChildren -> visitChildren
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23266)*

**Pull request merged**
