### PR TITLE
sql: Repartition tables before dropping regions

### LINKED ISSUE #64223: sql: Internal error when querying a REGIONAL BY ROW table during DROP REGION
If users query REGIONAL BY ROW tables while a background DROP REGION statement is occurring (more specifically, is in the schema changer), they may observe this:

```
ERROR: internal error: Optimize can only be called on relational root expressions
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:775: optimizeRootWithProps()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:220: Optimize()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:525: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:194: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:940: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:821: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:659: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:122: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1527: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1529: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1450: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:484: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:626: func1()
runtime/asm_amd64.s:1374: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

The query then fails, but is likely to succeed if reissued.

This occurs because under the covers, the query detects the system in a partial state - the `crdb_internal_region` enum doesn't have the enum value present anymore, but the underlying RBR table hasn't yet been repartitioned.  

The fix for this problem is to ensure that queries can't find the system in this partial state.

### PR DESCRIPTION
**Pull request by ajstorm**
Previously we could get into a situation where on dropping a region,
concurrent queries on REGIONAL BY ROW tables could fail. This was due to
the fact that when resolving the partition tuple in the optimizer, we'd
encounter a partition without a corresponding enum value. This issue was
timing dependant, and would only be hit if the query had a leased type
descriptor from after the drop region, along with a table descriptor
from before the drop region.

To get around this problem, we introduce a new transaction to the drop
region schema changer which performs a pre-drop action of repartitioning
all REGIONAL BY ROW tables, and updating their leases. This ensures that
the table descriptors will be seen _before_ the modified type
descriptors.

Of note is the fact that this is only required on drop region. In the
add region case, having this mismatch occur and seeing an extra region
(with no corresponding partition) is not a problem for the query engine.

Release note (sql change): Fix a bug where queries on REGIONAL BY ROW tables
could fail in the brief window in which a DROP REGION operation is in
progress.

Resolves: #64223

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/type_change.go, line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZJJO9D2e8_QMMxHwzM:-MZJJO9D2e8_QMMxHwzN:boxb029) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/sql/type_change.go#L337)):*
> ```Go
> 		// enum portion, so that we ensure that any concurrent queries see the
> 		// descriptor updates in the correct order.
> 		if multiRegionPreDropIsNecessary {
> ```

Any reason to only repartition here if there is a `DROP REGION` operation? Or can we perform all multi-region repartitioning, regardless of op type (ADD/DROP), in one place?

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/type_change.go, line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZJJO9D2e8_QMMxHwzM:-MZJY9DZ4Mp0TR7DyrxW:b-lu844p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/sql/type_change.go#L337)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Any reason to only repartition here if there is a `DROP REGION` operation? Or can we perform all multi-region repartitioning, regardless of op type (ADD/DROP), in one place?
</blockquote></details>

I haven't validated this with a test, but my theory is that it won't work.  For starters, I'm not sure if our repartitioning will work on enum values which aren't in the public state yet (unless you're suggesting that we'd modify the descriptor, and then repartition first).  Secondly, and more importantly, if we repartition on ADD here, and publish the new table descriptors, we'll be in the same timing hole that we're fixing in the DROP region case (partition is present, but enum value isn't).  

This does bring about an interesting question though - do we need to force the publication of the type descriptors before the table descriptors in the ADD case (necessitating yet another transaction).  Will need to think on this some more (and maybe write another test case to validate this concern).

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/type_change.go, line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZJJO9D2e8_QMMxHwzM:-MZKKIey8x0E8CVUP2r0:b-8cum3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/sql/type_change.go#L337)):*
> For starters, I'm not sure if our repartitioning will work on enum values which aren't in the public state yet 

Oh yeah, you're right.  

> do we need to force the publication of the type descriptors before the table descriptors in the ADD case (necessitating yet another transaction). Will need to think on this some more (and maybe write another test case to validate this concern).

I don't think we need to because even if the type descriptor is of the older version, it will have the enum value being added in `READ_ONLY` mode. IIUC you can't create a partition for a READ_ONLY enum value, but it's fine if one exists. There's only a problem if the enum value is missing entirely. Still worth a test to validate though.

**Review by otan — COMMENTED** [review]
i'm a little sad that the lease can acquire a value after the first value that has been read, e.g. a read of table whose value was read at time 10 can hydrates types that were written at time 15. this seems broken to me, i wonder if this is really a schema issue....

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-:-MZKT3BECefgKBf7czLs:b-nz9f47)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/ccl/multiregionccl/region_test.go, line 1016 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKRwuA4JSSUXb0nTyO:-MZKRwuB2Sa_rlgobR6p:b-485apu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1016)):*
> ```Go
> 
> 				tempExternalIODir, tempDirCleanup := testutils.TempDir(t)
> 				defer (tempDirCleanup)()
> ```

nit: `defer tempDirCleanup()` is fine.
___
*[pkg/ccl/multiregionccl/region_test.go, line 1051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKSBgzAesEd72nqhMc:-MZKSBgzAesEd72nqhMd:b-4x6tq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1051)):*
> ```Go
> 				// our backup with the type change in progress. This wait
> 				// prevents the DROP DATABASE command below from dropping
> 				// the type descriptor while the alter cmd is in progress.
> ```

i think the alter cmd bit is a copypasta
___
*[pkg/ccl/multiregionccl/region_test.go, line 1056 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKSDkt-dmSKaCLhfgv:-MZKSDkt-dmSKaCLhfgw:b-op8ufl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1056)):*
> ```Go
> 				// FIXME: We shouldn't need this drop here, as we're using a
> 				//  different cluster.
> 				_, err = sqlDBBackup.Exec(`DROP DATABASE db`)
> ```

should this be a todo with issue?
what happens if we don't drop? does something exit uncleanly?
___
*[pkg/ccl/multiregionccl/region_test.go, line 1085 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKS_8J4CEzy8CXPHZX:-MZKS_8J4CEzy8CXPHZY:bgn6wt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1085)):*
> ```Go
> 				// Need SucceedsSoon here because the schema change job
> 				// occurring as part of the restore may not be done yet.
> 				testutils.SucceedsSoon(t, func() error {
> ```

can we succeedssoon the minimal possible section? i.e. wait til count is 3, then perform the rest:

```
				testutils.SucceedsSoon(t, func() error {
					numRows := sqlDBRestore.QueryRow(`SELECT count(*) from db.rbr`)
					if numRows.Err() != nil {
						return numRows.Err()
					}
					var count int
					err = numRows.Scan(&count)
					require.NoError(t, err)
					if count != 3 {
						return errors.Newf("unexpected number of rows after restore: expected 3, found %d", count)
					}
                                  })
                                  // validate partitions
```

this makes it a little more easier to debug in future, as we know for sure that e.g. the backup was already completed.
___
*[pkg/ccl/multiregionccl/region_test.go, line 1132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKRmIW5RnlYfh5y8ji:-MZKRmIW5RnlYfh5y8jj:bvww5f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1132)):*
> ```Go
> 					// Now validate the partitions on the REGIONAL BY ROW
> 					// tables.
> 					rowsPartitions, err := sqlDBRestore.Query(`
> ```

this bit feels similar to https://github.com/cockroachdb/cockroach/blob/29305bfb08116f38e10ca090347eea170899b919/pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go#L68, so we should re-use that.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/ccl/multiregionccl/region_test.go, line 1051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKSBgzAesEd72nqhMc:-MZKvk0wCPHx8QX5K_a3:bz3yhjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1051)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think the alter cmd bit is a copypasta
</blockquote></details>

I think it's still valid.  There is an alter command running here, and it could be impacted by a concurrent DROP DATABASE command.
___
*[pkg/ccl/multiregionccl/region_test.go, line 1056 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKSDkt-dmSKaCLhfgv:-MZKvz8g6qn-XI4ow5Ej:bl83c2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1056)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

should this be a todo with issue?
what happens if we don't drop? does something exit uncleanly?
</blockquote></details>

Sorry, forgot I still had this FIXME in here (it was a note to myself to address before I put out the PR).  It's gone now.

I also removed the DROP DATABASE call.  We shouldn't need it as at this point, we're done with the backup cluster, and we're moving onto the restore cluster.
___
*[pkg/ccl/multiregionccl/region_test.go, line 1085 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKS_8J4CEzy8CXPHZX:-MZKyB7-96QGuweFLJhS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1085)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we succeedssoon the minimal possible section? i.e. wait til count is 3, then perform the rest:

```
				testutils.SucceedsSoon(t, func() error {
					numRows := sqlDBRestore.QueryRow(`SELECT count(*) from db.rbr`)
					if numRows.Err() != nil {
						return numRows.Err()
					}
					var count int
					err = numRows.Scan(&count)
					require.NoError(t, err)
					if count != 3 {
						return errors.Newf("unexpected number of rows after restore: expected 3, found %d", count)
					}
                                  })
                                  // validate partitions
```

this makes it a little more easier to debug in future, as we know for sure that e.g. the backup was already completed.
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/region_test.go, line 1132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKRmIW5RnlYfh5y8ji:-MZKyCaF2WXT2jFIvi8x:b-5ozkje) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1132)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this bit feels similar to https://github.com/cockroachdb/cockroach/blob/29305bfb08116f38e10ca090347eea170899b919/pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go#L68, so we should re-use that.
</blockquote></details>

Yeah, good call.  That didn't exist when I started writing this test case but I noticed it in a review and planned to use it eventually.  It's there now.
___
*[pkg/sql/type_change.go, line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZJJO9D2e8_QMMxHwzM:-MZL1pRTAMv_mC-gzdo0:bfnp70w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/sql/type_change.go#L337)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> For starters, I'm not sure if our repartitioning will work on enum values which aren't in the public state yet 

Oh yeah, you're right.  

> do we need to force the publication of the type descriptors before the table descriptors in the ADD case (necessitating yet another transaction). Will need to think on this some more (and maybe write another test case to validate this concern).

I don't think we need to because even if the type descriptor is of the older version, it will have the enum value being added in `READ_ONLY` mode. IIUC you can't create a partition for a READ_ONLY enum value, but it's fine if one exists. There's only a problem if the enum value is missing entirely. Still worth a test to validate though. 
</blockquote></details>

Right, I think it's good.  I'll add a test to validate in a subsequent PR.

**Comment by otan** [comment]
> This issue was
timing dependant, and would only be hit if the query had a leased type
descriptor from after the drop region, along with a table descriptor
from before the drop region.

i'm still a little hung up on the whether this is true.
it makes everything very hard to reason about if you can read a type descriptor from a timestamp that is after the time you read the table descriptor timestamp.
ideally they are read as of the same timestamp...

**Comment by ajstorm** [comment]
If I'm interpreting the logs correctly, it seems to be happening:

```
I210428 12:31:54.730948 64123 jobs/registry.go:1175  [n1] 14016  TYPEDESC SCHEMA CHANGE job 653861567265669121: stepping through state running with error: <nil>
I210428 12:31:54.792201 64123 sql/schema_changer.go:1009  [n1,job=653861567265669121] 14022  waiting for a single version...
I210428 12:31:54.829758 64123 sql/schema_changer.go:1011  [n1,job=653861567265669121] 14023  waiting for a single version... done (at v 2)
I210428 12:31:54.829828 64123 sql/schema_changer.go:1009  [n1,job=653861567265669121] 14024  waiting for a single version...
I210428 12:31:54.864228 64123 sql/schema_changer.go:1011  [n1,job=653861567265669121] 14025  waiting for a single version... done (at v 2)
I210428 12:31:54.954645 64123 sql/schema_changer.go:1009  [n1,job=653861567265669121] 14026  waiting for a single version...
I210428 12:31:54.959402 64834 sql/catalog/lease/lease.go:800  [n1] 14027  new lease: 55("rbr") ver=3:1619613424.897723440,0, refcount=0
I210428 12:31:54.968693 64123 sql/catalog/lease/lease.go:350  [n1,job=653861567265669121] 14028  waiting for 1 leases to expire: desc=[{rbr 55 2}]
I210428 12:31:54.991419 64123 sql/schema_changer.go:1011  [n1,job=653861567265669121] 14029  waiting for a single version... done (at v 3)
I210428 12:31:55.210363 64123 sql/schema_changer.go:1009  [n1,job=653861567265669121] 14030  waiting for a single version...
I210428 12:31:55.221645 65627 sql/catalog/lease/lease.go:800  [n1] 14031  new lease: 53("crdb_internal_region") ver=3:1619613408.391468905,0, refcount=0      <- New lease granted on the crdb_internal_region type
I210428 12:31:55.222228 64123 sql/catalog/lease/lease.go:350  [n1,job=653861567265669121] 14032  waiting for 1 leases to expire: desc=[{rbr 55 3}]            <- Still waiting on one lease to expire on the rbr table
I210428 12:31:55.227840 65730 sql/catalog/lease/lease.go:800  [n1] 14033  new lease: 54("_crdb_internal_region") ver=3:1619613409.378292821,0, refcount=0
I210428 12:31:55.232065 65367 sql/catalog/lease/lease.go:800  [n1] 14034  new lease: 55("rbr") ver=4:1619613424.898723440,0, refcount=0
```

**Review by arulajmani — COMMENTED** [review]
> it makes everything very hard to reason about if you can read a type descriptor from a timestamp that is after the time you read the table descriptor timestamp.
> ideally they are read as of the same timestamp...

I guess the idea is that at any point both versions of the type descriptor, old and new, should be compatible with the table descriptor using it? This change looks good to me, though I think it would be worth getting @ajwerner 's take on the approach. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-:-MZNqINv4UwisqQGDxXV:b-5avfmp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

**Comment by ajstorm** [comment]
Thanks @arulajmani.  I agree with your point about @ajwerner.  I've added him as a reviewer.  Andrew, please let me know if our findings here make sense to you, and whether or not the approach taken makes sense.

**Review by ajwerner — COMMENTED** [review]
This all makes sense to me. 

> it makes everything very hard to reason about if you can read a type descriptor from a timestamp that is after the time you read the table descriptor timestamp.

I don't disagree but that's not what the infrastructure gives you. How would we possibly know that there was a later version of the table descriptor corresponding to that version of the type descriptor? That level of coupling seems scary. It's definitely painful to have to think about the making the two-version invariant and all of the various possible interleavings of descriptor versions. However, I'm not sure of an alternative given the desire to support online schema changes. Potentially you could try serializing version requirements for all descriptors modified at the same time or something and then have the newer type tell you about the need to go get the new table but that seems very hard to get right. 

In the new world, we'll have better ways to talk about dependencies between things. In particular, here, I think we're saying that we need to make sure all uses of an enum value need to be fully scrubbed from expressions before the enum value is dropped. The new world doesn't make it easier to understand what dependencies need to exist (I'm still searching for formalisms to help guide that problem), but at least it pulls the concepts to the fore. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-:-MZNycP963iSmByNhAqH:b-lno7np)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/ccl/multiregionccl/region_test.go, line 1085 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKS_8J4CEzy8CXPHZX:-MZNy3CB5hClgnsDl7-w:b-puo1dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1085)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The `SucceedsSoon` still seems very large.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/ccl/multiregionccl/region_test.go, line 1085 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZKS_8J4CEzy8CXPHZX:-MZO5S5A9U4SVV9skTNS:b6vu75r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e8c5f07cce146d5e7da8154ca90b45af32b2b4/pkg/ccl/multiregionccl/region_test.go#L1085)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The `SucceedsSoon` still seems very large.
</blockquote></details>

I thought I needed all of it in one block, but I was wrong.  I've trimmed it down, and split it into a couple of smaller `SucceedsSoon`s, and pulled a piece out completely.

**Review by ajwerner — COMMENTED** [review]
FYI Stumbled upon this discussion from a while ago which has a similar flavor. https://github.com/cockroachdb/cockroach/issues/44007#issuecomment-574781110 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-:-MZOtF_NA81IAOMrm5vZ:bnmcgk9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

**Comment by ajstorm** [comment]
> This isn't really a problem right now

Rohan was a prophet.  I can confirm that this *is* a problem now :-D

**Review by arulajmani — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-:-MZPKALP65jp-7klvDgq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/database_region_change_finalizer.go, line 130 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZPJoja2CVCJRhTTgh-:-MZPJoja2CVCJRhTTgh0:b-cqha96) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c671897f8d27e3d21b080f391f5a4b0cd67a71/pkg/sql/database_region_change_finalizer.go#L130)):*
> ```Go
> // descriptors never become incorrect (from a query perspective). For more info,
> // see the caller.
> func (r *databaseRegionChangeFinalizer) preDrop(ctx context.Context, txn *kv.Txn) error {
> ```

nit: maybe rename this `preTypeDescriptorChangeFinalization` and `finalize` above `postTypeDescriptorChangeFinalization`? 
___
*[pkg/sql/type_change.go, line 336 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZPKSN40nl5penHy8PU:-MZPKSN40nl5penHy8PV:bpm594j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c671897f8d27e3d21b080f391f5a4b0cd67a71/pkg/sql/type_change.go#L336)):*
> ```Go
> 		// we must refresh the table descriptors before we proceed to the drop
> 		// enum portion, so that we ensure that any concurrent queries see the
> 		// descriptor updates in the correct order.
> ```

Is it worth adding some words here (or maybe on `preDrop` actually) about why we don't care about this case in the `OnFailOrCancelPath`? In particular, something like because we failed adding a region we are guaranteed that no partition for that region exists. This is because that region was never public and we can only partition on public enum values. So this problem can't exist there. I say because I just asked myself this while reviewing :P

**Review by ajstorm — COMMENTED** [review]
Thanks everyone for the reviews.  

bors r=arulajmani,otan,ajwerner

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-:-MZSuA3_4JiLKlFX-nxn:b-7y90c1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/type_change.go, line 336 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64273#-MZPKSN40nl5penHy8PU:-MZSu36Z0aTrlGnpYtTb:b3dw09h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c671897f8d27e3d21b080f391f5a4b0cd67a71/pkg/sql/type_change.go#L336)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is it worth adding some words here (or maybe on `preDrop` actually) about why we don't care about this case in the `OnFailOrCancelPath`? In particular, something like because we failed adding a region we are guaranteed that no partition for that region exists. This is because that region was never public and we can only partition on public enum values. So this problem can't exist there. I say because I just asked myself this while reviewing :P 
</blockquote></details>

Good idea.  I added a note and also paragraphed this long comment.

**Comment by ajstorm** [comment]
Closes #64273

**Pull request merged**
