### PR TITLE
distsql: update range caches in response to metadata 

### PR DESCRIPTION
**Pull request by andreimatei**
Queries running through DistSQL bypass the DistSender (on the gateway
node), which is responsible for keeping the RangeDescriptorCache and
LeaseHolderCache up to date. Instead, DistSQL reports information about
bad decisions done by the physical planner inline with the query
results, as metadata. Such bad decisions are indicative of stale or
missing cache entries.
This patch closes the loop and uses this metadata to update the said
caches.

cc @RaduBerinde

### CODE REVIEW

**Comment by andreimatei** [comment]
I'm going to write an integration test for the effects of these cache updates, but I wanted to get a review on the mechanics.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-:-KhZ_QqGdfDcBTnAciVC:b3sqc9d)*

**Comment by bdarnell** [comment]
Reviewed 4 of 7 files at r1, 3 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/kv/range_cache.go, line 545 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_QF8PkUAGIQyD-6Vr:-Kh_QF8QMzX52ZmtBStr:bcgdenx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d69f1ec3933b44129f067a84a968adaf7a222da/pkg/kv/range_cache.go#L545)):*
> ```Go
> }
> 
> // insertRangeDescriptorsLocks is like InsertRangeDescriptors, but it assumes
> ```

s/Locks/Locked/

---

*[pkg/kv/range_cache.go, line 559 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_UQpZvkQUfWCjsKj7:-Kh_UQpZvkQUfWCjsKj8:b-ox7ifw) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b0344e217542894f34aaa8df98092c3f7229d7/pkg/kv/range_cache.go#L559)):*
> ```Go
> 		// re-inserted due to concurrent range lookups.
> 		notPresent, err := rdc.clearOverlappingCachedRangeDescriptors(ctx, &rs[i])
> 		if err != nil || !notPresent {
> ```

The multiple negations here are confusing. 

---

*[pkg/kv/range_iter.go, line 87 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_Q7GtL-SGS8vnT6IE:-Kh_Q7GuskLSH85Ty0na:b-cx29f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d69f1ec3933b44129f067a84a968adaf7a222da/pkg/kv/range_iter.go#L87)):*
> ```Go
> 	// TODO(andrei): The leaseHolderCache might have a replica that's not part of
> 	// the RangeDescriptor that the iterator is currently positioned on. IOW, the
> 	// leaseHolderCache can be inconsistent with the RangerDescriptor cache, and
> ```

s/Ranger/Range/

---

*[pkg/kv/range_iter.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_Q9Y8qd4AkiIj-Oxv:-Kh_Q9Y93sssNa8n0tSY:bxqif9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d69f1ec3933b44129f067a84a968adaf7a222da/pkg/kv/range_iter.go#L88)):*
> ```Go
> 	// the RangeDescriptor that the iterator is currently positioned on. IOW, the
> 	// leaseHolderCache can be inconsistent with the RangerDescriptor cache, and
> 	// with reality. We should attempt to fix-up caches when this is encoutered.
> ```

s/encoutered/encountered/

---

*[pkg/roachpb/metadata.go, line 176 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_TkfQLmi0jBRrxbDp:-Kh_TkfRQhMnOX5ukBPG:b-z8c5qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b0344e217542894f34aaa8df98092c3f7229d7/pkg/roachpb/metadata.go#L176)):*
> ```Go
> 
> // Equal tests whether two RangeDescriptor have all the fields equal.
> func (r RangeDescriptor) Equal(other RangeDescriptor) bool {
> ```

This looks prone to rot. Unless we can generate it, use `reflect.DeepEqual` unless and until it shows up in profiles. 

---

*[pkg/sql/executor.go, line 225 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_UistrmidnWiAlSCT:-Kh_UisupyTrHc1x37g6:bvmgcuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5c108329fccf22f5c7e04f0ecdf4cef18f6c2e1/pkg/sql/executor.go#L225)):*
> ```Go
> 	HistogramWindowInterval time.Duration
> 
> 	// Cache that are updated by DistSQL.
> ```

s/Cache/Caches/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871)*

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/kv/leaseholder_cache.go, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhboKnXaA6Mx99pqxDJ:-KhboKnXaA6Mx99pqxDK:b-f35ftc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d69f1ec3933b44129f067a84a968adaf7a222da/pkg/kv/leaseholder_cache.go#L37)):*
> ```Go
> // The underlying cache internally uses a hash map, so lookups
> // are cheap.
> func NewLeaseHolderCache(size int) *LeaseHolderCache {
> ```

does this constructor need to be exported?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/kv/leaseholder_cache.go, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhboKnXaA6Mx99pqxDJ:-KhbsmkJ6zskt59F8rB6:bcu9928) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d69f1ec3933b44129f067a84a968adaf7a222da/pkg/kv/leaseholder_cache.go#L37)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

does this constructor need to be exported?
</blockquote></details>

Ah, it does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871)*

**Comment by RaduBerinde** [comment]
Nice, excited to have this in place!

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/kv/range_cache.go, line 575 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhbrtC1i8R2JQVkUxyX:-KhbrtC2swr2L6AjeSe-:bh9yf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b0344e217542894f34aaa8df98092c3f7229d7/pkg/kv/range_cache.go#L575)):*
> ```Go
> 
> // clearOverlappingCachedRangeDescriptors looks up and clears any
> // cache entries which overlap the specified descriptor.
> ```

, unless the descriptor is already in the cache.

---

*[pkg/roachpb/metadata.go, line 176 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_TkfQLmi0jBRrxbDp:-Khbs9F3H-FgP5q2UkO-:b9yrq19) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b0344e217542894f34aaa8df98092c3f7229d7/pkg/roachpb/metadata.go#L176)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This looks prone to rot. Unless we can generate it, use `reflect.DeepEqual` unless and until it shows up in profiles. 
</blockquote></details>

The check could be
`if descriptor.StartKey.Equals(desc.StartKey) && descriptor.EndKey.Equals(desc.EndKey) && reflect.DeepEqual(descriptor, desc)`, to avoid the expensive call when the keys don't match.

---

*[pkg/sql/distsql_physical_planner.go, line 1611 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhbvHHCRPCepLXnaTgy:-KhbvHHD4NH86PFezE9a:bllr9zt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5c108329fccf22f5c7e04f0ecdf4cef18f6c2e1/pkg/sql/distsql_physical_planner.go#L1611)):*
> ```Go
> // updates the range descriptor and lease-holder caches accordingly.
> //
> // TODO(andrei): updating these caches is not perfect: we can clobber newer
> ```

An option here is to just evict overlapping ranges instead of populating. But I think with either approach the cache should get correct info in at most a couple queries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-:-Khbvu2CA3sh32EA-0tu:bz70kki)*

**Comment by andreimatei** [comment]
Review status: 3 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/kv/range_cache.go, line 545 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_QF8PkUAGIQyD-6Vr:-KhbutkNsVV-UJ8Dy3fV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d69f1ec3933b44129f067a84a968adaf7a222da/pkg/kv/range_cache.go#L545)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/Locks/Locked/
</blockquote></details>

Done.

---

*[pkg/kv/range_cache.go, line 559 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_UQpZvkQUfWCjsKj7:-KhbvbAiTPXKJrG-RRoR:b-svnb58) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b0344e217542894f34aaa8df98092c3f7229d7/pkg/kv/range_cache.go#L559)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The multiple negations here are confusing. 
</blockquote></details>

yes, but I also don't like inverting the return value in `clearOverlappingCachedRanges`. I've renamed the result `continueWithInsert`.

---

*[pkg/kv/range_cache.go, line 575 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhbrtC1i8R2JQVkUxyX:-KhdUwvC4R-p9BV3GGkg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b0344e217542894f34aaa8df98092c3f7229d7/pkg/kv/range_cache.go#L575)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

, unless the descriptor is already in the cache.
</blockquote></details>

Done.

---

*[pkg/kv/range_iter.go, line 87 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_Q7GtL-SGS8vnT6IE:-Khbv3YjSwrPdnrUe40b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d69f1ec3933b44129f067a84a968adaf7a222da/pkg/kv/range_iter.go#L87)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/Ranger/Range/
</blockquote></details>

Done.

---

*[pkg/kv/range_iter.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_Q9Y8qd4AkiIj-Oxv:-KhbvDaZyXYE58ka__RO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d69f1ec3933b44129f067a84a968adaf7a222da/pkg/kv/range_iter.go#L88)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/encoutered/encountered/
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 225 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_UistrmidnWiAlSCT:-KhcM25CFRu9zFDtYj3D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5c108329fccf22f5c7e04f0ecdf4cef18f6c2e1/pkg/sql/executor.go#L225)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/Cache/Caches/
</blockquote></details>

Done.

---

*[pkg/roachpb/metadata.go, line 176 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-Kh_TkfQLmi0jBRrxbDp:-KhbyU_ghNMRzIUxtwUc:b4fyozs) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b0344e217542894f34aaa8df98092c3f7229d7/pkg/roachpb/metadata.go#L176)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The check could be
`if descriptor.StartKey.Equals(desc.StartKey) && descriptor.EndKey.Equals(desc.EndKey) && reflect.DeepEqual(descriptor, desc)`, to avoid the expensive call when the keys don't match.
</blockquote></details>

The story here is that first I tried to use `proto.Equal`; that panicked because it doesn't like that we alias a `[]bytes` through a gogo extension.
Then I tried to use the gogo `equals` plugin, which generates code, but that caused a bad import line. I filed a bug and the plan was to switch to that once the bug is resolved. In the meantime; the wrong import situation has been cleared - see changes in `protobuf.mk`. So switched to that.

---

*[pkg/sql/distsql_physical_planner.go, line 1611 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhbvHHCRPCepLXnaTgy:-KhcLBp-ljY7qkQznGVz:bybp8d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5c108329fccf22f5c7e04f0ecdf4cef18f6c2e1/pkg/sql/distsql_physical_planner.go#L1611)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

An option here is to just evict overlapping ranges instead of populating. But I think with either approach the cache should get correct info in at most a couple queries.
</blockquote></details>

I think populating is generally a good thing - we have pretty high confidence in the descriptors we got from running a query, since they come from a recent leaseholder.
The answer, I think, is to put some timestamps in the caches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871)*

**Comment by andreimatei** [comment]
Added a test.

---

Review status: 3 of 14 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-:-KhdWy-Dw_6ilQ6zenvg:b-7gclag)*

**Comment by RaduBerinde** [comment]
Tests LGTM.

Really cool how the metadata flow came out btw. :thumbsup:

---

Review status: 3 of 14 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner_test.go, line 270 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhgwImqmx0fVFNHQ6dg:-KhgwImqmx0fVFNHQ6dh:bdngrpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e8ca739a507455c53c02f9e85aad3af8a6025f/pkg/sql/distsql_physical_planner_test.go#L270)):*
> ```Go
> 	}
> 
> 	// Assert that the caches start empty and the initial planning is bad. Only
> ```

I misunderstood a bit what is going on (mostly due to the comment below, I thought that if something is missing from the cache, it returns everything on the gatewary) , a bit more clear would be "The cache on node 3 is unaware of the splits and still holds the initial state after cluster setup, which has everything on the first node."

---

*[pkg/sql/distsql_physical_planner_test.go, line 285 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhgwEuADss3uj07KJok:-KhgwEuADss3uj07KJol:bp433t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e8ca739a507455c53c02f9e85aad3af8a6025f/pkg/sql/distsql_physical_planner_test.go#L285)):*
> ```Go
> 
> 	// Run a non-trivial query to force the "wrong range" metadata to flow through
> 	// a number of components. Assert that this initial planning is suboptimal -
> ```

The "Assert that" sentence is out of place and confusing, should remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-:-Khgx4CFfm5jmaQfNQLt:b-5ijs6d)*

**Comment by andreimatei** [comment]
Review status: 3 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner_test.go, line 270 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhgwImqmx0fVFNHQ6dg:-KhhcfdEcvoq74AT7CwH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e8ca739a507455c53c02f9e85aad3af8a6025f/pkg/sql/distsql_physical_planner_test.go#L270)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I misunderstood a bit what is going on (mostly due to the comment below, I thought that if something is missing from the cache, it returns everything on the gatewary) , a bit more clear would be "The cache on node 3 is unaware of the splits and still holds the initial state after cluster setup, which has everything on the first node."
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner_test.go, line 285 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhgwEuADss3uj07KJok:-Khhckr2hAFj4Yr8Yquc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e8ca739a507455c53c02f9e85aad3af8a6025f/pkg/sql/distsql_physical_planner_test.go#L285)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The "Assert that" sentence is out of place and confusing, should remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsql_physical_planner_test.go, line 270 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhgwImqmx0fVFNHQ6dg:-KhikdpfQHHeWtrFC_EJ:bsnlina) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e8ca739a507455c53c02f9e85aad3af8a6025f/pkg/sql/distsql_physical_planner_test.go#L270)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No longer correct :) (the "initial state" part, now we expect the cache to be populated from the initial query you added).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871)*

**Comment by bdarnell** [comment]
:lgtm: for KV and roachpb parts.

---

Reviewed 1 of 9 files at r4, 5 of 5 files at r11, 5 of 5 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-:-KhrvPbtRXExKR3lI7Bs:b-d5f4mt)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner_test.go, line 270 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871#-KhgwImqmx0fVFNHQ6dg:-KhizxQqXxGYunhI7eio:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e8ca739a507455c53c02f9e85aad3af8a6025f/pkg/sql/distsql_physical_planner_test.go#L270)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

No longer correct :) (the "initial state" part, now we expect the cache to be populated from the initial query you added).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14871)*

**Pull request merged**
