### PR TITLE
scripts: allow GCEWORKER_USER env to override ssh user

### LINKED ISSUE #63641: scripts: allow user override in gceworker.sh
Setting USER env var doesn't work on mac OSX  (I suspect it would on linux but I didn't test it).    I changed my login user name after setting up my gceworker and needed this functionality to get back into the correct home directory.

### PR DESCRIPTION
**Pull request by cucaroach**
fixes #63641

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63645)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[scripts/gceworker.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63645#-MYGpBqo9vvmI0fYUw8M:-MYGpBqo9vvmI0fYUw8N:b2wot9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/658fe6e80b878facac1cc4f832a903b48244109e/scripts/gceworker.sh#L11)):*
> ```Shell
> export CLOUDSDK_COMPUTE_ZONE=${GCEWORKER_ZONE-${CLOUDSDK_COMPUTE_ZONE-us-east1-b}}
> INSTANCE=${GCEWORKER_NAME-gceworker-$(id -un)}
> USER=${GCEWORKER_USER:-""}
> ```

should the default be `$(id - un)`? Or does empty `USER` work fine below (`${USER}@${INSTANCE}`)?

**Comment by cucaroach** [comment]
___
*[scripts/gceworker.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63645#-MYGpBqo9vvmI0fYUw8M:-MYGpcs22fZDSD9X2mYO:b-owyykp) ([raw file](https://github.com/cockroachdb/cockroach/blob/658fe6e80b878facac1cc4f832a903b48244109e/scripts/gceworker.sh#L11)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

should the default be `$(id - un)`? Or does empty `USER` work fine below (`${USER}@${INSTANCE}`)?
</blockquote></details>

I thought about it but I didn't want to rock the boat in case id -un differs from what blank gives you, in particular I suspect on linux you can just set USER=blak and gcloud will pick that up and use it.   I tested that specifying @instance with no user name works.   Come to think of it I should probably not use USER as my variable name so that USER=blak gceworker.sh can work.   I'll rename it to SSH_USER.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63645)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[scripts/gceworker.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63645#-MYGpBqo9vvmI0fYUw8M:-MYGwM5n2VZR18EJMHgk:b7nlvbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/658fe6e80b878facac1cc4f832a903b48244109e/scripts/gceworker.sh#L11)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

I thought about it but I didn't want to rock the boat in case id -un differs from what blank gives you, in particular I suspect on linux you can just set USER=blak and gcloud will pick that up and use it.   I tested that specifying @instance with no user name works.   Come to think of it I should probably not use USER as my variable name so that USER=blak gceworker.sh can work.   I'll rename it to SSH_USER.
</blockquote></details>

But then if you want USER to work, don't you want the default value to be `$USER` and not `""` ?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63645)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[scripts/gceworker.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63645#-MYGpBqo9vvmI0fYUw8M:-MYGwcZRA3dFD4_hEO6w:b-q6udsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/658fe6e80b878facac1cc4f832a903b48244109e/scripts/gceworker.sh#L11)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

But then if you want USER to work, don't you want the default value to be `$USER` and not `""` ?
</blockquote></details>

Oh, sorry, now I understand. If we pass in the empty one, gcloud would use `$USER` anyway. Still, may be less subtle if we just do that ourselves.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63645#-:-MYGwloT6rgesAxlaCK0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Comment by cucaroach** [comment]
___
*[scripts/gceworker.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63645#-MYGpBqo9vvmI0fYUw8M:-MYGzEPn3roPePHegSt2:b-oxxt6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/658fe6e80b878facac1cc4f832a903b48244109e/scripts/gceworker.sh#L11)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh, sorry, now I understand. If we pass in the empty one, gcloud would use `$USER` anyway. Still, may be less subtle if we just do that ourselves.
</blockquote></details>

Exactly, I didn't want to trump whatever gcloud/ssh are doing by default.

**Comment by cucaroach** [comment]
bors r=RaduBerinde

**Pull request merged**
