### PR TITLE
colexec,execinfrapb: preliminary changes for default aggregate function

### PR DESCRIPTION
**Pull request by yuzefovich**
**execinfrapb: move ExprHelper and introduce a helper method**

This commit moves `execinfra.ExprHelper` into `execinfrapb` package and
adds a helper method that processes the specification of a single
serialized aggregate function (the method will be used by both `rowexec`
and `colexec`). It also does a few minor changes.

Release note: None

**colexec: extend vecToDatumConverter to not perform deselection step**

`vecToDatumConverter` only had support for "dense" conversion when
selection vector is present on the batch (meaning it would populate
`converted` columns with only selected values). This, however, is
insufficient for the hash aggregator use case because that operator
applies a selection vector-"lense" on top of already present vector. In
order to support that use case, this commit extends the converter to
support "sparse" conversion as well.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
This was extracted from #52174. Please take a look at this sooner rather than later because several PRs depend on this.

**Comment by yuzefovich** [comment]
@asubiotto this is the PR that I'd like to take a look first.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52315)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 108 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-ME7Eqy97QFu5ejpz7xi:-ME7Eqy97QFu5ejpz7xj:b-p0653e) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb8b264b07fe648dc32bb4a54aa9a93f21080174/pkg/sql/colexec/hash_aggregator.go#L108)):*
> ```Go
> // TODO(yuzefovich): remove this once it is used by the hash aggregator.
> var c vecToDatumConverter
> var _ = c.convertBatchSparsely
> ```

take it or leave it: vecToDatumConverter{}.convertBatchSparsely
___
*[pkg/sql/colexec/vec_to_datum_tmpl.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-ME7F6H93ml0qGwEHr4k:-ME7F6H93ml0qGwEHr4l:b-4ypfup) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb8b264b07fe648dc32bb4a54aa9a93f21080174/pkg/sql/colexec/vec_to_datum_tmpl.go#L62)):*
> ```Go
> }
> 
> // convertBatchDensely converts the selected vectors from the batch while
> ```

Is dense/sparse the correct terminology for this? `convertBatchAndDeselect` makes more sense to me.
___
*[pkg/sql/execinfrapb/processors.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-ME79TGn24lwCo4Ls9Si:-ME79TGo4S-CWi36ZM4Y:b-i1g2u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab51796dc6bd54297e4bd195cc4e52981232f4/pkg/sql/execinfrapb/processors.go#L105)):*
> ```Go
> }
> 
> // ProcessAggFnSpec processes the specification of a single aggregate function.
> ```

I think `Process` is ambiguous, what is actually happening?  Maybe `GetAggregateConstructor` or something similar?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52315)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/hash_aggregator.go, line 108 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-ME7Eqy97QFu5ejpz7xi:-MEO5suP98hclZ72wOmu:bfnboow) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb8b264b07fe648dc32bb4a54aa9a93f21080174/pkg/sql/colexec/hash_aggregator.go#L108)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

take it or leave it: vecToDatumConverter{}.convertBatchSparsely
</blockquote></details>

The compiler complains because `convertBatchSparsely` has a pointer receiver.
___
*[pkg/sql/colexec/vec_to_datum_tmpl.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-ME7F6H93ml0qGwEHr4k:-MEO7jjk6boH82KwIm1a:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb8b264b07fe648dc32bb4a54aa9a93f21080174/pkg/sql/colexec/vec_to_datum_tmpl.go#L62)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is dense/sparse the correct terminology for this? `convertBatchAndDeselect` makes more sense to me.
</blockquote></details>

Good point, done.
___
*[pkg/sql/execinfrapb/processors.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-ME79TGn24lwCo4Ls9Si:-MEO6yjW6h9VWE5YoRdI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ab51796dc6bd54297e4bd195cc4e52981232f4/pkg/sql/execinfrapb/processors.go#L105)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think `Process` is ambiguous, what is actually happening?  Maybe `GetAggregateConstructor` or something similar?
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 13 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-:-MESfVt29h-KIOjQTfm5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 108 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-MESdR_C268SR3g9DY6o:-MESdR_C268SR3g9DY6p:b-bvtx55) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8195288a8eb072224154dbbda115f87c9c30b53/pkg/sql/colexec/hash_aggregator.go#L108)):*
> ```Go
> // TODO(yuzefovich): remove this once it is used by the hash aggregator.
> var c vecToDatumConverter
> var _ = c.convertBatch
> ```

Oh, if it's a pointer receiver `(&vecToDatumConverter{}).convertBatch` should work
___
*[pkg/sql/colexec/vec_to_datum_tmpl.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-MESdhny7KshhQUPVhkU:-MESdhny7KshhQUPVhkV:b396jx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8195288a8eb072224154dbbda115f87c9c30b53/pkg/sql/colexec/vec_to_datum_tmpl.go#L64)):*
> ```Go
> // convertBatchAndDeselect converts the selected vectors from the batch while
> // performing a deselection step.
> // NOTE: converted columns are "dense" in regards to the selection vector - if
> ```

nit: do you want to keep "dense" here and "sparse" below?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-:-MET3ahZEyNO7KeHaeBx:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/hash_aggregator.go, line 108 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-MESdR_C268SR3g9DY6o:-MET2uNS0aBCwnZnqxYF:bqtiucs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8195288a8eb072224154dbbda115f87c9c30b53/pkg/sql/colexec/hash_aggregator.go#L108)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Oh, if it's a pointer receiver `(&vecToDatumConverter{}).convertBatch` should work
</blockquote></details>

Yeah, I was missing parenthesis.
___
*[pkg/sql/colexec/vec_to_datum_tmpl.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52315#-MESdhny7KshhQUPVhkU:-MET2HtrApem6G1crYrY:b-mvgkk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8195288a8eb072224154dbbda115f87c9c30b53/pkg/sql/colexec/vec_to_datum_tmpl.go#L64)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: do you want to keep "dense" here and "sparse" below?
</blockquote></details>

I find the terminology helpful, so I'll keep it.

**Comment by otan** [comment]
did this crash bors?

**Comment by yuzefovich** [comment]
Looks like it, probably because I bors'ed it before CI was green.

bors r+

**Comment by otan** [comment]
i think this crashed bors?

**Comment by otan** [comment]
strange, i think in the process it cancelled my PR :|

**Pull request merged**
