### PR TITLE
Makefile: update "make help" text for specifying files to test

### PR DESCRIPTION
**Pull request by shaqq**
Just to add a little specificity to help the next poor dev.

Screenshot of how it looks on my terminal:

image

Release justification: non-production change

### CODE REVIEW

**Comment by irfansharif** [comment]
Thanks for sending it in! This LGTM, but I prefer the previous, shorter file names, if you don't mind amending that change back.

**Comment by shaqq** [comment]
@irfansharif done!

**Comment by jordanlewis** [comment]
Looks great! Please squash your two commits together and we'll merge. We don't accept PRs with big chains of WIP commits - we like them all bundled up into either a single commit or multiple "atomic commits" that could stand on their own.

**Comment by shaqq** [comment]
@jordanlewis updated to a single commit. i've been spoiled by github's "squash & merge" 😄

**Comment by jordanlewis** [comment]
Thanks!

bors r+

**Comment by irfansharif** [comment]
Jordan, I think it's missing a release justification.

**Comment by SWDevAngel** [comment]
@shaqq Hi Shaker. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)

**Pull request merged**
