### PR TITLE
Statically allocate IDs for all system tables.

### PR DESCRIPTION
**Pull request by petermattis**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3778)

### CODE REVIEW

**Comment by tamird** [comment]
needs a rebase

**Comment by petermattis** [comment]
Rebased.

**Comment by petermattis** [comment]
Rebased (again).

**Comment by tamird** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[keys/constants.go, line 210 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3778#-K7rwZSv0SLhukMcOn06:-K7rwZSwkN6t6-PlD1lj:-580397457) ([raw file](https://github.com/cockroachdb/cockroach/blob/10b381ad1649e946674113a693a2415ada6d6bb6/keys/constants.go#L210)):*
s/IDS/IDs/

---

*[sql/metadata.go, line 58 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3778#-K7rwy_8A-n9lJqCJxbN:-K7rwy_9VR827Ci-7fvR:1936706143) ([raw file](https://github.com/cockroachdb/cockroach/blob/10b381ad1649e946674113a693a2415ada6d6bb6/sql/metadata.go#L58)):*
> system descriptors have well-known, static descriptors

what?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3778)*

**Comment by petermattis** [comment]
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[keys/constants.go, line 210 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3778#-K7rwZSv0SLhukMcOn06:-K7s7tWOMRv64i_VE_Ss:-141845836) ([raw file](https://github.com/cockroachdb/cockroach/blob/10b381ad1649e946674113a693a2415ada6d6bb6/keys/constants.go#L210)):*
Done. My fingers keep doing that.

---

*[sql/metadata.go, line 58 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3778#-K7rwy_8A-n9lJqCJxbN:-K7s8tNbqcQMgL48kuQO:-99473789) ([raw file](https://github.com/cockroachdb/cockroach/blob/10b381ad1649e946674113a693a2415ada6d6bb6/sql/metadata.go#L58)):*
I reworked this entire comment. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3778)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3778)*

**Comment by petermattis** [comment]
Was that an LGTM? The "all files reviewed at latest revision, all discussions resolved" review status doesn't quite mean the same thing to me.

**Comment by tamird** [comment]
Yep, LGTM

**Comment by mrtracy** [comment]
LGTM

**Pull request merged**
