### PR TITLE
sql/schemachanger/scbuild: make builder tests more compact

### PR DESCRIPTION
**Pull request by ajwerner**
Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
New formatting is much cleaner, just one minor nit commnet.

> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84271#-:-N6n2fcr0DllWyZuTX_u:bucg5ty)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/builder_test.go` line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84271#-N6n219b8UpIEFou9WYD:-N6n219b8UpIEFou9WYE:b-vxj62t) ([raw file](https://github.com/cockroachdb/cockroach/blob/056b087dd64f77d67459010a44eb97bda7f30e71/pkg/sql/schemachanger/scbuild/builder_test.go#L242)):*
> ```Go
> 	var n yaml.Node
> 	require.NoError(t, dec.Decode(&n))
> 	walkYaml(&n, func(node *yaml.Node) { node.Style = yaml.FlowStyle })
> ```

Why not combine both of the calls above and below together?

**Comment by ajwerner** [comment]
I reworked this so we can get rid of the embedded layering everywhere.

**Comment by ajwerner** [comment]
This actually addresses https://github.com/cockroachdb/cockroach/issues/77155.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
