### PR TITLE
Licensing section added to README.md

### PR DESCRIPTION
**Pull request by cargillb**
The licensing information is available but not easily found from the root directory.

As someone trying to familiarize myself with cockroachDB, I wanted to understand the licensing in
use. I think that by adding a brief summary as well as links for FAQs, new users will more quickly 
understand the nuances of cockroachDBs licensing. 

I also considered simply adding the links to the "See Also" section but think the description
and reasoning makes it so that users can at a glance understand the licensing decisions made.

Release note (general change): licensing added to Readme

### CODE REVIEW

**Comment by jordanlewis** [comment]
@bdarnell, would you please review this? Thanks.

**Comment by bdarnell** [comment]
Hi @cargillb,

Thanks for the contribution! I agree that we need a good summary of our licenses here. This is a good start, but I think it could use a little work - I'd emphasize the current state of the master branch instead of leading with the historical note about 19.1, and I think it's clearer to talk about two licenses rather than three. Since it's important to get the details right when talking about licensing, I think it might be better if you don't mind for one of our writers to take over and get this polished up instead of a lot of back-and-forth.

**Comment by cargillb** [comment]
Hi @bdarnell,

I'm glad that you think it's useful and thanks for the advice on what you think should be changed too. 

Absolutely happy for your writers to take over and glad I could at least get the ball rolling.

**Comment by cargillb** [comment]
Should I go ahead and close the pull request?

**Pull request closed without merging**
