### PR TITLE
roachtest: add acceptance/cluster-init

### LINKED ISSUE #29489: roachtest: move "init-mode" acceptance tests to roachtests
Move `TestInitModeBootstrapNodeZero`, `TestInitModeCommand`, and `TestInitModeNone` to "acceptance" roachtests.

### PR DESCRIPTION
**Pull request by petermattis**
Move the init-mode acceptance tests to a new acceptance/cluster-init
roachtest. Fixes a TODO about sending the "init" command to nodes other
than node 1. This was previously a limitation due to the --join flag
settings.

Fixes #29489

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29493#-:-LLdHk09CXmKWOEXV2M9:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cluster_init.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29493#-LLdHYoG2MfmW5WxM501:-LLdHYoH2E0f8IDCcSD5:b-l8przf) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f64db513ce2aab35627fbba86b7677fe62a5e7/pkg/cmd/roachtest/cluster_init.go#L179)):*
> ```Go
> 			{
> 				// Make sure that running init again returns the expected error message and
> 				// does not break the cluster. We have to use ExecCLI rahter than OneShot in
> ```

rather

**Review by petermattis — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29493#-:-LLdIjqXBydzxCdm9kAN:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cluster_init.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29493#-LLdHYoG2MfmW5WxM501:-LLdI4Zr0ntFXlaZmtmy:b-moxtv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/29f64db513ce2aab35627fbba86b7677fe62a5e7/pkg/cmd/roachtest/cluster_init.go#L179)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

rather
</blockquote></details>

Doen. Also proof that I copied most of this code: that typo was in `init_test.go`.

**Comment by petermattis** [comment]
(bors crashed)

bors r=tschottdorf

**Comment by petermattis** [comment]
(bors crashed, again)

bors r=tschottdorf

**Pull request merged**
