### PR TITLE
build: add build that simply compiles CRDB on supported platforms

### PR DESCRIPTION
**Pull request by otan**
Abstract away the process of building from
`./pkg/cmd/publish-*-artifacts`, and use this in
`./pkg/cmd/compile-builds`. This is intended to become a CI job for
TeamCity.

Build: https://teamcity.cockroachdb.com/admin/editBuild.html?id=buildType:Cockroach_UnitTests_CompileBuilds

Release note: None

### CODE REVIEW

**Review by jlinder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49974)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cmd/compile-builds/main.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49974#-M9KHj0vAn4OzuN0Njia:-M9KHj0vAn4OzuN0Njib:bwebmba) ([raw file](https://github.com/cockroachdb/cockroach/blob/799899a0599dcda12c3312e1c13ee647ab1d3e40/pkg/cmd/compile-builds/main.go#L28)):*
> ```Go
> 	}
> 
> 	for _, build := range release.SupportedBuilds {
> ```

The variable name `build`, maybe make it `target` like in publish-provisional-artifacts? (It also wouldn't override the imported `build`.)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49974)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder)

___
*[pkg/cmd/compile-builds/main.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49974#-M9KHj0vAn4OzuN0Njia:-M9KQsOs-rLtifNp7eXj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/799899a0599dcda12c3312e1c13ee647ab1d3e40/pkg/cmd/compile-builds/main.go#L28)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

The variable name `build`, maybe make it `target` like in publish-provisional-artifacts? (It also wouldn't override the imported `build`.)
</blockquote></details>

Done.

**Review by jlinder — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49974#-:-M9KU4hH10Bga51u1yeg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder)

**Comment by otan** [comment]
tftr!

bors r=jlinder

**Pull request merged**
