### PR TITLE
kv: correctly handle replicated locks when using the SKIP LOCKED policy

### LINKED ISSUE #115057: kv: skip locked does not work correctly with read committed
**Describe the problem**

Currently, when a skip locked request is evaluating, it only checks for in-memory exclusive and shared locks. Notably, it does not check for replicated locks. As a result, read committed transactions (which have a potential to acquire replicated locks) do not work well with `SKIP LOCKED`.

Related to https://github.com/cockroachdb/cockroach/issues/110743

Jira issue: CRDB-33860

Epic CRDB-34172

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, we weren't correctly handling replicated locks when using the SKIP LOCKED wait policy. Instead of skipping the replicated lock, we'd instead throw an unsupported error. This patch lifts this limitation. After doing so, we're able to support SKIP LOCKED in conjunction with both replicated locks and read committed transactions, as demostrated by the change to logic tests.

Closes #115057

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117888)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @RaduBerinde)

___
*[`pkg/kv/kvserver/batcheval/cmd_scan.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOlLXx6w1ttmnVtn5o:-NoOlLXx6w1ttmnVtn5p:bysnx3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/kv/kvserver/batcheval/cmd_scan.go#L41)):*
> ```Go
> 	var lockTableForSkipLocked storage.LockTableView
> 	if h.WaitPolicy == lock.WaitPolicy_SkipLocked {
> 		txnBoundReplicatedLTV := newTransactionBoundReplicatedLockTableView(readWriter, h.Txn)
> ```

It would be nice to push these two objects into a single constructor to avoid verbosity, even if the `requestBoundLockTableView` constructor calls out to a separate `txnBoundReplicatedLockTableView` constructor under the hood. That might also make any memory pooling cleaner. 

Ex.
```go
lockTableForSkipLocked = newRequestBoundLockTableView(
    readWriter, cArgs.Concurrency, h.Txn, args.KeyLockingStrength,
)
defer lockTableForSkipLocked.Close()
```
___
*[`pkg/kv/kvserver/batcheval/lock.go` line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOknWVDJIJp1fma4BG:-NoOknWVDJIJp1fma4BH:bw60cx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/kv/kvserver/batcheval/lock.go#L239)):*
> ```Go
> // strength that an individual request is attempting to acquire.
> type requestBoundLockTableView struct {
> 	inMemoryLockTableView   txnBoundLockTableView
> ```

nit: consider shortening these to `mem` and `repl`.
___
*[`pkg/kv/kvserver/batcheval/lock.go` line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOlyoQ0QTsyg6y-Ylz:-NoOlyoQ0QTsyg6y-Ym-:b-mxjsqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/kv/kvserver/batcheval/lock.go#L279)):*
> ```Go
> // newTransactionBoundReplicatedLTV creates a new
> // txnBoundReplicatedLockTableView.
> func newTransactionBoundReplicatedLockTableView(
> ```

nit: `newTxnBoundReplicatedLockTableView`
___
*[`pkg/kv/kvserver/batcheval/lock.go` line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOjy3m69B-4TeLjA8p:-NoOjy3m69B-4TeLjA8q:b6bkg47) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/kv/kvserver/batcheval/lock.go#L283)):*
> ```Go
> ) *txnBoundReplicatedLockTableView {
> 	return &txnBoundReplicatedLockTableView{
> 		reader: reader,
> ```

I'm not sure that this works if `!reader.ConsistentIterators()`. In that case, the `txnBoundReplicatedLockTableView` reader could observe a different view of the LSM than the `pebbleMVCCScanner`. It's difficult to predict what kinds of issues this could cause. Can we assert that all `reader`s passed here have `ConsistentIterators`?
___
*[`pkg/storage/mvcc.go` line 5854 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOmxJ97AQ0-mHxaFzn:-NoOmxJ97AQ0-mHxaFzo:b-fb9hmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/storage/mvcc.go#L5854)):*
From Slack:

> We can't re-use `CheckForAcquireLock` because it validates we're not calling it in the context of non-locking reads or non-transactional requests (the "for acquire" part). We can get around the former, but not the latter -- so I decided to introduce this new guy.

We could get around the former (non-locking reads) by hoisting this `if str == lock.None` up a level, right?

Why is the latter (non-transactional requests) a problem? Just because of the assertion in `validateLockAcquisition`? `lockTableKeyScanner` does handle non-transactional requests properly.

I'm pushing on this partly because I'd like to avoid a new method that's almost identical to `MVCCCheckForAcquireLock` and partly because I think we'll need to have an answer for this to decide what to do for https://github.com/cockroachdb/cockroach/issues/117628.
___
*[`pkg/storage/mvcc.go` line 5868 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOm_gXAlmEiZF-Pgpt:-NoOm_gXAlmEiZF-Pgpu:bplb55u) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/storage/mvcc.go#L5868)):*
> ```Go
> 	if err != nil {
> 		if lcErr := (*kvpb.LockConflictError)(nil); errors.As(err, &lcErr) {
> 			return true, &lcErr.Locks[0].Txn, nil
> ```

It's unfortunate that we could run into multiple conflicts (now with shared locks) but we only surface the first. We could have `pebbleMVCCScanner.isKeyLockedByConflictingTxn` handle multiple lock holders

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117888)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

___
*[`pkg/storage/mvcc.go` line 5854 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOmxJ97AQ0-mHxaFzn:-NoS76QI2GkZUddbo_B5:bv96zlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/storage/mvcc.go#L5854)):*
> Why is the latter (non-transactional requests) a problem? Just because of the assertion in `validateLockAcquisition`? 

Yeah, exactly. I initially didn't want to remove that assertion because of the "ForAcquire" bit in `MVCCCheckForAcquireLock`, but now I'm reconsidering. 

You're right, removing the assertion and pushing non-txnal complexity further down will allow us to address  address https://github.com/cockroachdb/cockroach/issues/117628 without code duplication as well. Instead of having a separate non-txnal branch in `cmd_{get,scan,reverse_scan}.go`, we could teach `acquireLockOnKeys`/`acquireLocksOnKeys`[*] to only return lock acquisition structs for transactional requests.

[*] with these methods renamed to be prefixed with a "maybe".

**Review by arulajmani — COMMENTED** [review]
TFTR, RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-:-Nonv_MRC-VMsYlCL0yX:bmu8ofu)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

___
*[`pkg/kv/kvserver/batcheval/cmd_scan.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOlLXx6w1ttmnVtn5o:-NonjHl08Gf_7gEfh5WU:bz0zv3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/kv/kvserver/batcheval/cmd_scan.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It would be nice to push these two objects into a single constructor to avoid verbosity, even if the `requestBoundLockTableView` constructor calls out to a separate `txnBoundReplicatedLockTableView` constructor under the hood. That might also make any memory pooling cleaner. 

Ex.
```go
lockTableForSkipLocked = newRequestBoundLockTableView(
    readWriter, cArgs.Concurrency, h.Txn, args.KeyLockingStrength,
)
defer lockTableForSkipLocked.Close()
```
</blockquote></details>

Done. Ended up renaming this function to`makeRequestBoundLockTableView` and introducing a new `newRequestBoundLockTableView` implementation that calls into that function. Doing so allows us to use `makeRequestBoundLockTableView` in tests with `replLTV` mocked out.

I also added a memory pool for requestBoundLockTableView (3rd commit). It's a bit hard to add one for `txnBoundReplicatedLockTableView`. We're re-using the `txnBoundLockTableView` for it, so:

- Either we need to expand that interface to include a `Close` method. However, that doesn't play well with other implementations (such as `concurrency.Guard`)
- Or we can do something hacky by trying to cast `replLockTableView` to a `txnBoundReplicatedLockTableView`. and only release memory if the cast succeeds.

For now, I've not done either. Do you prefer either options? Or are you okay with no memory pooling here for now?
___
*[`pkg/kv/kvserver/batcheval/lock.go` line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOknWVDJIJp1fma4BG:-Nonb3CN16OyknqOr7mY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/kv/kvserver/batcheval/lock.go#L239)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider shortening these to `mem` and `repl`.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/batcheval/lock.go` line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOjy3m69B-4TeLjA8p:-NonakMD4V0-Co1oDT6B:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/kv/kvserver/batcheval/lock.go#L283)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm not sure that this works if `!reader.ConsistentIterators()`. In that case, the `txnBoundReplicatedLockTableView` reader could observe a different view of the LSM than the `pebbleMVCCScanner`. It's difficult to predict what kinds of issues this could cause. Can we assert that all `reader`s passed here have `ConsistentIterators`?
</blockquote></details>

Done. 
___
*[`pkg/storage/mvcc.go` line 5854 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOmxJ97AQ0-mHxaFzn:-Non_Vs67AVCnHdsUSqD:bpm0m77) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/storage/mvcc.go#L5854)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> Why is the latter (non-transactional requests) a problem? Just because of the assertion in `validateLockAcquisition`? 

Yeah, exactly. I initially didn't want to remove that assertion because of the "ForAcquire" bit in `MVCCCheckForAcquireLock`, but now I'm reconsidering. 

You're right, removing the assertion and pushing non-txnal complexity further down will allow us to address  address https://github.com/cockroachdb/cockroach/issues/117628 without code duplication as well. Instead of having a separate non-txnal branch in `cmd_{get,scan,reverse_scan}.go`, we could teach `acquireLockOnKeys`/`acquireLocksOnKeys`[*] to only return lock acquisition structs for transactional requests.

[*] with these methods renamed to be prefixed with a "maybe".
</blockquote></details>

Done. I pulled this out into its own commit (the first one).
___
*[`pkg/storage/mvcc.go` line 5868 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOm_gXAlmEiZF-Pgpt:-NonuV_C38JOfcJlpiZs:b-6franv) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/storage/mvcc.go#L5868)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's unfortunate that we could run into multiple conflicts (now with shared locks) but we only surface the first. We could have `pebbleMVCCScanner.isKeyLockedByConflictingTxn` handle multiple lock holders
</blockquote></details>

This proved to be a bigger change -- we'll need to change the `lockTableGuardImpl` implementation for this as well. For now, I've just added a TODO. I'm not sure how much this matters in practice, given we're only using the return value to perform intent resolution in case the intent was abandoned -- we might not proactively remove some abandoned intents, but that seems fine.

**Review by nvb — COMMENTED** [review]
> Reviewed 22 of 22 files at r2, 20 of 20 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117888)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @RaduBerinde)

___
*[`pkg/kv/kvserver/batcheval/cmd_scan.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOlLXx6w1ttmnVtn5o:-NooyMP86U676e599cn-:b-gmihlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/kv/kvserver/batcheval/cmd_scan.go#L41)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done. Ended up renaming this function to`makeRequestBoundLockTableView` and introducing a new `newRequestBoundLockTableView` implementation that calls into that function. Doing so allows us to use `makeRequestBoundLockTableView` in tests with `replLTV` mocked out.

I also added a memory pool for requestBoundLockTableView (3rd commit). It's a bit hard to add one for `txnBoundReplicatedLockTableView`. We're re-using the `txnBoundLockTableView` for it, so:

- Either we need to expand that interface to include a `Close` method. However, that doesn't play well with other implementations (such as `concurrency.Guard`)
- Or we can do something hacky by trying to cast `replLockTableView` to a `txnBoundReplicatedLockTableView`. and only release memory if the cast succeeds.

For now, I've not done either. Do you prefer either options? Or are you okay with no memory pooling here for now?
</blockquote></details>

Another option would be to try to cast each inner `txnBoundLockTableView` to a `type closer interface { Close() }`. But I don't think it's worth accidentally closing the `concurrency.Guard` if we ever add a `Close` method to it.

So I'm ok with no memory pooling for the `txnBoundReplicatedLockTableView` until we decide that it's a performance concern. Now that we have the users of `requestBoundLockTableView` doing the right thing, any additional memory recycling in the future will be straightforward and localized.
___
*[`pkg/storage/mvcc.go` line 5868 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOm_gXAlmEiZF-Pgpt:-Nooxzbl9_kvuS5DSfhq:b-4imoop) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/storage/mvcc.go#L5868)):*
> I've just added a TODO

A TODO for now sounds good to me.
___
*[`pkg/storage/mvcc.go` line 5840 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-Noow58yERVuJUHukJNN:-Noow58yERVuJUHukJNO:bafc4nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/99a74ee4267f8286bb0b2edc3555245b5d491899/pkg/storage/mvcc.go#L5840)):*
> ```Go
> 	maxLockConflicts int64,
> ) error {
> 	if !(str == lock.Shared || str == lock.Exclusive) {
> ```

I feel like it's useful to retain some shared logic between `MVCCCheckForAcquireLock` and `MVCCAcquireLock` to make their relationship clear and prevent them from drifting. Consider the following alternative change:
1. rename `validateLockAcquisition` to `validateLockAcquisitionStrength`.
2. inline the `txn == nil` check in `MVCCAcquireLock` and remove the `txn` arg from `validateLockAcquisitionStrength`.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117888)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

___
*[`pkg/kv/kvserver/batcheval/cmd_scan.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-NoOlLXx6w1ttmnVtn5o:-NorAeeo1vE8XFiLrNO4:bdnerqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e243911bb186d61add9402cb07d72eaf5c4fe/pkg/kv/kvserver/batcheval/cmd_scan.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Another option would be to try to cast each inner `txnBoundLockTableView` to a `type closer interface { Close() }`. But I don't think it's worth accidentally closing the `concurrency.Guard` if we ever add a `Close` method to it.

So I'm ok with no memory pooling for the `txnBoundReplicatedLockTableView` until we decide that it's a performance concern. Now that we have the users of `requestBoundLockTableView` doing the right thing, any additional memory recycling in the future will be straightforward and localized.
</blockquote></details>

Sounds good! 
___
*[`pkg/storage/mvcc.go` line 5840 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-Noow58yERVuJUHukJNN:-NorAan39I1MRsXTe8Md:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/99a74ee4267f8286bb0b2edc3555245b5d491899/pkg/storage/mvcc.go#L5840)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I feel like it's useful to retain some shared logic between `MVCCCheckForAcquireLock` and `MVCCAcquireLock` to make their relationship clear and prevent them from drifting. Consider the following alternative change:
1. rename `validateLockAcquisition` to `validateLockAcquisitionStrength`.
2. inline the `txn == nil` check in `MVCCAcquireLock` and remove the `txn` arg from `validateLockAcquisitionStrength`.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 20 of 21 files at r5, 15 of 21 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117888#-:-NorCTS9EV0I3lHo3UxI:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by arulajmani** [comment]
Ugh I changed an error message and forgot to update TestMVCCHistories. I'll re-push.

**Comment by arulajmani** [comment]
bors r=nvanbenschoten

**Pull request merged**
