### PR TITLE
distsql: Fix flaky TestDistSQLUnavailableHosts.

### LINKED ISSUE #126908: sql: TestDistSQLUnavailableHosts failed
sql.TestDistSQLUnavailableHosts [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16000385?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/16000385?buildTab=artifacts#/) on master @ [21cddcfa9868b8f6b4817a50318303dc21aa87cd](https://github.com/cockroachdb/cockroach/commits/21cddcfa9868b8f6b4817a50318303dc21aa87cd):

```
=== RUN   TestDistSQLUnavailableHosts
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/765430912bd62afa1f42a127d71d4b8a/logTestDistSQLUnavailableHosts3635241226
    test_log_scope.go:81: use -show-logs to present logs inline
    distsql_physical_planner_test.go:669: -- test log scope end --
--- FAIL: TestDistSQLUnavailableHosts (30.94s)
=== RUN   TestDistSQLUnavailableHosts/unhealthy-nodes-in-single-tenant-mode
    distsql_physical_planner_test.go:541: condition failed to evaluate within 2s: from distsql_physical_planner_test.go:497: query 'SELECT info FROM [EXPLAIN (DISTSQL, SHAPE) SELECT sum(xsquared) FROM t] WHERE info LIKE 'Diagram%'':
        expected one of:
        Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJyklV9ro0wUxu_fTyEHXtrCiI4aY7xqaVwaNv2zMcsulFBm46krNU46M9KWku--GNutcRtR40XAceZ5fvOcmZNXkI8p-BAG0-B8riXZPde-zK4vtdvg5830bHKlHY8n4Tz8NiVaeHF2E5xob1Nlvjp-lo85ExidlGvUQvtxEcyCUmY6-RpoR-OExYKt_j8CAhmP8IqtUIJ_CxQIWEDABgIOEBjAgsBa8CVKyUUx5XW7YBI9g28SSLJ1rorhBYElFwj-K6hEpQg-zNmvFGfIIhSGCQQiVCxJtzbqVN2tH_AFCJzzNF9l0tfesYFAuGbFiG5YJiw2BHiuPmykYjGCTytckzH45oa0RzuLY4ExU1wYg12y8Pvl8Sk92Wtr1WwHe20_3PKMiwjLrX1YLTbNYNTsRmbXyOhuIrR9sWifYhmWqRtO-3rRLnSVWNzD6uXu2FrtQ7F6heKYuuG2D8XqQlcJZXhYKMMdW7t9KHavUFxTN7z2odhd6CqheIeF4u3YOu1DcXqF4pl660ScLmiVREaHJTLq0mJnKNc8k1jreZ87mTUnnRbNEaMYy04qeS6WeCP4cju3fL3eCm0HIpSq_ErLl0n2_kkqgWz19x-iqkQblawdJVpVGtSVrGamLlB2o5SzX4nWlZy-23PrSoNGJXc_k1VXcvsyDetKw0Ylbz-TXVfy-jJ5daVR8zEw90M5_5zN5mPeQDUqrs59yp_ukgh8MN8e_ZOf9weKBSyWxf0Nf_Onrez8ZV3cvnuWSiRwyR5wjArFKskSqZIl-ErkuNn89ycAAP__hKt0rw==
        Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJyklF9vmzAUxd_3KawrTW0lR2AgJOOpVcPUaOmfhUybVEWVF24pKsGpbdRWVb77BLQrQQ0CygMStvmd43Pt-wLqIQEPAn_mny5InN4K8n1-eU6u_T9Xs5PpBTmcTINF8HNGSXB2cuUfkdelKlsfPqmHjEsMj8p_9JL8PvPnfomZTX_45GAS80jy9dcDoJCKEC_4GhV418CAggUUbKDgwJLCRooVKiVkPv1SLJ6GT-CZFOJ0k-l8eElhJSSC9wI61gmCBwv-N8E58hClYQKFEDWPk0JCH-ubzT0-A4VTkWTrVHnkzTJQCDY8HxkYlgnLLQWR6XcZpXmE4LGKr-kEPHNL21s7iSKJEddCGs6us-DX-eExO9ora9Vknb2y72pZKmSI5dbepZbbZmPjbsbsmrHxjjHWvlSsT6kMyxwYjkl4GhJGhL5D2bpyrIvTSkDDz1VuuCNrtQ_I6hWQYw4Mt_1xtrq4q4Tifi4Ud0fWbh-K3SsU1xwY4_ah2F3cVUIZfS6UUZfWMke1EanC2l3_WMmsKQ1Y3hQwjLDsIEpkcoVXUqyKteXnZQEqBkJUupxl5cc0fZtSWiJf_--MVRJrJFk7JFYlOXWS1Uj61sGT3Uhy9pNYneT03d2wTho2ktz9nqw6ye3rya2TRo2k8X5Pdp007utplJ_R20Q83sQheGC-PoMPXm8P5D_wSOUXJbgTjwV28bzJj_ktTxRSOOf3OEGNch2nsdLxCjwtM9xuv_wLAAD__7Co7LA=
        Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJyklF9vmzAUxd_3KawrTW0lR2AgJOOpVcPUaOmfhUybVEWVF24pKsGpbdRWVb77BLQrQQ0CygMStvmd43Pt-wLqIQEPAn_mny5InN4K8n1-eU6u_T9Xs5PpBTmcTINF8HNGSXB2cuUfkdelKlsfPqmHjEsMj8p_9JL8PvPnfomZTX_45GAS80jy9dcDoJCKEC_4GhV418CAggUUbKDgwJLCRooVKiVkPv1SLJ6GT-CZFOJ0k-l8eElhJSSC9wI61gmCBwv-N8E58hClYQKFEDWPk0JCH-ubzT0-A4VTkWTrVHnkzTJQCDY8HxkYlgnLLQWR6XcZpXmE4LGKr-kEPHNL21s7iSKJEddCGs6us-DX-eExO9ora9Vknb2y72pZKmSI5dbepZbbZmPjbsbsmrHxjjHWvlSsT6kMyxwYTvtqsS7uKqEMP1et4Y6s1T4Uq1cojjkwXJPwNCSMCH2HsnVAVhenlYDczwXk7sja7QOyewXkmgNj3P7U2F3cVUIZfS6UUZfWMke1EanC2l3_WMmsKQ1Y3hQwjLDsIEpkcoVXUqyKteXnZQEqBkJUupxl5cc0fZtSWiJf_--MVRJrJFk7JFYlOXWS1Uj61sGT3Uhy9pNYneT03d2wTho2ktz9nqw6ye3rya2TRo2k8X5Pdp007utplJ_R20Q83sQheGC-PoMPXm8P5D_wSOUXJbgTjwV28bzJj_ktTxRSOOf3OEGNch2nsdLxCjwtM9xuv_wLAAD__6oi7LA=
        got:
        Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJyklF9vmzAUxd_3KawrTW0lR2AgJOOpVcPUaOmfhUybVEWVF24pKsGpbdRWVb77BLQrQQ0CygMStvmd43Pt-wLqIQEPAn_mny5InN4K8n1-eU6u_T9Xs5PpBTmcTINF8HNGSXB2cuUfkdelKlsfPqmHjEsMj8p_9JL8PvPnfomZTX_45GAS80jy9dcDoJCKEC_4GhV418CAggUUbKDgwJLCRooVKiVkPv1SLJ6GT-CZFOJ0k-l8eElhJSSC9wI61gmCBwv-N8E58hClYQKFEDWPk0JCH-ubzT0-A4VTkWTrVHnkzTJQCDY8HxkYlkl4GhJGhL5DCcstBZHpd0mleYTgsYrH6QQ8c0vb2zyJIokR10Iazq7L4Nf54TE72itr1WSdvbLvalkqZIjlNt-llttmY-NuxuyasfGOMda-bKxP2QzLHBiO2bparIu7SijDz1VruCNrtQ_F6hWKYw4Mt30oVhd3lVDcz4Xi7sja7UOxe4XimgNj3D4Uu4u7Siijz4Uy6tJO5qg2IlVYu98fK5k1pQHLGwGGEZZdQ4lMrvBKilWxtvy8LEDFQIhKl7Os_Jimb1NKS-Tr_92wSmKNJGuHxKokp06yGknfOniyG0nOfhKrk5y-uxvWScNGkrvfk1UnuX09uXXSqJE03u_JrpPGfT2N8jN6m4jHmzgED8zXZ_DB6-2B_AceqfyiBHfiscAunjf5Mb_liUIK5_weJ6hRruM0Vjpegadlhtvtl38BAAD__7Hc7LA=
    --- FAIL: TestDistSQLUnavailableHosts/unhealthy-nodes-in-single-tenant-mode (6.33s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDistSQLUnavailableHosts.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40179

### PR DESCRIPTION
**Pull request by shubhamdhama**
This PR fixes the two flaky tests as reported in the linked issue:

**TestDistSQLUnavailableHosts/unhealthy-nodes-in-single-tenant**

The issue was that the first plan of `plans` slice was incorrect and included the 5th node.

Some more context: Although this test shouldn't be affected by the core changes in #124986, I made slight improvements during refactoring. I added a plan check after stopping the 5th node and before running the query to avoid updating the lease and to understand how the query is planned.

This issue wasn't detected even in local stress testing. My hypothesis is that leases are usually updated quickly enough that the 5th node's ranges are moved to the 2nd or 3rd node most of the time. But on teamcity it hits the case where the leases haven't moved and range is planned on the gateway.

**TestDistSQLUnavailableHosts/unhealthy-nodes-in-shared-mode**

The test runs fast enough that if a heartbeat hasn't occurred yet, `ConnHealthTryDialInstance` returns `ErrNotHeartbeated`. The fix here is in most cases, this error can be ignored, and the node can be considered healthy. If the node is indeed unhealthy, we would anyway retry-as-local.

Fixes: #126908

Epic: CRDB-40179

Release note: None

### CODE REVIEW

**Comment by shubhamdhama** [comment]
- [ ] Revert `skip.UnderShort` back to `skip.UnderDuress`. It's here right now to stress on teamcity.

**Comment by shubhamdhama** [comment]
I was thinking of stressing using the way mentioned [here](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/2212790312/How+to+investigate+a+Go+test+failure#Reproducing-a-test-failure) but found out some `Bazel Extended CI` was failing with the following error

[Link to the test](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_MaybeStressrace/16023364?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true)
```
Failed
=== RUN   TestDistSQLUnavailableHosts/unhealthy-nodes-in-shared-mode
    distsql_physical_planner_test.go:563: query 'SELECT IF(substring(start_key for 1)='…',start_key,NULL),
                      IF(substring(end_key for 1)='…',end_key,NULL),
                      lease_holder, replicas FROM [SHOW RANGES FROM TABLE t WITH DETAILS]': expected:
        NULL, …/Table/106/1/0, 1, {1}
        …/Table/106/1/0, …/Table/106/1/20, 1, {1,2,3}
        …/Table/106/1/20, …/Table/106/1/40, 2, {2,3,4}
        …/Table/106/1/40, …/Table/106/1/60, 3, {1,3,4}
        …/Table/106/1/60, …/Table/106/1/80, 4, {1,2,4}
        …/Table/106/1/80, NULL, 5, {2,3,5}
        got:
        NULL, …/Table/106/1/0, 1, {1}
        …/Table/106/1/0, …/Table/106/1/20, 3, {1,2,3}
        …/Table/106/1/20, …/Table/106/1/40, 2, {2,3,4}
        …/Table/106/1/40, …/Table/106/1/60, 3, {1,3,4}
        …/Table/106/1/60, …/Table/106/1/80, 4, {1,2,4}
        …/Table/106/1/80, NULL, 5, {2,3,5}
    --- FAIL: TestDistSQLUnavailableHosts/unhealthy-nodes-in-shared-mode (98.59s)
```

I didn't have a concrete answer to why a particular replica should be a leaseholder so I explicitly added
```go
			r.Exec(t, fmt.Sprintf("ALTER TABLE t RELOCATE LEASE VALUES (%d, %d)", i+1, n*i/5))
```

but now it's failing with the same error for [another subtest](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_MaybeStressrace/16026471?buildTab=tests&expandedTest=build%3A%28id%3A16026471%29%2Cid%3A784), 
```
Failed
=== RUN   TestDistSQLUnavailableHosts/unhealthy-nodes-in-external-mode
    distsql_physical_planner_test.go:614: query 'SELECT IF(substring(start_key for 1)='…',start_key,NULL),
                      IF(substring(end_key for 1)='…',end_key,NULL),
                      lease_holder, replicas FROM [SHOW RANGES FROM TABLE t WITH DETAILS]': expected:
        NULL, …/Table/106/1/0, 1, {1}
        …/Table/106/1/0, …/Table/106/1/20, 1, {1,2,3}
        …/Table/106/1/20, …/Table/106/1/40, 2, {2,3,4}
        …/Table/106/1/40, …/Table/106/1/60, 3, {1,3,4}
        …/Table/106/1/60, …/Table/106/1/80, 4, {1,2,4}
        …/Table/106/1/80, NULL, 5, {2,3,5}
        got:
        NULL, …/Table/106/1/0, 1, {1}
        …/Table/106/1/0, …/Table/106/1/20, 3, {1,2,3}
        …/Table/106/1/20, …/Table/106/1/40, 2, {2,3,4}
        …/Table/106/1/40, …/Table/106/1/60, 3, {1,3,4}
        …/Table/106/1/60, …/Table/106/1/80, 4, {1,2,4}
        …/Table/106/1/80, NULL, 5, {2,3,5}
    --- FAIL: TestDistSQLUnavailableHosts/unhealthy-nodes-in-external-mode (91.26s)
```

I'm out of ideas what's causing this? Or is this expected and is the reason why Yahor suggested to mark these as `skip.UnderDuress`?

**Comment by rytaft** [comment]
Adding @yuzefovich as a reviewer since it looks like you reviewed the most recent change to this test. If you don't have time let me know and I can take a look. Thanks!

**Review by yuzefovich — COMMENTED** [review]
`race` builds impose performance penalty, `stressrace` builds even larger one. This test has 5 nodes (which obviously requires more resources than a single node), and when we have tenants (either shared or external mode), then performance overhead of the test is even larger. Generally speaking, commands that modify the KV range allocation decisions (like relocating leases, etc) are kinda best-effort, and they generally work, but they could fail / take long time under overload (which is the case in this test). In short, yes, all these observations are the reason why I suggested `skip.UnderDuress` since this test is destined to be flaky under overload.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126976#-:-O1Xu24X8ZWUbwmQ44vk:b-v7l7f1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @shubhamdhama)

___
*[`pkg/sql/distsql_physical_planner.go` line 1578 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126976#-O1XpaF24G82ypfn9g4c:-O1XpaF24G82ypfn9g4d:bxu61kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3998406a1cf7228328b38c628f9671f7cd2df9a5/pkg/sql/distsql_physical_planner.go#L1578)):*
> ```Go
> 	status := NodeOK
> 	err := dsp.nodeHealth.connHealthInstance(instanceID, instanceRPCAddr)
> 	if errors.Is(err, rpc.ErrNotHeartbeated) {
> ```

nit: perhaps move this check inside the `err != nil` block below.

**Review by shubhamdhama — COMMENTED** [review]
Got it, thanks for the explanation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126976#-:-O1Y845s59sCDNQQqOan:bx40ouy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/distsql_physical_planner.go` line 1578 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126976#-O1XpaF24G82ypfn9g4c:-O1Y8806AAOPLbdCzTup:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3998406a1cf7228328b38c628f9671f7cd2df9a5/pkg/sql/distsql_physical_planner.go#L1578)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps move this check inside the `err != nil` block below.
</blockquote></details>

Done
___
*[`pkg/sql/distsql_physical_planner_test.go` line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126976#-O1Y8LPkDTwy5-K4TCqe:-O1Y8LPkDTwy5-K4TCqf:b-lozyte) ([raw file](https://github.com/cockroachdb/cockroach/blob/3998406a1cf7228328b38c628f9671f7cd2df9a5/pkg/sql/distsql_physical_planner_test.go#L467)):*
> ```Go
> 				i+1, (i+1)%4+1, (i+2)%4+1, n*i/5,
> 			))
> 			r.Exec(t, fmt.Sprintf("ALTER TABLE t RELOCATE LEASE VALUES (%d, %d)", i+1, n*i/5))
> ```

I'm removing this line then because I'm sure the execute query one line above does this anyway, and it would just increase the test time.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126976#-:-O1YALHM9KyVZIM1PanH:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Comment by shubhamdhama** [comment]
Thanks for the review!

Stress and race tests on my local and gceworkers have passed (many times), so I'm merging this. I will take care of any other failures in follow-up PRs. 

bors r=yuzefovich

**Comment by yuzefovich** [comment]
bors r=yuzefovich

**Pull request merged**
