### PR TITLE
release-19.2: jobs: check GCMutations when checking for orphaned jobs

### PR DESCRIPTION
**Pull request by pbardea**
Backport 2/2 commits from #44831.

/cc @cockroachdb/release

---

We periodically GC jobs from the jobs table, this includes collecting
orphaned running jobs. However, jobs could still be referenced by a
GCMutation or the job that drops the table (and therefore not be
orphaned).

Release note (bug fix): Fix a bug where drop index jobs waiting for GC
TTL might be erroneously deleted early. Usually a DROP INDEX job would
appear as "waiting for GC TTL" to indicate that the data is still on
disk, however this bug would may cause this job to be deleted before the
data was actually removed from disk.

### CODE REVIEW

**Review by spaskob — APPROVED** [review]
lgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44873#-:-M-VznYD-cI-rrp7W3ui:bb7k0qh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @spaskob)

**Comment by pbardea** [comment]
bors r=spaskob

**Comment by pbardea** [comment]
Updated release note.
bors r=spaskob

**Pull request merged**
