### PR TITLE
Add Descriptor which is a union of {Table,Database}Descriptor.

### LINKED ISSUE #2511: Provide a way to tell object type from its ID.
eg: given ID=1010, is the corresponding object a table or database?
Currently, we need to fetch its descriptor and attempt to parse it as either a database descriptor, or a table descriptor. see: `sql/config.go:GetZoneConfig` for an example.

Ideally, we should be able to look this up using a single KV get, preferably alongside the descriptor.

Possibilities:
* make `TableDescriptor` and `DatabaseDescriptor` use the same proto message with additional `type` field. Requires slightly stricter validation on creation/use.
* add a `type` column to `system.descriptor`. Would double the number of keys and require two reads.
* separate column or table based on descriptor type. Would need two lookups, one of which would always fail. Moves enforcement of unique ID outside the `system.descriptor` table.
* encode the type into the ID. We would have to be very careful about passing them around.

Future considerations:
Depending on if/how we end up supporting proto fields as columns, having different proto messages may not work.

### PR DESCRIPTION
**Pull request by petermattis**
Get rid of ugly hack in GetZoneConfig which tried to parse a descriptor
first as a DatabaseDescriptor and then as a TableDescriptor.

Fixes #2511

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/2947)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. Could you file a "easy, helpwanted, cleanup" issue to see about merging `Descriptor` and `descriptorProto`? The two now feel somewhat redundant.

**Comment by petermattis** [comment]
Not sure how to merge `Descriptor` and `descriptorProto`. The latter is an interface for the shared functionality between `{Table,Database}Descriptor`. What did you have in mind?

**Comment by tamird** [comment]
well `Descriptor` could implement `descriptorProto`'s methods and pass through to its underlying {Database,Table}Descriptor

**Comment by petermattis** [comment]
It could, yet we pass `&{Table,Database}Descriptor` as arguments to methods which take a `descriptorProto`, so I'm not clear on how that would help.

**Comment by tamird** [comment]
My thinking is that we'd pass `Descriptor`s to those methods instead. Perhaps it wouldn't be any more ergonomic, but both constructs provide polymorphism over the `*Descriptor`s, which feels like overlap worth investigating (at least for new contributors).

**Comment by petermattis** [comment]
I don't see any benefit in having the callers of `{create,get}Descriptor` pass a `Descriptor` instead of a `descriptorProto`. Seems like it would just be pushing code around and the result wouldn't be any clearer (IMO).

**Pull request merged**
