### PR TITLE
server: tag kv request tracing spans with the BatchRequest

### PR DESCRIPTION
**Pull request by andreimatei**
This patch adds the BatchRequest as a tracing lazy tag to the respective
span, so that the request gets rendered in the tracing UI.

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
Are we sure we want to backport this into the release branch? What's the justification? This seems like it could introduce some risk, as we're now holding new references with unclear lifetimes (at least to me) to a potentially large batch request. Could this increase memory pressure in large AddSSTable workloads?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78204#-:-MyjDjJo3jcKL9R8IhXU:b-lij8yh)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
I don't have to backport it if you don't think (note that this here is the master PR).
But I think the lifetime of the new reference is clear enough - the span pretty convincingly doesn't outlive the request. To see if you feel any better, I've amended the patch to nil out the lazy tags slice eagerly when spans are released to the sync.Pool. Not doing so before was an oversight.
What do you think?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78204#-:-MylxgXR99oJ75yt0lE3:b-mkop4v)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
friendly ping for opinion

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78204#-:-Mzqkmcz5OE5qdjBSFt5:brxhofh)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — APPROVED** [review]
:lgtm: this seems very useful. I still don't think we should immediately backport the first half of this PR, given where we are in the stability period, but maybe for a v22.1.2+ patch release once it's baked on master for a few weeks?

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78204#-:-Mzut2XS57c96EZMsTy5:b-stkxcb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/util/tracing/tracer.go, line 989 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78204#-MzutDsS6Ip6uDiaihvo:-MzutDsS6Ip6uDiaihvp:b5ts81q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99b9731629c71b3c91a91268d4dd2d86ab6f612/pkg/util/tracing/tracer.go#L989)):*
> ```Go
> 	c.mu.recording.finishedChildren = nil
> 	c.mu.tags = nil
> 	c.mu.lazyTags = nil
> ```

Should this be part of a different commit that we do backport ASAP?

**Review by andreimatei — COMMENTED** [review]
removed the backport label

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78204#-:-N4Do5ql4T78CSbJpBXU:bujepyz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/util/tracing/tracer.go` line 989 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78204#-MzutDsS6Ip6uDiaihvo:-N4DmrpHEplGWrGfCSfQ:b-4oohm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b99b9731629c71b3c91a91268d4dd2d86ab6f612/pkg/util/tracing/tracer.go#L989)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be part of a different commit that we do backport ASAP?
</blockquote></details>

not particularly, I don't think. Independent of this code, the `c.mu.lazyTags` field is reset if/when the span is reused, [here](https://github.com/cockroachdb/cockroach/blob/26df381376ca988500da3289d0d89e0815d4047e/pkg/util/tracing/span.go#L649). I think you pushed for that reset structure, and it was a a good idea.
nil-ing out the field here means that the tag is not kept alive while the span is in the `sync.Pool`. The lock contention is the only one using the lazy tags until this patch, so it's not a big deal. Now with the `BatchRequest` hanging from the lazy tags, it becomes a somewhat bigger deal.

**Pull request merged**
