### PR TITLE
opt: Prune Delete operator input columns

### PR DESCRIPTION
**Pull request by andy-kimball**
Prune input columns that are not needed by a Delete operator. Needed
columns include returned columns and index key columns. All other columns
can be pruned.

Pruning Delete columns causes new interactions with the Delete "fast path"
that uses range delete. When multiple column families are in use, the
range delete needs to cover all column families. The "forDelete" flag
is used to construct spans that cover all columns, rather than just
"needed" columns. A new ConstructDeleteRange exec factory function sets
this flag correctly.

After this change, optimizer deletes no longer need to stay behind a
feature flag, as all fast paths should now work at least as well as they
do with the heuristic planner.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
@jordanlewis, I've added a `ConstructDeleteRange` method that I think should hook into your new operator easily.

**Comment by jordanlewis** [comment]
Nice. Should this come sequenced after the execution PR?

**Review by andy-kimball — COMMENTED** [review]
I assume so, if you get yours in soon.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-:-LXM5fb62U0_C9OpydPb:b-xlg95u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

**Comment by jordanlewis** [comment]
Mine is merged now.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: (modulo using the new delete range operator)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-:-LXPJmR7EIjWEWhMGUMt:b-tdl8zb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/metadata.go, line 220 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXPIeEh2U2hZKs-xHn3:-LXPIeEiCpfLmAOuddxh:b-yow7fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e9a72a85614db9eca785acf908cfa74a2f5c32b/pkg/sql/opt/metadata.go#L220)):*
> ```Go
> // is passed separately so that its original formatting is preserved for error
> // messages, pretty-printing, etc.
> func (md *Metadata) AddTableWithAlias(tab cat.Table, alias tree.TableName) TableID {
> ```

[nit] most functions pass `*TableName`. We'd just make a copy so it shouldn't escape
___
*[pkg/sql/opt/cat/table.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXPHMy90eKQ_qrkgeEa:-LXPHMy90eKQ_qrkgeEb:bmzbob1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7b75eaf174b8d479f4702b566a7997495db90d/pkg/sql/opt/cat/table.go#L29)):*
> ```Go
> // Table is an interface to a database table, exposing only the information
> // needed by the query optimizer.
> type Table interface {
> ```

[nit] This comment could be extended with some general info on public, writable, deletable columns.
___
*[pkg/sql/opt/cat/table.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXPHawF-GVheuH_nZO_:-LXPHawF-GVheuH_nZOa:b-p1pwl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7b75eaf174b8d479f4702b566a7997495db90d/pkg/sql/opt/cat/table.go#L43)):*
> ```Go
> 	ColumnCount() int
> 
> 	// WritableColumnCount returns the number of public and writable columns in
> ```

In these descriptions, "writable" and "deletable" each have two meanings (they either include the other columns or not). I would switch to using "write-only" and "delete-only" when referring to just those columns (consistent with the `ImmutableTableDescriptor` terminology). E.g. `WritableColumnCount returns the number of public and write-only columns`.
___
*[pkg/sql/opt/cat/table.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXPIM69-ubSCn84a8TF:-LXPIM69-ubSCn84a8TG:b-bl3p2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b38c4f76119d6760c730c501b02332a4979bf47/pkg/sql/opt/cat/table.go#L73)):*
> ```Go
> 	IndexCount() int
> 
> 	// WritableIndexCount returns the number of public and writable indexes
> ```

Same suggestion, "write-only indexes".

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 25 of 25 files at r1, 5 of 5 files at r2, 15 of 15 files at r3, 20 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-:-LXQywmg-jIEgUjT-pQI:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

___
*[pkg/sql/logictest/testdata/logic_test/delete, line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQvxvGD4maCdOv0ueT:-LXQvxvGD4maCdOv0ueU:bu7rwgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/5add46733c791c021bbc78eeeb6f13d2b8132885/pkg/sql/logictest/testdata/logic_test/delete#L267)):*
> ```
> BEGIN; ALTER TABLE family ADD COLUMN z INT CREATE FAMILY
> 
> # Check that the new column is not usable in RETURNING
> ```

I think this comment is stale
___
*[pkg/sql/opt/cat/column.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQX_iO0pCdrCiMdGy8:-LXQX_iO0pCdrCiMdGy9:bqf4dpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7b75eaf174b8d479f4702b566a7997495db90d/pkg/sql/opt/cat/column.go#L75)):*
> ```Go
> // the given ordinal position is a mutation column.
> func IsMutationColumn(table Table, ord int) bool {
> 	return ord >= table.ColumnCount()
> ```

Do you also want to check that it's less than `table.DeletableColumnCount()`?
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1653 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQyWaZ28z73mWB1-M_:-LXQyWa_50kaOYaTCAOY:b7u658d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5add46733c791c021bbc78eeeb6f13d2b8132885/pkg/sql/opt/norm/testdata/rules/prune_cols#L1653)):*
> ```
> 
> # Prune when computed ordering column is present.
> opt
> ```

do you want to add an expectation here?
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1706 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQy_hxDoRKCEmIPUq9:-LXQy_hxDoRKCEmIPUqA:b-yq3btr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5add46733c791c021bbc78eeeb6f13d2b8132885/pkg/sql/opt/norm/testdata/rules/prune_cols#L1706)):*
> ```
> 
> # Prune when mutation columns/indexes exist.
> opt
> ```

and here?
___
*[pkg/sql/opt/optbuilder/insert.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQYxyV64ULT2Ag3qt5:-LXQYxyW--MdRcLvXI5y:b425yyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7b75eaf174b8d479f4702b566a7997495db90d/pkg/sql/opt/optbuilder/insert.go#L408)):*
> ```Go
> 
> // addTargetTableColsForInsert adds up to maxCols columns to the list of columns
> // that will be set by an INSERT operation. Non-mutation olumns are added from
> ```

Non-mutation olumns -> Non-mutation columns
___
*[pkg/sql/opt/optbuilder/insert.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQZahQ8uQOodmk3SWp:-LXQZHaQ99bRkuoTwOld:brcuvpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7b75eaf174b8d479f4702b566a7997495db90d/pkg/sql/opt/optbuilder/insert.go#L423)):*
> ```Go
> 
> 	// Only consider non-mutation columns, since mutation columns are hidden from
> 	// the SQL user.
> ```

Is this a change from before?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34303)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/delete, line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQvxvGD4maCdOv0ueT:-LXZ8pJzDxDcGw7Nfvjd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5add46733c791c021bbc78eeeb6f13d2b8132885/pkg/sql/logictest/testdata/logic_test/delete#L267)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think this comment is stale
</blockquote></details>

Done.
___
*[pkg/sql/opt/cat/column.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQX_iO0pCdrCiMdGy8:-LXZ9Fpg6dMInhHS1d-O:bgocxkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7b75eaf174b8d479f4702b566a7997495db90d/pkg/sql/opt/cat/column.go#L75)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you also want to check that it's less than `table.DeletableColumnCount()`?
</blockquote></details>

That'd be more of an assert, since only mutation columns are >= `ColumnCount`. I want this to be inlined, and don't want to add an assert panic in this code path, since it's used in contexts where we should be returning errors rather than panicking. I'm also not too worried about that case. So I'll leave as-is.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1653 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQyWaZ28z73mWB1-M_:-LXZC9Y-3wTBLBI7Ruze:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5add46733c791c021bbc78eeeb6f13d2b8132885/pkg/sql/opt/norm/testdata/rules/prune_cols#L1653)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

do you want to add an expectation here?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1706 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQy_hxDoRKCEmIPUq9:-LXZCAAw3ORHVxlohde8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5add46733c791c021bbc78eeeb6f13d2b8132885/pkg/sql/opt/norm/testdata/rules/prune_cols#L1706)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

and here?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQYxyV64ULT2Ag3qt5:-LXZCDyl8-dlWActP9Br:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7b75eaf174b8d479f4702b566a7997495db90d/pkg/sql/opt/optbuilder/insert.go#L408)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Non-mutation olumns -> Non-mutation columns
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34303#-LXQZahQ8uQOodmk3SWp:-LXZCFos3s3KP3bFGwb_:b-ijng5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f7b75eaf174b8d479f4702b566a7997495db90d/pkg/sql/opt/optbuilder/insert.go#L423)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is this a change from before?
</blockquote></details>

No, just additional comment for clarification.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 47 files at r5, 13 of 25 files at r6, 1 of 5 files at r7, 9 of 15 files at r8, 23 of 23 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34303)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj)

**Review by danhhz — COMMENTED** [review]
changefeed changes lgtm

**Pull request merged**
