### PR TITLE
compose: fixes

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
@andreimatei this should address the issue you had in https://github.com/cockroachdb/cockroach/pull/44127#issuecomment-580397538.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47720#-:-M5OUOYnDVuB6ajAy5qB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by andreimatei** [comment]
thanks!

**Pull request merged**
