### PR TITLE
kv: Get rid of NoopRequests

### LINKED ISSUE #12142: kv: Get rid of NoopRequests
Opening a separate issue to avoid losing track of @petermattis's comment on https://github.com/cockroachdb/cockroach/issues/11195#issuecomment-264659110, suggesting that we may want to get rid of NoopRequests as a performance optimization.

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #12142. @tschottdorf  @andreimatei. 

I still don't know how to add some test for this, any reference would be appreciate.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Wow, glad to see no more changes were necessary! For testing, I would suggest first fixing up `TestTruncate` (which must certainly fail right now) and adding a `TestCombine` next to it.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/kv/dist_sender.go, line 677 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KnfLqDqXBDsAwsN2meM:-KnfKBLKurgTWrZFbVNv:byizglg) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b4a19e104eee2ce40d4ff43da0a094d923d376/pkg/kv/dist_sender.go#L677)):*
> ```Go
> 	// BatchResponse when finished.
> 	var responseChs []chan response
> 	var be roachpb.BatchResponse
> ```

Doesn't seem like you need this variable?

---

*[pkg/roachpb/batch.go, line 234 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KnfKRKZrEf4AlhSY607:-KnfKRK_shjHBhM3FRjm:bb3j816) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b4a19e104eee2ce40d4ff43da0a094d923d376/pkg/roachpb/batch.go#L234)):*
> ```Go
> func (br *BatchResponse) Combine(otherBatch *BatchResponse, positions []int) error {
> 	for i, l := 0, len(otherBatch.Responses); i < l; i++ {
> 		if reflect.DeepEqual(br.Responses[positions[i]], ResponseUnion{}) {
> ```

You can't use `reflect` here. Can't you compare `br.Responses[positions[i]] == ResponseUnion{}` directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-:-KnfMCvH6Sa9Ncc8U4LF:b-iwaj1k)*

**Comment by tschottdorf** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by petermattis** [comment]
Nice! This is as simple as I was hoping.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/kv/batch.go, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KngIoHrYti5HQN5iwO8:-KngIoHrYti5HQN5iwO9:buce4c5) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b4a19e104eee2ce40d4ff43da0a094d923d376/pkg/kv/batch.go#L104)):*
> ```Go
> 	var positions []int
> 	truncBA = ba
> 	truncBA.Requests = make([]roachpb.RequestUnion, 0)
> ```

I think you can remove this line now. The default value of `nil` for `truncBA.Requests` is equivalent to the 0-length slice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-:-KngJCF66VcM-T6ue54I:b-gz6rhu)*

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/kv/batch.go, line 121 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KniyHrjuiHb5oJeY1qH:-KniyHrjuiHb5oJeY1qI:b-6rzvsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1561da9709aca2b19e9dc4bdeb876cc4fdf7606/pkg/kv/batch.go#L121)):*
> ```Go
> 		}
> 		if err != nil {
> 			return roachpb.BatchRequest{}, []int{}, err
> ```

return `nil`.

---

*[pkg/kv/dist_sender.go, line 1003 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KniydYgGh1PDRRn2pQn:-KniydYgGh1PDRRn2pQo:b-meggja) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1561da9709aca2b19e9dc4bdeb876cc4fdf7606/pkg/kv/dist_sender.go#L1003)):*
> ```Go
> 				return response{pErr: pErr}
> 			}
> 			if reply != nil {
> ```

Can `reply` ever be `nil` here when `pErr == nil`? I would be surprised.

---

*[pkg/roachpb/batch.go, line 233 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-Kniz3eQ4NX8IznvS_cG:-Kniz3eQ4NX8IznvS_cH:b-xmee59) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1561da9709aca2b19e9dc4bdeb876cc4fdf7606/pkg/roachpb/batch.go#L233)):*
> ```Go
> 	for i, l := 0, len(otherBatch.Responses); i < l; i++ {
> 		id := positions[i]
> 		if (ResponseUnion{}) == br.Responses[id] {
> ```

I think it would look better as `if br.Responses[id] == (ResponseUnion{}) {`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by a6802739** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/kv/batch.go, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KngIoHrYti5HQN5iwO8:-Knj9Wfy_DJ7nH_fceQ6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b4a19e104eee2ce40d4ff43da0a094d923d376/pkg/kv/batch.go#L104)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you can remove this line now. The default value of `nil` for `truncBA.Requests` is equivalent to the 0-length slice.
</blockquote></details>

Done.

---

*[pkg/kv/batch.go, line 121 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KniyHrjuiHb5oJeY1qH:-Knj9XsZ-fRDlMvmwXHt:b3ows4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1561da9709aca2b19e9dc4bdeb876cc4fdf7606/pkg/kv/batch.go#L121)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

return `nil`.
</blockquote></details>

Gotcha. 

---

*[pkg/kv/dist_sender.go, line 677 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KnfLqDqXBDsAwsN2meM:-Knj9gD2H2GHuRsQpFJu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b4a19e104eee2ce40d4ff43da0a094d923d376/pkg/kv/dist_sender.go#L677)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Doesn't seem like you need this variable?
</blockquote></details>

Done.

---

*[pkg/kv/dist_sender.go, line 1003 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KniydYgGh1PDRRn2pQn:-Knj9gvK_mphw7bBHSB1:b-piuzvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1561da9709aca2b19e9dc4bdeb876cc4fdf7606/pkg/kv/dist_sender.go#L1003)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Can `reply` ever be `nil` here when `pErr == nil`? I would be surprised.
</blockquote></details>

Yes, I'm also surprised. And I still don't know how to deal with this.

---

*[pkg/roachpb/batch.go, line 233 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-Kniz3eQ4NX8IznvS_cG:-Knj9uD6sl0gZSAzrEjL:b-4gor3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1561da9709aca2b19e9dc4bdeb876cc4fdf7606/pkg/roachpb/batch.go#L233)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I think it would look better as `if br.Responses[id] == (ResponseUnion{}) {`.
</blockquote></details>

Gotcha.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by a6802739** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/kv/dist_sender.go, line 1003 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KniydYgGh1PDRRn2pQn:-KnjBoExGEFXZm9oRK_Q:b-njgrs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1561da9709aca2b19e9dc4bdeb876cc4fdf7606/pkg/kv/dist_sender.go#L1003)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary><blockquote>

Yes, I'm also surprised. And I still don't know how to deal with this.
</blockquote></details>

hmm, I'm not sure, I should have some test first. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/kv/dist_sender.go, line 1003 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KniydYgGh1PDRRn2pQn:-KnjP1Znpj35ra6xEgG4:b-8xmuoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1561da9709aca2b19e9dc4bdeb876cc4fdf7606/pkg/kv/dist_sender.go#L1003)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary><blockquote>

hmm, I'm not sure, I should have some test first. 
</blockquote></details>

Where does it fail during tests? Perhaps a test is doing illegal things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by tamird** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/kv/batch.go, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KnkAyOxM5YS6PkQaap9:-KnkAyOxM5YS6PkQaapA:b-mgqnse) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b5f97d6115d16d95dc02178549bd399f0d753f/pkg/kv/batch.go#L32)):*
> NoopRequest

looks like a lie

---

*[pkg/kv/batch.go, line 102 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-Knk5MJmR5OJE37hB80G:-Knk5MJmR5OJE37hB80H:b8llfrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/11197fddf43a8cafb05bafec5147eaec3308e23d/pkg/kv/batch.go#L102)):*
> ```Go
> 
> 	var numNoop int
> 	truncBA := ba
> ```

why did this need to change?

---

*[pkg/kv/batch.go, line 103 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-Knk5YUvp15nE1U8kyt-:-Knk5YUvp15nE1U8kyt0:b-42b15c) ([raw file](https://github.com/cockroachdb/cockroach/blob/11197fddf43a8cafb05bafec5147eaec3308e23d/pkg/kv/batch.go#L103)):*
> ```Go
> 	var numNoop int
> 	truncBA := ba
> 	truncBA.Requests = make([]roachpb.RequestUnion, len(ba.Requests))
> ```

it might still be better to pre-allocate this with `len(ba.Requests)` capacity, no?


`truncBA.Requests = make([]roachpb.RequestUnion, 0, len(ba.Requests))`

---

*[pkg/kv/dist_sender.go, line 677 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KnkAkYl4KL139Ih72Ck:-KnkAkYl4KL139Ih72Cl:b-jgnj5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b5f97d6115d16d95dc02178549bd399f0d753f/pkg/kv/dist_sender.go#L677)):*
> ```Go
> 	// BatchResponse when finished.
> 	var responseChs []chan response
> ```

this addition looks unrelated

---

*[pkg/roachpb/batch.go, line 225 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KnkAb1DGrZdX55Xvh4Q:-KnkAb1DGrZdX55Xvh4R:b-h4nfuu) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b5f97d6115d16d95dc02178549bd399f0d753f/pkg/roachpb/batch.go#L225)):*
> ```Go
> }
> 
> // Combine implements the Combinable interface. It combines each slot of the
> ```

I think this comment is mostly lies now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/kv/batch.go, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KnkAyOxM5YS6PkQaap9:-KnkCAGeffvpWk3l2boK:b-rkgn6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b5f97d6115d16d95dc02178549bd399f0d753f/pkg/kv/batch.go#L32)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> NoopRequest

looks like a lie
</blockquote></details>

Let's hold off on the commentary review for now and get it functionally right. I imagine we'll do the comments and documentation at the end.

---

*[pkg/kv/batch.go, line 102 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-Knk5MJmR5OJE37hB80G:-KnkC8wJTwXTGf82DcAH:b-667hb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/11197fddf43a8cafb05bafec5147eaec3308e23d/pkg/kv/batch.go#L102)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why did this need to change?
</blockquote></details>

Yeah, that seems spurious.

---

*[pkg/kv/batch.go, line 103 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-Knk5YUvp15nE1U8kyt-:-KnkBwkykiD21Nqkg0Sy:b-efkigq) ([raw file](https://github.com/cockroachdb/cockroach/blob/11197fddf43a8cafb05bafec5147eaec3308e23d/pkg/kv/batch.go#L103)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

it might still be better to pre-allocate this with `len(ba.Requests)` capacity, no?


`truncBA.Requests = make([]roachpb.RequestUnion, 0, len(ba.Requests))`
</blockquote></details>

Yep, current code looks wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/kv/batch.go, line 103 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-Knk5YUvp15nE1U8kyt-:-KnkLyfxgVn_-lO0-gw1:b2vujs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/11197fddf43a8cafb05bafec5147eaec3308e23d/pkg/kv/batch.go#L103)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Yep, current code looks wrong.
</blockquote></details>

What's wrong with the current code? Using `len(ba.Requests)` will be excessive in some cases (e.g. a timeseries write where each `MergeRequest` goes to a different range). I think we shouldn't over think this and just let the slice expand as necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by tschottdorf** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/kv/batch.go, line 103 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-Knk5YUvp15nE1U8kyt-:-Knl4nJwMfWdki9PZH7O:b-y4wpgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/11197fddf43a8cafb05bafec5147eaec3308e23d/pkg/kv/batch.go#L103)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What's wrong with the current code? Using `len(ba.Requests)` will be excessive in some cases (e.g. a timeseries write where each `MergeRequest` goes to a different range). I think we shouldn't over think this and just let the slice expand as necessary.
</blockquote></details>

Sorry, it's not wrong, looked at the wrong side of the diff. Agree with just letting it grow though would be good to make a note. Many requests are going to go to a single range and a little bit could be gained in the common path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by a6802739** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/kv/batch.go, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KnkAyOxM5YS6PkQaap9:-KnlC6daznxGYklLL6V3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b5f97d6115d16d95dc02178549bd399f0d753f/pkg/kv/batch.go#L32)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Let's hold off on the commentary review for now and get it functionally right. I imagine we'll do the comments and documentation at the end.
</blockquote></details>

Done.

---

*[pkg/kv/dist_sender.go, line 1003 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KniydYgGh1PDRRn2pQn:-KnlB7fRP8ZlF518USK0:b-nynzqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1561da9709aca2b19e9dc4bdeb876cc4fdf7606/pkg/kv/dist_sender.go#L1003)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Where does it fail during tests? Perhaps a test is doing illegal things.
</blockquote></details>

For test `TestSendRPCOrder`, it will panic from `unwrappedReply := br.Responses[0].GetInner()`, the panic is `interface conversion: interface is nil, not roachpb.Response`, Maybe it's just a `ResponseUnion{}`, I don't know how does this happen. And I wonder could i use some command to just run `TestSendRPCOrder`.

---

*[pkg/kv/dist_sender.go, line 677 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KnkAkYl4KL139Ih72Ck:-KnlB1O4PLWNRoWeW1S8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b5f97d6115d16d95dc02178549bd399f0d753f/pkg/kv/dist_sender.go#L677)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this addition looks unrelated
</blockquote></details>

Done.

---

*[pkg/roachpb/batch.go, line 234 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KnfKRKZrEf4AlhSY607:-KnlC0LRtgW5stgdo0M0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63b4a19e104eee2ce40d4ff43da0a094d923d376/pkg/roachpb/batch.go#L234)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

You can't use `reflect` here. Can't you compare `br.Responses[positions[i]] == ResponseUnion{}` directly?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/kv/dist_sender.go, line 1003 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744#-KniydYgGh1PDRRn2pQn:-KnlFaPCTD_qqOiN8E-h:bk08cgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1561da9709aca2b19e9dc4bdeb876cc4fdf7606/pkg/kv/dist_sender.go#L1003)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary><blockquote>

For test `TestSendRPCOrder`, it will panic from `unwrappedReply := br.Responses[0].GetInner()`, the panic is `interface conversion: interface is nil, not roachpb.Response`, Maybe it's just a `ResponseUnion{}`, I don't know how does this happen. And I wonder could i use some command to just run `TestSendRPCOrder`.
</blockquote></details>

`make test PKG=./pkg/kv TESTS=TestSendRPCOrder TESTFLAGS='-v'`. Also take a look at the test. Maybe it is just returning something illegal and it didn't matter before but now does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16744)*

**Comment by a6802739** [comment]
@tschottdorf , it seems it still will fail on the test `TestSessionTrace` in the `sql` package.

The test error if just like:

```
E170706 18:13:17.480236 98 storage/replica_proposal.go:470  [n1,s1,r1/1:/M{in-ax}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
=== RUN   TestSessionTrace/SessionTrace/TracingOff/node-0
=== RUN   TestSessionTrace/SessionTrace/TracingOff/node-1
=== RUN   TestSessionTrace/SessionTrace/TracingOff/node-2
=== RUN   TestSessionTrace/SessionTrace/TracingOn
E170706 18:13:18.158858 1984 storage/queue.go:657  [replicate,n1,s1,r1/1:/{Min-System/}] range requires a replication change, but lacks a quorum of live replicas (0/1)
E170706 18:13:18.164374 1971 storage/replica_proposal.go:470  [n1,s1,r2/1:/{System/-Max}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
=== RUN   TestSessionTrace/SessionTrace/TracingOn/node-0
=== RUN   TestSessionTrace/SessionTrace/TracingOn/node-1
=== RUN   TestSessionTrace/SessionTrace/TracingOn/node-2
=== RUN   TestSessionTrace/ShowTraceFor
=== RUN   TestSessionTrace/ShowTraceFor/TracingOff
E170706 18:13:18.815192 3748 storage/replica_proposal.go:470  [n1,s1,r2/1:/{System/-Max}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
=== RUN   TestSessionTrace/ShowTraceFor/TracingOff/node-0
=== RUN   TestSessionTrace/ShowTraceFor/TracingOff/node-1
=== RUN   TestSessionTrace/ShowTraceFor/TracingOff/node-2
=== RUN   TestSessionTrace/ShowTraceFor/TracingOn
E170706 18:13:19.615309 5671 storage/queue.go:657  [replicate,n1,s1,r1/1:/{Min-System/}] range requires a replication change, but lacks a quorum of live replicas (0/1)
E170706 18:13:19.635311 5505 storage/replica_proposal.go:470  [n1,s1,r3/1:/{System/tsd-Max}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
E170706 18:13:19.640588 5640 storage/replica_proposal.go:470  [n1,s1,r4/1:/{System/tse-Max}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
=== RUN   TestSessionTrace/ShowTraceFor/TracingOn/node-0
=== RUN   TestSessionTrace/ShowTraceFor/TracingOn/node-1
=== RUN   TestSessionTrace/ShowTraceFor/TracingOn/node-2
test logs left over in: /var/folders/72/byjy11cs0dj_z3rjtxnj_nn00000gn/T/logTestSessionTrace230770652
--- FAIL: TestSessionTrace (2.83s)
	test_log_scope.go:80: test logs captured to: /var/folders/72/byjy11cs0dj_z3rjtxnj_nn00000gn/T/logTestSessionTrace230770652
	test_log_scope.go:63: use -show-logs to present logs inline
    --- FAIL: TestSessionTrace/SessionTrace (1.37s)
        --- FAIL: TestSessionTrace/SessionTrace/TracingOff (0.72s)
            --- FAIL: TestSessionTrace/SessionTrace/TracingOff/node-0 (0.06s)
            	trace_test.go:155: pq: duplicate span 3994486636842284457
            --- PASS: TestSessionTrace/SessionTrace/TracingOff/node-1 (0.03s)
            --- FAIL: TestSessionTrace/SessionTrace/TracingOff/node-2 (0.04s)
            	trace_test.go:155: pq: duplicate span 791668636436196151
        --- FAIL: TestSessionTrace/SessionTrace/TracingOn (0.64s)
            --- PASS: TestSessionTrace/SessionTrace/TracingOn/node-0 (0.02s)
            --- FAIL: TestSessionTrace/SessionTrace/TracingOn/node-1 (0.03s)
            	trace_test.go:155: pq: duplicate span 7682119861234975851
            --- FAIL: TestSessionTrace/SessionTrace/TracingOn/node-2 (0.03s)
            	trace_test.go:155: pq: duplicate span 8591574203061632380
    --- FAIL: TestSessionTrace/ShowTraceFor (1.46s)
        --- FAIL: TestSessionTrace/ShowTraceFor/TracingOff (0.81s)
            --- PASS: TestSessionTrace/ShowTraceFor/TracingOff/node-0 (0.03s)
            --- FAIL: TestSessionTrace/ShowTraceFor/TracingOff/node-1 (0.09s)
            	trace_test.go:155: pq: duplicate span 3875319386712636620
            --- FAIL: TestSessionTrace/ShowTraceFor/TracingOff/node-2 (0.04s)
            	trace_test.go:155: pq: duplicate span 5427151336124731356
        --- FAIL: TestSessionTrace/ShowTraceFor/TracingOn (0.66s)
            --- PASS: TestSessionTrace/ShowTraceFor/TracingOn/node-0 (0.01s)
            --- FAIL: TestSessionTrace/ShowTraceFor/TracingOn/node-1 (0.03s)
            	trace_test.go:155: pq: duplicate span 6308042347559520454
            --- FAIL: TestSessionTrace/ShowTraceFor/TracingOn/node-2 (0.04s)
            	trace_test.go:155: pq: duplicate span 5403986949324466315
FAIL
```

I don't know why this happen, it seems the `NoopRequest` has nothing to do with this test?

**Comment by tschottdorf** [comment]
I'll take a look, @a6802739!

**Comment by tschottdorf** [comment]
@a6802739 the PR actually passes rebase -- but I found some other problems and there was a lot of code movement in this one making proper review hard -- thanks for doing all the hard work, though! I'll bring this over the finish line in https://github.com/cockroachdb/cockroach/pull/16946.

**Pull request closed without merging**
