### PR TITLE
distsql: Implement diagramCellType for AlgebraicSetOpSpec

### PR DESCRIPTION
**Pull request by abhimadan**
Release note: None

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21556#-L3ABpU0E2XVlDNcXOCW:-L3ABpU0E2XVlDNcXOCX:b-rdqwh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f388dd03531d33a8cd93882c123ecfcf49103c2f/pkg/sql/distsqlrun/flow_diagram.go#L197)):*
> ```Go
> 		details = append(details, aso.Ordering.diagramString())
> 	}
> 	return "AlgebraicSetOp", details
> ```

I'd switch on the op type (which currently is just `except all` and then output that, since the diagram saying `AlgebraicSetOp` is confusing when it should only really happen when they run an `EXCEPT ALL`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21556#-:-L3AC-k0j9Es5HRlbllM:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21556#-L3ACi6gkEI3UDOo_Yma:-L3ACi6gkEI3UDOo_Ymb:b-tt0ueo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f388dd03531d33a8cd93882c123ecfcf49103c2f/pkg/sql/distsqlrun/flow_diagram.go#L191)):*
> ```Go
> }
> 
> func (aso *AlgebraicSetOpSpec) summary() (string, []string) {
> ```

please comment with `summary implements the diagramCellType interface.` here and on the other implementations missing it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21556)*

**Comment by arjunravinarayan** [comment]
*[pkg/sql/distsqlrun/flow_diagram.go, line 191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21556#-L3ACi6gkEI3UDOo_Yma:-L3ADk6Wue4NbJGbBEgt:biz6yf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f388dd03531d33a8cd93882c123ecfcf49103c2f/pkg/sql/distsqlrun/flow_diagram.go#L191)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please comment with `summary implements the diagramCellType interface.` here and on the other implementations missing it.
</blockquote></details>

@abhimadan not your fault that we've slipped on this all over this file, but since you're in this part of the codebase, it would be great if you could help clean it up as @andreimatei suggests! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21556)*

**Comment by abhimadan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21556#-L3ACi6gkEI3UDOo_Yma:-L3AMllANUBpMOgdGaxJ:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/f388dd03531d33a8cd93882c123ecfcf49103c2f/pkg/sql/distsqlrun/flow_diagram.go#L191)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

@abhimadan not your fault that we've slipped on this all over this file, but since you're in this part of the codebase, it would be great if you could help clean it up as @andreimatei suggests! :)
</blockquote></details>

Done!

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21556#-L3ABpU0E2XVlDNcXOCW:-L3AMonWim5U7DJrpADu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f388dd03531d33a8cd93882c123ecfcf49103c2f/pkg/sql/distsqlrun/flow_diagram.go#L197)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I'd switch on the op type (which currently is just `except all` and then output that, since the diagram saying `AlgebraicSetOp` is confusing when it should only really happen when they run an `EXCEPT ALL`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21556)*

**Pull request merged**
