### PR TITLE
roachpb,sql.ui: remove Opt field from StatementStatisticsKey

### LINKED ISSUE #68077: sql: remove `opt` field from Statement Statistics
`opt` is always true and has been for a couple of releases now. It's not providing much value to us other than taking up much space.

Note: we should remove it both from the [protobuf messages](https://github.com/cockroachdb/cockroach/blob/518f67c41e4c4810783cd668a446c47f44719a36/pkg/roachpb/app_stats.proto#L177) as well as [system table](https://github.com/cockroachdb/cockroach/blob/5c1a4413fc5ff92b9b0faec52acf2d852fb858ff/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go#L57).

cc: @yuzefovich

### PR DESCRIPTION
**Pull request by Azhng**
Resolves #68077

Release note: None

### CODE REVIEW

**Comment by Azhng** [comment]
Should we try to get this in for this release? Or we should wait for after the branch cut?

**Comment by maryliag** [comment]
wait for after the branch cut

**Review by matthewtodd — APPROVED** [review]
Looks good to me! I love the smell of deleted code in the morning.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69597#-:-Mj-nulT-UNt9FHGJ0Fp:bnmgvj4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69597#-Mj-o-noBh7G4COnc5V-):*
nit: It might be worth explicitly saying here why this field is safe to delete?

**Comment by Azhng** [comment]
TFTR!

bors r=matthewtodd

**Comment by Azhng** [comment]
Hmm bors flaked, try again 

bors r=matthewtodd

**Pull request merged**
