### PR TITLE
build: upgrade to ubuntu focal in builder images

### LINKED ISSUE #59432: Update builder docker image to a newer base ubuntu LTS version
The builder docker image is currently based on Ubuntu Xenial, which ends standard support in April this year. We want to upgrade to at least Bionic Beaver, though skipping to Focal Fossa would be good.

[Related conversation in slack](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1611624803040100).

### PR DESCRIPTION
**Pull request by rickystewart**
This necessitated a few cascading changes:

* `crosstool-ng` v1.23 doesn't build out of the box on the latest
  Ubuntu, so I had to update to 1.24.
* The `DEFCONFIG` format isn't back-compatible between minor versions of
  `crosstool-ng`, so I had to deal with that as well. Luckily,
  `crosstool-ng` has an upgrade path. I used the *old* builder image
  with v1.23 to run `ct-ng defconfig` to generate `.config` files for
  the different build configurations, and then used the *new* version to
  run `ct-ng upgradeconfig` to produce updated `.config`s. I then
  updated the contents of the `.defconfig`s in-tree and renamed the
  files accordingly. As a result we no longer have to run `defconfig`
  during the build. If we need to update to a newer `crosstool-ng` at
  some point in the future, we'll have to follow a similar procedure
  (i.e. we'll have to run `ct-ng upgradeconfig` once for each of these
  configs).
  Ref: http://crosstool-ng.github.io/docs/configuration/
* Upgrade to the latest `clang`, and to a compatible `llvm` for the
  `msan` build. The directory structure has changed slightly, so update
  some of the build commands to account for that.

Also, make corresponding changes in `build/bazelbuilder` so there isn't
skew between the two images.

Fixed #59432.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Ah, [my build failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2628833&buildTypeId=Cockroach_UnitTests_CompileBuilds&tab=buildLog) right after I sent this review out *facepalm*.

I'll recall this while I resolve that.

**Review by jlinder — COMMENTED** [review]
This is looking good. A question: Have you build binaries for all the supported platforms using the new builder image? Do they run?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59562#-:-MSdIL_w7q7r7LmOu0e7:b31le1y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[build/bazelbuilder/Dockerfile, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59562#-MSdMeCP1xXenZjhB4VB:-MSdMeCP1xXenZjhB4VC:b-svz8np) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db31519fb61a8192face620c9f969b59423629d/build/bazelbuilder/Dockerfile#L4)):*
> ```
> DEBIAN_FRONTEND=noninteractive
> ```

If we're adding this here, it seems it should be added to all `apt-get` uses that may present dialogs in the file (and in the build/builder/Dockerfile).

**Comment by jlinder** [comment]
> This is looking good. A question: Have you build binaries for all the supported platforms using the new builder image? Do they run?

I just remembered that we compile all the builds in the [Compile Builds](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_CompileBuilds?mode=builds#all-projects) build configuration as part of CI. So they were built there, but the mac and windows builds weren't run.

**Comment by rickystewart** [comment]
I've validated the Linux and Darwin binaries work. I'm going to test the Windows binary next.

**Comment by rickystewart** [comment]
Windows also works, so all the binaries are good.

**Comment by jlinder** [comment]
I imagine the larger task of figuring out how to build the binaries overshadowed this suggestion. What are your thoughts on this?

> _[build/bazelbuilder/Dockerfile, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59562#-MSdMeCP1xXenZjhB4VB:-MSdMeCP1xXenZjhB4VC:b-svz8np) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db31519fb61a8192face620c9f969b59423629d/build/bazelbuilder/Dockerfile#L4)):_
> 
> > ```
> > DEBIAN_FRONTEND=noninteractive
> > ```
> 
> If we're adding this here, it seems it should be added to all `apt-get` uses that may present dialogs in the file (and in the build/builder/Dockerfile).

**Comment by rickystewart** [comment]
Sure, done. (It doesn't make a difference here so I won't rebuild the images, we can just leave it for convenience for the next person who has to build them.)

**Review by jlinder — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59562#-:-MSinDa38uLGTIEjLQrG:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
Thanks!

bors r+

**Pull request merged**
