### PR TITLE
security: new sub-package for certificate/key paths  (cli refactor sequence 1/n)

### PR DESCRIPTION
**Pull request by knz**
Informs [82075](https://github.com/cockroachdb/cockroach/issues/82075).
PR split from #82020 to ease review.

### CODE REVIEW

**Review by catj-cockroach — APPROVED** [review]
Looks good to me!

> Reviewed 2 of 2 files at r1, 9 of 9 files at r2, 8 of 8 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82068#-:-N3KjA3IBRqxg87-pVVs:b9j9n3q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[`pkg/security/certnames/certnames.go` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82068#-N3KgzQy9kKozPW0W5zJ:-N3KgzQy9kKozPW0W5zK:b-5zf2no) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3837f5fe99e4a7a4f07a84650d0dd4dd8dc1dd/pkg/security/certnames/certnames.go#L25)):*
> ```Go
> 
> // IsCertificateFile returns true if the file name looks like a certificate file.
> func IsCertificateFile(filename string) bool {
> ```

nit: I would argue this should be `IsCertificateFilename` rather than `IsCertificateFile` unless we're checking that the file has a PEM header.
___
*[`pkg/security/certnames/locator.go` line 22 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82068#-N3KiGSADqUeh0o6Vmqm:-N3KiGSADqUeh0o6Vmqn:b-gt459y) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa8d939dadd704e20be8a17b09608b4091b7811/pkg/security/certnames/locator.go#L22)):*
> ```Go
> 
> // A Locator provides locations to certificates.
> type Locator struct {
> ```

This is more for my curiosity rather than a request, but would it be difficult to move the certificate fallback logic into Locator?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82068)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach and @otan)

___
*[`pkg/security/certnames/certnames.go` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82068#-N3KgzQy9kKozPW0W5zJ:-N3KlMth3-fPtzwhW6qD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3837f5fe99e4a7a4f07a84650d0dd4dd8dc1dd/pkg/security/certnames/certnames.go#L25)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

nit: I would argue this should be `IsCertificateFilename` rather than `IsCertificateFile` unless we're checking that the file has a PEM header.
</blockquote></details>

Done.
___
*[`pkg/security/certnames/locator.go` line 22 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82068#-N3KiGSADqUeh0o6Vmqm:-N3KlUIu26zoSoeOBSZA:baho20s) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfa8d939dadd704e20be8a17b09608b4091b7811/pkg/security/certnames/locator.go#L22)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

This is more for my curiosity rather than a request, but would it be difficult to move the certificate fallback logic into Locator?
</blockquote></details>

This new package is only interested in defining paths. In particular,  it does not actually access the filesystem.

I think to do what you suggest we'll want to extract the fallback logic from CertificateManager into an actuall file access layer. It's a good idea (and on the way to solve #82075) but it's out of scope on the sequence of PRs that I'm currently working on (towards solving #81882).

**Comment by knz** [comment]
(NB: Holding off on merging this despite the review approval, since we can't merge intermediate PRs in a sequence without dropping the entire sequence off github.)

**Review by otan — APPROVED** [review]

**Review by catj-cockroach — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82068)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach)

**Review by catj-cockroach — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82068)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Pull request merged**
