### PR TITLE
builtins: add in unimplemented spatial builtins

### PR DESCRIPTION
**Pull request by otan**
This adds telemetry to remaining unused functions, as well as displaying
the issue number when someone attempts to use an unimplemented function.

Also changed the wording of the error message to be a little more
friendly.

Release justification: low risk, high benefit changes

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
@sumeerbhola mind taking a look at this today?
the metrics would be nice to get in before the next cut.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53556#-:-MG4O0Xo0VNRCEd8dG19:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
bors r=sumeerbhola

tftr!

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
sorry, more and more builtins getting in.

bors r=sumeerbhola

**Comment by otan** [comment]
one more builtin from open source...

bors r-

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
