### PR TITLE
sql: deflake TestConcurrentSchemaChanges

### LINKED ISSUE #129132: pkg/sql/schemachanger/schemachanger_test: TestConcurrentSchemaChanges failed
pkg/sql/schemachanger/schemachanger_test.TestConcurrentSchemaChanges [failed](https://tanzanite.cluster.engflow.com/invocations/default/a8072aa6-f595-4364-abc8-ea3705495149?testReportRun=10&testReportShard=24&testReportAttempt=1#targets-Ly9wa2cvc3FsL3NjaGVtYWNoYW5nZXI6c2NoZW1hY2hhbmdlcl90ZXN0) on release-24.1 @ [957fad03d6876049dc0faef2217858e5ea92f5ca](https://github.com/cockroachdb/cockroach/commits/957fad03d6876049dc0faef2217858e5ea92f5ca):

```
    schemachanger_test.go:760: RENAME TABLE TO t_88
    schemachanger_test.go:760: RENAME TABLE TO t_89
    schemachanger_test.go:787: Parent database or schema or table is renamed or column already exists; skipping this column addition.
    schemachanger_test.go:787: Parent database or schema or table is renamed or column already exists; skipping this column addition.
    schemachanger_test.go:732: RENAME SCHEMA TO testsc_90
    schemachanger_test.go:783: ADD COLUMN col_93 TO testdb_76.testsc_90.t_89
    schemachanger_test.go:783: ADD COLUMN col_96 TO testdb_76.testsc_90.t_89
    schemachanger_test.go:807: DROP COLUMN col_93 FROM testdb_76.testsc_90.t_89
    schemachanger_test.go:838: Parent database or schema or table is renamed or column is dropped or index already exists; skipping this index creation.
    schemachanger_test.go:760: RENAME TABLE TO t_98
    schemachanger_test.go:760: RENAME TABLE TO t_100
    schemachanger_test.go:783: ADD COLUMN col_101 TO testdb_76.testsc_90.t_100
    schemachanger_test.go:811: Parent database or schema or table is renamed; skipping this column removal.
    schemachanger_test.go:698: DROP DATABASE testdb_76
    schemachanger_test.go:739: Parent database is renamed; skipping this schema renaming.
    schemachanger_test.go:698: DROP DATABASE testdb_76
    schemachanger_test.go:698: DROP DATABASE testdb_76
    schemachanger_test.go:783: ADD COLUMN col_106 TO testdb_76.testsc_90.t_100
    schemachanger_test.go:807: DROP COLUMN col_106 FROM testdb_76.testsc_90.t_100
    schemachanger_test.go:783: ADD COLUMN col_110 TO testdb_76.testsc_90.t_100
    schemachanger_test.go:762: DROP TABLE t_109
    schemachanger_test.go:783: ADD COLUMN col_112 TO testdb_76.testsc_90.t_100
    schemachanger_test.go:807: DROP COLUMN col_112 FROM testdb_76.testsc_90.t_100
    schemachanger_test.go:783: ADD COLUMN col_116 TO testdb_76.testsc_90.t_100
    schemachanger_test.go:838: Parent database or schema or table is renamed or column is dropped or index already exists; skipping this index creation.
    schemachanger_test.go:807: DROP COLUMN col_116 FROM testdb_76.testsc_90.t_100
    schemachanger_test.go:734: DROP SCHEMA TO testsc_90
    schemachanger_test.go:783: ADD COLUMN col_118 TO testdb_76.testsc_90.t_100
    schemachanger_test.go:807: DROP COLUMN col_118 FROM testdb_76.testsc_90.t_100
    schemachanger_test.go:698: DROP DATABASE testdb_76
    schemachanger_test.go:838: Parent database or schema or table is renamed or column is dropped or index already exists; skipping this index creation.
    schemachanger_test.go:783: ADD COLUMN col_122 TO testdb_76.testsc_90.t_100
    schemachanger_test.go:698: DROP DATABASE testdb_76
    schemachanger_test.go:709: RENAME DATABASE TO testdb_125
    schemachanger_test.go:709: RENAME DATABASE TO testdb_126
    schemachanger_test.go:679: rename-tbl-worker encounters error driver: bad connection; signal to main routine and finish working
    schemachanger_test.go:675: rename-schema-worker is signaled to finish work
    schemachanger_test.go:675: rename-db-worker is signaled to finish work
    schemachanger_test.go:675: add-column-worker is signaled to finish work
    schemachanger_test.go:675: drop-index-worker is signaled to finish work
    schemachanger_test.go:675: create-index-worker is signaled to finish work
    schemachanger_test.go:675: drop-column-worker is signaled to finish work
    schemachanger_test.go:869: 
        	Error Trace:	pkg/sql/schemachanger/schemachanger_test_test/pkg/sql/schemachanger/schemachanger_test.go:869
        	Error:      	Received unexpected error:
        	            	driver: bad connection
        	Test:       	TestConcurrentSchemaChanges
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestConcurrentSchemaChanges2973834955
--- FAIL: TestConcurrentSchemaChanges (40.92s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=10</code>
 - <code>shard=24</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestConcurrentSchemaChanges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41392

### LINKED ISSUE #129220: pkg/sql/schemachanger/schemachanger_test: TestConcurrentSchemaChanges failed
pkg/sql/schemachanger/schemachanger_test.TestConcurrentSchemaChanges [failed](https://tanzanite.cluster.engflow.com/invocations/default/32a1e35a-ff33-497c-aca7-cf6266f198db?testReportRun=12&testReportShard=22&testReportAttempt=1#targets-Ly9wa2cvc3FsL3NjaGVtYWNoYW5nZXI6c2NoZW1hY2hhbmdlcl90ZXN0) on master @ [1993fc04b5116f20f4814d637c7ce87b003687e4](https://github.com/cockroachdb/cockroach/commits/1993fc04b5116f20f4814d637c7ce87b003687e4):

```
    schemachanger_test.go:783: ADD COLUMN col_231 TO testdb_169.testsc_222.t_156
    schemachanger_test.go:762: DROP TABLE t_233
    schemachanger_test.go:760: RENAME TABLE TO t_234
    schemachanger_test.go:783: ADD COLUMN col_236 TO testdb_169.testsc_222.t_234
    schemachanger_test.go:838: Parent database or schema or table is renamed or column is dropped or index already exists; skipping this index creation.
    schemachanger_test.go:734: DROP SCHEMA TO testsc_222
    schemachanger_test.go:783: ADD COLUMN col_241 TO testdb_169.testsc_222.t_234
    schemachanger_test.go:807: DROP COLUMN col_241 FROM testdb_169.testsc_222.t_234
    schemachanger_test.go:783: ADD COLUMN col_244 TO testdb_169.testsc_222.t_234
    schemachanger_test.go:830: CREATE INDEX idx_247 ON testdb_169.testsc_222.t_234(col_244)
    schemachanger_test.go:732: RENAME SCHEMA TO testsc_248
    schemachanger_test.go:787: Parent database or schema or table is renamed or column already exists; skipping this column addition.
    schemachanger_test.go:732: RENAME SCHEMA TO testsc_249
    schemachanger_test.go:807: DROP COLUMN col_244 FROM testdb_169.testsc_222.t_234
    schemachanger_test.go:734: DROP SCHEMA TO testsc_249
    schemachanger_test.go:767: Parent database or schema is renamed; skipping this table renaming.
    schemachanger_test.go:783: ADD COLUMN col_254 TO testdb_169.testsc_249.t_234
    schemachanger_test.go:783: ADD COLUMN col_258 TO testdb_169.testsc_249.t_234
    schemachanger_test.go:830: CREATE INDEX idx_259 ON testdb_169.testsc_249.t_234(col_254)
    schemachanger_test.go:830: CREATE INDEX idx_261 ON testdb_169.testsc_249.t_234(col_258)
    schemachanger_test.go:856: DROP INDEX idx_259 FROM testdb_169.testsc_249.t_234
    schemachanger_test.go:732: RENAME SCHEMA TO testsc_262
    schemachanger_test.go:807: DROP COLUMN col_254 FROM testdb_169.testsc_249.t_234
    schemachanger_test.go:811: Parent database or schema or table is renamed; skipping this column removal.
    schemachanger_test.go:734: DROP SCHEMA TO testsc_262
    schemachanger_test.go:787: Parent database or schema or table is renamed or column already exists; skipping this column addition.
    schemachanger_test.go:767: Parent database or schema is renamed; skipping this table renaming.
    schemachanger_test.go:783: ADD COLUMN col_270 TO testdb_169.testsc_262.t_234
    schemachanger_test.go:830: CREATE INDEX idx_275 ON testdb_169.testsc_262.t_234(col_270)
    schemachanger_test.go:783: ADD COLUMN col_276 TO testdb_169.testsc_262.t_234
    schemachanger_test.go:830: CREATE INDEX idx_277 ON testdb_169.testsc_262.t_234(col_270)
    schemachanger_test.go:679: rename-db-worker encounters error driver: bad connection; signal to main routine and finish working
    schemachanger_test.go:675: add-column-worker is signaled to finish work
    schemachanger_test.go:675: create-index-worker is signaled to finish work
    schemachanger_test.go:760: RENAME TABLE TO t_278
    schemachanger_test.go:675: rename-tbl-worker is signaled to finish work
    schemachanger_test.go:863: Parent database or schema or table is renamed or index is dropped; skipping this index removal.
    schemachanger_test.go:675: drop-index-worker is signaled to finish work
    schemachanger_test.go:734: DROP SCHEMA TO testsc_262
    schemachanger_test.go:675: rename-schema-worker is signaled to finish work
    schemachanger_test.go:811: Parent database or schema or table is renamed; skipping this column removal.
    schemachanger_test.go:675: drop-column-worker is signaled to finish work
    schemachanger_test.go:869: 
        	Error Trace:	pkg/sql/schemachanger/schemachanger_test_test/pkg/sql/schemachanger/schemachanger_test.go:869
        	Error:      	Received unexpected error:
        	            	driver: bad connection
        	Test:       	TestConcurrentSchemaChanges
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestConcurrentSchemaChanges4294690333
--- FAIL: TestConcurrentSchemaChanges (86.79s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=12</code>
 - <code>shard=22</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #129132 pkg/sql/schemachanger/schemachanger_test: TestConcurrentSchemaChanges failed [C-test-failure O-robot T-sql-foundations branch-release-24.1 release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestConcurrentSchemaChanges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41456

### LINKED ISSUE #129271: pkg/sql/schemachanger/schemachanger_test: TestConcurrentSchemaChanges failed
pkg/sql/schemachanger/schemachanger_test.TestConcurrentSchemaChanges [failed](https://mesolite.cluster.engflow.com/invocations/default/a5f604b8-33c9-4de1-8ec1-9ada80790ed2?testReportRun=1&testReportShard=19&testReportAttempt=1#targets-Ly9wa2cvc3FsL3NjaGVtYWNoYW5nZXI6c2NoZW1hY2hhbmdlcl90ZXN0) on release-24.2 @ [0d7cf33d920d3b9d4c4b204177733ea982d307eb](https://github.com/cockroachdb/cockroach/commits/0d7cf33d920d3b9d4c4b204177733ea982d307eb):

```
    schemachanger_test.go:811: Parent database or schema or table is renamed; skipping this column removal.
    schemachanger_test.go:783: ADD COLUMN col_482 TO testdb_477.testsc_446.t_478
    schemachanger_test.go:783: ADD COLUMN col_484 TO testdb_477.testsc_446.t_478
    schemachanger_test.go:783: ADD COLUMN col_485 TO testdb_477.testsc_446.t_478
    schemachanger_test.go:783: ADD COLUMN col_487 TO testdb_477.testsc_446.t_478
    schemachanger_test.go:830: CREATE INDEX idx_483 ON testdb_477.testsc_446.t_478(col_471)
    schemachanger_test.go:698: DROP DATABASE testdb_477
    schemachanger_test.go:787: Parent database or schema or table is renamed or column already exists; skipping this column addition.
    schemachanger_test.go:739: Parent database is renamed; skipping this schema renaming.
    schemachanger_test.go:739: Parent database is renamed; skipping this schema renaming.
    schemachanger_test.go:739: Parent database is renamed; skipping this schema renaming.
    schemachanger_test.go:767: Parent database or schema is renamed; skipping this table renaming.
    schemachanger_test.go:767: Parent database or schema is renamed; skipping this table renaming.
    schemachanger_test.go:767: Parent database or schema is renamed; skipping this table renaming.
    schemachanger_test.go:767: Parent database or schema is renamed; skipping this table renaming.
    schemachanger_test.go:698: DROP DATABASE testdb_477
    schemachanger_test.go:811: Parent database or schema or table is renamed; skipping this column removal.
    schemachanger_test.go:698: DROP DATABASE testdb_477
    schemachanger_test.go:783: ADD COLUMN col_502 TO testdb_477.testsc_446.t_478
    schemachanger_test.go:807: DROP COLUMN col_502 FROM testdb_477.testsc_446.t_478
    schemachanger_test.go:783: ADD COLUMN col_505 TO testdb_477.testsc_446.t_478
    schemachanger_test.go:783: ADD COLUMN col_509 TO testdb_477.testsc_446.t_478
    schemachanger_test.go:830: CREATE INDEX idx_511 ON testdb_477.testsc_446.t_478(col_505)
    schemachanger_test.go:734: DROP SCHEMA TO testsc_446
    schemachanger_test.go:811: Parent database or schema or table is renamed; skipping this column removal.
    schemachanger_test.go:783: ADD COLUMN col_512 TO testdb_477.testsc_446.t_478
    schemachanger_test.go:830: CREATE INDEX idx_514 ON testdb_477.testsc_446.t_478(col_512)
    schemachanger_test.go:698: DROP DATABASE testdb_477
    schemachanger_test.go:783: ADD COLUMN col_516 TO testdb_477.testsc_446.t_478
    schemachanger_test.go:830: CREATE INDEX idx_517 ON testdb_477.testsc_446.t_478(col_516)
    schemachanger_test.go:783: ADD COLUMN col_518 TO testdb_477.testsc_446.t_478
    schemachanger_test.go:787: Parent database or schema or table is renamed or column already exists; skipping this column addition.
    schemachanger_test.go:811: Parent database or schema or table is renamed; skipping this column removal.
    schemachanger_test.go:863: Parent database or schema or table is renamed or index is dropped; skipping this index removal.
    schemachanger_test.go:679: rename-tbl-worker encounters error driver: bad connection; signal to main routine and finish working
    schemachanger_test.go:675: rename-db-worker is signaled to finish work
    schemachanger_test.go:675: drop-index-worker is signaled to finish work
    schemachanger_test.go:675: drop-column-worker is signaled to finish work
    schemachanger_test.go:675: create-index-worker is signaled to finish work
    schemachanger_test.go:675: add-column-worker is signaled to finish work
    schemachanger_test.go:734: DROP SCHEMA TO testsc_446
    schemachanger_test.go:675: rename-schema-worker is signaled to finish work
    schemachanger_test.go:869: 
        	Error Trace:	pkg/sql/schemachanger/schemachanger_test_test/pkg/sql/schemachanger/schemachanger_test.go:869
        	Error:      	Received unexpected error:
        	            	driver: bad connection
        	Test:       	TestConcurrentSchemaChanges
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestConcurrentSchemaChanges1676792673
--- FAIL: TestConcurrentSchemaChanges (150.59s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=19</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #129220 pkg/sql/schemachanger/schemachanger_test: TestConcurrentSchemaChanges failed [C-test-failure O-robot P-1 T-sql-foundations branch-master]
- #129132 pkg/sql/schemachanger/schemachanger_test: TestConcurrentSchemaChanges failed [C-test-failure O-robot P-1 T-sql-foundations branch-release-24.1]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestConcurrentSchemaChanges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41472

### PR DESCRIPTION
**Pull request by fqazi**
Previously, TestConcurrentSchemaChanges was intermittently failing because the connection pool was not correctly being used. Some of operations like selecting if the declarative or legacy schema changer should be used were incorrectly being run on the main connection. To address this, this patch uses the dedicated connections per-thread.

Fixes: #129220
Fixes https://github.com/cockroachdb/cockroach/issues/129271
Fixes https://github.com/cockroachdb/cockroach/issues/129132

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129296)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129296#-O4qaU8zEFQK8SA89AvA:-O4qaU9--DPeohsTM6Ux:b-gvh7hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebadbce82f8b1a419c6ec151e3a678e60587303/pkg/sql/schemachanger/schemachanger_test.go#L623)):*
> ```Go
> 		JobsTestingKnobs: jobs.NewTestingKnobsWithShortIntervals(),
> 	}
> 	s, sqlDB, _ := serverutils.StartServer(t, params)
> ```

super nit: this `sqlDB` variable could be renamed to something else so it's more clear that it's the top-level one that shouldn't be reused

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129296)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129296#-O4qaU8zEFQK8SA89AvA:-O4rgmiTBWlMNseKNFIU:b-fv4xjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ebadbce82f8b1a419c6ec151e3a678e60587303/pkg/sql/schemachanger/schemachanger_test.go#L623)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: this `sqlDB` variable could be renamed to something else so it's more clear that it's the top-level one that shouldn't be reused
</blockquote></details>

Done.

Renamed this one to setupConn. The others are called workerConn to help distinguish them better.

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Comment by rafiss** [comment]
blathers backport 24.2 24.1 23.2 23.1

**Comment by rafiss** [comment]
blathers backport 24.2.1-rc

**Pull request merged**
