### PR TITLE
roachtest: improvements to `mixedversion` package

### PR DESCRIPTION
**Pull request by renatolabs**
This commit introduces a few improvements to the `mixedversion` package, the recently introduced framework for mixed-version (and mixed-binary) roachtests.

Specifically, the following improvements are made:

* Removal of `DBNode()` function: having the planner pick a database that the individual steps will connect to is insufficient in many cases and could be misleading. The idea was that the user would be able to see, from the test plan itself, what node a certain step would be interacting with. However, the reality is that steps often need to run statements on multiple different nodes, or perhaps they need to pick one node specifically (e.g., the statement needs to run on a node in the old version). For that reason, the `DBNode()` function was dropped. Instead, steps have access to a random number generator that they can use to pick an arbitrary node themselves. The random number generators are unique to each user function, meaning each test run will see the same numbers being generated even if other steps are scheduled concurrently. The numbers observed by a user function will also be the same if the seed passed to `mixedversion.Test` is the same.

* Definition of a "test context" that is available to mixed-version tests. For now, the test context includes things like which version we are upgrading (or downgrading) to and from and which nodes are running which version. This allows tests to take actions based on, for example, the number of nodes upgraded. It also allows them to run certain operations on nodes that are known to be in a specific version.

* Introduction of a `helper` struct that is passed to user-functions. For now, the helper includes functions to connect to a specific node and get the current test context. The struct will help us provide common functionality to tests so that they don't have to duplicate code.

* Log cached binary and cluster versions before executing a step. This makes it easier to understand the state of the cluster when looking at the logs of one specific step.

* Internal improvement to the test runner: instead of assuming the first step of a mixed-version test plan will start the the cockroach nodes, we now check that that is the case, providing a clear error message if/when that assumption doesn't hold anymore (instead of a cryptic connection failure error).

Epic: CRDB-19321

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
This is part of a stacked PR comprised of 3 parts. Please review them in order.

1.  #96989 **(this one!)**
2. #96990
3. #96991

**Review by herkolategan — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96989#-NOjeDPn7a2kRvno8kRi:-NOjeDPoBldNNz4dZk0J:b-405odq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac248b6ddf1ec3e544e3443f304e2906af3cdc6c/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L39)):*
> ```Go
> 	Helper struct {
> 		ctx       context.Context
> 		context   *Context
> ```

Nit: `ctx` vs. `context` might be a little confusing here, could help to make the field naming a little more descriptive.

**Review by herkolategan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96989#-:-NOvD2yuA32cdlApKEsP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

**Review by herkolategan — APPROVED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96989)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96989)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan and @smg260)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96989#-NOjeDPn7a2kRvno8kRi:-NP2w1HFDHCKeLIPmq9a:b-gvw8oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac248b6ddf1ec3e544e3443f304e2906af3cdc6c/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L39)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Nit: `ctx` vs. `context` might be a little confusing here, could help to make the field naming a little more descriptive.
</blockquote></details>

Good point, renamed to `testContext.`

**Comment by renatolabs** [comment]
bors r=herkolategan

TFTR!

**Pull request merged**
