### PR TITLE
tracing: replace RawSpan with a new proto

### PR DESCRIPTION
**Pull request by RaduBerinde**
Replacing the use of `basictracer.RawSpan` with a new `RecordedSpan` proto. The
main benefit is that we don't have to do our own encoding and decoding. This
also removes our dependency on basictracer.

Fixing some bugs in the explain trace code (n.earliest, uninitialized lastTS)
and omitting the times from the explain trace test (the second line shows
something around 0.015ms now).

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

Closes #16232, right?

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[glide.lock, line 349 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlUcnrZpnQ679yInFfN:-KlUcnrZpnQ679yInFfO:b-oi2uyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/223490433e6b0028b547ca4c171c7def6c90f3c0/glide.lock#L349)):*
> ```
> - name: github.com/opencontainers/go-digest
>   version: eaa60544f31ccf3b0653b1a118b76d33418ff41b
> - name: github.com/opentracing/basictracer-go
> ```

Good night, sweet prince.

---

*[glide.lock, line 552 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlUgKpy35GkvCeenmCY:-KlUgKpy35GkvCeenmCZ:b-6xoyno) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd438fc26bd66beaf682ad9d40da08fb63c52fb/glide.lock#L552)):*
> ```
> - name: github.com/go-sql-driver/mysql
>   version: 382e13d099fcf5f5994290892ab258fbebbdc5e3
> - name: github.com/opentracing/basictracer-go
> ```

Where do we need this one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-:-KlUgRJDJjh-mtXL1zsI:b-vljx4c)*

**Comment by RaduBerinde** [comment]
TFTR! It should, I will verify.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[glide.lock, line 552 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlUgKpy35GkvCeenmCY:-KlUhdH4wn4Ywy9mlRBm:b-b8kpxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd438fc26bd66beaf682ad9d40da08fb63c52fb/glide.lock#L552)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Where do we need this one?
</blockquote></details>

In a test where we set up a testing tracer that records stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-:-KlUhWbw1GzXkHtaoJNL:b6m30p2)*

**Comment by tamird** [comment]
Reviewed 3 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/tracing/recorded_span.proto, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVHarDSz4R6S5y0vwy:-KlVHarDSz4R6S5y0vwz:bvbyjgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/30db934b0da3bee0a1fcb44d82a6bc6a62cd77ee/pkg/util/tracing/recorded_span.proto#L33)):*
> ```protobuf
>   map<string, string> tags = 6;
>   // Time when the span was started as (UnixNano).
>   int64 start_time = 7;
> ```

while we're changing these, can we use the WKTs for duration and time here? i.e. see `serverpb/admin.proto` which contains:
```
google.protobuf.Timestamp timestamp = 1 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
```

(and the corollary `google.protobuf.Duration` also exists though we don't use it anywhere (yet!))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236)*

**Comment by tamird** [comment]
Apologies for the piecemeal review. Nice work!

Release notes should mention that this will break tracing during an upgrade.

---

Reviewed 12 of 15 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/server/node.go, line 946 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVOGBfOlb0zxs1CIAr:-KlVOGBfOlb0zxs1CIAs:b-j8srf) ([raw file](https://github.com/cockroachdb/cockroach/blob/30db934b0da3bee0a1fcb44d82a6bc6a62cd77ee/pkg/server/node.go#L946)):*
> ```Go
> 			// We don't want to do this if the operation is on the same host, in which
> 			// case everything is already part of the same recording.
> 			rec := tracing.GetRecording(sp)
> ```

nit: inline into the `if`

---

*[pkg/util/tracing/recorded_span.proto, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVLA_i6yvQBrJf4QPi:-KlVLA_i6yvQBrJf4QPj:b-xxugfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/30db934b0da3bee0a1fcb44d82a6bc6a62cd77ee/pkg/util/tracing/recorded_span.proto#L26)):*
> ```protobuf
> // over the wire for snowball tracing.
> message RecordedSpan {
>   uint64 trace_id = 1 [(gogoproto.customname) = "TraceID"];
> ```

Can you document all these fields? Perhaps some are obvious, but I think it'd be helpful.

---

*[pkg/util/tracing/recorded_span.proto, line 39 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVLEgmFiNuPlR87LjJ:-KlVLEgmFiNuPlR87LjK:bbuulkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/30db934b0da3bee0a1fcb44d82a6bc6a62cd77ee/pkg/util/tracing/recorded_span.proto#L39)):*
> ```protobuf
>   message LogRecord {
>     // Time of the log record (as UnixNano). 
>     int64 time = 1;
> ```

ditto about WKTs

---

*[pkg/util/tracing/tracer_span.go, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVOWzCzIdDNZGr8lBM:-KlVMJfbdIMx0Nqgclqi:b-qyxdt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/223490433e6b0028b547ca4c171c7def6c90f3c0/pkg/util/tracing/tracer_span.go#L445)):*
> ```Go
> 			}
> 		}
> 		// It's safe to return the same slice as long as the caller doesn't modify
> ```

no longer true? or are the types no longer identical?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-:-KlVLHdM2zv47cC1-2jB:bmtjnml)*

**Comment by andreimatei** [comment]
:lgtm:

---

Reviewed 1 of 15 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[glide.lock, line 552 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlUgKpy35GkvCeenmCY:-KlVcVj3fUvajlB2TcWB:b-vwp2x1) ([raw file](https://github.com/cockroachdb/cockroach/blob/30db934b0da3bee0a1fcb44d82a6bc6a62cd77ee/glide.lock#L552)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In a test where we set up a testing tracer that records stuff
</blockquote></details>

so what's the difference between packages listed in this `testImports` section and the others?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-:-KlVkrv3JQrx0mRrIxW7:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTR! Yeah, I will make a note of that. In fact that is already the case with my previous PR.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/server/node.go, line 946 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVOGBfOlb0zxs1CIAr:-KlVkxu9dC2Dfm3M8s1V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30db934b0da3bee0a1fcb44d82a6bc6a62cd77ee/pkg/server/node.go#L946)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: inline into the `if`
</blockquote></details>

Done.

---

*[pkg/util/tracing/recorded_span.proto, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVLA_i6yvQBrJf4QPi:-KlVkzNT_w4AMGSsfbrK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30db934b0da3bee0a1fcb44d82a6bc6a62cd77ee/pkg/util/tracing/recorded_span.proto#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Can you document all these fields? Perhaps some are obvious, but I think it'd be helpful.
</blockquote></details>

Done.

---

*[pkg/util/tracing/recorded_span.proto, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVHarDSz4R6S5y0vwy:-KlVczkqI2gZj7b-iyDN:btp6eot) ([raw file](https://github.com/cockroachdb/cockroach/blob/30db934b0da3bee0a1fcb44d82a6bc6a62cd77ee/pkg/util/tracing/recorded_span.proto#L33)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

while we're changing these, can we use the WKTs for duration and time here? i.e. see `serverpb/admin.proto` which contains:
```
google.protobuf.Timestamp timestamp = 1 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
```

(and the corollary `google.protobuf.Duration` also exists though we don't use it anywhere (yet!))
</blockquote></details>

Great!! Thanks for pointing this out!

---

*[pkg/util/tracing/tracer_span.go, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVOWzCzIdDNZGr8lBM:-KlVk9MbI0SkYNLxUYtn:b-d6hi2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/223490433e6b0028b547ca4c171c7def6c90f3c0/pkg/util/tracing/tracer_span.go#L445)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

no longer true? or are the types no longer identical?
</blockquote></details>

Right, the types don't match anymore (the new one is part of the proto we added).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-:-KlVkR9JmXXxJ-Nlir_L:b-sz8k21)*

**Comment by RaduBerinde** [comment]
Review status: 9 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

*[glide.lock, line 552 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlUgKpy35GkvCeenmCY:-KlVnXuip12f06OAuysu:b-fwn9cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/30db934b0da3bee0a1fcb44d82a6bc6a62cd77ee/glide.lock#L552)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

so what's the difference between packages listed in this `testImports` section and the others?
</blockquote></details>

can't imagine there would be a difference, its just informative

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/util/tracing/recorded_span.proto, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVHarDSz4R6S5y0vwy:-KlVnyhHzxDYeQdE7tnD:bt2lvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/30db934b0da3bee0a1fcb44d82a6bc6a62cd77ee/pkg/util/tracing/recorded_span.proto#L33)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Great!! Thanks for pointing this out!
</blockquote></details>

nice little cleanup :fire: :fire:

---

*[pkg/util/tracing/tracer_span.go, line 433 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVoCkIzSi2D3896ZZ0:-KlVoCkIzSi2D3896ZZ1:b-7lokep) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a60f6ea985e332c01f5790a30c9ee4a969d223/pkg/util/tracing/tracer_span.go#L433)):*
> ```Go
> 		case 0:
> 			// 0 is a special value for unfinished spans. Change to 1ns.
> 			rs.Duration = 1
> ```

nit: time.Nanosecond

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-:-KlVoTLtwI04eY5Cau6-:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 14 of 15 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/tracing/tracer_span.go, line 433 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236#-KlVoCkIzSi2D3896ZZ0:-KlVoko_VBYqlxqviY5d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a60f6ea985e332c01f5790a30c9ee4a969d223/pkg/util/tracing/tracer_span.go#L433)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: time.Nanosecond
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16236)*

**Pull request merged**
