### PR TITLE
upgradecluster: retry until cluster stable with unavailable nodes

### LINKED ISSUE #119696: pkg/upgrade/upgrademanager/upgrademanager_test: TestPauseMigration failed [node unavailable in KV NodeLiveness even though it started up]
pkg/upgrade/upgrademanager/upgrademanager_test.TestPauseMigration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/14178204?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/14178204?buildTab=artifacts#/) on release-23.1 @ [b4978725125cda7b02d6801c3fb6b6c6ab39229f](https://github.com/cockroachdb/cockroach/commits/b4978725125cda7b02d6801c3fb6b6c6ab39229f):

```
=== RUN   TestPauseMigration
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/0a595abbc53f575a0f489dc4e6e5da0f/logTestPauseMigration4009095469
    test_log_scope.go:79: use -show-logs to present logs inline
    testcluster.go:429: pq: n2 required, but unavailable
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/0a595abbc53f575a0f489dc4e6e5da0f/logTestPauseMigration4009095469
--- FAIL: TestPauseMigration (0.56s)
```

Parameters:
 - <code>TAGS=bazel,gss</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #119487 pkg/upgrade/upgrademanager/upgrademanager_test: TestPauseMigration failed [C-test-failure O-robot T-release branch-release-23.1.15-rc release-blocker]
</p>
</details>
/cc @cockroachdb/release-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPauseMigration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36286

### LINKED ISSUE #120521: ccl/schemachangerccl: TestBackupMixedVersionElements failed [node unavailable in KV NodeLiveness even though it started up]
ccl/schemachangerccl.TestBackupMixedVersionElements_base_alter_table_alter_primary_key_drop_rowid [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/14398457?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/14398457?buildTab=artifacts#/) on release-23.1 @ [689c53764c44c609313c00f7317f1e747e13a152](https://github.com/cockroachdb/cockroach/commits/689c53764c44c609313c00f7317f1e747e13a152):

```
I240314 21:19:02.138565 1303481 3@pebble/event.go:701  [n2,s2,pebble] 41  [JOB 14] sstable deleted 000008
I240314 21:19:02.155747 1300521 13@kv/kvserver/replica_raft.go:381  [T1,n1,s1,r36/1:/Table/3{5-6}] 42  proposing SIMPLE(v2) [(n2,s2):2]: after=[(n1,s1):1 (n2,s2):2] next=3
I240314 21:19:02.156702 1300521 13@kv/kvserver/replicate_queue.go:1283  [T1,n1,replicate,s1,r50/1:/Table/5{0-1}] 43  adding voter n3,s3: [1*:12]
I240314 21:19:02.157280 1300521 13@kv/kvserver/replica_command.go:2376  [T1,n1,replicate,s1,r50/1:/Table/5{0-1}] 44  change replicas (add [(n3,s3):2LEARNER] remove []): existing descriptor r50:/Table/5{0-1} [(n1,s1):1, next=2, gen=0]
I240314 21:19:02.160757 1300521 13@kv/kvserver/replica_raft.go:381  [T1,n1,s1,r50/1:/Table/5{0-1}] 45  proposing SIMPLE(l2) [(n3,s3):2LEARNER]: after=[(n1,s1):1 (n3,s3):2LEARNER] next=3
I240314 21:19:02.176306 1303491 13@kv/kvserver/store_snapshot.go:1579  [T1,n1,s1,r50/1:/Table/5{0-1}] 46  streamed INITIAL snapshot 82cb4430 at applied index 15 to (n3,s3):2LEARNER with 700 B in 0.00s @ 4.4 MiB/s: kvs=9 rangeKVs=0, rate-limit: 32 MiB/s, queued: 0.01s
I240314 21:19:02.176952 1303441 13@kv/kvserver/replica_raftstorage.go:480  [T1,n3,s3,r50/2:{-}] 47  applying INITIAL snapshot 82cb4430 from (n1,s1):1 at applied index 15
I240314 21:19:02.177400 1303441 3@pebble/event.go:697  [n3,s3,pebble] 48  [JOB 15] ingesting: sstable created 000015
I240314 21:19:02.177528 1303441 3@pebble/event.go:697  [n3,s3,pebble] 49  [JOB 15] ingesting: sstable created 000020
I240314 21:19:02.177618 1303441 3@pebble/event.go:697  [n3,s3,pebble] 50  [JOB 15] ingesting: sstable created 000016
I240314 21:19:02.177643 1303441 3@pebble/event.go:697  [n3,s3,pebble] 51  [JOB 15] ingesting: sstable created 000017
I240314 21:19:02.177659 1303441 3@pebble/event.go:697  [n3,s3,pebble] 52  [JOB 15] ingesting: sstable created 000018
I240314 21:19:02.177674 1303441 3@pebble/event.go:697  [n3,s3,pebble] 53  [JOB 15] ingesting: sstable created 000019
I240314 21:19:02.177734 1303441 3@pebble/event.go:717  [n3,s3,pebble] 54  [JOB 16] WAL created 000021 (recycled 000002)
I240314 21:19:02.177845 1303523 3@pebble/event.go:677  [n3,s3,pebble] 55  [JOB 17] flushing 1 memtable to L0
I240314 21:19:02.177891 1303523 3@pebble/event.go:697  [n3,s3,pebble] 56  [JOB 17] flushing: sstable created 000022
I240314 21:19:02.178068 1303523 3@pebble/event.go:681  [n3,s3,pebble] 57  [JOB 17] flushed 1 memtable to L0 [000022] (1.7 K), in 0.0s (0.0s total), output rate 9.6 M/s
I240314 21:19:02.178171 1303526 3@pebble/event.go:665  [n3,s3,pebble] 58  [JOB 18] compacting(default) L0 [000022] (1.7 K) + L6 [000013 000012] (2.8 K)
I240314 21:19:02.178319 1303526 3@pebble/event.go:697  [n3,s3,pebble] 59  [JOB 18] compacting: sstable created 000023
I240314 21:19:02.178563 1303526 3@pebble/event.go:669  [n3,s3,pebble] 60  [JOB 18] compacted(default) L0 [000022] (1.7 K) + L6 [000013 000012] (2.8 K) -> L6 [000023] (2.3 K), in 0.0s (0.0s total), output rate 7.0 M/s
I240314 21:19:02.178816 1303441 3@pebble/event.go:705  [n3,s3,pebble] 61  [JOB 15] ingested L0:000015 (1.4 K), L0:000020 (1.1 K), L0:000016 (1.5 K), L6:000017 (1.2 K), L6:000018 (1.1 K), L6:000019 (1.1 K)
I240314 21:19:02.178933 1303529 3@pebble/event.go:701  [n3,s3,pebble] 62  [JOB 18] sstable deleted 000012
I240314 21:19:02.178979 1303529 3@pebble/event.go:701  [n3,s3,pebble] 63  [JOB 18] sstable deleted 000013
I240314 21:19:02.178995 1303529 3@pebble/event.go:701  [n3,s3,pebble] 64  [JOB 18] sstable deleted 000022
I240314 21:19:02.179066 1303409 3@pebble/event.go:665  [n3,s3,pebble] 65  [JOB 20] compacting(default) L0 [000015 000020 000016] (4.1 K) + L6 [000023] (2.3 K)
I240314 21:19:02.179189 1303409 3@pebble/event.go:697  [n3,s3,pebble] 66  [JOB 20] compacting: sstable created 000024
I240314 21:19:02.179309 1303441 kv/kvserver/replica_raftstorage.go:491  [T1,n3,s3,r50/2:/Table/5{0-1}] 67  applied INITIAL snapshot 82cb4430 from (n1,s1):1 at applied index 15 (total=2ms data=757 B ingestion=6@2ms)
I240314 21:19:02.179466 1303409 3@pebble/event.go:669  [n3,s3,pebble] 68  [JOB 20] compacted(default) L0 [000015 000020 000016] (4.1 K) + L6 [000023] (2.3 K) -> L6 [000024] (2.6 K), in 0.0s (0.0s total), output rate 7.8 M/s
I240314 21:19:02.179576 1303557 3@pebble/event.go:665  [n3,s3,pebble] 69  [JOB 21] compacting(elision-only) L6 [000017] (1.2 K) + L6 [] (0 B)
I240314 21:19:02.179676 1303557 3@pebble/event.go:669  [n3,s3,pebble] 70  [JOB 21] compacted(elision-only) L6 [000017] (1.2 K) + L6 [] (0 B) -> L6 [] (0 B), in 0.0s (0.0s total), output rate 0 B/s
I240314 21:19:02.179718 1303558 3@pebble/event.go:665  [n3,s3,pebble] 71  [JOB 22] compacting(elision-only) L6 [000018] (1.1 K) + L6 [] (0 B)
I240314 21:19:02.179780 1303558 3@pebble/event.go:669  [n3,s3,pebble] 72  [JOB 22] compacted(elision-only) L6 [000018] (1.1 K) + L6 [] (0 B) -> L6 [] (0 B), in 0.0s (0.0s total), output rate 0 B/s
I240314 21:19:02.179827 1303560 3@pebble/event.go:665  [n3,s3,pebble] 73  [JOB 23] compacting(elision-only) L6 [000019] (1.1 K) + L6 [] (0 B)
I240314 21:19:02.179901 1303560 3@pebble/event.go:669  [n3,s3,pebble] 74  [JOB 23] compacted(elision-only) L6 [000019] (1.1 K) + L6 [] (0 B) -> L6 [] (0 B), in 0.0s (0.0s total), output rate 0 B/s
I240314 21:19:02.179956 1303559 3@pebble/event.go:701  [n3,s3,pebble] 75  [JOB 22] sstable deleted 000018
I240314 21:19:02.179987 1303556 3@pebble/event.go:701  [n3,s3,pebble] 76  [JOB 20] sstable deleted 000015
I240314 21:19:02.180017 1303556 3@pebble/event.go:701  [n3,s3,pebble] 77  [JOB 20] sstable deleted 000016
I240314 21:19:02.179998 1303532 3@pebble/event.go:701  [n3,s3,pebble] 78  [JOB 24] sstable deleted 000017
I240314 21:19:02.180034 1303556 3@pebble/event.go:701  [n3,s3,pebble] 79  [JOB 20] sstable deleted 000020
I240314 21:19:02.180043 1303532 3@pebble/event.go:701  [n3,s3,pebble] 80  [JOB 24] sstable deleted 000019
I240314 21:19:02.180046 1303556 3@pebble/event.go:701  [n3,s3,pebble] 81  [JOB 20] sstable deleted 000023
I240314 21:19:02.180403 1300521 13@kv/kvserver/replica_command.go:2376  [T1,n1,replicate,s1,r50/1:/Table/5{0-1}] 82  change replicas (add [(n3,s3):2] remove []): existing descriptor r50:/Table/5{0-1} [(n1,s1):1, (n3,s3):2LEARNER, next=3, gen=1]
I240314 21:19:02.183884 1300521 13@kv/kvserver/replica_raft.go:381  [T1,n1,s1,r50/1:/Table/5{0-1}] 83  proposing SIMPLE(v2) [(n3,s3):2]: after=[(n1,s1):1 (n3,s3):2] next=3
I240314 21:19:02.184837 1300521 13@kv/kvserver/replicate_queue.go:1283  [T1,n1,replicate,s1,r22/1:/Table/2{1-2}] 84  adding voter n2,s2: [1*:18]
I240314 21:19:02.185345 1300521 13@kv/kvserver/replica_command.go:2376  [T1,n1,replicate,s1,r22/1:/Table/2{1-2}] 85  change replicas (add [(n2,s2):2LEARNER] remove []): existing descriptor r22:/Table/2{1-2} [(n1,s1):1, next=2, gen=0]
I240314 21:19:02.188777 1300521 13@kv/kvserver/replica_raft.go:381  [T1,n1,s1,r22/1:/Table/2{1-2}] 86  proposing SIMPLE(l2) [(n2,s2):2LEARNER]: after=[(n1,s1):1 (n2,s2):2LEARNER] next=3
--- FAIL: TestBackupMixedVersionElements_base_alter_table_alter_primary_key_drop_rowid (274.72s)
=== RUN   TestBackupMixedVersionElements_base_alter_table_alter_primary_key_drop_rowid/backup/restore_stage_17_of_19
    testcluster.go:429: pq: n3 required, but unavailable
    --- FAIL: TestBackupMixedVersionElements_base_alter_table_alter_primary_key_drop_rowid/backup/restore_stage_17_of_19 (0.82s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupMixedVersionElements_base_alter_table_alter_primary_key_drop_rowid.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36728

### LINKED ISSUE #121069: pkg/upgrade/upgrademanager/upgrademanager_test: TestAlreadyRunningJobsAreHandledProperly failed [node unavailable in KV NodeLiveness even though it started up]
pkg/upgrade/upgrademanager/upgrademanager_test.TestAlreadyRunningJobsAreHandledProperly [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/14546290?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/14546290?buildTab=artifacts#/) on release-23.1 @ [b10541de302b66c47b72db592bc368af01a7a204](https://github.com/cockroachdb/cockroach/commits/b10541de302b66c47b72db592bc368af01a7a204):

```
=== RUN   TestAlreadyRunningJobsAreHandledProperly
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/0a595abbc53f575a0f489dc4e6e5da0f/logTestAlreadyRunningJobsAreHandledProperly2631556899
    test_log_scope.go:79: use -show-logs to present logs inline
    testcluster.go:429: pq: n2 required, but unavailable
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/0a595abbc53f575a0f489dc4e6e5da0f/logTestAlreadyRunningJobsAreHandledProperly2631556899
--- FAIL: TestAlreadyRunningJobsAreHandledProperly (0.88s)
```

Parameters:
 - <code>TAGS=bazel,gss</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/release-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAlreadyRunningJobsAreHandledProperly.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-37055

### PR DESCRIPTION
**Pull request by kvoli**
Nodes can be transiently unavailable (failing a heartbeat), in which case the upgrade manager will error out. Retry `UntilClusterStable` for up to 10 times when there are unavailable nodes before returning an error.

Resolves: #120521
Resolves: #121069
Resolves: #119696
Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124288)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/upgrade/upgradecluster/cluster.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124288#-NzF86T362c1ttXJ1dCL:-NzF86T362c1ttXJ1dCM:bbiqekb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab76750e7deb45e4d5a94c1e659a1d5e0f09afa7/pkg/upgrade/upgradecluster/cluster.go#L79)):*
> ```Go
> 	unavailableRetries := 0
> 
> 	for {
> ```

nit: would a retry ctx make sense here?
```
	retryOpts := base.DefaultRetryOptions()
	retryOpts.MaxRetries = 10
	for r := retry.StartWithCtx(ctx, retryOpts); r.Next(); {
		// ...
	}
```
___
*[`pkg/upgrade/upgradecluster/cluster.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124288#-NzF9g-E92S7wMOLgqzN:-NzF9g-E92S7wMOLgqzO:b-o0rwki) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab76750e7deb45e4d5a94c1e659a1d5e0f09afa7/pkg/upgrade/upgradecluster/cluster.go#L111)):*
> ```Go
> 	}
> 	if len(unavailable) > 0 {
> 		return 0, errors.Newf("unavailable node(s): %v", unavailable)
> ```

is there any concern that this would create a new error scenario that didn't exist before (asking since we'd want to backport this)? or is it just that this problem could already happen, but returning the error here is more clear?

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124288)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @rafiss)

___
*[`pkg/upgrade/upgradecluster/cluster.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124288#-NzF86T362c1ttXJ1dCL:-NzUfc6E6N6pe9sjfkrS:b46lqk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab76750e7deb45e4d5a94c1e659a1d5e0f09afa7/pkg/upgrade/upgradecluster/cluster.go#L79)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: would a retry ctx make sense here?
```
	retryOpts := base.DefaultRetryOptions()
	retryOpts.MaxRetries = 10
	for r := retry.StartWithCtx(ctx, retryOpts); r.Next(); {
		// ...
	}
```
</blockquote></details>

Somewhat - the existing behavior is to retry indefinitely when the node set changes between calls, without a backoff. 

For checking whether there are unavailable nodes, it makes sense to have a backoff and max attempts. However, that logic is currently coupled to retrying on node diffs.

The current implementation is less of a behavior change for backporting but I'm not too familiar with this code, to say that introducing a general backoff + retry limit would be fine.
___
*[`pkg/upgrade/upgradecluster/cluster.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124288#-NzF9g-E92S7wMOLgqzN:-NzUfjZm8jZUqX3m_B2f:biv2tqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab76750e7deb45e4d5a94c1e659a1d5e0f09afa7/pkg/upgrade/upgradecluster/cluster.go#L111)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is there any concern that this would create a new error scenario that didn't exist before (asking since we'd want to backport this)? or is it just that this problem could already happen, but returning the error here is more clear?
</blockquote></details>

The error could already be returned above from `NodesFromNodeLiveness`, this error is mostly moved up from there.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124288)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/upgrade/upgradecluster/cluster.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124288#-NzF86T362c1ttXJ1dCL:-NzUt8sOD88BmSnbwUQA:ba4fhrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab76750e7deb45e4d5a94c1e659a1d5e0f09afa7/pkg/upgrade/upgradecluster/cluster.go#L79)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Somewhat - the existing behavior is to retry indefinitely when the node set changes between calls, without a backoff. 

For checking whether there are unavailable nodes, it makes sense to have a backoff and max attempts. However, that logic is currently coupled to retrying on node diffs.

The current implementation is less of a behavior change for backporting but I'm not too familiar with this code, to say that introducing a general backoff + retry limit would be fine.
</blockquote></details>

ah i see, `unavailableRetries` is only incremented in certain cases. sgtm

**Comment by kvoli** [comment]
TYFTR

bors r=rafiss

**Pull request merged**
