### PR TITLE
deps: update errors dependency to 1.10.1

### PR DESCRIPTION
**Pull request by dhartunian**
This errors lib release is a compatibility release that adds multi-
cause error support in preparation for go 1.20.

One test needed to have datadriven output updated due to a bugfix that
improved error printing for certain kinds of wrapped error chains.

Part of https://github.com/cockroachdb/cockroach/issues/97799
Epic: None

Release note: None

### CODE REVIEW

**Comment by dhartunian** [comment]
Pushing this up to generate a CI run

**Review by knz — APPROVED** [review]

**Comment by dhartunian** [comment]
bors r=knz p99 single on

**Comment by rickystewart** [comment]
Also, it's `p=99`, not `p99`.

**Comment by dhartunian** [comment]
bors r=knz p=99 single on

**Comment by dhartunian** [comment]
bors r=knz p=99 single on

**Pull request merged**
