### PR TITLE
sql/pgwire: Support returning Tuple composite types in pgwire

### LINKED ISSUE #10321: sql/pgwire: Support returning Tuple composite types in pgwire
We currently do not support returning tuples over pgwire. I can't come up with of any good reasons for why support here would have been omitted, so I think this was just an oversight.

```
root@:26257> SELECT (1, 2);
pq: unsupported result type: tuple{int, int}
```

For now we can just support the pgwire text format, because I have not seen any drivers use the binary format for `record` OID types.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #10321.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10380)

### CODE REVIEW

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10380#-:-KVYZizmV-cDKJvSqXCl:bnfp4nl)*

**Comment by tamird** [comment]
How difficult is it to support the binary format? It would be good to add this test to `acceptance.TestDockerC`.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10380#-:-KVYllnZqXEJ9jePj46r:b-89mikr)*

**Comment by knz** [comment]
LGTM, but beware that SQL does not guarantee the order of results when ORDER BY is not specified and the input is not VALUES.

**Comment by nvanbenschoten** [comment]
TFTRs.

Supporting a binary format looks like it would be a lot more involved based on its implementation. I have yet to see any drivers use the binary format for the `record` OID, so I don't think we should prioritize supporting it. On that note, because this change is only adding support to _return_ Tuples in the string format (like what we have for Arrays at the moment), adding to `TestDockerC` would be more effort than its worth.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10380#-:-KW-UBod3J38wHOnu4gb:bh84l5e)*

**Pull request merged**
