### PR TITLE
memsize: consolidate memory size constants

### PR DESCRIPTION
**Pull request by mgartner**
Constants that describe the in-memory size of data types have been
consolidated into a new package.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Thanks!

> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67522#-:-MeVsyxn0-mSEAc8eKPx:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/col/coldataext/datum_vec.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67522#-MeVrk2H9oc7OtU0gTze:-MeVrk2H9oc7OtU0gTzf:b-srfauo) ([raw file](https://github.com/cockroachdb/cockroach/blob/951fb2700e7e45b1aeedf7e3e338f4b49db9dcff/pkg/col/coldataext/datum_vec.go#L181)):*
> ```Go
> 
> // Size implements coldata.DatumVec interface.
> func (dv *datumVec) Size(startIdx int) uintptr {
> ```

Curious whether it's worth changing the return argument to be `int64` here too, for consistency.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67522#-MeVsEJ_B_jQvvVfsExL:-MeVsEJ_B_jQvvVfsExM:bmf2vfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/951fb2700e7e45b1aeedf7e3e338f4b49db9dcff/pkg/col/colserde/arrowbatchconverter.go#L70)):*
> ```Go
> }
> 
> const sizeOfInt64 = int(memsize.Int64)
> ```

nit: why not removing this?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67522#-MeVrk2H9oc7OtU0gTze:-MeW0zxX7AnCAcWN8Bi8:b-e9x2zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/951fb2700e7e45b1aeedf7e3e338f4b49db9dcff/pkg/col/coldataext/datum_vec.go#L181)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Curious whether it's worth changing the return argument to be `int64` here too, for consistency.
</blockquote></details>

Done.

I also noticed that [`Datum.Size`](https://github.com/cockroachdb/cockroach/blob/951fb2700e7e45b1aeedf7e3e338f4b49db9dcff/pkg/sql/sem/tree/datum.go#L155) returns a `uintptr`. I think changing that to `int64` is a more invasive change, but if we want to go ahead with it I can do it in a follow-up PR.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67522#-MeVsEJ_B_jQvvVfsExL:-MeXI2T--Pep-b6Xu1yV:bw10jn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/951fb2700e7e45b1aeedf7e3e338f4b49db9dcff/pkg/col/colserde/arrowbatchconverter.go#L70)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: why not removing this?
</blockquote></details>

Oops, done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67522#-:-MeXLc9366AlpNU0Yce2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/col/coldataext/datum_vec.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67522#-MeVrk2H9oc7OtU0gTze:-MeXL9Vi9htvk4qBHJ9v:bc85uui) ([raw file](https://github.com/cockroachdb/cockroach/blob/951fb2700e7e45b1aeedf7e3e338f4b49db9dcff/pkg/col/coldataext/datum_vec.go#L181)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Done.

I also noticed that [`Datum.Size`](https://github.com/cockroachdb/cockroach/blob/951fb2700e7e45b1aeedf7e3e338f4b49db9dcff/pkg/sql/sem/tree/datum.go#L155) returns a `uintptr`. I think changing that to `int64` is a more invasive change, but if we want to go ahead with it I can do it in a follow-up PR.
</blockquote></details>

Probably not worth it, as is looks good to me.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 179 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67522#-MeXLVaZ9qIKtamDkjyN:-MeXLVaZ9qIKtamDkjyO:b-d8e32e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec409473f5753eeecf6a6e7378b41ee8de77aa6/pkg/col/colserde/arrowbatchconverter.go#L179)):*
> ```Go
> 				}
> 				curSlice := values[intervalSize*curNonNullInterval : intervalSize*(curNonNullInterval+1)]
> 				binary.LittleEndian.PutUint64(curSlice[0:int(memsize.Int64)], uint64(nanos))
> ```

nit: this looks to me like an unnecessary conversion. Probably the linter will complain too.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67522)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67522#-MeVrk2H9oc7OtU0gTze:-MeXODaW-F1iPUkGQjhA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/951fb2700e7e45b1aeedf7e3e338f4b49db9dcff/pkg/col/coldataext/datum_vec.go#L181)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Probably not worth it, as is looks good to me.
</blockquote></details>

Done.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 179 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67522#-MeXLVaZ9qIKtamDkjyN:-MeXODzy960Bv5dJJVtd:b-yq7auh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec409473f5753eeecf6a6e7378b41ee8de77aa6/pkg/col/colserde/arrowbatchconverter.go#L179)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this looks to me like an unnecessary conversion. Probably the linter will complain too.
</blockquote></details>

Thanks for catching this. I incorrectly assumed only an `int` could index a slice. Fixed.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
