### PR TITLE
*: track build "channels" for better usage stats

### LINKED ISSUE #22283: Include channel partner information in diagnostic reporting
We’ve seen a lot of interest from partners like Red Hat and Mesosphere in offering CockroachDB containers in their marketplaces. Unfortunately, we have no way of knowing which channels are actually useful to customers. 

Let’s update the CockroachDB binary to check for an environment variable (most likely set in a Dockerfile) indicating the channel through which the container was obtained. This will let us hold ourselves and our partners accountable for making CockroachDB available in the best locations for our users. 

This update should ultimately send simple strings like “red hat container store” or “dc/os universe”

And of course, this must honor the user's [reporting preferences](https://www.cockroachlabs.com/docs/stable/diagnostics-reporting.html).

### PR DESCRIPTION
**Pull request by benesch**
Plumb the concept of "channels" through the build system. A channel is
an arbitrary string that tracks the origin of a CockroachDB artifact
(e.g., a binary or Docker image). There are two types of channels: build
channels and environment channels. The build channel is compiled into
the binary using linker flags, while the environment channel is read
from the COCKROACH_CHANNEL environment. Both channels are reported to
the registration server when checking for updates.

Build channels are necessary when we don't control the environment, like
when a user downloads a binary and runs it directly on their machine.
Environment channels aren't strictly necessary--we could recompile a
different binary for every distribution platform--but it's typically
more convenient to set an environment variable when we do control the
environment, like in Docker images.

So far, the build channels are:

   * official-binary, for binaries downloaded from
     binaries.cockroachdb.com and for binaries in official Docker
     images;

   * source-archive, for binaries compiled from an official source archive;

   * unknown, for binaries compiled directly from Git;

and the environment channels are:

   * official-docker, for the official cockroachdb/cockroach Docker
     image;

   * rhel-docker, for the Red Hat Container Catalogue Docker image;

   * unknown, for everything else.

Fixes #22283.

Release note: None

/cc @kannanlakshmi @nstewart 

@bdarnell is it too late to slip this into 2.0? I'm touching a lot of files but the changes are quite surgical.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm: and OK for cherry-pick to 2.0.

Is there a third level needed here? For example, kubernetes and docker swarm would both use our official-docker image, but it seems worth tracking these somehow. Would those configs just be able clobber the COCKROACH_CHANNEL env var? 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23437#-:-L6sV1fNf4KsMClwecE7:bqs8l7o)*

**Comment by benesch** [comment]
> Would those configs just be able clobber the COCKROACH_CHANNEL env var?

I think so! I'm no Kubernetes expert, but https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#define-an-environment-variable-for-a-container suggests it's pretty straightforward. @a-robinson can you confirm the viability of this approach?

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23437#-:-L6sYT3QnxHA4mBDiuJG:bnhhor)*

**Comment by a-robinson** [comment]
> Would those configs just be able clobber the COCKROACH_CHANNEL env var?

Yeah, it's easy for Kubernetes since most people are just using our config file. We can do something similar in [our DC/OS configs](https://github.com/cockroachdb/dcos-cockroachdb-service). For Swarm we can include it in copy/paste commands in our docs, but that's a little less aesthetically pleasing since it's staring everyone in the face in all the commands.

**Comment by a-robinson** [comment]
I've added a commit that adds it for Kubernetes. Feel free to squash it if you like, but it doesn't really need to be cherry-picked since we historically haven't maintained the Kubernetes configs on the release branches.

We should probably also add it to our Helm chart (for Kubernetes) if we care about full coverage: https://github.com/kubernetes/charts/tree/master/stable/cockroachdb

**Comment by kannanlakshmi** [comment]
@benesch can we edit the channel var to attribute a particular cluster that was built using the official binary that came from the website?

**Comment by benesch** [comment]
Discussed offline with @kannanlakshmi. Sounds like `buildchannel = 'official-binary' and envchannel IS NULL` will do the trick.

**Pull request merged**
