### PR TITLE
config: Add a static split for node liveness spans

### LINKED ISSUE #17297: config: add a StaticSplit to isolate the node liveness span
The node liveness span is critical to cluster operation. When investigating a cluster, it is very helpful to know that it is not sharing its range with anything else.

### PR DESCRIPTION
**Pull request by m-schneider**
Before node liveness spans could be combined with other ranges at
startup.

Now they will be in a separate range to reduce interference from other
data.

Closes #17297

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM, though I added a commit that throws out one redundant test case and moves the tests (and key definition) further up. Let me know if that looks good!

**Review by a-robinson — APPROVED** [review]
LGTM!

**Comment by tschottdorf** [comment]
@m-schneider you've got some more test failures to sort out 😄

**Comment by tschottdorf** [comment]
@m-schneider you've got some more test failures to sort out 😄

**Comment by m-schneider** [comment]
Looks good! I fixed the tests.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17810#-:-Ks9ltWSniuyyBLm77kb:b-zhrnsk)*

**Comment by tschottdorf** [comment]
I think you accidentally overwrote the edits that I pushed, but looks good otherwise! I'll reinstate them tomorrow and merge.

---

Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17810#-:-KsAtFIYD5D-egnCdpnQ:bkzuloq)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17810#-:-KsBmCDksnsLmqC9UV-K:bnfp4nl)*

**Pull request merged**
