### PR TITLE
More explicitly test that a character is an ASCII digit.

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by vivekmenezes** [comment]
LGTM

**Comment by tamird** [comment]
@petermattis could you export parser.isDigit (or put it in util) and use that?

**Comment by bdarnell** [comment]
LGTM

**Comment by petermattis** [comment]
`parser.isDigit` is so small that it seems ok to repeat myself. That's what I thought when writing this code and I'm still thinking it as I look at it again.

**Pull request merged**
