### PR TITLE
storage: assume success on AmbiguousResultError when [un]replicating

### LINKED ISSUE #10969: storage: TestRaftRemoveRace is flaky under stress (ambiguous result)
Somewhat hard to reproduce locally, but reproduces almost instantly in GCE:
```
tamird@gceworker173:~/go/src/github.com/cockroachdb/cockroach$ make stress STRESSFLAGS='-p 100 -stderr -maxfails 1' PKG=./pkg/storage TESTS=TestRaftRemoveRace
go list -tags '' -f 'go test -v  -tags '\'''\'' -ldflags '\'''\'' -i -c {{.ImportPath}} -o {{.Dir}}/stress.test && (cd {{.Dir}} && if [ -f stress.test ]; then stress -p 100 -stderr -maxfails 1 ./stress.test -test.run '\''TestRaftRemoveRace'\'' -test.timeout 2m ; fi)' ./pkg/storage | /bin/bash
github.com/cockroachdb/cockroach/pkg/storage
github.com/cockroachdb/cockroach/pkg/storage_test
testmain
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
2 runs so far, 0 failures, over 20s
9 runs so far, 0 failures, over 25s
57 runs so far, 0 failures, over 30s
96 runs so far, 0 failures, over 35s
98 runs so far, 0 failures, over 40s

--- FAIL: TestRaftRemoveRace (7.48s)
	client_test.go:915: change replicas of range 1 failed: result is ambiguous (Raft re-proposal failed: write at timestamp 0.000000123,1564 too old; wrote at 0.000000123,1565)
FAIL


ERROR: exit status 1

99 runs completed, 1 failures, over 41s
FAIL
Makefile:138: recipe for target 'stress' failed
make: *** [stress] Error 1
```

My guess is that we need better error handling in either `(*storage.Replica).ChangeReplicas` or its callers `(*storage.multiTestContext).{,un}replicateRange`.

### PR DESCRIPTION
**Pull request by spencerkimball**
I don't see utility in trying to handle this except for at the `client_test.go` level.

Fixes #10969

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11621)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: modulo the regexp amendments:
```
$ git grep -F 'already present' | wc -l
       9
$ git grep -F 'not present' | wc -l
      24
```
having the extra words in there will help anyone looking for the origin of these errors.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/client_test.go, line 919 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11621#-KXStPsWP0S5r09ZGFGD:-KXStPsWP0S5r09ZGFGE:bvj4b2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/01651a8333cbfcdabd1bc2a054c687c10942e908/pkg/storage/client_test.go#L919)):*
> ```Go
> 				&desc,
> 			)
> 			if err == nil || testutils.IsError(err, "already present") {
> ```

`"unable to remove replica .* which is not present"`

---

*[pkg/storage/client_test.go, line 983 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11621#-KXStob1F0yt1w0kn0V9:-KXStob1F0yt1w0kn0VA:bvj4b2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/01651a8333cbfcdabd1bc2a054c687c10942e908/pkg/storage/client_test.go#L983)):*
> ```Go
> 			&desc,
> 		)
> 		if err == nil || testutils.IsError(err, "not present") {
> ```

`"unable to remove replica .* which is not present"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11621#-:-KXStyMWPE4FqOmoiK6A:bm7u1rs)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11621#-:-KXW8fQZFaNvzkctkSEU:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/client_test.go, line 919 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11621#-KXStPsWP0S5r09ZGFGD:-KXfjLNrF-G4C56_VAgV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01651a8333cbfcdabd1bc2a054c687c10942e908/pkg/storage/client_test.go#L919)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`"unable to remove replica .* which is not present"`
</blockquote></details>

Done.

---

*[pkg/storage/client_test.go, line 983 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11621#-KXStob1F0yt1w0kn0V9:-KXfjLqUILKuZZAJXFOv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01651a8333cbfcdabd1bc2a054c687c10942e908/pkg/storage/client_test.go#L983)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`"unable to remove replica .* which is not present"`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11621)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11621)*

**Pull request merged**
