### PR TITLE
ui/server: Conditionally enable UI analytics

### PR DESCRIPTION
**Pull request by mrtracy**
Analytics collection from the Admin UI will now be enabled if cluster
setting "diagnostics.reporting.enabled" is set to true.

The "Cluster" method of the Admin API has been augmented to return an
additional field indicating if the cluster has reporting enabled. The
analytics system on the AdminUI respects this setting.

### CODE REVIEW

**Comment by BramGruneir** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ui/src/redux/analytics.ts, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18046#-Kst8-N-FS24OHSs0u_Y:-Kst8-N-FS24OHSs0u_Z:b-pyrtig) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d9c9977f582077edf8b318e0af41c190b3d3a18/pkg/ui/src/redux/analytics.ts#L82)):*
> ```XML
>         // A cluster setting determines if diagnostic reporting is enabled. If
>         // it is not explicitly enabled, do nothing.
>         if (!reporting_enabled) {
> ```

Clear the queued pages is this is the case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18046)*

**Comment by BramGruneir** [comment]
:lgtm: With only one issue.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18046#-:-Kst88SepvPpOi2jOXG6:b-ttw3jc)*

**Comment by mrtracy** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ui/src/redux/analytics.ts, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18046#-Kst8-N-FS24OHSs0u_Y:-KstUeJeqkxcAamekx6V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d9c9977f582077edf8b318e0af41c190b3d3a18/pkg/ui/src/redux/analytics.ts#L82)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Clear the queued pages is this is the case?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18046)*

**Comment by BramGruneir** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18046)*

**Pull request merged**
