### PR TITLE
plpgsql: misc fixes for parsing and formatting identifiers and constants

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: correctly format variable names in declarations

This commit fixes formatting for variable and cursor declarations to
use `FmtCtx.FormatNode` instead of `FormatString`. This ensures that
variable names are correctly redacted when applicable, and that
complex identifiers round-trip through the parser.

Informs #106368

Release note (bug fix): Fixed a bug that prevented the use of PL/pgSQL
routines with complex variable names that require double quotes. This
bug has existed since v23.2.

#### plpgsql/parser: propagate errors during string scanning

This commit fixes handling for string constants in the PL/pgSQL parser.
Now, the PL/pgSQL scanner handles string scanning itself instead of delegating
to the SQL scanner. This ensures that the correct token ID is used when an
error occurs (e.g. unterminated string). This commit also adds a check for the
ERROR token during PL/pgSQL lexing, so that a scanning error is noticed and
propagated back to the user.

Informs #106368

Release note (bug fix): Fixed a bug that could cause creation of a
syntactically invalid PL/pgSQL routine to return the wrong error. This bug has
existed since v23.2.

#### plpgsql/parser: fix parsing for escaped strings

This commit adds support for scanning an escaped string constant in a
PL/pgSQL routine. This is necessary because escaped strings have imbalanced
quotes (like `e'foobar''`), which previously caused the scanner to return
an "unterminated string" error.

Informs #106368

Release note (bug fix): Fixed a bug that could result in a syntax error
if a PL/pgSQL routine was created with an escaped string constant in
the routine body. This bug has existed since v23.2.

### CODE REVIEW

**Comment by DrewKimball** [comment]
Found these while working on #106368

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-:-NqU4lZA2CoovOLtyjjL:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqTy_9z0lzoX0rpY3_1:-NqTy_9z0lzoX0rpY3_2:b-vyh39w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bf1c0e01f2735a7249cdad01d720d0cbd78c7b4/pkg/sql/plpgsql/parser/plpgsql.y#L666)):*
> ```Yacc
> | stmt_while
>   {
>     $$.val = $1.statement()
> ```

Do we not have tests for this case?
___
*[`pkg/sql/scanner/plpgsql_scan.go` line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqU49uMCx071czNgf6M:-NqU49uMCx071czNgf6N:b-k4f034) ([raw file](https://github.com/cockroachdb/cockroach/blob/94424e8fa622b33295ff558d179039c860f8c987/pkg/sql/scanner/plpgsql_scan.go#L147)):*
> ```Go
> }
> 
> // scanString is similar to Scanner.scanString, but uses PL/pgSQL tokens.
> ```

Are the tokens the only difference? I wonder if there's a clever way we can combine the two functions.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119034)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/scanner/plpgsql_scan.go` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqUAe90EUUWRcxzO9ul:-NqUAe919QTqO7pB0fvQ:b-1gwao2) ([raw file](https://github.com/cockroachdb/cockroach/blob/94424e8fa622b33295ff558d179039c860f8c987/pkg/sql/scanner/plpgsql_scan.go#L26)):*
> ```Go
> // PLpgSQLScanner is a scanner with a PLPGSQL specific scan function
> type PLpgSQLScanner struct {
> 	Scanner
> ```

nit: do you think it'd be worth making the currently-embedded `Scanner` object actually a named variable so that we could see more easily what `s.scanString` actually refers to (i.e. it's `PLpgSQLScanner.scanString` or `Scanner.scanString`)?
___
*[`pkg/sql/scanner/plpgsql_scan.go` line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqU49uMCx071czNgf6M:-NqUBJ282UJZXKkv16c5:bkxsp5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/94424e8fa622b33295ff558d179039c860f8c987/pkg/sql/scanner/plpgsql_scan.go#L147)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Are the tokens the only difference? I wonder if there's a clever way we can combine the two functions.
</blockquote></details>

I'm confused - I just copied the contents of `scanString` from this PR and replaced `Scanner.scanString` with them, and there were effectively no differences. What are the different parts? Or if the code exactly the same, and the only difference is other `s.scan*` methods that get called by this code that was copied?
___
*[`pkg/sql/scanner/plpgsql_scan.go` line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqUCV0v2IWxwEyY4ymm:-NqUCV0v2IWxwEyY4ymn:b-lg2nqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea953abe1d620268bfc810c50ed3472b8dfd4cdc/pkg/sql/scanner/plpgsql_scan.go#L73)):*
> ```Go
> 		return
> 
> 	case 'e', 'E':
> ```

Interesting that `Scanner.Scan` has this code block, so I have the same question as Marcus: can both scanners share the core of its logic? This would remove a lot of code duplication, and I think we can do so without incurring a performance penalty of interfaces. For example, if both scanner objects have `scanFoo` function that behaves differently, we could imagine a config struct that would provide this function, i.e. something like
```
type ScannerConfig struct {
  scanFoo func(...)
  scanBar func(...)
}

NewScanner(cfg ScannerConfig) Scanner {
  return Scanner{...}
}

func (s *Scanner) Scan() {
...
  switch ch {
  case 'foo':
    s.cfg.scanFoo(...)
  case 'bar':
    s.cfg.scanBar(...)
  // all other cases have `scan` functions that behave the same
...
}
```
Am I missing something that this wouldn't work?
___
*[`pkg/sql/plpgsql/parser/parser_test.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqU9q1I3QUOTWSWhBgy:-NqU9q1I3QUOTWSWhBgz:bnifcsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bf1c0e01f2735a7249cdad01d720d0cbd78c7b4/pkg/sql/plpgsql/parser/parser_test.go#L23)):*
> ```Go
> )
> 
> func TestParseDatadriven(t *testing.T) {
> ```

nit: why this change? We have plenty of `TestDataDriven` and almost none `TestDatadriven` (I think we should instead do `s/TestParseDatadriven/TestParseDataDriven` for an already existing test).

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119034)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqTy_9z0lzoX0rpY3_1:-Nrbr-6S0cKnePDVEpcg:bcz8o97) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bf1c0e01f2735a7249cdad01d720d0cbd78c7b4/pkg/sql/plpgsql/parser/plpgsql.y#L666)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do we not have tests for this case?
</blockquote></details>

We do, but I believe the way `stmt_while` is referenced in the parser just happens to work out. If it was something like `| foo stmt_while bar` where `stmt_while` wasn't the only symbol, it might have been broken.
___
*[`pkg/sql/scanner/plpgsql_scan.go` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqUAe90EUUWRcxzO9ul:-Nrbyfe34-ZBrpKoCbqj:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/94424e8fa622b33295ff558d179039c860f8c987/pkg/sql/scanner/plpgsql_scan.go#L26)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: do you think it'd be worth making the currently-embedded `Scanner` object actually a named variable so that we could see more easily what `s.scanString` actually refers to (i.e. it's `PLpgSQLScanner.scanString` or `Scanner.scanString`)?
</blockquote></details>

Good idea, done.
___
*[`pkg/sql/scanner/plpgsql_scan.go` line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqU49uMCx071czNgf6M:-NrmGOApDxZrSilcx7ui:b-xjk07w) ([raw file](https://github.com/cockroachdb/cockroach/blob/94424e8fa622b33295ff558d179039c860f8c987/pkg/sql/scanner/plpgsql_scan.go#L147)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm confused - I just copied the contents of `scanString` from this PR and replaced `Scanner.scanString` with them, and there were effectively no differences. What are the different parts? Or if the code exactly the same, and the only difference is other `s.scan*` methods that get called by this code that was copied?
</blockquote></details>

The tokens are pretty much it. There are some places where the plpgsql scanner has removed some logic from the sql scanner, but from my reading of postgres source I _think_ it's safe to combine them. I'd rather do that in a different PR though, if that's alright.
___
*[`pkg/sql/plpgsql/parser/parser_test.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqU9q1I3QUOTWSWhBgy:-NrbtS9H1eHyteo003Lr:b-drlaey) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bf1c0e01f2735a7249cdad01d720d0cbd78c7b4/pkg/sql/plpgsql/parser/parser_test.go#L23)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: why this change? We have plenty of `TestDataDriven` and almost none `TestDatadriven` (I think we should instead do `s/TestParseDatadriven/TestParseDataDriven` for an already existing test).
</blockquote></details>

I was changing it to fit the SQL test, but I'll just change that one instead.

**Comment by DrewKimball** [comment]
Opened an issue to de-duplicate the scanning logic here: https://github.com/cockroachdb/cockroach/issues/119755

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, 4 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-:-NrmOdKV8DGqPHbEPtLF:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/scanner/plpgsql_scan.go` line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119034#-NqU49uMCx071czNgf6M:-NrmOWPVCrB9-L-qCwl2:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/94424e8fa622b33295ff558d179039c860f8c987/pkg/sql/scanner/plpgsql_scan.go#L147)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

The tokens are pretty much it. There are some places where the plpgsql scanner has removed some logic from the sql scanner, but from my reading of postgres source I _think_ it's safe to combine them. I'd rather do that in a different PR though, if that's alright.
</blockquote></details>

SGTM

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Pull request merged**
