### PR TITLE
TEAMS: ping kv-triage for unittest failures

### PR DESCRIPTION
**Pull request by tbg**
Currently unit test nightlies ping (at)cockroachdb/kv, our main handle.
This is not a team we'd like people to just leave to avoid notifications.
Github doesn't seem to offer a way to opt out of notifications for a team
one is on, besides, there are useful notifications going to that handle.

Our triage process is robust without these mentions. They can go to
(at)cockroachdb/kv-notifications for those inclined to consume a
firehose.

This change frees up our main alias (at)cockroachdb/kv for more
meaningful notifications.

Epic: none

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136571#-:-ODCCj8a35PgUfMVqBMg:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong and @nameisbhaskar)

**Comment by tbg** [comment]
TFTR!

bors r+

**Comment by tbg** [comment]
blathers backport 24.3
blathers backport 24.2
blathers backport 24.1

**Comment by tbg** [comment]
blathers backport 24.2

**Pull request merged**
