### PR TITLE
storage: remove range descriptor from admin commands

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10904)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: except that the commit message should **range** descriptor, not replica descriptor.

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10904#-:-KX6kNve3iJ1cksaZWGO:b-j97szb)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_command.go, line 2822 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10904#-KX9DKiEn09iuPQJsdpl:-KX9DKiEn09iuPQJsdpm:b-q9t2fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/23177c8f4c3f947e70a1eb541333ea6bfb72b2fb/pkg/storage/replica_command.go#L2822)):*
> ```Go
> // The supplied RangeDescriptor is used as a form of optimistic lock. See the
> // comment of "AdminSplit" for more information on this pattern.
> func (r *Replica) AdminMerge(
> ```

I think AdminMerge should still take a range descriptor - concurrent changes to the range may change whether we want to merge nor not. (if there are two concurrent AdminMerge commands, we want the second one to fail with a ConditionFailedError instead of merging the range again with the next one to the right)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10904)*

**Comment by vivekmenezes** [comment]
*[pkg/storage/replica_command.go, line 2822 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10904#-KX9DKiEn09iuPQJsdpl:-KXBeZN5pnr5-Z6ZVKxJ:bkxm44j) ([raw file](https://github.com/cockroachdb/cockroach/blob/23177c8f4c3f947e70a1eb541333ea6bfb72b2fb/pkg/storage/replica_command.go#L2822)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I think AdminMerge should still take a range descriptor - concurrent changes to the range may change whether we want to merge nor not. (if there are two concurrent AdminMerge commands, we want the second one to fail with a ConditionFailedError instead of merging the range again with the next one to the right)
</details>
Well this change in itself doesn't change the implementation of AdminMerge. I made it merely to make these commands consistent. We can adjust later if we need to change the implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10904)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_command.go, line 2822 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10904#-KX9DKiEn09iuPQJsdpl:-KXEB-6bn8GC_4zCdb7g:b-magjn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/23177c8f4c3f947e70a1eb541333ea6bfb72b2fb/pkg/storage/replica_command.go#L2822)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> Well this change in itself doesn't change the implementation of AdminMerge. I made it merely to make these commands consistent. We can adjust later if we need to change the implementation.
</details>
But this does change the implementation. Previously, this method was "merge this range with the following one if its range descriptor is still X"; now it's an unconditional merge. We don't yet have any callers that relied on this functionality, but the "real" use of AdminMerge in a future mergeQueue will want this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10904)*

**Pull request merged**
