### PR TITLE
build: accept extra TESTFLAGS for testrace

### PR DESCRIPTION
**Pull request by andreimatei**
I'll set a parallelism level in the TC env.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41828#-:-LrsZgfO7zakEghOTyCa:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
Rationale?

**Comment by ajwerner** [comment]
I’m pretty sure this was TestRepartitioning timing out and the fix was to change (lower) the parallelism from above this in the team city config. The TESTTIMEOUT change was drive by to make that controllable

**Comment by andreimatei** [comment]
yeah; added to the commit msg

**Pull request merged**
