### PR TITLE
ui: backport 20.2 custom chart changes

### PR DESCRIPTION
**Pull request by vladlos**
backport:
 - fix for extra space on custom charts page
 - add drag-to-select time range feature on custom charts page

### CODE REVIEW

**Review by Santamaura — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster, @koorosh, and @nathanstilwell)

___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/index.tsx, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66623#-McoXusc1sprnrqEOTNB:-McoXusc1sprnrqEOTNC:biukjph) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcdfe2391753490984bc6243dc8d41630cd7adb3/pkg/ui/src/views/cluster/containers/nodeGraphs/index.tsx#L219)):*
> ```XML
>     });
> 
>     // add pading to have last chart tooltip visible
> ```

Nit padding

**Review by Santamaura — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66623#-:-McoY4YY2NK3UnCqEuTR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @elkmaster, @koorosh, and @nathanstilwell)

**Review by koorosh — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66623)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @elkmaster and @nathanstilwell)

**Comment by nathanstilwell** [comment]
___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/index.tsx, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66623#-Mcxxdpf19pBiPGlC-SE:-Mcxxdpf19pBiPGlC-SF:b-t85tvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcdfe2391753490984bc6243dc8d41630cd7adb3/pkg/ui/src/views/cluster/containers/nodeGraphs/index.tsx#L224)):*
> ```XML
>     // 9 nodes it switch to multicolumn layout that take
>     // somewhere around 90px height + 10px for per node
>     // as we have 3 columns, we divide node ammount on 3
> ```

"ammount" is misspelled ("amount"). I guess someone added a spell checker to the linter, so the build failed due to this misspelling.

**Review by nathanstilwell — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66623)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @elkmaster)

**Review by vladlos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66623)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @koorosh, @nathanstilwell, and @Santamaura)

___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/index.tsx, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66623#-Mcxxdpf19pBiPGlC-SE:-MdMnj5g0SJzNsniRMLr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcdfe2391753490984bc6243dc8d41630cd7adb3/pkg/ui/src/views/cluster/containers/nodeGraphs/index.tsx#L224)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

"ammount" is misspelled ("amount"). I guess someone added a spell checker to the linter, so the build failed due to this misspelling.
</blockquote></details>

Done.

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66623)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @elkmaster)

**Pull request merged**
