### PR TITLE
add CDC to add-to-project

### PR DESCRIPTION
**Pull request by shermanCRL**
Issues & PRs will be added to the [new CDC project](https://github.com/orgs/cockroachdb/projects/38). GitHub Projects v2 has a different (non-REST) API and blathers doesn't do that.

https://github.com/actions/add-to-project

Epic: none

### CODE REVIEW

**Review by jlinder — COMMENTED** [review]
Cool.

Could you also update the `name` field in the file `.yml` file to be more generic? Maybe "Add issues to project boards"?

**Comment by shermanCRL** [comment]
@jlinder I made that change. @ajstorm may I get your review?

**Review by ajstorm — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94958#-:-NLgiTh31xxEIO_ssChO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder and @miretskiy)

**Review by jlinder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94958)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @shermanCRL)

___
*[`.github/workflows/add-issues-to-project.yml` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94958#-NLi8Lv20eAT_NcFnA10:-NLi8Lv20eAT_NcFnA11:b-o0fkvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/07c7ca07c42aa454af4763855a80f9e1cc108a81/.github/workflows/add-issues-to-project.yml#L1)):*
> ```YAML
> name: Add issues to multi-tenant project board
> ```

Hehe. I was speaking about this line as the line to change to `name: Add issues to project boards` but was using the GitHub review interface that doesn't allow comments outside the changed parts of the code and didn't give enough specificity about the line I was thinking of. Could you change this one too?

**Review by jlinder — APPROVED** [review]
LGTM!

**Comment by shermanCRL** [comment]
bors r=jlinder

**Pull request merged**
