### PR TITLE
roachtest: fix npgsql test parsing; add builtins for compat

### LINKED ISSUE #97614: roachtest: npgsql failed
roachtest.npgsql [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8820223?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8820223?buildTab=artifacts#/npgsql) on master @ [0d3393b0623a5c258b25725f64f3689e2f54667b](https://github.com/cockroachdb/cockroach/commits/0d3393b0623a5c258b25725f64f3689e2f54667b):

```
--- FAIL: TwoNonQueries -  (unexpected)
--- PASS: Send_NpgsqlDbType_Unknown(NotPrepared) - unknown (unexpected)
--- PASS: ExecuteScalar_on_connectionless_batch(True) - unknown (unexpected)
--- FAIL: Open_stream_when_changing_columns(False) -  (unexpected)
--- PASS: Bug3443 - unknown (unexpected)
--- FAIL: Prepended_messages -  (unexpected)
--- FAIL: Transaction_on_recycled_connection -  (unexpected)
--- FAIL: Batch -  (unexpected)
--- FAIL: SingleRow(Prepared) -  (unexpected)
--- PASS: QueryNonQuery - unknown (unexpected)
--- PASS: ExecuteReader_on_connectionless_command(False) - unknown (unexpected)
--- PASS: Import_direct_buffer - unknown (unexpected)
--- PASS: BaseColumnName - unknown (unexpected)
--- PASS: DeriveParameters_text_prepared_statement - unknown (unexpected)
--- PASS: Wrong_table_definition_binary_export - unknown (unexpected)
--- PASS: Batched_big_statements_do_not_deadlock - unknown (unexpected)
--- PASS: ExecuteScalar_on_connectionless_batch(False) - unknown (unexpected)
--- FAIL: Write_as_ArraySegment_of_char -  (unexpected)
--- PASS: ExecuteReader_on_connectionless_batch(False) - unknown (unexpected)
--- PASS: CreateConnection - unknown (unexpected)
--- FAIL: Truncate -  (unexpected)
--- PASS: Concurrent_use_throws - unknown (unexpected)
--- PASS: Double_prepare_different_sql - unknown (unexpected)
--- PASS: Many_statements_on_unprepare - unknown (unexpected)
--- PASS: Broken_lifecycle(False) - unknown (unexpected)
--- FAIL: Same_command_different_param_values -  (unexpected)
--- FAIL: Wrong_format_raw_binary_copy -  (unexpected)
--- PASS: ExecuteNonQuery_on_connectionless_batch(True) - unknown (unexpected)
--- FAIL: Overloaded_sql -  (unexpected)
--- PASS: Timestamp_write - unknown (unexpected)
--- FAIL: As_string -  (unexpected)
--- FAIL: TimestampTz_write -  (unexpected)
--- PASS: ExecuteReader_on_connectionless_command(True) - unknown (unexpected)
--- PASS: Log_Open_Close_pooled - unknown (unexpected)
--- PASS: Batched_small_then_big_statements_do_not_deadlock_in_sync_io - unknown (unexpected)
--- FAIL: Log_ExecuteScalar_single_statement_without_parameters -  (unexpected)
--- PASS: ExecuteReader_on_connectionless_batch(True) - unknown (unexpected)
--- PASS: Nested - https://github.com/cockroachdb/cockroach/issues/51480 (unexpected)
--- PASS: ExecuteNonQuery_on_connectionless_command(True) - unknown (unexpected)
--- PASS: As_DbDataSource(False) - unknown (unexpected)
--- PASS: Default_IsolationLevel - unknown (unexpected)
--- PASS: As_DbDataSource(True) - unknown (unexpected)
--- PASS: Bug1695 - unknown (unexpected)
--- PASS: Enum - https://github.com/cockroachdb/cockroach/issues/51480 (unexpected)
--- PASS: One_command_same_sql_twice - unknown (unexpected)
--- FAIL: Legacy_batching -  (unexpected)
--- PASS: As_JsonDocument - unknown (unexpected)
--- FAIL: ExecuteScalar_Throws_PostgresException(False) -  (unexpected)
For a full summary look at the npgsql artifacts
An updated blocklist (npgsqlBlocklist) is available in the artifacts' npgsql log
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-sessions
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*npgsql.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24788

### PR DESCRIPTION
**Pull request by rafiss**
Now it accounts for the class name and test name, so that there are no duplicated results during parsing.

---

builtins: add compat implementations for pg_advisory_unlock_*

These can be safely implemented as no-ops, since we don't support the
corresponding lock functions.

I'm adding this because npgsql uses pg_advisory_unlock_all whenever it
returns a connection to its connection pool.

---

fixes https://github.com/cockroachdb/cockroach/issues/97614

Release note: None

### CODE REVIEW

**Review by ZhouXing19 — APPROVED** [review]
LGTM! Just added nit comments.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97626#-:-NPXm1Nf5rVeTz4aneJH:b-8wqyw9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/dotnet_helpers.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97626#-NPXjV2GCJfQJhoyqOlO:-NPXjV2GCJfQJhoyqOlP:b-npouf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cfbba2f29fb2b2225fd94d0a2d50a790e4143e8/pkg/cmd/roachtest/tests/dotnet_helpers.go#L51)):*
> ```Go
> 	}
> 	type UnitTest struct {
> 		Name       string     `xml:"name,attr"`
> ```

nit: this `Name` seems never used. Curious if we added just to make sure the string can be unmarshalled.
___
*[`pkg/cmd/roachtest/tests/dotnet_helpers.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97626#-NPXj_Ji-Pl-2jQ_pnvD:-NPXj_Ji-Pl-2jQ_pnvE:b-poibz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cfbba2f29fb2b2225fd94d0a2d50a790e4143e8/pkg/cmd/roachtest/tests/dotnet_helpers.go#L75)):*
> ```Go
> 	}
> 
> 	// Create mapping from TestID to ClassName+TestName.
> ```

nit: `TestName` made me think this is `UnitTest.Name` but this is actually `testDef.TestMethod.Name`. Can we update the comment?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97626)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @srosenberg, and @ZhouXing19)

___
*[`pkg/cmd/roachtest/tests/dotnet_helpers.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97626#-NPXjV2GCJfQJhoyqOlO:-NPYOP6e09UJrDfUiCh5:b-2qx5fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cfbba2f29fb2b2225fd94d0a2d50a790e4143e8/pkg/cmd/roachtest/tests/dotnet_helpers.go#L51)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: this `Name` seems never used. Curious if we added just to make sure the string can be unmarshalled.
</blockquote></details>

yeah i needed it to do the XML parsing
___
*[`pkg/cmd/roachtest/tests/dotnet_helpers.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97626#-NPXj_Ji-Pl-2jQ_pnvD:-NPYOURu6DO_XoNN0G8y:bdhy48o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cfbba2f29fb2b2225fd94d0a2d50a790e4143e8/pkg/cmd/roachtest/tests/dotnet_helpers.go#L75)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: `TestName` made me think this is `UnitTest.Name` but this is actually `testDef.TestMethod.Name`. Can we update the comment?
</blockquote></details>

i can comment this - `UnitTest.Name` and `testDef.TestMethod.Name` actually are always identical.

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
