### PR TITLE
docs: add pause/resume/cancel all jobs sql diagram

### PR DESCRIPTION
**Pull request by katmayb**
docs: add pause/resume/cancel all jobs sql diagram

Release note: None
Epic: None

### CODE REVIEW

**Comment by kathancox** [comment]
@taroface Do the changes to the files look ok here? I went for the separate diagram for now.

**Comment by kathancox** [comment]
> It looks OK to me, but I'm still not an expert on this. You will want to check that the HTML files are actually updated in `generated-diagrams` from the new bnfs.

@taroface That does not need to be included in the PR though, correct?

**Comment by taroface** [comment]
Correct, no need to include the generated html files in the PR. I've just happened to discover after merging that the files were never updated, and had to further troubleshoot.

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
I suspect this one is gonna need a rebase as there have been several build/CI changes in the last couple months.

**Pull request merged**
