### PR TITLE
release: move email templates to external files

### PR DESCRIPTION
**Pull request by celiala**
"Week -1" emails are going to have some email content variants depending on various cases, e.g. if it's an alpha, number
of blockers, whether we've passed the prep/qualify date, etc.

This commit sets up pattern for creating email templates for different data variants, and for verifying expected
email output via `.golden` files.

### To generate `.golden` files:
- add template test to `pkg/cmd/release/sender_test.go`
- run `go test -v ./pkg/cmd/release -update`

Actual logic to fetch blockers and wire up data to actual email templates will be implemented in a later commit (PR https://github.com/cockroachdb/cockroach/pull/77250).

### Manual testing

Test 1: confirmed that `post-blockers` sends out email:

```
bazel build //pkg/cmd/release
SMTP_PASSWORD=$MY_SMTP_PWD SMTP_USER=$MY_SMTP_USER GITHUB_TOKEN=$MY_GITHUB_TOKEN \
$(bazel info bazel-bin)/pkg/cmd/release/release_/release post-blockers \
  --release-series 21.2 \
  --smtp-user $MY_SMTP_USER --smtp-host smtp.gmail.com --smtp-port 587 \
  --to $MY_TO_EMAIL \
  --template-dir ./pkg/cmd/release/templates \
  --prep-date 2022-10-11 --publish-date 2022-12-13
```

image

Test 2: confirmed that `pick-sha` shows me expected s3 errors (see "modifications" section below)

### Modifications to previous release commands:

Note that because emails are now using external templates, `pick-sha` will now require a `template-dir` parameter, i.e.:

```
bazel build //pkg/cmd/release
SMTP_PASSWORD=foo JIRA_USERNAME=foo JIRA_TOKEN=foo \
$(bazel info bazel-bin)/pkg/cmd/release/release_/release pick-sha \
--dry-run --release-series 21.1 \
--smtp-user foo --smtp-host smtp.gmail.com --smtp-port 587 \
--to release@cockroachlabs.com \
--qualify-bucket foo --qualify-object-prefix foo --release-bucket foo --release-object-prefix foo \
--template-dir ./pkg/cmd/release/templates
```

Release note: None
Release justification: Non-production code change.

### CODE REVIEW

**Comment by celiala** [comment]
Hi @jlinder @rail - this is RFAL, thanks!

**Review by rail — CHANGES_REQUESTED** [review]
Wheee. This looks great. I left some minor comments. Also need to make CI happy - something wrong with the paths I guess.

> Reviewed 37 of 38 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-:-MxFbD7A80cBqEBNWrSg:b-2m4y9e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala and @jlinder)

___
*[pkg/cmd/release/blockers.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFKHyh64ZvX88LKYud:-MxFKHyh64ZvX88LKYue:b-4oe2t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/blockers.go#L40)):*
> ```Go
> 	// TODO: improve flag usage comments
> 	postReleaseSeriesBlockersCmd.Flags().StringVar(&blockersFlags.releaseSeries, releaseSeries, "", "major release series")
> 	postReleaseSeriesBlockersCmd.Flags().StringVar(&blockersFlags.templatesDir, templatesDir, "", "major release series")
> ```

The description has to be updated.
___
*[pkg/cmd/release/blockers.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFKsOsE_SXOKcgDrze:-MxFKSbL1YINRnPJYJod:b-o169tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/blockers.go#L64)):*
> ```Go
> 	}
> 	if blockersFlags.smtpUser == "" {
> 		return fmt.Errorf("either %s environment variable or %s flag should be set", envGithubToken, smtpUser)
> ```

I believe `s/envGithubToken/envSMTPUser/`
___
*[pkg/cmd/release/blockers.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFLQ2Q47K48gcSQcFl:-MxFLQ2Q47K48gcSQcFm:b-80sdmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/blockers.go#L80)):*
> ```Go
> 	}
> 	args := messageDataPostBlockers{
> 		Version:       "v99.9.999 - alpha - 23",
> ```

I assume this is just a stub for now.
___
*[pkg/cmd/release/pick_sha.go, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFLqhu-ZS9is6PMC2q:-MxFLqhu-ZS9is6PMC2r:b-4oe2t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/pick_sha.go#L59)):*
> ```Go
> 	pickSHACmd.Flags().StringVar(&pickSHAFlags.releaseObjectPrefix, releaseObjectPrefix, "", "release candidate object prefix")
> 	pickSHACmd.Flags().StringVar(&pickSHAFlags.releaseSeries, releaseSeries, "", "major release series")
> 	pickSHACmd.Flags().StringVar(&pickSHAFlags.templatesDir, templatesDir, "", "major release series")
> ```

The description has to be updated.
___
*[pkg/cmd/release/templates/post-blockers.html, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFMY7o6hRzd-80Kk34:-MxFMY7o6hRzd-80Kk35:b-6av4d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/templates/post-blockers.html#L1)):*
> ```HTML
> <html>
> ```

Can you rename all html files and use `.gohtml` extension instead? My IDE prefers it :)
___
*[pkg/cmd/release/templates/post-blockers.html, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFMwbq1YP_gdlp79z8:-MxFMwbrDZQbReb-fqLT:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/templates/post-blockers.html#L25)):*
> ```HTML
>     {{ end }}
>     
>     {{ if (eq .Args.TotalBlockers 0) }}
> ```

Nice!
___
*[pkg/cmd/release/sender_test.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFXoBH40pvUv6FE6uo:-MxFXoBH40pvUv6FE6up:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/sender_test.go#L27)):*
> ```Go
> var update = flag.Bool("update", false, "update .golden files")
> 
> // hookGlobal sets `*ptr = val` and returns a closure for restoring `*ptr` to
> ```

Nice!

**Review by celiala — COMMENTED** [review]
Hello, this is RFAL!

* request for changes have been addressed
* making CI happy -- I added the `template\` folder to the `.bazel` file, which did the trick locally. So hopefully that gets CI to pass!
* 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-:-MxewfExBC71WFgQ9Meh:b-whhocf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder and @rail)

___
*[pkg/cmd/release/blockers.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFKHyh64ZvX88LKYud:-MxG3l7kEnFxNke8mGn5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/blockers.go#L40)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

The description has to be updated.
</blockquote></details>

Done.
___
*[pkg/cmd/release/blockers.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFKsOsE_SXOKcgDrze:-MxG3tarDyCmTu7qaV-I:bs7wunb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/blockers.go#L64)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

I believe `s/envGithubToken/envSMTPUser/`
</blockquote></details>

Done..
___
*[pkg/cmd/release/blockers.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFLQ2Q47K48gcSQcFl:-MxG3vfiEHtpneLBp4gO:b93zzvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/blockers.go#L80)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

I assume this is just a stub for now.
</blockquote></details>

Ah, added logic to this commit to derive version and/or have it passed via input parameters (same with prep & release date).
___
*[pkg/cmd/release/pick_sha.go, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFLqhu-ZS9is6PMC2q:-MxG46nk5cwinTrAlZLw:bs7wunb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/pick_sha.go#L59)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

The description has to be updated.
</blockquote></details>

Done..
___
*[pkg/cmd/release/templates/post-blockers.html, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-MxFMY7o6hRzd-80Kk34:-MxH2u8LB_SrZeCqNKOi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a7f2fe6920c0f2b7639b23928930ca12c1ae30a/pkg/cmd/release/templates/post-blockers.html#L1)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Can you rename all html files and use `.gohtml` extension instead? My IDE prefers it :)
</blockquote></details>

Done.

**Review by celiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77062)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder and @rail)

___
*[pkg/cmd/release/blockers.go, line 78 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-Mxf1dU919Se6OfH1I_U:-Mxf1dU919Se6OfH1I_V:b-tlgjnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e07c20c770d0fc986dd83f6e0e5c01698bc28f37/pkg/cmd/release/blockers.go#L78)):*
> ```Go
> 	}
> 	args := messageDataPostBlockers{
> 		Version:       "v99.9.999 - alpha - 23",
> ```

FYI - I wired up logic to get real nextVersion, and ability to pass in prepDate/releaseDate via command line.

(PR to fetch blockers will come in a future PR)

**Review by rail — APPROVED** [review]
:lgtm:
Let's merge if CI agrees :)

> Reviewed 3 of 12 files at r4, 13 of 13 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77062#-:-Mxf3cr_0zgKjcRb-B_Z:b-uf13rd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder)

**Comment by celiala** [comment]
🤔 Bazel CI is failing on:
* `pkg/ccl/logictestccl/logictestccl_test_/logictestccl_test`
But I don't think this was caused by anything in this PR (?). I've tried re-running but Bazel CI is consistently failing on this.

**Comment by celiala** [comment]
I'm seeing `pkg/ccl/logictestccl/logictestccl_test_/logictestccl_test` fail on `master` against 
* https://github.com/cockroachdb/cockroach/commit/d46182c2760f197a0834fe69c79df64e1b5b47c0

I'm going to say this PR is good to merge.


TFTRs!

bors r=rail

**Pull request merged**
