### PR TITLE
distsql: aggregator behavior for no rows

### PR DESCRIPTION
**Pull request by irfansharif**
compatibility with Postgres behavior to return `NULL` if there are no
rows, parity with package sql.

cc @arjunravinarayan.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12046)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql/aggregator.go, line 183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12046#-KYJZe1T-DOJSB-gB97A:-KYJZe1T2HJAba2RFUWL:b-lt58t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/74032f174ee4bb1f85c7eed099a7274b639db3f1/pkg/sql/distsql/aggregator.go#L183)):*
> ```Go
> 		}
> 		for i, datum := range tuple {
> 			encD, err := sqlbase.DatumToEncDatumWithInferredType(datum)
> ```

Can you remove DatumToEncDatumWithInferredType?

---

*[pkg/sql/distsql/aggregator_test.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12046#-KYJZmlQEykKfYtzJ3rS:-KYJZmlQ5Dp5RP_WtNzK:b3valhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae19216450335b2d5d789518eb59fc4273ee8267/pkg/sql/distsql/aggregator_test.go#L50)):*
> ```Go
> 		input    sqlbase.EncDatumRows
> 		expected sqlbase.EncDatumRows
> 	}{
> ```

This change is also fixing the handling of NULL values in the input stream. Can you mention that in a comment and add a testcase? (something that would have paniced in DatumToEncDatumWithInferredType before)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12046)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql/aggregator_test.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12046#-KYJZmlQEykKfYtzJ3rS:-KYJZyET2Ejwg9cp8lg4:b-zd00fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae19216450335b2d5d789518eb59fc4273ee8267/pkg/sql/distsql/aggregator_test.go#L50)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This change is also fixing the handling of NULL values in the input stream. Can you mention that in a comment and add a testcase? (something that would have paniced in DatumToEncDatumWithInferredType before)
</blockquote></details>

Sorry I meant "mention that in the commit"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12046)*

**Comment by irfansharif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsql/aggregator.go, line 183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12046#-KYJZe1T-DOJSB-gB97A:-KYJp7QX5gfQTsWa50tV:bpkyj0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/74032f174ee4bb1f85c7eed099a7274b639db3f1/pkg/sql/distsql/aggregator.go#L183)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you remove DatumToEncDatumWithInferredType?
</blockquote></details>

ah, yes, forgot to check in that change. Done.

---

*[pkg/sql/distsql/aggregator_test.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12046#-KYJZmlQEykKfYtzJ3rS:-KYJs1fu7_pLLQtG4zQJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae19216450335b2d5d789518eb59fc4273ee8267/pkg/sql/distsql/aggregator_test.go#L50)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Sorry I meant "mention that in the commit"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12046)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12046#-:-KYJtv1y-FLoHfJjawTS:bnfp4nl)*

**Pull request merged**
