### PR TITLE
roachtest: skip schemachange step in acceptance/version-upgrade

### PR DESCRIPTION
**Pull request by renatolabs**
Informs: #111844.

Epic: none

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Sorry about the flake!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111845#-:-Ng-ajVCDBstGTcn-SZt:b-qwnn9c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

**Comment by renatolabs** [comment]
TFTR!

bors r=DrewKimball

**Comment by renatolabs** [comment]
Superseded by #111851.

**Pull request closed without merging**
