### PR TITLE
rowexec: minor joinreader cleanup

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/rowexec/joinreader.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59199#-MRZPvE04vkMtoPcvJcB:-MRZPvE04vkMtoPcvJcC:bf8elno) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7497b886636eb72857f88b5392160cfaaa2fe21/pkg/sql/rowexec/joinreader.go#L174)):*
> ```Go
> 		}
> 		if !spec.OnExpr.Empty() {
> 			return nil, errors.AssertionFailedf("non-empty ON expressions are not supported for index joins")
> ```

Should this ever occur? Why are these not supported?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/rowexec/joinreader.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59199#-MRZPvE04vkMtoPcvJcB:-MRb_21k1ZzB1QgUd9PN:b66cc56) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7497b886636eb72857f88b5392160cfaaa2fe21/pkg/sql/rowexec/joinreader.go#L174)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should this ever occur? Why are these not supported?
</blockquote></details>

This will never occur because an index join can only be of INNER type and INNER join with ON condition is equivalent to INNER join followed by a filter (more context [here](https://cockroachlabs.slack.com/archives/C8HD41C82/p1611105764038100)).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59199#-:-MRt0MPx1MLtnFzzpF6b:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
