### PR TITLE
sql/parser: mark all EvalContext-dependent builtins with ctxDependent

### PR DESCRIPTION
**Pull request by knz**
Needed for #13821

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:lgtm: on the additions, and thank you very much for catching this. Of course, I have no idea if this is complete, that is not a thing I can judge as well as you can. You might want to get someone else on the SQL team to verify that the other builtins are not context dependent, since that's the real danger.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15607#-:-Kj9LGnGDABZ-AhRonHI:b-z6wzcj)*

**Comment by knz** [comment]
@arjunravinarayan mind taking this PR over? either integrate in other fixes or merge this when it's green, I'll be afk for a while

**Comment by RaduBerinde** [comment]
LGTM

**Comment by arjunravinarayan** [comment]
@knz I got this, thank you for doing it! @dt can you please take a look at the builtins, see if @knz left any out that should be tagged as `ctxDependent`? With your stamp of approval I can merge this.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15607#-:-Kj9MM2tmP8CY38awOF2:b-9uz2hz)*

**Comment by dt** [comment]
For now:

Can you locally eyeball `git grep -B1 "fn: func(ctx \*EvalContext"` to look at all the fn's that bind `ctx` and ensure the printed preceding line for each is either `ctxDependent: true,` (or change `ctx` to `_` if it doesn't need it and re-run)?

Long Term:
I'd rather see this done by the compiler instead of a brittle convention -- if the question we're tracking is if `fn` is using `ctx` we should assume `fn` is used if it is passed, and if we want it to not use `ctx`, we should not pass it. Concretely: I'd remove the `EvalCtx` from fn signature and add an alternative `fnCtx` field with the current signature, and then you fill the appropriate field in your bultin and we'd derive `ctxDependent` from which one is non-nil.  
I'd TODO and file issue if you don't want to do this now.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15607#-:-Kj9QFE98MEBcuLuY9Df:b8x1gib)*

**Comment by RaduBerinde** [comment]
Hopefully we will be able to pass the right EvalContext in distsql and won't need this flag at all longer term.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15607#-:-Kj9W2YV7FemC2TVubh2:bsrl972)*

**Comment by arjunravinarayan** [comment]
I think Radu is right in that the long term plan is not necessary, since in the long term we intend to remove the whole `ctxDependent` dependency. @dt do you mind doing the local eyeballing? I'm trying to send out a PR partially addressing #13821 today. We can also find someone else looking for 1.0 issues to work on.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15607#-:-Kj9ZOdphztcHgjiEimg:b-42iq4y)*

**Comment by dt** [comment]
Okay, well, local eyeballing says there are _a lot_ missing from this list, which make me even more dubious of this approach. The first few I saw:
* regexp_extract
* regexp_replace x2
* greatest
* least
* age
 * current_date
* statement_timestamp
* cluster_logical_timestamp
* extract
* current_schemas
* crdb_internal.force_internal_error
* pg_get_userbyid

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15607#-:-KjB7SkWObxu1cUEtS9r:b-oago08)*

**Comment by andreimatei** [comment]
Let's go with #15628 instead :P

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15607#-:-KjANJAvXcGbKGYzQdKU:b-w3pgip)*

**Comment by knz** [comment]
To react to the comment above:

>    regexp_extract
>    regexp_replace x2

These merely use a cache, it doesn't matter how it's initialized

>    greatest
>    least

These two just need the DecimalCtx pre-allocated in evalCtx for comparisons, but the default allocated DecimalCtx is OK to use.

>    age

I marked the one variants that needs the txn timestamp  as dependent, the other one doesn't really use its context (the context would be needed for decimal conversions but these are timestamps)

>    current_date
>    statement_timestamp
>    cluster_logical_timestamp

These are already marked in `txnTSImpl`


>    extract

doesn't use the ctx

>    current_schemas

I also marked that one

>    crdb_internal.force_internal_error

Doesn't use the context

>    pg_get_userbyid

Woops yes I missed that one!!

**Comment by dt** [comment]
I'm still not entirely comfortable with the extremely subtle distinctions about when some usage is safe and when it isn't -- it seems likely someone will mess it up -- but if this is a just stopgap with a better solution on the horizon, I withdraw my objections.
 
`extract` looks like it is using it (`ctx.GetLocation()`)  to me? 

:lgtm: 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15607#-:-KjDfZ2TbAFX3sdPZ71I:b-u5jk3m)*

**Comment by knz** [comment]
I'm going to close this in favor of #15628 which seems like a better approach. Thanks for the input everyone.

**Pull request closed without merging**
