### PR TITLE
Rename TestChaos to TestClusterRecovery. Add TestNodeRestart.

### PR DESCRIPTION
**Pull request by vivekmenezes**
TestNodeRestart restarts a single node in the cluster and keeps
track of read/write performance. Read/write performance should be
minimally affected by a node restart.

This change is mostly a refactoring of TestChaos into helper functions so that
we can build more tests using them. I'll add the latency metric to the node restart
test in a followup PR.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4392)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[acceptance/chaos_test.go, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAee8wssbsb4bxCGP5S:-KAee8wssbsb4bxCGP5T:1037381068) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L82)):*
now that this is more modular, could you stop using the flag variables and extend the function signature to something like `transferMoney(client *sql.DB, numAccounts, maxAmount int64)`?

---

*[acceptance/chaos_test.go, line 106 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAeeiaRdoA0BIwaf7jK:-KAeeiaSp5c3dMfrSIp_:951152569) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L106)):*
better to `defer` since you have a `Fatal` above.

---

*[acceptance/chaos_test.go, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAeeuShngn_cJxgIe2F:-KAeeuShngn_cJxgIe2G:1960513358) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L112)):*
only one error is sent, so `errChan chan error`.

---

*[acceptance/chaos_test.go, line 139 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAef7wDA-Q5sste_N-o:-KAef7wDA-Q5sste_N-p:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L139)):*
ditto

---

*[acceptance/chaos_test.go, line 165 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAefMCi4QLkUqNN2iSm:-KAefMCi4QLkUqNN2iSn:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L165)):*
ditto

---

*[acceptance/chaos_test.go, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAehkvnY9Wf1k-Mv0Fv:-KAehkvoQ5EZ_uFpY61f:-876145236) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L228)):*
what happened to the stopper (not unlikely that that's the source of the deadlocks in the current version, but still)

---

*[acceptance/chaos_test.go, line 239 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAeiA1QouZj5QpIl9dp:-KAeiA1QouZj5QpIl9dq:-450686428) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L239)):*
Doesn't it make sense to factor this code out as well? From a cursory glance, it looks like the only difference between your two monkeys is how many nodes they restart. It's easy to set an upper cap on that number.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[acceptance/chaos_test.go, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAee8wssbsb4bxCGP5S:-KAfBcxyPLoh0rAXhRYY:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L82)):*
done

---

*[acceptance/chaos_test.go, line 106 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAeeiaRdoA0BIwaf7jK:-KAfBpw_lCH5D4bxGRc5:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L106)):*
done

---

*[acceptance/chaos_test.go, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAeeuShngn_cJxgIe2F:-KAfBv5ao9x7yvqF5F_8:-567503514) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L112)):*
renamed to errChan and also created a new struct testState to hold stuff used in a few functions that we don't want to pass around individually.

---

*[acceptance/chaos_test.go, line 139 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAef7wDA-Q5sste_N-o:-KAfDG3tT14BDc0mFKP1:-467915377) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L139)):*
fixed

---

*[acceptance/chaos_test.go, line 165 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAefMCi4QLkUqNN2iSm:-KAfDHffNwCmoWPz4Kj2:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L165)):*
done

---

*[acceptance/chaos_test.go, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAehkvnY9Wf1k-Mv0Fv:-KAepnEmArc91gVDONaV:73318053) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L228)):*
I've removed the stopper because it was not needed in the original test. The deadlock was fixed by https://github.com/cockroachdb/cockroach/commit/18a677f67efd80820cfe8315854d7ccb8d11883f

---

*[acceptance/chaos_test.go, line 239 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAeiA1QouZj5QpIl9dp:-KAeq9sE7gM8powj5wYu:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/722bae4f673a4cdfa64faaf8f709646e644b910e/acceptance/chaos_test.go#L239)):*
Done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392)*

**Comment by vivekmenezes** [comment]
This revision is substantial enough that it warrants a review of the entire change.

---

Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-:-KAh4DibK3Q5hpEMw3RK:416941564)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[acceptance/chaos_test.go, line 153 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAoI-qZ3mdsgFZrHPae:-KAoI-qZ3mdsgFZrHPaf:1335632422) ([raw file](https://github.com/cockroachdb/cockroach/blob/05138416c7525e68796aec35d5882d7ba61e7b4f/acceptance/chaos_test.go#L153)):*
seems odd to pass in `state` and `idx` - why not pass the client? Ah, you need `state.Done`.

---

*[acceptance/chaos_test.go, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAoJ35j81VXV6SOu3SL:-KAoJ35j81VXV6SOu3SM:1912390833) ([raw file](https://github.com/cockroachdb/cockroach/blob/05138416c7525e68796aec35d5882d7ba61e7b4f/acceptance/chaos_test.go#L156)):*
nit: i'd get rid of this function - you only need to hold the lock for the `transferMoney` call, and that never panics

---

*[acceptance/chaos_test.go, line 184 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAoJWM3YZyi5hLJuJBt:-KAoJWM3YZyi5hLJuJBu:605336621) ([raw file](https://github.com/cockroachdb/cockroach/blob/05138416c7525e68796aec35d5882d7ba61e7b4f/acceptance/chaos_test.go#L184)):*
slight modification will let you do this in one fewer atomic operation:
```
curRound := 0
for atomic.StoreUint64(&state.monkeyIteration, curRound); !state.done(); {
  curRound := atomic.SwapUint64(&state.monkeyIteration, curRound+1)
  ...
}

---

*[acceptance/chaos_test.go, line 213 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAoKUnpZuK_VWroNhfm:-KAoKUnpZuK_VWroNhfn:-465122004) ([raw file](https://github.com/cockroachdb/cockroach/blob/05138416c7525e68796aec35d5882d7ba61e7b4f/acceptance/chaos_test.go#L213)):*
it is not safe to call (*testing.T).Fatal from the non-main goroutine, which i believe this is.

Also this will panic while holding locks, which can lead to a deadlock.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392)*
<!-- Sent from Reviewable.io -->

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[acceptance/chaos_test.go, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAoJ35j81VXV6SOu3SL:-KAp2yKFd7HQB84UkG2C:851849061) ([raw file](https://github.com/cockroachdb/cockroach/blob/05138416c7525e68796aec35d5882d7ba61e7b4f/acceptance/chaos_test.go#L156)):*
done. Much cleaner!

---

*[acceptance/chaos_test.go, line 184 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAoJWM3YZyi5hLJuJBt:-KAp58zFEaL95DC6SUXW:-1179321904) ([raw file](https://github.com/cockroachdb/cockroach/blob/05138416c7525e68796aec35d5882d7ba61e7b4f/acceptance/chaos_test.go#L184)):*
Fixed. I've simplified it even further using:

for currRound := 1; !state.done(); currRound++ {
    atomic.StoreUint64(&state.monkeyIteration, curRound)

---

*[acceptance/chaos_test.go, line 213 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAoKUnpZuK_VWroNhfm:-KAp76KdIQPdxrH1I5dU:357081909) ([raw file](https://github.com/cockroachdb/cockroach/blob/05138416c7525e68796aec35d5882d7ba61e7b4f/acceptance/chaos_test.go#L213)):*
Yeah t.FailNow can only be called from the main goroutine. Fortunately T.Error() can be called from anywhere.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392)*

**Comment by vivekmenezes** [comment]
@tschottdorf any more comments? Thanks

**Comment by tschottdorf** [comment]
LGTM. Sorry I let this sit.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[acceptance/chaos_test.go, line 357 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAqPqk8dY4BVxXJSLho:-KAqPqk8dY4BVxXJSLhp:-257850456) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c28ad1c7c2875d7c827621772f7a7a6d447411/acceptance/chaos_test.go#L357)):*
Add that the restarted node isn't the one that the client is writing on. Don't you want to restart a minority in each round?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-:-KAqQ43YxWB58iQiQN5N:145757640)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392)*

**Comment by vivekmenezes** [comment]
Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/chaos_test.go, line 357 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAqPqk8dY4BVxXJSLho:-KArJI1VRk6jqEfGRzxN:39386800) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c28ad1c7c2875d7c827621772f7a7a6d447411/acceptance/chaos_test.go#L357)):*
Done. I've picked one node for the now because a single node restarting continues to guarantee quorum on all ranges.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-:-KArJT_yG4KJIOhciGPq:-1834867277)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/chaos_test.go, line 357 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAqPqk8dY4BVxXJSLho:-KArY24cqqa5MoRF-SRq:-358050271) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c28ad1c7c2875d7c827621772f7a7a6d447411/acceptance/chaos_test.go#L357)):*
No, not with `<3` nodes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/chaos_test.go, line 357 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAqPqk8dY4BVxXJSLho:-KAr_8eudSL7WwmHkhxB:2090061130) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c28ad1c7c2875d7c827621772f7a7a6d447411/acceptance/chaos_test.go#L357)):*
This test should not need to run in < 3 node clusters.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[acceptance/chaos_test.go, line 357 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392#-KAqPqk8dY4BVxXJSLho:-KAronFMK4F7qA5PIuPV:-531931162) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c28ad1c7c2875d7c827621772f7a7a6d447411/acceptance/chaos_test.go#L357)):*
Then it should skip itself in that case and not just fail.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4392)*

**Pull request merged**
