### PR TITLE
pgwire: accept non-TLS client conns safely in secure mode

### LINKED ISSUE #44842: cli,server: enable SQL clients on TCP with non-TLS modes
Today CockroachDB requires TLS for all client connections on TCP soon as a cluster is runnign securely.

(Unix socket connections already do not require TLS).

As discussed in https://github.com/cockroachdb/cockroach/issues/16188#issuecomment-571191964 and following, it may be interesting to introduce an alternate listener when the network environment (e.g. k8s) provides its own layer of transport security.

When this becomes available, the authentication should be configurable in a different way than TLS certificates (for example, to require passwords).

PostgreSQL already supports this by distinguishing `hostssl` and `hostnossl` rules in the HBA configuration. CockroachDB could do something similar.

Note that this enhancement does not require separate listeners, because the pg protocol already supports mixed TLS / non-TLS connections over a single port.

### PR DESCRIPTION
**Pull request by knz**
Fixes cockroachdb/cockroach#44842.
Informs cockroachdb/helm-charts#228. 
Informs cockroachdb/cockroach#53404.

This change makes it possible for a DBA / system administrator to
reconfigure individual nodes *in a secure cluster* to accept SQL
client sessions over TCP without mandating a TLS
handshake. Authentication remains mandatory as per the HBA rules.

Motivation: we have at least two high-profile customers who keep their
nodes and client apps in a private secure network (with network-level
encryption / privacy) and who experience client-side TLS as
unnecessary and expensive friction.

Additionally, **this feature is a prerequisite to upgrade an insecure
cluster to secure mode without downtime.**

Why this does not impair security:

- authentication remains mandatory (as per the HBA rules -- [1] [2]).
- the feature is opt-in: the operator must set a command-line flag
  (`--accept-sql-without-tls`), which is not enabled by default.
- there is an interlock: the user must both set up the flag
  and set log-in passwords for their SQL users (by default,
  users get created without a password and thus cannot log
  in without client certs).
- for now, node-node connections still require TLS.

[1]: https://www.postgresql.org/docs/12/auth-pg-hba-conf.html
[2]: https://dr-knz.net/authentication-in-postgresql-and-cockroachdb.html

For context, the default HBA configuration is the following:

```
host  all root all cert-password # fixed rule
host  all all  all cert-password # built-in CockroachDB default
local all all      password      # built-in CockroachDB default
```

The directive `host` covers both TLS and non-TLS incoming TCP
connections (`local` is for the unix socket). The method
`cert-password` means "client cert or password": without a cert, the
password is mandatory.

As previously, the user can further secure the configuration by
restricting non-TLS connections to just a subnetwork, for example:

```
host  all all 10.0.0.0/8 password # accept conns on the 10/8 network.
host  all all all        reject   # refuse conns from other nets.
local all all            password
```

Note that this change is limited to the server side: CockroachDB's own
`cockroach` CLI commands do not yet know how to connect to a
CockroachDB server without TLS; such connections are only supported
from `psql` or SQL client drivers in apps. See cockroachdb/cockroach#53994 for a follow-up.

Release justification: fixes for high-priority or high-severity bugs in existing functionality

### CODE REVIEW

**Comment by knz** [comment]
@bdarnell @petermattis I'd like to petition for this PR to be included in the 20.2 release, even though it is coming late in the cycle. This had been tracked before, but we have only learned in the past few days how important this feature is to our customers and why the security impact is minimal (as described in the commit message). Moreover, the code change is minimal (1 conditional) and the feature is opt-in.

**Comment by knz** [comment]
cc @thtruo for tracking

**Review by irfansharif — APPROVED** [review]
The code changes LGTM. Thanks for the detailed write up in your commit message, it was instructive!

> Reviewed 1 of 1 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-:-MGi7gAO2DCy_Uqs_UIY:b-36gv8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @knz)

___
*[pkg/sql/pgwire/testdata/auth/secure_non_tls, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGi3bcp5aBNN03gnoYt:-MGi3bcp5aBNN03gnoYu:bqdxgj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/testdata/auth/secure_non_tls#L18)):*
> ```
> ----
> 
> # Since root and testuser do not have a password, they stil
> ```

typo: still.
___
*[pkg/sql/pgwire/testdata/auth/secure_non_tls, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGi3kwZ6NoH3AD5c-FK:-MGi3kwZ6NoH3AD5c-FL:b-8r9yez) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/testdata/auth/secure_non_tls#L49)):*
> ```
> # Active authentication configuration on this node:
> # Original configuration:
> # host  all root all cert-password # CockroachDB mandatory rule
> ```

I think the column alignment here is a bit off.

**Comment by aaron-crl** [comment]
Code and feature :LGTM:.

**Review by bdarnell — APPROVED** [review]
> To introduce this feature into an existing cluster, proceed as
follows:

Using this feature on a new cluster is awkward (assuming you want to use the `hostnossl` directive to restrict non-TLS access to a certain network). You have to start the cluster without the command-line flag, connect with TLS to set the new `hba.conf`, then restart the cluster with the flag.

Instead, if the default `hba.conf` were more restrictive, say by defaulting to localhost-only, the process would be to start the cluster with the flag, then connect from localhost without TLS to set a less-restrictive `hba.conf`. (but if you're unable to easily connect from localhost, which may be an issue in some orchestrated environments, you may be back to the more complicated procedure)


On the other hand, are these `hba.conf` settings even necessary? A user who is comfortable with this flag is presumably practicing some sort of perimeter-based security, in which case I would expect that only the trusted part of the network is able to route packets to the database (and even if untrusted machines were able to talk to the database, they'd still need a valid password to get in). Unless we have specific user requests for this capability, I might leave the `hba.conf` out. 

> Reviewed 11 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-:-MGjQacP3A9i0Uk5-Bja:b1eyzp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl and @knz)

___
*[pkg/cli/flags.go, line 350 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjNhgE-ihFBGlRKOwn:-MGjNhgF0YaX1TBL8gY2:b-1xzp82) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/cli/flags.go#L350)):*
> ```Go
> 		varFlag(f, addrSetter{&serverHTTPAddr, &serverHTTPPort}, cliflags.ListenHTTPAddr)
> 		stringFlag(f, &serverSocketDir, cliflags.SocketDir)
> 		boolFlag(f, &startCtx.unencryptedLocalhostHTTP, cliflags.UnencryptedLocalhostHTTP)
> ```

It's unfortunate that `--unencrypted-localhost-http` combines non-TLS access with restricting the port to the loopback interface. It would be nice to split that up some day (but not today - I think there are a number of cleanups we could make to the network configuration flags)
___
*[pkg/cli/cliflags/flags.go, line 540 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjOYsF95zOQIDxdsgM:-MGjOYsGA8SGaKK8Ybqb:b-c7wf3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/cli/cliflags/flags.go#L540)):*
> ```Go
> 	}
> 
> 	AllowSecureSQLWithoutTLS = FlagInfo{
> ```

It always smells bad to me when the FlagInfo variable name and the flag itself don't match. Consider removing the word `Secure` here. 
___
*[pkg/cli/cliflags/flags.go, line 541 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjSbO51ROnKzGIDFwj:-MGjSbO51ROnKzGIDFwk:b-622320) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/cli/cliflags/flags.go#L541)):*
> ```Go
> 
> 	AllowSecureSQLWithoutTLS = FlagInfo{
> 		Name: "accept-sql-without-tls",
> ```

In the counterpart PR #53994, the flag name makes it clear that passwords will be sent unencrypted. Should we do more to make that clear with the server-side flag? 
___
*[pkg/sql/pgwire/auth_test.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjOvEe07bH-nt7qD69:-MGjOvEe07bH-nt7qD6A:b-hlnqbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/auth_test.go#L56)):*
> ```Go
> //       the test file is applicable to both.)
> //
> // allow_non_tls
> ```

nit: Consider `s/non/without/` for consistency with the other variables.
___
*[pkg/sql/pgwire/hba_conf.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjPRuXAWAiDSf2zdjr:-MGjPRuXAWAiDSf2zdjs:b-3h7ts4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/hba_conf.go#L153)):*
> ```Go
> 				)
> 			}
> 		case hba.ConnHostSSL, hba.ConnHostNoSSL:
> ```

Maybe I'm just unfamiliar with this code, but I don't see where the `hostssl` and `hostnossl` directives are actually used. 
___
*[pkg/sql/pgwire/testdata/auth/secure_non_tls, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjPnSMDBiDupQ6yV9r:-MGjPnSMDBiDupQ6yV9s:b-jt3tjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/testdata/auth/secure_non_tls#L35)):*
> ```
> ok
> 
> # Now testuser can log in.
> ```

Add a test to verify that testuser can't log in with an invalid password.

**Review by knz — COMMENTED** [review]
Thank you Ben I was also waiting for you to chime in before moving forward with this.

> Using this feature on a new cluster is awkward (assuming you want to use the hostnossl directive to restrict non-TLS access to a certain network). You have to start the cluster without the command-line flag, connect with TLS to set the new hba.conf, then restart the cluster with the flag.

Good point. You're right but I believe, based on the next paragraph, that you were *accidentally* right. I'll clarify in the release note. This would be improved if we ever solve #26722 . 

> Instead, if the default hba.conf were more restrictive, say by defaulting to localhost-only, the process would be to start the cluster with the flag, then connect from localhost without TLS to set a less-restrictive hba.conf. 

No that's not true - even if the SQL client can establish the connection, `root` still cannot log in: without a valid TLS client cert, root would need a password, and there is no password by default. We'd need a `trust` rule in the HBA config to log in without a password, but I'm feeling icky about that.

Which means that above you probably didn't meanm "you need to start the cluster without the flag to connect". In fact, you can connect with the flag just fine using the unix datagram socket and the default HBA config. However, you cannot *log in* as long as the password is not set.

This is why #26722 is so important: not just to customize the HBA conf, but also to set a `root` password.
 
> A user who is comfortable with this flag is presumably practicing some sort of perimeter-based security, in which case I would expect that only the trusted part of the network is able to route packets to the database (and even if untrusted machines were able to talk to the database, they'd still need a valid password to get in). 

This was motivated by the general principle of defense in depth.

> Unless we have specific user requests for this capability, I might leave the hba.conf out.

I can leave it out of the release note, but I think the code is more natural to read this way (and closer to pg).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-:-MGjXsJ0E_H6VMwfz49-:bq3lxlg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl, @bdarnell, and @knz)

___
*[pkg/cli/flags.go, line 350 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjNhgE-ihFBGlRKOwn:-MGjZ0GD0B4ZUbfG_AsK:b-pbdqz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/cli/flags.go#L350)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's unfortunate that `--unencrypted-localhost-http` combines non-TLS access with restricting the port to the loopback interface. It would be nice to split that up some day (but not today - I think there are a number of cleanups we could make to the network configuration flags)
</blockquote></details>

Agreed.
___
*[pkg/cli/cliflags/flags.go, line 541 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjSbO51ROnKzGIDFwj:-MGjZ33wD2yhUMsKKCu_:bdw03qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/cli/cliflags/flags.go#L541)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In the counterpart PR #53994, the flag name makes it clear that passwords will be sent unencrypted. Should we do more to make that clear with the server-side flag? 
</blockquote></details>

What do you have in mind?
___
*[pkg/sql/pgwire/hba_conf.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjPRuXAWAiDSf2zdjr:-MGjZ6Oh03l9OwCB48S9:bk4pweb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/hba_conf.go#L153)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Maybe I'm just unfamiliar with this code, but I don't see where the `hostssl` and `hostnossl` directives are actually used. 
</blockquote></details>

The code to check them was already implemented in 20.1 and used internally in unit tests, but the condition was never encountered in a running server because of the conditional in `server.go`.

**Review by bdarnell — COMMENTED** [review]
> Which means that above you probably didn't meanm "you need to start the cluster without the flag to connect". 

I didn't mean you have to start the cluster without the flag *in order to* connect; you have to start the cluster without the flag to avoid temporarily exposing non-TLS SQL sessions on unintended networks. It's true that it's accidentally safe because there are no users with passwords by default, but that's something we need to fix anyway (it's a prerequisite for #51991 cert-free setup). And when we set up a default user with a password, it becomes necessary to use this two-restart dance for new clusters *if* we accept the requirement that users need to be able to restrict non-TLS connections by IP range.

So that's why I'd prefer to reject this requirement unless we have a more explicit indication that it's important (especially if this is to be a last-minute addition to a release, which I'm not thrilled with. New flags are surface area we have to support for a long time, and if we're doing a wholesale change to the security setup model with #51991 in the next release I'm not sure it's a good idea to add a couple more knobs to the old scheme without time to really validate the interface in this release)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-:-MGnqw5M7YC1EHhMX3kO:b-g76fs8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl, @bdarnell, and @knz)

___
*[pkg/cli/cliflags/flags.go, line 541 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjSbO51ROnKzGIDFwj:-MGnsqxY7p_rsVybyZ2e:b-9d87g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/cli/cliflags/flags.go#L541)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What do you have in mind?
</blockquote></details>

I'm not sure; everything I can think of seems very cumbersome. But again coming back to the scram discussion from #53994, it seems likely that in the future we'd want to allow non-TLS connections only if we're able to use scram for authentication. Maybe just make the flag `--allow-unencrypted-passwords` for both client and server? 
___
*[pkg/sql/pgwire/hba_conf.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjPRuXAWAiDSf2zdjr:-MGntXtS44o8bLEm_V_J:b-eojpk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/hba_conf.go#L153)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The code to check them was already implemented in 20.1 and used internally in unit tests, but the condition was never encountered in a running server because of the conditional in `server.go`.
</blockquote></details>

A cluster version check for this seems excessive to me, but OK.

**Review by knz — COMMENTED** [review]
> you have to start the cluster without the flag to avoid temporarily exposing non-TLS SQL sessions on unintended networks

Not exactly. The user can still limit somewhat with `--listen-addr=` to localhost or something like that.
Also we should really talk about #26722 which would solve both this and facilitate #51991 like you point out.

> So that's why I'd prefer to reject this requirement ... not sure it's a good idea to add a couple more knobs

For context we're focusing on the `hostnossl` and `hostssl` rule match right? These are pg-compatible directives and the logic for them was already implemented in v20.1. What is new here is that the code path is activated. The user doesn't even have to know about them since `host` matches both TLS and non-TLS and they could use that already.

So I'll take your hint we dont want to *talk* about them and removed them from the release note.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-:-MGrtb3s0J9Z2-XK8FYc:brsugq8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aaron-crl, @bdarnell, and @irfansharif)

___
*[pkg/cli/cliflags/flags.go, line 540 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjOYsF95zOQIDxdsgM:-MGrsX9y5FOhsAdLoDG1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/cli/cliflags/flags.go#L540)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It always smells bad to me when the FlagInfo variable name and the flag itself don't match. Consider removing the word `Secure` here. 
</blockquote></details>

Done.
___
*[pkg/cli/cliflags/flags.go, line 541 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjSbO51ROnKzGIDFwj:-MGrsZvtEH0fAFaEERel:bean2of) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/cli/cliflags/flags.go#L541)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm not sure; everything I can think of seems very cumbersome. But again coming back to the scram discussion from #53994, it seems likely that in the future we'd want to allow non-TLS connections only if we're able to use scram for authentication. Maybe just make the flag `--allow-unencrypted-passwords` for both client and server? 
</blockquote></details>

These are two fully unrelated concerns. 
SCRAM would work equally well with or without TLS. SCRAM doesn't need a flag.

The flag here is introduced to ensure that a cluster does not get mistaknely started without TLS, unless the user opts in explicitly.
___
*[pkg/sql/pgwire/auth_test.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjOvEe07bH-nt7qD69:-MGrsoxrA57HvTNXW7rL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/auth_test.go#L56)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

nit: Consider `s/non/without/` for consistency with the other variables.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/hba_conf.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjPRuXAWAiDSf2zdjr:-MGrsulK4xHypzz5cPjd:b77vhux) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/hba_conf.go#L153)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

A cluster version check for this seems excessive to me, but OK. 
</blockquote></details>

We discovered last time it is necessary: the other not-yet-upgraded nodes in the cluster would choke if they see a new keyword they don't understand in the HBA config.
___
*[pkg/sql/pgwire/testdata/auth/secure_non_tls, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGi3bcp5aBNN03gnoYt:-MGrt3bYCoFx6mj2T-rr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/testdata/auth/secure_non_tls#L18)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

typo: still.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/testdata/auth/secure_non_tls, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGjPnSMDBiDupQ6yV9r:-MGrtBLf3HeYxZbdRL-R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/testdata/auth/secure_non_tls#L35)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add a test to verify that testuser can't log in with an invalid password. 
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/testdata/auth/secure_non_tls, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53991#-MGi3kwZ6NoH3AD5c-FK:-MGrtLQm2shCpESmB1pe:b-qbolf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b0882272fe3c2bf0d65f230f073d41616249bd0/pkg/sql/pgwire/testdata/auth/secure_non_tls#L49)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I think the column alignment here is a bit off.
</blockquote></details>

this is auto-generated. If there's an improvement to be made it doesn't belong to this PR.

**Comment by knz** [comment]
bors r=aaron-crl,irfansharif,bdarnell

**Pull request merged**
