### PR TITLE
ui: reduce boilerplate in makeFetch

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6947)

### CODE REVIEW

**Comment by maxlang** [comment]
Originally I wrote the code like this but I think the current code is simpler and reads better. The boilerplate is minimal and you save almost nothing by making `makeFetch` generic. Case in point, your code saves only 10 characters. I appreciate the thought, however, since it definitely _feels_ like it should be written this way.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> #### ui: reduce boilerplate in makeFetch
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6947#-:-KIn7f0tp3wY0-E6wrte:-916463789)*

**Comment by tamird** [comment]
I don't follow this. It's not really about the amount of code saved, it's about the locality of the type of the request to the type of the response's constructor. When/if we change this to use protos, we're going to need to change every one of these calls to makeFetch (with the current code). The new code centralizes this knowledge, and that's both easier to change and easier to read (because all the requisite knowledge is function-local).

<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Originally I wrote the code like this but I think the current code is simpler and reads better. The boilerplate is minimal and you save almost nothing by making `makeFetch` generic. Case in point, your code saves only 10 characters. I appreciate the thought, however, since it definitely _feels_ like it should be written this way.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6947#-:-KInK3jhqWdVIZinMGgb:393513385)*

**Comment by maxlang** [comment]
If you want to centralize the JSON/ArrayBuffer knowledge, why not:

```
let responseAccessor = "json"; //TODO: use "arrayBuffer" for protos;
function makeFetch...

...
res[responseAccessor]<DatabasesResponse>()

```

The way the old code was written the endpoints read much better:

Request type, endpoint, response type, response message builder

vs

Request type, response message type, response builder class, endpoint

But ultimately this feels like premature optimization because we only have 4 endpoints here.
 

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I don't follow this. It's not really about the amount of code saved, it's about the locality of the type of the request to the type of the response's constructor. When/if we change this to use protos, we're going to need to change every one of these calls to makeFetch (with the current code). The new code centralizes this knowledge, and that's both easier to change and easier to read (because all the requisite knowledge is function-local).
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6947#-:-KInLJduXFgiaD_ZnvI0:1366799758)*

**Comment by tamird** [comment]
The code you posted above doesn't make any sense - you can't `res["arrayBuffer"]<DatabasesResponse>()` - that's not a thing.

I want to clarify that I rewrote this code while debugging a compilation failure, and found the existing code very difficult to parse out. The point is that the current code requires modification in N places to switch the transport type, and this new code requires modification in a single place. This will be especially useful when we switch to protobuf but occasionally want to use JSON for development.

<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> If you want to centralize the JSON/ArrayBuffer knowledge, why not:
> 
> ```
> let responseAccessor = "json"; //TODO: use "arrayBuffer" for protos;
> function makeFetch...
> 
> ...
> res[responseAccessor]<DatabasesResponse>()
> 
> ```
> 
> The way the old code was written the endpoints read much better:
> 
> Request type, endpoint, response type, response message builder
> 
> vs
> 
> Request type, response message type, response builder class, endpoint
> 
> But ultimately this feels like premature optimization because we only have 4 endpoints here.
>  
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6947#-:-KInPEGJB9LywvTg3DSe:881473228)*

**Comment by maxlang** [comment]
Ah good point, you can't type the arraybuffer like that.

:lgtm:

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> The code you posted above doesn't make any sense - you can't `res["arrayBuffer"]<DatabasesResponse>()` - that's not a thing.
> 
> I want to clarify that I rewrote this code while debugging a compilation failure, and found the existing code very difficult to parse out. The point is that the current code requires modification in N places to switch the transport type, and this new code requires modification in a single place. This will be especially useful when we switch to protobuf but occasionally want to use JSON for development.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6947#-:-KInUHk1yGv3nvefZy5y:-1135125939)*

**Pull request merged**
