### PR TITLE
ttl: test multiple TTL storage param changes

### LINKED ISSUE #88560: TTL storage param changes are temporarily visible before schema change rollback
Some test assertions that check the table schema after an `ALTER TABLE x SET (ttl_*)`/`ALTER TABLE x RESET (ttl_*)` commits, but before the corresponding schema changer mutation commits are commented out in #88260.

The schema changer logic needs to be debugged after uncommenting them to figure out why this is happening.

Jira issue: CRDB-19838

Epic CRDB-14592

### PR DESCRIPTION
**Pull request by ecwall**
fixes https://github.com/cockroachdb/cockroach/issues/88560

Add tests to cover multiple changes to TTL storage params.

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice tests, thanks!

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88714#-:-NCv36bPBXyUM3_hQC-E:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall)

**Comment by ecwall** [comment]
bors r=rafiss,ajwerner

**Comment by ecwall** [comment]
bors r=rafiss,ajwerner

**Pull request merged**
