### PR TITLE
opt: fix ON filter reduction in GenerateInvertedJoins

### LINKED ISSUE #59859: opt: panic in GenerateInvertedJoins with multi-column inverted indexes
Looks like we're calling ExtractRemainingJoinFilters with an empty `rightEq` list in some cases in `GenerateInvertedJoins`.

#### To reproduce:

```
exec-ddl
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT,
  b INT,
  j JSON,
  INVERTED INDEX (a, j)
)
----

exec-ddl
CREATE TABLE small (
  k INT PRIMARY KEY,
  j JSON
)
----

opt
SELECT small.k, t.k FROM small INNER INVERTED JOIN t ON t.a = 1 AND t.j @> small.j AND t.b = small.k
----
```

#### Stacktrace:

```
    --- FAIL: TestRules/__test (0.00s)
        opt_tester.go:506: testdata/rules/__test:45: runtime error: index out of range [0] with length 0
            (1) assertion failure
            Wraps: (2) attached stack trace
              -- stack trace:
              | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize.func1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:205
              | runtime.gopanic
              |         /usr/local/opt/go/libexec/src/runtime/panic.go:969
              | runtime.goPanicIndex
              |         /usr/local/opt/go/libexec/src/runtime/panic.go:88
              | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ExtractRemainingJoinFilters
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/extract.go:265
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).GenerateInvertedJoins.func1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:577
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*scanIndexIter).ForEachStartingAfter
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:258
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*scanIndexIter).ForEach
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:186
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).GenerateInvertedJoins
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:488
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreInnerJoin
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.og.go:632
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreGroupMember
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.og.go:24
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreGroup
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.go:182
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroup
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:464
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeExpr
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:251
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:506
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroup
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:451
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:225
              | github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester.(*OptTester).optimizeExpr
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester/opt_tester.go:1645
              | github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester.(*OptTester).Optimize
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester/opt_tester.go:981
              | github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester.(*OptTester).RunCommand
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester/opt_tester.go:504
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform_test.runDataDrivenTest.func1.1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer_test.go:234
              | github.com/cockroachdb/datadriven.runDirective.func1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:321
              | github.com/cockroachdb/datadriven.runDirective
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:326
              | github.com/cockroachdb/datadriven.runDirectiveOrSubTest
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:195
              | github.com/cockroachdb/datadriven.runTestInternal
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:168
              | github.com/cockroachdb/datadriven.RunTest
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:136
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform_test.runDataDrivenTest.func1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer_test.go:231
              | github.com/cockroachdb/datadriven.Walk
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:413
              | github.com/cockroachdb/datadriven.Walk.func1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:426
              | testing.tRunner
              |         /usr/local/opt/go/libexec/src/testing/testing.go:1123
              | runtime.goexit
              |         /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1374
            Wraps: (3) runtime error: index out of range [0] with length 0
              | -- cause hidden behind barrier
              | runtime error: index out of range [0] with length 0
              | (1) runtime error: index out of range [0] with length 0
              | Error types: (1) runtime.boundsError
            Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *barriers.barrierError
```

### PR DESCRIPTION
**Pull request by mgartner**
This commit fixes a bug in the logic of GenerateInvertedJoins that
removes redundant ON filters when those filters were used to constrain
non-inverted prefix columns of a multi-column inverted index. The bug
resulted in a panic in `memo.ExtractRemainingJoinFilters` when two lists
of columns of unequal lengths were passed to the function. This function
now explicitly checks for equal list lengths, which catches the bug in
existing tests even though existing tests didn't previously trigger a
panic. I've also added a regression test that panicked before the bug
fix in this commit.

The length check added to `memo.ExtractRemainingJoinFilters` also caught
a bug where the list of right equality columns was re-used for
successive iterations over inverted indexes. This prevented redundant ON
filters from being removed in some cases. An existing test's output
changed, highlighting the issue.

There is no release note because this bug only affects queries on tables with
multi-column inverted indexes. Multi-column inverted indexes have been
gated behind an experimental session setting in all previous 21.1 alpha
releases.

Fixes #59859

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/xform/join_funcs.go, line 577 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59868#-MSoPpzT1ZkaDj1bWhgc:-MSoPpzT1ZkaDj1bWhgd:bogxndi) ([raw file](https://github.com/cockroachdb/cockroach/blob/584e8948b6359ede7b0d32b8441a5889b8ac27a1/pkg/sql/opt/xform/join_funcs.go#L577)):*
> ```Go
> 		// Remove redundant filters from the ON condition if non-inverted prefix
> 		// columns were constrained by equality filters.
> 		filtersCopied := false
> ```

This seems kind of brittle .... I would probably just change `RemoveCommonFilters` to always make a copy (or create a new function that does), and get rid of he `filtersCopied` boolean. It has the potential to cause one extra allocation, but seems worth it for the simplicity.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/join_funcs.go, line 577 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59868#-MSoPpzT1ZkaDj1bWhgc:-MSogEg1Dowpvn-XjaUQ:b5a29nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/584e8948b6359ede7b0d32b8441a5889b8ac27a1/pkg/sql/opt/xform/join_funcs.go#L577)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This seems kind of brittle .... I would probably just change `RemoveCommonFilters` to always make a copy (or create a new function that does), and get rid of he `filtersCopied` boolean. It has the potential to cause one extra allocation, but seems worth it for the simplicity.
</blockquote></details>

Good point. This was a mess. I've replaced `RemoveCommonFilters` with a `Difference` function.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59868#-:-MSsm-pH0QBFjZLrNSsO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/memo/expr.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59868#-MSsl5In0ezZrVA_g2a0:-MSsl5In0ezZrVA_g2a1:bom38pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2789b6e0f7549fdf38e93e392b80d7578d13ce56/pkg/sql/opt/memo/expr.go#L255)):*
> ```Go
> }
> 
> // Difference returns a new list filters containing the filters of n that are
> ```

[nit] list of
___
*[pkg/sql/opt/xform/join_funcs.go, line 324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59868#-MSsn0PHBIywnqhDGHt6:-MSsn0PHBIywnqhDGHt7:bx6hci7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804b257e67f743413ec34f2a0232d100f2b748d/pkg/sql/opt/xform/join_funcs.go#L324)):*
> ```Go
> 		// constrained by equality filters or constant filters.
> 		lookupJoin.On = onFilters
> 		if len(rightSideCols) > 0 || len(constFilters) > 0 {
> ```

Do you need this check? If you're worried about unnecessary computation in `ExtractRemainingJoinFilters`, maybe it's worth adding a check at the top of that function that `len(leftEq) > 0`.
___
*[pkg/sql/opt/xform/join_funcs.go, line 581 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59868#-MSsnhbgDlFy5gURa0lt:-MSsnhbgDlFy5gURa0lu:b-5ouup3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804b257e67f743413ec34f2a0232d100f2b748d/pkg/sql/opt/xform/join_funcs.go#L581)):*
> ```Go
> 		// Remove redundant filters from the ON condition if non-inverted prefix
> 		// columns were constrained by equality filters or constant filters.
> 		if len(rightSideCols) > 0 || len(constFilters) > 0 {
> ```

Ditto - do we really need this check?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59868)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/expr.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59868#-MSsl5In0ezZrVA_g2a0:-MT1pMAc2UsogXDmy8_C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2789b6e0f7549fdf38e93e392b80d7578d13ce56/pkg/sql/opt/memo/expr.go#L255)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] list of
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_funcs.go, line 324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59868#-MSsn0PHBIywnqhDGHt6:-MT1oqcj7b_wqRMv_ggJ:b-pmm7jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804b257e67f743413ec34f2a0232d100f2b748d/pkg/sql/opt/xform/join_funcs.go#L324)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you need this check? If you're worried about unnecessary computation in `ExtractRemainingJoinFilters`, maybe it's worth adding a check at the top of that function that `len(leftEq) > 0`.
</blockquote></details>

Oops... For a lookup join, this condition is always true. I've removed and added the check to ExtractRemainingJoinFilters.
___
*[pkg/sql/opt/xform/join_funcs.go, line 581 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59868#-MSsnhbgDlFy5gURa0lt:-MT1pDKq0H-5psshANUo:b-ss7tb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804b257e67f743413ec34f2a0232d100f2b748d/pkg/sql/opt/xform/join_funcs.go#L581)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ditto - do we really need this check?
</blockquote></details>

Nope. Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59868#-:-MT1vJ_zAOyRHtNVT1eX:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
