### PR TITLE
tree: implement casts between box2d and geometry

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): Implement the ability to cast between box2d
and geometry types.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52965#-:-MF0HiztC0RKfNzKcM6t:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52965)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/testdata/logic_test/geospatial_bbox, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52965#-MF0kPxH3KVxJmZ5SZ5A:-MF0kPxH3KVxJmZ5SZ5B:bpylc0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b559ae75b7e476dac8357eb105609ccb985210/pkg/sql/logictest/testdata/logic_test/geospatial_bbox#L152)):*
> ```
> NULL
> POINT (-1 -1)
> LINESTRING (-1 -2, 4 6)
> ```

I tried this in Postgres after writing my other comment and got
```
POINT(-1 -1)
 POLYGON((-1 -2,-1 6,4 6,4 -2,-1 -2))
```
___
*[pkg/sql/sem/tree/casts.go, line 817 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52965#-MF0jjAC6wCCE0dFntv8:-MF0jjAC6wCCE0dFntv9:b1xnhkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b559ae75b7e476dac8357eb105609ccb985210/pkg/sql/sem/tree/casts.go#L817)):*
> ```Go
> 			} else {
> 				g, err = geo.NewGeometryFromGeomT(
> 					geom.NewLineStringFlat(geom.XY, []float64{d.LoX, d.LoY, d.HiX, d.HiY}),
> ```

surprising that Box2D turns into a LineString and not a Polygon.

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/geospatial_bbox, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52965#-MF0kPxH3KVxJmZ5SZ5A:-MF0vekV8WrMCSoVleMy:b-bki0cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b559ae75b7e476dac8357eb105609ccb985210/pkg/sql/logictest/testdata/logic_test/geospatial_bbox#L152)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I tried this in Postgres after writing my other comment and got
```
POINT(-1 -1)
 POLYGON((-1 -2,-1 6,4 6,4 -2,-1 -2))
```
</blockquote></details>

My mistake, every time I tried I go LineStrings but looks like it was because I did vertical / horizontal lines. good catch

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52965#-:-MF19KhI5ZBYcfuZdF70:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/bbox.go, line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52965#-MF18C8P-s2pckvc9DrY:-MF18C8P-s2pckvc9DrZ:b-p0c4ci) ([raw file](https://github.com/cockroachdb/cockroach/blob/51b89db8d0b2cee6b498c022929241ef06eb2757/pkg/geo/bbox.go#L204)):*
> ```Go
> 			b.HiX, b.HiY,
> 			b.HiX, b.LoY,
> 			b.LoX, b.LoY,
> ```

should we orient this CCW to start with, since we'll need to change the orientation later in code.

**Comment by otan** [comment]
___
*[pkg/geo/bbox.go, line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52965#-MF18C8P-s2pckvc9DrY:-MF19aSy7rtVbk07t9UH:b-hy0atu) ([raw file](https://github.com/cockroachdb/cockroach/blob/51b89db8d0b2cee6b498c022929241ef06eb2757/pkg/geo/bbox.go#L204)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should we orient this CCW to start with, since we'll need to change the orientation later in code.
</blockquote></details>

this is how PostGIS explicitly specified they'd do it :(

**Comment by otan** [comment]
bors r=rytaft,sumeerbhola

**Pull request merged**
