### PR TITLE
opt, sqlsmith: fix incorrect output with NULLS LAST in window and aggregate functions

### LINKED ISSUE #91295: sql: disallow ORDER BY NULLS LAST in window functions and aggregate functions
We added support for `ORDER BY ... NULLS LAST` in v22.1, but it seems this is not working for `ORDER BY` in window functions. For example:

```sql
create table if not exists window_test
(
    id int null
);

insert into window_test
values
(1),
(2),
(null),
(3);

select *
from window_test;

select 
    id,
    row_number() over (order by id nulls last) as row_num_using_nulls_last,
    row_number() over (order by coalesce(id, 999)) as row_num_using_coalesce 
from window_test
order by id nulls last;
```

Gives these results on v22.2.0-alpha.3-1791-g52d7d6515f:

```
   id  | row_num_using_nulls_last | row_num_using_coalesce
-------+--------------------------+-------------------------
     1 |                        2 |                      1
     2 |                        3 |                      2
     3 |                        4 |                      3
  NULL |                        1 |                      4
(4 rows)


Time: 2ms total (execution 2ms / network 0ms)
```

On PostgreSQL 14.5 the result is:

```
 id | row_num_using_nulls_last | row_num_using_coalesce
----+--------------------------+------------------------
  1 |                        1 |                      1
  2 |                        2 |                      2
  3 |                        3 |                      3
    |                        4 |                      4
(4 rows)
```

Jira issue: CRDB-21192

### PR DESCRIPTION
**Pull request by rytaft**
**opt: fix incorrect output with `NULLS LAST` in window and aggregate functions**

Prior to this commit, window and aggregate functions dropped any `NULLS LAST`
modifier on their order by clauses. This commit updates the optbuilder to
add an implicit `col IS NULL` ordering column for each column `col` that uses
`NULLS LAST`.

Fixes https://github.com/cockroachdb/cockroach/issues/91295

Release note (bug fix): Fixed a bug in which the non-default nulls ordering,
`NULLS LAST`, was ignored in window and aggregate functions. This bug could cause
incorrect query results when `NULLS LAST` was used, and was introduced in 22.1.0.
This is now fixed.

**sqlsmith: added support for randomly using `NULLS FIRST` or `NULLS LAST`**

Prior to this commit, SQLSmith did not produce queries that used the
non-default nulls ordering. This commit adds support for sometimes using
`NULLS FIRST` or `NULLS LAST` with ordering clauses.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
LGTM

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-:-NJ60J4n-3SS7Q2-Kjtz:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Review by rytaft — COMMENTED** [review]
I updated the code to actually fix the bug, since returning an error won't work due to the `null_ordered_last` session setting. I think it's still backportable. PTAL. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-:-NJ6vm0h0PLsSQ_UXRLJ:b2xvq0t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

**Review by michae2 — APPROVED** [review]
Thanks for fixing it! I had some questions, but in general it :lgtm:

> Reviewed 1 of 4 files at r1, 8 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-:-NJ7Qf2n10TOwY08Cnem:b-szw0la)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/optbuilder/groupby.go` line 728 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-NJ7PKGA1IwUBJycvhgv:-NJ7PKGA1IwUBJycvhgw:brvr6tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab24d8059ff249ed5b920568d41f8bce31db709/pkg/sql/opt/optbuilder/groupby.go#L728)):*
> ```Go
> 			nullsDefaultOrder := b.hasDefaultNullsOrder(o)
> 			if !nullsDefaultOrder {
> 				expr := tree.NewTypedIsNullExpr(o.Expr.(tree.TypedExpr))
> ```

Do we need to do something special here to handle the case where `expr` is a tuple, like we did in window functions?
___
*[`pkg/sql/opt/optbuilder/orderby.go` line 287 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-NJ7JpAFAyLffLDzUa_G:-NJ7JpAFAyLffLDzUa_H:bz3s2rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab24d8059ff249ed5b920568d41f8bce31db709/pkg/sql/opt/optbuilder/orderby.go#L287)):*
> ```Go
> 			((order.NullsOrder == tree.NullsFirst && order.Direction == tree.Descending) ||
> 				(order.NullsOrder == tree.NullsLast && order.Direction != tree.Descending))) {
> 		telemetry.Inc(sqltelemetry.OrderByNullsNonStandardCounter)
> ```

Side note, I know this was already here but it seems a little odd that there's nothing to compare it to (i.e. I would expect an equivalent counter for when the default nulls order is used).
___
*[`pkg/sql/opt/optbuilder/window.go` line 434 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-NJ7Mwut98OlSMpwmi76:-NJ7Mwut98OlSMpwmi77:b-fgkwir) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab24d8059ff249ed5b920568d41f8bce31db709/pkg/sql/opt/optbuilder/window.go#L434)):*
> ```Go
> 					// in other expressions.
> 					colName := scopeColName("").WithMetadataName(
> 						fmt.Sprintf("%s_%d_nulls_ordering_%d", funcName, windowIndex+1, j+1),
> ```

Should this also use the index of `e` within `cols` in case this is a tuple with multiple columns that cannot be referenced?

**Review by rytaft — COMMENTED** [review]
TFTR! I went down a very deep rabbit hole trying to understand Postgres' behavior with NULLS FIRST/LAST and tuples, and I realized that our current approach of adding an extra ordering column in the optimizer unfortunately just doesn't work very well with tuples (i.e., we'll never be able to completely match Postgres' behavior with the current approach). I opened #93558 to track that issue, but it seems difficult to fix and much lower priority than #91295 (which this PR fixes).

So even if our behavior is somewhat wrong for tuples, at least we are now internally consistent. And this PR should fix the non-tuple cases completely.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-:-NJCu74g3u0JQJwgqjDX:b-hdnphx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/opt/optbuilder/groupby.go` line 728 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-NJ7PKGA1IwUBJycvhgv:-NJCY1197ScwT0qU7SVJ:b-geexvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab24d8059ff249ed5b920568d41f8bce31db709/pkg/sql/opt/optbuilder/groupby.go#L728)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Do we need to do something special here to handle the case where `expr` is a tuple, like we did in window functions?
</blockquote></details>

Great catch! This was actually a pre-existing bug that caused expressions like `array_agg((k, v) ORDER BY (k+1, v||'foo'))` to fail. Added a test for this too.
___
*[`pkg/sql/opt/optbuilder/orderby.go` line 287 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-NJ7JpAFAyLffLDzUa_G:-NJCZ77u3cNe89G-nDdE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab24d8059ff249ed5b920568d41f8bce31db709/pkg/sql/opt/optbuilder/orderby.go#L287)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Side note, I know this was already here but it seems a little odd that there's nothing to compare it to (i.e. I would expect an equivalent counter for when the default nulls order is used).
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/window.go` line 434 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-NJ7Mwut98OlSMpwmi76:-NJCYaYsB7F-LeEE9mC8:bw7zw8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab24d8059ff249ed5b920568d41f8bce31db709/pkg/sql/opt/optbuilder/window.go#L434)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should this also use the index of `e` within `cols` in case this is a tuple with multiple columns that cannot be referenced?
</blockquote></details>

Done. (I don't think it matters that the metadata name is unique, but fixed just in case...)

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

That slack thread definitely taught me a thing or two! :laughing:

> Reviewed 5 of 7 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-:-NJCyYMi6AjGgeYSR46c:b63cvoy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/optbuilder/groupby.go` line 728 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-NJ7PKGA1IwUBJycvhgv:-NJCzkvZCni0aLZuc97S:b-ras9f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab24d8059ff249ed5b920568d41f8bce31db709/pkg/sql/opt/optbuilder/groupby.go#L728)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Great catch! This was actually a pre-existing bug that caused expressions like `array_agg((k, v) ORDER BY (k+1, v||'foo'))` to fail. Added a test for this too.
</blockquote></details>

Wow! I was not expecting that, haha. SQL is ridiculous sometimes.
___
*[`pkg/sql/opt/optbuilder/orderby.go` line 287 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-NJ7JpAFAyLffLDzUa_G:-NJD1j4t0EMFzsu4287T:b-9755fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab24d8059ff249ed5b920568d41f8bce31db709/pkg/sql/opt/optbuilder/orderby.go#L287)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you!

**Review by rytaft — COMMENTED** [review]
Me too!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93426#-:-NJDBbUSC87ucmsq4aOR:bq54gqj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Pull request merged**
