### PR TITLE
kv: introduce transaction isolation level enumeration

### PR DESCRIPTION
**Pull request by nvb**
This commit introduces a new `isolation.Level` protobuf enumeration. The enum is given three values:
```go
// Serializable provides the strictest transaction isolation. The isolation
// level emulates serial transaction execution for all committed transactions;
// as if transactions had been executed one after another, serially, rather
// than concurrently.
//
// Serializable isolation is commonly implemented using two-phase locking
// [2PL]. However, CockroachDB does not use two-phase locking. Instead, its
// implementation of Serializable isolation uses an optimistic concurrency
// control algorithm that is related to Serializable Snapshot Isolation [SSI]
// and is probably most accurately described as a variant of Write-Snapshot
// Isolation [WSI]. These two algorithms live in a family of concurrency
// control schemes that extend the multi-versioning present in Snapshot
// Isolation with additional runtime conflict detection to provide
// Serializable Isolation.
//
// [2PL]: https://en.wikipedia.org/wiki/Two-phase_locking
// [SSI]: https://dl.acm.org/doi/10.1145/1620585.1620587
// [WSI]: https://dl.acm.org/doi/10.1145/2168836.2168853
Serializable = 0;

// Snapshot provides moderately strict transaction isolation. A transaction
// using the isolation level sees only data committed before the transaction
// began; it never sees either uncommitted data or changes committed during
// transaction execution by concurrent transactions. A transaction using this
// isolation level is also prevented from writing to data that has changed
// since the transaction began ("first committer wins"), preventing lost
// updates.
//
// Snapshot isolation is commonly built upon Multi-Version Concurrency Control
// (MVCC), which allows to isolation level to provide efficient concurrent
// access to reads and writes in different transactions that operate on the
// same data.
Snapshot = 1;

// ReadCommitted provides relatively weak transaction isolation. Each
// statement in a transaction using this isolation level sees only data
// committed before that statement began. However, two successive statements
// can see different data.
//
// For more about ReadCommitted, see the Read Committed RFC:
//  cockroachdb/cockroach/docs/RFCS/20230122_read_committed_isolation.md
ReadCommitted = 2;
```

The commit also defines two properties on the isolation levels: **Write Skew Tolerance** and **Read Snapshot Scope**. See the comment in `levels.proto` for an explanation.

Part of #100129

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99873#-:-NRiN9yFBAkXd0wTLnik:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/isolation/levels.proto` line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99873#-NRiMFxeA6OPtXHLplgN:-NRiMFxeA6OPtXHLplgO:b1lsmma) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa8866ada4f9390b8fee8bbb6df8a70864027f8/pkg/kv/kvserver/concurrency/isolation/levels.proto#L184)):*
> ```protobuf
>   // For more about ReadCommitted, see the Read Committed RFC:
>   //  cockroachdb/cockroach/docs/RFCS/20230122_read_committed_isolation.md
>   ReadCommitted = 2;
> ```

Suppose we eventually implement something akin to EPQ rechecks. How do you envision that fitting into this configuration? Would that be a separate isolation level? Or just another setting to be used with read committed isolation?

**Review by arulajmani — APPROVED** [review]
:rocket: :rocket: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99873#-:-NRidoXd0w5fmJvBj46Y:b-iot6t7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99873#-:-NRigK8n1XYaX1aiF3On:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/kv/kvserver/concurrency/isolation/levels.proto` line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99873#-NRiMFxeA6OPtXHLplgN:-NRifPyMD9zPtx2HtHaI:bh130oy) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa8866ada4f9390b8fee8bbb6df8a70864027f8/pkg/kv/kvserver/concurrency/isolation/levels.proto#L184)):*
That's a good question. Doing so will require invasive changes to both SQL and KV. You're well aware of the SQL-level changes. The KV-level changes will look something like (from draft RFC):

> This necessitates a change in the KV API's handling of write-write version conflicts between transaction isolation levels. This difference is summarized below:
> 
> | Operation type   | SI Read Version   | SI WW Version Conflict     | RC Read Version   | RC WW Version Conflict     |
> | ---------------- | ----------------- | -------------------------- | ----------------- | -------------------------- |
> | Non-locking Read | [txn.ReadTimestamp](https://github.com/cockroachdb/cockroach/blob/8e24570fa366ed038c6ae65f50db5d8e22826db0/pkg/storage/pebble_mvcc_scanner.go#L791) | N/A                        | txn.ReadTimestamp | N/A                        |
> | Locking Read     | [txn.ReadTimestamp](https://github.com/cockroachdb/cockroach/blob/8e24570fa366ed038c6ae65f50db5d8e22826db0/pkg/storage/pebble_mvcc_scanner.go#L791) | [WriteTooOldError](https://github.com/cockroachdb/cockroach/blob/8e24570fa366ed038c6ae65f50db5d8e22826db0/pkg/storage/pebble_mvcc_scanner.go#L832)           | latest version    | txn.WriteTimestamp.Forward |
> | Write-Only       | N/A               | [txn.WriteTimestamp.Forward](https://github.com/cockroachdb/cockroach/blob/8e24570fa366ed038c6ae65f50db5d8e22826db0/pkg/kv/kvserver/replica_evaluate.go#L371), then [WriteTooOldError](https://github.com/cockroachdb/cockroach/blob/8e24570fa366ed038c6ae65f50db5d8e22826db0/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L259) | N/A               | txn.WriteTimestamp.Forward | 
> | Read-Write       | [txn.ReadTimestamp](https://github.com/cockroachdb/cockroach/blob/8e24570fa366ed038c6ae65f50db5d8e22826db0/pkg/storage/mvcc.go#L2050) | [WriteTooOldError](https://github.com/cockroachdb/cockroach/blob/8e24570fa366ed038c6ae65f50db5d8e22826db0/pkg/kv/kvserver/replica_evaluate.go#L365)           | latest version    | txn.WriteTimestamp.Forward |
> 
> Users of the KV API must be aware of this change in write-write version conflict handling or they will risk lost updates. Specifically, a non-locking read of a key followed by a write to that key in the same transaction could ignore a committed version between the transaction's read and write timestamp.
>
> Users of the KV API must also be aware that this change in write-write version conflict handling can expose locking read and read-write operations to an inconsistent snapshot of the system.

Those are invasive-enough changes that I do think it would make sense to consider them to be part of a different isolation level. This is similar to how SQL Server has a pair of READ COMMITTED implementations, depending on the `READ_COMMITTED_SNAPSHOT` option. At that time, we may want to use SQL Server as inspiration and call the existing `ReadCommitted` variant (the one added here) `ReadCommittedSnapshot`.

**Comment by nvanbenschoten** [comment]
bors r=michae2,arulajmani

**Pull request merged**
