### PR TITLE
stats: use no-op DatumAlloc when decoding EncDatums

### LINKED ISSUE #136394: roachtest: bounded memory leak of garbage datums during table stats collection
roachtest.perturbation/metamorphic/elasticWorkload [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_PerturbationNightlyGceBazel/17962806?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_PerturbationNightlyGceBazel/17962806?buildTab=artifacts#/perturbation/metamorphic/elasticWorkload) on master @ [7d48198a57f014a8828194b90098699f70f0695a](https://github.com/cockroachdb/cockroach/commits/7d48198a57f014a8828194b90098699f70f0695a):

```
(assertions.go:363).Fail: 
	Error Trace:	pkg/cmd/roachtest/tests/perturbation/framework.go:645
	            				pkg/cmd/roachtest/test_runner.go:1314
	            				src/runtime/asm_amd64.s:1695
	Error:      	Should be true
	Test:       	perturbation/metamorphic/elasticWorkload
	Messages:   	FAILURE: write          : Increase 21.3444 > 20.0000 BASE: 5.275704ms SCORE: 112.606575ms
(require.go:1950).True: FailNow called
test artifacts and logs in: /artifacts/perturbation/metamorphic/elasticWorkload/run_1
```

Parameters:
 - <code>arch=amd64</code>
 - <code>cloud=gce</code>
 - <code>coverageBuild=false</code>
 - <code>cpu=32</code>
 - <code>encrypted=false</code>
 - <code>fs=ext4</code>
 - <code>localSSD=true</code>
 - <code>runtimeAssertionsBuild=false</code>
 - <code>ssd=2</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-17962806/perturbation-metamorphic-elasticworkload/1732867055934/1732869216989)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*perturbation/metamorphic/elasticWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45014

### PR DESCRIPTION
**Pull request by yuzefovich**
**tree: make nil DatumAlloc act as a no-op**

This commit makes so that `nil` `DatumAlloc` value makes the alloc struct a no-op, i.e. each datum type passed by value results in a separate allocation. This can be useful when the callers will keep only a subset of all allocated datums.

Release note: None

**stats: use no-op DatumAlloc when decoding EncDatums**

This commit fixes a bounded memory leak that could previously occur due to usage of the DatumAlloc when decoding EncDatums into `tree.Datum`s during table stats collection. We have two use cases for decoded `tree.Datum`s:
- we need it when adding _all_ rows into the sketch (we compute the datum's fingerprint ("hash") to use in the distinct count estimation). This usage is very brief and we don't need the decoded datum afterwards.
- we also need it when sampling _some_ rows when we decide to keep a particular row. In this case, the datum is needed throughout the whole stats collection job (or until it's replaced by another sample) for the histogram bucket computation.

The main observation is that the DatumAlloc allocates datums in batches of 16 objects, and even if at least one of the objects is kept by the sample, then all others from the same batch are as well. We only perform memory accounting for the ones we explicitly keep, yet others would be considered live by the Go runtime, resulting in a bounded memory leak. This behavior has been present since forever, but it became more problematic in 24.2 release with the introduction of dynamically computing the sample size. To go around this problematic behavior this commit uses `nil` DatumAlloc which makes it so that every decoded datum incurs a separate allocation. This will have a minor performance hit and increase in total number of allocations, but at least most of them should be short-lived. Alternatively, we could use an "operating" DatumAlloc during fingerprinting and a no-op during the sampling, but we'd need to explicitly nil out the decoded datum after fingerprinting which would result in decoding some datums twice.

Fixes: #136394.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Commits 1 and 3 are temporary and won't be merged (the first one is a test I used to confirm the theory about the bounded leak, and the third one is a sanity check that nil DatumAlloc used all the time works in the CI).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-:-ODJt8WR4hQtUJrX1rhQ:b4yvxig)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[`-- commits` line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-ODJt3jv9efAhdU4Th88:-ODJt3jv9efAhdU4Th89:bgt1uoi):*
Curious whether you think that this (or some other) approach is preferable.

**Review by mgartner — COMMENTED** [review]
Nice find!

> Reviewed 1 of 1 files at r2, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-:-ODSIg0j37jVXGcdmS7G:bdkgtm2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 52 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-ODSHYrM1KmZsA_rumzq:-ODSHYrM1KmZsA_rumzr:b-21eocf):*
Can't we mitigate (or completely eliminate) the extra allocations by using `(*DatumAlloc).AddTypeAllocSize`? E.g., we know ahead of time that a row has 3 int columns, so we can allocated exactly 3 DInts.
___
*[`-- commits` line 56 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-ODSI-1g84MTtvQ4pxOn:-ODSI-1g84MTtvQ4pxOo:bydcgld):*
Another alternative would be to allocate exactly the number and type of datums needed for a decoding a row as a "fingerprint scratch row", and reusing those datums for fingerprinting. Then, if the row is sampled we allocate new datums and copy the datums in the fingerprint scratch into those datums.

In practice this would require a DatumAlloc interface (might add overhead or other allocations) or new code paths for decoding into a different datum allocator (the fingerprint type). And it might also require adding a Copy method to the `tree.Datum` interface. So it may not be too easy.

**Comment by mgartner** [comment]
*[`-- commits` line 52 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-ODSHYrM1KmZsA_rumzq:-ODSIr8xEgsONwRTmqZT:b6kp6pw):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can't we mitigate (or completely eliminate) the extra allocations by using `(*DatumAlloc).AddTypeAllocSize`? E.g., we know ahead of time that a row has 3 int columns, so we can allocated exactly 3 DInts.
</blockquote></details>

Oh, nvm. I see that the batches of 16 allocated datums were shared across rows. So we'd still have more allocations even if we used `AddTypeAllocSize`. But it might help a bit...

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

Do we also need to change [this one](https://github.com/cockroachdb/cockroach/blob/85afe78272f7bc2a5ac733e8d139bfefdb4cfa95/pkg/sql/rowexec/sample_aggregator.go#L252) in sample_aggregator?

> Reviewed 1 of 1 files at r2, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-:-ODSdftG0GSTbYKo0QFK:b-bdfys9)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`-- commits` line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-ODJt3jv9efAhdU4Th88:-ODSaWNb5pDahdebQesu:basoxt7):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Curious whether you think that this (or some other) approach is preferable.
</blockquote></details>

This looks good to me.

**Review by yuzefovich — COMMENTED** [review]
> Do we also need to change [this one](https://github.com/cockroachdb/cockroach/blob/85afe78272f7bc2a5ac733e8d139bfefdb4cfa95/pkg/sql/rowexec/sample_aggregator.go#L252) in sample_aggregator?

I don't think that's needed. That DatumAlloc is used to allocate a single `DBytes` datum per sketch row, and that datum is only used ephemerally (to be unmarshalled and that's it), so we shouldn't be keeping references to any datums for long.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-:-ODh9H3z-Xbxhgm6pN3i:bt3yvmr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`-- commits` line 52 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-ODSHYrM1KmZsA_rumzq:-ODhA-cjE-oxAnlH9Cmf:b-dcx2f1):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Oh, nvm. I see that the batches of 16 allocated datums were shared across rows. So we'd still have more allocations even if we used `AddTypeAllocSize`. But it might help a bit...
</blockquote></details>

Yeah, the main problem is sharing datums across rows. My intuition tells me that this code path is not super important to micro-optimize, so I left a TODO with the idea to use `typeAllocSizes` in such a way so that all datums within a single row would be backed by a single allocation (modulo different column types).
___
*[`-- commits` line 56 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136780#-ODSI-1g84MTtvQ4pxOn:-ODhCnIfD2mJtFfQ_ILk:b-3epb0c):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Another alternative would be to allocate exactly the number and type of datums needed for a decoding a row as a "fingerprint scratch row", and reusing those datums for fingerprinting. Then, if the row is sampled we allocate new datums and copy the datums in the fingerprint scratch into those datums.

In practice this would require a DatumAlloc interface (might add overhead or other allocations) or new code paths for decoding into a different datum allocator (the fingerprint type). And it might also require adding a Copy method to the `tree.Datum` interface. So it may not be too easy.
</blockquote></details>

`tree.Datum` implementations are supposed to be immutable, so we'd be breaking that assumption if we reused the same datums for fingerprinting. Granted, in this case those datums are "swallowed" by the sampler processor and do not propagate any further, so probably this would be a safe approach, but I guess I'd like to see a profile from a customer-like cluster / workload where this inefficiency in allocations is the main bottleneck before going down this road.

**Comment by yuzefovich** [comment]
Actually, I think I'll add a simple randomized unit test for the no-op datum alloc behavior.

bors r-

**Pull request merged**
