### PR TITLE
log: pass runtime.Error through crash reports

### PR DESCRIPTION
**Pull request by dt**
panics thrown by the runtime itself are usually tagged with the RuntimeError method so they
implement the runtime.Error interface.

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16230#-:-KlTngzHnN_7fI0Nv6ad:bnfp4nl)*

**Comment by knz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16230#-:-KlTrgGbwTreJTiOOT2W:bnfp4nl)*

**Comment by dt** [comment]
this is a tiny change and gets us actionable info -- i'd like to propose it be cherry-picked. /cc @knz @petermattis ?

**Comment by petermattis** [comment]
This seems reasonable for 1.0.2.

**Pull request merged**
