### PR TITLE
allocatorimpl,asim: fix replace constraints check fn

### LINKED ISSUE #117886: kv: `replaceConstraintsCheck` considers necessary replacement to be invalid, can stall decommission
https://github.com/cockroachdb/cockroach/commit/f7db7e348f6c596da6e497b847ddf77f399c5182 added subtle logic to protect against replica replacement causing a range to go out of conformance. The core of this logic is in `replaceConstraintsCheck`.

That function appears to have a bug. Specifically, consider the following setup:
```
voters: {
  11 - us-west-2c
  14 - us-west-2a
  16 - us-west-2c
}

store: 15, us-west-2b
existingStore: 11 - us-west-2c

iter 1:
  constraints: {us-west-2b: 1}
  satisfiedByExistingStore = false
  satisfiedByCandidateStore = true
  necessary = true

iter 2:
  constraints: {us-west-2c: 1}
  satisfiedByExistingStore = true
  satisfiedByCandidateStore = false
  necessary is still true from prior iteration
  if necessary && satisfiedByExistingStore && !satisfiedByCandidateStore { return false /* valid */, true }
```

Notice that in this case, the function returns `valid=false`, even though the replacement is both `valid` and `necessary`.

A fix for this will look along the lines of:
```
for i, constraints := range analyzed.Constraints {
    matchingStores := analyzed.SatisfiedBy[i]
    satisfiedByExistingStore := containsStore(matchingStores, existingStore.StoreID)
    satisfiedByCandidateStore := constraint.CheckStoreConjunction(store, constraints.Constraints)
    if satisfiedByCandidateStore {
        valid = true
        // If the constraint is not already satisfied, it's necessary.
        // Additionally, if the constraint is only just satisfied by the existing
        // store being replaced, since that store is going away, the constraint is
        // also marked as necessary.
        if len(matchingStores) < int(constraints.NumReplicas) ||
            (len(matchingStores) == int(constraints.NumReplicas) &&
                satisfiedByExistingStore) {
            necessary = true
        }
    } else if satisfiedByExistingStore {
        // Check if existing store matches a constraint that isn't overly satisfied.
        // If so, then only replacing it with a satisfying store is valid to ensure
        // that the constraint stays fully satisfied.
        if len(matchingStores) <= int(constraints.NumReplicas) {
            return false, false
        }
    }
}
```

Along with some much needed unit testing of this function and ideally also other `constraintsCheckFn` implementations.

Jira issue: CRDB-35403

### PR DESCRIPTION
**Pull request by kvoli**
Previously, it was possible for replica replacement to not return a
valid target when some constraint was initially undersatisfied in
addition to the replica being replaced satisfying a separate constraint.

When this occurred, it could stall decommissioning a node, as replicas
become stuck with the allocator returning no valid replacement target.

Update the `replaceConstraintsCheck` function to correctly consider
whether the replacement store satisfies the constraint when computing if
the replacement is necessary.

Fixes: https://github.com/cockroachdb/cockroach/issues/117886
Part of: https://github.com/cockroachdb/cockroach/issues/117891
Release note (bug fix): Decommissioning replicas which are part of a
mis-replicated range will no longer get stuck on a rebalance operation
that was falsely determined to be unsafe. This bug was introduced in
23.1.0.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: once https://github.com/cockroachdb/cockroach/pull/117941 merges and this is rebased on it.

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117900#-:-NonOVeWEI3HHupfQ3Jv:b-qnkstf)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117900#-NonNXcG0MZFQXAAL_IK):*
Can we change this release note to talk more about the user-visible behavior instead of the implementation? For instance, instead of saying "replacement targets returned", we can talk about the decommissioning not getting stuck on a rebalance operation that was falsely determined to be unsafe.

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117900#-:-NosG57GB_aH0RBl0W9y:b-80sls6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117900#-NonNXcG0MZFQXAAL_IK):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we change this release note to talk more about the user-visible behavior instead of the implementation? For instance, instead of saying "replacement targets returned", we can talk about the decommissioning not getting stuck on a rebalance operation that was falsely determined to be unsafe.
</blockquote></details>

Fair point, I've updated to be closer to this language.

**Comment by kvoli** [comment]
`TestStoreRangeMergeWithData` timed out, unrelated to this PR.

TYFTR

bors r=nvanbenschoten.

**Comment by kvoli** [comment]
Updated the unit test to only replace existing stores.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117900#-:-Nox3lDa8DBttDsVoMZj:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by kvoli** [comment]
TYFTR

bors r=nvanbenschoten

**Comment by kvoli** [comment]
[Canceled with comment: Agent removed
](https://teamcity.cockroachdb.com/viewLog.html?buildId=13691306&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_Builds_BuildMacOSArm64)

Retrying

bors r=nvanbenschoten

**Comment by kvoli** [comment]
bors r=nvanbenschoten

**Pull request merged**
