### PR TITLE
opt: Enable additional logic tests for opt configs

### PR DESCRIPTION
**Pull request by andy-kimball**
Enable more logic tests (join -> ordinality).
Fix various bugs and issues that were failing tests.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm: 

Can we merge the `order_by_index` tests into `order_by` (perhaps with a `subtest` directive)? It's strange for such a small feature to get its own file (and every file has some setup cost). I'd do the same to txn_retry and txn if you work on those.

---

Review status: 0 of 49 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/optbuilder/scope.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26116#-LDRI8U83nOSfXibdE8h:-LDRI8U94eH2yY5zFD2t:b7pm2da) ([raw file](https://github.com/cockroachdb/cockroach/blob/5501dc61b3799adaad8093951e7f1e119d51940b/pkg/sql/opt/optbuilder/scope.go#L225)):*
> ```Go
> 
> // setTableAlias qualifies the names of all columns in this scope with the
> // given alias name, as if they were part of a table with that name.
> ```

[nit] maybe mention that you can pass the empty string to remove any qualification.

---

*[pkg/sql/opt/optbuilder/testdata/join, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26116#-LDRI-JR0M5RpF43VzyF:-LDRI-JS54L2gRZLunkv:b-mugp3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5501dc61b3799adaad8093951e7f1e119d51940b/pkg/sql/opt/optbuilder/testdata/join#L146)):*
> ```
> # Check that ORDER BY chokes on ambiguity if no table less columns
> # were introduced by USING. (#12239)
> # TODO(rytaft): This is a bug. This query is invalid.
> ```

remove this TODO

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26116#-:-LDRL49s4zupZW3Z36go:b-461ktq)*

**Comment by andy-kimball** [comment]
OK, I merged them.

---

Review status: 0 of 49 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/optbuilder/scope.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26116#-LDRI8U83nOSfXibdE8h:-LDVYVGb1KyMugOUQd4t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5501dc61b3799adaad8093951e7f1e119d51940b/pkg/sql/opt/optbuilder/scope.go#L225)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe mention that you can pass the empty string to remove any qualification.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26116#-:-LDVY7AO28K2UKEvWi8V:b-aggp92)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26116)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26116#-:-LDWS8Yo8QTG6bCbFmqy:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/optbuilder/testdata/scalar, line 738 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/26116#-LDbSL9M2BYLVrmp_0Ih:-LDbSL9N9MtP1Le-nmL9:b-wf3rx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ff2e77b896ed9baa56fe1fb1c974e238d74e320/pkg/sql/opt/optbuilder/testdata/scalar#L738)):*
> ```
> ARRAY['"foo"'::json]
> ----
> error: arrays of jsonb not allowed
> ```

should this be "arrays of json"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26116#-:-LDbWKtuC6b80CT37PZL:bnfp4nl)*

**Comment by andy-kimball** [comment]
*[pkg/sql/opt/optbuilder/testdata/scalar, line 738 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/26116#-LDbSL9M2BYLVrmp_0Ih:-LDck0fq3TaGK_zcXyri:b-3usjsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ff2e77b896ed9baa56fe1fb1c974e238d74e320/pkg/sql/opt/optbuilder/testdata/scalar#L738)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should this be "arrays of json"?
</blockquote></details>

Cockroach treats `json` as an alias for `jsonb`. For example, `SELECT pg_typeof('"foo"'::json);` returns `jsonb`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26116)*

**Pull request merged**
