### PR TITLE
release-23.1: kvcoord: Fix metrics tracking in mux rangefeed

### LINKED ISSUE #106152: kvcoord/(mux)rangefeed: when changefeed job is cancelled distsender.rangefeed.total_ranges doesn't go down
DistSender maintains a gauge metric showing number of active rangefeeds on the client side. This metric is increased when each feed covering single range is created and decreased when it is cancelled or restarted.

This behaviour seem broken as the gauge doesn't go down if rangefeed is stopped by client by cancelling context. That kind of cancellation happens when changefeed jobs are paused or cancelled.

Note that there may be other effects of rangefeed not being released correctly as this is just manifestation of rangefeed lifecycle management being broken.

**Environment:**
 - CockroachDB version 23.1.4 and likely earlier ones

Jira issue: CRDB-29429

Epic CRDB-26372

### LINKED ISSUE #106252: kvcoord/(mux)rangefeed: when changefeed job is cancelled distsender.rangefeed.catchup_ranges doesn't go down
If changefeed jobs are cancelled or paused while catch up scan is running, metric for those ranges won't be decreased.

Problem is similar to #106152

**Environment:**
 - CockroachDB version 23.1.4 and likely earlier ones

Jira issue: CRDB-29462

Epic CRDB-26372

### PR DESCRIPTION
**Pull request by miretskiy**
Backport 1/1 commits from #107384.

/cc @cockroachdb/release

---

Fix an observability bug in mux rangefeed which would incorrectly count various rangefeed related metrics (total ranges, catchup ranges, etc).

Fixes #106152
Fixes #106252

Release note: None
Release justification: fix observability/metrics accounting in mux rangefeed (disabled by default)

### CODE REVIEW

**Comment by miretskiy** [comment]
@erikgrinaker some conflicts occurred; but overall mostly clean backport.

**Comment by erikgrinaker** [comment]
I have a cluster running `master` which doesn't appear to be populating `distsender.rangefeed.catchup_ranges`. Going to confirm before approving this.

**Comment by miretskiy** [comment]
> I have a cluster running `master` which doesn't appear to be populating `distsender.rangefeed.catchup_ranges`. Going to confirm before approving this.

I fixed an issue by adding metric struct tag to the new struct. Found it because chart.catalig test failed. I'm surprised it is still not fixed.

**Comment by erikgrinaker** [comment]
Yeah, that fix isn't merged yet. Can confirm that metrics are broken on master, so let's hold off on this.

**Comment by miretskiy** [comment]
> Yeah, that fix isn't merged yet. Can confirm that metrics are broken on master, so let's hold off on this.

Can you pick my other metrics or to see if that's what was needed?

**Comment by erikgrinaker** [comment]
Works with #108062.

**Comment by miretskiy** [comment]
@erikgrinaker okay to merge this one then?

**Comment by miretskiy** [comment]
It's here already.  That's how I discovered this issue (because of catalog_chart tests -- and those tests were removed on the master.  note to self: we really need to have a linter or some such to protect against that)

**Review by erikgrinaker — APPROVED** [review]
Ah, missed that.

**Pull request merged**
