### PR TITLE
cli: show the current database name in the sql prompt.

### PR DESCRIPTION
**Pull request by pmamatsis**
Hi @knz i have redone everything for the issue "Show current database in sql prompt." and created a pull request. Really thanks for the vote of confidence! :+1:

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12747)

### CODE REVIEW

**Comment by knz** [comment]
You forgot to address my previous comments:

- run `make acceptance`. Use the output of the failing test as input to fix the tests in `pkg/cli/interactive_tests` that need to be modified due to your patch. See https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=110221#_focus=395

- run `make check`. Then perform the changes required by `make check`, if any. See https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=110222#_focus=337

**Comment by knz** [comment]
Starting to look good.

Although please add a *new* test in pkg/cli/interactive_tests to test the new feature explicitly.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/cli/sql.go, line 407 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747#-K_sCD3Qy3GsaOyx6Jx0:-K_sCD3Qy3GsaOyx6Jx1:bedmd24) ([raw file](https://github.com/cockroachdb/cockroach/blob/d138f82050b7755f678402170298a508c1180c3c/pkg/cli/sql.go#L407)):*
> ```Go
> //This function is performing the 'refresh' action to update the cli prompt with the current
> //database in the user's context.
> func (c *cliState) refreshDatabaseName(promptSuffix string, nextState cliStateEnum) cliStateEnum {
> ```

Rename `promptSuffix` to `txnStatus` throughout.

---

*[pkg/cli/sql.go, line 427 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747#-K_sCWvxdEZK33mZIYol:-K_sCWvxdEZK33mZIYom:bynj4d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d138f82050b7755f678402170298a508c1180c3c/pkg/cli/sql.go#L427)):*
> ```Go
> 		fmt.Fprintf(osStderr, "error retrieving the database name: %v", err)
> 		return c.refreshPrompts(promptSuffix, nextState)
> 	} else {
> ```

See what `make check` has to say about this.

---

*[pkg/cli/sql.go, line 429 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747#-K_sC8totsVzbn1yDPa6:-K_sC8tpOe-SPhAUZMl6:b-kokmdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d138f82050b7755f678402170298a508c1180c3c/pkg/cli/sql.go#L429)):*
> ```Go
> 	} else {
> 		dbName := formatVal(dbVals[0].(string), false /* showPrintableUnicode */, false /* shownewLinesAndTabs */)
> 		return c.refreshPrompts(promptSuffix+":/"+dbName, nextState)
> ```

Sorry I just noticed (thanks to thet `test_txn_prompt.tcl` acceptance test!) that this places the database name after the transaction status, which feels wrong.
I'd suggest inverting the two: `"/" + dbname + txnStatus` instead. This way probably you don't even need to change the existing test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747#-:-K_sCZHCM9ZkhtDW-oGN:b6tnq6o)*

**Comment by pmamatsis** [comment]
Hi @knz,
   my apologies for the late reply. I will do as needed and i will perform the necessary testing. Please give me some time to try and understand the whole "testing" thing with the tcl.

Best regards,
Panos.

**Comment by pmamatsis** [comment]
Hi @knz I am trying to perform the `make test` but i am getting the below error:

```
Makefile:247: .bootstrap: No such file or directory
go install ./vendor/github.com/robfig/glock
can't load package: package ./vendor/github.com/robfig/glock: open /home/panos/GoSrc/src/github.com/cockroach/vendor/github.com/robfig/glock: no such file or directory
Makefile:238: recipe for target '../../../../bin/glock' failed
make: *** [../../../../bin/glock] Error 1
```

Do i need to install something else ? Do i need to `go get` the `github.com/robfig/glock` module manually?

Best regards,
Panos.

**Comment by knz** [comment]
I have never seen this error before. Try to `go get` glock and see if that helps.

@dt what do you make of it?

**Comment by pmamatsis** [comment]
Hi @knz and @dt,
   i am really sorry but it's just occurred to me that i haven't actually checked myself the `Makefile` file... :-)
My `$GOPATH` is in $HOME/GoSrc and the directory i have cloned my github PR is in `$HOME/GoSrc/src/github.com/cockroach`. I just needed to "re-adjust" the various (two areas actually) paths into the `Makefile` file itself! After doing  i have given the `make test` and it it started downloading into the ./vendor directory various packages and then i got various things that i need to change!!! :-)

I will do as needed!cAnother question i wanted to ask is...for the `make acceptance`

Best regards and thank you both for your time,
Panos.

**Comment by dt** [comment]
@pmamatsis @knz that error suggests that `glock` was missing *from vendor*... can you check `ls ./vendor/github.com/robfig/glock`? maybe try `git submodule update vendor` ?

**Comment by pmamatsis** [comment]
Hi @knz and @dt ,
   I have already finished with this but my question is about `docker`. Why is docker needed in `make acceptance` process ? Of course i will install it tonight and conclude with the final part but i am just asking the "why". :-)

Best regards and thank you for your help,
Panos.

**Comment by knz** [comment]
Hi Panos, 

1. first note that you do not need docker to "fix" the failing acceptance test - for CLI interactive tests specifically, you can run them outside of `make acceptance`. If you do not wish (or do not have time to) install Docker, I have a solution for you, see below.

2. to answer your "why" question we use Docker to ensure that `make acceptance` runs in an environment with all the necessary tools installed. Our acceptance tests will check compatibility with Java, Ruby, PHP, Finagle and many other things that you may not have installed on your system, or perhaps with different versions. It would be very unfair / cumbersome for us to ask you to install everything exactly in the way `make acceptance` requires. So we use Docker to avoid this difficulty.

So to come back to the failing tests. 

- first you should learn how to use the TeamCity test results. If you look at the PR check results you can see that the TeamCity CI build has failed. So you can click the "Details" link at the right to go to the TeamCity test results. 
  - Now in the main test result page you get an overview of the failing tests. As you can see, the two main things failing for now are the `check` tests and the `acceptance` tests. 
  - To see the details of what has failed, use the small downwards triangle next to the name of the failing test then "Show in build log". See [this screenshot](https://cloud.githubusercontent.com/assets/642886/21805574/24bbaabc-d735-11e6-9a8b-d4ccbc145977.png) for an example.
- If you do that for the `check` test you will see the following error: `cli/sql.go:427:9: if block ends with a return statement, so drop this else and outdent its block` -- this is what I explained earlier about if/else. You just have to do what the test result says. Then you can run `make check` locally to verify you did it right.
- if you go to the build log for the acceptance test you will see that the failing test is `test_txn_prompt.tcl`. This is because this test checks the syntax structure of the SQL shell prompt and your patch is changing that. So you need to modify the test to recognize your new syntax.

When you modify a `tcl` CLI test, you can either run `make acceptance TESTS=TestDockerCLI` to check them, but there is a simpler method: you can invoke `expect` directly like this:

      make build    # ensure that the ./cockroach binary exists and is up to date
      expect -d -f pkg/cli/interactive_tests/test_txn_prompt.tcl ./cockroach

Once `expect` runs without error you know you have fixed the test. Then you can upload the result and let TeamCity run `make acceptance` for you. Then yo do not need Docker.

**Comment by knz** [comment]
By the way I say "The PR Checks" this is what is given in the github interface at the bottom of the PR page, here:

schermafdruk_2017-01-10_13-10-48

**Comment by pmamatsis** [comment]
Hi @knz,
   first let me thank you so much for you detailed reply! Thinking about it i will be doing it the "official" way and install `Docker` to my laptop. I like the whole idea of making the acceptance checking in an isolated environment! :-)

About the TeamCity CI yes you are correct! I could see some red icons but since i wasn't get use into using it i couldn't figure out on how to understand of what's going on! As far as the .tcl testing files i must really spend some time reading and understanding these but i will definitely planning to do!

Best regards and really appreciate all the help provided,
Panos.

**Comment by pmamatsis** [comment]
Hi @knz,
   i have managed to finish quickly all the changes required by the `make check` but i am afraid that the `make acceptance` will be my Waterloo !!! I haven't quite managed to pull the official acceptance docker image(s) required because as my laptop start to fetch the parts of the test-prostgress image it suddenly stops. Since i have this pull request too much time on me and i don't want to waste any more time on this (of course after successful merge i will re-try to fix this issue in order to continue working with this project) i have tried using the second option but i believe that i am failing to all the tests !!! :-(

Do i need to rewrite the tests ? Of course i know i am missing a lot of things here because i don't know the tcl language at all!

A small sample of the output is the following:

```
expect: does "" (spawn_id exp6) match glob pattern ":/# "? no
PS1='\h:''/# '

expect: does "PS1='\h:''/# '\r\n" (spawn_id exp6) match glob pattern ":/# "? no
panos@ubuntupc:~/GoSrc/src/github.com/cockroachdb/cockroach$ PS1=
expect: does "PS1='\h:''/# '\r\npanos@ubuntupc:~/GoSrc/src/github.com/cockroachdb/cockroach$ PS1=" (spawn_id exp6) match glob pattern ":/# "? no
'\h:
expect: does "PS1='\h:''/# '\r\npanos@ubuntupc:~/GoSrc/src/github.com/cockroachdb/cockroach$ PS1='\h:" (spawn_id exp6) match glob pattern ":/# "? no
''/#
expect: does "PS1='\h:''/# '\r\npanos@ubuntupc:~/GoSrc/src/github.com/cockroachdb/cockroach$ PS1='\h:''/#" (spawn_id exp6) match glob pattern ":/# "? no
 '

expect: does "PS1='\h:''/# '\r\npanos@ubuntupc:~/GoSrc/src/github.com/cockroachdb/cockroach$ PS1='\h:''/# '\r\n" (spawn_id exp6) match glob pattern ":/# "? no
```

Best regards,
Panos.

**Comment by knz** [comment]
Try setting the environment variable SHELL to /bin/bash

like `export SHELL=/bin/bash`

then try again.

**Comment by pmamatsis** [comment]
Hi @knz and thank you so much for your quick reply,
   i have tested with `echo $SHELL` and it prompted back `/bin/bash` but nevertheless i have done the set again and then tried again. Unfortunately the output from `expect` is the same. I haven't touched any .tcl files in any way because i thought that the `default` tests will cover this case.

My next plan is to push push it to my repo and then try a pull request and see what the TeamCity CI is going to tell me... How do you thing?

Best regards,
Panos.

**Comment by pmamatsis** [comment]
Hi @knz,
   because i don't see any other way around it...I MUST learn how to read and understand the tcl scripts quickly! :)

I am looking into the file named `./pkg/cli/interactive_tests/test_txn_prompt.tcl` and especially into the place where we are checking for an not existing column name as following:

```
# Test that prompt becomes "ERROR>"
send "select a;\r"
eexpect "pq: column name \"a\""
eexpect "ERROR>"
send "rollback;\r"
```

I am connecting to a cockroach node and open manually a sql command prompt and i am issuing the `select a;` sql statement by hand but the output is not quite the same as expected from the tcl script...the output is as following:

```
root@:26257:/> select a;
pq: column name "a" not found
root@:26257:/>  
```
and also the prompt does not return to `"ERROR>"`.

My question is...am i understand correctly or am i making stupid assumptions? I am asking this only because if i am beginning to understand correctly maybe i am try and re-adjust this tcl script. :)

Best regards,
Panos.

**Comment by knz** [comment]
Huh I think the test is telling you that your code is wrong :)

Basically it looks like your way to modify the prompt has "forgotten" the transaction status, which was indicated there before.

**Comment by pmamatsis** [comment]
Hi @knz,
   thank you so much for your quick response! I will have a look at the "original" sql prompt from my backup copy and revert back the soonest!

Best regards,
Panos.

**Comment by pmamatsis** [comment]
Good morning @knz,
   my apologies for the late response. I have also rebuild and executed the original sources of the cockroachdb and i could see any indication of the transaction status on the command prompt. Is it possible to explain a bit more? I believed that i would see any kind of difference on the sql command prompt but it's the same...Most probably i haven't quite understood how the `expect` program really works...

Best regards and thank you in advance,
Panos.

**Comment by pmamatsis** [comment]
Hi @knz,
   please disregard my last message. Is everything all right now? Is there anything to be done for this issue? May i proceed with the next issue?

Best regards,
Panos.

**Comment by knz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/cli/sql.go, line 366 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747#-Kb78KhPniV_oNmwwDis:-Kb78KhPniV_oNmwwDit:bxhpnxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/424a6fedf3d3442c2275ec51b42c41a0b382327e/pkg/cli/sql.go#L366)):*
> ```Go
> 
> 	// Query the server for the current transaction status.
> 	query := makeQuery(`SHOW TRANSACTION STATUS`)
> ```

Move the current body of this function to a separate function `refreshTransactionStatus` and call it from `doRefreshPrompts`.

---

*[pkg/cli/sql.go, line 369 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747#-Kb78ETMCcgxIGRvkfEC:-Kb78ETMCcgxIGRvkfED:b-zgia1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/424a6fedf3d3442c2275ec51b42c41a0b382327e/pkg/cli/sql.go#L369)):*
> ```Go
> 	rows, err := query(c.conn)
> 	if err != nil {
> 		fmt.Fprintf(osStderr, "error retrieving the database name: %v", err)
> ```

Change the error message.

---

*[pkg/cli/sql.go, line 382 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747#-Kb7890xDVAawfqwXpA0:-Kb7890y3WzVxtbYBvLE:b-9v09vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/424a6fedf3d3442c2275ec51b42c41a0b382327e/pkg/cli/sql.go#L382)):*
> ```Go
> 	if err != nil {
> 		fmt.Fprintf(osStderr, "invalid transaction status")
> 		//return c.refreshPrompts(" ?", nextState)
> ```

Remove this comment.

---

*[pkg/cli/sql.go, line 425 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747#-Kb78ole2vCbd9QRqcO8:-Kb78olfJWD4dL9LfQAG:b-mvs86y) ([raw file](https://github.com/cockroachdb/cockroach/blob/424a6fedf3d3442c2275ec51b42c41a0b382327e/pkg/cli/sql.go#L425)):*
> ```Go
> 	err = rows.Next(dbVals[:])
> 	if err != nil {
> 		fmt.Fprintf(osStderr, "error retrieving the database name: %v", err)
> ```

Can you clarify what is expected when the user has not set a current database yet with `SET DATABASE`. To me it looks like the prompt should just print the transaction status without reporting any error. That is, an empty result from `SHOW DATABASE` should not cause an error message to be printed. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747)*

**Comment by knz** [comment]
(sorry for the late answer, I had taken a week vacation)

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747#-:-Kb794_01lNuKIb17BmB:bfzbb9g)*

**Comment by pmamatsis** [comment]
Hi @knz,
   no worries about the late reply. I have already started to work on your feedback soon i will do a push...

Best regards,
Panos.

**Comment by pmamatsis** [comment]
Hi @knz,
   i have finished with the rest of the issues except the first one...I wanted to ask you quick question...the new function `refreshTransactionStatus` that will be created and called from `doRefreshPrompts` is not going to return formatted string value, correct? It's going to comply (somehow) with the whole FSM setup of the sql.go...right?

Best regards and thank you in advance,
Panos.

**Comment by knz** [comment]
yes that's correct

**Comment by pmamatsis** [comment]
Hi @knz,
   so, since i am going to move the current code of `doRefreshPrompts` into the `refreshTransactionStatus` then this means that the later will chain the call to the `refreshDatabaseName`, correct? I just want to double check it with you in order not to waste you time with my code review...

Best regards and thanks in advance,
Panos.

**Comment by knz** [comment]
> since i am going to move the current code of |doRefreshPrompts| into the
> |refreshTransactionStatus| then this means that the later will chain the
> call to the |refreshDatabaseName|, correct?

yes.

also do not worry about wasting anyone's time. The learning process
takes its time. It's normal.

**Comment by pmamatsis** [comment]
Hi @knz,
   i have just finished with the push and i see that there is no error. If you are also all right please tell me so, so i can close this push and proceed with the next issue.

Best regards,
Panos.

**Comment by knz** [comment]
You've done excellent work here.

:lgtm_strong: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12747#-:-Kbe-IMxhMpdZNgVbMfC:bel2r7l)*

**Comment by knz** [comment]
Thanks for your contribution!

**Comment by pmamatsis** [comment]
Good afternoon @knz,
   firstly let me thank you and @dt for your welcome feedback in order to help me with this. Since we have finished with this issue is it possible for me to touch the next one? I wanted to give a shot to this one: cli: 

> add missing username in SQL prompt for connection URL (#12408)

Is it all right? Or is someone else is currently working on it?

Best regards,
Panos.

**Comment by knz** [comment]
We already have the username in the prompt, but it merely mirrors the username entered in the connection string. We do not query the database for the current user. I don't know whether that matters.

**Comment by knz** [comment]
On 29-01-17 12:54, pmamatsis wrote:
> Is it all right? Or is someone else is currently working on it?
> 

But to answer your question, no no one else is working on this, so you
can go ahead!

**Comment by pmamatsis** [comment]
Hi @knz and @jordanlewis,
   have i accidentally broken something ? Is there anything i can do for this issue ?

Best regards,
Panos.

**Pull request merged**
