### PR TITLE
bazel: set correct flags for `printf` analyzer

### LINKED ISSUE #80006: bazel: make sure we're configuring the correct set of `printf` funcs for `roachvet` checks in `nogo`
We have a list of `printf`-style functions in `lint_test.go` in https://github.com/cockroachdb/cockroach/blob/cfb6bab73d7f3b4e1705df4d85f1625339efc8ae/pkg/testutils/lint/lint_test.go#L2062. We should make sure we configure this list the same way in `build/bazelutil/nogo_config.json`. Might be easiest to just wait until https://github.com/bazelbuild/rules_go/pull/3082 hits a release.

Jira issue: CRDB-15692

Epic CRDB-8349

### PR DESCRIPTION
**Pull request by rickystewart**
Closes #80006.

Release note: None
Epic: CRDB-8349

### CODE REVIEW

**Review by healthy-pod — APPROVED** [review]
Since `lint_test.go` is a `go` file we can keep them synced by reading `nogo_config.json`. Drawback is if schema changes this breaks (but at least it breaks and we know and fix it compared to drifting silently otherwise). Not sure which is better, up to you.

**Comment by healthy-pod** [comment]
```
jsonFile, err := os.ReadFile(nogo_config_file)
if err != nil {
// deal with err
}
var printSchema map[string]map[string]map[string]string
if err := json.Unmarshal(jsonFile, &printSchema); err != nil {
// deal with err
}
printfuncs := printSchema["printf"]["analyzer_flags"]["funcs"]
```

**Review by rail — APPROVED** [review]

**Comment by jlinder** [comment]
Note that since the epic is linked in the referenced issue's body, the epic ref isn't necessary.

**Comment by rickystewart** [comment]
bors r=rail,healthy-pod

**Pull request merged**
