### PR TITLE
exec: template the distinct operator

### PR DESCRIPTION
**Pull request by jordanlewis**
Template the distinct operator using a new approach, where the template
file is normal executable Go, but prevented from being compiled normally
by a build tag.

The generator file reads the template file in, replaces some special
variables with template variables, and runs the template.

There are two main warts with this approach:

1. ColVec needed to be extended with a dummy _TemplateType method whose
   signature is _TemplateType() []interface{}, so the template can
   compile. That method is implemented to always panic().
2. The template generator needs to textually replace things in a way
   that can be confusing. _TYPE, _GOTYPE, _TYPES_T, _EQUALITY_FN, and
   _TemplateType all need to be replaced, with {{.}}, {{.GoTypeName}},
   types.{{.}}, {{.EqualityFunction}} and {{.}} respectively.

Also, rename distinctFinalizerOp to boolVecToSelOp and move to its own
file. The implementation doesn't change.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
PTAL

**Review by asubiotto — APPROVED** [review]
LGTM. Very educational PR.

> Reviewed 6 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31957#-:-LQ9eoco99tcHN2CKFt5:b-ueqhds)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 1315 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31957#-LQ9af352KZw08jAkST1:-LQ9af352KZw08jAkST2:bn02q5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4427a7ff655a4b30f71b199f6feceeadf9a2935b/Makefile#L1315)):*
> ```Makefile
> 	@$(settings-doc-gen) gen settings-list --format=html > $@
> 
> pkg/sql/exec/distinct.og.go: pkg/sql/exec/distinct_tmpl.go
> ```

Is it necessary to have the `_tmpl` and `_gen` files in `pkg/sql/exec`? I like how the projection ops template is in `execgen` but I guess that might be more difficult to do with this approach. This is just being nitpicky but wondering if we can find a better structure.

**Comment by jordanlewis** [comment]
`distinct_gen.go` is already in `execgen`, and it's pretty hard to not have the template in the main package if we want to try to make it read like normal Go, for a couple of reasons. I actually kind of like having the template in the main package - as it's the thing that I would probably prefer to read when understanding what the code does.

That being said I do hear your point. If you can figure out a better way for this I'm all ears, and I'm definitely going to keep thinking on it over time.

bors r+

**Comment by jordanlewis** [comment]
Needed to rebase to pick up the decimal/date stuff, good to go now though.

bors r+

**Comment by jordanlewis** [comment]
Flaky test: `TestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected` failed. Going to file an issue for that and retrigger. This is frustrating.

bors r+

**Comment by jordanlewis** [comment]
The batch crashed. Bors really hates this PR.

bors r+

**Pull request merged**
