### PR TITLE
sql: omit virtual tables from new column type telemetry

### LINKED ISSUE #45215: sql: don't count virtual tables in data type telemetry
In https://github.com/cockroachdb/cockroach/pull/44175 we added telemetry counters for data types. Unfortunately, we are counting virtual tables data types too. We should stop counting virtual table data types in this telemetry.

### PR DESCRIPTION
**Pull request by otan**
Resolves https://github.com/cockroachdb/cockroach/issues/45215.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Is it possible to add a test for this? code looks good though

**Comment by otan** [comment]
tests are already in place (https://github.com/cockroachdb/cockroach/blob/6525c22d4e7145810c7285780d9813fa6dd9bc8f/pkg/sql/logictest/testdata/logic_test/create_table#L27)
i can't really add one for virtual schemas in particular though...

**Comment by rohany** [comment]
you could ensure that there aren't entries for some virtual table names right? like tables with prefix  `crdb_internal`, `information_schema` and `pg_catalog`

**Comment by otan** [comment]
> you could ensure that there aren't entries for some virtual table names right? like tables with prefix crdb_internal, information_schema and pg_catalog

it's not names it's types. when running these tests under CI the features table seems to be populated with other tests too, so it's a little difficult finding _the_ type that isn't in virtual or anything.

**Comment by rohany** [comment]
ohhh woops, i misunderstood. ok, lgtm.

**Comment by otan** [comment]
bors r=rohany

ty :)

**Comment by otan** [comment]
bors r=rohany

**Comment by otan** [comment]
`license/cla` keeps not triggering...

**Comment by otan** [comment]
bors r=rohany

**Pull request merged**
