### PR TITLE
kvserver: partial implementation of ReplicasStorage

### PR DESCRIPTION
**Pull request by sumeerbhola**
The significant missing piece is part of the Init
implementation to handle a RecoveryInconsistentReplica that requires applying committed raft log entries to the state machine. This missing piece will need to wait until #75729 is fixed.

There are multiple TODOs, including related to concurrency, but the implementation is complete enough for the datadriven test to exercise many state transitions. Additionally, the test exercises loss of unsynced state, and fixup of that state in ReplicasStorage.Init, by using vfs.NewStrictMem.

Informs #16624

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
cc @cockroachdb/replication

**Comment by sumeerbhola** [comment]
I have some changes sitting in my local copy that I need to finish and push -- I'm going to do so soon. Is it ok if we delay closing this until someone is actually ready to pick this up -- that allows me to continue pushing changes meanwhile if something occurs to me?

**Comment by tbg** [comment]
Of course! I will hold off on touching this until you confirm that you're ready.

**Comment by sumeerbhola** [comment]
I've pushed my pending changes.

**Comment by tbg** [comment]
Interesting failure on the PR here, hope this isn't indicative of some storage bug:

```
sandbox/2316/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/kv/kvserver/kvserver_test_/kvserver_test.runfiles/com_github_cockroachdb_cockroach/pkg/kv/kvserver/datadriven.go:426
            	Error:      	Received unexpected error:
            	            	L6: 000022: file size mismatch (000022.sst): 0 (disk) != 1208 (MANIFEST)
            	            	(1) attached stack trace
            	            	  -- stack trace:
            	            	  | github.com/cockroachdb/pebble/internal/manifest.(*Version).CheckConsistency
            	            	  | 	github.com/cockroachdb/pebble/internal/manifest/external/com_github_cockroachdb_pebble/internal/manifest/version.go:1066
            	            	  | github.com/cockroachdb/pebble.Open
            	            	  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/open.go:258
            	            	  | github.com/cockroachdb/cockroach/pkg/storage.NewPebble
            	            	  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:933
            	            	  | github.com/cockroachdb/cockroach/pkg/storage.Open
            	            	  | 	github.com/cockroachdb/cockroach/pkg/storage/open.go:235
            	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.TestReplicasStorageBasic.func1.3
            	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicas_storage_test.go:79
            	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.TestReplicasStorageBasic.func1.4
            	            	  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replicas_storage_test.go:94
            	            	  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.TestReplicasStorageBasic.func1.5
```

**Comment by tbg** [comment]
Closing for https://github.com/cockroachdb/cockroach/pull/91579, which is a copy of this PR that doesn't spam Sumeer's inbox.

**Pull request closed without merging**
