### PR TITLE
sql: refactor procedures and prevent incorrect usage of UDFs and procedures

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: combine Overload.IsUDF and Overload.IsProcedure into enum

The boolean struct fields `Overload.IsUDF` and `Overload.IsProcedure`
have been combined into a single enum `Overload.Type` with the type
`RoutineType`. This enum maps more accurately to the concept of an
overload and prevents the invalid state where both `IsUDF` and
`IsProcedure` are true.

Release note: None

#### sql: use `*tree.FuncExpr` as child of `tree.Call`

This commit replaces the `Name` and `Exprs` struct fields of `tree.Call`
with a single `*tree.FuncExpr` field. This allows existing function
resolution logic to be reused for procedures.

Release note: None

#### sql: prevent incorrect usage of UDFs and procedures

This commit disallows:

1. The use of UDFs in a `CALL` statement (only procedures can be used
   here).
2. The use of procedures outside of `CALL` statements.

Epic: CRDB-25388

Release note: None

### CODE REVIEW

**Review by rharding6373 — CHANGES_REQUESTED** [review]
Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110822#-:-NedR65XAzj6DkixcFkp:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/parser/testdata/call` line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110822#-NedQ1ql6X4M0xDX_Lq5:-NedQ1qm8QWnU6GPq6IA:b-cr6aw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a1fec64ef208a4d48231915300684b366a64f9/pkg/sql/parser/testdata/call#L7)):*
> ```
> CALL p() -- fully parenthesized
> CALL p() -- literals removed
> CALL p() -- identifiers removed
> ```

We should still consider the procedure name an identifier.

**Comment by mgartner** [comment]
*[`pkg/sql/parser/testdata/call` line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110822#-NedQ1ql6X4M0xDX_Lq5:-NedcDiiDEhClD6fJSGY:b-hugc6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a1fec64ef208a4d48231915300684b366a64f9/pkg/sql/parser/testdata/call#L7)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

We should still consider the procedure name an identifier.
</blockquote></details>

Hmm, maybe this is an existing bug with FuncExpr? I've add a test with a function call in a SELECT expression and the name isn't redacted. 

I see that we have tests for built-in functions, where the name is not redacted: https://github.com/cockroachdb/cockroach/blob/f633361ae4f62798d1086d357df8b4af2900012c/pkg/sql/parser/testdata/predefined_functions

But at parse-time there's no way to know whether a function invocation is a built-in or not because it hasn't been resolved to a specific overload yet. Should we just redact all function names, even potentially built-in ones?

**Comment by mgartner** [comment]
*[`pkg/sql/parser/testdata/call` line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110822#-NedQ1ql6X4M0xDX_Lq5:-NedfHv93KWogNy4Nj8l:bk7yf1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a1fec64ef208a4d48231915300684b366a64f9/pkg/sql/parser/testdata/call#L7)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmm, maybe this is an existing bug with FuncExpr? I've add a test with a function call in a SELECT expression and the name isn't redacted. 

I see that we have tests for built-in functions, where the name is not redacted: https://github.com/cockroachdb/cockroach/blob/f633361ae4f62798d1086d357df8b4af2900012c/pkg/sql/parser/testdata/predefined_functions

But at parse-time there's no way to know whether a function invocation is a built-in or not because it hasn't been resolved to a specific overload yet. Should we just redact all function names, even potentially built-in ones?
</blockquote></details>

The `FmtAnonymize` flag which is used for `"identifiers removed"` explicitly doesn't anonymize function names: https://github.com/cockroachdb/cockroach/blob/f0a2788c2fa099c1c9263aa5675f95075ff735fe/pkg/sql/sem/tree/format.go#L79-L82

The historical context here is a bit confusing. It mentions #13968, and that's already been addressed. So it may be ok to anonymize function names now, but it's not clear.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/parser/testdata/call` line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110822#-NedQ1ql6X4M0xDX_Lq5:-NeduqyS1LXIsB-6BTOT:b-t6rjmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a1fec64ef208a4d48231915300684b366a64f9/pkg/sql/parser/testdata/call#L7)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The `FmtAnonymize` flag which is used for `"identifiers removed"` explicitly doesn't anonymize function names: https://github.com/cockroachdb/cockroach/blob/f0a2788c2fa099c1c9263aa5675f95075ff735fe/pkg/sql/sem/tree/format.go#L79-L82

The historical context here is a bit confusing. It mentions #13968, and that's already been addressed. So it may be ok to anonymize function names now, but it's not clear.
</blockquote></details>

Thanks for doing the code archaeology. It looks like this is the format used for crash reports and error telemetry to redact/anonymize queries. This seems even more strict than PCI compliance -- we remove table names as identifiers, too. Since identifiers like table names and enum names are ok for PCI compliance, I would assume that function names are too, but since we remove them for telemetry, I'm not sure user-provided names for functions and procedures are ok or useful. I'll ask for more context in slack.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/parser/testdata/call` line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110822#-NedQ1ql6X4M0xDX_Lq5:-Nee3eNL2sCcO3SD8zfq:bv4knsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a1fec64ef208a4d48231915300684b366a64f9/pkg/sql/parser/testdata/call#L7)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Thanks for doing the code archaeology. It looks like this is the format used for crash reports and error telemetry to redact/anonymize queries. This seems even more strict than PCI compliance -- we remove table names as identifiers, too. Since identifiers like table names and enum names are ok for PCI compliance, I would assume that function names are too, but since we remove them for telemetry, I'm not sure user-provided names for functions and procedures are ok or useful. I'll ask for more context in slack.
</blockquote></details>

It's a bug: https://cockroachlabs.slack.com/archives/CHVV403F0/p1695070413672459?thread_ts=1695070295.062209&cid=CHVV403F0

I can make a PR to fix it that's backportable, but it shouldn't hold up this change.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110822#-:-Nee5H815PaDk0d-IDdM:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

**Review by mgartner — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110822#-:-NeeDsjYDBU7GZ7k5nM5:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/parser/testdata/call` line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110822#-NedQ1ql6X4M0xDX_Lq5:-NeeDpKyEXfzskzGZ3W7:b-hay2ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a1fec64ef208a4d48231915300684b366a64f9/pkg/sql/parser/testdata/call#L7)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It's a bug: https://cockroachlabs.slack.com/archives/CHVV403F0/p1695070413672459?thread_ts=1695070295.062209&cid=CHVV403F0

I can make a PR to fix it that's backportable, but it shouldn't hold up this change.
</blockquote></details>

Thanks!!

**Pull request merged**
