### PR TITLE
verbose logging in multiraft package

### PR DESCRIPTION
**Pull request by tbg**
this should help addressing issues such as #285.

### CODE REVIEW

**Comment by bdarnell** [comment]
Multiraft is *really* verbose at v=8 - it logs at least twice per tick (unless it's blocked), which in the tests is every millisecond. I think 6 or 7 is the right level of "show everything" that we want for the tests.

**Comment by tschottdorf** [comment]
changed.

**Comment by bdarnell** [comment]
I'd rather do this by passing TESTFLAGS=--vmodule=multiraft=7 when we run the tests on circleci. I don't think we should turn up the verbosity be default for local test runs, and we should have more verbose logging of raft actions for tests in the storage package too.

**Comment by cockroach-team** [comment]
Didn't know this was possible, definitely sounds better. Feel free to go
ahead and do it, I can't at the moment.

**Comment by tschottdorf** [comment]
@bdarnell how does that look?

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
