### PR TITLE
colexec: clean up vectorized stats

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note (sql change): `selectivity` information has been removed
from EXPLAIN ANALYZE diagrams which would be present if the query was
executed via the vectorized engine because it has been quite confusing
and probably not helpful information.

Release note (sql change): `stall time` has been renamed to
`IO + execution time` in EXPLAIN ANALYZE diagrams for the queries that are
executed via the vectorized engine.

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53153)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/execpb/stats.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53153#-MFFEjhFEwRBpOR48rkn:-MFFEjhFEwRBpOR48rko:b-up3y2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bbd91ead6649aabd8b799f8ecc2c4b8a3231f4/pkg/sql/colexec/execpb/stats.go#L54)):*
> ```Go
> 	batchesOutputQueryPlanSuffix     = "batches output"
> 	tuplesOutputQueryPlanSuffix      = "tuples output"
> 	ioIncludedTimeQueryPlanSuffix    = "IO + execution time"
> ```

Are you sure it includes execution time? I'm under the impression it's only IO.
___
*[pkg/sql/colexec/execpb/stats.proto, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53153#-MFFEwXg4JD51aeKaQ6Z:-MFFEwXg4JD51aeKaQ6_:b-c43qid) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bbd91ead6649aabd8b799f8ecc2c4b8a3231f4/pkg/sql/colexec/execpb/stats.proto#L29)):*
> ```protobuf
>   google.protobuf.Duration time = 4 [(gogoproto.nullable) = false,
>                                   (gogoproto.stdduration) = true];
>   reserved 5;
> ```

Why not just rename 5? The semantics are the same and it would avoid having to bump distsql version.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53153)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/execpb/stats.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53153#-MFFEjhFEwRBpOR48rkn:-MFGe5qy4os-LLQqczNn:b-81mu9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bbd91ead6649aabd8b799f8ecc2c4b8a3231f4/pkg/sql/colexec/execpb/stats.go#L54)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Are you sure it includes execution time? I'm under the impression it's only IO.
</blockquote></details>

It's only IO in the row engine, in the vectorized we measure the time differently, so it'll include both IO (`cFetcher` waiting for next KV) and execution (`cFetcher` decoding things).
___
*[pkg/sql/colexec/execpb/stats.proto, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53153#-MFFEwXg4JD51aeKaQ6Z:-MFGeHo58sgU8BnDlEtm:b-i7i6yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bbd91ead6649aabd8b799f8ecc2c4b8a3231f4/pkg/sql/colexec/execpb/stats.proto#L29)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not just rename 5? The semantics are the same and it would avoid having to bump distsql version.
</blockquote></details>

Done. I did that initially as well but then decided to change to a different value just to be safe, but I've now remembered that I tried renaming a field and it worked like a charm in mixed-version cluster.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53153)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/execpb/stats.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53153#-MFFEjhFEwRBpOR48rkn:-MFGyzPVAfa-cUEFX_I6:bpqnsja) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bbd91ead6649aabd8b799f8ecc2c4b8a3231f4/pkg/sql/colexec/execpb/stats.go#L54)):*
> It's only IO in the row engine

I don't think that's true (if you consider "decoding" = "execution time"). `rowFetcherStatCollector` starts timing before the call to `NextRow` and stops the timer after. I vote to keep it as just `IO`, I think it's less confusing because we can't define "execution" time when stalling.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53153)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187 and @jordanlewis)

___
*[pkg/sql/colexec/execpb/stats.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53153#-MFFEjhFEwRBpOR48rkn:-MFGzu2vCZkSNB8d9n8n:bchbhi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bbd91ead6649aabd8b799f8ecc2c4b8a3231f4/pkg/sql/colexec/execpb/stats.go#L54)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

> It's only IO in the row engine

I don't think that's true (if you consider "decoding" = "execution time"). `rowFetcherStatCollector` starts timing before the call to `NextRow` and stops the timer after. I vote to keep it as just `IO`, I think it's less confusing because we can't define "execution" time when stalling.
</blockquote></details>

cc @awoods187 @jordanlewis on naming

There was some discussion here https://cockroachlabs.slack.com/archives/C8HD41C82/p1594249854088100?thread_ts=1594243319.067000&cid=C8HD41C82.

Maybe simply "IO time" is less confusing than "IO + execution time", but the latter is more precise IMO.

**Review by asubiotto — APPROVED** [review]
:lgtm: I leave the choice up to you

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53153#-:-MFH0kZL4bz--kVZpwSA:b-jioh5u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187 and @jordanlewis)

**Comment by yuzefovich** [comment]
After discussing with Jordan, we decided to go with Alfonso's suggestion and just to use simply "IO time" since it's less confusing. I'll wait for a green CI and then will merge this.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
