### PR TITLE
storage: consider quiescing when owning expired lease

### PR DESCRIPTION
**Pull request by tbg**
Consider a dormant range whose lease expired peacefully before the Raft
group had a chance to quiesce. Prior to this commit, no replica would ever
quiesce this range, as this required both Raft and an active Range
leadership at one location. However, there isn't a mechanism to "poke"
inactive Range leadership (i.e. trigger a lease renewal), and so a Range in
that state would just "sit around" forever, consuming CPU on ticks. It is
suspected that this explains severe instability on one of our production
clusters, where a large table was dropped, and its replicas seemingly never
quiesce, hogging resources.

Release note (bug fix): Fixed a situation (common after dropping a table) in
which empty ranges continued to remain active (thus consuming more CPU than
necessary).

### CODE REVIEW

**Comment by tschottdorf** [comment]
I'm not sure this fixes the problem at hand, but it seems reasonable to assume so based on my reading of the code (and logspy output). Also, there is no testing coverage here. Perhaps I should roll out this change to cyan to see whether it fixes the situation?

**Review by petermattis — COMMENTED** [review]
All table ranges have epoch leases. Where is expiration coming into play?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28053#-:-LIgZe-97CLw8qPU9WdZ:b-ktges0)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tschottdorf** [comment]
The epoch can change and then leases are expired (as in, not active).

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28053)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 4463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28053#-LIgwwM16ko6ZqV6_AQ1:-LIgwwM16ko6ZqV6_AQ2:b-kf9ue1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece11ad24cf8f478b11b7808d0f05d2c7d9e3acf/pkg/storage/replica.go#L4463)):*
> ```Go
> 		return nil, false
> 	}
> 	// Only quiesce if this replica is (to the best of our knowledge) the most
> ```

What if our knowledge is outdated? What if another node has proposed acquiring the lease but we haven't processed it yet? If we're considering quiescing and we held the most recent lease but it has expired, maybe we should try to renew our lease instead. 

OTOH, that may not solve the problem. My hypothesis is that the root of the problem is that these dormant ranges are being processed by the replica scanner, and different queues process at different rates. Some queues initialize the raft group without getting a lease, which puts them into this unquiesced state. Other queues acquire leases, which allows them to quiesce, but this takes longer. Acquiring the lease *here* doesn't accomplish the real need, which is to apply backpressure to the fast queues that are initializing the raft group. (alternately, we need to ensure that any non-needsLease queue does not inadvertently wake up a dormant raft group)
___
*[pkg/storage/replica.go, line 4468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28053#-LIgxJQh6TCdfoQTERwO:-LIgxJQi2zcMStzPv0uU:b-aov3k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece11ad24cf8f478b11b7808d0f05d2c7d9e3acf/pkg/storage/replica.go#L4468)):*
> ```Go
> 	// propose.
> 	//
> 	// Note that we can't ask that lease to be live. If the range is dormant but
> ```

I don't think you mean "dormant" (i.e. "no raft group") here. Dormant ranges are always in a quiescent state.

**Pull request closed without merging**
