### PR TITLE
status: account for gomaxprocs in cpu utilization

### LINKED ISSUE #101633: server: account for GOMAXPROCS when calculating num_cpus
CRDB uses "CPU shares" to calculate CPU utilization [^1]. The utilization is calculated as `usage/cpu_shares`. The CPU Shares are calculated using the number of available CPUs at start time if `cpu.cfs_period_us` or `cpu.cfs_quota_us` are not set (<=0) . Otherwise, CPU Shares is equal to `cpu.cfs_quota_us/cpu.cfs_period_us`[^2].

The environment variable `GOMAXPROCS` which controls the number of parallel processors in use, is not taken into account when calculating the cpu shares. This issue is to update the code so it is.

**Describe the solution you'd like**

Update [^1] so that `GOMAXPROCS` is used if it is less than `num_cpus` otherwise `num_cpus` is used (assuming no quota/period set). 

[^1]: https://github.com/cockroachdb/cockroach/blob/a95ffcd9ce5fd06eef08f0f79bed4908638f6b60/pkg/server/status/runtime.go#L522-L522
[^2]: https://github.com/cockroachdb/cockroach/blob/a95ffcd9ce5fd06eef08f0f79bed4908638f6b60/pkg/util/cgroups/cgroups.go#L627-L634

### LINKED ISSUE #103472: sql: throttling row sampling is based on potentially dubious CPU signal
The SQL stats row sampler uses the normalized CPU to pace and throttle sampling:
https://github.com/cockroachdb/cockroach/blob/a0e80d2be66a0c656cc9ce3fd8b678c362a158f5/pkg/sql/rowexec/sampler.go#L285-L289

However due to https://github.com/cockroachdb/cockroach/issues/101633, the normalized CPU signal used may be under reported if `GOMAXPROCS` is set to a lower number than the number of CPUs available for the process -  `num_cpus`.

This may lead to a lack of throttling due to the underreported normalized CPU.

Jira issue: CRDB-28020

### PR DESCRIPTION
**Pull request by kvoli**
When a CRDB process had GOMAXPROCS set lower than the number of CPUs
available, the normalized CPU utilization metric would only account for
the number of processors. However, the process could never use more than
GOMAXPROCS processors in parallel, capping CPU capacity. As a result,
the normalized CPU utilization would be under reported.

e.g. When the number of CPUs available is 4, GOMAXPROCS is 2 and the
usage is 1, utilization would be reported as 25%, whilst the real
utilized capacity is 50%.

Update the normalized CPU calculation to take the GOMAXPROCS into
account, using the smallest capacity for utilization calculation. This
affects the `sys.cpu.combined.percent-normalized` metric.

Fixes: https://github.com/cockroachdb/cockroach/issues/101633
Fixes: https://github.com/cockroachdb/cockroach/issues/103472

Release note (bug fix): `sys.cpu.combined.percent-normalized` now
uses `GOMAXPROCS`, if lower than the number of CPU shares when
calculating CPU utilization.

### CODE REVIEW

**Comment by kvoli** [comment]
Running `./cockroach workload run kv --drop --read-percent=0 --max-rate=5000`:

`./cockroach start-single-node --insecure --store=type=mem,size=8GiB`
image
`GOMAXPROCS=8 ./cockroach start-single-node --insecure --store=type=mem,size=8GiB`
image

**Review by knz — APPROVED** [review]

**Comment by kvoli** [comment]
TYFTR

bors r=knz

**Comment by kvoli** [comment]
bors r=knz

**Comment by kvoli** [comment]
One last try. The failure appears unrelated, judging the stacks. Likely related to the other restore tests flaking.

bors r+

**Pull request merged**
