### PR TITLE
Add Nib, UI tweaks

### PR DESCRIPTION
**Pull request by maxlang**
- updated bower version
- added nib so stylus will automatically add vendor prefixes
- changed the mithril type defs in a fork and pointed to it (I'll create an issue for this)
- style tweaks including graph units and table font

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3860)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. Would be nice to include before/after screenshots in changes that touch CSS (at least for my untrained eyes).

**Comment by mrtracy** [comment]
LGTM

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3860#-:-K8umiraPVjbYpQe_6ND:676834233)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 4 of 5 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3860)*

**Comment by maxlang** [comment]
Added comma.

Mostly this wasn't a very visual change, but here a few of the differences:

Table font:

Before: 
screen shot 2016-01-31 at 12 57 41 pm

After:
screen shot 2016-01-31 at 1 03 49 pm

Broken graphs:

Before:
screen shot 2016-01-31 at 12 58 43 pm

After:
screen shot 2016-01-31 at 1 03 59 pm

Some tooltip formatting:

Before:
screen shot 2016-01-31 at 12 58 36 pm

After:
screen shot 2016-01-31 at 1 03 55 pm

Also, adding nib allowed me to remove some vendor prefixes which are now added automatically.

**Comment by tamird** [comment]
LGTM. first and third commit look like they could be combined, though.

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3860#-:-K9OL0bPjSkys3VP3mdw:1830233632)*

**Comment by maxlang** [comment]
Makes sense - I originally separated out adding deps/using deps but I guess that doesn't really make sense.

**Pull request merged**
