### PR TITLE
roachprod: enumerate local clusters in `roachprod list --mine`

### PR DESCRIPTION
**Pull request by irfansharif**
Was suspiciously missing before.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
This is going to make `roachprod destroy --all-mine` destroy local clusters as well. Or maybe it's just going to cause that to throw an error because we aren't special-casing `clusterName != config.Local` in `destroyCmd.Run`.

Is that a behavior change we want to make? I don't see a strong reason why not, but I also know that I would have accidentally deleted a local cluster that I didn't want to delete a few times over the past month if that was the behavior here. What do you think?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51922#-:-MDHIrqA-nowbVfXJf6-:b-r677fy)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by irfansharif — COMMENTED** [review]
> This is going to make roachprod destroy --all-mine destroy local clusters as well. 

It does indeed, and I think I do actually want this behavior. I've been using `roachprod destroy local` in my local testing, and was just a bit annoyed by the fact that it errors out if `local` didn't exist, which seems like `destroy --all-mine` should be handling. Can post to #engineering as a PSA.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51922#-:-MDHLgQM1gfLVobX5VQs:b-7lfa66)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by irfansharif** [comment]
> It does indeed

(actually, err, it doesn't do it properly. Let me fix that.)

**Comment by nvanbenschoten** [comment]
> Can post to #engineering as a PSA.

Please do. I'll vote against it, but I'm happy to have the discussion and be outvoted if others see more utility in it than I do.

My feeling is basically that I use `--all-mine` to clean up any resources that might be costing the company money. A local cluster doesn't cost anything, so I rarely want to destroy my local cluster and, when I do, I'm fine needing to be explicit about it.

**Comment by irfansharif** [comment]
Outvoted, RIP.

**Pull request closed without merging**
