### PR TITLE
sql: run scrub FK queries through the internal executor

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: handle ignore_foreign_keys hint for table-by-id

We weren't handling the `IGNORE_FOREIGN_KEYS` hint in the table-by-id
case. Moving the addition of the table to the metadata into
`buildScan`.

Release note: None

#### sql: run scrub FK queries through the internal executor

This commit rewrites the scrubbing of FKs to use the same queries used
by `VALIDATE CONSTRAINT`. This allows us to use the internal executor
instead of a hacky (non-optimizer-friendly) path which was tweaking
the distsql plan.

Note that the removed code was incorrectly handling NULLs for FKs
(mixing null and non-null columns is always ok with PARTIAL MATCH, and
is never ok with FULL MATCH).

The `VALIDATE CONSTRAINT` queries are improved to return the
referencing columns and the PK columns (which leads to improved error
messages).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
@justinj - could you take a quick look at the first commit? It's a follow-up fix for #37572.

**Review by justinj — COMMENTED** [review]
first commit :lgtm:, does seem like the right place for that code anyway.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37604#-:-LfLgMMH2g5x2jrUbxDz:b-3mzemg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/select.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37604#-LfLgJog8BmA9BotUZCg:-LfLgJog8BmA9BotUZCh:b-rlthgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b827f9812aa13094165ce5c673c83f7e1fc14c3/pkg/sql/opt/optbuilder/select.go#L313)):*
> ```Go
> 	inScope *scope,
> ) (outScope *scope) {
> ```

nit: extra line?

**Review by thoszhang — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37604)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lucy-zhang and @RaduBerinde)

___
*[pkg/sql/check.go, line 151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37604#-LfLuP-85LoUx0S0AQG2:-LfLuP-85LoUx0S0AQG3:b-sn51pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e96fec8cfb467f311b32208f358c69d13141cd87/pkg/sql/check.go#L151)):*
> ```Go
> 	targetIdx *sqlbase.IndexDescriptor,
> 	limitResults bool,
> 	asOf hlc.Timestamp,
> ```

This seems to not be working with AOST. On this branch, I get
```
root@127.0.0.1:63715/defaultdb> create table t (a int primary key, b int, index (b));
CREATE TABLE

Time: 2.836ms

root@127.0.0.1:63715/defaultdb> alter table t add foreign key (b) references t (a);
ALTER TABLE

Time: 39.755ms

root@127.0.0.1:63715/defaultdb> experimental scrub table t as of system time '-1s';
pq: scrub-fk: AS OF SYSTEM TIME must be provided on a top-level statement
```
and on master,
```
root@127.0.0.1:63728/defaultdb> alter table t add foreign key (b) references t (a);
ALTER TABLE

Time: 40.599ms

root@127.0.0.1:63728/defaultdb> experimental scrub table t as of system time '-1s';
  job_uuid | error_type | database | table | primary_key | timestamp | repaired | details
+----------+------------+----------+-------+-------------+-----------+----------+---------+
(0 rows)

Time: 3.531ms
```
I tried ignoring the specified timestamp and instead passing in `hlc.MaxTimestamp` where this is called in scrub_fk.go, which results in
```
root@127.0.0.1:63668/defaultdb> experimental scrub table t as of system time '-1s';
  job_uuid | error_type | database | table | primary_key | timestamp | repaired | details
+----------+------------+----------+-------+-------------+-----------+----------+---------+
(0 rows)

Time: 2.807ms

root@127.0.0.1:63685/defaultdb> experimental scrub table t as of system time '-1h';
pq: relation "t" does not exist
```
which appears to be correct, since `t` was created sometime between 1 second and 1 hour ago. But I'm not sure why this works (if it does indeed work).
___
*[pkg/sql/scrub_fk.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37604#-LfLn9CgDGxCPrGCWUL_:-LfLn9CgDGxCPrGCWULa:b-6hetim) ([raw file](https://github.com/cockroachdb/cockroach/blob/e96fec8cfb467f311b32208f358c69d13141cd87/pkg/sql/scrub_fk.go#L72)):*
> ```Go
> 	}
> 
> 	// TODO(radu): also run matchFullUnacceptableKeyQuery if match type is "full".
> ```

I thought this was already added further down.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37604)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lucy-zhang)

___
*[pkg/sql/check.go, line 151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37604#-LfLuP-85LoUx0S0AQG2:-LfPWWG38QVfkCKM45JK:bbi095o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e96fec8cfb467f311b32208f358c69d13141cd87/pkg/sql/check.go#L151)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This seems to not be working with AOST. On this branch, I get
```
root@127.0.0.1:63715/defaultdb> create table t (a int primary key, b int, index (b));
CREATE TABLE

Time: 2.836ms

root@127.0.0.1:63715/defaultdb> alter table t add foreign key (b) references t (a);
ALTER TABLE

Time: 39.755ms

root@127.0.0.1:63715/defaultdb> experimental scrub table t as of system time '-1s';
pq: scrub-fk: AS OF SYSTEM TIME must be provided on a top-level statement
```
and on master,
```
root@127.0.0.1:63728/defaultdb> alter table t add foreign key (b) references t (a);
ALTER TABLE

Time: 40.599ms

root@127.0.0.1:63728/defaultdb> experimental scrub table t as of system time '-1s';
  job_uuid | error_type | database | table | primary_key | timestamp | repaired | details
+----------+------------+----------+-------+-------------+-----------+----------+---------+
(0 rows)

Time: 3.531ms
```
I tried ignoring the specified timestamp and instead passing in `hlc.MaxTimestamp` where this is called in scrub_fk.go, which results in
```
root@127.0.0.1:63668/defaultdb> experimental scrub table t as of system time '-1s';
  job_uuid | error_type | database | table | primary_key | timestamp | repaired | details
+----------+------------+----------+-------+-------------+-----------+----------+---------+
(0 rows)

Time: 2.807ms

root@127.0.0.1:63685/defaultdb> experimental scrub table t as of system time '-1h';
pq: relation "t" does not exist
```
which appears to be correct, since `t` was created sometime between 1 second and 1 hour ago. But I'm not sure why this works (if it does indeed work).
</blockquote></details>

Wow.. Thank you so much for testing that and catching this bug! Indeed, I was putting AOST in the wrong place and I didn't realize it wasn't being tested at all. As you observed, we don't need it at all because we are issuing the query within the same transaction which already has the timestamp set. I cleaned up the code and improved the test to verify this.
___
*[pkg/sql/scrub_fk.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37604#-LfLn9CgDGxCPrGCWUL_:-LfPbWDe71dKi_bOoZfh:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e96fec8cfb467f311b32208f358c69d13141cd87/pkg/sql/scrub_fk.go#L72)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I thought this was already added further down.
</blockquote></details>

Fixed.

**Review by thoszhang — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37604)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lucy-zhang and @RaduBerinde)

___
*[pkg/sql/check.go, line 151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37604#-LfLuP-85LoUx0S0AQG2:-LfVGxjf-X5hbveEMSrF:bcqi0hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e96fec8cfb467f311b32208f358c69d13141cd87/pkg/sql/check.go#L151)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Wow.. Thank you so much for testing that and catching this bug! Indeed, I was putting AOST in the wrong place and I didn't realize it wasn't being tested at all. As you observed, we don't need it at all because we are issuing the query within the same transaction which already has the timestamp set. I cleaned up the code and improved the test to verify this.
</blockquote></details>

Thanks for fixing the tests!

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Comment by RaduBerinde** [comment]
Failed tests don't involve SCRUB.

bors r+

**Pull request merged**
