### PR TITLE
exec: Add more tracing output to cfetcher.

### PR DESCRIPTION
**Pull request by rohany**
The previous commit adding logging to the cfetcher did not add enough logging statements to match
that of the rowfetcher. This PR adds these missing statements.

When rebased on top of #38945, this fixes most of the failing tests, except for a few which we think might not be compatible with the vectorized engine.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Thanks for the quick work on tracing stuff! I'm a little concerned about the performance impact, but I don't really know how cfetcher works.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-:-Lk5tzuuD9b_P8tsz3_L:b2ipwf7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/row/cfetcher.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-Lk5tZaHCRcwZWG7boez:-Lk5tZaHCRcwZWG7bof-:bcc97vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/23f700277d4457b7b833b687ec74803a05f600cb/pkg/sql/row/cfetcher.go#L80)):*
> ```Go
> 
> 	// One value per column that is part of the key; each value is a column
> 	// index (into cols); -1 if we don't need the value for that column.
> ```

[nit]: this comment might need an adjustment.
___
*[pkg/sql/row/cfetcher.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-Lk5t1yQEe_jMrDsLZAm:-Lk5t1yQEe_jMrDsLZAn:bsi91xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/23f700277d4457b7b833b687ec74803a05f600cb/pkg/sql/row/cfetcher.go#L373)):*
> ```Go
> 			}
> 			for i, id := range table.index.ExtraColumnIDs {
> 				// TODO (rohany): In order to properly trace output, we need all
> ```

Does this have a performance impact? Maybe we should propagate the information whether we want tracing or not here and keep `-1`s if tracing is not needed? I'm not sure if it possible or if it's important though.
___
*[pkg/sql/row/cfetcher.go, line 767 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-Lk5sTaf2xXwMh378VUH:-Lk5sTaf2xXwMh378VUI:bc94yac) ([raw file](https://github.com/cockroachdb/cockroach/blob/23f700277d4457b7b833b687ec74803a05f600cb/pkg/sql/row/cfetcher.go#L767)):*
> ```Go
> 
> // getDatumAt returns the converted datum object at the given (colIdx, rowIdx).
> // This function is meant for tracing and should not be used in hotpaths.
> ```

[nit]: `s/hotpaths/hot paths/`.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38971)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/row/cfetcher.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-Lk5tZaHCRcwZWG7boez:-Lk5udKGElqbijUh1YVh:bwwz6m6) ([raw file](https://github.com/cockroachdb/cockroach/blob/23f700277d4457b7b833b687ec74803a05f600cb/pkg/sql/row/cfetcher.go#L80)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: this comment might need an adjustment.
</blockquote></details>

I'll adjust this if it ends up that what I did was an OK change.
___
*[pkg/sql/row/cfetcher.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-Lk5t1yQEe_jMrDsLZAm:-Lk5ui5B23iRPwS7sbRQ:brhoe2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/23f700277d4457b7b833b687ec74803a05f600cb/pkg/sql/row/cfetcher.go#L373)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Does this have a performance impact? Maybe we should propagate the information whether we want tracing or not here and keep `-1`s if tracing is not needed? I'm not sure if it possible or if it's important though.
</blockquote></details>

I'm not sure the performance impact. I think it is a reasonable change because the row fetcher always decodes the extra columns as well. I'm not sure if this has an extra impact on the vectorized engine though.
___
*[pkg/sql/row/cfetcher.go, line 767 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-Lk5sTaf2xXwMh378VUH:-Lk5usmW2-3mJU2P8ZKD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/23f700277d4457b7b833b687ec74803a05f600cb/pkg/sql/row/cfetcher.go#L767)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/hotpaths/hot paths/`.
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38971)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/row/cfetcher.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-Lk5t1yQEe_jMrDsLZAm:-Lk5viBw6N4mB8G6Q-ys:b-28fmwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/23f700277d4457b7b833b687ec74803a05f600cb/pkg/sql/row/cfetcher.go#L373)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I'm not sure the performance impact. I think it is a reasonable change because the row fetcher always decodes the extra columns as well. I'm not sure if this has an extra impact on the vectorized engine though.
</blockquote></details>

Yeah, we definitely don't want to be doing this. You need to make sure this only happens when kv tracing is enabled. The cfetcher is more efficient than the fetcher because of stuff like this, we want to make sure we preserve that.

You could consider setting all columns to needed if tracing was on, like we talked about, as an alternative.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38971)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/row/cfetcher.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-Lk5t1yQEe_jMrDsLZAm:-Lk5wtidBtNtsWujHcRQ:b513it0) ([raw file](https://github.com/cockroachdb/cockroach/blob/23f700277d4457b7b833b687ec74803a05f600cb/pkg/sql/row/cfetcher.go#L373)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah, we definitely don't want to be doing this. You need to make sure this only happens when kv tracing is enabled. The cfetcher is more efficient than the fetcher because of stuff like this, we want to make sure we preserve that.

You could consider setting all columns to needed if tracing was on, like we talked about, as an alternative.
</blockquote></details>

ok, let me try that.

**Comment by rohany** [comment]
alright RFAL -- that was a much easier change than I anticipated the first time.

**Review by yuzefovich — COMMENTED** [review]
LGTM, but I'd wait for Jordan's approval.

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-:-Lk60Ejm4if15r4nP88W:b-ofisax)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @yuzefovich)

___
*[pkg/sql/row/cfetcher.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-Lk6-Uqp3phc5ir7GiRV:-Lk6-Uqp3phc5ir7GiRW:b-821hk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/026c40697b0b3ebbb17591a5c3d3d202e276a63a/pkg/sql/row/cfetcher.go#L84)):*
> ```Go
> 	// fullExtraValColOrdinals is the same as extraValColOrdinals but
> 	// does not contain any -1's. It is meant to be used only in logging.
> 	fullExtraValColOrdinals []int
> ```

[nit]: I'd call it "allExtra..."

**Comment by rohany** [comment]
RFAL -- updated a test case in vectorize. Double check me on this, but I think the old test case was slightly incorrect due to logging from everything under the columnarizer (index + lookup joins) being sent to a blackhole rather than the logs.

**Review by yuzefovich — COMMENTED** [review]
LGTM, thanks!

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-:-LkPWZHSEFbeGFVprB84:b2c0zcb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @yuzefovich)

**Review by jordanlewis — APPROVED** [review]
:lgtm:

Agreed the old test case was wrong.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38971#-:-LkPudgt0O0tJHRsciCM:b-9rr1lz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany and @yuzefovich)

**Pull request merged**
