### PR TITLE
scbuildstmt: ALTER PK drops rowid column when possible

### LINKED ISSUE #80149: sql: drop rowid column when ADD PRIMARY KEY overwrites the hidden rowid column
Today, ADD PRIMARY KEY will not drop the `rowid` column if it was the default.

We should DROP this column if:
* ADD PRIMARY KEY is used
* rowid is the non-visible hidden column

There was an attempt to do this in https://github.com/cockroachdb/cockroach/pull/78476, but we has bugs. We anticipate doing this in the new schema changer. 

[Slack discussion](https://cockroachlabs.slack.com/archives/C0168LW5THS/p1648518834672859)

Jira issue: CRDB-15832

### PR DESCRIPTION
**Pull request by postamar**
This commit improves the ALTER TABLE ... ALTER PRIMARY KEY ...
implementation in the declarative schema changer by also having it drop
the hidden rowid column when possible.

This required introducing a transient public index which includes rowid
as a storing column. This transient index is then swapped out with
the definitive primary index which does not include rowid at all. This
commit adds a rule to ensure that the second swapping takes place only
after the original primary index, in which rowid was the PK, has been
completely removed. Otherwise, we run into some nasty issues when faced
with concurrent writes.

Fixes #80149.

Release note (sql change): When performed by the declarative schema
changer (as is the case by default) the ALTER PRIMARY KEY statement
now also drops the rowid column when no references are held to it
anywhere. The rowid column is a hidden column which is implicitly added
and serves as primary key on any table which is created without
explicitly specifying a primary key.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 6 of 6 files at r3, 128 of 128 files at r4, 2 of 2 files at r5, 262 of 262 files at r6, 43 of 43 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86071#-:-N9Jbi3n-x8fvjsQ2EUS:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go` line 94 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86071#-N9JaoJ5DprEDNgyln6T:-N9JaoJ5DprEDNgyln6U:bz5iqo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d08e60682f7250b2edd4ecdea1a413bd79c118/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go#L94)):*
> ```Go
> 				canBeDropped = false
> 			case *scpb.SecondaryIndex:
> 				// TODO(postamar): support dropping rowid in the presence of secondary
> ```

This ends up mattering less because we don't handle `ALTER PRIMARY KEY` if there are any secondary indexes: https://github.com/cockroachdb/cockroach/blob/6a6dbb212470906bdd0536937dd5d0777ffc94e4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go#L321-L324



_Code quote:_
```Go
				// TODO(postamar): support dropping rowid in the presence of secondary
				// indexes if the column is only present in key suffixes.
```

**Comment by otan** [comment]
do i need to do anything to make this work? trying this on master...

```
demo@127.0.0.1:26257/defaultdb> create table load_table (id int not null, t text);
CREATE TABLE


Time: 12ms total (execution 11ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> alter table load_table add primary key (id);
ALTER TABLE


Time: 120ms total (execution 120ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> show create table load_table;
  table_name |                      create_statement
-------------+--------------------------------------------------------------
  load_table | CREATE TABLE public.load_table (
             |     id INT8 NOT NULL,
             |     t STRING NULL,
             |     rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
             |     CONSTRAINT load_table_pkey PRIMARY KEY (id ASC)
             | )
(1 row)
```

**Comment by ajwerner** [comment]
We didn't handle that syntax, just `ALTER PRIMARY KEY`, but it's easy, give me a few.

**Comment by ajwerner** [comment]
@otan this is what you're looking for: https://github.com/cockroachdb/cockroach/pull/86195

**Pull request merged**
