### PR TITLE
roachtest: stats exporter

### LINKED ISSUE #125381: drtprod: implement drt prod in golang rather than shell for better meintenance
Currently, drtprod is a shell script as scripts/drtprod. The script has the logic to do lot of different operations. As we keep adding more commands to the same script, it will grow and will become unmanageable. So, we can move the code to be a golang code similar to roachprod and make it more manageable and navigable.

Jira issue: CRDB-39422

### PR DESCRIPTION
**Pull request by nameisbhaskar**
This implements the stats-exporter that enables us to emit the stats in openmetrics format. The openmetrics exported is enabled based on a roachtest flag.

Fixes: #125381
Epic: None

### CODE REVIEW

**Comment by nameisbhaskar** [comment]
Thanks @sambhav-jain-16 ! I have addressed your comment.

**Comment by sambhav-jain-16** [comment]
@nameisbhaskar There are some CI errors. We can merge after fixing those.

**Comment by nameisbhaskar** [comment]
The lines of code are more because this  has refactoring of the library code, which requires changes across a lot of files.

**Review by sambhav-jain-16 — APPROVED** [review]
LGTM
Thanks for the changes @nameisbhaskar

**Comment by nameisbhaskar** [comment]
Thanks @sambhav-jain-16 for reviewing the changes

**Comment by nameisbhaskar** [comment]
bors r=@sambhav-jain-16

**Pull request merged**
