### PR TITLE
kvserver,storage: pass Server's ExternalStorage factory to pebble

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107298#-:-N_qDKyy3LwRQh9O5rCl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by dt** [comment]
TFTR!

bors r+

**Comment by RaduBerinde** [comment]
Sorry, you'll need to rebase - `SharedStorage` became `RemoteStorage`.

**Pull request merged**
