### PR TITLE
server/drain: shut down SQL subsystems gracefully before releasing table leases

### PR DESCRIPTION
**Pull request by knz**
Needed for #99941 and #99958.
Epic: CRDB-23559

See individual commits for details.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100476)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson, @miretskiy, and @rytaft)

___
*[`pkg/server/drain.go` line 359 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100476#-NS6UrEvYjkPjCqmnHYM-r4-359:-NS6Wyld1soF6l_DGKZ4:bjclz7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3df5f7379251ca04c832667782ccbe047bd38/pkg/server/drain.go#L359)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we need this to happen after the above step?
</blockquote></details>

How so? I figured that if we mark the registry as draining _before_ we wait for SQL clients to disconnect, we create the risk that one of these sessions will issue a BACKUP or some other job-based statement before it disconnects, and encounter a job error as a result (that the registry is now unavailable). Do you need a comment here to explain that?

**Comment by miretskiy** [comment]
>

**Comment by knz** [comment]
huh why did you close it?

**Comment by miretskiy** [comment]
> How so? I figured that if we mark the registry as draining _before_ we wait for SQL clients to disconnect, we create the risk that one of these sessions will issue a BACKUP or some other job-based statement before it disconnects, and encounter a job error as a result (that the registry is now unavailable). Do you need a comment here to explain that?

Just curious.  The whole shutdown is a bit of a "dance"... I was working on some other code, and wanted to get as much 
"notification" as possible when node starts draining, so moving this removes that time.
On the other hand, this dance is pretty brittle, and sort of doesn't provide any guarantees anyway (guarantees in a sense
that the caller may want to do some cleanup work before connections/sessions are cancelled.

> huh why did you close it?

I have NO idea how that happen.  Apologies.  I guess I was typing reply, and hit tab or something to change focus...

**Review by knz — COMMENTED** [review]
> I was working on some other code, and wanted to get as much
> "notification" as possible when node starts draining, so moving this removes that time.

If we find there is a benefit to notifying various subsystems when a drain is *starting* (as opposed to the hard deadline of it completing), we could also build that. It's out of scope of this PR but I think it'd be an interesting project.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100476#-:-NS6Yu0Q3UqvaPEKsMWJ:bvswmql)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson, @miretskiy, and @rytaft)

**Comment by knz** [comment]
@JeffSwenson i have added the extra logging and test knob in a last commit as we discussed.

**Review by jeffswenson — APPROVED** [review]
LGTM

**Review by rytaft — APPROVED** [review]
SQL Queries changes LGTM

> Reviewed 3 of 3 files at r2, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100476#-:-NS6f6SG06F4cZUKxsJz:btii536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @miretskiy)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100476#-NS6eUgU0rATocG1wlKV):*
These changes look good. Do you have any explicit tests that this is working?
___
*[`pkg/sql/stats/automatic_stats.go` line 814 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100476#-NS6djjSEqHAwJ4VGKrq:-NS6djjSEqHAwJ4VGKrr:b-4pj2kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a64821ec998c768729f85f08e0c6e26ce4dc6/pkg/sql/stats/automatic_stats.go#L814)):*
> ```Go
> 				// helps avoiding log spam.
> 				err = errors.New("server is shutting down")
> 			}
> ```

If I understand correctly how this works, one of these cases will be chosen at random if all are ready. Should we bias selection of the latter two cases to avoid the log spam?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100476)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @rytaft)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100476#-NS6eUgU0rATocG1wlKV):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These changes look good. Do you have any explicit tests that this is working?
</blockquote></details>

Will add those as part of #100436 which will exercise this code path.
___
*[`pkg/server/drain.go` line 359 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100476#-NS6UrEvYjkPjCqmnHYM-r4-359:-NS6gxsYDKtcb7vJ1uF6:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3df5f7379251ca04c832667782ccbe047bd38/pkg/server/drain.go#L359)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

How so? I figured that if we mark the registry as draining _before_ we wait for SQL clients to disconnect, we create the risk that one of these sessions will issue a BACKUP or some other job-based statement before it disconnects, and encounter a job error as a result (that the registry is now unavailable). Do you need a comment here to explain that?
</blockquote></details>

Added a comment.
___
*[`pkg/sql/stats/automatic_stats.go` line 814 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100476#-NS6djjSEqHAwJ4VGKrq:-NS6hBiEAEy6ikCqk3HL:bm1uw2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a64821ec998c768729f85f08e0c6e26ce4dc6/pkg/sql/stats/automatic_stats.go#L814)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

If I understand correctly how this works, one of these cases will be chosen at random if all are ready. Should we bias selection of the latter two cases to avoid the log spam?
</blockquote></details>

As discussed in #100482  it is actually undesirable to fail to queue the mutation during a server shutdown. So probably we benefit from the extra warning in that case.

**Comment by knz** [comment]
bors r=JeffSwenson,rytaft

**Pull request merged**
