### PR TITLE
sql: introduce ImmutableTableDescriptor struct

### PR DESCRIPTION
**Pull request by eriktrinh**
Create new ImmutableTableDescriptor struct which embeds a table schema
and increase usage of it. The ImmutableTableDescriptor will also contain
various data structures which will make the CRUD code path cleaner and
also improve lookup times for table schema elements (for example: col ID
to ordinal index map, compute exprs, col ID/name to descriptors).

Related to #22275.

### CODE REVIEW

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
You want to add a comment like:

The ImmutableTableDescriptor besides holding a TableDescriptor will also house various data-structures that will make the CRUD operation code paths cleaner and faster. For example: a number of functions in sqlbase/structured.go like sqlbase.FindColumnByID() can benefit from memoization. 

to better motivate this change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-:-LSKyC4N9ORh1zqMXJK3:beg1ur2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/load.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-LSKywTx0943eJzxMEIv:-LSKywTx0943eJzxMEIw:b-cup8ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b873712193d8f1be655b003f2367d328ee483f9/pkg/ccl/importccl/load.go#L104)):*
> ```Go
> 	var defaultExprs []tree.TypedExpr
> 	var cols []sqlbase.ColumnDescriptor
> 	var tableDesc *sqlbase.ImmutableTableDescriptor
> ```

Do we need to change the type to ImmutableTableDescriptor in load.go?
___
*[pkg/sql/lease.go, line 1473 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-LSL0BeX1y3X3dyXW6hb:-LSL0BeX1y3X3dyXW6hc:b-ue3ke7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b873712193d8f1be655b003f2367d328ee483f9/pkg/sql/lease.go#L1473)):*
> ```Go
> 			return nil, hlc.Timestamp{}, err
> 		}
> 		if !nameMatchesTable(table.TableDesc(), dbID, tableName) {
> ```

might as well have this function take an ImmutableTableDescriptor
___
*[pkg/sql/resolver.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-LSL1iueCCijZnf7mWvS:-LSL1iueCCijZnf7mWvT:bmbena7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b873712193d8f1be655b003f2367d328ee483f9/pkg/sql/resolver.go#L196)):*
> ```Go
> func (p *planner) ResolveUncachedTableDescriptor(
> 	ctx context.Context, tn *ObjectName, required bool, requiredType requiredType,
> ) (_ *UncachedTableDescriptor, err error) {
> ```

We should get rid of this UncachedTableDescriptor nonsense in another PR.
___
*[pkg/sql/table.go, line 370 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-LSL2JCg3qEyFaCNztKH:-LSL2JCg3qEyFaCNztKI:blbem7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b873712193d8f1be655b003f2367d328ee483f9/pkg/sql/table.go#L370)):*
> ```Go
> 
> 	if flags.avoidCached || testDisableTableLeases {
> 		table, err := sqlbase.GetTableDescFromID(ctx, txn, tableID)
> ```

We will eventually have to make the change that makes GetTableDescFromID() return an immutable type. But that is for another day.
___
*[pkg/sql/sqlbase/structured.go, line 2547 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-LSL2unREaUr1dMCXHuK:-LSL2unREaUr1dMCXHuL:byv7sub) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b873712193d8f1be655b003f2367d328ee483f9/pkg/sql/sqlbase/structured.go#L2547)):*
> ```Go
> func (desc *TableDescriptor) TableDesc() *TableDescriptor {
> 	return desc
> }
> ```

Can we get rid of this in this PR?

**Review by vivekmenezes — COMMENTED** [review]
This is a great change. While there is more work to do especially given that the code calls TableDesc() a  lot to reach into the underlying table descriptor, but I can see how you can't attack everything in one chunk!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-:-LSL34OJ6lR_ug2RusGq:bkv3wf0)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by vivekmenezes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-:-LSL3_2uAAJbDKqjhCEB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by RaduBerinde** [comment]
I believe that the opt_catalog.go code can (and should) be changed to use `ImmutableTableDescriptor`.

**Comment by vivekmenezes** [comment]
Feel free to merge when you can and keep working on this in future PRs.

**Review by eriktrinh — COMMENTED** [review]
> I believe that the opt_catalog.go code can (and should) be changed to use ImmutableTableDescriptor.

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-:-LSLWgalD5LZC2M7e3b8:b-po76jl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/importccl/load.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-LSKywTx0943eJzxMEIv:-LSLIYsm6u_dwHOIzyRQ:b-pbq41m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b873712193d8f1be655b003f2367d328ee483f9/pkg/ccl/importccl/load.go#L104)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Do we need to change the type to ImmutableTableDescriptor in load.go?
</blockquote></details>

Yes, this file uses mutation code for inserting rows into the created table.
___
*[pkg/sql/lease.go, line 1473 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-LSL0BeX1y3X3dyXW6hb:-LSLLW4zDH2ah2cvqYQ3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b873712193d8f1be655b003f2367d328ee483f9/pkg/sql/lease.go#L1473)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

might as well have this function take an ImmutableTableDescriptor
</blockquote></details>

Done.
___
*[pkg/sql/resolver.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-LSL1iueCCijZnf7mWvS:-LSLOgXH-VuCXNej62Vm:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b873712193d8f1be655b003f2367d328ee483f9/pkg/sql/resolver.go#L196)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

We should get rid of this UncachedTableDescriptor nonsense in another PR.
</blockquote></details>

Ack
___
*[pkg/sql/table.go, line 370 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-LSL2JCg3qEyFaCNztKH:-LSLLj0k1ww0qpt1kwYs:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b873712193d8f1be655b003f2367d328ee483f9/pkg/sql/table.go#L370)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

We will eventually have to make the change that makes GetTableDescFromID() return an immutable type. But that is for another day.
</blockquote></details>

Ack
___
*[pkg/sql/sqlbase/structured.go, line 2547 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32603#-LSL2unREaUr1dMCXHuK:-LSLMLuS0y5-uVcNdDoJ:b-9f087b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b873712193d8f1be655b003f2367d328ee483f9/pkg/sql/sqlbase/structured.go#L2547)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Can we get rid of this in this PR?
</blockquote></details>

Yep, done.

**Comment by RaduBerinde** [comment]
>> I believe that the opt_catalog.go code can (and should) be changed to use ImmutableTableDescriptor.

> Done.

Great! Thanks!!

**Comment by eriktrinh** [comment]
TFTR!

bors r+

**Pull request merged**
