### PR TITLE
*: switch from npm to yarn

### PR DESCRIPTION
**Pull request by tamird**
Yarn is faster, and doesn't require constantly nuking the .node_modules
directory like npm does. It also has Facebook's weight behind it, so it
seems like a safe bet in terms of ongoing support and maintenance.

See https://dev.to/bugsnag/replacing-npm-with-yarn for some compelling
performance numbers.

Also updates the builder to go1.7.3 and Terraform to 0.7.7 while I'm
cutting a new image.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10178)

### CODE REVIEW

**Comment by mrtracy** [comment]
LGTM, if it works.  Do we need to do anything about the existing `npm.installed` file? You removed it from ignore, but nothing here appears to delete that file, it could be confusing for people who have previously built the UI.

**Comment by tamird** [comment]
I'll circulate something on the forum regarding npm.installed.

**Comment by maxlang** [comment]
@tamird 

When I ran make after rebasing a branch I got.

```sh
➜  ui git:(maxlang/ui-registration-server) make
make: yarn: Command not found
yarn install
/bin/bash: yarn: command not found
make: *** [yarn.installed] Error 127
```

Should we add `npm install yarn` to the make file?

**Comment by maxlang** [comment]
Spoke to @tamird. Agreed the place for this is in the `README`.

**Comment by tamird** [comment]
I think we should not; attempting to manage dependencies with both npm and
yarn won't work. Perhaps the readme should include a link to
https://yarnpkg.com/en/docs/install.

**Pull request merged**
