### PR TITLE
exec: add sorter

### LINKED ISSUE #32101: exec: implement simple, in-memory sorter
Implement an `exec.Operator` for a simple in-memory global sort. Use Go's builtin sort library to do the hard work. The operator should operate on a single, int64 column to start, and can be extended later.

### PR DESCRIPTION
**Pull request by jordanlewis**
Builds on the commit in #32394.

Closes #32101.

The sorts are now fully templated, including the underlying quicksort implementation, which was copied from the Go source tree so it can be templated like the rest of the exec code. That provided a pretty good (almost 2x) speedup on top of the first implementation.

```
BenchmarkSort/rows=2048/cols=1-8                  100000             19086 ns/op         858.39 MB/s
BenchmarkSort/rows=2048/cols=2-8                   30000             43096 ns/op         760.33 MB/s
BenchmarkSort/rows=2048/cols=4-8                   20000             82746 ns/op         792.01 MB/s
BenchmarkSort/rows=16384/cols=1-8                  10000            169373 ns/op         773.86 MB/s
BenchmarkSort/rows=16384/cols=2-8                   3000            407879 ns/op         642.70 MB/s
BenchmarkSort/rows=16384/cols=4-8                   2000            816472 ns/op         642.14 MB/s
BenchmarkSort/rows=262144/cols=1-8                   500           2729214 ns/op         768.41 MB/s
BenchmarkSort/rows=262144/cols=2-8                   200           6020773 ns/op         696.64 MB/s
BenchmarkSort/rows=262144/cols=4-8                   100          12384021 ns/op         677.37 MB/s
```

The throughput can undoubtedly be improved by using a sort implementation that's more data dependent. One idea that I've seen repeated in the literature is using sorter networks on small chunks of the input data, then merging the chunks, instead of using a general purpose sort. Sorter networks are deterministic orders of compares and swaps that might be more efficient than a general-purpose sort because they allow the CPU more determinism.

But this should be fine for now. On an ORDER BY, this implementation already is about 2x faster than on master.

The strategy is as follows. First, globally sort the first column,
keeping an ordinal column that is swapped as the first column is. Then,
for each subsequent column, perform the following steps:

1. find all partitions in the most recently sorted column, ORing them
   with the previous partition list if there is one
2. reorder the column to sort based on the ordinal order column
3. for each partition in the partition list, sort the column, updating
   the ordinal order column

This strategy seems to be pretty effective. The slowest thing about it
is still buffering the input data.

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32673)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/sort_test.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LSRZvyy0KAjE-RnWZ5x:-LSRZvyy0KAjE-RnWZ5y:btxz19e) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b3186722785f16f519d2a05a44bce17ed25bbb/pkg/sql/exec/sort_test.go#L80)):*
> ```Go
> 		runTests(t, []tuples{tc.tuples}, []types.T{}, func(t *testing.T, input []Operator) {
> 			sortSpec := sortSpec{
> 				sortCol:    0,
> ```

Might be interesting to have the sortCol be part of the test spec to mess around with this variable but up to you.
___
*[pkg/sql/exec/sort_tmpl.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LSQkiko1YL3eITvmE9K:-LSQkiko1YL3eITvmE9L:bwitumt) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b3186722785f16f519d2a05a44bce17ed25bbb/pkg/sql/exec/sort_tmpl.go#L149)):*
> ```Go
> 				p.output.ColVec(j).Copy(p.values[j], p.emitted, newEmitted, p.spec.inputTypes[j])
> 			} else {
> 				p.output.ColVec(j).CopyWithSelInt64(p.values[j], p.order[p.emitted:], p.output.Length(), p.spec.inputTypes[j])
> ```

I talked about this with Arjun, and I think it might be a good idea to separate sorting a single column and using that ordering to reorder the other columns in something like your distinct finalizer. This would probably make it easier to do a multi-column sort by chaining multiple single-column sort operators that sort with the constraint of the previous sorter's output. Then you'd have a final stage that looks at the selection vector and outputs the final order. Haven't given this much thought so it might be wrong, but I feel like the separation of these two stages would be a good thing. What do you think?
___
*[pkg/sql/exec/sort_tmpl.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LSR_Ni-EbHExzPJSRi6:-LSR_Ni-EbHExzPJSRi7:bp14nsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/7caa056d160e713804ea622bfb07d75a87187fa6/pkg/sql/exec/sort_tmpl.go#L1)):*
> ```Go
> // Copyright 2009 The Go Authors. All rights reserved.
> ```

Hmm.. how do these copyright things work? Is it fine to put our own copyright here?
___
*[pkg/sql/exec/sort_tmpl.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LSR_kavBoQB0EGFRYfB:-LSR_kavBoQB0EGFRYfC:buppt73) ([raw file](https://github.com/cockroachdb/cockroach/blob/7caa056d160e713804ea622bfb07d75a87187fa6/pkg/sql/exec/sort_tmpl.go#L203)):*
> ```Go
> 
> 	n := p.Len()
> 	p.quickSort(0, n, maxDepth(n))
> ```

What should I be paying attention to in this file?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32673)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/sort_test.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LSRZvyy0KAjE-RnWZ5x:-LSSyVNt5BKYvWTnm5KR:b954xad) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b3186722785f16f519d2a05a44bce17ed25bbb/pkg/sql/exec/sort_test.go#L80)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Might be interesting to have the sortCol be part of the test spec to mess around with this variable but up to you.
</blockquote></details>

Yeah, just seems like since the tests don't vary it for now there's no point in adding that line to all test cases.
___
*[pkg/sql/exec/sort_tmpl.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LSQkiko1YL3eITvmE9K:-LSSyqPA2uHQOHONW4k3:b-7bip49) ([raw file](https://github.com/cockroachdb/cockroach/blob/27b3186722785f16f519d2a05a44bce17ed25bbb/pkg/sql/exec/sort_tmpl.go#L149)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I talked about this with Arjun, and I think it might be a good idea to separate sorting a single column and using that ordering to reorder the other columns in something like your distinct finalizer. This would probably make it easier to do a multi-column sort by chaining multiple single-column sort operators that sort with the constraint of the previous sorter's output. Then you'd have a final stage that looks at the selection vector and outputs the final order. Haven't given this much thought so it might be wrong, but I feel like the separation of these two stages would be a good thing. What do you think?
</blockquote></details>

Yes, I totally agree. I'll restructure this as suggested.
___
*[pkg/sql/exec/sort_tmpl.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LSR_Ni-EbHExzPJSRi6:-LSSya1E0yt-6nTj7ukw:b-fsh7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7caa056d160e713804ea622bfb07d75a87187fa6/pkg/sql/exec/sort_tmpl.go#L1)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm.. how do these copyright things work? Is it fine to put our own copyright here?
</blockquote></details>

That's what we do in pkg/sql/sqlbase/sort.go, so I figure it should be okay. But I decided I'd just move the quicksort impl to a different template and generated file.
___
*[pkg/sql/exec/sort_tmpl.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LSR_kavBoQB0EGFRYfB:-LSSz2zFDke0HGEd82PI:b-vxehdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7caa056d160e713804ea622bfb07d75a87187fa6/pkg/sql/exec/sort_tmpl.go#L203)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What should I be paying attention to in this file?
</blockquote></details>

Everything. I moved the quicksort implementation to a different file that can be ignored.

**Comment by jordanlewis** [comment]
As discussed, I updated this to perform multi-column ascending sorts as the decomposition you were discussing wasn't particularly obvious without actually trying to implement the whole thing.

**Comment by jordanlewis** [comment]
I added support for descending sorts as the final commit.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, 4 of 4 files at r5, 3 of 3 files at r6, 9 of 9 files at r7, 4 of 4 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, 7 of 7 files at r11, 6 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32673)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/bool_vec_to_sel.go, line 72 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTMblXuCZ2DsRdBWrUe:-LTMblXuCZ2DsRdBWrUf:b-85bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/bool_vec_to_sel.go#L72)):*
> ```Go
> 		// Zero our output column for next time.
> 		for i := range p.outputCol {
> 			p.outputCol[i] = false
> ```

Why did this change?
___
*[pkg/sql/exec/sort.go, line 43 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNg1ec3_jKn7SF2WTc:-LTNg1ec3_jKn7SF2WTd:b-43ul89) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/sort.go#L43)):*
> ```Go
> 			}
> 		}
> 		colWasSorted[idx] = true
> ```

Why is this being set here?
___
*[pkg/sql/exec/sort.go, line 226 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNar-e6ojmY74MuTeb:-LTNar-e6ojmY74MuTec:b-643ebr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/sort.go#L226)):*
> ```Go
> 	// 2 b
> 
> 	tmp := make([]uint64, nTuples)
> ```

Is there a more descriptive name you could use here and in the interface definition?
___
*[pkg/sql/exec/sort.go, line 234 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNWpH1-PraXiqRxiQG:-LTNWpH1-PraXiqRxiQH:b-ypbqca) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/sort.go#L234)):*
> ```Go
> 		// produces a distinct vector (a boolean vector that has true in each
> 		// position that is different from the last position).
> 		p.partitioners[i].partition(p.values[p.sortColIdxs[i]], outputCol, nTuples)
> ```

Could you have partition return a selection vector directly to avoid the step of converting to a selection vector from a distinct output?
___
*[pkg/sql/exec/sort_tmpl.go, line 133 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNYlOBAosOps8h-u41:-LTNYlOBAosOps8h-u42:b-esd998) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/sort_tmpl.go#L133)):*
> ```Go
> 		s.sortCol = sortCol[partitionStart:partitionEnd]
> 		n := int(partitionEnd - partitionStart)
> 		s.quickSort(0, n, maxDepth(n))
> ```

Should this 0 be `partitionStart`?
___
*[pkg/sql/exec/sort_tmpl.go, line 75 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNliJsCiLLW46dHapt:-LTNliJsCiLLW46dHapu:btoa0ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/480b1e4302d0ac0faa52eca32186ca926e73a96f/pkg/sql/exec/sort_tmpl.go#L75)):*
> ```Go
> 		case _DIR_ENUM:
> 			return &sort_TYPE_DIROp{}, nil
> 			// {{end}}
> ```

Indentation got you here ;)

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32673)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/sort.go, line 43 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNg1ec3_jKn7SF2WTc:-LTOEyz10vHBC5_NEoSh:bn1b2di) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/sort.go#L43)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is this being set here?
</blockquote></details>

This needs more comments. `colWasSorted` is an array that indicates that, by the end of the complete sorting process, the given column has already been ordered by the `order` index and can be directly written to the output batch without reordering again. Columns that aren't explicit sort columns don't have this property and must be reordered by tthe end.

I've added more comments - thanks for noticing that this is confusing.
___
*[pkg/sql/exec/sort.go, line 226 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNar-e6ojmY74MuTeb:-LTOFk3a0ECsFo3Iyrjs:b-3xfyzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/sort.go#L226)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is there a more descriptive name you could use here and in the interface definition?
</blockquote></details>

Improved the name and interface - it's just working space, and it can be passed in just once at `init` time.
___
*[pkg/sql/exec/sort.go, line 234 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNWpH1-PraXiqRxiQG:-LTOFqLj62GwbVWWYtOJ:balvij7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/sort.go#L234)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you have partition return a selection vector directly to avoid the step of converting to a selection vector from a distinct output?
</blockquote></details>

No, because the partitioner has to build partitions over multiple columns the way distinct does. It's more efficient to keep that boolean slice around. Otherwise, the selection vector will have to be modified in place as new partitions are added to the list.
___
*[pkg/sql/exec/sort_tmpl.go, line 133 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNYlOBAosOps8h-u41:-LTOGKXUC8X6hoC0QL1d:b751dk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/sort_tmpl.go#L133)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should this 0 be `partitionStart`?
</blockquote></details>

No, `s` was already modified to start at `partitionStart` - so from the perspective of the sorter, we should start at index 0.
___
*[pkg/sql/exec/sort_tmpl.go, line 75 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNliJsCiLLW46dHapt:-LTOGGGG3RDq95Aqzqls:b-9rrsi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/480b1e4302d0ac0faa52eca32186ca926e73a96f/pkg/sql/exec/sort_tmpl.go#L75)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Indentation got you here ;)
</blockquote></details>

Nooooo. Fixed.

**Review by asubiotto — APPROVED** [review]
> Reviewed 12 of 12 files at r13, 4 of 4 files at r14, 3 of 3 files at r15, 1 of 1 files at r16, 7 of 7 files at r17, 7 of 7 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32673)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/distinct_tmpl.go, line 230 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTSsBzk93WAEyYHWHtX:-LTSsBzk93WAEyYHWHtY:b-v0pfnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b4674dd0d0cc088e91c230eb6c1f159fcfe9cb/pkg/sql/exec/distinct_tmpl.go#L230)):*
> ```Go
> 
> func (p partitioner_TYPE) partition(colVec ColVec, outputCol []bool, n uint64) {
> 	col := colVec._TemplateType()
> ```

Makes me wonder if we could have templated helper functions that are expanded. e.g. this could be used in sorted distinct as well as partition.
___
*[pkg/sql/exec/sort.go, line 43 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNg1ec3_jKn7SF2WTc:-LTSvTuuAJk3VPHmdDyL:b-mrbhy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/sort.go#L43)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This needs more comments. `colWasSorted` is an array that indicates that, by the end of the complete sorting process, the given column has already been ordered by the `order` index and can be directly written to the output batch without reordering again. Columns that aren't explicit sort columns don't have this property and must be reordered by tthe end.

I've added more comments - thanks for noticing that this is confusing.
</blockquote></details>

Ah got it, maybe a name like `isOrderingCol` would make it clearer?

**Review by jordanlewis — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-:-LTT2uyKERjN3dltQQxC:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/distinct_tmpl.go, line 230 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTSsBzk93WAEyYHWHtX:-LTT2qzuBm48rk8bIAos:b-8o4ei3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b4674dd0d0cc088e91c230eb6c1f159fcfe9cb/pkg/sql/exec/distinct_tmpl.go#L230)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Makes me wonder if we could have templated helper functions that are expanded. e.g. this could be used in sorted distinct as well as partition.
</blockquote></details>

Yeah. I think soon we'll have something that can be used like this.
___
*[pkg/sql/exec/sort.go, line 43 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32673#-LTNg1ec3_jKn7SF2WTc:-LTT2twQASlHJ9fjB-Ng:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca446a6e20e1b7aaaac96e1a0fb7c605ce19c671/pkg/sql/exec/sort.go#L43)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Ah got it, maybe a name like `isOrderingCol` would make it clearer?
</blockquote></details>

Done.

**Pull request merged**
