### PR TITLE
opt: fix panic in GenerateLookupJoin

### LINKED ISSUE #59738: opt: GenerateLookupJoin panics on table with computed columns
Here's a reproduction:

```
exec-ddl
CREATE TABLE ab (a INT, b INT AS (a + 10) STORED, INDEX (a))
----

exec-ddl
CREATE TABLE cd (c INT, d INT)
----

opt
SELECT * FROM cd LEFT JOIN ab ON a = c AND d > 5
----
```

The error:

```
--- FAIL: TestNormRules (0.00s)
    --- FAIL: TestNormRules/__test (0.00s)
        opt_tester.go:506: testdata/rules/__test:42: runtime error: index out of range [-3]
            (1) assertion failure
            Wraps: (2) attached stack trace
              -- stack trace:
              | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize.func1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:205
              | runtime.gopanic
              |         /usr/local/opt/go/libexec/src/runtime/panic.go:969
              | runtime.goPanicIndex
              |         /usr/local/opt/go/libexec/src/runtime/panic.go:88
              | github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/testcat.(*Table).Column
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/testcat/test_catalog.go:656
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).findConstantFilterCols
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/select_funcs.go:417
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).computedColFilters
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/general_funcs.go:242
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).GenerateLookupJoins
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:227
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreLeftJoin
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.og.go:856
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreGroupMember
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.og.go:26
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreGroup
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.go:182
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroup
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:464
              | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:225
              | github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester.(*OptTester).optimizeExpr
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester/opt_tester.go:1645
              | github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester.(*OptTester).Optimize
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester/opt_tester.go:981
              | github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester.(*OptTester).RunCommand
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/opttester/opt_tester.go:504
              | github.com/cockroachdb/cockroach/pkg/sql/opt/norm_test.TestNormRules.func1.1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/norm_test.go:45
              | github.com/cockroachdb/datadriven.runDirective.func1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:321
              | github.com/cockroachdb/datadriven.runDirective
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:326
              | github.com/cockroachdb/datadriven.runDirectiveOrSubTest
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:195
              | github.com/cockroachdb/datadriven.runTestInternal
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:168
              | github.com/cockroachdb/datadriven.RunTest
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:136
              | github.com/cockroachdb/cockroach/pkg/sql/opt/norm_test.TestNormRules.func1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/norm_test.go:42
              | github.com/cockroachdb/datadriven.Walk
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:413
              | github.com/cockroachdb/datadriven.Walk.func1
              |         /Users/marcus/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/datadriven/datadriven.go:426
              | testing.tRunner
              |         /usr/local/opt/go/libexec/src/testing/testing.go:1123
              | runtime.goexit
              |         /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1374
            Wraps: (3) runtime error: index out of range [-3]
              | -- cause hidden behind barrier
              | runtime error: index out of range [-3]
              | (1) runtime error: index out of range [-3]
              | Error types: (1) runtime.boundsError
            Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *barriers.barrierError
```

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: fix panic in GenerateLookupJoin

In #57690 a new code path was introduced from `findConstantFilterCols`
from `GenerateLookupJoins`. This new code path made it possible for the
filters passed to `findConstantFilterCols` to contain columns that are
not part of the given table. This violated the assumption that the
filter only contains columns in the given table and caused a panic. This
commit fixes the issue by neglecting constant filters for columns not in
the given table.

Fixes #59738

Release note (bug fix): A bug has been fixed that caused errors when
joining two tables when one of the tables had a computed column. This
bug was present since version 21.1.0-alpha.2 and not present in any
production releases.

#### opt: move findConstantFilterCols to general_funcs.go

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59741#-:-MS_lxWTE6wI1MzqAjrz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59741#-:-MScjs08B6v6Acw8qUtg:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/testdata/rules/join, line 3178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59741#-MScim5d7WnAQGU-3FI8:-MScim5d7WnAQGU-3FI9:b-p2ssu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/69ec0853e0d513694c637a68a13c016132e07ae6/pkg/sql/opt/xform/testdata/rules/join#L3178)):*
> ```
> 
> # Regression test for #59738. findConstantFilterCols should not panic when
> # it finds constant filters that are not in the scanned table.
> ```

[nit] this comment is a bit confusing. Instead of "scanned table", maybe say "index of the lookup join"?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59741)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/xform/testdata/rules/join, line 3178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59741#-MScim5d7WnAQGU-3FI8:-MSdgTXt7KUhao1hgkCe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69ec0853e0d513694c637a68a13c016132e07ae6/pkg/sql/opt/xform/testdata/rules/join#L3178)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] this comment is a bit confusing. Instead of "scanned table", maybe say "index of the lookup join"?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59741)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
