### PR TITLE
sql: make scanNode use MaxInt64 as limit value

### PR DESCRIPTION
**Pull request by ssbl**
This PR is an attempt at fixing #15947.

### CODE REVIEW

**Comment by knz** [comment]
Thank you so much for tackling this!
This looks good!

I think now you can be even slightly more ambitious and make the extra mile: 
- modify the row fetcher (`sqlbase/rowfetcher.go`) accordingly
  - in particular, ensure that the scaling `limitHint * int64(keysize)` does not overflow, and ignore the limit if an overflow would occur;
- update/simplify `distsqlrun/tablereader.go` accordingly;
- simplify `(*scanNode)limitHint()` accordingly;
- add a new logic test that looks at the output of`EXPLAIN SELECT ... FROM ... LIMIT 0` to verify that the plan is simplified.

---

Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16189#-:-KlOseFbkRls7N2PdW_R:bw51soo)*

**Comment by ssbl** [comment]
@knz I've added an overflow check similar to the one in `tablereader.go`. Should the row fetchers and table readers use MaxInt64 as well? It seems that `kvFetcher` also expects a non-zero limit value (`firstBatchLimit`) to indicate a limit.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16189#-:-KlRM1Lf07HznF4pcRH0:b-8vcnbe)*

**Comment by knz** [comment]
Yes I was suggesting that you perform the change throughout these locations, including kvFetcher.
Let me know if you think this is too complicated, perhaps I can help.

---

Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 188 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16189#-KlTx4bE7HCkh5VnrIiO:-KlTx4bE7HCkh5VnrIiP:b-8968zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a432b79b583e3fff15106433c536a7814a998442/pkg/sql/sqlbase/rowfetcher.go#L188)):*
> ```Go
> 		// The limitHint is a row limit, but each row could be made up of more
> 		// than one key.
> 		firstBatchLimit = limitHint * int64(rf.desc.KeysPerRow(rf.index.ID))
> ```

```go
kprSize := rf.desc.KeysPerRow(rf.index.ID)
if limitHint + 1 >= math.MaxInt64 / kprSize {
   // Overflow: keep the hint limited.
   firstBatchLimit = math.MaxInt64 - 1
} else {
   firstBatchLimit = limitHint * kprSize
}
// We need an extra key to make sure we form the last row.
firstBatchLimit++
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16189#-:-KlTxeE1bp297f_8MplU:b-6cpwpr)*

**Comment by knz** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 188 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16189#-KlTx4bE7HCkh5VnrIiO:-KlTy6EKkhktQ54oFhXF:b7zmmiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a432b79b583e3fff15106433c536a7814a998442/pkg/sql/sqlbase/rowfetcher.go#L188)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

```go
kprSize := rf.desc.KeysPerRow(rf.index.ID)
if limitHint + 1 >= math.MaxInt64 / kprSize {
   // Overflow: keep the hint limited.
   firstBatchLimit = math.MaxInt64 - 1
} else {
   firstBatchLimit = limitHint * kprSize
}
// We need an extra key to make sure we form the last row.
firstBatchLimit++
```
</blockquote></details>

Oops sorry I made a mistake in there :)
```go
kprSize := rf.desc.KeysPerRow(rf.index.ID)
if limitHint >= math.MaxInt64 / kprSize - 1 {
   // Overflow: keep the hint limited.
   firstBatchLimit = math.MaxInt64 - 1
} else {
   firstBatchLimit = limitHint * kprSize
}
// We need an extra key to make sure we form the last row.
firstBatchLimit++
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16189)*

**Comment by ssbl** [comment]
This latest commit adds the overflow check suggested earlier, and initializes tableReaders with a `limitHint` of MaxInt64. Tests fail with a scan error though; the limit we specify here is used to set the `MaxSpanRequestKeys` in the batch header (in the fetch function in `kvfetcher.go`). Since it's expected to be 0 if no limit is specified, maybe this is causing the tests to fail?

@knz Could use some help here.

---

Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16189#-:-KldY0TFRv-Ljimt0AHg:b-b1zo4r)*

**Comment by tschottdorf** [comment]
Reopening; I think this was closed accidentally.

**Comment by knz** [comment]
We have decided that the cleanup described in #15947 was not desirable any more and will thus not pursue this work further. However of course we are grateful for your effort and for forcing us to think about this doubly. Thank you again for your time and your contribution.

**Pull request closed without merging**
