### PR TITLE
schemachanger: support ALTER DATABASE .. CONFIGURE ZONE in DSC

### LINKED ISSUE #117574: Implement ALTER DATABASE ... CONFIGURE ZONE USING ... in declarative schema changer
This issue tracks our progress of supporting zone configs in declarative schema changer and let's concretize it into implementing `ALTER DATABASE ... CONFIGURE ZONE` stmt in declarative schema changer.

Epic: CRDB-31473

Jira issue: CRDB-35252

### PR DESCRIPTION
**Pull request by annrpom**
### scpb: Introduce DatabaseZoneConfig element
This commit introduces the DatabaseZoneConfig element that will become
relevant for supporting `ALTER DATABASE ... CONFIGURE ZONE` in DSC.

---

### schemachanger: add db zone config opgen rule
This patch adds an opgen rule for db zone configs
in the ADD direction, along with some interfaces
for zone config verification and retrieval.

---
### schemachanger: support DB zone config
This patch adds the functionality to configure
a zone configuration on a database.

Informs: https://github.com/cockroachdb/cockroach/issues/117574
Epic: CRDB-35252

Release note: None

Fixes: #117574

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 8 of 8 files at r2, 9 of 9 files at r3, 16 of 16 files at r4, 20 of 20 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121026)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 497 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-NziDTL_4fz-qbQFu4iV:-NziDTL_4fz-qbQFu4iW:bvb96im) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L497)):*
> ```Go
> ) (zone *zonepb.ZoneConfig, seqNum uint32, err error) {
> 	if keys.RootNamespaceID == uint32(targetID) {
> 		zc, err := b.ZoneConfigGetter().GetZoneConfig(b, targetID)
> ```

Think we need to go through decomposition / resolve? Otherwise, are we in trouble if schema changes stack within a txn?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 82 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-NziBEQ_A4RNqTv8mIaB:-NziBEQ_A4RNqTv8mIaC:b-ss3szs) ([raw file](https://github.com/cockroachdb/cockroach/blob/deba4e155d6a22bf24f2bbf979832a3d94fd2c63/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L82)):*
> ```Go
> 	// NodesStatusServer gives access to the NodesStatus service and is only
> 	// available when running as a system tenant.
> 	NodesStatusServer() *serverpb.OptionalNodesStatusServer
> ```

Nit: It feels like we should just pull in a narrower interface? WDYT?
___
*[`pkg/sql/schemachanger/scdeps/exec_deps.go` line 237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-NziCD443p7dr1AyXBnX:-NziCD443p7dr1AyXBnY:b-6fp7sk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d54fb1778381f79ac947ae0cd47115b7f70788c3/pkg/sql/schemachanger/scdeps/exec_deps.go#L237)):*
> ```Go
> 	var rawBytes []byte
> 	if oldZc != nil {
> 		rawBytes = oldZc.GetRawBytesInStorage()
> ```

Wait, shouldn't this be the raw bytes for the new zone config?

**Review by spilchen — CHANGES_REQUESTED** [review]
I'm reviewing this to better understand the DSC. Some of my comments are just questions about the code.

> Reviewed 5 of 5 files at r1, 8 of 8 files at r2, 9 of 9 files at r3, 16 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-:-O-I6HRF3t2pozbDyWyF:b-46g4s1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 48 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-HnUFa4bVWFeopiBi1:-O-HnUFa4bVWFeopiBi2:b-m1h5t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L48)):*
> ```Go
> 	}
> 
> 	// TODO(annie): implement complete support for CONFIGURE ZONE
> ```

Can you be more specific about what this TODO means? Does it mean we want to support CONFIGURE ZONE for things other than the database?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-Hgc1GCuTr495dJ-jd:-O-Hgc1H1Dzuj1Kp6KEX:b3e8dma) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L54)):*
> ```Go
> 	// Block from using YAML config unless we are discarding a YAML config.
> 	if n.YAMLConfig != nil && !n.Discard {
> 		panic(scerrors.NotImplementedErrorf(n, "YAML config is deprecated and not supported in DSC"))
> ```

Is DSC a term that a customer would know? I wonder if we should have a better error message that an end user may understand.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-HqDk9601ldth3A7MI:-O-HqDk9601ldth3A7MJ:b4cndjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L83)):*
> ```Go
> 		panic(err)
> 	}
> 	if elem.DatabaseID == 104 {
> ```

Is this intentional or something left over from test?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 96 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-Hj4mK2NAewznpC4vI:-O-Hj4mK2NAewznpC4vJ:bngxo2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L96)):*
> ```Go
> 	// For the system database, the user must be an admin. Otherwise, we
> 	// require CREATE or ZONECONFIG privilege on the database in question.
> 	reqNonAdminPrivs := []privilege.Kind{privilege.ZONECONFIG, privilege.CREATE}
> ```

nit: suggest moving this declaration down to when we need it. It's only needed in the error case, so make sense to declare right before returning the error
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 302 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-HqRK-BqtrX_SZuPcc:-O-HqRK-BqtrX_SZuPcd:bvac31x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L302)):*
> ```Go
> 	}
> 
> 	// TODO Guard against system tenant here
> ```

If we are missing guards, is it possible to do unauthorized modifications to the system tenant? Just trying to understand what happens if we don't address this right away.

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121026)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 48 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-HnUFa4bVWFeopiBi1:-O-b72Ea9SGTyj7eBeLV:b-p3xwiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L48)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Can you be more specific about what this TODO means? Does it mean we want to support CONFIGURE ZONE for things other than the database?
</blockquote></details>

done. yes! although getting database out in this PR gets a chunk of the work done -- the other PRs that i will stop hoarding (like #125786)

the list of objects we surpport configure zone on is: https://www.cockroachlabs.com/docs/stable/configure-replication-zones

i'll add a list in to be more verbose
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-Hgc1GCuTr495dJ-jd:-O-b7c5mCNDlWMGDO_qO:b135epu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L54)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is DSC a term that a customer would know? I wonder if we should have a better error message that an end user may understand.
</blockquote></details>

done. i think a similar comment was left on Bergin's comment on type PR -- i'll spell this out to "declarative schema changer" since we do actually document the declarative schema changer (https://www.cockroachlabs.com/docs/stable/online-schema-changes#declarative-schema-changer), but "DSC" is a bit less obvious
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-HqDk9601ldth3A7MI:-O-b9cp95ArM18D0hijs:b-2l4mkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L83)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is this intentional or something left over from test?
</blockquote></details>

done -- left over! thx for catching
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 96 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-Hj4mK2NAewznpC4vI:-O-bAs0y3VIQBySxqvO7:bt4ytbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L96)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: suggest moving this declaration down to when we need it. It's only needed in the error case, so make sense to declare right before returning the error
</blockquote></details>

done -- makes sense in terms of readability ('-')7
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 302 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-HqRK-BqtrX_SZuPcc:-O-bB-Vt0RAlb3O47sA-:b-p5q18u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L302)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

If we are missing guards, is it possible to do unauthorized modifications to the system tenant? Just trying to understand what happens if we don't address this right away.
</blockquote></details>

done. i'll freshen up this TODO -- for more context, we need to guard against non-system/secondary tenants setting zone configs on any system ranges (https://www.cockroachlabs.com/docs/stable/configure-replication-zones#create-a-replication-zone-for-a-system-range). this is inspired by https://github.com/cockroachdb/cockroach/blob/91024190faeb1462e559471bef42ce601fc9bbbd/pkg/sql/set_zone_config.go#L414-L425, but we don't allow anything other than configure zone on databases in this PR; so, we do not need to keep this in mind for now
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 497 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-NziDTL_4fz-qbQFu4iV:-O-bORvB8oB2jFEsB23N:b-jwdjql) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L497)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Think we need to go through decomposition / resolve? Otherwise, are we in trouble if schema changes stack within a txn?
</blockquote></details>

may i get an example/clarification of what you are talking about? does it mean for a situation like the following:
```
demo@127.0.0.1:26257/demoapp/movr> set use_declarative_schema_changer =          
                                -> unsafe_always;                                
SET

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> begin;                                        
BEGIN

Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr  OPEN> ALTER DATABASE annie CONFIGURE ZONE     
                                      -> USING num_replicas = 19;                
CONFIGURE ZONE 0

Time: 6ms total (execution 6ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr  OPEN> show zone configuration for database    
                                      -> annie;                                  
      target     |              raw_config_sql
-----------------+--------------------------------------------
  DATABASE annie | ALTER DATABASE annie CONFIGURE ZONE USING
                 |     range_min_bytes = 134217728,
                 |     range_max_bytes = 536870912,
                 |     gc.ttlseconds = 14400,
                 |     num_replicas = 19,
                 |     constraints = '[]',
                 |     lease_preferences = '[]'
(1 row)

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr  OPEN> ALTER DATABASE annie CONFIGURE ZONE     
                                      -> USING num_replicas = 18;                
CONFIGURE ZONE 0

Time: 5ms total (execution 4ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr  OPEN> show zone configuration for database    
                                      -> annie;                                  
      target     |              raw_config_sql
-----------------+--------------------------------------------
  DATABASE annie | ALTER DATABASE annie CONFIGURE ZONE USING
                 |     range_min_bytes = 134217728,
                 |     range_max_bytes = 536870912,
                 |     gc.ttlseconds = 14400,
                 |     num_replicas = 18,
                 |     constraints = '[]',
                 |     lease_preferences = '[]'
(1 row)

Time: 1ms total (execution 1ms / network 0ms)

-- just checking that we are indeed in dsc-land
demo@127.0.0.1:26257/demoapp/movr  OPEN> explain (ddl) ALTER DATABASE annie      
                                      -> CONFIGURE ZONE USING num_replicas = 18; 
                                                                                                                    info
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Schema change plan for ALTER DATABASE ‹annie› CONFIGURE ZONE USING ‹num_replicas› = ‹18›; following ALTER DATABASE ‹annie› CONFIGURE ZONE USING ‹num_replicas› = ‹19›; ALTER DATABASE ‹annie› CONFIGURE ZONE USING ‹num_replicas› = ‹18›;
   ├── StatementPhase
   │    └── Stage 1 of 1 in StatementPhase
   │         ├── 1 element transitioning toward PUBLIC
   │         │    └── ABSENT → PUBLIC DatabaseZoneConfig:{DescID: 114 (annie), SeqNum: 3}
   │         └── 1 Mutation operation
   │              └── AddDatabaseZoneConfig {"DatabaseID":114,"SeqNum":3}
   └── PreCommitPhase
        ├── Stage 1 of 2 in PreCommitPhase
        │    ├── 3 elements transitioning toward PUBLIC
        │    │    ├── PUBLIC → ABSENT DatabaseZoneConfig:{DescID: 114 (annie), SeqNum: 1}
        │    │    ├── PUBLIC → ABSENT DatabaseZoneConfig:{DescID: 114 (annie), SeqNum: 2}
        │    │    └── PUBLIC → ABSENT DatabaseZoneConfig:{DescID: 114 (annie), SeqNum: 3}
        │    └── 1 Mutation operation
        │         └── UndoAllInTxnImmediateMutationOpSideEffects
        └── Stage 2 of 2 in PreCommitPhase
             ├── 3 elements transitioning toward PUBLIC
             │    ├── ABSENT → PUBLIC DatabaseZoneConfig:{DescID: 114 (annie), SeqNum: 1}
             │    ├── ABSENT → PUBLIC DatabaseZoneConfig:{DescID: 114 (annie), SeqNum: 2}
             │    └── ABSENT → PUBLIC DatabaseZoneConfig:{DescID: 114 (annie), SeqNum: 3}
             └── 3 Mutation operations
                  ├── AddDatabaseZoneConfig {"DatabaseID":114,"SeqNum":1}
                  ├── AddDatabaseZoneConfig {"DatabaseID":114,"SeqNum":2}
                  └── AddDatabaseZoneConfig {"DatabaseID":114,"SeqNum":3}

(1 row)

Time: 4ms total (execution 4ms / network 0ms)
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 82 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-NziBEQ_A4RNqTv8mIaB:-O-bGOJxD1E2i0ERh6ej:bevto6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/deba4e155d6a22bf24f2bbf979832a3d94fd2c63/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L82)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: It feels like we should just pull in a narrower interface? WDYT?
</blockquote></details>

done -- yeah, i think that i just slapped this in here because it sounded remotely similar, but i don't think similar enough to not warrant another interface
___
*[`pkg/sql/schemachanger/scdeps/exec_deps.go` line 237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-NziCD443p7dr1AyXBnX:-O-c30oB0_eiPif0RMX0:bbj5b8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d54fb1778381f79ac947ae0cd47115b7f70788c3/pkg/sql/schemachanger/scdeps/exec_deps.go#L237)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Wait, shouldn't this be the raw bytes for the new zone config?
</blockquote></details>

let me add a comment or something, but it seems like we either update or insert whenever we are writing zone config to batch where:
- an insert is denoted by a value needing to be written (the ZoneConfigWithRawBytes's `zc`) and an empty expected values (since we don't expect any values to be in storage for a fresh insert) 
- an upsert is denoted by a value needing to be written (the ZoneConfigWithRawBytes's `zc`) and expected values for the values we are overwriting (ZoneConfigWithRawBytes's `rb`)

i took a look at the other code that calls on WriteZoneConfigToBatch and they seem to follow the same protocol (where zc and rb are not the same) like in repair.go:
https://github.com/cockroachdb/cockroach/blob/48ebfd19349624e70a658437af4e597be7e75c06/pkg/sql/repair.go#L836-L853

**Review by fqazi — APPROVED** [review]
Great work, I just have a few minor comments. Its good to merge after. :lgtm: 

> Reviewed 48 of 48 files at r6, 15 of 15 files at r7, 21 of 21 files at r8, 25 of 25 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-:-O-fhXw_5YawE5KWFopt:bbe8k7s)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom and @spilchen)

___
*[`pkg/sql/descriptor.go` line 296 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-fgcjkBu6RCvAF3Uc2:-O-fgcjkBu6RCvAF3Uc3:b-4zmgl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2391ef1bea22c7c063646e36158f5107f1d3dfed/pkg/sql/descriptor.go#L296)):*
> ```Go
> 		provider := p.regionsProvider()
> 		if provider == nil {
> 			return errors.New("no regions provider available")
> ```

errors.AssertionFailed? I don't think we expect this ever?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 497 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-NziDTL_4fz-qbQFu4iV:-O-ffJ_h7Im8KkdBcrZG:bu7nz4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L497)):*
> ```
>                                       -> USING num_replicas = 18;                
> ```

Can you try changing gc.ttlseconds and num_replicas in the same txn? Just want to make sure we have both changes by the end of the txn.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 61 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-fhCVAEdeG1FZzErpV:-O-fhCVAEdeG1FZzErpW:b-6spnaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10bdd42a06c59138644c2906137bb736dc66f0d/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L61)):*
> ```Go
> 	// Block from using YAML config unless we are discarding a YAML config.
> 	if n.YAMLConfig != nil && !n.Discard {
> 		panic(scerrors.NotImplementedErrorf(n,
> ```

Just as a a follow on maybe we should toss a warning on YAML in legacy to make this clear, if we don't have one. 
___
*[`pkg/sql/schemachanger/scdeps/exec_deps.go` line 237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-NziCD443p7dr1AyXBnX:-O-fgCU5CcKJDs0qBTvx:b2ybgtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d54fb1778381f79ac947ae0cd47115b7f70788c3/pkg/sql/schemachanger/scdeps/exec_deps.go#L237)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

let me add a comment or something, but it seems like we either update or insert whenever we are writing zone config to batch where:
- an insert is denoted by a value needing to be written (the ZoneConfigWithRawBytes's `zc`) and an empty expected values (since we don't expect any values to be in storage for a fresh insert) 
- an upsert is denoted by a value needing to be written (the ZoneConfigWithRawBytes's `zc`) and expected values for the values we are overwriting (ZoneConfigWithRawBytes's `rb`)

i took a look at the other code that calls on WriteZoneConfigToBatch and they seem to follow the same protocol (where zc and rb are not the same) like in repair.go:
https://github.com/cockroachdb/cockroach/blob/48ebfd19349624e70a658437af4e597be7e75c06/pkg/sql/repair.go#L836-L853
</blockquote></details>

Oh the name is just wacky and the comment on the zone config side isn't great:

// ZoneConfigWithRawBytes wraps a zone config together with its expected raw bytes. For cached modified zone configs, the raw bytes should be the   deserialized bytes from the zone config proto. Though, the raw bytes should   be the raw value read from kv when it's first read from storage.

^ The second part isn't clear. Probably should be clearer and say what we expect when doing a CPut

**Review by spilchen — COMMENTED** [review]
Thanks for addressing my earlier comments. I just had a follow-up question.

> Reviewed 48 of 48 files at r6, 15 of 15 files at r7, 21 of 21 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-:-O-gKGCP4LUx-N7LEmpS:bxmlohr)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 48 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-HnUFa4bVWFeopiBi1:-O-gHNXS-CLXnyZkvpqA:b-h6mvtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L48)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

done. yes! although getting database out in this PR gets a chunk of the work done -- the other PRs that i will stop hoarding (like #125786)

the list of objects we surpport configure zone on is: https://www.cockroachlabs.com/docs/stable/configure-replication-zones

i'll add a list in to be more verbose
</blockquote></details>

Is the support for configure zone on a table in a separate codepath? Maybe I am missing something, but it looks like the support in this file is just for the database object.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 155 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-gIAPk7rfASd_atgAp:-O-gIAPk7rfASd_atgAq:b-praqf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10bdd42a06c59138644c2906137bb736dc66f0d/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L155)):*
> ```Go
> 	if options == nil {
> 		// User is trying to update a zone config value that's protected for
> 		// multi-region databases. Return the constructed error.
> ```

nit: I wasn't sure if this was copied from below, where it does make sense.



_Suggestion:_
```Go
		// User is trying to remove the protected multi-region zone config.
		// Return the constructed error.
```

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121026)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/descriptor.go` line 296 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-fgcjkBu6RCvAF3Uc2:-O-qv3l78PBNJW2SJUKR:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2391ef1bea22c7c063646e36158f5107f1d3dfed/pkg/sql/descriptor.go#L296)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

errors.AssertionFailed? I don't think we expect this ever?
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 48 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-HnUFa4bVWFeopiBi1:-O-qxcS8B_EsFKJABfNZ:b-guq6ml) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L48)):*
> it looks like the support in this file is just for the database object

for this PR, yes -- i realized this question is probably centered around the fact that i mistakenly put table in my comment. fixed!
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 497 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-NziDTL_4fz-qbQFu4iV:-O-qxW82-QHSVf-Uni7y:bkapv1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c388c3d8ffb50ce1040ab40678326e23601e2454/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L497)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

> ```
>                                       -> USING num_replicas = 18;                
> ```

Can you try changing gc.ttlseconds and num_replicas in the same txn? Just want to make sure we have both changes by the end of the txn.
</blockquote></details>


```
demo@127.0.0.1:26257/demoapp/movr> set use_declarative_schema_changer = unsafe_always;                    
SET

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> begin;                                                                 
BEGIN

Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr  OPEN> alter database annie configure zone using num_replicas = 4;      
CONFIGURE ZONE 0

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr  OPEN> alter database annie configure zone using gc.ttlseconds = 13300; 
CONFIGURE ZONE 0

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr  OPEN> show zone configuration for database annie;                      
      target     |              raw_config_sql
-----------------+--------------------------------------------
  DATABASE annie | ALTER DATABASE annie CONFIGURE ZONE USING
                 |     range_min_bytes = 134217728,
                 |     range_max_bytes = 536870912,
                 |     gc.ttlseconds = 13300,
                 |     num_replicas = 4,
                 |     constraints = '[]',
                 |     lease_preferences = '[]'
(1 row)

Time: 2ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr  OPEN> commit;                                                          
COMMIT

Time: 11ms total (execution 8ms / network 3ms)

demo@127.0.0.1:26257/demoapp/movr> show zone configuration for database annie;                            
      target     |              raw_config_sql
-----------------+--------------------------------------------
  DATABASE annie | ALTER DATABASE annie CONFIGURE ZONE USING
                 |     range_min_bytes = 134217728,
                 |     range_max_bytes = 536870912,
                 |     gc.ttlseconds = 13300,
                 |     num_replicas = 4,
                 |     constraints = '[]',
                 |     lease_preferences = '[]'
(1 row)

Time: 6ms total (execution 5ms / network 0ms)
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 61 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-fhCVAEdeG1FZzErpV:-O-r1jHr9gEsxvzLB8G0:b-nhbf65) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10bdd42a06c59138644c2906137bb736dc66f0d/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L61)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Just as a a follow on maybe we should toss a warning on YAML in legacy to make this clear, if we don't have one.
</blockquote></details>

sure -- let me clarify what makes sense with dikshant and then add that in a smaller follow-up pr. i recall him suggesting a cluster setting at one point...
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 155 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-O-gIAPk7rfASd_atgAp:-O-qysqwE9nJOskAQg6y:b-xu4q62) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10bdd42a06c59138644c2906137bb736dc66f0d/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L155)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: I wasn't sure if this was copied from below, where it does make sense.
</blockquote></details>

thanks for the catch! i removed this part since it is guarded by the fact that we fallback to legacy when the user is trying to discard zone config
___
*[`pkg/sql/schemachanger/scdeps/exec_deps.go` line 237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-NziCD443p7dr1AyXBnX:-O-qzCRp7oq7vSSlAPB8:b-te4w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d54fb1778381f79ac947ae0cd47115b7f70788c3/pkg/sql/schemachanger/scdeps/exec_deps.go#L237)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Oh the name is just wacky and the comment on the zone config side isn't great:

// ZoneConfigWithRawBytes wraps a zone config together with its expected raw bytes. For cached modified zone configs, the raw bytes should be the   deserialized bytes from the zone config proto. Though, the raw bytes should   be the raw value read from kv when it's first read from storage.

^ The second part isn't clear. Probably should be clearer and say what we expect when doing a CPut
</blockquote></details>

done -- tried to make it a bit clearer

**Review by spilchen — APPROVED** [review]
lgtm

> Reviewed 53 of 53 files at r10, 8 of 8 files at r11, 10 of 10 files at r12, 18 of 18 files at r13, 20 of 20 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121026#-:-O-uoHZY2vvt7V8QvphR:bb7k0qh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

**Comment by annrpom** [comment]
TFTR! ('-')7

bors r=fqazi, spilchen

**Pull request merged**
