### PR TITLE
sql: Support column type DECIMAL in the SQL logic tests.

### PR DESCRIPTION
**Pull request by knz**
Needed for #5750.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5810)

### CODE REVIEW

**Comment by andreimatei** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5810#-:-KEIEPJx-CdiFgEhkWPG:676834233)*

**Comment by nvanbenschoten** [comment]
Wait dont merge yet.

**Comment by knz** [comment]
Of course I'll wait until it passes tests :)

**Comment by nvanbenschoten** [comment]
`sqllogictest` is actually a standard that we've tried to stick with, so I'm not sure we want to be extending the standard. You'll notice that `R` already has support for decimals, which is what the sqllite logic tests support and expect. Do you mind explaining your rationale a bit more here?

**Comment by knz** [comment]
Wow my mind is blown.
I thought I had tried R before and I got rejected then. 
Now your comment made me double check and it appears to work!

Well that's that that then. Thanks :)

**Pull request closed without merging**
