### PR TITLE
changefeedccl: create new spanFrontier tracker

### PR DESCRIPTION
**Pull request by danhhz**
`spanFrontier` tracks the minimum timestamp of a set spans. The
timestamp for a span may be advanced. If the span doesn't overlap (or
partially overlaps) the tracked span set, the currently untracked parts
will be noted, but not used to calculate the frontier.

The set of spans used to calculate the frontier may be changed.

@nvanbenschoten I've got a partial commit that uses this in changefeeds, planning on pushing it to this PR once I finish it up. This is the meaty part though, so I figured I'd get it out for early review. (Also, you'll notice I took liberal inspiration from the structure and tests of the rangefeed package!)

### CODE REVIEW

**Comment by danhhz** [comment]
Okay, pushed the commit that uses it

**Comment by danhhz** [comment]
Flakes are #26304 and #28132

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28319)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/span_frontier.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJUwAwjCQViAR1d5G6a:-LJUwAwjCQViAR1d5G6b:b-q03oa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf99215874bd7c02607a91e2c95f86a3a570766/pkg/ccl/changefeedccl/span_frontier.go#L31)):*
> ```Go
> 
> 	// tracked is true when this entry is included in the set of tracked spans.
> 	tracked bool
> ```

Expand this comment a bit. When are spans not tracked? Why do we need entries for those spans at all?
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJUv4hL6ON9mrtQL3nv:-LJUv4hL6ON9mrtQL3nw:b-sjq187) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf99215874bd7c02607a91e2c95f86a3a570766/pkg/ccl/changefeedccl/span_frontier.go#L95)):*
> ```
> all span `Forward`s
> ```

what do you mean by this?
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJUwVJKDo7gsz2hp5H4:-LJUwVJKDo7gsz2hp5H5:b-gwnwmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf99215874bd7c02607a91e2c95f86a3a570766/pkg/ccl/changefeedccl/span_frontier.go#L166)):*
> ```Go
> // set boundary). Similarly, an entry created by a previous Forward may be
> // partially overlapped and have to be split into two entries. Thus, there is no
> // easy relationship between this and the output of `Len`.
> ```

Is there a reason to export a `Len` method then?
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJV09TF0-xRXZaD5Ld3:-LJV09TF0-xRXZaD5Ld4:bcl4r06) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf99215874bd7c02607a91e2c95f86a3a570766/pkg/ccl/changefeedccl/span_frontier.go#L177)):*
> ```Go
> 	overlapping := s.tree.Get(entryKeys)
> 
> 	// TODO(dan): OverlapCoveringMerge is overkill, do this without it.
> ```

Yeah, this all seems a little expensive for what we're trying to accomplish. Can't we just scan from `span.Key` to `span.EndKey` in the interval tree and adjust accordingly. Take a look at `tscache/treeImpl.Add` for inspiration. That has a bit more logic because it's maintaining an LRU linked-list as well, but it will let you compare this approach to an alternative.
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJV-aZG6q6TyqRZ33S0:-LJV-aZG6q6TyqRZ33S1:b-rasxht) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf99215874bd7c02607a91e2c95f86a3a570766/pkg/ccl/changefeedccl/span_frontier.go#L194)):*
> ```Go
> 		var mergedTs hlc.Timestamp
> 		var tracked bool
> 		for _, payload := range m.Payload.([]interface{}) {
> ```

Checking my understanding here: this should always have either one or two payloads, right?

**Review by danhhz — COMMENTED** [review]
Okay, I think this is ready to go, including the second commit. PTAL @nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-:-LJoov_V4nsTzpB3Dfpp:b-hts0tw)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/span_frontier.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJUwAwjCQViAR1d5G6a:-LJojGsg6S7feOMl0RiL:bl02sur) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf99215874bd7c02607a91e2c95f86a3a570766/pkg/ccl/changefeedccl/span_frontier.go#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Expand this comment a bit. When are spans not tracked? Why do we need entries for those spans at all?
</blockquote></details>

I decided that adding this complexity was premature, so ripped it out. spanFrontier is now constructed with the set of spans it should track and it ignores everything outside them
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJUv4hL6ON9mrtQL3nv:-LJojRir0rsvGSzP5GA4:b-5pbso8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf99215874bd7c02607a91e2c95f86a3a570766/pkg/ccl/changefeedccl/span_frontier.go#L95)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> all span `Forward`s
> ```

what do you mean by this?
</blockquote></details>

uhhhhh, no idea. fixed
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJUwVJKDo7gsz2hp5H4:-LJojUi65lOhG70ULmxU:b-btxt3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf99215874bd7c02607a91e2c95f86a3a570766/pkg/ccl/changefeedccl/span_frontier.go#L166)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason to export a `Len` method then?
</blockquote></details>

was there for testing, but it wasn't great. replaced with a testing method that prints the entries (which does double duty of testing the method we'll use for checkpointing the component span-level resolved timestamps in the jobs progress)
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJV09TF0-xRXZaD5Ld3:-LJokMo71WuHZZwk_9P5:bggltvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf99215874bd7c02607a91e2c95f86a3a570766/pkg/ccl/changefeedccl/span_frontier.go#L177)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, this all seems a little expensive for what we're trying to accomplish. Can't we just scan from `span.Key` to `span.EndKey` in the interval tree and adjust accordingly. Take a look at `tscache/treeImpl.Add` for inspiration. That has a bit more logic because it's maintaining an LRU linked-list as well, but it will let you compare this approach to an alternative.
</blockquote></details>

100% agree, but I really don't want to bite this off right now. That method is over three hundred lines, most of which are comments to handhold the reader through its correctness. Gonna leave this one as a TODO, but added the `tscache/treeImpl.Add` pointer
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJV-aZG6q6TyqRZ33S0:-LJokuoA7PX6pGQGYlb2:b2nhtan) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf99215874bd7c02607a91e2c95f86a3a570766/pkg/ccl/changefeedccl/span_frontier.go#L194)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Checking my understanding here: this should always have either one or two payloads, right?
</blockquote></details>

Yup

**Review by rjnn — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28319)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/span_frontier.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJt4X7O38WkmZEfANio:-LJt4X7O38WkmZEfANip:bqt2z92) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier.go#L116)):*
> ```Go
> 		}
> 		s.idAlloc++
> 		if err := s.tree.Insert(e, true /* fast */); err != nil {
> ```

A `TODO` to refactor this panic away would be nice (or just refactor it away).
___
*[pkg/ccl/changefeedccl/span_frontier_test.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJt64U7BRLT1lqUCQQO:-LJt4d1EBS0aITDHq3pC:b-rqcn4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier_test.go#L32)):*
> ```Go
> 	return buf.String()
> }
> ```

I didn't understand how heaps worked, and was convinced you did it wrong, so I wrote up this test case, which proved that you did it right. But you can have it, since you might want to test your `spanFrontierHeap` separately in any case:

```
func TestSpanFrontierHeap(t *testing.T) {
	defer leaktest.AfterTest(t)()

	keyA, keyB := roachpb.Key("a"), roachpb.Key("b")
	keyC := roachpb.Key("c")

	spAB := roachpb.Span{Key: keyA, EndKey: keyB}
	//	spAC := roachpb.Span{Key: keyA, EndKey: keyC}
	//spAD := roachpb.Span{Key: keyA, EndKey: keyD}
	spBC := roachpb.Span{Key: keyB, EndKey: keyC}
	//spBD := roachpb.Span{Key: keyB, EndKey: keyD}
	//spCD := roachpb.Span{Key: keyC, EndKey: keyD}

	var sfh spanFrontierHeap

	e1 := spanFrontierEntry{
		span: spAB,
		ts:   hlc.Timestamp{WallTime: 1},
	}

	e2 := spanFrontierEntry{
		span: spBC,
		ts:   hlc.Timestamp{WallTime: 1},
	}

	heap.Push(&sfh, &e1)

	entry := heap.Pop(&sfh).(*spanFrontierEntry)

	if !reflect.DeepEqual(*entry, e1) {
		t.Fatalf("e1 %+v != popped %+v", e1, entry)
	}

	heap.Push(&sfh, &e1)
	heap.Push(&sfh, &e2)

	entry1 := heap.Pop(&sfh).(*spanFrontierEntry)
	_ = heap.Pop(&sfh)

	heap.Push(&sfh, &e2)
	heap.Push(&sfh, &e1)

	entry2 := heap.Pop(&sfh).(*spanFrontierEntry)
	_ = heap.Pop(&sfh)

	if !reflect.DeepEqual(entry1, entry2) {
		t.Fatalf("heap is not invariant on insertion order: %+v vs %+v", entry1, entry2)
	}
}
```

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-:-LJvyf7M7bw2MedEwJ3y:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/changefeed.go, line 245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJvyvSy2seKIH2rSv7e:-LJvyvSy2seKIH2rSv7f:b-wuqs51) ([raw file](https://github.com/cockroachdb/cockroach/blob/22c35308557d253f7a2096e784ca988650723b33/pkg/ccl/changefeedccl/changefeed.go#L245)):*
> ```Go
> 	var scratch bufalloc.ByteAllocator
> 	var key, value bytes.Buffer
> 	emitRowFn := func(ctx context.Context, row emitRow) error {
> ```

Out of curiosity, what is this style called where you're chaining closures to create a processing pipeline? Is it scala influenced?
___
*[pkg/ccl/changefeedccl/changefeed.go, line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJvyWr34qrHUK1_XTUX:-LJvyWr34qrHUK1_XTUY:b-xrzh1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/22c35308557d253f7a2096e784ca988650723b33/pkg/ccl/changefeedccl/changefeed.go#L312)):*
> ```Go
> 			// Make sure to flush the sink before forwarding resolved spans,
> 			// otherwise, we could lose buffered messages and violate the
> 			// at-least-once guarantee.
> ```

Make a note that we also need to flush before updating our job record with the updated resolved spans or we risk hitting the same hazard.
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJt4X7O38WkmZEfANio:-LJvvMOX0Mit8-Y7lSrF:brwgd52) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier.go#L116)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

A `TODO` to refactor this panic away would be nice (or just refactor it away).
</blockquote></details>

The method only returns an error if a span is inverted, so a panic here seems fine to me.

**Review by danhhz — COMMENTED** [review]
Thanks for the reviews!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-:-LJyAj-22FBsoxvJwt67:b9imwmn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/changefeed.go, line 245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJvyvSy2seKIH2rSv7e:-LJy28tX2JEUBTEPCl7r:b-hylssp) ([raw file](https://github.com/cockroachdb/cockroach/blob/22c35308557d253f7a2096e784ca988650723b33/pkg/ccl/changefeedccl/changefeed.go#L245)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Out of curiosity, what is this style called where you're chaining closures to create a processing pipeline? Is it scala influenced?
</blockquote></details>

i patterned it after distsql, actually. this is how RowSources chain together (though i guess distsql processors don't really use closures)
___
*[pkg/ccl/changefeedccl/changefeed.go, line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJvyWr34qrHUK1_XTUX:-LJy4ceeAcxLb2_II0yU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22c35308557d253f7a2096e784ca988650723b33/pkg/ccl/changefeedccl/changefeed.go#L312)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Make a note that we also need to flush before updating our job record with the updated resolved spans or we risk hitting the same hazard.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/span_frontier.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJt4X7O38WkmZEfANio:-LJy4eIzBN6gxT3CPsko:bvwba36) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier.go#L116)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The method only returns an error if a span is inverted, so a panic here seems fine to me.
</blockquote></details>

 = nathan
___
*[pkg/ccl/changefeedccl/span_frontier_test.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28319#-LJt64U7BRLT1lqUCQQO:-LJy4fowDOdvmeYRfRrk:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fa14eee4d5d996e5dab5a82d64c2ea7ccfba33b/pkg/ccl/changefeedccl/span_frontier_test.go#L32)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I didn't understand how heaps worked, and was convinced you did it wrong, so I wrote up this test case, which proved that you did it right. But you can have it, since you might want to test your `spanFrontierHeap` separately in any case:

```
func TestSpanFrontierHeap(t *testing.T) {
	defer leaktest.AfterTest(t)()

	keyA, keyB := roachpb.Key("a"), roachpb.Key("b")
	keyC := roachpb.Key("c")

	spAB := roachpb.Span{Key: keyA, EndKey: keyB}
	//	spAC := roachpb.Span{Key: keyA, EndKey: keyC}
	//spAD := roachpb.Span{Key: keyA, EndKey: keyD}
	spBC := roachpb.Span{Key: keyB, EndKey: keyC}
	//spBD := roachpb.Span{Key: keyB, EndKey: keyD}
	//spCD := roachpb.Span{Key: keyC, EndKey: keyD}

	var sfh spanFrontierHeap

	e1 := spanFrontierEntry{
		span: spAB,
		ts:   hlc.Timestamp{WallTime: 1},
	}

	e2 := spanFrontierEntry{
		span: spBC,
		ts:   hlc.Timestamp{WallTime: 1},
	}

	heap.Push(&sfh, &e1)

	entry := heap.Pop(&sfh).(*spanFrontierEntry)

	if !reflect.DeepEqual(*entry, e1) {
		t.Fatalf("e1 %+v != popped %+v", e1, entry)
	}

	heap.Push(&sfh, &e1)
	heap.Push(&sfh, &e2)

	entry1 := heap.Pop(&sfh).(*spanFrontierEntry)
	_ = heap.Pop(&sfh)

	heap.Push(&sfh, &e2)
	heap.Push(&sfh, &e1)

	entry2 := heap.Pop(&sfh).(*spanFrontierEntry)
	_ = heap.Pop(&sfh)

	if !reflect.DeepEqual(entry1, entry2) {
		t.Fatalf("heap is not invariant on insertion order: %+v vs %+v", entry1, entry2)
	}
}
```
</blockquote></details>

Done

**Comment by danhhz** [comment]
damnit bors. @arjunravinarayan can you approve, plz?

**Review by rjnn — APPROVED** [review]

**Comment by arjunravinarayan** [comment]
Done.

**Comment by danhhz** [comment]
Thanks!

bors r=nvanbenschoten,arjunravinarayan

**Comment by benesch** [comment]
@danhhz FYI I've been "Dismiss"ing reviews via the GitHub UI when I run into this problem.

**Comment by danhhz** [comment]
Didn't know you could do that. I was thinking we should turn off this check in bors; we should be able to trust people to only kick it off in appropriate circumstances

**Comment by benesch** [comment]
I'm not sure we _can_ do that. At least, I'm not seeing a Bors configuration option for it.

**Comment by danhhz** [comment]
Thanks for checking! Your workaround is good enough for me, then

**Comment by danhhz** [comment]
`TestLogic/fakedist` flaked with `unable to dial n3: breaker open`

bors r=nvanbenschoten,arjunravinarayan

**Pull request merged**
