### PR TITLE
[DNM] clusterversion: set developmentBranch to false

### PR DESCRIPTION
**Pull request by celiala**
DNM: Using this draft to confirm that tests pass for:
- https://github.com/cockroachdb/cockroach/pull/111634/commits/e57ff81d078cc95e505d0d0513e492d76e2199ed
I plan to ultimately close this in favor https://github.com/cockroachdb/cockroach/pull/111634

### CODE REVIEW

**Comment by celiala** [comment]
The following 2 tests fail for `./dev test pkg/sql/catalog/bootstrap` (see error message below):

- For `TestSystemDatabaseSchemaBootstrapVersionBumped`: I was able to fix by setting `prevSystemHash = "858ffcb4bcdc6fb82c4cfff812ac3a0037a0d6267996d00e924c1edd33df14d9"`.
- For `TestInitialValuesToString`: I'm having trouble figuring out what exactly to run in order to "rewrite the expected test output and the hash value", in order to fix/pass.


```
I231008 20:11:35.871890 1 (gostd) rand.go:250  [-] 1  random seed: -8009162691271454191
--- FAIL: TestInitialValuesToString (0.00s)
    test_log_scope.go:170: test logs captured to: /tmp/cockroach/_tmp/403fccac927737279f86cb423ac2d596/logTestInitialValuesToString2074717473
    test_log_scope.go:81: use -show-logs to present logs inline
    --- FAIL: TestInitialValuesToString/testdata (0.00s)
        bootstrap_test.go:96: Unexpected hash value 858ffcb4bcdc6fb82c4cfff812ac3a0037a0d6267996d00e924c1edd33df14d9 for system.
            If you're seeing this error message, this means that the bootstrapped system
            schema has changed. Assuming that this is expected:
            - If this occurred during development on the main branch, rewrite the expected
              test output and the hash value and move on.
            - If this occurred during development of a patch for a release branch, make
              very sure that the underlying change really is expected and is backward-
              compatible and is absolutely necessary. If that's the case, then there are
              hardcoded literals in the main development branch as well as any subsequent
              release branches that need to be updated also.
    bootstrap_test.go:111: -- test log scope end --
--- FAIL: TestSystemDatabaseSchemaBootstrapVersionBumped (0.00s)
    test_log_scope.go:170: test logs captured to: /tmp/cockroach/_tmp/403fccac927737279f86cb423ac2d596/logTestSystemDatabaseSchemaBootstrapVersionBumped4252596510
    test_log_scope.go:81: use -show-logs to present logs inline
    bootstrap_test.go:183: Check whether you need to bump systemschema.SystemDatabaseSchemaBootstrapVersion
        and then update prevSystemHash to "858ffcb4bcdc6fb82c4cfff812ac3a0037a0d6267996d00e924c1edd33df14d9".
        The current value of SystemDatabaseSchemaBootstrapVersion is 23.1-32.
    panic.go:522: -- test log scope end --
FAIL
I231008 20:11:41.136582 1 (gostd) testmain.go:93  [-] 1  Test //pkg/sql/catalog/bootstrap:bootstrap_test exited with error code 1
```

**Comment by celiala** [comment]
Message for `pkg/sql/catalog/bootstrap/TestInitialValuesToString` is:
```
bootstrap_test.go:96: Unexpected hash value 858ffcb4bcdc6fb82c4cfff812ac3a0037a0d6267996d00e924c1edd33df14d9 for system.
            If you're seeing this error message, this means that the bootstrapped system
            schema has changed. Assuming that this is expected:
            - If this occurred during development on the main branch, rewrite the expected
              test output and the hash value and move on.
```
I can't figure out what exactly to run in order to "rewrite the expected test output and the hash value":
 - @andyyang890 or @zachlite - perhaps one of you could help direct me here? 
Thank you!

**Comment by andyyang890** [comment]
@celiala You'll need to update the hash in `pkg/sql/catalog/bootstrap/testdata/testdata` to be the expected hash from the error message and then run the test again with `--rewrite`:
https://github.com/cockroachdb/cockroach/blob/a87f0c71ab05a1569641744cb687e8c913d46f1b/pkg/sql/catalog/bootstrap/testdata/testdata#L1

You'll probably need to do a second time for the tenant hash later in the file:
https://github.com/cockroachdb/cockroach/blob/a87f0c71ab05a1569641744cb687e8c913d46f1b/pkg/sql/catalog/bootstrap/testdata/testdata#L194

**Comment by celiala** [comment]
Closing this in favor of https://github.com/cockroachdb/cockroach/pull/112452:

We don't need to merge this onto master. We can instead set this directly on release-23.2

**Pull request closed without merging**
