### PR TITLE
sctest: Add a test that runs comparator testing from logictest stmts

### LINKED ISSUE #108183: Schema: Add comparator testing in logic tests
We should add comparator checks for logic tests where we run the same test with the legacy schema changer and the declarative schema changer. These tests should check that the end state of the data and descriptors after the schema changes are the same for both. This will alert us in events where there is a divergence in the logic between the two schema changers. The legacy schema changer will treated as the ground truth for such tests.

Jira issue: CRDB-30354

Epic CRDB-30346

### PR DESCRIPTION
**Pull request by Xiang-Gu**
This commit introduced a new test that takes as input a path to a corpus file (of stmts collected from logic tests) and feed them into the comparator testing framework.

It also edit the existing nightly such that we now collect the corpus and immediately feed them into the comparator testing framework, without having to store them in the cloud in between.

Fixes #108183
Epic [CRDB-30346](https://cockroachlabs.atlassian.net/browse/CRDB-30346)
Release note: None

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111660)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 879 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111660#-NfvFfw1AhulCFfAE5Qe:-NfvFfw1AhulCFfAE5Qf:b-u7cbsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfa86e2f6e0761bbf3c11488fabe20b3981e899e/pkg/sql/schemachanger/schemachanger_test.go#L879)):*
> ```Go
> var logictestStmtsCorpusFile = flag.String("logictest-stmt-corpus-path", "", "path to logictest stmts corpus")
> 
> func TestComparatorFromLogicTests(t *testing.T) {
> ```

Do we want some parallelism in this test? Not sure how it currently performs. Might make sense to have a subtest per-file also to help ID failures

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111660)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 879 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111660#-NfvFfw1AhulCFfAE5Qe:-NfvkQPJ3vDIUzj8ePLG:b3yep1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfa86e2f6e0761bbf3c11488fabe20b3981e899e/pkg/sql/schemachanger/schemachanger_test.go#L879)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Do we want some parallelism in this test? Not sure how it currently performs. Might make sense to have a subtest per-file also to help ID failures
</blockquote></details>

yeah, that's a good point. I've modified the test such that each "entry" (i.e. stmts from the same logic test file) is run in a separate subtest.

**Review by fqazi — COMMENTED** [review]
:lgtm:  Nice!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111660#-:-NfvmNM12aiB1Xy8H_At:b-bsmgd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Xiang-Gu)

**Review by fqazi — APPROVED** [review]
> Reviewed 6 of 6 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111660)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Xiang-Gu)

___
*[`pkg/sql/schemachanger/sctest/comparator.go` line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111660#-Ng-ErWMB7QNksP1tt8j:-Ng-ErWMB7QNksP1tt8k:b-bexh8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab679ea491c3292f9cde832c837e808e41594650/pkg/sql/schemachanger/sctest/comparator.go#L79)):*
> ```Go
> 		// state. This step is to account for the known behavior difference between
> 		// the two schema changers.
> 		// Only run when not in a transaction.
> ```

Maybe so more about what breaks.

**Comment by Xiang-Gu** [comment]
TFTR!
bors r+

**Pull request merged**
