### PR TITLE
sql: start of distributed SQL implementation

### PR DESCRIPTION
**Pull request by RaduBerinde**
Broken down into a few commits:
- APIs
- SQL expression support
- TableReader
- Server wiring (WIP)
  See each commit message for more context.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6368)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Reviewed 5 of 5 files at r1, 8 of 8 files at r2, 6 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/indexed_vars.go, line 80 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSGCFepBkBPQtdQD2e:-KGSGCFepBkBPQtdQD2f:32664111) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a4fbef6d7ee75d5f380515c5f92eaf8b36d5a1d/sql/parser/indexed_vars.go#L80)):*
`SELECT VALUES($1, $912125125)` would have `NumVars() == 912125126`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368)*

**Comment by tschottdorf** [comment]
Only gave this a rough pass, but wanted to stop and thank you for putting very manageable pieces up and not a huge initial PR.

**Comment by RaduBerinde** [comment]
Thanks!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/indexed_vars.go, line 80 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSGCFepBkBPQtdQD2e:-KGSMw_o0pqdlLRArFYf:256695454) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a4fbef6d7ee75d5f380515c5f92eaf8b36d5a1d/sql/parser/indexed_vars.go#L80)):*
No, we initialize the `IndexedVarHelper` with the amount of variables we have available - for tablereader this is the number of columns in the table. When we process the expression we check if the $xx number is less than `NumVars()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGSN_1UdBANC-7p1p_k:-1834867277)*

**Comment by andreimatei** [comment]
LGTM

---

Review status: 5 of 22 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[server/server.go, line 82 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSvm7CTRY5Si7Ek26R:-KGSvm7CTRY5Si7Ek26S:945999905) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf9d6b1e058cf7f3e3652443b2c4c110d53d0ca/server/server.go#L82)):*
how about using distSQLServerImpl here? The interface is not useful for anything, is it? Or dropping the member all-together.

---

*[sql/dist_sql_server.go, line 70 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSwnHaiA-4SXAH_QIE:-KGSwnHaiA-4SXAH_QIF:-1513377344) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf9d6b1e058cf7f3e3652443b2c4c110d53d0ca/sql/dist_sql_server.go#L70)):*
how about doing this `Run()` call in a different goroutine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGSx6sfiKxI-Jqf6x20:676834233)*

**Comment by RaduBerinde** [comment]
Review status: 5 of 22 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[server/server.go, line 82 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSvm7CTRY5Si7Ek26R:-KGSyZ2gwGvu1DpUcxMr:-1663869276) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf9d6b1e058cf7f3e3652443b2c4c110d53d0ca/server/server.go#L82)):*
Ah I see what you mean now, no point keeping it here unless we can use its fields for something. Will switch to storing a pointer to the struct.

---

*[sql/dist_sql_server.go, line 70 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSwnHaiA-4SXAH_QIE:-KGSxqz0lN3zUj6T4q6G:824028581) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf9d6b1e058cf7f3e3652443b2c4c110d53d0ca/sql/dist_sql_server.go#L70)):*
Yup, definitely can't run like this when there are multiple readers :) I'll work on that in follow-up changes though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 5 of 22 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[server/server.go, line 82 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSySKNnrtCHPiAcvrq:-KGSySKNnrtCHPiAcvrr:59775191) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf9d6b1e058cf7f3e3652443b2c4c110d53d0ca/server/server.go#L82)):*
There is a bit of stuttering with some of the name here. Perhaps `s/sql.DistSQLServer/sql.DistServer/g`. Same comment applies to the `dist_sql_*` filenames.

---

*[sql/dist_sql_api.proto, line 34 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSuvq-sevnhHfqMG6p:-KGSuvq-sevnhHfqMG6q:-1263437294) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d17e1940567244a20a360aba8c0e65196d09920/sql/dist_sql_api.proto#L34)):*
The response isn't quite empty given that it contains an error. 

---

*[sql/dist_sql_data.proto, line 25 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSxR9iD1wxy0-YnyXf:-KGSxR9iD1wxy0-YnyXg:-1803157709) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d17e1940567244a20a360aba8c0e65196d09920/sql/dist_sql_data.proto#L25)):*
`s/SQLExpression/Expression/g` to avoid stuttering. 

---

*[sql/dist_sql_data.proto, line 37 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSyWwmSU_x_08IiIUi:-KGSyWwmSU_x_08IiIUj:-2057779177) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf9d6b1e058cf7f3e3652443b2c4c110d53d0ca/sql/dist_sql_data.proto#L37)):*
Something like: 

```
repeated roachpb.Value start = 1 [(gogoproto.nullable) = false];
repeated roacphb.Value end = 1 [(gogoproto.nullable) = false];
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGSzCXxtZDSX6iHafZD:1417088721)*

**Comment by RaduBerinde** [comment]
Review status: 5 of 22 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[server/server.go, line 82 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSySKNnrtCHPiAcvrq:-KGSzupqhsKb7ADFKxsQ:-1757386920) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf9d6b1e058cf7f3e3652443b2c4c110d53d0ca/server/server.go#L82)):*
Hm, I don't know.. We have the dist sender which might make things confusing when reading code where the sql prefix isn't there or when simply talking about things..

---

*[sql/dist_sql_api.proto, line 34 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSuvq-sevnhHfqMG6p:-KGT-1dkABKngziUMHI6:1869539445) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d17e1940567244a20a360aba8c0e65196d09920/sql/dist_sql_api.proto#L34)):*
Will rename to SetupFlowsResponse

---

*[sql/dist_sql_data.proto, line 37 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSyWwmSU_x_08IiIUi:-KGT-iy4VYvyWiK-A0FJ:1442471221) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf9d6b1e058cf7f3e3652443b2c4c110d53d0ca/sql/dist_sql_data.proto#L37)):*
Right, the problem is that the index selection code generates key spans. We can more easily switch when we rewrite that code to use values instead of keys (something I have on my TODO list anyway)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368)*

**Comment by RaduBerinde** [comment]
TFTRs, updated.

---

Review status: 1 of 22 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[server/server.go, line 82 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGSySKNnrtCHPiAcvrq:-KGT4wLidbgzvsis-UCo:-1190606728) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf9d6b1e058cf7f3e3652443b2c4c110d53d0ca/server/server.go#L82)):*
As for the filenames - I don't like them either, but I don't want the files to blend in with the rest of the files in sql/ (the directory is already pretty daunting). We will likely move these into a separate package and then the dist_sql_ prefix can go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGT5EjWV5-c0m3SrVjH:240422629)*

**Comment by nvanbenschoten** [comment]
Nice job on this!

---

Reviewed 3 of 21 files at r9, 7 of 9 files at r10, 4 of 6 files at r11, 1 of 2 files at r12.
Review status: 16 of 22 files reviewed at latest revision, 16 unresolved discussions, all commit checks successful.

---

*[sql/dist_sql_api.proto, line 39 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGT8q_ecTyLRVojC39Z:-KGT8q_ecTyLRVojC39_:-203954925) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_api.proto#L39)):*
s/set flows/set of flows/?

---

*[sql/dist_sql_data.proto, line 25 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGT7qxeblT6n1IO9RlT:-KGT7qxeblT6n1IO9RlU:-1827626876) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_data.proto#L25)):*
Is there anything more specific we can name this to avoid having `sql.Expression` and `sql/parser.Expr` types?

---

*[sql/dist_sql_data.proto, line 63 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGT7RTavTF0vzFiZAH9:-KGT7RTbYuUexGlvaeZv:-718142572) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_data.proto#L63)):*
Could you add a comment about the `FlowSpec`'s purpose, since for now it's the same as a `TableReaderSpec`?

---

*[sql/dist_sql_data.proto, line 65 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGT9H3LkZWqwcseDt2z:-KGT9H3LkZWqwcseDt3-:-2123657863) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_data.proto#L65)):*
Nullable?

---

*[sql/dist_sql_expr.go, line 26 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGTDbwTi2rVsJrBHzhF:-KGTDbwTi2rVsJrBHzhG:1480880480) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_expr.go#L26)):*
Aren't ValArgs 1-indexed?

---

*[sql/dist_sql_server.go, line 71 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGT9cMqbFYMYp6Xr6PF:-KGT9cMqbFYMYp6Xr6PG:-1974061538) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_server.go#L71)):*
We dont do anything with this error? It's not added to the response or returned?

---

*[sql/dist_sql_tablereader.go, line 158 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGTDCSAfKBQo7bxHsy7:-KGTDCSAfKBQo7bxHsy8:-928078933) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_tablereader.go#L158)):*
s/TODO/TODO(RaduBerinde )/

---

*[sql/structured.go, line 720 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGTBQipEf7LaUueQ6mc:-KGTBQipEf7LaUueQ6md:-520819859) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/structured.go#L720)):*
I'd consider calling this `toDatumType`. The use of dummy datum variables as types is something that @knz and I are going to look at soon, but for now, calling it `toDatum` makes its purpose a little unclear.

---

*[sql/parser/indexed_vars.go, line 70 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGTC6v7CvwwDJMNQFj0:-KGTC6v7CvwwDJMNQFj1:2085546106) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/parser/indexed_vars.go#L70)):*
Are there situations where `container.Len() != numVars` (`container.Len()` doesnt exist yet, but you get the idea)? If not, maybe consolidate them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGTDkSlZTs70ktg6xd6:1641593379)*

**Comment by RaduBerinde** [comment]
Thanks! Updated.

---

Review status: 1 of 22 files reviewed at latest revision, 16 unresolved discussions, some commit checks pending.

---

*[sql/dist_sql_data.proto, line 25 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGT7qxeblT6n1IO9RlT:-KGTGW2IAK9nKu-BmLP5:-300534506) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_data.proto#L25)):*
I started with SQLExpression but I just renamed it at Peter's request..  Do you have any suggestion? We will probably move all this to a separate package so it might not matter then.

---

*[sql/dist_sql_data.proto, line 65 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGT9H3LkZWqwcseDt2z:-KGTHL3qL1TKRJX53lFs:-888729711) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_data.proto#L65)):*
this will change soon, it's going to be a repeated list of "processors" and "streams" or something like that

---

*[sql/dist_sql_expr.go, line 26 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGTDbwTi2rVsJrBHzhF:-KGTHRFJU3k5xykwU0qg:1074876413) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_expr.go#L26)):*
AFAICT they can be anything, even `$foo`. We aren't using any of the ValArgs functionality, just reusing the syntax (we convert them to IndexedVars right after parsing).

---

*[sql/dist_sql_server.go, line 71 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGT9cMqbFYMYp6Xr6PF:-KGTJbPh6NqncPTYOjMu:-909157472) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_server.go#L71)):*
we don't return anything yet, this temporary.. Run will (in the general case) run in a separate goroutine and we need to work on some infrastructure for returning results

---

*[sql/parser/indexed_vars.go, line 70 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGTC6v7CvwwDJMNQFj0:-KGTIHegqcwKqVt-zLdE:122608127) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/parser/indexed_vars.go#L70)):*
I'd prefer to keep the IndexedVarContainer interface as simple as possible. "Container" is just a name, maybe "Manager" or "Handler" would have been more appropriate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGTKjTyFcpiuzBkla9E:-1953558848)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 1 of 22 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[sql/dist_sql_data.proto, line 25 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGT7qxeblT6n1IO9RlT:-KGTPQfsmWv23VE5YJ38:-1349601683) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_data.proto#L25)):*
If it's in a `sql/dist` package or something, then `dist.Expression` seems fine.

---

*[sql/dist_sql_data.proto, line 65 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-KGT9H3LkZWqwcseDt2z:-KGTPZoEHjLenqCQORe9:677042770) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1b644dfa8e1d20d66eee3b44585a9ba0d34245/sql/dist_sql_data.proto#L65)):*
SGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGTPtJN7zW2a6tWTE2I:1417088721)*

**Comment by RaduBerinde** [comment]
I want to move this new stuff to a separate package before it gets too big; the problem is that this depends on `structured.proto`. So the plan I have right now is:
 - move `structured.proto/go`, `privilege.proto/go` to `sql/base` or `sql/common`. Some other common functionality might go in there other than protos.
 - move dist_sql stuff to `sql/dist`
 - `sql` depends on `sql/dist`. `sql/dist` depends on `sql/base` and `sql/parser`
 - move some of the useful functionality from `sql_test` to some common test-only package where it can be used by both `sql_test` and `dist_test`

Any objections or alternate proposals?

---

Review status: 1 of 22 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGX0I5AHY9HBS5ASuVz:-836069268)*

**Comment by petermattis** [comment]
`sql/base` has the problem that you would then have `base.TableDescriptor`. Perhaps `sqlbase` instead. I don't have a clear picture in my head of the various distributed SQL bits, but I'd worry that `sql/dist` (or `sqldist`) would need to depend on `sql` which would in turn want to depend on `sqldist`. Avoiding the circular dependency might involve some awkward contortions. That's not a reason not to do it, just something to be aware of. 

---

Review status: 1 of 22 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGX5LxIbKRLhzSMuRDL:1499337095)*

**Comment by RaduBerinde** [comment]
Thanks Peter! Would that be `/sql/sqlbase` or `/sqlbase`? Bear in mind that this package would depend on `sql/parser`, some of the functions around the common proto stuff (in `structured.go`) already need it.

Yeah, the circular dependency issue is why we need the third "base" package. I think that in the long term, maintaining the separation will pay off. And if it turns out to be too much of a pain, we can easily revert to one package. Doing the opposite - splitting the packages later - would be much harder as we accumulate more code and interdependencies.

---

Review status: 1 of 22 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGXZRFLvElHIa6JEXXw:1066442374)*

**Comment by petermattis** [comment]
Guess that depends on whether we want the nested directories for some other reason. I don't feel too strongly either way, though the repetition in the path `sql/sqlbase` is a bit distracting. We could always move `sql/parser` to `sqlparser` (or `sql/sqlparser`) for consistency.

---

Review status: 1 of 22 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGXb1iPFr15I_ipoqZA:985598025)*

**Comment by RaduBerinde** [comment]
Are there any technical differences between the two? Or are they equivalent as far as go is concerned?

---

Review status: 1 of 22 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGXbqsInJUAvRrhLMgi:16330276)*

**Comment by petermattis** [comment]
The one difference is if we ever start using `internal` packages. Other than that, the two are equivalent.

---

Review status: 1 of 22 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6368#-:-KGXcZOdLXz5XgwGjGhT:2028204891)*

**Pull request merged**
