### PR TITLE
plpgsql: add support for execution of routines with exception blocks

### LINKED ISSUE #105253: plpgsql: implement exception handling
PLpgSQL blocks allow an `EXCEPTION` clause, which is able to catch and examine errors thrown in the block body. Once an error is caught, the statements in that branch of the `EXCEPTION` clause are executed as normal PLpgSQL statements. Any postgres error can be caught, for example `division_by_zero`: https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-ERROR-TRAPPING

This will take special care to ensure errors are caught and propagated correctly. I've prototyped an approach here: https://github.com/cockroachdb/cockroach/commit/a5f1766239a55c75ff34b170a2a5720e59c2bdf8

Epic: CRDB-799

Jira issue: CRDB-28942

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: add parser and optbuilder support for exception blocks

This patch adds support in the parser and optbuilder for the
EXCEPTION block of a PLpgSQL routine. A future commit will add
execution support. See the `buildExceptions` comments in `plpgsql.go`
for further detail.

#### plpgsql: add support for execution of routines with exception blocks

This patch adds support for executing a PLpgSQL routine with an
exception block. This allows PLpgSQL routines to catch arbitrary errors
encountered during execution of the main block, and then return either
a datum result or another error. For example:
```
CREATE FUNCTION f(n INT) RETURNS INT AS $$
  BEGIN
    RETURN 1 / n;
  EXCEPTION
    WHEN division_by_zero THEN
      RETURN 100;
  END
$$ LANGUAGE PLpgSQL;

--Returns 1
SELECT f(1);

--Returns 100
SELECT f(0);
```

Fixes #105253

Release note (sql change): Added support for execution of PLpgSQL
functions with exception blocks. This allows a PLpgSQL function to
catch and handle arbitrary errors it encounters during its execution.

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]
parser LGTM. nice work.

**Review by rharding6373 — APPROVED** [review]
:lgtm: This is great! I mostly just have nits and test suggestions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-:-Nan0Og_9UGOmA-EDD9-:box8jv6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NamlpbxB0YsPFvMj7aO:-NamlpbxB0YsPFvMj7aP:b-qi2k74) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e26d4d2434c64fc4dac6f96df6d7438cb20eea/pkg/sql/plpgsql/parser/plpgsql.y#L393)):*
> ```Yacc
>       Decls: $2.plpgsqlDecls(),
>       Body: $4.plpgsqlStatements(),
>       Exceptions: $5.plpgsqlExceptions(),
> ```

I see in another PR you're adding support for SQL exec statements! In light of that, what are your thoughts on the `EXCEPTION` example 43.2 in https://www.postgresql.org/docs/15/plpgsql-control-structures.html? Can we parse and execute the `merge_db` function correctly with both of these PRs? (I haven't spent much time looking at your other PR, so maybe this is addressed there).
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 839 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-Namk31rD5vhbK4xfvux:-Namk31s9FGc9FTMHR-4:b-6jex7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb25622c8a9643ef2ae9df73be86cc0580de72e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L839)):*
> ```
> CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$
>   BEGIN
>     RETURN 1 // 0;
> ```

Do you happen to know why we support `//` as a division operator instead of `/`? We have the opposite behavior as postgres:

postgres:
```
rharding=# CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$

rharding$#   BEGIN

rharding$#     RETURN 1 // 0;

rharding$#   END $$ LANGUAGE PLpgSQL;

CREATE FUNCTION

rharding=# select f();

ERROR:  operator does not exist: integer // integer
```

CRDB:

root@127.0.0.1:26257/defaultdb> CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$                                                        

                             \->   BEGIN                                                                                                 

                             \->     RETURN 1 // 0;                                                                                      

                             \->   END                                                                                                   

                             \-> $$ LANGUAGE PLpgSQL;                                                                                    

CREATE FUNCTION
  

root@127.0.0.1:26257/defaultdb> select f();                                                                                             

ERROR: division by zero

SQLSTATE: 22012

root@127.0.0.1:26257/defaultdb> CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$                                                        

                             \->   BEGIN                                                                                                 

                             \->     RETURN 1 / 0;                                                                                       

                             \->   END                                                                                                   

                             \-> $$ LANGUAGE PLpgSQL;                                                                                    

CREATE FUNCTION

root@127.0.0.1:26257/defaultdb> select f();                                                                                             

ERROR: unsupported binary operator: <int> / <int> (desired <int>)
```
```

___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 949 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NamhO6E0OX_19Q3Z0_f:-NamhO6E0OX_19Q3Z0_g:b-aqf1mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb25622c8a9643ef2ae9df73be86cc0580de72e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L949)):*
> ```
> 100
> 
> # Raise with error name, catch with error name.
> ```

Minor and completely optional suggestion: you could consolidate some of these tests by putting the different `RAISE` codes you're testing into a `CASE` of `IF` based on an input value, then call the same function on different input values to trigger (or not) the various exceptions.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1096 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-Namj8Fu8L06Hxg1UxDA:-Namj8Fu8L06Hxg1UxDB:bds3i2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb25622c8a9643ef2ae9df73be86cc0580de72e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1096)):*
> ```
> 
> query IIII
> SELECT f(0, 0, 0), f(1, 0, 0), f(1, 1, 0), f(1, 1, 1);
> ```

Nice test.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NamzwvN01VKf-wr2bAa:-NamzwvN01VKf-wr2bAb:b-junxft) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb25622c8a9643ef2ae9df73be86cc0580de72e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1214)):*
> ```
> 
> statement error pgcode 42601 pq: invalid SQLSTATE code '123aB'
> SELECT f();
> ```

Could you add a test that has an error during the exception block? E.g.,
```
BEGIN
  RETURN 1 / 0;
EXCEPTION
  WHEN division_by_zero THEN
    RETURN 2/0;
END
```
___
*[`pkg/sql/opt/optbuilder/testdata/udf_plpgsql` line 3086 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-Name5pH8xFMSC30Px6O:-Name5pH8xFMSC30Px6P:bo77msf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e26d4d2434c64fc4dac6f96df6d7438cb20eea/pkg/sql/opt/optbuilder/testdata/udf_plpgsql#L3086)):*
> ```
> CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$
>   BEGIN
>     RAISE this_error_does_not_exist;
> ```

I think that the optbuilder test suite could be pruned to query plans that are interesting. All the error tests could be done in the logic test only. And there are some redundant queries (e.g., the series of 3 exceptions and one raise that varies its code) that could be removed since their plans don't add much value here.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107601)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NamlpbxB0YsPFvMj7aO:-NaxLf6ZCQ4F0TS7fTt8:bphn51p) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e26d4d2434c64fc4dac6f96df6d7438cb20eea/pkg/sql/plpgsql/parser/plpgsql.y#L393)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I see in another PR you're adding support for SQL exec statements! In light of that, what are your thoughts on the `EXCEPTION` example 43.2 in https://www.postgresql.org/docs/15/plpgsql-control-structures.html? Can we parse and execute the `merge_db` function correctly with both of these PRs? (I haven't spent much time looking at your other PR, so maybe this is addressed there).
</blockquote></details>

Right now `EXCEPTION` block doesn't have the nested transaction semantics (I'll add a TODO). I plan to implement that using savepoints, and it definitely needs to be handled before the release.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 839 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-Namk31rD5vhbK4xfvux:-NaxMuxM8O6Q_yaZPfld:b-qw49gm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb25622c8a9643ef2ae9df73be86cc0580de72e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L839)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Do you happen to know why we support `//` as a division operator instead of `/`? We have the opposite behavior as postgres:

postgres:
```
rharding=# CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$

rharding$#   BEGIN

rharding$#     RETURN 1 // 0;

rharding$#   END $$ LANGUAGE PLpgSQL;

CREATE FUNCTION

rharding=# select f();

ERROR:  operator does not exist: integer // integer
```

CRDB:

root@127.0.0.1:26257/defaultdb> CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$                                                        

                             \->   BEGIN                                                                                                 

                             \->     RETURN 1 // 0;                                                                                      

                             \->   END                                                                                                   

                             \-> $$ LANGUAGE PLpgSQL;                                                                                    

CREATE FUNCTION
  

root@127.0.0.1:26257/defaultdb> select f();                                                                                             

ERROR: division by zero

SQLSTATE: 22012

root@127.0.0.1:26257/defaultdb> CREATE OR REPLACE FUNCTION f() RETURNS INT AS $$                                                        

                             \->   BEGIN                                                                                                 

                             \->     RETURN 1 / 0;                                                                                       

                             \->   END                                                                                                   

                             \-> $$ LANGUAGE PLpgSQL;                                                                                    

CREATE FUNCTION

root@127.0.0.1:26257/defaultdb> select f();                                                                                             

ERROR: unsupported binary operator: <int> / <int> (desired <int>)
```
```

</blockquote></details>

This is a known issue: https://github.com/cockroachdb/cockroach/issues/41448. It's a little sad, but oh, well.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 949 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NamhO6E0OX_19Q3Z0_f:-NaxOCIEEWP-4W4E69GX:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb25622c8a9643ef2ae9df73be86cc0580de72e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L949)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Minor and completely optional suggestion: you could consolidate some of these tests by putting the different `RAISE` codes you're testing into a `CASE` of `IF` based on an input value, then call the same function on different input values to trigger (or not) the various exceptions.
</blockquote></details>

Good idea, done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1096 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-Namj8Fu8L06Hxg1UxDA:-NaxNEYj8hnP13bMHCNE:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb25622c8a9643ef2ae9df73be86cc0580de72e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1096)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Nice test.
</blockquote></details>

Thanks!
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 1214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NamzwvN01VKf-wr2bAa:-NaxNxEI0r0bhZPsOF8w:b-t45cp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb25622c8a9643ef2ae9df73be86cc0580de72e/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L1214)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you add a test that has an error during the exception block? E.g.,
```
BEGIN
  RETURN 1 / 0;
EXCEPTION
  WHEN division_by_zero THEN
    RETURN 2/0;
END
```
</blockquote></details>

Good call, added it.
___
*[`pkg/sql/opt/optbuilder/testdata/udf_plpgsql` line 3086 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-Name5pH8xFMSC30Px6O:-NaxT4Nt9BF5ZkShtDme:b-6adh7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e26d4d2434c64fc4dac6f96df6d7438cb20eea/pkg/sql/opt/optbuilder/testdata/udf_plpgsql#L3086)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think that the optbuilder test suite could be pruned to query plans that are interesting. All the error tests could be done in the logic test only. And there are some redundant queries (e.g., the series of 3 exceptions and one raise that varies its code) that could be removed since their plans don't add much value here.
</blockquote></details>

Good point, I'll prune those down.

**Review by mgartner — APPROVED** [review]
:lgtm: 

Great work and nice tests!

Do we support `BEGIN` blocks within other control structures yet? If so, we should have `EXCEPTION` handler tests for those too.

> Reviewed 6 of 12 files at r1, 8 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-:-NbQMcJ78sgrTT8vexG6:b-k8qz7)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/opt/memo/expr.go` line 734 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NbQIttT6kt79YhXAwHO:-NbQIttT6kt79YhXAwHP:b-d6k8bj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fd44cba4090fa5f2b8c370efa59e0a9b2a83666/pkg/sql/opt/memo/expr.go#L734)):*
> ```Go
> 	// Codes is a list of pgcode strings (see pgcode/codes.go). When the body of a
> 	// routine with an ExceptionBlock returns an error, the code of that error is
> 	// compared against the Codes slice for a match.
> ```

nit: Explain why `Codes` is `[]string` and not `[]pgcode.Code` here too.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 263 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NbQJXpFBTE1zKpj-Uxm:-NbQJXpFBTE1zKpj-Uxn:b1ixfy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fd44cba4090fa5f2b8c370efa59e0a9b2a83666/pkg/sql/opt/optbuilder/plpgsql.go#L263)):*
> ```Go
> 			if b.exceptionBlock != nil {
> 				// If exception handling is required, we have to start a new
> 				// continuation after each variable assignment. This ensures that in the
> ```

This is an for errors during assignment, correct? Can exceptions from variable declarations in `DECLARE` blocks be caught, or no?
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 606 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NbQK-di42gC35-gRocu:-NbQK-di42gC35-gRocv:bulgdti) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fd44cba4090fa5f2b8c370efa59e0a9b2a83666/pkg/sql/opt/optbuilder/plpgsql.go#L606)):*
> ```Go
> // The first condition handles the case when an error occurs before any variable
> // assignments happen. PLpgSQL exception blocks do not catch errors that occur
> // during variable declaration.
> ```

Ahh, this answers my previous question.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 616 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NbQKAwh-1lFPS7Nsc9g:-NbQKAwh-1lFPS7Nsc9h:b-k1mto8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fd44cba4090fa5f2b8c370efa59e0a9b2a83666/pkg/sql/opt/optbuilder/plpgsql.go#L616)):*
> ```Go
> // the assignment continuation is called, the continuation will have access to
> // the updated value from the assignment, and can supply it to the exception
> // handler.
> ```

nit: I think a simple example would really help communicate this.
___
*[`pkg/sql/pgwire/pgcode/codes.go` line 415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NbQILiV2xZpzN9d9L7H:-NbQILiV2xZpzN9d9L7I:b-tra3ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fd44cba4090fa5f2b8c370efa59e0a9b2a83666/pkg/sql/pgwire/pgcode/codes.go#L415)):*
> ```Go
> func IsValidPGCode(code string) bool {
> 	// The code must consist of 5 digits and/or upper-case ASCII letters.
> 	return regexp.MustCompile(`[A-Z0-9]{5}`).MatchString(code)
> ```

nit: make the compiled regex a global variable to avoid re-compiling everytime the function is called

**Review by DrewKimball — COMMENTED** [review]
>Do we support `BEGIN` blocks within other control structures yet?

Not yet, nested blocks aren't planned for 23.2.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-:-NbRFgg5Av8GceQFb2Kq:b-q9on4s)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/memo/expr.go` line 734 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NbQIttT6kt79YhXAwHO:-NbWjYht6E_rCt6w1TdE:b6oofsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fd44cba4090fa5f2b8c370efa59e0a9b2a83666/pkg/sql/opt/memo/expr.go#L734)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Explain why `Codes` is `[]string` and not `[]pgcode.Code` here too.
</blockquote></details>

The answer is that there's no real reason, just a holdover from an early implementation. I've switched to using `pgcode.Code` instead.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 606 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NbQK-di42gC35-gRocu:-NbRFEww4i1ZYx0gGYkm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fd44cba4090fa5f2b8c370efa59e0a9b2a83666/pkg/sql/opt/optbuilder/plpgsql.go#L606)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ahh, this answers my previous question.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 616 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NbQKAwh-1lFPS7Nsc9g:-NbWgGD_4b_TnngslVKA:bjxhtes) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fd44cba4090fa5f2b8c370efa59e0a9b2a83666/pkg/sql/opt/optbuilder/plpgsql.go#L616)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I think a simple example would really help communicate this.
</blockquote></details>

Done. Let me know if you think it needs more clarification.
___
*[`pkg/sql/pgwire/pgcode/codes.go` line 415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107601#-NbQILiV2xZpzN9d9L7H:-NbWh8lPC5SzEV2qYsJ7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fd44cba4090fa5f2b8c370efa59e0a9b2a83666/pkg/sql/pgwire/pgcode/codes.go#L415)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: make the compiled regex a global variable to avoid re-compiling everytime the function is called
</blockquote></details>

Done.

**Comment by DrewKimball** [comment]
TFTRs! These aren't trivial to review; I appreciate the help.

bors r+

**Pull request merged**
