### PR TITLE
cli/flags,config: new flag for tenant KV listen addr

### LINKED ISSUE #51464: kvserver: expose grpc server for tenant use
We need to set up a separate gRPC server at the kv layer that accepts tenants' incoming connection. This is a prelude to https://github.com/cockroachdb/cockroach/issues/47898.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #51464.

This patch introduces the ability to split off the tenant KV server into a
separate port, using the new command-line flag `--tenant-addr`.

This is motivated primarily by security concerns. We plan to use different
TLS configs for KV<->KV kv/replication/gossip traffic and SQL<->KV tenant
kv traffic. The easiest way to facilitate this is to listen to tenant KV
traffic on a separate port and separate gRPC server.

The `--tenant-addr` and `--advertise-tenant-addr` flags are inspired by the
`--sql-addr` and `--advertise-sql-addr` flags. The two pairs have similar
fallback behavior, as is discussed in depth in 6cb71bf.

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Nice! Let's also write the listener files for the tenant port (if the flag was changed):

https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server.go#L769-L775

Is it OK for me to start working off this branch or do you anticipate more changes to be piled on?

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-:-MAa6YuQ1BLfXv9bF-2j:b-grmto3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/cli/cliflags/flags.go, line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MAa5XX5AjLFukWq9MM0:-MAa5XX5AjLFukWq9MM1:b4z5n7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/46559436bce5fe93f6931addb9d8fc4bd5903e53/pkg/cli/cliflags/flags.go#L534)):*
> ```Go
> To actually use separate bindings, it is recommended to specify both
> flags and use a different port number via --listen-addr, for example
> --tenant-addr=:26257 --listen-addr=:26258. Ensure that --join is set
> ```

To make our life a little easier, I was thinking to suggest *3*6257 for the tenant.
___
*[pkg/cli/cliflags/flags.go, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MAa61oS8OOXb5XnCL_c:-MAa61oS8OOXb5XnCL_d:bvgbx7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/46559436bce5fe93f6931addb9d8fc4bd5903e53/pkg/cli/cliflags/flags.go#L545)):*
> ```Go
> 
> 	TenantAdvertiseAddr = FlagInfo{
> 		Name: "advertise-tenant-addr",
> ```

nit: you write `--advertise-tenant-addr` in a few places, can those use `"--"+TenantAdvertiseAddr.Name`
___
*[pkg/roachpb/metadata.go, line 483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MAa6TZcBIPdfm0rknGF:-MAa6TZcBIPdfm0rknGG:b-n3pzm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/46559436bce5fe93f6931addb9d8fc4bd5903e53/pkg/roachpb/metadata.go#L483)):*
> ```Go
> }
> 
> // CheckedTenandAddress returns the value of TenantAddress if set. If not,
> ```

Tenant here and in method name

**Review by tbg — COMMENTED** [review]
PS this is still marked as draft, not sure it's intentional

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-:-MAa72F15WvEh2N5rIgG:brwz3p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by tbg** [comment]
Test failure for your convenience:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x38b3f62]

goroutine 1 [running]:
panic(0x4435280, 0x7ab5310)
	/usr/local/go/src/runtime/panic.go:722 +0x2c2 fp=0xc000b05890 sp=0xc000b05800 pc=0x75bb62
github.com/cockroachdb/cockroach/pkg/util/log.RecoverAndReportPanic(0x53c9300, 0xc000072108, 0xc00046aa80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:88 +0x9f fp=0xc000b058e0 sp=0xc000b05890 pc=0xfdf15f
runtime.call32(0x0, 0x4b804b8, 0xc000b05f00, 0x1800000018)
	/usr/local/go/src/runtime/asm_amd64.s:539 +0x3b fp=0xc000b05910 sp=0xc000b058e0 pc=0x78a4bb
panic(0x4435280, 0x7ab5310)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2 fp=0xc000b059a0 sp=0xc000b05910 pc=0x75ba52
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:199
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:394 +0x3ec fp=0xc000b059d0 sp=0xc000b059a0 pc=0x77177c
github.com/cockroachdb/cockroach/pkg/cli.extraServerFlagInit(0x7af4020, 0xc000b05cb8, 0x97f0d4)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/flags.go:933 +0x8d2 fp=0xc000b05c50 sp=0xc000b059d0 pc=0x38b3f62
github.com/cockroachdb/cockroach/pkg/cli.init.8.func3(0x7af4020, 0xc00078bea0, 0x0, 0x7, 0x7b316a0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/flags.go:277 +0x2b fp=0xc000b05c80 sp=0xc000b05c50 pc=0x38ec08b
github.com/cockroachdb/cockroach/pkg/cli.AddPersistentPreRunE.func1(0x7af4020, 0xc00078bea0, 0x0, 0x7, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/flags.go:110 +0x5d fp=0xc000b05cc8 sp=0xc000b05c80 pc=0x38ebefd
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x7af4020, 0xc00078be30, 0x7, 0x7, 0x7af4020, 0xc00078be30)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:741 +0x56b fp=0xc000b05da0 sp=0xc000b05cc8 pc=0x35bcfeb
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x7aec240, 0xc000072108, 0xc0002967ea, 0xc)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x2ea fp=0xc000b05e70 sp=0xc000b05da0 pc=0x35bd91a
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:800
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:223
github.com/cockroachdb/cockroach/pkg/cli.Main()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:67 +0x272 fp=0xc000b05f50 sp=0xc000b05e70 pc=0x388a712
main.main()
```

**Review by nvb — COMMENTED** [review]
> Let's also write the listener files for the tenant port (if the flag was changed):

Yeah, we're writing these. This is tested by `TestListenerFileCreation`.

> Test failure for your convenience:

Fixed.

> PS this is still marked as draft, not sure it's intentional

Yes, that was intentional. It's no longer a draft and gets all the way to starting a second gRPC server.

I updated this with a pair of follow on commits that changes the tenant proxy to route tenant KV traffic to this new tenant KV address when a node is configured with one. We now have unit tests and roachtests that exercise this logic.

PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-:-MCIMYTQ8nizZwiDLGz5:bdhb9t8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cli/cliflags/flags.go, line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MAa5XX5AjLFukWq9MM0:-MCINA-V8XVSs-jyf80t:bz7j4e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/46559436bce5fe93f6931addb9d8fc4bd5903e53/pkg/cli/cliflags/flags.go#L534)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

To make our life a little easier, I was thinking to suggest *3*6257 for the tenant.
</blockquote></details>

I like the idea of using 36257 in our deployments, but making that the default port iff `--tenant-addr` is specified but its port is omitted is tricky and not obviously worth the complexity, so I'll leave this as-is for now.
___
*[pkg/cli/cliflags/flags.go, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MAa61oS8OOXb5XnCL_c:-MCIOatD5WkKhh-buA_E:b-5qjisd) ([raw file](https://github.com/cockroachdb/cockroach/blob/46559436bce5fe93f6931addb9d8fc4bd5903e53/pkg/cli/cliflags/flags.go#L545)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: you write `--advertise-tenant-addr` in a few places, can those use `"--"+TenantAdvertiseAddr.Name`
</blockquote></details>

I only see one instance of this outside of comments:
```
return errors.Wrap(err, "invalid --advertise-tenant-addr")
```

Is that what you're referring to?
___
*[pkg/roachpb/metadata.go, line 483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MAa6TZcBIPdfm0rknGF:-MCIP46sAvDTCZuI87qY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/46559436bce5fe93f6931addb9d8fc4bd5903e53/pkg/roachpb/metadata.go#L483)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Tenant here and in method name
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
Regarding this:
> The `--tenant-addr` and `--advertise-tenant-addr` flags are inspired by the `--sql-addr` and `--advertise-sql-addr` flags. The two pairs have similar fallback behavior, as is discussed in depth in 6cb71bf.

1) We found out that `--advertise-sql-addr` is not so useful after all. In contrast with the RPC addresses it so happens that crdb does not need to self-connect over public/private network boundaries, so that distinction was over-engineered (and is turning out unnecesary).

2) I wonder here if `--advertise-tenant-addr` is actually necessary. This would only make sense if you had the following combination of design requirements:

  - a tenant SQL server needs to run in a separate DC / internet region than the KV server, so it needs to know the public address of the KV server; and
  - a tenant SQL server must discover the address of the KV server automatically by using some advertisement information from the KV server. (If there is no need for auto-discovery, there's no need to distinguish addr vs advertised addr)

The first requirement was not on planning for CC free tier, as far as I know; but even then, the second requirement is completely non-sensical with the KV/SQL disctinction, and therefore I think it makes no sense whatsoever to try to develop an "advertised addr".

Unless I misunderstood something?

> Reviewed 1 of 21 files at r1, 3 of 16 files at r2, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-:-MCIcP6kEGg3ETQCzBgd:bckqo99)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by nvanbenschoten** [comment]
Good point, I hear what you're saying. I added the flag primarily to maintain consistency between this pair of flags and the the `--sql-addr` and `--advertise-sql-addr` pair of flags. But since you bring it up, we should discuss if the `--advertise-tenant-addr` is worth adding at all.

> The first requirement was not on planning for CC free tier, as far as I know; but even then, the second requirement is completely non-sensical with the KV/SQL disctinction, and therefore I think it makes no sense whatsoever to try to develop an "advertised addr".

You are correct that the first requirement is not applicable to CC free tier. As far as I know, we don't plan to separate the public address of these KV servers from their private address. What I'm less sure about is whether there will ever be reason to make such distinctions. We do have aspirations to provide this infrastructure to others, so I don't think we should limit ourselves entirely to just how we plan to deploy the thing.

As for the second requirement, tenant SQL servers do need to discover the address of the KV servers automatically. This is why these advertised addrs are stored on NodeDescriptors that are propagated to SQL servers through the tenant proxy. I might be misunderstanding what you mean with this point.

**Comment by knz** [comment]
> tenant SQL servers do need to discover the address of the KV servers automatically. This is why these advertised addrs are stored on NodeDescriptors that are propagated to SQL servers through the tenant proxy.

That is ... odd. Are you telling me that a node descriptor arrives to the SQL server *from the client-side proxy*?  How does the proxy even learn of the node descriptor then?

**Comment by nvanbenschoten** [comment]
> Are you telling me that a node descriptor arrives to the SQL server from the client-side proxy? How does the proxy even learn of the node descriptor then?

SQL processes are started with a set of seed KV addresses, passed in through the `--kv-addrs` flag. These addresses are used by the [tenant proxy](https://github.com/cockroachdb/cockroach/pull/50520) (not the SQL proxy! in case that's where the confusion is coming from) to subscribe to a subset of the gossip network's information. This subscription is where it learns about NodeDescriptors. It then uses these descriptors to route KV traffic to a KV node's tenant gRPC service, given a node ID from a RangeDescriptor. It uses the tenant proxy here as well, to delegate range lookups (`fn(key) -> RangeDesc`) to one of the seed KV nodes. Does that make sense?

**Comment by tbg** [comment]
I also find the "proxy" naming for this subsystem a little unfortunate due to the ambiguity. It's not really a proxy, anyway - no stand-alone component and it's not like it's passing anything "through" really, it's merely subscribing to updates from KV. It is more of a "connector" or "gateway" IMO. For example, we could rename the proxy to `KVConnector` or `KVDiscovery` and then we could say "the tenant SQL servers use run a KVConnector to maintain an up-to-date view of the KV layer's topology and configuration needed for routing requests to ranges".

**Review by tbg — APPROVED** [review]
Nice! I (locally) rebased #51498 on top of this and will see about adding the right certs on the server side.

> Reviewed 13 of 16 files at r2, 6 of 6 files at r4, 5 of 5 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-:-MCLmaE_EuTQeioViTda:b-rir10s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/cli/cliflags/flags.go, line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MAa5XX5AjLFukWq9MM0:-MCLjj2H3dWzlhbuiTRB:b-8cd9zo) ([raw file](https://github.com/cockroachdb/cockroach/blob/46559436bce5fe93f6931addb9d8fc4bd5903e53/pkg/cli/cliflags/flags.go#L534)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I like the idea of using 36257 in our deployments, but making that the default port iff `--tenant-addr` is specified but its port is omitted is tricky and not obviously worth the complexity, so I'll leave this as-is for now.
</blockquote></details>

How about updating this to `--listen-addr=:26257` and `--tenant-addr=:36257` to match what we expect to be the canonical use?
___
*[pkg/cli/cliflags/flags.go, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MAa61oS8OOXb5XnCL_c:-MCLjwxq0aYDlslq2Rti:bagyjen) ([raw file](https://github.com/cockroachdb/cockroach/blob/46559436bce5fe93f6931addb9d8fc4bd5903e53/pkg/cli/cliflags/flags.go#L545)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I only see one instance of this outside of comments:
```
return errors.Wrap(err, "invalid --advertise-tenant-addr")
```

Is that what you're referring to?
</blockquote></details>

Looks like it (based on my on grepping, the original comment is too long ago to remember)
___
*[pkg/cmd/roachtest/multitenant.go, line 28 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MCLkqNd0qtAxBsGLnq6:-MCLkqNd0qtAxBsGLnq7:b-cieo68) ([raw file](https://github.com/cockroachdb/cockroach/blob/961cec51adc6b316155db911b42bbe53347a2849/pkg/cmd/roachtest/multitenant.go#L28)):*
> ```Go
> 	// Don't bind to external interfaces when running locally.
> 	tenantAddr := ifLocal("127.0.0.1", "0.0.0.0") + ":0"
> 	c.Start(ctx, t, c.All(), startArgs("--args=--tenant-addr="+tenantAddr))
> ```

Mind adding a comment here that we're starting a tenant server on another port,
___
*[pkg/cmd/roachtest/multitenant.go, line 33 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MCLl2JF-EHqufjnnHxm:-MCLl2JF-EHqufjnnHxn:b-b8lykv) ([raw file](https://github.com/cockroachdb/cockroach/blob/961cec51adc6b316155db911b42bbe53347a2849/pkg/cmd/roachtest/multitenant.go#L33)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	kvAddrs := c.ExternalAddr(ctx, c.All())
> ```

Shouldn't this be the tenant server address? I think as written the proxy will connect to the "wrong" port on KV (which will still work because of lack of the real auth).
___
*[pkg/server/testserver.go, line 793 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MCLkaq3BG2GFrsoQjF3:-MCLkaq3BG2GFrsoQjF4:b-lmhxwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4441f92e07ba51d1a88eaaa99e8fe0d8a6f9d84b/pkg/server/testserver.go#L793)):*
> ```Go
> }
> 
> // ServingTenantAddr returns the server's Tenant address. Should be used by clients.
> ```

"by clients"?

**Comment by knz** [comment]
I went to #50520 to educate myself. In light of that, I retract my comment on the "advertise flag being nonsensical".  Then, for consistency with the other flags, you can keep it. So the code LGTM.

That said I agree with Tobias that the word "proxy" is problematic. I like the proposals for "connector" and "discovery".

**Review by nvb — COMMENTED** [review]
TFTR!

> That said I agree with Tobias that the word "proxy" is problematic. I like the proposals for "connector" and "discovery".

I empathize with the confusion. I'll rename to "connector" in a follow on PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-:-MCNjRbcE10HPB7OwMl2:bclo7v9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/cli/cliflags/flags.go, line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MAa5XX5AjLFukWq9MM0:-MCNWo7ZDRvNbLSok26C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/46559436bce5fe93f6931addb9d8fc4bd5903e53/pkg/cli/cliflags/flags.go#L534)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

How about updating this to `--listen-addr=:26257` and `--tenant-addr=:36257` to match what we expect to be the canonical use?
</blockquote></details>

Done.
___
*[pkg/cli/cliflags/flags.go, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MAa61oS8OOXb5XnCL_c:-MCNYPs51pwAIWpAbELD:b5rx8bw) ([raw file](https://github.com/cockroachdb/cockroach/blob/46559436bce5fe93f6931addb9d8fc4bd5903e53/pkg/cli/cliflags/flags.go#L545)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Looks like it (based on my on grepping, the original comment is too long ago to remember)
</blockquote></details>

I don't feel strongly for error strings, but done throughout `addr_validation.go`.
___
*[pkg/cmd/roachtest/multitenant.go, line 28 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MCLkqNd0qtAxBsGLnq6:-MCNcyAh6Vkyn9e4ITIF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/961cec51adc6b316155db911b42bbe53347a2849/pkg/cmd/roachtest/multitenant.go#L28)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Mind adding a comment here that we're starting a tenant server on another port,
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/multitenant.go, line 33 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MCLl2JF-EHqufjnnHxm:-MCNj3om42irW7e2Im92:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/961cec51adc6b316155db911b42bbe53347a2849/pkg/cmd/roachtest/multitenant.go#L33)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Shouldn't this be the tenant server address? I think as written the proxy will connect to the "wrong" port on KV (which will still work because of lack of the real auth).
</blockquote></details>

Good point, done.
___
*[pkg/server/testserver.go, line 793 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50503#-MCLkaq3BG2GFrsoQjF3:-MCNbIOA1Mx4ksN_2YRI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4441f92e07ba51d1a88eaaa99e8fe0d8a6f9d84b/pkg/server/testserver.go#L793)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

"by clients"?
</blockquote></details>

Done.

**Pull request merged**
