### PR TITLE
settings: enforce that all descriptions start with lower case letters

### PR DESCRIPTION
**Pull request by nvb**
Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
:clap: :clap: great idea!

:lgtm: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27407#-:-LH9Z8RdE8bNZlx8Fg1S:b-u8ogu6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/settings/registry.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27407#-LH9ZTPq8Kwd8W5SrdbI:-LH9ZTPq8Kwd8W5SrdbJ:b-4i46tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf1e4e3815d5c4b8982adecdf2430272d457f463/pkg/settings/registry.go#L50)):*
> ```Go
> 		panic(fmt.Sprintf("setting already defined: %s", key))
> 	}
> 	if len(desc) > 0 && desc[:1] != strings.ToLower(desc[:1]) {
> ```

Might as well enforce that they're not empty? Also slight preference for using `unicode.IsUpper`.

```
if len(desc) == 0 {
  panic(fmt.Sprintf("setting missing description: %s", key))
}
if r, _ := utf8.DecodeRuneInString(desc); unicode.IsUpper(r) {
// panic(...
```

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27407)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/settings/registry.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27407#-LH9ZTPq8Kwd8W5SrdbI:-LH9zC7OBp7qS6YJf7Qz:bcujtxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf1e4e3815d5c4b8982adecdf2430272d457f463/pkg/settings/registry.go#L50)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Might as well enforce that they're not empty? Also slight preference for using `unicode.IsUpper`.

```
if len(desc) == 0 {
  panic(fmt.Sprintf("setting missing description: %s", key))
}
if r, _ := utf8.DecodeRuneInString(desc); unicode.IsUpper(r) {
// panic(...
```
</blockquote></details>

Good suggestion! Done.

**Review by benesch — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27407)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by nvanbenschoten** [comment]
Flaked on #27417. Round two!

bors r+

**Pull request merged**
