### PR TITLE
kvserver: deflake read load metric test

### LINKED ISSUE #112391: kv/kvserver: TestReadLoadMetricAccounting failed
kv/kvserver.TestReadLoadMetricAccounting [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12187970?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/12187970?buildTab=artifacts#/) on release-23.2 @ [87a94f6ac59d4e01c822bb2128db858176600dd6](https://github.com/cockroachdb/cockroach/commits/87a94f6ac59d4e01c822bb2128db858176600dd6):

```
=== RUN   TestReadLoadMetricAccounting
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestReadLoadMetricAccounting3976845280
    test_log_scope.go:81: use -show-logs to present logs inline
    replica_rankings_test.go:210: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_rankings_test.go:210
        	            				github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_rankings_test.go:433
        	            				github.com/cockroachdb/cockroach/pkg/testutils/soon.go:75
        	            				github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:213
        	            				github.com/cockroachdb/cockroach/pkg/testutils/soon.go:81
        	            				github.com/cockroachdb/cockroach/pkg/testutils/soon.go:60
        	            				github.com/cockroachdb/cockroach/pkg/testutils/soon.go:42
        	            				github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_rankings_test.go:398
        	Error:      	Max difference between 0 and 79 allowed is 60, but difference was -79
        	Test:       	TestReadLoadMetricAccounting
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestReadLoadMetricAccounting3976845280
--- FAIL: TestReadLoadMetricAccounting (8.38s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestReadLoadMetricAccounting.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32393

### PR DESCRIPTION
**Pull request by kvoli**
`TestReadLoadMetricAccounting` measures the read/write bytes of the
leaseholder for a target range, asserting that the replica load stats
(roughly) match the requests sent by the test.

The test incorrectly created keys to fill a SST by using
`scratchKey.Next()`, which sorts into the key range
`/{Systemtse-Table/0}`, instead of the scratch range created
`/{Table/Max-Max}`. The incorrect range could also contain timeseries
data, which would be written to and cause the write bytes to be higher
than expected, failing the test.

Update the key creation to avoid this occurring and clean up the test.

Fixes: https://github.com/cockroachdb/cockroach/issues/112391
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
```
dev test pkg/kv/kvserver -f TestReadLoadMetricAccounting -v --stress --race --count=2000
...
//pkg/kv/kvserver:kvserver_test                                          PASSED in 20.9s
  Stats over 2000 runs: max = 20.9s, min = 9.4s, avg = 13.9s, dev = 1.3s
```

May still be flaky on CI.

**Comment by kvoli** [comment]
Extended CI flake looks unrelated.

**Review by andrewbaptist — COMMENTED** [review]
:lgtm: modulo the nits listed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112458#-:-NhCOPtY792-_Idi-PWa:blull91)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replica_rankings_test.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112458#-NhCLedx0ABNc_OG15qo:-NhCLedx0ABNc_OG15qp:b6tln3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c61596bceef38ccbb71304f2559779aeb4e141e/pkg/kv/kvserver/replica_rankings_test.go#L371)):*
> ```Go
> 		{getReadBA, 1, 0, 1, 0, 10},
> 		{genVariableRead(ctx, start, sstKeys[1].(storage.MVCCKeyValue).Key.Key), 1, 0, 1, 0, 38},
> 		{genVariableRead(ctx, start, sstKeys[4].(storage.MVCCKeyValue).Key.Key), 1, 0, 4, 0, 152},
> ```

nit: Can you pull out a constant for 38 and write the lines as 
1 * entry_size
4 * entry_size
64 * entry_size

Otherwise it is hard to see where the magic is coming from. Alternatively since these numbers match the `expectedRPS` you could use the same variable for both and compute it within the expectation.
___
*[`pkg/kv/kvserver/replica_rankings_test.go` line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112458#-NhCMnXo5GWiMocyRDUf:-NhCMnXo5GWiMocyRDUg:b-muoloe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c61596bceef38ccbb71304f2559779aeb4e141e/pkg/kv/kvserver/replica_rankings_test.go#L390)):*
> ```Go
> 	// artificially inflating measurement due to consistency checking.
> 	sqlDB.Exec(t, `SET CLUSTER SETTING server.consistency_check.interval = '0'`)
> 	sqlDB.Exec(t, `SET CLUSTER SETTING kv.range_split.by_load.enabled = false`)
> ```

nit: Should we change `ReplicationManual` to encompass these two settings if it doesn't already? 

There are 3 reasons for this:
1) It is easy to forget to set these, and if they really are required it will likely be found by a test being flakey
2) This is done using SQL here so it prevents using `DisableSQLServer` on this test (otherwise I think the test could use that and run twice as fast)
3) These settings are just before we start writing, so there is a risk that it won't have propagated to all nodes by the time the test is running and we could accidentally split (if the split by load is still enabled). I don't think this can happen on a 1 node cluster, but it definitely could if this was a multi-node cluster.

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112458#-:-NhCSpSh9FdHbglYvfvH:b-80sls6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/replica_rankings_test.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112458#-NhCLedx0ABNc_OG15qo:-NhCQ-u40iMshdPi_plk:b-tgo3h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c61596bceef38ccbb71304f2559779aeb4e141e/pkg/kv/kvserver/replica_rankings_test.go#L371)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Can you pull out a constant for 38 and write the lines as 
1 * entry_size
4 * entry_size
64 * entry_size

Otherwise it is hard to see where the magic is coming from. Alternatively since these numbers match the `expectedRPS` you could use the same variable for both and compute it within the expectation.
</blockquote></details>

Updated to entry size, nice suggestion.
___
*[`pkg/kv/kvserver/replica_rankings_test.go` line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112458#-NhCMnXo5GWiMocyRDUf:-NhCQ4hr3Bp8ecBNErWT:b165pp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c61596bceef38ccbb71304f2559779aeb4e141e/pkg/kv/kvserver/replica_rankings_test.go#L390)):*
> nit: Should we change `ReplicationManual` to encompass these two settings if it doesn't already?
`SET CLUSTER SETTING kv.range_split.by_load.enabled = false` is already applied by disabling the split queue via `ReplicationManual`, I removed the line.

Disabling the consistency checker seems specific to this test, but generally could be useful to keep around.

I have another branch which disables the SQL server for this test, but it wasn't the cause of the flake. I'd prefer to defer disabling SQL server into a larger batch of commits for tests which we think would be appropriate for.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

**Comment by kvoli** [comment]
TYFTR

bors r=andrewbaptist

**Pull request merged**
