### PR TITLE
storage: write to AbortSpan less, clean up AbortSpan more

### LINKED ISSUE #29128: storage: clear abort span on non-poisoning, aborting EndTransaction request
Forked from https://github.com/cockroachdb/cockroach/pull/28799#issuecomment-414090586.

> Why isn't
>
> https://github.com/cockroachdb/cockroach/blob/f435f61bec59768ad54fe4ff5ae0028059b9bf08/pkg/storage/batcheval/cmd_end_transaction.go#L492-L497
>
> written as:
> 
> ```go
> if txn.Status == roachpb.ABORTED {
> 	if err := SetAbortSpan(ctx, evalCtx, batch, ms, txn.TxnMeta, args.Poison); err != nil {
> 		return nil, err
> 	}
> }
> ```
> 
> The effect of this is that we currently never remove abort span entries if they exist when the `TxnCoordSender` sends an `EndTransactionRequest(Commit=false)`. My understanding of `Poison` and its interaction with the `AbortSpan` is that it is safe to remove the entry when `Poison=false` because that implies an acknowlegement from the `TxnCoordSender` of the transaction's aborted disposition. I wonder if this has any implications on https://github.com/cockroachdb/cockroach/issues/25233.

Response from @tschottdorf:

> I think this comes (came?) down to a lack of trust in that TxnCoordSender was doing the right thing with respect to its "async aborts". Could a txn be aborted (unbeknownst to it) and dispatch a read (which needs to hit the abort span for correctness) that would be "passed" by an async abort but would still return its value to the client? If so, clearing the abort span from the async abort would let the read return something incorrect (i.e. not read what you wrote).
>
> I agree that we should revisit this and that it has a likely connection to #25233!

We should explore this further.

@tschottdorf for triage.

### PR DESCRIPTION
**Pull request by nvb**
This PR introduces two improvements to our handling of the AbortSpan. It also introduces the first set of comprehensive testing around AbortSpan entry state transitions, which was sorely missing. 

This comes after a few different customer issues that at least at first glance appeared to be AbortSpan leaks. There's still more to do to resolve those, mostly by improving GC, but anything we can do here on the frontend to reduce the number of AbortSpan entries that need to be GCed in the first place helps.

### Clean up span on non-poisoning, aborting EndTransaction request

Fixes #29128.

Before this change, an EndTransaction request sent to rollback a transaction record would not remove any AbortSpan entries, even if its own Poison flag was set to false. This allowed AbortSpan entries to leak. This commit fixes this behavior by removing the AbortSpan entry in this case.

There were concerns raised in #29128 about this being safe. It turns out that we already do this on every Range except the transaction record's Range during normal intent resolution, so this isn't introducing any new concerns.

### Only write AbortSpan entries if intents are removed

This reduces the frequency of AbortSpan entries that can be abandoned even without a transaction coordinator failure. Specifically, it protects against the case where intent resolution races with a transaction coordinator cleaning up its own transaction record and intents. This can happen for both aborted and committed transactions.

In the first case, a pusher might find a transaction's intent and then find its record to be aborted after that transaction had cleanly rolled back its own intents. Even though the transaction's coordinator had already cleaned up and potentially "unpoisoned" AbortSpans, the pusher would happily re-introduce AbortSpan records when it goes to resolve the intents that were already cleaned up. These AbortSpan entries would be fully abandoned and have to wait out the GC.

Similarly, in the second case, the transaction might have committed. Here, the pushee might hit an intent and the txn coordinator might clean up and auto-GC its txn record before the pushee arrives at the txn record. Once the pushee gets there, it would mistake the txn for aborted (by design) and proceed to write an AbortSpan record where the intent it had once observed had been (not by design).

We can tell both of these cases by simply recognizing whether intent resolution actually succeeds. If intent resolution doesn't find an intent, then we might be in either case. That's fine, because we only need to ever poison the abort span if we actually remove an intent that could confuse a zombie transaction.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

The fact that we clear when `!Poison` seems problematic. This isn't new behavior, but it looks worth fixing (though not necessarily in this PR).

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 15 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-:-Lve_PcV9Ri0s048bGiw:b-bhp63q)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/storage/batcheval/cmd_resolve_intent.go, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-Lve_7FI6mH8xUom-PA7:-Lve_7FI6mH8xUom-PA8:b4nthj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e578f4eb6d80ac8953f84fc8f66f294fdd8d6f/pkg/storage/batcheval/cmd_resolve_intent.go#L42)):*
> ```Go
> 		txnID = t.IntentTxn.ID
> 	}
> 	if status == roachpb.ABORTED {
> ```

Could add a comment here that we won't even always write the key in this case, but we can't know this from this code. Your call
___
*[pkg/storage/batcheval/transaction_test.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LveXaXo0icfK92SDied:-LveXaXo0icfK92SDiee:bubr558) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a31ef2747cc966eebfd8a63e37962d053f957c4/pkg/storage/batcheval/transaction_test.go#L190)):*
> ```Go
> 		{
> 			// NOTE: this request doesn't make sense, but we handle it. An abort
> 			// span shouldn't be present if the transaction is still committable.
> ```

In practice the commit would run into the abort span, but this check is outside of the code being tested, right?
___
*[pkg/storage/batcheval/transaction_test.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LveZ7APAlZF145Qd-A4:-LveZ7APAlZF145Qd-A5:b6uw4cr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a31ef2747cc966eebfd8a63e37962d053f957c4/pkg/storage/batcheval/transaction_test.go#L306)):*
> ```Go
> 		},
> 		{
> 			name:   "resolve intent, txn aborted, no poison, intent missing, abort span present",
> ```

Isn't this problematic? If a txn gets pushed first but the corresponding non-poisoning ResolveIntent gets delayed, then the txn gets aborted and poisoning happens, won't the delayed request unpoison accidentally?

The direct blame is broken due to code movement, but I think this is a problem I introduced at some point. Worth filing an issue. The bool should (as always) have been an enum `NOOP, CLEAR, POISON`.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42765)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @tbg)

___
*[pkg/storage/batcheval/cmd_resolve_intent.go, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-Lve_7FI6mH8xUom-PA7:-LvqzyyVDK3MqgXDUSKy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e578f4eb6d80ac8953f84fc8f66f294fdd8d6f/pkg/storage/batcheval/cmd_resolve_intent.go#L42)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Could add a comment here that we won't even always write the key in this case, but we can't know this from this code. Your call
</blockquote></details>

Done.
___
*[pkg/storage/batcheval/transaction_test.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LveXaXo0icfK92SDied:-Lvr-0kf67LVUFsPdihR:bmblsmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a31ef2747cc966eebfd8a63e37962d053f957c4/pkg/storage/batcheval/transaction_test.go#L190)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

In practice the commit would run into the abort span, but this check is outside of the code being tested, right?
</blockquote></details>

Well, an abort span should be possible to write unless the txn is already aborted, in which case the EndTxn would necessarily fail.
___
*[pkg/storage/batcheval/transaction_test.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LveZ7APAlZF145Qd-A4:-Lvr0dtn0-pYI7Efj7hO:b-xf7k0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a31ef2747cc966eebfd8a63e37962d053f957c4/pkg/storage/batcheval/transaction_test.go#L306)):*
> If a txn gets pushed first but the corresponding non-poisoning ResolveIntent gets delayed

I don't think there's a case where a PushTxn triggers a ResolveIntent without a Poison flag (even for PUSH_TIMESTAMP), so I think the only case where a ResolveIntent request can have `Poison=false` is when it was initiated by the transaction coordinator itself or when it was initiated by GC. Maybe I'm missing something.

> The fact that we clear when !Poison seems problematic. 

Isn't this kind of the point? When !Poison, we're saying that we 're operating as the transaction and we're aware of the ABORT so we're able to clear. When were you thinking we'd set `Poison = NOOP`?

**Review by andreimatei — APPROVED** [review]
LGTM good stuff

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-:-Lvs2Ide6l4OUlzrDoA4:bs7d4m0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 521 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-Lvs-Eh_B3dh2AXvKAnd:-Lvs-Eh_B3dh2AXvKAne:bcp56it) ([raw file](https://github.com/cockroachdb/cockroach/blob/6370a65f20bb6d0c3202f4ab904adc62cbb05eb1/pkg/storage/batcheval/cmd_end_transaction.go#L521)):*
> ```Go
> 	}
> 
> 	if WriteAbortSpanOnResolve(txn.Status) {
> ```

I like `txn.Status == ABORTED` better. In fact I'd get rid of this function.
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 522 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-Lvs-RS21tbYm1tFAl9u:-Lvs-RS21tbYm1tFAl9v:b-k5bszf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6370a65f20bb6d0c3202f4ab904adc62cbb05eb1/pkg/storage/batcheval/cmd_end_transaction.go#L522)):*
> ```Go
> 
> 	if WriteAbortSpanOnResolve(txn.Status) {
> 		if err := SetAbortSpan(ctx, evalCtx, batch, ms, txn.TxnMeta, args.Poison); err != nil {
> ```

please add a comment that this surprisingly might clear the entry. Or better yet, split the `SetAbortSpan()` function in two. I think this function is the textbook example of a bool argument anti-pattern.
___
*[pkg/storage/batcheval/transaction_test.go, line 27 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvueWAjMdv5q0jIn6:-LvrvueWAjMdv5q0jIn7:bysh37l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L27)):*
> ```Go
> // TestSetAbortSpan tests the different ways that request can set, update, and
> // delete AbortSpan entries.
> func TestSetAbortSpan(t *testing.T) {
> ```

excellent test
___
*[pkg/storage/batcheval/transaction_test.go, line 43 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvruoKR-g2vZKKPrjXc:-LvruoKR-g2vZKKPrjXd:b-5oj80o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L43)):*
> ```Go
> 
> 	txn := roachpb.MakeTransaction("test", txnKey, 0, hlc.Timestamp{WallTime: 1}, 0)
> 	txnAbortSpanEntry := roachpb.AbortSpanEntry{
> ```

maybe name this `newTxnAbortSpanEntry`
___
*[pkg/storage/batcheval/transaction_test.go, line 50 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvruDMO1L1vooqIL_t7:-LvruDMP87avvqHobv79:b-wgcnj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L50)):*
> ```Go
> 	// Used to detect updates to the AbortSpan entry.
> 	txnPrev := txn.Clone()
> 	txnPrev.WriteTimestamp.Add(-1, 0)
> ```

can you remind the reader if the priority and write timestamp matter for anything or if they're just testing artifacts?
___
*[pkg/storage/batcheval/transaction_test.go, line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvF9G7J9jMkWI1E6G:-LvrvF9G7J9jMkWI1E6H:b-pr9voy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L191)):*
> ```Go
> 			// NOTE: this request doesn't make sense, but we handle it. An abort
> 			// span shouldn't be present if the transaction is still committable.
> 			name:   "end txn, commit, no poison, abort span present",
> ```

let's crash in this case
___
*[pkg/storage/batcheval/transaction_test.go, line 212 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvPKv2yGI7zVtUCg-:-LvrvPKv2yGI7zVtUCg0:b-5euhqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L212)):*
> ```Go
> 			// NOTE: this request doesn't make sense, but we handle it. An EndTxn
> 			// should never pass Commit = true and Poison = true.
> 			name:   "end txn, commit, poison, abort span present",
> ```

let's crash
___
*[pkg/storage/batcheval/transaction_test.go, line 262 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvieRCuKUt3tS6JLT:-LvrvieRCuKUt3tS6JLU:bt6yqd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L262)):*
> ```Go
> 			name: "resolve intent, txn pending, poison, intent missing, abort span missing",
> 			run: func(b engine.ReadWriter, rec EvalContext) error {
> 				return resolveIntent(b, rec, roachpb.PENDING, true /* poison */)
> ```

resolving an intent with PENDING doesn't make sense, right? Let's crash.

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42765)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @tbg)

___
*[pkg/storage/batcheval/transaction_test.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LveZ7APAlZF145Qd-A4:-Lvt9OXt-H7bLK9G7xXV:b7txfxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a31ef2747cc966eebfd8a63e37962d053f957c4/pkg/storage/batcheval/transaction_test.go#L306)):*
> I don't think there's a case where a PushTxn triggers a ResolveIntent without a Poison flag (even for PUSH_TIMESTAMP), 

Heh, it turns out you're right, but only because I had this same thought in 2017 and made that change:

https://github.com/cockroachdb/cockroach/blob/844eac452509fcafcedff6ab798e8e8e0376695a/pkg/storage/intentresolver/intent_resolver.go#L265-L278

I was just mildly confused how this all worked (if we push an intent timestamp, certainly the txn should not get a TransactionAbortedError?) but it looks like even before your PR we only mutate the abort span when aborting. So in a roundabout way, we have already implemented the NOOP option. I don't love the messiness of this, but it seems to be working as intended already: if we're not removing intents, Poison is effectively ignored.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42765)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @tbg)

___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 521 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-Lvs-Eh_B3dh2AXvKAnd:-Lx8bMwX20GVvUC1UmDL:b-1ctzhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6370a65f20bb6d0c3202f4ab904adc62cbb05eb1/pkg/storage/batcheval/cmd_end_transaction.go#L521)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I like `txn.Status == ABORTED` better. In fact I'd get rid of this function.
</blockquote></details>

But there's more to this function that just `txn.Status == ABORTED`.
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 522 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-Lvs-RS21tbYm1tFAl9u:-Lx8bf2dDvpY7JjjagVO:bfc1fnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6370a65f20bb6d0c3202f4ab904adc62cbb05eb1/pkg/storage/batcheval/cmd_end_transaction.go#L522)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please add a comment that this surprisingly might clear the entry. Or better yet, split the `SetAbortSpan()` function in two. I think this function is the textbook example of a bool argument anti-pattern.
</blockquote></details>

How about renaming it to `UpdateAbortSpan`? I'd rather not pull the condition out to all callers and force them to make decisions that don't really concern them.
___
*[pkg/storage/batcheval/transaction_test.go, line 43 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvruoKR-g2vZKKPrjXc:-Lx8cfxZBxa8Pbui-7si:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L43)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe name this `newTxnAbortSpanEntry`
</blockquote></details>

Done.
___
*[pkg/storage/batcheval/transaction_test.go, line 50 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvruDMO1L1vooqIL_t7:-Lx8c_Re1sRLy9YVvox2:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L50)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you remind the reader if the priority and write timestamp matter for anything or if they're just testing artifacts?
</blockquote></details>

Good idea, done.
___
*[pkg/storage/batcheval/transaction_test.go, line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvF9G7J9jMkWI1E6G:-Lx8e4pw3IVkdKuFTNov:bu75gub) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L191)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

let's crash in this case
</blockquote></details>

If we're all about the KV layer providing an external API (which it sounds like we are) then I don't think we should crash on user input. This case doesn't do anything wrong, we just wouldn't even get to batch evaluation if there's an abort span present.
___
*[pkg/storage/batcheval/transaction_test.go, line 212 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvPKv2yGI7zVtUCg-:-Lx8eZSw9QihKLi9Pf9F:bc331lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L212)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

let's crash
</blockquote></details>

Again, I don't think we should crash, but in this case, I could see some extra input validation and rejecting the request. Done.
___
*[pkg/storage/batcheval/transaction_test.go, line 262 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvieRCuKUt3tS6JLT:-Lx8dr0a20wfVkfJ1DYY:blf6da7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L262)):*
> resolving an intent with PENDING doesn't make sense, right?

No, it does. That's what happens during a PUSH_TIMESTAMP push.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42765)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/storage/batcheval/transaction_test.go, line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvF9G7J9jMkWI1E6G:-LxAFdKm3JcYzKl5ooYb:b-bmz0z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L191)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we're all about the KV layer providing an external API (which it sounds like we are) then I don't think we should crash on user input. This case doesn't do anything wrong, we just wouldn't even get to batch evaluation if there's an abort span present.
</blockquote></details>

Exactly - we wouldn't get to batch evaluation if there's an abort span. Even if the KV layer were to be treated as an "external" API (where I'd litigate the meaning of "external"), the KV layer isn't the request evaluation functions. Committing a txn with an abort span entry set would be a bug, and a bad one (wouldn't it?). So what are we testing here? The test says `// Not aborted, don't touch abort span.`. What does "not aborted" mean? The txn *is* aborted. Whether or not the `EndTransaction` updates the abort span or not in this case seems like a frivolous concern.
Do you like this test? If I understand it correctly, I think we should get rid of it and just leave a note here about this case not being possible. And if it's easy enough, I do think I'd make sense to refuse the request (or crash), I guess at the `evaluateBatch()` level. But that higher level function is beyond the concern of this test.

**Comment by knz** [comment]
I haven't looked into this PR yet but reflecting on the last two comments I thought I'd share my views:

1) if an API needs to reject some invalid combinations of inputs and it was not designed to return `error`, then `panic()` is the next best thing before `log.Fatal` or `os.Exit`.

2) in my book it's perfectly a-OK to implement unit tests that verify that an API rejects invalid input combinations. In this case, the test could ascertain that a panic is indeed thrown.

3) we've started to grow a habit to throw `error` objects using `panic()`, instead of strings, and this will pay dividend down the line. If done here, it also enables the test to verify the contents of the exception being thrown.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42765)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @tbg)

___
*[pkg/storage/batcheval/transaction_test.go, line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvF9G7J9jMkWI1E6G:-LxbVI4F-zh47DTDf_kg:blvun3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L191)):*
> What does "not aborted" mean?

Would you like it better if it said "not aborting"?

> I think we should get rid of it and just leave a note here about this case not being possible

We could get rid of the test case, but I think there's value in enumerating all combinations of inputs here and just explaining the test cases that should never be hit in practice. It makes it easier to ensure that we've exhaustively tested all valid cases and at least considered the validity of invalid ones. What's the cost of keeping these two cases?

> And if it's easy enough, I do think I'd make sense to refuse the request (or crash)

We certainly don't want to read from RocksDB just to perform a local assertion that is already caught further up the stack.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-:-LxbkrRY69fJKi35SFXQ:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 521 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-Lvs-Eh_B3dh2AXvKAnd:-LxbkkNb2FgY7on4-1HC:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6370a65f20bb6d0c3202f4ab904adc62cbb05eb1/pkg/storage/batcheval/cmd_end_transaction.go#L521)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

But there's more to this function that just `txn.Status == ABORTED`.
</blockquote></details>

ack
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 522 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-Lvs-RS21tbYm1tFAl9u:-LxbkJ-eBC47Bt55p8bD:b-3us6r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6370a65f20bb6d0c3202f4ab904adc62cbb05eb1/pkg/storage/batcheval/cmd_end_transaction.go#L522)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How about renaming it to `UpdateAbortSpan`? I'd rather not pull the condition out to all callers and force them to make decisions that don't really concern them.
</blockquote></details>

`UpdateAbortSpan` sounds good.
___
*[pkg/storage/batcheval/transaction_test.go, line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvF9G7J9jMkWI1E6G:-LxbgH683_gjScaTgmGw:bayju9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L191)):*
> What's the cost of keeping these two cases?

The biggest cost is paid when this test fails one day and I start wracking my brain about what it is testing.
If you want to enumerate, enumerate it as a comment. The way I see it, the only test to write (if any) is a test that the request is rejected - at whatever layer.
But I'll shut up now.

> We certainly don't want to read from RocksDB just to perform a local assertion that is already caught further up the stack.

Right, I wasn't suggesting we check anything in `EndTxn`. I was saying we should do it in `evaluateBatch()` - as I now see that we already do.
___
*[pkg/storage/batcheval/transaction_test.go, line 212 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvPKv2yGI7zVtUCg-:-LxbjED-B3GSWpy9aIt1:b-dvobdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L212)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Again, I don't think we should crash, but in this case, I could see some extra input validation and rejecting the request. Done.
</blockquote></details>

Thanks. I think the comment is no longer necessary on this test and the one above, now that we expect an error. Or change it to `It is an error to...`.
___
*[pkg/storage/batcheval/transaction_test.go, line 262 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvieRCuKUt3tS6JLT:-LxbjVW727N-0X5crR0o:bnqc91v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L262)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> resolving an intent with PENDING doesn't make sense, right?

No, it does. That's what happens during a PUSH_TIMESTAMP push.
</blockquote></details>

So what "doesn't make sense" here then? Can you add more words to the comment?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42765)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @tbg)

___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 522 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-Lvs-RS21tbYm1tFAl9u:-LxbmId23wsNxHLmMmcv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6370a65f20bb6d0c3202f4ab904adc62cbb05eb1/pkg/storage/batcheval/cmd_end_transaction.go#L522)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`UpdateAbortSpan` sounds good.
</blockquote></details>

Done.
___
*[pkg/storage/batcheval/transaction_test.go, line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvF9G7J9jMkWI1E6G:-LxbsV5J5Mwk4qDfdaDJ:bclsha6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L191)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> What's the cost of keeping these two cases?

The biggest cost is paid when this test fails one day and I start wracking my brain about what it is testing.
If you want to enumerate, enumerate it as a comment. The way I see it, the only test to write (if any) is a test that the request is rejected - at whatever layer.
But I'll shut up now.

> We certainly don't want to read from RocksDB just to perform a local assertion that is already caught further up the stack.

Right, I wasn't suggesting we check anything in `EndTxn`. I was saying we should do it in `evaluateBatch()` - as I now see that we already do.
</blockquote></details>

Ok, I removed the test cases.
___
*[pkg/storage/batcheval/transaction_test.go, line 212 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvPKv2yGI7zVtUCg-:-LxbmZmn8YfRl-kPd62C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L212)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Thanks. I think the comment is no longer necessary on this test and the one above, now that we expect an error. Or change it to `It is an error to...`.
</blockquote></details>

Done.
___
*[pkg/storage/batcheval/transaction_test.go, line 262 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-LvrvieRCuKUt3tS6JLT:-LxbnAZMCzRIrMscGJwc:b-sa8y67) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aaf30009540d58b00ea747f443e992c34513ce7/pkg/storage/batcheval/transaction_test.go#L262)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

So what "doesn't make sense" here then? Can you add more words to the comment?
</blockquote></details>

I removed those comments. They actually do make sense because of the complexity @tbg brought up above.

**Review by andreimatei — COMMENTED** [review]
:ship: it

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42765#-:-LxbwqtyDO4MlNnz3utR:biypm1u)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @tbg)

**Comment by tbg** [comment]
In light of recent events, how nervous would we be about backporting this?

**Comment by nvanbenschoten** [comment]
I feel ok about backporting this to v19.2. Almost all of this was testing, and the few non-testing changes that went in here seem safe.

Here's the PR: https://github.com/cockroachdb/cockroach/pull/45553. It was mostly clean, and the parts that weren't were because of renames and other non-behavioral changes.

**Pull request merged**
