### PR TITLE
kvserver: add w-amp metric for each store

### PR DESCRIPTION
**Pull request by itsbilal**
Previously, we did not have a dedicated metric to report the w-amp reported by Pebble for each level. This change adds a write-amp metric to specifically measure and report the w-amp sum reported by Pebble as part of its LevelMetrics.

Epic: none

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131963)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[`pkg/kv/kvserver/metrics.go` line 767 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131963#-O8OBELq9g1i1kz0nRHv:-O8OBELq9g1i1kz0nRHw:bnqznyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/269ded938d6c343188272310aa2f8ff7d7a3fea4/pkg/kv/kvserver/metrics.go#L767)):*
> ```Go
> 		Help: `Running measure of write-amplification.
> 
> Write amplification is measured as the ratio of bytes written to disk over the life of a store
> ```

This reads "bytes written to disk over the life of a store" which doesn't sound right.

Maybe "ratio of bytes written to disk relative to the logical bytes stored, over the life of a store"

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131963)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`pkg/kv/kvserver/metrics.go` line 767 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131963#-O8OBELq9g1i1kz0nRHv:-O8OScOFDWyzE07ISj9k:b-376vyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/269ded938d6c343188272310aa2f8ff7d7a3fea4/pkg/kv/kvserver/metrics.go#L767)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This reads "bytes written to disk over the life of a store" which doesn't sound right.

Maybe "ratio of bytes written to disk relative to the logical bytes stored, over the life of a store"
</blockquote></details>

Done. Good catch!

**Review by RaduBerinde — APPROVED** [review]
:lgtm:  Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131963#-:-O8Ofc7R6bPqH8u-Wsow:b-e7bejd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Comment by itsbilal** [comment]
TFTR! 

bors r=RaduBerinde

**Pull request merged**
