### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by xiaoyulei**
#1846

### CODE REVIEW

**Comment by MBerhault** [comment]
LGTM

**Comment by bdarnell** [comment]
LGTM, but it's not a typo: it's regex syntax.

**Comment by YuleiXiao** [comment]
@MBerhault hi, it looks like ci failed. But I only modify design.md. Can it affect ci?

**Comment by bdarnell** [comment]
It's a bug in the CI script; I'll go ahead and merge.

**Comment by YuleiXiao** [comment]
@bdarnell Yes, I guess so. But there are two different expressions. meta{1,2} and meta[12]. 
When I saw it I feel a little confuse. So now make it only one.

**Pull request merged**
