### PR TITLE
sql: allow FKs to use the prefix of an index

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8059)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/create.go, line 539 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNmY00VHiL7RmleH-v2:-KNmY00VHiL7RmleH-v3:543694733) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/create.go#L539)):*
> ```Go
> }
> 
> func matchesIndex(cols []sqlbase.ColumnDescriptor, idx sqlbase.IndexDescriptor, exact bool) bool {
> ```

A function comment explaining `exact` would be useful. Or - it might make the callsites more readable if we left this function alone and added a `matchesIndexPrefix`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-:-KNmZ2kCMYfwQisHVtxS:1417088721)*

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/create.go, line 539 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNmY00VHiL7RmleH-v2:-KNnCzXzauCZPTh8tDcC:2060355258) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/create.go#L539)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> A function comment explaining `exact` would be useful. Or - it might make the callsites more readable if we left this function alone and added a `matchesIndexPrefix`
</details>
Done.

I thought about a second sig, or a enum, but since this is only called in one method, it just seemed like overkill.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by paperstreet** [comment]
sorry about the delay, I wrote my comments a while ago but apparently forgot to publish. I agree with Radu on the matchesIndex bool. enum is my preferred resolution

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 539 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqv-tTV4kzmMREyj-p:-KNqv-tTV4kzmMREyj-q:717508936) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/create.go#L539)):*
> ```Go
> }
> 
> func matchesIndex(cols []sqlbase.ColumnDescriptor, idx sqlbase.IndexDescriptor, exact bool) bool {
> ```

should probably make this bool an `indexMatchType` or something

---

*[sql/fk.go, line 110 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqvsP-2HBPwXseaQY-:-KNqvsP-2HBPwXseaQY0:413031654) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L110)):*
> ```Go
> 	for _, fk := range fks[idx] {
> 		nulls := true
> 		for i := range fk.searchIdx.ColumnIDs[:fk.prefixLen] {
> ```

`for i, colID` or searchColID

---

*[sql/fk.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqvyUrgPduMuYqfTC2:-KNqvyUrgPduMuYqfTC3:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L127)):*
> ```Go
> 		if found == nil {
> 			fkValues := make(parser.DTuple, fk.prefixLen)
> 			for i := range fk.searchIdx.ColumnIDs[:fk.prefixLen] {
> ```

ditto

---

*[sql/fk.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqw0fhsx0vt8uLk2m6:-KNqw0fhsx0vt8uLk2m7:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L181)):*
> ```Go
> 			}
> 			fkValues := make(parser.DTuple, fk.prefixLen)
> 			for i := range fk.searchIdx.ColumnIDs[:fk.prefixLen] {
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-:-KNqvPHw9PWV_HMlF-t_:420958224)*

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 539 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqv-tTV4kzmMREyj-p:-KNr-LNv8V-BtUuXJNNE:705786362) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/create.go#L539)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> should probably make this bool an `indexMatchType` or something
</details>
I'm not convinced the extra symbols and the added code of an enum adds much here -- the benefit of that approach is more information at the callsites, but this is only called in one function, immediately above the definition.

---

*[sql/fk.go, line 110 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqvsP-2HBPwXseaQY-:-KNqyd1ILIZOcTmtshCr:-1579137682) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L110)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> `for i, colID` or searchColID
</details>
well, not strictly in the scope of this change, but at one point I recall a style preference, if you were using the slice index to do other things, of using the single-bind form such that you had parity, e.g. `foo[i] = bar[i]` is clearer that there's a 1:1 mapping happening whereas to convince yourself of that when reading `foo[i] = x`, you'd need to go find the bind of `x`.

In this instance though, this is now just a trivial `for i := 0; i < fk.prefixLen`loop and don't need range at all anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by dt** [comment]
bah, somehow rebased #8067 into this and made conflict mess. fixed.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/fk.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqvyUrgPduMuYqfTC2:-KNr4V_UEDKNJdCcw4TN:-1296331409) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L127)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> ditto
</details>
Done (simple for loop)

---

*[sql/fk.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqw0fhsx0vt8uLk2m6:-KNr4VwjndBdWOv6Rw5q:-1531567969) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L181)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> ditto
</details>
Done (simple for loop).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-:-KNr4bawVPpx10qCK1XZ:-107561166)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 539 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqv-tTV4kzmMREyj-p:-KNr51hdgtNXuAIN82I7:80889943) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/create.go#L539)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I'm not convinced the extra symbols and the added code of an enum adds much here -- the benefit of that approach is more information at the callsites, but this is only called in one function, immediately above the definition.
</details>
moved it inline so it isn't even a pkg-level symbol anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r1, 2 of 7 files at r2, 4 of 5 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/fk.go, line 110 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqvsP-2HBPwXseaQY-:-KNr78DPFXSQrwuqH82W:-2101228861) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L110)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> well, not strictly in the scope of this change, but at one point I recall a style preference, if you were using the slice index to do other things, of using the single-bind form such that you had parity, e.g. `foo[i] = bar[i]` is clearer that there's a 1:1 mapping happening whereas to convince yourself of that when reading `foo[i] = x`, you'd need to go find the bind of `x`.
> 
> In this instance though, this is now just a trivial `for i := 0; i < fk.prefixLen`loop and don't need range at all anymore.
</details>
Wait, why is `i` needed at all? can't this be:
```
for _, colID := range fk.searchIdx.ColumnIDs {
  found, ok := fk.ids[colID]
}
```

---

*[sql/fk.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqvyUrgPduMuYqfTC2:-KNr7S4KxsH5yCIPXftB:1146054081) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L127)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Done (simple for loop)
</details>
everyone's got an opinion but in this case i think the double-bind form would be clearer. current triple-nesting brackets down here.

---

*[sql/fk.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqw0fhsx0vt8uLk2m6:-KNr7_rICTCPqJTTib1M:1745567667) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L181)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Done (simple for loop).
</details>
(what i said above)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by dt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/fk.go, line 110 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqvsP-2HBPwXseaQY-:-KNr83ecBjBIJiXeuHcW:-458793003) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L110)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Wait, why is `i` needed at all? can't this be:
> ```
> for _, colID := range fk.searchIdx.ColumnIDs {
>   found, ok := fk.ids[colID]
> }
> ```
</details>
I don't particularly want to allocate a new slice header just to call `range` it where a plain 0 to `x` loop would work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by tamird** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/fk.go, line 110 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqvsP-2HBPwXseaQY-:-KNr973BrZe44WtfGyl_:1006119715) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L110)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I don't particularly want to allocate a new slice header just to call `range` it where a plain 0 to `x` loop would work?
</details>
Are you suggesting that reslicing a slice allocates?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by paperstreet** [comment]
I agree with Tamir's followups.

Anyway, I'm not really sure why you seem to be digging your feet in over these particular issues, but I don't care enough about them to hold up the review. lgtm

---

Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 481 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNrBa3NtHZHiF_RZsHx:-KNrBa3NtHZHiF_RZsHy:-195711612) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b935e78e6079dbce75b7718fccaff987820a2f8/sql/create.go#L481)):*
> ```Go
> 	// Referencing cols have no uniqueness requirement and thus may match a
> 	// strict prefix of an index.
> 	matchesIndex := func(cols []sqlbase.ColumnDescriptor, idx sqlbase.IndexDescriptor, exact bool) bool {
> ```

FWIW, this would have been idiomatic in scala, but in go, it makes me assume it's here because you needed it to close over something. I think it was better at package level and with the enum, but ¯\_(ツ)_/¯

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-:-KNrAx5Ux0H1t4xGwNaN:1428973809)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/fk.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqw0fhsx0vt8uLk2m6:-KNrCffle38pxk8v3cTx:-367817846) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L181)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> (what i said above)
</details>
I would like to suggest painting this bike shed in the color `for i := range fkValues` here (same above). It's fine to merge with whatever version though :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by dt** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 481 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNrBa3NtHZHiF_RZsHx:-KNrJ9QusYHdU0a-eQLn:158935826) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b935e78e6079dbce75b7718fccaff987820a2f8/sql/create.go#L481)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> FWIW, this would have been idiomatic in scala, but in go, it makes me assume it's here because you needed it to close over something. I think it was better at package level and with the enum, but ¯\_(ツ)_/¯
</details>
fine, made it an enum, but I still don't want to add more package level symbols to `sql` just for a helper that's only called in one place.

---

*[sql/fk.go, line 110 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqvsP-2HBPwXseaQY-:-KNr9hyK4OB8JqI9MEr9:433519031) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L110)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Are you suggesting that reslicing a slice allocates?
</details>
Done. (reslicing to call `range` with a double-bind).

You're right, the new slice header is just on the stack, so it just has to compute it. I tied a little demo with simple for loop vs a re-slice and range, and it looks like its only ~3ns (~20%) slower, so I don't really care.

---

*[sql/fk.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqvyUrgPduMuYqfTC2:-KNrHx39NlsqZiO4Irkx:-175661972) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L127)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> everyone's got an opinion but in this case i think the double-bind form would be clearer. current triple-nesting brackets down here.
</details>
Done (double bind)

---

*[sql/fk.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNqw0fhsx0vt8uLk2m6:-KNrHqvMwQxz85xE1_hG:-175661972) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c42a8303a24f93e07b389cd2ca0a64a6497ded/sql/fk.go#L181)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I would like to suggest painting this bike shed in the color `for i := range fkValues` here (same above). It's fine to merge with whatever version though :)
</details>
Done (double bind)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by tamird** [comment]
Thanks!

---

Reviewed 1 of 2 files at r5.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[sql/fk.go, line 264 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNrK5GbfhaoyprIRB1k:-KNrK5GbfhaoyprIRB1l:1851248868) ([raw file](https://github.com/cockroachdb/cockroach/blob/008c3a44a9ee2ec63946074db9126ca24586835e/sql/fk.go#L264)):*
> ```Go
> 	nulls := true
> 	for i := range writeIdx.ColumnIDs[:b.prefixLen] {
> 		if found, ok := colMap[writeIdx.ColumnIDs[i]]; ok {
> ```

could save another bracket here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-:-KNrK8-YhGgqXbmePvM-:-1834867277)*

**Comment by dt** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[sql/fk.go, line 264 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNrK5GbfhaoyprIRB1k:-KNrKtcFADNRNduOwOtw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/008c3a44a9ee2ec63946074db9126ca24586835e/sql/fk.go#L264)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> could save another bracket here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6.
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by tamird** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[sql/fk.go, line 246 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNrLMdeqCd6T4FND7b0:-KNrLMdeqCd6T4FND7b1:2032447472) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a768e74f1a3dc24a2b1358835a0ab85007d812/sql/fk.go#L246)):*
> ```Go
> 	}
> 	b.prefixLen = len(searchIdx.ColumnIDs)
> 	if len(writeIdx.ColumnIDs) < b.prefixLen {
> ```

nit: yoda condition, keep b.prefixLen on the LHS consistently

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Comment by tamird** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/fk.go, line 246 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059#-KNrLMdeqCd6T4FND7b0:-KNrLaqNBzpWJUST7Sd4:-927996834) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a768e74f1a3dc24a2b1358835a0ab85007d812/sql/fk.go#L246)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: yoda condition, keep b.prefixLen on the LHS consistently
</details>
on second thought...not important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8059)*

**Pull request merged**
