### PR TITLE
sqlccl: ensure session revival cluster setting propagates to tenant

### LINKED ISSUE #128125: pkg/ccl/testccl/sqlccl/sqlccl_test: TestShowTransferState failed
pkg/ccl/testccl/sqlccl/sqlccl_test.TestShowTransferState [failed](https://mesolite.cluster.engflow.com/invocations/default/4adc367d-de04-48f6-982f-a16f4e3808bd?testReportRun=1&testReportShard=13&testReportAttempt=1#targets-Ly9wa2cvY2NsL3Rlc3RjY2wvc3FsY2NsOnNxbGNjbF90ZXN0) on master @ [78fa126dfc749e620c28531c1659e35bf98034ec](https://github.com/cockroachdb/cockroach/commits/78fa126dfc749e620c28531c1659e35bf98034ec):

```
=== RUN   TestShowTransferState
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestShowTransferState246603600
    test_log_scope.go:81: use -show-logs to present logs inline
    show_transfer_state_test.go:268: -- test log scope end --
test logs left over in: outputs.zip/logTestShowTransferState246603600
--- FAIL: TestShowTransferState (2.05s)
=== RUN   TestShowTransferState/errors
    --- FAIL: TestShowTransferState/errors (0.02s)
=== RUN   TestShowTransferState/errors/root_user
    show_transfer_state_test.go:219: 
        	Error Trace:	pkg/ccl/testccl/sqlccl/sqlccl_test/pkg/ccl/testccl/sqlccl/show_transfer_state_test.go:219
        	Error:      	Not equal: 
        	            	expected: "cannot create token for root user"
        	            	actual  : "session revival tokens are not supported on this cluster"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-cannot create token for root user
        	            	+session revival tokens are not supported on this cluster
        	Test:       	TestShowTransferState/errors/root_user
        --- FAIL: TestShowTransferState/errors/root_user (0.00s)
=== RUN   TestShowTransferState/successful_transfer
    show_transfer_state_test.go:163: 
        	Error Trace:	pkg/ccl/testccl/sqlccl/sqlccl_test/pkg/ccl/testccl/sqlccl/show_transfer_state_test.go:163
        	Error:      	Received unexpected error:
        	            	failed to connect to ``host=127.0.0.1 user=testuser database=``: server error (ERROR: session revival tokens are not supported on this cluster (SQLSTATE 28000))
        	Test:       	TestShowTransferState/successful_transfer
    --- FAIL: TestShowTransferState/successful_transfer (0.01s)
=== RUN   TestShowTransferState/with_transfer_key
    show_transfer_state_test.go:142: 
        	Error Trace:	pkg/ccl/testccl/sqlccl/sqlccl_test/pkg/ccl/testccl/sqlccl/show_transfer_state_test.go:142
        	Error:      	Should be false
        	Test:       	TestShowTransferState/with_transfer_key
    --- FAIL: TestShowTransferState/with_transfer_key (0.20s)
=== RUN   TestShowTransferState/without_transfer_key
    show_transfer_state_test.go:78: 
        	Error Trace:	pkg/ccl/testccl/sqlccl/sqlccl_test/pkg/ccl/testccl/sqlccl/show_transfer_state_test.go:78
        	Error:      	Should be false
        	Test:       	TestShowTransferState/without_transfer_key
        	Messages:   	expected null error, got session revival tokens are not supported on this cluster
    --- FAIL: TestShowTransferState/without_transfer_key (0.02s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=13</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestShowTransferState.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

### PR DESCRIPTION
**Pull request by annrpom**
This patch adds a `SucceedsSoon` in `TestShowTransferState` to ensure that our `server.user_login.session_revival_token.enabled` cluster setting has actually propagated to the tenant during
`SHOW TRANSFER STATE`.

Fixes: #128125

Release note: None

### CODE REVIEW

**Comment by annrpom** [comment]
draft since i have not been able to repro the failure with

```
./dev test pkg/ccl/testccl/sqlccl --stress -f=TestShowTransferState
```

**Comment by annrpom** [comment]
i was still not able to repro with:

https://github.com/cockroachdb/cockroach/pull/132119#issuecomment-2397867187

any advice? i do think Jay's comment (the cluster setting has not propagated to the tenant yet) is very likely to be the issue, though

**Review by rafiss — APPROVED** [review]
This seems like a safe change to make regardless. lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132119#-:-O8me5DQ3LRWugmyV36L:be6oigl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by annrpom** [comment]
oki dokie crossing fingies

TFTR! ('-')7
bors r=rafiss

**Pull request merged**
