### PR TITLE
util/timeutil: add an RWMutex around nowFunc

### PR DESCRIPTION
**Pull request by cuongdo**
It's difficult to use `timeutil.SetTimeOffset` and `timeutil.Now`
without adding data races, because `timeutil.nowFunc` lacks synchronized
access. This fixes that by wrapping accesses to `nowFunc` with a
`RWMutex`. By far, the common case for production code will be to call
`Now`, which now grabs a shared read lock. So, this shouldn't introduce
noticeable blocking.

`make bench` shows no statistically significant changes in performance.

Also reverts a workaround for the prior lack of synchronization in
`timeutil`.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6357)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
I want to put it out there that the intention was never for SetTimeOffset to be exported at all. Note that it was done seemingly randomly in 08b34d887e499c2e3149e795b592abe785380f6f - I would much rather see that reverted than to see this type of proliferation of its use.

The approach taken in this PR culminates in us reimplementing something like https://godoc.org/github.com/101loops/clock.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6357#-:-KGOBQWqGWeyEOGLCECx:-620762370)*

**Comment by tschottdorf** [comment]
I'm with @tamird. Not sure what this is used for, but certainly not in the original spirit.

**Comment by cuongdo** [comment]
From looking at `timeutil/time.go`, I'm not clear what the spirit of this code is meant to be. However, given the feedback, it's clear this PR isn't taking the right approach, so I'll abandon it.

**Comment by tschottdorf** [comment]
@cuongdo this was introduced a) to provide some scrambling of the process-wide clock (i.e. not changed during process runtime), for use in acceptance tests and b) to try to catch problems with the local clock (where again, you wouldn't tamper with it during runtime).

If for some reason we want to muck with system time during tests, hopefully we can do that through a `manualClock` or we should consider not using a global clock at all (but instead making the physical clock part of the configuration as well). Either of those is preferable to using a global which is modified in various parts of the code which hope (but can't really prove) that they're the only user at the time.

**Comment by cuongdo** [comment]
That makes sense to me, though it isn't evident from reading the function
comments in `timeutil/time.go`.

**Comment by tschottdorf** [comment]
Agreed.

On Thu, Apr 28, 2016 at 9:02 AM Cuong Do <notifications@github.com> wrote:

> That makes sense to me, though it isn't evident from reading the function
> comments in `timeutil/time.go`.
>
> On Thu, Apr 28, 2016 at 8:37 AM Tobias Schottdorf <
> notifications@github.com>
> wrote:
>
> > @cuongdo <https://github.com/cuongdo> this was introduced a) to provide
> > some scrambling of the process-wide clock (i.e. not changed during
> process
> > runtime), for use in acceptance tests and b) to try to catch problems
> with
> > the local clock (where again, you wouldn't tamper with it during
> runtime).
> >
> > If for some reason we want to muck with system time during tests,
> > hopefully we can do that through a manualClock or we should consider not
> > using a global clock at all (but instead making the physical clock part
> of
> > the configuration as well). Either of those is preferable to using a
> global
> > which is modified in various parts of the code which hope (but can't
> really
> > prove) that they're the only user at the time.
> >
> > —
> > You are receiving this because you were mentioned.
> >
> >
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cockroachdb/cockroach/pull/6357#issuecomment-215410393>
> >
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/6357#issuecomment-215416183>
>
-- 

-- Tobias

**Pull request closed without merging**
