### PR TITLE
storage: remove key bounds from ReplicatedEvalResult message

### PR DESCRIPTION
**Pull request by nvb**
Part of #16075.
Part of #18659.
Should help with #19746 and #19751.

This change removes the `StartKey` and `EndKey` field from
`ReplicatedEvalResult`, shrinking the size of each replicated Raft message
by an amount proportional to the length of the key boundaries it operates on.
The change is allowed because these fields were only being used for a single
assertion that was already guarded against elsewhere.

The assertion was that a Raft command needed to be evaluating inside its Replica's
bounds. However, we already knew that the Raft command was allowed to apply
within its key range by the time the command was proposed and reached this point.
This was guaranteed by checks upstream of Raft, which perform the same validation,
and by the CommandQueue, which ensured that any modifications to a range's
boundaries (eg. splits) were serialized with commands inside that Range. Finally,
the leaseAppliedIndex check in checkForcedErrLocked ensured that replays outside
of the CommandQueue's control which broke this serialization ordering were
already by caught and already threw an error.

Release note (performance improvement): reduce write amplification of
Raft replication.

### CODE REVIEW

**Comment by petermattis** [comment]
:crossed_fingers: :LGTM:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20647#-:-L0AqUiiIDmW2b__31JH:b-r876ux)*

**Comment by spencerkimball** [comment]
Nice. I was just wondering myself what `StartKey` and `EndKey` were for as I added a suggested compactions field here. Does this change have any visible performance impact when doing 100% write benchmarks?

**Comment by mberhault** [comment]
uh? I got this: https://teamcity.cockroachdb.com/viewLog.html?buildId=445457&buildTypeId=Cockroach_UnitTests
```
F171215 20:48:10.744460 49809 storage/replica.go:4525  [n1,s1,r20/1:/{Table/51-Max}] @nvanbenschoten, no performance for you! If this is seen, please update github.com/cockroachdb/cockroach/pull/20647; (desc=r20:/{Table/51-Max} [(n1,s1):1, next=2], gcThresh=1513370890.720662395,0, cmd={ProposerReplica:(n1,s1):1 ProposerLease:repl=(n1,s1):1 start=0.000000000,0 exp=1513370898.952865300,0 pro=1513370889.952895499,0 MaxLeaseIndex:3 TestingBatchRequest:TruncateLog [/Table/51,/Min) ReplicatedEvalResult:{StartKey:/Table/51 EndKey:/Table/51/NULL BlockReads:false State:truncated_state:<index:11 term:6 >  Split:<nil> Merge:<nil> ComputeChecksum:<nil> IsLeaseRequest:false Timestamp:1513370890.669386813,0 IsConsistencyRelated:false DeprecatedDelta:<nil> Delta:{ContainsEstimates:false LastUpdateNanos:0 IntentAge:0 GCBytesAge:0 LiveBytes:0 LiveCount:0 KeyBytes:0 KeyCount:0 ValBytes:0 ValCount:0 IntentBytes:0 IntentCount:0 SysBytes:0 SysCount:0} ChangeReplicas:<nil> RaftLogDelta:-42 AddSSTable:<nil>} WriteBatch:data:"\000\000\000\000\000\000\000\000\001\000\000\000\001\t\001i\234rrftt\000\027\022\004\010\000\020\000\030\000 \000(\0002\t+\r\014\222\003\010\013\020\006" }): batch timestamp 1513370890.669386813,0 must be after GC threshold 1513370890.720662395,0
```

**Comment by nvanbenschoten** [comment]
@spencerkimball nothing that I could see after a few quick tests. I benchmarked with this change and the proposed lease sequence number change from https://github.com/cockroachdb/cockroach/issues/16075. I was testing on a geo-distributed cluster (thanks to @m-schneider!), so that may have been a dominant factor that drowned out any perceivable performance win.

We can see in `TestProposalOverhead` that this change removes 7% of the raft command overhead (in the test), with the savings being variable and proportional to the size of the keys. With the other change, we remove roughly 40% of the fixed overhead of raft commands. Together, the changes will avoid a significant amount of overhead in each Raft message so I still expect to see them have a noticeable impact.

@mberhault thanks for the update. I purposely made the assertion there a little broader than what's necessary for this change, so that actually confirms my suspicion that we still need to check the GC timestamp. I'll adjust the assertion to only assert that we don't see range boundary mismatches instead of not seeing any error from `requestCanProceed`.

**Comment by petermattis** [comment]
> @spencerkimball nothing that I could see after a few quick tests. I benchmarked with this change and the proposed lease sequence number change from #16075. I was testing on a geo-distributed cluster (thanks to @m-schneider!), so that may have been a dominant factor that drowned out any perceivable performance win.

I imagine if you benchmark on a local cluster with a large-ish (>= 1KB) primary key the difference will be very noticeable.

**Comment by nvanbenschoten** [comment]
@petermattis @spencerkimball I did some more comprehensive experimentation. Again, I compared `master` with and without the combination of this change and the proposed lease sequence number change from #16075. As expected, the impact of the optimization is dependent on the size of the keys being sent through raft, so I used a patched version of `kv --read-percent=0` with a variable key size instead of a variable value size. A plot of the results is below:

chart

There a few things of interest to note here:
- There looks to be a constant throughput improvement independent of the primary key size of **~2%**. I think it's safe to attribute this primarily to the lease sequence change, which, as mentioned above, reduces the fixed overhead of `RaftCommand` by about 40%. This fixed size reduction doesn't seem to translate into any noticeable impact on 99th-percentile latency.
- As the key size grows, the change made in this PR results in more and more of an improvement in throughput. By the time the key size is **1KB**, this change improves throughput by **7%**. By the time the key size is **4KB**, this change improves throughput by **18%**. This is what we would expect.
- As the key size grows, the change made in this PR begins to have a noticeable impact on 99th-percentile latency after about the 1KB mark. By the time the key size reaches **8KB**, this change is responsible for a **25%** reduction in 99th-percentile latency.

**Comment by spencerkimball** [comment]
Awesome

**Comment by nvanbenschoten** [comment]
It's been a month since https://github.com/cockroachdb/cockroach/pull/20772 and we've never seen the assertion fire. I'm going to move towards merging this change soon.

**Pull request merged**
