### PR TITLE
sql: remove TODO about #13642 & revert unintentional math function changes

### PR DESCRIPTION
**Pull request by hueypark**
The title says it all.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Thanks for the fix! :lgtm:

A couple of nits: we usually don't have periods in the PR titles, and the PR description is missing

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48014#-:-M5gkXOt9PRMlSMXJ0su:bqp6zro)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by hueypark — COMMENTED** [review]
Thank you for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48014#-:-M5hbVxu8QLYmsvztBH5:b-rrkdbt)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
bors r=yuzefovich

**Comment by yuzefovich** [comment]
CI flake.

bors r=yuzefovich

**Pull request merged**
