### PR TITLE
storage: Switch replica stats from counts to QPS

### PR DESCRIPTION
**Pull request by a-robinson**
This was discussed prior to 1.0 but pushed off to minimize scope. This
makes stats more comparable across time (i.e. it's now more fair to
compare stats collected after 5 minutes to stats collected after 20
minutes), which should make for a reduced likelihood of thrashing.

I still have to rerun a couple of the allocsim workloads before merging this to see if the constants in the allocator code need to be tweaked at all, since this will make some of the replica weights there considerably smaller in imbalanced situations. That's tough to do without understanding #16463, though.

(edit) some relevant allocsim results, all of which look good without needing to adjust anything

`node-per-locality-high-latency-imbalanced-load.json`:
```
_elapsed__ops/sec__average__latency___errors_replicas_______________1:1_______________2:2_______________3:3
    1m0s    585.9    436.0   73.3ms        0      129           43/8/14           43/31/3            43/4/0
    2m0s    522.2    507.0   63.1ms        0      261          87/10/14           87/63/3            87/4/0
    3m0s    578.8    529.6   60.4ms        0      420         140/11/15         140/124/3           140/4/0
    4m0s    581.8    541.3   59.1ms        0      598         199/15/15         200/166/3           199/5/0
    5m0s    550.8    546.3   58.6ms        0      795         265/17/15         265/238/4           265/5/0
    6m0s    555.9    551.1   58.1ms        0      807         269/16/15         269/246/5           269/6/0
    7m0s    558.9    554.1   57.7ms        0      954         318/20/15         318/278/6           318/6/0
```

`node-per-locality-uneven-latency-imbalanced-load2.json`:
```
_elapsed__ops/sec__average__latency___errors_replicas_______________1:1_______________2:2_______________3:3
    1m0s   1269.8   1106.3   28.9ms        0      311         104/35/28          104/36/5           103/7/0
    2m0s   1289.8   1172.2   27.3ms        0      721         240/97/34          241/95/8           240/8/0
    3m0s   1269.8   1195.9   26.8ms        0      810        270/113/34         270/145/8           270/9/0
    4m0s   1272.7   1207.0   26.5ms        0     1449        483/214/35         483/231/8           483/9/0
    5m0s   1239.6   1211.3   26.4ms        0     1575        525/226/35        525/288/12          525/10/0
    6m0s   1296.4   1219.0   26.2ms        0     1632        544/232/35        544/289/12          544/10/0
```

`multiple-nodes-per-locality-imbalanced-load.json`:
```
_elapsed__ops/sec__average__latency___errors_replicas_______________1:1_______________2:1_______________3:1_______________4:2_______________5:2_______________6:2_______________7:3_______________8:3_______________9:3
    1m0s    505.3    394.4   81.0ms        0      132           15/4/16            15/6/6            15/4/5           14/10/7            14/6/1            14/7/3            15/3/6            15/0/3            15/4/1
    2m0s    487.9    440.5   72.6ms        0      234           25/6/19            26/7/9            25/6/6          26/14/13           27/14/4           26/16/3            25/6/8            27/3/4            27/4/3
    3m0s    524.4    454.8   70.3ms        0      427           48/9/22          49/11/12           45/11/6          49/27/16           48/30/6           46/29/7            48/8/9            48/8/5            46/8/3
    4m0s    438.9    465.1   68.8ms        0      442           51/9/22          50/11/12           48/12/7          49/28/16           49/30/6           48/29/7            50/8/9            51/9/5            46/7/3
    5m0s    482.1    469.5   68.1ms        0      749          87/18/23          83/18/15          79/16/11          86/49/16           83/52/6          84/47/10          81/11/12           82/16/5           84/12/3
    6m0s    531.9    473.2   67.6ms        0      820          89/17/27          91/18/16          86/16/11          95/57/18           94/61/8          90/57/10          93/14/12           91/19/5           91/13/4
```

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/allocator.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16464#-KmS9nLPVMl283wdQ30k:-KmS9nLPVMl283wdQ30l:bie6cdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc0c9b22c43322c6ce1529623f403c8e2dd6307b/pkg/storage/allocator.go#L54)):*
> ```Go
> 	// needed because a weight of zero doesn't work in the current lease scoring
> 	// algorithm.
> 	minReplicaWeight
> ```

Did you want to initialize this to an explicit value? I'm not even sure what this does without such an initialize. Is the value 0? That contradicts the comment. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16464)*

**Comment by a-robinson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/allocator.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16464#-KmS9nLPVMl283wdQ30k:-KmSHxYMXf0YRY4qB9TK:b9rhles) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc0c9b22c43322c6ce1529623f403c8e2dd6307b/pkg/storage/allocator.go#L54)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Did you want to initialize this to an explicit value? I'm not even sure what this does without such an initialize. Is the value 0? That contradicts the comment. 
</blockquote></details>

Whoops, yeah. I made the switch from an inline constant to this after running tests. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16464)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16464#-:-KmSKavandXblFYDBHqG:bnfp4nl)*

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_stats_test.go, line 279 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16464#-KmSkNHoyt0EWFl2elOD:-KmSkNHptVB_mNY5PW8I:bzd6bxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5594fceb021df3f10f2d4b38d6fdb16c0950adb7/pkg/storage/replica_stats_test.go#L279)):*
> ```Go
> 			rs.record(req)
> 		}
> 		durationDivisor := time.Duration(float64(replStatsRotateInterval) * decayFactor).Seconds()
> ```

I know these numbers where there before, but it would be nice to have a bit more clarity as to why the values are 2*df/div, (2*df +2)/div, etc...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16464#-:-KmSkbS4mJYqGhjk-8Wu:bnfp4nl)*

**Comment by a-robinson** [comment]
I've updated the initial PR message with allocsim results. No further changes to the allocator logic appear to be needed.

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_stats_test.go, line 279 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16464#-KmSkNHoyt0EWFl2elOD:-KmSoc8uVLNtDe7cIKzS:b-63v6yu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5594fceb021df3f10f2d4b38d6fdb16c0950adb7/pkg/storage/replica_stats_test.go#L279)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I know these numbers where there before, but it would be nice to have a bit more clarity as to why the values are 2*df/div, (2*df +2)/div, etc...
</blockquote></details>

Yeah, added a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16464#-:-KmSofFqLzlokmPoADOh:btw4kqc)*

**Pull request merged**
