### PR TITLE
spanconfig: exclude non table data from span used for BACKUP 

### LINKED ISSUE #102338: spanconfig: SystemTargetTypeEntireKeyspace should not apply to NodeLiveness
The `SystemTargetTypeEntireKeyspace` is the system span config target that is written to apply a spanconfig to the entire keyspace of the system tenant. The keyspace currently translates to the `keys.EverythingSpan` which extends from `[roachpb.KeyMin, roachpb.KeyMax)`. This implies that the spanconfig will apply to all non-table spans such as `NodeLiveness`, table-spans and all secondary tenants. A cluster backup and cluster restore in the system tenant use this system span config target to apply a protected timestamp on the entire cluster. As mentioned above, this protection will also apply to non-table spans such as `NodeLiveness` that are not backed up or restored. This prevents the GC queue from clearing up MVCC revisions from these non-table spans. `NodeLiveness` in particular has a short GC TTL of 600s so as to encourage faster GC because of the large number of updates that the span receives. The short TTL will not be respected if there is a running or paused cluster backup or restore in the system tenant.

This is a regression in behaviour from 21.2 where backup would only protect the table and tenant spans that it was going to read data from and export. To fix this we should consider modifying the `SystemTargetTypeEntireKeyspace` to only refer to table data and all secondary tenant keys in the system tenant keyspace.

Jira issue: CRDB-27400

### PR DESCRIPTION
**Pull request by aadityasondhi**
Previously, we were returning the `EverythingSpan` when targetting the
entire keyspace for a cluster backup. This would place a protected
timestamp on the entire keyspace. This was non-ideal because not all
spans are used for BACKUP. This is especially problematic for the case
of `Nodeliveness` since it would violate its GC TTL while the BACKUP is
taking place.

This patch introducees a more limited span for this use case and only
includes table data for system tables and tenant tables since this is
the only data used in a BACKUP.

Fixes: https://github.com/cockroachdb/cockroach/issues/102338

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
Let's add a test for the change we're making here? Doesn't have to be anything fancy, maybe something for the `spanconfig.Store` that sets system spanconfigs for `EntireTableKeyspaceTarget` and ensures getting a SpanConfig for a key < `TableDataMin` is correctly hydrated?

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-:-NcYhdZbEbx85CZnzssr:b96eeo5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @andrewbaptist)

___
*[`pkg/keys/spans.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-NcYglyV82KEnHpZnVTa:-NcYglyV82KEnHpZnVTb:bxonf19) ([raw file](https://github.com/cockroachdb/cockroach/blob/92560f70bf822ab9862b829f36ebc9c20721f63e/pkg/keys/spans.go#L22)):*
> ```Go
> 	// subset of EverythingSpan and skips certain keyspaces that are not used in
> 	// full cluster backups (i.e. NodeLiveness, Timeseries, etc.)
> 	TableSpan = roachpb.Span{Key: TableDataMin, EndKey: roachpb.KeyMax}
> ```

Not sure if `TableSpan` is the right name here -- I would expect `TableSpan` to end with `TableDataMax`,  not `roachpb.KeyMax`. Can we come up with a better name? I'd even go so far as saying this should be called `ClusterBackupSpan`. 
___
*[`pkg/spanconfig/systemtarget.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-NcYhMM4009xGbw0aPBA:-NcYhMM4009xGbw0aPBB:b-hev6n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/92560f70bf822ab9862b829f36ebc9c20721f63e/pkg/spanconfig/systemtarget.go#L54)):*
> ```Go
> 	// targeting the entire table keyspace (the system and all tenants). Only the
> 	// host tenant is allowed to do so.
> 	SystemTargetTypeEntireTableKeyspace
> ```

How about `SystemTargetTypeClusterBackupKeyspace`.
___
*[`pkg/spanconfig/spanconfigkvsubscriber/testdata/system_span_configs` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-NcYhYhc-RaQCvK26lPI:-NcYhYhc-RaQCvK26lPJ:b-b9pene) ([raw file](https://github.com/cockroachdb/cockroach/blob/92560f70bf822ab9862b829f36ebc9c20721f63e/pkg/spanconfig/spanconfigkvsubscriber/testdata/system_span_configs#L72)):*
> ```
> # invoked correctly + configs for various keys are correctly hydrated.
> update
> delete {entire-keyspace}
> ```

Should we update this {entire-keyspace} bit as well?

**Review by aadityasondhi — COMMENTED** [review]
Made the recommended naming changes. See my comment below about testing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-:-NcbpoY57lpxGZt9Dp5e:b-rw4abz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @arulajmani)

___
*[`pkg/keys/spans.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-NcYglyV82KEnHpZnVTa:-NcbphGX7mdLX_xpjnWm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92560f70bf822ab9862b829f36ebc9c20721f63e/pkg/keys/spans.go#L22)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Not sure if `TableSpan` is the right name here -- I would expect `TableSpan` to end with `TableDataMax`,  not `roachpb.KeyMax`. Can we come up with a better name? I'd even go so far as saying this should be called `ClusterBackupSpan`.
</blockquote></details>

Done.
___
*[`pkg/spanconfig/systemtarget.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-NcYhMM4009xGbw0aPBA:-Ncbpi8T2hgYlguiYcgR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92560f70bf822ab9862b829f36ebc9c20721f63e/pkg/spanconfig/systemtarget.go#L54)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

How about `SystemTargetTypeClusterBackupKeyspace`.
</blockquote></details>

Done.
___
*[`pkg/spanconfig/spanconfigkvsubscriber/testdata/system_span_configs` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-NcYhYhc-RaQCvK26lPI:-NcbpnmpCijPlsW2tBR1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92560f70bf822ab9862b829f36ebc9c20721f63e/pkg/spanconfig/spanconfigkvsubscriber/testdata/system_span_configs#L72)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we update this {entire-keyspace} bit as well?
</blockquote></details>

Done.
___
*[`pkg/spanconfig/spanconfigkvsubscriber/testdata/system_span_configs` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-Ncbq6z4EKaDl2fmGnUm:-Ncbq6z4EKaDl2fmGnUn:b-bp5eoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f3306037b7bc0a77ce811fa7e363df46651a518/pkg/spanconfig/spanconfigkvsubscriber/testdata/system_span_configs#L34)):*
> ```
> updates
> ----
> [/Table/0,/Max)
> ```

Does this not cover your concern about testing? It ensures that the right bounds are set for this span (`ClusterBackupSpan`) and maps to `SystemTargetTypeClusterBackupKeyspace`. Let me know if I am missing something.

**Review by arulajmani — COMMENTED** [review]
> Reviewed 11 of 22 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108905)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @andrewbaptist)

___
*[`pkg/keys/spans.go` line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-Ncc2FuDDU3gTjD2qss2:-Ncc2FuDDU3gTjD2qss3:b-6gh9r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/560173e3d6baccf3a4c5dd3d63b951e728f6ec81/pkg/keys/spans.go#L20)):*
> ```Go
> 
> 	// ClusterBackupSpan is a span that covers all System and Tenant tables. It is
> 	// a subset of EverythingSpan and skips certain keyspaces that are not used in
> ```

nit: "certain spans"
___
*[`pkg/spanconfig/spanconfigkvsubscriber/testdata/system_span_configs` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108905#-Ncbq6z4EKaDl2fmGnUm:-Ncc3suIEuEbkooomTGv:bocczz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f3306037b7bc0a77ce811fa7e363df46651a518/pkg/spanconfig/spanconfigkvsubscriber/testdata/system_span_configs#L34)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Does this not cover your concern about testing? It ensures that the right bounds are set for this span (`ClusterBackupSpan`) and maps to `SystemTargetTypeClusterBackupKeyspace`. Let me know if I am missing something.
</blockquote></details>

All this says is that we've received an update for ranges that overlap with this key range. It doesn't say anything about the hydration logic when you fetch a key that belongs to the span `[roachpb.KeyMin, roachpb.TableDataMin)`. Are we correctly hydrating span configurations in that range by excluding the system span config that applies over `ClusterBackupSpan`? 

We should write a test to convince ourselves that this patch is actually doing that. I may be missing something, but I don't think this patch is doing that after reading:

https://github.com/cockroachdb/cockroach/blob/da1dc5ef8618569cbaa9a3093f8b7ba721c62018/pkg/spanconfig/spanconfigstore/system_store.go#L92-L119

**Comment by aadityasondhi** [comment]
Leaning towards this alternative solution: https://github.com/cockroachdb/cockroach/pull/109683

**Pull request closed without merging**
