### PR TITLE
ui: use yarn workspaces for project structure

### PR DESCRIPTION
**Pull request by koorosh**
Note. This is a huge PR with lots of changes which mostly affect files location.

The purpose of this change
This is a part of build improvements that include optimization and speed up of builds on CI to get fast response on code changes.

The main changes introduced with this change:
- added top level `pkg/ui/package.json` that defines yarn workspaces and includes project wide dependencies required for all packages (including for building protobufs).
- `cluster-ui` NPM package is moved to `pkg/ui/workspaces/cluster-ui`
- main `ui` package is moved to `pkg/ui/workspaces/db-console`
- Make file configuration adjusted to run builds with new project structure
- typescript version is changed to 4.x for all packages to have consistency across of projects. This also affected linting rules which now is more strict and required fix loose typings.

Note for reviewers. It is easier to review on per commit basis (to distinguish lint autofix changes etc)

Release note: none

Release justification: non-production code changes

### CODE REVIEW

**Review by Santamaura — COMMENTED** [review]
> Reviewed 66 of 1040 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elkmaster, @koorosh, @nathanstilwell, and @Santamaura)

___
*[Makefile, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68412#-MgHIA773M71E37AStdn:-MgHIA786TBK-2aDHjIR:b-txw27h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e90830c973d091f06457d3a863dc68dbc45b73e/Makefile#L374)):*
> ```Makefile
> .SECONDARY: pkg/ui/yarn.installed
> pkg/ui/yarn.installed: pkg/ui/package.json pkg/ui/yarn.lock | bin/.submodules-initialized
> 	$(NODE_RUN) -C pkg/ui yarn install --ignore-optional
> ```

What is the significance of adding this flag when yarn install is run? Maybe a brief comment on why ignore-optional is needed

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 6 of 262 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, and @Santamaura)

**Comment by nathanstilwell** [comment]
I pulled this down and tested it locally and was able to build and develop with `make ui-watch`. I'm excited about this change in general as I think it is going to make the build faster and more stable.

**Review by rickystewart — APPROVED** [review]
`Makefile` changes look sane to me.

**Pull request merged**
