### PR TITLE
sql: separate kv fetching from scan

### PR DESCRIPTION
**Pull request by RaduBerinde**
Minor refactoring before adding more code to fetch KVs in chunks.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4733)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

I'm wondering if instead of `kvFetcher` we should create a `rowFetcher`. Definitely more involved to move the logic for reconstructing a row out of `scanNode`, but it might be a first step towards pushing knowledge of rows down into lower levels (i.e. I could imagine having a `client.RowFetcher`).

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/kvfetcher.go, line 108 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-KBmfYfi9bWdK_F81SGT:-KBmfYfi9bWdK_F81SGU:-2091243688) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e7845482b1add29752c1bec73cf9f7cb705abf/sql/kvfetcher.go#L108)):*
`s/fetchKVs/fetch/g`

---

*[sql/kvfetcher.go, line 143 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-KBmfvmqMPHqeCwu8QQf:-KBmfvmrKS60D6i76JFz:-1448883016) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e7845482b1add29752c1bec73cf9f7cb705abf/sql/kvfetcher.go#L143)):*
The name is `nextKey`, yet it is returning a `KeyValue`. Perhaps `s/nextKey/next/g`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-:-KBmg96uae16n1rdpXvx:1976670132)*

**Comment by tschottdorf** [comment]
LGTM

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/kvfetcher.go, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-KBmtToUuUFQ7xOpn2Ke:-KBmtToUuUFQ7xOpn2Kf:-1600888303) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e7845482b1add29752c1bec73cf9f7cb705abf/sql/kvfetcher.go#L32)):*
looks like
```go
type span Struct {
  roachpb.Span
  count int64
}
```
to me

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-:-KBmuEH2WewIhEoiACjM:676834233)*

**Comment by RaduBerinde** [comment]
*[sql/kvfetcher.go, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-KBmtToUuUFQ7xOpn2Ke:-KBmv8JLXmLZVp1nf-mO:2090597925) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e7845482b1add29752c1bec73cf9f7cb705abf/sql/kvfetcher.go#L32)):*
True, but it doesn't help us much, and a lot of existing code would need to be modified to use Key/EndKey instead (and IMO would be less readable as "start" is more obvious than "Key").

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733)*

**Comment by petermattis** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/kvfetcher.go, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-KBmtToUuUFQ7xOpn2Ke:-KBn1RPzts5HbTzC8N94:-902543081) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e7845482b1add29752c1bec73cf9f7cb705abf/sql/kvfetcher.go#L32)):*
I'm neutral, just pointing out that we have this structure already.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733)*

**Comment by RaduBerinde** [comment]
The main reason I of `kvFetcher` was to separate the fetching code from the row reconstruction logic. If we wanted to have a `rowFetcher`, given the current APIs I would prefer to implement it on top of `kvFetcher` to maintain that separation.. But then again that's pretty much what `scanNode` is, there isn't much left in there other than row reconstruction.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-:-KBmrlgED4VgqRS_bTPS:-1652885679)*

**Comment by andreimatei** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-:-KBnJT9bOJAvSt0uf-CA:676834233)*

**Comment by tamird** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/join.go, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-KBja7tDzDV_CGBMcVUf:-KBja7tDzDV_CGBMcVUg:-1062194971) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e7845482b1add29752c1bec73cf9f7cb705abf/sql/join.go#L130)):*
is this some kind of reset? how come it is necessary?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733)*

**Comment by RaduBerinde** [comment]
*[sql/join.go, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-KBja7tDzDV_CGBMcVUf:-KBneWDCmcan1WRpRb2Z:1765210215) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e7845482b1add29752c1bec73cf9f7cb705abf/sql/join.go#L130)):*
We're starting over with new spans and we need `initScan` to be called again. The condition for calling `initScan` used to be whether `kvs` is `nil`, now it's whether the fetcher was initialized.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/join.go, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733#-KBja7tDzDV_CGBMcVUf:-KBnlE_v46UE36a0Tg7D:878871595) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e7845482b1add29752c1bec73cf9f7cb705abf/sql/join.go#L130)):*
I added a `scanInitialized` flag to clean this up.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4733)*

**Pull request merged**
