### PR TITLE
sql: Rename DOIDWrapper to DTypeWrapper (patch 12/)

### PR DESCRIPTION
**Pull request by knz**
Split from #36598 cc @andy-kimball 

Generalize DOIDWrapper so that it can wrap a Datum with any types.T rather
than an OID. This enables it to represent any type, such as "VARCHAR(20)",
rather than just "VARCHAR".

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> This enables it to represent any type, such as "VARCHAR(20)", rather than just "VARCHAR".

Please add a (small) test here that demonstrates/verifies this, in advance of more comprehensive changes/tests in a later commit. The test can live in the `types` package.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36709#-:-Lc5y4ab1HyGa84aKTMp:b-dkwvwd)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andy-kimball — COMMENTED** [review]
We only ever create 3 instances of `DTypeWrapper`: for `oidvector`, `int2vector`, and `name`. I can't think of any interesting tests that we don't already have for those. Do you have something in mind?

I had originally thought we did more than those 3 types, which is why I thought we needed this. I could revert the change to turn this into `DTypeWrapper`, but it seems like it might come in useful in the future if we decide to actually propagate other type variations than those three. Storing `*types.T` rather than `oid.Oid` is more flexible for the future.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36709#-:-LcJzUHfBMytX30trwB_:b-6k6ecf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Review by knz — COMMENTED** [review]
There are several examples :) We can use this to e.g. decorate a decimal value with different precision/width. Or decorate a string to distinguish a varchar value from a char value. (Although we don't _use_ those things today, you can write a meaningful test with them in the types package.)

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36709#-:-LcfP3p05Dz1h3NxHsie:bbgcwbl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Review by andy-kimball — COMMENTED** [review]
But doesn't that just look like:
```
d := DTypeWrapper{Wrapped: NewDString("foo"), types.MakeVarChar(10)}
???
```
Just constructing it doesn't seem like a useful test. Can you give me example(s) of test(s) that might reasonably find a bug?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36709#-:-Lcfpy8t-p-ommZtbqew:b-ckarzh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Review by knz — COMMENTED** [review]
> Can you give me example(s) of test(s) that might reasonably find a bug?

I was more thinking of [tests as documentation](https://duckduckgo.com/?q=tests+as+documentation) to illustrate this new facility. The kind of test I was thinking about would do:

1. construct a datum using the DTypeWrapper, using a type different from that of the wrapped datum
2. pass it as argument to `pg_type`
3. verify that works and assert the expected type name (that of the wrapping type)

Then the test would assert this works as expected for the 3 cases already in pervasive use, and would add a couple cases that were not possible previously, for illustration purposes.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36709#-:-LcqTv-23T1KPuQ2NkJk:br7ii3a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Review by andy-kimball — COMMENTED** [review]
I'm not sure what `pg_type` is; do you mean `pg_typeof`? I tried writing code like:
```
func TestDatumTypeWrapper(t *testing.T) {
	evalCtx := tree.NewTestingEvalContext(cluster.MakeTestingClusterSettings())
	d := &tree.DTypeWrapper{tree.NewDString("foo"), types.MakeVarChar(10)}
	res, err := tree.FunDefs["pg_typeof"].Definition[0].(*tree.Overload).Fn(evalCtx, tree.Datums{d})
}
```
But `pg_typeof` does not show widths, so this is not really testing anything useful (in PG, it would show `character varying`, and in CRDB it currently shows `varchar`).

If you have some other idea, can you give me a code snippet to illustrate (doesn't need to compile, just to show me what you're thinking in more specific way)?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36709#-:-LcqeqW71uRcTxH-oS33:b-ak2upb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Review by andy-kimball — COMMENTED** [review]
I could also just get rid of this commit entirely, since it's not needed for this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36709#-:-LcqfcG1DIj1WmsbbZP6:b-iveoj9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by andy-kimball** [comment]
Reflecting on this further, I'm just going to discard this patch entirely. It's not doing anything now, and may never do anything in the future.

Perhaps what we should think about is the possibility of getting rid of `DOidWrapper/DTypeWrapper` entirely. Maybe the `pg_typeof` function can always be statically folded by the optimizer. Perhaps other reasons why the wrappers exist can now go away?

**Pull request closed without merging**
