### PR TITLE
storage: renaming functions in the Reader interface

### PR DESCRIPTION
**Pull request by sumeerbhola**
- Get to MVCCGet
- GetProto to MVCCGetProto
- Iterate to MVCCIterate
- ExportToSst to ExportMVCCToSst

Also added MVCCIterKind.

Release note: None

### CODE REVIEW

**Comment by dt** [comment]
I'm not sure if we care, but `ExportToSST` isn't _quite_ like the others in that it doesn't always do normal MVCC lastest-as-of-x reads, e.g. if revisions=true. Maybe it is still more MVCC-ish than not though?

**Review by petermattis — APPROVED** [review]
:lgtm:

I don't have good thoughts on @dt's comment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55998#-:-MKasK7Q-Y7gjTS6b29t:b-wwt97z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @itsbilal, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine.go, line 636 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/55998#-MKas6r131h_4lpNe0DM:-MKas6r131h_4lpNe0DN:b1pox73) ([raw file](https://github.com/cockroachdb/cockroach/blob/86ff0cf791259efd4d48bfb796e7b2c9803096ec/pkg/storage/engine.go#L636)):*
> ```Go
> // start (inclusive) and ending at end (non-inclusive).
> // Specify max=0 for unbounded scans.
> func Scan(reader Reader, start, end roachpb.Key, max int64) ([]MVCCKeyValue, error) {
> ```

This function is a bit dangerous, especially with `max=0`. Not for this PR, but I wonder if we should get rid of it. There are only 4 uses.

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> I'm not sure if we care, but ExportToSST isn't quite like the others in that it doesn't always do normal MVCC lastest-as-of-x reads, e.g. if revisions=true. Maybe it is still more MVCC-ish than not though?

The use of "MVCC" in the naming here is saying that we are iterating over the part of the key space that can have multiple versions. Whether the caller is only interested in the latest version, or all, is orthogonal to this naming.

This is to distinguish it from iterating over the more general `EngineKey` key space which would include MVCC and lock table.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55998#-:-MKatrH3Dntj5S3KofiL:b-iybyha)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/storage/engine.go, line 636 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/55998#-MKas6r131h_4lpNe0DM:-MKav30f-7fi4wlY6O05:b-j0hky9) ([raw file](https://github.com/cockroachdb/cockroach/blob/86ff0cf791259efd4d48bfb796e7b2c9803096ec/pkg/storage/engine.go#L636)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This function is a bit dangerous, especially with `max=0`. Not for this PR, but I wonder if we should get rid of it. There are only 4 uses.
</blockquote></details>

There are a lot of test uses (I see more than 20).

**Pull request merged**
