### PR TITLE
cli: add shared process testing for debug zip 

### LINKED ISSUE #98781: cli: missing test for debug-zip with in-process tenants
The `TestTenantZip` in `pkg/cli` only tests for seperate process tenants (i.e. serverless use case). We recently added debug zip capability for generating debug zips for in-process tenants. There is missing test coverage there.

Related PR: https://github.com/cockroachdb/cockroach/pull/96393

Jira issue: CRDB-25518

### PR DESCRIPTION
**Pull request by aadityasondhi**
When the functionality of targetting shared-process multitenant clusters
was added to debug zip, unit tests to verify this functionality were
missing due to lack of configuration in the test infra.

This change adds the test along with required CLITest changes to enable
shared-process testing for debug zip.

Fixes #98781

Release note: None

### CODE REVIEW

**Comment by aadityasondhi** [comment]
Thanks @herkolategan for the assist with https://github.com/cockroachdb/cockroach/compare/master...herkolategan:cockroach:hbl/exp-debug-zip-test-inprocess-tenants

**Review by andreimatei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99446)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @dhartunian)

___
*[`pkg/cli/testutils.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-NReJ3zx-R5MbZHxAsp1:-NReJ3zx-R5MbZHxAsp2:b-dudtqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ad951500e00e942874113fde59a6231e15bb304/pkg/cli/testutils.go#L70)):*
> ```Go
> 	reportExitCode bool
> 	// if true, targets the system tenant.
> 	forceSystemTenant bool
> ```

maybe `useSystemTenant`? At least have the same name here and in the `TestCLIParams`.
But actually I don't really like this field. It's not clear *who* targets the system tenant. I think it'd be better to have the test explicitly request the RPC address of one tenant or another.

Btw, if `TestCLI` doesn't really give our test much on top of what a `TestServer` or a `TestCluster` provide, consider moving it away from this `TestCLI` guy. I think all this tenant varieties are getting to be quite a burden for this rando test utility.
___
*[`pkg/cli/zip_tenant_test.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-NReKDQ1E1Kco0zuQopD:-NReKDQ1E1Kco0zuQopE:br4kx1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ad951500e00e942874113fde59a6231e15bb304/pkg/cli/zip_tenant_test.go#L41)):*
> ```Go
> 	}{
> 		{
> 			testName: "testzip_tenant_separate_process",
> ```

we usually use spaces in these names. The testing framework with turn them into some dashes.
___
*[`pkg/cli/zip_tenant_test.go` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-NReKUIX5J6rAMXyl1YZ:-NReKUIX5J6rAMXyl1Y_:b-r8ksbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ad951500e00e942874113fde59a6231e15bb304/pkg/cli/zip_tenant_test.go#L45)):*
> ```Go
> 				tenantDir, tenantDirCleanupFn := testutils.TempDir(t)
> 				defer tenantDirCleanupFn()
> 				tenantArgs := base.TestTenantArgs{
> ```

nit: `parans.TenantArgs = &base.TestTenantArgs{...`
and the same in the next test case. That would make it easier to see the difference between the two cases.
___
*[`pkg/cli/zip_tenant_test.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-NReKq8_BEzesMhG_oF-:-NReKq8_BEzesMhG_oF0:bdnxg4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ad951500e00e942874113fde59a6231e15bb304/pkg/cli/zip_tenant_test.go#L69)):*
> ```Go
> 
> 	for _, tenant := range tenants {
> 		tenant := tenant // loop var capture
> ```

is this necessary? The subtests do not run in parallel, do they?

**Review by herkolategan — COMMENTED** [review]
Great work! I agree with Andrei's comments, but otherwise looks good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-:-NRmMT8t9ahlM49R-34Z:boxt0qs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @dhartunian)

**Review by aadityasondhi — COMMENTED** [review]
PTAL at the latest changes. I ended up agreeing with all your suggestions other than replacing TestCLI entirely. Let me know what you think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-:-NRneKd-6E9pSPlmthDt:bc9olcq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dhartunian)

___
*[`pkg/cli/testutils.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-NReJ3zx-R5MbZHxAsp1:-NRndqyc7M9rK46iWIWy:b-khsfny) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ad951500e00e942874113fde59a6231e15bb304/pkg/cli/testutils.go#L70)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe `useSystemTenant`? At least have the same name here and in the `TestCLIParams`.
But actually I don't really like this field. It's not clear *who* targets the system tenant. I think it'd be better to have the test explicitly request the RPC address of one tenant or another.

Btw, if `TestCLI` doesn't really give our test much on top of what a `TestServer` or a `TestCluster` provide, consider moving it away from this `TestCLI` guy. I think all this tenant varieties are getting to be quite a burden for this rando test utility.
</blockquote></details>

Ended up renaming but keeping TestCLI since it allows me to easily capture the results of the log output of debug zip. I feel like these changes to the TestCLI could also be useful for future multitenant tests in the `cli` package. Let me know if you think differently.
___
*[`pkg/cli/zip_tenant_test.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-NReKDQ1E1Kco0zuQopD:-NRneAx588m5yIvSB-tu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ad951500e00e942874113fde59a6231e15bb304/pkg/cli/zip_tenant_test.go#L41)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

we usually use spaces in these names. The testing framework with turn them into some dashes.
</blockquote></details>

Done.
___
*[`pkg/cli/zip_tenant_test.go` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-NReKUIX5J6rAMXyl1YZ:-NRneCgJCvL07PT1ZQVS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ad951500e00e942874113fde59a6231e15bb304/pkg/cli/zip_tenant_test.go#L45)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: `parans.TenantArgs = &base.TestTenantArgs{...`
and the same in the next test case. That would make it easier to see the difference between the two cases.
</blockquote></details>

Done.
___
*[`pkg/cli/zip_tenant_test.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-NReKq8_BEzesMhG_oF-:-NRneEE5-81XvuChF9gD:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ad951500e00e942874113fde59a6231e15bb304/pkg/cli/zip_tenant_test.go#L69)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this necessary? The subtests do not run in parallel, do they?
</blockquote></details>

Fixed.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-:-NRoHYU5AXhWKXKFYYe-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi and @dhartunian)

___
*[`pkg/cli/testutils.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99446#-NReJ3zx-R5MbZHxAsp1:-NRoHUAI0u4IFtjQPc-g:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ad951500e00e942874113fde59a6231e15bb304/pkg/cli/testutils.go#L70)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Ended up renaming but keeping TestCLI since it allows me to easily capture the results of the log output of debug zip. I feel like these changes to the TestCLI could also be useful for future multitenant tests in the `cli` package. Let me know if you think differently.
</blockquote></details>

:thumbsup:

**Pull request merged**
