### PR TITLE
sql: rewrite sql stats compaction job to avoid scanning mvcc garbage

### PR DESCRIPTION
**Pull request by Azhng**
Related to #79548

Previously, SQL Stats cleanup job's performance could severely degrade 
and cannot keep up with the write load, since its `DELETE` statements
often needed to scan over large range of MVCC garbage.
This commit addresses this issue by further constraining the scans of
the `DELETE` statements to reduce how much MVCC garbage it scans over.

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80341)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, and @mgartner)

___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a3tO5E-BPlaY9ELYJ:-N0a3tO5E-BPlaY9ELYK:bxrvede) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L27)):*
> ```Go
> //  value.
> var (
> 	// N.B.: statement and transaction statistics system tables has hash sharded
> ```

nit: have
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4GIN6sLEICixZXQD:-N0a4GIN6sLEICixZXQE:b-e6d4hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L69)):*
> ```Go
> 				(
> 		      aggregated_ts,
> 					fingerprint_id,
> ```

nit: alignment
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4LaV6MqcMElMRUGo:-N0a4LaV6MqcMElMRUGp:bqgrwp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L73)):*
> ```Go
> 		      plan_hash,
> 		      app_name,
> 		      node_id                   
> ```

nit: remove trailing space
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4JtK7vEWYOjP4iIR:-N0a4JtK7vEWYOjP4iIS:b-e6d4hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L89)):*
> ```Go
> 				(
> 		      aggregated_ts,
> 					fingerprint_id,
> ```

nit: alignment
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4OV-5gvYGdiMOrGx:-N0a4OV-5gvYGdiMOrGy:bqgrwp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L91)):*
> ```Go
> 					fingerprint_id,
> 		      app_name,
> 		      node_id                   
> ```

nit: remove trailing space
___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_test.go` line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4rft1cq7HZHC4pH5:-N0a4rft1cq7HZHC4pH6:b-7wjsgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L216)):*
> ```Go
> 				// The two interceptors (kvInterceptor and cleanupInterceptor) are
> 				// injected into kvserver and StatsCompactor respectively.
> 				// The cleanupInterceptor calculates number of expected "wide scan"
> ```

nit: calculates the number
___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_test.go` line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4utSCAv5H5jB3xSy:-N0a4utSCAv5H5jB3xSz:bb5ui56) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L218)):*
> ```Go
> 				// The cleanupInterceptor calculates number of expected "wide scan"
> 				// that should be issued by the StatsCompactor.
> 				// The kvInterceptor counts number of actual "wide scan" KV Request
> ```

nit: counts the number

**Review by mgartner — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80341)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @Azhng)

___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go` line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0b0fcT8DWGlOJR_5hM:-N0b0fcT8DWGlOJR_5hN:bx7f4o0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L168)):*
> ```Go
> 		for remainToBeRemoved := rowsToRemove; remainToBeRemoved > 0; {
> 			if len(lastDeletedRow) > 0 {
> 				stmt = ops.subsequentDeleteStmt
> ```

nit: It might be clearer to create a method of `cleanupOperations` that returns the stmt given `lastDeletedRow` - if `lastDeletedRow` was empty it could return the wide version, otherwise the constrained version.
___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go` line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0b0-vx5WLqPKwL3g4-:-N0b0-vy8ykAeI6Fudy-:b-d2nxfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L224)):*
> ```Go
> 
> func getQargs(shardIdx, limit int64, lastDeletedRow tree.Datums) []interface{} {
> 	qargs := make([]interface{}, 0, len(lastDeletedRow)+2)
> ```

nit: you could make this a scratch field in `StatsCompactor` to reduce allocations.
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0b1Bfl612aHtvVjsq0:-N0b1Bfl612aHtvVjsq1:b-236704) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L117)):*
> ```Go
> 		}
> 	case "system.transaction_statistics":
> 		return &cleanupOperations{
> ```

You could defined these structs are singletons that can be accessed directly without the need of this `cleanupOpForTable` helper. I think it'd be nice to have the constrained and unconstrained queries side by side for reference.

**Review by Azhng — COMMENTED** [review]
Also moved `query_utils.go` back into `compaction_exec.go` 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-:-N0c-7YvDfK4-I_w8JeC:b-g0st07)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @maryliag, and @mgartner)

___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go` line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0b0fcT8DWGlOJR_5hM:-N0bz7cD6DO5tQ6GPaDD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L168)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: It might be clearer to create a method of `cleanupOperations` that returns the stmt given `lastDeletedRow` - if `lastDeletedRow` was empty it could return the wide version, otherwise the constrained version.
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go` line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0b0-vx5WLqPKwL3g4-:-N0brDAM9csVEKGmCdID:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L224)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you could make this a scratch field in `StatsCompactor` to reduce allocations.
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_test.go` line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4rft1cq7HZHC4pH5:-N0bz3V2CzEZndpw7vWx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L216)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: calculates the number
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_test.go` line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4utSCAv5H5jB3xSy:-N0bz5Ez8yddzrfycsln:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L218)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: counts the number
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a3tO5E-BPlaY9ELYJ:-N0b-xPQBAmEjoFy2VBm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L27)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: have
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4GIN6sLEICixZXQD:-N0bzUWA3C4QT_LRyTMb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L69)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: alignment
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4LaV6MqcMElMRUGo:-N0bzVYQD0akZtmSL9ua:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L73)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: remove trailing space
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4JtK7vEWYOjP4iIR:-N0b0V_w9T4uGOyuxtEu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L89)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: alignment
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0a4OV-5gvYGdiMOrGx:-N0b0WEI0e1Y9EWRMe6L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L91)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: remove trailing space
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/persistedsqlstats/query_utils.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0b1Bfl612aHtvVjsq0:-N0byxfJCBOnfGmJCnrg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5db1ea6312b43223cb2184fdb2e851a910d37e66/pkg/sql/sqlstats/persistedsqlstats/query_utils.go#L117)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You could defined these structs are singletons that can be accessed directly without the need of this `cleanupOpForTable` helper. I think it'd be nice to have the constrained and unconstrained queries side by side for reference.
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-:-N0fU-JfAp3wLHt4Nu3l:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @Azhng)

___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go` line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0fTTGZCF0eQZpGwwD-:-N0fTTGZCF0eQZpGwwD0:b-j43aga) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5f6d1407e73b8d88bd1c90fb2c28336cfc9128c/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L165)):*
> ```Go
> ) error {
> 	var err error
> 	lastDeletedRow := tree.Datums{}
> ```

nit: `var lastDeletedRow tree.Datums` should be sufficient here.
___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go` line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-N0fTEGaDh1ZYpfuEOCQ:-N0fTEGaDh1ZYpfuEOCR:bvujnbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5f6d1407e73b8d88bd1c90fb2c28336cfc9128c/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L284)):*
> ```Go
> 
> 	deleteFromStmtStatsWithWideScan = `
>     DELETE FROM system.statement_statistics
> ```

nit: you could move these strings into the structs defined below to avoid a reader having to follow a trail to make sense of this.

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80341#-:-N0kTYSJ2Niu8_nl5Q_R:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner and @Azhng)

**Comment by Azhng** [comment]
TFTR!

bors r=maryliag,mgartner

**Comment by rickystewart** [comment]
bors r=maryliag,mgartner

**Pull request merged**
