### PR TITLE
Revert "changefeedccl: implement concurrent execution for webhook sink"

### PR DESCRIPTION
**Pull request by otan**
This reverts commit b5bbe1e39e0bb44a0e424d684d4ac99ca72e4db0.

This commit causes flaking regularly on bors.

Release note: None

### CODE REVIEW

**Review by adityamaru — APPROVED** [review]

**Comment by otan** [comment]
bors r=adityamaru

**Comment by otan** [comment]
bors r=adityamaru p=999 single on

**Comment by otan** [comment]
bors r=adityamaru p=999 single on

**Comment by otan** [comment]
bors r=adityamaru p=999 single on

**Pull request merged**
