### PR TITLE
server/license: Add core throttling logic for license policy enforcement

### PR DESCRIPTION
**Pull request by spilchen**
As part of deprecating the CockroachDB core license, new logic has been added to throttle access when license policies are violated. This change introduces the core logic, though it does not yet integrate with the SQL engine, so throttling won't affect SQL users at this stage.

The LicenseEnforcer has been enhanced with throttling logic, including a new API, MaybeFailIfThrottled, which determines whether throttling should occur and returns an error if it is active.

To make throttling decisions, the LicenseEnforcer requires access to license state. However, since the license code remains in the CCL package, which cannot be imported directly into the server code, a workaround is used. When the enterprise.license changes, a callback (from CCL to server packages) updates the state. Initially, this callback points to a stub function, which the CCL package replaces with the actual implementation upon import.

The implementation also includes handling for mandatory telemetry data required by certain licenses. While the logic is in place to make decisions based on the last telemetry ping, the integration with the diagnostics reporter for actual telemetry ping times will be completed in a follow-up change.

This change will be backported to 23.1, 23.2, 24.1 and 24.2.

Epic: CRDB-39988
Informs: CRDB-39991
Release note: None

### CODE REVIEW

**Review by rafiss — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129880)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/server/license/enforcer.go` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5UtSbdD-jA82fOYCmK:-O5UtSbdD-jA82fOYCmL:bq23w28) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6a00753fc5968ad190a43d7626aa8b967e4f21/pkg/server/license/enforcer.go#L32)):*
> ```Go
> const (
> 	defaultMaxOpenTransactions = 5
> 	defaultMaxTelemetryDelay   = 7 * 24 * time.Hour
> ```

nit: "delay" feels like the wrong term here. should we call it a "telemetry grace period" or something like that?
___
*[`pkg/server/license/enforcer.go` line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5Ui-qR4ra2HWUCBbY3:-O5Ui-qR4ra2HWUCBbY4:b-ehvwua) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6a00753fc5968ad190a43d7626aa8b967e4f21/pkg/server/license/enforcer.go#L248)):*
i'm not sure where to make this change, but one more requirement from the spec is:
> All single-node clusters are permanently exempt from throttling

we could implement that as an infinite grace period, or we could do it at a lower level and just short-circuit the license check if it's single node
___
*[`pkg/server/license/enforcer.go` line 250 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5UsWra9NHiS43-2Fwt:-O5UsWra9NHiS43-2Fwu:bndqmyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6a00753fc5968ad190a43d7626aa8b967e4f21/pkg/server/license/enforcer.go#L250)):*
> ```Go
> 	switch licType {
> 	case LicTypeNone:
> 		e.storeNewGracePeriodEndDate(e.GetGracePeriodInitTS(), e.getGracePeriodDuration(7*24*time.Hour))
> ```

i don't think this calculation covers all the cases. the spec says
- New cluster is created and no license key has been added: 7 day grace period
- Cluster running without a license is upgraded to a patch version that requires a license: 30 day grace period

so this means we need to also account for the time when a cluster is first created. (and maybe that should be another field in the enforcer)
___
*[`pkg/server/license/enforcer.go` line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5UycAN9a_4WqNiOY8n:-O5UycAN9a_4WqNiOY8o:byqgqi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6a00753fc5968ad190a43d7626aa8b967e4f21/pkg/server/license/enforcer.go#L327)):*
> ```Go
> // logged recently. The purpose is to alert the user about throttling without
> // overwhelming the cockroach log.
> func (e *Enforcer) maybeLogError(ctx context.Context, err error, lastLogTimestamp *atomic.Int64) {
> ```

i don't see a strong reason to log this error, since the error will already be getting returned to the client. but if you feel like keeping this log is helpful, i'm not opposed. (maybe include a comment describing why it's helpful.)
___
*[`pkg/ccl/utilccl/main_test.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5Uyszz6vQ3lT8M9PQh:-O5Uyszz6vQ3lT8M9PQi:b97jarf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6a00753fc5968ad190a43d7626aa8b967e4f21/pkg/ccl/utilccl/main_test.go#L22)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/randutil"
> )
> ```

looks like this package was missing a
```
//go:generate ../../util/leaktest/add-leaktest.sh *_test.go
```

line, but we should add it now

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129880)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @rafiss)

___
*[`pkg/server/license/enforcer.go` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5UtSbdD-jA82fOYCmK:-O5t1L9-A4Y_1ir6FiE-:b-o77clc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6a00753fc5968ad190a43d7626aa8b967e4f21/pkg/server/license/enforcer.go#L32)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: "delay" feels like the wrong term here. should we call it a "telemetry grace period" or something like that?
</blockquote></details>

I agree "delay" isn't right. We already have a grace period for the license, so I think it may be confusing to have a grace period for receiving telemetry data. How about using "interval" to talk about the length of time and "deadline" to talk about a specific timestamp that we must receive the telemetry data by?
___
*[`pkg/server/license/enforcer.go` line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5Ui-qR4ra2HWUCBbY3:-O5tH_0b3TTiQXPGUbaY:b-4hpvhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6a00753fc5968ad190a43d7626aa8b967e4f21/pkg/server/license/enforcer.go#L248)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm not sure where to make this change, but one more requirement from the spec is:
> All single-node clusters are permanently exempt from throttling

we could implement that as an infinite grace period, or we could do it at a lower level and just short-circuit the license check if it's single node
</blockquote></details>

Good point. I ended up adding it as a big hammer that can be turned off if running as single node.
___
*[`pkg/server/license/enforcer.go` line 250 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5UsWra9NHiS43-2Fwt:-O5xRANS2C-bAnO77KdG:bjid9e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6a00753fc5968ad190a43d7626aa8b967e4f21/pkg/server/license/enforcer.go#L250)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think this calculation covers all the cases. the spec says
- New cluster is created and no license key has been added: 7 day grace period
- Cluster running without a license is upgraded to a patch version that requires a license: 30 day grace period

so this means we need to also account for the time when a cluster is first created. (and maybe that should be another field in the enforcer)
</blockquote></details>

I overlooked this requirement. We need to persist this to disk; otherwise, we'll lose track of the grace period end time if a new cluster is created and then restarted. Instead of adding a new key to the system keyspace, I’ll repurpose the one I previously added. It will now store the grace period end time rather than the start time, allowing us to set the grace period to either 7 or 30 days.
___
*[`pkg/server/license/enforcer.go` line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5UycAN9a_4WqNiOY8n:-O5xLT9F1xnsaENnP4Jk:bylmhtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6a00753fc5968ad190a43d7626aa8b967e4f21/pkg/server/license/enforcer.go#L327)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't see a strong reason to log this error, since the error will already be getting returned to the client. but if you feel like keeping this log is helpful, i'm not opposed. (maybe include a comment describing why it's helpful.)
</blockquote></details>

I included this because the product brief mentions logging alerts in CockroachDB when throttling occurs. Additionally, I think it will serve as a helpful breadcrumb for debugging, especially in automated test runs where the client response might not always be examined.

I'll update the function comment.
___
*[`pkg/ccl/utilccl/main_test.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5Uyszz6vQ3lT8M9PQh:-O5xMyEv6KLwNiMKfgQY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6a00753fc5968ad190a43d7626aa8b967e4f21/pkg/ccl/utilccl/main_test.go#L22)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

looks like this package was missing a
```
//go:generate ../../util/leaktest/add-leaktest.sh *_test.go
```

line, but we should add it now
</blockquote></details>

Done.

**Review by fqazi — APPROVED** [review]
Just some questions / minor suggestions.

:lgtm_strong: 

> Reviewed 4 of 11 files at r1, 1 of 2 files at r3, 10 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-:-O5yeGOY5S4FTEbF4UU_:bpaulbl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kyle-a-wong, @rafiss, and @spilchen)

___
*[`pkg/ccl/utilccl/license_check.go` line 336 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5yeA1tDh0P0zXt1NPf:-O5yeA1tDh0P0zXt1NPg:bnlzzlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced1bd7689b35d2eebfc488e8ee56d35795670b8/pkg/ccl/utilccl/license_check.go#L336)):*
> ```Go
> 				licenseType = licenseserver.LicTypeEvaluation
> 			default:
> 				licenseType = licenseserver.LicTypeEnterprise
> ```

I think for the purpose of enforcement non-commercial behaves the same?
___
*[`pkg/server/license/enforcer.go` line 265 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5ycPRp5WLHvujKX8Lx:-O5ycPRp5WLHvujKX8Ly:b-swcff5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced1bd7689b35d2eebfc488e8ee56d35795670b8/pkg/server/license/enforcer.go#L265)):*
> ```Go
> 				"Cockroach Labs reporting server. You can also consider changing your license to one that doesn't "+
> 				"require diagnostic reporting to be emitted.")
> 		e.maybeLogError(ctx, err, &e.lastTelemetryThrottlingLogTime)
> ```

Just from a diagnostic view point should we log the last time telemetry was contacted?
___
*[`pkg/server/license/enforcer.go` line 292 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5ycdQ4C-4Ob0bqt1Me:-O5ycdQ4C-4Ob0bqt1Mf:b-rdcw5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced1bd7689b35d2eebfc488e8ee56d35795670b8/pkg/server/license/enforcer.go#L292)):*
> ```Go
> 		e.licenseRequiresTelemetry.Store(false)
> 	default:
> 		e.storeNewGracePeriodEndDate(timeutil.UnixEpoch, 0)
> ```

This almost feels like an assertion failure, since I don't think there is any case that should get us here?
___
*[`pkg/server/license/enforcer_test.go` line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5ybsQz3d6BaSwH4ZCT:-O5ybsQz3d6BaSwH4ZCU:b-ee1d65) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced1bd7689b35d2eebfc488e8ee56d35795670b8/pkg/server/license/enforcer_test.go#L93)):*
> ```Go
> 
> 	const UnderTxnThreshold = 3
> 	const OverTxnThreshold = 7
> ```

Do you think its worth checking at the threshold?

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129880)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi, @kyle-a-wong, and @rafiss)

___
*[`pkg/ccl/utilccl/license_check.go` line 336 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5yeA1tDh0P0zXt1NPf:-O611_aOEfiCoDtLnseC:b-emsh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced1bd7689b35d2eebfc488e8ee56d35795670b8/pkg/ccl/utilccl/license_check.go#L336)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think for the purpose of enforcement non-commercial behaves the same?
</blockquote></details>

Yes, that’s correct. I group everything else under enterprise, as the enforcement code doesn’t differentiate between them.
___
*[`pkg/server/license/enforcer.go` line 265 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5ycPRp5WLHvujKX8Lx:-O614ZXd8dc6m1RSjNSE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced1bd7689b35d2eebfc488e8ee56d35795670b8/pkg/server/license/enforcer.go#L265)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Just from a diagnostic view point should we log the last time telemetry was contacted?
</blockquote></details>

Done.
___
*[`pkg/server/license/enforcer.go` line 292 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5ycdQ4C-4Ob0bqt1Me:-O615LiwBX_m0_tPTgt0:bl53q3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced1bd7689b35d2eebfc488e8ee56d35795670b8/pkg/server/license/enforcer.go#L292)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This almost feels like an assertion failure, since I don't think there is any case that should get us here?
</blockquote></details>

This applies specifically to the enterprise license. I replaced `default` with `LicTypeEnterprise` to make it more explicit. Since this is in a no-errors code path—where config settings change callbacks can't fail—I'd prefer to avoid adding an assertion.
___
*[`pkg/server/license/enforcer_test.go` line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/129880#-O5ybsQz3d6BaSwH4ZCT:-O616Ke04BfAV-XlIG-4:b-8n327p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced1bd7689b35d2eebfc488e8ee56d35795670b8/pkg/server/license/enforcer_test.go#L93)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Do you think its worth checking at the threshold?
</blockquote></details>

Yes, good point.

**Comment by spilchen** [comment]
TFTR!

bors r=rafiss,fqazi

**Comment by spilchen** [comment]
bors r=rafiss,fqazi

**Pull request merged**
