### PR TITLE
roachtest: add admissioncontrol/index-overload

### PR DESCRIPTION
**Pull request by andrewbaptist**
This test sets up a 3 node cluster and measures the impact of creating
an index while a controlled KV workload is running. The test measures
two things
* The baseline KV workload P99 latency
* The impact on running index creation on the workload.

The KV workload is designed to use about 20% of the CPU and IO
resources of the system. Index creation is impactful by both reading
a lot of data and writing a large index, however the primary impact
is that it causes enough L0 inversion to make user traffic pause.

Release note: None

### CODE REVIEW

**Review by irfansharif — COMMENTED** [review]
Do you happen to have the prometheus data dump from a full test run lying around? I'd like to take a look.

**Comment by andrewbaptist** [comment]
Files from a run

[prometheus-snapshot.tar.gz](https://github.com/cockroachdb/cockroach/files/9728536/prometheus-snapshot.tar.gz)

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/admission_control.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj3Ovx5n7Pw7NXJFtR:-NDj3Ovx5n7Pw7NXJFtS:b-1k4p7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control.go#L89)):*
> ```Go
> // throttleWriteIO will limit the write io performance of a node to the provided
> // rate using Linux capabilities.
> func throttleWriteIO(
> ```

What's `rate` in? Bytes? Could be made clearer. If we stop reading the rate from the cluster and hard-coded something we've experimentally verified to work, you could do something like below which makes it slightly more readable.

```
throttleWriteIO(..., 1<<20 /* 1 MiB */)
```

Also, instead of this bare function to throttle IO, could you create a cgroupHelper struct of sorts? You can have it initialized with everything you need to hold onto, like the surrounding test.Test or cluster.Cluster, and it'll be easy to use it to limit a specific node along some specific dimension (bandwidth, CPU).
___
*[`pkg/cmd/roachtest/tests/admission_control.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj4EVK1xEFEi04YP9A:-NDj4EVK1xEFEi04YP9B:b60yko1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control.go#L92)):*
> ```Go
> 	ctx context.Context, t test.Test, c cluster.Cluster, node option.NodeListOption, rate int,
> ) {
> 	t.Status(fmt.Sprintf("throttling IO to (%d Bps) and running to verify no impact", rate))
> ```

Use humanize.Bytes for a more readable form. Drop the "... and running to verify no impact", too presumptive of the caller's intent.
___
*[`pkg/cmd/roachtest/tests/admission_control.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj4dfN6Ns-Q6KpXZOK:-NDj4dfN6Ns-Q6KpXZOL:bjmhs05) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control.go#L94)):*
> ```Go
> 	t.Status(fmt.Sprintf("throttling IO to (%d Bps) and running to verify no impact", rate))
> 
> 	cmd := `DEV=$(lsblk | grep /mnt/data1 | cut -f 2 -d " ") 
> ```

Use this instead: https://github.com/cockroachdb/cockroach/pull/81516/files#diff-f3e802dd4d8331559cd9e53691628cfdef7d38671a8fb7bb5b4cb9c1bc59b5f5R256

Writing to the cgroup files directly in this way can cause your limits to be erased automagically.
___
*[`pkg/cmd/roachtest/tests/admission_control.go` line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj4Nql0FJZ37mnul47:-NDj4Nql0FJZ37mnul48:b-mw6q43) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control.go#L98)):*
> ```Go
> 	cmd = fmt.Sprintf(cmd, rate)
> 
> 	t.Status(fmt.Sprintf("running cmd: `%s`", cmd))
> ```

This likely pollutes the test log, worth dropping.
___
*[`pkg/cmd/roachtest/tests/admission_control.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDixTwi-2xzHaRIuf-T:-NDixTwi-2xzHaRIuf-U:bfykjg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control.go#L105)):*
> ```Go
> // It imports the dashboard at http://go.crdb.dev/p/snapshot-admission-control-grafana. As part
> // of setting up the cluster.
> func setupAdmissionControlGrafana(ctx context.Context, t test.Test, c cluster.Cluster) func() {
> ```

https://github.com/cockroachdb/cockroach/pull/89482#pullrequestreview-1133547508. Let's make the following helper in the prometheus package instead:

```
func MakeConfig(monitor install.Node, cluster install.Nodes, dashboardURL string, additional ...ScrapeConfigs) *Config
```
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDixlNC5oVoFa5L_6wp:-NDixlNC5oVoFa5L_6wq:basdymz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L42)):*
> ```Go
> 		// 	Tags:    []string{`weekly`},
> 		Cluster: r.MakeClusterSpec(4, spec.CPU(8)),
> 		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
> ```

Even if we're using cgroup things below, make this work with c.IsLocal() and verify it using --local. It's often much faster to smoke test roachtests by running some minified form locally -- I've burned far too much time and $$$ importing something for minutes before realizing I had some SQL syntax typo further below that a local, cheap run could've sussed out. It makes for much faster iteration time in the same way .SkipInit() was intended.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDiyM7VA2giLXK3CLEq:-NDiyM7VA2giLXK3CLEr:bavftk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L51)):*
> ```Go
> 
> 			if !t.SkipInit() {
> 				cleanupFunc := setupAdmissionControlGrafana(ctx, t, c)
> ```

Move this out of the SkipInit block like we do in the other roachtest(s).
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDiyXl_C8-AmNDzQvGw:-NDiyXl_C8-AmNDzQvGx:b-1zt6iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L57)):*
> ```Go
> 				// leaseholders on just n1.
> 				t.Status(fmt.Sprintf("initializing kv dataset (<%s)", time.Minute))
> 				splits := ifLocal(c, " --splits=3", " --splits=100")
> ```

Lets use the TPC-C workload? The queries there should not observe this new junk index, and it's more sensitive tail latency wise given the non-trivial requests it generates. There's code to cargocult from #89482 now. Feel free to ignore this suggestion if the data dump here shows useful things.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDizKr7DaYzPvfckmmF:-NDizKr7DaYzPvfckmmG:bb4y9b8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L65)):*
> ```Go
> 			}
> 
> 			duration, err := time.ParseDuration(ifLocal(c, "20s", "5m"))
> ```

[nit] Don't re-use duration and some multipliers below, introduce separate vars for each thing. Right below for example the status message is incorrect, printing out `duration` and not `(4 * duration)`.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDizvuR7Th-qJrv6pAY:-NDizvuR7Th-qJrv6pAZ:bzejw0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L72)):*
> ```Go
> 			m.Go(func(ctx context.Context) error {
> 				duration := " --duration=" + (duration * 4).String()
> 				concurrency := ifLocal(c, "  --concurrency=8", " --concurrency=2048")
> ```

Do we need this high a concurrency given the low max rate? I see that you're trying to make it open-loop, but do verify that the workload generator itself is well behaved on the small VM it's running.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj-9WP9A14NI0ETZy2:-NDj-9WP9A14NI0ETZy3:briyn9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L84)):*
> ```Go
> 
> 			nodeList := c.Range(1, crdbNodes)
> 			medianWriteIO := getWriteIO(ctx, t, c, nodeList)
> ```

Retrieving this feels a bit fragile and could vary across runs depending on load distribution. We're controlling the workload, so we should have a very good idea after a few runs for what this looks like, and it's just something we could hard code. We're doing so somewhat in other tests now where I'm assuming a backup schedule of N minutes is sufficient, or that snapshots take X minutes to fully transfer so swapping zone configs every X+delta minutes works ok. Just trying to reduce as much chance of flakiness/non-determinism as possible since these tests will primarily exist to generate prometheus dumps (for now).
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj-uWd9WVv045IfzJH:-NDj-uWd9WVv045IfzJI:b56f7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L90)):*
> ```Go
> 			time.Sleep(duration)
> 
> 			// TODO: Iterate through different index types (small, medium, large)
> ```

Let's just pick `order_line` and be done with.

**Review by andrewbaptist — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/admission_control.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj3Ovx5n7Pw7NXJFtR:-NE1L3fI9FhaF6GuXIkN:b-dafx15) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control.go#L89)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

What's `rate` in? Bytes? Could be made clearer. If we stop reading the rate from the cluster and hard-coded something we've experimentally verified to work, you could do something like below which makes it slightly more readable.

```
throttleWriteIO(..., 1<<20 /* 1 MiB */)
```

Also, instead of this bare function to throttle IO, could you create a cgroupHelper struct of sorts? You can have it initialized with everything you need to hold onto, like the surrounding test.Test or cluster.Cluster, and it'll be easy to use it to limit a specific node along some specific dimension (bandwidth, CPU).
</blockquote></details>

Done. I didn't want to hardcode a number here as it becomes hard to change if we change things internally (for instance a change to pebble that changes write amplification). 

I called it `hardware_limiter` as I'm hoping that it applies to IO, bandwidth, and CPU and I'm not sure if we will use the same cgroup mechanism for all. Even if we do, it is more clear with this name. 
___
*[`pkg/cmd/roachtest/tests/admission_control.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj4EVK1xEFEi04YP9A:-NE1NU7y-WHdjmlqBfV8:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control.go#L92)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Use humanize.Bytes for a more readable form. Drop the "... and running to verify no impact", too presumptive of the caller's intent.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/admission_control.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj4dfN6Ns-Q6KpXZOK:-NE1Nk2E1866Dq486qUA:bm1l36m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control.go#L94)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Use this instead: https://github.com/cockroachdb/cockroach/pull/81516/files#diff-f3e802dd4d8331559cd9e53691628cfdef7d38671a8fb7bb5b4cb9c1bc59b5f5R256

Writing to the cgroup files directly in this way can cause your limits to be erased automagically.
</blockquote></details>

Nice - I hadn't thought about using systemctl, but this is definitely better
___
*[`pkg/cmd/roachtest/tests/admission_control.go` line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj4Nql0FJZ37mnul47:-NE1Nxqb6PzRVyEutp4j:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control.go#L98)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This likely pollutes the test log, worth dropping.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDizKr7DaYzPvfckmmF:-NE1RRVa3o0-n1ekJALd:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L65)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] Don't re-use duration and some multipliers below, introduce separate vars for each thing. Right below for example the status message is incorrect, printing out `duration` and not `(4 * duration)`.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj-uWd9WVv045IfzJH:-NE1S1Pz2JHFY9Qb0wxR:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L90)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Let's just pick `order_line` and be done with.
</blockquote></details>

Done

**Review by irfansharif — APPROVED** [review]
I'm not sure I understand enough about the L0 sublevels thing to know that this is reproducing what we want to reproduce but in a smaller form, but am fine merging it for now. Do post a more current prometheus dump given this test code is now different. It's useful to have so we can come around if needed.

> Reviewed 1 of 5 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-:-NFAcAze0kaFvNlzNje7:b12kiva)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @srosenberg)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFAb2lD36UYCj2HIbia):*
This mentions three things but lists two.
___
*[`-- commits` line 12 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFAb6uV5MKR4fjdmong):*
Of what resource, CPU? IO? Both? Mention kv50 explicitly perhaps.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDiyXl_C8-AmNDzQvGw:-NFAakl_BeR16XbI0CWC:b-z87h73) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L57)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Lets use the TPC-C workload? The queries there should not observe this new junk index, and it's more sensitive tail latency wise given the non-trivial requests it generates. There's code to cargocult from #89482 now. Feel free to ignore this suggestion if the data dump here shows useful things.
</blockquote></details>

I'm going to assume the data dump showed measurable impact. Do post it here before merging.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDizvuR7Th-qJrv6pAY:-NFAbmwxBBb_sxR0eKJI:b-6tf7sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L72)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Do we need this high a concurrency given the low max rate? I see that you're trying to make it open-loop, but do verify that the workload generator itself is well behaved on the small VM it's running.
</blockquote></details>

I'm going to assume you've verified that the workload is well-behaved. BTW, do you prefer github reviews or reviewable? Happy to use either. You can respond to these inline + close the comments in both out so it's easier to follow what's addressed/isn't.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj-uWd9WVv045IfzJH:-NFAaAPg9_fxwPnGm9nw:b-rfh5tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L90)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I'm going to assume the stock column takes just as long as order_line given that's what we're using.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFA_LKmDJVncDsbh3o3:-NFA_LKmDJVncDsbh3o4:b-avsv0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d450491acc4666db06858a7456d6f7673a62c1b0/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L29)):*
> ```Go
> // This test sets up a 3-node CRDB cluster on 8vCPU machines, loads it up with a
> // large TPC-C dataset, and sets up a foreground load of kv50/1b. It then
> // attempts to create a several "dummy" secondary index on the table while the
> ```

Drop "several" and mention the lowering of L0 file count + why.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFA_SrI3Lorw_3_yNnS:-NFA_SrI3Lorw_3_yNnT:b-e1o77n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d450491acc4666db06858a7456d6f7673a62c1b0/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L59)):*
> ```Go
> 			if !t.SkipInit() {
> 				// Initialize the kv database with replicas on all nodes but
> 				// leaseholders on just n1.
> ```

This comment doesn't fully apply; we're not messing with zone configs like in the snapshot-overload test.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFAbOi08KWe0MRj6s-u:-NFAbOi08KWe0MRj6s-v:b-lac41z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d450491acc4666db06858a7456d6f7673a62c1b0/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L70)):*
> ```Go
> 
> 				// Setting this low allows us to hit overload. In a larger cluster with
> 				// more nodes and larger tables, it will hit the unmodified 1000 limit.
> ```

Leave a TODO to edit this test later on to not need this lowering. It's better to have $$$ tests running infrequently that use unmodified cluster settings unless the modifications are very clearly skewing things to stress a particular fix. Here I don't yet understand what L0 file count has do with things but I hope to in the coming few days.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFA_acX3GX2Mq_DyV6o:-NFA_acX3GX2Mq_DyV6p:bh8wmff) ([raw file](https://github.com/cockroachdb/cockroach/blob/d450491acc4666db06858a7456d6f7673a62c1b0/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L71)):*
> ```Go
> 				// Setting this low allows us to hit overload. In a larger cluster with
> 				// more nodes and larger tables, it will hit the unmodified 1000 limit.
> 				t.Status(fmt.Sprintf("decreasing L0 overload threshold (%s)", duration))
> ```

This step will take <30s, not 10m which is what the log will suggest. 
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFA_B7f526XFadBuV0Q:-NFA_B7gEgPICeTIkd8Q:bmv210o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d450491acc4666db06858a7456d6f7673a62c1b0/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L97)):*
> ```Go
> 			t.Status(fmt.Sprintf("starting index creation (%s)", duration))
> 			if _, err := db.ExecContext(ctx,
> 				"CREATE INDEX test_index ON tpcc.stock(s_quantity)",
> ```

Instead of dropping the index below (which if anything can mess with the metrics of this otherwise "one-shot" test), pick a unique index name, for ex. suffixed with the timestamp: `tpcc_stock_quantity_20221024_15_57`.

**Comment by andrewbaptist** [comment]
Latest prometheus
[prometheus-snapshot.tar.gz](https://github.com/cockroachdb/cockroach/files/9856172/prometheus-snapshot.tar.gz)

**Review by andrewbaptist — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @srosenberg)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFAb2lD36UYCj2HIbia):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This mentions three things but lists two.
</blockquote></details>

Done
___
*[`-- commits` line 12 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFAb6uV5MKR4fjdmong):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Of what resource, CPU? IO? Both? Mention kv50 explicitly perhaps.
</blockquote></details>

Done, cleaned up the commit message.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDixlNC5oVoFa5L_6wp:-NE1TdFrARDBffRdNKNF:b-c9edrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L42)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Even if we're using cgroup things below, make this work with c.IsLocal() and verify it using --local. It's often much faster to smoke test roachtests by running some minified form locally -- I've burned far too much time and $$$ importing something for minutes before realizing I had some SQL syntax typo further below that a local, cheap run could've sussed out. It makes for much faster iteration time in the same way .SkipInit() was intended.
</blockquote></details>

Done - removed the need for workload limits.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDiyM7VA2giLXK3CLEq:-NE1Oo8d0k0ws5UksIjs:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L51)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Move this out of the SkipInit block like we do in the other roachtest(s).
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDiyXl_C8-AmNDzQvGw:-NE1Q5ZY6b2MAH-hsSdY:b-qmxzmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L57)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I'm going to assume the data dump showed measurable impact. Do post it here before merging.
</blockquote></details>

Done, posted the prometheus dump.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDizvuR7Th-qJrv6pAY:-NE1RTRoERCJ0desrTPo:btrjigv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L72)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I'm going to assume you've verified that the workload is well-behaved. BTW, do you prefer github reviews or reviewable? Happy to use either. You can respond to these inline + close the comments in both out so it's easier to follow what's addressed/isn't.
</blockquote></details>

This workload is well behaved prior to index creation. 
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj-9WP9A14NI0ETZy2:-NE1RhIWBSdUAHlWuVkR:b-k5phzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L84)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Retrieving this feels a bit fragile and could vary across runs depending on load distribution. We're controlling the workload, so we should have a very good idea after a few runs for what this looks like, and it's just something we could hard code. We're doing so somewhat in other tests now where I'm assuming a backup schedule of N minutes is sufficient, or that snapshots take X minutes to fully transfer so swapping zone configs every X+delta minutes works ok. Just trying to reduce as much chance of flakiness/non-determinism as possible since these tests will primarily exist to generate prometheus dumps (for now).
</blockquote></details>

Done, removed the rate limiting completely.
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NDj-uWd9WVv045IfzJH:-NFAi_Y95ALSW2qA0l3J:bdm285k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dda9131d707cc45e06bacfd1dfcf4b2012a5beb/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L90)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I'm going to assume the stock column takes just as long as order_line given that's what we're using.
</blockquote></details>

Done, order_line was taking too long, I wanted something on the order of ~10 minutes. Experimenting found that stock was best. (customer was too short and order_line was too long)
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFA_LKmDJVncDsbh3o3:-NFAgryd9OsS4fPtkRQn:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d450491acc4666db06858a7456d6f7673a62c1b0/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L29)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Drop "several" and mention the lowering of L0 file count + why.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFA_SrI3Lorw_3_yNnS:-NFAhVIm8kGhQ5xPv-Gw:b-i8xfmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d450491acc4666db06858a7456d6f7673a62c1b0/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L59)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This comment doesn't fully apply; we're not messing with zone configs like in the snapshot-overload test.
</blockquote></details>

Done, removed unnecessary comment
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFAbOi08KWe0MRj6s-u:-NFAhe8A54o_2JUkSPNZ:b2hx5wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d450491acc4666db06858a7456d6f7673a62c1b0/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L70)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Leave a TODO to edit this test later on to not need this lowering. It's better to have $$$ tests running infrequently that use unmodified cluster settings unless the modifications are very clearly skewing things to stress a particular fix. Here I don't yet understand what L0 file count has do with things but I hope to in the coming few days.
</blockquote></details>

Done, added a TODO
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFA_acX3GX2Mq_DyV6o:-NFAi8yKBQc0q6tvyGTj:b-6n002l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d450491acc4666db06858a7456d6f7673a62c1b0/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L71)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This step will take <30s, not 10m which is what the log will suggest. 
</blockquote></details>

Done, fixed logging to remove time (this is done very quickly)
___
*[`pkg/cmd/roachtest/tests/admission_control_index_overload.go` line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89324#-NFA_B7f526XFadBuV0Q:-NFAk6sc542UxLxKBqhE:bjs4lmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d450491acc4666db06858a7456d6f7673a62c1b0/pkg/cmd/roachtest/tests/admission_control_index_overload.go#L97)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Instead of dropping the index below (which if anything can mess with the metrics of this otherwise "one-shot" test), pick a unique index name, for ex. suffixed with the timestamp: `tpcc_stock_quantity_20221024_15_57`.
</blockquote></details>

Done, I removed the drop index part and simply let the system choose the name.

**Pull request merged**
