### PR TITLE
storage: fix TestGetTruncatableIndexes

### LINKED ISSUE #7056: storage: TestGetTruncatableIndexes looks buggy
From commentary on #7040.

> `TestGetTruncatableIndexes` looks buggy: it does some of its testing with a Replica which is not attached to a store, so it always returns 0 because `RaftStatus` is nil when accessed via the store.
> 
> The parts of that test that use `newRng` need some work. The first part is kind of meaningless now, but will be significant once Arjun reintroduces lazy raft groups. I'm not sure what the last block of the test is trying to do with `newRng`; it looks like maybe it's supposed to use r instead.

### PR DESCRIPTION
**Pull request by BramGruneir**
Fixes #7056, #9445

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9833)

### CODE REVIEW

**Comment by BramGruneir** [comment]
It was more of a complete re-write than a fix.

**Comment by bdarnell** [comment]
LGTM, but it's not clear to me why the test was flaky before or why this fixes it.

**Comment by tamird** [comment]
Remember that the github requires the form:

Fixes #xxxx.
Fixes #yyyy.

to close more than one issue on merge.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/raft_log_queue_test.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KThPY1CHeQDRV6ioPY-:-KThPY1CHeQDRV6ioPY0:b-cm5c0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae63117655bf7cf6534fcd359c7890f9172ec7f/storage/raft_log_queue_test.go#L121)):*
> ```Go
> 	}
> 
> 	getIndexes := func(r *Replica) (uint64, uint64, uint64, error) {
> ```

seems like there's no need for this to take an argument; nothing other than `r` above is passed.

---

*[storage/raft_log_queue_test.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KThQLXa1fg8aJq_FX0L:-KThQLXa1fg8aJq_FX0M:by0bzqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae63117655bf7cf6534fcd359c7890f9172ec7f/storage/raft_log_queue_test.go#L195)):*
> ```Go
> 
> 	// Again, enable the raft log scanner and and force a truncation. This time
> 	// we expect no truncation to occur.
> ```

this is problematic compared to the above because of the util.SucceedsSoon used above. how do you know that you didn't observe truncation just because you didn't wait long enough?

is it possible to more reliably know when the queue has done its thing?

---

*[storage/raft_log_queue_test.go, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KThQgNTfnVD9w1xZRLC:-KThQgNTfnVD9w1xZRLD:bvqaq69) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae63117655bf7cf6534fcd359c7890f9172ec7f/storage/raft_log_queue_test.go#L206)):*
> ```Go
> 
> 	if cFirst != dFirst {
> 		t.Errorf("truncation should not have occurred, but firstIndex changed from %d -> %d", cFirst, dFirst)
> ```

you use the language "went from" everywhere else. let's be consistent (though "changed" is better).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-:-KThP6J-fWg00tJODD3V:bjtit8n)*

**Comment by BramGruneir** [comment]
@bdarnell I decided to just re-write the test.  But I think it is the delay between sending the truncate command and the indexes being updated was the culprit.  

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/raft_log_queue_test.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KThPY1CHeQDRV6ioPY-:-KTj13azFyuzHO56Z3dk:b-l97i80) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae63117655bf7cf6534fcd359c7890f9172ec7f/storage/raft_log_queue_test.go#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> seems like there's no need for this to take an argument; nothing other than `r` above is passed.
</details>
Good point, fixed.

---

*[storage/raft_log_queue_test.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KThQLXa1fg8aJq_FX0L:-KTj1IoZAenQ1H02oFwU:b-yr9av9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae63117655bf7cf6534fcd359c7890f9172ec7f/storage/raft_log_queue_test.go#L195)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is problematic compared to the above because of the util.SucceedsSoon used above. how do you know that you didn't observe truncation just because you didn't wait long enough?
> 
> is it possible to more reliably know when the queue has done its thing?
</details>
I tried to do just that,  It would require writing a function that calls maybeAdd and then checks the size of the queue, while also retooling the scanner no to add in the replica on its own.  It's a headache that I don't think adds any benefit.

What should be of note, is that, in only around 1 of 10,000 runs, I would get a failure without the succeedsSoon while stressing.  So in almost all cases, the normal force should be sufficient for testing.

---

*[storage/raft_log_queue_test.go, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KThQgNTfnVD9w1xZRLC:-KTj2lMf1ZIc3WAoUQUV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae63117655bf7cf6534fcd359c7890f9172ec7f/storage/raft_log_queue_test.go#L206)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> you use the language "went from" everywhere else. let's be consistent (though "changed" is better).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-:-KTj-pzP4FSaLtpWkF7o:b684r2d)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/raft_log_queue_test.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KThQLXa1fg8aJq_FX0L:-KTjNE1e3Y5EUskiqnFc:bv32r8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae63117655bf7cf6534fcd359c7890f9172ec7f/storage/raft_log_queue_test.go#L195)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> I tried to do just that,  It would require writing a function that calls maybeAdd and then checks the size of the queue, while also retooling the scanner no to add in the replica on its own.  It's a headache that I don't think adds any benefit.
> 
> What should be of note, is that, in only around 1 of 10,000 runs, I would get a failure without the succeedsSoon while stressing.  So in almost all cases, the normal force should be sufficient for testing.
</details>
Heh, did you stress it on GCE with `-p {num}` where num is > 3x`number-of-cores`? Anyway, this seems fragile and at least needs a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-:-KTjNPGoNYGRGljYwoxo:bnfp4nl)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/raft_log_queue_test.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KThQLXa1fg8aJq_FX0L:-KTjYwu09cL3GqVTUBgw:boz8qy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae63117655bf7cf6534fcd359c7890f9172ec7f/storage/raft_log_queue_test.go#L195)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Heh, did you stress it on GCE with `-p {num}` where num is > 3x`number-of-cores`? Anyway, this seems fragile and at least needs a comment.
</details>
I stressed it locally with 3x.

And I added a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/raft_log_queue_test.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KThQLXa1fg8aJq_FX0L:-KTjac07h83lDvJe4IFJ:bthrhwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae63117655bf7cf6534fcd359c7890f9172ec7f/storage/raft_log_queue_test.go#L195)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> I stressed it locally with 3x.
> 
> And I added a comment.
</details>
OK. Just so you know, stress on GCE is (for reasons I don't fully understand) vastly more capable of reproducing these timing issues than local stress.

---

*[storage/raft_log_queue_test.go, line 200 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTjan91KGMkvahuzh1a:-KTjan91KGMkvahuzh1b:bnhqc81) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c8fc4e623bb864e471402f124945e0923a2cde/storage/raft_log_queue_test.go#L200)):*
> ```Go
> 	store.SetRaftLogQueueActive(false)
> 
> 	// It's not possible to use a SucceedsSoon in this case as we don't expect
> ```

This comment should explain that this is fragile, not why it isn't possible to use SucceedsSoon. The point of the comment is to alert future investigators that the issue they are seeing may be caused by this fragility.

Also, what is "the normal force"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/raft_log_queue_test.go, line 200 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTjan91KGMkvahuzh1a:-KTjkXrPz65j2allC3iB:bc2ohsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c8fc4e623bb864e471402f124945e0923a2cde/storage/raft_log_queue_test.go#L200)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> This comment should explain that this is fragile, not why it isn't possible to use SucceedsSoon. The point of the comment is to alert future investigators that the issue they are seeing may be caused by this fragility.
> 
> Also, what is "the normal force"?
</details>
I just outright removed this section.  There's no need for it and this functionality is tested elsewhere.  See client_raft_log_queue.test. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/raft_log_queue_test.go, line 200 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTjan91KGMkvahuzh1a:-KTjlR_e5lmFmdzjWkUZ:b-g8lcup) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c8fc4e623bb864e471402f124945e0923a2cde/storage/raft_log_queue_test.go#L200)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> I just outright removed this section.  There's no need for it and this functionality is tested elsewhere.  See client_raft_log_queue.test. 
</details>
That test only checks FirstIndex, not getTruncatableIndexes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833)*

**Comment by BramGruneir** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/raft_log_queue_test.go, line 200 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTjan91KGMkvahuzh1a:-KTjmDrS-qWyAVlk2A87:bz5jbs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c8fc4e623bb864e471402f124945e0923a2cde/storage/raft_log_queue_test.go#L200)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> That test only checks FirstIndex, not getTruncatableIndexes.
</details>
A truncation always changes FirstIndex.  But looking closer at it, it suffers the same problem with no succeedsSoon on the after check.

I'm going to add it back in with a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/raft_log_queue_test.go, line 200 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTjan91KGMkvahuzh1a:-KTjmtinM8BheF4PNUk5:baoicx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c8fc4e623bb864e471402f124945e0923a2cde/storage/raft_log_queue_test.go#L200)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> A truncation always changes FirstIndex.  But looking closer at it, it suffers the same problem with no succeedsSoon on the after check.
> 
> I'm going to add it back in with a comment.
</details>
Yes, that test is equally fragile and could also benefit from the same comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833)*

**Comment by BramGruneir** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/raft_log_queue_test.go, line 200 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTjan91KGMkvahuzh1a:-KTjoS9hnzduXaT0egck:b9d80d9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c8fc4e623bb864e471402f124945e0923a2cde/storage/raft_log_queue_test.go#L200)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yes, that test is equally fragile and could also benefit from the same comment.
</details>
Of course.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/client_raft_log_queue_test.go, line 115 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTjqeClIezeYUvz3_LM:-KTjqeClIezeYUvz3_LN:bnohfyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5071ba6e65ea76614a24f2198d26d7b728049c45/storage/client_raft_log_queue_test.go#L115)):*
> ```Go
> 	// expect a truncation and can wait on it with succeedsSoon, we can't do
> 	// that here. So this check may be fragile in that the truncation my
> 	// erroneously occur but getFirstIndex might not pick up that truncation
> ```

"So this check is fragile in that the truncation triggered here may lose the race against the call to `GetFirstIndex` below, giving a false negative. Fixing this requires additional instrumentation of the queues, which was deemed to require too much work at the time of this writing."

---

*[storage/raft_log_queue_test.go, line 201 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTjrBQaFycibYt5cHVA:-KTjrBQbG2AvFaoGMUot:bnohfyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5071ba6e65ea76614a24f2198d26d7b728049c45/storage/raft_log_queue_test.go#L201)):*
> ```Go
>  
> 	// Unlike the last iteration, where we expect a truncation and can wait on
> 	// it with succeedsSoon, we can't do that here. So this check may be fragile
> ```

"So this check is fragile in that the truncation triggered here may lose the race against the call to `GetFirstIndex` below, giving a false negative. Fixing this requires additional instrumentation of the queues, which was deemed to require too much work at the time of this writing."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833)*

**Comment by BramGruneir** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/client_raft_log_queue_test.go, line 115 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTjqeClIezeYUvz3_LM:-KToj5yrTYOKPODWesF3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5071ba6e65ea76614a24f2198d26d7b728049c45/storage/client_raft_log_queue_test.go#L115)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "So this check is fragile in that the truncation triggered here may lose the race against the call to `GetFirstIndex` below, giving a false negative. Fixing this requires additional instrumentation of the queues, which was deemed to require too much work at the time of this writing."
</details>
Done.

---

*[storage/raft_log_queue_test.go, line 201 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTjrBQaFycibYt5cHVA:-KToj4q-4LiUUEjgK6ae:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5071ba6e65ea76614a24f2198d26d7b728049c45/storage/raft_log_queue_test.go#L201)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "So this check is fragile in that the truncation triggered here may lose the race against the call to `GetFirstIndex` below, giving a false negative. Fixing this requires additional instrumentation of the queues, which was deemed to require too much work at the time of this writing."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/raft_log_queue_test.go, line 205 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTokT4P9JrOchmDUM27:-KTokT4P9JrOchmDUM28:bm0wn7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b39b6b58916f73cb8e8d86cb65939712bcb58b8/storage/raft_log_queue_test.go#L205)):*
> ```Go
> 	// GetFirstIndex or getTruncatableIndexes, giving a false negative. Fixing
> 	// this requires additional instrumentation of the queues, which was deemed
> 	// to require too much work  at the time of this writing.
> ```

double space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-:-KTokWEQLhDPMGmdnQPB:bnfp4nl)*

**Comment by BramGruneir** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/raft_log_queue_test.go, line 205 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833#-KTokT4P9JrOchmDUM27:-KTonPIWyrofBotk0zna:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b39b6b58916f73cb8e8d86cb65939712bcb58b8/storage/raft_log_queue_test.go#L205)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> double space
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9833)*

**Pull request merged**
