### PR TITLE
roachprod: clean up `roachprod start` cmd generation

### PR DESCRIPTION
**Pull request by irfansharif**
Need to make some changes here (in future PRs), might as well clean it
up.

Release note: None.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52035#-:-MDMZn_kDVdQQtBBsMV6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @nvanbenschoten)

___
*[pkg/cmd/roachprod/install/cockroach.go, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52035#-MDMYoD56Ax81mp-HZxE:-MDMYoD56Ax81mp-HZxF:b-dymnbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/363d4f43597992590cc987ec25f31ed0d1a841b8/pkg/cmd/roachprod/install/cockroach.go#L361)):*
> ```Go
> 		                 2>> %[1]s/cockroach.stderr.log \
> 			|| (x=$?; cat %[1]s/cockroach.stderr.log; exit $x)
> `, logDir, keyCmd, nodes[nodeIdx], h.c.Tag, h.getEnvVars(), binary, startCmd, strings.Join(args, " "))
> ```

[nit] maybe put the arguments on separate lines and annotate with `// %[1]s` so you can more easily decipher the format

**Review by irfansharif — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52035#-:-MDMgPyr2SSmM5LTXa9n:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/cmd/roachprod/install/cockroach.go, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52035#-MDMYoD56Ax81mp-HZxE:-MDMgLkY9bo6N3mYqyyE:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/363d4f43597992590cc987ec25f31ed0d1a841b8/pkg/cmd/roachprod/install/cockroach.go#L361)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe put the arguments on separate lines and annotate with `// %[1]s` so you can more easily decipher the format
</blockquote></details>

Good idea, done.

**Comment by RaduBerinde** [comment]
___
*[pkg/cmd/roachprod/install/cockroach.go, line 360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52035#-MZ0oFMr2AxTCB6A0ude:-MZ0oFMr2AxTCB6A0udf:bnnu4ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdea7a86e54d5340f362aabc3a4f5db30375c7b8/pkg/cmd/roachprod/install/cockroach.go#L360)):*
> ```Go
> 		%[6]s %[7]s %[8]s >> %[1]s/cockroach.stdout.log \
> 		                 2>> %[1]s/cockroach.stderr.log \
> 			|| (x=$?; cat %[1]s/cockroach.stderr.log; exit $x)`,
> ```

Random question but I'm trying to figure out how this whole thing works.. What process is running this command? Looking briefly at the code, it suggests that `roachprod` runs this and actually waits for the output which is not what happens, so I'm missing something. More specifically, where does the output of the final `cat` go?

**Comment by RaduBerinde** [comment]
___
*[pkg/cmd/roachprod/install/cockroach.go, line 360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52035#-MZ0oFMr2AxTCB6A0ude:-MZ0tHcjDJeAWSSPHFQn:bfovreb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdea7a86e54d5340f362aabc3a4f5db30375c7b8/pkg/cmd/roachprod/install/cockroach.go#L360)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Random question but I'm trying to figure out how this whole thing works.. What process is running this command? Looking briefly at the code, it suggests that `roachprod` runs this and actually waits for the output which is not what happens, so I'm missing something. More specifically, where does the output of the final `cat` go?
</blockquote></details>

Ah, never mind, we have `--background` in the `start` command, that makes sense.

**Pull request merged**
