### PR TITLE
opt[wip]: modify DecorrelateScalarGroupBy for null

### PR DESCRIPTION
**Pull request by justinj**
I think this could probably do with a good bit more testing, but I wanted
to finally just get it out in front of people (and take a quick break to work on something else).

This commit modifies DecorrelateScalarGroupBy to support aggregates
which cannot ignore NULL inputs.

The challenge with said aggregates is that in the output of a left join,
they cannot distinguish between a row whose RHS columns are NULL because
there was no matching row, and those where there was a single match
which was all NULL values.

To resolve this, we synthesize a non-nullable "canary" aggregation which
gets threaded up through the left join in order to distinguish between
these cases.

I think the rule as-is is a bit overcomplicated, but I'm not sure how to
simplify it further - advice welcome on how to restructure things. In
particular, I think the translation between the "raw" aggregates and
those which do the appropriate projection (essentially, the work done by
TranslateNonIgnoreAggs) is very implicit and is hurt by the inability to
explicitly pass values from functions in the subtrees around (it depends
on the output of TranslateAggs matching up with its input).

Release note: none.

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
Nice work!

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-:-LJV7YD95fzV17WJBMWf:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/decorrelate.go, line 398 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJUyHvJ7t9udeFc6Pby:-LJUyHvJ7t9udeFc6Pbz:b-bywc17) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L398)):*
> ```Go
> }
> 
> func (c *CustomFuncs) referencedCols(scalarExpr memo.GroupID) opt.ColSet {
> ```

Can't you just use `ScalarProperties.OuterCols` instead of this function?
___
*[pkg/sql/opt/norm/decorrelate.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJUymPTA5FahUZxXLUJ:-LJUymPTA5FahUZxXLUK:btz0oc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L428)):*
> ```Go
> 		agg := c.f.mem.NormExpr(a)
> 		op := agg.Operator()
> 		if op != opt.CountRowsOp && !opt.AggregateIsNullOnEmpty(op) && !opt.AggregateIgnoresNulls(op) {
> ```

[nit] For clarity, I'd make the order of these match the order in the list above
___
*[pkg/sql/opt/norm/decorrelate.go, line 445 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV2Nwi3_GQoiVRh0nS:-LJV2Nwi3_GQoiVRh0nT:b-yst9vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L445)):*
> ```Go
> //   input in order to distinguish whether the aggregate should be considered to
> //   have consumed a single NULL or nothing.
> func (c *CustomFuncs) TranslateAggs(left, in, oldAggs memo.GroupID) memo.GroupID {
> ```

[nit] the name of this function is a bit vague -- is there a more descriptive name?
___
*[pkg/sql/opt/norm/decorrelate.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV-f9135myvrLdt5DI:-LJV-f9135myvrLdt5DJ:bpmwjx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L476)):*
> ```Go
> 			// a new column ID for them. This will later be projected properly by
> 			// TranslateNonIgnoreAggs.
> 			newAggCols[i] = c.f.Metadata().AddColumn("aggregate", c.f.Metadata().ColumnType(aggCols[i]))
> ```

why not use the same name as `aggCols[i]`? I think that would be clearer than "aggregate".
___
*[pkg/sql/opt/norm/decorrelate.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV0HSmA7SE9__3cvfb:-LJV0HSmA7SE9__3cvfc:b-ix3uo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L484)):*
> ```Go
> 	aggCanaryIdx := len(newAggCols) - 1
> 
> 	aggCanaryID := c.f.Metadata().AddColumn("aggregated_canary", types.Bool)
> ```

Is the type always bool? What if there was already a not-null column, so `EnsureNotNullIfNeeded` doesn't create a new column? Also, in that case, can we safely call `ConstructConstNotNullAgg` below?
___
*[pkg/sql/opt/norm/decorrelate.go, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV25C--_lC9wuoqyA_:-LJV25C--_lC9wuoqyAa:bxupzmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L500)):*
> ```Go
> // const_not_null_agg aggregation over a non-nullable column.  If found, it returns
> // the id of the aggregation column and true, otherwise, it returns false.
> // TODO(justin): this seems slightly ad-hoc and sketchy.
> ```

Seems fine to me, but maybe instead of returning a bool you should just panic if you don't find the column. That way, you guarantee that this function is only called if you've already called `TranslateAggs`. I think it's also fine to leave as-is.
___
*[pkg/sql/opt/norm/decorrelate.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV3vn0-zaOuaGD_xji:-LJV3vn0-zaOuaGD_xjj:b7tsb1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L546)):*
> ```Go
> // aggsRequiringTranslation returns the set of columns in aggregations which
> // require a discriminating canary aggregation in TryDecorrelateScalarGroupBy.
> // This is true for aggregations which read from the right input and cannot
> ```

What is the right input? Is this function used for joins? More context needed....

I think an example would help a lot here.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV6E4wA6ySwvi5GIH2:-LJV6E4wA6ySwvi5GIH3:bo99mtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/rules/decorrelate.opt#L331)):*
> ```
> #         input from those that arose from the left join:
> #
> #  CASE
> ```

[nit] I'd move this case statement over a few columns so it's more clear that it corresponds to the last bullet point above

**Review by justinj — COMMENTED** [review]
@andy-kimball helped restructure this - I've merged in his changes and updated various comments, but as a result this code changed around a good bit. I appreciate the review @rytaft! Sorry a bunch of the code you reviewed got removed 😅

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-:-LJ_60ML5h9X-0SqrP1o:b-16x0of)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/decorrelate.go, line 398 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJUyHvJ7t9udeFc6Pby:-LJZy5B-0TamYcJQIcf6:b-oz8tyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L398)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can't you just use `ScalarProperties.OuterCols` instead of this function?
</blockquote></details>

Good call!
___
*[pkg/sql/opt/norm/decorrelate.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJUymPTA5FahUZxXLUJ:-LJZyF-F8MmgMRrVnjGA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L428)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] For clarity, I'd make the order of these match the order in the list above
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/decorrelate.go, line 445 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV2Nwi3_GQoiVRh0nS:-LJZz-Ih5Y1FfKaAzcPJ:b-fh26q2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L445)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] the name of this function is a bit vague -- is there a more descriptive name?
</blockquote></details>

good point, but this ended up going away
___
*[pkg/sql/opt/norm/decorrelate.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV-f9135myvrLdt5DI:-LJZz5Vd1RcBUtn2oxth:b-lhnlgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L476)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why not use the same name as `aggCols[i]`? I think that would be clearer than "aggregate".
</blockquote></details>

this ended up going away
___
*[pkg/sql/opt/norm/decorrelate.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV0HSmA7SE9__3cvfb:-LJ_-Tet4rydqBBaqcXC:bk24pxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L484)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is the type always bool? What if there was already a not-null column, so `EnsureNotNullIfNeeded` doesn't create a new column? Also, in that case, can we safely call `ConstructConstNotNullAgg` below?
</blockquote></details>

you're correct, this was wrong! but it ended up going away
___
*[pkg/sql/opt/norm/decorrelate.go, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV25C--_lC9wuoqyA_:-LJ_5LRy6gP-jhOEz6ji:b-5ak28q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L500)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems fine to me, but maybe instead of returning a bool you should just panic if you don't find the column. That way, you guarantee that this function is only called if you've already called `TranslateAggs`. I think it's also fine to leave as-is.
</blockquote></details>

also went away
___
*[pkg/sql/opt/norm/decorrelate.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV3vn0-zaOuaGD_xji:-LJ_5euX2L6iZv5wQDVY:bdat16b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/decorrelate.go#L546)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What is the right input? Is this function used for joins? More context needed....

I think an example would help a lot here.
</blockquote></details>

agreed, but this also went away
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJV6E4wA6ySwvi5GIH2:-LJ_5moOBlkj9l7GX3tr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b7a26f50c26c19937e55d14503093947e81e1a1/pkg/sql/opt/norm/rules/decorrelate.opt#L331)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I'd move this case statement over a few columns so it's more clear that it corresponds to the last bullet point above
</blockquote></details>

Done.

**Review by rytaft — CHANGES_REQUESTED** [review]
No worries! Still looking at the changes... looks like an improvement!

> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-:-LJf4Jin34FKsIZ8LfhY:bxr0a0j)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/decorrelate.go, line 384 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJf-6JG4QyP9SF5GTL2:-LJf-6JH64HxPzGSKx6r:bz07hir) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/decorrelate.go#L384)):*
> ```Go
> 
> // EnsureCanaryCol searches for a not-null output column in the given group.
> // If such a column does not exist, it checks whether an aggregation which
> ```

The flow of logic has changed a bit - you're checking these in the opposite order now
___
*[pkg/sql/opt/norm/decorrelate.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJf-_G8DdVxfYFhdiHf:-LJf-_G8DdVxfYFhdiHg:b-teq460) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/decorrelate.go#L414)):*
> ```Go
> }
> 
> // EnsureCanary makes sure that if canaryCol is set, it's projected out of the
> ```

[nit] "projected out" makes it sound like the canary column is excluded, rather than included

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/decorrelate.go, line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJkvuG4-Ni4ip3FBW7Y:-LJkvuG4-Ni4ip3FBW7Z:b-c0s9tx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/decorrelate.go#L334)):*
> ```Go
> // MinNotNullCol returns a singleton set containing the non-nullable output
> // column in the given group with the smallest ID.
> func (c *CustomFuncs) MinNotNullCol(group memo.GroupID) opt.ColSet {
> ```

Where are you using this helper? Also, anytime we'd use this, which column we pick would be arbitrary. I'd just call it `AnyNotNullCol`.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 1872 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJkvblpBsfmvYA_O0OK:-LJkvblpBsfmvYA_O0OL:b-t75ah0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/testdata/rules/decorrelate#L1872)):*
> ```
>            └── array_agg = ARRAY[] [type=bool, outer=(5), constraints=(/5: (/NULL - ])]
> 
> build
> ```

Why is this using `build` and not `norm` or `opt`?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJnma-N3eWmQjo4Lk2Y:-LJnma-N3eWmQjo4Lk2Z:b-66fw63) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/rules/decorrelate.opt#L326)):*
> ```
> #         necessary).
> #       - ConstAgg is mapped into the less restrictive ConstNotNullAgg.
> #       - Any other operator which doesn't ignore NULLs can be replaced with a
> ```

This works because in each group we have a single left row, so either the row matches some rows from the right in which case the aggregation is valid, or it didn't match anything and we have to return what the aggregation returns when there are no rows. Is this right? It would help if something along this lines was explained.

Can you put down an example in SQL (after the example below)? Using ARRAY_AGG or maybe a fictional agg function (e.g. `CountNulls`) to show the principle.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 333 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJnoT3B8jLlzZQBva5Y:-LJnoT3B8jLlzZQBva5Z:bn0l087) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/rules/decorrelate.opt#L333)):*
> ```
> #         CASE
> #           WHEN notnull IS NOT NULL THEN aggregated_value
> #           ELSE NULL
> ```

This `NULL` should actually be the value of the aggregation when there are no input rows (e.g. it would be 0 for Count) no?
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 378 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJnq7TDEeNqQQOduOwF:-LJnq7TDEeNqQQOduOwG:b-isajw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/rules/decorrelate.opt#L378)):*
> ```
> )
> =>
> (Select
> ```

Since this is where the logic comes together, I think it would be useful to add some comments below. Maybe if you add an example above, you can add comments with pieces of that example. E.g. `TranslateNonIgnoreAggs` adds the `CASE`. Also should be said somewhere that canaryCol can be 0 when a canary col isn't needed (in which case EnsureCanary does nothing)
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 383 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJoK3Ei6cTNKv7KzjmW:-LJoK3Ei6cTNKv7KzjmX:b-c43q59) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/rules/decorrelate.opt#L383)):*
> ```
>             (LeftJoinApply
>                 $leftWithKey:(EnsureKey $left)
>                 $rightWithCanary:(EnsureCanary
> ```

Is there an optgen feature that wouldn't be complicated which you think can make this rule cleaner?

For example, here, if there was the possibility of returning (and binding to) a second return value, `EnsureCanary` and `EnsureCanaryCol` could be consolidated. I don't quite know how that would look though, maybe something like `(First ($rightWithCanary, $canaryCol)=(EnsureCanary $input $aggregations))`

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 383 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJoK3Ei6cTNKv7KzjmW:-LJoMC8r9cHSk_Ht5vCe:b-795vz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/rules/decorrelate.opt#L383)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is there an optgen feature that wouldn't be complicated which you think can make this rule cleaner?

For example, here, if there was the possibility of returning (and binding to) a second return value, `EnsureCanary` and `EnsureCanaryCol` could be consolidated. I don't quite know how that would look though, maybe something like `(First ($rightWithCanary, $canaryCol)=(EnsureCanary $input $aggregations))`
</blockquote></details>

I've thought about doing something like that, but I'd want to wait until we had multiple use cases to justify the work. Splitting it into two calls is the current way to work around not having multiple return values.

**Review by rytaft — COMMENTED** [review]
:lgtm:, assuming you address the remaining open comments. Nicely done!

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-:-LJokLMR7xfVbEYy-ioI:b-44h2er)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by justinj — COMMENTED** [review]
I forgot to comment about it before - Andy suggested re-introducing `ANY_NOT_NULL` since that's what we really want for the canary aggregation (the value isn't necessarily constant if it's not a canary we synthesized).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-:-LJom-WR8I8zezdWVVXd:b-uw9nic)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJkvuG4-Ni4ip3FBW7Y:-LJoc_5UEwyfpUhoRKII:b-7e7d5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/decorrelate.go#L334)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Where are you using this helper? Also, anytime we'd use this, which column we pick would be arbitrary. I'd just call it `AnyNotNullCol`.
</blockquote></details>

Got rid of it, didn't realize it was unused now.
___
*[pkg/sql/opt/norm/decorrelate.go, line 384 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJf-6JG4QyP9SF5GTL2:-LJockCj7AuLFn3TU9mE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/decorrelate.go#L384)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

The flow of logic has changed a bit - you're checking these in the opposite order now
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/decorrelate.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJf-_G8DdVxfYFhdiHf:-LJockjODY9M0xhosF-Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/decorrelate.go#L414)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] "projected out" makes it sound like the canary column is excluded, rather than included
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJnma-N3eWmQjo4Lk2Y:-LJomph-4ELqSMS6b_wm:b-7qrnxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/rules/decorrelate.opt#L326)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This works because in each group we have a single left row, so either the row matches some rows from the right in which case the aggregation is valid, or it didn't match anything and we have to return what the aggregation returns when there are no rows. Is this right? It would help if something along this lines was explained.

Can you put down an example in SQL (after the example below)? Using ARRAY_AGG or maybe a fictional agg function (e.g. `CountNulls`) to show the principle.


</blockquote></details>

Yeah, that's correct, and the canary is used to distinguish between there being no matches and there being a match of a row of `NULL`s. I added some more exposition and an example, let me know if it helps?
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 333 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJnoT3B8jLlzZQBva5Y:-LJodPqV6JfZMuhmH4dF:b515ekw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/rules/decorrelate.opt#L333)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This `NULL` should actually be the value of the aggregation when there are no input rows (e.g. it would be 0 for Count) no?
</blockquote></details>

Yes, but this transformation doesn't occur for `Count` since it can ignore nulls. I added an assertion that any aggregate we do this for satisfies `AggregateIsNullOnEmpty` to make sure we don't erroneously do this.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 378 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJnq7TDEeNqQQOduOwF:-LJp4Y7D-NIkv2wSgRs1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/rules/decorrelate.opt#L378)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Since this is where the logic comes together, I think it would be useful to add some comments below. Maybe if you add an example above, you can add comments with pieces of that example. E.g. `TranslateNonIgnoreAggs` adds the `CASE`. Also should be said somewhere that canaryCol can be 0 when a canary col isn't needed (in which case EnsureCanary does nothing)
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 383 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJoK3Ei6cTNKv7KzjmW:-LJoqtehD_GZkZLBq41B:b-yja5tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/rules/decorrelate.opt#L383)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I've thought about doing something like that, but I'd want to wait until we had multiple use cases to justify the work. Splitting it into two calls is the current way to work around not having multiple return values.
</blockquote></details>

Yeah, I think something like that would be good, or even a predeclaration phase before the return value, like
```
...
    $on:*
)
=>
$rightWithCanary, $canaryCol = (EnsureCanary $input $aggregations)
(Select

...
```
but then you lose a bit of the structural consistency, so overall I don't know what would be best.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 1872 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJkvblpBsfmvYA_O0OK:-LJosABoCXdlDttLod43:b-fyb4al) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/testdata/rules/decorrelate#L1872)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Why is this using `build` and not `norm` or `opt`?
</blockquote></details>

No reason - I think I was looking at something and forgot to change it back.

**Review by rytaft — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 502 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJp9kRNDuF_uEph04tX:-LJp9kRNDuF_uEph04tY:b-fvlgh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b866ee1241d128c70b89045755f4dca0577ca1/pkg/sql/opt/norm/decorrelate.go#L502)):*
> ```Go
> 			if !opt.AggregateIsNullOnEmpty(expr.Operator()) {
> 				// If this gets triggered we need to modify constructCanaryChecker to
> 				// have a special "on-empty" value.
> ```

Can you expand this comment a bit to explain why you don't expect it to be triggered currently?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:  Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-:-LJsrnA06ijy698KWdzw:bo31fz2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJnma-N3eWmQjo4Lk2Y:-LJsq5pQ4nUJ9vDiFjJq:bs2nnae) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5a4f68a03a219ff1be22ab746d03df29e6e071/pkg/sql/opt/norm/rules/decorrelate.opt#L326)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Yeah, that's correct, and the canary is used to distinguish between there being no matches and there being a match of a row of `NULL`s. I added some more exposition and an example, let me know if it helps?
</blockquote></details>

Yes, this helps a ton, thank you!
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 387 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJsp-xKEBQ26vJGL22T:-LJsp-xKEBQ26vJGL22U:bzesp40) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b866ee1241d128c70b89045755f4dca0577ca1/pkg/sql/opt/norm/rules/decorrelate.opt#L387)):*
> ```
> #
> # In this example, the "notnull" canary is needed to determine if the value of
> # the ARRAY_AGG aggregation should be NULL or {NULL}.
> ```

Add: In other cases, we can use an existing non-null column as a canary; that column would not be constant necessarily, hence the use of ANY_NOT_NULL instead of CONST_AGG.

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 502 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJp9kRNDuF_uEph04tX:-LJsxzt71Yk5F7itcAcW:b5vns00) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b866ee1241d128c70b89045755f4dca0577ca1/pkg/sql/opt/norm/decorrelate.go#L502)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you expand this comment a bit to explain why you don't expect it to be triggered currently?
</blockquote></details>

So it wasn't quite correct, because `AggregateIsNullOnEmpty` and `AggregateIgnoresNulls` needed to be extended to include a few extra aggregates. I extended it and added a test that verifies that every aggregate (except `CountRows`) is accepted by one of those. That test can be deleted if we lift this restriction, though. I extended this comment a bit too.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 387 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28410#-LJsp-xKEBQ26vJGL22T:-LJsyWJRDp6CVY13vG1u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b866ee1241d128c70b89045755f4dca0577ca1/pkg/sql/opt/norm/rules/decorrelate.opt#L387)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Add: In other cases, we can use an existing non-null column as a canary; that column would not be constant necessarily, hence the use of ANY_NOT_NULL instead of CONST_AGG.
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28410)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
