### PR TITLE
cherrypick-2.0: sql: report unimplemented error on ORDER BY in function arguments

### PR DESCRIPTION
**Pull request by knz**
Picks #25146.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

**Comment by knz** [comment]
Actually sequelize requires support for the syntax. #25148

**Comment by knz** [comment]
@benesch @nvanbenschoten is it safe to cherry-pick this for our sequelize support, is it possible that sequelize will not hit this on the common case.

**Pull request merged**
