### PR TITLE
opt: update stats calculation for Select and Join

### PR DESCRIPTION
**Pull request by rytaft**
This PR consists of 7 commits which improve stats calculation:
1. Set the estimated distinct count for boolean columns to 2 when no stats are available
2. Clean up and refactor the Select and Scan stats calculation
3. Make the stats calculation for Select aware of equivalent columns
4. Add stats calculation for Joins using the actual ON conditions
5. Cleanup of statisticsBuilder to remove construction of extra statisticsBuilders for recursion
6. Fix join cardinality calculation and use the cardinality to ensure stats conform to the cardinality
7. Add a function to the FD library to return a representative column for each equivalency group, and use this function in the stats code

See the individual commit messages for details.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Thanks for working on this, very cool! Some random initial comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-:-LJISw82AD89xA8CVopO:bs5jw8m)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 275 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIP8UQ4fhgda-n13hs:-LJIP8UQ4fhgda-n13ht:b-dcsvsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L275)):*
> ```
>     "columns": ["a"],
>     "created_at": "2018-01-01 1:00:00.00000+00:00",
>     "row_count": 1,
> ```

The 1 and 10 values were forced by the old formula. These should be something that makes more sense, like 100 and 10000. If we change them, do we still get lookup joins? (I'm hoping yes, without having to add extra conditions below). Note that this is repeated a bunch of times in this file, and there is a related TODO that we can clean up now (grep for INJECT).
___
*[pkg/sql/opt/memo/statistics_builder.go, line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIKQ7dERcWvhC2RTaR:-LJIKQ7dERcWvhC2RTaS:b-3jypi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b48b4e381211daa70503f8f83c45db0fc19771d/pkg/sql/opt/memo/statistics_builder.go#L327)):*
> ```Go
> 	// Short cut if there is a contradiction.
> 	if def.Constraint != nil && def.Constraint.IsContradiction() {
> 		sb.s.RowCount = 0
> ```

This check and the similar one in select can also be used to set Cardinality to 0. Maybe we should move them to the props builder and just check the Cardinality here?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIMXvB33ESDJAI8WS7:-LJIMXvB33ESDJAI8WS8:b-habgql) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b48b4e381211daa70503f8f83c45db0fc19771d/pkg/sql/opt/memo/statistics_builder.go#L1130)):*
> ```Go
> //
> func (sb *statisticsBuilder) applyFilter(
> 	filter ExprView, getBuilder func(col opt.ColumnID) *statisticsBuilder,
> ```

[nit] I would define a type with this prototype and add comments for that type explaining how it is used.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 659 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJINgpJEtSwmDcINcSr:-LJINgpJEtSwmDcINcSs:b-i4bioz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd2784a5efdbed21a01291b440817b6f0b4129ef/pkg/sql/opt/norm/testdata/rules/decorrelate#L659)):*
> ```
>       │    ├── key: (1)
>       │    └── fd: (1)-->(2)
>       ├── left-join (merge)
> ```

How come this commit changes these plans?
___
*[pkg/sql/opt/xform/testdata/rules/join, line 568 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIRWr0Ao-qslz5b9dJ:-LJIRWr0Ao-qslz5b9dK:b-26rd6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/xform/testdata/rules/join#L568)):*
> ```
> SELECT * FROM stu, abc WHERE (c,b,a) = (s,t,u)
> ----
> inner-join (lookup stu)
> ```

I believe the lookup join is indeed more efficient with these stats, but these are testcases for merge. Maybe we can decrease the row_count above so merge+sort is still chosen.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1257 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIRy7h5x6vSTBxtA5g:-LJIRy7h5x6vSTBxtA5h:b-cau4cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/xform/testdata/rules/join#L1257)):*
> ```
>     "columns": ["a"],
>     "created_at": "2018-05-01 1:00:00.00000+00:00",
>     "row_count": 1,
> ```

Similar to that other file, try 100 and 10000 (or 100 and 100000) instead of adding conditions.

**Review by andy-kimball — COMMENTED** [review]
I've added some initial comments as well; there's a lot to digest. Definitely a big step forward.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-:-LJK-6iS8Lvtkh9tejMZ:b-egwbrr)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIKQ7dERcWvhC2RTaR:-LJJeGuGBvfavcJIVIVB:bghyt4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b48b4e381211daa70503f8f83c45db0fc19771d/pkg/sql/opt/memo/statistics_builder.go#L327)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This check and the similar one in select can also be used to set Cardinality to 0. Maybe we should move them to the props builder and just check the Cardinality here?
</blockquote></details>

:+1: 
I think we want all "hard" cardinality checks to be consolidated with the `Cardinality` code, and then have stats use those indirectly by checking `Cardinality`. In other words, if we know a hard min or max limit, it should always be reflected in `Cardinality`. There are other interesting checks that are part of cardinality that we want reflected in stats. For example, when we compute that a set has max 1 row using FD's, we update cardinality to reflect that, and we want to also reflect that in stats.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJhSDL22R1QlQVVxLC:-LJJhSDL22R1QlQVVxLD:b-q2w8ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b48b4e381211daa70503f8f83c45db0fc19771d/pkg/sql/opt/memo/statistics_builder.go#L435)):*
> ```Go
> 	// Calculate distinct counts for constrained columns
> 	// -------------------------------------------------
> 	getBuilder := func(col opt.ColumnID) *statisticsBuilder {
> ```

Did you make sure that `getBuilder` doesn't escape to the heap?

It's quite abstract to pass around a function for creating `statisticsBuilder`s that behaves differently for different operators. I'd think hard about whether there's a simpler way to do this (might not be, but I'd be searching for one).
___
*[pkg/sql/opt/memo/statistics_builder.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJo0VI0Rj-vpxO07Ox:-LJJo0VI0Rj-vpxO07Oy:b-jyp6bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L422)):*
> ```Go
> 	// Shortcut if the filter is false or there is a contradiction.
> 	// (True filters are removed by normalization).
> 	constraintSet := filter.Logical().Scalar.Constraints
> ```

Similar to above, I think this check should be moved to `logicalPropsBuilder` to update cardinality.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 454 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJo9ky36gFrVdpgLa8:-LJJo9ky36gFrVdpgLa9:bchodnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L454)):*
> ```Go
> 	sb.s.Selectivity *= sb.selectivityFromUnappliedConstraints(numUnappliedConstraints)
> 
> 	// Calculate row count
> ```

I really like the new flow (calc distinct counts, calc selectivity, calc row count). It's much easier to follow the logic now, because i can analyze each phase independently for correctness.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 542 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJxchzEPSDbpQJ5Rww:-LJJxchzEPSDbpQJ5Rwx:b-cmnnv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L542)):*
> ```Go
> 	}
> 
> 	// Shortcut if the ON condition is false or there is a contradiction.
> ```

More stuff that could go into `logicalPropsBuilder` cardinality calculations.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJqFVS-O2WimWJs1Yd:-LJJqFVS-O2WimWJs1Ye:bukv2y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L1296)):*
> ```Go
> 	tight := filter.Logical().Scalar.TightConstraints
> 
> 	sel := func(filter ExprView, constraintSet *constraint.Set, tight bool) {
> ```

How about `applyConjunct` instead of just `sel`?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1301 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJqWNZ9ciGgcMLlbGs:-LJJqWNZ9ciGgcMLlbGt:b-6tdbax) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L1301)):*
> ```Go
> 			return
> 		}
> 		constrainedCols.UnionWith(filter.Logical().Scalar.OuterCols)
> ```

Isn't `constraintedCols` always just `filter.Logical().Scalar.OuterCols`? I don't understand why `sel` needs to re-compute it each time we apply a conjunct (it's constant). For that matter, how come the caller needs `applyFilter` to compute and return it? Can't the caller just trivially call `filter.Logical().Scalar.OuterCols` itself?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1730 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJt0mW2jUMW25IIxPe:-LJJt0mX3oAfHL8DDZ6M:b-ot7kyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L1730)):*
> ```Go
> }
> 
> func (sb *statisticsBuilder) getEquivalencyGroups(fd *props.FuncDepSet) []opt.ColSet {
> ```

It feels like we're working around lack of functionality in `FuncDepSet` at a high cost (N**2 computation, allocation of slice). What if we added these methods to `FuncDepSet`:
```
// EquivReps returns one "representative" column from each equivalency group in
// the FD set. ComputeEquivClosure can be called to obtain the remaining columns
// from each equivalency group.
func (f *FuncDepSet) EquivReps() opt.ColSet {
  ...
}

// Also we'd rename ColSet to be AllCols for symmetry.
```

This way, rather than passing around the entire equivalency groups in a slice, you can pass around the "representative" columns in a colset, and then expand them with calls to `ComputeEquivClosure` when needed. Perhaps there's a need for another `FuncDepSet` helper method to make that easier:
```
func (f *FuncDepSet) ComputeEquivGroup(rep opt.ColumnID) opt.ColSet {
}
```

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28315)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 275 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIP8UQ4fhgda-n13hs:-LJKa2bm46RlovwsP_wb:b-taqnoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L275)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The 1 and 10 values were forced by the old formula. These should be something that makes more sense, like 100 and 10000. If we change them, do we still get lookup joins? (I'm hoping yes, without having to add extra conditions below). Note that this is repeated a bunch of times in this file, and there is a related TODO that we can clean up now (grep for INJECT).
</blockquote></details>

Yep! Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJqFVS-O2WimWJs1Yd:-LJKfF7g86rgGylntgq1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L1296)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How about `applyConjunct` instead of just `sel`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1301 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJqWNZ9ciGgcMLlbGs:-LJKd4AxEkE5uO0LVbKI:bt8wlhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L1301)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Isn't `constraintedCols` always just `filter.Logical().Scalar.OuterCols`? I don't understand why `sel` needs to re-compute it each time we apply a conjunct (it's constant). For that matter, how come the caller needs `applyFilter` to compute and return it? Can't the caller just trivially call `filter.Logical().Scalar.OuterCols` itself?
</blockquote></details>

The problem is that we don't want to include equality columns in constrainedCols -- I added a comment with the details. Also changed the parameter name from filter to conjunct, since I think that may have been part of the confusion...
___
*[pkg/sql/opt/xform/testdata/rules/join, line 568 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIRWr0Ao-qslz5b9dJ:-LJKaQDADrG4Ym2LE-Lz:bpm3xnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/xform/testdata/rules/join#L568)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I believe the lookup join is indeed more efficient with these stats, but these are testcases for merge. Maybe we can decrease the row_count above so merge+sort is still chosen.
</blockquote></details>

Decreasing the row count didn't work, but changing to a left join did the trick.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1257 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIRy7h5x6vSTBxtA5g:-LJKaiWn6DbkNe4cJt6i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/xform/testdata/rules/join#L1257)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Similar to that other file, try 100 and 10000 (or 100 and 100000) instead of adding conditions.
</blockquote></details>

Done.

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 659 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJINgpJEtSwmDcINcSr:-LJLR1CTDkWYQOmAWAfz:b-dhssn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd2784a5efdbed21a01291b440817b6f0b4129ef/pkg/sql/opt/norm/testdata/rules/decorrelate#L659)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How come this commit changes these plans?
</blockquote></details>

This is actually due to a subtle bug fix. Before, the selectivity of the filter `a.i=5` was calculated as `1/700` for the Select operation below. But `a.i` is an outer column for the Select, so the selectivity should actually be `1.0`. Once this was fixed, the number of rows was estimated to be 1000, which was more expensive to sort.

The fix is due to the fact that `getBuilder` returns nil if the given `colID` is not an output column of the input.

**Review by rytaft — COMMENTED** [review]
Based on an offline discussion with @andy-kimball, I made a pretty big change to the model of `statisticsBuilder`. Instead of constructing new `statisticsBuilder` objects for recursive calls, the current `ExprView` is passed around as a parameter. `statisticsBuilder` no longer contains any expression-specific state. See the commit message for more details.

Still working on a few more items, but PTAL at the latest commit. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-:-LJU89482bAsdZcRaWjj:bq14a89)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJhSDL22R1QlQVVxLC:-LJU7M52Db6XvaQq_q2B:b-1qk9d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b48b4e381211daa70503f8f83c45db0fc19771d/pkg/sql/opt/memo/statistics_builder.go#L435)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Did you make sure that `getBuilder` doesn't escape to the heap?

It's quite abstract to pass around a function for creating `statisticsBuilder`s that behaves differently for different operators. I'd think hard about whether there's a simpler way to do this (might not be, but I'd be searching for one).
</blockquote></details>

I've gotten rid of this completely.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIMXvB33ESDJAI8WS7:-LJU7yeu3D8b_kUiHG6l:b6z9o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b48b4e381211daa70503f8f83c45db0fc19771d/pkg/sql/opt/memo/statistics_builder.go#L1130)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would define a type with this prototype and add comments for that type explaining how it is used.
</blockquote></details>

Got rid of this.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 733 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJU7_WA8wa3AFV3aXrj:-LJU7_WA8wa3AFV3aXrk:bg1cww8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L733)):*
> ```Go
> }
> 
> func (sb *statisticsBuilder) colStatIndexJoin(colSet opt.ColSet) *props.ColumnStatistic {
> ```

FYI - got rid of this since this function is never actually called.

**Review by andy-kimball — COMMENTED** [review]
Your updates look very nice to me. Take a look at the several unaddressed comments, and I think this is close to ready.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-:-LJVTd4N8u4fN9VZCoh4:bjtwvo4)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 733 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJU7_WA8wa3AFV3aXrj:-LJVQh5rAd8hOO_CoH5W:b-nsrdyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L733)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

FYI - got rid of this since this function is never actually called.
</blockquote></details>

How come `PushFilterIntoIndexJoin` wouldn't hit this/

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28315)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJIKQ7dERcWvhC2RTaR:-LJVZQHjAm3gN7Dk6d20:b-sdldcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b48b4e381211daa70503f8f83c45db0fc19771d/pkg/sql/opt/memo/statistics_builder.go#L327)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

:+1: 
I think we want all "hard" cardinality checks to be consolidated with the `Cardinality` code, and then have stats use those indirectly by checking `Cardinality`. In other words, if we know a hard min or max limit, it should always be reflected in `Cardinality`. There are other interesting checks that are part of cardinality that we want reflected in stats. For example, when we compute that a set has max 1 row using FD's, we update cardinality to reflect that, and we want to also reflect that in stats.
</blockquote></details>

Added the check for cardinality = 0. I think I might leave other cardinality checks to another PR.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJo0VI0Rj-vpxO07Ox:-LJVZJ9U-Ln3W_D_K4-2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L422)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Similar to above, I think this check should be moved to `logicalPropsBuilder` to update cardinality.
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28315)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 454 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJo9ky36gFrVdpgLa8:-LJX5sMB7oC1Y65-bGc-:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L454)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I really like the new flow (calc distinct counts, calc selectivity, calc row count). It's much easier to follow the logic now, because i can analyze each phase independently for correctness.
</blockquote></details>

Thanks!
___
*[pkg/sql/opt/memo/statistics_builder.go, line 542 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJxchzEPSDbpQJ5Rww:-LJVZeXH1bS3ZpoTc6Xi:br42lel) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L542)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

More stuff that could go into `logicalPropsBuilder` cardinality calculations.
</blockquote></details>

Added a shortcut above, but this block is still needed for everything other than `InnerJoin` (although I left `InnerJoin` here for completeness).
___
*[pkg/sql/opt/memo/statistics_builder.go, line 733 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJU7_WA8wa3AFV3aXrj:-LJX3V4h24d6IYM1egCL:b-1kys8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L733)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come `PushFilterIntoIndexJoin` wouldn't hit this/
</blockquote></details>

`PushFilterIntoIndexJoin` constructs a new `IndexJoin`, which causes `statisticsBuilder.buildIndexJoin` to be called. But the parent `Select` of the `IndexJoin` is not constructed -- it is just added as a new expression to the existing memo group. `colStatIndexJoin` would only be called if the parent of `IndexJoin` was constructed.

**Review by rytaft — COMMENTED** [review]
TFTRs! I think I've addressed all the feedback now. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-:-LJZFXig0cR7s7Ngs6mw:b-bgptx6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1730 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJJt0mW2jUMW25IIxPe:-LJZFPUu2pcT16SkQdK4:b-ydonj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c981e77606f51ecb765a8e40283edf9b091f131/pkg/sql/opt/memo/statistics_builder.go#L1730)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

It feels like we're working around lack of functionality in `FuncDepSet` at a high cost (N**2 computation, allocation of slice). What if we added these methods to `FuncDepSet`:
```
// EquivReps returns one "representative" column from each equivalency group in
// the FD set. ComputeEquivClosure can be called to obtain the remaining columns
// from each equivalency group.
func (f *FuncDepSet) EquivReps() opt.ColSet {
  ...
}

// Also we'd rename ColSet to be AllCols for symmetry.
```

This way, rather than passing around the entire equivalency groups in a slice, you can pass around the "representative" columns in a colset, and then expand them with calls to `ComputeEquivClosure` when needed. Perhaps there's a need for another `FuncDepSet` helper method to make that easier:
```
func (f *FuncDepSet) ComputeEquivGroup(rep opt.ColumnID) opt.ColSet {
}
```
</blockquote></details>

Done. Good idea!

**Review by andy-kimball — APPROVED** [review]
:lgtm:, nice work getting this over the finish line.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-:-LJZfLdR7imfWz5O_2Mx:bhilspf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 354 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJZc75L6aiuiOrE0Z2T:-LJZc75MEvxA4Jfy2oSX:b4bye9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1950e81f3da2f5c23afca15d84c6192b439a93da/pkg/sql/opt/memo/statistics_builder.go#L354)):*
> ```Go
> 
> 	// Short cut if cardinality is 0.
> 	if relProps.Cardinality.IsZero() {
> ```

I think you should have a helper method for this case, since you'll do it multiple times. Maybe `CheckZeroCardinality(relProps *props.Relational) bool`. If the cardinality is zero, it updates the stats on relProps and returns true (in which case you return). Or maybe better would be to pass relProps into `Init`, and do the check there (I could imagine other checks as well). Ultimately, at the end of each `build` method you want to update the calculated row count to be within the hard `Cardinality` bounds.

**Review by rytaft — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-:-LJ_dKqI6kId66ywVTFc:b-voiyyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 354 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/28315#-LJZc75L6aiuiOrE0Z2T:-LJ_dBgl0HTdh7e0g0lk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1950e81f3da2f5c23afca15d84c6192b439a93da/pkg/sql/opt/memo/statistics_builder.go#L354)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think you should have a helper method for this case, since you'll do it multiple times. Maybe `CheckZeroCardinality(relProps *props.Relational) bool`. If the cardinality is zero, it updates the stats on relProps and returns true (in which case you return). Or maybe better would be to pass relProps into `Init`, and do the check there (I could imagine other checks as well). Ultimately, at the end of each `build` method you want to update the calculated row count to be within the hard `Cardinality` bounds.
</blockquote></details>

Done.

**Pull request merged**
