### PR TITLE
opt: make colset check a test-build-only check

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: make colset check a test-build-only check

There isn't a convincing reason to make the `col >= 0` check in
`ColSet.Add` run in non-test builds. It's now a test-only build. Without
the panic, it may be inlined in more cases.

Release note: None

Release justification: This is a very low risk change.

#### opt: add inline assertion for ColSet.setVal and ColSet.retVal

Release note: None

Release justification: This is a lint-only change.

#### testutils/skip: fix broken github links

Release note: None

Release justification: This is a test-only change.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86569)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/opt/colset.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86569#-NA5F5O61PDjeWXaZqRF:-NA5F5O61PDjeWXaZqRG:b-tr9p7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5d409e73eb273c78766884dfddbd5ccf714f86/pkg/sql/opt/colset.go#L52)):*
> ```Go
> 
> // Add adds a column to the set. No-op if the column is already in the set.
> func (s *ColSet) Add(col ColumnID) {
> ```

Should we add `//gcassert:inline` assertion here or are there cases when the function is not inlined? (You'd also need to modify `TestGCAssert` linter to run on this package.)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86569)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/opt/colset.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86569#-NA5F5O61PDjeWXaZqRF:-NA5NdVzANXj7BbQbqp0:bh255nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc5d409e73eb273c78766884dfddbd5ccf714f86/pkg/sql/opt/colset.go#L52)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we add `//gcassert:inline` assertion here or are there cases when the function is not inlined? (You'd also need to modify `TestGCAssert` linter to run on this package.)
</blockquote></details>

Unfortunately there's many places that the function is not inlined. I did add inline assertions for `setVal` and `retVal` though as a stepping stone for inline assertions in the optimizer.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86569#-:-NA5YhG32ahu7fL7xpZq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86569#-NA5YdAv0QNO1_aTW6JG):*
I think all commits need release justifications now.

**Comment by mgartner** [comment]
> I think all commits need release justifications now.

That's new to me. The blathers checker only looks in PR descriptions for release justifications. I added them to the commits anyway for now.

TFTR!

bors r+

**Review by yuzefovich — COMMENTED** [review]
Hm, maybe something changed, but I remember [this](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1631115828090400?thread_ts=1631113979.088300&cid=CJ0H8Q97C) thread from like a year ago.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86569#-:-NA5fSYsC6Vpg-tJglVS:baz40hz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @michae2, and @yuzefovich)

**Pull request merged**
