### PR TITLE
release-21.1: deps: upgrade gogoproto and cockroachdb/errors

### PR DESCRIPTION
**Pull request by knz**
Backports:
- 1/1 commit from #56147
- 1/1 commit from #76498
- 1/1 commit from #77525

Release justification: low risk, high benefit changes to existing functionality

----
See individual PRs for details

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I'm not sure I'm entirely comfortable backporting these. What's the motivation?

**Comment by knz** [comment]
Fixing #76571 as requested by @yuzefovich

**Comment by erikgrinaker** [comment]
I feel like this pulls in too much additional stuff. The diff is 60k lines. Any way to strip this down to the bare minimum?

**Comment by knz** [comment]
> The diff is 60k lines.

Most of this is generated .pb.go, which was checked in in the 21.1 branch.

**Comment by erikgrinaker** [comment]
Sure, but still -- this seems like a lot. Is it really worth it, especially when this will be out of support in a couple of months anyway?

Saw a bunch of conflict markers in here too, btw. E.g.:

```
<<<<<<< HEAD
        sum = "h1:4MY060fB1DLGMB/7MBTLnwQUY6+F09GEiz6SsrNqyzM=",
        version = "v1.23.0",
=======
        sum = "h1:bxAC2xTBsZGibn2RTntX0oH50xLsqy1OxA9tTL3p/lk=",
        version = "v1.26.0",
>>>>>>> bb6ebca751 (*: update to use gogoproto v1.3.)
```

**Review by knz — COMMENTED** [review]
> this seems like a lot. 

Excluding the generated files, we're looking at 13 modified go files. Most of this is test code adjustments; the only non-test code change adds protobuf marshal methods.

> Is it really worth it, especially when this will be out of support in a couple of months anyway?

That's a good question. I'll let @yuzefovich and @jordanlewis chime in on this.

> Saw a bunch of conflict markers in here too

That was just DEPS.bzl. This also auto-generated and I forgot to run the re-gen. Done now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77677#-:-Mxthdv3-5cnppuJgE8V:buwo875)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @erikgrinaker)

**Comment by erikgrinaker** [comment]
> Excluding the generated files, we're looking at 13 modified go files.

Sure, but the dependency bumps here aren't entirely trivial.

It's probably fine though -- we use these in 21.2 after all -- but I'd rather avoid the larger bumps if we can. We can't limit this to the sentry package alone, with some small error tweaks?

**Comment by knz** [comment]
no worries!

**Pull request closed without merging**
