### PR TITLE
kv: add multi-store roachtests

### PR DESCRIPTION
**Pull request by lidorcarmel**
In order to better test multi-store deployment, add multi-store allocator
roachtests and multi-store kv95 performance tests.

Release note: None.

### CODE REVIEW

**Review by aayushshah15 — COMMENTED** [review]
What do our results look like when stressing one of these variants? No failures?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80649#-:-N0gDHNhAD3F2B496YWu:b8dzzem)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @lidorcarmel)

___
*[`pkg/cmd/roachtest/tests/rebalance_load.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80649#-N0gDV_d4zzawAG-rHxU:-N0gDV_d4zzawAG-rHxV:b-oihtud) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c529fee730cc8eb9082e0f9bb25f5d452d6c428/pkg/cmd/roachtest/tests/rebalance_load.go#L276)):*
> ```Go
> 			return false, err
> 		}
> 		leaseCounts[storeID] = leaseCount
> ```

Should this be looking at `NodeID` now? Or do we expect each of the 8 * `numNodes` stores to have a lease at the end here? If so, I suspect we may see some flakes if we don't increase the timeout on this test. Since we're now expecting a lot more splits and rebalances than the single-store variants.

**Review by lidorcarmel — COMMENTED** [review]
with the updates, things are ok but I didn't stress those much because the infra is flaky.. unfortunately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80649#-:-N0grFKc1Vegl7bPMyAJ:bv9jth1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[`pkg/cmd/roachtest/tests/rebalance_load.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80649#-N0gDV_d4zzawAG-rHxU:-N0gjdXjDm-QKVEoEII9:b-d6gcjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c529fee730cc8eb9082e0f9bb25f5d452d6c428/pkg/cmd/roachtest/tests/rebalance_load.go#L276)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Should this be looking at `NodeID` now? Or do we expect each of the 8 * `numNodes` stores to have a lease at the end here? If so, I suspect we may see some flakes if we don't increase the timeout on this test. Since we're now expecting a lot more splits and rebalances than the single-store variants.
</blockquote></details>

yes, thanks! PTAL.
the leases test is flaky so I removed it for now, I'll chat with you about it and see how it should be done.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80649)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @lidorcarmel)

___
*[`pkg/cmd/roachtest/tests/rebalance_load.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80649#-N0gDV_d4zzawAG-rHxU:-N1ARI2q5PIB8zFmcEy4:b-bemwyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c529fee730cc8eb9082e0f9bb25f5d452d6c428/pkg/cmd/roachtest/tests/rebalance_load.go#L276)):*
> the leases test is flaky so I removed it for now

Do we know why? It's not flaky in the single-store variant afaict. We can discuss in our 1:1 this week too if you'd like.

**Review by aayushshah15 — APPROVED** [review]
Lgtm. We discussed offline that we'll add the other version of the roachtest separately once we dig into the flakiness.

**Comment by lidorcarmel** [comment]
Thank Aayush!

bors r+

**Pull request merged**
