### PR TITLE
ui: add empty graph state when no metrics for tenants 

### LINKED ISSUE #103519: ui: add graph state for when there is no data.
**Is your feature request related to a problem? Please describe.**
When switching to a secondary tenant, it is possible the tenant would not have any results to report on certain metrics. Thus, there should be a state for the graphs that indicates there is no data.

Jira issue: CRDB-28054

Epic CRDB-26090

### PR DESCRIPTION
**Pull request by Santamaura**
This change adds an empty graph state when switching to a secondary
tenant that has no data.

Fixes: https://github.com/cockroachdb/cockroach/issues/103519

Release note (ui change): add no data empty graph state when
switching to a secondary tenant with no data.

Screenshot 2023-06-06 at 11 16 18 AM

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103971)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103971#-NXVj_JSEW4gX-4xkbXB:-NXVj_JT5CnyLoFv5rgc:b-130si2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b522f95929074704977fe3678c631c22abbfc0fc/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx#L357)):*
> ```XML
>       tenantSource: isSecondaryTenant(currentTenant)
>         ? currentTenant
>         : selectedTenant,
> ```

this reads oddly to me. what's happening here? why wouldn't the dash always use the selected tenant?

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103971)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @Santamaura)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx` line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103971#-NXVjn2FEkgdfMYPY8R_:-NXVjn2FEkgdfMYPY8Ra:bw2g104) ([raw file](https://github.com/cockroachdb/cockroach/blob/b522f95929074704977fe3678c631c22abbfc0fc/pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx#L387)):*
> ```XML
>             <MonitoringIcon />
>             <span className="body-text-empty">
>               {"Metric is not being collected for this tenant."}
> ```

nit: How would you feel about something like "Metric is not currently available for this tenant" instead? Just because I think in the cases like when the tenant doesn't have the `can_view_node_info` capability, it's not that the metric isn't being collected, it's just that the tenant doesn't have sufficient permissions to *view* the metric.

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103971)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx` line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103971#-NXVjn2FEkgdfMYPY8R_:-NXjvnuwAF4fTA3xP719:bohqzsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b522f95929074704977fe3678c631c22abbfc0fc/pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx#L387)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: How would you feel about something like "Metric is not currently available for this tenant" instead? Just because I think in the cases like when the tenant doesn't have the `can_view_node_info` capability, it's not that the metric isn't being collected, it's just that the tenant doesn't have sufficient permissions to *view* the metric.
</blockquote></details>

Agreed, done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103971#-NXVj_JSEW4gX-4xkbXB:-NXjvq_DDA9aQButHh2k:b665qe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b522f95929074704977fe3678c631c22abbfc0fc/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx#L357)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

this reads oddly to me. what's happening here? why wouldn't the dash always use the selected tenant?
</blockquote></details>

If we are viewing the secondary tenant we don't want to use the selected tenant since that will be an empty string (we don't provide the metrics page dropdown option if on secondary tenant for now) and we are using this prop to determine whether we want to show the empty graph state. Therefore we should pass the current tenant we are viewing.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103971)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @Santamaura)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103971#-NXVj_JSEW4gX-4xkbXB:-NXkUrAB6sSJceiBI0Gy:b-tws4lr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b522f95929074704977fe3678c631c22abbfc0fc/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx#L357)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

If we are viewing the secondary tenant we don't want to use the selected tenant since that will be an empty string (we don't provide the metrics page dropdown option if on secondary tenant for now) and we are using this prop to determine whether we want to show the empty graph state. Therefore we should pass the current tenant we are viewing.
</blockquote></details>

gotcha. is there any way to avoid an empty string for `selectedTenant`? why not set `selectedTenant` to `currentTenant` in that case up above when it's defined?

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103971)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103971#-NXVj_JSEW4gX-4xkbXB:-NXkgM5HB2USbhcwZT7a:bu59rct) ([raw file](https://github.com/cockroachdb/cockroach/blob/b522f95929074704977fe3678c631c22abbfc0fc/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx#L357)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

gotcha. is there any way to avoid an empty string for `selectedTenant`? why not set `selectedTenant` to `currentTenant` in that case up above when it's defined?
</blockquote></details>

Yes this will work, done.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103971#-:-NXpxspt3WNcvPyzGUQ0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Comment by Santamaura** [comment]
TFTR!
bors r+

**Comment by Santamaura** [comment]
bors cancel

**Pull request merged**
