### PR TITLE
multitenant: add multitenant/shared-process/basic roachtest

### LINKED ISSUE #95990: multitenant: create roachtest that uses in-process tenants
There does not currently exist a roachtest that runs with in-process tenants, aside from the C2C replication roachtests. We ought to build a simple, in process tenant specific, roachtest to increase test coverage and to better triage in-process tenant specific bugs from C2C specific bugs caught by the C2C roachtests.

Jira issue: CRDB-23883

### PR DESCRIPTION
**Pull request by msbutler**
This patch introduces a simple roachtest that runs in a shared-process tenant.
This test imports a 500 tpcc workload (about 30 GB of replicated data), and
runs the workload for 10 minutes. The test is run on a 4 node, 4vcpu cluster
with local ssds.

A future patch could complicate the test by running schema changes or other
bulk operations.

Fixes https://github.com/cockroachdb/cockroach/issues/95990

Release note: None

### CODE REVIEW

**Comment by msbutler** [comment]
Test seems to run just fine!

**Comment by msbutler** [comment]
(unrelated flake in CI. opened seperate PR to skip that test)

**Review by knz — COMMENTED** [review]
(Don't forget to update the PR title and description from the new commit message/title.)

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-:-NMsITUT2yFxvE0s-Dua:bb4i1lh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @msbutler, @smg260, and @stevendanna)

___
*[`pkg/cmd/roachtest/tests/multitenant_shared_process.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NMsI6m1EzmLKHnja1eO:-NMsI6m1EzmLKHnja1eP:b-3xp2ny) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d1512db689f975f906b3776a0aca0b9bbb8ea01/pkg/cmd/roachtest/tests/multitenant_shared_process.go#L36)):*
> ```Go
> 		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
> 			var (
> 				appTenantID    = 2
> ```

`CREATE TENANT` will not guarantee you a fixed appTenantID. If you need the tenant ID, you need to look it up after CREATE TENANT.

(IMHO we should extend `update_tenant_resource_limits` to accept a tenant name as first argument instead. Feel free to do so; or file an issue to do so and add a TODO around here.)
___
*[`pkg/cmd/roachtest/tests/multitenant_shared_process.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NMsHnBa1ZSjJwKVSJRz:-NMsHnBc3loMY5ckSKCz:bqy2nbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d1512db689f975f906b3776a0aca0b9bbb8ea01/pkg/cmd/roachtest/tests/multitenant_shared_process.go#L50)):*
> ```Go
> 			sysSQL := sqlutils.MakeSQLRunner(sysConn)
> 
> 			sysSQL.Exec(t, fmt.Sprintf(`CREATE TENANT %s`, appTenantName))
> ```

After #95658 merges, you will want to do `ALTER TENANT %1 START SERVICE SHARED` here.
And after that you will need something like "SucceedsSoon" to wait until the service has started. Otherwise, the workload init below has a small chance to fail if it tries to connect before the tenant service is ready.
___
*[`pkg/cmd/roachtest/tests/multitenant_shared_process.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NMsHpmq3PSBBXZJ8xkg:-NMsHpmq3PSBBXZJ8xkh:b-8l4t34) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d1512db689f975f906b3776a0aca0b9bbb8ea01/pkg/cmd/roachtest/tests/multitenant_shared_process.go#L50)):*
> ```Go
> 			sysSQL := sqlutils.MakeSQLRunner(sysConn)
> 
> 			sysSQL.Exec(t, fmt.Sprintf(`CREATE TENANT %s`, appTenantName))
> ```

also,
`sysSQL.Exec(t, `CREATE TENANT $1`, appTenantName)`. No  need for Sprintf.

**Review by msbutler — COMMENTED** [review]
@knz I've added an additional commit that I believe addresses all your feedback. I'll plan to squash it with the second commit in this PR, if you approve. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-:-NN7QIvKBCLo15lwFjeV:b2sbs8v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, @smg260, and @stevendanna)

___
*[`pkg/cmd/roachtest/tests/multitenant_shared_process.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NMsI6m1EzmLKHnja1eO:-NN7QAFo-RRmIs41r2nF:byx7z41) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d1512db689f975f906b3776a0aca0b9bbb8ea01/pkg/cmd/roachtest/tests/multitenant_shared_process.go#L36)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

`CREATE TENANT` will not guarantee you a fixed appTenantID. If you need the tenant ID, you need to look it up after CREATE TENANT.

(IMHO we should extend `update_tenant_resource_limits` to accept a tenant name as first argument instead. Feel free to do so; or file an issue to do so and add a TODO around here.)
</blockquote></details>

added a todo and opened the following issue https://github.com/cockroachdb/cockroach/issues/96176
___
*[`pkg/cmd/roachtest/tests/multitenant_shared_process.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NMsHnBa1ZSjJwKVSJRz:-NN7Q6HxECYd4ortzPeJ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d1512db689f975f906b3776a0aca0b9bbb8ea01/pkg/cmd/roachtest/tests/multitenant_shared_process.go#L50)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

After #95658 merges, you will want to do `ALTER TENANT %1 START SERVICE SHARED` here.
And after that you will need something like "SucceedsSoon" to wait until the service has started. Otherwise, the workload init below has a small chance to fail if it tries to connect before the tenant service is ready.
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/multitenant_shared_process.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NMsHpmq3PSBBXZJ8xkg:-NN7Q7p98AjtnHz9plZP:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d1512db689f975f906b3776a0aca0b9bbb8ea01/pkg/cmd/roachtest/tests/multitenant_shared_process.go#L50)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

also,
`sysSQL.Exec(t, `CREATE TENANT $1`, appTenantName)`. No  need for Sprintf.
</blockquote></details>

done

**Review by knz — COMMENTED** [review]
LGTM modulo a few nits and checking the retry behavior.

> Reviewed 1 of 5 files at r3, 1 of 4 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-:-NN7U1Fl7LSeVf45T-rS:bitrs9g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @msbutler, @smg260, and @stevendanna)

___
*[`-- commits` line 17 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7T-0c-ynaWcYglzKH):*
commit title: funciton -> function
___
*[`pkg/cmd/roachtest/tests/multitenant_shared_process.go` line 46 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7T9YNCm6puqyGEHhH:-NN7T9YNCm6puqyGEHhI:bjxlzyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/cmd/roachtest/tests/multitenant_shared_process.go#L46)):*
> ```Go
> 
> 			// In order to observe the app tenant's db console,
> 			//create a secure cluster and add Admin roles to the system and app tenant.
> ```

nit: space after `//`
___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 350 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7THpr5TGhcPoaagrr:-NN7THpr5TGhcPoaagrs:bucewf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/cmd/roachtest/tests/multitenant_utils.go#L350)):*
> ```Go
> 	sysSQL.Exec(t, "ALTER TENANT $1 START SERVICE SHARED", tenantName)
> 
> 	// Ensure the tenant server is ready to accept queires
> ```

nit: `queries` and period after the end.
___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 353 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7TKEh4gYsIwgO-cwk:-NN7TKEh4gYsIwgO-cwl:b-i9h2kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/cmd/roachtest/tests/multitenant_utils.go#L353)):*
> ```Go
> 	tenantConn := c.Conn(ctx, t.L(), nodes.RandNode()[0], option.TenantName(tenantName))
> 	tenantSQL := sqlutils.MakeSQLRunner(tenantConn)
> 	tenantSQL.ExecSucceedsSoon(t, `SELECT 1`)
> ```

Could you stress this? I'm surprised this works -- I'd have expected that the call to `.Conn` would be the one to fail.
Maybe you need to use `.ConnE` instead and retry based on that error.
___
*[`pkg/sql/sem/builtins/builtins.go` line 6433 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7Tl0nECB_cUjD45Lj:-NN7Tl0nECB_cUjD45Lk:b-kh1k02) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/sql/sem/builtins/builtins.go#L6433)):*
> ```Go
> 	// Used to configure the tenant token bucket. See UpdateTenantResourceLimits.
> 	//
> 	// TODO(multitenantTeam): use tenantName instead of tenantID
> ```

nit: period at end of sentence.
Also you can include a link to the new issue in the comment.

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @stevendanna)

___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 353 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7TKEh4gYsIwgO-cwk:-NN8BWNfAWfKoVWSQXoA:b-eh7wnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/cmd/roachtest/tests/multitenant_utils.go#L353)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Could you stress this? I'm surprised this works -- I'd have expected that the call to `.Conn` would be the one to fail.
Maybe you need to use `.ConnE` instead and retry based on that error.
</blockquote></details>

huh, I chose to retry the SELECT query instead of `.Conn` cmd bc I was under the impression that the connection to the in-process tenant is lazily created during the first query, but maybe I misinterpreted @stevendanna? FWIW the c`.Conn` call will panic if `.ConnE` throws an error, and I don't think we've seen `c.Conn` fail in the c2c roachtests that use in-process tenants.

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @stevendanna)

___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 353 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7TKEh4gYsIwgO-cwk:-NN8DOW59Z2ChGbYel-b:b-1xaxwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/cmd/roachtest/tests/multitenant_utils.go#L353)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

huh, I chose to retry the SELECT query instead of `.Conn` cmd bc I was under the impression that the connection to the in-process tenant is lazily created during the first query, but maybe I misinterpreted @stevendanna? FWIW the c`.Conn` call will panic if `.ConnE` throws an error, and I don't think we've seen `c.Conn` fail in the c2c roachtests that use in-process tenants. 
</blockquote></details>

could you explain why you're surprised?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @msbutler, @smg260, and @stevendanna)

___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 353 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7TKEh4gYsIwgO-cwk:-NN8rPk-5mlXyPX0bC0X:brtthai) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/cmd/roachtest/tests/multitenant_utils.go#L353)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

could you explain why you're surprised?
</blockquote></details>

1. Under the hood `.Conn` / `.ConnE` call `gosql.Open`. It is driver-specific whether `gosql.Open` directly opens the SQL session, or whether the SQL session will only be opened on first use. The API doesn't specify either way. So you're just being lucky here.

2. You're then passing that conn object through `MakeSQLRunner`. There's no API guarantee in `MakeSQLRunner` either that it doesn't "do" something with the connection before handing you a `*SQLRunner` object back.

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, @smg260, and @stevendanna)

___
*[`-- commits` line 17 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7T-0c-ynaWcYglzKH):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

commit title: funciton -> function
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/multitenant_shared_process.go` line 46 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7T9YNCm6puqyGEHhH:-NN94faz6cFyDFzxC8IF:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/cmd/roachtest/tests/multitenant_shared_process.go#L46)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: space after `//`
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 350 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7THpr5TGhcPoaagrr:-NN94glf4-xDImAiP2vI:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/cmd/roachtest/tests/multitenant_utils.go#L350)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `queries` and period after the end.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 353 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7TKEh4gYsIwgO-cwk:-NN94VkE9srnFztEKJ7r:bhzrh3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/cmd/roachtest/tests/multitenant_utils.go#L353)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

1. Under the hood `.Conn` / `.ConnE` call `gosql.Open`. It is driver-specific whether `gosql.Open` directly opens the SQL session, or whether the SQL session will only be opened on first use. The API doesn't specify either way. So you're just being lucky here.

2. You're then passing that conn object through `MakeSQLRunner`. There's no API guarantee in `MakeSQLRunner` either that it doesn't "do" something with the connection before handing you a `*SQLRunner` object back.

</blockquote></details>

I see. I've modified my PR in the last commit to hedge against the vague API. Let me know if this strategy makes sense!
___
*[`pkg/sql/sem/builtins/builtins.go` line 6433 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN7Tl0nECB_cUjD45Lj:-NN94jMBBWmlv8H52rPR:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c8770482ba8eff600972d2224120a80967ab0f1/pkg/sql/sem/builtins/builtins.go#L6433)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: period at end of sentence.
Also you can include a link to the new issue in the comment.
</blockquote></details>

Done

**Review by knz — APPROVED** [review]
> Reviewed 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @msbutler, @smg260, and @stevendanna)

___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 351 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN99eE41s99VbFraG3k:-NN99eE41s99VbFraG3l:b-zhfk4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/9270e659358563ca93239a85a778a1f8f97a9db3/pkg/cmd/roachtest/tests/multitenant_utils.go#L351)):*
> ```Go
> 
> 	// Opening a SQL session to a newly created in-process tenant may require a
> 	// few retires. Unfortunately, the c.ConnE and MakeSQLRunner APIs do not make
> ```

nit: few retries
___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 364 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN99kW7EtiYNaEdXtPQ:-NN99kW7EtiYNaEdXtPR:b-msxvx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9270e659358563ca93239a85a778a1f8f97a9db3/pkg/cmd/roachtest/tests/multitenant_utils.go#L364)):*
> ```Go
> 		return nil
> 	})
> 	tenantSQL.ExecSucceedsSoon(t, `SELECT 1`)
> ```

You can remove this ExecSucceedsSoon and add a call to `tenantConn.Ping()` inside the SucceedsSoon above instead.

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, @smg260, and @stevendanna)

___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 351 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN99eE41s99VbFraG3k:-NNC4NrT6BAzsKMQir8J:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9270e659358563ca93239a85a778a1f8f97a9db3/pkg/cmd/roachtest/tests/multitenant_utils.go#L351)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: few retries
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/multitenant_utils.go` line 364 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/95999#-NN99kW7EtiYNaEdXtPQ:-NNC4Kv_7vBQzp4HpdEp:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9270e659358563ca93239a85a778a1f8f97a9db3/pkg/cmd/roachtest/tests/multitenant_utils.go#L364)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

You can remove this ExecSucceedsSoon and add a call to `tenantConn.Ping()` inside the SucceedsSoon above instead.
</blockquote></details>

Done

**Comment by msbutler** [comment]
TFTR!!

bors r=stevendanna

**Pull request merged**
