### PR TITLE
roachtest: update hibernate blacklist v19.2

### LINKED ISSUE #36971: roachtest: hibernate failed
SHA: https://github.com/cockroachdb/cockroach/commits/4b3a1216e3a387aad900e70fde65b97b0fa17a8c

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=hibernate PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1251417&tab=buildLog

```
The test failed on master:
	hibernate.go:314,hibernate.go:325,test.go:1237: 
		Tests run on Cockroach v19.1.0-beta.20190318-997-g4b3a121
		Tests run against Hibernate 5.4.2
		8587 Total Tests Run
		8273 tests passed
		314 tests failed
		9 tests passed unexpectedly
		0 tests failed unexpectedly
		0 tests expected failed, but not run
		For a full summary look at the hibernate artifacts 
		
		An updated blacklist (hibernateBlackList19_1) is available in the artifacts' hibernate log

```

### PR DESCRIPTION
**Pull request by BramGruneir**
With the updated unified types from #36598, a number of tests are now passing.
Each test has already been vetted.

Fixes #36971

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37002#-:-Ld5l7Wx5MQrDmHuaU3T:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by BramGruneir** [comment]
TFTR!

bors r+

**Pull request merged**
