### PR TITLE
roachtest: fix bank/cluster-recovery

### PR DESCRIPTION
**Pull request by irfansharif**
Informs #38785.

The "stalls" detected boil down to the time between chaos monkey
iterations. Within each chaos monkey iteration we do the following:

  - Lock all clients, in sequence
  - Restart each node
  - Unlock all clients
  - Sleep until at least one client has made progress

Given our stall timeout is only 30s, we have just that long to go through all
of the above. In each client we lock around the UPDATE query so as to not be
interrupted. The problem is that every now and then these UPDATE queries take a
lot longer than a few milliseconds. This is expected behaviour: this is
primarily due to txnwait procedures and having to wait for the expiration of
an extant contending txn. More importantly, it's not what we're testing here as
the clients are still making progress. Given the chaos monkey first locks each
client, it has to drain out these requests, which eats out of the 30s or so we
have for each chaos monkey iteration. This is made worse by the fact that we do
this in sequence for each client. When we're unlucky, we run into this
particular convoy situation and we're unable to finish the round in time, and a
"stall" is detected.

We should really only be interested in how long it takes for the chaos monkey
to restart a set of nodes, and ensuring that after it does, that clients are
still making progress. We already have statement timeouts for the UPDATE
queries that fail if we take "too long". Removing the stopClients apparatus
gives us what we need.

Release justification: Category 1: Non-production code changes

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: nice debugging!

We don't expect to ever need to "wait for the expiration of an extant contending txn" unless nodes are crashing though. This is what the `kv/contention/nodes=4` test is intending to verify. Did you get to a point where you understand why we are seeing these abandoned transaction records? You can play with the `COCKROACH_TXN_LIVENESS_HEARTBEAT_MULTIPLIER` env var to make these stalls more dramatic.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40976#-:-LpU6toK6kvLj4ABotiN:b6t58um)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/gossip/gossip.go, line 1359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40976#-LpU6PZT2woiCXh9ebNk:-LpU6PZT2woiCXh9ebNl:b-yis70h) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffadfe577d41a5b7c800b64f2895d738c9d1d45/pkg/gossip/gossip.go#L1359)):*
> ```Go
> 			case <-bootstrapTimer.C:
> 				bootstrapTimer.Read = true
> 				// break
> ```

Not your change, but is this correct?

**Review by irfansharif — COMMENTED** [review]
tftr! yep, I did end up (co-incidentally) understanding it in the course of trying to figure this out. Good stuff, I think there's probably work in there to rope in our p99s but I also didn't know we only run into that when nodes are crashing. I haven't yet had a chance to checkout #40786 but this foray should carry over nicely.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40976#-:-LpUGV0DBQO3_3OTrhTQ:b-j9ewi6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
>> Did you get to a point where you understand why we are seeing these abandoned transaction records?

> yep, I did end up (co-incidentally) understanding it in the course of trying to figure this out

So you did find the cause of the transaction record leak? What was it?

**Comment by irfansharif** [comment]
Oh, no, misread, not that. Just understood how things are supposed to work around that area.

**Pull request merged**
