### PR TITLE
kvserver: add a concept of suspect nodes to the allocator

### PR DESCRIPTION
**Pull request by lunevalex**
Touches #57093

A flaky node that goes in and out of liveness can cause
lease thrashing, as live nodes steal leases from the
failing node and then when it heartbeats the allocator
puts them back to maintain mean counts. This could be very
disruptive to the cluster as the leases ping-pong back and
forth. To prevent this problem we introduce a new concept
of a suspect node to the allocator. When a node fails to
hearbeat liveness it's considered suspect until it can reliably
heartbeat liveness for an extended period of time (60s by default).

Release note: None

### CODE REVIEW

**Comment by lunevalex** [comment]
@aayushshah15 @nvanbenschoten @tbg I put together a quick prototype of the idea we described last week to enhance the allocator to have a concept of suspected nodes. This will need some polish and a lot more testing, but I would like some comments and thoughts on it before I spend more time on this. The TestCluster test works for this, but is still a bit flaky I am going to try and clean it up a bit later.

**Review by tbg — COMMENTED** [review]
This looks good, the only question is whether this unavailability detection is good enough. We seem to only "notice" that a store is going in and out of liveness when we check the store status at the right time. One would assume that in practice this would work well enough. On the other hand, this also makes the "suspect" signal only available to the allocator and not anywhere else (for example, it will be hard to plumb it to the UI the way it's defined here now).
I wonder if it's worth pursuing the alternative of adding some information to the liveness record itself, i.e. we'd add a `suspect` bool around here:

https://github.com/cockroachdb/cockroach/blob/ffa0ce3cae9b8de5af1f48fdeb286833869038e3/pkg/kv/kvserver/liveness/livenesspb/liveness.proto#L23-L48

where the contract is that the `suspect` bool is set to true a) by `IncrementEpoch` and b) by the liveness record owner's heartbeat loop following a failed heartbeat (if it isn't already true then), and cleared only in the heartbeat occuring N seconds after detection of the suspect status.

We could then go through the code and look for uses of the `Draining` field, and see if some of them may want to be sensitive to `Suspect` as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-:-MZC075K7n_tMiebAjVv:b-ye6ds5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @lunevalex, and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_lease_test.go, line 583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZC-0aO5jf_62GSjir7:-MZC-0aO5jf_62GSjir8:bocz4nl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/client_lease_test.go#L583)):*
> ```Go
> 	// We are not going to have stats, so disable this so we just rely on
> 	// the store means.
> 	kvserver.EnableLoadBasedLeaseRebalancing.Override(sv, false)
> ```

btw you don't need to export this var to set it, you can just go through `SET CLUSTER SETTING`.
___
*[pkg/kv/kvserver/store_pool.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZC-RO68Nwzn-1x_2UT:-MZC-RO68Nwzn-1x_2UU:brg5pa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/store_pool.go#L190)):*
> ```Go
> 	lastUnavailable time.Time
> 	// lastAvailable is set when it's detected that a store was available,
> 	// i.e. we got a liveliness heartbeat.
> ```

s/liveliness/liveness/ here and in other places
___
*[pkg/kv/kvserver/store_pool.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZC-X7-Csl5mpRhHENh:-MZC-X7-Csl5mpRhHENi:b-shchbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/store_pool.go#L201)):*
> ```Go
> // isSuspect returns whether the store is currently suspect. We measure that by
> // looking at the time it was last unavailable making sure we have not seen any
> //failures for a period of time defined by StoreSuspectDuration.
> ```

// failures
___
*[pkg/kv/kvserver/store_pool.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZC-_1F4y40J14auBTt:-MZC-_1F4y40J14auBTu:b-d1afhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/store_pool.go#L226)):*
> its liveness heartbeat recently

**Review by lunevalex — COMMENTED** [review]
In practice we will notice a store goes suspect very quickly in the allocator, because we will detect it every time something goes through the replica queue. The allocator always builds a StoreList from the StorePool for all the stores it knows about, not just the stores that relate to the range that is going through the queue. 

DBConsole already uses liveness to figure out if a node is suspect, based on the same logic https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/redux/nodes.ts#L39. The only differences is that it will unsuspect a node as soon as it stops failing liveness. 

We may want to consider doing this in phases, first do a limited change in the allocator to support backportability and then change the detection mechanism to use the liveness record itself on master. We will still need most of the changes in the allocator/store_pool to propagate the storeSuspectStatus. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-:-MZDLFK993iR4u89OaIZ:bhpkn6a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @lunevalex, and @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
This all seems reasonable to me.

Once we settle on a mechanism to use for this (i.e. volatile state in the StorePool vs. durable state in NodeLiveness) we'll want to do some experimentation with and without the change in a real cluster under a situation where we expect it to help. That will serve both as validation of the change and harden the motivation for it. Have you given thought to how we could test this new mechanism in action? The unit test you have here is nice in that it asserts that leases aren't moved to suspect nodes, but what about one step above this? How do we show that this heuristic plays well with every other heuristic and load-balancing mechanism in the system to improve system-wide stability in the presence of a problem node? One idea would be to run `kv` against a 5 node cluster and pick a node to periodically inject 5s disk stalls into. With this change, we'd expect the system to adapt and slowly shift leases off of the bad node by virtue of leases being lost during liveness blips and then never transferred back, right?

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-:-MZLakhD9WdFoQ_Ju0UD:b-meqihi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @lunevalex)

___
*[pkg/kv/kvserver/client_lease_test.go, line 570 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZL_f1k5E2uobu2DIIo:-MZL_f1l3eZ7JLcq8kyj:b1g06l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/client_lease_test.go#L570)):*
> ```Go
> }
> 
> func TestLeasesDontThrashWhenNodeBecomesSuspect(t *testing.T) {
> ```

Could you add an explanation to this test, describing the mechanisms that it's exercising and the steps it takes to do so.
___
*[pkg/kv/kvserver/client_lease_test.go, line 629 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZLaH130AMAYOHUxNDt:-MZLaH130AMAYOHUxNDu:bu4ql5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/client_lease_test.go#L629)):*
> ```Go
> 	}
> 
> 	checkLeases := func() error {
> ```

`s/checkLeases/allStoresHaveSomeLeases/`
___
*[pkg/kv/kvserver/client_lease_test.go, line 639 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZLaXtA8ilsI8Bwuv6g:-MZLaXtA8ilsI8Bwuv6h:bknvjdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/client_lease_test.go#L639)):*
> ```Go
> 	}
> 
> 	allReplicasHaveLeases := func() error {
> ```

`s/allReplicasHaveLeases/allRangesHaveValidLeases/`
___
*[pkg/kv/kvserver/store_pool.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZLXwC6DIVNPalYwKzF:-MZLXwC6DIVNPalYwKzG:b-unux3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/store_pool.go#L69)):*
> ```Go
> var SuspectStoreDuration = settings.RegisterDurationSetting(
> 	"server.suspect_store_duration",
> 	"the amount of time we consider a store suspect after it failed it's for the last time liveliness",
> ```

"the amount of time we consider a store suspect for after it fails a node liveness heartbeat"

Also, could you add a sentence about what the effects are of considering a node "suspect"?
___
*[pkg/kv/kvserver/store_pool.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZLYxPi4sIiytiMstCY:-MZLYxPi4sIiytiMstCZ:bpt7fj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/store_pool.go#L255)):*
> ```Go
> 		return storeStatusDecommissioning
> 	case livenesspb.NodeLivenessStatus_UNAVAILABLE:
> 		// We don't suspect the store until it's been considered available.
> ```

Could you explain this a little further? If a node is not considered live in node liveness, we stick with `storeStatusUnknown`? And then we shift to `storeStatusSuspect` once it's back? Could you explain why this distinction is important here?

What if `lastAvailable` was set to a value before the node began failing liveness updates?
___
*[pkg/kv/kvserver/store_pool.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZLYieS0RUfuVTTRtC_:-MZLYieT-WWDKkx3PKBt:b-nvhqon) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/store_pool.go#L256)):*
> ```Go
> 	case livenesspb.NodeLivenessStatus_UNAVAILABLE:
> 		// We don't suspect the store until it's been considered available.
> 		if sd.lastAvailable.UnixNano() > 0 {
> ```

`.IsZero()` here?

**Comment by aayushshah15** [comment]
I took this change out for a quick test drive today, going to dump my observations: 

Note that I ran with a 20% probability of a 5 second sleep [right before we perform a noop fsync before heartbeating liveness](https://github.com/cockroachdb/cockroach/blob/dd325f0cadb0d2c8059209ff13c9ea2043451740/pkg/kv/kvserver/liveness/liveness.go#L1220) on `node 1`. This made `node 1` flip-flop on its node liveness heartbeats. I ran `kv` with the following config:
```
rp run $CLUSTER:10 -- ./workload run kv --init --histograms=perf/stats.json --concurrency=192 --splits=1000 --duration=10m0s --read-percent=5 --batch=32 {pgurl:2-9};

```

<details>
<summary>With Alex's change:</summary>
<br>

with_suspect
```

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0          34652           57.8    111.4     26.2     79.7    142.6 103079.2  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0         655526         1092.5    158.8     67.1    104.9    159.4 103079.2  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0         690178         1150.3    156.4     67.1    104.9    151.0 103079.2

```
</details>

<details>
<summary>On `master`</summary>
<br>

no_suspect

```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           7649           12.7    331.8     28.3    130.0    209.7 103079.2  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0         146788          244.6    527.7     79.7    125.8    184.5 103079.2  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0         154437          257.4    518.0     75.5    125.8    184.5 103079.2

```

</details>

The throughput improvements are pretty nice, though I was surprised that, with this change, we were seeing any leases go back to `node 1` at all (since the workload generator is also not pointing to `node 1`). I don't think I understand why that's the case, but it's possible that one of the ways through which leases are transferred needs to be updated to filter out `suspect` stores. I couldn't immediately figure out what we're missing though. With a 20% chance of a slow heartbeat, there's about a ~6% chance of `node 1` successfully heartbeating for 1 minute so maybe that explains some of what we're seeing. :shrug:

**Comment by tbg** [comment]
Maybe a more robust way for the experiment would be to delay heartbeats for
30s, allow them for 30s, delay them for 30s again, etc (with the "not
delayed" period short enough to keep the store suspect)

**Comment by lunevalex** [comment]
Discussed this with @aayushshah15 offline a bit and we have a reasonable hypothesis for the fact that we still see some leases hang around on the bad node. The changes in this PR would only affect cooperative leases transfers through the allocator, but would not affect the ability of the bad node to steal leases via `replica.redirectOnOrAcquireLease` https://github.com/cockroachdb/cockroach/blob/736d0eb82d1f9258294e2e203cd63a6e7f81721f/pkg/kv/kvserver/replica_range_lease.go#L1050. The likely fix for that is to do what @tbg proposed above and move the suspected state to liveness. 

Given the positive affects of this change and the fact that adding a field to liveness is a non-starter for a backportable solution, I propose the following course of action. 
 1. Confirm the above hypothesis is correct through another reproduction
 2. Make a limited backportable change in the allocator, as proposed here. 
 3. Using this as a basis add suspect status to liveness and update replica.redirectOnOrAcquireLease to respect it, i.e. a node that is suspect would not attempt to acquire leases. This change would be made in a separate PR and only for 21.2.

**Comment by irfansharif** [comment]
I'm a bit hesitant to introduce "suspect" to node liveness now, just because doing it this way (N blips over X seconds) seems like an arbitrary indicator. I'll beat my failure-detector drum again and say that we could be a lot more principled about the all the various kind of signals we could consider for "suspect" nodes, but until we do, I would rather we not introduce the concept that would then necessitate backwards compatibility. I do agree that longer term that's the direction we'd want to move towards. When we do, perhaps the allocator could read off of node-liveness directly, instead of doing the kind of volatile-reader-side analysis it's doing today, and continuing to do in this PR (https://github.com/cockroachdb/cockroach/issues/50707).

I'm ok with this PR as is given it's an improvement on our allocator's behavior in the presence of blips. If we care about redirectOnOrAcquireLease, another gross hack could be exposing the allocator's view of suspect stores (especially it's own), and checking if the containing store is suspect before attempting to acquire leases. That would also be backport friendly.

**Review by aayushshah15 — COMMENTED** [review]
>Confirm the above hypothesis is correct through another reproduction

I was able to confirm that this is indeed the case. Since I was only injecting a random delay during node liveness heartbeats, `n1` was losing its range leases but not its raft leaderships. After #55148, this means that only `n1` could ever successfully re-acquire leases for such ranges. Here's a chart of successful lease request attempts per node (only `n1` is ever successful): 
leases success with suspect

Under a scenario where `n1` had an actually slow disk, would we expect the node to also lose its raft leaderships? [`etcd` claims to be sensitive to slow disks](https://etcd.io/docs/v3.3/faq/#why-does-etcd-lose-its-leader-from-disk-latency-spikes) but (AFAICT) there is no corresponding logic within `etcd/raft` at least. My understanding here is that if our processing of `raft.Ready`s is slow, our processing of raft ticks should be delayed and that should trigger leader elections.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-:-MZe90h0-e7QORCC0-31:bsexunv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lunevalex)

___
*[pkg/kv/kvserver/store_pool.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZ1TV2x4AbDycJn1XOb:-MZ1TV2x4AbDycJn1XOc:b8nd1y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/store_pool.go#L68)):*
> ```Go
> // it's last failure.
> var SuspectStoreDuration = settings.RegisterDurationSetting(
> 	"server.suspect_store_duration",
> ```

nit: how do you feel about `server.time_after_store_suspect` for consistency with the existing setting below?

**Review by lunevalex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lunevalex and @tbg)

___
*[pkg/kv/kvserver/store_pool.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZC-RO68Nwzn-1x_2UT:-MZkIr7G91uIDaaKH8Qg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/store_pool.go#L190)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/liveliness/liveness/ here and in other places
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/store_pool.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZC-X7-Csl5mpRhHENh:-MZkIwA02pagf_eqLIVX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/store_pool.go#L201)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

// failures
</blockquote></details>

Done.

**Review by lunevalex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/store_pool.go, line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MZC-_1F4y40J14auBTt:-MZzuU7U1zuseuGupdoU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f48f6904ed55570d6d03b9a7317ce244e9e505a3/pkg/kv/kvserver/store_pool.go#L226)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> its liveness heartbeat recently
</blockquote></details>

Done.

**Comment by sumeerbhola** [comment]
(Continuing one part of the conversation from https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1620157661074200)

I now understand that the direct motivation was the Pebble locking bug involving flushes and file cleaning, but IIRC we've also seen slow "hardware" in the sense of poor IOPs or high latency. Is that correct? If the answer is yes, then once we have admission control we will prioritize node liveness, which is likely to succeed while the rest of the traffic suffers. IIUC the allocator won't notice since the qps used in load-based rebalancing will be low.
It would be worth adding a TODO to enhance the signals used to mark a node as suspect. We may need to experiment to see what those signals should be -- the things that come to mind are "high" Pebble commit latency or read latency despite low read/write bandwidth. This relates to the comment from @irfansharif above about "I'll beat my failure-detector drum again and say that we could be a lot more principled about the all the various kind of signals we could consider for "suspect" nodes". 

More immediately, it seems to me that a write stall signal from Pebble could cover both this software problem and slow hardware (when it affects writes) -- we would need to set a threshold on fraction of time writes were stalled in order to be declared suspect, and gate it on bandwidth achieved during the non-stall time (to exclude cases where the write stall was a consequence of a huge burst). This threshold setting is harder than a binary node liveness signal but would be more robust in discovering problem nodes.

**Comment by lunevalex** [comment]
@tbg @nvanbenschoten this is ready for another view and I believe should be in a state where we can land this change now. PTAL and let me know.

**Review by aayushshah15 — COMMENTED** [review]
An issue that might deserve some consideration in this PR is a scenario where all nodes are marked suspect due to some sort of a maintenance event (imagine just restarting all nodes within the suspect duration), or because the entire cluster is under duress because all nodes are running at elevated levels of CPU utilization. More generally, in a multi-region cluster where all ranges have fully-constrained replicas, if all nodes inside of a "hot" region miss a liveness heartbeat, we end up in a similar boat.

If I understand correctly, this would effectively disable all load-based lease transfers and replica rebalancing in the cluster for those `server.time_after_store_suspect` seconds. This seems like it would be problematic in scenarios where all legal nodes are running hot. Does this seem like a problem? Is this something we think is worth handling in this PR? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-:-Ma7ITAz3JKEViUkTmpy:b-3gwfbv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lunevalex, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 546 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-Ma7LOvT5rKe5B6b6dfI:-Ma7LOvT5rKe5B6b6dfJ:b-53cpfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/daeb46096a8595fa1af6e9867a64b8eeb5346d9b/pkg/kv/kvserver/allocator_scorer.go#L546)):*
> ```Go
> 	for _, store := range allStores.stores {
> 		if !isStoreValidForRoutineReplicaTransfer(ctx, store.StoreID) {
> 			log.VEventf(ctx, 3, "not considering non-ready node s%d for rebalance", store.StoreID)
> ```

`s/node/store` in the log message. Though I think after a rebase you might not need to do that.
___
*[pkg/kv/kvserver/store_pool.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-Ma7RT_d03bpNDOPv0Kt:-Ma7RT_d03bpNDOPv0Ku:b-7ubfsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/daeb46096a8595fa1af6e9867a64b8eeb5346d9b/pkg/kv/kvserver/store_pool.go#L145)):*
> ```Go
> //    The node is considered LIVE (or DECOMMISSIONING or UNAVAILABLE if draining).
> //  - At tExp, the IsLive() method starts returning false. The state becomes
> //    UNAVAILABLE (or stays DECOMMISSIONING or UNAVAILABLE if draining).
> ```

We should update these to account for `DRAINING`
___
*[pkg/kv/kvserver/store_pool.go, line 649 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-Ma7Pbko3nv74lra9IK3:-Ma7Pbko3nv74lra9IK4:bc8tk6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/daeb46096a8595fa1af6e9867a64b8eeb5346d9b/pkg/kv/kvserver/store_pool.go#L649)):*
> ```Go
> 			// and should be used for up-replication if necessary.
> 			liveReplicas = append(liveReplicas, repl)
> 		case storeStatusUnknown, storeStatusSuspect:
> ```

Do you think this choice may need to be reconsidered in light of my comment above?
___
*[pkg/kv/kvserver/liveness/livenesspb/liveness.proto, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-Ma7QlalE4FZ2MQPiHRn:-Ma7QlalE4FZ2MQPiHRo:bnewqgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/daeb46096a8595fa1af6e9867a64b8eeb5346d9b/pkg/kv/kvserver/liveness/livenesspb/liveness.proto#L139)):*
> ```protobuf
>   NODE_STATUS_DECOMMISSIONED = 5 [(gogoproto.enumvalue_customname) = "DECOMMISSIONED"];
>   // DRAINING indicates a node that is in the process of draining.
>   NODE_STATUS_DRAINING = 6 [(gogoproto.enumvalue_customname) = "DRAINING"];
> ```

The comments above `NODE_STATUS_UNAVAILABLE` here should be updated. 

I'm curious if this is just a cosmetic change. This `NodeLivenessStatus` enum only seems to be used by `admin` and `status` endpoints and based on my skimming of the code we shouldn't need a migration for this, but I wonder if we want avoid making this change in this commit (purely out of an abundance of caution).

**Review by lunevalex — COMMENTED** [review]
This is an interesting question, but I think it will actually have the right effect. If a node is hot and misses liveness then this change will prevent that node from acquiring new replicas or leases until server.time_after_store_suspect seconds, which is what we want as it would give that node some breathing room to catch up. If all nodes are hot moving leases or replicas around just adds load to an already overloaded system, so it seems this behavior is desired. 

One negative side-effect as you point out is that if there is a maintenance event, then when a node restarts we will consider it suspect for server.time_after_store_suspect seconds. One way to control for that would be wipe out the lastAvailable timestamp in the store_pool when a node starts draining, this will prevent the node becoming suspect on a restart. Now that we actually have a draining state, we can do that. This will not work for a non-graceful shutdown because there is no way to know why a node failed liveness was it a kill -9, OOM or something else. I think that is a reasonable trade off for this feature that if you kill -9 a node without draining it takes a bit more time for it to start getting leases. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-:-MaEfbdh9ToqcZesd4Zf:bkn2hbm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @lunevalex, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 546 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-Ma7LOvT5rKe5B6b6dfI:-MaEedIq9CNi5bwScGCB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/daeb46096a8595fa1af6e9867a64b8eeb5346d9b/pkg/kv/kvserver/allocator_scorer.go#L546)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

`s/node/store` in the log message. Though I think after a rebase you might not need to do that.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/store_pool.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-Ma7RT_d03bpNDOPv0Kt:-MaEf12-4QtsCEC6GslN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/daeb46096a8595fa1af6e9867a64b8eeb5346d9b/pkg/kv/kvserver/store_pool.go#L145)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

We should update these to account for `DRAINING`
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/liveness/livenesspb/liveness.proto, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-Ma7QlalE4FZ2MQPiHRn:-MaEfBRgA4rKjrBiJSVK:b-sie3ww) ([raw file](https://github.com/cockroachdb/cockroach/blob/daeb46096a8595fa1af6e9867a64b8eeb5346d9b/pkg/kv/kvserver/liveness/livenesspb/liveness.proto#L139)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

The comments above `NODE_STATUS_UNAVAILABLE` here should be updated. 

I'm curious if this is just a cosmetic change. This `NodeLivenessStatus` enum only seems to be used by `admin` and `status` endpoints and based on my skimming of the code we shouldn't need a migration for this, but I wonder if we want avoid making this change in this commit (purely out of an abundance of caution). 
</blockquote></details>

it's purely a cosmetic change so we can distinguish between a failed liveness heartbeat and when a node is actually draining. It just makes the code easier to grok, it does not change any behavior.

**Review by aayushshah15 — APPROVED** [review]
>If all nodes are hot moving leases or replicas around just adds load to an already overloaded system

Ack.

>One way to control for that would be wipe out the lastAvailable timestamp in the store_pool when a node starts draining.

How do you feel about a maximum cap on `server.time_after_store_suspect`, perhaps along with a slightly shorter default?  I can't think of any scenarios where setting this to a value higher than 60 seconds would make sense (and a very high value for this setting definitely seems footgun-y). Do you see any issues with a ~30second default and perhaps a 60 second max? 

Everything else :lgtm_strong:  Thanks for pushing on the change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-:-MaFPmYu7iDTDWdFRDVE:ba0iva3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @lunevalex, @nvanbenschoten, and @tbg)

**Review by nvb — APPROVED** [review]
:lgtm:, and nice testing overall.

> How do you feel about a maximum cap on server.time_after_store_suspect, perhaps along with a slightly shorter default? I can't think of any scenarios where setting this to a value higher than 60 seconds would make sense (and a very high value for this setting definitely seems footgun-y). Do you see any issues with a ~30second default and perhaps a 60 second max?

These two suggestions both sound reasonable to me. We can pass a second validator to `TimeAfterStoreSuspect` to ensure that it's never set higher than some threshold. I'd permit a little more than 60 seconds though. Maybe 5m?

> Reviewed 4 of 11 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-:-MajWchmBLw3B8ke8lE_:b-1n3xtz)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aayushshah15, @lunevalex, and @tbg)

___
*[pkg/kv/kvserver/allocator_test.go, line 1871 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MajX6Mf8b59W3nWqUEe:-MajX6Mf8b59W3nWqUEf:bsl1p1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce4fee039b9805e36da9e4fa129fd1cecc7f6e9f/pkg/kv/kvserver/allocator_test.go#L1871)):*
> ```Go
> 	sg.GossipStores(stores, t)
> 
> 	runTest := func(expected bool) {
> ```

nit: consider renaming to `assertShouldTransferLease`

Also, you might want a `t.Helper()` in here.
___
*[pkg/kv/kvserver/store_pool.go, line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MajXcYuEn8vxqYkI7pZ:-MajXcYuEn8vxqYkI7p_:b-qhn5r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce4fee039b9805e36da9e4fa129fd1cecc7f6e9f/pkg/kv/kvserver/store_pool.go#L268)):*
> ```Go
> 	case livenesspb.NodeLivenessStatus_DRAINING:
> 		// Wipe out the lastAvailable timestamp, so if this node comes back after a
> 		// graceful restart it will not be considered as suspect.
> ```

Consider mentioning that this is best-effort. If we don't process a store between the time that it starts draining and the time that it is dead, we will never reset `lastAvailable`. To do any better, we'd need to reset `lastAvailable` when a node is dead as well. Did you think through the effect that doing so would have?

**Review by lunevalex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63999)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aayushshah15, @lunevalex, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/store_pool.go, line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63999#-MajXcYuEn8vxqYkI7pZ:-Matk6J05yIOjnEJIFYD:bcf9jpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce4fee039b9805e36da9e4fa129fd1cecc7f6e9f/pkg/kv/kvserver/store_pool.go#L268)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider mentioning that this is best-effort. If we don't process a store between the time that it starts draining and the time that it is dead, we will never reset `lastAvailable`. To do any better, we'd need to reset `lastAvailable` when a node is dead as well. Did you think through the effect that doing so would have?
</blockquote></details>

I think thats a good point and we should do a similar clear on a dead store as well, so that once a node comes up from death it's not considered suspect.

**Pull request merged**
