### PR TITLE
Pass a loaded range descriptor to an iterator in Snapshot()

### PR DESCRIPTION
**Pull request by kkaneda**
We used to pass `curDesc`, which is stored in memory, to `newRangeDataIterator()`. I couldn't come up with a concrete test case, but it seems that passing a descriptor loaded from an engine is safer since the descriptor might be changed concurrently (e.g., end key can change due to range split).

### CODE REVIEW

**Comment by tschottdorf** [comment]
yeah, this seems safer since now all the data that goes into the snapshot comes from the same (engine) snapshot. Could you make sure `curDesc` is only in scope immediately when it's needed (i.e. for reading the descriptor from the snapshot)?
Other than that, LGTM.

**Comment by kkaneda** [comment]
Sure! Since `curDesc` was actually used only at one place, I've removed the local variable (pass `r.Desc().StartKey` to `MVCCGetProto`) to clarify its scope.

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
LGTM

**Pull request merged**
