### PR TITLE
sql: make 'set tracing' just work

### LINKED ISSUE #23558: sql: session tracing inside a txn is painful
If one uses, for example, `crdb.ExecuteTx()` and has code like the following:
```
                if _, err := tx.Exec(`set tracing=on`); err != nil {
                    return err
                }
                defer func() {
                    _, _ = tx.Exec(`set tracing=off`)
                }()
```
that's no good cause the final `set tracing=off` is rejected if the txn is in an error state. Moreover, starting tracing on that conn again fails. We should allow `set tracing=off` in all states. Or something.

Hacks like the following help, although tracing leaks on conns where it isn't stopped properly.
```
            var tracing string
            if err := tx.QueryRow(`show tracing`).Scan(&tracing); err != nil {
                return err
            }
            if tracing != "off" {
                if _, err := tx.Exec(`set tracing=off; set tracing=on;`); err != nil {
                    return err
                }
            } else {
                if _, err := tx.Exec(`set tracing=on`); err != nil {
                    return err
                }
            }
```

cc @petermattis

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, starting tracing while tracing was ongoing, as well
as stopping tracing while it wasn't resulted in errors. Also, like all
statements, running set tracing in an aborted transaction was an error.
All these facts colluded to make tracing from a program around some code
that might result in errors hilariously frustrating - you start tracing,
then you may or may not get an error, then you want to stop tracing -
but how do you stop?

This patch makes it so that starting twice, stopping twice, or running
set tracing after an error, is a-OK.

Fixes #23558

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice cleanup and improvement!

The first commit should mention that if you start twice and stop once, it gets stopped. When I read it I assumed we would be using a "count" to support nested start/stops.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/conn_executor_exec.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaOGxTBxFjHfsqNTbd:-LBaOGxTBxFjHfsqNTbe:b6d2x9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/136f95a79dce05af6fc82fa19f92206ff45f9225/pkg/sql/conn_executor_exec.go#L35)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
> 	"github.com/cockroachdb/cockroach/pkg/util/tracing"
> 	"github.com/pkg/errors"
> ```

[nit] move this up to a separate block

---

*[pkg/sql/conn_executor_exec.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaONLK0QlysU6cV9n1:-LBaONLK0QlysU6cV9n2:b-o09iem) ([raw file](https://github.com/cockroachdb/cockroach/blob/136f95a79dce05af6fc82fa19f92206ff45f9225/pkg/sql/conn_executor_exec.go#L70)):*
> ```Go
> 	if _, ok := stmt.AST.(tree.ObserverStatement); ok {
> 		err := ex.runObserverStatement(ctx, stmt, res)
> 		log.Infof(ctx, "!!! observer stmt err: %v", err)
> ```

Did you intend to keep the `!!!`?

---

*[pkg/sql/conn_executor_exec.go, line 907 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaOfQa4C6ALxbTrlYu:-LBaOfQa4C6ALxbTrlYv:b-q7fn2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/136f95a79dce05af6fc82fa19f92206ff45f9225/pkg/sql/conn_executor_exec.go#L907)):*
> ```Go
> 		return ex.runShowSyntax(ctx, sqlStmt.Statement, res)
> 	case *tree.SetTracing:
> 		ex.runSetTracing(ctx, sqlStmt, res)
> ```

Why is SetTracing an "observer statement" (which is defined as not modifying the session state)?

---

*[pkg/sql/conn_executor_exec.go, line 961 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaP1po66GrV50r8ruw:-LBaP1po66GrV50r8rux:bif8go9) ([raw file](https://github.com/cockroachdb/cockroach/blob/136f95a79dce05af6fc82fa19f92206ff45f9225/pkg/sql/conn_executor_exec.go#L961)):*
> ```Go
> 	modes := make([]string, len(n.Values))
> 	for i, v := range n.Values {
> 		// Special rule for SET: because SET doesn't apply in the context
> ```

[nit] I think this is the third place now where we have a copy of this comment and code, I'd put it in a helper.

---

*[pkg/sql/vars.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaPpxX6LSPu7OUdrra:-LBaPpxX6LSPu7OUdrrb:b-bc5spo) ([raw file](https://github.com/cockroachdb/cockroach/blob/136f95a79dce05af6fc82fa19f92206ff45f9225/pkg/sql/vars.go#L585)):*
> ```Go
> 			return stopTracing(m)
> 		},
> 		// Setting is done by the SetTracing planNode.
> ```

It doesn't look like there's a SetTracing planNode, maybe needs updating?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-:-LBaPMPOBuwvYZDD-xg9:biuh5kr)*

**Comment by andreimatei** [comment]
TFTR!

---

Review status: 0 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/conn_executor_exec.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaOGxTBxFjHfsqNTbd:-LBaX7oA9BW6iBVCpYoc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/136f95a79dce05af6fc82fa19f92206ff45f9225/pkg/sql/conn_executor_exec.go#L35)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] move this up to a separate block
</blockquote></details>

Done.

---

*[pkg/sql/conn_executor_exec.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaONLK0QlysU6cV9n1:-LBaX9Wq0RPH_lYEMt1N:b-hc9g8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/136f95a79dce05af6fc82fa19f92206ff45f9225/pkg/sql/conn_executor_exec.go#L70)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Did you intend to keep the `!!!`?
</blockquote></details>

No :)
My scripts have failed me.

---

*[pkg/sql/conn_executor_exec.go, line 907 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaOfQa4C6ALxbTrlYu:-LBaY-_aBq-3kUflBm2C:b2dzvwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/136f95a79dce05af6fc82fa19f92206ff45f9225/pkg/sql/conn_executor_exec.go#L907)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why is SetTracing an "observer statement" (which is defined as not modifying the session state)?
</blockquote></details>

well the ObserverStatement is the mechanism we have for marking statements to be executed regardless of the state - which is what I want for this statement. I considered inventing a new mechanism because the ObserverStatements have special execution (they're not planned), which is not necessarily great, but I gave up because I didn't really need it and also there's some technical difficulties with planning in weird txn states.

I've modified the comment on `ObserverStatement` to make it less about what a statement is and isn't allowed to do, and more about how their execution actually happens (screw the OOP textbook). 

---

*[pkg/sql/conn_executor_exec.go, line 961 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaP1po66GrV50r8ruw:-LBaa2GQ-Rc6J9Tkuvgv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/136f95a79dce05af6fc82fa19f92206ff45f9225/pkg/sql/conn_executor_exec.go#L961)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I think this is the third place now where we have a copy of this comment and code, I'd put it in a helper.
</blockquote></details>

Done.

---

*[pkg/sql/vars.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaPpxX6LSPu7OUdrra:-LBaZU3p28Sq_-z2Tawb:by1t42n) ([raw file](https://github.com/cockroachdb/cockroach/blob/136f95a79dce05af6fc82fa19f92206ff45f9225/pkg/sql/vars.go#L585)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It doesn't look like there's a SetTracing planNode, maybe needs updating?
</blockquote></details>

good catch; leftover from a different attempt. Changed to "SetTracing statement", which is accurate.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-:-LBabJA9-ztZwX7PYZWR:b-814g8k)*

**Comment by andreimatei** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sem/tree/stmt.go, line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBaco-d0ZAwT9SAaxg5:-LBaenRHBUx1zX74cG4j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37f7bcf701fa9dde20b328daa0fa2d2e153bb5e8/pkg/sql/sem/tree/stmt.go#L163)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] there are (or planNode)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25262)*

**Comment by knz** [comment]
LGTM modulo finishing touches on sql.y

---

Reviewed 6 of 9 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/parse_test.go, line 788 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBafrZw9H6HYhTNCjGy:-LBafrZw9H6HYhTNCjGz:bwn8f0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1b1a4f84bbbcd0a30b52ab1ee7207343303aa9/pkg/sql/parser/parse_test.go#L788)):*
> ```Go
> 		{`SET TRANSACTION PRIORITY HIGH`},
> 		{`SET TRANSACTION ISOLATION LEVEL SNAPSHOT, PRIORITY HIGH`},
> 		{`SET TRACING = off`},
> ```

test with a list of multiple options. Test with TO too.

---

*[pkg/sql/parser/sql.y, line 2565 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBafxbm2ggQiAJ7otMx:-LBafxbm2ggQiAJ7otMy:b1kb4wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1b1a4f84bbbcd0a30b52ab1ee7207343303aa9/pkg/sql/parser/sql.y#L2565)):*
> ```Yacc
>   var_name TO var_list
>   {
>     $$.val = &tree.SetVar{Name: strings.Join($1.strs(), "."), Values: $3.exprs()}
> ```

you need the same action ({ ... }) here as below.

---

*[pkg/sql/parser/sql.y, line 2575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBafuEy9y-440QRZiGI:-LBafuEy9y-440QRZiGJ:b-d4kt9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1b1a4f84bbbcd0a30b52ab1ee7207343303aa9/pkg/sql/parser/sql.y#L2575)):*
> ```Yacc
>   }
>   }
> /*
> ```

remove this comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-:-LBagGEgAfSBOtczLha9:b-igw7up)*

**Comment by andreimatei** [comment]
Review status: 6 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/parser/parse_test.go, line 788 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBafrZw9H6HYhTNCjGy:-LBahe0zAWEFSXDWnEPa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1b1a4f84bbbcd0a30b52ab1ee7207343303aa9/pkg/sql/parser/parse_test.go#L788)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

test with a list of multiple options. Test with TO too.
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 2565 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBafxbm2ggQiAJ7otMx:-LBaiddNCFw-7i_9F6Fv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1b1a4f84bbbcd0a30b52ab1ee7207343303aa9/pkg/sql/parser/sql.y#L2565)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you need the same action ({ ... }) here as below.
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 2575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-LBafuEy9y-440QRZiGI:-LBaidwl1m4y_foL2yOW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1b1a4f84bbbcd0a30b52ab1ee7207343303aa9/pkg/sql/parser/sql.y#L2575)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

remove this comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25262)*

**Comment by knz** [comment]
Reviewed 2 of 7 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25262)*

**Comment by andreimatei** [comment]
bors r+

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-:-LBbCLNf0wY0c9NU8Oqh:b-ydi9ay)*

**Comment by andreimatei** [comment]
test flake filed #25291


bors r+

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25262#-:-LBbklXQ12bRj07DjswV:b3aj8r5)*

**Pull request merged**
