### PR TITLE
storage/pebbleiter: mangle unsafe buffers during positioning

### LINKED ISSUE #86657: storage: randomly clobber `UnsafeKey()` and `UnsafeValue()` in `pebbleIterator`
In #86440, we removed the `unsafeMVCCIterator` wrapping inside `intentInterleavingIter` in order to use a concrete `pebbleIterator` for performance. However, we lose the test coverage that `unsafeMVCCIterator` provided, by randomly clobbering unsafe byte slices. We should consider moving this into `pebbleIterator` itself, in addition to the `unsafeMVCCIterator` which is useful to wrap higher-level iterators.

https://github.com/cockroachdb/cockroach/pull/86440#pullrequestreview-1080608341

Jira issue: CRDB-18861

### PR DESCRIPTION
**Pull request by jbowens**
**storage/pebbleiter: mangle unsafe buffers between positioning methods**

Randomly clobber the key and value buffers in order to ensure lifetimes are respected. This commit extends the `pebbleiter.assertionIter` type used in `crdb_test` builds that sits between pkg/storage and the pebble.Iterator type. It now will randomly zero the buffers used to return the previous iterator position's key and value, to ensure code isn't improperly relying on the stability of the these keys.

**storage: fix UnsafeKey() usage of invalid iterator**

Previously, CheckSSTConflicts would improperly call UnsafeKey on an exhausted
sstIter. This could result in undefined, inconsistent behavior as UnsafeKey
may point to arbitrary data once the iterator is exhausted.

**kv/kvserver/spanset: fix read of invalid iterator's UnsafeKey**

Previously, the spanset.MVCCIterator implementation would retrieve the
contained iterator's UsafeKey() on an invalid iterator in Next, NextKey and
Prev. This retrieval was harmless because it always checked the validity of the
iterator before using it, but recent assertions in test builds prevent this
usage.

Epic: None
Close #86657.
Informs #94141.
Release note: None

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96685)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @erikgrinaker, and @itsbilal)

___
*[`pkg/storage/pebbleiter/crdb_test_on.go` line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNmq4k98abLlWL-Wudm:-NNmq4k98abLlWL-Wudn:b-a1loam) ([raw file](https://github.com/cockroachdb/cockroach/blob/070d2c3452967f455fd70abbee252ba0e90dde1a/pkg/storage/pebbleiter/crdb_test_on.go#L55)):*
> ```Go
> 		key [2][]byte
> 		val [2][]byte
> 	}
> ```

In a subsequent PR I plan to add similar mangling of `RangeBounds()` and `RangeKeys()`, but restricted to when `RangeKeyChanged()` to obey that more permissive contract.

**Comment by jbowens** [comment]
Checked and this does not resolve #94141.

**Review by bananabrick — COMMENTED** [review]
:lgtm: except the one part which I think @itsbilal should look over.

I have a slight preference for this being squashed into one commit. The first commit is introducing tests which would start failing if the second or third commit is reverted, right?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-:-NNnoeiK2rYb1ghpVX7M:bdmxjfx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, and @jbowens)

___
*[`pkg/kv/kvserver/spanset/batch.go` line 122 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNno6t56fZzPoLfYL72:-NNno6t56fZzPoLfYL73:b-1ybkxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/070d2c3452967f455fd70abbee252ba0e90dde1a/pkg/kv/kvserver/spanset/batch.go#L122)):*
> ```Go
> // checkAllowedCurrPosForward checks the span starting at the current iterator
> // position, if the current iterator position is valid.
> func (i *MVCCIterator) checkAllowedCurrPosForward(errIfDisallowed bool) {
> ```

We could check if `i.i.Valid()` and then call `checkAllowed` with the appropriate span from here. I guess that causes a duplicate `Valid` check.
___
*[`pkg/kv/kvserver/spanset/batch.go` line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNnnBb7E3w1YTIhHmck:-NNnnBb7E3w1YTIhHmcl:bxdz4s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/070d2c3452967f455fd70abbee252ba0e90dde1a/pkg/kv/kvserver/spanset/batch.go#L136)):*
> ```Go
> // checkAllowedCurrPosForward checks the provided span if the current iterator
> // position is valid.
> func (i *MVCCIterator) checkAllowed(span roachpb.Span, errIfDisallowed bool) {
> ```

"// checkAllowed checks" instead of "// checkAllowedCurrPosForward checks"...
___
*[`pkg/storage/sst.go` line 1080 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNnpcfF6JVaeHNMXxFi:-NNnpcfF6JVaeHNMXxFj:b-jdpktq) ([raw file](https://github.com/cockroachdb/cockroach/blob/070d2c3452967f455fd70abbee252ba0e90dde1a/pkg/storage/sst.go#L1080)):*
> ```Go
> 				// 3) both iterators changed keys and the sst iterator's key is further
> 				//    ahead.
> 				if sstOK && extChangedKeys && (!sstChangedKeys || !extOK || extIter.UnsafeKey().Key.Compare(sstIter.UnsafeKey().Key) < 0) {
> ```

This seems fine, but I'm not sure what the ramifications of not seeking here are. cc @itsbilal 
___
*[`pkg/storage/pebbleiter/crdb_test_on.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNniMuM9PTk9--hJ0cs:-NNniMuM9PTk9--hJ0ct:b-mo8jmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/88392b23980d4db4225cece959b3e63861354329/pkg/storage/pebbleiter/crdb_test_on.go#L31)):*
> ```Go
> // MaybeWrap returns the provided Pebble iterator, wrapped with double close
> // detection.
> func MaybeWrap(iter *pebble.Iterator) Iterator {
> ```

unrelated, but reading through the rest of this code since I've never seen this code before. Why is this called `MaybeWrap`, when it always seems to wrap the iterator?
___
*[`pkg/storage/pebbleiter/crdb_test_on.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNnj7_GDtO56Xr7h2i6:-NNnj7_GDtO56Xr7h2i7:bwyuqz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/88392b23980d4db4225cece959b3e63861354329/pkg/storage/pebbleiter/crdb_test_on.go#L94)):*
> ```Go
> func (i *assertionIter) LazyValue() pebble.LazyValue {
> 	if !i.Valid() {
> 		panic(errors.AssertionFailedf("Value() called on !Valid() pebble.Iterator"))
> ```

LazyValue called on...
___
*[`pkg/storage/pebbleiter/crdb_test_on.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNnjLj8519Vrqd-v-L3:-NNnjLj8519Vrqd-v-L4:bur8vrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/88392b23980d4db4225cece959b3e63861354329/pkg/storage/pebbleiter/crdb_test_on.go#L162)):*
> ```Go
> // the caller. This is used to ensure that the client respects the Pebble
> // iterator interface and the lifetimes of buffers it returns.
> func (i *assertionIter) mangleBufs() {
> ```

nit: maybeMangleBufs? And what's the benefit to doing this randomly as opposed to always?

**Review by jbowens — COMMENTED** [review]
TFTR!

> I have a slight preference for this being squashed into one commit. The first commit is introducing tests which would start failing if the second or third commit is reverted, right?

Yes, but the bug wouldn't stop existing if the second or third commit were reverted.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-:-NNqne-u2LliqmCneokS:blkzdf2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick, @erikgrinaker, @itsbilal, and @jbowens)

___
*[`pkg/kv/kvserver/spanset/batch.go` line 122 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNno6t56fZzPoLfYL72:-NNqlGgB2APoBRf_Wrb-:bq41yow) ([raw file](https://github.com/cockroachdb/cockroach/blob/070d2c3452967f455fd70abbee252ba0e90dde1a/pkg/kv/kvserver/spanset/batch.go#L122)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

We could check if `i.i.Valid()` and then call `checkAllowed` with the appropriate span from here. I guess that causes a duplicate `Valid` check.
</blockquote></details>

yep, this structure is intended to avoid the duplicate `Valid` calls
___
*[`pkg/kv/kvserver/spanset/batch.go` line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNnnBb7E3w1YTIhHmck:-NNqlaDN5ffVn2qVRC16:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/070d2c3452967f455fd70abbee252ba0e90dde1a/pkg/kv/kvserver/spanset/batch.go#L136)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

"// checkAllowed checks" instead of "// checkAllowedCurrPosForward checks"...
</blockquote></details>

Done.
___
*[`pkg/storage/pebbleiter/crdb_test_on.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNniMuM9PTk9--hJ0cs:-NNqlmzA1AHAldiTma46:b-yoznel) ([raw file](https://github.com/cockroachdb/cockroach/blob/88392b23980d4db4225cece959b3e63861354329/pkg/storage/pebbleiter/crdb_test_on.go#L31)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

unrelated, but reading through the rest of this code since I've never seen this code before. Why is this called `MaybeWrap`, when it always seems to wrap the iterator?
</blockquote></details>

There are two implementations of `MaybeWrap`, controlled by build tags. The one used when the `crdb_test` build tag is _not_ present does not wrap the iterator.
___
*[`pkg/storage/pebbleiter/crdb_test_on.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNnj7_GDtO56Xr7h2i6:-NNqmYyX70pd2NgNAa1v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88392b23980d4db4225cece959b3e63861354329/pkg/storage/pebbleiter/crdb_test_on.go#L94)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

LazyValue called on...
</blockquote></details>

Done.
___
*[`pkg/storage/pebbleiter/crdb_test_on.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNnjLj8519Vrqd-v-L3:-NNqmZDpC6zLAeetZN2P:bm8xqkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/88392b23980d4db4225cece959b3e63861354329/pkg/storage/pebbleiter/crdb_test_on.go#L162)):*
> nit: maybeMangleBufs?

Sure

> And what's the benefit to doing this randomly as opposed to always?

It ensures no usages are dependent on either behavior. No clients should expect the buffers to remain the same, but they also should not expect the buffers to be zeroed.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-:-NNrZrNEE1nDIq0Yfs_u:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick and @erikgrinaker)

___
*[`pkg/storage/sst.go` line 1080 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96685#-NNnpcfF6JVaeHNMXxFi:-NNrX_DB9GBtw0MojAjq:bb6ywmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/070d2c3452967f455fd70abbee252ba0e90dde1a/pkg/storage/sst.go#L1080)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

This seems fine, but I'm not sure what the ramifications of not seeking here are. cc @itsbilal 
</blockquote></details>

LGTM

**Comment by jbowens** [comment]
TFTRs!

bors r+

**Pull request merged**
