### PR TITLE
Add support for chaining of TestingCommandFilter's.

### LINKED ISSUE #4757: storage.TestingCommandFilter should be a function
We need to make it easier to not get this wrong in tests, see #4755. Here's a proposal:

```diff
diff --git a/storage/replica.go b/storage/replica.go
index 267d768..de33bfa 100644
--- a/storage/replica.go
+++ b/storage/replica.go
@@ -77,13 +77,20 @@ const (
 	opReplica = "replica"
 )
 
-// TestingCommandFilter may be set in tests to intercept the handling
-// of commands and artificially generate errors. Return nil to continue
-// with regular processing or non-nil to terminate processing with the
-// returned error. Note that in a multi-replica test this filter will
-// be run once for each replica and must produce consistent results
-// each time.
-var TestingCommandFilter func(roachpb.StoreID, roachpb.Request, roachpb.Header) error
+// SetTestingCommandFilter may be used in tests to intercept the handling of
+// commands and artificially generate errors. Return nil to continue with
+// regular processing or non-nil to terminate processing with the returned
+// error. Note that in a multi-replica test this filter will be run once for
+// each replica and must produce consistent results each time.
+func SetTestingCommandFilter(filter func(roachpb.StoreID, roachpb.Request, roachpb.Header) error) func() {
+	if testingCommandFilter != nil {
+		panic("cannot set testingCommandFilter because it is already non-nil")
+	}
+	testingCommandFilter = filter
+	return func() { testingCommandFilter = nil }
+}
+
+var testingCommandFilter func(roachpb.StoreID, roachpb.Request, roachpb.Header) error
 
 // This flag controls whether Transaction entries are automatically gc'ed
 // upon EndTransaction if they only have local intents (which can be

```

### PR DESCRIPTION
**Pull request by andreimatei**
This is useful for SQL tests which add one filter by default.

This also eliminates a race in TestTxnRestarts.

Fixes #4757, #4753

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4785)

### CODE REVIEW

**Comment by tamird** [comment]
commit message: no apostrophe on "Filters", and you need the strings "Fixes #4757" and "Fixes #4753" to both appear in the commit message for github to close both issues.

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/main_test.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtE12QHG0AIA1PxVAz:-KBtE12QHG0AIA1PxVB-:894574786) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/main_test.go#L95)):*
why append the nuclear `Reset` instead of the return from AppendFilter? also, no need to wrap this in an extra anonymous function.

---

*[sql/txn_restart_test.go, line 99 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtDsf95BTZYD0HspCW:-KBtDj0x12omhISn4M0Z:-735512734) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/txn_restart_test.go#L99)):*
this should be deferred.

---

*[sql/txn_restart_test.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtEpUAVeNof7qSQP3M:-KBtEpUBBD6J4Dq5toWz:-1375599040) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/txn_restart_test.go#L113)):*
how come you need to set this again?

---

*[storage/replica.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtED9NPbZRz-HTWSZO:-KBtED9NPbZRz-HTWSZP:196262558) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L80)):*
s/types/type/

---

*[storage/replica.go, line 107 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtEyeFwv5SMkK0j0L7:-KBtEyeFwv5SMkK0j0L8:166874) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L107)):*
?

---

*[storage/replica.go, line 116 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtF96lkxHO2oWHJ-_T:-KBtF96lkxHO2oWHJ-_U:1700244956) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L116)):*
s/and/any/

---

*[storage/replica.go, line 123 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtEU1zHMu_59nzftTA:-KBtEU2-y1b0WnDZXcHa:1247109850) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L123)):*
this never gets cleaned up, which is concerning for cases where tests and benchmarks are run in the same invocation - the benchmarks will lie.

---

*[storage/replica.go, line 136 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtFGS-NvFQ7RVUp7YM:-KBtFGS-NvFQ7RVUp7YN:-1070356174) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L136)):*
inline this below: `if err := ...; err != nil {`

---

*[storage/replica.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtFKaMathwCSzNU4pS:-KBtFKaMathwCSzNU4pT:-1972193943) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L145)):*
s/filtes/filters/

---

*[storage/replica.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtDOWmGis36jBd7Y4g:-KBtDOWmGis36jBd7Y4h:388149285) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L178)):*
I don't think you want this to be an exported function. Can you return it from GetTestingCommandFilters? On second thought, I think you can just remove it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/main_test.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtE12QHG0AIA1PxVAz:-KBtnrtutg8qLSNlcG2s:-580300062) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/main_test.go#L95)):*
Because we want the nuclear options in between tests; protects from badly-written tests fucking up other tests.

Fixed the wrapping.

---

*[sql/txn_restart_test.go, line 99 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtDsf95BTZYD0HspCW:-KBto5i1YB4WAgrM8URi:2146729406) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/txn_restart_test.go#L99)):*
nope, i want to get rid of the filter now so I can add another filter below

---

*[sql/txn_restart_test.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtEpUAVeNof7qSQP3M:-KBtoBECntfADM0WMGB_:787601823) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/txn_restart_test.go#L113)):*
because now the filter does something else. I could have just modified `magicVals` and left the same filter in place, but then the filter needs synchronization inside. This way the filter is nice: short and dumb.

---

*[storage/replica.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtED9NPbZRz-HTWSZO:-KBtmne-C5SzlRnWbaE4:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L80)):*
Done.

---

*[storage/replica.go, line 107 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtEyeFwv5SMkK0j0L7:-KBtmrT2lwlj3lheRU9I:2103372956) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L107)):*
suggests that this is the one and only CommandFilters that's ever going to exist

---

*[storage/replica.go, line 116 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtF96lkxHO2oWHJ-_T:-KBtn4pNBg3M4Ru4Dukc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L116)):*
Done.

---

*[storage/replica.go, line 136 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtFGS-NvFQ7RVUp7YM:-KBtnEQI69eW3x2txuiw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L136)):*
Done.

---

*[storage/replica.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtFKaMathwCSzNU4pS:-KBtnILJk2Wfo3_h28cd:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L145)):*
Done.

---

*[storage/replica.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtDOWmGis36jBd7Y4g:-KBtnLIFZsvYVsQBIG7I:-23031444) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L178)):*
This protects against tests forgetting to do their own cleanup; you definitely want to start with a fresh state on every test.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785)*

**Comment by andreimatei** [comment]
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[storage/replica.go, line 123 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtEU1zHMu_59nzftTA:-KBtovqoUUWb_IGXXOUQ:-1205073757) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L123)):*
I wouldn't call this "concerning" :)  In fact, we should probably just take the mutex in read mode in prod code too when looking at the global.

But anyway, the alternative is to have replace the `sync.Once` with comparing `TestingCommandFilter` to nil, and set it back to nil in `Reset()` (at which point Reset becomes crucial, and cannot be replaced with everybody just running the cleanup that they get from calling `AppendFilter`.

Let's see what happens to Toby's diff too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785)*

**Comment by bdarnell** [comment]
I don't really like either of the `TestingCommandFilter` PRs; they both build a lot of complexity around something that we want to discourage anyway. (#4757 looks like a good idea to me). This PR in particular allows and might encourage use of more complex arrangements of TestingCommandFilters, and I think this is a sign that TestingCommandFilter is not the right tool for the job. Why don't we just put the `checkEndTransactionTrigger` logic in `EndTransaction` itself, and then TestingCommandFilter can be reserved for per-test fault injection?

**Comment by tschottdorf** [comment]
> they both build a lot of complexity around something that we want to discourage anyway.

I must be missing something about my PR #4766 since that comes up again and again, but that PR adds nothing new - it just removes two frequent errors, namely fiddling with the filter while there are running and forgetting to unset them when done, and at the same time makes it very clear that a test is mocking.
In fact, it's exactly #4757 plus allowing to set the filter whenever, which is what unversed test writers will do and which won't obviously fail.

Anyway, my main interest is avoiding that this thing becomes more complex (such as in this PR) is currently turning into a joint waste of efforts. I'm ok with just settling for #4757 for now; doesn't make the data races go away but then what else is the race detector for.

It's a problematic standpoint to discourage TestingCommandFilter without providing a viable alternative; some PRs like #4507 are legitimate uses since they just want to manufacture transaction restarts. With SQL, I'm assuming that more and more of those use cases come up, and more complex ones as well, such as in @andreimatei's test here. We shouldn't complicate that unnecessarily. Then again, this one here looks like a solution which is part of the problem (and in search of one). @andreimatei, if you really need some of this for your test, maybe put it into/next to it, at least for now.
Does another EndTransactionTrigger really solve the problem? That's just a special-cased TestingCommandFilter

Could plumb this method on a Context instead? I'd feel way more comfortable about that in general since it gets rid of the global and forces setting the interceptor early (plus it can grow without turning into spaghetti).

**Comment by tamird** [comment]
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/txn_restart_test.go, line 99 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtDsf95BTZYD0HspCW:-KBx9RiO_FDyuZF3ClYz:477547097) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/txn_restart_test.go#L99)):*
I mean that it should run via defer, not that it should run at the end of the test.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/main_test.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtE12QHG0AIA1PxVAz:-KBxAlfR5LNtVdqql9m5:504171232) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/main_test.go#L95)):*
See other comment about nuclear options. 

---

*[sql/txn_restart_test.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtEpUAVeNof7qSQP3M:-KBxAI1McrXnoLNW2dta:648559807) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/txn_restart_test.go#L113)):*
Per discussion offline, the filter is already racy. It's not clear to me what the benefit of avoid a lock is, it adds two lines to the filter, and two lines here where you reset the data.

---

*[storage/replica.go, line 107 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtEyeFwv5SMkK0j0L7:-KBxAVA3IwWStEmvTCPq:1075954565) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L107)):*
It's already in the name.

---

*[storage/replica.go, line 123 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtEU1zHMu_59nzftTA:-KBxAaGdZVcx0y037dxw:160383661) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L123)):*
OK.

---

*[storage/replica.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtDOWmGis36jBd7Y4g:-KBxAdLLnNB__ba_Y4zQ:-1657240802) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L178)):*
As discussed offline, this creates an opportunity for badly written tests to have their badness hidden by this function. We should figure out a way to make sure that every test cleans up correctly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785)*

**Comment by andreimatei** [comment]
@tschottdorf @bdarnell PTAL at the last commit

---

Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-:-KBxmemTin5zDYMnyUyF:-1017400069)*

**Comment by tschottdorf** [comment]
I haven't looked in detail at the logic contained in the last commit, but as discussed this is the direction that I would prefer.
To recap that discussion, we already have another test switch that we fiddle with at the moment (`txnAutoGC`) and both (and any others we incur over time) could live here; same with `tracing.Disable()` if we decide we need to keep it (but I hope we won't). Tests could (theoretically) run in parallel which is soothing even if we don't make us of it. Having a small number of "configurable", safe switches which are testing-only, explicit and well-documented makes this useful as opposed to hacky.
The context is created before the test runs, so no more races (or at least very unlikely). No more global state which can be left polluted. I'm 
The downside is a little bit of plumbing, but it's relatively straightforward as the context already goes to the right places.

**Comment by bdarnell** [comment]
> Does another EndTransactionTrigger really solve the problem? That's just a special-cased TestingCommandFilter

I wasn't suggesting we introduce another EndTransactionTrigger. I was suggesting that the logic in `checkEndTransactionTrigger` be moved out of a test hook and run on every `EndTransaction` call. That would (at least so far) remove the need to run two TestingCommandFilters simultaneously.

+1 to getting rid of globals and plumbing them through the context instead.

**Comment by andreimatei** [comment]
Moved all the tests over.

---

Review status: 0 of 19 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-:-KCIw9ac-aWONtSfnFFs:772161275)*

**Comment by tamird** [comment]
Reviewed 3 of 8 files at r3, 14 of 14 files at r5.
Review status: 17 of 19 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[server/context.go, line 126 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIyD1qHva_atbxcLKL:-KCIyD1qHva_atbxcLKM:1887313217) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/context.go#L126)):*
can you add a comment here explaining that at present this is here for the purpose of plumbing it down into the store context?

---

*[server/context.go, line 131 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIyL3rDg6nQoM_GmoM:-KCIyL3rDg6nQoM_GmoN:-1130164620) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/context.go#L131)):*
can't you just use `storage.StoreTestingMocker` directly?

---

*[server/testserver.go, line 53 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIylJsZ215ul2k2TaH:-KCIylJsZ215ul2k2TaI:-1725805133) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/testserver.go#L53)):*
s/a/an/

---

*[server/testserver.go, line 67 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIygw48FkRvm4gMxzP:-KCIygw48FkRvm4gMxzQ:-1725805133) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/testserver.go#L67)):*
s/a/an/

---

*[storage/replica_command.go, line 59 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIx0HhBUfZTOd7Tvk8:-KCIx0HixX8tvJzy4ppu:1534952542) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/storage/replica_command.go#L59)):*
tip: shorten the next line by using `if filter := r.store.ctx.TestingMocker.TestingCommandFilter; filter != nil {` on this line

---

*[storage/store_test.go, line 126 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIxguwTat0CemXg-ac:-KCIxguwTat0CemXg-ad:1451429201) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/storage/store_test.go#L126)):*
why does this take a `*StoreContext`? you end up dereferencing it in this function, so sharing it with the caller doesn't seem to help much.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785)*

**Comment by andreimatei** [comment]
Review status: 10 of 19 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/context.go, line 126 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIyD1qHva_atbxcLKL:-KCLwH-E-Kv4bw9Tm18R:-502483865) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/context.go#L126)):*
this is gonna get  expanded pretty quickly with all sorts of things; already got requests from @nvanbenschoten and @tschottdorf

---

*[server/context.go, line 131 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIyL3rDg6nQoM_GmoM:-KCLzMvqG3IRXl2AFRR8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/context.go#L131)):*
Done.

---

*[server/testserver.go, line 53 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIylJsZ215ul2k2TaH:-KCM1yPQw-ICjW2ffa0S:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/testserver.go#L53)):*
Done.

---

*[server/testserver.go, line 67 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIygw48FkRvm4gMxzP:-KCLzUgfztX_mJJxkwER:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/testserver.go#L67)):*
Done.

---

*[sql/main_test.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtE12QHG0AIA1PxVAz:-KCLzY94Y-lRSKLKfKjK:370911595) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/main_test.go#L95)):*
no more nuclear warfare

---

*[sql/txn_restart_test.go, line 99 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtDsf95BTZYD0HspCW:-KCLzmU16lhD6jV3QJE4:454387696) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/txn_restart_test.go#L99)):*
now there's no more globals, it doesn't matter any more if the cleanup doesn't run on various test failures

---

*[sql/txn_restart_test.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtEpUAVeNof7qSQP3M:-KCM0BLU1XrkKfZEz_65:2137512728) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/sql/txn_restart_test.go#L113)):*
made the filter take a lock. But I still left the test code using two separate filters for the two phases, I think it's cleaner and easier to read.

---

*[storage/replica.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KBtDOWmGis36jBd7Y4g:-KCM0JiEi9JmchMcIypu:1891725987) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb9474e8cc2fa106ebf0e3452a44241379b0d57d/storage/replica.go#L178)):*
no longer an issue

---

*[storage/replica_command.go, line 59 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIx0HhBUfZTOd7Tvk8:-KCM1RvA2O7Nq4txtr2L:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/storage/replica_command.go#L59)):*
Done.

---

*[storage/store_test.go, line 126 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIxguwTat0CemXg-ac:-KCM1YKhPwQt7i54Ha9u:-2103602295) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/storage/store_test.go#L126)):*
well, it (arguably) makes sense to share because the context gets further populated in this function. What's going on is not very clean - we should move the context population out of this function and have this take a const ctx, but meh too much to refactor

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785)*

**Comment by tschottdorf** [comment]
Reviewed 10 of 14 files at r5, 9 of 9 files at r6.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[server/context.go, line 126 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIyD1qHva_atbxcLKL:-KCM3YQQY8OMPOF0yWIi:257253886) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/context.go#L126)):*
There are some existing mocks/switches around the codebase which I'll unify here when this lands, in the course of which I'm going to add more comments. Still, a one-liner wouldn't hurt.

---

*[server/server.go, line 199 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCM3sHabGgE3CWGrvUs:-KCM3sHabGgE3CWGrvUt:1977548495) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/server.go#L199)):*
I thought we were going to have only a single Mocker type, not StoreTestingMocker and TestingMocker (which means that there have to be conversions).  Why the choice for two? It would seem that StoreTestingMocker would always be a subset of TestingMocker. My preference would be to remove the former, unless there's an rationale for the existence of both.

---

*[storage/replica_test.go, line 102 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCM5r83WmQcRiWrO1SX:-KCM5r83WmQcRiWrO1SY:-928619802) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fc339e2cfea82a5fb50751f5ca442f842abd79/storage/replica_test.go#L102)):*
s/testContext\.// in those comments here and below.

---

*[storage/store_test.go, line 126 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIxguwTat0CemXg-ac:-KCM6547-SRUDTtcPBvx:1585157922) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/storage/store_test.go#L126)):*
At least add a comment to `createTestStoreWithoutStart`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785)*

**Comment by andreimatei** [comment]
Review status: 6 of 19 files reviewed at latest revision, 11 unresolved discussions.

---

*[server/context.go, line 126 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIyD1qHva_atbxcLKL:-KCMB7UsQ5MgRDtAlpWz:1040045680) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/context.go#L126)):*
I don't know what to write besides the type comment that's right below.

---

*[server/server.go, line 199 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCM3sHabGgE3CWGrvUs:-KCMAMJZLvYBAhaNja28:-1404386757) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/server/server.go#L199)):*
discussed, let's leave it

---

*[storage/replica_test.go, line 102 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCM5r83WmQcRiWrO1SX:-KCMAXpND7UdTaRp3Em4:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fc339e2cfea82a5fb50751f5ca442f842abd79/storage/replica_test.go#L102)):*
Done.

---

*[storage/store_test.go, line 126 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCIxguwTat0CemXg-ac:-KCMApy1JzAFoVnrHnho:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b294d0728b88a42738a453c63e94b599f2860c6/storage/store_test.go#L126)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r7.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-:-KCMF94ZMi5_I75XTpa-:1417088721)*

**Comment by tamird** [comment]
Seems like this should have been squash before merging.

---

Reviewed 2 of 9 files at r6, 13 of 13 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/txn_restart_test.go, line 38 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCMLtCcImBd28xdWWKf:-KCMLtCcImBd28xdWWKg:1750412204) ([raw file](https://github.com/cockroachdb/cockroach/blob/994a08123bef64d9e8d7759b40ad89e384fe6aaa/sql/txn_restart_test.go#L38)):*
this line is no longer so long, can you put this all above?

---

*[sql/txn_restart_test.go, line 120 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCMMuMXA8bNr3wE7NQC:-KCMMuMXA8bNr3wE7NQD:-209244810) ([raw file](https://github.com/cockroachdb/cockroach/blob/994a08123bef64d9e8d7759b40ad89e384fe6aaa/sql/txn_restart_test.go#L120)):*
instead of doing this unregister-and-reregister dance, can't you hold the magicVals lock here?

---

*[storage/replica_command.go, line 59 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCMK_st1KfuC3QR7f4z:-KCMK_st1KfuC3QR7f5-:2024159601) ([raw file](https://github.com/cockroachdb/cockroach/blob/994a08123bef64d9e8d7759b40ad89e384fe6aaa/storage/replica_command.go#L59)):*
nit: prefer shorter lifetimes, that is: `if err := ...; err != nil {`

---

*[storage/store_test.go, line 964 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-KCMKvcUJ3a98-PL_hjE:-KCMKvcUJ3a98-PL_hjF:150221728) ([raw file](https://github.com/cockroachdb/cockroach/blob/994a08123bef64d9e8d7759b40ad89e384fe6aaa/storage/store_test.go#L964)):*
slightly cleaner to write
```
if pr, ok := args.(*roachpb.PushTxnRequest); ok && pr.PusherTxn.Name == "test" {
	if exp, act := mc.UnixNano(), pr.PushTo.WallTime; exp > act {
		return fmt.Errorf("expected PushTo >= WallTime, but got %d < %d:\n%+v", act, exp, pr)
	}
}
return nil
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4785#-:-KCMKBuy3RUP1moFviLH:2077513597)*

**Pull request merged**
