### PR TITLE
Revert change to run with multiple CPUs by default.

### PR DESCRIPTION
**Pull request by bdarnell**
This was merged prematurely; we need to fix the issues that this
change uncovers before we start causing failures in master and unrelated
PRs.

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. For posterity, we will revisit this when these are fixed:
- https://github.com/cockroachdb/cockroach/issues/1531
- https://github.com/cockroachdb/cockroach/issues/1532
- https://github.com/cockroachdb/cockroach/issues/1536
- https://github.com/cockroachdb/cockroach/issues/1544
- https://github.com/cockroachdb/cockroach/issues/1551
- https://github.com/cockroachdb/cockroach/issues/1558
- https://github.com/cockroachdb/cockroach/issues/1563

**Comment by tamird** [comment]
@bdarnell how about setting CPUS=1 in circle.yml? It'd be nice to run multi-cpu locally to reduce the probability of regression

**Comment by bdarnell** [comment]
We don't have a clean way of detecting whether we're on circleci. Master builds run the tests twice, in one case very far removed from circle.yml. Also, while race-related failures are rare locally, they still happen. Better to err on the side of avoiding spurious failures.

**Comment by tschottdorf** [comment]
I think we'll have a hard time even finding the races that prevent us from running on multiple CPUs on CircleCI if we don't ever do that. A lot of the races that pop up there I've never been able to find locally, despite trying. Why not run `make test` with multiple CPUs and ignore the return code? We can easily set things up so that this creates an issue but doesn't fail the build.

**Comment by bdarnell** [comment]
@tschottdorf We already have 7 issues to work on. When we fix those, we'll make a new PR to set CPUs to 2, and retry the build of that PR many times to shake out any issues before merging it. If we have something automatically create issues then we'll just have to triage those and handle a lot of duplicates of the 7 we already have.

**Comment by tschottdorf** [comment]
ok. Up to date list using labels is at https://github.com/cockroachdb/cockroach/labels/multi-cpu

**Pull request merged**
