### PR TITLE
sql,pgwire: rework the implementation of the Copy-in pgwire subprotocol

### PR DESCRIPTION
**Pull request by andreimatei**
The COPY... FROM STDIN statement is special: it puts the connection into
a special mode allowing the client to keep sending data.
Before this patch, the implementation of this protocol was very
convoluted - the v3Conn, Executor, Session, Copy node and CopyData
statement all collaborated to get things going: the connection would
send the COPY FROM stmt to the Executor, which would execute it and
return a result which had the side-effect of shifting the conn to a state
machine that would produce (with the collaboration of the Session)
synthetic CopyData statements. These statements were executed and they'd
accumulate data in a session-bound object. Finally, the connection would
send a special instance of the CopyData statement that would clean the
session.

This intertwining of the connection and the execution layer is a problem
for the upcoming rewrite of these modules, which insists on a clean
separation between them.
This patch moves to an implementation that recognizes COPY FROM as a
special instruction. This instruction does not have a plan; instead, it
is supported by a struct that takes ownership of the pgwire connection
and encapsulates the buffering of data, execution of the insertNodes and
aoptionally management of transactions (if executed outside of an
explicit transaction) and network communication. Control of the
connection is handed back to the pgwire server when the subprotocol
finishes.

This patch also happens to fix two issues with the previous code:
1) something was wrong with the reporting of the command tag and the
ServerMsgCommandComplete msg. This could be seen by running a copy with
psql and noticing that nothing was being printed to the console after
the final "\.". postgres and the new code print "COPY <rows>".
2) the memory used for batching rows was accounted to the wrong monitor
as #21278 explains.

Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 32 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/copy.go, line 45 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2cq96W20hLiMPAsxYe:-L2cq96W20hLiMPAsxYf:bymea3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/copy.go#L45)):*
> ```Go
> //
> // Incoming data is buffered and batched; batches are turned into insertNodes
> // that are executed. INSERT priviledges are required on the destination table.
> ```

"privileges"

---

*[pkg/sql/copy.go, line 135 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2cqn3U11j5N1_ejGCV:-L2cqn3U11j5N1_ejGCW:b-ei3c7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/copy.go#L135)):*
> ```Go
> 				return err
> 			}
> 			done = true
> ```

nit: I think using a named break here is easier to follow than setting a bool (because then I'm forced to find all usages of done). But whatever.

---

*[pkg/sql/executor.go, line 706 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2cspQxtS6pZ9Bj3Mv-:-L2cspQxtS6pZ9Bj3Mv0:b-xuqnwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/executor.go#L706)):*
> ```Go
> 	session.phaseTimes[sessionStartParse] = timeutil.Now()
> 	var sl tree.StatementList
> 	sl, err = parser.Parse(sql)
> ```

`sl, err :=` is sufficient here, and you can remove the var line above

---

*[pkg/sql/executor.go, line 707 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2ct2ECYbGUZjh-OzUN:-L2ct2EDpuN7yc2rhyNe:b-310n8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/executor.go#L707)):*
> ```Go
> 	var sl tree.StatementList
> 	sl, err = parser.Parse(sql)
> 	stmts = NewStatementList(sl)
> ```

same here: `stmts :=`

---

*[pkg/sql/executor.go, line 1776 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2ctN0bdQeoBVuEnmJC:-L2ctN0bdQeoBVuEnmJD:b-vnoace) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/executor.go#L1776)):*
> ```Go
> 		p := &session.planner
> 		session.resetPlanner(p, e, txnState.mu.txn)
> 		p.extendedEvalCtx.SetTxnTimestamp(txnState.sqlTimestamp)
> ```

Just want to make sure I know what's going on here with these two times. COPY can take many minutes to get all its data. Assuming the user is executing this long COPY outside of an explicit txn (clearly, because we would complain otherwise), then each batched INSERT should have its txn timestamp set to the time that particular INSERT was executed. Is that what happens here? We also need to do the opposite in a BEGIN/COMMIT block, too (that is, not changing the txn timestamp on each INSERT batch).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408)*

**Comment by andreimatei** [comment]
Review status: 0 of 32 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/copy.go, line 45 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2cq96W20hLiMPAsxYe:-L2fpx-ynrRMsHFNmkwr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/copy.go#L45)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

"privileges"
</blockquote></details>

Done.

---

*[pkg/sql/copy.go, line 135 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2cqn3U11j5N1_ejGCV:-L2fq_p4aLJP_HTPDd80:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/copy.go#L135)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

nit: I think using a named break here is easier to follow than setting a bool (because then I'm forced to find all usages of done). But whatever.
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 706 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2cspQxtS6pZ9Bj3Mv-:-L2fqr835DGDm4X0Cp_N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/executor.go#L706)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

`sl, err :=` is sufficient here, and you can remove the var line above
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 707 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2ct2ECYbGUZjh-OzUN:-L2fqquCqVJtI6qidI7L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/executor.go#L707)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

same here: `stmts :=`
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 1776 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2ctN0bdQeoBVuEnmJC:-L2frCqtaVQAkkZcPTFT:bskdnhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/executor.go#L1776)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Just want to make sure I know what's going on here with these two times. COPY can take many minutes to get all its data. Assuming the user is executing this long COPY outside of an explicit txn (clearly, because we would complain otherwise), then each batched INSERT should have its txn timestamp set to the time that particular INSERT was executed. Is that what happens here? We also need to do the opposite in a BEGIN/COMMIT block, too (that is, not changing the txn timestamp on each INSERT batch).
</blockquote></details>

The executor no longer sees the  `INSERTs`; their planning and execution is completely encapsulated by the `copyMachine`. This code only runs once for the whole copy protocol and sets up the planner for the use of the machine. So there's one timestamp: the timestamp of the transaction in which the `COPY FROM` is executed. Whether that txn is explicit or implicit doesn't matter here - there's always a txn by this point (and btw we support `COPY FROM` inside an explicit txn).

I've added comments here and also to `copyMachine.run()` hinting to how the planner is going to be used and that attention should be paid to the txn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408)*

**Comment by mjibson** [comment]
Review status: 0 of 32 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1776 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2ctN0bdQeoBVuEnmJC:-L2gQKl0zXHkdKro3lCS:b9i798z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/executor.go#L1776)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

The executor no longer sees the  `INSERTs`; their planning and execution is completely encapsulated by the `copyMachine`. This code only runs once for the whole copy protocol and sets up the planner for the use of the machine. So there's one timestamp: the timestamp of the transaction in which the `COPY FROM` is executed. Whether that txn is explicit or implicit doesn't matter here - there's always a txn by this point (and btw we support `COPY FROM` inside an explicit txn).

I've added comments here and also to `copyMachine.run()` hinting to how the planner is going to be used and that attention should be paid to the txn.
</blockquote></details>

I'm not sure we are talking about the same thing, and I think it's really important to get this part correct, so I'm going to try restating my question. Also keep in mind that I'm not closely following the executor work you are doing, so there may be many assumptions you have of which I'm unaware.

Users are able to use COPY FROM either inside an explicit txn or not. If they use it inside an explicit txn, then the total number of INSERTs must fit within whatever our intent limits are (which are either by number, size, or something else that just changed in a recent PR I saw, doesn't matter). If more data was sent over COPY than this limit supports, the COPY as a whole fails. Furthermore, all data's mvcc time is inserted at whatever time the txn was pinned to, regardless of when the batched INSERT was executed. This mode effectively caps the maximum amount of data that can be inserted using the COPY protocol. My question is: does the code in this PR do exactly what I describe above?

Now take the case where a user runs a COPY outside of an explicit transaction. Every time there's enough data in the batch, a new INSERT is executed. The mvcc time of the data should be set to whenever that particular INSERT was executed. Each INSERT batch should be in its own DB.txn with a unique mvcc timestamp. Because of this, there's effectively no limit on the size of the COPY since batches will be inserted anytime they reach some reasonable size that is well below our internal intent limits. My question is: does the code in this PR do exactly this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408)*

**Comment by andreimatei** [comment]
Review status: 0 of 32 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1776 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L2ctN0bdQeoBVuEnmJC:-L2gTxkUDZDjolSqZqR-:blxpjeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3cc24ee848f6576e1c69a2d09718fccbab8b92/pkg/sql/executor.go#L1776)):*
> This mode effectively caps the maximum amount of data that can be inserted using the COPY protocol. My question is: does the code in this PR do exactly what I describe above?

Yes.

> Now take the case where a user runs a COPY outside of an explicit transaction. 

Hmmm, I see what you're saying. I have changed this behavior for implicit txns indeed. I haven't thought about it before. Let me try to split the transactions again like they were.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408)*

**Comment by andreimatei** [comment]
I've made the `copyMachine` split its execution into multiple txns if executing outside of an explicit sql txn. PTAL.

r3 is #21441

---

Review status: 0 of 35 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-:-L2vi0wiWH6sKhVJIK6v:bfrvp3o)*

**Comment by mjibson** [comment]
Review status: 0 of 35 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/copy.go, line 86 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L3-QtG_kZrxyeKrrJOp:-L3-QtG_kZrxyeKrrJOq:bkasyr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a728875276f6147e2fdfd550e39b22a19c201de7/pkg/sql/copy.go#L86)):*
> ```Go
> 	}
> 
> 	cleanup := c.preparePlanner(ctx)
> ```

I don't understand why this needs to be run here in newCopyMachine.

---

*[pkg/sql/copy.go, line 147 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L3-QyM_nGdPtqEuUwtU:-L3-QyMartf-S6FYnjKi:b-b7l9hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a728875276f6147e2fdfd550e39b22a19c201de7/pkg/sql/copy.go#L147)):*
> ```Go
> 
> 		cont, err := func() (cont bool, retErr error) {
> 			cleanup := c.preparePlanner(ctx)
> ```

I don't understand why this needs to be run on every invocation of this loop. I thought we just wanted one txn per insert batch, not per copy message. Or maybe it is doing that and I don't see it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408)*

**Comment by andreimatei** [comment]
Review status: 0 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/copy.go, line 86 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L3-QtG_kZrxyeKrrJOp:-L3-nLzfGERUzmGezNke:badkjsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a728875276f6147e2fdfd550e39b22a19c201de7/pkg/sql/copy.go#L86)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I don't understand why this needs to be run here in newCopyMachine.
</blockquote></details>

well because the planner is used below for the `makeEditNode()` call. I guess that's just a convenience for getting a table desc and checking privileges. We could unravel the sweater a bit probably and do it without a planner, but we'd still need a txn to get the table descriptor. We could probably work on that sweater too because a txn is not really needed from the caller except for some special cases which I think don't apply, but all our interfaces suck. I'll leave it alone...

---

*[pkg/sql/copy.go, line 147 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L3-QyM_nGdPtqEuUwtU:-L309SlybB6RkU5xSR9a:blw84kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a728875276f6147e2fdfd550e39b22a19c201de7/pkg/sql/copy.go#L147)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I don't understand why this needs to be run on every invocation of this loop. I thought we just wanted one txn per insert batch, not per copy message. Or maybe it is doing that and I don't see it?
</blockquote></details>

The reason was that we needed an eval context to parse some strings, and so I used a pretty big hammer. Please see now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 32 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/copy.go, line 86 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-L3-QtG_kZrxyeKrrJOp:-L36buDPw_Q9tlR7wwjS:b-x584kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a728875276f6147e2fdfd550e39b22a19c201de7/pkg/sql/copy.go#L86)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well because the planner is used below for the `makeEditNode()` call. I guess that's just a convenience for getting a table desc and checking privileges. We could unravel the sweater a bit probably and do it without a planner, but we'd still need a txn to get the table descriptor. We could probably work on that sweater too because a txn is not really needed from the caller except for some special cases which I think don't apply, but all our interfaces suck. I'll leave it alone...
</blockquote></details>

Ok. Fine with me to leave as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21408#-:-L36ceOc8o-r3NJq4pmJ:bnfp4nl)*

**Pull request merged**
