### PR TITLE
roachtest: better triage schema workload flakes in backup-restore tests

### PR DESCRIPTION
**Pull request by msbutler**
Informs #136709

Release note: none

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
Does this only affect the owner of newly filed issues? If we already have an issue with the name (of the test) that is assigned to us or them, and then we get a new failure that is/ism't the schema change workload such that it differs from the previous one, the issue filer is just going to comment on the original issue, right?

**Comment by dt** [comment]
Perhaps a follow-up improvement would be to augment the reported name of the failure to include " (workload)" or something in the title of failures of the workload

**Comment by msbutler** [comment]
> Does this only affect the owner of newly filed issues? I
yes

>  If we already have an issue with the name (of the test) that is assigned to us or them, and then we get a new failure that is/ism't the schema change workload such that it differs from the previous one, the issue filer is just going to comment on the original issue, right?
yeah, i trust foundations folks to do so.

**Comment by msbutler** [comment]
TFTR!

bors r=dt

**Pull request merged**
