### PR TITLE
kvserver: remove redundant "too little" log line

### PR DESCRIPTION
**Pull request by kvoli**
Some small improvements and fixes for allocator/store rebalancer logging.

Epic: none
Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Comment by kvoli** [comment]
Rebased on latest master.

**Comment by kvoli** [comment]
> Rebased on latest master.

Again.

**Comment by kvoli** [comment]
bors r=tbg

**Comment by kvoli** [comment]
bor r+

**Review by knz — APPROVED** [review]

**Pull request merged**
