### PR TITLE
sql: fix fingerprinting for tables with BYTES and non-BYTES cols

### PR DESCRIPTION
**Pull request by danhhz**
The placeholders used to refer to the columns were all being typed as
strings instead of the type of the column. I don't really understand
why. The tests worked before because we also have a variadic string
version of fnv64.

We didn't really need the placeholders anyway, this commit uses our
escaping code to escape the names of the columns and print them into the
query directly.

### CODE REVIEW

**Comment by dt** [comment]
:lgtm:

*kinda* gross but if it actually works, yay.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967#-:-KkJVqcrMDc8_UoF6a-y:b-dip1wb)*

**Comment by benesch** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_fingerprints.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967#-KkL2nngVKb9Vk5ek9g2:-KkL2nnhHcjiVDc3_3m9:b2uvpep) ([raw file](https://github.com/cockroachdb/cockroach/blob/03b78cda35188657b23c3847c93ee8dace371d3f/pkg/sql/show_fingerprints.go#L132)):*
> ```Go
> 		switch col.Type.Kind {
> 		case sqlbase.ColumnType_BYTES:
> 			cols = append(cols, fmt.Sprintf("%s:::bytes", col.Name))
> ```

Is this `:::bytes` annotation necessary?

---

*[pkg/sql/show_fingerprints.go, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967#-KkL1xTYRJj8EufFHGl1:-KkL1xTYRJj8EufFHGl2:bjuc6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7423db2fd90d308b24017fb373d1274ec716393/pkg/sql/show_fingerprints.go#L136)):*
> ```Go
> 		switch col.Type.Kind {
> 		case sqlbase.ColumnType_BYTES:
> 			placeholders = append(placeholders, fmt.Sprintf("$%d", placeholderIdx))
> ```

Wait, did this actually work?! Unless we differ radically from other SQL implementations, you can't supply the name of a column via a placeholder... so isn't the current implementation hashing the literal column _names_ for every row, instead of their values?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_fingerprints.go, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967#-KkL1xTYRJj8EufFHGl1:-KkL3H8kFfGdciHgh3OE:b-9378s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7423db2fd90d308b24017fb373d1274ec716393/pkg/sql/show_fingerprints.go#L136)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Wait, did this actually work?! Unless we differ radically from other SQL implementations, you can't supply the name of a column via a placeholder... so isn't the current implementation hashing the literal column _names_ for every row, instead of their values?
</blockquote></details>

(Which, of course, would explain why they're always strings.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_fingerprints.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967#-KkL2nngVKb9Vk5ek9g2:-KkLHythJZq9A-G8I021:b-1jr8do) ([raw file](https://github.com/cockroachdb/cockroach/blob/03b78cda35188657b23c3847c93ee8dace371d3f/pkg/sql/show_fingerprints.go#L132)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Is this `:::bytes` annotation necessary?
</blockquote></details>

I like it, since it asserts our assumption that it is bytes, which would e.g. catch using the column name as a string instead of a column name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_fingerprints.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967#-KkL2nngVKb9Vk5ek9g2:-KkLIkvq1eTQ1BNtVxmI:b8resx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/03b78cda35188657b23c3847c93ee8dace371d3f/pkg/sql/show_fingerprints.go#L132)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I like it, since it asserts our assumption that it is bytes, which would e.g. catch using the column name as a string instead of a column name.
</blockquote></details>

I do too. Sorry, I should have been more clear. My question was meant as  "this annotation is here to fail loudly if things go wrong and not because of some godawful type system bug, right?"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967)*

**Comment by danhhz** [comment]
Argh. Github bugged and I missed every comment after the LGTM (until immediately after I clicked merge and it refreshed, of course)

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_fingerprints.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967#-KkL2nngVKb9Vk5ek9g2:-KkLnPuDbrGapopzJeWn:bfdjab8) ([raw file](https://github.com/cockroachdb/cockroach/blob/03b78cda35188657b23c3847c93ee8dace371d3f/pkg/sql/show_fingerprints.go#L132)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I do too. Sorry, I should have been more clear. My question was meant as  "this annotation is here to fail loudly if things go wrong and not because of some godawful type system bug, right?"
</blockquote></details>

Correct, just paranoia

---

*[pkg/sql/show_fingerprints.go, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967#-KkL1xTYRJj8EufFHGl1:-KkLniSgqZt4Gv5lBA_P:b3fxz9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7423db2fd90d308b24017fb373d1274ec716393/pkg/sql/show_fingerprints.go#L136)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

(Which, of course, would explain why they're always strings.)
</blockquote></details>

Good point. I'll followup with a test to check that we're not just hashing the column names

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15967#-:-KkLnEXMbA_npTkRE14v:b-m9nu8p)*

**Pull request merged**
