### PR TITLE
sql: move name resolution in tree to operate on UnresolvedObjectNames

### PR DESCRIPTION
**Pull request by rohany**
This commit has two effects:
* generalize the name resolution logic on TableNames for reuse
  in type resolution cases
* Continue work of #34240 and stop using TableNames before we
  know what the schema and database are.

It also moves UnresolvedObjectName into the `object_name.go` file.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
:tada: Love it! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48001#-:-M5gQpTkAmP0WOXteyFN:bliq4v5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rohany)

___
*[pkg/sql/resolver.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48001#-M5gPX5JAxCpUfMbJWFh:-M5gPX5JAxCpUfMbJWFi:b3lecwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecf5825191b8fd75d629d82f82b09053ce5f0bee/pkg/sql/resolver.go#L136)):*
> ```Go
> 	requiredType ResolveRequiredType,
> ) (res tree.NameResolutionResult, err error) {
> 	un := tn.ToUnresolvedObjectName()
> ```

[nit] maybe add a TODO here and in similar places that mention `#34240` and that this function should take an *UnresolvedObjectName
___
*[pkg/sql/sem/tree/name_resolution.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48001#-M5gQk3o71DuJgRhIBaW:-M5gQk3o71DuJgRhIBaX:b-6w89h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecf5825191b8fd75d629d82f82b09053ce5f0bee/pkg/sql/sem/tree/name_resolution.go#L268)):*
> ```Go
> }
> 
> // ResolveExisting performs name resolution for a table name when
> ```

[nit] object name
___
*[pkg/sql/sem/tree/name_resolution.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48001#-M5gOrcL8dg8yl1Yd9yO:-M5gOrcL8dg8yl1Yd9yP:b-702vdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecf5825191b8fd75d629d82f82b09053ce5f0bee/pkg/sql/sem/tree/name_resolution.go#L269)):*
> ```Go
> 
> // ResolveExisting performs name resolution for a table name when
> // the target object is expected to exist already. It does not
> ```

This is great, nice solution to return the ObjectNamePrefix. The mutation of TableName was something subtle before, now it's explicit at the callsites.
___
*[pkg/sql/sem/tree/name_resolution.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48001#-M5gPvmqCklXimf2vB5t:-M5gPvmqCklXimf2vB5u:b-lvhjnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecf5825191b8fd75d629d82f82b09053ce5f0bee/pkg/sql/sem/tree/name_resolution.go#L274)):*
> ```Go
> // name was "a.b" and the name was resolved to "a.public.b", the
> // prefix "a.public" is returned.
> func (u *UnresolvedObjectName) ResolveExisting(
> ```

[nit] I always found it strange that these are methods on the name. You'd expect this to be a method on a resolver object not on something which is just part of the the input to the resolution algorithm. What do you think about making them freestanding functions and passing the name as an argument?
___
*[pkg/sql/sem/tree/name_resolution.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48001#-M5gQmq-CgUbZ8xtvHT7:-M5gQmq-CgUbZ8xtvHT8:b-6w89h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecf5825191b8fd75d629d82f82b09053ce5f0bee/pkg/sql/sem/tree/name_resolution.go#L344)):*
> ```Go
> }
> 
> // ResolveTarget performs name resolution for a table name when
> ```

[nit] object name

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48001)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/sem/tree/name_resolution.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48001#-M5gOrcL8dg8yl1Yd9yO:-M5gvYk0-fAWUUq8WpBp:bd5l6mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecf5825191b8fd75d629d82f82b09053ce5f0bee/pkg/sql/sem/tree/name_resolution.go#L269)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is great, nice solution to return the ObjectNamePrefix. The mutation of TableName was something subtle before, now it's explicit at the callsites.
</blockquote></details>

thanks!
___
*[pkg/sql/sem/tree/name_resolution.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48001#-M5gPvmqCklXimf2vB5t:-M5gvZtTA8LfsN6vM-Sq:b-h1n3dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecf5825191b8fd75d629d82f82b09053ce5f0bee/pkg/sql/sem/tree/name_resolution.go#L274)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I always found it strange that these are methods on the name. You'd expect this to be a method on a resolver object not on something which is just part of the the input to the resolution algorithm. What do you think about making them freestanding functions and passing the name as an argument?
</blockquote></details>

that makes sense

**Comment by rohany** [comment]
bors r=raduberinde

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48001#-:-M5hI9K5-dRPOdC0kIuE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by rohany** [comment]
bors r=raduberinde

**Comment by rohany** [comment]
bors r=raduberinde

**Comment by rohany** [comment]
a flake i think?

bors r=raduberinde

**Pull request merged**
