### PR TITLE
[DNM] exportStorage backed by inter-node file sharing

### PR DESCRIPTION
**Pull request by dt**
(DNM: this is completely untested, I'm just getting a rough draft out so we have something concrete to discuss, and decide if we want to pursue this approach further)

Context: #17057 

The plumbing involved here makes me a little sad -- lots of added surface area in method sigs and some pretty widely used structs to support what is currently a pretty niche use-case. Of course, if we think that its a valuable feature long-term that might be worth it, but it seems worth making the decision explicitly (I pulled most of that plumbing into a standalone commit to make it easier to evaluate in insolation).

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/storageccl/export_storage.go, line 154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17255#-Kq4E6WQhVsAVhEhV6yz:-Kq4E6WQhVsAVhEhV6z-:bynul2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b187d7034f99443b1b3e5fdbb05ed9735882a1/pkg/ccl/storageccl/export_storage.go#L154)):*
> ```Go
> 
> 	// WriteMetadataFile should write the content to requested name.
> 	WriteMetadataFile(ctx context.Context, basename string, content []byte) error
> ```

I don't understand how this will help us solve the problem of where to put the BACKUP file using the blobstorage stuff. It seems really weird that in general an export store can change a filename, or you can tell it not to change the filename instead. Why can't we have a single WriteFile API call, and callers can choose to ignore the first return value?

---

*[pkg/ccl/storageccl/export_storage.go, line 104 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17255#-Kq4K9cWhHLupdBR99WJ:-Kq4K9cWhHLupdBR99WK:b-5zwtxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b1be9829c2ce42b729a2cff378588f56f66d60/pkg/ccl/storageccl/export_storage.go#L104)):*
> ```Go
> 		conf.Provider = roachpb.ExportStorageProvider_BlobSharing
> 		conf.Blob.Prefix = uri.Path
> 		if i, err := strconv.Atoi(uri.Query().Get(MetadataNode)); err != nil {
> ```

This is the thing I think will be hard for users to get correct. How do they find a valid node ID? Is there a way for us to provide a sane default? If there's an easy way for users to get this then I think this will work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17255)*

**Comment by petermattis** [comment]
I think this approach looks reasonable except there is the massive irritation of having to plumb `blob.Service` everywhere. I think this could be avoided with a global registry. This is the approach that Google uses internally for accessing various distributed filesystems. When you wanted to write `gfs://foo/bar` it would dispatch to the `gfs` client which would look up the cluster `foo` and access the file `/bar`. I only skimmed the PR, so it is possible I'm missing something that prohibits this. 

As to the long-term maintenance this imposes, perhaps we should name this `experimental-blobsharing` or something like that.

**Comment by tschottdorf** [comment]
> I think this approach looks reasonable except there is the massive irritation of having to plumb blob.Service everywhere.

Having had to deal with the `settings` system recently which is essentially a zoo of singletons, I feel strongly that every singleton is technical debt. These things limit testing and don't buy a lot of velocity. In other words, I find convenience singletons a massive irritation. You pay the price later.

**Comment by petermattis** [comment]
> Having had to deal with the settings system recently which is essentially a zoo of singletons, I feel strongly that every singleton is technical debt. These things limit testing and don't buy a lot of velocity. In other words, I find convenience singletons a massive irritation. You pay the price later.

My feelings aren't nearly so strong and I'd prefer to discuss specifics. `makeAzureStorage` takes a `ExportStorage_Azure` and makes a client. Why can't the same be done for `blobsharing`? There shouldn't be a need to plumb `*blob.Service` as a parameter through so many layers. This can be accomplished by a singleton, a cache of connections behind the scene or opening a new connection on every request.

**Comment by tschottdorf** [comment]
I agree that a singleton is acceptable for an entity that contains no relevant shared state (i.e., just a connection cache and perhaps credentials which don't get in the way of tests) which is probably what the the azure storage is like.

But the blob service isn't just something to talk to an external system - it's it's own system, much like a much simpler cockroach server, in that it contains the nodeid, a storage directory, and potentially more in the future. As such, and unless I'm missing something major here, I'd *really* not want there to be a singleton. Perhaps I am missing something because you don't seem to share that concern.

**Comment by dt** [comment]
You can't quite just create a new client on the spot: `blob.Service` wraps local path on disk and a nodeID, the two things needed to store a file, plus needs a gossip-backed grpc-dialer, for fetching files -- those are basically what's being plumbed from pkg/server/server.go, where we set them up, to the exportStorage implementation, where we use them.

**Comment by dt** [comment]
I kinda share @tschottdorf's concern about singletons: I slightly regret adding the `settings` singleton after seeing some of the difficulties encountered in testing.

Don't know if it makes sense, but we could go with a non-singleton registry of fs impls, plumbing an `IORegistry` in the places I currently have a `blob.Service`? same plumbing involved, just different name, but I guess it'd be easier to just add the next one? That said, usual reservations about trying to build the general case until the second use shows what's actually general apply.

**Comment by petermattis** [comment]
Using node ids in the blob URLs ties those URLs to a specific cluster. Is there a reason the URLs don't contain a hostname:port instead?

**Comment by dt** [comment]
nope, no strong reason -- I guess I was thinking if a node moved (e.g. ephemeral instance hostnames) you'd still be able to find it by ID, but this whole thing is already so intolerant of any nodes going away that that is probably not worth much.

**Comment by benesch** [comment]
So IIUC if the URL contains the hostname/port, we can avoid all the `blobs.Storage` plumbing?

**Comment by dt** [comment]
@benesch no, it would let you ditch gossip, but still need to plumb rpcContext (to talk gRPC to said nodes), and the local storage path, for saving your local files. You could ditch the grpc part, and instead open a new, plain http port, but that is icky: if the operator was expecting nodes to be doing TLS (part of what that plumbing was enabling), you've quietly downgraded to something else? yuck.

**Comment by benesch** [comment]
Ah, I see. FWIW this plumbing seems entirely reasonable to me.

**Comment by dt** [comment]
👍 
that said, I think the plumbing is only part of what I believe @danhhz (and I, to some lesser extent) are concerned about -- the number of touch points just served to highlight and bring to front of mind questions of scope, surface area, and reasonable payoff.

I think I *might* have another possible solution for the short-term customer need that motivated this proposed change, which I just whipped up in #17291

**Pull request closed without merging**
