### PR TITLE
sql: add missing `MakeDBool` to decodeUntaggedDatum

### PR DESCRIPTION
**Pull request by petermattis**
Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
By my bisect https://github.com/cockroachdb/cockroach/pull/21253 is somehow to blame? o_O At least, applying the revert of a59814e09f07b554448451c15fcbd5534bfb9f15 to the current tip of master makes the problem go away.

I don't understand what's going on here at all (i.e., how did I get a green build before?).

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 952 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21270#-L277Nni2xw0Xf8GvHnT:-L277Nni2xw0Xf8GvHnU:bkl8fxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d56364cecf181f2c625b21e5efc37cf783aeca66/pkg/sql/logictest/testdata/logic_test/aggregate#L952)):*
> ```
> false true
> 
> # TODO(radu): this used to be `WHERE b` but that doesn't currently
> ```

At the very least, link to a bug here so there's some hope of deleting the note in the future.
Of course, this PR seems bizarre :) This test doesn't seem sufficiently unrelated to the bug to warrant your innocent bystander treatment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21270)*

**Comment by RaduBerinde** [comment]
LGTM

**Comment by petermattis** [comment]
> I don't understand what's going on here at all (i.e., how did I get a green build before?).

That's interesting. I don't know what is going on either.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 952 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21270#-L277Nni2xw0Xf8GvHnT:-L277zdbAqrIBVRc3che:bvtzusc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d56364cecf181f2c625b21e5efc37cf783aeca66/pkg/sql/logictest/testdata/logic_test/aggregate#L952)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

At the very least, link to a bug here so there's some hope of deleting the note in the future.
Of course, this PR seems bizarre :) This test doesn't seem sufficiently unrelated to the bug to warrant your innocent bystander treatment.
</blockquote></details>

I filed a bug https://github.com/cockroachdb/cockroach/issues/21271. Should we really wait for another round of CI?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21270#-:-L2786-rLNPcS1VjLV-x:bpygirn)*

**Review by benesch — APPROVED** [review]
Thanks!

**Comment by RaduBerinde** [comment]
LGTM, thanks for figuring out the fix!

**Pull request merged**
