### PR TITLE
codeowners: mark `pkg/sql/sqlstats` as owned by SQL O11y

### PR DESCRIPTION
**Pull request by yuzefovich**
Informs: #94880.

Epic: None

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94928#-:-NLMEQws1hCML0KpL95w:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
bors r+
bors single on

**Pull request merged**
