### PR TITLE
 sql: add stmt error code to execution insights tables

### PR DESCRIPTION
**Pull request by gtr**
Part of: #87785.

Previously, the insights subsystem did not keep track of `error code` for
failed executions and only contained a `FailedExecution` value for the
problem field. This commit adds the `error_code` column to the
`crdb_internal.{cluster/node}_execution_insights` virtual tables. This
commit also bubbles up that error code at the transaction level for
writing into the `crdb_internal.{cluster/node}_txn_execution_insights`
virtual table.

Release note (sql change): Adds `error_code` column to the
`crdb_internal.{cluster/node}_execution_insights` virtual tables, which
contains the error code for a failed execution. Adds `last_error_code`
column to the `crdb_internal.{cluster/node}_txn_execution_insights`
virtual tables, which is the error code of the last failed statement in
that transaction.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
can you update the file pkg/sql/sqlstats/insights/integration/insights_test.go to add the new column on the test `TestInsightsIntegration` and also create a new one testing the cases where you have errors (when the statement is slow so it would also hit that detector, but one that would still be fast and only hit the failed detector)

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96676#-:-NNs2SRhC6fI91IMqijf:buraips)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96676#-NNs09995d03lsBgAWDi):*
these should be 2 different PRs, since they're not related
also, looks like the changes here are  fixing 94381 and not just "part of"

**Review by gtr — COMMENTED** [review]
Sure thing! I put the slow and failure detectors tests in `pkg/sql/sqlstats/insights/detector_test.go`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96676#-:-NNxLpQU7r3L_D10NPJm:b-gkri2e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96676#-NNs09995d03lsBgAWDi):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

these should be 2 different PRs, since they're not related
also, looks like the changes here are  fixing 94381 and not just "part of"
</blockquote></details>

Done.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96676#-NNs09995d03lsBgAWDi):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You tagged the wrong issue here.
This PR is dealing with 87785, and should be Part Of, since you haven't finish and still need to add to the UI.
The other PR which I imagine you're creating with the updates on the detector is the one where you tag as Fixes 94381

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96676#-NNxaDhSCUnvlL098wJu:-NNxaDhSCUnvlL098wJv:b-bj4837) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c783f3da17dde46d169072b970b1554ff0e2cc0/pkg/sql/sqlstats/insights/integration/insights_test.go#L157)):*
> ```Go
> 		var cpuSQLNanos int64
> 		var errorCode string
> 		err = row.Scan(&query, &startInsights, &endInsights, &implicitTxn, &cpuSQLNanos, &errorCode)
> ```

you need to add some test here with a failed execution and confirm that the error code is showing up as expected.
You should check in both statement and transaction insights

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96676#-NNs09995d03lsBgAWDi):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

You tagged the wrong issue here.
This PR is dealing with 87785, and should be Part Of, since you haven't finish and still need to add to the UI.
The other PR which I imagine you're creating with the updates on the detector is the one where you tag as Fixes 94381
</blockquote></details>

Opened two PRs for the two issues:
- #97039 to detect failed executions
- #97046 to add error code for failed executions in the execution insights tables
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96676#-NNxaDhSCUnvlL098wJu:-NOA_dQj3XEYAoUGkOrD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c783f3da17dde46d169072b970b1554ff0e2cc0/pkg/sql/sqlstats/insights/integration/insights_test.go#L157)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you need to add some test here with a failed execution and confirm that the error code is showing up as expected.
You should check in both statement and transaction insights
</blockquote></details>

Done.

**Pull request closed without merging**
