### PR TITLE
kvcoord: reap DistSender circuit breaker probes during GC

### LINKED ISSUE #121030: kvcoord: fix DistSender circuit breaker tripped metrics leak
Currently, if a tripped circuit breaker is GCed, it will continue to be considered tripped in the DistSender metrics until the node restarts. Fixing this requires synchronization with the probe, since it is normally responsible for increasing/decreasing the metric as the circuit breaker trips/untrips. The probe likely isn't running when the circuit breaker is GCed, but it may be if a probe is concurrently launching while GC is running, or the threshold/interval has been configured higher than the GC threshold. If there is a race, it can lead to persistent gauge leaks.

Jira issue: CRDB-37035

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvcoord: split out DistSender circuit breaker `probeLoop`**

This separates the goroutine management from the probe loop logic.

**kvcoord: reap DistSender circuit breaker probes during GC**

This prevents probe leaks in case they are long-running, and will allow removing GCed circuit breakers from the tripped metrics.

**kvcoord: remove GCed DistSender circuit breakers from tripped metrics**

Otherwise, these will register as tripped forever.

Resolves #121030.
Epic: none
Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I'm not thrilled about the amount of synchronization needed to reap probes, but it gets the job done and isn't too bad I suppose. Open to suggestions on how to simplify.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120946)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @erikgrinaker)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 671 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120946#-NtqIVO8AXbHtaBIDVTl:-NtqIVO95iS0JJr2UOpl:b-mlhltv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f94e6c25ebec5cf8e7591f71bd9920f4ae7bafcd/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L671)):*
> ```Go
> 			err := r.sendProbe(ctx, transport)
> 
> 			// If the context failed, we're shutting down. Just exit the probe without
> ```

"If the context with no timeout failed,"
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 781 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120946#-NtqIIsM2FCUrxWw-4oo:-NtqIIsM2FCUrxWw-4op:b-q9hyb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f94e6c25ebec5cf8e7591f71bd9920f4ae7bafcd/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L781)):*
> ```Go
> 		// either the remote node or the local node has been decommissioned. We
> 		// rely on RPC circuit breakers to fail fast for these, so there's no point
> 		// in us probing individual replicas. Stop probing.
> ```

"Stop probing and untrip the breaker if it was tripped."
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 282 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/120946#-NtqMlqD8AZU_g8J4TES:-NtqMlqD8AZU_g8J4TET:bh4983q) ([raw file](https://github.com/cockroachdb/cockroach/blob/edee57d265c9fb526eb4f77b6566a9bcf661bd77/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L282)):*
> ```Go
> 					// replicas. But it can happen if we race with a probe launch, or if
> 					// probes run longer than the GC threshold. The map removal above will
> 					// prevent new probes being launched (checked by launchProbe).
> ```

"being launched for this same ReplicaCircuitBreaker"
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 353 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/120946#-NtqMi8yARiGVdT5D8hy:-NtqMi8yARiGVdT5D8hz:b-ikw2s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/edee57d265c9fb526eb4f77b6566a9bcf661bd77/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L353)):*
> ```Go
> 		cancelFns map[*kvpb.BatchRequest]context.CancelCauseFunc
> 
> 		// reapProbe, if non-nil, can be called to synchronously cancel a running
> ```

Is it important that this cancellation is synchronous? I'd be concerned that this allows a circuit breaker that's either slow to respond to context cancellation, or that's broken entirely, to stall the gc loop. This change would be more obviously correct if the `reapProbe` function was non-blocking. We could then also call it under lock in `ReplicaCircuitBreaker.reapProbe` and set `mu.reapProbe` to nil right after, to ensure it is only called once.

EDIT: I guess you want this to be synchronous so that you can perform the `cb.isTripped` check after without risk of racing with a probe or double accounting in the `ReplicasTripped` metric.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 868 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/120946#-NtqNWD_-xxWBTj2VvEL:-NtqNWD_-xxWBTj2VvEM:bvtq802) ([raw file](https://github.com/cockroachdb/cockroach/blob/edee57d265c9fb526eb4f77b6566a9bcf661bd77/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L868)):*
> ```Go
> }
> 
> // reapProbe synchronously reaps the currently running probe, if any.
> ```

Consider renaming to `maybeReapProbe` so that it's contract is clearer and it can't be confused wit the `reapProbe` field.

**Review by erikgrinaker — COMMENTED** [review]
Comments addressed.

Since there may still be some uncertainty about whether this is the best approach to solve this problem, I wrote up a GA blocker issue for it (https://github.com/cockroachdb/cockroach/issues/121030), so we don't have to rush this in before the branch cut. I also split out the semi-unrelated changes to separate PRs that we can merge before the branch cut: https://github.com/cockroachdb/cockroach/pull/121028# and https://github.com/cockroachdb/cockroach/pull/121029.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120946#-:-Ntqfa_bCGUQcvWezw2g:b-gmzwdo)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 353 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/120946#-NtqMi8yARiGVdT5D8hy:-NtqahUe7h_RUmMw8sK9:b-530qt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/edee57d265c9fb526eb4f77b6566a9bcf661bd77/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L353)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is it important that this cancellation is synchronous? I'd be concerned that this allows a circuit breaker that's either slow to respond to context cancellation, or that's broken entirely, to stall the gc loop. This change would be more obviously correct if the `reapProbe` function was non-blocking. We could then also call it under lock in `ReplicaCircuitBreaker.reapProbe` and set `mu.reapProbe` to nil right after, to ensure it is only called once.

EDIT: I guess you want this to be synchronous so that you can perform the `cb.isTripped` check after without risk of racing with a probe or double accounting in the `ReplicasTripped` metric.
</blockquote></details>

Yes, exactly -- the whole reason for this synchronization is to avoid GC and the probe racing to update the metric, so we need to know that the probe has shut down first (assuming one is even running, which it may or may not be).

**Comment by erikgrinaker** [comment]
Thought of a way to possibly simplify this. Let me submit a new take tomorrow.

**Comment by erikgrinaker** [comment]
See #121142 for a simpler alternative. I think I prefer it.

**Comment by erikgrinaker** [comment]
Closing in favor of #121142.

**Pull request closed without merging**
