### PR TITLE
Add Marcus to AUTHORS

### PR DESCRIPTION
**Pull request by mgartner**
Add myself to the AUTHORS file as part of onboarding.

Release justification: no code changes

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Comment by mgartner** [comment]
bors +r

**Comment by RaduBerinde** [comment]
Ok, apparently it was necessary to go to https://bors.crdb.io/repositories/56/settings and trigger a refresh of the list. Should work now, fingers crossed.

**Pull request merged**
