### PR TITLE
colexec: miscellaneous cleanup

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: clean up external distinct test a bit**

Release note: None

**colbuilder: enforce unique memory monitor names**

Our disk-spilling infrastructure (namely, `diskSpillerBase`) uses the
name of the limited memory monitor of its in-memory operator in order to
distinguish the "memory budget exceeded" errors between the ones it
needs to catch and the ones it needs to propagate further. In
particular, previously it was possible that the in-memory chains within
two disk-backed sorters created for the external distinct (one in the
fallback strategy and another when the output ordering is needed, on top
of the external distinct) would have the same memory monitor names. This
is now fixed by appending a unique suffix to all names and is enforced
via an invariants assertion in the test setup.

Note that even with the previous behavior no actual bug would occur
because the monitors with the same name were on "different levels of the
tree" and there was the correct catcher in-between. So this commit
simply restores the assumption that we had implicitly without fixing any
production bugs.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63371#-:-MXrVCBBEG1T4e1scIEH:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63371#-MXrU4Cf9cyTd0iiLZu2:-MXrU4Cg-XM7ExtqTbrD:b-dlo6f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbc3b2273ac43fc2ea2f65ffca86dc65aacdaf33/pkg/sql/colexec/colbuilder/execplan.go#L1537)):*
> ```Go
> 	ctx context.Context, flowCtx *execinfra.FlowCtx, name string,
> ) (*mon.BoundAccount, string) {
> 	monitorName := r.getMemMonitorName(name + "-limited")
> ```

nit: it's a bit confusing that the name (which appears to be the monitor name) is an argument, but a modified monitor name is also returned. Not sure if it'd necessarily be better, but you could change the `name string` argument here and in the function below to `opName string, pid execinfrapb.ProcessorID`, and pass both and a `suffix string` to a `getMemMonitorName(opName string, pid execinfrapb.ProcessorID, suffix string)`. (Not sure `opName` is the right term, maybe there's something better). This would eliminate some duplicat `fmt.Sprintf`'s I think.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63371)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63371#-MXrU4Cf9cyTd0iiLZu2:-MXrcwzn4K0rFHFJYm8I:bk0aulv) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbc3b2273ac43fc2ea2f65ffca86dc65aacdaf33/pkg/sql/colexec/colbuilder/execplan.go#L1537)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: it's a bit confusing that the name (which appears to be the monitor name) is an argument, but a modified monitor name is also returned. Not sure if it'd necessarily be better, but you could change the `name string` argument here and in the function below to `opName string, pid execinfrapb.ProcessorID`, and pass both and a `suffix string` to a `getMemMonitorName(opName string, pid execinfrapb.ProcessorID, suffix string)`. (Not sure `opName` is the right term, maybe there's something better). This would eliminate some duplicat `fmt.Sprintf`'s I think.
</blockquote></details>

I like this idea, done. Overall, this mechanism of monitor name matching is quite brittle, and the code is not very pretty, but at least it does the job :)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Review by michae2 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63371)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63371#-MXrU4Cf9cyTd0iiLZu2:-MXs6Me96cvTHN7K18_O:b-mr80s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbc3b2273ac43fc2ea2f65ffca86dc65aacdaf33/pkg/sql/colexec/colbuilder/execplan.go#L1537)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I like this idea, done. Overall, this mechanism of monitor name matching is quite brittle, and the code is not very pretty, but at least it does the job :)
</blockquote></details>

Nit: Now that you've changed it, I don't think you need the hyphen on "-limited" any more.

**Review by yuzefovich — COMMENTED** [review]
bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63371#-:-MXs96814XRfQN_upeei:b-ydi9aw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63371#-MXrU4Cf9cyTd0iiLZu2:-MXs9-3k6vUoeGdzVrox:b-bfgbzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbc3b2273ac43fc2ea2f65ffca86dc65aacdaf33/pkg/sql/colexec/colbuilder/execplan.go#L1537)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Nit: Now that you've changed it, I don't think you need the hyphen on "-limited" any more.
</blockquote></details>

Indeed, nice catch!

**Pull request merged**
