### PR TITLE
sql/logictest: when rewriting, emit sorted results

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27970#-:-LINTWc7CDzYte2jCE2c:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by RaduBerinde** [comment]
I'm not sure what was the motivation for this change, but it broke rewriting EXPLAIN statements:
```
EXPLAIN (VERBOSE) SELECT a.v FROM kv a, kv b GROUP BY a.v, a.w, a.s
]
----
render      ·           ·
│           render      0
v           └──         distinct
·           ·           │
distinct    on          v,
w,          s           └──
join        ·           ·
│           type        cross
├──         scan        ·
·           │           table
kv@primary  │           spans
ALL         └──         scan
·           ·           ·
table       kv@primary  ·
```

This is a huge problem for the `sql/opt/exec/execbuilder` tests.

**Comment by knz** [comment]
ouch I hadn't thought about EXPLAIN. That won't do of course.

**Comment by knz** [comment]
Following up in #28025. Not only this PR is responsible.

**Pull request merged**
