### PR TITLE
sqlstats: add idle_lat to node_statement_statistics

### PR DESCRIPTION
**Pull request by matthewtodd**
Part of #86667.

For parity with our existing statement-level work in #91098.

(No release note here since `node_statement_statistics` is not one of the ["Use in production" `crdb_internal` tables](https://www.cockroachlabs.com/docs/stable/crdb-internal.html#tables).)

Release note: None

### CODE REVIEW

**Review by xinhaoz — APPROVED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`pkg/sql/crdb_internal.go` line 1186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92281#-NHUu8h21cwYb8vFYQXL:-NHUu8h21cwYb8vFYQXM:b-54p2y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d64098aa1a0b02d18f808b8a38ed9d4664e03d/pkg/sql/crdb_internal.go#L1186)):*
> ```Go
>   rows_var            FLOAT NOT NULL,
>   idle_lat_avg        FLOAT NOT NULL,
>   idle_lat_var        FLOAT NOT NULL,
> ```

Just wondering, do we have any sort of precedence of adding new columns to the end, to preserve the order of columns in things like SELECT * ?

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/sql/crdb_internal.go` line 1186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92281#-NHUu8h21cwYb8vFYQXL:-NHUypY989fCxXzW5JAE:b-qicj3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d64098aa1a0b02d18f808b8a38ed9d4664e03d/pkg/sql/crdb_internal.go#L1186)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Just wondering, do we have any sort of precedence of adding new columns to the end, to preserve the order of columns in things like SELECT * ?
</blockquote></details>

Good question! I have no idea -- I'll ask. (And maybe it's okay here, since we're non-committal about the stability of this table?)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/sql/crdb_internal.go` line 1186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92281#-NHUu8h21cwYb8vFYQXL:-NHV2giICuJXSRkbrAbF:b-me9bgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d64098aa1a0b02d18f808b8a38ed9d4664e03d/pkg/sql/crdb_internal.go#L1186)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Good question! I have no idea -- I'll ask. (And maybe it's okay here, since we're non-committal about the stability of this table?)
</blockquote></details>

separately, just wondering: are these new columns also going to end up being flushed to `system.statement_statistics` and appear in the `crdb_internal.statement_statistics` view?

i think in the case of tables that are actually "internal only" adding columns in the middle is fine. but for the externally-used tables, they should be added at the end. so if these will be at the end of `crdb_internal.statement_statistics`, then maybe they should be at the end here too. up to you, i don't feel strongly

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @xinhaoz)

___
*[`pkg/sql/crdb_internal.go` line 1186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92281#-NHUu8h21cwYb8vFYQXL:-NHWRmiA1JolcdljD36b:b-aaiewk) ([raw file](https://github.com/cockroachdb/cockroach/blob/54d64098aa1a0b02d18f808b8a38ed9d4664e03d/pkg/sql/crdb_internal.go#L1186)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

separately, just wondering: are these new columns also going to end up being flushed to `system.statement_statistics` and appear in the `crdb_internal.statement_statistics` view?

i think in the case of tables that are actually "internal only" adding columns in the middle is fine. but for the externally-used tables, they should be added at the end. so if these will be at the end of `crdb_internal.statement_statistics`, then maybe they should be at the end here too. up to you, i don't feel strongly
</blockquote></details>

Thank you both. It turns out this is the only table with explicit columns for these values: `crdb_internal.statement_statistics` and `system.statement_statistics` put them into a json blob in their `statistics` columns instead, so we're all good!

**Pull request merged**
