### PR TITLE
rocksdb{,ccl}: collapse into parent

### PR DESCRIPTION
**Pull request by tamird**
@petermattis per our discussion we might want to go the other way, moving engine/rocksdb.go into engine/rocksdb/rocksdb.go.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13701)

### CODE REVIEW

**Comment by bdarnell** [comment]
For the record, we split the `engine` and `rocksdb` packages in #1608 because it sped up compilation of changes to files in `engine` (and at that time we were using the modern `c-rocksdb` compilation, not `pkg-config`). I don't know whether that's still a concern. 

+1 to moving `engine/rocksdb.go` to `engine/rocksdb/rocksdb.go` if that works, but if not I'm fine with merging in this direction too. 

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13701#-:-KdXtATjD8lHvtd4HwnR:bh9fpsk)*

**Comment by tamird** [comment]
Looking into collapsing things the other way, and there are some challenges. For instance, engine/rocksdb.go references `engine.MVCCKey`:
```
type SSTableInfo struct {
	Level int
	Size  int64
	Start MVCCKey
	End   MVCCKey
}
```
so that's going to be a pain to disentangle (i'm not even sure how).

**Comment by tamird** [comment]
Further FWIW
```
$ touch ./pkg/storage/engine/rocksdb.go && time go build ./pkg/storage/engine
...
real	0m2.395s
user	0m1.722s
sys	0m0.633s
```

**Comment by petermattis** [comment]
> Further FWIW

Didn't you just say you're using `ccache`? Try `touch *.cc`. On my laptop, building `storage/engine/rocksdb` takes 3.4s. Rebuilding both `storage/engine` and `storage/engine/rocksdb` take 3.8s. This is with the parallel cgo patch. 

Regardless, I made an aborted attempt to move `rocksdb.go` into `storage/engine/rocksdb`. I think it is doable, but a lot messier than moving in the other direction. Lots of tests and other stuff need to be fixed up and we'd have to export some currently private methods like `unsafe{Key,Value}`.

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: 0 of 37 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/storageccl/engineccl/rocksdb.go, line 19 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13701#-KdY2yFC2gItl2ox1Wfe:-KdY2yFC2gItl2ox1Wff:b-6fpl7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fee8722f7407aa644bc342f45f25e9dca363be6/pkg/ccl/storageccl/engineccl/rocksdb.go#L19)):*
> ```Go
> )
> 
> // #cgo CPPFLAGS: -I ../../../../vendor/github.com/cockroachdb/c-protobuf/internal/src
> ```

I've been dropping the space after `-I` as that is the style we use most consistently and it looks better for `go list -json`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13701#-:-KdY48ZacsfbXUCTtUWY:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 68 of 68 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13701#-:-KdZ6tVjbpFNL3ErTfig:bnfp4nl)*

**Comment by danhhz** [comment]
ccl stuff lgtm

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13701#-:-Kda9k5VrmRkslQw0bU4:bpfat2x)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/storageccl/engineccl/rocksdb.go, line 19 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13701#-KdY2yFC2gItl2ox1Wfe:-KdaMJohgbu9oABEqUxN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fee8722f7407aa644bc342f45f25e9dca363be6/pkg/ccl/storageccl/engineccl/rocksdb.go#L19)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I've been dropping the space after `-I` as that is the style we use most consistently and it looks better for `go list -json`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13701)*

**Pull request merged**
