### PR TITLE
sql: support parsing expression-based indexes

### PR DESCRIPTION
**Pull request by RaduBerinde**
I started doing some of the initial legwork for expression-based indexes.

Allow parsing of expression-based index elements. We still error out
if use is attempted, but we do so at a higher layer.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Cool :)

**Review by mgartner — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55231)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/create_index, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-MIyqk6P80a72BtEXo-H:-MIyqk6Q9_RW1TKatJHI:b-6y4rqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dc9364e659aacb7176a1be6fbcbdb707de3610/pkg/sql/logictest/testdata/logic_test/create_index#L33)):*
> ```
> 
> statement error pgcode 0A000 only simple columns are supported as index elements
> CREATE TABLE t2 (a INT PRIMARY KEY, b INT, INDEX ((a+b)))
> ```

Can you add tests for UNIQUE indexes, both for `CREATE INDEX` and `CREATE TABLE`?
___
*[pkg/sql/parser/parse_test.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-MIyqTRE7f_nB5M1rGE5:-MIyqTRFEfqxFEAX37OW:b-df6bc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dc9364e659aacb7176a1be6fbcbdb707de3610/pkg/sql/parser/parse_test.go#L120)):*
> ```Go
> 		{`CREATE INDEX ON a (lower(a), lower(b))`},
> 		{`CREATE INDEX ON a (a, lower(b))`},
> 		{`CREATE INDEX ON a (((lower(a) || ' ') || lower(b)))`},
> ```

[nit] add UNIQUE variants

[nit] add a test case for non-function, multiple expressions like, `CREATE INDEX ON a ((a + 1), (b + 2))`
___
*[pkg/sql/sem/tree/pretty.go, line 1603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-MIyr53_EGOByxF5WR-T:-MIyr53_EGOByxF5WR-U:bfxgwcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/310480213c17f78d9790523dced244a70594bac0/pkg/sql/sem/tree/pretty.go#L1603)):*
> ```Go
> }
> 
> func (node *IndexElem) doc(p *PrettyCfg) pretty.Doc {
> ```

It looks like all node `doc` functions are defined in this file. Is there a reason you're moving this and breaking the pattern?

**Review by mgartner — COMMENTED** [review]
Looks like Postgres supports inverted expression indexes. Not sure if we'll pursue that from the get-go, but might be nice to have some parsing test cases for those as well, since you've updated `index_elem` which is a building block for parsing inverted indexes too.

```
marcus=# create table t (a int, b int);
CREATE TABLE

marcus=# create index i3 on t using gin ((ARRAY[a, b]));
CREATE INDEX

marcus=# \d t
                 Table "public.t"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 a      | integer |           |          |
 b      | integer |           |          |
Indexes:
    "i3" gin ((ARRAY[a, b]))
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-:-MIyszeh3eHRSf0dSpJk:b-bm8tay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
TFTR! Added some tests for inverted indexes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-:-MIzLaaL1WP6e-fstqjG:b-te9hmd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/logictest/testdata/logic_test/create_index, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-MIyqk6P80a72BtEXo-H:-MIzKHtp93KLlQMtdFwd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dc9364e659aacb7176a1be6fbcbdb707de3610/pkg/sql/logictest/testdata/logic_test/create_index#L33)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add tests for UNIQUE indexes, both for `CREATE INDEX` and `CREATE TABLE`?
</blockquote></details>

Done.
___
*[pkg/sql/parser/parse_test.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-MIyqTRE7f_nB5M1rGE5:-MIzKcmx92eS2R56k9h6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dc9364e659aacb7176a1be6fbcbdb707de3610/pkg/sql/parser/parse_test.go#L120)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] add UNIQUE variants

[nit] add a test case for non-function, multiple expressions like, `CREATE INDEX ON a ((a + 1), (b + 2))`
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/pretty.go, line 1603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-MIyr53_EGOByxF5WR-T:-MIzKgjX-EpCcF46dikY:bf69h6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/310480213c17f78d9790523dced244a70594bac0/pkg/sql/sem/tree/pretty.go#L1603)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It looks like all node `doc` functions are defined in this file. Is there a reason you're moving this and breaking the pattern?
</blockquote></details>

It's a bad pattern, there was some agreement that we should keep the doc functions next to the corresponding Format.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-:-MIzbDwB0xOWxQw40LNn:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/sem/tree/pretty.go, line 1603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-MIyr53_EGOByxF5WR-T:-MIzbAuEA64AqfW5NWK1:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/310480213c17f78d9790523dced244a70594bac0/pkg/sql/sem/tree/pretty.go#L1603)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's a bad pattern, there was some agreement that we should keep the doc functions next to the corresponding Format.
</blockquote></details>

SGTM

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55231)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/sem/tree/create.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-MIzbSVR1EkVcEeSxiPv:-MIzbSVR1EkVcEeSxiPw:b4rtmsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c4e56e5ebaaf6c8b27626f360f63e17d1bd9cef/pkg/sql/sem/tree/create.go#L150)):*
> ```Go
> 
> func (node *IndexElemList) doc(p *PrettyCfg) pretty.Doc {
> 	if node == nil || len(*node) == 0 {
> ```

looks like your build failed because the linter wants this to be `l` so its consistent with the receiver name of the function above

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55231)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/sem/tree/create.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55231#-MIzbSVR1EkVcEeSxiPv:-MIzgWjx4ncKHVLh8B7x:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c4e56e5ebaaf6c8b27626f360f63e17d1bd9cef/pkg/sql/sem/tree/create.go#L150)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

looks like your build failed because the linter wants this to be `l` so its consistent with the receiver name of the function above
</blockquote></details>

Fixed.

**Review by mgartner — APPROVED** [review]

**Pull request merged**
