### PR TITLE
colexec: wrap most unsupported processor cores into the vectorized flow

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: wrap all unsupported processor cores into the vectorized flow**

This commit refactors the setup of the vectorized flow so that all
processor cores that do not have an equivalent columnar operator are
wrapped with a materializer and a columnarizer. It extracts all the
checks for whether the core is "supported" into a new function, and if
the core is not supported, it'll get wrapped. All such wrapped
processors are marked as "streaming" because they are not buffering
operators (although they could be buffering processors), and as
a result, such wrapped processors will be planned when vectorize is set
to 'auto'.

The only processor cores that are not wrapped are LocalPlanNode (because
wrapping it seems to break some assumptions, and a flow with such
processor probably will not benefit from vectorization anyway) and
MetadataTest{Sender,Receiver} (because the vectorized flow propagates
the metadata in an unexpected way to these processors).

Release note: None

**rowexec, execinfra: move all processors into rowexec**

Previously IndexJoiner and JoinReader lived in execinfra because the
vectorized flow (colflow package) needed to instantiate them. However,
now that we're wrapping almost all unsupported processors into the
vectorized flow, we are instantiating them using NewProcessor method,
and all processors can be unexported. This commit also moves the related
things from execinfra to rowexec and unexports a bunch of stuff as well
(previously, it was exported because processors in rowexec and execinfra
needed access, but now everything is in rowexec).

Release note: None

**rowexec: implement execinfra.OpNode interface by some processors**

Now that the processors can be wrapped into the vectorized flow, for
them to show up properly during EXPLAIN (VEC), they need to implement
execinfra.OpNode interface. This commit adds that.

Release note: None

**sql: move dependency on rowexec from colexec to colflow**

Previously, there was a dependency on sql/rowexec package from
sql/colexec package because we wrapping processors that do not have an
equivalent columnar operator into the vectorized flow. This commit moves
that dependency into sql/colflow package. It is done by abstracting away
a function-constructor that lives in sql/execinfra.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, 32 of 32 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42873)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKaYHnBC_t0jPIZO99:-LvKaYHnBC_t0jPIZO9A:b-wvvgzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L24)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/sql/execinfra"
> 	"github.com/cockroachdb/cockroach/pkg/sql/execinfrapb"
> 	"github.com/cockroachdb/cockroach/pkg/sql/rowexec"
> ```

This dependency makes me slightly uncomfortable. Is there a way to avoid it?
___
*[pkg/sql/colexec/execplan.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKaHEd8hZy1XBvpzSH:-LvKaHEd8hZy1XBvpzSI:b-5c96sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L244)):*
> ```Go
> // processor described by spec. Note that it doesn't perform any other checks
> // (like validity of the number of inputs).
> func isSupported(spec *execinfrapb.ProcessorSpec) (bool, error) {
> ```

I like this, does this mean we can change our supported check (the one we have before sending out the flows for vectorization) to be more lightweight? Or would it not have much benefit given the interface you added to make constructions noops?
___
*[pkg/sql/colexec/execplan.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKca2kDfUBtjdpi7sr:-LvKca2kDfUBtjdpi7ss:b-8g5otm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L413)):*
> ```Go
> 		}
> 
> 		c, err = wrapRowSources(
> ```

Should we have a heuristic that prohibits more than `n` wraps? I wonder what the threshold is where we'd just benefit from running the whole flow in the row execution engine.
___
*[pkg/sql/colexec/execplan.go, line 452 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKcCCED9kkZVlRBMLO:-LvKcCCED9kkZVlRBMLP:b6ijrzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L452)):*
> ```Go
> 
> 		// We say that the wrapped processor is "streaming" because it is not a
> 		// buffering operator (even if it is a buffering processor).
> ```

Could you just mention that memory used will still be accounted for?
___
*[pkg/sql/execinfra/stats.proto, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKdaaK5-qIDx76STck:-LvKdaaK5-qIDx76STcl:bcidw1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea9c6a53b149912324c2489e5b7dfd8029e6da1/pkg/sql/execinfra/stats.proto#L19)):*
> ```protobuf
> 
> // InputStats represents the stats collected from an input.
> message InputStats {
> ```

Will the fact that these protos moved affect displaying these stats?
___
*[pkg/sql/logictest/testdata/logic_test/tpch_vec, line 781 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKeAS49Bhv5Qn3z6M3:-LvKeAS49Bhv5Qn3z6M4:b-txab26) ([raw file](https://github.com/cockroachdb/cockroach/blob/bed91ca89bf5780a9c77de92634cb46ad78e3650/pkg/sql/logictest/testdata/logic_test/tpch_vec#L781)):*
> ```
> │
> └ Node 1
>   └ *colexec.sortOp
> ```

Are we sure we want to implement the visibility into the non-vectorized tree by having processors implement the `OpNode` interface? It weird to have to implement a vectorized interface, and processors that haven't done so won't show up in explain. Is there a way to delegate explaining of a non-vectorized tree to another function? Or maybe have the node be an opaque "wrapped processor" (similar to `LocalProcessor`), but I'm not sure whether that's better. What you have might be the best solution right now.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42873)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/execplan.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKaYHnBC_t0jPIZO99:-LvMCQT37gPKBuTXUBCc:b-37l3u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L24)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This dependency makes me slightly uncomfortable. Is there a way to avoid it?
</blockquote></details>

I don't like it myself, but philosophically speaking, this dependency was already there the moment we decided to wrap any processor. Previously it was solved by having a few processor live in `execinfra`, but that's not right - the processors should live in `rowexec`, and this PR fixes that.

Now the question is how do we handle the mixed-flow? Ideally, the setup of the vectorized flow (which can include processors) would depend on `rowexec`, but `colexec` would only know about columnar execution.

While typing out this comment, I realized that it's a minor change, so I added another commit to do that.
___
*[pkg/sql/colexec/execplan.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKaHEd8hZy1XBvpzSH:-LvMHSkn-N0y-QuFSLZx:be5vrkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L244)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I like this, does this mean we can change our supported check (the one we have before sending out the flows for vectorization) to be more lightweight? Or would it not have much benefit given the interface you added to make constructions noops?
</blockquote></details>

I don't see much benefit in that direction - currently, we still want to fully instantiate the columnar operators because operators' constructors can return errors other than this `isSupported` check does.
___
*[pkg/sql/colexec/execplan.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKca2kDfUBtjdpi7sr:-LvMHyb72Yzh0BgZsmOh:b-s7pgrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L413)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we have a heuristic that prohibits more than `n` wraps? I wonder what the threshold is where we'd just benefit from running the whole flow in the row execution engine.
</blockquote></details>

Good point, I was also thinking about this. I think that we mostly care about the pair of `materializer - columnarizer` that is added whenever the input to the wrapped processor is not a `columnarizer` already. We could in `SupportsVectorized` check simply traverse all the `leaves` (the `execinfra.OpNode`s) and see how many `columnarizer`s we have in there relative to the total number of nodes. I'd say that if > 20% of all nodes are `columnarizer`s, then we will fallback to row-by-row engine with `auto` setting. Thoughts?

I also was thinking that we might wanna introduce a `vectorize` setting so that only columnar operators are planned with wrapping disallowed completely (even for `index` and `lookup` joins).
___
*[pkg/sql/colexec/execplan.go, line 452 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKcCCED9kkZVlRBMLO:-LvMJufS2aB24rlab4Eh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L452)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you just mention that memory used will still be accounted for?
</blockquote></details>

Done.
___
*[pkg/sql/execinfra/stats.proto, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKdaaK5-qIDx76STck:-LvMJx1Z8to9_igTLQIe:b1kgezw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea9c6a53b149912324c2489e5b7dfd8029e6da1/pkg/sql/execinfra/stats.proto#L19)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Will the fact that these protos moved affect displaying these stats?
</blockquote></details>

I believe there will be no difference. Important point is that all protos are defined as if they are in `package cockroach.sql.distsqlrun;`.
___
*[pkg/sql/logictest/testdata/logic_test/tpch_vec, line 781 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKeAS49Bhv5Qn3z6M3:-LvMKIJiBr0SD6kjYUYY:bu07wa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bed91ca89bf5780a9c77de92634cb46ad78e3650/pkg/sql/logictest/testdata/logic_test/tpch_vec#L781)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Are we sure we want to implement the visibility into the non-vectorized tree by having processors implement the `OpNode` interface? It weird to have to implement a vectorized interface, and processors that haven't done so won't show up in explain. Is there a way to delegate explaining of a non-vectorized tree to another function? Or maybe have the node be an opaque "wrapped processor" (similar to `LocalProcessor`), but I'm not sure whether that's better. What you have might be the best solution right now.
</blockquote></details>

Hm, I kinda like the way this output looks - it is clear that this vectorized flow is actually a "mixed" flow. I'd definitely want to see the names of the wrapped processors.

I agree that the fact that processors are implementing `execinfra.OpNode` interface is somewhat broken, but we already had that for `indexJoiner` and `joinReader`, and in this PR I've gone over all processors that implement `execinfra.RowSource` (necessary condition for being wrapped) and added the implementation. I think right now this is the least invasive change that does the job.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 36 of 36 files at r4, 32 of 32 files at r5, 10 of 10 files at r6, 14 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-:-LwDvqb500HfosXIsvp6:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKaYHnBC_t0jPIZO99:-LwDvDkh-qdmJ8kjof-Y:bccpe83) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L24)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't like it myself, but philosophically speaking, this dependency was already there the moment we decided to wrap any processor. Previously it was solved by having a few processor live in `execinfra`, but that's not right - the processors should live in `rowexec`, and this PR fixes that.

Now the question is how do we handle the mixed-flow? Ideally, the setup of the vectorized flow (which can include processors) would depend on `rowexec`, but `colexec` would only know about columnar execution.

While typing out this comment, I realized that it's a minor change, so I added another commit to do that.
</blockquote></details>

Awesome!
___
*[pkg/sql/colexec/execplan.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKca2kDfUBtjdpi7sr:-LwDvKXL3Km4pGHOVu8W:b9louvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L413)):*
> I'd say that if > 20% of all nodes are columnarizers, then we will fallback to row-by-row engine with auto setting. Thoughts?
That SGTM. We might not want to get too clever with this, I think this decision should probably be pulled out into the optimizer at some point.

> I also was thinking that we might wanna introduce a vectorize setting so that only columnar operators are planned with wrapping disallowed completely (even for index and lookup joins).
Not sure if we'd benefit much from that, what would that be for?
___
*[pkg/sql/colflow/colbatch_scan_test.go, line 82 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LwDurQOAGVUg3OJ3q0b:-LwDurQPDiMAdmpX_oJr:b-gyiqxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b5ef7a0188229be6be6e4a9ee5a645b666034ee/pkg/sql/colflow/colbatch_scan_test.go#L82)):*
> ```Go
> 				b.StopTimer()
> 				res, err := colexec.NewColOperator(
> 					ctx, &flowCtx, &spec, nil /* inputs */, testMemAcc,
> ```

With the addition of `processorConstructor`, I think we should change the arguments to be part of an arg struct to organize them better and make these calls less verbose in another PR

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-:-LwEh1lCEK-Dx9GPzpMX:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LvKca2kDfUBtjdpi7sr:-LwEh54Y2hBNXcwCBIiX:b-8rntqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56a7ea27481a40af50b6b51e8c549fafb256aa1/pkg/sql/colexec/execplan.go#L413)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

> I'd say that if > 20% of all nodes are columnarizers, then we will fallback to row-by-row engine with auto setting. Thoughts?
That SGTM. We might not want to get too clever with this, I think this decision should probably be pulled out into the optimizer at some point.

> I also was thinking that we might wanna introduce a vectorize setting so that only columnar operators are planned with wrapping disallowed completely (even for index and lookup joins).
Not sure if we'd benefit much from that, what would that be for?
</blockquote></details>

I'm not sure, but it seems that the wrapped processors could be the bottlenecks in the mixed flows, disabling the wrapping would be somewhat similar to `experimental_always`. In theory, we would also need to tweak the optimizer cost model so that the plans with columnar operators are favored, but this idea is definitely not fully fleshed out.
___
*[pkg/sql/colflow/colbatch_scan_test.go, line 82 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42873#-LwDurQOAGVUg3OJ3q0b:-LwEiBJS9U28TjCdfmPK:belan7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b5ef7a0188229be6be6e4a9ee5a645b666034ee/pkg/sql/colflow/colbatch_scan_test.go#L82)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

With the addition of `processorConstructor`, I think we should change the arguments to be part of an arg struct to organize them better and make these calls less verbose in another PR
</blockquote></details>

Yeah, I agree.

**Pull request merged**
