### PR TITLE
scripts: fix the release note script to pick up more backports

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, the release note script was only recognizing PR
merges from either of two formats:

- from Bors, starting with `Merge #xxx #yyy`
- from Github, starting with `Merge pull request #xxx from ...`

Sometime in 2019, Github has started populating merge commits using
a different format, using instead the title of the PR followed by the
PR number between parentheses.

This new format was not recognized by the script and caused it to skip
over these merges (and all their underlying commits) and list them in
the section "changes without a release note annotation".

This patch fixes it.

Release note: None

### CODE REVIEW

**Review by jseldess — APPROVED** [review]
:lgtm: but I didn't test it. Have you run it a few times, @knz?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43302#-:-LwPYHly91sXU_B4fvkU:b-i6v994)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @jseldess)

**Comment by knz** [comment]
Yes I have verified it picks up the missing bits on 2.1.10 and 19.1.6.

**Comment by ericharmeling** [comment]
@knz Thank you!

**Pull request merged**
