### PR TITLE
ci: fix release acceptance

### LINKED ISSUE #18347: build: Fix acceptance test invocation in docker publish step
The acceptance test invocation in teamcity-publish-artifacts.sh appears to have broken with recent changes to the acceptance tests. We need to fix this before 1.1 final. 

https://github.com/cockroachdb/cockroach/blob/e39fa2763144b0c008dc0e8aeaa5053f0c4ed029/build/teamcity-publish-artifacts.sh#L26

```
[20:48:14]+ cd pkg/acceptance
[20:48:14]+ ./acceptance.test -i docker.io/cockroachdb/cockroach -b /cockroach/cockroach -nodes 4 -test.v -test.timeout -5m
[20:48:14]I170907 20:48:14.427511 1 rand.go:74  Random seed: 4658583927301546891
[20:48:14]F170907 20:48:14.429457 41 acceptance/localcluster/cluster.go:188  while starting first node: running /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach [/home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach start --insecure --host=127.0.0.1 --port=0 --http-port=0 --store=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster665671304/1 --listening-url-file=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster665671304/1/cockroachdb-url --cache=256MiB]: fork/exec /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach: no such file or directory
```

### PR DESCRIPTION
**Pull request by tbg**
Fixes #18347.

### CODE REVIEW

**Comment by tschottdorf** [comment]
@bdarnell this ought to do it, right? Or was there a problem with the `make testbuild` itself?

**Comment by benesch** [comment]
I queued you a "Test Publish Release Binaries" build, which should exercise the code path. https://teamcity.cockroachdb.com/viewQueued.html?itemId=348971&tab=queuedBuildOverviewTab.

**Comment by benesch** [comment]
Welp, never mind, that execs build/teamcity-publish-s3-binaries.sh directly.

**Comment by bdarnell** [comment]
:lgtm:

The build was fine, it was just a "no such file" error while running. (I don't know if there will be another problem after this)

Unfortunately this is tricky to test, since it is not run in "test" teamcity jobs. We should probably run everything up to the `docker push` in test jobs too.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18400#-:-KtgiKvTKVKVsF6YHAFY:bs8retk)*

**Pull request merged**
