### PR TITLE
UI bugfixes

### LINKED ISSUE #4641: ui: remove unused columns from "logs" table
The `Node`, `Store`, `Range`, `Key` and `Method` columns will always be empty and can be removed. There is additional cleanup in the implementation. The `LogEntry.{thread_id,node_id,store_id,range_id,method,key,stacks,args}` fields will never be returned. Note that `LogEntry.format` contains the already formatted message so formatting of the message in the UI can be removed.

### LINKED ISSUE #4642: ui: "logs" page bug with regex filter
Navigate to the "logs" page for a node and let it sit there for a while. Looks like on every refresh a new "Regex Filter" appears.

screen shot 2016-02-25 at 10 38 09 am

### LINKED ISSUE #4867: ui: node count should not display values using scientific notation (2e+1 instead of 20)

### LINKED ISSUE #4954: ui: updated time breaks when the server is unreachable
The last updated time should either show the last attempt to reach the server, or the last time we successfully reach the server.

screen shot 2016-03-07 at 4 16 34 pm

### PR DESCRIPTION
**Pull request by maxlang**
Fix updated time in top bar when update time isn't present - fixes #4954 
Fix number of node chart format - fixes #4867
Fix up logs page. 
- Prevent continual adding of html (fixes #4642)
- Fix styling
- Reload without having to fix enter (otherwise the values get overwritten by page redraws.)
- Remove unneeded columns (fixes #4641)

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4975)

### CODE REVIEW

**Comment by maxlang** [comment]
Old logs page
screen shot 2016-03-08 at 9 28 46 am

Fixed logs page
screen shot 2016-03-08 at 9 22 52 am

Old "updated" string
screen shot 2016-03-08 at 9 28 11 am

Fixed "updated" string
screen shot 2016-03-08 at 9 23 15 am

Old nodes display
screen shot 2016-03-08 at 9 28 02 am

Fixed nodes display
screen shot 2016-03-08 at 9 26 28 am

**Comment by mrtracy** [comment]
Reviewed 4 of 10 files at r1.
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ui/ts/components/health.ts, line 58 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-KCMMi3iMVpGv9FB1O1B:-KCMMi3iMVpGv9FB1O1C:901138280) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53ca610fbf12b04ef02c75d8d33f04f9e9a23d5/ui/ts/components/health.ts#L58)):*
Any notion of why they can't be present now?  Mention what needs to happen for these to be re-enabled. 

---

*[ui/ts/pages/log.ts, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-KCMNdWvSfGzd0c1FaXI:-KCMNdWvSfGzd0c1FaXJ:-1701780484) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53ca610fbf12b04ef02c75d8d33f04f9e9a23d5/ui/ts/pages/log.ts#L97)):*
`m.route` isn't a soft change?   That sucks and is unexpected.  Soft changes have been widespread for, as you can tell by the date on that stackoverflow, at least six years.

---

*[ui/ts/pages/log.ts, line 102 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-KCMRtj7f_qYA65LtDhy:-KCMRtj8jvGgT9Pga4ig:-136710686) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53ca610fbf12b04ef02c75d8d33f04f9e9a23d5/ui/ts/pages/log.ts#L102)):*
How does debouncing fix the problem?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975)*

**Comment by maxlang** [comment]
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ui/ts/components/health.ts, line 58 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-KCMMi3iMVpGv9FB1O1B:-KCMWXSjm_ioLn7zkmJt:2039117788) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53ca610fbf12b04ef02c75d8d33f04f9e9a23d5/ui/ts/components/health.ts#L58)):*
No real reason - the health endpoint refreshes at a different frequency from the main graphs, so I decided having the word "refreshing" flash was confusing. I'll make a note.

---

*[ui/ts/pages/log.ts, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-KCMNdWvSfGzd0c1FaXI:-KCMXLc1Is510DrACtXH:1634328938) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53ca610fbf12b04ef02c75d8d33f04f9e9a23d5/ui/ts/pages/log.ts#L97)):*
Actually, it might be soft, but because mithril redraws after each change, the inputs lose focus. I can't tell exactly what the issue is.

---

*[ui/ts/pages/log.ts, line 102 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-KCMRtj7f_qYA65LtDhy:-KCMXWLOvhxmaBN6Ikac:1151752566) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53ca610fbf12b04ef02c75d8d33f04f9e9a23d5/ui/ts/pages/log.ts#L102)):*
The main issue is that if you type something, wait to press enter, and the health endpoint finishes a check, the input is cleared and loses focus. To fix that I updated after keyup. But of course then the page was being redrawn after every character I typed. This way, I wait and it hopefully won't refresh until you're done typing. I'll add a note - this behavior isn't ideal, but I'm not sure how to address it within the context of mithril. If we move away from mithril, our new framework might solve this or have a separate solution, so I felt it wasn't worth going into depth here until we knew how were were going to proceed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975)*

**Comment by mrtracy** [comment]
The issue with focus is not the route, it's the VDOM system.  Try using this solution provided by mithril: https://lhorie.github.io/mithril/mithril.html#dealing-with-focus

---

Review status: 2 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-:-KCMtisQtvL7bwtd75Td:566820883)*

**Comment by mrtracy** [comment]
Hmm, but actually, while that will solve the problem of refreshes from an AJAX query, I do believe that changing the route always triggers a full redraw.  In order to deal with that, you might also have to give the element a context.retain flag: https://lhorie.github.io/mithril/mithril.html#persisting-dom-elements-across-route-changes

---

Review status: 2 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-:-KCMu2S-bbKoB-i1Pob6:1382547148)*

**Comment by mrtracy** [comment]
Review status: 2 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[ui/ts/pages/log.ts, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-KCMNdWvSfGzd0c1FaXI:-KCMvCsrmR_i4zEw7IQi:2124947105) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53ca610fbf12b04ef02c75d8d33f04f9e9a23d5/ui/ts/pages/log.ts#L97)):*
It's not an issue with soft routing, its an issue with mithril's vdom algorithm.  I've included some instructions on how to deal with it above; however, even if you choose to use your current solution, the issue is not a "hard" route change, so this comment should be removed.

---

*[ui/ts/pages/log.ts, line 102 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-KCMRtj7f_qYA65LtDhy:-KCMuvv7PXUdXm-K9Nvo:126686853) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53ca610fbf12b04ef02c75d8d33f04f9e9a23d5/ui/ts/pages/log.ts#L102)):*
I've updated the comment with some suggestions on how to deal with this in mithril.  However, if you think this solution is fine for now, go ahead and use it, but please update the comment on "debouncedReroute" with more information on the problem this is trying to solve.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975)*

**Comment by maxlang** [comment]
Ok I think the full redraw tricked me into thinking it was a refresh - because the page flashes. I'll see if either of these solutions work.

---

Review status: 2 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[ui/ts/pages/log.ts, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-KCMNdWvSfGzd0c1FaXI:-KCMwBlUBzzUm_RMTnSA:1606105017) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53ca610fbf12b04ef02c75d8d33f04f9e9a23d5/ui/ts/pages/log.ts#L97)):*
Ok - the page just visually looked like it was refreshing, but either way it looks like there's a way you're supposed to address these issues. I'll take a look.

---

*[ui/ts/pages/log.ts, line 102 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-KCMRtj7f_qYA65LtDhy:-KCMwStQ9xaH69FuVQaK:-1571629475) ([raw file](https://github.com/cockroachdb/cockroach/blob/a53ca610fbf12b04ef02c75d8d33f04f9e9a23d5/ui/ts/pages/log.ts#L102)):*
I'll see if I can get the focus fix to work, and if not I'll file an issue.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-:-KCMwaK6KyYs-E_R4Qc-:-2069578036)*

**Comment by maxlang** [comment]
Thanks for the tips. I seem to have gotten it working.

---

Review status: 2 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-:-KCRIoZaMsNhsndBE9OH:-798277021)*

**Comment by mrtracy** [comment]
Hah, a bit of a hammer, but if it's fixed it's fixed.  Definitely one of the oddities of mithril.  LGTM.

---

Reviewed 2 of 5 files at r2, 1 of 3 files at r3.
Review status: 5 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-:-KCRljcX4Xo1a5N_eq_8:1175521840)*

**Comment by mrtracy** [comment]
After talking with you in person, LGTM is revoked because you apparently did not get it working.  :(  Good luck!

---

Review status: 5 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-:-KCRlxKnsjcFprmLR3wU:-69995426)*

**Comment by maxlang** [comment]
Removed updating the URL as discussed

---

Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-:-KCU_VaA-T_Zv2e1vHub:1233997798)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4975#-:-KCWnHrbUaWwdJezmHd_:1417088721)*

**Pull request merged**
