### PR TITLE
sql: add catalog.Index interface, replace catalog.TableDescriptor methods for indexes

### PR DESCRIPTION
**Pull request by postamar**
In an effort to not directly use `descpb.IndexDescriptor protos` everywhere, this multi-commit PR:
1. introduces a new `catalog.Index` interface to encapsulate them, and a bunch of new methods in `catalog.TableDescriptor` to replace those which have `descpb.IndexDescriptor` in their signatures, this is done in the first commit;
2. replaces calls to the old methods with calls to the new methods throughout the codebase, this is done one method at a time in the subsequent commits.

This breakdown into multiple commits is done to ease review, after all most of the contents of this diff are effectively little more than noise. Still, there are a few non-straightforward changes, but I figured they were worth it, though. 

This PR is motivated by https://github.com/cockroachdb/cockroach/issues/57465, see also its parent issue https://github.com/cockroachdb/cockroach/issues/56306 for more details. 

Subsequent work should consist in propagating this `descpb.IndexDescriptor -> catalog.Index` change further throughout the codebase.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
The biggest thing missing in the first commit, as I review it, is unit testing of all of these methods. This code is an opportunity for us to have good unit testing. There are some different approaches you could take. You could do it externally using an `_test` package to create a server and use SQL syntax to construct descriptors. That's probably less painful than doing it by hand. 

> Reviewed 15 of 15 files at r1, 7 of 7 files at r2, 15 of 15 files at r3, 7 of 7 files at r4, 8 of 8 files at r5, 15 of 15 files at r6, 16 of 16 files at r7, 38 of 38 files at r8, 39 of 39 files at r9, 42 of 42 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-:-MQFFkV723lP7v9BQqEl:b-6y83xb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/truncate.go, line 198 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQFZBklAz62sfTnbGKJ:-MQFZBklAz62sfTnbGKK:bqy20qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/064b855db00b8dc402fe4af54b5dd0b056de0229/pkg/sql/truncate.go#L198)):*
> ```
> 	oldIndexes := make([]descpb.IndexDescriptor, len(tableDesc.ActiveIndexes()))
> 	for _, idx := range tableDesc.ActiveIndexes() {
> ```

It seems somewhat subtle that these are going to line up in a contiguous manner. I think, maybe, I don't have a clear enough mental model for `Ordinal`.
___
*[pkg/sql/catalog/descriptor.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQEg22k-vDiCRPKyTOJ:-MQEg22k-vDiCRPKyTOK:b-l80ptx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e1ebb9c734f53bbeace7eac8a0ebd6b02101db6/pkg/sql/catalog/descriptor.go#L150)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
> 	ForEachIndex(opts IndexOpts, f func(idx Index) error) error
> 	ForEachActiveIndex(f func(idx Index) error) error
> 	ForEachNonDropIndex(f func(idx Index) error) error
> 	ForEachPartialIndex(f func(idx Index) error) error
> 	ForEachPublicNonPrimaryIndex(f func(idx Index) error) error
> 	ForEachWritableNonPrimaryIndex(f func(idx Index) error) error
> 	ForEachDeletableNonPrimaryIndex(f func(idx Index) error) error
> 	ForEachDeleteOnlyNonPrimaryIndex(f func(idx Index) error) error
> 	FindIndex(opts IndexOpts, test func(idx Index) bool) Index
> 	FindActiveIndex(test func(idx Index) bool) Index
> 	FindNonDropIndex(test func(idx Index) bool) Index
> 	FindPartialIndex(test func(idx Index) bool) Index
> 	FindPublicNonPrimaryIndex(test func(idx Index) bool) Index
> 	FindWritableNonPrimaryIndex(test func(idx Index) bool) Index
> 	FindDeletableNonPrimaryIndex(test func(idx Index) bool) Index
> 	FindDeleteOnlyNonPrimaryIndex(test func(idx Index) bool) Index
> ```
</details>


Should these be functions implemented on top of the interface rather than in the interface itself? Seems like all of the implementations are going to end up interacting with the slices. At some point there is a cost to growing the interface to have all of the functionality. 
___
*[pkg/sql/catalog/descriptor.go, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQFG96TBQp0iC7To88U:-MQFG96U-mtEmH1BPiqF:b1kftw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e1ebb9c734f53bbeace7eac8a0ebd6b02101db6/pkg/sql/catalog/descriptor.go#L220)):*
> ```Go
> 
> // Index is an interface around the index descriptor types.
> type Index interface {
> ```

A bit of grouping might be good here. Eventually we'll want comments too. 
___
*[pkg/sql/catalog/descriptor.go, line 215 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQFi0804A7KB9y8wC4t:-MQFi0804A7KB9y8wC4u:bp1pg0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/064b855db00b8dc402fe4af54b5dd0b056de0229/pkg/sql/catalog/descriptor.go#L215)):*
> ```Go
> 	IndexDescDeepCopy() descpb.IndexDescriptor
> 
> 	Ordinal() int
> ```

In particular I think it's really important to comment this. I believe that it corresponds to indexes in `AllIndexes()` and for active indexes it corresponds to `ActiveIndexes()`
___
*[pkg/sql/catalog/tabledesc/index.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQEh-gv-Jgg8ZFdXawz:-MQEh-gv-Jgg8ZFdXax-:bcjfhao) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e1ebb9c734f53bbeace7eac8a0ebd6b02101db6/pkg/sql/catalog/tabledesc/index.go#L39)):*
> ```Go
> 
> // IndexDescDeepCopy returns a deep copy of the underlying protobuf descriptor.
> func (w index) IndexDescDeepCopy() descpb.IndexDescriptor {
> ```

These methods should almost definitely be on the pointer and not the struct. 
___
*[pkg/sql/catalog/tabledesc/index.go, line 314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQEmRGd5V3FI2Z3mqKx:-MQEmRGd5V3FI2Z3mqKy:b-cwh34i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e1ebb9c734f53bbeace7eac8a0ebd6b02101db6/pkg/sql/catalog/tabledesc/index.go#L314)):*
> ```Go
> // indexCache contains lazily precomputed slices of catalog.Index interfaces.
> // A field value of nil indicates that the slice hasn't been precomputed yet.
> type indexCache struct {
> ```

There are some tricks we use take to eliminate some allocations here. Let's revisit them later. Ideally the allocations shouldn't matter if we follow through on https://github.com/cockroachdb/cockroach/pull/53747 / https://github.com/cockroachdb/cockroach/issues/55960
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQDqLxX6dGwppqhR86N:-MQDqLxY4BVUbHFWBtYI:b-72nfx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e1ebb9c734f53bbeace7eac8a0ebd6b02101db6/pkg/sql/catalog/tabledesc/table_desc.go#L318)):*
> ```Go
> // catalog.Index interface.
> func (desc *wrapper) PrimaryIndexInterface() catalog.Index {
> 	return index{desc: &desc.PrimaryIndex}
> ```

This is stealthily going to incur an allocation every time you call it. Instead I think it may make sense to stick this index object inside the wrapper and then return the pointer here.

**Review by postamar — COMMENTED** [review]
I've added some testing, among other things. Coverage is not strictly complete but it goes most of the way. Depending on how you define unit testing this might not qualify as such but IMHO it's as low-level a test as can be done while remaining meaningful.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-:-MQPnjDZ2_0hmY5L4wyX:bg4yrrp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/truncate.go, line 198 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQFZBklAz62sfTnbGKJ:-MQPodSF1_LE-6JzPebS:b-r7ty43) ([raw file](https://github.com/cockroachdb/cockroach/blob/064b855db00b8dc402fe4af54b5dd0b056de0229/pkg/sql/truncate.go#L198)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	oldIndexes := make([]descpb.IndexDescriptor, len(tableDesc.ActiveIndexes()))
> 	for _, idx := range tableDesc.ActiveIndexes() {
> ```

It seems somewhat subtle that these are going to line up in a contiguous manner. I think, maybe, I don't have a clear enough mental model for `Ordinal`.
</blockquote></details>

I've added more comments on how Ordinal() works which I'm hoping will clear this up.
___
*[pkg/sql/catalog/descriptor.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQEg22k-vDiCRPKyTOJ:-MQPozfhDZmmE4DEDviD:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e1ebb9c734f53bbeace7eac8a0ebd6b02101db6/pkg/sql/catalog/descriptor.go#L150)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	ForEachIndex(opts IndexOpts, f func(idx Index) error) error
> 	ForEachActiveIndex(f func(idx Index) error) error
> 	ForEachNonDropIndex(f func(idx Index) error) error
> 	ForEachPartialIndex(f func(idx Index) error) error
> 	ForEachPublicNonPrimaryIndex(f func(idx Index) error) error
> 	ForEachWritableNonPrimaryIndex(f func(idx Index) error) error
> 	ForEachDeletableNonPrimaryIndex(f func(idx Index) error) error
> 	ForEachDeleteOnlyNonPrimaryIndex(f func(idx Index) error) error
> 	FindIndex(opts IndexOpts, test func(idx Index) bool) Index
> 	FindActiveIndex(test func(idx Index) bool) Index
> 	FindNonDropIndex(test func(idx Index) bool) Index
> 	FindPartialIndex(test func(idx Index) bool) Index
> 	FindPublicNonPrimaryIndex(test func(idx Index) bool) Index
> 	FindWritableNonPrimaryIndex(test func(idx Index) bool) Index
> 	FindDeletableNonPrimaryIndex(test func(idx Index) bool) Index
> 	FindDeleteOnlyNonPrimaryIndex(test func(idx Index) bool) Index
> ```

Should these be functions implemented on top of the interface rather than in the interface itself? Seems like all of the implementations are going to end up interacting with the slices. At some point there is a cost to growing the interface to have all of the functionality. 
</blockquote></details>

Done
___
*[pkg/sql/catalog/descriptor.go, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQFG96TBQp0iC7To88U:-MQPpD2F3Dj5cME1VAQK:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e1ebb9c734f53bbeace7eac8a0ebd6b02101db6/pkg/sql/catalog/descriptor.go#L220)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

A bit of grouping might be good here. Eventually we'll want comments too. 
</blockquote></details>

Done
___
*[pkg/sql/catalog/descriptor.go, line 215 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQFi0804A7KB9y8wC4t:-MQPpEL-3h_DriNVaASJ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/064b855db00b8dc402fe4af54b5dd0b056de0229/pkg/sql/catalog/descriptor.go#L215)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

In particular I think it's really important to comment this. I believe that it corresponds to indexes in `AllIndexes()` and for active indexes it corresponds to `ActiveIndexes()`
</blockquote></details>

Done
___
*[pkg/sql/catalog/tabledesc/index.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQEh-gv-Jgg8ZFdXawz:-MQPpFx08o6oyTZ1t54x:bjljirx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e1ebb9c734f53bbeace7eac8a0ebd6b02101db6/pkg/sql/catalog/tabledesc/index.go#L39)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

These methods should almost definitely be on the pointer and not the struct. 
</blockquote></details>

I agree with you in principle, however in this case the `index` struct is basically a pointer to the desc along with a few metadata. It's tiny and should remain tiny. I'll do the change if you insist but imho it feels like we're already calling by reference.
___
*[pkg/sql/catalog/tabledesc/index.go, line 314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQEmRGd5V3FI2Z3mqKx:-MQPqCgXDxvx35MueU4u:b-gda452) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e1ebb9c734f53bbeace7eac8a0ebd6b02101db6/pkg/sql/catalog/tabledesc/index.go#L314)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

There are some tricks we use take to eliminate some allocations here. Let's revisit them later. Ideally the allocations shouldn't matter if we follow through on https://github.com/cockroachdb/cockroach/pull/53747 / https://github.com/cockroachdb/cockroach/issues/55960
</blockquote></details>

I've refined this somewhat (I think? Please LMK) and in the process fixed a small regression of mine in `index_encoding.go`. 
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQDqLxX6dGwppqhR86N:-MQPr7EH-m2D0OTzAUG6:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e1ebb9c734f53bbeace7eac8a0ebd6b02101db6/pkg/sql/catalog/tabledesc/table_desc.go#L318)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is stealthily going to incur an allocation every time you call it. Instead I think it may make sense to stick this index object inside the wrapper and then return the pointer here. 
</blockquote></details>

OK

**Comment by postamar** [comment]
CI had one failure on an acceptance test which appears to be unrelated to these changes, see https://github.com/cockroachdb/cockroach/issues/58489 .

**Comment by ajwerner** [comment]
Have you rebased master? Try rebasing and pushing again

**Review by ajwerner — COMMENTED** [review]
Thanks for the tests and comments. Just nits from me now. 

> Reviewed 1 of 3 files at r11, 19 of 19 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-:-MQSJ1BP2wsN8yR_92ti:b5r5532)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/catalog/descriptor.go, line 458 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSIMe67QpSYQ4pbNfh:-MQSIMe67QpSYQ4pbNfi:b-65on65) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/catalog/descriptor.go#L458)):*
> ```Go
> 		}
> 		if err := f(idx); err != nil {
> 			return err
> ```

One thing we may want to support here is https://godoc.org/github.com/cockroachdb/cockroach/pkg/util/iterutil#Done. It allows users to supply an error to stop iteration that gets swallowed. This is a pattern we've been picking up and is better than having the closures put a bool somewhere and then early returning. 

In short this would look like:

```
if iterutils.Done(err) {
    err = nil
}
return err
```
___
*[pkg/sql/catalog/descriptor.go, line 466 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSIZ2AD1BIciiV5Ip9:-MQSIZ2AD1BIciiV5IpA:b5qo82q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/catalog/descriptor.go#L466)):*
> ```Go
> func forEachIndex(slice []Index, f func(idx Index) error) error {
> 	for _, idx := range slice {
> 		if err := f(idx); err != nil {
> ```

same iterutil comment here
___
*[pkg/sql/catalog/descriptor.go, line 516 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSIkcb5YM52xMuzTa0:-MQSIkcb5YM52xMuzTa1:b-3f4lvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/catalog/descriptor.go#L516)):*
> ```Go
> // Indexes are visited in their canonical order, see Index.Ordinal().
> func FindIndex(desc TableDescriptor, opts IndexOpts, test func(idx Index) bool) Index {
> 	for _, idx := range desc.AllIndexes() {
> ```

If you had the `iterutil.Done` thing then you could just call `ForEachIndex` inside of this. 
___
*[pkg/sql/catalog/descriptor.go, line 535 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSIrLE-hOnIr7vHgee:-MQSIrLE-hOnIr7vHgef:b-wcwl5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/catalog/descriptor.go#L535)):*
> ```Go
> func findIndex(slice []Index, test func(idx Index) bool) Index {
> 	for _, idx := range slice {
> 		if test(idx) {
> ```

Ditto the `iterutil.Done` thing here 
___
*[pkg/sql/catalog/tabledesc/index_test.go, line 52 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSGiQB5ArKdd-T2GaG:-MQSGiQC57_dDZkNgqX4:brsg62c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/catalog/tabledesc/index_test.go#L52)):*
> ```Go
> 			CONSTRAINT pk PRIMARY KEY (c1 ASC, c2 ASC, c3 ASC),
> 			INDEX s1 (c4 DESC, c5 DESC),
>       INVERTED INDEX s2 (c6),
> ```

super nit: indentation
___
*[pkg/sql/rowenc/index_encoding.go, line 550 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSH9ls0xTTBVGrZI8o:-MQSH9ls0xTTBVGrZI8p:b4bvrbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/rowenc/index_encoding.go#L550)):*
> ```Go
> 
> 	interleaves := make([]catalog.Index, 0, len(desc.ActiveIndexes()))
> 	interleaves = append(interleaves, desc.ActiveIndexes()...)
> ```

extremely minor nit: just do this all in one expression?

```
	interleaves := append(make([]catalog.Index, 0, len(desc.ActiveIndexes())), 
                desc.ActiveIndexes()...)
```

**Review by postamar — COMMENTED** [review]
Thanks for the quick turnaround. I rebased on master, looking good now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-:-MQSzS5SEFCj4ESakQAF:bw84jut)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/descriptor.go, line 458 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSIMe67QpSYQ4pbNfh:-MQSzYq11SflYZT-iCjm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/catalog/descriptor.go#L458)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

One thing we may want to support here is https://godoc.org/github.com/cockroachdb/cockroach/pkg/util/iterutil#Done. It allows users to supply an error to stop iteration that gets swallowed. This is a pattern we've been picking up and is better than having the closures put a bool somewhere and then early returning. 

In short this would look like:

```
if iterutils.Done(err) {
    err = nil
}
return err
```
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descriptor.go, line 466 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSIZ2AD1BIciiV5Ip9:-MQSzcNM9_ZeKpnj0tYr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/catalog/descriptor.go#L466)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

same iterutil comment here
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descriptor.go, line 516 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSIkcb5YM52xMuzTa0:-MQSzdPe6JHTVTmiXXKm:bihwolj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/catalog/descriptor.go#L516)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

If you had the `iterutil.Done` thing then you could just call `ForEachIndex` inside of this. 
</blockquote></details>

Agreed, though I tried rewriting this using ForEachIndex but it actually turned out less clear. This did lead me to move the logic surrounding `opts` into its own helper function.
___
*[pkg/sql/catalog/descriptor.go, line 535 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSIrLE-hOnIr7vHgee:-MQT-7ty-UNqvKZPeDk5:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/catalog/descriptor.go#L535)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Ditto the `iterutil.Done` thing here 
</blockquote></details>

See above.
___
*[pkg/sql/catalog/tabledesc/index_test.go, line 52 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSGiQB5ArKdd-T2GaG:-MQT-C265fbkh6bOP2LM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/catalog/tabledesc/index_test.go#L52)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

super nit: indentation
</blockquote></details>

Done.
___
*[pkg/sql/rowenc/index_encoding.go, line 550 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQSH9ls0xTTBVGrZI8o:-MQT-Cs97hItiZZoHisY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4428fdc3c03064a2b52b26e0a33eff24bcb3924b/pkg/sql/rowenc/index_encoding.go#L550)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

extremely minor nit: just do this all in one expression?

```
	interleaves := append(make([]catalog.Index, 0, len(desc.ActiveIndexes())), 
                desc.ActiveIndexes()...)
```
</blockquote></details>

Done.

**Review by thoszhang — APPROVED** [review]
> Reviewed 2 of 15 files at r1, 97 of 97 files at r14, 5 of 15 files at r16, 8 of 15 files at r19, 7 of 16 files at r20, 15 of 38 files at r21, 36 of 42 files at r23, 1 of 3 files at r24, 20 of 20 files at r25, 2 of 2 files at r26.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 313 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQTONSAAhV8mszbqZ1Y:-MQTONSAAhV8mszbqZ1Z:b-t5ybp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa87b0f621bd7b00b949c42fdb0d191cd74b12c5/pkg/sql/catalog/tabledesc/table_desc.go#L313)):*
> ```Go
> // in their canonical order. This is equivalent to the Indexes array in the
> // proto.
> func (desc *wrapper) PublicNonPrimaryIndexes() []catalog.Index {
> ```

nit: is there a reason why these aren't `PublicSecondaryIndexes`, etc.?

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 313 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/58273#-MQTONSAAhV8mszbqZ1Y:-MQTbgcW17Fot0KPIFJN:bfgjh24) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa87b0f621bd7b00b949c42fdb0d191cd74b12c5/pkg/sql/catalog/tabledesc/table_desc.go#L313)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: is there a reason why these aren't `PublicSecondaryIndexes`, etc.?
</blockquote></details>

Historical reasons, I guess. There was already a `GetPublicNonPrimaryIndexes` method so I just stuck with that and tried to be consistent.

**Comment by postamar** [comment]
Rebased on master because of merge conflict.

**Pull request merged**
