### PR TITLE
roachtest: fix activerecord and cleanup pgjdbc tests

### PR DESCRIPTION
**Pull request by rafiss**
- The activerecord test was passing env vars incorrectly.

- The pgjdbc test needs an updated blocklist, and the release tag is
  cleaned up now.

- Ignore flaky tests from the Django suite.

Release note: None

### CODE REVIEW

**Review by apantel — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51851)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rafiss** [comment]
thanks!

bors r=apantel

**Comment by rafiss** [comment]
bors r=apantel

**Comment by rafiss** [comment]
bors r=apantel

**Comment by rafiss** [comment]
bors r=apantel

**Pull request merged**
