### PR TITLE
importccl: DELIMITED should handle delimiters only at end of fields

### LINKED ISSUE #40959: importccl: DELIMITED should match more closely the functionality of mysql's LOAD INTO
Currently `DELIMITED` mode for importing text files has limited support for handling unmatched quotes in enclosed fields. Mysql supports a broad range of use cases and since `DELIMITED` is meant as our analog of Mysql's `LOAD INTO` command we should get them to par. Also this is currently causing problems with on-boarding enterprise clients. See #40374 which deals with mishandling of a few rows in large csv-like files.

This what one can achieve with MySql today when importing file `quotes.csv` with separator `|`:
```
"Iam"|quoted field.
I"a"m|non-quoted 2 quotes in middle.
"I"a"m"|quoted 2 quotes in middle.
I"am|non-quoted quote in middle.
"I"am"|quoted quote in middle.
```
Our current implementation crashed on this input, while in MySql this is treated quite sanely:

```
mysql> LOAD DATA INFILE 'quotes.csv'  into table baz FIELDS TERMINATED BY '|' ENCLOSED BY '"';
Query OK, 5 rows affected (0.03 sec)
Records: 5  Deleted: 0  Skipped: 0  Warnings: 0

mysql> select * from baz;
+-------+--------------------------------+
| s1    | s2                             |
+-------+--------------------------------+
| Iam   | quoted field.                  |
| I"a"m | non-quoted 2 quotes in middle. |
| I"a"m | quoted 2 quotes in middle.     |
| I"am  | non-quoted quote in middle.    |
| I"am  | quoted quote in middle.        |
+-------+--------------------------------+
5 rows in set (0.01 sec)
```

**Describe the solution you'd like**
Add support for the above use case in Cockroah `DELIMITED` import mode.

**Additional context**
See https://github.com/cockroachdb/cockroach/issues/40374

### PR DESCRIPTION
**Pull request by spaskob**
Previously DELIMITED import mode will complain about importing field
`"This a nested single quote " inside quoted field"`
when importing using option `WITH fields_enclosed_by '"'`.
Mysql implementation handles this case correctly.
For more info and examples see #40959.

Touches #40374.
Fixes #40959.

Release note (enterprise change): Fixes incorrect behavior for enclosed fields.

Release justification: This is low risk since only business logic of
import has changed. Moreover this functionality has been requested
from a potential client.

### CODE REVIEW

**Review by dt — COMMENTED** [review]
Are we doc'ing `DELIMITED` ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-:-LpUBPM6E2bhM3XWv1Ba:b4vli9k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @robert-s-lee, @rolandcrosby, and @spaskob)

___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpU8GET1wFHWM5O6iO0:-LpU8GEUBY4AftxkFKq1:b-5ikcu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L67)):*
> ```Go
> }
> 
> func (d *mysqloutfileReader) readFile(
> ```

nit (and doesn't need to go in this PR): we should rename this struct/file/etc to delimited and expunge "mysqlout" from the codebase.
___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpUAgWw41XYQDLLAT-C:-LpUAgWw41XYQDLLAT-D:b7dm63a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L75)):*
> ```Go
> 
> 	var row []tree.Datum
> 	// the current field being read.
> ```

this comment could help explain why it is a []string
___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpU91vj-D_ckTU7wcST:-LpU91vj-D_ckTU7wcSU:b-qzicsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L88)):*
> ```Go
> 	var readingField bool
> 	// If we have just encountered a potential encloser symbol.
> 	// That means if a end of filed or line is next we should honor it.
> ```

nit: s/filed/field/
___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpU8YsOAHD_uDm_GHYG:-LpU8YsOAHD_uDm_GHYH:b-2k73nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L95)):*
> ```Go
> 	reader := bufio.NewReaderSize(input, 1024*64)
> 	addField := func() error {
> 		thefield := strings.Join(field, "")
> ```

nit: don't love the name / doesn't really tell me what it and "field" are. suggestion: field -> fieldParts, thefield -> field.
___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpUAX1W3joo_icci8Q3:-LpUAX1W3joo_icci8Q4:bluoobv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L238)):*
> ```Go
> 				} else {
> 					// Unexpected since we did not
> 					// see one at start of field.
> ```

any reason not to wrap at the usual 50?
___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpU9Wpg1MX9a2Rf1CS2:-LpU9Wpg1MX9a2Rf1CS3:bbc624y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L272)):*
> ```Go
> 		}
> 
> 		field = append(field, string(c))
> ```

will an o(n) slice of 1-byte _strings_ get expensive? how hard would it be to append to field[-1]?

**Comment by rolandcrosby** [comment]
We are doc'ing DELIMITED now, yes. It solves some customer problems, is not tied to the little-known CSV RFC, and is more general than its old name implied. @spaskob - LGTM once you get through David's suggestions.

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @robert-s-lee, and @rolandcrosby)

___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpU8GET1wFHWM5O6iO0:-LpUjx3kDAwT5ZbuxZV6:b-acmf60) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L67)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit (and doesn't need to go in this PR): we should rename this struct/file/etc to delimited and expunge "mysqlout" from the codebase.
</blockquote></details>

good point, should have done it in the original DELIMITED PR. I will do it in a follow-up PR.
___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpUAgWw41XYQDLLAT-C:-LpUkIqp95w2QOQsAfwb:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L75)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

this comment could help explain why it is a []string
</blockquote></details>

done
___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpU91vj-D_ckTU7wcST:-LpUkSPv8H-XwSPjh3mu:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L88)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: s/filed/field/
</blockquote></details>

done
___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpU8YsOAHD_uDm_GHYG:-LpUkUMN3b-O_HbxgiLn:bu7tpph) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L95)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: don't love the name / doesn't really tell me what it and "field" are. suggestion: field -> fieldParts, thefield -> field.
</blockquote></details>

thanks, that was WIP name and forgot to change it
___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpUAX1W3joo_icci8Q3:-LpUlZhYAe7veLjjf435:b-bhpwuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L238)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

any reason not to wrap at the usual 50?
</blockquote></details>

Do you mean the comment? Lmk if this what you expected.
___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpU9Wpg1MX9a2Rf1CS2:-LpUlwQI1LJ1gBTfdhuD:b-85rnj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L272)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

will an o(n) slice of 1-byte _strings_ get expensive? how hard would it be to append to field[-1]? 
</blockquote></details>

In could be in come corner case but usually this is limited by the line length which should something reasonable. It's harder to reason about which is the last symbol in the presence of unicode symbols. Alternatively, we can have field be []rune aka []int32 and convert to string only in the end when we join the parts. Lmk if you like this approach.

**Review by dt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @robert-s-lee, @rolandcrosby, and @spaskob)

___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpU9Wpg1MX9a2Rf1CS2:-LpUtt2zBe3zn1s0N9HN:b-m2flrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L272)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

In could be in come corner case but usually this is limited by the line length which should something reasonable. It's harder to reason about which is the last symbol in the presence of unicode symbols. Alternatively, we can have field be []rune aka []int32 and convert to string only in the end when we join the parts. Lmk if you like this approach.
</blockquote></details>

if `[]rune` would work just as well, that'd certainly be my preference.

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @robert-s-lee, and @rolandcrosby)

___
*[pkg/ccl/importccl/read_import_mysqlout.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40960#-LpU9Wpg1MX9a2Rf1CS2:-LpYzwqE-3x0_uPkodrZ:b-hjo1vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2940d756f44be823bdce98630ba8b625dbf91a76/pkg/ccl/importccl/read_import_mysqlout.go#L272)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

if `[]rune` would work just as well, that'd certainly be my preference.
</blockquote></details>

yes that worked really nicely, turns out one can join a slice of runes by calling `string(runes)`

**Review by dt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @robert-s-lee and @rolandcrosby)

**Pull request merged**
