### PR TITLE
sql: add stddev_pop and var_pop aggregates

### LINKED ISSUE #48103: sql: add stddev_pop and var_pop aggregates
They are used by Django (https://github.com/cockroachdb/django-cockroachdb/issues/25).

https://github.com/cockroachdb/cockroach/issues/41274 is a similar issue for other aggregates that may help guide the implementation.

### PR DESCRIPTION
**Pull request by xuhui-lu**
Resolves:  #48103 

Add stddev_pop and var_pop aggregates into sql/sem/builtins/aggregate_builtins.go

Release note (sql change): Add stddev_pop and var_pop aggregate function for population stddev and variance calculation.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Hi @xuhui-lu, thanks for taking this on! I haven't reviewed the PR, but please ping me when you think it is ready for a look.

Also, nit: please squash multiple commits into one.

**Comment by xuhui-lu** [comment]
> Hi @xuhui-lu, thanks for taking this on! I haven't reviewed the PR, but please ping me when you think it is ready for a look.
> 
> Also, nit: please squash multiple commits into one.

oh thanks. I will let you know once it is ready.

**Comment by xuhui-lu** [comment]
Hi @yuzefovich , could you help review my PR?

**Review by yuzefovich — COMMENTED** [review]
Nice work! This is looking very good, and the main missing piece is some logic tests. Please take a look at `pkg/sql/logictest/testdata/logic_test/aggregate` and add some queries that use newly-added aggregate functions (make sure to verify that the output is as expected - I usually confirm it by running the same queries on Postgres database). You can also use `make testbaselogic FILES=aggregate TESTFLAGS='-rewrite'` to run that logic test file and update any output.

nit: you should update the commit message to be similar to the PR description.

nit: you should use something like `Fixes: #48103` or `Resolves: #48103` so that the issue is closed once the PR merges.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-:-MCJZ9zp1-Tgjvynljn-:b-9zi1rg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xuhui-lu)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 2504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCJ_QJZ87_CrJBZjbbV:-MCJ_QJZ87_CrJBZjbbW:b-3frca7) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c8edf9bf0ff0516c70ca46fa89ee9d44b479bf/pkg/sql/sem/builtins/aggregate_builtins.go#L2504)):*
> ```Go
> 
> func newIntVarPopAggregate(
> 	params []*types.T, evalCtx *tree.EvalContext, _ tree.Datums,
> ```

super nit: "params" is not used, so we could use `_` instead to be similar to other signatures.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 2580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCJbNdX6PYwiwQfrWWk:-MCJbNdX6PYwiwQfrWWl:b-so36je) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c8edf9bf0ff0516c70ca46fa89ee9d44b479bf/pkg/sql/sem/builtins/aggregate_builtins.go#L2580)):*
> ```Go
> // Size is part of the tree.AggregateFunc interface.
> func (a *floatVarPopAggregate) Size() int64 {
> 	return sizeOfFloatVarianceAggregate
> ```

nit: I'd define separate `sizeOfFloatVarPopAggregate` and `sizeOfDecimalVarPopAggregate` and use those in `Size()` methods.

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

Note that there is a conflict with `processors_sql.pb.go` - you might need to pull from the master branch and rebase your PR.

nit: you should update the commit message to be similar to the PR description.

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-:-MCSKrLP4SRRW7mkZGst:bg0s4zt)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by rytaft — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xuhui-lu)

___
*[pkg/sql/opt/operator.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCSOTaa07npQ8Eo7Sts:-MCSOTaa07npQ8Eo7Stt:b2y9w6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e0dede3c142bebfeb840343fa0b2be4a326b02/pkg/sql/opt/operator.go#L336)):*
> ```Go
> 		JsonAggOp, JsonbAggOp, MaxOp, MinOp, SqrDiffOp,
> 		StringAggOp, SumOp, SumIntOp, XorAggOp, PercentileDiscOp, PercentileContOp,
> 		JsonObjectAggOp, JsonbObjectAggOp, StdDevPopOp, VarPopOp:
> ```

Is this correct that these aggregates behave differently here than Variance and StdDev?

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xuhui-lu)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 2537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCSPz64DwT-mzN2tks2:-MCSPz64DwT-mzN2tks3:bpqxfb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e0dede3c142bebfeb840343fa0b2be4a326b02/pkg/sql/sem/builtins/aggregate_builtins.go#L2537)):*
> ```Go
> }
> 
> // Result calculates the variance from the member square difference aggregator.
> ```

[nit] variance -> population variance

**Comment by xuhui-lu** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xuhui-lu)
> 
> _[pkg/sql/opt/operator.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCSOTaa07npQ8Eo7Sts:-MCSOTaa07npQ8Eo7Stt:b2y9w6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e0dede3c142bebfeb840343fa0b2be4a326b02/pkg/sql/opt/operator.go#L336)):_
> 
> > ```go
> > 		JsonAggOp, JsonbAggOp, MaxOp, MinOp, SqrDiffOp,
> > 		StringAggOp, SumOp, SumIntOp, XorAggOp, PercentileDiscOp, PercentileContOp,
> > 		JsonObjectAggOp, JsonbObjectAggOp, StdDevPopOp, VarPopOp:
> > ```
> 
> Is this correct that these aggregates behave differently here than Variance and StdDev?

Yes, when there is only one row input, variance (sqrtdiff / (count - 1)) will output NULL due to zero divisor. var_pop (sqrtdiff / count) will output 0.

**Comment by xuhui-lu** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xuhui-lu)
> 
> _[pkg/sql/sem/builtins/aggregate_builtins.go, line 2537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCSPz64DwT-mzN2tks2:-MCSPz64DwT-mzN2tks3:bpqxfb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e0dede3c142bebfeb840343fa0b2be4a326b02/pkg/sql/sem/builtins/aggregate_builtins.go#L2537)):_
> 
> > ```go
> > }
> > 
> > // Result calculates the variance from the member square difference aggregator.
> > ```
> 
> [nit] variance -> population variance

Fixed. Thanks for the comment.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/operator.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCSOTaa07npQ8Eo7Sts:-MCT1nLL2CwClD_xm0dm:bkpyfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e0dede3c142bebfeb840343fa0b2be4a326b02/pkg/sql/opt/operator.go#L336)):*
<details><summary><i>Previously, xuhui-lu (Xuhui Lu) wrote…</i></summary><blockquote>

Yes, when there is only one row input, variance (sqrtdiff / (count - 1)) will output NULL due to zero divisor. var_pop (sqrtdiff / count) will output 0. 
</blockquote></details>

Great - thanks for checking.

**Comment by xuhui-lu** [comment]
> Nice! :lgtm:
> 
> Note that there is a conflict with `processors_sql.pb.go` - you might need to pull from the master branch and rebase your PR.
> 
> nit: you should update the commit message to be similar to the PR description.
> 
> > Reviewed 8 of 8 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-:-MCSKrLP4SRRW7mkZGst:bg0s4zt)_ status: :shipit: complete! 1 of 0 LGTMs obtained

cool, I've resolved the conflicts and fix the commit message. Thanks for your comment!

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @xuhui-lu)

___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 804 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCTj-SzBAsQRq5tboqX:-MCTj-SzBAsQRq5tboqY:btqdjkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd5dd09a264e00cd0cabba8857a72a83a5694fc/pkg/sql/logictest/testdata/logic_test/aggregate#L804)):*
> ```
> SELECT var_pop(x) FROM xyz WHERE x = 1
> ----
> NULL
> ```

I think this is incorrect - it should be 0 since we have a single element.
___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 824 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCTj7VNA5rfQpRvi82u:-MCTj7VNA5rfQpRvi82v:b-62kqda) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd5dd09a264e00cd0cabba8857a72a83a5694fc/pkg/sql/logictest/testdata/logic_test/aggregate#L824)):*
> ```
> SELECT stddev_pop(x) FROM xyz WHERE x = 1
> ----
> NULL
> ```

Also should be 0.
___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 898 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCTjPPs1s6KQqOx6eyM:-MCTjPPs1s6KQqOx6eyN:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd5dd09a264e00cd0cabba8857a72a83a5694fc/pkg/sql/logictest/testdata/logic_test/aggregate#L898)):*
> ```
> SELECT var_pop(1::int), var_pop(1::float), var_pop(1::decimal)
> ----
> NULL  NULL  NULL
> ```

ditto
___
*[pkg/sql/opt/operator.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCSOTaa07npQ8Eo7Sts:-MCTjTU30wb5eGqAlFK4:bi230yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e0dede3c142bebfeb840343fa0b2be4a326b02/pkg/sql/opt/operator.go#L336)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Great - thanks for checking.
</blockquote></details>

This discussion prompted me to take a look at the logic tests, and I think there is a bug in how we handle the case with exactly one row.

**Comment by xuhui-lu** [comment]
> > Reviewed 2 of 2 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @xuhui-lu)
> 
> _[pkg/sql/logictest/testdata/logic_test/aggregate, line 804 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCTj-SzBAsQRq5tboqX:-MCTj-SzBAsQRq5tboqY:btqdjkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd5dd09a264e00cd0cabba8857a72a83a5694fc/pkg/sql/logictest/testdata/logic_test/aggregate#L804)):_
> 
> > ```
> > SELECT var_pop(x) FROM xyz WHERE x = 1
> > ----
> > NULL
> > ```
> 
> I think this is incorrect - it should be 0 since we have a single element.
> 
> _[pkg/sql/logictest/testdata/logic_test/aggregate, line 824 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCTj7VNA5rfQpRvi82u:-MCTj7VNA5rfQpRvi82v:b-62kqda) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd5dd09a264e00cd0cabba8857a72a83a5694fc/pkg/sql/logictest/testdata/logic_test/aggregate#L824)):_
> 
> > ```
> > SELECT stddev_pop(x) FROM xyz WHERE x = 1
> > ----
> > NULL
> > ```
> 
> Also should be 0.
> 
> _[pkg/sql/logictest/testdata/logic_test/aggregate, line 898 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCTjPPs1s6KQqOx6eyM:-MCTjPPs1s6KQqOx6eyN:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dd5dd09a264e00cd0cabba8857a72a83a5694fc/pkg/sql/logictest/testdata/logic_test/aggregate#L898)):_
> 
> > ```
> > SELECT var_pop(1::int), var_pop(1::float), var_pop(1::decimal)
> > ----
> > NULL  NULL  NULL
> > ```
> 
> ditto
> 
> _[pkg/sql/opt/operator.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCSOTaa07npQ8Eo7Sts:-MCTjTU30wb5eGqAlFK4:bi230yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e0dede3c142bebfeb840343fa0b2be4a326b02/pkg/sql/opt/operator.go#L336)):_
> 
> Previously, rytaft (Rebecca Taft) wrote…
> This discussion prompted me to take a look at the logic tests, and I think there is a bug in how we handle the case with exactly one row.

oh yes, that is definitely a bug. I need to check the agg count against 1 instead of 2. I have fixed that. Now the logic test result should be as expected.

**Review by yuzefovich — APPROVED** [review]
Thanks for working on this! LGTM

I'll merge this once the build is green.

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-:-MCTqG0X4WH5DKx1qmL6:bcjf2dv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/operator.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51447#-MCSOTaa07npQ8Eo7Sts:-MCTqEK-8rXC576HOoq8:b-af183f) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e0dede3c142bebfeb840343fa0b2be4a326b02/pkg/sql/opt/operator.go#L336)):*
<details><summary><i>Previously, xuhui-lu (Xuhui Lu) wrote…</i></summary><blockquote>

oh yes, that is definitely a bug. I need to check the agg count against 1 instead of 2. I have fixed that. Now the logic test result should be as expected. 
</blockquote></details>

Yep, thanks!

**Comment by yuzefovich** [comment]
bors r=yuzefovich,rytaft

**Comment by xuhui-lu** [comment]
Do I need to do any fixup? I notice the bors task is cancelled.

**Comment by yuzefovich** [comment]
Looks like bors crashed, let's try again.

bors r=yuzefovich,rytaft

**Pull request merged**
