### PR TITLE
geoindex,invertedexpr: optimize allocations for RPKeyExpr

### PR DESCRIPTION
**Pull request by sumeerbhola**
RPKeyExpr is used for ST_CoveredBy.
- generateRPExprForTree appends directly to a slice passed
  as a parameter so we can take advantage of slice growth
  to reduce allocations.
- GeoRPKeyExprToSpanExpr unions the FactoredUnionSpans
  into the span with the larger capacity.
- GeoRPKeyExprToSpanExpr avoids an extra call to geoToSpan
  to generate the spansToRead.

For the following query
```
SELECT Count(census.blkid), Count(subways.name)
FROM nyc_census_blocks AS census
JOIN nyc_subway_stations AS subways
ON ST_CoveredBy(subways.geom, census.geom)
```

we get a speedup
```
Test/nyc/nyc-coveredby   85.9 ±18%  79.4 ±28%  -7.56%  (p=0.019 n=19+20)
```

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I've added a second commit that fixes an old bug that was tickled by the first change -- we were never sorting the spans when generating a `SpanExpression` from `RPKeyExpr`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53415#-:-MFajTjs7Pnhu2teZV1Z:b-xfzifw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53415#-:-MFbQ_QQASh5zT-ade6_:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53415#-:-MFgh_hw7ephF1Afm6CV:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

**Comment by otan** [comment]
bors r=rytaft

atoning for bors sins

**Pull request merged**
