### PR TITLE
sql: add support for AS OF SYSTEM TIME clause in BEGIN and SET TRANSACTION

### PR DESCRIPTION
**Pull request by ajwerner**
This PR enables use of a historical timestamp throughout the life of a read-only
transaction. It supports setting this timestamp both in the `BEGIN TRANSACTION`
and the `SET TRANSACTION` clauses. It permits updating the timestamp in `SET
TRANSACTION` even if a timestamp has already been set in `BEGIN TRANSACTION`
however it does not permit setting a transaction a historical transaction to
READ WRITE.

This change is part of the user story for follower reads but is not a directly
related feature.

There are aspects of this change at the sql layer which feel like I'm making a further mess and duplicating some logic. I'm open to suggestions on how to better consolidate this logic. 

Release note (sql change): Add support for AS OF SYSTEM TIME clause in
BEGIN TRANSACTION and SET TRANSACTION statements.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thanks for submitting this.
This is almost good to go!

- You also need to extend `sem/tree/walk.go` to recurse into the new AsOf field of the Begin struct. See SetVar and Backup for examples.

- please extend the release note in the commit message with more words: how this implies the txn is read-only, why this new feature is useful/preferable to ASOT clauses in SELECT, etc. "Sell" the feature to the external user.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-:-LXOHROo6kgZ8WEZVjOA:b-b7mfw0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/sql/conn_executor_exec.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXOGZlfBNTyJrJDpI8h:-LXOGZlfBNTyJrJDpI8i:b-4biz8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/efde15440991d9ebb737e9c48d48d7dbd535ef9c/pkg/sql/conn_executor_exec.go#L381)):*
> ```Go
> 			ex.state.isHistorical = true
> 			p.semaCtx.AsOfTimestamp = ts
> 			ex.state.mu.Lock()
> ```

This may benefit from an accessor that guarantees the locking behavior.
___
*[pkg/sql/conn_executor_exec.go, line 397 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXOGcd8EoDqj14QQB3N:-LXOGcd8EoDqj14QQB3O:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/efde15440991d9ebb737e9c48d48d7dbd535ef9c/pkg/sql/conn_executor_exec.go#L397)):*
> ```Go
> 			ex.state.mu.RLock()
> 			if *ts != ex.state.mu.txn.OrigTimestamp() {
> 				ex.state.mu.RUnlock()
> ```

ditto
___
*[pkg/sql/conn_executor_exec.go, line 1075 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXOGW6HB6Dkzm7Ka58n:-LXOGW6HB6Dkzm7Ka58o:b-am6lnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/efde15440991d9ebb737e9c48d48d7dbd535ef9c/pkg/sql/conn_executor_exec.go#L1075)):*
> ```Go
> 		}
> 
> 		// Deal with evaluating an AS OF SYSTEM TIME clause and setting the
> ```

Please hoist this code in a helper function.
___
*[pkg/sql/logictest/testdata/logic_test/txn_as_of, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXOGzjNCTuo9nzTlUBD:-LXOGzjNCTuo9nzTlUBE:b-pt7kuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/efde15440991d9ebb737e9c48d48d7dbd535ef9c/pkg/sql/logictest/testdata/logic_test/txn_as_of#L46)):*
> ```
> COMMIT
> 
> # Subqueries are only allowed if the exact same timestamp is used
> ```

nit: period missing at end of sentence
___
*[pkg/sql/logictest/testdata/logic_test/txn_as_of, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXOH3bID86Z4dnk89XS:-LXOH3bID86Z4dnk89XT:b-httgys) ([raw file](https://github.com/cockroachdb/cockroach/blob/efde15440991d9ebb737e9c48d48d7dbd535ef9c/pkg/sql/logictest/testdata/logic_test/txn_as_of#L52)):*
> ```
> # leading to a failure due to the relation not existing.
> 
> statement error pq: inconsistent \"as of system time\" timestamp. Expected: [0-9]+\.[0-9]+,[0-9]+. Generally \"as of system time\" cannot be used inside a transaction.
> ```

you can remove the entire "Expected ..." part from the expected error string, as I believe the full error message is tested elsewhere. This will make the test more readably.

**Review by knz — COMMENTED** [review]
Also a minor thing that the CI failure reveals to me:

```
                expected "pq: cannot set AS OF SYSTEM TIME transaction to READ WRITE", but found "pq: cannot set \"as of system time\" transaction to \"read write\""
```

1) I personally prefer the error text using capitals than those using the quoted words

2) try to instantiate the error object only once and reuse it in various places

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-:-LXOI1128rM9c2DEkWKz:b-4ndaq5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

**Review by ajwerner — COMMENTED** [review]
TFTR! I wavered between AS OF SYSTEM TIME and "as of system time" and appreciated the input. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-:-LXPImj-1AmkRUyE4TLM:b5px2w0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/sql/conn_executor_exec.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXOGZlfBNTyJrJDpI8h:-LXP5iS_9Mzypebdmc_c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efde15440991d9ebb737e9c48d48d7dbd535ef9c/pkg/sql/conn_executor_exec.go#L381)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This may benefit from an accessor that guarantees the locking behavior.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_exec.go, line 397 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXOGcd8EoDqj14QQB3N:-LXP5j8MD8vscNhFEhFI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efde15440991d9ebb737e9c48d48d7dbd535ef9c/pkg/sql/conn_executor_exec.go#L397)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_exec.go, line 1075 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXOGW6HB6Dkzm7Ka58n:-LXPDgMd0t-XjeeVXfcB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efde15440991d9ebb737e9c48d48d7dbd535ef9c/pkg/sql/conn_executor_exec.go#L1075)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please hoist this code in a helper function.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/txn_as_of, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXOH3bID86Z4dnk89XS:-LXPDhlA4_syEAm5UV3a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efde15440991d9ebb737e9c48d48d7dbd535ef9c/pkg/sql/logictest/testdata/logic_test/txn_as_of#L52)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can remove the entire "Expected ..." part from the expected error string, as I believe the full error message is tested elsewhere. This will make the test more readably.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
LGTM but I want Andrei to double-check the executor changes. Thanks!

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-:-LXPO5XS6IAIO4wbQLki:b2pxdz8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/sql/conn_executor.go, line 1755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXPNH6n24deBWJIpIt8:-LXPNH6oBZmGiR7S-5Q5:bdj0s2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b35443354fea40b55a795413fb2836bb84ee4e3/pkg/sql/conn_executor.go#L1755)):*
> ```Go
> 		ex.state.setHistoricalTimestamp(ex.Ctx(), ts)
> 		ex.planner.semaCtx.AsOfTimestamp = &ts
> 		ex.state.sqlTimestamp = ts.GoTime()
> ```

this assignment to `sqlTimestamp` wasn't there before. Why did you add it? Which problem does it solve?
___
*[pkg/sql/txn_state.go, line 318 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXPNodd8XgxtdM_2jFb:-LXPNode6AZj0s9hmSU1:b-aon4to) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b35443354fea40b55a795413fb2836bb84ee4e3/pkg/sql/txn_state.go#L318)):*
> ```Go
> }
> 
> var errAsOfWithReadWrite = errors.Errorf("cannot set AS OF SYSTEM TIME transaction to READ WRITE")
> ```

reuse the error from package `tree`.
___
*[pkg/sql/sem/tree/txn.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXPNwZF0aXSxsQK_Thn:-LXPNwZF0aXSxsQK_Tho:b-s49yb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b35443354fea40b55a795413fb2836bb84ee4e3/pkg/sql/sem/tree/txn.go#L131)):*
> ```Go
> 	errReadModeSpecifiedMultipleTimes       = pgerror.NewError(pgerror.CodeSyntaxError, "read mode specified multiple times")
> 	errAsOfSpecifiedMultipleTimes           = pgerror.NewError(pgerror.CodeSyntaxError, "AS OF SYSTEM TIME specified multiple times")
> 	errAsOfSpecifiedWithReadWrite           = pgerror.NewError(pgerror.CodeSyntaxError, "AS OF SYSTEM TIME specified with READ WRITE mode")
> ```

export this error and use it from `sql`.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/sql/conn_executor.go, line 1755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXPNH6n24deBWJIpIt8:-LXPOXj-4xxkLU50O7I3:b9csun0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b35443354fea40b55a795413fb2836bb84ee4e3/pkg/sql/conn_executor.go#L1755)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

this assignment to `sqlTimestamp` wasn't there before. Why did you add it? Which problem does it solve?
</blockquote></details>

Before this change calls to `now()` or `current_timetsamp()` would reflect the timestamp from the `BEGIN` rather than the timestamp set here. This sqlTimestamp in subsequent statements propagates to the TxnTimstamp in the EvalContext. The previous behavior was that transactions which had an AS OF from BEGIN would use that as their transaction time whereas those with a SET TRANSACTION would not. This asymmetry seems certainly wrong. While responding to this comment I went to add logic tests to ensure the behavior matches my expectation and it now does but in the process I discovered that the below query does not match my expectation (though is straightforward to fix). 

```
SELECT * FROM (SELECT now()) AS OF SYSTEM TIME '2019-01-01';                                                                                                             
                now                 
+----------------------------------+
  2019-01-29 16:28:59.039533+00:00  
```
Where I'd expect
```
SELECT * FROM (SELECT now()) AS OF SYSTEM TIME '2019-01-01';                                                                                                             
                now                 
+----------------------------------+
  2019-01-01 00:00:00.000000+00:00  
```

The reason this is the case is that sqlTimestamp gets used to create the TxnTimestamp when resetting or constructing the planner which happens just before we were setting this timestamp for the implicit transaction case. I spoke to Andrei for a bit about it this morning and we concluded that the current behavior is bad. I've now added an additional call to update the TxnTimestamp in the implicit transaction case as well and created logical tests for all three to demonstrate that the behavior of `now()` is consistent.
___
*[pkg/sql/txn_state.go, line 318 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXPNodd8XgxtdM_2jFb:-LXPrTTG79Wf55EcIH_P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b35443354fea40b55a795413fb2836bb84ee4e3/pkg/sql/txn_state.go#L318)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

reuse the error from package `tree`.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/txn.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXPNwZF0aXSxsQK_Thn:-LXPrUKj0awM4wBpgWVi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b35443354fea40b55a795413fb2836bb84ee4e3/pkg/sql/sem/tree/txn.go#L131)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

export this error and use it from `sql`.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
> Reviewed 9 of 14 files at r1, 2 of 6 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @knz)

___
*[pkg/sql/conn_executor_exec.go, line 1050 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRHp8f-oBa1F3dJuwV:-LXRHp8f-oBa1F3dJuwW:b-ddsfaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_executor_exec.go#L1050)):*
> ```Go
> }
> 
> // beginTransactionTimestampsAndReadMode computes the timestamps and
> ```

Specify what these timestamps are.
___
*[pkg/sql/conn_executor_exec.go, line 1073 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRI6pwCmuwPU0408ni:-LXRI6pwCmuwPU0408nj:bj83j8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_executor_exec.go#L1073)):*
> ```Go
> 		return time.Time{}, nil, 0, err
> 	}
> 	return ts.GoTime(), &ts, tree.ReadOnly, nil
> ```

We determine the `tree.ReadWriteMode` based on the AOST expr in a few places. I think it's needed in `setTransactionModes`, but is this one redundant with `noTxnToOpen`?
___
*[pkg/sql/conn_executor_exec.go, line 1116 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRH-0F-1g4nwFLGqd5:-LXRH-0F-1g4nwFLGqd6:b-qyk4yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_executor_exec.go#L1116)):*
> ```Go
> 				mode,
> 				ex.server.cfg.Clock.PhysicalTime(),
> 				nil, /* historicalTimestamp */
> ```

Add a note that this will be adjusted if necessary when executing the statement.
___
*[pkg/sql/conn_fsm.go, line 133 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXREBH2ArtIAnx3qNgY:-LXREBH2ArtIAnx3qNgZ:b5jfdgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_fsm.go#L133)):*
> ```Go
> 	txnSQLTimestamp     time.Time
> 	readOnly            tree.ReadWriteMode
> 	historicalTimestamp *hlc.Timestamp
> ```

nit: put these in the same order as they're taken by `resetForNewSQLTxn`.
___
*[pkg/sql/conn_fsm.go, line 449 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXREmab7iNv0OBWaVzo:-LXREmab7iNv0OBWaVzp:bwyq72w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_fsm.go#L449)):*
> ```Go
> 					explicitTxn,
> 					payload.txnSQLTimestamp,
> 					nil, /* historicalTimestamp */
> ```

Why don't we want to preserve the historical timestamp across SQL rollbacks? Let's add a rest for this.
___
*[pkg/sql/logictest/testdata/logic_test/txn_as_of, line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRLo8I-s-BkfNJALv4:-LXRLo8I-s-BkfNJALv5:bxypnmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/logictest/testdata/logic_test/txn_as_of#L126)):*
> ```
> 
> statement error pq: AS OF SYSTEM TIME specified with READ WRITE mode
> BEGIN AS OF SYSTEM TIME '-1h'; SET TRANSACTION READ WRITE;
> ```

Looks like we're missing a few cases like this. For instance, both in the BEGIN statement, both in the SET statement, etc.
___
*[pkg/sql/sem/tree/txn.go, line 121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRJyUi0svI55XEmotv:-LXRJyUi0svI55XEmotw:b-az7th6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/sem/tree/txn.go#L121)):*
> ```
> ctx.Printf("%s ", sep)
> ```

`ctx.WriteString(sep)`

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @nvanbenschoten)

___
*[pkg/sql/conn_executor_exec.go, line 1073 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRI6pwCmuwPU0408ni:-LXRUkwe-CU9qe0HMqZL:bfgcx6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_executor_exec.go#L1073)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We determine the `tree.ReadWriteMode` based on the AOST expr in a few places. I think it's needed in `setTransactionModes`, but is this one redundant with `noTxnToOpen`?
</blockquote></details>

noTxnToOpen just passes along the payload value. The code here is a little clever in that it doesn't need to check for an error here because if `s.Modes.ReadWriteMode` were `ReadWrite` we already would have returned an error inside the Merge call in the parser. I can add a defensive check just so we aren't so coupled to the parser implementation as well as a comment.

It does seem to be the case that the conditional in `resetForNewSQLTxn` that checked if the mode was Unresolved was too unnecessary.
___
*[pkg/sql/conn_executor_exec.go, line 1116 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRH-0F-1g4nwFLGqd5:-LXRVVtH7G2tpjCxb65a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_executor_exec.go#L1116)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a note that this will be adjusted if necessary when executing the statement.
</blockquote></details>

Done.
___
*[pkg/sql/conn_fsm.go, line 133 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXREBH2ArtIAnx3qNgY:-LXR_g4a4bqBj0systeQ:bra8282) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_fsm.go#L133)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: put these in the same order as they're taken by `resetForNewSQLTxn`.
</blockquote></details>

Done. Also moved the call to `readWriteModeWithSessionDefault` up into this method.
___
*[pkg/sql/conn_fsm.go, line 449 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXREmab7iNv0OBWaVzo:-LXRa7ZnCpjJEYOXvKvG:b-bzyv3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_fsm.go#L449)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why don't we want to preserve the historical timestamp across SQL rollbacks? Let's add a rest for this.
</blockquote></details>

Interesting point. This potentially feels like an academic case given that read-only transactions (which all historical ones are) shouldn't enter the aborted state (right?). I honestly did not really know much about these SAVEPOINTs, I added some logic tests to those. I also added a unit test for this specific transition though it required implementing `SetFixedTimestamp` for the `MockTransactionalSender`.
___
*[pkg/sql/logictest/testdata/logic_test/txn_as_of, line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRLo8I-s-BkfNJALv4:-LXRb8IG-I_ez3uItspD:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/logictest/testdata/logic_test/txn_as_of#L126)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like we're missing a few cases like this. For instance, both in the BEGIN statement, both in the SET statement, etc.
</blockquote></details>

Done. 
___
*[pkg/sql/sem/tree/txn.go, line 121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRJyUi0svI55XEmotv:-LXRgr91-oQFNS-O8-5C:b-80tlqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/sem/tree/txn.go#L121)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> ctx.Printf("%s ", sep)
> ```

`ctx.WriteString(sep)`
</blockquote></details>

Sure.

**Review by nvb — COMMENTED** [review]
:lgtm: from my side once the last two comments are addressed.

> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-:-LXUEr_QCnEAZqSqChm9:b-4bcss9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @nvanbenschoten)

___
*[pkg/sql/conn_fsm.go, line 449 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXREmab7iNv0OBWaVzo:-LXUDjs80a9yvtjFNUl5:b9jqyhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_fsm.go#L449)):*
> given that read-only transactions (which all historical ones are) shouldn't enter the aborted state (right?)

The KV transaction associated with a read-only transaction should never enter the aborted state, but the `stateAborted` state corresponds to more than just the KV transaction. I believe we enter it from any SQL error (for instance, a syntax error).

Also FWIW, I don't think the test cases you added are going through this state transition, because they're starting in the `stateOpen{ImplicitTxn: False, RetryIntent: True}` state.
___
*[pkg/sql/sem/tree/txn.go, line 121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRJyUi0svI55XEmotv:-LXUEjFM08R0od-YHJOF:bm3sbb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/sem/tree/txn.go#L121)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

Looks like this was missed. Not super important, but it avoids an allocation.

**Review by knz — APPROVED** [review]
:lgtm: modulo extension of the commit message to explain the new SQL timestamp behavior.
Maybe turn that part into a (separate, additional) release note.

> Reviewed 1 of 5 files at r3, 4 of 6 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-:-LXV1a4dBO8j9o8mQ4I5:btg5xrb)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andreimatei)

___
*[pkg/sql/conn_executor.go, line 1755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXPNH6n24deBWJIpIt8:-LXV1Fpz9fumm7k68HP6:blg48s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b35443354fea40b55a795413fb2836bb84ee4e3/pkg/sql/conn_executor.go#L1755)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Before this change calls to `now()` or `current_timetsamp()` would reflect the timestamp from the `BEGIN` rather than the timestamp set here. This sqlTimestamp in subsequent statements propagates to the TxnTimstamp in the EvalContext. The previous behavior was that transactions which had an AS OF from BEGIN would use that as their transaction time whereas those with a SET TRANSACTION would not. This asymmetry seems certainly wrong. While responding to this comment I went to add logic tests to ensure the behavior matches my expectation and it now does but in the process I discovered that the below query does not match my expectation (though is straightforward to fix). 

```
SELECT * FROM (SELECT now()) AS OF SYSTEM TIME '2019-01-01';                                                                                                             
                now                 
+----------------------------------+
  2019-01-29 16:28:59.039533+00:00  
```
Where I'd expect
```
SELECT * FROM (SELECT now()) AS OF SYSTEM TIME '2019-01-01';                                                                                                             
                now                 
+----------------------------------+
  2019-01-01 00:00:00.000000+00:00  
```

The reason this is the case is that sqlTimestamp gets used to create the TxnTimestamp when resetting or constructing the planner which happens just before we were setting this timestamp for the implicit transaction case. I spoke to Andrei for a bit about it this morning and we concluded that the current behavior is bad. I've now added an additional call to update the TxnTimestamp in the implicit transaction case as well and created logical tests for all three to demonstrate that the behavior of `now()` is consistent.
</blockquote></details>

Excellent explanation thanks. Please propagate it to the commit message.
___
*[pkg/sql/conn_executor_exec.go, line 1056 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXV1KzT9TvxINgd9ATb:-LXV1KzT9TvxINgd9ATc:brhwt3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc039dcef5f3a8aecfad1af779ca7ffc9b96e158/pkg/sql/conn_executor_exec.go#L1056)):*
> ```Go
> // if it exists. The timestamps correspond to the timestamps passed to
> // makeEventTxnStartPayload; txnSQLTimestamp propagates to become the
> // TxnTimestamp while historicalTimestamp is optionally populated if s carries
> ```

"if s carries"?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @knz)

___
*[pkg/sql/conn_executor.go, line 1755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXPNH6n24deBWJIpIt8:-LXVlKz0CHQ-mIH8kVvs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b35443354fea40b55a795413fb2836bb84ee4e3/pkg/sql/conn_executor.go#L1755)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Excellent explanation thanks. Please propagate it to the commit message.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_exec.go, line 1056 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXV1KzT9TvxINgd9ATb:-LXVlOiDBFQIw4cgiCcD:b-6cqewz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc039dcef5f3a8aecfad1af779ca7ffc9b96e158/pkg/sql/conn_executor_exec.go#L1056)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"if s carries"? 
</blockquote></details>

`s` being the argument name for the BeginTransaction statement. Clarified the comment. 
___
*[pkg/sql/conn_fsm.go, line 449 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXREmab7iNv0OBWaVzo:-LXUPaYmBYo30lZWUHVp:b3b89xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/conn_fsm.go#L449)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> given that read-only transactions (which all historical ones are) shouldn't enter the aborted state (right?)

The KV transaction associated with a read-only transaction should never enter the aborted state, but the `stateAborted` state corresponds to more than just the KV transaction. I believe we enter it from any SQL error (for instance, a syntax error).

Also FWIW, I don't think the test cases you added are going through this state transition, because they're starting in the `stateOpen{ImplicitTxn: False, RetryIntent: True}` state.
</blockquote></details>

The test does hit this case. I singled it out and ran a coverage report to verify.

Each case has an init function which for this case is:

```
668      init: func() (State, *txnState, error) {                                                                                                                                                                  
669        s, ts := testCon.createAbortedState(retryIntentSet)                                                                                                                                                     
670        return s, ts, nil                                                                                                                                                                                       
671      },      
```

That being said it was lame in so far as it didn't verify the timestamp but it does now.
___
*[pkg/sql/sem/tree/txn.go, line 121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34305#-LXRJyUi0svI55XEmotv:-LXUO5VQ4CkfOQo3Tl4a:b-yo6azb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64ead780306a359de674aceafe0212d417bf48d/pkg/sql/sem/tree/txn.go#L121)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like this was missed. Not super important, but it avoids an allocation.
</blockquote></details>

Gah, sloppy, sorry

**Review by knz — COMMENTED** [review]
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34305)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei)

**Pull request merged**
