### PR TITLE
pkg/storage: enable EFOS, excise on snapshot, ingest splitting

### LINKED ISSUE #115432: storage: enable excise-on-snapshot and EFOS by default
We have two cluster settings:
- `storage.experimental.eventually_file_only_snapshots.enabled`,
- `kv.snapshot_receiver.excise.enabled`,
- `storage.ingest_split.enabled`.

All are disabled by default in 23.2.

Change the defaults to `true` on `master`.

Jira issue: CRDB-34032

### PR DESCRIPTION
**Pull request by itsbilal**
The following three cluster settings were introduced in the 23.2 cycle, and are disabled by default in that release:

- `storage.experimental.eventually_file_only_snapshots.enabled`,
- `kv.snapshot_receiver.excise.enabled`,
- `storage.ingest_split.enabled`.

Enable all three by default, in preparation for 24.1.

Fixes #115432.

Release note: None.

### CODE REVIEW

**Comment by itsbilal** [comment]
This PR supersedes #116330.

**Review by nicktrav — APPROVED** [review]
Thanks!

**Comment by itsbilal** [comment]
TFTR!

bors r=nicktrav

**Comment by RaduBerinde** [comment]
Looks like this change affected BenchmarkFKInsert, BenchmarkResolveFunction, BenchmarkSequenceIncrement significantly (https://github.com/cockroachdb/cockroach/issues/117494). Are any of these regressions expected?

**Comment by jbowens** [comment]
That sounds very unexpected. Are reads of virtual sstables slower?

**Comment by itsbilal** [comment]
It does sound unexpected on the surface, but I notice that all these benchmarks do a `defer cluster.Stopper().Stop()` that is getting timed by the benchmark. Is it possible that we're waiting for the consistency queue to empty out before we close the cluster? In that case the move to EFOS would explain the difference. However it seems non-ideal to have that timed by the benchmark to begin with.

**Comment by jbowens** [comment]
> It does sound unexpected on the surface, but I notice that all these benchmarks do a defer cluster.Stopper().Stop() that is getting timed by the benchmark. Is it possible that we're waiting for the consistency queue to empty out before we close the cluster? In that case the move to EFOS would explain the difference. However it seems non-ideal to have that timed by the benchmark to begin with.

Good catch.

**Pull request merged**
