### PR TITLE
ui: add warning to network page when unavailable

### PR DESCRIPTION
**Pull request by stevendanna**
The network page doesn't work inside a virtual cluster yet.  Rather than just presenting a spinner, here we add a warning to the page. Additionally, it simplifies the text of the warning
presented on the Advanced Debug page.

Informs #115022

Screenshot 2023-12-06 at 16 09 16

Screenshot 2023-12-06 at 16 09 33

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
Hey Steven, it's common for PRs with UI changes to add a screenshot (or video when appropriate) of the changes, to make approval for the design itself easier

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115689#-:-Nkz_YEB6Pp4F02X4tEb:b-m3k1d3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115689)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @stevendanna)

___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/network/index.tsx` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115689#-NkzaVUJ3sMQE_KIQGkz:-NkzaVUJ3sMQE_KIQGl-:b1hcxxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/af1abe0b73681db1727d20869ae888cb2750eaa1/pkg/ui/workspaces/db-console/src/views/reports/containers/network/index.tsx#L466)):*
> ```XML
>           <section className="section">
>             <InlineAlert
>               title="The network page is only available via the sytem interface."
> ```

nit: system

**Review by stevendanna — COMMENTED** [review]
Cool, screenshots added for the two pages this changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115689#-:-NkztTD20PSY_UafcgLv:b5gg1he)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/network/index.tsx` line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115689#-NkzaVUJ3sMQE_KIQGkz:-NkztRPD1XZLPvt6Se4q:b-a6taqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/af1abe0b73681db1727d20869ae888cb2750eaa1/pkg/ui/workspaces/db-console/src/views/reports/containers/network/index.tsx#L466)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: system
</blockquote></details>

Thanks! Fixed.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115689#-:-NkzzTeVA7BB8hqkkRrm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by stevendanna** [comment]
blathers backport 23.2 23.2.0-rc

**Pull request merged**
