### PR TITLE
clusterversion: introduce version key for `crdb_internal.cluster_locks`

### PR DESCRIPTION
**Pull request by AlexTalks**
This change adds a new cluster version to enable usage of the virtual
table `crdb_internal.cluster_locks`, so that we can disable usage of new
KV `QueryLocksRequest` API on cluster versions prior to 22.1.

Release note: None

Release justification: introduces a new cluster version without any
logic changes

### CODE REVIEW

**Review by aayushshah15 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78532#-:-Mz2luVk9NvccBJmsfHd:bfsmuih)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78532)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks and @rafiss)

___
*[pkg/clusterversion/cockroach_versions.go, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78532#-Mz8IU6_3ywGTn76bqad:-Mz8IU6_3ywGTn76bqae:b86fmhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6621bc6542960261aa36e136f4515c1a7098b332/pkg/clusterversion/cockroach_versions.go#L544)):*
> ```Go
> 		Key:     DateStyleIntervalStyleCastRewrite,
> 		Version: roachpb.Version{Major: 21, Minor: 2, Internal: 94},
> 	},
> ```

you'll also need to add the key here (with `major=21`, `minor=2`, and `internal` 2 more than the last one.

@aayushshah15 i just noticed that you didn't add the version for `EnableNewStoreRebalancer` in https://github.com/cockroachdb/cockroach/pull/78334 -- was that intentional?

**Comment by aayushshah15** [comment]
___
*[pkg/clusterversion/cockroach_versions.go, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78532#-Mz8IU6_3ywGTn76bqad:-Mz8JrAk3iCCpCyO5116:b-4erd45) ([raw file](https://github.com/cockroachdb/cockroach/blob/6621bc6542960261aa36e136f4515c1a7098b332/pkg/clusterversion/cockroach_versions.go#L544)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

you'll also need to add the key here (with `major=21`, `minor=2`, and `internal` 2 more than the last one.

@aayushshah15 i just noticed that you didn't add the version for `EnableNewStoreRebalancer` in https://github.com/cockroachdb/cockroach/pull/78334 -- was that intentional?
</blockquote></details>

That's my bad. Thanks for noticing. I've fixed it here if you don't mind stamping: https://github.com/cockroachdb/cockroach/pull/78566

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78532)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @rafiss)

___
*[pkg/clusterversion/cockroach_versions.go, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78532#-Mz8IU6_3ywGTn76bqad:-MzHCWt005rCOzz47M3C:bq01roy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6621bc6542960261aa36e136f4515c1a7098b332/pkg/clusterversion/cockroach_versions.go#L544)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

That's my bad. Thanks for noticing. I've fixed it here if you don't mind stamping: https://github.com/cockroachdb/cockroach/pull/78566
</blockquote></details>

Done - Thanks for calling this out!  Sorry I didn't do that correctly (I had based it off of @aayushshah15 which also missed it).

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78532#-:-MzHFEbc-3CgFUaqBgj_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78532)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)

**Pull request merged**
