### PR TITLE
scripts: make the release note extraction script search for common parent

### LINKED ISSUE #21815: release note extraction should provide guidance on forks
So the following command fails:

`release-notes.py --from v2.0-alpha.20180122 --until master`

Because the tagged release is not an ancestor of the "until" branch:

schermafdruk_2018-01-26_11-45-58

**In general** it is unsound / meaningless to try to determine a history between the tip of one branch and the tip of another branch. There is no code history from one to the other. 

The solution to the particular error encountered above was to manually determine what was the common parent commit and search from there. Maybe this can be automated.

Requested by @jseldess / @Amruta-Ranade

### PR DESCRIPTION
**Pull request by knz**
Fixes #21815. Requested by @jseldess and @Amruta-Ranade. 

Prior to this patch:

```
% python3 scripts/release-notes.py --from v2.0-alpha.20180122 --until bae7465a3
error: origin commit v2.0-alpha.20180122 not in history of bae7465a3160d68594613cc709ba3f05c12ee40f
```

After this patch:

```
% python3 scripts/release-notes.py --from v2.0-alpha.20180122 --until bae7465a3
warning: v2.0-alpha.20180122 is not an ancestor of bae7465a3!

The first common ancestor is 9da836000c7cc1ca058a4082a80c741c942b58c3,
which is 1 commits older than v2.0-alpha.20180122 and 2 days older. Using that as origin.

Changes 9da836000c7cc1ca058a4082a80c741c942b58c3 ... bae7465a3160d68594613cc709ba3f05c12ee40f
...
```

If someone makes a mistake and attempts to extract release notes for unreleated branches, the commit count and age to the common parent should outline the problem:
```
% python3 scripts/release-notes.py --from v2.0-alpha.20180122 --until v1.1.4
warning: v2.0-alpha.20180122 is not an ancestor of v1.1.4!

The first common ancestor is 8633ca46d53c987b229562c0652694c53f3bae79,
which is 3461 commits older than v2.0-alpha.20180122 and 140 days older. Using that as origin.

```

### CODE REVIEW

**Comment by knz** [comment]
I want to highlight this is a somewhat abnormal case. I'm not sure it's good practice to fork branches on a release branch to tag.

**Review by benesch — APPROVED** [review]
LGTM!

I don't think this case is *that* abnormal. It comes up whenever we have a known bug with a fix that we want to backport to the currently-deployed alpha. Usually we scuttle the release, but in this case we'd gone several weeks without an alpha. I can definitely see that happening again.

It'll also come up when generating release notes from, say, v1.1.4 to v2.0.0.

**Comment by knz** [comment]
> It'll also come up when generating release notes from, say, v1.1.4 to v2.0.0.

Ugh that's an entirely different problem. In that case the common ancestor is something back in May 2016. We'd need to ignore all the release notes that have made it to both branches somehow.

**Comment by benesch** [comment]
> Ugh that's an entirely different problem. In that case the common ancestor is something back in May 2016. We'd need to ignore all the release notes that have made it to both branches somehow.

We also want to transform releases notes like "sequences now support features x, y, and z" into one overall release note like "SQL sequences are now supported." I think we'll just have to do that manually, but having the ability to generate all possible release notes will be a nice place to start.

**Pull request merged**
