### PR TITLE
status: add network packet dropped and error metrics

### LINKED ISSUE #115458: kv: add network errors and drops metrics
Cockroach currently exposes network IO stats using `gopsutil/net` library, which exports [these IO counters](https://pkg.go.dev/github.com/shirou/gopsutil/net#IOCountersStat) after reading from `/proc/net/dev`. This code in CRDB which uses this library is around here:
https://github.com/cockroachdb/cockroach/blob/146b425eea85d8cc8dc113b5758819609bb021bb/pkg/server/status/runtime.go#L556-L559

We don't currently make use of all counters.

For the sake of network debugging, we should expose the following four metrics, pulling from their corresponding fields:
- `sys.host.net.recv.err`
- `sys.host.net.recv.drop`
- `sys.host.net.send.err`
- `sys.host.net.send.drop`

We can then add some new graphs to the `Network` dashboard in the debug console.

Jira issue: CRDB-34046

Epic CRDB-34227

### PR DESCRIPTION
**Pull request by lyang24**
This commit adds packet drop/error counter on network's sending and receiving end. These metrics are derived from the os and aims for better observability on tail latencies.

The second added chart looks like below for number of packets, packets error, and packets dropped on sending and receiving end.

Screenshot 2023-12-13 at 4 49 11 PM

Fixes: #115458

Release note(ui change): the DB Console metrics dashboard's Networking tab is
enhanced with charts that visualize number of packets received, number of
receiving packets with error, number of receiving packets got dropped, number
of packets sent, number of sending packets with error, and number of sending
packets got dropped.

### CODE REVIEW

**Comment by lyang24** [comment]
looks like we can mimic network [bytes](https://github.com/cockroachdb/cockroach/blob/e747f6e6857a19d6048cb184b0f55c52cb8a6390/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L28)  graph and add graphs on packets dropped and packets error even total number of packet received.

what are the best place to write test with new metrics?

**Review by nvb — COMMENTED** [review]
> looks like we can mimic network [bytes](https://github.com/cockroachdb/cockroach/blob/e747f6e6857a19d6048cb184b0f55c52cb8a6390/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L28) graph and add graphs on packets dropped and packets error even total number of packet received as commit 2.

:thumbsup: 

> what are the best place to write test with new metrics?

I'm not sure that we have a great testing story for metrics, beyond the two unit tests that I pointed you at.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-:-NlPEmEb0-hyVSSHzhGK:b-7ivppj)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @lyang24)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-NlPBKl20myMG51ld-Kf):*
s/aims/aim/
___
*[`pkg/server/status/runtime.go` line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-NlPB1RpEzGA1h9iE9hK:-NlPB1RpEzGA1h9iE9hL:bcnyrkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e374eaed21499d6d619e750bab4df965eff2b40/pkg/server/status/runtime.go#L236)):*
> ```Go
> 		Help:        "Bytes received on all network interfaces since this process started (as reported by the OS)",
> 	}
> 	metaHostNetRecvDrop = metric.Metadata{
> ```

Here and throughout this PR: let's keep a consistent ordering when manipulating the metrics:
- recv.bytes
- recv.packets
- recv.err
- recv.drop
- send.bytes
- send.packets
- send.err
- send.drop
___
*[`pkg/server/status/runtime.go` line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-NlPBFUrDQKrrT1uA0O5:-NlPBFUrDQKrrT1uA0O6:b-kfw8et) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e374eaed21499d6d619e750bab4df965eff2b40/pkg/server/status/runtime.go#L238)):*
> ```Go
> 	metaHostNetRecvDrop = metric.Metadata{
> 		Name:        "sys.host.net.recv.drop",
> 		Unit:        metric.Unit_BYTES,
> ```

The unit for all of these is `COUNT`.
___
*[`pkg/server/status/runtime.go` line 811 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-NlPAiD9EUkrIMhRpJ7O:-NlPAiD9EUkrIMhRpJ7P:bkwy03e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e374eaed21499d6d619e750bab4df965eff2b40/pkg/server/status/runtime.go#L811)):*
> ```Go
> 		output.BytesSent += counter.BytesSent
> 		output.PacketsRecv += counter.PacketsRecv
> 		output.PacketsSent += counter.PacketsSent
> ```

Do we need to adjust this function as well? And then add to `TestSumNetCounters`.
___
*[`pkg/server/status/runtime.go` line 823 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-NlPBoeU0SWLarOTxQX_:-NlPBoeU0SWLarOTxQXa:b-wezpuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e374eaed21499d6d619e750bab4df965eff2b40/pkg/server/status/runtime.go#L823)):*
> ```Go
> 	from.PacketsRecv -= sub.PacketsRecv
> 	from.PacketsSent -= sub.PacketsSent
> 	from.Errin -= sub.Errin
> ```

We can add testing to `TestSubtractNetCounters`.

**Review by lyang24 — COMMENTED** [review]
Thanks for the feedback, I have fixed all the issues and double checked the code. Looking forward for more early feedbacks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-:-NlReePjBbFdf2Oepb2I:b-2hvws8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by lyang24** [comment]
This is not as easy as i thought :( need to figure out how `pkg/ui/workspaces/db-console/eslint.sh` works, turning this back to a draft

**Comment by lyang24** [comment]
I configured the eslint on my Goland and fixed the template lint issues, it should be ready to review now.

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116005)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @lyang24)

___
*[`pkg/server/status/runtime.go` line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-NlPB1RpEzGA1h9iE9hK:-Nl_-ibfEUpcEqqfI6Td:boeoytp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e374eaed21499d6d619e750bab4df965eff2b40/pkg/server/status/runtime.go#L236)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Here and throughout this PR: let's keep a consistent ordering when manipulating the metrics:
- recv.bytes
- recv.packets
- recv.err
- recv.drop
- send.bytes
- send.packets
- send.err
- send.drop
</blockquote></details>

nit: `metaHostNetRecvDrop` still needs to be moved down.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx` line 57 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-Nl_1aQN-p9NJ_R73Fpd:-Nl_1aQN-p9NJ_R73Fpe:b6z9vmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f608812b8abf814aa7678d05da0225575cd25e31/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L57)):*
> ```XML
> 
>     <LineGraph
>       title="Network Packets Received With Error"
> ```

nit: "Network Packet Errors on Receive"
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx` line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-Nl_1FEw0yo-kTNFFpz1:-Nl_1FEw0yo-kTNFFpz2:b-op4ggq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f608812b8abf814aa7678d05da0225575cd25e31/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L74)):*
> ```XML
> 
>     <LineGraph
>       title="Network Receiving Packets Dropped"
> ```

nit: "Network Packet Drops on Receive"
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx` line 119 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-Nl_1fOC5zqZS_8PRDpx:-Nl_1fOC5zqZS_8PRDpy:bt43g28) ([raw file](https://github.com/cockroachdb/cockroach/blob/f608812b8abf814aa7678d05da0225575cd25e31/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L119)):*
> ```XML
> 
>     <LineGraph
>       title="Network Packets Sent With Error"
> ```

nit: "Network Packet Errors on Send"
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx` line 136 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-Nl_1NGk-CxBHkO3NGsh:-Nl_1NGk-CxBHkO3NGsi:b-k1y425) ([raw file](https://github.com/cockroachdb/cockroach/blob/f608812b8abf814aa7678d05da0225575cd25e31/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L136)):*
> ```XML
> 
>     <LineGraph
>       title="Network Sending Packets Dropped"
> ```

nit: "Network Packet Drops on Send"

**Review by lyang24 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116005)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @nvanbenschoten)

___
*[`pkg/server/status/runtime.go` line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-NlPB1RpEzGA1h9iE9hK:-Nlarp7E4qbmbojGiDtG:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e374eaed21499d6d619e750bab4df965eff2b40/pkg/server/status/runtime.go#L236)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `metaHostNetRecvDrop` still needs to be moved down.
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm:

bors r=nvanbenschoten

> Reviewed 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116005#-:-NlcXtdc8o8K3VfKZ0gi:b-qdhl0k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Comment by lyang24** [comment]
Hi @nvanbenschoten, it is possible to back port this commit to v23.1? The reason why i am asking is many of our support issues are suspected to be network related this might save debugging time from both side.

**Comment by nvanbenschoten** [comment]
Hi @lyang24, yes, we can backport this to v23.1. We'll just need to keep in mind that this is only exposing some forms of network errors.

blathers backport 23.2

blathers backport 23.1

**Comment by nvanbenschoten** [comment]
I'll need to do this manually.

**Pull request merged**
