### PR TITLE
distsql: support filtering inside aggregations

### PR DESCRIPTION
**Pull request by RaduBerinde**

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Don't leave a bro hanging.

**Comment by arjunravinarayan** [comment]
Shame cube, I'm so sorry. I lost track of things with the trip to SF. On it now.
https://media1.giphy.com/media/pEjnnil9lLrUc/giphy.gif

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15865#-KkC7ucbUvIh0dL16LRh:-KkC7ucbUvIh0dL16LRi:b-br7dlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8750441d09b29a92b7fabf6fbe118999dcab952c/pkg/sql/distsqlrun/aggregator.go#L116)):*
> ```Go
> 	for i, aggInfo := range spec.Aggregations {
> 		if aggInfo.FilterColIdx != nil {
> 			t := inputTypes[*aggInfo.FilterColIdx].Kind
> ```

if you're checking the type, wanna also check that the index is in range?

---

*[pkg/sql/distsqlrun/processors.proto, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15865#-KkC8LJE422yVjIw_h9U:-KkC8LJE422yVjIw_h9V:bgk71wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8750441d09b29a92b7fabf6fbe118999dcab952c/pkg/sql/distsqlrun/processors.proto#L328)):*
> ```protobuf
> 
>     // If set, this column index specifies a boolean argument; rows for which
>     // this value is not true don't contribute to this aggregation.
> ```

I'd give a hint about the SQL feature that this is used for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15865#-:-KkC9-1kfVV1hRUau4pc:bnfp4nl)*

**Comment by arjunravinarayan** [comment]
:lgtm:
The flow_diagram.go could use an update with some parentheses and commas for the table reader. "Render: @4 @1 + @2 @1 < @4 @1 = @3" for example is unreadable, and is only something we're seeing now that we're generating boolean conditionals all over the place for use by the Aggregator with FILTER.

---

Reviewed 5 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/processors.proto, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15865#-KkC8LJE422yVjIw_h9U:-KkCBjHMfUZcjMtSRfSW:b-dplhu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8750441d09b29a92b7fabf6fbe118999dcab952c/pkg/sql/distsqlrun/processors.proto#L328)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd give a hint about the SQL feature that this is used for.
</blockquote></details>

I don't think it's really necessary. The word "filter" is used in the variable name, but your call...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15865#-:-KkCAiumYcMfn2DORFfk:b-ol0bgy)*

**Comment by RaduBerinde** [comment]
TFTRs!

Arjun, that is a fair observation. I will do that in a separate PR though (I want to separate the churn in the testfiles).

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15865#-KkC7ucbUvIh0dL16LRh:-KkCkugqEdQ3CrI4yQqi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8750441d09b29a92b7fabf6fbe118999dcab952c/pkg/sql/distsqlrun/aggregator.go#L116)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if you're checking the type, wanna also check that the index is in range?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.proto, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15865#-KkC8LJE422yVjIw_h9U:-KkCl_1gD3EqbTz0QmjK:b36tte5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8750441d09b29a92b7fabf6fbe118999dcab952c/pkg/sql/distsqlrun/processors.proto#L328)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I don't think it's really necessary. The word "filter" is used in the variable name, but your call...
</blockquote></details>

Added, can't hurt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15865#-:-KkCkQ4B251zdgNPkJlh:bf6tnzk)*

**Pull request merged**
