### PR TITLE
norm: push Select into UniqueKeyExpr

### LINKED ISSUE #109751: Optimizer picks slow full scan on PK when other indexes are available
**Describe the problem**
A join query using lateral joins always does a full scan against the large table, even when constrained index scans are possible. Adding an extra column to the SELECT list of one of the lateral joins somehow allows the optimizer to do constrained index scan.
This issue is opened to investigate the reason for this and see if the optimizer can be taught to use constrained scan, even when that extra column is not selected.

**To Reproduce**
```sql
DROP TABLE IF EXISTS trm;
CREATE TABLE trm (
        id UUID NOT NULL DEFAULT gen_random_uuid(),
        trid UUID NOT NULL,
        data JSONB NOT NULL,
        ts11 TIMESTAMP NOT NULL,
        ts12 TIMESTAMP NOT NULL,
        CONSTRAINT "primary" PRIMARY KEY (id ASC)
);

DROP TABLE IF EXISTS trrec;
CREATE TABLE trrec (
        id UUID NOT NULL DEFAULT gen_random_uuid(),
        uuid1 UUID NOT NULL,
        trid STRING NOT NULL,
        trcol1 STRING NOT NULL,
        str1 STRING NOT NULL,
        ts2 TIMESTAMP NOT NULL,
        ts3 TIMESTAMP NULL,
        ts11 TIMESTAMP NOT NULL,
        ts12 TIMESTAMP NOT NULL,
        str3 STRING NOT NULL DEFAULT '':::STRING,
        str16 STRING NULL,
        CONSTRAINT "primary" PRIMARY KEY (id ASC),
        INDEX trrec_idx5 (str16 ASC) STORING (uuid1)
);

DROP TABLE IF EXISTS trtab4;
CREATE TABLE trtab4 (
        id UUID NOT NULL DEFAULT gen_random_uuid(),
        uuid1 UUID NOT NULL,
        trid UUID NOT NULL,
        str4 STRING NOT NULL,
        dec1 DECIMAL(19,2) NOT NULL,
        str5 STRING NOT NULL,
        bool1 BOOL NOT NULL,
        ts11 TIMESTAMP NOT NULL,
        ts12 TIMESTAMP NOT NULL,
        str7 STRING NULL,
        json9 JSONB NULL,
        CONSTRAINT "primary" PRIMARY KEY (id ASC)
);

-- Make the trrec table look large.  The optimizer should favor plans than can avoid full scan of this table.
ALTER TABLE trrec INJECT STATISTICS '[
    {
        "columns": [
            "id"
        ],
        "created_at": "2021-04-13 20:35:46.476858",
        "distinct_count": 1000000000,
        "name": "__auto__",
        "null_count": 0,
        "row_count": 1000000000
    }
]';
```
Query:
```sql
EXPLAIN(OPT)
WITH
  with2
    AS (
      SELECT
        r.uuid1,
        tq.trid,
        tq.dec1,
        tq.str5,
        tq.bool1,
        tq.ts12,
        tq.ts11,
        tq.str7
      FROM
        trrec AS r
        INNER JOIN trtab4 AS tq ON
            r.id = tq.trid
            AND r.str16 = '12345'
            AND tq.ts11 >= '2022-07-02 00:00:00'
            AND tq.ts11 <= '2023-09-19 00:00:00'
    )
SELECT
  tr.id,
  tr.trid,
  tr.trcol1
FROM
  trrec AS tr
  LEFT JOIN LATERAL (
      SELECT
        q.dec1, q.str5, q.bool1, q.ts12, q.str7
      FROM
        with2 AS q
      WHERE
        tr.id = q.trid
    )
      AS q ON true
  LEFT JOIN LATERAL (
      SELECT
        --tr.id, -- uncomment this line to get a good query plan
                 -- with no full scan on trrec
        m.ts12
      FROM
        trm AS m
      WHERE
        tr.id = m.trid
        AND m.ts11 >= '2022-07-02 00:00:00'
        AND m.ts11 <= '2023-09-19 00:00:00'
      ORDER BY
        m.ts11 DESC
      LIMIT
        1
    )
      AS val3 ON true
WHERE
  tr.str16 = '12345'
  AND tr.ts11 >= '2022-07-02 00:00:00'
  AND tr.ts11 <= '2023-09-19 00:00:00'
;
```
Bad query plan:
```
  project
   └── distinct-on
        ├── sort
        │    └── right-join (hash)
        │         ├── select
        │         │    ├── scan trm [as=m]
        │         │    └── filters
        │         │         └── (m.ts11 >= '2022-07-02 00:00:00') AND (m.ts11 <= '2023-09-19 00:00:00')
        │         ├── select
        │         │    ├── ordinality
        │         │    │    └── project
        │         │    │         └── left-join (merge)
        │         │    │              ├── scan trrec [as=tr]      -- this is the full scan that we don't want
        │         │    │              ├── sort
        │         │    │              │    └── project
        │         │    │              │         ├── inner-join (hash)
        │         │    │              │         │    ├── select
        │         │    │              │         │    │    ├── scan trtab4 [as=tq]
        │         │    │              │         │    │    └── filters
        │         │    │              │         │    │         └── (tq.ts11 >= '2022-07-02 00:00:00') AND (tq.ts11 <= '2023-09-19 00:00:00')
        │         │    │              │         │    ├── scan trrec@trrec_idx5 [as=r]
        │         │    │              │         │    │    └── constraint: /11/1: [/'12345' - /'12345']
        │         │    │              │         │    └── filters
        │         │    │              │         │         └── r.id = tq.trid
        │         │    │              │         └── projections
        │         │    │              │              └── tq.trid
        │         │    │              └── filters (true)
        │         │    └── filters
        │         │         ├── (tr.ts11 >= '2022-07-02 00:00:00') AND (tr.ts11 <= '2023-09-19 00:00:00')
        │         │         └── tr.str16 = '12345'
        │         └── filters
        │              └── tr.id = m.trid
        └── aggregations
             ├── const-agg
             │    └── tr.id
             ├── const-agg
             │    └── tr.trid
             └── const-agg
                  └── tr.trcol1
```
Good query plan:
```
  project
   └── distinct-on
        ├── sort
        │    └── right-join (hash)
        │         ├── select
        │         │    ├── scan trm [as=m]
        │         │    └── filters
        │         │         └── (m.ts11 >= '2022-07-02 00:00:00') AND (m.ts11 <= '2023-09-19 00:00:00')
        │         ├── ordinality
        │         │    └── right-join (hash)
        │         │         ├── project
        │         │         │    ├── inner-join (hash)
        │         │         │    │    ├── select
        │         │         │    │    │    ├── scan trtab4 [as=tq]
        │         │         │    │    │    └── filters
        │         │         │    │    │         └── (tq.ts11 >= '2022-07-02 00:00:00') AND (tq.ts11 <= '2023-09-19 00:00:00')
        │         │         │    │    ├── scan trrec@trrec_idx5 [as=r]
        │         │         │    │    │    └── constraint: /11/1: [/'12345' - /'12345']
        │         │         │    │    └── filters
        │         │         │    │         └── r.id = tq.trid
        │         │         │    └── projections
        │         │         │         └── tq.trid
        │         │         ├── select
        │         │         │    ├── index-join trrec
        │         │         │    │    └── scan trrec@trrec_idx5 [as=tr]
        │         │         │    │         └── constraint: /37/27: [/'12345' - /'12345']
        │         │         │    └── filters
        │         │         │         └── (tr.ts11 >= '2022-07-02 00:00:00') AND (tr.ts11 <= '2023-09-19 00:00:00')
        │         │         └── filters
        │         │              └── tr.id = trid
        │         └── filters
        │              └── tr.id = m.trid
        └── aggregations
             ├── const-agg
             │    └── tr.id
             ├── const-agg
             │    └── tr.trid
             └── const-agg
                  └── tr.trcol1
```

**Environment:**
 - CockroachDB version v23.1+ and below

**Additional context**
This issue is spawned from support issue https://github.com/cockroachlabs/support/issues/2567

Jira issue: CRDB-31078

### PR DESCRIPTION
**Pull request by msirek**
ops: add UniqueKeyExpr

This adds a `UniqueKeyExpr` which adds a column containing unique numbers
to any input. This is done to differentiate the operation added by
`EnsureKey`, which currently uses `OrdinalityExpr`, from a true
ordinality expression constructed for the WITH ORDINALITY SQL clause.
WITH ORDINALITY requires that rows receive a sequential numbering, and
the actual values returned matters, and if gotten wrong, means the query
returns incorrect results. This disallows certain operations from being
pushed into `OrdinalityExpr`, whereas `UniqueKeyExpr` should impose no
such restriction.

Informs: #109751

Release note: None

----
norm: push Select into UniqueKeyExpr

A join query with LIMIT 1 and a WHERE clause filter which could enable
constrained scan on a table index may perform a full scan the table,
and the optimizer may never consider query plans where the table is
read via a constrained index scan. Similar queries which project more
columns or expressions do consider constrained scans, because
normalization of the LIMIT portion of the query is delayed in that case
until the input to the LIMIT is a join expression.

The issue is that normalization rules such as TryDecorrelateLimitOne
inject a UniqueKey operation above a join, which prevents rules which
push a Select into a join from firing, such as PushSelectIntoJoinLeft,
which matches on a Select as the immediate parent of a join. The
expression tree may look like this:
```
├── select
│    ├── columns: tr.id:12!null tr.trid:13!null tr.str16:15!null rownum:25!null
│    ├── key: (25)
│    ├── fd: ()-->(15), (12)-->(13), (25)-->(12,13)
│    ├── unique-key
│    │    ├── columns: tr.id:12!null tr.trid:13!null tr.str16:15 rownum:25!null
│    │    ├── key: (25)
│    │    ├── fd: (12)-->(13,15), (25)-->(12,13,15)
│    │    └── project
│    │         ├── columns: tr.id:12!null tr.trid:13!null tr.str16:15
│    │         ├── fd: (12)-->(13,15)
│    │         └── left-join (hash)
│    │              ├── columns: tr.id:12!null tr.trid:13!null tr.str16:15 trid:18
│    │              ├── multiplicity: left-rows(one-or-more), right-rows(zero-or-one)
│    │              ├── fd: (12)-->(13,15)
│    │              ├── scan trrec [as=tr]
│    │              │    ├── columns: tr.id:12!null tr.trid:13!null tr.str16:15
│    │              │    ├── key: (12)
│    │              │    └── fd: (12)-->(13,15)
│    │              ├── project
│    │              │    ├── columns: trid:18!null
...
│    │              │    └── projections
│    │└── tq.trid:8 [as=trid:18, outer=(8)]
│    │              └── filters
│    │                   └── tr.id:12 = trid:18 [outer=(12,18), constraints=(/12: (/NULL - ]; /18: (/NULL - ]), fd=(12)==(18), (18)==(12)]
│    └── filters
│         └── tr.str16:15 = '12345' [outer=(15), constraints=(/15: [/'12345' - /'12345']; tight), fd=()-->(15)]
```

The `unique-key` expression, in this case, was created by normalization
rule TryDecorrelateLimitOne to tag rows with a unique identifier so
duplicates can be removed later. We should be able to push the `select`
below this `unique-key`, because besides adding the unique identifier, it
is just passing rows through to the next operation.

The solution is to do just that, introduce a new normalization rule
which pushes a Select operation below a UniqueKey operation which was
created for duplicate row removal if the selection filter applies to
columns in the UniqueKey expression's input.

Epic: none
Fixes: #109751

Release note (bug fix): This patch fixes a performance issue in join
queries with a LIMIT clause, where the optimizer may fail to push a
WHERE clause filter into a join due to how the Limit operation is
internally rewritten, causing a full scan of the table referenced in the
filter.

### CODE REVIEW

**Comment by michae2** [comment]
Nice fix! This makes complete sense.

Bikeshedding: I wonder if it would be worth making this a completely separate operator from `Ordinality` rather than distinguishing with a flag in the `OrdinalityPrivate`. Granted, the implementation is currently the same, but the logical purpose is different (assigning ordinals vs. "distinctifying" a set of rows) and I could imagine this "distinctifying" operator being implemented one day with unordered integers (similar to `unordered_unique_rowid`).

**Review by msirek — COMMENTED** [review]
Good idea. This PR would be backported, but maybe it's not too much of a change (and so still backportable) to use a different operator name for distinct row tagging.  The output from the execbuilder may still use the same operation node as currently (`ordinalityNode`), but this could be changed in the future.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-NdmDx465fzrIETLD3QO:b-7r0xy2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Review by DrewKimball — COMMENTED** [review]
This is a great find! Do you think it would be worth adding additional pushdown rules, say for Project and/or joins?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-Ne4ihfF-B9CgBZgFyOL:bdt2zuf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @msirek)

___
*[`pkg/sql/opt/ops/relational.opt` line 1230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-Ne4hjvr2cW79WLPZQic:-Ne4hjvr2cW79WLPZQid:b-el4kue) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac83bd837b2b0af588e4eea2026a253ae0165d8e/pkg/sql/opt/ops/relational.opt#L1230)):*
> ```
>     # `false` if this is built from a WITH ORDINALITY clause, where the value
>     # returned does matter.
>     ForDuplicateRemoval bool
> ```

Could we just use `Any` ordering instead? That would imply there are no guarantees on which ordinality values are associated with a given row, so I think the Select pushdown rule would be valid. I think the Limit pushdown rule already works with unordered Ordinality.

**Review by msirek — COMMENTED** [review]
I have implemented @michae2's idea of creating a new operator called UniqueKey for uniquely tagging rows. It still uses the ordinality operation in the execbuilder. Please take a look. Since this is for backport, I didn't want to make too many changes.

> Do you think it would be worth adding additional pushdown rules, say for Project and/or joins?

Yes! For sure a rule like `PushLimitIntoUniqueKey` could be added because there is already a `PushLimitIntoOrdinality`. Maybe a `HoistProjectFromUniqueKey` would also make sense. For rules surrounding joins (whether pushed or hoisted), maybe those couldn't be done depending on the semantics of the unique key being added, but in general I'd assume it's not safe.

In any case, since this PR is for backport, I'm not adding any additional rules to it. Potentially a `PushLimitIntoUniqueKey` could be backported, any maybe we'd want to include that in this PR since `PushLimitIntoOrdinality` is already there, but we'd have to find test cases specific to `UniqueKey`. I'm not sure there are any since a distinct operation is built over the `UniqueKey` and I don't think we can push a limit into a distinct.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-Ne9SXZO7U5RGzEaz6EP:bh22swi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/opt/ops/relational.opt` line 1230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-Ne4hjvr2cW79WLPZQic:-Ne9USoZEfkFR6K4E07j:b-9mmbs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac83bd837b2b0af588e4eea2026a253ae0165d8e/pkg/sql/opt/ops/relational.opt#L1230)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Could we just use `Any` ordering instead? That would imply there are no guarantees on which ordinality values are associated with a given row, so I think the Select pushdown rule would be valid. I think the Limit pushdown rule already works with unordered Ordinality.
</blockquote></details>

This has gone away with the latest refactoring to add a `UniqueKey` op.

**Comment by DrewKimball** [comment]
>I have implemented @michae2's idea of creating a new operator called UniqueKey for uniquely tagging rows. It still uses the ordinality operation in the execbuilder. Please take a look. Since this is for backport, I didn't want to make too many changes.

@michae2 how do you feel about using an unordered Ordinality operator for this? Were you mainly concerned with the `ForDuplicateRemoval` field changing the operator's behavior, or with using the Ordinality operator itself?

**Review by msirek — COMMENTED** [review]
Adding `UniqueKey` would allow row tagging to occur in parallel on different processors, so is a forward-looking change.  This wouldn't limit us from creating a `PushLimitIntoOrdinality` rule for unordered Ordinality as well, if we think that would be useful.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-Ne9iiopBTe6ydhfgIhY:b4z4p6i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

**Comment by mgartner** [comment]
Using an unordered Ordinality seems much simpler if it works. Did you try it?

> In any case, since this PR is for backport,

Is there a strong enough case to backport this? Backporting rules comes with a high risk, and while we've done it in the past I want to avoid doing it going forward unless absolutely necessary.

**Review by msirek — COMMENTED** [review]
> Using an unordered Ordinality seems much simpler if it works. Did you try it?

I haven't tried it, but it would probably work. I can switch back to the old fix (modified for unordered ordinality) if there's consensus on that. Maybe will wait for @michae2 to comment.

> Is there a strong enough case to backport this?

This is to fix a case found in a support issue, which has been communicated to the customer already. So, if we choose not to backport it, we'd have to let them know they'd need to wait for v23.2 for a fix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-NeAB1IX9VGuFRzBR7iP:b-pl28b9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

**Comment by mgartner** [comment]
> This is to fix a case found in a support issue, which has been communicated to the customer already. So, if we choose not to backport it, we'd have to let them know they'd need to wait for v23.2 for a fix.

It sounds like they have an acceptable work-around for now.

**Review by michae2 — COMMENTED** [review]
> [@michae2](https://github.com/michae2) how do you feel about using an unordered Ordinality operator for this? Were you mainly concerned with the `ForDuplicateRemoval` field changing the operator's behavior, or with using the Ordinality operator itself?

I was concerned with using the Ordinality operator itself. Creating a new operator is admittedly a little more work up front, but I think it will set us up better to (one day) have a different implementation that, as Mark points out, could be distributed, instead of the `ordinalityNode` we have today. Plus I think distinguishing on an operator level instead of a physical property level makes plans easier to read.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-NeAKJCQACG-rya5M7Qx:bcaa6w7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by michae2 — COMMENTED** [review]
> Reviewed 25 of 35 files at r3, 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @msirek)

___
*[`-- commits` line 86 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-NeBxouf7Aui7PoP85Z1):*
If we're not backporting this, then I don't think we need the setting.
___
*[`pkg/sql/opt/norm/prune_cols_funcs.go` line 646 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-NeBnOBtAroluVxGhXTt:-NeBnOBtAroluVxGhXTu:b-npgssm) ([raw file](https://github.com/cockroachdb/cockroach/blob/02a4b291b031b079496fb33e0248a4c6c808b019/pkg/sql/opt/norm/prune_cols_funcs.go#L646)):*
> ```Go
> 		}
> 		uniqueKeyExpr := e.(*memo.UniqueKeyExpr)
> 		relProps.Rule.PruneCols = c.DerivePruneCols(uniqueKeyExpr.Input, disabledRules)
> ```

I'm unsure about this part. I've been thinking of UniqueKey as similar to Project. Why can't we prune every column (i.e. why can't we prune the unique key column)? Is it just that in practice we never will?

Oh, or is it because we need to wrap the UniqueKey in a Project in order to prune that column?

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`-- commits` line 86 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-NeBxouf7Aui7PoP85Z1):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If we're not backporting this, then I don't think we need the setting.
</blockquote></details>

Removed it
___
*[`pkg/sql/opt/norm/prune_cols_funcs.go` line 646 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-NeBnOBtAroluVxGhXTt:-NeE1jrB62131O2VYP3o:b3sqjxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/02a4b291b031b079496fb33e0248a4c6c808b019/pkg/sql/opt/norm/prune_cols_funcs.go#L646)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I'm unsure about this part. I've been thinking of UniqueKey as similar to Project. Why can't we prune every column (i.e. why can't we prune the unique key column)? Is it just that in practice we never will?

Oh, or is it because we need to wrap the UniqueKey in a Project in order to prune that column?
</blockquote></details>

The thought was, when we build a unique key, there will always be a consumer of it generated like an ensure distinct on operator. I don't think we could ever elide that consumer.  Perhaps there could be some future uses of `UniqueKey` which don't need to consume the column, but I can't imagine them. I'd assume every time we generate the column internally, it will be used.  However, I can't predict if future optimizations might be able to remove the consumer, so I've updated the code as suggested.

**Review by mgartner — COMMENTED** [review]
Philosophically, I prefer not to design for hypothetical changes in the future if there are simpler solutions, especially when those solutions won't make the hypothetical changes more difficult in the future (e.g., the UniqueKey operator will be the same amount of work to add later as it is now). If you design for a lot of future hypothetical changes in the future that never come to pass, you can end up with a designs in the present with motivations that are hard to understand.

The suggestion I believe is a few line change, so I think it's worth exploring.

If we do want to add a new expression, we need to test the code added here with the same rigor as other operators. Each of the new normalization rules should have tests. We also need [tests for the logical properties](https://github.com/cockroachdb/cockroach/tree/e2a49ffebbcefaafa013dc0ef51b1531afd2790b/pkg/sql/opt/memo/testdata/logprops) of the new operator. I think we should also have at least one execbuilder test to verify the expression is contructed into an operator correctly. And we may need to add a rule like PushLimitIntoOrdinality to avoid a regression.

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-NeE7fKNBFFP0FTXMizJ:bizsyad)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

**Review by michae2 — COMMENTED** [review]
Very good point, I concede. @msirek would you be willing to try out that unordered Ordinality suggestion in another PR? If  we end up going with that fix we can save this PR and bring it back when we do have a distributed uniqueKey implementation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-NeELAz457TJ7CLXs_7K:b-w8as29)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

**Review by msirek — COMMENTED** [review]
I can revert back to using Ordinality, but I don't think checking for Any ordering will work.  For example:
```sql
create table t1 (a int, b int);
insert into t1 values (1,1), (2,2), (3,3);
select * FROM [select * from t1 with ordinality] WHERE a=3;
  a | b | ordinality
----+---+-------------
  3 | 3 |          3
```
If the `a=3` Select filter is pushed in, this would change the result to:
```sql
  a | b | ordinality
----+---+-------------
  3 | 3 |          1
```

Is it OK to go with the original fix, or are there any other ideas?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-NeE_WcFAtYswDttCSNE:b6audt1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @michae2)

**Comment by DrewKimball** [comment]
Wouldn't that result be indistinguishable from writing the query with a descending ordering?
```
select * FROM [select * from (select * from t1 order by a desc) with ordinality] WHERE a=3;
```

Maybe this behavior is too confusing, but I don't think the ordering is completely deterministic as written, anyway. What if the scan was parallelized, for example? We explicitly don't guarantee the ordering without ORDER BY: https://www.cockroachlabs.com/docs/stable/order-by#ordering-of-rows-without-order-by.

**Comment by DrewKimball** [comment]
That being said, if we want to backport we'd probably still want to use your earlier solution just in case someone is incorrectly depending on this behavior. I think making behavior *more* nondeterministic than it already is should probably only happen across major version changes.

**Review by msirek — COMMENTED** [review]
> I don't think the ordering is completely deterministic as written, anyway.

Good point, a relation without ORDER BY could present rows in any order. I understood from @mgartner's earlier comment that we won't be backporting rules any more, so in that case checking for Any ordering seems OK.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-NeEfBamCjCbrnipPgK7:bwkrw6g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @michae2)

**Comment by mgartner** [comment]
> I understood from @mgartner's earlier comment that we won't be backporting rules any more

To be clear this isn't some hard-and-fast rule and it's worth discussion for each situation, but in order to mitigate risk of breaking changes and bugs in patches we need to be sure there are strong motivations for risky backports, e.g., incorrect query results that can only be fixed by a new rule would be a strong motivation.

**Review by msirek — COMMENTED** [review]
I've put this PR on hold and opened https://github.com/cockroachdb/cockroach/pull/110593 for the fix using Ordinality.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109903#-:-NeG2JhyCDR2m-g5ioTk:b16wk00)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @michae2)

**Pull request closed without merging**
