### PR TITLE
sql: fix substring(byte[]) to treat input as raw bytes without escaping

### LINKED ISSUE #57367: could not parse "\\000x\\0ffyz" as type bytes: invalid bytea escape sequence
**Describe the problem**
I have a problem using `SUBSTRING` function on a column defined as `BYTEA`. For some values in a column, the function fails with an error:
```
ERROR: substring(): could not parse "���Q��=\nݻk�1\x10�O�j�%V\\\x12\rz����/\x02���'��z���w�b3EӍK�^��n\t٩�1��\f�$f �\x1e\\G�\x06: \x1a" as type bytes: invalid bytea escape sequence (SQLSTATE 22025)
```
I'm using `pgx` as a Go driver.

**To Reproduce**
This snippet can be used to reproduce this error:
```
root@localhost:26257/defaultdb> SELECT substring(x'02535497082f02bd395c', 1);
ERROR: substring(): could not parse "\x02ST�\b/\x02�9\\" as type bytes: bytea encoded value ends with escape character
SQLSTATE: 22025
```
The same snippet works fine for Postgres.

**Expected behavior**
No error.

**Environment:**
Build Tag:        v20.2.2
Build Time:       2020/11/25 14:45:44
Distribution:     CCL
Platform:         linux amd64 (x86_64-unknown-linux-gnu)
Go Version:       go1.13.14
C Compiler:       gcc 6.3.0
Build Commit ID:  92d94952060fd24400906dc06e392d7a7419b392
Build Type:       release

### PR DESCRIPTION
**Pull request by rafiss**
fixes #57367 

Release note (bug fix): The substring function on byte arrays would
treat its input as unicode code points, which would cause the wrong
bytes to be returned. Now it only operates on the raw bytes.

Release note (bug fix): The substring(byte[]) functions were not able to
interpret bytes that had the `\` character since it was treating it as
the beginning of an escape sequence. This is now fixed.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Second commit LGTM. First commit unsure - I take it that you checked that pg does the same - but I'll let another reviewer approve.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58265#-:-MPeJQcKAkWJ-UJv0wT4:beoaf1m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by rafiss** [comment]
Yeah, PG does this here: [text_substring](https://github.com/postgres/postgres/blob/472e518a44eacd9caac7d618f1b6451672ca4481/src/backend/utils/adt/varlena.c#L864) versus [bytea_substring](https://github.com/postgres/postgres/blob/472e518a44eacd9caac7d618f1b6451672ca4481/src/backend/utils/adt/varlena.c#L3292)

**Review by solongordon — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @solongordon)

___
*[pkg/sql/sem/builtins/builtins.go, line 4930 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58265#-MQ8dUPy1VIbEnYeyMjN:-MQ8dUPy1VIbEnYeyMjO:b-tqbvyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0afa2b999af68881572d748faeebc3b051505db3/pkg/sql/sem/builtins/builtins.go#L4930)):*
> ```Go
> 
> 	end := start + length
> 	// Check for integer overflow.
> ```

These are kind of funky cases. If it's easy enough, please add tests and verify we match Postgres behavior.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/sem/builtins/builtins.go, line 4930 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58265#-MQ8dUPy1VIbEnYeyMjN:-MQDPFjfCkDcKxDZrN0J:b-pajiwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0afa2b999af68881572d748faeebc3b051505db3/pkg/sql/sem/builtins/builtins.go#L4930)):*
Sure. I have been adding these tests, but while comparing to Postgres, I think I discovered a bug/mistake in PG.

The PG source code https://github.com/postgres/postgres/blob/472e518a44eacd9caac7d618f1b6451672ca4481/src/backend/utils/adt/varlena.c#L884-L891
```
                        int			E = S + length;
			/*
			 * A negative value for L is the only way for the end position to
			 * be before the start. SQL99 says to throw an error.
			 */
			if (E < S)
				ereport(ERROR,
						(errcode(ERRCODE_SUBSTRING_ERROR),
						 errmsg("negative substring length not allowed")));
```

But that comment is wrong -- the end position could be before the start if L is not negative and the addition overflows.

I'm gonna go ahead and intentionally diverge from PG in that case to avoid this confusing behavior.

```
> select substr('string', 2147483646, 2147483646);
2021-01-04 12:23:00.298 EST [85734] ERROR:  negative substring length not allowed
```

I submitted a bug report to PG as well.

**Comment by solongordon** [comment]
Nice catch. Do you think we should consider just erroring out in the overflow case? But with a more accurate error than Postgres?

**Comment by rafiss** [comment]
The PG devs seem to be pretty responsive on the bug tracker, so I'll see how they want to handle it and decide if we should do the same. I would lean towards keeping our current behavior of just going to the end of the string.

e.g. these should be the same.
```
> select substring('string', 2, 100);
tring

> select substring('string', 2, 9223372036854775807);
tring
```

**Comment by rafiss** [comment]
It's being discussed in the PG list here: https://www.postgresql.org/message-id/16804-f4eeeb6c11ba71d4%40postgresql.org

**Comment by rafiss** [comment]
PG devs landed on doing the same behavior we already implement, so merging this https://www.postgresql.org/message-id/3219376.1609795681%40sss.pgh.pa.us

bors r=solongordon

**Pull request merged**
