### PR TITLE
sql: de-pointer FK ref proto

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8067)

### CODE REVIEW

**Comment by paperstreet** [comment]
@jseldess fyi this breaks backward compatibility. if you create a table with this commit and then try to use it with a version before this commit, it won't work

**Comment by paperstreet** [comment]
I'm concerned that TestDockerReadWriteBidirectionalReferenceVersion didn't fail for this commit

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/drop.go, line 218 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8067#-KNi4LeLj6-8ShGLHf4Q:-KNi4LeLj6-8ShGLHf4R:-1371241957) ([raw file](https://github.com/cockroachdb/cockroach/blob/46fd70fed1819a28b7bc0c0f68c3239165ab2098/sql/drop.go#L218)):*
> ```Go
> 			idx := tableDesc.Indexes[i]
> 
> 			if idx.ForeignKey.Table != 0 {
> ```

what do you think about making this an IsEmpty method on ForeignKeyReference? (I'd like to do the same for Interleaved stuff)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8067#-:-KNi4AginyxfKJzcl88h:-643618017)*

**Comment by dt** [comment]
Yeah, looks like the reference tests never make the "old" binary _write_ to the `testing_new` table created by the "new" binary so this break isn't caught. followup on that in: #8102

**Comment by jseldess** [comment]
@bdarnell, should this be called out in this week's release notes?

**Comment by dt** [comment]
(note this wasn't merged yet, so it'll be next week's beta)

**Comment by jseldess** [comment]
Thanks @dt. Good thing @sploiselle has started on foreign keys.

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/drop.go, line 218 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8067#-KNi4LeLj6-8ShGLHf4Q:-KNnOeGHn2ovvLaLrZX4:103850182) ([raw file](https://github.com/cockroachdb/cockroach/blob/46fd70fed1819a28b7bc0c0f68c3239165ab2098/sql/drop.go#L218)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> what do you think about making this an IsEmpty method on ForeignKeyReference? (I'd like to do the same for Interleaved stuff)
</details>
Done (though `IsSet` made more sense than `IsEmpty()` since all the calls would just negate it anyway).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8067)*

**Comment by sploiselle** [comment]
@dt @paperstreet – Is the impact here just the backwards incompatibility or are there other implications for foreign keys?

**Comment by dt** [comment]
no behavior change, just a code cleanup, but it does introduce backwards incompatibility in that tables or indexes created with this or later version will encounter spurious foreign key errors when used by an older version.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8067#-:-KNnQkDs3lQh20wIOoQl:-1017332664)*

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/structured.go, line 1519 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8067#-KNnSou4qWvjLRpp8sha:-KNnSou4qWvjLRpp8shb:-1101430666) ([raw file](https://github.com/cockroachdb/cockroach/blob/3316d3861796ac1f6ccef26a07b1185f7e396d6b/sql/sqlbase/structured.go#L1519)):*
> refereences

spelling

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8067#-:-KNnSsNO7IVOTwrvYNMH:1417088721)*

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/structured.go, line 1519 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8067#-KNnSou4qWvjLRpp8sha:-KNnVylosGe1Ti4EhhHq:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3316d3861796ac1f6ccef26a07b1185f7e396d6b/sql/sqlbase/structured.go#L1519)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> > refereences
> 
> spelling
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8067)*

**Pull request merged**
