### PR TITLE
Detail the result ordering with EXPLAIN(VERBOSE).

### PR DESCRIPTION
**Pull request by knz**
As recommended by @RaduBerinde.

Required by #6735.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6848)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice!

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> #### Detail the result ordering with EXPLAIN\(VERBOSE\)\.
> 
> As recommended by @RaduBerinde.
> 
> 
> 
> Required by #6735.
> 
> 
> 
</details>


---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/ordering.go, line 84 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6848#-KIOVverFgZvugVB1Kxk:-KIOVvesaNkbrkfQhgxr:351780952) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3519e8abc9f953e15309d95c712175004b31659/sql/ordering.go#L84)):*
> ```Go
> 		}
> 	}
> 	for i := range ord.exactMatchCols {
> ```

I think the exact match columns should come first (as they have a "bigger" impact on ordering).

Also, this loop will return things in a different order every time.. Maybe do a loop to get the max col value, then loop over the entire range and check the map each time.

---

*[sql/testdata/explain_plan, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6848#-KIOWzfpitfgtIvpccG6:-KIOWzfqeVDilKwMjv_e:857651534) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3519e8abc9f953e15309d95c712175004b31659/sql/testdata/explain_plan#L27)):*
> ```
> ----
> Level  Type   Description Ordering
> 0      select (k, v)@t    +k,unique
> ```

a test with exact matches would be nice (something with more columns and a WHERE clause where some of the columns are restricted to a single value).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6848#-:-KIOYAwmTlyterZsQzxb:-490100129)*

**Comment by knz** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/ordering.go, line 84 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6848#-KIOVverFgZvugVB1Kxk:-KIPNq3w43YmazgQYFxg:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3519e8abc9f953e15309d95c712175004b31659/sql/ordering.go#L84)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I think the exact match columns should come first (as they have a "bigger" impact on ordering).
> 
> Also, this loop will return things in a different order every time.. Maybe do a loop to get the max col value, then loop over the entire range and check the map each time.
</details>
Done.

---

*[sql/testdata/explain_plan, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6848#-KIOWzfpitfgtIvpccG6:-KIPPn1aTa913ygELbQQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3519e8abc9f953e15309d95c712175004b31659/sql/testdata/explain_plan#L27)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> a test with exact matches would be nice (something with more columns and a WHERE clause where some of the columns are restricted to a single value).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6848)*

**Comment by RaduBerinde** [comment]
:lgtm:

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Nice!
</details>


---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/testdata/explain_plan, line 81 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6848#-KIPgOwgC5GeCSRYUDJE:-KIPgOwgC5GeCSRYUDJF:1393982622) ([raw file](https://github.com/cockroachdb/cockroach/blob/945453b23389c1f730a4df08b39fb1cf4715413b/sql/testdata/explain_plan#L81)):*
> ```
> 2     index-join                 =a,+rowid,unique
> 3     scan         tc@c /10-/11  =a,+rowid,unique
> 3     scan         tc@primary    +rowid,unique
> ```

Very nice seeing how it changes at each level!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6848#-:-KIPgjmWJgBJ_Ol7vwKe:1417088721)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
