### PR TITLE
sql: add unique constraints to table descriptor for UNIQUE WITHOUT INDEX

### PR DESCRIPTION
**Pull request by rytaft**
**sql,clusterversion: add cluster version and settings for `UNIQUE WITHOUT INDEX`**

This commit adds a new cluster version `UniqueWithoutIndexConstraints` as well
as a session setting `experimental_enable_unique_without_index_constraints`
and cluster default setting
`sql.defaults.experimental_enable_unique_without_index_constraints.enabled` to
control the use of `UNIQUE WITHOUT INDEX`. The session setting and cluster
default setting will be removed after full support is added for `UNIQUE WITHOUT INDEX`.
The cluster version will remain, however, because we need to prevent
users from creating `UNIQUE WITHOUT INDEX` constraints before all nodes are
upgraded to the correct version.

Release note (sql change): Added a session setting
`experimental_enable_unique_without_index_constraints` and cluster default
`sql.defaults.experimental_enable_unique_without_index_constraints.enabled`
to enable the use of `UNIQUE WITHOUT INDEX` syntax. The default value of both
settings is `false` since this feature is not yet fully supported. Use of
`UNIQUE WITHOUT INDEX` also depends on all nodes being upgraded to the cluster
version `UniqueWithoutIndexConstraints`.

**sql: add unique constraints to table descriptor for `UNIQUE WITHOUT INDEX`**

This commit adds unique constraints to the table descriptor for
`UNIQUE WITHOUT INDEX` constraints. This is currently only implemented for
constraints that are added in a `CREATE TABLE` statement. Support for
adding unique constraints in an `ALTER TABLE` statement will be added
in a future PR.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-:-MNzQhFU2mKcmE897TtC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/catalog/descpb/constraint.go, line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MNzOtnP0KCy3gKtjQkY:-MNzOtnP0KCy3gKtjQkZ:b-g1bdja) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab09289eebc0a59277176999d30c511a74048c03/pkg/sql/catalog/descpb/constraint.go#L114)):*
> ```Go
> 
> 	// Only populated for Unique Constraints without an index.
> 	UniqueConstraint *UniqueConstraint
> ```

[nit] should it be UniqueConstraintWithoutIndex then? Similar question for the proto.
___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 1483 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MNzQ_qH6PpiICoM_bPV:-MNzQ_qIAnnHmpMH5edl:b-py10np) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab09289eebc0a59277176999d30c511a74048c03/pkg/sql/logictest/testdata/logic_test/alter_table#L1483)):*
> ```
> SHOW CONSTRAINTS FROM unique_without_index
> ----
> unique_without_index  unique_without_index_c_key  UNIQUE  UNIQUE (c ASC)  true
> ```

[nit] we don't have a positive case for DROP CONSTRAINT, maybe drop this last constraint too

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-:-MNzwO9HE8UPDR36e1Vv:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, @mgartner, and @RaduBerinde)

___
*[pkg/sql/catalog/descpb/constraint.go, line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MNzOtnP0KCy3gKtjQkY:-MNzpKXz69Cwb1Vu4Man:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab09289eebc0a59277176999d30c511a74048c03/pkg/sql/catalog/descpb/constraint.go#L114)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] should it be UniqueConstraintWithoutIndex then? Similar question for the proto.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 1483 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MNzQ_qH6PpiICoM_bPV:-MNzhyt66YPfKp-Oph9h:b-gfgqzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab09289eebc0a59277176999d30c511a74048c03/pkg/sql/logictest/testdata/logic_test/alter_table#L1483)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] we don't have a positive case for DROP CONSTRAINT, maybe drop this last constraint too
</blockquote></details>

This constraint is from the index -- currently it can only be dropped using `DROP INDEX CASCADE` (or by dropping column `c`). There isn't yet a way to drop constraints directly since I haven't yet added support for adding not-valid unique constraints and dropping valid constraints requires a schema change (or at least that's how it works now for foreign key and check constraints).

Anyway, added a TODO to add those test cases once supported.

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 3 of 17 files at r2, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57666)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, @RaduBerinde, and @rytaft)

___
*[pkg/sql/alter_column_type.go, line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3fzVV2TJrXPTVbKSI:-MO3fzVV2TJrXPTVbKSJ:b-wjoako) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/alter_column_type.go#L200)):*
> ```Go
> 	}
> 
> 	for _, uc := range tableDesc.AllActiveAndInactiveUniqueWithoutIndexConstraints() {
> ```

[nit] add a comment similar to the one above: `// Disallow ALTER COLUMN TYPE general for columns that have a UNIQUE WITHOUT INDEX constraint.`
___
*[pkg/sql/alter_table.go, line 531 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3gq6K46jBI47CACA2:-MO3gq6K46jBI47CACA3:b-zf0hlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/alter_table.go#L531)):*
> ```Go
> 				}
> 			}
> 			n.tableDesc.UniqueWithoutIndexConstraints = n.tableDesc.UniqueWithoutIndexConstraints[:sliceIdx]
> ```

Won't this drop any unique constraints after `sliceIdx` even if they don't reference the column being dropped? I added a comment to the tests mentioning to test this case.
___
*[pkg/sql/alter_table.go, line 714 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3hKtf1dH29jAaN0MI:-MO3hKtf1dH29jAaN0MJ:b-eld6sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/alter_table.go#L714)):*
> ```Go
> 				// This unique constraint is enforced by an index, so fall through to
> 				// the error below.
> 				fallthrough
> ```

[nit] you could move `fallthrough` up just below the `case` to reduce indentation: `if constraint.Index != nil { fallthrough }`. It's all personal preference though, so leave as is if you think this is more grok-able.
___
*[pkg/sql/create_table.go, line 639 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3lKwhEtm2f-xys9_n:-MO3lKwhEtm2f-xys9_o:byd2865) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/create_table.go#L639)):*
> ```Go
> 	}
> 
> 	var validity descpb.ConstraintValidity
> ```

[nit] it might help readable (and maybe safer) to make the default case explicit rather than the implicit zero value: `validity := descpb.ConstraintValidity_Validated`
___
*[pkg/sql/create_table.go, line 1765 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3m0Y213oS6DM88Vy9:-MO3m0Y213oS6DM88VyA:b-f1hl7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/create_table.go#L1765)):*
> ```Go
> 				if len(d.Storing) > 0 {
> 					return nil, pgerror.New(pgcode.FeatureNotSupported,
> 						"stored columns for unique constraints without an index are not supported",
> ```

Maybe its just me but this error is confusing. Maybe `unique constraints without indexes cannot store columns`? Or maybe its just weird because it doesn't make sense for a constraint to store anything. Should `UNIQUE WITHOUT INDEX (a) STORING (x)` even be parsable?
___
*[pkg/sql/opt_catalog.go, line 757 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3sIAj2OSz5VJO2dkX:-MO3sIAj2OSz5VJO2dkY:bymtn0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/opt_catalog.go#L757)):*
> ```Go
> 	for i := range ot.desc.UniqueWithoutIndexConstraints {
> 		u := &ot.desc.UniqueWithoutIndexConstraints[i]
> 		ot.uniqueConstraints = append(ot.uniqueConstraints, optUniqueConstraint{
> ```

[nit] initialize `ot.uniqueConstraints` with a capacity of `len(ot.desc.UniqueWithoutIndexConstraints)` to prevent `append` from having to create a new underlying array. It looks like we do that for `ot.indexes`, `ot.families, and some other fields, though not for `ot.outboundFKs` or `ot.inboundFKs`. Not sure if there's any reason for that...
___
*[pkg/sql/catalog/tabledesc/structured.go, line 469 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3pbJAE8agc6MrnXmZ:-MO3pbJAE8agc6MrnXm_:bei5ec2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/catalog/tabledesc/structured.go#L469)):*
> ```Go
> 	for i := range desc.Mutations {
> 		if c := desc.Mutations[i].GetConstraint(); c != nil &&
> 			c.ConstraintType == descpb.ConstraintToUpdate_UNIQUE {
> ```

Should `descpb.ConstraintToUpdate_UNIQUE` be more specifically `descpb.ConstraintToUpdate_UNIQUE_WITHOUT_INDEX`? Do you envision ever needing a distinction between `UNIQUE` and `UNIQUE WITHOUT INDEX` so that this function returns the correct constraints?
___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 1478 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3quWQ0Z7NyoVMCJe0:-MO3quWQ0Z7NyoVMCJe1:b-j9hkw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/logictest/testdata/logic_test/alter_table#L1478)):*
> ```
> # Dropping a column in a unique constraint drops the constraint.
> statement ok
> ALTER TABLE unique_without_index DROP COLUMN b
> ```

Can you add a `UNIQUE WITHOUT INDEX` constraint that does not reference `b` and make sure it doesn't get dropped when `b` is dropped.
___
*[pkg/sql/logictest/testdata/logic_test/show_create, line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3ngL99AN_C67Y0KoK:-MO3ngLA6f0voH8iNMtD:b-z9kbuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/logictest/testdata/logic_test/show_create#L9)):*
> ```
> 	b INT NULL,
> 	INDEX c_a_b_idx (a ASC, b ASC),
> 	UNIQUE WITHOUT INDEX (a, b),
> ```

[nit] convert the indents from tabs to spaces to make the style elsewhere in the file. I think we generally use spaces in data driven test, but I'm not 100% sure.

**Review by rytaft — COMMENTED** [review]
TFTR! Updated.

I also realized (thanks to some test failures) that I was missing validation logic as well as safe formatting. PTAL.

@lucy-zhang or @ajwerner any chance either one of you can take a quick glance at this PR some time this week?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-:-MO8s2AsCUqT1k0bGTVa:b50p3uo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, and @mgartner)

___
*[pkg/sql/alter_column_type.go, line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3fzVV2TJrXPTVbKSI:-MO8lOu-5C777ylF7rss:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/alter_column_type.go#L200)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] add a comment similar to the one above: `// Disallow ALTER COLUMN TYPE general for columns that have a UNIQUE WITHOUT INDEX constraint.`
</blockquote></details>

Done.
___
*[pkg/sql/alter_table.go, line 531 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3gq6K46jBI47CACA2:-MO8lSPE0fKfIrPEge5w:b-n1uzzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/alter_table.go#L531)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Won't this drop any unique constraints after `sliceIdx` even if they don't reference the column being dropped? I added a comment to the tests mentioning to test this case.
</blockquote></details>

No, because the constraints are shifted over a few lines up:
```
constraint := &n.tableDesc.UniqueWithoutIndexConstraints[i]
n.tableDesc.UniqueWithoutIndexConstraints[sliceIdx] = *constraint
```

I did it this way to be consistent with the rest of this function.
___
*[pkg/sql/alter_table.go, line 714 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3hKtf1dH29jAaN0MI:-MO8lnV51iN3myXrohLQ:b-6lr9zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/alter_table.go#L714)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] you could move `fallthrough` up just below the `case` to reduce indentation: `if constraint.Index != nil { fallthrough }`. It's all personal preference though, so leave as is if you think this is more grok-able.
</blockquote></details>

I see your point, but I have a slight preference to leave this as-is since I think it will make someone less likely to insert another `case` here in the future and miss the fact that they need to fix the `fallthrough`.
___
*[pkg/sql/create_table.go, line 639 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3lKwhEtm2f-xys9_n:-MO8mFY5Da_UcRuzP8XC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/create_table.go#L639)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] it might help readable (and maybe safer) to make the default case explicit rather than the implicit zero value: `validity := descpb.ConstraintValidity_Validated`
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1765 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3m0Y213oS6DM88Vy9:-MO8mJUX72pkM5noJooV:bgeo88f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/create_table.go#L1765)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Maybe its just me but this error is confusing. Maybe `unique constraints without indexes cannot store columns`? Or maybe its just weird because it doesn't make sense for a constraint to store anything. Should `UNIQUE WITHOUT INDEX (a) STORING (x)` even be parsable?
</blockquote></details>

Done.

Yea, it's parsable because it would have been a fair amount more complicated to make it not parsable.
___
*[pkg/sql/opt_catalog.go, line 757 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3sIAj2OSz5VJO2dkX:-MO8oK3F98tcq45XYMX8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/opt_catalog.go#L757)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] initialize `ot.uniqueConstraints` with a capacity of `len(ot.desc.UniqueWithoutIndexConstraints)` to prevent `append` from having to create a new underlying array. It looks like we do that for `ot.indexes`, `ot.families, and some other fields, though not for `ot.outboundFKs` or `ot.inboundFKs`. Not sure if there's any reason for that...
</blockquote></details>

Done.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 469 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3pbJAE8agc6MrnXmZ:-MO8p0RR069XzxXw7DsW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/catalog/tabledesc/structured.go#L469)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should `descpb.ConstraintToUpdate_UNIQUE` be more specifically `descpb.ConstraintToUpdate_UNIQUE_WITHOUT_INDEX`? Do you envision ever needing a distinction between `UNIQUE` and `UNIQUE WITHOUT INDEX` so that this function returns the correct constraints?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 1478 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3quWQ0Z7NyoVMCJe0:-MO8pA_f5dzDGKkdM7bM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/logictest/testdata/logic_test/alter_table#L1478)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add a `UNIQUE WITHOUT INDEX` constraint that does not reference `b` and make sure it doesn't get dropped when `b` is dropped.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/show_create, line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3ngL99AN_C67Y0KoK:-MO8peW-6yZ4H0I17A55:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/logictest/testdata/logic_test/show_create#L9)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] convert the indents from tabs to spaces to make the style elsewhere in the file. I think we generally use spaces in data driven test, but I'm not 100% sure.
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 22 files at r4, 22 of 22 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-:-MO9D1VrEjAW1I2p62K8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, and @rytaft)

___
*[pkg/sql/alter_table.go, line 531 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3gq6K46jBI47CACA2:-MO9AueT82AKySw5y9A0:b9oip9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/alter_table.go#L531)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

No, because the constraints are shifted over a few lines up:
```
constraint := &n.tableDesc.UniqueWithoutIndexConstraints[i]
n.tableDesc.UniqueWithoutIndexConstraints[sliceIdx] = *constraint
```

I did it this way to be consistent with the rest of this function.
</blockquote></details>

I see. This is an efficient way to delete items from the slice. :+1: 
___
*[pkg/sql/alter_table.go, line 714 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3hKtf1dH29jAaN0MI:-MO9B8YAD77tfjJkrgvm:b-dxcbu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/alter_table.go#L714)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I see your point, but I have a slight preference to leave this as-is since I think it will make someone less likely to insert another `case` here in the future and miss the fact that they need to fix the `fallthrough`.
</blockquote></details>

Makes sense!
___
*[pkg/sql/create_table.go, line 1765 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO3m0Y213oS6DM88Vy9:-MO9BINW1dH8NAWOQyQ0:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8240ea59dc4bcefb9f98c0c59d2652d0ee0b2b66/pkg/sql/create_table.go#L1765)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Done.

Yea, it's parsable because it would have been a fair amount more complicated to make it not parsable.
</blockquote></details>

:+1: 
___
*[pkg/sql/catalog/tabledesc/structured_test.go, line 733 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO9Cu-E-xf3L1rcdAk5:-MO9Cu-FBOk4NbCTIAY_:b3xfn99) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c826e3e1c7d5cdf7472c05d3188618778d50a07/pkg/sql/catalog/tabledesc/structured_test.go#L733)):*
> ```Go
> 				},
> 			}},
> 		{`unique without index constraint "bar_unique" contains duplicate column "1"`,
> ```

[nit] while you're at it, you could add a test for the "unknown column" case that you have in the validation function.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57666)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @lucy-zhang, and @mgartner)

___
*[pkg/sql/catalog/tabledesc/structured_test.go, line 733 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MO9Cu-E-xf3L1rcdAk5:-MO9dFRQ3kYOdJ8aupwt:bd0gvle) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c826e3e1c7d5cdf7472c05d3188618778d50a07/pkg/sql/catalog/tabledesc/structured_test.go#L733)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] while you're at it, you could add a test for the "unknown column" case that you have in the validation function.
</blockquote></details>

Done. It has a different error message because this issue actually gets caught earlier by `CheckUniqueConstraints`.

**Review by ajwerner — COMMENTED** [review]
:lgtm: 

@postamar you should give this PR a read when you find some time. It does things the way they are currently done but demonstrates the mix of logic in the sql layer and methods on the mutable table descriptor to mutate the descriptor. It also highlights the ways in which we mix the validation of changes with the imperative logic to perform them. All-in-all just a good change that touches on the APIs and conventions we're actively looking to rework. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-:-MOAED6O7Da3n3dFcZqG:b-ify673)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @lucy-zhang, @mgartner, and @rytaft)

___
*[pkg/sql/alter_column_type.go, line 201 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MOA8Q83Bp9lwTGG-q1P:-MOA8Q83Bp9lwTGG-q1Q:b-wpgvc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fc523a4f8fc0646f9f413243625af39ba1f123/pkg/sql/alter_column_type.go#L201)):*
> ```Go
> 	}
> 
> 	// Disallow ALTER COLUMN TYPE general for columns that have a
> ```

nit `generally`?
___
*[pkg/sql/alter_table.go, line 529 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MOABlj559ZU-7gGR3vT:-MOABlj559ZU-7gGR3vU:b-gw98c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fc523a4f8fc0646f9f413243625af39ba1f123/pkg/sql/alter_table.go#L529)):*
> ```Go
> 				if descpb.ColumnIDs(constraint.ColumnIDs).Contains(colToDrop.ID) {
> 					sliceIdx--
> 				}
> ```

This is totally fine as is, just sharing that my usual idiom for this is:

```go
constraints := n.tableDesc.UniqueWithoutIndexConstraints // for code brevity
truncated := constraints[:0]
for i := range constraints {
    if !descpb.ColumnIDs(constraints[i].ColumnIDs).Contains(colToDrop.ID) {
        truncated = append(truncated, constraints[i])
    }
}
n.tableDesc.UniqueWithoutIndexConstraints = truncated
```

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-:-MOByjgn15LKcKIZYcX7:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @lucy-zhang, and @mgartner)

___
*[pkg/sql/alter_column_type.go, line 201 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MOA8Q83Bp9lwTGG-q1P:-MOBxNdW6iGkz_V0y5fT:b-6k4t9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fc523a4f8fc0646f9f413243625af39ba1f123/pkg/sql/alter_column_type.go#L201)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit `generally`?
</blockquote></details>

I think it's supposed to be "general" in reference to the `ColumnConversionKind`, which is `schemachange.ColumnConversionGeneral`. (I just copied this from the other comments in the function.)
___
*[pkg/sql/alter_table.go, line 529 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-MOABlj559ZU-7gGR3vT:-MOByJKR6oVUEkiLuFmZ:b4k8lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fc523a4f8fc0646f9f413243625af39ba1f123/pkg/sql/alter_table.go#L529)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is totally fine as is, just sharing that my usual idiom for this is:

```go
constraints := n.tableDesc.UniqueWithoutIndexConstraints // for code brevity
truncated := constraints[:0]
for i := range constraints {
    if !descpb.ColumnIDs(constraints[i].ColumnIDs).Contains(colToDrop.ID) {
        truncated = append(truncated, constraints[i])
    }
}
n.tableDesc.UniqueWithoutIndexConstraints = truncated
```
</blockquote></details>

Cool! I like this method. I'll leave the code as-is to be consistent with the rest of the for loops in the function, but I'll definitely keep this in mind.

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57666#-:-MOCBneo31tCn20thqXR:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @lucy-zhang, and @mgartner)

**Pull request merged**
