### PR TITLE
docs: Tech note on the rebalancing system

### PR DESCRIPTION
**Pull request by a-robinson**
Release note: None

---

Sorry for not getting this out earlier, but better late than never :)

@petermattis @BramGruneir @tbg @nvanbenschoten

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: This is fantastic!

Just a couple of minor edits below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-:-LWgGnVuEBNJPEfkoLQM:b-bt9m3y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @a-robinson)

___
*[docs/tech-notes/rebalancing.md, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-LWgF8xM8X0WVKzj7mMb:-LWgF8xM8X0WVKzj7mMc:blwfhh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e63a75ce41fc084c36afce8abda7667c53ebc29/docs/tech-notes/rebalancing.md#L122)):*
> ```Markdown
> * The `ReplicateQueue` only acts on ranges for which the local store is the
>   current leaseholder.
> * Only one goroutine is doing all this processing, including the actual sending
> ```

Reading this makes it seem like we should have multiple goroutines doing this processing. Worthwhile to point out the tension here: having multiple goroutines sending snapshots can easily overload the network and dramatically impact user traffic.
___
*[docs/tech-notes/rebalancing.md, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-LWgEgsz2N3h8NB5vorp:-LWgEgsz2N3h8NB5vorq:bujlf5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e63a75ce41fc084c36afce8abda7667c53ebc29/docs/tech-notes/rebalancing.md#L155)):*
> ```Markdown
> non-decommissioning replicas from the range. There's a bit of extra logic needed
> to dynamically adjust the desired number of replicas when it's greater than the
> number of nodes in the cluster ([#27349], [#30441], [#32949]), but that's about
> ```

Might as well add #34126 to this list.
___
*[docs/tech-notes/rebalancing.md, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-LWgG-AmBzDBHvRD-eIc:-LWgG-AmBzDBHvRD-eId:bcn2kne) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e63a75ce41fc084c36afce8abda7667c53ebc29/docs/tech-notes/rebalancing.md#L181)):*
> ```Markdown
> straightforward. We just iterate over each replica's store, grading it on the
> same [considerations](#Considerations) as always, choosing whichever store
> scores worst. The only real exception is if one of the replicas is dead; in such
> ```

Looks like we do a worst-of-two-random-candidates similar to up-replication. Am I missing something about the code in `RemoveTarget`?
___
*[docs/tech-notes/rebalancing.md, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-LWgGTO82HQLeIawFa4z:-LWgGTO82HQLeIawFa5-:b-7dp2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e63a75ce41fc084c36afce8abda7667c53ebc29/docs/tech-notes/rebalancing.md#L357)):*
> ```Markdown
> to remove a replica that is critical for the range's quorum. If only 3 replicas
> out of 5 are caught up with the raft leader's state, we can't remove any of
> those 3, but can safely remove either of the other 2.
> ```

Might want to note that this decision is made at a high-level and can be invalidated by the time the removal actually occurs, but that time window is short and this hasn't occurred in practice. 
___
*[docs/tech-notes/rebalancing.md, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-LWgGcJV7rKsWBSK7p3W:-LWgGcJV7rKsWBSK7p3X:bx5amxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e63a75ce41fc084c36afce8abda7667c53ebc29/docs/tech-notes/rebalancing.md#L361)):*
> ```Markdown
> ## Known issues
> 
> * Rebalancing isn't atomic, leaving room for locality failures to cause
> ```

I think it is worth spelling out what it means for it to be non-atomic: we add a replica, temporarily increasing the replication factor, and then remove a replica.

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34131)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis)

___
*[docs/tech-notes/rebalancing.md, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-LWgF8xM8X0WVKzj7mMb:-LWgPpkd0ZWTBkyrEqCF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e63a75ce41fc084c36afce8abda7667c53ebc29/docs/tech-notes/rebalancing.md#L122)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Reading this makes it seem like we should have multiple goroutines doing this processing. Worthwhile to point out the tension here: having multiple goroutines sending snapshots can easily overload the network and dramatically impact user traffic.
</blockquote></details>

Done.
___
*[docs/tech-notes/rebalancing.md, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-LWgEgsz2N3h8NB5vorp:-LWgQDbQEa4WOfpDlY9V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e63a75ce41fc084c36afce8abda7667c53ebc29/docs/tech-notes/rebalancing.md#L155)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Might as well add #34126 to this list.
</blockquote></details>

Done.
___
*[docs/tech-notes/rebalancing.md, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-LWgG-AmBzDBHvRD-eIc:-LWgQMv32Aoa8ZHpR2Mg:bont21y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e63a75ce41fc084c36afce8abda7667c53ebc29/docs/tech-notes/rebalancing.md#L181)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Looks like we do a worst-of-two-random-candidates similar to up-replication. Am I missing something about the code in `RemoveTarget`?
</blockquote></details>

No, we do. I just wasn't going into as much detail here. Added.
___
*[docs/tech-notes/rebalancing.md, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-LWgGTO82HQLeIawFa4z:-LWgQuXw8FbmPAZICdGU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e63a75ce41fc084c36afce8abda7667c53ebc29/docs/tech-notes/rebalancing.md#L357)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Might want to note that this decision is made at a high-level and can be invalidated by the time the removal actually occurs, but that time window is short and this hasn't occurred in practice. 
</blockquote></details>

Done.
___
*[docs/tech-notes/rebalancing.md, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-LWgGcJV7rKsWBSK7p3W:-LWgRnQcEWRiYi_tCOhj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e63a75ce41fc084c36afce8abda7667c53ebc29/docs/tech-notes/rebalancing.md#L361)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think it is worth spelling out what it means for it to be non-atomic: we add a replica, temporarily increasing the replication factor, and then remove a replica. 
</blockquote></details>

Done.

**Review by petermattis — COMMENTED** [review]
:shipit:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34131#-:-LWgTDw0BxFe3Ro9aFf1:b-xr9eiq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by tbg** [comment]
Fantastic, thanks @a-robinson!

bors r+

**Pull request merged**
