### PR TITLE
roachtest: Add github issues to blacklist

### LINKED ISSUE #31781: roachtest: hibernate failed
SHA: https://github.com/cockroachdb/cockroach/commits/5a373445c0674f060a4bfe369ad290a0cacccb6c

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stressrace TESTS=hibernate PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=982644&tab=buildLog

```
The test failed on master:
	test.go:644,hibernate.go:263,hibernate.go:278: 
		0 tests failed unexpectedly
		2 tests passed unexpectedly
		0 tests were not run that were expected to fail
		See artifacts/hibernate/log/logs/report for more details

```

### PR DESCRIPTION
**Pull request by BramGruneir**
This patch does two things:

- add multiple blacklists so that there can be more than one based on the
version of cockroach
- add the github issues to each test in the blacklist, so if one passes
unexpectedly we can quickly track down why

Fixes #31781.

Release note: None

### CODE REVIEW

**Comment by BramGruneir** [comment]
Just a note that I'm running this against 2.0, 2.1 and 2.2 right now to confirm all the blacklist are correct.

So i won't merge until I'm certain.

**Comment by BramGruneir** [comment]
This is ready to merge.  Passes on 2.0, 2.1 and 2.2.

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31890)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31890#-LPl4gmCDAj8vM5Xr_Oq:-LPl4gmCDAj8vM5Xr_Or:b6ao701) ([raw file](https://github.com/cockroachdb/cockroach/blob/386db2ada20ac93e91d850324c44bf06f985baa4/pkg/cmd/roachtest/hibernate.go#L140)):*
> ```Go
> 		blacklistName, expectedFailures := getHibernateBlacklistForVersion(version)
> 		if expectedFailures == nil {
> 			t.Fatal(errors.Errorf("No hibernate blacklist defined for cockroach version %s", version))
> ```

Just wondering why you're not doing `t.Fatalf("No ..... %s", version)`.
___
*[pkg/cmd/roachtest/hibernate.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31890#-LPl4sTX7CW7quDJzD0p:-LPl4sTX7CW7quDJzD0q:be46bf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/386db2ada20ac93e91d850324c44bf06f985baa4/pkg/cmd/roachtest/hibernate.go#L213)):*
> ```Go
> 				switch {
> 				case pass && !expectedFailure:
> 					results[test] = fmt.Sprintf("--- PASS: %s (expected)", test)
> ```

I hadn't noticed this before, but I'm not sure it's a good idea to use a format fit to confuse the test output parsers. I suppose it's already running like that and nobody is on fire, so... maybe it's OK. Do you get any benefit from doing it this way? Otherwise, perhaps just switch these to `PASS:` (without the `---`) instead. Otherwise, make sure they actually parse like the correct expected lines so that things match up (I think that means that all the expected/unexpected stuff has to look like a subtest). Doesn't have to be this PR.

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31890)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate_blacklist.go, line 685 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31890#-LPl5gzy9T2juybcPOBW:-LPl5gzy9T2juybcPOBX:b-27u0mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/386db2ada20ac93e91d850324c44bf06f985baa4/pkg/cmd/roachtest/hibernate_blacklist.go#L685)):*
> ```Go
> }
> 
> var hibernateBlackList2_0 = blacklist{
> ```

You may want to put each blacklist into its own file. `hibernate_blacklist_2_0.go` etc. Things will be a real mess over time otherwise.

**Review by BramGruneir — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31890)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31890#-LPl4gmCDAj8vM5Xr_Oq:-LPl6eE7-01Gj5hkhAjM:b-17zn9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/386db2ada20ac93e91d850324c44bf06f985baa4/pkg/cmd/roachtest/hibernate.go#L140)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Just wondering why you're not doing `t.Fatalf("No ..... %s", version)`.
</blockquote></details>

Ha... good question.  Done.
___
*[pkg/cmd/roachtest/hibernate.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31890#-LPl4sTX7CW7quDJzD0p:-LPl6V4m1d-YCJDxV4ad:b-h1esrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/386db2ada20ac93e91d850324c44bf06f985baa4/pkg/cmd/roachtest/hibernate.go#L213)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I hadn't noticed this before, but I'm not sure it's a good idea to use a format fit to confuse the test output parsers. I suppose it's already running like that and nobody is on fire, so... maybe it's OK. Do you get any benefit from doing it this way? Otherwise, perhaps just switch these to `PASS:` (without the `---`) instead. Otherwise, make sure they actually parse like the correct expected lines so that things match up (I think that means that all the expected/unexpected stuff has to look like a subtest). Doesn't have to be this PR.
</blockquote></details>

This was a request from Peter, he wanted to be able to quickly glance at the log and find if anything went wrong and wanted an already used format.  I did add the github issue links, which will make this useful going forward.

I'll consider updating the format again in a follow up PR.
___
*[pkg/cmd/roachtest/hibernate_blacklist.go, line 685 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31890#-LPl5gzy9T2juybcPOBW:-LPl6rGIBuYaLkBkLFXB:bembls5) ([raw file](https://github.com/cockroachdb/cockroach/blob/386db2ada20ac93e91d850324c44bf06f985baa4/pkg/cmd/roachtest/hibernate_blacklist.go#L685)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

You may want to put each blacklist into its own file. `hibernate_blacklist_2_0.go` etc. Things will be a real mess over time otherwise.
</blockquote></details>

I was considering that.  When we split for v2.3, I think I will.

**Comment by BramGruneir** [comment]
Thanks for the review @tschottdorf !

**Pull request merged**
