### PR TITLE
release-2.1: pgwire: report unimplemented client parameters in telemetry

### PR DESCRIPTION
**Pull request by knz**
Backport 1/2 commits from #33264.

/cc @cockroachdb/release

---

### CODE REVIEW

**Review by bdarnell — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33394)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/set_var.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33394#-LUqAfnw16FPRK8zchpR:-LUqAfnw16FPRK8zchpS:b2plbhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abb84a994735409d1c75d474feab5d5256c0261/pkg/sql/set_var.go#L52)):*
> ```Go
> 
> 	if _, ok := UnsupportedVars[name]; ok {
> 		return nil, pgerror.Unimplemented("set."+name,
> ```

This does more than adding telemetry; it may make things that used to work stop working. That's too risky to backport.

(Yes, it's true that maybe things were "working", but not as intended because we ignored the parameter. But I think it's more likely to be cases like the renegotiation limit where some client is (unconfigurably) setting a parameter to its default)

It's also weird that this change makes a known-but-unsupported setting an error but a completely garbage setting is logged and ignored.

**Comment by knz** [comment]
@bdarnell I think you may be reading the code wrong.

The code in `set_var.go` is ran only upon explicit SET commands by a client. Before this patch, such a statement with a non-existent setting would error out with an error "variable does not exist". With this patch, it gets an error "variable not supported" instead, with telemetry.

Meanwhile, the code in `pgwire/server.go` does only telemetry, there is no client change.

**Review by bdarnell — APPROVED** [review]
Right, nevermind. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33394#-:-LUqgcNL5AXN6mNR0yci:b-svj8nv)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by dt** [comment]
hm, I'm not quite sure that I see the motivation for this change meeting the bar for a backport?

That said, I think the change itself isn't too risky, so I don't actually feel strongly about it... so if you think it should get one (and it looks like @bdarnell is okay with it), then I guess it is fine by me.

**Comment by dt** [comment]
I think that's an accurate account.

**Comment by knz** [comment]
Ok @dt and @bdarnell do you think we should wait until Andy comes back to decide whether this should be backported or not?

**Comment by bdarnell** [comment]
I don't generally love backporting telemetry stuff, but we've done it before. I think this particular bit of telemetry seems unlikely to give us anything we would actually act on for 2.3, though. This work started when I noticed we were logging the ssl_renegotiation setting, so unless we have a stronger motivation for collecting telemetry on all the other settings I'd vote against backporting.

**Comment by knz** [comment]
I'm ok with not backporting this (I'll wait in any case until @awoods187 is back), however a heads up that the telemetry logic is broken in 2.1 currently and currently reporting data that's broken and/or super difficult to use. There will thus be other telemetry PRs that we'll want to merge (although perhaps these will be less discussion-worthy since they probably qualify as straight "bug fixes").

**Comment by knz** [comment]
Closing this since it was voted down by 2 votes out of 3.

**Pull request closed without merging**
