### PR TITLE
server/license: store cluster init time in the KV system keyspace

### PR DESCRIPTION
**Pull request by spilchen**
We need to store cluster-level metadata for license policy enforcement. This metadata must be protected from modification, so it cannot be stored in any system table. This PR introduces a new field in the system keyspace to store the cluster's initialization start time, which will be used in a follow-up PR to track the grace period for clusters without a license. The metadata needs to be stored at the cluster level to align with the license's scope.

A new struct, License.Enforcer, is responsible for writing and caching the new timestamp. This struct will be extended in future PRs to check for throttling in clusters that violate our license policies.

This update will be backported to versions 23.1, 23.2, 24.1, and 24.2.

Epic: CRDB-39988
Informs: CRDB-40064
Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
just had a few minor comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-:-O5ErFkr4GgcWquMv0ZT:b-ddjh1y)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/keys/constants.go` line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5EnjEX0CoasKF-89xd:-O5EnjEX0CoasKF-89xe:bvl2qru) ([raw file](https://github.com/cockroachdb/cockroach/blob/3333cb9809d8b3c732918bb31d9aec24f1edfc59/pkg/keys/constants.go#L306)):*
> ```Go
> 	// ClusterInitTimestamp is used for license enforcement. It represents the timestamp
> 	// of when the cluster was first initialized and is used for tracking the grace period.
> 	ClusterInitTimestamp = roachpb.Key(makeKey(SystemPrefix, roachpb.RKey("lic-cls-init")))
> ```

i think ClusterInitTimestamp might be a little misleading. I would interpret that to mean "the time when the cluster was first initialized." but what it's actually recording is "the time when the cluster first ran on a version that requires a license."

perhaps a name like `GracePeriodInitTimestamp` would work better.

also more of a nit: it would be useful for the comment to mention the format of the timestamp. is it seconds since unix epoch?
___
*[`pkg/server/license/enforcer.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5Ep6-7Aq-yee0Lq2Zh:-O5Ep6-7Aq-yee0Lq2Zi:bwurtt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3333cb9809d8b3c732918bb31d9aec24f1edfc59/pkg/server/license/enforcer.go#L89)):*
> ```Go
> 		}
> 		if val.Value == nil {
> 			log.Infof(ctx, "Generated new cluster init time: %s", e.startTime.UTC().String())
> ```

super nit: these two info log messages should start with lower case
___
*[`pkg/server/license/enforcer_test.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5EqtLu-DffXGDG9EC_:-O5EqtLu-DffXGDG9ECa:bm87450) ([raw file](https://github.com/cockroachdb/cockroach/blob/3333cb9809d8b3c732918bb31d9aec24f1edfc59/pkg/server/license/enforcer_test.go#L50)):*
> ```Go
> 	// Create a new enforcer, to test that it won't overwrite the cluster init
> 	// timestamp that was already setup.
> 	enforcer := &license.Enforcer{}
> ```

nit: this test could assert even more; we can access the real enforcer using `srv.SystemLayer().ExecutorConfig().(*sql.ExecutorConfig).LicenseEnforcer` (for the system tenant), and `srv.ApplicationLayer().ExecutorConfig().(*sql.ExecutorConfig).LicenseEnforcer` (for a secondary tenant). this would allow us to check that the behavior is correct for tenants.

**Review by spilchen — COMMENTED** [review]
Thanks for reviewing. I've applied the code revisions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-:-O5FL80h-96AAt_yZnjB:b-idm9s9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

___
*[`pkg/keys/constants.go` line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5EnjEX0CoasKF-89xd:-O5EzoaO246pe3aOoxnW:bbb4j31) ([raw file](https://github.com/cockroachdb/cockroach/blob/3333cb9809d8b3c732918bb31d9aec24f1edfc59/pkg/keys/constants.go#L306)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think ClusterInitTimestamp might be a little misleading. I would interpret that to mean "the time when the cluster was first initialized." but what it's actually recording is "the time when the cluster first ran on a version that requires a license."

perhaps a name like `GracePeriodInitTimestamp` would work better.

also more of a nit: it would be useful for the comment to mention the format of the timestamp. is it seconds since unix epoch?
</blockquote></details>

Yes, I prefer this name as well. I'll also specify the format. Initially, I used microsecond precision for the timestamp, but I switched to seconds for consistency after noticing that the telemetry ping timestamp uses second precision.
___
*[`pkg/server/license/enforcer.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5Ep6-7Aq-yee0Lq2Zh:-O5F2FWf8CL4AWUf9qP4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3333cb9809d8b3c732918bb31d9aec24f1edfc59/pkg/server/license/enforcer.go#L89)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: these two info log messages should start with lower case
</blockquote></details>

Done.
___
*[`pkg/server/license/enforcer_test.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5EqtLu-DffXGDG9EC_:-O5FKlT05LjkRD4WRYem:bim3n98) ([raw file](https://github.com/cockroachdb/cockroach/blob/3333cb9809d8b3c732918bb31d9aec24f1edfc59/pkg/server/license/enforcer_test.go#L50)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this test could assert even more; we can access the real enforcer using `srv.SystemLayer().ExecutorConfig().(*sql.ExecutorConfig).LicenseEnforcer` (for the system tenant), and `srv.ApplicationLayer().ExecutorConfig().(*sql.ExecutorConfig).LicenseEnforcer` (for a secondary tenant). this would allow us to check that the behavior is correct for tenants.
</blockquote></details>

Good ideas. Done.

**Review by rafiss — APPROVED** [review]
i noticed a few more nits in the latest review. they're all minor/stylistic, so feel free to merge after addressing them

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-:-O5J4ftc3UjP1ljN950X:b-gzh0mv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/server/license/enforcer.go` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5HAvdY9BLeEmf1QMSN:-O5HAvdY9BLeEmf1QMSO:bn4lyvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a308781e35662e9b635c09096b6da0afac26f2/pkg/server/license/enforcer.go#L28)):*
> ```Go
> // Enforcer is responsible for enforcing license policies.
> type Enforcer struct {
> 	// DB is used to access into the KV. This is set via InitDB. It must have
> ```

nit: I think the comment should say `Start` instead of `InitDB`
___
*[`pkg/server/license/enforcer.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5HB43LCqyxBpZE9bLx:-O5HB43LCqyxBpZE9bLy:b-xw7bin) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a308781e35662e9b635c09096b6da0afac26f2/pkg/server/license/enforcer.go#L31)):*
> ```Go
> 	// access to the system tenant since it read/writes KV keys in the system
> 	// keyspace.
> 	db descs.DB
> ```

in this case, we might want to use `isql.DB`interface. the `descs.DB` interface provides more functionality (like access to a `desc.Collection`) but we don't need that here, and the extra functionality makes the `descs` package larger. this `license` package might need to be imported by a variety of other packages, so it's better to make it have fewer dependencies.
___
*[`pkg/server/license/enforcer.go` line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5HC4-25QSCr3KPuOqi:-O5HC4-25QSCr3KPuOqj:bod1bpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a308781e35662e9b635c09096b6da0afac26f2/pkg/server/license/enforcer.go#L42)):*
> ```Go
> 
> 	// startTime is the time when the enforcer was created. This is used to seed
> 	// the grace period init timestamp if it's not set in the KV.
> ```

super nit: i think it should say `not set in KV` or `not set in the KV layer`.
___
*[`pkg/server/license/main_test.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5HCUQt53fBhyg-Rxh7:-O5HCUQt53fBhyg-Rxh8:bc15ms9) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a308781e35662e9b635c09096b6da0afac26f2/pkg/server/license/main_test.go#L23)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/testutils/testcluster"
> )
> ```

nit: the `main_test.go` file of a package also should include a line like:
```
//go:generate ../../util/leaktest/add-leaktest.sh *_test.go
```

this causes code to be generated that adds a no-memory-leak test assertion to each test.

**Review by spilchen — COMMENTED** [review]
tftr @rafiss 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-:-O5JxnYvAEsFdvNrc84y:b-jeloo7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @spilchen)

___
*[`pkg/server/license/enforcer.go` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5HAvdY9BLeEmf1QMSN:-O5JtYRv03G1THtaS7yk:b-ahf785) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a308781e35662e9b635c09096b6da0afac26f2/pkg/server/license/enforcer.go#L28)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: I think the comment should say `Start` instead of `InitDB`
</blockquote></details>

Good catch. I went back and forth on this and forgot to update this comment.
___
*[`pkg/server/license/enforcer.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5HB43LCqyxBpZE9bLx:-O5Jv48W7QO9dVkTrwvr:ba0msie) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a308781e35662e9b635c09096b6da0afac26f2/pkg/server/license/enforcer.go#L31)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in this case, we might want to use `isql.DB`interface. the `descs.DB` interface provides more functionality (like access to a `desc.Collection`) but we don't need that here, and the extra functionality makes the `descs` package larger. this `license` package might need to be imported by a variety of other packages, so it's better to make it have fewer dependencies.
</blockquote></details>

Good to know. I didn't know the difference.
___
*[`pkg/server/license/enforcer.go` line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129634#-O5HC4-25QSCr3KPuOqi:-O5JuAA_C7LiyE7wT3hD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a308781e35662e9b635c09096b6da0afac26f2/pkg/server/license/enforcer.go#L42)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: i think it should say `not set in KV` or `not set in the KV layer`.
</blockquote></details>

Done.

**Comment by spilchen** [comment]
TFTR!

bors r=rafiss

**Pull request merged**
