### PR TITLE
storeliveness: add Support Manager

### PR DESCRIPTION
**Pull request by miraradeva**
This commit adds the Store Liveness `SupportManager`, which implements the `storeliveness.Fabric` interface. The `SupportManager` is responsible for orchestrating sending support requests, handling Store Liveness messages, withdrawing support, and adding and removing stores to request support from. Scheduling these actions to run periodically in a single goroutine serializes them and simplifies the concurrency model.

Part of: #125063

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
I haven't looked closely at the tests yet, but flushing review comments for the rest of the PR.

> Reviewed 7 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-:-O5F0xFm7zQcmQCqLs0R:b-f0ex4o)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5Evg0l8gXUDbffHdG3:-O5Evg0l8gXUDbffHdG4:b-dgab9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/requester_state.go#L52)):*
> ```Go
> 	// requesterState is the source of truth for requested support.
> 	requesterState    requesterState
> 	recentlyRequested map[slpb.StoreIdent]bool
> ```

Could we give this field a comment which describes the role of the map and its relationship to `requesterState`?

EDIT: see comment below first.
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5EvVJGCOkG_bWqU6i0:-O5EvVJGCOkG_bWqU6i1:bc1c91l) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/requester_state.go#L110)):*
> ```Go
> 	rsh.mu.Lock()
> 	defer rsh.mu.Unlock()
> 	rsh.recentlyRequested[id] = true
> ```

We had talked about how a separate map would allow for inconsistencies between `requesterState.supportFrom` and `recentlyRequested`. I guess it's fine if a store is in `recentlyRequested` but not `requesterState.supportFrom`, as any inconsistency in that direction will be resolved by `removeIdleStores` soon.

However, the opposite is not fine. If a store is missing from `recentlyRequested` but not `requesterState.supportFrom`, the idle store will never be recognized. Currently, it seems like that's possible if `addStore` is called for an id, but `getSupportFrom` is never called.

I'm also wondering whether we should be deleting from `recentlyRequested` in `removeIdleStores`.

Based on a quick reading of this, it does feel like two maps raises more questions than it avoids. Were there downsides to a single map with a `struct{state slpb.SupportState, recentlyRequested bool}` value?
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5Ezeq-BVtS-odP4CF3:-O5Ezeq-BVtS-odP4CF4:b-m8flax) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/support_manager.go#L112)):*
> ```Go
> var _ MessageHandler = (*SupportManager)(nil)
> 
> // SupportFromEnabled implements the Fabric interface and determines if Store
> ```

small nit: move this below `SupportFrom` to keep the methods in the same order as in the interface definition.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5Ezpt90vXRk3x513pO:-O5Ezpt90vXRk3x513pP:bs3zx10) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/support_manager.go#L141)):*
> ```Go
> 		// If this is the first time SupportFrom has been called for this store,
> 		// the store will be added to requesterStateHandler before the next
> 		// round of heartbeats.
> ```

Could we add a note about how this can race if there are concurrent calls to `SupportFrom` for the same ID, but that it's ok because 1. storesToAdd ignores duplicates, and 2. `maybeAddStores` tolerates existing stores?
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5F-4BACcZsisxfYuNb:-O5F-4BACcZsisxfYuNc:b-7iuba8) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/support_manager.go#L147)):*
> ```Go
> 	// An empty expiration implies support has expired.
> 	if ss.Expiration.IsEmpty() {
> 		return slpb.Epoch(0), hlc.Timestamp{}, false
> ```

nit: `return 0, hlc.Timestamp{}, false`
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5F-Auf0EJ3SST5j0p0:-O5F-Auf0EJ3SST5j0p1:bmttpeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/support_manager.go#L154)):*
> ```Go
> // Start starts the main processing goroutine in startLoop as an async task.
> func (sm *SupportManager) Start(ctx context.Context) error {
> 	if err := sm.onRestart(ctx); err != nil {
> ```

Let's add a comment here explaining why we run this synchronously and not async at the beginning of the `startLoop`.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5F-roGBNWqpv0h7nC_:-O5F-roGBNWqpv0h7nCa:b-fh9amr) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/support_manager.go#L202)):*
> ```Go
> // simplifies the concurrency model.
> func (sm *SupportManager) startLoop(ctx context.Context) {
> 	var heartbeatTimer timeutil.Timer
> ```

If we are never changing the interval for any of these, we could use `time.Ticker`s ([docs](https://pkg.go.dev/time#Ticker)). Tickers have the advantage of not allowing errors to compound. They also don't require the `.Read = true` or `Reset` calls down below.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5F0T_NEt3r_s73Pdwd:-O5F0T_NEt3r_s73Pdwe:bhmrx8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/support_manager.go#L271)):*
> ```Go
> 	heartbeats := rsfu.getHeartbeatsToSend(sm.storeID, sm.clock.Now(), livenessInterval)
> 	if err := rsfu.write(ctx, sm.engine); err != nil {
> 		log.Warningf(ctx, "failed to write requester meta: %v", err)
> ```

Aren't we leaking the `rsfu` on this path? Same thing in a few other places in this file.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129090)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5EvVJGCOkG_bWqU6i0:-O5K3NhT9_lCLdeso61j:b-nlb9e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/requester_state.go#L110)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We had talked about how a separate map would allow for inconsistencies between `requesterState.supportFrom` and `recentlyRequested`. I guess it's fine if a store is in `recentlyRequested` but not `requesterState.supportFrom`, as any inconsistency in that direction will be resolved by `removeIdleStores` soon.

However, the opposite is not fine. If a store is missing from `recentlyRequested` but not `requesterState.supportFrom`, the idle store will never be recognized. Currently, it seems like that's possible if `addStore` is called for an id, but `getSupportFrom` is never called.

I'm also wondering whether we should be deleting from `recentlyRequested` in `removeIdleStores`.

Based on a quick reading of this, it does feel like two maps raises more questions than it avoids. Were there downsides to a single map with a `struct{state slpb.SupportState, recentlyRequested bool}` value?
</blockquote></details>

I tried the single-map approach and I do like it better than the two maps (potentially going out of sync). But I am a little concerned about the new write locks on `requesterStateHandler.mu`. While before in order to remove a store we only grabbed the write lock for a short duration, now we hold it while iterating over all stores in `removeIdleStores`; all the while blocking `SupportFrom` calls. Maybe there's no way around this if we want to have the support state and recently requested together.

Somewhat unrelated, it seems like regardless of which mutex we hold for updating `recentlyRequested` in `SupportFrom`, it will result in concurrent calls waiting for each other. A separate mutex per store just for the purposes of `recentlyRequested` could probably help, but maybe it's too much complexity.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5F-roGBNWqpv0h7nC_:-O5K5N9n7lbRrDMGQ-Mm:b-3anc7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/support_manager.go#L202)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we are never changing the interval for any of these, we could use `time.Ticker`s ([docs](https://pkg.go.dev/time#Ticker)). Tickers have the advantage of not allowing errors to compound. They also don't require the `.Read = true` or `Reset` calls down below.
</blockquote></details>

I like these!
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5F0T_NEt3r_s73Pdwd:-O5K5PGT4OFm4iJFlf50:bsc94vd) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/support_manager.go#L271)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Aren't we leaking the `rsfu` on this path? Same thing in a few other places in this file.
</blockquote></details>

Yes, good catch! This `write` call should also use `batch` and not `sm.engine`. I will fix these and add tests in a separate PR since this one is getting too large.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129090)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5EvVJGCOkG_bWqU6i0:-O5KNRrTAKcBHD-ryUwh:b-rxfs9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/requester_state.go#L110)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

I tried the single-map approach and I do like it better than the two maps (potentially going out of sync). But I am a little concerned about the new write locks on `requesterStateHandler.mu`. While before in order to remove a store we only grabbed the write lock for a short duration, now we hold it while iterating over all stores in `removeIdleStores`; all the while blocking `SupportFrom` calls. Maybe there's no way around this if we want to have the support state and recently requested together.

Somewhat unrelated, it seems like regardless of which mutex we hold for updating `recentlyRequested` in `SupportFrom`, it will result in concurrent calls waiting for each other. A separate mutex per store just for the purposes of `recentlyRequested` could probably help, but maybe it's too much complexity.
</blockquote></details>

Also, one downside of the single map is that we can no longer depend on the assumption that if there is an update checked out, no one will write to `supportFrom`. Now `SupportFrom` invocations write to `supportFrom`, as we see in the race condition failure in CI.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129090)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5EvVJGCOkG_bWqU6i0:-O5Te19dDFVWy5iDDpoT:b59go2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/45e3eee8d12a7b945e039ca9c3171653e8ad58ef/pkg/kv/kvserver/storeliveness/requester_state.go#L110)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Also, one downside of the single map is that we can no longer depend on the assumption that if there is an update checked out, no one will write to `supportFrom`. Now `SupportFrom` invocations write to `supportFrom`, as we see in the race condition failure in CI.
</blockquote></details>

Decided on a single-map and single-mutex approach offline.

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 12 files at r1, 3 of 9 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129090)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UKM2aEbQI6s2CtD_7:-O5UKM2aEbQI6s2CtD_8:b-6qjtsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/requester_state.go#L45)):*
> ```Go
> 	// because it is not updated as part of the support state and meta process;
> 	// it is written to in SupportFrom, so it's important that it doesn't lock
> 	// requesterStateHandler.mu for writing.
> ```

It does require the mutex to be held in read-mode, right?
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 124 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UKapLDuU3li2MAFxR:-O5UKapLDuU3li2MAFxS:b4dy616) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/requester_state.go#L124)):*
> ```Go
> 	defer rsh.mu.RUnlock()
> 	rs, ok := rsh.requesterState.supportFrom[id]
> 	supportState := slpb.SupportState{}
> ```

nit: `var supportState slpb.SupportState` is a bit more of an idiomatic way to declare an uninitialized variable.
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UKqRD9yjdEIAaV8ag:-O5UKqRD9yjdEIAaV8ah:burgi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/requester_state.go#L170)):*
> ```Go
> 	defer rsh.mu.Unlock()
> 	for id, rs := range rsh.requesterState.supportFrom {
> 		if !rs.recentlyQueried.Load() {
> ```

This will be more important when we address your TODO above, but let's use `rs.recentlyQueried.Swap(false)` here to avoid two atomic operations.
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5ULNJc2QWQBAFA-aVk:-O5ULNJc2QWQBAFA-aVl:b-j33ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/requester_state.go#L216)):*
> ```Go
> 		rs, ok = rsfu.checkedIn.supportFrom[storeID]
> 	}
> 	supportState := slpb.SupportState{}
> ```

nit: same comment as above about `var supportState slpb.SupportState`.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5ULrRG6Vjkm8jj4Tbv:-O5ULrRG6Vjkm8jj4Tbw:b-vfl7s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/support_manager.go#L158)):*
> ```Go
> 	// onRestart is called synchronously before the start of the main loop in
> 	// order to ensure the SupportManager has loaded all persisted state into
> 	// memory before answering SupportFrom and SupportFor requests.
> ```

It's also important for the clock manipulation, right?
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 322 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UMINU70TTtjBzdeMf:-O5UMINU70TTtjBzdeMg:b-uj9h0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/support_manager.go#L322)):*
> ```Go
> 
> 	// TODO(mira): handle the errors below (and elsewhere in SupportManager)
> 	// properly by resetting the update in progress. Also, use batch not engine.
> ```

I feel like we should address the "batch not engine" TODO right now, because it's a pretty bad bug.
___
*[`pkg/kv/kvserver/storeliveness/support_manager_test.go` line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UWXM5A4o6-mZ2epNm:-O5UWXM5A4o6-mZ2epNn:b-t273gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/support_manager_test.go#L36)):*
> ```Go
> 	remoteStore = slpb.StoreIdent{NodeID: roachpb.NodeID(2), StoreID: roachpb.StoreID(2)}
> 	options     = Options{
> 		HeartbeatInterval:       30 * time.Millisecond,
> ```

Any reason not to drop these even lower (maybe 10x lower) to speed up the tests?

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129090)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UKM2aEbQI6s2CtD_7:-O5U_FlU4oODn7hGPOiw:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/requester_state.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It does require the mutex to be held in read-mode, right?
</blockquote></details>

Yes.
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 124 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UKapLDuU3li2MAFxR:-O5UaqxC3tPBYLDmqO95:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/requester_state.go#L124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `var supportState slpb.SupportState` is a bit more of an idiomatic way to declare an uninitialized variable.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UKqRD9yjdEIAaV8ag:-O5UauJqEf4eODLpWsU3:bxhqrqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/requester_state.go#L170)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This will be more important when we address your TODO above, but let's use `rs.recentlyQueried.Swap(false)` here to avoid two atomic operations.
</blockquote></details>

Done. Thoughts on addressing the TODO now vs. only if we need to?
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5ULNJc2QWQBAFA-aVk:-O5Ub3384v7MtzI9u8HK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/requester_state.go#L216)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: same comment as above about `var supportState slpb.SupportState`.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5ULrRG6Vjkm8jj4Tbv:-O5UbrMi3RO2ay1CwfoD:bb7867z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/support_manager.go#L158)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's also important for the clock manipulation, right?
</blockquote></details>

Yup.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 322 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UMINU70TTtjBzdeMf:-O5Ub_M74L9ljwje7D4g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/support_manager.go#L322)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I feel like we should address the "batch not engine" TODO right now, because it's a pretty bad bug.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/storeliveness/support_manager_test.go` line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UWXM5A4o6-mZ2epNm:-O5Uc9BM2rLBxGkVsrFv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/support_manager_test.go#L36)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any reason not to drop these even lower (maybe 10x lower) to speed up the tests?
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-:-O5Vjles2uR5aezbtd4E:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129090#-O5UKqRD9yjdEIAaV8ag:-O5VjGbdACgH9jFROQvS:b-6o1lgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2aa1b2cb643d9219740ea37b3e158b5e8fbee4/pkg/kv/kvserver/storeliveness/requester_state.go#L170)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Done. Thoughts on addressing the TODO now vs. only if we need to?
</blockquote></details>

I don't think we need to do it in this PR, but it's probably best to just do this now so that we don't need to remind ourselves of this in a few years when we see mutex contention on the request path (through calls to `SupportFrom`) that only shows up in very large clusters.

**Comment by miraradeva** [comment]
bors r=nvanbenschoten

**Pull request merged**
