### PR TITLE
storage: remove pointers from allocator returns

### PR DESCRIPTION
**Pull request by BramGruneir**
Specifically, remove them from RebalanceTarget and AllocateTarget.

Part of #10275.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11206)

### CODE REVIEW

**Comment by petermattis** [comment]
I'm missing the motivation for this change. Returning a pointer nicely captures the optionality of the return value. And returning the structure is actually a pessimization as it consumes more stack space (which isn't a big deal for this code, but still).

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-:-KXHSkztxwhJaAri88Af:b-qm3ic7)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 250 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXHSo7POi898xDgpg9i:-KXHSo7POi898xDgpg9j:b-kmvbn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacffff0e9119699e32cc7ceb0ee269e8ba162f9/pkg/storage/allocator.go#L250)):*
> ```Go
> 	for attrs := constraints.Constraints; ; attrs = attrs[:len(attrs)-1] {
> 		filteredSL := sl.filter(config.Constraints{Constraints: attrs})
> 		if target := a.selectGood(filteredSL, existingNodes); target != nil {
> ```

why not propagate the move to values to `selectGood`?

---

*[pkg/storage/allocator.go, line 382 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXHScAB1hPOK6EdrLD-:-KXHScAB1hPOK6EdrLD0:b3fefg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacffff0e9119699e32cc7ceb0ee269e8ba162f9/pkg/storage/allocator.go#L382)):*
> ```Go
> 	leaseStoreID roachpb.StoreID,
> 	rangeID roachpb.RangeID,
> ) (bool, roachpb.StoreDescriptor, error) {
> ```

why the unusual order of returns?

---

*[pkg/storage/allocator.go, line 483 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXHSy_6tsCwxskSO9iR:-KXHSy_6tsCwxskSO9iS:bcz3rs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacffff0e9119699e32cc7ceb0ee269e8ba162f9/pkg/storage/allocator.go#L483)):*
> ```Go
> 		existingNodes[repl.NodeID] = struct{}{}
> 	}
> 	improve := a.improve(sl, existingNodes)
> ```

why not propagate the move to values to `improve`?

---

*[pkg/storage/allocator_test.go, line 313 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXHTEeRhNZIInekh3IO:-KXHTEeRhNZIInekh3IP:b2hpddt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacffff0e9119699e32cc7ceb0ee269e8ba162f9/pkg/storage/allocator_test.go#L313)):*
> ```Go
> 			false,
> 		)
> 		if result.StoreID != 0 {
> ```

`result != (roachpb.ReplicaDescriptor{})`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206)*

**Comment by BramGruneir** [comment]
Unless I'm mistaken, using a pointer to show that a value was retrieved or not is considered a go anti-pattern and the preferred pattern is to return a boolean as well.

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator.go, line 250 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXHSo7POi898xDgpg9i:-KXHdB83AWNxBLPEWdFT:b-mkx3ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacffff0e9119699e32cc7ceb0ee269e8ba162f9/pkg/storage/allocator.go#L250)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why not propagate the move to values to `selectGood`?
</details>
Seemed like it was unnecessary considering that we are going to be moving to the rule solver.  But since this might be a while.  Done.

---

*[pkg/storage/allocator.go, line 382 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXHScAB1hPOK6EdrLD-:-KXHh4FD6sht0nsx3W5S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacffff0e9119699e32cc7ceb0ee269e8ba162f9/pkg/storage/allocator.go#L382)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why the unusual order of returns?
</details>
Done.

---

*[pkg/storage/allocator.go, line 483 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXHSy_6tsCwxskSO9iR:-KXHh52z51R42ZjGazTa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacffff0e9119699e32cc7ceb0ee269e8ba162f9/pkg/storage/allocator.go#L483)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why not propagate the move to values to `improve`?
</details>
Done.

---

*[pkg/storage/allocator_test.go, line 313 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXHTEeRhNZIInekh3IO:-KXHhCetb0icErCYUr_l:bceot3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacffff0e9119699e32cc7ceb0ee269e8ba162f9/pkg/storage/allocator_test.go#L313)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `result != (roachpb.ReplicaDescriptor{})`
</details>
Had to use deepEqual.  :( 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-:-KXHc_um-RrZ9Lx-aUkh:b-uf9ikf)*

**Comment by petermattis** [comment]
> Unless I'm mistaken, using a pointer to show that a value was retrieved or not is considered a go anti-pattern and the preferred pattern is to return a boolean as well.

I'm not aware of that. The Go stdlib certainly uses sentinels instead of a separate return value in various places. For example, [`strings.Index`](https://golang.org/pkg/strings/#Index) returns `-1` if the string can't be found. I don't see a significant difference in using a `nil` pointer return value to indicate not found. I'm thumbs down on this change, particularly now when we have so many other moving parts in this area of the code.

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator_test.go, line 313 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXHTEeRhNZIInekh3IO:-KXHoIgwIvn_vommKk59:bdwq3st) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacffff0e9119699e32cc7ceb0ee269e8ba162f9/pkg/storage/allocator_test.go#L313)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Had to use deepEqual.  :( 
</details>
Yet another reason against this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206)*

**Comment by tamird** [comment]
I think those examples from the standard library aren't exactly canon - there's a lot of junk in the stdlib that was written early and can't be changed. That said, I'm also thumbs down on this as-written for reasons elaborated on in another comment.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator.go, line 484 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXI4OS5bJqXaOUlzLcQ:-KXI4OS5bJqXaOUlzLcR:b80sqia) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7b22207957e6f26672d185918afcfc1337b13c/pkg/storage/allocator.go#L484)):*
> ```Go
> 		existingNodes[repl.NodeID] = struct{}{}
> 	}
> 	if improve, ok := a.improve(sl, existingNodes); ok {
> ```

isn't this equivalent to
```
improve, ok := a.improve(sl, existingNodes)
return improve, ok, nil
```

---

*[pkg/storage/allocator_test.go, line 313 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXHTEeRhNZIInekh3IO:-KXI4ccbNYuJNyhVGSaQ:byixjt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacffff0e9119699e32cc7ceb0ee269e8ba162f9/pkg/storage/allocator_test.go#L313)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Yet another reason against this change.
</details>
Yeah, this stinks - changing things to return values only makes sense when you're able to change the entire chain - that is, if you're dereferencing anything _anywhere_ to do it, you've probably already pessimized it. The same is true of the use of a boolean - either use it everywhere, or you end up with fragile or slow patterns like `reflect.DeepEqual()` or `.StoreID == 0`.

---

*[pkg/storage/balancer.go, line 42 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXI8NU3J_MPri5FEauM:-KXI8NU3J_MPri5FEauN:b-trtt7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7b22207957e6f26672d185918afcfc1337b13c/pkg/storage/balancer.go#L42)):*
> ```Go
> 
> func formatCandidates(
> 	selected roachpb.StoreDescriptor, candidates []roachpb.StoreDescriptor,
> ```

another example of an interface that would need to change if this were to move to values - you'd probably want to pass `selected`'s index in `candidates` rather than the value itself.

---

*[pkg/storage/balancer.go, line 103 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXI9-HEbYAXF8rkbrcz:-KXI9-HEbYAXF8rkbrd-:b-fcfl05) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7b22207957e6f26672d185918afcfc1337b13c/pkg/storage/balancer.go#L103)):*
> ```Go
> 		// than the average numbers of ranges.
> 		candidates := make([]roachpb.StoreDescriptor, 0, len(sl.stores))
> 		for i := range sl.stores {
> ```

`for _, candidate := range ...`?

---

*[pkg/storage/balancer.go, line 115 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-KXI9MA7HVPx1f0R5JQf:-KXI9MA7HVPx1f0R5JQg:b-srq48w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e7b22207957e6f26672d185918afcfc1337b13c/pkg/storage/balancer.go#L115)):*
> ```Go
> 			// candidates.
> 			bad = candidates[rcb.rand.Intn(len(candidates))]
> 			ok = true
> ```

this is odd. `bad` and `ok` are way more broadly scoped than they need to be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-:-KXI7A8t9BGURy2LoErM:b-rw2r0f)*

**Comment by petermattis** [comment]
> I think those examples from the standard library aren't exactly canon - there's a lot of junk in the stdlib that was written early and can't be changed. 

No, those examples aren't canon and neither is the stdlib, but returning pointers is very common. I don't think we should be changing code like this unless there is a very compelling reason. For example, a `nil` return value doesn't make sense or returning a pointer incurs an allocation which has been shown to be costly via profiling. 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11206#-:-KXIwdti3X89sSV0b-OW:b-yww06z)*

**Comment by tamird** [comment]
Yes, that's a sensible argument. I don't particularly feel strongly about
this change one way or the other, but I wanted to enumerate the rationale
one might consider.

**Comment by BramGruneir** [comment]
ok, I'm going to close this.  Maybe revisit it once the rest of the changes to allocator are complete.

**Pull request closed without merging**
