### PR TITLE
sql: use FastIntMap for column id -> idx maps

### LINKED ISSUE #37801: sql: replace all map[sqlbase.ColumnID]int types with util.FastIntMap
`pkg/sql` is littered with mappings from column IDs to projection/row/other indexes. The package uses the type `map[sqlbase.ColumnID]int` to represent these mappings.

In almost all cases, we would be better off using `util.FastIntMap`, which can avoid a map allocation if the column ID never goes above 31 and the index never goes above 14. Any table that wouldn't be considered "wide" meets these requirements.

We should replace all instances of `map[sqlbase.ColumnID]int` with a `util.FastIntMap` in `pkg/sql`. It looks like `pkg/sql/opt` already does this and aliases `util.FastIntMap` to `ColMap`. We might consider sharing the same alias across these packages.

cc. @jordanlewis @RaduBerinde is there any reason that I'm missing not to do this?

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit replaces the use of map[ColumnID]int for maps of column id
to ordinal with the use of FastIntMap, to save on allocations in common
cases.

Closes #37801

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
I don't think that it's necessary to make a typed wrapper. The casts are free - I checked the assembly!

**Review by mgartner — APPROVED** [review]
:lgtm: 

> I don't think that it's necessary to make a typed wrapper. The casts are free - I checked the assembly!

I think the goal for the wrappers is more about convenience and safety rather than performance. @raduberinde may have a stronger argument for them — I know he is a fan. Related discussion: https://github.com/cockroachdb/cockroach/pull/49819#discussion_r434863592

> Reviewed 44 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56639#-:-MM3JNRY8eGbpJAZiGAL:b8shsyo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/row/fetcher_mvcc_test.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56639#-MM70EzoCacFpMTBkvzj:-MM70Ezp85cDkWad_3GU:b-tw67nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c39e3d2aea0d1c8bd7af585605c40b4a712d7f8/pkg/sql/row/fetcher_mvcc_test.go#L93)):*
> ```Go
> 	var args []row.FetcherTableArgs
> 	for _, desc := range []*tabledesc.Immutable{parentDesc, childDesc} {
> 		colIdxMap := util.FastIntMap{}
> ```

Any reason you initialize like this in tests but like `var colIdxMap util.FastIntMap` in non-test code? There's no difference under the hood is there?
___
*[pkg/sql/rowexec/joinreader.go, line 402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56639#-MM70yfXCyzUjHyLgu2J:-MM70yfXCyzUjHyLgu2K:bsakeiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c39e3d2aea0d1c8bd7af585605c40b4a712d7f8/pkg/sql/rowexec/joinreader.go#L402)):*
> ```Go
> 		return nil
> 	})
> 	return cols, err
> ```

Should this function return an error if `err` will always be `nil`? I suppose someone could come along and change the `RunOverAllColumns` callback so that errors can be produced and forget to un-ignore the err. I'm not sure what is most idiomatic in this case.

**Comment by nvanbenschoten** [comment]
This is great! We can close https://github.com/cockroachdb/cockroach/issues/37801 once this merges, right?

**Comment by jordanlewis** [comment]
I forgot about that issue - yes, this will close it.

**Review by ajwerner — COMMENTED** [review]
I also have a slight preference for a strongly typed wrapper but am willing to acquiesce if you feel it is too big of a lift. It will make the code more readable and clearly indicate what the mapping is used for. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56639#-:-MMHHpWz9Vjpm-GfA-FN:bpvdyej)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @mgartner)

**Comment by jordanlewis** [comment]
I'm happy to make that change. Main reason I haven't is that I'm not sure what the most appropriate package would be. @ajwerner could you suggest an appropriate package for the typed wrapper? The `colset` lives in `schemaexpr`, I'm not sure if this is an appropriate place for this one.

**Comment by jordanlewis** [comment]
also cc @yuzefovich if you have opinions about where such a wrapper should live.

**Comment by ajwerner** [comment]
> I'm happy to make that change. Main reason I haven't is that I'm not sure what the most appropriate package would be. @ajwerner could you suggest an appropriate package for the typed wrapper? The `colset` lives in `schemaexpr`, I'm not sure if this is an appropriate place for this one.

put it in `pkg/sql/catalog`, @mgartner moved ColSet to that package in https://github.com/cockroachdb/cockroach/pull/56660.

**Review by mgartner — COMMENTED** [review]
@jordanlewis I've moved the `TableColSet` to the `catalog` package in #56660. It did not belong in `schemaexpr` (there's some more refactoring to be done in `schemaexpr` too... looks like it got a bit disorganized).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56639#-:-MMHILra7O_VjmaIevyR:bwekjpb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @mgartner)

**Comment by yuzefovich** [comment]
`sql/catalog` sounds good to me

**Review by mgartner — APPROVED** [review]
> Reviewed 54 of 54 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56639)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

**Pull request merged**
