### PR TITLE
raft: don't propose config changes with regressed lead support

### LINKED ISSUE #125355: kv/raft: support configuration changes for leader leases
**Is your feature request related to a problem? Please describe.**

Part of https://github.com/cockroachdb/cockroach/issues/123847

Relates to https://github.com/cockroachdb/cockroach/issues/125264
Relates to https://github.com/cockroachdb/cockroach/issues/125263

This will likely just be adding test cases for configuration changes and asserting the QSE is as expected.

Jira issue: CRDB-39406

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by nvb**
Fixes #125355.

If the lead support has not caught up from the previous configuration, we must not propose another configuration change. Doing so would compromise the lead support promise made by the previous configuration and used as an expiration of a leader lease. Instead, we wait for the lead support under the current configuration to catch up to the maximum lead support reached under the previous config. If the lead support is never able to catch up, the leader will eventually step down due to CheckQuorum.

As a reminder, if we reject a config change, it will be reproposed again shortly, at which point the lead support will likely have caught up.

As a second reminder, we fortify both voters and learners. We also always add new replicas as learners before promoting them to voters. The combination here means that a leader will commonly already be supported a voter when it is promoted added to the lead support computation.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
@arulajmani I've rebased this on master and added unit tests + datadriven tests, so this should be good for a review.

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r5, 4 of 4 files at r6, 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132150#-:-O9LVA__DjgIUnEOKI_Y:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/testdata/confchange_fortification_safety.txt` line 114 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/132150#-O9LUs6hDVkQcjJiV8gt:-O9LUs6hDVkQcjJiV8gu:bbvk1i1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b240473a6849f6ab469eb5623faccd8e290103/pkg/raft/testdata/confchange_fortification_safety.txt#L114)):*
> ```help
> 
> # Try to demote v2. This should be rejected because v1's lead support under the
> # current config has not caught up to the previous config.
> ```

nit: consider printing out the `fortification-state` to make this easy to glean. 
___
*[`pkg/raft/testdata/confchange_fortification_safety.txt` line 177 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/132150#-O9LV7KH4ADFv2AVwKla:-O9LV7KH4ADFv2AVwKlb:b25co7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b240473a6849f6ab469eb5623faccd8e290103/pkg/raft/testdata/confchange_fortification_safety.txt#L177)):*
> ```help
>   4->1 MsgAppResp Term:1 Log:0/5 Commit:4
> 
> # Try to demote v2 again. This time, the proposal should be allowed.
> ```

nit: maybe `fortification-state` here as well. 
___
*[`pkg/raft/tracker/fortificationtracker_test.go` line 547 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/132150#-O9LU4X7Bhh4382PbeMj:-O9LU4X7Bhh4382PbeMk:bikjo9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b240473a6849f6ab469eb5623faccd8e290103/pkg/raft/tracker/fortificationtracker_test.go#L547)):*
> ```Go
> 		{
> 			afterConfigChange: func(sl *mockStoreLiveness, ft *FortificationTracker) {
> 				// r4 fortified, but support still lagging.
> ```

nit: is this meaningfully different than the previous test case?

**Review by nvb — COMMENTED** [review]
TFTR!

bors r=arulajmani

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132150#-:-O9LizRKBK-Q6wjls4cX:be4m769)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/testdata/confchange_fortification_safety.txt` line 114 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/132150#-O9LUs6hDVkQcjJiV8gt:-O9LixjW3hpZTo9g01Vv:b-tb4n8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b240473a6849f6ab469eb5623faccd8e290103/pkg/raft/testdata/confchange_fortification_safety.txt#L114)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: consider printing out the `fortification-state` to make this easy to glean.
</blockquote></details>

Nice idea. Done.
___
*[`pkg/raft/testdata/confchange_fortification_safety.txt` line 177 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/132150#-O9LV7KH4ADFv2AVwKla:-O9Liyeh0ivKUoqyHTS1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b240473a6849f6ab469eb5623faccd8e290103/pkg/raft/testdata/confchange_fortification_safety.txt#L177)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: maybe `fortification-state` here as well.
</blockquote></details>

Done.
___
*[`pkg/raft/tracker/fortificationtracker_test.go` line 547 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/132150#-O9LU4X7Bhh4382PbeMj:-O9LiiOX4TK8waBjPD7D:b9ujtwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b240473a6849f6ab469eb5623faccd8e290103/pkg/raft/tracker/fortificationtracker_test.go#L547)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: is this meaningfully different than the previous test case?
</blockquote></details>

Not meaningfully. Removed.

**Review by arulajmani — APPROVED** [review]
> Reviewed 11 of 11 files at r8, 4 of 4 files at r9, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132150)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
