### PR TITLE
storage: remove last part of the TestTransferRaftLeadership test

### PR DESCRIPTION
**Pull request by ghost**
Removing the last part of `TestTransferRaftLeadership`.
Removing `RaftTransferLeader` as well to get rid of lint error.

Issue: #25788.
Release note: None

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26507#-:-LEPrL8O9JeD-VCpaqVu:bnfp4nl)*

**Comment by windchan7** [comment]
Thanks, Ben.

bors r+

**Comment by windchan7** [comment]
Failed due to #26304

**Pull request merged**
