### PR TITLE
server: add SQL STATS COMPACTION to automatic job list

### PR DESCRIPTION
**Pull request by Azhng**
Previously, SQL STATS COMPACTION job was not marked as automatic
job. This means SQL STATS COMPACTION job would show up in the
Jobs Page in DB Console and in the output of SHOW JOBS.
This commit adds SQL STATS COMPACTION to a list of automatic
jobs (e.g. auto table stats). This means SQL STATS COMPACTION
job information would only be present in the output of
SHOW AUTOMATIC JOBS.

Release justification: Bug fixes and low-risk updates to new
functionality

Release note (sql change): SQL STATS COMPACTION job now only shows
up in the output of SHOW AUTOMATIC JOBS.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69641)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-MiSWE-27yviJi_41SJx):*
This patch doesn't change this behaviour, does it? Automatic jobs still show up in DB Console, right? Isn't that something we want to do in the future? If so, let's remove the reference to DB console in the commit message. 
___
*[pkg/jobs/jobspb/wrap.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-MiSWtVR0SpP2kMkzG2z:-MiSWtVR0SpP2kMkzG3-:b-dw4wzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/64c12fa5066acaaea6358861ab76d0efe98d3e0a/pkg/jobs/jobspb/wrap.go#L77)):*
> ```Go
> 	TypeAutoCreateStats,
> 	TypeAutoSpanConfigReconciliation,
> 	TypeSQLStatsCompaction,
> ```

Let's add a test for this? If we have the compaction job running we should be able to see it in the result of `SHOW AUTOMATIC JOBS`
___
*[pkg/server/admin_test.go, line 1546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-MiSWfsR5A54kC7OXJet:-MiSWfsR5A54kC7OXJeu:b-g6rcj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/64c12fa5066acaaea6358861ab76d0efe98d3e0a/pkg/server/admin_test.go#L1546)):*
> ```Go
> 		},
> 		{
> 			fmt.Sprintf("jobs?type=%d", jobspb.TypeSQLStatsCompaction),
> ```

I don't follow what this is testing, could you say more (and maybe add a comment)?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69641)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-MiSWE-27yviJi_41SJx):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This patch doesn't change this behaviour, does it? Automatic jobs still show up in DB Console, right? Isn't that something we want to do in the future? If so, let's remove the reference to DB console in the commit message. 
</blockquote></details>

Done.
___
*[pkg/jobs/jobspb/wrap.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-MiSWtVR0SpP2kMkzG2z:-MiT4XmG-Y-JBpc4WrrP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64c12fa5066acaaea6358861ab76d0efe98d3e0a/pkg/jobs/jobspb/wrap.go#L77)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's add a test for this? If we have the compaction job running we should be able to see it in the result of `SHOW AUTOMATIC JOBS`
</blockquote></details>

Done.
___
*[pkg/server/admin_test.go, line 1546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-MiSWfsR5A54kC7OXJet:-MiT4Ya1ElUKUtVqVdQ_:bbnzdbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/64c12fa5066acaaea6358861ab76d0efe98d3e0a/pkg/server/admin_test.go#L1546)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't follow what this is testing, could you say more (and maybe add a comment)?
</blockquote></details>

Removed this. I misunderstood that this is to hide the jobs from the Jobs Page. 

Added test in `compaction_test.go`.

**Review by maryliag — APPROVED** [review]
:lgtm: 
make sure to get approval from @arulajmani  too

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-:-MiTBfkg0rz91L0ndFo-:b-ndvtx4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @Azhng)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-MiTBqwx2FJ3SAVcSZyX):*
typo: show up in the output

**Review by arulajmani — COMMENTED** [review]
Now that we're saying that this job is an automatic job, much like the `AUTO SPANCONFIG RECONCILIATION` and `AUTO CREATE STATS`, should we be prefixing the word `AUTO` in the protos relating to the `SQL STATS COMPACTION` job? I was thinking the job types, progress, and payload related protos? It would be nice to be consistent through the various layers here. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-:-MiTHBQ07LKPaXmqEU-w:bpay45y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_test.go, line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-MiTGp9f73-S28LqXjiM:-MiTGp9f73-S28LqXjiN:b-sg81lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/93bb45185bbf307acfdcf91bf9fff427bfc5cf95/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L273)):*
> ```Go
> 	)
> 
> 	// Ensure the sqlstats job is hidden from the SHOW JOBS command.
> ```

Is it worth pulling this test out in its own thing or are we fine reusing this existing test for the `SHOW AUTOMATIC JOBS` semantics?

**Review by Azhng — COMMENTED** [review]
Renames all sql stats-related jobs proto fields to include `AUTO` 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-:-MiTRxIO4MYTsJ68iD9c:buruwnv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @maryliag)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-MiTBqwx2FJ3SAVcSZyX):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

typo: show up in the output
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_test.go, line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-MiTGp9f73-S28LqXjiM:-MiTNFBUEsWs3vfF0W2Q:bcapk4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/93bb45185bbf307acfdcf91bf9fff427bfc5cf95/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L273)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is it worth pulling this test out in its own thing or are we fine reusing this existing test for the `SHOW AUTOMATIC JOBS` semantics? 
</blockquote></details>

No strong preference for either here. Pulled it out to its own test.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

Thanks for making this change! 

> Reviewed 6 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-:-MiU2qJwDh18GiJ3w4D9:b-fyqp45)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @maryliag)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69641#-:-MiWxj5x-rW27Xp7g16U:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani and @maryliag)

**Comment by Azhng** [comment]
TFTR!

bors r=maryliag,arulajmani,ajwerner

**Pull request merged**
