### PR TITLE
sql: group statement statistics based on its transaction fingerprintID

### PR DESCRIPTION
**Pull request by Azhng**
Depends on #69710

# First Commit

sql: plumb sqlstats.TestingKnobs down into ssmemstorage

This commit plumbs sqlstats.TestingKnobs into ssmemstorage
in order to allow later unit tests to manipulate times in the
tests.

Release note: None

# Second Commit

sql: remove GetStatementStats and GetTransactionStats API

Previsously, we had GetStatementStats and GetTransactionStats
exported as part of the interface for SQL Stats subsystem.
These two methods are only used within tests and nowhere else
in the code base.
This commit removes those two exported methods and rewrite the
tests to use the iterator API.

Release note: None

# Third Commit

sql: group statement statistics based on its transaction fingerprintID

Previously, statement that are executed as part of different
transactions are grouped together resulting in one single
stats entry. This results in weird UX and makes it difficult
for developer to debug slow queries.
This commit groups statement statsitics based on its transaction
fingerprintIDs on top of the statement fingerprint ID.

Partially addresses #65106, #59205

Release note (bug fix): statement statsitics are now grouped by
the statement's corresponding transaction fingerprints.

### CODE REVIEW

**Review by matthewtodd — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r2, 2 of 12 files at r6, 31 of 31 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70261)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/executor_statement_metrics.go, line 167 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL6-9eAyZzs2b65dUn:-MlL6-9eAyZzs2b65dUo:bbw6rtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/executor_statement_metrics.go#L167)):*
> ```Go
> 	// implicit transaction.
> 	//
> 	// TODO(azhng): this will require some big refactoring later, we already
> ```

nit: this -> This
___
*[pkg/sql/executor_statement_metrics.go, line 168 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL61kTBDV2Bk-ChsZ-:-MlL61kTBDV2Bk-ChsZ0:bwiiwvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/executor_statement_metrics.go#L168)):*
> ```Go
> 	//
> 	// TODO(azhng): this will require some big refactoring later, we already
> 	//  computes statement's fingerprintID in RecordStatement().
> ```

nit: computes -> compute
___
*[pkg/sql/executor_statement_metrics.go, line 168 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL661u4A-W_fMKmzJw:-MlL661u4A-W_fMKmzJx:brvh1y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/executor_statement_metrics.go#L168)):*
> ```Go
> 	//
> 	// TODO(azhng): this will require some big refactoring later, we already
> 	//  computes statement's fingerprintID in RecordStatement().
> ```

übernit: There's an extra column of whitespace in the comment from this line down.
___
*[pkg/sql/logictest/testdata/logic_test/statement_statistics, line 214 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL6hOyBtm0Qi5-3Gl1:-MlL6hOyBtm0Qi5-3Gl2:b-harxug) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/logictest/testdata/logic_test/statement_statistics#L214)):*
> ```
> key                             implicit_txn
> SELECT x FROM test WHERE y = _  false
> SELECT x FROM test WHERE y = _  false
> ```

Is this duplicated line here on purpose? I don't see anything nearby to suggest that it has any observable effect.
___
*[pkg/sql/sqlstats/cluster_settings.go, line 110 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL9jzO6Nf8jajJUI9f:-MlL9jzO6Nf8jajJUI9g:b3kie2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/sqlstats/cluster_settings.go#L110)):*
> ```Go
> //
> // This limit is introduced because when SQL Stats starts to record statement
> // statistics for statements inside an explicit transactions, the transaction
> ```

nit: transactions -> transaction
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 388 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlLAS6u9P-2PTom3OQp:-MlLAS6u9P-2PTom3OQq:b-kipvza) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/sqlstats/persistedsqlstats/flush.go#L388)):*
> ```Go
> 	if rowsAffected == 0 {
> 		return errors.AssertionFailedf("failed to update statement statistics"+
> 			"for fingerprint_id: %s,"+
> ```

I think you want to put a trailing space in each of these strings, yes?
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 389 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlLAeDL6UQwHaIC2Mr_:-MlLAeDL6UQwHaIC2Mra:b1jcvsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/sqlstats/persistedsqlstats/flush.go#L389)):*
> ```Go
> 		return errors.AssertionFailedf("failed to update statement statistics"+
> 			"for fingerprint_id: %s,"+
> 			"transaction_fingerprint_id: %s"+
> ```

And a comma here?
___
*[pkg/sql/sqlstats/persistedsqlstats/testdata/logical_plan_sampling_for_explicit_txn, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlLB0613-3aOh6vT1pw:-MlLB0613-3aOh6vT1px:bwl8co2) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/sqlstats/persistedsqlstats/testdata/logical_plan_sampling_for_explicit_txn#L1)):*
> ```
> exec-sql
> ```

I wonder if a leading comment describing the overall test path here would be useful, WDYT? I'm having a little trouble seeing where the assertions are.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70261)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/sql/executor_statement_metrics.go, line 167 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL6-9eAyZzs2b65dUn:-MlLKkBX8YHP6NS8JzL0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/executor_statement_metrics.go#L167)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: this -> This
</blockquote></details>

Done.
___
*[pkg/sql/executor_statement_metrics.go, line 168 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL61kTBDV2Bk-ChsZ-:-MlLKmD2E9mHOQAc8_Ty:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/executor_statement_metrics.go#L168)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: computes -> compute
</blockquote></details>

Done.
___
*[pkg/sql/executor_statement_metrics.go, line 168 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL661u4A-W_fMKmzJw:-MlLKxKH03afBI56q9eY:b17vq91) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/executor_statement_metrics.go#L168)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

übernit: There's an extra column of whitespace in the comment from this line down.
</blockquote></details>

Removed extra line.
___
*[pkg/sql/logictest/testdata/logic_test/statement_statistics, line 214 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL6hOyBtm0Qi5-3Gl1:-MlLLEJx0oC2m2UUUXwO:balr9h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/logictest/testdata/logic_test/statement_statistics#L214)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Is this duplicated line here on purpose? I don't see anything nearby to suggest that it has any observable effect.
</blockquote></details>

Yes it's on purpose. This is because previously, we run 1 implicit statement w/ fingerprint `SELECT x FROM test WHERE y = _` and 2 explicit txns with the same fingerprint,
but those two explicit txns have different txn fingerprint, with our change, this result in 2 different entry.

Though `crdb_internal.node_statement_statistics` is a rather ancient (kind of weird calling this ancient since it's introduced not that many releases ago) and it does not surface txn fingerprint information, I really want to just deprecate this. 
___
*[pkg/sql/sqlstats/cluster_settings.go, line 110 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL9jzO6Nf8jajJUI9f:-MlLM1jZEL4l9V6JEdad:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/sqlstats/cluster_settings.go#L110)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: transactions -> transaction
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 388 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlLAS6u9P-2PTom3OQp:-MlLKPl23PULoGYeeFCh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/sqlstats/persistedsqlstats/flush.go#L388)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I think you want to put a trailing space in each of these strings, yes?
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 389 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlLAeDL6UQwHaIC2Mr_:-MlLKQ5m3CCed9dwTQms:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/sqlstats/persistedsqlstats/flush.go#L389)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

And a comma here?
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/testdata/logical_plan_sampling_for_explicit_txn, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlLB0613-3aOh6vT1pw:-MlLV-BU35HfXRF_gw-9:bdjt5oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/sqlstats/persistedsqlstats/testdata/logical_plan_sampling_for_explicit_txn#L1)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I wonder if a leading comment describing the overall test path here would be useful, WDYT? I'm having a little trouble seeing where the assertions are.
</blockquote></details>

Added top-level comment as well as inline commnet for each tests

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-:-MlLYoEe8F9c8Y7qnCPB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[pkg/sql/executor_statement_metrics.go, line 168 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlL661u4A-W_fMKmzJw:-MlLWqlX0JbBaITxRv3T:b5lrn7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/executor_statement_metrics.go#L168)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Removed extra line.
</blockquote></details>

Retracting my nit! The extra column of whitespace tells GoLang to treat the whole block as the TODO, not just the first line. TIL.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 387 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlLYUIv2nGwKri9kNC1:-MlLYUIv2nGwKri9kNC2:b-vgv9su) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26b86d2e18bee10c70cfadae97ead0d6da974e8/pkg/sql/sqlstats/persistedsqlstats/flush.go#L387)):*
> ```Go
> 
> 	if rowsAffected == 0 {
> 		return errors.AssertionFailedf("failed to update statement statistics"+
> ```

nit: oops, a trailing space here, too
___
*[pkg/sql/sqlstats/persistedsqlstats/testdata/logical_plan_sampling_for_explicit_txn, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70261#-MlLB0613-3aOh6vT1pw:-MlLYeZf5rq-8qj1Jlsx:b-xqeifk) ([raw file](https://github.com/cockroachdb/cockroach/blob/44be130bc55b3ef3dbd6ce2c8d91cc10333311a5/pkg/sql/sqlstats/persistedsqlstats/testdata/logical_plan_sampling_for_explicit_txn#L1)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Added top-level comment as well as inline commnet for each tests 
</blockquote></details>

Love it, thanks!

**Comment by Azhng** [comment]
TFTR!

bors r=matthewtodd

**Comment by Azhng** [comment]
blather backport 21.2

**Comment by Azhng** [comment]
blathers backport 21.2

**Pull request merged**
