### PR TITLE
sql: change the syntax for txn retries to SAVEPOINT

### PR DESCRIPTION
**Pull request by andreimatei**
This changes the statements used to the standard sql sub-transaction
syntax:
SAVEPOINT cockroach_restart
RELEASE SAVEPOINT cockroach_restart
ROLLBACK TO SAVEPOINT cockroach_restart

The plan was always to probably support this syntax too since Ben argued
it helps with ORMs caching mechanism. I was forced to do this right away
because the C++ postgres driver (libpqxx) doesn't allow you to use a
transaction in any way after an error is returned, so there's no
oportunity to restart. But it does allow you to use subtransactions,
which is how they recommend doing error handling.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5535)

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/executor.go, line 736 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535#-KDe1bioqBYvTVIZt37P:-KDe1bioqBYvTVIZt37Q:-2051232762) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa15b4ee0df52655d9df3ceb7c8a428f9756a06/sql/executor.go#L736)):*
either "we are erroneously allowing" or "we erronously allow"

---

*[sql/session.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535#-KDe28Wr21QO3B_LPfQe:-KDe28Ws6pB2T0DbmTpV:1262245178) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa15b4ee0df52655d9df3ceb7c8a428f9756a06/sql/session.go#L154)):*
Please add a link to this comment in issue #5531.

---

*[sql/parser/stmt.go, line 184 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535#-KDe2fKdPhc97XhSpznU:-KDe2fKe4-r5YEr4HWJd:-1967068008) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa15b4ee0df52655d9df3ceb7c8a428f9756a06/sql/parser/stmt.go#L184)):*
Did you check these are the same tags as used by pg?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535)*

**Comment by andreimatei** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/executor.go, line 736 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535#-KDe1bioqBYvTVIZt37P:-KDe5YocbyKNjQtoak7H:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa15b4ee0df52655d9df3ceb7c8a428f9756a06/sql/executor.go#L736)):*
Done.

---

*[sql/session.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535#-KDe28Wr21QO3B_LPfQe:-KDe5aSV987FUgN3ArV-:-880894685) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa15b4ee0df52655d9df3ceb7c8a428f9756a06/sql/session.go#L154)):*
will do after it lands

---

*[sql/parser/stmt.go, line 184 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535#-KDe2fKdPhc97XhSpznU:-KDe9QBoXXJgdyB2DuBH:1871134802) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa15b4ee0df52655d9df3ceb7c8a428f9756a06/sql/parser/stmt.go#L184)):*
pg seems to just say "ROLLBACK". Switched to that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535)*

**Comment by knz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/stmt.go, line 184 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535#-KDe2fKdPhc97XhSpznU:-KDeA8FtSBitVSqyMf0T:490949704) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa15b4ee0df52655d9df3ceb7c8a428f9756a06/sql/parser/stmt.go#L184)):*
I assume you checked for all new statements not just this one?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535)*

**Comment by andreimatei** [comment]
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---

*[sql/parser/stmt.go, line 184 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535#-KDe2fKdPhc97XhSpznU:-KDeDOGh8DQcIGK7pGcu:1484709269) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa15b4ee0df52655d9df3ceb7c8a428f9756a06/sql/parser/stmt.go#L184)):*
yeah, I had to correct RELEASE too. Anyway as far as I could tell, these tags are not really part of the protocol and their intended uses is just for showing in a prompt. There was one special case for COMMIT I think where libpq cares about the tag for some reason.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5535#-:-KDeYVUJOmycUvsnZV2N:1417088721)*

**Comment by jseldess** [comment]
Covered in [Transactions](https://www.cockroachlabs.com/docs/transactions.html) and [Build a Test App](https://www.cockroachlabs.com/docs/build-a-test-app.html).

**Pull request merged**
