### PR TITLE
storage: use finer locks and async methods for queuing ranges

### PR DESCRIPTION
**Pull request by tbg**
baseQueue.mu locks were held unnecessarily long, and in particular across
`shouldQueue` invocations which in turn can acquire various Replica locks,
complicating the lock ordering story.

Sidestep this issue by never holding baseQueue.mu across any operation that
can touch the Replica.

The remaining issue here is that callers of `Add` or `MaybeAdd` may be
holding locks on the Replica object already which could also lead to
deadlock. This is because the queue calls into
`repl.maybeInitializeRaftGroup()` (which can end up acquiring the raftMu)
but also because it calls the various `shouldQueue` methods doing the
queue-specific checks; those almost always acquire locks, too. This problem
should be exclusive to `raftMu`; I doubt we hold `Replica.mu` while calling
`Add/MaybeAdd` or at least it should be easy to avoid that.

Working around this is left to the second commit, which avoids having to worry
about lock ordering if a replica is added to a queue while holding mutexes.
Primarly, this affects calls to add a replica to a queue from within the raft
processing goroutines, where the replica's raftMu is held. Adding a replica to
a queue can in turn require acquisition of the raftMu, leading to potential
deadlock.

This hasn't been observed in practice, but let's be prudent and avoid this
problem. Queues act asynchronously by their very nature, so we lose very
little by not offering replicas to a queue synchronously, except during
unit tests, where we'll simply have work around it.

Touches #36413.

### CODE REVIEW

**Comment by tbg** [comment]
Pretty sure there are some test flakes waiting to be discovered, I'm currently running `make stress PKG=./pkg/storage STRESSFLAGS='-p 4 -maxruns 20'` on my gceworker.

**Comment by tbg** [comment]
Well now that's surprising:

```
20 runs completed, 0 failures, over 12m30s
SUCCESS
ok      github.com/cockroachdb/cockroach/pkg/storage    749.869s
```

Meanwhile all other packages basically fail but I think it's because I moved some of those `ForceXYZScanAndProcess` methods out, and those were actually accessed from outside the package. Oops. Going to fix that but I think this can still be reviewed in the meantime.

**Review by bdarnell — APPROVED** [review]
LGTM. I'm mildly concerned about anything that has the potential to spin out an unlimited number of goroutines. Maybe this should be a LimitedAsyncTask and just log an error and drop the replica on the floor in the unlikely event it can't keep up?

> Reviewed 1 of 1 files at r1, 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36564#-:-LbnaYwh8YVPiLd7S-Gi:bj3gups)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tbg** [comment]
> LGTM. I'm mildly concerned about anything that has the potential to spin out an unlimited number of goroutines. Maybe this should be a LimitedAsyncTask and just log an error and drop the replica on the floor in the unlikely event it can't keep up?

Done.

**Comment by tbg** [comment]
bors r=bdarnell

**Pull request merged**
