### PR TITLE
storage: Remove the last vestiges of non-proposer-evaluated-KV

### PR DESCRIPTION
**Pull request by bdarnell**
This allows us to remove nearly all protobufs from the "below raft"
list of types requiring strict compatibility.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/replica.go, line 3655 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15228#-KiC27XcPaUbvWO_VBo_:-KiC27XcPaUbvWO_VBoa:b-38aes) ([raw file](https://github.com/cockroachdb/cockroach/blob/358cc9c97938a3de3f1c424352517910a51a7a2f/pkg/storage/replica.go#L3655)):*
> ```Go
> 	{
> 		if raftCmd.ReplicatedEvalResult == nil && forcedErr == nil {
> 			panic("non-proposer-evaluated command found in raft log")
> ```

I wonder if this should be more verbose and mention what action the user should take or point to this week's beta release notes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15228#-:-KiC2QavjDHyHyydFi8E:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica.go, line 3655 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15228#-KiC27XcPaUbvWO_VBo_:-KiC4tSQ1o-kY8ncFTvz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/358cc9c97938a3de3f1c424352517910a51a7a2f/pkg/storage/replica.go#L3655)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if this should be more verbose and mention what action the user should take or point to this week's beta release notes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15228)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/track_raft_protos.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15228#-KiC2arruGi6I8dZDP3Y:-KiC2arruGi6I8dZDP3Z:b-vni661) ([raw file](https://github.com/cockroachdb/cockroach/blob/358cc9c97938a3de3f1c424352517910a51a7a2f/pkg/storage/track_raft_protos.go#L46)):*
> ```Go
> 	whitelist := []string{
> 		// Some raft operations trigger gossip, but we don't require
> 		// strict consitency there.
> ```

"consistency"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15228)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15228#-:-KiGLwitIO5NaHrWXyru:bnfp4nl)*

**Comment by tamird** [comment]
I think you caught some build skew related to my rocksdb patch here, can you rebase for good measure?

**Comment by bdarnell** [comment]
And now it's (correctly) failing the reference binary acceptance tests. It's time to bump up the version used there.

**Comment by bdarnell** [comment]
Added a new commit to update the acceptance tests (it won't pass until cockroachdb/postgres-test#22 is merged and tagged).

**Comment by bdarnell** [comment]
Done, and I also swapped the order of the commits so the acceptance tests pass for both of them.

**Comment by tamird** [comment]
LGTM!

**Pull request merged**
