### PR TITLE
storage: Prioritize replica rebalancing over lease rebalancing

### PR DESCRIPTION
**Pull request by a-robinson**
This shouldn't come up in most healthy clusters, but rebalancing
replicas seems more important than moving leases, and I saw some
behavior in indigo where a node kept choosing to transfer leases
rather than replicas, which slowed down replica rebalancing to a
new node.

The first commit is duplicated from #17584. This shouldn't be merged until after the 1.1 branch has been cut. I'm just opening this to avoid forgetting about it.

### CODE REVIEW

**Comment by petermattis** [comment]
Lease transfers are much cheaper than rebalancing. That might have been the logic behind preferring them. Having a strict preference for one operation or another might be wrong. Perhaps we can weight the priority of each and select the highest priority.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17595#-:-KrHYz0-kdDH68ya-p36:b-hjzavj)*

**Comment by a-robinson** [comment]
They are cheaper, but if a range requires rebalancing, it makes more sense to change the replicas before changing the leaseholder, because after changing to a new set of replicas we'll have to reconsider the leaseholder placement and may need to transfer it again.

And in some cases, we could be transferring the lease to the replica that we want to remove from the range, requiring it to be transferred away immediately in order to accommodate the replica change.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17595#-:-KrHdg73UDhF2z4g5som:b-onaswc)*

**Comment by petermattis** [comment]
Good points.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17595#-:-KrHf9-Wq7gr_5rh4J2Y:b-c3tlw3)*

**Comment by bdarnell** [comment]
I agree with this change (so it LGTM after the release branch is cut), but one more minor counterpoint: Rebalancing replicas puts a little extra load on the leaseholder (since the leaseholder generates the preemptive snapshot), so moving the lease to a suitable node first could be a slight optimization.

**Comment by a-robinson** [comment]
Yeah, that's fair. Along those lines, in geographically distributed clusters we could also consider moving the lease before adding a new replica in order to send the snapshot from a replica that's closer to the recipient.

**Comment by bdarnell** [comment]
We don't even need to transfer the lease to optimize snapshot traffic (although it might be the simplest way to do so). The lease holder could instruct a follower to send the snapshot instead of sending it itself.

This is especially important since the node in the best position to send the snapshot is often the most likely to be removed next (Consider a range with replicas in three localities on nodes A1, B1, and C1. It wants to move its replica in locality C to node C2. It's cheapest to send the snapshot from C1, but C1 will be removed once the rebalancing is complete, so it would be unnecessarily disruptive to transfer leadership to it from A1 or B1 just to transfer it away again)

**Pull request merged**
