### PR TITLE
storage: don't fail liveness on callback errors

### LINKED ISSUE #16656: teamcity: failed tests on master: testrace/TestLogic, testrace/TestLogic/5node, testrace/TestLogic/5node/distsql_agg
The following tests appear to have failed:

[#277700](https://teamcity.cockroachdb.com/viewLog.html?buildId=277700):

```
--- FAIL: testrace/TestLogic (377.880s)
<autogenerated>:10: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogic024332870
<autogenerated>:9: use -show-logs to present logs inline
--- FAIL: testrace/TestLogic/5node (0.000s)
null
--- FAIL: testrace/TestLogic/5node/distsql_agg (7.260s)
logic_test.go:1718: 
	testdata/logic_test/distsql_agg:11: expected success, but found
	pq: change replicas of r4 failed: [n1,s1,r4/1:/Table/51/1/{3-4}]: invalid ChangeReplicasTrigger trigger:<change_type:REMOVE_REPLICA replica:<node_id:1 store_id:1 replica_id:1 > updated_replicas:<node_id:4 store_id:4 replica_id:2 > next_replica_id:3 >  to remove leaseholder replica
logic_test.go:1728: 
	testdata/logic_test/distsql_agg:11: error in statement, skipping to next file

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tbg**
Previously, we were passing a callback to node liveness that returned an
error. If an error was returned, that would fail the liveness update. A
recent PR added a return which would sometimes fire (trying to load its own
liveness record, but not finding it yet) which would then trip up liveness
updates, and caused surprising failures during lease transfers.

Investigation of how the spuriously returned error caused the weird test
failure is deferred to #16697. It's likely that most tests don't experience
this problem because most tests run for a very short period of time, and
epoch based leases only matter after ~3s (most ranges in tests inherit the
expiration-based lease from the first range since that's where they are
split off from).

Fixes #16656.

### CODE REVIEW

**Comment by tamird** [comment]
Are you sure that changing the signatures here is the right solution? Some of these conversions to error logging seem worrisome to me, suggesting that we might want to avoiding return an error in just the one place where it does a Bad Thing.

---

Reviewed 1 of 10 files at r1.
Review status: 1 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/server_test.go, line 543 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZshDwemkx1RBuw5eb:-KnZshDwemkx1RBuw5ec:b-d949f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/server/server_test.go#L543)):*
> ```Go
> 	s, _, _ := serverutils.StartServer(t, base.TestServerArgs{})
> 	defer s.Stopper().Stop(context.TODO())
> 	ts := s.(*TestServer)
> ```

no need for this local

---

*[pkg/server/server_test.go, line 545 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZsa0JptO_JmMv46G9:-KnZsa0JptO_JmMv46GA:b8r8cub) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/server/server_test.go#L545)):*
> ```Go
> 	ts := s.(*TestServer)
> 	nodeLiveness := ts.nodeLiveness
> 	var liveness *storage.Liveness
> ```

why are these two `var`s here?

---

*[pkg/server/server_test.go, line 557 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZsjtxx7tM8sZ5ZeDU:-KnZsjtxx7tM8sZ5ZeDV:bjkocb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/server/server_test.go#L557)):*
> ```Go
> 	testutils.SucceedsSoon(t, func() error {
> 		if liveness, err := nodeLiveness.Self(); err != nil {
> 			return err
> ```

this should be fatal, shouldn't it?

---

*[pkg/server/server_test.go, line 558 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZsoWxdNDuSqKZaGvm:-KnZsoWxdNDuSqKZaGvn:bn99hcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/server/server_test.go#L558)):*
> ```Go
> 		if liveness, err := nodeLiveness.Self(); err != nil {
> 			return err
> 		} else if !liveness.Decommissioning || !liveness.Draining {
> ```

break this into two cases so the error is clearer. why is the draining precondition not checked, given that decommissioning is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-:-KnZtK2ClELddRlXLVON:b-mij6c0)*

**Comment by tamird** [comment]
Littered some nits, but main question remains.

---

Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/storage/helpers_test.go, line 402 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZxmqms-kkCtBeA-S5:-KnZxmqms-kkCtBeA-S6:b85gtw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/helpers_test.go#L402)):*
> ```Go
> 	return nl.setDrainingInternal(ctx, liveness, drain)
> }
> func (nl *NodeLiveness) SetDecommissioningInternal(
> ```

no newline? i thought gofmt would do that.

---

*[pkg/storage/node_liveness.go, line 176 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZyL-V2NSU1SpA9mfm:-KnZyL-V2NSU1SpA9mfn:b-9r2wj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/node_liveness.go#L176)):*
> ```Go
> 			log.Errorf(ctx, "unexpected error getting liveness: %s", err)
> 		}
> 		if err := nl.setDecommissioningInternal(ctx, nodeID, liveness, decommission); err == nil {
> ```

how come you can use `liveness` here if you got an error above?

---

*[pkg/storage/node_liveness.go, line 229 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZyQJ2ZfWTZiQ0qcw5:-KnZyQJ2ZfWTZiQ0qcw6:b-1tjj5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/node_liveness.go#L229)):*
> ```Go
> 			return ctx.Err()
> 		}
> 		defer func() {
> ```

this should be inside the `nl.sem <-` arm above. it doesn't matter now, but the pattern is weird.

---

*[pkg/storage/node_liveness.go, line 246 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZyZGOejdxDni-PbFI:-KnZyZGOejdxDni-PbFJ:bi0geqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/node_liveness.go#L246)):*
> ```Go
> 			return nil
> 		}
> 		return errors.New("failed to update liveness record")
> ```

no sentinel error here?

---

*[pkg/storage/node_liveness_test.go, line 720 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZxWk5-5qEJEpAUnGJ:-KnZxWk5-5qEJEpAUnGK:b-79owey) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/node_liveness_test.go#L720)):*
> ```Go
> 					expected = true
> 				}
> 				if liveness.Decommissioning != expected {
> ```

`livenss.Decommissioning != (liveness.NodeID == nodeID)`? or you can keep the local, but there's no need for an `if true { foo = true }` above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-:-KnZyaTY4U3_2zWtV0Q1:boiqjsx)*

**Comment by bdarnell** [comment]
:lgtm:

Yes, changing these signatures is the right solution. The node liveness code can't do anything with a returned error but log it and continue anyway; better to make the callbacks explicitly responsible for their own error handling. 

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 834 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KneW1qBVrrWYbUhHZ8b:-KneW1qBVrrWYbUhHZ8c:bh657c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/server/server.go#L834)):*
> ```Go
> 			s.stopper.RunWorker(ctx, func(context.Context) {
> 				select {
> 				case sem <- struct{}{}:
> ```

This is kind of a weird pattern. Instead of spawning goroutines and having all but one exit immediately as a noop, it seems better to set a flag so we don't start multiple goroutines in the first place. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-:-KneWJAyAtQ_Zv2Zn-ID:b-mcfc85)*

**Comment by tschottdorf** [comment]
> Are you sure that changing the signatures here is the right solution?

Yeah, what Ben said.

Addressed comments and pulled on some threads, so probably want to give this another look.

---

Review status: 5 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/server/server.go, line 834 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KneW1qBVrrWYbUhHZ8b:-KneinPduEn29CSK6Rku:b-k8rr02) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/server/server.go#L834)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is kind of a weird pattern. Instead of spawning goroutines and having all but one exit immediately as a noop, it seems better to set a flag so we don't start multiple goroutines in the first place. 
</blockquote></details>

Moved the sem outside, which accomplishes that.

---

*[pkg/server/server_test.go, line 543 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZshDwemkx1RBuw5eb:-Kn_YCvybYU0gYl79zwy:b9iu0ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/server/server_test.go#L543)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

no need for this local
</blockquote></details>

`ts` is used twice below.

---

*[pkg/server/server_test.go, line 545 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZsa0JptO_JmMv46G9:-Kn_YOppa0JKyKG1oIB9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/server/server_test.go#L545)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why are these two `var`s here?
</blockquote></details>

Done.

---

*[pkg/server/server_test.go, line 557 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZsjtxx7tM8sZ5ZeDU:-KneXHAK9SCPtLcK6tMn:b-no4bmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/server/server_test.go#L557)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this should be fatal, shouldn't it?
</blockquote></details>

Yes and no. The original bug was that `Self()` in fact can return an error when called before the first heartbeat has happened. Added that before this SucceedsSoon so that this error is now a fatal.

---

*[pkg/server/server_test.go, line 558 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZsoWxdNDuSqKZaGvm:-Kneh8vM6_hu1O24FyVE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/server/server_test.go#L558)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

break this into two cases so the error is clearer. why is the draining precondition not checked, given that decommissioning is?
</blockquote></details>

Done.

---

*[pkg/storage/helpers_test.go, line 402 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZxmqms-kkCtBeA-S5:-KnehHzQL5a_9Ev_xVsp:b-lbut5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/helpers_test.go#L402)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

no newline? i thought gofmt would do that.
</blockquote></details>

What do you mean?

---

*[pkg/storage/node_liveness.go, line 176 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZyL-V2NSU1SpA9mfm:-KnehWLpc_t5TKQHHDo1:b-5tq2ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/node_liveness.go#L176)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come you can use `liveness` here if you got an error above?
</blockquote></details>

Because it was wrong. Good catch, fixed!

---

*[pkg/storage/node_liveness.go, line 229 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZyQJ2ZfWTZiQ0qcw5:-Knemf312TAHCXSpioUZ:b-4yi1mc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/node_liveness.go#L229)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this should be inside the `nl.sem <-` arm above. it doesn't matter now, but the pattern is weird.
</blockquote></details>

Yeah, this was funky. Changed.

---

*[pkg/storage/node_liveness.go, line 246 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZyZGOejdxDni-PbFI:-KnelXxxmUwjL8qrKUji:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/node_liveness.go#L246)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

no sentinel error here?
</blockquote></details>

Done.

---

*[pkg/storage/node_liveness_test.go, line 720 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZxWk5-5qEJEpAUnGJ:-KnelFbg2zyJqWjc2mNk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/node_liveness_test.go#L720)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`livenss.Decommissioning != (liveness.NodeID == nodeID)`? or you can keep the local, but there's no need for an `if true { foo = true }` above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-:-Kn_Wf5e1NZayJ4OE2hI:bvyc0t2)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/helpers_test.go, line 402 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZxmqms-kkCtBeA-S5:-Kneqr-upho79ge-uz2d:blltanp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/helpers_test.go#L402)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

I'm surprised that there's no empty line between this function prototype and the previous function's closing brace.

---

*[pkg/storage/node_liveness.go, line 45 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KneqZ0Rfi-l0ItjshGZ:-KneqZ0Se1Bbj6KMFEXI:b-rmvt9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc874a733bc4642995493d7f3527c3b7c5b6865e/pkg/storage/node_liveness.go#L45)):*
> ```Go
> 	ErrNoLivenessRecord = errors.New("node not in the liveness table")
> 
> 	ErrChangeDecommissioningFailed = errors.New("failed to change the decommissioning status")
> ```

why exported?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698)*

**Comment by tschottdorf** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/helpers_test.go, line 402 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KnZxmqms-kkCtBeA-S5:-Knf-Q0rPcHzplAFwqVR:b-m10u5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e4fb500c3ed2f0a1a79621b406e1c385cf83915/pkg/storage/helpers_test.go#L402)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I'm surprised that there's no empty line between this function prototype and the previous function's closing brace.
</blockquote></details>

Oh, didn't even notice - yeah, surprising. Added.

---

*[pkg/storage/node_liveness.go, line 45 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698#-KneqZ0Rfi-l0ItjshGZ:-Knf-kY34kVKszDisj0K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc874a733bc4642995493d7f3527c3b7c5b6865e/pkg/storage/node_liveness.go#L45)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why exported?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16698)*

**Pull request merged**
