### PR TITLE
col*: miscellaneous minor improvements and cleanup

### PR DESCRIPTION
**Pull request by yuzefovich**
**colbuilder: fix error propagation and optimize logging**

This commit fixes several places in planning of expressions where we
didn't check whether err is non-nil before using some other variables.
This could lead to, e.g., an index out of bounds panic. This wouldn't
crash server though because we would catch the panic during
`SupportsVectorized` check and refuse to plan a vectorized flow.

Additionally, this commit avoids evaluating a formatted string for
logging when the verbosity level isn't high enough.

Release note: None

**colserde: support zero length schema**

Previously, we didn't support the zero length schema serialization since
we thought that it wasn't necessary, but there are valid queries (e.g.
count(*)) when we want to send the batches with no vectors but with the
length field correctly set over the wire. This commit adds such an
ability.

Release note: None

**sql: add ResultTypes to processor spec**

This commit introduces a new field to `execinfrapb.ProcessorSpec` in
order to propagate the result types of the processors and the
corresponding field has been removed from `PhysicalPlan` (and was
replaced by a getter method). I believe it is a cleaner abstraction than
what we had previously (implicit type schema expectation by the output
stage that is passed into InputSyncSpec), and this change is
a prerequisite to refactor of the vectorized flow setup - with this
change it'll be now very easy to make sure that the desired type schema
is produced after any vectorized operator (without this plumbing we
would need to attempt to deduce the desired schema, and in some cases it
is not possible - e.g. when we have a remote table reader that is
feeding into an outbox).

Release note: None

**colbuilder,colflow: enforce type schema on the stream ends by casting**

Previously, whenever we're setting up an output (or the final
materializer) we asserted that the types the flow spec contains and the
types that the columnar operators return are equal. This is necessary
in order to not hit a runtime conversion error (for example, we've had
issues when `default_int_size` is set to 4 - and due to short-comings of
our SQL type system, we could encounter an internal error). If we saw
that the types aren't equal, we gave up on vectorizing the query.

This commit takes a different approach - we now will plan cast operators
in order to guarantee the desired output schema. I believe that only
integers of different width need to be casted.

Release note: None

**colexec: add more casts to decimals and datum-backed types**

Previously, we allowed only identity casts to decimals between decimals
of the same precision. This commit extends the support of casts of any
precision and scale (from ints, floats, and other decimals). The cast
from ints to decimals has been optimized by removing an unnecessary
allocation of a new apd.Decimal object and operating on the output
object directly.

It also adds the supports of casts between datum-backed types as well as
refactors the cast template to remove the code duplication. Null
handling has been optimized as well.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Benchmarks of the fourth commit:
```
name                                                    old time/op    new time/op     delta
CastOp/useSel=true/hasNulls=true/int_to_float-24          1.82µs ± 6%     2.27µs ± 6%    +24.77%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=false/int_to_float-24         1.22µs ± 6%     1.64µs ± 4%    +33.82%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=true/int_to_float-24         3.43µs ± 3%     2.68µs ± 1%    -21.87%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=false/int_to_float-24        1.07µs ± 0%     1.08µs ± 0%     +1.22%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=true/int_to_decimal-24         409µs ± 1%       50µs ± 2%    -87.74%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=false/int_to_decimal-24        422µs ± 1%       31µs ± 6%    -92.55%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=true/int_to_decimal-24        406µs ± 2%       60µs ± 1%    -85.13%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=false/int_to_decimal-24       419µs ± 1%       55µs ± 0%    -86.84%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=true/float_to_decimal-24      1.49ms ± 3%     0.54ms ± 5%    -63.91%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=false/float_to_decimal-24     1.61ms ± 1%     0.59ms ± 5%    -63.32%  (p=0.000 n=9+10)
CastOp/useSel=false/hasNulls=true/float_to_decimal-24     1.48ms ± 1%     1.05ms ± 2%    -28.85%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=false/float_to_decimal-24    1.61ms ± 1%     1.17ms ± 1%    -27.67%  (p=0.000 n=10+10)

name                                                    old speed      new speed       delta
CastOp/useSel=true/hasNulls=true/int_to_float-24        4.52GB/s ± 6%   3.62GB/s ± 6%    -19.87%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=false/int_to_float-24       6.70GB/s ± 5%   5.01GB/s ± 3%    -25.30%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=true/int_to_float-24       2.39GB/s ± 3%   3.05GB/s ± 1%    +27.97%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=false/int_to_float-24      7.69GB/s ± 0%   7.59GB/s ± 0%     -1.20%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=true/int_to_decimal-24      20.0MB/s ± 1%  163.3MB/s ± 2%   +715.88%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=false/int_to_decimal-24     19.4MB/s ± 1%  261.1MB/s ± 5%  +1243.92%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=true/int_to_decimal-24     20.2MB/s ± 2%  135.6MB/s ± 1%   +572.64%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=false/int_to_decimal-24    19.5MB/s ± 1%  148.5MB/s ± 0%   +659.95%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=true/float_to_decimal-24    5.50MB/s ± 3%  15.26MB/s ± 6%   +177.29%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=false/float_to_decimal-24   5.09MB/s ± 1%  13.89MB/s ± 6%   +172.83%  (p=0.000 n=9+10)
CastOp/useSel=false/hasNulls=true/float_to_decimal-24   5.53MB/s ± 1%   7.76MB/s ± 2%    +40.23%  (p=0.000 n=10+9)
CastOp/useSel=false/hasNulls=false/float_to_decimal-24  5.08MB/s ± 1%   7.02MB/s ± 1%    +38.25%  (p=0.000 n=10+10)

name                                                    old alloc/op   new alloc/op    delta
CastOp/useSel=true/hasNulls=true/int_to_float-24           0.00B           0.00B            ~     (all equal)
CastOp/useSel=true/hasNulls=false/int_to_float-24          0.00B           0.00B            ~     (all equal)
CastOp/useSel=false/hasNulls=true/int_to_float-24          0.00B           0.00B            ~     (all equal)
CastOp/useSel=false/hasNulls=false/int_to_float-24         0.00B           0.00B            ~     (all equal)
CastOp/useSel=true/hasNulls=true/int_to_decimal-24         112kB ± 3%        4kB ± 3%    -96.71%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=false/int_to_decimal-24        123kB ± 1%        4kB ± 7%    -96.73%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=true/int_to_decimal-24        110kB ± 1%        7kB ± 2%    -93.29%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=false/int_to_decimal-24       123kB ± 0%        8kB ± 0%    -93.32%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=true/float_to_decimal-24       268kB ± 3%       84kB ± 5%    -68.67%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=false/float_to_decimal-24      297kB ± 0%       92kB ± 5%    -68.88%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=true/float_to_decimal-24      268kB ± 1%      165kB ± 2%    -38.39%  (p=0.000 n=8+9)
CastOp/useSel=false/hasNulls=false/float_to_decimal-24     296kB ± 0%      184kB ± 0%    -37.75%  (p=0.000 n=10+10)

name                                                    old allocs/op  new allocs/op   delta
CastOp/useSel=true/hasNulls=true/int_to_float-24            0.00            0.00            ~     (all equal)
CastOp/useSel=true/hasNulls=false/int_to_float-24           0.00            0.00            ~     (all equal)
CastOp/useSel=false/hasNulls=true/int_to_float-24           0.00            0.00            ~     (all equal)
CastOp/useSel=false/hasNulls=false/int_to_float-24          0.00            0.00            ~     (all equal)
CastOp/useSel=true/hasNulls=true/int_to_decimal-24         3.70k ± 2%      0.46k ± 3%    -87.58%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=false/int_to_decimal-24        4.09k ± 0%      0.50k ± 7%    -87.65%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=true/int_to_decimal-24        3.66k ± 1%      0.92k ± 2%    -74.81%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=false/int_to_decimal-24       4.09k ± 0%      1.02k ± 0%    -74.94%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=true/float_to_decimal-24       10.0k ± 3%       3.7k ± 5%    -62.92%  (p=0.000 n=10+10)
CastOp/useSel=true/hasNulls=false/float_to_decimal-24      11.1k ± 0%       4.1k ± 5%    -63.17%  (p=0.000 n=10+10)
CastOp/useSel=false/hasNulls=true/float_to_decimal-24      10.0k ± 2%       7.3k ± 2%    -26.98%  (p=0.000 n=10+9)
CastOp/useSel=false/hasNulls=false/float_to_decimal-24     11.1k ± 0%       8.2k ± 0%    -26.48%  (p=0.000 n=9+10)
```

**Review by asubiotto — CHANGES_REQUESTED** [review]
Which existing tests will test the cast behavior you added?

> Reviewed 2 of 2 files at r1, 11 of 11 files at r2, 3 of 3 files at r3, 5 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-:-MKZ_TjM-nDX_qDTFh4I:b-r4jj2w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/cast_tmpl.go, line 221 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-MKZZqSJ07miGRwp7OjL:-MKZZqSKBPekSfDSlwZF:bzaawv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd20fa62b71c4cd0def6f4604fcd0bbf35ca63b6/pkg/sql/colexec/cast_tmpl.go#L221)):*
> ```Go
> 				outputNulls.Copy(inputNulls)
> 				if sel != nil {
> 					_CAST_TUPLES(true, true)
> ```

Any way to comment these boolean inputs?
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-MKZUCfREWS6oUPRLCI_:-MKZUCfS40eBVAMzz4Kq:b-uf32pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ce6c1952ca788176fb9b8e2705eb29384d6e3e6/pkg/sql/colexec/colbuilder/execplan.go#L549)):*
> ```Go
> 	}
> 
> 	log.VEventf(ctx, 2, "planning col operator for spec %q", spec)
> ```

I don't think this is equivalent with the new version of the code. This will show up as a trace event even though the verbosity is not the required verbosity in the old version, but won't be displayed at all in the new version. Presumably, we made these events because we wanted to trace planning. If not, we should change these `Event` calls to `Info`.
___
*[pkg/sql/colflow/vectorized_flow.go, line 1014 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-MKZYWV1CyXxg6q17q4r:-MKZYWV1CyXxg6q17q4s:b-1kisx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b809de44f541027f4477a5773d122474a53b1ceb/pkg/sql/colflow/vectorized_flow.go#L1014)):*
> ```Go
> 			// Try to determine the output type schema of this processor.
> 			var outputTypes []*types.T
> 		FOUNDTYPES:
> ```

Consider using a helper function rather than a label
___
*[pkg/sql/colflow/vectorized_flow.go, line 1027 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-MKZYmyMBMV8HLa7EKUT:-MKZYmyMBMV8HLa7EKUU:b-7zo8fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b809de44f541027f4477a5773d122474a53b1ceb/pkg/sql/colflow/vectorized_flow.go#L1027)):*
> ```Go
> 					default:
> 						if procIdx, ok := streamIDToSpecIdx[stream.StreamID]; ok {
> 							inputIdx := streamIDToInputIdx[stream.StreamID]
> ```

Might be nice to assert existence

**Review by yuzefovich — COMMENTED** [review]
The eval tests (e.g. `eval/cast`).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-:-MK_OufMCQo-fjlZgISZ:bh0fxgc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/cast_tmpl.go, line 221 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-MKZZqSJ07miGRwp7OjL:-MK_PLXB-9up0HnI86yY:b-gil8as) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd20fa62b71c4cd0def6f4604fcd0bbf35ca63b6/pkg/sql/colexec/cast_tmpl.go#L221)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Any way to comment these boolean inputs?
</blockquote></details>

I don't think so - these boolean values are put into the templated blocks, and if we add the inlined comments, the template function calls will get messed up. I believe I tried doing that for the merge joiner template at some point, but I couldn't figure it out.
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-MKZUCfREWS6oUPRLCI_:-MK_PsKd1-iys609HqpO:bo7it79) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ce6c1952ca788176fb9b8e2705eb29384d6e3e6/pkg/sql/colexec/colbuilder/execplan.go#L549)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think this is equivalent with the new version of the code. This will show up as a trace event even though the verbosity is not the required verbosity in the old version, but won't be displayed at all in the new version. Presumably, we made these events because we wanted to trace planning. If not, we should change these `Event` calls to `Info`.
</blockquote></details>

I believe I added most of this logging in #38992 without giving it too much thought, so I think it is ok to change it without trying to keep the old behavior if we think the new behavior is reasonable.

Am I reading your comment correctly - previously, these log messages would show up in the trace and now they won't unless the verbosity is of the desired level, right? I think that is acceptable and maybe even desirable - I often saw these messages in the traces and they are not helpful at all because they are a big blurb of text that is likely not helpful. I think only logging the fact whether vectorizing of the whole flow succeeded or not should be sufficient. Thoughts?

**Review by yuzefovich — COMMENTED** [review]
I added another commit (the third) that propagates the result types via a processor spec because I realized that in some cases we might not be able to deduce the output types based on a flow spec of a single node - e.g. when we have a remote table reader with an outbox, there is no "other end of the output stream" that lives on the current node. I think the propagation via the proto makes more sense in general.

I also added a unit test for casting behavior during exec-planning (in now the fourth commit). RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-:-MKbRVIQ1fb6RQMYe2uK:b-ryl4nz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colflow/vectorized_flow.go, line 1014 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-MKZYWV1CyXxg6q17q4r:-MKa01On6zwO58sLnemD:b-698bvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b809de44f541027f4477a5773d122474a53b1ceb/pkg/sql/colflow/vectorized_flow.go#L1014)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Consider using a helper function rather than a label
</blockquote></details>

This code was removed.
___
*[pkg/sql/colflow/vectorized_flow.go, line 1027 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-MKZYmyMBMV8HLa7EKUT:-MKa0wyD9F3G5EZnysrY:b-698bvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b809de44f541027f4477a5773d122474a53b1ceb/pkg/sql/colflow/vectorized_flow.go#L1027)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Might be nice to assert existence
</blockquote></details>

This code was removed.

**Review by asubiotto — COMMENTED** [review]
@raduberinde could you share your opinion on the `sql: add ResultTypes to processor spec` commit?

> Reviewed 21 of 21 files at r5, 11 of 11 files at r6, 28 of 28 files at r7, 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-:-MKdbRE0EzbVrJ98Pvb5:bs4ppfh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-MKZUCfREWS6oUPRLCI_:-MKdb9Fg-2MyFKPtp4g5:bnu89cf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ce6c1952ca788176fb9b8e2705eb29384d6e3e6/pkg/sql/colexec/colbuilder/execplan.go#L549)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I believe I added most of this logging in #38992 without giving it too much thought, so I think it is ok to change it without trying to keep the old behavior if we think the new behavior is reasonable.

Am I reading your comment correctly - previously, these log messages would show up in the trace and now they won't unless the verbosity is of the desired level, right? I think that is acceptable and maybe even desirable - I often saw these messages in the traces and they are not helpful at all because they are a big blurb of text that is likely not helpful. I think only logging the fact whether vectorizing of the whole flow succeeded or not should be sufficient. Thoughts?
</blockquote></details>

I agree. We should either always trace these or not add them to the trace. If we don't find them helpful, then let's put them in `Infof`

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55946)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-MKZUCfREWS6oUPRLCI_:-MKfNBA89PJsrpktQDNL:b-mc7018) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ce6c1952ca788176fb9b8e2705eb29384d6e3e6/pkg/sql/colexec/colbuilder/execplan.go#L549)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I agree. We should either always trace these or not add them to the trace. If we don't find them helpful, then let's put them in `Infof`
</blockquote></details>

Updated to use `Infof`

**Comment by yuzefovich** [comment]
I'm currently trying to figure out what's wrong with the enum type support in the vectorized engine - the following logic test fails:
```
# LogicTest: fakedist

statement ok
CREATE TYPE greeting AS ENUM ('hello', 'howdy', 'hi');
CREATE TABLE enum_agg (x greeting, y INT);
INSERT INTO enum_agg VALUES
  ('hello', 1),
  ('hello', 3),
  ('howdy', 5),
  ('howdy', 0),
  ('howdy', 1),
  ('hi', 10);
SET vectorize=experimental_always

query TIRI rowsort
SELECT x, max(y), sum(y), min(y) FROM enum_agg GROUP BY x
----
hello 3 4 1
howdy 5 6 0
hi 10 10 10
```
with
```
                testdata/logic_test/wip:15: SELECT x, max(y), sum(y), min(y) FROM enum_agg GROUP BY x
                expected success, but found
                (XX000) internal error: unexpected error from the vectorized engine: runtime error: index out of range [2] with length 2
                error.go:90: in func1()
                DETAIL: stack trace:
                github.com/cockroachdb/cockroach/pkg/sql/colexecbase/colexecerror/error.go:90: func1()
                runtime/panic.go:679: gopanic()
                runtime/panic.go:75: goPanicIndex()
                github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1139: assertTypesMatch()
                github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1104: func1()
                github.com/cockroachdb/cockroach/pkg/sql/colexecbase/colexecerror/error.go:93: CatchVectorizedRuntimeError()
                github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:960: setupFlow()
                github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1314: SupportsVectorized()
...
```
(this is a repro of the build failure that got exposed by the fourth commit)

**Comment by yuzefovich** [comment]
Never mind, there was a bug in the third commit (getting `plan.GetResultTypes()` in a loop while updating `ResultRouters` within the same loop), the build should be green now, RFAL.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55946#-:-MKie_L31-CqSIGhkTEu:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
