### PR TITLE
sql: make CALL statements explainable

### LINKED ISSUE #114674: sql: stored procedures should be explainable
Currently, it is not possible to view the plan of a stored procedure call, or to collect a statement bundle for one:
```
root@localhost:26257/system/defaultdb> explain analyze (debug) call arr_var();
ERROR: statement ignored: at or near "call": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
explain analyze (debug) call arr_var()
                        ^
HINT: try \h <SELECTCLAUSE>
root@localhost:26257/system/defaultdb> explain call arr_var();
ERROR: statement ignored: at or near "call": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
explain call arr_var()
        ^
HINT: try \h EXPLAIN
```
Postgres doesn't allow explaining a CALL statement either, but it seems worth it to remove this limitation anyway, since otherwise it's a pretty large gap in observability.

Jira issue: CRDB-33619

### PR DESCRIPTION
**Pull request by DrewKimball**
This patch makes it possible to run CALL statements with EXPLAIN. Currently, most explain variants only display the name and arguments of the procedure. The `OPT` explain variants additionally show the SQL/PLpgSQL body statements of the procedure. This commit also changes the name displayed for a procedure in the output of `EXPLAIN (OPT)` from `udf` to `procedure`.

Fixes #114674

Release note (sql change): It is now possible to run CALL statements with EXPLAIN. The `EXPLAIN (OPT)` variant will show the body of the procedure, while other variants will only show the procedure name and arguments.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

Might also be good to add a test to `explain_bundle_test.go` that ensures that no errors are encountered and the expected files are added to the bundle.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-:-Nkc44UKC68S7vr195BU:b1cgzfi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rharding6373)

___
*[`pkg/sql/opt/memo/expr.go` line 711 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-Nkc2exC-2Nh7C8p7RpD:-Nkc2exC-2Nh7C8p7RpE:bmgumuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bcfa5afb81764a01ed93cd3e2901a14d1ce4154/pkg/sql/opt/memo/expr.go#L711)):*
> ```Go
> 
> 	// RoutineType indicates whether this routine is a UDF, stored procedure, or
>   // builtin function.
> ```

nit: indentation is off.
___
*[`pkg/sql/logictest/testdata/logic_test/prepare` line 1697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-Nkc3QEPD9eCc6X3euR8:-Nkc3QEPD9eCc6X3euR9:b-vq6gmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bcfa5afb81764a01ed93cd3e2901a14d1ce4154/pkg/sql/logictest/testdata/logic_test/prepare#L1697)):*
> ```
> {red}
> 
> subtest prepare_call
> ```

nit: do we need `subtest end` before starting another `subtest`?

**Review by rharding6373 — APPROVED** [review]
:lgtm: with some added tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-:-Nkq8Z3G8yWWlj3McmWt:b-n8a8j6)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/prepare` line 1706 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-Nkq6tvW-SCObZmIE1qA:-Nkq6tvW-SCObZmIE1qB:b8b4sls) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bcfa5afb81764a01ed93cd3e2901a14d1ce4154/pkg/sql/logictest/testdata/logic_test/prepare#L1706)):*
> ```
> $$;
> 
> statement error pgcode 42601 pq: statement ignored: at or near \"call\": syntax error
> ```

looks like the error doesn't contain "statement ignored:"
___
*[`pkg/sql/opt/exec/execbuilder/testdata/call` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-Nkq7RvA-vpEmYRoxdyM:-Nkq7RvA-vpEmYRoxdyN:bywtsy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bcfa5afb81764a01ed93cd3e2901a14d1ce4154/pkg/sql/opt/exec/execbuilder/testdata/call#L170)):*
> ```
>   nodes: <hidden>
>   regions: <hidden>
>   actual row count: 0
> ```

I think a test that produces some rows and seeing that reflected in the explain output and distsql diagram would be valuable.
___
*[`pkg/sql/opt/optbuilder/testdata/procedure` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-Nkq7iGQ0-RZ_8uQG2x4:-Nkq7iGQ0-RZ_8uQG2x5:b-xss0yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bcfa5afb81764a01ed93cd3e2901a14d1ce4154/pkg/sql/opt/optbuilder/testdata/procedure#L27)):*
> ```
> ----
> call
>  └── procedure: p
> ```

nice :-)

**Review by DrewKimball — COMMENTED** [review]
>Might also be good to add a test to `explain_bundle_test.go` that ensures that no errors are encountered and the expected files are added to the bundle.

I added another commit with a test, and added logic to make sure the create statement is added to `schema.sql`. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-:-NksNLBvB8KHqGMcmjYp:b-rko4kk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @rharding6373, and @yuzefovich)

___
*[`pkg/sql/opt/memo/expr.go` line 711 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-Nkc2exC-2Nh7C8p7RpD:-Nkr80tD8HMHjeF0VPeT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bcfa5afb81764a01ed93cd3e2901a14d1ce4154/pkg/sql/opt/memo/expr.go#L711)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: indentation is off.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/prepare` line 1697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-Nkc3QEPD9eCc6X3euR8:-Nkr71SH0S8neH3reLT7:b-gh2eve) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bcfa5afb81764a01ed93cd3e2901a14d1ce4154/pkg/sql/logictest/testdata/logic_test/prepare#L1697)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: do we need `subtest end` before starting another `subtest`?
</blockquote></details>

I don't think it's necessary. I'm not sure the logictest framework even distinguishes that command from an empty subtest named `end`, actually.
___
*[`pkg/sql/logictest/testdata/logic_test/prepare` line 1706 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-Nkq6tvW-SCObZmIE1qA:-Nkr7QBDAw-wiwqlvAeO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bcfa5afb81764a01ed93cd3e2901a14d1ce4154/pkg/sql/logictest/testdata/logic_test/prepare#L1706)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

looks like the error doesn't contain "statement ignored:"
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/call` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-Nkq7RvA-vpEmYRoxdyM:-NkrABS-Ao4IaHGMjxEi:bz62nzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bcfa5afb81764a01ed93cd3e2901a14d1ce4154/pkg/sql/opt/exec/execbuilder/testdata/call#L170)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think a test that produces some rows and seeing that reflected in the explain output and distsql diagram would be valuable.
</blockquote></details>

A call statement never outputs rows (until we support out parameters, I guess). And we don't show the body here because it's built lazily during execution. UDFs and apply-joins have the same problem. Which I guess means that the non-bundle variants of `EXPLAIN ANALYZE` aren't very useful yet.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-:-NkvDDjE2QpV8ryd0KfL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @mgartner, and @rharding6373)

___
*[`pkg/sql/explain_bundle.go` line 548 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-NkvCSdB7C8Ql_NCCp2l:-NkvCSdB7C8Ql_NCCp2m:beorbkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/46825ff4084fc3fa41a898ea0fa75b267d663309/pkg/sql/explain_bundle.go#L548)):*
> ```Go
> 		// Currently, a stored procedure can only be called from a CALL statement,
> 		// which can only be the root expression.
> 		proc := call.Proc.(*memo.UDFCallExpr)
> ```

nit: should we do `proc, ok := call.Proc.(*memo.UDFCallExpr)` to be safe in case in the future we forget to update this spot?
___
*[`pkg/sql/explain_bundle.go` line 554 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-NkvCwn7BnElvXH5PHhv:-NkvCgXD5MD4Vr5Kzms8:b-t3glmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/46825ff4084fc3fa41a898ea0fa75b267d663309/pkg/sql/explain_bundle.go#L554)):*
> ```Go
> 		)
> 		if err != nil {
> 			b.printError(fmt.Sprintf("-- error getting schema for udfs: %v", err), &buf)
> ```

nit: maybe `s/udfs/procedures/`?
___
*[`pkg/sql/explain_bundle_test.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-NkvD3C757pOSUp9vjom:-NkvD3C757pOSUp9vjon:brhhya3) ([raw file](https://github.com/cockroachdb/cockroach/blob/46825ff4084fc3fa41a898ea0fa75b267d663309/pkg/sql/explain_bundle_test.go#L70)):*
> ```Go
> 		base, plans, "stats-defaultdb.public.abc.sql", "distsql.html vec.txt vec-v.txt",
> 	)
> ```

nit: stray newline.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-:-NkvKQqN4tyPEpVyGbIu:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/call` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-Nkq7RvA-vpEmYRoxdyM:-NkvKJBmC4DbWEpuXriX:bhtlgux) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bcfa5afb81764a01ed93cd3e2901a14d1ce4154/pkg/sql/opt/exec/execbuilder/testdata/call#L170)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

A call statement never outputs rows (until we support out parameters, I guess). And we don't show the body here because it's built lazily during execution. UDFs and apply-joins have the same problem. Which I guess means that the non-bundle variants of `EXPLAIN ANALYZE` aren't very useful yet.
</blockquote></details>

Right, that's right. Thanks.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115468)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/explain_bundle.go` line 548 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-NkvCSdB7C8Ql_NCCp2l:-Nl-NRCRDMXBIYTD_Vny:bqjrebq) ([raw file](https://github.com/cockroachdb/cockroach/blob/46825ff4084fc3fa41a898ea0fa75b267d663309/pkg/sql/explain_bundle.go#L548)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we do `proc, ok := call.Proc.(*memo.UDFCallExpr)` to be safe in case in the future we forget to update this spot?
</blockquote></details>

Good idea, Done. I added a printed error if that check fails.
___
*[`pkg/sql/explain_bundle.go` line 554 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-NkvCwn7BnElvXH5PHhv:-Nl-NUYXEvMPP2XrGRFq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/46825ff4084fc3fa41a898ea0fa75b267d663309/pkg/sql/explain_bundle.go#L554)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe `s/udfs/procedures/`?
</blockquote></details>

Done.
___
*[`pkg/sql/explain_bundle_test.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115468#-NkvD3C757pOSUp9vjom:-Nl-Nn_z-562ZvW0SyzN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/46825ff4084fc3fa41a898ea0fa75b267d663309/pkg/sql/explain_bundle_test.go#L70)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: stray newline.
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
I think this needs a rebase / adjustment for plpgsql licensing change.

bors r-

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Comment by DrewKimball** [comment]
bors retry

**Pull request merged**
