### PR TITLE
serverutils: probabilistic shared process virtual cluster

### LINKED ISSUE #111134: multitenant: Randomly test over all three tenancy configurations
We currently have three supported tenancy configurations in which to run CRDB:

* Single tenant 
* Shared-process multi-tenant (aka cluster virtualization)
* Separate-process multi-tenant

https://github.com/cockroachdb/cockroach/pull/76582 (and several follow-on PRs) allowed for the ability to randomly test the first two configurations.  This issue should add the third configuration to the randomization.

Epic CRDB-31933
Jira issue: CRDB-31784

### PR DESCRIPTION
**Pull request by herkolategan**
This PR contain several commits that ultimately enables the probabilistic selection of a shared process test virtual cluster that tests run against, iff the test also probabilistically decided to run with a test tenant. Previously only an external process virtual cluster would be available as an option when deciding to run with a test virtual cluster.

Additionally some API changes have been made to serverutils to encourage the use of the test interface layers when working with a test server or cluster. Tests that use other utility methods to connect or create connection URLs may not be aware of a test virtual cluster and lack required information when interacting with the cluster resulting in flakiness and failures.

Finally this change also disables selecting a shared process virtual cluster instead of an external process virtual cluster for tests which fail with a shared process virtual cluster. An issue has been created to track these tests: https://github.com/cockroachdb/cockroach/issues/112857
Issues linked to this issue will contain more detail relating to the failure. And the issue has been referenced in the code itself when disabling a shared process virtual cluster for a specific test.

Resolves: #111134

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Nice work!

I have some questions and some nits.

I also wonder whether eventually we want to merge `StartTenant` and `StartSharedProcessTenant` into one and adjust the existing tests that use "explicit tenant" option with `StartTenant` to also run probabilistically between the two modes. Thoughts?

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 25 of 25 files at r4, 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-:-NhcytyD9Gil2ggNoCnn:b-mlzrvs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @DarrylWong, @dhartunian, @herkolategan, @jayshrivastava, and @srosenberg)

___
*[`pkg/base/test_server_args.go` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhcqF8LBFQthDOLBjU9:-NhcqF8LBFQthDOLBjUA:b-gicus8) ([raw file](https://github.com/cockroachdb/cockroach/blob/26c4ea0e5fff5bede1bf737cb36a18d7ce000eec/pkg/base/test_server_args.go#L404)):*
> ```Go
> }
> 
> func TestDoesNotWorkWithSharedProcessModeButWeDontKnowWhyYet(
> ```

nit: comments to these two methods would be helpful. In particular, it's worth calling out that `baseOptions` is adjusted to use the external process mode. I also don't immediately see why we have the panics in place - explaining that either at the function comment level or close to the panics would be nice.
___
*[`pkg/base/test_server_args.go` line 411 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcpp90DKmbzR7LxDDA:-Nhcpp90DKmbzR7LxDDB:b-cjrnx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/26c4ea0e5fff5bede1bf737cb36a18d7ce000eec/pkg/base/test_server_args.go#L411)):*
> ```Go
> 	}
> 	if baseOptions.testBehavior&ttSharedProcess != 0 {
> 		panic("test behavior cannot be be set to a shared process.")
> ```

nit: `s/be be/be/`.
___
*[`pkg/server/testserver.go` line 678 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcu-auE87WUaPCzhOw:-Nhcu-auE87WUaPCzhOx:bkmxubc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e00f8872dbaa18555573a532cdccdc5d2821c9cf/pkg/server/testserver.go#L678)):*
> ```Go
> // maybeStartDefaultTestTenant might start a test tenant. This can then be used
> // for multi-tenant testing, where the default SQL connection will be made to
> // this tenant instead of to the system tenant. Note that we will
> ```

nit: the last two sentences in this comment are actually no longer - we no longer require CCL license for this.
___
*[`pkg/server/testserver.go` line 743 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcv1s9ELHq_xVSPuji:-Nhcv1s9ELHq_xVSPujj:b-cmcui3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e00f8872dbaa18555573a532cdccdc5d2821c9cf/pkg/server/testserver.go#L743)):*
> ```Go
> }
> 
> func (ts *testServer) grantDefaultSharedProcessCapabilities(
> ```

This logic seems like it should be shared between "shared" and "external" modes. What's the rationale for keeping it separate?
___
*[`pkg/server/testserver.go` line 763 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhcvSVsDxyPINMXwoBN:-NhcvSVsDxyPINMXwoBO:b-9f1yl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e00f8872dbaa18555573a532cdccdc5d2821c9cf/pkg/server/testserver.go#L763)):*
> ```Go
> 		return err
> 	}
> 	err := execSQL("set-tenant-capability",
> ```

In the "external" mode we try to not grant any capabilities unless it seems necessary because it adds to the startup time. (This might be sped up by #112094 but Steven would know best about that.) Should we apply a similar check to see whether we need to grant these capabilities based on the test config?
___
*[`pkg/server/testserver_sqlconn.go` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhct2Kf9wWqON0VUq3T:-Nhct2Kf9wWqON0VUq3U:b-izjcs1) ([raw file](https://github.com/cockroachdb/cockroach/blob/984ae9c926101a4ba1faa226462c85af030e50de/pkg/server/testserver_sqlconn.go#L53)):*
> ```Go
> 	clientCerts bool,
> 	prefix string,
> ) (url.URL, func(), error) {
> ```

nit: perhaps name the second return parameter explicitly.
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcq_du014f247bvSgG:-Nhcq_du014f247bvSgH:b8ony96) ([raw file](https://github.com/cockroachdb/cockroach/blob/26c4ea0e5fff5bede1bf737cb36a18d7ce000eec/pkg/testutils/serverutils/test_server_shim.go#L76)):*
> ```Go
> 	t TestLogger, baseArg base.DefaultTestTenantOptions,
> ) (retval base.DefaultTestTenantOptions) {
> 	// Explicit cases for enabling or disabling the default test tenant.
> ```

nit: the comment needs a minor adjustment.
___
*[`pkg/ccl/spanconfigccl/spanconfiglimiterccl/testdata/indexes` line 4 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcx7629XiyG7b3LO16:-Nhcx7629XiyG7b3LO17:b-85bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a03af6dc2e56034fd415991aa7eef89d981a56e0/pkg/ccl/spanconfigccl/spanconfiglimiterccl/testdata/indexes#L4)):*
> ```
> # dropping secondary indexes, and then dropping the table entirely.
> 
> initialize tenant=11
> ```

Why did this change?
___
*[`pkg/base/test_server_args_test.go` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhcrjZ86SmASFCvWf9R:-NhcrjZ86SmASFCvWf9S:b-gjizg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/26c4ea0e5fff5bede1bf737cb36a18d7ce000eec/pkg/base/test_server_args_test.go#L25)):*
> ```Go
> 		name     string
> 		tb       testBehavior
> 		expected bool
> ```

nit: perhaps `s/expected/expectedNoDecision/`.
___
*[`pkg/sql/importer/import_stmt_test.go` line 1699 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhcwYoW7Bb7r-o5yzJO:-NhcwYoW7Bb7r-o5yzJP:bz069zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/31605d4ee6f5ffda011fa4ccde8f7811e2d41d45/pkg/sql/importer/import_stmt_test.go#L1699)):*
> ```Go
> 
> 	// Also create a pgx connection so we can check notices.
> 	pgURL, cleanup := tc.Server(0).PGUrl(
> ```

nit: do `s/Server/ApplicationLayerInterface`.

**Review by herkolategan — COMMENTED** [review]
Thanks for the excellent review!
> I also wonder whether eventually we want to merge `StartTenant` and `StartSharedProcessTenant` into one and adjust the existing tests that use "explicit tenant" option with `StartTenant` to also run probabilistically between the two modes. Thoughts?

I think this is a great idea, we can surely do it in a follow up PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-:-Nhfb6rSEDRbx_ZIAgsB:bro96wy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @DarrylWong, @dhartunian, @herkolategan, @jayshrivastava, @srosenberg, and @yuzefovich)

___
*[`pkg/base/test_server_args.go` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhcqF8LBFQthDOLBjU9:-NhfugbC4YZm0Lsl8brO:b7tayk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/26c4ea0e5fff5bede1bf737cb36a18d7ce000eec/pkg/base/test_server_args.go#L404)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: comments to these two methods would be helpful. In particular, it's worth calling out that `baseOptions` is adjusted to use the external process mode. I also don't immediately see why we have the panics in place - explaining that either at the function comment level or close to the panics would be nice.
</blockquote></details>

Good catch, I planned to add comments to these methods but forgot to. Done; some part of me wants to merge the two functions since they are very similar, but since it's mostly documenting functions I've kept it separate and duplicated parts of the description.
___
*[`pkg/base/test_server_args.go` line 411 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcpp90DKmbzR7LxDDA:-Nhg7igG9OmGuEgyeOch:b94l0d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/26c4ea0e5fff5bede1bf737cb36a18d7ce000eec/pkg/base/test_server_args.go#L411)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/be be/be/`.
</blockquote></details>

Whoops, nice catch, thanks. Done.
___
*[`pkg/server/testserver.go` line 678 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcu-auE87WUaPCzhOw:-Nhg7vmd2h_sb1vXYwGg:b-b5cz09) ([raw file](https://github.com/cockroachdb/cockroach/blob/e00f8872dbaa18555573a532cdccdc5d2821c9cf/pkg/server/testserver.go#L678)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the last two sentences in this comment are actually no longer - we no longer require CCL license for this.
</blockquote></details>

True. Done.
___
*[`pkg/server/testserver.go` line 743 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcv1s9ELHq_xVSPuji:-Nhg82Vy6fFqYEDP2B4q:bxme321) ([raw file](https://github.com/cockroachdb/cockroach/blob/e00f8872dbaa18555573a532cdccdc5d2821c9cf/pkg/server/testserver.go#L743)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This logic seems like it should be shared between "shared" and "external" modes. What's the rationale for keeping it separate?
</blockquote></details>

I agree and I had the same thought, my only rotational was that I didn't fully comprehend the differences in capabilities between external and shared. But it's clear now that it's the same, except for I think `can debug process` works on external without explicitly setting it here. Busy merging these two, as well as taking the comment around selective capabilities into account.
___
*[`pkg/server/testserver.go` line 763 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhcvSVsDxyPINMXwoBN:-NhgbotI6eLP4anILGVd:b-907nsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e00f8872dbaa18555573a532cdccdc5d2821c9cf/pkg/server/testserver.go#L763)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

In the "external" mode we try to not grant any capabilities unless it seems necessary because it adds to the startup time. (This might be sped up by #112094 but Steven would know best about that.) Should we apply a similar check to see whether we need to grant these capabilities based on the test config?
</blockquote></details>

Will be done in addition to removing the duplication of process capabilities. I'll just ask for a second look once I'm done.
___
*[`pkg/server/testserver_sqlconn.go` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhct2Kf9wWqON0VUq3T:-Nhg8nTCEp9DGpswHPxN:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/984ae9c926101a4ba1faa226462c85af030e50de/pkg/server/testserver_sqlconn.go#L53)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps name the second return parameter explicitly.
</blockquote></details>

done.
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcq_du014f247bvSgG:-Nhg8rC9DqeJ6o0JC3eS:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/26c4ea0e5fff5bede1bf737cb36a18d7ce000eec/pkg/testutils/serverutils/test_server_shim.go#L76)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the comment needs a minor adjustment.
</blockquote></details>

done.
___
*[`pkg/ccl/spanconfigccl/spanconfiglimiterccl/testdata/indexes` line 4 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcx7629XiyG7b3LO16:-Nhg8x2V21mKtXXElwBq:b-glms8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a03af6dc2e56034fd415991aa7eef89d981a56e0/pkg/ccl/spanconfigccl/spanconfiglimiterccl/testdata/indexes#L4)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Why did this change?
</blockquote></details>

This test has scenarios where it both uses either the default test tenant or creates its own tenant with the command above. The problem is tenant 10 is the Default Test Tenant as well. And if the test framework starts a default test tenant as a shared process and this test tries to start an external tenant on the same ID it fails. The start tenant method usually accepts when trying to start an already started tenant, but not if it is for a different process mode. An investigation may be required to decide if this test should at all enable the default test tenant.
___
*[`pkg/base/test_server_args_test.go` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhcrjZ86SmASFCvWf9R:-Nhg9QD29VPZV6wyU_vB:b38le2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/26c4ea0e5fff5bede1bf737cb36a18d7ce000eec/pkg/base/test_server_args_test.go#L25)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps `s/expected/expectedNoDecision/`.
</blockquote></details>

good call, will make it clearer. done.
___
*[`pkg/sql/importer/import_stmt_test.go` line 1699 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhcwYoW7Bb7r-o5yzJO:-Nhg9SSy7XaZSv8msyE8:buwqjy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/31605d4ee6f5ffda011fa4ccde8f7811e2d41d45/pkg/sql/importer/import_stmt_test.go#L1699)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: do `s/Server/ApplicationLayerInterface`.
</blockquote></details>

good catch. done.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @DarrylWong, @dhartunian, @jayshrivastava, @srosenberg, and @yuzefovich)

___
*[`pkg/server/testserver.go` line 743 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhcv1s9ELHq_xVSPuji:-NhljXLBE63s4sQ8_kXt:bcix9e3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e00f8872dbaa18555573a532cdccdc5d2821c9cf/pkg/server/testserver.go#L743)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

I agree and I had the same thought, my only rotational was that I didn't fully comprehend the differences in capabilities between external and shared. But it's clear now that it's the same, except for I think `can debug process` works on external without explicitly setting it here. Busy merging these two, as well as taking the comment around selective capabilities into account.
</blockquote></details>

Merged the two, but there is still a bit of work left I intend to complete in a follow-up PR: #107695, #113187
___
*[`pkg/server/testserver.go` line 763 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhcvSVsDxyPINMXwoBN:-Nhlk3HM1OiQMlnVl81m:b-83xred) ([raw file](https://github.com/cockroachdb/cockroach/blob/e00f8872dbaa18555573a532cdccdc5d2821c9cf/pkg/server/testserver.go#L763)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Will be done in addition to removing the duplication of process capabilities. I'll just ask for a second look once I'm done.
</blockquote></details>

I've added the check you have mentioned as well.

**Review by yuzefovich — APPROVED** [review]
I have a few more comments, but it :lgtm: It might still be worth it to wait for @stevendanna to take a look at least at the testserver changes.

> Reviewed 48 of 48 files at r6, 4 of 4 files at r7, 1 of 1 files at r8, 25 of 25 files at r9, 21 of 21 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-:-Nhn77f68PraFf4hAjuR:b-mciszo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @DarrylWong, @dhartunian, @herkolategan, @jayshrivastava, and @srosenberg)

___
*[`pkg/server/testserver.go` line 762 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhmzUun0XkbiYkcVal0:-NhmzUun0XkbiYkcVal1:bpv2im4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff38cb2e5fb0b89ad7721e13d8214528d7ac43c7/pkg/server/testserver.go#L762)):*
> ```Go
> 	}
> 
> 	// Waiting for capabilities can time To avoid paying this cost in all
> ```

nit: `s/can time/can time./`.
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 105 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhn2fMq4avTOvyy6oiX:-Nhn2fMq4avTOvyy6oiY:bbb3ter) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a84cc656b908953fe21e11ead01ddef5ec24e9f/pkg/testutils/serverutils/test_server_shim.go#L105)):*
> ```Go
> 		shared = false
> 	default:
> 		shared = util.ConstantWithMetamorphicTestBoolWithoutLogging("test-tenant-shared-process", false)
> ```

nit: what's the rationale for using metamorphic helper here? I'd have expected that here we'd give each mode 50% probability, and the current way will pick the external process more frequently.
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 115 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhn35BxBhQ15RDNF1Lw:-Nhn35BxBhQ15RDNF1Lx:b-45icpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a84cc656b908953fe21e11ead01ddef5ec24e9f/pkg/testutils/serverutils/test_server_shim.go#L115)):*
> ```Go
> 
> 	// Obey the env override if present.
> 	if str, present := envutil.EnvString("COCKROACH_TEST_TENANT", 0); present {
> ```

It might be nice to have a way to force the default test tenant with a particular process mode. We could either adjust the existing env var to take in a string or something, or introduce another bool env var that controls whether the shared process is picked (I'd probably prefer the latter option slightly), or perhaps in some other fashion. This doesn't have to be in this PR, but please leave a TODO for this if it's not done.
___
*[`pkg/sql/tests/show_commit_timestamp_test.go` line 80 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhn655s6bRB5hMHRS9o:-Nhn655s6bRB5hMHRS9p:bip09n1) ([raw file](https://github.com/cockroachdb/cockroach/blob/24a26be14f54df70164f866774583fb1e910c7db/pkg/sql/tests/show_commit_timestamp_test.go#L80)):*
> ```Go
> 	testutils.RunTrueAndFalse(t, "pgx batch; simple", func(t *testing.T, simple bool) {
> 		resetTable(t)
> 		pgURL, cleanup := s.PGUrl(t)
> ```

nit: add `.ApplicationLayer()` here and below.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112822)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @DarrylWong, @jayshrivastava, @srosenberg, and @yuzefovich)

___
*[`pkg/server/testserver.go` line 762 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-NhmzUun0XkbiYkcVal0:-Ni09Ytd5-w0ga5O9pdF:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff38cb2e5fb0b89ad7721e13d8214528d7ac43c7/pkg/server/testserver.go#L762)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/can time/can time./`.
</blockquote></details>

done.
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 105 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhn2fMq4avTOvyy6oiX:-Ni09aCtB9ImJrmZgrXs:bvt7k9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a84cc656b908953fe21e11ead01ddef5ec24e9f/pkg/testutils/serverutils/test_server_shim.go#L105)):*
> metamorphicBuildProbability \= 0.8

Ah right, metamorphic eligible builds don't always run metamorphic, so the 50% bool selection is slanted ~40% for the default case.
I'll update this to use the `randutil`.
___
*[`pkg/testutils/serverutils/test_server_shim.go` line 115 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhn35BxBhQ15RDNF1Lw:-Ni0CoFh1HQ60jCtvCME:bxm7g9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a84cc656b908953fe21e11ead01ddef5ec24e9f/pkg/testutils/serverutils/test_server_shim.go#L115)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It might be nice to have a way to force the default test tenant with a particular process mode. We could either adjust the existing env var to take in a string or something, or introduce another bool env var that controls whether the shared process is picked (I'd probably prefer the latter option slightly), or perhaps in some other fashion. This doesn't have to be in this PR, but please leave a TODO for this if it's not done.
</blockquote></details>

Good idea; adding a TODO.
___
*[`pkg/sql/tests/show_commit_timestamp_test.go` line 80 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/112822#-Nhn655s6bRB5hMHRS9o:-Ni0Y6qs9qCTno8aQ37l:b1jxzi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/24a26be14f54df70164f866774583fb1e910c7db/pkg/sql/tests/show_commit_timestamp_test.go#L80)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: add `.ApplicationLayer()` here and below.
</blockquote></details>

good catch, done.

**Review by stevendanna — APPROVED** [review]
I really like where this landed.  Thanks for pushing this forward and working to integrate it nicely into the existing test-server setup.

**Comment by herkolategan** [comment]
TFTRs!

bors r=yuzefovich,stevendanna

**Pull request merged**
