### PR TITLE
logictest: revert some incorrect recent rewrites

### LINKED ISSUE #134299: pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test: TestLogic_zone_config_system_tenant failed
pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test.TestLogic_zone_config_system_tenant [failed](https://tanzanite.cluster.engflow.com/invocations/default/a664d1bf-f30d-4b79-afa3-4cbd3d2a1187?testReportRun=1&testReportShard=24&testReportAttempt=1#targets-Ly9wa2cvc3FsL2xvZ2ljdGVzdC90ZXN0cy9mYWtlZGlzdC1kaXNrOmZha2VkaXN0LWRpc2tfdGVzdA==) on master @ [e8f6410ecd99591fd6103dd8461ea3fb0361f8d6](https://github.com/cockroachdb/cockroach/commits/e8f6410ecd99591fd6103dd8461ea3fb0361f8d6):

```
=== RUN   TestLogic_zone_config_system_tenant
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestLogic_zone_config_system_tenant3169770164
    test_log_scope.go:76: use -show-logs to present logs inline
    test_server_shim.go:139: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    logic.go:4404: -- test log scope end --
test logs left over in: outputs.zip/logTestLogic_zone_config_system_tenant3169770164
--- FAIL: TestLogic_zone_config_system_tenant (68.33s)
=== RUN   TestLogic_zone_config_system_tenant/dropped_relation_gc_ttl
[11:14:24] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 31 statements
[11:14:27] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 32 statements
[11:14:29] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 34 statements
    logic.go:3033: 
         
        /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant:198: SELECT
          crdb_internal.pretty_key(start_key, -1),
          crdb_internal.pb_to_json('cockroach.roachpb.SpanConfig', config)->'gcPolicy'->>'ttlSeconds'
        FROM system.span_configurations
        WHERE start_key >= (SELECT crdb_internal.table_span(100)[1])
        ORDER BY start_key
        expected:
            /Table/106  14400
            /Table/107  14400
            /Table/110  90001
            /Table/111  90001
            /Table/112  14400
            
        but found (query options: "retry") :
            /Table/106  14400
            /Table/107  14400
            /Table/110  90001
            /Table/111  1
            /Table/112  1
            
[11:15:14] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 35 statements
[11:15:14] --- done: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant with config fakedist-disk: 35 tests, 1 failures
[11:15:20] --- total progress: 35 statements
--- total: 35 tests, 1 failures
    --- FAIL: TestLogic_zone_config_system_tenant/dropped_relation_gc_ttl (53.05s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=24</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_zone_config_system_tenant.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44010

### LINKED ISSUE #134300: pkg/sql/logictest/tests/fakedist/fakedist_test: TestLogic_zone_config_system_tenant failed
pkg/sql/logictest/tests/fakedist/fakedist_test.TestLogic_zone_config_system_tenant [failed](https://tanzanite.cluster.engflow.com/invocations/default/a664d1bf-f30d-4b79-afa3-4cbd3d2a1187?testReportRun=2&testReportShard=27&testReportAttempt=1#targets-Ly9wa2cvc3FsL2xvZ2ljdGVzdC90ZXN0cy9mYWtlZGlzdDpmYWtlZGlzdF90ZXN0) on master @ [e8f6410ecd99591fd6103dd8461ea3fb0361f8d6](https://github.com/cockroachdb/cockroach/commits/e8f6410ecd99591fd6103dd8461ea3fb0361f8d6):

```
=== RUN   TestLogic_zone_config_system_tenant
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestLogic_zone_config_system_tenant1643130383
    test_log_scope.go:76: use -show-logs to present logs inline
    test_server_shim.go:139: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    logic.go:4404: -- test log scope end --
test logs left over in: outputs.zip/logTestLogic_zone_config_system_tenant1643130383
--- FAIL: TestLogic_zone_config_system_tenant (68.04s)
=== RUN   TestLogic_zone_config_system_tenant/dropped_relation_gc_ttl
[11:46:14] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 31 statements
[11:46:17] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 33 statements
    logic.go:3033: 
         
        /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant:198: SELECT
          crdb_internal.pretty_key(start_key, -1),
          crdb_internal.pb_to_json('cockroach.roachpb.SpanConfig', config)->'gcPolicy'->>'ttlSeconds'
        FROM system.span_configurations
        WHERE start_key >= (SELECT crdb_internal.table_span(100)[1])
        ORDER BY start_key
        expected:
            /Table/106  14400
            /Table/107  14400
            /Table/110  90001
            /Table/111  90001
            /Table/112  14400
            
        but found (query options: "retry") :
            /Table/106  14400
            /Table/107  14400
            /Table/110  90001
            /Table/111  1
            /Table/112  1
            
[11:47:04] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 35 statements
[11:47:04] --- done: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant with config fakedist: 35 tests, 1 failures
[11:47:09] --- total progress: 35 statements
--- total: 35 tests, 1 failures
    --- FAIL: TestLogic_zone_config_system_tenant/dropped_relation_gc_ttl (52.54s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=27</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_zone_config_system_tenant.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44011

### LINKED ISSUE #134404: pkg/sql/logictest/tests/fakedist-vec-off/fakedist-vec-off_test: TestLogic_zone_config_system_tenant failed
pkg/sql/logictest/tests/fakedist-vec-off/fakedist-vec-off_test.TestLogic_zone_config_system_tenant [failed](https://tanzanite.cluster.engflow.com/invocations/default/53efa5c8-5982-4049-8d31-516dc6d35af4?testReportRun=3&testReportShard=23&testReportAttempt=1#targets-Ly9wa2cvc3FsL2xvZ2ljdGVzdC90ZXN0cy9mYWtlZGlzdC12ZWMtb2ZmOmZha2VkaXN0LXZlYy1vZmZfdGVzdA==) on master @ [f5fde858b71c965da8068e211e46d2a3d297e876](https://github.com/cockroachdb/cockroach/commits/f5fde858b71c965da8068e211e46d2a3d297e876):

```
=== RUN   TestLogic_zone_config_system_tenant
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestLogic_zone_config_system_tenant3959901861
    test_log_scope.go:76: use -show-logs to present logs inline
    test_server_shim.go:139: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    logic.go:4404: -- test log scope end --
test logs left over in: outputs.zip/logTestLogic_zone_config_system_tenant3959901861
--- FAIL: TestLogic_zone_config_system_tenant (67.35s)
=== RUN   TestLogic_zone_config_system_tenant/dropped_relation_gc_ttl
[11:29:32] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-vec-off/fakedist-vec-off_test_/fakedist-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 31 statements
[11:29:35] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-vec-off/fakedist-vec-off_test_/fakedist-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 32 statements
[11:29:37] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-vec-off/fakedist-vec-off_test_/fakedist-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 34 statements
    logic.go:3033: 
         
        /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-vec-off/fakedist-vec-off_test_/fakedist-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant:198: SELECT
          crdb_internal.pretty_key(start_key, -1),
          crdb_internal.pb_to_json('cockroach.roachpb.SpanConfig', config)->'gcPolicy'->>'ttlSeconds'
        FROM system.span_configurations
        WHERE start_key >= (SELECT crdb_internal.table_span(100)[1])
        ORDER BY start_key
        expected:
            /Table/106  14400
            /Table/107  14400
            /Table/110  90001
            /Table/111  90001
            /Table/112  14400
            
        but found (query options: "retry") :
            /Table/106  14400
            /Table/107  14400
            /Table/110  90001
            /Table/111  1
            /Table/112  1
            
[11:30:22] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-vec-off/fakedist-vec-off_test_/fakedist-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 35 statements
[11:30:22] --- done: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist-vec-off/fakedist-vec-off_test_/fakedist-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant with config fakedist-vec-off: 35 tests, 1 failures
[11:30:28] --- total progress: 35 statements
--- total: 35 tests, 1 failures
    --- FAIL: TestLogic_zone_config_system_tenant/dropped_relation_gc_ttl (52.59s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=23</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_zone_config_system_tenant.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44061

### LINKED ISSUE #134406: pkg/sql/logictest/tests/local-vec-off/local-vec-off_test: TestLogic_zone_config_system_tenant failed
pkg/sql/logictest/tests/local-vec-off/local-vec-off_test.TestLogic_zone_config_system_tenant [failed](https://tanzanite.cluster.engflow.com/invocations/default/53efa5c8-5982-4049-8d31-516dc6d35af4?testReportRun=2&testReportShard=27&testReportAttempt=1#targets-Ly9wa2cvc3FsL2xvZ2ljdGVzdC90ZXN0cy9sb2NhbC12ZWMtb2ZmOmxvY2FsLXZlYy1vZmZfdGVzdA==) on master @ [f5fde858b71c965da8068e211e46d2a3d297e876](https://github.com/cockroachdb/cockroach/commits/f5fde858b71c965da8068e211e46d2a3d297e876):

```
=== RUN   TestLogic_zone_config_system_tenant
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestLogic_zone_config_system_tenant2619407339
    test_log_scope.go:76: use -show-logs to present logs inline
    test_server_shim.go:139: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
[11:13:37] setting distsql_workmem='36127B';
    logic.go:4404: -- test log scope end --
test logs left over in: outputs.zip/logTestLogic_zone_config_system_tenant2619407339
--- FAIL: TestLogic_zone_config_system_tenant (64.81s)
=== RUN   TestLogic_zone_config_system_tenant/dropped_relation_gc_ttl
[11:13:42] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local-vec-off/local-vec-off_test_/local-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 31 statements
[11:13:44] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local-vec-off/local-vec-off_test_/local-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 32 statements
[11:13:46] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local-vec-off/local-vec-off_test_/local-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 34 statements
    logic.go:3033: 
         
        /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local-vec-off/local-vec-off_test_/local-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant:198: SELECT
          crdb_internal.pretty_key(start_key, -1),
          crdb_internal.pb_to_json('cockroach.roachpb.SpanConfig', config)->'gcPolicy'->>'ttlSeconds'
        FROM system.span_configurations
        WHERE start_key >= (SELECT crdb_internal.table_span(100)[1])
        ORDER BY start_key
        expected:
            /Table/106  14400
            /Table/107  14400
            /Table/110  90001
            /Table/111  90001
            /Table/112  14400
            
        but found (query options: "retry") :
            /Table/106  14400
            /Table/107  14400
            /Table/110  90001
            /Table/111  1
            /Table/112  1
            
[11:14:32] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local-vec-off/local-vec-off_test_/local-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant: 35 statements
[11:14:32] --- done: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local-vec-off/local-vec-off_test_/local-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant with config local-vec-off: 35 tests, 1 failures
[11:14:38] --- total progress: 35 statements
--- total: 35 tests, 1 failures
    --- FAIL: TestLogic_zone_config_system_tenant/dropped_relation_gc_ttl (52.76s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=2</code>
 - <code>shard=27</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_zone_config_system_tenant.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-44063

### PR DESCRIPTION
**Pull request by yuzefovich**
These were included in 533e5479f024dd4b07693f892176f6db7c66b31e.

Fixes: #134299
Fixes: #134300
Fixes: #134404
Fixes: #134406

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134432)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Review by michae2 — APPROVED** [review]
:lgtm: arg, this keeps biting us

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134432#-:-OB1lcE869fIifo01KlM:b-rixvxs)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by dt** [comment]
Ooff, sorry about that!

> arg, this keeps biting us

Adding a new _internal only_ debugging virtual table shouldn't update 31 files. These tests are being way too prescriptive about behaviors that are not what the test in intended to actually test -- most of these files are updated just because there happens to be a new virtual table and not because they actually care about that table or its content and behavior at all.

**Review by yuzefovich — COMMENTED** [review]
Michael was referring to [this](https://github.com/cockroachdb/cockroach/issues/130405#issuecomment-2341764875) comment. In other words, we have a poor interaction between `--rewrite` logic test flag and `retry` logic test directive where we could pollute the correct output inadvertently.

I do agree with your point though that overhead of including debugging-only virtual table when updating tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134432#-:-OB1voXc3esFuk98y1G4:b-elzglq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Comment by dt** [comment]
> a poor interaction between --rewrite

Right, and I'm saying that the only reason someone like me is blindly running `rewrite` on a bunch of stuff they didn't touch is because that stuff has decided it wants to be updated -- via `--rewrite` when _unrelated_ thing change.

**Review by michae2 — APPROVED** [review]
(I only meant that this specific query result keeps getting --rewritten incorrectly. I think it should be fine to --rewrite the entire logictest testsuite, and this one query result keeps causing problems.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134432#-:-OB26-iC5dOcMImJqPBB:b-p2uh5l)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Pull request merged**
