### PR TITLE
util: remove unnecessary logs from pgdate.TestParse

### PR DESCRIPTION
**Pull request by RaduBerinde**
The teamcity parser gets confused by the output of this test. I'm hoping this works around that. I'll see if I can hit some flakes in CI in this PR.

### CODE REVIEW

**Comment by jordanlewis** [comment]
LGTM.

**Review by bobvawter — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35760#-:-La0MCNU68sT2f7wwKOB:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by RaduBerinde** [comment]
Hit a flake and still saw "Test ended in panic.". Will try not using the expressions as the subtest name.

**Comment by RaduBerinde** [comment]
Updated to just use indexes in the subtest names.

**Comment by bobvawter** [comment]
Changing it to be index-based would be fine, although there's a go syntax that would ensure that the numbers stay in sync.  You can write a slice as though it were a `map[int]X`

```
x := []string{
	0: "foo",
	1: "bar",
}
```

**Comment by RaduBerinde** [comment]
Excellent idea, done.

**Review by bobvawter — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35760#-:-La0vfhk6T_IQrBvfLuP:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by RaduBerinde** [comment]
No joy, I still see the same thing.

**Comment by RaduBerinde** [comment]
The log looks like this:
```
                --- PASS: TestParse/ParseModeMDYmake: *** [test] Error 1 
/dateTestData-13/timeTestData-36/ParseTime (0.00s) 
[15:33:47] :             [TestParse/ParseModeMDY/dateTestData-13/timeTestData-36] /ParseTimestamp 
```

I think it's this intermingling that's causing the issue. Not sure what can be done about it though.

I will still merge this change as it seems worthwhile to trim down the logs (and it might make this less likely too happen).

bors r+

**Comment by RaduBerinde** [comment]
bors r-

We are still posting a lot of logs, there are ~13000 subtests. I will see if I can trim it down more.

**Comment by RaduBerinde** [comment]
@bobvawter if I mess with the `exp` fields in `timeTestData`, there is no failure (I was trying to check how a failure looks like). I verified on master. I'll let you look at that separately.


```
ok  	github.com/cockroachdb/cockroach/pkg/util/timeutil/pgdate	0.299s
radu (8f9d022)(+1/-1) ~/roach # gdt
diff --git a/pkg/util/timeutil/pgdate/parsing_test.go b/pkg/util/timeutil/pgdate/parsing_test.go
index 4fe2d57..ddc98ec 100644
--- a/pkg/util/timeutil/pgdate/parsing_test.go
+++ b/pkg/util/timeutil/pgdate/parsing_test.go
@@ -448,7 +448,7 @@ var timeTestData = []timeData{
 	},
 	{
 		s:               "2003-06-12 04:05:06 America/New_York",
-		exp:             time.Date(0, 1, 1, 4, 5, 6, 0, time.FixedZone("-0400", -4*60*60)),
+		exp:             time.Date(0, 1, 2, 4, 5, 6, 0, time.FixedZone("-0400", -4*60*60)),
 		expectConcatErr: true,
 		hasTimezone:     true,
 	},

```

**Comment by bobvawter** [comment]
The date components of the values in `timeTestData` are ignored.  That diff would indeed be a no-op.

I'm unclear on the overall problem.  Is there another test which is panicking and the results are getting mangled?

**Comment by RaduBerinde** [comment]
Ah, ok. Another test is failing (no panic). Because of the many thousands of lines printed out by this test, some error message from somewhere `*** [test] Error 1` is getting intermingled. The real problem is somewhere else, but I think trimming down the logs when tests are passing is helpful regardless.

**Comment by RaduBerinde** [comment]
Ok, third time's the charm. I removed the subtests; instead I plumbed the test case information to the errors and reverted the indexing change.

**Review by bobvawter — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35760)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

**Comment by RaduBerinde** [comment]
Hit a flake and no longer see the false TestParse failure.

bors r+

**Pull request merged**
