### PR TITLE
kvserver/rangefeed: abstract registration in interface

### PR DESCRIPTION
**Pull request by wenyihu6**
**kvserver/rangefeed: change registration to be a pointer everywhere**

This patch changes registration to be a pointer everywhere. In a future commit,
we will abstracts registration in an interface and change processor registry to
use that interface. Note that this patch should not change any behavior, and the
main purpose is to make future commits cleaner.

Part of: https://github.com/cockroachdb/cockroach/issues/126560
Release note: none

---

**kvserver/rangefeed: rename registration to buffered registration**

This patch renames registration to buffered registration. In a future commit, we
will introduce another type of registration - unbuffered registration. This is
to distinguish them.

Part of: https://github.com/cockroachdb/cockroach/issues/126560
Release note: none

---

**kvserver/rangefeed: separate out buffered registration into its own file**

This patch separates out buffered registration into its own file.

Part of: https://github.com/cockroachdb/cockroach/issues/126560
Release note: none

---

**kvserver/rangefeed: abstract registration in interface**

This patch abstracts buffered registration in an interface and change processor
registry to use this interface instead. In a future commit, we will introduce
unbuffered registration, and this interface abstracts the implementation
details of buffered and unbuffered registrations. Note that this patch should
not change any behavior, and the main purpose is to make future commits cleaner.

Part of: https://github.com/cockroachdb/cockroach/issues/126560
Release note: none

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 5 of 5 files at r3, 3 of 3 files at r4, 2 of 3 files at r5, 3 of 3 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127834)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`-- commits` line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127834#-O2zPtmt8QTpUhR5XUWg):*
> nonbuffered registration

Go has a concept of "buffered" and "unbuffered" channels. We could adopt that language here as well. So instead of calling the second kind of registration "nonbuffered", call it "unbuffered".
___
*[`pkg/kv/kvserver/rangefeed/buffered_registration.go` line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127834#-O2zRDavBbPttPfDBIFr:-O2zRDaw-aV7y_5ukxtQ:bpdy0bf) ([raw file](https://github.com/cockroachdb/cockroach/blob/33af60068027259815046f32ce03486a1667b625/pkg/kv/kvserver/rangefeed/buffered_registration.go#L30)):*
> ```Go
> )
> 
> // bufferedRegistration is an instance of a rangefeed subscriber who has
> ```

Was this comment the only thing that changed beyond the code movement in commit 3? It's a bit tough to tell.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 440 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127834#-O2zPdIq8-2wVuTzA1H6:-O2zPdIq8-2wVuTzA1H7:b-mmwkoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8119a4bb3cf4f39872a48d5b8434862532613b63/pkg/kv/kvserver/rangefeed/processor.go#L440)):*
> ```Go
> 		case r := <-p.regC:
> 			if !p.Span.AsRawSpanWithNoLocals().Contains(r.span) {
> 				log.Fatalf(ctx, "bufferedRegistration %s not in Processor's key range %v", r, p.Span)
> ```

nit: we probably don't want to change this log text, since it's just referring to the concept of a "registration" and not to a specific type of registration.
___
*[`pkg/kv/kvserver/rangefeed/registry.go` line 47 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/127834#-O2zSVm02OSIkaLARij-:-O2zSVm02OSIkaLARij0:bn4p6hv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56a3528646b9cfa72670b468b44066b43aae477/pkg/kv/kvserver/rangefeed/registry.go#L47)):*
> ```Go
> 	// runOutputLoop runs the output loop for the registration. The output loop is
> 	// meant to be run in a separate goroutine.
> 	runOutputLoop(ctx context.Context, forStacks roachpb.RangeID)
> ```

Does `runOutputLoop` belong on this interface? It seems like it only applies to the `bufferedRegistration` interface.

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127834)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`-- commits` line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127834#-O2zPtmt8QTpUhR5XUWg):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> nonbuffered registration

Go has a concept of "buffered" and "unbuffered" channels. We could adopt that language here as well. So instead of calling the second kind of registration "nonbuffered", call it "unbuffered".
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/rangefeed/buffered_registration.go` line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127834#-O2zRDavBbPttPfDBIFr:-O2zZObA-XIyP8vQXRe5:b-585qt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/33af60068027259815046f32ce03486a1667b625/pkg/kv/kvserver/rangefeed/buffered_registration.go#L30)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Was this comment the only thing that changed beyond the code movement in commit 3? It's a bit tough to tell.
</blockquote></details>

I’ve moved these changes to commit 2 to make it easier to compare. You can copy and compare everything above `func (br \*bufferedRegistration) waitForCaughtUp(ctx context.Context) error { ` with content in original file, and do the same for everything after `waitForCaughtUp`.  I have verified that there are no changes beyond code movement in commit 3. 
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 440 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127834#-O2zPdIq8-2wVuTzA1H6:-O2z_PRJE-g-4nSDYCyR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8119a4bb3cf4f39872a48d5b8434862532613b63/pkg/kv/kvserver/rangefeed/processor.go#L440)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: we probably don't want to change this log text, since it's just referring to the concept of a "registration" and not to a specific type of registration.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/rangefeed/registry.go` line 47 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/127834#-O2zSVm02OSIkaLARij-:-O2z_QHi7zlcuZ57rYcF:b-8k5h7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56a3528646b9cfa72670b468b44066b43aae477/pkg/kv/kvserver/rangefeed/registry.go#L47)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does `runOutputLoop` belong on this interface? It seems like it only applies to the `bufferedRegistration` interface.
</blockquote></details>

I was planning to use runOutputLoop as everything that needs to be run in a separate goroutine. For buffered registration, this goroutine is long-running and volleys updates in buf to underlying stream. For unbuffered registration, this goroutine is short lived - just for catch up scan and draining raft updates stored in catch up buf during catch up scan.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r9, 1 of 3 files at r10, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127834#-:-O2zqiTL-jML-lelviD2:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/registry.go` line 47 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/127834#-O2zSVm02OSIkaLARij-:-O2zqe995OVLzOJQWqNI:b-vcjhub) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56a3528646b9cfa72670b468b44066b43aae477/pkg/kv/kvserver/rangefeed/registry.go#L47)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I was planning to use runOutputLoop as everything that needs to be run in a separate goroutine. For buffered registration, this goroutine is long-running and volleys updates in buf to underlying stream. For unbuffered registration, this goroutine is short lived - just for catch up scan and draining raft updates stored in catch up buf during catch up scan.
</blockquote></details>

Got it, thanks for explaining.

**Comment by wenyihu6** [comment]
TFTR! 

bors r=nvanbenschoten

**Pull request merged**
