### PR TITLE
kvserver: remove ToIsLearner flag from RaftHeartbeat

### PR DESCRIPTION
**Pull request by nvb**
This commit removes the ToIsLearner flag from the RaftHeartbeat message. This is allowed because 20.2 no longer need to deal with preemptive snapshots. This completes @ajwerner's heroic migration started in 99a031d and followed up by b2850e1.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: thanks

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51691#-:-MCql_du5RKxdlBBDmRY:b-v6ynew)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
TFTR!

**Comment by yuzefovich** [comment]
bors crashed, so here is a courtesy ping.

bors r+

**Pull request merged**
