### PR TITLE
docs: add CREATE CHANGEFEED sql diagram

### PR DESCRIPTION
**Pull request by lnhsingh**
Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
Dunno what I'm doing here at all but these ones look like they're implying that you could start the options bit with an `= value` or a comma, which seems off
```
	| 'CREATE' 'CHANGEFEED' 'FOR' table_name ( ( ',' table_name ) )* 'INTO' sink 'WITH'  '=' value ( ( ',' ( option '=' value | option |  '=' value |  ) ) )*
	| 'CREATE' 'CHANGEFEED' 'FOR' table_name ( ( ',' table_name ) )* 'INTO' sink 'WITH'  ( ( ',' ( option '=' value | option |  '=' value |  ) ) )*
```

The repetition has the same issue
```
( option '=' value | option |  '=' value |  )
```

The `'=' value` and the empty branch shouldn't be there. I think it's because you're replacing the SCONST with empty? Can you ignore any branches with that instead?

**Review by lnhsingh — COMMENTED** [review]
I think I fixed it. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29592#-:-LLepo6l2Asb5YwsZPwe:b-4vionq)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by danhhz — COMMENTED** [review]
It's closer but now they're exact duplicates. I tried checking out your branch and playing with it for a bit, but didn't have much luck. maybe have one of the experts take a look? otherwise, backup and restore skirt around this issue by not inlining kv_option_list, which i'm okay with

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29592#-:-LLesACT7jwX67CDDipk:b983hhd)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by lnhsingh — COMMENTED** [review]
@mjibson - are duplicates in the BNF ok? The generated HTML looks correct but we're unsure if I need to clean up the BNF or diagrams.go somehow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29592#-:-LLf6ou27PBoQIlzvWKT:b8381o0)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by mjibson** [comment]
duplicates are fine. this is ok. i looked at this and didn't see a clean way to have it not output duplicates.

**Comment by danhhz** [comment]
:lgtm: then. thanks @mjibson!

**Comment by lhirata** [comment]
TFTRs!

**Pull request merged**
