### PR TITLE
sql: add `sql.log.user_audit.reduced_config.enabled` to support single role checks for role-based audit logs

### PR DESCRIPTION
**Pull request by THardy98**
Part of: https://github.com/cockroachdb/cockroach/issues/100467

This change introduces the `sql.log.user_audit.reduced_config.enabled`
cluster setting. When enabled, this cluster setting computes a "reduced"
audit configuration based on the user's current role memberships and the
current value for the `sql.log.user_audit` cluster setting. The
"reduced" audit configuration is computed at the _first SQL event emit
by the user after the setting is enabled_. Enabling the cluster setting
allows us to compute the audit configuration once at session start,
instead of computing at each SQL event (providing ~5% increase in
throughput). The tradeoff is that changes to the audit configuration
(user role memberships or cluster setting configuration) are not
reflected within session. Users will need to start a new session to see
these changes in their auditing behaviour.

Release note (sql change): Introduce new cluster setting
`sql.log.user_audit.reduced_config.enabled`. When enabled, this cluster
setting computes a "reduced" audit configuration based on the user's
current role memberships and the current value for the
`sql.log.user_audit` cluster setting. The "reduced" audit configuration
is computed at the _first SQL event emit by the user after the setting
is enabled_. Enabling the cluster setting allows us to compute the audit
configuration once at session start, instead of computing at each SQL
event (providing ~5% increase in throughput). The tradeoff is that
changes to the audit configuration (cluster
setting) and the user's role memberships are not reflected within session. Users will need
to start a new session to see these changes in their auditing behaviour.

### CODE REVIEW

**Comment by knz** [comment]
No objection on the approach taken here (I assume only the 2nd commit is new). Will need to be validated through benchmarking.

**Comment by THardy98** [comment]
Yes only the 2nd commit is new.
This is to be merged as a follow-up PR to the original implementation. Enabling/disabling the single-role check logic to be done with a cluster setting.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103759)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @THardy98)

___
*[`-- commits` line 27 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/103759#-NXCCGB01siD2t2HqtRd):*
Is it just the audit configuration or is it also changes to the user's?
___
*[`pkg/sql/audit_logging.go` line 100 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103759#-NXCBkGhDp0EgkzgfNea:-NXCBkGhDp0EgkzgfNeb:bwb7rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b115371e4d4ca9e8a0809467a59a426eecff69/pkg/sql/audit_logging.go#L100)):*
> ```Go
> 	// We do this to avoid the potential overhead of continuously retrying
> 	// to fetch user role memberships.
> 	p.reducedAuditConfig.Initialized = true
> ```

Should there be a lock to prevent multiple requests initializing in parallel?

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103759)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @knz, and @rafiss)

___
*[`-- commits` line 27 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/103759#-NXCCGB01siD2t2HqtRd):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Is it just the audit configuration or is it also changes to the user's?
</blockquote></details>

Sorry the use of parentheses in the release note isn't clear - changes to the audit configuration AND changes the user's actual role memberships.

Updated the release note on the PR

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103759)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @knz, and @rafiss)

___
*[`pkg/sql/audit_logging.go` line 100 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103759#-NXCBkGhDp0EgkzgfNea:-NXCFO6nDXEu6LdT8O7C:b-jrnsdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b115371e4d4ca9e8a0809467a59a426eecff69/pkg/sql/audit_logging.go#L100)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should there be a lock to prevent multiple requests initializing in parallel? 
</blockquote></details>

Likely, yes. I've added a lock here.

**Comment by j82w** [comment]
*[`pkg/sql/audit_logging.go` line 100 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103759#-NXCBkGhDp0EgkzgfNea:-NXCIMfa8h-S57V0IylP:b-s5lvph) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b115371e4d4ca9e8a0809467a59a426eecff69/pkg/sql/audit_logging.go#L100)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Likely, yes. I've added a lock here.
</blockquote></details>

You should add a check here if it's already Initialized then return. Multiple threads can all get through the initial check that doesn't have a lock so all the threads will wait to get the lock here and as each one get the lock it will reinitialize it.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103759)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @knz, and @rafiss)

___
*[`pkg/sql/audit_logging.go` line 100 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103759#-NXCBkGhDp0EgkzgfNea:-NXCOy51CeW26DnZU5Ye:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b115371e4d4ca9e8a0809467a59a426eecff69/pkg/sql/audit_logging.go#L100)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

You should add a check here if it's already Initialized then return. Multiple threads can all get through the initial check that doesn't have a lock so all the threads will wait to get the lock here and as each one get the lock it will reinitialize it. 
</blockquote></details>

Done.

**Review by j82w — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103759#-:-NXCTWRT3DGI8CHCqBNb:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @rafiss)

**Pull request merged**
