### PR TITLE
ci: more logging for `github-pull-request-make` if query fails

### PR DESCRIPTION
**Pull request by rickystewart**
Epic: none
Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
thank you!

**Comment by rickystewart** [comment]
bors r=knz

**Comment by srosenberg** [comment]
@rickystewart `errcmp` linter (part of `roachvet`) failed in `GitHub CI` but not in the bazel analog,

```
=== RUN   TestLint/TestRoachVet
    lint_test.go:95:
        pkg/cmd/github-pull-request-make/main.go:254:29: invalid direct cast on error object
        Alternatives:
           if _, ok := err.(*T); ok        ->   if errors.HasType(err, (*T)(nil))
           if _, ok := err.(I); ok         ->   if errors.HasInterface(err, (*I)(nil))
           if myErr, ok := err.(*T); ok    ->   if myErr := (*T)(nil); errors.As(err, &myErr)
           if myErr, ok := err.(I); ok     ->   if myErr := (I)(nil); errors.As(err, &myErr)
           switch err.(type) { case *T:... ->   switch { case errors.HasType(err, (*T)(nil)): ...
    --- FAIL: TestLint/TestRoachVet (110.18s)
```
Any idea why?

**Comment by knz** [comment]
(I'm sending a patch as part of a different PR to remove the cause of the linter error on `master`. But I agree we should investigate the linter output difference between github CI and the bazel analog)

**Comment by rickystewart** [comment]
> @rickystewart `errcmp` linter (part of `roachvet`) failed in `GitHub CI` but not in the bazel analog,
> 
> ```
> === RUN   TestLint/TestRoachVet
>     lint_test.go:95:
>         pkg/cmd/github-pull-request-make/main.go:254:29: invalid direct cast on error object
>         Alternatives:
>            if _, ok := err.(*T); ok        ->   if errors.HasType(err, (*T)(nil))
>            if _, ok := err.(I); ok         ->   if errors.HasInterface(err, (*I)(nil))
>            if myErr, ok := err.(*T); ok    ->   if myErr := (*T)(nil); errors.As(err, &myErr)
>            if myErr, ok := err.(I); ok     ->   if myErr := (I)(nil); errors.As(err, &myErr)
>            switch err.(type) { case *T:... ->   switch { case errors.HasType(err, (*T)(nil)): ...
>     --- FAIL: TestLint/TestRoachVet (110.18s)
> ```
> 
> Any idea why?

I specifically added an exception for this to `build/bazelutil/nogo_config.json` in `e024963ace42`, but forgot to make the corresponding change for `make lint` in `pkg/testutils/lint/lint_test.go`. I have addressed this in #100777.

**Pull request merged**
