### PR TITLE
opt, makefile: generate rule_name_string.go automatically

### PR DESCRIPTION
**Pull request by RaduBerinde**
I've been seeing a lot of merge conflicts with this file. It needs to be regenerated every time a rule is added or changed. These commits remove the file from the repo and configure the Makefile to generate this file too.

#### opt: remove rule_name_string.go from git

Release note: None

#### opt: add rule_name_string.go to .gitignore

Release note: None

#### opt, makefile: generate rule_name_string.go automatically

Release note: None

### CODE REVIEW

**Review by benesch — CHANGES_REQUESTED** [review]
Thanks for doing this!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27196#-:-LGb7ylT4Iil4QwIuc1J:bxgavm9)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 1344 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27196#-LGb7bXpC3IPQQiOyRkk:-LGb7bXpC3IPQQiOyRkl:bg26oqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a1f585400e8e9d3313fca828eb7e2ceb5f3e941/Makefile#L1344)):*
> ```Makefile
> 
> pkg/sql/opt/rule_name.og.go: $(optgen-defs) $(optgen-norm-rules) $(optgen-xform-rules) bin/optgen
> 	optgen -out $(@D)/rule_name.og.go rulenames $(optgen-defs) $(optgen-norm-rules) $(optgen-xform-rules)
> ```

While you're here, mind changing `$(@D)/rule_name.og.go` to `$@`? No reason to spell that out. The other rules above it even do it correctly.
___
*[Makefile, line 1347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27196#-LGb7QEX5b2GRCzpVAKQ:-LGb7QEX5b2GRCzpVAKR:bjvmryi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a1f585400e8e9d3313fca828eb7e2ceb5f3e941/Makefile#L1347)):*
> ```Makefile
> 
> pkg/sql/opt/rule_name_string.go: pkg/sql/opt/rule_name.go pkg/sql/opt/rule_name.og.go
> 	stringer -output=pkg/sql/opt/rule_name_string.go -type=RuleName pkg/sql/opt/rule_name.go pkg/sql/opt/rule_name.og.go
> ```

You can use automatic variables here: $@ for the name of the target and $^ for all the prerequisites, separated by spaces. You'll also need to add a dependency on bin/.bootstrap; that's what installs `stringer`.

```
pkg/sql/opt/rule_name_string.go: pkg/sql/opt/rule_name.go pkg/sql/opt/rule_name.og.go bin/.bootstrap
	stringer -output=$@ -type=RuleName $(filter %.go,$^)
```

**Review by benesch — CHANGES_REQUESTED** [review]
Oh, also, please make sure to remove the `go:generate` line from rule_name.go, too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27196#-:-LGb8DcC4timc01Zcqzq:b-dv1f01)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 1347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27196#-LGb7QEX5b2GRCzpVAKQ:-LGb81D8C_vSr1d8Gy9v:bhuiqzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a1f585400e8e9d3313fca828eb7e2ceb5f3e941/Makefile#L1347)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

You can use automatic variables here: $@ for the name of the target and $^ for all the prerequisites, separated by spaces. You'll also need to add a dependency on bin/.bootstrap; that's what installs `stringer`.

```
pkg/sql/opt/rule_name_string.go: pkg/sql/opt/rule_name.go pkg/sql/opt/rule_name.og.go bin/.bootstrap
	stringer -output=$@ -type=RuleName $(filter %.go,$^)
```
</blockquote></details>

By the way, it's a little dangerous to only `stringer` two files in the package like this. Someone could come along and add `RuleName`s to, say, moar_rules.go, and they wouldn't get `stringer`ed. I realize the existing `go:generate` invocation was like this, so fine to leave it.

**Review by RaduBerinde — COMMENTED** [review]
TFTR! Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27196#-:-LGbK0EhEqiJdEI-kkJ3:boopawo)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 1347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27196#-LGb7QEX5b2GRCzpVAKQ:-LGbKSrt1PMQdQVY1dKw:b-mc5t8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a1f585400e8e9d3313fca828eb7e2ceb5f3e941/Makefile#L1347)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

By the way, it's a little dangerous to only `stringer` two files in the package like this. Someone could come along and add `RuleName`s to, say, moar_rules.go, and they wouldn't get `stringer`ed. I realize the existing `go:generate` invocation was like this, so fine to leave it.
</blockquote></details>

Done.

I gave a shot using `$(@D)` instead of the file list which works but it's slower (probably like half a second or so) so I left it as is.

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27196#-:-LGbThGM3ZNsEC6gVjjd:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by RaduBerinde — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27196#-:-LGc-m_eBWd3mLGd0NHX:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
