### PR TITLE
storage: use demotions for replica removal

### PR DESCRIPTION
**Pull request by tbg**
We recently discovered that replica removal (both atomic and simple)
entails a small window during which a leader crashing can cause the raft
group to lose quorum until the leader returns (i.e.  potentially never).

This can happen because the removed node may "disappear" and the
leaseholder may crash before the surviving quorum have learned that
the latest configuration change in their log can be applied (and thus
the new configuration activated, which is how etcd/raft - not vanilla
raft - works). Using the old configuration, quorum in that setting can
not be achieved, effectively rendering the raft group unavailable.

For example,  with nodes n1-n4 and a range initially replicated on n1,
n3, and n4, a rebalance operation that wants to swap n1 for n2 first
transitions into the joint configuration `(n1 n3 n4) && (n2 n3 n4)`,
that is, n2 is VOTER_OUTGOING. After this is committed and applied (say
by everyone), the configuration entry for the final configuration 
`(n2 n3 n4)` is distributed and the following could occur:

- the leader is n3
- conf entry reaches n1, n2, n3 (so it is committed under the joint config)
- n1 applies conf change and immediately disappears (via replicaGC,
- since it's not a part of the latest config)
- n3 crashes

At this point, the remaining replicas n4 and n2 form a quorum of the
latest committed configuration, but both still have the joint
configuration active (and don't know that they can apply the log
entry for the latest config), which cannot reach quorum any more.

@ajwerner pointed out that a "simple" way to avoid this problem is to
demote the voter first, and remove it in a subsequent round of
configuration change (with any new configuration change added to the
log, the previous one is known to the replica to be fine to apply to the
state machine). This is a great idea and it's implemented in this
commit: we add a new cluster version which, if active, goes through a
demotion before removing the resulting learner.

Release note (bug fix): fixed a bug which could result in ranges
becoming unavailable while a single node is unreachable. The
symptoms of this would closely resemble that of a range that
has lost a majority of replicas, i.e. the log files would likely
indicate messages of the form "have been waiting [...] for proposing
command", except that a majority will be available, though not
reflected in the surviving replicas' range status.

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
random drive-by comments/questions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-:-Lt2sFMY-9SfIesF36QS:b-tqp1a8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

___
*[pkg/roachpb/data.go, line 1400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2qJUJ8NdO12P8PnC-:-Lt2qJUJ8NdO12P8PnC0:b-d9cv9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/data.go#L1400)):*
> ```Go
> 		return nil
> 	}
> ```

I don't really understand this function. We seem to have a state (from `Replicas()`) that we will be in, and the `Added()` and `Removed()` replicas that brought us to that state and we are constructing a state transition? That seems backwards, so I must be missing something. 
___
*[pkg/roachpb/data.go, line 1436 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2raO140ATyFGCrJQi:-Lt2raO140ATyFGCrJQj:brl1dnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/data.go#L1436)):*
> ```Go
> 			}
> 		case VOTER_FULL:
> 			// A voter can't be in the descriptor if it's being removed.
> ```

when would a VOTER_FULL be removed in a single state transition?
___
*[pkg/roachpb/metadata.proto, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2i5faD_D-SYba3J0X:-Lt2i5faD_D-SYba3J0Y:b-ui0yqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/metadata.proto#L55)):*
> ```protobuf
> // Thus, {1,2} is a quorum of both, {1,3} is a quorum of the first but not the
> // second, {1,4} is a quorum of the second but not the first, and {3,4} is a
> // quorum of neither.
> ```

can this comment be updated to include VOTER_DEMOTING?

**Review by ajwerner — COMMENTED** [review]
I need to take another pass through the testing in the morning but in my first pass I'm happy with how "simple" this ended up being.

Somewhere (not necessarily now) I'd love a simple visual explanation of the various protocols. The below example tries to express the different states of the range descriptor. Do I understand the protocols correctly?

START({n1/1, n2/2, n3/3}), ADD(n4, n5), REMOVE(n1, n2)

"Simple"/19.1-:
```
{n1/1, n2/2, n3/3}
{n1/1, n2/2, n3/3, n4/4}
{n1/1, n2/2, n3/3, n4/4, n5/5}
{n2/2, n3/3, n4/4, n5/5}
{n3/3, n4/4, n5/5}
```

19.2
```
{n1/1, n2/2, n3/3}
{n1/1, n2/2, n3/3, n4/4LEARNER, n5/5LEARNER}
{n1/1VOTER_OUTGOING, n2/2VOTER_OUTGOING, n3/3, n4/4VOTER_INCOMING, n5/5VOTER_INCOMING}
{n3/3, n4/4, n5/5}
```

This PR
```
{n1/1, n2/2, n3/3}
{n1/1, n2/2, n3/3, n4/4LEARNER, n5/5LEARNER}
{n1/1VOTER_DEMOTING, n2/2VOTER_DEMOTING, n3/3, n4/4VOTER_INCOMING, n5/5VOTER_INCOMING}
{n1/1LEARNER, n2/2LEARNER, n3/3, n4/4, n5/5}
{n2/2LEARNER, n3/3, n4/4, n5/5}
{n3/3, n4/4, n5/5}
```

After https://github.com/cockroachdb/cockroach/pull/40268
```
{n1/1, n2/2, n3/3}
{n1/1, n2/2, n3/3, n4/4LEARNER, n5/5LEARNER}
{n1/1VOTER_DEMOTING, n2/2VOTER_DEMOTING, n3/3, n4/4VOTER_INCOMING, n5/5VOTER_INCOMING}
{n1/1LEARNER, n2/2LEARNER, n3/3, n4/4, n5/5}
{n3/3, n4/4, n5/5}
```

> Reviewed 5 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-:-Lt3IQYcC1LwZV_Q_RKp:b24vyel)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @sumeerbhola, and @tbg)

___
*[pkg/roachpb/data.go, line 1400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2qJUJ8NdO12P8PnC-:-Lt3-dU9D1YCYW9Guv-8:b-bd814l) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/data.go#L1400)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't really understand this function. We seem to have a state (from `Replicas()`) that we will be in, and the `Added()` and `Removed()` replicas that brought us to that state and we are constructing a state transition? That seems backwards, so I must be missing something. 
</blockquote></details>

The semantics on Added(), Removed(), and Replicas() are a bit surprising. When using joint consensus, Removed() does not include the set of replicas which will no longer exist in the descriptor after the transition, it only includes the set moving from VOTER_FULL to VOTER_OUTGOING. In the common case today this means that the set of replicas in `Removed()` are also in `Replicas()` but when a replica is actually being removed from the range it does not appear in `Removed()`. See https://github.com/cockroachdb/cockroach/blob/f8249ec872692a4c5a0268896f2c009e1508cd4f/pkg/storage/replica_application_state_machine.go#L521 for a demonstration of this.

`Removed()` and `Added()` exist somewhat to help with a migration in the format of the `ChangeReplicasTrigger`. Note however that this terminology somewhat to help aid in backwards compatibility. In the 19.1 and prior protocol we'd explicitly provide a replica being removed or added which was always a new replica becoming a VOTER_FULL straight away or a replica being removed directly from being a VOTER_FULL. 

See here for the legacy case: https://github.com/cockroachdb/cockroach/blob/f8249ec872692a4c5a0268896f2c009e1508cd4f/pkg/roachpb/data.go#L1559-L1580
___
*[pkg/roachpb/data.go, line 1436 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2raO140ATyFGCrJQi:-Lt3FmHU255wsvly69yY:bm2nlni) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/data.go#L1436)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

when would a VOTER_FULL be removed in a single state transition?
</blockquote></details>

This happens when dealing with commands created while speaking the 19.1 or prior protocol. We currently have no way to ensure that old commands won't be applied under new versions so we carry backwards compatibility logic forever. It also seems like any time there's a range with an even number of replicas (say 4), the "simple" protocol which just removes one should probably be used. Tobi can speak to when/how this happens. I think we continue to allow clients to add and remove one at a time. 

Here's an issue outlining some of the thoughts about how long-running migrations and eventual deprecation of code which deals with durable state. We'd need to do something like that if we were to deprecate the "simple" protocol entirely. https://github.com/cockroachdb/cockroach/issues/39182

**Review by tbg — COMMENTED** [review]
That's spot on Andrew, except that "This PR" and "19.2" has to add the learners one by one as well.
I used your example to improve the comment on ChangeReplicas.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-:-Lt4drPa7V8K8zlsx5L0:b-3dnvx9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/roachpb/data.go, line 1400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2qJUJ8NdO12P8PnC-:-Lt4gNOUCZEy_8oPKvc3:bsvdzus) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/data.go#L1400)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The semantics on Added(), Removed(), and Replicas() are a bit surprising. When using joint consensus, Removed() does not include the set of replicas which will no longer exist in the descriptor after the transition, it only includes the set moving from VOTER_FULL to VOTER_OUTGOING. In the common case today this means that the set of replicas in `Removed()` are also in `Replicas()` but when a replica is actually being removed from the range it does not appear in `Removed()`. See https://github.com/cockroachdb/cockroach/blob/f8249ec872692a4c5a0268896f2c009e1508cd4f/pkg/storage/replica_application_state_machine.go#L521 for a demonstration of this.

`Removed()` and `Added()` exist somewhat to help with a migration in the format of the `ChangeReplicasTrigger`. Note however that this terminology somewhat to help aid in backwards compatibility. In the 19.1 and prior protocol we'd explicitly provide a replica being removed or added which was always a new replica becoming a VOTER_FULL straight away or a replica being removed directly from being a VOTER_FULL. 

See here for the legacy case: https://github.com/cockroachdb/cockroach/blob/f8249ec872692a4c5a0268896f2c009e1508cd4f/pkg/roachpb/data.go#L1559-L1580
</blockquote></details>

Yep, this is definitely confusing. I'm hesitant to clean this up before we have https://github.com/cockroachdb/cockroach/issues/39182 though, because we'll need to continue supporting the deprecated ChangeReplicasTrigger behavior unfortunately (that's the plight of anything that goes through raft).
___
*[pkg/roachpb/data.go, line 1436 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2raO140ATyFGCrJQi:-Lt4iLX67DoDUgKxZ9mH:b-udzxym) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/data.go#L1436)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This happens when dealing with commands created while speaking the 19.1 or prior protocol. We currently have no way to ensure that old commands won't be applied under new versions so we carry backwards compatibility logic forever. It also seems like any time there's a range with an even number of replicas (say 4), the "simple" protocol which just removes one should probably be used. Tobi can speak to when/how this happens. I think we continue to allow clients to add and remove one at a time. 

Here's an issue outlining some of the thoughts about how long-running migrations and eventual deprecation of code which deals with durable state. We'd need to do something like that if we were to deprecate the "simple" protocol entirely. https://github.com/cockroachdb/cockroach/issues/39182
</blockquote></details>

As of this cluster version, we'll never use the simple protocol when removing replicas (but we do for adding a single replica). Before, we'd automatically use the simple protocol when all that was requested was adding or removing a single node.
___
*[pkg/roachpb/metadata.proto, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2i5faD_D-SYba3J0X:-Lt4j7tP-sb1vLfNu5Mw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/metadata.proto#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can this comment be updated to include VOTER_DEMOTING?
</blockquote></details>

Done.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @sumeerbhola, and @tbg)

___
*[pkg/roachpb/data.go, line 1400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2qJUJ8NdO12P8PnC-:-Lt5M87m8nNK_p-AhPxT:b68jxo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/data.go#L1400)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yep, this is definitely confusing. I'm hesitant to clean this up before we have https://github.com/cockroachdb/cockroach/issues/39182 though, because we'll need to continue supporting the deprecated ChangeReplicasTrigger behavior unfortunately (that's the plight of anything that goes through raft).
</blockquote></details>

Thanks. What I don't understand is the purpose of populating the `ConfChangeSingle` in `sl` -- it models all of the removed cases as `ConfChangeRemoveNode` even though the states the node will be in after this transition are quite different. But for the `VOTER_DEMOTING` case it also adds a `ConfChangeAddLearnerNode` to distinguish it -- I know it will in be in learner after the next state transition but I don't understand the code level artifacts that require us to say that now. 
___
*[pkg/roachpb/data.go, line 1465 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt5NKmx4gUNTCcxrtHr:-Lt5NKmx4gUNTCcxrtHs:b-i2t8rs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9d9105a9d91226d5d3b7af7bf8b75714f46837/pkg/roachpb/data.go#L1465)):*
> ```Go
> 			// A voter is demoting, so it was just removed and re-added in the
> 			// `removals` handler. We should not see it again here.
> 			return nil, errors.Errorf("demoting voter should not be in `added`: %+v", added)
> ```

and this is true for VOTER_OUTGOING too but that falls through to the error returned by the default case?
___
*[pkg/roachpb/data.go, line 1494 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt5NX913jctxjmHdNE1:-Lt5NX9225Jyu0QjNSQT:b-dhmkoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9d9105a9d91226d5d3b7af7bf8b75714f46837/pkg/roachpb/data.go#L1494)):*
> ```Go
> 		}
> 	}
> 	wantLeaveJoint := len(added)+len(removed) == 0
> ```

if nothing is being added or removed, why is this considered a desire to leave the joint config versus just staying in the joint config? Is this because the replica that transitioned from VOTER_OUTGOING to "gone" is not in `removed` (as @ajwerner said in response to my earlier question), so this function is having to guess that fact without knowing it.
___
*[pkg/roachpb/metadata.proto, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt5IFTz9YY9uoOok8TN:-Lt5IFU-CxNI1D32qXMk:b-rvsqtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9d9105a9d91226d5d3b7af7bf8b75714f46837/pkg/roachpb/metadata.proto#L83)):*
> ```protobuf
>   VOTER_DEMOTING = 4;
>   // LEARNER indicates a replica that applies committed entries, but
>   // does not count towards the quorum(s). Learners do not vote for leadership
> ```

could this "do not vote for leadership" comment use some rephrasing given that we are relying on LEARNERs voting if they think they are LEARNERs, but the candidate either still thinks they are in a preceding voting state, or knows they are in a succeeding voting state?

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 11 of 20 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-:-Lt8Lg0PC74mGEkI11xx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

___
*[pkg/roachpb/data.go, line 1400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2qJUJ8NdO12P8PnC-:-Lt8Ere79JDXC61tEbNY:b-4o5w4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/data.go#L1400)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Thanks. What I don't understand is the purpose of populating the `ConfChangeSingle` in `sl` -- it models all of the removed cases as `ConfChangeRemoveNode` even though the states the node will be in after this transition are quite different. But for the `VOTER_DEMOTING` case it also adds a `ConfChangeAddLearnerNode` to distinguish it -- I know it will in be in learner after the next state transition but I don't understand the code level artifacts that require us to say that now. 
</blockquote></details>

I think this relates to the semantics of the joint configuration with etcd/raft. All of these `ConfChangeSingle`s go in one https://godoc.org/go.etcd.io/etcd/raft/raftpb#ConfChangeV2. To move the Replica from voter to learner we need to remove it as a voter and add it as a learner. Both of these happen in the same operation and which comprises the first phase of the joint consensus. 
___
*[pkg/roachpb/data.go, line 1494 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt5NX913jctxjmHdNE1:-Lt8FKbS74zMr32Y8i-Y:b-dnb40s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9d9105a9d91226d5d3b7af7bf8b75714f46837/pkg/roachpb/data.go#L1494)):*
I think there's something implicit going on with the idea that if you're not adding or removing anything but you're in this function at all then the only reason would be because you're in a joint configuration. The code in replica_command.go uses an empty config change to imply leave joint. This maps to the semantics of etcd/raft for the second phase of joint configuration, leaving.

> Leaving the joint configuration is accomplished by proposing a ConfChangeV2 with only and optionally the Context field populated. 


https://godoc.org/go.etcd.io/etcd/raft/raftpb#ConfChangeV2
___
*[pkg/storage/replica_command.go, line 922 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt8J-TRElTpjHiRmHLO:-Lt8J-TRElTpjHiRmHLP:b5cdc84) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9d9105a9d91226d5d3b7af7bf8b75714f46837/pkg/storage/replica_command.go#L922)):*
> ```Go
> //    voters and removes any replicas for which this was requested; voters are
> //    demoted before actually being removed to avoid bug in etcd/raft:
> //    See ttps://github.com/cockroachdb/cockroach/pull/40268.
> ```

missing an `h`

**Review by tbg — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-:-Lt9T6U36Ug-4aiUEJUX:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/roachpb/data.go, line 1400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2qJUJ8NdO12P8PnC-:-Lt9N7K_CqqDXZcx-fxG:bfghnb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/data.go#L1400)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this relates to the semantics of the joint configuration with etcd/raft. All of these `ConfChangeSingle`s go in one https://godoc.org/go.etcd.io/etcd/raft/raftpb#ConfChangeV2. To move the Replica from voter to learner we need to remove it as a voter and add it as a learner. Both of these happen in the same operation and which comprises the first phase of the joint consensus. 
</blockquote></details>

For example, if the config is initially `(1 2 3)` and you start a joint conf state that, for example, removes two nodes, the conf change passed to raft will be `RemoveNode(1) RemoveNode(2)` which puts the raft group in the config `(1) && (1 2 3)`. To decode that in the range descriptor, we keep 1 as voter_full, and 2, 3 as voter_outgoing. If 2 got demoted instead of dropped, the conf change would have an additional `AddLearnerNode(2)` and the config would be `(1) && (1 2 3) LearnersNext=2` and the descriptor would have `2` as `voter_demoting`. I think the main reason this is confusing is because raft's ConfState explicitly has the joint config and the range descriptor only has a flat slice of replicas, and so it needs to communicate the "side" of the joint config (and thus the future type of the replica in the final conf) through states.
___
*[pkg/roachpb/data.go, line 1465 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt5NKmx4gUNTCcxrtHr:-Lt9OGq1CQ7nEGwx-i2C:b-sxkp7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9d9105a9d91226d5d3b7af7bf8b75714f46837/pkg/roachpb/data.go#L1465)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

and this is true for VOTER_OUTGOING too but that falls through to the error returned by the default case?
</blockquote></details>

Good point, I simplified so that demotions also fall through to the default.
___
*[pkg/roachpb/data.go, line 1494 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt5NX913jctxjmHdNE1:-Lt9OLw4-AkgLUW5TH62:bh25qvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9d9105a9d91226d5d3b7af7bf8b75714f46837/pkg/roachpb/data.go#L1494)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think there's something implicit going on with the idea that if you're not adding or removing anything but you're in this function at all then the only reason would be because you're in a joint configuration. The code in replica_command.go uses an empty config change to imply leave joint. This maps to the semantics of etcd/raft for the second phase of joint configuration, leaving.

> Leaving the joint configuration is accomplished by proposing a ConfChangeV2 with only and optionally the Context field populated. 


https://godoc.org/go.etcd.io/etcd/raft/raftpb#ConfChangeV2
</blockquote></details>

Right, by design an empty conf change is just how you leave a joint configuration. We could also have implemented this in raft with a conf change that has some bool set. But an empty  conf change isn't such a bad choice, because when you're leaving a joint config you really have zero data that you're passing in. The joint config already encodes the next config. BTW, an empty conf change will fail outside of a joint config. It's really only used to leave a joint conf.
___
*[pkg/roachpb/metadata.proto, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt5IFTz9YY9uoOok8TN:-Lt9SdNpE4XqOTddLAXq:b-5stkgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a9d9105a9d91226d5d3b7af7bf8b75714f46837/pkg/roachpb/metadata.proto#L83)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

could this "do not vote for leadership" comment use some rephrasing given that we are relying on LEARNERs voting if they think they are LEARNERs, but the candidate either still thinks they are in a preceding voting state, or knows they are in a succeeding voting state? 
</blockquote></details>

Good point, updated:

  // LEARNER indicates a replica that applies committed entries, but does not
  // count towards the quorum(s). Candidates will not ask for (or take into
  // account) votes of (peers they consider) LEARNERs for leadership nor do
  // their acknowledged log entries get taken into account for determining the
  // committed index. At the time of writing, learners in CockroachDB are a
  // short-term transient state: a replica being added and on its way to being a
  // VOTER_{FULL,INCOMING}, or a VOTER_DEMOTING being removed.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42251)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @sumeerbhola)

___
*[pkg/roachpb/data.go, line 1400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-Lt2qJUJ8NdO12P8PnC-:-Lt9TAyzACUBvlrK3Szw:ba5713h) ([raw file](https://github.com/cockroachdb/cockroach/blob/da4d50a2be6a389496cee4dabbfa224689306eb5/pkg/roachpb/data.go#L1400)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

For example, if the config is initially `(1 2 3)` and you start a joint conf state that, for example, removes two nodes, the conf change passed to raft will be `RemoveNode(1) RemoveNode(2)` which puts the raft group in the config `(1) && (1 2 3)`. To decode that in the range descriptor, we keep 1 as voter_full, and 2, 3 as voter_outgoing. If 2 got demoted instead of dropped, the conf change would have an additional `AddLearnerNode(2)` and the config would be `(1) && (1 2 3) LearnersNext=2` and the descriptor would have `2` as `voter_demoting`. I think the main reason this is confusing is because raft's ConfState explicitly has the joint config and the range descriptor only has a flat slice of replicas, and so it needs to communicate the "side" of the joint config (and thus the future type of the replica in the final conf) through states.
</blockquote></details>

(botched the example - it's RemoveNode(2) RemoveNode(3)`).

**Review by sumeerbhola — COMMENTED** [review]
Thanks for the explanations!

> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42251#-:-LtCVovK2AQGl-L9l11D:b-mfdgup)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @sumeerbhola)

**Comment by tbg** [comment]
bors r=ajwerner

TFTRs!

**Pull request merged**
