### PR TITLE
go.mod: bump Pebble to b418e86f4cd4

### PR DESCRIPTION
**Pull request by RaduBerinde**
```
0d4ce49e vfs: clean up Fd functionality
825168d1 Makefile: add lint target
9509bbfa compaction: introduce multilevel compaction heuristic 19fce0ea replay: fix race in WorkloadCollector
51871384 db: minor cleanup in Open
f91ad392 ci: only use latest version of Go
7538d97e db: calculate w-amp when DisableWAL is enabled f6fee311 metamorphic: remove defunct comment
d8d957fa replay: various WorkloadCollector clean up and refactors
4576c9d9 db: support narrow checkpoints
```

Epic: none

Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95704#-:-NMWatGk2bxjkVBmndt8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by rickystewart — APPROVED** [review]

**Review by jbowens — COMMENTED** [review]
```
=== RUN   TestEngineMustExist
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/c5eb8fc8b8e683c19f3c3e4238f64094/logTestEngineMustExist2631251466
    test_log_scope.go:79: use -show-logs to present logs inline
    engine_test.go:531: pebble: database "/artifacts/tmp/_tmp/c5eb8fc8b8e683c19f3c3e4238f64094/TestEngineMustExist549107430" does not exist
    panic.go:522: -- test log scope end --
--- FAIL: TestEngineMustExist (0.01s)
```
maybe we missed something in the recent Open changes?


Also, I think we can nix [this test](https://github.com/cockroachdb/cockroach/blob/778b6fbb15ebc9dfcb519b47b0afdeda9aade3a8/pkg/storage/pebble_test.go#L1200-L1228) after your `Fd` refactor.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95704#-:-NMZXyRv9FKdd78BJEOz:b-vq7wo9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by RaduBerinde — COMMENTED** [review]
TFTR! Fixed, it was just the exact text in the error message that changed. And removed that test, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95704#-:-NMZetqWDEm8SDFwDQyL:bfx6j5v)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal)

**Pull request merged**
