### PR TITLE
storage: Send raftlogger panics to Sentry, wrap numbers as safe.

### LINKED ISSUE #25333: storage: report more information from raftlogger panics
See https://github.com/cockroachdb/cockroach/issues/25217.

### PR DESCRIPTION
**Pull request by giorgosp**
Closes #25333

Release note: None

### CODE REVIEW

**Comment by giorgosp** [comment]
@tbg is there a way to test these changes?

**Review by tbg — APPROVED** [review]
Thanks @giorgosp!

I'd set up a test that calls `log.ReportablesToSafeError` on the result of `wrapNumbersAreSafe` and verifies that it matches the expectation. For example, `ReportablesToSafeError("foo %d bar %s %d", uint64(5), "baz", float32(1.2))` should return an error that contains the 5 and 1.2 but not the "baz". (You probably want to throw all numeric types into the example).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-:-Lcz3qTh4BMyRPL3yY7q:b-3d0qn1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @giorgosp and @tbg)

___
*[pkg/storage/raft.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-Lcz3C8j9ke9ozku24GQ:-Lcz3C8j9ke9ozku24GR:b-t69n5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e0c3b1f048a4ca61b734d2392ec4e3a671edce5/pkg/storage/raft.go#L79)):*
> ```Go
> 
> func (r *raftLogger) Warning(v ...interface{}) {
> 	wrapNumbersAsSafe(v)
> ```

You only need this call in `{Panic,Fatal}{,f}`
___
*[pkg/storage/raft.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-Lcz3HsAABGzRqeOWHKA:-Lcz3HsAABGzRqeOWHKB:b-38a8bv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e0c3b1f048a4ca61b734d2392ec4e3a671edce5/pkg/storage/raft.go#L112)):*
> ```Go
> 	s := fmt.Sprint(v...)
> 	log.FatalfDepth(r.ctx, 1, s)
> 	panic(s)
> ```

Remove this line here and below.
___
*[pkg/storage/raft.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-Lcz3JucErMz3TYRPRW6:-Lcz3JucErMz3TYRPRW7:bfjgg8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e0c3b1f048a4ca61b734d2392ec4e3a671edce5/pkg/storage/raft.go#L134)):*
> ```Go
> 		case int32:
> 		case int64:
> 		case float32:
> ```

These don't fallthrough, i.e. as the code is written you'd only do stuff for `float64`. You need to put this line into each individual case (I don't think you get to use `fallthrough` since this is a type switch).

**Review by tbg — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @giorgosp)

**Review by giorgosp — COMMENTED** [review]
Thank you for taking the time to review!

In an effort to not directly use the internal func `wrapNumbersAsSafe` in tests, I found out about `ScopeWithoutShowLogs`. Seems like I can use it to create a test-scoped log output and then call the public log methods {Panic,Fatal}{,f}  from raft.go. I would also have to make sure that logs are not sent to Sentry during tests. Would this approach make sense?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-:-Ld-EK9i1OifDQgixF0O:b-bjn692)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/raft.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-Lcz3C8j9ke9ozku24GQ:-Ld-JkTh7knichG0-1wB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e0c3b1f048a4ca61b734d2392ec4e3a671edce5/pkg/storage/raft.go#L79)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

You only need this call in `{Panic,Fatal}{,f}`
</blockquote></details>

Done.
___
*[pkg/storage/raft.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-Lcz3HsAABGzRqeOWHKA:-LczGbdl5cDj5b8bdPQ3:bei0lp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e0c3b1f048a4ca61b734d2392ec4e3a671edce5/pkg/storage/raft.go#L112)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Remove this line here and below.
</blockquote></details>

Ok, but isn't raft (the caller) expecting a panic here?
___
*[pkg/storage/raft.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-Lcz3JucErMz3TYRPRW6:-Ld-KKK7-iBpkRUbtEF6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e0c3b1f048a4ca61b734d2392ec4e3a671edce5/pkg/storage/raft.go#L134)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

These don't fallthrough, i.e. as the code is written you'd only do stuff for `float64`. You need to put this line into each individual case (I don't think you get to use `fallthrough` since this is a type switch).
</blockquote></details>

Done.

**Review by tbg — COMMENTED** [review]
There's nothing wrong with calling `wrapNumbersAsSafe` in a unit test (internal methods need tests too!). Above that, all you're achieving with "higher-level" test coverage is making sure that we are calling it in the right place. This is clearly true now, and so the remaining worry is that we might lose it in some future refactor, which in this area of the code is highly unlikely (and if it happens, it's not a big deal). 
If you want reasonable end-to-end coverage, let `*raftLogger` embed a `fatalFunc` (i.e. a func to use instead of `log.Fatal`) which defaults to `log.Fatal` and then override it in your test to something that captures the args passed to it. (That way you can test that you actually call `wrapNumbersAreSafe` in the right place, and you can test that method directly enough to not have to worry about a separate unit test for it, but you should still do that `ReportablesToSafeError` thing above and that would be the thing you're verifying).
There's definitely no need to pull in the actual error reporting code, after all that is already tested and you don't need to verify again (and from a distance) that it works.

I think the code looks good now, let's see if the tests agree :-)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-:-Ld08ZBq4yJDpSM0Q8XC:bnr9fz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @giorgosp and @tbg)

___
*[pkg/storage/raft.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-Lcz3HsAABGzRqeOWHKA:-Ld08H2o1wTkxLfmpYVJ:bzgh8jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e0c3b1f048a4ca61b734d2392ec4e3a671edce5/pkg/storage/raft.go#L112)):*
<details><summary><i>Previously, giorgosp (George Papadrosou) wrote…</i></summary><blockquote>

Ok, but isn't raft (the caller) expecting a panic here?
</blockquote></details>

No, it's asking us to panic, but we're choosing to treat this as a fatal (non-recoverable) error. A call to `log.Fatal*` will never return, so the panic will never be called (outside of tests, where you can set up Fatal to not actually exit, but that's not something I recommend you do).

**Review by giorgosp — COMMENTED** [review]
Ok thanks! I just tested `wrapNumbersAsSafe` through `ReportablesToSafeError`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-:-LdDTFM6C5gpImO2swtP:b-um9h62)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/raft.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-Lcz3HsAABGzRqeOWHKA:-LdDTPAeDSN54-WAh8HU:bauijm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e0c3b1f048a4ca61b734d2392ec4e3a671edce5/pkg/storage/raft.go#L112)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

No, it's asking us to panic, but we're choosing to treat this as a fatal (non-recoverable) error. A call to `log.Fatal*` will never return, so the panic will never be called (outside of tests, where you can set up Fatal to not actually exit, but that's not something I recommend you do).
</blockquote></details>

Right, I forgot `log.Fatal` doesn't return. Done, thanks!
___
*[pkg/storage/raft.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-LdF-JCh-CeXr3IGHjlP:-LdF-JCh-CeXr3IGHjlQ:b-nldtes) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b3a1216e3a387aad900e70fde65b97b0fa17a8c/pkg/storage/raft.go#L91)):*
> ```Go
> 
> func (r *raftLogger) Fatal(v ...interface{}) {
> 	log.FatalfDepth(r.ctx, 1, "", v...)
> ```

Btw the above will redact all strings so the final message will probably be difficult to understand. The implementation is same with `raftLogger.Panic` now.

**Review by tbg — COMMENTED** [review]
Almost there!

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-:-LdF6WM9BAjgtURtlTVR:b-debr86)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @giorgosp)

___
*[pkg/storage/raft.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-LdF-JCh-CeXr3IGHjlP:-LdF4hgL0Yzgg4Lq1B2O:bo41r31) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b3a1216e3a387aad900e70fde65b97b0fa17a8c/pkg/storage/raft.go#L91)):*
<details><summary><i>Previously, giorgosp (George Papadrosou) wrote…</i></summary><blockquote>

Btw the above will redact all strings so the final message will probably be difficult to understand. The implementation is same with `raftLogger.Panic` now.
</blockquote></details>

Good point. Why did you have to make a change here? I think this is strictly worse than before because now `log.FatalfDepth` doesn't even get to see the args any more (it sees the final string `s` as its only arg, which gets fully redacted). I would update `Panic` and `Fatal` to both call `FatalfDepth(r.ctx, 1, "", v...)` as before. Is there a problem I'm missing?
___
*[pkg/storage/raft_test.go, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-LdF5BNJA-cjtqYZ314-:-LdF5BNKA58oPgjd4I3V:bb6ht2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/646ac701374405833b4c71c9a4630105da17b58b/pkg/storage/raft_test.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

2019
___
*[pkg/storage/raft_test.go, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-LdF6JtrDsf4vhf1RVyk:-LdF6JtrDsf4vhf1RVyl:b-jcavpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/646ac701374405833b4c71c9a4630105da17b58b/pkg/storage/raft_test.go#L28)):*
> ```Go
> 
> // TestWrapNumbersAsSafe tests the wrapNumbersAsSafe through ReportablesToSafeError.
> func TestWrapNumbersAsSafe(t *testing.T) {
> ```

You probably need a `defer leaktest.AfterTest(t)()` as the first thing in this test to satisfy the linters. (That thing checks for leaked goroutines).

**Review by giorgosp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/raft.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-LdF-JCh-CeXr3IGHjlP:-LdF76zWDeekMRoKscG1:by4pdin) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b3a1216e3a387aad900e70fde65b97b0fa17a8c/pkg/storage/raft.go#L91)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Good point. Why did you have to make a change here? I think this is strictly worse than before because now `log.FatalfDepth` doesn't even get to see the args any more (it sees the final string `s` as its only arg, which gets fully redacted). I would update `Panic` and `Fatal` to both call `FatalfDepth(r.ctx, 1, "", v...)` as before. Is there a problem I'm missing?
</blockquote></details>

Initially I had the same thought (and even commited it) but then I thought that `FatalfDepth(r.ctx, 1, "", v...)` will redact all the string parameters and may render the message useless. For example, 
`raft.Fatal("error with safe arg:", 123)` will later call `ReportablesToSafeError(1, "", []interface{}{"error with safe arg", 123})` which will just print 1string; "123"1 and the string that gives context to the error will be redacted.
___
*[pkg/storage/raft_test.go, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-LdF5BNJA-cjtqYZ314-:-LdFA2Xs3Swi3GpgF0hd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/646ac701374405833b4c71c9a4630105da17b58b/pkg/storage/raft_test.go#L1)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

2019
</blockquote></details>

Done.
___
*[pkg/storage/raft_test.go, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-LdF6JtrDsf4vhf1RVyk:-LdFATKQ06M7tQMLGIZA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/646ac701374405833b4c71c9a4630105da17b58b/pkg/storage/raft_test.go#L28)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

You probably need a `defer leaktest.AfterTest(t)()` as the first thing in this test to satisfy the linters. (That thing checks for leaked goroutines).
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @giorgosp)

___
*[pkg/storage/raft.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-LdF-JCh-CeXr3IGHjlP:-LdFX-Xd9M7S-t7rAa0_:b-ysgnrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b3a1216e3a387aad900e70fde65b97b0fa17a8c/pkg/storage/raft.go#L91)):*
<details><summary><i>Previously, giorgosp (George Papadrosou) wrote…</i></summary><blockquote>

Initially I had the same thought (and even commited it) but then I thought that `FatalfDepth(r.ctx, 1, "", v...)` will redact all the string parameters and may render the message useless. For example, 
`raft.Fatal("error with safe arg:", 123)` will later call `ReportablesToSafeError(1, "", []interface{}{"error with safe arg", 123})` which will just print 1string; "123"1 and the string that gives context to the error will be redacted.
</blockquote></details>

Yes, that's not ideal, but consider what happens now: you only get `<redacted>`, don't you? The other behavior is better - it loses something, but not everything. Also consider that fatal errors give you a stack trace, so we'll know where the error was generated and we will find the string there. This is what we do today already; it's just the variables that we can't reconstruct (because they're not hard-coded in the source code). The vars are always almost ints.

**Review by giorgosp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/raft.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-LdF-JCh-CeXr3IGHjlP:-LdFZAnR1F12gi6hi6lr:bboepg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b3a1216e3a387aad900e70fde65b97b0fa17a8c/pkg/storage/raft.go#L91)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yes, that's not ideal, but consider what happens now: you only get `<redacted>`, don't you? The other behavior is better - it loses something, but not everything. Also consider that fatal errors give you a stack trace, so we'll know where the error was generated and we will find the string there. This is what we do today already; it's just the variables that we can't reconstruct (because they're not hard-coded in the source code). The vars are always almost ints.
</blockquote></details>

I see. Done!

**Review by tbg — APPROVED** [review]
:lgtm: you're good to go! To celebrate (and merge), comment "bors r=tbg" on this PR. Up for more? Send me an email at tobias@cockroachlabs.com and I'll get back to you with something soon.

Thanks again, this is really useful! See for example https://github.com/cockroachdb/cockroach/issues/32927, https://github.com/cockroachdb/cockroach/issues/36522, https://github.com/cockroachdb/cockroach/issues/36567, https://github.com/cockroachdb/cockroach/issues/36592 for issues that will have better information with your code.

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-:-LdF_VQl9Lw4Olc8XRBy:bx82v6g)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by giorgosp** [comment]
Nice thank you!

bors r=tbg

**Comment by giorgosp** [comment]
Oops. I 'll celebrate even if I don't merge it myself though :)

**Review by tbg — APPROVED** [review]
Well, it might work next time around, but now I want to have this code in:

bors r+

:pray: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36976#-:-LdFfuNbAJL31YuWh773:b-7z6cfl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
