### PR TITLE
sql: omit dropped columns from SHOW STATISTICS output

### LINKED ISSUE #76573: Remove 'unknown' columns from statement bundles
**Describe the problem**

If a column has been dropped and a statement bundle is created, the statistics inside the statement bundle will have references to 'unknown' columns:

```
    {
        "columns": [
            "\u003cunknown\u003e"
        ],
        "created_at": "2022-02-03 19:00:27.54292",
        "distinct_count": 6241,
        "histo_buckets": [
            {
                "distinct_range": 0,
                "num_eq": 1,
                "num_range": 0,
                "upper_bound": "690999344562995201"
            },
            {
                "distinct_range": 4272,
                "num_eq": 1,
                "num_range": 4261,
                "upper_bound": "700567439108505602"
            }
        ],
        "histo_col_type": "INT8",
        "name": "__auto__",
        "null_count": 0,
        "row_count": 4263
    },
```

**To Reproduce**

Have a table with statistics, remove a column, create a statement bundle, attempt to inject those statistics in to a test cluster.

**Expected behavior**
Unknown columns should not be exported into the statistics of a statement bundle.  I had considered also requesting that `INJECT STATISTICS...` actively ignore columns called `unknown`, but users might genuinely call a column that so it's fine to manually remove these columns from older statistics bundles but have the columns removed from newer versions of CockroachDB.

### PR DESCRIPTION
**Pull request by msirek**
Fixes #76573

Previously, statistics on dropped columns were displayed in `SHOW
STATISTICS [USING JSON]` output.

This was inadequate because statement bundle scripts with
`ALTER TABLE ... INJECT STATISTICS` statements, generated via
`SHOW STATISTICS USING JSON` output, required manual editing
in order to run successfully if the table in question had a dropped
column.

To address this, this patch omits printing of statistics involving
dropped columns in `SHOW STATISTICS` output, including multicolumn
statistics.

Release note (bug fix): This fixes SHOW STATISTICS output so statistics
involving dropped columns are not displayed.

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
Nice! Just a small nit, otherwise :lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82190#-:-N3SlsUf1hoEP4UXzSFW:b9qwcqi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @rharding6373)

___
*[`pkg/sql/show_stats.go` line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82190#-N3SlS392Or4ykuHn_eg:-N3SlS392Or4ykuHn_eh:b-ivksqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f71ba004c93204e63ec5988829e81ad38a38c9/pkg/sql/show_stats.go#L272)):*
> ```Go
> 	if err != nil {
> 		// This can happen if a column was removed.
> 		return "<unknown>"
> ```

nit: Instead of adding two calls to `desc.FindColumnWithID(id)` above, could we change this `statColumnString` function to return an error instead of returning `"<unknown>"`? Then we could check for that error in both places we call this function.



_Code quote:_
```Go
		// This can happen if a column was removed.
		return "<unknown>"
```

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82190)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @rharding6373)

___
*[`pkg/sql/show_stats.go` line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82190#-N3SlS392Or4ykuHn_eg:-N3UVh7i4ER4UnCYS9iM:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f71ba004c93204e63ec5988829e81ad38a38c9/pkg/sql/show_stats.go#L272)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Instead of adding two calls to `desc.FindColumnWithID(id)` above, could we change this `statColumnString` function to return an error instead of returning `"<unknown>"`? Then we could check for that error in both places we call this function.
</blockquote></details>

Done

**Review by rharding6373 — COMMENTED** [review]
:lgtm: with some minor nits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82190#-:-N3V5lH7EeIOkBrmn5sJ:bmq2v8o)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @msirek)

___
*[`pkg/sql/show_stats.go` line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82190#-N3V3mASExt6vO1rnqF1:-N3V3mASExt6vO1rnqF2:bbeq5q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2426850e54e1f081541e9816f489e5a90b51d4b3/pkg/sql/show_stats.go#L171)):*
> ```Go
> 					colIDs := r[columnIDsIdx].(*tree.DArray).Array
> 					statsRow.Columns = make([]string, len(colIDs))
> 					ignoreStatsRowWithDroppedColumn := false
> ```

nit: Since we may skip the rest of this iteration, consider moving the chunk of code that sets/checks `ignoreStatsRowWithDroppedColumn` to the top of the outer loop to avoid wasting the work filling out `statsRow` above.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 1597 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82190#-N3V4wHx1xtjzYMmIKfD:-N3V4wHx1xtjzYMmIKfE:b-y019u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2426850e54e1f081541e9816f489e5a90b51d4b3/pkg/sql/logictest/testdata/logic_test/distsql_stats#L1597)):*
> ```
> query TTIIIB colnames
> SELECT
> 	statistics_name,
> ```

nit: it looks like there's a tab here that should ideally be formatted as spaces.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82190)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2 and @rharding6373)

___
*[`pkg/sql/show_stats.go` line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82190#-N3V3mASExt6vO1rnqF1:-N3V841u5ip5Yh0tbdcV:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2426850e54e1f081541e9816f489e5a90b51d4b3/pkg/sql/show_stats.go#L171)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: Since we may skip the rest of this iteration, consider moving the chunk of code that sets/checks `ignoreStatsRowWithDroppedColumn` to the top of the outer loop to avoid wasting the work filling out `statsRow` above.
</blockquote></details>

Done
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 1597 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82190#-N3V4wHx1xtjzYMmIKfD:-N3V82kk6JGezqMM1vIq:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2426850e54e1f081541e9816f489e5a90b51d4b3/pkg/sql/logictest/testdata/logic_test/distsql_stats#L1597)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: it looks like there's a tab here that should ideally be formatted as spaces.
</blockquote></details>

Fixed

**Review by msirek — COMMENTED** [review]
TFTRs!
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82190#-:-N3VPvJ9BZzC1JJ87hAj:bg1822s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2 and @rharding6373)

**Comment by mgartner** [comment]
https://github.com/cockroachdb/cockroach/pull/78997 was backported to 21.2, so maybe there's no need to backport this PR to 21.2 too.

**Pull request merged**
