### PR TITLE
roachprod: introduce --skip-init to `roachprod start`

### PR DESCRIPTION
**Pull request by irfansharif**
..and `roachprod init`. I attempted to originally introduce this flag in
\#51329, and ultimately abandoned it. I still think it's a good idea to
have such a thing, especially given now we're writing integration tests
that want to control `init` behaviour. It's much easier to write them
with this --skip-init flag than it is to work around roachprod's magical
auto-init behavior.

To do what's skipped when using --skip-init, we introduce a `roachprod
init` sub command.

Release note: None

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53113#-:-MFBEPTc4QVrNHi_f7QP:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @irfansharif, and @nvanbenschoten)

___
*[pkg/cmd/roachprod/main.go, line 1046 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53113#-MFBDs6-3xaHG-Xnntl1:-MFBDs605diHp61MX7om:bjb7t4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d11548c975ec05c26cafff430f92c8d93f59e0/pkg/cmd/roachprod/main.go#L1046)):*
> ```Go
> The "init" command bootstraps the cluster (using "cockroach init"). It also sets
> default cluster settings. It's intended to be used in conjunction with
> 'roachprod start --skip-init'.
> ```

nit: spell out even more that `roachprod start` by defaults inits
___
*[pkg/cmd/roachprod/install/cockroach.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53113#-MFBECb29uRsoH1Qt0ix:-MFBECb29uRsoH1Qt0iy:b-le7abn) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d11548c975ec05c26cafff430f92c8d93f59e0/pkg/cmd/roachprod/install/cockroach.go#L168)):*
> ```Go
> 		if shouldInit {
> 			fmt.Printf("%s: initializing cluster\n", h.c.Name)
> 			initOut, err := h.initializeCluster(nodeIdx)
> ```

can't we make this guy call `Init()`?

**Review by irfansharif — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53113#-:-MFBO8519Qxmo1VHM1GV:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/cmd/roachprod/main.go, line 1046 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53113#-MFBDs6-3xaHG-Xnntl1:-MFBNXB84lehKfK0Sqdp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d11548c975ec05c26cafff430f92c8d93f59e0/pkg/cmd/roachprod/main.go#L1046)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: spell out even more that `roachprod start` by defaults inits
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/install/cockroach.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53113#-MFBECb29uRsoH1Qt0ix:-MFBNYC84pHTIj2NcuCB:b-huqc8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/56d11548c975ec05c26cafff430f92c8d93f59e0/pkg/cmd/roachprod/install/cockroach.go#L168)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can't we make this guy call `Init()`?
</blockquote></details>

Yea, but the workhorse is pretty much within `initializeCluster`; everything else is error handling + printing output. And I didn't want to tie initialization and setting cluster settings into its own wrapper because reasons.

**Comment by irfansharif** [comment]
Huh, I thought we changed bors to go back to the old behavior.

bors r+

**Comment by irfansharif** [comment]
Example-ORM failures look unrelated, and seems like @taroface has been seeing them too. Re-running.

**Comment by irfansharif** [comment]
+cc @knz this may be of passing interest to you (or maybe not).

**Pull request merged**
