### PR TITLE
ui: adds a spinner that appears when there's no graph data

### PR DESCRIPTION
**Pull request by maxlang**
NOTE: the spinner freezes while the graph is rendering.

spinner

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12711)

### CODE REVIEW

**Comment by maxlang** [comment]
cc @kuanluo

**Comment by kuanluo** [comment]
LGTM. Thanks!

**Comment by kuanluo** [comment]
I have a question, actually - why does the spinner freeze when the graph is rendering?

**Comment by maxlang** [comment]
@kuanluo The UI is single threaded so while it's rendering the graphs it can't stop to render the gifs. Fixing it might not be straightforward.

**Comment by kuanluo** [comment]
@maxlang 

Gotcha. We can re-investigate if that becomes an issue with engineers. Thank you!

**Pull request merged**
