### PR TITLE
storage: replace remote proposal tracking with uncommitted log size protection

### LINKED ISSUE #30064: teamcity: failed test: bank/node-restart
The following tests appear to have failed:

[#897838](https://teamcity.cockroachdb.com/viewLog.html?buildId=897838):

```
--- FAIL: roachtest/acceptance/bank/node-restart (32.231s)
	test.go:503,bank.go:291,bank.go:398,acceptance.go:59: stall detected at round 1, no forward progress for 30s

--- FAIL: roachtest/acceptance/bank/node-restart (32.231s)
	test.go:503,bank.go:291,bank.go:398,acceptance.go:59: stall detected at round 1, no forward progress for 30s


```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by nvb**
Closes https://github.com/cockroachdb/cockroach/issues/30064.

This change reverts most of the non-testing code from 03b116f and f2f3fd2
and replaces it with use of the MaxUncommittedEntriesSize config. This
configuration was added in etcd-io/etcd#10167 and provides protection against
unbounded Raft log growth when a Raft group stops being able to commit
entries. It makes proposals into Raft safer because proposers don't need
to verify before the fact that the proposal isn't a duplicate that might
be blowing up the size of the Raft group.

By default, the configuration is set to double the Replica's proposal quota.
The logic here is that the quotaPool should be responsible for throttling
proposals in all cases except for unbounded Raft re-proposals because it
queues efficiently instead of dropping proposals on the floor indiscriminately.

Release note (bug fix): Fix a bug where Raft proposals could get
stuck if forwarded to a leader who could not itself append a new
entry to its log.

This will be backported, but not to 2.1.0. The plan is to get it into 2.1.1.

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31408)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/storagepb/state.proto, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31408#-LOxgRVzDWOZW8bZM4vZ:-LOxgRVzDWOZW8bZM4v_:btziolx) ([raw file](https://github.com/cockroachdb/cockroach/blob/396077240ff8bbae6c4327ae78e66d6a4e789d2a/pkg/storage/storagepb/state.proto#L93)):*
> ```protobuf
>   uint64 last_index = 2;
>   uint64 num_pending = 3;
>   uint64 num_remote_pending = 9;
> ```

Add `reserved 9`.

**Review by tbg — APPROVED** [review]
:lgtm:

curious whether etcd-io/etcd#10063 will break something.

> Reviewed 2 of 2 files at r1, 11 of 11 files at r2, 8 of 8 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31408#-:-LP0NNg5AcSV4CwjxSD_:bc0mkua)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/base/config.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31408#-LP0LeBb4usaDhGXDl1e:-LP0LeBb4usaDhGXDl1f:b-vhzzra) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4003e160982cb3f3f31eaedb15b80a87d163a48/pkg/base/config.go#L101)):*
> ```Go
> 	// defaultRaftLogMaxSize specifies the upper bound that a single Range's
> 	// Raft log is limited to.
> 	defaultRaftLogMaxSize = envutil.EnvOrDefaultInt64(
> ```

Consider renaming so that it's obvious that it's the threshold after which truncation is preferred over letting the Raft log grow further due to straggler followers. Perhaps `RaftLogForceTruncationThreshold`?.
___
*[pkg/base/config.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31408#-LP0LPKX6AAEdT2hrWIA:-LP0LPKX6AAEdT2hrWIB:b-3m8cct) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4003e160982cb3f3f31eaedb15b80a87d163a48/pkg/base/config.go#L107)):*
> ```Go
> 	// that a leader will send to followers in a single MsgApp.
> 	defaultRaftMaxSizePerMsg = envutil.EnvOrDefaultInt(
> 		"COCKROACH_RAFT_MAX_SIZE_PER_MSG", 16*1024)
> ```

/* 16 kb */
___
*[pkg/base/config.go, line 496 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31408#-LP0MH_C2qloqxS2fUSm:-LP0MH_C2qloqxS2fUSn:b-kb08si) ([raw file](https://github.com/cockroachdb/cockroach/blob/58413cb2bc08441c534e0e8d18dd93759e41352d/pkg/base/config.go#L496)):*
> ```Go
> 	if cfg.RaftProposalQuota == 0 {
> 		// By default, set this to a fraction of RaftLogMaxSize. See comment
> 		// above for the tradeoffs of setting this higher or lower.
> ```

"See comment above" -> "See the comment on the field."

**Review by vilterp — APPROVED** [review]
LGTM for UI stuff

**Review by nvb — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31408#-:-LP2P4un4XONSA6e7DQF:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/base/config.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31408#-LP0LeBb4usaDhGXDl1e:-LP2NdrE49dbLU0nBtGC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4003e160982cb3f3f31eaedb15b80a87d163a48/pkg/base/config.go#L101)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Consider renaming so that it's obvious that it's the threshold after which truncation is preferred over letting the Raft log grow further due to straggler followers. Perhaps `RaftLogForceTruncationThreshold`?.
</blockquote></details>

Done.
___
*[pkg/base/config.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31408#-LP0LPKX6AAEdT2hrWIA:-LP2NizX1kjZPV1e15-M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4003e160982cb3f3f31eaedb15b80a87d163a48/pkg/base/config.go#L107)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

/* 16 kb */
</blockquote></details>

Done.
___
*[pkg/base/config.go, line 496 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31408#-LP0MH_C2qloqxS2fUSm:-LP2P2Se2Ut7X2YmVTj-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58413cb2bc08441c534e0e8d18dd93759e41352d/pkg/base/config.go#L496)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

"See comment above" -> "See the comment on the field."
</blockquote></details>

Done.
___
*[pkg/storage/storagepb/state.proto, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31408#-LOxgRVzDWOZW8bZM4vZ:-LP2Q2Mn6aLGs3aQ_fK4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/396077240ff8bbae6c4327ae78e66d6a4e789d2a/pkg/storage/storagepb/state.proto#L93)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add `reserved 9`. 
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
@bdarnell @tbg how do we feel about backporting this to 2.1 and 2.0 now? It fixes some Raft stalls that we know are currently possible.

**Pull request merged**
