### PR TITLE
c-deps: bump rocksdb for fallocate build flag fix

### PR DESCRIPTION
**Pull request by ajkr**
Pick up change to enable `fallocate` even on machines where
hole-punching is unsupported, which includes our release build.

Release note: None

### CODE REVIEW

**Comment by ajkr** [comment]
- upstream commit with more detailed message: https://github.com/cockroachdb/rocksdb/commit/b238986bba8cc0d7c14e7b18956f2ddcd010e082
- up-upstream PR: https://github.com/facebook/rocksdb/pull/5023

**Comment by petermattis** [comment]
LGTM. Note that the cockroachdb/rocksdb has a crl-release-5.17.2 branch which we use for our mini fork. I’m on mobile now so it’s hard for me to check that you updated that correctly.

**Comment by ajkr** [comment]
I'm following this doc (https://github.com/cockroachdb/rocksdb/blob/master/README.md), and pushing to that branch is up next (step 7).

**Comment by petermattis** [comment]
> I'm following this doc (https://github.com/cockroachdb/rocksdb/blob/master/README.md), and pushing to that branch is up next (step 7)

Ok. We should update that as recently we've moved to opening PRs that merge into the crl-release branch and then merging those before bumping the pointer. Your current approach is fine for this PR, though.

**Review by petermattis — APPROVED** [review]

**Pull request merged**
