### PR TITLE
sql: fix formatting of import, backup and create tenant

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Informs: #99185

This commit cherry-picked changes from #107723 and add fixes for formatting `EXPORT` and `CHANGEFEED` options.

Release note: None

### CODE REVIEW

**Comment by chengxiong-ruan** [comment]
@knz may I also have a review on this PR? Thanks!

**Review by knz — APPROVED** [review]
I would like to question the wisdom of fixing the bugs on the release branch before the master branch, but that's a separate discussion. For now :lgtm: here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107892#-:-Nalor6T-er25quSsI68:b3i8jx9)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by chengxiong-ruan** [comment]
> I would like to question the wisdom of fixing the bugs on the release branch before the master branch, but that's a separate discussion

Good question! The reasoning behind is that I doubted the "backportability" from the beginning when looking for fixes for the test failure for 22.2. I started looking at issues for older version because I thought some syntaxes has been fixed in newer versions and a backport of fix for newer version won't fix it in older versions. It's true for 22.2. But funny that failures in master branch turned out to be a superset of 23.1, I overlooked that for sure :(

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
