### PR TITLE
testutils/testcluster: add TestCluster.RemoveReplica

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7858)

### CODE REVIEW

**Comment by petermattis** [comment]
@tschottdorf This one is for you! The test fails every time with an error like:

```
	testcluster_test.go:169: change replicas of range 1 failed: storage/store.go:1938: rejecting command with timestamp in the future: 1468630707580614897 (3.044092547s ahead)
```

If you comment out the `TransferRangeLease` then the test succeeds.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[testutils/testcluster/testcluster.go, line 344 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMlWt-0C5z_sK11yMbZ:-KMlWt-0C5z_sK11yMb_:-900552588) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster.go#L344)):*
> ```Go
> 	// not.
> 	if err := tc.Servers[0].DB().GetProto(
> 		keys.RangeDescriptorKey(startKey), rangeDesc); err != nil {
> ```

method comments should indicate that this mutates the argument

---

*[testutils/testcluster/testcluster_test.go, line 172 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMlWbrW5mbYhhrB0AfQ:-KMlWbrW5mbYhhrB0AfR:-183757836) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster_test.go#L172)):*
> ```Go
> 	}
> 	if len(desc.Replicas) != 2 {
> 		t.Fatalf("expected 3 replicas, got %+v", desc.Replicas)
> ```

s/3/2/. better yet, give it a name and %d it in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-:-KMlXByXvL5FFtDhY9jm:1417088721)*

**Comment by andreimatei** [comment]
:lgtm_strong: 

Nice, I was just adding the same.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[testutils/testcluster/testcluster.go, line 334 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMn5riV5MHfg244-5bl:-KMn5riV5MHfg244-5bm:303700416) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster.go#L334)):*
> ```Go
> // RemoveReplica removes a replica from a range.
> func (tc *TestCluster) RemoveReplica(
> 	rangeDesc *roachpb.RangeDescriptor, target ReplicationTarget,
> ```

change to RemoveReplica*s* (plural) to match `AddReplicas`.

---

*[testutils/testcluster/testcluster.go, line 344 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMn5zhZz6ybGCQ86KqM:-KMn5zhZz6ybGCQ86KqN:-505479580) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster.go#L344)):*
> ```Go
> 	// not.
> 	if err := tc.Servers[0].DB().GetProto(
> 		keys.RangeDescriptorKey(startKey), rangeDesc); err != nil {
> ```

if you keep this method taking a single target, I don't think we need the read in the beginning. You should rely on the caller to give you an up-to-date descriptor.

---

*[testutils/testcluster/testcluster.go, line 344 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMlWt-0C5z_sK11yMbZ:-KMn6MSNHKNd9bHda3Bk:-2025508795) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster.go#L344)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> method comments should indicate that this mutates the argument
</details>
yeah, maybe both this and AddReplicas shouldn't mutate the arg, for tests' conveniance

---

*[testutils/testcluster/testcluster.go, line 348 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMn5HtS8ESrRfh9oZe3:-KMn5HtS8ESrRfh9oZe4:-897573373) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster.go#L348)):*
> ```Go
> 	}
> 
> 	// Ask a random replica of the range to up-replicate.
> ```

down-replicate

---

*[testutils/testcluster/testcluster_test.go, line 163 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMn6WobNeKECENtUAdq:-KMn6WobNeKECENtUAdr:-255607731) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster_test.go#L163)):*
> ```Go
> 	}
> 
> 	if err := tc.TransferRangeLease(desc, tc.Target(1)); err != nil {
> ```

once we figure out why the test fails, there's no reason for this transfer, right? In fact, even better to test removing the leader.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-:-KMn6l51H2U7GkpYTsl1:-263619428)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[testutils/testcluster/testcluster_test.go, line 163 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMn6WobNeKECENtUAdq:-KMnzIuNiqAouYRVCpeX:-968324417) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster_test.go#L163)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> once we figure out why the test fails, there's no reason for this transfer, right? In fact, even better to test removing the leader.
</details>
Correct. @andreimatei, @tschottdorf, the failure is caused by https://github.com/cockroachdb/cockroach/blob/master/storage/replica_command.go#L1647-L1649:

```
			log.Infof("range %d: new range lease %s following %s [physicalTime=%s]",
				r.RangeID, lease, prevLease, r.store.Clock().PhysicalTime())
			r.mu.tsCache.SetLowWater(prevLease.Expiration)
```

`prevLease.Expiration` is in the future. Is it unsafe for the lease holder to adjust the expiration of the lease? If yes, lease transfer before lease expiration is going to be problematic.  The comments above `TransferLease` suggest that the new lease can overlap with the previous lease, so perhaps there is just a bug here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858)*

**Comment by petermattis** [comment]
I've commented out the problematic portion of the test and also switched to removing a non-leader replica. There is a `TODO` about figuring out the slowness of removing the leader replica.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[testutils/testcluster/testcluster.go, line 344 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMlWt-0C5z_sK11yMbZ:-KMo2sBEWmJ1lf2p3Gfc:-703554254) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster.go#L344)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> yeah, maybe both this and AddReplicas shouldn't mutate the arg, for tests' conveniance
</details>
I've changed `{Add,Remove}Replicas` to take a key instead of a `RangeDescriptor` as the first argument.

---

*[testutils/testcluster/testcluster.go, line 344 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMn5zhZz6ybGCQ86KqM:-KMo2zogo1G6R-owcLx_:1476627404) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster.go#L344)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> if you keep this method taking a single target, I don't think we need the read in the beginning. You should rely on the caller to give you an up-to-date descriptor.
</details>
I've changed the method signature.

---

*[testutils/testcluster/testcluster.go, line 348 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMn5HtS8ESrRfh9oZe3:-KMo3UXs87WM0t6M-BvR:2113276715) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster.go#L348)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> down-replicate
</details>
Reworded here and in `AddReplicas`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-:-KMo3c4yQma-P2OsNnf2:-556809789)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[testutils/testcluster/testcluster.go, line 270 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMoBbQbcU_beI5oeQm1:-KMoBbQc22-rRIgjcAT4:-1057737631) ([raw file](https://github.com/cockroachdb/cockroach/blob/af84b4feeafcf7479156e1c3aed95a1e2a9b4f7b/testutils/testcluster/testcluster.go#L270)):*
> ```Go
> // new replicas and the new replicas become part of the Raft group.
> func (tc *TestCluster) AddReplicas(
> 	startKey roachpb.RKey, dests ...ReplicationTarget,
> ```

nit: `dests` here and `targets` below

---

*[testutils/testcluster/testcluster_test.go, line 160 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMoBsghrQj9t5G2GrAf:-KMoBsghrQj9t5G2GrAg:424178781) ([raw file](https://github.com/cockroachdb/cockroach/blob/af84b4feeafcf7479156e1c3aed95a1e2a9b4f7b/testutils/testcluster/testcluster_test.go#L160)):*
> ```Go
> 	}
> 
> 	// if err := tc.TransferRangeLease(desc, tc.Target(1)); err != nil {
> ```

did you mean to remove this transfer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[testutils/testcluster/testcluster.go, line 270 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMoBbQbcU_beI5oeQm1:-KMoCYQaOJM_KFhAIvEh:1028277431) ([raw file](https://github.com/cockroachdb/cockroach/blob/af84b4feeafcf7479156e1c3aed95a1e2a9b4f7b/testutils/testcluster/testcluster.go#L270)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: `dests` here and `targets` below
</details>
Done. Standardized on `targets`.

---

*[testutils/testcluster/testcluster_test.go, line 160 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMoBsghrQj9t5G2GrAf:-KMoCbHiyqYK2bUvfjUb:254987605) ([raw file](https://github.com/cockroachdb/cockroach/blob/af84b4feeafcf7479156e1c3aed95a1e2a9b4f7b/testutils/testcluster/testcluster_test.go#L160)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> did you mean to remove this transfer?
</details>
Yes, so my message above. This is something for @andreimatei and @tschottdorf to debug. I've added a `TODO`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858)*

**Comment by petermattis** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[testutils/testcluster/testcluster.go, line 334 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMn5riV5MHfg244-5bl:-KMoDJcLUXQYyQ-V_E_m:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster.go#L334)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> change to RemoveReplica*s* (plural) to match `AddReplicas`.
</details>
Done.

---

*[testutils/testcluster/testcluster_test.go, line 172 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMlWbrW5mbYhhrB0AfQ:-KMoDNMgINDJvqKbKgFQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster_test.go#L172)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/3/2/. better yet, give it a name and %d it in.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[testutils/testcluster/testcluster_test.go, line 160 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMoBsghrQj9t5G2GrAf:-KMoDTTdjn-Bts-g_5JS:1709472232) ([raw file](https://github.com/cockroachdb/cockroach/blob/af84b4feeafcf7479156e1c3aed95a1e2a9b4f7b/testutils/testcluster/testcluster_test.go#L160)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Yes, so my message above. This is something for @andreimatei and @tschottdorf to debug. I've added a `TODO`.
</details>
Yeah, sorry, I meant to ask if you meant to remove the code rather than comment it out. Makes sense with the TODO now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[testutils/testcluster/testcluster_test.go, line 163 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMn6WobNeKECENtUAdq:-KMsVIGwyHZrpVGECeQB:-298595159) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster_test.go#L163)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Correct. @andreimatei, @tschottdorf, the failure is caused by https://github.com/cockroachdb/cockroach/blob/master/storage/replica_command.go#L1647-L1649:
> 
> ```
> 			log.Infof("range %d: new range lease %s following %s [physicalTime=%s]",
> 				r.RangeID, lease, prevLease, r.store.Clock().PhysicalTime())
> 			r.mu.tsCache.SetLowWater(prevLease.Expiration)
> ```
> 
> `prevLease.Expiration` is in the future. Is it unsafe for the lease holder to adjust the expiration of the lease? If yes, lease transfer before lease expiration is going to be problematic.  The comments above `TransferLease` suggest that the new lease can overlap with the previous lease, so perhaps there is just a bug here.
</details>
Hmmm I wonder how the tests for the lease transfer work.
The leases indeed overlap in case of a transfer. I think the new holder must set the low-water mark to the present time, on the account of the old holder knowing that it can't serve anything after the transfer, and the old and new holders also synchronizing their clocks with the occasion of the transfer.

I'll send a fix out.

---

*[testutils/testcluster/testcluster_test.go, line 172 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMsZXWkpPrR5FG7wClk:-KMsZXWlEmw1n_SWzfxw:-2090078055) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ec30cf9978e1a1d5aacfb2780f4c50c95489d7/testutils/testcluster/testcluster_test.go#L172)):*
> ```Go
> 
> 	// TODO(peter): Removing the range leader (tc.Target(0)) causes the test to
> 	// take ~13s vs ~1.5s for removing a non-leader. Track down that slowness.
> ```

nice, `TestCluster` is paying off already

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[testutils/testcluster/testcluster_test.go, line 163 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMn6WobNeKECENtUAdq:-KMtXS1Jqq--5Iv3AYBI:-1064324348) ([raw file](https://github.com/cockroachdb/cockroach/blob/92c377967804c11844faf3832902b22a875d6eb9/testutils/testcluster/testcluster_test.go#L163)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> Hmmm I wonder how the tests for the lease transfer work.
> The leases indeed overlap in case of a transfer. I think the new holder must set the low-water mark to the present time, on the account of the old holder knowing that it can't serve anything after the transfer, and the old and new holders also synchronizing their clocks with the occasion of the transfer.
> 
> I'll send a fix out.
</details>
`Now()` would work, but feels dirty. This breaks now because the old lease is used and there is an implicit assumption that the old lease must have expired. Instead of using some unpredictable timestamp, see whether you can use `newLease.Start` (which seems like the most idiomatic of the bunch).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858)*

**Comment by bdarnell** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[testutils/testcluster/testcluster.go, line 287 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMtbWB5VvivVRqZVT_N:-KMtbWB5VvivVRqZVT_O:1376821342) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ec30cf9978e1a1d5aacfb2780f4c50c95489d7/testutils/testcluster/testcluster.go#L287)):*
> ```Go
> 		}
> 
> 		// Ask the first replica of the range to up-replicate. Note that the target
> ```

s/the first/an arbitrary/?

---

*[testutils/testcluster/testcluster.go, line 364 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMtcROx8ss0GglOZEvf:-KMtcROx8ss0GglOZEvg:-17913126) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ec30cf9978e1a1d5aacfb2780f4c50c95489d7/testutils/testcluster/testcluster.go#L364)):*
> ```Go
> 		}
> 		if err := replica.ChangeReplicas(context.Background(),
> 			roachpb.REMOVE_REPLICA,
> ```

These methods are nearly identical except for this constant and the extra wait for completion in the ADD case. Can we fold these into one method that takes ADD/REMOVE as an argument?

---

*[testutils/testcluster/testcluster_test.go, line 152 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMtcvQxyYepWAIauHvP:-KMtcvQxyYepWAIauHvQ:-691829021) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ec30cf9978e1a1d5aacfb2780f4c50c95489d7/testutils/testcluster/testcluster_test.go#L152)):*
> ```Go
> 	defer tc.Stopper().Stop()
> 
> 	desc, err := tc.AddReplicas(roachpb.RKey(keys.MinKey), tc.Target(1), tc.Target(2))
> ```

s/roachpb.RKey(keys.MinKey)/roachpb.RKeyMin/

---

*[testutils/testcluster/testcluster_test.go, line 172 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMsZXWkpPrR5FG7wClk:-KMtdakACokNip7Esxo0:-607647308) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ec30cf9978e1a1d5aacfb2780f4c50c95489d7/testutils/testcluster/testcluster_test.go#L172)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> nice, `TestCluster` is paying off already
</details>
My guess: at the end of `RemoveReplicas`, you do a consistent read of the range descriptor via the first store. Since that store has a local replica, it tries to read from itself first, and hangs until SendNextTimeout. Fixing the races and reducing SendNextTimeout would mitigate this problem, but there's probably something better we could do to get the local replica to fail sooner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858)*

**Comment by petermattis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[testutils/testcluster/testcluster.go, line 287 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMtbWB5VvivVRqZVT_N:-KMvLYresG8XhOG3Pc8C:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ec30cf9978e1a1d5aacfb2780f4c50c95489d7/testutils/testcluster/testcluster.go#L287)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/the first/an arbitrary/?
</details>
Done.

---

*[testutils/testcluster/testcluster.go, line 364 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMtcROx8ss0GglOZEvf:-KMvLWu2cQKQM3JVvJhb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ec30cf9978e1a1d5aacfb2780f4c50c95489d7/testutils/testcluster/testcluster.go#L364)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> These methods are nearly identical except for this constant and the extra wait for completion in the ADD case. Can we fold these into one method that takes ADD/REMOVE as an argument?
</details>
Done.

---

*[testutils/testcluster/testcluster_test.go, line 172 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858#-KMsZXWkpPrR5FG7wClk:-KMvLlMBSoWZcIM3neVr:1725126835) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ec30cf9978e1a1d5aacfb2780f4c50c95489d7/testutils/testcluster/testcluster_test.go#L172)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> My guess: at the end of `RemoveReplicas`, you do a consistent read of the range descriptor via the first store. Since that store has a local replica, it tries to read from itself first, and hangs until SendNextTimeout. Fixing the races and reducing SendNextTimeout would mitigate this problem, but there's probably something better we could do to get the local replica to fail sooner.
</details>
@andrematei Yes, `TestCluster` has been useful so far. I'm also using to test gossiping of the first range in various scenarios. 

@bdarnell I'll keep this in mind. I'm going to take a look tomorrow. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7858)*

**Pull request merged**
