### PR TITLE
log: Fix EntryDecoder to handle multi-line log messages

### LINKED ISSUE #15944: Log entry decoder used by status endpoint doesn't handle multi-line log messages
This causes the logs in the admin UI and all log files included in the output of `cockroach debug zip` to not include anything other than the first line of multi-line log messages.

This means for example, that

```
I170515 22:36:08.791058 247 storage/allocator.go:401  [replicate,n3,s3,r5/3:/Table/{0-11}] rebalance candidates: [
s4, valid:true, con:1.00, ranges:3, details:(diversity=0.00, preferred=0, converge=1.00)]
existing replicas: [
s3, valid:true, con:1.00, ranges:8, details:(diversity=0.00, preferred=0, converge=1.00)
s2, valid:true, con:0.00, ranges:9, details:(diversity=0.00, preferred=0, converge=0.00)
s1, valid:true, con:0.00, ranges:10, details:(diversity=0.00, preferred=0, converge=0.00)]
```

becomes

```
I170515 22:36:08.791058 247 storage/allocator.go:401  [replicate,n3,s3,r5/3:/Table/{0-11}] rebalance candidates: [
```

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #15944

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/log/clog.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949#-KkGUptdYCQulKjPc16q:-KkGUptdYCQulKjPc16r:byrfrbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d1ff3c6789660a75dfa2aa9e15f6101f8da1f1/pkg/util/log/clog.go#L328)):*
> ```Go
> 
> var entryRE = regexp.MustCompile(
> 	`(?m)^([IWEF])(\d{6} \d{2}:\d{2}:\d{2}.\d{6}) (?:(\d+) )?([^:]+):(\d+)  ((?s).*)`)
> ```

so you make the last group match newlines, but shouldn't you have to make this non-greedy somehow? Why doesn't the last group simply match the rest of the log file? Your test shows it does the right thing, but I'm not sure why.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949#-:-KkGVJ00kPI0SnlKK3_I:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/clog.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949#-KkGUptdYCQulKjPc16q:-KkGWcDFALWVqwrt5S3u:b-24odnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d1ff3c6789660a75dfa2aa9e15f6101f8da1f1/pkg/util/log/clog.go#L328)):*
> *EntryDecoder) split

It's because of how `(*EntryDecoder).split` works. When `Scan` is called on the scanner, `split` grabs everything until the next chunk that matches the regex, i.e. the next line that starts with all the per-log-line metadata.

It's possible that this new version is less efficient on large files, though, due to the size of the matches that we'll be processing in `split`. Might be worth a benchmark

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/clog.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949#-KkGUptdYCQulKjPc16q:-KkGZQhw6Zq3HQKxepyE:b3v6ceu) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d1ff3c6789660a75dfa2aa9e15f6101f8da1f1/pkg/util/log/clog.go#L328)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

> *EntryDecoder) split

It's because of how `(*EntryDecoder).split` works. When `Scan` is called on the scanner, `split` grabs everything until the next chunk that matches the regex, i.e. the next line that starts with all the per-log-line metadata.

It's possible that this new version is less efficient on large files, though, due to the size of the matches that we'll be processing in `split`. Might be worth a benchmark
</blockquote></details>

Huh? I could have sworn I tested this on multi-line log entries. That was the point of setting `(?m)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949#-:-KkGZbSuG56JRObL1yNw:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/clog.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949#-KkGUptdYCQulKjPc16q:-KkG_Dqw5nMRHk8bAadl:b-23knq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d1ff3c6789660a75dfa2aa9e15f6101f8da1f1/pkg/util/log/clog.go#L328)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Huh? I could have sworn I tested this on multi-line log entries. That was the point of setting `(?m)`.
</blockquote></details>

According to [the docs](https://github.com/google/re2/wiki/Syntax), all `(?m)` affects is letting `^` and `$` match the beginning and end of lines in addition to the beginning and end of the entire input text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/clog.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949#-KkGUptdYCQulKjPc16q:-KkG_iIYXat44cMIPv3_:b82b93p) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d1ff3c6789660a75dfa2aa9e15f6101f8da1f1/pkg/util/log/clog.go#L328)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

According to [the docs](https://github.com/google/re2/wiki/Syntax), all `(?m)` affects is letting `^` and `$` match the beginning and end of lines in addition to the beginning and end of the entire input text.
</blockquote></details>

Yep, I see that (now).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/clog.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949#-KkGUptdYCQulKjPc16q:-KkGZTlqp1UDpJJ7fShI:bmzo4f2) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d1ff3c6789660a75dfa2aa9e15f6101f8da1f1/pkg/util/log/clog.go#L328)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yep, I see that (now).
</blockquote></details>

Thanks, makes sense. Performance shouldn't be abysmal, ISTM that it would have to track two matches per line tops, and there isn't any backtracking in there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15949)*

**Comment by a-robinson** [comment]
@petermattis did you mention cherry-picking this into 1.0.1? It's not critical, but could help in debugging situations.

**Comment by petermattis** [comment]
Yes, seems worth cherry-picking.

**Pull request merged**
