### PR TITLE
importccl: Support import resume for all input formats

### PR DESCRIPTION
**Pull request by miretskiy**
Add support for resuming imports for all inputs formats.
Add a unit test to verify resume behavior.

Release note (cli change): resume paused import

### CODE REVIEW

**Comment by miretskiy** [comment]
Please note, top 2 commits are being reviewed in https://github.com/cockroachdb/cockroach/pull/42476

**Comment by miretskiy** [comment]
Master picked up dependent changes; ready for review.

**Comment by spaskob** [comment]
thank you will look at it after lunch!

**Review by spaskob — CHANGES_REQUESTED** [review]
I think you are missing read_import_mysqlout.go

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-:-Lvl1jY_-tPwOZP_WpjN:bivkrmw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/import_processor_test.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-Lvl0SzrE2BoZVahaOCE:-Lvl0SzrE2BoZVahaOCF:b6b7grt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0963fe15ec840c3619a07c88607e248d124c7c9a/pkg/ccl/importccl/import_processor_test.go#L222)):*
> ```
> 
> ```
nit: keep it a 1-liner as well
___
*[pkg/ccl/importccl/import_processor_test.go, line 803 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-Lvl166oDXZSo-cJcgsm:-Lvl166oDXZSo-cJcgsn:baevzej) ([raw file](https://github.com/cockroachdb/cockroach/blob/0963fe15ec840c3619a07c88607e248d124c7c9a/pkg/ccl/importccl/import_processor_test.go#L803)):*
> ```
> descr, &descr.PrimaryIndex, colMap, []tree.Datum{tree.NewDInt(tree.DInt(id))}, primaryIndexKeyPrefix)
> ```
long line

**Review by miretskiy — COMMENTED** [review]
> read_import_mysqlout.go
Good catch.  Added; test updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-:-LvlJDSLBlSl3YKp9Epr:bgyfq40)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/ccl/importccl/import_processor_test.go, line 803 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-Lvl166oDXZSo-cJcgsm:-LvlDOFv3PuFWw9hQ7SR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0963fe15ec840c3619a07c88607e248d124c7c9a/pkg/ccl/importccl/import_processor_test.go#L803)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

> ```
> descr, &descr.PrimaryIndex, colMap, []tree.Datum{tree.NewDInt(tree.DInt(id))}, primaryIndexKeyPrefix)
> ```
long line
</blockquote></details>

Done.

**Review by spaskob — CHANGES_REQUESTED** [review]
All Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43053)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/import_processor_test.go, line 245 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-LvlMK5ICrkhQTSMl8um:-LvlMK5ICrkhQTSMl8un:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/94a06ecc274c96857affec428335c417d6ebf9b0/pkg/ccl/importccl/import_processor_test.go#L245)):*
> ```Go
> 			ExternalStorage: externalStorageFactory,
> 			BulkAdder: func(
> 				_ context.Context, _ *client.DB, _ hlc.Timestamp, _ storagebase.BulkAdderOptions) (storagebase.BulkAdder, error) {
> ```

long line
___
*[pkg/ccl/importccl/import_processor_test.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-LvlMNJZ7ZxI4OtBveii:-LvlMNJZ7ZxI4OtBveij:b-bkb7il) ([raw file](https://github.com/cockroachdb/cockroach/blob/94a06ecc274c96857affec428335c417d6ebf9b0/pkg/ccl/importccl/import_processor_test.go#L312)):*
> ```Go
> 			}
> 
> 			processor.Run(context.TODO())
> ```

context.Background()
___
*[pkg/ccl/importccl/import_processor_test.go, line 333 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-LvlMQJT52rNNy9ybrmZ:-LvlMQJT52rNNy9ybrm_:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/94a06ecc274c96857affec428335c417d6ebf9b0/pkg/ccl/importccl/import_processor_test.go#L333)):*
> ```Go
> 			ExternalStorage: externalStorageFactory,
> 			BulkAdder: func(
> 				_ context.Context, _ *client.DB, _ hlc.Timestamp, _ storagebase.BulkAdderOptions) (storagebase.BulkAdder, error) {
> ```

long line
___
*[pkg/ccl/importccl/import_processor_test.go, line 344 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-LvlMTNu7NG_6cK-O0GO:-LvlMTNu7NG_6cK-O0GP:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/94a06ecc274c96857affec428335c417d6ebf9b0/pkg/ccl/importccl/import_processor_test.go#L344)):*
> ```Go
> 	// In this test, we'll specify various resume positions for different input formats.
> 	// We expect that the rows before resume position will be skipped.
> 	// NB: We assume that the (external) test files are sorted and contain at least batchSize rows.
> ```

long line
___
*[pkg/ccl/importccl/import_processor_test.go, line 368 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-LvlMXw87IpEyMKSDL0v:-LvlMXw87IpEyMKSDL0w:bc6o6xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/94a06ecc274c96857affec428335c417d6ebf9b0/pkg/ccl/importccl/import_processor_test.go#L368)):*
> ```Go
> 				// Setup progress consumer.
> 				go func() {
> 					// Consume progress reports. Since we expect every batch to be flushed (BulkAdderFlushesEveryBatch),
> ```

long lines
___
*[pkg/ccl/importccl/import_processor_test.go, line 379 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43053#-LvlMZMw0AFw1JA9biH1:-LvlMZMw0AFw1JA9biH2:b-bkb7il) ([raw file](https://github.com/cockroachdb/cockroach/blob/94a06ecc274c96857affec428335c417d6ebf9b0/pkg/ccl/importccl/import_processor_test.go#L379)):*
> ```Go
> 				}()
> 
> 				_, err := runImport(context.TODO(), flowCtx, spec, progCh)
> ```

context.Background()

**Review by spaskob — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43053)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

**Pull request merged**
