### PR TITLE
util: introduce generic containers package

### PR DESCRIPTION
**Pull request by nvb**
This PR introduces a new `util/container` package.

Package container provides three container types: `heap`, `list`, and `ring`.

The package is a direct copy of the Go standard library's `container` package, but with interfaces replaced with generics. No other changes have been made, even at the expense of ergonomics in a few places, and no other changes should be made. The intention is to delete this library when the Go standard library adds generics support to these packages.

The use of generics over (empty) interfaces for the contained value in these containers provides three main benefits:

- type safety: generics replace dynamic type assertions with static type checks. This ensures that code with type errors cannot compile, rather than panicking at runtime.

- performance: generics allow values to be stored directly in the container, rather than boxed in an interface{}. This reduces allocations, eliminates runtime type assertions, and improves cache locality.

- code documentation: generics require the container to be parameterized by the type of value it stores. This serves as a helpful form of documentation that describes the intended use of the container.

Container types are one of the quintessential application of generics, so much of the benefit of generics that was described in the original design proposal[^1] is realized by this package.

The PR then includes a trio of follow up commits that adopt this new package, one for each container type:
- `heap` in `unresolvedTxnHeap`
- `list` in `intervalSkl`
- `ring` in `SpanStatsCollector`

[^1]: https://go.googlesource.com/proposal/+/HEAD/design/43651-type-parameters.md

Epic: None
Release note: None

### CODE REVIEW

**Review by pav-kv — COMMENTED** [review]
> No other changes have been made, even at the expense of ergonomics in a few places, and no other changes should be made.

The no changes policy makes sense given it's a "forked" code, and we should be able to patch upstream changes to it with minimal effort, and then migrate seamlessly.

Are there any "ergonomic" changes that we would like though? Just mentioning, because it's still possible to do without inlining into the fork. For example, we could have an adapter `containers.Heap[T]` with `Push(v)` and `Pop()` methods which would use `heap.Push[T](v)` and `heap.Pop[T]()` under the hood. (although it would be harder to support the inverted indexing built into this type, right now it's conveniently left out of scope of the interface)

**Comment by nvanbenschoten** [comment]
> Are there any "ergonomic" changes that we would like though?

Yeah, as you mentioned, `heap` is the case where we could improve ergonomics by having the library own the underlying data. This would allow us to transition from generic functions (which require a type annotation on each call) to a generic type with methods (which don't require a type annotation). We could also provide a default slice-backed heap implementation, instead of forcing each user to provide their own.

I'm not opposed to us doing that in a follow-up PR.

**Review by knz — APPROVED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rickystewart)

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=knz

**Pull request merged**
