### PR TITLE
colexec: fix multiple starts of the wrapped processors

### LINKED ISSUE #44133: Crash when using VECTORIZE=experimental_on
Consider the following test case:

```SQL
SET SESSION VECTORIZE=experimental_on;
CREATE TABLE t0(c0 STRING);
CREATE TABLE t1(c0 STRING UNIQUE NOT NULL);
SELECT * FROM t0, t1 WHERE t0.c0 NOT BETWEEN t1.c0 AND '' AND (t1.c0 IS NULL); -- crash
```

Unexpectedly, the query results in a crash (see stack trace below).

I found this issue in commit `3bb183403b4bc75c25fbcfc69d7d35de76d2b984` on Ubuntu 19.04.

```
oveToDraining called in state StateTrailingMeta with err: received multiple headers
goroutine 443 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x744cb00, 0xed5b6c637, 0x0, 0x840c90)
	.../go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb1
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0x7449a40, 0xc000000004, 0x6cdb4a1, 0x1f, 0x24a, 0xc0188cfa80, 0x7a)
	.../go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:209 +0x968
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4a9bd80, 0xc01059e940, 0x4, 0x2, 0x416e782, 0x2e, 0xc00e6e1de8, 0x2, 0x2)
	.../go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2cc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4a9bd80, 0xc01059e940, 0x1, 0xc000000004, 0x416e782, 0x2e, 0xc00e6e1de8, 0x2, 0x2)
	.../go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:44 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
	.../go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:155
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).MoveToDraining(0xc00a827200, 0x4a259a0, 0xc00f8b4b00)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:586 +0x30c
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*valuesProcessor).Start(0xc00a827200, 0x4a9bd80, 0xc01059e940, 0xc007693180, 0x400)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/values.go:81 +0x224
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init(0xc0263c6700)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:85 +0x211
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*hashJoinEqOp).Init(0xc02167bd00)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/hashjoiner.go:221 +0x6c
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*bufferOp).Init(0xc00f8b48e0)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/buffer.go:48 +0x33
github.com/cockroachdb/cockroach/pkg/sql/colexec.constBoolOp.Init(...)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/const.eg.go:111
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*caseOp).Init(0xc035fc9c00)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/case.go:99 +0x8d
github.com/cockroachdb/cockroach/pkg/sql/colexec.selBoolOp.Init(...)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/bool_vec_to_sel.go:121
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*boolVecToSelOp).Init(0xc01059efc0)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/bool_vec_to_sel.go:85 +0x33
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*simpleProjectOp).Init(0xc0035e63c0)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/simple_project.go:89 +0x33
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Start(0xc0263c6e00, 0x4a9bd80, 0xc01059e940, 0x749c4a0, 0x3b03440)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:132 +0x3e
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run(0xc0263c6e00, 0x4a9bd80, 0xc01059e940)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:748 +0x52
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc0232f67e0, 0x4a9bd80, 0xc01059e940, 0x427ece8, 0x0, 0x0)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370 +0x1fe
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000114780, 0xc00e09a120, 0xc0330ea1b0, 0xc00e6e2950, 0xc001152dc0, 0xc00d38e470, 0x0, 0x0)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:375 +0x413
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc000114780, 0x4a9be40, 0xc00aea7650, 0xc00d38e470, 0xc00e09a120, 0xc0330ea1b0, 0x4a9db80, 0xc00d43f080, 0xc001152dc0, 0xc00d38e1d8)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:977 +0x20a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc00d38e000, 0x4a9be40, 0xc00aea7650, 0xc00d38e390, 0x3, 0x7fae74b8fc40, 0xc00a0ac680, 0xc00e6e2b01, 0x0, 0x0, ...)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:823 +0x370
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc00d38e000, 0x4a9be40, 0xc00aea7650, 0xc00d38e390, 0x7fae74b8fc40, 0xc00a0ac680, 0x0, 0x0)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:715 +0x6af
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc00d38e000, 0x4a9be40, 0xc00aea7650, 0x4ab3a80, 0xc00ad66dc0, 0xc00621c6a9, 0x4d, 0x0, 0x2, 0x0, ...)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:418 +0xbc4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc00d38e000, 0x4a9be40, 0xc00aea7650, 0x4ab3a80, 0xc00ad66dc0, 0xc00621c6a9, 0x4d, 0x0, 0x2, 0x0, ...)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:100 +0x4f9
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00d38e000, 0x4a9bd80, 0xc018f10440, 0x0, 0x0)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1283 +0x1aa2
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00d38e000, 0x4a9bd80, 0xc00c0bc5c0, 0xc000931540, 0x5400, 0x15000, 0xc0009315d8, 0xc00963a140, 0x0, 0x0)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1212 +0x1c0
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000861900, 0x4a9bd80, 0xc00c0bc5c0, 0xc00d38e000, 0x5400, 0x15000, 0xc0009315d8, 0xc00963a140, 0x0, 0x0)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:451 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00a56a139, 0xc0082c2380, 0x4a9bd80, 0xc00c0bc5c0, 0xc00963a140, 0xc000861900, 0xc00a0ac000, 0x4ab1d00, 0xc0082c2360, 0xc00d280240, ...)
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:566 +0x2ae
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	.../go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:498 +0x17e

```

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix multiple starts of the wrapped processors**

Previously, wrapped processors could be started multiple times if they
were in the input chain for the bufferOp (each of the CASE arms will
initialize its input - the bufferOp). Now this is fixed by tracking in
both Columnarizer and bufferOp whether Init has already been called.

Previous behavior could lead to a crash when rowexec.valuesProcessor was
wrapped because it sends a "bogus" metadata header on each call to
Start, and only single header is expected whereas with multiple Inits
they would be multiple headers.

Fixes: #44133.

Release note (bug fix): Previously, CockroachDB could crash in special
circumstances when vectorized execution engine is used (it was more
likely to happen if `vectorize=experimental_on` setting was used). Now
this has been fixed.

**execerror: catch panics coming from sql/execinfra package**

sql/execinfra is definitely a part of the vectorized engine as a whole,
so we should be catching panics coming from it when running vectorized
flows.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The issue raises several questions:
- should we be catching panics coming from `execinfra`? I think yes
- should we modify the `Operator` interface so that `Init` can be called at most once? I think so (actually I put a TODO about it already into the code). Opened #44145
- it's actually unclear from `execinfra.RowSource` interface whether it is ok to call `Start` method multiple times. `valuesProcessor` is at least one example that shows that it is *not* ok.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

Am I correct in saying that this patch would also work if nothing is added to the columnarizer?

> should we be catching panics coming from execinfra? I think yes

I agree we should, I think we just didn't have the mechanism in place, while we added it to the vectorized engine because it had been such a problem not to catch panics.

> should we modify the Operator interface so that Init can be called at most once? I think so (actually I put a TODO about it already into the code). Opened #44145 

Unless we have a strong reason to allow Init to be called multiple times, I would prefer making it explicit that it should only be called only once. If there are exceptions, we can add those explicitly (i.e. a specific operator may be Inited more than once if an operator-specific `reset` method is called)

> it's actually unclear from execinfra.RowSource interface whether it is ok to call Start method multiple times. valuesProcessor is at least one example that shows that it is not ok.

That should be explicit as well.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44144#-:-Lz7YHhd5Jbb-HPoN5M0:b8awi5n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/buffer.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44144#-Lz7YQBG6ZVnS2pSeXj_:-Lz7YQBG6ZVnS2pSeXja:buc1t0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d686659ddd979884c7f8d3cfbe2dbdddca950867/pkg/sql/colexec/buffer.go#L49)):*
> ```Go
> 
> func (b *bufferOp) Init() {
> 	if b.initStatus == OperatorNotInitialized {
> ```

Add a comment as to why we're doing the check (no harm in being obvious).

**Review by yuzefovich — COMMENTED** [review]
I believe you are correct, but I added the changes to columnarizer to be safe. I think `bufferOp` is the only operator on which `Init` might be called multiple times, but I could be missing something.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44144#-:-Lz8JMrYEKd9BtxQsV_B:bfh8bhe)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
bors r-

Oops, missed that you left another comment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44144#-:-Lz8K20VCD8zXZ1GcARl:b3kgiq9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
I also pushed a second commit to catch panics from `sql/execinfra`. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44144#-:-Lz8LlHQ--FK8-r4UMNU:bqolq1t)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/buffer.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44144#-Lz7YQBG6ZVnS2pSeXj_:-Lz8Lk10AKsQANSVNXAH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d686659ddd979884c7f8d3cfbe2dbdddca950867/pkg/sql/colexec/buffer.go#L49)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Add a comment as to why we're doing the check (no harm in being obvious).
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44144#-:-Lz8oBUYE5PVLWy-U6X-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
