### PR TITLE
opt: Run bigtests with opt configs

### PR DESCRIPTION
**Pull request by andy-kimball**
- Enable bigtests to run nightly with opt configs
- Enable bigtests containing correlated subqueries
- Fix several bugs found while enabling bigtests

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm: assuming you address Radu's concerns

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/logic.go, line 1360 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26344#-LEAPKlw3INLbD8OBsm2:-LEAPKlw3INLbD8OBsm3:bpml75x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f33c3355d4a99f138aeaf466c7adeb00eb4aab91/pkg/sql/logictest/logic.go#L1360)):*
> ```Go
> 								// The number of expected fields must match the number
> 								// of expected types, except if:
> 								//   1. Expected results will be rewritten anyway.
> ```

Would help to clarify that this is due to the flag `rewriteResultsInTestFiles`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26344#-:-LEARwES-r5s8EXp0wuL:byd83w2)*

**Comment by andy-kimball** [comment]
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/logic.go, line 1360 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26344#-LEAPKlw3INLbD8OBsm2:-LEAd2ZL6quno5dWvscP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f33c3355d4a99f138aeaf466c7adeb00eb4aab91/pkg/sql/logictest/logic.go#L1360)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Would help to clarify that this is due to the flag `rewriteResultsInTestFiles`
</blockquote></details>

Done.

---

*[pkg/sql/logictest/logic.go, line 1362 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26344#-LEAGSIkC7gs5342C0yx:-LEAd9Zx40h32PKOx1gy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f33c3355d4a99f138aeaf466c7adeb00eb4aab91/pkg/sql/logictest/logic.go#L1362)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] columns
</blockquote></details>

Done.

---

*[pkg/sql/logictest/logic.go, line 1367 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26344#-LEAIq35CV_Vjl1B1ZXQ:-LEAdABAA5-K6Yt5JfUN:brwakd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f33c3355d4a99f138aeaf466c7adeb00eb4aab91/pkg/sql/logictest/logic.go#L1367)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

since we're using `len(query.colTypes)`, `valsPerLine` can just be a boolean `oneValPerLine`
</blockquote></details>

I actually tried that when I was developing this, and it turned out to be messier. This is because I use `valsPerLine` in several numeric contexts below. I'd have to do an `if` statement in each of those places in order to test the value of `oneValPerLine`.

---

*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 894 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26344#-LEAHEBW21iAwm4_HWit:-LEAdX848FnPqE-eKdsR:b-51vb4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f33c3355d4a99f138aeaf466c7adeb00eb4aab91/pkg/sql/logictest/testdata/logic_test/builtin_function#L894)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

A comment about the newline being converted to spaces would help here.

The --rewrite-results-in-testfiles code needs to know to do this as well. For example, add some bogus stuff to this output, and run with the flag. The rewritten output is going to be
```
fooXBa
YrXbazY
```
which isn't right anymore, and the test would subsequently fail without the flag, with a head-scratcher of a message:
```
        		expected:
        		    fooXBa
        		    YrXbazY
        		    
        		but found (query options: "") :
        		    fooXBa
        		    YrXbazY
```


Would it be difficult to just keep the old behavior altogether when `-bigtest` isn't passed?
</blockquote></details>

I now don't try to find value boundaries when a sort is not specified, so this case "works" with my latest patch.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26344)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt_exec_factory.go, line 378 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/26344#-LEAfRuQ6H-HOk7HSPWc:-LEAfRuQ6H-HOk7HSPWd:b-i3msku) ([raw file](https://github.com/cockroachdb/cockroach/blob/f03835f87af2aaeb06e2081e2108a58b7483ad51/pkg/sql/opt_exec_factory.go#L378)):*
> ```Go
> 		return newZeroNode(sqlbase.ResultColumnsFromColDescs(colDescs)), nil
> 	default:
> 		return nil, fmt.Errorf("%s not supported as input to lookup join", reflect.TypeOf(t))
> ```

[nit] can use `%T` instead of reflect

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26344#-:-LEAfujI-0FxjSHzuXGy:bnfp4nl)*

**Pull request merged**
