### PR TITLE
*: Refactor/rename contextutil package

### PR DESCRIPTION
**Pull request by miretskiy**
Move `TimeoutError` and `RunWithTimeout` to timeutil package. Remove unused `WithCancelReason` (go 1.20 has WithCancelCause). Move remaining `WithCancel` wrapper (which adds logging upon cancellation) to `ctxlog` package.

Epic: None
Release note: None

### CODE REVIEW

**Review by knz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @renatolabs, @rhu713, @rytaft, and @srosenberg)

___
*[`pkg/util/timeutil/timeout_error.go` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103705#-NW1kbkOBoaLzzobPrQz:-NW1kbkOBoaLzzobPrR-:b-wrbpzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/17349d20e244d608ba99c8489fc7481e5217c982/pkg/util/timeutil/timeout_error.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package timeutil
> ```

You need to use `errors.RegisterTypeMigration()`.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @renatolabs, @rhu713, and @srosenberg)

___
*[`pkg/util/timeutil/timeout_error.go` line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103705#-NW8JCzs9NhapojVqk6h:-NW8JCzs9NhapojVqk6i:bdj9if1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b7f5402dca9720a3eaebf96f5cbdcb6338d15d7/pkg/util/timeutil/timeout_error.go#L134)):*
> ```Go
> 	errors.RegisterWrapperEncoder(pKey, encodeTimeoutError)
> 	errors.RegisterWrapperDecoder(pKey, decodeTimeoutError)
> 	errors.RegisterTypeMigration("pkg/util/contextutil", "*ctxutil.TimeoutError", &TimeoutError{})
> ```

I'd be more comfortable if you could use `reflect.TypeOf(contextutil.SomethingStillInThatPackage).PkgPath()` for the first argument, instead of cranking out your own interpretation of the string.
See what we do in pkg/kv/kvpb/errors.go.

**Comment by knz** [comment]
> For now, that package is gone... I am thinking of putting something back there maybe/eventually;

Ok. Have you manually verified that the string returned by PkgPath is the same as the one you've hardcoded?

In my memory, there was additional text at the beginning (the full crdb go package path). This is what we need to be very careful about.

**Comment by miretskiy** [comment]
> 

just did.

**Review by knz — APPROVED** [review]
:lgtm: thank you.

> Reviewed 116 of 119 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103705#-:-NW8nvk43IvrXDDG8RJ9:bro309g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB, @renatolabs, @rhu713, and @srosenberg)

**Pull request merged**
