### PR TITLE
sql: fix index backfill read before GC TTL threshold error

### LINKED ISSUE #29192: schema change: index backfiller running with 1 month old timestamp and spamming logs
On a customer cluster I'm seeing an `IndexBackfiller` running with what appears to be a very old timestamp. Its scans are failing because the ts is below the GC threshold. Has it been running and failing for a month?
Logs show periodic:
```
E180827 10:15:41.157604 548472845 sql/distsqlrun/indexbackfiller.go:164  [n4,IndexBackfiller=215] scan error: batch timestamp 1532182391.295619869,0 must be after GC threshold 1533589762.856589150,0
```
`1532182391` is July 21. The gc threshold is August 6th (which is also really old; I hope that's expected in case there's been no garbage to collect after that date).

The logs are also full of the following, which I think means that an intent encountered is no longer present by the time the intent resolver runs. The keys are on the same table as the backfill, so I think the two might be connected, but I don't really know.
```
W180827 10:15:37.026282 548470998 storage/engine/mvcc.go:2081  [n4,s4,r16348/1:/Table/215/5/2018-07-20T03:2…] unable to find value for /Table/215/5/2018-07-20T03:25:39.505Z/"withdrawbd4e3d03-4074-470b-9741-fe43fe1067a0:6"/366958148014243846/0 @ 1535364936.509191055,0: 1532057139.455866667,0 (txn={ID:42a723f8-3c8b-4912-8145-38813287726d Isolation:SERIALIZABLE Key:[246 215 141 20 249 91 71 53 253 249 1 33 234 192 18 119 105 116 104 100 114 97 119 98 100 52 101 51 98 101 97 45 56 49 48 101 45 52 101 101 99 45 56 54 99 52 45 100 51 53 51 48 53 102 101 99 56 51 98 58 54 0 1 253 5 15 248 202 57 118 128 4 136] Epoch:0 Timestamp:1535364936.509191055,0 Priority:331139 Sequence:27 BatchIndex:0})
```

Same cluster as #29190, which another periodic schema change error.

### PR DESCRIPTION
**Pull request by vivekmenezes**
Before this change the historical read timestamp would remain fixed
for the duration of the index backfill. But if the index backfill
takes a long time or keeps restarting the timestamp can exceed the
GC window (configurable and defaults to 24hrs). Sometimes customers
are told to set the GC window to as low as 10m to reclaim disk space.

It was never clear what was the value of keeping this indefinitely
fixed. In fact it's quite likely it's worse to keep it fixed,
because any UPDATE to a row is likely to trigger redoing the index
backfill for the subspan containing the row at the current time.

This change marks the GC TTL threshold error as a non-permanent error.
On hitting the error, the backfill will be restarted at the last
checkpoint after picking a new historical read timestamp.

Includes a test that failed before the change.

fixes #29192

Release note (sql change): fix schema change rollback caused by
GC TTL threshold error.

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@jordanlewis any thoughts on this?

**Comment by jordanlewis** [comment]
Sorry, I missed this. Taking a look

**Comment by jordanlewis** [comment]
I think this will inhibit performance. Reading in the past is much faster when there are concurrent writes. This change effectively removes that optimization. You can test this easily - run kv with a high write percentage and run a concurrent index build. Your change should make the index build much slower.

**Comment by vivekmenezes** [comment]
@jordanlewis I've added a unittest that tests for this failure. The code now resets the historical read timestamp only on hitting the GC TTL threshold error. Ready for another review. Thanks!

**Comment by vivekmenezes** [comment]
Turns out there was already an existing test for this case. Shocked how little memory I have :-)

**Review by jordanlewis — APPROVED** [review]
LGTM

**Comment by vivekmenezes** [comment]
TFTR!

**Pull request merged**
