### PR TITLE
sql: initialize connExecutor with use_declarative_schema_changer

### LINKED ISSUE #85240: sql: connExecutor forgets to set its extraTxnState.SchemaChangeState.mode in initialization
When we open a new connection to a sql database and initialize a 
connExecutor, we forget to initialize its `extraTxnState.SchemaChangeState` 
so it's possible we use the legacy schema changer even if the
session variable `use_declarative_schema_changer = on`.

Part of the reason we didn't notice it previously is that whenever we
establish a connection to the database, certain stmts will be automatically
run and after each stmt, `resetTxnState` will run and there we did
set the schema changer state accordingly. It will only exhibit itself
when we attempt to open a connection but that previous one is not 
free so we have to open a new one from the connection pool. Such scenarios
happen in some unit tests when we do the "double channel dance" (e.g. 
run this DDL stmt while another DDL stmt is in backfill, just to test certain
expected behavior).

(I discovered it while debugging unit test `schema_changer_test/pk-change-before`
for `ALTER PRIMARY KEY` because I noticed that the new schema changer
is not used even if `use_schema_changer = on`.)

The fix is simple -- we just need to add a line
```ex.extraTxnState.schemaChangerState.mode = ex.sessionData().NewSchemaChangerMode```
in `func (s *Server) newConnExecutor(...)`.

The untrivial part is that this bug hid some issues in the declarative schema changer 
for `ADD/DROP COLUMN` (and possibly more), because the new schema changer
code is never exercised -- the legacy schema changer was unknowingly used. So I expect
some unit tests to fail after adding this line (e.g. `TestSchemaChangeWhileExecutingAlterColumnType`,
one of those tests that uses the "double channel dance" to test an error is thrown while 
a `ALTER COLUMN TYPE` is executing). Therefore, I opened a separate issue to track this 
bug (instead of just adding this line in my`ALTER PRIMARY KEY` PR). 

To close this issue, we will need to investigate and fix those failed unit tests 
after adding the line. We also need to add a test to ensure connExecutor is initialized
from the session variable `use_declarative_schema_changer`.

Jira issue: CRDB-18130

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Previously, we forget to initialize
`connExecutor.extraTxnState.schemaChangerState`. It was inadequate
because it can cause the system to use lagacy schema changer even if
the session variable is set to `use_declarative_schema_changer=on`. This
PR fixes this.

fix: #85240

Release note (bug fix): Fixed a bug that we forgot to initialize a
connExecutor's schemaChangerState from the corresponding session
variable (`use_declarative_schema_changer`), which can cause DDL
statements to be executed under the legacy schema changer unknowningly.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @Xiang-Gu)

___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85344#-N8Oahy289Aot0DT9Vwj):*
The commit which fixes the tests should come first. Can you reorder it?
___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85344#-N8OabND05igeXLWBvC4):*
nit: remove this
___
*[`pkg/sql/schema_changer_test.go` line 7798 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85344#-N8OaVDq5c_Ja4TZmKRX:-N8OaVDq5c_Ja4TZmKRY:b-39soph) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b3956d168f31ee25ad63d42d29f2b8b95fa5eb3/pkg/sql/schema_changer_test.go#L7798)):*
> ```Go
> 			params.Knobs = base.TestingKnobs{
> 				DistSQL: &execinfra.TestingKnobs{
> 					RunBeforeBackfillChunk: func(_ roachpb.Span) error {
> ```

why did this change?

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85344#-N8Oahy289Aot0DT9Vwj):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The commit which fixes the tests should come first. Can you reorder it?
</blockquote></details>

Done
___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85344#-N8OabND05igeXLWBvC4):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: remove this
</blockquote></details>

done
___
*[`pkg/sql/schema_changer_test.go` line 7798 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85344#-N8OaVDq5c_Ja4TZmKRX:-N8PXQTm5OPClpwQHnlg:b6fvvq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b3956d168f31ee25ad63d42d29f2b8b95fa5eb3/pkg/sql/schema_changer_test.go#L7798)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why did this change?
</blockquote></details>

This test consists of three subtests. The change of adding that one-liner during connExecutor initialization will make the [first subtest](https://github.com/cockroachdb/cockroach/blob/6c043128406a3ed2a9d08688b1cc7961ac58212d/pkg/sql/schema_changer_test.go#L7740-L7750) fail because of the different blocking behavior on concurrent schema changes between the old and new schema changer. 

Then I disabled the new schema changer, as in other unit tests in the PR. But this time, this will make the [third subtest] (https://github.com/cockroachdb/cockroach/blob/6c043128406a3ed2a9d08688b1cc7961ac58212d/pkg/sql/schema_changer_test.go#L7763-L7773) fail because the testing knob is on `DeclarativeSchemaChanger` so the first transaction was not able to unblock the main goroutine (which was supposed to proceed to execute the second transaction).

To fix that, I changed the testing knob to one that will be used in both the old and new schema changer.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85344#-:-N8PoGfKDWfsWe707Oj1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @Xiang-Gu)

___
*[`pkg/sql/schema_changer_test.go` line 7798 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85344#-N8OaVDq5c_Ja4TZmKRX:-N8Po40xDTCNiwps5A2B:b-ccwwik) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b3956d168f31ee25ad63d42d29f2b8b95fa5eb3/pkg/sql/schema_changer_test.go#L7798)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

This test consists of three subtests. The change of adding that one-liner during connExecutor initialization will make the [first subtest](https://github.com/cockroachdb/cockroach/blob/6c043128406a3ed2a9d08688b1cc7961ac58212d/pkg/sql/schema_changer_test.go#L7740-L7750) fail because of the different blocking behavior on concurrent schema changes between the old and new schema changer. 

Then I disabled the new schema changer, as in other unit tests in the PR. But this time, this will make the [third subtest] (https://github.com/cockroachdb/cockroach/blob/6c043128406a3ed2a9d08688b1cc7961ac58212d/pkg/sql/schema_changer_test.go#L7763-L7773) fail because the testing knob is on `DeclarativeSchemaChanger` so the first transaction was not able to unblock the main goroutine (which was supposed to proceed to execute the second transaction).

To fix that, I changed the testing knob to one that will be used in both the old and new schema changer.
</blockquote></details>

I see. Thanks.

**Comment by Xiang-Gu** [comment]
TFTR!
bors r+

**Comment by rafiss** [comment]
I wonder if a callback approach like the one used here would be better
https://github.com/cockroachdb/cockroach/blob/e52f732f8130df956449786c053d1d4539548411/pkg/sql/conn_executor.go#L928-L932

**Pull request merged**
