### PR TITLE
ccl/sqlproxyccl: add basic login rate limiting

### PR DESCRIPTION
**Pull request by darinpp**
Moves from the CC repo a package which performs basic login admission
control to rate limit login attempts. Login attempts are rate limited
based solely on source IP. Admission control is currently purely a
local decision, but the package this interface defines could easily
become the client-side for connection to a centralized service.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm:

Is the eventual plan to import this package from the `cockroachdb` repo into the `managed-service` repo, so that it doesn't exist in both places?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64305#-:-MZQfaZN4rcFStnsABsf:b-qsp8av)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by darinpp** [comment]
> :lgtm:
> 
> Is the eventual plan to import this package from the `cockroachdb` repo into the `managed-service` repo, so that it doesn't exist in both places?
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64305#-:-MZQfaZN4rcFStnsABsf:b-qsp8av)_ status: :shipit: complete! 1 of 0 LGTMs obtained

Yes, this is the plan.

**Pull request merged**
