### PR TITLE
roachtest: run ycsb roachtest on zfs

### PR DESCRIPTION
**Pull request by bananabrick**
As part of testing of cockroach on the zfs filesystem,
we want to start by enabling some simple roachtests on zfs.

Release note: None

### CODE REVIEW

**Comment by bananabrick** [comment]
I added the support to set file system on node creation here: https://github.com/cockroachdb/cockroach/pull/67788

I'm still not quite sure, how to make this show up on the roachperf, dashboard. The roachperf links on the wiki don't seem to mention it, unless I missed something.

**Review by itsbilal — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67884)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @tbg)

___
*[pkg/cmd/roachtest/spec/cluster_spec.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67884#-MfDRsPl4lCjfJWF5eW5:-MfDRsPl4lCjfJWF5eW6:b66cy0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b53468b76496b29f2132750a5641ee8b54fb9ce/pkg/cmd/roachtest/spec/cluster_spec.go#L42)):*
> ```Go
> 	// the test. The ext4 file system is used by default, when UseZfs is
> 	// false.
> 	UseZfs bool
> ```

Would be better to make this a `Filesystem string`, and have empty mean ext4. Down below you could just have switches for the Filesystem, and `default` could return `unsupported filesystem`. 
___
*[pkg/cmd/roachtest/tests/ycsb.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67884#-MfDS7lR3ng0hZBLEC5R:-MfDS7lR3ng0hZBLEC5S:bfo8e93) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b53468b76496b29f2132750a5641ee8b54fb9ce/pkg/cmd/roachtest/tests/ycsb.go#L97)):*
> ```Go
> 				r.Add(registry.TestSpec{
> 					Name:    fmt.Sprintf("ycsb/%s/zfs/nodes=3/cpu=%d", wl, cpus),
> 					Owner:   registry.OwnerStorage,
> ```

Happy to get other people's inputs on this, but we likely don't want to change the owner for a sub-test like this. Might be better to just keep it KV.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67884)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @itsbilal, and @tbg)

___
*[pkg/cmd/roachtest/spec/cluster_spec.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67884#-MfDRsPl4lCjfJWF5eW5:-MfDe8NW1ebRdim54dpZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b53468b76496b29f2132750a5641ee8b54fb9ce/pkg/cmd/roachtest/spec/cluster_spec.go#L42)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Would be better to make this a `Filesystem string`, and have empty mean ext4. Down below you could just have switches for the Filesystem, and `default` could return `unsupported filesystem`. 
</blockquote></details>

Done.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67884)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @itsbilal, and @tbg)

___
*[pkg/cmd/roachtest/spec/cluster_spec.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67884#-MfDibQF6BoPc-HGNO9n:-MfDibQF6BoPc-HGNO9o:bsg983z) ([raw file](https://github.com/cockroachdb/cockroach/blob/648a2d57123e7a7749e53e551ac9dda6f64bee2d/pkg/cmd/roachtest/spec/cluster_spec.go#L196)):*
> ```Go
> 	}
> 
> 	// Make sure that this doesn't show up as a failed roachtest.
> ```

This fails the roachtest command, if the flags don't add up(use gce+zfs). Will this show up as a failed roachtest? I'm worried about the ycsb test being run on aws, resulting in a failed roachtest due to the code here.

**Review by itsbilal — APPROVED** [review]
:lgtm: save for two minor suggestions

> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67884#-:-MfDsz5M79JkppwW4XPF:bhn6a91)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick, @itsbilal, and @tbg)

___
*[pkg/cmd/roachtest/spec/cluster_spec.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67884#-MfDrEKH9ZNqe1MeL7Gg:-MfDrEKH9ZNqe1MeL7Gh:b-vfpoi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/648a2d57123e7a7749e53e551ac9dda6f64bee2d/pkg/cmd/roachtest/spec/cluster_spec.go#L23)):*
> ```Go
> )
> 
> type FileSystemType string
> ```

Sorry for the bikeshedding on this, but since you have an enum / const thing going below, going, it makes more sense as an int, where the iota value can be Ext4. 
___
*[pkg/cmd/roachtest/spec/cluster_spec.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67884#-MfDibQF6BoPc-HGNO9n:-MfDrzGq4TtQ9VwdeXr9:b-ykytay) ([raw file](https://github.com/cockroachdb/cockroach/blob/648a2d57123e7a7749e53e551ac9dda6f64bee2d/pkg/cmd/roachtest/spec/cluster_spec.go#L196)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

This fails the roachtest command, if the flags don't add up(use gce+zfs). Will this show up as a failed roachtest? I'm worried about the ycsb test being run on aws, resulting in a failed roachtest due to the code here.
</blockquote></details>

Yeah, you're right, this isn't the right place as this code will run before `runYcsb`. We want control to fall into the `t.Skip` and skip the test, not error out before it even gets there. 

It looks like you already added an error for this in #67788 as part of cluster creation, so it's okay to just not have the error case in here.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67884)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick, @itsbilal, and @tbg)

___
*[pkg/cmd/roachtest/spec/cluster_spec.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67884#-MfDibQF6BoPc-HGNO9n:-MfEPWG94lnl22mS9Z6r:b-u5z64m) ([raw file](https://github.com/cockroachdb/cockroach/blob/648a2d57123e7a7749e53e551ac9dda6f64bee2d/pkg/cmd/roachtest/spec/cluster_spec.go#L196)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yeah, you're right, this isn't the right place as this code will run before `runYcsb`. We want control to fall into the `t.Skip` and skip the test, not error out before it even gets there. 

It looks like you already added an error for this in #67788 as part of cluster creation, so it's okay to just not have the error case in here. 
</blockquote></details>

The problem is that both failing in `ClusterSpec.Args`, or failing on cluster creation through roachprod seem to cause a failure here: https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/test_runner.go, which probably leads to a failed roachtest. It would be helpful to know how/where the roachtests are scheduled from, so that I can determine if my roachtest will ever be run with cloud=`aws/azure`. Cause it looks like that's going to lead to a failed roachtest.

**Comment by bananabrick** [comment]
Snooped around the code, and talked to @tbg on slack, and it seems as if my tests should get added to gce nightly automatically, and wouldn't get added to aws nightly tests, cause the aws nightly tests only run tests from an allow list in `teamcity-nightly-roachtest.sh`.

So, if the build passes, I'm going to merge this.

**Comment by bananabrick** [comment]
TFTRs!

bors r+

**Pull request merged**
