### PR TITLE
Move priority to TxnMeta; propagate priority on sequence cache poisoning

### PR DESCRIPTION
**Pull request by spencerkimball**
This provides ratcheting of priorities for transactions which fail due
to sequence cache poisoning. Before this, a transaction would restart or
retry (depending on whether it was aborted or pushed) with no knowledge
of how it might have had its priority ratcheted in its transaction
record; it would then just continue retrying obliviously.

Moving priority to TxnMeta looks to be generally useful going forward
for deciding the smartest move based on whether a write intent conflict
is pushable or should be waited out.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5558)

### CODE REVIEW

**Comment by spencerkimball** [comment]
@andreimatei is there an issue for this?

**Comment by andreimatei** [comment]
I don't think there's an issue. The ones that I care about I just talk to
people about over and over.

**Comment by tschottdorf** [comment]
Needs a rebase.

**Comment by spencerkimball** [comment]
@tschottdorf is this on your radar?

**Comment by tschottdorf** [comment]
Yes, going to plow through right after the rebase.

**Comment by spencerkimball** [comment]
Rebased.

**Comment by tschottdorf** [comment]
:lgtm: with comments addressed.

---

Reviewed 4 of 17 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[kv/txn_test.go, line 290 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-KDoqn1MygihbwdCidku:-KDoqn1MygihbwdCidkv:16766272) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b6ab66d3179748c598a82a56b5f5f9d0f139c9/kv/txn_test.go#L290)):*
it's obvious, but add `// pusher will win`.

---

*[kv/txn_test.go, line 292 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-KDoqtXp_mEC_lujFA5I:-KDoqtXp_mEC_lujFA5J:625437060) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b6ab66d3179748c598a82a56b5f5f9d0f139c9/kv/txn_test.go#L292)):*
The name suggest you're starting a push here directly. Maybe`s/readAndPush/pushByReading/`?

---

*[kv/txn_test.go, line 301 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-KDor2HR-_puqqWPAOuk:-KDor2HS70ieLxQXAIzX:-1863930256) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b6ab66d3179748c598a82a56b5f5f9d0f139c9/kv/txn_test.go#L301)):*
`abortByWriting`

---

*[storage/gc_queue_test.go, line 391 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-KDornz7TaYFUdA56YHG:-KDornz7TaYFUdA56YHH:-236483438) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b6ab66d3179748c598a82a56b5f5f9d0f139c9/storage/gc_queue_test.go#L391)):*
Add inline comment.

---

*[storage/replica.go, line 1623 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-KDos1cctOsjrFfWe3Ku:-KDos1cctOsjrFfWe3Kv:1262850423) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b6ab66d3179748c598a82a56b5f5f9d0f139c9/storage/replica.go#L1623)):*
Not quite sure why we were passing the entry prior to this change, actually. This always unmarshals a proto on every Get - we could pass in `nil` and unmarshal (calling `Get` again) only if we actually need it (in your change below).
Might be overoptimizing things, but add a TODO - @nvanbenschoten mentioned that he saw about 15% of the time spent checking the sequence cache for the photos app.

---

*[storage/replica_command.go, line 605 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-KDosQQn7YrrQxXQzmEt:-KDosQQn7YrrQxXQzmEu:1572671634) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b6ab66d3179748c598a82a56b5f5f9d0f139c9/storage/replica_command.go#L605)):*
This is a `gofmt` oddity  (to flow the comma to the left of the inline comment).  Could change to `// !poison` or move the inline comment before the `false`.

---

*[storage/engine/mvcc.go, line 607 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-KDosvqg-DOO2C2_eZh0:-KDosvqg-DOO2C2_eZh1:-666556509) ([raw file](https://github.com/cockroachdb/cockroach/blob/c842eb239ae576daedf597d690c463f97a9a033f/storage/engine/mvcc.go#L607)):*
Nothing to worry about with a `0` priority? Could we hard-code `1` instead?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-:-KDot2m2FvvGnsullvIl:1905687740)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[storage/gc_queue_test.go, line 391 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-KDornz7TaYFUdA56YHG:-KDpALKdeXlAGCF0Vu34:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b6ab66d3179748c598a82a56b5f5f9d0f139c9/storage/gc_queue_test.go#L391)):*
Done.

---

*[storage/replica.go, line 1623 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-KDos1cctOsjrFfWe3Ku:-KDpDpxBbT8z-o7RrUpn:-480978940) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b6ab66d3179748c598a82a56b5f5f9d0f139c9/storage/replica.go#L1623)):*
Added a TODO.

---

*[storage/engine/mvcc.go, line 607 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558#-KDosvqg-DOO2C2_eZh0:-KDpBUufcMxMelcpy7fX:2050727662) ([raw file](https://github.com/cockroachdb/cockroach/blob/c842eb239ae576daedf597d690c463f97a9a033f/storage/engine/mvcc.go#L607)):*
The real priority is in the `TxnMeta` already now so there's no need for the fake `MinUserPriority` or to hard code something now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5558)*

**Pull request merged**
