### PR TITLE
sql: support AS OF with JOINs

### LINKED ISSUE #8188: sql: AS OF SYSTEM TIME should be allowed for joins
This query does not work:

```sql
SELECT * FROM bar CROSS JOIN baz AS OF SYSTEM TIME '2016-07-30 12:30:00'
-- or alternatively:
SELECT * FROM bar, baz AS OF SYSTEM TIME '2016-07-30 12:30:00'
```

although it could without changes to the execution engine.

Solving this issue requires either 1) changing `isAsOf` in `executor.go` to make more efforts at finding the `AS OF` clause in nested table expressions or 2) (easier, better) change the grammar to make `opt_as_of_clause` an attribute of the `from_clause` (so it is always placed and found at the top level of a `FROM` clause), not `table_ref` as currently implemented. This latter solution is also backward-compatible with current implementation.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #8188

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8198)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
The old grammar made sense if we wanted to support each table having its own, potentially different `AS OF` time. Technically we could support that - would it make the implementation too complicated?

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198#-:-KO84L75W7gd57wasC6N:-39759860)*

**Comment by mjibson** [comment]
Yes, that makes the implementation too complicated. Also I can't imagine a use case where that'd be useful.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198#-:-KO8604g5OF12dJKJ6tb:-2141219275)*

**Comment by RaduBerinde** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/walk.go, line 592 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198#-KO87eoODgrUt2HO2d6W:-KO87eoODgrUt2HO2d6X:-1188662628) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e47b97813693b9a0d60ae113e4fcfc1bee94323/sql/parser/walk.go#L592)):*
> ```Go
> 	stmtCopy := *stmt
> 	stmtCopy.Exprs = SelectExprs(append([]SelectExpr(nil), stmt.Exprs...))
> 	stmtCopy.From = &From{
> ```

Can you add a couple of tests with "AS OF" in `TestParse`?

---

*[sql/parser/walk.go, line 594 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198#-KO881PUbVcdg75cyX4F:-KO881PUbVcdg75cyX4G:976981419) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e47b97813693b9a0d60ae113e4fcfc1bee94323/sql/parser/walk.go#L594)):*
> ```Go
> 	stmtCopy.From = &From{
> 		Tables: TableExprs(append([]TableExpr(nil), stmt.From.Tables...)),
> 		AsOf:   stmt.From.AsOf,
> ```

Don't we want to make a copy of `AsOf.Expr`? Or we could make it just contain a string/StrVal instead of an `Expr`.

---

*[sql/parser/walk.go, line 611 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198#-KO88XIQqjhhoLAyg2WH:-KO88XIQqjhhoLAyg2WI:1805522290) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e47b97813693b9a0d60ae113e4fcfc1bee94323/sql/parser/walk.go#L611)):*
> ```Go
> func (stmt *SelectClause) WalkStmt(v Visitor) Statement {
> 	ret := stmt
> ```

Technically we should wak the `AsOf.Expr` here, though I'm not sure it ever matters in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198)*

**Comment by mjibson** [comment]
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/walk.go, line 592 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198#-KO87eoODgrUt2HO2d6W:-KO8U2l-qDrWaPottGgJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e47b97813693b9a0d60ae113e4fcfc1bee94323/sql/parser/walk.go#L592)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Can you add a couple of tests with "AS OF" in `TestParse`?
</details>
Done.

---

*[sql/parser/walk.go, line 594 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198#-KO881PUbVcdg75cyX4F:-KO8Rl_TffrXUEfqZCvq:-765620353) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e47b97813693b9a0d60ae113e4fcfc1bee94323/sql/parser/walk.go#L594)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Don't we want to make a copy of `AsOf.Expr`? Or we could make it just contain a string/StrVal instead of an `Expr`.
</details>
The comment for this function says "makes a copy of this Expr without recursing in any child Exprs", so I didn't think we needed any more than this. Since AsOf is a struct and not a pointer, I think this makes a copy of the whole AsOf struct, but with the same pointer to the Expr. Is my analysis wrong somewhere?

---

*[sql/parser/walk.go, line 611 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198#-KO88XIQqjhhoLAyg2WH:-KO8Sp3q83leXC3CH7fz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e47b97813693b9a0d60ae113e4fcfc1bee94323/sql/parser/walk.go#L611)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Technically we should wak the `AsOf.Expr` here, though I'm not sure it ever matters in this case.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/walk.go, line 594 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198#-KO881PUbVcdg75cyX4F:-KOAXSOzTpAKaU3uayPZ:-1362992158) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e47b97813693b9a0d60ae113e4fcfc1bee94323/sql/parser/walk.go#L594)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> The comment for this function says "makes a copy of this Expr without recursing in any child Exprs", so I didn't think we needed any more than this. Since AsOf is a struct and not a pointer, I think this makes a copy of the whole AsOf struct, but with the same pointer to the Expr. Is my analysis wrong somewhere?
</details>
Ah sorry, yes, it's a copy of this node and not any child Exprs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8198#-:-KOAXgVe9AC37zcttV4v:1417088721)*

**Pull request merged**
