### PR TITLE
sql,clusterversion: add a cluster version for procedures

### PR DESCRIPTION
**Pull request by mgartner**
#### sql,clusterversion: add a cluster version for procedures

Release note: None

#### sql/logictest: rename drop_routine to drop_function

The drop_routine test file has been renamed to drop_function because it
only tests dropping functions.

Release note: None

#### sql/logictest: move DROP PROCEDURE tests to their own file

This commit moves `DROP PROCEDURE` tests to their own file so that they
can be disabled for the mixed version configuration in a future commit.

Epic: CRDB-25388

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
All the other logic tests that use procedures need to disable the local-mixed-22.2-23.1 config, otherwise :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-:-Ng6RVPx1a3oS3WS8bVG:b-16ltmf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/mixed_version_procedure` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-Ng6S23b776buBA1uAc2:-Ng6S23b776buBA1uAc3:b43z080) ([raw file](https://github.com/cockroachdb/cockroach/blob/68cc3cb8092f8f0c0a84279ede2f897868894149/pkg/sql/logictest/testdata/logic_test/mixed_version_procedure#L20)):*
> ```
> 23.1
> 
> upgrade 0
> ```

Can this test be extended such that it upgrades to the point where the test procedure succeeds?

**Review by DrewKimball — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-:-Ng6VtUA0zZYB8Gjy-JV:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/create_function.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-Ng6ULsS4UmOmJAYXPPh:-Ng6ULsS4UmOmJAYXPPi:b-m8q36h) ([raw file](https://github.com/cockroachdb/cockroach/blob/68cc3cb8092f8f0c0a84279ede2f897868894149/pkg/sql/create_function.go#L55)):*
> ```Go
> 	}
> 
> 	version := params.ExecCfg().Settings.Version.ActiveVersion(params.ctx)
> ```

Could we check this in the optbuilder instead?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-Ng6TphrCBSS4adMq-u5:-Ng6TphrCBSS4adMq-u6:b-msomzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/68cc3cb8092f8f0c0a84279ede2f897868894149/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go#L37)):*
> ```Go
> 
> 	activeVersion := b.EvalCtx().Settings.Version.ActiveVersion(context.TODO())
> 	if n.IsProcedure && !activeVersion.IsActive(clusterversion.V23_2_PartiallyVisibleIndexes) {
> ```

`V23_2_PartiallyVisibleIndexes` should be `V23_2_Procedures`.
___
*[`pkg/sql/logictest/testdata/logic_test/mixed_version_procedure` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-Ng6S23b776buBA1uAc2:-Ng6UU39COXv40WoWlrL:b-dedh5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/68cc3cb8092f8f0c0a84279ede2f897868894149/pkg/sql/logictest/testdata/logic_test/mixed_version_procedure#L20)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Can this test be extended such that it upgrades to the point where the test procedure succeeds?
</blockquote></details>

When I tried this in the past the test ended up flaking, but maybe we can figure something out here.

**Review by mgartner — COMMENTED** [review]
> All the other logic tests that use procedures need to disable the local-mixed-22.2-23.1

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-:-Ng6vag5CDfGl6V-IEVI:b-fr4e6v)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/create_function.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-Ng6ULsS4UmOmJAYXPPh:-Ng6vgpW-nlmHludwUGS:bsiiruc) ([raw file](https://github.com/cockroachdb/cockroach/blob/68cc3cb8092f8f0c0a84279ede2f897868894149/pkg/sql/create_function.go#L55)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Could we check this in the optbuilder instead?
</blockquote></details>

Yes, good idea. I originally thought we couldn't, but I think we can. Done.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-Ng6TphrCBSS4adMq-u5:-Ng6w6G71I2GuZWSPVJa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68cc3cb8092f8f0c0a84279ede2f897868894149/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go#L37)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`V23_2_PartiallyVisibleIndexes` should be `V23_2_Procedures`.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/mixed_version_procedure` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-Ng6S23b776buBA1uAc2:-Ng6v5W84Q_Ws-gam6dA:bdprji1) ([raw file](https://github.com/cockroachdb/cockroach/blob/68cc3cb8092f8f0c0a84279ede2f897868894149/pkg/sql/logictest/testdata/logic_test/mixed_version_procedure#L20)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

When I tried this in the past the test ended up flaking, but maybe we can figure something out here.
</blockquote></details>

I've added a few extra commands to try this. We'll see if it works...

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 3 of 18 files at r2, 8 of 9 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111965#-:-NgApZ8k8Yf0m0qtVgIw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
