### PR TITLE
HLC: remove access to "bare" physical time

### PR DESCRIPTION
**Pull request by tamird**
This should alleviate some of the rejecting timestamp in future
failures we've been seeing in tests.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10610)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/client_replica_test.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWF1wIrje5BA2Gk11g5:-KWF1wIrje5BA2Gk11g6:b-85bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db1c2a36b183a28e10e7bc9ebec8a181d786171/pkg/storage/client_replica_test.go#L137)):*
> ```Go
> 
> 	// Once the accumulated offset reaches MaxOffset, commands will be rejected.
> 	_, pErr := client.SendWrappedWith(context.Background(), rg1(mtc.stores[0]), roachpb.Header{Timestamp: ts2.Add(clock.MaxOffset().Nanoseconds()+1, 0)}, &incArgs)
> ```

Why did this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610)*

**Comment by RaduBerinde** [comment]
A lot of these uses are about calculating a time duration. Using HLC for that can have unexpected effects. If another node's clock is 50ms ahead, 50ms can go by before the HLC's WallTime changes at all.  Or the other way, we can set `startNS` then we may receive an unrelated message from a host that has the clock 50ms ahead of us, and suddenly it looks like 50ms have passed.

This could result in various things being flaky or hard to debug. We should switch to a monotonic source for time delta calculations instead (#10572).

---

Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-:-KWF1v_Cobxpk8a0W1NO:b-pq6gdn)*

**Comment by andreimatei** [comment]
This is true, but I think very few, if any, of these tests actually have different "nodes" with different clocks.

---

Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-:-KWF4EpcLUGZo_QfHgVi:b-eh89ca)*

**Comment by tamird** [comment]
I think Radu might be (rightly) worried about production issues. I'm auditing the various users now.

---

Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/client_replica_test.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWF1wIrje5BA2Gk11g5:-KWF3CiPo90avoabG-Sc:bqlattz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db1c2a36b183a28e10e7bc9ebec8a181d786171/pkg/storage/client_replica_test.go#L137)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Why did this change?
</details>
I have no idea how this was passing before; note that the preceding code in this test sends a bunch of requests that are meant to move the clock forward (and even checks for that), so using a timestamp with a "big" offset from the start of the test results in a zero offset to the clock by the time we reach this part of the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-:-KWF3Po1hgDwhv2wHYUF:bi6isg2)*

**Comment by tamird** [comment]
OK, so I took a look and I basically think it's ok for those durations to be subject to HLC forward-ratcheting. That stuff only matters in the context of commands and transactions, and we actually _do_ want to experience forward time jumps in those cases. I've tidied up a few locations, and would appreciate your eyes on this once more.

**Comment by RaduBerinde** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/client_replica_test.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWF1wIrje5BA2Gk11g5:-KWF98jMpVR7_FZuB3Oy:bnow4cr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db1c2a36b183a28e10e7bc9ebec8a181d786171/pkg/storage/client_replica_test.go#L137)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I have no idea how this was passing before; note that the preceding code in this test sends a bunch of requests that are meant to move the clock forward (and even checks for that), so using a timestamp with a "big" offset from the start of the test results in a zero offset to the clock by the time we reach this part of the test.
</details>
I think the expectation is that timestamps that are more than MaxOffset ahead of the physical clock won't be accepted, in which case the existing code made sense..

[nit] while you're here please break up this very long line

---

*[pkg/storage/store.go, line 2251 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWF9MIFanuu_m29x90t:-KWF9MIGhx0dtLysBVMV:b-abr8y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4436ebd585495e019864c13a05fc53fe81a1dc85/pkg/storage/store.go#L2251)):*
> ```Go
> 		// appears to come from a node with a bad clock, reject it now
> 		// before we reach that point.
> 		offset := ba.Timestamp.GoTime().Sub(s.Clock().Now().GoTime())
> ```

I am not sure about this. If we are checking clock drift between the nodes, don't we want to check against the physical clock? If two hosts talk frequently enough, the HLCs will never drift too much even if their clocks drift a lot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610)*

**Comment by tamird** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/client_replica_test.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWF1wIrje5BA2Gk11g5:-KWFBxOZQrU4lK0tUz-Q:b-w1ywuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db1c2a36b183a28e10e7bc9ebec8a181d786171/pkg/storage/client_replica_test.go#L137)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I think the expectation is that timestamps that are more than MaxOffset ahead of the physical clock won't be accepted, in which case the existing code made sense..
> 
> [nit] while you're here please break up this very long line
</details>
Indeed, it doesn't seem clear what behaviour we expect here (unless we go by the test). Paging bigwigs @bdarnell @petermattis.

---

*[pkg/storage/store.go, line 2251 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWF9MIFanuu_m29x90t:-KWFCDAnBqez9Pq0wEYK:b-5v4y12) ([raw file](https://github.com/cockroachdb/cockroach/blob/4436ebd585495e019864c13a05fc53fe81a1dc85/pkg/storage/store.go#L2251)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I am not sure about this. If we are checking clock drift between the nodes, don't we want to check against the physical clock? If two hosts talk frequently enough, the HLCs will never drift too much even if their clocks drift a lot.
</details>
Yeah, this is the same discussion as the other one. Paging the bigwigs against.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610)*

**Comment by bdarnell** [comment]
I'm -1 on using the HLC instead of the local clock for this. It's not always clear how to decide each case, but in many of them I think we *do* want the local time, and in any case it seems like a bad idea to change all of them at once without a better reason. Maybe once we have #10572 it will be worth auditing all our uses of time to categorize them as walltime, HLC, or monotonic. 

We could introduce a new function `timeutil.MonotonicUnixNano` which stores its own max value in a global and use that instead of `time.UnixNano` where needed. But I'm not sure that that's much of an improvement. Naive monotonic wrappers around wall time are often worse in practice than raw wall time at computing durations, for example. 

---

Reviewed 3 of 20 files at r1, 2 of 4 files at r2.
Review status: 5 of 23 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 100 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWIz9hU_dpL2Bw3-_Kk:-KWIz9hVVUjaS9GS4Irb:b-vcdzp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/97443279ea9380d2799c86ffacdf7d34a33598a9/pkg/rpc/clock_offset.go#L100)):*
> ```Go
> 			r.mu.offsets[addr] = offset
> 		}
> 	} else if oldOffset.isStale(r.offsetTTL, r.clock.Now().GoTime()) {
> ```

Don't we specifically want to use our non-HLC local time here? We don't want a group of clocks to be able to endlessly offset each other into the future.  

---

*[pkg/storage/client_replica_test.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWF1wIrje5BA2Gk11g5:-KWIzXRbG0rN25gsss72:bkmjzqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db1c2a36b183a28e10e7bc9ebec8a181d786171/pkg/storage/client_replica_test.go#L137)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Indeed, it doesn't seem clear what behaviour we expect here (unless we go by the test). Paging bigwigs @bdarnell @petermattis.
</details>
Yeah, the intention is that we limit how far the HLC can get from our best guess of the "true" time, not how big it can go in one jump. The old code captured the intention correctly. 

---

*[pkg/storage/replica_proposal.go, line 328 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWIzu1zFPbB3xZfkKrS:-KWIzu2-i1JQBnJDdUpk:b-4lwiib) ([raw file](https://github.com/cockroachdb/cockroach/blob/97443279ea9380d2799c86ffacdf7d34a33598a9/pkg/storage/replica_proposal.go#L328)):*
> ```Go
> 		// the timestamp cache low water.
> 		log.Infof(ctx, "new range lease %s following %s [physicalTime=%s]",
> 			newLease, prevLease, r.store.Clock().Now().GoTime())
> ```

It's just logging, but the intention (based on the text of the message) here was to show the local clock and not the HLC. If we do show the HLC, we shouldn't label it physicalTime and should show the whole thing including logical ticks. 

---

*[pkg/storage/store.go, line 2251 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWF9MIFanuu_m29x90t:-KWJ2F4svJy62KshRWNo:b-irnwzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4436ebd585495e019864c13a05fc53fe81a1dc85/pkg/storage/store.go#L2251)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, this is the same discussion as the other one. Paging the bigwigs against.
</details>
This is the one part of the PR that really matters; the rest is just cleanup. Here, we really do need a monotonic view of the clock underlying the HLC, which is not influenced by remote clocks. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-:-KWJ-MEfkmjGRhqIu9Eb:bv7ns73)*

**Comment by tamird** [comment]
I've addressed the line comments, so this PR is pretty much just cleanup now - it probably no longer "fixes" the issues referenced which occur during large backwards clock jumps.

Anyway, please take another look - I think it's worth merging even if it doesn't close those issues.

---

Review status: 0 of 24 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/rpc/clock_offset.go, line 100 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWIz9hU_dpL2Bw3-_Kk:-KWJ4lo2RTVmyU-gAcsR:b6jj9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/97443279ea9380d2799c86ffacdf7d34a33598a9/pkg/rpc/clock_offset.go#L100)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Don't we specifically want to use our non-HLC local time here? We don't want a group of clocks to be able to endlessly offset each other into the future.  
</details>
I'm not sure what you mean exactly; `Now()` doesn't update the local clock on the basis of a remote clock.

---

*[pkg/storage/client_replica_test.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWF1wIrje5BA2Gk11g5:-KWJ5GY9t7cDsQjT4OpE:bewfebt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db1c2a36b183a28e10e7bc9ebec8a181d786171/pkg/storage/client_replica_test.go#L137)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Yeah, the intention is that we limit how far the HLC can get from our best guess of the "true" time, not how big it can go in one jump. The old code captured the intention correctly. 
</details>
Yikes, good thing we silently update in hlc.Update.

---

*[pkg/storage/replica_proposal.go, line 328 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWIzu1zFPbB3xZfkKrS:-KWJ5MgzJgmUVYMW6sOs:b6bo53z) ([raw file](https://github.com/cockroachdb/cockroach/blob/97443279ea9380d2799c86ffacdf7d34a33598a9/pkg/storage/replica_proposal.go#L328)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> It's just logging, but the intention (based on the text of the message) here was to show the local clock and not the HLC. If we do show the HLC, we shouldn't label it physicalTime and should show the whole thing including logical ticks. 
</details>
Agreed, changed to show the full timestamp.

---

*[pkg/storage/store.go, line 2251 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWF9MIFanuu_m29x90t:-KWJ52pfrayFnYT6BYEg:b-nm8y01) ([raw file](https://github.com/cockroachdb/cockroach/blob/4436ebd585495e019864c13a05fc53fe81a1dc85/pkg/storage/store.go#L2251)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This is the one part of the PR that really matters; the rest is just cleanup. Here, we really do need a monotonic view of the clock underlying the HLC, which is not influenced by remote clocks. 
</details>
Updated by adding a new method for this check to the HLC. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-:-KWJG13i5B_abg8M19Yz:b-ohdphw)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 24 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/heartbeat.go, line 79 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWJMVlAPX7--tlUQfZd:-KWJMVlAPX7--tlUQfZe:bb7pugy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc7876653c4b25f62123ae3ef7003bfaa671196/pkg/rpc/heartbeat.go#L79)):*
> ```Go
> 	return &PingResponse{
> 		Pong:       args.Ping,
> 		ServerTime: hs.clock.Now().WallTime,
> ```

I think @bdarnell's comment above is really about this line and the line `receiveTime := ctx.localClock.Now().GoTime()`; these are what decide how the offset is calculated.

Anything calculating offsets should involve physical clocks. It's completely unclear what we are trying to measure by comparing walltimes of HLCs on different nodes.

Say we are in a cluster with 2 other nodes that have faster clocks. If we are constantly communicating with those machines (and thus updating our HLC), our `Now().WallTime` will never be far behind because it will get periodically updated. So our physical clock might have fallen behind by a lot but nobody will notice that.

As an extreme example, if we have RPCs between any two nodes every 10ms, the HLC walltimes will never be more than 10ms off, regardless of physical clocks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610)*

**Comment by bdarnell** [comment]
I don't think the "cleanup" portion of this PR is justified from a cost/benefit perspective. It's a bunch of semantic changes which may or may not matter, and many of which will just need to be changed again when we get access to CLOCK_MONOTONIC. I'd prefer to make a targeted fix to the actual issues and leave the rest alone until then. 

---

Review status: 0 of 24 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 100 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-KWIz9hU_dpL2Bw3-_Kk:-KWNv2ADWjmVFWoZBWHr:b-mjmc0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/97443279ea9380d2799c86ffacdf7d34a33598a9/pkg/rpc/clock_offset.go#L100)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm not sure what you mean exactly; `Now()` doesn't update the local clock on the basis of a remote clock.
</details>
`HLC.Now()` doesn't update anything, but it returns a value that has been influenced by a remote clock. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10610#-:-KWNv9PCAJsMDnXeoJfg:b-8mcfvw)*

**Pull request closed without merging**
