### PR TITLE
migrations: Remove TODO comment.

### PR DESCRIPTION
**Pull request by rohany**
Mistakenly left a comment.

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40339)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by rohany** [comment]
HOW DOES TEAMCITY FAIL

**Comment by rafiss** [comment]
heh, I think it was because of a flaky test, which it looks like is getting disabled (https://github.com/cockroachdb/cockroach/issues/40200)

**Pull request merged**
