### PR TITLE
storage: remove verification queue

### LINKED ISSUE #9329: Remove verify queue
The verify replica queue is meant to find bit-rot on disk by iterating over all data in a replica. We already do the same thing via the consistency checker, so probably better to just have one way to accomplish this.

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #9329

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9333)

### CODE REVIEW

**Comment by tamird** [comment]
Rather than only "fixes xxxx" in the commit message, can you please include the full rationale from that issue? It is better to not have to dereference a pointer when looking at this in `git log`.

**Comment by tschottdorf** [comment]
:lgtm: and agreed with @tamird that a short rationale is helpful even if there's an issue to link to.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333#-:-KRZwTmKw40c2tSKmwIJ:bn8dh9l)*

**Comment by spencerkimball** [comment]
Annoyingly there was leftover detritus which was not covered by my first attempt. Actually needed to remove references to last verification timestamp, while leaving in some bits to be deprecated appropriately.

**Comment by tamird** [comment]
Reviewed 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[keys/keys.go, line 252 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333#-KR_HYxyFeWOAt-edmt4:-KR_HYxyFeWOAt-edmt5:b-93jxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdb7d312c0c2940edac1530e97228e016a689ab/keys/keys.go#L252)):*
> ```Go
> // RangeLastVerificationTimestampKey returns a range-local key for
> // the range's last verification timestamp.
> func RangeLastVerificationTimestampKey(rangeID roachpb.RangeID) roachpb.Key {
> ```

should this also be renamed Deprecated?

---

*[keys/keys_test.go, line 113 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333#-KR_HBNhULVquEZub9ZM:-KR_HBNhULVquEZub9ZN:b92ai1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f829e743629a1ba340b1915cb505733f2e6f4b87/keys/keys_test.go#L113)):*
> ```Go
> 			RaftLogKey(0, 0),
> 			RangeLastReplicaGCTimestampKey(0),
> 			RangeLastVerificationTimestampKey(0),
> ```

this still exists, so should still be tested.

---

*[storage/replica_data_iter_test.go, line 84 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333#-KR_HPoDkudENwYV6kCJ:-KR_HPoDkudENwYV6kCK:b-px7vhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f829e743629a1ba340b1915cb505733f2e6f4b87/storage/replica_data_iter_test.go#L84)):*
> ```Go
> 		{keys.RaftLogKey(r.RangeID, 2), ts0},
> 		{keys.RangeLastReplicaGCTimestampKey(r.RangeID), ts0},
> 		{keys.RangeLastVerificationTimestampKey(r.RangeID), ts0},
> ```

keep this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[keys/keys.go, line 252 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333#-KR_HYxyFeWOAt-edmt4:-KRbBMiF37dY9NJgpt9I:bskr1vr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdb7d312c0c2940edac1530e97228e016a689ab/keys/keys.go#L252)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> should this also be renamed Deprecated?
</details>
Is it even still needed? It looks to me like you've removed all callers. 

---

*[storage/storagebase/state.proto, line 67 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333#-KRbBXNjPsYkq-tQ1PNM:-KRbBXNjPsYkq-tQ1PNN:bbc9rn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdb7d312c0c2940edac1530e97228e016a689ab/storage/storagebase/state.proto#L67)):*
> ```protobuf
> 
>   // Deprecated with removal of the verify queue.
>   util.hlc.Timestamp last_verification_deprecated = 4 [(gogoproto.nullable) = false];
> ```

This looks unused, so we can just make it `reserved`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333#-:-KRbBdoBkz-IkzluAEji:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: 9 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[keys/keys.go, line 252 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333#-KR_HYxyFeWOAt-edmt4:-KRd-OTJqFuQxj2y6POo:b-yzh6dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdb7d312c0c2940edac1530e97228e016a689ab/keys/keys.go#L252)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Is it even still needed? It looks to me like you've removed all callers. 
</details>
It's needed in the key printer and also some tests.

---

*[storage/storagebase/state.proto, line 67 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333#-KRbBXNjPsYkq-tQ1PNM:-KRcysRGADHURDd2HvLQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdb7d312c0c2940edac1530e97228e016a689ab/storage/storagebase/state.proto#L67)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This looks unused, so we can just make it `reserved`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9333#-:-KRd8N5W9LMVcBVC2vWS:bnfp4nl)*

**Pull request merged**
