### PR TITLE
sql: add support for joinReader to be the first join in paired joins

### PR DESCRIPTION
**Pull request by sumeerbhola**
This is to allow lookup joins to be used for left outer/semi/anti
joins with non-covering indexes. Currently only semi joins for
this case can use the index (by doing two inner joins and a DistinctOn)

Paired joins with a non-covering index will be used as follows:
- Left outer join: will become a pair of left outer lookup joins.
- Left anti join: will be a left outer lookup join followed by
  a left anti lookup join.
- Left semi join: will be an inner lookup join followed by a
  left semi lookup join.

This PR does not contain the optimizer changes.

Informs #55452

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: (but @yuzefovich or @asubiotto should take a look too)

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-:-ML8oc7a2aTWAO_J73VZ:b-pubjsu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML8jN2z5R5eFs7CXxqo:-ML8jN2z5R5eFs7CXxqp:b-3umva1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/execinfrapb/processors_sql.proto#L326)):*
> ```protobuf
>   optional bool left_join_with_paired_joiner = 14 [(gogoproto.nullable) = false];
> 
>   // OutputGroupContinuationForLeftRow indicates that this join is a first
> ```

[nit] a first -> the first
___
*[pkg/sql/rowexec/joinerbase.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML8joyL87u-Zn9U8lw1:-ML8joyL87u-Zn9U8lw2:bj4mjnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/rowexec/joinerbase.go#L87)):*
> ```Go
> 
> 	// condTypes does not include the continuation column, but the slice has the
> 	// capacity for it.
> ```

Why do you want to add capacity for it? (Is it so the extra capacity can be used for `outputTypes`? If so, would be good to say that here).

Also, since you're not using the variable `condRowSize`, you might as well just use one variable `size` or `rowSize`.
___
*[pkg/sql/rowexec/joinreader.go, line 882 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML8ls0m7wZdHRC5UD_L:-ML8ls0n3_LWldvC1BYv:b9d8baq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/rowexec/joinreader.go#L882)):*
> ```Go
> }
> 
> // setMatched returns the previous value of the matched field.
> ```

[nit] this comment should also describe the main purpose of the function, which is to set the matched field to true.
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML8mAD3AsHdTg-vjiX0:-ML8mAD3AsHdTg-vjiX1:bo6jkfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/rowexec/joinreader_strategies.go#L394)):*
> ```Go
> 	groupingState *inputBatchGroupingState
> 
> 	// True when this join is the first join in paired-joins. Note that in this
> ```

[nit] most comments for data members should start with the name of the field. E.g., `outputGroupContinuationForLeftRow is true when....`

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-:-ML9ySJ8Et3f7GlgVffc:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto and @sumeerbhola)

___
*[pkg/sql/rowexec/joinerbase.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML9yaVmCPp_Q1_zXSC1:-ML9yaVmCPp_Q1_zXSC2:b8c9r0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/rowexec/joinerbase.go#L95)):*
> ```Go
> 	if !jb.joinType.ShouldIncludeRightColsInOutput() {
> 		outputTypes = outputTypes[:len(leftTypes)]
> 	} else if outputContinuationColumn {
> ```

I think this needs to be broken up into two independent `if` blocks - currently, for left semi/anti we will never append a boolean if `outputContinuationColumn` is `true`.

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-:-MLKvd0r4y-uBHUUDPA5:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @rytaft, and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML8jN2z5R5eFs7CXxqo:-MLKsBE34o1WLOQ766X7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/execinfrapb/processors_sql.proto#L326)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] a first -> the first
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/joinerbase.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML8joyL87u-Zn9U8lw1:-MLKstPN32l5_7hFq1l9:b-11luk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/rowexec/joinerbase.go#L87)):*
> Why do you want to add capacity for it? (Is it so the extra capacity can be used for outputTypes? If so, would be good to say that here).

Yes, it is for outputTypes. Added a comment.
  
> Also, since you're not using the variable condRowSize, you might as well just use one variable size or rowSize.

Done
___
*[pkg/sql/rowexec/joinerbase.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML9yaVmCPp_Q1_zXSC1:-MLKu1rn84fPPCFwU6XD:b1s7qtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/rowexec/joinerbase.go#L95)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think this needs to be broken up into two independent `if` blocks - currently, for left semi/anti we will never append a boolean if `outputContinuationColumn` is `true`.
</blockquote></details>

We only support continuation for inner and left outer joins since it does not make sense to filter out false positives without outputting the right row. I've added a code comment that says that outputContinuationCol implies jb.joinType.ShouldIncludeRightColsInOutput() -- hopefully that makes it a bit clearer.
___
*[pkg/sql/rowexec/joinreader.go, line 882 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML8ls0m7wZdHRC5UD_L:-MLKuayuBdq_ZO6IU5Cw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/rowexec/joinreader.go#L882)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] this comment should also describe the main purpose of the function, which is to set the matched field to true.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML8mAD3AsHdTg-vjiX0:-MLKus0W-eWeAneYrRvm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/rowexec/joinreader_strategies.go#L394)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] most comments for data members should start with the name of the field. E.g., `outputGroupContinuationForLeftRow is true when....`
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56161)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto and @rytaft)

___
*[pkg/sql/rowexec/joinerbase.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-ML9yaVmCPp_Q1_zXSC1:-MLKwO_bEMnabXaKyoiy:b-lt0lyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebce62e7875dd0489dd85b262edab7634e810b/pkg/sql/rowexec/joinerbase.go#L95)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We only support continuation for inner and left outer joins since it does not make sense to filter out false positives without outputting the right row. I've added a code comment that says that outputContinuationCol implies jb.joinType.ShouldIncludeRightColsInOutput() -- hopefully that makes it a bit clearer.
</blockquote></details>

I see, makes sense.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56161#-:-MLKx8pM1CwIiLQ6MLHE:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

**Pull request merged**
