### PR TITLE
ui: fix infinite re-render on the key visualizer page

### PR DESCRIPTION
**Pull request by zachlite**
Since #101258, the TimeScaleDropdownWithSearchParams can cause infinite re-renders. The exact cause of the bug is not yet diagnosed, but it occurs on the key visualizer page, and seems to be related to the custom duration options. This is tracked in #106395.

This commit removes the dependency on TimeScaleDropdownWithSearchParams from the key visualizer, and replaces it with the vanilla TimeScaleDropdown. The custom duration options are still present.

Informs: #106395
Epic: none
Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106398)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)

___
*[`pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106398#-NZkmMhk6hiUMqGsQYLP:-NZkmMhk6hiUMqGsQYLQ:b45p0ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/db1d5892b1d1d42240bebd5adffeb5e0ee92cf97/pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx#L41)):*
> ```XML
> const IntervalSetting = "keyvisualizer.sample_interval";
> 
> const timeScaleOptions: TimeScaleOptions = {
> ```

can't you import this from cluster-ui since we have the options there already? Or is this means to be different (since I don't see the option for month and 2 months)?

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106398)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106398#-NZkmMhk6hiUMqGsQYLP:-NZkmjO_80AwC_fw_U1f:b-2j8uq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/db1d5892b1d1d42240bebd5adffeb5e0ee92cf97/pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx#L41)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can't you import this from cluster-ui since we have the options there already? Or is this means to be different (since I don't see the option for month and 2 months)?
</blockquote></details>

Since the key visualizer (currently) only persists samples for up to 1 week, it seemed strange to include duration options for anything longer. 

In the other direction, the default smallest duration of 10 minutes felt too small since we'll only collect 2 samples by default in that time period. (1 sample every 5 minutes)

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106398)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)

___
*[`pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106398#-NZkmMhk6hiUMqGsQYLP:-NZkpwpO7XCq2a9dh8RJ:b-c6b96s) ([raw file](https://github.com/cockroachdb/cockroach/blob/db1d5892b1d1d42240bebd5adffeb5e0ee92cf97/pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx#L41)):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

Since the key visualizer (currently) only persists samples for up to 1 week, it seemed strange to include duration options for anything longer. 

In the other direction, the default smallest duration of 10 minutes felt too small since we'll only collect 2 samples by default in that time period. (1 sample every 5 minutes)

</blockquote></details>

Got it! Thanks for clarifying!
Can you add a loom showing it working with those changes?

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106398)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106398#-NZkmMhk6hiUMqGsQYLP:-NZl2bAn6MFDaU_A0Vog:b-7ojsci) ([raw file](https://github.com/cockroachdb/cockroach/blob/db1d5892b1d1d42240bebd5adffeb5e0ee92cf97/pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx#L41)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Got it! Thanks for clarifying!
Can you add a loom showing it working with those changes?
</blockquote></details>

I increased the sample interval to _10 seconds_ just so it would be a little more interesting.
In the video, you can see how the samples displayed are a function of the time window selected. 
At the time the video was taken, the key visualizer was running for a little more than 30 minutes, so when 1 hour is selected, you can see the total number of samples displayed grow slightly. (No behavior has changed)

https://www.loom.com/share/96f64efc518f4b69bae67b6a2940456f?sid=c4b86c8f-7250-4ade-964d-5090300ff1ee

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106398#-:-NZlVHW0EqL9LQ9Crb1T:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
