### PR TITLE
build: integrate new cross toolchains w/ Bazel

### PR DESCRIPTION
**Pull request by rickystewart**
1. Add new toolchains that run on ARM hosts.
2. Add new toolchains that target M1 Mac's.

Release note: None

Jira issue: CRDB-14852

### CODE REVIEW

**Review by mari-crl — CHANGES_REQUESTED** [review]
Nice work! :D Woohoo, ARM builds!! :lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77960#-:-N--ByjXDW7-mPScNSbC:b-d59q6i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[build/toolchains/crosstool-ng/toolchain.bzl, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77960#-N--B8ip4rbSSAvOmacP:-N--B8iqBESBkRJRFqlV:b1csvy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/68355af110dca2654703821cc41d67a4729942a6/build/toolchains/crosstool-ng/toolchain.bzl#L4)):*
> ```Starlark
>     if rctx.attr.host == "x86_64":
>         url = "https://storage.googleapis.com/public-bazel-artifacts/toolchains/crosstool-ng/{}/20220317-191459/{}.tar.gz".format(rctx.attr.host, rctx.attr.target)
>     elif rctx.attr.host == "aarch64":
> ```

Just for my curiosity's sake, why the different URL for aarch64? Not supported in the most recent release yet?
___
*[c-deps/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77960#-N--BYUy5b9UydrzdaHi:-N--BYUy5b9UydrzdaHj:bpxedqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/68355af110dca2654703821cc41d67a4729942a6/c-deps/BUILD.bazel#L17)):*
> ```Starlark
>         "@io_bazel_rules_go//go/platform:darwin_arm64": [
>             "--host=aarch64-apple-darwin21.2",
>             "--with-lg-page=16",
> ```

Hmmm, why do we need this for arm and not for anything else?
___
*[c-deps/BUILD.bazel, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77960#-N--BtIZ--jsH1yE6oX3:-N--BtIZ--jsH1yE6oX4:b16y9k6) ([raw file](https://github.com/cockroachdb/cockroach/blob/68355af110dca2654703821cc41d67a4729942a6/c-deps/BUILD.bazel#L186)):*
> ```Starlark
>         "//build/toolchains:cross": {
>             "AUTOM4TE": "$(execpath :autom4te)",
>             "krb5_cv_attr_constructor_destructor": "yes",
> ```

Why the changes here?

**Review by mari-crl — APPROVED** [review]
Oop, didn't hit approve. :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77960#-:-N--C3qeBod9knSEtj9U:bmdmsbd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
> Just for my curiosity's sake, why the different URL for aarch64? Not supported in the most recent release yet?

To build these toolchains I ran the [CI script](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/internal/release/build-and-publish-cross-toolchains.sh) twice, once on a normal x86_64 agent and once on an ARM agent. The script is written to use the value of `date +%Y%m%d-%H%M%S` for the URL the toolchains are uploaded to, and so they'll write to different URL's as a matter of course (they'll never initiate this write at the exact same second). See https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_BuildAndPublishCrossToolchains?mode=builds#all-projects vs. https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_BuildAndPublishCrossToolchainsArmHost?mode=builds#all-projects

> Hmmm, why do we need this for arm and not for anything else?

Our `jemalloc` has this issue when cross-compiling for macOS ARM for some reason. If I remove this line, I get this error:

```
cockroach$ ./artifacts/cockroach-short
<jemalloc>: Error allocating TSD for 
zsh: abort      ./artifacts/cockroach-short
```

Adding the line back gets rid of it.

> Why the changes here?

This helps `configure` figure out a few checks that it otherwise can't perform when we're cross-compiling. [Here's](https://github.com/cockroachdb/cockroach/blob/d4daa99f6bcae263ba351e2b101901dae8bb110f/build/builder/mkrelease.sh#L54) another example.

**Comment by rickystewart** [comment]
bors r=mari-crl

**Pull request merged**
