### PR TITLE
opt: improve stats for filters with placeholder equalities

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: add stats tests for generic query plans

This commit adds some stats tests with queries containing placeholders.

Release note: None

#### opt: improve stats for filters with placeholder equalities

Stats estimates for filters of the form `col = $1` have been improved.
While histograms cannot be filtered without knowing the placeholder
value, we do know that `col` is limited to a one distinct value. This
improves the estimate over the simple 1/3 "unknown selectivity" that was
applied for these filters before this commit.

This changed required a modification to `TestCopyAndReplace` because it
made it such that a merge-join was no longer selected when optimizing
the query with placeholders. Now the test checks that `CopyAndReplace`
works correctly when copying a fully optimized memo with a parameterized
lookup-join. I've confirmed that the test still catches the bug
fixed in the original PR that added the test, #35020.

Epic: CRDB-37712

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first two commits are from #125795.

**Review by michae2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125808)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/memo/testdata/stats/generic` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/125808#-O-wot9K5F8LxaoBnUB0:-O-wot9K5F8LxaoBnUB1:b-9wrjgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b6c3e93aae68ebf6cdc92cdf8de76d3e1e09222/pkg/sql/opt/memo/testdata/stats/generic#L85)):*
> ```
> 
> norm
> SELECT * FROM t WHERE i = $1 AND s = $2
> ```

Some disjunction cases might also be interesting, maybe something like:
* `SELECT * FROM t WHERE k = $1 OR k = $2`
* `SELECT * FROM t WHERE i IN ($1, $2, $3)`
* `SELECT * FROM t WHERE i = $1 OR s = $2`

**Comment by mgartner** [comment]
*[`pkg/sql/opt/memo/testdata/stats/generic` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/125808#-O-wot9K5F8LxaoBnUB0:-O09mcvRDAJgTaACtiLU:bsibx63) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b6c3e93aae68ebf6cdc92cdf8de76d3e1e09222/pkg/sql/opt/memo/testdata/stats/generic#L85)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Some disjunction cases might also be interesting, maybe something like:
* `SELECT * FROM t WHERE k = $1 OR k = $2`
* `SELECT * FROM t WHERE i IN ($1, $2, $3)`
* `SELECT * FROM t WHERE i = $1 OR s = $2`
</blockquote></details>

Done. This change doesn't alter the row counts for any of these queries.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 10 of 10 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125808#-:-O0AZyCB12eZ4WT7he0Z:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
