### PR TITLE
sql: add comment to IndexedVarHelper

### PR DESCRIPTION
**Pull request by andreimatei**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12851)

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/indexed_vars.go, line 198 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12851#-KaDfU3vHnMNwdotgO78:-KaDfU3vHnMNwdotgO79:b-u01j9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfc6a883dc27d35ea1e98f65253fc5dad0313878/pkg/sql/parser/indexed_vars.go#L198)):*
> ```Go
> 	// Make sure that the variables previously bound to this container are not
> 	// usable before they're bound again.
> 	for i := range h.vars {
> ```

I thought this destruction would be a good idea, but a test fails. Is this expected? :S 
```
=== RUN   TestLogic/testdata/explain_types
--- new user: root
--- queries start here
panic: indexed var must be bound to a container before type resolution [recovered]
	panic: EXPLAIN (TYPES,NOEXPAND) SELECT 2*COUNT(k) as z, v FROM t WHERE v>123 GROUP BY v HAVING v<2: indexed var must be bound to a container before type resolution
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12851)*

**Comment by knz** [comment]
Before you go further with this, can you clarify in the commit message what is the problem that this patch intends to solve, and justify how this new mandatory run-time overhead is going to pay off.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12851#-:-KaDrFqebq4LIiXow6zb:b-cquutv)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/parser/indexed_vars.go, line 198 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12851#-KaDfU3vHnMNwdotgO78:-KaDrajRCwiLoZfxdnKn:b-v0oaap) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfc6a883dc27d35ea1e98f65253fc5dad0313878/pkg/sql/parser/indexed_vars.go#L198)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I thought this destruction would be a good idea, but a test fails. Is this expected? :S 
```
=== RUN   TestLogic/testdata/explain_types
--- new user: root
--- queries start here
panic: indexed var must be bound to a container before type resolution [recovered]
	panic: EXPLAIN (TYPES,NOEXPAND) SELECT 2*COUNT(k) as z, v FROM t WHERE v>123 GROUP BY v HAVING v<2: indexed var must be bound to a container before type resolution
```
</blockquote></details>

This may or may not be a bug, I don't know without investigating.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12851)*

**Comment by knz** [comment]
As we discussed the current failure is currently a design shortcoming of groupNode (and perhaps windowNode). Perhaps we should revisit this when #12525 is fixed.

**Comment by andreimatei** [comment]
Removed the sanity check and added a TODO

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12851#-:-KbCsGJUfxamA5tZuF7a:b-dju4yk)*

**Comment by knz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12851#-:-KbF6xitvLxWRn3Yyyh9:bnfp4nl)*

**Pull request merged**
