### PR TITLE
sql, opt: add AvgSize stat to scan row cost and session setting to enable/disable the old cost methodology

### PR DESCRIPTION
**Pull request by rharding6373**
sql: add session setting for scan costing methodology
    
In this PR we add a session setting to gate usage of an upcoming feature
in which the optimizer will use `AvgSize`, the average column size, from
table stats to cost scans and index joins. When enabled, the optimizer
will revert to the old default method of costing scans, where each
column is treated as the same size. By default, this setting will be
off.

Informs: #72332
    
Release note: None

opt: add AvgSize to scan row cost
    
Before this change, the optimizer cost scans per row regardless of the
size of the columns comprising the row. This fails to account for time
to read or transport a large number of bytes over the network. It can
also lead to undesirable plans when there are multiple options for scans
or joins that read directly from tables.
    
For example, let's say we have the following table with secondary
indexes, and the following query.
    
```
CREATE TABLE t (
      k INT PRIMARY KEY,
      x INT,
      y INT,
      z INT,
      j JSONB,
      INDEX xj (x, j),
      INDEX xy (x, y));
    
SELECT k, x, z FROM t where x > 3;
```
    
Before this change, the optimizer may choose to scan index xj and
perform an index join, even if the average column size of j (and
therefore the number of bytes scanned reading index xj) is much
greater than the average column size of y (and therefore the number
of bytes scanned reading index xy).
    
This change utilizes the `avg_size` table statistic to cost scans and
relevant joins relative to the average column size of the columns
being scanned. If the table does not have an average size statistic
available for a column, the default value of 4 bytes results in the same
cost as before this change.
    
Informs: #72332

Release note (sql change): Modifies query cost based on the `avg_size`
table statistic, which may change query plans. This is gated by the
session setting `cost_scans_with_default_col_size`, and can be disabled by
setting it to true via `SET cost_scans_with_default_col_size=true`.

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
This is ready for review now. The first commit is #74251 so doesn't need a review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-:-MtKzhs2-J8GHT1F6Vy1:b-8ofb0q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 1371 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-MtL-McT4fA-6o9nAzDp:-MtL-McT4fA-6o9nAzDq:b-65nqkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e817a989c6bcdb46642aef1b23e9adc001702546/pkg/sql/opt/xform/coster.go#L1371)):*
> ```Go
> 		}
> 		colSet := opt.MakeColSet(colID)
> 		colStat, ok := c.mem.RequestColStatTable(tabID, colSet)
> ```

Wanted to leave a note about this change. I was going to go through stats builder via `mem.RequestColStat` like `getOrderingColStats` does, but ran into the problems that 1) stats builder ends up only returning the col stats for the normalized expression, which isn't actually equivalent for our purposes, and 2) index join omits some of the lookup columns even when specifically requested. This seemed like a cleaner way to get col stats directly from table stats, but doesn't cache col stats with the expression and led to tweaking some opt tester tests. Let me know if there are any issues with this method that I haven't identified.

**Review by rytaft — COMMENTED** [review]
Sorry for the delay!

> Reviewed 6 of 78 files at r1, 2 of 87 files at r3, 2 of 96 files at r4, 64 of 102 files at r7, 38 of 38 files at r10, 13 of 13 files at r11, 11 of 11 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-:-Mtn9LwKCfWfJxoGcW4M:b2c5wy4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[-- commits, line 79 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn2huh1o9spXWEcGtV):*
I think you'll just want to mention the session setting `cost_scans_with_default_col_size`
___
*[pkg/sql/exec_util.go, line 701 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn30sz9mA0NaQIqx_j:-Mtn30t-1tjHu4_FnIk8:bja0au4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2f6004d862798af606e1a94819e83f9deb2894/pkg/sql/exec_util.go#L701)):*
> ```Go
> ).WithPublic()
> 
> var costScansWithDefaultColSize = settings.RegisterBoolSetting(
> ```

I think we're generally not bothering with these cluster defaults anymore, since we're adding infrastructure for setting per-role or per-db defaults for session settings, which makes these cluster settings unnecessary.
___
*[pkg/sql/opt/memo/memo.go, line 211 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn5E1M6gCSMIUv6VDD:-Mtn5E1N0Wq25Cobtff-:bjuouou) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/memo/memo.go#L211)):*
> ```Go
> // after optimization is complete with the real computed cost, not the perturbed
> // cost.
> func (m *Memo) ResetLogProps(evalCtx *tree.EvalContext) {
> ```

why was this necessary?
___
*[pkg/sql/opt/xform/coster.go, line 1371 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-MtL-McT4fA-6o9nAzDp:-Mtn6vYtAJWFZzgIhYcJ:b-jxfajh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e817a989c6bcdb46642aef1b23e9adc001702546/pkg/sql/opt/xform/coster.go#L1371)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Wanted to leave a note about this change. I was going to go through stats builder via `mem.RequestColStat` like `getOrderingColStats` does, but ran into the problems that 1) stats builder ends up only returning the col stats for the normalized expression, which isn't actually equivalent for our purposes, and 2) index join omits some of the lookup columns even when specifically requested. This seemed like a cleaner way to get col stats directly from table stats, but doesn't cache col stats with the expression and led to tweaking some opt tester tests. Let me know if there are any issues with this method that I haven't identified.
</blockquote></details>

Seems fine to me
___
*[pkg/sql/opt/xform/coster.go, line 685 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn5sKG2ySuRq1JZ_iX:-Mtn5sKG2ySuRq1JZ_iY:b2verpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/xform/coster.go#L685)):*
> ```Go
> 	// Each lookup might retrieve many rows; add the IO cost of retrieving the
> 	// rows (relevant when we expect many resulting rows per lookup) and the CPU
> 	// cost of emitting the rows.
> ```

nit: this comment now sounds specific to lookup joins, not scans
___
*[pkg/sql/opt/xform/coster.go, line 686 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn5_A0CJU3C_-ylOCZ:-Mtn5_A0CJU3C_-ylOC_:b-vit1sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/xform/coster.go#L686)):*
> ```Go
> 	// rows (relevant when we expect many resulting rows per lookup) and the CPU
> 	// cost of emitting the rows.
> 	perRowCost := c.rowScanCost(memo.RelExpr(scan), scan.Table, scan.Index, scan.Cols, stats)
> ```

I don't think you should need to perform this cast
___
*[pkg/sql/opt/xform/coster.go, line 1384 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn7DUaDVbvxYoufW49:-Mtn7DUaDVbvxYoufW4A:bwle03u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/xform/coster.go#L1384)):*
> ```Go
> 		colStat, ok := c.mem.RequestColStatTable(tabID, colSet)
> 		if !ok {
> 			panic(errors.AssertionFailedf("could not request the stats for ColSet %v", colSet))
> ```

I'd use`%s` and `colSet.String()` here, since I don't think the default output will be useful
___
*[pkg/sql/opt/xform/coster.go, line 1392 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn7YPk7MLS0FlguWfh:-Mtn7YPk7MLS0FlguWfi:b-kappab) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/xform/coster.go#L1392)):*
> ```Go
> 			networkCostFactor = 2
> 		}
> 		cost += memo.Cost(colStat.AvgSize/4) * costFactor * networkCostFactor
> ```

why are you dividing by 4? Maybe add a comment

**Review by rharding6373 — COMMENTED** [review]
Thanks for the review! RFAL -- delayed due to trying (slowly) to get the stats builder changes merged, sorry about that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-:-MuIOyUgDJVdBQR2Gutb:bvy5pe9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[-- commits, line 79 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn2huh1o9spXWEcGtV):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you'll just want to mention the session setting `cost_scans_with_default_col_size`
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 701 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn30sz9mA0NaQIqx_j:-MuIIzid2WjHO-lI9_5L:b-9u0vyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2f6004d862798af606e1a94819e83f9deb2894/pkg/sql/exec_util.go#L701)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think we're generally not bothering with these cluster defaults anymore, since we're adding infrastructure for setting per-role or per-db defaults for session settings, which makes these cluster settings unnecessary.
</blockquote></details>

I tried to refactor `PrintSessionSettings` in `pkg/sql/explain_bundle.go` to use the `GlobalDefault()` from `vars.go` instead of the cluster default `exec_util.go` but was not successful in the short time I put in because getting ahold of a `settings.Values` appears non-trivial. `PrintSessionSettings` seems like a minor reason to keep this around, but I think that may be a prerequisite before removing this if having the cluster default isn't actively bad. Unless you have another idea of how to get around this?
___
*[pkg/sql/opt/memo/memo.go, line 211 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn5E1M6gCSMIUv6VDD:-MuIKCBQAOGyvMavcblq:b-vmcgvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/memo/memo.go#L211)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why was this necessary?
</blockquote></details>

There is a class of opt tests, ones that use `perturb-cost`, that cause `Optimize()` to be called a second time even though the optimizer was cleaned up after the first `Optimize()` finished. This is a problem for the way we're currently getting column stats for `rowScanCost` in the coster, because when the optimizer is cleaned up it deletes the memo's `logPropsBuilder`. Other parts of the optimizer coster get around this by caching the stats with the memo group, so the second pass doesn't actually need a `logPropsBuilder` to get the stats. The current implementation of `rowScanCost` doesn't cache the stats in a memo group, we get the stats directly from the table stats.

The second pass through the optimizer is only done in testing, so this hack seemed like a straightforward workaround.
___
*[pkg/sql/opt/xform/coster.go, line 685 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn5sKG2ySuRq1JZ_iX:-MuIMGvj9z3iNee0Iteq:b7a77v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/xform/coster.go#L685)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: this comment now sounds specific to lookup joins, not scans
</blockquote></details>

Copy paste issue. Fixed.
___
*[pkg/sql/opt/xform/coster.go, line 686 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn5_A0CJU3C_-ylOCZ:-MuIMtb3DkU2CeB91D9e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/xform/coster.go#L686)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think you should need to perform this cast
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 1384 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn7DUaDVbvxYoufW49:-MuIN-mB6II5Z1a-bGSZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/xform/coster.go#L1384)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'd use`%s` and `colSet.String()` here, since I don't think the default output will be useful
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/coster.go, line 1392 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn7YPk7MLS0FlguWfh:-MuIOL7OCZi1d4S5roVy:b-kzqss0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/xform/coster.go#L1392)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why are you dividing by 4? Maybe add a comment
</blockquote></details>

Added a comment, PTAL.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 109 of 109 files at r13, 10 of 10 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-:-MuNB6od0kNxkjSmjqij:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[-- commits, line 58 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-MuM4Lh-EE7SaZQh9pnS):*
nit: there are two different settings: the session setting, and the cluster setting, which serves as the default value for the session setting. I'd just focus on the session setting, especially since we'll get rid of the cluster setting at some point.
___
*[pkg/sql/exec_util.go, line 701 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn30sz9mA0NaQIqx_j:-MuM4gMs9oOjV4HnLjXd:b-7hlh5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2f6004d862798af606e1a94819e83f9deb2894/pkg/sql/exec_util.go#L701)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I tried to refactor `PrintSessionSettings` in `pkg/sql/explain_bundle.go` to use the `GlobalDefault()` from `vars.go` instead of the cluster default `exec_util.go` but was not successful in the short time I put in because getting ahold of a `settings.Values` appears non-trivial. `PrintSessionSettings` seems like a minor reason to keep this around, but I think that may be a prerequisite before removing this if having the cluster default isn't actively bad. Unless you have another idea of how to get around this?
</blockquote></details>

I see -- seems fine to leave it, then. We'll need to fix the bundle logic at some point, but I agree that it's not worth doing in this PR.
___
*[pkg/sql/opt/memo/memo.go, line 211 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-Mtn5E1M6gCSMIUv6VDD:-MuM5c6IEYANyMy0e8PQ:bflyw1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff37aec2150797bff5ceb2aa60cf09db301a009/pkg/sql/opt/memo/memo.go#L211)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

There is a class of opt tests, ones that use `perturb-cost`, that cause `Optimize()` to be called a second time even though the optimizer was cleaned up after the first `Optimize()` finished. This is a problem for the way we're currently getting column stats for `rowScanCost` in the coster, because when the optimizer is cleaned up it deletes the memo's `logPropsBuilder`. Other parts of the optimizer coster get around this by caching the stats with the memo group, so the second pass doesn't actually need a `logPropsBuilder` to get the stats. The current implementation of `rowScanCost` doesn't cache the stats in a memo group, we get the stats directly from the table stats.

The second pass through the optimizer is only done in testing, so this hack seemed like a straightforward workaround.
</blockquote></details>

makes sense - thanks for the explanation!

**Comment by rytaft** [comment]
nit: update the PR title to something that includes the package name(s) and describes the whole PR

**Comment by rharding6373** [comment]
TFTR!

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74551)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[-- commits, line 58 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/74551#-MuM4Lh-EE7SaZQh9pnS):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: there are two different settings: the session setting, and the cluster setting, which serves as the default value for the session setting. I'd just focus on the session setting, especially since we'll get rid of the cluster setting at some point.
</blockquote></details>

Done.

**Pull request merged**
