### PR TITLE
sql: move constant detection from sortNode to renderNode

### LINKED ISSUE #13476: sql: move constant detection for ordering to renderNode
`planNode.Ordering()` gives us information about the columns in the plan that need to be sorted using selected indexes. However, there are many cases where optimizations are interested in the ordering properties of the data source, and aren't interested in which indexes were scanned or which fields were sorted to achieve this ordering. 

The distinction is subtle but important for cases like `SELECT 1 ORDER BY 1`. Here we know that the first column can be considered sorted in both an ascending and descending order. However, even with the `ORDER BY` clause, [sort.go](https://github.com/cockroachdb/cockroach/blob/81e8f13b70b7e95092b53f65dadda78cc847891c/pkg/sql/sort.go#L181) notices that no sorting is needed and elides the entry into its `plan.Ordering() orderingInfo `. Another example is `SELECT pk, secondary FROM t ORDER BY 1, 2`. Because we know the pk will be unique, we remove the second ordering from `plan.Ordering()`. It would be useful in a number of places to have something like `plan.OrderingProperties()`, targeted at consumers of the `planNode` to communicate which ordering conditions can be relied upon. Ideally, this would fit into our many uses of [`computeOrderingMatch`](https://github.com/cockroachdb/cockroach/blob/81e8f13b70b7e95092b53f65dadda78cc847891c/pkg/sql/ordering.go#L134) and improve a number of statement types at once.

This might also prompt the introduction of a third ordering direction: bidirectional. This would be useful for constants that can be considered ordered in both an ascending and descending direction.

### PR DESCRIPTION
**Pull request by RaduBerinde**
Move the one-off constant detection code in sortNode to
renderNode.computeOrdering, where it is more generally useful. The sortNode can
use this information to avoid sorting just like before.

Fixes #13476.

### CODE REVIEW

**Comment by knz** [comment]
I see the benefit of this change, but then why not go the mile further and ensure sortNode is still entirely dropped if there's no sorting needed any more?  See my comments below.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/order_by, line 285 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15954#-KkKxPOpcqaYnF4EGpCN:-KkKxPOqupzcEA1cpNBc:bs066y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ec776c021d025b92725357f828bdf6f0cf436d/pkg/sql/testdata/logic_test/order_by#L285)):*
> ```
> ----
> 0  nosort
> 0          order  +"1 + 2"
> ```

Can you double check this? Why not ensure the sort node is eliminated here?

---

*[pkg/sql/testdata/logic_test/order_by, line 295 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15954#-KkKxStfnu4JXmvJn_pW:-KkKxStfnu4JXmvJn_pX:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ec776c021d025b92725357f828bdf6f0cf436d/pkg/sql/testdata/logic_test/order_by#L295)):*
> ```
> ----
> 0  nosort
> 0          order  +"length('abc')"
> ```

Ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15954#-:-KkKx3kiPwRJ2vG7rr07:b-56sfut)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/testdata/logic_test/order_by, line 285 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15954#-KkKxPOpcqaYnF4EGpCN:-KkLTCqS0HisVkKLwNyt:btx8ke0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ec776c021d025b92725357f828bdf6f0cf436d/pkg/sql/testdata/logic_test/order_by#L285)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you double check this? Why not ensure the sort node is eliminated here?
</blockquote></details>

We are not sorting, just like before. A "nosort" node is effectively just a projection - we need it to get rid of the 1+2 column. Same below.  I see where you're coming from though - we could get rid of the render altogether - but this can't easily be done in general (because of distsql, in cases like `SELECT v FROM k ORDER BY k` we need to leave enough information so distsql knows it needs to maintain ordering by `k`; if we remove the render and nosort node, the plan will look identical to `SELECT v FROM k`).

I added a testcase where it goes away completely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15954)*

**Comment by knz** [comment]
Thanks for explaining. I will let this one sleep since "ORDER BY constant" is unlikely to be a big deal in practice (if ever found in prod). However, I would recommend that we think about a way to carry the ordering information in the distsql plan over to where it's needed. What is happening here is that we are burdening/polluting flows with constant values that are then discarded before the result is produced. This seems unnecessarily wasteful to me. Perhaps a followup issue?

:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/order_by, line 285 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15954#-KkKxPOpcqaYnF4EGpCN:-KkLYoTDpTOnkpiZV2az:baq8nw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ec776c021d025b92725357f828bdf6f0cf436d/pkg/sql/testdata/logic_test/order_by#L285)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We are not sorting, just like before. A "nosort" node is effectively just a projection - we need it to get rid of the 1+2 column. Same below.  I see where you're coming from though - we could get rid of the render altogether - but this can't easily be done in general (because of distsql, in cases like `SELECT v FROM k ORDER BY k` we need to leave enough information so distsql knows it needs to maintain ordering by `k`; if we remove the render and nosort node, the plan will look identical to `SELECT v FROM k`).

I added a testcase where it goes away completely.
</blockquote></details>

I had seen from other tests where it "goes away completely" already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15954#-:-KkLYyMYli1RY0gP9Hiz:b-od13qp)*

**Comment by RaduBerinde** [comment]
Note that we are not introducing this behavior in this change. This change is still a net win IMO. What you are proposing is a larger change with more far reaching consequences, it shouldn't be tied up to this PR (feel free to file an issue).

Note that in this case, because distsql doesn't actually have to do anything special to maintain the ordering of an exact match column, the render will just be omitted (this happens automatically when we apply a projection on top of a rendering).

This is the plan for `EXPLAIN (DISTSQL) SELECT * FROM t ORDER BY 1+2`:

https://cockroachdb.github.io/distsqlplan/decode.html?eJzMkL9qwzAQh_c-RfjNKlj2pslrlrSYbsWDah3B4OjESYaW4HcvlobUwS3t1vH-fPfd3RWeHZ3shSLMKzQUGvQKQXigGFnWdGk6uneYSmH0YU5rulcYWAjmijSmiWDwYt8m6sg6Eig4Snac8uAg48XKR5ug0JF3JObQ6kNbH9oG_aLAc7qNjcmeCUYv6hv1zTh7FkdCbuPrl53lTvzI4a5tX1xvxPp_3Lyj7igG9pF-dVS1_oTcmcoDI88y0LPwkDUlfMpcTjiKqVR1CY4-l_KCX2H9I9xs4Ooerv9k7peHzwAAAP__TETi6A==

I'd say that if we want to simplify these nosorts for classic SQL as well, the easiest thing would be to have another traversal that is only applied if we're not using the plan tree for distsql. (In general, a traversal which applies optimizations that are only valid when rows are sequentially processed).

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15954#-:-KkL_YpUZgzuTJqVGFou:b-t37esz)*

**Comment by knz** [comment]
As I wrote in my previous comment this is indeed out of scope for this PR.

**Pull request merged**
