### PR TITLE
workload/tpcc: add audit check 9.2.2.5.3

### PR DESCRIPTION
**Pull request by solongordon**
Added an audit check for remote order-lines frequency and distribution.
Also fixed a minor related bug where the local warehouse might be
randomly chosen when a remote one was called for.

Release note: None

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/workload/tpcc/audit.go, line 156 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24219#-L8YgBblYrue89-3LaCb:-L8YgBblYrue89-3LaCc:blt0r2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a6eb120148fb34d998deb0d9729db9eb25dcac/pkg/workload/tpcc/audit.go#L156)):*
> ```Go
> 	// expectation.
> 	if remoteOrderLines < 15*uint64(a.warehouses) {
> 		// Not enough remote order-lines to expect all warehouses to be used.
> ```

Print a warning? this is sufficiently unintuitive (and we're doing fairly short runs for our internal iterations) that we should have a reminder when this audit check was not done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24219)*

**Comment by solongordon** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/workload/tpcc/audit.go, line 156 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24219#-L8YgBblYrue89-3LaCb:-L8Z1UtpRKeYDHCZRVIK:b-a54ept) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a6eb120148fb34d998deb0d9729db9eb25dcac/pkg/workload/tpcc/audit.go#L156)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Print a warning? this is sufficiently unintuitive (and we're doing fairly short runs for our internal iterations) that we should have a reminder when this audit check was not done.
</blockquote></details>

Good call. @jordanlewis already requested in a previous PR that we print out each check which is run even if it passes. So I added a bit of logic to do this and also to indicate if it was skipped for some reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24219)*

**Comment by arjunravinarayan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/workload/tpcc/audit.go, line 56 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24219#-L8Z2BE33cwltKKLsUUM:-L8Z2BE33cwltKKLsUUN:bjcvxrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07b26bc6a86676fb9b53d946a2bf859ac6e8a9e/pkg/workload/tpcc/audit.go#L56)):*
> ```Go
> 
> type auditResult struct {
> 	status      string // PASS, FAIL, or SKIP
> ```

make it an enum, rather than a string.

```
const (
auditPass = iota
auditFail
auditSkip
)
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24219)*

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/workload/tpcc/audit.go, line 56 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24219#-L8Z2BE33cwltKKLsUUM:-L8Z37fx30rN3fwZvRXJ:b3k6wfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07b26bc6a86676fb9b53d946a2bf859ac6e8a9e/pkg/workload/tpcc/audit.go#L56)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

make it an enum, rather than a string.

```
const (
auditPass = iota
auditFail
auditSkip
)
```
</blockquote></details>

In retrospect, don't bother. You'll have to stringify it before printing anyway.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24219#-:-L8Z3BiU194essGMOOF8:bnfp4nl)*

**Pull request merged**
