### PR TITLE
workload: rework split concurrency to avoid deadlock

### PR DESCRIPTION
**Pull request by nvb**
The previous approach to pre-splitting in workload had two
different ways that it could deadlock:
- any send on `errCh` except the first would block indefinitely
- filling `splitCh` could deadlock because it did not have
  a sufficiently provisioned capacity

I saw this happen in practice when running large roachtests.
I'm not sure which deadlock I actually saw, but this change
resolves the issue.

EDIT: running the roachtest again with this change confirmed
that I was seeing the first deadlock. Linux hits file descriptor
limits too quickly these days.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

Why is a roachtest causing the file descriptor limit to be hit? We could have roachprod automatically bump the file descriptor limit. Looking just now I see it only does so for the unused `SyncedCluster.RunLoad`. Easy enough to bump the file descriptor limit for all processes run by `roachprod`.

I wonder if this deadlock was the cause of https://github.com/cockroachdb/cockroach/issues/28727.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29029#-:-LKg_mJw1dE_ARCJ_KzZ:b-qcjlrf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by nvanbenschoten** [comment]
> Why is a roachtest causing the file descriptor limit to be hit? 

Because I ramped up its concurrency. 

> We could have roachprod automatically bump the file descriptor limit. Looking just now I see it only does so for the unused SyncedCluster.RunLoad. Easy enough to bump the file descriptor limit for all processes run by roachprod.

That's a good idea. Any roachtests that run a substantial amount of load against a cluster will hit this. We already have in the tpcc tests.

> I wonder if this deadlock was the cause of #28727.

I wanted to ask you about that. There are a few roachtest flakes that you've investigated that looked like they could be related, but their artifacts were gone so I couldn't tell if they got stuck during the pre-split phase. Are you aware of any that definitely did?

**Review by petermattis — COMMENTED** [review]
> I wanted to ask you about that. There are a few roachtest flakes that you've investigated that looked like they could be related, but their artifacts were gone so I couldn't tell if they got stuck during the pre-split phase. Are you aware of any that definitely did?

The `kv/splits/nodes=3` test is the only one I've seen that has blocked in the pre-split phase (that test only utilizes the pre-split phase). I'm going to close #28727 until we see a re-occurrence. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29029#-:-LKlIwSL6pfG-UNBPaFJ:bz1htag)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
