### PR TITLE
storage: remove range tree

### LINKED ISSUE #7495: storage: DRY {client_,}range_tree_test.go
Requested in #5839: these two files mostly test the same things at different levels - it'd be good to abstract over the backing storage and have a single test runner that exercises both.

Seems like a good starter task.

### PR DESCRIPTION
**Pull request by a6802739**
I don't know how to continue on the previous PR from https://github.com/cockroachdb/cockroach/pull/7639. so I propose a new pull request.
Closes #7495.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7692)

### CODE REVIEW

**Comment by a6802739** [comment]
@knz , could you merge two commit into one please? I could execute squash in my local environment. when I `git rebase -i 770dd82abec2469e952a8b363632403165698204`, after I edit and input `wq`, it reminds `Could not execute editor`

**Comment by knz** [comment]
Hello, I could do this however of course it is better if you can also learn how to do this in the future! 
Try setting the environment variable EDITOR to something you find easier to use; for example "nano".

**Comment by petermattis** [comment]
@BramGruneir Can you take a look at this?

**Comment by BramGruneir** [comment]
Hey songhao,

The code changes look good!  

Should be good to merge once the following are completed:
- Can you please squish the commits into one?
- The PR title should be `storage: remove range tree`
- Make sure the commit message (of the single squashed commit) contains the `closes #7495` line as well.

If you need help with any of the steps, jump on [gitter](https://gitter.im/cockroachdb/cockroach?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) and we'll be sure to help step you through the process.

**Comment by BramGruneir** [comment]
Reviewed 14 of 14 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7692)*

**Comment by BramGruneir** [comment]
Thanks so much for the help @a6802739!

**Pull request merged**
