### PR TITLE
workload/schemachange: add ALTER TYPE ... DROP VALUE

### LINKED ISSUE #59197: sql: add ALTER TYPE DROP VALUE to the randomized schema change tests
Followup to adding support for dropping enum values, once https://github.com/cockroachdb/cockroach/pull/58688 goes in. 

Jira issue: CRDB-3322

Epic CRDB-19168

### PR DESCRIPTION
**Pull request by arulajmani**
Closes #59197

Release note: None

### CODE REVIEW

**Review by otan — COMMENTED** [review]
LGTM, letting @ajwerner sign off!

**Review by ajwerner — COMMENTED** [review]
Huh, seems like this is going to get ugly when https://github.com/cockroachdb/cockroach/pull/62827 merges and if we added code to generate expressions which use enums, those are things we should do. Should we just buy into some set of "optional" commit errors which are fine if they happen and fine if they don't? I worry it will make the correctness checking exact and that that's a slipperly slope but the effort bar to adding things here is really high. I'm torn. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63328#-:-MXoJ8AZ2ocbszK5ML1K:b-ui9dun)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by arulajmani — COMMENTED** [review]
> I worry it will make the correctness checking exact and that that's a slipperly slope but the effort bar to adding things here is really high. 

I don't follow this, did you mean correctness checking _not_ exact?

I haven't had experience de-flaking this thing as you have, so maybe I'm naive, but I'd be much happier if we remain intentional about when and what errors we expect. I think that's what makes this thing powerful. At some level, if we're saying "enum drop validation may or may not fail", we're leaving an important aspect of this feature untested.

Looks like we can introspect `information_schema.columns` to see default expressions. Maybe all we need is some ugly string parsing. (side note: we might have to do it for all tables in the database if we don't want to cheat and look in the descriptor). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63328#-:-MXrAv08B69D1pnIYAtY:b-o1liop)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by arulajmani** [comment]
Friendly ping @ajwerner

**Review by ajwerner — COMMENTED** [review]
Ack, sorry, this test is presently flakey and skipped which has led to my not really giving this any attention. 

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63328#-:-MZJR-Y78nWH0WLHRnc7:br7vlbx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Pull request closed without merging**
