### PR TITLE
roachtest: testing load based splitting under uniform distribution

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Adds a roachtest testing behavior of LBS when run with KV under uniform
distribution. We expect to see the number of ranges increase as LBS is
enabled. It does seem to take a long time and that concerns me. 
I don't know how long a roachtest like this should run @nvanbenschoten.
I also suspect that the next few roachtests I'll write for LBS right here will be
similar to this one so would like to know now if this is okay.

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31987)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/load_split.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55SMU8DYG92dDCwNz:-LQ55SMU8DYG92dDCwO-:b-39rdpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L34)):*
> ```Go
> 	const numNodes = 3
> 
> 	r.Add(testSpec{
> ```

This needs a `MinVersion`.
___
*[pkg/cmd/roachtest/load_split.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ54QVR3rRzxglV-egd:-LQ54QVR3rRzxglV-ege:b-dspibs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L35)):*
> ```Go
> 
> 	r.Add(testSpec{
> 		Name:    fmt.Sprintf("range_split/by_load/uniform/nodes=%d", numNodes),
> ```

Let's combine this naming scheme with `largerange/splits/size=10GiB,nodes=3`. We can name this file `split.go`, call this test `splits/load/uniform/nodes=%d`, call that test `splits/largerange/size=%s,nodes=%d`, and move that test into this file (in a separate commit).
___
*[pkg/cmd/roachtest/load_split.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ53zRu6VbR_AluYB1N:-LQ53zRu6VbR_AluYB1O:bo5xkp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L37)):*
> ```Go
> 		Name:    fmt.Sprintf("range_split/by_load/uniform/nodes=%d", numNodes),
> 		Nodes:   nodes(numNodes),
> 		Timeout: 5 * time.Hour,
> ```

You shouldn't need to specify a timeout. The default is fine.
___
*[pkg/cmd/roachtest/load_split.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55HDQ7Kw-nSt9a-Us:-LQ55HDQ7Kw-nSt9a-Ut:b-nwo9fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L49)):*
> ```
> QPSThreshold
> ```

lower case name
___
*[pkg/cmd/roachtest/load_split.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55gKEC3PzjYImgVeX:-LQ55gKEC3PzjYImgVeY:bvux8ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L52)):*
> ```Go
> 
> 	c.Put(ctx, cockroach, "./cockroach", c.All())
> 	c.Put(ctx, workload, "./workload", c.All())
> ```

Do you need workload on all nodes?
___
*[pkg/cmd/roachtest/load_split.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55V_I4_U-YXxB4P9B:-LQ55V_JB77t04M62IPZ:bdmlij7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L71)):*
> ```Go
> 			if err != nil && strings.Contains(err.Error(), "syntax error") {
> 				// Pre-2.1 was EXPERIMENTAL.
> 				// TODO(knz): Remove this in 2.2.
> ```

We don't need this once we have a min version.
___
*[pkg/cmd/roachtest/load_split.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55_zB0-nUAiJFcMDp:-LQ55_zB0-nUAiJFcMDq:bi9ks19) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L79)):*
> ```Go
> 			}
> 		}
> 		// Set the range size to a huge size so we don't get splits the occur
> ```

`s/the/that/`
___
*[pkg/cmd/roachtest/load_split.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55oVR2uE5OjmDH7B0:-LQ55oVR2uE5OjmDH7B1:b-vfrr93) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L101)):*
> ```Go
> 
> 		// Set the QPS threshold for load based splitting before turning it on.
> 		if _, err := db.ExecContext(ctx, fmt.Sprintf("SET CLUSTER SETTING kv.range_split.load_QPS_threshold = %d",
> ```

`s/load_QPS_threshold/load_qps_threshold/`
___
*[pkg/cmd/roachtest/load_split.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55tfU9Fbc9tGgYynG:-LQ55tfU9Fbc9tGgYynH:bb7ibks) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L110)):*
> ```Go
> 		}
> 		// After load based splitting is turned on, from experiments
> 		// its clear than at least 10 splits will happen. We could
> ```

it's
___
*[pkg/cmd/roachtest/load_split.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55y2pDV1PXvVGe00R:-LQ55y2pDV1PXvVGe00S:bmeak45) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L111)):*
> ```
> Used 10
> ```

No you didn't.
___
*[pkg/cmd/roachtest/load_split.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ563WSBGZw5I14gATC:-LQ563WSBGZw5I14gATD:bkk1mn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L132)):*
> ```Go
> 			float64((split.DurationThreshold / time.Second))))
> 		c.Run(ctx, c.Node(1), fmt.Sprintf("./workload run kv "+
> 			"--init --concurrency=%d --read-percent=%d {pgurl:1-%d} --duration='%ds'", concurrency,
> ```

`s/%ds/%s`
___
*[pkg/cmd/roachtest/registry.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ53s6X-_HhhpDzXNjq:-LQ53s6X-_HhhpDzXNjr:b-49qhe7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/registry.go#L59)):*
> ```Go
> 	registerSyncTest(r)
> 	registerTPCC(r)
> 	registerUniformLoadSplits(r)
> ```

s/`registerUniformLoadSplits`/`registerLoadSplits`/
___
*[pkg/storage/split/split.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ53biKAmhUnscleYVC:-LQ53biKAmhUnscleYVD:b-g4eqbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/storage/split/split.go#L52)):*
> ```Go
> 	// DurationThreshold is the minimum duration of time the split finder
> 	// will record a range for, before being ready for a split.
> 	DurationThreshold          = 10 * time.Second // 10s
> ```

Let's give this a real name. "duration threshold" conveys just about no information :smiley:

**Comment by nvanbenschoten** [comment]
> I don't know how long a roachtest like this should run @nvanbenschoten.

Talked offline. This will only take a few minutes, which is short by roachtest standards.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31987)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/load_split.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55SMU8DYG92dDCwNz:-LQB-g-F2xULD1gnlvIj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This needs a `MinVersion`.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ54QVR3rRzxglV-egd:-LQArrbP-b-F06AUSEy_:bsub0pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's combine this naming scheme with `largerange/splits/size=10GiB,nodes=3`. We can name this file `split.go`, call this test `splits/load/uniform/nodes=%d`, call that test `splits/largerange/size=%s,nodes=%d`, and move that test into this file (in a separate commit).
</blockquote></details>

That's a good note. I'll add a separate commit doing that after cleaning up this roachtest.
___
*[pkg/cmd/roachtest/load_split.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ53zRu6VbR_AluYB1N:-LQApBYq3DxrRUQOiWFA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You shouldn't need to specify a timeout. The default is fine.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55HDQ7Kw-nSt9a-Us:-LQApJCWAl8kMkIyRJa7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L49)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> QPSThreshold
> ```

lower case name
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55gKEC3PzjYImgVeX:-LQApKibEjZn2GJgQ5hl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L52)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you need workload on all nodes?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55V_I4_U-YXxB4P9B:-LQAps16EJcWl5vAEofp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L71)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We don't need this once we have a min version.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55_zB0-nUAiJFcMDp:-LQAq4eGCwqGhgOOyyLj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L79)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/the/that/`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55oVR2uE5OjmDH7B0:-LQAqB53BfbA75jDCToR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L101)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/load_QPS_threshold/load_qps_threshold/`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55tfU9Fbc9tGgYynG:-LQAqGVTAg0wafYEhi3p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L110)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

it's
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ55y2pDV1PXvVGe00R:-LQAqGxAEFIveNgVseBb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L111)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> Used 10
> ```

No you didn't.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ563WSBGZw5I14gATC:-LQAqvN2-OzHQh3Mf4lZ:ban87wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/%ds/%s`
</blockquote></details>

I think `%ds` is right so we format the duration as `50s` for example.
___
*[pkg/cmd/roachtest/registry.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ53s6X-_HhhpDzXNjq:-LQArBw93xIU0rsdXbGn:b692mnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/registry.go#L59)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/`registerUniformLoadSplits`/`registerLoadSplits`/
</blockquote></details>

Kept this as is because I intend to add a few more load split roachtests for different distributions.
___
*[pkg/storage/split/split.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ53biKAmhUnscleYVC:-LQAro7w5hADX1Z_lo7R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/storage/split/split.go#L52)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's give this a real name. "duration threshold" conveys just about no information :smiley: 
</blockquote></details>

Done.

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31987)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/load_split.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ54QVR3rRzxglV-egd:-LQF2Ki39iVl-9UaHshu:b-nu5klp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L35)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

That's a good note. I'll add a separate commit doing that after cleaning up this roachtest.
</blockquote></details>

You can add the commit to this PR. I wouldn't merge a test name that we're immediately going to change.
___
*[pkg/cmd/roachtest/load_split.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ563WSBGZw5I14gATC:-LQF2dmXA-i1oAXkjJHu:b5y3ihd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L132)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

I think `%ds` is right so we format the duration as `50s` for example.
</blockquote></details>

`%s` will also do this because `time.Duration` has a `String` method.
___
*[pkg/cmd/roachtest/load_split.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQF2QBJ082jxQdCDfua:-LQF2QBJ082jxQdCDfub:b8p4mxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa89850291ec08db98c688748c84c6ee497f61e/pkg/cmd/roachtest/load_split.go#L34)):*
> ```Go
> 	r.Add(testSpec{
> 		Name:       fmt.Sprintf("range_split/by_load/uniform/nodes=%d", numNodes),
> 		MinVersion: `v2.1-2`,
> ```

Can you use `cluster.VersionLoadSplits` directly?
___
*[pkg/cmd/roachtest/registry.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ53s6X-_HhhpDzXNjq:-LQF2k-o4QonLmLbQe83:blijxns) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/registry.go#L59)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

Kept this as is because I intend to add a few more load split roachtests for different distributions.
</blockquote></details>

Right, but we don't need different registration functions for them. For instance, `registerTPCC` registers all tpcc roachtests.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31987)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/registry.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ53s6X-_HhhpDzXNjq:-LQFZzIX0FrZScn13BY9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/registry.go#L59)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Right, but we don't need different registration functions for them. For instance, `registerTPCC` registers all tpcc roachtests.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ54QVR3rRzxglV-egd:-LQFfQsZ3L9M7E8z69Ib:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You can add the commit to this PR. I wouldn't merge a test name that we're immediately going to change.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ563WSBGZw5I14gATC:-LQFZ7nF2iat0tDW4DXp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`%s` will also do this because `time.Duration` has a `String` method.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/load_split.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQF2QBJ082jxQdCDfua:-LQFZ4m3EcUv_eHV7dtj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa89850291ec08db98c688748c84c6ee497f61e/pkg/cmd/roachtest/load_split.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can you use `cluster.VersionLoadSplits` directly?
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm: mod the confusion about `waitDuration`.

> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-:-LQFuDI31pbjAouSf6yd:b-e1ox82)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/load_split.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ563WSBGZw5I14gATC:-LQFtWXyBBpSfduIlSjD:b-mp0jen) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L132)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This still seems too complicated and that might be stemming from the addition of `expSplits`. `waitDuration` should be a `time.Duration` that factors in how long you expect `expSplits` to need. Then you can just pass it directly as an argument to `fmt.Sprintf`.

**Review by ridwanmsharif — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-:-LQFy8Yh6Sx5HK6TxMlx:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/load_split.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31987#-LQ563WSBGZw5I14gATC:-LQFy6AK916hLOoT7Z9T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24a01b842d143dfc73fd8ae656e881db31893b5/pkg/cmd/roachtest/load_split.go#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This still seems too complicated and that might be stemming from the addition of `expSplits`. `waitDuration` should be a `time.Duration` that factors in how long you expect `expSplits` to need. Then you can just pass it directly as an argument to `fmt.Sprintf`.
</blockquote></details>

Done.

**Pull request merged**
