### PR TITLE
settings,sqlbase: some pre-2.1 cleanup

### PR DESCRIPTION
**Pull request by benesch**
See commit messages for details.

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM however-

Please extend the 2nd commit message to remind the reader it's already not possible to connect a 2.1 node to a 1.1 cluster because there is an initial version check during the join.

Please extend the 3rd commit message to explain what IsVersionMin returns when the cluster version has not been initialized yet: I understand there's a race condition, but I want confidence that there's no window of time where the user can create a bit array before the node realizes it's still in "2.0 mode" after all.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30533#-:-LN9nsyqC1auy_SFxypj:b-4ubuji)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by benesch** [comment]
> Please extend the 3rd commit message to explain what IsVersionMin returns when the cluster version has not been initialized yet: I understand there's a race condition, but I want confidence that there's no window of time where the user can create a bit array before the node realizes it's still in "2.0 mode" after all.

Welp, the third commit causes all sorts of "Version() called before having been initialized" panics. I'm just going to merge without that commit and file an issue about fixing this race.

**Comment by benesch** [comment]
bors r=knz

**Comment by knz** [comment]
gosh this must be backported as @bdarnell  is introducing the new 2.1 version

**Comment by benesch** [comment]
It doesn't backport cleanly, unfortunately. I'm inclined to just not bother. There's no harm in having the extra checks in v2.1.

**Pull request merged**
