### PR TITLE
workflow: Building protobuf-client for Cluster UI

### PR DESCRIPTION
**Pull request by nathanstilwell**
On dry-run publishing, there is an npm life-cycle script that will run (`prepublishOnly`). This script will clean and rebuild Cluster-ui using the Typscript compiler for type generation and Webpack for the bundle. This is currently failing due to a dependence on @cockroachlabs/crdb-protobuf-client, which is has not explicitly built as a part of the workflow.

To resolve this issue, I am removing the `prepublishOnly` script as it was an additional build step that was implicitly run as a part of `npm publish`. Then I am adding a step to `Build Cluster UI` to build the  protobuf client with Bazel. Then I am copying the built files out of the bazel directory into the package directory and building the Cluster UI bundle with npm.

I have also added a "files" section to the package.json to managed the files that are added to the package when publishing. Previously the package would include everything in the directory filtered by the contents of `.npmignore`. Now the package will include "mandatory files" (`package.json` and `README.md`) and the files specified in the "files" array (`dist/` and `AUTHORS`). A diff was also taken of the produced package against the published package [on npm](https://www.npmjs.com/package/@cockroachlabs/cluster-ui/v/23.1.0-prerelease.2?activeTab=explore). In this example, `local` is the locally built Cluster UI `.tgz` package on master and `remote` is `@cockroachlabs/cluster-ui@23.1.0-prerelease.2` package. The difference in package.json is part of this pull request.

```
╔═══════════════════════════
║ code/test/cluster-ui-publish-test 
╚════  △ diff -rq local remote
Only in remote: .babelrc
Only in remote: .prettierignore
Only in remote: .yarnrc
Only in remote: BUILD.bazel
Only in local/dist/js: main.js.map
Files local/package.json and remote/package.json differ
Only in remote: tsconfig.linting.json
```

This workflow was tested on [my personal fork](https://github.com/nathanstilwell/cockroach). An example dry run against master can be found [here](https://github.com/nathanstilwell/cockroach/actions/runs/3751489293).

Epic: CC-7999
See also: CC-7959

### CODE REVIEW

**Review by sjbarag — APPROVED** [review]
Makes sense!  Thanks for the explanation :)

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94014#-:-NJq9cpv2fdADD2qKw7j:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nathanstilwell)

**Comment by nathanstilwell** [comment]
@sjbarag and @maryliag Thank you for the reviews. Please note, that I am disabling the dry-run command in favor of a "live" publish for pre-release versions (on the master branch). Since these pull-requests are restrictive, I think we might as well enable this now. Also note, that back-ports will be required to enable publishing on release branches (in my testing I couldn't run a workflow against a branch without the workflow file).

**Review by rickystewart — APPROVED** [review]
Not an expert in JS or anything but everything here looks sane to me.

**Review by sjbarag — APPROVED** [review]

**Pull request merged**
