### PR TITLE
opt: extend JoinOrderBuilder to handle non-inner joins

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, JoinOrderBuilder could only reorder inner join trees.
This patch implements the algorithms described in 'On the correct
and complete enumeration of the core search space'. Join trees
containing semi, anti, and left joins can now be reordered in addition
to inner joins. For example, this transformation is now possible:
```
SELECT *
FROM xy
INNER JOIN (SELECT * FROM ab LEFT JOIN uv ON a = u)
ON x = a
=>
SELECT *
FROM (SELECT * FROM xy INNER JOIN ab ON x = a)
LEFT JOIN uv
ON a = u
```
Full joins cannot yet be reordered because the entries of the join
property lookup tables first need to be extended to check for
null-rejection by the join's predicate. This is left for a future
PR to ease the burden of reviewing.

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
Plan time comparison vs master for TPCH queries:
Screen Shot 2020-07-25 at 11 13 02 PM
Total run time comparison vs master:
Screen Shot 2020-07-25 at 11 13 11 PM
Only the plans for queries 16, 20 and 21 changed; I included Q2, Q5 and Q9 to ensure that no regression was introduced. Note that while the run times for Q16 and Q20 have increased vs master, the costs for the plans are lower. Take a look at `stats_quality/tpch/q16` and `stats_quality/tpch/q20` and you'll see why; the `LIKE '%Customer%Complaints%'` and `LIKE 'forest%'` filters are throwing off the stats.

**Review by rytaft — COMMENTED** [review]
This is looking great! I haven't finished reviewing yet, but I'm pushing some comments now since I need to take a break.

> Reviewed 20 of 24 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-:-MDLL4aR9dApwIcRp421:b-3dbkmt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/testutils/opttester/reorder_joins.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDGt_5OC4NzVjvTjOj7:-MDGt_5OC4NzVjvTjOj8:b-s0lb1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/87669c0261f099e231228f5466dbeffc3ffdd7ba/pkg/sql/opt/testutils/opttester/reorder_joins.go#L148)):*
> ```Go
> 		buf.WriteString("cross")
> 	} else if len(edge) == 1 {
> 		buf.WriteString(strings.TrimSuffix(o.FormatExpr(&edge[0], memo.ExprFmtHideAll), "\n"))
> ```

seems like you don't need a special case for this (the else case below covers it)
___
*[pkg/sql/opt/xform/join_order_builder.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDKx3Ar4G81OQYRt2Lb:-MDKx3As5aMxK__0zvEK:bwe5f9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L111)):*
> ```Go
> // ({xy}, {uv}) or ({xy, uv}, {cd}). This is done efficiently using bit sets.
> // For each pair of relation subsets, the edges are iterated over. For each
> // edge, if the aforementioned edge conditions are satisfied, a new join is
> ```

I don't think you've really described the edge conditions at this point, have you? Instead of "aforementioned", maybe say "... certain edge conditions (to be described in the next section) ...". 
___
*[pkg/sql/opt/xform/join_order_builder.go, line 138 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDKyRvh3emwbOMQZpN3:-MDKyRvi2Irze67Xma9f:b-nrphjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L138)):*
> ```Go
> // The TES of an edge is initialized with the SES, and then expanded during
> // execution of the CD-C algorithm (see citations: [8] section 5.4). For each
> // 'child' join under the current join, associative, left-asscom and
> ```

what's asscom?
___
*[pkg/sql/opt/xform/join_order_builder.go, line 149 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDKz6Xd-Zc0CYZ9VRoz:-MDKz6Xd-Zc0CYZ9VRp-:b-j32ufv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L149)):*
> ```Go
> //    SELECT *
> //    FROM uv
> //    INNER JOIN (SELECT * FROM xy LEFT JOIN uv ON x = a)
> ```

should this be `ON x = u`?
___
*[pkg/sql/opt/xform/join_order_builder.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDKzDXD6YkZXRDUKCEL:-MDKzDXD6YkZXRDUKCEM:b-3b0f0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L150)):*
> ```Go
> //    FROM uv
> //    INNER JOIN (SELECT * FROM xy LEFT JOIN uv ON x = a)
> //    ON x = a
> ```

and should this be `ON a = u`?
___
*[pkg/sql/opt/xform/join_order_builder.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDKzM-X7KpGWM-HmdRG:-MDKzM-X7KpGWM-HmdRH:b52pjh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L152)):*
> ```Go
> //    ON x = a
> //
> // The left join's TES will include all three relations. Because all relations
> ```

Why does the TES contain all 3 relations while the SES only contains 2? Would help to give some intuition about how the TES is calculated for this case.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 176 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDL0rMf3TUnI1FsWdpu:-MDL0rMgDLcOuomQBm9R:b-hbuzuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L176)):*
> ```Go
> //
> // Treating the ON conditions of these joins as a conglomerate (as we do with
> // non-inner joins), a join between base relations xy and uv would not be
> ```

Might help to add another paragraph somewhere before this explaining why ON conditions need to be treated as a conglomerate for non-inner joins.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 591 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLEQRj8slANYOjbShP:-MDL9gnNA8oC0DUNoEan:blxobl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L591)):*
> ```Go
> 	// Find the inner join down to which this filter would be pushed if it had
> 	// been made explicit in the original query. This operator will be used to
> 	// construct the TES for this edge.
> ```

Would help to add a reminder here that each edge contains a record of the original base relations present from each side, even those not present in the filter. I was confused about what was happening here until I read the comments on the `edge` struct.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 610 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDL8VGj7VcwJiju7VQX:-MDL8VGk5vJMX6HPAaQ-:b-2h8qk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L610)):*
> ```Go
> 
> 	// Construct the edge.
> 	var1 := jb.f.Memo().MemoizeVariable(col1)
> ```

is there a reason you're calling the `Memoize` functions instead of `Construct`? Seems like we would want to apply any relevant normalization rules.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 642 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLFxgg-CfsHff2Ftg3:-MDLFxgh6O-pIGxaCXgp:b-h1nzjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L642)):*
> ```Go
> //
> // While still satisfying the syntactic eligibility sets of the edges.
> func (jb *JoinOrderBuilder) getSES(predicate memo.FiltersExpr) vertexSet {
> ```

Seems like this could be a method on `edge` called `calcSES` to be symmetric with `calcTES`. Alternatively `calcTES` could be converted to a method on `joinOrderBuilder` similar to this one...
___
*[pkg/sql/opt/xform/join_order_builder.go, line 791 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLCUD_26xJQ0cAWdpv:-MDLCUD_26xJQ0cAWdpw:b-9pxnvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L791)):*
> ```Go
> // a select with those filters, which is also added to the memo and returned.
> func (jb *JoinOrderBuilder) memoize(
> 	op opt.Operator, left, right memo.RelExpr, on, selectFilters memo.FiltersExpr,
> ```

Is this ever called with a non-nil `selectFilters`?

**Review by andy-kimball — COMMENTED** [review]
:lgtm:, I'd previously looked over the PR and it incorporates my feedback

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-:-MDLouj31i_z865ZqAFh:b-fdnmr4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51900)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/testutils/opttester/reorder_joins.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDGt_5OC4NzVjvTjOj7:-MDLrMxp3rJ2G8jAaFcV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87669c0261f099e231228f5466dbeffc3ffdd7ba/pkg/sql/opt/testutils/opttester/reorder_joins.go#L148)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

seems like you don't need a special case for this (the else case below covers it)
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDKx3Ar4G81OQYRt2Lb:-MDLrvUqDkZWcJ-mA88s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L111)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think you've really described the edge conditions at this point, have you? Instead of "aforementioned", maybe say "... certain edge conditions (to be described in the next section) ...". 
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 138 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDKyRvh3emwbOMQZpN3:-MDLsKHvCAT4Z0q9IyfZ:b-tw7msq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L138)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

what's asscom?
</blockquote></details>

I'll add a comment. Done.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 149 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDKz6Xd-Zc0CYZ9VRoz:-MDLt0wiAYnpeqK2Yu0E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L149)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should this be `ON x = u`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDKzDXD6YkZXRDUKCEL:-MDLt1kpA0rU5K5z5U3i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L150)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

and should this be `ON a = u`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDKzM-X7KpGWM-HmdRG:-MDM5n1n6-zzZQLRdILd:b7396hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L152)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why does the TES contain all 3 relations while the SES only contains 2? Would help to give some intuition about how the TES is calculated for this case.
</blockquote></details>

Done (I think; let me know if my explanation is good enough).
___
*[pkg/sql/opt/xform/join_order_builder.go, line 176 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDL0rMf3TUnI1FsWdpu:-MDM8PNXB49lvceNWfWo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L176)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Might help to add another paragraph somewhere before this explaining why ON conditions need to be treated as a conglomerate for non-inner joins.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 591 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLEQRj8slANYOjbShP:-MDM9F3z9dX7SezbCmEM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L591)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Would help to add a reminder here that each edge contains a record of the original base relations present from each side, even those not present in the filter. I was confused about what was happening here until I read the comments on the `edge` struct.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 610 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDL8VGj7VcwJiju7VQX:-MDM9Uhc7HpWQiDsrHPE:b6b2ygp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L610)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is there a reason you're calling the `Memoize` functions instead of `Construct`? Seems like we would want to apply any relevant normalization rules.
</blockquote></details>

No particular reason, no. I'll change it.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 642 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLFxgg-CfsHff2Ftg3:-MDMCcit2WbFlpcTuSnH:behgs8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L642)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Seems like this could be a method on `edge` called `calcSES` to be symmetric with `calcTES`. Alternatively `calcTES` could be converted to a method on `joinOrderBuilder` similar to this one...
</blockquote></details>

Done. I also refactored the makeEdge functions a bit.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 791 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLCUD_26xJQ0cAWdpv:-MDMGlCz7PRsxcIWfuTU:b-p1t51x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L791)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this ever called with a non-nil `selectFilters`?
</blockquote></details>

There weren't any test cases for it, so I've added one. I don't think calling memoize when `selectFilters` is non-nil will ever add an expression to the memo because we would already have added that expression to a previous group, but it is necessary because we rematch at each point in the join tree.

**Review by rytaft — APPROVED** [review]
:lgtm: really nice work!

I'm wondering if we have enough logic-style tests with real data and different types of joins that are run on a nightly basis. We might want to consider uncommenting this line: https://github.com/cockroachdb/cockroach/blob/4de665c6cf65850b4910787e88f377c213085a53/pkg/sql/logictest/logic_test.go#L55. 

Not needed for this PR, but you might also investigate using the `-optimizer-cost-perturbation` flag in some additional tests to make sure that all the different valid join orders produce valid results. Maybe it's worth adding a run of sqllogictest with that flag set to a non-zero value (see `build/teamcity-testlogicrace.sh` and `build/teamcity-sqllogictest.sh`).

> Reviewed 3 of 24 files at r1, 1 of 1 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-:-MDMOHHSEVy6qN4CXJE9:b-eybc0t)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[pkg/sql/opt/xform/join_order_builder.go, line 1061 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLvHg8Evcm00OjYpbG:-MDLvHg8Evcm00OjYpbH:bw6y532) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L1061)):*
> ```Go
> 		}
> 		child := &edges[idx]
> 		if !assoc(child, e) {
> ```

These different cases could use a comment explaining what's going on
___
*[pkg/sql/opt/xform/join_order_builder.go, line 1086 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLvXUU1IKYdWPOqPnK:-MDLvXUU1IKYdWPOqPnL:b8roagx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L1086)):*
> ```Go
> 		if e.op.rightVertexes.isSubsetOf(e.tes) {
> 			// Fast path to break out early: the TES includes all relations from the
> 			// left input.
> ```

left -> right
___
*[pkg/sql/opt/xform/join_order_builder.go, line 1222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLuAbM9oG3olZ_fV0r:-MDLuAbNBHVk8UtqVaxr:b-z0yezk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L1222)):*
> ```Go
> }
> 
> // assoc returns true if the given edges are associative with each other.
> ```

It's a bit odd to think about edges being associative with each other. Would help to go into a bit more detail about what this means exactly.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 1245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLrvwwCJaP-Pbc9vY8:-MDLrvwwCJaP-Pbc9vY9:bpgz1bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L1245)):*
> ```Go
> }
> 
> // leftAsscom returns true if the given edges have the left-asscom property.
> ```

Can you give a bit more detail about what this property is?
___
*[pkg/sql/opt/xform/join_order_builder.go, line 1382 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLta6x9JdEbZ0UP-bZ:-MDLta6x9JdEbZ0UP-b_:b8p7ve0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L1382)):*
> ```Go
> // next returns the next element in the set after the given start index, and
> // a bool indicating whether such an element exists.
> func (s bitSet) next(startVal vertexIndex) (elem uint64, ok bool) {
> ```

should this be `int64` instead of `vertexIndex`?
___
*[pkg/sql/opt/xform/join_order_builder_test.go, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDM2V1VCFGeAT9fU7tv:-MDM2V1W17dJJOhpTtqz:bjxindw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder_test.go#L285)):*
> ```Go
> 			}
> 			if len(tc.rightChildEdges) > 0 {
> 				rightEdges.AddRange(0, len(tc.leftChildEdges)+len(tc.rightChildEdges)-1)
> ```

Shouldn't this be `rightEdges.AddRange(len(tc.leftChildEdges), len(tc.leftChildEdges)+len(tc.rightChildEdges)-1)`?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51900)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/xform/join_order_builder.go, line 1061 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLvHg8Evcm00OjYpbG:-MDMhujc0tvnWaeHDcun:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L1061)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These different cases could use a comment explaining what's going on
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 1086 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLvXUU1IKYdWPOqPnK:-MDMdRGk73r6jKS1OHNo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L1086)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

left -> right
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 1222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLuAbM9oG3olZ_fV0r:-MDMgFfT2_wijkJflcjJ:biuj71p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L1222)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It's a bit odd to think about edges being associative with each other. Would help to go into a bit more detail about what this means exactly.
</blockquote></details>

Done. Let me know if it's enough.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 1245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLrvwwCJaP-Pbc9vY8:-MDMgKaP5VGfK03IJzug:bhdyo9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L1245)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you give a bit more detail about what this property is?
</blockquote></details>

I'll add an example transformation. Done.
___
*[pkg/sql/opt/xform/join_order_builder.go, line 1382 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDLta6x9JdEbZ0UP-bZ:-MDMgfrQ4YhECORkkCN1:b-5bs3hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder.go#L1382)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should this be `int64` instead of `vertexIndex`?
</blockquote></details>

Indeed it should, nice catch. Done.
___
*[pkg/sql/opt/xform/join_order_builder_test.go, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDM2V1VCFGeAT9fU7tv:-MDMh46DBLQvc5w_U8oH:b-ymf2y4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder_test.go#L285)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Shouldn't this be `rightEdges.AddRange(len(tc.leftChildEdges), len(tc.leftChildEdges)+len(tc.rightChildEdges)-1)`?
</blockquote></details>

Yup. This line has given me an odd amount of trouble. Done.

**Comment by DrewKimball** [comment]
TFTR!

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51900)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball)

___
*[pkg/sql/opt/xform/join_order_builder_test.go, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDM2V1VCFGeAT9fU7tv:-MDPKe0mDyp2GVjl-zqP:bcv6uph) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder_test.go#L285)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Yup. This line has given me an odd amount of trouble. Done.
</blockquote></details>

Strange that the test still worked with no problems. Is that something that we should be concerned  about? Or this wouldn't happen in real scenarios anyway so not a problem?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51900)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/xform/join_order_builder_test.go, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDM2V1VCFGeAT9fU7tv:-MDQkumw3G-sNle3zXWf:bi2mfyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder_test.go#L285)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Strange that the test still worked with no problems. Is that something that we should be concerned  about? Or this wouldn't happen in real scenarios anyway so not a problem?
</blockquote></details>

It shouldn't happen in the real world, since it was a problem with my test representing traversal a join tree correctly rather than a failing of the calcTES method. Also, this was actually a completeness issue rather than correctness; a problem of this sort would only restrict the search space, rather than allow invalid plans.

**Comment by DrewKimball** [comment]
___
*[pkg/sql/opt/xform/join_order_builder_test.go, line 285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDM2V1VCFGeAT9fU7tv:-MDQlR0y3UraswzUMqHB:b-wgbq19) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcf6c69bcde541152faecbbaaea84f07e5556b5/pkg/sql/opt/xform/join_order_builder_test.go#L285)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

It shouldn't happen in the real world, since it was a problem with my test representing traversal a join tree correctly rather than a failing of the calcTES method. Also, this was actually a completeness issue rather than correctness; a problem of this sort would only restrict the search space, rather than allow invalid plans.
</blockquote></details>

*traversal of a join tree

**Review by rytaft — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-:-MDQqL3k7MAFLShg1ABI:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by RaduBerinde — COMMENTED** [review]
:lgtm: Very nice work! I can't say I was able to verify all the details but the code is very clean and easy to read.

I tried changing `LIKE 'forest%'` to `p_name >= 'forest' AND p_name < 'foresu'` and we get the same plan; I also don't understand the TODO to push the filter into the Scan (the column is not indexed). Maybe also having a histogram on the column would do it..

In any case, before merging, can you file an issue (or issues) to track these instances where we know a better but higher-cost plan is being explored?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-:-MDVuX7M19BppK4w-VcY:begq6rn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @rytaft)

___
*[pkg/sql/opt/xform/join_order_builder.go, line 1366 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDVqKji2dhzoOtyZ0JI:-MDVqKji2dhzoOtyZ0JJ:b-swb6md) ([raw file](https://github.com/cockroachdb/cockroach/blob/71774bdfe94e550081194ee883675b0166524a7e/pkg/sql/opt/xform/join_order_builder.go#L1366)):*
> ```Go
> // TODO(drewk): a few of these 'false' entries can be conditionally 'true',
> //  depending on whether the filters reject nulls. Handle these.
> var assocTable = [][]bool{
> ```

[nit] I think `[5][5]bool` leads to a more efficient memory layout

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51900)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/xform/join_order_builder.go, line 1366 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51900#-MDVqKji2dhzoOtyZ0JI:-MDW5AQ7Bh2491JbaZyS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71774bdfe94e550081194ee883675b0166524a7e/pkg/sql/opt/xform/join_order_builder.go#L1366)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I think `[5][5]bool` leads to a more efficient memory layout
</blockquote></details>

Done.

**Comment by DrewKimball** [comment]
TFTR!

**Comment by DrewKimball** [comment]
Sure, I'll put up an issue.

**Pull request merged**
