### PR TITLE
Add "Create Table statement" to Database Details

### PR DESCRIPTION
**Pull request by mrtracy**
DatabaseDetails endpoint now returns a "create table statement", which is the
output of SHOW CREATE TABLE for that database.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7301)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 366 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301#-KKQsPncr-xjFnq_S3b0:-KKQsPncr-xjFnq_S3b1:597138196) ([raw file](https://github.com/cockroachdb/cockroach/blob/f390aa3104725f807bc73f6f04431e9b11e9365c/server/admin.go#L366)):*
> ```Go
> 	// Marshal SHOW CREATE TABLE result.
> 	{
> 		const (
> ```

multiline const?

---

*[server/admin.go, line 369 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301#-KKQsiHffmVSIc8Vrj7_:-KKQsiHffmVSIc8Vrj7a:470668263) ([raw file](https://github.com/cockroachdb/cockroach/blob/f390aa3104725f807bc73f6f04431e9b11e9365c/server/admin.go#L369)):*
> ```Go
> 			createTableCol = "CreateTable"
> 		)
> 		showResult := r.ResultList[3]
> ```

why [3]? might help to comment.

---

*[server/admin_test.go, line 448 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301#-KKQsYYZNnXjXdrEeYY8:-KKQsYYZNnXjXdrEeYY9:855183347) ([raw file](https://github.com/cockroachdb/cockroach/blob/f390aa3104725f807bc73f6f04431e9b11e9365c/server/admin_test.go#L448)):*
> ```Go
> 
> 		res := s.sqlExecutor.ExecuteStatements(context.Background(), session, showCreateTableQuery, nil)
> 		if res.ResultList[0].Err != nil {
> ```

res.ResultList[0] => extract local

---

*[server/serverpb/admin.proto, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301#-KKQsrXrGErPDCEHegU6:-KKQsrXrGErPDCEHegU7:-698373457) ([raw file](https://github.com/cockroachdb/cockroach/blob/f390aa3104725f807bc73f6f04431e9b11e9365c/server/serverpb/admin.proto#L121)):*
> ```protobuf
>   // estimate of the storage requirements for the table.
>   int64 range_count = 4;
> ```

no space is the prevailing convention

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301)*

**Comment by mrtracy** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/admin.go, line 366 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301#-KKQsPncr-xjFnq_S3b0:-KKiYY98BRjiPbmoGId3:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f390aa3104725f807bc73f6f04431e9b11e9365c/server/admin.go#L366)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> multiline const?
</details>
Done.

---

*[server/admin.go, line 369 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301#-KKQsiHffmVSIc8Vrj7_:-KKiYYNTKZS_zlm9ciF8:1498285942) ([raw file](https://github.com/cockroachdb/cockroach/blob/f390aa3104725f807bc73f6f04431e9b11e9365c/server/admin.go#L369)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why [3]? might help to comment.
</details>
The reason for this being [3] is apparent in the context of the file, it might not be apparent in the diff for this change, which excludes unchanged lines.  

This function is constructed from four consecutive code blocks, working on result [0], [1], [2] and [3] respectively.

---

*[server/admin_test.go, line 448 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301#-KKQsYYZNnXjXdrEeYY8:-KKiiM9XmFeiVpwHk2eY:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f390aa3104725f807bc73f6f04431e9b11e9365c/server/admin_test.go#L448)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> res.ResultList[0] => extract local
</details>
Done.

---

*[server/serverpb/admin.proto, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301#-KKQsrXrGErPDCEHegU6:-KKijw81kt1oMED2j4SJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f390aa3104725f807bc73f6f04431e9b11e9365c/server/serverpb/admin.proto#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> no space is the prevailing convention
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[server/admin.go, line 369 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301#-KKQsiHffmVSIc8Vrj7_:-KKix0cFKCqMFTttKFXS:-116605670) ([raw file](https://github.com/cockroachdb/cockroach/blob/f390aa3104725f807bc73f6f04431e9b11e9365c/server/admin.go#L369)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> The reason for this being [3] is apparent in the context of the file, it might not be apparent in the diff for this change, which excludes unchanged lines.  
> 
> This function is constructed from four consecutive code blocks, working on result [0], [1], [2] and [3] respectively.
</details>
Ah, okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301)*

**Comment by mrtracy** [comment]
@cuongdo would you mind taking a quick look at this?  You're still the best person to review a change to this API.

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7301#-:-KKoMlweoUIEhyvQIOpG:1417088721)*

**Comment by maxlang** [comment]
LGTM

**Pull request merged**
