### PR TITLE
sql: introduce BatchReceiver

### LINKED ISSUE #50857: sql: coldata.Batch-aware distsql receiver and pgwire.conn
The `Materializer` is expensive because it has to turn all of our nicely packed native data back into expensive boxed `tree.Datum`s. At the very end of the pipe, the `DistSQLReceiver`’s job is to push a row of `tree.Datum` into pgwire, by type-switching on the `tree.Datum` and converting into bytes.

If we have a pipeline of vectorized-only execution, there’s no need to convert to `Datum` at all. Theoretically, we could push an entire `coldata.Batch` to the receiver, and have the pgwire adapter churn through that batch itself, converting our physical datatypes directly to pgwire bytes, no wasted allocations.

I expect this would be a nice win, and bring us much closer to the dream of 0 pointless allocations in the query path.

A very cursory investigation shows that the main interface that would have to change is the `pgwire.conn`, which currently has a `bufferRow` method that takes `tree.Datums`. If we added a new method that took `coldata.Batch`, and propagated that change all the way up into the `DistSQLReceiver`, then the stage would be set for the vectorized planner to not plan that final `Materializer` in flows and instead push its batches right to the receiver.

### PR DESCRIPTION
**Pull request by yuzefovich**
Fixes: #50857

Release note (performance improvement): Queries that produce a lot of
rows in the result usually will now run faster when executed via the
vectorized engine.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Exciting!

**Comment by yuzefovich** [comment]
Some tests are still failing, but I think it is RFAL.

**Comment by yuzefovich** [comment]
Fixed a bazel dependency issue, but a couple of tests are still failing.

**Comment by yuzefovich** [comment]
Just a note to myself: think through whether EXPLAIN (VEC, VERBOSE) needs an update to show the batch flow coordinator.

**Comment by yuzefovich** [comment]
Alright, I fixed one bug (and hopefully CI will be green now) and addressed the EXPLAIN (VEC, VERBOSE) issue too.

**Review by jordanlewis — COMMENTED** [review]
From a high level: nice work, this looks great. I would love to see benchmarks though I know you said it wasn't significant. What about alloc benchmarks?

I think you should consider breaking this PR up into a couple for ease of review, since it's covering a lot of ground. I suggest making one PR that creates the new methods to write batches to pgwire, with tests, but not hooked up to the bigger machinery yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-:-Ma6ZwIk-WH9pcxYh1Nu:b-g47yec)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/conn_io.go, line 722 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-Ma6TFOgEKduHEkJv04E:-Ma6TFOh1-Kq_xJD0YbO:bezgiwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/002bfc5ce37ad1718f2417b35f54b686ca002cad/pkg/sql/conn_io.go#L722)):*
> ```Go
> 	//
> 	// The implementation cannot hold on to the contents of the batch without
> 	// deeply copying them.
> ```

nit: I think it would make better sense to phrase it (also?) from the client's perspective. "The memory in the input batch is safe to modify as soon as `AddBatch` returns" or some such.
___
*[pkg/sql/conn_io.go, line 930 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-Ma6TTslD-wgdzY47Fc4:-Ma6TTslD-wgdzY47Fc5:b-mchm1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/002bfc5ce37ad1718f2417b35f54b686ca002cad/pkg/sql/conn_io.go#L930)):*
> ```Go
> // AddBatch is part of the RestrictedCommandResult interface.
> func (r *streamingCommandResult) AddBatch(context.Context, coldata.Batch) error {
> 	// TODO(yuzefovich): implement this.
> ```

do we need this?
___
*[pkg/sql/distsql_running.go, line 587 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-Ma6XIS-6JgIyZTQRnfJ:-Ma6XIS0EnDT_tTURRFf:blt5pdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/002bfc5ce37ad1718f2417b35f54b686ca002cad/pkg/sql/distsql_running.go#L587)):*
> ```Go
> 		// streamingCommandResult currently doesn't support receiving batches.
> 		// TODO(yuzefovich): this is a bit hacky, but I'm not sure how to make
> 		// it cleaner.
> ```

A `SupportsBatchPut` method on the interface? 
___
*[pkg/sql/pgwire/types.go, line 722 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-Ma6ZZDO8X4s0rhZgMtS:-Ma6ZZDO8X4s0rhZgMtT:b-bea87h) ([raw file](https://github.com/cockroachdb/cockroach/blob/002bfc5ce37ad1718f2417b35f54b686ca002cad/pkg/sql/pgwire/types.go#L722)):*
> ```Go
> // writeBinaryColumnarElement is the same as writeBinaryDatum where the datum is
> // represented in a columnar element (at position idx in vec).
> func (b *writeBuffer) writeBinaryColumnarElement(
> ```

Any way for us to test that this works the same (exactly) with vec as it does with datums? can we do some kind of roundtrip bytes test for this? Maybe @rafiss would have suggestions here?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65289)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @michae2, and @yuzefovich)

___
*[pkg/sql/pgwire/types.go, line 722 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-Ma6ZZDO8X4s0rhZgMtS:-Ma6dVhL7xIp2S6oHIR-:bws10qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/002bfc5ce37ad1718f2417b35f54b686ca002cad/pkg/sql/pgwire/types.go#L722)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Any way for us to test that this works the same (exactly) with vec as it does with datums? can we do some kind of roundtrip bytes test for this? Maybe @rafiss would have suggestions here?
</blockquote></details>

yes, to make sure that the encodings are the same, i'd suggest adding something to `TestEncodings` around here https://github.com/cockroachdb/cockroach/blob/1bb90a39c2ba55eb0ee3fb19c718d258d07d4adf/pkg/sql/pgwire/encoding_test.go#L163-L174 which uses this new function.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65289)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @michae2, and @yuzefovich)

___
*[pkg/sql/pgwire/types.go, line 722 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-Ma6ZZDO8X4s0rhZgMtS:-Ma6eOx292JdI0oGfQ8d:bhl7mnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/002bfc5ce37ad1718f2417b35f54b686ca002cad/pkg/sql/pgwire/types.go#L722)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

yes, to make sure that the encodings are the same, i'd suggest adding something to `TestEncodings` around here https://github.com/cockroachdb/cockroach/blob/1bb90a39c2ba55eb0ee3fb19c718d258d07d4adf/pkg/sql/pgwire/encoding_test.go#L163-L174 which uses this new function.
</blockquote></details>

And also is there a way to hook up the new `AddBatch` functionality so it's used by the datadriven tests in pkg/sql/pgwire/pgtest_test.go

**Comment by yuzefovich** [comment]
Ok, I extracted first 6 commits into a separate PR #65497 since I think they should be uncontroversial, and I will split up the last commit into a couple with the introduction of some unit testing in this PR.

**Review by yuzefovich — COMMENTED** [review]
I broke out the pgwire encoding methods with the unit tests into a separate commit, and also added the test for the vectorized flow shutdown when the batch flow coordinator is used. I'm not sure whether the second commit can be reasonably broken down further.

> I would love to see benchmarks though I know you said it wasn't significant. What about alloc benchmarks?

Do you have something in particular in mind? I'll kick off the microbenchmarks in `pkg/bench` since there is a good mix of queries there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-:-MaFP-HB7LQhW2ctYLAp:bj5yslf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @michae2)

___
*[pkg/sql/conn_io.go, line 722 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-Ma6TFOgEKduHEkJv04E:-MaF8LSz1jU7kz5XmV05:bdlkc9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/002bfc5ce37ad1718f2417b35f54b686ca002cad/pkg/sql/conn_io.go#L722)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: I think it would make better sense to phrase it (also?) from the client's perspective. "The memory in the input batch is safe to modify as soon as `AddBatch` returns" or some such.
</blockquote></details>

Good point, added. I was following the comment on `AddRow` about not holding on to the data without a deep copy, and I think it's worth having both perspectives.
___
*[pkg/sql/conn_io.go, line 930 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-Ma6TTslD-wgdzY47Fc4:-MaFA1Lc4ykMXnurpuQB:b4iwqmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/002bfc5ce37ad1718f2417b35f54b686ca002cad/pkg/sql/conn_io.go#L930)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

do we need this?
</blockquote></details>

Do you mean in general or right now? If the latter, I think that it can definitely wait since it is not a trivial change; if the former, I imagine that there might be cases where it would be beneficial to implement it - imagine that we're executing an OLAP-y query via the internal executor via the vectorized engine, then it'd be good to stream columnar batches instead of having to materialize to the datums.
___
*[pkg/sql/distsql_running.go, line 587 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-Ma6XIS-6JgIyZTQRnfJ:-MaF9o5u0GLUoQuWmhci:b-4pj5my) ([raw file](https://github.com/cockroachdb/cockroach/blob/002bfc5ce37ad1718f2417b35f54b686ca002cad/pkg/sql/distsql_running.go#L587)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

A `SupportsBatchPut` method on the interface? 
</blockquote></details>

Nice, done.
___
*[pkg/sql/pgwire/types.go, line 722 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-Ma6ZZDO8X4s0rhZgMtS:-MaF7i2i3A3NAPIJaLE6:bui9l6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/002bfc5ce37ad1718f2417b35f54b686ca002cad/pkg/sql/pgwire/types.go#L722)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

And also is there a way to hook up the new `AddBatch` functionality so it's used by the datadriven tests in pkg/sql/pgwire/pgtest_test.go
</blockquote></details>

Thanks for the suggestions! I extended `TestEncodings` to run against new methods. I also confirmed that new `AddBatch` method is already being used for `PGTest` because for those we just issue queries against a running server, and the server will use the batch receiver when appropriate on its own, so we get that testing for free :)

**Comment by yuzefovich** [comment]
Finally got some benchmarks of `./pkg/bench` [here](https://gist.github.com/yuzefovich/7990c58aa4a8602a15493d91b6e8e9d9). They mostly don't show significant changes, some have improved, few have regressed, but I would just think it's mostly noise.

For some reason `benchdiff` tool didn't work a couple of times I tried (I think we might have been hitting the --max-sql-memory limit - 128MiB by default - in some bulk operations).

Anyway, I'm certain this change is beneficial in the grand scheme of things even if we don't have immediate benchmarks to back that claim up. I spent some time looking into the heap profiles, and we might want to spend some time optimizing the code in `pgwire` package to remove some allocations, but that is definitely follow-up PRs.

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-:-Mb7dYco2nMSVcCz7aRd:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/pgwire/conn.go, line 1282 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-MasleGs5bt2RjkjKaXy:-MasleGs5bt2RjkjKaXz:b-176f4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c86c8f937e3c5d4728079d2bdb2a98943a7d872/pkg/sql/pgwire/conn.go#L1282)):*
> ```Go
> 		c.msgBuilder.initMsg(pgwirebase.ServerMsgDataRow)
> 		c.msgBuilder.putInt16(width)
> 		for colIdx, col := range vecs {
> ```

Idea for later: this could be the perfect place for us to prototype the "opcode style" of execution, since it's such a simple, constrained codepath. I'm not even sure if it would help matters, but I know from profiles that the most expensive part of places like this where we revert to row-based execution is the type switching.

So, what if we made a simple little opcode runner, and pre-calculated the types that we will be running through over and over again on every row?

For example, at plantime, we'd run something like this:

```
opcodes = []
for i, type := types {
    fmtCode = formatCodes[i]
    opcodes = append(opcodes, getOpcode(type, fmtCode)
}
```

An "opcode" would be something like `EncodeBinaryInt32` or `EncodeTextDate`.

Then, at runtime (aka right here), we'd run:

```
for i := 0; i < n; i++ {
    // get rowidx
    for _, opCode := range opCodes {
        switch opCode {
            case EncodeBinaryInt32:
                ...
        }
    }
}
```

Then again maybe we'd gain exactly nothing here - we'd be replacing a type switch with an int switch, but we'd keep the interface-to-ptr cast...

Maybe the true way to make all of this better would be to use more `unsafe.Ptr` stuff to avoid the expensive, checked interface type lookup and cast.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

@michae2 I see that you were typing something, do you have some feedback here?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-:-Mb8-M666q_v7cJ_KumT:bd5tht5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @michae2)

___
*[pkg/sql/pgwire/conn.go, line 1282 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-MasleGs5bt2RjkjKaXy:-Mb805Qd0X75VeXxrK8K:b-5ms13m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c86c8f937e3c5d4728079d2bdb2a98943a7d872/pkg/sql/pgwire/conn.go#L1282)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Idea for later: this could be the perfect place for us to prototype the "opcode style" of execution, since it's such a simple, constrained codepath. I'm not even sure if it would help matters, but I know from profiles that the most expensive part of places like this where we revert to row-based execution is the type switching.

So, what if we made a simple little opcode runner, and pre-calculated the types that we will be running through over and over again on every row?

For example, at plantime, we'd run something like this:

```
opcodes = []
for i, type := types {
    fmtCode = formatCodes[i]
    opcodes = append(opcodes, getOpcode(type, fmtCode)
}
```

An "opcode" would be something like `EncodeBinaryInt32` or `EncodeTextDate`.

Then, at runtime (aka right here), we'd run:

```
for i := 0; i < n; i++ {
    // get rowidx
    for _, opCode := range opCodes {
        switch opCode {
            case EncodeBinaryInt32:
                ...
        }
    }
}
```

Then again maybe we'd gain exactly nothing here - we'd be replacing a type switch with an int switch, but we'd keep the interface-to-ptr cast...

Maybe the true way to make all of this better would be to use more `unsafe.Ptr` stuff to avoid the expensive, checked interface type lookup and cast.
</blockquote></details>

I filed #65959 to track this idea.

My initial thought is that this type switch is not that expensive in comparison to actually having to serialize objects into the pgwire message builder. In some profiles I looked at I noticed still a bunch of allocations in the vectorized path, so there is more low-hanging fruit that this idea describes. Also, in the case of natively supported by vectorized engine types we are already essentially performing an int switch (we do `vec.Type().Family()`).

**Review by michae2 — APPROVED** [review]
Oh, sorry, no, I was just clicking red eyeballs. :lgtm:

> Reviewed 31 of 32 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-:-Mb9-6htC1MVaWi7_eBZ:b-pk2t24)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jordanlewis, @michae2, and @yuzefovich)

___
*[pkg/sql/pgwire/conn.go, line 1282 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-MasleGs5bt2RjkjKaXy:-Mb9-HSH7YDSJl1aWohj:bycupds) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c86c8f937e3c5d4728079d2bdb2a98943a7d872/pkg/sql/pgwire/conn.go#L1282)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I filed #65959 to track this idea.

My initial thought is that this type switch is not that expensive in comparison to actually having to serialize objects into the pgwire message builder. In some profiles I looked at I noticed still a bunch of allocations in the vectorized path, so there is more low-hanging fruit that this idea describes. Also, in the case of natively supported by vectorized engine types we are already essentially performing an int switch (we do `vec.Type().Family()`).
</blockquote></details>

There are ways to make the switch cheaper, such as [direct threading](http://www.cs.toronto.edu/~matz/dissertation/matzDissertation-latex2html/node6.html#SECTION00630000000000000000) often implemented with [computed gotos](https://eli.thegreenplace.net/2012/07/12/computed-goto-for-efficient-dispatch-tables), but every opcode interpreter will have a switch like this. JIT compilation is required to avoid the switch.

As @yuzefovich points out, though, the dispatch strategy only starts to matter if the average amount of work per opcode is very small.

(Aside: it might also be nice to use opcodes to "fuse" together some of the vectorized loops, but this would be more about using cache efficiently than minimizing interpreter overhead.)

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65289#-:-Mb98p2-B2qha-TKsQTR:b-tlx7ko)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jordanlewis and @michae2)

**Pull request merged**
