### PR TITLE
admission: move kv admission under tracing span setup

### PR DESCRIPTION
**Pull request by cucaroach**
Release justification: Important for full tracing visibility

Release note: none

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
looks ok to me, but can you get someone from KV to approve -- there may be some subtleties that I am unaware of.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77538#-:-MxosXZa9FmuLNAbHgMK:b4pnbp7)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77538#-:-Mxoxz5u3GG8Yumn_nTE:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @cucaroach)

___
*[pkg/server/node.go, line 979 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77538#-MxoxuoY23_CPdVIZPoF:-MxoxuoY23_CPdVIZPoG:b-ikbhda) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc8324fc7fe7fc5639d052883cc56d6b42a6b1/pkg/server/node.go#L979)):*
> ```Go
> 		var pErr *roachpb.Error
> 		br, pErr = n.stores.Send(ctx, *args)
> 		n.admissionController.AdmittedKVWorkDone(handle)
> ```

can we `defer` this?

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77538)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @sumeerbhola)

___
*[pkg/server/node.go, line 979 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77538#-MxoxuoY23_CPdVIZPoF:-MxpQU_CAmweMIFfJxL7:bpdqc67) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc8324fc7fe7fc5639d052883cc56d6b42a6b1/pkg/server/node.go#L979)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can we `defer` this?
</blockquote></details>

@sumeerbhola ?   I can't think of compelling argument either way given how simple the function is.  I guess it boils down to do we want callComplete blocking the call to AdmittedKVWorkDone.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77538)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @sumeerbhola)

___
*[pkg/server/node.go, line 979 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77538#-MxoxuoY23_CPdVIZPoF:-MxpkoL6B6ratrD8ezGF:bxumyhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc8324fc7fe7fc5639d052883cc56d6b42a6b1/pkg/server/node.go#L979)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

@sumeerbhola ?   I can't think of compelling argument either way given how simple the function is.  I guess it boils down to do we want callComplete blocking the call to AdmittedKVWorkDone.
</blockquote></details>

defer-ing is fine, since callComplete is cpu work.

**Comment by cucaroach** [comment]
TFTRs
bors r+

**Pull request merged**
