### PR TITLE
server: properly set up new pipes on every loopback connection

### LINKED ISSUE #42828: server: UI dead if internal net.Pipe closes
**Describe the problem**

The cockroach server creates a singleton net.Pipe through which it connects the status server to the local gRPC server. 

https://github.com/cockroachdb/cockroach/blob/f97dc13163020a032b098ef3eb88e4d9f54a04ba/pkg/server/server.go#L1264-L1265

It wraps one side of this pipe in a `singleListener` on which it serves the gRPC server:

https://github.com/cockroachdb/cockroach/blob/f97dc13163020a032b098ef3eb88e4d9f54a04ba/pkg/server/server.go#L933

This listener no-ops on close and always returns the same side of the pipe. This is problematic if the underlying `Conn` is closed. I can't speak exactly to why the `Conn` is closed, but it seems to line up with a period of unavailability of the remote side. My best guess is that there was a client timeout somewhere.

The error on authentication requests looks like:

```
W191122 05:33:26.328330 56 vendor/google.golang.org/grpc/clientconn.go:1304  grpc: addrConn.createTransport failed to connect to {ip-172-31-10-214:26257 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: io: read/write on closed pipe". Reconnecting...
```

The observable behavior is that login requests display `System Unavailable`. If you perform the login request with `Accept: application/json` you get the following response:

```
{
  "error": "all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: io: read/write on closed pipe\"",
  "message": "all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: io: read/write on closed pipe\"",
  "code": 14,
  "details": [
  ]
}
```

**To Reproduce**

Not sure how exactly to repro. It seems easy enough to contrive the situation. Coming up with a realistic repro is probably worthwhile. The situation occurred during a rolling restart and upgrade of a four node cluster. At some point during the upgrade a large number of ranges were transiently unavailable as they submitted crash reports (specifically this one: https://github.com/cockroachdb/cockroach/issues/42802).

The upgrade was from 19.1.5 (maybe 19.1.4) to 19.2.1. 

**Expected behavior**

The expected behavior is that the admin UI remain available.

**Possible solution**

We should detect the close on the net.Pipe and create a new one. This can all happen underneath the listener. The dialer we inject into the client should then look up the most up-to-date conn from the listener. Probably we should rate limit all of this so we don't get caught in a tight loop.

### PR DESCRIPTION
**Pull request by knz**
Fixes #42828.

Prior to this patch, the loopback connection for the HTTP <-> RPC
gateway was using a single `net.Pipe` call. This was fragile because
the RPC subsystem can close is end of the connection under multiple
timeout scenarios, and the loopback conn would become unoperable from
that point.

This patch changes the code to hand off a new net.Pipe pair upon
every new loopback dial.

Release note (bug fix): A long-standing bug has been fixed where HTTP
requests would start to fail with error 503 "`transport:
authentication handshake failed: io: read/write on closed pipe`" and
never become possible again until the node is restarted. This bug
existed since v2.1 or some time prior.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48369)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @knz)

___
*[pkg/server/loopback.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-M6WahjhCavpzgurgRzr:-M6WahjhCavpzgurgRzs:b-m9g3kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc8250a0a43c56bd8e540b922172f40e858b456/pkg/server/loopback.go#L33)):*
> ```Go
> 		closed bool
> 	}
> 	active chan struct{}
> ```

 nit: this is implementing `sync.Once`. Maybe instead have a `closeOnce sync.Once` and in `Close()` use it?
___
*[pkg/server/loopback.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-M6Wb6Dg0a1kO8t2zG2-:-M6Wb6Dg0a1kO8t2zG20:bme8e79) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc8250a0a43c56bd8e540b922172f40e858b456/pkg/server/loopback.go#L60)):*
> ```Go
> 	}
> 	c1, c2 := net.Pipe()
> 	l.conns <- c1
> ```

Is there a problem here if the caller in `Connect` goes away due to a `Close` or the stopper queiescing where this could block? The buffer will probably help you in common cases but if there is enough concurrency it could be a problem. I find these buffers can hide bugs which only show up in extreme places. 
___
*[pkg/server/loopback.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-M6WbnI_E1nYFfYp0xm7:-M6WbnI_E1nYFfYp0xm8:bmnipp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc8250a0a43c56bd8e540b922172f40e858b456/pkg/server/loopback.go#L106)):*
> ```
> 		requests: make(chan struct{}, 10),
> 		conns:    make(chan net.Conn, 10),
> ```

Do we need to buffer these chans for correctness? If I read the code correctly, the answer is no. If that's the case, I'd hope we don't create these things at a high frequency. I'd rather have the peace of mind that there won't be deadlocks than the perf win due to the buffers.

**Review by ajwerner — COMMENTED** [review]
Thanks for jumping on this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-:-M6WcOMLERTwQk6xT9o0:b-c34ggs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @knz)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48369)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @bdarnell)

___
*[pkg/server/loopback.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-M6WahjhCavpzgurgRzr:-M6Z5nvJ7ArKvWSl0BEW:bombmv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc8250a0a43c56bd8e540b922172f40e858b456/pkg/server/loopback.go#L33)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

 nit: this is implementing `sync.Once`. Maybe instead have a `closeOnce sync.Once` and in `Close()` use it?
</blockquote></details>

Good call. Done.
___
*[pkg/server/loopback.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-M6Wb6Dg0a1kO8t2zG2-:-M6Z5p7x9C0aMi3Cgxbx:b-xwgxs1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc8250a0a43c56bd8e540b922172f40e858b456/pkg/server/loopback.go#L60)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is there a problem here if the caller in `Connect` goes away due to a `Close` or the stopper queiescing where this could block? The buffer will probably help you in common cases but if there is enough concurrency it could be a problem. I find these buffers can hide bugs which only show up in extreme places. 
</blockquote></details>

What's missing here is a `select`. The buffering is inconsequential. Fixed.
___
*[pkg/server/loopback.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-M6WbnI_E1nYFfYp0xm7:-M6Z5uGc4kYp0DZjcsCb:b-ulm5hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc8250a0a43c56bd8e540b922172f40e858b456/pkg/server/loopback.go#L106)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		requests: make(chan struct{}, 10),
> 		conns:    make(chan net.Conn, 10),
> ```

Do we need to buffer these chans for correctness? If I read the code correctly, the answer is no. If that's the case, I'd hope we don't create these things at a high frequency. I'd rather have the peace of mind that there won't be deadlocks than the perf win due to the buffers. 
</blockquote></details>

No it's not needed. Removed.

**Comment by joshimhoff** [comment]
Thanks for getting a fix ready so quickly!

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-:-M6_EpxW-pUSTr1kCmFZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @knz)

___
*[pkg/server/loopback.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-M6Wb6Dg0a1kO8t2zG2-:-M6_EIeD-jQ_67Hj0KHj:b-h28nnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc8250a0a43c56bd8e540b922172f40e858b456/pkg/server/loopback.go#L60)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What's missing here is a `select`. The buffering is inconsequential. Fixed.
</blockquote></details>

That's what I had in mind. Thanks!
___
*[pkg/server/loopback.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-M6_EXKKBujZUsuqENYb:-M6_EXKKBujZUsuqENYc:b-q3up4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/cee00abdcf0a6e3e540478d660dad5d1eb1a5209/pkg/server/loopback.go#L61)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> 	case <-l.stopper.ShouldQuiesce():
> 		err := errLocalListenerClosed
> 		err = errors.CombineErrors(err, c1.Close())
> 		err = errors.CombineErrors(err, c2.Close())
> 		return nil, err
> 	case <-l.active:
> 		err := errLocalListenerClosed
> 		err = errors.CombineErrors(err, c1.Close())
> 		err = errors.CombineErrors(err, c2.Close())
> 		return nil, err
> ```
</details>

nit: I'm fine with this duplication but you could eliminate it by returning in the positive case:

```
select {
case l.conns <- c1:
    return c2, nil
case <-l.stopper.ShouldQuiesce():
case <-l.active:
}
err := errLocalListenerClosed
err = errors.CombineErrors(err, c1.Close())
err = errors.CombineErrors(err, c2.Close())
return nil, err
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48369)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @bdarnell)

___
*[pkg/server/loopback.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48369#-M6_EXKKBujZUsuqENYb:-M6amvaUEbHrydZxJskV:b-g70hwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cee00abdcf0a6e3e540478d660dad5d1eb1a5209/pkg/server/loopback.go#L61)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	case <-l.stopper.ShouldQuiesce():
> 		err := errLocalListenerClosed
> 		err = errors.CombineErrors(err, c1.Close())
> 		err = errors.CombineErrors(err, c2.Close())
> 		return nil, err
> 	case <-l.active:
> 		err := errLocalListenerClosed
> 		err = errors.CombineErrors(err, c1.Close())
> 		err = errors.CombineErrors(err, c2.Close())
> 		return nil, err
> ```
nit: I'm fine with this duplication but you could eliminate it by returning in the positive case:

```
select {
case l.conns <- c1:
    return c2, nil
case <-l.stopper.ShouldQuiesce():
case <-l.active:
}
err := errLocalListenerClosed
err = errors.CombineErrors(err, c1.Close())
err = errors.CombineErrors(err, c2.Close())
return nil, err
```
</blockquote></details>

Cool! Done.

**Comment by knz** [comment]
bors r=ajwerner

**Pull request merged**
