### PR TITLE
rac2: add send token watcher

### LINKED ISSUE #128023: kvflowcontrol: implement store stream token watcher
Implement the store stream token watcher interface added in https://github.com/cockroachdb/cockroach/issues/128011. 

Note waiting on tokens should be performant, the existing prototype [code](https://github.com/sumeerbhola/cockroach/blob/2064b279e95bbd68b0a7898503168d384cd0158c/pkg/kv/kvserver/kvflowcontrol/kvflowconnectedstream/store_stream.go#L208-L208) and setup should be considered but not wholesale used due to allocations/perf.

Jira issue: CRDB-40757

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by kvoli**
`SendTokenWatcher` can be used for watching and waiting for available elastic send tokens. The caller registers a notification `TokenGrantNotification`, which will be called when elastic tokens are available for the given send stream being watched. Note that only elastic tokens are watched, as the `SendTokenWatcher` is intended to be used when a send queue exists for a replication stream, requiring only one goroutine per stream for potentially many different `RangeController`s waiting on send tokens.

See `testdata/send_token_watcher` for further semantic information.

Resolves: #128023
Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131133)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ecab9BCc6EW5s6S0v:-O7ecabA5nMu5YkgTOx8:bbkal66) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L366)):*
> ```Go
> // CancelHandle when tokens are no longer needed, or when the caller is done.
> func (s *SendTokenWatcher) NotifyWhenAvailable(
> 	ctx context.Context, tc *tokenCounter, notify TokenGrantNotification,
> ```

is this trying to respect context cancellation, in that if the context is cancelled, it may not call `Notify`? If not, we should state that context is only used for logging/tracing.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ebV13A_TBDE9UPkPU:-O7ebV13A_TBDE9UPkPV:b9ysi18) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L396)):*
> ```Go
> 	tc      *tokenCounter
> 	// nonEmptyCh is used to signal the watcher that there are events to process.
> 	// When the heap is empty, the watcher will wait for the next event to be
> ```

where is the heap?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ec0PR-quxcoGYRld_:-O7ec0PR-quxcoGYRlda:bvsx929) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L401)):*
> ```Go
> 	mu         struct {
> 		syncutil.Mutex
> 		// size is the number of waiting handles in the queue.
> ```

Is `size` always equal to `len(queueItems)`? If yes, do we need it?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ec8AGAMfD2wpZ1INb:-O7ec8AGAMfD2wpZ1INc:b-ps52zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L407)):*
> ```Go
> 		// started is true if the watcher is running, false otherwise. It is used
> 		// to prevent running more than one goroutine per stream.
> 		started bool
> ```

is `started == size > 0`? If yes, do we need it?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 409 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7eb04k4q7GCvCt2FMG:-O7eb04k4q7GCvCt2FMH:b-f3itaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L409)):*
> ```Go
> 		started bool
> 		// queueItems maps handles to their grant notification.
> 		queueItems map[SendTokenWatcherHandle]TokenGrantNotification
> ```

can this be keyed by the uint64 id, given the `sendStreamTokenWatcher` is specific to a `kvflowcontrol.Stream`?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ebbHz9oLM-t488wxN:-O7ebbHz9oLM-t488wxO:b-dimkku) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L412)):*
> ```Go
> 		// queue is the FIFO ordered queue of handles to be notified when tokens
> 		// are available.
> 		queue *queue.Queue[SendTokenWatcherHandle]
> ```

Can this be the ids too?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ee5tj0NAX5bf1i-DF:-O7ee5tj0NAX5bf1i-DG:b-mlafo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L448)):*
> ```Go
> 		if err := w.stopper.RunAsyncTask(ctx,
> 			"flow-control-send-stream-token-watcher", w.run); err == nil {
> 			w.mu.started = true
> ```

I don't see where `started` transitions back to false. If we are trying to save goroutines, it seems we should have the goroutine start a timer when it sees the queue is empty (say 60s) and then when the timer fires set started to false and exit.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ecyT48PuxdK-KjNCO:-O7ecyT48PuxdK-KjNCP:b-nggb4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L485)):*
> ```Go
> 		if empty := s.size() == 0; empty {
> 			// The watcher will wait here until a item is added to the queue, or
> 			// until cancellation.
> ```

why is it using the context of one of the `add` calls, given this is shared across multiple `add` calls. It seems to me that we should not propagate that context to `run`, and document here that this is a background context so we are not including context cancellation as a case in the select.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 536 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ef6lH5b_XxJlFNuQ4:-O7ef6lH5b_XxJlFNuQ5:bymb49p) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L536)):*
> ```Go
> 		// check if it's still in the queueItems map.
> 		if grant, found = s.mu.queueItems[handle]; found {
> 			s.mu.queue.Enqueue(handle)
> ```

why is this being enqueued again?

----

Never mind. I looked at the prototype and saw that we kept the handle enqueued until canceled. And we only canceled if there were actually tokens available (which should be the common case). Given that we are moving this to the end of the queue, this behavior is no better than registering a new handle. So I think we should just simplify the behavior and make it a one shot notification. We will still need `CancelHandle` as a best-effort cancellation, for `replicaSendStreams` being closed or force-flushed, though there is no guarantee that the notification is not already in progress.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131133)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ecab9BCc6EW5s6S0v:-O7euVmx0YIxgTrfRenU:b-qeurrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L366)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this trying to respect context cancellation, in that if the context is cancelled, it may not call `Notify`? If not, we should state that context is only used for logging/tracing.
</blockquote></details>

It is, added this comment.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ebV13A_TBDE9UPkPU:-O7euoIg8Wrvzjs5CImc:b-g0ybd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L396)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where is the heap?
</blockquote></details>

Whoops, should be queue. Updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ec0PR-quxcoGYRld_:-O7euux58uNM_y_5x4JH:b4u1rhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L401)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is `size` always equal to `len(queueItems)`? If yes, do we need it?
</blockquote></details>

It is always the same. The queue being used doesn't have a size method but does have `Empty()`, which could be used instead. 

I decided to update this use the queueItems map length instead and not maintain a separate size counter.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ec8AGAMfD2wpZ1INb:-O7evsJq2FJ8-fQics2T:bia0e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L407)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `started == size > 0`? If yes, do we need it?
</blockquote></details>

We aren't stopping the watcher ever, so its not exactly the same because the queue could be drained but the goroutine already spawned.

I opted to reap idle goroutines, so this is now relevant again.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 409 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7eb04k4q7GCvCt2FMG:-O7ewQrz1zmZ23HY015k:b-sycye0) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L409)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can this be keyed by the uint64 id, given the `sendStreamTokenWatcher` is specific to a `kvflowcontrol.Stream`?
</blockquote></details>

It can be, good idea. Updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ebbHz9oLM-t488wxN:-O7ewgZED-V4buPLBy_T:b-wmx3it) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L412)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can this be the ids too?
</blockquote></details>

Yup. Done.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ee5tj0NAX5bf1i-DF:-O7f1QN39gb8CPhmaErf:b-gpt4vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L448)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't see where `started` transitions back to false. If we are trying to save goroutines, it seems we should have the goroutine start a timer when it sees the queue is empty (say 60s) and then when the timer fires set started to false and exit.
</blockquote></details>

It didn't transition back to false. Updated to kick off a timer and exit if it fires here and added some testing for it.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ecyT48PuxdK-KjNCO:-O7ewmtf6mY4GuUGirt5:b-f1ois5) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L485)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is it using the context of one of the `add` calls, given this is shared across multiple `add` calls. It seems to me that we should not propagate that context to `run`, and document here that this is a background context so we are not including context cancellation as a case in the select.
</blockquote></details>

Yeah this wasn't wise. I've remove the context cancellation references and updated them to be stopper refs. Also replaced the run ctx with a background ctx.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 536 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7ef6lH5b_XxJlFNuQ4:-O7exa_x5eA-NdD6It2h:b-b8fori) ([raw file](https://github.com/cockroachdb/cockroach/blob/545b86a2a58f031274fd1a3f0ca3ab04c751d2b5/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L536)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is this being enqueued again?

----

Never mind. I looked at the prototype and saw that we kept the handle enqueued until canceled. And we only canceled if there were actually tokens available (which should be the common case). Given that we are moving this to the end of the queue, this behavior is no better than registering a new handle. So I think we should just simplify the behavior and make it a one shot notification. We will still need `CancelHandle` as a best-effort cancellation, for `replicaSendStreams` being closed or force-flushed, though there is no guarantee that the notification is not already in progress.
</blockquote></details>

Yeah that was the reason why. Removed the re-enqueue and updated the relevant comments.

**Comment by kvoli** [comment]
TYFTR, should be good for another round @sumeerbhola.

**Comment by kvoli** [comment]
Actually, it looks like I left in some log statements. Ignoring those, which I'll clean up shortly, it is ready.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131133)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 518 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7jgqPZCW3Rh1yaGHGo:-O7jgqPZCW3Rh1yaGHGp:b-gzks7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3153f606a90394936e6caa5d344afa8c4ec47379/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L518)):*
> ```Go
> 				w.timer.MarkRead()
> 				w.timer.Stop()
> 				w.markStopped()
> ```

What is preventing the receive from the timer channel racing with the receive from the nonEmptyCh? If the former gets ahead, we will think that `started` is true and not create a goroutine in push, but the goroutine sees the timer fire first and then sets started=false. I think we need atomicity in checking that there is nothing in the queue and setting started to false. I think we would want two state transitions that are atomic:

push (while holding the lock):
```
  push onto queue
  if queue was empty {
      signal the channel
      get current value of started
      if current value is false {
         started = true
      }
   }
```

After releasing the lock:
  if last value of started was false, start the goroutine

inside the goroutine for case <-w.timer.Ch():
```
  w.timer.MarkRead()
  w.timer.Stop()
  while holding the lock {
     if queue is non-empty, ignore
     else started = false and exit
  }
```
 
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/send_token_watcher` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7jkYyACAkBBWvBpvyo:-O7jkYyACAkBBWvBpvyp:b-q5k16z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3153f606a90394936e6caa5d344afa8c4ec47379/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/send_token_watcher#L70)):*
> ```
> # tokens when they are notified as well. Expect 'b' to transition 'notified' =>
> # 'cancelled'.
> cancel name=b
> ```

is this relevant anymore, given b is notified?

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131133)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 518 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7jgqPZCW3Rh1yaGHGo:-O7jthXTBJ3YTK9ELM5G:bt1q8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3153f606a90394936e6caa5d344afa8c4ec47379/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L518)):*
Ah nice catch, there is nothing preventing a race like:

```
t=0   (empty)
t=60
          w.nonEmptyCh <- struct{}{} (add)
         <- timer.Ch()
         exit, started=false and the queue has 1 item
```

For:

```
  push onto queue
  if queue was empty {
      signal the channel
      get current value of started
      if current value is false {
         started = true
      }
   }
```

> After releasing the lock:  
> if last value of started was false, start the goroutine

I don't follow why this is needed. Isn't it sufficient to sync on started and empty, why do we also need to start the goroutine outside the lock? It is async w.r.t the caller. In any execution path, wouldn't checking `empty` and setting `started=false` before returning under a lock inside `<-w.timer.Ch():` ensure that no concurrent goroutine could add something and not start the watcher, or start multiple watchers -- assuming the push is atomic w.r.t these variables, which it already was.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/send_token_watcher` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7jkYyACAkBBWvBpvyo:-O7jqqbuAriFcUpvkKaN:bleb86u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3153f606a90394936e6caa5d344afa8c4ec47379/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/send_token_watcher#L70)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this relevant anymore, given b is notified?
</blockquote></details>

Not really relevant, its just a testing detail. I'll remove this one.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131133)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 518 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7jgqPZCW3Rh1yaGHGo:-O7k--KWBMxKg-2KNpr9:b-8njwdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3153f606a90394936e6caa5d344afa8c4ec47379/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L518)):*
> Isn't it sufficient to sync on started and empty, why do we also need to start the goroutine outside the lock? It is async w.r.t the caller.

No reason. Starting under the lock is ok too.

**Comment by kvoli** [comment]
Needed a `nolint:deferunlock`. Should be ready for another round.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-:-O7kknQiDl60bGnQ62GK:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 531 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7kkUMQE4y9nloDCe9p:-O7kkUMQE4y9nloDCe9q:b-s9qrwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/60a5b8db8da626ddf328627769a41e338d993155/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L531)):*
> ```Go
> 				if w.emptyLocked() {
> 					defer w.mu.Unlock()
> 					clear(w.mu.queueItems)
> ```

why are we clearing if it is empty? In general we should never be clearing items that we are not going to process. The caller expects the callback unless it cancels it.

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-:-O82I2Mh6puY7WEGodfx:bzftgo7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 531 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-O7kkUMQE4y9nloDCe9p:-O82I4lC7ug0XAjKsn_n:b-895okl) ([raw file](https://github.com/cockroachdb/cockroach/blob/60a5b8db8da626ddf328627769a41e338d993155/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L531)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why are we clearing if it is empty? In general we should never be clearing items that we are not going to process. The caller expects the callback unless it cancels it.
</blockquote></details>

It was defensive but pointless, the `emptyLocked` is checking the map length, so the clear is a no-op (maybe there's some GC benefit idk). Removed.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131133#-:-O82TuyLDGxRgHNW0kv9:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Comment by kvoli** [comment]
Merge skew, going to rebase and fix the test issue.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Pull request merged**
