### PR TITLE
kvserver: Use response data in the load-based splitter

### LINKED ISSUE #87279: workload: ycsb-e creates a single hot range
**Describe the problem**

Running the YCSB-E workload, one range has 99% of the request load and remains above the split threshold, despite not splitting.

image

The range appears to have sufficient rows to split:

image

```
 /Table/106/1 to /Max
```

This causes a hotspot to develop on the leaseholder for this range. Which does not dissipate. 

**To Reproduce**

```bash
export gce_project=cockroach-ephemeral
export email=austen-ycsbe
roachprod create $email -n 8 --gce-machine-type=n1-standard-16

# recent commit on master
roachprod stage $email cockroach 4f0065ad010cee1ce50bbc65019b26f93a7dc6ad
roachprod start $email:1-7

# stimulate some rebalancing activity
roachprod run $email:8 -- './cockroach workload init ycsb --workload E --drop {pgurl:1-7}'
roachprod run $email:8 -- './cockroach workload run ycsb --max-rate 50000 --workload E {pgurl:1-7}'

```

Jira issue: CRDB-19250

### PR DESCRIPTION
**Pull request by KaiSun314**
Fixes #87279

We investigated why running YCSB Workload E results in a single hot
range and we observed that range queries of the form
SELECT * FROM table WHERE pkey >= A LIMIT B will result in all request
spans having the same end key - similar to [A, range_end) - rather than
end keys that take into account the specified LIMIT. Since the majority
of request spans have the same end key, the load splitter algorithm
cannot find a split key without too many contained and balance between
left and right requests. A proposed solution is to use the response span
rather than the request span, since the response span is more accurate
in reflecting the keys that this request truly iterated over. We utilize
the request span as well as the response's resume span to derive the key
span that this request truly iterated over. Using response data (resume
span) rather than just the request span in the load-based splitter
(experimentally) allows the load-based splitter to find a split key
under range query workloads (YCSB Workload E, KV workload with spans).

Ops/sec for YCSB-E workload with / without this change and various number of nodes (3 / 5) and CPUs (8 / 32): https://docs.google.com/spreadsheets/d/1OcvRUkXORiGpr-f7cMAiuv9DW7qQZgconfqE4UbfQ2c/edit?usp=sharing

Release note (ops change): We use response data rather than just the
request span in the load-based splitter to pass more accurate data
about the keys iterated over to the load splitter to find a suitable
split key, enabling the load splitter to find a split key under heavy
range query workloads.

### CODE REVIEW

**Review by kvoli — COMMENTED** [review]
Nice patch. Can you post the results of running ycsb-e for the unsplittable metrics and workload ops/s when you get a chance.

Going to tag @aayushshah15 to also take a look.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89217#-:-NDdodXG15h77cbLhAXj:b-5bojq2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/replica_send.go` line 405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89217#-NDdkJc2Ef77VlD9xoKw:-NDdkJc2Ef77VlD9xoKx:b-rblbjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/09d7d5ee5cfad20269c375ffa93b94e75c7ac47b/pkg/kv/kvserver/replica_send.go#L405)):*
> ```Go
> 					// Request:    [key...............endKey]
> 					// ResumeSpan:          [key......endKey]
> 					// True span:  [key......key]
> ```

nit: for clarity, add in `[key,endKey)` rather than `[]`.  To avoid any confusion about the`endKey` being inclusive when it is exclusive.



_Code quote:_
```Go
					// Request:    [key...............endKey]
					// ResumeSpan:          [key......endKey]
					// True span:  [key......key]
```

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89217)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @kvoli)

___
*[`pkg/kv/kvserver/replica_send.go` line 405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89217#-NDdkJc2Ef77VlD9xoKw:-NDhpqUX9DneGpE5Hspa:b1imalp) ([raw file](https://github.com/cockroachdb/cockroach/blob/09d7d5ee5cfad20269c375ffa93b94e75c7ac47b/pkg/kv/kvserver/replica_send.go#L405)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: for clarity, add in `[key,endKey)` rather than `[]`.  To avoid any confusion about the`endKey` being inclusive when it is exclusive.
</blockquote></details>

Done. Changed to [key, endKey). Also changed for reverse scan comment below, just want to confirm that reverse scans are also exclusive [key, endKey)?

**Review by kvoli — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89217#-:-NE6EMB22Wfbws0zIZCy:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[`pkg/kv/kvserver/replica_send.go` line 405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89217#-NDdkJc2Ef77VlD9xoKw:-NE6EFAm53HBmCC6X-2A:b-c0w660) ([raw file](https://github.com/cockroachdb/cockroach/blob/09d7d5ee5cfad20269c375ffa93b94e75c7ac47b/pkg/kv/kvserver/replica_send.go#L405)):*
<details><summary><i>Previously, KaiSun314 (Kai Sun) wrote…</i></summary><blockquote>

Done. Changed to [key, endKey). Also changed for reverse scan comment below, just want to confirm that reverse scans are also exclusive [key, endKey)?
</blockquote></details>

That's right, take a look at this comment. It is specific to spans:

https://github.com/cockroachdb/cockroach/blob/20e55fcca7651472a6b112900c413e67b270979f/pkg/roachpb/data.pb.go#L285-L288

**Review by aayushshah15 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89217)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/replica_send.go` line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89217#-NESQx_x0f1o2twgwj9X:-NESQx_x0f1o2twgwj9Y:biyd0k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d117916b749dda9901de7bca4225e4485baf433/pkg/kv/kvserver/replica_send.go#L381)):*
> ```Go
> var _ batchExecutionFn = (*Replica).executeReadOnlyBatch
> 
> func getTrueSpans(
> ```

This function re-implements the logic represented by `Replica.collectSpansRead()`. Let's reuse that method here. Also note the special handling for `SkipLocked` requests that is dealt with in `collectSpansRead`. Making this change should simplify this patch significantly.

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89217)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @kvoli)

___
*[`pkg/kv/kvserver/replica_send.go` line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89217#-NESQx_x0f1o2twgwj9X:-NElGNkdEn_9mVNGRrN3:b-heexo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d117916b749dda9901de7bca4225e4485baf433/pkg/kv/kvserver/replica_send.go#L381)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

This function re-implements the logic represented by `Replica.collectSpansRead()`. Let's reuse that method here. Also note the special handling for `SkipLocked` requests that is dealt with in `collectSpansRead`. Making this change should simplify this patch significantly.
</blockquote></details>

Done.

For SkipLocked requests, my understanding is that the spans returned will contain one span for each key in the response. I think using Replica.collectSpansRead() in this case should still be fine, since we take the union of all the spans returned?

**Review by aayushshah15 — APPROVED** [review]

**Comment by KaiSun314** [comment]
TFTRs!

Bazel Extended CI test failures appear to be unrelated.

bors r+

**Comment by kvoli** [comment]
Try rebasing on master - it looks like a persistent issue with that test that is unrelated.

**Comment by knz** [comment]
alas master is where the problem is. That's why the bors run failed and not the original CI on this PR.

**Pull request merged**
