### PR TITLE
cmd/github-post: post top stack traces on Fatal or panic

### PR DESCRIPTION
**Pull request by tamird**
Previously, we'd always keep the end of the log when truncating to
Github's length limit; we now keep the head of the log if the failure
includes stack traces, since that tends to be the interesting part.

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm:

As a future improvement idea, maybe we should just gist these stack traces and only include a small summary in the comment?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15986#-:-KkM2nU1XTch5-yOGEgW:bazrio0)*

**Comment by tamird** [comment]
I'm not sure that improves usability. FWIW, the reason this PR even exists is because "small summary" is rather difficult to define while keeping it useful.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15986#-:-KkM39n3xecoqidr1o4L:bo13hmo)*

**Comment by jordanlewis** [comment]
I understand that. I think it would help usability if we could figure out a way to detect the goroutine that caused the panic and print its stack trace only, or just print that there was a timeout if that happened.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15986#-:-KkM42Cc3CfFaUb54GR5:br0dj1i)*

**Review by a-robinson — COMMENTED** [review]
Thanks @tamird!

**Pull request merged**
