### PR TITLE
sql: include referencing tables into the bundle schema

### LINKED ISSUE #111585: sql: add foreign key references to stmt bundle schema
Today, statement bundles of queries that may involve foreign key cascades may not include target tables of the cascade. That is, we include the parent table in schema.sql, but not the child tables that may reference it. For example, in https://github.com/cockroachlabs/support/issues/2630 there was a delete with multiple cascades to different tables, but none of the relevant child tables are included in the schema. We should look into adding this to the statement bundle.

Jira issue: CRDB-31977
Epic: CRDB-34181

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, when collecting the set of tables to include into the schema for the stmt bundle we'd only include tables that we reference via FK relationship ("referenced" tables). However, it can be beneficial to also include tables that reference us ("referencing" tables) - for example, in case the FK constraint has a cascade action. This commit includes referencing tables into the set. Note that we probably could have included only referencing tables with cascades, but including extra tables is unlikely to be problematic, so we lean on the side of including more.

Co-authored with @rharding6373.

Fixes: #111585.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118157#-:-Nox9ASB6lWdmqLfN7kR:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

**Comment by rytaft** [comment]
Is it worth adding an explicit test for this?

**Comment by yuzefovich** [comment]
I think existing `EXPLAIN (OPT, ENV)` are sufficient - in the encoded string we can see the order of tables that would be used for recreation, and Rachael and I were using those to figure out what are the correct changes to achieve what we want. Do you think other tests would be helpful? What do you have in mind? Like adding a unit test for `getAllReferenceTables` specifically?

**Comment by rytaft** [comment]
I was just thinking you could update the "foreign keys" test in `explain_bundle_test.go`

**Review by mgartner — APPROVED** [review]
:lgtm: +1 to updating the test

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118157#-:-Np0AT5x5O_ytKLVP-mV:bcwbry9)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @rharding6373)

**Comment by yuzefovich** [comment]
Good point, extended the existing foreign key test in `TestExplainAnalyzeDebug`.

TFTRs!

bors r+

**Pull request merged**
