### PR TITLE
storage: set the last GC expiration time on replicas

### PR DESCRIPTION
**Pull request by madelynnblue**
This is in preparation for time travel queries (#5963). It will work in
conjunction with #6778, but does not require that PR to go in first. A
future PR, after these are both merged, will enforce reads and writes
happen after the last GC expiration of a replica.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6831)

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica.go, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIJ73VSyMx8BTpeVN5z:-KIJ73VSyMx8BTpeVN6-:-533135858) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica.go#L227)):*
> ```Go
> 		// WallTime in ns at which last GC occurred. Reads and writes should not
> 		// happen <= this time.
> 		lastGC int64
> ```

Why `int64` wall time? Shouldn't this be a `roachpb.Timestamp`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica.go, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIJ73VSyMx8BTpeVN5z:-KIMCdZ2nBTm4_bbOKko:318724839) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica.go#L227)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Why `int64` wall time? Shouldn't this be a `roachpb.Timestamp`?
</details>
Probably yes. I made it `int64` because the `engin.MVCCPut` wants a `roachpb.Value`, which doesn't appear to have a handy `SetTimestamp` method. So I think it'd have to marshal a `roachpb.Timestamp` to bytes, then use `SetBytes`, right? Is that better than an int64?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica.go, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIJ73VSyMx8BTpeVN5z:-KIVu0Jp5L8xMRiouhou:421752823) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica.go#L227)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Probably yes. I made it `int64` because the `engin.MVCCPut` wants a `roachpb.Value`, which doesn't appear to have a handy `SetTimestamp` method. So I think it'd have to marshal a `roachpb.Timestamp` to bytes, then use `SetBytes`, right? Is that better than an int64?
</details>
It doesn't have a `SetTimestamp`, but it does have a `SetProto` (and `roachpb.Timestamp` implements `proto.Message`). After thinking about this some more I'm not sure whether it really matters here, though. We're always constructing these timestamps based on wall time, never deriving them from the MVCC values. It's probably still better to store the `roachpb.Timestamp`, though - that could be useful if we introduce other GC policies that are not based on fixed time intervals. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831)*

**Comment by tschottdorf** [comment]
Needs a test. Content-wise LGTM mod the timestamp, most of my comments are about naming and commentary.

<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> #### storage: set the last GC expiration time on replicas
> 
> This is in preparation for time travel queries (#5963). It will work in
> 
> conjunction with #6778, but does not require that PR to go in first. A
> 
> future PR, after these are both merged, will enforce reads and writes
> 
> happen after the last GC expiration of a replica.
> 
> 
> 
</details>


---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/gc_queue.go, line 372 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIYDm4Y_C6NeGtHXANc:-KIYDm4Y_C6NeGtHXANd:-1192952494) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/gc_queue.go#L372)):*
> ```Go
> 	// ResolveErrors is the number of successful intent resolutions.
> 	ResolveSuccess int
> 	// Expiration is the computed expiration timestamp in ns.
> ```

If I didn't know what this was already, I wouldn't know from the description. Expand the comment (similar to what I suggest in `(Replica).lastGC`) and/or rename this field - `Threshold`?

---

*[storage/replica.go, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIJ73VSyMx8BTpeVN5z:-KIYDGxKcvEjgQTef2ic:713830474) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica.go#L227)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> It doesn't have a `SetTimestamp`, but it does have a `SetProto` (and `roachpb.Timestamp` implements `proto.Message`). After thinking about this some more I'm not sure whether it really matters here, though. We're always constructing these timestamps based on wall time, never deriving them from the MVCC values. It's probably still better to store the `roachpb.Timestamp`, though - that could be useful if we introduce other GC policies that are not based on fixed time intervals. 
</details>
Yeah, better to make this a `roachpb.Timestamp`. Also, the description is incorrect (unless you're doing something other than what we've discussed). This timestamp should be the threshold used by the last GC, i.e. the timestamp below which reads are disallowed because the data they would read might've been GC'ed.
It should also be renamed - maybe to `lastGCThreshold` (assuming you rename `Expiration` to `Threshold` in `GCInfo`), with the rename trickling down to other places (`setLastGC`, etc). Now that I think of it, `gcThreshold` is even better - it's the max of all gc thresholds ever, so nothing specific about the last gc.

---

*[storage/replica_command.go, line 1033 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIYE_3-6OLvmLzu7A51:-KIYE_3-6OLvmLzu7A52:1268388891) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica_command.go#L1033)):*
> ```Go
> 	updateLast := args.Expiration > r.mu.lastGC
> 	r.mu.Unlock()
> 	if !updateLast {
> ```

I don't think it's worth to guard this - just always run it.

---

*[storage/replica_command.go, line 1039 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIYEQJPhPLZJn0CegyF:-KIYEQJPhPLZJn0CegyG:-718661750) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica_command.go#L1039)):*
> ```Go
> 	batch.Defer(func() {
> 		r.mu.Lock()
> 		r.mu.lastGC = args.Expiration
> ```

You'll be able to simply `r.mu.lastGCThreshold.Forward(args.Expiration)`.

---

*[storage/engine/gc.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIYEkJ9vI-9ryVtyJmy:-KIYEkJ9vI-9ryVtyJmz:1567893725) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/engine/gc.go#L29)):*
> ```Go
> // versions and maximum age.
> type GarbageCollector struct {
> 	Expiration roachpb.Timestamp
> ```

Ah, that's where `Expiration` comes from. If you think that is a clear name for someone who doesn't know what's going on, keep it and just add comments in the other places (it's reasonably clear here because of context, but I think less so when the name is used elsewhere), though I personally would find a better name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-:-KIYFJdDWa-ajO5YkO2c:-278489067)*

**Comment by mjibson** [comment]
Added a test, renamed some stuff, changed type to Timestamp.

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Needs a test. Content-wise LGTM mod the timestamp, most of my comments are about naming and commentary.
</details>


---

Review status: 2 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/gc_queue.go, line 372 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIYDm4Y_C6NeGtHXANc:-KIZ4PFBAcFWXi3p9qUV:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/gc_queue.go#L372)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> If I didn't know what this was already, I wouldn't know from the description. Expand the comment (similar to what I suggest in `(Replica).lastGC`) and/or rename this field - `Threshold`?
</details>
Done.

---

*[storage/replica.go, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIJ73VSyMx8BTpeVN5z:-KIZ4SQ7PSboVtOVI-4i:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica.go#L227)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Yeah, better to make this a `roachpb.Timestamp`. Also, the description is incorrect (unless you're doing something other than what we've discussed). This timestamp should be the threshold used by the last GC, i.e. the timestamp below which reads are disallowed because the data they would read might've been GC'ed.
> It should also be renamed - maybe to `lastGCThreshold` (assuming you rename `Expiration` to `Threshold` in `GCInfo`), with the rename trickling down to other places (`setLastGC`, etc). Now that I think of it, `gcThreshold` is even better - it's the max of all gc thresholds ever, so nothing specific about the last gc.
</details>
Done.

---

*[storage/replica_command.go, line 1033 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIYE_3-6OLvmLzu7A51:-KIYnvfe16MCED5YAPU8:88225494) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica_command.go#L1033)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I don't think it's worth to guard this - just always run it.
</details>
What if a a GC with threshold `t2` happens, and then one happens later with threshold `t1` (where `t1` is before `t2`)? That would set gcThreshold to a time earlier than it has data for. Is this guaranteed to not happen at some other layer?

---

*[storage/engine/gc.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIYEkJ9vI-9ryVtyJmy:-KIZ4UnIf5hK6gucpzrt:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/engine/gc.go#L29)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Ah, that's where `Expiration` comes from. If you think that is a clear name for someone who doesn't know what's going on, keep it and just add comments in the other places (it's reasonably clear here because of context, but I think less so when the name is used elsewhere), though I personally would find a better name.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-:-KIZtIDoKbjjNo0rW1EN:1532435491)*

**Comment by tschottdorf** [comment]
:lgtm:

<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Added a test, renamed some stuff, changed type to Timestamp.
</details>


---

Reviewed 10 of 10 files at r1, 2 of 2 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[roachpb/api.proto, line 413 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIZy51N8Cip8k0eAA5q:-KIZy51OJ5jPv6gvyENI:458172748) ([raw file](https://github.com/cockroachdb/cockroach/blob/fef68d21e1ec35c332360816563c69a549dd17b0/roachpb/api.proto#L413)):*
> ```protobuf
>   }
>   repeated GCKey keys = 3 [(gogoproto.nullable) = false];
>   optional Timestamp threshold = 4 [(gogoproto.nullable) = false];
> ```

Add a comment while you're here.

---

*[storage/replica.go, line 225 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIZyKOO0GSf0EB0abYg:-KIZyKOO0GSf0EB0abYh:1977459787) ([raw file](https://github.com/cockroachdb/cockroach/blob/fef68d21e1ec35c332360816563c69a549dd17b0/storage/replica.go#L225)):*
> ```Go
> 		// Most recent timestamps for keys / key ranges.
> 		tsCache *timestampCache
> 		// gcThreshold is the GC threshold of the replica. Reads and writes should
> ```

s/should/must/

---

*[storage/replica.go, line 497 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KI_-Ayl27gYmSHSuyEa:-KI_-Aymbywy2Rbsd_5X:1441857398) ([raw file](https://github.com/cockroachdb/cockroach/blob/fef68d21e1ec35c332360816563c69a549dd17b0/storage/replica.go#L497)):*
> ```Go
> 	var val roachpb.Value
> 	val.SetProto(threshold)
> 	return engine.MVCCPut(context.Background(), eng, ms,
> ```

`MVCCPutProto` also exists.

---

*[storage/replica.go, line 503 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KI_-JG96VwIryej_8Rm:-KI_-JG96VwIryej_8Rn:-1199920708) ([raw file](https://github.com/cockroachdb/cockroach/blob/fef68d21e1ec35c332360816563c69a549dd17b0/storage/replica.go#L503)):*
> ```Go
> func loadGCThreshold(eng engine.Engine, rangeID roachpb.RangeID) (roachpb.Timestamp, error) {
> 	var t roachpb.Timestamp
> 	val, _, err := engine.MVCCGet(context.Background(), eng, keys.RangeLastGCKey(rangeID),
> ```

`MVCCGetProto` exists.

---

*[storage/replica_command.go, line 1033 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIYE_3-6OLvmLzu7A51:-KIZyZfE6dpKOMyE0Hvb:-484338175) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica_command.go#L1033)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> What if a a GC with threshold `t2` happens, and then one happens later with threshold `t1` (where `t1` is before `t2`)? That would set gcThreshold to a time earlier than it has data for. Is this guaranteed to not happen at some other layer?
</details>
I think you would always update to the maximum of all values seen. Something like

```go
r.mu.Lock()
newThreshold := r.mu.gcThreshold
newThreshold.Forward(args.Threshold)
r.mu.Unlock()

// use newThreshold for both the batch.Defer and `setGCThreshold`
```

We just have to be careful that GC requests always overlap (and they do; we address them to the whole range). Otherwise, there could be write skew in between us computing the new threshold and actually writing it (but that is the same with the current code).

---

*[storage/replica_raftstorage.go, line 725 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIZzkWCQ2dUP_aULRVU:-KIZzkWCQ2dUP_aULRVV:55823382) ([raw file](https://github.com/cockroachdb/cockroach/blob/fef68d21e1ec35c332360816563c69a549dd17b0/storage/replica_raftstorage.go#L725)):*
> ```Go
> 		r.mu.leaderLease = lease
> 		r.mu.frozen = frozen
> 		r.mu.gcThreshold = lastGC
> ```

s/GC/Threshold/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-:-KI_-TjFAVtqi7PdOab-:1417088721)*

**Comment by mjibson** [comment]
Review status: 6 of 11 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[roachpb/api.proto, line 413 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIZy51N8Cip8k0eAA5q:-KIiD0B-65amzlqAET62:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/fef68d21e1ec35c332360816563c69a549dd17b0/roachpb/api.proto#L413)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Add a comment while you're here.
</details>
Done.

---

*[storage/replica.go, line 225 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIZyKOO0GSf0EB0abYg:-KIiD16pAXX3LCSgQi98:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/fef68d21e1ec35c332360816563c69a549dd17b0/storage/replica.go#L225)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/should/must/
</details>
Done.

---

*[storage/replica.go, line 497 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KI_-Ayl27gYmSHSuyEa:-KIiD1uK0aI5H4XzQjAs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/fef68d21e1ec35c332360816563c69a549dd17b0/storage/replica.go#L497)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> `MVCCPutProto` also exists.
</details>
Done.

---

*[storage/replica.go, line 503 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KI_-JG96VwIryej_8Rm:-KIiD2NKdsmgVTG34XNC:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/fef68d21e1ec35c332360816563c69a549dd17b0/storage/replica.go#L503)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> `MVCCGetProto` exists.
</details>
Done.

---

*[storage/replica_command.go, line 1033 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIYE_3-6OLvmLzu7A51:-KIiD4-pAQVu7p0es1rM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica_command.go#L1033)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I think you would always update to the maximum of all values seen. Something like
> 
> ```go
> r.mu.Lock()
> newThreshold := r.mu.gcThreshold
> newThreshold.Forward(args.Threshold)
> r.mu.Unlock()
> 
> // use newThreshold for both the batch.Defer and `setGCThreshold`
> ```
> 
> We just have to be careful that GC requests always overlap (and they do; we address them to the whole range). Otherwise, there could be write skew in between us computing the new threshold and actually writing it (but that is the same with the current code).
</details>
Done.

---

*[storage/replica_raftstorage.go, line 725 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIZzkWCQ2dUP_aULRVU:-KIiD7CtMR7An0MEzMY2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/fef68d21e1ec35c332360816563c69a549dd17b0/storage/replica_raftstorage.go#L725)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/GC/Threshold/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831)*

**Comment by tschottdorf** [comment]
still :LGTM:.

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> :lgtm:
</details>


---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 1033 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-KIYE_3-6OLvmLzu7A51:-KIiGWpr7ngP4BkPl5Nm:-160693215) ([raw file](https://github.com/cockroachdb/cockroach/blob/6725221ad276a959c7d57d72557721caa78478c0/storage/replica_command.go#L1033)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Done.
</details>
BTW, my comment above about concurrent requests is nonsense. This is inside of Raft, so only one would apply at a time anyway. Still, better this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6831#-:-KIiHP1sukZJ2DxGu3hc:1743841477)*

**Pull request merged**
