### PR TITLE
storeliveness: SupportManager improvements and bug fixes

### PR DESCRIPTION
**Pull request by miraradeva**
This PR includes 3 commits: 2 of them fix a couple of `SupportManager` bugs, and the third one improves the process of stopping heartbeats for idle stores. See individual commits for more details.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130101)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62z47v9M3pTNmGSbR6):*
"invariants"
___
*[`-- commits` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62z8sH6RcirNKgVA4R):*
s/it/is/
___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62zL4p2RWcp6RH0KTN):*
nit: the wording here is a bit off regarding singular vs. plural. "impact", "they"
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62x1zS9MtpHB3b4xjQ:-O62x1zS9MtpHB3b4xjR:bhpwz72) ([raw file](https://github.com/cockroachdb/cockroach/blob/0819c39cbbf1eb5c6c4f9449cee9329942daa766/pkg/kv/kvserver/storeliveness/requester_state.go#L49)):*
> ```Go
> 	// needs to lock requesterStateHandler.mu for reading to ensure that no new
> 	// stores are added to the supportFrom map.
> 	recentlyQueried atomic.Value // recentlyQueriedState
> ```

`atomic.Value` boxes values in an interface and incurs heap allocation costs as a result. It's not actually generic. We should use an `atomic.Int32` instead.
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62y1ZSC9mercLnhRT4:-O62y1ZSC9mercLnhRT5:b-3212gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0819c39cbbf1eb5c6c4f9449cee9329942daa766/pkg/kv/kvserver/storeliveness/requester_state.go#L191)):*
> ```Go
> 	defer rsh.mu.RUnlock()
> 	for _, rs := range rsh.requesterState.supportFrom {
> 		if !rs.recentlyQueried.CompareAndSwap(active, inactive) {
> ```

It's tempting to use `atomic.Int32.Add(1)` here to avoid having to think about races with these two CASs and concurrent Stores, but that doesn't quite work.

I guess the following does, but I doubt we want it:
```go
if rs.recentlyQueried.Load() != idle {
    rs.recentlyQueried.Add(1)
}
```
What you have here does seem to work, so no need to change it.
___
*[`pkg/kv/kvserver/storeliveness/supporter_state.go` line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O63-0YU8Y-2oRfNMcxP:-O63-0YVEyuvQqj6PRms:bah2bct) ([raw file](https://github.com/cockroachdb/cockroach/blob/8547230aa84c3fc48385311b4191ff6a18bf1509/pkg/kv/kvserver/storeliveness/supporter_state.go#L154)):*
> ```Go
> 
> // write writes the supporter meta and supportFor to disk if they changed in
> // this update. Use a batch to avoid potentially writing multiple support states
> ```

`s/Use/Accepts/`
___
*[`pkg/kv/kvserver/storeliveness/testdata/requester_state` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62yqnf1n7vwWWfGcj4:-O62yqnf1n7vwWWfGcj5:b3r3vx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0819c39cbbf1eb5c6c4f9449cee9329942daa766/pkg/kv/kvserver/storeliveness/testdata/requester_state#L164)):*
> ```
> support from:
> {Target:{NodeID:2 StoreID:2} Epoch:2 Expiration:410.000000000,0}
> ```

Should we show here that heartbeats are still sent to store 2?
___
*[`pkg/kv/kvserver/storeliveness/support_manager_test.go` line 429 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O631eIa8PPlRZUwzF_Y:-O631eIb8ZFGZZLh4e-B:bno54g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8547230aa84c3fc48385311b4191ff6a18bf1509/pkg/kv/kvserver/storeliveness/support_manager_test.go#L429)):*
> ```Go
> type testBatch struct {
> 	storage.Batch
> 	errorOnWrite bool
> ```

To avoid confusion in the future, should we add support for `blockOnWrite` to `testBatch` as well?

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130101)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62z47v9M3pTNmGSbR6):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"invariants"
</blockquote></details>

Done
___
*[`-- commits` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62z8sH6RcirNKgVA4R):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/it/is/
</blockquote></details>

Done
___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62zL4p2RWcp6RH0KTN):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: the wording here is a bit off regarding singular vs. plural. "impact", "they"
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62x1zS9MtpHB3b4xjQ:-O67VigBAVTbWR5IIYEn:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0819c39cbbf1eb5c6c4f9449cee9329942daa766/pkg/kv/kvserver/storeliveness/requester_state.go#L49)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`atomic.Value` boxes values in an interface and incurs heap allocation costs as a result. It's not actually generic. We should use an `atomic.Int32` instead.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62y1ZSC9mercLnhRT4:-O67Vp6MDCuTZIqqT075:b-pfsayt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0819c39cbbf1eb5c6c4f9449cee9329942daa766/pkg/kv/kvserver/storeliveness/requester_state.go#L191)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's tempting to use `atomic.Int32.Add(1)` here to avoid having to think about races with these two CASs and concurrent Stores, but that doesn't quite work.

I guess the following does, but I doubt we want it:
```go
if rs.recentlyQueried.Load() != idle {
    rs.recentlyQueried.Add(1)
}
```
What you have here does seem to work, so no need to change it.
</blockquote></details>

A circular linked list with 3 values is what we need.
___
*[`pkg/kv/kvserver/storeliveness/supporter_state.go` line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O63-0YU8Y-2oRfNMcxP:-O67W2FD4nNQeV3G2oLp:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8547230aa84c3fc48385311b4191ff6a18bf1509/pkg/kv/kvserver/storeliveness/supporter_state.go#L154)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/Use/Accepts/`
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/testdata/requester_state` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O62yqnf1n7vwWWfGcj4:-O67WRaC01hxxEJe02vN:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0819c39cbbf1eb5c6c4f9449cee9329942daa766/pkg/kv/kvserver/storeliveness/testdata/requester_state#L164)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we show here that heartbeats are still sent to store 2?
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/support_manager_test.go` line 429 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O631eIa8PPlRZUwzF_Y:-O67XLmq2lvQv3_QCTlR:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8547230aa84c3fc48385311b4191ff6a18bf1509/pkg/kv/kvserver/storeliveness/support_manager_test.go#L429)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

To avoid confusion in the future, should we add support for `blockOnWrite` to `testBatch` as well?
</blockquote></details>

Done

**Review by nvb — APPROVED** [review]
:lgtm: after the two remaining comments are addressed.

> Reviewed 9 of 9 files at r4, 2 of 2 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-:-O67btYSA7qB8m9908q1:bi8gnar)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O67b-n21cRuQnvQndwH:-O67b-n21cRuQnvQndwI:bpr3a66) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7cc5316a5dd18d309f0d86e21a620c58d41ccf/pkg/kv/kvserver/storeliveness/requester_state.go#L166)):*
> ```Go
> 		rs := requestedSupport{
> 			state:           slpb.SupportState{Target: id, Epoch: rsh.requesterState.meta.MaxEpoch},
> 			recentlyQueried: atomic.Int32{},
> ```

The zero value for `atomic.Int32` is usable, so we don't need this line.

Arguably, we don't even need the `rs.recentlyQueried.Store(active)` below either, but I'll defer to you on whether you'd think there's value in being explicit about the initial value of the field and not assuming that `active` is the zero value.
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 169 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O67bGX2ANltepyBKtTM:-O67bGX2ANltepyBKtTN:b-ief86v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7cc5316a5dd18d309f0d86e21a620c58d41ccf/pkg/kv/kvserver/storeliveness/requester_state.go#L169)):*
> ```Go
> 		}
> 		// Adding a store is done in response to SupportFrom, so it's ok to set
> 		// recentlyQueried to true here. This also ensures the store will not be
> ```

s/true/active/

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130101)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O67b-n21cRuQnvQndwH:-O67eE_u2uyD6Wh6nSJy:b-kjnhl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7cc5316a5dd18d309f0d86e21a620c58d41ccf/pkg/kv/kvserver/storeliveness/requester_state.go#L166)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The zero value for `atomic.Int32` is usable, so we don't need this line.

Arguably, we don't even need the `rs.recentlyQueried.Store(active)` below either, but I'll defer to you on whether you'd think there's value in being explicit about the initial value of the field and not assuming that `active` is the zero value.
</blockquote></details>

I'll remove the initialization line, but I think I like the other assignment being explicit.
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 169 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-O67bGX2ANltepyBKtTM:-O67eKh89VtOBAAFr1g7:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7cc5316a5dd18d309f0d86e21a620c58d41ccf/pkg/kv/kvserver/storeliveness/requester_state.go#L169)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/true/active/
</blockquote></details>

Done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130101#-:-O67foNJDMSBsvT6avBq:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva)

**Comment by miraradeva** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
