### PR TITLE
issues: improve panic/Fatal handling in default issue template

### PR DESCRIPTION
**Pull request by tbg**
Test flake issues are most actionable if the failure mode is visible at
a glance. This is typically either the way in which the test failed
(i.e. the stuff after `--- FAIL:`) or a crash. We were doing a poor job
with the latter.

This commit changes that by grabbing fatal errors and panics from the
test log. If one is found, the standard template will be smart about
it, putting the error message and goroutine stack front and center.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Looks like this:

image


image

**Review by jordanlewis — COMMENTED** [review]
Looks great except for the accidentallyquadratic entry, maybe it doesn't matter though up to you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43115#-:-Lvvni155aIO_hKBffnM:b9xtrkl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @jordanlewis, and @tbg)

___
*[pkg/cmd/internal/issues/condense.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43115#-LvvXLwD6tQy4gl-5ngl:-LvvXLwD6tQy4gl-5ngm:bp3gg2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/261605c086e5992649a1e2a1559c5076f5ad2cab/pkg/cmd/internal/issues/condense.go#L32)):*
> ```Go
> 	for pos >= 0 && n > 0 {
> 		n--
> 		pos = strings.LastIndex(input[:pos], "\n")
> ```

Tobi isn't this an n^2 loop? :grin: Maybe it doesn't matter...

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @jordanlewis)

___
*[pkg/cmd/internal/issues/condense.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43115#-LvvXLwD6tQy4gl-5ngl:-LvygspZ9M5jD-eZUOZq:b-kxqmbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/261605c086e5992649a1e2a1559c5076f5ad2cab/pkg/cmd/internal/issues/condense.go#L32)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Tobi isn't this an n^2 loop? :grin: Maybe it doesn't matter... 
</blockquote></details>

No, `LastIndex` searches from the back: https://golang.org/src/strings/strings.go?s=2802:2838#L103

**Comment by tbg** [comment]
bors r=jordanlewis

**Pull request merged**
