### PR TITLE
sql: make NOTHING and INDEX non-reserved keywords

### LINKED ISSUE #69420: sql: doesn't allow 'index' as a column name
**Describe the problem**

Attempting to convert a PostgreSQL based application to CockroachDB. Found that CockroachDB is more strict than necessary in disallowing SQL keywords as column names. PostgreSQL works with a column named `index` while CockroachDB does not. `Index` is a pretty common name for fields since it denotes an application generated identifier that differs from a DB identifier.  Since it does not appear where the SQL keyword usually appears it should not be considered a syntax error.

**To Reproduce**

1. `cockroach demo`
2. Run SQL with reserved keyword `index` as a column name
```
demo@127.0.0.1:26257/movr> create table foo(index bigint);
invalid syntax: statement ignored: at or near ")": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
create table foo(index bigint)
                             ^
HINT: try \h CREATE TABLE
```
3. Watch it succeed after adding a `2`
```
demo@127.0.0.1:26257/movr> create table foo(index2 bigint);
CREATE TABLE

Time: 4ms total (execution 4ms / network 0ms)
```

**Expected behavior**
Parity with PostgreSQL to allow `index` as a column name.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version v21.1.6
 - Server OS: MacOS
 - Client app: cockroach sql

**Additional context**

Had to rename columns

Jira issue: CRDB-9589

### PR DESCRIPTION
**Pull request by knz**
Fixes #69420.

Release note (bug fix): It is now possible again to create tables,
views, columns, etc with the name `nothing` (e.g. `CREATE TABLE
nothing...`) without having to quote the name, like in
PostgreSQL. This bug was introduced in CockroachDB v2.0.

Release note (bug fix): It is now possible again to create tables,
views, columns, etc with the name `index` (e.g. `CREATE TABLE
index...`) without having to quote the name, like in
PostgreSQL. This bug was introduced in CockroachDB v1.0.

### CODE REVIEW

**Comment by knz** [comment]
NB: I've looked at FAMILY too but that will require a different approach. I might think about it more, perhaps in a different PR, unless you have a different idea.

**Comment by otan** [comment]
(recusing myself as i'm no longer actively involved in the experience team)

**Comment by knz** [comment]
@otan i just wanted to involve you because that might simplify some migration stuff? How are identifiers from the source database handled if they are CRDB keywords?

**Comment by otan** [comment]
when translating (at least from other languages), we rewrite the foreign language AST with the `tree` AST objects and pretty print that - `tree.Name` naturally handles this for us.

with PG we're not great at handling name differences atm, so this would help that!

**Comment by knz** [comment]
>  we rewrite the foreign language AST with the tree AST objects

Is this also done for the SQL queries that operate on the tables afterwards?

**Comment by otan** [comment]
we don't rewrite any queries atm but if we need to we could.

**Comment by knz** [comment]
yeah ok then that's one more reason to ensure that non-quoted identifiers in pg remain non-quoted in crdb.

**Review by rafiss — APPROVED** [review]
nice, thanks for the comprehensive test cases as well!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89903#-:-NEaoLtaDly9mUeYdWkm:bhb7hy5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[`docs/generated/sql/bnf/stmt_block.bnf` line 2621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89903#-NEaZSLhCBAxxPHdFXDj:-NEaZSLhCBAxxPHdFXDk:b-hunrt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7e34e6c54810f4f7be74bb679d37b61e2fd517f/docs/generated/sql/bnf/stmt_block.bnf#L2621)):*
> ```
> 	'INDEX'
> 	| 'INDEX'
> 	| 'INDEX'
> ```

should we fix something so there's no dupe in this generated doc?

**Comment by knz** [comment]
> should we fix something so there's no dupe in this generated doc?

the diagram generator already de-dups. Do we print the raw BNF in text form anywhere?

**Comment by knz** [comment]
cheers

bors r=rafiss

**Pull request merged**
