### PR TITLE
sql: fix create table failure with regional by row

### LINKED ISSUE #71600: ccl/multiregionccl: TestRegionAddDropEnclosingRegionalByRowOps failed
ccl/multiregionccl.TestRegionAddDropEnclosingRegionalByRowOps [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3588667&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3588667&tab=artifacts#/) on master @ [0984f873c6170ab34afe6fee4661fc5f76ac0dee](https://github.com/cockroachdb/cockroach/commits/0984f873c6170ab34afe6fee4661fc5f76ac0dee):

```
=== RUN   TestRegionAddDropEnclosingRegionalByRowOps/add-region-create-rbr-table#01
```
<details><summary>Reproduce</summary>
<p>
To reproduce, try:

```bash
make stressrace TESTS=TestRegionAddDropEnclosingRegionalByRowOps PKG=./pkg/ccl/multiregionccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
Parameters in this failure:

- TAGS=deadlock

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/multiregion arulajmani
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRegionAddDropEnclosingRegionalByRowOps.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-10669

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #71600

Previously, if a transaction retry error happened
during a CREATE TABLE, we could had AST changes
persist which could lead to incorrect behaviour.
For example tables with a locality of regional
by row would have an implicit column added with an
OID from the database descriptor. Unfortunately, after
a transaction retry it is possible that the OID
ID could have changed. To address this, and prevent
future issues in CREATE TABLE, we are going to clone
the AST before any modification.

Release note (bug fix): Creating a table with a locality
of regional by row could intermittently fail with a missing
type error.

### CODE REVIEW

**Review by Xiang-Gu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @Xiang-Gu)

___
*[`pkg/sql/create_table.go` line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80590#-N0gOorO9jzcB9jSfT7t:-N0gOorO9jzcB9jSfT7u:b-qjao3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0be6b321331de7c7b997be4d98ef5ff5aee640/pkg/sql/create_table.go#L263)):*
> ```Go
> 	defer func(originalDefs tree.TableDefs) { n.n.Defs = originalDefs }(n.n.Defs)
> 	n.n.Defs = defsCopy
> ```

If I understand correctly, we want to save a copy `defsCopy` to be the initial `n.n.Defs`. We then go ahead and modify `n.n.Defs` but we can rest assured that we have deferred a function that reset `n.n.Defs` back to the initial `defsCopy` that we saved and is intact.

I didn't understand the defer function where we essentially did `n.n.Defs = n.n.Defs`

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/create_table.go` line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80590#-N0gOorO9jzcB9jSfT7t:-N0gW5DR8jt1o2H3AxOR:b-157fti) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0be6b321331de7c7b997be4d98ef5ff5aee640/pkg/sql/create_table.go#L263)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

If I understand correctly, we want to save a copy `defsCopy` to be the initial `n.n.Defs`. We then go ahead and modify `n.n.Defs` but we can rest assured that we have deferred a function that reset `n.n.Defs` back to the initial `defsCopy` that we saved and is intact.

I didn't understand the defer function where we essentially did `n.n.Defs = n.n.Defs`
</blockquote></details>

The key here is that this function will be invoked when the function scope ends. With the original slice that we specified as a parameter to the call (think of that being closure capturing it in a slice). The slice afterwards could have had any value, but will be reverted back to the originally observed value

**Review by chengxiong-ruan — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80590#-:-N0gkrnp4v58IScSP3RT:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @Xiang-Gu)

___
*[`pkg/sql/create_table.go` line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80590#-N0gOorO9jzcB9jSfT7t:-N0gkJKADsk7Fjm9noYu:bxes2zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0be6b321331de7c7b997be4d98ef5ff5aee640/pkg/sql/create_table.go#L263)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

The key here is that this function will be invoked when the function scope ends. With the original slice that we specified as a parameter to the call (think of that being closure capturing it in a slice). The slice afterwards could have had any value, but will be reverted back to the originally observed value
</blockquote></details>

yeah, the key point about defer is that, the function input value is evaluated at definition time. so the defer function takes the original defs value as input. this is true even we over write it with the defsCopy. this should work.

**Comment by fqazi** [comment]
@Xiang-Gu @chengxiong-ruan TFTR!

**Pull request merged**
