### PR TITLE
ui: update styles for session details page

### LINKED ISSUE #54513: ui: Sessions pages style updates
### 1. Update `icon button `in sessions table [figma designs](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv_admin-ui-query-performance?node-id=559%3A14386)

- icon should be 16x16 and centered 
-  Use the same menu popover as used on filter drop downs in admin ui. (no caret arrow on popover, no vertical grey line) 
- note: ideally we can start using our https://core-components.crdb.io/?path=/story/button--example

Screen Shot 2020-09-17 at 11 14 45 AM

### 2. Update `session age link` to follow pattern on Jobs/statement tables [figma designs](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv_admin-ui-query-performance?node-id=559%3A14386)

- Default: `Source Sans Pro Regular` `#242A35` 
   Hover: `Source Sans Pro Regular` `#0788FF` `Underline`

Screen Shot 2020-09-17 at 12 13 19 PM

### 3. Fix `...` icon on Pagination with more than 5 pages 

Screen Shot 2020-09-17 at 12 13 42 PM

### 4. Session Detail page style updates to align with other detail pages ([figma designs](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv_admin-ui-query-performance?node-id=608%3A17785)) 

- Update 'Terminate session' and 'terminate query' buttons to be secondary buttons, and move to header (see designs)
- Fix spacing above and below  Sessions, transaction and statements headers (see designs)
- Match 'back' arrow button style to the rest of detail pages hex:`#394455`
- verify blue for node link it hex:`#0788FF`

Screen Shot 2020-08-17 at 12 31 20 PM

### PR DESCRIPTION
**Pull request by koorosh**
resolves #54513 
depends on https://github.com/cockroachdb/admin-ui-components/pull/31
depends on https://github.com/cockroachdb/admin-ui-components/pull/34
depends on https://github.com/cockroachdb/admin-ui-components/pull/35

Current fix is quite complex and touches a lot of places because most of the issues with styles were common for all pages (Statements, Jobs, Node Overview).
Also many style duplicates required to get rid of duplicates and unify single version of proper components to use across entire app.

It's easier to review this PR per commit. Each commit describes in details what changes were made and their purpose.
 
Screen Shot 2020-10-13 at 3 18 18 PM

Screen Shot 2020-10-13 at 1 43 23 PM

### CODE REVIEW

**Comment by Annebirzin** [comment]
One language thing I notice here in the screenshots: We use `terminate statement` and `terminate session` in the session list view and we use `cancel query` and `cancel session` on the detail page. 

@awoods187 @jordanlewis can you confirm that we want to go with `terminate statement` and `terminate session` for both? cc @taroface

**Review by nathanstilwell — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 9 of 9 files at r2, 9 of 9 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55499)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[pkg/ui/src/views/sessions/sessionsPage.module.styl, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55499#-MJYZiHfEkp0kPCqqVpc:-MJYZiHfEkp0kPCqqVpd:b6kpehh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d24f182f9365c99db17b5db4e479a391df263019/pkg/ui/src/views/sessions/sessionsPage.module.styl#L11)):*
> ```Stylus
> // licenses/APL.txt.
> 
> @require '~src/views/statements/statementsPage.module.styl'
> ```

hmmm. I feel like we could move these styles into a more central place if they are going to be used by both Statements and Sessions.

**Comment by koorosh** [comment]
> > Reviewed 5 of 5 files at r1, 9 of 9 files at r2, 9 of 9 files at r3, 4 of 4 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55499)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)
> 
> _[pkg/ui/src/views/sessions/sessionsPage.module.styl, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55499#-MJYZiHfEkp0kPCqqVpc:-MJYZiHfEkp0kPCqqVpd:b6kpehh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d24f182f9365c99db17b5db4e479a391df263019/pkg/ui/src/views/sessions/sessionsPage.module.styl#L11)):_
> 
> > ```stylus
> > // licenses/APL.txt.
> > 
> > @require '~src/views/statements/statementsPage.module.styl'
> > ```
> 
> hmmm. I feel like we could move these styles into a more central place if they are going to be used by both Statements and Sessions.

Took a closer look and figured out that `statementsPage.module.styl` isn't used anymore in `Statements` page, it was left as a redundant style file when we migrated from global styles to CSS modules. As a solution I moved it to `SessionsPage` directory where it is used exclusively.
Right now, I don't know what is the best way to define shared styles for these kinds of definitions, because current styles don't represent any particular component. Instead these styles just customize components visual representation.

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 21 of 21 files at r5, 9 of 9 files at r6, 9 of 9 files at r7, 6 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55499)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
