### PR TITLE
sqlproxy: enforce idle timeouts on DRAINING pods

### PR DESCRIPTION
**Pull request by andy-kimball**
#### sqlproxy: enforce idle timeouts on DRAINING pods

Update the sqlproxy to listen to pod change notifications from the
tenant directory. When a pod enters the DRAINING state, enforce an
idle timeout in order to aggressively prune less acitve connections
to that pod.

#### sqlproxy: add idle monitor

Add a new idle monitor which will be used to detect DRAINING connections
which have been idle for more than 10 seconds (they will be closed).
RUNNING connections will not be subject to an idle timeout. Because
connections can move back and forth between the DRAINING and RUNNING
states, the idle monitor needs to support setting and clearing the
idle timeout dynamically. It also needs to perform efficient idle
detection over thousands of connections. The previous code used a
static idle timeout and called time.Now() on every call to Read/Write.
The new code supports dynamically set timeouts based on the connection's
remote address and only does 1-2 atomic read/write operations on each
Read/Write call.

A future commit will finish integrating usage of the idle monitor into
the sqlproxy.

#### sqlproxy: rename idle_disconnect_connection files

Rename files to "monitor_conn" in a separate commit in order to
make diff'ing easier.

#### sqlproxyccl: notify proxy on changes to tenant pod state

The proxy wants to know when a tenant pod's state changes so that it
can take action. For example, if a pod moves to the DRAINING state,
the proxy needs to stop routing new connections to that pod.

This commit adds a Pod.State field that can either be DRAINING or
RUNNING. It also updates NewDirectory to take an optional PodWatcher
channel argument. If this is specified, then any time a tenant pod
is created, destroyed, or modified, a notification is sent to the
channel. A future commit will handle those notifications.

### CODE REVIEW

**Comment by andy-kimball** [comment]
I recommend reviewing this commit-by-commit, since there's some file movement involved.

**Comment by andy-kimball** [comment]
@chrisseto, heads up that this PR conflicts somewhat with your `CPU Load` PR.

**Review by jaylim-crl — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67290)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @darinpp, and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0O9-s2C7KEKOEFUOY:-Me0O9-s2C7KEKOEFUOZ:bx0jrcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30e82f3fcf41c49766d492d7a811d5b254e4704/pkg/ccl/sqlproxyccl/proxy_handler.go#L349)):*
> ```Go
> 	if handler.idleMonitor != nil {
> 		crdbConn = handler.idleMonitor.DetectIdle(crdbConn, func() {
> 			err = newErrorf(codeIdleDisconnect, "idle connection closed")
> ```

Will we race on setting `err`? If yes, I think we should just make this a local variable.

I suspect we might be able to remove this: https://github.com/cockroachdb/cockroach/blob/90cfef65b6760def465491444f9d347fafebc05f/pkg/ccl/sqlproxyccl/proxy.go#L51-L53

It also looks like we're not sending these error back to the client. Do you know why? https://github.com/cockroachdb/cockroach/blob/90cfef65b6760def465491444f9d347fafebc05f/pkg/ccl/sqlproxyccl/proxy_handler.go#L376-L393
___
*[pkg/ccl/sqlproxyccl/idle/monitor_test.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0ZnSj8Z7ZqH88Q4Hk:-Me0ZnSj8Z7ZqH88Q4Hl:bmq8t82) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30e82f3fcf41c49766d492d7a811d5b254e4704/pkg/ccl/sqlproxyccl/idle/monitor_test.go#L31)):*
> ```Go
> 				wrapped := mon.DetectIdle(conn, func() {
> 					if addr != "addr2" {
> 						panic(fmt.Sprintf("did not expect %s connections to be idled", addr))
> ```

How come we panic here and we don't use `t.NotEqual` or something similar?
___
*[pkg/ccl/sqlproxyccl/idle/monitor_test.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0_b1E0SFsSvqS1utS:-Me0_b1F1LW9KpPPMAAi:b-t09i9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30e82f3fcf41c49766d492d7a811d5b254e4704/pkg/ccl/sqlproxyccl/idle/monitor_test.go#L49)):*
> ```Go
> 
> 		require.Eventually(t, func() bool {
> 			return atomic.LoadInt64(&idled) >= 5
> ```

If we're only creating 5 connections for addr2, why is this `>= 5`, and not `== 5`? Or is this just to handle the case in which we're calling the idle closure multiple times before we could get a chance to close the connection?
___
*[pkg/ccl/sqlproxyccl/idle/monitor_test.go, line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0_Cfr-yXVa_5-tQBq:-Me0_Cfr-yXVa_5-tQBr:b-r1vjcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30e82f3fcf41c49766d492d7a811d5b254e4704/pkg/ccl/sqlproxyccl/idle/monitor_test.go#L95)):*
> ```Go
> 		require.Equal(t, 0, mon.countAddrsToCheck())
> 
> 		time.Sleep(timeout * 2)
> ```

What's this used for?
___
*[pkg/ccl/sqlproxyccl/tenant/directory.go, line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0Dd3G05UepoVc5Pfk:-Me0Dd3G05UepoVc5Pfl:blad5vr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52eb1d3d9073c875097ab03320022c34bd6335e/pkg/ccl/sqlproxyccl/tenant/directory.go#L383)):*
> ```Go
> 
> 	// Ensure that a directory entry exists for this tenant.
> 	entry, err := d.getEntry(ctx, roachpb.MakeTenantID(pod.TenantID), true)
> ```

nit: `true /* allowCreate */`
___
*[pkg/ccl/sqlproxyccl/tenant/directory.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0DQp0CU3HJNaYiife:-Me0DQp0CU3HJNaYiiff:b4ggb4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52eb1d3d9073c875097ab03320022c34bd6335e/pkg/ccl/sqlproxyccl/tenant/directory.go#L393)):*
> ```Go
> 	}
> 
> 	if entry != nil {
> ```

Since allowCreate is now true, will entry ever be nil if err is nil? From what I tell, it looks like a no, so I think we could remove this.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67290)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp, @jaylim-crl, and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0O9-s2C7KEKOEFUOY:-Me1yMojC7oKv_AYInd5:bpsmfea) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30e82f3fcf41c49766d492d7a811d5b254e4704/pkg/ccl/sqlproxyccl/proxy_handler.go#L349)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

Will we race on setting `err`? If yes, I think we should just make this a local variable.

I suspect we might be able to remove this: https://github.com/cockroachdb/cockroach/blob/90cfef65b6760def465491444f9d347fafebc05f/pkg/ccl/sqlproxyccl/proxy.go#L51-L53

It also looks like we're not sending these error back to the client. Do you know why? https://github.com/cockroachdb/cockroach/blob/90cfef65b6760def465491444f9d347fafebc05f/pkg/ccl/sqlproxyccl/proxy_handler.go#L376-L393
</blockquote></details>

Good catch, I just cut and pasted the code and didn't notice that. I also removed the case from `proxy.go` since it should not be necessary.
___
*[pkg/ccl/sqlproxyccl/idle/monitor_test.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0ZnSj8Z7ZqH88Q4Hk:-Me1y_Dk6XSV7J-M-ADp:b8ktiux) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30e82f3fcf41c49766d492d7a811d5b254e4704/pkg/ccl/sqlproxyccl/idle/monitor_test.go#L31)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

How come we panic here and we don't use `t.NotEqual` or something similar?
</blockquote></details>

The `require` methods don't work correctly on background goroutines because they call `t.FailNow` which should only be called from the foreground goroutine. However, I switched go use `t.Error` which will mark the test as failed but not try to stop the goroutine.
___
*[pkg/ccl/sqlproxyccl/idle/monitor_test.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0_b1E0SFsSvqS1utS:-Me2-QQm3VWif_o5_rK_:baziklg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30e82f3fcf41c49766d492d7a811d5b254e4704/pkg/ccl/sqlproxyccl/idle/monitor_test.go#L49)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

If we're only creating 5 connections for addr2, why is this `>= 5`, and not `== 5`? Or is this just to handle the case in which we're calling the idle closure multiple times before we could get a chance to close the connection?
</blockquote></details>

Yes, there's an inherent race condition here that means the idle closure can be called multiple times for the same connection. I added a comment explaining that.
___
*[pkg/ccl/sqlproxyccl/idle/monitor_test.go, line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0_Cfr-yXVa_5-tQBq:-Me2-pXk1yNnSHpgwoOM:bhyjvlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b30e82f3fcf41c49766d492d7a811d5b254e4704/pkg/ccl/sqlproxyccl/idle/monitor_test.go#L95)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

What's this used for?
</blockquote></details>

Just leftover detritus. Removed.
___
*[pkg/ccl/sqlproxyccl/tenant/directory.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-Me0DQp0CU3HJNaYiife:-Me2-ysZ3wsN9kcdDpvf:bs2vhuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52eb1d3d9073c875097ab03320022c34bd6335e/pkg/ccl/sqlproxyccl/tenant/directory.go#L393)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

Since allowCreate is now true, will entry ever be nil if err is nil? From what I tell, it looks like a no, so I think we could remove this.
</blockquote></details>

Good point, removed.

**Review by jaylim-crl — APPROVED** [review]
:lgtm: 

Some clarifications:
1. When a pod enters the DRAINING state, and connections are not idle, what happens? From what I understand, the operator will only terminate the pod if there are no open sql connections. Do we plan to set any hard limits on those connections?
2. What's the timeout value you're thinking for the idle monitor?

> Reviewed 13 of 13 files at r5, 2 of 4 files at r6, 7 of 11 files at r7, 6 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-:-Me26sI17f7_-RDHFqES:beagw8g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @darinpp and @JeffSwenson)

**Comment by andy-kimball** [comment]
1. Once this change goes in, I'll make a separate change to forcible terminate any DRAINING pods that have been draining for > 10 minutes. That will put a limit on how long we try to more gracefully terminate.
2. I plan to configure a 10 second drain timeout for the idle monitor.

**Review by jaylim-crl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67290)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/ccl/sqlproxyccl/tenant/directory.go` line 383 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-N2do1ne2TklYLdrhikH:-N2do1ne2TklYLdrhikI:b-h6dndw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b958c8b95c8d12ab91492398f49351d7e177a5d/pkg/ccl/sqlproxyccl/tenant/directory.go#L383)):*
> 	// Ensure that a directory entry exists for this tenant.
	entry, err := d.getEntry(ctx, roachpb.MakeTenantID(pod.TenantID), true /* allowCreate */)


I think this PR may have introduced a subtle bug when allowCreate is set to true. WatchPods receives a new pod update event regardless of tenants.

Consider the following example:
1. tenant-10 has 3 RUNNING pods
2. sqlproxy restarts, and we get a new tenant directory cache
3. a new pod starts up for tenant-10
4. pod watcher registers the new pod for tenant-10; this will be the first pod since allowCreate=true

Existing pods will never be registered because we will never call ListPods. ListPods is not called because len(pods) != 0 (i.e. the pod registered in 4). As a result, all new connections to that given sqlproxy will only be routed to that single SQL pod (or any subsequent new RUNNING pods). Note that this bug won't be triggered if a new connection comes in right before (3), causing the connection goroutine to trigger entry creation, which then calls EnsurePod and ListPods.

cc: @jeffswenson @andy-kimball

**Comment by andy-kimball** [comment]
*[`pkg/ccl/sqlproxyccl/tenant/directory.proto` line 69 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/67290#-N2qZJuu2gS080bO5G3n:-N2qZJuu2gS080bO5G3o:bdzy5nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b958c8b95c8d12ab91492398f49351d7e177a5d/pkg/ccl/sqlproxyccl/tenant/directory.proto#L69)):*
> ```protobuf
>   reserved 2, 3;
>   // Pod describes the tenant pod which has been added, modified, or deleted.
>   Pod pod = 4;
> ```

How would we upgrade to this? If we update the `tenantdir` first, then the existing fields that clients expect will be zero. If we upgrade the clients first, then they will try to access the `Pod` field, which will be zero.

Instead, I think we need to have a transition period where the `tenantdir` sets _both_ the old and new fields. We can roll that out in a patch release. Once it's rolled out, we can then update the clients to switch from the old fields to the new fields.

**Pull request merged**
