### PR TITLE
rpc: use tenant client/server certs

### PR DESCRIPTION
**Pull request by tbg**
With this PR, tenant SQL servers use tenant client certificates to
connect to the tenant server endpoint at the KV layer. They were
previously using the KV-internal node certs.

No validation is performed as of this PR, but this is the obvious
next step.

Follow-up work will assertions that make sure that we don't see
tenants "accidentally" use the node certs for some operations
when they are available (as is typically the case during testing).

Finally, there will be some work on the heartbeats exchanged by
the RPC context. We don't want a SQL tenant's time signal to
ever trigger KV nodes to crash, for example.

Touches #47898.

Release note: None

- cli/flags,config: new flag for tenant KV listen addr
- sql: route tenant KV traffic to tenant KV address
- roachtest: configure --tenant-addr flag in acceptance/multitenant
- rpc: add TenantID to rpc.ContextOptions
- security: slight test improvement
- rpc: pass TenantID to SecurityContext to CertManager
- security: use a single test_certs dir
- security: embed certs for a few hard-coded tenants
- rpc: *almost* use tenant client certs (on tenants)
- rpc: use tenant client/server certs where appropriate

### CODE REVIEW

**Review by nvb — APPROVED** [review]
Very nice! I don't see anything major here that needs to be discussed further, though I'm ignoring the last commit. :lgtm: 

> Reviewed 24 of 24 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, 29 of 29 files at r4, 28 of 28 files at r5, 2 of 2 files at r6, 5 of 5 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51503#-:-MCmcwtN2b9UpKTxdx8w:b-cl33ma)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/rpc/context.go, line 239 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/51503#-MCmbh5u7nbKz3rWmusR:-MCmbh5u7nbKz3rWmusS:b1mq3iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc881110aa4a0a0413e16acdfc876e4ae8d529c/pkg/rpc/context.go#L239)):*
> ```Go
> 		}
> 
> 		// TODO(tbg): do something else if `o.tenant`.
> ```

This is the same TODO as the one five lines up, right? There's not multiple "something else"s that you want to do?
___
*[pkg/rpc/context.go, line 770 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/51503#-MCmbtvY5zGH7OBRTQk7:-MCmbtvY5zGH7OBRTQk8:b8rmvvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc881110aa4a0a0413e16acdfc876e4ae8d529c/pkg/rpc/context.go#L770)):*
> ```Go
> 		// TODO(tbg): remove this override when the KV layer can authenticate tenant
> 		// client certs.
> 		const override = false
> ```

Why keep the code?
___
*[pkg/rpc/tls.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51503#-MCmZV5B0-wDA-jTzQ6y:-MCmZV5C3wTuRaz_QTfQ:b-43js7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebb22187ba689ff9d7131d045880093f985540d/pkg/rpc/tls.go#L85)):*
> ```Go
> 	ctx.lazy.certificateManager.Do(func() {
> 		var opts []security.Option
> 		if !roachpb.IsSystemTenantID(ctx.tenID.ToUint64()) {
> ```

You can just do `ctx.tenID != roachpb.SystemTenantID`.
___
*[pkg/rpc/tls.go, line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51503#-MCmZzN05JIp_HTTj36V:-MCmZzN05JIp_HTTj36W:b4a85t4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebb22187ba689ff9d7131d045880093f985540d/pkg/rpc/tls.go#L86)):*
> ```Go
> 		var opts []security.Option
> 		if !roachpb.IsSystemTenantID(ctx.tenID.ToUint64()) {
> 			opts = append(opts, security.ForTenant(ctx.tenID.String()))
> ```

Any reason to lose type safety here with the `tenantIdentifier`?
___
*[pkg/rpc/tls.go, line 177 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/51503#-MCmcBFB9F3LgCK1RPEw:-MCmcBFB9F3LgCK1RPEx:b8rmk2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc881110aa4a0a0413e16acdfc876e4ae8d529c/pkg/rpc/tls.go#L177)):*
> ```Go
> // certificate for the configured tenant from the cert manager.
> func (ctx *SecurityContext) GetTenantClientTLSConfig() (*tls.Config, error) {
> 	// Early out.
> ```

We have almost the exact same logic in each of these methods. Think it's worth generalizing? Something like:
```go
func (ctx *SecurityContext) getTLSConfig(fn (*security.CertificateManager) (*tls.Config, error)) (*tls.Config, error) {
    ...
}
```
___
*[pkg/server/testserver.go, line 638 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/51503#-MCmche66GxT7gEDccCl:-MCmche66GxT7gEDccCm:b9n4rxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc881110aa4a0a0413e16acdfc876e4ae8d529c/pkg/server/testserver.go#L638)):*
> ```Go
> 		}
> 	}
> 	sqlCfg.TenantKVAddrs = []string{ts.TenantAddr()}
> ```

Good catch. Should this be `ServingTenantAddr` though?

**Review by tbg — COMMENTED** [review]
TFTR! I'll see about this wip commit and try to merge this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51503#-:-MDJbyWICdgJI54K9QLZ:bf1xpk4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/rpc/tls.go, line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51503#-MCmZzN05JIp_HTTj36V:-MDJax-B8ZqqG_4vaD9R:bhef7yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ebb22187ba689ff9d7131d045880093f985540d/pkg/rpc/tls.go#L86)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any reason to lose type safety here with the `tenantIdentifier`?
</blockquote></details>

It didn't seem useful to have to deal with string/tenantID conversions inside of the `security` package. Open to revisiting this after this PR.
___
*[pkg/rpc/tls.go, line 177 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/51503#-MCmcBFB9F3LgCK1RPEw:-MDJb4BO3DpiyfQmsrWx:b-82clti) ([raw file](https://github.com/cockroachdb/cockroach/blob/7bc881110aa4a0a0413e16acdfc876e4ae8d529c/pkg/rpc/tls.go#L177)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We have almost the exact same logic in each of these methods. Think it's worth generalizing? Something like:
```go
func (ctx *SecurityContext) getTLSConfig(fn (*security.CertificateManager) (*tls.Config, error)) (*tls.Config, error) {
    ...
}
```
</blockquote></details>

Yes, that might be a good idea. I would like to get this PR in first, though.

**Comment by tbg** [comment]
I rebased onto https://github.com/cockroachdb/cockroach/pull/52034. This *should* turn green now.

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Comment by tbg** [comment]
Failed on `pip` in examples-orms

bors r=nvanbenschoten

**Comment by tbg** [comment]
Sigh

> [10:50:03]
Cause 6: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve javax.annotation:javax.annotation-api:1.2.
[10:50:03]
Required by:
[10:50:03]
    project : > org.glassfish.jersey.core:jersey-server:2.25

bors r=nvanbenschoten

**Comment by knz** [comment]
I have skipped the Example-ORMs target so this will be able to go in now

**Comment by knz** [comment]
ok I thought I had skipped example-orms and it seems that I did not.

**Comment by knz** [comment]
oh that's because your bors run started before my conf change. Let's try that again.

bors r=nvanbenschoten

**Pull request merged**
