### PR TITLE
rfcs: complementary RFC to inventory the plan properties

### PR DESCRIPTION
**Pull request by knz**
Note: I intend to merge this PR into #19135 together with #19220.

### CODE REVIEW

**Comment by petermattis** [comment]
Glad to see this inventory getting done. Some of the properties you listed I would not consider properties, but metadata or implementation data on the expressions. I suppose that depends on what our definition of properties is. I'm defining properties as common metadata that is maintained on a per expression basis. Individual expressions will also have additional metadata. For example, an `index scan` operation needs to know the index it is scanning, but parent expressions only need to know the ordering that produces.

---

Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/sql_plan_properties.md, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-KwtyWHHX2PqUIOkEwTQ:-KwtyWHHX2PqUIOkEwTR:b690eu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L82)):*
> ```Markdown
> | algorithm               | enum      | P, x-func | derived.  | relational | mand. | physical planning         |                        |
> | scan index              | string    | P, x-func | derived   | relational | mand. | physical planning         |                        |
> | spans for scans         | []span    | P, sem    | derived   | relational | opt   | TBD                       |                        |
> ```

I think this table should be in an appendix as I find it obfuscates rather than clarifies. In its place, I'd put a list of the logical and physical properties that are hyperlinked to their sections. 

---

*[docs/RFCS/sql_plan_properties.md, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwtynw4alqLBFK01eqB:-Kwtynw4alqLBFK01eqC:brbqg6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L90)):*
> ```Markdown
> 
> - *logical* (L) properties which define equivalency classes, and are
>   shared among all m-expressions in the class.
> ```

I'd like to leave m-expressions and equivalency classes out of the definition of logical and physical properties. As an alternative:

*logical* properties are those that can be derived from the extended relational algebra. For example, NULL-ability of columns and keys, weak keys and foreign keys.

*physical* properties are those that can be derived from the specific implementation of relational algebra expressions. The sole physical property is ordering which is not a consideration in the extended relational algebra. (`ORDER BY` sits outside of the extended relational algebra).

---

*[docs/RFCS/sql_plan_properties.md, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu-HYqkBbl-IN-GbPi:-Kwu-HYun-4ESJF7Rio5:bdkerlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L94)):*
> ```Markdown
>   class.
> 
> We distinguish two *sub-categories*:
> ```

This felt overly categorical on my first read through the document. While I don't mind the categorization being done, placing the categorization up front got in my way of reading about the properties. Perhaps move to a terminology section at the end of the document.

---

*[docs/RFCS/sql_plan_properties.md, line 101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu-PCkBSBQ0oKwCmhL:-Kwu-PCkBSBQ0oKwCmhM:b6fzoxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L101)):*
> ```Markdown
>   the input/output values.
> 
> We distinguish the *origin*:
> ```

Similar to the above, this felt overly categorical on my first read through the document.

---

*[docs/RFCS/sql_plan_properties.md, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu-ZRoaauLIPjT3xRt:-Kwu-ZRoaauLIPjT3xRu:b-wzgrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L138)):*
> ```Markdown
> 
> Properties can be both relational and scalar; we'll call them *common*
> in contexts where a separate word is needed.
> ```

I feel like this section is "burying the lede" which means that you're keeping me from the good stuff. I know you prefer to have all of these definitions upfront, but I think the average reader would be find with them in a terminology section at the end.

---

*[docs/RFCS/sql_plan_properties.md, line 351 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu18mRXJq8cJDM-RkT:-Kwu18mRXJq8cJDM-RkU:b8zqla5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L351)):*
> ```Markdown
> (No synthetic notation)
> 
> Example with memo:
> ```

I think using `memo` for explanation here and elsewhere in this document is less clear than if you showed the relational algebra expressions in a nested tree structure.

---

*[docs/RFCS/sql_plan_properties.md, line 590 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu1cPhV6-DxktSj62W:-Kwu1cPhV6-DxktSj62X:bgos4dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L590)):*
> ```Markdown
> ```
> 
> ## Range constraints
> ```

I've been calling this column value constraints. `Range` is a bit of an overloaded term in Cockroach.

---

*[docs/RFCS/sql_plan_properties.md, line 843 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu0eNgggDwspiFWtEX:-Kwu0eNgggDwspiFWtEY:blgri1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L843)):*
> ```Markdown
> ```
> 
> ## (Actual) algorithm
> ```

I don't think this is a property, but instead metadata on the expression. 

---

*[docs/RFCS/sql_plan_properties.md, line 860 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu0cPHQYi-TjzbMmzP:-Kwu0cPHQYi-TjzbMmzQ:b-ltbpol) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L860)):*
> ```Markdown
> relational expression in the plan.
> 
> ## Scan index
> ```

I don't think this is a property. When enumerating the alternative ways of scanning a table, we would expand all of the possible indexes. This seems like metadata about the index scan rather than a property that needs to be propagated to other expressions.

---

*[docs/RFCS/sql_plan_properties.md, line 876 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu0dXFFxKKIUwp5xhg:-Kwu0dXFFxKKIUwp5xhh:b-lcqvau) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L876)):*
> ```Markdown
> query plan.
> 
> ## Spans for scans
> ```

Similar to `Scan index`, I don't think this is a property, but metadata on the `index scan` expression.

---

*[docs/RFCS/sql_plan_properties.md, line 897 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu06_omC6rXEth91ym:-Kwu06_omC6rXEth91yn:b-ndc6e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L897)):*
> ```Markdown
> - column labels. Labels disappear from the expressions during
>   the prep phase, and only remains at the top level, as
>   an attribute of the results for the entire query.
> ```

While it isn't necessary to maintain labels for correctness, doing so can aid debug-ability. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-:-Kwu2YlwFqYX6FbW7cBR:bb22yxp)*

**Comment by knz** [comment]
I am moving this document over to #19135. I will process your last few comments there.

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/sql_plan_properties.md, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-KwtyWHHX2PqUIOkEwTQ:-KwymTk3ynnPZ9XLPQoD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L82)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this table should be in an appendix as I find it obfuscates rather than clarifies. In its place, I'd put a list of the logical and physical properties that are hyperlinked to their sections. 
</blockquote></details>

Done.

---

*[docs/RFCS/sql_plan_properties.md, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwtynw4alqLBFK01eqB:-KwyheLiyJb9T8v6DFs9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L90)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'd like to leave m-expressions and equivalency classes out of the definition of logical and physical properties. As an alternative:

*logical* properties are those that can be derived from the extended relational algebra. For example, NULL-ability of columns and keys, weak keys and foreign keys.

*physical* properties are those that can be derived from the specific implementation of relational algebra expressions. The sole physical property is ordering which is not a consideration in the extended relational algebra. (`ORDER BY` sits outside of the extended relational algebra).
</blockquote></details>

Done.

---

*[docs/RFCS/sql_plan_properties.md, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu-HYqkBbl-IN-GbPi:-KwyhfUAKk2B0RJ1MRJt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L94)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This felt overly categorical on my first read through the document. While I don't mind the categorization being done, placing the categorization up front got in my way of reading about the properties. Perhaps move to a terminology section at the end of the document.
</blockquote></details>

Done.

---

*[docs/RFCS/sql_plan_properties.md, line 101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu-PCkBSBQ0oKwCmhL:-Kwyhgyji4Tns7hFZQdt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L101)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Similar to the above, this felt overly categorical on my first read through the document.
</blockquote></details>

Done.

---

*[docs/RFCS/sql_plan_properties.md, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu-ZRoaauLIPjT3xRt:-KwyhhPUmezJVmHGwFgJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L138)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I feel like this section is "burying the lede" which means that you're keeping me from the good stuff. I know you prefer to have all of these definitions upfront, but I think the average reader would be find with them in a terminology section at the end.
</blockquote></details>

Done.

---

*[docs/RFCS/sql_plan_properties.md, line 351 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu18mRXJq8cJDM-RkT:-KwyhkdIkDd2R71agI1m:b-byn2sy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L351)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think using `memo` for explanation here and elsewhere in this document is less clear than if you showed the relational algebra expressions in a nested tree structure.
</blockquote></details>

I added the expression tree, for clarity. I am keeping the memo because we should not lose track of the fact that properties are carried by classes, not expression nodes.

---

*[docs/RFCS/sql_plan_properties.md, line 590 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu1cPhV6-DxktSj62W:-Kwyi2Bine0n5qiCFHaG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L590)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I've been calling this column value constraints. `Range` is a bit of an overloaded term in Cockroach.
</blockquote></details>

Done.

---

*[docs/RFCS/sql_plan_properties.md, line 843 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu0eNgggDwspiFWtEX:-KwyiApX4P3VPuPJIGXV:bbdo1ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L843)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't think this is a property, but instead metadata on the expression. 
</blockquote></details>

I do not see what is this distinction you are making between physical properties and expression metadata.

Two m-expressions that have the same operator and same operands can only differ in their physical properties. If the only thing that differs is the algorithm, then necessarily the algorithm must be a physical property.

---

*[docs/RFCS/sql_plan_properties.md, line 860 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu0cPHQYi-TjzbMmzP:-KwyiLhLALGplLJrGPVZ:bshwmcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L860)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't think this is a property. When enumerating the alternative ways of scanning a table, we would expand all of the possible indexes. This seems like metadata about the index scan rather than a property that needs to be propagated to other expressions.
</blockquote></details>

"We would expand all of the possible indexes" == "Generate all the possible scan expressions, differing from each other in which index they use"

Two m-expressions that have the same operator and same operands can only differ in their physical properties. If the only thing that differs is the index name, then necessarily the index name must be a physical property.

---

*[docs/RFCS/sql_plan_properties.md, line 876 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu0dXFFxKKIUwp5xhg:-Kwyihocp7XweGltlaDg:b-b3e8vm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L876)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Similar to `Scan index`, I don't think this is a property, but metadata on the `index scan` expression.
</blockquote></details>

Two m-expressions that have the same operator and same operands can only differ in their physical properties. If the only thing that differs is the list of spans, then necessarily the list of spans must be a physical property.

---

*[docs/RFCS/sql_plan_properties.md, line 897 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu06_omC6rXEth91ym:-KwyilX_eBEFT1haMxU9:b-ir904y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L897)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

While it isn't necessary to maintain labels for correctness, doing so can aid debug-ability. 
</blockquote></details>

Agreed. Added a note.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/sql_plan_properties.md, line 843 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu0eNgggDwspiFWtEX:-Kwz-UnqJg-xGTR9YIYA:b-ls1sg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L843)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I do not see what is this distinction you are making between physical properties and expression metadata.

Two m-expressions that have the same operator and same operands can only differ in their physical properties. If the only thing that differs is the algorithm, then necessarily the algorithm must be a physical property.
</blockquote></details>

The distinction I'm making is that a property is something we'd want to maintain on every expression while something like the algorithm is private to the expression. My guess is that you're looking at "property" in a general sense, while I'm trying to restrict it to attributes that are common across either logical or physical nodes. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/sql_plan_properties.md, line 843 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366#-Kwu0eNgggDwspiFWtEX:-KwzJuwrLStVytL3i5nW:bigkf4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a9d487cb5d997771d935012ed313e55ccfb82d/docs/RFCS/sql_plan_properties.md#L843)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The distinction I'm making is that a property is something we'd want to maintain on every expression while something like the algorithm is private to the expression. My guess is that you're looking at "property" in a general sense, while I'm trying to restrict it to attributes that are common across either logical or physical nodes. 
</blockquote></details>

Ah now I understand what you mean. I will try to integrate this idea into the definition.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19366)*

**Pull request closed without merging**
