### PR TITLE
cli: include cpu profiles into debug.zip

### LINKED ISSUE #105012: cli: have debug zip collect the env sampler cpu profiles
**Is your feature request related to a problem? Please describe.**
Currently when the debug zip is constructed, it searches for existing heap profiles, go routine profiles and logs to collect to add to the zip. We should do the same for the env sampler cpu profiles.

**Describe the solution you'd like**
I think we would need to add some logic around here: https://github.com/cockroachdb/cockroach/blob/c5d21f95b2c241fa9c6536eb50c44366aa280a61/pkg/cli/zip_per_node.go#L275
to search for the cpu profiles. They currently get written to `/cockroach-data/logs/pprof_dump`.

Jira issue: CRDB-28824

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit extends `GetFiles` API to support sending CPU profiles (collected by the CPU profiler) and uses this in the debug.zip to automatically include all relevant CPU profiles (this is in addition to collecting fresh CPU profiles at the time debug.zip is taken). In 24.1 time frame we enabled the CPU profiler by default, so this is a nice addition to that. (Note that on CC clusters we had the CPU profiler enabled already, and SREs had to manually fetch the CPU profiles since it wasn't included into the debug.zip. This will remove that extra overhead.)

Fixes: #105012.

Release note: None

### CODE REVIEW

**Review by dhartunian — APPROVED** [review]
:lgtm: thank you for closing this gap!

> Reviewed 1 of 1 files at r1, 14 of 14 files at r2, 8 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123172#-:-NweJDuL5yyqWILZW3oY:b-phexbv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @abarganier, @arjunmahishi, @kousiknath, @xinhaoz, and @yuzefovich)

___
*[`pkg/server/get_local_files_test.go` line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123172#-NwePQs_0NSTb8v9XvSP:-NwePQs_0NSTb8v9XvSQ:bvijkem) ([raw file](https://github.com/cockroachdb/cockroach/blob/219902ca19e97eb30d70740a244a4ebc28c6cae0/pkg/server/get_local_files_test.go#L55)):*
> ```Go
> 		require.NoError(t, err)
> 		require.Equal(t, 1, len(res.Files))
> 		require.Equal(t, "im-in-the-heap-dir", res.Files[0].Name)
> ```

can you add a successful read case here for cpu profiles?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123172#-:-NwekJK2Ds4Uv6OfkB2P:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aa-joshi, @abarganier, @arjunmahishi, @dhartunian, @kousiknath, and @xinhaoz)

___
*[`pkg/server/get_local_files_test.go` line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123172#-NwePQs_0NSTb8v9XvSP:-NwejsejBoJe2pe-9sip:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/219902ca19e97eb30d70740a244a4ebc28c6cae0/pkg/server/get_local_files_test.go#L55)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can you add a successful read case here for cpu profiles?
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
blathers backport release-23.2

**Comment by yuzefovich** [comment]
blathers backport release-23.1

**Pull request merged**
