### PR TITLE
sql, server, ui: update permissions for observability related features

### LINKED ISSUE #89034: Addressing observability related system privileges acceptance testing feedback for v22.2
Ref: Refer to [22.2 Acceptance Testing Obs Privileges](https://docs.google.com/document/d/1vUVk3T7P_to0B_XrBCpTrI-X5_Csyf9-RA6t880IDyM/edit)

- [x] User with `VIEWCLUSTERSETTING` OR `MODIFYCLUSTERSETTING` privileges should be able to run the command `SHOW CLUSTER SETTINGS;` - currently doing so will result in a SQLSTATE: 42501 message 
- [x]  User with `MODIFYCLUSTERSETTING` privilege should be able to run the command `SET CLUSTER SETTING;` - currently doing so will result in a SQLSTATE: 42501 message 
- [x] For the Hot Ranges page, we should update the gate from the old `VIEWACTIVITY`/`VIEWACTIVITYREDACTED` role option to the `VIEWCLUSTERMETADATA` privilege. The idea is that most range related info should be behind `VIEWCLUSTERMETADATA` (not `VIEWACTIVITY` which was added as a temporary stopgap in 22.1)
- [x] Currently nothing gates https://localhost:8080/#/reports/problemranges/1 (we should introduce the `VIEWCLUSTERMETADATA` gate)
- [x] Currently ADMIN gates https://localhost:8080/#/data-distribution (we should introduce the `VIEWCLUSTERMETADATA` gate)
- [x] Update the stores request gate (which feeds pages like https://localhost:8080/#/reports/stores/local) to be behind `VIEWCLUSTERMETADATA` (it's currently gated by ADMIN)
- [x] Update _status/hotranges to be gated by `VIEWCLUSTERMETADATA` (investigate https://localhost:8080/#/debug/hotranges which is currently not gated by anything)
- [x] Under the section "Even More Advanced Debugging", the "Ranges" links - Range Status (#/reports/range/[range_id]), Raft Messages (#/raft/messages/all), Raft for all ranges (#/raft/ranges) - should be gated behind the same standard privilege `VIEWCLUSTERMETADATA`
- [x] #/debug/redux (UI Debugging) should be behind VIEWDEBUG but it's not gated by anything

Jira issue: CRDB-20081

### PR DESCRIPTION
**Pull request by Santamaura**
This patch adds the following changes:
- users with `VIEWCLUSTERSETTING/MODIFYCLUSTERSETTING` can run `SHOW CLUSTER SETTING` sql command
- Hot ranges page now requires `VIEWCLUSTERMETADA`
- Problem ranges report requires `VIEWCLUSTERMETADATA`
- Data distribution requires `VIEWCLUSTERMETADATA`
- Stores report requires `VIEWCLUSTERMETADATA`
- Hot ranges debug page requires `VIEWCLUSTERMETADATA`
- Range status page requires `VIEWCLUSTERMETADATA`
- Raft for all ranges page requires `VIEWCLUSTERMETADATA`
- Fixed a visual bug on Stores report where a response that returned an error shows an infinite spinner

Resolves #89034

Release note (bug fix): Update hot ranges, problem ranges, data distribution, stores report, range status, raft for all ranges features to require `VIEWCLUSTERMETADATA`. Update `SHOW CLUSTER SETTING` sql command to require
`VIEWCLUSTERSETTING/MODIFYCLUSTERSETTING`. Fix visual bug on stores report where an error shows an infinite spinner only.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89114)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @RichardJCai, @Santamaura, and @zachlite)

___
*[`pkg/server/admin.go` line 1572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-NDTfn7C2NSXmMOvKvW5:-NDTfn7C2NSXmMOvKvW6:b-lqom45) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca2266d6ad4362d6a82ada788b347c3f8d4e2fd/pkg/server/admin.go#L1572)):*
> ```Go
> 	it, err := s.server.sqlServer.internalExecutor.QueryIteratorEx(
> 		ctx, "admin-range-log", nil, /* txn */
> 		sessiondata.InternalExecutorOverride{User: username.RootUserName()},
> ```

Are you sure about this?

Why not a virtual table/view on top of `system/rangelog`, which checks the privilege?

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89114)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @koorosh, @RichardJCai, and @zachlite)

___
*[`pkg/server/admin.go` line 1572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-NDTfn7C2NSXmMOvKvW5:-NDZg1dB2ieSlqpiWFHQ:b-grvvr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca2266d6ad4362d6a82ada788b347c3f8d4e2fd/pkg/server/admin.go#L1572)):*
`rangeLogHelper` is only used by that 1 endpoint so this should be fine. 

>Why not a virtual table/view on top of system/rangelog, which checks the privilege?

Our current pattern is to check the privilege at the beginning of endpoints, if there is need for a vtable/view of `system/rangelog` in other places as well perhaps we can do it in a separate PR and move this over afterward?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89114)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @koorosh, @RichardJCai, @Santamaura, and @zachlite)

___
*[`pkg/sql/crdb_internal.go` line 1605 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_5elb1XaF3jXV-v1D:-ND_5elb1XaF3jXV-v1E:bd73tet) ([raw file](https://github.com/cockroachdb/cockroach/blob/610ad9a1a27de59b8dde7262d116ccc1dac7d8f5/pkg/sql/crdb_internal.go#L1605)):*
> ```Go
> 		}
> 		for _, k := range settings.Keys(p.ExecCfg().Codec.ForSystemTenant()) {
> 			if !hasAdmin && settings.AdminOnly(k) {
> ```

there should be tests added that show this change taking effect
___
*[`pkg/sql/set_cluster_setting.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_5anu5AHagKEoy7hj:-ND_5anu5AHagKEoy7hk:bd73tet) ([raw file](https://github.com/cockroachdb/cockroach/blob/610ad9a1a27de59b8dde7262d116ccc1dac7d8f5/pkg/sql/set_cluster_setting.go#L68)):*
> ```Go
> 
> func checkPrivilegesForSetting(ctx context.Context, p *planner, name string, action string) error {
> 	if settings.AdminOnly(name) {
> ```

there should be tests added that show this change taking effect
___
*[`pkg/sql/delegate/show_all_cluster_settings.go` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_57CdBFGWPNGOriYa:-ND_57CdBFGWPNGOriYb:b29jy8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/33140f3d5eacd5bfc5794ce95bac52db43c7c402/pkg/sql/delegate/show_all_cluster_settings.go#L34)):*
> ```Go
> 	var hasViewPrivilegeErr error
> 	if d.evalCtx.Settings.Version.IsActive(d.ctx, clusterversion.SystemPrivilegesTable) {
> 		hasModifyPrivilegeErr = d.catalog.CheckPrivilege(d.ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYCLUSTERSETTING)
> ```

hm this is beyond the scope of your PR, but this doesn't seem that robust -- the error that's returned here might be because of a problem looking up the privileges, but it can't be differentiated from not having the privilege.

i'll try to clean up this interface separately.
___
*[`pkg/sql/delegate/show_all_cluster_settings.go` line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_4_z39R61Fc68Oobd:-ND_4_z39R61Fc68Oobe:bqn0iao) ([raw file](https://github.com/cockroachdb/cockroach/blob/33140f3d5eacd5bfc5794ce95bac52db43c7c402/pkg/sql/delegate/show_all_cluster_settings.go#L49)):*
> ```Go
> 			return nil, pgerror.Newf(pgcode.InsufficientPrivilege,
> 				"only users with either %s or %s privileges are allowed to SHOW CLUSTER SETTINGS",
> 				roleoption.MODIFYCLUSTERSETTING, roleoption.VIEWCLUSTERSETTING)
> ```

nit: can you change this to use the `privilege` constants instead of `roleoption` ones?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89114)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @koorosh, @RichardJCai, @Santamaura, and @zachlite)

___
*[`pkg/sql/syntheticprivilege/global_privilege.go` line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_5mP-9eBXzxbQx3yC:-ND_5mP-9eBXzxbQx3yD:b-q3vg5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/33140f3d5eacd5bfc5794ce95bac52db43c7c402/pkg/sql/syntheticprivilege/global_privilege.go#L62)):*
> ```Go
> 
> // ID implements the cat.Object interface.
> func (p *GlobalPrivilege) ID() cat.StableID {
> ```

why was this needed? can a test be added that demonstrates why?

**Comment by rafiss** [comment]
I added a `backport-22.2.x` label. if this is a GA-blocker, then I'll leave it to you to add a `backport-22.2.0` label

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89114)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @koorosh, @RichardJCai, @Santamaura, and @zachlite)

___
*[`pkg/sql/set_cluster_setting.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_E5PT2xV8qG5u6ZkK:-ND_E5PU7nrfDUVb5OYG:bqi8ngv) ([raw file](https://github.com/cockroachdb/cockroach/blob/33140f3d5eacd5bfc5794ce95bac52db43c7c402/pkg/sql/set_cluster_setting.go#L68)):*
> ```Go
> func checkPrivilegesForSetting(ctx context.Context, p *planner, name string, action string) error {
> 
> 	// logic for system privileges.
> ```

while trying to figure out a better interface for privileges, i realized that we can save a lot of lookups if we change this implementation to:

```
	// First check system privileges.
	hasModify := false
	hasView := false
	if p.ExecCfg().Settings.Version.IsActive(ctx, clusterversion.SystemPrivilegesTable) {
		if err := p.CheckPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYCLUSTERSETTING); err != nil {
			hasModify = true
			hasView = true
		} else if pgerror.GetPGCode(err) != pgcode.InsufficientPrivilege {
			return err
		}
		if !hasView {
			if err := p.CheckPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.VIEWCLUSTERSETTING); err != nil {
				hasView = true
			} else if pgerror.GetPGCode(err) != pgcode.InsufficientPrivilege {
				return err
			}
		}
	}

	// Fallback to role option if the user doesn't have the privilege.
	if !hasModify {
		ok, err := p.HasRoleOption(ctx, roleoption.MODIFYCLUSTERSETTING)
		if err != nil {
			return err
		}
		hasModify = hasModify || ok
		hasView = hasView || ok
	}

	// The "set" action requires MODIFYCLUSTERSETTING.
	if action == "set" && !hasModify {
		return pgerror.Newf(pgcode.InsufficientPrivilege,
			"only users with the %s privilege are allowed to %s cluster setting '%s'",
			privilege.MODIFYCLUSTERSETTING, action, name)
	}

	if !hasView {
		ok, err := p.HasRoleOption(ctx, roleoption.VIEWCLUSTERSETTING)
		if err != nil {
			return err
		}
		hasView = hasView || ok
	}

	// The "show" action requires either either MODIFYCLUSTERSETTING or VIEWCLUSTERSETTING privileges.
	if action == "show" && !hasView {
		return pgerror.Newf(pgcode.InsufficientPrivilege,
			"only users with either %s or %s privileges are allowed to %s cluster setting '%s'",
			privilege.MODIFYCLUSTERSETTING, privilege.VIEWCLUSTERSETTING, action, name)
	}
	return nil
```
___
*[`pkg/sql/delegate/show_all_cluster_settings.go` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_57CdBFGWPNGOriYa:-ND_DT05EDc6cBKKHKd6:b-yfbjgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/33140f3d5eacd5bfc5794ce95bac52db43c7c402/pkg/sql/delegate/show_all_cluster_settings.go#L34)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm this is beyond the scope of your PR, but this doesn't seem that robust -- the error that's returned here might be because of a problem looking up the privileges, but it can't be differentiated from not having the privilege.

i'll try to clean up this interface separately.
</blockquote></details>

changing this interface won't really be possible. but see my suggestion in set_cluster_setting. i think ew can change the checks to be similar here

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89114)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @koorosh, @rafiss, @RichardJCai, and @zachlite)

___
*[`pkg/sql/crdb_internal.go` line 1605 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_5elb1XaF3jXV-v1D:-ND_X2U67dcoYl_jptLZ:b-n0ds3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/610ad9a1a27de59b8dde7262d116ccc1dac7d8f5/pkg/sql/crdb_internal.go#L1605)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

there should be tests added that show this change taking effect
</blockquote></details>

Added some tests to `crdb_internal` logic test file.
___
*[`pkg/sql/set_cluster_setting.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_5anu5AHagKEoy7hj:-ND_XAC769YTIdZLagEo:b-79nnn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/610ad9a1a27de59b8dde7262d116ccc1dac7d8f5/pkg/sql/set_cluster_setting.go#L68)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

there should be tests added that show this change taking effect
</blockquote></details>

Added some tests to `cluster_settings` logic test file.
___
*[`pkg/sql/set_cluster_setting.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_E5PT2xV8qG5u6ZkK:-ND_XIJiBBvKbOL34SFS:bw99q6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/33140f3d5eacd5bfc5794ce95bac52db43c7c402/pkg/sql/set_cluster_setting.go#L68)):*
> if err := p.CheckPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.MODIFYCLUSTERSETTING); err != nil
> if err := p.CheckPrivilege(ctx, syntheticprivilege.GlobalPrivilegeObject, privilege.VIEWCLUSTERSETTING); err != nil
 
I think we want this to be `err == nil` but otherwise I think it works, thanks for the suggestion!! 
___
*[`pkg/sql/delegate/show_all_cluster_settings.go` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_57CdBFGWPNGOriYa:-ND_XdzB1GIiGgh7VQ10:b-h0os3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/33140f3d5eacd5bfc5794ce95bac52db43c7c402/pkg/sql/delegate/show_all_cluster_settings.go#L34)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

changing this interface won't really be possible. but see my suggestion in set_cluster_setting. i think ew can change the checks to be similar here
</blockquote></details>

Yep, I've made use of the suggestion.
___
*[`pkg/sql/delegate/show_all_cluster_settings.go` line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_4_z39R61Fc68Oobd:-ND_Xhb_0ahCbQaskMwR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33140f3d5eacd5bfc5794ce95bac52db43c7c402/pkg/sql/delegate/show_all_cluster_settings.go#L49)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can you change this to use the `privilege` constants instead of `roleoption` ones?
</blockquote></details>

Done.
___
*[`pkg/sql/syntheticprivilege/global_privilege.go` line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-ND_5mP-9eBXzxbQx3yC:-ND_XjZy0ygyeg1HTVLy:b-ayi00s) ([raw file](https://github.com/cockroachdb/cockroach/blob/33140f3d5eacd5bfc5794ce95bac52db43c7c402/pkg/sql/syntheticprivilege/global_privilege.go#L62)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why was this needed? can a test be added that demonstrates why?
</blockquote></details>

The tests in `cluster_settings` cover this code path, we need to implement the `cat.Object` interface because `delegate.catalog`'s `CheckPrivilege` has a different signature from the `planner` so without the update `GlobalPrivilegeObject can't be passed. We can't make a planner either here due to dependency cycle.

**Review by rafiss — CHANGES_REQUESTED** [review]
this is looking good. just had very small nits now. thanks for the new tests

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-:-NDcy9l79_kqS4p-nbNA:b-y8o29n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @koorosh, @rafiss, @RichardJCai, @Santamaura, and @zachlite)

___
*[`pkg/sql/delegate/show_all_cluster_settings.go` line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-NDcvdad0u-kFnnNh55g:-NDcvdad0u-kFnnNh55h:b-ltc3l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c324f3ea7240534e188538fba4c6f7b611d5da1/pkg/sql/delegate/show_all_cluster_settings.go#L26)):*
> ```Go
> 	stmt *tree.ShowClusterSettingList,
> ) (tree.Statement, error) {
> 	isAdmin, err := d.catalog.HasAdminRole(d.ctx)
> ```

super nit: we can remove this check and the `isAdmin` variable, since the admin role should automatically have the privilegese
___
*[`pkg/sql/syntheticprivilege/global_privilege.go` line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-NDcxvlS1tHNnZEthycT:-NDcxvlT5bistCXcXjFT:b-euaamm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c324f3ea7240534e188538fba4c6f7b611d5da1/pkg/sql/syntheticprivilege/global_privilege.go#L63)):*
> ```Go
> // ID implements the cat.Object interface.
> func (p *GlobalPrivilege) ID() cat.StableID {
> 	return 0
> ```

nit: can you make this `descpb.InvalidID` (with a type conversion if needed)
___
*[`pkg/sql/syntheticprivilege/global_privilege.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-NDcxh9E4AOSr26Xupil:-NDcxh9I24TqwA7-mSe5:b-6gbsi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c324f3ea7240534e188538fba4c6f7b611d5da1/pkg/sql/syntheticprivilege/global_privilege.go#L68)):*
> ```Go
> // PostgresDescriptorID implements the cat.Object interface.
> func (p *GlobalPrivilege) PostgresDescriptorID() catid.DescID {
> 	return 0
> ```

nit: can you make this `descpb.InvalidID`

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89114)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @koorosh, @rafiss, @RichardJCai, and @zachlite)

___
*[`pkg/sql/delegate/show_all_cluster_settings.go` line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-NDcvdad0u-kFnnNh55g:-NDdhIw45-cZxxGMLZj9:b4jchf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c324f3ea7240534e188538fba4c6f7b611d5da1/pkg/sql/delegate/show_all_cluster_settings.go#L26)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: we can remove this check and the `isAdmin` variable, since the admin role should automatically have the privilegese
</blockquote></details>

Sure, done
___
*[`pkg/sql/syntheticprivilege/global_privilege.go` line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-NDcxvlS1tHNnZEthycT:-NDdhGA22aHFN3BWJ5c7:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c324f3ea7240534e188538fba4c6f7b611d5da1/pkg/sql/syntheticprivilege/global_privilege.go#L63)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can you make this `descpb.InvalidID` (with a type conversion if needed)
</blockquote></details>

Done
___
*[`pkg/sql/syntheticprivilege/global_privilege.go` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-NDcxh9E4AOSr26Xupil:-NDdhH5YB8cAy7weYimj:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c324f3ea7240534e188538fba4c6f7b611d5da1/pkg/sql/syntheticprivilege/global_privilege.go#L68)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can you make this `descpb.InvalidID`
</blockquote></details>

Done

**Review by rafiss — APPROVED** [review]
lgtm, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89114#-:-NDdhyvbB8osvWx7zpbY:b-348is5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @koorosh, @rafiss, @RichardJCai, and @zachlite)

**Comment by Santamaura** [comment]
TFTR!
bors r+

**Pull request merged**
