### PR TITLE
cli: fix debug pebble commands on encrypted stores

### LINKED ISSUE #110121: cli: make debug pebble commands work with encryption
The `debug pebble` commands don't currently work with encryption. There is some code around that but it doesn't work; perhaps it worked at some point and it got broken?

Edit: it appears the commands work but only when the store path is `cockroach-data`.

Jira issue: CRDB-31275

### PR DESCRIPTION
**Pull request by RaduBerinde**
Currently the debug pebble commands only work correctly on an
encrypted store if the encrypted store's path is `cockroach-data` or
the store directory is passed using `--store` (in addition to being
passed to the pebble subcommand itself). What's worse, knowledge of
this subtle fact was lost among team members.

The root cause is that we are trying to resolve encryption options
using the server config.  The difficulty is that there are a bunch of
different commands and there is no unified way to obtain the store
directory of interest

To fix this, we create `autoDecryptFS`. This is a `vfs.FS`
implementation which is able to automatically detect encrypted paths
and use the correct unencrypted FS. It does this by having a list of
known encrypted stores (the ones in the `--enterprise-encryption`
flag), and looking for any of these paths as ancestors of any path in
an operation. This new implementation replaces `swappableFS` and
`absoluteFS`.

We also improve the error message when we try to open an encrypted
store without setting up the key correctly.

Fixes: #110121

Release note (bug fix): `cockroach debug pebble` commands now work
correctly with encrypted stores which don't use the default
`cockroach-data` path without having to also pass `--store`.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I will look into adding some tests, but it will be a separate PR in case it's harder to backport. I will keep the issue open until then.

**Comment by RaduBerinde** [comment]
I found that there were existing tests, and they worked because they also passed a matching `--store` argument.

**Comment by RaduBerinde** [comment]
Added a test for `autoDecryptFS`.

**Comment by RaduBerinde** [comment]
Added some other reviewers since Jackson is out. I plan to backport to 23.1 and 22.2.

**Review by jbowens — APPROVED** [review]
:lgtm_strong: 

Clever approach!

> Reviewed 3 of 7 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110150#-:-Ne5Lv-m5Vzdtn8k-M4S:b48nr5f)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick, @itsbilal, and @RaduBerinde)

___
*[`pkg/cli/auto_decrypt_fs.go` line 245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110150#-Ne5JUZE7C0u4zrWo38Z:-Ne5JUZE7C0u4zrWo38_:bel3dib) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c7d4416fef9f8a8673715311bdb14b235afa501/pkg/cli/auto_decrypt_fs.go#L245)):*
> ```Go
> // path. Otherwise, returns the default FS.
> //
> // Assumes that path is absolute; the returned FS also assumes that any paths
> ```

nit: we also assume the path is "clean", eg, `filepath.Clean`, right?
___
*[`pkg/cli/auto_decrypt_fs_test.go` line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110150#-Ne5KfVo3HhXVxeE2RMT:-Ne5KfVo3HhXVxeE2RMU:bndtevq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c7d4416fef9f8a8673715311bdb14b235afa501/pkg/cli/auto_decrypt_fs_test.go#L80)):*
> ```Go
> `
> 	require.Equal(t, expected, output)
> }
> ```

Do other tests in the package exercise the autoDecryptFS, maybe indirectly through an `Engine`'s access? I want to make sure the breadth of the `autoDecryptFS` operations are covered (looks like code coverage flaked, otherwise that would probably tell me)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110150)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick, @itsbilal, and @jbowens)

___
*[`pkg/cli/auto_decrypt_fs.go` line 245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110150#-Ne5JUZE7C0u4zrWo38Z:-Ne5fryw10Q5X8GZvYkH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c7d4416fef9f8a8673715311bdb14b235afa501/pkg/cli/auto_decrypt_fs.go#L245)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: we also assume the path is "clean", eg, `filepath.Clean`, right?
</blockquote></details>

Done.
___
*[`pkg/cli/auto_decrypt_fs_test.go` line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110150#-Ne5KfVo3HhXVxeE2RMT:-Ne5eZHe7nhgc4i2OiRr:bthn2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c7d4416fef9f8a8673715311bdb14b235afa501/pkg/cli/auto_decrypt_fs_test.go#L80)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Do other tests in the package exercise the autoDecryptFS, maybe indirectly through an `Engine`'s access? I want to make sure the breadth of the `autoDecryptFS` operations are covered (looks like code coverage flaked, otherwise that would probably tell me)
</blockquote></details>

Looks like the cli tests are way too big for the coverage runner, I don't think we'll get coverage in this PR.

The interactive tests would cover the operations performed by `debug pebble db lsm`

**Comment by jbowens** [comment]
> Let me know if you have more ideas of what tests to add or if I should merge. TFTR!

:shipit:

**Pull request merged**
