### PR TITLE
sql/parser: support Y-M-D in intervals

### LINKED ISSUE #8617: sql: support Y-M-D in intervals
See: https://www.postgresql.org/docs/current/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT-EXAMPLES

See #8603

### PR DESCRIPTION
**Pull request by hainesc**
Fixes #8617

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10499)

### CODE REVIEW

**Comment by mjibson** [comment]
Modify the commit message to say "Fixes #8617". Rebase and squish this PR into a single commit.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/datum.go, line 1017 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10499#-KW1rRBvXsN7nbI-H6nR:-KW1rRBw5r29m1VrpwpI:b-vffk6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/52276dbf71ce68e04d345c7b7b65ac940cb73203/pkg/sql/parser/datum.go#L1017)):*
> ```Go
> 				return nil, makeParseError(s, TypeInterval, err)
> 			}
> 			ret = &DInterval{ret.Add(dur)}
> ```

Be consistent with use of struct field names: `{Duration: ret.Add(dur)}`.

---

*[pkg/sql/parser/eval_test.go, line 598 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10499#-KW1raakJMKSc3o6RBnk:-KW1raalbP589SAHk5sv:bjxx3hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/52276dbf71ce68e04d345c7b7b65ac940cb73203/pkg/sql/parser/eval_test.go#L598)):*
> ```Go
> 		{`'-1:2:3'::interval`, `-1h2m3s`},
> 		{`'-1234:56:54'::interval`, `-1234h56m54s`},
> 		{`'1-2'::interval`, `14m0d0ns`},
> ```

Need to add tests for all possibilities here:

1
1-2
1-2-3
3 4:00:00
2-3 4:05
1-2-3 4:05
3 4: (this works in postgres, I don't care if it works here but add a test to see what it does)
3 4 (this is an error in postgres, it should be an error here too)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10499#-:-KW1p7QNIDxZdxQjdIdN:b-hk1s7q)*

**Comment by hainesc** [comment]
Thanks for the review and advise.

**Comment by hainesc** [comment]
'1'::interval has been test at eval_test.go line 582.
More tests added.

**Comment by hainesc** [comment]
Sorry for commit a unrelated commit, I will revert ASAP.

**Comment by mjibson** [comment]
The commit message still isn't quite right, I wasn't specific enough. It should be:

```
sql/parser: support Y-M-D in intervals

Fixes #8617.
```

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/eval_test.go, line 607 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10499#-KW4GOqgMACok5xb5H4K:-KW4GOqgMACok5xb5H4L:b-e5wt24) ([raw file](https://github.com/cockroachdb/cockroach/blob/e16cecdb9e9b838ae0fa86f6b53d6c668708fd97/pkg/sql/parser/eval_test.go#L607)):*
> ```Go
> 		{`'1-2-3 4:08'::interval`, `14m3d4h8m0s`},
> 		{`'1-2 4:08:23'::interval`, `14m0d4h8m23s`},
> 		{`'1-2-3 4:08:23'::interval`, `14m3d4h8m23s`},
> ```

Still missing `3 4:00`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10499)*

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/eval_test.go, line 696 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10499#-KW9I20Vajlw53AEBGaO:-KW9I20Vajlw53AEBGaP:b-qk1kat) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ada643b998170360ad530be4a264ccb1bbccee9/pkg/sql/parser/eval_test.go#L696)):*
> ```Go
> 			`could not parse '3 4:' as type interval: could not parse '4:' as type interval: time: unknown unit hm in duration 4hm`},
> 		{`'3 4'::interval`,
> 			`could not parse '3 4' as type interval: interval: unknown unit  in postgres duration 3 4`},
> ```

Why are there two spaces between "unit" and "in"? Can we fix that error formatting here too?

---

*[pkg/sql/parser/interval.go, line 117 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10499#-KW9Jj-soNaC4-9dOv4w:-KW9Jj-soNaC4-9dOv4x:bbegobv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ada643b998170360ad530be4a264ccb1bbccee9/pkg/sql/parser/interval.go#L117)):*
> ```Go
> 	var d duration.Duration
> 	if len(s) == 0 {
> 		return d, fmt.Errorf("interval: invalid SQL stardard duration %s", s)
> ```

Change all of these to be `fmt.Errorf(errInvalidSQLDuration, s)` and add `const errInvalidSQLDuration = "interval: invalid SQL duration %s"` to the beginning of this function.

---

*[pkg/sql/parser/interval.go, line 119 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10499#-KW9HWH-73AeRBMIP5Xk:-KW9HWH0XYVj4xG1qp44:bp1ma5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ada643b998170360ad530be4a264ccb1bbccee9/pkg/sql/parser/interval.go#L119)):*
> ```Go
> 		return d, fmt.Errorf("interval: invalid SQL stardard duration %s", s)
> 	}
> 	// l := intervalLexer{str: s, offset: 0, err: nil}
> ```

Remove unused code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10499)*

**Comment by hainesc** [comment]
Thanks a lot. The double blank problem is caused by function `postgresToDuration(s)` when the input `s` looks like `'3 4'`, I will fix it. Thanks again.

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10499#-:-KWC4dEjDZ5T-wGrSqRP:bnfp4nl)*

**Pull request merged**
