### PR TITLE
kv: always enable local calls

### PR DESCRIPTION
**Pull request by petermattis**
For single-node benchmarks this gives a 10-15% perf boost.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4628)

### CODE REVIEW

**Comment by tschottdorf** [comment]
where the bench at pete!

**Comment by petermattis** [comment]
The numbers were similar to: https://github.com/cockroachdb/cockroach/pull/4046. I can run them again if you really want.

**Comment by tschottdorf** [comment]
Those make me happy enough. Any potential caveats (other than possible data
races)? I'm always suspicious when there are two paths and we don't really
test one of them a lot only in production.

**Comment by dt** [comment]
I might argue for keeping a flag but just inverting default, so we could `DISABLE_LOCAL_CALLS=1` to run a stricter test as desired.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4628#-:-KBLJxmodtB-LteIlkjT:1198672664)*

**Comment by dt** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4628)*

**Comment by petermattis** [comment]
Testing of the code paths is probably the biggest caveat. I haven't thought through whether we're getting sufficient testing of both local and non-local code paths.

**Comment by bdarnell** [comment]
The concern isn't exactly data races but the possibility that some code may be modifying a request object and things are succeeding only because the whole test runs in a single address space. (we've had these problems before). I'd be in favor of keeping the option and just flipping the default (and running tests occasionally with local calls turned off)

**Comment by petermattis** [comment]
The people have spoken: I've changed this to just flip the default.

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
