### PR TITLE
backupccl: fix span-after-finish and some other races in processors

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.
This is all happening because I want to make using Spans after they've been FInish()ed less tolerated than it has historically been.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72624)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dt)

___
*[pkg/ccl/backupccl/backup_processor.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCIJhx0Cm45iUJHf3V:-MoCIJhx0Cm45iUJHf3W:bl8iegt) ([raw file](https://github.com/cockroachdb/cockroach/blob/799b21ba83edb1397b60189fd4d7d3e3063e76e8/pkg/ccl/backupccl/backup_processor.go#L190)):*
> ```Go
> }
> 
> func (bp *backupDataProcessor) close() {
> ```

I think we also want to override `ConsumerClosed` implementation to call `close`.
___
*[pkg/ccl/backupccl/backup_processor.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCJ2Q42UWjKgO1cZ40:-MoCJ2Q42UWjKgO1cZ41:bkf01mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/943cca9d30dd71fc26376ca78473bf77e4067f53/pkg/ccl/backupccl/backup_processor.go#L171)):*
> ```Go
> 		bp.backupErr = err
> 		cancel()
> 		close(bp.progCh)
> ```

nit: maybe add a quick comment here that we have to close `bp.progCh` because `RunAsyncTaskEx` returned an error meaning that `runBackupProcessor` was not called?
___
*[pkg/ccl/backupccl/restore_data_processor.go, line 500 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCLZI8-IZ5OzpdAeoy:-MoCLZI8-IZ5OzpdAeoz:b-iocc99) ([raw file](https://github.com/cockroachdb/cockroach/blob/a539b38b5a83be6d4a205d3053aca7ccb5f24717/pkg/ccl/backupccl/restore_data_processor.go#L500)):*
> ```Go
> func (rd *restoreDataProcessor) ConsumerClosed() {
> 	if rd.InternalClose() {
> 		if rd.metaCh != nil {
> ```

I think we still want to close `rd.metaCh` here. Also I don't think we need `if rd.metaCh != nil` conditional.
___
*[pkg/ccl/backupccl/split_and_scatter_processor.go, line 270 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCK2BK56U-D_j142w2:-MoCK2BK56U-D_j142w3:btx8ooy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e8906b39a12cb42dc7120698322e6bcbd4bbb8/pkg/ccl/backupccl/split_and_scatter_processor.go#L270)):*
> ```Go
> 		ssp.scatterErr = err
> 		cancel()
> 		close(workerDone)
> ```

Should we close `ssp.doneScatterCh` here too? Do you wanna move closing of this channel in the main path into `runSplitAndScatter` for symmetry with the other processor?
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 439 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCKVig1y5Od0QPPhof:-MoCKVig1y5Od0QPPhog:boj6t1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/05635c651314b9f46c194bb51372135ec8ef64f1/pkg/ccl/changefeedccl/changefeed_processors.go#L439)):*
> ```Go
> 		return
> 	}
> 	// Shut down the poller if it wasn't already. Note that it will cancel
> ```

I think this comment should now be removed.

**Review by andreimatei — COMMENTED** [review]
Thanks for the careful review!
There's on `close` where we're not on the same page - see the comments. Give it another look pls.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-:-MoF9UkUDWohcT69FGuh:bmow833)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @yuzefovich)

___
*[pkg/ccl/backupccl/backup_processor.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCIJhx0Cm45iUJHf3V:-MoF45H52v74oXJinGQ3:b-tfsjif) ([raw file](https://github.com/cockroachdb/cockroach/blob/799b21ba83edb1397b60189fd4d7d3e3063e76e8/pkg/ccl/backupccl/backup_processor.go#L190)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we also want to override `ConsumerClosed` implementation to call `close`.
</blockquote></details>

I think you're right. Done.
___
*[pkg/ccl/backupccl/backup_processor.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCJ2Q42UWjKgO1cZ40:-MoF3EzA9i9K9qWR7rZ2:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/943cca9d30dd71fc26376ca78473bf77e4067f53/pkg/ccl/backupccl/backup_processor.go#L171)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe add a quick comment here that we have to close `bp.progCh` because `RunAsyncTaskEx` returned an error meaning that `runBackupProcessor` was not called?
</blockquote></details>

done
___
*[pkg/ccl/backupccl/restore_data_processor.go, line 500 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCLZI8-IZ5OzpdAeoy:-MoF5W1AB0VaAhqRHOy9:befnifo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a539b38b5a83be6d4a205d3053aca7ccb5f24717/pkg/ccl/backupccl/restore_data_processor.go#L500)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we still want to close `rd.metaCh` here. Also I don't think we need `if rd.metaCh != nil` conditional.
</blockquote></details>

I don't think we want the `close` here. Having it here seems to me to be racy with the writer (so I think this was a possible crash).
I've considered having the writer (`inputReader()` close `metaCh`, but I think that'd be bad for the reader, which is not equipped to handle that channel being closed. So I think it's better I leave it alone.

No?
___
*[pkg/ccl/backupccl/split_and_scatter_processor.go, line 270 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCK2BK56U-D_j142w2:-MoF8Vs98pjUlRAuxhpI:bx4nh62) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e8906b39a12cb42dc7120698322e6bcbd4bbb8/pkg/ccl/backupccl/split_and_scatter_processor.go#L270)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we close `ssp.doneScatterCh` here too? Do you wanna move closing of this channel in the main path into `runSplitAndScatter` for symmetry with the other processor?
</blockquote></details>

Done and done.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 439 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCKVig1y5Od0QPPhof:-MoF9QyY1ub0KJR7p8SF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05635c651314b9f46c194bb51372135ec8ef64f1/pkg/ccl/changefeedccl/changefeed_processors.go#L439)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think this comment should now be removed.
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72624)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @yuzefovich)

___
*[pkg/ccl/backupccl/split_and_scatter_processor.go, line 270 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCK2BK56U-D_j142w2:-MoFULJW7RJL3vurvnlw:bc48t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e8906b39a12cb42dc7120698322e6bcbd4bbb8/pkg/ccl/backupccl/split_and_scatter_processor.go#L270)):*
> Do you wanna move closing of this channel in the main path into runSplitAndScatter for symmetry with the other processor?

Actually, this proved to be incorrect both here and in the `backupDataProcessor`. This channel also synchronizes access to `ssp.scatterErr`, so it can't be closed until that variable is written. Synchronization is hard.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 7 of 7 files at r11, 4 of 4 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 2 of 2 files at r15, 1 of 1 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72624)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dt)

___
*[pkg/ccl/backupccl/restore_data_processor.go, line 500 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCLZI8-IZ5OzpdAeoy:-MoFbEaC5yKrojOAcwAH:bqndo3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a539b38b5a83be6d4a205d3053aca7ccb5f24717/pkg/ccl/backupccl/restore_data_processor.go#L500)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think we want the `close` here. Having it here seems to me to be racy with the writer (so I think this was a possible crash).
I've considered having the writer (`inputReader()` close `metaCh`, but I think that'd be bad for the reader, which is not equipped to handle that channel being closed. So I think it's better I leave it alone.

No?
</blockquote></details>

But currently this channel is never closed, right? It seems no bueno. What about closing `metaCh` after `cancelWorkersAndWait`? Then there will be no race.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72624)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @yuzefovich)

___
*[pkg/ccl/backupccl/restore_data_processor.go, line 500 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCLZI8-IZ5OzpdAeoy:-MoFdx_H0w52kGDBS_Ht:b-qy2yx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a539b38b5a83be6d4a205d3053aca7ccb5f24717/pkg/ccl/backupccl/restore_data_processor.go#L500)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

But currently this channel is never closed, right? It seems no bueno. What about closing `metaCh` after `cancelWorkersAndWait`? Then there will be no race.
</blockquote></details>

I wouldn't say it's necessarily no bueno. Nobody says you gotta close all the channels. If you know that nobody can read from a channel when you'd close it, then there's no point in closing it. You're suggesting doing it in `ConsumerClosed()`, right? If `ConsumerClosed` is called, we know there's no ongoing `Next()` call reading from the channel, and there will never be another `Next` call (right?). So, I could close the chan in `ConsumerClosed()`, but I think it would only serve to confuse the reader about why that's necessary / who is the closing synchronizing with.

I think that, if you want to insist that someone has to close this channel, that someone needs to be associated with the writing side, not the reading side (and `ConsumerClosed()` is associated with the reading side). The writing side is `inputReader()`. So, we could have that guy close the channel when the function finishes, but then I think we need to worry about the reader side (`Next()`) properly handling that closing. Right now the reader would do the wrong thing if it reads from the closed channel - it would return `nil, nil`, which I think is not good because then `Next()` would not be called again to process `rd.progCh`. My worry is that it's possible for the reader to see this empty channel; I think that would only happen in a race with the closing of `rd.Ctx.Done()`, but still I think it'd be bad for the closing of `metaCh` to win that race.
So, we could prepare `Next()` to handle the closing of `metaCh` by disabling reading from that channel and looping around. But, I don't think it's worth it / don't feel the need for it. Never closing `metaCh` seems fine to me.

Thoughts?

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-:-MoFpL7MBU6ynqTTw3H3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @dt)

___
*[pkg/ccl/backupccl/restore_data_processor.go, line 500 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-MoCLZI8-IZ5OzpdAeoy:-MoFoqbj09XAE9Ijj2m4:boy5qt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a539b38b5a83be6d4a205d3053aca7ccb5f24717/pkg/ccl/backupccl/restore_data_processor.go#L500)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I wouldn't say it's necessarily no bueno. Nobody says you gotta close all the channels. If you know that nobody can read from a channel when you'd close it, then there's no point in closing it. You're suggesting doing it in `ConsumerClosed()`, right? If `ConsumerClosed` is called, we know there's no ongoing `Next()` call reading from the channel, and there will never be another `Next` call (right?). So, I could close the chan in `ConsumerClosed()`, but I think it would only serve to confuse the reader about why that's necessary / who is the closing synchronizing with.

I think that, if you want to insist that someone has to close this channel, that someone needs to be associated with the writing side, not the reading side (and `ConsumerClosed()` is associated with the reading side). The writing side is `inputReader()`. So, we could have that guy close the channel when the function finishes, but then I think we need to worry about the reader side (`Next()`) properly handling that closing. Right now the reader would do the wrong thing if it reads from the closed channel - it would return `nil, nil`, which I think is not good because then `Next()` would not be called again to process `rd.progCh`. My worry is that it's possible for the reader to see this empty channel; I think that would only happen in a race with the closing of `rd.Ctx.Done()`, but still I think it'd be bad for the closing of `metaCh` to win that race.
So, we could prepare `Next()` to handle the closing of `metaCh` by disabling reading from that channel and looping around. But, I don't think it's worth it / don't feel the need for it. Never closing `metaCh` seems fine to me.

Thoughts?
</blockquote></details>

Yeah, makes sense. For some reason I thought that it was a general principle that _someone_ must close the channel eventually, but it is indeed unnecessary in a case when we know is blocked on reading from this channel. I.e. we only need to close the channels as means of control flow, and I was thinking from the perspective of the garbage collection - and there we don't need the `close`.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72624#-:-MoFv4Sj3c1aPJjkzcPO:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @dt)

**Pull request merged**
