### PR TITLE
sql: only fetch specific columns needed to validate check constraints for UPDATES

### PR DESCRIPTION
**Pull request by nvb**
This change begins with some cleanup I stumbled upon when looking into addressing https://github.com/cockroachdb/cockroach/issues/30618. The tweaks are minor, although the second commit might be backport worthy. It then addresses a related issue that was slightly easier to fix.

The change addresses a longstanding TODO that's related to #30618 but was a little easier to start with. The goal is to only request the columns used in check constraints when performing an UPDATE instead of blindly requesting all columns when a check constraint is present. 8d37935 did all of the heavy lifting for this. This change just plugs it in.

The new logic tests fail if we don't correctly request the columns we need for the check constraint. Interestingly, this isn't because we don't fetch the other columns from KV. Instead, it's because we
don't decode them and pass them up the stack.

### CODE REVIEW

**Review by knz — APPROVED** [review]
Thanks for this change.

It looks to me like the new logic test would work before your PR, because the code was requesting all columns. Did it not?

If it did indeed work, then I think your PR is missing a test that demonstrates the before/after change. Perhaps a report of a logical plan where the requested columns are detailed?

If it did not work previously, that means there was a bug. In that case I'd like to see a release note.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30707#-:-LNQOZUE26WGwV_1Gt0S:b-xo1hrq)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
TFTR!

> It looks to me like the new logic test would work before your PR, because the code was requesting all columns. Did it not?

Yes, it would. The new logic test is the only test in our code base that would fail if we didn't specifically check the `desc.Checks` at all in `update.go` at all. For instance, it fails if we changed:
```
if rowsNeeded || len(desc.Checks) > 0 {
```
to
```
if rowsNeeded {
```

> If it did indeed work, then I think your PR is missing a test that demonstrates the before/after change. Perhaps a report of a logical plan where the requested columns are detailed?

Good point. I was hoping to merge this after https://github.com/cockroachdb/cockroach/pull/30744 so that we could see the difference in the requested spans, but I'll look into other ways to test this. Hopefully the requested columns are detailed in the logical plan.

**Review by knz — COMMENTED** [review]
> Good point. I was hoping to merge this after #30744 so that we could see the difference in the requested spans, but I'll look into other ways to test this. Hopefully the requested columns are detailed in the logical plan.

Thanks. Let me know if you need help.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30707#-:-LO48zbw-KJeRmcPLaGH:b3011is)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — COMMENTED** [review]
https://github.com/cockroachdb/cockroach/pull/30744 made this much easier to test. Please see the new logic test. @solongordon might be interested in this as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30707#-:-LR6stY_4IdJHbamF8B8:b-eklnbp)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
Thanks for the extra tests. LGTM modulo resolution of my question below.

> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30707#-:-LR7uD8k5NirXJpq_S0r:b-g5lhlr)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/check_constraints, line 305 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/30707#-LR7u4ld1Sa1XlOqDRRq:-LR7u4ld1Sa1XlOqDRRr:byetb18) ([raw file](https://github.com/cockroachdb/cockroach/blob/576f83c08fff3cc844e1c581fe689eeae8a2dc54/pkg/sql/logictest/testdata/logic_test/check_constraints#L305)):*
> ```
> UPDATE t9 SET b = 6 WHERE a = 5
> 
> # Only column families that are needed to validate check constraints are fetched.
> ```

I'm not sure this test tells us which columns are fetched (or not) -- I think only the list of columns produced by `explain(eerbose)` can tell us that.

**Review by nvb — COMMENTED** [review]
TFTR.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30707#-:-LR884EmA9V8zhJ5I6b9:b4e9j4i)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/check_constraints, line 305 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/30707#-LR7u4ld1Sa1XlOqDRRq:-LR883tP2CF6ubbIOp-N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/576f83c08fff3cc844e1c581fe689eeae8a2dc54/pkg/sql/logictest/testdata/logic_test/check_constraints#L305)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm not sure this test tells us which columns are fetched (or not) -- I think only the list of columns produced by `explain(eerbose)` can tell us that.
</blockquote></details>

Done.

**Pull request merged**
