### PR TITLE
amazon: add custom retryer to retry on `read: connection reset`

### PR DESCRIPTION
**Pull request by adityamaru**
This change implements a custom retryer that we use when
initializing a new s3 client for interaction with the external
storage sink. This change was motivated by the increased number
of backup job failures we were observing with a `read: connection reset`
error being thrown by s3.

A read connection reset error is thrown when the SDK is unable to read
the response of an underlying API request due to a connection reset. The
DefaultRetryer in the AWS SDK does not treat this error as a retryable error
since the SDK does not have knowledge about the idempotence of the request,
and whether it is safe to retry -
https://github.com/aws/aws-sdk-go/pull/2926#issuecomment-553637658.
In CRDB all operations with s3 (read, write, list) are considered idempotent,
and so we can treat the read connection reset error as retryable too.

Release note (bug fix): Retry s3 operations when they error out with a
read connection reset error instead of failing the top level job.

### CODE REVIEW

**Comment by adityamaru** [comment]
I ran the s3 tests locally, and they work fine. I'm going to run a few bigger backups/restores to make sure there's no regression.

**Review by stevendanna — APPROVED** [review]

**Review by miretskiy — APPROVED** [review]
super nice.

**Comment by adityamaru** [comment]
Sanity checked it on a largish backup and restore, and also filed https://github.com/cockroachdb/cockroach/issues/83534

TFTR!

bors r=miretskiy,stevendanna

**Comment by adityamaru** [comment]
Going to manually open a backport to 22.1 since we might want a custom build and bors is slow.

**Pull request merged**
