### PR TITLE
exec: wrap [][]bytes and introduce templating functions

### PR DESCRIPTION
**Pull request by asubiotto**
This PR is the first couple of commits of #38876, to avoid having to rebase.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39150)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec/any_not_null_agg_tmpl.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1j8vC9GylspuyITqu:-Ll1j8vD0G9-Ci_zcuFs:b67bez8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44783f597949757a72f6ec2d6eb931d2d817411/pkg/sql/exec/any_not_null_agg_tmpl.go#L184)):*
> ```Go
> 		// output.
> 		// TODO(asubiotto): I can't use execgen.{Get,Set} here because the receiver
> 		// names are different in _FIND_ANY_NO_NULL and the main loop. Any ideas?
> ```

Looks like you fixed it - does the comment still belong?
___
*[pkg/sql/exec/execgen/placeholders.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1jUmNAXx3xnEdad5x:-Ll1jUmNAXx3xnEdad5y:b-xx5u3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7499ec3b9106155d94ecb56991f8e58f8dabd6/pkg/sql/exec/execgen/placeholders.go#L47)):*
> ```Go
> }
> 
> func LOOP(target interface{}) bool {
> ```

Thoughts on renaming this to `RANGE` so it matches Go's syntax better? And making `i` not be the required loop variable?

```
for i := range x ...
```

```
for i := execgen.RANGE(x)
```

I know the bytes one currently uses a normal for loop, but I think you could easily convert it into a range loop if you range over the lengths array? Or does that not work? I don't like the idea of having `i` be the hidden loop variable name... if this doesn't work, I feel like we should just include the loop variable name in the arguments to `execgen.RANGE`.
___
*[pkg/sql/exec/execgen/cmd/execgen/any_not_null_agg_gen.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1nwfEBbIlIP2OGcl0:-Ll1nwfFA9DQFg4O05Fe:bn9m3vh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44783f597949757a72f6ec2d6eb931d2d817411/pkg/sql/exec/execgen/cmd/execgen/any_not_null_agg_gen.go#L30)):*
> ```Go
> // TODO(asubiotto): I need to make this wrapper so that there is one receiver
> // name for the type throughout the file, otherwise multiple replacements need
> // to be done since the type is referenced by ".Global" in _FIND_ANY_NOT_NULL
> ```

I think we could fix this (later) by making a variable name that always contains the current type being templated, like $curtype or something, so that everybody could always use that safely without having to do anything weird.

Alternatively, you could fix it just this one case by assigning `.` to a new variable at the top of any not null, and assigning `.Global` to that same variable name inside of the inner loop.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39150)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/exec/any_not_null_agg_tmpl.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1j8vC9GylspuyITqu:-LlHmUlN8Nx5ejDRlx0L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44783f597949757a72f6ec2d6eb931d2d817411/pkg/sql/exec/any_not_null_agg_tmpl.go#L184)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Looks like you fixed it - does the comment still belong?
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/placeholders.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1jUmNAXx3xnEdad5x:-LlHmWP8BWDxQJTKfQiw:baybwgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7499ec3b9106155d94ecb56991f8e58f8dabd6/pkg/sql/exec/execgen/placeholders.go#L47)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Thoughts on renaming this to `RANGE` so it matches Go's syntax better? And making `i` not be the required loop variable?

```
for i := range x ...
```

```
for i := execgen.RANGE(x)
```

I know the bytes one currently uses a normal for loop, but I think you could easily convert it into a range loop if you range over the lengths array? Or does that not work? I don't like the idea of having `i` be the hidden loop variable name... if this doesn't work, I feel like we should just include the loop variable name in the arguments to `execgen.RANGE`.
</blockquote></details>

This is another example of why it's extremely useful to make templates go code, renaming this using goland's normal rename was super easy! I can't do `for i := execgen.RANGE` because the expression needs to evaluate to a boolean but I agree that we probably shouldn't make i the required variable. Unfortunately the only thing that comes to mind is passing the variable identifier as a string to `RANGE`, any ideas?
___
*[pkg/sql/exec/execgen/cmd/execgen/any_not_null_agg_gen.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1nwfEBbIlIP2OGcl0:-LlIHpsxD_Wj4xD8W2XC:bqzqyne) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44783f597949757a72f6ec2d6eb931d2d817411/pkg/sql/exec/execgen/cmd/execgen/any_not_null_agg_gen.go#L30)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think we could fix this (later) by making a variable name that always contains the current type being templated, like $curtype or something, so that everybody could always use that safely without having to do anything weird.

Alternatively, you could fix it just this one case by assigning `.` to a new variable at the top of any not null, and assigning `.Global` to that same variable name inside of the inner loop.
</blockquote></details>

I tried the variable route but it was failing for confusing reasons. I ended up just removing this stuff in favor of explicitly using template language in find any not null, which I think is fine for now.

**Comment by asubiotto** [comment]
Not a high priority but just a note that this is RFAL @jordanlewis

**Review by jordanlewis — COMMENTED** [review]
All of this looks good to go! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-:-Ll1tEgL5aSF1_G6yZHC:b-gas84u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec/execgen/placeholders.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1jUmNAXx3xnEdad5x:-LlXSscqE4Gb6SvS8Vp3:b-g2qlx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7499ec3b9106155d94ecb56991f8e58f8dabd6/pkg/sql/exec/execgen/placeholders.go#L47)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This is another example of why it's extremely useful to make templates go code, renaming this using goland's normal rename was super easy! I can't do `for i := execgen.RANGE` because the expression needs to evaluate to a boolean but I agree that we probably shouldn't make i the required variable. Unfortunately the only thing that comes to mind is passing the variable identifier as a string to `RANGE`, any ideas?
</blockquote></details>

I don't understand why the expression needs to evaluate to a boolean?
___
*[pkg/sql/exec/execgen/cmd/execgen/any_not_null_agg_gen.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1nwfEBbIlIP2OGcl0:-LlXT1B-BwbCsCuNavHT:buq5q0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44783f597949757a72f6ec2d6eb931d2d817411/pkg/sql/exec/execgen/cmd/execgen/any_not_null_agg_gen.go#L30)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I tried the variable route but it was failing for confusing reasons. I ended up just removing this stuff in favor of explicitly using template language in find any not null, which I think is fine for now.
</blockquote></details>

Fair, plz add a comment above the comments though :)

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39150)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/exec/execgen/placeholders.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1jUmNAXx3xnEdad5x:-LlYX_AOAjTcxI2D4Wku:b-c8fwxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7499ec3b9106155d94ecb56991f8e58f8dabd6/pkg/sql/exec/execgen/placeholders.go#L47)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't understand why the expression needs to evaluate to a boolean?
</blockquote></details>

So that we can still have valid go code: i.e. `for true {}` is valid but `for i:= true` is not. I made the change to have a variable name be an argument.
___
*[pkg/sql/exec/execgen/cmd/execgen/any_not_null_agg_gen.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1nwfEBbIlIP2OGcl0:-LlYXXhRE8RL4FYMcUuZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44783f597949757a72f6ec2d6eb931d2d817411/pkg/sql/exec/execgen/cmd/execgen/any_not_null_agg_gen.go#L30)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Fair, plz add a comment above the comments though :)
</blockquote></details>

Done.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39150)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec/execgen/placeholders.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39150#-Ll1jUmNAXx3xnEdad5x:-LlZgO3e1r7_7XggUObI:b-vp3g4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7499ec3b9106155d94ecb56991f8e58f8dabd6/pkg/sql/exec/execgen/placeholders.go#L47)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

So that we can still have valid go code: i.e. `for true {}` is valid but `for i:= true` is not. I made the change to have a variable name be an argument.
</blockquote></details>

Ah... it's yet another limitation caused by our incomplete regexp takeover of Go :)

I'm okay with this, but I do think if you keep it this way you should switch the order of the arguments to `exec.RANGE` so they mimic the normal usage.

2 more ideas:

```
for i := exec.RANGE(x);; {
}
```

Then you could have the right semantics, at the cost of requiring 2 weird semicolons for every range loop.

Or:

```
for i := range exec.EVERY(x) {
```
and then regex replace `range exec.EVERY(x)` with the right thing, instead of just looking for `exec.RANGE` - we don't have a requirement to only replace a single token at a time.

I think I like the last one the best...not sure about `EVERY` vs `ALL` or something, but it does seem like a big win to be able to keep the `range` keyword if we can.

Sorry for bikeshedding this so badly!

**Comment by asubiotto** [comment]
No problem. I changed the `RANGE` to take the identifier as the first argument but I agree that we should go for your second proposed solution: `for i := range exec.EVERY(x)`. However, I think I'm going to work on that in a separate PR to just get this big refactor merged in independently.

**Comment by asubiotto** [comment]
@danhhz heads up that I added `pkg/sql/exec/execgen` to the `pkg/workload/dep_test`.go` whitelist since it is a transitive dependency through `coldata`. The package is essentially a couple of dummy function definitions used in templating.

**Comment by danhhz** [comment]
adding that dep lgtm. I do eventually want to remove codegen from coldata, which is one of the last steps in making pkg/workload go-get-able and would also help with stuff like this

**Comment by asubiotto** [comment]
TFTRs!

bors r=jordanlewis

**Pull request merged**
