### PR TITLE
typedesc: avoid slice copy when hydrating enums

### PR DESCRIPTION
**Pull request by rafiss**
A profile showed that when an enum has a lot of values, hydrating it can become expensive since it requires initializing a large slice.

Since these objects are immutable, we can just reference the slice directly.

```
goos: darwin
goarch: arm64
                    │   bench-old   │              bench-new              │
                    │    sec/op     │    sec/op     vs base               │
ResolveTypeByOID-10   106.266µ ± 4%   1.246µ ± 14%  -98.83% (p=0.002 n=6)

                    │   bench-old   │             bench-new             │
                    │     B/op      │    B/op     vs base               │
ResolveTypeByOID-10   422992.5 ± 0%   453.0 ± 0%  -99.89% (p=0.002 n=6)

                    │ bench-old  │             bench-new             │
                    │ allocs/op  │ allocs/op   vs base               │
ResolveTypeByOID-10   51.00 ± 4%   12.00 ± 0%  -76.47% (p=0.002 n=6)
```

informs https://github.com/cockroachdb/cockroach/issues/109228
Release note (performance improvement): Improved the cost of resolving a
user-defined enum type that has many values.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
Good find!

:LGTM:

Ah, the collections hydration cache doesn't save us because just the initial hydration in an implicit txn is expensive

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109394#-:-Ncd0KwN8JuMQH1vZKNB:b-fe0n01)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
ah interesting. where is the hydration cache? maybe there's a place where we can fix this there.

**Comment by rafiss** [comment]
ah ok. the problem here is actually with hydrating the `*types.T`; hydrating the descriptor itself didn't show up in that profile. i don't know if there's a good place where we can cache `types.T` hydration,

**Comment by fqazi** [comment]
> ah ok. the problem here is actually with hydrating the `*types.T`; hydrating the descriptor itself didn't show up in that profile. i don't know if there's a good place where we can cache `types.T` hydration,

Ah, that makes sense

**Pull request merged**
