### PR TITLE
sql: introduce a new virtual database crdb_internal

### PR DESCRIPTION
**Pull request by knz**
This exposes the following virtual tables:
- `tables`: table descriptor details.
- `schema_changes`: schema changes currently ongoing.
- `sessions`: SQL sessions on the node where the query inspecting the
  `sessions` table is ran.
- `txns`: SQL transactions on the node where the query inspecting the
  `txns` table is ran.
- `leases`: table leases held on the node where the query inspecting
  the `leases` table is ran.

These tables are intended for debugging / troubleshooting purposes.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10317)

### CODE REVIEW

**Comment by knz** [comment]
I found myself needing this information while working on #10188 and #9259.

The sessions table in particular is a stepping stone towards cancelling sessions preemptively from another client.

**Comment by knz** [comment]
cc @vivekmenezes, this exposes the schema changes from SQL.

**Comment by tamird** [comment]
Haven't reviewed in detail but this is great!

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-:-KVKktOTiI9k7Z-K-_sC:b6bwa42)*

**Comment by petermattis** [comment]
We already have the "system" database. I would have expected these virtual
tables to live there, though I realize there might be practical
considerations which make that difficult.

**Comment by knz** [comment]
@petermattis currently our virtual table infrastructure does not support hanging off virtual tables from a concrete database. I'll have a look to see if that can be arranged.

**Comment by knz** [comment]
I researched this a bit more; since it would be a non-trivial change to both the virtual descriptor initialization and the lookup code, I filed #10319 to follow up on this.

**Comment by bdarnell** [comment]
The preferred acronym is `crdb`, not `cdb`. 

A side benefit of making this `crdb_internal` instead of `system` is that we can be freer about schema changes on these virtual tables while we're figuring out their uses. Even if we could put them in `system` we might want to leave them in `crdb_internal` and only let them graduate to `system` when we're ready to freeze and document them for public use. 

---

Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/cdb_internal.go, line 127 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KVQQw9jDpsZ1bIpOse3:-KVQQw9klbpiprbqfJ8H:b-x92oq) ([raw file](https://github.com/cockroachdb/cockroach/blob/27a25e54efd0fb54970ce054686b50330bcb14a0/pkg/sql/cdb_internal.go#L127)):*
> ```Go
>   STATE         STRING NOT NULL,
>   DIRECTION     STRING NOT NULL,
>   RESUME_KEY    BYTES NOT NULL,
> ```

Exposing actual data here makes me nervous. As long as we limit it to tables that the user has permission to query anyway, I guess it's OK, but I'd still rather leave the key fields out unless and until we're ready to use them in some sort of progress estimator. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-:-KVQQCrgE4mAVW1P7xye:b-c1stjd)*

**Comment by knz** [comment]
I have renamed to "crdb" as suggested. I removed the columns with the resume keys, I understand your point as a security concern (potentially revealing stored information).

---

Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-:-KVQj4fyIMS1XMErRr_g:b-7xkcg9)*

**Comment by knz** [comment]
ping?

**Comment by andreimatei** [comment]
LGTM, good stuff

As we discussed, let's de-racify this by maintaining a copy of all the sessions state (other than the mem accounts) that we updated atomically after every statement.

---

Review status: 0 of 18 files reviewed at latest revision, 16 unresolved discussions, all commit checks successful.

---

*[pkg/sql/crdb_internal.go, line 15 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_F8KLU5KTBC1Ixwn3:-KW_F8KLU5KTBC1Ixwn4:b-vls386) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L15)):*
> ```Go
> // permissions and limitations under the License.
> //
> // Author: Raphael 'kena' Poss (knz@cockroachlabs.com)
> ```

mind adding a preamble to the file with the create statements for all the tables and a few words?

---

*[pkg/sql/crdb_internal.go, line 41 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_E_J7uZH7ItJsxdiF:-KW_E_J7uZH7ItJsxdiG:bfggzr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L41)):*
> ```Go
> }
> 
> type sessionRegistry struct {
> ```

I could have sworn that we have such a struct somewhere cause I thought we close all the sessions when we "drain". But now I can't see it in pgserver... Maybe check again in case I'm blind.

also this will probably be useful for @asubiotto if we do add better draining

---

*[pkg/sql/crdb_internal.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_FaPzU4JRb7GTUt10:-KW_FaPzU4JRb7GTUt11:b-gxnjhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L73)):*
> ```Go
>   FORMAT_VERSION           STRING NOT NULL,
>   STATE                    STRING NOT NULL,
>   SC_LEASE_NODE_ID         INT,
> ```

I wonder if these lease columns are gonna do more harm than good. They're not the only leases that the node might have for that descriptor. In fact, I think they might not even be the only lease the node might have for the *current version* of the descriptor.

I'd suggest dropping them, to be replaced (later?) by a table dedicated to leases. In fact, such a table (real one, not virtual) already exists.

---

*[pkg/sql/crdb_internal.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_GQhk6q9xSAhHCIU3:-KW_GQhk6q9xSAhHCIU4:bycarhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L118)):*
> ```Go
> var crdbInternalSchemaChangesTable = virtualSchemaTable{
> 	schema: `
> CREATE TABLE crdb_internal.schema_changes (
> ```

can we also put version info in this table (I forgot how things work exactly, but ideally we'd see the version that the descriptor would get updated to once the mutation is done).

---

*[pkg/sql/crdb_internal.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_H6uvLTrNVBOTVHcG:-KW_H6uvLTrNVBOTVHcH:b-uqs9ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L118)):*
> ```Go
> var crdbInternalSchemaChangesTable = virtualSchemaTable{
> 	schema: `
> CREATE TABLE crdb_internal.schema_changes (
> ```

technically what you're returning here are mutations, not schema changes. 

---

*[pkg/sql/crdb_internal.go, line 122 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_GGOfdYLCHPcBsE9p:-KW_GGOfdYLCHPcBsE9q:b2xpoi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L122)):*
> ```Go
>   PARENT_ID     INT NOT NULL,
>   NAME          STRING NOT NULL,
>   TYPE          STRING NOT NULL,
> ```

please add a comment to TYPE

---

*[pkg/sql/crdb_internal.go, line 178 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_Hp3F3LolzBxjAacL:-KW_Hp3F3LolzBxjAacM:b-tjv92k) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L178)):*
> ```Go
> var crdbInternalSessionsTable = virtualSchemaTable{
> 	schema: `
> CREATE TABLE crdb_internal.sessions (
> ```

this table is node-specific, whereas the others aren't. Maybe it's worth putting in a node-specific virtual db, or calling it "node_sessions".

---

*[pkg/sql/crdb_internal.go, line 182 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_HLh5cZ9dNqrpZWQ_:-KW_HLh5cZ9dNqrpZWQa:b-4ax0jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L182)):*
> ```Go
>   SESSION_ID              INT NOT NULL,
>   CLIENT                  STRING NOT NULL,
>   "USER"                  STRING NOT NULL,
> ```

why the quotes?

---

*[pkg/sql/crdb_internal.go, line 214 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_HVYtOvka_c6Mm4fB:-KW_HVYtOvka_c6Mm4fC:b-fngo90) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L214)):*
> ```Go
> 			if err := addRow(
> 				nodeID,
> 				parser.NewDInt(parser.DInt(int64(uintptr(unsafe.Pointer(s))))),
> ```

loool. Are you sure this is a sane identifier to expose? Perhaps we should generate some guids at session start? And perhaps the identifier should start with the "client" as a prefix.

---

*[pkg/sql/crdb_internal.go, line 234 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_I042p-zJ1Z6FYySq:-KW_I042p-zJ1Z6FYySr:b5gy8vu) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L234)):*
> ```Go
> }
> 
> var crdbInternalTxnsTable = virtualSchemaTable{
> ```

this table is also node-specific. I see your todo below; in the meantime perhaps call it `node_txns`.

---

*[pkg/sql/crdb_internal.go, line 243 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_IHzqADnWGha-6H4Y:-KW_IHzqADnWGha-6H4Z:bwo8wn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L243)):*
> ```Go
>   EPOCH             INT NOT NULL,
>   TIMESTAMP         TIMESTAMP NOT NULL,
>   TIMESTAMP_L       DECIMAL NOT NULL,
> ```

s/L/LOGICAL ?

---

*[pkg/sql/crdb_internal.go, line 252 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_IOy9mpYwX8zqwID8:-KW_IOy9mpYwX8zqwID9:b3cridc) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L252)):*
> ```Go
>   ORIG_TIMESTAMP_L  DECIMAL NOT NULL,
>   WRITING           BOOL NOT NULL,
>   NUM_INTENTS       INT NOT NULL
> ```

I believe these are ranges of intents, not actual intents, right? Maybe it's better to remove.

---

*[pkg/sql/crdb_internal.go, line 273 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_Ilr5Mu42oJL8bFlY:-KW_Ilr5Mu42oJL8bFlZ:b-koyphs) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L273)):*
> ```Go
> 
> 			txn := s.TxnState.txn
> 			if txn == nil {
> ```

i think you should be looking at `TxnState.State != NoTxn`

---

*[pkg/sql/crdb_internal.go, line 313 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_J8KeQlOrwC_xnFjj:-KW_J8KeQlOrwC_xnFjk:blptnwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L313)):*
> ```Go
> var crdbInternalLeasesTable = virtualSchemaTable{
> 	schema: `
> CREATE TABLE crdb_internal.leases (
> ```

`node_leases` ?

---

*[pkg/ui/config.js, line 1156 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_JJFeUG7kz9tE6C8s:-KW_JJFeUG7kz9tE6C8t:b-yad8tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/ui/config.js#L1156)):*
> ```JavaScript
>       "process": "github:jspm/nodelibs-process@0.1.2"
>     },
>     "npm:source-map-support@0.4.6": {
> ```

what's up with this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-:-KW_EK1lNPG0-MIrb_Gg:b-jk6gpk)*

**Comment by knz** [comment]
Discussed this with @andreimatei today. There's an underlying design issue here that needs to be addressed: currently the code accesses the fields of Session and client.Txn concurrently without any locks. I am wary of adding locking to every access to Session and Txn where the common case is sequential access that doesn't need locking and the rare case is concurrent access by the crdb_internal tables. 

My initial impetus while writing this patch was "We don't care, crdb_internal doesn't need to guarantee transactional access to the structs" but then Andrei pointed out our race detector will whine about this.

Andrei had an idea, to make a shadow copy of the fields we want to access from crdb_internal at the end of every statement in Executor; and have the copy locked properly for concurrent access. Thoughts?

**Comment by knz** [comment]
Review status: 0 of 18 files reviewed at latest revision, 16 unresolved discussions, all commit checks successful.

---

*[pkg/sql/crdb_internal.go, line 41 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_E_J7uZH7ItJsxdiF:-KW_JkCP3089RCalzWfJ:b-4zx74a) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L41)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I could have sworn that we have such a struct somewhere cause I thought we close all the sessions when we "drain". But now I can't see it in pgserver... Maybe check again in case I'm blind.
> 
> also this will probably be useful for @asubiotto if we do add better draining
</details>
The network contexts are closed, which in turn cause the KV contexts to be closed, which in turn cause the state-modifying operations in Executor to fail, which cause pgwire to attempt reporting errors to the client, which fails because the network connection is closed, which causes the session to terminate and be cleaned up normally. 

It's a bit indirect but that's how it works AFAIK.

---

*[pkg/sql/crdb_internal.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_FaPzU4JRb7GTUt10:-KW_KN1U8Mi80H0Mj57i:bvm0eee) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L73)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I wonder if these lease columns are gonna do more harm than good. They're not the only leases that the node might have for that descriptor. In fact, I think they might not even be the only lease the node might have for the *current version* of the descriptor.
> 
> I'd suggest dropping them, to be replaced (later?) by a table dedicated to leases. In fact, such a table (real one, not virtual) already exists.
</details>
Ah, smart move.

---

*[pkg/sql/crdb_internal.go, line 178 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_Hp3F3LolzBxjAacL:-KW_KVGhl5AM_GmC-7o-:bwncvbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L178)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> this table is node-specific, whereas the others aren't. Maybe it's worth putting in a node-specific virtual db, or calling it "node_sessions".
</details>
the tables that are node-specific have a column "node_id". 

---

*[pkg/sql/crdb_internal.go, line 182 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_HLh5cZ9dNqrpZWQ_:-KW_KZK-4uHMZuyjbuDb:b2ouof5) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L182)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> why the quotes?
</details>
It's a non-columnname keyword.

---

*[pkg/sql/crdb_internal.go, line 214 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_HVYtOvka_c6Mm4fB:-KW_KdMm-VGyl_qKBP6K:b-vzcyfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L214)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> loool. Are you sure this is a sane identifier to expose? Perhaps we should generate some guids at session start? And perhaps the identifier should start with the "client" as a prefix.
</details>
What is the problem you think this creates?

---

*[pkg/sql/crdb_internal.go, line 273 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_Ilr5Mu42oJL8bFlY:-KW_L0cJHag2FEFY_Qmk:bsxtspz) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/sql/crdb_internal.go#L273)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> i think you should be looking at `TxnState.State != NoTxn`
</details>
And then what? Skip generating the other columns, or fill them with NULL, if the state is NoTxn? (suggestions welcome)

---

*[pkg/ui/config.js, line 1156 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317#-KW_JJFeUG7kz9tE6C8s:-KW_LBEJpMhnkR4gtfvf:bk65iyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/381294a7c5ce2c3ba91c1b56a6ce1580c287c79e/pkg/ui/config.js#L1156)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> what's up with this file?
</details>
That's a weekend npm mess leftover, will clean with rebase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10317)*

**Comment by knz** [comment]
Uh I think there's still some stuff in this PR that deserves to be worked on.

**Comment by mjibson** [comment]
Oops. Yes. Do you mean problems with the stuff I merged or additional features that are here but not in the other PR?

**Comment by knz** [comment]
just the additional features.

**Comment by knz** [comment]
Most of this PR made it to master already, and the remaining bits will be replaced by the outcome of #15761.

**Pull request closed without merging**
