### PR TITLE
logmetrics: add metrics for fluent write error, attempts

### LINKED ISSUE #116694: Improve observability around fluent logging sinks
**Is your feature request related to a problem? Please describe.**

Although we're adding the log.fluent.sink.conn.errors metric in 23.2 to track fluent sink connection errors, there are a few pieces of information that would also be useful for monitoring the flow of logs from crdb. Specifically, it would be helpful to track write errors in addition to connection errors (since we've seen log lines indicating write errors but not connection errors), and to track attempts as well as errors, so that we can calculate error rates.

**Describe the solution you'd like**

Add a new metric for fluent sink write errors, as well as metrics for connect and write attempts.

**Describe alternatives you've considered**

In theory users could alert on log lines that indicate errors sending logs to the fluent sink, but obviously this could be tricky if logs aren't flowing to the system that would alert on them!

**Additional context**

This looks like it would be pretty straightforward to implement, so I'm going to send in a tiny patch for discussion.

Jira issue: CRDB-34726

### PR DESCRIPTION
**Pull request by jmcarp**
Previously, we emitted a metric to count fluent sink connection errors in the logmetrics package. However, we didn't have a metric to count write errors, and we didn't have metrics to count connection/write attempts. This metrics would let users write better alerts. Specifically, users would be able to alert on write errors as well as connection errors. And users would be able to alert on error rates rather than error counts. This patch adds new metrics to track fluent sink connection attempts, and fluent sink write attempts and errors.

Fixes #116694.

### CODE REVIEW

**Review by sudomateo — CHANGES_REQUESTED** [review]
Nice work on this. The new metrics look good to me. Would you be able to update/add tests for this change? I believe they are in `pkg/util/log/logmetrics/metrics_test.go`.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116699#-:-NlyW3sx8oJtdfsTCL_k:bx8kv98)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @jmcarp)

___
*[`pkg/util/log/metric.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116699#-NlyVD3R6r0WXEtfS6w3:-NlyVD3R6r0WXEtfS6w4:bmxoh8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/655cb78764fc866b1c77373739feaa4eb19a75b6/pkg/util/log/metric.go#L48)):*
> ```Go
> 	FluentSinkConnectionError   Metric = iota
> 	FluentSinkWriteAttempt      Metric = iota
> 	FluentSinkWriteError        Metric = iota
> ```

Since all of these constants are the same type whose value is determined by `iota`, you can omit the `Metric = iota` lines on all but the first line. It's generally considered good Go style to do so, and it's how the code was styled before your change.



_Suggestion:_
```Go
	FluentSinkConnectionAttempt Metric = iota
	FluentSinkConnectionError
	FluentSinkWriteAttempt
	FluentSinkWriteError
```

**Review by abarganier — APPROVED** [review]
Looks good given the fixes made in response to @sudomateo's feedback (thanks for taking a look Matthew!)

:lgtm: - thanks for adding! I hope the dependency injection metrics thing I created here wasn't too hard to make sense of!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116699#-:-NmgeGd57rboYB6OGJvZ:b-nuxd6a)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jmcarp and @sudomateo)

**Review by abarganier — COMMENTED** [review]
FYI, for your CI failure, I think you just need to rebase.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116699#-:-NmgeWbV9wDhVypO7s4Z:b2ijaza)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jmcarp and @sudomateo)

**Review by sudomateo — APPROVED** [review]
Thank you for working on this! Looks good!

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116699#-:-NnF79rf3TbchefjJCXV:ba42864)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jmcarp)

**Pull request merged**
