### PR TITLE
kvserver: acquire and switch leases during Raft ticks

### LINKED ISSUE #98433: kvserver: lease maintenance scheduler
We need a scheduler that eagerly maintains range leases. This should:

* Acquire leases for ranges that don't have one.
* Extend expiration-based leases before they expire.
* Switch the lease type when appropriate (see #93903).

There are two motivations for this

1. We don't want lease acquisition to be lazily driven by client requests.
    1. It can prevent ranges from ever acquiring a lease under certain failure modes, e.g. because the client request times out before the lease acquisition succeeds under disk stalls (see #81100 and #80713).
    2. It adds unnecessary latency, e.g. in the case where a scan across many ranges has to sequentially acquire leases for each range, especially under failure modes such as network outages or disk stalls where the lease acquisition has to wait for network timeouts.

3. When only using expiration leases, we want to ensure ranges have a lease even when there is no traffic on the ranges, to avoid lease acquisition latencies on the next request to the range.

A few important aspects to consider:

* Some ranges are more important that others. In particular, the meta and liveness range leases must get priority.
* Expiration lease extensions are currently expensive (one Raft write per extension per range). We may want to allow very cold ranges to let their leases expire after some period of inactivity (e.g. minutes).
* There may not be any point in quiescing ranges where we eagerly extend expiration leases (see #94592 and #94454).
* We already have other scheduler infrastructure that we could piggyback on: the Raft scheduler, and the queue infrastructure (e.g. a new lease queue).
* We should try to honour lease preferences.

We have a few similar mechanisms already, that should be mostly be replaced by this scheduler:

* The replicate queue acquires leases for ranges that doesn't have one.

    https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/kv/kvserver/replicate_queue.go#L989-L996

* `Store.startLeaseRenewer()` eagerly renews the expiration leases on the meta and liveness ranges to avoid high tail latencies.

    https://github.com/cockroachdb/cockroach/blob/8add7c5447ce49df3c00cd68f87aba9f48d2c515/pkg/kv/kvserver/store.go#L2089-L2098

* `Replica.maybeExtendLeaseAsyncLocked()` will extend an expiration lease when processing a request in the last half of the lease interval.

    https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/kv/kvserver/replica_range_lease.go#L1437-L1454

Jira issue: CRDB-25265

Epic CRDB-25207

### LINKED ISSUE #100426: kvserver: limit concurrent lease requests
When #98433 lands, we should consider limiting the number of concurrent lease requests in flight, since we'll be extending 1/6 of all local leases every 500 ms, probably by using a semaphore during `requestLease()`. However, prioritization can be a bit tricky here -- for example, we probably want lease acquisitions that's blocking foreground traffic to take precedence over lease extensions for mostly-idle ranges.

We can also consider having a bounded goroutine pool for lease requests, instead of spawning new goroutines for these.

Jira issue: CRDB-26429

Epic CRDB-25207

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvserver: acquire and switch leases during Raft ticks**

This patch eagerly acquires leases, and switches their type when appropriate, during Raft ticks. This avoids incurring lease acquisition latency on the next request to the range. However, it's only effective for unquiesced ranges (which includes all expiration-based ranges), so we retain the corresponding logic in the replicate queue as a fallback, taking effect within 10 minutes or so.

Resolves #98433.

Epic: none
Release note: None

**kvserver: eagerly initialize replicas with expiration leases**

By default, replicas start out quiesced and only unquiesce in response to range traffic. Since expiration-based leases should not quiesce, and should eagerly acquire leases, this patch eagerly initializes and unquiesces replicas with expiration-based leases when loaded.

Touches #98433.

Epic: none
Release note: None
  
**kvserver: limit concurrent eager lease acquisitions**

This patch limits the number of concurrent eager lease acquisitions done by the Raft scheduler to 256 per node (across all stores), configurable via `kv.lease.eager_acquisition_concurrency`. When the limit is reached, further lease acquisition requests are dropped and then retried on the next tick.

This only applies to acquisition of expired leases and switching of lease types done by the Raft scheduler, not to lease extensions nor to lease acquisitions driven by client requests. Since expiration leases need to be extended regularly there is little point in throttling them and the cluster must be provisioned to handle them, and client-driven acquisitions are clearly high priority.

A more sophisticated policy can be considered later if necessary.

Resolves #100426.

Epic: none
Release note: None

### CODE REVIEW

**Review by andrewbaptist — APPROVED** [review]
:lgtm: I had some minor comments / clarifications, but generally it all looks good. Thanks!

> Reviewed 7 of 7 files at r1, 3 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-:-NV6WLvJ3ZU3CLTyETuR:b-2ihx61)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6UhMB70ZXqfMbjvxW:-NV6UhMB70ZXqfMbjvxX:bpbw1wx) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a588b8ba3bd67c3adfbc2f187ad1bd1e08286a/pkg/kv/kvserver/replica_range_lease.go#L1422)):*
> ```Go
> 	case kvserverpb.LeaseState_EXPIRED:
> 		// Attempt to acquire an expired lease if we're the Raft leader.
> 		return r.isRaftLeaderRLocked()
> ```

Why is this check `isRaftLeaderRLocked` instead of `st.OwnerBy(r.StoreID()))` I think they would give the same result here unless the leader and leaseholder are different, but there may be a case I'm missing. I guess I'm confused how to proceed in a leader/leaseholder split, should it be the leader or the previous leaseholder that gets the lease? 
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6Taq3EK9mkenbmLf-:-NV6Taq3EK9mkenbmLf0:blnb9e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a588b8ba3bd67c3adfbc2f187ad1bd1e08286a/pkg/kv/kvserver/replica_range_lease.go#L1431)):*
> ```Go
> 		return st.OwnedBy(r.StoreID())
> 
> 	case kvserverpb.LeaseState_VALID, kvserverpb.LeaseState_UNUSABLE:
> ```

I'm a little confused about how we should handle UNUSABLE leases. Shouldn't these be treated more like EXPIRED leases since they are "about to" expire? Or is the problem that we still own it, so we can't let it go to the Raft leader? If we get to UNUSABLE with a leader/leaseholder split, we will be racing with the leader (who will try and get the lease once it thinks it's expired) and the leaseholder trying to get the lease when it is "almost expired". That's OK because only one will win, but it seems like we would want consistent behavior. Also it makes me wonder how we get out of the leader/leaseholder split at all here. 
___
*[`pkg/kv/kvserver/replicate_queue.go` line 1024 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6XDCDC16oC1ZLESh5:-NV6XDCDC16oC1ZLESh6:bxytzzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a588b8ba3bd67c3adfbc2f187ad1bd1e08286a/pkg/kv/kvserver/replicate_queue.go#L1024)):*
> ```Go
> 	// this lease transfer.
> 	//
> 	// TODO(erikgrinaker): This is also done more eagerly during Raft ticks, but
> ```

nit: Is this still a TODO?
___
*[`pkg/kv/kvserver/store.go` line 1982 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6Xckq7QiKU7hyqsNh:-NV6Xckq7QiKU7hyqsNi:b-863e1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd855652bbb30a8c1efc2fff91cb0828cfcbae8f/pkg/kv/kvserver/store.go#L1982)):*
> ```Go
> 		// NB: cluster settings haven't propagated yet, so we have to check the last
> 		// known lease instead of relying on shouldUseExpirationLeaseRLocked().
> 		if l, _ := rep.GetLease(); l.Type() == roachpb.LeaseExpiration && l.Sequence > 0 {
> ```

nit: Add a note about l.Sequence > 0. I would assume that all leases have a sequence > 0, so this should only happen for a newly created range that has never had a leaseholder. Alternatively, maybe we should just initialize all raft groups at startup and let the quiese again naturally.  I don't love the idea of checking the previous setting. Another alternative is to check if we would get an expiration lease on this range by calling `shouldUseExpirationLeaseRLocked`. That seems a little better.
___
*[`pkg/kv/kvserver/store.go` line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6ZXF80QzI1AB9Waaj:-NV6ZXF80QzI1AB9Waak:b-haknrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c4c274891e04420289374639a68a034675a02dd/pkg/kv/kvserver/store.go#L246)):*
> ```Go
> 	settings.SystemOnly,
> 	"kv.store.concurrent_eager_lease_acquisitions",
> 	"the number of concurrent, eager lease acquisitions to make (0 disables eager acquisition)",
> ```

nit: What are the implications of setting this to 0. It seems better to not allow that as a user will do it by accident. I think the replicate_queue will still take care of this, but I'm not sure we would want anyone to do this.

**Review by erikgrinaker — COMMENTED** [review]
TFTR!

I'm still a bit unsure about the `PROSCRIBED` policy here -- it makes sense after a restart, but I want to doublecheck that it won't be problematic after revoking our lease during a transfer. I think in that case we'll already see the new lease and not hit the `PROSCRIBED` path, and if we don't then the lease request's compare-and-swap will fail anyway.

I also just want to run some quick perf checks of Raft ticks to make sure the costs aren't increasing too much.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-:-NV6g0tWCjGWvdvz6fek:b-dg7418)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6UhMB70ZXqfMbjvxW:-NV6aUVr1LvSTNVTGoF2:b-6pwtx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a588b8ba3bd67c3adfbc2f187ad1bd1e08286a/pkg/kv/kvserver/replica_range_lease.go#L1422)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Why is this check `isRaftLeaderRLocked` instead of `st.OwnerBy(r.StoreID()))` I think they would give the same result here unless the leader and leaseholder are different, but there may be a case I'm missing. I guess I'm confused how to proceed in a leader/leaseholder split, should it be the leader or the previous leaseholder that gets the lease? 
</blockquote></details>

The common case here is when the old leaseholder died. In that case, `st.OwnerBy(r.StoreID())` would mean that noone tries to acquire the lease, which is the opposite of what we want.

The reason we check the Raft leadership is because we also check below Raft that only the Raft leader can acquire the lease, to keep them colocated. Returning `true` for non-leaders is pointless here, because the lease request is guaranteed to fail below Raft. This also reduces the aggregate cost of these acquisition attempts by 2/3 since only 1/3 replicas will attempt it.

https://github.com/cockroachdb/cockroach/blob/a9989a85485c1796fd11907ae2cc019c962c1818/pkg/kv/kvserver/replica_proposal_buf.go#L615-L628
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6Taq3EK9mkenbmLf-:-NV6axhT3YhWtAYqWhNf:b-8ohdy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a588b8ba3bd67c3adfbc2f187ad1bd1e08286a/pkg/kv/kvserver/replica_range_lease.go#L1431)):*
Only the leaseholder can request the lease during `UNUSABLE`, since it's in the stasis period of the current lease. We still own the lease, but we can't use it to serve read requests since it may overlap with a different leaseholder in real time (not logical time) due to clock skew. However, we know that the lease is about to expire, so we'd still like to try to extend it if we can instead of letting it expire and incurring lease acquisition latency for the next requests to the range.

>it makes me wonder how we get out of the leader/leaseholder split at all here

In general, leader/leaseholder splits are handled by the leader actively transferring leadership to the leaseholder:

https://github.com/cockroachdb/cockroach/blob/a9989a85485c1796fd11907ae2cc019c962c1818/pkg/kv/kvserver/replica_raft.go#L1216

But once the lease expires, we try to acquire it on the current leader.
___
*[`pkg/kv/kvserver/replicate_queue.go` line 1024 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6XDCDC16oC1ZLESh5:-NV6bx7G7Eol4ztB3ZAk:b-crzp9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a588b8ba3bd67c3adfbc2f187ad1bd1e08286a/pkg/kv/kvserver/replicate_queue.go#L1024)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Is this still a TODO?
</blockquote></details>

Yes, we still quiesce ranges with epoch leases, so we need the replicate queue to do this for ranges that use them (since they aren't ticked and therefore can't rely on the Raft scheduler to do this). Maybe in the future we can get rid of quiescence entirely for epoch leases too, but not yet.
___
*[`pkg/kv/kvserver/store.go` line 1982 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6Xckq7QiKU7hyqsNh:-NV6dlN71roy_D0bacx5:brmfaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd855652bbb30a8c1efc2fff91cb0828cfcbae8f/pkg/kv/kvserver/store.go#L1982)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Add a note about l.Sequence > 0. I would assume that all leases have a sequence > 0, so this should only happen for a newly created range that has never had a leaseholder. Alternatively, maybe we should just initialize all raft groups at startup and let the quiese again naturally.  I don't love the idea of checking the previous setting. Another alternative is to check if we would get an expiration lease on this range by calling `shouldUseExpirationLeaseRLocked`. That seems a little better.
</blockquote></details>

Yeah, the sequence check and only doing this for expiration leases is just to be conservative and avoid any unwanted regressions in the default case where we use epoch leases. I'll add a comment. I'd love to remove this and always initialize, but I think we should be conservative here until we get some more runtime with this in actual production environments.

As the comment points out, `shouldUseExpirationLeaseRLocked` doesn't work here -- it will always return `false` because cluster settings haven't propagated yet. The best we can do is to look at the last lease we know about, which in the worst case would give a false result if someone flipped the setting while the node was offline, and that doesn't seem terrible.
___
*[`pkg/kv/kvserver/store.go` line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6ZXF80QzI1AB9Waaj:-NV6c7UT6OwcFojJBTcQ:b298gre) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c4c274891e04420289374639a68a034675a02dd/pkg/kv/kvserver/store.go#L246)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: What are the implications of setting this to 0. It seems better to not allow that as a user will do it by accident. I think the replicate_queue will still take care of this, but I'm not sure we would want anyone to do this.
</blockquote></details>

Oops, that description doesn't match reality. The actual implementation will disable the limit (i.e. infinity) when set to 0. I'm honestly not sure which behavior makes more sense. Maybe we'd want a way to disable this if it causes problems, so 0 is a useful escape hatch? I mean, setting it to 1 would be equally bad, and if someone did want infinity they can just use 1e6 or something.

**Review by erikgrinaker — COMMENTED** [review]
Thanks again for the review! I've updated the PR, I'll give you a chance to respond to any of the comments or changes before borsing this.

>I'm still a bit unsure about the `PROSCRIBED` policy here

We already do the same thing in `redirectOnOrAcquireLease()`, which will be called on every request processed by this replica in `PROSCRIBED` state, so this seems fine.

>I also just want to run some quick perf checks of Raft ticks

Didn't see a significant effect. We'll do some more micro-optimization of Raft ticks later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-:-NV9ZbfF1LWh4gDSdv4_:bmo8zs4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvserver/store.go` line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101098#-NV6ZXF80QzI1AB9Waaj:-NV9YDV4AjrTO_Y0tEIf:b-mirtai) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c4c274891e04420289374639a68a034675a02dd/pkg/kv/kvserver/store.go#L246)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Oops, that description doesn't match reality. The actual implementation will disable the limit (i.e. infinity) when set to 0. I'm honestly not sure which behavior makes more sense. Maybe we'd want a way to disable this if it causes problems, so 0 is a useful escape hatch? I mean, setting it to 1 would be equally bad, and if someone did want infinity they can just use 1e6 or something.
</blockquote></details>

I made this disable eager lease acquisition, it seems handy to have the ability if something goes wrong.

I also made the limit per-node rather than per-store, and renamed it to `kv.lease.eager_acquisition_concurrency` in the possibly naïve hope that we can move all lease-related settings under `kv.lease`.

**Comment by erikgrinaker** [comment]
Going to bors this to run some tests/benchmarks. TFTR!

bors r+

**Pull request merged**
