### PR TITLE
sql: skip uniqueness check during backfill for ALTER LOCALITY REGIONAL BY ROW

### PR DESCRIPTION
**Pull request by otan**
Refs: #63619

Release note (sql change): When using ALTER TABLE ... LOCALITY REGIONAL
BY ROW, we would previously verify uniqueness of the new table which was
an unnecessary operation. This is now removed, giving improved
performance when updating localities to or from REGIONAL BY ROW.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: although I'm not familiar with the mutation logic below. Might be good to get an extra review from someone on SQL experience.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63714#-:-MYL1uX2Ar7YtKZyO66v:b-wg4s5r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/backfill.go, line 1650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63714#-MYL2du-21l7HIVwzl7t:-MYL2du-21l7HIVwzl7u:b-4ju6mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/19dbc169ec2280324b757a6d67055131a337431d/pkg/sql/backfill.go#L1650)):*
> ```Go
> // rollback. However, if gatherAllInvalid is true, it instead accumulates all
> // the indexes which fail and returns them together.
> func ValidateForwardIndexes(
> ```

while you're here, would be great to explain what the `withFirstMutationPublic` param means

**Review by otan — COMMENTED** [review]
added @arulajmani to double check

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63714#-:-MYMGimyBrVJ2DfZrXx4:b-ua38fb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @rytaft)

___
*[pkg/sql/backfill.go, line 1650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63714#-MYL2du-21l7HIVwzl7t:-MYMGhsF9hjBk9wuDQ8d:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/19dbc169ec2280324b757a6d67055131a337431d/pkg/sql/backfill.go#L1650)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

while you're here, would be great to explain what the `withFirstMutationPublic` param means
</blockquote></details>

done

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63714)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

___
*[pkg/sql/backfill.go, line 1687 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63714#-MYQp_uTDC26Tc2ABtQm:-MYQp_uTDC26Tc2ABtQn:b6py2ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e09ad418a811f104020f8a07738f5fc2229635/pkg/sql/backfill.go#L1687)):*
> ```Go
> 				mutations := tableDesc.AllMutations()
> 				if len(mutations) > 0 {
> 					mutationID := mutations[0].MutationID()
> ```

IIUC, we shouldn't need this loop right, because if we're doing an ALTER PK Swap then we are guaranteed that there's only one mutation with that `mutationID`? Let's simplify this?

**Comment by otan** [comment]
Not true. Add column and alter ok can be in the same txn.

**Review by arulajmani — APPROVED** [review]
Ah right, the column we add underneath the hood can end up here I guess. Okay, :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63714#-:-MYRUiYR9p2bRISlMw0K:b-8v8k2h)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @rytaft)

**Comment by otan** [comment]
bors r=rytaft,arulajmani

**Pull request merged**
