### PR TITLE
sql: stop duplicating primary region on database descriptor

### PR DESCRIPTION
**Pull request by arulajmani**
Currently, we store the primary region on both the database descriptor
and type descriptor. There's no real need for this and we should
converge to a single source of truth -- the region config on the type
descriptor.

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
Just the first commit from https://github.com/cockroachdb/cockroach/pull/62727

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @dt)

___
*[pkg/sql/create_type.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62978#-MXDuat2-9rRO6LjywH9:-MXDuat2-9rRO6LjywHA:b-hkfo0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb8634db0f93a6fb41ff696702277afe82532d1/pkg/sql/create_type.go#L280)):*
> ```Go
> 	}
> 	return params.p.createEnumWithID(
> 		params, id, n.n.EnumLabels, n.dbDesc, n.typeName, nil, /* regionConfig*/
> ```

Nit: space :stuck_out_tongue: 
___
*[pkg/sql/catalog/descpb/structured.proto, line 1229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62978#-MXDv3mOA8xQvPW7UCvJ:-MXDv3mOA8xQvPW7UCvK:b2k9gnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb8634db0f93a6fb41ff696702277afe82532d1/pkg/sql/catalog/descpb/structured.proto#L1229)):*
> ```protobuf
>     reserved 1;
>     optional SurvivalGoal survival_goal = 2 [(gogoproto.nullable)=false];
>     reserved 3;
> ```

How is this going to work for migrating databases from earlier betas?  The primary region is going to be set here, and not in the enum.  Will that cause validation to fail?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @dt)

___
*[pkg/sql/create_type.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62978#-MXDuat2-9rRO6LjywH9:-MXERLai56ja98JWyw8g:bd5ty59) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb8634db0f93a6fb41ff696702277afe82532d1/pkg/sql/create_type.go#L280)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: space :stuck_out_tongue: 
</blockquote></details>

:eyes: 
___
*[pkg/sql/catalog/descpb/structured.proto, line 1229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62978#-MXDv3mOA8xQvPW7UCvJ:-MXEQyYP87ZkSNHt1350:b-8xwv2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb8634db0f93a6fb41ff696702277afe82532d1/pkg/sql/catalog/descpb/structured.proto#L1229)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

How is this going to work for migrating databases from earlier betas?  The primary region is going to be set here, and not in the enum.  Will that cause validation to fail?
</blockquote></details>

The primary region was set on the enum previously, so we should be fine. There was validation code to make sure that the primary region value was in sync on both the descriptors, but this patch removes that logic -- I think it should be fine. Databases created in the beta will have this proto field set on them, but considering it is set as "reserved" here it shouldn't cause a problem going forward.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @dt)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62978#-MXDv3mOA8xQvPW7UCvJ:-MXERw7PB6waN_a9iqL3:b537z1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb8634db0f93a6fb41ff696702277afe82532d1/pkg/sql/catalog/descpb/structured.proto#L1229)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

The primary region was set on the enum previously, so we should be fine. There was validation code to make sure that the primary region value was in sync on both the descriptors, but this patch removes that logic -- I think it should be fine. Databases created in the beta will have this proto field set on them, but considering it is set as "reserved" here it shouldn't cause a problem going forward. 
</blockquote></details>

Any chance you can quickly test this, if you haven't already?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @dt)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62978#-MXDv3mOA8xQvPW7UCvJ:-MXJF6eJ8HXXxo0ol-8T:b-zd2fpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb8634db0f93a6fb41ff696702277afe82532d1/pkg/sql/catalog/descpb/structured.proto#L1229)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Any chance you can quickly test this, if you haven't already?
</blockquote></details>

Tested it out. Things _mostly_ work, but the mixed version setting _may_ be slightly problematic in the following scenario:
```
- Create a multi-region database in beta.2
- Upgrade one of the nodes so that it has this commit. Alter the database on this node so that a new descriptor entry is written.
- Connect to a beta.2 node and try running `SHOW DATABASES`, this will fail validation.
```
It's worth noting that once the beta.2 node is upgraded to have this commit, things start working as expected.

**Review by ajstorm — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @dt)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62978#-MXDv3mOA8xQvPW7UCvJ:-MXWywckD3sIWJjRNlDP:b6zo127) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb8634db0f93a6fb41ff696702277afe82532d1/pkg/sql/catalog/descpb/structured.proto#L1229)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Tested it out. Things _mostly_ work, but the mixed version setting _may_ be slightly problematic in the following scenario:
```
- Create a multi-region database in beta.2
- Upgrade one of the nodes so that it has this commit. Alter the database on this node so that a new descriptor entry is written.
- Connect to a beta.2 node and try running `SHOW DATABASES`, this will fail validation.
```
It's worth noting that once the beta.2 node is upgraded to have this commit, things start working as expected. 
</blockquote></details>

What happens in the interim?  Will the beta.2 node fail?  Will the `SHOW DATABASES` command fail?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @dt)

___
*[pkg/sql/catalog/descpb/structured.proto, line 1229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62978#-MXDv3mOA8xQvPW7UCvJ:-MXXHNHs3l1UOifKktea:b-goe12m) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb8634db0f93a6fb41ff696702277afe82532d1/pkg/sql/catalog/descpb/structured.proto#L1229)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

What happens in the interim?  Will the beta.2 node fail?  Will the `SHOW DATABASES` command fail?
</blockquote></details>

The beta.2 node will not fail. Queries on/involving the multi-region database which are executed with the beta.2 node being the gateway node will fail however. They'll start working again once the node is upgraded. 

I'd initially hoped we could side step this problem by doing it in two steps. As a strawman, we could remove this validation in the intermediate version and de-duplicate in the version after. I don't think that'll work though, as I think we allow users to jump minor versions. I think we might have to shelve this :(

**Pull request closed without merging**
