### PR TITLE
kvstreamer: add limit to how many eager batches are issued

### LINKED ISSUE #113729: streamer: investigate occasional suboptimal behavior in InOrder mode
Consider the following setup:
```sql
CREATE TABLE t (
	k INT PRIMARY KEY,
	v STRING,
	blob STRING,
	INDEX t_v_idx (v ASC)
);

INSERT INTO t SELECT 3000 * (i // 1000) + i % 1000, '1', repeat('a', 600 + i % 200) FROM generate_series(1, 10000) AS g(i);
INSERT INTO t SELECT 3000 * (i // 1000) + i % 1000 + 1000, '1', repeat('a', 3000 + i % 1000) FROM generate_series(1, 10000) AS g(i);
INSERT INTO t SELECT 3000 * (i // 1000) + i % 1000 + 2000, '1', repeat('a', 20000 + i) FROM generate_series(1, 10000) AS g(i);

ALTER TABLE t SPLIT AT SELECT generate_series(1, 30000, 3000);
ALTER TABLE t SCATTER;

SET streamer_always_maintain_ordering = true;

EXPLAIN ANALYZE SELECT length(blob) FROM t@t_v_idx WHERE v = '1';
```
The last query usually completes within 2s on a single node local cluster, but occasionally it can take as long as 30s:
```
                            info
------------------------------------------------------------
  planning time: 433µs
  execution time: 30s
  distribution: local
  vectorized: true
  rows decoded from KV: 60,000 (280 MiB, 1,861 gRPC calls)
  cumulative time spent in KV: 30s
  maximum memory usage: 68 MiB
  network usage: 0 B (0 messages)
  max sql temp disk usage: 49 MiB
  regions: us-east1
  sql cpu time: 311ms
  isolation level: serializable
  priority: normal
  quality of service: regular

  • render
  │
  └── • index join (streamer)
      │ nodes: n1
      │ regions: us-east1
      │ actual row count: 30,000
      │ KV time: 30s
      │ KV contention time: 0µs
      │ KV rows decoded: 30,000
      │ KV bytes read: 279 MiB
      │ KV gRPC calls: 1,860
      │ estimated max memory allocated: 68 MiB
      │ estimated max sql temp disk usage: 49 MiB
      │ sql cpu time: 305ms
      │ table: t@t_pkey
      │
      └── • scan
            nodes: n1
            regions: us-east1
            actual row count: 30,000
            KV time: 21ms
            KV contention time: 0µs
            KV rows decoded: 30,000
            KV bytes read: 966 KiB
            KV gRPC calls: 1
            estimated max memory allocated: 1020 KiB
            sql cpu time: 6ms
            missing stats
            table: t@t_v_idx
            spans: [/'1' - /'1']
(45 rows)

Time: 30.021s total (execution 30.020s / network 0.000s)
```
We need to figure it out.

Jira issue: CRDB-33123

### PR DESCRIPTION
**Pull request by yuzefovich**
**kvstreamer: add limit to how many eager batches are issued**

This commit fixes extremely suboptimal behavior of the streamer in the
InOrder mode in some cases. In particular, previously it was possible
for the buffered responses to consume most of the working budget, so the
streamer would degrade to processing all requests effectively one
BatchRequest with one Get / Scan at a time, significantly increasing the
latency. For example, the query added as a regression test that performs
30k Gets across 10 ranges would usually take on the order of 1.5s (which
is not great already since in the non-streamer path it takes 400ms), but
in the degenerate cases it could be on the order of 20-30s.

Similar behavior could occur in the OutOfOrder mode too where we would
issue more BatchRequests in which only one request could be satisfied
(although in OutOfOrder mode the problem is not as severe - we don't
buffer any results since we can always return them right away).

This problem is now fixed by imposing the limit on the budget's usage at
which point the streamer stops issuing "eager" requests. Namely, now,
when there is at least one request in flight, the streamer won't issue
anymore requests once `limit * eagerFraction` is exceeded. This
effectively reserves a portion of the budget for the "head-of-the-line"
batch.

The "eager fraction" is controlled by a session variable, separate for
each mode. The defaults of 0.5 for InOrder and 0.8 for OutOfOrder modes
were chosen after running TPCH queries and the query that inspired this
commit. These values bring the number of gRPC calls for the reproduction
query from 1.5k-2k range to below 200 and the query latency to be
reliably around 400ms.

I don't really see any significant downsides to this change - in the
worst case, we'd be utilizing less of the available memory budget which
is not that big of a deal, so I intend to backport this change. Also,
setting the eager fractions to large values (greater than 1.0 is
allowed) would disable this limiting behavior and revert to the previous
behavior if we need it.

Fixes: #113729.

Release note (bug fix): Previously, when executing queries with
index / lookup joins when the ordering needs to be maintained,
CockroachDB in some cases could get into a pathological behavior
which would lead to increased query latency, possibly by 1 or 2 orders
of magnitude. This bug was introduced in 22.2 and is now fixed.

**kvstreamer: increase default avg response multiple**

This commit increases the default value for
`sql.distsql.streamer.avg_response_size_multiple` cluster setting from
1.5 to 3.0. This setting controls the factor by which the current "avg
response size" estimate is multiplied and allows for TargetBytes
parameter to grow over time. In the reproduction query from the
previous commit it was determined that the growth might not be as quick
as desirable.

The effect of this change is as follows:
- if we have responses of varying sizes, then we're now likely to be more
effective since we'll end up issuing less BatchRequests
- if we have responses of similar sizes, then we might pre-reserve too
much budget upfront, so we'll end up with lower concurrency across
ranges.

Thus, we don't want to increase the multiple by too much; however,
keeping it at 1.5 can be quite suboptimal in some cases - 3.0 seems like
a decent middle ground. This number was chosen based on running TPCH
queries (both via InOrder and OutOfOrder modes of the streamer) and the
reproduction query. (For the latter this change reduces the number of
gRPC calls by a factor of 3 or so.)

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
This :lgtm:.

> Reviewed 13 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113809#-:-Nifwt_hDWYu8Tgr1QZa:b-4te7cr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113809#-NifsrgaAAMkpafCF-p4:-NifsrgaAAMkpafCF-p5:bybvrpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d35a9e70931e22ba15c5171dad3bc721d78e9d/pkg/kv/kvclient/kvstreamer/streamer.go#L447)):*
> ```Go
> 	}
> 	if eagerFraction == 0 {
> 		// Zero value doesn't make sense - we're probably in the testing
> ```

[nit] Why doesn't zero make sense? Wouldn't it just indicate no concurrency?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113809)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113809#-NifsrgaAAMkpafCF-p4:-NigoX4K8OXF9fdtc8JP:bswsnyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d35a9e70931e22ba15c5171dad3bc721d78e9d/pkg/kv/kvclient/kvstreamer/streamer.go#L447)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Why doesn't zero make sense? Wouldn't it just indicate no concurrency?
</blockquote></details>

Yeah, good point. I was thinking mostly that in production we wouldn't want to set it to zero, so I assumed it must be coming from tests, but setting it to zero might be useful for debugging (or testing / metamorphic purposes), so it makes sense to allow it. I made minor tweaks to indicate that `nil` session data can be used in tests in which case a "reasonable" default is picked.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113809#-:-NihUVeNBt0b8kOtuBPW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113809#-NifsrgaAAMkpafCF-p4:-NihURjI-RdVz-83qfzI:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d35a9e70931e22ba15c5171dad3bc721d78e9d/pkg/kv/kvclient/kvstreamer/streamer.go#L447)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, good point. I was thinking mostly that in production we wouldn't want to set it to zero, so I assumed it must be coming from tests, but setting it to zero might be useful for debugging (or testing / metamorphic purposes), so it makes sense to allow it. I made minor tweaks to indicate that `nil` session data can be used in tests in which case a "reasonable" default is picked.
</blockquote></details>

Thanks!

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
