### PR TITLE
roachprod: use gcloud CLI instead of net.LookupSRV

### LINKED ISSUE #111269: roachprod: ns-cloud-a1.googledomains.com lookup failure
We observed a DNS flake on a custom run of roachtest [1].
It was unable to lookup `ns-cloud-a1.googledomains.com` the DNS server against which follow-up DNS requests would have been made.
```
lookup _system-sql._tcp.teamcity-11905017-1695525840-95-n9cpu4-geo.roachprod-managed.crdb.io on 169.254.169.254:53: dial tcp: lookup ns-cloud-a1.googledomains.com: i/o timeout
```

[1] https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11905017

Jira issue: CRDB-31847

### PR DESCRIPTION
**Pull request by herkolategan**
Previously `net.LookupSRV` with a custom resolver was used to lookup DNS
records. This approach resulted in several flakes and required waiting on DNS
servers to have the records available. The CLI is more stable, but has a greater
call overhead.

This PR also introduces a cache to reduce the cost of the `LookupSRVRecords`
call which could be called frequently depending on the origin of use. The cache
is updated for any CRUD operations on the DNS entries, and a call to the CLI
will not occur if any entry exists for the name the lookup is attempting. The
names are also normalised to remove a trailing dot in order to make matching
against the cache work correctly.

There is a small risk that the cache could go out of sync if any other roachprod
process manipulates the records with a create, update or destroy operation,
while a continuous roachprod process is interacting with the entries. This risk
is relatively small and usually applies to roachtest rather than everyday use of
roachprod.

Fixes #111269

Epic: None
Release Note: None

### CODE REVIEW

**Review by herkolategan — COMMENTED** [review]
TC Run (0.3 prob): https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12555726

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113934#-:-NijXeQN3TZ90i6r7Ich:bbopp32)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by herkolategan — COMMENTED** [review]
Ran all `seed-multi-region` tests as well as these are the ones always present on the DNS failures: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12675094?buildTab=tests

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113934#-:-NjDouEj83KJub7HRJyt:b-ijsoc4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @renatolabs, and @srosenberg)

**Review by renatolabs — APPROVED** [review]
:lgtm: Nice!

A couple of questions and a suggestion about use of mutex. Excited to finally fix that roachtest! :laughing: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113934#-:-NjOlU8T-B0T1U2NrpK6:b9qmws1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @srosenberg)

___
*[`pkg/roachprod/vm/gce/dns.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113934#-NjOjD_x4i7lsmA7EuLY:-NjOjD_x4i7lsmA7EuLZ:b-ei0y6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f06db1132f295248cc080434ca17be799da45fa9/pkg/roachprod/vm/gce/dns.go#L171)):*
> ```Go
> 	target := name
> 	if service != "" || proto != "" {
> 		target = "_" + service + "._" + proto + "." + name
> ```

Not immediately obvious to me what this is doing, especially the predicate above.
___
*[`pkg/roachprod/vm/gce/dns.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113934#-NjOl45-E0muK0CfKGKp:-NjOl45-E0muK0CfKGKq:b581wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7224aff239010f3718e485c292cfd21cf9f9e20/pkg/roachprod/vm/gce/dns.go#L43)):*
> ```Go
> type dnsProvider struct {
> 	recordsCache struct {
> 		mu      syncutil.RWMutex
> ```

I think we should make our lives easier and just use a regular `Mutex`. `RWMutex`'s performance gains are questionable [1], and we are just opening the door for a class of bugs that doesn't exist with `Mutex`. Also, this is not going to be ultra performance sensitive anyway.

[1] https://cockroachlabs.slack.com/archives/C4X2J0RH6/p1693183691487509?thread_ts=1692899413.532049&cid=C4X2J0RH6
___
*[`pkg/roachprod/vm/gce/dns.go` line 277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113934#-NjOkEz34_wDbA19ArRL:-NjOkEz34_wDbA19ArRM:b-5uwicl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7224aff239010f3718e485c292cfd21cf9f9e20/pkg/roachprod/vm/gce/dns.go#L277)):*
> depending on where the name originates from

Curious to understand this better.

**Comment by renatolabs** [comment]
> There is a small risk that the cache could go out of sync

Just so I understand the risk: it would have to involve two roachprod instances (command line or through roachtest) changing the same cluster at the same time, yes?

**Review by herkolategan — COMMENTED** [review]
Yes that's the primary case. The other risk is that any long running process holding onto roachprod, for instance roachtest, would be unaware of external changes to the entries due to the cache (for the same cluster). For instance, I start a long running test. Then via command line start more virtual clusters via a new roachprod process. This would result in the long running test not being aware of those new services. If that test were to in a subsequent later step try to do something similar it might fail.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113934#-:-NjRIGo1DpU6tqvPiCHE:b-czcbeu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @renatolabs, and @srosenberg)

___
*[`pkg/roachprod/vm/gce/dns.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113934#-NjOjD_x4i7lsmA7EuLY:-NjRL4VJ1_RNazcsqu-u:bdcpucn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f06db1132f295248cc080434ca17be799da45fa9/pkg/roachprod/vm/gce/dns.go#L171)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Not immediately obvious to me what this is doing, especially the predicate above.
</blockquote></details>

Originates from the go code logic to choose between name or constructing the name: https://github.com/golang/go/blob/master/src/net/lookup.go#L723
But I agree, it's convoluted and unclear. I'll clean this up a bit.
___
*[`pkg/roachprod/vm/gce/dns.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113934#-NjOl45-E0muK0CfKGKp:-NjRI3WoC4iECoVaKMK6:b-x0qd1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7224aff239010f3718e485c292cfd21cf9f9e20/pkg/roachprod/vm/gce/dns.go#L43)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I think we should make our lives easier and just use a regular `Mutex`. `RWMutex`'s performance gains are questionable [1], and we are just opening the door for a class of bugs that doesn't exist with `Mutex`. Also, this is not going to be ultra performance sensitive anyway.

[1] https://cockroachlabs.slack.com/archives/C4X2J0RH6/p1693183691487509?thread_ts=1692899413.532049&cid=C4X2J0RH6
</blockquote></details>

Fair enough, I'll change to a regular mutex.
___
*[`pkg/roachprod/vm/gce/dns.go` line 277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113934#-NjOkEz34_wDbA19ArRL:-NjRLTjE4LYdhtWJoSux:b-1dh5mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7224aff239010f3718e485c292cfd21cf9f9e20/pkg/roachprod/vm/gce/dns.go#L277)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

> depending on where the name originates from

Curious to understand this better.
</blockquote></details>

`gcloud` cli and lookups will allow passing a FQDN with or without a trailing dot (https://en.wikipedia.org/wiki/Fully_qualified_domain_name). This allows you to create an entry without a trailing dot, but get one back if you query the same record. `dig` also allows you to pass this optionally. It's possible to enforce the convention here, or just handle both cases.

My wording on the comment could be improved to rather mention `gcloud` will always return the domain name ending with a dot, but you can optionally specify it during creation, updates, or lookups.

**Pull request merged**
