### PR TITLE
sql: refactor code shared by diagnostics and EXPLAIN ANALYZE (DEBUG)

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: pass recording to WithStatementTrace

Pass the recording instead of the span.

Release note: None

#### sql: refactor code shared by diagnostics and EXPLAIN ANALYZE (DEBUG)

There are two paths that result in a bundle being collected and inserted
into the diagnostics tables. Each path uses its own code to insert the
diagnostics bundle, which leads to unnecessary complication.

This change simplifies the stmtdiagnostics code to let the caller do
the insertion and streamlines the higher level code.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56262#-:-MLK69-I27Vhu_XmommC:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

**Comment by RaduBerinde** [comment]
Looks like a couple of flaky tests.

bors r+

**Comment by RaduBerinde** [comment]
Hit #56283 

bors r+

**Pull request merged**
