### PR TITLE
build: allow building with go1.10

### PR DESCRIPTION
**Pull request by xudongzheng**
Issue #22825

### CODE REVIEW

**Comment by benesch** [comment]
Thanks for the PR, @xudongzheng! Don't see any reason we shouldn't merge this, but let me double-check with our release team real quick.

/cc @cockroachdb/release

**Comment by mberhault** [comment]
We're still heavily cherry-picking for 2.0, any discrepancy requiring switching tool chain versions (such as [small tweaks in gofmt](https://golang.org/doc/go1.10#gofmt)) will be a horrible pain.

I'd say let's hold off for a bit, both to simplify our lives, and to give 1.10 time to bake (it's only 4 days old, we can probably expect a 1.10.1 within a few weeks).

**Comment by benesch** [comment]
@mberhault, this doesn’t actually change what version we use. It just
allows building the 1.1 branch with Go 1.10. (We’ve already removed the
exact matching logic on master and only enforce a minimum version of go.)

**Comment by benesch** [comment]
@xudongzheng could you update your commit message to clarify? I suggest something like this:

```
build: allow building with go1.10
```

**Comment by benesch** [comment]
Awesome, thanks, @xudongzheng!

**Pull request merged**
