### PR TITLE
storage: use RWMutex in NodeLiveness

### PR DESCRIPTION
**Pull request by ajwerner**
When at Mutex profiles for heavily loaded TPC-C clusters we noticed that a lot
of time was being spent blocked on a RWMutex held by Replica.leaseGoodToGo which
underneath was reading NodeLiveness state in a read-only way. This PR adds a
RWMutex to NodeLiveness to eliminate contention. Prior to this change we
observed nearly 60% of lock contention on leaseGoodToGo. After we observe
closer to 20%.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
Before: 
Screenshot_2019-03-28 cockroach delay(1)

After:
Screenshot_2019-03-28 cockroach delay

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/node_liveness.go, line 598 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36316#-Lb9mKu62YGt7-vI1GJc:-Lb9mKu7-QO_nFRS5Wl9:bkg072b) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd7c16970746ce620144cc523470cbb95743c57/pkg/storage/node_liveness.go#L598)):*
> ```Go
> // a former liveness update on restart.
> func (nl *NodeLiveness) Self() (*storagepb.Liveness, error) {
> 	nl.mu.Lock()
> ```

Read lock here as well?
___
*[pkg/storage/node_liveness.go, line 619 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36316#-Lb9n9e52Z6LpiYt8pVX:-Lb9n9e52Z6LpiYt8pVY:b-h2aiqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd7c16970746ce620144cc523470cbb95743c57/pkg/storage/node_liveness.go#L619)):*
> ```Go
> 	nl.mu.RLock()
> 	defer nl.mu.RUnlock()
> 	lMap := IsLiveMap{}
> ```

Let's pull this allocation out of the lock.
___
*[pkg/storage/node_liveness.go, line 845 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36316#-Lb9miaiCZcQTIBWZq3s:-Lb9miaiCZcQTIBWZq3t:b-n4fv75) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd7c16970746ce620144cc523470cbb95743c57/pkg/storage/node_liveness.go#L845)):*
> ```Go
> 	}
> 
> 	nl.mu.Lock()
> ```

Read lock?
___
*[pkg/storage/node_liveness.go, line 857 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36316#-Lb9oGZmEo-IiJ1cqfaE:-Lb9oGZmEo-IiJ1cqfaF:b-lxzyay) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd7c16970746ce620144cc523470cbb95743c57/pkg/storage/node_liveness.go#L857)):*
> ```Go
> // registered callbacks if the node became live in the process.
> func (nl *NodeLiveness) maybeUpdate(new storagepb.Liveness) {
> 	nl.mu.Lock()
> ```

While we're here, I wonder if we should improve this. There are a few easy wins. For starters, if `shouldReplaceLiveness` is `false` some non-negligible percent of time (I'm not sure about this) then it's probably worth initially grabbing a read-lock and only upgrading to a write-lock if necessary. Doing this would also give us the ability to optimistically allocate the `callbacks` slice outside of the lock.
___
*[pkg/storage/node_liveness.go, line 935 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36316#-Lb9n-BJAy1mZykHTonl:-Lb9n-BJAy1mZykHTonm:b-n4fv75) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd7c16970746ce620144cc523470cbb95743c57/pkg/storage/node_liveness.go#L935)):*
> ```Go
> 	maxOffset := nl.clock.MaxOffset()
> 
> 	nl.mu.Lock()
> ```

Read lock?

**Review by ajwerner — COMMENTED** [review]
Updated, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36316#-:-LbTCaJC5xyEoq0k0SHR:b-rr168b)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — COMMENTED** [review]
:lgtm: mod the question about whether the optimistic read-locking in `maybeUpdate` could be a pessimization.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36316#-:-LbUO7fR4kPCFow6BcbD:b-ag87n8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/node_liveness.go, line 866 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36316#-LbUNU53CFGaqNcyEgq-:-LbUNU53CFGaqNcyEgq0:b-smhzi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4e9c9c9732be53bc5d9802790c171ea11c5f8bc/pkg/storage/node_liveness.go#L866)):*
> ```Go
> 	// Note that this works fine even if `old` is empty.
> 	should := shouldReplaceLiveness(old, new)
> 	if !should {
> ```

Nice! Any idea how frequently we hit this path? Running a roachtest manually with a bit of instrumentation would be enough to get some feel for this.
___
*[pkg/storage/node_liveness.go, line 872 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36316#-LbUO-mB9fQJ0U_WZGj1:-LbUO-mB9fQJ0U_WZGj2:b8vnbsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4e9c9c9732be53bc5d9802790c171ea11c5f8bc/pkg/storage/node_liveness.go#L872)):*
> ```Go
> 	callbacks := make([]IsLiveCallback, 0, numCallbacks)
> 	nl.mu.Lock()
> 	old = nl.mu.nodes[new.NodeID]
> ```

Drop a comment above this that we check `shouldReplaceLiveness` again now that we're under and exclusive lock.

**Comment by ajwerner** [comment]
> Nice! Any idea how frequently we hit this path? Running a roachtest manually with a bit of instrumentation would be enough to get some feel for this.

It does indeed seem to be a pessimization. We seem to hit the fast path roughly 1/3rd of the time on a 3 node cluster and 1/9th of the time on a 9 node cluster (pattern?) 

I'll rip it out

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36316#-:-LbVGAXuBwjva0DPBjto:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Pull request merged**
