### PR TITLE
ui: display closedts info on range report page

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

Looks like:

Screenshot from 2021-03-23 18-59-39

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62502)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dhartunian)

___
*[pkg/kv/kvserver/kvserverpb/state.proto, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-MWb4QyyEC6rGi6dD-Me:-MWb4Qyz07C61ecgtkfJ:b3xroif) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee199b5f0d4371ff6c34245dd4df08423f1026c/pkg/kv/kvserver/kvserverpb/state.proto#L173)):*
> ```protobuf
> }
> 
> // RangeSidetransportInfo describes a range's closed timestamp info communicated
> ```

`RangeSideTransportInfo` to be consistent?
___
*[pkg/server/serverpb/status.proto, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-MWb4e9LBidIXICyjs-r:-MWb4e9LBidIXICyjs-s:b-k3rmty) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee199b5f0d4371ff6c34245dd4df08423f1026c/pkg/server/serverpb/status.proto#L15)):*
> ```protobuf
> option go_package = "serverpb";
> ```

accidental line?
___
*[pkg/server/serverpb/status.proto, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-MWb4kMjEA9SYNaFKZUC:-MWb4kMjEA9SYNaFKZUD:b-aoxs9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee199b5f0d4371ff6c34245dd4df08423f1026c/pkg/server/serverpb/status.proto#L222)):*
> ```protobuf
> 
> message ClosedTimestampInfo {
>   util.hlc.Timestamp sidetransport_replica_closed = 1 [(gogoproto.nullable) = false];
> ```

We don't want the `sidetransport_replica_lai` here?
___
*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 787 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-MWb53h91e_henOYRu_1:-MWb53h91e_henOYRu_2:b92ct2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee199b5f0d4371ff6c34245dd4df08423f1026c/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L787)):*
> ```XML
>           raftLeader,
>         ),
>         closedTimestampPolicy: this.createContent(
> ```

@dhartunian is going to have to take this file :smile:

**Review by dhartunian — APPROVED** [review]
:lgtm: just a small import nit

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-:-MWySvMe0TEIHVIHMJMI:bu0nnyz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/ui/src/views/reports/containers/range/print.ts, line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-MWySOfD5EAV1JxtrdV6:-MWySOfD5EAV1JxtrdV7:b-kctjy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee199b5f0d4371ff6c34245dd4df08423f1026c/pkg/ui/src/views/reports/containers/range/print.ts#L17)):*
> ```XML
> import * as protos from "src/js/protos";
> import { LongToMoment, TimestampToMoment } from "src/util/convert";
> import {getMoment} from "oss/src/redux/queryManager/saga";
> ```

Remove this import? If you need to keep it for some reason, remove the `oss/` prefix.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62502)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @nvanbenschoten)

___
*[pkg/kv/kvserver/kvserverpb/state.proto, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-MWb4QyyEC6rGi6dD-Me:-MYg0Cjd2GzJJJJPVfQn:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee199b5f0d4371ff6c34245dd4df08423f1026c/pkg/kv/kvserver/kvserverpb/state.proto#L173)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`RangeSideTransportInfo` to be consistent?
</blockquote></details>

done
___
*[pkg/server/serverpb/status.proto, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-MWb4e9LBidIXICyjs-r:-MYg0Lij0AHEHD2JzKMS:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee199b5f0d4371ff6c34245dd4df08423f1026c/pkg/server/serverpb/status.proto#L15)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

accidental line?
</blockquote></details>

removed
___
*[pkg/server/serverpb/status.proto, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-MWb4kMjEA9SYNaFKZUC:-MYg2s6O4BxZZKwsW-k0:bw3bjr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee199b5f0d4371ff6c34245dd4df08423f1026c/pkg/server/serverpb/status.proto#L222)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We don't want the `sidetransport_replica_lai` here?
</blockquote></details>

this proto was unused; leftover. Removed.
___
*[pkg/ui/src/views/reports/containers/range/print.ts, line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-MWySOfD5EAV1JxtrdV6:-MYg1c_D6SNySLYb7GVO:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee199b5f0d4371ff6c34245dd4df08423f1026c/pkg/ui/src/views/reports/containers/range/print.ts#L17)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Remove this import? If you need to keep it for some reason, remove the `oss/` prefix.
</blockquote></details>

done

**Comment by rickystewart** [comment]
CC'ing myself for a reported Bazel issue (I'll review tomorrow).

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-:-MYhLI7t81T31YUsdmXA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @rickystewart)

**Review by rickystewart — CHANGES_REQUESTED** [review]
Please apply the following diff:

```
diff --git a/pkg/kv/kvserver/kvserverpb/BUILD.bazel b/pkg/kv/kvserver/kvserverpb/BUILD.bazel
index 128e0f4fcd..8bc831eb61 100644
--- a/pkg/kv/kvserver/kvserverpb/BUILD.bazel
+++ b/pkg/kv/kvserver/kvserverpb/BUILD.bazel
@@ -46,7 +46,7 @@ go_proto_library(
     proto = ":kvserverpb_proto",
     visibility = ["//visibility:public"],
     deps = [
-        "//pkg/kv/kvserver/closedts/ctpb:ctpb_go_proto",  # keep
+        "//pkg/kv/kvserver/closedts/ctpb",  # keep
         "//pkg/kv/kvserver/liveness/livenesspb",
         "//pkg/kv/kvserver/readsummary/rspb",
         "//pkg/roachpb",
```

**Review by andreimatei — COMMENTED** [review]
Thanks Ricky!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-:-MYkE8bT7RD7UUDK8sG-:b802hte)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dhartunian and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62502#-:-MYqKdNr7U2n-sdf1eh7:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dhartunian and @nvanbenschoten)

**Pull request merged**
