### PR TITLE
backupccl: clean up type descriptors after failed restore

### PR DESCRIPTION
**Pull request by rohany**
This commit ensures that the `RESTORE` job cleans up any written type
descriptors if the job fails.

Release note: None

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52491)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @rohany)

___
*[pkg/ccl/backupccl/backup_test.go, line 1309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52491#-ME5KhHw5aJnZmWeStMp:-ME5KhHw5aJnZmWeStMq:b82eo1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35a0f181cb75373ee6ce37ebee40b1b40bbae8f/pkg/ccl/backupccl/backup_test.go#L1309)):*
> ```Go
> 	// Verify that `myenum` was cleaned out from the failed restore. There should
> 	// only be one namespace entry (data.myenum).
> 	sqlDB.CheckQueryResults(t, `SELECT count(*) FROM system.namespace WHERE name = 'myenum'`, [][]string{{"1"}})
> ```

Is the restore that's run in this test expected to write any types even if it did succeed?

**Comment by rohany** [comment]
Yeah it should -- we are backing up the `data` database, and I've created a type `data.myenum` before the backup.

**Review by pbardea — APPROVED** [review]
Indeed - my eyes deceived me. LGTM.

**Comment by rohany** [comment]
teamcity pls

bors r+

**Pull request merged**
