### PR TITLE
sql: update the reporting hash function to be more secure

### PR DESCRIPTION
**Pull request by BramGruneir**
Use HMAC with a secret instead of just salting a SHA256.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
I'm sorry but this commit message is too terse. It should be extended to explain
1) why this change was needed
2) what are the costs associated

**Comment by knz** [comment]
Also the release note should highlight what is going on.

**Comment by BramGruneir** [comment]
I've updated the commit message.  There are no costs involved and this change is minor that I don't think a release note makes sense.

**Comment by knz** [comment]
Thanks! LGTM

**Comment by mberhault** [comment]
I don't have a problem with the change, I'm mostly curious. Is this purely for better crypo use (of which I'm all in favor), or is there a deeper reason? While hmac-sha256 does have some advantages over plain concatenated sha256, it doesn't quite impact this type of use.

**Comment by BramGruneir** [comment]
It was a far fetched scenario, but I felt it best to address it is all.  Entirely about better crypto.

**Pull request merged**
