### PR TITLE
build: remove useless env variable

### PR DESCRIPTION
**Pull request by tamird**
Snuck in a drive-by comment fix.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7516)

### CODE REVIEW

**Comment by dt** [comment]
Eh, I didn't do this the first time since if _we_ don't run this code path it risks not being exercised and we might miss something... think it's worth it?

**Comment by tamird** [comment]
Interestingly this causes TestSetupReportingURLs to fail, which begs the question: how does it pass in CI? My guess is that the answer is that setting the environment variable in circle-test.sh is not doing anything. What do you think?

**Comment by tamird** [comment]
Ah, of course it doesn't do anything - we're not passing the environment variable into the docker container that actually runs the tests.

**Comment by tamird** [comment]
Updated to just remove the useless env var. PTAL

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7516#-:-KLRNa_Yolkg6whlldhB:1417088721)*

**Comment by dt** [comment]
Huh, looks like there are some other env vars in here too that we might want to look at, e.g. `GOTRACEBACK`

**Comment by dt** [comment]
maybe the "right" way to do this isn't to disable reporting in dev/ci but rather to point it at a separate dummy reg server.

**Comment by petermattis** [comment]
@dt FYI, we're disabling the update check via the env var in `acceptance/cluster/localcluster.go` now.

**Comment by dt** [comment]
:lgtm:

This one is indeed useless, but we should probably figure something else out so that unit tests don't spam us.

**Comment by tamird** [comment]
Unit tests are probably unaffected since `SetupReportingURLs` is never
called, right?

**Comment by tamird** [comment]
Added a commit, PTAL

**Comment by dt** [comment]
Heh, so that last change is essentially where the update checker started started: parsing URLs in `Init` and then conditionally starting the goroutine . I switched it to always run the loop, including the KV parts, and then just bail out at the network calls to make execution as close to expected production execution as possible to minimize risk of anything rotting unnoticed. You think it's better to switch it off completely though?

**Comment by tamird** [comment]
Yeah, I mean, none of that stuff is really tested, and it has no way of returning any errors; I don't know what would be caught by running this goroutine =/

**Comment by tamird** [comment]
@petermattis: @dt makes a good point that the GOTRACEBACK setting in circle-test.sh appears to be useless. I'm not sure where it should go, though.

**Comment by petermattis** [comment]
I think you can do `${builder} make GOTRACEBACK=all test`. Would need to test that.

**Comment by dt** [comment]
k, :lgtm:

**Comment by tamird** [comment]
@petermattis done.
@RaduBerinde see last commit (will see the JSPM token for local runs)

**Pull request merged**
