### PR TITLE
roachtest: don't run SQL against the draining node

### LINKED ISSUE #125731: roachtest: kv/gracefuldraining failed
roachtest.kv/gracefuldraining [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15670966?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15670966?buildTab=artifacts#/kv/gracefuldraining) on master @ [3aa5bdf40527e2f60b179094403b4302a1c2cbe1](https://github.com/cockroachdb/cockroach/commits/3aa5bdf40527e2f60b179094403b4302a1c2cbe1):

```
(assertions.go:363).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:590
	            				main/pkg/cmd/roachtest/monitor.go:120
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
	            				src/runtime/asm_amd64.s:1695
	Error:      	Received unexpected error:
	            	QPS of 5.00 at time 2024-06-15 08:46:06.251665142 +0000 UTC m=+10554.934669970 is below minimum allowable QPS of 1800.00
	            	(1) attached stack trace
	            	  -- stack trace:
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKVGracefulDraining.func1.2
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:573
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKVGracefulDraining.func1.4
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:590
	            	  | main.(*monitorImpl).Go.func1
	            	  | 	main/pkg/cmd/roachtest/monitor.go:120
	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
	            	  | runtime.goexit
	            	  | 	src/runtime/asm_amd64.s:1695
	            	Wraps: (2) QPS of 5.00 at time 2024-06-15 08:46:06.251665142 +0000 UTC m=+10554.934669970 is below minimum allowable QPS of 1800.00
	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
	Test:       	kv/gracefuldraining
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/kv/gracefuldraining/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-15670966/kv-gracefuldraining/1718441130292/1718441330705)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/gracefuldraining.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-39576

### LINKED ISSUE #126986: roachtest: kv/gracefuldraining failed
roachtest.kv/gracefuldraining [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16022118?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16022118?buildTab=artifacts#/kv/gracefuldraining) on release-24.2 @ [495d20e82f09b3436f1b00d7331146fe2042dd6a](https://github.com/cockroachdb/cockroach/commits/495d20e82f09b3436f1b00d7331146fe2042dd6a):

```
(assertions.go:363).Fail: 
	Error Trace:	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:596
	            				main/pkg/cmd/roachtest/monitor.go:120
	            				golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
	            				src/runtime/asm_amd64.s:1695
	Error:      	Received unexpected error:
	            	QPS of 48.00 at time 2024-07-11 09:22:21.441444532 +0000 UTC m=+12619.612331461 is below minimum allowable QPS of 1800.00
	            	(1) attached stack trace
	            	  -- stack trace:
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKVGracefulDraining.func1.2
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:579
	            	  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKVGracefulDraining.func1.4
	            	  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:596
	            	  | main.(*monitorImpl).Go.func1
	            	  | 	main/pkg/cmd/roachtest/monitor.go:120
	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
	            	  | runtime.goexit
	            	  | 	src/runtime/asm_amd64.s:1695
	            	Wraps: (2) QPS of 48.00 at time 2024-07-11 09:22:21.441444532 +0000 UTC m=+12619.612331461 is below minimum allowable QPS of 1800.00
	            	Error types: (1) *withstack.withStack (2) *errutil.leafError
	Test:       	kv/gracefuldraining
(require.go:1357).NoError: FailNow called
test artifacts and logs in: /artifacts/kv/gracefuldraining/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16022118/kv-gracefuldraining/1720689700949/1720690183911)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #125731 roachtest: kv/gracefuldraining failed [A-testing C-bug C-test-failure O-roachtest O-robot P-2 T-kv branch-master]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/gracefuldraining.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40222

### LINKED ISSUE #128168: roachtest: kv/gracefuldraining failed
roachtest.kv/gracefuldraining [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16298889?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16298889?buildTab=artifacts#/kv/gracefuldraining) on release-24.2.0-rc @ [46c11ab2cf6fa6f6adf7abb99ef72f68e4d538f8](https://github.com/cockroachdb/cockroach/commits/46c11ab2cf6fa6f6adf7abb99ef72f68e4d538f8):

```
(soon.go:64).SucceedsWithin: condition failed to evaluate within 45s: from kv.go:588: QPS of 1672.00 at time 2024-08-02 09:13:41.512159845 +0000 UTC m=+12419.554139960 is below minimum allowable QPS of 1800.00
test artifacts and logs in: /artifacts/kv/gracefuldraining/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16298889/kv-gracefuldraining/1722589954357/1722590171661)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #126986 roachtest: kv/gracefuldraining failed [A-testing C-bug C-test-failure O-roachtest O-robot P-2 T-kv X-duplicate branch-release-24.2]
- #125731 roachtest: kv/gracefuldraining failed [A-testing C-bug C-test-failure O-roachtest O-robot P-2 T-kv branch-master]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/gracefuldraining.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40841

### LINKED ISSUE #128439: roachtest: kv/gracefuldraining/nodes=3 failed
roachtest.kv/gracefuldraining/nodes=3 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16356924?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16356924?buildTab=artifacts#/kv/gracefuldraining/nodes=3) on release-24.1 @ [8b9381ed3138c5fb93db15534b25d78b49d6a75a](https://github.com/cockroachdb/cockroach/commits/8b9381ed3138c5fb93db15534b25d78b49d6a75a):

```
(soon.go:64).SucceedsWithin: condition failed to evaluate within 45s: from kv.go:571: QPS of 667.00 at time 2024-08-07 06:11:41.623925657 +0000 UTC m=+1443.157948403 is below minimum allowable QPS of 900.00
test artifacts and logs in: /artifacts/kv/gracefuldraining/nodes=3/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16356924/kv-gracefuldraining-nodes-3/1723011035340/1723011247089)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/gracefuldraining/nodes=3.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41014

### LINKED ISSUE #129027: roachtest: kv/gracefuldraining/nodes=3 failed
roachtest.kv/gracefuldraining/nodes=3 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16475340?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16475340?buildTab=artifacts#/kv/gracefuldraining/nodes=3) on release-24.1.4-rc @ [f629e9a3a88152ab73ee154eb5fe1e7c819e1af3](https://github.com/cockroachdb/cockroach/commits/f629e9a3a88152ab73ee154eb5fe1e7c819e1af3):

```
(soon.go:64).SucceedsWithin: condition failed to evaluate within 45s: from kv.go:571: QPS of 668.00 at time 2024-08-15 07:21:17.159809514 +0000 UTC m=+5630.001831879 is below minimum allowable QPS of 900.00
test artifacts and logs in: /artifacts/kv/gracefuldraining/nodes=3/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16475340/kv-gracefuldraining-nodes-3/1723706412262/1723706623016)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #128439 roachtest: kv/gracefuldraining/nodes=3 failed [A-testing C-bug C-test-failure O-roachtest O-robot P-2 T-kv X-duplicate branch-release-24.1]
</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv/gracefuldraining/nodes=3.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41336

### PR DESCRIPTION
**Pull request by andrewbaptist**
After #126506 the test incorrectly included the draining node as part of the nodes the workload were run against. This caused the statistics to be off by a factor of 5/6.

Note there is a separate issue related to the QPS dropping as part of the drain which is a different issue that is masked by this issue.

Epic: none

Fixes: #129027
Fixes: #128439
Fixes: #128168
Fixes: #126986
Fixes: #125731

Release note: None

### CODE REVIEW

**Review by kvoli — APPROVED** [review]

**Comment by andrewbaptist** [comment]
bors r=kvoli

Merging now to prevent additional test failures, but I opened #129427 to track the change of the default setting.

**Comment by aadityasondhi** [comment]
bors r-

This is failing lint.

**Comment by kvoli** [comment]
I'm not sure about some of the other commits added in after the first review. Was the first change insufficient, could they have been separate PRs?

**Comment by andrewbaptist** [comment]
I added a new commit to fix the erroneous log message. The 2 other commits helped the test debuggability by fixing "leak" issues on failures. The settings change was necessary and I opened #129427 to track it so at least this test can run cleanly until that is addressed.

**Pull request merged**
