### PR TITLE
Multiple log improvements

### PR DESCRIPTION
**Pull request by knz**
Moving forward with the improvements listed in #14327:

**log: restore the original stderr as failover error stream**

The patch in 3123215 has introduced a
mechanism whereby syscall.Stderr (file descriptor 2) becomes an alias
to the log file, when a log file is created. This ensures that e.g. Go
panic reports are sent to the log file for later inspection.

This patch complements the original change by ensuring that the really
important informational messages from the running process are still
emitted to the original stderr, despite this redirect. These
informational messages include:

- errors that occur while writing to a log file.
- the informational message that indicates which directory contains
  the log files, emitted by the TestLogScope object when used in tests.

**log: make the TestLogScope more informative and helpful.**

- the original stderr is now restored when the log file is closed.
  This ensures that when a TestLogScope() is closed because of a panic,
  the panic details still get reported on the original stderr.
- the TestLogScope now also informs about the location of the log
  files at the beginning of the test, not only at the end.
- if a panic has occurred, the TestLogScope also informs the user
  on (the real) stderr that the panic has occurred, suggesting
  where to find the information.

**cli: make it more likely that the user will know a panic has occurred.**

(This sets up a recover at the top-level CLI functions so that the user is informed to look at the log files if no panic details are visible)

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14364)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 4 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cli/cli.go, line 44 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364#-KgFKKXRX7naVtqBvbhy:-KgFKKXRX7naVtqBvbhz:b-l7wdkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e91557dbd1624c6933bb14207e95cf05d9982/pkg/cli/cli.go#L44)):*
> ```Go
> 
> 	defer func() {
> 		if err := recover(); err != nil {
> ```

Note that this only catches panics in this goroutine, so it will catch many panics at startup but probably not any once the server is running. 

---

*[pkg/cli/start.go, line 354 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364#-KgFKsdNrvOk-avw45YR:-KgFKsdNrvOk-avw45YS:bapnav8) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e91557dbd1624c6933bb14207e95cf05d9982/pkg/cli/start.go#L354)):*
> ```Go
> 	errChan := make(chan error, 1)
> 	go func() {
> 		defer func() {
> ```

Maybe factor this function out into a separate method so it can be shared between the two uses?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364#-:-KgFMBSwGjxsVjfQi7Lw:bnfp4nl)*

**Comment by knz** [comment]
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cli/cli.go, line 44 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364#-KgFKKXRX7naVtqBvbhy:-KgHy0oqzl-OYuoieOS2:b-in9m5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e91557dbd1624c6933bb14207e95cf05d9982/pkg/cli/cli.go#L44)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Note that this only catches panics in this goroutine, so it will catch many panics at startup but probably not any once the server is running. 
</blockquote></details>

Correct; that's why I am also adding one in `start.go`.

---

*[pkg/cli/start.go, line 354 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364#-KgFKsdNrvOk-avw45YR:-KgI1p7MoVRhRvsl-D9j:b-p2hnvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/820e91557dbd1624c6933bb14207e95cf05d9982/pkg/cli/start.go#L354)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Maybe factor this function out into a separate method so it can be shared between the two uses?
</blockquote></details>

Done.

Contrary to what I initially thought you can actually call recover from a separate function. That's what the Stopper does already.

I actually extended this patch so that the stopper also invokes the common informational function for all worker / async tasks.

PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364)*

**Comment by knz** [comment]
cc @petermattis since you're now back from vacation.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/util/log/clog_test.go, line 625 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364#-KgKiqPnSNrUC2dJFlQd:-KgKiqPowMysQYg1msVE:bnfomsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/766a3daa5c9f365c61b3c9469d94ea4c01b8e67a/pkg/util/log/clog_test.go#L625)):*
> ```Go
> 	showLogsSave := showLogs
> 	defer func(s bool) { showLogs = s }(showLogsSave)
> 	showLogs = false
> ```

I don't think `showLogsSave` is necessary. This could be:

```
defer func(s bool) { showLogs = s}(showLogs)
showLogs = false
```

---

*[pkg/util/stop/stopper.go, line 208 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364#-KgKkAbgo6ln7IaAZvTG:-KgKkAbgo6ln7IaAZvTH:b-ozjy7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/766a3daa5c9f365c61b3c9469d94ea4c01b8e67a/pkg/util/stop/stopper.go#L208)):*
> ```Go
> 	go func() {
> 		defer log.RecoverAndReportPanic()
> 		defer s.Recover()
> ```

Sort of strange to have 2 defers that `recover/re-panic`. Perhaps `Stopper.Recover` should call `log.ReportPanic(r)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364#-:-KgKkNOTFHR2mGk5af7G:bnfp4nl)*

**Comment by knz** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/util/log/clog_test.go, line 625 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364#-KgKiqPnSNrUC2dJFlQd:-KgL_fVTEkvc30gw9hP-:bhtoxkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/766a3daa5c9f365c61b3c9469d94ea4c01b8e67a/pkg/util/log/clog_test.go#L625)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't think `showLogsSave` is necessary. This could be:

```
defer func(s bool) { showLogs = s}(showLogs)
showLogs = false
```
</blockquote></details>

Oh excellent. I always forget about immediate evaluation of defer args.

---

*[pkg/util/stop/stopper.go, line 208 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364#-KgKkAbgo6ln7IaAZvTG:-KgL_NMfPj77tc21H_Lb:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/766a3daa5c9f365c61b3c9469d94ea4c01b8e67a/pkg/util/stop/stopper.go#L208)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Sort of strange to have 2 defers that `recover/re-panic`. Perhaps `Stopper.Recover` should call `log.ReportPanic(r)`.
</blockquote></details>

Good idea. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14364)*

**Comment by knz** [comment]
TFYRs!

**Pull request merged**
