### PR TITLE
colexec: introduce batches with dynamic capacity

### LINKED ISSUE #49796: colexec: add dynamic batches
Add support for dynamically growing batch sizes. This is a first step towards removing the row execution engine. If batch sizes start with a size of 1 and only grow when necessary, point lookups could be as performant, if not more, than the row execution engine.

This might allow us to remove `vectorize_row_count_threshold` entirely and always plan the vectorized flow when it is supported.

I'd likely extend `colmem.Allocator` to add a method like `MaybeReallocate(coldata.Batch) coldata.Batch` which would look at the capacity of the old batch and would double it until `coldata.BatchSize()` threshold is reached. I'd also probably introduce another lightweight utility operator `batchCapacityEnforcer` that would be planned similarly to `vectorTypeEnforcer`, as an input to all other operators.

### PR DESCRIPTION
**Pull request by yuzefovich**
Depends on #52728.

**col, colexec: introduce the concept of capacity to coldata.Batch**

This commit introduces the concept of capacity to `coldata.Batch` which
describes the maximum number of tuples the batch can store. Note that it
is a lower bound meaning that some vectors in the batch might have
larger underlying capacity (e.g. when they were appended to).

Additionally this commit does several mechanical changes to rename the
methods.

Release note: None

**colexec: remove custom input/output batch size logic from few places**

Ordered aggregator, hash and merge joiners, and hash router had custom
input/output batch size logic that was put in place in order to increase
testing. This, however, is no longer required since we now randomize
`coldata.BatchSize()` value during the test runs, so that custom logic
is now removed.

Additionally, this commit removes several unit tests of the merge joiner
which are now exact copies of each other (previously, they had different
output batch size set).

One notable change is that this commit removes a tiny optimization from
the merge joiner when there are no output columns (meaning we have
a COUNT query).

This work has been done in order to ease follow-up work on the dynamic
batch sizes.

Release note: None

**colexec: use batches with dynamic capacity in several operators**

This commit introduces `ResetMaybeReallocate` method on
`colmem.Allocator` which might allocate a new batch (it uses an
exponential capacity growth until `coldata.BatchSize()` and also
supports a minimum capacity argument). The method can be used by the
operators that want "dynamic batch size" behavior. All usages of
`NewMemBatchWithMaxCapacity` and `NewMemBatchWithFixedCapacity` in
non-test files have been audited, and most of the operators have been
updated to exhibit the dynamic batch size behavior (most notable
exception to this are the aggregators because currently aggregate
functions hold on their output vectors, so we can't just reallocate an
output batch). The usage of `NewMemBatchWithMaxCapacity` is now
prohibited in non-test files by a linter in order to encourage the
engineers to think whether a dynamic batch size behavior is desired.

Resolves: #49796.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Alright, I think this is RFAL.

I run a quick benchmark of KV workload on 3 node roachprod cluster on my laptop with `vectorize_row_count_threshold=1000` (default value which will force us to use the table reader - "old") and with `vectorize_row_count_threshold=0` (which will force us to use the cfetcher - "new"), and the numbers are very optimistic:
- "old":
```
Yahors-MacBook-Pro:cockroach yuzefovich$ tail -f old.out 
Highest sequence written: 29301. Can be passed as --write-seq=R29301 to the next run.

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  120.0s        0         556047         4633.5      0.9      0.4      0.8      1.3    369.1  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  120.0s        0          29269          243.9    114.2    113.2    184.5    234.9    436.2  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  120.0s        0         585316         4877.4      6.6      0.4     65.0    151.0    436.2  
```
- "new":
```
Highest sequence written: 32543. Can be passed as --write-seq=R32543 to the next run.

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  120.0s        0         621370         5177.9      0.8      0.4      0.9      1.5    335.5  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  120.0s        0          32514          270.9    102.3    100.7    176.2    218.1    503.3  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  120.0s        0         653884         5448.9      5.9      0.5     56.6    130.0    503.3  
```
I'd take it with a grain of salt (maybe they are due to variance of running the benchmark on the mac), but it looks like we might be able to get rid off `vectorize_row_count_threshold` heuristic entirely and always use the vectorized engine if it is supported.

**Comment by yuzefovich** [comment]
Some TPCC numbers, 3 node roachprod cluster with 100 warehouses, 1 minute of ramp and 5 minutes of load:
```
Yahors-MacBook-Pro:cockroach yuzefovich$ tail -f -n 2 3node-old.log 
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  300.0s     1194.2  92.9%     25.5     24.1     35.7     41.9     56.6     83.9

Yahors-MacBook-Pro:cockroach yuzefovich$ tail -f -n 2 3node-new.log 
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  300.0s     1197.0  93.1%     28.6     27.3     39.8     48.2     67.1    100.7
```

**Review by asubiotto — CHANGES_REQUESTED** [review]
Great to see this and awesome results

> Reviewed 68 of 68 files at r1, 22 of 22 files at r2, 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-:-ME8XQWD9dpL_hLsQW_W:b-fwdqpk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/coldata/batch.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8A_U65PbQ_2ViWbFA:-ME8A_U65PbQ_2ViWbFB:bg9jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7559c8ff399780df92adc098513eb7f7cb6894d2/pkg/col/coldata/batch.go#L128)):*
> ```Go
> func NewMemBatchNoCols(typs []*types.T, capacity int) Batch {
> 	if max := math.MaxUint16; capacity > max {
> 		panic(fmt.Sprintf(`batches cannot have length larger than %d; requested %d`, max, capacity))
> ```

`s/length/capacity`
___
*[pkg/col/coldata/vec.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8EPyjDeGaDTeVIcDW:-ME8EPyjDeGaDTeVIcDX:b-eiezbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7559c8ff399780df92adc098513eb7f7cb6894d2/pkg/col/coldata/vec.go#L134)):*
> ```Go
> 	// Capacity returns the capacity of the Golang's slice that is underlying
> 	// this Vec. Note that if there is no "slice" (like in case of flat bytes),
> 	// then "capacity" of such object is equal to its "length".
> ```

I think this last sentence is a bit vague (maybe just to me) how about: `then the capacity is equal to the number of elements`
___
*[pkg/sql/colexec/dynamic_batch_size_helper.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8TEpt79MwSGbwy6AM:-ME8TEpt79MwSGbwy6AN:b-3r2p3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a93872871b2842552606e086b0ce349e1444d80/pkg/sql/colexec/dynamic_batch_size_helper.go#L29)):*
> ```Go
> }
> 
> // DynamicBatchSizeHelper is a utility struct that helps operators work with
> ```

I think this comment can use more fleshing out, i.e. how does it "help"?
___
*[pkg/sql/colexec/dynamic_batch_size_helper.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8VV6yCHiRZvU7OQtQ:-ME8VV6yCHiRZvU7OQtR:bdc2qte) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a93872871b2842552606e086b0ce349e1444d80/pkg/sql/colexec/dynamic_batch_size_helper.go#L40)):*
> ```Go
> // grow the allocated capacity of the batch exponentially, until the batch
> // reaches coldata.BatchSize().
> func (d *DynamicBatchSizeHelper) ResetMaybeReallocate(
> ```

Why not make this a part of the allocator? Also, all operators should now be calling this method, right? Are we enforcing this in any way? What valid uses of the normal `Reset` are there?
___
*[pkg/sql/colexec/mergejoiner.go, line 606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8GPD_CL1CUDlUwXZo:-ME8GPDa7rFKaAgbWf8u:b-uorap) ([raw file](https://github.com/cockroachdb/cockroach/blob/7559c8ff399780df92adc098513eb7f7cb6894d2/pkg/sql/colexec/mergejoiner.go#L606)):*
> ```Go
> 		bufferedGroup = &o.proberState.rBufferedGroup
> 	}
> 	// TODO(yuzefovich): reuse the same scratch batches when spillingQueue
> ```

I have an old branch that I'm hoping to revive
___
*[pkg/sql/colexec/routers.go, line 415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8W6lY9La4IV0c5j8o:-ME8W6lY9La4IV0c5j8p:b-w5q3te) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a93872871b2842552606e086b0ce349e1444d80/pkg/sql/colexec/routers.go#L415)):*
> ```Go
> 	for toAppend := len(selection); toAppend > 0; {
> 		if o.mu.pendingBatch == nil {
> 			// TODO(yuzefovich): consider whether this should be a dynamic batch.
> ```

It's a good question. I don't think so because I consider this a fixed-size scratch buffer that we flush from. What do you think?
___
*[pkg/sql/colexec/sorttopk.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8Wcm41myZeC7pKdxp:-ME8Wcm53N1DC_A6NgIZ:bxkuyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a93872871b2842552606e086b0ce349e1444d80/pkg/sql/colexec/sorttopk.go#L60)):*
> ```Go
> 	// its input.
> 	topKSortSpooling topKSortState = iota
> 	// topKSortSpooling is the second state of the operator, indicating that
> ```

nit: `s/topKSortSpooling/topKSortEmitting`
___
*[pkg/sql/colmem/allocator.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8Er0l1WYpqyRCuoQY:-ME8Er0l1WYpqyRCuoQZ:b-z5fptr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7559c8ff399780df92adc098513eb7f7cb6894d2/pkg/sql/colmem/allocator.go#L94)):*
> ```Go
> // NewMemBatchWithMaxCapacity allocates a new in-memory coldata.Batch of
> // coldata.BatchSize() capacity.
> func (a *Allocator) NewMemBatchWithMaxCapacity(typs []*types.T) coldata.Batch {
> ```

Why not keep this as `NewMemBatch`?
___
*[pkg/sql/colmem/allocator.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8Ex730xdxuI7pHLPI:-ME8Ex730xdxuI7pHLPJ:b-9emrm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7559c8ff399780df92adc098513eb7f7cb6894d2/pkg/sql/colmem/allocator.go#L100)):*
> ```Go
> // NewMemBatchWithFixedCapacity allocates a new in-memory coldata.Batch with
> // the given capacity.
> func (a *Allocator) NewMemBatchWithFixedCapacity(typs []*types.T, capacity int) coldata.Batch {
> ```

Why `Fixed` if it's going to be dynamic?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52453)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/batch.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8A_U65PbQ_2ViWbFA:-MEPaHAM3FXvjsv18Fqb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7559c8ff399780df92adc098513eb7f7cb6894d2/pkg/col/coldata/batch.go#L128)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/length/capacity`
</blockquote></details>

Done.
___
*[pkg/col/coldata/vec.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8EPyjDeGaDTeVIcDW:-MEPakPL0FlmL9LoHeHQ:b-zc0ner) ([raw file](https://github.com/cockroachdb/cockroach/blob/7559c8ff399780df92adc098513eb7f7cb6894d2/pkg/col/coldata/vec.go#L134)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this last sentence is a bit vague (maybe just to me) how about: `then the capacity is equal to the number of elements`
</blockquote></details>

Done.

I agree, it's a bit vague for non-slice-backed typed, but currently this method is only used to get the memory footprint, so it's ok if we don't define the contract perfectly. I think in the future we should be able to have pools of vectors of all types of different capacities that would be taken from by `colmem.Allocator` objects, but we're not there yet.
___
*[pkg/sql/colexec/dynamic_batch_size_helper.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8TEpt79MwSGbwy6AM:-MEPd5WbD0_hrCcR8Pjl:bj7qf8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a93872871b2842552606e086b0ce349e1444d80/pkg/sql/colexec/dynamic_batch_size_helper.go#L29)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this comment can use more fleshing out, i.e. how does it "help"?
</blockquote></details>

Expanded the comment.

Update: removed the struct.
___
*[pkg/sql/colexec/dynamic_batch_size_helper.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8VV6yCHiRZvU7OQtQ:-MEPh6GMAYS4htIa2r7I:b-i2ummm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a93872871b2842552606e086b0ce349e1444d80/pkg/sql/colexec/dynamic_batch_size_helper.go#L40)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not make this a part of the allocator? Also, all operators should now be calling this method, right? Are we enforcing this in any way? What valid uses of the normal `Reset` are there?
</blockquote></details>

Made it a part of the allocator.

No, not all operators are expected to use this method - only those for which it makes sense to have the "dynamic size" behavior. My thinking is that all operators that instantiate batches to be returned as their output can be roughly divided into two groups:
- in the first group, the work that operator needs to perform in order to produce a single tuple into the output is about the same, regardless whether that tuple is first, second, or last in the whole output stream (examples of such operators are `cFetcher` and `columnarizer`). Operators in this group want the "dynamic size" behavior.
- in the second group, the work that operator needs to perform in order to produce a single tuple is not "distributed uniformly" among all tuples (examples are hash joiner and hash aggregator). Such operators don't want the "dynamic size" behavior because it wouldn't be beneficial because usually such operators perform other non-batch-related "internal" allocations of different things, so it wouldn't really matter if their output batch behaved dynamically.

In this PR, I first looked over all usages of `Allocator.NewMemBatch` method to separate them into `NewMemBatchWithMaxCapacity` and `NewMemBatchWithFixedCapacity`, and the usages of the latter definitely don't need the dynamic behavior. Then, I looked at all usages of `NewMemBatchWithMaxCapacity` in the non-test files and singled out those that I think would benefit from the dynamic behavior, and I converted all such cases to the new pattern. The only operator I wasn't sure about is `routerOutputOp`, but I think that should use "max capacity" batch.

`ResetMaybeReallocate` effectively replaces `outputBatch.ResetInternalBatch` in the operators that want the dynamic behavior. However, since some operators still want the fixed behavior, we need to keep `coldata.Batch.ResetInternalBatch`.
___
*[pkg/sql/colexec/mergejoiner.go, line 606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8GPD_CL1CUDlUwXZo:-MEPlHVs8jI-OdvSwbJ5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7559c8ff399780df92adc098513eb7f7cb6894d2/pkg/sql/colexec/mergejoiner.go#L606)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I have an old branch that I'm hoping to revive
</blockquote></details>

Done.
___
*[pkg/sql/colexec/routers.go, line 415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8W6lY9La4IV0c5j8o:-MEPk_Vt100BylqzRLms:b-gdt3hv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a93872871b2842552606e086b0ce349e1444d80/pkg/sql/colexec/routers.go#L415)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's a good question. I don't think so because I consider this a fixed-size scratch buffer that we flush from. What do you think?
</blockquote></details>

Yeah, I think so too.
___
*[pkg/sql/colmem/allocator.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8Er0l1WYpqyRCuoQY:-MEPbVph6cp0Se-5IkT0:bd94rib) ([raw file](https://github.com/cockroachdb/cockroach/blob/7559c8ff399780df92adc098513eb7f7cb6894d2/pkg/sql/colmem/allocator.go#L94)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not keep this as `NewMemBatch`?
</blockquote></details>

I think `NewMemBatch` is a little too generic, and I want to force the user of `Allocator` to think through whether a batch with fixed size should be used, a batch with maximum size, or a dynamic batch. I'm worried that `NewMemBatch` will be considered as the default option without giving it any thought.
___
*[pkg/sql/colmem/allocator.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8Ex730xdxuI7pHLPI:-MEPbuCVB0zcPeDFg-Pv:bamgigw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7559c8ff399780df92adc098513eb7f7cb6894d2/pkg/sql/colmem/allocator.go#L100)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why `Fixed` if it's going to be dynamic?
</blockquote></details>

The batch itself is not dynamic in size - we currently will allocate a new batch with a bigger size.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r4, 22 of 22 files at r5, 12 of 12 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52453)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/dynamic_batch_size_helper.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8VV6yCHiRZvU7OQtQ:-MEXy5dw24okG40n7--K:b-k4d32o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a93872871b2842552606e086b0ce349e1444d80/pkg/sql/colexec/dynamic_batch_size_helper.go#L40)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Made it a part of the allocator.

No, not all operators are expected to use this method - only those for which it makes sense to have the "dynamic size" behavior. My thinking is that all operators that instantiate batches to be returned as their output can be roughly divided into two groups:
- in the first group, the work that operator needs to perform in order to produce a single tuple into the output is about the same, regardless whether that tuple is first, second, or last in the whole output stream (examples of such operators are `cFetcher` and `columnarizer`). Operators in this group want the "dynamic size" behavior.
- in the second group, the work that operator needs to perform in order to produce a single tuple is not "distributed uniformly" among all tuples (examples are hash joiner and hash aggregator). Such operators don't want the "dynamic size" behavior because it wouldn't be beneficial because usually such operators perform other non-batch-related "internal" allocations of different things, so it wouldn't really matter if their output batch behaved dynamically.

In this PR, I first looked over all usages of `Allocator.NewMemBatch` method to separate them into `NewMemBatchWithMaxCapacity` and `NewMemBatchWithFixedCapacity`, and the usages of the latter definitely don't need the dynamic behavior. Then, I looked at all usages of `NewMemBatchWithMaxCapacity` in the non-test files and singled out those that I think would benefit from the dynamic behavior, and I converted all such cases to the new pattern. The only operator I wasn't sure about is `routerOutputOp`, but I think that should use "max capacity" batch.

`ResetMaybeReallocate` effectively replaces `outputBatch.ResetInternalBatch` in the operators that want the dynamic behavior. However, since some operators still want the fixed behavior, we need to keep `coldata.Batch.ResetInternalBatch`.
</blockquote></details>

Did you write this comment before the 1:1? I think it's still worth discussing whether we want to have these two separate groups or just have dynamic batch sizes everywhere. I prefer going down the route of having dynamic batch sizes everywhere because it makes programming simpler and the cost of dynamic batch sizes should be amortized. Also, it's not clear that the second group is that clearly defined, e.g. I think you put the hash joiner in the second group but we brought up the case of a single row join. We didn't finish that discussion because we had to leave to the next meeting, but we were talking about how it needed to allocate a hash table anyway.

Is there a way we could measure the performance impact of having dynamic batch sizes everywhere?

**Comment by asubiotto** [comment]
Might be good to discuss the above point at standup cc @jordanlewis @helenmhe

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52453)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/dynamic_batch_size_helper.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-ME8VV6yCHiRZvU7OQtQ:-MEZhCsSBer42pMaeVa3:b-wdrgv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a93872871b2842552606e086b0ce349e1444d80/pkg/sql/colexec/dynamic_batch_size_helper.go#L40)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Did you write this comment before the 1:1? I think it's still worth discussing whether we want to have these two separate groups or just have dynamic batch sizes everywhere. I prefer going down the route of having dynamic batch sizes everywhere because it makes programming simpler and the cost of dynamic batch sizes should be amortized. Also, it's not clear that the second group is that clearly defined, e.g. I think you put the hash joiner in the second group but we brought up the case of a single row join. We didn't finish that discussion because we had to leave to the next meeting, but we were talking about how it needed to allocate a hash table anyway.

Is there a way we could measure the performance impact of having dynamic batch sizes everywhere?
</blockquote></details>

Yes, I did write this down before our 1:1.

I have gone ahead and audited all usages of `NewMemBatchWith*Capacity` methods in non-test files and added the dynamic batch size behavior in several places. I also added a linter to prohibit calls to `NewMemBatchWithMaxCapacity` from non-test files so that the engineer was forced to think whether dynamic batch size behavior is desired. The only operators that haven't been converted (but in theory which could have been) are the aggregators (because reallocating an output batch breaks the contract of aggregate functions) and `relative_rank` operators (because that code is already pretty hard to reason about, and introduction of dynamic batch size would likely make things worse without giving any performance benefit).

I think it's not worth spending more time on this at this point.

**Comment by yuzefovich** [comment]
I figured out why the tests were failing (problem with falling over from in-memory hash joiner to the external hash joiner on `*-disk` configs - I changed when output batch allocation was occurring; fixed). RFAL.

**Review by asubiotto — APPROVED** [review]
:lgtm: but are the `SIGQUIT` CI failures concerning?

> Reviewed 79 of 79 files at r7, 68 of 68 files at r8, 26 of 26 files at r10, 34 of 34 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52453#-:-MEhO1LaDP36PBc8x5mW:b-8nhah)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
I'm thinking it's logic tests timeouts.

**Comment by asubiotto** [comment]
That's surprising to me, `TestLogic` takes 18m on the latest green build on master (https://teamcity.cockroachdb.com/viewLog.html?buildId=2081184&buildTypeId=Cockroach_UnitTests&tab=testsInfo&branch_Cockroach=%3Cdefault%3E), here it's 30m.

**Comment by yuzefovich** [comment]
Since we vary batch size, a single run might not be representative. I also saw the timeout failure on your PR for context cancellation fix. I have a hypothesis that dynamic batch size logic might be making tests run even slower (to be confirmed), so the timeouts are more likely to occur. Another thing is that I think I've seen timeouts a couple of times recently, so I'm pretty sure that currently on master we're pretty close to 30 minutes often.

**Comment by asubiotto** [comment]
I'm not so sure. Given that this change modifies a pretty fundamental part of the code, isn't it likely that there's something else going on? Do you have a link to those timeouts? Combing through the last ~10 runs on master https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_EssentialCi&branch_Cockroach=%3Cdefault%3E&tab=buildTypeStatusDiv the runtime is more or less steady at ~20-22 mins with one run at 25mins. Unfortunately I don't think it's easy to see the batch size for successful builds.

**Comment by yuzefovich** [comment]
I'm not sure either. I want to wait for another CI build on this branch before jumping to any conclusions, but I thought I'd share my current guess.

**Comment by asubiotto** [comment]
I see what you mean regarding timeouts in the context cancellation PR. It doesn't seem like that's a normal timeout. It looks like `UpsertSetDefault` was stuck for 10 minutes.

**Comment by yuzefovich** [comment]
I'm pretty sure the failures are timeouts - the dump of goroutines on SIGQUIT shows a bunch of them have been running around 29-30 minutes, possibly it's a coincidence, but I think it's more likely to be timeouts (locally, the files that the tests failed on pass when ran one at a time).

**Comment by yuzefovich** [comment]
There was a simple bug in `ResetMaybeReallocate` - I wasn't truncating `minCapacity` to `coldata.BatchSize()` in all code paths although that's the contract of the method. As a result, we could have created batches that are larger than the maximum size which breaks our assumptions and would end up in an infinite loop, fixed.

I'll wait for a CI run and merge if green.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
