### PR TITLE
sql/pgwire: support decoding of binary bitarrays

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note (sql change): add binary varbit support over pgwire.

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm: AWESOME! Thank you

(nits below)

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34050#-:-LWL-ggcDC-tlG_4AKGQ:b31ckdo)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34050#-LWKzwy-55bfwI2_NSae:-LWKzwy0Ahb2-VStHTGV:b4f5a2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/937c48079807d04cbf645e9c4d5115a17edf5862/pkg/sql/pgwire/pgwirebase/encoding.go#L548)):*
> ```Go
> 				lastBitsUsed = 64
> 			}
> 			if bitlen < 0 || len(b)*8 < int(bitlen) {
> ```

`bitlen` is a `Uint32` and thus cannot be negative.
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34050#-LWL-Fmt0twrrMzBzo9Z:-LWL-Fmt0twrrMzBzo9_:bpv2zsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/937c48079807d04cbf645e9c4d5115a17edf5862/pkg/sql/pgwire/pgwirebase/encoding.go#L551)):*
> ```Go
> 				return nil, errors.Errorf("unexpected varbit bitlen %d (b: %d)", bitlen, len(b))
> 			}
> 			words := make([]uint64, (len(b)+7)/8)
> ```

Add an explanatory comment as to why you need two loops. An uninformed reader would be tempted to merge them into just one (`for i := 0; i < len(words); i++`)
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34050#-LWL-S20EWKKgFxE7e-5:-LWL-S20EWKKgFxE7e-6:b-afe73n) ([raw file](https://github.com/cockroachdb/cockroach/blob/937c48079807d04cbf645e9c4d5115a17edf5862/pkg/sql/pgwire/pgwirebase/encoding.go#L560)):*
> ```Go
> 				i := uint(0)
> 				for ; i < uint(lastBitsUsed); i += 8 {
> 					w <<= 8
> ```

nit: `w = (w << 8) | uint64(b[0])` is more idiomatic (at least use `|` instead of `+`)
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34050#-LWL-a515PAHSjVKUScV:-LWL-a52D4Rc0uxYRWAW:b-t0bq7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/937c48079807d04cbf645e9c4d5115a17edf5862/pkg/sql/pgwire/pgwirebase/encoding.go#L565)):*
> ```Go
> 				}
> 				w <<= 64 - i
> 				words[len(words)-1] = w
> ```

ditto for readability I think you can combine these last two statements in one line.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34050)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34050#-LWKzwy-55bfwI2_NSae:-LWNBQ2C1aSDNk_N1HSB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/937c48079807d04cbf645e9c4d5115a17edf5862/pkg/sql/pgwire/pgwirebase/encoding.go#L548)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`bitlen` is a `Uint32` and thus cannot be negative.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34050#-LWL-Fmt0twrrMzBzo9Z:-LWNBrr5E_v5vQoWitvg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/937c48079807d04cbf645e9c4d5115a17edf5862/pkg/sql/pgwire/pgwirebase/encoding.go#L551)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add an explanatory comment as to why you need two loops. An uninformed reader would be tempted to merge them into just one (`for i := 0; i < len(words); i++`)
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/pgwirebase/encoding.go, line 565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34050#-LWL-a515PAHSjVKUScV:-LWNBz633ruFhfG2AJrx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/937c48079807d04cbf645e9c4d5115a17edf5862/pkg/sql/pgwire/pgwirebase/encoding.go#L565)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto for readability I think you can combine these last two statements in one line.
</blockquote></details>

Done.

**Pull request merged**
