### PR TITLE
kvserver: batch intents in `MVCCIterator.CheckForKeyCollisions`

### PR DESCRIPTION
**Pull request by erikgrinaker**
`MVCCIterator.CheckForKeyCollisions()` is used by `AddSSTable` to check
for key collisions when `DisallowShadowing` is set. If it encounters any
intents, it returns `WriteIntentError` to resolve these before retrying.

However, this returned an error for each individual intent, which has
quadratic performance. This patch changes it to instead collect and
return a batch of intents, for more efficient intent resolution.

The batch size is controlled by the existing setting
`storage.mvcc.max_intents_per_error`, which defaults to 5000.

Resolves #71697.

Release note (performance improvement): Improved `IMPORT INTO`
performance in cases where it encounters large numbers of unresolved
write intents.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
This is a nice change!

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-:-Mn83tPn7vrlqN2rPiZ7:bk3yvc6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go, line 765 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn806r8CfvfQG0oDgtT:-Mn806r8CfvfQG0oDgtU:b-sz44tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go#L765)):*
> ```Go
> 				})
> 
> 				// Add in a write intent.
> ```

"two write intents"
___
*[pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go, line 779 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn808MtC_pqRQxAGO84:-Mn808MtC_pqRQxAGO85:bv4y3xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go#L779)):*
> ```Go
> 					&txn,
> 				); err != nil {
> 					if !errors.HasType(err, (*roachpb.WriteIntentError)(nil)) {
> ```

Why do we allow `WriteIntentErrors` here? Don't we expect these intent writes to succeed?
___
*[pkg/kv/kvserver/spanset/batch.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn80qXJ-O26pJ-uN9vd:-Mn80qXJ-O26pJ-uN9ve:bqdfgm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/kv/kvserver/spanset/batch.go#L218)):*
> ```Go
> // CheckForKeyCollisions is part of the storage.MVCCIterator interface.
> func (i *MVCCIterator) CheckForKeyCollisions(
> 	sstData []byte, start, end roachpb.Key, maxIntents int64,
> ```

nit: should we rename this to `maxIntentCount` to mirror the `pebbleExportToSst` parameter?
___
*[pkg/storage/engine.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn83V5c0CeXPJxyfpOZ:-Mn83V5c0CeXPJxyfpO_:b-py5ym6) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/storage/engine.go#L182)):*
> ```Go
> 	// and the encoded SST data specified, within the provided key range.
> 	// maxIntents specifies the number of intents to collect and return in a
> 	// WriteIntentError. Returns stats on skipped KVs, or an error if a collision
> ```

Let's add a mention of what a caller should pass if it doesn't want to limit the number of intents. I think that's `math.MaxInt64`. It would be a shame if a caller passed 0 and thought it was getting that behavior (like it does elsewhere).
___
*[pkg/storage/engine.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn812wxBbUNj6qqNIp5:-Mn812wxBbUNj6qqNIp6:bpoodcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/storage/engine.go#L184)):*
> ```Go
> 	// WriteIntentError. Returns stats on skipped KVs, or an error if a collision
> 	// is found.
> 	CheckForKeyCollisions(sstData []byte, start, end roachpb.Key, maxIntents int64) (enginepb.MVCCStats, error)
> ```

It's interesting that this limit is part of the `MVCCIterator` interface. The corresponding limit on `ExportMVCCToSst` is not part of the `Reader` interface. Instead, we check the cluster setting internally. Is the reason for this difference that `MVCCIterator` implementations don't have direct access to the cluster settings?

FWIW I think pushing this decision to the caller (who can check cluster settings if it wants) instead of implicitly checking the cluster settings internally is cleaner. How about you? Maybe we should update `ExportMVCCToSst` after this to follow this same pattern.
___
*[pkg/storage/engine_test.go, line 1076 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn83n1s1Q14qDmBgjIm:-Mn83n1s1Q14qDmBgjIn:b91qqpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/storage/engine_test.go#L1076)):*
> ```Go
> 					require.Error(t, err)
> 					writeIntentErr := &roachpb.WriteIntentError{}
> 					require.ErrorAs(t, err, &writeIntentErr)
> ```

Woah, TIL.
___
*[pkg/storage/mvcc.go, line 4181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn82MH51cEztJdDXukT:-Mn82MH51cEztJdDXukU:bnr0hxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/storage/mvcc.go#L4181)):*
> ```Go
> ) (enginepb.MVCCStats, error) {
> 	var skippedKVStats enginepb.MVCCStats
> 	var writeIntentErr = new(roachpb.WriteIntentError)
> ```

Do we want to pay this heap allocation cost if we don't end up hitting any intents? Maybe we should replace this with `var intents []roachpb.Intent` and then only construct the `*roachpb.WriteIntentError` on the `len(intents) > 0` paths.
___
*[pkg/storage/mvcc.go, line 4216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn82kBI8DWWZUAz_lct:-Mn82kBI8DWWZUAz_lcu:b-5asd5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/storage/mvcc.go#L4216)):*
> ```Go
> 			} else if mvccMeta.Txn != nil {
> 				// Check for a write intent. We keep looking for additional intents to
> 				// return a large batch for intent resolution.
> ```

Consider adding one more sentence that alludes to why a large batch is beneficial to higher levels of the stack.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72042)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @nvanbenschoten)

___
*[pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go, line 779 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn808MtC_pqRQxAGO84:-Mn9jLXBEbrA1JNcwINO:b-oxim5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go#L779)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why do we allow `WriteIntentErrors` here? Don't we expect these intent writes to succeed?
</blockquote></details>

Figured it was there for a reason, but looks like it's been there since the test was written, and it passes just fine without them. Removed.
___
*[pkg/kv/kvserver/spanset/batch.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn80qXJ-O26pJ-uN9vd:-Mn9mQ0A1zVV0k16BN3W:bp0hi8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/kv/kvserver/spanset/batch.go#L218)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: should we rename this to `maxIntentCount` to mirror the `pebbleExportToSst` parameter?
</blockquote></details>

I ended up moving the `pebbleExportToSst` parameter into `ExportOptions.MaxIntents`, which is consistent with `ScanOptions.MaxIntents`, so I've kept `maxIntents` here.
___
*[pkg/storage/engine.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn83V5c0CeXPJxyfpOZ:-Mn9mdxh6ZUoH6EQzp28:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/storage/engine.go#L182)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's add a mention of what a caller should pass if it doesn't want to limit the number of intents. I think that's `math.MaxInt64`. It would be a shame if a caller passed 0 and thought it was getting that behavior (like it does elsewhere).
</blockquote></details>

Good call, done.
___
*[pkg/storage/engine.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn812wxBbUNj6qqNIp5:-Mn9wSCGCmzBsMsyLMO3:b-sc2z2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/storage/engine.go#L184)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's interesting that this limit is part of the `MVCCIterator` interface. The corresponding limit on `ExportMVCCToSst` is not part of the `Reader` interface. Instead, we check the cluster setting internally. Is the reason for this difference that `MVCCIterator` implementations don't have direct access to the cluster settings?

FWIW I think pushing this decision to the caller (who can check cluster settings if it wants) instead of implicitly checking the cluster settings internally is cleaner. How about you? Maybe we should update `ExportMVCCToSst` after this to follow this same pattern.
</blockquote></details>

I agree, passing it explicitly is clearer. Added on a commit which moves it to `ExportOptions.MaxIntents`.
___
*[pkg/storage/mvcc.go, line 4181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-Mn82MH51cEztJdDXukT:-Mn9nKy_Ek4FLWmYKcT2:b-fuqtjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/78ddfedace0611f54c4a48a9bc8da376f5b06003/pkg/storage/mvcc.go#L4181)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to pay this heap allocation cost if we don't end up hitting any intents? Maybe we should replace this with `var intents []roachpb.Intent` and then only construct the `*roachpb.WriteIntentError` on the `len(intents) > 0` paths.
</blockquote></details>

I figured this cost would be negligible since we're paying it once per `AddSSTable` request, but might as well avoid it. Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72042#-:-MnBv8mv-pLOvXudBnKe:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Comment by erikgrinaker** [comment]
Backporting this to 20.2 will be a bit more involved, since we'll have to implement this for RocksDB in C++. I suggest we drop it, at least until we get reports of users experiencing issues with this.

**Comment by nvanbenschoten** [comment]
We backported https://github.com/cockroachdb/cockroach/pull/64931 to v20.2, but it doesn't look like that made it to the RocksDB code. I think that's fine, as RocksDB is off-by-default in v20.2. If it's easy enough, I think you follow that model and backport this only for the Pebble engine in v20.2. Or you can skip the v20.2 backport entirely for now, as we haven't heard of users running into this.

**Comment by erikgrinaker** [comment]
Turns out #65465 wasn't backported, so we'd have to either backport that too or migrate the old cluster setting `storage.sst_export.max_intents_per_error` etc. I'm going to skip the 20.2 backport for now.

**Pull request merged**
