### PR TITLE
workload: add "gentle" chaos to tpccbench

### LINKED ISSUE #26387: roachtest: add new "gentle" chaos mode
https://github.com/cockroachdb/cockroach/issues/24279 added basic chaos testing to roachtest, where nodes are killed without warning. We should extend this approach with an option for "gentle" chaos, where a node is drained before being killed.

I foresee this being implemented as an option on the `Chaos` struct introduced in https://github.com/cockroachdb/cockroach/pull/25427.

### PR DESCRIPTION
**Pull request by m-schneider**
Before we used the roachprod stop command to stop cockroach for our
chaos scenarios, which is a kill -9. Now for chaos we'll have an option
to do a gracefull drain of the node.

Closes #26387

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/cmd/roachtest/chaos.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElAIvY-5HCxCvowBNp:-LElAIva1Hmm_skaZhLI:b1qrpmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/chaos.go#L77)):*
> ```Go
> 			if ch.DrainAndQuit {
> 				l.printf("stopping and draining %v (slept %s)\n", target, before)
> 				c.Run(ctx, target, `pkill cockroach`)
> ```

I was expecting `cockroach quit`, but I guess this works.

---

*[pkg/cmd/roachtest/chaos.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElAMCVCgk4d7g9yjAj:-LElAMCVCgk4d7g9yjAk:bwv2hzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/chaos.go#L78)):*
> ```Go
> 				l.printf("stopping and draining %v (slept %s)\n", target, before)
> 				c.Run(ctx, target, `pkill cockroach`)
> ```

Odd new line here.

---

*[pkg/cmd/roachtest/tpcc.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElASP21T_NwQ4GC5js:-LElASP21T_NwQ4GC5jt:b-csf7f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/tpcc.go#L33)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/search"
> 	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
> 	"math"
> ```

Move that up to the rest of the stdlib imports.

---

*[pkg/cmd/roachtest/tpcc.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElARjl98Riw-c5k8cp:-LElARjl98Riw-c5k8cq:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/tpcc.go#L260)):*
> ```Go
> 		// warehouses that can be operated on while sustaining a throughput
> 		// threshold, set to a fraction of max tpmC.
> 		precision := int(math.Max(1.0, float64(b.LoadWarehouses/200)))
> ```

Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-:-LElAYCF4mrxizz2Uehr:bnfp4nl)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/cmd/roachtest/chaos.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElAIvY-5HCxCvowBNp:-LEnGnB_Cz6GpQv6uw78:bouxqzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/chaos.go#L77)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I was expecting `cockroach quit`, but I guess this works.
</blockquote></details>

It's less than ideal because it'll indiscriminately kill any cockroach process. This won't work locally! Please use `./cockroach quit`. (On a related note, it *is* interesting to gracefully terminate the process to check that it does the right thing, but you need to target the PID directly and that's a bit of work to set up).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26609)*

**Comment by petermattis** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/cmd/roachtest/chaos.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElAIvY-5HCxCvowBNp:-LEoEZIA1VM0wFvH7YeY:b-8sdb9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/chaos.go#L77)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

It's less than ideal because it'll indiscriminately kill any cockroach process. This won't work locally! Please use `./cockroach quit`. (On a related note, it *is* interesting to gracefully terminate the process to check that it does the right thing, but you need to target the PID directly and that's a bit of work to set up).
</blockquote></details>

`roachprod` knows how to find the cockroach process for a specific local node. We could expose that if desired. One way to almost achieve this already is to start cockroach with a specific tag (`roachprod start --tag foo`) and then you can use `roachprod stop --tag foo <cluster>:<node>` to stop all of the processes with that tag on the specified nodes. The one additional piece we'd have to add is that `stop` uses `kill -9` by default. Adding a flag to use a different signal would be easy.

Note that if you use `cockroach quit`, you'll want to specify the port. Something like `cockroach quit {pgport:<target>}`. Otherwise, the `quit` will be sent to the default port which won't do the right thing locally either. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26609)*

**Comment by m-schneider** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/cmd/roachtest/chaos.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElAIvY-5HCxCvowBNp:-LEoTEpkEtyy3GqE04bR:b-z3vrae) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/chaos.go#L77)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`roachprod` knows how to find the cockroach process for a specific local node. We could expose that if desired. One way to almost achieve this already is to start cockroach with a specific tag (`roachprod start --tag foo`) and then you can use `roachprod stop --tag foo <cluster>:<node>` to stop all of the processes with that tag on the specified nodes. The one additional piece we'd have to add is that `stop` uses `kill -9` by default. Adding a flag to use a different signal would be easy.

Note that if you use `cockroach quit`, you'll want to specify the port. Something like `cockroach quit {pgport:<target>}`. Otherwise, the `quit` will be sent to the default port which won't do the right thing locally either. 
</blockquote></details>

Tobi, our docs actually suggest using pkill cockroach to kill it locally and I tested to make sure it works  with the chaos flag set by looking at running processes on the hosts and log files. `./cockroach quit` didn't actually do anything because as Peter mentioned you need to pass it the correct port. 

Maybe we should add a shutdown method to roachprod to be more explicit about what it does? I can send that out later today.

---

*[pkg/cmd/roachtest/chaos.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElAMCVCgk4d7g9yjAj:-LEoTxiY91j-bVlCYgKk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/chaos.go#L78)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Odd new line here.
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/tpcc.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElASP21T_NwQ4GC5js:-LEoV_MSDhepjAaCOFFK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/tpcc.go#L33)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Move that up to the rest of the stdlib imports.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26609)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/cmd/roachtest/chaos.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElAIvY-5HCxCvowBNp:-LEopVdHEOqN5hub1hDF:bgdgmso) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/chaos.go#L77)):*
> Tobi, our docs actually suggest using pkill cockroach to kill it locally and I tested to make sure it works  with the chaos flag set by looking at running processes on the hosts and log files.

Our docs might suggest that to kill *all* local instances of cockroach. It definitely will not do what you want if used as in this PR right now.

```
[tschottdorf@toblerone cockroach (fix/cmdq-dump)]$ pgrep cockroach
24031
24087
24291
[tschottdorf@toblerone cockroach (fix/cmdq-dump)]$ pkill cockroach
initiating graceful shutdown of server
initiating graceful shutdown of server
initiating graceful shutdown of server
```

> ./cockroach quit didn't actually do anything because as Peter mentioned you need to pass it the correct port.

But why not just pass it in? See

https://github.com/cockroachdb/cockroach/blob/b6d56983fe4166d3f12c2af0bbfe4438ac9a3aaa/pkg/cmd/roachtest/version.go#L142

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26609)*

**Comment by m-schneider** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/cmd/roachtest/chaos.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-LElAIvY-5HCxCvowBNp:-LFONz8s1NTI6YYy0gam:bb6byw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0855e16ea9cbbef6894f8b23d6fe52b9252ce7e/pkg/cmd/roachtest/chaos.go#L77)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> Tobi, our docs actually suggest using pkill cockroach to kill it locally and I tested to make sure it works  with the chaos flag set by looking at running processes on the hosts and log files.

Our docs might suggest that to kill *all* local instances of cockroach. It definitely will not do what you want if used as in this PR right now.

```
[tschottdorf@toblerone cockroach (fix/cmdq-dump)]$ pgrep cockroach
24031
24087
24291
[tschottdorf@toblerone cockroach (fix/cmdq-dump)]$ pkill cockroach
initiating graceful shutdown of server
initiating graceful shutdown of server
initiating graceful shutdown of server
```

> ./cockroach quit didn't actually do anything because as Peter mentioned you need to pass it the correct port.

But why not just pass it in? See

https://github.com/cockroachdb/cockroach/blob/b6d56983fe4166d3f12c2af0bbfe4438ac9a3aaa/pkg/cmd/roachtest/version.go#L142

</blockquote></details>

Updated using signal 15.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26609)*

**Comment by m-schneider** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26609#-:-LFSk9Hx25k4Qyc018wK:b-ydi9ay)*

**Pull request merged**
