### PR TITLE
builtins: implement encrypt and decrypt pgcrypto functions

### PR DESCRIPTION
**Pull request by andyyang890**
This patch implements `encrypt`, `encrypt_iv`, `decrypt`,
and `decrypt_iv` from pgcrypto. These functions require an
enterprise license on a CCL distribution.

Performance benchmarks:

**Apple M1 Pro Macbook Pro**
```
==================== Test output for //pkg/ccl/pgcryptoccl/pgcryptocipherccl:pgcryptocipherccl_test:
goos: darwin
goarch: arm64
BenchmarkEncrypt
BenchmarkEncrypt/AES-128_with_IV
BenchmarkEncrypt/AES-128_with_IV-10         	  201392	      5883 ns/op
BenchmarkEncrypt/AES-192
BenchmarkEncrypt/AES-192-10                 	  195708	      6047 ns/op
BenchmarkEncrypt/AES-192_with_IV
BenchmarkEncrypt/AES-192_with_IV-10         	  195644	      6095 ns/op
BenchmarkEncrypt/AES-256
BenchmarkEncrypt/AES-256-10                 	  189553	      6250 ns/op
BenchmarkEncrypt/AES-256_with_IV
BenchmarkEncrypt/AES-256_with_IV-10         	  188533	      6429 ns/op
BenchmarkEncrypt/AES-128
BenchmarkEncrypt/AES-128-10                 	  204352	      5830 ns/op
BenchmarkDecrypt
BenchmarkDecrypt/AES-128
BenchmarkDecrypt/AES-128-10                 	1000000000	         0.0000165 ns/op
BenchmarkDecrypt/AES-128_with_IV
BenchmarkDecrypt/AES-128_with_IV-10         	1000000000	         0.0000154 ns/op
BenchmarkDecrypt/AES-192
BenchmarkDecrypt/AES-192-10                 	1000000000	         0.0000133 ns/op
BenchmarkDecrypt/AES-192_with_IV
BenchmarkDecrypt/AES-192_with_IV-10         	1000000000	         0.0000131 ns/op
BenchmarkDecrypt/AES-256
BenchmarkDecrypt/AES-256-10                 	1000000000	         0.0000170 ns/op
BenchmarkDecrypt/AES-256_with_IV
BenchmarkDecrypt/AES-256_with_IV-10         	1000000000	         0.0000240 ns/op
```

**GCE n1-standard-1**
```
==================== Test output for //pkg/ccl/pgcryptoccl/pgcryptocipherccl:pgcryptocipherccl_test:
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) CPU @ 2.30GHz
BenchmarkEncrypt
BenchmarkEncrypt/AES-256
BenchmarkEncrypt/AES-256                   66396             17984 ns/op
BenchmarkEncrypt/AES-256_with_IV
BenchmarkEncrypt/AES-256_with_IV           63297             18224 ns/op
BenchmarkEncrypt/AES-128
BenchmarkEncrypt/AES-128                   69272             17372 ns/op
BenchmarkEncrypt/AES-128_with_IV
BenchmarkEncrypt/AES-128_with_IV           69180             17315 ns/op
BenchmarkEncrypt/AES-192
BenchmarkEncrypt/AES-192                   68107             17619 ns/op
BenchmarkEncrypt/AES-192_with_IV
BenchmarkEncrypt/AES-192_with_IV           67282             17655 ns/op
BenchmarkDecrypt
BenchmarkDecrypt/AES-256_with_IV
BenchmarkDecrypt/AES-256_with_IV        1000000000               0.0000346 ns/op
BenchmarkDecrypt/AES-128
BenchmarkDecrypt/AES-128                1000000000               0.0000321 ns/op
BenchmarkDecrypt/AES-128_with_IV
BenchmarkDecrypt/AES-128_with_IV        1000000000               0.0000316 ns/op
BenchmarkDecrypt/AES-192
BenchmarkDecrypt/AES-192                1000000000               0.0000319 ns/op
BenchmarkDecrypt/AES-192_with_IV
BenchmarkDecrypt/AES-192_with_IV        1000000000               0.0000372 ns/op
BenchmarkDecrypt/AES-256
BenchmarkDecrypt/AES-256                1000000000               0.0000377 ns/op
```

**GCE n2-standard-2**
```
==================== Test output for //pkg/ccl/pgcryptoccl/pgcryptocipherccl:pgcryptocipherccl_test:
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) CPU @ 2.80GHz
BenchmarkEncrypt
BenchmarkEncrypt/AES-128
BenchmarkEncrypt/AES-128-2                 82330             12522 ns/op
BenchmarkEncrypt/AES-128_with_IV
BenchmarkEncrypt/AES-128_with_IV-2         96104             12442 ns/op
BenchmarkEncrypt/AES-192
BenchmarkEncrypt/AES-192-2                 94000             12687 ns/op
BenchmarkEncrypt/AES-192_with_IV
BenchmarkEncrypt/AES-192_with_IV-2         95246             12635 ns/op
BenchmarkEncrypt/AES-256
BenchmarkEncrypt/AES-256-2                 93202             12871 ns/op
BenchmarkEncrypt/AES-256_with_IV
BenchmarkEncrypt/AES-256_with_IV-2         91792             13099 ns/op
BenchmarkDecrypt
BenchmarkDecrypt/AES-256_with_IV
BenchmarkDecrypt/AES-256_with_IV-2      1000000000               0.0000527 ns/op
BenchmarkDecrypt/AES-128
BenchmarkDecrypt/AES-128-2              1000000000               0.0000507 ns/op
BenchmarkDecrypt/AES-128_with_IV
BenchmarkDecrypt/AES-128_with_IV-2      1000000000               0.0000502 ns/op
BenchmarkDecrypt/AES-192
BenchmarkDecrypt/AES-192-2              1000000000               0.0000552 ns/op
BenchmarkDecrypt/AES-192_with_IV
BenchmarkDecrypt/AES-192_with_IV-2      1000000000               0.0000518 ns/op
BenchmarkDecrypt/AES-256
BenchmarkDecrypt/AES-256-2              1000000000               0.0000533 ns/op
```

Informs #21001

Release note (enterprise change): The pgcrypto functions `encrypt`,
`encrypt_iv`, `decrypt`, and `decrypt_iv` are now implemented.
These functions require an enterprise license on a CCL distribution.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
the code looks great! just want to make sure we have the right testing

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-:-NZDESl37db7cjBqiPM2:b-qjaybu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/sql/sem/builtins/pgcrypto/pgcryptocipher/cipher.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-NZDDjam0I7yVPvQQInK:-NZDDjam0I7yVPvQQInL:b83qp94) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804c5963bd5d117eeefc7ae86d7662ec01e2e8d/pkg/sql/sem/builtins/pgcrypto/pgcryptocipher/cipher.go#L23)):*
> ```Go
> )
> 
> func Encrypt(data []byte, key []byte, iv []byte, cipherType string) ([]byte, error) {
> ```

nit: need comments on the public functions
___
*[`pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins` line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-NZDE-iA7C8CnTPn1nTR:-NZDE-iA7C8CnTPn1nTS:b-ojsh3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804c5963bd5d117eeefc7ae86d7662ec01e2e8d/pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins#L363)):*
> ```
> ----
> abc
> ```

nit: put `subtest end` at the end of each subtest
___
*[`pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins` line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-NZDELuw4wktLOZm77j7:-NZDELuw4wktLOZm77j8:bk15ot3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804c5963bd5d117eeefc7ae86d7662ec01e2e8d/pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins#L385)):*
> ```
> 
> query error pgcode 22023 data has length 3, which is not a multiple of block size 16
> SELECT encrypt('abc', 'key', 'aes/pad:none')
> ```

i ran this in postgres and it worked:
```
postgres=> SELECT encrypt('abc', 'key', 'aes/pad:none');
              encrypt
------------------------------------
 \xa77d1248c32aa0a820527b04d22703c2
```

let's make sure all the tests here match the PG behavior
___
*[`pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins` line 411 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-NZDDvEX7Du_ERox6mgX:-NZDDvEX7Du_ERox6mgY:bni2xta) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804c5963bd5d117eeefc7ae86d7662ec01e2e8d/pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins#L411)):*
> ```
> 
> query error pgcode 22023 data has length 3, which is not a multiple of block size 16
> SELECT decrypt('abc', 'key', 'aes/pad:none')
> ```

just curious, were you able to find any tests in the postgres source code?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/pgcrypto/pgcryptocipher/cipher.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-NZDDjam0I7yVPvQQInK:-N_2WnZD5XEnZ-PykOIi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804c5963bd5d117eeefc7ae86d7662ec01e2e8d/pkg/sql/sem/builtins/pgcrypto/pgcryptocipher/cipher.go#L23)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: need comments on the public functions
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins` line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-NZDE-iA7C8CnTPn1nTR:-N_2Wp4g2Sk6lV0J4tAk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804c5963bd5d117eeefc7ae86d7662ec01e2e8d/pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins#L363)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: put `subtest end` at the end of each subtest
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins` line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-NZDELuw4wktLOZm77j7:-N_2Wptk7ls_1NlYk3MB:b-tpab8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804c5963bd5d117eeefc7ae86d7662ec01e2e8d/pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins#L385)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i ran this in postgres and it worked:
```
postgres=> SELECT encrypt('abc', 'key', 'aes/pad:none');
              encrypt
------------------------------------
 \xa77d1248c32aa0a820527b04d22703c2
```

let's make sure all the tests here match the PG behavior
</blockquote></details>

Interesting, when I run it on Postgres (version 15.1), I get:
```
postgres=# SELECT encrypt('abc', 'key', 'aes/pad:none');
ERROR:  encrypt error: Encryption failed
```
___
*[`pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins` line 411 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-NZDDvEX7Du_ERox6mgX:-N_2XA3k-2mqCs_D7Icn:b-rxywvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804c5963bd5d117eeefc7ae86d7662ec01e2e8d/pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins#L411)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just curious, were you able to find any tests in the postgres source code?
</blockquote></details>

Yeah, I found this test file: https://github.com/postgres/postgres/blob/19508f4763b6e55baae788af000ee47e74d24370/contrib/pgcrypto/sql/rijndael.sql

and associated output file:
https://github.com/postgres/postgres/blob/19508f4763b6e55baae788af000ee47e74d24370/contrib/pgcrypto/expected/rijndael.out

It seems to mostly be a sanity check like our logic tests.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins` line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-NZDELuw4wktLOZm77j7:-N_6C2TOD2wpq6qJg2c5:bw5zd6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804c5963bd5d117eeefc7ae86d7662ec01e2e8d/pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins#L385)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Interesting, when I run it on Postgres (version 15.1), I get:
```
postgres=# SELECT encrypt('abc', 'key', 'aes/pad:none');
ERROR:  encrypt error: Encryption failed
```
</blockquote></details>

hmm. we should probably find out why this behavior changed between PG versions.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins` line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-NZDELuw4wktLOZm77j7:-N_uquZG-ACL8ALE7i2A:banw57g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d804c5963bd5d117eeefc7ae86d7662ec01e2e8d/pkg/sql/logictest/testdata/logic_test/pgcrypto_builtins#L385)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hmm. we should probably find out why this behavior changed between PG versions.
</blockquote></details>

Looks like this case was fixed in Postgres 15 by this commit https://github.com/postgres/postgres/commit/f5576a21b0778f275d7418f6f7a44d9400ee90aa

**Review by rafiss — APPROVED** [review]
really nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-:-NdaVlit6DAsrCFjO5zf:b-tqdyb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`-- commits` line 18 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-Ndagp7S3aeoP3pimkjk):*
super nit: mention that they are CCL only. also, i think we should use `enterprise change` instead of `sql change` https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#Categories

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 18 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/105654#-Ndagp7S3aeoP3pimkjk):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: mention that they are CCL only. also, i think we should use `enterprise change` instead of `sql change` https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#Categories
</blockquote></details>

Done!

**Comment by andyyang890** [comment]
tftr!

bors r=rafiss

**Pull request merged**
