### PR TITLE
kvclient: remove SendError from ErrorDetails

### PR DESCRIPTION
**Pull request by andreimatei**
This patch take SendError out of the ErrorDetails. In fact, the error is
no longer a proto at all.
The SendError is used for communicating between layers of the
DistSender - one layers tells another that the descriptor that was used
appears to be stale. Since its not coming from the kvserver, it doesn't
need to be a proto - and it shouldn't be. To be able to change the
error, I has to collapse things around in the DistSender. The
refactoring there is about removing a function that was a fairly useless
layer in an RPCs path.

The DistSender refactoring is actually how I got here. I'm trying to
shift code around to rationalize the way the leaseholder cache and the
range desc cache are updated. As it stands, the code is really hard to
follow because updates to the cache happen in multiple places and the
flow of the errors that cause these updates is hard to track. The
collapsing of the layers in this patch and a prior commit helps, and
I'll have more to say about it in an upcoming PR that merges the range
descriptor cache and the leaseholder cache.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
LGTM but I did not look at the `wip` commit at the end.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 12 of 12 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-:-M92yGs3DDLHoBpmSvlq:b-own5ue)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 535 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92nmYsDHO5Vno2W95n:-M92nmYsDHO5Vno2W95o:bti9m6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7a903d797bdc8a3bb6b135d86910d2307cb812/pkg/kv/kvclient/kvcoord/dist_sender.go#L535)):*
> ```Go
> 	// only to the `Voters` replicas. This is just an optimization to save a
> 	// network hop, everything would still work if we had `All` here.
> 	replicas := NewReplicaSlice(ds.gossip, desc.Replicas().Voters())
> ```

How about having `NewReplicaSlice` return an error in this case? It seems that all three callers would be happy about that.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1358 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92qSx4C6n1sON6ZonJ:-M92qSx4C6n1sON6ZonK:bwgmklv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1358)):*
> ```Go
> 		if err != nil {
> 			// Set pErr so that, if we don't perform any more retries, the
> 			// deduceRetryEarlyExitError() call below the loop is inhibited.
> ```

I just looked at that code in `deduceRetryEarlyExitError` - don't we possibly need to return an ambiguous result in the `Closer` case?
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1367 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92r2LyAH54S3GLLcvP:-M92r2LyAH54S3GLLcvQ:b-golgsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1367)):*
> ```Go
> 				// though it might have succeeded the first time around because of
> 				// idempotency.
> 				log.VEventf(ctx, 1, "evicting range descriptor on %T and backoff for re-lookup: %+v", err, desc)
> ```

`%T` will be useless now, also `%+v `is not a great way to print `desc`, just use `%s`, how about

`log.Veventf(ctx, 1, "evicting %s after %s", desc, err)`
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1591 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92rTgB8Df5dxLh90mj:-M92rTgB8Df5dxLh90mk:b-anqyq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1591)):*
I'd rearrange this whole comment a bit. For example, this paragraph needs to be before the preceding one. Attempt:


> sendToReplicas sends a batch to the replicas in desc. Replicas a tried oneat a time (generally the leaseholder first). The result of this call is either a BatchResponse or an error. In the former case, the BatchResponse wraps either a response or a `*roachpb.Error`; this error will come from a replica authorized to serve the request (for example ConditionFailedError) and can be seen as "data" returned from the request. In the latter case, DistSender was unable to reach a replica willing to serve the request, and the second return value is either a `sendError` or `AmbiguousResultError`. Of those two, the latter has to be passed back to the client, while the former should be handled by retrying with an updated range descriptor. This method handles other errors returned from replicas internally by retrying (NotLeaseholderError, RangeNotFoundError), and falls back to a sendError when it runs out of replicas to try.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1675 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92t3_m5uviepUy5-6t:-M92t3_m5uviepUy5-6u:blulu4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1675)):*
> ```Go
> 	var ambiguousError error
> 
> 	noMoreReplicasErr := func(br *roachpb.BatchResponse, err error) error {
> ```

Mind lifting this to be a named function that additionally takes `replicas` and `ambiguousError` as params instead of closing over them? The use of the closure here adds cognitive complexity.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1809 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92uHQQ9AS9Yw_oy80z:-M92uHQRBPuLTq5iYI1N:b-kj4inc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1809)):*
> ```Go
> 					// If the implicated leaseholder is not a known replica, return a sendError
> 					// to signal eviction of the cached RangeDescriptor and re-send.
> 					if replicas.FindReplica(lh.StoreID) == -1 {
> ```

If we had a replica that was still a member of the desc but not catching up (and far behind) we could repeatedly hit this. This could happen during a network partition, for example. A DistSender close to a replica in the minority may never try one of the replicas on the healthy side of the partition. Hmm, but additionally the healthy side would've had to move the old leaseholder out of the descriptor already. Ok, this is probably fine (it's also automatically fine as it was the status quo before you touched this as well).
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1839 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92vJThDF_vMXEKJma5:-M92vJThDF_vMXEKJma6:b-ah7f7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1839)):*
> ```Go
> 			}
> 
> 			if propagateError {
> ```

Can't you inline this into the `default:` branch now and simplify the flow by removing the `propagateError` bool?
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1884 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92qsnzCqTHWN139y9x:-M92qsnzCqTHWN139y9y:b-kphyt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1884)):*
> ```Go
> // This error is produced by the DistSender. Note that the DistSender generates
> // AmbiguousResultError instead of sendError when there's an EndTxn(commit) in
> // the BatchRequest. But also note that the sever can return
> ```

server
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1892 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92quKy9s5NPbJP_ptP:-M92quKy9s5NPbJP_ptQ:b-egouf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1892)):*
> ```Go
> }
> 
> // newSendError creates a SendError.
> ```

sendError

**Review by andreimatei — COMMENTED** [review]
> LGTM but I did not look at the wip commit at the end.

Don't worry about the wip, it was just about transitioning some error type asserts to the form that the linters like.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-:-M9K_HpE62K1DpxTgGRr:b-1r7j66)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 535 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92nmYsDHO5Vno2W95n:-M9JtmnD0oOtkdZS-Mrt:b-nj2nb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c7a903d797bdc8a3bb6b135d86910d2307cb812/pkg/kv/kvclient/kvcoord/dist_sender.go#L535)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

How about having `NewReplicaSlice` return an error in this case? It seems that all three callers would be happy about that.
</blockquote></details>

good idea; done. This required me to tweak `NewReplicaSlice` a bit more, but it's all for the better.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1358 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92qSx4C6n1sON6ZonJ:-M9JxErP1xfb1xYPVesr:biobibr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1358)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I just looked at that code in `deduceRetryEarlyExitError` - don't we possibly need to return an ambiguous result in the `Closer` case?
</blockquote></details>

I don't think so... If there's any ambiguity, `sendToReplicas` will return `AmbiguousResultError` (if `withCommit`). If we get to `deduceRetryEarlyExitError`, it means that `sendToReplicas()` was not even called - in which case there's no ambiguity.
Right?
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1367 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92r2LyAH54S3GLLcvP:-M9JyeIx4vXrUfsgtGUs:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1367)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

`%T` will be useless now, also `%+v `is not a great way to print `desc`, just use `%s`, how about

`log.Veventf(ctx, 1, "evicting %s after %s", desc, err)`
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1591 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92rTgB8Df5dxLh90mj:-M9KYwfZ1Hq6Nrc_rdLD:b6761ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1591)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'd rearrange this whole comment a bit. For example, this paragraph needs to be before the preceding one. Attempt:


> sendToReplicas sends a batch to the replicas in desc. Replicas a tried oneat a time (generally the leaseholder first). The result of this call is either a BatchResponse or an error. In the former case, the BatchResponse wraps either a response or a `*roachpb.Error`; this error will come from a replica authorized to serve the request (for example ConditionFailedError) and can be seen as "data" returned from the request. In the latter case, DistSender was unable to reach a replica willing to serve the request, and the second return value is either a `sendError` or `AmbiguousResultError`. Of those two, the latter has to be passed back to the client, while the former should be handled by retrying with an updated range descriptor. This method handles other errors returned from replicas internally by retrying (NotLeaseholderError, RangeNotFoundError), and falls back to a sendError when it runs out of replicas to try.
</blockquote></details>

took your text with minor edits, and also left the paragraph for `withCommit`.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1675 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92t3_m5uviepUy5-6t:-M9K1Fib5b5n4tMfDgN1:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1675)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Mind lifting this to be a named function that additionally takes `replicas` and `ambiguousError` as params instead of closing over them? The use of the closure here adds cognitive complexity.
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1809 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92uHQQ9AS9Yw_oy80z:-M9K1QyX1rj4IIeveTnE:b-89ggbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1809)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

If we had a replica that was still a member of the desc but not catching up (and far behind) we could repeatedly hit this. This could happen during a network partition, for example. A DistSender close to a replica in the minority may never try one of the replicas on the healthy side of the partition. Hmm, but additionally the healthy side would've had to move the old leaseholder out of the descriptor already. Ok, this is probably fine (it's also automatically fine as it was the status quo before you touched this as well).
</blockquote></details>

Yeah... The code as written doesn't make a whole lot of sense. What we want is for `NotLeaseHolderError` to carry an updated descriptor too, whose generation we can compare to the descriptor we already have. It's coming.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1839 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92vJThDF_vMXEKJma5:-M9K79qY8ftJggieWKxb:b-pb9bue) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1839)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can't you inline this into the `default:` branch now and simplify the flow by removing the `propagateError` bool?
</blockquote></details>

indeed
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1884 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92qsnzCqTHWN139y9x:-M9K8Mh-5zj2EKKQT-l5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1884)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

server
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1892 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92quKy9s5NPbJP_ptP:-M9K8NJw5DUDtjQ1beVI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1892)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

sendError
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
> Reviewed 13 of 13 files at r7, 7 of 7 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 13 of 13 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49859)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1358 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-M92qSx4C6n1sON6ZonJ:-M9O1Ztl2TJzyrJJsZRv:bosaprn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08983bb1525e04d97c77db3236e9877de22393a/pkg/kv/kvclient/kvcoord/dist_sender.go#L1358)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think so... If there's any ambiguity, `sendToReplicas` will return `AmbiguousResultError` (if `withCommit`). If we get to `deduceRetryEarlyExitError`, it means that `sendToReplicas()` was not even called - in which case there's no ambiguity.
Right?
</blockquote></details>

Yep, you're right, thanks for explaining.

**Review by tbg — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-:-M9O1mfj2A-UxxdZ2hJc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, @nvanbenschoten, and @tbg)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49859#-:-M9OSiUE0jKGL95qTDR6:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, and @nvanbenschoten)

**Comment by andreimatei** [comment]
flaked on #49789

bors r+

**Pull request merged**
