### PR TITLE
engine: find split keys in the first range of a partition

### PR DESCRIPTION
**Pull request by benesch**
This deserves a roachtest—roachmart should make sure it has the correct number of ranges after inserting data—but I wanted to get this out for review ASAP.

---

MVCCFindSplitKey would previously fail to find any split keys in the
first range of a partition. As a result, partitioned tables have been
observed with multi-gigabyte ranges. This commit fixes the bug.

Specifically, MVCCFindSplitKey was assuming that the start key of a
range within a table was also the row prefix for the first row of data
in the range. This does not hold true for the first range of a table or
a partition of a table--that range begins at, for example, /Table/51,
while the row begins at /Table/51/1/aardvark. The old code had a special
case for the first range in a table, but not for the first range in a
partition. (It predates partitioning.)

Remove the need for special casing by actually looking in RocksDB to
determine the row prefix for the first row of data rather than
attempting to derive it from the range start key. This properly handles
partitioning and is robust against future changes to range split
boundaries.

See the commit within for more details on the approach.

Release note (bug fix): Ranges in partitioned tables now properly split
to respect their configured maximum size.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Oh wow, so there were three problems here, right?

1. MVCCFindSplitKey mistakes partition component for column family and will never split the first partition
1. Won't ever split a range with a large first row if there's more than one column family
1. creation of unnecessary empty range if StartKey is not actually present

:lgtm: 

> roachmart should make sure it has the correct number of ranges after inserting data

Perhaps the right test to insert this into is https://github.com/cockroachdb/cockroach/blob/ecb4801f2d708dcc8e22379ed2c4fdb78b8bec7b/pkg/cmd/roachtest/large_range.go#L94, you're just also going to have to import a fixture that has a large first partition. (large as in, larger than the final range size of 64MB so not really that large).

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 2536 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LANFtHlB6ASeXMVW_pc:-LANFtHlB6ASeXMVW_pd:bq49fy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5967a0e9842f5c029b36cc1f18c3dee55ad3e225/pkg/storage/engine/mvcc.go#L2536)):*
> ```Go
> 	minSplitKey := key
> 	// If this is a table, we can only split at row boundaries.
> 	if remainder, _, err := keys.DecodeTablePrefix(roachpb.Key(key)); err == nil {
> ```

And this didn't catch the partitioning case because in that case you first split off the empty range, so now the range in question begins at the first key in the first partition, and then your actual problem starts because that range isn't going to be split. Correct?

---

*[pkg/storage/engine/mvcc.go, line 2561 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LANG_6h-jTqU9ETMDA6:-LANG_6h-jTqU9ETMDA7:bfzn9bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4925c7931eea8a24bfb80a998d3bf3056bd3f796/pkg/storage/engine/mvcc.go#L2561)):*
> ; the right hand side of the split is then susceptible to never being split as outlined above.

---

*[pkg/storage/engine/mvcc.go, line 2580 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LANI-Yp9ckI9aB3upor:-LANI-Yr-eTfNMOFU5jV:bvaq979) ([raw file](https://github.com/cockroachdb/cockroach/blob/4925c7931eea8a24bfb80a998d3bf3056bd3f796/pkg/storage/engine/mvcc.go#L2580)):*
Could you add a comment here? Something like

> The first key in the range belongs to a SQL table, and so the found split key may as well. We can't split in the middle of a column family and will wind back the candidate key in that case before returning the key. To avoid rewinding all the way to the beginning of the range (which can happen if the first row in the table is large), ask that the returned split key puts at least the first column to the left of the split.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-:-LANH0_85YngQAcLCGNP:b-57dvyn)*

**Comment by a-robinson** [comment]
:lgtm: 

> 2. Won't ever split a range with a large first row if there's more than one column family

This had been previously fixed by https://github.com/cockroachdb/cockroach/pull/19339. The big problem here was the first one in your list. The third was an edge case with little downside that was called out in the unit tests.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 2536 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LANFtHlB6ASeXMVW_pc:-LAOCaIXEOy3Zqdm7dvS:bgt766s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5967a0e9842f5c029b36cc1f18c3dee55ad3e225/pkg/storage/engine/mvcc.go#L2536)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

And this didn't catch the partitioning case because in that case you first split off the empty range, so now the range in question begins at the first key in the first partition, and then your actual problem starts because that range isn't going to be split. Correct?
</blockquote></details>

No. The problem starts not because the range in question begins at the first key in the first partition. The problem starts because the range starts at a non-real prefix that is more than just the table prefix but less than a full valid row. It starts with a prefix of all the keys that will fall in the partition, meaning that `PrefixEnd()` will always be greater than any of the keys it contains.

---

*[pkg/storage/engine/mvcc.go, line 2580 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LAODYXe8mtV6yBMHVa6:-LAODYXe8mtV6yBMHVa7:b-ar9580) ([raw file](https://github.com/cockroachdb/cockroach/blob/4925c7931eea8a24bfb80a998d3bf3056bd3f796/pkg/storage/engine/mvcc.go#L2580)):*
> ```Go
> 	}
> 	minSplitKey := key
> 	if encoding.PeekType(it.UnsafeKey().Key) == encoding.Int {
> ```

I really wish there was a clearer way to express this than peeking for an int, but trust you that this is the best way.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-:-LAOCLPVDDgaYQZy3yd5:bscv1ko)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 2536 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LANFtHlB6ASeXMVW_pc:-LAOJvA59XBd4fgaNaYJ:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5967a0e9842f5c029b36cc1f18c3dee55ad3e225/pkg/storage/engine/mvcc.go#L2536)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

No. The problem starts not because the range in question begins at the first key in the first partition. The problem starts because the range starts at a non-real prefix that is more than just the table prefix but less than a full valid row. It starts with a prefix of all the keys that will fall in the partition, meaning that `PrefixEnd()` will always be greater than any of the keys it contains.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 2585 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LAOLP724J8Owpf-PPT5:-LAOLP724J8Owpf-PPT6:b-7zs1aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4925c7931eea8a24bfb80a998d3bf3056bd3f796/pkg/storage/engine/mvcc.go#L2585)):*
> ```Go
> 			return nil, err
> 		}
> 		minSplitKey = roachpb.RKey(firstRowKey.PrefixEnd())
> ```

If the c++ side falls back to the minSplitKey, does that mean we'll have splits at row prefix ends? This might be more complexity than we want, but prefix end is pretty ugly for some datum types. Would it make more sense to return the start of the second row?

---

*[pkg/storage/engine/mvcc_test.go, line 3448 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LAOMtp2Cmtd2zPP0T1P:-LAOMtp2Cmtd2zPP0T1Q:b-aqsd9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4925c7931eea8a24bfb80a998d3bf3056bd3f796/pkg/storage/engine/mvcc_test.go#L3448)):*
> ```Go
> 		rowKey := roachpb.Key(encoding.EncodeVarintAscending(append([]byte(nil), tableKey...), 1))
> 		for i, rowVal := range rowVals {
> 			rowKey = encoding.EncodeVarintAscending(rowKey, int64(i+1))
> ```

Is this right?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-:-LAOPWwC7_jNJjQnCVjB:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 2585 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LAOLP724J8Owpf-PPT5:-LAOSbSyBMm1wiqluEt-:b-l44z7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4925c7931eea8a24bfb80a998d3bf3056bd3f796/pkg/storage/engine/mvcc.go#L2585)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

If the c++ side falls back to the minSplitKey, does that mean we'll have splits at row prefix ends? This might be more complexity than we want, but prefix end is pretty ugly for some datum types. Would it make more sense to return the start of the second row?
</blockquote></details>

The C++ side doesn't fall back to minSplitKey, it just refuses to return a key less than minSplitKey

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-:-LAOWmHZ30ywF_THg420:bnfp4nl)*

**Comment by benesch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/storage/engine/mvcc.go, line 2561 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LANG_6h-jTqU9ETMDA6:-LAOTxbt1as06O99C0Dr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4925c7931eea8a24bfb80a998d3bf3056bd3f796/pkg/storage/engine/mvcc.go#L2561)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> ; the right hand side of the split is then susceptible to never being split as outlined above.
</blockquote></details>

Done.

---

*[pkg/storage/engine/mvcc.go, line 2580 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LAODYXe8mtV6yBMHVa6:-LAOU9Bs-5BDB6sro07B:bivlpmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4925c7931eea8a24bfb80a998d3bf3056bd3f796/pkg/storage/engine/mvcc.go#L2580)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I really wish there was a clearer way to express this than peeking for an int, but trust you that this is the best way.
</blockquote></details>

Heh, I just cargo-culted from the implementation of `keys.GetRowPrefixLength`. I switched it to checking that `keys.DecodeTablePrefix` does not return an error, like you had previously.

---

*[pkg/storage/engine/mvcc.go, line 2580 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LANI-Yp9ckI9aB3upor:-LAOoYb0CQE-6n89-fUr:b7d2p2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4925c7931eea8a24bfb80a998d3bf3056bd3f796/pkg/storage/engine/mvcc.go#L2580)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Could you add a comment here? Something like

> The first key in the range belongs to a SQL table, and so the found split key may as well. We can't split in the middle of a column family and will wind back the candidate key in that case before returning the key. To avoid rewinding all the way to the beginning of the range (which can happen if the first row in the table is large), ask that the returned split key puts at least the first column to the left of the split.
</blockquote></details>

Done, with a modification to instead reference the rationale in the big ol' comment above.

---

*[pkg/storage/engine/mvcc_test.go, line 3448 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896#-LAOMtp2Cmtd2zPP0T1P:-LAOUPOk9Abs6sDCYiaN:bgxqa3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4925c7931eea8a24bfb80a998d3bf3056bd3f796/pkg/storage/engine/mvcc_test.go#L3448)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Is this right?
</blockquote></details>

Ha! No it's not. I mean, it's encoding a valid primary key, but not the family key it's claiming to encode.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24896)*

**Comment by benesch** [comment]
bors r=tschottdorf,a-robinson,bdarnell,danhhz

**Comment by nvanbenschoten** [comment]
@benesch @jordanlewis is this a proper use of `PrefixEnd`? Will it work correctly with interleaved tables or will it cause all rows interleaved under the first row in a range to be unsplittable from it?

**Comment by benesch** [comment]
@nvanbenschoten I think you're 💯 right that this is busted. Let's discuss over on #30445?

**Pull request merged**
