### PR TITLE
vendor: bump Pebble to a24bc6c83054489b1bb0d9f53bcdd4ad8ec75977

### PR DESCRIPTION
**Pull request by sumeerbhola**
a24bc6c sstable: optimize seeks to use next
76afcca db: optimize levelIter for repeated seeks with narrow and monotonic bounds

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM, though @knz should speak up regarding the upgrade of `cockroachdb/errors`. Or you can figure out how to revert that portion of this bump.

**Review by sumeerbhola — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53208#-:-MFHIQIp444zQFM2bzGK:bb6un1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by petermattis — COMMENTED** [review]
I think @knz is already bumping `cockroachdb/redact` in #53199. Not sure if that also is fraught to upgrade here, but if we want to be really safe I'd leave it out of this PR. I'm curious why these bits are getting picked up. I thought there was a way to bump only a single dependency.

**Review by petermattis — APPROVED** [review]
LGTM

**Pull request merged**
