### PR TITLE
distsql: rename "simple flow" to "sync flow"

### PR DESCRIPTION
**Pull request by RaduBerinde**
The "simple" flow is an API which streams all the results as part of the call; it
is also used locally (when setting up a flow on the same machine). The name
"simple" is not accurate (and causes confusion with e.g. SimpleResponse);
renaming to "sync" flow.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10557)

### CODE REVIEW

**Comment by irfansharif** [comment]
Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsql/api.proto, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10557#-KW65BDWdN-ZnkW5bcnS:-KW65BDWdN-ZnkW5bcnT:b4jzczw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b261a2e7dfb5befb2badcae642df99c59261858f/pkg/sql/distsql/api.proto#L56)):*
> ```protobuf
>   // SetupFlow instantiates a flow (subgraps of a distributed SQL
>   // computation) on the receiving node.
>   rpc SetupFlow(SetupFlowRequest) returns (SimpleResponse) {}
> ```

are we still keeping this `SimpleResponse`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10557)*

**Comment by RaduBerinde** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsql/api.proto, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10557#-KW65BDWdN-ZnkW5bcnS:-KW66S9kYZ1JzNJ9Cmz4:b-mnbtpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b261a2e7dfb5befb2badcae642df99c59261858f/pkg/sql/distsql/api.proto#L56)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> are we still keeping this `SimpleResponse`?
</details>
Yeah that's part of the confusion, that's supposed to be "simple". It's not used only for sync flows. Maybe that could use a renaming as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10557)*

**Comment by RaduBerinde** [comment]
CC @andreimatei

**Comment by irfansharif** [comment]
:lgtm:

---

Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10557#-:-KW8JT8TNTgsOYO6abYd:bnfp4nl)*

**Pull request merged**
