### PR TITLE
ccl: move expression walking for IMPORT out of row converter and put it in exp_walker.go instead.

### PR DESCRIPTION
**Pull request by Anzoteh96**
When supporting default expressions for selected non-immutable functions, we not
only have to walk through the default expression to make sure that each
function expression is explicitly supported, but also follow our own overrides.
These code are originally in `row_converter.go` and could be extremely long as
other default expressions are supported later. This PR tries to address this issue
by moving it to a new file expr_walker.go within the `row` package.

Release note: None

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52086#-MDVC13S7aWQGZy0nFyL:-MDVC13S7aWQGZy0nFyM:b-bt09u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/076afc7270f9444cd991a8ab0fa5692fe1cbe28b/pkg/sql/row/expr_walker.go#L38)):*
> ```Go
> 	// cellInfoAddr is the address used to store relevant information
> 	// in the Annotation field of evalCtx when evaluating expressions.
> 	cellInfoAddr tree.AnnotationIdx = iota + 1
> ```

I would move this constant outside of const() block -- it's really unrelated to the volatility constants below.
___
*[pkg/sql/row/expr_walker.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52086#-MDVCGVj2Cl_Uht3XRtm:-MDVCGVj2Cl_Uht3XRtn:b-l4geln) ([raw file](https://github.com/cockroachdb/cockroach/blob/076afc7270f9444cd991a8ab0fa5692fe1cbe28b/pkg/sql/row/expr_walker.go#L112)):*
> ```Go
> // Besides overriding, there are also counters that we want to keep track
> // of as we walk through the expressions in a row (at datumRowConverter creation
> // time). This will be handled by the sideEffect field: it will be called with an
> ```

s/sideEffect/visitorSideEffect/

(you'll probably need to rewrap this comment if it gets too long).
___
*[pkg/sql/row/expr_walker.go, line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52086#-MDVCwW1-Pvbk7cfPoT5:-MDVCwW1-Pvbk7cfPoT6:b-rodo4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/076afc7270f9444cd991a8ab0fa5692fe1cbe28b/pkg/sql/row/expr_walker.go#L198)):*
> ```
> 	switch fn := expr.(type) {
> 	case *tree.FuncExpr:
> ```
while changing this code... do you think it makes sense to short circuit this switch (and outdent most of this function)?

i.e.

```
fn, ok := expr(.*tree.FuncExpr)
if !ok {
  return expr
}
.... rest of the code below without switch stmt
```

**Review by Anzoteh96 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52086#-MDVC13S7aWQGZy0nFyL:-MDWJjbR42bg2yacqYdF:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/076afc7270f9444cd991a8ab0fa5692fe1cbe28b/pkg/sql/row/expr_walker.go#L38)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would move this constant outside of const() block -- it's really unrelated to the volatility constants below.
</blockquote></details>

Done. 
___
*[pkg/sql/row/expr_walker.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52086#-MDVCGVj2Cl_Uht3XRtm:-MDWJl983JzUrpEDZSvN:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/076afc7270f9444cd991a8ab0fa5692fe1cbe28b/pkg/sql/row/expr_walker.go#L112)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

s/sideEffect/visitorSideEffect/

(you'll probably need to rewrap this comment if it gets too long).
</blockquote></details>

Done. 
___
*[pkg/sql/row/expr_walker.go, line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52086#-MDVCwW1-Pvbk7cfPoT5:-MDWJpfK8nrA3afmzhLm:b-7g3wmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/076afc7270f9444cd991a8ab0fa5692fe1cbe28b/pkg/sql/row/expr_walker.go#L198)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 	switch fn := expr.(type) {
> 	case *tree.FuncExpr:
> ```
while changing this code... do you think it makes sense to short circuit this switch (and outdent most of this function)?

i.e.

```
fn, ok := expr(.*tree.FuncExpr)
if !ok {
  return expr
}
.... rest of the code below without switch stmt
```
</blockquote></details>

Yeah that's a good idea, though I've made a step further in outdenting the code. Thoughts on how that turns out?

**Review by pbardea — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

**Review by miretskiy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @miretskiy)

___
*[pkg/sql/row/expr_walker.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52086#-MDWeCB1AXf47pUTL1bB:-MDWeCB1AXf47pUTL1bC:blhf78r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c5acd7a37d634f815c3fa8fe479d731b49a5d59/pkg/sql/row/expr_walker.go#L200)):*
> ```Go
> 	fn, ok := expr.(*tree.FuncExpr)
> 	if !ok || fn.ResolvedOverload().Volatility <= tree.VolatilityImmutable {
> 		return expr
> ```

I would just comment...
// If the expression is not a function expression, or it is not volatile, 
// then we can use this expression as is.

**Review by Anzoteh96 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/sql/row/expr_walker.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52086#-MDWeCB1AXf47pUTL1bB:-MDXExLlAssXt10ti_QB:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c5acd7a37d634f815c3fa8fe479d731b49a5d59/pkg/sql/row/expr_walker.go#L200)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would just comment...
// If the expression is not a function expression, or it is not volatile, 
// then we can use this expression as is.
</blockquote></details>

Done.

**Comment by Anzoteh96** [comment]
TFTR!

bors r+

**Pull request merged**
