### PR TITLE
execgen: extract template reading code

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, all template generators had to read their template file
themselves. Now, this is done by execgen main, opening the door to
global transforms that affect all templates in the same way.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 33 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-:-M8lvB53A2IHcItcvjXH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/execgen/cmd/execgen/const_gen.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8ltiGv6Id3mzjWkuqc:-M8ltiGwB1g_QLbQAbiI:b-ncbhhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/const_gen.go#L25)):*
> ```Go
> 
> func genConstOps(inputFile string, wr io.Writer) error {
> 	d, err := ioutil.ReadFile(constTmpl)
> ```

Leftover.
___
*[pkg/sql/colexec/execgen/cmd/execgen/hashjoiner_gen.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8ltwBi0ZwzeSvLmTaW:-M8ltwBi0ZwzeSvLmTaX:b-3f05wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/hashjoiner_gen.go#L21)):*
> ```Go
> 
> func genHashJoiner(inputFile string, wr io.Writer) error {
> 	s := inputFile
> ```

~I don't think this will work.~
___
*[pkg/sql/colexec/execgen/cmd/execgen/main.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8luZEv-SKfI8bCZsh1:-M8luZEv-SKfI8bCZsh2:br1lr1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/main.go#L53)):*
> ```Go
> // generator is a func that, given an input file's contents as a string,
> // outputs the result of execgen to the outputFile.
> type generator func(inputFile string, outputFile io.Writer) error
> ```


I misunderstood the meaning of `inputFile` - I thought it was "input filename" but it is "input file contents". I'd `s/inputFile/inputFileContents/g` for clarity.
___
*[pkg/sql/colexec/execgen/cmd/execgen/rank_gen.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8lurrU1b0Z9WbbDQ4a:-M8lurrU1b0Z9WbbDQ4b:bvvcm3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/rank_gen.go#L62)):*
> ```Go
> 
> func genRankOps(inputFile string, wr io.Writer) error {
> 	s := strings.ReplaceAll(inputFile, "_RANK_STRING", "{{.String}}")
> ```

Left over for `Replacer`.
___
*[pkg/sql/colexec/execgen/cmd/execgen/relative_rank_gen.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8luvIU8u82iYxf6DE0:-M8luvIU8u82iYxf6DE1:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/relative_rank_gen.go#L29)):*
> ```Go
> 
> func genRelativeRankOps(inputFile string, wr io.Writer) error {
> 	s := strings.ReplaceAll(inputFile, "_RELATIVE_RANK_STRING", "{{.String}}")
> ```

ditto
___
*[pkg/sql/colexec/execgen/cmd/execgen/row_number_gen.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8lux0tArfP4EW3vSo5:-M8lux0tArfP4EW3vSo6:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/row_number_gen.go#L27)):*
> ```Go
> 
> func genRowNumberOp(inputFile string, wr io.Writer) error {
> 	s := strings.ReplaceAll(inputFile, "_ROW_NUMBER_STRING", "{{.String}}")
> ```

ditto
___
*[pkg/sql/colexec/execgen/cmd/execgen/window_peer_grouper_gen.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8lv7A_4r7nwE-YcWAA:-M8lv7A_4r7nwE-YcWAB:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/window_peer_grouper_gen.go#L28)):*
> ```Go
> 
> func genWindowPeerGrouperOps(inputFile string, wr io.Writer) error {
> 	s := strings.ReplaceAll(inputFile, "_PEER_GROUPER_STRING", "{{.String}}")
> ```

ditto

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49751)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/execgen/cmd/execgen/const_gen.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8ltiGv6Id3mzjWkuqc:-M91HAX13aLpovapAIRa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/const_gen.go#L25)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Leftover.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/hashjoiner_gen.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8ltwBi0ZwzeSvLmTaW:-M91H9Jw4JyK6jwqrJHz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/hashjoiner_gen.go#L21)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

~I don't think this will work.~
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/main.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8luZEv-SKfI8bCZsh1:-M91H9ye-OUX9iY3Q-2U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/main.go#L53)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I misunderstood the meaning of `inputFile` - I thought it was "input filename" but it is "input file contents". I'd `s/inputFile/inputFileContents/g` for clarity.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/rank_gen.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8lurrU1b0Z9WbbDQ4a:-M91HBtQAe7Yplgphl31:b-bxss3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/rank_gen.go#L62)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Left over for `Replacer`.
</blockquote></details>

No need to use Replacer until there's several in a row, I'll leave these alone for now.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 32 of 32 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49751)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/sql/colexec/execgen/cmd/execgen/rank_gen.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49751#-M8lurrU1b0Z9WbbDQ4a:-M91PfVL89Fn0482-N8z:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d125a780756117d9b3a51dbea44b465211d2ea54/pkg/sql/colexec/execgen/cmd/execgen/rank_gen.go#L62)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

No need to use Replacer until there's several in a row, I'll leave these alone for now.
</blockquote></details>

sgtm

**Pull request merged**
