### PR TITLE
colexecwindow: implement first_value, last_value, and nth_value

### LINKED ISSUE #37035: exec: support all window functions in vectorized engine
Add support for:
 - [x] ROW_NUMBER, RANK, DENSE_RANK (#36926)
 - [x] PERCENT_RANK
 - [x] CUME_DIST
 - [x] NTILE
 - [x] LAG
 - [x] LEAD
 - [ ] FIRST_VALUE
 - [ ] LAST_VALUE
 - [ ] NTH_VALUE

### PR DESCRIPTION
**Pull request by DrewKimball**
**logictest: add testfile to ensure that window functions are vectorized**

This commit adds a logic testfile that executes the window functions
currently supported by the vectorized engine with
`SET vectorize = experimental_always`. This tests that supported
window functions can actually be executed in the vectorized engine.

Release note: None

**colexecwindow: add first_value, last_value, and nth_value**

This patch adds vectorized implementations of the `first_value`,
`last_value`, and `nth_value` window functions. These functions
return an expression evaluated at the first, last, and nth positions
respectively in the window frame for the current row.

Release note (sql change): first_value, last_value, and nth_value
window functions can now be executed in the vectorized engine. This
allows for faster execution time, and also removes the need for
conversions to and from row format.

**colexecwindow: test window framer with different memory limits**

Previously, the `TestWindowFramer` used `math.MaxInt64` as the memory
limit for the `SpillingBuffer` used to buffer all tuples in a partition.
This patch modifies the test to choose a random memory limit and fixes
a bug that could cause `windowFramer` operators to skip a peer group
when seeking to frame start and end indexes in `RANGE` or `GROUPS` mode.

Release note: None

**colexec: add range check for binary operations with timestamps**

This commit adds a range check after additions or subtractions that
produce a timestamp result. This ensures that the vectorized engine
produces the same error as the row engine when the result of the
operation is out of range.

Release note: None

Fixes #37035

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Great work! This one is now quite easy given all the previous hard work. I only have a few minor comments.

One kind of test that I realized we're missing is making sure that all currently supported by the vectorized engine window functions are, in fact, being executed via the vectorized. I think originally, when I added a couple, I introduced some simple queries with `row_number`, `rank`, `dense_rank`, `percent_rank`, and `cume_dist` at the bottom of `window` logic test file, but it would probably be worth moving those into a separate file `vectorize_window` or something like that. There, we would use `SET vectorize=experimental_always` to make sure that the vectorized is used. And then extend the file with the recent increased support.

> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-:-Mf0A7lO7HMbNpJctYVy:bqnk8qn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/colexec/colexecwindow/first_last_nth_value_tmpl.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-Mf0C7ki8TJL_fIoWhZx:-Mf0C7ki8TJL_fIoWhZy:b-ddv0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ed99a08180aeea42c79a20aadd3d416ac49cfce/pkg/sql/colexec/colexecwindow/first_last_nth_value_tmpl.go#L155)):*
> ```Go
> 			if partitionCol[i] {
> 				// Don't break for the start of the current partition.
> 				if !isPartitionStart || i != startIdx {
> ```

nit: I wonder whether it would be cleaner to pull this conditional outside of the loop and break here unconditionally. I'm thinking of something like:
```
i := startIdx
if isPartitionStart {
  i++
}
for ; i < n; i++ {
  if partitionCol[i] {
    break
  }
}
```
___
*[pkg/sql/colexec/execgen/cmd/execgen/first_last_nth_value_gen.go, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-Mf0DbOb9tW9OHv2O5dg:-Mf0DbOb9tW9OHv2O5dh:bqeloxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ed99a08180aeea42c79a20aadd3d416ac49cfce/pkg/sql/colexec/execgen/cmd/execgen/first_last_nth_value_gen.go#L37)):*
> ```Go
> }
> 
> func genFirstValueOp(inputFileContents string, wr io.Writer) error {
> ```

nit: these three generator functions are basically the same, and we could define a generator constructor in `init()` below that would be taking a couple of arguments and returning the correct generator. Take a look at `projection_ops_gen.go` for an example.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-Mf05oAv1JhLqnmDJme2:-Mf05oAv1JhLqnmDJme3:b-1553oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1672eaffb17263f3cc55153b96c4b83461bbe334/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L808)):*
> ```Go
> // timestampRangeCheck should be added at the end of operations that modify and
> // return timestamps in order to ensure that the vectorized engine returns the
> // same errors as the row engine.
> ```

nit: mention `t_res` local variable.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 810 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-Mf06gDGApNrrVZr3FHI:-Mf06gDGApNrrVZr3FHJ:bkxb0bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1672eaffb17263f3cc55153b96c4b83461bbe334/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L810)):*
> ```Go
> // same errors as the row engine.
> const timestampRangeCheck = `	
> if t_res.After(tree.MaxSupportedTime) || t_res.Before(tree.MinSupportedTime) {
> ```

Looks like the row engine also rounds to `tree.Microsecond` precision first, I think we should do too.
___
*[pkg/sql/colexec/execgen/cmd/execgen/range_offset_handler_gen.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-Mf05RwTDC6u3IvtUejH:-Mf05RwTDC6u3IvtUejI:b-l72u8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1672eaffb17263f3cc55153b96c4b83461bbe334/pkg/sql/colexec/execgen/cmd/execgen/range_offset_handler_gen.go#L306)):*
> ```Go
> }
> 
> const dateToTimeCastStr = `
> ```

nit: add a quick comment about which "arguments" should this format string be used with.

**Review by yuzefovich — COMMENTED** [review]
Oh, also, I'd be curious to see the absolute numbers of the microbenchmarks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-:-Mf0EZQN75xU7IARdimf:b-xulmbo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — COMMENTED** [review]
Added a commit for the `vectorized_window` testfile.

Here are numbers for `first_value`, the other two are about the same:
```
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
BenchmarkWindowFunctions/FIRST_VALUE/rows=4096/partition=true/order=true-12         	    2079	    534864 ns/op
BenchmarkWindowFunctions/FIRST_VALUE/rows=4096/partition=true/order=false-12        	    2210	    537169 ns/op
BenchmarkWindowFunctions/FIRST_VALUE/rows=4096/partition=false/order=true-12        	    2211	    536847 ns/op
BenchmarkWindowFunctions/FIRST_VALUE/rows=4096/partition=false/order=false-12       	    2221	    534657 ns/op
BenchmarkWindowFunctions/FIRST_VALUE/rows=32768/partition=true/order=true-12        	     280	   4225680 ns/op
BenchmarkWindowFunctions/FIRST_VALUE/rows=32768/partition=true/order=false-12       	     284	   4223189 ns/op
BenchmarkWindowFunctions/FIRST_VALUE/rows=32768/partition=false/order=true-12       	     285	   4222705 ns/op
BenchmarkWindowFunctions/FIRST_VALUE/rows=32768/partition=false/order=false-12      	     283	   4244977 ns/op
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-:-Mf1IeAU0gPkj3qnS6it:b-qxllka)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/colexecwindow/first_last_nth_value_tmpl.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-Mf0C7ki8TJL_fIoWhZx:-Mf11TTHCyvZXev9lzHb:b-m420f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ed99a08180aeea42c79a20aadd3d416ac49cfce/pkg/sql/colexec/colexecwindow/first_last_nth_value_tmpl.go#L155)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I wonder whether it would be cleaner to pull this conditional outside of the loop and break here unconditionally. I'm thinking of something like:
```
i := startIdx
if isPartitionStart {
  i++
}
for ; i < n; i++ {
  if partitionCol[i] {
    break
  }
}
```
</blockquote></details>

Done. I've also pulled out the common logic between lead/lag and first_value/last_value/nth_value.
___
*[pkg/sql/colexec/execgen/cmd/execgen/first_last_nth_value_gen.go, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-Mf0DbOb9tW9OHv2O5dg:-Mf13zqp3qP7F58bEmMQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ed99a08180aeea42c79a20aadd3d416ac49cfce/pkg/sql/colexec/execgen/cmd/execgen/first_last_nth_value_gen.go#L37)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: these three generator functions are basically the same, and we could define a generator constructor in `init()` below that would be taking a couple of arguments and returning the correct generator. Take a look at `projection_ops_gen.go` for an example.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-Mf05oAv1JhLqnmDJme2:-Mf1DfanC7p8wVNND3BP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1672eaffb17263f3cc55153b96c4b83461bbe334/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L808)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: mention `t_res` local variable.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 810 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-Mf06gDGApNrrVZr3FHI:-Mf1EElP2ZgcKym--eih:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1672eaffb17263f3cc55153b96c4b83461bbe334/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L810)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Looks like the row engine also rounds to `tree.Microsecond` precision first, I think we should do too.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/range_offset_handler_gen.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-Mf05RwTDC6u3IvtUejH:-Mf1Efz71pDZQ9l_O4fo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1672eaffb17263f3cc55153b96c4b83461bbe334/pkg/sql/colexec/execgen/cmd/execgen/range_offset_handler_gen.go#L306)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: add a quick comment about which "arguments" should this format string be used with.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 22 of 22 files at r4, 3 of 3 files at r5, 19 of 19 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67764#-:-Mf3ixgk0rM4opyOVB8R:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
TFTR!

**Pull request merged**
