### PR TITLE
sql/logictest: metamorphic param to use range tombstones for deletes

### LINKED ISSUE #84042: logictest: probabilistically replace point tombstones with range tombstones
**Is your feature request related to a problem? Please describe.**

To increase test coverage and increase confidence in our use of MVCC range operations, we should consider some enhancements to our existing tests that would use a range tombstone in place of a point tombstone with some probability (or via some metamorphic flags).

This testing can only happen outside of the KV API boundary, since inside the API boundary callers can observe the differences.

Extending the SQL logic tests to do this probabilistic testing seems like a good place to start. We should also consider other high-level tests, e.g. roachtests.

This is complicated by the fact that MVCC point tombstones are transactional but MVCC range tombstones aren't. This means that we'll have to do this replacement inside the KV/storage layer. For the 1PC path, well need to write MVCC range tombstones directly, while for transactional deletes we'll have to write an initial MVCC point tombstone as the provisional intent value, and only replace it with an MVCC range tombstone during intent resolution.

Jira issue: CRDB-17427

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by erikgrinaker**
**logictest: properly set rangefeed testing knobs**

This also changes the knobs to only implement the interface on the
pointer receiver, to avoid this issue in the future.

Release justification: non-production code changes

Release note: None
  
**server: inherit test tenant rangefeed knobs from test server**

Release justification: non-production code changes

Release note: None
  
**batcheval: add knob to write MVCC range tombstones for point deletes**

This patch adds a testing knob
`BatchEvalKnobs.UseRangeTombstonesForPointDeletes` and envvar
`COCKROACH_MVCC_RANGE_TOMBSTONES_FOR_POINT_DELETES` which will replace
point tombstones with range tombstones on a best-effort basis. These
should not appear different to a KV client (or thus SQL client), but
will exercise range key code paths in the KV/storage layer.

Release justification: non-production code changes

Release note: None
  
**sql/logictest: metamorphic param to use range tombstones for deletes**

This patch adds a metamorphic parameter
`logictest-use-mvcc-range-tombstones-for-point-deletes` which will write
point-sized MVCC range tombstones for point deletions. These are
indistinguishable to a KV client, but activates MVCC range tombstone
code paths in the storage/KV layer for testing.

Resolves #84042.

Release justification: non-production code changes

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Added a metamorphic logictest parameter and ran the fakedist suite a few times, no significant failures so far. I'll try to extend this to the point tombstone variant of `DeleteRange` as well, which is used a fair bit by SQL.

**Comment by erikgrinaker** [comment]
Added in support for `DeleteRange` point deletions too, should be good to go. Didn't find any new issues with MVCC range tombstones though, which is reassuring.

**Review by tbg — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 14 of 14 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87178)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @yuzefovich)

___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 566 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-NBCl1Di7sBWkqJFU7OS:-NBCl1Di7sBWkqJFU7OT:bdchvo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c3e1675696e0b010ae4ecb5a0449df7e195dae/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L566)):*
> ```Go
> 				resolvedLocks = append(resolvedLocks, update)
> 				// If requested, replace point tombstones with range tombstones.
> 				if ok && evalCtx.EvalKnobs().UseRangeTombstonesForPointDeletes {
> ```

Couldn't you do this more "easily" below raft?

```diff
diff --git a/pkg/kv/kvserver/replica_application_state_machine.go b/pkg/kv/kvserver/replica_application_state_machine.go
index a4ad32e91e..e20cae37ab 100644
--- a/pkg/kv/kvserver/replica_application_state_machine.go
+++ b/pkg/kv/kvserver/replica_application_state_machine.go
@@ -614,6 +614,22 @@ func (b *replicaAppBatch) stageWriteBatch(ctx context.Context, cmd *replicatedCm
 	if err := b.batch.ApplyBatchRepr(wb.Data, false); err != nil {
 		return wrapWithNonDeterministicFailure(err, "unable to apply WriteBatch")
 	}
+	if sk := b.r.store.TestingKnobs(); sk != nil && sk.EvalKnobs.UseRangeTombstonesForDeletes {
+		reader, err := storage.NewPebbleBatchReader(wb.Data)
+		if err != nil {
+			return err
+		}
+		for reader.Next() {
+			k := reader.Key()
+			endK := k.Next()
+			if err := storage.ReplacePointTombstonesWithRangeTombstones(
+				ctx, spanset.DisableReadWriterAssertions(b.batch),
+				&cmd.raftCmd.ReplicatedEvalResult.Delta /* not sure if this works and/or is race-free */, k, endK); err != nil {
+				return err
+			}
+		}
+
+	}
 	return nil
 }
 

```

I'm okay with this as-is too, and don't think it's worth a pivot, but thought it was at least worth a thought experiment in case we'd need something similar down the line.
___
*[`pkg/sql/logictest/logic.go` line 1241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-NBCg92uC-2kEKcrp3wl:-NBCg92uC-2kEKcrp3wm:bhmjeap) ([raw file](https://github.com/cockroachdb/cockroach/blob/61deb07329045fc386ff760353e75b328ac4eb37/pkg/sql/logictest/logic.go#L1241)):*
> ```Go
> 				},
> 				RangeFeed: &rangefeed.TestingKnobs{
> 					IgnoreOnDeleteRangeError: enableGlobalMVCCRangeTombstone,
> ```

Shouldn't this line implement the interface on the ptr receiver? https://github.com/cockroachdb/cockroach/blob/7d3ac48eefe945cc15a8b35d32b23f5ca11105b5/pkg/kv/kvclient/rangefeed/rangefeed.go#L94
Then there wouldn't be a wrong way to pass these knobs.
___
*[`pkg/sql/logictest/logic.go` line 547 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-NBCmvDB930Nt8T9m-1U:-NBCmvDB930Nt8T9m-1V:bs8wtzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2603af61d75dab13a42446379a4595633b09526f/pkg/sql/logictest/logic.go#L547)):*
> ```Go
> 	// tombstones for point deletions, on a best-effort basis. These should be
> 	// indistinguishable to a KV client, but activate MVCC range tombstone
> 	// code paths in the storage/KV layer, for testing.
> ```

Point out that they might cause incorrect stats?
___
*[`pkg/sql/logictest/logic.go` line 1415 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-NBCnG0p0HjqYoFH5wVC:-NBCnG0q1G_1chWvqWrY:b-z5gdq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2603af61d75dab13a42446379a4595633b09526f/pkg/sql/logictest/logic.go#L1415)):*
> ```Go
> 		}
> 
> 		// Reduce the schema GC job's MVCC polling interval for faster tests.
> ```

Just double checking that you meant to commit this.
___
*[`pkg/storage/testdata/mvcc_histories/replace_point_tombstones_with_range_tombstones` line 244 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-NBCkp9l7E2i0NFp6QcL:-NBCkp9l7E2i0NFp6QcM:b-nvqzpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c3e1675696e0b010ae4ecb5a0449df7e195dae/pkg/storage/testdata/mvcc_histories/replace_point_tombstones_with_range_tombstones#L244)):*
> ```
> data: "l"/1.000000000,0 -> /BYTES/l1
> data: "m"/5.000000000,0 -> /BYTES/m5
> stats: key_count=10 key_bytes=200 val_count=15 val_bytes=152 range_key_count=7 range_key_bytes=160 range_val_count=14 live_count=5 live_bytes=153 gc_bytes_age=34769 intent_count=2 intent_bytes=31 separated_intent_count=2 intent_age=190
> ```

I know I asked this somewhere else too but not sure what the answer was, are these stats verified against source of truth via recomputation?

**Review by tbg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-:-NBCnMoF74BxGLM2FVE1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @yuzefovich)

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87178)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911, @tbg, and @yuzefovich)

___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 566 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-NBCl1Di7sBWkqJFU7OS:-NBCxas82igKrfIoI5_N:b-8zm4lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c3e1675696e0b010ae4ecb5a0449df7e195dae/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L566)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Couldn't you do this more "easily" below raft?

```diff
diff --git a/pkg/kv/kvserver/replica_application_state_machine.go b/pkg/kv/kvserver/replica_application_state_machine.go
index a4ad32e91e..e20cae37ab 100644
--- a/pkg/kv/kvserver/replica_application_state_machine.go
+++ b/pkg/kv/kvserver/replica_application_state_machine.go
@@ -614,6 +614,22 @@ func (b *replicaAppBatch) stageWriteBatch(ctx context.Context, cmd *replicatedCm
 	if err := b.batch.ApplyBatchRepr(wb.Data, false); err != nil {
 		return wrapWithNonDeterministicFailure(err, "unable to apply WriteBatch")
 	}
+	if sk := b.r.store.TestingKnobs(); sk != nil && sk.EvalKnobs.UseRangeTombstonesForDeletes {
+		reader, err := storage.NewPebbleBatchReader(wb.Data)
+		if err != nil {
+			return err
+		}
+		for reader.Next() {
+			k := reader.Key()
+			endK := k.Next()
+			if err := storage.ReplacePointTombstonesWithRangeTombstones(
+				ctx, spanset.DisableReadWriterAssertions(b.batch),
+				&cmd.raftCmd.ReplicatedEvalResult.Delta /* not sure if this works and/or is race-free */, k, endK); err != nil {
+				return err
+			}
+		}
+
+	}
 	return nil
 }
 

```

I'm okay with this as-is too, and don't think it's worth a pivot, but thought it was at least worth a thought experiment in case we'd need something similar down the line.
</blockquote></details>

I think this would be harder. In particular, we can't do this for provisional intent values, which must remain as point tombstones until resolved.
___
*[`pkg/sql/logictest/logic.go` line 1241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-NBCg92uC-2kEKcrp3wl:-NBCzBCm30I0X-sXWhBf:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/61deb07329045fc386ff760353e75b328ac4eb37/pkg/sql/logictest/logic.go#L1241)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Shouldn't this line implement the interface on the ptr receiver? https://github.com/cockroachdb/cockroach/blob/7d3ac48eefe945cc15a8b35d32b23f5ca11105b5/pkg/kv/kvclient/rangefeed/rangefeed.go#L94
Then there wouldn't be a wrong way to pass these knobs.
</blockquote></details>

Good idea, done.
___
*[`pkg/sql/logictest/logic.go` line 547 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-NBCmvDB930Nt8T9m-1U:-NBCyDqt22D8-3VQnz4u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2603af61d75dab13a42446379a4595633b09526f/pkg/sql/logictest/logic.go#L547)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Point out that they might cause incorrect stats?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/logic.go` line 1415 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-NBCnG0p0HjqYoFH5wVC:-NBCzCdD4j6D_GJQSXaX:b1jzl9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2603af61d75dab13a42446379a4595633b09526f/pkg/sql/logictest/logic.go#L1415)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Just double checking that you meant to commit this.
</blockquote></details>

I did. Without this, a couple of tests ended up hanging indefinitely with failures I couldn't easily track down (database drops would be blocked on schema descriptors which were themselves blocked on schema GC). Most likely the use of MVCC range tombstones slows down GC enough to trigger a race where the GC job doesn't succeed on the first pass, and then ends up waiting 5 minutes before retrying, or some such.
___
*[`pkg/storage/testdata/mvcc_histories/replace_point_tombstones_with_range_tombstones` line 244 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-NBCkp9l7E2i0NFp6QcL:-NBCzm5W-vUHn7Kt8G55:b267bek) ([raw file](https://github.com/cockroachdb/cockroach/blob/93c3e1675696e0b010ae4ecb5a0449df7e195dae/pkg/storage/testdata/mvcc_histories/replace_point_tombstones_with_range_tombstones#L244)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I know I asked this somewhere else too but not sure what the answer was, are these stats verified against source of truth via recomputation?
</blockquote></details>

Yes, they are.

**Comment by tbg** [comment]
Still good.

**Comment by erikgrinaker** [comment]
Blocked on #87364 and #87357, and it would be good to get a quick ✅ from @yuzefovich as well.

**Review by yuzefovich — COMMENTED** [review]
3rd, 4th, and 6th commits LGTM.

> Reviewed 2 of 2 files at r9, 2 of 2 files at r10, 1 of 14 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87178#-:-NBJstKP9iIhU1QFZABw:b22r4un)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911 and @tbg)

**Comment by erikgrinaker** [comment]
TFTRs! CI failure is unrelated.

bors r=tbg,yuzefovich

**Pull request merged**
