### PR TITLE
distsql: memory accounting in hash joiner

### PR DESCRIPTION
**Pull request by RaduBerinde**
Use RowContainer in the hash joiner. Each bucket stores row indexes into this
container.

The memory exceeded test was changed because it was taking too long too fail
(10+ seconds) in its original form - we were only storing empty rows, so it's
just the row indices in the buckets that used up memory (we can accumulate a lot
of those). In contrast, in the non-distsql version the `parser.Datums` rows
contain the hidden columns as well so only a fraction
of rows must be processed before we fill up the memory.

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8XUvOU8Y8168zwK1Q:-Kj8XUvOU8Y8168zwK1R:b-xzhipo) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/aggregator.go#L204)):*
> ```Go
> 	defer func() {
> 		if err != nil && cleanupRequired {
> 			log.Infof(ctx, "accumulate error %s", err)
> ```

I think we do %v for errors

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 147 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8Xg3sOipd-ENBKHpY:-Kj8Xg3sOipd-ENBKHpZ:b-quson7) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/hashjoiner.go#L147)):*
> ```Go
> 		// the consumer. Note that rightSource has already been drained at this
> 		// point.
> 		log.Infof(ctx, "MEH probe phase error %s", err)
> ```

Clarify what's a "MEH probe phase"

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 223 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8XuxaDxpu_IqUimEC:-Kj8XuxaDxpu_IqUimED:bwzl8ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/hashjoiner.go#L223)):*
> ```Go
> 		}
> 
> 		if err := h.bucketsAcc.Grow(ctx, sizeOfRowIdx); err != nil {
> ```

I think you meant to pass `usage` to `Grow()` here

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 305 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8YF7cLtdMgKwWRg8U:-Kj8YF7d1iND27VtfMKJ:bcuh6ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/hashjoiner.go#L305)):*
> ```Go
> 				}
> 				if !failedOnCond && (h.joinType == rightOuter || h.joinType == fullOuter) {
> 					b.seen[i] = true
> ```

This is a patch that belongs to a different commit, isn't that the fix for #12550 / #13342 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/distsqlrun/aggregator.go, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8XUvOU8Y8168zwK1Q:-Kj8hYuq7SbNOu_uL908:b-40h8vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/aggregator.go#L204)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think we do %v for errors
</blockquote></details>

Hm, I think only when it could be `nil`, otherwise they're equivalent.

I moved it out to log the error even if cleanupRequired is false though.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 147 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8Xg3sOipd-ENBKHpY:-Kj8ikcPmDfztUFQL8GZ:b-p4ybu) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/hashjoiner.go#L147)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Clarify what's a "MEH probe phase"
</blockquote></details>

Oops, fixed.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 223 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8XuxaDxpu_IqUimEC:-Kj8imPoK5IHm5xq_miT:b6zrrk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/hashjoiner.go#L223)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you meant to pass `usage` to `Grow()` here
</blockquote></details>

Good catch!

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 305 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8YF7cLtdMgKwWRg8U:-Kj8ix31oTQm16U8GrGL:b4mkt1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/hashjoiner.go#L305)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is a patch that belongs to a different commit, isn't that the fix for #12550 / #13342 ?
</blockquote></details>

I swapped the two branches, but the code is the same. I just added an `if` to avoid calling `renderAndEmit` if we are doing an inner join and we don't find a bucket. Sorry for the diff noise, it seemed natural to first consider the case where we actually find something.

I think this code already handles outer joins correctly, we're just missing planning for outer joins.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-:-Kj8jsL1CJLBxH4PcxhB:b-814g8k)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/testdata/logic_test/join, line 624 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8tvkiu14gYGMYL0aX:-Kj9ByChG2uSkQGohYeu:b-ljet9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68d3f67b042947f28779221ea5040bfe9053224/pkg/sql/testdata/logic_test/join#L624)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

why the explicit columns with additions?
</blockquote></details>

See the second paragraph in the PR description

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595)*

**Comment by andreimatei** [comment]
:lgtm: but consider sharing the account between the rowContainer and the buckets

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8XUvOU8Y8168zwK1Q:-Kj90oEFHRwr21pqiasw:b2g4ya9) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/aggregator.go#L204)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hm, I think only when it could be `nil`, otherwise they're equivalent.

I moved it out to log the error even if cleanupRequired is false though.
</blockquote></details>

yeah, I think we use "%v" to explicitly say "this can be nil"

nit: consider `log.Warningf()` here and in the other error logging

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 147 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8Xg3sOipd-ENBKHpY:-Kj90LvQbRHiqQ8GrPsC:bvi29ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/hashjoiner.go#L147)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oops, fixed.
</blockquote></details>

LOLOLO

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 37 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj91JBAGa3cfxOBiZs_:-Kj91JBAGa3cfxOBiZsa:boed05f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68d3f67b042947f28779221ea5040bfe9053224/pkg/sql/distsqlrun/hashjoiner.go#L37)):*
> ```Go
> 	// rows hold indices of rows into the hashJoiner's rows container.
> 	rows []int
> 	seen []bool
> ```

unrelated to your change, but why is `seen` an array? Shouldn't it be one bool per bucket?
If you know anything about this, perhaps improve the comment. And if you do, consider moving the comment here, to the member, and fixing that #IrfanComma

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 58 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj9493qv0mYXGkHEQz2:-Kj9493qv0mYXGkHEQz3:bisdmrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68d3f67b042947f28779221ea5040bfe9053224/pkg/sql/distsqlrun/hashjoiner.go#L58)):*
> ```Go
> 	rows rowContainer
> 
> 	// bucketsAcc is the memory account for the buckets. The datums themselves are
> ```

is this account really necessary, in addition to the `rowContainer`'s one? If feasible (e.g. if it wouldn't need concurrent access), I'd suggest we make the `rowContainer` ctor take an account, and share it with the buckets. I think this would also generate better error messages when the underlying monitor runs out of memory.

---

*[pkg/sql/sqlbase/row_container.go, line 271 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj93Zd2ejpVNtSCPIEk:-Kj93Zd3NNG_NCVpggfE:b-lc77a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68d3f67b042947f28779221ea5040bfe9053224/pkg/sql/sqlbase/row_container.go#L271)):*
> ```Go
> 	}
> 	if c.numCols == 0 {
> 		// We don't want to return nil, as in some contexts nil is used as a special
> ```

were the changes in this file needed for this PR? Just curious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-:-Kj9JwiKvJC7xj3u8iaC:b18ggim)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8XUvOU8Y8168zwK1Q:-Kj9O8m8zwuCf_4vbibs:b-h5v460) ([raw file](https://github.com/cockroachdb/cockroach/blob/20af648b0258e04ed5e1d56567cbd4710d4c3ca5/pkg/sql/distsqlrun/aggregator.go#L204)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

yeah, I think we use "%v" to explicitly say "this can be nil"

nit: consider `log.Warningf()` here and in the other error logging
</blockquote></details>

This can include expected errors (like uncertain reads), I think Info is probably ok.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 37 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj91JBAGa3cfxOBiZs_:-Kj9PYKuW03Bk1k-loF2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68d3f67b042947f28779221ea5040bfe9053224/pkg/sql/distsqlrun/hashjoiner.go#L37)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

unrelated to your change, but why is `seen` an array? Shouldn't it be one bool per bucket?
If you know anything about this, perhaps improve the comment. And if you do, consider moving the comment here, to the member, and fixing that #IrfanComma
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 58 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj9493qv0mYXGkHEQz2:-Kj9Pbudp0O8R2ysTGb-:b-r3h2sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68d3f67b042947f28779221ea5040bfe9053224/pkg/sql/distsqlrun/hashjoiner.go#L58)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this account really necessary, in addition to the `rowContainer`'s one? If feasible (e.g. if it wouldn't need concurrent access), I'd suggest we make the `rowContainer` ctor take an account, and share it with the buckets. I think this would also generate better error messages when the underlying monitor runs out of memory.
</blockquote></details>

I thought it's good practice to separate things into multiple accounts. For one it would tell us how much memory we are using for buckets vs rows no?  How are the error messages better if there is only one account? (cc @knz)

---

*[pkg/sql/sqlbase/row_container.go, line 271 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj93Zd2ejpVNtSCPIEk:-Kj9PyOLisK3wMIKwJDQ:b-ujl5gp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68d3f67b042947f28779221ea5040bfe9053224/pkg/sql/sqlbase/row_container.go#L271)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

were the changes in this file needed for this PR? Just curious.
</blockquote></details>

Yes, I believe so (for the test added in #15420, and for the original form of the test query that runs of memory).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595)*

**Comment by andreimatei** [comment]
Review status: 8 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 58 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj9493qv0mYXGkHEQz2:-Kj9RhM0p3MwP9z-3ap4:bdb4xbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68d3f67b042947f28779221ea5040bfe9053224/pkg/sql/distsqlrun/hashjoiner.go#L58)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I thought it's good practice to separate things into multiple accounts. For one it would tell us how much memory we are using for buckets vs rows no?  How are the error messages better if there is only one account? (cc @knz)
</blockquote></details>

I guess it's good practice to separate different things into different accounts, but are the buckets and the rows in them really different?

I thought the error tells you the budget of the monitor and how many bytes have been allocated in the account that's trying to grow and can't, but now in `newMemoryError` I only see information about the monitor. Perhaps somewhere we should wrap with information which account is failing to allocate? @knz

Not a big deal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595)*

**Comment by RaduBerinde** [comment]
Review status: 8 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 58 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj9493qv0mYXGkHEQz2:-Kj9U1i2NCGtnZoEk4ao:bmzt178) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68d3f67b042947f28779221ea5040bfe9053224/pkg/sql/distsqlrun/hashjoiner.go#L58)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I guess it's good practice to separate different things into different accounts, but are the buckets and the rows in them really different?

I thought the error tells you the budget of the monitor and how many bytes have been allocated in the account that's trying to grow and can't, but now in `newMemoryError` I only see information about the monitor. Perhaps somewhere we should wrap with information which account is failing to allocate? @knz

Not a big deal.
</blockquote></details>

They're different in that buckets only store metadata and the container stores datums. Their relative sizes can tell you if the problem is that there are too many rows, or that the rows are too "big". Not sure if that difference is important enough though.

Anyway, I'll leave as is for now since the message is the same regardless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595)*

**Comment by arjunravinarayan** [comment]
*[pkg/sql/testdata/logic_test/join, line 624 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595#-Kj8tvkiu14gYGMYL0aX:-Kj9apfHivPk_vhnxhMz:b-ey83kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68d3f67b042947f28779221ea5040bfe9053224/pkg/sql/testdata/logic_test/join#L624)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

See the second paragraph in the PR description
</blockquote></details>

Oops, missed that. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15595)*

**Pull request merged**
