### PR TITLE
release-20.2: colexec: reduce some allocations

### PR DESCRIPTION
**Pull request by yuzefovich**
Found some inefficiencies when looking into https://github.com/cockroachlabs/support/issues/1011.

The relevant code has been fixed in 21.1 time frame, so this PR is directly against 20.2 branch.

**colexec: delay instantiation of some objects in external hash joiner**

Previously, we would always allocate several batches (either 2 or 4) of
1024 size in the constructor of the external hash joiner even if we
don't spill to disk. This is very inefficient in case of hash joins
processing very small amount of data. This commit moves that
instantiation to `Init` method which is called only once we spill to
disk.

Release note: None

**colexec: delay instantiation of a dequeue scratch in the spilling queue**

Previously, we would always allocate a batch of maximum size in the
constructor of the spilling queue. This is suboptimal if the queue isn't
used (which could happen if the flow is abandoned).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/colexec/spilling_queue.go, line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66104#-MbNuoEp8Jt37goIb4Tp:-MbNuoEp8Jt37goIb4Tq:b53dp4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7908364cf851192df0c9b0bc53b0e4c5ef412fda/pkg/sql/colexec/spilling_queue.go#L177)):*
> ```Go
> 			q.unlimitedAllocator.ReleaseBatch(q.dequeueScratch)
> 		} else {
> 			q.dequeueScratch = q.unlimitedAllocator.NewMemBatchWithFixedCapacity(q.typs, coldata.BatchSize())
> ```

In the previous code, we would do `NewMemBatchWithFixedCapacity` and then we would do a `ReleaseBatch` here (paired with the `RetainBatch` below). Now we are not doing the first `ReleaseBatch` call anymore, is that not a problem?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66104)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @RaduBerinde)

___
*[pkg/sql/colexec/spilling_queue.go, line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66104#-MbNuoEp8Jt37goIb4Tp:-MbNwxY76wUYefUEHzHC:bqeeoj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7908364cf851192df0c9b0bc53b0e4c5ef412fda/pkg/sql/colexec/spilling_queue.go#L177)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In the previous code, we would do `NewMemBatchWithFixedCapacity` and then we would do a `ReleaseBatch` here (paired with the `RetainBatch` below). Now we are not doing the first `ReleaseBatch` call anymore, is that not a problem?
</blockquote></details>

Good catch, fixed. With the original version we would double-count some of the memory.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66104#-:-MbO-XAHBpWv918l9dyt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/colexec/spilling_queue.go, line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66104#-MbNuoEp8Jt37goIb4Tp:-MbO-NeKDWER71Y4TyKS:brtog2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7908364cf851192df0c9b0bc53b0e4c5ef412fda/pkg/sql/colexec/spilling_queue.go#L177)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good catch, fixed. With the original version we would double-count some of the memory.
</blockquote></details>

[nit] I would move this before the NOTE comment which refers to the ReleaseBatch call.

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66104#-:-MbO5uMn5-d2GkMvkVav:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTRs!

**Pull request merged**
