### PR TITLE
sql: skip pgbench if not on PATH

### PR DESCRIPTION
**Pull request by dt**
Currently blocking #8081

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10509)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

please mention the issue.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/pgbench_test.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10509#-KVzzDQ_9VhP-pdweuYF:-KVzzDQ_9VhP-pdweuYG:b5w52xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/19572666b51f539774991e4f7a98fcabdece9c1a/pkg/sql/pgbench_test.go#L24)):*
> ```Go
> 	"math/rand"
> 	"net/url"
> 	osexec "os/exec"
> ```

why the alias?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10509#-:-KVzzH4t6NeRLv2X9i44:bxlo3sv)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/pgbench_test.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10509#-KVzzDQ_9VhP-pdweuYF:-KVzzwZdDSPvWz4dLQXC:b9g5x5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/19572666b51f539774991e4f7a98fcabdece9c1a/pkg/sql/pgbench_test.go#L24)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why the alias?
</details>
there's already a symbol `exec` in the sql package (in txn_restart_test.go).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10509)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10509#-:-KW-0XlCyI11dU4lNMM8:bnfp4nl)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/pgbench_test.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10509#-KVzzDQ_9VhP-pdweuYF:-KW-12YQ10RSkdPoPtfP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19572666b51f539774991e4f7a98fcabdece9c1a/pkg/sql/pgbench_test.go#L24)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> which has one caller :facepalm: 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10509)*

**Comment by tamird** [comment]
Can you mention the issue in the commit message, not just the PR description?

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10509#-:-KW-248bZGf8Dy18ypGP:bjm4cth)*

**Comment by dt** [comment]
Done.

**Comment by tamird** [comment]
Great. Feel free to unassign yourself from #8081 and kick off a benchmark run when this merges.

**Pull request merged**
