### PR TITLE
docs: new tech note on TxnCoordSender

### PR DESCRIPTION
**Pull request by knz**
I am splitting off this tech note from #41569 so it can become a document that can be consumed standalone.

Direct link for easier consumption/review:
https://github.com/knz/cockroach/blob/20191101-tcs-tech-note/docs/tech-notes/txn_coord_sender.md

### CODE REVIEW

**Comment by knz** [comment]
@tbg you wanted to have a look, I think this is mature enough for you to read (and dump additional knowledge into if you have it).

@nvanbenschoten I acknowledge that this tech note, as-is, is not doing justice to all the logic and intelligence present in the various interceptors. If you have reference links or extra contents to add, I'll take it.

**Comment by knz** [comment]
TODO(self): 

- [ ] integrate the discussion on WriteTooOldError from the mailing list.

**Review by tbg — APPROVED** [review]
Nice write up. I added a few comments.

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-:-Lsr5Y-GE8t0RwzctfXs:bag0zu8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @nvanbenschoten)

___
*[docs/tech-notes/txn_coord_sender.md, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lsr0dh5DkM4yigopXVZ:-Lsr0dh5DkM4yigopXV_:bnp2syv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L453)):*
> ```Markdown
> object and the TCS to become unusable. Indeed, there is no good reason
> for that. It is actually silly, as a SQL client may legitimately want
> to continue using the txn object after detecting a logical error (eg
> ```

I wouldn't call this silly, just poor design. Whenever we extract information from an error that counts as a read, we have to make sure that read is accounted for by the KV store. For example, a ConditionFailedError from a CPut is in fact a successful read; if this isn't accounted for properly at the KV layer (timestamp cache update), there will be anomalies (CPut has code to do exactly that [here](https://github.com/cockroachdb/cockroach/blob/2c0e2ab3d2f2faa664c4cc809c9b990c2519a773/pkg/storage/replica_tscache.go#L136-L142)). I generally find it unfortunate that we're relying on errors to return what are really logical results, and I hope that we buy out of that as much as we can. For CPut, for example, we'd have `ConditionalPutResponse` carry a flag that tells us the actual value and whether a write was carried out. I suspect we're using errors for some of these only because errors eagerly halt the processing of the current batch.
Continuing past errors generally needs a good amount of idempotency (for example, getting a timeout during a CPut and retrying the CPut without seqnos could read-your-own-write). We had no way of doing that prior to the intent history and seqnos.

By the way, in case you haven't stumbled upon this yet, the txn span refresher has a horrible contract with DistSender, where DistSender returns a partially populated response batch on errors, from which the refresher then picks out spans for its refresh set. I'm wondering how this hasn't backfired yet.
___
*[docs/tech-notes/txn_coord_sender.md, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lsr3JFV8czJCLs8Mkl1:-Lsr3JFW2OVir_ggxPc2:b8avsul) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L486)):*
> ```Markdown
>   complexity to process writes, concurrency would be limited by this
>   counter, until/unless we can guarantee that two separate TCSs
>   generate separate operation identifiers.
> ```

I wonder if we also need their read/write spans to be non-overlapping. There's all sort of weird stuff if they do overlap, though maybe it's not actually illegal. Either way, not something we're going to do today or tomorrow.
___
*[docs/tech-notes/txn_coord_sender.md, line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lsr43nV7RAa-gOM_bPw:-Lsr43nV7RAa-gOM_bPx:bwr1fp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L503)):*
> ```Markdown
>   then at later instant t2 is augmented by a LeafTxn whose
>   state was part of its "past" using the original txn object.
>   How to combine the states from the two "generations" of the txn object?
> ```

The real problem I see here is similar to allowing leaves to write. You have to reason about the semantics in case the spans accessed overlap. If we've answered that, I'm not aware of any specific problem with updating the state in the way you're describing. As long as there is a distinguished error handling actor, this looks just like what `txn.Update` already does (except we need to merge the whole state, like refresh spans, etc). Curious if you had a concrete problem in mind.
PS I'm totally fine not wanting to change this restriction, just working on my understanding.
___
*[docs/tech-notes/txn_coord_sender.md, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lsr56ZFBCO40ew4N0MH:-Lsr56ZFBCO40ew4N0MI:b-p2f7ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L549)):*
> ```Markdown
> - read operations operate "at" a particular seqnum: a MVCC read that
>   encounters an intent ignores the values written at later seqnums
>   and returns the most recent value at that seqnum instead.
> ```

Isn't this one-offy? If I want to retry a CPut idempotently (because the first one got context canceled, who knows), I'd want it to *not* see its own seqno.

**Comment by knz** [comment]
> If I want to retry a CPut idempotently (because the first one got context canceled, who knows), I'd want it to not see its own seqno.

I just realized it's worse than that, the cput has to ignore seqnums for its condition too (it shouldn't see a rolled back value when testing the condition).

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-:-Lss3G0z7t-PJaoMNWRM:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @nvanbenschoten)

___
*[docs/tech-notes/txn_coord_sender.md, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lss19QQ7eaXCtWcoa_z:-Lss19QQ7eaXCtWcoaa-:bugkql9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L384)):*
> ```Markdown
>      its "identity" (ID, epoch) is unchanged.
> 
>      For example, txn refreshes are processes automatically
> ```

are processed
___
*[docs/tech-notes/txn_coord_sender.md, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lss1ZuG9ZZbS_hdVON2:-Lss1ZuG9ZZbS_hdVON3:b8t1nou) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L413)):*
> ```Markdown
>   This group contains 3 kinds of errors:
> 
>   1. *transaction aborts* (`TransactionAbortedError`), which occurs when
> ```

`TransactionAbortedError` trashes the TCS, but not the client.Txn. The client.Txn will recognize the error an instantiate a new TCS.
___
*[docs/tech-notes/txn_coord_sender.md, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lss2SPv1eW_xoKHwbQp:-Lss2SPv1eW_xoKHwbQq:bdr84jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L461)):*
> ```Markdown
> inside the TCS may become different "on the way out" (back to
> client.Txn and the SQL layer) from what it was "on the way in". It is
> currently the responsibility of the client (SQL layer), which may have
> ```

What are you referring to here? What state is SQL picking up on?

**Review by tbg — COMMENTED** [review]
As I understand it, ConditionalPut demonstrates something we missed when introducing seqnos: commands that combine both a read and a write operation need two seqnums, one for its reads and one for its writes. Isn't the correct thing to use `seqno-1` for the read portion? And of course, like any other read, it also needs to ignore the rolled back sequences, as you point out. I don't see a major problem here, just something we overlooked so far.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-:-LsvH0H13-QxNYmsE523:brcpufg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @nvanbenschoten)

**Review by knz — COMMENTED** [review]
> Isn't the correct thing to use seqno-1 for the read portion?

Yes Nathan has convinced me this is true. Added a note to this effect.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-:-LucDWqB7Nvg1lzHCra6:bf5azgs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[docs/tech-notes/txn_coord_sender.md, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lss19QQ7eaXCtWcoa_z:-Luc8TQ1AFCvNz8DkhAN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L384)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

are processed
</blockquote></details>

Done.
___
*[docs/tech-notes/txn_coord_sender.md, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lss1ZuG9ZZbS_hdVON2:-Luc8gN22C_8UrS5KRvm:b-uzakx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L413)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`TransactionAbortedError` trashes the TCS, but not the client.Txn. The client.Txn will recognize the error an instantiate a new TCS.
</blockquote></details>

Your prompt invited me to investigate more and I found out the situation is more complicated than that. There's in fact two categories of abort errors.
___
*[docs/tech-notes/txn_coord_sender.md, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lsr0dh5DkM4yigopXVZ:-LucC6BZ1z6psTry11mu:b-vuuh60) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L453)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I wouldn't call this silly, just poor design. Whenever we extract information from an error that counts as a read, we have to make sure that read is accounted for by the KV store. For example, a ConditionFailedError from a CPut is in fact a successful read; if this isn't accounted for properly at the KV layer (timestamp cache update), there will be anomalies (CPut has code to do exactly that [here](https://github.com/cockroachdb/cockroach/blob/2c0e2ab3d2f2faa664c4cc809c9b990c2519a773/pkg/storage/replica_tscache.go#L136-L142)). I generally find it unfortunate that we're relying on errors to return what are really logical results, and I hope that we buy out of that as much as we can. For CPut, for example, we'd have `ConditionalPutResponse` carry a flag that tells us the actual value and whether a write was carried out. I suspect we're using errors for some of these only because errors eagerly halt the processing of the current batch.
Continuing past errors generally needs a good amount of idempotency (for example, getting a timeout during a CPut and retrying the CPut without seqnos could read-your-own-write). We had no way of doing that prior to the intent history and seqnos.

By the way, in case you haven't stumbled upon this yet, the txn span refresher has a horrible contract with DistSender, where DistSender returns a partially populated response batch on errors, from which the refresher then picks out spans for its refresh set. I'm wondering how this hasn't backfired yet.
</blockquote></details>

Added your comments in the tech note.
___
*[docs/tech-notes/txn_coord_sender.md, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lss2SPv1eW_xoKHwbQp:-LucCkGb-0IB_AHdim4r:b-u5t80l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L461)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

What are you referring to here? What state is SQL picking up on?
</blockquote></details>

Added comment to clarify.
___
*[docs/tech-notes/txn_coord_sender.md, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lsr3JFV8czJCLs8Mkl1:-LucCraP9THuahFC-u1l:b-hfok4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L486)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I wonder if we also need their read/write spans to be non-overlapping. There's all sort of weird stuff if they do overlap, though maybe it's not actually illegal. Either way, not something we're going to do today or tomorrow.
</blockquote></details>

Added note.
___
*[docs/tech-notes/txn_coord_sender.md, line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lsr43nV7RAa-gOM_bPw:-LucD3od7idhHCEOqKqd:b-mxyppa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L503)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The real problem I see here is similar to allowing leaves to write. You have to reason about the semantics in case the spans accessed overlap. If we've answered that, I'm not aware of any specific problem with updating the state in the way you're describing. As long as there is a distinguished error handling actor, this looks just like what `txn.Update` already does (except we need to merge the whole state, like refresh spans, etc). Curious if you had a concrete problem in mind.
PS I'm totally fine not wanting to change this restriction, just working on my understanding.
</blockquote></details>

My opinion is that this is the wrong problem to solve. These complex questions, which may or may not have good answers, should not be necessary to answer in the first place. Enabling concurrency between Root and Leafs on the same spans is just a horrible mess.
___
*[docs/tech-notes/txn_coord_sender.md, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lsr56ZFBCO40ew4N0MH:-LucDMSs7Zu8lxCwXZzR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L549)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Isn't this one-offy? If I want to retry a CPut idempotently (because the first one got context canceled, who knows), I'd want it to *not* see its own seqno.
</blockquote></details>

Done.

**Comment by knz** [comment]
Going to merge this as it now has enough content to base further work on.

Also it's needed to ground the discussion on #42766.

bors r+

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42116)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, @nvanbenschoten, and @tbg)

___
*[docs/tech-notes/txn_coord_sender.md, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-Lss1ZuG9ZZbS_hdVON2:-LucSZ62DXxJLkKxaBlf:b3v5avs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65e00ae50dde3973a2f3e20ec9e9d5be59b4d82/docs/tech-notes/txn_coord_sender.md#L413)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Your prompt invited me to investigate more and I found out the situation is more complicated than that. There's in fact two categories of abort errors.
</blockquote></details>

Are there? I'm not sure what you're referring to here, I think it's wrong. AOST read under GC doesn't have anything to do with a `TransactionAbortedError`, does it?
`TransactionAbortedError` means one thing - some other transaction blew away some of our intents.
___
*[docs/tech-notes/txn_coord_sender.md, line 417 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42116#-LucTy0Z42XUIojmzqXS:-LucTy0_B48M97jjICJL:bxduy2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee398a591d773060dfa4a2e92b68db6e1066fe39/docs/tech-notes/txn_coord_sender.md#L417)):*
> ```Markdown
>      internal CRDB mechanism, but not due to a logical
>      error. Intuitively, this corresponds to errors due to the
>      distributed nature of CRDB which would not occur in a
> ```

Deadlock between multiple transactions is the case where transaction aborts happen because of "user fault". That's analogous to single-node systems - there too sometimes transactions are aborted and forced to release their locks.

**Comment by knz** [comment]
Can you suggest an extension to the text to make it better?

**Pull request merged**
