### PR TITLE
storage: enforce gc ttl strictly

### PR DESCRIPTION
**Pull request by ajwerner**
This PR creates a cluster setting to control whether the GC TTL is enforced
"strictly". Strict GC enforcement is not a strong guarantee that we will
serve no user reads whatsoever for timestamps that are older than the current
reading of the node's clock less the GC TTL. Rather it is a setting to enable
the behavior that most of the time, most requests will see an error if they
use a timestamp which is older than the GC TTL.

The main case in which the user will see an error is if the only reason a
read would be able to request a timestamp was because of a protected timestamp.
The process of verifying a protected timestamp will prevent this case.
If the users of protected timestamps verify the protected timestamp before
they operate, or they use admin commands, they'll be fine.

In the presence of a protected timestamp, all requests can read back to
that protected timestamp.

Lease transfers are another source possibility for data to be visible at the
GC Threshold rather than the TTL.

Strict mode is controlled via a cluster setting.

Strict mode does not apply to admin commands or to system ranges.

The interesting thing with this all is that the problem which prompted this
setting in the first place was due to backups being run at a period longer
than the GC TTL and pretty much never failing.

Backups in 20.1 (in theory) are going to use protected timestamps. If they
successfully verify the protected timestamp then they'll be able to still
succeed an even higher percentage of the time! If we want to discourage this
behavior we could

* Have the protected timestamp subsystem enforce that clients can't save
  data they currently view as expired. This is probably a bad idea because
  interestingly enough the protected timestamp subsystem ignores zone configs
  completely.

* Have the higher levels try to do it. This seems probably better. The backup
  pulls the table descriptors and knows exactly the timestamp ranges it's
  backing up. In a lot of cases I can imagine wanting to back up data that
  is expired. Making that hard would probably be worse than making messing
  up like this worse. It probably also has zone configs. I might instead
  just warn loudly in this case.

What this will do is bring greater awareness of the GC ttl. If you don't
update or delete data frequently the GC hueristic won't kick in for quite
some time.

Release justification: bug fixes and low-risk updates to new functionality

Release note (general change): GC TTLs will now be enforced by default.
This enforcement can be controlled by disabling `kv.gc_ttl.strict_enforcement`

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45826)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/client_replica_test.go, line 2951 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-bBjzBqgZA7Vrdwu9:-M2-bBk-1ZfDcdB7WS-L:b-cq5ttl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/client_replica_test.go#L2951)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	// The unfortunate thing about this test is that the gcttl is in seconds and
> ```

How long does it take on average?
___
*[pkg/kv/kvserver/client_replica_test.go, line 3064 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-boU72ao15K83lh4w:-M2-boU72ao15K83lh4x:b-8li84r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/client_replica_test.go#L3064)):*
> ```Go
> 	t.Run("disable strict enforcement", func(t *testing.T) {
> 		sqlDB.Exec(t, `SET CLUSTER SETTING kv.gc_ttl.strict_enforcement = false`)
> 		defer sqlDB.Exec(t, `SET CLUSTER SETTING kv.gc_ttl.strict_enforcement = DEFAULT`)
> ```

Do you think it's worth structuring this test so that it will work regardless of whether `kv.gc_ttl.strict_enforcement` is defaulted to true or not (i.e. set to true at the beginning and avoid `DEFAULT`)?
___
*[pkg/kv/kvserver/client_replica_test.go, line 3104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-c9a56y1CJUPs-8Vz:-M2-c9a56y1CJUPs-8W-:b-yqmmhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/client_replica_test.go#L3104)):*
> ```Go
> 		// Let's now release the protected timestamp, refresh past that, then
> 		// make sure that we've got enforcement. Then let's add a new one.
> 		// That one should not see itself respect because we haven't verified.
> ```

Were you intending to extend this test?
___
*[pkg/kv/kvserver/replica.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-YkRz4LcORcFwfqvN:-M2-YkRz4LcORcFwfqvO:b29kfyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/replica.go#L458)):*
> ```Go
> 		draining bool
> 
> 		// protectedTimestampCache provides the state of the protected timestamp
> ```

s/protectedTimestampCache/cachedProtectedTS/
___
*[pkg/kv/kvserver/replica.go, line 737 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-Z3Kn6cheWyBmKcNs:-M2-Z3Kn6cheWyBmKcNt:bn5bube) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/replica.go#L737)):*
> ```Go
> 	impliedThreshold := gc.CalculateThreshold(now, *r.mu.zone.GC)
> 	if threshold.Less(impliedThreshold) {
> 		threshold = impliedThreshold
> ```

nit: consider using `.Forward()` in here in both places.
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-Zsh0A4LjG7-JKSpE:-M2-Zsh0A4LjG7-JKSpF:b-5dtv74) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/replica_protected_timestamp.go#L44)):*
> ```Go
> 
> // makeUpdateFunc returns a function which will attempt to update the Replica's
> // cached with cpts if it is non-empty. It assumes that the Replica is not
> ```

"with cpts"

this looks stale. Same issue below. I think you mean "ts".
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-aW0L31NELbzUa-z2:-M2-aW0L31NELbzUa-z3:b1pc86w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/replica_protected_timestamp.go#L46)):*
> ```Go
> // cached with cpts if it is non-empty. It assumes that the Replica is not
> // locked when the returned function is called.
> func (ts *cachedProtectedTimestampState) makeUpdateFunc(r *Replica) func() {
> ```

I feel like this would be cleaner as a method on `Replica` instead of a closure capturing the `cachedProtectedTimestampState` reference and the `Replica` reference, but I guess this is fine if you prefer this structure.
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-aC5w0qOWoM1O-zFl:-M2-aC5w0qOWoM1O-zFm:b-aztvky) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/replica_protected_timestamp.go#L60)):*
> ```Go
> 
> // clearIfNotNewer clears the state in cpts if it is not newer than the passed
> // ts. This will enable the fastpath in the update func.
> ```

Could you make it clear that this is an optimization and describe how it works. It's pretty subtle that we're including this in the rlock path to avoid hitting the wlock path in `makeUpdateFunc`.
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-_G1-5AWRNhiMOPXI:-M2-_G1-5AWRNhiMOPXJ:bhqcepi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/replica_protected_timestamp.go#L105)):*
> earliestValidRecord

Bad copy-paste?
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-_TFC4cpmAaWneWRW:-M2-_TFC4cpmAaWneWRX:bunm6c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a99194d5933b900b7e84e19d37996ddda55874cb/pkg/kv/kvserver/replica_protected_timestamp.go#L123)):*
> ```Go
> 				seen = true
> 			}
> 			return !seen
> ```

We lost the early return here. Don't we want that? It shouldn't be hard to add it back in.
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-_jb61a49EM8VBWzU:-M2-_jb61a49EM8VBWzV:b-7rdsq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/replica_protected_timestamp.go#L166)):*
> ```Go
> 	// here. If we do so, update the replica's cache of its state. The guarantee
> 	// we provide is that if a record is successfully verified then the state will
> 	// be updated to include it or some protected timestamp which precedes it.
> ```

Precedes it or follows it? I thought we're ratcheting the timestamp in `cachedProtectedTimestampState` up.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45826)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/client_replica_test.go, line 2951 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-bBjzBqgZA7Vrdwu9:-M2-kFB7ARNuOyIJ-u69:bu7ro4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/client_replica_test.go#L2951)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How long does it take on average?
</blockquote></details>

```
--- PASS: TestStrictGCEnforcement (1.75s)
    --- PASS: TestStrictGCEnforcement/strict_enforcement (0.00s)
    --- PASS: TestStrictGCEnforcement/disable_strict_enforcement (0.04s)
    --- PASS: TestStrictGCEnforcement/zone_config_changes_are_respected (0.08s)
    --- PASS: TestStrictGCEnforcement/system_ranges_are_unaffected (0.02s)
    --- PASS: TestStrictGCEnforcement/protected_timestamps_are_respected (0.04s)
```
___
*[pkg/kv/kvserver/client_replica_test.go, line 3064 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-boU72ao15K83lh4w:-M2-kH4I2jdslu5LiJMB:boujqo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/client_replica_test.go#L3064)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think it's worth structuring this test so that it will work regardless of whether `kv.gc_ttl.strict_enforcement` is defaulted to true or not (i.e. set to true at the beginning and avoid `DEFAULT`)?
</blockquote></details>

sure, done. 
___
*[pkg/kv/kvserver/client_replica_test.go, line 3104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-c9a56y1CJUPs-8Vz:-M2-oqYW6tyXKi0pY_NO:bvvryq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/client_replica_test.go#L3104)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Were you intending to extend this test?
</blockquote></details>

I think I decided that there wasn't a lot of added value in this additional work. 
___
*[pkg/kv/kvserver/replica.go, line 737 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-Z3Kn6cheWyBmKcNs:-M2-rpxlDDu3rt_cSyeU:bn4vz95) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/replica.go#L737)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider using `.Forward()` in here in both places.
</blockquote></details>

Done here. The one on the other side is not a forward, it's a backwards if you will. I added a comment.
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-aW0L31NELbzUa-z2:-M2-rwKhCIg9Qv_pFhPY:b-9ncr7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/replica_protected_timestamp.go#L46)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I feel like this would be cleaner as a method on `Replica` instead of a closure capturing the `cachedProtectedTimestampState` reference and the `Replica` reference, but I guess this is fine if you prefer this structure.
</blockquote></details>

That's better. 
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-_TFC4cpmAaWneWRW:-M2-zfD46yaKMj6eYVAB:bolejvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a99194d5933b900b7e84e19d37996ddda55874cb/pkg/kv/kvserver/replica_protected_timestamp.go#L123)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We lost the early return here. Don't we want that? It shouldn't be hard to add it back in.
</blockquote></details>

Yes, that was intentional. If we early return we may miss a different earliest valid record and we wouldn't be able to reliably update the state. 
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2-_jb61a49EM8VBWzU:-M2-z-Fq1a5nzdGC-kKc:b-bdloez) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5c6f5c31880e1ccb8becc3c652eb7845e43ea4/pkg/kv/kvserver/replica_protected_timestamp.go#L166)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Precedes it or follows it? I thought we're ratcheting the timestamp in `cachedProtectedTimestampState` up.
</blockquote></details>

Well, we're ratcheting `readAt` but we're not obviously changing the earliest record. Hence the confusion. 

I've tried to make the comment clearer.

**Comment by ajwerner** [comment]
@nvanbenschoten this is RFAL

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-:-M2AGrME5--N-Aj2IGPX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/helpers_test.go, line 473 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2AGHU955LiPESGNK3u:-M2AGHUA1cw8QfG7ds-O:bcixp0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/60fdd29291ded9bf936f2e8b02872e2076581cfb/pkg/kv/kvserver/helpers_test.go#L473)):*
> ```Go
> }
> 
> func (r *Replica) ReadProtectedTimestamps() {
> ```

Should this take a `context.Context`?

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-:-M2AIWKWCDo0gqYxn7mr:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/helpers_test.go, line 473 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2AGHU955LiPESGNK3u:-M2AIOW04w9jO17fF_0i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60fdd29291ded9bf936f2e8b02872e2076581cfb/pkg/kv/kvserver/helpers_test.go#L473)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this take a `context.Context`?
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, 2 of 2 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-:-M2AjySk9C9G-O8E9710:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2325 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2AjTC-9JRxIrrAZ2Px:-M2AjTC-9JRxIrrAZ2Py:b6i8m5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/984e50ad6993277b58bb3fcf8acc7c3a415acdde/pkg/ccl/changefeedccl/changefeed_test.go#L2325)):*
> ```Go
> 	) *roachpb.Error {
> 		if r, ok := ba.GetArg(roachpb.AdminVerifyProtectedTimestamp); ok {
> ```

nit: stray line
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2327 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2Ajd0b3igOykSwqhdQ:-M2Ajd0b3igOykSwqhdR:b-8f7kqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/984e50ad6993277b58bb3fcf8acc7c3a415acdde/pkg/ccl/changefeedccl/changefeed_test.go#L2327)):*
> ```Go
> 
> 			verifyRequestCh <- r.(*roachpb.AdminVerifyProtectedTimestampRequest)
> 			return roachpb.NewError(errors.New("boom"))
> ```

What error does `AdminVerifyProtectedTimestamp` return when it fails? Consider returning that here instead of this fake error so that readers of the test are more clear about why this might fail.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2350 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2Ajq419g-7NW75u7PG:-M2Ajq419g-7NW75u7PH:blg3y1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/984e50ad6993277b58bb3fcf8acc7c3a415acdde/pkg/ccl/changefeedccl/changefeed_test.go#L2350)):*
> ```Go
> 			pts := cfg.ProtectedTimestampProvider
> 			// Make sure that the canceled job gets moved through its OnFailOrCancel
> 			// phase.
> ```

"phase and removes its protected timestamp."
___
*[pkg/jobs/jobs.go, line 819 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2Aiknm1vLbRME2UMTr:-M2Aiknm1vLbRME2UMTs:b3nxp40) ([raw file](https://github.com/cockroachdb/cockroach/blob/db4c0c127525b427f6b83135c89fcfc4be65a51d/pkg/jobs/jobs.go#L819)):*
> ```Go
> func (sj *StartableJob) Cancel(ctx context.Context) error {
> 	defer sj.registry.unregister(*sj.ID())
> 	return sj.registry.CancelRequested(ctx, nil, *sj.id)
> ```

nit: why the `sj.ID()` vs `sj.id`?

**Review by ajwerner — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-:-M2AmAlJ7FWVu_hjfALP:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2325 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2AjTC-9JRxIrrAZ2Px:-M2AlRTW7pwc-LrApbJs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/984e50ad6993277b58bb3fcf8acc7c3a415acdde/pkg/ccl/changefeedccl/changefeed_test.go#L2325)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: stray line
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2327 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2Ajd0b3igOykSwqhdQ:-M2AkV0B6AzMpDhKDw1f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/984e50ad6993277b58bb3fcf8acc7c3a415acdde/pkg/ccl/changefeedccl/changefeed_test.go#L2327)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What error does `AdminVerifyProtectedTimestamp` return when it fails? Consider returning that here instead of this fake error so that readers of the test are more clear about why this might fail.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2350 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2Ajq419g-7NW75u7PG:-M2Alt_R1A-G_IL1rwCz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/984e50ad6993277b58bb3fcf8acc7c3a415acdde/pkg/ccl/changefeedccl/changefeed_test.go#L2350)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"phase and removes its protected timestamp."
</blockquote></details>

Done.
___
*[pkg/jobs/jobs.go, line 819 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-M2Aiknm1vLbRME2UMTr:-M2AlZHT4N3XsQImBqlY:b-kf8be7) ([raw file](https://github.com/cockroachdb/cockroach/blob/db4c0c127525b427f6b83135c89fcfc4be65a51d/pkg/jobs/jobs.go#L819)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: why the `sj.ID()` vs `sj.id`?
</blockquote></details>

no reason, made it consistent with the rest of the file.

**Review by ajwerner — COMMENTED** [review]
bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45826#-:-M2AnGu4E22FTompkJjo:b-nvg7rs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Comment by ajwerner** [comment]
Release justification.

bors r=nvanbenschoten

**Comment by ajwerner** [comment]
Flaked in something with protos and js? 

bors r+

**Comment by ajwerner** [comment]
flaked on https://github.com/cockroachdb/cockroach/issues/28033

bors r+

**Comment by pbardea** [comment]
@ajwerner does this close #45037?

**Comment by ajwerner** [comment]
Indeed!

**Pull request merged**
