### PR TITLE
kvserver: bound the number of scatter operations per range

### PR DESCRIPTION
**Pull request by aayushshah15**
After #75894, on every `(replicateQueue).processOneChange` call with the
`scatter` option set, stores in the cluster are essentially randomly
categorized as "overfull" or "underfull" (replicas on overfull stores are then
rebalanced to the underfull ones). Since each existing replica will be on a
store categorized as either underfull or overfull, it can be expected to be
rebalanced with a probability of `0.5`. This means that, roughly speaking, for
`N` replicas, probability of a successful rebalance is `(1 - (0.5)^N)`.

The previous implementation of `adminScatter` would keep requeuing a range into
the `replicateQueue` until it hit an iteration where none of the range's
replicas could be rebalanced. This patch improves this behavior by ensuring
that ranges are only enqueued for scattering upto a pre-defined maximum number
of times.

Release justification: low risk improvement to current functionality

Release note: None

### CODE REVIEW

**Comment by aayushshah15** [comment]
Before this commit (yellow is the rate of `AdminScatter` calls):
before

After this commit: 
after

**Comment by aayushshah15** [comment]
___
*[pkg/kv/kvserver/replica_command.go, line 3321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77743#-My4TnQT7uY126J4i3gk:-My4TnQT7uY126J4i3gl:b1frjgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/80683f1eae4558db88c3229094ca7d11329f83a7/pkg/kv/kvserver/replica_command.go#L3321)):*
> ```Go
> 	// number of times we try to scatter a particular range to a reasonable
> 	// function of its replication factor.
> 	maxAttempts := len(r.Desc().Replicas().Descriptors())/2 + 1
> ```

This was just a random choice. Should we simply be setting this to the replication factor instead?

**Comment by aayushshah15** [comment]
For posterity, here are the import times for TPCC 10K on a 10 node cluster across the commit _before_ https://github.com/cockroachdb/cockroach/pull/75894, `master` and this PR.

Commit before https://github.com/cockroachdb/cockroach/pull/75894:
```
imported 686 GiB bytes in 9 tables (took 17m56.61933797s, 652.34 MiB/s)
```

`master` (i.e. with https://github.com/cockroachdb/cockroach/pull/75894):
```
imported 686 GiB bytes in 9 tables (took 25m58.282284537s, 450.70 MiB/s)
```

This PR:  
```
imported 686 GiB bytes in 9 tables (took 20m52.06350545s, 560.93 MiB/s)
```

cc @dt. Looks like this oversight in `AdminScatter` definitely made things worse with non-empty range scatters.

**Review by nvb — APPROVED** [review]
Nice catch! :lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77743#-:-My5E59t-96YxBohytmZ:bppivfc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/replica_command.go, line 3321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77743#-My4TnQT7uY126J4i3gk:-My5DtizET-Me89cmBjI:b-7vy9md) ([raw file](https://github.com/cockroachdb/cockroach/blob/80683f1eae4558db88c3229094ca7d11329f83a7/pkg/kv/kvserver/replica_command.go#L3321)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

This was just a random choice. Should we simply be setting this to the replication factor instead?
</blockquote></details>

Setting this to the replication factor feels like it makes sense. Otherwise, there is no way for the range to replace all of its replicas.

**Review by aayushshah15 — COMMENTED** [review]
TFTR 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77743#-:-My5JYIY-dPUpQxpgjgL:b-l4uzs0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_command.go, line 3321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77743#-My4TnQT7uY126J4i3gk:-My5JX3O6oNPFEBJIEjR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80683f1eae4558db88c3229094ca7d11329f83a7/pkg/kv/kvserver/replica_command.go#L3321)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Setting this to the replication factor feels like it makes sense. Otherwise, there is no way for the range to replace all of its replicas.
</blockquote></details>

Done.

**Comment by dt** [comment]
Does this need a 22.1 backport?

**Comment by aayushshah15** [comment]
I think this patch landed right before the branch cut, so it seems to be in `release-22.1`
```
> git log v22.1.0-alpha.4 | grep '77743'
    Merge #77743
    77743: kvserver: bound the number of scatter operations per range r=aayushshah15 a=aayushshah15
```

**Comment by dt** [comment]
Ah, perfect, thanks and sorry for the noise!

**Pull request merged**
