### PR TITLE
kvserver: introduce ProbeRequest

### PR DESCRIPTION
**Pull request by tbg**
This commit introduces a new KV request type `ProbeRequest`. This
request performs a mutationless round-trip through the replication
layer. The proximate reason to add this request is #33007, where we want
to fail-fast requests on a Replica until a `ProbeRequest` succeeds.

The alternative to introducing a new request type is using a a `Put` on
`keys.RangeProbeKey` (a key introduced for [kvprober]). However, when
the Replica circuit breakers perform a probe, they have to make sure
that this probe doesn't get caught up in the circuit breakers
themselves. In particular, the circuit breaker's request needs special
casing with respect to lease requests (which would otherwise also bounce
on the circuit breaker), and in particular we would also like the probe
to be proposed (via the local raft instance) when the local replica is
not the leaseholder, as this allows the circuit breakers to cover more
ground and ascertain that the Replica has access to the replication
layer regardless of its status.

`ProbeRequest` bypasses lease checks and can thus be processed by any
Replica. Upon application, they are guaranteed to result in a forced
error, and we suppress this error above the replication layer (i.e. at
the waiting request). This means that receiving a nil error from the
probe implies that the probe successfully made it through latching,
evaluation, and application.

While no concrete plans exist for adoption of `ProbeRequest` elsewhere,
this might be of interest for [kvprober] and as a general building block
for quickly assessing overall KV health; for example we may extend #72732
to facilitate sending a probe to the leaseholders of all Ranges in the
system.

`ProbeRequest` is a point request. A ranged version is possible but
since `DistSender` will not return partial responses, it is not
introduced at this point. This can be done when a concrete need
arises.

`ProbeRequest` by default will be routed to the leaseholder, but it
can also be used with the `NEAREST` routing policy.

[kvprober]: https://github.com/cockroachdb/cockroach/tree/2ad2bee257e78970ce2c457ddd6996099ed6727a/pkg/kv/kvprober
[routing policy]: https://github.com/cockroachdb/cockroach/blob/e1c7d6a55ed147aeb20d6d5c564d3d9bf73d2624/pkg/roachpb/api.proto#L48-L60

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72972)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgDILxCMzB87CwxDSJ):*
"a a"
___
*[-- commits, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgEn06-jXkyNiB6jOe):*
It might be useful to, in the future, extend this with a variant that also respects the lease (e.g. with a request parameter). This might make sense e.g. for kvprober, which I suppose would ultimately want to know that the lease is also valid and able to propose and apply a command. I don't think there should be anything preventing this, right?
___
*[-- commits, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgFRtW8xQGTEjg4MoJ):*
`Fitler` → `Filter`
___
*[pkg/kv/kvserver/replica_application_state_machine.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgPV-95xJZ9fxyz-xr:-MpgPV-95xJZ9fxyz-xs:bx670el) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_application_state_machine.go#L175)):*
> ```Go
> // corresponding to a ProbeRequest is handled.
> //
> // This error is used with `errors.Is`, so don't change it or mixed-version
> ```

I don't think this is accurate. The error is instantiated on the local node during command application, and the `errors.Is()` check is also done on the local node after passing it via local memory, so it shouldn't be possible to get an error from a different version here.
___
*[pkg/kv/kvserver/replica_application_state_machine.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgMrVD1vRpMWd5WP0C:-MpgMrVD1vRpMWd5WP0D:brz1url) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_application_state_machine.go#L204)):*
> ```Go
> 	replicaState *kvserverpb.ReplicaState,
> ) (uint64, proposalReevaluationReason, *roachpb.Error) {
> 	if raftCmd.ReplicatedEvalResult.IsProbe {
> ```

Update the function comment to describe this condition as well.
___
*[pkg/kv/kvserver/replica_application_state_machine.go, line 1278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgNe5S27ntJqzQkgUS:-MpgNe5S27ntJqzQkgUT:b1yqeoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_application_state_machine.go#L1278)):*
> ```Go
> 	// NB: we intentionally never zero out rResult.IsProbe because probes are
> 	// implemented by always catching a forced error and thus never show up in
> 	// this method.
> ```

Consider adding a sentence saying that this effectively asserts that `IsProbe` returned a forced error.
___
*[pkg/kv/kvserver/replica_probe_test.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgTS6U5ulkXyU-EGEl:-MpgTS6U5ulkXyU-EGEm:bvemuvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_probe_test.go#L33)):*
> ```Go
> // TestReplicaProbeRequest verifies that all Replicas can serve a ProbeRequest,
> // and that it applies downstream of raft via a forced error.
> func TestReplicaProbeRequest(t *testing.T) {
> ```

Consider adding a test-case when there is no leader as well, to make sure it actually fails/times out when the Raft group can't make progress. It's arguably a bit overkill, but that is the crucial property that we want from these requests.
___
*[pkg/kv/kvserver/replica_probe_test.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgSBLg8XUVZjp9VbOO:-MpgSBLg8XUVZjp9VbOP:b-ao12rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_probe_test.go#L52)):*
> ```Go
> 		}
> 		if args.ForcedError == nil {
> 			t.Error("probe has no forcedError") // avoid Fatal on goroutine
> ```

I believe you could do `if !assert.NotNil { return 0, args.ForcedError }` here as well.
___
*[pkg/kv/kvserver/replica_probe_test.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgT4mbELYlLslF4xdg:-MpgT4mbELYlLslF4xdh:bo1d5nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_probe_test.go#L116)):*
> ```Go
> 			return errors.Errorf("waiting for stores to apply command: %d/%d", act, exp)
> 		}
> 		n := 2 * len(tc.Servers) // sent two probes per server
> ```

Do we want to assert the routing policies here, or is that out of scope?
___
*[pkg/kv/kvserver/replica_probe_test.go, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgTL_7Be0T9FWo0Jda:-MpgTL_7Be0T9FWo0Jdb:bsjxw8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_probe_test.go#L152)):*
> ```Go
> 		ba.Add(probeReq)
> 		_, pErr := repl.Send(ctx, ba)
> 		require.True(t, errors.Is(pErr.GoError(), injErr.GoError()), "%+v", pErr.GoError())
> ```

`require.ErrorIs()`
___
*[pkg/kv/kvserver/replica_raft.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgJ9i-6kVX9dzCtgSm:-MpgJ9i-6kVX9dzCtgSn:b-8ywivg) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_raft.go#L184)):*
> ```Go
> 		// to mutate state.
> 		var seq roachpb.LeaseSequence
> 		switch t := ba.Requests[0].GetInner().(type) {
> ```

I'd prefer to keep this in `GetPrevLeaseForLeaseRequest()` and return a zero-valued lease (or separate `ok` boolean) for irrelevant request types, to keep this sort of request logic in one place.
___
*[pkg/kv/kvserver/replica_write.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgLazd1Zajx5x7qmlW:-MpgLazd1Zajx5x7qmlX:b-v0737r) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_write.go#L276)):*
> ```Go
> 				propResult.Err = roachpb.NewError(applicationErr)
> 			}
> 			if propResult.Err != nil && ba.IsSingleProbeRequest() && errors.Is(propResult.Err.GoError(), noopOnProbeCommandErr.GoError()) {
> ```

Wrap at 100.
___
*[pkg/kv/kvserver/testing_knobs.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgRS6j7YRE-6sHfScs:-MpgRS6j7YRE-6sHfSct:b-e65jb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/testing_knobs.go#L72)):*
> ```Go
> 	// *Error replace the existing proposalReevaluationReason (if initially zero
> 	// only) and forced error.
> 	TestingApplyForcedErrFilter kvserverbase.ReplicaApplyFilter
> ```

It's unclear to me why `TestingApplyFilter` couldn't handle this case as well.
___
*[pkg/kv/kvserver/batcheval/cmd_probe.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgIDod3r2Ui3DF0mmo:-MpgIDod3r2Ui3DF0mmp:bir1qmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/batcheval/cmd_probe.go#L28)):*
> ```Go
> // Probe causes an effectless round-trip through the replication layer,
> // i.e. it is a write that does not change any kv pair. It declares a
> // read on the targeted key.
> ```

It declares read/write on the targeted key, but only with a latch (no lock).
___
*[pkg/roachpb/api.proto, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgGFcn4tK7tJnF1asb:-MpgGFcn4tK7tJnF1asc:b915305) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/roachpb/api.proto#L178)):*
> ```protobuf
> // latches, and declare key access, but it will not check locks (i.e.
> // if an intent exists on the key that is being probed, the probe will
> // not observe it). ProbeRequest can be served by any Replica including
> ```

Consider being explicit about bypassing the lease here, i.e. it checks that the Raft group can make progress but not that the leaseholder (and thus the range) can make progress.

**Review by tbg — COMMENTED** [review]
TFTR! I addressed all the small fry, didn't touch the test yet since I had a question about whether we even want to acquire any latch here, let's discuss that and then I will address the remaining open comments.
I "dismissed" you from all comments that were 100% trivial (I think your default disposition is different from most reviewers', might be something to look into for you, may not be intentional)

> Dismissed @erikgrinaker from 9 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-:-Mpuey0286SCKft6fdV6:b-edcygd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @tbg)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgDILxCMzB87CwxDSJ):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

"a a"
</blockquote></details>

Done.
___
*[-- commits, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgEn06-jXkyNiB6jOe):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

It might be useful to, in the future, extend this with a variant that also respects the lease (e.g. with a request parameter). This might make sense e.g. for kvprober, which I suppose would ultimately want to know that the lease is also valid and able to propose and apply a command. I don't think there should be anything preventing this, right?
</blockquote></details>

Yeah, should be possible, but doesn't seem necessary and I'm also not sure there is a strong case for a lease-respecting probe for `kvprober` since it can do the same thing using the existing KV API (it's doing that now) and I'd rather not complicate our KV API.
___
*[-- commits, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgFRtW8xQGTEjg4MoJ):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

`Fitler` → `Filter`
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_application_state_machine.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgPV-95xJZ9fxyz-xr:-MpuYWY4CfcWoow7NOsm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_application_state_machine.go#L175)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I don't think this is accurate. The error is instantiated on the local node during command application, and the `errors.Is()` check is also done on the local node after passing it via local memory, so it shouldn't be possible to get an error from a different version here.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_application_state_machine.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgMrVD1vRpMWd5WP0C:-MpuZ73w4JHyau_AiPTY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_application_state_machine.go#L204)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Update the function comment to describe this condition as well.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_application_state_machine.go, line 1278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgNe5S27ntJqzQkgUS:-MpuZFIm48Pkj8xnyoUd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_application_state_machine.go#L1278)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Consider adding a sentence saying that this effectively asserts that `IsProbe` returned a forced error.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_probe_test.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgSBLg8XUVZjp9VbOO:-MpuZLN2A_gxvT6xjrNM:b-zebnrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_probe_test.go#L52)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I believe you could do `if !assert.NotNil { return 0, args.ForcedError }` here as well.
</blockquote></details>

That would work, but we don't use `assert` much and I want to be extra clear here.
___
*[pkg/kv/kvserver/replica_probe_test.go, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgTL_7Be0T9FWo0Jda:-Mpu_yA2CWUu_1vfQ63W:b-rwu9s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_probe_test.go#L152)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

`require.ErrorIs()`
</blockquote></details>

No, we need `cockroachdb/errors.Is` here. I think this is because we are round-tripping through `(roachpb.Error).EncodedErr`:

```
        	Error:      	Target error should be in err chain:
        	            	expected: "kv/kvserver/replica_probe_test.go:139: bang"
        	            	in chain: "kv/kvserver/replica_probe_test.go:139: bang"
        	            		"kv/kvserver/replica_probe_test.go:139: bang"
        	            		"bang"
        	            		"bang"
```
___
*[pkg/kv/kvserver/replica_raft.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgJ9i-6kVX9dzCtgSm:-Mpua9--7HLlCzGc2_Zu:beuajcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_raft.go#L184)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I'd prefer to keep this in `GetPrevLeaseForLeaseRequest()` and return a zero-valued lease (or separate `ok` boolean) for irrelevant request types, to keep this sort of request logic in one place.
</blockquote></details>

This is bespoke logic for these requests that is part of how they evaluate, which is not something I like to see tucked far away in `roachpb`, which is why I inlined this code. I think the previous abstraction was premature and made me anxious about what exactly the contracts were.
___
*[pkg/kv/kvserver/replica_write.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgLazd1Zajx5x7qmlW:-Mpub0305euEjeGo4-0v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_write.go#L276)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Wrap at 100.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/testing_knobs.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgRS6j7YRE-6sHfScs:-Mpub1eT3DObW_hs1HSi:b-vx364p) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/testing_knobs.go#L72)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

It's unclear to me why `TestingApplyFilter` couldn't handle this case as well.
</blockquote></details>

All existing users of this filter would need to address the special case of getting a forced error. This would incur a large diff in this PR but also add a subtle condition that would need to be handled to all future users of this filter, which would likely be forgotten and lead to weird flakes in some cases.
___
*[pkg/kv/kvserver/batcheval/cmd_probe.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgIDod3r2Ui3DF0mmo:-MpubUQj6DUBPuHDQZpA:b-syarki) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/batcheval/cmd_probe.go#L28)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

It declares read/write on the targeted key, but only with a latch (no lock).
</blockquote></details>

Oh, you're right, thanks.

I have been a little torn over whether to declare keys at all. From a purity-based point of view it would be nice for this request to really only check the replication layer, i.e. completely bypass latching. From the POV of the circuit breaker though, you want to make sure that you trip if the replication layer is ok but something doesn't release the latch. I think I lean towards the pure approach and to solve the rest in the circuit breaker probe? So the probe would

- check replication layer via ProbeRequest
- check lease (which is now up to date thanks to having seen the probe pop up from below raft)
- if leaseholder is elsewhere & lease is valid, declare success
- send `ScanRequest(desc.Start, desc.End, limit=1)` (with special-cased ctx that bypasses circuit breaker, and also code that translates that ctx into the lease request which has its own ctx to prevent that from bouncing on the breaker)
- success

We want some of that lease stuff anyway, so baking a latch into ProbeRequest isn't really giving us a single-step circuit breaker probe, and the latch makes a failing probe just a little difficult to interpret since now there are more things that could block it.

WDYT?
___
*[pkg/roachpb/api.proto, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgGFcn4tK7tJnF1asb:-Mpuc2gk8BQIXT-T59N-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/roachpb/api.proto#L178)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Consider being explicit about bypassing the lease here, i.e. it checks that the Raft group can make progress but not that the leaseholder (and thus the range) can make progress.
</blockquote></details>

Done.

**Review by erikgrinaker — APPROVED** [review]
:lgtm: modulo the latch tweak and test improvements.

>I "dismissed" you from all comments that were 100% trivial (I think your default disposition is different from most reviewers', might be something to look into for you, may not be intentional)

Ah, yeah, it was set to blocking by default. I don't really use the disposition that actively, so changed it to discussing. Thanks for the heads-up.

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-:-MpvCn-p-lKmZJm_-nrY:b-bbj724)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[-- commits, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgEn06-jXkyNiB6jOe):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yeah, should be possible, but doesn't seem necessary and I'm also not sure there is a strong case for a lease-respecting probe for `kvprober` since it can do the same thing using the existing KV API (it's doing that now) and I'd rather not complicate our KV API.
</blockquote></details>

Suppose that's true.
___
*[pkg/kv/kvserver/replica_probe_test.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgSBLg8XUVZjp9VbOO:-MpvB8UT06A304BE1XcD:b4jild8) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_probe_test.go#L52)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

That would work, but we don't use `assert` much and I want to be extra clear here.
</blockquote></details>

Sure, nbd.
___
*[pkg/kv/kvserver/replica_probe_test.go, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgTL_7Be0T9FWo0Jda:-MpvBHZo1yfo2n4Ny03b:b-vii3eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/replica_probe_test.go#L152)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

No, we need `cockroachdb/errors.Is` here. I think this is because we are round-tripping through `(roachpb.Error).EncodedErr`:

```
        	Error:      	Target error should be in err chain:
        	            	expected: "kv/kvserver/replica_probe_test.go:139: bang"
        	            	in chain: "kv/kvserver/replica_probe_test.go:139: bang"
        	            		"kv/kvserver/replica_probe_test.go:139: bang"
        	            		"bang"
        	            		"bang"
```
</blockquote></details>

Ah, you're right, forgot about that part.
___
*[pkg/kv/kvserver/batcheval/cmd_probe.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72972#-MpgIDod3r2Ui3DF0mmo:-MpvBs9g2nAYP2wcuNpH:b1sm9te) ([raw file](https://github.com/cockroachdb/cockroach/blob/efc58094a3db9dcde9e9142d148403a7ba0ebd12/pkg/kv/kvserver/batcheval/cmd_probe.go#L28)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Oh, you're right, thanks.

I have been a little torn over whether to declare keys at all. From a purity-based point of view it would be nice for this request to really only check the replication layer, i.e. completely bypass latching. From the POV of the circuit breaker though, you want to make sure that you trip if the replication layer is ok but something doesn't release the latch. I think I lean towards the pure approach and to solve the rest in the circuit breaker probe? So the probe would

- check replication layer via ProbeRequest
- check lease (which is now up to date thanks to having seen the probe pop up from below raft)
- if leaseholder is elsewhere & lease is valid, declare success
- send `ScanRequest(desc.Start, desc.End, limit=1)` (with special-cased ctx that bypasses circuit breaker, and also code that translates that ctx into the lease request which has its own ctx to prevent that from bouncing on the breaker)
- success

We want some of that lease stuff anyway, so baking a latch into ProbeRequest isn't really giving us a single-step circuit breaker probe, and the latch makes a failing probe just a little difficult to interpret since now there are more things that could block it.

WDYT?
</blockquote></details>

I agree, I don't think latching adds anything here -- let's check that elsewhere in the circuit breaker.

**Comment by tbg** [comment]
bors r=erikgrinaker

**Pull request merged**
