### PR TITLE
sql: add crdb_internal views for system activity tables

### LINKED ISSUE #98882: sql: optimize system.statement_statistics and system.transaction_statistics for console
Problem:
system.statement_statistics and system.transaction_statistics are large tables which can take any where from several seconds to minutes to get results. This is not the ideal user experience. We need a design that allows fast response even if the users has a million rows in the system tables.

Solution:
Upon investigating it was discovered that most users don't need all the stmts/txns. Instead they only need the top 100 by a few different key columns. To take advantage of this 2 new tables should be created. They should follow a similar column structure as the existing tables. They will add new columns with indexes for the most popularly sorted fields. A new job will be created that will run once an hour and copy the top 500 stmts/txns for each of the 5 most popular columns to the new table. This way the table will only have a max of 2500 rows for a given time interval which will allow for a fast response. This will also reduce the overhead on the cluster as it will not need to query the million rows in the system table.

Jira issue: CRDB-25566

### PR DESCRIPTION
**Pull request by j82w**
This commit adds two new crdb_internal views:

crdb_internal.statement_activity, which surfaces the system.statement_activity table

crdb_internal.transaction_activity, which surfaces the system.transaction_statistics table

Epic: none
closes: #98882

Release note (sql change): Added two views to the crdb_internal catalog: crdb_internal.statement_activity, which surfaces data in the persisted system.statement_activity table, and crdb_internal.transaction_activity, which surfaces the system.transaction_activity table.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101916)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101916#-NTUanzG0WTD46dhkI_b:-NTUanzG0WTD46dhkI_c:b9kiyb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3042c4fee9457b4f05318fcfa9836433203430cb/pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant#L113)):*
> ```
> WHERE end_key > (SELECT crdb_internal.table_span($t_id)[1])
> ----
> {"gcPolicy": {"ttlSeconds": 14400}, "numReplicas": 3, "rangeMaxBytes": "67108864", "rangeMinBytes": "1048576"}
> ```

was this removed by accident?

**Review by maryliag — APPROVED** [review]
one nit, otherwise
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101916#-:-NTUhlRi1kzuVVEF5ucG:b-skcne8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/crdb_internal.go` line 6461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101916#-NTUh_wr7ML33a6j_2-n:-NTUh_wr7ML33a6j_2-o:b-75fxvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e773438ae970512762129e9f1e7e17ca9a46428/pkg/sql/crdb_internal.go#L6461)):*
> ```Go
> 
> // crdb_internal.statement_activity view to give permission to non-admins
> // to access the system.transaction_activity table
> ```

access system.statement_activity table

**Comment by j82w** [comment]
*[`pkg/sql/crdb_internal.go` line 6461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101916#-NTUh_wr7ML33a6j_2-n:-NTVCYksAeA4--fcmzUi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e773438ae970512762129e9f1e7e17ca9a46428/pkg/sql/crdb_internal.go#L6461)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

access system.statement_activity table
</blockquote></details>

Done.

**Comment by j82w** [comment]
blathers backport 23.1 23.1.0

**Pull request merged**
