### PR TITLE
sql/exec,storage/engine: Remove magic assembly files

### PR DESCRIPTION
**Pull request by bdarnell**
These assembly files no longer have any (intended) effect in go 1.12,
and their existence has proven surprisingly troublesome as their
comments indicated.

Release note: None

### CODE REVIEW

**Comment by bdarnell** [comment]
This is not to be merged until #38379 is.

**Comment by andreimatei** [comment]
you want me to merge this into #38379 ?

**Comment by bdarnell** [comment]
Sure, if you want to go through another CI cycle (I pushed this branch thinking you had already merged yours).

**Comment by bdarnell** [comment]
Closing in favor of #38379

**Pull request closed without merging**
