### PR TITLE
cherrypick-1.1: sql/pgwire,parser: render non-tz timestamp in its loc, set loc when c…

### LINKED ISSUE #16228: sql: casting timestamptz to timestamp not respecting timezone
**BUG REPORT**
Version:
```
Build Tag:    v1.0.1
Build Time:   2017/05/25 15:17:49
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.1
C Compiler:   gcc 6.3.0
Build SHA-1:  50fd18dcf8da75a0f4980344a885fe6105d0cf23
Build Type:   release
```
Code:
```
SET TIME ZONE 'Asia/Kolkata';
CREATE TABLE a (
	id INT NOT NULL DEFAULT unique_rowid(), 
	t TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT "primary" PRIMARY KEY (id ASC));
INSERT INTO a(t) VALUES (TIMESTAMPTZ '2017-01-01 00:00:00');
SELECT extract('year', t::TIMESTAMP) FROM a; -- Returns 2016
SELECT extract('year', t::DATE) FROM a; -- Returns 2017
```
Expected behaviour: Conversion of timestamptz to timestamp is expected to respect time zone as Postgres does that.

### PR DESCRIPTION
**Pull request by dt**
…asting

Updated logic test behaviors verified from postgres: when a timestamptz is cast to timestamp, the result renders a localized time, with no offset.

Fixes #16228.

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Review by justinj — APPROVED** [review]

**Comment by dt** [comment]
This also needs #18783 or another fix for #18774, so I'll wait to see how we resolve that on master before moving forward here.

**Comment by dt** [comment]
so #18783 feels a bit big, just in terms of files changed, for a late cherry-pick, though the actual change (`time.Unix()` vs `time.Unix().UTC()`) isn't that scary. We could potentially selectively `.UTC()`  just a couple callsites here instead. That said, this change, as-is, without ensuring we've `.UTC()`ed all the applicable paths, is potentially worse than just leaving the timestamp casts knonwn-broken?

**Comment by knz** [comment]
I think your patch in #18783 is acceptable for a cherry-pick. Although perhaps we need a second set of eyes to check.

**Comment by dt** [comment]
@knz okay, this now has #18676, #18553,  #18590 and #18783 so it's ready for another look. 
Also cc @bdarnell for thoughts on the scope here, as far as a cherrypick goes.

**Comment by bdarnell** [comment]
LGTM

**Comment by knz** [comment]
:lgtm: thank you!

---

Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 3 of 3 files at r3, 39 of 39 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18764#-:-Kv4KBGqP2Xiid2jYT8i:bro3093)*

**Pull request merged**
