### PR TITLE
server: evaluate decommission pre-checks

### PR DESCRIPTION
**Pull request by AlexTalks**
This adds support for the evaluation of the decommission readiness of a
node (or set of nodes), by simulating their liveness to have the
DECOMMISSIONING status and utilizing the allocator to ensure that we are
able to perform any actions needed to repair the range. This supports a
"strict" mode, in which case we expect all ranges to only need
replacement or removal due to the decommissioning status, or a more
permissive "non-strict" mode, which allows for other actions needed, as
long as they do not encounter errors in finding a suitable allocation
target. The non-strict mode allows us to permit situations where a range
may have more than one action needed to repair it, such as a range that
needs to reach its replication factor before the decommissioning replica
can be replaced, or a range that needs to finalize an atomic replication
change.

Depends on https://github.com/cockroachdb/cockroach/pull/94024.

Part of https://github.com/cockroachdb/cockroach/issues/91568

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93758)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[`pkg/server/decommission.go` line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-NLXO3LBEyFUuetm-7DC:-NLXO3LBEyFUuetm-7DD:b-yche8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e57036bc5b05ba00dbc4b434f00cbe140a7761d/pkg/server/decommission.go#L51)):*
> ```Go
> type decommissionRangeCheckResult struct {
> 	desc         *roachpb.RangeDescriptor
> 	action       allocatorimpl.AllocatorAction
> ```

It would be nice if the allocator action didn't leak into the server pkg here. We discussed offline that this will only RPC the string.
___
*[`pkg/server/decommission.go` line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-NLXLWtlDxEc4vTbiyK-:-NLXLWtlDxEc4vTbiyK0:b-dc4nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e57036bc5b05ba00dbc4b434f00cbe140a7761d/pkg/server/decommission.go#L168)):*
> ```Go
> 	nodeIDs []roachpb.NodeID,
> 	strictReadiness bool,
> 	collectTraces bool,
> ```

See below comment on trace overhead at high decommission replica count when this is enabled
___
*[`pkg/server/decommission.go` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-NLXKFSn9HB2zDujRf46:-NLXKFSn9HB2zDujRf47:b-ea4u8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e57036bc5b05ba00dbc4b434f00cbe140a7761d/pkg/server/decommission.go#L252)):*
> ```Go
> 			}
> 
> 			action, _, recording, rErr := evalStore.AllocatorCheckRange(ctx, &desc, overrideStorePool)
> ```

What is the expected mem overhead of collecting a trace recording on every range containing a replica on a decommissioning  node?

I see that the check can pass in a list of Nodes that are to be decommissioned so it's foreseeable that you could be collecting a few hundred k traces (especially with multi-store).
___
*[`pkg/server/decommission_test.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-NLXM2zg4UVAX3oVl7OM:-NLXM2zg4UVAX3oVl7ON:bb770qx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e57036bc5b05ba00dbc4b434f00cbe140a7761d/pkg/server/decommission_test.go#L170)):*
> ```Go
> 	hasAll := true
> 	for _, idx := range serverIdxs {
> 		hasAll = hasAll && desc.Replicas().HasReplicaOnNode(tc.Server(idx).NodeID())
> ```

nit: Why not just return early here?

```go
for (...) {
    if !desc.Replicas().HasReplicaOnNode(tc.Server(idx).NodeID()) {
        return false
    }
}
return true
```

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93758)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/server/decommission.go` line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-NLXO3LBEyFUuetm-7DC:-NM4vZI2BNCdMp49Xt6g:b-tz6hzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e57036bc5b05ba00dbc4b434f00cbe140a7761d/pkg/server/decommission.go#L51)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It would be nice if the allocator action didn't leak into the server pkg here. We discussed offline that this will only RPC the string.
</blockquote></details>

From the RPC, yes, but the action is used within the evaluation to determine a few things (see `evaluateRangeCheckResult`).  In this return struct I can use a string of course, though it means the `AllocatorAction` will still be used in the server pkg.
___
*[`pkg/server/decommission.go` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-NLXKFSn9HB2zDujRf46:-NM4woNd-ZWco0r8ZaQU:bitpx2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e57036bc5b05ba00dbc4b434f00cbe140a7761d/pkg/server/decommission.go#L252)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

What is the expected mem overhead of collecting a trace recording on every range containing a replica on a decommissioning  node?

I see that the check can pass in a list of Nodes that are to be decommissioned so it's foreseeable that you could be collecting a few hundred k traces (especially with multi-store).
</blockquote></details>

This is a good point and was one of the things I most wanted input on in this review.  Especially since right now, it's collecting traces always, and just returning them if `collectTraces` is on.

I think that we should collect traces only if requested, and we should also make sure we have a limit on the number of errors so that we can avoid huge memory overheads.
___
*[`pkg/server/decommission_test.go` line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-NLXM2zg4UVAX3oVl7OM:-NM4xaDlEAk3UD-kEpP1:b6gxpjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e57036bc5b05ba00dbc4b434f00cbe140a7761d/pkg/server/decommission_test.go#L170)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: Why not just return early here?

```go
for (...) {
    if !desc.Replicas().HasReplicaOnNode(tc.Server(idx).NodeID()) {
        return false
    }
}
return true
```
</blockquote></details>

Can do that.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93758)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/server/decommission.go` line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-NLXO3LBEyFUuetm-7DC:-NM6SGmv3-SKFgR72M4L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e57036bc5b05ba00dbc4b434f00cbe140a7761d/pkg/server/decommission.go#L51)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

From the RPC, yes, but the action is used within the evaluation to determine a few things (see `evaluateRangeCheckResult`).  In this return struct I can use a string of course, though it means the `AllocatorAction` will still be used in the server pkg.
</blockquote></details>

Done.
___
*[`pkg/server/decommission.go` line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-NLXLWtlDxEc4vTbiyK-:-NM6SOoh3lcqwdG0k5fh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e57036bc5b05ba00dbc4b434f00cbe140a7761d/pkg/server/decommission.go#L168)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

See below comment on trace overhead at high decommission replica count when this is enabled
</blockquote></details>

Done.
___
*[`pkg/server/decommission.go` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-NLXKFSn9HB2zDujRf46:-NM6SSC40sRB1GZyBq9C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e57036bc5b05ba00dbc4b434f00cbe140a7761d/pkg/server/decommission.go#L252)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

This is a good point and was one of the things I most wanted input on in this review.  Especially since right now, it's collecting traces always, and just returning them if `collectTraces` is on.

I think that we should collect traces only if requested, and we should also make sure we have a limit on the number of errors so that we can avoid huge memory overheads.
</blockquote></details>

Done.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93758#-:-NMFZckCEToWKCD1Q7Tk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks)

**Comment by AlexTalks** [comment]
bors r=kvoli

**Comment by AlexTalks** [comment]
bors r=kvoli

**Pull request merged**
