### PR TITLE
UI: Simplify typings

### PR DESCRIPTION
**Pull request by maxlang**
---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7246)

### CODE REVIEW

**Comment by mrtracy** [comment]
Good idea, LGTM

**Comment by tamird** [comment]
Looks like lint failed: 
```
app/containers/banner/helpusBanner.tsx[9, 39]: unused variable: 'KeyValue'

app/containers/helpus.tsx[5, 39]: unused variable: 'KeyValue'

Makefile:34: recipe for target 'lint' failed
```

LGTM though

**Comment by maxlang** [comment]
Whoops! Removed the unused typings and fixed one broken typing in a test.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 11 of 13 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ui/next/app/containers/events.spec.tsx, line 13 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246#-KKLkPFqVAu5plKkF_ZV:-KKLkPFqVAu5plKkF_ZW:-1109649605) ([raw file](https://github.com/cockroachdb/cockroach/blob/929b5bce3638864f2efa8d621306d36eb79ae4b0/ui/next/app/containers/events.spec.tsx#L13)):*
> ```XML
> type Event = cockroach.server.serverpb.EventsResponse.Event;
> 
> function makeEventList(events: Event[], refreshEvents: () => any) {
> ```

wait, why did this change? How did it compile before?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246#-:-KKLkM5N8caYFNZJdNTZ:1417088721)*

**Comment by maxlang** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ui/next/app/containers/events.spec.tsx, line 13 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246#-KKLkPFqVAu5plKkF_ZV:-KKLlQivBAML2drDWc6d:176615522) ([raw file](https://github.com/cockroachdb/cockroach/blob/929b5bce3638864f2efa8d621306d36eb79ae4b0/ui/next/app/containers/events.spec.tsx#L13)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> wait, why did this change? How did it compile before?
</details>
The typings have changed a little bit, since now they adhere more correctly to the actual types of the functions being passed in. The `refreshEvents` function returns a promise, but originally the `refreshEvents` type in the `EventListProps` interface was set manually to `() => void`. Now that we've switched the typings we just needed to relax the definition here. Otherwise it complained because I was passing something of type `() => void` into something that expected type `typeof refreshEvents`.

I could also import `refreshEvents` and make this `refreshEvents: typeof refreshEvents` but I felt that was overkill.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246)*

**Comment by tamird** [comment]
Reviewed 8 of 8 files at r1, 2 of 13 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ui/next/app/containers/events.spec.tsx, line 13 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246#-KKLkPFqVAu5plKkF_ZV:-KKLmd_j309fayf-4y0N:2096862608) ([raw file](https://github.com/cockroachdb/cockroach/blob/929b5bce3638864f2efa8d621306d36eb79ae4b0/ui/next/app/containers/events.spec.tsx#L13)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> The typings have changed a little bit, since now they adhere more correctly to the actual types of the functions being passed in. The `refreshEvents` function returns a promise, but originally the `refreshEvents` type in the `EventListProps` interface was set manually to `() => void`. Now that we've switched the typings we just needed to relax the definition here. Otherwise it complained because I was passing something of type `() => void` into something that expected type `typeof refreshEvents`.
> 
> I could also import `refreshEvents` and make this `refreshEvents: typeof refreshEvents` but I felt that was overkill.
</details>
I'd prefer that, FWIW.

I think we're greatly overusing `any` in general, so I'd be happy to see the scope of its usage reduced, even if it's a trivial case like this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246)*

**Comment by maxlang** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ui/next/app/containers/events.spec.tsx, line 13 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246#-KKLkPFqVAu5plKkF_ZV:-KKLsLlLpi4iMLVOTQi2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/929b5bce3638864f2efa8d621306d36eb79ae4b0/ui/next/app/containers/events.spec.tsx#L13)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'd prefer that, FWIW.
> 
> I think we're greatly overusing `any` in general, so I'd be happy to see the scope of its usage reduced, even if it's a trivial case like this one.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ui/next/app/containers/events.spec.tsx, line 13 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246#-KKLkPFqVAu5plKkF_ZV:-KKLsrIsP6p2_ICiZlY0:-1814265556) ([raw file](https://github.com/cockroachdb/cockroach/blob/929b5bce3638864f2efa8d621306d36eb79ae4b0/ui/next/app/containers/events.spec.tsx#L13)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Done.
</details>
why not inline it? no other file does the type alias.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246)*

**Comment by maxlang** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ui/next/app/containers/events.spec.tsx, line 13 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246#-KKLkPFqVAu5plKkF_ZV:-KKMQBnn_TED0yVj2t-g:1800277154) ([raw file](https://github.com/cockroachdb/cockroach/blob/929b5bce3638864f2efa8d621306d36eb79ae4b0/ui/next/app/containers/events.spec.tsx#L13)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why not inline it? no other file does the type alias.
</details>
Scoping. The argument is also named `refreshEvents` so the type is undefined. I renamed the variable instead. I could also import with an alias like: 

```import { refreshEvents as RefreshEvents } ...```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7246)*

**Pull request merged**
