### PR TITLE
sql/*: improve descs.Collection, clean up resolution

### PR DESCRIPTION
**Pull request by ajwerner**
The first few commits are trivial. The last commit got a bit away from me. It reworks the resolution logic to be more uniform. It's an intermediate step. It pulls the remaining portions of temporary and virtual resolution underneath the collection. The big change is that instead of returning name prefixes directly, we return the actual database and schema objects, along with some booleans indicating how explicitly they were named. 

There are some very minor behavior changes whereby, for virtual tables, if the database does note exist and was not stated explicitly, we return an error indicating that the relation does not exist. This seems like a purely good change.

### CODE REVIEW

**Review by postamar — APPROVED** [review]
I like this change a lot. LGTM modulo a few tiny things, also could you please flesh out your commit messages a tad? I'm not sure anyone chasing a bug with git-bisect or whatever who'd stumble on any of these commits would be terribly happy. Especially the last commit.

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 6 of 6 files at r3, 3 of 3 files at r4, 3 of 3 files at r5, 85 of 85 files at r6, 90 of 90 files at r7, 2 of 5 files at r8, 2 of 6 files at r9, 1 of 3 files at r10, 86 of 86 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-:-McsqsKtA__xsXV3jU25:bbq0uxm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @pbardea)

___
*[pkg/sql/resolver.go, line 462 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-McsoxmYDEvLM8QhIhIJ:-McsoxmYDEvLM8QhIhIK:b8fxbkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd867ab0a6bd9e6e2dba6c0e4efea0dfbf2eac/pkg/sql/resolver.go#L462)):*
> ```Go
> 	// the type reference resolver.
> 	//
> 	// TODO(ajwerner): Understand these reasons.
> ```

I'm curious too.
___
*[pkg/sql/catalog/descs/descriptor.go, line 167 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-Mcsqfjs1GrghK5Z6tn1:-Mcsqfjs1GrghK5Z6tn2:bdjs2d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd867ab0a6bd9e6e2dba6c0e4efea0dfbf2eac/pkg/sql/catalog/descs/descriptor.go#L167)):*
> ```Go
> 	switch {
> 	case db == nil && sc == nil:
> 		if db := maybeGetSystemDatabase(name, mutable); db != nil {
> ```

I noticed that if one calls`GetMutableDatabaseByName(ctx, txn, "system", ...)` then the resulting mutable system database descriptor comes out of nowhere, bypassing the uncommitted descriptors, ignoring `avoidCached` etc. Is this OK?
___
*[pkg/sql/catalog/descs/descriptor.go, line 267 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-McsqcjvAl-T3jeDwZ7O:-Mcsqcjw6grjTCKFXyuS:bej0vmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd867ab0a6bd9e6e2dba6c0e4efea0dfbf2eac/pkg/sql/catalog/descs/descriptor.go#L267)):*
> ```Go
> 	systemschema.JobsTable.GetName(),
> 	systemschema.EventLogTable.GetName(),
> }, "|"))
> ```

Isn't this regex pattern incorrect? It seems that it should be bracketed in `^` and `$` lest we one day add a new system table called `jobs_dependencies` which will incorrectly match on `...|jobs|...`.
___
*[pkg/sql/catalog/descs/object.go, line 60 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-McsqnyDCVtLTEfqx1RL:-McsqnyE3Z6eHjpgPVs8:b-rvetir) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd867ab0a6bd9e6e2dba6c0e4efea0dfbf2eac/pkg/sql/catalog/descs/object.go#L60)):*
> ```Go
> 			err = sqlerrors.NewUndefinedRelationError(&tn)
> 		}
> 	}()
> ```

I really like this pattern. It makes this function's body clean and easy to read.
___
*[pkg/sql/catalog/descs/temporary_descriptors.go, line 47 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-McspPHHAkcBpEPJnVcQ:-McspPHHAkcBpEPJnVcR:b-q0seqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd867ab0a6bd9e6e2dba6c0e4efea0dfbf2eac/pkg/sql/catalog/descs/temporary_descriptors.go#L47)):*
> ```Go
> // TODO(ajwerner): Understand and rationalize the namespace lookup given the
> // schema lookup by ID path only returns descriptors owned by this session.
> // TODO(ajwerner):
> ```

Missing comment?

**Review by ajwerner — COMMENTED** [review]
TFTR. I updated some of the more sparse comments. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-:-MctEbkQ3iyneLM6vOPS:bpqg9e2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @pbardea, and @postamar)

___
*[pkg/sql/catalog/descs/descriptor.go, line 167 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-Mcsqfjs1GrghK5Z6tn1:-Mct6Q_GDx7h1hSo_6Is:b11awql) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd867ab0a6bd9e6e2dba6c0e4efea0dfbf2eac/pkg/sql/catalog/descs/descriptor.go#L167)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I noticed that if one calls`GetMutableDatabaseByName(ctx, txn, "system", ...)` then the resulting mutable system database descriptor comes out of nowhere, bypassing the uncommitted descriptors, ignoring `avoidCached` etc. Is this OK?
</blockquote></details>

Good question. This preserves the existing behavior rather than questioning it. I think it's okay because users don't have rights to modify that descriptor and we don't have any migrations that modify that descriptor. All that being said, seems fine to read the descriptor transactionally if we're going to be modifying it. The hazard would be if we ever added a schema to the `system` database. See the comment in `maybeGetSystemDescriptor`. Do you want me to make a change here?
___
*[pkg/sql/catalog/descs/descriptor.go, line 267 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-McsqcjvAl-T3jeDwZ7O:-Mct66wdEEYG3cHRm48i:b-t2r6i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd867ab0a6bd9e6e2dba6c0e4efea0dfbf2eac/pkg/sql/catalog/descs/descriptor.go#L267)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Isn't this regex pattern incorrect? It seems that it should be bracketed in `^` and `$` lest we one day add a new system table called `jobs_dependencies` which will incorrectly match on `...|jobs|...`.
</blockquote></details>

 Done. 
___
*[pkg/sql/catalog/descs/temporary_descriptors.go, line 47 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-McspPHHAkcBpEPJnVcQ:-MctE9CH2IgCh-Ghi45w:b-507po1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd867ab0a6bd9e6e2dba6c0e4efea0dfbf2eac/pkg/sql/catalog/descs/temporary_descriptors.go#L47)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Missing comment?
</blockquote></details>

I don't recall :(

**Review by postamar — CHANGES_REQUESTED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-:-MctTRkh2guYA581vFEg:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @pbardea, and @postamar)

___
*[pkg/sql/catalog/descs/descriptor.go, line 167 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66697#-Mcsqfjs1GrghK5Z6tn1:-MctT7a60OXyVJ2of5A2:blrim7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd867ab0a6bd9e6e2dba6c0e4efea0dfbf2eac/pkg/sql/catalog/descs/descriptor.go#L167)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Good question. This preserves the existing behavior rather than questioning it. I think it's okay because users don't have rights to modify that descriptor and we don't have any migrations that modify that descriptor. All that being said, seems fine to read the descriptor transactionally if we're going to be modifying it. The hazard would be if we ever added a schema to the `system` database. See the comment in `maybeGetSystemDescriptor`. Do you want me to make a change here?
</blockquote></details>

I realized after the fact that this preserves the existing behaviour. No further change needed as far as I'm concerned.

**Review by postamar — APPROVED** [review]
> Reviewed 91 of 91 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @pbardea, and @postamar)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
