### PR TITLE
acceptance test: let new v2.0 node join v1.1 cluster

### LINKED ISSUE #24248: roachtest: let new node join mixed cluster in version upgrade test
To exercise https://github.com/cockroachdb/cockroach/pull/24241.

### PR DESCRIPTION
**Pull request by ghost**
Added a step in TestVersionUpgrade that tests a fresh node running v2.0 can
join a cluster with version 1.1.

Fixes #24248.
Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/acceptance/version_upgrade_test.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25236#-LBwx8ET1OWmuyBhkLky:-LBwx8ET1OWmuyBhkLkz:b-m21rct) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed4534f75921423fb3fa691afc713f27234322df/pkg/acceptance/version_upgrade_test.go#L256)):*
> ```Go
> 		clusterVersionUpgrade("1.1"),
> 
> 		binaryVersionUpgrade{newVersion: "v2.0.0", nodes: []int{min(3, len(cfg.Nodes)) - 1}},
> ```

rename this field to `wipe` or `wipeNodes` with an associated comment on the field and this line (to explain why you wipe in this step specifically).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25236#-:-LBwy5nc1nCjKtrwYC_x:bnfp4nl)*

**Comment by tschottdorf** [comment]
@windchan7 wanna merge this?

**Comment by windchan7** [comment]
@tschottdorf , thank you!

**Pull request merged**
