### PR TITLE
roachtest: move quota inside test runner

### PR DESCRIPTION
**Pull request by RaduBerinde**
Currently the quota is freed by the cluster when it is destroyed. But
this is not always what we want, so there is fragile logic around
removing the allocation from the cluster before destruction.

This change simplifies this by removing the cluster's responsibility
for the allocation. Now the main worker loop manages the quota
allocation, which makes things a lot simpler.

We reorganize the main loop to separately look for a test that can
reuse the cluster, and if that fails destroy the cluster and release
the allocation before looking for a new test. We now log when we
acquire, release, and wait for quota.

Epic: none
Release note: None

### CODE REVIEW

**Review by renatolabs — APPROVED** [review]
:lgtm:

Nice, this is a lot cleaner! Left some optional comments.

Given we know changes in the test runner are risky, I'd suggest merging this on Monday (or early next week) to avoid issues during the weekend.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112661#-:-NiLSq9127MN_J2x11mV:b-ccuy66)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`pkg/cmd/roachtest/test_runner.go` line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112661#-NiLMRIH-Z3lnkXIgDz8:-NiLMRIH-Z3lnkXIgDz9:b-faw3ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/d758dfa622c4a46a730a03db5ae083afb5a89557/pkg/cmd/roachtest/test_runner.go#L548)):*
> ```Go
> 			l.PrintfCtx(ctx, "Releasing quota for %s CPUs", alloc.String())
> 			qp.Release(alloc)
> 			alloc = nil
> ```

If this is necessary for correctness (I can't immediately see why), it would be great if we had a comment explaining it.
___
*[`pkg/cmd/roachtest/test_runner.go` line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112661#-NiLQUUY77Jj6ZSq0w3s:-NiLQUUY77Jj6ZSq0w3t:b1559ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/d758dfa622c4a46a730a03db5ae083afb5a89557/pkg/cmd/roachtest/test_runner.go#L850)):*
> ```Go
> 			}
> 			if clustersOpt.debugMode == DebugKeepAlways {
> 				// TODO(andrei): should we extend the cluster here? For how long?
> ```

Nit: this TODO could probably be removed as people have been using `--debug` for a while now and the request to automatically extend the lifetime hasn't come up (to my knowledge).
___
*[`pkg/cmd/roachtest/work_pool.go` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112661#-NiLRSZ76FxRnIRF5oa5:-NiLRSZ76FxRnIRF5oa6:b-pn0hm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d758dfa622c4a46a730a03db5ae083afb5a89557/pkg/cmd/roachtest/work_pool.go#L201)):*
> ```Go
> 	if !logTimer.Stop() {
> 		// It is possible that the function is starting to run right now; either
> 		// prevent the log or wait for it so the messages don't get scrambled.
> ```

Not sure I understand this comment; we don't seem to be waiting for anything here? I'm not sold that the complexity / added lines of code are justified by the small probability that we'll stop the log from firing. There's fundamentally a TOCTOU race here that I think is fine -- if we do log that line but the code is moving forward, it should be easy to understand from the context.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!  Good idea on merging Monday.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112661#-:-NiLWpTs2Y1lXzqaiF3H:b-7bkba4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs)

___
*[`pkg/cmd/roachtest/test_runner.go` line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112661#-NiLMRIH-Z3lnkXIgDz8:-NiLUTQP161jM1VnaMiU:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d758dfa622c4a46a730a03db5ae083afb5a89557/pkg/cmd/roachtest/test_runner.go#L548)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

If this is necessary for correctness (I can't immediately see why), it would be great if we had a comment explaining it.
</blockquote></details>

Removed.
___
*[`pkg/cmd/roachtest/work_pool.go` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112661#-NiLRSZ76FxRnIRF5oa5:-NiLUwECBVASTBVXMBoN:ben2a9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d758dfa622c4a46a730a03db5ae083afb5a89557/pkg/cmd/roachtest/work_pool.go#L201)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Not sure I understand this comment; we don't seem to be waiting for anything here? I'm not sold that the complexity / added lines of code are justified by the small probability that we'll stop the log from firing. There's fundamentally a TOCTOU race here that I think is fine -- if we do log that line but the code is moving forward, it should be easy to understand from the context.
</blockquote></details>

`Once.Do()` waits until any other in-progress `Do()` call completes.

I don't think `PrintfCtx` is safe to be called multiple times in parallel, so if I don't do something like this we may hit a race that's hard to debug. I simplified a tiny bit by not conditioning on stopping the timer.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112661)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[`pkg/cmd/roachtest/work_pool.go` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112661#-NiLRSZ76FxRnIRF5oa5:-NiLg4QR0LlfIQlWMnnx:b-kx89i2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d758dfa622c4a46a730a03db5ae083afb5a89557/pkg/cmd/roachtest/work_pool.go#L201)):*
> `Once.Do()` waits until any other in-progress `Do()` call completes

Ah I see, TIL.

> I don't think `PrintfCtx` is safe to be called multiple times in parallel

Is it not? A lot of tests write to the same `t.L()` instance in concurrent goroutines. I also see a lot of synchronization code in the logger implementation. Unless there's a specific failure mode you're thinking of.

**Comment by renatolabs** [comment]
Would also be nice to run a sanity check (~0.1 probability) on this branch, I don't see any runs.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112661)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs)

___
*[`pkg/cmd/roachtest/work_pool.go` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112661#-NiLRSZ76FxRnIRF5oa5:-NiLhxgt86ikzOYCHdo4:b-jy61pe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d758dfa622c4a46a730a03db5ae083afb5a89557/pkg/cmd/roachtest/work_pool.go#L201)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

> `Once.Do()` waits until any other in-progress `Do()` call completes

Ah I see, TIL.

> I don't think `PrintfCtx` is safe to be called multiple times in parallel

Is it not? A lot of tests write to the same `t.L()` instance in concurrent goroutines. I also see a lot of synchronization code in the logger implementation. Unless there's a specific failure mode you're thinking of.
</blockquote></details>

Ah, you're right, I didn't look deep enough in the code. Removed the `once` stuff.

**Comment by RaduBerinde** [comment]
> Would also be nice to run a sanity check (~0.1 probability) on this branch, I don't see any runs.

Definitely, will do that before merging.

**Comment by RaduBerinde** [comment]
Some test runs: https://teamcity.cockroachdb.com/viewLog.html?buildId=12494640&buildTypeId=Cockroach_BazelEssentialCi
https://teamcity.cockroachdb.com/viewLog.html?buildId=12537322&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel

**Comment by RaduBerinde** [comment]
Run looks good, I also checked the quota messages in the logs and they look as expected.

bors r+

**Pull request merged**
