### PR TITLE
goroutinedumper: Test the goroutine file is written in gzip format

### PR DESCRIPTION
**Pull request by giorgosp**
Release note: None

### CODE REVIEW

**Comment by giorgosp** [comment]
Seems like I forgot to include this patch in https://github.com/cockroachdb/cockroach/pull/36922.

**Review by tbg — APPROVED** [review]
Thanks!

bors r+

**Comment by giorgosp** [comment]
I am not sure why CI fails. Do you think it's related to this PR?

**Comment by tbg** [comment]
No. Filed https://github.com/cockroachdb/cockroach/issues/36980.

bors r+

**Pull request merged**
