### PR TITLE
server: allow tests to override boostrap version

### PR DESCRIPTION
**Pull request by healthy-pod**
This code change allows `TestServer` to override the bootstrap version using hard-coded values when bootstrapping into old versions.

Release note: None
Epic: none

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96997)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @fqazi, and @healthy-pod)

___
*[`pkg/sql/catalog/bootstrap/previous_releases.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96997#-NOBJSLp4cNI1etyLudA:-NOBJSLp4cNI1etyLudB:bmh0ecg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd800e3788a3d559ee218518b2181f071bbca3b0/pkg/sql/catalog/bootstrap/previous_releases.go#L27)):*
> ```Go
> 
> var initialValuesFnByKey = map[string]map[clusterversion.Key]initialValuesFn{
> 	"forSecondaryTenant": {
> ```

Nit: This might read better if instead of using a string, you created a const with the two options and used that throughout the code.  It will also prevent strange error cases, in case of typos in the string.
___
*[`pkg/sql/catalog/bootstrap/previous_releases.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96997#-NOBMA4k2KNWRH9G8V6O:-NOBMA4k2KNWRH9G8V6P:b-hq5mht) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd800e3788a3d559ee218518b2181f071bbca3b0/pkg/sql/catalog/bootstrap/previous_releases.go#L28)):*
> ```Go
> var initialValuesFnByKey = map[string]map[clusterversion.Key]initialValuesFn{
> 	"forSecondaryTenant": {
> 		clusterversion.V22_2: InitialValuesForTenantV222,
> ```

What will happen here if someone passes in a key aside from V22_2?  Will we handle that gracefully?  Or panic?
___
*[`pkg/ccl/serverccl/server_startup_guardrails_test.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96997#-NOBJr4y5AxHAStwfvxQ:-NOBJr4y5AxHAStwfvxR:b-p0hq3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd800e3788a3d559ee218518b2181f071bbca3b0/pkg/ccl/serverccl/server_startup_guardrails_test.go#L82)):*
> ```Go
> 				Server: &server.TestingKnobs{
> 					BinaryVersionOverride:          test.storageBinaryVersion,
> 					BootstrapVersionKeyOverride:    clusterversion.V22_2,
> ```

Nit: Is there some way we can validate that we're bootstrapping to the correct version?  Maybe not in this test but elsewhere?

**Comment by healthy-pod** [comment]
> _[`pkg/sql/catalog/bootstrap/previous_releases.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96997#-NOBJSLp4cNI1etyLudA:-NOBJSLp4cNI1etyLudB:bmh0ecg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd800e3788a3d559ee218518b2181f071bbca3b0/pkg/sql/catalog/bootstrap/previous_releases.go#L27)):_
> 
> > ```go
> > var initialValuesFnByKey = map[string]map[clusterversion.Key]initialValuesFn{
> > 	"forSecondaryTenant": {
> > ```
> 
> Nit: This might read better if instead of using a string, you created a const with the two options and used that throughout the code. It will also prevent strange error cases, in case of typos in the string.
> 

Done
> _[`pkg/sql/catalog/bootstrap/previous_releases.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96997#-NOBMA4k2KNWRH9G8V6O:-NOBMA4k2KNWRH9G8V6P:b-hq5mht) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd800e3788a3d559ee218518b2181f071bbca3b0/pkg/sql/catalog/bootstrap/previous_releases.go#L28)):_
> 
> > ```go
> > var initialValuesFnByKey = map[string]map[clusterversion.Key]initialValuesFn{
> > 	"forSecondaryTenant": {
> > 		clusterversion.V22_2: InitialValuesForTenantV222,
> > ```
> 
> What will happen here if someone passes in a key aside from V22_2? Will we handle that gracefully? Or panic?
> 

Changed it to return an error:
```
errors.Newf("key '%s' does not map to any releases for which we have hard-coded initial values", key)
```
> _[`pkg/ccl/serverccl/server_startup_guardrails_test.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96997#-NOBJr4y5AxHAStwfvxQ:-NOBJr4y5AxHAStwfvxR:b-p0hq3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd800e3788a3d559ee218518b2181f071bbca3b0/pkg/ccl/serverccl/server_startup_guardrails_test.go#L82)):_
> 
> > ```go
> > 				Server: &server.TestingKnobs{
> > 					BinaryVersionOverride:          test.storageBinaryVersion,
> > 					BootstrapVersionKeyOverride:    clusterversion.V22_2,
> > ```
> 
> Nit: Is there some way we can validate that we're bootstrapping to the correct version? Maybe not in this test but elsewhere?

Added `TestGetInitialValuesCheckForOverrides` to test this.

**Comment by healthy-pod** [comment]
Ready for another look

**Review by ajstorm — APPROVED** [review]
:lgtm: 

@ajwerner are you planning on having a look? If not, and if nobody else from Schema is interested, I think we should merge this to unblock the rest of the tenant upgrade work for 23.1.

> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96997#-:-NPwtJW19iEHOHpkaiEZ:b-rlz45a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @fqazi)

**Review by ajwerner — APPROVED** [review]
:lgtm: this is very nice. Let's unexport these constructor functions which are only accessed underneath the key-oriented API. 

> Reviewed 1 of 5 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96997#-:-NPxa_knDR-QC7xzdQpJ:b-d9hh5p)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajstorm, @dt, @fqazi, and @healthy-pod)

___
*[`pkg/sql/catalog/bootstrap/initial_values.go` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96997#-NPxaNIR64P9VBKgrFPT:-NPxaNIR64P9VBKgrFPU:bvi8dw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/401fa38746f2f72ae9a200991fed037be2205158/pkg/sql/catalog/bootstrap/initial_values.go#L98)):*
> ```Go
> }
> 
> func InitialValuesForSystemV222(
> ```

let's unexport this
___
*[`pkg/sql/catalog/bootstrap/initial_values.go` line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96997#-NPxaV59067crV0t-f-G:-NPxaV59067crV0t-f-H:bvi8dw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/401fa38746f2f72ae9a200991fed037be2205158/pkg/sql/catalog/bootstrap/initial_values.go#L128)):*
> ```Go
> // is that the contents of the system.zones table are overwritten with the new
> // values.
> func InitialValuesForTenantV222(
> ```

let's unexport this

**Comment by healthy-pod** [comment]
TFTRs!
bors r=[ajstorm,ajwerner]

**Pull request merged**
