### PR TITLE
workload/schemachange: complete error screening

### LINKED ISSUE #56119: workload/schemachange: classify and handle errors in all operations
Right now errors occur very frequently inside the schemachange workload and there is no mechanism that checks to see if the error makes sense or not. For example, if we try to add a column to a table that does not exist, we should assert that we receive the right error code for an undefined table. 

All ops should be updated up to the standard above:
- [x] addColumn (https://github.com/cockroachdb/cockroach/pull/55521)
- [x] addConstraint (https://github.com/cockroachdb/cockroach/pull/57491)
- [x] createIndex (https://github.com/cockroachdb/cockroach/pull/57491)
- [x] createSequence (https://github.com/cockroachdb/cockroach/pull/56379)
- [x] createTable (https://github.com/cockroachdb/cockroach/pull/55521)
- [x] createTableAs (https://github.com/cockroachdb/cockroach/pull/55521)
- [x] createView (https://github.com/cockroachdb/cockroach/pull/55521)
- [x] createEnum (https://github.com/cockroachdb/cockroach/pull/56184)
- [x] createSchema (https://github.com/cockroachdb/cockroach/pull/56184)
- [x] dropColumn (https://github.com/cockroachdb/cockroach/pull/56184)
- [x] dropColumnDefault (https://github.com/cockroachdb/cockroach/pull/56184)
- [x] dropColumnNotNull (https://github.com/cockroachdb/cockroach/pull/56184)
- [x] dropColumnStored (https://github.com/cockroachdb/cockroach/pull/57491)
- [x] dropConstraint (https://github.com/cockroachdb/cockroach/pull/57491)
- [x] dropIndex (https://github.com/cockroachdb/cockroach/pull/57491)
- [x] dropSequence (https://github.com/cockroachdb/cockroach/pull/56379)
- [x] dropTable (https://github.com/cockroachdb/cockroach/pull/56379)
- [x] dropView (https://github.com/cockroachdb/cockroach/pull/56379)
- [x] dropSchema (https://github.com/cockroachdb/cockroach/pull/57491)
- [x] renameColumn (https://github.com/cockroachdb/cockroach/pull/56184)
- [x] renameIndex (https://github.com/cockroachdb/cockroach/pull/57491)
- [x] renameSequence (https://github.com/cockroachdb/cockroach/pull/56379)
- [x] renameTable (https://github.com/cockroachdb/cockroach/pull/56184)
- [x] renameView (https://github.com/cockroachdb/cockroach/pull/56184)
- [x] setColumnDefault (https://github.com/cockroachdb/cockroach/pull/57491)
- [x] setColumnNotNull (https://github.com/cockroachdb/cockroach/pull/57491)
- [x] setColumnType (https://github.com/cockroachdb/cockroach/pull/57491)
- [x] insertRow (https://github.com/cockroachdb/cockroach/pull/56379)

Once all the ops are up to date:
- [x] remove extra code (marked by TODOs) in 5b60540c9cccc7822b944fb95b2e3ba582700a06 (https://github.com/cockroachdb/cockroach/pull/57491)

### LINKED ISSUE #56120: workload/schemachange: handle aborted transactions
The function `OperationGenerator.randOp(tx *pgx.Tx)` has a subtle problem when spurious errors occur. Consider the call stack here:

- `OperationGenerator.randOp(tx *pgx.Tx)`
  - `createTable(tx)`
    - `randTable(tx ...)`
    - `tableExists(tx ...)`

Say that `tableExists(tx ...)` produces an error which aborts transaction `tx`. `randOp` will see the error and try to call another operation, but every other op will fail because `randOp` will pass in a `tx` which is aborted. `randOp` will be stuck in a loop for a while until it randomly calls an operation does not use `tx` (ex. `createSequence`). Note, this will happen far less frequently after the competition of https://github.com/cockroachdb/cockroach/issues/56119

To fix this, it would be nice if all non-opType functions that receive a transaction as a parameter used nested transactions so that the original transaction does not get aborted. That way, when `randOp` sees an error and calls another op, the `tx` passed will be in its original state.

### PR DESCRIPTION
**Pull request by jayshrivastava**
**workload/schemachange: complete error screening**

This change adds error screening for the following ops:
- createIndex
- setColumnNotNull 
- dropConstraint
- dropIndex
- setColumnDefault
- dropColumnStored
- setColumnType
- renameIndex
 
Since all ops now have error screening, this change removes the overhead due to supporting ops that screen for errors and do not.

Closes: https://github.com/cockroachdb/cockroach/issues/56119
Release note: None

**workload/schemachange: refactor type resolution**

Previously, the type resolver used to generate types.T structs
from type name strings did not have logic for checking if schema names
were present. This was causing enums to only exist in the public schema.

Furthermore, the use of tree.ResolvableTypeReference in functions
such as randType would make it difficult to inspect the type to see
if a schema name were present.

This change updates the type resolver to correctly handle type names
which are prefixed with schemas. Furthermore, the type resolver will
now fetch OIDs which can be used to check for type equivalence when
screening for type-related errors. This change also refactors the
operation generator to use a helper function for type resolution and
the tree.TypeName struct to represent type names.

Release note: None

**workload/schemachange: cleanup error states on op generation failure**

Previously, if an op func failed, then the op state would not
get reset on subsequent iterations of the loop inside randOp.
This meant that any expected execution errors or commit errors
from the failed op generation would linger and potentially affect
the next generated op.

This change adds some simple mechanisms to ensure the expected
errors get reset on op generation failure.

Release note: None

**workload/schemachange: allow validate after write**

Transactions do not support schema changes after writes in the
same transaction. Previously, a FeatureNotSupported error was
anticipated when a validate operation followed an insertRow operation,
but this error would never occur. This change removes that behavior
because a validate should be allowed to occur after an insert
in a transaction without expecting any errors.

Release note: None

 
**workload/schemachange: use regex to fetch tables**

Previously, the clause `LIKE 'table%'` was used to fetch tables.
This pattern was capabable of fetching system tables, such as
information_schema.tables. Generally, this workload should not
alter the system tables, and should only test using the tables it
creates. Tables created by the workload can be fetched using
the clause `~ 'table[0-9]+'`, which is the word 'table' followed
by a sequence number.

Release note: None
 
**workload/schemachange: use nested transactions for op gen and err screening**

Previously, it was possible for transactions to become aborted
while generating operations or screening for errors. When a
transaction became aborted and an operation generation function
returned an error, a new operation generation function would be
called with the same transaction. Because the transaction was
aborted, all subsequent attempts to use it would fail, so this
situation resulted in an infinite loop.

This change updates the operation generator to use savepoints
before each call to an operation generation function. If
the operation generation function returns an error, the
transaction is rolled back to the savepoint so the transaction
can be reused.

If there are any errors caused by using savepoints, the workload
will terminate with a fatal error.

Closes: #56120

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 3 of 3 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57491)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[pkg/workload/schemachange/operation_generator.go, line 1954 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO7e0OoD5M5lx3dbeOX:-MO7e0OoD5M5lx3dbeOY:b-x3qmxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b2c739fbe21c2b6e476f67f198b0b49a970cb7/pkg/workload/schemachange/operation_generator.go#L1954)):*
> ```Go
> 		return nil, err
> 	}
> 	typ, err := tree.ResolveType(
> ```

this is cute, I like it.
___
*[pkg/workload/schemachange/operation_generator.go, line 54 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO84kqz6COqurdfozJs:-MO84kr-1R4RhPHtJLDg:b9j1huz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02f2698479c34a4ebf7c8704fd4783a013c8768/pkg/workload/schemachange/operation_generator.go#L54)):*
> ```
> 	// function succeeds and the op statement is constructed, then candidateExpectedCommitErrors
> 	// are added to expectedCommitErrors.
> ```

Does this policy always make sense? I wonder if this will mask errors at commit time we don't expect. I understand figuring out the set of cases might not be super easy but it might be worth an experiment
___
*[pkg/workload/schemachange/operation_generator.go, line 231 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO9z0aZ2HbxEFpjDpB1:-MO9z0aZ2HbxEFpjDpB2:b-ifb6ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5d70c3c7fbc6335b7e2026136411cbd6da9cd/pkg/workload/schemachange/operation_generator.go#L231)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		if strings.Contains(err.Error(), pgcode.InFailedSQLTransaction.String()) {
> 			log.WriteString(fmt.Sprintf("Aborted: %s -> %v\n", op, err))
> 			return "SELECT 1", log.String(), err
> 		}
> ```
</details>

This deserves more commentary. This is the case where we've become aborted during op generation. Why does this happen? Why `SELECT 1` and not just `""`? Should this fail out the workload? 
___
*[pkg/workload/schemachange/schemachange.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO7crip4rn4f-8YwecS:-MO7criq2Fg15QOqGEmo:b-nd2rrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/55ed047c1891e9cd4f199191a79d747d62859514/pkg/workload/schemachange/schemachange.go#L406)):*
> ```Go
> 
> 		// Check for any expected errors.
> 		if w.opGen.expectedCommitErrors.empty() || !w.opGen.expectedCommitErrors.contains(pgcode.MakeCode(pgErr.Code)) {
> ```

nit: why the empty check? shouldn't contains just return false if it's empty?
___
*[pkg/workload/schemachange/schemachange.go, line 95 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO9zRBZ23n0Vy248DGd:-MO9zRBZ23n0Vy248DGe:b-5py43) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5d70c3c7fbc6335b7e2026136411cbd6da9cd/pkg/workload/schemachange/schemachange.go#L95)):*
> ```Go
> 		s.flags.IntVar(&s.sequenceOwnedByPct, `seq-owned-pct`, defaultSequenceOwnedByPct,
> 			`Percentage of times that a sequence is owned by column upon creation.`)
> 		s.flags.BoolVar(&s.retryOpGenFailures, `retry-op-gen`, true,
> ```

I'd like to hear more justification for this behavior.

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57491)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/sem/tree/type_name.go, line 249 at r37](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MOJ0FTDAJyDMeoEQ2mW:-MOJ0FTE9L6Ev7GN2iHA:b-5sh42v) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbdfcb74201addd90a907e111fdfb71b6464d875/pkg/sql/sem/tree/type_name.go#L249)):*
> ```Go
> func (name *UnresolvedObjectName) SQLString() string {
> 	// FmtBareIdentifiers prevents the TypeName string from being wrapped in quotations.
> 	return AsStringWithFlags(name, FmtBareIdentifiers)
> ```

I noticed that tree.TypeName and tree.UnresolvedObjectName don't implement `ResolvableTypeReference` very well, so I thought I would go ahead and make them better. I added some more details in the commit message.
___
*[pkg/workload/schemachange/operation_generator.go, line 54 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO84kqz6COqurdfozJs:-MOHDWDGCRqycz9kIGtD:b-x6urs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02f2698479c34a4ebf7c8704fd4783a013c8768/pkg/workload/schemachange/operation_generator.go#L54)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// function succeeds and the op statement is constructed, then candidateExpectedCommitErrors
> 	// are added to expectedCommitErrors.
> ```

Does this policy always make sense? I wonder if this will mask errors at commit time we don't expect. I understand figuring out the set of cases might not be super easy but it might be worth an experiment
</blockquote></details>

With respect to masking commit errors, there's two cases of things that could happen:

1. Op 1 expects error 1 on commit, but op 1 will actually cause a different error on commit. Op 2 adds the correct commit error to the set. Then, the txn commits op1/op2 and the error caused by op 1 will not be unexpected because op 2 added it to the expected commit error set. This can occur, and I think the best way to solve this problem is to just try to commit the txn as soon as there are any expected commit errors in the set. I added some logic + a comment to`runInTxn() `in `schemachange.go` that does this. 

2. Op 1 expects no errors, but a commit error will occur because of it. Op 2 adds the right commit error to the set. Then, the txn commits and the unexpected error from txn 1 will be masked. This is also possible, but there's no way to catch it. I think we just need to hope that a similar transaction gets randomly constructed eventually where op 1 is the only op in the txn that affects expected commit errors. 
___
*[pkg/workload/schemachange/operation_generator.go, line 231 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO9z0aZ2HbxEFpjDpB1:-MODT2JI-xoZC2sKGoUN:b4ygxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5d70c3c7fbc6335b7e2026136411cbd6da9cd/pkg/workload/schemachange/operation_generator.go#L231)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		if strings.Contains(err.Error(), pgcode.InFailedSQLTransaction.String()) {
> 			log.WriteString(fmt.Sprintf("Aborted: %s -> %v\n", op, err))
> 			return "SELECT 1", log.String(), err
> 		}
> ```
This deserves more commentary. This is the case where we've become aborted during op generation. Why does this happen? Why `SELECT 1` and not just `""`? Should this fail out the workload? 
</blockquote></details>

I refactored this to use savepoints, which I feel are better than using regex to see if the txn became aborted. In the comment, I have an example of a transaction becoming aborted due to a bug in system tables.

We need to decide what the best wrt debugging the workload (ie. if generating a sql statement fails, should we terminate the workload?). Generally, I've only noticed 3 situations where generating a statement fails. 
1. Failure to meet the expected isolation level (which is the error I described above). There's an issue for this bug. Once it's fixed, we won't have that problem.
2. There are not enough rows in the database to generate a statement (if you call addColumn with no tables so randTable() returns no rows). This can safely be ignored, and we can try generating another op. 
3. You are developing/debugging a new op locally. With verbosity >= 2, it's easy to spot if your new op function is failing (which is usually due to broken sql introspections). However, it's possible that you miss an edge case locally and a broken op gets merged to master. 

I think we should make the workload terminate if we see an op function return any error other than a `no rows` error, but not yet. This is because the first reason I mentioned above will manifest itself in confusing ways, so it's better to fix it first rather than to debug things caused by it. I also think it would be beneficial to squash all the bugs the workload has found as well. Once we know those bugs are fixed, then we can turn our attention towards verifying that the workload has no edge cases that have been overlooked.
___
*[pkg/workload/schemachange/schemachange.go, line 95 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO9zRBZ23n0Vy248DGd:-MODSqEvBiJAWPREfGMO:b-pynxye) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5d70c3c7fbc6335b7e2026136411cbd6da9cd/pkg/workload/schemachange/schemachange.go#L95)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'd like to hear more justification for this behavior. 
</blockquote></details>

Let's talk about this in the `operation_generator.go` thread.
___
*[pkg/workload/schemachange/schemachange.go, line 404 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MOIhl3vEfnD9EzLsaEG:-MOIhl3vEfnD9EzLsaEH:bvmumjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4914c4cb41bd9ff72ad1a7ad1ce2942a3201bd/pkg/workload/schemachange/schemachange.go#L404)):*
> ```Go
> 			errors.Errorf("***UNEXPECTED SUCCESS"),
> 			errRunInTxnFatalSentinel,
> 		)
> ```

I realized this case was missing, so I added it.

**Review by ajwerner — APPROVED** [review]
:lgtm:

The `SAVEPOINT` thing is nice. 

> Reviewed 3 of 6 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-:-MOZWdpbCAJMn84qjIxV:b-whr0qo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @jayshrivastava)

___
*[pkg/sql/sem/tree/type_name.go, line 249 at r37](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MOJ0FTDAJyDMeoEQ2mW:-MOZWH3p9ihPykNgPozn:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbdfcb74201addd90a907e111fdfb71b6464d875/pkg/sql/sem/tree/type_name.go#L249)):*
<details><summary><i>Previously, jayshrivastava (Jayant Shrivastava) wrote…</i></summary><blockquote>

I noticed that tree.TypeName and tree.UnresolvedObjectName don't implement `ResolvableTypeReference` very well, so I thought I would go ahead and make them better. I added some more details in the commit message.
</blockquote></details>

:thumbsup: 
___
*[pkg/workload/schemachange/operation_generator.go, line 54 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO84kqz6COqurdfozJs:-MOZWSB84--J5lrpx8as:b-zcjvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02f2698479c34a4ebf7c8704fd4783a013c8768/pkg/workload/schemachange/operation_generator.go#L54)):*
<details><summary><i>Previously, jayshrivastava (Jayant Shrivastava) wrote…</i></summary><blockquote>

With respect to masking commit errors, there's two cases of things that could happen:

1. Op 1 expects error 1 on commit, but op 1 will actually cause a different error on commit. Op 2 adds the correct commit error to the set. Then, the txn commits op1/op2 and the error caused by op 1 will not be unexpected because op 2 added it to the expected commit error set. This can occur, and I think the best way to solve this problem is to just try to commit the txn as soon as there are any expected commit errors in the set. I added some logic + a comment to`runInTxn() `in `schemachange.go` that does this. 

2. Op 1 expects no errors, but a commit error will occur because of it. Op 2 adds the right commit error to the set. Then, the txn commits and the unexpected error from txn 1 will be masked. This is also possible, but there's no way to catch it. I think we just need to hope that a similar transaction gets randomly constructed eventually where op 1 is the only op in the txn that affects expected commit errors. 
</blockquote></details>

Thanks
___
*[pkg/workload/schemachange/operation_generator.go, line 231 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO9z0aZ2HbxEFpjDpB1:-MOZW3E21osXmcfQ033X:bfdr162) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5d70c3c7fbc6335b7e2026136411cbd6da9cd/pkg/workload/schemachange/operation_generator.go#L231)):*
<details><summary><i>Previously, jayshrivastava (Jayant Shrivastava) wrote…</i></summary><blockquote>

I refactored this to use savepoints, which I feel are better than using regex to see if the txn became aborted. In the comment, I have an example of a transaction becoming aborted due to a bug in system tables.

We need to decide what the best wrt debugging the workload (ie. if generating a sql statement fails, should we terminate the workload?). Generally, I've only noticed 3 situations where generating a statement fails. 
1. Failure to meet the expected isolation level (which is the error I described above). There's an issue for this bug. Once it's fixed, we won't have that problem.
2. There are not enough rows in the database to generate a statement (if you call addColumn with no tables so randTable() returns no rows). This can safely be ignored, and we can try generating another op. 
3. You are developing/debugging a new op locally. With verbosity >= 2, it's easy to spot if your new op function is failing (which is usually due to broken sql introspections). However, it's possible that you miss an edge case locally and a broken op gets merged to master. 

I think we should make the workload terminate if we see an op function return any error other than a `no rows` error, but not yet. This is because the first reason I mentioned above will manifest itself in confusing ways, so it's better to fix it first rather than to debug things caused by it. I also think it would be beneficial to squash all the bugs the workload has found as well. Once we know those bugs are fixed, then we can turn our attention towards verifying that the workload has no edge cases that have been overlooked.


</blockquote></details>

Can we have a separate issue to ensure that we fix this?

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57491)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/workload/schemachange/operation_generator.go, line 231 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/57491#-MO9z0aZ2HbxEFpjDpB1:-MOatBudDHaBy_5Rdqxe:b-9zxeuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5d70c3c7fbc6335b7e2026136411cbd6da9cd/pkg/workload/schemachange/operation_generator.go#L231)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can we have a separate issue to ensure that we fix this? 
</blockquote></details>

https://github.com/cockroachdb/cockroach/issues/57949 :+1:

**Comment by jayshrivastava** [comment]
bors r=ajwerner

**Pull request merged**
