### PR TITLE
build: fold checkdeps into check

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, there was one parallel build step for both `check` and `checkdeps`. `check` takes ~5 minutes on average, `checkdeps` takes just a few seconds.

This PR folds `checkdeps` into `check`. The extra few seconds won't make the total build time any different, especially since `check` isn't the slowest parallel step on CI. This way, each PR requires one less builder to build.

### CODE REVIEW

**Comment by tamird** [comment]
> There's no need to have 2 programs for this - let's just run them both
> during the Check parallel step in CI.

Perhaps you could rephrase this rationale in terms of time taken for each step, and perhaps mention the time taken for other build parts for comparison.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15259#-:-KiHRnxkUBUFa3CyMAtX:b7ymd0)*

**Comment by dt** [comment]
:lgtm: though I'd leave the file there for the TC build until all open PRs merge/rebase?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15259#-:-KiHRtkEqQz5ZbsilM-n:b-my97f)*

**Comment by jordanlewis** [comment]
Updated the PR description, @tamird. I changed the `checkdeps` invocation on TeamCity to only run the script if it exists, so that way we can merge this soon, wait a while until all outstanding PRs are rebased, then delete the parallel step from TeamCity.

**Comment by tamird** [comment]
LGTM but please update the commit message as well.

**Comment by dt** [comment]
still :lgtm:, but slightly sad about using bash scripting in TC  -- making the TC config only a script path and then having all the behavior/conditionals/etc in that checked-in, code-reviewed script was a maintainability win.

**Review by dt — APPROVED** [review]

**Comment by jordanlewis** [comment]
Agreed - so you're suggesting the flow should have been add `checkdeps` to `check`, leaving the original `checkdeps` as well, wait a while, then delete the job, then delete the file?

I'm happy to do that next time.

**Pull request merged**
