### PR TITLE
ui: allow stmts page to search across explain plan page

### PR DESCRIPTION
**Pull request by gtr**
Partially addresses [#71615](https://github.com/cockroachdb/cockroach/issues/71615).

Previously, the search functionality for the stmts page only allowed a search 
through the statement query. This change adds the statement's Plan as part of 
that search.

Release note (ui change): logical plan text included in searchable text for 
stmts page.

### CODE REVIEW

**Review by xinhaoz — CHANGES_REQUESTED** [review]
Great start on this! Just some comments on improving readability and testing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-:-MtKVyqA3DT0VJ06HvD7:b-lvo9xp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtKV2G_3fEu9Mi-L087:-MtKV2G_3fEu9Mi-L088:bzdjbrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24cbb1f5ae851175dacf402dcd09df8d49f9365/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L59)):*
> ```XML
> }
> // planNodeAttributesToString converts a FlatPlanNodeAttribute into a string.
> export function planNodeAttributesToString(
> ```

Might want to include some unit testing for this in `planview.spec.tsx`
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtKWVPj-eWlcJKIdTrw:-MtKWVPj-eWlcJKIdTrx:b-31a8wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24cbb1f5ae851175dacf402dcd09df8d49f9365/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L65)):*
> ```XML
> 
>   attrs.forEach(function(attr) {
>     str = str.concat(attr.key, " ", attr.values.join(" "), " ");
> ```

nit: we could shorten this function further by doing a map over attrs, returning the key and values as a string, and joining those elements.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtKX8QiDY2Jxho_6QoB:-MtKX8QiDY2Jxho_6QoC:b-y82d4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24cbb1f5ae851175dacf402dcd09df8d49f9365/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L415)):*
> ```XML
>       )
>       .filter(statement => (filters.fullScan ? statement.fullScan : true))
>       .filter(statement =>
> ```

This section is getting pretty large, I'd suggest lifting this out into its own function to improve readability. We could also then test that filter function separately.



_Code quote:_
```XML
        search
          ? search.split(" ").every(val =>
              statement.label
                .toLowerCase()
                .concat(
                  flattenTreeAttributes(
                    statement.stats.sensitive_info &&
                      statement.stats.sensitive_info
                        .most_recent_plan_description,
                  ).name.toLowerCase(),
                  " ",
                  planNodeAttributesToString(
                    flattenTreeAttributes(
                      statement.stats.sensitive_info &&
                        statement.stats.sensitive_info
                          .most_recent_plan_description,
                    ).attrs,
                  ).toLowerCase(),
                  " ",
                )
                .includes(val.toLowerCase()),
```

**Review by Azhng — COMMENTED** [review]
Nice! Great work on the first PR! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-:-MtKY5D3C1R9XaDpGnFR:bus3iw6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtKWakY36v_VPblcaO7:-MtKWakY36v_VPblcaO8:bhesc20) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24cbb1f5ae851175dacf402dcd09df8d49f9365/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L418)):*
> ```XML
>         search
>           ? search.split(" ").every(val =>
>               statement.label
> ```

On top of Xin's comments of lifting the code, I think some additional refactors can be done here. There are a few things:

Currently

1. we take a search query and break it down into a list of`val`s. We then loop through every single `val` and 
    1. take the statement text and combine with its plan attributes to form a match string
    1. check to see if the current `val` is present in the match string

The match string creation is quite expensive since and it seems like it's being done in the inner most nested loop, but the statement text, as well as its sampled plan doesn't change across the search `val`s, so we can extract that logic and reuse the same search string. 
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtKXwNQ5kFyjaafmP8U:-MtKXwNQ5kFyjaafmP8V:b6qwcsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24cbb1f5ae851175dacf402dcd09df8d49f9365/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L428)):*
> ```XML
>                   " ",
>                   planNodeAttributesToString(
>                     flattenTreeAttributes(
> ```

we are calling `flattenTreeAttributes` here with the exact same arguments as a few lines ago. This can definitely be extracted.

**Review by maryliag — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74820)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, @maryliag, and @xinhaoz)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtKb3j1DS7FpdG-2Ygt):*
all the info you have on your PR description should also be on your commit message

**Review by jocrl — COMMENTED** [review]
Yay, nice work! +1 to everything Xin Hao said 🙂

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-:-MtKernsBOSCdgfUyLsV:bsf3i0w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, @jocrl, @maryliag, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtKWVPj-eWlcJKIdTrw:-MtKdaTKCK_iK3AAcqah:b3aobug) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24cbb1f5ae851175dacf402dcd09df8d49f9365/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L65)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: we could shorten this function further by doing a map over attrs, returning the key and values as a string, and joining those elements.
</blockquote></details>

And string interpolation as well, instead of concat. Something like:
```
attrs.map(attr => `${attr.key} ${attr.values.join(" ")}`).join(" ")
```

One difference you'll notice between the existing code and this snippet (and which you might notice in the test) is that the snippet lacks of final trailing comma.  (I'm guessing it doesn't matter for your implementation, but fyi)

And actually, if this function is becoming a one-liner, I could see reworking this as the function that Xin Hao suggests pulling out. And in the function, giving this one-liner and other things variable names can also help break up all the string manipulation to make it easier to understand.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtKX8QiDY2Jxho_6QoB:-MtKg0BtCgpn94VR92Uw:b74gzhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c24cbb1f5ae851175dacf402dcd09df8d49f9365/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L415)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

This section is getting pretty large, I'd suggest lifting this out into its own function to improve readability. We could also then test that filter function separately.
</blockquote></details>

Much agreed! It's currently not clear what it does, in even just the function name would help.

**Comment by gtr** [comment]
Thanks for the feedback all! I made the changes to the PR making the code more readable and adding tests.

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74820)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, @jocrl, @maryliag, and @xinhaoz)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtiaUZhE11Tj9XeGHco):*
Looks like you still need to address Marylia's comment about the commit message.
Make sure you have 1 commit describing this change (squash commits), and that the description you've put in the github PR is also in the commit message.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtiQHDD3IdZEtXqD_3z:-MtiQHDD3IdZEtXqD_4-:by6u9to) ([raw file](https://github.com/cockroachdb/cockroach/blob/156ff11296f52308bc85748af91d6eaadbc261fa/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L61)):*
> ```XML
> // planNodeAttrsToString converts an array of FlatPlanNodeAttribute[] into a string.
> export function planNodeAttrsToString(attrs: FlatPlanNodeAttribute[]): string {
>   attrs.map(attr => `${attr.key} ${attr.values.join(" ")}`).join(" ");
> ```

Looks like this line was duplicated.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74820#-MtiZnchEMeW0S0buSbG:-MtiZnchEMeW0S0buSbH:b9edgnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/156ff11296f52308bc85748af91d6eaadbc261fa/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L151)):*
> ```XML
> 
> // filterBySearchQuery returns true if a search query matches the statement.
> function filterBySearchQuery(
> ```

Nice! This is much more readable now.

**Pull request closed without merging**
