### PR TITLE
engine: store timestamp bounds in RocksDB sstable user metadata

### PR DESCRIPTION
**Pull request by danhhz**
RocksDB exposes a hook (TablePropertiesCollector) to allow adding metadata to
each sstable as it's being built. Use this to keep track of the lowest and
highest mvcc timestamp of the keys in each sstable. This will later be used to
more efficiently implement incremental backups.

I ran block_writer on a `roachdemo -n 3` cluster with and without this change
and it hovered between 411-417 micros/op regardless. Seems like whatever perf
difference this change makes is within the noise.

For #9293.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10182)

### CODE REVIEW

**Comment by petermattis** [comment]
Try running a local 1-node cluster (`roachdemo -n 1`) to avoid any issues with the multiple nodes interfering with each other (e.g. punishing the disk). And then run `block_writer -duration 10m` before and after. In parallel, I'll review this change.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-:-KUsLdNmiy-yDuw6qG7v:b-ez1lf)*

**Comment by petermattis** [comment]
I need to look at the test, but this looks good so far.

---

Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/storage/engine/rocksdb.go, line 628 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsMNqoHs72csGr3xmI:-KUsMNqoHs72csGr3xmJ:b-324xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb.go#L628)):*
> ```Go
> // GetUserProperties fetches the user properties stored in each sstable's
> // metadata.
> func (r *RocksDB) GetUserProperties() (enginepb.SSTUserPropertiesCollection, error) {
> ```

Should this take a start and end key? Retrieving the user properties for every sstable seems excessive, though perhaps that's what you need.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1370 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsMX7nykSSirjXkHjo:-KUsMX7nykSSirjXkHjp:b6957lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb/db.cc#L1370)):*
> ```cpp
>   }
> 
>   for(auto i = props.begin(); i != props.end(); i++) {
> ```

`s/for(/for (/g`

---

*[pkg/storage/engine/rocksdb/db.cc, line 1425 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsMqAewa-mVlTKNR6m:-KUsMqAewa-mVlTKNR6n:b-kju3o6) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb/db.cc#L1425)):*
> ```cpp
>         char* data = static_cast<char*>(malloc(ts_.size()));
>         memcpy(data, ts_.data(), ts_.size());
>         ts_max_ = rocksdb::Slice(data, ts_.size());
> ```

You should use `std::string` instead of `rocksdb::Slice` and then the memory management will be automatic.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1520 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsN9B-m12Shv7HvU9a:-KUsN9B-m12Shv7HvU9b:b-esz9nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb/db.cc#L1520)):*
> ```cpp
>   // Use the TablePropertiesCollector hook to store the min and max MVCC
>   // timestamps present in each sstable in the metadata for that sstable.
>   std::shared_ptr<rocksdb::TablePropertiesCollectorFactory> time_bound_prop_collector(new TimeBoundTblPropCollectorFactory());
> ```

Do you need this local? I think you can pass `new TimeBoundTblPropCollectorFactory()` to `table_properties_collector_factories.push_back`. Maybe. The C++ compiler in my mind is a bit stale.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-:-KUsNLFffoReyhKMcjmF:b-ssx5o1)*

**Comment by paperstreet** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/storage/engine/rocksdb.go, line 628 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsMNqoHs72csGr3xmI:-KUsOiWkeO4EqWKVJmNm:b-kjnse) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb.go#L628)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Should this take a start and end key? Retrieving the user properties for every sstable seems excessive, though perhaps that's what you need.
</details>
This is only used in the test, the production path iterator will presumably use something more direct

---

*[pkg/storage/engine/rocksdb/db.cc, line 1370 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsMX7nykSSirjXkHjo:-KUsQL0VzPYKaVGyVs0x:b915d1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb/db.cc#L1370)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/for(/for (/g`
</details>
Whoops, done.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1425 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsMqAewa-mVlTKNR6m:-KUsQPPe_V6vX2V-E-GP:bia757s) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb/db.cc#L1425)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> You should use `std::string` instead of `rocksdb::Slice` and then the memory management will be automatic.
</details>
Awesome, seems to work. Double check that I'm not leaking anything else, if you don't mind. I'm _really_ rusty

---

*[pkg/storage/engine/rocksdb/db.cc, line 1520 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsN9B-m12Shv7HvU9a:-KUsPxWmrkK6KS1DZ7B4:b-d0of16) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb/db.cc#L1520)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Do you need this local? I think you can pass `new TimeBoundTblPropCollectorFactory()` to `table_properties_collector_factories.push_back`. Maybe. The C++ compiler in my mind is a bit stale.
</details>
I remember nothing of my c++ days, but this doesn't seem to work. Maybe because options.table_properties_collector_factories is a vector of shared_ptrs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182)*

**Comment by paperstreet** [comment]
Added results of the 1-node test to commit message. No change.

---

Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-:-KUsckjboda68q11od8r:b-aa7atd)*

**Comment by petermattis** [comment]
Review status: 0 of 13 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/storage/engine/rocksdb.go, line 628 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsMNqoHs72csGr3xmI:-KUtAthDKUEfvnwuPJsD:bktbexw) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb.go#L628)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> This is only used in the test, the production path iterator will presumably use something more direct
</details>
If it is only used in testing, can we unexport this method?

---

*[pkg/storage/engine/enginepb/rocksdb.proto, line 24 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtDcy2q5iEbqfAx8eC:-KUtDcy2q5iEbqfAx8eD:b-8dw6qt) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/enginepb/rocksdb.proto#L24)):*
> ```protobuf
> message SSTUserProperties {
>     string path = 1;
>     map<string, string> entries = 2;
> ```

The map is general, but it might be better to pull out `ts_{min,max}` fields which have type `hlc.Timestamp`.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1425 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsMqAewa-mVlTKNR6m:-KUtB10hVi_LqdrYRj6t:b-bb0je2) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb/db.cc#L1425)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Awesome, seems to work. Double check that I'm not leaking anything else, if you don't mind. I'm _really_ rusty
</details>
Yes, I will attest to your rustiness. There is no need to allocate (and leak) `data`:

```
ts_max_.assign(ts_.data(), ts_.size())
```

---

*[pkg/storage/engine/rocksdb/db.cc, line 1375 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtDIwDR7NwlEeB-wzM:-KUtDIwDR7NwlEeB-wzN:b-fu46mh) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/rocksdb/db.cc#L1375)):*
> ```cpp
>     auto userprops = i->second->user_collected_properties;
>     for (auto j = userprops.begin(); j != userprops.end(); j++) {
>       (*sst->mutable_entries())[j->first] = j->second;
> ```

So the map value is the encoded timestamp? I wonder if we should decode it for returning to Go land.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1413 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtC6Npmf9K4ybYu8Jb:-KUtC6Nqq9nscrk5AOqU:b-ito8cm) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/rocksdb/db.cc#L1413)):*
> ```cpp
>         {"crdb.ts.min", ts_min_},
>         {"crdb.ts.max", ts_max_},
>     };
> ```

That works? C++ has advanced.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1421 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtBIohTmNkoS-sMXQA:-KUtBIohTmNkoS-sMXQB:b-ri1cvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/rocksdb/db.cc#L1421)):*
> ```cpp
>     if (SplitKey(user_key, &unused_, &ts_) && ts_.size() > 0) {
>       ts_.remove_prefix(1);  // The NUL prefix.
>       if (ts_max_.size() == 0 || ts_.compare(ts_max_) > 0) {
> ```

`s/ts_max_.size() == 0/ts_max_.empty()/g`

---

*[pkg/storage/engine/rocksdb/db.cc, line 1426 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtBMJSlhYW7ReHUsYV:-KUtBMJSlhYW7ReHUsYW:bormbn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/rocksdb/db.cc#L1426)):*
> ```cpp
>         ts_max_.assign(data, ts_.size());
>       }
>       if (ts_min_.size() == 0 || ts_.compare(ts_min_) < 0) {
> ```

`s/ts_min_.size() == 0/ts_min_.empty()/g`

---

*[pkg/storage/engine/rocksdb/db.cc, line 1443 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtBUjtKunMJnl8q4DW:-KUtBUjtKunMJnl8q4DX:b-sdjl2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/rocksdb/db.cc#L1443)):*
> ```cpp
>   std::string ts_max_;
>   rocksdb::Slice unused_;
>   rocksdb::Slice ts_;
> ```

Unlike in Go, there is no value in placing these temporaries in the class structure. They can be placed on the stack in `AddUserKey` (with the underscore suffix removed).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182)*

**Comment by paperstreet** [comment]
Review status: 0 of 13 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/storage/engine/rocksdb.go, line 628 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsMNqoHs72csGr3xmI:-KUwL1YHv7N0LTvvZxsG:b-2ew230) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb.go#L628)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> If it is only used in testing, can we unexport this method?
</details>
Indeed we can

---

*[pkg/storage/engine/enginepb/rocksdb.proto, line 24 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtDcy2q5iEbqfAx8eC:-KUwR7lVBNaZOweUxOa6:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/enginepb/rocksdb.proto#L24)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> The map is general, but it might be better to pull out `ts_{min,max}` fields which have type `hlc.Timestamp`.
</details>
Done

---

*[pkg/storage/engine/rocksdb/db.cc, line 1425 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUsMqAewa-mVlTKNR6m:-KUwOxyutdvWN76bZEMk:b-p1mxok) ([raw file](https://github.com/cockroachdb/cockroach/blob/882100c2935ba48759b374b522cdee37df5c522b/pkg/storage/engine/rocksdb/db.cc#L1425)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Yes, I will attest to your rustiness. There is no need to allocate (and leak) `data`:
> 
> ```
> ts_max_.assign(ts_.data(), ts_.size())
> ```
</details>
Ah, I see. The string constructer copies the data? rocksdb::Slice wasn't doing this (which is expected from slice) which is why I had this in there in the first place. Much better.

(This commit has felt uncomfortably close to button mashing. The iterator followup that actually uses this data seems like it'll be considerably more complex, so hopefully I'll get some of this loaded back up a bit.)

---

*[pkg/storage/engine/rocksdb/db.cc, line 1375 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtDIwDR7NwlEeB-wzM:-KUwYj5fJAYIN-ix6SKn:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/rocksdb/db.cc#L1375)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> So the map value is the encoded timestamp? I wonder if we should decode it for returning to Go land.
</details>
Done

---

*[pkg/storage/engine/rocksdb/db.cc, line 1413 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtC6Npmf9K4ybYu8Jb:-KUwL5GMaE19x_o40Rx9:byi91im) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/rocksdb/db.cc#L1413)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> That works? C++ has advanced.
</details>
¯\_(ツ)_/¯, I got it from their examples

---

*[pkg/storage/engine/rocksdb/db.cc, line 1421 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtBIohTmNkoS-sMXQA:-KUwLJNiC3VfBscrVBHb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/rocksdb/db.cc#L1421)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/ts_max_.size() == 0/ts_max_.empty()/g`
</details>
Done.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1426 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtBMJSlhYW7ReHUsYV:-KUwLKZ12qmuEV7MZst6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/rocksdb/db.cc#L1426)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/ts_min_.size() == 0/ts_min_.empty()/g`
</details>
Done.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1443 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUtBUjtKunMJnl8q4DW:-KUwPR2tYjYCW9UmY27D:byr4fnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/61caf211b3992f8a7921fab2667d074347515144/pkg/storage/engine/rocksdb/db.cc#L1443)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Unlike in Go, there is no value in placing these temporaries in the class structure. They can be placed on the stack in `AddUserKey` (with the underscore suffix removed).
</details>
Righto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182)*

**Comment by paperstreet** [comment]
Thanks for the review! RFAL

---

Review status: 0 of 13 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-:-KUwZ5QviCJfpman7oB7:b-6sx6b6)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1390 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUwliPv3-NAObcPyKxy:-KUwliPv3-NAObcPyKxz:b-rnged6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4592ac17643deea035d47a09af2b9f80c2908b/pkg/storage/engine/rocksdb/db.cc#L1390)):*
> ```cpp
>         sst->mutable_ts_min()->set_wall_time(wall_time);
>         sst->mutable_ts_min()->set_logical(logical);
>       }
> ```

This could be pulled out into a helper function to be shared with the code below. `DecodeHLCTimestamp`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-:-KUwm-089rNteYEJxnQw:bnfp4nl)*

**Comment by paperstreet** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1390 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182#-KUwliPv3-NAObcPyKxy:-KUwrLChjn-GtRjef9zv:b757pjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4592ac17643deea035d47a09af2b9f80c2908b/pkg/storage/engine/rocksdb/db.cc#L1390)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This could be pulled out into a helper function to be shared with the code below. `DecodeHLCTimestamp`?
</details>
I like it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10182)*

**Comment by tamird** [comment]
This has broken master due to merge skew.

**Pull request merged**
