### PR TITLE
ui/db-console: surface more job metrics around reverting and retrying in the DBConsole Jobs Overview page

### LINKED ISSUE #68179: ui,jobs: improve jobs overview page in DBConsole
In https://github.com/cockroachdb/cockroach/issues/44594, Schema is adding a retry mechanism to the jobs infrastructure. During this work, we plan to add additional columns to `crdb_internal.jobs` to surface more job metrics.

These new metrics would be helpful in the DBConsole Jobs Overview page. 

- last execution time
- execution count
- updated status to indicate Retrying

FYI @ajwerner @sajjadrizvi 

Epic CRDB-7912

### PR DESCRIPTION
**Pull request by jocrl**
Fixes https://github.com/cockroachdb/cockroach/issues/68179

This commit surfaces the status `reverting`, annotates existing `running` and
`reverting` statuses UI with "retrying" where applicable, and adds the "Last
Execution Time (UTC)" and "Execution Count" columns to the jobs overview table
in db console. "Retrying" is defined as `status IN ('running', 'reverting') AND
next_run > now() AND num_runs > 1`.

Hovering a retrying status shows the next execution time. The "Status" column
was also moved left to the second column. Filtering using the dropdown by
`Status: Running` or `Status: Reverting` will include those that are
also "retrying". Users can also filter by `Status: Retrying`.

The `/jobs` endpoint was modified to add the `last_run`, `next_run`, and
`num_runs` fields required for the UI change. Jobs with status `running` or
`reverting` and are also "retrying" have their statuses sent as `retry-running`
and `retry-reverting` respectively. The endpoint was also modified to support
the value `retrying` for the `status` query parameter.

This commit also adds a storybook story for the jobs table, which showcases the
different possible statuses in permutations of information that could be
present for the `running` status.

Release note (ui change): The jobs overview table in DBConsole now shows when
jobs have the status "reverting", and shows the badge "retrying" when running
or reverting jobs are also retrying. Hovering the status for a "retrying" job
will show the "Next execution time" in UTC. Two new columns, "Last Execution
Time (UTC)" and "Execution Count", were also added to the jobs overview table
in DBConsole, and the "Status" column was moved left to the second column in
the table.

The `status` query parameter in the `/jobs` endpoint now supports the values
`reverting` and `retrying`.

Jobs table:
image

Filter and hover:
https://user-images.githubusercontent.com/91907326/141375153-2cf2641a-33a1-4bfb-a900-a187dc5579a1.mov

Permutations of running jobs with present/absent combinations of time remaining, running message, or retrying:
image

### CODE REVIEW

**Comment by jocrl** [comment]
Some side notes:

**Execution errors field** (@ajwerner and @vy-ton)
The `execution_errors` column was added in #44594, but I didn't surface it in the UI or add it to the endpoint because it didn't appear in the mockup. I also wasn't sure how it plays with the existing `error` column in `crdb_internal.jobs`.

**Roachprod reproduction** (@Annebirzin and @kevin-v-ngo)
My understanding is that you usually manually test features in roachprod. In @ajwerner's words on slack regarding the retrying state, "you’re butting up against a real rough edge in that it’s not easy to actually make those states happen in practice".

I'm personally not even sure how to induce a non-retrying running or reverting state in db console. Andrew provided a code snippet that I'll put in the next comment for inducing the retrying states in development where you can write as `root`. Not sure if you could use that snippet for testing in roachprod?

**Storybook** (@Annebirzin and @kevin-v-ngo)
I'm not sure if you have the dev environment built? If you have the db console front end built and would like to poke around storybook, you can launch it with

```
# from the crdb repo
cd pkg/ui/workspaces/db-console
yarn storybook
```

Happy to help with any installation trouble!

**Minor retry badge UI stuff** (@Annebirzin)
For `retry-running`, I've put the retry badge on a new line because I couldn't fit it in the same line while maintaining consistency with other badge styles or making the column wider. A similar thing happens with `retry-reverting`, the two badges end up in different lines exepct in the widest of windows. Other than in the Jobs overview page, the same badge style is also used in other places like the nodes overview and the statements page.

The separate line does make the row taller than other normal rows. Not sure if you would prefer to break with other badge styles, and have a squished retry badge that's smaller than the others?

**Comment by jocrl** [comment]
The snippet Andrew provided to write to jobs table as `root` to create retrying jobs:

```
create table foo ();
create table bar ();
drop table foo;
drop table bar;
select pg_sleep(1);
  WITH pl AS (
            SELECT id,
                   crdb_internal.pb_to_json(
                    'cockroach.sql.jobs.jobspb.Payload',
                    payload
                   ) AS pl
              FROM system.jobs
             WHERE id
                   IN (
                      SELECT job_id
                        FROM crdb_internal.jobs
                       WHERE job_type = 'SCHEMA CHANGE GC'
                             AND description
                              LIKE 'GC for DROP TABLE%'
                    )
          ),
       updated AS (
                SELECT id, json_remove_path(
                        json_remove_path(pl, ARRAY['finishedMicros']),
                        ARRAY['finalResumeError']
                       ) AS pl
                  FROM pl
               ),
       to_insert AS (
                  SELECT id, 
                          crdb_internal.json_to_pb(
                            'cockroach.sql.jobs.jobspb.Payload',
                            pl
                          ) AS encoded_pl, pl
                    FROM updated
                 )
UPDATE system.jobs
   SET status = IF(pl->>'description' LIKE '%foo%', 'reverting', 'running'),
       payload = encoded_pl,
       claim_session_id = NULL,
       claim_instance_id = NULL,
       last_run = now(),
       num_runs = 10
  FROM to_insert
 WHERE jobs.id = to_insert.id;
```

**Review by maryliag — COMMENTED** [review]
> Reviewed 11 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jocrl)

___
*[pkg/ui/workspaces/db-console/src/views/jobs/jobStatus.tsx, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnSXMwr5PFwU23ZhZTl:-MnSXMwr5PFwU23ZhZTm:b3m2907) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/ui/workspaces/db-console/src/views/jobs/jobStatus.tsx#L71)):*
> ```XML
>           />
>           <div className="jobs-table__align-progress-bar">
>             {jobIsRetrying && <RetryingStatusBadge />}
> ```

you probably want the jib is running check for the div component, not just the div content. No need to create this div if it will be empty
```
{jobIsRetrying && (<div className....)}
```

**Review by matthewtodd — COMMENTED** [review]
This looks nice! I'm not sure what to do about 2., but I've done something like it before, flattening a couple of dimensions into one for display purposes. In that context, it became a little icky to work with, but I don't know if it will here, since we're just building a read-only view. IIUC, we do have enough fields in the API response to calculate the "retrying" answer on the client side, yes? (Except we would be depending on the browser's sense of time, which isn't great.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-:-MnW87xOCFyYaHstH2_t:b-p25hcz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jocrl)

**Review by Azhng — COMMENTED** [review]
Just trying to wrap my head around the job CTE query here, is my understanding correct that this CTE finds the schema change jobs on `foo` table and set its status to reverting? 

Few things that I don't quite understand here:
1. Why do we need to remove `finishedMicros` and `finalResumeError` field? 
2. if a job is running at the reverting stage, why do we need to set the `claim_{session, instance}_id` to NULL ? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-:-MnW927OAZlCFx-IGD6x:b-twdohl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jocrl)

___
*[pkg/server/admin.go, line 1855 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWHxYK35Yoh54Fnzjc:-MnWHxYK35Yoh54Fnzjd:b9cv8zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/server/admin.go#L1855)):*
> ```Go
>              case when ` + retryRunningCondition + `then 'retry-running' 
>              when ` + retryRevertingCondition + ` then 'retry-reverting' 
>              else status end as status,
> ```

super minor nit: is it possible we can format the `case` operator as

``` sql
case 
  when ... then ...
  when ... then ...
  else ...
end 
```

for better readability ? 
___
*[pkg/server/admin.go, line 2735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWIyD32yEhOe4haDPz:-MnWIyD32yEhOe4haDQ-:bdcs708) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/server/admin.go#L2735)):*
> ```Go
> 		*d = &val
> 
> 	case *[]string:
> ```

quick question, which column has the destination type `*[]string` ?
___
*[pkg/ui/workspaces/db-console/src/views/jobs/duration.tsx, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWJPZgAJ01IJy305xo:-MnWJPZgAJ01IJy305xp:b-6fp02w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/ui/workspaces/db-console/src/views/jobs/duration.tsx#L37)):*
> ```XML
>     if (isRunning(job.status)) {
>       const fractionCompleted = job.fraction_completed;
>       if (fractionCompleted > 0) {
> ```

I think we have other long running jobs like [CDC](https://github.com/cockroachdb/cockroach/blob/66ff69fbb78388ff7790cf3335df1b3e84049708/pkg/jobs/jobspb/jobs.proto#L815) that does not terminate. In that case I think `fraction_completed` is omitted and it returns a `high_water` timestamp instead.
So what would happen here if we have a CDC job ?
___
*[pkg/ui/workspaces/db-console/src/views/jobs/JobTable.stories.tsx, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWJwDZ-fn_AHAqpx9l:-MnWJwDZ-fn_AHAqpx9m:bmje1un) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/ui/workspaces/db-console/src/views/jobs/JobTable.stories.tsx#L1)):*
> ```XML
> // Copyright 2020 The Cockroach Authors.
> ```

nit: `s/2020/2021/`

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jocrl)

___
*[-- commits, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWmErvBO_G5i5pNbe8):*
link the issue being addressed, with a Fixes #issuenumber or Partially Adresses #issuenumber

**Review by jocrl — COMMENTED** [review]
@matthewtodd thanks, good to know there's precedent for that! 

> IIUC, we do have enough fields in the API response to calculate the "retrying" answer on the client side, yes? (Except we would be depending on the browser's sense of time, which isn't great.)

Yup, that's correct. The downside is that the filtering is done back end (https://github.com/cockroachdb/cockroach/pull/72291/files#diff-1402bca7aa2ae9e5b623ab3d1e93d918e0f8d652c689c42d644e46611151c9f6R1853). So there are two places where the logic is used,
1. when deciding what badge to show
2. when deciding whether a job filtered by query params should be part of the result

We have the fields, but independently calculating 1. on the client side would mean that the definition of "retrying" would be duplicated in the front end and back end code, and risk getting out of sync.

@azhng so... Andrew Werner gave me the job CTE query; I don't understand it xD. This was the message if you would like to ask him? https://cockroachlabs.slack.com/archives/C02DSDS9TM1/p1635345519023200

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-:-Mng9MsK7WjxbPuPWXLM:b-kebn34)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, and @maryliag)

___
*[-- commits, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWmErvBO_G5i5pNbe8):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

link the issue being addressed, with a Fixes #issuenumber or Partially Adresses #issuenumber
</blockquote></details>

Done.
___
*[pkg/server/admin.go, line 1855 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWHxYK35Yoh54Fnzjc:-Mng8NNA65RN9iq_D8cV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/server/admin.go#L1855)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

super minor nit: is it possible we can format the `case` operator as

``` sql
case 
  when ... then ...
  when ... then ...
  else ...
end 
```

for better readability ? 
</blockquote></details>

Done.
___
*[pkg/server/admin.go, line 2735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWIyD32yEhOe4haDPz:-Mng8SYVBbs2p6ND-tCf:b-6hg1ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/server/admin.go#L2735)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

quick question, which column has the destination type `*[]string` ?
</blockquote></details>

Thanks for the catch. This should've been for a different issue, adding `execution_errors` which is *[]string. I've removed this.
___
*[pkg/ui/workspaces/db-console/src/views/jobs/duration.tsx, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWJPZgAJ01IJy305xo:-Mng8tjnCMfuQeTP92lQ:b-3yi8hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/ui/workspaces/db-console/src/views/jobs/duration.tsx#L37)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I think we have other long running jobs like [CDC](https://github.com/cockroachdb/cockroach/blob/66ff69fbb78388ff7790cf3335df1b3e84049708/pkg/jobs/jobspb/jobs.proto#L815) that does not terminate. In that case I think `fraction_completed` is omitted and it returns a `high_water` timestamp instead.
So what would happen here if we have a CDC job ?
</blockquote></details>

The pre-existing code has it that if there is a highwater time stamp, it doesn't show a status badge at all (doesn't go into `jobStatus.tsx` and doesn't show duration). https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/jobs/jobStatusCell.tsx#L28

It looks like this:

___
*[pkg/ui/workspaces/db-console/src/views/jobs/JobTable.stories.tsx, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWJwDZ-fn_AHAqpx9l:-Mng9GkX37u_kaEMetIJ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/ui/workspaces/db-console/src/views/jobs/JobTable.stories.tsx#L1)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `s/2020/2021/`
</blockquote></details>

done
___
*[pkg/ui/workspaces/db-console/src/views/jobs/jobStatus.tsx, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnSXMwr5PFwU23ZhZTl:-Mng9Jfn9ptTFRj2zII5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/ui/workspaces/db-console/src/views/jobs/jobStatus.tsx#L71)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you probably want the jib is running check for the div component, not just the div content. No need to create this div if it will be empty
```
{jobIsRetrying && (<div className....)}
```

</blockquote></details>

Done.

**Review by jocrl — COMMENTED** [review]
@azhng it's possible that he was just trying to make other unnecessary fields more realistic

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-:-MngAdJV8gy-7cHqnfC6:b-c6yjes)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, and @maryliag)

**Comment by Annebirzin** [comment]
@jocrl Looking good! I had one suggestion for better alignment of the text/badges ([Figma link](https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/20.1_obsrv_db-console-jobs?node-id=2156%3A9487)):

- For in-progress status, can we move the percentage to the right of the progress bar? This way we can left-align the progress bar, timestamp, additional description text, and badges.  

Also, I was wondering if we could make a few color tweaks (can break this out in a separate issue if you want)
- Update the progress bar to our default blue: Hex `#0055FF` (also called `info-3`)
- Update the 'Succeeded' badge colors to match Figma 
> - Text: Hex `#237300` (also called `success-4`)
> - Background-fill: Hex `#E3F5E0` (also called `success-1`)

Screen Shot 2021-11-04 at 2 10 48 PM

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @maryliag)

___
*[pkg/server/admin.go, line 2735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWIyD32yEhOe4haDPz:-Mo4RkfG6xN0e0iwcxpu:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/server/admin.go#L2735)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Thanks for the catch. This should've been for a different issue, adding `execution_errors` which is *[]string. I've removed this.
</blockquote></details>

:+1:
___
*[pkg/ui/workspaces/db-console/src/views/jobs/duration.tsx, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MnWJPZgAJ01IJy305xo:-Mo4Rqph0R99mXBqhYLB:b-jp2694) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5167391b42c92061b831acfd98f6986eea1f33/pkg/ui/workspaces/db-console/src/views/jobs/duration.tsx#L37)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

The pre-existing code has it that if there is a highwater time stamp, it doesn't show a status badge at all (doesn't go into `jobStatus.tsx` and doesn't show duration). https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/jobs/jobStatusCell.tsx#L28

It looks like this:

</blockquote></details>

Ah nice, TIL :+1:

**Review by jocrl — COMMENTED** [review]
@annebirzin , how does this look for alignment?


The color change turns out to be more complicated to do nicely (https://cockroachlabs.slack.com/archives/C0182T8NUH0/p1636579523023600 if anyone is interested in the implementation details). I'll break it into a separate issue!

@cockroachdb/sql-observability I've added tests, made a minor UI change, and made the fixtures prettier. Reviewable also seems to detect changes in `full.md` in the latest push that I'm not seeing on github; does anyone have an idea what's going on?

@laurenbarker, could I get your review for `index.spec.tsx`? The test for this PR doesn't require any redux stuff, so I've left out the `testHelper.tsx` port from this PR and will work on that later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-:-MoAtpq76mM6RDYAXNic:b-8vz7hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @maryliag)

___
*[pkg/ui/workspaces/db-console/src/views/jobs/index.spec.tsx, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MoAvQWb0mR8nbbuFf6T:-MoAvQWb0mR8nbbuFf6U:b-29kzei) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bd9beed6a6ebddcb6858a469cf2bafc5eaaf23b/pkg/ui/workspaces/db-console/src/views/jobs/index.spec.tsx#L19)):*
> ```XML
>   allJobsFixture,
>   retryRunningJobFixture,
> } from "src/views/jobs/jobTable.fixture";
> ```

What do people think about sharing these fixtures between storybook and tests?

Pros:
- The fixture for what a running job looks like already exists, so might as well reuse it. It reduces boilerplate and having to re-specify all the fields in the test
- Having the storybook fixtures used in test makes it less likely that the storybook fixtures will diverge and break

Cons:
- It is not obvious that the fixtures are used in both. One might imagine wanting to change the storybook fixture just because, and being surprised that it affects tests

**Comment by Annebirzin** [comment]
@jocrl alignment looks great, thanks for the update!

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 11 of 14 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jocrl, @laurenbarker, and @maryliag)

___
*[pkg/ui/workspaces/db-console/src/views/jobs/index.spec.tsx, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MoAvQWb0mR8nbbuFf6T:-MoEqehxChBCfFDPCJwC:b5w2u4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bd9beed6a6ebddcb6858a469cf2bafc5eaaf23b/pkg/ui/workspaces/db-console/src/views/jobs/index.spec.tsx#L19)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

What do people think about sharing these fixtures between storybook and tests?

Pros:
- The fixture for what a running job looks like already exists, so might as well reuse it. It reduces boilerplate and having to re-specify all the fields in the test
- Having the storybook fixtures used in test makes it less likely that the storybook fixtures will diverge and break

Cons:
- It is not obvious that the fixtures are used in both. One might imagine wanting to change the storybook fixture just because, and being surprised that it affects tests
</blockquote></details>

I think it makes sense to use the same. If a change is made with storybook in mind and that breaks a test, that's good, because we caught that. The ui and tests should be aligned anyway

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @laurenbarker, and @maryliag)

___
*[pkg/ui/workspaces/db-console/src/views/jobs/index.spec.tsx, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MoAvQWb0mR8nbbuFf6T:-MoEsQspCYnqdRdphrnw:b-r9qe4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bd9beed6a6ebddcb6858a469cf2bafc5eaaf23b/pkg/ui/workspaces/db-console/src/views/jobs/index.spec.tsx#L19)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I think it makes sense to use the same. If a change is made with storybook in mind and that breaks a test, that's good, because we caught that. The ui and tests should be aligned anyway
</blockquote></details>

Mmm, yeah I'm thinking there are two types of "storybook change breaks a test", one which is good to catch and one which we don't care about and could be annoying.

E.g., let's say there's a tooltip that if you hover will show the job description, in this case "automatic SQL Stats compaction". The test is like
```
// pseudocode
renderTheComponent()
hoverTheComponent()
verifyThatThisTextAppears("automatic SQL Stats compaction")
```

A storybook change could break `verifyThatThisTextAppears` in two ways
1) Something about the new storybook inputs makes it so that the tooltip no longer appears. This is good to catch 😃
2) The storybook changes the description to `"BACKUP DATABASE bank TO 'gs://acme-co-backup/database-bank-2017-03-29-nightly' AS OF SYSTEM TIME '-10s' INCREMENTAL FROM 'gs://acme-co-backup/database-bank-2017-03-27-weekly', 'gs://acme-co-backup/database-bank-2017-03-28-nightly' WITH revision_history"`, or some other different text, to be able to front end develop on whether the page works with a really long tooltip. The tooltip still works, but the test breaks because the text changes.

So yeah, I think 1) is legit and useful. 2) I'm concerned that it constrains the ability of storybook to be a sandbox and causes flaky test churn

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jocrl, and @laurenbarker)

___
*[pkg/ui/workspaces/db-console/src/views/jobs/index.spec.tsx, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MoAvQWb0mR8nbbuFf6T:-MoEvtbD8ZU9H5bv-t0y:b-xs4eee) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bd9beed6a6ebddcb6858a469cf2bafc5eaaf23b/pkg/ui/workspaces/db-console/src/views/jobs/index.spec.tsx#L19)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Mmm, yeah I'm thinking there are two types of "storybook change breaks a test", one which is good to catch and one which we don't care about and could be annoying.

E.g., let's say there's a tooltip that if you hover will show the job description, in this case "automatic SQL Stats compaction". The test is like
```
// pseudocode
renderTheComponent()
hoverTheComponent()
verifyThatThisTextAppears("automatic SQL Stats compaction")
```

A storybook change could break `verifyThatThisTextAppears` in two ways
1) Something about the new storybook inputs makes it so that the tooltip no longer appears. This is good to catch 😃
2) The storybook changes the description to `"BACKUP DATABASE bank TO 'gs://acme-co-backup/database-bank-2017-03-29-nightly' AS OF SYSTEM TIME '-10s' INCREMENTAL FROM 'gs://acme-co-backup/database-bank-2017-03-27-weekly', 'gs://acme-co-backup/database-bank-2017-03-28-nightly' WITH revision_history"`, or some other different text, to be able to front end develop on whether the page works with a really long tooltip. The tooltip still works, but the test breaks because the text changes.

So yeah, I think 1) is legit and useful. 2) I'm concerned that it constrains the ability of storybook to be a sandbox and causes flaky test churn
</blockquote></details>

I see, in that case we don't want to create new points of failures for tests. Let keep as is and think for future improvements we can make on this area, but that will not be on the scope of this PR

**Comment by jocrl** [comment]
Updated images on description to reflect the latest state

**Review by laurenbarker — APPROVED** [review]
Apologize for the delay! I need to setup my notifications for this repo. The test looks good to me, I just had one question about the necessity of pulling out the helper.

My approval is for the test as I didn't review the rest of the PR :)

> Reviewed 1 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-:-MpxJrl28epucs8AXmPz:bc1skvg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jocrl, and @maryliag)

___
*[pkg/ui/workspaces/db-console/src/test-utils/tooltip.ts, line 13 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MpxH9THBq3Q_DwpDFoW:-MpxH9THBq3Q_DwpDFoX:bnbzsw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e50224821c7b162fc81675148beb2781cce65be0/pkg/ui/workspaces/db-console/src/test-utils/tooltip.ts#L13)):*
> ```XML
> import { expect } from "chai";
> 
> export const expectPopperTooltipActivated = () =>
> ```

Are you planning on using this in other tests? Based on only this PR is seems like an early optimization.
___
*[pkg/ui/workspaces/db-console/src/views/jobs/index.spec.tsx, line 91 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MpxGUk47XscaS_SNh3q:-MpxGUk47XscaS_SNh3r:bwltqck) ([raw file](https://github.com/cockroachdb/cockroach/blob/e50224821c7b162fc81675148beb2781cce65be0/pkg/ui/workspaces/db-console/src/views/jobs/index.spec.tsx#L91)):*
> ```XML
> 
>     await waitFor(expectPopperTooltipActivated);
>     userEvent.hover(getByText("retrying"));
> ```

Glad this works! We've had inconsistent behavior for triggering hover events in tests depending on the tooltip library.

**Comment by jocrl** [comment]
___
*[pkg/ui/workspaces/db-console/src/test-utils/tooltip.ts, line 13 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-MpxH9THBq3Q_DwpDFoW:-Mq0VlRf8nGkYCV52Xrc:b72dw5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e50224821c7b162fc81675148beb2781cce65be0/pkg/ui/workspaces/db-console/src/test-utils/tooltip.ts#L13)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Are you planning on using this in other tests? Based on only this PR is seems like an early optimization.
</blockquote></details>

Not currently planning, but yeah it's an early optimization on the basis that the tooltip is a reusable component. Would you suggest not making that optimization without a current use case?

**Review by maryliag — APPROVED** [review]
Great job on this PR! :lgtm: 

Can you also add the backport 21.2 label to this? We will want to backport this :) 

> Reviewed 1 of 14 files at r3, 3 of 4 files at r6, 5 of 8 files at r7, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72291#-:-MqPe0Ed3hIydXUdAkeQ:b2dycua)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @laurenbarker)

**Comment by jocrl** [comment]
I'm now realizing that this is also

1) a server change, but I didn't include "server" in the title
2) an api change, but I didn't include "(api change)" in the release notes, or describe the `/jobs` endpoint change in the release notes section

@maryliag, should I correct these somehow?

**Comment by maryliag** [comment]
1. Since this was already merged and backported, it don't think it matters that much
2. You do have a description of the jobs endpoint change on your release note (with "The status query parameter in the /jobs endpoint now supports the values reverting and retrying."). The point of the release note is to add changes to the Docs, so if there is anything else that should be added, changing just here won't notify the docs team since the issue for this was already created, so you can add any missing info to the issue itself https://github.com/cockroachdb/docs/issues/12535

**Pull request merged**
