### PR TITLE
util/net: implement insecure gRPC

### PR DESCRIPTION
**Pull request by tamird**
builds on #4423, so I suggest only reviewing the last commit.

I observed some goroutine leaks locally, though I'm not yet sure of the cause.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4427)

### CODE REVIEW

**Comment by tamird** [comment]
Actually, #4423 is not properly tested without this change, so I'm going to close that one in favour of this.

**Comment by tschottdorf** [comment]
Not that ugly, actually. LGTM.

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 6 of 6 files at r5, 2 of 2 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[util/net.go, line 42 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAha_pNkflxFxrcQq4n:-KAha_pO9p0H04R_75_E:923218933) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8407c8d2c638a879be75eaf9f219e968cca336/util/net.go#L42)):*
doesn't look like this "really" should return anything.

---

*[util/net.go, line 45 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAha3z6ghsxVkit6DaA:-KAha3z6ghsxVkit6DaB:2053753478) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8407c8d2c638a879be75eaf9f219e968cca336/util/net.go#L45)):*
you can't embed `reader` and omit this?

---

*[util/net.go, line 122 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAhbA_C__hh4PTKuTNz:-KAhbA_C__hh4PTKuTO-:823324344) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8407c8d2c638a879be75eaf9f219e968cca336/util/net.go#L122)):*
what's the task/stopper situation here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-:-KAhbGVL-HnGf-Oz_nYy:-420553869)*

**Comment by tamird** [comment]
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/net.go, line 42 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAha_pNkflxFxrcQq4n:-KAhbtUviRMK2lcJjXBQ:1955021022) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8407c8d2c638a879be75eaf9f219e968cca336/util/net.go#L42)):*
yeah, that's how I had it originally, but now it returns a copy. do you have a preference?

---

*[util/net.go, line 45 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAha3z6ghsxVkit6DaA:-KAhc13PXlJN16MChwcA:1537406900) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8407c8d2c638a879be75eaf9f219e968cca336/util/net.go#L45)):*
Turns out it's a compile error, since `net.Conn` is also an `io.Reader`

---

*[util/net.go, line 122 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAhbA_C__hh4PTKuTNz:-KAhc6_Kq2k9Yy8iDxYu:1801352474) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8407c8d2c638a879be75eaf9f219e968cca336/util/net.go#L122)):*
Well, this line above will call into `handler`, which in non-test code will always be server.Server's ServeHTTP method, and that thing runs inside a task. Looking at this now, I don't need the `go` here. Simplified it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427)*

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/raft_transport.go, line 77 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAhfweVCGNsFOTT2LLO:-KAhfweVCGNsFOTT2LLP:-1479666803) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ad0303a7b1987b7a44875f3faa55b8a1be792d4/server/raft_transport.go#L77)):*
should this pattern be christened now that it's popping up everywhere?

---

*[util/net.go, line 42 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAha_pNkflxFxrcQq4n:-KAhezN6tJldx1j4uCss:937487319) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8407c8d2c638a879be75eaf9f219e968cca336/util/net.go#L42)):*
I have a slight preference for not returning anything.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[util/net.go, line 42 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAha_pNkflxFxrcQq4n:-KAjjY4T7q4pYIEDc3w0:554652548) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8407c8d2c638a879be75eaf9f219e968cca336/util/net.go#L42)):*
+1 to making this mutate a pointer instead of returning a copy. The original is unsafe to use once the copy is created so you might as well mutate it.

---

*[util/net.go, line 34 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAjjn2NEjQD2Mo0OBJo:-KAjjn2NEjQD2Mo0OBJp:-738340324) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced4516a55d367d020b0a53e5c2eab8c6ef9846/util/net.go#L34)):*
Nice, this was a lot simpler than I had expected.

---

*[util/net.go, line 120 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAjiujVxXaZNlGqnIe9:-KAjiujWcjKt4ZuzEaN7:1071844336) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced4516a55d367d020b0a53e5c2eab8c6ef9846/util/net.go#L120)):*
Both of these `ifs` need `elses`, even if they're just going to `log.Fatal`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-:-KAjmo2siPf10wNXJMEg:676834233)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 6 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[util/net.go, line 34 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAjjn2NEjQD2Mo0OBJo:-KAjpTm-lVaR76_I5o0T:84601268) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced4516a55d367d020b0a53e5c2eab8c6ef9846/util/net.go#L34)):*
The implementation looks good, though the naming doesn't seem quite right. I would think a `bufferedConn` is one that wraps a connection with a `bufio.Reader` and/or `bufio.Writer`. But that isn't what this does. Perhaps `replayableConn`. 

---

*[util/net.go, line 41 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAjqsaFeZgX8u4fnzwT:-KAjqsaFeZgX8u4fnzwU:-662096596) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced4516a55d367d020b0a53e5c2eab8c6ef9846/util/net.go#L41)):*
This won't work correctly if `replay` is called twice on a `bufferedConn`. Perhaps panic if `bc.reader` is already a multi reader. Hmm, that doesn't look easy to test, though. Perhaps just document that calling `replay` twice won't work. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-:-KAjrW4YPgTuHqAqo-6j:676834233)*

**Comment by tamird** [comment]
Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[util/net.go, line 34 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAjjn2NEjQD2Mo0OBJo:-KAjt_T_vGjNd7-Og5No:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced4516a55d367d020b0a53e5c2eab8c6ef9846/util/net.go#L34)):*
Done.

---

*[util/net.go, line 41 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAjqsaFeZgX8u4fnzwT:-KAju9QhvyzzWCxXfKLj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced4516a55d367d020b0a53e5c2eab8c6ef9846/util/net.go#L41)):*
Done.

---

*[util/net.go, line 120 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAjiujVxXaZNlGqnIe9:-KAjuKuFmoa1zzc-RNn7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced4516a55d367d020b0a53e5c2eab8c6ef9846/util/net.go#L120)):*
Done.

---

*[server/raft_transport.go, line 77 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAhfweVCGNsFOTT2LLO:-KAjuNA95ts9eWJkl9AI:-1792420046) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ad0303a7b1987b7a44875f3faa55b8a1be792d4/server/raft_transport.go#L77)):*
Yeah, I'm going to do that in a follow-up change, though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427)*

**Comment by tschottdorf** [comment]
LGTM

---

Reviewed 4 of 4 files at r10, 1 of 2 files at r11, 2 of 2 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[gossip/client.go, line 144 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAjtBQ16-TAlz9hBfgA:-KAjtBQ2J8kfOvZoBCjq:2110383392) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced4516a55d367d020b0a53e5c2eab8c6ef9846/gossip/client.go#L144)):*
what about
```go
g.mu.Lock()
args := ...
g.mu.Unlock()
if len(args.Delta) == 0 {
  return nil
}
return stream.Send(&args)
```

The overhead is negligible, right?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-:-KAjx21AXeupTSROSJv_:676834233)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[gossip/client.go, line 144 \[r11\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-KAjtBQ16-TAlz9hBfgA:-KAjykXF7MCJjDnVLSKI:-1743339982) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ced4516a55d367d020b0a53e5c2eab8c6ef9846/gossip/client.go#L144)):*
It's an allocation!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 9 of 14 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4427#-:-KAl9FRyJddTky7bYDIW:676834233)*

**Pull request merged**
