### PR TITLE
sql: remove connExecutor.eventLog and sql.trace.session_eventlog.enabled

### PR DESCRIPTION
**Pull request by petermattis**
The `connExecutor.eventLog` was capturing session events when `sql.trace.session_eventlog.enabled` was enabled (default false). This was historically used by SQL engineers for debugging the pgwire connection state machine, but is not in current use.

Epic: none
Release note (sql change): Remove sql.trace.session_eventlog.enabled and the associated event log tracing. The information in these traces is still available in the DEV log channel by enabling --vmodule=conn_executor=2.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117928#-:-NoSiWiMCCvfDFaQRaqg:b-g2a5fb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

**Comment by petermattis** [comment]
@mgartner or someone else from @cockroachdb/sql-queries, can you also give this a stamp of approval?

**Comment by yuzefovich** [comment]
I'm a member of SQL Queries, does my approval not count? :) Perhaps we should get a sign off from @rafiss or someone in @cockroachdb/sql-foundations.

**Comment by petermattis** [comment]
> I'm a member of SQL Queries, does my approval not count? :) Perhaps we should get a sign off from @rafiss or someone in @cockroachdb/sql-foundations.

Oh, it sure does. Brain fart about team membership there.

@rafiss

**Review by rafiss — APPROVED** [review]
thank you!

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117928#-:-NoSomr-90901PGAHw8r:bsv417h)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373)

**Comment by petermattis** [comment]
TFTR!

bors r+

**Pull request merged**
