### PR TITLE
opt: replace projections column set with a list

### PR DESCRIPTION
**Pull request by RaduBerinde**
The way we store projections in the memo does not allow us to list an
expression to a column index. This change replaces the ColSet with a
map and shows the map in the expression printouts.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/expr.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mF6qGVyGb7aBO1qX7:-L4mF6qHrBJM2yPY1rFz:bw1s66n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7177f8ce950d5c8456b8b74da7c748c0033c033/pkg/sql/opt/xform/expr.go#L195)):*
> ```Go
> 		private = ev.mem.metadata.ColumnLabel(colIndex)
> 
> 	case opt.ProjectionsOp:
> ```

I excluded this data because it was redundant with the Project output cols info. What additional benefit does printing it give? The trouble is that it makes output more "noisy" and harder to quickly understand.

---

*[pkg/util/fast_int_map.go, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mFTEBgRXLx6Lrs40f:-L4mFTEBgRXLx6Lrs40g:b5w52xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f32978e109fa36655c583e10ee8f40bc3d4396/pkg/util/fast_int_map.go#L19)):*
> ```Go
> import (
> 	"bytes"
> 	fmt "fmt"
> ```

why the alias?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-:-L4mF_ig2aPjawnretpy:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/expr.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mF6qGVyGb7aBO1qX7:-L4mIOoWYxEuRkzJNLNF:b-6uknp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7177f8ce950d5c8456b8b74da7c748c0033c033/pkg/sql/opt/xform/expr.go#L195)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I excluded this data because it was redundant with the Project output cols info. What additional benefit does printing it give? The trouble is that it makes output more "noisy" and harder to quickly understand.
</blockquote></details>

Consider this case:
```
build
SELECT x, x+1, y FROM t.a
----
project
 ├── columns: a.x:int:1 a.y:float:null:2 column3:int:null:3
 ├── scan
 │    └── columns: a.x:int:1 a.y:float:null:2
 └── projections: map[0:1 1:3 2:2] [type=tuple{int, int, float}]
      ├── variable: a.x [type=int]
      ├── plus [type=int]
      │    ├── variable: a.x [type=int]
      │    └── const: 1 [type=int]
      └── variable: a.y [type=float]
```
The third column in `columns` is actually the second expression.

I could omit the map in the common case where the indexes are in increasing order, but still show it in cases like this, what do you think?

---

*[pkg/util/fast_int_map.go, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mFTEBgRXLx6Lrs40f:-L4mHh7e56ScJay68R0c:b-9oh1wx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f32978e109fa36655c583e10ee8f40bc3d4396/pkg/util/fast_int_map.go#L19)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

why the alias?
</blockquote></details>

no idea, fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/build/testdata/aggregate, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mI7Yv4bK8yyiqtyII:-L4mI7Yv4bK8yyiqtyIJ:b-qtcc5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f32978e109fa36655c583e10ee8f40bc3d4396/pkg/sql/opt/build/testdata/aggregate#L25)):*
> ```
>  │    └── columns: kv.k:int:1 kv.v:int:null:2 kv.w:int:null:3 kv.s:string:null:4
>  ├── projections: map[] [type=tuple{}]
>  └── projections: map[1:6 5:10 10:15 0:5 2:7 4:9 6:11 3:8 7:12 8:13 9:14] [type=tuple{NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}]
> ```

Any chance we could print these indexes in order? (Alternatively just remove them, as Andy suggested below)

---

*[pkg/util/fast_int_map.go, line 194 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mJFg0GpmCYVUgPVGP:-L4mJFg0GpmCYVUgPVGQ:b9f6g5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f32978e109fa36655c583e10ee8f40bc3d4396/pkg/util/fast_int_map.go#L194)):*
> ```Go
> func (m FastIntMap) String() string {
> 	if m.large != nil {
> 		return fmt.Sprint(m.large)
> ```

I think this might be the source of the out-of-order issue above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-:-L4mJ_zNqb8VbPBXmRlk:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/build/testdata/aggregate, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mI7Yv4bK8yyiqtyII:-L4mKnJpWDQO0uY4d-Py:b-uh03pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f32978e109fa36655c583e10ee8f40bc3d4396/pkg/sql/opt/build/testdata/aggregate#L25)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Any chance we could print these indexes in order? (Alternatively just remove them, as Andy suggested below)
</blockquote></details>

Ah, I tried printing a map in the go playground and it seemed like it was always in increasing order, perhaps I used one that was too small. Fixed.

---

*[pkg/sql/opt/xform/expr.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mF6qGVyGb7aBO1qX7:-L4mOIjfM4s-VO-365Gb:b-5h8pir) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7177f8ce950d5c8456b8b74da7c748c0033c033/pkg/sql/opt/xform/expr.go#L195)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Consider this case:
```
build
SELECT x, x+1, y FROM t.a
----
project
 ├── columns: a.x:int:1 a.y:float:null:2 column3:int:null:3
 ├── scan
 │    └── columns: a.x:int:1 a.y:float:null:2
 └── projections: map[0:1 1:3 2:2] [type=tuple{int, int, float}]
      ├── variable: a.x [type=int]
      ├── plus [type=int]
      │    ├── variable: a.x [type=int]
      │    └── const: 1 [type=int]
      └── variable: a.y [type=float]
```
The third column in `columns` is actually the second expression.

I could omit the map in the common case where the indexes are in increasing order, but still show it in cases like this, what do you think?
</blockquote></details>

I omitted it when it's increasing. Let me know if this is fine or if you prefer to omit it always.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483)*

**Comment by rytaft** [comment]
Reviewed 4 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/xform/expr.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mF6qGVyGb7aBO1qX7:-L4mPlRLzcGz0UJfuPqg:bdf3cso) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7177f8ce950d5c8456b8b74da7c748c0033c033/pkg/sql/opt/xform/expr.go#L195)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I omitted it when it's increasing. Let me know if this is fine or if you prefer to omit it always.
</blockquote></details>

It's still somewhat redundant since the columns are printed in the correct order in the tree under the projections node

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/xform/expr.go, line 195 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22483#-L4mF6qGVyGb7aBO1qX7:-L4mRsYF-NDmoUkv2YCY:b-d4y9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7177f8ce950d5c8456b8b74da7c748c0033c033/pkg/sql/opt/xform/expr.go#L195)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It's still somewhat redundant since the columns are printed in the correct order in the tree under the projections node
</blockquote></details>

The expressions, but not the column indexes.. There is no other way of associating `column3` with the `plus` expression, unless you know how the indexes are generated.

Perhaps a nicer alternative would be to special case the project op and use the map to reorder the columns in the `columns:` line?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22483)*

**Comment by rytaft** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/expr.go, line 195 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22483#-L4mF6qGVyGb7aBO1qX7:-L4mVXu32WouoF6AlFkF:b302pnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7177f8ce950d5c8456b8b74da7c748c0033c033/pkg/sql/opt/xform/expr.go#L195)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The expressions, but not the column indexes.. There is no other way of associating `column3` with the `plus` expression, unless you know how the indexes are generated.

Perhaps a nicer alternative would be to special case the project op and use the map to reorder the columns in the `columns:` line?
</blockquote></details>

:thumbsup: good idea

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22483)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/expr.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mF6qGVyGb7aBO1qX7:-L4mZ1y_FVUspEEt-Iht:byqj5o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7177f8ce950d5c8456b8b74da7c748c0033c033/pkg/sql/opt/xform/expr.go#L195)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

:thumbsup: good idea
</blockquote></details>

Yeah, I like the special-casing `Project` idea. I think we want to look for ways to keep this tree output as simple and clean as possible, b/c we'll be looking at it *a lot*.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/expr.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mF6qGVyGb7aBO1qX7:-L4mZy_3RaJ7XZNNYL_R:bcqw5yf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7177f8ce950d5c8456b8b74da7c748c0033c033/pkg/sql/opt/xform/expr.go#L195)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yeah, I like the special-casing `Project` idea. I think we want to look for ways to keep this tree output as simple and clean as possible, b/c we'll be looking at it *a lot*.
</blockquote></details>

Along those lines, I've wondered if we should omit the type from Projections, since it doesn't add much - it's always a tuple of the types we already list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483)*

**Comment by RaduBerinde** [comment]
Review status: 5 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/xform/expr.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mF6qGVyGb7aBO1qX7:-L4nXqMLJ_6Ace9UaLDp:b-b1rcnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7177f8ce950d5c8456b8b74da7c748c0033c033/pkg/sql/opt/xform/expr.go#L195)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Along those lines, I've wondered if we should omit the type from Projections, since it doesn't add much - it's always a tuple of the types we already list.
</blockquote></details>

Done (both). This is much nicer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483)*

**Comment by rytaft** [comment]
Reviewed 1 of 4 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/expr.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483#-L4mF6qGVyGb7aBO1qX7:-L4pkqSXJ73XgA3fq7QW:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7177f8ce950d5c8456b8b74da7c748c0033c033/pkg/sql/opt/xform/expr.go#L195)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done (both). This is much nicer.
</blockquote></details>

Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22483)*

**Pull request merged**
