### PR TITLE
gossip: Fix updateNodeAddress to not ignore certain updates

### LINKED ISSUE #15856: gossip: panic in infostore due to uninitialized node ID
https://sentry.io/cockroach-labs/cockroachdb/issues/270737359/

```
*errors.errorString: string infostore.go:151
  File "github.com/cockroachdb/cockroach/pkg/gossip/infostore.go", line 151, in newInfo
  File "github.com/cockroachdb/cockroach/pkg/gossip/gossip.go", line 764, in addInfoLocked
  File "github.com/cockroachdb/cockroach/pkg/gossip/gossip.go", line 675, in updateNodeAddress
  File "github.com/cockroachdb/cockroach/pkg/gossip/gossip.go", line 263, in updateNodeAddress)-fm
  File "github.com/cockroachdb/cockroach/pkg/gossip/infostore.go", line 277, in func1
  File "github.com/cockroachdb/cockroach/pkg/gossip/infostore.go", line 299, in func2
  File "github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go", line 294, in func1
```

### PR DESCRIPTION
**Pull request by a-robinson**
Previously, if node b moved to node c's address (effectively
replacing node c), existing nodes would not remove node c's descriptor
from gossip because node b's ID was already known. This could cause
problems upon node restart, because the restarting node would be given
two node descriptors for the same address, which could cause panics if
it processed them before initializing its own node ID.

Fixes #15856

I wouldn't say it's necessarily needed, but we should at least consider this for 1.0.1 given the panics that have been seen in the wild - https://sentry.io/cockroach-labs/cockroachdb/issues/270737359/

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

Testing this should be easy enough, WDYT?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15928#-:-KkCAR9VSFeTPxAyJ5CI:bvsbg3q)*

**Comment by a-robinson** [comment]
Yeah, was easier than I had expected. Done.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15928#-:-KkCPAdkWTCLWe5FgBkI:b-om0mjv)*

**Comment by a-robinson** [comment]
Any comments on the test?

**Comment by tamird** [comment]
Looking now.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/gossip_test.go, line 135 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15928#-KkCeOam-HJ-RTuJfydM:-KkCeOam-HJ-RTuJfydN:b-la03fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf8d106970d4217cbc4a07170f4effc433d362e/pkg/gossip/gossip_test.go#L135)):*
> ```Go
> 	for _, node := range nodes {
> 		if val, err := g.GetNodeDescriptor(node.NodeID); err != nil {
> 			t.Error(err)
> ```

is it valid to continue the test, here?

---

*[pkg/gossip/gossip_test.go, line 154 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15928#-KkCeZfmX71jGyhnR5SL:-KkCeZfmX71jGyhnR5SM:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf8d106970d4217cbc4a07170f4effc433d362e/pkg/gossip/gossip_test.go#L154)):*
> ```Go
> 	stopper.Quiesce(context.TODO())
> 	if val, err := g.GetNodeDescriptor(movedNode.NodeID); err != nil {
> 		t.Error(err)
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15928#-:-KkCega_U1e-BZrW3eQo:bnfp4nl)*

**Comment by a-robinson** [comment]
Thanks!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/gossip_test.go, line 135 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15928#-KkCeOam-HJ-RTuJfydM:-KkCgHkC18GFX-udPtqb:bddp37h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf8d106970d4217cbc4a07170f4effc433d362e/pkg/gossip/gossip_test.go#L135)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is it valid to continue the test, here?
</blockquote></details>

Nope, done.

---

*[pkg/gossip/gossip_test.go, line 154 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15928#-KkCeZfmX71jGyhnR5SL:-KkCgLr5ZuUhoewpT3KM:b-r9pvx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf8d106970d4217cbc4a07170f4effc433d362e/pkg/gossip/gossip_test.go#L154)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

If this failed I'd still be curious to see what the final check says, so leaving as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15928#-:-KkCgXMvaOdF2xpeq-rZ:b-ucfknh)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15928)*

**Pull request merged**
