### PR TITLE
go.mod: update to pgx v4.13

### LINKED ISSUE #62840: sql: refactor pgx_helpers to use pgx/v4
Currently `pgx_helpers.go` and most notably `MultiConnPool` which is used in workloads uses pgx, upgrading it to pgx/v4 adds many more options for connections such as MaxConnLifetime and MaxConnIdleTime.

Context here:
https://github.com/cockroachdb/cockroach/pull/62740#pullrequestreview-624665640

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/62840

This also required an update to cockroach-go/v2 to get the crdbpgx
transaction retry helper.

The majority of changes here are because pgx now requires the context to
be passed in always.

Other changes:
* The way that pgx prepares statements has changed -- to disable
automatic prepared statements, the PreferSimpleProtocol setting must be
enabled when making the pgxpool.
* The `noprepare` setting was removed from `workload`. This functionality
is not supported by pgx any more. pgx will either use prepared statements and
cache them automatically or use the simple protocol.
* sqlproxy tests had to be modified since pgx now has more
fallback logic to retry connections when using an sslmode of `prefer`
or `allow`. pgx also now tries to resolve `localhost` as the IPv6 address
`:::1`, which isn't well-supported by sqlproxy, so IP resolution was disabled
for sqlproxy tests.
* CHANGEFEED tests had to be changed since `pgx.Conn.Query` now immediately
tries fetching the results, which didn't work with the synchronization that was added
to TestChangefeedDataTTL.
* COPY was fixed to correctly ignore CopyData after encountering an error.

Release note: None

### CODE REVIEW

**Review by otan — APPROVED** [review]
some test failures but they look like you'd have to massage them differently, lgtm

**Review by knz — APPROVED** [review]
> Reviewed 55 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @rafiss, and @stevendanna)

___
*[pkg/ccl/backupccl/backup_test.go, line 7297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68608#-MgkSLYJ58BJZlA4JDqq:-MgkSLYJ58BJZlA4JDqr:b-c6ttf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472c4483bdd67c2f20119574940b8cff0457ba7/pkg/ccl/backupccl/backup_test.go#L7297)):*
> ```Go
> 				db, err := pgx.ConnectConfig(ctx, connCfg)
> 				assert.NoError(t, err)
> 				defer func() { _ = db.Close(ctx) }()
> ```

`assert.NoError(t, db.Close(ctxo))`
___
*[pkg/workload/kv/kv.go, line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68608#-MgkX8h36hBkQ5C291O2:-MgkX8h36hBkQ5C291O3:b-6lgbfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472c4483bdd67c2f20119574940b8cff0457ba7/pkg/workload/kv/kv.go#L444)):*
> ```Go
> 		}
> 		defer func() {
> 			_ = tx.Rollback(ctx)
> ```

maybe assert the return value?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68608)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @knz, and @stevendanna)

___
*[pkg/ccl/backupccl/backup_test.go, line 7297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68608#-MgkSLYJ58BJZlA4JDqq:-Mgkg1ZC-RjcIDb-Cuug:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472c4483bdd67c2f20119574940b8cff0457ba7/pkg/ccl/backupccl/backup_test.go#L7297)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`assert.NoError(t, db.Close(ctxo))`
</blockquote></details>

done
___
*[pkg/workload/kv/kv.go, line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68608#-MgkX8h36hBkQ5C291O2:-Mgkg0j11iTLjWCoZvgW:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a472c4483bdd67c2f20119574940b8cff0457ba7/pkg/workload/kv/kv.go#L444)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe assert the return value?
</blockquote></details>

done

**Comment by rafiss** [comment]
`TestFailedConnection` is failing in CI, but I cannot get it to fail even when running it under `stress` on a GCE Worker.

Will debug later today or tomorrow.

**Comment by rafiss** [comment]
@stevendanna if you have some time would you be able to help me with this?

I'm trying to upgrade our pgx dependency to use v4 across the board, and I've encountered an issue in `TestChangefeedDataTTL` which it seems like you have touched last.

The test is getting stuck at this line: https://github.com/cockroachdb/cockroach/blob/ab15e5f3cf0cd648b393dfbee500065d56b83866/pkg/ccl/changefeedccl/changefeed_test.go#L2328

The reason is because the `sinklessFeed` is gets stuck when making the changefeed: https://github.com/cockroachdb/cockroach/blob/ab15e5f3cf0cd648b393dfbee500065d56b83866/pkg/ccl/changefeedccl/testfeed_test.go#L186

pgx v4 differs from the old pgx in that it immediately tries to fetch the result [when running `Query()`](https://github.com/jackc/pgx/blob/23b4656fc573dcecd8bdce9c0235249e73d384f4/conn.go#L602). That means the [synchronization logic](https://github.com/cockroachdb/cockroach/blob/ab15e5f3cf0cd648b393dfbee500065d56b83866/pkg/ccl/changefeedccl/changefeed_test.go#L2293-L2297) in the test won't let the `pgx.Conn.Query("CREATE CHANGEFEED ...")` statement complete. 

Do you have any other ideas on how to synchronize here while still achieving the goals of the test? The other option I thought of is to jump into a lower level and use `jackc/pgconn` to create the changefeed without trying to pull results from it right away, but that seems like a big refactor and isn't my first choice.

**Comment by rafiss** [comment]
I understand the test a bit better now -- @stevendanna when you have a chance, please review the diff in `pkg/ccl/changefeedccl/changefeed_test.go`

**Review by stevendanna — APPROVED** [review]
Uff, apologies for the delay here.  Thanks for digging into this. I think your fix looks reasonable. This test has been a thorn in our side for a bit as the existing coordination is a bit suspected.  I noted a small nitpick but overall it :LGTM:

> Reviewed 1 of 35 files at r3, 1 of 25 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68608#-:-MhIf9GT62ckZlknuqz0:b-8gwh8u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @knz, and @rafiss)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2373 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/68608#-MhIg1L51Xt4tCZfwjIK:-MhIg1L66sOPbJapFEYP:b-y9t1jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/174c020b93b08890b007929337aafe12f9177681/pkg/ccl/changefeedccl/changefeed_test.go#L2373)):*
> ```Go
> 		resume <- struct{}{}
> 		dataExpiredRows := <-changefeedInit
> 		defer closeFeed(t, dataExpiredRows)
> ```

[nit] We could fail to clean up this feed if there are errors above in upsertRow() or forceTableGC. 
___
*[pkg/ccl/changefeedccl/testfeed_test.go, line 129 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/68608#-MhIgNiU-wE6WVbNuS5z:-MhIgNiU-wE6WVbNuS6-:bqp7ftg) ([raw file](https://github.com/cockroachdb/cockroach/blob/174c020b93b08890b007929337aafe12f9177681/pkg/ccl/changefeedccl/testfeed_test.go#L129)):*
> ```Go
> }
> 
> var _ cdctest.TestFeed = (*sinklessFeed)(nil)
> ```

Thanks for adding these!

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68608)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @knz, @rafiss, and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2373 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/68608#-MhIg1L51Xt4tCZfwjIK:-MhJM1ax1yrzYaD2lzLJ:b65b305) ([raw file](https://github.com/cockroachdb/cockroach/blob/174c020b93b08890b007929337aafe12f9177681/pkg/ccl/changefeedccl/changefeed_test.go#L2373)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] We could fail to clean up this feed if there are errors above in upsertRow() or forceTableGC. 
</blockquote></details>

in that case there would have already been a t.Fatal, or otherwise `closeFeed` itself will call t.Fatal

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68608)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @knz, @rafiss, and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2373 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/68608#-MhIg1L51Xt4tCZfwjIK:-MhJN2318EfwfBUWnXqh:b-w26dd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/174c020b93b08890b007929337aafe12f9177681/pkg/ccl/changefeedccl/changefeed_test.go#L2373)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in that case there would have already been a t.Fatal, or otherwise `closeFeed` itself will call t.Fatal
</blockquote></details>

ah, i see your point. the execution could stop before reaching this defer. fixing it, nice catch!

**Comment by rafiss** [comment]
thanks for the reviews all!

bors r=otan,knz,stevendanna

**Pull request merged**
