### PR TITLE
sql: allow UPDATE to modify primary key columns

### LINKED ISSUE #5943: sql: allow UPDATE to modify primary key columns
`UPDATE` currently disallows modifications to the primary key columns. There is no strong reason for this restriction. A modification to a primary key column would need to delete and rewrite any existing column data for the row and for associated indexes which reference the primary key, but these keys and values can be derived from the data available to `UPDATE`.

### PR DESCRIPTION
**Pull request by danhhz**
Closes #5943.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6043)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/update.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFtzPggMv9faRheZUh:-KFFtzPggMv9faRheZUi:1883425623) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L48)):*
This is a good example of something that can be cached in the table descriptor. Just add a TODO.

---

*[sql/update.go, line 190 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFul6BnJzPUC96F6TB:-KFFuaeEmsL6sxHT0-os:-612637951) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L190)):*
might as well just short circuit this
```
if primaryKeyColChange {
return true
}
```

---

*[sql/update.go, line 277 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFvEVRP8Ey7um1CNeU:-KFFvEVRP8Ey7um1CNeV:-1412285761) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L277)):*
Looks like you're always doing this. A change of a column to a primary key is rare, we shouldn't need to always run this code.

---

*[sql/update.go, line 341 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFwjJzOOHVfmRlpxoY:-KFFwjJzOOHVfmRlpxoZ:-1879909222) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L341)):*
One thing to note is that an Update once it's updating a column that's part of a primary index and the index key changes, it's behavior is like an INSERT followed by a DELETE. Can you reuse code better by implementing it using those two methods?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[sql/update.go, line 339 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG1y7I4vpTTQ-rV1BQ:-KFG1y7I4vpTTQ-rV1BR:-1174720165) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L339)):*
Maybe add a comment here about the state of the row. Something along the lines of:

```
// At this point, we've deleted the old row and associate index data and written the sentinel
// keys and column keys for non-updated columns. Fall through to below where the index 
// keys and updated column keys will be written.
```

---

*[sql/update.go, line 349 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG1I0vILOmR_CGbGFA:-KFG1I0vILOmR_CGbGFB:-1822648434) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L349)):*
Didn't you already delete the secondary index above if `rowPrimaryKeyChanged` is true?

---

*[sql/testdata/update, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG2YqTX6-r2Ujs9imf:-KFG2YqTX6-r2Ujs9img:308077872) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/testdata/update#L228)):*
`s/select/SELECT/g` to maintain our capitalization

---

*[sql/testdata/update, line 233 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG2dsWFZ-hA_ABxJo3:-KFG2dsWFZ-hA_ABxJo4:-2037807881) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/testdata/update#L233)):*
You might want to `s/abc/abc@d/g` to force usage of index `d`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-:-KFG2oGEgQZS-t3g29nO:1417088721)*

**Comment by paperstreet** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[sql/update.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFtzPggMv9faRheZUh:-KFFzyItrBxhDrlX87cw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L48)):*
Done.

---

*[sql/update.go, line 190 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFul6BnJzPUC96F6TB:-KFFzlwA_z--T4U6mGbQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L190)):*
Done.

---

*[sql/update.go, line 277 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFvEVRP8Ey7um1CNeU:-KFG0-zVMBZOXEBTUkzy:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L277)):*
Done.

---

*[sql/update.go, line 339 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG1y7I4vpTTQ-rV1BQ:-KFG6-FF_kq0fRodN9aM:524086435) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L339)):*
Great idea. Done

---

*[sql/update.go, line 341 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFwjJzOOHVfmRlpxoY:-KFFzz0l-zHZz_iSyazr:-1006646865) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L341)):*
Yes, absolutely. I'm planning to do some of that cleanup as part of UPSERT (which is next on my plate).

---

*[sql/update.go, line 349 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG1I0vILOmR_CGbGFA:-KFG6Fkap8NyJ6SXaCJy:1321340958) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L349)):*
Yeah, I was on the fence about whether it mattered. Fixed.

---

*[sql/testdata/update, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG2YqTX6-r2Ujs9imf:-KFG5W7yh9Z12-WvbikP:-612889902) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/testdata/update#L228)):*
Oops. Done.

---

*[sql/testdata/update, line 233 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG2dsWFZ-hA_ABxJo3:-KFG5VNM0FZqTNbWvhXk:160388434) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/testdata/update#L233)):*
TIL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/update.go, line 349 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG1I0vILOmR_CGbGFA:-KFG8kGHYu0DW1YWs03G:1747329967) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L349)):*
It wouldn't matter for correctness, but it does for performance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043)*

**Comment by RaduBerinde** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[sql/update.go, line 292 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG8dEv4i73j-yy2Yyh:-KFG8dEv4i73j-yy2Yyi:-1338353954) ([raw file](https://github.com/cockroachdb/cockroach/blob/050d4b3c94906344da6ce17a9c22a6bef923df69/sql/update.go#L292)):*
I would declare this above and only set it in the `if primaryKeyColChange` block above.

---

*[sql/testdata/update, line 223 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG9SbjndHDlqMwtfza:-KFG9SbkU6IpOIoCHqUU:-47293080) ([raw file](https://github.com/cockroachdb/cockroach/blob/050d4b3c94906344da6ce17a9c22a6bef923df69/sql/testdata/update#L223)):*
Can you add a case where the updated PK causes a PK conflict? And one where the updated PK causes a unique index conflict (e.g. if primary key columns are k1 k2 and we have an unique index on k2,v)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-:-KFG9gL4TXjlYwQ15dGT:676834233)*

**Comment by paperstreet** [comment]
Thanks for the review!

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[sql/update.go, line 292 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG8dEv4i73j-yy2Yyh:-KFGAmlU4cAHcqmYEjNk:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/050d4b3c94906344da6ce17a9c22a6bef923df69/sql/update.go#L292)):*
Done.

---

*[sql/testdata/update, line 223 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFG9SbjndHDlqMwtfza:-KFGAoDWa49iuz_6w7PQ:-1221810807) ([raw file](https://github.com/cockroachdb/cockroach/blob/050d4b3c94906344da6ce17a9c22a6bef923df69/sql/testdata/update#L223)):*
Good idea. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-:-KFGEcSu8suTeNK4A2Q6:-588504495)*

**Comment by RaduBerinde** [comment]
*[sql/update.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFtzPggMv9faRheZUh:-KFsWgagBSticoODbEKh:-1711986707) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L48)):*
Hi Vivek, I was thinking of caching the colID->index map in the table descriptor and I remembered this comment. How do you envision doing this? TableDescriptor is a protobuf type.. Is it possible to add non-proto fields to that type? If not, we would have to create a new type that has TableDescriptor as a field and adds some more stuff (but it would be a pretty invasive change)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/update.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFtzPggMv9faRheZUh:-KFsoo8bb6I1NwkWBzgg:-1900780647) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L48)):*
No, it isn't possible to add non-proto fields to `TableDescriptor`. I see two options here: you could create a new wrapper struct (`MemTableDescriptor`) that is passed around instead of `TableDescriptor`. Or you could add a `map` field to `TableDescriptor` that is populated when the descriptor is read and cleared before being written. This map field would look something like:

```
message TableDescriptor {

  map<ColumnID, bool> primary_key_columns;
  map<ColumnID, int> column_id_to_index;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/update.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043#-KFFtzPggMv9faRheZUh:-KFt-IBmgAqS6Xn8lRKi:1715213268) ([raw file](https://github.com/cockroachdb/cockroach/blob/b096b4beb56089f4121162df28755ff65939347d/sql/update.go#L48)):*
Given that we have a cache, it probably makes sense to create a new temp struct that also holds the schema for each table. But I'd wait on this until we see more use cases for this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6043)*

**Pull request merged**
