### PR TITLE
opt: index constraints for top-level OR

### PR DESCRIPTION
**Pull request by RaduBerinde**
Support top-level disjunction for index constraints:
 - use the existing code to generate spans for each disjunct
 - add new code to merge span sets.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 541 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1If-Psp93prtygjayp:-L1If-PtB-nl0_PTsM26:b-g60upf) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints.go#L541)):*
> ```Go
> 		orExprs = filter.children
> 	} else {
> 		orExprs = []*expr{filter}
> ```

This and the handling of `andExprs` below feels a bit awkward, though I'm blanking on a better approach.

---

*[pkg/sql/opt/index_constraints_spans.go, line 246 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1IfdxpxWxq7h2NDY1O:-L1Ifdxqr3UD_Gh-ag-j:b-nybwmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints_spans.go#L246)):*
> ```Go
> 	}
> 	switch {
> 	case len(prevSpanEnd.Vals) < len(spanStart.Vals):
> ```

It is somewhat surprising to me that `compareKeyVals` only compares `min(len(prevSpanEnd.Vals), len(spanStart.Vals))`.

---

*[pkg/sql/opt/index_constraints_spans.go, line 377 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1Ij2-0Tlz4kvkipgB5:-L1Ij2-0Tlz4kvkipgB6:b7a8cpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints_spans.go#L377)):*
> ```Go
> // generates their union (as ordered, non-overlapping spans).
> func (c *indexConstraintCtx) mergeSpanSets(
> 	offset int, a LogicalSpans, b LogicalSpans,
> ```

Are you ever passing a non-zero `offset` to `mergeSpanSets`?

---

*[pkg/sql/opt/index_constraints_spans.go, line 392 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1IjQW5ofj01HAcl_C9:-L1IjQW5ofj01HAcl_CA:bek2vlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints_spans.go#L392)):*
> ```Go
> 		a = a[1:]
> 
> 		// Merge this span with any overlapping spans in a or b.
> ```

Since `a` started as a set of non-overlapping spans, `span` can't overlap with `a`, right? I'm not clear about this comment or why you need to check against `a` in the loop below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-:-L1Ik6Ve4NP5uCK3VgCN:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/index_constraints.go, line 541 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1If-Psp93prtygjayp:-L1J6PIXNnAI6HFHJC-W:beg4di9) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints.go#L541)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This and the handling of `andExprs` below feels a bit awkward, though I'm blanking on a better approach.
</blockquote></details>

I could make `makeIndexConstraintsCalc` take a variable number of `andExprs` (and similarly move the code to handle `orExpr`s to a separate function with a vararg) but I think it would cause the same amount of allocations.

---

*[pkg/sql/opt/index_constraints_spans.go, line 246 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1IfdxpxWxq7h2NDY1O:-L1J3zqGhNN9yKZMnCOr:bq28sie) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints_spans.go#L246)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It is somewhat surprising to me that `compareKeyVals` only compares `min(len(prevSpanEnd.Vals), len(spanStart.Vals))`.
</blockquote></details>

It is documented as "Returns 0 if the lists are equal, or one is a prefix of the other". The trouble is that there is no "universal" way to compare them, it depends if what kind of keys we are comparing.

---

*[pkg/sql/opt/index_constraints_spans.go, line 377 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1Ij2-0Tlz4kvkipgB5:-L1J4F0VHU4a8oD6BxOF:b-vc5yhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints_spans.go#L377)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are you ever passing a non-zero `offset` to `mergeSpanSets`?
</blockquote></details>

Not right now, but all the code in this file uses `offset`. We may want to use that later, e.g. to handle "inner" ORs, e.g. `(A = 1 AND (B = 1 OR B = 2))`

---

*[pkg/sql/opt/index_constraints_spans.go, line 392 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1IjQW5ofj01HAcl_C9:-L1J4QlSIfsJ_UAij-Mh:bp5u8aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints_spans.go#L392)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Since `a` started as a set of non-overlapping spans, `span` can't overlap with `a`, right? I'm not clear about this comment or why you need to check against `a` in the loop below.
</blockquote></details>

You're right that the first check in the first iteration of the loop is not needed. But it is needed in later iterations, because `span` can be extended, leading to new overlaps. I extended the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/index_constraints.go, line 541 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1If-Psp93prtygjayp:-L1JM08UE8NOlCMFCJfT:bplaj98) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints.go#L541)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I could make `makeIndexConstraintsCalc` take a variable number of `andExprs` (and similarly move the code to handle `orExpr`s to a separate function with a vararg) but I think it would cause the same amount of allocations.
</blockquote></details>

I pushed the `andOp` handling inside `makeIndexConstraintsCalc` and refactored the rest of the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints_spans.go, line 246 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1IfdxpxWxq7h2NDY1O:-L1KckdQDdig7QVgPReJ:b-bdd5gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints_spans.go#L246)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It is documented as "Returns 0 if the lists are equal, or one is a prefix of the other". The trouble is that there is no "universal" way to compare them, it depends if what kind of keys we are comparing.
</blockquote></details>

Ack. I don't have a good suggestion for improvement here, just noting the unintuitiveness. 

---

*[pkg/sql/opt/index_constraints_spans.go, line 392 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1IjQW5ofj01HAcl_C9:-L1KdFzegJ9hHf6dNbIu:b-2js6z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/250474dc63f4fbfaca7d4b0d5d4299a2be67e9f5/pkg/sql/opt/index_constraints_spans.go#L392)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

You're right that the first check in the first iteration of the loop is not needed. But it is needed in later iterations, because `span` can be extended, leading to new overlaps. I extended the comment.
</blockquote></details>

Ack. Thanks for the expanded comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028)*

**Comment by knz** [comment]
:lgtm: but I have a question

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1N9N7AxkFFWRmRCQtO:-L1N9N7B91QLILKjdFwf:b-lnzbbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8f9db14d75ecfbd29899eafc8307913d1510ee/pkg/sql/opt/index_constraints.go#L51)):*
> ```Go
> 		c.andExprs = e.children
> 	} else {
> 		c.andExprs = []*expr{e}
> ```

Is there no way to re-use arrays instead of going to the heap every time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-:-L1N9kysq9MKPHLK5EAq:b-dfrhag)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/index_constraints.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1N9N7AxkFFWRmRCQtO:-L1NHUM22Wn-x98PAIXf:b-1nykhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8f9db14d75ecfbd29899eafc8307913d1510ee/pkg/sql/opt/index_constraints.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Is there no way to re-use arrays instead of going to the heap every time?
</blockquote></details>

I can put an `[1]expr` in `indexConstraintCalc` and use it for this case. I can do that if you think it matters. I didn't do it mainly because there's another TODO around perhaps organizing the `andExprs` in a map (but I'm not sure doing that is worth it, it would only matter if there are a lot of expressions).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1N9N7AxkFFWRmRCQtO:-L1NJaPRj3rJDccZ_PqU:bnwcrcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8f9db14d75ecfbd29899eafc8307913d1510ee/pkg/sql/opt/index_constraints.go#L51)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I can put an `[1]expr` in `indexConstraintCalc` and use it for this case. I can do that if you think it matters. I didn't do it mainly because there's another TODO around perhaps organizing the `andExprs` in a map (but I'm not sure doing that is worth it, it would only matter if there are a lot of expressions).
</blockquote></details>

It does not matter in this PR but it is a strong concern I have throughout this package. I do believe so far this code is putting more pressure on the heap than our legacy code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/index_constraints.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1N9N7AxkFFWRmRCQtO:-L1NMBHXSudvlHwFzEB_:bjhvmt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8f9db14d75ecfbd29899eafc8307913d1510ee/pkg/sql/opt/index_constraints.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

It does not matter in this PR but it is a strong concern I have throughout this package. I do believe so far this code is putting more pressure on the heap than our legacy code.
</blockquote></details>

Can you be more specific about which parts are worrisome to you? The expression build code is IMO better than the legacy code because we bulk-allocate the nodes.

The index constraint code is more complicated and indeed there may be more allocations, but it is a work in progress. We will be adding benchmarks and such.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1N9N7AxkFFWRmRCQtO:-L1NN3kb32y78teoGNJK:brlwcky) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8f9db14d75ecfbd29899eafc8307913d1510ee/pkg/sql/opt/index_constraints.go#L51)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you be more specific about which parts are worrisome to you? The expression build code is IMO better than the legacy code because we bulk-allocate the nodes.

The index constraint code is more complicated and indeed there may be more allocations, but it is a work in progress. We will be adding benchmarks and such.
</blockquote></details>

There is no single part that is worrisome to me. Like every time we think about allocations, it's the behavior of the whole that needs to be considered. Indeed, via alloc benchmarks -- but not only micro-benchmarks on single functions, actually the entire optimization pipeline needs to be considered across a set of queries.

In reaction to "We will be adding benchmarks and such" -- I really liked it when, a couple months ago, you were including before/after benchmarks on significant code changes related to sql optimizations. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/index_constraints.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1N9N7AxkFFWRmRCQtO:-L1NQqi6x0fZ9o9kpfR2:b-zk71m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8f9db14d75ecfbd29899eafc8307913d1510ee/pkg/sql/opt/index_constraints.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

There is no single part that is worrisome to me. Like every time we think about allocations, it's the behavior of the whole that needs to be considered. Indeed, via alloc benchmarks -- but not only micro-benchmarks on single functions, actually the entire optimization pipeline needs to be considered across a set of queries.

In reaction to "We will be adding benchmarks and such" -- I really liked it when, a couple months ago, you were including before/after benchmarks on significant code changes related to sql optimizations. 
</blockquote></details>

When we will wire up the new code to replace the existing index constraint generation code, we will compare some sql planning benchmarks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/index_constraints.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028#-L1N9N7AxkFFWRmRCQtO:-L1NZGtwtP4ymkFBdGLq:b4bbe52) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8f9db14d75ecfbd29899eafc8307913d1510ee/pkg/sql/opt/index_constraints.go#L51)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

When we will wire up the new code to replace the existing index constraint generation code, we will compare some sql planning benchmarks.
</blockquote></details>

Cheers!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21028)*

**Pull request merged**
