### PR TITLE
opt: introduce memo.ExistsPrivate and add lazy projection column

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: introduce memo.ExistsPrivate and add lazy projection column

This commit introduces the `memo.ExistsPrivate` struct, which wraps the
`memo.SubqueryPrivate` struct. This new private struct has a column that
is used during the execbuilder phase if the Exists subquery is planned
as a lazily-evaluated routine. By adding this column to the Exists
expression, we can avoid the anti-pattern of creating a new column ID in
the execbuilder. This will be beneficial in future commits in which
execbuilder will rely on knowing the maximum column ID for a query plan
before it begins constructing execution nodes.

Release note: None

#### opt: move WasLimited from SubqueryPrivate to ExistsPrivate

The `WasLimited` field is only used for Exists subqueries, so it has
been moved from `SubqueryPrivate` to `ExistsPrivate`.

Release note: None

#### opt: remove IntroduceExistsLimit rule

This rule has been superseded by the
`ConvertUncorrelatedExistsToCoalesceSubquery` rule. Since that rule was
introduced, `IntroduceExistsLimit` should have never matched.

Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
This change is a prerequisite for the changes in #119095.

**Comment by mgartner** [comment]
The diff is quite large, but most of it is changes to column IDs in optimizer tests. I'm happy to walk through all the changes if that'd be helpful.

**Review by DrewKimball — APPROVED** [review]
:lgtm: 

> Reviewed 50 of 50 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119094#-:-Nq_9o-tDgQhx7HiUS7z:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119094#-Nq_9cJx8CX4w5cY_DPN):*
I think you could go further, and just remove `WasLimited` entirely and replace it with a `HasZeroOrOneRow` check.
___
*[`pkg/sql/opt/ops/scalar.opt` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119094#-Nq_6ESjAtb7sKkTabEJ:-Nq_6ESjAtb7sKkTabEK:b-bb4jw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51b7eba5cf6ecba497947a97d464da597b48839/pkg/sql/opt/ops/scalar.opt#L35)):*
> ```
> # SubqueryPrivate contains information related to a subquery (Subquery, Any,
> # Exists). It is shared between the Subquery and Any operators so that the same
> # rules can be used across all both expressions.
> ```

[nit] `all both` -> `both`

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119094)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`-- commits` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119094#-Nq_9cJx8CX4w5cY_DPN):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think you could go further, and just remove `WasLimited` entirely and replace it with a `HasZeroOrOneRow` check.
</blockquote></details>

Good idea. I went even further and removed `IntroduceExistsLimit` entirely in the third commit.
___
*[`pkg/sql/opt/ops/scalar.opt` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119094#-Nq_6ESjAtb7sKkTabEJ:-NrHib5h68n1erJvNZMz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51b7eba5cf6ecba497947a97d464da597b48839/pkg/sql/opt/ops/scalar.opt#L35)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `all both` -> `both`
</blockquote></details>

Done.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice!

> Reviewed 3 of 3 files at r3, 2 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119094#-:-NrILzSm8qgrSb0FlUcz:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
