### PR TITLE
ui: add badges for filter elements

### PR DESCRIPTION
**Pull request by maryliag**
Adds badges for each of the selected filters on SQL Activity and
Insights pages.

Part Of #98891

https://www.loom.com/share/e7417209fc704d71b2733f58609fb4de

Screenshot 2023-03-19 at 1 30 49 PM

Release note (ui change): Adds badges for each selected
filter on SQL Activity and Insights pages.

### CODE REVIEW

**Review by THardy98 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dongniwang and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx` line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98988#-NQz63L97nirJL7XnTA6:-NQz63L97nirJL7XnTA7:b-vcl3wo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2fae03cfc33e4f6a69b3edef305438227661bd3/pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx#L814)):*
> ```XML
>   const badges = Object.keys(filters).map(filter => {
>     if (
>       filters[filter] != null &&
> ```

Not a big deal, but I see we do this check in `calculateActiveFilters` in the statements page as well, except it returns the _number_ of active filters. 

Maybe we could extend that to return the filters that are active, and in places that need the number we return the length?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dongniwang and @THardy98)

___
*[`pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx` line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98988#-NQz63L97nirJL7XnTA6:-NQzOlpY4Iy6cF5w6L_0:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2fae03cfc33e4f6a69b3edef305438227661bd3/pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx#L814)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Not a big deal, but I see we do this check in `calculateActiveFilters` in the statements page as well, except it returns the number of active filters. 

Maybe we could extend that to return the filters that are active, and in places that need the number we return the length?

</blockquote></details>

Done

**Review by THardy98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98988#-:-NQzR4XpA4J28L2X8vBc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dongniwang)

**Comment by dongniwang** [comment]
LGTM! Thanks for the quick turnaround!

**Review by dongniwang — APPROVED** [review]
LGTM!

**Comment by maryliag** [comment]
TFTR!
bors r+

**Pull request merged**
