### PR TITLE
allocator: better domain for lease transfers

### LINKED ISSUE #93258: allocator: take lease preferences into account for lease convergence
When load-based lease rebalancing is disabled, the allocator falls back to rebalancing leases by count. It does this by calculating the mean lease count across the cluster, and then transfer a lease from a node with `leases > mean` to one with `leases < mean`. However, this does not take lease preferences into account, and the mean calculation will include the 0 lease counts from nodes that are not within the lease preferences.

Consider an example with three nodes in each of `asia`, `eu`, `us`, and a lease preference set to us:

* `asia1`: 0
* `asia2`: 0
* `asia3`: 0
* `eu1`: 0
* `eu2`: 0
* `eu3`: 0
* `us1`: 133
* `us2`: 133
* `us3`: 33

In this case, the operator might expect the leases to rebalance such that all `us` nodes have ~100 leases each, but this won't happen. `us3` will be stuck at 33 leases, because the average lease count is 300 / 9 = 33 and it's therefore right at the mean and thus not considered underfull.

The lease convergence calculation needs to take lease preferences into account for this calculation, as well as which preferences can actually be satisfied (e.g. in the case of unavailable nodes/regions).

This determination is made here:

https://github.com/cockroachdb/cockroach/blob/d4a2c743e02c82a903fdbac782f1d5df5e8c33a1/pkg/kv/kvserver/allocator.go#L2170-L2186

Based on the lease candidate store mean which is calculated here:

https://github.com/cockroachdb/cockroach/blob/0f816899cd3e8605b3d8955967a8956b4cf15fb9/pkg/kv/kvserver/store_pool.go#L778

### LINKED ISSUE #98870: allocator: domain store list is constructed using all stores passed in
`bestStoreToMinimizeDelta` selects a store to move load to from the given existing store. The candidate store list it receives is filtered to only be valid, equally diverse and constraint matching replacements. 

https://github.com/cockroachdb/cockroach/blob/0495342e81d473901278993f6162b1d78b685bc1/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L1187-L1187

The domain is constructed to be candidates+existing and is used for calculating the mean load value. The mean load value then determines if the max load thresholds. The max load threshold is used to possibly return early if the existing store isn't above that threshold. The result is, if the mean is incorrectly using a different domain than the candidates+existing, `bestStoreToMinimizeLoad` may erroneously return `existingNotOverfull` and no rebalance target.

The domain store list is not constructed using the domain currently, instead it uses the `storeDescMap` which doesn't guarantee to only include the domain stores (lease transfers don't). This is causing the above issue.

https://github.com/cockroachdb/cockroach/blob/0495342e81d473901278993f6162b1d78b685bc1/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L1218-L1223

### PR DESCRIPTION
**Pull request by kvoli**
Previously, the allocator would not take into account lease preferences
when calculating the mean load or leases. This was problematic,
especially as lease counts were balanced, assuming that all stores are
equally preferred for leases, when they are not.

This problem affected both lease count and load convergence based lease
transfers. For lease count based transfers, the average lease count of
comparable stores should be balanced within some threshold. For load
convergence, it is the same but for load, either QPS or CPU.

For load convergence, this commit updates the store list creation so
that only comparable stores are included in the mean calculation. The
comments in `bestStoreToMinimizeDelta` are also updated to be more
accurate.

For lease count, this commit filters the store list used in calculating
the mean, to only preferred stores, if at least one preferred store
exists and overlaps with the valid transfer targets. If there are no
preferred stores or no preferred stores which overlap with the valid
transfer targets, the unfiltered storelist is used like before.

Resolves: https://github.com/cockroachdb/cockroach/issues/98870
Resolves: https://github.com/cockroachdb/cockroach/issues/93258

Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
I'm not that happy with the approach, it would be better to use the stores filtered on replica constraints (as it was using previously) and also lease preferences.

The other validity checks should filter candidates down but not the domain we are minimizing max-min over.

This patch just uses the candidate set which isn't perfect.

I think I'll split out the useful comment changes and the domain changes. I'll also remove the GA blocker on domain issue, given its been like this for a couple releases.

**Comment by kvoli** [comment]
> I'm not that happy with the approach, it would be better to use the stores filtered on replica constraints (as it was using previously) and also lease preferences.

I updated to do this instead.

**Comment by kvoli** [comment]
@nvanbenschoten @andrewbaptist ptal at the changes and whether this is something we should backport to 23.1 or not.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98893#-NV5dXX21u1RcXYZY0kq:-NV5dXX30yBuOWTG5PM4:b-ax7qh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85797edd84837c04b069ff2936a95b718d7c566/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2255)):*
> ```Go
> 	sl = sl.ExcludeInvalid(conf.Constraints)
> 	sl = sl.ExcludeInvalid(conf.VoterConstraints)
> 	preferredSL := sl.ExcludeNonPreferred(conf.LeasePreferences)
> ```

question about `SpanConfig.LeasePreferences` semantics: is each `LeasePreference` conjunction meant to be stand-alone in that if we compute the set of stores in the cluster that satisfy that, we have the full set that could be the leaseholder. Or do we need intersect the conjunctions in each `LeasePreference` with each of the conjunctions in `Constraints` or `VoterConstraints`, and then union the set of stores? The latter is more complicated but not too bad for allocator2 given that we have a `constraintsDisj`.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98893#-NV5dXX21u1RcXYZY0kq:-NV69o6z-un7bmS8zF5c:b-bzsb22) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85797edd84837c04b069ff2936a95b718d7c566/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2255)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

question about `SpanConfig.LeasePreferences` semantics: is each `LeasePreference` conjunction meant to be stand-alone in that if we compute the set of stores in the cluster that satisfy that, we have the full set that could be the leaseholder. Or do we need intersect the conjunctions in each `LeasePreference` with each of the conjunctions in `Constraints` or `VoterConstraints`, and then union the set of stores? The latter is more complicated but not too bad for allocator2 given that we have a `constraintsDisj`.
</blockquote></details>

I think something like the latter is occurring in this PR and was so originally. I don't actually know the original intended semantics.

We intersect the `Constraints` and `VoterConstraints`, then take the first non-empty intersection between that resulting store list and preference conjunction in `LeasePreferences`.  The preferences conjunctions are ordered, see comment on `ExcludeNonPreferred`:

	// Go one preference at a time. As soon as we've found stores that match a
	// preference, we don't need to look at the later preferences, because
	// they're meant to be ordered by priority.

This becomes the domain for means, however the action space is limited to transferring to an existing voting replica, we don't try and rebalance replicas to satisfy a lease preference.


For `allocator2` I'm not sure what would be best here. Could we only do the former if we assume every store in the set can actually be selected and isn't just used for calculating the loadSummary?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98893#-NV5dXX21u1RcXYZY0kq:-NVBIlQHB80HyzBeiAi8:b-uxv9sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85797edd84837c04b069ff2936a95b718d7c566/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2255)):*
Say 3 constraint conjunctions in `Constraints`, c1, c2, c3, so we have `c1 or c2 or c3`
And 2 constraint conjunctions in `VoterConstraints`, vc1, vc2, so we have `vc1 or vc2`
So the intersection of these two:
```
(c1 and vc1) or (c1 and vc2) or (c2 and vc1) or (c2 and vc2) or (c3 and vc1) or (c3 and vc2)
```
which can be simplified to
```
c4 or c5 or c6 or c7 or c8 or c9
```
And then we have lease preferences as an ordered sequence of conjunctions lp1, lp2, ...
That we can intersect
```
(c4 and lp1) or (c5 and lp1) or (c6 and lp1) or (c7 and lp1) or (c8 and lp1) or (c9 and lp1)
```
which can be represented as a `constraintsDisj` so we can use it for mean calculation.

> however the action space is limited to transferring to an existing voting replica, we don't try and rebalance replicas to satisfy a lease preference.

Good to know

> For `allocator2` I'm not sure what would be best here. Could we only do the former if we assume every store in the set can actually be selected and isn't just used for calculating the loadSummary?

What is meant by "only do the former"?

**Comment by kvoli** [comment]
Closing for now, the patch is stale and likely to be superseded by a wider scoped project.

**Pull request closed without merging**
