### PR TITLE
opt: extend SplitScanIntoUnionScans to handle longer keys

### LINKED ISSUE #55156: opt: extend SplitScanIntoUnionScans to support splitting a constraint with multi-key spans
I have this table

```
CREATE TABLE IF NOT EXISTS  user_checklist_items (
    tenant_id UUID,
    location_id UUID,
    checklist_item_id UUID,
    user_id STRING,
    configuration_maintenance_id UUID NOT NULL,
    configuration_maintenance_item_id UUID NOT NULL,
    date_should_be_completed DATE NOT NULL,
    is_recurrent_assignation BOOL,
    location_name STRING NOT NULL,
    order_item FLOAT NOT NULL,
    title STRING NOT NULL,
    create_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (tenant_id, location_id, checklist_item_id, user_id)
) INTERLEAVE IN PARENT tenants (tenant_id);

CREATE INDEX IF NOT EXISTS userchecklistitems_tenantid_userid_dateshouldbecompleted_locationname_orderitem ON user_checklist_items (tenant_id, user_id, date_should_be_completed, location_name, title, order_item, checklist_item_id) USING HASH WITH BUCKET_COUNT = 8;
CREATE INDEX IF NOT EXISTS userchecklistitems_tenantid_locationid_configurationmaintenanceid_configurationmaintenanceitemid_dateshouldbecompleted ON user_checklist_items (tenant_id, location_id, configuration_maintenance_id, configuration_maintenance_item_id, date_should_be_completed) USING HASH WITH BUCKET_COUNT = 8;
```

The secondary indexes are using a hash shard index because they are sequentially.

If I run this query:
```
select tenant_id, user_id, date_should_be_completed
from user_checklist_items@userchecklistitems_tenantid_userid_dateshouldbecompleted_locationname_orderitem
where 
tenant_id = 'a2a0dd49-23cf-4cf2-b823-61701c416e60' and
user_id = '01603523-c6f0-4e12-a43f-524c76b0fa8f' and 
date_should_be_completed >= '2020-10-01'
order by index user_checklist_items@userchecklistitems_tenantid_userid_dateshouldbecompleted_locationname_orderitem
limit 5
```
keyset pagination works, it´s limmiting the scan to just 5 records, but data is not ordered by the "date_should_be_completed" field, as the index indicates. (I guess due to the hash function to distribute load)

Screen Shot 2020-10-02 at 0 50 33

Screen Shot 2020-10-02 at 0 52 01

If I run this other query
```
select tenant_id, user_id, date_should_be_completed
from user_checklist_items@userchecklistitems_tenantid_userid_dateshouldbecompleted_locationname_orderitem
where 
tenant_id = 'a2a0dd49-23cf-4cf2-b823-61701c416e60' and
user_id = '01603523-c6f0-4e12-a43f-524c76b0fa8f' and 
date_should_be_completed >= '2020-10-01'
order by date_should_be_completed
limit 5
```
The query works, but it´s running a scan to the entire table (in this example, i´m just showing a table which contains 365 records), and after the scan is completed, it´s limiting to 5 records, which is not efficient although all the fields are indexed.

Screen Shot 2020-10-02 at 0 53 16

Screen Shot 2020-10-02 at 0 54 05

Is it possible to run a keyset pagination using a hash shard index?

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, `SplitScanIntoUnionScans` only handled Scan constraints
where all the start and end keys of the spans were of the exact same
length `keyLength`, and the first `keyLength` columns of the index
formed a prefix for the limit ordering columns. The following is an
example of a case that can be handled under these conditions:
```
/1/2/3: [/US_WEST/0 - /US_WEST/1]
=>
/1/2/3: [/US_WEST/0 - /US_WEST/0], [/US_WEST/1 - /US_WEST/1]
keyLength: 2
limit ordering: +3
```
However, a case like this one could not be handled, even though
the transformation shown is a valid (and desirable) one:
```
/1/2/3: [/US_WEST/0/postfix - /US_WEST/1]
=>
/1/2/3: [/US_WEST/0/postfix - /US_WEST/0], [/US_WEST/1 - /US_WEST/1]
keyLength: -
limit ordering: +3
```
This patch extends `SplitScanIntoUnionScans` to handle cases like the
above. This is accomplished by modifying the `keyCount()` and `span.split()`
code to require a prefix length as input. Examples:
```
[/ASIA/0/postfix - /ASIA/4].keyCount(prefixLength=1) = 1
[/ASIA/0/postfix - /ASIA/4].keyCount(prefixLength=2) = 5
[/ASIA/0/postfix - /ASIA/4].keyCount(prefixLength=3) = undefined
```
In this case, the prefix length used is the number of index columns that
precede the limit ordering columns (which must either be in order or in
reverse order):
```
index: /1/2/-3/4
limit ordering: /3/-4
prefix length: 2
```
In addition, `SplitScanIntoUnionScans` can now support cases where one span
from the Scan's constraint can be split and used to generate limited Scans,
but the other cannot.

Fixes #55156

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
Welcome back, @drewkimball!

This is great! :lgtm: 

In the PR/commit message, you say that the following transformation is valid:
```
/1/2/3: [/US_WEST/0/postfix - /US_WEST/1]
=>
/1/2/3: [/US_WEST/0/postfix - /US_WEST/0], [/US_WEST/1/postfix - /US_WEST/1]
```
I'm not sure that's technically correct, since the first constraint contains more keys than the second one. 

But looking at the code and comments, it looks like you would actually perform this transformation:
```
/1/2/3: [/US_WEST/0/postfix - /US_WEST/1]
=>
/1/2/3: [/US_WEST/0/postfix - /US_WEST/0], [/US_WEST/1 - /US_WEST/1]
```
So maybe you just need to update the PR/commit message?

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58085#-:-MP4kbLe2ijVWEJF75-Z:baqo16p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/constraint/span.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58085#-MP4mtZx3Tl_LZoXdPCb:-MP4mtZx3Tl_LZoXdPCc:b3ussba) ([raw file](https://github.com/cockroachdb/cockroach/blob/44da2a04dfa1fe41ece89c23f5887db6a2f4e9c4/pkg/sql/opt/constraint/span.go#L335)):*
> ```Go
> // removed:
> //
> //    ['ASIA'/1 - /'ASIA'/2]/KeyCount(keyCtx, length=2) => 2, true
> ```

[nit] /KeyCount -> .KeyCount
___
*[pkg/sql/opt/xform/limit_funcs.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58085#-MP4r1Yu9mbkeQUNoYC8:-MP4r1YvD_UcYlaDL0db:b-ap4384) ([raw file](https://github.com/cockroachdb/cockroach/blob/44da2a04dfa1fe41ece89c23f5887db6a2f4e9c4/pkg/sql/opt/xform/limit_funcs.go#L162)):*
> ```Go
> 
> // SplitScanIntoUnionScans returns a Union of Scan operators with hard limits
> // that each Scan over a single key from the original scan's constraints. This
> ```

[nit] each Scan -> each scan ... original scan's -> original Scan's

**Review by DrewKimball — COMMENTED** [review]
Thanks @rytaft, it's good to be (sort of) back. And you're right, I'll change the commit message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58085#-:-MP7VNao1-kuUcf7ly5p:b-j9o654)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/constraint/span.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58085#-MP4mtZx3Tl_LZoXdPCb:-MP7VfwABmv10_2xJnyT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44da2a04dfa1fe41ece89c23f5887db6a2f4e9c4/pkg/sql/opt/constraint/span.go#L335)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] /KeyCount -> .KeyCount
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/limit_funcs.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58085#-MP4r1Yu9mbkeQUNoYC8:-MP7W5yh6ZqlaJoYcc0w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44da2a04dfa1fe41ece89c23f5887db6a2f4e9c4/pkg/sql/opt/xform/limit_funcs.go#L162)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] each Scan -> each scan ... original scan's -> original Scan's
</blockquote></details>

Done.

**Comment by DrewKimball** [comment]
TFTR!

**Review by rytaft — APPROVED** [review]
:lgtm: 

[super nit] in the commit/PR message you're using +3 for the ordering at the top, and /3 for the ordering further down

Also, don't forget to update the PR message to include the fixes you made to the commit message!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58085#-:-MP9cIpu9XgRF4b_z_Vx:bhx92b1)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
I tried the example in #55156 with this change, but I see no change. Here's the execbuilder test I used: https://gist.github.com/RaduBerinde/0a5286cc3352944726ee588ba7650fc5

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58085#-:-MPHC9MB8xbZ6k2dnbBM:b9kboc0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by RaduBerinde — APPROVED** [review]
In this case, we don't even need to split any of the spans.. We just need to separate them in their own scans, so that each can be limited.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58085#-:-MPHClPi2GLs2kmDD239:b-qi1jqo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by DrewKimball** [comment]
@RaduBerinde that's because the logic at line 233 in limit_funcs prevents the plan from being generated when the new plan isn't expected to decrease the number of rows scanned by a decent margin. Do you think we should be generating the plan in this case?

If you just want to see the plan being generated from those constraints, you can just increase the rowcount of the table.

**Comment by RaduBerinde** [comment]
Ah, that's great! Could you add an execbuilder or xform test with the case from the issue? You can inject stats as needed.

**Comment by DrewKimball** [comment]
@RaduBerinde any chance you could bors this? I'm just an external contributor right now:)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58085)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[pkg/sql/opt/exec/execbuilder/testdata/limit, line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58085#-MPfFT0C6Pk5hLR-YkmV:-MPfFT0C6Pk5hLR-YkmW:bswx1uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2795425d69127190eb86c0f308ef63567f8ab677/pkg/sql/opt/exec/execbuilder/testdata/limit#L393)):*
> ```
> # Expect a scan over each shard.
> query T
> EXPLAIN (OPT, VERBOSE)
> ```

[nit] Could you make this a regular EXPLAIN? (the tests are meant to cover what the execbuilder does as well)  It doesn't have to be verbose, we're just looking for some unions.

**Comment by DrewKimball** [comment]
Done.

**Comment by RaduBerinde** [comment]
Thanks!

bors r+

**Pull request merged**
