### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tamird**
Omits grpc/grpc-go#690 which "temporarily" removed the (*grpc.ClientConn).{State,WaitForStateChange} APIs.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7066)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by knz** [comment]
LGTM

**Comment by tamird** [comment]
Holding off on this until @mberhault figures out what's up with jemalloc on OS X.

**Comment by mberhault** [comment]
ok. so it turns out the sample dump part works fine on OSX. What's broken is the list of mapped libraries. Currently, jemalloc tries to get it from `/proc/<pid>/maps` which obviously doesn't exist on OSX.
It still writes the samples properly. The reason they were still empty for a while is that you need enough activity for sampling (or run something like the block_writer). There's still a massive discrepancy between RSS and "go active + jemalloc allocated", but that's a separate issue.

**Pull request merged**
