### PR TITLE
opt: Remove ability to control mutation ordering

### PR DESCRIPTION
**Pull request by andy-kimball**
Currently, INSERT and UPDATE operators inherit the ordering of their inputs,
and then apply mutations in that order. For example:

  UPDATE kv SET k = k + 1 ORDER BY k DESC

The Update operator's input query fetches rows from the kv table in the
given order, starting from the largest value of "k" and proceeding backwards.
The Update operator will apply mutations in this same order. This behavior
could be used to workaround unique key violation errors when updating keys
(e.g. updating k=1->2 before k=2->3).

However, the CBO compiles UPDATE statements in new ways that make mutation
ordering difficult to guarantee without requiring additional sort operators
to be inserted. For example:

  UPDATE kv SET k=(SELECT b FROM ab WHERE a=k) ORDER BY k DESC

The correlated subquery gets hoisted, a left-outer-join is introduced, and
other optimizations may be applied. When all is said and done, the Update
operator's input may not ordered by "k", and so it may need to be wrapped
in an extra Sort operator.

The situation is similar for INSERT...ON CONFLICT statements. While any
internal INSERT input ordering could be used as the output ordering in
simple cases, the ON CONFLICT clause introduces a new set of rows which
scrambles the ordering of the input.

Note that the ORDER BY/LIMIT syntax was added to UPDATE in order to make it
possible to limit the size of UPDATE batches, given Cockroach limits on
batch size. This is non-Postgres syntax adopted from MySql. Going forward,
we'll implement UPDATE FROM, which gives a PG-compatible way of doing the
same thing, at which point the old syntax will be deprecated. The intent of
ORDER BY was always to control batch size, and never to control output or
mutation ordering. In addition, our documentation explicitly states that
internal ORDER BY clauses (including ORDER BY on UPDATE, which is meant to
control input ordering, not output ordering) do not guarantee result
ordering:

  https://www.cockroachlabs.com/docs/v2.1/query-order.html#order-preservation

Due to these factors, we don't expect many users to be affected by this
change in behavior. However, in order to further discourage incorrect
assumptions about the effects of ORDER BY when used with UPDATE, this
commit makes it an error to use UPDATE ORDER BY without a LIMIT specified.

Release note (backwards-incompatible change): Mutation statements like
UPDATE and INSERT no longer attempt to guarantee mutation or output
ordering when an ORDER BY is present. It is now an error to use ORDER BY
without LIMIT with the UPDATE statement.

### CODE REVIEW

**Comment by knz** [comment]
maybe it's time to start a tech note in the source tree to discuss mutation semantics. I'll work on that.

**Comment by knz** [comment]
maybe change the release not prefix to `Release note (backward-incompatible change)`

**Review by bdarnell — APPROVED** [review]
(Haven't looked at the code but approving the semantic change as described)

**Review by RaduBerinde — COMMENTED** [review]
Nit: I found the description confusing because it's talking about inheriting the ordering of inputs but in the `UPDATE .. ORDER BY` example the clause is part of the UPDATE statement itself. In particular, "our documentation explicitly states that internal ORDER BY clauses do not guarantee result ordering" wouldn't apply to this statement.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33087#-:-LTcLIfTDoHFNr9qOlcf:b-8iayx8)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/ordering/insert.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33087#-LTcMAk34cA28YIQdFJz:-LTcMAk34cA28YIQdFK-:b4s7k2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ee54dee38b3a75e6f0dad94fa0b5a1e846274b/pkg/sql/opt/ordering/insert.go#L25)):*
> ```Go
> func insertCanProvideOrdering(expr memo.RelExpr, required *physical.OrderingChoice) bool {
> 	// Insert operator can always pass through ordering to its input.
> 	return true
> ```

The comment you added in optbuilder is at odds with this.. If we can't guarantee an output ordering (even if there is a matching input ordering), shouldn't this always return false?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33087#-:-LTckkkx2oddzWxJ6Agc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/ordering/insert.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33087#-LTcMAk34cA28YIQdFJz:-LTck_LwAj1XJuEX8FAz:b-2w1e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ee54dee38b3a75e6f0dad94fa0b5a1e846274b/pkg/sql/opt/ordering/insert.go#L25)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The comment you added in optbuilder is at odds with this.. If we can't guarantee an output ordering (even if there is a matching input ordering), shouldn't this always return false?
</blockquote></details>

Retracting after our offline talk, this will apply when we have UpsertOp

**Comment by andy-kimball** [comment]
I changed the release note to `backwards-incompatible change`.

**Review by andy-kimball — COMMENTED** [review]
Radu and I talked about this further. The `ORDER BY` clause is part of the `UPDATE` statement, but it is actually meant to control the _input_ to the `UPDATE` (i.e. when `LIMIT` is present), not its output. I did some rewording of the commit message to be a bit clearer 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33087#-:-LTclwsgBqnUCnlx-JC8:btd3okr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/ordering/insert.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33087#-LTcMAk34cA28YIQdFJz:-LTcrbZK8PUOCDz_5z4b:b-k2bi8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ee54dee38b3a75e6f0dad94fa0b5a1e846274b/pkg/sql/opt/ordering/insert.go#L25)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Retracting after our offline talk, this will apply when we have UpsertOp
</blockquote></details>

I added to the comment in case someone else gets confused.

**Pull request merged**
