### PR TITLE
multitenant: add tests for existing multitenant admin function behavior

### LINKED ISSUE #89947: multitenant: add tests for existing multitenant admin function behavior
Currently some admin functions do not support multitenacy and return a "operation is unsupported in multi-tenancy mode" error message. This behavior is not always covered by tests.

Create test cases for these function for documentation and to drive development towards supporting these admin functions.

Jira issue: CRDB-20508

### PR DESCRIPTION
**Pull request by ecwall**
fixes https://github.com/cockroachdb/cockroach/issues/89947

Some admin functions do not support multitenacy and return a "operation is unsupported in multi-tenancy mode" error message.

These test cases documentation the current behavior and can be used to drive development towards supporting these admin functions.

Release note: None

### CODE REVIEW

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @knz)

___
*[`pkg/sql/multitenant_admin_function_test.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEINFJd9mqJC3lzM5sr:-NEINFJd9mqJC3lzM5ss:bnh257t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L63)):*
> ```Go
> 	defer log.Scope(t).Close(t)
> 
> 	testCases := []struct {
> ```

Am I missing any functions? I plan on creating tickets based on each of the test cases here.

**Review by knz — APPROVED** [review]
:lgtm: thanks.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-:-NEKbRqk7ZFtiw3HXJHj:brfqlva)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @ecwall)

___
*[`pkg/sql/multitenant_admin_function_test.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEINFJd9mqJC3lzM5sr:-NEK_MIg4_0d66Dsa4uo:ba15466) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L63)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Am I missing any functions? I plan on creating tickets based on each of the test cases here.
</blockquote></details>

yes you are missing TRUNCATE after a SPLIT (TRUNCATE tries to preserve split points using a KV admin command). However, you will not see an error about this when it fails, it fails silently.

Also maybe some of the multi-region functionality may also use KV admin commands. Can you approach the members of the (ex)MR team to see what they think?
___
*[`pkg/sql/multitenant_admin_function_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEK_tpXC5c2M7DLhLKn:-NEK_tpXC5c2M7DLhLKo:b-qmszei) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L68)):*
> ```Go
> 	}{
> 		{
> 			desc: "ALTER RANGE x RELOCATE LEASE",
> ```

there's both a lease and a data variant. For ranges, there's also a "nonvoters" variant.
You can grep for all this in the logic tests
___
*[`pkg/sql/multitenant_admin_function_test.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEK_qpACXKPRqktJJ4u:-NEK_qpACXKPRqktJJ4v:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L75)):*
> ```Go
> 		},
> 		{
> 			desc: "ALTER TABLE x EXPERIMENTAL_RELOCATE LEASE",
> ```

ditto

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89950)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @ecwall)

___
*[`pkg/sql/multitenant_admin_function_test.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEKix1IEnTuzcmTGHaX:-NEKix1IEnTuzcmTGHaY:bxgefqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L28)):*
> ```Go
> 	t *testing.T,
> ) (systemTenant *sqlutils.SQLRunner, secondaryTenant *sqlutils.SQLRunner, cleanup func()) {
> ```

nit: remove empty line.
___
*[`pkg/sql/multitenant_admin_function_test.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEKizQM3gabQdaLBysY:-NEKizQM3gabQdaLBysZ:b-3cvobg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L97)):*
> ```Go
> 		},
> 		{
> 			// todo(ewall): support 'ALTER TABLE x SPLIT AT' first
> ```

nit: `TODO` and missing period at end of sentence.
___
*[`pkg/sql/multitenant_admin_function_test.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEKj0UT5kX08XS787f-:-NEKj0UT5kX08XS787f0:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L106)):*
> ```Go
> 		},
> 		{
> 			// todo(ewall): support 'ALTER INDEX x SPLIT AT' first
> ```

ditto
___
*[`pkg/sql/multitenant_admin_function_test.go` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEKj1ut4OG5Gtb1-B1B:-NEKj1ut4OG5Gtb1-B1C:bxgefqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L156)):*
> ```Go
> 	for _, tc := range testCases {
> 		t.Run(tc.desc, func(t *testing.T) {
> ```

nit: remove empty line.
___
*[`pkg/sql/multitenant_admin_function_test.go` line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEKj3-J6BBgqOPgIN18:-NEKj3-J6BBgqOPgIN19:bcshyd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L163)):*
> ```Go
> 			query := tc.query
> 
> 			// System tenant test
> ```

nit: here and below, missing period at end of sentence.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89950)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajstorm, and @knz)

___
*[`pkg/sql/multitenant_admin_function_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEK_tpXC5c2M7DLhLKn:-NEMYzxm-J2ZN3PLae-z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L68)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

there's both a lease and a data variant. For ranges, there's also a "nonvoters" variant.
You can grep for all this in the logic tests
</blockquote></details>

Done.
___
*[`pkg/sql/multitenant_admin_function_test.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEK_qpACXKPRqktJJ4u:-NEMZ-KC1UZaKLfEXlpu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L75)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/sql/multitenant_admin_function_test.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89950#-NEKj0UT5kX08XS787f-:-NELrjME1EqbCUKJWKXC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c5825b7c9538db8d763a403277ef54ae86cd6ed/pkg/sql/multitenant_admin_function_test.go#L106)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by ecwall** [comment]
bors r=knz

**Pull request merged**
