### PR TITLE
acceptance:nodes in acceptance tests are killed and flush their logs

### LINKED ISSUE #9220: acceptance/cluster: nodes in acceptance tests are killed brutally and don't flush their logs
`LocalTestCluster.stop()` does `ContainerKill(9)` to stop the docker container, which bypasses all the server's nice shutdown logic. Instead we should attempt a more graceful signal first, and SIGKILL only if the server doesn't cooperate.

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #9220.

@andreimatei @knz  help review if I have done it right.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10052)

### CODE REVIEW

**Comment by knz** [comment]
You had made a mistake in the mention to Andrei ("@ andreimate" instead of "@ andreimatei"). I fixed it.

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/cluster/localcluster.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUa_Tc8Yom-NpFAihde:-KUa_Tc8Yom-NpFAihdf:b-ifdjmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e0b1b63163bbeadce164a8caa845ba7eba70caf/pkg/acceptance/cluster/localcluster.go#L137)):*
> ```Go
> 	// (which might fail) before killing.
> 	_ = t.Container.Unpause()
> 	if err := t.Container.cluster.client.ContainerKill(context.Background(), t.Container.id, "4"); err != nil && !strings.Contains(err.Error(), "is not running") {
> ```

Can you explain a comment that value "4" means SIGQUIT.

Also the line is too long, please break it over two lines.

Also your solution is not yet complete. The problem is that SIGQUIT may not be sufficient!
The proper procedure is to:
1. use SIGQUIT a first time
2. wait for a few seconds (check how long a cockroachdb node takes to quit usually), 
3. if the process has not terminated yet, send SIGQUIT a 2nd time to initiate a hard shutdown
4. wait for a few more seconds (probably 1 or 2 is sufficient), 
5. only after that, if the process still has not terminated use SIGKILL, like Docker's Kill() method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052)*

**Comment by knz** [comment]
Also contrary to what @andreimatei said I recommend SIGINT instead of SIGQUIT. 
(@andreimatei: SIGQUIT will not do what we want: it forcefully terminates the process with a goroutine dump, and does not initiate the normal shutdown. SIGTERM or SIGINT do. But SIGINT ensures the exit status will be nonzero, because of #9051)

**Comment by knz** [comment]
@andreimatei unless you actually had a goroutine dump in mind?

**Comment by a6802739** [comment]
@knz, yeah, I had made a mistake above. thanks for you review.

I will change it according to your advice. 

thanks again.

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/cluster/localcluster.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUa_Tc8Yom-NpFAihde:-KUgOW5y3x4JDDcVsvB7:b-dtu4go) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e0b1b63163bbeadce164a8caa845ba7eba70caf/pkg/acceptance/cluster/localcluster.go#L137)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Can you explain a comment that value "4" means SIGQUIT.
> 
> Also the line is too long, please break it over two lines.
> 
> Also your solution is not yet complete. The problem is that SIGQUIT may not be sufficient!
> The proper procedure is to:
> 1. use SIGQUIT a first time
> 2. wait for a few seconds (check how long a cockroachdb node takes to quit usually), 
> 3. if the process has not terminated yet, send SIGQUIT a 2nd time to initiate a hard shutdown
> 4. wait for a few more seconds (probably 1 or 2 is sufficient), 
> 5. only after that, if the process still has not terminated use SIGKILL, like Docker's Kill() method.
</details>
Signal 4 is SIGILL, not SIGQUIT. It looks like the docker kill command accepts signal names, not just numbers (that's why it's a string) so we should definitely be using the name here to avoid confusion. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052)*

**Comment by a6802739** [comment]
*[pkg/acceptance/cluster/localcluster.go, line 163 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUq4d3iR65EshobQw5J:-KUq4d3iR65EshobQw5K:b-dx3f14) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec37bb519797cd613d54100063f884d34b4636ba/pkg/acceptance/cluster/localcluster.go#L163)):*
> ```Go
> 		}
> 		quitTimes = quitTimes + 1
> 		time.Sleep(3 * time.Second)
> ```

I test the real node quit consume about 2 second, so I use 3 * second here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052)*

**Comment by a6802739** [comment]
*[pkg/acceptance/cluster/localcluster.go, line 145 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUq5CPJRtN2kyr6gayp:-KUq5CPJRtN2kyr6gayq:b-gpi9vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec37bb519797cd613d54100063f884d34b4636ba/pkg/acceptance/cluster/localcluster.go#L145)):*
> ```Go
> 	_ = t.Container.Unpause()
> 	if err := t.Container.cluster.client.ContainerKill(context.Background(),
> 		t.Container.id, "3"); err != nil && !strings.Contains(err.Error(), "is not running") {
> ```

I will use signal string to replace here, but I quite don't use which correct signal here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052)*

**Comment by a6802739** [comment]
*[pkg/acceptance/cluster/localcluster.go, line 133 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUq5cs-1rFVZ606gUg0:-KUq5cs-1rFVZ606gUg1:b9q1ud4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec37bb519797cd613d54100063f884d34b4636ba/pkg/acceptance/cluster/localcluster.go#L133)):*
> ```Go
> 
> // Get node status.
> func (t *testNode) status() (string, error) {
> ```

I wonder if it has another way to check the node's status?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052)*

**Comment by a6802739** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/cluster/localcluster.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUa_Tc8Yom-NpFAihde:-KUu7YgWqOeZJfErhQ6b:b-nb9568) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e0b1b63163bbeadce164a8caa845ba7eba70caf/pkg/acceptance/cluster/localcluster.go#L137)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Signal 4 is SIGILL, not SIGQUIT. It looks like the docker kill command accepts signal names, not just numbers (that's why it's a string) so we should definitely be using the name here to avoid confusion. 
</details>
@knz, I have done it as what you say.Now I still use number, after we confirm which signal we'll actually use, I'll change it to string instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/cluster/localcluster.go, line 133 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUq5cs-1rFVZ606gUg0:-KUugnusZVUyZF1bDtYy:b-3jef34) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec37bb519797cd613d54100063f884d34b4636ba/pkg/acceptance/cluster/localcluster.go#L133)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> I wonder if it has another way to check the node's status?
</details>
I'm not sure either. @tamird do you have an opinion?

But if it works I'd be happy with this.

---

*[pkg/acceptance/cluster/localcluster.go, line 141 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUugSYzJRogqkSNsiYG:-KUugSZ-AKWvJyZ2PA40:b-k164dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec37bb519797cd613d54100063f884d34b4636ba/pkg/acceptance/cluster/localcluster.go#L141)):*
> ```Go
> }
> 
> // Send SIGQUIT(3) to container process.
> ```

As I explained earlier, please use SIGTERM.
SIGQUIT is something else entirely and will not perform graceful shutdown.

---

*[pkg/acceptance/cluster/localcluster.go, line 145 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUugXaQn5j3rU6AHa5A:-KUugXaRTcYJTcDurM4m:b-j9z373) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec37bb519797cd613d54100063f884d34b4636ba/pkg/acceptance/cluster/localcluster.go#L145)):*
> ```Go
> 	_ = t.Container.Unpause()
> 	if err := t.Container.cluster.client.ContainerKill(context.Background(),
> 		t.Container.id, "3"); err != nil && !strings.Contains(err.Error(), "is not running") {
> ```

I think you can use the signal name here, `"SIGTERM"` or even perhaps `"TERM"` instead of `"3"`.

---

*[pkg/acceptance/cluster/localcluster.go, line 163 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUq4d3iR65EshobQw5J:-KUugskl7Zs_PtsYDXau:b-lrg61c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec37bb519797cd613d54100063f884d34b4636ba/pkg/acceptance/cluster/localcluster.go#L163)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> I test the real node quit consume about 2 second, so I use 3 * second here.
</details>
The first signal can certainly take longer to drain, depending on which test is being run. I'd recommend 5-10 seconds for the first signal.
The 2nd one must be very short, no need to wait more than 1-2 seconds.
SIGKILL at the end needs no wait, it is guaranteed to succeed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052)*

**Comment by a6802739** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/cluster/localcluster.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUa_Tc8Yom-NpFAihde:-KUv1O0u2fFaLl1khIan:bh8gkcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e0b1b63163bbeadce164a8caa845ba7eba70caf/pkg/acceptance/cluster/localcluster.go#L137)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> @knz, I have done it as what you say.Now I still use number, after we confirm which signal we'll actually use, I'll change it to string instead.
</details>
maybe, we should change all the signal number to signal string in another issue.

---

*[pkg/acceptance/cluster/localcluster.go, line 145 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUugXaQn5j3rU6AHa5A:-KUv1c5soCaSRPx9Pe1S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec37bb519797cd613d54100063f884d34b4636ba/pkg/acceptance/cluster/localcluster.go#L145)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I think you can use the signal name here, `"SIGTERM"` or even perhaps `"TERM"` instead of `"3"`.
</details>
Done.

---

*[pkg/acceptance/cluster/localcluster.go, line 163 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUq4d3iR65EshobQw5J:-KUv1giPcqwGBvXGl7EH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec37bb519797cd613d54100063f884d34b4636ba/pkg/acceptance/cluster/localcluster.go#L163)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> The first signal can certainly take longer to drain, depending on which test is being run. I'd recommend 5-10 seconds for the first signal.
> The 2nd one must be very short, no need to wait more than 1-2 seconds.
> SIGKILL at the end needs no wait, it is guaranteed to succeed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052)*

**Comment by tamird** [comment]
There is a lot of code duplication here.

---

Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/cluster/localcluster.go, line 132 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUwYC1r9P-MRnog8y2s:-KUwYC1r9P-MRnog8y2t:b9eme86) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a9b50f993d2f9edf01c34507bbbe5fcd6dd9ac/pkg/acceptance/cluster/localcluster.go#L132)):*
> ```Go
> }
> 
> // Get node's status.
> ```

By the way, why are all these methods on the `testNode`? Seems more appropriate to put them on `Container`.

---

*[pkg/acceptance/cluster/localcluster.go, line 134 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUwXYIPKhTCQVk4rLZA:-KUwXYIPKhTCQVk4rLZB:b-i4ilt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a9b50f993d2f9edf01c34507bbbe5fcd6dd9ac/pkg/acceptance/cluster/localcluster.go#L134)):*
> ```Go
> // Get node's status.
> func (t *testNode) status() (string, error) {
> 	s, err := t.Container.cluster.client.ContainerInspect(context.Background(), t.Container.id)
> ```

`s, err : = t.Inspect()`

---

*[pkg/acceptance/cluster/localcluster.go, line 142 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUwXtcu4o38oFLS6zYf:-KUwXtcu4o38oFLS6zYg:bb5k04i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a9b50f993d2f9edf01c34507bbbe5fcd6dd9ac/pkg/acceptance/cluster/localcluster.go#L142)):*
> ```Go
> 
> // Send SIGTERM to container process.
> func (t *testNode) quit() error {
> ```

instead of this new method, you should make `(*Container).Kill()` take the signal as an argument.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-:-KUwYLfUQK-RPbYtcQ-y:bkh95en)*

**Comment by a6802739** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/cluster/localcluster.go, line 134 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUwXYIPKhTCQVk4rLZA:-KV4Mrz1Tf4sNOiojRbU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a9b50f993d2f9edf01c34507bbbe5fcd6dd9ac/pkg/acceptance/cluster/localcluster.go#L134)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `s, err : = t.Inspect()`
</details>
Done.

---

*[pkg/acceptance/cluster/localcluster.go, line 142 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUwXtcu4o38oFLS6zYf:-KV4MuultTKTnaOe1yq3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a9b50f993d2f9edf01c34507bbbe5fcd6dd9ac/pkg/acceptance/cluster/localcluster.go#L142)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> instead of this new method, you should make `(*Container).Kill()` take the signal as an argument.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052)*

**Comment by knz** [comment]
Reviewed 1 of 2 files at r4.
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/cluster/localcluster.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-KUa_Tc8Yom-NpFAihde:-KV4NkrlUgQBDs58owZM:b-ahzrhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e0b1b63163bbeadce164a8caa845ba7eba70caf/pkg/acceptance/cluster/localcluster.go#L137)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> maybe, we should change all the signal number to signal string in another issue.
</details>
This looks better, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052)*

**Comment by knz** [comment]
Please investigate the CI failures and see what you can do about them.

**Comment by a6802739** [comment]
@knz , it seem it failed in test `TestDockerReadWriteForwardReferenceVersion`.
```
goroutine 1377 [select]:
net/http.(*persistConn).roundTrip(0xc42000bc00, 0xc42030b860, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1840 +0x93b
net/http.(*Transport).RoundTrip(0xc420396d20, 0xc4203963c0, 0xc420396d20, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:380 +0x4ee
net/http.send(0xc4203963c0, 0x1a84ce0, 0xc420396d20, 0x0, 0x0, 0x0, 0x8, 0xc420352128, 0x5d2428)
    /usr/local/go/src/net/http/client.go:256 +0x15f
net/http.(*Client).send(0xc4201bac90, 0xc4203963c0, 0x0, 0x0, 0x0, 0xc420352128, 0x0, 0x1)
    /usr/local/go/src/net/http/client.go:146 +0x102
net/http.(*Client).doFollowingRedirects(0xc4201bac90, 0xc4203963c0, 0x1378220, 0x4, 0xc420646501, 0x5cfb8f)
    /usr/local/go/src/net/http/client.go:528 +0x5e5
net/http.(*Client).Do(0xc4201bac90, 0xc4203963c0, 0xc4204e40c0, 0xc4203963c0, 0xc4204e40c0)
    /usr/local/go/src/net/http/client.go:187 +0x11d
golang.org/x/net/context/ctxhttp.Do(0x7f73e479b078, 0xc4204e40c0, 0xc4201bac90, 0xc4203962d0, 0xa, 0x0, 0x1a827e0)
    /go/src/golang.org/x/net/context/ctxhttp/ctxhttp.go:30 +0x92
github.com/docker/docker/client.(*Client).sendClientRequest(0xc420410a10, 0x7f73e479b078, 0xc4204e40c0, 0x12e3cd8, 0x4, 0xc4204e4120, 0x51, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/docker/docker/client/request.go:110 +0x1a9
github.com/docker/docker/client.(*Client).sendRequest(0xc420410a10, 0x7f73e479b078, 0xc4204e40c0, 0x12e3cd8, 0x4, 0xc4204e4120, 0x51, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/docker/docker/client/request.go:78 +0xf1
github.com/docker/docker/client.(*Client).post(0xc420410a10, 0x7f73e479b078, 0xc4204e40c0, 0xc4204e4120, 0x51, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/docker/docker/client/request.go:41 +0xbd
github.com/docker/docker/client.(*Client).ContainerWait(0xc420410a10, 0x7f73e479b078, 0xc4204e40c0, 0xc4204d4800, 0x40, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/client/container_wait.go:14 +0x107
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.retryingDockerClient.ContainerWait.func1(0x7f73e479b078, 0xc4204e40c0, 0x2540be400, 0x7f73e479b078)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/docker.go:460 +0x6b
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.retry(0x7f73e47eb208, 0xc420014550, 0xa, 0x2540be400, 0x12ed857, 0xd, 0x12e33c6, 0x2, 0xc420646c70, 0x5ce54f, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/docker.go:393 +0x92
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.retryingDockerClient.ContainerWait(0x1aa0d20, 0xc420410a10, 0xa, 0x2540be400, 0x7f73e47eb208, 0xc420014550, 0xc4204d4800, 0x40, 0x1233620, 0x1aa0d00, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/docker.go:463 +0x11f
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*retryingDockerClient).ContainerWait(0xc420572820, 0x7f73e47eb208, 0xc420014550, 0xc4204d4800, 0x40, 0x0, 0x0, 0x0)
    <autogenerated>:276 +0x9f
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*Container).Wait(0xc420272570, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/docker.go:231 +0xa7
github.com/cockroachdb/cockroach/pkg/acceptance/cluster.(*LocalCluster).OneShot(0xc42000bb00, 0x130435b, 0x27, 0x12ea700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/cluster/localcluster.go:284 +0x27d
github.com/cockroachdb/cockroach/pkg/acceptance.testDocker(0xc4205e8180, 0x0, 0x12ea778, 0x9, 0xc4201babd0, 0x3, 0x3, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/util_test.go:430 +0x56d
github.com/cockroachdb/cockroach/pkg/acceptance.testDockerOneShot(0xc4205e8180, 0x12ea778, 0x9, 0xc4201babd0, 0x3, 0x3, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/util_test.go:438 +0x68
github.com/cockroachdb/cockroach/pkg/acceptance.runReferenceTestWithScript(0xc4205e8180, 0xc42060ec00, 0xb9c)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/reference_test.go:31 +0x156
github.com/cockroachdb/cockroach/pkg/acceptance.runReadWriteReferenceTest(0xc4205e8180, 0x12f7f3e, 0x19, 0x13215b6, 0x19d)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/reference_test.go:92 +0x194
github.com/cockroachdb/cockroach/pkg/acceptance.TestDockerReadWriteForwardReferenceVersion(0xc4205e8180)
    /go/src/github.com/cockroachdb/cockroach/pkg/acceptance/reference_test.go:127 +0x55
testing.tRunner(0xc4205e8180, 0x13757f0)
    /usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:646 +0x2ec
```

But I didn't change any code in `TestDockerReadWriteForwardReferenceVersion`.

**Comment by knz** [comment]
I see here: https://teamcity.cockroachdb.com/viewLog.html?buildId=37810&buildTypeId=Cockroach_UnitTests

that the failure is a timeout in `TestDockerRuby`. It looks like the container is not terminating properly. Please check whether the new logic you have implemented is involved in this failure.

**Comment by a6802739** [comment]
@knz , thanks, I'll check it carefully.

**Comment by a6802739** [comment]
@knz , I change the timeout parameter in `pkg/acceptance/run.sh` from `10m` to `15m`, but when I see teamcity failed info, it's still `panic: test timed out after 10m0s`. it seems the parameter doesn't take effect.
  
I test it in my local machine, and execute the command `make acceptance TESTFLAGS="-l=logs -nodes=3"`, and it pass all the test.

```
root@st01-dba-sz-cr00.st01:~/cockroachdb/src/github.com/cockroachdb/cockroach$ make acceptance TESTFLAGS="-l=logs -nodes=3"
GOPATH set to /go
/go/bin added to PATH
go install -v -tags clockoffset
+ go test -tags acceptance ./pkg/acceptance -run . -timeout 15m -l=logs -nodes=3
ok  	github.com/cockroachdb/cockroach/pkg/acceptance	879.081s
```

**Comment by andreimatei** [comment]
Summarizing the discussion from Gitter - this change takes overall acceptance tests running time from ~400s to ~900s, so it's worth investigating why that happens.

Some pointers: you can read an old RFC about the process here: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/drain_modes.md

This is where the server starts draining:
https://github.com/cockroachdb/cockroach/blob/a1e027a/pkg/server/server.go#L707
You'll see that it first uses `DrainMode_CLIENT`, which makes the server stop accepting new SQL client connections, and then waits 10s for all existing SQL connections to be closed:
https://github.com/cockroachdb/cockroach/blob/a1e027a5f55c16e3d63a0789fca8392026b4dad8/pkg/sql/pgwire/server.go#L187
I think deciding if this waiting is a good thing or not is a whole discussion (also see #6295). But for the purposes of the current PR, I think we should see if this waiting is responsible for some of the time wasted. If it is, why is that? Are the connections that tests open really not closed? A few acceptance tests I've looked at seem to call `db.Close()`, so they do want to close their connections... But maybe they do that *after* shutting down the servers? Or maybe that metric that the server looks at to see when all connections have been closed is simply broken?

Then, the server uses `DrainMode_LEASES` to drain the "range leases":
https://github.com/cockroachdb/cockroach/blob/a1e027a5f55c16e3d63a0789fca8392026b4dad8/pkg/server/node.go#L390
This waits for ~ a lease duration (9s?) for all the node's leases to go away. This is useful so that we minimize the disruption of a node shutting down within a cluster. But in the case of acceptance tests shutting down, when the whole cluster is shutting down, we don't care about this disruption. So if you can indeed verify that this waiting is responsible for (part or all of) the wait, then I'd recommend we add an environment variable that makes the server skip this waiting. Maybe the flag could control which of the "drain modes" (`LEASES, CLIENT`) are used. And then the acceptance test would set this flag to skip the `LEASES` stage.

Does this make sense? Happy to answer more questions.

---

Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-:-KVSrQMOiS3utRwKRELF:b-7lfukw)*

**Comment by bdarnell** [comment]
Alternatively, we could address this by introducing a signal handler to flush the logs (many programs do this on either SIGHUP or SIGUSR1) and then we could kill the server with SIGKILL without the full draining process. 

---

Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-:-KVUajkf2EGtVaPnPw7_:b-6w1nt7)*

**Comment by petermattis** [comment]
Or we could have acceptance tests pass `--logtostderr` to cockroach nodes. This is what I do for the `zerosum` and `allocsim` tools which start up local clusters without using docker. In addition to not having to worry about flushing the log, this also makes log writes visible immediately instead of when the log is flushed some time later. 

---

Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-:-KVUs7PRFCNNAiz0QksO:b-omcza3)*

**Comment by andreimatei** [comment]
I think we already pass `--alsologtostderr` to the nodes. I guess changing it to `--logtostderr` would be good because then the `stderr` would be the only file created and there wouldn't be confusion with the `.INFO`, `.WARNING`, etc? But on the other hand, we'd lose the separation of the log levels we get with those files...
But anyway, regardless of the log flushing issue, I think we want to shut down these nodes cleanly, out of principle. If a test gets a node in a state where it can't be shut down cleanly, then we'd like to know, right? You can argue that above I'm suggesting introducing a hack that would make the "clean shutdown" not that clean, but still...

---

Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-:-KVVOQQr1BKAsQHXIkpw:b-gpfoyd)*

**Comment by petermattis** [comment]
I don't find the separation of log levels useful in the acceptance test logs. Yes, we should be testing clean shut down of clusters, but I don't think we should be making clean shut down the solution to the problem of ensuring logs are flushed for acceptance tests. 

---

Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10052#-:-KVWcvlyZIeCcZHhrnLn:b-v8k276)*

**Comment by knz** [comment]
We have made numerous other refactorings that have alleviated the original issue somewhat. I am going to close this for now. Feel free to raise the issue again if you wish.

**Pull request closed without merging**
