### PR TITLE
gc: separate out lock table scan in the gc queue

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, we'd handle resolving intents while scanning through the
MVCC keyspace if we came across one. We would resolve it if it was
older than some configurable threshold. In all this, we never needed
to scan the lock table keyspace directly.

We're introducing replicated shared and exclusive locks. The GC queue
is expected to resolve extant replicated locks, and as such, needs to
concern itself with an explicit lock table scan. This patch removes
intent handling from the scan of the MVCC keyspace. For now, no behavior
changes -- we only look for and resolve intents. In a future patch we'll
extend this behavior to include shareed and exclusive replicated locks.

While here, we also modify an exsiting test
(`TestIntentAgeThresholdSetting`) to include an intent on a range local
key. I've ensured that the test fails if we were to only scan the lock
table corresponding to the global keyspace of a range.

Informs https://github.com/cockroachdb/cockroach/issues/111215

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
Thanks for  helping me debug this thing earlier today @nvanbenschoten. This should be good for a look now!

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111275#-NfNiMXn6wQTZb8J0qQW):*
"shared"
___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111275#-NfNiOA44rlFIH9r6D_M):*
"existing"
___
*[`pkg/kv/kvserver/gc/gc.go` line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111275#-NfNjGzD9v0D-zX62gir:-NfNjGzD9v0D-zX62gis:b4g091s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eda823d356e5797ccc7fb29cc60cf3bd8661dc7/pkg/kv/kvserver/gc/gc.go#L601)):*
> ```Go
> 	}
> 
> 	// We want to find/resolve replicated locks in over both local and global
> ```

"in over"
___
*[`pkg/kv/kvserver/gc/gc.go` line 603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111275#-NfNjJl83Z4_jjq2Sf-E:-NfNjJl83Z4_jjq2Sf-F:bdjcdor) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eda823d356e5797ccc7fb29cc60cf3bd8661dc7/pkg/kv/kvserver/gc/gc.go#L603)):*
> ```Go
> 	// We want to find/resolve replicated locks in over both local and global
> 	// keys.
> 	var ltSpans []roachpb.Span
> ```

We should use `rditer.Select` to construct these key spans. Either we can add a new `ReplicatedSpansLocksOnly` `ReplicatedSpansFilter`, or do the filtering up here.

**Review by arulajmani — COMMENTED** [review]
I prefixed the GC queue change with the `rditer.Select` commit. RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111275#-:-NfOCPrt8v5J2iCYBZeR:badcjc4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/gc/gc.go` line 603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111275#-NfNjJl83Z4_jjq2Sf-E:-NfOC6BN9eURQxeWQuke:bgpm8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eda823d356e5797ccc7fb29cc60cf3bd8661dc7/pkg/kv/kvserver/gc/gc.go#L603)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should use `rditer.Select` to construct these key spans. Either we can add a new `ReplicatedSpansLocksOnly` `ReplicatedSpansFilter`, or do the filtering up here.
</blockquote></details>

I chose to add a new `ReplicatedSpansLocksOnly` filter. That way, we don't have to duplicate any filtering logic if we ever need something like this again.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111275#-:-NfOJXiE7pUmpRE-ac1s:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/rditer/select.go` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111275#-NfOIf4M49EBzPMfIDXr:-NfOIf4M49EBzPMfIDXs:b-z2wwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0e75184780371c221558f07109aa71b420b003/pkg/kv/kvserver/rditer/select.go#L18)):*
> ```Go
> )
> 
> type ReplicatedSpansFilter int
> ```

We don't need to make a change now, but it feels like this would be better expressed as a bitset. We could then test given values in `Select` with bitwise operators. Maybe just leave a TODO for now.

**Review by arulajmani — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111275#-:-NfRK62u07irjPw-zvln:b-l0r5kv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/rditer/select.go` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111275#-NfOIf4M49EBzPMfIDXr:-NfRJqPrB_oS63QWDdUI:b-rgb0cs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0e75184780371c221558f07109aa71b420b003/pkg/kv/kvserver/rditer/select.go#L18)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We don't need to make a change now, but it feels like this would be better expressed as a bitset. We could then test given values in `Select` with bitwise operators. Maybe just leave a TODO for now.
</blockquote></details>

Added a TODO. I'm a bit lukewarm on converting this to a bitset because a lot of the fields here are mutually exclusive, which means we'll need to add some sort of validation for them. But then again, maybe there's going to be a usecase for "only user locks", in which case a bitset will come in handy.

**Pull request merged**
