### PR TITLE
pgwire: fix binary decoding of decimal NaN and NULL in arrays

### PR DESCRIPTION
**Pull request by madelynnblue**
Also enable decoding tests using the same test data from the encoding
tests. Some tests skipped because they are unimplemented or have rounding
issues.

Release note (bug fix): Fixed pgwire binary decoding of decimal NaN and
NULL in arrays.

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33295#-:-LU9m73TAP9kMlP21365:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/pgwire/encoding_test.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33295#-LU9ltA70lqh084JwFR0:-LU9ltA70lqh084JwFR1:b-iga60w) ([raw file](https://github.com/cockroachdb/cockroach/blob/25ea7e67884e8651756030504aac212cec886a75/pkg/sql/pgwire/encoding_test.go#L159)):*
> ```Go
> 					t.Skip()
> 				case *tree.DTuple, *tree.DBitArray:
> 					// Unsupported.
> ```

just curious: what happens currently if a client passes a bit array in binary?

**Comment by knz** [comment]
(this might want a backport)

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33295)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/pgwire/encoding_test.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33295#-LU9ltA70lqh084JwFR0:-LUC6lHw0yesRaYuQhAX:b-ogyzsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/25ea7e67884e8651756030504aac212cec886a75/pkg/sql/pgwire/encoding_test.go#L159)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

just curious: what happens currently if a client passes a bit array in binary?
</blockquote></details>

We return an error saying we don't support that OID. Same with tuples. A future commit may address this issue.

**Pull request merged**
