### PR TITLE
sql: skip flaky TestParallel

### PR DESCRIPTION
**Pull request by petermattis**
See #8089.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8142)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

**Comment by RaduBerinde** [comment]
Hi Peter, I was just sending out a PR that disables just the problematic multinode test.

**Comment by RaduBerinde** [comment]
PTAL #8144 instead so we don't disable the single-node test which has been enabled for a while. Sorry about not doing this earlier, I was hoping we would get the failure figured out sooner.

**Comment by RaduBerinde** [comment]
#8144 is merged.

**Pull request closed without merging**
