### PR TITLE
tracing: optimize logging into recordable, but not recording, spans

### LINKED ISSUE #16518: sql: session-based tracing performance regression
```
~/Development/go/src/github.com/cockroachdb/cockroach/pkg/sql (d290370...) benchstat out.good out.bad
name            old time/op    new time/op    delta
KV/Scan1_SQL-8     188µs ± 2%     225µs ± 0%  +20.04%  (p=0.000 n=10+9)

name            old alloc/op   new alloc/op   delta
KV/Scan1_SQL-8    28.8kB ± 0%    35.8kB ± 0%  +23.94%  (p=0.000 n=10+8)

name            old allocs/op  new allocs/op  delta
KV/Scan1_SQL-8       268 ± 0%       402 ± 0%  +50.37%  (p=0.000 n=10+10)
```

Bad is 6a369c3f40448b782cd6b047cd7915ac907a2087 (#16253). Good is d290370ac795f3efd1cc5036a003505e2f2eb43d.  I haven't investigated what is going on yet. Notice the massive increase in the number of allocations. Session-based tracing is off by default, right?

@tamird Did the new benchmark storage infrastructure catch this? Even if it didn't, this is a good example on which we should backfill some data to verify we would notice a performance regression.

### PR DESCRIPTION
**Pull request by andreimatei**
This patch removes allocations from the logging path when logging into
recordable, but not recording, spans. This is a fairly common case,
since these are the kind of spans we create as txn roots.
Before this patch, logging into these spans was a no-op, but it took as
a while and some allocations to realize that there's nothing to do. This
patch changes getSpanOrEventLog() to consider such spans the same as
instances of NoopSpans and bail early.

Fixes #16518

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/tracing/tracer_span.go, line 260 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16545#-KmhHDKLWLa380sQ_M6-:-KmhHDKLWLa380sQ_M60:b-jqm0je) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9ffe221355dfdcaa7f99c673693d7159c74d9f/pkg/util/tracing/tracer_span.go#L260)):*
> ```Go
> 
> const (
> 	// LogicalNoop means the caller is interested if the span should be considered
> ```

This stuff is overkill. Code external to `tracing` should never care about this difference. There should be a public function with a different name (`BlackHoleSpan`?) which behaves like LogicalNoop. Internally we can have an `isNoopSpan` for the other case (or we can just do the downcast directly, there's only one use in non-testing code).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16545)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/tracing/tracer_span.go, line 282 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16545#-KmhIM6NhvEG-QtmXeUT:-KmhIM6NhvEG-QtmXeUU:b4elkpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9ffe221355dfdcaa7f99c673693d7159c74d9f/pkg/util/tracing/tracer_span.go#L282)):*
> ```Go
> 		return true
> 	}
> 	if checkType == ActualNoop {
> ```

This feels like two methods: `IsNoopSpan` (as written before) and `IsLogicalNoopSpan`. That would remove the need for this conditional and the `ActualNoop` and `LogicalNoop` constants.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16545)*

**Comment by andreimatei** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/util/tracing/tracer_span.go, line 260 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16545#-KmhHDKLWLa380sQ_M6-:-KmmRPouQ03P3QhupSyV:b1hbhlo) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9ffe221355dfdcaa7f99c673693d7159c74d9f/pkg/util/tracing/tracer_span.go#L260)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This stuff is overkill. Code external to `tracing` should never care about this difference. There should be a public function with a different name (`BlackHoleSpan`?) which behaves like LogicalNoop. Internally we can have an `isNoopSpan` for the other case (or we can just do the downcast directly, there's only one use in non-testing code).
</blockquote></details>

there's more than one use in non-testing code for the noopSpan downcast (I had a bug before whereby I was sharing instances of a non-recording span between callers that had requested for a child of that span which was no bueno). But yeah, did what you suggested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16545)*

**Comment by RaduBerinde** [comment]
Great!  :lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/util/tracing/tracer_span.go, line 235 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16545#-KmmX5v9WHrxts5c3HPx:-KmmX5vA4avsekbfdH61:b-ucuk5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/deab3f451264edf5ead3e561dbcaae3de56347ff/pkg/util/tracing/tracer_span.go#L235)):*
> ```Go
> 
> // IsBlackHoleSpan returns true if events for this span are just dropped. This
> // is the case when tracing is disable and we're not recording. Tracing clients
> ```

disabled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16545#-:-KmmXCe3vonnJYvDQu6d:b-8ya197)*

**Comment by andreimatei** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/util/tracing/tracer_span.go, line 235 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16545#-KmmX5v9WHrxts5c3HPx:-Kmmb4IZkNZPC2SQBIY0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/deab3f451264edf5ead3e561dbcaae3de56347ff/pkg/util/tracing/tracer_span.go#L235)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

disabled
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16545)*

**Pull request merged**
