### PR TITLE
cluster-ui: enable terminate session / query buttons

### PR DESCRIPTION
**Pull request by matthewtodd**
Addresses #70832.

The backend endpoints to support these actions were backported to the
release-21.2 branch in cbe3347 and first released in version 21.2.2:

```
$ git tag --contains cbe3347
@cockroachlabs/cluster-ui@21.2.1
v21.2.2
v21.2.3
```

Cockroach Cloud UI code may selectively enable these buttons by setting
`pages.{sessions,sessionDetails}.showTerminateActions` in the UI Config
slice. The default is `false`, continuing to not show the buttons.

Release note (ui change): The terminate session and terminate query
buttons are again available to be enabled in the cluster ui.

### CODE REVIEW

**Review by Azhng — APPROVED** [review]
Code looks good. What's your thoughts on testing this using the RTL ? 

> Reviewed 5 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74408#-:-MsaSROi8YIVrjGy-NYE:b-85l7bh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74408#-MsaRV6d209xvU7LJmL2:-MsaRV6d209xvU7LJmL3:bpuhc0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c96cfec9ace40a1ce4b76d3c678018726ad064a7/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx#L84)):*
> ```XML
>   terminateSessionRef: React.RefObject<TerminateSessionModalRef>;
>   terminateQueryRef: React.RefObject<TerminateQueryModalRef>;
>   static defaultProps = {
> ```

TIL: `defaultProps`

**Review by maryliag — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74408)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74408#-MsaZ1Mq66y0EXEywaJJ):*
Where is this check happening?
___
*[pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74408#-MsaZnWnAJTyAeQFBpeu:-MsaZnWnAJTyAeQFBpev:bo99smu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c96cfec9ace40a1ce4b76d3c678018726ad064a7/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts#L40)):*
> ```XML
>     },
>     sessions: {
>       showTerminateActions: false,
> ```

don't we want to default case to be `true`?

**Review by matthewtodd — COMMENTED** [review]
That's a good idea, let me work something up. I originally didn't add one since we don't have any tests over this component, but now's a fine time to add some.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74408#-:-Msf3nUc3oJLlqZsHG5A:b-goloj1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74408#-MsaZ1Mq66y0EXEywaJJ):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Where is this check happening?
</blockquote></details>

Good call, I'll be more explicit in this message.
___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74408#-MsaRV6d209xvU7LJmL2:-Msf4Qn9A8GLX2JBZ92I:b3rqxql) ([raw file](https://github.com/cockroachdb/cockroach/blob/c96cfec9ace40a1ce4b76d3c678018726ad064a7/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx#L84)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

TIL: `defaultProps` 
</blockquote></details>

:magic_wand: 
___
*[pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74408#-MsaZnWnAJTyAeQFBpeu:-Msf4Xqm8xo7SXinOFKh:b1audbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c96cfec9ace40a1ce4b76d3c678018726ad064a7/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts#L40)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

don't we want to default case to be `true`?
</blockquote></details>

IIUC, these are the defaults only for the cloud side. (The self-hosted ones are in the static `defaultProps` property.) For cloud, I think `false` is a safer default, so that we can deploy this patch whether or not the cloud ui code that checks the cluster version has been deployed.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74408#-:-Msgc7kZDr4zCkzO5xpM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

**Comment by matthewtodd** [comment]
blathers backport 21.2

**Pull request merged**
