### PR TITLE
acceptance: make paths relative to repository root

### PR DESCRIPTION
**Pull request by tamird**
This makes special handling for acceptanceccl unnecessary.

### CODE REVIEW

**Comment by tamird** [comment]
Manual run with this change applied: https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&buildTypeId=Cockroach_Nightlies_RestoreTpch10&buildId=324404

**Review by cuongdo — APPROVED** [review]

**Comment by tamird** [comment]
Took a different approach; PTAL.

**Comment by cuongdo** [comment]
*[pkg/acceptance/util.go, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17651#-Kr_y4zyCG2IZRZno0CN:-Kr_y4zzHl67-fPQ-4Jl:b-5abn62) ([raw file](https://github.com/cockroachdb/cockroach/blob/b647dcddac7d3785a7314bcc2443be927646156d/pkg/acceptance/util.go#L91)):*
> ```Go
> 		panic(err)
> 	}
> 	return filepath.Join(rootPkg.Dir, "terraform", "azure")
> ```

If rootPkg.Dir contains the root of the cockroach repo, wouldn't this also need "pkg" and "acceptance?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17651)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/acceptance/util.go, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17651#-Kr_y4zyCG2IZRZno0CN:-Kra79iG4TUaJ8RrZnl3:b-y1vg5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b647dcddac7d3785a7314bcc2443be927646156d/pkg/acceptance/util.go#L91)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

If rootPkg.Dir contains the root of the cockroach repo, wouldn't this also need "pkg" and "acceptance?
</blockquote></details>

:man_facepalming: fixed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17651)*

**Review by cuongdo — APPROVED** [review]

**Pull request merged**
