### PR TITLE
clusterversion: mint the 20.1 cluster version

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
This still needs the 20.2 version start version but i'm going to do that in a separate commit (since that doesn't get backported) and want to get a green CI on this half first.

**Review by tbg — APPROVED** [review]
There's a test failure about old migrations not being removed. Just skip that test or change it to be ok with one more release.

**Comment by tbg** [comment]
If you skip it, file an issue for me please

**Comment by dt** [comment]
I edited the test to allow the extra old version and filed https://github.com/cockroachdb/cockroach/issues/47447 to do the cleanup. I'm going to go ahead  and merge this one I think and do the 20.2 version start in a separate PR actually, for a cleaner backport?

**Comment by bdarnell** [comment]
That test is really annoying. I don't like that it triggers when we're minting the final cluster version for a release; it's silly that we have to trip over this and eat extra CI cycles just as we're trying to finalize the release. Maybe the test should be tweaked to trigger on the first unstable version of the master branch instead of the stable version of the outgoing release (and we always resolve it by skipping the test instead of removing the migrations, because removing the migrations is risky at this stage)

Or this test could become a manual process run at some point during the release cycle instead of being forced as soon as the version advances to permit the deletion of the old migrations. I don't think it's important to be so aggressive about cleaning up old migrations.

**Comment by dt** [comment]
ah, i guess i hadn't had to fight with bors yet today. no space left on device this time.

bors r+

**Pull request merged**
