### PR TITLE
sql: allow ALTER TABLE DROP COLUMN to drop dependent indices.

### LINKED ISSUE #6463: sql: Can't DROP a UNIQUE column
A unique column "d" when dropped reports an error of the presence of an existing index.

statement error column "d" is referenced by existing index "t_d_key"
ALTER TABLE t DROP COLUMN d

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, `ALTER TABLE DROP COLUMN` would refuse to drop a
column if it was involved in any index, even ignoring the drop
behavior specification (`RESTRICT`/`CASCADE`).

With this patch, the following is implemented:

- if a column is not indexed, then it is dropped, as usual;
- for each index on that column:

  - if the index is defined on that column only, then it is
    automatically dropped as per `DROP INDEX` *without* `CASCADE`.
  - if the index is defined on that column and also other columns,
    then if `CASCADE` is also specified it is automatically dropped as
    per `DROP INDEX CASCADE`; otherwise an error is reported (the same
    error as before).

  In both cases when an index is dropped, the usual checks performed
  by DROP INDEX apply, and the RESTRICT/CASCADE clause on ALTER TABLE
  DROP COLUMN is propagated to the underlying DROP INDEX.

Addresses most of the concerns in  #10122 (all?)
Fixes #6463.

cc @vivekmenezes

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12782)

### CODE REVIEW

**Comment by a-robinson** [comment]
:lgtm: other than the couple questions

---

Reviewed 1 of 1 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/alter_table.go, line 223 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka3C8JA2smo0tBwUBSz:-Ka3C8JA2smo0tBwUBT-:b-vuvv75) ([raw file](https://github.com/cockroachdb/cockroach/blob/79377eca6d6851cdc06fa12066e566427ba5c26a/pkg/sql/alter_table.go#L223)):*
> ```Go
> 					containsThisColumn := false
> 					// containsOnlyThisColumn becomes false if the index also
> 					// includes non-PK columns other than the one being dropped.
> ```

Could you clarify this a little more? The non-PK restriction is only applied to the ExtraColumnIDs, not the indexed column IDs (which seems correct, but I didn't get from this comment).

Also, can you explain why we might want not want to drop an index whose only indexed column is being dropped but happens to store a non-PK column?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-:-Ka3CiWPFp05h9ExcME_:b-ldtok)*

**Comment by a-robinson** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782)*

**Comment by vivekmenezes** [comment]
Thanks for making this change.

Can you modify TestTableMutationQueue to have v be a unique column and see how it affects the mutation ids.

Thanks

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/alter_table.go, line 223 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka3C8JA2smo0tBwUBSz:-Ka3aegxcwWZ9C49RrfH:b-3gc22j) ([raw file](https://github.com/cockroachdb/cockroach/blob/79377eca6d6851cdc06fa12066e566427ba5c26a/pkg/sql/alter_table.go#L223)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Could you clarify this a little more? The non-PK restriction is only applied to the ExtraColumnIDs, not the indexed column IDs (which seems correct, but I didn't get from this comment).

Also, can you explain why we might want not want to drop an index whose only indexed column is being dropped but happens to store a non-PK column?
</blockquote></details>

I didn't follow this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-:-Ka3cZFpYz7e5XnZiVxf:bnbd0mh)*

**Comment by knz** [comment]
> @a-robinson
>     Could you clarify this a little more? The non-PK restriction is only
>     applied to the ExtraColumnIDs, not the indexed column IDs (which
>     seems correct, but I didn't get from this comment).

I have extended the comment. PTAL.

>     Also, can you explain why we might want not want to drop an index
>     whose only indexed column is being dropped but happens to store a
>     non-PK column?

Good idea! done.

> @vivekmenezes
> Can you modify TestTableMutationQueue to have v be a unique column and
> see how it affects the mutation ids.

Done.

**Comment by a-robinson** [comment]
Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/alter_table.go, line 223 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka3C8JA2smo0tBwUBSz:-Ka4ITJXoflVwxxC4GqU:b-l152a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/79377eca6d6851cdc06fa12066e566427ba5c26a/pkg/sql/alter_table.go#L223)):*
> Also, can you explain why we might want not want to drop an index whose only indexed column is being dropped but happens to store a non-PK column?

I don't see an explanation for this anywhere

---

*[pkg/sql/alter_table.go, line 225 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka4HhUC9y-JZEGXIcp3:-Ka4HhUC9y-JZEGXIcp4:bg4vo4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f19934d9fd59789d5511cdb19f31c3963a1458ba/pkg/sql/alter_table.go#L225)):*
> ```Go
> 					// INDEX i2 ON foo(a) STORING(b) -> i2 deleted
> 					// INDEX i3 ON foo(a, b) -> i3 not deleted unless CASCADE is specified.
> 					// INDEX i4 ON foo(b) STORING(a) -> i4 not deleted unless CASCADE is specified.
> ```

Did you forget to specify that one of the columns in the table is a primary key? Otherwise I'm not sure what makes i2 different from i4.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/alter_table.go, line 220 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka55b_4F7a5ilon04Yk:-Ka55b_4F7a5ilon04Yl:b-brdg7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f19934d9fd59789d5511cdb19f31c3963a1458ba/pkg/sql/alter_table.go#L220)):*
> ```Go
> 					// indexes that column":
> 					//
> 					// Assume a table created with CREATE TABLE foo (a INT, b INT).
> ```

foo (a INT PRIMARY, b INT) ?

DROP b ?

---

*[pkg/sql/descriptor_mutation_test.go, line 949 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka585ZriPfE3I9h4i3z:-Ka585ZriPfE3I9h4i4-:b-t9x5wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f19934d9fd59789d5511cdb19f31c3963a1458ba/pkg/sql/descriptor_mutation_test.go#L949)):*
> ```Go
> 		{"idx_g", 3, sqlbase.DescriptorMutation_DELETE_ONLY},
> 		// Drop mutations start off in the WRITE_ONLY state.
> 		{"test_v_key", 4, sqlbase.DescriptorMutation_WRITE_ONLY},
> ```

// UNIQUE column deletion gets split into two mutation ids.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-:-Ka58P5MRyHTS0T4NLx1:bnfp4nl)*

**Comment by knz** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/alter_table.go, line 223 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka3C8JA2smo0tBwUBSz:-Ka46cnS0Du6z7-_Tp5A:b-9ugv4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/79377eca6d6851cdc06fa12066e566427ba5c26a/pkg/sql/alter_table.go#L223)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

> Also, can you explain why we might want not want to drop an index whose only indexed column is being dropped but happens to store a non-PK column?

I don't see an explanation for this anywhere
</blockquote></details>

As I said in my previous comment, we do want to do what you say, and I changed the code accordingly. Also that's the example index i4 in the comment above.

Does this clarify?

---

*[pkg/sql/alter_table.go, line 220 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka55b_4F7a5ilon04Yk:-Ka7CNs6gg1XlVAzOhBg:b-mhayvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f19934d9fd59789d5511cdb19f31c3963a1458ba/pkg/sql/alter_table.go#L220)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

foo (a INT PRIMARY, b INT) ?

DROP b ?
</blockquote></details>

What's special about that?

---

*[pkg/sql/alter_table.go, line 225 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka4HhUC9y-JZEGXIcp3:-Ka7C5b4kDHNkWLerT-r:b-oomhuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f19934d9fd59789d5511cdb19f31c3963a1458ba/pkg/sql/alter_table.go#L225)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Did you forget to specify that one of the columns in the table is a primary key? Otherwise I'm not sure what makes i2 different from i4.
</blockquote></details>

Sorry I forgot to indicate that the example uses DROP on column "a". Fixed that in comment.
(i2 is indexing "a", whereas i4 is indexing "b". A drop on "a" will not drop i4 which is *not* an index on "a" unless CASCADE is specified.)

---

*[pkg/sql/descriptor_mutation_test.go, line 949 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka585ZriPfE3I9h4i3z:-Ka7BvMOKChaFJSJa6G8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f19934d9fd59789d5511cdb19f31c3963a1458ba/pkg/sql/descriptor_mutation_test.go#L949)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

// UNIQUE column deletion gets split into two mutation ids.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/alter_table.go, line 223 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-Ka3C8JA2smo0tBwUBSz:-Ka80eksOAvdM1J-s-OZ:bdsdlq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/79377eca6d6851cdc06fa12066e566427ba5c26a/pkg/sql/alter_table.go#L223)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

As I said in my previous comment, we do want to do what you say, and I changed the code accordingly. Also that's the example index i4 in the comment above.

Does this clarify?
</blockquote></details>

Ah, I see. Sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12782#-:-Ka80oMxrQabz9sPjIw9:bnfp4nl)*

**Review by dt — APPROVED** [review]
LGTM

**Comment by knz** [comment]
TFYRs!

**Pull request merged**
