### PR TITLE
kvserver/rangefeed: wrap muxer inside setRangeIDEventSink

### PR DESCRIPTION
**Pull request by wenyihu6**
**kvserver/rangefeed: remove unused cancel**

This patch removes the unused field cancel from setRangeIDEventSink.

Epic: none
Release note: none

---

**kvserver/rangefeed: wrap muxer inside setRangeIDEventSink**

Previously, each rangefeed stream setRangeIDEventSink wrapped the underlying
muxstream to send to grpc stream. This patch changes the stream to wrap the
stream muxer struct instead which itself wraps the underlying muxstream.

Note that this patch doesn’t change any existing behavior but only to make
future commits cleaner when we change muxer to send data to a buffered stream
instead of directly to grpc.

Part of: #126561
Release note: none

---

**kvserver/rangefeed: rename setRangeIDEventSink to perRangeEventSink**

This patch renames `setRangeIDEventSink` to `perRangeEventSink` for clarity.

Epic: none
Release note: none

### CODE REVIEW

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126489)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/server/node.go` line 1841 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126489#-O1X18oO7txhHJPYhM8f:-O1X18oO7txhHJPYhM8g:b-s4ehcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a5d9f398f3452c0d79851c3fa7c6416ba52843/pkg/server/node.go#L1841)):*
> ```Go
> 	Send(event *kvpb.MuxRangeFeedEvent) error
> 	SendIsThreadSafe()
> }
> ```

I added an interface to abstract the methods of `rangefeed.StreamMuxer`. We could also just store the actual `*rangefeed.StreamMuxer` here, but I thought using an interface here makes the purpose of stream muxer in this package clearer. In the future, we will start adding methods like `StreamMuxer.DisconnectStreamWithError` to remove future package, but it should never need other methods like `StreamMuxer.Run`. Do you think this makes sense?

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126489#-:-O1XMf5U0Ygvyhcs-5LY:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/server/node.go` line 1841 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126489#-O1X18oO7txhHJPYhM8f:-O1XKol-0INTHHndSRv0:bkup9n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a5d9f398f3452c0d79851c3fa7c6416ba52843/pkg/server/node.go#L1841)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I added an interface to abstract the methods of `rangefeed.StreamMuxer`. We could also just store the actual `*rangefeed.StreamMuxer` here, but I thought using an interface here makes the purpose of stream muxer in this package clearer. In the future, we will start adding methods like `StreamMuxer.DisconnectStreamWithError` to remove future package, but it should never need other methods like `StreamMuxer.Run`. Do you think this makes sense?
</blockquote></details>

Will there be multiple implementations of this interface? If not, then I don't think the interface is buying us much beyond making the code a little harder to understand and breaking jump-to-definition.
___
*[`pkg/server/node.go` line 1845 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126489#-O1XLAnE5Loqv3Tc347b:-O1XLAnE5Loqv3Tc347c:b-nykf6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a5d9f398f3452c0d79851c3fa7c6416ba52843/pkg/server/node.go#L1845)):*
> ```Go
> var _ muxer = &rangefeed.StreamMuxer{}
> 
> // setRangeIDEventSink is an implementation of rangefeed.Stream which annotates
> ```

Unrelated to this change, but what do you think of this name? I keep thinking it's a function that "sets a range ID on an event sink". Any appetite to switching to something like `rangeBoundEventSink` or `perRangeEventSink` which makes it more clear how the type relates to the other streams?

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126489)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/server/node.go` line 1841 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126489#-O1X18oO7txhHJPYhM8f:-O1XRE9gCj6tu7v_dTje:b-qraapc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a5d9f398f3452c0d79851c3fa7c6416ba52843/pkg/server/node.go#L1841)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Will there be multiple implementations of this interface? If not, then I don't think the interface is buying us much beyond making the code a little harder to understand and breaking jump-to-definition.
</blockquote></details>

No, there will only be one implementation of this interface. Agree, I've removed the interface and only stored the actual struct. 
___
*[`pkg/server/node.go` line 1845 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126489#-O1XLAnE5Loqv3Tc347b:-O1XRHblEupjxLpuWoHm:b9ix9yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a5d9f398f3452c0d79851c3fa7c6416ba52843/pkg/server/node.go#L1845)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Unrelated to this change, but what do you think of this name? I keep thinking it's a function that "sets a range ID on an event sink". Any appetite to switching to something like `rangeBoundEventSink` or `perRangeEventSink` which makes it more clear how the type relates to the other streams?
</blockquote></details>

I like `perRangeEventSink`! I added another commit for this.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126489#-:-O1Xc8Wr9pdZxZipvOXn:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

**Comment by wenyihu6** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
