### PR TITLE
timeutil: allow certain timezone names to be case insensitive

### LINKED ISSUE #36847: sql: perform time zone name comparison case-insensitively
In Postgres, the session timezone setting can always be set by name case-insensitively, but this isn't the case in CockroachDB. Here are examples using `set timezone` in Postgres 11:

<details>
<summary>PG 11, interactive</summary>

```
postgres=# select version();
                                                             version
----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.2 (Debian 11.2-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
(1 row)

postgres=# set timezone=utc;
SET
postgres=# show timezone;
 TimeZone
----------
 UTC
(1 row)

postgres=# set timezone='america/new_york';
SET
postgres=# show timezone;
     TimeZone
------------------
 America/New_York
(1 row)

postgres=# set timezone='est';
SET
postgres=# show timezone;
 TimeZone
----------
 EST
(1 row)

postgres=# set timezone='eUrOPe/iSLe_Of_mAN';
SET
postgres=# show timezone;
      TimeZone
--------------------
 Europe/Isle_of_Man
(1 row)

postgres=# set timezone='PACIFIC/GALAPAGOS';
SET
postgres=# show timezone;
     TimeZone
-------------------
 Pacific/Galapagos
(1 row)
```

</details>

CockroachDB's behavior is not internally consistent and I'm not sure what the pattern is. When using `set timezone` interactively, `utc` and `est` are accepted, but `america/new_york` is not:

<details>
<summary>CockroachDB 19.1, interactive</summary>

```
root@localhost:26257/defaultdb> set timezone='utc';
SET

Time: 670.411µs

root@localhost:26257/defaultdb> show timezone;
  timezone
+----------+
  UTC
(1 row)

Time: 929.086µs

root@localhost:26257/defaultdb> set timezone='est';
SET

Time: 709.276µs

root@localhost:26257/defaultdb> show timezone;
  timezone
+----------+
  EST
(1 row)

Time: 919.475µs

root@localhost:26257/defaultdb> set timezone='america/new_york';
pq: invalid value for parameter "timezone": "'america/new_york'"
DETAIL: cannot find time zone "america/new_york": timezone data cannot be found
root@localhost:26257/defaultdb> set timezone='America/New_York';
SET

Time: 685.353µs

root@localhost:26257/defaultdb> show timezone;
      timezone
+------------------+
  America/New_York
(1 row)

Time: 960.559µs
```

</details>

And when pasing the timezone in the connection URL, the case-sensitive zone name appears to always be required: `utc` and `est` don't work, and neither does `america/new_york`:

<details>
<summary>CockroachDB 19.1, connection string</summary>

```
$ cockroach sql --url 'postgres://localhost:26257/defaultdb?sslmode=disable&timezone=utc' -e 'show timezone'
Error: pq: invalid value for parameter "TimeZone": "utc"
Failed running "sql"
$ cockroach sql --url 'postgres://localhost:26257/defaultdb?sslmode=disable&timezone=UTC' -e 'show timezone'
  timezone
+----------+
  UTC
(1 row)
$ cockroach sql --url 'postgres://localhost:26257/defaultdb?sslmode=disable&timezone=est' -e 'show timezone'
Error: pq: invalid value for parameter "TimeZone": "est"
Failed running "sql"
$ cockroach sql --url 'postgres://localhost:26257/defaultdb?sslmode=disable&timezone=EST' -e 'show timezone'
  timezone
+----------+
  EST
(1 row)
$ cockroach sql --url 'postgres://localhost:26257/defaultdb?sslmode=disable&timezone=america/new_york' -e 'show timezone'
Error: pq: invalid value for parameter "TimeZone": "america/new_york"
Failed running "sql"
$ cockroach sql --url 'postgres://localhost:26257/defaultdb?sslmode=disable&timezone=America/New_York' -e 'show timezone'
      timezone
+------------------+
  America/New_York
(1 row)
```

</details>

Directly motivated by #14988, but we've seen the same issue before (e.g. #31297). In the past we've said "timezones are case sensitive on Linux", but that's a distinction that Postgres doesn't make, so that seems like an unnecessary restriction.

### PR DESCRIPTION
**Pull request by otan**
Resolves https://github.com/cockroachdb/cockroach/issues/36847 

Release note (sql change): Previously, timezones must be entered in the
same case as it is stored on the system. Now, timezone names can be case
insensitive provided it matches well known zone names according to Go's
time/tzdata package.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
I'm glad for the added fnctionality, but I think you can be more clever on the implementation.

The key observation is that you only needs the names, not the actual tzdata. So why don't you simply make a generator program that lists the contents of zoneinfo.zip and creates a go map (lowercase -> normal case) based on that? This could even be re-generated on every build, since we can assume that every Go toolchain will have zoneinfo.zip at a fixed location relative to $GOROOT.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57250#-:-MNY_BeH9hEEeJBaNp-2:b-wey7mw)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by otan** [comment]
ah didn't realise it was in $GOROOT! fixed!

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57250)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
Wait you need to remove the entries that are just for directories, e.g. `artic/`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57250#-:-MNZNBWB9t3xLQQBHrc0:bc8yvmm)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by otan** [comment]
gotcha, done!

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57250)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57250#-:-MNZXakK9pS7ZYVr1I4J:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
cheers

bors r=knz

**Pull request merged**
