### PR TITLE
sql: prevent information loss during decimal parsing

### LINKED ISSUE #25258: sql: string to decimal conversion improperly truncates large negative values
Consider the following (valid, unsurprising) behavior:

```
> select decimal '9223372036854775807.000000001';
+---------------------------------+
|             DECIMAL             |
| '9223372036854775807.000000001' |
+---------------------------------+
|   9223372036854775807.000000001 |
+---------------------------------+

> select 9223372036854775807.000000001::decimal;
+----------------------------------------+
| 9223372036854775807.000000001::DECIMAL |
+----------------------------------------+
|          9223372036854775807.000000001 |
+----------------------------------------+
```

Now compare this:

```
> select decimal '-9223372036854775807.000000001';
+----------------------------------+
|             DECIMAL              |
| '-9223372036854775807.000000001' |
+----------------------------------+
|   -9223372036854775807.000000001 |
+----------------------------------+
```

Still happy! And now:

```
> select (-9223372036854775807.000000001)::decimal;
+-------------------------------------------+
| (-9223372036854775807.000000001)::DECIMAL |
+-------------------------------------------+
|                    -9223372036854775807.0 |
+-------------------------------------------+
```

woops, the fractional part was truncated.

cc @nvanbenschoten @mjibson

### PR DESCRIPTION
**Pull request by nvb**
Fixes #25258.

This change introduces safeguards to prevent the conversion from
`constant.Value` to `apd.Decimal` from losing information. This is
critical because the expectation is that parsing a literal numeric
value will either be lossless or will throw an error. However, up
until this point, this was not the case.

Release note (bug fix): Numeric literal values will no longer silently
lose information after a certain precision.

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]

**Comment by knz** [comment]
Could you simplify the test in `eval_test.go` that I had to write in a crummy fashion because of this? I think I left a TODO with a link to the issue so you can find it more easily.

**Comment by nvanbenschoten** [comment]
@knz done (I think).

**Comment by knz** [comment]
Yep thanks!

**Pull request merged**
