### PR TITLE
testcluster,server: copy test settings to shared proc settings

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
Overall this change seems right to me but the test failures seem to suggest that I'm missing something.

The test that is failing seems to be one that sets a custom setting object:

```
// TestWithOnFrontierAdvance sets up a rangefeed on a span that has more than
// one range and ensures that the OnFrontierAdvance callback is called with the
// correct timestamp.
func TestWithOnFrontierAdvance(t *testing.T) {
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)

	ctx := context.Background()
	settings := cluster.MakeClusterSettings()
	tc := testcluster.StartTestCluster(t, 1, base.TestClusterArgs{
		ReplicationMode: base.ReplicationManual,
		ServerArgs:      base.TestServerArgs{Settings: settings},
	})
	defer tc.Stopper().Stop(ctx)
```

**Comment by dt** [comment]
Server startup is stalling with `unable to start server for tenant ‹"test-tenant"› (attempt 12, will retry): while creating server: cannot initialize version to 1000023.1 because already set to: 1000023.2-upgrading-to-1000024.1-step-004`

**Comment by dt** [comment]
Okay, pretty sure `TestingCopyForVirtualCluster` shouldn't be copying the version setting. Let's see what CI says about this now.

**Review by stevendanna — APPROVED** [review]
LGTM! Thanks for digging into this.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
