### PR TITLE
sql: normalize results for float aggregate functions

### LINKED ISSUE #118733: sql: consider normalizing negative floats due to precision errors
roachtest.unoptimized-query-oracle/disable-rules=all/seed-multi-region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13818354?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13818354?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=all/seed-multi-region) on master @ [15961a19faca0e2b66df2d01a547549523ca70c7](https://github.com/cockroachdb/cockroach/commits/15961a19faca0e2b66df2d01a547549523ca70c7):

```
(query_comparison_util.go:387).runOneRoundQueryComparison: . 1224 statements run: expected unoptimized and optimized results to be equal
  []string{
  	... // 31 identical elements
  	"0",
  	"0",
- 	"0",
  	"NULL",
  	"NULL",
  	... // 170 identical elements
  	"NULL",
  	"NULL",
+ 	"NaN",
  	"NaN",
  	"NaN",
  }
sql: SELECT
	variance("|tͩab_268"._float8::FLOAT8)::FLOAT8 AS c😅ol_1042
FROM
	defaultdb.public.seed_mr_table@[0] AS "|tͩab_268"
WHERE
	"|tͩab_268"._bool
GROUP BY
	"|tͩab_268"._float8
HAVING
	bool_and("|tͩab_268"._bool::BOOL)::BOOL
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=all/seed-multi-region/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13818354/unoptimized-query-oracle-disable-rules-all-seed-multi-region/1706972533352/1706974551762)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=all/seed-multi-region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35873

### PR DESCRIPTION
**Pull request by DrewKimball**
This commit normalizes the results of the float aggregates that should return return a non-negative result, to account for floating-point errors. This should decreases the rate of randomized test failures due to this problem.

Fixes #118733

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119507#-:-NrH2Xh9BInW5JjKxMJJ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 4769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119507#-NrH2MI4DsD1In1GHXPW:-NrH2MI4DsD1In1GHXPX:b-ojm44e) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee696d9668cc2b7c2becf47310329f32396d022/pkg/sql/sem/builtins/aggregate_builtins.go#L4769)):*
> ```Go
> // that cannot be less than zero.
> func ensureNonNegativeFloatResult(res float64) float64 {
> 	if res < 0 {
> ```

nit: should we check some special cases? For example, if `res` is `NaN`, then we'll return `NaN` too.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119507)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 4769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119507#-NrH2MI4DsD1In1GHXPW:-NrH9fpHEh-5w3cXE7Rq:bbn4lfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee696d9668cc2b7c2becf47310329f32396d022/pkg/sql/sem/builtins/aggregate_builtins.go#L4769)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we check some special cases? For example, if `res` is `NaN`, then we'll return `NaN` too.
</blockquote></details>

I think we'd better keep the current behavior - what if one of the input values is `NaN`?

**Comment by DrewKimball** [comment]
TFYR!

bors r+

**Comment by DrewKimball** [comment]
I'll leave this just on master for now. If we see more failures on other branches, we can backport this.

**Comment by rytaft** [comment]
Saw another failure here: https://github.com/cockroachdb/cockroach/issues/122346. Should we backport this?

**Comment by DrewKimball** [comment]
blathers backport 23.2 23.1

**Pull request merged**
