### PR TITLE
backupccl: restart restore if plan changed

### PR DESCRIPTION
**Pull request by dt**
Off by default.

Release note: none.

### CODE REVIEW

**Comment by shermanCRL** [comment]
What behavior is changed by this? I assume that, prior, restore would fail if the plan changed?

**Comment by dt** [comment]
> What behavior is changed by this? 

none, it is off by default.

>  I assume that, prior, restore would fail if the plan changed?
No, the opposite: it'd keep running. The opt-in functionality added here instead stop and then restart it, if it determines that the post-restart plan would be sufficiently different than the one that is running now (e.g. if your cluster has moved ranges, added nodes, etc).

**Comment by miretskiy** [comment]
I know we have the threshold parameter to control the frequency of those restarts.  I wonder if this is sufficient though?
Couldn't we hit the threshold often enough to cause the restarts while the backup itself did not have a chance to advance?

**Comment by dt** [comment]
Yeah, for now you lose un-checkpointed progress when you restart, so you want to balance how long you forfeit the capacity of ignoring new nodes vs how often you throw away the progress since checkpoint. Tuning that trade (or finding a way for jobs to gracefully drawing flows to not throw away progress) is what stands between now and enabling by default.

**Review by adityamaru — APPROVED** [review]
sweet!

**Comment by dt** [comment]
@miretskiy were you worried about this even with it currently off by default?

**Comment by miretskiy** [comment]
Nah... Just bringing this up...

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
