### PR TITLE
sqlccl: add RepartitioningFastPathAvailable

### PR DESCRIPTION
**Pull request by danhhz**
RepartitioningFastPathAvailable returns true when the schema change to
validate existing data can be skipped.

Each partitioned index guarantees that all rows in that index belong to
one of its partitions. Certain repartitionings (removing partitioning
entirely, a LIST partitioning that is a superset of the previous
partitioning, etc) can assume the the existing data meets this guarantee
without checking it via a sort of "inductive proof".

This method is added and tested, but not used yet.

Also refactor partitioning tests to support future development.

@benesch as discussed offline, there's a bit more work to be done here, but you wanted to look at the unfinished version, so here it is! : - )

### CODE REVIEW

**Comment by benesch** [comment]
This looks really, really good. Some comments below.

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/partition.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-bzTrugBXAjdvFJQAz:-L-bzTrugBXAjdvFJQB-:bpmlx0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb03f10b571580529481f9b240106e7450566584/pkg/ccl/sqlccl/partition.go#L118)):*
> ```Go
> 		}
> 		coverings = append(coverings, covering)
> 	}
> ```

I think you want

```
if len(partDesc.List > 0 {
  // ...
} else if len(partDesc.Range) > 0 {
  // ...
} else {
  span := tableDesc.IndexSpan(indexDesc.ID)
  coverings = []{start: span.Key, End: span.EndKey, Payload: payload}
}
```

because an unpartitioned index essentially has one anonymous `DEFAULT` partition covering the whole thing.

---

*[pkg/ccl/sqlccl/partition_test.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-bnyGlKHB-pn8JKFk-:-L-bnyGlKHB-pn8JKFk0:bid0ki8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffcf8b8dbe93832ac46c06512860f4965d5ce8d6/pkg/ccl/sqlccl/partition_test.go#L84)):*
> ```Go
> 		tableName string
> 
> 		// createStmt is `schema` with a table name of `escapedName`
> ```

`escapedName` doesn't exist. `tableName`?

---

*[pkg/ccl/sqlccl/partition_test.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-bo1ks8w7u0MQdgtw3:-L-bo1ks8w7u0MQdgtw4:b-ytass5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffcf8b8dbe93832ac46c06512860f4965d5ce8d6/pkg/ccl/sqlccl/partition_test.go#L90)):*
> ```Go
> 		tableDesc *sqlbase.TableDescriptor
> 
> 		// zoneConfigStmt constains SQL that effects the zone configs described by
> ```

`constains`

---

*[pkg/ccl/sqlccl/partition_test.go, line 115 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-boRr_OBl6rk1aPYfJ:-L-boRr_OBl6rk1aPYfK:b-gf6vdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffcf8b8dbe93832ac46c06512860f4965d5ce8d6/pkg/ccl/sqlccl/partition_test.go#L115)):*
> ```Go
> 		}
> 		const parentID, tableID = keys.MaxReservedDescID + 1, keys.MaxReservedDescID + 2
> 		t.parsed.tableDesc, err = makeCSVTableDescriptor(
> ```

Well that's kind of a weirdly-named function to call, but I suppose it does the trick. Something somewhere should have a comment about this though.

---

*[pkg/ccl/sqlccl/partition_test.go, line 693 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-bxYyDLQhOB_0ljeZq:-L-bxYyDLQhOB_0ljeZr:bka268t) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb03f10b571580529481f9b240106e7450566584/pkg/ccl/sqlccl/partition_test.go#L693)):*
> ```Go
> 			old:        `unpartitioned`,
> 			new:        `single col list partitioning`,
> 			isFastPath: true,
> ```

Wait, how is this fast path? Couldn't any random crap be in the table?

---

*[pkg/ccl/sqlccl/partition_test.go, line 703 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-bxhlPr2R71sSrTEEG:-L-bxhlPr2R71sSrTEEH:b-7esevx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb03f10b571580529481f9b240106e7450566584/pkg/ccl/sqlccl/partition_test.go#L703)):*
> ```Go
> 			old:        `unpartitioned`,
> 			new:        `single col range partitioning`,
> 			isFastPath: true,
> ```

Ditto here.

---

*[pkg/ccl/sqlccl/partition_test.go, line 709 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-c-Fby-s7rTiZJVk71:-L-c-Fby-s7rTiZJVk72:bjsa7yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb03f10b571580529481f9b240106e7450566584/pkg/ccl/sqlccl/partition_test.go#L709)):*
> ```Go
> 			new:        `single col range partitioning - MAXVALUE`,
> 			isFastPath: true,
> 		},
> ```

Tests from all the above _to_ `unpartitioned`? I.e., removing partitioning schemes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-:-L-bxqf4gPimlnzmpNbC:bbs3hh5)*

**Comment by danhhz** [comment]
Thanks for the review! RFAL

---

Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/ccl/sqlccl/partition.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-bzTrugBXAjdvFJQAz:-L-cXTMxZlPzPk8xIEtg:b-79vye7) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb03f10b571580529481f9b240106e7450566584/pkg/ccl/sqlccl/partition.go#L118)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think you want

```
if len(partDesc.List > 0 {
  // ...
} else if len(partDesc.Range) > 0 {
  // ...
} else {
  span := tableDesc.IndexSpan(indexDesc.ID)
  coverings = []{start: span.Key, End: span.EndKey, Payload: payload}
}
```

because an unpartitioned index essentially has one anonymous `DEFAULT` partition covering the whole thing.
</blockquote></details>

You are correct, good sir.

---

*[pkg/ccl/sqlccl/partition_test.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-bnyGlKHB-pn8JKFk-:-L-cVgUp7j8KtCxdFjuf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffcf8b8dbe93832ac46c06512860f4965d5ce8d6/pkg/ccl/sqlccl/partition_test.go#L84)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`escapedName` doesn't exist. `tableName`?
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/partition_test.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-bo1ks8w7u0MQdgtw3:-L-cVkjWYsk4VCG7Q3qr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffcf8b8dbe93832ac46c06512860f4965d5ce8d6/pkg/ccl/sqlccl/partition_test.go#L90)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`constains`
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/partition_test.go, line 115 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-boRr_OBl6rk1aPYfJ:-L-cVx9w9dISRJv5MF9e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffcf8b8dbe93832ac46c06512860f4965d5ce8d6/pkg/ccl/sqlccl/partition_test.go#L115)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Well that's kind of a weirdly-named function to call, but I suppose it does the trick. Something somewhere should have a comment about this though.
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/partition_test.go, line 693 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-bxYyDLQhOB_0ljeZq:-L-cW11ZZz2vWztJQsmx:b-1z398h) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb03f10b571580529481f9b240106e7450566584/pkg/ccl/sqlccl/partition_test.go#L693)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Wait, how is this fast path? Couldn't any random crap be in the table?
</blockquote></details>

:man_facepalming: 

---

*[pkg/ccl/sqlccl/partition_test.go, line 703 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-bxhlPr2R71sSrTEEG:-L-cWmY2N1J7prE97bpO:bzhs7tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb03f10b571580529481f9b240106e7450566584/pkg/ccl/sqlccl/partition_test.go#L703)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ditto here.
</blockquote></details>

you're also right about this one

---

*[pkg/ccl/sqlccl/partition_test.go, line 709 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-c-Fby-s7rTiZJVk71:-L-cXAfoJvZFqxw-uZOe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb03f10b571580529481f9b240106e7450566584/pkg/ccl/sqlccl/partition_test.go#L709)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Tests from all the above _to_ `unpartitioned`? I.e., removing partitioning schemes?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-:-L-ca7osDPJ_Strklglu:b-6sx6b6)*

**Comment by benesch** [comment]
:lgtm:

Looks like the INET type is failing your test, though.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/partition_test.go, line 753 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-gLsm_Dlo4VmwJAZSf:-L-gLsmaiG5y0eyKhKqQ:b-lj4hgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e42b8292eb7ed58a03caa13c13da48bfbec999e/pkg/ccl/sqlccl/partition_test.go#L753)):*
> ```Go
> 			new:        `single col range partitioning`,
> 			isFastPath: false,
> 		},
> ```

This looks like a dupe?

---

*[pkg/ccl/sqlccl/partition_test.go, line 809 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-gMJREqrwRxmCjopeB:-L-gMJREqrwRxmCjopeC:b-u2bvxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e42b8292eb7ed58a03caa13c13da48bfbec999e/pkg/ccl/sqlccl/partition_test.go#L809)):*
> ```Go
> 			old:        `multi col range partitioning - MAXVALUE`,
> 			new:        `multi col range partitioning`,
> 			isFastPath: true, // NB: The MAXVALUE one is constructed to cover the same range
> ```

I don't understand this comment. The MAXVALUE one has an additional partition, right? 

In any case, I don't care about this ATM because range partitions are screwy in general.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-:-L-gMgU5yWfWVTfmQ_Ga:b-2xuv5v)*

**Comment by danhhz** [comment]
I think I lost INET in a rebase or something. I recall having fixed that one

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/partition_test.go, line 753 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-gLsm_Dlo4VmwJAZSf:-L-gXdVHLvmED5E51HeN:bldt98m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e42b8292eb7ed58a03caa13c13da48bfbec999e/pkg/ccl/sqlccl/partition_test.go#L753)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This looks like a dupe?
</blockquote></details>

With what?

---

*[pkg/ccl/sqlccl/partition_test.go, line 809 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-gMJREqrwRxmCjopeB:-L-gXw1X6W98ILSGaJQC:b-929x8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e42b8292eb7ed58a03caa13c13da48bfbec999e/pkg/ccl/sqlccl/partition_test.go#L809)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I don't understand this comment. The MAXVALUE one has an additional partition, right? 

In any case, I don't care about this ATM because range partitions are screwy in general.
</blockquote></details>

Expanded the comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-:-L-gY_iVACRaN11jdzPL:by7vise)*

**Comment by benesch** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/partition_test.go, line 753 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-gLsm_Dlo4VmwJAZSf:-L-g_99hlP13YRDjJcFi:b-3iwacu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e42b8292eb7ed58a03caa13c13da48bfbec999e/pkg/ccl/sqlccl/partition_test.go#L753)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

With what?
</blockquote></details>

With the second entry in the list

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483)*

**Comment by benesch** [comment]
Reviewed 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/partition_test.go, line 809 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-gMJREqrwRxmCjopeB:-L-gcK5Y83XC3rwRq7dx:b-3ohalw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e42b8292eb7ed58a03caa13c13da48bfbec999e/pkg/ccl/sqlccl/partition_test.go#L809)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Expanded the comment
</blockquote></details>

D'oh, I think that I was looking at the single col range partitioning before. This expanded comment is much appreciated, though—thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483)*

**Comment by danhhz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/partition_test.go, line 753 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483#-L-gLsm_Dlo4VmwJAZSf:-L-gccj1lI28HV7LYU3f:b6plgok) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e42b8292eb7ed58a03caa13c13da48bfbec999e/pkg/ccl/sqlccl/partition_test.go#L753)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

With the second entry in the list
</blockquote></details>

Ah, that one is unpartitioned -> single col _list_ partitioning, this is _range_

This proves something that I've suspected tho, which is that my naming here sucks. I'm going to merge this as is, but I think we should revisit and see if we can do something that's more obvious at a glance

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20483)*

**Pull request merged**
