### PR TITLE
sql: support redaction of EXPLAIN (OPT)

### PR DESCRIPTION
**Pull request by michae2**
**sql: support redaction of EXPLAIN (OPT)**

Support redaction of `EXPLAIN (OPT)` and add opt*.txt back to redacted
statement diagnostics bundles. This is achieved by adding a new
`redactableValues` option to `cat.FormatTable`,
`xform.(*Optimizer).FormatMemo`, and `memo.ExprFmtCtx` which causes
user-provided constants and literals to be surrounded by redaction
markers in formatted output. Then `redact.(RedactableString).Redact` is
used to further redact the redactable output.

Part of: #68570

Epic: CRDB-19756

Release note (sql change): Add support for the `REDACT` flag to the
following variants of `EXPLAIN`:

- `EXPLAIN (OPT)`
- `EXPLAIN (OPT, CATALOG)`
- `EXPLAIN (OPT, MEMO)`
- `EXPLAIN (OPT, TYPES)`
- `EXPLAIN (OPT, VERBOSE)`

These explain statements will have constants, literal values, parameter
values, and any other user data redacted in output.

**sql, tests, sqlccl: split TestExplainRedactDDL out of TestExplainRedact**

Create another version of TestExplainRedact which also tests
`EXPLAIN (REDACT)` of DDL statements. This version is in sqlccl to allow
for DDL statements using partitions.

Part of: #68570
Informs: #98746

Epic: CRDB-19756

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
@RaduBerinde I'm wondering if you would be willing to take a look at one more `EXPLAIN` redaction PR? This will be the last one.

**Review by RaduBerinde — COMMENTED** [review]
I don't see any tests showing what the redacted output looks like. We'd want fairly extensive tests (probably in `opt/cat`) to make sure we redact everything (and probably add more complex schemas to the existing bundle test with `pterodactyl`)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-:-NPEBuvC1uAXFxf1weuV:b-j6kqug)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPEChLMB_aUWyggymNK):*
[nit] It would be nice to explain functionally what we're doing. In particular the fact that the entire opt plan is redacted was surprising to me.
___
*[`pkg/sql/opt/cat/utils.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPEAqau57k0Q-bJJffb:-NPEAqau57k0Q-bJJffc:b9wny8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/cat/utils.go#L60)):*
> ```Go
> // FormatTable nicely formats a catalog table using a treeprinter for debugging
> // and testing.
> func FormatTable(cat Catalog, tab Table, tp treeprinter.Node, redactableValues bool) {
> ```

[nit] maybe explain what redactableValues means in the comment. It's worth considering that whoever reads this code probably isn't familiar with the redaction library - it took me a bit to understand that we are not *removing* any values here, just adding some markers (and the removal happens later in `.Redact()`)

Or instead of a flag, consider passing a `redactor` type (that's an alias for `func(string) string`) which can be documented separately.

Also, looking at the redaction library, it looks like it's intended that we always include the readaction markers (and return `RedactableString`) and then use either `StripMarkers` or `Redact` on the output. Maybe that's a too intrusive change though.
___
*[`pkg/sql/opt/cat/utils.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPEBgPk-CT2yt_cLBw2:-NPEBgPk-CT2yt_cLBw3:bc9eyx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/cat/utils.go#L83)):*
> ```Go
> 
> 	for i := 0; i < tab.CheckCount(); i++ {
> 		constrStr := tab.Check(i).Constraint
> ```

[nit] This common pattern would be simplified if we had a `maybeRedact()` function that is either a noop or a `redact.Sprintf("%s")` depending on the flag.
___
*[`pkg/sql/opt/cat/utils.go` line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPECFf64ibyEaQ8raVY:-NPECFf64ibyEaQ8raVZ:b-npcm9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/cat/utils.go#L293)):*
> ```Go
> 	}
> 	if col.HasOnUpdate() {
> 		fmt.Fprintf(buf, " on update (%s)", col.OnUpdateExprStr())
> ```

This needs redacting I think?

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 6 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97549)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @RaduBerinde)

___
*[`pkg/sql/opt/cat/utils.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPKRgrJ9yv5T2e7GTpo:-NPKRgrJ9yv5T2e7GTpp:bpeqpqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/cat/utils.go#L61)):*
> ```Go
> // and testing.
> func FormatTable(cat Catalog, tab Table, tp treeprinter.Node, redactableValues bool) {
> 	child := tp.Childf("TABLE %s", tab.Name())
> ```

It might be obvious, but I'm confused why we're redacting the CHECK constraint below but not the table name here. I took a brief look at https://github.com/cockroachdb/cockroach/issues/68570 and https://cockroachlabs.atlassian.net/browse/CRDB-19756 but didn't see a list of things that we're ok keeping unredacted. Is there such a list somewhere?
___
*[`pkg/sql/opt/memo/expr_format.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPKSmU121LqWhQqKHD6:-NPKSmU2-vwXk-35VjO5:boxdz1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/memo/expr_format.go#L177)):*
> ```Go
> 
> 	// If RedactableValues is true we surround any constant values or other user
> 	// data from the formatted expression with redaction markers, including spans.
> ```

Do we need to do something about `inverted.Spans.Format`? Perhaps more details in the commit message about how places of redaction were chosen vs left unchanged would be helpful.

**Review by michae2 — COMMENTED** [review]
Sorry for the delay. Added some cases to logic tests (this was easier than unit tests in `opt/cat`). I'm hesitant to add more random schemas to [TestExplainRedact](https://github.com/cockroachdb/cockroach/blob/a79338ae18a646bbf3509ca82985b28c970d2aa4/pkg/sql/explain_test.go#L479-L480) because they could contain partitions, so instead I'll add a randomized test somewhere under `pkg/ccl/testccl/sqlccl`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-:-NQWELU83Mo7lkhFrUep:bd4vkcq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPEChLMB_aUWyggymNK):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] It would be nice to explain functionally what we're doing. In particular the fact that the entire opt plan is redacted was surprising to me.
</blockquote></details>

I've added a little more to the commit message, LMK if that is better (sorry for the poor explanation).
___
*[`pkg/sql/opt/cat/utils.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPEAqau57k0Q-bJJffb:-NQW21-s0QVoGwBejlX1:b-q5xy06) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/cat/utils.go#L60)):*
> nit] maybe explain what redactableValues means in the comment. It's worth considering that whoever reads this code probably isn't familiar with the redaction library - it took me a bit to understand that we are not removing any values here, just adding some markers (and the removal happens later in .Redact())

Ah, good point. I added a little more to the comment, LMK if that helps.

> Or instead of a flag, consider passing a redactor type (that's an alias for func(string) string) which can be documented separately.

Not sure I understand. Were you thinking the redactor would perform the last step (redaction)? E.g. something like:

```go
redactor := func (redactable string) string {
  return string(redact.RedactableString(redactable).Redact())
}
```

or would it perform the first step (surrounding with redaction markers)? I'm trying to keep the two steps separate, to leave open the possibility of `EXPLAIN (REDACTABLE)` one day.

> Also, looking at the redaction library, it looks like it's intended that we always include the readaction markers (and return RedactableString) and then use either StripMarkers or Redact on the output. Maybe that's a too intrusive change though.

We could always add redaction markers, but it seems like extra work for something that will almost always be stripped out.
___
*[`pkg/sql/opt/cat/utils.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPKRgrJ9yv5T2e7GTpo:-NQWAhxU5v2K0_fXzXXk:bz27a5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/cat/utils.go#L61)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It might be obvious, but I'm confused why we're redacting the CHECK constraint below but not the table name here. I took a brief look at https://github.com/cockroachdb/cockroach/issues/68570 and https://cockroachlabs.atlassian.net/browse/CRDB-19756 but didn't see a list of things that we're ok keeping unredacted. Is there such a list somewhere?
</blockquote></details>

Right now we're only redacting end-user data (that is, values stored in tables) and not the names of tables or columns. We're including all constants / literals in DML and DDL queries because these could be derived from end-user data. Some discussions about this were in [slack](https://cockroachlabs.slack.com/archives/C037HS56734/p1660843858052999) and [docs](https://docs.google.com/document/d/1J9PMjeXsAwuK3GeYRMA-VVU3ptPQCtriqQMFgh7V8iA/edit?usp=sharing).

If we find that redacting CHECK constraints is too strict I think we could come back and loosen it in 23.2.
___
*[`pkg/sql/opt/cat/utils.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPEBgPk-CT2yt_cLBw2:-NQWCUl69DsS90d4-sYy:b-6w29b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/cat/utils.go#L83)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This common pattern would be simplified if we had a `maybeRedact()` function that is either a noop or a `redact.Sprintf("%s")` depending on the flag.
</blockquote></details>

Created a helper function.
___
*[`pkg/sql/opt/cat/utils.go` line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPECFf64ibyEaQ8raVY:-NQWCYa4AlvN-PWFHb_J:b-o7vuhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/cat/utils.go#L293)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This needs redacting I think?
</blockquote></details>

Good catch! Done.
___
*[`pkg/sql/opt/memo/expr_format.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPKSmU121LqWhQqKHD6:-NQWC_ktBCoOoPLSfST9:b-uq4i26) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/memo/expr_format.go#L177)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Do we need to do something about `inverted.Spans.Format`? Perhaps more details in the commit message about how places of redaction were chosen vs left unchanged would be helpful.
</blockquote></details>

Good catch, I will take a look at this.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-:-NQWKpSY4yTV9vR2maab:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/opt/cat/utils.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPEAqau57k0Q-bJJffb:-NQWK7PCCdw69zLD1iv9:b-wc2l7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/cat/utils.go#L60)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> nit] maybe explain what redactableValues means in the comment. It's worth considering that whoever reads this code probably isn't familiar with the redaction library - it took me a bit to understand that we are not removing any values here, just adding some markers (and the removal happens later in .Redact())

Ah, good point. I added a little more to the comment, LMK if that helps.

> Or instead of a flag, consider passing a redactor type (that's an alias for func(string) string) which can be documented separately.

Not sure I understand. Were you thinking the redactor would perform the last step (redaction)? E.g. something like:

```go
redactor := func (redactable string) string {
  return string(redact.RedactableString(redactable).Redact())
}
```

or would it perform the first step (surrounding with redaction markers)? I'm trying to keep the two steps separate, to leave open the possibility of `EXPLAIN (REDACTABLE)` one day.

> Also, looking at the redaction library, it looks like it's intended that we always include the readaction markers (and return RedactableString) and then use either StripMarkers or Redact on the output. Maybe that's a too intrusive change though.

We could always add redaction markers, but it seems like extra work for something that will almost always be stripped out.
</blockquote></details>

No, I was thinking of just passing around a function that is either a no-op `func (s string) string { return s }` or or a function that calls `redact.Sprintf`. But it's ok the way you have it now too, with `MaybeRedact` instead of `if`s everywhere.

**Review by michae2 — COMMENTED** [review]
> I'll add a randomized test somewhere under pkg/ccl/testccl/sqlccl.

Ok, the second commit now adds a new randomized test to `pkg/ccl/testccl/sqlccl/explain_test.go` called `TestExplainRedactDDL` which uses more complex schemas and tests `EXPLAIN (REDACT)` variants on `CREATE` and `ALTER` statements.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-:-NQi6hyK2WlNcq6VkqIS:bu3ykbl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @yuzefovich)

___
*[`pkg/sql/opt/memo/expr_format.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97549#-NPKSmU121LqWhQqKHD6:-NQi5slH6pnteJftudva:b1tbk08) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7725ebdfd5ccc36d9b3bdd2342088c2af9b11/pkg/sql/opt/memo/expr_format.go#L177)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Good catch, I will take a look at this.
</blockquote></details>

This was indeed a PII leak (great catch!) which has now been fixed. A testcase has been added to `pkg/sql/opt/exec/execbuilder/testdata/explain_redact` (the one starting with `EXPLAIN (OPT, REDACT) SELECT * FROM g`).

**Comment by michae2** [comment]
Looks like the new test is running into a problem when running `EXPLAIN ANALYZE BACKUP ...`. I'm going to work on this. After fixing the test I will bors this later today (if there are no objections).

**Comment by michae2** [comment]
TFYR!

bors r=RaduBerinde

**Pull request merged**
