### PR TITLE
sql: make databases track their child schemas

### LINKED ISSUE #52000: sql: databases should store a list available schema names
This will allow us to know when a database doesn't have a schema under it without performing a KV lookup.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #52000.

This commits adds a mapping to database descriptors to track their set
of child schemas. This will be important for making name resolution more
efficient, but this optimization is not done in this PR.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52014#-:-MDQK4zhAQLJDPUUJIfa:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/sqlbase/structured.proto, line 1044 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52014#-MDQJf0o2VxODhUyvaO2:-MDQJf0rAWdnc0SF9vDA:bzfpywc) ([raw file](https://github.com/cockroachdb/cockroach/blob/396de05ea03be5bb144f96b9d17b72c275bd5a0c/pkg/sql/sqlbase/structured.proto#L1044)):*
> ```protobuf
>   // child_schemas is a mapping from child schema name to ID. It is used during
>   // name resolution to know without a KV lookup whether a database has a
>   // child schema with a target name.
> ```

maybe note that we don't store temp schemas here (maybe it's obvious). 
___
*[pkg/sql/sqlbase/structured.proto, line 1045 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52014#-MDQJlQ94qtAgN7M56lw:-MDQJlQ94qtAgN7M56lx:bsbzrvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/396de05ea03be5bb144f96b9d17b72c275bd5a0c/pkg/sql/sqlbase/structured.proto#L1045)):*
> ```protobuf
>   // name resolution to know without a KV lookup whether a database has a
>   // child schema with a target name.
>   map<string, uint32> child_schemas = 7 [(gogoproto.castvalue) = "ID"];
> ```

nit: maybe just call it `schemas`?

**Review by thoszhang — COMMENTED** [review]
Don't we also need to store whether the schema descriptor corresponding to the name is dropped?

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52014#-:-MDQPdL76toeVc_Po1ci:btc4plx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by rohany** [comment]
> Don't we also need to store whether the schema descriptor corresponding to the name is dropped?

Do we need that? I was just going to delete it from here when dropping the schema

**Comment by rohany** [comment]
Updated with andrew's comments, and updated to store whether or not the schema is dropped.

**Review by ajwerner — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52014)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
