### PR TITLE
storage: batch multiple RaftMessageRequests per RPC

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9485)

### CODE REVIEW

**Comment by petermattis** [comment]
I was hoping this would have more of an impact. Perhaps it will on real clusters. The three commits show the development process. I'll squash before/if this gets merged. And I should probably get rid of `MultiRaft.RaftMessage` since that endpoint is only used by tests now.

Cc @cockroachdb/stability

**Comment by petermattis** [comment]
Here's a histogram of the batch size for a 5 min block_writer test against a local 3 node cluster:

screen shot 2016-09-21 at 12 44 58 pm

66% of requests have a batch size of 1.

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/raft_transport.go, line 329 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485#-KSCerYyGjJzurnK7WrU:-KSCerYyGjJzurnK7WrV:bi1mrro) ([raw file](https://github.com/cockroachdb/cockroach/blob/b857e4f6f2ed4e600dfef4cc6e365f5aac6eb213/storage/raft_transport.go#L329)):*
> ```Go
> 
> // RaftMessageBatch proxies the incoming requests to the listening server interface.
> func (t *RaftTransport) RaftMessageBatch(stream MultiRaft_RaftMessageBatchServer) (err error) {
> ```

kill named return

---

*[storage/raft_transport.go, line 354 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485#-KSCfBszmDwTqTYHTiH7:-KSCfBszmDwTqTYHTiH8:bic1t2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b857e4f6f2ed4e600dfef4cc6e365f5aac6eb213/storage/raft_transport.go#L354)):*
> ```Go
> 						req := &batch.Requests[i]
> 						if pErr := t.handleRaftRequest(stream.Context(), req, stream); pErr != nil {
> 							atomic.AddInt64(&stats.serverSent, 1)
> ```

i'd give `serverRecv` the same treatment for simplicity

---

*[storage/raft_transport.go, line 542 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485#-KSCfYrDl1to3LuVyYiy:-KSCfYrExiOJeT-2bs3U:bq3mqe1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b857e4f6f2ed4e600dfef4cc6e365f5aac6eb213/storage/raft_transport.go#L542)):*
> ```Go
> 					select {
> 					case req := <-ch:
> 						batch.Requests = append(batch.Requests, *req)
> ```

something something it's already on the heap so maybe better not to copy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485)*

**Comment by petermattis** [comment]
I experimented with add a 1ms pause to wait for other requests to add to the batch. Doing so lowered the top-end speed when starting an empty cluster, but didn't have any impact on a 10min `block_writer` run.

**Comment by bdarnell** [comment]
LGTM. 5% isn't huge, but it's not bad for this fairly simple change. How many ranges do we see in these 5-10min test runs? The impact should grow with higher range counts. 

GRPC has some [compression options](https://godoc.org/google.golang.org/grpc#Compressor) that we're not yet using. I think batching will improve the effectiveness of compression since they appear to be compressing each message independently. 

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485#-:-KSEqu_U8iSxz6MPiGOi:btk81cb)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485)*

**Comment by petermattis** [comment]
The 10min block_writer test had something like a thousand ranges. This was accomplished by setting the range max size to 4MB and using larger block_writer values (1KB-2KB). I'll be curious to see what impact that has on gamma/delta.

I added another commit which gets rid of the `RaftMessage` RPC endpoint. I think this is ready to go now (assuming we don't care about restricting the size of batches yet). PTAL.

---

Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/raft_transport.go, line 329 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485#-KSCerYyGjJzurnK7WrU:-KSHViqy1APWYeacjOac:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b857e4f6f2ed4e600dfef4cc6e365f5aac6eb213/storage/raft_transport.go#L329)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> kill named return
</details>
Done.

---

*[storage/raft_transport.go, line 354 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485#-KSCfBszmDwTqTYHTiH7:-KSHVq61LkBwQhsk0D58:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b857e4f6f2ed4e600dfef4cc6e365f5aac6eb213/storage/raft_transport.go#L354)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i'd give `serverRecv` the same treatment for simplicity
</details>
Done.

---

*[storage/raft_transport.go, line 542 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485#-KSCfYrDl1to3LuVyYiy:-KSHVrN7oQx5UFUp4bzq:bq8g0tc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b857e4f6f2ed4e600dfef4cc6e365f5aac6eb213/storage/raft_transport.go#L542)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> something something it's already on the heap so maybe better not to copy.
</details>
Yeah, I considered that. But then `Requests` would have the type `[]*RaftMessageRequest` which implies more allocation on the receiver side.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485#-:-KSHWGlrMdmCXJ9_rqkU:b-viqho4)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9485)*

**Pull request merged**
