### PR TITLE
Revert #63785

### PR DESCRIPTION
**Pull request by adityamaru**
This change reverts both the commits in #63785 that are causing a data race in tests.

### CODE REVIEW

**Comment by tbg** [comment]
Is this a clean revert? If so, LGTM. Otherwise, let's wait for @postamar.

**Comment by ajwerner** [comment]
I never looked at these changes in the first place but here's a stamp as a revert should be low friction

**Review by ajwerner — APPROVED** [review]

**Comment by adityamaru** [comment]
@postamar wanted to take a quick look in case the fix is quicker than the revert -- I'll merge this once I get an LGTM from him!

**Comment by postamar** [comment]
Yes I'll be quick about it.

**Comment by postamar** [comment]
I have a fix. This is a dumb bug.

**Comment by postamar** [comment]
https://github.com/cockroachdb/cockroach/pull/63921 is up

**Comment by adityamaru** [comment]
Closing because of fix in #63921.

**Pull request closed without merging**
