### PR TITLE
ccl/sqlproxyccl: tenant denylist in yml format

### PR DESCRIPTION
**Pull request by darinpp**
Moves over from the CC repo a denylist service implementation.
* vendor: make viper explicit dep
* ccl/sqlproxyccl/denylist: add a simple denylist service  The service
reads denied ids from a yml denylist file with format
`<id>: <reason for denial>`
The file is loaded at init time and periodically reloaded to capture
any new updates.  The initial implemenation is very simplistic on
purpose to speed up e2e use of the denylist file. In a fillow up PR we
will switch to SIGHUP or fsnotofy to reload the file on demand when
changes have been made and also a notification service will be added
to notify listeners of any changes to the list.

Release note: None

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
Are we worried about taking this dependency in CRDB? How big of a dependency is it? It looks like the only thing we get from it is monitoring of files. Can't we use the same approach you used for certificate files instead?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64617#-:-MZopxE59KU55sP4kGmU:bgyiweg)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by andy-kimball** [comment]
Hm, never mind, I see that we're just polling on the file, which is not great. Also, I guess viper is the one parsing the file, which still surprises me. Is it adding enough value over just using a regular yaml parser?

**Review by darinpp — COMMENTED** [review]
The dependency is already there. This only changes it to be explicit (vs being dependency of the other part of the package that we use to parse command line arguments). There are no changes from what we have in CC repo. I'm just moving it over. It probably would make sense to see if just reading yaml isn't better but I'm not sure if I should do this now. This is the last piece that I need before I move the handler. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64617#-:-MZp0Y9T9jWpS6w2hw9j:b-1ehzdn)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andy-kimball — APPROVED** [review]
OK, sounds fine, then, if it's already a dependency.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64617#-:-MZpDIaN1bbdkqKhH1Gv:b-j1p9p8)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
