### PR TITLE
systemschema: use ExcludeDataFromBackup on some tables

### PR DESCRIPTION
**Pull request by rafiss**
Certain tables are updated frequently and contain data that should never be backed up or restored. Allowing backups on them is not desired, since that results in protected timestamps being applied on the table, which prevents GC of old data.

This commit excludes the lease, replication_constraint_stats, replication_stats, and tenant_usage tables from backups. These are the tables that explicitly have their gc.ttl configured to a lower value.

informs: https://github.com/cockroachdb/cockroach/issues/80866
Release note: None

### CODE REVIEW

**Comment by Arivijay** [comment]
Hey @rafiss,
Any chance of this getting backported it to 23.2?

**Comment by rafiss** [comment]
It cannot be backported, since modifying system tables in this way is not possible in patch releases.

**Review by fqazi — CHANGES_REQUESTED** [review]
Looks good, just one minor comment

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119947#-:-NsOcxPM8S5Ug0Hckc_C:bfza8p4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/upgrade/upgrades/v24_1_system_database.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119947#-NsOcimS0w0PtHg2B7o4:-NsOcimS0w0PtHg2B7o5:b-d30ov3) ([raw file](https://github.com/cockroachdb/cockroach/blob/de39d70fac3c44ba943a38e946b0f3e3b28ac865/pkg/upgrade/upgrades/v24_1_system_database.go#L111)):*
> ```Go
> 		if err := deps.DB.DescsTxn(ctx, func(ctx context.Context, txn descs.Txn) error {
> 			for _, tabName := range []catconstants.SystemTableName{
> 				catconstants.ReplicationConstraintStatsTableName,
> ```

Do we want an upgrade test to confirm this?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119947)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/upgrade/upgrades/v24_1_system_database.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119947#-NsOcimS0w0PtHg2B7o4:-NsP2m3LCVBe5P8aWrHa:b9ugcmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/de39d70fac3c44ba943a38e946b0f3e3b28ac865/pkg/upgrade/upgrades/v24_1_system_database.go#L111)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Do we want an upgrade test to confirm this?
</blockquote></details>

i added a logic test

**Review by fqazi — APPROVED** [review]
:lgtm: great work!

> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119947#-:-NsP8Z8GEQdXE_hp9cJo:b-2zonaq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
