### PR TITLE
storage/engine: disable L6 bloom filters in Pebble

### PR DESCRIPTION
**Pull request by petermattis**
We disable L6 bloom filters in RocksDB due to the excessive space
overhead they impose in relation to their impact on reads. Disable L6
bloom filters in Pebble for symmetry.

Release note: None

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43895#-:-LyUVjn4-UDeHssOzK12:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43895#-LyUVTJuEsBN_ax--7C5:-LyUVTJuEsBN_ax--7C6:b-ug59dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a943f706bbd72a9710a09081c94c1759cc90a2cc/pkg/storage/engine/pebble.go#L247)):*
> ```Go
> 	}
> 
> 	opts.Levels[0].EnsureDefaults()
> ```

What's the reason behind not calling this on all levels to start with?

**Review by petermattis — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43895#-:-LyUhHTFC8mjr4aDjYRy:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43895#-LyUVTJuEsBN_ax--7C5:-LyUfVoL47ZD5RZ9yY4L:b-t4w30g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a943f706bbd72a9710a09081c94c1759cc90a2cc/pkg/storage/engine/pebble.go#L247)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

What's the reason behind not calling this on all levels to start with?
</blockquote></details>

No reason, and it does look a little strange. Internally, `pebble.Open` will call `EnsureDefaults` on every level, so the effect of not doing so was harmless. I've switched this to doing it inside the loop.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43895)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @petermattis)

___
*[pkg/storage/engine/pebble.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43895#-LyUVTJuEsBN_ax--7C5:-LyUoTf9BKlhuIq-bJuC:b-a0rigg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a943f706bbd72a9710a09081c94c1759cc90a2cc/pkg/storage/engine/pebble.go#L247)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

No reason, and it does look a little strange. Internally, `pebble.Open` will call `EnsureDefaults` on every level, so the effect of not doing so was harmless. I've switched this to doing it inside the loop.
</blockquote></details>

I'm confused. `Options.EnsureDefaults` does not copy the `LevelOptions` from index 0 of the slice, so prior to this PR how were the other levels getting a non-nil `FilterPolicy`?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43895)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43895#-LyUVTJuEsBN_ax--7C5:-LyUwZ0Y21FSD79iSu5g:b1b893r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a943f706bbd72a9710a09081c94c1759cc90a2cc/pkg/storage/engine/pebble.go#L247)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm confused. `Options.EnsureDefaults` does not copy the `LevelOptions` from index 0 of the slice, so prior to this PR how were the other levels getting a non-nil `FilterPolicy`?
</blockquote></details>

`Options.MakeWriterOptions(level)` calls `Options.Level(level)` which copies the the settings from the last level.

**Pull request merged**
