### PR TITLE
cdc: Avoid unnecessary string allocations when emitting rows.

### PR DESCRIPTION
**Pull request by miretskiy**
Memoize descriptor id to topic name mapping when creating kafka
sink to reduce memory allocations when emitting rows.

Release Notes: None

### CODE REVIEW

**Comment by miretskiy** [comment]
Prior to this change: 
```
BenchmarkEmitRow-16    	  325440	      3463 ns/op	     520 B/op	      16 allocs/op
```

Now:
```
BenchmarkEmitRow-16    	  573620	      1779 ns/op	     235 B/op	       6 allocs/op
```

In addition, memory profile before:
Screen Shot 2021-03-19 at 11 11 13 AM

Memory profile after:
Screen Shot 2021-03-19 at 11 25 43 AM

**Comment by HonoreDB** [comment]
Whoops, nice catch.

**Review by HonoreDB — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Pull request merged**
