### PR TITLE
roachtest: add DELETE/TRUNCATE/DROP test

### PR DESCRIPTION
**Pull request by tbg**
Add a test that exercises a) deletion of a large number of rows and b) the DROP
fast path for a nontrivial schema.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/roachtest/drop.go, line 54 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5sKN3PcQB3E8JCruOg:-L5sKN3PcQB3E8JCruOh:b5otq3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca2b7f646b5c13129530464e7b101a36f3b5cf57/pkg/cmd/roachtest/drop.go#L54)):*
> ```Go
> 			// into one exposed on `roachprod` and returns the result. In the meantime,
> 			// hack around it and just run this on the first node making assumptions
> 			// about the URL. As a consequence, this only works with `-local` right now.
> ```

Getting access to `{pgurl}` isn't sufficient as that URL references IP addresses that you can't connect to remotely. We could provide a facility for getting externally connectable addresses, but the approach I would have taken is to invoke `roachprod ssh <node> ./cockroach sql --url {pgurl} -e "<command>"`. Alternately (equivalently), the new `roachprod sql` command could be exposed in `cluster`. 

---

*[pkg/cmd/roachtest/test.go, line 154 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5sK1AJcpdY-urZGn_H:-L5sK1AJcpdY-urZGn_I:b-p0vyn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca2b7f646b5c13129530464e7b101a36f3b5cf57/pkg/cmd/roachtest/test.go#L154)):*
> ```Go
> 	// status to give an indication of progress.
> 	var tick <-chan time.Time
> 	if parallelism > 1 || local {
> ```

For most local tests the periodic output isn't useful. I'm guessing this new `drop` test is different. Perhaps we should always display the periodic output. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876)*

**Comment by tschottdorf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cmd/roachtest/drop.go, line 54 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5sKN3PcQB3E8JCruOg:-L5t1aWWec3ppODcjybn:b-2ldmzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca2b7f646b5c13129530464e7b101a36f3b5cf57/pkg/cmd/roachtest/drop.go#L54)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Getting access to `{pgurl}` isn't sufficient as that URL references IP addresses that you can't connect to remotely. We could provide a facility for getting externally connectable addresses, but the approach I would have taken is to invoke `roachprod ssh <node> ./cockroach sql --url {pgurl} -e "<command>"`. Alternately (equivalently), the new `roachprod sql` command could be exposed in `cluster`. 
</blockquote></details>

Good point, I'll use that approach for now. Things will yucky quickly once we have to run less trivial SQL, but I'll kick that can down the road.

---

*[pkg/cmd/roachtest/test.go, line 154 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5sK1AJcpdY-urZGn_H:-L5t2w2BiSOoIm0rh_-g:b-fa6g6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca2b7f646b5c13129530464e7b101a36f3b5cf57/pkg/cmd/roachtest/test.go#L154)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

For most local tests the periodic output isn't useful. I'm guessing this new `drop` test is different. Perhaps we should always display the periodic output. 
</blockquote></details>

That makes sense to me. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876)*

**Comment by tschottdorf** [comment]
Ok, this test code is now in good working order. The test itself however, fails rather wildly:

```
[   9] drop/tpcc/w=100/nodes=9: DELETE FROM tpcc.stock (24s)
Error: driver: bad connection
```

```
I180222 10:07:17.912638 176 server/status/runtime.go:219  [n1] runtime stats: 3.9 GiB RSS,
 294 goroutines, 418 MiB/978 MiB/1.4 GiB GO alloc/idle/total, 2.3 GiB/2.6 GiB CGO alloc/to
tal, 463310.85cgo/sec, 0.67/0.05 %(u/s)time, 0.00 %gc (6x)
fatal error: runtime: out of memory
```

@spencerkimball shouldn't this work? @bdarnell [seemed to think so](https://gitter.im/cockroachdb/cockroach?at=5a85e663f283b8e54668791d).

**Comment by spencerkimball** [comment]
Good question and good test, because I didn't do anything specific to verify that memory consumption remained constant. Is it possible to get a heap profile?

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/roachtest/drop.go, line 54 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5sKN3PcQB3E8JCruOg:-L5xf3qpc3GYccZyK_VO:b-a7eee7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca2b7f646b5c13129530464e7b101a36f3b5cf57/pkg/cmd/roachtest/drop.go#L54)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Good point, I'll use that approach for now. Things will yucky quickly once we have to run less trivial SQL, but I'll kick that can down the road.
</blockquote></details>

It isn't getting punted very far: Dan just added `roachprod pgurl --external <cluster>` and he's adding a method to `cluster` to facilitate access. 

---

*[pkg/cmd/roachtest/drop.go, line 27 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5xgNcnnWSKiTI3J0gh:-L5xgNcnnWSKiTI3J0gi:bu0ygn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/146d76c622f905379f05afcc60cd6a7430d44af8/pkg/cmd/roachtest/drop.go#L27)):*
> ```Go
> func init() {
> 	// TODO(tschottdorf): rearrange all tests so that their synopses are available
> 	// via godoc and (some variation on) `roachtest run <testname> --help`.
> ```

Can you file an issue about this? I've been wondering if the interface for registering tests is too narrow. Perhaps we should view this more like how `cobra` commands are registered. That is, there is a `cobra.Command` struct that you file in. Easy to go overboard here.

---

*[pkg/cmd/roachtest/drop.go, line 63 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5xfgM5CaH7Onyj8onb:-L5xfgM5CaH7Onyj8onc:b-2fag1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/146d76c622f905379f05afcc60cd6a7430d44af8/pkg/cmd/roachtest/drop.go#L63)):*
> ```Go
> gc:
>   ttlseconds: 1
> '`
> ```

The newlines in this string will display poorly in a status message. I wonder if `test.Status` should truncate at the first newline.

---

*[pkg/cmd/roachtest/drop.go, line 74 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5xfuJ-e7LRNybcE3LC:-L5xfuJ-e7LRNybcE3LD:b-4rgycj) ([raw file](https://github.com/cockroachdb/cockroach/blob/146d76c622f905379f05afcc60cd6a7430d44af8/pkg/cmd/roachtest/drop.go#L74)):*
> ```Go
> 	tests.Add("drop/tpcc/w=100/nodes=9", func(t *test) {
> 		// NB: this is likely not going to work out in `-local` mode. Edit the
> 		// numbers during iteration.
> ```

Other tests use `ifLocal`, though that function takes string arguments. Would be nice to figure out a better mechanism, but conditioning the values on `local` is fine in the short term.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-:-L5xgGe6YHkOzwR-SbvW:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/roachtest/drop.go, line 54 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5sKN3PcQB3E8JCruOg:-L5xf3qpc3GYccZyK_VO:b-a7eee7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca2b7f646b5c13129530464e7b101a36f3b5cf57/pkg/cmd/roachtest/drop.go#L54)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Good point, I'll use that approach for now. Things will yucky quickly once we have to run less trivial SQL, but I'll kick that can down the road.
</blockquote></details>

It isn't getting punted very far: Dan just added `roachprod pgurl --external <cluster>` and he's adding a method to `cluster` to facilitate access. 

---

*[pkg/cmd/roachtest/drop.go, line 27 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5xgNcnnWSKiTI3J0gh:-L5xgNcnnWSKiTI3J0gi:bu0ygn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/146d76c622f905379f05afcc60cd6a7430d44af8/pkg/cmd/roachtest/drop.go#L27)):*
> ```Go
> func init() {
> 	// TODO(tschottdorf): rearrange all tests so that their synopses are available
> 	// via godoc and (some variation on) `roachtest run <testname> --help`.
> ```

Can you file an issue about this? I've been wondering if the interface for registering tests is too narrow. Perhaps we should view this more like how `cobra` commands are registered. That is, there is a `cobra.Command` struct that you file in. Easy to go overboard here.

---

*[pkg/cmd/roachtest/drop.go, line 63 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5xfgM5CaH7Onyj8onb:-L5xfgM5CaH7Onyj8onc:b-2fag1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/146d76c622f905379f05afcc60cd6a7430d44af8/pkg/cmd/roachtest/drop.go#L63)):*
> ```Go
> gc:
>   ttlseconds: 1
> '`
> ```

The newlines in this string will display poorly in a status message. I wonder if `test.Status` should truncate at the first newline.

---

*[pkg/cmd/roachtest/drop.go, line 74 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5xfuJ-e7LRNybcE3LC:-L5xfuJ-e7LRNybcE3LD:b-4rgycj) ([raw file](https://github.com/cockroachdb/cockroach/blob/146d76c622f905379f05afcc60cd6a7430d44af8/pkg/cmd/roachtest/drop.go#L74)):*
> ```Go
> 	tests.Add("drop/tpcc/w=100/nodes=9", func(t *test) {
> 		// NB: this is likely not going to work out in `-local` mode. Edit the
> 		// numbers during iteration.
> ```

Other tests use `ifLocal`, though that function takes string arguments. Would be nice to figure out a better mechanism, but conditioning the values on `local` is fine in the short term.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-:-L5xgGe6YHkOzwR-SbvW:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/roachtest/drop.go, line 54 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5sKN3PcQB3E8JCruOg:-L5yV8DyeCpv176tkAoR:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca2b7f646b5c13129530464e7b101a36f3b5cf57/pkg/cmd/roachtest/drop.go#L54)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It isn't getting punted very far: Dan just added `roachprod pgurl --external <cluster>` and he's adding a method to `cluster` to facilitate access. 
</blockquote></details>

:thumbsup: 

---

*[pkg/cmd/roachtest/drop.go, line 27 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5xgNcnnWSKiTI3J0gh:-L5yUUl-x2R88lBohWM6:b-6fw5eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/146d76c622f905379f05afcc60cd6a7430d44af8/pkg/cmd/roachtest/drop.go#L27)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you file an issue about this? I've been wondering if the interface for registering tests is too narrow. Perhaps we should view this more like how `cobra` commands are registered. That is, there is a `cobra.Command` struct that you file in. Easy to go overboard here.
</blockquote></details>

Done, https://github.com/cockroachdb/cockroach/issues/22942.

---

*[pkg/cmd/roachtest/drop.go, line 63 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5xfgM5CaH7Onyj8onb:-L5yV7OdW_di9eLDkThe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/146d76c622f905379f05afcc60cd6a7430d44af8/pkg/cmd/roachtest/drop.go#L63)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The newlines in this string will display poorly in a status message. I wonder if `test.Status` should truncate at the first newline.
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/drop.go, line 74 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5xfuJ-e7LRNybcE3LC:-L5yktNP-giJw2MTYqV4:b-8wgbxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/146d76c622f905379f05afcc60cd6a7430d44af8/pkg/cmd/roachtest/drop.go#L74)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Other tests use `ifLocal`, though that function takes string arguments. Would be nice to figure out a better mechanism, but conditioning the values on `local` is fine in the short term.
</blockquote></details>

I gated this on `local` now and am printing a message that the actual numbers are being adjusted. I don't want the test list to depend on `local` (just in case that was your original suggestion).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876)*

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cmd/roachtest/drop.go, line 74 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876#-L5xfuJ-e7LRNybcE3LC:-L5yvTaKUKrvK8Ah3B2H:bx5mlnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/146d76c622f905379f05afcc60cd6a7430d44af8/pkg/cmd/roachtest/drop.go#L74)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I gated this on `local` now and am printing a message that the actual numbers are being adjusted. I don't want the test list to depend on `local` (just in case that was your original suggestion).
</blockquote></details>

The change you made is what I was suggesting. See `kv.go` and the use of `ifLocal` to reduce concurrency and duration when running locally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22876)*

**Comment by tschottdorf** [comment]
TFTRs! I pinged #17921 which, when fixed, should also fix this test.

@petermattis do we have nightlies for this already? What do I do to set it up for this one (happy to document that as well).

**Comment by danhhz** [comment]
Every registered test (`tests.Add`) is currently run nightly so you should be good to go!

**Comment by petermattis** [comment]
> @petermattis do we have nightlies for this already? What do I do to set it up for this one (happy to document that as well).

All of the `roachtest` tests are run automatically by `build/roachtest-nightly.sh`. We might want to disable this test until it reliably passes.

**Comment by tschottdorf** [comment]
Also filed a follow-up to make sure the disk space is reclaimed: https://github.com/cockroachdb/cockroach/issues/22956

**Pull request merged**
