### PR TITLE
storage: refactor to expose raft-consistent state

### PR DESCRIPTION
**Pull request by tbg**
One of a few more refactors to come while tackling #6290.

Make it obvious which variables are consistently updated through Raft with an associated on-disk state. In the process, removes `rangeStats`.

More follow-up refactors are planned, but this one is big enough and should highlight the direction.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7192)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: except for atomicity of stats updates

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> #### storage: refactor to expose raft\-consistent state
> 
> One of a few more refactors to come while tackling #6290.
> 
> 
> 
> Make it obvious which variables are consistently updated through Raft with an associated on-disk state. In the process, removes `rangeStats`.
> 
> 
> 
> More follow-up refactors are planned, but this one is big enough and should highlight the direction.
> 
> 
> 
</details>


---

Reviewed 6 of 6 files at r1, 14 of 14 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/client_split_test.go, line 436 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAIjOeF7h8Pe6hpZ4y:-KKAIjOfqLQuOp1y4ETU:1647197056) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/client_split_test.go#L436)):*
> ```Go
> 		t.Fatalf("failed to verify range's stats before split: %v", err)
> 	}
> 	inMemMS := rng.GetMVCCStats()
> ```

reduce scope?

---

*[storage/replica.go, line 501 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAHc9mnfBLt_LFo3fC:-KKAHc9tFssEr1Fuz7Lt:1759863638) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/replica.go#L501)):*
> ```Go
> }
> 
> func setMVCCStats(eng engine.ReadWriter, rangeID roachpb.RangeID, newMS engine.MVCCStats) error {
> ```

nit: s/set/save/ to make this the obvious corollary of `load`

---

*[storage/replica_command.go, line 2181 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAJ5hSgMcRjzSgoBRQ:-KKAJ5hSgMcRjzSgoBRR:-1209636346) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/replica_command.go#L2181)):*
> ```Go
> 		return util.Errorf("unable to write MVCC stats: %s", err)
> 	}
> 	r.mu.Lock()
> ```

nit: lock should be held during mvcc ops as is done elsewhere

there are a number of places in this PR where in-memory updates are not atomic with on-disk updates. I think this wants a function.

---

*[storage/replica_command.go, line 2476 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAJFmc_kpJKxwqBQCD:-KKAJFmc_kpJKxwqBQCE:-446598547) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/replica_command.go#L2476)):*
> ```Go
> 
> 	// Set stats for updated range (in-memory updated under lock below).
> 	if err = setMVCCStats(batch, r.RangeID, mergedMS); err != nil {
> ```

`err :=` while you're here

---

*[storage/replica_raftstorage.go, line 737 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAK59Ow__ZwO4OUFBv:-KKAK59Ow__ZwO4OUFBw:-455603788) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ce0b113b1631e44972a317439610925f5192b5/storage/replica_raftstorage.go#L737)):*
> ```Go
> 	}
> 
> 	// The next line sets the persisted last index to the last applied index.
> ```

stale

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-:-KKAKFzZk2sZ_KYazw70:2104643372)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[storage/client_split_test.go, line 436 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAIjOeF7h8Pe6hpZ4y:-KKAPfrz15jTr04vkN5K:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/client_split_test.go#L436)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> reduce scope?
</details>
Done.

---

*[storage/replica.go, line 501 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAHc9mnfBLt_LFo3fC:-KKAQcZ4fdewDEKbR9_O:839801250) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/replica.go#L501)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: s/set/save/ to make this the obvious corollary of `load`
</details>
`load` and `set` is the current language used for this throughout. I'll refactor this more in a future PR (which will also make sure that in-memory and on-disk states updated in a more coupled manner)

---

*[storage/replica_command.go, line 2181 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAJ5hSgMcRjzSgoBRQ:-KKARF2f7orByaIc5q31:283514631) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/replica_command.go#L2181)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: lock should be held during mvcc ops as is done elsewhere
> 
> there are a number of places in this PR where in-memory updates are not atomic with on-disk updates. I think this wants a function.
</details>
What's your point about the locks?
Re: non-atomicity, I agree but this preserves the status quo and I'm going to clean this up in future PRs (which will remove `batch.Defer()` and express all side effects properly).

---

*[storage/replica_command.go, line 2476 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAJFmc_kpJKxwqBQCD:-KKAPzRv1ZxD0dlNtjQB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/replica_command.go#L2476)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `err :=` while you're here
</details>
Done.

---

*[storage/replica_raftstorage.go, line 737 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAK59Ow__ZwO4OUFBv:-KKAQWB-F_23bVHW4twG:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1ce0b113b1631e44972a317439610925f5192b5/storage/replica_raftstorage.go#L737)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> stale
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192)*

**Comment by tamird** [comment]
Reviewed 14 of 14 files at r5, 14 of 14 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/gc_queue_test.go, line 140 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAU7YmSsvYtYvgCcda:-KKAU7YmSsvYtYvgCcdb:-1899744838) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a48484d3534e4ad83d89feda61a23ffcf6767d3/storage/gc_queue_test.go#L140)):*
> ```Go
> 		}
> 		func() {
> 			tc.rng.mu.Lock()
> ```

here the lock is held over in-memory and on-disk update

---

*[storage/replica_command.go, line 2181 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAJ5hSgMcRjzSgoBRQ:-KKATpp7UiTDQPWq7kT5:-1957114913) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/replica_command.go#L2181)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> What's your point about the locks?
> Re: non-atomicity, I agree but this preserves the status quo and I'm going to clean this up in future PRs (which will remove `batch.Defer()` and express all side effects properly).
</details>
The point about the lock is that the lock is not held here during setMVCCStats, but in some other places, it is. I've left another comment to point out one such location.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 2181 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAJ5hSgMcRjzSgoBRQ:-KKAW0Rz9cNEZi5ErSGQ:21441290) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/replica_command.go#L2181)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> The point about the lock is that the lock is not held here during setMVCCStats, but in some other places, it is. I've left another comment to point out one such location.
</details>
The location you've pointed out is crudely refactored test code in which the lock is mainly held because it writes straight to the engine (but even that's not a particularly good reason; the test is doing bad things™). That is not the case here and the only thing that expanding lock scope here is hold the lock over potential disk i/o. Am I missing something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192)*

**Comment by tamird** [comment]
did you mean to use that last commit as a fixup?

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> :lgtm: except for atomicity of stats updates
</details>


---

Reviewed 10 of 14 files at r11, 1 of 2 files at r12, 2 of 2 files at r13, 1 of 1 files at r14.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/gc_queue_test.go, line 140 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAU7YmSsvYtYvgCcda:-KKAXFjlbvv-n618fz2C:1158288135) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a48484d3534e4ad83d89feda61a23ffcf6767d3/storage/gc_queue_test.go#L140)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> here the lock is held over in-memory and on-disk update
</details>
can you add a comment about why the lock is held over disk io here?

---

*[storage/replica_command.go, line 2181 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAJ5hSgMcRjzSgoBRQ:-KKAXTe62MJ2iYvr2Jsz:-1439803136) ([raw file](https://github.com/cockroachdb/cockroach/blob/4423b44f7570a3153480b517aa180b971a8f8dc7/storage/replica_command.go#L2181)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> The location you've pointed out is crudely refactored test code in which the lock is mainly held because it writes straight to the engine (but even that's not a particularly good reason; the test is doing bad things™). That is not the case here and the only thing that expanding lock scope here is hold the lock over potential disk i/o. Am I missing something?
</details>
seems to me that this pattern is generally susceptible to write skew, though not in this instance. 

I've left comments on the "crudely refactored test code".

---

*[storage/split_queue_test.go, line 84 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAXhaPRLpKDflXNmuX:-KKAXhaPRLpKDflXNmuY:1158288135) ([raw file](https://github.com/cockroachdb/cockroach/blob/6875481520946f1474d10177b970a103ff3892ae/storage/split_queue_test.go#L84)):*
> ```Go
> 		func() {
> 			ms := engine.MVCCStats{KeyBytes: test.bytes}
> 			tc.rng.mu.Lock()
> ```

can you add a comment about why the lock is held over disk io here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-:-KKAX5X1jgQcVYY5fZ0h:-446196594)*

**Comment by tschottdorf** [comment]
Yep, fixed.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> did you mean to use that last commit as a fixup?
</details>


---

Review status: 10 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/gc_queue_test.go, line 140 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAU7YmSsvYtYvgCcda:-KKA_uZj6oOzcqtBZl4C:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a48484d3534e4ad83d89feda61a23ffcf6767d3/storage/gc_queue_test.go#L140)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you add a comment about why the lock is held over disk io here?
</details>
Done.

---

*[storage/split_queue_test.go, line 84 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAXhaPRLpKDflXNmuX:-KKA_wfOwMxokeW5pPS7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6875481520946f1474d10177b970a103ff3892ae/storage/split_queue_test.go#L84)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you add a comment about why the lock is held over disk io here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-:-KKAYukfHut-sSkmsXLb:-419528115)*

**Comment by tschottdorf** [comment]
@arjunravinarayan, you might also want to take a look (mostly to get into the groove of Raft-related code reviews).

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Yep, fixed.
</details>


---

Review status: 10 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-:-KKAaVmoZFELKxvurTEU:-1812884135)*

**Comment by tamird** [comment]
Reviewed 2 of 5 files at r18, 1 of 2 files at r19, 2 of 2 files at r20.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192)*

**Comment by bdarnell** [comment]
:lgtm:

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> @arjunravinarayan, you might also want to take a look (mostly to get into the groove of Raft-related code reviews).
</details>


---

Reviewed 1 of 6 files at r1, 8 of 14 files at r11, 1 of 1 files at r14, 2 of 5 files at r18, 1 of 2 files at r19, 2 of 2 files at r20.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/gc_queue_test.go, line 140 \[r20\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKB-G10_gYvjurwGxcL:-KKB-G115khhlGRH3d0V:-1009939878) ([raw file](https://github.com/cockroachdb/cockroach/blob/6143a247c8fa50db2dada4bec8c1021b3c536d79/storage/gc_queue_test.go#L140)):*
> ```Go
> 		}
> 		func() {
> 			// Hold lock throughout to reduce chance of random commands
> ```

Does it just "reduce the chance", or does it completely prevent the inconsistency? (here and in split_queue_test.go)  It looks like this could still race with applying a raft command, which does a read/modify/write of the stats with two separate locks. Maybe we should install a blocking TestingCommandFilter to make sure that nothing else happens behind our backs. 

---

*[storage/replica.go, line 174 \[r20\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAxcyA5we7EiJvnUJX:-KKAxcyA5we7EiJvnUJY:-542897579) ([raw file](https://github.com/cockroachdb/cockroach/blob/6143a247c8fa50db2dada4bec8c1021b3c536d79/storage/replica.go#L174)):*
> ```Go
> // TODO(tschottdorf): unified method to update both in-mem and on-disk state,
> // similar to how loadState unifies restoring from storage.
> type state struct {
> ```

`s/state/rangeState/`? Otherwise this is `storage.state`, which is a little vague.

---

*[storage/replica.go, line 237 \[r20\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAy3KvrzQ7iM2GD1Zr:-KKAy3KwVUoMOUxXozG9:-1283034709) ([raw file](https://github.com/cockroachdb/cockroach/blob/6143a247c8fa50db2dada4bec8c1021b3c536d79/storage/replica.go#L237)):*
> ```Go
> // as appropriate.
> type Replica struct {
> 	// TODO(tschottdorf): Duplicates r.mu.stats.desc.RangeID; revisit that.
> ```

s/stats/state/

The duplication is intentional because it allows us to access this never-changing value without any locking. I'm not sure if we currently access the range ID separately from the full descriptor often enough for this to be worthwhile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-:-KKB0subeKaXkUGOc2yR:1417088721)*

**Comment by tschottdorf** [comment]
TFTRs!

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 1 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/gc_queue_test.go, line 140 \[r20\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKB-G10_gYvjurwGxcL:-KKBTE80dy3cNcl2B0bX:63913898) ([raw file](https://github.com/cockroachdb/cockroach/blob/6143a247c8fa50db2dada4bec8c1021b3c536d79/storage/gc_queue_test.go#L140)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Does it just "reduce the chance", or does it completely prevent the inconsistency? (here and in split_queue_test.go)  It looks like this could still race with applying a raft command, which does a read/modify/write of the stats with two separate locks. Maybe we should install a blocking TestingCommandFilter to make sure that nothing else happens behind our backs. 
</details>
Yes, this can still race (like the old code). I'm going to leave as is for now (if it suddenly becomes flaky, it should be pretty obvious why).

---

*[storage/replica.go, line 174 \[r20\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAxcyA5we7EiJvnUJX:-KKBUMATDTUjmmo4cTbj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6143a247c8fa50db2dada4bec8c1021b3c536d79/storage/replica.go#L174)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> `s/state/rangeState/`? Otherwise this is `storage.state`, which is a little vague.
</details>
Done.

---

*[storage/replica.go, line 237 \[r20\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-KKAy3KvrzQ7iM2GD1Zr:-KKBUSR1LdPiNZZO0n0R:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6143a247c8fa50db2dada4bec8c1021b3c536d79/storage/replica.go#L237)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/stats/state/
> 
> The duplication is intentional because it allows us to access this never-changing value without any locking. I'm not sure if we currently access the range ID separately from the full descriptor often enough for this to be worthwhile.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192#-:-KKBUU2y90phsrGf_MpV:2125754307)*

**Comment by tamird** [comment]
Reviewed 11 of 14 files at r22, 1 of 2 files at r23, 1 of 2 files at r24, 1 of 1 files at r25.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7192)*

**Pull request merged**
