### PR TITLE
pgwire: detect, log, and immediately close any cancel requests

### LINKED ISSUE #32973: sql: ensure that a pgwire-level cancellation request (using a cancel msg) prevents a client freeze
**Issue summary** (Added @knz 2018-12-14)

The client tries to cancel its request with a pg cancel message and then gets stuck (until a timeout of 2mn) because the server does not respond. Instead CockroachDB should see the pg cancel message and immediately return an error packet and/or close the connection.

**Describe the problem**

1. Create an insert request.
2. Cancel context when the request is executing.

The request will be terminated exactly in 2 minutes.

**To Reproduce**

```
	dbname := "db" + strconv.Itoa(int(uuid.New().ID()))
	connString := fmt.Sprintf("postgresql://root@localhost:26257/%s?sslmode=disable", dbname)
	db, err := sql.Open("postgres", connString)
	if err != nil {
		panic(err)
	}
	_, err = db.Exec(`CREATE DATABASE ` + dbname)
	if err != nil {
		panic("cannot create database: " + err.Error())
	}

	defer db.Exec(`DROP DATABASE ` + dbname)

	_, err = db.Exec(`CREATE TABLE IF NOT EXISTS table1 (id STRING PRIMARY KEY)`)
	if err != nil {
		panic("cannot create schema: " + err.Error())
	}

	for {
		ctx := context.Background()
		ctx, cancel := context.WithCancel(ctx)
		go func() {
			time.Sleep(15 * time.Millisecond)
			cancel()
		}()
		started := time.Now()
		query := `INSERT INTO table1 (id) VALUES ($1)`
		id := uuid.New().String()

		_, err := db.ExecContext(ctx, query, id)
		if err != nil && err != context.Canceled {
			panic(err)
		}

		fmt.Println("inserted:", time.Since(started))
		if time.Since(started) > 1*time.Second {
			panic("too long")
		}
	}
```

**Expected behavior**
The request should be terminated immediately after the context is canceled.

**Environment:**
 - CCL v2.1.1 @ 2018/11/19 18:24:21 (go1.10.3)
 - Server OS: Debian
 - Golang (database/sql, lib/pq)

### PR DESCRIPTION
**Pull request by madelynnblue**
Previously the cmuxer would not detect pgwire cancel requests as pgwire
and instead hand them off to GRPC causing them to hang. We still don't
support cancel, but it should be handled better by clients now.

Fixes #32973

Release note (bug fix): Cancel requests (via the pgwire protocol) will
now close quickly with an EOF instead of hang (but still don't cancel
the request).

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM with nit on the counter name.

Thank you for the fast response!

**Comment by tbg** [comment]
Were you planning on backporting this? I don't know that we have problems
here concretely, but it would be nice to rule it out. I'm dealing with
unexplainably stuck requests every once in a while.

**Comment by knz** [comment]
I'm :+1: on backporting

**Pull request merged**
