### PR TITLE
sql/types,tree,parser: fix quoting and formatting of UDTs

### LINKED ISSUE #97493: sql/schemachanger: type resolution is broken for case sensitive enums in ADD COLUMN
**Describe the problem**
Case sensitivity is broken for enums in add column type resolution in the declarative schema changer. 

**To Reproduce**

```sql 
CREATE TABLE t (i INT PRIMARY KEY);
CREATE TYPE "MixedCase" AS ENUM ('a', 'b');
ALTER TABLE t ADD COLUMN j "MixedCase";
```

**Additional context**
What was the impact?

```
ERROR: type "mixedcase" does not exist
SQLSTATE: 42704
```

Version Affected: 22.20-22.2.5

Jira issue: CRDB-24725

### PR DESCRIPTION
**Pull request by ajwerner**
This commit fixes bugs when round-tripping sql strings which reference types which need to be quoted.

This bug resulted in bugs in the declarative schema changer for statements such as `ALTER TABLE ... ADD COLUMN` when the referenced type needs to be quoted.

Fixes: #97493

Release note (bug fix): Fixed a bug in `ALTER TABLE ... ADD COLUMN` when the new column name requires quoting due to mixed case or special characters and the statement is not run in an explicit or multi-statement transaction.

Release note (bug fix): Fixed a bug when formatting create statements for user-defined types which require quoting which might prevent those statements from round-tripping.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
it's unfortunate how easy it is to mess up the formatting logic for types, but the new test cases you've added hopefully will go a long way!

thanks for addressing all these. this lgtm, except for a nit and a suggestion for a test

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97514#-:-NOv1ZH1BH_CgizLuJ_9:b3ho2mt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/sem/tree/create.go` line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97514#-NOv2P3e3xTagIR-9A3G:-NOv2P3e3xTagIR-9A3H:b-jrl5fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8f9f8f4571a3bca84a5871c76aba262739137f8/pkg/sql/sem/tree/create.go#L392)):*
> ```Go
> 			ctx.FormatNode(&elem.Label)
> 			ctx.WriteString(" ")
> 			ctx.FormatTypeReference(node.CompositeTypeList[i].Type)
> ```

nit: could use `elem.Type`
___
*[`pkg/sql/types/types.go` line 250 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97514#-NOv33OvBocGWxwYuCWH:-NOv33OvBocGWxwYuCWI:b-g973ov) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8f9f8f4571a3bca84a5871c76aba262739137f8/pkg/sql/types/types.go#L250)):*
> ```Go
> // FQName returns the fully qualified name.
> func (u UserDefinedTypeName) FQName() string {
> 	return FormatTypeName(u)
> ```

i noticed that https://github.com/cockroachdb/cockroach/issues/72241 was fixed already due to the existing FQName implementation.

could you add a test that checks that the new logic that injects different type formatting still addresses this issue?
___
*[`pkg/sql/types/types.go` line 1930 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97514#-NOv3Hmq8taYfXkKfzio:-NOv3Hmq8taYfXkKfzip:bbmp0xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8f9f8f4571a3bca84a5871c76aba262739137f8/pkg/sql/types/types.go#L1930)):*
> ```Go
> var FormatTypeName = fallbackFormatTypeName
> 
> func fallbackFormatTypeName(u UserDefinedTypeName) string {
> ```

nit: is this fallback ever used?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97514)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/tree/create.go` line 392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97514#-NOv2P3e3xTagIR-9A3G:-NOv89zN29hrsWsIYGJJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8f9f8f4571a3bca84a5871c76aba262739137f8/pkg/sql/sem/tree/create.go#L392)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: could use `elem.Type`
</blockquote></details>

Done.
___
*[`pkg/sql/types/types.go` line 250 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97514#-NOv33OvBocGWxwYuCWH:-NOv8EDn6jufZaSunSCo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8f9f8f4571a3bca84a5871c76aba262739137f8/pkg/sql/types/types.go#L250)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i noticed that https://github.com/cockroachdb/cockroach/issues/72241 was fixed already due to the existing FQName implementation.

could you add a test that checks that the new logic that injects different type formatting still addresses this issue?
</blockquote></details>

Done.
___
*[`pkg/sql/types/types.go` line 1930 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97514#-NOv3Hmq8taYfXkKfzio:-NOv8GZ-7GK95iD0X0hE:bqj53zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8f9f8f4571a3bca84a5871c76aba262739137f8/pkg/sql/types/types.go#L1930)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: is this fallback ever used?
</blockquote></details>

replaced with a static string. A panic seems extreme.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by ajwerner** [comment]
blathers backport 22.2

**Pull request merged**
