### PR TITLE
sql: show only constrained cols in fk

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by tamird** [comment]
Since there was previously no test: what did this do before? Please include in the commit message.

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15298#-:-KiWAPMQxdorhDqaWKYv:b-r1zag3)*

**Comment by dt** [comment]
even better, linked to issue.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15298#-:-KiWAh96056-cuWv_HKb:b-khkgco)*

**Comment by tamird** [comment]
Heh, that's better than not linking to the issue, but please also include
the full description of the issue in the commit message. We generally
prefer to save the indirection when reading `git log` or `git blame`.

**Comment by dt** [comment]
@tamird how do you feel about the current commit message wording?

**Comment by knz** [comment]
In commit message: 

contrained -> constrainted

"the rendering changed here didn't get the same treatment." -> 
"the rendering didn't get the same treatment. This patch completes the fix by changing the rendering as well"

LGTM otherwise

**Comment by dt** [comment]
Done.

**Comment by knz** [comment]
:+1: :shipit:

**Pull request merged**
