### PR TITLE
Metrics for range splits & replica adds/removes

### LINKED ISSUE #5651: ui: add metrics for splits/merges/rebalances
We have events for these operations, but no metrics as far as I can tell. Would be good to have a single graph at the node/nodes level containing splits/merges/rebalances.

### PR DESCRIPTION
**Pull request by cuongdo**
This change adds metrics and graphs for the range events that we currently log:
- range split
- range add replica
- range remove replica

Resolves #5651

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5666)

### CODE REVIEW

**Comment by cuongdo** [comment]
skitch

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/log_test.go, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5666#-KE1sX-gxFjLY7zR9Uxs:-KE1sX-hNjMo30TBDzZb:-1271826375) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4b7cd9e0e6bfb1e61b4a4a17663cfc783fd4ffc/storage/log_test.go#L77)):*
Did you intend to leave this in?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5666#-:-KE1smfxeNb_Bz2oVwZS:1417088721)*

**Comment by cuongdo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/log_test.go, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5666#-KE1sX-gxFjLY7zR9Uxs:-KE2-oBnGILDR6czy4Gt:-916392897) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4b7cd9e0e6bfb1e61b4a4a17663cfc783fd4ffc/storage/log_test.go#L77)):*
Nope, it's gone now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5666)*

**Comment by tamird** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[storage/log.go, line 101 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5666#-KE218Cp-Rsl6mB26rg8:-KE218CqZMgzrvUisZo9:-2017614656) ([raw file](https://github.com/cockroachdb/cockroach/blob/737bf153f5cbc7890649773ade412bb33281d851/storage/log.go#L101)):*
*the* range log?

---

*[storage/log_test.go, line 122 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5666#-KE21iReEsvTT_HRza4W:-KE21iReEsvTT_HRza4X:548811487) ([raw file](https://github.com/cockroachdb/cockroach/blob/737bf153f5cbc7890649773ade412bb33281d851/storage/log_test.go#L122)):*
This code is copied from elsewhere - rather than duplicating this comment (and the inherent assumption), can you extract a method?

---

*[storage/log_test.go, line 132 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5666#-KE21rUnO2yIAgShIJIQ:-KE21rUnO2yIAgShIJIR:-955850704) ([raw file](https://github.com/cockroachdb/cockroach/blob/737bf153f5cbc7890649773ade412bb33281d851/storage/log_test.go#L132)):*
minimimum is probably not the word you wanted

---

*[storage/log_test.go, line 133 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5666#-KE21y1pnGSHPoFXaBcH:-KE21y1pnGSHPoFXaBcI:1344987343) ([raw file](https://github.com/cockroachdb/cockroach/blob/737bf153f5cbc7890649773ade412bb33281d851/storage/log_test.go#L133)):*
remove the comma

---

*[storage/log_test.go, line 180 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5666#-KE225upnRLGzSSBiD3m:-KE225upnRLGzSSBiD3n:-1832323248) ([raw file](https://github.com/cockroachdb/cockroach/blob/737bf153f5cbc7890649773ade412bb33281d851/storage/log_test.go#L180)):*
i think we typically pad with spaces `/* foo */`. Also the singular/plural mix here is odd, if intentional.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5666)*

**Pull request merged**
