### PR TITLE
obsservice: connect to the sink cluster and run migrations 

### PR DESCRIPTION
**Pull request by andreimatei**
This patch adds a --sink-pgurl flag to the obsservice for the connection
string to the sink cluster. It uses it to run SQL schema migrations, of
which there is a single dummy one.

We're using https://github.com/pressly/goose for schema migrations;
it can be used both as a cmdline binary, and as a library (we use it
as a library), and it supports migrations written as either SQL files,
or as a set of go functions (for the more involved ones, I guess).

Release note: None

### CODE REVIEW

**Review by dhartunian — APPROVED** [review]
:lgtm: approach looks straightforward to me :)

> Reviewed 13 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82695#-:-N4iOVuP9kuqBwT0lZ93:b-wqardw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Review by abarganier — APPROVED** [review]
Nice and easy to follow! :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82695#-:-N55ix7x8PtZ0VLHjg5l:b-4au5ec)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82695#-:-N5As2IQC3bn5FvDtOqz:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82695#-:-N5Goa5jAvT88Dk5x0tD:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

**Pull request merged**
