### PR TITLE
kv: cancel outstanding RPCs when DistSender.sendRPC returns

### LINKED ISSUE #10968: stability: goroutine spike after restarting down node
On `blue`, when a node is killed and kept down for a few minutes, upon restart it sees a spike in goroutines:

screen shot 2016-11-22 at 3 27 19 pm

All 3 spikes below correspond to a node being restarted. The bulk of the goroutines have a single stack trace:

```
6644: select [0~1 minutes] [Created by grpc.(*Server).serveStreams.func1 @ server.go:423]
    storage             replica.go:921               (*Replica).redirectOnOrAcquireLease(*, #84539, *, *)
    storage             replica.go:1808              (*Replica).tryAddWriteCmd(*, #84539, *, *, *, #131, *, *, 0, *, ...)
    storage             replica.go:1706              (*Replica).addWriteCmd(*, #84539, *, *, *, #131, *, *, 0, *, ...)
    storage             replica.go:1173              (*Replica).Send(*, #84539, *, *, *, #131, *, *, 0, *, ...)
    storage             store.go:2387                (*Store).Send(#1222, #84539, *, *, *, #131, *, *, 0, *, ...)
    storage             stores.go:187                (*Stores).Send(#305, #84539, *, 0, 0, #131, *, *, 0, *, ...)
    server              node.go:819                  (*Node).batchInternal.func1(0, 0)
    stop                stopper.go:245               (*Stopper).RunTaskWithErr(#550, *, 0, 0)
    server              node.go:830                  (*Node).batchInternal(#407, #84539, *, *, *, *, *)
    server              node.go:850                  (*Node).Batch(#407, #84539, *, *, *, *, *)
    roachpb             api.pb.go:1522               _Internal_Batch_Handler(#39, #407, #84539, *, *, 0, 0, 0, *, *)
    grpc                server.go:611                (*Server).processUnaryRPC(#676, #97, *, *, #753, #65, 0, 0, 0)
    grpc                server.go:769                (*Server).handleStream(#676, #97, *, *, 0)
    grpc                server.go:422                (*Server).serveStreams.func1.1(*, #676, #97, *, *)
```

This count is somewhat surprising because the local `block_writer` will only send 64 concurrent requests, so other nodes must be directing traffic at this newly restarted node. I instrumented the binary at some point and could definitively see that the requests were coming from remote notes. In #10427 I experiment with increasing `kv.defaultSendNextTimeout` without noticeable improvement, but perhaps it is worth trying that again. Another question is why these goroutines are blocked for so long. Aren't the RPCs cancelled eventually?

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #10968

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10970)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. Nice.

**Comment by tamird** [comment]
Actually, can you inline the interesting bits of #10968 into the commit message?

**Review by a-robinson — APPROVED** [review]
Nice find!

**Comment by petermattis** [comment]
Update the commit message.

**Comment by bdarnell** [comment]
Nice. This also makes things work the way I said they were supposed to in https://github.com/cockroachdb/cockroach/issues/10427#issuecomment-262265074

**Pull request merged**
