### PR TITLE
opt: Add additional decorrelation rules + tests

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR adds additional decorrelation rules, as well as a suite of benchmark/ORM queries that require decorrelation to work.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/norm/testdata/rules/test, line 209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCVC-TX3MIdx_tCDjaN:-LCVC-TX3MIdx_tCDjaO:b-uht513) ([raw file](https://github.com/cockroachdb/cockroach/blob/436c82941c17b0db0abb84785781a6e8d60d673f/pkg/sql/opt/norm/testdata/rules/test#L209)):*
> ```
>       └── l_linenumber int not null
> 
> opt
> ```

This is tpch query 20, right? Is there a reason you're not identifying it as such and/or placing it in a file named `tpch`?

Update: or perhaps this file was included by accident and is for your own testing purposes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477)*

**Comment by petermattis** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/xform/testdata/external/tpch, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCVE88f-fU8xesfFkQp:-LCVE88f-fU8xesfFkQq:bitrvc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/436c82941c17b0db0abb84785781a6e8d60d673f/pkg/sql/opt/xform/testdata/external/tpch#L387)):*
> ```
>  │    │         │    ├── grouping columns: rownum:49(int!null)
>  │    │         │    ├── keys: (49)
>  │    │         │    ├── left-join-apply
> ```

This seems to be the only apply remaining in any of the tpch query plans. Is removing it part of any of the TODOs above?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477)*

**Comment by andy-kimball** [comment]
Review status: 0 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/norm/testdata/rules/test, line 209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCVC-TX3MIdx_tCDjaN:-LCVG3Hk-cvPOMe9MULk:b-gnbu44) ([raw file](https://github.com/cockroachdb/cockroach/blob/436c82941c17b0db0abb84785781a6e8d60d673f/pkg/sql/opt/norm/testdata/rules/test#L209)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is tpch query 20, right? Is there a reason you're not identifying it as such and/or placing it in a file named `tpch`?

Update: or perhaps this file was included by accident and is for your own testing purposes.
</blockquote></details>

Ah, whoops, yes, I should have removed this. I use this file when I want to run a specific test in isolation.

---

*[pkg/sql/opt/xform/testdata/external/tpch, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCVE88f-fU8xesfFkQp:-LCVGbiO10B0-eZm7mXt:b-uf13f2) ([raw file](https://github.com/cockroachdb/cockroach/blob/436c82941c17b0db0abb84785781a6e8d60d673f/pkg/sql/opt/xform/testdata/external/tpch#L387)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This seems to be the only apply remaining in any of the tpch query plans. Is removing it part of any of the TODOs above?
</blockquote></details>

The failure to decorrelate is caused by the `RowNumber` operator that's introduced to the tree in order to provide a unique key. While I do mention the `RowNumber` in the TODO, I'll add another line to remind me to add a decorrelation rule that deals with `RowKey`. `RowKey` is a new operator I plan to add that can be more freely reordered, because it doesn't care about what number gets assigned to what row, just that each row has a unique number.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477)*

**Comment by RaduBerinde** [comment]
Great stuff! Still looking over the new rules. Unfortunately you will have to fix some conflicts with my projection change.

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/ops/scalar.opt, line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZMU4x7TMojG89bffU:-LCZMU4x7TMojG89bffV:btzrfqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a173477bf3b28d239ccd30cb064db461719a2f/pkg/sql/opt/ops/scalar.opt#L609)):*
> ```
> }
> 
> # FirstAgg returns the first non-null value in the grouping set, or null if
> ```

Lets rename to `AnyNotNullAgg` since that's all we need. Also mention that this is particularly useful for "passing through" the value of a column which we know is constant within any group.

---

*[pkg/sql/opt/xform/testdata/external/tpch, line 209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZRnKo2Qrx5wLL3Wm9:-LCZRnKo2Qrx5wLL3WmA:brty5t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ba6635c22b42481571c085d3cb6e337f88ade5/pkg/sql/opt/xform/testdata/external/tpch#L209)):*
> ```
>       └── l_linenumber int not null
> 
> # --------------------------------------------------
> ```

Having all these queries here is great!

---

*[pkg/sql/opt/xform/testdata/external/tpch, line 2438 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZR8uz5BqMETBEm2LR:-LCZR8uz5BqMETBEm2LS:b-t8usha) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ba6635c22b42481571c085d3cb6e337f88ade5/pkg/sql/opt/xform/testdata/external/tpch#L2438)):*
> ```
> WHERE
> 	s_suppkey IN (
> 		SELECT
> ```

[nit] tabs are kind of annoying in these files, I'd just do a mass conversion to 2 or 4 spaces

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-:-LCZQch4EqHxriVd6NAP:blbtc3t)*

**Comment by rytaft** [comment]
Looks great! I'll take another look after you fix the conflicts with Radu's change.

---

Reviewed 15 of 15 files at r1, 4 of 5 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/norm/decorrelate.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZZDywEu8ATCe-ih6X:-LCZZDywEu8ATCe-ih6Y:b-199ebo) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a173477bf3b28d239ccd30cb064db461719a2f/pkg/sql/opt/norm/decorrelate.go#L196)):*
> ```Go
> }
> 
> // constructScalarGroupByLeftJoin maps an (InnerJoinApply (GroupBy)) expression
> ```

`constructScalarGroupByLeftJoin` -> `hoistCorrelatedScalarGroupBy`

---

*[pkg/sql/opt/norm/decorrelate.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZTYS4AxsRko7sx84H:-LCZTYS4AxsRko7sx84I:b-qhciv) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a173477bf3b28d239ccd30cb064db461719a2f/pkg/sql/opt/norm/decorrelate.go#L230)):*
> ```Go
> //   HAVING left.y = 10
> //
> // FIRST_AGG is an internal aggregation function that returns the first non-null
> ```

What if the only value is NULL? 

I think this might be clearer if you say something like: "...Since the grouping column(s) are a key of "left", FIRST_AGG will return the first and only value of the given column..."

---

*[pkg/sql/opt/norm/factory.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZVSZ6EDs5YEPTvFyj:-LCZVSZ6EDs5YEPTvFyk:b-w8d21p) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a173477bf3b28d239ccd30cb064db461719a2f/pkg/sql/opt/norm/factory.go#L470)):*
> ```Go
> // of the fewest columns. If there are multiple keys with the same number of
> // columns, any one of them may be returned. If there are no strong keys in the
> // group, then shortestKey panics.
> ```

Doesn't seem like it panics...

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZYwxn7G22O1xql9Qn:-LCZYwxn7G22O1xql9Qo:b-2t80hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a173477bf3b28d239ccd30cb064db461719a2f/pkg/sql/opt/norm/rules/decorrelate.opt#L170)):*
> ```
> #   HAVING left.y = 10
> #
> # An ordinality column only needs to be synthesized if "left" does not already
> ```

It would be helpful to add this paragraph to the other matching comment for `hoistCorreatedScalarGroupBy`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-:-LCZcBTQ3TufsoIhpWXY:boo2ztg)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/xform/testdata/external/tpch, line 209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZRnKo2Qrx5wLL3Wm9:-LCZcNAPC-A7iety6Fhb:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ba6635c22b42481571c085d3cb6e337f88ade5/pkg/sql/opt/xform/testdata/external/tpch#L209)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Having all these queries here is great!
</blockquote></details>

+1

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477)*

**Comment by rytaft** [comment]
Review status: 3 of 32 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/opt/xform/testdata/external/liquibase, line 230 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LC_id9CAQLx5sJh9c18:-LC_id9CAQLx5sJh9c19:b-4ziojy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1999a46be463f4b7ce17a6f2ed781c0db326cdad/pkg/sql/opt/xform/testdata/external/liquibase#L230)):*
> ```
>       └── oid oid not null (storing)
> 
> # TODO(andyk): Enable once subquery data source name resolution bug is fixed.
> ```

That change is merged now.

---

*[pkg/sql/opt/xform/testdata/external/navicat, line 230 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LC_ijQ-3odtxzRv4Ny_:-LC_ijQ-3odtxzRv4Nya:bagpbpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1999a46be463f4b7ce17a6f2ed781c0db326cdad/pkg/sql/opt/xform/testdata/external/navicat#L230)):*
> ```
>       └── oid oid not null (storing)
> 
> # TODO(andyk): Enable once subquery data source name resolution bug is fixed.
> ```

Fix is merged

---

*[pkg/sql/opt/xform/testdata/external/tpch, line 2536 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LC_iybV-4pdZ0SXcJGc:-LC_iybW1VY4iu4ddoX5:bagpbpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1999a46be463f4b7ce17a6f2ed781c0db326cdad/pkg/sql/opt/xform/testdata/external/tpch#L2536)):*
> ```
> #
> # TODO:
> #   1. Recognize data source names in subqueries
> ```

Fix is merged

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477)*

**Comment by andy-kimball** [comment]
Review status: 1 of 35 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/sql/opt/norm/decorrelate.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZZDywEu8ATCe-ih6X:-LC_ceWO9_Y8-nsYeT8M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a173477bf3b28d239ccd30cb064db461719a2f/pkg/sql/opt/norm/decorrelate.go#L196)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

`constructScalarGroupByLeftJoin` -> `hoistCorrelatedScalarGroupBy`
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/decorrelate.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZTYS4AxsRko7sx84H:-LC_eFhz6X9RQmoL1qQq:b-wvm1hd) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a173477bf3b28d239ccd30cb064db461719a2f/pkg/sql/opt/norm/decorrelate.go#L230)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What if the only value is NULL? 

I think this might be clearer if you say something like: "...Since the grouping column(s) are a key of "left", FIRST_AGG will return the first and only value of the given column..."
</blockquote></details>

It's still a bit misleading to say "first and only value", because there may be many copies of the `FIRST_AGG` column value in the grouping set. It does not matter which one we project (in fact, we're going to rename `FIRST_AGG` to `ANY_NOT_NULL`). I did reword this section, so see if you like new wording better.

---

*[pkg/sql/opt/norm/factory.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZVSZ6EDs5YEPTvFyj:-LC_g0hv0CQpQ8UnzBty:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a173477bf3b28d239ccd30cb064db461719a2f/pkg/sql/opt/norm/factory.go#L470)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Doesn't seem like it panics...
</blockquote></details>

Fixed.

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZYwxn7G22O1xql9Qn:-LC_gVUL3ylL8ysQPBE5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a173477bf3b28d239ccd30cb064db461719a2f/pkg/sql/opt/norm/rules/decorrelate.opt#L170)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It would be helpful to add this paragraph to the other matching comment for `hoistCorreatedScalarGroupBy`
</blockquote></details>

Done.

---

*[pkg/sql/opt/ops/scalar.opt, line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZMU4x7TMojG89bffU:-LC_kQEJ3efYLreeFp-Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a173477bf3b28d239ccd30cb064db461719a2f/pkg/sql/opt/ops/scalar.opt#L609)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Lets rename to `AnyNotNullAgg` since that's all we need. Also mention that this is particularly useful for "passing through" the value of a column which we know is constant within any group.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/external/tpch, line 2438 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCZR8uz5BqMETBEm2LR:-LC_zD351TWtd2gIDzbD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ba6635c22b42481571c085d3cb6e337f88ade5/pkg/sql/opt/xform/testdata/external/tpch#L2438)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] tabs are kind of annoying in these files, I'd just do a mass conversion to 2 or 4 spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/norm/decorrelate.go, line 286 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCdHyTF76JlyTjwCGMR:-LCdHyTF76JlyTjwCGMS:b-kjj69t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7d0d1f788e6e4f3aa7066db8b359c59c85a62ec/pkg/sql/opt/norm/decorrelate.go#L286)):*
> ```Go
> 	if f.outputCols(join).Len() == 0 {
> 		fmt.Println(memo.MakeNormExprView(f.mem, join))
> 		panic("here")
> ```

Leftover debugging code

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/opt/memo/typing.go, line 135 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCdQsSN-JoJ6mbA3sbC:-LCdeuBHAXX7UsUAr3Ql:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7d0d1f788e6e4f3aa7066db8b359c59c85a62ec/pkg/sql/opt/memo/typing.go#L135)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Now `AnyNotNull` is going to be part of the builtins table -- update comment
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/decorrelate.go, line 286 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCdHyTF76JlyTjwCGMR:-LCdd34tANEPWyGRTkhl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7d0d1f788e6e4f3aa7066db8b359c59c85a62ec/pkg/sql/opt/norm/decorrelate.go#L286)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Leftover debugging code
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/factory.go, line 546 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCdSzyX94tPFSJBi-xv:-LCddJq59gKpYJNhHkaY:b-1j792t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7d0d1f788e6e4f3aa7066db8b359c59c85a62ec/pkg/sql/opt/norm/factory.go#L546)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why not use `f.ConstructSimpleProject(...)`?
</blockquote></details>

Because that constructs a `Project` operator, but here I need a `Projections` operator.

---

*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 127 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCdWs_o0c4_oKU09lrS:-LCdf3Hu-S-LlL_vBqdx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7d0d1f788e6e4f3aa7066db8b359c59c85a62ec/pkg/sql/opt/testutils/testcat/test_catalog.go#L127)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Just noticed that this error message should be updated, now that we have ALTER TABLE.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477)*

**Comment by rytaft** [comment]
Reviewed 9 of 10 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/norm/factory.go, line 546 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25477#-LCdSzyX94tPFSJBi-xv:-LCds-EO9X-62sDIHUyO:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7d0d1f788e6e4f3aa7066db8b359c59c85a62ec/pkg/sql/opt/norm/factory.go#L546)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Because that constructs a `Project` operator, but here I need a `Projections` operator.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25477)*

**Pull request merged**
