### PR TITLE
gossip: test stall detection on orphaning

### LINKED ISSUE #8129: gossip: test reconnection to gossip network on node failure
See #8128. Prior to that change, we wouldn't attempt to open a new gossip connection if our current connection closed unexpectedly with no forwarding address. This would leave the node in a state where it wasn't receiving or sending gossip updates.

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8901)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[gossip/gossip_test.go, line 287 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901#-KQMgX7j6rYGPeRIsshz:-KQMgX7j6rYGPeRIssi-:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e1bb2998aec3dcf41b04e64045b6cf914878f2/gossip/gossip_test.go#L287)):*
> ```Go
> 	local.startClient(peerAddr, peerNodeID)
> 
> 	const slowGossipDuration = time.Minute
> ```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gossip/gossip.go, line 1070 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901#-KQMfl-wqmCEyqsgMyzZ:-KQMgHd34a1JxQYXqyIs:b-l64d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a147f7d807841de590894dabf5593401c9c104/gossip/gossip.go#L1070)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Why remove this one? Catches a newbie error.
> These are also (afaict) the only logs that make it clear that gossip isn't connected. I don't think we should remove them. The log messages here aren't great, but I think not being connected to gossip is fundamental enough to be logged prominently.
</details>
The log messages aren't removed, they just moved to a different function.

You're right though, that the message logged now is `log.Warningf(ctx, "no incoming or outgoing connections")` which is less suggestive, but it also seems to me that this is overly speculative. In particular, take a look at the new location - all we know is that the node is "orphaned". Perhaps we could log "use --join" if the node is both orphaned _and_ has no resolvers?

---

*[gossip/gossip_test.go, line 287 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901#-KQMgX7j6rYGPeRIsshz:-KQMgez48eC3csQdUvOC:b-z4su8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e1bb2998aec3dcf41b04e64045b6cf914878f2/gossip/gossip_test.go#L287)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> ?
</details>
oops, bad pasta. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/gossip.go, line 1070 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901#-KQMfl-wqmCEyqsgMyzZ:-KQMi9N2RD4rWfwARH0v:b-gjrjx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a147f7d807841de590894dabf5593401c9c104/gossip/gossip.go#L1070)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> The log messages aren't removed, they just moved to a different function.
> 
> You're right though, that the message logged now is `log.Warningf(ctx, "no incoming or outgoing connections")` which is less suggestive, but it also seems to me that this is overly speculative. In particular, take a look at the new location - all we know is that the node is "orphaned". Perhaps we could log "use --join" if the node is both orphaned _and_ has no resolvers?
</details>
Yes, that makes sense to me, though that would mean that the "first node" (which, if restarted with the same command line, has no resolvers) could occasionally log this at startup (but that's not really incorrect since it relies on another node to talk to it, which is not robust).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901#-:-KQMib3CAJb9__0qV-KO:bnfp4nl)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/gossip.go, line 1070 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901#-KQMfl-wqmCEyqsgMyzZ:-KQMjtK_AYOWlZ3nUAKn:b-x1t454) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a147f7d807841de590894dabf5593401c9c104/gossip/gossip.go#L1070)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Yes, that makes sense to me, though that would mean that the "first node" (which, if restarted with the same command line, has no resolvers) could occasionally log this at startup (but that's not really incorrect since it relies on another node to talk to it, which is not robust).
</details>
Won't that node have persisted its resolvers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gossip/gossip.go, line 1070 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901#-KQMfl-wqmCEyqsgMyzZ:-KQMmIU7vYN3r87oDUOW:b-qjr46n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a147f7d807841de590894dabf5593401c9c104/gossip/gossip.go#L1070)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Won't that node have persisted its resolvers?
</details>
Ideally, but it might've cleaned them up again after being alone for a bit. It's pretty hypothetical and I think the message above is good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8901)*

**Pull request merged**
