### PR TITLE
colexec: add support for disk-backed distinct

### PR DESCRIPTION
**Pull request by yuzefovich**
**colmem: fix appending column to the windowed batches**

We use `MaybeAppendColumn` to enforce that a vector of the desired type
is at the correct position. However, with the introduction of the
concept of capacity to the batches we now also need to make sure that
the vector has the desired capacity. In vast majority of cases we are
reallocating the whole batch because of the dynamic size, so it
shouldn't be an issue, still this commit fixes that theoretical problem.

Additionally, this commit fixes a problem of appending a vector to the
windowed batches - such batches are instantiated with 0 capacity, and
previously when we were appending a vector to it, we would always
allocate the vector of 0 capacity.

Release note: None

**colexec: extract hash-based partitioner base from external hash joiner**

This commit extracts the logic of the Grace hash join algorithm into a
hash-based partitioner that can be reused by the unordered distinct and
the hash aggregator to add support for disk-spilling. The idea is that at
planning time we can provide different in-memory "main" and disk-backed
"fallback" strategies. If a partition fits under the memory limit, then
the former is used; however, if recursive partitioning isn't successful
in reducing the size, that partition is assigned to be handled by the
latter. In case of the external hash joiner, the in-memory hash joiner
is the "main" operator whereas the external sort and the merge joiner
form the "fallback" operator.

Release note: None

**colexec: fix test harness in some cases when comparing sets**

This commit fixes our test harness when comparing expected and actual
tuples as sets. We use a sort to speed things up, and previously in
some cases we could have different ordering for essentially the same
sets of tuples because in the actual ones we have tree.Datums and in
the expected ones we have strings.

Release note: None

**colexec: implement disk-spilling for unordered distinct**

This commit introduces an external distinct operator that reuses the
hash-based partitioner that works according to "partitioning by hash"
scheme when dividing the input into separate partitions. The "main"
strategy for the new operator is already existing in-memory unordered
distinct whereas the "fallback" strategy is the external sort followed by
the ordered distinct. The benchmarks have shown that using such approach is
significantly faster in most cases when comparing against the external
sort + ordered distinct approach (i.e. against making the fallback
strategy the main one).

One important detail of the fallback strategy is that we need to make sure
that we keep the very first tuple from the input among all tuples that
are identical on the distinct columns. If we naively use a sort
plus ordered distinct, we might break that, so in order to go around it, we
plan an ordinality operator and include the ordinality column as the
last one in the ordering, we then project out that temporary column when
feeding into the ordered distinct.

Another important detail is that distinct is expected to maintain the
ordering of the output stream (to be the same as the ordering of the
input stream) when the output ordering is specified. Previously, this was
achieved for "free" in both the vectorized and the row-by-row engines;
however, with the partitioning by hash approach we don't have that anymore.
Therefore, a new field was added to DistinctSpec that specified the desired
output ordering, and the field is now used to optionally plan an external
sort on top of the external distinct. The benchmarks have shown that the
performance overhead of having such sort is relatively small.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
Rather than using a sort+distinct, why not use a partitioned distinct? i.e. store partitions and run a distinct on each partition. This is the approach we use for all other external strategies.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-:-MLgYKJcE7bu6NcQFRlK:b-u5eo68)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
I considered a couple of other strategies:
1. use unordered distinct to divide up the input into partitions which will allow us to remove some duplicates instead of spilling all tuples to disk. The disadvantage is that we'll need to create a component that "merges" the partitions ensuring global distinctness. The complication is that we need to make sure to keep the first tuple from the input among all duplicates.
2. use hashing on the distinct columns to divide up the input into partitions, and then run unordered distinct on each partition separately. This will allow us to not write the "partitions merger" as in step 1 because we know that all identical tuples must end up in the same partition, but it also has a few complications - we need to be able to handle a case when the total size of identical tuples exceeds the maximum size of one partition (64MB) and, similarly, we need to make sure that the first tuple from the input is kept.

Given all these complications I decided to implement the current approach which is the simplest and simply reuses already existing components. True, it is probably not the fastest one, so we might want to iterate on the algorithm later if we find it necessary.

The benchmarks are [here](https://gist.github.com/yuzefovich/1d7e54c0ae667b6247d5614e2d57248f) which show that the spilling causes the slowdown of 3-10x on the larger data sets (on the smaller ones slowdown is on the order of 20x, but I think it's not important) which seems reasonable to me.

**Review by asubiotto — COMMENTED** [review]
> use hashing on the distinct columns to divide up the input into partitions, and then run unordered distinct on each partition separately. This will allow us to not write the "partitions merger" as in step 1 because we know that all identical tuples must end up in the same partition, but it also has a few complications - we need to be able to handle a case when the total size of identical tuples exceeds the maximum size of one partition (64MB) and, similarly, we need to make sure that the first tuple from the input is kept.

This is what I'm suggesting. I think the problem of tuples exceeding the maximum size of one partition is a problem we've already solved with repartitioning in other cases. Maybe we should dedicate some effort to make it reusable here and possible as well for the hash aggregator? Keeping the first tuple from the input is not a problem since the diskqueue stores inputs in order, so if your in-memory hash aggregator has this behavior (which I think it does because I think archer had to implement it). I guess we need benchmarks to understand the cost of an on-disk sort vs the partitioning approach, but I would intuitively want to push towards the partitioning solution, since I think it's something that will inform the disk spilling of the hash aggregator as well.

Since you already wrote the on-disk sort, it'd be interesting to see if you can write a quick and dirty repartitioning strategy (maybe by copying the hash join repartitioning code) and see what the benchmarks say for a couple of different cases.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-:-MLlXN_Y4G1Kb-W8P-9W:byk2lmn)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
We need to have the "base case" for repartitioning in order to handle the scenario when we literally have 1GB of duplicates, and the approach of external sort + ordered distinct could be the base.

I'll look into the repartitioning implementation.

By the way, the external hash aggregation could also be handled by the approach that this PR currently takes - external sort + ordered aggregator.

**Comment by asubiotto** [comment]
Right, I was thinking that the base case could be abstracted out and swapped in depending on what the operator wants to do when repartitioning hits the threshold where it can't reduce the size anymore.

> By the way, the external hash aggregation could also be handled by the approach that this PR currently takes - external sort + ordered aggregator.

Yeah, I think this is why it'd be good to get an idea for the performance difference. If this sorting + ordered approach is better it'd be great to do it, but if not it's sort of a temporary solution and I think we have the time to focus building something permanent since it's a release goal.

**Comment by yuzefovich** [comment]
I prototyped the partitioning approach with benchmarks [here](https://gist.github.com/yuzefovich/b7dcd3004e169662a0f530befd79b608), and it does show a noticeable improvement on larger datasets when the spilling occurs, so I think it's worth pursuing that avenue.

I'll cleanup the commits and will ping once it is RFAL.

**Comment by asubiotto** [comment]
Nice, thanks for trying it out!

**Comment by yuzefovich** [comment]
Actually, there is a complication with the partitioning approach. Currently, the optimizer assumes that distinct operator preserves the ordering (both in a sense that the firth distinct tuple from each group is kept and that if the input stream is already ordered on a set of columns, the resultant output stream will also be ordered on the same set of columns). We've worked hard to ensure that the former is the case, and the partitioning approach doesn't change that, but we lose the latter ordering preservation.

We have several alternatives:
1. keep the optimizer's assumption of ordering preservation - this can be quite a beneficial assumption that allows to remove the sort in some cases, and to implement it I see two options:
  - use my original approach of full external sort + ordered distinct, the sort here is of `n` tuples where `n` is the cardinality of the input
  - use the partitioning approach but also add an external sort before emitting the output, the sort here is of `d` tuples where `d` is the total number of distinct tuples in the input.
We could take it one step further and remove the "fallback" strategy for the external distinct (which is external sort of a partition + ordered distinct) and always plan external sort + ordered distinct on the output (not sure if this would be more performant though).
2. remove the optimizer's assumption of ordering preservation
  - then the partitioning approach works, and there is no need to plan an external sort separately - it'll be a part of the plan if ordering is needed.

Overall, I'm not sure which approach would be best and how important it is to determine that. I feel like we should choose an approach from "keeping the optimizer's assumption" part since that option is more performant when the spilling to disk doesn't occur. Thoughts? cc @jordanlewis  @RaduBerinde

**Comment by RaduBerinde** [comment]
The most important case for preserving the ordering is when there is a LIMIT on top - it's the difference between stopping execution early and processing all the rows. I don't know how prevalent that is in practice though. It's worth noting that various rules like decorrelation can add a DISTINCT ON even if the query doesn't have one.

It would be easy for the optimizer to let execution know if we care or not about the inter-group ordering, if that helps at all.

I don't have a great understanding of all the details, but I'd probably go the external sort + streaming distinct route.

Is there any comment or doc I can read to understand the partitioning approach better? Wondering why we couldn't partition by ranges of values on the distinct columns rather than hashing (so that we preserve the ordering).

**Comment by asubiotto** [comment]
https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20191113_vectorized_external_storage.md and https://www.cockroachlabs.com/blog/disk-spilling-vectorized/. We can partition by whatever we want; the important part is dividing the input.

**Comment by yuzefovich** [comment]
I prototyped partitioning by hashing because we already have external Grace hash join, and it was relatively easy to extract the logic to be reused. We will also likely reuse the same hashing approach for disk-spilling of the hash aggregation.

Talking about partitioning by range of values - we would need to be able to divide the space of all values for each type into an arbitrary number of partitions, is that easy? I guess it'll be some encoding manipulations? I think if we go with this range partitioning approach, we still are not guaranteed the ordering preservation in case when the sets of ordering columns is not the same as the set of distinct columns, so I'm not sure what would be the benefit of such strategy.

**Comment by yuzefovich** [comment]
I think we should go with the partitioning by hash approach with the optimizer keeping the assumption of preserving the ordering, but requiring it to specify whether that is necessary (i.e. the optimizer will the execution that the ordering must be preserved). This way we're likely to get the best speed overall when we spill to disk.

I'll prototype that and benchmark to see how much the external sort of the distinct tuples slows down overall speed.

**Comment by yuzefovich** [comment]
Alright, I benchmarked external sort + ordered distinct vs distinct with partitioning + "final" sorter (on all columns from the input) [here](https://gist.github.com/yuzefovich/9ddf4bcb5fa7b1185226d088a69291e9), and on large inputs the latter wins by a big margin. I think the former will only be faster when the number of distinct tuples in the input is roughly the same as the total number of tuples in the input *and* we need to preserve the ordering (I ran quick benchmarks [here](https://gist.github.com/yuzefovich/bea96de7d86ef8736e711c0627afcf30) with 90% probability of a tuple being distinct).

I also ran the benchmarks of distinct with partitioning without and with the "final" sorter [here](https://gist.github.com/yuzefovich/fda01514eb27f5c8c638224da0d047a0) to get a sense for the price of that external sort, and they show that it is relatively cheap in comparison to the distinct operation itself.

So I believe we should proceed with this partitioning strategy. This will require us to teach the optimizer to keep track whether ordering preservation is required and what that ordering is. That shouldn't be that hard.

**Comment by yuzefovich** [comment]
Actually, the optimizer already tracks the ordering for `distinctNode`, so the changes are required only during physical planning.

**Comment by yuzefovich** [comment]
Alright, it is RFAL.

The benchmark numbers are
```
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.001/rows=1024/cols=2/ordCols=0-24         	   19372	     61256 ns/op	 267.47 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.001/rows=1024/cols=4/ordCols=0-24         	   15028	     81477 ns/op	 402.17 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.001/rows=65536/cols=2/ordCols=0-24        	     794	   1502681 ns/op	 697.80 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.001/rows=65536/cols=4/ordCols=0-24        	     514	   2331439 ns/op	 899.51 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.001/rows=4194304/cols=2/ordCols=0-24      	      10	 100558395 ns/op	 667.36 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.001/rows=4194304/cols=4/ordCols=0-24      	       7	 163954933 ns/op	 818.63 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.100/rows=1024/cols=2/ordCols=0-24         	   10000	    100296 ns/op	 163.36 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.100/rows=1024/cols=4/ordCols=0-24         	    9051	    133691 ns/op	 245.10 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.100/rows=65536/cols=2/ordCols=0-24        	     411	   2944697 ns/op	 356.09 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.100/rows=65536/cols=4/ordCols=0-24        	     272	   4392753 ns/op	 477.41 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.100/rows=4194304/cols=2/ordCols=0-24      	       6	 198308831 ns/op	 338.41 MB/s
BenchmarkExternalDistinct/spilled=false/ordering=false/newTupleProbability=0.100/rows=4194304/cols=4/ordCols=0-24      	       4	 290221540 ns/op	 462.47 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.001/rows=1024/cols=2/ordCols=0-24          	     505	   2386549 ns/op	   6.87 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.001/rows=1024/cols=4/ordCols=0-24          	     277	   4378874 ns/op	   7.48 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.001/rows=65536/cols=2/ordCols=0-24         	      93	  11053999 ns/op	  94.86 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.001/rows=65536/cols=4/ordCols=0-24         	      79	  14065186 ns/op	 149.10 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.001/rows=4194304/cols=2/ordCols=0-24       	       4	 286174008 ns/op	 234.50 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.001/rows=4194304/cols=4/ordCols=0-24       	       3	 456314708 ns/op	 294.13 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.100/rows=1024/cols=2/ordCols=0-24          	     196	   6315555 ns/op	   2.59 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.100/rows=1024/cols=4/ordCols=0-24          	     183	   6520146 ns/op	   5.03 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.100/rows=65536/cols=2/ordCols=0-24         	      82	  13563473 ns/op	  77.31 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.100/rows=65536/cols=4/ordCols=0-24         	      66	  17693084 ns/op	 118.53 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.100/rows=4194304/cols=2/ordCols=0-24       	       3	 423576688 ns/op	 158.43 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.100/rows=4194304/cols=4/ordCols=0-24       	       2	 670810610 ns/op	 200.08 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.001/rows=1024/cols=2/ordCols=0-24           	     256	   4678747 ns/op	   3.50 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.001/rows=1024/cols=4/ordCols=0-24           	     256	   4769514 ns/op	   6.87 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.001/rows=65536/cols=2/ordCols=0-24          	      75	  14564006 ns/op	  72.00 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.001/rows=65536/cols=4/ordCols=0-24          	      67	  16328251 ns/op	 128.44 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.001/rows=4194304/cols=2/ordCols=0-24        	       4	 296674508 ns/op	 226.20 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.001/rows=4194304/cols=4/ordCols=0-24        	       3	 474110992 ns/op	 283.09 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.100/rows=1024/cols=2/ordCols=0-24           	     136	   8303009 ns/op	   1.97 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.100/rows=1024/cols=4/ordCols=0-24           	     136	   8745822 ns/op	   3.75 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.100/rows=65536/cols=2/ordCols=0-24          	      63	  17858634 ns/op	  58.72 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.100/rows=65536/cols=4/ordCols=0-24          	      51	  22312821 ns/op	  93.99 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.100/rows=4194304/cols=2/ordCols=0-24        	       2	 532456478 ns/op	 126.04 MB/s
BenchmarkExternalDistinct/spilled=true/ordering=true/newTupleProbability=0.100/rows=4194304/cols=4/ordCols=0-24        	       2	 811718828 ns/op	 165.35 MB/s
```

**Review by asubiotto — CHANGES_REQUESTED** [review]
Skipped over the first commit since that's being reviewed in #57647.

> Reviewed 5 of 5 files at r2, 1 of 1 files at r3, 7 of 7 files at r4, 1 of 1 files at r5, 16 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-:-MO0kyPM84lLlX6QCMi_:bh1soer)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/external_distinct.go, line 94 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-MO0pRFo51ZbfwVJlDew:-MO0pRFo51ZbfwVJlDex:b-7z04ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4e134ff4c90f3eaf0cf7036778a76380bb2777/pkg/sql/colexec/external_distinct.go#L94)):*
> ```Go
> 	)
> 	outputOrdering := args.Spec.Core.Distinct.OutputOrdering
> 	if len(outputOrdering.Columns) == 0 {
> ```

Add a comment about this check
___
*[pkg/sql/colexec/external_operator.go, line 204 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-MO0mOA88e2NiaKfHtL1:-MO0mOA88e2NiaKfHtL2:b-mqk0fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4932d645158db5a959f581c91da4a33cb88f4ed2/pkg/sql/colexec/external_operator.go#L204)):*
> ```Go
> // repartitioned; if that is not successful, the partition in question is
> // handled by the "fallback" disk-backed operator.
> func newExternalOperator(
> ```

nit: I think `externalOperator` is too general. How about something like `hashBasedPartitioner`
___
*[pkg/sql/colmem/allocator.go, line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-MO0lUq32pSkaqUD3rcD:-MO0lUq32pSkaqUD3rcE:b-1lv67o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dfc0e4dfc76cc1cfd55cd7f45b67037317b776b/pkg/sql/colmem/allocator.go#L246)):*
> ```Go
> 	width := b.Width()
> 	desiredCapacity := b.Capacity()
> 	if desiredCapacity == 0 {
> ```

Can we add a test for this? If the commit fixes an issue, that should be easy to demonstrate with a unit test.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56399)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_distinct.go, line 94 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-MO0pRFo51ZbfwVJlDew:-MO2McKL-BJYzY57aVpC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c4e134ff4c90f3eaf0cf7036778a76380bb2777/pkg/sql/colexec/external_distinct.go#L94)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Add a comment about this check
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_operator.go, line 204 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-MO0mOA88e2NiaKfHtL1:-MO2LfZL2e-eat6cTSPM:bkq9gue) ([raw file](https://github.com/cockroachdb/cockroach/blob/4932d645158db5a959f581c91da4a33cb88f4ed2/pkg/sql/colexec/external_operator.go#L204)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: I think `externalOperator` is too general. How about something like `hashBasedPartitioner`
</blockquote></details>

Hm, I agree, your suggestion sounds better, done.
___
*[pkg/sql/colmem/allocator.go, line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-MO0lUq32pSkaqUD3rcD:-MO2I7Te8BhmlOKgHGNZ:bfg91i4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dfc0e4dfc76cc1cfd55cd7f45b67037317b776b/pkg/sql/colmem/allocator.go#L246)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we add a test for this? If the commit fixes an issue, that should be easy to demonstrate with a unit test.
</blockquote></details>

Good point, added a few unit tests.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 23 of 23 files at r7, 4 of 4 files at r8, 7 of 7 files at r9, 1 of 1 files at r10, 19 of 19 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-:-MO5wjY2595-RH0C4_q5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colmem/allocator_test.go, line 39 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-MO5vY2t2JUfcccGVALf:-MO5vY2t2JUfcccGVALg:b-nw1y9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a5026fbadce7763160ec4e19949633eeb19470a/pkg/sql/colmem/allocator_test.go#L39)):*
> ```Go
> 	testAllocator := colmem.NewAllocator(ctx, &memAcc, testColumnFactory)
> 
> 	t.Run("vector already present", func(t *testing.T) {
> ```

nit: write these test names with camel case so it's easy to run a single one from the command line: `make test PKG=./pkg/sql/colmem TESTS=TestMaybeAppendColumn/VectorAlreadyPresent`

**Review by yuzefovich — COMMENTED** [review]
TFTR!

I'll wait for @cathymw to take a look at #57647 before merging this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-:-MO7BBMJ0Xv2qim2t_9v:b-nw3rqq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colmem/allocator_test.go, line 39 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56399#-MO5vY2t2JUfcccGVALf:-MO7B67K05WKAiEI4r6z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a5026fbadce7763160ec4e19949633eeb19470a/pkg/sql/colmem/allocator_test.go#L39)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: write these test names with camel case so it's easy to run a single one from the command line: `make test PKG=./pkg/sql/colmem TESTS=TestMaybeAppendColumn/VectorAlreadyPresent`
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Huh, seems like CI failed.

bors r-

**Comment by yuzefovich** [comment]
Turns out, there was a minor bug (accessing the wrong field) when deciding whether repartitioning was successful which caused an infinite recursion in some cases, and it is now fixed. I also made a couple of other cosmetic changes. Will wait for green CI and merge then.

**Comment by yuzefovich** [comment]
Seems like two unrelated flakes.

bors r+

**Pull request merged**
