### PR TITLE
opt: fix regression in stats estimation for large tables

### LINKED ISSUE #69709: opt: fix selectivity estimates for very large tables
Consider the following example:
```
CREATE TABLE bigtable (x INT, y INT);
ALTER TABLE bigtable INJECT STATISTICS '[
    {
        "columns": [
            "x"
        ],
        "created_at": "2021-06-15 02:06:48.036389",
        "distinct_count": 3000000002,
        "histo_buckets": [
            {
                "distinct_range": 0,
                "num_eq": 10,
                "num_range": 0,
                "upper_bound": "0"
            },
            {
                "distinct_range": 3000000000,
                "num_eq": 10,
                "num_range": 29999999980,
                "upper_bound": "100000000000"
            }
        ],
        "histo_col_type": "INT8",
        "name": "__auto__",
        "row_count": 30000000000
    }
]';

EXPLAIN (opt, verbose) SELECT * from bigtable WHERE x = 10;
                                        info
-------------------------------------------------------------------------------------
  select
   ├── columns: x:1 y:2
   ├── stats: [rows=1.11111111e-08, distinct(1)=1.11111111e-08, null(1)=0]
   │   histogram(1)=  0 1.1111e-08
   │                <------ 10 ---
   ├── cost: 3.33e+10
   ├── fd: ()-->(1)
   ├── prune: (2)
   ├── scan bigtable
   │    ├── columns: x:1 y:2
   │    ├── stats: [rows=3e+10, distinct(1)=3e+09, null(1)=0]
   │    │   histogram(1)=  0 10  3e+10       10
   │    │                <--- 0 ------- 100000000000
   │    ├── cost: 3.3e+10
   │    └── prune: (1,2)
   └── filters
        └── x:1 = 10 [outer=(1), constraints=(/1: [/10 - /10]; tight), fd=()-->(1)]
(17 rows)
```
Based on the stats, we should estimate that this query produces 10 rows. However, the estimate is actually 1.11e-08 rows. 

This is a regression due to https://github.com/cockroachdb/cockroach/pull/67940. The problem is caused by the way we are multiplying and dividing selectivities in the optimizer and causing underflow for the selectivity type.

### PR DESCRIPTION
**Pull request by rytaft**
This commit fixes a regression in statistics estimation that could
cause the optimizer to severely underestimate the number of rows returned
by an expression.

Fixes #69709

Release note (bug fix): Fixed a regression in statistics estimation in
the optimizer for very large tables. The bug, which has been present since
20.2.14 and 21.1.7, could cause the optimizer to severely underestimate the
number of rows returned by an expression. This has now been fixed.

Release justification: low risk bug fix to existing functionality

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Does the bug happens because the numbers we multiply get smaller than the `epsilon`? How did the changes in #67940 make a difference here?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-:-MiYa-r5-sOjtEKDLQqA:b9i6q2g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/union, line 483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-MiY_vxB8QLxJx1LTzSM:-MiY_vxC29kXFO5efN7r:b7tbxn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4429af8bd92d44333fbef27fc9829edb464c4899/pkg/sql/opt/exec/execbuilder/testdata/union#L483)):*
> ```
> │ columns: (a, b, c, d, e)
> │ ordering: +b,+c,+d,+a
> │ estimated row count: 0 (missing stats)
> ```

How come we get so many zeros now? Shouldn't the result be the same on small numbers?
___
*[pkg/sql/opt/memo/testdata/stats/select, line 3204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-MiYYyZV1JzW0Xu_sDDZ:-MiYYyZV1JzW0Xu_sDD_:b-iodhlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4429af8bd92d44333fbef27fc9829edb464c4899/pkg/sql/opt/memo/testdata/stats/select#L3204)):*
> ```
>             },
>             {
>                 "distinct_range": 3000000000,
> ```

[nit], can you align the three integer values? It was hard to see that distinct_range has one less digit.
___
*[pkg/sql/opt/props/statistics.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-MiYZpq1BfkMTOef7d2c:-MiYZpq1BfkMTOef7d2d:b1l10ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/4429af8bd92d44333fbef27fc9829edb464c4899/pkg/sql/opt/props/statistics.go#L112)):*
> ```Go
> 	// update the RowCount.
> 	if ratio > 1 {
> 		adjustedRatio := 1 / s.Selectivity.AsFloat()
> ```

[nit] This was hard to understand. Maybe use variables like `oldSelectivity` and `newSelectivity` and then `RowCount *= oldSelectivity / newSelectivity` is much more clear. And add a comment right above MakeSelectivity that mentions that the value is capped to 1.

**Review by rytaft — COMMENTED** [review]
yea exactly -- we get a smaller selectivity than epsilon, which is then reset to epsilon. The row count then is no longer in sync with the selectivity. When we call `UnapplySelectivity` the row count becomes correct, but the selectivity is way too high. Then we limit the selectivity (this was added in #67940), which updates the row count to be tiny.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-:-MiZFs-c3fMrTCs0R5jN:be5wpp9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/testdata/union, line 483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-MiY_vxB8QLxJx1LTzSM:-MiZKuEa7qlK95sSWUpC:btbl449) ([raw file](https://github.com/cockroachdb/cockroach/blob/4429af8bd92d44333fbef27fc9829edb464c4899/pkg/sql/opt/exec/execbuilder/testdata/union#L483)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How come we get so many zeros now? Shouldn't the result be the same on small numbers?
</blockquote></details>

These new stats are correct, since the selectivity of (c=1) is ~0.01 and the selectivity of (d=e) is also ~0.01. Together, the selectivity of the predicate is 0.01 * 0.01 = 0.0001, which results in an estimate of 1000 * 0.0001 = 0.1 rows. The union then has an estimate of 0.2 rows, which gets rounded down to 0. I'd need to dig a bit more to understand why the old logic was estimating 2 rows here, but it has something to do with selectivity being capped either on the upper or lower bound, and the row count getting out of sync...
___
*[pkg/sql/opt/memo/testdata/stats/select, line 3204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-MiYYyZV1JzW0Xu_sDDZ:-MiZITwP5unjMfQGiBl8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4429af8bd92d44333fbef27fc9829edb464c4899/pkg/sql/opt/memo/testdata/stats/select#L3204)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit], can you align the three integer values? It was hard to see that distinct_range has one less digit.
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/statistics.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-MiYZpq1BfkMTOef7d2c:-MiZJi0uBPsayHVXB55M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4429af8bd92d44333fbef27fc9829edb464c4899/pkg/sql/opt/props/statistics.go#L112)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This was hard to understand. Maybe use variables like `oldSelectivity` and `newSelectivity` and then `RowCount *= oldSelectivity / newSelectivity` is much more clear. And add a comment right above MakeSelectivity that mentions that the value is capped to 1.
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-:-MibPMhlDKgC1-gYRJr2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/union, line 483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-MiY_vxB8QLxJx1LTzSM:-MibP1ec4s37OZZYSbjP:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4429af8bd92d44333fbef27fc9829edb464c4899/pkg/sql/opt/exec/execbuilder/testdata/union#L483)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These new stats are correct, since the selectivity of (c=1) is ~0.01 and the selectivity of (d=e) is also ~0.01. Together, the selectivity of the predicate is 0.01 * 0.01 = 0.0001, which results in an estimate of 1000 * 0.0001 = 0.1 rows. The union then has an estimate of 0.2 rows, which gets rounded down to 0. I'd need to dig a bit more to understand why the old logic was estimating 2 rows here, but it has something to do with selectivity being capped either on the upper or lower bound, and the row count getting out of sync...
</blockquote></details>

:thumbsup:

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69711#-:-MicCzWbDyR4VuSvsJTb:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by rytaft** [comment]
The regression doesn't actually exist in 20.2, so removing that label.

**Pull request merged**
