### PR TITLE
jobs/scheduled_jobs: Implement scheduled jobs daemon

### PR DESCRIPTION
**Pull request by miretskiy**
Implement scheduled jobs daemon responsible for periodically finding
and executing schedules.

Release notes: None

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50025)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/jobs/job_scheduler.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9TmDjoB0gNd-Oitauc:-M9TmDjp8mb8kFaRoPzk:b3q506a) ([raw file](https://github.com/cockroachdb/cockroach/blob/f253906c522d3a49073f8a2c3753487e1a6a3786/pkg/jobs/job_scheduler.go#L184)):*
> ```Go
> func (s *jobScheduler) executeSchedules(
> 	ctx context.Context, maxSchedules int64, txn *kv.Txn,
> ) error {
> ```

Do we need a check to `schedulerEnableSetting` here? If not, wouldn't the daemon execute the schedules every 5 minutes?

Could we also add a test for this?
___
*[pkg/jobs/job_scheduler.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9Tq10xDCm37L7XXhzw:-M9Tq10xDCm37L7XXhzx:b-ny3ugd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f253906c522d3a49073f8a2c3753487e1a6a3786/pkg/jobs/job_scheduler.go#L213)):*
> ```Go
> 	"jobs.scheduler.enabled",
> 	"enable/disable job scheduler",
> 	true)
> ```

nit: paren on the next line to match the others
___
*[pkg/jobs/job_scheduler.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9TmrV49peGO4RmIwx0:-M9TmrV49peGO4RmIwx1:b-v2p41) ([raw file](https://github.com/cockroachdb/cockroach/blob/f253906c522d3a49073f8a2c3753487e1a6a3786/pkg/jobs/job_scheduler.go#L240)):*
> ```Go
> var getWaitPeriod = func(sv *settings.Values) time.Duration {
> 	if !schedulerEnabledSetting.Get(sv) {
> 		// Retry after a minute
> ```

Comment should read 5 minutes? Maybe we can also pull out this 5 minutes into a `const`?
___
*[pkg/jobs/job_scheduler_test.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9ToEf-C9KimEXXsmd7:-M9ToEf-C9KimEXXsmd8:b-dk6kbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f253906c522d3a49073f8a2c3753487e1a6a3786/pkg/jobs/job_scheduler_test.go#L218)):*
> ```Go
> 			return nil
> 		}
> 		return errors.Newf("still waiting for matching jobs: res=%+v", results)
> ```

It may be useful to also log the expected results here?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50025)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/jobs/job_scheduler.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9TmDjoB0gNd-Oitauc:-M9U1B0gE3cylw1y2T9q:b-kza4ea) ([raw file](https://github.com/cockroachdb/cockroach/blob/f253906c522d3a49073f8a2c3753487e1a6a3786/pkg/jobs/job_scheduler.go#L184)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Do we need a check to `schedulerEnableSetting` here? If not, wouldn't the daemon execute the schedules every 5 minutes?

Could we also add a test for this?
</blockquote></details>

Good catch -- added check in the main daemon loop, plus a test. thanks.
___
*[pkg/jobs/job_scheduler.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9TmrV49peGO4RmIwx0:-M9U0bps1BtqJv5_4daJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f253906c522d3a49073f8a2c3753487e1a6a3786/pkg/jobs/job_scheduler.go#L240)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Comment should read 5 minutes? Maybe we can also pull out this 5 minutes into a `const`?
</blockquote></details>

Done.
___
*[pkg/jobs/job_scheduler_test.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9ToEf-C9KimEXXsmd7:-M9U0E2G4k9AKRrMTRa5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f253906c522d3a49073f8a2c3753487e1a6a3786/pkg/jobs/job_scheduler_test.go#L218)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

It may be useful to also log the expected results here?
</blockquote></details>

Done.

**Review by pbardea — APPROVED** [review]
LGTM - my latest comments shouldn't block this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-:-M9VXchXAvzuLC_Do4QG:b-6dkmu6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/jobs/job_scheduler.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9VVCTu6XSjEpKpokKy:-M9VVCTu6XSjEpKpokKz:bbwzpto) ([raw file](https://github.com/cockroachdb/cockroach/blob/74ac2e0d74ae56a10ee4ee56b360a2b02e56b801/pkg/jobs/job_scheduler.go#L90)):*
> ```Go
> // getFindSchedulesStatement returns SQL statement used for finding
> // scheduled jobs that should be started.
> func getFindSchedulesStatement(env jobSchedulerEnv, maxSchedules int64) string {
> ```

bikeshed: From the API, it's not obvious to me that passing in 0 here will result in all of the values being returned. I'm split on this because on one hand, although it is possible to ask for 0 schedules, it would be pointless. That being said, I was wondering what your thoughts on this were (if you had any feels on this). An alternative would be to make the sentinel negative + add a comment here, but again I'm torn because... why would anyone ask for 0 schedules. 
___
*[pkg/jobs/job_scheduler.go, line 250 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9VWvC_CJ9JTzKISfz_:-M9VWvC_CJ9JTzKISfza:b-g2t7b1) ([raw file](https://github.com/cockroachdb/cockroach/blob/74ac2e0d74ae56a10ee4ee56b360a2b02e56b801/pkg/jobs/job_scheduler.go#L250)):*
> ```Go
> 	pace := schedulerPaceSetting.Get(sv)
> 	if pace < minPacePeriod {
> 		pace = minPacePeriod
> ```

It would be nice to notify the user that their requested pace is too frequent... Logging here may be excessive, since it will log at every interval. Do you have any ideas here?

I don't think we necessarily need to do anything about it now, but we might want to add a TODO for us to keep this in mind?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50025)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/jobs/job_scheduler.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9VVCTu6XSjEpKpokKy:-M9VvuW307HLDbvgvmCE:b-jg8hdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/74ac2e0d74ae56a10ee4ee56b360a2b02e56b801/pkg/jobs/job_scheduler.go#L90)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

bikeshed: From the API, it's not obvious to me that passing in 0 here will result in all of the values being returned. I'm split on this because on one hand, although it is possible to ask for 0 schedules, it would be pointless. That being said, I was wondering what your thoughts on this were (if you had any feels on this). An alternative would be to make the sentinel negative + add a comment here, but again I'm torn because... why would anyone ask for 0 schedules. 
</blockquote></details>

This is a private, non-exported function.  The maxSchedules argument is there mostly for tests (and that's why I though it's okay to have allSchedules constant so that seeing 0, or -1 is not that surprising in tests).  I updated schedulerMaxJobsPerIterationSetting setting description to indicate that setting to 0 turns this limit off.

Wdyt?
___
*[pkg/jobs/job_scheduler.go, line 250 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9VWvC_CJ9JTzKISfz_:-M9Vvhej0pMP6vwUdzLK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/74ac2e0d74ae56a10ee4ee56b360a2b02e56b801/pkg/jobs/job_scheduler.go#L250)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

It would be nice to notify the user that their requested pace is too frequent... Logging here may be excessive, since it will log at every interval. Do you have any ideas here?

I don't think we necessarily need to do anything about it now, but we might want to add a TODO for us to keep this in mind?
</blockquote></details>

Done.

**Review by pbardea — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50025)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/jobs/job_scheduler.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-M9VVCTu6XSjEpKpokKy:-M9WDkKO2xfV5e7x4ZjZ:b86eoqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/74ac2e0d74ae56a10ee4ee56b360a2b02e56b801/pkg/jobs/job_scheduler.go#L90)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This is a private, non-exported function.  The maxSchedules argument is there mostly for tests (and that's why I though it's okay to have allSchedules constant so that seeing 0, or -1 is not that surprising in tests).  I updated schedulerMaxJobsPerIterationSetting setting description to indicate that setting to 0 turns this limit off.

Wdyt?
</blockquote></details>

Yep, that sounds pretty reasonable to me.

**Review by miretskiy — COMMENTED** [review]
fyi: I updated the tests -- they were flaky due to conversion from time.Time to string.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50025#-:-M9Yp_8mEMwTp3YMk3An:b-4fx6ku)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

**Pull request merged**
