### PR TITLE
[WIP][DNM]vendor,roachpb: pull github.com/cockroachdb/errors for IsType and use in roachpb

### PR DESCRIPTION
**Pull request by ajwerner**
This PR comes in 2 commits:

1) Pull github.com/cockroachdb/errors to master
2) Use `IsType()` in `roachpb.IsRangeNotFoundError()`

### CODE REVIEW

**Comment by ajwerner** [comment]
@knz does the sentry change in the library change the behavior in any way that would require a release note?

**Comment by knz** [comment]
It's not user-visible.

But the APIs have changed. So there needs to be some updates in crdb util/log, and perhaps sql/sqltelemetry too.

**Comment by ajwerner** [comment]
Grr the incompatibilities on some of these APIs are annoying. I'm working on it.

**Comment by ajwerner** [comment]
@knz this has very WIP work to adopt sentry-go in the 3rd commit.

**Review by knz — COMMENTED** [review]
1st and 3rd commit LGTM. Awesome! Thank you for doing this.

2nd commit makes me notice we made a little mistake. What do you think? Is there space in this PR for one more version dump?

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43930#-:-M-RbOcF0hB2ce1eSOwl:b-l5xmmm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/roachpb/errors.go, line 868 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43930#-M-Rb1jD7kwQsRexHyI5:-M-Rb1jEB2A4OH0PJRie:bgn3orv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5297827b06036a315eb2ddb76252d9a41724bfa/pkg/roachpb/errors.go#L868)):*
> ```Go
> // IsRangeNotFoundError returns true if err contains a *RangeNotFoundError.
> func IsRangeNotFoundError(err error) bool {
> 	return errors.IsType(err, (*RangeNotFoundError)(nil))
> ```

Gah, I am just noticing here this fails the general pattern promoted by the Go library:

- `errors.IsXX` = the *head* of the list is XX
- `errors.HasXX` = *some item in the list* has XX

I think your function ought to be called `errors.HasType`...

**Pull request closed without merging**
