### PR TITLE
util/log: fix redactability of logging tags

### LINKED ISSUE #72905: log: the 21.2 refactor removed auto-redaction for log tags
**Describe the problem**

In 21.1 and prior versions, the "tags" part of a log entry envelope were redacted if the sink flag `redact` was set to `true`.

In 21.2, this redaction is not taking place any more. This is a regression.

**To Reproduce**

`cockroach start-single-node ... --log='sinks: {stderr: {filter: INFO, redact: true}}'`

**Expected behavior**

redactable value are redacted

### PR DESCRIPTION
**Pull request by knz**
Fixes #72905.

Some time in the v21.2 cycle, the log entry preparation logic was
refactored and a mistake was introduced: the logging tags were not any
more subject to the redaction logic. The result was that redaction
markers were missing in log tag values, and if a value had contained
unbalanced redaction markers in a value string (say, as part of a SQL
table key), it would have caused log file corruption and possibly a
confidential data leak.

This patch fixes that, by preparing the logging tags in the same way
as the main message for each entry.

Release note (cli change): A bug affecting the redactability of
logging tags in output log entries has been fixed. This bug had
been introduced in the v21.2 release.

### CODE REVIEW

**Comment by knz** [comment]
the two bugs:

- redactable values in tags do not get redacted when `redact: true` is set
- redaction markers are not removed when `redactable: false` is set

**Review by abarganier — COMMENTED** [review]
Although this is my first time really digging into our `logEntry`/redaction code, I found the `formattableTags` API to be readable and straightforward - nice work. 

It seems like a test or two is causing issues with the iterator, although I'm unsure if it's just the test or if we truly need to account for the case where `bytes.IndexByte` returns `-1` :thinking: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72992#-:-MrO-xM-8hnV6UvpEwoa:b-w96opb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @knz)

___
*[pkg/util/log/formattable_tags.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72992#-MrO2l5K6glKCYCf9Ax6:-MrO2l5K6glKCYCf9Ax7:bgvuob8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6051cd59f691f0d6284d859a5c5be3ae3d4fba78/pkg/util/log/formattable_tags.go#L79)):*
> ```Go
> 	}
> 	// Advance the cursor to the beginning of the first next value.
> 	nv := bytes.IndexByte(i.tags, 0)
> ```

should we code defensively against a case where `bytes.IndexByte()` returns `-1`? 



_Code quote:_
```Go
nv := bytes.IndexByte(i.tags, 0)
```
___
*[pkg/util/log/formattable_tags.go, line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72992#-MrNwoxG6PhkD4aLWlUL:-MrNwoxG6PhkD4aLWlUM:b-u33kzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6051cd59f691f0d6284d859a5c5be3ae3d4fba78/pkg/util/log/formattable_tags.go#L136)):*
> ```Go
> 		if len(val) > 0 {
> 			if len(key) != 1 {
> 				w.SafeRune('=')
> ```

I'm curious, what does a `key` with a length of 1 represent/imply? 



_Code quote:_
```Go
			if len(key) != 1 {
				w.SafeRune('=')
			}
```

**Review by knz — COMMENTED** [review]
> It seems like a test or two is causing issues with the iterator,

it was just a linter error. Fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72992#-:-MrOZ67_4LiNPGlk4oLi:bf0rklo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier)

___
*[pkg/util/log/formattable_tags.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72992#-MrO2l5K6glKCYCf9Ax6:-MrOYhby8EooKjZdOP8G:bgb645y) ([raw file](https://github.com/cockroachdb/cockroach/blob/6051cd59f691f0d6284d859a5c5be3ae3d4fba78/pkg/util/log/formattable_tags.go#L79)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

should we code defensively against a case where `bytes.IndexByte()` returns `-1`? 
</blockquote></details>

No need - it's an invariant of the `formattableTags` that there's always a value for every key, possibly empty.
___
*[pkg/util/log/formattable_tags.go, line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72992#-MrNwoxG6PhkD4aLWlUL:-MrOYn5lDqFTQYt8_9D2:b-wkcpvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6051cd59f691f0d6284d859a5c5be3ae3d4fba78/pkg/util/log/formattable_tags.go#L136)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

I'm curious, what does a `key` with a length of 1 represent/imply? 
</blockquote></details>

We skip the `=` sign for 1-letter keys: we write "n1" in logs, not "n=1".

**Comment by knz** [comment]
oh the test in TestStoreRangeMergeWithData reveals there may be nul bytes in keys or values. Looking into it now.

**Comment by knz** [comment]
> oh the test in TestStoreRangeMergeWithData reveals there may be nul bytes in keys or values. Looking into it now.

Fixed.

**Review by abarganier — APPROVED** [review]
:lgtm:, thank you for fixing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72992#-:-MrSqCms3wrOLBYDbSbY:b-xwvw7z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @knz)

___
*[pkg/util/log/formattable_tags.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72992#-MrO2l5K6glKCYCf9Ax6:-MrSq0njCl6-ZgMqJEij:b-q9310n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6051cd59f691f0d6284d859a5c5be3ae3d4fba78/pkg/util/log/formattable_tags.go#L79)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

No need - it's an invariant of the `formattableTags` that there's always a value for every key, possibly empty.
</blockquote></details>

Ack, with the addition of `escapeNulBytes` it seems like we're good here :thumbsup: 
___
*[pkg/util/log/formattable_tags.go, line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72992#-MrNwoxG6PhkD4aLWlUL:-MrSq-71C4SopdpXWfP0:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6051cd59f691f0d6284d859a5c5be3ae3d4fba78/pkg/util/log/formattable_tags.go#L136)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We skip the `=` sign for 1-letter keys: we write "n1" in logs, not "n=1".
</blockquote></details>

Ack.

**Comment by knz** [comment]
TFYR!

bors r=abarganier

**Comment by knz** [comment]
blathers backport 21.2

**Pull request merged**
