### PR TITLE
Update golang.org/x deps

### PR DESCRIPTION
**Pull request by RaduBerinde**
Changes:
 - https://github.com/golang/crypto/compare/3d3f9f41...505ab145
 - https://github.com/golang/net/compare/c73622c7...351d144f
 - https://github.com/golang/oauth2/compare/6881fee4...d668ce99
 - https://github.com/golang/perf/compare/4469e6ce...6e6d33e2
 - https://github.com/golang/sync/compare/8e0aa688...42b31787
 - https://github.com/golang/sys/compare/95c65762...a5c9d58d
 - https://github.com/golang/time/compare/6dc17368...85acf8d2
 - https://github.com/golang/tools/compare/90b807ad...22934f0f

Informs #30774.

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]

**Comment by tbg** [comment]
Did you go through the changelogs? I looked at crypto (thankfully very short), but not the others.

**Comment by tbg** [comment]
LGTM
`sys` is long, skimmed it less thoroughly (>200 commits)
`tools` is massive (474 commits), didn't look

**Comment by RaduBerinde** [comment]
Thanks! I made a pass through them as well, had to kind of skim through `sys` and `tools`.

bors +

**Pull request merged**
