### PR TITLE
sql: ignore empty statements during Prepare

### LINKED ISSUE #9093: pgwire: empty query should result in emptyresponse, not error/commandcomplete
Found by @fishcakez in https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-237389617:

*An empty query will fail with an error, postgresql handles this with an EmptyQueryResponse message, instead of CommandComplete. This may not matter to cockroach.*

Note that this is may appear to be a dup of #3852 but the fix to that issue didn't change what happens for empty queries.

### LINKED ISSUE #9518: CockroachDB may not properly support JDBC's isValid() API
Reported by @theangryangel  in https://github.com/theangryangel/logstash-output-jdbc/issues/53#issuecomment-242997716

Pertains to this line of original code: https://github.com/theangryangel/logstash-output-jdbc/blob/3dc76277827aa42cecfad0cbf4a6c3f7b33b6ea0/lib/logstash/outputs/jdbc.rb#L153

In short: logstash initializes the DB connection via JDBC, performs some initial configuration then calls Connection.isValid() to see if CockroachDB accepted the configuration. If the connection is OK it is returned back to the rest of the software for further use.

In the initial report isValid() was returning false. 

My initial interpretation was that some configuration prior to the call to isValid wasn't recognized by CockroachDB, resulting in the server closing the connection (or something similar). **However the code was since modified to bypass the call to isValid and apparently the connection can be used like this just fine** (see https://github.com/theangryangel/logstash-output-jdbc/commit/f46fd580487b8ca2e79fe10ec890638e8202a051) suggesting that isValid() itself may not be supported properly.

If so we need to investigate a small repro using JDBC and calling isValid() to see what really happens.

For reference the official doc for isValid is to be found here: http://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html?is-external=true#isValid-int-

Note in particular the doc specifies " *The driver shall submit a query on the connection or use some other mechanism that positively verifies the connection is still valid when this method is called* " which suggests some active support from the DB is required.

@theangryangel please chime in to confirm that my analysis is correct.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #9093
Fixes #9518

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9811)

### CODE REVIEW

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/pgwire_test.go, line 848 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811#-KTVlI9YOLtfvG72IwwA:-KTVlI9Z58LMuna0Nx5V:b-enildn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb16f766aa839dd2e957909642a5896f47d5c02/sql/pgwire_test.go#L848)):*
> ```Go
> 				}
> 			} else {
> 				if rowsAffected, _ := result.RowsAffected(); rowsAffected != test.rowsAffected {
> ```

Why do we no longer want to check the error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811#-:-KTVldlzr_OllRGbt_GG:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/executor.go, line 349 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811#-KTVuujXVOnjv71XWqdN:-KTVuqR5O5II030OzJQD:bba5dh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb16f766aa839dd2e957909642a5896f47d5c02/sql/executor.go#L349)):*
> ```Go
> 		return nil, err
> 	}
> 	if len(stmts) > 1 {
> ```

```
switch len(stmts) {
...
}
```

---

*[sql/pgwire_test.go, line 848 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811#-KTVlI9YOLtfvG72IwwA:-KTVv41sjoloNPdc4sDb:b5nvces) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb16f766aa839dd2e957909642a5896f47d5c02/sql/pgwire_test.go#L848)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Why do we no longer want to check the error?
</details>
+1, let's still check it (string comparison, womp womp).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/pgwire_test.go, line 848 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811#-KTVlI9YOLtfvG72IwwA:-KTWLEl2kDC5w6GDC34S:bbdgh7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb16f766aa839dd2e957909642a5896f47d5c02/sql/pgwire_test.go#L848)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> +1, let's still check it (string comparison, womp womp).
</details>
Because in this specific case it's really, really stupid. We have to add a new property that is the rowsAffectedError (can't use the existing error field because that's used for something else) and then do the thing to make sure both have the same error or neither do. It's a more lines of code for just the stupidest error. But whatever I'll add it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811)*

**Comment by knz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/pgwire_test.go, line 848 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811#-KTVlI9YOLtfvG72IwwA:-KTgelxBlUfdL7hyA9O3:b-uni644) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb16f766aa839dd2e957909642a5896f47d5c02/sql/pgwire_test.go#L848)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Because in this specific case it's really, really stupid. We have to add a new property that is the rowsAffectedError (can't use the existing error field because that's used for something else) and then do the thing to make sure both have the same error or neither do. It's a more lines of code for just the stupidest error. But whatever I'll add it. 
</details>
No, just keep it simple:
```
if rowsAffected, err := result.RowsAffected(); rowsAffected != test.rowsAffected {
  t.Errorf("%s: %v: expected %v, got %v (error %+v)", query, test.qargs, test.rowsAffected, rowsAffected, err)
}
```

No need for an additional test field.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811#-:-KTgf3HImS-cTJsjJnze:bnfp4nl)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/pgwire_test.go, line 848 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811#-KTVlI9YOLtfvG72IwwA:-KTgucAMG6KSVq7wb0WO:b-9hw71e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebb16f766aa839dd2e957909642a5896f47d5c02/sql/pgwire_test.go#L848)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> No, just keep it simple:
> ```
> if rowsAffected, err := result.RowsAffected(); rowsAffected != test.rowsAffected {
>   t.Errorf("%s: %v: expected %v, got %v (error %+v)", query, test.qargs, test.rowsAffected, rowsAffected, err)
> }
> ```
> 
> No need for an additional test field.
</details>
This won't catch the case where rowsAffected returns 0 and an error if test.rowsAffected is also 0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/pgwire_test.go, line 855 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811#-KTkHO6el3kJBN3c60UF:-KTkHO6el3kJBN3c60UG:b-acoj2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5ac4c74c53e9f750f85b47ce6c6524044abcfe/sql/pgwire_test.go#L855)):*
> ```Go
> 			} else {
> 				rowsAffected, err := result.RowsAffected()
> 				hasRAErr := err != nil
> ```

eh, this could be stronger; in general, we should not accept just any error here; this is what testutils.IsError is for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9811)*

**Pull request merged**
