### PR TITLE
sql: fixes and helpers for zone partitioning

### PR DESCRIPTION
**Pull request by benesch**
Various fixes and helpers needed for zone partitioning.

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone.go, line 146 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHHDQ5QL2tqQmiqOSo:-KyHHDQ5QL2tqQmiqOSp:b-ih5a6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/config/zone.go#L146)):*
> ```Go
> 		return 0, err
> 	}
> 	tn = zs.Table.Table.TableName()
> ```

feels like these changes want a test

---

*[pkg/sql/config.go, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHGWVMBSoC3XOPlYSB:-KyHGWVMBSoC3XOPlYSC:biyy0up) ([raw file](https://github.com/cockroachdb/cockroach/blob/713842452962dc49083f1c670fea409bf03f4dc0/pkg/sql/config.go#L136)):*
> ```Go
> }
> 
> var GenerateSubzoneSpansHook = func(
> ```

call this GenerateSubzoneSpans to match our other hooks (which don't have a suffix)

---

*[pkg/sql/parser/sql.y, line 109 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHGt7fJbW7MGIm1cxr:-KyHGt7fJbW7MGIm1cxs:b3afu12) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/sql/parser/sql.y#L109)):*
> ```Yacc
>     return u.val.([]string)
> }
> func (u *sqlSymUnion) newTableWithIdx() *TableNameWithIndex {
> ```

maybe tableWithIdxPtr? not sure the contextual naming helps the readability here

---

*[pkg/sql/sqlbase/structured.go, line 1494 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHHdMb-usPrAtLkN6y:-KyHHdMb-usPrAtLkN6z:b-j7vlye) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/sql/sqlbase/structured.go#L1494)):*
> ```Go
> // the partition with the specified name belongs to. If no such partition
> // exists, an error is returned.
> func (desc *TableDescriptor) FindPartitionByName(
> ```

I know this is wordy but since you're only including NonDrop indexes, can you include NonDrop in the name, plz?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-:-KyHHigrY1jsX0czpBSH:bnfp4nl)*

**Comment by benesch** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/config/zone.go, line 146 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHHDQ5QL2tqQmiqOSo:-KyHVC2_9dzR2E2nmoJN:bmi445e) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/config/zone.go#L146)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

feels like these changes want a test
</blockquote></details>

Would you accept "my next PR will no longer panic" as a test? I'm fairly sure there's no present code path that tickles the panic; the tests in config/zone_test.go are pretty comprehensive.

---

*[pkg/sql/config.go, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHGWVMBSoC3XOPlYSB:-KyHT_skAvkhMT4091tv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/713842452962dc49083f1c670fea409bf03f4dc0/pkg/sql/config.go#L136)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

call this GenerateSubzoneSpans to match our other hooks (which don't have a suffix)
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 109 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHGt7fJbW7MGIm1cxr:-KyHTlMyDVT5gEn1ODZF:b-7z0xa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/sql/parser/sql.y#L109)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

maybe tableWithIdxPtr? not sure the contextual naming helps the readability here
</blockquote></details>

Following `newNormalizableTableName` and `normalizableTableName`'s lead. Thoughts?

---

*[pkg/sql/sqlbase/structured.go, line 1494 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHHdMb-usPrAtLkN6y:-KyHV76a3_yG6SjKnSi1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/sql/sqlbase/structured.go#L1494)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I know this is wordy but since you're only including NonDrop indexes, can you include NonDrop in the name, plz?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825)*

**Comment by danhhz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone.go, line 146 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHHDQ5QL2tqQmiqOSo:-KyI2WXmWxDpyEQ8g2JF:b-r89ylq) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/config/zone.go#L146)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Would you accept "my next PR will no longer panic" as a test? I'm fairly sure there's no present code path that tickles the panic; the tests in config/zone_test.go are pretty comprehensive.
</blockquote></details>

I guess I don't understand the problem that's being fixed. And the commit message doesn't really have any detail

---

*[pkg/sql/parser/sql.y, line 109 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHGt7fJbW7MGIm1cxr:-KyI3-seKU8BwSZsqsLw:bu8mqes) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/sql/parser/sql.y#L109)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Following `newNormalizableTableName` and `normalizableTableName`'s lead. Thoughts?
</blockquote></details>

ack. consistency with surrounding code trumps

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825)*

**Comment by benesch** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/config/zone.go, line 146 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHHDQ5QL2tqQmiqOSo:-KyI9tXruTjeA3BtzcmD:bbmubv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/config/zone.go#L146)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I guess I don't understand the problem that's being fixed. And the commit message doesn't really have any detail
</blockquote></details>

Yeah, it's kind of hard to explain without the next PR of context. Maybe I split out too much. Removed from this PR; I'll include it in the next one with more of an explanation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825)*

**Comment by benesch** [comment]
I had to remove the last commit because the function was unused. I'll ship it in the next PR. Sigh.

**Comment by danhhz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/config/zone.go, line 146 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHHDQ5QL2tqQmiqOSo:-KyIKT9uGurS7O5JzQ3X:b-fi53wk) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/config/zone.go#L146)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, it's kind of hard to explain without the next PR of context. Maybe I split out too much. Removed from this PR; I'll include it in the next one with more of an explanation.
</blockquote></details>

oof. what a hassle, sorry. perhaps in retrospect my suggestion for how to split up the mega-pr was more work than it's worth

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825)*

**Comment by benesch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/config/zone.go, line 146 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825#-KyHHDQ5QL2tqQmiqOSo:-KyILwnYUojV_SJXkypM:bp47bcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f965b832aa95193273b85044249e36384006ae/pkg/config/zone.go#L146)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

oof. what a hassle, sorry. perhaps in retrospect my suggestion for how to split up the mega-pr was more work than it's worth
</blockquote></details>

Not your fault!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19825)*

**Comment by benesch** [comment]
TFTR! One mega-PR on its way.

**Pull request merged**
