### PR TITLE
vendor: bump pebble to f63b6f081cc2a42fb7bb5ed5f916de50a9b11d18

### PR DESCRIPTION
**Pull request by petermattis**
* internal/cache: restrict when finalizers are used
* tool: remove use of runtime.SetFinalizer
* internal/cache: remove the "alloc cache"
* *: update the vendored modules
* db: format L6 score as "-" since it is not used
* *: Use L0SubLevels to pick base/intra-L0 compactions
* db: fix estimated compaction debt calculation
* internal/record: remove an unnecessary allocation in LogWriter

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@nvanbenschoten I believe this disables all use of `runtime.SetFinalizer` in Pebble for "race" builds. I'd be curious to know if the false-positive race is still reproducible.

**Review by itsbilal — APPROVED** [review]
:lgtm: though unfortunately you'll have to rebase vendor, sorry for not rubber stamping this earlier!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49405#-:-M8M8p7K5UVoEVUmeC06:b-wx87h8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by petermattis** [comment]
TFTR!

bors r+

**Comment by petermattis** [comment]
TestLogic timed out. Retrying.

bors r+

**Pull request merged**
