### PR TITLE
[WIP] sql: refactor the statement pretty-printer and implement EXPLAIN(TYPES)

### PR DESCRIPTION
**Pull request by knz**
The first part of this patch replaces the pretty-printing using a tree of String() calls
by a NodeFormatter interface common to all syntax object. This interface
allows caller code to pass formatting flags throughout the pretty
printing. This can be used later to implement conditional
printing of node details (e.g. typing information).

A side effect is a performance improvement: prior to this patch String
and bytes.Buffer objects would be created and destroyed throughout the
recursion, causing pressure on memory allocation. With this patch a
single Buffer object is used per top-level request to the
pretty-printer.

The second part of this patch introduces a new features: the statement `EXPLAIN (TYPES)`
to inspect the types of intermediate results in a query plan.

Known limitation: `EXPLAIN(TYPES)` cannot be applied on statements
containing placeholders ($xxx).

As a side effect this patch also fixes a bug, where EXPLAIN(PLAN)
would cause a panic when invoked on an INSERT statement.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6424)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed commit 1.

---

Reviewed 32 of 32 files at r1.
Review status: 29 of 48 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[sql/parser/alter_table.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd9-DBFqQLXl54WKI9:-KGd9-DBFqQLXl54WKIA:221612105) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/alter_table.go#L46)):*
No String method?

---

*[sql/parser/create.go, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd39zw-mir4bu47aRL:-KGd39zx64Pd7tTp8fG-:871720938) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/create.go#L55)):*
It seems like in most places you're avoiding the format printing if possible. This seems like another good candidate.

---

*[sql/parser/datum.go, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd3uQAf3SCH-bOpErh:-KGd3uQAf3SCH-bOpEri:1117523690) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/datum.go#L197)):*
I'm not positive, but I would assume that `buf.WriteString(strconv.FormatBool(...))` would perform a little better that this. Same below. It might make things harder to read though, so feel free to ignore.

---

*[sql/parser/datum.go, line 905 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd4VIgsFLX2sH4CoJf:-KGd4VIh0tiWJCdMAoWF:-2123318916) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/datum.go#L905)):*
Twice?

---

*[sql/parser/drop.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd4gBIhaO8JbpGXKlj:-KGd4gBIhaO8JbpGXKlk:-1396467559) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/drop.go#L80)):*
Can this be split up to avoid formatting?

---

*[sql/parser/encode.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd4qpnP6yflhmVG73G:-KGd4qpnP6yflhmVG73H:1735759195) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/encode.go#L48)):*
Are you sure you want to allocate here?

---

*[sql/parser/encode.go, line 98 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd54WI4qhwi2ZS-4AU:-KGd54WI4qhwi2ZS-4AV:160841994) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/encode.go#L98)):*
Same as above.

---

*[sql/parser/expr.go, line 746 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd6WYfEwXR0QbQsvzx:-KGd6WYfEwXR0QbQsvzy:216287425) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/expr.go#L746)):*
Should this be moved below with the rest?

---

*[sql/parser/expr.go, line 1009 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd6TFareoRfPmU8X40:-KGd6TFareoRfPmU8X41:979159443) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/expr.go#L1009)):*
This sticks out like a sore thumb.

---

*[sql/parser/format.go, line 37 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd7FUkTz0I4lhcBln2:-KGd7FUkTz0I4lhcBln3:1911496861) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/format.go#L37)):*
Extra spaces?

---

*[sql/parser/stmt.go, line 346 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd8j_N2ruFU0KOW4OZ:-KGd8j_N2ruFU0KOW4O_:-219244031) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/stmt.go#L346)):*
I think I saw a few others scattered throughout the code instead of here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-:-KGd9T85vsqy0Xs2ftux:-93120350)*

**Comment by nvanbenschoten** [comment]
Reviewed commit 2. This is really cool!

---

Reviewed 1 of 32 files at r1, 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[sql/explain.go, line 154 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdAj3sRSoLnvLOTkVb:-KGdAj3sRSoLnvLOTkVc:148719369) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/explain.go#L154)):*
What exactly does it mean to call `ExplainPlan` on a types node (and other mixed explains like this)?

---

*[sql/plan.go, line 450 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd9xdDM07wp_WnZwtp:-KGd9xdDM07wp_WnZwtq:-825583654) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/plan.go#L450)):*
`elt`? What is that supposed to stand for?

---

*[sql/sort.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdAWO05-xDcdz4Nqv2:-KGdAWO05-xDcdz4Nqv3:1538393322) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/sort.go#L254)):*
No types for `sortNodes`?

---

*[sql/union.go, line 170 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdAutySVicFAlOxc-q:-KGdAutySVicFAlOxc-r:1825187488) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/union.go#L170)):*
No types?

---

*[sql/testdata/explain_types, line 55 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdBU-fE224jqYcDx_f:-KGdBU-fE224jqYcDx_g:701391992) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/testdata/explain_types#L55)):*
Because this is all new and we're supporting a number of different `planNode` types, we should probably have at least one test for each.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-:-KGdBnQL2ob7hOQ865YF:-1179935466)*

**Comment by knz** [comment]
Review status: 22 of 48 files reviewed at latest revision, 16 unresolved discussions, some commit checks pending.

---

*[sql/explain.go, line 154 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdAj3sRSoLnvLOTkVb:-KGdBwZlhHZrCpvUbp36:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/explain.go#L154)):*
Done.

---

*[sql/plan.go, line 450 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd9xdDM07wp_WnZwtp:-KGdBzn9E9-skRrZ_pOP:2085502819) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/plan.go#L450)):*
"element"

---

*[sql/sort.go, line 254 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdAWO05-xDcdz4Nqv2:-KGdC0rlZguFu8jokxIw:149792423) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/sort.go#L254)):*
There's nothing in the sortNode itself that's worth explaining. The result columns are explained by explain.go already. Most of the useful types come from sortNode's child plan.

---

*[sql/union.go, line 170 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdAutySVicFAlOxc-q:-KGdCDDwD_h3AXHnzL_D:-1582418045) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/union.go#L170)):*
See above.

---

*[sql/parser/alter_table.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd9-DBFqQLXl54WKI9:-KGdBUcdoHWdCKDuhaj3:592794063) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/alter_table.go#L46)):*
I avoided creating the methods unless they were used somewhere else. I assumed the first person to need them can readily add them.

---

*[sql/parser/create.go, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd39zw-mir4bu47aRL:-KGdCFOF5a0vfuoSpZLF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/create.go#L55)):*
Done.

---

*[sql/parser/datum.go, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd3uQAf3SCH-bOpErh:-KGdCePxXIi4Q3Iizl18:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/datum.go#L197)):*
Done.

---

*[sql/parser/datum.go, line 905 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd4VIgsFLX2sH4CoJf:-KGdCiYa7KIMXPjaqfgA:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/datum.go#L905)):*
Done.

---

*[sql/parser/drop.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd4gBIhaO8JbpGXKlj:-KGdCslvjCXK4pP7Rkho:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/drop.go#L80)):*
Done.

---

*[sql/parser/encode.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd4qpnP6yflhmVG73G:-KGdDAorWrA3P766Mbmr:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/encode.go#L48)):*
Done.

---

*[sql/parser/encode.go, line 98 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd54WI4qhwi2ZS-4AU:-KGdDBb8K_PCPfIG6yPw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/encode.go#L98)):*
Done.

---

*[sql/parser/expr.go, line 746 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd6WYfEwXR0QbQsvzx:-KGdDRdSguDKTAC2QYW2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/expr.go#L746)):*
Done.

---

*[sql/parser/expr.go, line 1009 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd6TFareoRfPmU8X40:-KGdEZ3AOkJT5tRsD0ym:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/expr.go#L1009)):*
Done.

---

*[sql/parser/format.go, line 37 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd7FUkTz0I4lhcBln2:-KGdEjeCtk5sHz214FRP:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/format.go#L37)):*
Done.

---

*[sql/parser/stmt.go, line 346 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd8j_N2ruFU0KOW4OZ:-KGdFdL8GN8Zxl-4yGfo:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/stmt.go#L346)):*
Done.

---

*[sql/testdata/explain_types, line 55 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdBU-fE224jqYcDx_f:-KGdFfF0Cp8G6Nv6qlJM:961517262) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/testdata/explain_types#L55)):*
Yeah probably but then I'd like to have your PR merged first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424)*

**Comment by knz** [comment]
Review status: 22 of 48 files reviewed at latest revision, 16 unresolved discussions, some commit checks pending.

---

*[sql/explain.go, line 154 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdAj3sRSoLnvLOTkVb:-KGdGZqplq8brYqiH5ve:-1041123632) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/explain.go#L154)):*
Sorry the "Done" was meant for something else. There is no special meaning, but since the syntax allows `EXPLAIN EXPLAIN foo ..` it needs to make sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424)*

**Comment by nvanbenschoten** [comment]
Review status: 22 of 48 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/plan.go, line 450 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd9xdDM07wp_WnZwtp:-KGdG_jJBsjLReMO4xzp:802855183) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/plan.go#L450)):*
Huh, I would definitely favor `elem` for consistency with the rest of our code base.

---

*[sql/parser/alter_table.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd9-DBFqQLXl54WKI9:-KGdH6R1R7o-0jaWyUMn:-911270128) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/alter_table.go#L46)):*
I'm not sure I would rely on that. It's very common practice to `fmt.Println` when debugging, so it would be really nice for everything to retain their `String` methods.

---

*[sql/parser/expr.go, line 1003 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdHdx350t8kYqAq6TT:-KGdHdx4ktoM58Yet6_G:2105859370) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ec00fdffc559c4c5bc4bbaee712038ddf47e3e7/sql/parser/expr.go#L1003)):*
Now this sticks out ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424)*

**Comment by RaduBerinde** [comment]
The new functionality is badass!

---

Review status: 22 of 48 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/explain.go, line 154 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdAj3sRSoLnvLOTkVb:-KGdH9VrGRmh5XZZoQZz:-417484121) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/explain.go#L154)):*
Hm, I think we should disallow EXPLAIN EXPLAIN

---

*[sql/explain.go, line 161 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdHLB3HyYApwA-wW7d:-KGdHLB3HyYApwA-wW7e:1385755762) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/explain.go#L161)):*
Haven't seen blocks like this in our codebase, what's the reasoning? just to make sure `colDesc` goes out of scope early? The compiler/optimizer should be able to easily figure that out.

---

*[sql/explain.go, line 215 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdHpZ29ezZsFk3yhnV:-KGdHpZ29ezZsFk3yhnW:-274567884) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/explain.go#L215)):*
empty line before the function

---

*[sql/parser/format.go, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdFqGFNWXyWEic8SZO:-KGdFqGGD9wx60nc-fvY:10242595) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/format.go#L22)):*
I was surprised to see this is an interface, do you really think we will need that? (as opposed to just a struct)
Is `fmtFlags` just a dummy function? (maybe add a comment)

If it's just to hide it from external packages, we can have an exported `FmtFlags` struct with unexported fields..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-:-KGdIjOAOdF20osDiPTF:2071123640)*

**Comment by knz** [comment]
Review status: 22 of 48 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/explain.go, line 154 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdAj3sRSoLnvLOTkVb:-KGdKOg1V4ZsjxXCDgzD:-1909155927) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/explain.go#L154)):*
Perhaps but that would belong to a different PR.

---

*[sql/explain.go, line 161 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdHLB3HyYApwA-wW7d:-KGdMGYI0mYBc5UNAsU9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/explain.go#L161)):*
Done.

---

*[sql/explain.go, line 215 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdHpZ29ezZsFk3yhnV:-KGdMGFNB8TCez35_lbN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/explain.go#L215)):*
Done.

---

*[sql/plan.go, line 450 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd9xdDM07wp_WnZwtp:-KGdMPIqqjJUOJqynxcH:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/plan.go#L450)):*
Done.

---

*[sql/parser/alter_table.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGd9-DBFqQLXl54WKI9:-KGdLRr0amY_RNgNVJVq:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/alter_table.go#L46)):*
Done.

---

*[sql/parser/expr.go, line 1003 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdHdx350t8kYqAq6TT:-KGdLV3CS-CYjKFINPAr:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ec00fdffc559c4c5bc4bbaee712038ddf47e3e7/sql/parser/expr.go#L1003)):*
Done.

---

*[sql/parser/format.go, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdFqGFNWXyWEic8SZO:-KGdLeU9ilyx_yjTGaPb:-164518583) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/format.go#L22)):*
I'm thinking about a pretty-printer with indentation in the future.  This will like having an interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424)*

**Comment by nvanbenschoten** [comment]
Review status: 22 of 48 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/parser/format.go, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdFqGFNWXyWEic8SZO:-KGdN2A_9wB0ljl8610c:-1147014856) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/format.go#L22)):*
Yeah this shocked me a little too, but as long as we always use the sentinel variables defined below, it seems fine to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424)*

**Comment by nvanbenschoten** [comment]
Review status: 22 of 48 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/parser/format.go, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdFqGFNWXyWEic8SZO:-KGdNJ8scpXIE69TFh8K:-1288389810) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/format.go#L22)):*
Actually, this is almost really bad. We need both of those defined as 

```
var FmtSimple FmtFlags = fmtFlags{showTypes: false}
var FmtShowTypes FmtFlags = fmtFlags{showTypes: true}
```

or I believe they're going to allocate on every use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424)*

**Comment by knz** [comment]
Review status: 22 of 48 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/parser/format.go, line 22 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdFqGFNWXyWEic8SZO:-KGdNg_2WBIg1bPZjS6c:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b243ea4c42b0dde5bb1274351cbbdd24e5689d7/sql/parser/format.go#L22)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 22 of 48 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/explain.go, line 154 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-KGdAj3sRSoLnvLOTkVb:-KGdngi43Mokv-mJtJ_x:317608458) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca4d35a61fd600a079fc15c0bb8f385ae59321d/sql/explain.go#L154)):*
Agreed, maybe file an issue so we don't forget

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6424#-:-KGdoEmZxXtG9pvcjyRY:1417088721)*

**Comment by knz** [comment]
So I've checked and apparently we reject explain explain in the syntax already.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by knz** [comment]
Closed in favor of #6482.

**Pull request closed without merging**
