### PR TITLE
base: accept Pebble options in StoreSpec

### LINKED ISSUE #50600: storage: allow specifying arbitrary Pebble options
We can pass arbitrary options through to RocksDB using the `--store=path=<path>,rocksdb=key1=val1;key2=val2` syntax. We should generalize this option setting to allow specifying arbitrary Pebble options. The RocksDB syntax is frequently confusing as it doesn't map cleanly to the OPTIONS format. For Pebble, I propose we use the OPTIONS format exactly with the extension that we translate `;` to `\n`. For example, in order to change `L0CompactionThreshold` and `L0StopWritesThreshold` you would specify:

```
--store=path=<path>,pebble=[Options];l0_compaction_threshold=2;l0_stop_writes_threshold=10
```

Parsing this would involve a `strings.Replace(..., ";", "\n")` before calling `pebble.Options.Parse`. 

Alternately, we could use the syntax `<section>.<key>=<value>` syntax. This would involve a slight repetition on the command line, but is possibly more natural:

```
--store=path=<path>,pebble=Options.l0_compaction_threshold=2;Options.l0_stop_writes_threshold=10
```

### PR DESCRIPTION
**Pull request by jbowens**
Accept Pebble storage engine options within the `--store` flag under a
`pebble=` key, eg:

`--store="path=/mnt/data,size=100GiB,pebble=[Options] delete_range_flush_delay=2s"`

The options are provided in the Pebble ini-style `OPTIONS` file format,
but with any white space delimiting lines.

I wasn't able to support values with spaces, because of ambiguity
between the bracketed stanzas and lists. In the below example, it's
ambiguous whether `[Level "0"]` is a new stanza or a list value for
the key `wal_dir`.
```
[Options]
  table_property_collectors=[]
  wal_dir=

[Level "0"]
  target_file_size=4096
```

I put no release note because the `rocksdb=` key [isn't documented](https://www.cockroachlabs.com/docs/stable/cockroach-start-single-node.html#store),
so I assumed the pebble key won't be either.

Fix #50600

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[pkg/base/store_spec.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52080#-MDUeopI6X0-AtY8VGs8:-MDUeopJ-0AZ97yY90Oy:bx9oh6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6d30aff214c4e554e2ac3d421f3bff7a1d4cec7/pkg/base/store_spec.go#L365)):*
> ```Go
> 			// them again later when constructing the store engine.
> 			var opts pebble.Options
> 			if err := opts.Parse(buf.String(), &pebble.ParseHooks{}); err != nil {
> ```

Nit: I think it is ok to pass `nil` for the `ParseHooks`.
___
*[pkg/server/config.go, line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52080#-MDUf7kB7Ilo-N9noE8V:-MDUf7kB7Ilo-N9noE8W:b-5ghkwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6d30aff214c4e554e2ac3d421f3bff7a1d4cec7/pkg/server/config.go#L552)):*
> ```Go
> 				pebbleConfig.Opts.Cache = pebbleCache
> 				pebbleConfig.Opts.MaxOpenFiles = int(openFileLimitPerStore)
> 				// If the spec contains Pebble options, set those too.
> ```

What if the spec contains RocksDB options? Should we print a warning or an error? Ditto for if the storage engine is RocksDB and Pebble options are specified.
___
*[pkg/server/config.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52080#-MDUf-Kt-zUfJPVl5zOZ:-MDUf-Kt-zUfJPVl5zO_:b-d6oph4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6d30aff214c4e554e2ac3d421f3bff7a1d4cec7/pkg/server/config.go#L554)):*
> ```Go
> 				// If the spec contains Pebble options, set those too.
> 				if len(spec.PebbleOptions) > 0 {
> 					err = pebbleConfig.Opts.Parse(spec.PebbleOptions, &pebble.ParseHooks{})
> ```

Nit: ditto about passing `nil` for the `ParseHooks`. And below as well.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/server/config.go, line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52080#-MDUf7kB7Ilo-N9noE8V:-MDVLTbJAIROp_8JdBre:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6d30aff214c4e554e2ac3d421f3bff7a1d4cec7/pkg/server/config.go#L552)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What if the spec contains RocksDB options? Should we print a warning or an error? Ditto for if the storage engine is RocksDB and Pebble options are specified.
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52080#-:-MDVqTGT3eMAds6iuDc4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by jbowens** [comment]
TFTR!

bors r+

**Pull request merged**
