### PR TITLE
opt: Improve performance of the cost-based optimizer's PREPARE phase

### PR DESCRIPTION
**Pull request by andy-kimball**
Store the cost-based optimizer's Memo struct in the PreparedStatement,
and then use that to speed up the planning process on each execution,
since the `optbuild` and `normalize` phases can be either skipped or
significantly reduced. If there are no placeholders, then the `explore`
phase can be skipped as well.

This PR significantly improves execution times when plans have been
prepared. The "old time" is the planning time when only the AST is
cached. The "new time" is the planning time when both the AST and
Memo data structures are cached.
```
name                               old time/op  new time/op  delta
Phases/kv-read/ExecBuild           24.6µs ± 2%  16.2µs ± 1%  -34.38%  (p=0.008 n=5+5)
Phases/kv-read-const/ExecBuild     24.9µs ± 1%   0.7µs ± 2%  -97.35%  (p=0.008 n=5+5)
Phases/tpcc-new-order/ExecBuild    91.8µs ± 3%  56.5µs ± 1%  -38.53%  (p=0.008 n=5+5)
Phases/tpcc-delivery/ExecBuild     67.6µs ± 1%  41.7µs ± 2%  -38.39%  (p=0.008 n=5+5)
Phases/tpcc-stock-level/ExecBuild   357µs ± 4%   182µs ± 1%  -48.87%  (p=0.008 n=5+5)
Exec/kv-read/ExecOpt                331µs ± 2%   187µs ± 2%  -43.67%  (p=0.008 n=5+5)
Exec/kv-read-const/ExecOpt          235µs ± 1%   160µs ± 1%  -31.83%  (p=0.008 n=5+5)
Exec/tpcc-new-order/ExecOpt         499µs ± 1%   275µs ± 1%  -44.77%  (p=0.008 n=5+5)
Exec/tpcc-delivery/ExecOpt          430µs ± 3%   243µs ± 1%  -43.49%  (p=0.008 n=5+5)
Exec/tpcc-stock-level/ExecOpt      1.03ms ± 1%  0.58ms ± 1%  -43.27%  (p=0.008 n=5+5)
```
Notice that the `kv-read-const` can skip almost all of planning, since it
contains no placeholders. Consequently, it takes only 700ns to plan.

With this change, end-to-end running times (on empty tables) for the
cost-based optimizer are typically lower for prepared queries than the
heuristic optimizer (old time=heuristic, new-time=cost-based):
```
name                        old time/op  new time/op  delta
Exec/kv-read/Exec            196µs ± 3%   187µs ± 2%   -4.78%  (p=0.008 n=5+5)
Exec/kv-read-const/Exec      198µs ± 1%   160µs ± 1%  -18.83%  (p=0.008 n=5+5)
Exec/tpcc-new-order/Exec     287µs ± 3%   275µs ± 1%   -4.04%  (p=0.008 n=5+5)
Exec/tpcc-delivery/Exec      245µs ± 2%   243µs ± 1%     ~     (p=0.421 n=5+5)
Exec/tpcc-stock-level/Exec   552µs ± 1%   583µs ± 1%   +5.54%  (p=0.008 n=5+5)
```
The `tpcc-stock-level` is a bit higher, since the cost-based optimizer is
currently missing constant-folding.

### CODE REVIEW

**Comment by andy-kimball** [comment]
CC: @petermattis, @jordanlewis

**Review by jordanlewis — DISMISSED** [review]
Great work! I think that we should add some additional testing. Specifically, I think you should add some tests that exercise the pgwire-level prepare/execute path, which is unfortunately not identical to the SQL prepare/execute path. We've had bugs in one but not the other before. Currently the best place to exercise that functionality is in the file `pkg/sql/pgwire/pgwire_test.go`.

> Reviewed 14 of 14 files at r1, 8 of 8 files at r2, 9 of 9 files at r3, 1 of 18 files at r4, 7 of 7 files at r5, 6 of 9 files at r6, 16 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-:-LLp4aq04p2A3jmoX0eq:b-ghiri6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/prepare, line 623 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLp54Dk65oWJ1e03_mP:-LLp54Dk65oWJ1e03_mQ:b7hdiix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19afef497e094b305d20b1f9a8a5663b4b54a532/pkg/sql/logictest/testdata/logic_test/prepare#L623)):*
> ```
> 
> statement ok
> COMMIT TRANSACTION
> ```

What about some tests that add or delete indexes? I see that the implementation treats that case identically to any other schema change, but I think it'd be a good kind of regression test nonetheless.
___
*[pkg/sql/opt/catalog.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLocYK1D8wHOy1fcsjy:-LLocYK1D8wHOy1fcsjz:b1vc0t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1938195b91b450f6e8649212abc42e83189936/pkg/sql/opt/catalog.go#L40)):*
> ```Go
> // data source changes in any way, then the fingerprint must also change. This
> // enables cached data sources (or other data structures dependent on the data
> // sources) to be invalidated when their schema changes.
> ```

It'd be nice to have a comment explaining that Fingerprint is the 32 bit descriptor ID and version id concatenated.
___
*[pkg/sql/opt/memo/memo.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLogK1L7IaZigAWiI_s:-LLogK1L7IaZigAWiI_t:b-7jw0m4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1938195b91b450f6e8649212abc42e83189936/pkg/sql/opt/memo/memo.go#L276)):*
> ```Go
> 	if len(left) != 0 && &left[0] != &right[0] {
> 		return true
> 	}
> ```

This code is not checking that all of the elements are the same. While it may be the case that today the search path isn't modified in place, I'm not so sure if that'll be true forever going forward. The search path is a very short array in almost all cases - I'd much prefer that we take the safe way out and compare the array element-wise.

**Review by andy-kimball — COMMENTED** [review]
Good idea. There are already a lot of prepare/execute tests in `pgwire_test.go` that will test this change. But I did add a new test which ensures that we invalidate the prepared plan when schema changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-:-LLpODI039LuWcCrDZQM:b-4cd1nx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/prepare, line 623 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLp54Dk65oWJ1e03_mP:-LLpN1bn5-LMNQmKaBZs:b-hsb2f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/19afef497e094b305d20b1f9a8a5663b4b54a532/pkg/sql/logictest/testdata/logic_test/prepare#L623)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What about some tests that add or delete indexes? I see that the implementation treats that case identically to any other schema change, but I think it'd be a good kind of regression test nonetheless.
</blockquote></details>

OK, I added an add/remove index case in the `execbuilder` tests. I can't add it here because to be useful it needs to inspect the plans (i.e. use `EXPLAIN`).
___
*[pkg/sql/opt/catalog.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLocYK1D8wHOy1fcsjy:-LLpOAOc89gVpJIXt2ZS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1938195b91b450f6e8649212abc42e83189936/pkg/sql/opt/catalog.go#L40)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It'd be nice to have a comment explaining that Fingerprint is the 32 bit descriptor ID and version id concatenated.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/memo.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLogK1L7IaZigAWiI_s:-LLp8Uyw5mmN4gMdXNQZ:b-rdcelb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1938195b91b450f6e8649212abc42e83189936/pkg/sql/opt/memo/memo.go#L276)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This code is not checking that all of the elements are the same. While it may be the case that today the search path isn't modified in place, I'm not so sure if that'll be true forever going forward. The search path is a very short array in almost all cases - I'd much prefer that we take the safe way out and compare the array element-wise.
</blockquote></details>

But this approach is actually stricter than comparing the array element-wise, since I'm checking that both slices point to the same array. Since the lengths are also the same, this guarantees the arrays would compare equal element-wise.

**Comment by RaduBerinde** [comment]
It's odd, but it looks like the PR contains some unrelated `storage` commits. Maybe try a rebase?

**Review by RaduBerinde — APPROVED** [review]
:lgtm_strong: 

Very nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-:-LLqrfpB02DFqHnINiLy:b-5u1ooj)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/expr_view_format.go, line 249 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLqks1X0yTDutmmFn0v:-LLqks1X0yTDutmmFn0w:b-51rq9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/24e61be7fb41d133a5a2d164d05dab4d3f5cb5e3/pkg/sql/opt/memo/expr_view_format.go#L249)):*
> ```Go
> 		}
> 		if logProps.Relational.HasPlaceholder {
> 			tp.Child("placeholder")
> ```

[nit] I would use "has-placeholder", `placeholder` makes the output a bit confusing
___
*[pkg/sql/opt/memo/list_storage.go, line 148 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLqlS6w4GudRJw3yzt9:-LLqlS6w4GudRJw3yztA:b-e51i4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/44f31e63a43c56d670cbdcde3d1ba0124df5013c/pkg/sql/opt/memo/list_storage.go#L148)):*
> ```Go
> // initFrom initializes the list storage with a copy of all lists from another
> // list storage. This list storage can then be modified independent of that one.
> func (ls *listStorage) initFrom(from *listStorage) {
> ```

This deserves a test (which tries to modify the two copies).
___
*[pkg/sql/opt/memo/private_storage.go, line 107 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLqmIU19G-844THvZyP:-LLqmIU19G-844THvZyQ:beoygs) ([raw file](https://github.com/cockroachdb/cockroach/blob/44f31e63a43c56d670cbdcde3d1ba0124df5013c/pkg/sql/opt/memo/private_storage.go#L107)):*
> ```Go
> 	}
> 	ps.privates = make([]interface{}, len(from.privates))
> 	copy(ps.privates, from.privates)
> ```

This requires that all privates are immutable. Which should be the case, but it would be good to document the requirement clearly somewhere (maybe in the comment for the `privateStorage` struct).
___
*[pkg/sql/opt/optgen/cmd/optgen/factory_gen.go, line 130 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLqquhj9RJKKmGtNztj:-LLqquhj9RJKKmGtNztk:bgiu1ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/50430e8b710e7d5798c9681c4f3f0c08388c52e1/pkg/sql/opt/optgen/cmd/optgen/factory_gen.go#L130)):*
> ```Go
> 
> // genAssignPlaceholders generates code that recursively walks a subtree looking
> // for Placeholder operators and replacing them with their assigned values. The
> ```

This is really cool!

[nit] Add something along the lines of "and recreating all expressions that had a placeholder inside their subtree (implicitly reapplying all normalization rules)"

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29686)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/list_storage.go, line 148 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLqlS6w4GudRJw3yzt9:-LLtliF43HRmvBY1ZBLx:bdi7q1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/44f31e63a43c56d670cbdcde3d1ba0124df5013c/pkg/sql/opt/memo/list_storage.go#L148)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This deserves a test (which tries to modify the two copies).
</blockquote></details>

Added a test. `TestMemoInitFrom` was also intended to indirectly test the list storage (and private storage), since `Memo.InitFrom` is the exported method.
___
*[pkg/sql/opt/memo/private_storage.go, line 107 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLqmIU19G-844THvZyP:-LLtkZSD9FJwuwN8lmOL:b-h58x43) ([raw file](https://github.com/cockroachdb/cockroach/blob/44f31e63a43c56d670cbdcde3d1ba0124df5013c/pkg/sql/opt/memo/private_storage.go#L107)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This requires that all privates are immutable. Which should be the case, but it would be good to document the requirement clearly somewhere (maybe in the comment for the `privateStorage` struct).
</blockquote></details>

Hashing privates values already required that they be immutable, so this is not a new requirement. I added a comment to this effect on `privateStorage`.

**Review by andy-kimball — COMMENTED** [review]
Something really strange is happening with GIT. It keep adding others' commits to my pushes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-:-LLty3cM-g1KmEzOKbAW:bdwcr5c)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andy-kimball — COMMENTED** [review]
I see, all the issues with GIT are stemming from issues introduced by this PR: https://github.com/cockroachdb/cockroach/pull/29812

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-:-LLtzDsM7Hosr7SxeSr1:bu8l0if)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by rytaft — DISMISSED** [review]
:lgtm_strong:  Nicely done!

> Reviewed 10 of 16 files at r13, 32 of 32 files at r17, 7 of 7 files at r18, 10 of 10 files at r19, 19 of 19 files at r20.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-:-LM30Dke-t4C8uwLtcn9:becun86)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/plan.go, line 416 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2ukUe4tz2B9sAWKab:-LM2ukUe4tz2B9sAWKac:b-911ahb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded20cd554698492a76ada18b1dcc32b3c5875ed/pkg/sql/plan.go#L416)):*
> ```Go
> 	// If a prepared memo doesn't yet exist, or if it's been invalidated by schema
> 	// or other changes, then entirely rebuild the memo from the AST.
> 	if prepMemo == nil || inPreparePhase || prepMemo.IsStale(ctx, p.EvalContext(), &catalog) {
> ```

Mention that we also always build if in the prepare phase.
___
*[pkg/sql/logictest/testdata/logic_test/prepare, line 438 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2wR17BVSXOu2mSyis:-LM2wR17BVSXOu2mSyit:bqe3xr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded20cd554698492a76ada18b1dcc32b3c5875ed/pkg/sql/logictest/testdata/logic_test/prepare#L438)):*
> ```
> #
> # Test prepared statements that rely on context, and ensure they are invalidated
> # when that context changes.
> ```

Is it worth adding a couple of tests here with placeholders?
___
*[pkg/sql/opt/metadata_test.go, line 101 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2hPtN21LfDpmbl_r2:-LM2hPtN21LfDpmbl_r3:bta89fy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c862144fc979e7c12cb468bdc795b75484bff2e1/pkg/sql/opt/metadata_test.go#L101)):*
> ```Go
> 	}
> 
> 	// Add a table reference without a name to the metadata.
> ```

This comment seems stale -- `TabName` is set to "b" below
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1077 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2mlxs9-d1E_zCenT3:-LM2mlxs9-d1E_zCenT4:b-i7eqbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/585ac2f1aed189f0a116662ff9d2e0d7d057a7f8/pkg/sql/opt/memo/logical_props_builder.go#L1077)):*
> ```Go
> 	}
> 
> 	// By default, derive OuterCols and CanHaveSideEffects from all children,
> ```

and `HasPlaceholder`
___
*[pkg/sql/opt/memo/memo.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLogK1L7IaZigAWiI_s:-LM2jua37PQLEEs1Xklp:b-61cb50) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1938195b91b450f6e8649212abc42e83189936/pkg/sql/opt/memo/memo.go#L276)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

But this approach is actually stricter than comparing the array element-wise, since I'm checking that both slices point to the same array. Since the lengths are also the same, this guarantees the arrays would compare equal element-wise.
</blockquote></details>

But what if the array is modified in place as Jordan suggested?
___
*[pkg/sql/opt/memo/memo.go, line 258 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2i9eq1mlpkjondqPO:-LM2i9eq1mlpkjondqPP:bd0bj2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c862144fc979e7c12cb468bdc795b75484bff2e1/pkg/sql/opt/memo/memo.go#L258)):*
> ```Go
> //   4. Data source schema: this determines most aspects of how the query is
> //      compiled.
> //   5. Data source privileges: current user may no longer has access to one or
> ```

[nit] may no longer has -> may no longer have
___
*[pkg/sql/opt/memo/memo.go, line 223 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2phbR7rjyn1oXhOgP:-LM2phbS144FMrXxBNxs:b683lo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/642be2634f0291e91930eb454a6a881406634fa0/pkg/sql/opt/memo/memo.go#L223)):*
> ```Go
> 
> 	// Copy the groups.
> 	m.groups = m.groups[:0]
> ```

is it worth adding a check here to see if `m.groups` is nil, and if so, allocate space for `len(from.groups)` groups?
___
*[pkg/sql/opt/memo/memo.go, line 419 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2qNxyBqKGgx8NfP1q:-LM2qNxyBqKGgx8NfP1r:b7ty2em) ([raw file](https://github.com/cockroachdb/cockroach/blob/642be2634f0291e91930eb454a6a881406634fa0/pkg/sql/opt/memo/memo.go#L419)):*
> ```Go
> // the creation of a new memo group with the normalized expression as its first
> // expression. If the expression is already part of an existing memo group, then
> // MemoizeNormExpr is a no-op, and returns the existing group.
> ```

update comment to say it returns an `ExprView`
___
*[pkg/sql/opt/memo/memo_test.go, line 90 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2qudk1-B4mxhgIwal:-LM2qudk1-B4mxhgIwam:b-uokf26) ([raw file](https://github.com/cockroachdb/cockroach/blob/642be2634f0291e91930eb454a6a881406634fa0/pkg/sql/opt/memo/memo_test.go#L90)):*
> ```Go
> 	}
> 	if mem2Str != mem2.String() {
> 		t.Errorf("expected: %s, actual: %s", mem2.String(), mem2Str)
> ```

[nit] `mem2Str` should be the expected value
___
*[pkg/sql/opt/optgen/cmd/optgen/factory_gen.go, line 160 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2ytEzEP-7YFti0GJm:-LM2ytEzEP-7YFti0GJn:b-t2r2vn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded20cd554698492a76ada18b1dcc32b3c5875ed/pkg/sql/opt/optgen/cmd/optgen/factory_gen.go#L160)):*
> ```Go
> 		//   1. The operator is an aggregate.
> 		//   2. The operator has no children.
> 		if define.Tags.Contains("Aggregate") {
> ```

why can aggregates be skipped?

**Review by knz — APPROVED** [review]
:lgtm: on the idea and the changes to the `sql` package. This is indeed nicely done :)

> Reviewed 2 of 16 files at r13, 10 of 19 files at r20.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-:-LM33QOTDbH4N43Aj7Zi:b-yzncwl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale)

**Review by jordanlewis — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-:-LM3NaK35Ivv1CQ3sPNm:bg7igkv)* status: :shipit: complete! 3 of 0 LGTMs obtained (and 1 stale)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29686)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/plan.go, line 416 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2ukUe4tz2B9sAWKab:-LM3DI2qDlHiFzxyw2pc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded20cd554698492a76ada18b1dcc32b3c5875ed/pkg/sql/plan.go#L416)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Mention that we also always build if in the prepare phase.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/prepare, line 438 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2wR17BVSXOu2mSyis:-LM3Ltnl2MaOzs-JGArM:b-q1isfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded20cd554698492a76ada18b1dcc32b3c5875ed/pkg/sql/logictest/testdata/logic_test/prepare#L438)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is it worth adding a couple of tests here with placeholders?
</blockquote></details>

Placeholders shouldn't change anything, but doesn't hurt to make sure of that, so I added an extra case.
___
*[pkg/sql/opt/metadata_test.go, line 101 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2hPtN21LfDpmbl_r2:-LM3NA9X8JCn_d93Exap:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c862144fc979e7c12cb468bdc795b75484bff2e1/pkg/sql/opt/metadata_test.go#L101)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This comment seems stale -- `TabName` is set to "b" below
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1077 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2mlxs9-d1E_zCenT3:-LM3NJtV2MWRZRAA7hSZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/585ac2f1aed189f0a116662ff9d2e0d7d057a7f8/pkg/sql/opt/memo/logical_props_builder.go#L1077)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

and `HasPlaceholder`
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/memo.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LLogK1L7IaZigAWiI_s:-LM3Nw9t54A6jCHy81SW:bok1as5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b1938195b91b450f6e8649212abc42e83189936/pkg/sql/opt/memo/memo.go#L276)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

But what if the array is modified in place as Jordan suggested?
</blockquote></details>

`GetPathArray` already specifies that slice elements will never be modified in-place:
```
// GetPathArray returns the underlying path array of this SearchPath. The
// resultant slice is not to be modified.
func (s SearchPath) GetPathArray() []string {
```
Even if they were, comparing elements for equality would not detect that, since both the cached paths and the evalCtx paths would both have changed and so still compare equal. Detecting an in-place modification like that would require taking a deep copy of the slice, which would require an extra allocation. Given that the search paths slice is documented to never change in-place, I think this is unnecessary overhead in a place where every allocation counts.

I updated the comment with more info.
___
*[pkg/sql/opt/memo/memo.go, line 258 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2i9eq1mlpkjondqPO:-LM3NvC-7zJ6cn3m_J_O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c862144fc979e7c12cb468bdc795b75484bff2e1/pkg/sql/opt/memo/memo.go#L258)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] may no longer has -> may no longer have
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/memo.go, line 223 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2phbR7rjyn1oXhOgP:-LM3Np613G4wUxk3vlnw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/642be2634f0291e91930eb454a6a881406634fa0/pkg/sql/opt/memo/memo.go#L223)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

is it worth adding a check here to see if `m.groups` is nil, and if so, allocate space for `len(from.groups)` groups?
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/memo.go, line 419 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2qNxyBqKGgx8NfP1q:-LM3T1MF3a8HAiJw9zJk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/642be2634f0291e91930eb454a6a881406634fa0/pkg/sql/opt/memo/memo.go#L419)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

update comment to say it returns an `ExprView`
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/memo_test.go, line 90 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2qudk1-B4mxhgIwal:-LM3TEOG8FMGNOF09QJf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/642be2634f0291e91930eb454a6a881406634fa0/pkg/sql/opt/memo/memo_test.go#L90)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] `mem2Str` should be the expected value
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/factory_gen.go, line 160 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/29686#-LM2ytEzEP-7YFti0GJm:-LM3TG8i9TlsGFryQMXr:b-ncrq1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ded20cd554698492a76ada18b1dcc32b3c5875ed/pkg/sql/opt/optgen/cmd/optgen/factory_gen.go#L160)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why can aggregates be skipped?
</blockquote></details>

They never contain placeholders, since we always rewrite any non-`Variable` expression as an input projection. I added comment to clarify.

**Pull request merged**
