### PR TITLE
ci: add bazel lint job for ci

### LINKED ISSUE #67138: ci: add bazel lint job in CI
To consume from new "Bazel Github CI" build configuration.

Epic CRDB-8306

### PR DESCRIPTION
**Pull request by rickystewart**
Closes #67138.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_Lint/3267674

**Review by otan — APPROVED** [review]
noice

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68454#-:-MgfPoAh93Y1VDWtkx33:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
bors r=rail,otan

**Pull request merged**
