### PR TITLE
ui: update dates to 24h UTC

### LINKED ISSUE #78442: Update time picker to 24h instead of 12h
Update the time picker and all timestamps to 24 for consistency. The time picker update would apply across Metrics, Advanced Debug Custom Metrics, Statements, and Transactions pages.

- [x]  Update Time picker to 24h time and remove 'AM/PM' selector from time dropdown
Screen Shot 2022-03-24 at 2 06 34 PM

### Update Timestamps to 24h

**Databases pages**
- [x] Tables overview: `Table Stats Last Updated` column
- [x] Table detail page: 1) `Table Stats Last Updated` 2) `Last Reset` link 3) `Index Last Used` column
- [x] Index detail page: 1) `Last Reset` link, 2) `Index Last Used`

**SQL Activity pages**
- [x] Statement/transaction active execution overview and detail pages: `Start Time`
- [x] Sessions overview and detail page: 1) `Session Start Time` 2) `Statement Start Time`
- [x] Statement fingerprint detail: `Aggregation Interval` (is this being removed?)
- [x] Statement fingerprint detail / Diagnostics tab: `Activated on`
- [x] Advanced Debug > Statement Diagnostics History: `Activated on`

**Jobs pages** 
- [x] Jobs Detail page: `Creation Time`
- (Creation time on the jobs overview is already 24h)

**For KV observability team to update**
- [x] Hot ranges overview: `Last update` (#78517) 
- [x] Node details page: `Last update` 

Jira issue: CRDB-14133

### LINKED ISSUE #80103: Bug in label for diagnostic download menu
There's a typo in the download bundle pop-up. There's a stray `Z` before the bundle creation time. The label `Download <date> diagnostic` seems truncated.  Perhaps it should be `Download <date> bundle`.
Screen Shot 2022-04-15 at 1 10 39 PM

### PR DESCRIPTION
**Pull request by maryliag**
This commit updates all dates to use a 24h format in UTC

Fixes https://github.com/cockroachdb/cockroach/issues/78442
Fixes https://github.com/cockroachdb/cockroach/issues/80103

Release note (ui change): Update all dates to use 24h format in UTC

### CODE REVIEW

**Review by jocrl — APPROVED** [review]
Just checking if the AM/PM should also be removed here? https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.tsx#L131



 
Otherwise, :lgtm: !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81077#-:-N1sflXU0F778cda2YuB:b-yntsxh)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by maryliag — COMMENTED** [review]
Oh nice catch! Fixed!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81077#-:-N1ygk-kB9asr2l9RlK-:b-u5vpx6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by jocrl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81077)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by maryliag** [comment]
blathers backport release-22.1

**Pull request merged**
