### PR TITLE
distsql: add memory accounting and stats to windowers

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds memory accounting and stats collection to
windowers.

Related to: #24425.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
Great job, this stuff is confusing. I think you're missing the constant slice overhead in most `Grow` calls but this becomes insignificant.

> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-:-LJL--lr-h38Xnrvsbj6:b-ptv1d7)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/windower.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-LJKzfQn-9QWRm5FAA-l:-LJKzfQn-9QWRm5FAA-m:bejfqit) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a83e7f924fc49011c73a1c8ffee6daebda0fe/pkg/sql/distsqlrun/windower.go#L131)):*
> ```Go
> 	rowAlloc     sqlbase.EncDatumRowAlloc
> 
> 	memAcc        mon.BoundAccount
> ```

Memory accounts usually are associated with only one type of allocation. It's easier to have one `memAcc`, but given how confusing all the `Grow`s are, maybe consider what it would look like to have several memory accounts, one per allocation pattern? Would it make the `Grow`s more readable?
___
*[pkg/sql/distsqlrun/windower.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-LJKqvixAR3nLyuU-1Ci:-LJKqvixAR3nLyuU-1Cj:b-5jjuop) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a83e7f924fc49011c73a1c8ffee6daebda0fe/pkg/sql/distsqlrun/windower.go#L164)):*
> ```Go
> 	w.inputTypes = input.OutputTypes()
> 	// TODO: why not w.ctx?
> 	ctx := flowCtx.EvalCtx.Ctx()
> ```

Because `w.ctx` is nil until `startInternal` is called in `Start`.
___
*[pkg/sql/distsqlrun/windower.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-LJKrxuw801SnzIB0eHQ:-LJKrxuw801SnzIB0eHR:b-xxctx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a83e7f924fc49011c73a1c8ffee6daebda0fe/pkg/sql/distsqlrun/windower.go#L344)):*
> ```Go
> 				}
> 				// TODO: how can we learn the size of Datum before decoding it?
> 				if err := w.memAcc.Grow(w.ctx, int64(encRow[i].Datum.Size())); err != nil {
> ```

I don't think you can, especially since you have `Datum`s with variable sizes. In general we should grow before allocating, but this is fine.
___
*[pkg/sql/distsqlrun/windower.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-LJKu3nM5YMwON7dAW7I:-LJKu3nM5YMwON7dAW7J:bjj7x5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a83e7f924fc49011c73a1c8ffee6daebda0fe/pkg/sql/distsqlrun/windower.go#L400)):*
> ```Go
> func (w *windower) computeWindowFunctions(ctx context.Context, evalCtx *tree.EvalContext) error {
> 	var peerGrouper peerGroupChecker
> 	usage := int(unsafe.Sizeof([][]tree.Datum{}))*len(w.windowFns) + int(sizeOfIndexedRowsStruct)*len(w.encodedPartitions)
> ```

Do you think it would make sense to extract this `[][]tree.Datum{}` into a const like `sizeOfIndexedRowStruct` to make this more readable? I believe you're also missing the slice overhead but it doesn't matter much in the grand scheme of things.
___
*[pkg/sql/distsqlrun/windower.go, line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-LJKxlhn87dAvUTzScg1:-LJKxlhn87dAvUTzScg2:bdn9yag) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a83e7f924fc49011c73a1c8ffee6daebda0fe/pkg/sql/distsqlrun/windower.go#L427)):*
> ```Go
> 	// to the index of another window function f2 with the same ORDER BY
> 	// clause such that f2 will have been processed before f1.
> 	usage = int(unsafe.Sizeof(int(0))+unsafe.Sizeof([]indexedRows{})+unsafe.Sizeof(false)) * len(w.windowFns)
> ```

It's quite difficult to wrap one's head around this, I would at least add a comment (if not three variables where each one is described, same for other places in which you're calculating the usage for multiple objects on one line). I think you're missing the slice overhead here as well.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the comments!

I omit tracking some memory (like constant overhead of a slice and slice of bools or ints) intentionally for clarity - that memory should be tiny in comparison to other allocations.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-:-LJP4owCD8N1zWE2R0RX:bnv7rgf)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/windower.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-LJKzfQn-9QWRm5FAA-l:-LJP4Yyt3VE5ehQswxyT:b-jobz9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a83e7f924fc49011c73a1c8ffee6daebda0fe/pkg/sql/distsqlrun/windower.go#L131)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Memory accounts usually are associated with only one type of allocation. It's easier to have one `memAcc`, but given how confusing all the `Grow`s are, maybe consider what it would look like to have several memory accounts, one per allocation pattern? Would it make the `Grow`s more readable?
</blockquote></details>

Following your advice, I introduced several memory accounts that are distinguished by the "purpose" of memory they are tracking. Hopefully, it makes the code more comprehensible.
___
*[pkg/sql/distsqlrun/windower.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-LJKqvixAR3nLyuU-1Ci:-LJL6G668od4nAyKSdFa:b-kufkx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a83e7f924fc49011c73a1c8ffee6daebda0fe/pkg/sql/distsqlrun/windower.go#L164)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Because `w.ctx` is nil until `startInternal` is called in `Start`.
</blockquote></details>

I see, thanks.
___
*[pkg/sql/distsqlrun/windower.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-LJKrxuw801SnzIB0eHQ:-LJL6Mhy2J7-Rkbv-diJ:bm5oqht) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a83e7f924fc49011c73a1c8ffee6daebda0fe/pkg/sql/distsqlrun/windower.go#L344)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think you can, especially since you have `Datum`s with variable sizes. In general we should grow before allocating, but this is fine.
</blockquote></details>

I agree, thanks.
___
*[pkg/sql/distsqlrun/windower.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-LJKu3nM5YMwON7dAW7I:-LJP3F-J0xZu010RJ46l:b-g54coz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a83e7f924fc49011c73a1c8ffee6daebda0fe/pkg/sql/distsqlrun/windower.go#L400)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do you think it would make sense to extract this `[][]tree.Datum{}` into a const like `sizeOfIndexedRowStruct` to make this more readable? I believe you're also missing the slice overhead but it doesn't matter much in the grand scheme of things.
</blockquote></details>

I extracted the size into a constant, but I still think it's slightly confusing because all the constants are very similar yet different :/

By slice overhead do you mean three words that every slice needs? I do not include that, as well as some other allocations which I expect to be relatively small in comparison to rows-related allocations. Please let me know if I should do more precise accounting.
___
*[pkg/sql/distsqlrun/windower.go, line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-LJKxlhn87dAvUTzScg1:-LJP4IB50geS3OeNvwUq:bpmjt1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a83e7f924fc49011c73a1c8ffee6daebda0fe/pkg/sql/distsqlrun/windower.go#L427)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's quite difficult to wrap one's head around this, I would at least add a comment (if not three variables where each one is described, same for other places in which you're calculating the usage for multiple objects on one line). I think you're missing the slice overhead here as well.
</blockquote></details>

I decided to get rid off less important allocations to make memory accounting more clear.

**Review by asubiotto — APPROVED** [review]
I think it's clearer if you do track the constant overhead of a slice (since you'd do it all in a `Grow` call), but if you decide not to, please mention so above the memory account fields in the struct because some readers might find it surprising (same for not tracking the bool and int slice because of variable but likely low memory usage).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-:-LJPfElj4uOnDKsh3o2C:b-d7y6vm)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Agreed, so I added tracking of slices overheads and left a comment above accounts about choosing not to track certain allocations, as you suggested. I couldn't come with non-confusing names for the constants (not sure if there are such in this case).

If you could do a last quick pass through the code before I merge this, I'd appreciate it!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-:-LJVETB3040dpGDT18n-:b-moqhn2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28328#-:-LJVq4CiCa2DkLnAr1hy:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by yuzefovich** [comment]
Thanks for the review!

bors r+

**Pull request merged**
