### PR TITLE
storage: ignore non-live probing follower during log truncation

### PR DESCRIPTION
**Pull request by tbg**
Need to write tests and such, but I wanted to at least post this
before the weekend.

----

In the previous code, a follower in probing status which was not
recently active (i.e. a dead node) would permanently suppress
log truncations unless the Raft log was above threshold size (but the
size tracks only what the current leaseholder has written, i.e., it
can undercount dramatically). As a result, snapshots to other nodes
would get blocked if the log was in fact large (>16mb), leading to
ranges which effectively couldn't change their set of members.

Release note (bug fix): Prevent a problem that would cause the Raft log
to grow very large which in turn could prevent replication changes.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
This deserves a test. I'm surprised no existing tests break due to this. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34502#-:-LXeuGo-5FDqAkQ-HO6U:b-1yr7fo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/raft_log_queue.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34502#-LXetyRA4ATAGN8iTZmx:-LXetyRA4ATAGN8iTZmy:b-lffvd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3a0cf569607deeb2b2d67198c24d9a63fa1ac5/pkg/storage/raft_log_queue.go#L326)):*
> ```Go
> 		if !progress.RecentActive {
> 			// Make no exceptions for followers who haven't contacted
> 			// us within a reasonable period of time.
> ```

Can you elaborate on what it means to "make no exceptions"? Perhaps this should be something like: "If a follower hasn't contacted us within a reasonable period of time, do not include that follower's Raft log position in the decision for where to truncate".

**Review by tbg — COMMENTED** [review]
> This deserves a test. 

Absolutely. Wasn't my intention to merge without one. Just wanted to show the fix.



> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34502#-:-LXf41Uq2hkB2EK94fve:bmvupyh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by petermattis — COMMENTED** [review]
Oops, I completely missed that comment and went straight to the code. Apologies.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34502#-:-LXf4WnR4Cg7RkdpbsTY:bqnisgf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
Ready for a look. Turns out that a bug in the test prevented me from catching this in the first place.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34502)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/raft_log_queue.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34502#-LXetyRA4ATAGN8iTZmx:-LY21CIN27h90X7DUsYo:b-82oqa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3a0cf569607deeb2b2d67198c24d9a63fa1ac5/pkg/storage/raft_log_queue.go#L326)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you elaborate on what it means to "make no exceptions"? Perhaps this should be something like: "If a follower hasn't contacted us within a reasonable period of time, do not include that follower's Raft log position in the decision for where to truncate". 
</blockquote></details>

Ping.
___
*[pkg/storage/raft_log_queue_test.go, line 260 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34502#-LY21XgQ0gTEVeovnI_-:-LY21XgQ0gTEVeovnI_0:bcl2l0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31bb1326afa6a302165179aa178454800d033ad/pkg/storage/raft_log_queue_test.go#L260)):*
> ```Go
> 						Match:        0,
> 						Next:         v,
> 					}
> ```

These test cases are super hard to read. There is a minimum of code, yet I think we'd be better served by more code where each test case is easier to understand (i.e. `datadriven` tests). That said, this is fine for now. Just my griping.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34502)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/storage/raft_log_queue.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34502#-LXetyRA4ATAGN8iTZmx:-LY61dsc9d5lHUF353HF:b-hvfs5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3a0cf569607deeb2b2d67198c24d9a63fa1ac5/pkg/storage/raft_log_queue.go#L326)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ping.
</blockquote></details>

Thanks. Pong.
___
*[pkg/storage/raft_log_queue_test.go, line 260 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34502#-LY21XgQ0gTEVeovnI_-:-LY60lEb2ucKOufsZVDb:b-egb0j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31bb1326afa6a302165179aa178454800d033ad/pkg/storage/raft_log_queue_test.go#L260)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

These test cases are super hard to read. There is a minimum of code, yet I think we'd be better served by more code where each test case is easier to understand (i.e. `datadriven` tests). That said, this is fine for now. Just my griping.
</blockquote></details>

I actually looked at that before settling on this based on need to be cherry-picked and not wanting to hold up the fix. Other than that, I agree with you and I have a WIP locally in which I try to bike shed what the datadriven test would look like. I'll send that as a separate PR (maybe not for this particular test, but I do want to start translating some to establish good examples to lean on).

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34502)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/raft_log_queue_test.go, line 260 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34502#-LY21XgQ0gTEVeovnI_-:-LY7XmReAyExHbmV08vX:b-uui2wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31bb1326afa6a302165179aa178454800d033ad/pkg/storage/raft_log_queue_test.go#L260)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I actually looked at that before settling on this based on need to be cherry-picked and not wanting to hold up the fix. Other than that, I agree with you and I have a WIP locally in which I try to bike shed what the datadriven test would look like. I'll send that as a separate PR (maybe not for this particular test, but I do want to start translating some to establish good examples to lean on).
</blockquote></details>

Agreed that switching to datadriven tests will making backporting more difficult. We should avoid big cleanups like that when making changes we'll want to backport.

**Comment by tbg** [comment]
bors r=petermattis

**Pull request merged**
