### PR TITLE
storage: Collect IntentHistory for transactions

### PR DESCRIPTION
**Pull request by ridwanmsharif**
First part of making transactions more idempotent. This change
adds history of all writes on a key by the transaction. This
can be used to create save points and rollback to certain points
inside a transaction. More on why this is needed is explained here:
https://github.com/cockroachdb/cockroach/issues/5861#issuecomment-425990038

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I'll take a look at this shortly, but this could really use some testing. `mvcc_test.go` is where I would start, then I'd add some higher-level tests to `replica_test.go`.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/enginepb/mvcc.proto, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LS_ie7b6qu8nn0t37i-:-LS_ie7b6qu8nn0t37i0:b9hvjxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c623318bebd4239a7b3f2cd74778f81f7940027/pkg/storage/engine/enginepb/mvcc.proto#L78)):*
> ```protobuf
>   // returns the value at a given sequence.
>   // History will be empty for non-transactional requests.
>   optional IntentHistory history = 8 [(gogoproto.nullable) = false];
> ```

Adding non-nullable optional fields to below-raft protos is not generally safe. Repeated fields are fine, though, so I think you can just remove the IntentHistory wrapper.

**Review by nvb — CHANGES_REQUESTED** [review]
Haven't gotten to the tests yet, but this is looking good so far.

> Reviewed 9 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-:-LSuI7vL7xUWhJwPhh0I:buk0pri)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc.go, line 1116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuJ78S70ar8Y24kMWB:-LSuJ78TEqFWVsedHR4_:b-ay8bkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/mvcc.go#L1116)):*
> ```Go
> }
> 
> // getExistingValue returns the value of the data read at readTS from the buffer pool.
> ```

Let's inline this instead of pulling it out. We do so in `mvccResolveWriteIntent` and it doesn't seem to be a problem. 
___
*[pkg/storage/engine/mvcc.go, line 1272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuHfKC8Steh_by00qS:-LSuHfKC8Steh_by00qT:bqcmyzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/mvcc.go#L1272)):*
> ```Go
> 			cleanup()
> 
> 			// TODO(ridwanmsharif): Confirm this is correct.
> ```

Yep :thumbsup: 
___
*[pkg/storage/engine/mvcc.go, line 1277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuHca8DQ9cyzQWoB3z:-LSuHca8DQ9cyzQWoB4-:b8u4y5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/mvcc.go#L1277)):*
> ```Go
> 			// version.  For example, a conditional put within same
> 			// transaction should read previous write.
> 			if value, err = maybeGetValue(
> ```

Can we avoid reading the previous intent value twice?
___
*[pkg/storage/engine/enginepb/mvcc.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuGAsS081HRkuIF3W0:-LSuGAsS081HRkuIF3W1:bmytb0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.go#L134)):*
> ```Go
> 
> // AddToHistory adds the sequence and value to the intent history.
> func (meta *MVCCMetadata) AddToHistory(seq int32, val []byte, deleted bool) {
> ```

`s/AddToHistory/AddToIntentHistory/`
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuEIjH9t4dste4TSZ9:-LSuEIjH9t4dste4TSZA:bo0phnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.proto#L27)):*
> ```protobuf
> // tombstone - to be stored in an IntentHistory of a key during a transaction.
> // Making it possible for a transaction to be more idempotent
> message Entry {
> ```

This name should be more specific. What does `enginepb.Entry` mean? I'd make it a [nested message](https://developers.google.com/protocol-buffers/docs/proto#nested) within `MVCCMetadata` and give it a more specific name. Maybe `SequencedIntent`.
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuFyuZDn4m3OXHB73S:-LSuFyuZDn4m3OXHB73T:b7s0dyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.proto#L33)):*
> ```
>   // IntentHistory.GetValue(seq) returns the value
>   // in history if it exists.
> ```

This comment about a method on `MVCCMetadata` doesn't belong here.
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuEsJo5V61xMHdsRTs:-LSuEsJo5V61xMHdsRTt:b-6uk8bg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.proto#L39)):*
> ```protobuf
>   optional bytes value = 2;
>   // Is this value in the intent history a deletion tombstone?
>   optional bool deleted = 3 [(gogoproto.nullable) = false];
> ```

Does this need to be separate from `value == nil`?
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuFetE2g2e5nvJU77n:-LSuFetE2g2e5nvJU77o:boaen0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.proto#L69)):*
> ```protobuf
>   optional bytes raw_bytes = 6;
>   // IntentHistory of the transaction stores all they values the txn wrote
>   // for the key along with each values corresponding Sequence.
> ```

Not "all" versions, just all non-live versions, right?

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc.go, line 1116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuJ78S70ar8Y24kMWB:-LSv6BSz9C3lo_PwTWcP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/mvcc.go#L1116)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's inline this instead of pulling it out. We do so in `mvccResolveWriteIntent` and it doesn't seem to be a problem. 
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuHfKC8Steh_by00qS:-LSuzL2e-b3i86a7GdvW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/mvcc.go#L1272)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yep :thumbsup: 
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuHca8DQ9cyzQWoB3z:-LSv69lfA4QyhGQe6HZu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/mvcc.go#L1277)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we avoid reading the previous intent value twice?
</blockquote></details>

Done.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuGAsS081HRkuIF3W0:-LSuzMKXBmOuBhattm6N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.go#L134)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/AddToHistory/AddToIntentHistory/`
</blockquote></details>

Done.
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LS_ie7b6qu8nn0t37i-:-LSuzduFEat6_DPq8y0M:bgmz2y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c623318bebd4239a7b3f2cd74778f81f7940027/pkg/storage/engine/enginepb/mvcc.proto#L78)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Adding non-nullable optional fields to below-raft protos is not generally safe. Repeated fields are fine, though, so I think you can just remove the IntentHistory wrapper.
</blockquote></details>

Done. The empty checksum has not changed but the populated checksum for the below raft protos test did, which is what we want I think.
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuEIjH9t4dste4TSZ9:-LSuzN6G9-n_B5mrRTfn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.proto#L27)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This name should be more specific. What does `enginepb.Entry` mean? I'd make it a [nested message](https://developers.google.com/protocol-buffers/docs/proto#nested) within `MVCCMetadata` and give it a more specific name. Maybe `SequencedIntent`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuFyuZDn4m3OXHB73S:-LSuzNyf3v-B9l9nqy25:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.proto#L33)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
>   // IntentHistory.GetValue(seq) returns the value
>   // in history if it exists.
> ```

This comment about a method on `MVCCMetadata` doesn't belong here.
</blockquote></details>

Done.
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuEsJo5V61xMHdsRTs:-LSuzOax9tSctxPffq_z:bm28xcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.proto#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to be separate from `value == nil`?
</blockquote></details>

It doesn't, I'd misunderstood what the `Deleted` bool on the `MVCCMetadata` object was doing. Fixed.
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuFetE2g2e5nvJU77n:-LSuz_Su4ZhX86xWf7dQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.proto#L69)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Not "all" versions, just all non-live versions, right?
</blockquote></details>

Done.

**Review by nvb — CHANGES_REQUESTED** [review]
Almost there. The testing is solid.

> Reviewed 9 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-:-LSzSWpE1VYrr2tTsay_:b5rsn0x)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc.go, line 1221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzPj8sCjo8We6Xc7H0:-LSzPj8tB2Gqu1yWZfIy:b-gonyqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1221)):*
> ```Go
> 	var maybeTooOldErr error
> 	var prevValSize int64
> 	var prevValBytes []byte
> ```

These are referring to two different "prev vals", right? One is the previous intent value is one is the previous committed value. I'd rename `prevValBytes` to `prevIntentValBytes` and `prevSequence` to `prevIntentSequence`.

Also, move this into the `ok && meta.Txn != nil` block since we only need it there.
___
*[pkg/storage/engine/mvcc.go, line 1255 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzQ4YL3bC39AZC42vZ:-LSzQ4YL3bC39AZC42v_:b-o4dzn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1255)):*
> ```Go
> 				return err
> 			}
> 			if existingVal != nil {
> ```

Can this case exist? If not, should we throw an error?
___
*[pkg/storage/engine/mvcc.go, line 1259 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzPRXc95I1TRLqU4xJ:-LSzPRXc95I1TRLqU4xK:b-op2hte) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1259)):*
> ```Go
> 			}
> 			prevSequence := meta.Txn.Sequence
> 			// Make sure we process valueFn before clearing any earlier
> ```

minor nit: add a line break above this comment.
___
*[pkg/storage/engine/mvcc.go, line 1268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzPDITA2zHH9SDLLML:-LSzPDITA2zHH9SDLLMM:baphjf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1268)):*
> ```Go
> 				}
> 			}
> 			// Release the buffer after using the existing value.
> ```

We're leaking this in two different places. I'd defer it above.
___
*[pkg/storage/engine/mvcc.go, line 1305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzQFueCzrj-q1BVEGo:-LSzQFueCzrj-q1BVEGp:b-scoh94) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1305)):*
> ```Go
> 				timestamp = metaTimestamp
> 			}
> 			// Since a transaction exists for the MVCCMetadata, we must add the
> ```

Not just any transaction, our transaction. I'd rephase to "since an intent with a smaller sequence number for the same transaction exists, we must ..."
___
*[pkg/storage/engine/mvcc.go, line 1307 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzR4YQ60zjESJuJjz-:-LSzR4YQ60zjESJuJjz0:b-v7cstj) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1307)):*
> ```Go
> 			// Since a transaction exists for the MVCCMetadata, we must add the
> 			// previous value and sequence to the intent history.
> 			meta.AddToIntentHistory(prevSequence, prevValBytes)
> ```

I'm a little worried about modifying the `meta` directly. Can we avoid that?
___
*[pkg/storage/engine/mvcc_test.go, line 4384 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzRhB6AO6--vv6wdjY:-LSzRhB6AO6--vv6wdjZ:bdfzg2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc_test.go#L4384)):*
> ```Go
> 
> // TestMVCCIntentHistory verifies that trying to write to a key that already was written
> // to - results in the history being recorded in the MVCCMetadata.
> ```

Why the dash?
___
*[pkg/storage/engine/mvcc_test.go, line 4385 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzRrfx3hR8gnPazNhr:-LSzRrfx3hR8gnPazNhs:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc_test.go#L4385)):*
> ```Go
> // TestMVCCIntentHistory verifies that trying to write to a key that already was written
> // to - results in the history being recorded in the MVCCMetadata.
> func TestMVCCIntentHistory(t *testing.T) {
> ```

Nice test!
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuFetE2g2e5nvJU77n:-LSzSFDz8wEK6cghK9_v:bepobli) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.proto#L69)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add another sentence stating that it doesn't include the latest intent on the key, just those that have been overwritten.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc.go, line 1221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzPj8sCjo8We6Xc7H0:-LT-5KM_8kzIPQmlxw0t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1221)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

These are referring to two different "prev vals", right? One is the previous intent value is one is the previous committed value. I'd rename `prevValBytes` to `prevIntentValBytes` and `prevSequence` to `prevIntentSequence`.

Also, move this into the `ok && meta.Txn != nil` block since we only need it there.
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1255 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzQ4YL3bC39AZC42vZ:-LT-5M1X-mnoD5QtcjFt:bh5qwhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1255)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can this case exist? If not, should we throw an error?
</blockquote></details>

So currently this can happen when a transaction encounters an intent with a lower epoch. As a result it can't read the value using `mvccGetInternal`. I added a comment here but essentially, this shouldn't be a problem because in this case, the intent history is blown away anyway.
___
*[pkg/storage/engine/mvcc.go, line 1268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzPDITA2zHH9SDLLML:-LT-5voDAO6e6cgy9gPv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1268)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're leaking this in two different places. I'd defer it above.
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzQFueCzrj-q1BVEGo:-LT-6Fh-8-h6uDwxtIyH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1305)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Not just any transaction, our transaction. I'd rephase to "since an intent with a smaller sequence number for the same transaction exists, we must ..."
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1307 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzR4YQ60zjESJuJjz-:-LT-6HO1A1lFgFa2m76H:b6u9k47) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1307)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm a little worried about modifying the `meta` directly. Can we avoid that?
</blockquote></details>

Done. Updating `buf.newMeta` instead.
___
*[pkg/storage/engine/mvcc_test.go, line 4384 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzRhB6AO6--vv6wdjY:-LT-6WzC8dsCjNs3aMr9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc_test.go#L4384)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why the dash?
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc_test.go, line 4385 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzRrfx3hR8gnPazNhr:-LT-6Xsn9jk0GbpW7Pww:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc_test.go#L4385)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice test!
</blockquote></details>

Done.
___
*[pkg/storage/engine/enginepb/mvcc.proto, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSuFetE2g2e5nvJU77n:-LT-A54KDrEqnXmpSGLv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d67b7fc5918ab3c14d69ac817a9750fec10c3014/pkg/storage/engine/enginepb/mvcc.proto#L69)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add another sentence stating that it doesn't include the latest intent on the key, just those that have been overwritten.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm: once the final two comments are addressed. Nice work on this!

> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-:-LT17VAV4pQ2HwJuvsAv:b-bltwq0)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc.go, line 1255 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzQ4YL3bC39AZC42vZ:-LT17Hek72ToUZV_bnYx:b-e3k4yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1255)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

So currently this can happen when a transaction encounters an intent with a lower epoch. As a result it can't read the value using `mvccGetInternal`. I added a comment here but essentially, this shouldn't be a problem because in this case, the intent history is blown away anyway.
</blockquote></details>

Consider asserting that.
___
*[pkg/storage/engine/mvcc.go, line 1376 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LT16yxNDMudkUpwBSyU:-LT16yxNDMudkUpwBSyV:bvr77nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4832d60c6161e8d6e3fc7e8dc3b8447e7f95330/pkg/storage/engine/mvcc.go#L1376)):*
> ```Go
> 		}
> 		buf.newMeta.Txn = txnMeta
> 		buf.newMeta.Timestamp = hlc.LegacyTimestamp(timestamp)
> ```

Didn't we already do this above?

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/engine/enginepb/mvcc.proto, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LS_ie7b6qu8nn0t37i-:-LT3Keg_Aw8Zz6aBQL7w:b8pei5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c623318bebd4239a7b3f2cd74778f81f7940027/pkg/storage/engine/enginepb/mvcc.proto#L78)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

Done. The empty checksum has not changed but the populated checksum for the below raft protos test did, which is what we want I think.
</blockquote></details>

Yes, that's right.

**Review by ridwanmsharif — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-:-LT4JEhK8HpKZjkrDbwt:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/engine/mvcc.go, line 1255 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LSzQ4YL3bC39AZC42vZ:-LT4JC6Z9jy63jxd60qD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/378b2bc2aba18dae0339f68d7b6b3dc1332b8734/pkg/storage/engine/mvcc.go#L1255)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider asserting that.
</blockquote></details>

Done.
___
*[pkg/storage/engine/mvcc.go, line 1376 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LT16yxNDMudkUpwBSyU:-LT4J7ZTBQbwMl3yQOMP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4832d60c6161e8d6e3fc7e8dc3b8447e7f95330/pkg/storage/engine/mvcc.go#L1376)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Didn't we already do this above?
</blockquote></details>

Done.

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/engine/mvcc.go, line 1321 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LT4M0SP0qWF6Dv5b107:-LT4M0SP0qWF6Dv5b108:b-p6e2dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b61df2a8372a274649f7dcb57c633b691dee1fe/pkg/storage/engine/mvcc.go#L1321)):*
> ```Go
> 			// If the epoch of the transaction doesn't match the epoch of the
> 			// intent, blow away the intent history.
> 			if txn.Epoch <= meta.Txn.Epoch {
> ```

Do we have any tests for `txn.Epoch < meta.Txn.Epoch`? Don't we already return an error in that case?
___
*[pkg/storage/engine/mvcc.go, line 1322 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LT4LspN7mQA1bJDEP57:-LT4LspN7mQA1bJDEP58:b-j2fvsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b61df2a8372a274649f7dcb57c633b691dee1fe/pkg/storage/engine/mvcc.go#L1322)):*
> ```Go
> 			// intent, blow away the intent history.
> 			if txn.Epoch <= meta.Txn.Epoch {
> 				// I don't know where this case could pop up, but it is worth
> ```

nit: Comments are generally not in the first person.
___
*[pkg/storage/engine/mvcc.go, line 1326 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LT4Lvgx6mjQtnsttrZM:-LT4Lvgx6mjQtnsttrZN:b-ya5vq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b61df2a8372a274649f7dcb57c633b691dee1fe/pkg/storage/engine/mvcc.go#L1326)):*
> ```Go
> 				// to the history
> 				if existingVal == nil {
> 					return errors.Errorf("previous intent could not be read")
> ```

Leave a bit more context here. For instance, take a look at some of the warnings in `mvccResolveWriteIntent`.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/engine/mvcc.go, line 1321 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LT4M0SP0qWF6Dv5b107:-LT4TxLK4klT3rA5X0rr:b-n9kswy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b61df2a8372a274649f7dcb57c633b691dee1fe/pkg/storage/engine/mvcc.go#L1321)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we have any tests for `txn.Epoch < meta.Txn.Epoch`? Don't we already return an error in that case?
</blockquote></details>

Done. Should've been `==`
___
*[pkg/storage/engine/mvcc.go, line 1326 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-LT4Lvgx6mjQtnsttrZM:-LT4U1qu-YpA2q1vRSwb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b61df2a8372a274649f7dcb57c633b691dee1fe/pkg/storage/engine/mvcc.go#L1326)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Leave a bit more context here. For instance, take a look at some of the warnings in `mvccResolveWriteIntent`.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32688#-:-LT4WHGo5EijVs2nPshB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
