### PR TITLE
sql: do not silently ignore CTEs inside parentheses

### PR DESCRIPTION
**Pull request by knz**
Parent commit from #31003.

Informs #24303.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:, but cc @justinj who was just working on this in the optimizer

> Reviewed 7 of 7 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31004#-:-LO4hj2oCjzY0Ik985JZ:b8kqvt7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/with.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31004#-LO4gdpmACIHfAiHPNCh:-LO4gdpmACIHfAiHPNCi:b-5ovdfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/76f4748158f5f1f518344b2093c497fbbb676190/pkg/sql/with.go#L108)):*
> ```Go
> //
> // The argument needUse indicates the CTE must be used because it
> // contains a mutation.
> ```

I don't see this argument

**Review by justinj — COMMENTED** [review]
:lgtm: thanks for fixing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31004#-:-LO4wHum5sLya80fgo2d:b-1nny3v)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by knz — COMMENTED** [review]
TFYR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31004#-:-LOCUfQC2q-K1V943A0u:b-814cj3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/with.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31004#-LO4gdpmACIHfAiHPNCh:-LOCUcUF9NbmMjZ356Gs:bqal5m4) ([raw file](https://github.com/cockroachdb/cockroach/blob/76f4748158f5f1f518344b2093c497fbbb676190/pkg/sql/with.go#L108)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't see this argument
</blockquote></details>

Indeed, removed.

**Pull request merged**
