### PR TITLE
roachtest: increase the concurrency for gracefuldraining

### PR DESCRIPTION
**Pull request by andrewbaptist**
This set of commits changes gracefuldraining to use the `measureQPS` method instead of looking at the stats from the stats database and additionally increases the concurrency so it no longer fails.

### CODE REVIEW

**Comment by andrewbaptist** [comment]
Passes 50 roachtest runs with this change.

**Review by kvoli — COMMENTED** [review]
Nice! Left some minor comments/questions.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-:-Namrp852kbzutJz1ATd:be2531)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, and @renatolabs)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-Namr2m73kmHy2u13Es7):*
nit: Could you be more specific, "statistics during the test" could mean a lot of things. Perhaps, "based on the metric timeseries web API"?
___
*[`-- commits` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-NamqxluDsknmOPxkWON):*
rm this line
___
*[`-- commits` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-NamrgJT9VpoX0w6jVln):*
nit: could you mention that this is for the workload concurrency.
___
*[`pkg/cmd/roachtest/tests/kv.go` line 540 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-NamptGJ-sCYNyzLnhv8:-NamptGJ-sCYNyzLnhv9:b-d6y4ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/d315c5d4bd1944b54d209e8868a00958c89c32ac/pkg/cmd/roachtest/tests/kv.go#L540)):*
> ```Go
> 			// definitely a large number of leases on the node that we shut down
> 			// before it starts draining.
> 			c.Run(ctx, c.Node(1), "./cockroach workload init kv --splits 100")
> ```

Was `--max-ops` only supported on the deprecated workload runner?
___
*[`pkg/cmd/roachtest/tests/kv.go` line 561 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-Namqb-A9qVoPxNTSLf3:-Namqb-A9qVoPxNTSLf4:b49ptpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d315c5d4bd1944b54d209e8868a00958c89c32ac/pkg/cmd/roachtest/tests/kv.go#L561)):*
> ```Go
> 			m.Go(func(ctx context.Context) error {
> 				cmd := fmt.Sprintf(
> 					"./cockroach workload run kv --duration=%s --read-percent=0 --max-rate=%d {pgurl:1-%d}",
> ```

How come you removed the `--tolerate-errors` flag here; It seems like we may want this, to protect against noise here, wdyt?

**Review by andrewbaptist — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107955)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @kvoli, and @renatolabs)

___
*[`-- commits` line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-Namr2m73kmHy2u13Es7):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: Could you be more specific, "statistics during the test" could mean a lot of things. Perhaps, "based on the metric timeseries web API"?
</blockquote></details>

Done
___
*[`-- commits` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-NamqxluDsknmOPxkWON):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

rm this line
</blockquote></details>

Done 
___
*[`-- commits` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-NamrgJT9VpoX0w6jVln):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: could you mention that this is for the workload concurrency.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/tests/kv.go` line 540 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-NamptGJ-sCYNyzLnhv8:-Namvn_g3PxrMRfprKgk:b-vre39t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d315c5d4bd1944b54d209e8868a00958c89c32ac/pkg/cmd/roachtest/tests/kv.go#L540)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Was `--max-ops` only supported on the deprecated workload runner?
</blockquote></details>

This wasn't really necessary as it was trying to run `workload init` but doing it in a weird way. I'm not sure why it did it this way as it really only wanted to cause the splits to happen, so I think it was just a workaround. This was an old test, so probably predated many of the newer patterns.
___
*[`pkg/cmd/roachtest/tests/kv.go` line 561 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-Namqb-A9qVoPxNTSLf3:-Namw1JN9qJiW5OCDIta:b-osutpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d315c5d4bd1944b54d209e8868a00958c89c32ac/pkg/cmd/roachtest/tests/kv.go#L561)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

How come you removed the `--tolerate-errors` flag here; It seems like we may want this, to protect against noise here, wdyt?
</blockquote></details>

I was on the fence with this one. I didn't really want there to be any errors, and in my stress testing I didn't have any. Ideally with a drain we shouldn't have errors in addition to not having t throughput drop, so while there is a risk this makes it more flakey, it would be much better if this flag wasn't needed as it would catch any issues we introduce that cause normal drain/restart to fail.

**Review by kvoli — APPROVED** [review]
I don't see the latest commits, did you push?  With those nits addressed :lgtm:!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-:-Nan2N-U0oCqBlmSgMOn:bbj8v7v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/kv.go` line 540 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-NamptGJ-sCYNyzLnhv8:-Nan20XH0UFRZuogsEvH:b-utacki) ([raw file](https://github.com/cockroachdb/cockroach/blob/d315c5d4bd1944b54d209e8868a00958c89c32ac/pkg/cmd/roachtest/tests/kv.go#L540)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

This wasn't really necessary as it was trying to run `workload init` but doing it in a weird way. I'm not sure why it did it this way as it really only wanted to cause the splits to happen, so I think it was just a workaround. This was an old test, so probably predated many of the newer patterns.
</blockquote></details>

Yeah, I can't see that option when running `./cockroach workload init kv --help`, seems fine.
___
*[`pkg/cmd/roachtest/tests/kv.go` line 561 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107955#-Namqb-A9qVoPxNTSLf3:-Nan297TAeiIUN58l6Sh:b-3jt2i0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d315c5d4bd1944b54d209e8868a00958c89c32ac/pkg/cmd/roachtest/tests/kv.go#L561)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I was on the fence with this one. I didn't really want there to be any errors, and in my stress testing I didn't have any. Ideally with a drain we shouldn't have errors in addition to not having t throughput drop, so while there is a risk this makes it more flakey, it would be much better if this flag wasn't needed as it would catch any issues we introduce that cause normal drain/restart to fail.
</blockquote></details>

If it passed 50 stresses, then sounds good to me.  I suppose we can re-assess when/if this causes a failure.

**Comment by andrewbaptist** [comment]
bors r=kvoli

**Pull request merged**
