### PR TITLE
sql: remove vectorize=201auto option

### PR DESCRIPTION
**Pull request by yuzefovich**
`201auto` option of `vectorize` setting has been removed since it no
longer makes sense to keep (it was introduced as an escape hatch for
20.2 release). Note that we don't need to bump the distsql version
because of this change since it is backwards compatible - if the gateway
is running the old version that has `vectorize=201auto` set, then we
will check whether flows for all nodes don't have non-streaming
operators and possibly use `off` option on the flow setup request, then
the newer version remote node will check the vectorize setting on the
request whether it is not `off` and setup the vectorized flow if it is
not.

Release note (sql change): `201auto` value for `vectorize` session
variable and the corresponding cluster setting has been removed.

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
What about when the gateway is using the new version, and the other node is running the old version? Will that node run a streaming-only vectorized flow?

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55907#-:-MKZTL8_ES98qG-rCWnN:b-krrjbw)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
Note that the decision whether to vectorize the whole flow or not is made on the gateway, and then each node participating in the plan checks simply whether `Vectorize` setting from evalCtx proto is `off` or not to decide which flow to set up on itself.

In your example, say the newer node will set `Vectorize=on`, and the remote nodes running older version will also see `on` option, so they won't pay attention to the fact whether the operators are streaming or not.

**Review by asubiotto — CHANGES_REQUESTED** [review]
:lgtm: 

> In your example, say the newer node will set Vectorize=on, and the remote nodes running older version will also see on option, so they won't pay attention to the fact whether the operators are streaming or not.

Ahh gotcha, I was missing that you reserved the `Vectorize201Auto` field in the evalctx proto

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55907#-:-MKdeMc71Qusn0Y1a8j6:bpddhy3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colflow/BUILD.bazel, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55907#-MKdeQk74eJwA6qwRBKK:-MKdeQk74eJwA6qwRBKL:b2jejzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1709ecc9b1d47b303866bcf6bdc70f147c5e837/pkg/sql/colflow/BUILD.bazel#L26)):*
> ```Starlark
>         "//pkg/sql/pgwire/pgerror",
>         "//pkg/sql/rowexec",
>         "//pkg/sql/sessiondatapb",
> ```

Is this removal correct?

**Review by asubiotto — APPROVED** [review]
Hit the block by mistake

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55907#-:-MKdeV1uCWbQbJlXmhH3:b-rbm2l3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55907#-:-MKey5mc6Cl6sNSb3Mev:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colflow/BUILD.bazel, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55907#-MKdeQk74eJwA6qwRBKK:-MKey7N-CYdeCLt-minV:b-fvgkp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1709ecc9b1d47b303866bcf6bdc70f147c5e837/pkg/sql/colflow/BUILD.bazel#L26)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is this removal correct?
</blockquote></details>

Yeah - we no longer use `sessiondatapb` package in `vectorized_flow` file, so this package no longer needs to be imported when building `colflow` package.

**Pull request merged**
