### PR TITLE
liveness: introduce package for node liveness

### PR DESCRIPTION
**Pull request by irfansharif**
NodeLiveness is a relatively isolated component and makes for a good
"should be a standalone package" candidate. We tease it out here, mostly
through mechanical code movements, in the hope that it'll force us to
clarify API boundaries going forward. Some intended changes to these
APIs, like introducing a way to read liveness records directly from KV,
will be added to this new package in other PRs. (These APIs were
originally proposed in #56107, and will be pulled out into stand alone
PRs after this one.)

While here, we also move out the liveness proto definition into this new
package. The "changes" made in this PR are the following:
```
  pkg/kv/kvserver/{node liveness files}               => pkg/kv/kvserver/liveness
  pkg/kv/kvserver/liveness/{node liveness protos}     => pkg/kv/kvserver/liveness/livenesspb
  pkg/kv/kvserver/liveness/node_liveness_test.go      => pkg/kv/kvserver/liveness/client_test.go
  pkg/kv/kvserver/liveness/node_liveness_unit_test.go => pkg/kv/kvserver/liveness/liveness_test.go
```
Separately, we've had to initialize server factory in TestMain as the
package internal tests depend on it. This was previously done within
pkg/kv/kvserver/main_test.go.

We've also renamed a few exported symbols to avoid stuttering. This was
needed to make our linters happy.

---

I've left the existing node liveness tests that make use of
multiTestContext in the kvserver package, seeing as how we're slowly
upgrading them to use TestCluster instead (#8299). The expectation is
that as we migrate each test, they'll move into this new package.

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
I'm not actually sure if the proto file movement is safe. I think it is, because looks like we did the same thing earlier when moving from pkg/storage to pkg/kv/..., but not sure if I've missed something.

**Comment by tbg** [comment]
I don't think we should move the node liveness code out of the `./pkg/kv` package tree at this point. I think your reasoning is that the service liveness provides is used by the "whole cluster", but with the introduction of multi-tenancy, this is no longer true - liveness is really a statement about the liveness of a KV server. Besides, the implementation and API is heavily KV-centric including plenty of internals (special txn triggers, gossip), and we also de facto own it and will continue to do so. Let's anchor things at `./pkg/kv/kvserver/liveness` for now.

Proto file movement is always safe. What's not generally safe is changing the package of proto files. This is unsafe in two cases:

1. services were defined: that changes the name of the service, creating a migration concern
2. any of the defs in the affected files are used with `protobuf.Any`, in which case again the package name is in general needed to work with the field.

Neither are an issue here, so I think it is safe to adjust the package name (on top of the location).

**Review by tbg — APPROVED** [review]
:lgtm: mod my previous comment and thanks :bow: for making this happen!

> Reviewed 72 of 72 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56221#-:-MLCP3xf27vNnloMO1PU:b-le657q)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Review by irfansharif — COMMENTED** [review]
TFTR!

> Let's anchor things at ./pkg/kv/kvserver/liveness for now.

Done. I had it there originally, moving it out only to make the proto import paths a bit pithier, but not a good reason. Will bors on green. +cc @lunevalex, for the multiTestContext related details here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56221#-:-MLDNO1REF2kSvy9AiKJ:b-iwl6q3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @tbg)

**Pull request merged**
