### PR TITLE
sql: implement JSON{,B}_{OBJECT,}_AGG

### LINKED ISSUE #19978: sql: implement JSON{,B}_{OBJECT,}_AGG
I think this would be an ambitious, but doable first issue.

There's a handful of things that need to happen for this:

* We need a public interface from pkg/util/json to incrementally construct a
  JSON object/array. In the case of objects, since their keys need to be
  sorted, we would want to do something like push the new keys into a priority
  queue (the Go stdlib has a heap implementation). This should be tested
  independently from SQL-land. I think this will probably be useful outside of
  these aggregates so it should be a somewhat general interface.
* Add the aggregates in aggregate_builtins.go that use these new constructors.
  These will need be careful to monitor their memory usage, see the
  implementation of ARRAY_AGG for reference.
* Test the aggregates in SQL-land. Care should be taken to compare the
  semantics of what is implemented with what Postgres does (handling of NULL,
  duplicate keys, etc.).

This needs to happen for the next major release so I'll get to it if nobody is
interested in picking it up.

### PR DESCRIPTION
**Pull request by C0rWin**
Fixes #19978

This PR adds built in aggregate function allowing to augment query result set into json object.

Adds implementation of json{,b}_object_agg built in function, by adding a new construction which augments constructions and allows to keep track on memory usage. Finally, links json{,b}_object_agg built in function to enable support of queries which aggregates name/value pairs into JSON object.

Release note (sql change): enable aggregate queries which collect key/value pairs into JSON object.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Nice work so far @c0rwin, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-:-M6llVcGAYf3oe1zl7Cb:bu7o4ax)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @C0rWin and @jordanlewis)

___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 2466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M6lkRIm1RP8QK51rGhY:-M6lkRIm1RP8QK51rGhZ:b-w1vwok) ([raw file](https://github.com/cockroachdb/cockroach/blob/253e02b06ab5c0ba81f4fdfd82b180862bb41c34/pkg/sql/logictest/testdata/logic_test/aggregate#L2466)):*
> ```
> ----
> {"Alice": {"Facebook": "Alice_fb", "Instagram": "AliceInst", "Twitter": "@Alice"}}
> {"Bob": {"Facebook": "Bob_fb", "LinkedIn": "Bob The Builder"}}
> ```

Can you add some tests with the error cases you wrote in here? Checks for nulls, as an example. Also, please include some examples with JSON nulls, JSON arrays, and JSON numbers.
___
*[pkg/util/json/json.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M6lkgKD6HnJNuCQhvTj:-M6lkgKD6HnJNuCQhvTk:b-8sk4nx) ([raw file](https://github.com/cockroachdb/cockroach/blob/253e02b06ab5c0ba81f4fdfd82b180862bb41c34/pkg/util/json/json.go#L246)):*
> ```Go
> }
> 
> // ObjectBuilderWithCounter builds JSON object which keeps track of total size
> ```

nit: this should be a complete sentence with a period at the end. How about:

ObjectBuilderWithCounter builds a JSON object a key/value pair at a time, keeping of the memory usage of the object.
___
*[pkg/util/json/json.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M6lkvdl-m2WuNBbY5mC:-M6lkvdl-m2WuNBbY5mD:bx22tqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/253e02b06ab5c0ba81f4fdfd82b180862bb41c34/pkg/util/json/json.go#L252)):*
> ```Go
> }
> 
> // NewObjectBuilderWithCounter creates and instantiate ObjectBuilder with memory counter
> ```

nit: add a period
___
*[pkg/util/json/json.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M6lkdma1p46bG9ozZ3T:-M6lkdma1p46bG9ozZ3U:b-a88hbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/253e02b06ab5c0ba81f4fdfd82b180862bb41c34/pkg/util/json/json.go#L266)):*
> ```Go
> func (b *ObjectBuilderWithCounter) Add(k string, v JSON) {
> 	b.ob.Add(k, v)
> 	// Size of added JSON + size of the map kay pair and length of the key
> ```

nit: "kay" should be key.
___
*[pkg/util/json/json_test.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M6lkzB2E1RE3B3B2Dfh:-M6lkzB2E1RE3B3B2Dfi:b-fczksz) ([raw file](https://github.com/cockroachdb/cockroach/blob/253e02b06ab5c0ba81f4fdfd82b180862bb41c34/pkg/util/json/json_test.go#L467)):*
> ```Go
> 		{
> 			input:    [][]interface{}{{"key1", []interface{}{1, 2, 3, 4}}},
> 			expected: json(`{"key1": [1, 2, 3, 4]}`),
> ```

Please add some test cases with nulls.

**Comment by C0rWin** [comment]
> Can you add some tests with the error cases you wrote in here? Checks for nulls, as an example. Also, please include some examples with JSON nulls, JSON arrays, and JSON numbers.

Certainly will do, thanks.

**Comment by C0rWin** [comment]
@jordanlewis thanks for review, will address your comments and update my PR.

**Review by jordanlewis — COMMENTED** [review]
Couple more comments, but this is nearly there, thank you Artem!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-:-M7ele5e0ghJ3wy_ehkF:b-o3h9sr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @C0rWin and @jordanlewis)

___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 2470 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M7ekIP05G-moBahPkN0:-M7ekIP05G-moBahPkN1:b-18ayn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/93610368081ecce9ff763981324371c970efa768/pkg/sql/logictest/testdata/logic_test/aggregate#L2470)):*
> ```
> #empty result returned, since both key and value is nil, hence skipped
> statement ok
> select json_object_agg(null, null);
> ```

I think even this should return an error actually... any time the first arg is null you should return the error below.
___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 2528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M7el46X3PcwTgcm-hfw:-M7el46X3PcwTgcm-hfx:b-vi6hg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/93610368081ecce9ff763981324371c970efa768/pkg/sql/logictest/testdata/logic_test/aggregate#L2528)):*
> ```
> {"Alice": {"Facebook": "Developer", "Google": "Full Stack", "IBM": "Research"}}
> {"Bob": {"Cockroach Labs": "DB Developer", "Google": "DevOps", "Twitter": "Frontend"}}
> {"Charlie": null}
> ```

Are there any tests for what happens when there's a duplicate object key? Please add tests for that, thanks!
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 2685 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M7elTRfC_HChNPyaOZC:-M7elTRfC_HChNPyaOZD:bkdtn3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/93610368081ecce9ff763981324371c970efa768/pkg/sql/sem/builtins/aggregate_builtins.go#L2685)):*
> ```Go
> 
> 	// if only key datum equal to null, return error
> 	if datum == tree.DNull {
> ```

Bring this up above the first check, it should error if we ever have a null in the first position.

**Comment by C0rWin** [comment]
@jordanlewis thanks I will take care to address your comments

**Comment by C0rWin** [comment]
> Are there any tests for what happens when there's a duplicate object key? Please add tests for that, thanks!

I have some reservation with respect to duplicate keys, as I do not think this is defined or strictly articulated. While I understand that this has to be aligned with Postgres, it still not very well defined, I will add test to reflect current way to treat it. I actually was concerned about it, see here #48841.  /cc @jordanlewis

**Comment by C0rWin** [comment]
@jordanlewis the way CRDB currently treats JSON object formation, i.e. order of keys and order among duplicate keys depends on insertion order, hence not really deteministic for aggregate functions. (see: pkg/util/json/json.go:355)

```
func (s *pairSorter) unique() {
	// If there are any duplicate keys, then in sorted order it will have
	// two pairs with rank i and i + 1 whose keys are same.
	// For sorting based on comparisons, if two unique elements (pair.k, order)
	// have rank i and i + 1, they have to compare once to figure out their
	// relative order in the final position i and i + 1. So if there are any
	// equal elements, then the sort must have compared them at some point.
	if !s.hasNonUnique {
		return
	}
	top := 0
	for i := 1; i < len(s.pairs); i++ {
		if s.pairs[top].k != s.pairs[i].k {
			top++
			if top != i {
				s.pairs[top] = s.pairs[i]
			}
		}
	}
	s.pairs = s.pairs[:top+1]
}
```

I think that JSON object creation has to be fixed in a way that will not depend on how keys/values are inserted, unless I'm missing something.

**Review by yuzefovich — COMMENTED** [review]
Thanks for working on this! I left a bunch of nits, but in general the code is almost ready to go.

> I have some reservation with respect to duplicate keys, as I do not think this is defined or strictly articulated. While I understand that this has to be aligned with Postgres, it still not very well defined ...

Here is an excerpt from Postgres [docs](https://www.postgresql.org/docs/9.5/functions-aggregate.html):
```
The aggregate functions array_agg, json_agg, jsonb_agg, json_object_agg, jsonb_object_agg,
string_agg, and xmlagg, as well as similar user-defined aggregate functions, produce meaningfully
different result values depending on the order of the input values. This ordering is unspecified by
default, but can be controlled by writing an ORDER BY clause within the aggregate call.
```
So when there is no `ORDER BY` clause in the aggregate function, we are free to choose any order. If we deviate from Postgres in such case, it's ok, meaning that we should not be concerned about this:
> the way CRDB currently treats JSON object formation, i.e. order of keys and order among duplicate keys depends on insertion order, hence not really deteministic for aggregate functions.

In fact, in the logic tests you added we already deviate from Postgres, but it's acceptable.

On a related note, we should also add `json_object_agg` and `jsonb_object_agg` to `isOrderingSensetive` in `optbuilder/groupby.go`. This will allow us to support these new aggregates with `ORDER BY` clause (using window functions machinery behind the scenes), and we should add the tests for that.

> Reviewed 1 of 11 files at r1, 2 of 7 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-:-M8m7INM98rSxjh1p2XU:b-3jpcao)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @C0rWin)

___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 2638 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M8m0EMM17vI4nVPRf76:-M8m0EMNCJaygkJ95VWU:b9982u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/sql/logictest/testdata/logic_test/aggregate#L2638)):*
> ```
> 
> statement error pq: field name must not be null
> select json_object_agg(null, null);
> ```

super nit: unnecessary semicolon.
___
*[pkg/sql/opt/operator.go, line 306 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M8m10wn76aYKjDV3qS4:-M8m10wn76aYKjDV3qS5:btpzp6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/sql/opt/operator.go#L306)):*
> ```Go
> 		ConstNotNullAggOp, CorrOp, FirstAggOp, JsonAggOp, JsonbAggOp,
> 		MaxOp, MinOp, SqrDiffOp, StdDevOp, StringAggOp, SumOp, SumIntOp,
> 		VarianceOp, XorAggOp, PercentileDiscOp, PercentileContOp, JsonObjectAggOp, JsonbObjectAggOp:
> ```

super nit: seems like it might be time to start a new line here and below.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 3051 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M8m1XyF6-gABzSIDSY3:-M8m1XyF6-gABzSIDSY4:bh6z6rf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/sql/sem/builtins/aggregate_builtins.go#L3051)):*
> ```Go
> }
> 
> // Add accumulates the transformed json into the JSON array.
> ```

nit: probably `s/JSON array/JSON object/`.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 3059 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M8m1e_CDqtFigYZfQw-:-M8m1e_CDqtFigYZfQw0:b-xltjgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/sql/sem/builtins/aggregate_builtins.go#L3059)):*
> ```Go
> 	}
> 
> 	// if only key datum equal to null, return error
> ```

nit: if we have a comment that lives on a separate line, we usually start it with a capital letter and end it with a period.
___
*[pkg/util/json/json.go, line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M8m2zMl5l3X_IioP7YN:-M8m2zMl5l3X_IioP7YO:b-3jvwqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/util/json/json.go#L246)):*
> ```Go
> }
> 
> // ObjectBuilderWithCounter builds a JSON object a key/value pair at a time, keeping of the memory usage of the object.
> ```

nit: `s/keeping of the/keeping the/` and we strive for lines no longer than 80 characters.
___
*[pkg/util/json/json.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M8m35yb7kt2umkBbKQ3:-M8m35yb7kt2umkBbKQ4:b-xq97lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/util/json/json.go#L252)):*
> ```Go
> }
> 
> // NewObjectBuilderWithCounter creates and instantiate ObjectBuilder with memory counter.
> ```

nit: `s/instantiate/instantiates/`.
___
*[pkg/util/json/json.go, line 263 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M8m3Jcy2nnZTtFyKx0H:-M8m3Jcy2nnZTtFyKx0I:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/util/json/json.go#L263)):*
> ```Go
> 
> // Add appends key value pair to the sequence and updates
> // amount of memory allocated for the overall keys and values
> ```

nit: missing period.
___
*[pkg/util/json/json.go, line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M8m3xNNA4fleEj4oKjS:-M8m3xNNA4fleEj4oKjT:b-dzfbt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/util/json/json.go#L266)):*
> ```Go
> func (b *ObjectBuilderWithCounter) Add(k string, v JSON) {
> 	b.ob.Add(k, v)
> 	// Size of added JSON + size of the map key pair and length of the key
> ```

nit: something is off with "map key pair and length of the key", maybe "Size of added JSON + overhead of storing key/value pair + the size of the key"? (Also, a missing period.)
___
*[pkg/util/json/json.go, line 276 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M8m4VQ68gajMMAy-Byb:-M8m4VQ68gajMMAy-Byc:b-tnk93l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/util/json/json.go#L276)):*
> ```Go
> }
> 
> // Size returns the size in bytes of the JSON Array the builder is going to build.
> ```

nit: probably `s/Array/object/`.

**Comment by C0rWin** [comment]
@yuzefovich thanks for your feedback, will address your comments and provide updates.

**Review by yuzefovich — COMMENTED** [review]
The code looks good to me, but seems like you accidentally deleted a bunch of logic test cases, we should keep those :)

> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-:-M9fblx75VOLA-BILtL3:bqgd36q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @C0rWin)

___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 2570 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M9faS-yAFWQAUhBIxNM:-M9faS-yAFWQAUhBIxNN:b-2grmrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/sql/logictest/testdata/logic_test/aggregate#L2570)):*
> ```
> 
> query TT
> SELECT min(NULL::STRING COLLATE en_us), max(NULL::STRING COLLATE en_us)
> ```

Seems like you accidentally deleted a bunch of test cases here.

**Comment by C0rWin** [comment]
> The code looks good to me, but seems like you accidentally deleted a bunch of logic test cases, we should keep those :)
> 
> > Reviewed 8 of 8 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-:-M9fblx75VOLA-BILtL3:bqgd36q)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @C0rWin)
> 
> _[pkg/sql/logictest/testdata/logic_test/aggregate, line 2570 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M9faS-yAFWQAUhBIxNM:-M9faS-yAFWQAUhBIxNN:b-2grmrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/sql/logictest/testdata/logic_test/aggregate#L2570)):_
> 
> > ```
> > 
> > query TT
> > SELECT min(NULL::STRING COLLATE en_us), max(NULL::STRING COLLATE en_us)
> > ```
> 
> Seems like you accidentally deleted a bunch of test cases here.

Ups, this seems due to usage of ```TESTFLAGS='-rewrite=true'````, while I'm not really sure what am I doing wrong, but if I am trying to run specific subset of logic tests with this flag enabled it overwrites relevant part, but also wipes ones which was not executed.

**Comment by RaduBerinde** [comment]
`-rewrite` doesn't work well when you run only some subtests in a file.

**Comment by C0rWin** [comment]
> `-rewrite` doesn't work well when you run only some subtests in a file.

yep, thanks, realize that now, I have hit this several times in the past by was cautions enough to catch before pushed changes, unfortunately overlooked it this time.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48306)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @C0rWin and @jordanlewis)

___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 2528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M7el46X3PcwTgcm-hfw:-M9od8J8CPxdU4aBZQGf:bd8f2u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/93610368081ecce9ff763981324371c970efa768/pkg/sql/logictest/testdata/logic_test/aggregate#L2528)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Are there any tests for what happens when there's a duplicate object key? Please add tests for that, thanks!
</blockquote></details>

Hm, currently we deviate from Postgres in how we handle duplicate keys. Postgres seems to keep all of them whereas we keep only the last one.

PG:
```
yuzefovich=# CREATE TABLE profiles (
  userid int not null,
  property text not null,
  value text not null
);
CREATE TABLE
yuzefovich=# INSERT INTO profiles VALUES (1, 'email', 'foo'), (1, 'email', 'bar');
INSERT 0 2
yuzefovich=# SELECT json_object_agg(property, value) FROM profiles GROUP BY userid ORDER BY userid;
           json_object_agg            
--------------------------------------
 { "email" : "foo", "email" : "bar" }
(1 row)
```
CRDB:
```
root@127.0.0.1:50547/defaultdb> SELECT json_object_agg(property, value) FROM profiles GROUP BY userid ORDER BY userid;
  json_object_agg
--------------------
  {"email": "bar"}
(1 row)
```

I believe it is an existing behavior of `jsonObjectBuilder`, and this PR simply adds another case for when we use that object. @jordanlewis I think it should be ok to merge this, what do you think?

**Comment by C0rWin** [comment]
> I believe it is an existing behavior of `jsonObjectBuilder`, and this PR simply adds another case for when we use that object. @jordanlewis I think it should be ok to merge this, what do you think?

@yuzefovich please take a look on @jordanlewis answer here #48841

`Use jsonb_build_object, in Postgres the json ones aren't semantic json, just a text format. We emulate the jsonb ones as the json type is not really that useful in Postgres.`

**Comment by jordanlewis** [comment]
Yes, @yuzefovich we don't try to emulate the `json_xyz` builtins, just the `jsonb_xyz` ones (though we alias our `json_xyz` to the `jsonb_xyz` before for convenience, perhaps that was a bad idea in retrospect).

**Review by yuzefovich — APPROVED** [review]
Ok, cool, :lgtm:

I left last couple of nits, and once those are addressed, I'll merge this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-:-M9sWFrP6Dppy10DiNbD:b-7aehrf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @C0rWin and @jordanlewis)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 828 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M9sVDI61X8AbmwO1_ya:-M9sVDI61X8AbmwO1_yb:b8ilhab) ([raw file](https://github.com/cockroachdb/cockroach/blob/79df472e1a62daae5b2d8278446af7876e1e5bec/pkg/sql/opt/optbuilder/groupby.go#L828)):*
> ```Go
> 		return b.factory.ConstructPercentileCont(args[0], args[1])
> 	case "json_object_agg":
> 		return b.factory.ConstructJsonbObjectAgg(args[0], args[1])
> ```

nit: the calls are mismatched with the respective cases.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 3059 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M9sV_NQ0cyyCKHgEA6O:-M9sV_NQ0cyyCKHgEA6P:b-ckldcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/79df472e1a62daae5b2d8278446af7876e1e5bec/pkg/sql/sem/builtins/aggregate_builtins.go#L3059)):*
> ```Go
> 	}
> 
> 	// If only key datum equal to null, return error.
> ```

nit: there is something slightly off with the comment, I'd probably replace it with something like "If the key datum is NULL, return an error."
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 3081 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M9sVwh9DpFrTFjGdYRO:-M9sVwh9DpFrTFjGdYRP:b-uwc9zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/79df472e1a62daae5b2d8278446af7876e1e5bec/pkg/sql/sem/builtins/aggregate_builtins.go#L3081)):*
> ```Go
> }
> 
> // Result returns an DJSON from the array of JSON.
> ```

nit: `s/an DJSON/a DJSON/`.
___
*[pkg/util/json/json.go, line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-M8m2zMl5l3X_IioP7YN:-M9sW4_I16eHZJSN6NmH:b-82oqa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d710c3f3067b7ef20dcc9aee3d197317290ed544/pkg/util/json/json.go#L246)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: `s/keeping of the/keeping the/` and we strive for lines no longer than 80 characters.
</blockquote></details>

Ping.

**Comment by C0rWin** [comment]
> I left last couple of nits, and once those are addressed, I'll merge this.

@yuzefovich thanks, done.

**Review by yuzefovich — APPROVED** [review]
Thanks for your contribution!

bors r=yuzefovich

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48306#-:-M9txB4B26iJqVF0XL5z:b-5br0rs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @C0rWin and @jordanlewis)

**Pull request merged**
