### PR TITLE
sql: refactor dates to be fully PG compatible

### LINKED ISSUE #36557: sql: dates are not roundtrippable
```
SELECT
    7133080445639580613::INT8 + '1977-11-03'::DATE,
    '-239852040018-04-28':::DATE,
    (7133080445639580613::INT8 + '1977-11-03'::DATE) = '-239852040018-04-28':::DATE;
```

Returns:

```
               ?column?              |                date                | ?column?  
+------------------------------------+------------------------------------+----------+
  -239852040018-04-28 00:00:00+00:00 | -239852040018-04-28 00:00:00+00:00 |  false   
```

These two expressions return the same text string, but are nonetheless not equal. Dates are stored as an integer number of days. The first date is 7133080445639583476 and the second -87604159445685. There must be some logic in the date printing that overflows? Unsure. But this matters because when distsql serializes things they need to deserialize exactly.

### PR DESCRIPTION
**Pull request by madelynnblue**
Previously dates were an int64 number of days from 1970-01-01. Functions
and operators needing to act on a date could manipulate the value of
the date without any overflow checks, causing multiple bugs:

- The postgres binary wire protocol uses an int32 number of days since
2000-01-01, thus it was possible to have dates in cockroach outside
of the expressible range over the wire. We were blindly converting the
int64 to an int32, possibly discarding data.
- Adding dates to ints was done by normal addition. However this could
overflow. Our normal int + int path uses overflow-checked addition,
but dates were not subject to such checks.
- Converting dates to a text representation (for sending over pgwire or
our distsql serialization) converted the number of days to a time.Time
using the standard library time.Date method, which (more-or-less) stores
time as an int64 number of nanos. A very high year could overflow the
nanosecond part causing it to silently by incorrect.
- The infinity dates were not treated as infinity, but converted to an
actual date.

This change adds a new pgdate.Date type. It internally represented as
an int32 number of days since 2000-01-01, because that's exactly what
is needed by the postgres wire protocol. It doesn't export any internal
properties, and instead forces users of it to use its API, which is
guaranteed to be safe. The API does all overflow and bounds checking,
and correctly handles the infinity dates. This fixes the above bugs
since it's now not possible to mistakenly misuse Dates.

When reading from any existing on-disk data, dates outside of the postgres
bounds are converted to +/- infinity. This presents a problem since
datums need to roundtrip to the same on-disk encoding so that old index
entries can be deleted. In order to round trip correctly, the original
on-disk integer is saved and used during serialization if it exists.

Fixes #36557

Release note (sql change): Dates are now fully Postgres-compatible,
including support for sentinel values (+/- infinity) and the Postgres
date range (4714-11-24 BC to 5874897-12-31). Existing dates outside of
this range will be converted to the +/- infinity dates.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
This is great stuff! The API is very clean!

And I also like the compatibility approach that you and Bram came up with. Just wondering: do we plan to ever remove `orig` fields to reduce the space usage? I understand that it'll break the compatibility with already existing indices, but maybe like in 2 or 3 major releases?

> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-:-LcmP88j11I8rHfOPRYP:b-fcdnrw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, and @mjibson)

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmB8Q88R1Q6HlRb95C:-LcmB8Q88R1Q6HlRb95D:b-3ohxm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/sql/logictest/testdata/logic_test/datetime#L143)):*
> ```
> 
> query TTTT
> SELECT 'infinity'::date + 1, 'infinity'::date - 1, '-infinity'::date + 1, '-infinity'::date - 1
> ```

[nit]: this query overlaps with the one a few above, possibly combine them.
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmBlcq-1Y6HkvuY3_y:-LcmBlcq-1Y6HkvuY3_z:b-2o0bnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/sql/logictest/testdata/logic_test/datetime#L1281)):*
> ```
> subtest regression_36146
> 
> statement error out of range
> ```

Why does it have a different error message?
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 853 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmLu0a2OZvm0ErjALn:-LcmLu0a2OZvm0ErjALo:b-whtacr) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/sql/logictest/testdata/logic_test/pg_catalog#L853)):*
> ```
> 1042  bpchar        1307062959    NULL      -1      false     b
> 1043  varchar       1307062959    NULL      -1      false     b
> 1082  date          1307062959    NULL      16      true      b
> ```

[question]: just to confirm my understanding, `days` take up 4 bytes, `orig` another 8, and `hasOrig` yet another 4 bytes, correct?
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmGP9pAuNTwb01wuJW:-LcmGP9pAuNTwb01wuJX:bvrjy4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L18)):*
> ```Go
> // and times in a manner that is compatible with PostgreSQL.
> //
> // The implementation here is inspired by the following
> ```

[nit]: possibly this comment needs adjusting.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmH7Uz0DkoXIWh1NPI:-LcmH7Uz0DkoXIWh1NPJ:b7humzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L69)):*
> ```Go
> 	// instead of days when encoding for on-disk. This is required
> 	// so that we can roundtrip to the same on-disk value, which is
> 	// necessary deleting old index entries. This value should never
> ```

[nit]: necessary for deleting.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmJGzqEBJ5WE_fA3OW:-LcmJGzqEBJ5WE_fA3OX:b-u72xas) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L138)):*
> ```Go
> }
> 
> func makeDateFromYMD(year, month, day int) Date {
> ```

I can't seem to find where this method is used. Also, is `panic`king here unavoidable? Maybe return an error instead?
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmKE116dwnoqDYOeBh:-LcmKE116dwnoqDYOeBi:b-95t1eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L164)):*
> ```Go
> 	secondsPerHour  = 60 * 60
> 	secondsPerDay   = 24 * secondsPerHour
> 	daysPer400Years = 365*400 + 97
> ```

Also I can't seem to find where these `daysPer...` are used.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmK9Hb7v2n-nXrZo5b:-LcmK9Hb7v2n-nXrZo5c:bvp25hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L176)):*
> ```Go
> 	case math.MaxInt32:
> 		buf.WriteString("infinity")
> 	default:
> ```

Do we need a special case for `epoch` here?
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmL77f2QMkKG8HmLcG:-LcmL77f2QMkKG8HmLcH:bg71gya) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L262)):*
> ```Go
> 	if !ok {
> 		return Date{}, pgerror.NewErrorf(pgerror.CodeDatetimeFieldOverflowError,
> 			"%s + %d is out of range", d, days)
> ```

[nit]: `%s - %d`.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36938)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmB8Q88R1Q6HlRb95C:-LcnK5le65y3cZ2VNv2z:b82wn8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/sql/logictest/testdata/logic_test/datetime#L143)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: this query overlaps with the one a few above, possibly combine them.
</blockquote></details>

Removed, it was redundant.
___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 1281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmBlcq-1Y6HkvuY3_y:-LcnK9uvAWRNs-8qR4Sl:b-xni3g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/sql/logictest/testdata/logic_test/datetime#L1281)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why does it have a different error message?
</blockquote></details>

The original problem happened because of overflow during distsql serialization. But now it's not possible to even create that date.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 853 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmLu0a2OZvm0ErjALn:-LcnKIeaEBtkndibIj_C:bq70tnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/sql/logictest/testdata/logic_test/pg_catalog#L853)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[question]: just to confirm my understanding, `days` take up 4 bytes, `orig` another 8, and `hasOrig` yet another 4 bytes, correct?
</blockquote></details>

Go aligns things at word boundaries for adjacent properties. So days is 4, hasOrig is 1, and there's 3 unused bytes, but 8 total. Then orig is another 8.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmGP9pAuNTwb01wuJW:-LcnKzPxAlBPDPp5a4Vv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L18)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: possibly this comment needs adjusting.
</blockquote></details>

Done.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmH7Uz0DkoXIWh1NPI:-LcnL3950m0VkwZGUGTM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L69)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: necessary for deleting.
</blockquote></details>

Done.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmJGzqEBJ5WE_fA3OW:-LcnL3wd4Kz99RGJOmg2:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L138)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I can't seem to find where this method is used. Also, is `panic`king here unavoidable? Maybe return an error instead?
</blockquote></details>

Removed.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmKE116dwnoqDYOeBh:-LcnL4sK6S213xkDQkVN:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L164)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Also I can't seem to find where these `daysPer...` are used.
</blockquote></details>

Removed.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmK9Hb7v2n-nXrZo5b:-LcnL63zEr9I3qYcQ8Ff:bvzh1o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L176)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do we need a special case for `epoch` here?
</blockquote></details>

No. Epoch is an alias for 1970-01-01, it's not preserved as the word 'epoch'.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcmL77f2QMkKG8HmLcG:-LcnLC_3CCxDcPxGVD4m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cf7b3b2a488acbc1e8ac5d9d3d0c555f0d8f9e/pkg/util/timeutil/pgdate/pgdate.go#L262)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `%s - %d`.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
This is very good work. I love that I was feeling like I was learning something while reading the code of the new date package. Eventually I have a dream we give dedicated packages with proper semantics to all the scalar types. 

Only a few comments below.

> Reviewed 24 of 29 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-:-LcosRAB-1mKbhGPlkC4:buvkz81)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @mjibson, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcoqOTX5pkGludSSu1y:-LcoqOTY6YPBO90SeANC:bd1ncvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/logictest/testdata/logic_test/datetime#L124)):*
> ```
> '0001-12-13 BC'::date
> ```

psql gives me " 0001-12-13 BC" on this
your test displays "0000-12-13"

is that intended?

(I suspect it is -- we're merely seeing Go's conversion of a time.Time to string, which can display year 0. However in that case I would invite you to also test/display the result of converting the date back to `::string`. Thank you.)
___
*[pkg/sql/sem/tree/eval.go, line 701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcorBEo5lLs-yu1Pj6c:-LcorBEo5lLs-yu1Pj6d:b-u9gm9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/sem/tree/eval.go#L701)):*
> ```Go
> 			Fn: func(_ *EvalContext, left Datum, right Datum) (Datum, error) {
> 				a, b := MustBeDInt(left), MustBeDInt(right)
> 				r, ok := arith.SubWithOverflow(int64(a), int64(b))
> ```

This change does not belong to this commit. Please extract it to a separate commit in the sequence (or a subsequent PR) for clarity.
___
*[pkg/sql/sem/tree/eval.go, line 3111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcorNYNC1Syan667LgO:-LcorNYNC1Syan667LgP:bf879fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/sem/tree/eval.go#L3111)):*
> ```Go
> 			res = NewDInt(DInt(v.Unix()))
> 		case *DDate:
> 			// TODO(mjibson): This cast is unsupported by postgres. Should we remove ours?
> ```

Huh, why remove it - the semantics are super well defined.

I agree on the error, but out of curiosity: what is the SQL way to test whether a date is infinite?
___
*[pkg/sql/sem/tree/eval.go, line 3158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-Lcora9QC-5m4wMUB6Dt:-Lcora9QC-5m4wMUB6Du:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/sem/tree/eval.go#L3158)):*
> ```Go
> 		case *DDate:
> 			// TODO(mjibson): This cast is unsupported by postgres. Should we remove ours?
> 			if !v.IsFinite() {
> ```

ditto
___
*[pkg/sql/sem/tree/eval.go, line 3180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcorjM1-fP5PHitvFyK:-LcorjM1-fP5PHitvFyL:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/sem/tree/eval.go#L3180)):*
> ```Go
> 			// TODO(mjibson): This cast is unsupported by postgres. Should we remove ours?
> 			if !v.IsFinite() {
> 				return nil, errDecOutOfRange
> ```

ditto
___
*[pkg/sql/sem/tree/eval.go, line 3322 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcorkvD6q6bnyxR3YH5:-LcorkvD6q6bnyxR3YH6:b34ni6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/sem/tree/eval.go#L3322)):*
> ```Go
> 			return d, nil
> 		case *DInt:
> 			// TODO(mjibson): This cast is unsupported by postgres. Should we remove ours?
> ```

Same comment as above - the semantics are well defined. I don't see a reason to remove.

**Review by bobvawter — CHANGES_REQUESTED** [review]
> Reviewed 24 of 29 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36938)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @mjibson, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcoqOTX5pkGludSSu1y:-LcpyHJk-Yjzrzeqr4cM:bde0oyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/logictest/testdata/logic_test/datetime#L124)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> ```
> '0001-12-13 BC'::date
> ```

psql gives me " 0001-12-13 BC" on this
your test displays "0000-12-13"

is that intended?

(I suspect it is -- we're merely seeing Go's conversion of a time.Time to string, which can display year 0. However in that case I would invite you to also test/display the result of converting the date back to `::string`. Thank you.)
</blockquote></details>

This a weird formatting case where year 0 is what we'd normally write as 1 BC.  Year -1 is 2 BC, etc.  We should probably avoid using go's stringification as a follow-on patch to make the output consistent with pg.
___
*[pkg/util/arith/arith.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-Lcq-3IJ9tLxc2ITVYC6:-Lcq-3IK2601pyE3LXvZ:b-s0mrih) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/util/arith/arith.go#L32)):*
> ```Go
> // Add32to64WithOverflow returns a+b. If ok is false, a+b overflowed.
> func Add32to64WithOverflow(a int32, b int64) (r int32, ok bool) {
> 	if b > math.MaxInt32 || b < math.MinInt32 {
> ```

How are these functions supposed to behave?  Are they guaranteeing that the operation can be performed and that the resulting value fits within the return type?  Consider the case where `a := MaxInt32` and `b := MinInt32-1`.  I would expect this function to return `-1` since the result is in range, even though it may have required performing the math using more bits. 
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-Lcq0T4O21UcUiClP31P:-Lcq0T4O21UcUiClP31Q:bnvz8fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/util/timeutil/pgdate/pgdate.go#L58)):*
> ```Go
> 
> // Date is a postgres-compatible date implementation. It stores the number
> // of seconds from the postgres epoch (2000-01-01). Its properties are
> ```

If it's storing seconds, why is the field called days?
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-Lcq1HoC7AxUGbdrHl2o:-Lcq1HoC7AxUGbdrHl2p:b-nlxlup) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/util/timeutil/pgdate/pgdate.go#L210)):*
> ```Go
> 
> // Compare compares two dates.
> func (d Date) Compare(other Date) int {
> ```

Is it valid to just `return d.days - other.days`?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36938)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, @mjibson, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/datetime, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcoqOTX5pkGludSSu1y:-Lcql_7tBeW0Cmw2w3ex:bwbf5tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/logictest/testdata/logic_test/datetime#L124)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This a weird formatting case where year 0 is what we'd normally write as 1 BC.  Year -1 is 2 BC, etc.  We should probably avoid using go's stringification as a follow-on patch to make the output consistent with pg.
</blockquote></details>

Added a test for the string conversion.
___
*[pkg/sql/sem/tree/eval.go, line 701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcorBEo5lLs-yu1Pj6c:-Lcqlfza2bGzbIUThMUC:b-ubmxz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/sem/tree/eval.go#L701)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This change does not belong to this commit. Please extract it to a separate commit in the sequence (or a subsequent PR) for clarity.
</blockquote></details>

Moved to second commit.
___
*[pkg/sql/sem/tree/eval.go, line 3111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcorNYNC1Syan667LgO:-LcqljaM4MCY2Axp6mWT:b57t8fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/sem/tree/eval.go#L3111)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Huh, why remove it - the semantics are super well defined.

I agree on the error, but out of curiosity: what is the SQL way to test whether a date is infinite?
</blockquote></details>

The semantics used to be well defined: return the integer number of days since the unix epoch. Now that we support infinity dates, they are no longer well defined. What should we do in the infinity case? Should we return infinity for float and decimals since they support it? Should we not check for infinity at all, but instead just return whatever's there (max/min int32 in the inf cases)? Since postgres doesn't do this we can't check for compatibility, but it definitely adds some questions without clear answers. Furthermore, we chose the unix epoch fairly arbitrarily (especially considering that postgres uses a different epoch underneath). A user just has to know that these conversions use the unix epoch number of days, which isn't obvious at all.

I believe postgres made the better design choice here which is to support only the `date - date` operator which returns the number of days between those two dates, and errors if either are infinity. This absolves the database of having to choose an arbitrary epoch, is conceptually more obvious than raw number conversion, and the infinity problem is a bit simpler also.
___
*[pkg/util/arith/arith.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-Lcq-3IJ9tLxc2ITVYC6:-LcqoMb8-iZVrGoiHe31:bj82nzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/util/arith/arith.go#L32)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

How are these functions supposed to behave?  Are they guaranteeing that the operation can be performed and that the resulting value fits within the return type?  Consider the case where `a := MaxInt32` and `b := MinInt32-1`.  I would expect this function to return `-1` since the result is in range, even though it may have required performing the math using more bits. 
</blockquote></details>

For now they are fine. I've added a comment describing the int32 size requirement of b so it's operation is clearer. But postgres doesn't support date - int8, only date - int4, so we are within the spec for now.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-Lcq0T4O21UcUiClP31P:-LcqnYFi0xCC2xDV--IJ:b-7l8qd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/util/timeutil/pgdate/pgdate.go#L58)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

If it's storing seconds, why is the field called days?
</blockquote></details>

seconds was a typo. Fixed the comment to say days.
___
*[pkg/util/timeutil/pgdate/pgdate.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-Lcq1HoC7AxUGbdrHl2o:-LcqnlvH1ofnuY4tNLqh:b-geghoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/util/timeutil/pgdate/pgdate.go#L210)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Is it valid to just `return d.days - other.days`?
</blockquote></details>

No, the API docs for tree.Datum.Compare specify +/- 1, not positive or negative.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-:-LcrlLwY1oTI1CJEcaet:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter, @knz, @mjibson, and @yuzefovich)

**Review by knz — APPROVED** [review]
:lgtm: but I still don't like a "TODO: remove this" for valid and well-defined features :)

> Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-:-Ld-ks2m0noWn3SavQAT:b2i2mqt)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @bobvawter, @mjibson, and @yuzefovich)

___
*[pkg/sql/sem/tree/eval.go, line 3111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-LcorNYNC1Syan667LgO:-Ld-k2sP4gO1hics7yGQ:buuwo2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b90876b132ac554b1fa2246e1f27a47a9d3e76f/pkg/sql/sem/tree/eval.go#L3111)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

The semantics used to be well defined: return the integer number of days since the unix epoch. Now that we support infinity dates, they are no longer well defined. What should we do in the infinity case? Should we return infinity for float and decimals since they support it? Should we not check for infinity at all, but instead just return whatever's there (max/min int32 in the inf cases)? Since postgres doesn't do this we can't check for compatibility, but it definitely adds some questions without clear answers. Furthermore, we chose the unix epoch fairly arbitrarily (especially considering that postgres uses a different epoch underneath). A user just has to know that these conversions use the unix epoch number of days, which isn't obvious at all.

I believe postgres made the better design choice here which is to support only the `date - date` operator which returns the number of days between those two dates, and errors if either are infinity. This absolves the database of having to choose an arbitrary epoch, is conceptually more obvious than raw number conversion, and the infinity problem is a bit simpler also.
</blockquote></details>

- the infinity support is new, so it's just normal we have to ask the question and a good answer. If we don't want to answer this now, you can refuse the conversion from an infinity date with an error, like you did here. If we want an answer, I agree with you that likely conversion to/from floats and decimals should use infinities in that case. I don't have a clear opinion about integers (should remain an error until then).

- conversions with numbers using the epoch as reference is a common choice for server software. It's also consistent with the other date/time/timestamp conversions. It's a matter of documentation (for people who don't expect epoch-based conversions already).

**Review by bobvawter — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36938#-:-Ld4TtGY8rBBRwslUmmt:bg7igkv)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @mjibson and @yuzefovich)

**Pull request merged**
