### PR TITLE
Use go-metrics in status monitor

### PR DESCRIPTION
**Pull request by mrtracy**
Use package 'github.com/rcrowley/metrics' to manage metrics recording in the
node status monitor. Current functionality is exactly the same as it was before;
however, this new factoring will make it much easier to add more advanced
statistics such as moving averages and histograms.

This refactoring also moves the responsibility of naming metrics to the Monitor,
when it was previously in the recorder; this should also make managing larger
sets of statistics more straightforward.

Finally, this commit removes the `rangeDataAccumulator` interface completely;
having moved to a table-based system, we clearly are not intending to gather
statistics based on accounting prefixes, which was the original intention of
this system. This is a significant simplification; a subsequent commit should
completely remove the "beginScanRanges" and "endScanRanges" events from the
feed.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3273)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[server/status/monitor.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XSdLW46A7-HW0DWUR:-K4XSdLW46A7-HW0DWUS:865757923) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor.go#L30)):*
nit: move this about cockroach imports

---

*[server/status/monitor.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XSnsFvmD8z-2nxpqj:-K4XSnsFvmD8z-2nxpqk:-314515615) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor.go#L43)):*
can you rearrange such that this mutex is only followed by the fields it protects?

---

*[server/status/monitor.go, line 184 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XTVSyoeYY2kCfKSKD:-K4XTVSyoeYY2kCfKSKE:46867402) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor.go#L184)):*
can you change `ReplicationStatusEvent` to contain int64s?

---

*[server/status/monitor.go, line 308 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XVHZKaFzEaKpMoUVN:-K4XVHZKaFzEaKpMoUVO:262493016) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor.go#L308)):*
why does this need to be under lock? looks like all the gauges use atomics.

---

*[server/status/monitor_test.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XVbkC_hBnygbY6Z_c:-K4XVbkC_hBnygbY6Z_d:2042360811) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor_test.go#L30)):*
nit: move

---

*[server/status/recorder.go, line 28 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XVsDZM4W5rrNHvixJ:-K4XVsDZM4W5rrNHvixK:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/recorder.go#L28)):*
ditto

---

*[server/status/recorder.go, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XVu2j_NqalwI67B5I:-K4XVu2j_NqalwI67B5J:-632527180) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/recorder.go#L32)):*
needs an update

---

*[server/status/recorder.go, line 36 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XW1cu6gE_dfA8qYF9:-K4XW1cu6gE_dfA8qYFA:-1822405283) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/recorder.go#L36)):*
update name

---

*[server/status/recorder.go, line 137 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XW7ZfmHytcB2P2acg:-K4XW7ZfmHytcB2P2ach:-1027351282) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/recorder.go#L137)):*
as above: how painful is it to propagate this change to int32?

---

*[server/status/recorder_test.go, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XWTA_d5W34tMmm-U0:-K4XWTAa8n5tPdEFF4H_:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/recorder_test.go#L32)):*
ditto

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273)*

**Comment by tschottdorf** [comment]
LGTM (mod Tamir), though the package is `https://github.com/rcrowley/go-metrics` (in your commit message). Nice to see this get simplified.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-:-K4Y_zF2qHmlxyuK91oY:-1150242803)*

**Comment by mrtracy** [comment]
Review status: 1 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[server/status/monitor.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XSnsFvmD8z-2nxpqj:-K4ZL8lKC5MyaKGHvgbs:-309798324) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor.go#L43)):*
I believe I already did that, but this comment refers to two specific fields. I will make the comment less specific.

---

*[server/status/monitor.go, line 184 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XTVSyoeYY2kCfKSKD:-K4ZLNS0-X8PFSCxBQrn:-757579664) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor.go#L184)):*
Yes, this one didn't involve any test changes. Done.

---

*[server/status/monitor.go, line 308 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XVHZKaFzEaKpMoUVN:-K4ZM2uqXmhkaDXYH8EY:481918375) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor.go#L308)):*
because the `MVCCStats` variable being read from needs to be locked.  I considered making these counters and doing the increments directly without keeping the incremental `MVCCStats`, but there is a small amount of non-trivial logic in `MVCCStats.Add()` so I did not do this. 

---

*[server/status/monitor_test.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XVbkC_hBnygbY6Z_c:-K4ZSwIJ5LPVKKvjr5Ku:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor_test.go#L30)):*
Done.

---

*[server/status/recorder.go, line 28 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XVsDZM4W5rrNHvixJ:-K4ZSuk41W91hVDOtei4:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/recorder.go#L28)):*
Done.

---

*[server/status/recorder.go, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XVu2j_NqalwI67B5I:-K4ZSeG9MhOYSMi52UGS:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/recorder.go#L32)):*
Done.

---

*[server/status/recorder.go, line 36 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XW1cu6gE_dfA8qYF9:-K4ZSd3qk-pfiitcmRqL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/recorder.go#L36)):*
Done.

---

*[server/status/recorder.go, line 137 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XW7ZfmHytcB2P2acg:-K4ZSOC_YndoY1NKCYAK:-1374253550) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/recorder.go#L137)):*
This change is a little harder and involves quite a few protocol buffer and test changes.  I think i'll add a TODO().

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273)*

**Comment by mrtracy** [comment]
Review status: 1 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[server/status/monitor.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XSdLW46A7-HW0DWUR:-K4ZXfDpydl2-b1X1grE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor.go#L30)):*
Done.

---

*[server/status/recorder_test.go, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XWTA_d5W34tMmm-U0:-K4ZXdb36fk3ubHzcnla:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/recorder_test.go#L32)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[server/status/monitor.go, line 308 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XVHZKaFzEaKpMoUVN:-K4Z_DFOIL6oEV0L1Bjm:163356956) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor.go#L308)):*
Should there be a TODO here, then?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273)*

**Comment by tschottdorf** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/status/monitor.go, line 308 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-K4XVHZKaFzEaKpMoUVN:-K4d4YE9prwoTrRv6j7P:2145334307) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ce42709ba0864ad7cf59641c54c754bfc6a925e/server/status/monitor.go#L308)):*
No, I don't think so.  Some of these persistent storage stats are going to be getting an overhaul in the short term, I don't think this will survive; however, if it *does* survive, then the current implementation is acceptable.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273)*

**Comment by mrtracy** [comment]
Updated the commit message with the correct package.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273#-:-K4d4nfOEtY5mQ_i-oRy:-1681409602)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3273)*

**Pull request merged**
