### PR TITLE
release-23.2.5-rc: opt: improve partial index implication with virtual columns

### LINKED ISSUE #122352: sql/opt: prove partial index implication with in-exact atoms containing virtual computed columns
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

```
--! The following works as expected
CREATE TABLE test_index_stored (
    a int primary key,
    b jsonb
);

ALTER TABLE test_index_stored ADD COLUMN c STRING AS (b->>'c') STORED;
ALTER TABLE test_index_stored ADD COLUMN d STRING AS (b->>'d') STORED;
ALTER TABLE test_index_stored ADD COLUMN e INT AS ((b->>'e')::INT) STORED;
CREATE INDEX ON test_index_stored(c, e) WHERE c IS NOT NULL AND e IS NOT NULL;

INSERT INTO test_index_stored VALUES (1, '{"c": "foo", "d": "bar", "e": 5}');

SELECT c, e FROM test_index_stored@test_index_stored_c_e_idx WHERE c = 'foo' AND e > 4;  --! works

```
```
--! The following fails:
CREATE TABLE test_index_virtual (
    a int primary key,
    b jsonb
);

ALTER TABLE test_index_virtual ADD COLUMN c STRING AS (b->>'c') VIRTUAL;
ALTER TABLE test_index_virtual ADD COLUMN d STRING AS (b->>'d') VIRTUAL;
ALTER TABLE test_index_virtual ADD COLUMN e INT AS ((b->>'e')::INT) VIRTUAL;
CREATE INDEX ON test_index_virtual(c, e) WHERE c IS NOT NULL AND e IS NOT NULL;

INSERT INTO test_index_virtual VALUES (1, '{"c": "foo", "d": "bar", "e": 5}');

SELECT c, e FROM test_index_virtual@test_index_virtual_c_e_idx WHERE c = 'foo' AND e > 4; --! fails
SELECT c, e FROM test_index_virtual@test_index_virtual_c_e_idx WHERE c is not null and e is not null; --! works
SELECT c, e FROM test_index_virtual@test_index_virtual_c_e_idx WHERE c is not null and e is not null and c = 'foo' and e > 4; --! fails
```

Spent quite some time investigating the problem, even tried to force the index scan.  The exception was thrown here: https://github.com/cockroachdb/cockroach/blob/67547d7724f8a52646e2e8ecb3ca48b923957d90/pkg/sql/opt/exec/execbuilder/relational.go#L598, when the index that is actually needed mismatches the index in the flag. 

Changed the code to force the scan the flags.index, the query worked, but empty result was returned, likely due to predicate matching.
It seemed to me that the predict added here can be further pruned: https://github.com/cockroachdb/cockroach/blob/67547d7724f8a52646e2e8ecb3ca48b923957d90/pkg/sql/opt/optbuilder/select.go#L643
and it might also have something to do with virtual columns, because they are always applied a projection

**Expected behavior**
The query should not fail.

**Environment:**
 - CockroachDB version 24.1 alpha, also have tested on 23.1.17 and 23.2.3
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`]

Jira issue: CRDB-37825

### PR DESCRIPTION
**Pull request by mgartner**
Backport 3/3 commits from #123163.

/cc @cockroachdb/release

---

#### opt: add Implicator benchmarks with virtual columns

Release note: None

#### opt: improve partial index implication with virtual columns

The partial index implicator is now aware of computed columns and their
expressions. This allows implication to be proven in more cases. For
example, consider the table and query:

    CREATE TABLE (
      j JSONB,
      i INT AS ((j->>'x')::INT) VIRTUAL,
      INDEX (i) WHERE i IS NOT NULL
    );

    SELECT * FROM t WHERE i = 10;

Prior to this commit, the optimizer would not plan a constrained scan
over the partial index because the implicator could not prove that the
query filters, pushed into the projection as `(j->>'x')::INT = 10`,
imply the partial index predicate, built as
`(j->>'x')::INT IS NOT NULL`. To prove implication cases like this where
the expressions are not exact matches, the implicator must build
constraints to check if the predicate contains the filter. Constraints
cannot be built from these expressions, so verifying containment was
impossible.

Now that the implicator is aware of computed columns and their
expressions, it converts the filter and predicate into expressions
referencing virtual computed columns: `i = 10` and `i IS NOT NULL`.
Constraints can be built from expressions in this forms, containment can
be checked, and implication can be proven.

Fixes #122352

Release note (sql change): The optimizer can now plan constrained scans
over partial indexes in more cases, particularly on partial indexes with
predicates referencing virtual computed columns.

#### opt: add session setting for virtual computed column implication

The `optimizer_prove_implication_with_virtual_computed_columns` has been
added which, when enabled, indicates that virtual computed columns
should be considered during partial index implication to try to prove
that a filter implies a predicate.

Release note: None

---

Release justification: Fix for limitation with partial indexes and
virtual computed columns that is gated behind a session setting.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Once the `memo_test.go` backport is fixed.

> Reviewed 1 of 1 files at r1, 7 of 7 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-:-NwrTcvOD-Ok8i1fUL4c:b-70g9yg)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/memo/memo_test.go` line 434 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-NwrTNfaBJk9Yp4ToOFz:-NwrTNfaBJk9Yp4ToOG-:b-2k7x23) ([raw file](https://github.com/cockroachdb/cockroach/blob/591283db4881a255d3dd8cdb5a8336a0d0e60853/pkg/sql/opt/memo/memo_test.go#L434)):*
> ```Go
> 
> <<<<<<< HEAD
> =======
> ```

Looks like this bit didn't backport cleanly

**Review by rytaft — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 7 of 7 files at r2, 10 of 10 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123408)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/partialidx/implicator.go` line 541 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-Nwtd3ic8p2rqdeHTZ86:-Nwtd3ic8p2rqdeHTZ87:b-7jkia0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/implicator.go#L541)):*
> ```Go
> 			}
> 		}
> 		return im.f.Replace(e, replace)
> ```

This doesn't look like it will terminate if there are no matching computed columns. What am I missing?
___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-Nwte1MwAGDXtnw06O4t:-Nwte1MwAGDXtnw06O4u:b-v2l92k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/testdata/implicator/virtual#L5)):*
> ```
> # Atoms with no computed column references.
> #
> # These cases best simulate filter-predicate implication in practice, compared
> ```

I'm confused, these cases do seem to contain computed column references.
___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-NwteJ96-rkGnRJBF92q:-NwteJ96-rkGnRJBF92r:b-ngj4kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/testdata/implicator/virtual#L152)):*
> ```
> # Atoms with virtual computed columns referenced in the filter. This should
> # never happen in practice because virtual computed column references should be
> # replaced with their computed expression.
> ```

but isn't this replacing happening as part of implication?
___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-NwteQauBlf8jMCCssNi:-NwteQauBlf8jMCCssNj:b-l8l7r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/testdata/implicator/virtual#L180)):*
> ```
> # Atoms with virtual computed columns referenced in the predicate. This should
> # never happen in practice because virtual computed column references should be
> # replaced with their computed expression.
> ```

same question
___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-NwteebI0Wr8JB0fs1eb:-NwteebI0Wr8JB0fs1ec:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/testdata/implicator/virtual#L208)):*
> ```
> # Atoms with virtual computed columns referenced in the filter and predicate.
> # This should never happen in practice because virtual computed column
> # references should be replaced with their computed expression.
> ```

ditto

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123408)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rytaft)

___
*[`pkg/sql/opt/partialidx/implicator.go` line 541 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-Nwtd3ic8p2rqdeHTZ86:-NwtzH4TEh8gWhw0GyNe:b-vazip5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/implicator.go#L541)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This doesn't look like it will terminate if there are no matching computed columns. What am I missing?
</blockquote></details>

This is the standard pattern for replacement. `im.f.Replace` will call `replace` on each of `e`'s children, not on `e` itself. So it will terminate.
___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-Nwte1MwAGDXtnw06O4t:-NwtyzxLBBdIbwFYPpqD:bllgsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/testdata/implicator/virtual#L5)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm confused, these cases do seem to contain computed column references.
</blockquote></details>

They contain the computed columns' expression, but they do not reference the computed columns.
___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-NwteJ96-rkGnRJBF92q:-Nwtyjkk2VCqMlOumB_m:b-yobz49) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/testdata/implicator/virtual#L152)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

but isn't this replacing happening as part of implication?
</blockquote></details>

No, implication replaces the virtual columns' expressions with virtual column references, e.g., `(a->>'x')::INT` is replaced with `b` during implication.

I tried to explain this in the commit message a bit, but let me know if you have suggestions to make it more clear:

The partial index implicator is now aware of computed columns and their  
expressions. This allows implication to be proven in more cases. For  
example, consider the table and query:

```
CREATE TABLE (
  j JSONB,
  i INT AS ((j->>'x')::INT) VIRTUAL,
  INDEX (i) WHERE i IS NOT NULL
);

SELECT * FROM t WHERE i = 10;
```

Prior to this commit, the optimizer would not plan a constrained scan  
over the partial index because the implicator could not prove that the  
query filters, pushed into the projection as `(j->>'x')::INT = 10`,  
imply the partial index predicate, built as  
`(j->>'x')::INT IS NOT NULL`. To prove implication cases like this where  
the expressions are not exact matches, the implicator must build  
constraints to check if the predicate contains the filter. Constraints  
cannot be built from these expressions, so verifying containment was  
impossible.
___
*[`pkg/sql/opt/memo/memo_test.go` line 434 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-NwrTNfaBJk9Yp4ToOFz:-Nwtz8F5EUpIJwk4LfVV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/591283db4881a255d3dd8cdb5a8336a0d0e60853/pkg/sql/opt/memo/memo_test.go#L434)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Looks like this bit didn't backport cleanly
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-:-NwuXdTh6Zc1_EDCoyzG:bro3093)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/partialidx/implicator.go` line 541 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-Nwtd3ic8p2rqdeHTZ86:-NwuWqVA8w8kb05in-YJ:bnlm28d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/implicator.go#L541)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is the standard pattern for replacement. `im.f.Replace` will call `replace` on each of `e`'s children, not on `e` itself. So it will terminate.
</blockquote></details>

Ah right -- forgot how this worked
___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-Nwte1MwAGDXtnw06O4t:-NwuWvVX9pMV1NMWnrER:b-vo0hen) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/testdata/implicator/virtual#L5)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

They contain the computed columns' expression, but they do not reference the computed columns.
</blockquote></details>

Got it, thanks
___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-NwteJ96-rkGnRJBF92q:-NwuX7I82wAF-z5PjLPW:berkvjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/testdata/implicator/virtual#L152)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

No, implication replaces the virtual columns' expressions with virtual column references, e.g., `(a->>'x')::INT` is replaced with `b` during implication.

I tried to explain this in the commit message a bit, but let me know if you have suggestions to make it more clear:

The partial index implicator is now aware of computed columns and their  
expressions. This allows implication to be proven in more cases. For  
example, consider the table and query:

```
CREATE TABLE (
  j JSONB,
  i INT AS ((j->>'x')::INT) VIRTUAL,
  INDEX (i) WHERE i IS NOT NULL
);

SELECT * FROM t WHERE i = 10;
```

Prior to this commit, the optimizer would not plan a constrained scan  
over the partial index because the implicator could not prove that the  
query filters, pushed into the projection as `(j->>'x')::INT = 10`,  
imply the partial index predicate, built as  
`(j->>'x')::INT IS NOT NULL`. To prove implication cases like this where  
the expressions are not exact matches, the implicator must build  
constraints to check if the predicate contains the filter. Constraints  
cannot be built from these expressions, so verifying containment was  
impossible.
</blockquote></details>

Yea the commit message is clear. I was just confused by this comment in the test. Maybe it would help to say where the references get replaced (i.e., does this just happen in optbuilder? is it a normalization rule?). But it's not too important, not sure it's worth the effort to open a new PR.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123408)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rytaft)

___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123408#-NwteJ96-rkGnRJBF92q:-Nwumeq9D_sBG8ufMzI8:buzmo18) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef5ba91821ec9285c61504bfda335d9463d3d99f/pkg/sql/opt/partialidx/testdata/implicator/virtual#L152)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea the commit message is clear. I was just confused by this comment in the test. Maybe it would help to say where the references get replaced (i.e., does this just happen in optbuilder? is it a normalization rule?). But it's not too important, not sure it's worth the effort to open a new PR.
</blockquote></details>

Good point. I'll clarify in a follow-up PR, but go ahead and merge these backports.

**Pull request merged**
