### PR TITLE
xform: split custom functions into multiple files

### PR DESCRIPTION
**Pull request by mgartner**
#### xform: move select.opt functions to select_funcs.go

This is part of a refactoring to split up xform custom functions,
similar to normalization custom functions.

Release note: None

#### xform: move limit.opt functions to limit_funcs.go

Release note: None

#### xform: move groupby.opt functions to groupby_funcs.go

Release note: None

#### xform: move join.opt functions to join_funcs.go

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55838#-:-MKFii6lEs4aE1upgVVH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

**Comment by mgartner** [comment]
bors r=RaduBerinde

**Comment by mgartner** [comment]
@RaduBerinde Should I backport this refactor to make future backports less painful? If so, how far back do you think I should backport to?

**Comment by RaduBerinde** [comment]
Could go either way, I don't know if we should expect a lot of backports in xform. Up to you, but I wouldn't go farther back than 20.2.

**Pull request merged**
