### PR TITLE
cli: Fix FlagMap to work with custom struct types

### PR DESCRIPTION
**Pull request by nvb**
Related to #5642.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5645)

### CODE REVIEW

**Comment by tamird** [comment]
commit message needs more words. I'm not enough of a wizard to understand what this is doing without more words or more tests.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5645#-:-KDyo4V6befFYczuvdwj:143148408)*

**Comment by mberhault** [comment]
this is overkill when all we want is make sure we don't let flag names rot in message.
why not just have consts for flag names? that would both make sure the name gets propagated, and that removing a flag (and its const name) will properly break the build where it's used.

**Comment by nvanbenschoten** [comment]
Moving the flag names into constants so that we can get rid of this seems fine. It looks like we already have code duplication between the [flag declarations](https://github.com/cockroachdb/cockroach/blob/master/cli/flags.go#L331) and the [usage text](https://github.com/cockroachdb/cockroach/blob/master/cli/flags.go#L45), so it would also clean that up. We probably need to move most of the flag handling into a `cli/flags` package to avoid circular dependancies.

**Comment by nvanbenschoten** [comment]
@mberhault If you're not already working on this, I'll send out a PR with the proposed changes later today.

**Pull request closed without merging**
