### PR TITLE
sql, distsql: added FIRST aggregate builtin function

### PR DESCRIPTION
**Pull request by richardwu**
Release notes: feature: added the FIRST aggregation function which
returns the value of the first row seen in the group in a GROUP BY.
If there is more than one row per group, an arbitrary row is selected as
the "first".

For example, for the table
```
CREATE TABLE kv (k INT, v INT)
```

We can select an arbitrary first value v for all unique groups of k
```
SELECT FIRST(v) FROM kv GROUP BY k
```

Note that ordering information is not passed into `FIRST` as previously mentioned. This is because in a normal `GROUP BY`, ordering is always executed after any aggregations (including `FIRST`) (we do not have a postgres equivalent plan to compare to since postgres does not implement `FIRST`).

## Ordering during planning

During the planning phase, ordering is propagated from children node [through `planPhysicalProps`](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/plan_physical_props.go#L27). The actual `physicalProps struct` contains [ordering information](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/physical_props.go#L138-L141) (this ordering information can also be reduced down into `physicalProps.constantCols` via `reduce()`).

Example of how `planPhysicalProps` is used for ordering: currently, `groupNode` [has a `desiredOrdering`](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/group.go#L323) which can be used to optimize `MIN` and `MAX` aggregations by adding a `LIMIT 1` if the ordering aligns (respective of the function of course). The optimization is [accomplished during `expandPlan`](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/expand_plan.go#L153-L168) by peeking into `planPhysicalProps` (as described above) of its child node.

To address @knz's proposition of nodes that preserve ordering, we can take a look at each node derives `planPhysicalProps`:
- `sortNode`s derive their [ordering directly from the ordering set in its clause]( https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/plan_physical_props.go#L73-L104)
- `renderNode`s [re-compute the ordering from its source](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/render.go#L683-L694) via [`physicalProps.project`](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/physical_props.go#L559-L580).
- `filterNode`s [delegate the ordering](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/filter.go#L77-L80) to its child node (passthrough ordering)
- `ordinalityNode`s also derive ordering from [its source](https://github.com/cockroachdb/cockroach/blob/c9cc9eabb705cd3a52054af855f17085a2f36b01/pkg/sql/ordinality.go#L56) (note there are `restrictOrdering and `optimizeOrdering` member functions but they only check that a desired ordering does not include the ordinality column and updates the ordering from its source after `expand`, respectively)
- [`valueGenerator`](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/value_generator.go#L30-L40) for SRFs such as `unnest()` and `generate_series(...)` surprisingly [does not propagate `physicalProps` nor ordering information](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/plan_physical_props.go#L27) This is confirmed by the plan
```
root@:26257/foo> EXPLAIN (verbose) SELECT MIN(x) FROM (SELECT * FROM generate_series(10, 1) as x);
+-------+-----------+-------------+------------------------+------------+----------+
| Level |   Type    |    Field    |      Description       |  Columns   | Ordering |
+-------+-----------+-------------+------------------------+------------+----------+
|     0 | group     |             |                        | ("min(x)") |          |
|     0 |           | aggregate 0 | min(x)                 |            |          |
|     1 | filter    |             |                        | (x)        | x!=NULL  |
|     1 |           | filter      | x.x IS NOT NULL        |            |          |
|     2 | generator |             |                        | (x)        |          |
|     2 |           | expr        | generate_series(10, 1) |            |          |
+-------+-----------+-------------+------------------------+------------+----------+
(6 rows)

```

## Ordering during execution

Now in the local engine, since `groupNode` has one and only one child `planNode` and rows [are fetched serially](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/group.go#L370) the ordering should be preserved.

In DistSQL, inter-stream ordering is preserved by input synchronizers. This ordering is set after each processor is added [via `planner.SetMergeOrdering`](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/distsqlplan/physical_plan.go#L126-L132). 

For sort nodes, a `Sorter` processor is added whereby [`planner.AddNoGroupingStage` is invoked](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/distsql_physical_planner.go#L850-L860) (these are "local" processors/stages) which [sets the merge ordering](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/distsqlplan/physical_plan.go#L126-L132). 

Note however that after a local aggregation, we [do not propagate this `MergeOrdering`](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/distsql_physical_planner.go#L1236) from the previous processor (e.g. the `Sorter` processor). This is because `Aggregator` processors project columns down to the aggregated values and group keys, so columns in the ordering may be projected out. For example in
```
SELECT FIRST(x) FROM (SELECT x, y FROM xy ORDER BY y)
```
`y` is projected out. This is part of the reason why it's difficult to do local-final aggregation currently since `y` column is not propagated through the local aggregators and cannot be used in the input synchronizer of the final aggregator processor on the gateway node.

## Optimizing out sort nodes before aggregations

As we begin to develop a query optimizer, one optimization we can do with aggregations is to elide any immediate child sort nodes. For example
```
SELECT SUM(x) FROM (SELECT x FROM xy ORDER BY y)
```
is semantically the same as
```
SELECT SUM(x) FROM (SELECT x FROM xy)
```
where we elide the `sortNode` from the plan. However if we replace `SUM` with `FIRST` we obviously cannot elide the `sortNode`.

Intuitively we shouldn't elide the `sortNode` if the above query had `(MIN|MAX)(x) ... GROUP BY y (ASC|DESC)` and `y` was not indexed since we currently optimize this with a `LIMIT 1` clause. This is however an "unexpected" side-effect. In theory, it's better to elide the `sortNode` since sorting is O(nlogn) whereas a linear pass is O(n).

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20411)*

**Comment by knz** [comment]
LGTM but Radu please have a look too.

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20411#-:-L-JKUsaCqPKeUWRFdyZ:bnfp4nl)*

**Comment by richardwu** [comment]
So I realized we can't really do local-final aggregation in distsql. Given the counter example
```
SELECT FIRST(k) FROM (SELECT * FROM kv ORDER BY v)
```
This generates the [distsql plan](https://cockroachdb.github.io/distsqlplan/decode.html?eJzEk7FOwzAQhneeAt0EwkPttKXNFBakLhS13VAGE5-iiDaObAeBqrw7SjyURO2lFUEd7ct33x-fbg-5Vvgid2ghfAMODAQwCCBmUBidoLXa1CX_4UJ9QThikOVF6errmEGiDUK4B5e5LUIIG_m-xRVKhQYYKHQy2zbNC5PtpPmOPj6BwbJ04W3EWSQgrhjo0h06WidThJBX7HzrWhvXFUbi4TyTuMT0lKYGU-l0x_a8WK03dxG_P6kJTmoO3ctcG4UGVat5XA0aZNwKwq8yzx7rgPPsMQ01T3GVZ-yxDviMPab_WIsjmhXaQucWO-txvPOoXhtUKfods7o0Cb4anTQaf1w2XHOh0Dpf5f6wyH2pDvgb5iQsaFiQcNCCeRcO6NgjWj0m6QkNT0h4SsPTv_z0IwnPaPOMhOc0PL8odlzd_AQAAP___YFjyA==).

Note while one of the local `FIRST` is the correct logical `FIRST`, we have no way of guaranteeing that is the case after the final `FIRST`. We'd have to somehow propagate ordering information as well as the output columns required for the ordering.

This is rather difficult since we would need to introspect down from the `groupNode`
```
  0  group   ·            ·           ("first(k)")                    ·
  0  ·       aggregate 0  first(k)    ·                               ·
  1  render  ·            ·           (k)                             k!=NULL; key(k)
  1  ·       render 0     k           ·                               ·
  2  sort    ·            ·           (k, v, w[omitted], s[omitted])  k!=NULL; key(k); +v
  2  ·       order        +v          ·                               ·
  3  scan    ·            ·           (k, v, w[omitted], s[omitted])  k!=NULL; key(k)
  3  ·       table        kv@primary  ·                               ·
  3  ·       spans        ALL         ·                               ·
```
to tell the bottom nodes to render `v` and pass up the `+v` ordering info. I've removed the local-final agg for now and added a TODO.

**Comment by knz** [comment]
A quick question - why do you need a renderNode between the sort and the group?

**Comment by richardwu** [comment]
@knz I believe it was generated as part of the subquery clause.

**Comment by RaduBerinde** [comment]
That plan would work if we had an ordered synchronizer at the final stage, no?

**Comment by RaduBerinde** [comment]
@knz the renderNode is a projection, it removes the `v` which was needed by sort.

**Comment by RaduBerinde** [comment]
More importantly, I don't see how removing the local stage fixes the problem. We still need an ordered synchronizer at the final stage if we want to guarantee the first row in the ordering.

I would consider revisiting the semantics of this function.. How useful is the "first row" vs "arbitrary row"?
 Maybe having a `ANY` would be sufficient (is it sufficient for `DISTINCT ON`? I'm not sure what `DISTINCT ON` guarantees w.r.t which row it chooses)

**Comment by knz** [comment]
@RaduBerinde pg is pretty specific about the behavior. We don't get to choose here. Per https://www.postgresql.org/docs/9.0/static/sql-select.html#SQL-DISTINCT :

> DISTINCT ON ( expression [, ...] ) keeps only the first row of each set of rows where the given expressions evaluate to equal. The DISTINCT ON expressions are interpreted using the same rules as for ORDER BY (see above). Note that the "first row" of each set is unpredictable unless ORDER BY is used to ensure that the desired row appears first.

@richardwu let me take this opportunity to explain why this is important and why this FIRST function would be doing something different from the other aggregations.

The key idea here is that most relational operators are agnostic of the order of their input -- a filter doesn't care about the input order, a projection neither, etc, in particular *all aggregation functions* (except for FIRST) are independent from the input order. We use this property extensively in both logical plan optimizations and distsql physical planning to reorganize the query plan.

In fact, the SQL ORDER BY clause is not really part of relational algebra, and we must step outside of a number of algebraic properties (and step out of a number of optimizations) when taking user-specified ORDER BY clauses into account. Some true statements:

- the SQL standard indicates that ORDER BY is only semantically meaningful when used at the top level of a query. (In other words, the SQL standard allows a SQL engine to *ignore* ORDER BY -- and suggests to refuse it with an error -- anywhere else than the top-level SELECT). The idea behind this is that SQL only allows the user to control the order results are presented to the SQL client, but not the order in which the query processes rows internally.
- the SQL standard was able to specify this because all the SQL features defined by the standard *are agnostic of their row input order*, so an ORDER BY clause would not add anything semantically.
- **however, in contrast, pg and CockroachDB support non-standard SQL operators that are sensitive to the order of their input rows**: 
  - WITH ORDINALITY numbers its input in the specifier order -- ORDER BY is meaningful in the direct operand of WITH ORDINALITY
  - ARRAY() constructs an array in the specified order -- ORDER BY is meaningful in the direct operand of ARRAY()
  - DISTINCT ON is specified to return the "first row" -- so ORDER BY is meaningful in a SELECT DISTINCT ON clause

What's jarring / unfortunate with DISTINCT ON is that when combined with GROUP BY it operates on the result of aggregation, whereas the "first row" semantics of DISTINCT ON restrict the ordering of the aggregation *inputs* -- this is the first time we have this kind of restriction in CockroachDB.

There's no easy way out -- we must acknowledge that this is a new restriction, construct a logical plan that works, and audit the distsql physical planning code to ensure that the corresponding physical plans preserve order properly.

**Comment by richardwu** [comment]
@knz thanks for your insight: if I'm following correctly, I agree that respecting internal ordering will have to be "special cased" for `FIRST` (there is no actual special casing in implementation as of right now, but we'll have to be aware that there exist one aggregation that respects ordering in the future).

I think we should define the semantics of `FIRST` (disregarding `DISTINCT ON` for a moment) as the first value of the row of the source in the the `FROM` clause. Thus if the `FROM` clause has some explicit ordering (e.g. an `ORDER BY` in a subquery), we should respect that in `FIRST`. Otherwise, the source by SQL standards does not have any order guarantee and our definition of "first value of the row of the source" still holds.

Just to confirm (and correct me if I'm wrong): DistSQL will correctly synchronize the inputs (thus respecting the source's explicit ordering) if the aggregator only has a final stage. For example, a `Sorter` processor will set its `MergeOrdering` before a `FIRST` aggregation is added to the physical plan. I believe this should maintain the semantics we defined above.

**Comment by knz** [comment]
> I think we should define the semantics of FIRST (disregarding DISTINCT ON for a moment) as the first value of the row of the source in the the FROM clause. 

Yes -- although if there's a join or a union, all bets are off.

I think the proper approach is to enumerate explicitly the relational nodes for which we propose to guarantee that they preserve ordering if either: their source has a specified ORDER BY clause, or their source itself guarantees to preserve their own source order.

I think I'd be comfortable with:

- direct source (the direct descendent of the aggregation)
- projections (`renderNode`)
- filtering-only stages (currently `filterNode`)
- WITH ORDINALITY
- `unnest()` and perhaps SRFs in general

> Thus if the FROM clause has some explicit ordering (e.g. an ORDER BY in a subquery), we should respect that in FIRST. 

Not *anywhere* in a subquery however, see above.

**Comment by richardwu** [comment]
To follow up and recap on an offline discussion with @knz the other day, I'd like to document how and which source plan nodes preserve ordering with respect to `groupNode`.

## Ordering during planning

During the planning phase, ordering is propagated from children node [through `planPhysicalProps`](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/plan_physical_props.go#L27). The actual `physicalProps struct` contains [ordering information](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/physical_props.go#L138-L141) (this ordering information can also be reduced down into `physicalProps.constantCols` via `reduce()`).

Example of how `planPhysicalProps` is used for ordering: currently, `groupNode` [has a `desiredOrdering`](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/group.go#L323) which can be used to optimize `MIN` and `MAX` aggregations by adding a `LIMIT 1` if the ordering aligns (respective of the function of course). The optimization is [accomplished during `expandPlan`](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/expand_plan.go#L153-L168) by peeking into `planPhysicalProps` (as described above) of its child node.

To address @knz's proposition of nodes that preserve ordering, we can take a look at each node derives `planPhysicalProps`:
- `sortNode`s derive their [ordering directly from the ordering set in its clause]( https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/plan_physical_props.go#L73-L104)
- `renderNode`s [re-compute the ordering from its source](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/render.go#L683-L694) via [`physicalProps.project`](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/physical_props.go#L559-L580).
- `filterNode`s [delegate the ordering](https://github.com/cockroachdb/cockroach/blob/62d8ebf3f92bf18b007f5b106ec76b2797b5ec8f/pkg/sql/filter.go#L77-L80) to its child node (passthrough ordering)
- `ordinalityNode`s also derive ordering from [its source](https://github.com/cockroachdb/cockroach/blob/c9cc9eabb705cd3a52054af855f17085a2f36b01/pkg/sql/ordinality.go#L56) (note there are `restrictOrdering and `optimizeOrdering` member functions but they only check that a desired ordering does not include the ordinality column and updates the ordering from its source after `expand`, respectively)
- [`valueGenerator`](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/value_generator.go#L30-L40) for SRFs such as `unnest()` and `generate_series(...)` surprisingly [does not propagate `physicalProps` nor ordering information](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/plan_physical_props.go#L27) This is confirmed by the plan
```
root@:26257/foo> EXPLAIN (verbose) SELECT MIN(x) FROM (SELECT * FROM generate_series(10, 1) as x);
+-------+-----------+-------------+------------------------+------------+----------+
| Level |   Type    |    Field    |      Description       |  Columns   | Ordering |
+-------+-----------+-------------+------------------------+------------+----------+
|     0 | group     |             |                        | ("min(x)") |          |
|     0 |           | aggregate 0 | min(x)                 |            |          |
|     1 | filter    |             |                        | (x)        | x!=NULL  |
|     1 |           | filter      | x.x IS NOT NULL        |            |          |
|     2 | generator |             |                        | (x)        |          |
|     2 |           | expr        | generate_series(10, 1) |            |          |
+-------+-----------+-------------+------------------------+------------+----------+
(6 rows)

```

## Ordering during execution

Now in the local engine, since `groupNode` has one and only one child `planNode` and rows [are fetched serially](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/group.go#L370) the ordering should be preserved.

In DistSQL, inter-stream ordering is preserved by input synchronizers. This ordering is set after each processor is added [via `planner.SetMergeOrdering`](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/distsqlplan/physical_plan.go#L126-L132). 

For sort nodes, a `Sorter` processor is added whereby [`planner.AddNoGroupingStage` is invoked](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/distsql_physical_planner.go#L850-L860) (these are "local" processors/stages) which [sets the merge ordering](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/distsqlplan/physical_plan.go#L126-L132). 

Note however that after a local aggregation, we [do not propagate this `MergeOrdering`](https://github.com/cockroachdb/cockroach/blob/a21e518c2863a24b390a562f36e5e7f35c53f713/pkg/sql/distsql_physical_planner.go#L1236) from the previous processor (e.g. the `Sorter` processor). This is because `Aggregator` processors project columns down to the aggregated values and group keys, so columns in the ordering may be projected out. For example in
```
SELECT FIRST(x) FROM (SELECT x, y FROM xy ORDER BY y)
```
`y` is projected out. This is part of the reason why it's difficult to do local-final aggregation currently since `y` column is not propagated through the local aggregators and cannot be used in the input synchronizer of the final aggregator processor on the gateway node.

## Optimizing out sort nodes before aggregations

As we begin to develop a query optimizer, one optimization we can do with aggregations is to elide any immediate child sort nodes. For example
```
SELECT SUM(x) FROM (SELECT x FROM xy ORDER BY y)
```
is semantically the same as
```
SELECT SUM(x) FROM (SELECT x FROM xy)
```
where we elide the `sortNode` from the plan. However if we replace `SUM` with `FIRST` we obviously cannot elide the `sortNode`.

Intuitively we shouldn't elide the `sortNode` if the above query had `(MIN|MAX)(x) ... GROUP BY y (ASC|DESC)` and `y` was not indexed since we currently optimize this with a `LIMIT 1` clause. This is however an "unexpected" side-effect. In theory, it's better to elide the `sortNode` since sorting is O(nlogn) whereas a linear passthrough is O(n).

**Comment by knz** [comment]
Thank you for the detailed explanation. Please copy it to the top-level PR description and the commit message. Also add the appropriate release note to the commit message.

---

Reviewed 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 1369 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20411#-L-hbM65qAP4qr6Acm-Z:-L-hbM66mPmNKWgCaZzi:b1t35xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf8aaccc06c624bc174c763e5e72f6786581122/pkg/sql/distsql_physical_planner.go#L1369)):*
> ```Go
> 		}
> 		p.ResultTypes = finalOutTypes
> ```

this doesn't need to change in this PR.

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 496 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20411#-L-hbev9HXaWOzkpUqkM:-L-hbevAhVy2NlGe4rp3:b-jk5mxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf8aaccc06c624bc174c763e5e72f6786581122/pkg/sql/logictest/testdata/logic_test/aggregate#L496)):*
> ```
> 
> query I
> SELECT FIRST(v) FROM (SELECT * FROM kv ORDER BY v)
> ```

What is the plan for `SELECT FIRST(k) FROM (SELECT k FROM kv ORDER BY v)`? Can you test this? Verify the plan (and physical plan) is correct?

Salient properties:
- FIRST on a different column than ORDER BY
- the sub-query projection does not render the sort key
- the ORDER BY is on a non-indexed column so the sorting is mandatory

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20411#-:-L-hbzRr3OOJR8uDSqWQ:bdgbi54)*

**Comment by richardwu** [comment]
Done :+1: 

---

Review status: 5 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/aggregate, line 496 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20411#-L-hbev9HXaWOzkpUqkM:-L-hjVBva72oQfzpvNCE:b-5l6b87) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf8aaccc06c624bc174c763e5e72f6786581122/pkg/sql/logictest/testdata/logic_test/aggregate#L496)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What is the plan for `SELECT FIRST(k) FROM (SELECT k FROM kv ORDER BY v)`? Can you test this? Verify the plan (and physical plan) is correct?

Salient properties:
- FIRST on a different column than ORDER BY
- the sub-query projection does not render the sort key
- the ORDER BY is on a non-indexed column so the sorting is mandatory
</blockquote></details>

Hrm good point, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20411#-:-L-hl7dHUA4AAx9I5sR_:b-u10f03)*

**Comment by RaduBerinde** [comment]
Hm, I thought we would use the distinct node/processor for DISTINCT ON (#20463). Do we still want to add FIRST?

**Comment by richardwu** [comment]
I think @knz mentioned that it's useful in logic tests. There also seems to be some community demand for a `FIRST` aggregator (note that one of the answers suggest `DISTINCT ON`).

Since the `DISTINCT ON` implementation can do local and final aggregation in distsql, it begs the question whether or not we want to publicly introduce (or introduce at all) the `FIRST` aggregation function.

**Comment by knz** [comment]
:-1: to expose FIRST unless/until we have clear customer demand. It would introduce complexity in planning which I'd rather avoid.

**Comment by knz** [comment]
Discussed offline: OK on merging this PR if the built-in function is clearly marked as experimental (and thereby the discussion about user demand is delayed until later).

**Comment by RaduBerinde** [comment]
I wouldn't add this complexity without good reason.

**Pull request closed without merging**
