### PR TITLE
WIP: storage: Support scattering replicas in addition to leases

### LINKED ISSUE #23358: storage: SCATTER should have an option to randomize replicas
Both `ALTER TABLE tpcc.warehouse SCATTER` and `ALTER TABLE tpcc.warehouse SCATTER FROM (0) TO (5000)` do not seem to be doing anything. Specifically, `SHOW TESTING_RANGES FROM TABLE tpcc.warehouse` reveals the replicas are on the same ranges and the leaseholders do not appear to have moved. I haven't investigated further. Possibly user error.

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes https://github.com/cockroachdb/cockroach/issues/23358

Release note: TBD

This currently isn't a very satisfying experience. It doesn't scatter things as widely as I'd like, with a lot of replicas for a table still winding up on the same handful of nodes that they were predominantly on to begin with. It helps, as documented on https://github.com/cockroachdb/cockroach/issues/26059, especially if you run it multiple times and on all of your tables rather than just one, but needs to be better. I think that putting everything through the allocator logic, while necessary for respecting zone constraints, is hurting the variety of stores on which things end up.

Sending out as a WIP because I'm going to focus on improving the actual rebalancing logic as the first-order goal, with this being a less important addition to follow up on later. It still needs an option added to the SQL grammar so that it isn't used every time `SCATTER` is run.

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/scatter.go, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26438#-LEKh4XcAAzdRenD-hAt:-LEKh4XcAAzdRenD-hAu:bnmp4ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d56c10a211957110dd23a48cf5db4822cad073b/pkg/sql/scatter.go#L139)):*
> ```Go
> 		RequestHeader:   roachpb.RequestHeader{Key: n.run.span.Key, EndKey: n.run.span.EndKey},
> 		RandomizeLeases: true,
> 		// TODO: Require an additional option for this.
> ```

Why? I'd think that normally when you issue a scatter command you'd want both. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26438)*

**Comment by a-robinson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/scatter.go, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26438#-LEKh4XcAAzdRenD-hAt:-LEKjbhD6sNLuTIm6Qf-:b-yc2gvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d56c10a211957110dd23a48cf5db4822cad073b/pkg/sql/scatter.go#L139)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why? I'd think that normally when you issue a scatter command you'd want both. 
</blockquote></details>

Primarily because moving so many replicas is a lot more resource-intensive than just moving leases, and if anyone has made `SCATTER` a part of their workflow they could be in for quite a surprise when they run it after upgrading to 2.1.

Perhaps that's overly protective, though. I'm certainly open to leaving it like this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26438)*

**Comment by bdarnell** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/scatter.go, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26438#-LEKh4XcAAzdRenD-hAt:-LEKkGzP1VBqHWYJ6rni:b-cb0gio) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d56c10a211957110dd23a48cf5db4822cad073b/pkg/sql/scatter.go#L139)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Primarily because moving so many replicas is a lot more resource-intensive than just moving leases, and if anyone has made `SCATTER` a part of their workflow they could be in for quite a surprise when they run it after upgrading to 2.1.

Perhaps that's overly protective, though. I'm certainly open to leaving it like this.
</blockquote></details>

Yeah, it's more expensive, but I think that's what people generally want when they're calling this. We could have a separate lease-only option if there's concern about this, but I'm not sure if anyone would use it (check with Robert). 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26438)*

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/scatter.go, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26438#-LEKh4XcAAzdRenD-hAt:-LEMRxHz6BYX2gNBggEn:b1lalss) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d56c10a211957110dd23a48cf5db4822cad073b/pkg/sql/scatter.go#L139)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, it's more expensive, but I think that's what people generally want when they're calling this. We could have a separate lease-only option if there's concern about this, but I'm not sure if anyone would use it (check with Robert). 
</blockquote></details>

I'm ok with not adding an option for this. Prior to this PR `ALTER TABLE ... SCATTER` would move replicas if there was an imbalance (it looped until the replicate queue decided there was nothing to do). Yes, forcing replica rebalancing is a change in behavior, but I don't think it is drastic. One thing I'm interested in is how this affects stuff like `kv --splits=1000`. Does the forced rebalancing significantly slow down that operation? That might be an argument for having an `ALTER TABLE ... SCATTER LEASES`.

---

*[pkg/storage/replica_command.go, line 2121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26438#-LEMUROM0QefrRvv9P3j:-LEMUROM0QefrRvv9P3k:b-7t6kjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/67feca8deca8cca9793214f354690b82c2e8bf45/pkg/storage/replica_command.go#L2121)):*
> ```Go
> 		}
> 		numReplicas := int(zone.NumReplicas)
> 		replicasToAdd := rand.Intn(liveStores) + 1 - numReplicas
> ```

Rather than `liveStores`, don't you want to know how many candidate stores there are given the zone config constraints?

---

*[pkg/storage/replica_command.go, line 2126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26438#-LEMTUe04XvV4zFj0Kj8:-LEMTUe1EXcoEoUspkd5:b-xqu0l1) ([raw file](https://github.com/cockroachdb/cockroach/blob/67feca8deca8cca9793214f354690b82c2e8bf45/pkg/storage/replica_command.go#L2126)):*
> ```Go
> 		} else if replicasToAdd > numReplicas {
> 			replicasToAdd = numReplicas
> 		}
> ```

So you're adding up to N more replicas and then letting replicate queue chose which ones to remove. What is preventing replicate queue from removing the newly added replicas? Does this approach work well in practice? I don't have a better suggestion. The code could you a comment describing what it is doing.

---

*[pkg/storage/replica_command.go, line 2130 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26438#-LEMSwbJ5LeJmLHjkie0:-LEMSwbJ5LeJmLHjkie1:b-twwzwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/67feca8deca8cca9793214f354690b82c2e8bf45/pkg/storage/replica_command.go#L2130)):*
> ```Go
> 		var replicasAdded int
> 		for re := retry.StartWithCtx(ctx, retryOpts); re.Next() && replicasAdded < replicasToAdd; {
> 			requeue, err := rq.processOneChange(ctx, r, sysCfg, func() bool { return false } /* canTransferLease */, false /* dryRun */, true /* disableStatsBasedRebalancing */, true /* forceAddReplica */)
> ```

That's a lot of boolean arguments. I think you should change `processOneChange` to take an options struct. I see you've already added `replicateQueueOptions`, but it appears to be unused.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26438)*

**Comment by a-robinson** [comment]
I was using this while testing out load-based lease rebalancing and ran into a panic:

```
I180802 06:28:10.925661 3983220 storage/store.go:2551  [replicaGC,n1,s1,r7476/2:/Table/57/1/2{89/757…-90/115…}] removing replica
I180802 06:28:10.928514 3327671 util/mon/bytes_usage.go:592  [n1,client=10.142.0.36:46658,user=root] txn: bytes usage increases to 1.7 MiB (+1781760)
I180802 06:28:10.930257 3983220 storage/replica.go:842  [replicaGC,n1,s1,r7476/2:/Table/57/1/2{89/757…-90/115…}] removed 103972 (103965+7) keys in 4ms [clear=2ms commit=2ms]
E180802 06:28:10.931386 1768951 sql/conn_executor.go:657  [n1,client=127.0.0.1:48520,user=root] a SQL panic has occurred while executing "ALTER TABLE tpcc.public.stock SCATTER": context canceled
I180802 06:28:10.934749 3327671 util/mon/bytes_usage.go:592  [n1,client=10.142.0.36:46658,user=root] txn: bytes usage increases to 3.2 MiB (+3389440)
E180802 06:28:10.936822 1768951 util/log/crash_reporting.go:203  [n1,client=127.0.0.1:48520,user=root] a panic has occurred!
E180802 06:28:10.951230 1768951 util/log/crash_reporting.go:477  [n1,client=127.0.0.1:48520,user=root] Reported as error a1f4e80dd4e04ca699587d56f4eeb48d
panic: context canceled [recovered]
        panic: panic while executing 1 statements: ALTER TABLE _._._ SCATTER; caused by context canceled

goroutine 1768951 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc436288000, 0x2d41880, 0xc42ce7ce80, 0x278aa00, 0xc42a1002d0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:671 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc436288000, 0x2d41880, 0xc42ce7ce80)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:413 +0x61
panic(0x278aa00, 0xc42a1002d0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/kv.(*RangeIterator).Desc(0xc431f08640, 0x2d41940)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/range_iter.go:70 +0x6a
github.com/cockroachdb/cockroach/pkg/sql.(*scatterNode).Next(0xc42c1891a0, 0x2d41940, 0xc42a1ab680, 0xc4362884c0, 0xc436288430, 0xc421d74c01, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/scatter.go:164 +0xb4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).forEachRow(0xc436288000, 0x2d41940, 0xc42a1ab680, 0xc4362884c0, 0xc436288430, 0x2d335c0, 0xc42c1891a0, 0xc429492b28, 0x19c42c1, 0x2d41940)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:945 +0xb0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithLocalEngine(0xc436288000, 0x2d41940, 0xc42a1ab680, 0xc436288430, 0x3, 0x7fd4bf799350, 0xc428e28b40, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:887 +0x286
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc436288000, 0x2d41940, 0xc42a1ab680, 0x2d441c0, 0xc42ce7cf40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:802 +0xa8f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc436288000, 0x2d41940, 0xc42a1ab680, 0x2d441c0, 0xc42ce7cf40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:401 +0xb1e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc436288000, 0x2d41940, 0xc42a1ab680, 0x2d441c0, 0xc42ce7cf40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc436288000, 0x2d41880, 0xc42ce7ce80, 0xc4272c1220, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1078 +0x2055
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc42058cea0, 0x2d41880, 0xc42ce7ce80, 0x0, 0x0, 0xc462b11050, 0x4, 0xc462b1103d, 0xd, 0x2d22e40, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:415 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc42058cea0, 0x2d41880, 0xc42ce7ce80, 0xc450fa8a80, 0x5400, 0x15000, 0xc4208a4600, 0xc4272c1220, 0xc4272c11f0, 0xc43019a830, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:267 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:266 +0xf27
```

**Comment by bobvawter** [comment]
[CLA assistant check](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=26438) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=26438) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=26438) it.</sub>

**Pull request closed without merging**
