### PR TITLE
catalog: add more validation for primary key columns, add fix for encoding type

### LINKED ISSUE #97526: sql/catalog/tabledesc: encoding type validation can be too strict due to old bug
**Describe the problem**
In 21.1 and 20.2 (the first two versions to support `ALTER PRIMARY KEY`), we had a bug whereby the index automatically created in some cases to provide uniqueness for the old primary key would have its `EncodingType` field marked as `PrimaryIndexEncoding`. This behavior was fixed in https://github.com/cockroachdb/cockroach/pull/66599. This was not a problem until 22.2, when https://github.com/cockroachdb/cockroach/pull/86071 introduced more strict validation.

As soon as you upgrade, you'll hit issues using those tables; they fail validation.

**To Reproduce**

Go back to 21.1, alter the primary key of a table, upgrade up to 22.2.

**Expected behavior**
Everything works.

**Proposed solution**

Probably the easiest thing to do is to relax the validation such that it only kicks in after the 22.2 cluster version becomes active. Then, we ought to keep the precondition to make sure folks cannot cross the rubicon into 22.2 preventing downgrading.

A more complete fix would be to introduce a migration to fix the indexes. It's probably not much harder.

Jira issue: CRDB-24739

Epic CRDB-28665

### LINKED ISSUE #99561: ERROR: internal error: building declarative schema change targets for ALTER TABLE: failed to find column
**Describe the problem**

```
root@localhost:26257/encoderv2> alter table tasks drop column completed;
ERROR: internal error: building declarative schema change targets for ALTER TABLE: failed to find column
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:450: handleDropColumnCreateNewPrimaryIndex()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:432: handleDropColumnPrimaryIndexes()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:284: dropColumn()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:43: alterTableDropColumn()
GOROOT/src/reflect/value.go:584: call()
GOROOT/src/reflect/value.go:368: Call()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go:174: AlterTable()
GOROOT/src/reflect/value.go:584: call()
GOROOT/src/reflect/value.go:368: Call()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go:169: Process()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/build.go:62: Build()
github.com/cockroachdb/cockroach/pkg/sql/schema_change_plan_node.go:80: SchemaChange()
github.com/cockroachdb/cockroach/pkg/sql/opaque.go:56: buildOpaque()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/opaque.go:70: tryBuildOpaque()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:404: buildStmt()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:252: buildStmtAtRoot()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:226: Build()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:561: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:232: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1474: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1086: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:696: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2428: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1972: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1976: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1898: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:857: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728: func1()
GOROOT/src/runtime/asm_amd64.s:1594: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

Hi cockroachdb,

It started when I got a wierd error where cockroachdb state:

```
[2023-03-24 19:27:10] production.ERROR: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"tasks_completed_index\"
DETAIL:  Key (completed)=(true) already exists.
```

This is relevant schema:
```sql
CREATE TABLE public.tasks (
    id UUID NOT NULL,
    ...
    completed BOOL NOT NULL DEFAULT false,
    CONSTRAINT "primary" PRIMARY KEY (id ASC),
    ...
    UNIQUE INDEX tasks_id_key (id ASC),
    INDEX tasks_completed_index (completed ASC),
);
```

As you can see, `tasks_completed_index` is a non-unique index... After pulling most of my hair, I think something is wrong with the column `completed`, so I decide to drop all index related to `completed` column, then drop the `completed` column, then re-add the column and then re-add index. Luckily, when I attempt drop column, I got this error message error above.

**To Reproduce**
I try to reproduce it with newly install cockroachdb before (no luck), the light bulbs happen to me when I think the column on prod have gone corruption, I think I still have backup of this (if you want the back up to try drop column for yourself).

**Environment:**
 - CockroachDB version: `CockroachDB CCL v22.2.6 (x86_64-pc-linux-gnu, built 2023/03/03 19:31:13, go1.19.4)`
 - Server OS: `Ubuntu 22.04`
 - Client app: `cockroach sql`

I've try to get rid of `tasks_completed_index` and recreate index before (without drop `completed` column), it does solve problem for a brief moment but eventually I'll still have that error (unique index violation on non-unique column), only when I try get rid of the column itself, it manifest itself in this way.

Jira issue: CRDB-25934
Epic CRDB-28665

### LINKED ISSUE #105182: sql: table descriptor validator should ensure that all columns are in primary index key or store columns
A primary index should include every column in the table in either the `KeyColumnIDs` field or the `StoreColumnIDs` field (though I'm not sure this is true during schema migrations - is it?). It would be great if [`validateTableIndexes`](https://github.com/cockroachdb/cockroach/blob/c94698a190622e706dfce7c0b1475f04d31dafe9/pkg/sql/catalog/tabledesc/validate.go#L1278) guaranteed this invariant.

Jira issue: CRDB-28914

Epic CRDB-28665

### PR DESCRIPTION
**Pull request by rafiss**
### catalog: add more validation for primary key columns

This adds tests for existing validation that covers the primary index, and also adds three new checks:
- Primary index should have the correct encoding type, as well as secondary indexes that are not a mutation.
- Virtual columns must not be stored in the primary index.
- All other public columns must be in the primary index key or store columns.

This revealed a bug in the crdb_internal.generate_test_objects builtin
function (only used internally), so that is fixed in this patch as well.

fixes https://github.com/cockroachdb/cockroach/issues/105182

Release note: None

---

###  catalog: add a PostDeserializationChange for fixing secondary index encoding type

fixes https://github.com/cockroachdb/cockroach/issues/97526
fixes https://github.com/cockroachdb/cockroach/issues/99561

Release note (bug fix): Fixed a bug where some secondary indexes would
incorrectly be treated internally as ~secondary~ primary indexes, which could cause
some schema change operations to fail. The bug could occur if ALTER
PRIMARY KEY was used on v21.1 or earlier, and the cluster was upgraded.

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105828)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/sql/catalog/tabledesc/structured_test.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105828#-NZkwx3i-QnQJER0gwjf:-NZkwx3i-QnQJER0gwjg:bkloq4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1137aee0089fc2fe161bab0f1c899d2ddc997c90/pkg/sql/catalog/tabledesc/structured_test.go#L86)):*
> ```Go
> 			func() descpb.IndexDescriptor {
> 				idx := makeIndexDescriptor("f", []string{"c"})
> 				idx.EncodingType = catenumpb.PrimaryIndexEncoding
> ```

this secondary index with the incorrect encoding was intentionally added in https://github.com/cockroachdb/cockroach/pull/44808

i am fairly sure we don't want it any more, but would appreciate any additional background knowledge on why it was added before.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105828)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @postamar, and @rafiss)

___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 1017 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105828#-NZl1VzmBv8192KUpUgr:-NZl1VzmBv8192KUpUgs:b-yloncc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece0dd3fedab07cba6682ecc60c1b5b1d108ce87/pkg/sql/catalog/tabledesc/table_desc_builder.go#L1017)):*
> ```Go
> 	for i := range desc.Indexes {
> 		idx := &desc.Indexes[i]
> 		// HELP NEEDED: Since 12dec73c593, it seems like we expect primary
> ```

Ah that makes sense because during an add column or index swap we will have temporary indexes with that encoding. 

I think the short circuit is sufficient that you have above. Another option would be to look at mutation information, but it's overkill.

**Review by fqazi — APPROVED** [review]
:lgtm: Thanks for doing this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105828#-:-NZl2zjB4HTMMOL38WNN:b-pt8m11)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @postamar, and @rafiss)

___
*[`pkg/sql/catalog/tabledesc/validate_test.go` line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105828#-NZl2qztD2eSFCxQvRnT:-NZl2qztD2eSFCxQvRnU:bo6eoar) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece0dd3fedab07cba6682ecc60c1b5b1d108ce87/pkg/sql/catalog/tabledesc/validate_test.go#L158)):*
> ```Go
> 			"InvertedColumnKinds": {status: thisFieldReferencesNoObjects},
> 			"KeyColumnIDs":        {status: iSolemnlySwearThisFieldIsValidated},
> 			"KeySuffixColumnIDs":  {status: iSolemnlySwearThisFieldIsValidated},
> ```

Nice 🙂

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105828)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi, @postamar, and @rafiss)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105828#-NZl05R8BKuIUVhQfy-2):*
`internally as secondary indexes` -> `internally as primary indexes`
___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 1017 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105828#-NZl1VzmBv8192KUpUgr:-NZl4-QT5QZ08bSBX298:blu8wtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece0dd3fedab07cba6682ecc60c1b5b1d108ce87/pkg/sql/catalog/tabledesc/table_desc_builder.go#L1017)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Ah that makes sense because during an add column or index swap we will have temporary indexes with that encoding. 

I think the short circuit is sufficient that you have above. Another option would be to look at mutation information, but it's overkill.
</blockquote></details>

yeah, for declarative schema changer the short circuit above is good. For legacy schema changer, I forgot what's the encoding type we put when creating the primary key swap mutation... need to double check

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 1017 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105828#-NZl1VzmBv8192KUpUgr:-NZlAcxS3b_f-l7xvxIZ:b-yjsh6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece0dd3fedab07cba6682ecc60c1b5b1d108ce87/pkg/sql/catalog/tabledesc/table_desc_builder.go#L1017)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

yeah, for declarative schema changer the short circuit above is good. For legacy schema changer, I forgot what's the encoding type we put when creating the primary key swap mutation... need to double check
</blockquote></details>

So in the legacy schema changer, alter primary key would just create the candidate primary index (not primary yet before swapping) with [primary index encoding](https://github.com/cockroachdb/cockroach/blob/818aec861357579eb3a3e987cf5887f3cf112be4/pkg/sql/alter_primary_key.go#L184-L184). We could check if there is a `PrimaryKeySwap` mutation going on with the same new index id.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105828)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @postamar, and @rafiss)

___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 1017 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105828#-NZl1VzmBv8192KUpUgr:-NZlBgxD0sOh5N5xq-23:buqkg74) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece0dd3fedab07cba6682ecc60c1b5b1d108ce87/pkg/sql/catalog/tabledesc/table_desc_builder.go#L1017)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

So in the legacy schema changer, alter primary key would just create the candidate primary index (not primary yet before swapping) with [primary index encoding](https://github.com/cockroachdb/cockroach/blob/818aec861357579eb3a3e987cf5887f3cf112be4/pkg/sql/alter_primary_key.go#L184-L184). We could check if there is a `PrimaryKeySwap` mutation going on with the same new index id. 
</blockquote></details>

Yeah, I think we'll need that or just skip on mutatuons

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105828)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi and @postamar)

___
*[`pkg/sql/catalog/tabledesc/table_desc_builder.go` line 1017 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105828#-NZl1VzmBv8192KUpUgr:-NZlOE7MD6iJzP1zPFJs:b6hvwhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece0dd3fedab07cba6682ecc60c1b5b1d108ce87/pkg/sql/catalog/tabledesc/table_desc_builder.go#L1017)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yeah, I think we'll need that or just skip on mutatuons
</blockquote></details>

thanks for checking! ok i'll just make it skip if `len(mutations) > 0`

the other thing we're going to have to reason about is how these checks should change when we backport to 23.1 and 22.2

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105828)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @fqazi, and @postamar)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105828#-NZl05R8BKuIUVhQfy-2):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

`internally as secondary indexes` -> `internally as primary indexes`
</blockquote></details>

done

**Comment by rafiss** [comment]
tftrs!

bors r=fqazi,chengxiong-ruan

**Pull request merged**
