### PR TITLE
sql: add kv nodes to makeDeterministic method

### LINKED ISSUE #124909: pkg/sql/opt/exec/execbuilder/tests/5node/5node_test: TestExecBuild_distsql_misc failed
pkg/sql/opt/exec/execbuilder/tests/5node/5node_test.TestExecBuild_distsql_misc [failed](https://tanzanite.cluster.engflow.com/invocations/default/c1b19418-d0ed-4aa2-8652-0fd3e0a14e2f?testReportRun=1&testReportShard=12&testReportAttempt=1#targets-Ly9wa2cvc3FsL29wdC9leGVjL2V4ZWNidWlsZGVyL3Rlc3RzLzVub2RlOjVub2RlX3Rlc3Q=) on master @ [64bd4bbac8f8d27a2fe4968404cc3d048480375f](https://github.com/cockroachdb/cockroach/commits/64bd4bbac8f8d27a2fe4968404cc3d048480375f):

```
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestExecBuild_distsql_misc3035815738
    test_log_scope.go:81: use -show-logs to present logs inline
    logic.go:4308: -- test log scope end --
test logs left over in: outputs.zip/logTestExecBuild_distsql_misc3035815738
--- FAIL: TestExecBuild_distsql_misc (16.18s)
=== RUN   TestExecBuild_distsql_misc/stats
    logic.go:2968: 
         
        /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/opt/exec/execbuilder/tests/5node/5node_test_/5node_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc:102: EXPLAIN ANALYZE (DISTSQL) CREATE STATISTICS s1 ON a FROM data
        expected:
            planning time: 10µs
            execution time: 100µs
            distribution: <hidden>
            vectorized: <hidden>
            rows decoded from KV: 1,000 (7.8 KiB, 2,000 KVs, 1,000 gRPC calls)
            maximum memory usage: <hidden>
            network usage: <hidden>
            regions: <hidden>
            isolation level: serializable
            priority: normal
            quality of service: regular
            ·
            • create statistics
            ·
            Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJzsllFvm0gQx9_vU4zmpa2EAwvYcfapOTfVWZXjyKCeTqeo2sDURcYst7sozUX-WPcF7pOdgHKxqXFNKkt9qB-Qd3eY-f-Z3672EfVfKXKcLK4uwysIwstwGoTTSQCawfwaBLxdzGcQCyPg92n4G8xvwun8OoDLAOZvIfgjCK9mEE5nV_BiwAr9Ai3MZEzXYk0a-Z_I0EIXLfTQQh8tHOKthbmSEWktVRnyWL0wjT8jdyxMsrww5fSthZFUhPwRTWJSQo6huEtpQSImZTtoYUxGJGlVphT4unx8yFf0gBZOZFqsM81BoIVBLsq_A5uByGJgIM0nUmjhu_dQFtccMlYPTbImDs6__-h6HMnMUGYSmX21pOS9hpgiGVPMgTlOPX33YEiDIhFzGDsO_FpPLxc3E4hEmuqt2Fwkqol1q8nZ-8kEtKEcIllkBl7SZ2MnmXnFwbGfAohWXQGVLFmYvDB1pduNhfX4y3fVRiwJOdtqxPQNcmdjHd-LQKzzlJQ93O1DPR0kf1NVu7IUGGE4vGadQtyWkGGnkKf6RSZVTIrinfq3m06pl8uloqUwUtnMOV40vHQdB-6KaEVGv-q04LUssN2PyY4Hmz0DbJsNbLcbbfc70Xb3oc3ORvAu2QO3uw9u_xRwuz3gZn360cA9OgHcox0h7vFguM8Bwx3YXjcY3k8wuNunHw0Y5ycA43xHiHc8GN5zwPAGtt8Nhv8TDO716UcDxvgEYIx3hPjHg-E_Bwx_YA-7wRh-JxjePjDcM28_GN4-MEanAMPrAYbfpx8NGBcnAOOiz4VtQTqXmabWfWl_JadVacDKixXFS6pvYVoWKqIbJaMqth7Oq0TVREza1KusHkyzZkkbRWL9_31zOxM7mMndycS2Mw3bmdzDmvqI8g6m8rszsXYmv689UXUFMzL3Uq3qnaQpq86x8prYLNR7qV55OmSb1TVpLZZPASXp2zpHbZ3DgzpH3Y7ddqbRj-n4vK3z_KDOcbdjr51p_GM6Hrd1XhzeIE63Zf-rXXv4AOjl2ev07J753_A8bHm-KI-sj6m8_5DEyNH58hvseTQ_LF8QS12em8EneV-JDh_y8tT7KFJNFs7Eit6QIbVOskSbJEJuVEGbzS__BQAA__9hInyF
            
        but found (query options: "") :
            planning time: 10µs
            execution time: 100µs
            distribution: <hidden>
            vectorized: <hidden>
            rows decoded from KV: 1,000 (7.8 KiB, 2,000 KVs, 1,000 gRPC calls)
            maximum memory usage: <hidden>
            network usage: <hidden>
            regions: <hidden>
            isolation level: serializable
            priority: normal
            quality of service: regular
            ·
            • create statistics
            ·
            Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJzsllFvm0gQx9_vU4zmpa2EAwvYcfapOTfVWZXjyKCeTqeo2sDURcYst7sozUX-WPcF7pOdgHKxqXFNKkt9qB9QdneY-f-Z3272EfVfKXKcLK4uwysIwstwGoTTSQCawfwaBLxdzGcQCyPg92n4G8xvwun8OoDLAOZvIfgjCK9mEE5nV_BiwAr9Ai3MZEzXYk0a-Z_I0EIXLfTQQh8tHOKthbmSEWktVRnyWL0wjT8jdyxMsrww5fSthZFUhPwRTWJSQo6huEtpQSImZTtoYUxGJGlVphT4unx8yFf0gBZOZFqsM81BoIVBLso_BzYDkcXAQJpPpNDCd--hLK45ZKwemmRNHJx__9H1OJKZocwkMvtqScl7DTFFMqaYA3OcevruwZAGRSLmMHYc-LWeXi5uJhCJNNVbsblIVBPrVpOz95MJaEM5RLLIDLykz8ZOMvOKg2M_BRCtugIqWbIweWHqSrcbC-vxl--qjVgScrbViOkb5M7GOr4XgVjnKSl7uNuHejpI_qaqdmUpMMJweM06hbgtIcNOIU_1i0yqmBTFO_VvN51SL5dLRUthpLKZc7xoeOk6DtwV0YqMftVpwWtZYLsfkx0PNnsG2DYb2G432u53ou3uQ5udjeBdsgdudx_c_ingdnvAzfr0o4F7dAK4RztC3OPBcJ8DhjuwvW4wvJ9gcLdPPxowzk8AxvmOEO94MLzngOENbP_AP0MLMv8nHNzr05MGjvEJ4BjvCPGPh8N_Dhz-wB52wzH8TjC8fWC4Z95-MLx9YIxOAYbXAwy_Tz8aMC5OAMZFn0vbgnQuM02tO9P-Sk6r0oCVlyuKl1TfxLQsVEQ3SkZVbD2cV4mqiZi0qVdZPZhmzZI2isT6_zvndiZ2MJO7k4ltZxq2M7mHNfUR5R1M5XdnYu1Mfl97ouoKZmTupVrVO0lTVp1j5VWxWaj3Ur3ydMg2q2vSWiyfAkrSt3WO2jqHB3WOuh277UyjH9PxeVvn-UGd427HXjvT-Md0PG7rvDi8QZxuy_5Xu_bwAdDLs9fp2T3zv-F52PJ8UR5ZH1N5_yGJkaPz5TfY82h-WL4glro8N4NP8r4SHT7k5an3UaSaLJyJFb0hQ2qdZIk2SYTcqII2m1_-CwAA___stn1w
            
[09:46:42] --- progress: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/opt/exec/execbuilder/tests/5node/5node_test_/5node_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc: 7 statements
    logic.go:2205: 
         /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/opt/exec/execbuilder/tests/5node/5node_test_/5node_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc:121: too many errors encountered, skipping the rest of the input
[09:46:42] --- done: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/sql/opt/exec/execbuilder/tests/5node/5node_test_/5node_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc with config 5node: 7 tests, 2 failures
[09:46:46] --- total progress: 7 statements
--- total: 7 tests, 2 failures
    --- FAIL: TestExecBuild_distsql_misc/stats (2.11s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=12</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestExecBuild_distsql_misc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-39147

### PR DESCRIPTION
**Pull request by DrewKimball**
This patch adds `KVStats.NodeIDs` to `ComponentStats.MakeDeterministic` in order to prevent test flakes.

Fixes #124909

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Thanks for the patch! I actually somewhat deliberately omitted this from my PR since I couldn't quite understand why we'd have non-deterministic node IDs (both for SQL and KV) in the logic tests (since we shouldn't be using EXPLAIN ANALYZE in `fakedist*` configs). I'll probably look into adjusting a handful of tests that currently have non-deterministic physical planning so that node IDs are always deterministic, but for now your patch makes sense.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124950#-:-NzTrYBw8kHzS6g4B7zr:bp41azm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rytaft)

___
*[`pkg/sql/execinfrapb/component_stats.go` line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124950#-NzTrGdjCST5XS7MNjXD:-NzTrGdkAoNFnpdJouSO:b-kmacki) ([raw file](https://github.com/cockroachdb/cockroach/blob/eafd6936217edc17554e7a090d457b39e6aae934/pkg/sql/execinfrapb/component_stats.go#L447)):*
> ```Go
> 	resetUint(&s.KV.RangeKeyContainedPoints)
> 	resetUint(&s.KV.RangeKeySkippedPoints)
> 	s.KV.NodeIDs = nil
> ```

Rather than setting this to `nil`, we should set it to a constant list, i.e. something like:
```
s.KV.NodeIDs = []int32{1}
```
This is because the contract of the method is such that it shouldn't modify whether a particular exec stat is set.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124950)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`pkg/sql/execinfrapb/component_stats.go` line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124950#-NzTrGdjCST5XS7MNjXD:-NzUrosx0NMXAlKAupUm:by258u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/eafd6936217edc17554e7a090d457b39e6aae934/pkg/sql/execinfrapb/component_stats.go#L447)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Rather than setting this to `nil`, we should set it to a constant list, i.e. something like:
```
s.KV.NodeIDs = []int32{1}
```
This is because the contract of the method is such that it shouldn't modify whether a particular exec stat is set.
</blockquote></details>

Done. I also wrapped it in a check that `len(s.KV.NodeIDs) > 0`.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124950#-:-NzVWEtoDYDRNaEQHelF:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Pull request merged**
