### PR TITLE
ui: update eslint rules for `db-console` and `cluster-ui` to follow the same code styles as CC Console

### PR DESCRIPTION
**Pull request by koorosh**
It is recommended to review changes per commit. 
My apologies for enormous list of changes in a single PR, but I didn't find a better way 
how to split those changes in smaller parts and don't break other places in code. Appreciate
any suggestions which might make code review easier!

- This change applies the same eslint rules as defined in
CC Console to have the same code styles across the projects.
- Most of the changes just move code around (order of imports), or fixes types.
- Also there's some code changes that refactor code to not use `_.chain` function
and proposes alternative solutions.
- As an exception, `no-console` rule is disabled for existing code which uses `console`
to preserve existing logic but prevent farther usage of `console`.
- Updated dependencies for `eslint` related packages to follow the same version as CC Console.

Epic: https://cockroachlabs.atlassian.net/browse/CC-26102

Release note: None

### CODE REVIEW

**Review by laurenbarker — COMMENTED** [review]
This is awesome! I'm curious if all the lodash import changes make our bundle smaller :smile: I asked a couple small things, but this LGTM overall!

> Reviewed 6 of 6 files at r1, 353 of 353 files at r2, 131 of 131 files at r3, 5 of 5 files at r4, 14 of 14 files at r5, 249 of 249 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-:-NzAP13H2kc_zyABip4_:b-8p0mkv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @kyle-a-wong)

___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA1lbqASN75uAlXTg_:-NzA1lbqASN75uAlXTga:bu720jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L4)):*
> ```jsonc
>   "root": true,
>   "extends": [
>     "@cockroachlabs/eslint-config",
> ```

Can you add a ticket to the console separation epic to update the shared eslint config to contain all these rules? That way we won't have to update them in multiple places.
___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA0VQ86T6nrdZsc1wt:-NzA0VQ86T6nrdZsc1wu:b-ynfr9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L58)):*
> ```jsonc
>           {
>             // Webpack aliases look like external imports, so we need to explicitly mark them as internal.
>             "pattern": "{Store,Style,Typings}/**",
> ```

These will be specific to the repo since they're aliases added in the webpack config. Are any of these used in cluster-ui webpack config? It doesn't look like it.
___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA0mla5GH89DUuCwzu:-NzA0mla5GH89DUuCwzv:b-u3h11l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L62)):*
> ```jsonc
>           }
>         ],
>         "pathGroupsExcludedImportTypes": [
> ```

Same for these.
___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA1awK2dXsWOAf5KwL:-NzA1awK2dXsWOAf5KwM:b-iwyrr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L92)):*
> ```jsonc
>       }
>     ],
>     "no-restricted-syntax": [
> ```

We may not want this rule. I don't think the skip helpers are setup in this repo.
___
*[`pkg/ui/workspaces/cluster-ui/build/eslint/restrict-compound-components.js` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA2JKo7F3CyEIEIh4_:-NzA2JKo7F3CyEIEIh4a:bsbt7t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/build/eslint/restrict-compound-components.js#L2)):*
> ```JavaScript
> /**
>  * @fileoverview Restrict direct child elements of compound components.
> ```

This eslint rule should also be included in the shared config package. Can you mention it in the ticket you create to update the shared config (mentioned in another comment).
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsTable.tsx` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA4LxmAPsjG2bL5So-:-NzA4LxmAPsjG2bL5So0:b-8tfcei) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ec1887b51afcf5a78bd2a33fb2608f62843ad6d/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsTable.tsx#L28)):*
> ```XML
> } from "src/insights";
> import { Link } from "react-router-dom";
> import { Badge } from "src/badge";
> ```

Hm, it's treating imports from `src/` as a third-party input for some reason. I'm a little surprised these imports aren't causing issues, but that's how they were before. We definitely don't need to change them as part of this PR, but we may want to update them to use a webpack alias in the future.
___
*[`pkg/ui/workspaces/db-console/src/util/api.ts` line 447 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzAODZP7Yyd_8IaYYkE:-NzAODZP7Yyd_8IaYYkF:b-afuayk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68b988deab66a1511e23b767d2125079a2e3a7e/pkg/ui/workspaces/db-console/src/util/api.ts#L447)):*
> ```XML
>     (err: Error) => {
>       if (err instanceof TimeoutError) {
>         console.log(
> ```

Why was this changed from `error` to `log`?
___
*[`pkg/ui/workspaces/cluster-ui/src/api/safesql.spec.ts` line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA9bVH4-fQD5piTcfk:-NzA9bVH4-fQD5piTcfl:bqe7rlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/301a8418a0fd024c31231f14eb186d0aca5e56fa/pkg/ui/workspaces/cluster-ui/src/api/safesql.spec.ts#L104)):*
> ```XML
>       {
>         format: `hello %1`,
>         args: [new Date() as any],
> ```

Looks like you added an `any` here? Was there an issue?

**Review by koorosh — COMMENTED** [review]
@laurenbarker thanks for review! One more thing that should also be done is to mirror deps (as new versions are specified in this PR) with a command:
```bash
dev ui mirror-deps
```
Appreciate if you could help me with this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-:-NzD_Vt817eOlxTByO7l:b-rbf9hy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @laurenbarker)

___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA1lbqASN75uAlXTg_:-NzD7650Ede5Oasa-fHD:b-76qt45) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L4)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Can you add a ticket to the console separation epic to update the shared eslint config to contain all these rules? That way we won't have to update them in multiple places.
</blockquote></details>

Done. https://cockroachlabs.atlassian.net/browse/CC-28589
___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA0VQ86T6nrdZsc1wt:-NzDLBNK6LDu_DJcmauF:bw6duj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L58)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

These will be specific to the repo since they're aliases added in the webpack config. Are any of these used in cluster-ui webpack config? It doesn't look like it.
</blockquote></details>

Right, `cluster-ui` has only `src` alias defined in Webpack so I adjusted this pattern to include it. 
___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA0mla5GH89DUuCwzu:-NzDOtpY2bESPoFuLKxx:b-30oyx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L62)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Same for these.
</blockquote></details>

Done. removed for both `cluste-ui` and `db-console`
___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA1awK2dXsWOAf5KwL:-NzDPGa32TIXW4E2La79:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L92)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

We may not want this rule. I don't think the skip helpers are setup in this repo.
</blockquote></details>

Done. 
___
*[`pkg/ui/workspaces/cluster-ui/build/eslint/restrict-compound-components.js` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA2JKo7F3CyEIEIh4_:-NzDPk2n5gGrokDODfKa:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/build/eslint/restrict-compound-components.js#L2)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

This eslint rule should also be included in the shared config package. Can you mention it in the ticket you create to update the shared config (mentioned in another comment).
</blockquote></details>

Ack.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsTable.tsx` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA4LxmAPsjG2bL5So-:-NzDYMWH3PLoDigZ5_lW:b-bku385) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ec1887b51afcf5a78bd2a33fb2608f62843ad6d/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsTable.tsx#L28)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Hm, it's treating imports from `src/` as a third-party input for some reason. I'm a little surprised these imports aren't causing issues, but that's how they were before. We definitely don't need to change them as part of this PR, but we may want to update them to use a webpack alias in the future.
</blockquote></details>

Done. Grouped `src/` paths as "internal" group. `lint:fix` managed to do this with no efforts after `pathGroups` was properly specified to handle `src` paths as internal ones.
___
*[`pkg/ui/workspaces/db-console/src/util/api.ts` line 447 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzAODZP7Yyd_8IaYYkE:-NzDYndp6FtS1CO58bYl:b-n0n2wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68b988deab66a1511e23b767d2125079a2e3a7e/pkg/ui/workspaces/db-console/src/util/api.ts#L447)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Why was this changed from `error` to `log`?
</blockquote></details>

My mistake, had to revert this change. Fixed.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/safesql.spec.ts` line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA9bVH4-fQD5piTcfk:-NzDZscc9t8MZp7X-feI:bsd37yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/301a8418a0fd024c31231f14eb186d0aca5e56fa/pkg/ui/workspaces/cluster-ui/src/api/safesql.spec.ts#L104)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Looks like you added an `any` here? Was there an issue?
</blockquote></details>

This should be done because of proper type handling for `Format` function's args. It is not possible to directly pass a wrong type as this specific test tries to do.

**Comment by laurenbarker** [comment]
Checked it out and ran mirror-deps :thumbsup:

**Review by laurenbarker — APPROVED** [review]
Small thing with assets potentially being an alias too, but other than that, this LGTM!

> Reviewed 469 of 469 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-:-NzEJzDG9IhkfOjM9PiL:b89y7vs)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @kyle-a-wong)

___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA1lbqASN75uAlXTg_:-NzEJj155SqHjGzs04Cx:b-9755fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L4)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Done. https://cockroachlabs.atlassian.net/browse/CC-28589
</blockquote></details>

Thank you!
___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA0VQ86T6nrdZsc1wt:-NzEHcYa8kyx4bU6A0Lu:btr1s1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43515014bbcca2cf9bafc36de8788433f684cf3/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L58)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Right, `cluster-ui` has only `src` alias defined in Webpack so I adjusted this pattern to include it.
</blockquote></details>

Oh perfect, thanks!
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsTable.tsx` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzA4LxmAPsjG2bL5So-:-NzEJoa_3LTsDFJgY37c:b-op5a18) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ec1887b51afcf5a78bd2a33fb2608f62843ad6d/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsTable.tsx#L28)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Done. Grouped `src/` paths as "internal" group. `lint:fix` managed to do this with no efforts after `pathGroups` was properly specified to handle `src` paths as internal ones.
</blockquote></details>

Lovely! It looks like `assets` may be an alias too (I mentioned that in another comment).
___
*[`pkg/ui/workspaces/db-console/ccl/src/views/clusterviz/components/instructionsBox/index.tsx` line 14 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/124859#-NzEIeon5HF0G96vMdMO:-NzEIeon5HF0G96vMdMP:b-1me9f3) ([raw file](https://github.com/cockroachdb/cockroach/blob/126da925e0b04bd4d511af45ca5dfe9a0e275918/pkg/ui/workspaces/db-console/ccl/src/views/clusterviz/components/instructionsBox/index.tsx#L14)):*
> ```XML
> import classNames from "classnames";
> import nodeMapScreenshot from "assets/nodeMapSteps/3-seeMap.png";
> import questionMap from "assets/questionMap.svg";
> ```

It looks like `assets` may be an alias too.

**Pull request merged**
