### PR TITLE
sql: wire up the ported index constraints code

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: replace placeholders with values

If we have value for placeholders, replace them with their values
during build.

Release note: None

#### opt: prefer short cast syntax

We are building CastExpr using the explicit syntax. This causes some
churn in some distsql tests when the new index constraints code is on.
Switching to the short syntax.

Release note: None

#### sql: wire up the ported index constraints code

The new index constraints code was ported to the new optimizer
structures (in `opt/idxconstraint`). This change rewires sql to use
that.

Planning benchmark differences below. Note that we will be looking at
improving the performance before 2.1 ships.

```
name                                                             old time/op    new time/op    delta
Planning/SELECT_*_FROM_abc-8                                        265µs ± 3%     266µs ± 3%     ~     (p=0.886 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_a_>_5_ORDER_BY_a-8                 200µs ± 1%     214µs ± 1%   +6.88%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_b_=_5-8                            196µs ± 2%     213µs ± 5%   +8.59%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_b_=_5_ORDER_BY_a-8                 211µs ± 4%     225µs ± 2%   +6.54%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_c_=_5-8                            195µs ± 3%     209µs ± 4%   +6.85%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_JOIN_abc_AS_abc2_ON_abc.a_=_abc2.a-8     459µs ± 4%     435µs ± 4%     ~     (p=0.057 n=4+4)

name                                                             old alloc/op   new alloc/op   delta
Planning/SELECT_*_FROM_abc-8                                       33.8kB ± 2%    33.8kB ± 2%     ~     (p=1.000 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_a_>_5_ORDER_BY_a-8                23.4kB ± 2%    27.1kB ± 1%  +15.86%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_b_=_5-8                           25.1kB ± 1%    28.9kB ± 2%  +15.26%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_b_=_5_ORDER_BY_a-8                26.2kB ± 3%    29.7kB ± 0%  +13.19%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_c_=_5-8                           24.9kB ± 0%    28.7kB ± 1%  +15.48%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_JOIN_abc_AS_abc2_ON_abc.a_=_abc2.a-8    70.0kB ± 2%    69.6kB ± 0%     ~     (p=0.886 n=4+4)

name                                                             old allocs/op  new allocs/op  delta
Planning/SELECT_*_FROM_abc-8                                          354 ± 0%       354 ± 0%     ~     (p=1.000 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_a_>_5_ORDER_BY_a-8                   328 ± 0%       372 ± 0%  +13.41%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_b_=_5-8                              320 ± 0%       364 ± 0%  +13.74%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_b_=_5_ORDER_BY_a-8                   360 ± 0%       404 ± 0%  +12.14%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_WHERE_c_=_5-8                              317 ± 0%       361 ± 0%  +13.96%  (p=0.029 n=4+4)
Planning/SELECT_*_FROM_abc_JOIN_abc_AS_abc2_ON_abc.a_=_abc2.a-8       649 ± 0%       648 ± 0%     ~     (p=0.429 n=4+4)
```

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
First two commits LGTM modulo resolution of my worry for the 2nd one. 

I don't fully understand the 3rd commit: is that the new default path for all queries?

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/optbuilder/scalar.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236#-L6Sz6z3KiRNZaz99DOY:-L6Sz6z3KiRNZaz99DOZ:b-i830k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c630a15e6b081f92a6974984e05cdf1ee9e3785/pkg/sql/opt/optbuilder/scalar.go#L176)):*
> ```Go
> 			}
> 			if _, ok := d.(*tree.Placeholder); ok {
> 				panic(errorf("no placeholder value"))
> ```

this case seems impossible. `(*Placeholder).Eval()` never returns the original placeholder. Or did you only mean it as an assertion? Then maybe use `programming error` in the error text.

---

*[pkg/sql/sem/tree/expr.go, line 1262 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236#-L6SzUJfo3I2lwtkOqEC:-L6SzUJfo3I2lwtkOqED:b-60bkov) ([raw file](https://github.com/cockroachdb/cockroach/blob/b66dc20e7db95161f6028844ee4d5f522fadaf1e/pkg/sql/sem/tree/expr.go#L1262)):*
> ```Go
> 		return nil, err
> 	}
> 	node := &CastExpr{Expr: expr, Type: colType, SyntaxMode: CastShort}
> ```

Are you sure that's safe? W.r.t operator precedence? e.g. `CAST(a+b AS INT)` turned into `a + b::INT` or the same with some of the other operators? 

IIRC we don't have sufficient tests to exercise this and we have been bitten before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236#-:-L6T-UuUrJjlyNWnPemu:b-o8szbg)*

**Comment by RaduBerinde** [comment]
Yes, the `opt/index_constraints.go` code is defunct as of this PR. I plan to delete `sql/opt/*.go` and move `sql/opt/opt/*` to `sql/opt/` in a follow-up.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/optbuilder/scalar.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236#-L6Sz6z3KiRNZaz99DOY:-L6T01dKUVGqUxWet-ZN:btncoi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c630a15e6b081f92a6974984e05cdf1ee9e3785/pkg/sql/opt/optbuilder/scalar.go#L176)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

this case seems impossible. `(*Placeholder).Eval()` never returns the original placeholder. Or did you only mean it as an assertion? Then maybe use `programming error` in the error text.
</blockquote></details>

Removed (it does return it if `!HasPlaceholders()`, but I already checked that)

---

*[pkg/sql/sem/tree/expr.go, line 1262 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236#-L6SzUJfo3I2lwtkOqEC:-L6T1QmF18Iul5qLdVrc:bfhhfa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b66dc20e7db95161f6028844ee4d5f522fadaf1e/pkg/sql/sem/tree/expr.go#L1262)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Are you sure that's safe? W.r.t operator precedence? e.g. `CAST(a+b AS INT)` turned into `a + b::INT` or the same with some of the other operators? 

IIRC we don't have sufficient tests to exercise this and we have been bitten before.
</blockquote></details>

I added a testcase. `CAST(a + b + c AS string)` becomes `((a + b) + c)::STRING`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236#-:-L6T1eqHvcrLlLPPyjGb:b-e9gkf6)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r4, 2 of 2 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236#-:-L6Wz4ny0KS0UvqJmlnt:bnfp4nl)*

**Comment by RaduBerinde** [comment]
@knz or @jordanlewis can I get an OK from your end? Thanks!

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r4, 2 of 2 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt_index_selection.go, line 146 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236#-L6XYtqNn87qD45HhPwS:-L6XYtqNn87qD45HhPwT:b-i0k7f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a4d2840c50dc3ee863c11d33a9ac2f6016da297/pkg/sql/opt_index_selection.go#L146)):*
> ```Go
> 			ctx, &p.semaCtx, p.EvalContext(), optimizer.Factory(), colNames, colTypes,
> 		)
> 		bld.AllowUnsupportedExpr = true
> ```

What's this about? I'm definitely unfamiliar with this code, but any time there's an uncommented boolean switch set for something it makes me nervous that future maintainers will be confused about what's going on and possibly screw up. For example, someone who wants to copy this code to support this same thing in a different area might blindly copy this flag without knowing what it does, etc etc.

Point is, can you add a comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236#-:-L6XaD3OejCA5SB9iSbD:bnfp4nl)*

**Comment by knz** [comment]
Code LGTM

Please have someone from the perf team (Jordan for example) acknowledge
the perf hit. That will need to be known when folk will start measuring
/ comparing perf across branches and over time.

**Comment by jordanlewis** [comment]
Yeah @knz actually makes a pretty good point... we need to communicate that we shouldn't be testing perf stuff against master anymore at all. I will make sure to share that around.

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt_index_selection.go, line 146 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236#-L6XYtqNn87qD45HhPwS:-L6Xcbw1-z4iaAC0wVWW:bpiaw71) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a4d2840c50dc3ee863c11d33a9ac2f6016da297/pkg/sql/opt_index_selection.go#L146)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What's this about? I'm definitely unfamiliar with this code, but any time there's an uncommented boolean switch set for something it makes me nervous that future maintainers will be confused about what's going on and possibly screw up. For example, someone who wants to copy this code to support this same thing in a different area might blindly copy this flag without knowing what it does, etc etc.

Point is, can you add a comment?
</blockquote></details>

It is documented here: https://github.com/cockroachdb/cockroach/blob/6e197ccdad6baf99fd7e6a9249fc29375a00236e/pkg/sql/opt/optbuilder/builder.go#L49

I don't think we should replicate that everywhere we use it. It will go away at some point anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23236)*

**Comment by jordanlewis** [comment]
Fair enough - LGTM

**Pull request merged**
