### PR TITLE
jobs: skip TestRetriesWithExponentialBackoff

### PR DESCRIPTION
**Pull request by stevendanna**
Release note: None
Epic: none

### CODE REVIEW

**Review by msbutler — APPROVED** [review]

**Comment by stevendanna** [comment]
TFTR!

bors r+

**Comment by msbutler** [comment]
bors p=99

**Comment by rickystewart** [comment]
@msbutler If you've already added your PR to the queue, you have to remove it if you want to change the priority. You have the right idea using `p=99` for this skip of a very flaky test, you just did it in a way where `bors` doesn't know that's what you want to do.

**Pull request merged**
