### PR TITLE
cmd/roachtest: tweaks to sstable corruption test

### PR DESCRIPTION
**Pull request by nicktrav**
A few minor changes to the existing roachtest:

Reduce the warehouse count on ingest back to 100 - this should be ample,
and it matches the warehouse count on the read path in a later part of
the test.

Change the stop options to wait until the process has been terminated
before continuing.

Re-work the command to search for SSTables to corrupt - use tables from
the most recent manifest (if multiple are present); consider SSTables
with either a start or end key representing a user table; shuffle tables
to distribute corruption over the LSM; perform filtering in the bash
command rather than in the test runner itself.

Release justification: Roachtest-only change.

Release note: None.

Touches #77321.

### CODE REVIEW

**Comment by nicktrav** [comment]
I also did a [stress test of this](https://teamcity.cockroachdb.com/viewLog.html?buildId=4547105&buildTypeId=Cockroach_Nightlies_RoachtestStress&tab=buildLog), and it came back clean. That's not to say this fixes whatever is causing #77321, just that the test still works as expected.

**Comment by nicktrav** [comment]
I walk back the comment about the stress test not failing. I ran it again and hit what seems to be #77627. That's unrelated to the changes, but thought I'd mention it.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77675#-:-My7spSEA0u0igMoJbq9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nicktrav)

___
*[pkg/cmd/roachtest/tests/sstable_corruption.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77675#-My7stzA-X-LKked2yiJ:-My7stzA-X-LKked2yiK:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/436026f2018000a4b72f213a4836ade9e3e1026d/pkg/cmd/roachtest/tests/sstable_corruption.go#L56)):*
> ```Go
> 	c.Stop(ctx, t.L(), opts, crdbNodes)
> 
> 	const findTablesCmd = "" +
> ```

Nice!

**Comment by nicktrav** [comment]
TFTR!

bors r=itsbilal

**Pull request merged**
