### PR TITLE
cloudimpl: add ReadFileAt to ExternalStorage API

### PR DESCRIPTION
**Pull request by dt**
This adds `ReadFileAt` to the external storage API.

`ReadFileAt` returns a Reader, like ReadFile, but starting from the specified offset.

Unlike `ReadFile`, `ReadFileAt` also returns the total size of the file. This is added as callers reading at offsets may often need to know the total file size, for example to know the offset at which to read the footer of an sstable. Most remote storage providers include this information in their object fetch responses already, so passing it along to them could allow them to avoid making a separate RPC in some cases.

Support is added for each storage provider in individual commits, and then to the API in the last commit. A follow-up change will then use this API to implement pebble's vfs.File API.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 8 of 8 files at r5, 3 of 3 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58384)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/storage/cloudimpl/azure_storage.go, line 121 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58384#-MPpcDKE3F3A8EGf7fMf:-MPpcDKE3F3A8EGf7fMg:b-e692f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c22da0846c76be344c5b9a9f0be5b958238f03a/pkg/storage/cloudimpl/azure_storage.go#L121)):*
> ```Go
> 	// https://github.com/cockroachdb/cockroach/issues/23859
> 	blob := s.getBlob(basename)
> 	get, err := blob.Download(ctx, offset, 0, azblob.BlobAccessConditions{}, false)
> ```

let's replace 0 w/ azblock.CountToEnd
___
*[pkg/storage/cloudimpl/gcs_storage.go, line 264 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58384#-MPpcyl3EXyW3I-xk93R:-MPpcyl42xDQ1EMooZ55:bkils0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c22da0846c76be344c5b9a9f0be5b958238f03a/pkg/storage/cloudimpl/gcs_storage.go#L264)):*
> ```Go
> 		return nil, 0, err
> 	}
> 	return reader, reader.data.Attrs.Size, nil
> ```

Do we know for sure that Attrs.Size refers to the entire size of the blob and not to the fetched chunk?
___
*[pkg/storage/cloudimpl/http_storage.go, line 175 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58384#-MPpbk-61MC8Nsea7W_0:-MPpbk-61MC8Nsea7W_1:b-94bsm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c22da0846c76be344c5b9a9f0be5b958238f03a/pkg/storage/cloudimpl/http_storage.go#L175)):*
> ```Go
> // ensures that range start offset is the same as 'pos'
> // See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range
> func checkHTTPContentRangeHeader(h string, pos int64) (int64, error) {
> ```

can you update comment re return val?
___
*[pkg/storage/cloudimpl/s3_storage.go, line 255 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58384#-MPpdDoU88_ajTxJsE0U:-MPpdDoU88_ajTxJsE0V:b-obw888) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c22da0846c76be344c5b9a9f0be5b958238f03a/pkg/storage/cloudimpl/s3_storage.go#L255)):*
> ```Go
> 	}
> 	req := &s3.GetObjectInput{Bucket: s.bucket, Key: aws.String(path.Join(s.prefix, basename))}
> 	req.Range = aws.String(fmt.Sprintf("bytes=%d-", offset))
> ```

why not inline Range in the initialization above?
___
*[pkg/storage/cloudimpl/workload_storage.go, line 102 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58384#-MPpdLEKE7mCmJA7SoIB:-MPpdLEKE7mCmJA7SoIC:bwf9hqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c22da0846c76be344c5b9a9f0be5b958238f03a/pkg/storage/cloudimpl/workload_storage.go#L102)):*
> ```Go
> 	_ context.Context, basename string, offset int64,
> ) (io.ReadCloser, int64, error) {
> 	panic("unimplemented")
> ```

return `nil, 0, errors.AssertionFailedf()`?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58384)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/storage/cloudimpl/azure_storage.go, line 121 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58384#-MPpcDKE3F3A8EGf7fMf:-MPt2wtF6sWbrYcwsQ1E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c22da0846c76be344c5b9a9f0be5b958238f03a/pkg/storage/cloudimpl/azure_storage.go#L121)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

let's replace 0 w/ azblock.CountToEnd
</blockquote></details>

Done.
___
*[pkg/storage/cloudimpl/gcs_storage.go, line 264 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58384#-MPpcyl3EXyW3I-xk93R:-MPsy40-7n1FyWho4-lV:b-jqme5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c22da0846c76be344c5b9a9f0be5b958238f03a/pkg/storage/cloudimpl/gcs_storage.go#L264)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we know for sure that Attrs.Size refers to the entire size of the blob and not to the fetched chunk?
</blockquote></details>

Yep, the docs say it is the object's size, and looking at the code, they do the same song/dance I did for http: read Content-Length for non-range, otherwise parse the Content-Range header: https://github.com/googleapis/google-cloud-go/blob/c77c822b5aadb0f5f3ae9381acafdee496047f8a/storage/reader.go#L219
___
*[pkg/storage/cloudimpl/http_storage.go, line 175 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58384#-MPpbk-61MC8Nsea7W_0:-MPsydta6E818aKuG1iF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c22da0846c76be344c5b9a9f0be5b958238f03a/pkg/storage/cloudimpl/http_storage.go#L175)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

can you update comment re return val?
</blockquote></details>

Done.
___
*[pkg/storage/cloudimpl/s3_storage.go, line 255 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58384#-MPpdDoU88_ajTxJsE0U:-MPszybk5BnGdYl8uRRE:b-ugbus3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c22da0846c76be344c5b9a9f0be5b958238f03a/pkg/storage/cloudimpl/s3_storage.go#L255)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why not inline Range in the initialization above?
</blockquote></details>

Ah, because I actually meant to put it inside a `if offset != 0`. I suppose we may as well just use `0-` range though and eliminate the special case.
___
*[pkg/storage/cloudimpl/workload_storage.go, line 102 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/58384#-MPpdLEKE7mCmJA7SoIB:-MPszAE41s5b9IdLuMOp:b-lv365h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c22da0846c76be344c5b9a9f0be5b958238f03a/pkg/storage/cloudimpl/workload_storage.go#L102)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

return `nil, 0, errors.AssertionFailedf()`?
</blockquote></details>

This should never be called -- in fact, I think we could delete this file entirely with a little tweak to move csv generation into workload csv-server. Until, then can't see this ever being called, so I'd rather crash fast and obvious so I'm ok with the panic.

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 1 files at r10, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58384)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
