### PR TITLE
workload/schemachange: add support for ALTER TYPE ... DROP VALUE

### LINKED ISSUE #59197: sql: add ALTER TYPE DROP VALUE to the randomized schema change tests
Followup to adding support for dropping enum values, once https://github.com/cockroachdb/cockroach/pull/58688 goes in. 

Jira issue: CRDB-3322

Epic CRDB-19168

### PR DESCRIPTION
**Pull request by chrisseto**
**workload/schemachange: fix Scan error in watchdog**
Previously, running the schemachange workload would intermittently log
errors about not being able to scan NULL into an *int. This was due to
an aggregation that would occasionally find no rows.

This commit wraps the `sum` aggregations in a `coalesce` to ensure an
integer is always returned.

Epic: none
Release note: None

**workload/schemachange: add support for ALTER TYPE ... DROP VALUE**
`ALTER TYPE ... DROP VALUE ...` has been implemented for quite some time
now. However, it was never implemented within `workload/schemachange`.
This commit adds a generator for said statment to `operationGenerator`.

Epic: CRDB-19168
Fixes: #59197
Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:  Nice work!

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111056#-:-NeskLlv-0KkeGfzvZ7Q:bo31fz2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chrisseto, @herkolategan, and @smg260)

___
*[`pkg/workload/schemachange/operation_generator.go` line 3923 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111056#-NesjH3S2Vgxu2pHr9we:-NesjH3S2Vgxu2pHr9wf:b-dh7vd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5e8eb6d9241913f4498abb546e6ed8bc7c2a460/pkg/workload/schemachange/operation_generator.go#L3923)):*
> ```Go
> 		str[i] = alphabet[og.randIntn(len(alphabet))]
> 	}
> 	return string(str)
> ```

Should we just delegate to randUtil.RandString?

**Review by chrisseto — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111056#-:-NeskYoF6HN6vr9fOoh6:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, and @smg260)

___
*[`pkg/workload/schemachange/operation_generator.go` line 3923 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111056#-NesjH3S2Vgxu2pHr9we:-NeskSgi21TQSM1Taadx:b-2fvgxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5e8eb6d9241913f4498abb546e6ed8bc7c2a460/pkg/workload/schemachange/operation_generator.go#L3923)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Should we just delegate to randUtil.RandString?
</blockquote></details>

Oh didn't realize that was an option! I'll update this method to delegate before merging. Thanks!

**Comment by chrisseto** [comment]
bors r=fqazi

**Comment by chrisseto** [comment]
bors r=fqazi

**Comment by chrisseto** [comment]
Looks like the build agent may have gotten 🪓 'd? I see a canceled status.

bors retry

**Pull request merged**
