### PR TITLE
forbiddenmethod: lint against calls to (grpc.ClientConn).Close

### PR DESCRIPTION
**Pull request by tbg**
Our main use of ClientConn is through rpc.Context, where they are
cached. This means that most of the time, in production code, it
would be fairly disruptive to call `Close` when done with the
connection (as I found out, luckily in testing code). Essentially
we are forced into a pattern that is not idiomatic go, so our
muscle memory works against us.

This commit adds linting against calls to that method.

This is all relatively unfortunate. Ideally, we'd return wrapped objects
from `rpc.Context` that don't even have a Close method. But the common
use for these ClientConns is to pass them to an proto-generated wrapper
that makes an RPC client, and those take a naked `*ClientConn`. We could
build more tooling around this, but as a first pass the lint is helpful.

See #60473 for a WIP towards a change that "avoids" handing out the
`*ClientConn`. It seems workable, just needs a lot of (simple) code changes.
I won't be pushing that over the finish line anytime soon, so the lint
should merge first.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
Lovely generalization :lgtm_strong: 

> Reviewed 13 of 13 files at r1, 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60474#-:-MTI9FsjB4z7WP54Tf7g:b-avoy96)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
bors r=ajwerner

**Comment by tbg** [comment]
bors r=ajwerner

**Comment by tbg** [comment]
bors r=ajwerner

**Pull request merged**
