### PR TITLE
sql: add parser support for XA transactions

### PR DESCRIPTION
**Pull request by nvb**
Informs #22329.

This commit adds new syntax for `PREPARE TRANSACTION <gid>`, `COMMIT PREPARED <gid>`, and `ROLLBACK PREPARED <gid>`, for parity with Postgres support.

Handling of the syntax is currently unimplemented.

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm!

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129298#-:-ODteEoLBbVY-O7gTm9T:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=rafiss

**Comment by nvanbenschoten** [comment]
bors retry

**Comment by nvanbenschoten** [comment]
EngFlow issues this morning.

bors retry

**Pull request merged**
