### PR TITLE
geo: replace flattenGeometry with an iterator

### PR DESCRIPTION
**Pull request by otan**
Previously, we'd use flattenGeom to decompose a MULTI-* or
GEOMETRYCOLLECTION into individual components. However, this created an
allocation which took ~30ms for a 120k row join. To remove the
allocation, we instead change flattenGeom to an iterator that goes
through each sub-shape.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51938)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/iterator.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-MDLWu3J7khkkiH1UkPS:-MDLWu3J7khkkiH1UkPT:bs3hvvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f5157813a1b2c97cd9610d8924a0ea68cca004/pkg/geo/iterator.go#L26)):*
> ```Go
> 	g                 geom.T
> 	emptyBehavior     EmptyBehavior
> 	idx               int
> ```

can you add a comment for `idx` and `geomCollectionIdx`.
___
*[pkg/geo/iterator.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-MDLX2PR5K1LQeygcSJf:-MDLX2PR5K1LQeygcSJg:b7ppg6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f5157813a1b2c97cd9610d8924a0ea68cca004/pkg/geo/iterator.go#L60)):*
> ```Go
> }
> 
> func (it *GeomTIterator) next() (geom.T, bool, error) {
> ```

can you add a function comment so it is clear how this is different from `Next()`
___
*[pkg/geo/iterator.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-MDLaSbzEz-rELxxRccw:-MDLaSbzEz-rELxxRccx:b1feojq) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f5157813a1b2c97cd9610d8924a0ea68cca004/pkg/geo/iterator.go#L101)):*
> ```Go
> 				return nil, false, err
> 			}
> 			if next {
> ```

The conventional way (which is slightly easier to read) to handle the arbitrary nesting in GeometryCollection would be something like
```
type GeomTIterator struct {
  g                 geom.T
  // idx is either:
  // - at the current element and iter is non-nil. This occurs only if g is a GeometryCollection and iter is the iterator over g.Geom(idx).
  // - at the next element and iter is nil.
  idx               int
  iter *GeomTIterator
}
```

Instead of managing the `geomCollectionIdx` on behalf of the nested iterator that this code does. This code saves a heap allocation, so maybe that justifies it.
___
*[pkg/geo/geomfn/distance_test.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-MDLcEzV6ja3yrU0v3Ze:-MDLcEzV6ja3yrU0v3Zf:b-n5k14b) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f5157813a1b2c97cd9610d8924a0ea68cca004/pkg/geo/geomfn/distance_test.go#L286)):*
> ```Go
> 	{
> 		"GEOMETRYCOLLECTION (POINT, POINT) with POINT",
> 		"GEOMETRYCOLLECTION ( POINT(3 4), POINT(1 2) )",
> ```

can you add a test with another level of GEOMETRYCOLLECTION nesting?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51938)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/iterator.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-MDLWu3J7khkkiH1UkPS:-MDLvr0U8MkZeMG832Yj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f5157813a1b2c97cd9610d8924a0ea68cca004/pkg/geo/iterator.go#L26)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment for `idx` and `geomCollectionIdx`.
</blockquote></details>

Done.
___
*[pkg/geo/iterator.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-MDLX2PR5K1LQeygcSJf:-MDM-CAk3q6TuzU7L9Px:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f5157813a1b2c97cd9610d8924a0ea68cca004/pkg/geo/iterator.go#L60)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a function comment so it is clear how this is different from `Next()`
</blockquote></details>

Done.
___
*[pkg/geo/iterator.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-MDLaSbzEz-rELxxRccw:-MDLvs-FDtChFgkv0VTb:bcovi3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f5157813a1b2c97cd9610d8924a0ea68cca004/pkg/geo/iterator.go#L101)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The conventional way (which is slightly easier to read) to handle the arbitrary nesting in GeometryCollection would be something like
```
type GeomTIterator struct {
  g                 geom.T
  // idx is either:
  // - at the current element and iter is non-nil. This occurs only if g is a GeometryCollection and iter is the iterator over g.Geom(idx).
  // - at the next element and iter is nil.
  idx               int
  iter *GeomTIterator
}
```

Instead of managing the `geomCollectionIdx` on behalf of the nested iterator that this code does. This code saves a heap allocation, so maybe that justifies it.
</blockquote></details>

I didn't realise GeometryCollections could be nested within each other .... thanks for calling it out. I'll audit the rest.
___
*[pkg/geo/geomfn/distance_test.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-MDLcEzV6ja3yrU0v3Ze:-MDLvxmEDX0loRTw-D62:bcovi3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f5157813a1b2c97cd9610d8924a0ea68cca004/pkg/geo/geomfn/distance_test.go#L286)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a test with another level of GEOMETRYCOLLECTION nesting?
</blockquote></details>

I didn't realise GeometryCollections could be nested within each other .... thanks for calling it out. I'll audit the rest.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-:-MDR2M8rBR2YQNceMMD-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/iterator.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-MDR0QM3C3v4x6yk5Ki4:-MDR0QM3C3v4x6yk5Ki5:b-5km65j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d612ed2242ded430a17a2852662e336ff8e268f/pkg/geo/iterator.go#L26)):*
> ```Go
> 	g             geom.T
> 	emptyBehavior EmptyBehavior
> 	// idx the index into the MULTI-* or GEOMETRYCOLLECTION item.
> ```

// idx is the index ...

**Comment by otan** [comment]
bors r=sumeerbhola

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51938)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[pkg/geo/iterator.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51938#-MDR0QM3C3v4x6yk5Ki4:-MDR7EjO3u7vTesSm31E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d612ed2242ded430a17a2852662e336ff8e268f/pkg/geo/iterator.go#L26)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// idx is the index ...
</blockquote></details>

Done.

**Pull request merged**
