### PR TITLE
sql: enable some mutations in udfs

### PR DESCRIPTION
**Pull request by rharding6373**
sql: enable insert in udf bodies

  This PR enables INSERT in UDFs and adds some logic test coverage.

  There are currently some known limitations to mutations in UDFs, namely
  foreign key cascades and some constraint checking which will be
  addressed in future PRs.

  Epic: CRDB-19255
  Informs: #87289

  Release note (sql change): Enables INSERT commands in UDF statement
  bodies.

sql: enable update and upsert in udf bodies

  This PR enables UPDATE in UDFs and adds some logic test coverage. Since
  both INSERT and UPDATE are supported, this also enabled UPSERT.

  Epic: CRDB-19255
  Informs: #87289

  Release note (sql change): Enables UPDATE and UPSERT commands in UDF
  statement bodies.

sql: add upsert tests for udfs

  This PR adds logic tests for UPSERTs in UDF bodies.

  Epic: CRDB-19255
  Informs: #87289

  Release note: None

sql: fix record-returning udfs with no result

  Previously, record-returning UDFs whose last SQL statement returned no
  result (i.e., not a SELECT or RETURNING statement) would succeed. They
  now return a return type mismatch error, as expected.

  Epic: CRDB-19255
  Informs: #87289

  Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
Very cool! I've only reviewed the first commit so far. 

> Reviewed 14 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-:-NV6VPHiBQGuErFVqK-q:b8goyqc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/builder.go` line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6I9ti7-D_9KzY6b3u:-NV6I9ti7-D_9KzY6b3v:bdcw1vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/opt/optbuilder/builder.go#L321)):*
> ```Go
> 		case *tree.Delete:
> 			panic(unimplemented.NewWithIssuef(87289, "%s usage inside a function definition", stmt.StatementTag()))
> 		case *tree.Insert:
> ```

nit: you can combine this case with the *tree.Select and tree.SelectStatement cases: `case *tree.Select, tree.SelectStatement, *tree.Insert:`.
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6ITs8-WCM3PxE885o:-NV6ITs8-WCM3PxE885p:b1vn950) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf#L74)):*
> ```
> 
> statement error pgcode 42P01 pq: relation "dne" does not exist
> CREATE FUNCTION err() RETURNS INT LANGUAGE SQL AS 'SELECT a FROM dne'
> ```

Where did this test come from?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 5 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6IjRdAfHyg2jbfMsC:-NV6IjRdAfHyg2jbfMsD:bji212s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L5)):*
> ```
> 
> statement ok
> CREATE FUNCTION f_should_err() RETURNS RECORD AS
> ```

This should error because the return type doesn't match, correct? Can you leave a TODO to explain that?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6Is7-9emt2BwM2ELA:-NV6Is7-9emt2BwM2ELB:b-b7wg7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L11)):*
> ```
> 
> statement error pq: at or near "as": syntax error
> CREATE FUNCTION f_err() AS
> ```

nit: syntax errors probably don't need to be tested here, unless there was something specific to INSERTs about this case
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 17 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6J8GwCIJpOz8PoAPa:-NV6J8GwCIJpOz8PoAPb:bnn2bpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L17)):*
> ```
> 
> statement error missing "a" primary key column
> CREATE FUNCTION f_err(b INT) RETURNS RECORD AS
> ```

Nice test case!
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6JJ6jEW0Q2K9N5aNk:-NV6JJ6jEW0Q2K9N5aNl:by5fm6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L36)):*
> ```
> 
> query T
> SELECT f_insert(3,4);
> ```

Can you add a test that calls f_insert again with the same value for a to ensure there is a duplicate key error?

Some other ideas of interesting tests:

1. Errors for STABLE and IMMUTABLE functions that contain `INSERT`. Postgres errors lazily at runtime of the function, but maybe we want to error during creation of the function since that's a better user experience?

2. Ensure that later calls to a function can see inserts from prior invocations:

```
CREATE TABLE t (a int);

CREATE FUNCTION f(i INT) RETURNS SETOF INT LANGUAGE SQL AS $$
  INSERT INTO t VALUES (i);
  SELECT a FROM t;
$$;

-- The first call, f(1), sees its own insert. The second call, f(2), sees both inserted values.
SELECT * FROM f(1)
UNION ALL
SELECT * FROM f(2);
 f
---
 1
 1
 2
(3 rows)
```
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 188 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6STSy7OMK0ANvUdF4:-NV6STSy7OMK0ANvUdF5:b-cujg65) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L188)):*
> ```
> (5,100,101)
> 
> # TODO(102771): Expected error due to f_drop's dependency on c.
> ```

nit: add `#` in front of issue number

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102773)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6ITs8-WCM3PxE885o:-NV6sD133M89_b3R2BTa:bgjtk5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf#L74)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Where did this test come from?
</blockquote></details>

This is actually from the first test in insert: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/insert#L1

I saw that we didn't test that a table exists, only columns, in UDFs, and this seemed like a better place to cover it.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 5 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6IjRdAfHyg2jbfMsC:-NV6simj3dQWNr8X5eZ6:b5w3b4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L5)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This should error because the return type doesn't match, correct? Can you leave a TODO to explain that?
</blockquote></details>

Added (Though I fix this in the last commit...maybe the commits are suboptimally reordered).
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6Is7-9emt2BwM2ELA:-NV6sz3CCmgHHRNNZT0Y:b6slsgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L11)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: syntax errors probably don't need to be tested here, unless there was something specific to INSERTs about this case
</blockquote></details>

I added it as a follow-on to the previous test. We should always return something from a UDF. But you're right we cover this in other non-logic tests. 
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6JJ6jEW0Q2K9N5aNk:-NV6ui-_Exp1_qceRwW_:btsrvpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L36)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add a test that calls f_insert again with the same value for a to ensure there is a duplicate key error?

Some other ideas of interesting tests:

1. Errors for STABLE and IMMUTABLE functions that contain `INSERT`. Postgres errors lazily at runtime of the function, but maybe we want to error during creation of the function since that's a better user experience?

2. Ensure that later calls to a function can see inserts from prior invocations:

```
CREATE TABLE t (a int);

CREATE FUNCTION f(i INT) RETURNS SETOF INT LANGUAGE SQL AS $$
  INSERT INTO t VALUES (i);
  SELECT a FROM t;
$$;

-- The first call, f(1), sees its own insert. The second call, f(2), sees both inserted values.
SELECT * FROM f(1)
UNION ALL
SELECT * FROM f(2);
 f
---
 1
 1
 2
(3 rows)
```
</blockquote></details>

Done, good ideas!

I'm surprised that the last one worked, though. I would have expected it to fail due to https://github.com/cockroachdb/cockroach/issues/70731. I'm going to take some time to understand this issue in more detail.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r8, 11 of 11 files at r9, 9 of 9 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-:-NVTafq94pQpZ0lsdhDp:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6JJ6jEW0Q2K9N5aNk:-NVTUuY4AGO1zQXHjCHr:b-sf6hut) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L36)):*
>I'm surprised that the last one worked, though. I would have expected it to fail due to [#70731](https://github.com/cockroachdb/cockroach/issues/70731).

Is it because we configure txn stepping for volatile UDFs?

Another interesting test case might be a single query that tries to insert the same row twice, so the duplicate key comes from the same txn.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 5 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NVTaD2vD1ZfcVbqxo0M:-NVTaD2w5h7Ec4aQwdx8:b5d2zkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d078a37049e63feb3cc7ffd17c358e12e1a57c34/pkg/sql/logictest/testdata/logic_test/udf_insert#L5)):*
> ```
> 
> statement error pq: return type mismatch in function declared to return record\nDETAIL: Function's final statement must be SELECT or INSERT/UPDATE/DELETE RETURNING.
> CREATE FUNCTION f_err() RETURNS RECORD AS
> ```

Could we have a similar function that returns `VOID` so it succeeds despite the lack of `RETURNING` clause?

**Review by rharding6373 — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-:-NVWnDoB7c238udFyfA4:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6JJ6jEW0Q2K9N5aNk:-NVWhxbq0EA_Y-If1Huz:bha8xhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L36)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

>I'm surprised that the last one worked, though. I would have expected it to fail due to [#70731](https://github.com/cockroachdb/cockroach/issues/70731).

Is it because we configure txn stepping for volatile UDFs?

Another interesting test case might be a single query that tries to insert the same row twice, so the duplicate key comes from the same txn.
</blockquote></details>

If I disable stepping we don't get any result rows (because the statements can't see updated table values), but it doesn't return an error. I think I need to play with some test cases that try to repro the CTE inconsistency with UDFs instead of or inside of CTEs, but I'll add that test suite in another PR.

Added a couple tests with duplicate keys.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 5 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NVTaD2vD1ZfcVbqxo0M:-NVWgZvDB-hXNf6NTVHs:bkzfzws) ([raw file](https://github.com/cockroachdb/cockroach/blob/d078a37049e63feb3cc7ffd17c358e12e1a57c34/pkg/sql/logictest/testdata/logic_test/udf_insert#L5)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Could we have a similar function that returns `VOID` so it succeeds despite the lack of `RETURNING` clause?
</blockquote></details>

Done. Found a bug, too.

**Comment by rharding6373** [comment]
TFTR! I'm going to merge this PR to unblock some of my other work this week. If you have any other suggestions about mutation functionality we want to test (my list currently includes foreign key cascades and CTEs with UDFs), please let me know and I can add them in separate PRs.

bors r+

**Comment by rharding6373** [comment]
bors cancel

**Comment by yuzefovich** [comment]
I think the CI failure is a flake being introduced in this PR.
```
=== RUN   TestLogic_udf_upsert/on_conflict_do_nothing
    logic.go:2879: 
         
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/7550/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/udf_upsert:45: SELECT * FROM t_ocdn;
        expected:
            1 1 1
            5 5 5
            
        but found (query options: "") :
            5  5  5
            1  1  1
```

bors r-

**Comment by rharding6373** [comment]
Need to do a more thorough audit for rowsort opportunities. Will retry after stressing more locally. Sorry about slowing the merge queue.

**Comment by rharding6373** [comment]
I think I fixed all the potential flakes due to row order. Let's try again.

bors r+

**Review by mgartner — COMMENTED** [review]
Very nicely done! Sorry for the late drive-by - I have just a few questions.

IIUC the last commit doesn't need to be backported to 23.1 because it's only possible if non-SELECT statements are allowed in UDFs, correct? Can it reproduce with a SETOF UDF with an empty body?

> Reviewed 1 of 15 files at r12, 13 of 14 files at r16, 2 of 11 files at r17, 11 of 12 files at r20, 8 of 9 files at r21, 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-:-NVe2zuwAJS1-KXrk7bh:bccjxro)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6JJ6jEW0Q2K9N5aNk:-NVdwYHN2aENA8PG2euJ:bcyx3p2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L36)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

If I disable stepping we don't get any result rows (because the statements can't see updated table values), but it doesn't return an error. I think I need to play with some test cases that try to repro the CTE inconsistency with UDFs instead of or inside of CTEs, but I'll add that test suite in another PR.

Added a couple tests with duplicate keys.
</blockquote></details>

I don't think we'd expect an error due to #70731, we'd expect index corruption. I forgot about that issue. It may be a concern even for a simple UDF with INSERTS/UPSERTS that is invoked multiple times. I'll try to come up with a reproduction of this issue.

**Review by mgartner — COMMENTED** [review]
Sorry, leaving a few more questions. Reviewable lost them the first time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-:-NVe5di46SHtqPWoAIPw:b-n2zko1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/sql/opt/optbuilder/scalar.go` line 793 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NVdyOvL7BKxM3_bPVcF:-NVdyOvL7BKxM3_bPVcG:b6ownmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f36c5ee1f8227e4509016196e72cf565893bb6d/pkg/sql/opt/optbuilder/scalar.go#L793)):*
> ```Go
> 			// column is already a tuple.
> 			cols = physProps.Presentation
> 			if len(cols) > 0 {
> ```

Does this fix need to be backported?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_update` line 72 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NVe-u_1DldZKP0jpEK1:-NVe-u_1DldZKP0jpEK2:bhy93dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a04d868f6a7d53e30f71eaf716afa8abded35d2/pkg/sql/logictest/testdata/logic_test/udf_update#L72)):*
> ```
> 
> statement error pq: multiple modification subqueries of the same table \"t\" are not supported
> SELECT f2(5,9), f2(7,11);
> ```

Should we get this error in a case where `f2` is referenced once but is called multiple times, e.g.:

```
SELECT f2(x, y) FROM (VALUES (1, 2), (3, 4)) v(x, y)
```
___
*[`pkg/sql/logictest/testdata/logic_test/udf_upsert` line 33 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NVe0di-CZhAjK5Xo-2m:-NVe0di-CZhAjK5Xo-2n:b-w0l1hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac6b1e04b9b2ebb1a44522e5d2d84849eada08c/pkg/sql/logictest/testdata/logic_test/udf_upsert#L33)):*
> ```
> 
> statement error pq: multiple modification subqueries of the same table \"t_ocdn\" are not supported
> SELECT f_ocdn(1,1,1), f_ocdn(3,2,2), f_ocdn(6,6,2), f_ocdn(2,1,1);
> ```

I have the same question as the one in the update tests. Do we expect an error for:

```
SELECT f_ocdn(x, y, z) FROM (VALUES (1, 1, 1), (3, 2, 2)) v(x, y, z)
```

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102773)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/sql/opt/optbuilder/scalar.go` line 793 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NVdyOvL7BKxM3_bPVcF:-NVeevU644GHXVuk97cI:bf9u6rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f36c5ee1f8227e4509016196e72cf565893bb6d/pkg/sql/opt/optbuilder/scalar.go#L793)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does this fix need to be backported?
</blockquote></details>

I don't think we can hit this bug before 23.2, since we can only hit it if we return 0 columns, and before 23.2 we only support SELECT which must always return at least 1 column.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_insert` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NV6JJ6jEW0Q2K9N5aNk:-NVeg-cJ9_nJaRw_ZJJX:b-147zcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e6082be806d2929e4ea3290f5fc3ee75a5825b5/pkg/sql/logictest/testdata/logic_test/udf_insert#L36)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think we'd expect an error due to #70731, we'd expect index corruption. I forgot about that issue. It may be a concern even for a simple UDF with INSERTS/UPSERTS that is invoked multiple times. I'll try to come up with a reproduction of this issue.
</blockquote></details>

It's possible the guard rails added in https://github.com/cockroachdb/cockroach/pull/70976 need to be expanded. We have another test case in this file that does fail due to the guard rail when we call something like `SELECT f(), f();` where `f()` contains a mutation. Or we need to prioritize a fix for #70731.

Thanks for trying to repro, let me know if you find anything. I started some of my own investigation here: https://gist.github.com/rharding6373/bb2a81f55e8fceaa6b536cd86d67b937
___
*[`pkg/sql/logictest/testdata/logic_test/udf_update` line 72 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NVe-u_1DldZKP0jpEK1:-NVfsdOt-ENReQ8_zkEW:bpizu7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a04d868f6a7d53e30f71eaf716afa8abded35d2/pkg/sql/logictest/testdata/logic_test/udf_update#L72)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should we get this error in a case where `f2` is referenced once but is called multiple times, e.g.:

```
SELECT f2(x, y) FROM (VALUES (1, 2), (3, 4)) v(x, y)
```
</blockquote></details>

This (and the other query below) is successful. I tested it out and there does not appear to be any index corruption. I'll add this test in a follow up PR. The explain output is not currently helpful in seeing the plan (there's already an issue open for this). Notes are here: https://gist.github.com/rharding6373/bb2a81f55e8fceaa6b536cd86d67b937. 
___
*[`pkg/sql/logictest/testdata/logic_test/udf_upsert` line 33 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/102773#-NVe0di-CZhAjK5Xo-2m:-NVfxBsN880Wt_AoMQhi:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac6b1e04b9b2ebb1a44522e5d2d84849eada08c/pkg/sql/logictest/testdata/logic_test/udf_upsert#L33)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I have the same question as the one in the update tests. Do we expect an error for:

```
SELECT f_ocdn(x, y, z) FROM (VALUES (1, 1, 1), (3, 2, 2)) v(x, y, z)
```
</blockquote></details>

See above.

**Pull request merged**
