### PR TITLE
keys: pretty-print timeseries keys

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7649)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[keys/printer.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-KM-sYJ6LKQjmLXOOR-K:-KM-sYJ6LKQjmLXOOR-L:1704728698) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e5f0d6301842a6d11dd9dae0a40af5f206083e/keys/printer.go#L34)):*
> ```Go
> // PrettyPrintTimeseriesKey is a hook for pretty printing a timeseries key. The
> // timeseries key prefix will already have been stripped off.
> var PrettyPrintTimeseriesKey = print
> ```

can you leave it uninitialized?

---

*[ts/resolution.go, line 35 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-KM-sSGfP4PjOIdUI1PF:-KM-sSGfP4PjOIdUI1PG:1312045397) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e5f0d6301842a6d11dd9dae0a40af5f206083e/ts/resolution.go#L35)):*
> ```Go
> 		return "1ns"
> 	}
> 	return fmt.Sprintf("%d", int64(r))
> ```

strconv.FormatInt?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-:-KM-s_RzOVXotS_5fOVz:1417088721)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[keys/printer.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-KM-sYJ6LKQjmLXOOR-K:-KM046lAFniWPK1tn1hM:437060653) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e5f0d6301842a6d11dd9dae0a40af5f206083e/keys/printer.go#L34)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you leave it uninitialized?
</details>
But then we'd need to check whether it was `nil` in `decodeTimeseriesKey`.

---

*[ts/resolution.go, line 35 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-KM-sSGfP4PjOIdUI1PF:-KM04Gydrao-H0_hzxNA:65839261) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e5f0d6301842a6d11dd9dae0a40af5f206083e/ts/resolution.go#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> strconv.FormatInt?
</details>
This seems clearer. That line is never expected to run, so performance isn't a concern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[keys/printer.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-KM-sYJ6LKQjmLXOOR-K:-KM0GTSSMQXq7kc_8SzP:-2096873179) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e5f0d6301842a6d11dd9dae0a40af5f206083e/keys/printer.go#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> But then we'd need to check whether it was `nil` in `decodeTimeseriesKey`.
</details>
Couldn't we just let it crash?

---

*[ts/resolution.go, line 35 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-KM-sSGfP4PjOIdUI1PF:-KM0GaMe7MCwQ5mfrKgO:-697743497) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e5f0d6301842a6d11dd9dae0a40af5f206083e/ts/resolution.go#L35)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This seems clearer. That line is never expected to run, so performance isn't a concern.
</details>
Sure. The cast to int64 isn't necessary to appease `vet`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649)*

**Comment by petermattis** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[keys/printer.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-KM-sYJ6LKQjmLXOOR-K:-KM0ULAWJEqEh1n78Gar:-1084453819) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e5f0d6301842a6d11dd9dae0a40af5f206083e/keys/printer.go#L34)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Couldn't we just let it crash?
</details>
Sure, but initialization isn't onerous. Not sure what the worry is here.

---

*[ts/resolution.go, line 35 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-KM-sSGfP4PjOIdUI1PF:-KM0Ub8JkurSj2rFYvcc:-85892480) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e5f0d6301842a6d11dd9dae0a40af5f206083e/ts/resolution.go#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Sure. The cast to int64 isn't necessary to appease `vet`.
</details>
The cast to `int64` was to ensure we don't recursively call `String()`, but I suppose that isn't possible using the `%d` formatter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649)*

**Comment by tamird** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[keys/printer.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-KM-sYJ6LKQjmLXOOR-K:-KM0YowEbFY5WemqC2v5:-241907786) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e5f0d6301842a6d11dd9dae0a40af5f206083e/keys/printer.go#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Sure, but initialization isn't onerous. Not sure what the worry is here.
</details>
Feels sloppier to allow this to silently rot, somehow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649)*

**Comment by petermattis** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[keys/printer.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649#-KM-sYJ6LKQjmLXOOR-K:-KM0sTnIhcap9kkhPt4k:-1144948806) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e5f0d6301842a6d11dd9dae0a40af5f206083e/keys/printer.go#L34)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Feels sloppier to allow this to silently rot, somehow.
</details>
I don't think this matters, so I changed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7649)*

**Pull request merged**
