### PR TITLE
sql: SHOW TESTING_RANGES

### PR DESCRIPTION
**Pull request by RaduBerinde**
This syntax is temporary and it will be replaced with a more versatile system
table (see discussion in #14366). This is useful for implementing/testing
`TESTING_RELOCATE` before we are able to flesh out all the details of the system
table proposals.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14390)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/show_ranges.go, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgI6okomu620NjJsoAm:-KgI6okomu620NjJsoAn:b-4x90rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/99eb3335744fec42d248ec77aa6fbe5f18be374d/pkg/sql/show_ranges.go#L33)):*
> ```Go
> 
> func (p *planner) ShowRanges(ctx context.Context, n *parser.ShowRanges) (planNode, error) {
> 	tableDesc, index, err := p.getTableAndIndex(ctx, n.Table, n.Index)
> ```

Need to verify permissions. Split includes a p.CheckPrivileges to ensure the user can see this descriptor. Maybe that check should be included in getTableAndIndex so it can't be missed.

---

*[pkg/sql/show_ranges.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgI8llzEG7gUFxEE3l5:-KgI8llzEG7gUFxEE3l6:bvuwxf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/99eb3335744fec42d248ec77aa6fbe5f18be374d/pkg/sql/show_ranges.go#L113)):*
> ```Go
> 		return false, err
> 	}
> 	n.values[0] = parser.DNull
> ```

Why not `n.span.Key` and `n.span.EndKey` below? It'd be nice to be able to use the results from this directly instead of checking if it's a NULL. Or am I missing something?

---

*[pkg/sql/show_ranges.go, line 142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgI9hF62Kg-WtyhH1Wx:-KgI9hF62Kg-WtyhH1Wy:b-3xq8fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/99eb3335744fec42d248ec77aa6fbe5f18be374d/pkg/sql/show_ranges.go#L142)):*
> ```Go
> 	n.values[3] = parser.DNull
> 	b := &client.Batch{}
> 	b.AddRawRequest(&roachpb.LeaseInfoRequest{
> ```

Is there a race condition here? Can a split occur or a replica move since the Scan in Start? That would cause the lease holder to be listed but not be present in the replicas list. There's no table lease being used, so I don't think that's protecting anything. Do we need to get a lease to protect against that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/show_ranges.go, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgI6okomu620NjJsoAm:-KgK18ezn070YUv1HEBs:bg9l7lo) ([raw file](https://github.com/cockroachdb/cockroach/blob/99eb3335744fec42d248ec77aa6fbe5f18be374d/pkg/sql/show_ranges.go#L33)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Need to verify permissions. Split includes a p.CheckPrivileges to ensure the user can see this descriptor. Maybe that check should be included in getTableAndIndex so it can't be missed.
</blockquote></details>

Done, thanks! (I incorrectly thought we only need to check that for modifications)

---

*[pkg/sql/show_ranges.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgI8llzEG7gUFxEE3l5:-KgJxtlYhChp74VZo1ns:b-j9twze) ([raw file](https://github.com/cockroachdb/cockroach/blob/99eb3335744fec42d248ec77aa6fbe5f18be374d/pkg/sql/show_ranges.go#L113)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why not `n.span.Key` and `n.span.EndKey` below? It'd be nice to be able to use the results from this directly instead of checking if it's a NULL. Or am I missing something?
</blockquote></details>

The keys are pretty-printed, skipping the table and index parts.. `span.Key` and `span.EndKey` print as empty strings..

---

*[pkg/sql/show_ranges.go, line 142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgI9hF62Kg-WtyhH1Wx:-KgJyOVAnVdWRRh5SDE-:b-nc30u6) ([raw file](https://github.com/cockroachdb/cockroach/blob/99eb3335744fec42d248ec77aa6fbe5f18be374d/pkg/sql/show_ranges.go#L142)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Is there a race condition here? Can a split occur or a replica move since the Scan in Start? That would cause the lease holder to be listed but not be present in the replicas list. There's no table lease being used, so I don't think that's protecting anything. Do we need to get a lease to protect against that?
</blockquote></details>

Yeah, this information is "best-effort" if there are ongoing movements; the intention is to use this with the replication queue disabled (eg testcluster in manual replication mode).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390)*

**Comment by mjibson** [comment]
Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/show_ranges.go, line 142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgI9hF62Kg-WtyhH1Wx:-KgL2mDAueHx05IrictH:bodo98x) ([raw file](https://github.com/cockroachdb/cockroach/blob/99eb3335744fec42d248ec77aa6fbe5f18be374d/pkg/sql/show_ranges.go#L142)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, this information is "best-effort" if there are ongoing movements; the intention is to use this with the replication queue disabled (eg testcluster in manual replication mode).
</blockquote></details>

Does it make sense to get a table lease to prevent this problem from happening? Or do we just not care?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/show_ranges.go, line 142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgI9hF62Kg-WtyhH1Wx:-KgL7QgxU7OXkpWNuESb:brjqtgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/99eb3335744fec42d248ec77aa6fbe5f18be374d/pkg/sql/show_ranges.go#L142)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Does it make sense to get a table lease to prevent this problem from happening? Or do we just not care?
</blockquote></details>

Hm, I don't think there is any relation between a table lease and the range leaseholder. A table lease doesn't prevent rebalancing..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 18 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_ranges.go, line 33 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ58AXx38zbFP6Rh5o:-KgQ58AXx38zbFP6Rh5p:bxtx3hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L33)):*
> ```Go
> )
> 
> func (p *planner) ShowRanges(ctx context.Context, n *parser.ShowRanges) (planNode, error) {
> ```

mind adding a file-level comment about the syntax and what this statement does?

---

*[pkg/sql/show_ranges.go, line 39 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ5QBMOQ3YHPp74dvQ:-KgQ5QBMOQ3YHPp74dvR:b-684ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L39)):*
> ```Go
> 	}
> 	// Note: for interleaved tables, the ranges we report will include rows from
> 	// interleaving, but that's ok.
> ```

nit: "but that's ok" is superfluous, if not misleading

---

*[pkg/sql/show_ranges.go, line 74 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ5gCIvG2MbMMw2bae:-KgQ5gCJpEIe2spgJisC:b-51bdg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L74)):*
> ```Go
> 	},
> 	{
> 		Name: "Replicas",
> ```

comment that these are store ids.

And side question - how is one supposed to resolve a store id to a node IP, exactly?

---

*[pkg/sql/show_ranges.go, line 95 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ6atSs6kq_yva5Frt:-KgQ6atSs6kq_yva5Fru:b-2x7pyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L95)):*
> ```Go
> 		// Normally we need to scan one more KV because the ranges are addressed by
> 		// the end key.
> 		extraKV, err := n.p.txn.Scan(ctx, metaEnd, keys.Meta2Prefix.PrefixEnd(), 1)
> ```

nit : please comment the `1`

---

*[pkg/sql/show_ranges.go, line 141 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ7AD1mUKOvP3Fta9S:-KgQ7AD1mUKOvP3Fta9T:b72nufd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L141)):*
> ```Go
> 	// TODO(radu): this will be slow if we have a lot of ranges; find a way to
> 	// make this part optional.
> 	n.values[3] = parser.DNull
> ```

nit: move this up to where the rest of `values` is reset

---

*[pkg/sql/show_ranges.go, line 173 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ7Njofm299oevXlK8:-KgQ7Njofm299oevXlK9:b-4aduy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L173)):*
> ```Go
> 
> func (n *showRangesNode) DebugValues() debugValues {
> 	return debugValues{
> ```

can we just panic here and say not implemented?

---

*[pkg/sql/split_at.go, line 32 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ7YAB0P9ZRMQaNh0j:-KgQ7YAB0P9ZRMQaNh0k:bbsp1dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/split_at.go#L32)):*
> ```Go
> // Privileges: INSERT on table.
> func (p *planner) Split(ctx context.Context, n *parser.Split) (planNode, error) {
> 	tableDesc, index, err := p.getTableAndIndex(ctx, n.Table, n.Index, privilege.INSERT)
> ```

wouldn't a read privilege be more appropriate?

---

*[pkg/sql/parser/parse_test.go, line 230 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ2kYSkWUDA_lsYjl8:-KgQ2kYSkWUDA_lsYjl9:b1rxc89) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f072b8861e7eacf4a04e4ca312d11b8fe5bd01/pkg/sql/parser/parse_test.go#L230)):*
> ```Go
> 		{`SHOW TESTING_RANGES FROM INDEX t@i`},
> 		{`SHOW TESTING_RANGES FROM INDEX d.i`},
> 		{`SHOW TESTING_RANGES FROM INDEX i`},
> ```

shouldn't we require that indexes are always addresses as `table@index`? Are index names unique across tables?

---

*[pkg/sql/testdata/logic_test/ranges, line 81 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ4_vTS98OlLlunCFi:-KgQ4_vTS98OlLlunCFj:bt9w6bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/testdata/logic_test/ranges#L81)):*
> ```
> 3              limit  3
> 
> # -- Tests with interleaved tables --
> ```

how about also a test for an interleaved index?

---

*[pkg/sql/testdata/logic_test/ranges, line 89 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ4IZzHgH_Q-2kIgl1:-KgQ4I_-ydq1vRYM_RQB:b-8xr0hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/testdata/logic_test/ranges#L89)):*
> ```
> 
> query TTTI colnames
> SHOW TESTING_RANGES FROM TABLE t0
> ```

please add a comment that we expect this to be the same as the splits of `t`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-:-KgQ7hxGZAjmDZqAB-5W:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 18 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[pkg/sql/split_at.go, line 32 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ7YAB0P9ZRMQaNh0j:-KgQ8tfsY7UmrND4lp7z:b20tae7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/split_at.go#L32)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

wouldn't a read privilege be more appropriate?
</blockquote></details>

for splitting ranges? that doesn't sound right

---

*[pkg/sql/parser/parse_test.go, line 230 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ2kYSkWUDA_lsYjl8:-KgQ91T9SVmsKQkE_nwq:b-wc5oog) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f072b8861e7eacf4a04e4ca312d11b8fe5bd01/pkg/sql/parser/parse_test.go#L230)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

shouldn't we require that indexes are always addresses as `table@index`? Are index names unique across tables?
</blockquote></details>

I'm not crazy about it either but we support this syntax for other `INDEX` clauses. If there are multiple indexes with the same name, there will be an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 18 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/sql/show_ranges.go, line 33 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ58AXx38zbFP6Rh5o:-KgQIlgqkndv4OofOW8Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L33)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mind adding a file-level comment about the syntax and what this statement does?
</blockquote></details>

Done.

---

*[pkg/sql/show_ranges.go, line 39 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ5QBMOQ3YHPp74dvQ:-KgQIoQUAecK2DWmfqsV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L39)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: "but that's ok" is superfluous, if not misleading
</blockquote></details>

Done.

---

*[pkg/sql/show_ranges.go, line 74 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ5gCIvG2MbMMw2bae:-KgQIqXBDtb2PXhJbHJL:b-of37za) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L74)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

comment that these are store ids.

And side question - how is one supposed to resolve a store id to a node IP, exactly?
</blockquote></details>

Done. And no idea.

---

*[pkg/sql/show_ranges.go, line 95 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ6atSs6kq_yva5Frt:-KgQJLZAEg-ySp0rRCXS:bflx6n9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L95)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit : please comment the `1`
</blockquote></details>

Done. I would have thought the "one" in "one more KV" was enough

---

*[pkg/sql/show_ranges.go, line 141 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ7AD1mUKOvP3Fta9S:-KgQJfloLrwoZC1j3N2W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L141)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: move this up to where the rest of `values` is reset
</blockquote></details>

Done.

---

*[pkg/sql/show_ranges.go, line 173 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ7Njofm299oevXlK8:-KgQJkgrksTgyNaqLuHg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/show_ranges.go#L173)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can we just panic here and say not implemented?
</blockquote></details>

Done.

---

*[pkg/sql/testdata/logic_test/ranges, line 81 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ4_vTS98OlLlunCFi:-KgQIM_guo67cMDJaIer:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/testdata/logic_test/ranges#L81)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how about also a test for an interleaved index?
</blockquote></details>

Done.

---

*[pkg/sql/testdata/logic_test/ranges, line 89 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390#-KgQ4IZzHgH_Q-2kIgl1:-KgQHYZOVgIwO7UZPGfm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f6fb62326cd74392e7a421fbb424b9d81c0ce37/pkg/sql/testdata/logic_test/ranges#L89)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please add a comment that we expect this to be the same as the splits of `t`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14390)*

**Pull request merged**
