### PR TITLE
rpc: implement DecompressedSize on snappyCompressor

### PR DESCRIPTION
**Pull request by nvb**
This commit updates `snappyCompressor` to implement the anonymous interface declared in `grpc/rpc_util.go`'s decompress function. When implemented by an `encoding.Compressor`, the function can pre-allocate a buffer with the exact decompressed size instead of needing to dynamically grow the buffer while decompressing (in io.ReadAll), which can incur multiple allocations and memory copies.

This optimization has been available since https://github.com/grpc/grpc-go/commit/dcd1c9748d337a77f783b8be8666aa3d6fd47373.

See https://cockroachlabs.slack.com/archives/C4X2J0RH6/p1671224064592639 for discussion.

```
➜ benchdiff --run='BenchmarkReplicaProposal/bytes=.*,withFollower=true' --count=25 --old=HEAD~2 ./pkg/kv/kvserver

name                                                old time/op    new time/op    delta
ReplicaProposal/bytes=1.0_MiB,withFollower=true-10    3.23ms ± 6%    3.11ms ± 5%  -3.60%  (p=0.000 n=25+23)
ReplicaProposal/bytes=256_KiB,withFollower=true-10     835µs ± 7%     808µs ± 8%  -3.16%  (p=0.003 n=25+24)
ReplicaProposal/bytes=512_KiB,withFollower=true-10    1.67ms ± 6%    1.63ms ± 4%  -2.50%  (p=0.001 n=24+24)
ReplicaProposal/bytes=2.0_MiB,withFollower=true-10    6.17ms ± 9%    6.04ms ± 6%  -2.15%  (p=0.026 n=25+24)
ReplicaProposal/bytes=256_B,withFollower=true-10      44.9µs ± 2%    44.9µs ± 4%    ~     (p=0.945 n=24+25)
ReplicaProposal/bytes=512_B,withFollower=true-10      46.9µs ± 5%    46.9µs ± 3%    ~     (p=0.562 n=25+24)
ReplicaProposal/bytes=1.0_KiB,withFollower=true-10    49.3µs ± 4%    49.2µs ± 3%    ~     (p=0.835 n=25+24)

name                                                old speed      new speed      delta
ReplicaProposal/bytes=1.0_MiB,withFollower=true-10   325MB/s ± 6%   336MB/s ± 7%  +3.39%  (p=0.000 n=25+24)
ReplicaProposal/bytes=256_KiB,withFollower=true-10   314MB/s ± 7%   325MB/s ± 8%  +3.28%  (p=0.003 n=25+24)
ReplicaProposal/bytes=512_KiB,withFollower=true-10   315MB/s ± 6%   323MB/s ± 4%  +2.55%  (p=0.001 n=24+24)
ReplicaProposal/bytes=2.0_MiB,withFollower=true-10   341MB/s ± 9%   348MB/s ± 6%  +2.13%  (p=0.026 n=25+24)
ReplicaProposal/bytes=256_B,withFollower=true-10    5.70MB/s ± 2%  5.70MB/s ± 4%    ~     (p=0.941 n=24+25)
ReplicaProposal/bytes=512_B,withFollower=true-10    10.9MB/s ± 5%  10.9MB/s ± 3%    ~     (p=0.562 n=25+24)
ReplicaProposal/bytes=1.0_KiB,withFollower=true-10  20.8MB/s ± 4%  20.8MB/s ± 3%    ~     (p=0.847 n=25+24)

name                                                old alloc/op   new alloc/op   delta
ReplicaProposal/bytes=2.0_MiB,withFollower=true-10     102MB ± 4%      92MB ± 4%  -9.42%  (p=0.000 n=25+25)
ReplicaProposal/bytes=1.0_MiB,withFollower=true-10    55.8MB ± 2%    50.7MB ± 4%  -9.27%  (p=0.000 n=21+25)
ReplicaProposal/bytes=256_KiB,withFollower=true-10    14.8MB ± 4%    13.6MB ± 4%  -8.24%  (p=0.000 n=25+24)
ReplicaProposal/bytes=512_KiB,withFollower=true-10    27.4MB ± 3%    25.3MB ± 4%  -7.52%  (p=0.000 n=23+25)
ReplicaProposal/bytes=1.0_KiB,withFollower=true-10    53.6kB ± 2%    52.8kB ± 2%  -1.60%  (p=0.000 n=25+25)
ReplicaProposal/bytes=512_B,withFollower=true-10      35.3kB ± 1%    35.5kB ± 1%  +0.65%  (p=0.000 n=25+24)
ReplicaProposal/bytes=256_B,withFollower=true-10      26.3kB ± 2%    27.0kB ± 1%  +2.79%  (p=0.000 n=25+25)

name                                                old allocs/op  new allocs/op  delta
ReplicaProposal/bytes=512_KiB,withFollower=true-10     1.83k ±10%     1.76k ± 5%  -4.05%  (p=0.002 n=25+23)
ReplicaProposal/bytes=256_KiB,withFollower=true-10     1.02k ±10%     0.98k ± 8%  -4.00%  (p=0.001 n=25+24)
ReplicaProposal/bytes=1.0_MiB,withFollower=true-10     3.53k ± 7%     3.40k ± 5%  -3.66%  (p=0.002 n=25+22)
ReplicaProposal/bytes=1.0_KiB,withFollower=true-10       145 ± 0%       143 ± 2%  -1.24%  (p=0.000 n=18+24)
ReplicaProposal/bytes=512_B,withFollower=true-10         142 ± 1%       141 ± 1%  -0.82%  (p=0.000 n=24+24)
ReplicaProposal/bytes=256_B,withFollower=true-10         139 ± 1%       139 ± 1%    ~     (p=0.694 n=25+24)
ReplicaProposal/bytes=2.0_MiB,withFollower=true-10     6.80k ±12%     6.65k ±14%    ~     (p=0.247 n=25+25)
```

Release note (performance improvement): The RPC compression encoding was extended with a length prefixing format, allowing more efficient decompression on receivers.

Epic: None

### CODE REVIEW

**Review by tbg — CHANGES_REQUESTED** [review]
Just getting this off my review docket until it's ready for review 🕐

**Review by knz — COMMENTED** [review]
> Reviewed 6 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93871)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[`pkg/rpc/context.go` line 287 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93871#-NJkl3vnDujD7f35CcXw:-NJkl3vnDujD7f35CcXx:b-bbibeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/523ab7cf45a0b82636023440dfe9f14cdcf8b59c/pkg/rpc/context.go#L287)):*
> ```Go
> 	// Use the supplied cluster settings to determine whether length prefixing is
> 	// supported for the snappy compressor. This is a bit awkward because the
> 	// snappy compressor is a global object registered with gRPC at init time.
> ```

If my reading of the snappy source code is correct, you don't need this.
The base implementation of snappy.Reader already ignores the decompressed size header:
```go
    if chunkType ≤ 0x7f {
      // Section 4.5. Reserved unskippable chunks (chunk types 0x02-0x7f).
      r.err = ErrUnsupported
      return r.err
    }
    // Section 4.4 Padding (chunk type 0xfe).
    // Section 4.6. Reserved skippable chunks (chunk types 0x80-0xfd).
    if !r.readFull(r.buf[:chunkLen], false) {
      return r.err
    }
```

So as far as I can see:
- if the (new-version) sender provides the decompressed size header but the receiver doesn't support it, the (old-version) receiver will ignore it
- if the (old-version) sender doesn't send it, the (new-version) receiver can simply return -1

so we can always enable the header on the sending side, regardless of version, and be tolerant of a missing decompressed size header on the receiving side, regardless of version, and there'd be no version-specific code needed.

Does this check out?

**Review by tbg — DISMISSED** [review]
I added a commit that uses echotest for TestSnappyCompressorCompressDecompress, see if you like it.

Please re-request review when it's ready for another look (i.e. when you've responded), that's the best way to have it pop up in my queue as I only process notifications periodically.

**Review by nvb — COMMENTED** [review]
I've updated with @knz's suggested approach and am much more satisfied with the result.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93871#-:-NL9-9Bi5DDfIRWSwFWH:b6hptys)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[`pkg/rpc/snappy.go` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93871#-NJcPeiH6iZ-gmILyBtZ-r2-96:-NL8yDHPDecVt2tSR-Ql:b260ddb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c80cdd9737270e5d2c70128131f7dbab8fb3374/pkg/rpc/snappy.go#L96)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'm confused. Are we special-casing this `*snappyWriter` to our use case where the entire data is passed in with a single call to `Write`? Isn't that an artifact of how gRPC uses the decompressor? And if we are special casing on that, why do we need `w.wroteLen`?

What I expected the code here to look like was something like

- on the first call to `Write`, write the magic header, and reserve some room to fill in the uncompressed length at the very end (difficult with varint), and add `len(p)` to some counter
- on future calls, just add `len(p)` to the counter
- at Close/Flush time, put the counter into the buffer in an appropriate place.


</blockquote></details>

When the length was stored in the prefix of the compressed message, we had to jump through these kinds of hoops and impose the limitation you're referring to. Now that it's in the suffix, we avoid all of this. See now.
___
*[`pkg/rpc/context.go` line 287 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93871#-NJkl3vnDujD7f35CcXw:-NL8yWnV1canQgQXq8Kz:be3d70f) ([raw file](https://github.com/cockroachdb/cockroach/blob/523ab7cf45a0b82636023440dfe9f14cdcf8b59c/pkg/rpc/context.go#L287)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

If my reading of the snappy source code is correct, you don't need this.
The base implementation of snappy.Reader already ignores the decompressed size header:
```go
    if chunkType ≤ 0x7f {
      // Section 4.5. Reserved unskippable chunks (chunk types 0x02-0x7f).
      r.err = ErrUnsupported
      return r.err
    }
    // Section 4.4 Padding (chunk type 0xfe).
    // Section 4.6. Reserved skippable chunks (chunk types 0x80-0xfd).
    if !r.readFull(r.buf[:chunkLen], false) {
      return r.err
    }
```

So as far as I can see:
- if the (new-version) sender provides the decompressed size header but the receiver doesn't support it, the (old-version) receiver will ignore it
- if the (old-version) sender doesn't send it, the (new-version) receiver can simply return -1

so we can always enable the header on the sending side, regardless of version, and be tolerant of a missing decompressed size header on the receiving side, regardless of version, and there'd be no version-specific code needed.

Does this check out?
</blockquote></details>

Great idea! I had not considered storing the length in a real, skippable Snappy chunk so that the decoder would ignore it. That makes things significantly simpler, especially because it avoids the version gate. The Snappy decoder does require the first chunk to be a stream identifier, so we can no longer store the length in the compressed data's header, but a footer chunk works just as well.

I've changed things along these lines:
1. when encoding, add decompressed length in skippable snappy chunk at end of data stream
2. when decoding, do nothing. Snappy ignores the custom chunk type. This is why everything is backward compatible
3. when reading decompressed length, read over data stream, skipping from chunk to chunk until we find the custom decompressed length chunk. I had discounted length-suffixing schemes when originally drafting this PR because I wanted to keep `DecompressedSize` `O(1)` and not `O(data)`, but `O(chunks)` seems reasonable to me, given that each chunk is 64KB of uncompressed data (even though that's technically the same time complexity).

In addition to simplifying the change, it also improved performance. That's because when encoding, we're now appending the length to the underlying buffer after the rest of the compressed data, often in existing spare capacity. Before, we were appending the length to the underlying buffer before the rest of the compressed data, so we were often creating an intermediate buffer allocation to store the length, only to have to resize that buffer when the compressed data was appended.

**Review by knz — APPROVED** [review]
:lgtm: very clean. nicely done.

> Reviewed 1 of 1 files at r2, 8 of 8 files at r3, 14 of 14 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93871#-:-NLCaIuy-v3i0a_J6Mkd:ba6e3sm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[`pkg/rpc/snappy.go` line 165 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93871#-NLC_ZItDSshDdos6_pl:-NLC_ZItDSshDdos6_pm:b-52f8u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5851cc0867ad86146093a90344ccba3fb913a19/pkg/rpc/snappy.go#L165)):*
> ```Go
> 	chunkLen := binary.PutUvarint(dst[4:], uint64(v))
> 	dst[0] = chunkTypeDecompressedLength
> 	// chunkLen <= MaxVarintLen64, so it always fits in the first uint8.
> ```

The casual reader will trust this comment more if you included the actual value of MaxVarintLen64 for clarification.

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=knz

**Comment by nvanbenschoten** [comment]
bors r=knz

**Comment by nvanbenschoten** [comment]
bors r=knz

**Comment by knz** [comment]
lol

bors r+

**Comment by nvanbenschoten** [comment]
bors r=knz

**Comment by yuzefovich** [comment]
bors r=knz single=on

**Comment by knz** [comment]
bors r=knz
bors single on

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Pull request merged**
