### PR TITLE
opt: Use Optgen to generate the GenerateIndexScans rule

### PR DESCRIPTION
**Pull request by andy-kimball**
Previous PR's implemented the GenerateIndexScans rule manually, and also
made Optgen capable of generating explorer rules. This PR puts the two
together, and uses Optgen to generate code for the GenerateIndexScans
rule. This uncovered some bugs in Optgen, which this PR fixes:

- A custom replace function needs to return a slice of result expressions
  rather than trying to memoize them itself.
- The explore methods need to take an ExprID rather than a GroupID,
  because the methods needs to know the expression's ordinal within its
  group.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
> A custom replace function needs to return a slice of result expressions rather than trying to memoize them itself.

Can you expand on this? What was the problem? How will things work for rules that need to add expressions to different groups, or need to create new groups?

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24273#-:-L8gPwdc1N79YrOLXx0U:b-oq0m4l)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24273#-:-L8gtN9t184s9zMU-lnM:bnfp4nl)*

**Comment by andy-kimball** [comment]
Re: returning a slice of result expressions, the problem was that the custom function doesn't know the group of the pattern's root expression, so it can't add the new expression(s) to the group. The calling code does know it, though. So it gets back a slice of expressions, and then adds them one-by-one to the root group.

Explore rules should never be adding expressions to multiple groups - only the root group. They should never be directly creating new groups either. Rather, they use the factory to create sub-expressions, and the factory will end up creating new groups as a result.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24273#-:-L8h9FjREVs4OoHN48Xe:b-wf1ku6)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 588 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24273#-L8hByS84iPabOFP3Caa:-L8hByS84iPabOFP3Cab:bmzyof7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced3de25995af267ee546e72eba079890e77efb9/pkg/sql/opt/optgen/cmd/optgen/rule_gen.go#L588)):*
> ```Go
> 			g.genNestedExpr(rule.Replace)
> 			g.w.newline()
> 			g.w.nestIndent("for i := range exprs {\n")
> ```

I would add a testcase in `optgen/testdata/explorer` with a custom function to show the result of this (if it's not difficult).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24273#-:-L8hDDYU8eQA6OIwB0z4:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 588 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24273#-L8hByS84iPabOFP3Caa:-L8hFpvG5madSe7Ud6E3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced3de25995af267ee546e72eba079890e77efb9/pkg/sql/opt/optgen/cmd/optgen/rule_gen.go#L588)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would add a testcase in `optgen/testdata/explorer` with a custom function to show the result of this (if it's not difficult).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24273)*

**Comment by RaduBerinde** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24273)*

**Pull request merged**
