### PR TITLE
workload: add geo-distributed support to tpccbench

### LINKED ISSUE #25878: tpccbench: hook up distributed TPC-C load generation
https://github.com/cockroachdb/cockroach/issues/25087 and https://github.com/cockroachdb/cockroach/pull/25595 added support for running workload's TPC-C workload across a set of distributed load generators. However, it hasn't yet hooked it up in [`tpccbench`](https://github.com/cockroachdb/cockroach/pull/25310). We should hook this up and enable the `Geo` getting for tpccbench configs.

### PR DESCRIPTION
**Pull request by m-schneider**
This patch is adding support for a zones flag which will allow tpccbench
to benchmark over geodistributed clusters.

Closes #25878

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 2 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/cmd/roachtest/tpcc.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvEhYPDWCOEDS7mwKs:-LEvEhYQCNzUsK__bEyT:b4frj9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L115)):*
> ```Go
> 	nameParts := []string{
> 		"tpccbench",
> 		fmt.Sprintf("inNodes=%d", b.Nodes),
> ```

This is changing the test name. I don't think you meant to do that.

---

*[pkg/cmd/roachtest/tpcc.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvEkeo6lS0ANY26ls5:-LEvEkeo6lS0ANY26ls6:b-xgzxz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L127)):*
> ```Go
> 
> 	opts := []createOption{cpu(b.CPUs)}
> 	inNodes := nodes(b.Nodes+1, opts...)
> ```

`s/inNodes/nodeCount/`

---

*[pkg/cmd/roachtest/tpcc.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvF2eR9be2JzBFjKvF:-LEvF2eR9be2JzBFjKvG:ba3dfmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L150)):*
> ```Go
> 	ctx context.Context, c *cluster, b tpccBenchSpec, roachNodes, loadNode nodeListOption, zones []string,
> ) error {
> 	c.l.printf("here")
> ```

Remove.

---

*[pkg/cmd/roachtest/tpcc.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvFYT52lqyzf6u7oBL:-LEvFYT52lqyzf6u7oBM:bvplsqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L235)):*
> ```Go
> // can then be used during future runs.
> func runTPCCBench(ctx context.Context, t *test, c *cluster, b tpccBenchSpec) {
> 	roachNodeCount := c.nodes - 1
> ```

If we're not going to update this in the case of `b.Geo` then we should delete it so that it's not misused.

---

*[pkg/cmd/roachtest/tpcc.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvFh1dCOx5bH_eCU02:-LEvFh1dCOx5bH_eCU03:b-3yoe6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L237)):*
> ```Go
> 	roachNodeCount := c.nodes - 1
> 	roachNodes := c.Range(1, roachNodeCount)
> 	loadNodes := c.Range(c.nodes, c.nodes)
> ```

This didn't need to change.

---

*[pkg/cmd/roachtest/tpcc.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvGDPKAs3tGXGGTGA-:-LEvGDPKAs3tGXGGTGA0:b4qjix6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L253)):*
> ```Go
> 		loadNodes = nodeListOption{}
> 
> 		for i := 1; i <= c.nodes; i += nodesPerRegion {
> ```

This is nice, but we can be more aggressive here. The same logic works whether there is 1 zone or multiple, so let's use it regardless of `b.Geo`.

---

*[pkg/cmd/roachtest/tpcc.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvGW1uAtfFg9wbqyG3:-LEvGW1v7e6O4mdy5EyY:bg3yyvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L269)):*
> ```Go
> 		c.Run(ctx, c.Node(loadNodes[0]), fmt.Sprintf("./cockroach gen haproxy --insecure --host %s",
> 			c.InternalIP(ctx, c.Node(1))[0]))
> 		c.Run(ctx, c.Node(loadNodes[0]), "haproxy -f haproxy.cfg -D")
> ```

All of the load nodes need to be running HAProxy but the proxy itself should be partitioned. For now, let's not worry about this. I'd do the following in this block:
```
if len(loadNodes) > 1 {
    t.Fatal("distributed chaos benchmarking not supported")
}
loadNode := c.Node(loadNodes[0])
```

---

*[pkg/cmd/roachtest/tpcc.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvIhyS6Q31NG5lv-yI:-LEvIhyS6Q31NG5lv-yJ:b-s3jtz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3eddf8c8ff48e1ceca6a7bd0ec7494ffcf60103/pkg/cmd/roachtest/tpcc.go#L292)):*
> ```Go
> 			t.Status(fmt.Sprintf("running benchmark, warehouses=%d", warehouses))
> 			connStr := fmt.Sprintf("{pgurl:1-%d}", len(roachNodes))
> 			if useHAProxy {
> ```

What happened to this?

---

*[pkg/cmd/roachtest/tpcc.go, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvIGC-COK2-mbVIrvF:-LEvIGC-COK2-mbVIrvG:b-4ti8t1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L317)):*
> ```Go
> 			// aggregate tpmCs.
> 			var eg errgroup.Group
> 			tpmCs := make([]float64, zoneCount)
> ```

Why not use a channel for this?

---

*[pkg/cmd/roachtest/tpcc.go, line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvH3fyC7ZBilHg-XV-:-LEvH3fz5UN-Alaa7-74:bbhlurw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L320)):*
> ```Go
> 			for i := 0; i < len(loadNodes); i++ {
> 				// Copy for goroutine
> 				count := i
> ```

`count` is pretty ambiguous. `i := i` is probably better if you don't want a specific name.

---

*[pkg/cmd/roachtest/tpcc.go, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvIlYG3y2kN2ZGHNQi:-LEvIlYG3y2kN2ZGHNQj:bf7e5hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L357)):*
> ```Go
> 					fields := strings.Fields(statsLine)
> 					tpmCs[count], err = strconv.ParseFloat(fields[1], 64)
> 					if err != nil {
> ```

nit: `return err`

---

*[pkg/cmd/roachtest/tpcc.go, line 452 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvIC5O-YH0vzKaa_c9:-LEvIC5O-YH0vzKaa_cA:b-1f6n92) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L452)):*
> ```Go
> 			LoadWarehouses: 5000,
> 			EstimatedMax:   2000,
> 			Zones:          []string{"us-central1-b", "us-west1-b", "europe-west2-b"},
> ```

Move this right below `Geo`.

---

*[pkg/workload/tpcc/tpcc.go, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvHb00AgSGnLZDdvm3:-LEvHb00AgSGnLZDdvm4:bwuqp5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/workload/tpcc/tpcc.go#L430)):*
> ```Go
> 	startWarehouse := 0
> 	if w.affinityPartition != -1 {
> 		startWarehouse = w.affinityPartition * (w.warehouses / w.partitions)
> ```

This handles cases where `w.warehouses / w.partitions` is not a whole number correctly, right?

---

*[pkg/workload/tpcc/tpcc.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvI31L6Jqw5fRd_Sor:-LEvI31L6Jqw5fRd_Sos:b-52or5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/workload/tpcc/tpcc.go#L443)):*
> ```Go
> 			warehouse += startWarehouse
> 		} else if w.affinityPartition != -1 && p != w.affinityPartition {
> 			continue
> ```

Is this case needed anymore? Having a bit of trouble reasoning through all of this number mangling.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26654)*

**Comment by m-schneider** [comment]
*[pkg/cmd/roachtest/tpcc.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvFh1dCOx5bH_eCU02:-LFJdrqC-vHkSJcZTXEf:b-gghvdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L237)):*
> ```
> loadNode := c.Node(c.nodes)
> ```
Right.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26654)*

**Comment by m-schneider** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/cmd/roachtest/tpcc.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvEhYPDWCOEDS7mwKs:-LFJcR1W561zX1KctpQd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L115)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is changing the test name. I don't think you meant to do that.
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/tpcc.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvEkeo6lS0ANY26ls5:-LFJd4Jb5E7w-WCeOgZo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L127)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/inNodes/nodeCount/`
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/tpcc.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvF2eR9be2JzBFjKvF:-LFJdNZ3AYgcETHg7lxK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L150)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/tpcc.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LFJdmps80qa-8kM2w92:-LFJdmps80qa-8kM2w93:bjh8v8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3eddf8c8ff48e1ceca6a7bd0ec7494ffcf60103/pkg/cmd/roachtest/tpcc.go#L228)):*
> ```
> loadNode := c.Node(c.nodes)
> ```

---

*[pkg/cmd/roachtest/tpcc.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvFYT52lqyzf6u7oBL:-LFJhg5d75944MQvuJk4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L235)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we're not going to update this in the case of `b.Geo` then we should delete it so that it's not misused.
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/tpcc.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvGDPKAs3tGXGGTGA-:-LFJdvk64MhG9CKYO7in:b-dxcbts) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L253)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is nice, but we can be more aggressive here. The same logic works whether there is 1 zone or multiple, so let's use it regardless of `b.Geo`.
</blockquote></details>

Makes sense.

---

*[pkg/cmd/roachtest/tpcc.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvGW1uAtfFg9wbqyG3:-LFJeaENCR7GtU-bLvoO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L269)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

All of the load nodes need to be running HAProxy but the proxy itself should be partitioned. For now, let's not worry about this. I'd do the following in this block:
```
if len(loadNodes) > 1 {
    t.Fatal("distributed chaos benchmarking not supported")
}
loadNode := c.Node(loadNodes[0])
```
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/tpcc.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvIhyS6Q31NG5lv-yI:-LFJf2YuBpXhKzAGbLgp:b-xivh0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3eddf8c8ff48e1ceca6a7bd0ec7494ffcf60103/pkg/cmd/roachtest/tpcc.go#L292)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What happened to this?
</blockquote></details>

Automerge fail.

---

*[pkg/cmd/roachtest/tpcc.go, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvIGC-COK2-mbVIrvF:-LFJlYq74b6Gqa54sHKs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L317)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why not use a channel for this?
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/tpcc.go, line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvH3fyC7ZBilHg-XV-:-LFJedoj-2i1Tuxco1ds:b-4hvi0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L320)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`count` is pretty ambiguous. `i := i` is probably better if you don't want a specific name.
</blockquote></details>

Got it.

---

*[pkg/cmd/roachtest/tpcc.go, line 452 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvIC5O-YH0vzKaa_c9:-LFJfzbP9yzCbnj-M-yE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L452)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Move this right below `Geo`.
</blockquote></details>

Done.

---

*[pkg/workload/tpcc/tpcc.go, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvHb00AgSGnLZDdvm3:-LFJgz2MA2zTE65n1D7D:b-nmol8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/workload/tpcc/tpcc.go#L430)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This handles cases where `w.warehouses / w.partitions` is not a whole number correctly, right?
</blockquote></details>

Yes, it's integer division, if it's not a whole number the extra warehouses are tacked on to the last partition.

---

*[pkg/workload/tpcc/tpcc.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvI31L6Jqw5fRd_Sor:-LFJhGfg2sDcWQ50tmm9:bj529ag) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/workload/tpcc/tpcc.go#L443)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this case needed anymore? Having a bit of trouble reasoning through all of this number mangling.
</blockquote></details>

This is needed if we don't specify activeWarehouses.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26654)*

**Comment by nvanbenschoten** [comment]
:lgtm: as long as this doesn't break non-geo tests.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/cmd/roachtest/tpcc.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LEvEhYPDWCOEDS7mwKs:-LFU9o834d17CmJ6FFqb:bbadk3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4db13b7fc8e34289de09d4c5ca24266b6e497e0/pkg/cmd/roachtest/tpcc.go#L115)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think `Nodes` was lower-case. I'd change it back, otherwise the test names will look strange.

---

*[pkg/cmd/roachtest/tpcc.go, line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LFUm_wzES5He6BO33Bs:-LFUm_wzES5He6BO33Bt:b-lf43vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e926addb0f9ec34b26e342df53b87b317e6ff9/pkg/cmd/roachtest/tpcc.go#L234)):*
> ```Go
> // can then be used during future runs.
> func runTPCCBench(ctx context.Context, t *test, c *cluster, b tpccBenchSpec) {
> 	roachNodes := c.Range(1, c.nodes-1)
> ```

We're creating these just to overwrite them?

---

*[pkg/cmd/roachtest/tpcc.go, line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-LFUA9BiE9nOd6XnJXxf:-LFUA9BiE9nOd6XnJXxg:b-tgtmtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/48e926addb0f9ec34b26e342df53b87b317e6ff9/pkg/cmd/roachtest/tpcc.go#L244)):*
> ```Go
> 	}
> 
> 	zoneCount = len(b.Zones)
> ```

Does this work? Won't this be 0 for non-Geo cases?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-:-LFUmJcF0Qa8MR3BUMhw:b-py3dos)*

**Comment by nvanbenschoten** [comment]
I made a few tweaks to this to get it running, and it now seems to work great! I'm going to go ahead and merge so that we can continue making progress on this tool.

**Comment by benesch** [comment]
Billionth time is the charm?

bors r+

**Comment by m-schneider** [comment]
Reran all the tests locally and rebased.

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-:-LGQbgr1C4ZH3KqyQWJe:b-a0fior)*

**Comment by m-schneider** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26654#-:-LGQq8qN3W_eGR35wGAB:b-ydi9ay)*

**Pull request merged**
