### PR TITLE
roachtest: report health status during teardown

### PR DESCRIPTION
**Pull request by smg260**
roachtest: report health status of all nodes in teardown

In #102622, we changed how to determine if a node was suitable to connect to for post test validations, to first check a node's `health?ready=1` endpoint.  

This extends that PR by extracting the `http://node:port/health?ready=1` functionality, and using it to report on each node during teardown by logging the `status` and/or `body` or `error`. Finding a live node piggy backs of this information to create a connection to any node with `200` status.

This could be useful to add to `test_interface`

Epic: none
Release note: none

### CODE REVIEW

**Review by herkolategan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102636#-:-NVZOMj_Ar7yMsCAChg6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

___
*[`pkg/cmd/roachtest/test_runner.go` line 1106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102636#-NVZH8CH0yQyQD7vOK3y:-NVZH8CH0yQyQD7vOK3z:bxg4sg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6558c938d3fd250eb18c6d4814bb8c2343a86ae6/pkg/cmd/roachtest/test_runner.go#L1106)):*
> ```Go
> 		var validationNode int
> 		for _, s := range statuses {
> 			if s.Err != nil {
> ```

Nit: use of a switch or two continues might be cleaner / more go idiomatic like.
___
*[`pkg/cmd/roachtest/test_runner.go` line 1125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102636#-NVZKYGrDl9_z5-ms8hD:-NVZKYGrDl9_z5-ms8hE:b-po1oug) ([raw file](https://github.com/cockroachdb/cockroach/blob/6558c938d3fd250eb18c6d4814bb8c2343a86ae6/pkg/cmd/roachtest/test_runner.go#L1125)):*
> ```Go
> 		// not seem to be enough.
> 		//
> 		// TODO(testinfra): figure out why this can still get stuck despite the
> ```

Nit: Should we update this comment or is the issue mentioned still likely to happen (leave the comment for future ref)?

**Review by smg260 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102636)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/test_runner.go` line 1106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102636#-NVZH8CH0yQyQD7vOK3y:-NVZmk-Z9tMsipIY4QKa:bcxt7wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6558c938d3fd250eb18c6d4814bb8c2343a86ae6/pkg/cmd/roachtest/test_runner.go#L1106)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Nit: use of a switch or two continues might be cleaner / more go idiomatic like.
</blockquote></details>

Thanks. Updated to be more in line with style guide
___
*[`pkg/cmd/roachtest/test_runner.go` line 1125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102636#-NVZKYGrDl9_z5-ms8hD:-NVZmyFy1dKM2RDzxY-o:b-m2p5xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6558c938d3fd250eb18c6d4814bb8c2343a86ae6/pkg/cmd/roachtest/test_runner.go#L1125)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Nit: Should we update this comment or is the issue mentioned still likely to happen (leave the comment for future ref)?
</blockquote></details>

It is possible that the changes in this PR help, but I'd prefer to keep the comment there for now.

**Comment by smg260** [comment]
*[`pkg/cmd/roachtest/cluster.go` line 1427 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102636#gh-1195200309:-NV_CwE47z6lXxkTyy76:blhswrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/024c02df8be68bf3e06fda0fd4f71d65d410de46/pkg/cmd/roachtest/cluster.go#L1427)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Can't this entire block just be `results[node-1] = getStatus(ctx, node)`? The main blocking call in that function is `httputil.Get` which gets passed the same context.

If there _is_ a reason for not trusting context cancelation, we should document it.
</blockquote></details>

Yes it can, thanks. An early version used `http.Get` which did not accept a context.

**Review by renatolabs — APPROVED** [review]

**Comment by renatolabs** [comment]
Might be good to run a few roachtests on this branch before merging.

**Comment by smg260** [comment]
[TC job for this branch running a subset of roachtests](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10121593?buildTab=overview&showRootCauses=true&expandBuildChangesSection=true)

**Pull request merged**
