### PR TITLE
storage: expand documentation on versioning

### LINKED ISSUE #70046: storage: document min version file, cluster version relationship
Document the relationship between CockroachDB cluster versions, store cluster versions, min storage version, etc.

https://github.com/cockroachdb/cockroach/pull/70025#pullrequestreview-751703148

### PR DESCRIPTION
**Pull request by jbowens**
Expand the documentation on the relationship between cluster versions,
the store active cluster version, the storage min version file and
Pebble format major versions.

Fix #70046.

Release note: none

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
Nice. :lgtm: :thumbsup: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70371#-:-Mjox7Kj7Z5Fktn2YHHB:b-qk5c5k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70371#-:-Mk3rThx9dErv55iQThR:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jbowens)

___
*[pkg/storage/doc.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70371#-Mk3qY9pDQCG9bo9zQ2x:-Mk3qY9pDQCG9bo9zQ2y:bgcr2yx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46dedbecddf757938f2b6ccf0ac9f438b83f4d8/pkg/storage/doc.go#L148)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> Since this ratcheting is not
> atomic with the persistence of the `STORAGE_MIN_VERSION` file, Pebble
> re-sets the min-version on store open, ensuring that the storage engine
> is using the same format dictated by the `STORAGE_MIN_VERSION` file.
> ```
</details>


Can you elaborate on this with an example where a failure happens after the min version file is written but the Pebble major version has not yet been updated.
And add that therefore `SetMinVersion` should expect repeated calls that don't actually rachet the min version, but it must do the mapping to the Pebble format major version and call into Pebble, in case Pebble has not yet updated its major version.

**Review by jbowens — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70371#-:-Mk89wh60h8XIGOwHYI-:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @nicktrav and @sumeerbhola)

___
*[pkg/storage/doc.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70371#-Mk3qY9pDQCG9bo9zQ2x:-Mk89v1s1zUNzM9dXt6s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46dedbecddf757938f2b6ccf0ac9f438b83f4d8/pkg/storage/doc.go#L148)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
> Since this ratcheting is not
> atomic with the persistence of the `STORAGE_MIN_VERSION` file, Pebble
> re-sets the min-version on store open, ensuring that the storage engine
> is using the same format dictated by the `STORAGE_MIN_VERSION` file.
> ```

Can you elaborate on this with an example where a failure happens after the min version file is written but the Pebble major version has not yet been updated.
And add that therefore `SetMinVersion` should expect repeated calls that don't actually rachet the min version, but it must do the mapping to the Pebble format major version and call into Pebble, in case Pebble has not yet updated its major version.

</blockquote></details>

Done.

**Pull request merged**
