### PR TITLE
build: add connection_latency roachtest to nightly

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note: None

Adding roachtest added in https://github.com/cockroachdb/cockroach/pull/62166 to the nightly roachtest build.

The goal is to add the output from these benchmarks to roachperf.

### CODE REVIEW

**Comment by RichardJCai** [comment]
Requesting review from @rickystewart @stevendanna @adityamaru 

Also is there some sort of test to make sure this is added correctly?

**Review by rafiss — APPROVED** [review]
lgtm! but perhaps someone from dev-inf should confirm

**Review by rickystewart — APPROVED** [review]
Not sure if we want to do a one-off nightly run to verify this -- the change looks fine -- but let me know if you still want to, I should be able to kick one off.

**Comment by RichardJCai** [comment]
> Not sure if we want to do a one-off nightly run to verify this -- the change looks fine -- but let me know if you still want to, I should be able to kick one off.

Thanks @rickystewart ! no need to do a one-off, I'll just spot check it once it runs.

**Comment by RichardJCai** [comment]
bors r=rickystewart

**Comment by jlinder** [comment]
Is this meant to be run in AWS or in GCP? This change will make it run in AWS. If it's meant to run in GCP, it will run there automatically without any changes to this file.

**Comment by RichardJCai** [comment]
Don't necessarily need to run this on AWS so I'm bors r- for now.
Thanks @jlinder

**Pull request closed without merging**
