### PR TITLE
util/tracing: stringify a recording

### PR DESCRIPTION
**Pull request by andreimatei**
This is super useful for debugging tests - recording a trace and then
printing the recording when badness happens.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40740#-:-LoeJ0OF1hbNhve_8PGF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by andreimatei — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40740#-:-LqmORFi3sfzqiqvgUFN:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40740)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/util/tracing/tracer_span.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40740#-Lqq7FGy9ahAlp41zAr5:-Lqq7FGy9ahAlp41zAr6:bszrs7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ad7bb1a1439e45ee747f1329af25f139de25117/pkg/util/tracing/tracer_span.go#L229)):*
> ```Go
> }
> 
> // Recording represents a group of RecordedSpans, as returned by GetRecording.
> ```

seems pretty similar in spirit , though much different in implementation, to FormatRecordedSpans. can we have a comment on each explaining when you would use one or the other?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40740)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz)

___
*[pkg/util/tracing/tracer_span.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40740#-Lqq7FGy9ahAlp41zAr5:-LqqDEg96kQu9NJIvF5r:b-hyp6u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ad7bb1a1439e45ee747f1329af25f139de25117/pkg/util/tracing/tracer_span.go#L229)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

seems pretty similar in spirit , though much different in implementation, to FormatRecordedSpans. can we have a comment on each explaining when you would use one or the other?
</blockquote></details>

Hmm I forgot about `FormatRecordedSpans`. I'll revert this one and rename `FormatRecordedSpans` to `Recording.String()`.

**Pull request merged**
