### PR TITLE
sql: track attempts to use unimplemented features

### PR DESCRIPTION
**Pull request by dt**
currently only the parser-thrown unimplemented errors are captured, but that alone covers quite a few,
and a follow up can add the errors returned by planNode evaluation by making those returned the tagged error type as well.

### CODE REVIEW

**Comment by dt** [comment]
Some of the callsites in sql.y are still stubbed out with empty strings -- I started trying to fill all of them but then opted to wait since a) I assume there's some bike shed painting to do over format of those strings b) I wasn't exactly sure what a couple actually were.

**Comment by knz** [comment]
This looks good overall. However while you are at it you could equip the unimplemented error with the right pg error code, `CodeFeatureNotSupportedError`.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/parse.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16082#-KkpuCBWAAzXxd4k6R-O:-KkpuCBXzsk9Y4LZTH9P:b6jej8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/670e8bcb24e5473c2217283957b5b14c2fdd9e15/pkg/sql/parser/parse.go#L75)):*
> ```Go
> // The `UnimplementedFeature` method returns some short string uniquely
> // identifying the feature or functionality in question.
> type UnimplementedFeatureError interface {
> ```

Just curious: why an interface instead of exposing the struct directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16082#-:-KkpumBg7qzeyJfTs1fM:b-ai4mzw)*

**Comment by dt** [comment]
Done.

I switched away from a wrapper / interface and just pass a pgerror.Error around instead with the appropriate code.

---

Review status: 6 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/parse.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16082#-KkpuCBWAAzXxd4k6R-O:-Kkq83_JGBlC8hTGcCD2:b-lwe58) ([raw file](https://github.com/cockroachdb/cockroach/blob/670e8bcb24e5473c2217283957b5b14c2fdd9e15/pkg/sql/parser/parse.go#L75)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Just curious: why an interface instead of exposing the struct directly?
</blockquote></details>

I was thinking it'd be nice not to be tied to a single, concrete type, but ended up going with pgerror.Error instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16082#-:-KkqhA1IyCCrxW29eN-G:b-e0o9tp)*

**Comment by knz** [comment]
LGTM modulo regenerating the necessary protobuf.

Kind request: for the missing features in sql.y please file a follow-up issue. Also preferably replace the empty strings by the name of the non-terminal like you already did elsewhere.

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16082#-:-KkpvB8P3VJAb28DMnpa:b-lt6g0d)*

**Comment by dt** [comment]
what do you mean by the missing features?

and all the empty strings were just in comments, not live code, so I've simply reverted my changes I them for now -- 
if/when someone wants to uncomment and modify them, if they're keeping the `unimplemented`, the compiler will ensure they fill it in with an appropriate value.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16082#-:-KkvG6N6NCniqN5RWb5Z:bins5u0)*

**Comment by knz** [comment]
:lgtm:
thanks :)

---

Reviewed 5 of 5 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16082#-:-KkwP23HS_KzKpHu7nlr:bf5cdkd)*

**Comment by dt** [comment]
This is decidedly *not* a bug fix, but it might be nice to have the a few more months of this info collected when prioritizing upcoming features... do we want to cherry-pick into a point release? /cc @knz @petermattis

**Comment by knz** [comment]
I'm +1 on the idea

**Comment by dt** [comment]
If we *do* want to cherry-pick it, since it does include some non-essential refactoring, I guess I'd vote `1.0.3` rather than immediately, just so it has a little more time to bake.

**Comment by petermattis** [comment]
Seems a bit big for a cherry-pick. Do unimplemented bits of the SQL grammar get completely ignored by the statement tracking (before this change)?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16082#-:-KlU5uxtj9XFygxOa66Y:b-mamt59)*

**Comment by dt** [comment]
correct, we can only include statements we can parse in statement tracking, because we need to parse it to know how to redact it.

**Pull request merged**
