### PR TITLE
cli/debug: allow the user to refine which files get included

### LINKED ISSUE #54654: debug.zip an option to limit what logs files are included
**Is your feature request related to a problem? Please describe.**

an option to not grab all of the log files that would reduce the size would facilitate troubleshooting exchange with customers.  It is common to see 1GB to 10GB debug zip files in the field.  Uploading this on Zendesk, GitHub or other methods requires hours and often fails due to the sheer size.  The typical config that results in the large debug.zip are:
 
- [default log rentetion](https://www.cockroachlabs.com/docs/v20.1/debug-and-error-logs) increased to a larger size to retain more historical log for troubleshooting
- a large number of nodes (more than a dozen)

**Describe the solution you'd like**

An option to limit what logs files are included (perhaps with more recent logs)

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by knz**
First commit from #64071.
Fixes #54654.

We have observed in practice that the majority of the size of
generated `debug zip` outputs is attributable to the discrete files
retrieved from the server:

- log files
- goroutine dumps
- heap profiles

As clusters get larger and older, these files increase in number, and
the size of the `debug zip` output grows accordingly.

Meanwhile, in practice, there are many support cases where we know
ahead of running the `debug zip` command that only certain files are
going to be useful. Therefore, we wish to be able to restrict
which files get included / excluded from the generated archive.

Hence the functional change described below.

(Note: there is another expressed wish to limit the size of generated
archives based on a *time or date range*, not just file names /
types. This will be handled in a separate commit.)

Release note (cli change): It is now possible to fine tune which files
get retrieved from the server nodes by the `debug zip` command, using
the new flag `--include-files` and `--exclude-files`. These flags
take glob patterns that are applied to the file names server-side. For
example, to include only log files, use `--include-files='*.log'`.

The command `cockroach debug list-files` also accepts these flags and
can thus be used to experiment with the new flags before running the
`debug zip` command.

### CODE REVIEW

**Comment by knz** [comment]
cc @thtruo

**Review by stevendanna — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64094)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64094#-MYxYfYF-gMKKauzQlZs:-MYxYfYF-gMKKauzQlZt:bt7aspz) (no related file):*
First commit reviewed over at #64071, apologies for not doing it all here.

Thanks for adding the missing tests!

This looks like a useful addition. I think the only blocker is the function name changes I mentioned in #64071 to get this building again.

---
___
*[pkg/cli/zip_per_node.go, line 388 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64094#-MYxbnFP1mEXGAZyWv49:-MYxbnFP1mEXGAZyWv4A:bsy6i3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1abc6c56e001cdb653f2ba7b97f9e3cef8e226a/pkg/cli/zip_per_node.go#L388)):*
> ```Go
> 				if err := zc.z.createRaw(nodePrinter.start("writing dump"), name, file.Contents); err != nil {
> 					return err
> 				}
> ```

It feels like there might be some room for a helper function or two in this file that would reduce some of the code duplication. But, that looks true of the existing code as well.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64094)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/64094#-MYxYfYF-gMKKauzQlZs:-MYy9suJ1a0C78QN6mYu:b-qx7pk8) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

First commit reviewed over at #64071, apologies for not doing it all here.

Thanks for adding the missing tests!

This looks like a useful addition. I think the only blocker is the function name changes I mentioned in #64071 to get this building again.




</blockquote></details>

Thanks this seems to build now.

---
___
*[pkg/cli/zip_per_node.go, line 388 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64094#-MYxbnFP1mEXGAZyWv49:-MYy9gJs3mVQs7FZUiLb:b12qr1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1abc6c56e001cdb653f2ba7b97f9e3cef8e226a/pkg/cli/zip_per_node.go#L388)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

It feels like there might be some room for a helper function or two in this file that would reduce some of the code duplication. But, that looks true of the existing code as well.
</blockquote></details>

This is going to be complicated until go provides us with generics. Every one of these blocks has a different mix of types and function signatures.

**Comment by knz** [comment]
@tbg reviewed this in https://github.com/cockroachdb/cockroach/pull/64128#pullrequestreview-644382879

Addressing these comments here: https://github.com/cockroachdb/cockroach/pull/64128#pullrequestreview-644547587

**Pull request merged**
