### PR TITLE
roachprod: rewrite `roachprod start`

### PR DESCRIPTION
**Pull request by irfansharif**
This is quite the workhorse, and does a lot and has to be compatible
with a lot of existing CRDB versions. It's grown organically as a result
and I'm finding it a bit difficult to maintain, breaking it down a bit
makes it clearer what the structure of it all is and would've perhaps
prevented me introducing bugs like #51497.

Do scrutinize the PR closely, we use `roachprod start` everywhere. It's
mostly mindless code movement but it's pretty fragile code.

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
I've tested this with a few versions manually, but I also did that before and things still slipped through the crack. How do I make sure this is not breaking things any further?

**Comment by irfansharif** [comment]
Feel free to reject this PR, I'm more than happy to send out a more targeted patch and leave things as is if this is too controversial.

**Review by petermattis — COMMENTED** [review]
> Feel free to reject this PR, I'm more than happy to send out a more targeted patch and leave things as is if this is too controversial.

I'm not going to have the time to properly review this patch this week. So if there is something that needs to be fixed soon, a more targeted patch would be useful. That said, `start` has evolved over time and I can see the benefit in doing a clean slate rewrite. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51790#-:-MCs9Nw5EkeHnDsPersM:bmv6lzr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @petermattis)

**Comment by irfansharif** [comment]
Thinking about this a bit more, the targeted patch would have the same code block movements, this just packages it better, so I'm happy waiting (perhaps @knz may disagree). Tagging @jlinder for dev-inf eyes.

**Comment by knz** [comment]
I'm good with reviewing this (even the complex form), just today I'm a bit swamped. Will get to this soon.

**Comment by nvanbenschoten** [comment]
This is pretty tough to review. Is there really not a more targetted patch that we could pull out that addresses the issue without rewriting everything at the same time? Or can we split the rewrite into a separate commit so that we aren't "sneaking in the fix for #51497"? I have a hard time even finding where that logic change is in this.

**Comment by irfansharif** [comment]
Hm, ok, let me re-work this. I'll break this up so it's clearer where the code movement is happening.

**Comment by irfansharif** [comment]
PTAL, I'm keeping this PR focused on just the re-write, and outlining in comments what the current problems are without actually addressing them. I'll get to those after.

**Review by nvb — APPROVED** [review]
:lgtm: thanks for splitting this up! It made it much easier to review.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51790#-:-MCxiYJR6QzgQrC0xSq4:b-cxlpon)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif, @jlinder, and @knz)

___
*[pkg/cmd/roachprod/install/cockroach.go, line 520 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51790#-MCxgkAzDe6qm50ZONwS:-MCxgkB-2udfTKS6rikD:b-nww3ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/87a76948e4d1905d07dd2b6a8618b2194dd34f1c/pkg/cmd/roachprod/install/cockroach.go#L520)):*
> ```Go
> 	for i, vpc := range h.c.VPCs {
> 		if i > 0 && vpc != h.c.VPCs[0] {
> 			advertisePublicIP = true
> ```

`return true` and `return false` below?

**Review by irfansharif — COMMENTED** [review]
Thanks for the quick turn around! Going to just blaze ahead to catch nightly failures tonight (hopefully this adds nothing more than already present).

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51790#-:-MCxjiyM19M09d13ZkOf:b-ivlj4b)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jlinder, @knz, and @nvanbenschoten)

**Pull request merged**
