### PR TITLE
sql, opt: add generic plans to prepared statements and plan cache

### PR DESCRIPTION
**Pull request by michae2**
Epic: CRDB-37712

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
(This needs tests, and it would be nice to cache the plans separately, but I think the basic idea is there.)

**Review by mgartner — COMMENTED** [review]
Great start!

What would be the benefit of caching the plans separately?

I think the rough order of operations should be:

1. Fetch the cache entry for the query or prepared stmt.
2. Determine if we will use a custom or generic plan. Just use the "force" modes for now. In the future, the cache entry can contain all the information we need to make the decision for "auto".
3. If we have the correct type of plan and it is not stale, use it.
4. If not, build the correct type of plan and cache it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125919#-:-O-q1CP73qTID9a_FYTC:bab2n0p)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/plan_opt.go` line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125919#-O-pzGoaARlciclBELcl:-O-pzGoaARlciclBELcm:b-lbv1cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2730f16aadb61ada981e1eb901c70bdf12d1c354/pkg/sql/plan_opt.go#L419)):*
> ```Go
> func (opc *optPlanningCtx) buildReusableMemos(
> 	ctx context.Context,
> ) (customMemo, genericMemo *memo.Memo, _ error) {
> ```

I don't think we'll ever want to build both a custom and a generic memo at the same time, so maybe this function should take an option for the type of memo to generate.
___
*[`pkg/sql/plan_opt.go` line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125919#-O-q16KtDgtyw-RWI6AE:-O-q16KtDgtyw-RWI6AF:b-o09hm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2730f16aadb61ada981e1eb901c70bdf12d1c354/pkg/sql/plan_opt.go#L528)):*
> ```Go
> // The returned memo is only safe to use in one thread, during execution of the
> // current statement.
> func (opc *optPlanningCtx) reuseMemo(
> ```

nit: maybe we rename this to `reuseCustomMemo` since this function should not be called on generic memos.
___
*[`pkg/sql/plan_opt.go` line 537 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125919#-O-q0qLW1IqT3eHcHcx4:-O-q0qLW1IqT3eHcHcx5:b-ocjdsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2730f16aadb61ada981e1eb901c70bdf12d1c354/pkg/sql/plan_opt.go#L537)):*
> ```Go
> 		//
> 		// Is this where we would tap into? But we don't have placeholders filled in
> 		// completely, so we need to do something like that, right?
> ```

I don't think anything here needs to change—looks like you added the placeholder replacement logic in execbuilder :+1: 
___
*[`pkg/sql/plan_opt.go` line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125919#-O-q0Q0J6EV1aRDNgLmw:-O-q0Q0J6EV1aRDNgLmx:ba7eihh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2730f16aadb61ada981e1eb901c70bdf12d1c354/pkg/sql/plan_opt.go#L601)):*
> ```Go
> 		cachedData, ok := p.execCfg.QueryCache.Find(&p.queryCacheSession, opc.p.stmt.SQL)
> 		if ok {
> 			if isStale, err := cachedData.CustomMemo.IsStale(ctx, p.EvalContext(), opc.catalog); err != nil {
> ```

We'll need a stale check for the generic memo too.
___
*[`pkg/sql/prepared_stmt.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125919#-O-q-f-j65V4NVGNrjZc:-O-q-f-j65V4NVGNrjZd:b-dt338e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2730f16aadb61ada981e1eb901c70bdf12d1c354/pkg/sql/prepared_stmt.go#L66)):*
> ```Go
> 
> 	// GenericMemo is the fully-optimized memo constructed by the optimizer during
> 	// prepare of a SQL statement. (If the CustomMemo is already fully-optimized
> ```

nit: We won't construct the generic memo at prepare time. Instead it'll happen at execute time. The original RFC said the opposite.

**Review by michae2 — COMMENTED** [review]
Thanks for looking!

> What would be the benefit of caching the plans separately?

If we're always forcing one way or another it would be nice not to use the memory for both memos. (But being lazy about building the generic memo helps with this. And it seems difficult to avoid building the normalized / custom memo during prepare, even if we don't build the generic memo. So maybe caching them separately will be impossible.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125919#-:-O-rT38M0a4zQxxqIhzf:b-ge37l1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/prepared_stmt.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125919#-O-q-f-j65V4NVGNrjZc:-O-rKbFHAy01NPQv-xDM:b-szgw0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2730f16aadb61ada981e1eb901c70bdf12d1c354/pkg/sql/prepared_stmt.go#L66)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: We won't construct the generic memo at prepare time. Instead it'll happen at execute time. The original RFC said the opposite.
</blockquote></details>

I see, ok. I can make this lazier, and only compute the generic memo at execute time as needed.

**Comment by mgartner** [comment]
> If we're always forcing one way or another it would be nice not to use the memory for both memos.

It'd only save an extra byte per entry for the pointer to the unused memo, right?

**Comment by michae2** [comment]
Closing this in favor of https://github.com/cockroachdb/cockroach/pull/126528

**Pull request closed without merging**
