### PR TITLE
sql: ensure application_name is correctly reset during SET LOCAL

### PR DESCRIPTION
**Pull request by otan**
See commits for details.

Refs: #69391

Release justification: fix for new functionality

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/conn_executor_exec.go, line 838 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69552#-MiJt26m5YjsN_7N3ulK:-MiJt26m5YjsN_7N3ulL:b-374fgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/13377252c8b845931842d39fc815427f6ef14b0e/pkg/sql/conn_executor_exec.go#L838)):*
> ```Go
> 	}
> 	if ex.dataMutatorIterator.paramStatusUpdater == nil {
> 		return nil
> ```

i think it's no longer safe to short-circuit here

**Comment by otan** [comment]
___
*[pkg/sql/conn_executor_exec.go, line 838 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69552#-MiJt26m5YjsN_7N3ulK:-MiJteqN57u9z382VBFU:bu5vs1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/13377252c8b845931842d39fc815427f6ef14b0e/pkg/sql/conn_executor_exec.go#L838)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think it's no longer safe to short-circuit here
</blockquote></details>

let's see what fails!

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/conn_executor_exec.go, line 838 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69552#-MiJt26m5YjsN_7N3ulK:-MiJuE_v7D6Q7k0pWi8y:b-uagszs) ([raw file](https://github.com/cockroachdb/cockroach/blob/13377252c8b845931842d39fc815427f6ef14b0e/pkg/sql/conn_executor_exec.go#L838)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

let's see what fails!
</blockquote></details>

oh well i just meant maybe we should move  the new `ex.dataMutatorIterator.onApplicationNameChange(after.ApplicationName)` call so it happens before this short-circuit

but if we can remove the short-circuit entirely that's fine too!

**Comment by otan** [comment]
looks fine

**Review by rafiss — APPROVED** [review]

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
