### PR TITLE
ui: add webpack visualizer

### PR DESCRIPTION
**Pull request by couchand**
The [Webpack Visualizer](https://github.com/chrisbateman/webpack-visualizer) is a tool to collect bundle statistics and prepare a sunburst chart showing the size of the various pieces of the codebase.

This will help us keep track of our bundle size, monitor new dependencies, etc.

For example, this is what it looks like today for a CCL build:

screen shot 2018-11-14 at 3 12 46 pm

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
Cool!

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32358#-:-LRIvkzJDY7z3M-Fgbnp:b-89q77x)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 1210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32358#-LRIuki24ybMCy98H_U0:-LRIuki332kK18wV1Uz-:b765dh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7247c9631bd8b7e1d79d2609ff0f2ca5d1c1d36/Makefile#L1210)):*
> ```Makefile
> ui-stats: pkg/ui/yarn.opt.installed
> ui-stats: $(UI_CCL_DLLS) $(UI_CCL_MANIFESTS) $(UI_JS_CCL) $(shell find pkg/ui/ccl -type f)
> ui-stats: $(UI_OSS_DLLS) $(UI_OSS_MANIFESTS) $(UI_JS_OSS)
> ```

This line and the line above it are both redundant if you're going to depend on bindata.go (below). Plus introducing a `$(shell find)` has nontrivial overhead, so if for some reason you do need to duplicate prerequisites here please extract them into a shared variable so that the `$(shell find)` is only invoked once.
___
*[pkg/ui/webpack.app.js, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32358#-LRIvQsJAEHv2YGYTF7r:-LRIvQsJAEHv2YGYTF7s:bksy7iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7247c9631bd8b7e1d79d2609ff0f2ca5d1c1d36/pkg/ui/webpack.app.js#L129)):*
> ```JavaScript
>       new CopyWebpackPlugin([{ from: "favicon.ico", to: "favicon.ico" }]),
>       new DashboardPlugin(),
>       Visualizer && new Visualizer({ filename: "./stats.html" }),
> ```

If this visualizer is fast enough to be essentially free, I'd be in favor of making it a required dependency to avoid the additional build system complexity. `go-bindata` supports an `-ignore` flag so that it wouldn't actually get included in the binary. (Or just generate the HTML file somewhere besides the `dist` folder.)

**Review by couchand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32358)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 1210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32358#-LRIuki24ybMCy98H_U0:-LRIwpbe5miJkuD0JBRY:b-bcdjiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7247c9631bd8b7e1d79d2609ff0f2ca5d1c1d36/Makefile#L1210)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This line and the line above it are both redundant if you're going to depend on bindata.go (below). Plus introducing a `$(shell find)` has nontrivial overhead, so if for some reason you do need to duplicate prerequisites here please extract them into a shared variable so that the `$(shell find)` is only invoked once.
</blockquote></details>

I was hacking around and having some trouble with getting the target to run without explicitly duplicating all the deps, but obviously I was doing something wrong.  Will fix.
___
*[pkg/ui/webpack.app.js, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32358#-LRIvQsJAEHv2YGYTF7r:-LRIwTAwACSyGpeYOilq:bokpcnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7247c9631bd8b7e1d79d2609ff0f2ca5d1c1d36/pkg/ui/webpack.app.js#L129)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

If this visualizer is fast enough to be essentially free, I'd be in favor of making it a required dependency to avoid the additional build system complexity. `go-bindata` supports an `-ignore` flag so that it wouldn't actually get included in the binary. (Or just generate the HTML file somewhere besides the `dist` folder.)
</blockquote></details>

That probably makes sense.  It seemed at first to fall into the same group as the webpack dashboard, but I remember now that that had some cross-platform nastiness that definitely won't apply to this.  Since it hooks into stats that webpack is collecting anyway, I think it's "basically free".

I'll rejigger this and ping you when it's updated.

**Review by couchand — COMMENTED** [review]
Definitely simpler now.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32358#-:-LRJ-pIu5weW5C1U8EpI:ba79i09)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32358#-:-LRJBanY5CqgnjHvbp2G:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by vilterp — COMMENTED** [review]
Cool! 🎉 

Could you add a note to `pkg/ui/README` about how to use it? (I.e. "run `make` and open this HTML file")

**Comment by couchand** [comment]
> Could you add a note to pkg/ui/README
Done.

bors r+

**Pull request merged**
