### PR TITLE
scrun: added a cluster setting to skip planner sanity checks in prod

### LINKED ISSUE #91528: sql/schemachanger: declarative state generated on gc_job_mixed is not backwards compatible
The mixed version corpus validation test for gc_job_mixed encountered a potential state that is not backwards compatible between master and 22.2. As a result when we attempt to plan on this state generated on a mixed version state from master:

`failed to validate TestLogic_gc_job_mixed_TestLogic_gc_job_mixed_DROP TABLE db.kv_0 with error [[Column:{DescID: 108, ColumnID: 1}, ABSENT], ABSENT] should not yet be scheduled for this stage, ERROR: [[Column:{DescID: 160, ColumnID: 1}, ABSENT], ABSENT] should not yet be scheduled for this stage
SQLSTATE: XX000
DETAIL: dependencies graphviz: https://cockroachdb.github.io/scplan/viz.html#H4sIAAAAAAAA/+xc727juBH/HD+F4AJFe9juWv+lXmIgG2fbPbRJEGfRD8HBoEXGZleWVIrabK5Y4F6rfZx7kkKiTVmMbFMWrTjFfow4nOH8ZjicGdKBeEZAMte0f/dO0mzK/gjCLKWITFI9/1zz3Sy+n4RgisKzfkoBRQsU0bT/Y/45su4f4oim+Bd01vf7bxjZ6SkF0xBpQQjS9KwfZxSR/vCUkuEphauvcwRg/jkNkunb8Yrv6TsKh6fvCtKCfFjlVfzBeQ1vEQQBRVCYT+FwdHt9o43O787fn48vtd9+/Q/87df/ahfn44vz0eVzKbsYQImpd2BWP3ttzrtCgWH5pbf61Bu+SecgQWf9KI5Q/+cC397JybdasxgVs1BAZojbxG5tkx8Ko1yBBUoTEKCGRoEoDQhOaEw+Qg6IbnvP2URggTgF3B+myFGk8vVjhMjB1I1L7hQOSRzTFiq7ilT+lCJyQ/AXHKIZSg+meyKIoHBoPKfKUkSu1p0CwAWOWqDkvX6UBlYN4TOgkmwa4qAFUv7rR0oCppabTh8oQmkEKJiCtHFoXU7biE5jhXTFCt3GIRojSnE0U63bko7EIarYdDJJQhCgeRxCRCb58CQ/WCaTNrgYL32ISqKxYcf4Ow7b1uFCN4/vyK1Runrktj1N9Pbp7uGCZI32L3To6qoy0JeDydadLg5dXVXietwO1fbUVZXrjoM5WoCG6OD0Zs3MFA4pyWqieVrw3ghgY51VZa5M5xtAmlfXSTFpJHkSqQZAVUL6MiewM9hxAlN7MHD8SY03KgbSUJWzqjup68BRWhwbqtLaA8TVOuVf6KA2VGW5xw1TW2dSlere5RMaglP8uRGXxqqoSmCvp/9EAd3rVImLqTtNXbAeKw6FqhLTizjMFtEHsMDhU0P1q2UYwQtAalgoNruqNJPp3VDjoJi0rkyNuWfnlBI8zSi6yhbbKBUjoyq1ZMiUYUcpOhWf+XpwTFSlngyTu6fkEJjg9CoLwzKibkzMt4OzIuKL3LW2h7VNT+HwY0Q3hYEYl0KNGpmPGNI5p3CsbSZrbkRV6bOaLV9zTOP0rxhCFO0w34bIUMNQ7S4wVaXN6iJDjc5RNc95xPDguKhKrdVFh8a+8P+66U1V+TyzzQg9gCykl18TgtIUx4eIAuhrUlZ9WYT/laFJ4cd/+OPBPVlVXq8mRFpvDd/yHdfwbfT731nmj4OaBpxk0MTp+CmlaLG+sqYRVmo9ii2iqjxRF3OlUKhE4YDA6QRHFJEIhJPFlyCYULxAKQWL5OAAqi1wVARnSbc+imRuhAK8AKFMbNfdwVZDNTfdcdVopdmsI4tGW9ajeDMdX20ohUK1zZxzjDtIC4+vaJR04aOIPNcYSmWUjtqYo6pI/BhB9PVwlWLOfXs3QK0zW6pqP4W41LVAduPyGUfl+Pju+vZydHDwVBWIN6w5WmDYGL0opQTgiLZGEKefiqqkVXhojKGqQq4Ab4+TRwKY2tvMSfIZHbqdvXwUvXz7DFHCHj5Hlnm//Db48/n78eXVHZsQ2dZqQBdHbD6iCyMuHzGEEWdtZHR7fXNzOVoNeXzIFCb5fMSqjjgDPmILIzofcYQRg4+4wkipqieMmGsj1WU7JQp+dZJVshO4cRAMAVKHA2eIczg6hgCpw9ExBNxcjo4h4OZydAwBN5ejYwi4uRwDQ8DN5YoaAm4uB8cQwSlHhCkcHFMAx+XgmAI4LgfHFLlxcEwBHI+DYwrgeBwcUwDH4+CYAjgeB8cUwLFKfYQBro4g3+JrFsRbXjkg7B2ujLAum+siLMvmqggms7kmvrh1/zTMd3bb2Hr/cxrEydvrmnp+a1Qd8AD4Q8Hgb/Hs8svqBrW3c/plWP2Jylbi9bdOO6P9YZ441XxZaZJr/Z6/f961vvOMzmOCfwGUNyF3TfnU9BEAx03ZT4lkfg+0nHNX/IDn74gCCKik0cZxRgK09ImPo20J9Dib/iMmn9eI9P3sxtaZa5iVTzDYFpOZrgv+P0IhomjE339I7oNywrpGTX1xLclYjw76PSAkfsy3+lkfYrCII9h/E8RhTM76BMFVwOiXz1Y0SOJEI3g2p9oUPcQEaRAlKIIoohpiBtIIWsRfQFiJREaHsswOZVkdyrI7lOXeb+e7PNE0HGmUgCgFQR6wVjLqOHrdrd5Rg1TBGUezNaGPmM41QCnRCHrgiWgu0t1D5HLpzTQsxLmDbsXt4+YtxHULprdPcNpPnJm7Svurn9eQld1VOo0qX/59T7ZeItkyX0+ydUEQoOgvFz/F0w8xKR1xt4dzkD/EZETi5Kd4KonaHr+q3wJHvh9G+++HZwlfEXhsv5MjmAW5fQ6ofWV1k8gyWd0ksquDQl0Sxjh2k0IyWU6HsrpJLpmsDneR26Fnux16tttNicZkdejzboc+73bo826HPu91eHJ4He4vryOf91g1Wst3OTVlcxBcMWVXsPyKoi0HV2clagsORmsOphoO0lGRzdXoU7JmpFJCxYhrtPzuhZXZLZbrtObgsdq7BQe/LQdv0NZsBQfPaMahuATmN0pt/b/g0GoJZksGVm5Kq/2bl9fQaKj+g5ld1M3/r8z3dsNLtBtqnmG8jnZDxR0lbnhW/jja4I/H0ZnYCIZx0IuuhhvzWd+DxcFuMi8mq5sLISarm8qGyeqmsmGy9mn/7yvLV9hjKTja3dQvTJaa+kXyoouJVFN2NhKppvqUE9k7+dY76Z1ENgscS8Y01pbPa96k9ClEZ30I0jmCxZzIYRtfitZlG1eKdrnxpGh9tnGkaPU8RS7fJ+0g1plTyxEbzCvliE32MkCO2GJX+3LENrublyNeXq7LEef2syVtoi83jByxz1xditgYsB67HLHOmuRyxAbrcssRFw1RSaMYFutAyxHbrIUsR+ywik2O2GUNYzlij3V85Yh9VrtKEZsD1t+VI9ZZK0KO2GAdVjlik3UN5Igt1k+VI7ZZQ1SO2GGNAzlil7U/5Yg91r+UI/ZZA1KK2BqwDqIc8bIlIEdssH6hDHHvW+9/AQAA//+FBjL+71wAAA==
HINT: You have encountered an unexpected error.`

We need to root cause and identify the first post commit phase in this plan has a non-plannable state on 22.2

For manual reproduction fetch the corpus:

1. gsutil cp gs://cockroach-corpus/corpus-mixed-master/corpus .
2. ./cockroach debug declarative-corpus-validate corpus # This command will fail with the error observed above

Jira issue: CRDB-21304

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Previously, there is a niche case where we might run into a backward incompatible issue (see #91528). We decided to fix it by relaxing the sanity check that caused the issue and backport the change to relase-22.2, so this backward incompatibility issue is contained only between release-22.2.0 and master, which we think should be a rare occurrance in the wild.

Fixes: #91528
Release note: None

### CODE REVIEW

**Review by postamar — COMMENTED** [review]
Is it possible to test this? I'm concerned of the possibility that while `BuildStages` no longer throws an error now, `ValidateStages` might still be.

**Comment by Xiang-Gu** [comment]
The only way to test I can think of is in a roachtest; in fact, we do have such a roachtest but [it's currently disabled](https://github.com/cockroachdb/cockroach/issues/89345) (It will be revived soon when build version is v23.1).

I tested it manually:
- Apply this PR to both master and release-22.2.
- Then do the following commands:
```
roachprod create local -n 2
git checkout release-22.2
dev build cockroach
mv cockroach cockroach-22.2
roachprod put local:1 ./cockroach-22.2
git checkout master
dev build cockroach
roachprod put local:2 ./cockroach
roachprod start local:1 --binary=cockroach-22.2
roachprod start local:2 --binary=cockroach
roachprod run local:2 -- touch data/DISABLE_STARTING_BACKGROUND_JOBS
roachprod sql local:2 -- -e 'create table t (i int primary key);'
roachprod sql local:2 -- -e 'drop table t;'
```

The last command to drop the table succeeded, which means the job for `drop table t` is backward compatible and can be adopted and completed by a node running v22.2:
Screen Shot 2022-12-05 at 10 19 41 AM

(Note that it took >30s to finish that last command; I suspect it's related to how we detect and adopt pending jobs in our framework, instead of the command itself taking that long)

**Review by postamar — APPROVED** [review]
Sorry I forgot about this PR! Approved, of course.

> (Note that it took >30s to finish that last command; I suspect it's related to how we detect and adopt pending jobs in our framework, instead of the command itself taking that long)

I agree. I noticed the same thing when setting pausepoints in demo.

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Pull request merged**
