### PR TITLE
scripts: delete "mosh" when cleaning up in gceworker.sh.

### PR DESCRIPTION
**Pull request by ghost**
Run `gcloud compute firewall-rules delete "mosh"` when running `gceworker.sh delete`.

Release note: None

### CODE REVIEW

**Review by tbg — CHANGES_REQUESTED** [review]
I actually messed this up more than I thought I would. The name `mosh` is not scoped to the specific "${NAME}" and so everyone's gceworkers conflict! That might be why you ran into the problem in the first place.

Try these diffs:

```diff
@@ -47,7 +53,10 @@ case "${cmd}" in
     gcloud compute instances stop "${NAME}"
     ;;
     delete|destroy)
-    gcloud compute instances delete "${NAME}"
+    status=0
+    gcloud compute firewall-rules delete "${NAME}-mosh" || status=$((status+1))
+    gcloud compute instances delete "${NAME}" || status=$((status+1))
+    exit ${status}
     ;;
     ssh)
     retry gcloud compute ssh "${NAME}" --ssh-flag="-A" "$@"
```

and

```diff
@@ -27,7 +29,7 @@ case "${cmd}" in
            --boot-disk-type "pd-ssd" \
            --boot-disk-device-name "${NAME}" \
            --scopes "default,cloud-platform"
-    gcloud compute firewall-rules create "mosh" --allow udp:60000-61000
+    gcloud compute firewall-rules create "${NAME}-mosh" --allow udp:60000-61000

     # Retry while vm and sshd to start up.
     retry gcloud compute ssh "${NAME}" --command=true
```

**Review by tbg — APPROVED** [review]
Looks good, please give it a test run though. I don't trust my diff just yet.

**Comment by windchan7** [comment]
Running the test. I've run it using my handle and it works fine. Now running your `justtesting`.

**Comment by tschottdorf** [comment]
Same comment as
https://github.com/cockroachdb/cockroach/pull/25616#issuecomment-389959482.
<https://github.com/cockroachdb/cockroach/pull/25616#issuecomment-389959482a>
-- 

-- Tobias

**Pull request merged**
