### PR TITLE
sql: support 'base64' and 'escape' args for encode/decode

### PR DESCRIPTION
**Pull request by bsnyder788**
Release note sql change: support 'base64' and 'escape' arugments for
encode/decode

### CODE REVIEW

**Comment by bsnyder788** [comment]
@justinj initial PR for https://github.com/cockroachdb/cockroach/issues/22233

**Comment by justinj** [comment]
Looks good @bsnyder788! Couple comments.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 1343 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22334#-L4aiuMuPrCIxH7jabVj:-L4aiuMuPrCIxH7jabVk:bi3urus) ([raw file](https://github.com/cockroachdb/cockroach/blob/69593fb0665d3f2e17e089ea6fd492ee23e6a86f/pkg/sql/logictest/testdata/logic_test/builtin_function#L1343)):*
> ```
> 
> query TT
> SELECT ENCODE('abc', 'escape'), DECODE('abc', 'escape')
> ```

I think `escape` is going to need more extensive tests - the Postgres docs say it "converts zero bytes and high-bit-set bytes to octal sequences (\nnn) and doubles backslashes.", so I think we should have at least some tests which exercise inputs with zero bytes, high-bit-set bytes, and multiple levels of backslashes to ensure they get handled properly.

To help testing, you can construct such byte sequences by using the `\x` form of a byte array:
```
'\x0001ff'::BYTES
```
is the three-element byte sequence `[0, 1, 255]`.

You'll probably want to cross-reference with Postgres - it often has surprising behaviour for edge cases and it's important that we match their behaviour for compatibility reasons.

---

*[pkg/sql/sem/builtins/builtins.go, line 535 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22334#-L4ajBs-E76aJhew6Aqp:-L4ajBs-E76aJhew6Aqq:b7j1mfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/69593fb0665d3f2e17e089ea6fd492ee23e6a86f/pkg/sql/sem/builtins/builtins.go#L535)):*
> ```Go
> 					return tree.NewDString(buf.String()), nil
> 				case "escape":
> 					return tree.NewDString(data), nil
> ```

See my earlier comment about testing `escape` - I think the implementation here is slightly more involved than this.

---

*[pkg/sql/sem/builtins/builtins.go, line 543 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22334#-L4ajZKtEfFy3qhACHik:-L4ajZKu6mze8dANcPR6:b-2uht4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/69593fb0665d3f2e17e089ea6fd492ee23e6a86f/pkg/sql/sem/builtins/builtins.go#L543)):*
> ```Go
> 				}
> 			},
> 			Info: "Encodes `data` in the text format specified by `format` (\"hex\", \"base64\", and \"escape\" are supported).",
> ```

It occurs to me now that we'll probably need to document the behaviour of these more extensively, but that isn't urgent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22334#-:-L4aila0FNDVLi-5O6HS:b-wd8dg7)*

**Comment by bsnyder788** [comment]
Thanks for the comments @justinj, will try to get to them later in the week.

**Comment by isoos** [comment]
Great work guys, looking forward to have this landed.

**Comment by justinj** [comment]
@isoos We actually did land `escape` support for 2.0 in a separate PR (#23512), just not `base64`.

**Comment by bsnyder788** [comment]
@justinj Sorry about, not getting back to this for such a long time. I will re-base off master and add in just the `base64` since you went ahead and nailed support for `escape` :)

**Comment by bsnyder788** [comment]
Closing since base64 support was merged with https://github.com/cockroachdb/cockroach/pull/25002

**Pull request closed without merging**
