### PR TITLE
sql: fix unchecked constraints with cascade loops

### LINKED ISSUE #42117: opt: invalid passing of "input" CheckHelper to the FK cascades code
The `CheckHelper` can operate in two modes: the legacy "eval" mode where it evaluates expressions, and a much simpler "input" mode where the mutation input has computed boolean columns for the checks. The optimizer uses the "input" mode, but the FK code for cascades uses it in "eval" mode.

We are incorrectly passing an "input" CheckHelper to the FK code here:
https://github.com/cockroachdb/cockroach/blob/3373ca3c33b4f838fec9fe1f1835905b31558cdc/pkg/sql/opt_exec_factory.go#L1222

This CheckHelper is used if any cascading action gets back to the original table, which can happen if there are loops or self-references. The "input" checker silently does nothing when used as an "eval" checker, so we may incorrectly allow actions that don't pass the checks.

Example:
```
CREATE TABLE self_ab (a INT UNIQUE, b INT DEFAULT 1 CHECK (b != 1), INDEX (b));
INSERT INTO self_ab VALUES (1, 2), (2, 2);
ALTER TABLE self_ab ADD CONSTRAINT fk FOREIGN KEY (b) REFERENCES self_ab(a) ON UPDATE SET DEFAULT;
UPDATE self_ab SET a=3 WHERE a=2;
SELECT * FROM self_ab;
  a | b  
+---+---+
  1 | 1  
  3 | 2  
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: fix unchecked constraints with cascade loops

The cascader uses a `CheckHelper` when updating rows in a table. Since
we added optimizer support for mutations, we have two types of
`CheckHelper` (the old "eval mode" and the new "input mode").

The mutation code is passing the initial table's `CheckHelper` which
is in "input mode". The cascader is using it in the "eval mode" which
is a no-op. This causes CHECK constraints against the initial table to
not be verified. This can happen with self-referencing cascades, or
when there is a cascading loop.

I plan to follow up with a cleanup that removes the two modes and
separates the new "input mode" code completely. We can do this on
master where we ripped out the heuristic planner.

Fixes #42117.

Release note (bug fix): Fixed a bug in scenarios where we have UPDATE
cascades; and we are updating a table that has CHECK constraints; and
the table is self-referencing or is involved in a reference cycle. In
this case an UPDATE that cascades back in the original table was not
validated with respect to the CHECK constraints.

#### sql: allow check expressions with non-public columns in cascader

When adding a column with a check expression, the schema change
happens as follows:
 1. The backfill starts to initialize the new column; at this time, the
   check is not "active";
 2. The backfill completes; the check becomes "active" but the schema
    change is not complete and the column is still write-only;
 3. The check constraint is validated in another pass;
 4. The schema change is complete.

It is correct to treat the columns as readable once the check becomes
active.

This change modifies the legacy `CheckHelper` (used by the cascader)
to allow non-public columns in check expressions.

Release note: None

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42231#-:-Lt6sqgK1_8b8Lq7c2HX:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt_exec_factory.go, line 1407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42231#-Lt6sQGJD4Oi40JC3mmv:-Lt6sQGJD4Oi40JC3mmw:bfr5wx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4953f5f09365084c4f80f097824d4f8b6a973632/pkg/sql/opt_exec_factory.go#L1407)):*
> ```Go
> 
> 	// Create a CheckHelper, used in case of cascading actions that cause changes
> 	// in the original table. This is only possible with UPDATE (together with
> ```

This is possible with UPSERT as well, right?
___
*[pkg/sql/logictest/testdata/logic_test/cascade, line 3728 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42231#-Lt6sY6LENW_x5L35zzI:-Lt6sY6LENW_x5L35zzJ:b-ieqmk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4953f5f09365084c4f80f097824d4f8b6a973632/pkg/sql/logictest/testdata/logic_test/cascade#L3728)):*
> ```
> # which violates the check.
> statement error failed to satisfy CHECK constraint \(b != 1\)
> UPDATE self_ab SET a = 3 WHERE a = 2
> ```

I'd add an UPSERT case as well, if it can trigger this.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42231)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

___
*[pkg/sql/opt_exec_factory.go, line 1407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42231#-Lt6sQGJD4Oi40JC3mmv:-Lt9_djDEciwmIiJr_my:b60fjz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4953f5f09365084c4f80f097824d4f8b6a973632/pkg/sql/opt_exec_factory.go#L1407)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This is possible with UPSERT as well, right?
</blockquote></details>

Added to the comment.
___
*[pkg/sql/logictest/testdata/logic_test/cascade, line 3728 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42231#-Lt6sY6LENW_x5L35zzI:-Lt9_f5q-Md-tIgJh8iu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4953f5f09365084c4f80f097824d4f8b6a973632/pkg/sql/logictest/testdata/logic_test/cascade#L3728)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd add an UPSERT case as well, if it can trigger this.
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
I thought I was hitting a flaky test (that's what teamcity showed) but this change causes `TestRaceWithBackfill` to fail. The test fails this upsert:
https://github.com/cockroachdb/cockroach/blob/4953f5f09365084c4f80f097824d4f8b6a973632/pkg/sql/schema_changer_test.go#L493
with the error `column "x" does not exist` generated when we try to create a `NewEvalCheckHelper`. We are in a state where we are dropping column `x` but we still have a check constraint that refers to it `(x >= 0)`. It looks like the optimizer itself is ok with this case but not the legacy code.

CC @lucy-zhang, @BramGruneir what is the expected behavior in this case? Should the check constraint be ignored? And any idea how this used to work before the optimizer? (the HP code used to create an eval check helper just like this one)

**Comment by RaduBerinde** [comment]
From what I can tell, in 19.1 the table descriptor did not have an ActiveCheck when this UPSERT was executed.. What changed?

**Comment by RaduBerinde** [comment]
Thinking more about it, I think it's a bug that the optimizer tolerates CHECK expressions that involve deletable columns. I'll try to add a check for that and maybe try to bisect to see when this started happening.

**Comment by RaduBerinde** [comment]
Used bisect to figure out when this problem started. Unfortunately it came up with 0fab1a142aa327a24c74db37b666044370fa79f8 which is a test improvement. I verified that the bug existed in 19.1 as well. Not quite sure how to proceed.

**Comment by RaduBerinde** [comment]
I have added a commit that modifies the CheckHelper to allow using non-public columns. The commit message contains more information.

**Comment by RaduBerinde** [comment]
Failure was due to some connection problem with github.

bors r+

**Pull request merged**
