### PR TITLE
release-20.1: sql: Change output of CREATE/ALTER/DROP ROLE to not include rows affected. Add hint for GRANT ROLE. 

### PR DESCRIPTION
**Pull request by RichardJCai**
Backport 1/1 commits from #46795.
/cc @cockroachdb/release

### CODE REVIEW

**Comment by knz** [comment]
Can you fix the subject line of the commit message. right now it spans two lines

**Review by knz — COMMENTED** [review]
Please also add the examples from the PR description into the commit message. That's where they belong.

I also vaguely recall I have reviewed this PR already somewhere - did you create a new one?

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46819#-:-M3mqIg5115PdSAm9tvq:b-xmxx84)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
did you use the `backport` tool?

**Comment by RichardJCai** [comment]
> Please also add the examples from the PR description into the commit message. That's where they belong.
> 
> I also vaguely recall I have reviewed this PR already somewhere - did you create a new one?
> 
> > Reviewed 7 of 7 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46819#-:-M3mqIg5115PdSAm9tvq:b-xmxx84)_ status: :shipit: complete! 0 of 0 LGTMs obtained

Sorry, I didn't know about the backport tool - updated to use it.

**Comment by knz** [comment]
do you still need a review on this one?

**Comment by RichardJCai** [comment]
Yeah, or rather need approval to backport it.

**Comment by knz** [comment]
ok then can you update the PR description and rebase, then i'll review

**Comment by RichardJCai** [comment]
> ok then can you update the PR description and rebase, then i'll review

Rebased and updated

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46819#-:-M4FQmT_Aa2GWPPe0PBn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by RichardJCai** [comment]
TFTR!
bors r=knz

**Comment by knz** [comment]
i think you need to retry this.

**Comment by RichardJCai** [comment]
bors r=knz

**Comment by RichardJCai** [comment]
Retrying again - failure doesn't look related to change.

bors r=knz

**Comment by RichardJCai** [comment]
bors r=knz

**Pull request merged**
