### PR TITLE
importccl: add support for IMPORT INTO RBR table

### LINKED ISSUE #69616: importccl:  IMPORT INTO should support `gateway_region` builtin default expression
To unlock `IMPORT INTO` for regional by row tables, it needs to be able to handle the default expression on the `crdb_region` column which is a call to the crdb builtin `gateway_region`. This builtin is volatile depending on the gateway node the import job is running on, and thus we do cannot support it as is, since it breaks the idempotency invariant of import execution.

To work around this volatility we can override the `gateway_region` default expression to always return the primary region of the database that was resolved during import planning. This is similar to what we do during the backfill of the column when altering a table's locality to RBR. Evaluating the default expr to the primary region also seems like the "more correct" thing to do since an import job is not necessarily associated with a gateway node, it is a background process ingesting data. 

Today, an `IMPORT INTO` will fail during type resolution of the underlying UDT of `crdb_region`, but once https://github.com/cockroachdb/cockroach/issues/61133#issuecomment-908706919 is addressed we will not run into that particular hurdle.

Epic CRDB-7074

### PR DESCRIPTION
**Pull request by adityamaru**
This change overrides the `default_to_database_primary_region`
and `gateway_region` to always return the primary region of the
database of the table being imported into. This allows for
IMPORT INTO an RBR table.

To ensure that the import is idempotent across resumptions, we cache
the primary region of the database being imported into, during planning.
This information is store in the job details and flow spec to be used
when evaluating the relevant default expr/computed column.

Since IMPORT is a job, it does not have an associated session data
and so it cannot rely on the planners' implementation of the regional
operator. This change also implements the relevant methods in the
`importRegionOperator` to allow resolution of the primary region
of the database being imported into.

Fixes: #69616

Release note (sql change): IMPORT INTO regional by row tables
is supported.

Release justification: fixes for high-priority or high-severity bugs in existing functionality

### CODE REVIEW

**Comment by adityamaru** [comment]
The last commit is the relevant one. @ multiregion folks are there any other tests that you think would be worth adding here? Currently, I just tweaked the test that would previously check for an unsupported error.

**Review by ajstorm — CHANGES_REQUESTED** [review]
Nice to see this coming together.  Have you tested the case where the IMPORT data contains data for the `crdb_region` column?  Can we add a test for that case too?

> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-:-MjB0I3k8ZXOYICUCtD0:bg53jlw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, and @dt)

___
*[pkg/ccl/importccl/import_table_creation.go, line 315 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjAghrh95Q5fJCcqp98:-MjAghri-HT7xr7zJx7A:b-hrez42) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ac3fce653c740058040298544080e52a6a672a/pkg/ccl/importccl/import_table_creation.go#L315)):*
> ```Go
> 			dbDesc.GetID(),
> 			so.cf.NewCollection(nil /* TemporarySchemaProvider */),
> 			sql.SynthesizeRegionConfigOptionUseCache,
> ```

Out of curiosity, why use the cache here?  Can we add a comment with the rationale?
___
*[pkg/sql/row/expr_walker.go, line 523 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjB03rK-_9msvPFl7-g:-MjB03rK-_9msvPFl7-h:b-eylg5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ac3fce653c740058040298544080e52a6a672a/pkg/sql/row/expr_walker.go#L523)):*
> ```Go
> }
> 
> func importGatewayRegion(evalCtx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> ```

Should `importGatewayRegion` be returning the Primary region?  If so, maybe a comment as to why?
___
*[pkg/sql/row/expr_walker.go, line 684 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjB-OhL-u3ZhDyQhUzI:-MjB-OhL-u3ZhDyQhUzJ:b-hqhplh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ac3fce653c740058040298544080e52a6a672a/pkg/sql/row/expr_walker.go#L684)):*
> ```Go
> 				Types:      tree.ArgTypes{},
> 				ReturnType: tree.FixedReturnType(types.String),
> 				Info:       "Returns the primary region of the database.",
> ```

Returns the gateway region of the database?

**Review by arulajmani — COMMENTED** [review]
This does raise an interesting question. I don't think this function is immutable the way it is written. Consider the case where the primary region on the database descriptor changes while the import job is executing -- wouldn't we end up returning different values in that case? I'm not very familiar with this area of the code but I wonder if that's a problem for us?

**Comment by arulajmani** [comment]
@adityamaru wrote:

> This does raise an interesting question. I don't think this function is immutable the way it is written. Consider the case where the primary region on the database descriptor changes while the import job is executing -- wouldn't we end up returning different values in that case? I'm not very familiar with this area of the code but I wonder if that's a problem for us?

Yup, I'll have to cache the primary region (or descriptor) of the database at the time of planning so that it doesn't change while the import is running. Will update the change with this!

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69903)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @dt)

___
*[pkg/ccl/importccl/import_table_creation.go, line 315 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjAghrh95Q5fJCcqp98:-MjG0bgm3GJQsbSjjRVC:brvsacp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ac3fce653c740058040298544080e52a6a672a/pkg/ccl/importccl/import_table_creation.go#L315)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This does raise an interesting question. I don't think this function is immutable the way it is written. Consider the case where the primary region on the database descriptor changes while the import job is executing -- wouldn't we end up returning different values in that case? I'm not very familiar with this area of the code but I wonder if that's a problem for us?
</blockquote></details>

Changed the implementation to resolve the DB primary region during import planning, and storing the primary region string on the import job for use during execution. The resolution no longer uses the cache.
___
*[pkg/sql/row/expr_walker.go, line 523 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjB03rK-_9msvPFl7-g:-MjG0qxh1iRebya50LLJ:b-6iqig5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ac3fce653c740058040298544080e52a6a672a/pkg/sql/row/expr_walker.go#L523)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Should `importGatewayRegion` be returning the Primary region?  If so, maybe a comment as to why?
</blockquote></details>

Both `gateway_region` and `deafult_to_database_primary_region` should return the cached primary region of the database being imported into. This is important for import to be idempotent across job resumptions. Added a comment about this!
___
*[pkg/sql/row/expr_walker.go, line 684 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjB-OhL-u3ZhDyQhUzI:-MjG1qa71ieLM5As2zgk:bt8y8n1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ac3fce653c740058040298544080e52a6a672a/pkg/sql/row/expr_walker.go#L684)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Returns the gateway region of the database?
</blockquote></details>

As mentioned above, we need to return the primary region of the db even when we are evaluating `gateway_region()`.

**Review by arulajmani — CHANGES_REQUESTED** [review]
> Reviewed 5 of 25 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69903)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @dt)

___
*[-- commits, line 14 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGFUcPB0DtPR_tXkFL):*
Might be worth expanding the commit message to include details about the proto changes you've made to capture the primary region during planning. 
___
*[pkg/ccl/importccl/import_stmt.go, line 981 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGDPGC9AvDqWpFDour:-MjGDPGD6NuB5Ym4Djju:b-ui5dpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/import_stmt.go#L981)):*
> ```Go
> 		// computed columns such as `gateway_region`.
> 		var databasePrimaryRegion descpb.RegionName
> 		if db.IsMultiRegion() {
> ```

Do we need to add a version gate here? What if an import job is planned on a 21.2 node but gets run on a 21.1 node which doesn't know how to deal with this primary region stuff? 

Separately, if we do add a version gate, do we need to make some concessions for importing into GLOBAL/REGIONAL BY TABLE tables so as to not break them in a mixed version setting? 
___
*[pkg/ccl/importccl/import_stmt.go, line 982 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGDLvU7RlZmU61q53Q:-MjGDLvU7RlZmU61q53R:b-sk40n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/import_stmt.go#L982)):*
> ```Go
> 		var databasePrimaryRegion descpb.RegionName
> 		if db.IsMultiRegion() {
> 			if err := p.ExecCfg().CollectionFactory.Txn(ctx, p.ExecCfg().InternalExecutor, p.ExecCfg().DB,
> ```

Can we replace this with `sql.DescsTxn` instead?
___
*[pkg/ccl/importccl/read_import_base.go, line 65 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGGLzvEaFLN4jkfbo5:-MjGGLzvEaFLN4jkfbo6:b-3qxorh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/read_import_base.go#L65)):*
> ```Go
> 	// assignment.
> 	evalCtx.DB = flowCtx.Cfg.DB
> 	evalCtx.Regions = makeImportRegionOperator(*spec.DatabasePrimaryRegion)
> ```

Is this missing a nil check on `spec.DatabasePrimaryRegion` for non multi-region databases? 
___
*[pkg/jobs/jobspb/jobs.proto, line 328 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGG2H-80GCq_Sr-AVt:-MjGG2H-80GCq_Sr-AVu:bsw0ptv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/jobs/jobspb/jobs.proto#L328)):*
> ```protobuf
>   // field stores the databases' primary region.
>   string database_primary_region = 27 [
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.RegionName"
> ```

Should this be `nullable=false`?
___
*[pkg/sql/execinfrapb/processors_bulk_io.proto, line 149 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGHLhm-BOzKjfHf-2r:-MjGHLhm-BOzKjfHf-2s:b-evvuzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/sql/execinfrapb/processors_bulk_io.proto#L149)):*
> ```protobuf
>   // field stores the databases' primary region.
>   optional string database_primary_region = 17 [
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.RegionName"
> ```

Should this be `nullable=false` as well?

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69903)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @dt)

___
*[pkg/ccl/importccl/import_table_creation.go, line 276 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjG3dHG4vbkJbiMjyX6:-MjG3dHG4vbkJbiMjyX7:b4faybh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/import_table_creation.go#L276)):*
> ```Go
> 
> type importDatabaseRegionConfig struct {
> 	primaryRegion descpb.RegionName
> ```

Are we calling this "DatabaseRegionConfig" because we want to allow for its expansion later on?  Just wondering why it only contains the primary region?
___
*[pkg/sql/row/expr_walker.go, line 523 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjB03rK-_9msvPFl7-g:-MjGd6YA7xnfkD5NOqbg:bahrn5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ac3fce653c740058040298544080e52a6a672a/pkg/sql/row/expr_walker.go#L523)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Both `gateway_region` and `deafult_to_database_primary_region` should return the cached primary region of the database being imported into. This is important for import to be idempotent across job resumptions. Added a comment about this!
</blockquote></details>

Thanks, I get it now.  

Nit: Might just be me, but I think it would be more intuitive if you had both the `default_to_database_primary_region` and `gateway_region` import functions map to the same `importDefaultToDatabasePrimaryRegion` function and explain in that single place why both should map to the same thing.  Having a separate function here called `importGatewayRegion` which doesn't map to the gateway region seems like it could cause confusion down the road.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69903)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @dt)

___
*[-- commits, line 14 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGFUcPB0DtPR_tXkFL):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Might be worth expanding the commit message to include details about the proto changes you've made to capture the primary region during planning. 
</blockquote></details>

done.
___
*[pkg/ccl/importccl/import_stmt.go, line 981 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGDPGC9AvDqWpFDour:-MjGX072EWS7wW_ERt6c:bx70k1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/import_stmt.go#L981)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we need to add a version gate here? What if an import job is planned on a 21.2 node but gets run on a 21.1 node which doesn't know how to deal with this primary region stuff? 

Separately, if we do add a version gate, do we need to make some concessions for importing into GLOBAL/REGIONAL BY TABLE tables so as to not break them in a mixed version setting? 
</blockquote></details>

I thought this through let me know if this makes sense. Also @dt to sanity check:

There are three phases in an import relevant to us:
- Plan
- Prepare descriptor for ingestion (part of job execution)
- Flow execution

An important point to note is that an older version node can never plan a distsql flow on a newer version node. This is enforced in `SetupAllNodesPlanning` when we decide what nodes are eligible to run a flow.

Case 1: All nodes single version -- no problem

Case 2: 21.2, 21.1, 21.1:

21.1 node will fail https://github.com/cockroachdb/cockroach/blob/release-21.1/pkg/ccl/importccl/import_stmt.go#L1256 at this point.

Case 3: 21.2, 21.2, 21.1:

If the descriptor is prepared by a 21.2 node but the distsql flow gets planned on a 21.1 node, then it will fail when attempting to type-check a default expression with a UDT. This was the behavior before these 3 PRs. The failure will happen here https://github.com/cockroachdb/cockroach/blob/release-21.1/pkg/sql/row/row_converter.go#L337 since the semaCtx has a nil type resolver in 21.1.

Case 4: 21.1, 21.2, 21.2

In this case, 21.2 node will attempt to evaluate the default expression of `crdb_region` but will see an empty primary region since the field was never set by the 21.1 node. I added a check that if the primary region is "" then fail the import.

Case 5: 21.1, 21.2, 21.1

Similar to case 3.
___
*[pkg/ccl/importccl/import_stmt.go, line 982 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGDLvU7RlZmU61q53Q:-MjGWNl89VVKlS7HHwz0:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/import_stmt.go#L982)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we replace this with `sql.DescsTxn` instead?
</blockquote></details>

done.
___
*[pkg/ccl/importccl/import_table_creation.go, line 276 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjG3dHG4vbkJbiMjyX6:-MjGrGHm3A1PdSIrGRc_:b5mmi6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/import_table_creation.go#L276)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Are we calling this "DatabaseRegionConfig" because we want to allow for its expansion later on?  Just wondering why it only contains the primary region?
</blockquote></details>

I'm not sure about expansion but I needed a minimal implementation of the tree.DatabaseRegionConfig interface that would give me access to the cached primary region when `CurrentDatabaseRegionConfig` is called. This is needed in the builtin override that only receives an evalCtx as a parameter. 
It seemed intuitive to name it `importDatabaseRegionConfig` so as to imply that it is a stripped-down db region config that only has access to certain fields. I'm happy to rename it to something more suitable?
___
*[pkg/ccl/importccl/read_import_base.go, line 65 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGGLzvEaFLN4jkfbo5:-MjGWPLT3V9o4wmUKRWl:bg9mxta) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/read_import_base.go#L65)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is this missing a nil check on `spec.DatabasePrimaryRegion` for non multi-region databases? 
</blockquote></details>

It goes away once the proto field in processors_bulk_io.proto is made non-nullable.
___
*[pkg/jobs/jobspb/jobs.proto, line 328 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGG2H-80GCq_Sr-AVt:-MjGWTti7azPRin2cViH:b-kwa269) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/jobs/jobspb/jobs.proto#L328)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this be `nullable=false`?
</blockquote></details>

In proto3 I don't think we need to set nullable to false. It'll just be set to its zero value if it is unset which is "" I think?
___
*[pkg/sql/execinfrapb/processors_bulk_io.proto, line 149 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGHLhm-BOzKjfHf-2r:-MjGW_VS4sqBC4okU8mM:bero144) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/sql/execinfrapb/processors_bulk_io.proto#L149)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this be `nullable=false` as well?
</blockquote></details>

Nice catch, unfortunately, this proto is still on proto2. I'm hesitant to change it in this PR so adding the nullable clause. 
___
*[pkg/sql/row/expr_walker.go, line 523 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjB03rK-_9msvPFl7-g:-MjH0Nzc5xap4oThpmGZ:bl7tnra) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ac3fce653c740058040298544080e52a6a672a/pkg/sql/row/expr_walker.go#L523)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Thanks, I get it now.  

Nit: Might just be me, but I think it would be more intuitive if you had both the `default_to_database_primary_region` and `gateway_region` import functions map to the same `importDefaultToDatabasePrimaryRegion` function and explain in that single place why both should map to the same thing.  Having a separate function here called `importGatewayRegion` which doesn't map to the gateway region seems like it could cause confusion down the road.
</blockquote></details>

good point, done.

**Review by ajstorm — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-:-MjUIOYG3wSxs68D0SA0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @dt)

___
*[pkg/ccl/importccl/import_table_creation.go, line 276 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjG3dHG4vbkJbiMjyX6:-MjUHLsq9r_M2c1ulmCk:b-6rbb5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/import_table_creation.go#L276)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

I'm not sure about expansion but I needed a minimal implementation of the tree.DatabaseRegionConfig interface that would give me access to the cached primary region when `CurrentDatabaseRegionConfig` is called. This is needed in the builtin override that only receives an evalCtx as a parameter. 
It seemed intuitive to name it `importDatabaseRegionConfig` so as to imply that it is a stripped-down db region config that only has access to certain fields. I'm happy to rename it to something more suitable?
</blockquote></details>

That makes sense.  Is it worth adding a comment above this which states that this is just a stripped-down version of `multiregion.RegionConfig` for use by import?  That might help frame this for people who aren't immediately familiar with the RegionConfig structure.
___
*[pkg/sql/row/expr_walker.go, line 523 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjB03rK-_9msvPFl7-g:-MjUIEwq8Du9vG87MB6L:b-58y1yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3ac3fce653c740058040298544080e52a6a672a/pkg/sql/row/expr_walker.go#L523)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

good point, done.
</blockquote></details>

Looks good. Thanks!

**Review by arulajmani — COMMENTED** [review]
Things look good to me. See my comment around the mixed version stuff, but I'll defer to your and @dt's call on how to best handle that! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-:-MjVngrdCEqsxosRGdsj:b3ev5do)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @dt)

___
*[pkg/ccl/importccl/import_stmt.go, line 981 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGDPGC9AvDqWpFDour:-MjVYNfE3RG1kzSOW8aQ:blvdtvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/import_stmt.go#L981)):*
> Case 5: 21.1, 21.2, 21.1
> Similar to case 3.

Did you mean to say Case 2? 

This explanation makes sense at a high level. My first instinct would have been to version gate this, but looks like we're not breaking any existing behaviour here so maybe it's fine. I do wish that we had tests for all these tricky mixed version cases, but I know that'll be a fair bit of work. 

Considering I don't live around these code ends, I'll leave all this to your and @dt's call. 
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6432 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjVf4RZBnE55i-VqLRw:-MjVf4RZBnE55i-VqLRx:b-ergi7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e152cbe2d8f0921e963ea37ab6ed153d0b283e1/pkg/ccl/importccl/import_stmt_test.go#L6432)):*
> ```Go
> 	simpleOcf := fmt.Sprintf("nodelocal://0/avro/%s", "simple.ocf")
> 
> 	data := "1,\"foo\",NULL,us-east1\n"
> ```

Is it worth writing a test which writes a row referencing a region not present on the multi-region enum? 
___
*[pkg/jobs/jobspb/jobs.proto, line 328 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjGG2H-80GCq_Sr-AVt:-MjVXuYE2o3lDDFitAOK:btu3uqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/jobs/jobspb/jobs.proto#L328)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

In proto3 I don't think we need to set nullable to false. It'll just be set to its zero value if it is unset which is "" I think?
</blockquote></details>

heh I didn't realize we had proto3s here (or anywhere, if I'm being honest)

**Comment by dt** [comment]
In the mixed version cases that get into these error cases, with no version gate the IMPORT just fails with an error, right? and if we added a version gate, that would... also fail with an error? If so, I don't feel strongly that we need the gate, vs if there was correctness concern. /2¢

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69903)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajstorm, @arulajmani, and @dt)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 6432 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjVf4RZBnE55i-VqLRw:-MjeF4a02sievDjlgH59:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e152cbe2d8f0921e963ea37ab6ed153d0b283e1/pkg/ccl/importccl/import_stmt_test.go#L6432)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is it worth writing a test which writes a row referencing a region not present on the multi-region enum? 
</blockquote></details>

done!
___
*[pkg/ccl/importccl/import_table_creation.go, line 276 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69903#-MjG3dHG4vbkJbiMjyX6:-MjeF5sLE5PWBa-z8Yzm:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b78d0c588653825c3ada340f570896926d25b2b5/pkg/ccl/importccl/import_table_creation.go#L276)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

That makes sense.  Is it worth adding a comment above this which states that this is just a stripped-down version of `multiregion.RegionConfig` for use by import?  That might help frame this for people who aren't immediately familiar with the RegionConfig structure.
</blockquote></details>

done.

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
Unrelated bazel flake in `TestSeparatedIntentsMigration`.

TFTRs!

bors r=arulajmani,ajstorm,dt

**Pull request merged**
