### PR TITLE
sql: factor code away from expandPlan and into ordinalityNode methods.

### LINKED ISSUE #13594: sql: revisit ordering code for ordinalityNode
During expand plan we have one-off logic for the ordering of ordinalityNode: https://github.com/cockroachdb/cockroach/blob/b02e43f9e6d497f162cdc2fc1d72b5c9364aa00c/pkg/sql/expand_plan.go#L124

This should be better encapsulated in the node itself. The logic also needs to be revisited. We try to pass through a desired ordering even if there is a desired ordering on the ordinality column (code below) but that will never end up being used - what is important is the way we update `n.ordering` afterward; we only use the ordinality ordering if there is no underlying ordering. We also aren't checking for the desired direction of the ordinality column in this code:

```go
// If there's a desired ordering on the ordinality column, drop it.
if len(params.desiredOrdering) > 0 {
	newDesired := make(sqlbase.ColumnOrdering, 0, len(params.desiredOrdering))
	for _, ordInfo := range params.desiredOrdering {
		if ordInfo.ColIdx == len(n.columns)-1 {
			break
		}
		newDesired = append(newDesired, ordInfo)
	}
	params.desiredOrdering = newDesired
}
```
CC @knz

### PR DESCRIPTION
**Pull request by knz**
Fixes #13594.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13599)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Hi Raphael,
I am commenting more in the issue. Can this wait for #13577?

**Comment by knz** [comment]
Rebased, since #13577 is merged this can take another look.

**Comment by knz** [comment]
ping?

**Comment by RaduBerinde** [comment]
LGTM

Sorry this dropped from my radar.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/ordinality.go, line 126 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13599#-KmUQRjGnplcln-Knzav:-KmUQRjGnplcln-Knzaw:b-4j4o0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3048b32aea2b324f8f8b59ae0140dda8627d37/pkg/sql/ordinality.go#L126)):*
> ```Go
> 				break
> 			}
> 			newDesired = append(newDesired, ordInfo)
> ```

can't we just do `return desiredOrdering[:i]` instead of the `break`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13599#-:-KmUQd0blcWBCmJbhTkF:b-q2wvo)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/ordinality.go, line 126 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13599#-KmUQRjGnplcln-Knzav:-KmYZt0hyGBZgiz1jeMB:bsjrr2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3048b32aea2b324f8f8b59ae0140dda8627d37/pkg/sql/ordinality.go#L126)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

can't we just do `return desiredOrdering[:i]` instead of the `break`?
</blockquote></details>

Nice idea. Let's see if it passes CI, I wasn't sure if reusing the same slice was kosher.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13599)*

**Comment by knz** [comment]
It did! TFYR

**Pull request merged**
