### PR TITLE
storage: split the debug_range history's info

### PR DESCRIPTION
**Pull request by BramGruneir**
This was done by first converting RangeLogEvents from a struct to a Proto.
And this proto is used in the response instead of an adhoc one that was
already in place. One key part to this was making the info column, which is
just a JSON string now parsable into the proto.

Some care had to be taken to handle the older format that will have been
recorded in the range log table.

### CODE REVIEW

**Comment by BramGruneir** [comment]
screen shot 2017-05-18 at 11 09 58

**Comment by petermattis** [comment]
Showing the `RangeDescriptor` keys isn't terribly interesting except for on a split. And for a split, it would be nice to list the key that was split at explicitly. For `Add` events, I'm not sure if the `Update Range Descriptor` info is useful. Perhaps this could be simplified so that `Add` and `Remove` events only show the added/removed replica in the `Info` field. `Split` events would only show the `New Range Descriptor` (which would include the split key). Thoughts?

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/log.proto, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-KkS1P92D7N5Vran_NCO:-KkS1P92D7N5Vran_NCP:bdyr786) ([raw file](https://github.com/cockroachdb/cockroach/blob/2902c0dfcb4da1aa1bddb05c1ce26dab864904cf/pkg/storage/log.proto#L32)):*
> ```protobuf
> }
> 
> message RangeLogEvent {
> ```

Are you sending this over the wire? Seems like you could have exported `rangeEventLog` (and its fields). I'm probably just missing something.

---

*[pkg/storage/log.proto, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-KkS-oN-Cn4NrJwk77Lc:-KkS-oN0_6vN7y6BIhwk:b31ngc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2902c0dfcb4da1aa1bddb05c1ce26dab864904cf/pkg/storage/log.proto#L46)):*
> ```protobuf
>   int64 range_id = 2 [
>     (gogoproto.customname) = "RangeID",
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/roachpb.RangeID"
> ```

FYI, `gogoproto.jsontag` allows you to control the `json` tag emitted for a field. I think this would allow you to get rid of the `UnmarshalRangeLogEventInfoJSON` ugliness.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-:-KkS0UZD3pK7CYm8UkdW:b-lrnzcc)*

**Comment by bdarnell** [comment]
:lgtm: 

I think it's useful to show the updated range descriptor (or at least the full replica set) on add/remove so it's easy to see the then-current value, instead of having to replay all the adds and removes in your head. 

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/log.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-KkS2r420ODcWDA6djDj:-KkS2r420ODcWDA6djDk:b-5o7iq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2902c0dfcb4da1aa1bddb05c1ce26dab864904cf/pkg/storage/log.go#L59)):*
> ```Go
> 		event.RangeID,
> 		event.StoreID,
> 		event.EventType.String(),
> ```

I'd lowercase these for consistency with the previous records.

---

*[pkg/storage/log.proto, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-KkS1o8XTp8lc4QfA8Wz:-KkS1o8Y7cLkRKFkzYNF:b-t894pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2902c0dfcb4da1aa1bddb05c1ce26dab864904cf/pkg/storage/log.proto#L34)):*
> ```protobuf
> message RangeLogEvent {
>   message Info {
>       roachpb.RangeDescriptor updated_desc = 1;
> ```

I think you can use `[(gogoproto.jsontag) = "UpdatedDesc"]` here to be backwards-compatible without munging the strings. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-:-KkS3H4bt-yfpLW-OKVl:b-blktq8)*

**Comment by BramGruneir** [comment]
I'll leave it as is for now. 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/log.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-KkS2r420ODcWDA6djDj:-Kkg516-4Q2FAn3wrM1u:b-fgkerk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2902c0dfcb4da1aa1bddb05c1ce26dab864904cf/pkg/storage/log.go#L59)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'd lowercase these for consistency with the previous records.
</blockquote></details>

I've changed the enum to be lowercase instead so it always matches.

---

*[pkg/storage/log.proto, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-KkS1P92D7N5Vran_NCO:-KkgDhYxRi52hW6NjZFX:b-payobx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2902c0dfcb4da1aa1bddb05c1ce26dab864904cf/pkg/storage/log.proto#L32)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are you sending this over the wire? Seems like you could have exported `rangeEventLog` (and its fields). I'm probably just missing something.
</blockquote></details>

Yes, it is exported during calls to RangeLog in the admin server.  There already was a proto that I created there as part of the response, but it seemed silly to have two different versions, one in a struct and one in a proto.

---

*[pkg/storage/log.proto, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-KkS1o8XTp8lc4QfA8Wz:-KkgGskdYBLhLJ6WnTrL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2902c0dfcb4da1aa1bddb05c1ce26dab864904cf/pkg/storage/log.proto#L34)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think you can use `[(gogoproto.jsontag) = "UpdatedDesc"]` here to be backwards-compatible without munging the strings. 
</blockquote></details>

Done.

---

*[pkg/storage/log.proto, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-KkS-oN-Cn4NrJwk77Lc:-KkgGtq7aSxMK6Mt0Mvn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2902c0dfcb4da1aa1bddb05c1ce26dab864904cf/pkg/storage/log.proto#L46)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

FYI, `gogoproto.jsontag` allows you to control the `json` tag emitted for a field. I think this would allow you to get rid of the `UnmarshalRangeLogEventInfoJSON` ugliness.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021#-:-KkgGuapo22CJHbLuCme:b-g5bnt2)*

**Comment by bdarnell** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16021)*

**Pull request merged**
