### PR TITLE
storage/engine: use pool to avoid newiterator alloc

### PR DESCRIPTION
**Pull request by dt**
Easy to pool since we already have a `Close` method we need to call.

```
name                                    old time/op    new time/op    delta
IterOnBatch100_RocksDB-8                  4.81µs ± 3%    4.49µs ± 2%    -6.69%    (p=0.000 n=9+9)
MVCCPut100_RocksDB-8                      6.39µs ± 2%    6.24µs ± 1%    -2.49%   (p=0.000 n=10+9)
MVCCConditionalPutCreate100_RocksDB-8     6.41µs ± 2%    6.19µs ± 1%    -3.50%   (p=0.000 n=8+10)
MVCCConditionalPutReplace100_RocksDB-8    9.08µs ± 2%    8.56µs ± 2%    -5.76%  (p=0.000 n=10+10)

name                                    old alloc/op   new alloc/op   delta
IterOnBatch100_RocksDB-8                   96.0B ± 0%     16.0B ± 0%   -83.33%  (p=0.000 n=10+10)
MVCCPut100_RocksDB-8                       80.0B ± 0%     0.0B ±NaN%  -100.00%  (p=0.000 n=10+10)
MVCCConditionalPutCreate100_RocksDB-8      80.0B ± 0%     0.0B ±NaN%  -100.00%  (p=0.000 n=10+10)
MVCCConditionalPutReplace100_RocksDB-8      192B ± 0%      112B ± 0%   -41.67%  (p=0.000 n=10+10)

name                                    old allocs/op  new allocs/op  delta
IterOnBatch100_RocksDB-8                    3.00 ± 0%      2.00 ± 0%   -33.33%  (p=0.000 n=10+10)
MVCCPut100_RocksDB-8                        1.00 ± 0%     0.00 ±NaN%  -100.00%  (p=0.000 n=10+10)
MVCCConditionalPutCreate100_RocksDB-8       1.00 ± 0%     0.00 ±NaN%  -100.00%  (p=0.000 n=10+10)
MVCCConditionalPutReplace100_RocksDB-8      2.00 ± 0%      1.00 ± 0%   -50.00%  (p=0.000 n=10+10)

name                                    old speed      new speed      delta
MVCCPut100_RocksDB-8                    15.6MB/s ± 2%  16.0MB/s ± 1%    +2.54%   (p=0.000 n=10+9)
MVCCConditionalPutCreate100_RocksDB-8   15.6MB/s ± 2%  16.2MB/s ± 1%    +3.86%   (p=0.000 n=9+10)
MVCCConditionalPutReplace100_RocksDB-8  11.0MB/s ± 2%  11.7MB/s ± 2%    +6.12%  (p=0.000 n=10+10)
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5663)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663#-:-KE1rGW0qQcEJYTBENyl:1417088721)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/engine/rocksdb.go, line 586 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663#-KE1rHi86igATWmurnFh:-KE1rHi86igATWmurnFi:2018444532) ([raw file](https://github.com/cockroachdb/cockroach/blob/80913ce6cb6921373457019abd6b7b060e89f998/storage/engine/rocksdb.go#L586)):*
drive by: why does this return a pointer? is there anything to be gained from converting this to a value instead of pooling?

---

*[storage/engine/rocksdb.go, line 606 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663#-KE1qyl2Z1CwYnYkztvD:-KE1qyl2Z1CwYnYkztvE:1310550745) ([raw file](https://github.com/cockroachdb/cockroach/blob/80913ce6cb6921373457019abd6b7b060e89f998/storage/engine/rocksdb.go#L606)):*
would it be safer to use `*r = rocksDBIterator{}` here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/engine/rocksdb.go, line 586 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663#-KE1rHi86igATWmurnFh:-KE1s0OAthcZoA1KtEqY:1125758847) ([raw file](https://github.com/cockroachdb/cockroach/blob/80913ce6cb6921373457019abd6b7b060e89f998/storage/engine/rocksdb.go#L586)):*
No, there is no value to returning a pointer. The `rocksDBIterator` method change internal state. And the return value will be stored in an `Iterator` interface.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663)*

**Comment by tamird** [comment]
:lgtm: modulo one comment.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/engine/rocksdb.go, line 586 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663#-KE1rHi86igATWmurnFh:-KE1tky5WD5Yjrx9JxsP:-2048280346) ([raw file](https://github.com/cockroachdb/cockroach/blob/80913ce6cb6921373457019abd6b7b060e89f998/storage/engine/rocksdb.go#L586)):*
I assume you meant "there is no value to returning a value". OK. Perhaps this method should return an `Iterator` to clarity.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663#-:-KE1tyGfFVKLdqsAa9tx:844628932)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[storage/engine/rocksdb.go, line 586 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663#-KE1rHi86igATWmurnFh:-KE1wIa1am0-4MpHQzF2:232984592) ([raw file](https://github.com/cockroachdb/cockroach/blob/80913ce6cb6921373457019abd6b7b060e89f998/storage/engine/rocksdb.go#L586)):*
Err, yes: "no value to returning a value".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663)*

**Comment by nvanbenschoten** [comment]
:lgtm: Any change to the SQL benchmarks like the caching iterators had?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/engine/rocksdb.go, line 591 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663#-KE235BSvls6qMK3IHT-:-KE235BSvls6qMK3IHT0:-1929702606) ([raw file](https://github.com/cockroachdb/cockroach/blob/80913ce6cb6921373457019abd6b7b060e89f998/storage/engine/rocksdb.go#L591)):*
Seems like we're inconsistent on the `*rocksDBIterator` variable naming, which makes this ever so slightly harder to skim and understand.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5663#-:-KE23_OB0M_0Q74CDnwk:2013460631)*

**Comment by dt** [comment]
@nvanbenschoten laptop benchmarks, so grain of salt, but:
```
Insert10_Cockroach-8                   684µs ± 3%     648µs ± 1%  -5.15%  (p=0.000 n=10+10)
Insert100_Cockroach-8                 3.15ms ± 6%    3.08ms ± 2%  -2.17%  (p=0.035 n=10+10)
Insert1000_Cockroach-8                31.8ms ±11%    29.5ms ± 2%  -7.13%  (p=0.000 n=10+10)
Update10_Cockroach-8                  1.15ms ± 1%    1.13ms ± 2%  -1.75%    (p=0.002 n=9+8)
Update100_Cockroach-8                 6.25ms ± 5%    6.15ms ± 2%  -1.70%   (p=0.035 n=9+10)
Update1000_Cockroach-8                59.2ms ± 3%    54.8ms ± 2%  -7.40%   (p=0.000 n=9+10)
Delete10_Cockroach-8                  1.38ms ± 5%    1.34ms ± 1%  -3.24%  (p=0.000 n=10+10)
Delete100_Cockroach-8                 10.3ms ± 5%     9.9ms ± 3%  -4.51%  (p=0.000 n=10+10)
Delete1000_Cockroach-8                 109ms ± 6%     104ms ± 3%  -4.60%  (p=0.001 n=10+10)
Scan10_Cockroach-8                     234µs ± 4%     226µs ± 5%  -3.59%  (p=0.004 n=10+10)
Scan100_Cockroach-8                    552µs ± 4%     539µs ± 1%  -2.30%    (p=0.000 n=9+8)
Scan1000_Cockroach-8                  3.27ms ± 2%    3.28ms ± 2%    ~       (p=0.863 n=9+9)
Scan10000_Cockroach-8                 35.3ms ± 5%    34.3ms ± 5%  -2.82%  (p=0.035 n=10+10)
Scan1000Limit10_Cockroach-8            239µs ± 3%     239µs ± 4%    ~     (p=0.971 n=10+10)
Scan1000Limit100_Cockroach-8           561µs ± 2%     556µs ± 3%    ~      (p=0.095 n=10+9)
Scan10000FilterLimit10_Cockroach-8     495µs ± 6%     481µs ± 2%  -2.72%  (p=0.019 n=10+10)
Scan10000FilterLimit50_Cockroach-8    3.70ms ± 8%    3.71ms ±12%    ~      (p=0.905 n=10+9)
Sort100000Limit10_Cockroach-8          1.92s ± 6%     2.07s ±10%    ~      (p=0.055 n=8+10)

name                                old alloc/op   new alloc/op   delta
Insert10_Cockroach-8                  65.4kB ± 0%    63.6kB ± 0%  -2.87%   (p=0.000 n=10+9)
Insert100_Cockroach-8                  471kB ± 0%     462kB ± 0%  -1.92%  (p=0.000 n=10+10)
Insert1000_Cockroach-8                4.23MB ± 0%    4.15MB ± 1%  -1.90%   (p=0.000 n=7+10)
Update10_Cockroach-8                   104kB ± 0%     101kB ± 0%  -2.91%   (p=0.000 n=10+9)
Update100_Cockroach-8                  739kB ± 0%     722kB ± 0%  -2.31%   (p=0.000 n=10+9)
Update1000_Cockroach-8                6.40MB ± 1%    6.23MB ± 1%  -2.73%   (p=0.000 n=10+9)
Delete10_Cockroach-8                  46.0kB ± 0%    44.8kB ± 0%  -2.66%   (p=0.000 n=9+10)
Delete100_Cockroach-8                  189kB ± 0%     188kB ± 0%  -0.71%  (p=0.000 n=10+10)
Delete1000_Cockroach-8                1.76MB ± 0%    1.75MB ± 0%    ~     (p=0.190 n=10+10)
Scan10_Cockroach-8                    15.2kB ± 0%    15.0kB ± 0%  -1.43%    (p=0.000 n=9+9)
Scan100_Cockroach-8                   47.5kB ± 0%    47.3kB ± 0%  -0.35%  (p=0.000 n=10+10)
Scan1000_Cockroach-8                   336kB ± 0%     336kB ± 0%  -0.03%  (p=0.000 n=10+10)
Scan10000_Cockroach-8                 5.83MB ± 0%    5.83MB ± 0%    ~      (p=0.315 n=9+10)
Scan1000Limit10_Cockroach-8           15.6kB ± 0%    15.4kB ± 0%  -1.25%  (p=0.000 n=10+10)
Scan1000Limit100_Cockroach-8          47.8kB ± 0%    47.6kB ± 0%  -0.38%   (p=0.000 n=10+8)
Scan10000FilterLimit10_Cockroach-8    53.5kB ± 0%    53.3kB ± 0%  -0.36%  (p=0.000 n=10+10)
Scan10000FilterLimit50_Cockroach-8     499kB ± 0%     498kB ± 0%  -0.12%   (p=0.000 n=10+8)
Sort100000Limit10_Cockroach-8          182MB ± 0%     182MB ± 0%  -0.00%   (p=0.013 n=9+10)

name                                old allocs/op  new allocs/op  delta
Insert10_Cockroach-8                     745 ± 0%       716 ± 0%  -3.92%   (p=0.000 n=10+8)
Insert100_Cockroach-8                  4.65k ± 0%     4.53k ± 0%  -2.55%  (p=0.000 n=10+10)
Insert1000_Cockroach-8                 43.7k ± 0%     42.7k ± 0%  -2.29%   (p=0.000 n=8+10)
Update10_Cockroach-8                   1.29k ± 0%     1.25k ± 0%  -3.42%   (p=0.000 n=10+9)
Update100_Cockroach-8                  7.36k ± 0%     7.14k ± 0%  -3.00%   (p=0.000 n=10+8)
Update1000_Cockroach-8                 64.5k ± 0%     62.5k ± 1%  -3.08%  (p=0.000 n=10+10)
Delete10_Cockroach-8                     927 ± 0%       906 ± 0%  -2.27%    (p=0.000 n=9+9)
Delete100_Cockroach-8                  4.72k ± 0%     4.70k ± 0%  -0.42%  (p=0.000 n=10+10)
Delete1000_Cockroach-8                 42.6k ± 0%     42.6k ± 0%    ~     (p=0.137 n=10+10)
Scan10_Cockroach-8                       296 ± 0%       292 ± 0%  -1.52%  (p=0.000 n=10+10)
Scan100_Cockroach-8                    1.02k ± 0%     1.02k ± 0%  -0.49%   (p=0.002 n=8+10)
Scan1000_Cockroach-8                   8.23k ± 0%     8.23k ± 0%  -0.06%   (p=0.000 n=10+9)
Scan10000_Cockroach-8                  80.4k ± 0%     80.4k ± 0%  -0.01%  (p=0.000 n=10+10)
Scan1000Limit10_Cockroach-8              307 ± 0%       303 ± 0%  -1.43%  (p=0.000 n=10+10)
Scan1000Limit100_Cockroach-8           1.03k ± 0%     1.03k ± 0%  -0.45%  (p=0.000 n=10+10)
Scan10000FilterLimit10_Cockroach-8       859 ± 0%       855 ± 0%  -0.47%   (p=0.002 n=8+10)
Scan10000FilterLimit50_Cockroach-8     10.3k ± 0%     10.2k ± 0%  -0.11%   (p=0.000 n=10+9)
Sort100000Limit10_Cockroach-8          1.74M ± 0%     1.74M ± 0%  -0.01%   (p=0.000 n=7+10)
```

**Comment by nvanbenschoten** [comment]
Wow, those translated over from the MVCC benchmarks much better than I thought they would.

**Comment by petermattis** [comment]
Benchmarking on laptops is fraught. I take those numbers with a whole sack of salt.

**Comment by tamird** [comment]
LGTM but agree with @nvanbenschoten that the naming is inconsistent. `r` instead of `i` as the variable name would be better.

**Pull request merged**
