### PR TITLE
multitenant: add can_check_consistency capability

### LINKED ISSUE #100951: multitenant: support crdb_internal.check_consistency() for secondary tenants
`crdb_internal.check_consistency()` only works for the system tenant.

Replace the guard that is preventing secondary tenants from using this builtin with a new `can_check_consistency` capability.

Jira issue: CRDB-26710

Epic CRDB-26687

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #100951

This adds support for secondary tenants to use crdb_internal.check_consistency.

The functionality is guarded by a new can_check_consistency capability that is
disabled by default.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
Very good work. LGTM (but see my comments below)
Welcoming extra review from Rafi.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-:-NSVBg7l8moo2mUBS6sq:b-w7rzh0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSV8M0M2RI2iist09Qd):*
nit: conversion

nice simplification btw :100: 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSV90x6C2XBl91YC3ze:-NSV90x6C2XBl91YC3zf:b-84ff4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5034346f75c89c18e422bd119ad3bafa95b5253f/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L92)):*
> ```protobuf
>   bool can_use_nodelocal_storage = 9;
> 
>   // CanCheckConsistency if set to true, grants the tenant the ability to check
> ```

nit: "to run range consistency checks".
___
*[`pkg/sql/logictest/logic.go` line 1573 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSV9EKRBh5ldbTFHuKj:-NSV9EKRBh5ldbTFHuKk:b-s3nhaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5034346f75c89c18e422bd119ad3bafa95b5253f/pkg/sql/logictest/logic.go#L1573)):*
> ```Go
> 				capabilityMap[capability.ID()] = v
> 			}
> 			t.cluster.WaitForTenantCapabilities(t.t(), tenantID, capabilityMap)
> ```

Why did you need to add this check in this PR?
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1972 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSV9P1EDJNiQ5s3fYvD:-NSV9P1EDJNiQ5s3fYvE:b-ytvi1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5034346f75c89c18e422bd119ad3bafa95b5253f/pkg/sql/sem/builtins/generator_builtins.go#L1972)):*
> ```Go
> 	minKey := keys.LocalMax
> 	maxKey := roachpb.KeyMax
> 	if !codec.ForSystemTenant() {
> ```

I think we can remove the check for `ForSystemTenant` here. Something like this:

```go
minKey := codec.TenantPrefix()
maxKey := minKey.PrefixEnd()
if minKey.Compare(keys.LocalMax) < 0 {
   // We cannot run consistency checks on the local keyspace. Exclude it.
   minKey = keys.LocalMax
}
```

(I am assuming here that `systemTenantCodec.TenantPrefix().PrefixEnd() == roachpb.KeyMax`. If my reading of the code is correct, that should be true; but I think you should double check).
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1979 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSVB2tmCkV2xNCAuo2h:-NSVB2tmCkV2xNCAuo2i:bfj0mft) ([raw file](https://github.com/cockroachdb/cockroach/blob/334693c1fc295d6fcf525e1e2f0fe05747170e84/pkg/sql/sem/builtins/generator_builtins.go#L1979)):*
> ```Go
> 		// would interpret LocalMax as Meta1Prefix and translate that to KeyMin,
> 		// then fail on the scan. That method should really handle this better
> 		// but also we should use IterateRangeDescriptors instead.
> ```

Could you explain (to me) why you dropped this special case?
___
*[`pkg/sql/logictest/testdata/logic_test/builtin_function` line 3995 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSVBSJIBmbb3Mx0-7Hu:-NSVBSJJ0aonLTXM5v9g:blaz6yh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5034346f75c89c18e422bd119ad3bafa95b5253f/pkg/sql/logictest/testdata/logic_test/builtin_function#L3995)):*
> ```
> query TT
> SELECT status, regexp_replace(detail, '[0-9]+', '', 'g')
> FROM crdb_internal.check_consistency(true, crdb_internal.tenant_span()[1], crdb_internal.tenant_span()[2])
> ```

pass-by comment (not blocking): this makes me wonder if `check_consistency` shouldn't have an overload which takes an array as 2nd argument, so you can pass `tenant_span()` directly.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100921)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSV8M0M2RI2iist09Qd):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: conversion

nice simplification btw :100: 
</blockquote></details>

Fixed
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSV90x6C2XBl91YC3ze:-NSfV0Fw14Wr81nrmK6y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5034346f75c89c18e422bd119ad3bafa95b5253f/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L92)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: "to run range consistency checks".
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/logic.go` line 1573 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSV9EKRBh5ldbTFHuKj:-NSfV5iSAkITPYEgtvzP:bgrxovi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5034346f75c89c18e422bd119ad3bafa95b5253f/pkg/sql/logictest/logic.go#L1573)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Why did you need to add this check in this PR?
</blockquote></details>

I added the other capability code to `logic.go` before `WaitForTenantCapabilities` existed, but did not end up using it until now. `WaitForTenantCapabilities` is needed to make sure the granted capabilities propagate to all nodes to avoid race conditions.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1972 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSV9P1EDJNiQ5s3fYvD:-NSfi6Kd22xVyo937zfM:bfdzxyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5034346f75c89c18e422bd119ad3bafa95b5253f/pkg/sql/sem/builtins/generator_builtins.go#L1972)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I think we can remove the check for `ForSystemTenant` here. Something like this:

```go
minKey := codec.TenantPrefix()
maxKey := minKey.PrefixEnd()
if minKey.Compare(keys.LocalMax) < 0 {
   // We cannot run consistency checks on the local keyspace. Exclude it.
   minKey = keys.LocalMax
}
```

(I am assuming here that `systemTenantCodec.TenantPrefix().PrefixEnd() == roachpb.KeyMax`. If my reading of the code is correct, that should be true; but I think you should double check).
</blockquote></details>

Yes, it looks like that works. I added a comment about this based on our slack conversation.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1979 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSVB2tmCkV2xNCAuo2h:-NSfiJtPBNWvYH7zAxgu:b-nc3e21) ([raw file](https://github.com/cockroachdb/cockroach/blob/334693c1fc295d6fcf525e1e2f0fe05747170e84/pkg/sql/sem/builtins/generator_builtins.go#L1979)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Could you explain (to me) why you dropped this special case?
</blockquote></details>

`ScanMetaKVs` is no longer called and it looks like the current impl works with `LocalMax` so I think the code is simpler now. Is there an issue you see with doing this?

**Review by knz — COMMENTED** [review]
Still no objections.

> Reviewed 3 of 3 files at r5, 14 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-:-NSg4x-tCm7yGvmKRS_e:bj56fsy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1979 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/100921#-NSVB2tmCkV2xNCAuo2h:-NSg4nqp8Ki8zZ4FitHT:btgd744) ([raw file](https://github.com/cockroachdb/cockroach/blob/334693c1fc295d6fcf525e1e2f0fe05747170e84/pkg/sql/sem/builtins/generator_builtins.go#L1979)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

`ScanMetaKVs` is no longer called and it looks like the current impl works with `LocalMax` so I think the code is simpler now. Is there an issue you see with doing this?
</blockquote></details>

No issue thanks.

**Comment by ecwall** [comment]
bors r=knz

**Review by rafiss — COMMENTED** [review]
the pkg/sql changes lgtm, thanks!

**Pull request merged**
