### PR TITLE
sql: implement the `DROP SCHEMA` command

### LINKED ISSUE #50884: sql: support the `DROP SCHEMA` command
As well as supporting the `WITH CASCADE` option.

### LINKED ISSUE #52362: sql: dropping a database needs to drop its child schemas
right now, we only drop the namespace entries for each child schema -- we need to drop the descriptors as well.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #50884.

This commit adds support for the `DROP SCHEMA` command, and includes
support for the cascading behavior. To accomplish this, we refactor the
recursive deleted object collection from the `DROP DATABASE` command so
that `DROP SCHEMA` can use it. Note that this commit does not clean up
schemas when dropping a database, and will be handled in a future PR.

Release note (sql change): Support the `DROP SCHEMA` command.

### CODE REVIEW

**Comment by rohany** [comment]
Depends on #52349.

**Review by ajwerner — COMMENTED** [review]
Can you rebase this?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-:-MEdqbVTD9ZlynYKoMcW:bamvymz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @pbardea)

**Comment by rohany** [comment]
Woops, i forgot to push earlier. rebased

**Review by thoszhang — APPROVED** [review]
> Reviewed 9 of 18 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @pbardea, and @rohany)

___
*[pkg/sql/drop_schema.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF1fKSC-XB2GlUrbKHy:-MF1fKSC-XB2GlUrbKHz:bo5pqu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/drop_schema.go#L87)):*
> ```Go
> 
> func (n *dropSchemaNode) startExec(params runParams) error {
> 	telemetry.Inc(sqltelemetry.SchemaChangeDropCounter("database"))
> ```

Should this be `"schema"`?
___
*[pkg/sql/drop_table.go, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF1xMdJ8n9joWnkffG_:-MF1xMdJ8n9joWnkffGa:b-6aev4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/drop_table.go#L249)):*
> ```Go
> // dropped due to `cascade` behavior. droppingParent indicates whether this
> // table's parent (either database or schema) is being dropped.
> func (p *planner) dropTableImpl(
> ```

Not for this PR, but I wonder if we should also start using something like `DropCascadeState` for collecting dependencies when dropping single tables.
___
*[pkg/sql/logictest/testdata/logic_test/schema, line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF1zWFY0gG9qMSqGoNw:-MF1zWFY0gG9qMSqGoNx:b-ijgei5) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/logictest/testdata/logic_test/schema#L192)):*
> ```
> SELECT * FROM system.descriptor WHERE id = $schema_id
> 
> # We can't resolve a schema dropped in the same transaction.
> ```

Can we have a test like this where we try to create a new schema with the old name, or rename another schema to the old name?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @lucy-zhang, and @pbardea)

___
*[pkg/sql/drop_schema.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF1fKSC-XB2GlUrbKHy:-MF29E3F2JRFHyct8Lut:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/drop_schema.go#L87)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Should this be `"schema"`?
</blockquote></details>

Done.
___
*[pkg/sql/drop_table.go, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF1xMdJ8n9joWnkffG_:-MF29EeR6CuRE-PfMBAg:bjja5ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/drop_table.go#L249)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Not for this PR, but I wonder if we should also start using something like `DropCascadeState` for collecting dependencies when dropping single tables.
</blockquote></details>

I think so, it would help us reuse this code better
___
*[pkg/sql/logictest/testdata/logic_test/schema, line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF1zWFY0gG9qMSqGoNw:-MF29J_wAsmwT7urXj2U:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/logictest/testdata/logic_test/schema#L192)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Can we have a test like this where we try to create a new schema with the old name, or rename another schema to the old name?
</blockquote></details>

done

**Review by arulajmani — APPROVED** [review]
I like this new `dropCascadeState` stuff. Left some minor comments about testing suggestions, but other than that this looks good to me 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-:-MF2AcMyAWpTrTw7ezIU:bfwu1lu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang, @pbardea, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/schema, line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF29TFB8DorgE7CmCdL:-MF29TFB8DorgE7CmCdM:b-kqn7vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/logictest/testdata/logic_test/schema#L163)):*
> ```
> # in other schemas.
> statement ok
> CREATE TABLE myschema.myschema_t1 (x INT);
> ```

Could you add some sequences in the mix here too? It would be nice to have both used and owned sequences which cross schema boundaries. 
___
*[pkg/sql/logictest/testdata/logic_test/schema, line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF2AQAlCUSMjIKFpmtt:-MF2AQAlCUSMjIKFpmtu:b-libwxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/logictest/testdata/logic_test/schema#L170)):*
> ```
> CREATE TABLE otherschema.otherschema_t1 (x INT);
> 
> statement error pq: schema "myschema" is not empty and CASCADE was not specified
> ```

nit: Maybe add a test for when the schema is empty and CASCADE isn't specified as well

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @lucy-zhang, and @pbardea)

___
*[pkg/sql/logictest/testdata/logic_test/schema, line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF29TFB8DorgE7CmCdL:-MF2E4f926T-diWBgupk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/logictest/testdata/logic_test/schema#L163)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could you add some sequences in the mix here too? It would be nice to have both used and owned sequences which cross schema boundaries. 
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/schema, line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF2AQAlCUSMjIKFpmtt:-MF2E3u74TjxGGbXEXYb:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/logictest/testdata/logic_test/schema#L170)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Maybe add a test for when the schema is empty and CASCADE isn't specified as well 
</blockquote></details>

done

**Review by ajwerner — APPROVED** [review]
This is nice, just the nit and request for some clarity from me

> Reviewed 2 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-:-MF2HcJ3A7CmE5dRLaGe:b-1qztp5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @lucy-zhang, @pbardea, and @rohany)

___
*[pkg/sql/drop_cascade.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF2G7HM3_Q5PD0eWDnT:-MF2G7HN44XWwii2Md0l:bki5426) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/drop_cascade.go#L166)):*
> ```Go
> 		var err error
> 		if desc.IsView() {
> 			// TODO(knz): dependent dropped views should be qualified here.
> ```

Do you understand what this means? I'm not sure I do and if you do, leaving more clues around, and maybe an issue would be valuable. 
___
*[pkg/sql/schema_changer.go, line 601 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF2H91B9LbMYeVj8I3j:-MF2H91B9LbMYeVj8I3k:b-xlf2vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/schema_changer.go#L601)):*
> ```Go
> 			if desc.Dropped() {
> 				if err := sc.execCfg.DB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 					b := txn.NewBatch()
> ```

nit: I don't see a reason to create an a transaction or to create a batch, the DB has an API for this. 

```
descKey := sqlbase.MakeDescMetadataKey(sc.execCfg.Codec, desc.GetID())
if err := sc.execCfg.DB.Del(ctx, descKey); err != nil {
    return err
}
```

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @pbardea)

___
*[pkg/sql/drop_cascade.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF2G7HM3_Q5PD0eWDnT:-MF2LF471spfaCoX6uj-:b-qpsc1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/drop_cascade.go#L166)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Do you understand what this means? I'm not sure I do and if you do, leaving more clues around, and maybe an issue would be valuable. 
</blockquote></details>

yeah, it means that the returned names should be qualified. Updated the comment
___
*[pkg/sql/schema_changer.go, line 601 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52726#-MF2H91B9LbMYeVj8I3j:-MF2LJns7fHd1H_rpBhn:b2nid0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e3ebe29cdb802f4876e3b87317237fc53b3947/pkg/sql/schema_changer.go#L601)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: I don't see a reason to create an a transaction or to create a batch, the DB has an API for this. 

```
descKey := sqlbase.MakeDescMetadataKey(sc.execCfg.Codec, desc.GetID())
if err := sc.execCfg.DB.Del(ctx, descKey); err != nil {
    return err
}
```
</blockquote></details>

til

**Pull request merged**
