### PR TITLE
docs: add background reading for Life of a Query

### PR DESCRIPTION
**Pull request by erikgrinaker**
Add info on background topics that may be useful before reading the
document.

Release note: None

I'm sure everyone has an opinion on the best background material. I just
referred to Wikipedia and a few of my favorite books, but perhaps the
Wikipedia references in particular could be replaced by more
comprehensive resources.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
I'm slightly apprehensive about calling these "prerequisites" - we shouldn't tell people that you can't read this doc until you've read all of these other sources. We should supply them as supplemental materials that may be worth a look if unfamiliar concepts show up in the doc.

**Comment by erikgrinaker** [comment]
>I'm slightly apprehensive about calling these "prerequisites" - we shouldn't tell people that you can't read this doc until you've read all of these other sources. We should supply them as supplemental materials that may be worth a look if unfamiliar concepts show up in the doc.

I agree, it wasn't really meant as prereqs as such -- reworded it a bit.

**Review by tbg — APPROVED** [review]
That re-wording is great, thanks!

**Comment by aliher1911** [comment]
Does this section belong to this document though? I think it is as relevant to this doc as to other docs in this directory. Maybe it should be placed in top level readme or a separate doc. Otherwise we could end up with slightly different background reading section in every file.

**Comment by erikgrinaker** [comment]
>Does this section belong to this document though? I think it is as relevant to this doc as to other docs in this directory. Maybe it should be placed in top level readme or a separate doc. Otherwise we could end up with slightly different background reading section in every file.

This is true. @AlexTalks thought it would be helpful, as he's just reading through this for the first time now. I suppose we could split it out as a separate file and link to it, but I am a bit worried that it'll just turn into a huge list of random reading material that can be overwhelming to a newcomer.

**Review by andreimatei — COMMENTED** [review]
I personally wouldn't include these links in this doc; they're all seem either fairly superficial or otherwise trivial Wiki links. I thinks the links to the CMU series and to the Data-Intensive book deserve to exist somewhere; don't know if here tho.

But as you see fit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66652#-:-Mcj98l16lOy9_sqAaF-:b3nixmr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

**Comment by aliher1911** [comment]
Shouldn't we put them on a wiki: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/16646155/Database+Background or we want it to be publicly visible? I think that page captures exactly this kind of links, maybe we should mirror it in the docs if we want it to be part of repo.

**Comment by erikgrinaker** [comment]
Yeah, I'll move this there.

**Comment by erikgrinaker** [comment]
Better late than never: https://cockroachlabs.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=16646155&selectedPageVersions=12&selectedPageVersions=11

**Pull request closed without merging**
