### PR TITLE
sql: complete the implementation of extra_float_digits

### PR DESCRIPTION
**Pull request by knz**
First commit from #27951.

The code previously recognized the name of the session variable but
completely ignored the value that was specified. This would cause
silently invalid results to be processed in conversions from float to
string, and when float values are returned over pgwire.

This patch fixes the situation by making the setting work as intended
by clients.

Release note (sql change): The support for `extra_float_digits` is
extended for compatibility with PostgreSQL.

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm:

You should mention the addition of dataconversion and the movement of location and bytesEncodeFormat into it in the commit message.  It's clear from reading the code why this was a good idea, but not from the commit message.

Just some minor comments otherwise

**Comment by knz** [comment]
you haven't posted the minor comments?

**Review by BramGruneir — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 29 of 29 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27952)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/vars.go, line 384 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM4H-V8uueNCfOmjzf:-LIM4H-V8uueNCfOmjzg:b-h5xa22) ([raw file](https://github.com/cockroachdb/cockroach/blob/20de1cd72420be59f7fda9af984b97c4867e6320/pkg/sql/vars.go#L384)):*
> ```Go
> 				return err
> 			}
> 			if s < -15 || s > 3 {
> ```

add a comment to look at the explanation in dataconversion.
___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 534 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM1F6P4jm1ULqF1tdY:-LIM1F6P4jm1ULqF1tdZ:b-ssu571) ([raw file](https://github.com/cockroachdb/cockroach/blob/02a660f1154bca3f787f17450085b89cd78bf7d4/pkg/sql/logictest/testdata/logic_test/builtin_function#L534)):*
> ```
> 
> query RR
> SELECT acos(-0.5), round(acos(0.5), 15)
> ```

Please rerun all of these with a different values for extra_float_digits.
___
*[pkg/sql/logictest/testdata/logic_test/float, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM1VDHA_U3E_BIFk9P:-LIM1VDHA_U3E_BIFk9Q:b592e65) ([raw file](https://github.com/cockroachdb/cockroach/blob/20de1cd72420be59f7fda9af984b97c4867e6320/pkg/sql/logictest/testdata/logic_test/float#L85)):*
> ```
> CREATE UNIQUE INDEX ON i (f)
> 
> statement ok
> ```

subtest please
___
*[pkg/sql/pgwire/types_test.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM2qjX-qxKd1bAFjWD:-LIM2qjX-qxKd1bAFjWE:bwpb5fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/20de1cd72420be59f7fda9af984b97c4867e6320/pkg/sql/pgwire/types_test.go#L164)):*
> ```Go
> 		{123.4567890123456789, -10, "123.46"},
> 		{123.4567890123456789, -13, "1.2e+02"},
> 		{123.4567890123456789, -15, "1e+02"},
> ```

Test error cases with values > 3 and < -15 please.
___
*[pkg/sql/sessiondata/session_data.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM3VG81Tl0_qM2OE1I:-LIM3VG81Tl0_qM2OE1J:b-begxh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/20de1cd72420be59f7fda9af984b97c4867e6320/pkg/sql/sessiondata/session_data.go#L113)):*
> ```Go
> 	// expose DBL_DIG, so we use the standard literal constant for
> 	// 64bit floats.
> 	const DblDig = 15
> ```

Why not DoubleDigits?  Unless there's a known convention here.
___
*[pkg/sql/sessiondata/session_data.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM3LkmA9SA8rGuSRHL:-LIM3Lkn1e3AXmxVzw6-:b-j8zm6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/20de1cd72420be59f7fda9af984b97c4867e6320/pkg/sql/sessiondata/session_data.go#L115)):*
> ```Go
> 	const DblDig = 15
> 
> 	ndig := DblDig + c.ExtraFloatDigits
> ```

Please be more verbose in the name here, numberDigits would be a bit easier to read,

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27952)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/vars.go, line 384 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM4H-V8uueNCfOmjzf:-LIMAvo-1jFU84p5wKyp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20de1cd72420be59f7fda9af984b97c4867e6320/pkg/sql/vars.go#L384)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

add a comment to look at the explanation in dataconversion.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 534 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM1F6P4jm1ULqF1tdY:-LIMB9Sj-S6SN_b5PMyx:b-6ogsqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/02a660f1154bca3f787f17450085b89cd78bf7d4/pkg/sql/logictest/testdata/logic_test/builtin_function#L534)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please rerun all of these with a different values for extra_float_digits.
</blockquote></details>

Interestingly, some values hit bugs in the Go standard library! What a sorry piece of software.
I don't want to care about this. Used some arbitrary value that don't trigger the bug.
___
*[pkg/sql/logictest/testdata/logic_test/float, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM1VDHA_U3E_BIFk9P:-LIMClu-AXa9yxqn9eoq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20de1cd72420be59f7fda9af984b97c4867e6320/pkg/sql/logictest/testdata/logic_test/float#L85)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

subtest please
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/types_test.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM2qjX-qxKd1bAFjWD:-LIMEHa_D9IiHATxy8Cv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20de1cd72420be59f7fda9af984b97c4867e6320/pkg/sql/pgwire/types_test.go#L164)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Test error cases with values > 3 and < -15 please.
</blockquote></details>

Done.
___
*[pkg/sql/sessiondata/session_data.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM3VG81Tl0_qM2OE1I:-LIMDuV9A63lM0Olxg9A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20de1cd72420be59f7fda9af984b97c4867e6320/pkg/sql/sessiondata/session_data.go#L113)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not DoubleDigits?  Unless there's a known convention here.
</blockquote></details>

Done.
___
*[pkg/sql/sessiondata/session_data.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-LIM3LkmA9SA8rGuSRHL:-LIMDvSs8GzL3WYVtDyx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20de1cd72420be59f7fda9af984b97c4867e6320/pkg/sql/sessiondata/session_data.go#L115)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please be more verbose in the name here, numberDigits would be a bit easier to read,
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
I also extended the commit message as suggested.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-:-LIMKjX38yHWQMw4gKYV:bn0g7f4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27952#-:-LIMMKUbCHSd0pGZ5a-B:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
thanks!

**Pull request merged**
