### PR TITLE
streamingest: increase initial split TTLs

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
👍 Nice catch. I wonder how much this accounts for the throughput collapse you've seen in some of the larger-scale testing.

Left some comments but take them or leave them.

**Comment by dt** [comment]
> I wonder how much this accounts for the throughput collapse you've seen in some of the larger-scale testing

That's my theory, but it doesn't appear to be substantiated by the merge queue stats. That said, I see _no_ splits in `ranges_no_leases` above table 108 when I check back a day later, so maybe and I'm just misreading the merge queue chart. Either way, it seems the LtR fill means rightmost splits need more time to be justified by size.

**Comment by dt** [comment]
We still see throughput fall off a cliff after a couple hours even with this change, and I've confined the splits above the table that is seeing ingestions are still there, so this isn't a silver bullet. Still seems like a good idea, but something else yet to be found is causing the drop-off. _Something_ appears to cause a ton of leaseholder movement and then the ingestion rate tanks and compactions spike, but I'm still looking for exactly what.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
