### PR TITLE
parser: batch some allocations in the scanner

### PR DESCRIPTION
**Pull request by RaduBerinde**
The scanner allocates copies of all uppercase identifiers; preallocate
a buffer (proportional to the size of the query) to save some of these
allocations.

Benchmark:
```
name   old time/op    new time/op    delta
Parse    33.8µs ± 1%    33.7µs ± 1%     ~     (p=0.699 n=6+6)

name   old alloc/op   new alloc/op   delta
Parse    5.54kB ± 0%    5.68kB ± 0%   +2.60%  (p=0.002 n=6+6)

name   old allocs/op  new allocs/op  delta
Parse      92.0 ± 0%      81.0 ± 0%  -11.96%  (p=0.002 n=6+6)
```

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
OMG YESSSSSSSSS

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32805)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/scan.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-LSqaFjp4fgM2dD9cBfA:-LSqaFjp4fgM2dD9cBfB:b-aiip9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d45ab86b886b2c35eb3c65bb96b09a515032ed96/pkg/sql/parser/scan.go#L76)):*
> ```Go
> 	s.initialized = true
> 	s.in = str
> 	// Preallocate some buffer space for identifiers etc.
> ```

Leave a note about how this was sized.
___
*[pkg/sql/parser/scan.go, line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-LSqabdN3cblaR8Zpp9t:-LSqabdN3cblaR8Zpp9u:b-gkjgbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d45ab86b886b2c35eb3c65bb96b09a515032ed96/pkg/sql/parser/scan.go#L826)):*
> ```Go
> // scanHexString scans the content inside x'....'.
> func (s *Scanner) scanHexString(lval *sqlSymType, ch int) bool {
> 	buf := s.allocBytes(4)[:0]
> ```

This is just a guess, right? Seems like we could do something better in these cases by keeping a preallocated slice around that we could write into and use wherever necessary.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32805)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/scan.go, line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-LSqabdN3cblaR8Zpp9t:-LSqhYh88_8CTRT5ztSn:bocy81z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d45ab86b886b2c35eb3c65bb96b09a515032ed96/pkg/sql/parser/scan.go#L826)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is just a guess, right? Seems like we could do something better in these cases by keeping a preallocated slice around that we could write into and use wherever necessary.
</blockquote></details>

Yeah, it's basically just to save on a couple of initial small allocs. This becomes a `string` so we can't reuse buffers.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32805)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/scan.go, line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-LSqabdN3cblaR8Zpp9t:-LSqi46A90cR7BiTahPi:b-sd4lt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d45ab86b886b2c35eb3c65bb96b09a515032ed96/pkg/sql/parser/scan.go#L826)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, it's basically just to save on a couple of initial small allocs. This becomes a `string` so we can't reuse buffers.
</blockquote></details>

Or are you suggesting using a preallocated slice and then making a copy of the right size at the end? 

Anyway, I'll leave this for another change (I don't think these are even covered by the current benchmark).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32805)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/parser/scan.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-LSqaFjp4fgM2dD9cBfA:-LStrwN9-inH2DKQo95t:b8okn06) ([raw file](https://github.com/cockroachdb/cockroach/blob/d45ab86b886b2c35eb3c65bb96b09a515032ed96/pkg/sql/parser/scan.go#L76)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Leave a note about how this was sized.
</blockquote></details>

To be honest I think that value happens to work fine for the benchmark but doesn't make much sense otherwise. I changed it to the length of the string. The benchmark results look similar, except they allocate a tad more (in terms of size).

**Review by nvb — APPROVED** [review]
:lgtm: final comment doesn't need to block review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-:-LSuU304BWW71BLrIgOY:b6iq5g0)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/parser/scan.go, line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-LSqabdN3cblaR8Zpp9t:-LSuTxE-DN0hbYP9mY07:bcpek1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d45ab86b886b2c35eb3c65bb96b09a515032ed96/pkg/sql/parser/scan.go#L826)):*
> Or are you suggesting using a preallocated slice and then making a copy of the right size at the end?

Do we even need the copy? Would it be ok to perform an unsafe bytes -> string cast?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/parser/scan.go, line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-LSqabdN3cblaR8Zpp9t:-LSuVW2d5PmGKo1esRUg:bitqcvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d45ab86b886b2c35eb3c65bb96b09a515032ed96/pkg/sql/parser/scan.go#L826)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Or are you suggesting using a preallocated slice and then making a copy of the right size at the end?

Do we even need the copy? Would it be ok to perform an unsafe bytes -> string cast?
</blockquote></details>

This is in the context of your suggestion of reusing a slice. We can reuse, or we can do an unsafe cast, but not both..

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32805)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/parser/scan.go, line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-LSqabdN3cblaR8Zpp9t:-LSuW0-A3Dl9qtr0UYJd:b-y8au1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d45ab86b886b2c35eb3c65bb96b09a515032ed96/pkg/sql/parser/scan.go#L826)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is in the context of your suggestion of reusing a slice. We can reuse, or we can do an unsafe cast, but not both..
</blockquote></details>

Oh I was never recommending reusing a slice, but I see how the original wording here might make it sound like that. I just meant that we could do something similar to `strings.Builder` (without guessing at the size of a prealloc), but continue using the unused portions of the backing buffer across multiple output strings.

**Review by nvb — APPROVED** [review]

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32805)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/parser/scan.go, line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-LSqabdN3cblaR8Zpp9t:-LSufJ3Q-G7UQTOYwtuR:bz0wakl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d45ab86b886b2c35eb3c65bb96b09a515032ed96/pkg/sql/parser/scan.go#L826)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Oh I was never recommending reusing a slice, but I see how the original wording here might make it sound like that. I just meant that we could do something similar to `strings.Builder` (without guessing at the size of a prealloc), but continue using the unused portions of the backing buffer across multiple output strings.
</blockquote></details>

Ok, PTAL. I added a facility to "steal" the buffer and then return the unused portion. I also added more benchmarks (see the commit msg for results).

**Review by nvb — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32805#-:-LT--sPYB2rx7ZHaiHE2:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
