### PR TITLE
ui: show tables from user defined schemas in web ui

### LINKED ISSUE #53486: ui: does not show tables in user-defined schemas under the "Databases" page
Tables created in a user-defined schema do not show up under Databases>Tables page

image

```
root@127.0.0.1:63916/vy> show tables
                      -> ;
  schema_name | table_name | type  | estimated_row_count
--------------+------------+-------+----------------------
  public      | users      | table |                   0
  schema1     | users      | table |                   0
(2 rows)
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, the web ui did not show tables that were defined inside of
user-defined schemas. This commit corrects the problem.

Fixes #53486

Note that this commit changes the request/response protocol of the show
database details, show table details, and show table stats admin APIs to
include the schema name in the table name. The reason it was done this
way as opposed to a more comprehensive redoing of the admin APIs to
include a schema field in the request/response format is that doing that
would request a much larger overhaul of the web ui to include schemas as
a first class object, which we weren't prepared to do this late in the
release cycle.

Hopefully, we can elevate schemas to a first class concept sometime in
the future and remove this hack by adding a first class "schema" field
to the request/response format.

Release note (admin ui change): the admin ui's databases tab now
includes tables that live within user-defined schemas.

### CODE REVIEW

**Comment by jordanlewis** [comment]
image

image

Getting the escapes right in this was very irritating. I think I tested the cases that are important. Here is a screenshot that tries to prove that things work okay with weird situations.

**Comment by otan** [comment]
does this have to be backwards compatible? `crdb_internal.get_namespace_id` should remain for one more version if so.

**Comment by jordanlewis** [comment]
Good call, that was careless!

**Review by ajwerner — COMMENTED** [review]
This didn't turn out to be so bad. Nice that we didn't need to change the javascript. Looks like there's some minor testing fallout in the names of files in the debug zip. 

:raised_hands: for shepherding us over the :ocean:.

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54297#-:-MH-aJ-l7B-6f-700foZ:b-ktc0yr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jordanlewis)

___
*[docs/generated/sql/functions.md, line 2418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54297#-MH-aFNr51QfMVVkoRm4:-MH-aFNr51QfMVVkoRm5:b6qckp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0df63580f0c20c1ba5be0ce678c3ae358fce0f07/docs/generated/sql/functions.md#L2418)):*
> ```Markdown
> <tr><td><a name="crdb_internal.force_retry"></a><code>crdb_internal.force_retry(val: <a href="interval.html">interval</a>) &rarr; <a href="int.html">int</a></code></td><td><span class="funcdesc"><p>This function is used only by CockroachDB’s developers for testing purposes.</p>
> </span></td></tr>
> <tr><td><a name="crdb_internal.get_database_id"></a><code>crdb_internal.get_database_id(name: <a href="string.html">string</a>) &rarr; <a href="int.html">int</a></code></td><td></td></tr>
> ```

seems like this needs a regen now that we're retaining the function.
___
*[pkg/server/admin.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54297#-MH-an6A9Lbs26maFRGq:-MH-an6A9Lbs26maFRGr:b-9qpt8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0df63580f0c20c1ba5be0ce678c3ae358fce0f07/pkg/server/admin.go#L326)):*
> ```Go
> 		sessiondata.InternalExecutorOverride{User: userName},
> 		`SELECT table_schema, table_name FROM information_schema.tables
> WHERE table_catalog = $1 AND table_type != 'SYSTEM VIEW';`, req.Database)
> ```

Does this work? I thought `information_schema`gets interpreted as a schema inside the implied database context. This ends up being pretty great because it means we can fetch all of the descriptors from a given database but I don't think this is the way to do that. I think you want to shove the database into the sessiondata, at which point I don't think you'll need the predicate on table_catalog. The query to get all of the tables from all of the databases in cockroach is `SELECT * FROM "".information_schema.tables`

Also fun fact I just learned is that materialized views don't show up in `information_schema.tables` in postgres. We show them in information_schema as a `VIEW` and in `SHOW TABLES` as a `materialized view`
___
*[pkg/server/admin.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54297#-MH-Zv7O-se4Jov7GUUQ:-MH-Zv7O-se4Jov7GUUR:bv3pw2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0df63580f0c20c1ba5be0ce678c3ae358fce0f07/pkg/server/admin.go#L380)):*
> ```Go
> }
> 
> func getFullyQualifiedTableName(
> ```

This deserves a comment about why this exists and what it expects and what it returns

**Comment by jordanlewis** [comment]
PTAL, sorry this took an age and a half.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/server/admin.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54297#-MH-an6A9Lbs26maFRGq:-MIJoCdMAM1sKa42UCWP:b-v0w6pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0df63580f0c20c1ba5be0ce678c3ae358fce0f07/pkg/server/admin.go#L326)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Does this work? I thought `information_schema`gets interpreted as a schema inside the implied database context. This ends up being pretty great because it means we can fetch all of the descriptors from a given database but I don't think this is the way to do that. I think you want to shove the database into the sessiondata, at which point I don't think you'll need the predicate on table_catalog. The query to get all of the tables from all of the databases in cockroach is `SELECT * FROM "".information_schema.tables`

Also fun fact I just learned is that materialized views don't show up in `information_schema.tables` in postgres. We show them in information_schema as a `VIEW` and in `SHOW TABLES` as a `materialized view`
</blockquote></details>

Anything on this?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/server/admin.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54297#-MH-an6A9Lbs26maFRGq:-MHo9c0HCBvFTZk1zB8l:b-qs00eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0df63580f0c20c1ba5be0ce678c3ae358fce0f07/pkg/server/admin.go#L326)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Anything on this? 
</blockquote></details>

It seems to work fine. The reason is that, I believe, the root user sees all tables in `information_schema.tables`. I had this comment from a while ago and forgot to publish.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/server/admin.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54297#-MH-an6A9Lbs26maFRGq:-MIK6E7sDncbPrzkYgUj:b-bjrwa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0df63580f0c20c1ba5be0ce678c3ae358fce0f07/pkg/server/admin.go#L326)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It seems to work fine. The reason is that, I believe, the root user sees all tables in `information_schema.tables`. I had this comment from a while ago and forgot to publish.
</blockquote></details>

What I'd saying is that this is just much less efficient. It works not because the root user sees all tables but because the current database for the internal executor when you don't set the override is `""`.

**Comment by jordanlewis** [comment]
PTAL

**Review by ajwerner — APPROVED** [review]
remove the stray println and :lgtm: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54297#-:-MIL5pdJChUCYFUex8XU:b4nepwd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/server/admin.go, line 683 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54297#-MIL5e9a2h3zBtBWr1O1:-MIL5e9b5wBHxZ0gUJns:b-pi9d9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a18b69edac850787116313cfa0387956a6495a/pkg/server/admin.go#L683)):*
> ```Go
> 	}
> 	tableSpan := generateTableSpan(tableID)
> 	fmt.Println("TAAAAAA", tableID)
> ```

remove this

**Review by ajwerner — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54297#-:-MIMcIb_62WoXrMBWdpC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @jordanlewis)

**Pull request merged**
