### PR TITLE
release-20.2: rowexec: fix metadata propagation in zigzag joiner

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport 1/3 commits from #54377.
Backport 1/1 commits from #55610.

/cc @cockroachdb/release

---

**rowexec: fix metadata propagation in zigzag joiner**

This commit refactors the zigzag joiner slightly to be more similar to
other processors. Most notable change is the removal of `producerMeta`
method and switching to returning an error and moving to draining
instead. In fact, previous behavior of metadata propagation was
incorrect in some cases when two or more metadata records needed to be
returned, and this is now fixed.

This commit also fixes an issue of zigzag joiner not propagating a leaf
txn final state metadata which could lead to a write skew. Additionally,
this commit adds low-level tests that verify that all reader-processors
output the leaf txn final state meta as well as trace meta.

Release note (bug fix): Fixed possible write skew in distributed queries
that have both zigzag joins and table readers with the zigzag joins
reading keys not read by the table readers. Note that although this
sounds scary, the bug itself is very rare.

**rowexec: fix recent refactor of zigzag joiner**

In a recent refactor of zigzag joiner I introduced a helper method that
could emit an error which would force the processor to move to draining.
The issue is that this could happen regardless of the current state of
the processor which breaks the contract (namely, we could try to move to
draining state twice). This is now fixed.

Release note: None (no release with the bug)

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55563)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/rowexec/zigzagjoiner.go, line 922 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55563#-MJgAvlS306nF-q-d-Oc:-MJgAvlTA_Glt2V9z0XM:b-h9j8ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f5cd5624908d1852448164da4421540f4ea23ac/pkg/sql/rowexec/zigzagjoiner.go#L922)):*
> ```Go
> // Next is part of the RowSource interface.
> func (z *zigzagJoiner) Next() (rowenc.EncDatumRow, *execinfrapb.ProducerMetadata) {
> 	if err := z.maybeFetchInitialRow(); err != nil {
> ```

SQLLite logic tests have shown that this needs to be reworked.

**Comment by yuzefovich** [comment]
Updated the backport to include fix from #55610.

**Comment by asubiotto** [comment]
LGTM for 20.2.1 but why doesn't the first commit have a release note if it fixes a real bug? In my opinion, we shouldn't be backporting commits that we don't write release notes for (i.e. either the commit is important enough to the customer to deserve a release note, or the commit is not important enough to backport)

**Review by asubiotto — APPROVED** [review]

**Comment by yuzefovich** [comment]
I didn't write the release note for that commit because the conditions under which the bug would represent itself are pretty hard to describe (something like [this](https://github.com/cockroachdb/cockroach/pull/54377#issuecomment-707369314)) and I don't think such blurb would be helpful to our customers. Still, it does fix a bug, so I think it's worth backporting on 20.2 branch. Does this sound reasonable to you? What do you think about backporting to 20.1? For some reason I'm less eager to backport there.

**Comment by asubiotto** [comment]
You don't have to specifically describe the bug, you can describe the conditions in which the bug can happen (e.g. "fixed possible write skew in queries using zigzag joins" or something like that)

**Comment by yuzefovich** [comment]
My concern is that such description is a lot more general than the cases when the bug can actually occur, and it sounds really bad and scary, and although the bug is bad, it should be extremely rare if my current understanding of the conditions is correct.

Ok, I'll add a release note.

**Comment by yuzefovich** [comment]
Added the release note, but what do you think about backporting to 20.1? I'm on the fence here.

**Comment by asubiotto** [comment]
You can also call out that the bug is rare in the release note which makes it sounds less scary. What puts you on the fence for 20.1?

**Comment by yuzefovich** [comment]
Updated the release note.

I guess I'm being on the fence in regards to 20.1 backport because of my recent experience of backporting a fix for a bug that no one has reported and introducing an even worse one. Hm, the changes here are better tested and better isolated, so I think backport of this is pretty safe.

**Comment by asubiotto** [comment]
> the changes here are better tested and better isolated, so I think backport of this is pretty safe.

I agree

**Pull request merged**
