### PR TITLE
[DNM] ccl/gssapiccl: add GSS authentication support on Linux

### PR DESCRIPTION
**Pull request by madelynnblue**
This PR has a build error when running `make libkrb5`. When I run `make -n libkrb5` and run the outputted commands by hand, it works fine. When running in make it fails, so I'm not sure what's going on here. Does make set some ENV variables or something that causes the problem here? Further, the problem appears to be with `configure`. When I run make by hand in the build dir after this it still fails. Conversely, when I run the configure by hand and then `make libkrb5` it succeeds. Can someone else reproduce this failure? cc @petermattis @knz

### CODE REVIEW

**Comment by petermattis** [comment]
I'll take a look at this tomorrow.

**Comment by mjibson** [comment]
This is happening because CFLAGS and/or CXXFLAGS are both set to `-g1`. That is, if I run `CFLAGS=-g1 CXXFLAGS=-g1 ~/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/configure --enable-static --disable-shared` then `make` I can reproduce the problem. Interestingly, running them with hardcoded empty values (`CFLAGS= CXXFLAGS= ~/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/configure --enable-static --disable-shared`) makes a different problem. Seems they need to be unset? Tried a few things but haven't figured out how to do this in the Makefile yet.

**Comment by petermattis** [comment]
@mjibson Ok. That should be easy to fix. I'll take a look this morning.

**Review by petermattis — COMMENTED** [review]
I think this is nearly there. Just a few small tweaks to the Makefile and `pkg/ccl/gssapiccl`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34033#-:-LWMJrdRCvAT3wsDgetl:b-vyoku2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34033#-LWMJJKH-B7a3XQGCXyk:-LWMJJKH-B7a3XQGCXyl:bfwwgy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f02750bd971a67b9727b247a4a2dae85420293d8/Makefile#L444)):*
> ```Makefile
> C_LIBS_COMMON = $(if $(use-stdmalloc),,$(LIBJEMALLOC)) $(LIBPROTOBUF) $(LIBSNAPPY) $(LIBROCKSDB)
> C_LIBS_OSS = $(C_LIBS_COMMON) $(LIBROACH)
> C_LIBS_CCL = $(C_LIBS_COMMON) $(LIBCRYPTOPP) $(LIBROACHCCL) $(LIBKRB5)
> ```

We only want to build krb5 on linux, right? I think you need something like this:

```
C_LIBS_CCL = $(C_LIBS_COMMON) $(LIBCRYPTOPP) $(LIBROACHCCL)

# We only include krb5 on linux.
ifeq "$(findstring linux,$(TARGET_TRIPLE))" "linux"
C_LIBS_CCL += $(LIBKRB5)
endif
```
___
*[Makefile, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34033#-LWMIR7V7uH6ei7ULZll:-LWMIR7V7uH6ei7ULZlm:b8os8j2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f02750bd971a67b9727b247a4a2dae85420293d8/Makefile#L543)):*
> ```Makefile
> 	@# $(C_DEPS_DIR)/krb5-rebuild. See above for rationale.
> 	# If CFLAGS is set to -g1 then make will fail. Use "env -" to clear the environment.
> 	cd $(KRB5_DIR) && env - PATH="$$PATH" $(KRB5_SRC_DIR)/configure $(xconfigure-flags) --enable-static --disable-shared
> ```

`env -u CFLAGS` would be better than completely clearing the environment.
___
*[pkg/ccl/gssapiccl/gssapi.go, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34033#-LWMJT--A1HxwR5S8i3Z:-LWMJT--A1HxwR5S8i3_:b-9fr1pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f02750bd971a67b9727b247a4a2dae85420293d8/pkg/ccl/gssapiccl/gssapi.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> // +build linux
> ```

This is problematic on non-linux platforms because this package then has no-buildable Go files:

```
go build github.com/cockroachdb/cockroach/pkg/ccl/gssapiccl: build constraints exclude all Go files in /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/ccl/gssapiccl
```

I'd move this file to `gssapi_linux.go` and create an empty `gssapi_generic.go` file with a build tag of `!linux`.

**Comment by knz** [comment]
Why use `linux` as build tag and not simply `unix`? This code seems to work fine on BSD too.

**Comment by petermattis** [comment]
> Why use linux as build tag and not simply unix? This code seems to work fine on BSD too.

Just erring on the side that we know works. Also, `unix` isn't a build tag for Go. The code doesn't seem to work on Darwin (at least the krb5 build did not work for me). If you can test on a BSD and it work, we can easily add that tag to the mix.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34033)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34033#-LWMPdJ99RuxxzcND9s5:-LWMPdJ99RuxxzcND9s6:b-4s3e0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f02750bd971a67b9727b247a4a2dae85420293d8/Makefile#L482)):*
> ```Makefile
> 	@echo >> $@
> 	@echo '// #cgo CPPFLAGS: -I$(JEMALLOC_DIR)/include' >> $@
> 	@echo '// #cgo LDFLAGS: $(addprefix -L,$(CRYPTOPP_DIR) $(PROTOBUF_DIR) $(JEMALLOC_DIR)/lib $(SNAPPY_DIR) $(ROCKSDB_DIR) $(LIBROACH_DIR) $(KRB5_DIR)/lib)' >> $@
> ```

You'll also want to avoid adding `$(KRB5_LIB)/lib` to this line when not build on linux. Something like:

```
$(if $(findstring linux,$(TARGET_TRIPLE)),$(KRB5_DIR/lib))
```

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34033)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34033#-LWMPdJ99RuxxzcND9s5:-LWMQ2CP8CDfmbvexc-D:b-neyd9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f02750bd971a67b9727b247a4a2dae85420293d8/Makefile#L482)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You'll also want to avoid adding `$(KRB5_LIB)/lib` to this line when not build on linux. Something like:

```
$(if $(findstring linux,$(TARGET_TRIPLE)),$(KRB5_DIR/lib))
```
</blockquote></details>

Err, `$(if $(findstring linux,$(TARGET_TRIPLE)),$(KRB5_DIR)/lib)`.

**Pull request closed without merging**
