### PR TITLE
cli: bump libedit: fix multiline histories (again)

### PR DESCRIPTION
**Pull request by jordanlewis**
The previous bump to libedit had a fix to the problem of multi-line
histories including spaces for padding instead of newlines, but it
introduced a new problem: multiline histories with more than 2 lines
would restore incorrectly when the cursor was at the bottom of the
screen. This was due to an older bug in libedit that used the DO (aka
cud or parm_down_cursor) termcap to move the cursor vertically even when
the cursor was at the bottom of the terminal, which produces undefined
behavior according to the termcap manual.

The fix removes that undefined behavior, correcting the problem.

Release note (bug fix): restoring multi-line CLI histories in the SQL
shell no longer produces terminal anomalies when the cursor is on the
last line of the screen.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38505)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by benesch — APPROVED** [review]
🎉🎉🎉

**Comment by knz** [comment]
As discussed here http://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=54329

I think your problem is more specifically related to the osx terminal, and not to libedit, and therefore that this patch may not be the right fix.

**Comment by benesch** [comment]
Just to be clear: you are testing multi line entries that have two
contiguous new lines, right? A three line entry is not sufficient to
trigger the bug if it does not have two contiguous newline characters.
I.e., the entry must have a blank line between two non blank lines.

**Comment by knz** [comment]
I tried again with multiple combinations of multiple empty lines, large/long lines, etc.

I think I ran about 50 combinations of entry/terminals (5 terms x 10 inputs) and each of them went through different combinations of history recalls, that was quite the ordeal. 

The outcome is... well, I saw the issue you described *once*. The moment it did reproduce, I was joyful and I started to write down repro instructions (something with the input being re-drawn having to be shorter on non-empty lines than the previous input displayed, I thought libedit was not properly clearing the bottom of the terminal when re-drawing). However then I tried to follow my own repro steps and then I was not able to reproduce it again. :crying_cat_face: 

I'll side with Jordan and the upstream maintainer with removing an optimization designed at a time when drawing a newline over a modem was slower than sending two escape codes. It simplifies the code.

However I stand by my point that this is a bit of a case of macOS brokenness making people spend a lot of time.

**Comment by jordanlewis** [comment]
Definitely possible that macOS makes it worse, but I stick to my guns with the undefined behavior thing. Anyway, for the record, we tried with both Terminal.app and iTerm, with both xterm and xterm-256color as $TERM.

**Comment by benesch** [comment]
I really don't think this is specific to macOS at all. Here's a video of me reproducing the issue in xterm on NetBSD: https://www.youtube.com/watch?v=_11p93_ylyk.

**Pull request merged**
