### PR TITLE
sql: allow non-admins to use crdb_internal.get_fully_qualified_table_name

### PR DESCRIPTION
**Pull request by rafiss**
This builtin was recently added, but since it was implemented with a query on system.namespace, only admins could use the function.

To address this, we add a new virtual view named
crdb_internal.fully_qualified_names which does the query on system.namespace, and which allows normal users to query it. There is still a privilege check such that rows will only be included in the view if the user has the CONNECT privilege on the database the object belongs to. This privilege check is how name visibility is decided in other pg_catalog tables. Also, all users have CONNECT privilege on every database by default.

Epic: none
informs: #129744
Release note: None

### CODE REVIEW

**Review by azhu-crl — APPROVED** [review]
LGTM! Thanks for working on this

**Review by dt — APPROVED** [review]

**Review by spilchen — COMMENTED** [review]
The change looks good to me. I just have a question about the privilege validation.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129888#-:-O5UWM183O51UHPfHv71:b-gyytbc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 9303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129888#-O5UVHPC9rNIHOUWKhWW:-O5UVHPC9rNIHOUWKhWX:b-8f1yzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0efceac21947fc15ab9f44199931b17df1900ad/pkg/sql/crdb_internal.go#L9303)):*
> ```Go
> 			-- Filter rows that the user should not be able to see. This check matches
> 			-- how metadata visibility works for pg_catalog tables.
> 			AND has_database_privilege(db.name, 'CONNECT')`,
> ```

Should we specify the schema for this function? I think it should be `pg_catalog`. It might not matter, though, if users can't create a function with the same name.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129888)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @arjunmahishi, @rytaft, and @spilchen)

___
*[`pkg/sql/crdb_internal.go` line 9303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129888#-O5UVHPC9rNIHOUWKhWW:-O5UZy4jBstDAmZyu_Tr:bkxa1d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0efceac21947fc15ab9f44199931b17df1900ad/pkg/sql/crdb_internal.go#L9303)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Should we specify the schema for this function? I think it should be `pg_catalog`. It might not matter, though, if users can't create a function with the same name.
</blockquote></details>

this is a good idea -- they could create one with the same one

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129888#-:-O5UmabG1piLVTOmMT26:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @arjunmahishi, and @rytaft)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
