### PR TITLE
util/mon: require non-nil account

### LINKED ISSUE #122153: util/mon: don't allow access to uninitialized BoundAccount
In 3d7b19c2172b16aff8233ed6220266878b6f9d97 we made it so that uninitialized `BoundAccount` acts as an unlimited one. This change could be problematic because it allows bugs (like the one fixed in 88ebd70d7ca24d8cebe1acdcb711d4f0e840c619) slip through. We should revert that change (or at least most if it) to harden the `BoundAccount` usage.

Jira issue: CRDB-37731

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR reverts the decision from 3d7b19c2172b16aff8233ed6220266878b6f9d97 to treat `nil` `BoundAccount` as unlimited. I think it was a mistake to change the API in such a way because it can allow for some bugs to go unnoticed (for example like the one fixed in 88ebd70d7ca24d8cebe1acdcb711d4f0e840c619).

See each commit for details.

Fixes: #122153.

Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 15 of 15 files at r3, 35 of 35 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120170)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/pgwire/server.go` line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwqVDTP8FzmzNgk2dbC:-NwqVDTP8FzmzNgk2dbD:b1c5g3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad17fce7e270c343bf5f49db83f4f02cb77c841f/pkg/sql/pgwire/server.go#L193)):*
> ```Go
> // baseSQLMemoryBudget is the amount of memory pre-allocated in each connection.
> var baseSQLMemoryBudget = envutil.EnvOrDefaultInt32("COCKROACH_BASE_SQL_MEMORY_BUDGET",
> 	int32(2.1*float64(mon.DefaultPoolAllocationSize)))
> ```

I don't think `EnvOrDefaultInt32` provides bounds checking for the default value, so what happens if `mon.DefaultPoolAllocationSize` is too large?
___
*[`pkg/util/mon/bytes_usage.go` line 725 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwqdtVQ81dJS2Zv1g73:-NwqdtVQ81dJS2Zv1g74:b-1dqajm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0c817e9552c8ec40a65e9bb0129f860d9e865e/pkg/util/mon/bytes_usage.go#L725)):*
> ```Go
> 	// any BytesMonitor. As such, it doesn't have any limit, and even though it
> 	// tracks all reservations, they are not counted against the root budget.
> 	standaloneUnlimited bool
> ```

Rather than having to make `reserved` an int32, do you think it might be easier to use a singleton `BytesMonitor` to indicate a standalone `BoundAccount`? If necessary, there's room for another bool field on `BytesMonitor` without having to increase the struct size.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120170)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/pgwire/server.go` line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwqVDTP8FzmzNgk2dbC:-Nwv7DgrAOprxmCfa99I:bbaxzb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad17fce7e270c343bf5f49db83f4f02cb77c841f/pkg/sql/pgwire/server.go#L193)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I don't think `EnvOrDefaultInt32` provides bounds checking for the default value, so what happens if `mon.DefaultPoolAllocationSize` is too large?
</blockquote></details>

Actually, we do get bounds checks since we use 32 bitSize argument for `strconv` which returns an error whenever the value is outside of int32 range https://go.dev/play/p/rmaL3UXZIKp.
___
*[`pkg/util/mon/bytes_usage.go` line 725 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwqdtVQ81dJS2Zv1g73:-Nwv7l-f0PRTr869lJXm:b-d4ztu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0c817e9552c8ec40a65e9bb0129f860d9e865e/pkg/util/mon/bytes_usage.go#L725)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Rather than having to make `reserved` an int32, do you think it might be easier to use a singleton `BytesMonitor` to indicate a standalone `BoundAccount`? If necessary, there's room for another bool field on `BytesMonitor` without having to increase the struct size.
</blockquote></details>

That's an interesting idea I haven't considered.

This would change the contract of the standalone account - it would need to be closed after the caller is done with it since eventually `math.MaxInt64` limit of the global singleton monitor might be consumed in the production (i.e. for tests it'd be probably ok to do nothing). Another downside is that there would also be contention on the mutex of the global singleton whenever these unlimited accounts are used - although, _probably_, there shouldn't be any performance-sensitive code that plumbed the memory monitoring infra and doesn't actually use it (I'm mostly thinking about usages in `pkg/storage` when `batcheval.EvalContext.GetResponseMemoryAccount` returns `nil`).

I'm kinda on the fence between these two options. Given these two considerations, would you still prefer the global singleton approach? I can prototype it if so.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120170)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/util/mon/bytes_usage.go` line 725 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwqdtVQ81dJS2Zv1g73:-NwvAMra1JughLUhCoGz:b-er8baj) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0c817e9552c8ec40a65e9bb0129f860d9e865e/pkg/util/mon/bytes_usage.go#L725)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

That's an interesting idea I haven't considered.

This would change the contract of the standalone account - it would need to be closed after the caller is done with it since eventually `math.MaxInt64` limit of the global singleton monitor might be consumed in the production (i.e. for tests it'd be probably ok to do nothing). Another downside is that there would also be contention on the mutex of the global singleton whenever these unlimited accounts are used - although, _probably_, there shouldn't be any performance-sensitive code that plumbed the memory monitoring infra and doesn't actually use it (I'm mostly thinking about usages in `pkg/storage` when `batcheval.EvalContext.GetResponseMemoryAccount` returns `nil`).

I'm kinda on the fence between these two options. Given these two considerations, would you still prefer the global singleton approach? I can prototype it if so.
</blockquote></details>

We could mark this global singleton monitor with a boolean to indicate that its reservations could overflow `math.MaxInt64` and loop around, or simply ignore all reservations. This would probably require modifying the code elsewhere in case the accounts bound to this singleton do get closed (i.e. we don't want to error out if we attempt to `Shrink` by more than currently tracked in the singleton, due to an overflow).

Still, requiring that standalone accounts are closed seems cleaner for this.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120170)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/util/mon/bytes_usage.go` line 725 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwqdtVQ81dJS2Zv1g73:-NwvLQHFEVEucxV7xvSA:b-gop1di) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0c817e9552c8ec40a65e9bb0129f860d9e865e/pkg/util/mon/bytes_usage.go#L725)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We could mark this global singleton monitor with a boolean to indicate that its reservations could overflow `math.MaxInt64` and loop around, or simply ignore all reservations. This would probably require modifying the code elsewhere in case the accounts bound to this singleton do get closed (i.e. we don't want to error out if we attempt to `Shrink` by more than currently tracked in the singleton, due to an overflow).

Still, requiring that standalone accounts are closed seems cleaner for this.
</blockquote></details>

The idea could be that we don't actually do anything with the global singleton - we just `b.mon == globalSingleton` in the same way we use `b.mon == nil` now. Then, there shouldn't be any concerns about mutex contention or hitting `MaxInt64`

**Review by DrewKimball — APPROVED** [review]
:lgtm: I'm still wary of changing `reserved` to an int32, but I'll defer to your judgement on which method to use.

> Reviewed 48 of 48 files at r5, 14 of 16 files at r7, 35 of 35 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-:-NwvOKB90Yh8JfBNHkKj:b-gzgn0m)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/pgwire/server.go` line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwqVDTP8FzmzNgk2dbC:-NwvN1Fm2HpgCEIJPKJJ:b-6mdcjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad17fce7e270c343bf5f49db83f4f02cb77c841f/pkg/sql/pgwire/server.go#L193)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Actually, we do get bounds checks since we use 32 bitSize argument for `strconv` which returns an error whenever the value is outside of int32 range https://go.dev/play/p/rmaL3UXZIKp.
</blockquote></details>

I'm confused - what's stopping the `int32(2.1*float64(mon.DefaultPoolAllocationSize))` argument from exceeding the MaxInt32? Can you point me to where it's being passed to `strconv`?
___
*[`pkg/util/mon/bytes_usage.go` line 913 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwvNYq-BpTMfcnCMcfb:-NwvNYq-BpTMfcnCMcfc:blmqffq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f7f33b616d823e1735e4dd0fce36faf11395d1/pkg/util/mon/bytes_usage.go#L913)):*
> ```Go
> 		b.reserved = b.mon.poolAllocationSize
> 	} else {
> 		b.reserved += int32(b.used)
> ```

Should there be any overflow checks here and elsewhere?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the review! I refactored the solution to use your global singleton idea - let's see what CI says. (I still might push for reducing the size of `reserved` field to int32 as part of reducing the sizes of monitor and account objects #120534, but it can wait.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-:-NwwILEmCbo5Eh37JA0W:b9xvek3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/util/mon/bytes_usage.go` line 725 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwqdtVQ81dJS2Zv1g73:-NwwHe_j9_IqwJxShKsB:b-8n0aqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0c817e9552c8ec40a65e9bb0129f860d9e865e/pkg/util/mon/bytes_usage.go#L725)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

The idea could be that we don't actually do anything with the global singleton - we just `b.mon == globalSingleton` in the same way we use `b.mon == nil` now. Then, there shouldn't be any concerns about mutex contention or hitting `MaxInt64`
</blockquote></details>

Oh, very nice, I like it, done.
___
*[`pkg/util/mon/bytes_usage.go` line 913 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwvNYq-BpTMfcnCMcfb:-NwwHhp2CTB3XTicpVL2:b-dwc0lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1f7f33b616d823e1735e4dd0fce36faf11395d1/pkg/util/mon/bytes_usage.go#L913)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Should there be any overflow checks here and elsewhere?
</blockquote></details>

Not that it matters now, but there were implicit overflow checks - if addition of `b.used` to `b.reserved` would put us above `math.MaxInt32`, then `toRelease` would be positive (because `b.mon.poolAllocationSize` is at most `math.MaxInt32`), so we'd go into the `if` case.
___
*[`pkg/sql/pgwire/server.go` line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-NwqVDTP8FzmzNgk2dbC:-NwwI-iGCl8JD-oP5mr8:bowviwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad17fce7e270c343bf5f49db83f4f02cb77c841f/pkg/sql/pgwire/server.go#L193)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I'm confused - what's stopping the `int32(2.1*float64(mon.DefaultPoolAllocationSize))` argument from exceeding the MaxInt32? Can you point me to where it's being passed to `strconv`?
</blockquote></details>

Indeed, that's a good point - it was possible that we set `mon.DefaultPoolAllocationSize` to something very close to `math.MaxInt32`, so multiplying that by 2.1 would lead to an overflow. However, such a large `DefaultPoolAllocationSize` would definitely lead to problems elsewhere (like internal queries hitting the root SQL budget), so the node wouldn't be able to start even if it caused an overflow.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for working this out!

> Reviewed 49 of 49 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120170#-:-NwwOGl7CQ0xnf-C3WPF:bah3o5j)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
Thanks for the review!

bors r+

**Pull request merged**
