### PR TITLE
sql: reuse already allocated memory for the cache in a row container

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, we would always allocate new memory for every row that
we put in the cache of DiskBackedIndexedRowContainer and simply
discard the memory underlying the row that we remove from the cache.
Now, we're reusing that memory.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/rowcontainer/row_container.go, line 759 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-LYS1V2h7nclfqayGUQr:-LYS1V2i7BExSThCdGxE:bvhvchc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d84524a5424e43e3211c17c266fed18d4288b2e/pkg/sql/rowcontainer/row_container.go#L759)):*
> ```Go
> 	for {
> 		if f.indexedRowsCache.Len() == 0 {
> 			return errors.Errorf("unexpectedly the cache of DiskBackedIndexedRowContainer contains zero rows")
> ```

Couldn't this happen in an out of memory scenario, or in the case of an improbably large row? The loop would keep calling RemoveFirst until there were no rows left in the cache.

I'm not really sure what to do about this other than to say that we should probably just propagate the error in that case. Can you work that out?

Also, this is complicated enough that it really deserves a unit test. Would you mind adding some?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/rowcontainer/row_container.go, line 759 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-LYS1V2h7nclfqayGUQr:-LYSVXm24rn0aqz46490:b-io40pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d84524a5424e43e3211c17c266fed18d4288b2e/pkg/sql/rowcontainer/row_container.go#L759)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Couldn't this happen in an out of memory scenario, or in the case of an improbably large row? The loop would keep calling RemoveFirst until there were no rows left in the cache.

I'm not really sure what to do about this other than to say that we should probably just propagate the error in that case. Can you work that out?

Also, this is complicated enough that it really deserves a unit test. Would you mind adding some?
</blockquote></details>

You're right, this could happen, so I added the error propagation. Now, that "unexpected zero rows" error, I believe, should never be reachable, so should I panic there instead?

I added a unit test, and it showed that I had a bug (the cache was not being updated properly when memory was reused - only the copy ended up being updated), so thanks for this suggestion. Also, I realized that there is no change required to `ring.Buffer` and removed those changes.

**Review by jordanlewis — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-:-LYT6slLDJJe_9SD6vw4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/rowcontainer/row_container.go, line 759 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-LYS1V2h7nclfqayGUQr:-LYT6qzcAgAGSBXbrc6X:bs4yylu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d84524a5424e43e3211c17c266fed18d4288b2e/pkg/sql/rowcontainer/row_container.go#L759)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

You're right, this could happen, so I added the error propagation. Now, that "unexpected zero rows" error, I believe, should never be reachable, so should I panic there instead?

I added a unit test, and it showed that I had a bug (the cache was not being updated properly when memory was reused - only the copy ended up being updated), so thanks for this suggestion. Also, I realized that there is no change required to `ring.Buffer` and removed those changes.
</blockquote></details>

Keeping the error is fine I think.
___
*[pkg/sql/rowcontainer/row_container.go, line 761 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-LYT1Em53NfNevmdsGse:-LYT1Em53NfNevmdsGsf:b-5ijwpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/399785d3dc92a3f7b0507c3592786bff7fe3f8d6/pkg/sql/rowcontainer/row_container.go#L761)):*
> ```Go
> 	for {
> 		if f.indexedRowsCache.Len() == 0 {
> 			if err != nil {
> ```

Do you need this?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34767)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/rowcontainer/row_container.go, line 759 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-LYS1V2h7nclfqayGUQr:-LYT83iCBF4EJ2EErcFW:b-54avio) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d84524a5424e43e3211c17c266fed18d4288b2e/pkg/sql/rowcontainer/row_container.go#L759)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Keeping the error is fine I think.
</blockquote></details>

Ok, thanks.
___
*[pkg/sql/rowcontainer/row_container.go, line 761 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-LYT1Em53NfNevmdsGse:-LYT7TsU6X4uy3FB1XDd:brgy35l) ([raw file](https://github.com/cockroachdb/cockroach/blob/399785d3dc92a3f7b0507c3592786bff7fe3f8d6/pkg/sql/rowcontainer/row_container.go#L761)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Do you need this?
</blockquote></details>

This is only used in the case I described in the second paragraph of the comment to the function. The point is to return original OOM error instead of not very useful that I generate below. Are you suggesting returning the generated one and not take in `err` as an argument? I agree, this approach seems a little weird to me.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34767)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/rowcontainer/row_container.go, line 761 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-LYT1Em53NfNevmdsGse:-LYTHWPm4IDJAftdqJnN:bvsvcc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/399785d3dc92a3f7b0507c3592786bff7fe3f8d6/pkg/sql/rowcontainer/row_container.go#L761)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This is only used in the case I described in the second paragraph of the comment to the function. The point is to return original OOM error instead of not very useful that I generate below. Are you suggesting returning the generated one and not take in `err` as an argument? I agree, this approach seems a little weird to me.
</blockquote></details>

Oh, I see, yeah I thought that you can just return the final OOM error that you get down below in this case.  I thought you already have a case for this, I'll comment where it is.
___
*[pkg/sql/rowcontainer/row_container.go, line 780 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-LYTHnxc4pQlfLr4RWwG:-LYTHnxc4pQlfLr4RWwH:b-s9lh8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/399785d3dc92a3f7b0507c3592786bff7fe3f8d6/pkg/sql/rowcontainer/row_container.go#L780)):*
> ```Go
> 					f.maxCacheSize--
> 					f.firstCachedRowPos++
> 					if f.indexedRowsCache.Len() == 0 {
> ```

Seems to me you can rely on this case without having to pass in the outer error above.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34767)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/rowcontainer/row_container.go, line 780 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-LYTHnxc4pQlfLr4RWwG:-LYTPfmSDbpg4n-0BmPX:b-qyh11s) ([raw file](https://github.com/cockroachdb/cockroach/blob/399785d3dc92a3f7b0507c3592786bff7fe3f8d6/pkg/sql/rowcontainer/row_container.go#L780)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Seems to me you can rely on this case without having to pass in the outer error above.
</blockquote></details>

This case will not be reached when the cache is empty, and we're trying to cache the first row of very big size. I added an extra check within `GetRow()` to propagate OOM error in this unlikely case.

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34767#-:-LYTYq425enApBrN0HZa:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
Thanks for the reviews!

bors r+

**Comment by yuzefovich** [comment]
By the way, I forgot to mention that I looked again into that growing-shrinking behavior of the memory account with `pprof` and didn't see measurable impact on performance (it was like 0.43% with memory accounting and 0% without), so it shouldn't be a concern.

**Pull request merged**
