### PR TITLE
sql: ensure that db opt is always passed to session

### PR DESCRIPTION
**Pull request by dt**
Repro test and fix for #4689

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4690)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire/v3.go, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTK4xoEY4TDX5cmpa5:-KBTK4xoEY4TDX5cmpa6:-1002435151) ([raw file](https://github.com/cockroachdb/cockroach/blob/846ec8f73653c8bc1f4b07ab5134dc1ac5888930/sql/pgwire/v3.go#L161)):*
I would move this down to just before the serving loop. The setting of `c.session.Database` in `executeStatements` looks wrong. Can it be removed?

---

*[sql/pgwire_test.go, line 198 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTKImHYUzsP3pGb637:-KBTKImHYUzsP3pGb638:1068954415) ([raw file](https://github.com/cockroachdb/cockroach/blob/846ec8f73653c8bc1f4b07ab5134dc1ac5888930/sql/pgwire_test.go#L198)):*
Delete?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-:-KBTKS3wlrMl0osMhKAh:676834233)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire/v3.go, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTK4xoEY4TDX5cmpa5:-KBTUpsGBE0EczaQXfpb:588242927) ([raw file](https://github.com/cockroachdb/cockroach/blob/846ec8f73653c8bc1f4b07ab5134dc1ac5888930/sql/pgwire/v3.go#L161)):*
Done.

Agreed on first setting in `executeStatements` -- the second is needed for statements that change the db though, right?

---

*[sql/pgwire_test.go, line 198 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTKImHYUzsP3pGb637:-KBTUNNbfOV2YQTYUlyA:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/846ec8f73653c8bc1f4b07ab5134dc1ac5888930/sql/pgwire_test.go#L198)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690)*

**Comment by tamird** [comment]
LGTM

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire/v3.go, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTK4xoEY4TDX5cmpa5:-KBTWyGZdFmE7CuiGnri:-1372038954) ([raw file](https://github.com/cockroachdb/cockroach/blob/846ec8f73653c8bc1f4b07ab5134dc1ac5888930/sql/pgwire/v3.go#L161)):*
The second one is setting c.opts.database, not c.session.database?

---

*[sql/pgwire_test.go, line 174 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTXEvAngy9Cju4aN28:-KBTXEvAngy9Cju4aN29:1695717681) ([raw file](https://github.com/cockroachdb/cockroach/blob/2597a276dd9ac2a7286880fe84494fbfdc3e4e99/sql/pgwire_test.go#L174)):*
how come this doesn't fail prior to `foo` existing? seems fine, but that definitely doesn't work in postgres and the deviation may be worth documenting

---

*[sql/pgwire_test.go, line 184 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTXRgyFh_L-ghZZyDb:-KBTXRgyFh_L-ghZZyDc:316930247) ([raw file](https://github.com/cockroachdb/cockroach/blob/2597a276dd9ac2a7286880fe84494fbfdc3e4e99/sql/pgwire_test.go#L184)):*
perhaps another case above this one that fails before `foo` is created.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-:-KBTXQtljP68XD8qvN5q:676834233)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire/v3.go, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTK4xoEY4TDX5cmpa5:-KBTYsnqL85I3jcGlJOz:-528399125) ([raw file](https://github.com/cockroachdb/cockroach/blob/846ec8f73653c8bc1f4b07ab5134dc1ac5888930/sql/pgwire/v3.go#L161)):*
Actually, this all seems confused. I think `c.opts.database` is unnecessary. In `parseOptions`, set `c.session.Database` and be done with it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire/v3.go, line 564 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTaCCyFRSY_PY7KwqH:-KBTaCCyFRSY_PY7KwqI:1809236529) ([raw file](https://github.com/cockroachdb/cockroach/blob/2597a276dd9ac2a7286880fe84494fbfdc3e4e99/sql/pgwire/v3.go#L564)):*
Do we still need this?

---

*[sql/pgwire_test.go, line 174 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTXEvAngy9Cju4aN28:-KBTYwja_nFYH8EtCWV2:-179847086) ([raw file](https://github.com/cockroachdb/cockroach/blob/2597a276dd9ac2a7286880fe84494fbfdc3e4e99/sql/pgwire_test.go#L174)):*
I agree this is weird. Let's add an issue for this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire_test.go, line 174 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTXEvAngy9Cju4aN28:-KBTa_dI0PxkeHXaJNpZ:720240799) ([raw file](https://github.com/cockroachdb/cockroach/blob/2597a276dd9ac2a7286880fe84494fbfdc3e4e99/sql/pgwire_test.go#L174)):*
It's weird, but it is actually convenient that the database doesn't need to exist. We should document, but I'm not sure if we should follow the postgres behavior.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire/v3.go, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTK4xoEY4TDX5cmpa5:-KBTbl92dL8d6YhbLg9S:846930346) ([raw file](https://github.com/cockroachdb/cockroach/blob/846ec8f73653c8bc1f4b07ab5134dc1ac5888930/sql/pgwire/v3.go#L161)):*
Oh, yeah, good point.
Done.

---

*[sql/pgwire/v3.go, line 564 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTaCCyFRSY_PY7KwqH:-KBTbqQuj3scUJSWXzmd:1719869467) ([raw file](https://github.com/cockroachdb/cockroach/blob/2597a276dd9ac2a7286880fe84494fbfdc3e4e99/sql/pgwire/v3.go#L564)):*
Done (killed `c.opts.database`)

---

*[sql/pgwire_test.go, line 174 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTXEvAngy9Cju4aN28:-KBTZY6jL2z-IE3yRxeq:-539715206) ([raw file](https://github.com/cockroachdb/cockroach/blob/2597a276dd9ac2a7286880fe84494fbfdc3e4e99/sql/pgwire_test.go#L174)):*
=peter.

---

*[sql/pgwire_test.go, line 184 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTXRgyFh_L-ghZZyDb:-KBTZrZjZMUSDuYTbp58:-1431746755) ([raw file](https://github.com/cockroachdb/cockroach/blob/2597a276dd9ac2a7286880fe84494fbfdc3e4e99/sql/pgwire_test.go#L184)):*
My goal wasn't to test table creation, just that an unqualified name on a new connection correctly qualified with the session db name.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/pgwire_test.go, line 184 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTXRgyFh_L-ghZZyDb:-KBTcSY6tGrLC-PEPd5M:-264821960) ([raw file](https://github.com/cockroachdb/cockroach/blob/2597a276dd9ac2a7286880fe84494fbfdc3e4e99/sql/pgwire_test.go#L184)):*
I think this is fine as is, but you might be able to make the test simpler and more focused by using the `system` database and doing a `SELECT` on one of the tables there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 184 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690#-KBTXRgyFh_L-ghZZyDb:-KBTkqoL8Rw1tEwf5-1i:857054258) ([raw file](https://github.com/cockroachdb/cockroach/blob/2597a276dd9ac2a7286880fe84494fbfdc3e4e99/sql/pgwire_test.go#L184)):*
+1 to peter's suggestion.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4690)*

**Pull request merged**
