### PR TITLE
sql: add new check relation to help build insert fast path uniqueness checks

### PR DESCRIPTION
**Pull request by msirek**
sql: add new check relation to help build insert fast path uniqueness checks

This creates a `FastPathUniqueChecks` list as a child of `InsertExpr`,
similar to `UniqueChecks`, but consisting of relational expressions
which can be used to build a fast path uniqueness check using a
 particular index. Each item in the `FastPathUniqueChecks` list is a
`FastPathUniqueChecksItem` whose `Check` expression, if the unique
constraint is provisionally eligible to use a fast path uniqueness
check, is a filtered scan from the target table of an
`INSERT INTO ... VALUES` statement. It is only built if the
VALUES clause has a single row. The filter equates each of the unique
constraint key columns with its corresponding value from the VALUES
clause. The values may either be a `ValuesExpr` or a `WithScanExpr`
whose source is a `ValuesExpr`. During exploration,
GenerateConstrainedScans will find all valid constrained index scans
which are equivalent to the original filtered Scan. The built relations
are not executed or displayed in the EXPLAIN, but will be analyzed in a
later commit to specify the index and index key values to use for insert
fast path uniqueness checks.

FastPathUniqueChecksItemPrivate is added with elements which are
designed to communicate details of how to build a fast path uniqueness
check to the execbuilder.

Epic: CRDB-26290
Informs: #58047

Release note: None

----
memo: optbuild unit tests for fast path unique check exprs

This commit adds the `ExprFmtHideFastPathChecks` flag, which hides fast
path check expressions from the output of expression formatting. It is
used in all places except TestBuilder. Also, unit tests for
`buildFiltersForFastPathCheck` are added.

Epic: CRDB-26290
Informs: #58047

Release note: None

----
xform: opt test for insert fast path checks

This commit adds an `insert` transformation rules test which
displays optimized fast path checks which are built in the optbuilder
and later explored and optimized. This test is modified in a later
commit to test for rule firing.

Epic: CRDB-26290
Informs: #58047

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-:-NfmLW88E7rTTNwMlcl2:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/norm/rules/prune_cols.opt` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-NfmIZOP-Rh1A861Fsgq:-NfmIZOP-Rh1A861Fsgr:b-ke5aae) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0bb911557bf5358e899089ed463c4f6fb90b832/pkg/sql/opt/norm/rules/prune_cols.opt#L519)):*
> ```
> # Removing ReturnCols will then allow the PruneMutationFetchCols to be more
> # conservative with the fetch columns.
> # TODO(ridwanmsharif): Mutations shouldn't need to return the primary key
> ```

optional nit: Could you turn this into an issue and refer to the issue number here? I don't think Ridwan has worked here in awhile...

**Comment by msirek** [comment]
@mgartner Do you think you might have any comments on this PR beyond those addressed in https://github.com/cockroachdb/cockroach/pull/102995? If not, I may merge this and open a new PR for subsequent commits.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-:-NfqjjeN7tQoKQZYeLpU:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

**Review by mgartner — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, 13 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111403)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/optbuilder/testdata/unique-checks-insert` line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-Nfr8Ojo0piojDXv9y0W:-Nfr8Ojo0piojDXv9y0X:b-pw7ou5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ee3a0e0309658f436e5ec6eaefeae07cfb4b5/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L71)):*
> ```
>  └── fast-path-unique-checks
>       ├── fast-path-unique-checks-item: &{0 0 [] [] {  record best-effort}}
>       │    └── values
> ```

nit: This output could be more clear what it represents. Do these represent empty fast-path-unique-checks that could not be constructed? Or are the values simply not being formatted fully? If you want to fix this up in a separate PR, that's fine.
___
*[`pkg/sql/opt/optbuilder/testdata/unique-checks-insert` line 427 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-Nfr8wcu7kLGasoHvwmz:-Nfr8wcu7kLGasoHvwn-:b3h2w09) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ee3a0e0309658f436e5ec6eaefeae07cfb4b5/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L427)):*
> ```
>  │                        └── k:27 != uniq.k:20
>  └── fast-path-unique-checks
>       └── fast-path-unique-checks-item: &{0 0 [] [] {  record best-effort}}
> ```

nit: It'd be helpful to include a representation of the unique constraint here, like we do for `unique-checks-item`, e.g., `uniq(x,y)`. Feel free to address in a future PR, if you'd like to do this.
___
*[`pkg/sql/opt/optbuilder/testdata/unique-checks-insert` line 2161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-NfrBM82AAeIU4BhuNLk:-NfrBM82AAeIU4BhuNLl:b6kjeuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ee3a0e0309658f436e5ec6eaefeae07cfb4b5/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L2161)):*
> ```
> # column use a projection to compute the computed column value. Since it
> # is not merged with the ValuesExpr in TestBuilder, UNIQUE WITHOUT INDEX
> # constraints involving the computed column are not built as fast path checks.
> ```

nit: I see all 4 fast path checks built below. Is this comment still accurate?
___
*[`pkg/sql/opt/optbuilder/testdata/unique-checks-insert` line 2460 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-NfrBeptAyH9IrLYUfOk:-NfrBeptAyH9IrLYUfOl:b-ak1u9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ee3a0e0309658f436e5ec6eaefeae07cfb4b5/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L2460)):*
> ```
> ----
> 
> # Test fast path check building from a WithScanExpr referencing values.
> ```

Is this comment still accurate? All the values have been inlined in unique-checks below, so there are no WithScanExprs AFAICT. I agree we should have a test for that though—I don't see any here.
___
*[`pkg/sql/opt/xform/testdata/rules/insert` line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-NfrCd7W60CWN0Vew1lc:-NfrCd7W60CWN0Vew1ld:b-vjyb12) ([raw file](https://github.com/cockroachdb/cockroach/blob/9129400255e9b060aa9aa78203471c8ab7d77c5f/pkg/sql/opt/xform/testdata/rules/insert#L73)):*
> ```
> # A computed leading index column allows fast path uniqueness checks.
> # Note, the best-cost fast path check relation selected may not be one
> # which would enable fast path uniqueness checks.
> ```

Is this referring to the first fast-path-check with a non-true index join filter?

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111403)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/norm/rules/prune_cols.opt` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-NfmIZOP-Rh1A861Fsgq:-NfswSLoCjhBTrNt6kZT:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0bb911557bf5358e899089ed463c4f6fb90b832/pkg/sql/opt/norm/rules/prune_cols.opt#L519)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

optional nit: Could you turn this into an issue and refer to the issue number here? I don't think Ridwan has worked here in awhile...
</blockquote></details>

Done
___
*[`pkg/sql/opt/optbuilder/testdata/unique-checks-insert` line 427 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-Nfr8wcu7kLGasoHvwmz:-NftFIcA7eiagZxDRiWf:b4qvl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ee3a0e0309658f436e5ec6eaefeae07cfb4b5/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L427)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: It'd be helpful to include a representation of the unique constraint here, like we do for `unique-checks-item`, e.g., `uniq(x,y)`. Feel free to address in a future PR, if you'd like to do this.
</blockquote></details>

Made the change
___
*[`pkg/sql/opt/optbuilder/testdata/unique-checks-insert` line 2161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-NfrBM82AAeIU4BhuNLk:-Nfsyixi528ZTN8sUAzm:b-hz2550) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ee3a0e0309658f436e5ec6eaefeae07cfb4b5/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L2161)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I see all 4 fast path checks built below. Is this comment still accurate?
</blockquote></details>

Fixed up the comment
___
*[`pkg/sql/opt/xform/testdata/rules/insert` line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-NfrCd7W60CWN0Vew1lc:-Nft7aJ-9iwZ4uhMHz31:b-l2s9ov) ([raw file](https://github.com/cockroachdb/cockroach/blob/9129400255e9b060aa9aa78203471c8ab7d77c5f/pkg/sql/opt/xform/testdata/rules/insert#L73)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is this referring to the first fast-path-check with a non-true index join filter?
</blockquote></details>

Yes, the best-cost relation in this case picked the t_r_c_idx index for `UNIQUE WITHOUT INDEX (a)`.  That's why matching has to walk the equivalent relations in the memo group and use one that doesn't have a Select.

**Comment by msirek** [comment]
> Is this comment still accurate? All the values have been inlined in unique-checks below, so there are no WithScanExprs AFAICT. I agree we should have a test for that though—I don't see any here.

Updated the comment to indicate this case has a foreign key. A WithScanExpr case is on line 1965. I've updated the comment for that test case.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111403)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/optbuilder/testdata/unique-checks-insert` line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-Nfr8Ojo0piojDXv9y0W:-NftHgtt4SDwXhZpbdpQ:betv1pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ee3a0e0309658f436e5ec6eaefeae07cfb4b5/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L71)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: This output could be more clear what it represents. Do these represent empty fast-path-unique-checks that could not be constructed? Or are the values simply not being formatted fully? If you want to fix this up in a separate PR, that's fine.
</blockquote></details>

Valid expressions here are only ever things like Select, Scan, IndexJoin.
Values is the dummy statement put in there when we can't build a fast-path expression.
We can't avoid printing `values` unless we hijack this general-purpose code:
https://github.com/cockroachdb/cockroach/blob/9129400255e9b060aa9aa78203471c8ab7d77c5f/pkg/sql/opt/memo/expr_format.go#L1127-L1129

One possibility is, instead of printing something like this:
```
       └── fast-path-unique-checks-item: t(b)
            └── values
```
Print this:
```
       └── fast-path-unique-checks-item: fast path disabled for constraint t(b)
            └── values
```
What do you think? I might not hold up this PR for this small change. I can add another commit later if we think a change is in order.

**Comment by msirek** [comment]
TFTRs!
bors r+

**Comment by mgartner** [comment]
*[`pkg/sql/opt/optbuilder/testdata/unique-checks-insert` line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111403#-Nfr8Ojo0piojDXv9y0W:-Ng-7s98BOM-GOrWjQuG:b-26j3u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ee3a0e0309658f436e5ec6eaefeae07cfb4b5/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L71)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Valid expressions here are only ever things like Select, Scan, IndexJoin.
Values is the dummy statement put in there when we can't build a fast-path expression.
We can't avoid printing `values` unless we hijack this general-purpose code:
https://github.com/cockroachdb/cockroach/blob/9129400255e9b060aa9aa78203471c8ab7d77c5f/pkg/sql/opt/memo/expr_format.go#L1127-L1129

One possibility is, instead of printing something like this:
```
       └── fast-path-unique-checks-item: t(b)
            └── values
```
Print this:
```
       └── fast-path-unique-checks-item: fast path disabled for constraint t(b)
            └── values
```
What do you think? I might not hold up this PR for this small change. I can add another commit later if we think a change is in order.
</blockquote></details>

Can we avoid creating a `FastPathUniqueChecksItem` in the `FastPathUniqueChecks` slice if its not possible? Then we don't need a dummy expression.

**Comment by msirek** [comment]
> Can we avoid creating a FastPathUniqueChecksItem in the FastPathUniqueChecks slice if its not possible? Then we don't need a dummy expression.

Per offline discussion, added a 2nd commit in #111822 to build no FastPathUniqueChecks if any of the required checks could not be built.

**Pull request merged**
