### PR TITLE
changefeedccl: expand scope of tenant-based tests

### PR DESCRIPTION
**Pull request by stevendanna**
This expands the scope of our tenant based testing by testing
enterprise changefeeds on tenants as well.

Currently, enterprise changefeeds are not supported on tenants via the
DisabledExternalIO flag. However, we may want to enable them in the
future and this will help keep us closer to that goal.

The main stumbling block to supporting tenant-based tests is the
pervasive use of TestServerInterface. Currently, we have a shim that
turns a TestTenantInterface into a TestServerInterface, panic'ing on
any method that isn't shared between them (or wasn't trivial to
implement).

To enable cloudsink tests, I've added a new server testing knobs that
allows for limited nodelocal usage.

Release note: None

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67382)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @stevendanna)

___
*[pkg/server/testing_knobs.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67382#-MeAkmwtD8OW1ANkp-qj:-MeAkmwtD8OW1ANkp-qk:bu20ax1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12591a68bac88ed5503c35a846d12de9c56c519/pkg/server/testing_knobs.go#L102)):*
> ```Go
> 	// cloudstorage for tenants so that it can be used during
> 	// testing.
> 	EnableNodelocalStorageForTenants bool
> ```

Would it make sense to just specify the blob storage factory override directly?
This way server won't need to construct anything.  Just use whatever is specified there?

Alternatively, can we use userfile:// instead of nodelocal?

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67382)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @miretskiy)

___
*[pkg/server/testing_knobs.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67382#-MeAkmwtD8OW1ANkp-qj:-MeAqlhL8Q8TEI3iG912:b13m88e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12591a68bac88ed5503c35a846d12de9c56c519/pkg/server/testing_knobs.go#L102)):*
> Would it make sense to just specify the blob storage factory override directly?

Done.  I still kept the knob scoped to tenants for now.

> Alternatively, can we use userfile:// instead of nodelocal?

I don't see a reason why not.  I'll take a look.  It might make sense as a separate PR.

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 12 files at r1, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67382)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @miretskiy)

**Comment by stevendanna** [comment]
bors r=miretskiy

**Comment by stevendanna** [comment]
bors retry

**Pull request merged**
