### PR TITLE
pkg/cloud: bump MaxIdleConnsPerHost to 64

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by dt** [comment]
This appears to get our new connection rate from ~2-3/s down to more like <.075/s, and our TLS handshake rate from 8.5/s to .3/s if I'm reading the metrics in #115517 correctly.

**Review by stevendanna — APPROVED** [review]
The first two commits have the side-effect of applying the custom CA configuration to a broader set of external storage connections. To me, this is an improvement, but could be worth a release note.

I wonder if we should pair this change with a change to the IdleConnectionTimeout to avoid a large number of open being held around for too long. But, let's cross that bridge if we ever encounter it.

**Comment by dt** [comment]
> worth a release note

🤷 It's always applied to _some_ s3 connections (explicit endpoint) and is in addition to the system cert pool so this shouldn't be a visible behavior change for anyone who has something working today, right?

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
