### PR TITLE
kv: RangeKeyMismatchError cleanup.

### LINKED ISSUE #72399: kv: complete RangeKeyMismatchError suggestion migration
https://github.com/cockroachdb/cockroach/commit/213de8d028b26f79c343f7eb5f997041ac6a2e66 introduced a migration that left the `RangeKeyMismatchError` type with a pair of deprecated fields, an unexported field, and a method to stitch this all together. We've been able to remove this since v21.1. Let's do so.

### PR DESCRIPTION
**Pull request by mneverov**
kv: RangeKeyMismatchError cleanup.

Fixes #72399

### CODE REVIEW

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72483)* status: :shipit: complete! 0 of 0 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-MnlBYEU-PR_XsdDEOEZ:-MnlBYEU-PR_XsdDEOE_:b-8ocvkx) (no related file):*
@nvanbenschoten ptal.

As I understand, the Ranges slice cannot be empty. It still feels weird to access the first element without checking the length.
Let me know if it's better to keep `Ranges()` method (needs to be renamed then) and have length check there. It would look smth like:
```
func (e *RangeKeyMismatchError) GetRanges(ctx context.Context) []RangeInfo {
	if len(e.Ranges) == 0 {
		log.Fatalf(ctx, "empty ranges")
	}
	return e.Ranges
}
```

---

**Review by nvb — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72483)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mneverov)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-MnlBYEU-PR_XsdDEOEZ:-MnzrO0N9OmZzRo1KHnf:b9pw844) (no related file):*
Thanks @mneverov!

>  It still feels weird to access the first element without checking the length.
> Let me know if it's better to keep Ranges() method (needs to be renamed then) and have length check there. It would look smth like:

I agree. We should add some kind of validation here that avoids panicking. After reading through the uses of this error, I'd suggest a slight variation of what you wrote above. In the cases where we need at least one element in the slice, we're always looking for the first element, as this first element has a special meaning. So how about something like:
```go
func (e *RangeKeyMismatchError) MismatchedRange() (RangeInfo, error) {
    if len(e.Ranges) == 0 {
        return RangeInfo{}, errors.AssertionFailedf("RangeKeyMismatchError %+v with empty RangeInfo slice", e)
    }
    return e.Ranges[0], nil
}
```

---
___
*[pkg/kv/txn_test.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-MnzphLd7Bgazp6PPdhl:-MnzphLd7Bgazp6PPdhm:b-ydu4j2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84b8e7147ca427394fe7e5f1156596b54790d90/pkg/kv/txn_test.go#L262)):*
> ```Go
> 		{&roachpb.TransactionRetryError{}, true},
> 		{&roachpb.WriteTooOldError{}, true},
> 		{&roachpb.RangeNotFoundError{}, false},
> ```

Were either of these changes necessary?
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go, line 1426 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-MnzppLqCy25g5FzWr7w:-MnzppLqCy25g5FzWr7x:b-b4jy6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c860c9d7c5caecc20415147d2377d354fa6513/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L1426)):*
> ```Go
> 		{err: &roachpb.RangeNotFoundError{}, asyncAbort: false},
> 		{err: &roachpb.RangeKeyMismatchError{
> 			Ranges: []roachpb.RangeInfo{{}}}, asyncAbort: false,
> ```

Was this change necessary?
___
*[pkg/roachpb/errors.proto, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-MnzqMCF-w4x196aKyLb:-MnzqMCF-w4x196aKyLc:bpwn821) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84b8e7147ca427394fe7e5f1156596b54790d90/pkg/roachpb/errors.proto#L95)):*
> ```protobuf
>   // deprecated_mismatched_range is an older version of mismatched_range. Can go
>   // away in 21.1, when we don't worry about 20.1 kvservers not populating rangesInternal.
>   optional roachpb.RangeDescriptor deprecated_mismatched_range = 3 [(gogoproto.nullable) = false];
> ```

Let's add `reserved 3, 4;` at the bottom of this proto to ensure that these field numbers are never re-used.
___
*[pkg/roachpb/errors.proto, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-MnzqaKj9gQFio5gevdF:-MnzqaKkBodenImZO8vd:b-8qyyg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c860c9d7c5caecc20415147d2377d354fa6513/pkg/roachpb/errors.proto#L96)):*
> ```protobuf
>   // client (always the first in the array) and then all other ranges
>   // overlapping the requested key range, or in between the addressed range and
>   // the requested key range.
> ```

Since we rely on the size of this slice, let's add:
```proto
//
// The slice should always have a length of at least 1. However, users should
// call MismatchedRange instead of relying on this in cases where they require
// at least one entry.
```

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72483)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mneverov and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go, line 1426 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-MnzppLqCy25g5FzWr7w:-Mo-wZmoAyD8ZrasQCJr:bbqu94g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c860c9d7c5caecc20415147d2377d354fa6513/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L1426)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Was this change necessary?
</blockquote></details>

changes are relevant to the current implementation, without this we get index out of bound error, the same in txn_test.go
___
*[pkg/roachpb/errors.proto, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-MnzqMCF-w4x196aKyLb:-Mo-zaTwEjWcpO9eP5um:b-qav5kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84b8e7147ca427394fe7e5f1156596b54790d90/pkg/roachpb/errors.proto#L95)):*
> //
> // The slice should always have a length of at least 1. However, users should
> // call MismatchedRange instead of relying on this in cases where they require
> // at least one entry.
:+1: 
___
*[pkg/roachpb/errors.proto, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-MnzqaKj9gQFio5gevdF:-Mo-zfj6Bm3VhMAi2qtU:bpuiwb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c860c9d7c5caecc20415147d2377d354fa6513/pkg/roachpb/errors.proto#L96)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Since we rely on the size of this slice, let's add:
```proto
//
// The slice should always have a length of at least 1. However, users should
// call MismatchedRange instead of relying on this in cases where they require
// at least one entry.
```
</blockquote></details>

Does it make sense then to keep `ranges` private and expose it via `MismatchedRange` only? I don't trust comments :)

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72483)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mneverov and @nvanbenschoten)

___
*[pkg/roachpb/errors.proto, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-MnzqaKj9gQFio5gevdF:-Mo0QGzf6_ImeuVmP2D1:b-ph01cn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c860c9d7c5caecc20415147d2377d354fa6513/pkg/roachpb/errors.proto#L96)):*
<details><summary><i>Previously, mneverov (Max Neverov) wrote…</i></summary><blockquote>

Does it make sense then to keep `ranges` private and expose it via `MismatchedRange` only? I don't trust comments :)
</blockquote></details>

There are cases where we want to access the entire slice and don't make any assumptions about its length, so I think it makes sense to keep the field exported. And I don't expect people will make assumptions about the length and index into the slice blindly without reading the comment.

**Review by nvb — APPROVED** [review]
:lgtm: this looks great. Thanks @mneverov. I'll merge once that last comment is addressed.

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-:-Mo9ZS5g4oeQVVoqDbm5:b5g2wh5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mneverov)

___
*[pkg/roachpb/errors.go, line 604 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-Mo9ZFPq7YOzvhIpR92G:-Mo9ZFPq7YOzvhIpR92H:bysnwb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/34974b40a276f3eeca5e96c9506b6c717ad81325/pkg/roachpb/errors.go#L604)):*
> ```Go
> 
> // MismatchedRange returns the range info for the range that the request was
> // erroneously routed to, or an error if the Range slice is empty.
> ```

`s/Range/Ranges/`

**Review by nvb — APPROVED** [review]
bors r+

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72483#-:-MolD2Lw1mDEUad8kOos:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mneverov)

**Pull request merged**
