### PR TITLE
rocksdb/table: Always check key ordering when inserting to an SST

### PR DESCRIPTION
**Pull request by itsbilal**
Updates c-deps/rocksdb to point to a patch in cockroach's RocksDB fork.
Commit message for that patch:

To prevent an out-of-order SSTable insertion from ever happening, this
change updates BlockBasedTableBuilder::Add to always assert on key
ordering being maintained at the insertion point, rather than only
running with debug builds. When an out-of-order key insertion is
detected, the status is set to Corrupted to prevent the BlockBasedTable
from being written.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Did you get a chance to run a single-node `kv0` roachtest with and without this change?

**Comment by itsbilal** [comment]
@petermattis Just did, no discernable difference on `kv0/enc=false/nodes=1`.

```
before:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0        5756401         9594.0      6.7      6.3     11.0     22.0     60.8  write

after:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0        5802264         9670.4      6.6      6.3     11.0     22.0     60.8
```

**Review by petermattis — APPROVED** [review]
LGTM

We're going to want to backport this to 19.1 and 2.1 which will be somewhat onerous as you'll have to make changes to the crl-release-5.13 branch.

**Comment by itsbilal** [comment]
Sounds good, will backport the same patch to that branch of rocksdb. Thanks!

bors r+

**Pull request merged**
