### PR TITLE
storage: Remove a TODO comment on nil response on error

### PR DESCRIPTION
**Pull request by kkaneda**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5573)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica.go, line 763 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5573#-KDi3n5QNBFoBtSCkFvt:-KDi3n5QNBFoBtSCkFvu:1118749512) ([raw file](https://github.com/cockroachdb/cockroach/blob/460e853a2fa9d10ea347ab9ce68d14e032c009c5/storage/replica.go#L763)):*
this LG

I'd remove the `return nil, pErr` below and change `return br, nil` to `return br, pErr`

---

*[storage/replica.go, line 1032 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5573#-KDi3gGzbvo8mHVFDcjJ:-KDi3gGzbvo8mHVFDcjK:-1710585508) ([raw file](https://github.com/cockroachdb/cockroach/blob/460e853a2fa9d10ea347ab9ce68d14e032c009c5/storage/replica.go#L1032)):*
-1 on this, frankly. non-nil errors in go mean "don't use the other returns"

---

*[storage/replica.go, line 1122 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5573#-KDi3ly625ss0zc55g1K:-KDi3ly625ss0zc55g1L:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/460e853a2fa9d10ea347ab9ce68d14e032c009c5/storage/replica.go#L1122)):*
ditto

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5573)*

**Comment by kkaneda** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica.go, line 763 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5573#-KDi3n5QNBFoBtSCkFvt:-KDi7-fzxaCXny0fe_vT:1419253149) ([raw file](https://github.com/cockroachdb/cockroach/blob/460e853a2fa9d10ea347ab9ce68d14e032c009c5/storage/replica.go#L763)):*
Sure, changed to `return br, pErr`. 

Hmm, also reverted `log.Errorc` as we will hit when `add{ReadOnly,Write}Cmd` returns a response and a non-nil error. 

Will update the PR title to just "Remove a TODO comment on nil response on error"

---

*[storage/replica.go, line 1032 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5573#-KDi3gGzbvo8mHVFDcjJ:-KDi6v2PyJ0Usj0BAVAR:918705015) ([raw file](https://github.com/cockroachdb/cockroach/blob/460e853a2fa9d10ea347ab9ce68d14e032c009c5/storage/replica.go#L1032)):*
I see. Sure, just reverted this change.

---

*[storage/replica.go, line 1122 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5573#-KDi3ly625ss0zc55g1K:-KDi6y7TGT2OeEB1T3tw:-486775898) ([raw file](https://github.com/cockroachdb/cockroach/blob/460e853a2fa9d10ea347ab9ce68d14e032c009c5/storage/replica.go#L1122)):*
reverted.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5573)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/replica.go, line 763 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5573#-KDi3n5QNBFoBtSCkFvt:-KDi88lP4N2yjIBzHWCi:1210023163) ([raw file](https://github.com/cockroachdb/cockroach/blob/460e853a2fa9d10ea347ab9ce68d14e032c009c5/storage/replica.go#L763)):*
Ah, makes sense.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5573#-:-KDi8E5s9DnRhLCTwJYY:1417088721)*

**Comment by kkaneda** [comment]
Thanks for the quick review!

**Pull request merged**
