### PR TITLE
bugfix: maybeGossipConfigs run match function with wrong key

### PR DESCRIPTION
**Pull request by Kevin-GuanJian**
If the range was splited between config ranges, the maybeGossipConfigs will run match with wrong prefix key, the match will return true wrongly.
(e.g. : \x00\zone as prefix key, \x00\zonf as end key, match run with \x00\acct.)
this should never happen

### CODE REVIEW

**Comment by tamird** [comment]
Hi @keynovo, thanks for the patch. Could you add a test that demonstrates the bug you're fixing?

**Comment by bdarnell** [comment]
Good catch. But it feels weird to ask `rng` whether it contains the key prefix in a callback from a method on `rng`. I think that `rng.maybeGossipConfigsLocked` should check `rng.ContainsKey(cd.keyPrefix)` before calling `match()`.

Both Store and Range are looping over the `configDescriptors`; the role of the callback to `rng.maybeGossipConfigs` is to ensure that the Range only processes the config subset that the Store is currently iterating over. So instead of `rng.ContainsKey(cd.keyPrefix)`, I think what we really want is `bytes.Equal(configPrefix, cd.keyPrefix)`.

And this definitely needs a test.

**Comment by Kevin-GuanJian** [comment]
updated as @bdarnell 's comments. 
btw, i have no idea how to construct a unit test for this function, do you have any tips? @bdarnell

**Comment by bdarnell** [comment]
For testing, I think we just need to force a split between two config prefixes (e.g. at `\x00\x00b`) and run maybeGossipConfigs. See the tests in client_split_test.go.

**Comment by Kevin-GuanJian** [comment]
updated as per comments.

**Comment by tamird** [comment]
This doesn't actually work - see https://github.com/cockroachdb/cockroach/blob/master/storage/range.go#L1043:L1050, which was added in the original splitting implementation (4f50c830).

**Comment by Kevin-GuanJian** [comment]
@tamird  yep, this should never happen, the range did not split mid-config actually, the point is both store and range are looping over the configDescriptors.
the scenario is that if the range was splited between config prefixes（e.g. between “\\00perm” and “\\00user”), the first range will loop the config prefix belong to second range(e.g "\00user"), and the callback use "\00acct" actually , and the firs range did not contain “\\00uses” certainly, this will cause the range think it was splited mid-config

**Comment by tamird** [comment]
@Kevin-GuanJian ah, got it. LGTM. Could you do this without exporting `MaybeGossipConfigs`? Probably means you'll have to put the test case in `storage` rather than `storage_test`

**Comment by Kevin-GuanJian** [comment]
@tamird store of test case in storage dose not suport transaction, i'm not sure if i could modify it.

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
