### PR TITLE
util/log: rip out mostly defunct context logging, but make Logc family use trace

### PR DESCRIPTION
**Pull request by tbg**
This was a simple change but it removes a lot of cruft and makes us log to the trace whenever the `Logc` family of functions is used.

Some brave soul could comb the codebase and replace all uses of the `Logf` via `Logc` when there is a context around as this would make sure that everything that makes it to log files also makes it to an associated request's trace. We could even remove the `Log(|f)` family completely to force the more awkward `log.Infoc(context.Background(), msg, args...)`.
#1779 goes a few steps further, but this seems like a good short-term goal.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7914)

### CODE REVIEW

**Comment by petermattis** [comment]
I see a handful of places in the code where we're calling `{Replica,Store}.context(` and then `log.{Level}c` and expecting the log message to containing the `{node,store,range} ID`. For example:

```
		log.Fatalc(r.context(context.TODO()), "processRaftCommand requires a non-zero index")
```

I think adding `r.String()` as a prefix here is the correct change. I used the following grep to find the uses of `{Store,Replica}.context(`:

```
cd storage; git grep '\.context(' | grep -v _test.go
```

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7914#-:-KN2TMdael52RjmRCwSA:-1053733716)*

**Comment by tschottdorf** [comment]
Good point, done (I ripped out `.context()` because well, it was kind of pointless at that stage, and won't be able to hold a trace).

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7914#-:-KN33-bC6nwiw7DcHp8L:-1305931471)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/node.go, line 258 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7914#-KN34ncB-qApm_ANCPFV:-KN34ncB-qApm_ANCPFW:-1740860691) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b84725678bfc81f62250e6aeba080fa4988d72/server/node.go#L258)):*
> ```Go
> // String implements fmt.Stringer.
> func (n *Node) String() string {
> 	return fmt.Sprintf("node %d", n.Descriptor.NodeID)
> ```

`s/node %d/node=%d/g` for symmetry with `{Store,Replica}.String()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7914#-:-KN355J19FChAk1IdOKm:1417088721)*

**Comment by tschottdorf** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/node.go, line 258 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7914#-KN34ncB-qApm_ANCPFV:-KN37lTRWwQTxbi7ETKw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b84725678bfc81f62250e6aeba080fa4988d72/server/node.go#L258)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/node %d/node=%d/g` for symmetry with `{Store,Replica}.String()`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7914)*

**Comment by tschottdorf** [comment]
TFTR.

Curiously, `go tool vet` (via `make check`) locally didn't complain about the completely justified "possible formatting directive" in https://circleci.com/gh/tschottdorf/cockroach/2574). Any idea why that could be?

**Comment by petermattis** [comment]
Nope, no idea why it wouldn't fail locally as well.

**Comment by RaduBerinde** [comment]
I don't really get what the plan is here. Having a context for what node we're on etc and having that show up in the log message is something we definitely need as we implement more multi-node tests. Is there a plan to replace the stuff that was there with something else?

**Comment by tschottdorf** [comment]
Yes, #1779.

**Pull request merged**
