### PR TITLE
ts: add support for multitenant timeseries metrics

### LINKED ISSUE #96438: tsdb: support tenant separated metrics
Users on db console should be able to view tenant-separated metrics. To make this possible, we need to change the way we store the metrics in tsdb to include tenant information. On the query side, tsdb should be able to fetch these tenant-separated metrics for a tenant. The desired behavior here is that the system tenant, by default, views metrics for all tenants, while an application tenant can only view metrics for itself.

Jira issue: CRDB-24125

Epic CRDB-18798

### PR DESCRIPTION
**Pull request by aadityasondhi**
This patch allows tsdb to support tenant-sperated timeseries metrics.
The changes can be summarized as:

(1) Changes in the write path:
In `pkg/status` we now store metrics corresponding to non-system tenants
with their tenant IDs.  This makes the `source` component of the ts
key includes both node IDs and tenant IDs:
```
.../[NodeID]-[TenantID]
```
Note: the system tenant does not include the tenant ID to allow for
backwards compatibility.

(2) Changes in the query path:
(2.1) as system tenant:
If the request to ts server comes annotated as system tenant, we
aggregate timeseries across all tenants in that metric name's keyspace.

(2.2) as secondary tenant:
When a secondary tenant queries the server, it is routed through tenant
connect and checked for having tenant capabilites for viewing tsdb data.
During this stage that request is annotated with the Tenant ID. When the
system tenant ts server recevies this query with a Tenant ID set:
- If no sources are requested as part of the query, it will aggregate
  across all sources that match the tenant ID.
- If specific sources are specified along with the tenant ID, it will
  scan the keyspace for the NodeID and then filter out results that do
not match with the TenantID.

These changes ensure that the system tenant is able to have a view of
metrics across all tenants and application tenants have access to their
own metrics. These changes are all done entirely server-side so no
client changes are needed. The client will be automatically served the
timeseries data it has access to based on its tenant capability.

Fixes: https://github.com/cockroachdb/cockroach/issues/96438.

Release note (ui change): Timeseries metrics in db concole will show
tenant-specific metrics. For the system tenant, these timeseries will be
aggregated across all tenants. For a secondary tenant, only metrics
belonging to that particular tenant will be shown.

### CODE REVIEW

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/ts/server_test.go` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQVlWIT25mEMObFVIiC:-NQVlWIT25mEMObFVIiD:bkanslw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/server_test.go#L480)):*
> ```Go
> 	}
> 
> 	tenant, _ := serverutils.StartTenant(t, s, base.TestTenantArgs{TenantID: roachpb.MustMakeTenantID(10)})
> ```

I believe this is causing the CI failures. Could use some guidance on how to structure this part of the test.

**Comment by knz** [comment]
@herkolategan could you assist Aditya here?

**Review by abarganier — COMMENTED** [review]
Nice work - I have some nits but overall I'm happy with how these changes are minimally invasive to the existing code :raised_hands: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-:-NQWSTJh9dNTsGj1vDBy:b801xm6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @andreimatei)

___
*[`pkg/ts/query.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQW6zVB4YaxkU6EnetI:-NQW6zVC5MnLUUZKODPd:b9ribls) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L446)):*
> ```Go
> 	timespan QueryTimespan,
> 	mem QueryMemoryContext,
> 	secondarySource string,
> ```

nit: can we explain what `secondarySource` is in the comments, or maybe better, rename the variable? It's not immediately obvious what this variable does. It seems like `secondarySource` will only ever be a tenant ID, though, so I think it'd make sense to make the name tenant-specific. 

I also kind of wonder if this secondary source should be a part of the `tspb.Query` :thinking:. We already have precedent for modifying the request object at the authorizer step by setting the tenant ID at the top level, so maybe we could instead do something similar for each query included in the request. I don't want this idea to turn into a bikeshed, so if that would throw a wrench into things then disregard.



_Code quote:_
```Go
secondarySource string,
```
___
*[`pkg/ts/query.go` line 863 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWRGnpDu3WcThwhvWb:-NQWRGnpDu3WcThwhvWc:b3ajm8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L863)):*
> ```Go
> 				b.Get(key)
> 			} else {
> 				// In the case where a secondary source is not specified, we should scan
> ```

nit: consider elaborating a bit more in this comment about *why* we do a `Scan` instead of a `Get`. 



_Code quote:_
```Go
				// In the case where a secondary source is not specified, we should scan
				// all keys that prefix match the primary source.
```

**Review by herkolategan — COMMENTED** [review]
@knz @aadityasondhi I took a stab at solving the failure on CI, but I lack knowledge in a few areas as to why the test is failing. Nonetheless I did get it to pass locally by changing some things:

I noted the failure on CI was due to authentication issues:

```
E230309 22:34:33.498933 2517 2@rpc/context.go:2335  [T1,n1,rnode=1,raddr=127.0.0.1:34803,class=default,rpc] 609  unable to connect (is the peer up and reachable?): initial connection heartbeat failed: grpc: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"Cockroach CA\")" [code 14/Unavailable]
```

To fix that I swapped out to the tenant's RPC for connecting:

```
tenantConn, err := tenant.(*server.TestTenant).RPCContext().GRPCDialNode(tenant.(*server.TestTenant).Cfg.AdvertiseAddr, tsrv.NodeID(),rpc.DefaultClass).Connect(context.Background())
```

Next I ran into:

```
server_test.go:514: rpc error: code = Unauthenticated desc = client tenant does not have capability to query timeseries data
```

Capabilities can be altered by connecting to the test server:
```
db.Exec("ALTER TENANT [10] GRANT CAPABILITY can_view_tsdb_metrics=true;\n")
```

Full very crude solution / guidance:
```
// StartServer code at start of test
s, db, _ := serverutils.StartServer(t, base.TestServerArgs{
		DisableDefaultTestTenant: true,
...

// Later down the line where tenant is started
tenant, _ := serverutils.StartTenant(t, s, base.TestTenantArgs{TenantID: roachpb.MustMakeTenantID(10)})

db.Exec("ALTER TENANT [10] GRANT CAPABILITY can_view_tsdb_metrics=true;\n")
if err != nil {
	t.Fatal(err)
}

time.Sleep(5 * time.Second) // I don't know how to flush capabilities, yet, so just wait?

tenantConn, err := tenant.(*server.TestTenant).RPCContext().GRPCDialNode(tenant.(*server.TestTenant).Cfg.AdvertiseAddr, tsrv.NodeID(), rpc.DefaultClass).Connect(context.Background())
if err != nil {
	t.Fatal(err)
}
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-:-NQWUdav3ls8duBnFkiX:b8g78vp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @andreimatei)

**Review by herkolategan — COMMENTED** [review]
Just a follow-up, the `time.Sleep` is obviously just a placeholder while I browsed around for something better. A search for the function `WaitForTenantCapabilities` yields a possible better way after altering the capability.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-:-NQWkBDd6I1kZhaBO4Y6:b9p6pl3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @andreimatei)

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @andreimatei)

___
*[`pkg/ts/server_test.go` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQVlWIT25mEMObFVIiC:-NQWkbe55_DDP5CUD3a-:b-mjnkig) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/server_test.go#L480)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

I believe this is causing the CI failures. Could use some guidance on how to structure this part of the test.
</blockquote></details>

Left a comment above with a possible solution.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @herkolategan)

___
*[`pkg/server/status/recorder.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWzIch-12TPVm1NSMA:-NQWzIch-12TPVm1NSMB:bdxbi1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/server/status/recorder.go#L332)):*
> ```Go
> 		registry:       mr.mu.nodeRegistry,
> 		format:         nodeTimeSeriesPrefix,
> 		source:         ts.MakeSource(mr.mu.desc.NodeID.String(), ""),
> ```

nit: `"" /* secondarySource */`
___
*[`pkg/ts/keys.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWzMq87Pm7VQul8mX8:-NQWzMq9C75_Snvq6X4W:byxnb5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/keys.go#L122)):*
> ```Go
> // If a secondary source is specified, the returned source will be in the format
> // `[primary]-[secondary]`.
> func MakeSource(primarySource string, secondarySource string) string {
> ```

I would call them `nodeID` and `tenantID`. I think their interpretation is pretty ingrained in the different layers, I doubt that it's useful to consider it generic.
___
*[`pkg/ts/query.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQW6zVB4YaxkU6EnetI:-NQWzqxa8wGweONAasHH:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L446)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can we explain what `secondarySource` is in the comments, or maybe better, rename the variable? It's not immediately obvious what this variable does. It seems like `secondarySource` will only ever be a tenant ID, though, so I think it'd make sense to make the name tenant-specific. 

I also kind of wonder if this secondary source should be a part of the `tspb.Query` :thinking:. We already have precedent for modifying the request object at the authorizer step by setting the tenant ID at the top level, so maybe we could instead do something similar for each query included in the request. I don't want this idea to turn into a bikeshed, so if that would throw a wrench into things then disregard.
</blockquote></details>

+1
___
*[`pkg/ts/query.go` line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQX1YY4EcQuqtpJsU7I:-NQX1YY4EcQuqtpJsU7J:bprxkb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L544)):*
> ```Go
> 	mem QueryMemoryContext,
> 	dest *[]tspb.TimeSeriesDatapoint,
> 	sourceSet map[string]struct{},
> ```

Please add a comment about `sourceSet` and specify that it's an output param.
And then move `secondarySource` before the output ones.
___
*[`pkg/ts/query.go` line 580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQX2FVI8Cfgmb4Y79QR:-NQX2FVI8Cfgmb4Y79QS:b-xrh5rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L580)):*
> ```Go
> 		for source := range sourceSpans {
> 			_, source2 := DecodeSource(source)
> 			if secondarySource != source2 {
> ```

I think we should push the filter as far down as possible - inside `readAllSourcesFromDatabase`.
___
*[`pkg/ts/query.go` line 857 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQX2kq9BEeDgUBISBhr:-NQX2kq9BEeDgUBISBhs:bea2ix9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L857)):*
> ```Go
> 	for currentTimestamp := startTimestamp; currentTimestamp <= timespan.EndNanos; currentTimestamp += kd {
> 		for _, source := range sources {
> 			// If a secondary source is specified, only query data for that tenant source.
> ```

see, even you can't stay away from talking about tenants :P
___
*[`pkg/ts/query.go` line 863 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQX33kY8HIsEIIccsvO:-NQX33kY8HIsEIIccsvP:b-w2h74c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L863)):*
> ```Go
> 				b.Get(key)
> 			} else {
> 				// In the case where a secondary source is not specified, we should scan
> ```

s/should//
___
*[`pkg/ts/query.go` line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQX4FLwCycTnU4RfStH:-NQX4FLwCycTnU4RfStI:bykjlqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L877)):*
> ```Go
> 	for _, result := range b.Results {
> 		for _, row := range result.Rows {
> 			if row.Value == nil {
> ```

This is here for the case where we do a `Get` that doesn't find the key, right? I'd lift this guard up, for clarity (and a bit of efficiency).
```
for _, result := range b.Results {
  if len(result.Rows) == 1 && result.Rows[0].Value == nil {
    // This came from a Get...
    continue
  }
  rows = append(rows, result.Rows...)
} 
```
___
*[`pkg/ts/server.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWyRhXEWD1wAuFZ9Yi:-NQWyRhYBCnZP8oHG7CM:b-5ukzrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/server.go#L105)):*
> ```Go
> 
> type TenantServer struct {
> 	tspb.UnimplementedTimeSeriesServer
> ```

please put a comment on this embedding. What part of the service is not implemented?
___
*[`pkg/ts/tspb/timeseries.proto` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWxh5I3_9cAE1LRdE6:-NQWxh5I3_9cAE1LRdE7:b-migne5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/tspb/timeseries.proto#L126)):*
> ```protobuf
>   optional int64 sample_nanos = 4 [(gogoproto.nullable) = false];
>   // tenantID of the tenant requesting the query.
>   optional roachpb.TenantID tenant_id = 5 [(gogoproto.nullable) = false, (gogoproto.customname) = "TenantID"];
> ```

I was imagining that we'd put the tenant ID in the `Query`, as `source_tenant_id` (and rename the existing `source` to `source_node` unless we need to access this RPC through grpcGateway and that makes renaming fields not be backwards compatible). This way the client more explicitly expresses its intent, and the system tenant would be able to query any other tenant it wants.

Did you consider that?

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, and @herkolategan)

___
*[`pkg/server/status/recorder.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWzIch-12TPVm1NSMA:-NQzRsHd0yQc1MaeKqJc:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/server/status/recorder.go#L332)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: `"" /* secondarySource */`
</blockquote></details>

Fixed
___
*[`pkg/ts/query.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQW6zVB4YaxkU6EnetI:-NQzRw9312deFluqlBdu:b-69oe69) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L446)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Ended up switching to tenant ID, as you both recommended
___
*[`pkg/ts/query.go` line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQX1YY4EcQuqtpJsU7I:-NQzS0UKBpMMyZZozWA0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L544)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Please add a comment about `sourceSet` and specify that it's an output param.
And then move `secondarySource` before the output ones.
</blockquote></details>

Done.
___
*[`pkg/ts/query.go` line 580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQX2FVI8Cfgmb4Y79QR:-NQzS2yQ2CgJz_xa84MR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L580)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think we should push the filter as far down as possible - inside `readAllSourcesFromDatabase`.
</blockquote></details>

Done.
___
*[`pkg/ts/query.go` line 857 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQX2kq9BEeDgUBISBhr:-NQzS44LDShMS4qqTJ5W:bz1i57n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L857)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

see, even you can't stay away from talking about tenants :P
</blockquote></details>

Done. Changed to tenants everywhere
___
*[`pkg/ts/query.go` line 863 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWRGnpDu3WcThwhvWb:-NQzS92y7-Eu2nnvlQA_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L863)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: consider elaborating a bit more in this comment about *why* we do a `Scan` instead of a `Get`. 
</blockquote></details>

Done.
___
*[`pkg/ts/query.go` line 863 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQX33kY8HIsEIIccsvO:-NQzS9nB1qFNXQ3aTiLp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L863)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/should//
</blockquote></details>

Done.
___
*[`pkg/ts/query.go` line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQX4FLwCycTnU4RfStH:-NQzSE2b3Liue7VyaUEB:b6ajr5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L877)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This is here for the case where we do a `Get` that doesn't find the key, right? I'd lift this guard up, for clarity (and a bit of efficiency).
```
for _, result := range b.Results {
  if len(result.Rows) == 1 && result.Rows[0].Value == nil {
    // This came from a Get...
    continue
  }
  rows = append(rows, result.Rows...)
} 
```
</blockquote></details>

Done. Thanks for the pointer, a lot cleaner this way!
___
*[`pkg/ts/server.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWyRhXEWD1wAuFZ9Yi:-NQzTTXaCnCa_c3faqax:b-4tehns) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/server.go#L105)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please put a comment on this embedding. What part of the service is not implemented?
</blockquote></details>

Done. It only implements Query currently.
___
*[`pkg/ts/tspb/timeseries.proto` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWxh5I3_9cAE1LRdE6:-NQzSLb-82_UkRkYl7El:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/tspb/timeseries.proto#L126)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I was imagining that we'd put the tenant ID in the `Query`, as `source_tenant_id` (and rename the existing `source` to `source_node` unless we need to access this RPC through grpcGateway and that makes renaming fields not be backwards compatible). This way the client more explicitly expresses its intent, and the system tenant would be able to query any other tenant it wants.

Did you consider that?

</blockquote></details>

Done.
___
*[`pkg/ts/server_test.go` line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQVlWIT25mEMObFVIiC:-NQzSMz44GvTMWngnDd-:b-81nenx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/server_test.go#L480)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Left a comment above with a possible solution.
</blockquote></details>

Thanks, this was extremely helpful!
___
*[`pkg/ts/keys.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWzMq87Pm7VQul8mX8:-NQzSOZV-Va881Ho2UFM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/keys.go#L122)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I would call them `nodeID` and `tenantID`. I think their interpretation is pretty ingrained in the different layers, I doubt that it's useful to consider it generic.
</blockquote></details>

Done.

**Review by abarganier — APPROVED** [review]
:lgtm: - moving the tenant ID into the query makes the whole thing feel much more cohesive :tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-:-NQzm49pDwMXqahQADoV:bs4epho)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @andreimatei, and @herkolategan)

___
*[`pkg/ts/query.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQW6zVB4YaxkU6EnetI:-NQzjWeB834mZwUKb4PQ:bct07vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/query.go#L446)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Ended up switching to tenant ID, as you both recommended
</blockquote></details>

Thanks, looks good to me.
___
*[`pkg/ts/server.go` line 124 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQzlLVT5yH2GCX7JFxu:-NQzlLVT5yH2GCX7JFxv:b-47exgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4b64ee1e383f1f63cd56ecc92544d31660e57e7/pkg/ts/server.go#L124)):*
> ```Go
> 	ctx = t.AnnotateCtx(ctx)
> 	for i := range req.Queries {
> 		req.Queries[i].TenantID = t.tenantID
> ```

nit: consider a short comment stating that we (at least for now) only allow tenants to query their own timeseries. It'll help document the history of our decision marking here.



_Code quote:_
```Go
	for i := range req.Queries {
		req.Queries[i].TenantID = t.tenantID
	}
```
___
*[`pkg/ts/tspb/timeseries.proto` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQWxh5I3_9cAE1LRdE6:-NQzc6aQ0PjtK9HhirVJ:b-edvqha) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9378d8e04e63df818ceb6b0c3e51d3412451e4/pkg/ts/tspb/timeseries.proto#L126)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks much nicer this way, thanks @aadityasondhi! 
___
*[`pkg/ts/tsutil/util.go` line 49 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQzlurgDXGXb2ow-58M:-NQzlurgDXGXb2ow-58N:b-9iwsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/01eab8e9ebf41034a7c9af40c2405ff888f78129/pkg/ts/tsutil/util.go#L49)):*
> ```Go
> 
> // DecodeSource splits a source into its individual components.
> func DecodeSource(source string) (primarySource string, secondarySource string) {
> ```

nit: if we're calling it tenantID elsewhere, maybe rename this something like `tenantIDSource`.



_Code quote:_
```Go
secondarySource string
```

**Review by aadityasondhi — COMMENTED** [review]
The latest revision adds additional comments to provide clarity w/ tenant sources and the ability of the secondary tenant to only query its own time series. It also rewords the commit message to reflect the changes made based on suggestions in the PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-:-NR-ft7A9a7koi2LXi67:bayugyx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @andreimatei, and @herkolategan)

___
*[`pkg/ts/tsutil/util.go` line 49 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98077#-NQzlurgDXGXb2ow-58M:-NR-fqHGBTdkCYVBv0Az:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01eab8e9ebf41034a7c9af40c2405ff888f78129/pkg/ts/tsutil/util.go#L49)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: if we're calling it tenantID elsewhere, maybe rename this something like `tenantIDSource`.
</blockquote></details>

Done.

**Comment by aadityasondhi** [comment]
going to wait for https://github.com/cockroachdb/cockroach/pull/99062 to land. CI seems to be continually failing those tests.

**Comment by aadityasondhi** [comment]
TFTR! 

bors r+

**Pull request merged**
