### PR TITLE
ui, server: add a timeout per node while collecting hot ranges

### PR DESCRIPTION
**Pull request by zachlite**
Requests for hot ranges are serviced by a cluster wide fan-out, where non-trivial work is done on each node to provide a response. For each store, and for each hot range, we start a transaction with KV to look up descriptor info.

Previously, there was no upper-bound set on the time a node could take to provide a response. This commit introduces a per-node timeout in the pagination logic, and is configurable with the new cluster setting server.hot_ranges.node.timeout. A value of 0 will disable the timeout.

Error behavior and semantics are preserved. If a particular node times out, The fan-out continues as before, as if a node failed to provide a response.

Informs https://github.com/cockroachdb/cockroach/issues/104269
Resolves https://github.com/cockroachdb/cockroach/issues/107627 
Epic: none
Release note (ops change): Added a new cluster setting named server.hot_ranges.node.timeout, with a default value of 5 minutes. The setting controls the maximum amount of time that a hot ranges request will spend waiting for a node to provide a response. Set to 0 to disable timeouts.

### CODE REVIEW

**Review by koorosh — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @zachlite)

___
*[`pkg/server/hot_ranges.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-Naf16Vc99WPxpvTmeOS:-Naf16Vc99WPxpvTmeOT:bz5mqoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f74c92a4bed0ff1d43e0922487c00b7d5249bb3/pkg/server/hot_ranges.go#L21)):*
> ```Go
> var HotRangesNodeTimeout = settings.RegisterDurationSetting(
> 	settings.TenantWritable,
> 	"server.hot_ranges.node.timeout",
> ```

I would specify that this setting is about hot ranges request to make it more specific (ie `server.request_hot_ranges.node.timeout`) to avoid any confusing that this setting can affect hot ranges values.
___
*[`pkg/server/pagination_test.go` line 422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-NafPx4k76qVg1Qn2iIH:-NafPx4k76qVg1Qn2iII:b2vfxf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f74c92a4bed0ff1d43e0922487c00b7d5249bb3/pkg/server/pagination_test.go#L422)):*
> ```Go
> 	defer log.Scope(t).Close(t)
> 	ctx := context.Background()
> 	server, _, _ := serverutils.StartServer(t, base.TestServerArgs{})
> ```

I'd expect to use test cluster within this test to have several nodes at least. My concern about how this test can dial another node?

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)

___
*[`pkg/server/hot_ranges.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-NagMSUa27KXpB2I2IZ7:-NagMSUa27KXpB2I2IZ8:b3rtdxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f74c92a4bed0ff1d43e0922487c00b7d5249bb3/pkg/server/hot_ranges.go#L23)):*
> ```Go
> 	"server.hot_ranges.node.timeout",
> 	"the duration allowed for a single node to return hot range data before the request is cancelled; if set to 0, there is no timeout",
> 	time.Minute*5,
> ```

Just out of curiosity, why was 5 minutes chosen as the default? It might be good to elaborate this in a comment above the setting var, so people in the future have some context.

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @koorosh)

___
*[`pkg/server/hot_ranges.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-Naf16Vc99WPxpvTmeOS:-NagcMBX1O0ZlwW9s7Xg:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f74c92a4bed0ff1d43e0922487c00b7d5249bb3/pkg/server/hot_ranges.go#L21)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I would specify that this setting is about hot ranges request to make it more specific (ie `server.request_hot_ranges.node.timeout`) to avoid any confusing that this setting can affect hot ranges values.
</blockquote></details>

:+1: 
___
*[`pkg/server/hot_ranges.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-NagMSUa27KXpB2I2IZ7:-NagcSgX-O5L2O5OfZTT:b-jg7r72) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f74c92a4bed0ff1d43e0922487c00b7d5249bb3/pkg/server/hot_ranges.go#L23)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Just out of curiosity, why was 5 minutes chosen as the default? It might be good to elaborate this in a comment above the setting var, so people in the future have some context.
</blockquote></details>

Good call, I'll context. It's my attempt to find a reasonable balance between "long enough" and "too long" for a reasonably large cluster.  
___
*[`pkg/server/pagination_test.go` line 422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-NafPx4k76qVg1Qn2iIH:-Nagcy7g61p6B1Li38hk:b-6uhn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f74c92a4bed0ff1d43e0922487c00b7d5249bb3/pkg/server/pagination_test.go#L422)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I'd expect to use test cluster within this test to have several nodes at least. My concern about how this test can dial another node?
</blockquote></details>

I don't think this test needs to cover any of the dialing logic. My goal is to just test the new codepath that runs `nodeFn` with a timeout.  The old code path and the dialing logic is covered by the existing test.

What do you think?

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @koorosh)

___
*[`pkg/server/hot_ranges.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-Naf16Vc99WPxpvTmeOS:-NagijZm6VraT-wh__LD:bxriyy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f74c92a4bed0ff1d43e0922487c00b7d5249bb3/pkg/server/hot_ranges.go#L21)):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Actually, going to change to `hot_ranges_request` so it's similar to the existing proto names.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier)

___
*[`pkg/server/pagination_test.go` line 422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-NafPx4k76qVg1Qn2iIH:-Nagl-rkEGDbWmACcTrJ:b-axg5kq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f74c92a4bed0ff1d43e0922487c00b7d5249bb3/pkg/server/pagination_test.go#L422)):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

I don't think this test needs to cover any of the dialing logic. My goal is to just test the new codepath that runs `nodeFn` with a timeout.  The old code path and the dialing logic is covered by the existing test.

What do you think?
</blockquote></details>

Got it, it shouldn't test the logic on other side of the call.

**Review by koorosh — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-:-NalVG9C9EglWDQPQubS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107796)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @koorosh, and @zachlite)

___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-Nal_QCHAr3Mk5Oc9ES3):*
1) 5 minutes feels excessive. As a user invoking the "hot ranges" pages I would be disappointed if I don't see anything within a few seconds.

Short of changing the architecture to make the display incremental (this would be gold standard UX), I feel the user would be best served by a configurable _global_ timeout for node fan-outs (and its default be 1 minute or perhaps even 10 seconds).
then during the fan-out, use `context.WithDeadline` to reduce the timeout available to each node depending on how much time was elapsed since the start of the hot ranges request.  (as in, measure `startTime` when the request is initially received for the client, then use the same`deadline :=  startTime + maxTimeout` for all fan-out requests)

2) I wonder if we would like a more general-purpose "node fan-out timeout" cluster setting, that would apply equally to the hot ranges but also the span stats and other situations where we collect data via fan-outs. In that case perhaps the name doesn't need to include the specific name of the service.

**Comment by j82w** [comment]
*[`pkg/server/hot_ranges.go` line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-NagvEbi5_iRZ8V-t9XZ:-NagvEbi5_iRZ8V-t9X_:b-1aiu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/06b39692ff474f48e62dbbd768c8c859c05c387b/pkg/server/hot_ranges.go#L30)):*
> ```Go
> 	time.Minute*5,
> 	settings.NonNegativeDuration,
> ).WithPublic()
> ```

What is the reason for making this public? Wondering if it's better to keep it hidden and only use it if an issue is reported.

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107796)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-Nal_QCHAr3Mk5Oc9ES3):*
Discussed offline:
>  configurable _global_ timeout for node fan-outs  
> I wonder if we would like a more general-purpose "node fan-out timeout"

I think this concept is more readily understandable than a per-node timeout, but my concern is that the appropriate value will be dramatically different between clusters with a small number of nodes and clusters with a large number of nodes.

>  5 minutes feels excessive.

I agree. My concern was that I didn't want us to come back to Hard Rock and say "we fixed it", only for them to still experience timeouts. I think the cost of lowering it outweighs the cost of keeping it high?

>  make the display incremental

1000% :that: .  
We have a tracking issue here: [https://github.com/cockroachdb/cockroach/issues/104584](https://github.com/cockroachdb/cockroach/issues/104584)  
I would love to spend all my time here, instead of these "quick fixes".  Being able to incrementally load-and-show instead of waiting for the entire fan-out would be a dramatic improvement, and would _actually_ enable us to achieve our "5 seconds or less" SLO.  I love how splunk does it with the green line that progresses across the top of the screen.
___
*[`pkg/server/hot_ranges.go` line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107796#-NagvEbi5_iRZ8V-t9XZ:-NamdkNH7KewYFSq9btD:bdrpuwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/06b39692ff474f48e62dbbd768c8c859c05c387b/pkg/server/hot_ranges.go#L30)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

What is the reason for making this public? Wondering if it's better to keep it hidden and only use it if an issue is reported. 
</blockquote></details>

I think that making it public increases the chances that we avoid an escalation.

**Pull request merged**
