### PR TITLE
ttl: Add additional multi-node test cases

### PR DESCRIPTION
**Pull request by ecwall**
refs https://github.com/cockroachdb/cockroach/issues/85800

Add test cases for 0 splits, 1 split, 2 splits.

Release justification: Add additional TTL tests

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86674)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/ttl/ttljob/ttljob_test.go` line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86674#-NABBGeK6SMIfVjdHW_C:-NABBGeK6SMIfVjdHW_D:b-d282pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d09f2c28a6841a3de76ac443b5ed65e8f463f7b2/pkg/sql/ttl/ttljob/ttljob_test.go#L390)):*
> ```Go
> 					ExpectedNumSpanPartitions: len(splitAts) + 1,
> 				},
> 				false, /* testMultiTenant */ // SPLIT AT does not work with multi-tenant
> ```

just checking, does the new `SplitTable` function we're using now also not work with multi-tenant?

if it doesn't, let's adjust the comment so it references that instead of SPLIT AT

if it does, we can set the flag to true (or remove the flag entirely)

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86674)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/ttl/ttljob/ttljob_test.go` line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86674#-NABBGeK6SMIfVjdHW_C:-NABD0m-70sR3lFCsRgq:b-v5ugf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d09f2c28a6841a3de76ac443b5ed65e8f463f7b2/pkg/sql/ttl/ttljob/ttljob_test.go#L390)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just checking, does the new `SplitTable` function we're using now also not work with multi-tenant?

if it doesn't, let's adjust the comment so it references that instead of SPLIT AT

if it does, we can set the flag to true (or remove the flag entirely)
</blockquote></details>

It doesn't work with `SHOW RANGES FROM TABLE` which I'm using to figure out what the leaseholder is so it doesn't get that far.

I'll update the comment for now.

**Review by rafiss — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86674)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by ecwall** [comment]
bors=rafiss

**Pull request merged**
