### PR TITLE
jobs: Use thread safe map to override resumer constructor

### LINKED ISSUE #102221: Race on TestingResumerCreationKnobs
pkg/ccl/importerccl/importerccl_test.TestImportMultiRegion [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9782473?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9782473?buildTab=artifacts#/) on master @ [847de4595b62a0c03b14a3d0865cc8222fcf0f61](https://github.com/cockroachdb/cockroach/commits/847de4595b62a0c03b14a3d0865cc8222fcf0f61):

```
      github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go:79 +0x1ef
  pkg/ccl/importerccl/importerccl_test.TestImportMultiRegion()
      pkg/ccl/importerccl/importerccl_test/pkg/ccl/importerccl/ccl_test.go:61 +0x19b
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47

Previous read at 0x00c000860998 by goroutine 13960:
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).createResumer()
      github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1565 +0xf7
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob()
      github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:364 +0x10a4
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeClaimedJobs.func3()
      github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:224 +0xca
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeClaimedJobs.func4()
      github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:227 +0x47

Goroutine 46 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.runTests()
      GOROOT/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1726 +0xa84
  pkg/ccl/importerccl/importerccl_test.TestMain()
      pkg/ccl/importerccl/importerccl_test/pkg/ccl/importerccl/main_test.go:31 +0x1c9
  main.main()
      main/bazel-out/k8-fastbuild/bin/pkg/ccl/importerccl/importerccl_test_/testmain.go:117 +0x748

Goroutine 13960 (finished) created at:
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeClaimedJobs()
      github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:222 +0x1b7
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).processClaimedJobs()
      github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:206 +0x430
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.func7()
      github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1100 +0x150
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).withSession()
      github.com/cockroachdb/cockroach/pkg/jobs/registry.go:995 +0x301
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.func13()
      github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1011 +0x52
  github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.func10()
      github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1203 +0x4ce
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6
==================
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestImportMultiRegion.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27350

### PR DESCRIPTION
**Pull request by miretskiy**
Replace map with sync.Map to ensure the access to
testing knob overrides is thread safe.

Fixes #102221
Release note: None

### CODE REVIEW

**Comment by dt** [comment]
is this better than yahor's slack suggestion of making the map a server creation-time knob?

**Comment by miretskiy** [comment]
> is this better than yahor's slack suggestion of making the map a server creation-time knob?

Possible; though it would make cdc changes non-trivial. We do weird shenanigans with those creation knobs; and worse still, these happen in different files... Can certainly be fixed.. but not easily (for changefeed at least) because we don't have changefeeds running during creation...

**Review by dt — APPROVED** [review]

**Comment by yuzefovich** [comment]
blather backport 23.1

**Comment by yuzefovich** [comment]
blathers backport 23.1

**Pull request merged**
