### PR TITLE
roachtest: increase workmem limits for tpchvec/disk

### LINKED ISSUE #61033: roachtest: tpchvec/disk failed
[(roachtest).tpchvec/disk failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707822&tab=buildLog) on [master@5cfd7e5553a3072a1490d392390dddf968844215](https://github.com/cockroachdb/cockroach/commits/5cfd7e5553a3072a1490d392390dddf968844215):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpchvec/disk/run_1
	test_runner.go:826: test timed out (10h0m0s)

	tpchvec.go:535,tpchvec.go:633,tpchvec.go:658,test_runner.go:767: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2707822-1614064242-78-n3cpu4:1 -- ./workload run tpch --concurrency=1 --db=tpch --default-vectorize --max-ops=1 --queries=1 {pgurl:1}: signal: killed
		(1) attached stack trace
		  -- stack trace:
		  | main.execCmdWithBuffer
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:566
		  | main.(*cluster).RunWithBuffer
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2353
		  | main.baseTestRun
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:530
		  | main.runTPCHVec
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:633
		  | main.registerTPCHVec.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:658
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:767
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (2) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2707822-1614064242-78-n3cpu4:1 -- ./workload run tpch --concurrency=1 --db=tpch --default-vectorize --max-ops=1 --queries=1 {pgurl:1}
		Wraps: (3) signal: killed
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/tpchvec/disk](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707822&tab=artifacts#/tpchvec/disk)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpchvec%2Fdisk.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
With the recent improvements to memory accounting during the external
sort, TPCH Q1 will take extremely long time with very low `workmem`
limit (which is the expected) because the hash aggregator spills to
disk and is using the fallback strategy of external sort + ordered
aggregator, with the sort processing all of the incoming data (on the
order of 800MiB) in partitions of roughly workmem/4 in size. Such
behavior is determined by the fact that we allocate some RAM for caches
of disk queues (limiting us to use at most 2 input partitions).

To go around this issue we increase the range for allowed values of
`workmem` setting.

Fixes: #61033.

Release justification: non-production code changes.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61044)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/tpchvec.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61044#-MUJS-E940039R_Pixev:-MUJS-E940039R_Pixew:b-e3vxzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbf3f65c2b0f86e735c5176e9446ea0e2264b46c/pkg/cmd/roachtest/tpchvec.go#L514)):*
> ```Go
> 	// of disk queues (limiting us to use at most 2 input partitions).
> 	rng, _ := randutil.NewPseudoRand()
> 	workmemInKiB := 650 + rng.Intn(1350)
> ```

Can we make this even larger without sacrificing disk spilling? Like 1KiB?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61044)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61044#-MUJS-E940039R_Pixev:-MUJsM-U2FOXNxtMqtkX:b5aslma) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbf3f65c2b0f86e735c5176e9446ea0e2264b46c/pkg/cmd/roachtest/tpchvec.go#L514)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we make this even larger without sacrificing disk spilling? Like 1KiB?
</blockquote></details>

I think you meant `1MiB`, right? I believe it is the most beneficial to have the lowest possible value for the lower bound of the range, and I think the current value is very close to that because a single node simulation is the worst case for 3 node cluster that `tpchvec` is running on. I understand that `650KiB` is not pretty, but it might give us more coverage than `1MiB`, so I'm inclined to keep it.

**Review by asubiotto — APPROVED** [review]
ok :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61044#-:-MUJtYqnEmw9F8uPH0nw:bjfu1zp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by otan** [comment]
good samaritan retry

bors r=asubiotto

**Pull request merged**
