### PR TITLE
ts: remove dead row format code

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit removes row format code of timeseries that was deprecated long time ago. Back in 2018 we introduced newer columnar format and initially kept both formats in place; however, since the timeseries data is constantly updated (pruned, rolled up, etc), we can no longer have any row format data in clusters that were created before the introduction of the columnar format. Thus, it is safe to remove the old format.

The main contribution of this commit is updating all the tests to use the columnar format. Some notable deletions:
- `TestMaintainTimeSeriesNoRollups` is now duplicate of `TestMaintainTimeSeriesWithRollups` so is removed.
- `TestMakeInternalData` is removed because it tests two `makeInternal` helpers against each other and one of the helpers is no longer needed.

Epic: None

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I had this lay around for a bit and wonder whether we want to get this in.

I remember that initially when I opened this PR there were some acceptance tests failures, and that's why I kept it in the draft mode. However, I reran the CI a few times and now it seems to be green. @knz also mentioned that it might be possible for ts data to still be in the row format, but to me that seems impossible - we should've stopped writing ts data in row format like in 2018.

**Comment by knz** [comment]
@yuzefovich what would happen if there's still row format data in the ts keyspan? would it be silently ignored, or is there a risk of instability?

**Review by yuzefovich — COMMENTED** [review]
I don't have context in my mind anymore about this (i.e. whether we could read any part of the ts keyspan depending on the ts query), but there is definitely risk of instability - like, for example, we could be now accessing `InternalTimeSeriesData.Offset[0]` (where `Offset` is `[]int32`) when that slice is `nil` which would lead to a panic. In fact, IIRC this is what I saw in acceptance test failure when I originally opened this PR as a draft a few months ago.

However, how could we still have row format data? `timeseries.storage.resolution_30m.ttl` set to infinity so that row format is never converted?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107896#-:-NgPYnO-EX8sCOuGptg5:b-egfwlu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

**Comment by yuzefovich** [comment]
BTW the failure [was](https://teamcity.cockroachdb.com/viewLog.html?buildId=11753529&buildTypeId=Cockroach_BazelEssentialCi) on `acceptance/version-upgrade` with a node crash (but the logs are now gone).

**Comment by yuzefovich** [comment]
I don't have context about this anymore, and even though we should delete the dead row format code, it's up to Observability team.

**Pull request closed without merging**
