### PR TITLE
ui: stop polling in stmt fingerprint details page, change default sort on stmts

### PR DESCRIPTION
**Pull request by xinhaoz**
See individual commits.

https://www.loom.com/share/17569db4a0c04a968dabbc4421d429bf

### CODE REVIEW

**Comment by xinhaoz** [comment]
Loom incoming.

**Review by maryliag — COMMENTED** [review]
can you also change the option to alphabetical order? with % of runtime as first

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99154#-:-NR4zMt8-SmQb_B7-UFe:b-7oe0qt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99154)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts` line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/99154#-NR57H3m2mF2O2bm4_AT:-NR57H3m2mF2O2bm4_AU:b-vwu2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fd68df7c24c2c089b02b94e102846368043a27d/pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts#L45)):*
> ```XML
>     label: getSortLabel(sortVal as SqlStatsSortType),
>   }))
>   .sort((a, b) => a.label.charCodeAt(0) - b.label.charCodeAt(0));
> ```

this won't guarantee sort if you have "Execution time" and "Execution count" for example, since you're looking only at the first char

you can create your own compare:
```
function compare(a, b) {
  if (a.label < b.label) {
    return -1;
  }
  if (a.label > b.label) {
    return 1;
  }
  return 0;
}
```

and then call with `.sort(compare);`

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99154#-:-NR5FpER5_BSdz_ZORaW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts` line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/99154#-NR57H3m2mF2O2bm4_AT:-NR5FljyBBkQvQkN_J1W:bqihh47) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fd68df7c24c2c089b02b94e102846368043a27d/pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts#L45)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this won't guarantee sort if you have "Execution time" and "Execution count" for example, since you're looking only at the first char

you can create your own compare:
```
function compare(a, b) {
  if (a.label < b.label) {
    return -1;
  }
  if (a.label > b.label) {
    return 1;
  }
  return 0;
}
```

and then call with `.sort(compare);`
</blockquote></details>

Ah yeah IDK why I only compared the first char :woman_facepalming: . Fixed!

**Pull request merged**
