### PR TITLE
kvstreamer: add more tracing

### PR DESCRIPTION
**Pull request by michae2**
Informs: #101823

Epic: None

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
This needs a little refinement, but the general idea is to add a trace event anywhere we could drop the continuation from `Enqueue` to `GetResults` (basically any early return before we place something in the results buffer).

**Review by yuzefovich — COMMENTED** [review]
Thanks for taking this on! I have some suggestions.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-:-NcZBPuu-dwnr2U21KMT:bab7qhj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ5y4CCPHzDKs9EDxG:-NcZ5y4CCPHzDKs9EDxH:bol3f7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/requests_provider.go#L151)):*
> ```Go
> func (r singleRangeBatch) String() string {
> 	return fmt.Sprintf(
> 		"{%s %v %v %v %v %v %v %v %v}", kvpb.RequestsString(r.reqs), r.reqsKeys, r.positions,
> ```

nit: perhaps add quick prefix for each value (perhaps abbreviated)? I.e something like `{"reqs=%s keys=%v pos=%v subidx=%v ...`.
___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ5YeH0ajfXE-PbpP1:-NcZ5YeIEvkuWPBrQWI6:b-d0imyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/requests_provider.go#L207)):*
> ```Go
> 	// lengthLocked returns the number of requests that have yet to be served at
> 	// the moment. The lock of the provider must be already held.
> 	lengthLocked() int
> ```

nit: perhaps remove `emptyLocked` in favor of using `lengthLocked() == 0`? (I'm not sure whether I like it myself, I'm neutral so up to you.)
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ6Pm06ZA-eMuPy-br:-NcZ6Pm06ZA-eMuPy-bs:b9wrtw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/streamer.go#L457)):*
> ```Go
> // TODO(yuzefovich): lift this restriction and introduce the pipelining.
> func (s *Streamer) Enqueue(ctx context.Context, reqs []kvpb.RequestUnion) (retErr error) {
> 	log.VEventf(ctx, 2, "Enqueue %d requests: %s", len(reqs), kvpb.RequestsString(reqs))
> ```

I think we want to hide such `log.VEventf` calls behind `if log.ExpensiveLogEnabled(ctx, 2) {`. To me it seems like it could have non-trivial overhead to populate the stringified representation unconditionally.

Also, I think it should be safe to evaluate `log.ExpensiveLogEnabled(ctx, 2)` only once on the very first call to `Enqueue` before we start the coordinator goroutine and store it as a boolean that doesn't have to be mutex protected (because we don't usually enable tracing for a query mid-flight, and if we do, we likely don't care about the partial trace of the streamer).

nit: also perhaps do `Enqueue %d original requests: %s` (in my mind there is a distinction between "original" (those added in `Enqueue`) and "resume" (those added in `buildResumeSingleRangeBatch`) requests.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ7TWo2fBnkmsDRqjY:-NcZ7TWo2fBnkmsDRqjZ:bjrkxjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/streamer.go#L734)):*
> ```Go
> 			return results, err
> 		}
> 		s.results.wait()
> ```

nit: I'd consider adding a log message here that we're about to block. Perhaps also another message either when we're done blocking, or, alternatively, a deferred message on the return outside of the loop above.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZAJ6oDRWDtGeDAPnw:-NcZAJ6oDRWDtGeDAPnx:ba8sc6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/streamer.go#L1282)):*
> ```Go
> 			// by the DistSender). For the initial implementation it doesn't
> 			// seem important though.
> 			log.VEventf(ctx, 2, "sending request %v", ba)
> ```

nit: this might be redundant - IIRC we'll log stuff about the BatchRequest and the response down in the KV level.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1532 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZAvAG3Ul-liOAEbDw:-NcZAvAG3Ul-liOAEbDx:b4u5stu) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/streamer.go#L1532)):*
> ```Go
> 	fp singleRangeBatchResponseFootprint,
> ) {
> 	log.VEventf(ctx, 2, "")
> ```

nit: I think we want to include details of `fp` in the message.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZB5vn4LsD0sPpwA1i:-NcZB5vo5SlS6k7oAYs3:b-sc9m30) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/streamer.go#L1569)):*
> ```Go
> 	s.results.Lock()
> 	defer s.results.Unlock()
> 	defer s.results.doneAddingLocked(ctx)
> ```

We should add logging into `doneAddingLocked` about how many results are ready and whether `hasResults` channel has been sent on.
___
*[`pkg/kv/kvpb/api.go` line 726 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ8I2N21h0rfc80VoT:-NcZ8I2N21h0rfc80VoU:b-meyvyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvpb/api.go#L726)):*
> ```Go
> 	}
> 	var b strings.Builder
> 	b.WriteRune('[')
> ```

I'm a bit concerned about the size of the string here. Tracing has currently limits that cannot be configured, so if we include many messages that each is hundreds of KiBs, we'll end up dropping a lot of stuff from the trace. How about we show some number of "head" and "tail" requests (with `... <number> requests elided ...` in between)? Perhaps we give 1KiB total to the string, so we could iterate over the head until we accumulate 500 characters, and if we're not past the middle of `reqs`, then we'd include the same number from the tail?

**Review by michae2 — COMMENTED** [review]
TFTR! I'll ask someone else to take a look at this while you're out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-:-NcpWSKPDmXTy_0FF-uO:bwvh31z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ5y4CCPHzDKs9EDxG:-NcpUoPJ0_aAYUSj6FHe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/requests_provider.go#L151)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps add quick prefix for each value (perhaps abbreviated)? I.e something like `{"reqs=%s keys=%v pos=%v subidx=%v ...`.
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvstreamer/requests_provider.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ5YeH0ajfXE-PbpP1:-NcpUqFH6pEVWQ-kAr_a:b-imfho7) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/requests_provider.go#L207)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps remove `emptyLocked` in favor of using `lengthLocked() == 0`? (I'm not sure whether I like it myself, I'm neutral so up to you.)
</blockquote></details>

`lengthLocked() == 0` seems slightly less readable, so I left `emptyLocked`.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ6Pm06ZA-eMuPy-br:-NcpVAyZ0Z3wi5GelqVu:b-awsdeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/streamer.go#L457)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we want to hide such `log.VEventf` calls behind `if log.ExpensiveLogEnabled(ctx, 2) {`. To me it seems like it could have non-trivial overhead to populate the stringified representation unconditionally.

Also, I think it should be safe to evaluate `log.ExpensiveLogEnabled(ctx, 2)` only once on the very first call to `Enqueue` before we start the coordinator goroutine and store it as a boolean that doesn't have to be mutex protected (because we don't usually enable tracing for a query mid-flight, and if we do, we likely don't care about the partial trace of the streamer).

nit: also perhaps do `Enqueue %d original requests: %s` (in my mind there is a distinction between "original" (those added in `Enqueue`) and "resume" (those added in `buildResumeSingleRangeBatch`) requests.
</blockquote></details>

Good call. It felt a little fiddly to cache the result of `log.ExpensiveLogEnabled(ctx, 2)` so I'm currently calling it every time.

Changed the log message.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ7TWo2fBnkmsDRqjY:-NcpV_aO5CLIulwuO170:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/streamer.go#L734)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'd consider adding a log message here that we're about to block. Perhaps also another message either when we're done blocking, or, alternatively, a deferred message on the return outside of the loop above.
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZAJ6oDRWDtGeDAPnw:-NcpVb0tDzXLb82HRBny:b-qv6sec) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/streamer.go#L1282)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this might be redundant - IIRC we'll log stuff about the BatchRequest and the response down in the KV level.
</blockquote></details>

Oh, good point. Removed these.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1532 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZAvAG3Ul-liOAEbDw:-NcpVePR6icRiRUELo13:b-frlxqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/streamer.go#L1532)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think we want to include details of `fp` in the message.
</blockquote></details>

Gah! Sorry. Done.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 1569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZB5vn4LsD0sPpwA1i:-NcpVip1-2u7Wep0rCKr:b-8vihvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvclient/kvstreamer/streamer.go#L1569)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We should add logging into `doneAddingLocked` about how many results are ready and whether `hasResults` channel has been sent on.
</blockquote></details>

Oh, good idea! Done.
___
*[`pkg/kv/kvpb/api.go` line 726 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ8I2N21h0rfc80VoT:-NcpVmDm2-AdGgumhEdj:b1kjghj) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvpb/api.go#L726)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm a bit concerned about the size of the string here. Tracing has currently limits that cannot be configured, so if we include many messages that each is hundreds of KiBs, we'll end up dropping a lot of stuff from the trace. How about we show some number of "head" and "tail" requests (with `... <number> requests elided ...` in between)? Perhaps we give 1KiB total to the string, so we could iterate over the head until we accumulate 500 characters, and if we're not past the middle of `reqs`, then we'd include the same number from the tail?
</blockquote></details>

Really good point. I added a TODO, will try to get to this tomorrow. And I think I need to do the same with the printing of `requestsToServe` at the bottom of `Streamer.Enqueue`.

**Review by michae2 — COMMENTED** [review]
@rharding6373 would you mind reviewing this PR while Yahor is out? I'm hoping to get it into release-22.2 before the SHA for 22.2.14 is picked tomorrow, but I know it's tight.

CI failure looks unrelated, I filed https://github.com/cockroachdb/cockroach/issues/109601 for that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-:-NcwsYSH3AISfamwHBa3:b-7cd7iy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/kv/kvpb/api.go` line 726 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ8I2N21h0rfc80VoT:-NcwtGo150vStNEnc5IZ:bb4mryz) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvpb/api.go#L726)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Really good point. I added a TODO, will try to get to this tomorrow. And I think I need to do the same with the printing of `requestsToServe` at the bottom of `Streamer.Enqueue`.
</blockquote></details>

I took a little simpler approach, just truncated the string to 1 Ki runes before adding it to the trace message. LMK what you think.

**Review by rharding6373 — APPROVED** [review]
:lgtm: modulo a couple nits and concerns about request string truncation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-:-Ncx8ONy11xdjkcymjYh:b25waym)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-Ncx4aHl-keqpXCJCogB:-Ncx4aHl-keqpXCJCogC:bbemol) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b77d265ee887ac1e28c335a4d629aacb105d37b/pkg/kv/kvclient/kvstreamer/results_buffer.go#L225)):*
> ```Go
> }
> 
> // signal non-blockingly sends on hasResults channel and returns whether sent..
> ```

nit: s/../.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 465 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-Ncx5Y-54zk3RSF2QMcr:-Ncx5Y-54zk3RSF2QMcs:b-mmi2fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b77d265ee887ac1e28c335a4d629aacb105d37b/pkg/kv/kvclient/kvstreamer/streamer.go#L465)):*
> ```Go
> 			reqStr = util.TruncateString(reqStr, 1022) + "…]"
> 		}
> 		log.VEventf(ctx, 2, "Enqueue %d original requests: %s", len(reqs), reqStr)
> ```

minor optional nit: s/Enqueue/enqueuing to match other logs
___
*[`pkg/kv/kvpb/api.go` line 726 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ8I2N21h0rfc80VoT:-Ncx78ku93yEM3mDQb83:beyr96x) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvpb/api.go#L726)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I took a little simpler approach, just truncated the string to 1 Ki runes before adding it to the trace message. LMK what you think.
</blockquote></details>

I don't follow the approach you ultimately took. There are 3 calls to `RequestsString` and only one is truncated. I think that the truncation still needs to be done here to apply to all cases (and would be more performant). I think only including the first requests that fit in 1Ki runes is fine.

Also, remove the TODO unless it's there for more sophisticated truncation.

**Review by michae2 — COMMENTED** [review]
Thank you for looking!! Will bors this in a little bit if it passes CI.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-:-NcyYM3252CbiQyvrcAe:b-397zsm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373 and @yuzefovich)

___
*[`pkg/kv/kvclient/kvstreamer/results_buffer.go` line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-Ncx4aHl-keqpXCJCogB:-NcyXvWrEvZEnqMet2mg:b4855pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b77d265ee887ac1e28c335a4d629aacb105d37b/pkg/kv/kvclient/kvstreamer/results_buffer.go#L225)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: s/../.
</blockquote></details>

Thanks! Done.
___
*[`pkg/kv/kvclient/kvstreamer/streamer.go` line 465 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-Ncx5Y-54zk3RSF2QMcr:-NcyXyYO3DaElya4HMMR:b-hrmbd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b77d265ee887ac1e28c335a4d629aacb105d37b/pkg/kv/kvclient/kvstreamer/streamer.go#L465)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

minor optional nit: s/Enqueue/enqueuing to match other logs
</blockquote></details>

The name of the function is capitalized so I kept it the same (there's also a few log messages with "GetResults").
___
*[`pkg/kv/kvpb/api.go` line 726 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109308#-NcZ8I2N21h0rfc80VoT:-NcyYB9VAo7SzCtWt5qe:b-6663sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f0fd39b024ad51421a9a1812c8c9d2f3b43b38/pkg/kv/kvpb/api.go#L726)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I don't follow the approach you ultimately took. There are 3 calls to `RequestsString` and only one is truncated. I think that the truncation still needs to be done here to apply to all cases (and would be more performant). I think only including the first requests that fit in 1Ki runes is fine.

Also, remove the TODO unless it's there for more sophisticated truncation.
</blockquote></details>

Good points, ok, I made a more honest attempt at truncation.

**Comment by michae2** [comment]
bors r=rharding6373

**Pull request merged**
