### PR TITLE
sql: ensure column constraints are validated after SET for UPSERT

### LINKED ISSUE #35040: sql: INSERT ON CONFLICT can insert NULLs into NOT NULL columns
**Describe the problem**

The following sequence crashes CockroachDB:
```sql
CREATE TABLE test(
  key STRING NOT NULL,
  pos INT NOT NULL,
  token STRING NOT NULL,
  PRIMARY KEY(key)
);

PREPARE X AS
INSERT INTO test(key, pos, token)
VALUES ($1, $2, $3)
ON CONFLICT (key)
DO UPDATE SET pos = CASE
  WHEN excluded.token = test.token THEN excluded.pos
  ELSE NULL
END
RETURNING NOTHING;

EXECUTE X('key', 123, 'hello');
EXECUTE X('key', 123, 'bye');
SELECT * FROM test;
```

Backtrace:
```
*
* ERROR: [n1,client=[::1]:60292,user=root] a SQL panic has occurred while executing "SELECT * FROM test": Non-nullable column "test:pos" with no value! Index scanned was "primary" with the index key columns (key) and the values ('key')
*
*
* ERROR: [n1,client=[::1]:60292,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT * FROM _; caused by Non-nullable column "test:pos" with no value! Index scanned was "primary" with the index key columns (key) and the values ('key')

goroutine 90 [running]:
runtime/debug.Stack(0x6d171e0, 0xc0052a4400, 0x3)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6d171e0, 0xc0052a4400, 0xc0005b5980, 0x64db4c0, 0xc00612f860, 0x1)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:213 +0xa6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc005dbc000, 0x6d171e0, 0xc0052a4400, 0x61f4de0, 0xc0068db560)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:645 +0x2df
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc005dbc000, 0x6d171e0, 0xc0052a4400)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
panic(0x61f4de0, 0xc0068db560)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).finalizeRow(0xc0069b7c98, 0x6d172a0, 0xc00612f530)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:1247 +0xa37
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc0069b7c98, 0x6d172a0, 0xc00612f530, 0xc00612f560, 0x1, 0x1, 0x0, 0x10001, 0x0, 0x0)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:997 +0x19a
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*rowFetcherWrapper).Next(0xc0078b15c0, 0x6d172a0, 0xc00612f530, 0xc006cf2c60, 0xc00612f4d0)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:144 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Next(0xc0069b7800, 0x0, 0x6d172a0, 0x6d172a0, 0xc00612f530)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:247 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x6d172a0, 0xc00612f3b0, 0x6d20660, 0xc0069b7800, 0x6cf43a0, 0xc005044380)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:172 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc0069b7800, 0x6d172a0, 0xc00612f3b0, 0x0)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:731 +0x96
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartSync(0xc0062ea8c0, 0x6d172a0, 0xc00612f3b0, 0x6785fb8, 0xc000253880, 0x6cf4060)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:607 +0x19a
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0007d1600, 0xc006bd0d20, 0xc005024e10, 0xc0075f29e8, 0xc005c31680, 0xc005dbc4b0, 0x0)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:253 +0x8cb
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc0007d1600, 0x6d172a0, 0xc005e2d1d0, 0xc005dbc4b0, 0xc006bd0d20, 0xc005024e10, 0x6d0a3a0, 0xc000775500, 0xc005c31680)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:758 +0x24c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc005dbc000, 0x6d172a0, 0xc005e2d1d0, 0xc005dbc418, 0x3, 0xab9c398, 0xc005025050, 0x1, 0x0, 0x0)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:982 +0x26b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc005dbc000, 0x6d172a0, 0xc005e2d1d0, 0x6d1a920, 0xc00690d300, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:824 +0xa6a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc005dbc000, 0x6d172a0, 0xc005e2d1d0, 0x6d1a920, 0xc00690d300, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xaa7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc005dbc000, 0x6d172a0, 0xc005e2d1d0, 0x6d1a920, 0xc00690d300, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x333
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc005dbc000, 0x6d171e0, 0xc0052a4400, 0xc00063f998, 0x5400, 0x15000, 0xc00063fa30, 0xc0004c90f0, 0x0, 0x0)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1118 +0x2140
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000830870, 0x6d171e0, 0xc0052a4400, 0xc005dbc000, 0x5400, 0x15000, 0xc00063fa30, 0xc0004c90f0, 0x0, 0x0)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000830870, 0x6d171e0, 0xc0052a4400, 0xc005dbc000, 0x5400, 0x15000, 0xc00063fa30, 0xc0004c90f0, 0xc0004c9100, 0xc0004c6da4)
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:313 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/private/tmp/cockroach-20190121-61877-1tcqxrf/cockroach-v2.1.4/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:312 +0x1018
```

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

Run the set of statements posted above.

**Expected behavior**

Second `EXECUTE X` should fail to insert NULL value into a NON-NULL column.

**Environment:**
 - CockroachDB version:  CCL v2.1.4 @ 2019/01/21 23:00:37 (go1.11.4)
 - Server OS: macOS
 - Client app `cocroach sql`

### PR DESCRIPTION
**Pull request by knz**
Fixes #35040.

Release note (bug fix): CockroachDB now properly applies column width
and nullability constraints on the result of conflict resolution in
UPSERT and INSERT ON CONFLICT.

### CODE REVIEW

**Comment by knz** [comment]
@andy-kimball I have made the change to both the HP and CBO code. Thanks for checking I didn't mess up.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35371)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @bobvawter, @BramGruneir, and @knz)

___
*[pkg/sql/tablewriter_upsert_opt.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-L_AAztZ3y7bw7HQ2bEv:-L_AAzt_61w3dGNtTOez:b35jcji) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdfb58745fea73819ca892e27ac0a2795335cb8/pkg/sql/tablewriter_upsert_opt.go#L105)):*
> ```Go
> 	tu.resultCount++
> 
> 	// Validate the row constraints.
> ```

Don't the insert columns already get checked in `GenerateInsertRow`? I don't think we need this check here as well, do we?
___
*[pkg/sql/tablewriter_upsert_opt.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-L_AB9O60jGstlyyvUQk:-L_AB9O60jGstlyyvUQl:b-ssq8jv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdfb58745fea73819ca892e27ac0a2795335cb8/pkg/sql/tablewriter_upsert_opt.go#L133)):*
> ```Go
> 	}
> 
> 	// If columns need to be updated, validate the result values.
> ```

I'd put this call into `updateConflictingRow`, and then pass `updateValues` to `validateColumns`.
___
*[pkg/sql/tablewriter_upsert_opt.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-L_AAWtYDX2bNDu0MjpL:-L_AAWtYDX2bNDu0MjpM:b6ig06m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdfb58745fea73819ca892e27ac0a2795335cb8/pkg/sql/tablewriter_upsert_opt.go#L151)):*
> ```Go
> 
> // validateColumns verifies the nullability and column type constraitnts.
> func (tu *optTableUpserter) validateColumns(
> ```

Can't this be factored to a common `validateColumns` function used by both CBO and HP? I'd get rid of `startIdx` and pass in `insertRow`/`updateValues` in `insertNonConflictingRow`/`updateConflictingRow`. Better to pass already-clipped slice than to pass slice + index.

**Review by BramGruneir — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35371)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @knz)

___
*[pkg/sql/insert.go, line 682 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-L_DeG651HWIKR6xBHdP:-L_DeG668dsPvnMeiTob:b-ey0sm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ec1f894e598c7752c37662523318b7353ce53be/pkg/sql/insert.go#L682)):*
> ```Go
> 		return nil, err
> 	}
> 	// // Check to see if NULL is being inserted into any non-nullable column.
> ```

Shouldn't these be removed instead of left commented out?
___
*[pkg/sql/update.go, line 922 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-L_DeU0n-y9C5NSex95w:-L_DeU0o0aHh0z5WfZvD:b-sicf1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ec1f894e598c7752c37662523318b7353ce53be/pkg/sql/update.go#L922)):*
> ```Go
> 	for i := range cols {
> 		col := &cols[i]
> 		if !col.Nullable {
> ```

Can't the 2nd if be merged into the first?

if !col.Nullable && row[i] == tree.DNull {

**Review by knz — COMMENTED** [review]
Refactored/simplified. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-:-L_OU5R228tS2okWkDKe:b-mm7geq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @bobvawter, and @BramGruneir)

___
*[pkg/sql/insert.go, line 682 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-L_DeG651HWIKR6xBHdP:-L_OU1qw6HRicB5Qc81x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ec1f894e598c7752c37662523318b7353ce53be/pkg/sql/insert.go#L682)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Shouldn't these be removed instead of left commented out?
</blockquote></details>

Done.
___
*[pkg/sql/tablewriter_upsert_opt.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-L_AAztZ3y7bw7HQ2bEv:-L_CNmro67dOZy8eDLYT:bzahyws) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdfb58745fea73819ca892e27ac0a2795335cb8/pkg/sql/tablewriter_upsert_opt.go#L105)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Don't the insert columns already get checked in `GenerateInsertRow`? I don't think we need this check here as well, do we?
</blockquote></details>

Good call. Removed.
___
*[pkg/sql/tablewriter_upsert_opt.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-L_AB9O60jGstlyyvUQk:-L_CRg7WDKriXZCdsGyp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdfb58745fea73819ca892e27ac0a2795335cb8/pkg/sql/tablewriter_upsert_opt.go#L133)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd put this call into `updateConflictingRow`, and then pass `updateValues` to `validateColumns`.
</blockquote></details>

Done.
___
*[pkg/sql/tablewriter_upsert_opt.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-L_AAWtYDX2bNDu0MjpL:-L_CRi605fWFDb-ZGgY9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdfb58745fea73819ca892e27ac0a2795335cb8/pkg/sql/tablewriter_upsert_opt.go#L151)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can't this be factored to a common `validateColumns` function used by both CBO and HP? I'd get rid of `startIdx` and pass in `insertRow`/`updateValues` in `insertNonConflictingRow`/`updateConflictingRow`. Better to pass already-clipped slice than to pass slice + index.
</blockquote></details>

Done.
___
*[pkg/sql/update.go, line 922 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-L_DeU0n-y9C5NSex95w:-L_OTkXcByVNOWxU10Eh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ec1f894e598c7752c37662523318b7353ce53be/pkg/sql/update.go#L922)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can't the 2nd if be merged into the first?

if !col.Nullable && row[i] == tree.DNull {
</blockquote></details>

Done.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35371#-:-L_OWFO28C6MhCRobkUO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @bobvawter)

**Comment by knz** [comment]
TFYR!

bors r+

**Pull request merged**
