### PR TITLE
roachtest: add an encryption roachtest to test basic stuff

### PR DESCRIPTION
**Pull request by ghost**
Add an encryption roachtest to test can start and restart a node with encryption
enabled, cli can generates encryption store key with expected size, and Admin UI
endpoint has encryption status reported.

Release note: None

### CODE REVIEW

**Comment by mberhault** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/cmd/roachtest/cluster.go, line 875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26396#-LEBmpVa31-Q4_aIpWGU:-LEBmpVa31-Q4_aIpWGV:blxz7xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c2365a7a5fcab051d3ad52737b626b5a5fc804/pkg/cmd/roachtest/cluster.go#L875)):*
> ```Go
> 		c.t.Fatal(err)
> 	}
> 	uiPort, err := strconv.Atoi(port)
> ```

Strange variable name. Pretty the value is still the port.

---

*[pkg/cmd/roachtest/cluster.go, line 880 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26396#-LEBn6JG89wAvM4k2fVO:-LEBn6JG89wAvM4k2fVP:b9dlvxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c2365a7a5fcab051d3ad52737b626b5a5fc804/pkg/cmd/roachtest/cluster.go#L880)):*
> ```Go
> 	}
> 	// Roachprod makes Admin UI's port to be node's port + 1.
> 	port = strconv.Itoa(uiPort + 1)
> ```

how about just `return fmt.Sprintf("%s:%d", host, port+1)`

---

*[pkg/cmd/roachtest/encryption.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26396#-LEBofm2-zIW94SuTPcB:-LEBofm2-zIW94SuTPcC:b-jbtc57) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c2365a7a5fcab051d3ad52737b626b5a5fc804/pkg/cmd/roachtest/encryption.go#L36)):*
> ```Go
> 		// Check that /_status/stores/local endpoint has encryption status.
> 		for _, addr := range c.InternalAdminUIAddr(ctx, c.Range(1, nodes)) {
> 			if err := c.RunE(ctx, c.Node(nodes), fmt.Sprintf("curl http://%s/_status/stores/local | grep encryptionStatus", addr)); err != nil {
> ```

`encryptionStatus` is always set, it'll just be `null` if encryption isn't enabled.

---

*[pkg/cmd/roachtest/encryption.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26396#-LEBnsxV9BsksHqep0pO:-LEBnsxWBf6q0UXpufkq:b-j441z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c2365a7a5fcab051d3ad52737b626b5a5fc804/pkg/cmd/roachtest/encryption.go#L66)):*
> ```Go
> 
> 			// Check the size of generated aes key has expected size.
> 			if err := c.RunE(ctx, c.Node(nodes), fmt.Sprintf(`size=$(wc -c <"aes-%d.key"); test $size -eq %d && exit 0 || exit 1`, size, 32+size/8)); err != nil {
> ```

you can use `stat -c %s <filename>` to return just the size of the file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26396)*

**Comment by windchan7** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/roachtest/cluster.go, line 875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26396#-LEBmpVa31-Q4_aIpWGU:-LECBygD2s00B69gT4aI:b-tuxy75) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c2365a7a5fcab051d3ad52737b626b5a5fc804/pkg/cmd/roachtest/cluster.go#L875)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

Strange variable name. Pretty the value is still the port.
</blockquote></details>

Changed to webPort. We need a variable to hold the parsed integer anyway.

---

*[pkg/cmd/roachtest/cluster.go, line 880 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26396#-LEBn6JG89wAvM4k2fVO:-LECByGzA7DAE_uwF8l5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c2365a7a5fcab051d3ad52737b626b5a5fc804/pkg/cmd/roachtest/cluster.go#L880)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

how about just `return fmt.Sprintf("%s:%d", host, port+1)`
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/encryption.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26396#-LEBofm2-zIW94SuTPcB:-LECBxF3AAypZrkytSVf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c2365a7a5fcab051d3ad52737b626b5a5fc804/pkg/cmd/roachtest/encryption.go#L36)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

`encryptionStatus` is always set, it'll just be `null` if encryption isn't enabled.
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/encryption.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26396#-LEBnsxV9BsksHqep0pO:-LECBe7Y6x83O7Ycb-iO:b-3mgcfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c2365a7a5fcab051d3ad52737b626b5a5fc804/pkg/cmd/roachtest/encryption.go#L66)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

you can use `stat -c %s <filename>` to return just the size of the file.
</blockquote></details>

This is only valid on GNU stat, on mac, stat has no `-c` flag. We need to hold the size in a variable anyway.
I will just stick with the original command unless there's a particular reason not to do so.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26396)*

**Comment by mberhault** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/roachtest/encryption.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26396#-LEBnsxV9BsksHqep0pO:-LEEoPPR-T_FKzi3uJY9:b-nghci) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c2365a7a5fcab051d3ad52737b626b5a5fc804/pkg/cmd/roachtest/encryption.go#L66)):*
<details><summary><i>Previously, windchan7 (Victor Chen) wrote…</i></summary><blockquote>

This is only valid on GNU stat, on mac, stat has no `-c` flag. We need to hold the size in a variable anyway.
I will just stick with the original command unless there's a particular reason not to do so.
</blockquote></details>

ugh. of course it doesn't. Fine, let's stick with the wc.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26396#-:-LEEoTPjBc1ZGbDHoJw5:bnfp4nl)*

**Comment by windchan7** [comment]
Thanks, Marc!

bors r+

**Pull request merged**
