### PR TITLE
workload/tpcc: rework partitioning logic

### LINKED ISSUE #31584: roachtest: tpccbench line search doesn't repartition based on active warehouses
The TPCC database is partitioned based on the number of warehouses, but then the test performs a line search in which it varies the active warehouses.

This means that you need to repartition every time to cleanly split in the middle of the active warehouse range. This isn't happening today, resulting in an uneven load across the partitions.

For example, a 6 node 5k warehouses cluster seems to line search its way all the way to ~1500 active warehouses since it's really just hitting the first partition (thus simulating a 3 node cluster) right now.

As a result, all the partitioned tpcc results in this test that don't match the data set's warehouse count are likely bogus (too low).

### PR DESCRIPTION
**Pull request by nvb**
Fixes #31584.

This change reworks the tpcc partitioning logic. It centralizes
it into a new partitioner object, which is responsible for partitioning
a set of elements given a total count, and active count, and a partition
count.

In doing so, it simplifies the logic and makes its interactions with
partition affinity more clear.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I'm going to run a few partitioned `tpccbench` runs over the weekend. Please hold off on the reviews until they've completed.

**Comment by andreimatei** [comment]
How's this PR looking, N-man?

**Comment by tschottdorf** [comment]
I had offered to @nvanbenschoten to run this workload since I was investigating #31409, but it's not like I was able to get this workload running at all, even when the cluster didn't break. Not exactly sure why though, I would say you give it a spin if you get that far.

**Comment by nvanbenschoten** [comment]
I just had a few good runs with this so I think it's ready for a review. The only change I needed to make was to revert the connection-per-worker change. That ended up creating a huge number of connections and hitting file descriptor limits, which I think is what @tschottdorf saw.

**Review by tbg — COMMENTED** [review]
My review got interrupted, but here's what I got so far.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31651#-:-LPlKsoYB0Nn_qumwbPx:b91rqo)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/tpcc/partition.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31651#-LPlD0fhDaDFYFjCuIU7:-LPlD0fhDaDFYFjCuIU8:be5t1uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3421369e706a8c008a1c04bb9d4b0bea7a4cab4/pkg/workload/tpcc/partition.go#L70)):*
> ```Go
> 	bounds := make([]int, parts+1)
> 	for i := range bounds {
> 		bounds[i] = (i * total) / parts
> ```

Wait a minute, why isn't this `active`?
___
*[pkg/workload/tpcc/partition.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31651#-LPlCSxs9a6yLDL11n18:-LPlCSxs9a6yLDL11n19:b-4sg2cw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3421369e706a8c008a1c04bb9d4b0bea7a4cab4/pkg/workload/tpcc/partition.go#L80)):*
> ```Go
> 	//
> 	sizes := make([]int, parts)
> 	for i := range sizes {
> ```

This math is probably fine, but it makes me nervous that you're not deriving this from `bounds`. Oh, I just noticed you have a good unit test for this. That makes this a non-concern for me though I would personally still change it.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31651)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/tpcc/partition.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31651#-LPlCSxs9a6yLDL11n18:-LPlOCAfCUYi8Ltydb2O:b-vq5a86) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3421369e706a8c008a1c04bb9d4b0bea7a4cab4/pkg/workload/tpcc/partition.go#L80)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This math is probably fine, but it makes me nervous that you're not deriving this from `bounds`. Oh, I just noticed you have a good unit test for this. That makes this a non-concern for me though I would personally still change it.
</blockquote></details>

I think there's a bit of confusion here. The `bounds` of the partitions are a function of the number of partitions and the total element count.  It's explicitly not a function of the active count. The partition boundaries need to stay the same, regardless of how many elements are active so that we don't need to repartition whenever we change the active count.

The active `sizes` are a function of the number of partitions and the active count and can't be derived from the `bounds`. The only relation between the two is that `active <= total` and that the partition count is the same. These two are combined to create the active partition elements (`partElems`).

**Review by tbg — APPROVED** [review]
:lgtm: though I can't say that I've really scrutinized the way the partitioner is used. The new code looks so much better.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31651#-:-LPlxAKj1xYynNHD-oOh:bm5zc5o)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/tpcc/partition.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31651#-LPlCSxs9a6yLDL11n18:-LPlugGS-8hHMiJY4lMB:bs4jug6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3421369e706a8c008a1c04bb9d4b0bea7a4cab4/pkg/workload/tpcc/partition.go#L80)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think there's a bit of confusion here. The `bounds` of the partitions are a function of the number of partitions and the total element count.  It's explicitly not a function of the active count. The partition boundaries need to stay the same, regardless of how many elements are active so that we don't need to repartition whenever we change the active count.

The active `sizes` are a function of the number of partitions and the active count and can't be derived from the `bounds`. The only relation between the two is that `active <= total` and that the partition count is the same. These two are combined to create the active partition elements (`partElems`).
</blockquote></details>

:thumbsup: it makes more sense now that I've looked at the rest. The example comments are already really helpful, but consider adding a little bit of prose. For example, I'm assuming that `total` corresponds to the number of warehouses, so throughout this example, `Warehouses = 20`. With `parts = 3`, this seems like we're setting up three partitions `[0..6]`, `[6..13]`, `[13..20]` (what about the end key though, wouldn't that be exclusive? Or is `total = 19` when there are 20 warehouses?)

What does `sizes` mean then? I think it means how many warehouses per partition are going to be "active" in the corresponding TPCC run. `partElemens` then specifies the warehouse IDs that are going to be active specifically. The abstraction is good, but for the examples, I find it a little hard to map it back to TPCC when there's no guidance.

**Review by nvb — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31651#-:-LQ0rkpi0QX1mgnkITp7:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/tpcc/partition.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31651#-LPlD0fhDaDFYFjCuIU7:-LQ0pLtg3LkrSWpSMEPQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3421369e706a8c008a1c04bb9d4b0bea7a4cab4/pkg/workload/tpcc/partition.go#L70)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Wait a minute, why isn't this `active`?
</blockquote></details>

Done.
___
*[pkg/workload/tpcc/partition.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31651#-LPlCSxs9a6yLDL11n18:-LQ0pf8U4IRxrOgFqQR6:b-3yuiha) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3421369e706a8c008a1c04bb9d4b0bea7a4cab4/pkg/workload/tpcc/partition.go#L80)):*
> consider adding a little bit of prose

Done. Hopefully that makes all of this clearer.

>  With parts = 3, this seems like we're setting up three partitions [0..6], [6..13], [13..20] (what about the end key though, wouldn't that be exclusive? Or is total = 19 when there are 20 warehouses?)

Yes, with three partitions and a total count of 20 warehouses, we get the partitions `[0..6), [6..13), [13..20)`. I added a test for this case.

> What does sizes mean then? I think it means how many warehouses per partition are going to be "active" in the corresponding TPCC run. partElemens then specifies the warehouse IDs that are going to be active specifically.

Yes, exactly.

**Pull request merged**
