### PR TITLE
builtins: implement to_char for timestamps and intervals

### LINKED ISSUE #91156: sql,builtins: support to_char formatting builtins for timestamp and interval
We should support the following builtins for compatibility with Postgres. They allow timestamps and intervals to be formatted with a custom format.
```
 to_char(timestamp, text)
 to_char(interval, text)
```
https://www.postgresql.org/docs/current/functions-formatting.html

Spun off https://github.com/cockroachdb/cockroach/issues/3781

The goal is to support our DMS integration. So we could limit our first implementation to have only the features that DMS needs. Talk to @otan about this.

Jira issue: CRDB-21127

Epic CRDB-17785

### PR DESCRIPTION
**Pull request by otan**
Resolves #91156

These commits implement to_char for timestamp and interval types. Most
of the code is copied from the PG implementation.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
this is really great! my comments are nits mostly

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-:-NGIC_Ss8UH-T-12Z7Wg:bmra2f6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[`-- commits` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGICSTYBR5IgJmMR7_A):*
:clap: 
___
*[`pkg/sql/sem/builtins/builtins.go` line 2428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGI8-_S3w8CdwCmsZd6:-NGI8-_S3w8CdwCmsZd7:becyhyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/sql/sem/builtins/builtins.go#L2428)):*
> ```Go
> 			},
> 			Info:       "Convert an timestamp to a string using the given format.",
> 			Volatility: volatility.Immutable,
> ```

in postgres this is stable. any reason we shouldn't match it?

```
rafiss=# select proname, prosrc, provolatile, proleakproof from pg_proc where proname like 'to_char%';
 proname |       prosrc        | provolatile | proleakproof
---------+---------------------+-------------+--------------
 to_char | timestamptz_to_char | s           | f
 to_char | numeric_to_char     | s           | f
 to_char | int4_to_char        | s           | f
 to_char | int8_to_char        | s           | f
 to_char | float4_to_char      | s           | f
 to_char | float8_to_char      | s           | f
 to_char | interval_to_char    | s           | f
 to_char | timestamp_to_char   | s           | f
```
___
*[`pkg/util/duration/BUILD.bazel` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGIB8EL0t__iijTCco1:-NGIB8EL0t__iijTCco2:b-x5jgpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda317d28d7c4f94e5deb1ad407f602d6ed06538/pkg/util/duration/BUILD.bazel#L18)):*
> ```Starlark
>         "//pkg/sql/pgwire/pgcode",
>         "//pkg/sql/pgwire/pgerror",
>         "//pkg/sql/types",
> ```

this will pull in the `protobuf` dependency transitively. is it worth avoiding that by not using the `types` package from within the `duration` package?
___
*[`pkg/util/tochar/constants.go` line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGI8cNm8Ny5aoWcInfd:-NGI8cNm8Ny5aoWcInfe:bcwyezn) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/util/tochar/constants.go#L296)):*
> ```Go
> var dchIndex = []dchPos{
> 	/*
> 	   0	1	2	3	4	5	6	7	8	9
> ```

what's with this counting? is the comment supposed to line up with the code? probably we'll want to do something else due to the autoformatter
___
*[`pkg/util/tochar/tochar.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGI8xiA59oGB54NqRIt:-NGI8xiBA7g6R2L5mhdZ:b4k6k90) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/util/tochar/tochar.go#L28)):*
> ```Go
> // TimeToChar converts a time and a `to_char` format string to a string.
> func TimeToChar(t time.Time, f string) (string, error) {
> 	// TODO(#sql-experience): consider caching parse formats.
> ```

if this is a goal we should have, then should we have some microbenchmarks in place?
___
*[`pkg/util/tochar/tochar.go` line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGI9aMd2zTbaCphiraL:-NGI9aMd2zTbaCphiraM:b-5pr161) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/util/tochar/tochar.go#L401)):*
> ```Go
> 
> // parseFormat matches parse_format. We do not take in a flags as we only do
> // the DCH mode.
> ```

what is the DCH mode?
___
*[`pkg/util/tochar/tochar.go` line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGIBlIG15kXYE8KO73m:-NGIBlIG15kXYE8KO73n:b-nygc3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf3616bf2ce7b23e5dabf88a09fe6c095709a26/pkg/util/tochar/tochar.go#L63)):*
> ```Go
> }
> 
> // durationWrapper wraps duration.Duration to implement timeInterface.
> ```

it looks like it's not wrapping it, but instead reimplementing it. could be worth explaining why in the comment
___
*[`pkg/sql/logictest/testdata/logic_test/timestamp` line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGIASBRANDlivyUNDF0:-NGIASBRANDlivyUNDF1:b-fibynj) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/sql/logictest/testdata/logic_test/timestamp#L554)):*
> ```
> 1 day
> 
> # Rough translation of the to_char tests from PostgreSQL.
> ```

what about these tests and the ones below?

https://github.com/postgres/postgres/blob/0e758ae89a20f233bb1c20a0f52ac7c81b2ef1b8/src/test/regress/expected/timestamptz.out#L2105-L2110
___
*[`pkg/util/tochar/tochar_test.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGIAmpvCgY0XyWGcPIy:-NGIAmpw4rj1crkQogWq:b-yojadr) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/util/tochar/tochar_test.go#L27)):*
> ```Go
> 
> // TestDataDriven tests the relevant to_char facilities.
> func TestDataDriven(t *testing.T) {
> ```

i love this!

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91382)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGICSTYBR5IgJmMR7_A):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

:clap: 
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins.go` line 2428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGI8-_S3w8CdwCmsZd6:-NGIRQbU2ODaM01c-Qhj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/sql/sem/builtins/builtins.go#L2428)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in postgres this is stable. any reason we shouldn't match it?

```
rafiss=# select proname, prosrc, provolatile, proleakproof from pg_proc where proname like 'to_char%';
 proname |       prosrc        | provolatile | proleakproof
---------+---------------------+-------------+--------------
 to_char | timestamptz_to_char | s           | f
 to_char | numeric_to_char     | s           | f
 to_char | int4_to_char        | s           | f
 to_char | int8_to_char        | s           | f
 to_char | float4_to_char      | s           | f
 to_char | float8_to_char      | s           | f
 to_char | interval_to_char    | s           | f
 to_char | timestamp_to_char   | s           | f
```
</blockquote></details>

Done.
___
*[`pkg/util/duration/BUILD.bazel` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGIB8EL0t__iijTCco1:-NGIRWEo4aoiEq-HYe_1:b-u845qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda317d28d7c4f94e5deb1ad407f602d6ed06538/pkg/util/duration/BUILD.bazel#L18)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this will pull in the `protobuf` dependency transitively. is it worth avoiding that by not using the `types` package from within the `duration` package?
</blockquote></details>

eh, it's hard-ish to remove IntervalTypeMetadata so i'm inclined to go with no unless we have a good reason we shouldn't pull it in. I think we already do due to `IntervalStyle` pulling protobufs.
___
*[`pkg/util/tochar/constants.go` line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGI8cNm8Ny5aoWcInfd:-NGIRghD46oFz0VRDSj3:b1e6tom) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/util/tochar/constants.go#L296)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what's with this counting? is the comment supposed to line up with the code? probably we'll want to do something else due to the autoformatter
</blockquote></details>

Ah, this was leftover from a PG comment. I can delete it.
___
*[`pkg/util/tochar/tochar.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGI8xiA59oGB54NqRIt:-NGIRlrs0Vd6YeLBgZvX:b-n3t99y) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/util/tochar/tochar.go#L28)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

if this is a goal we should have, then should we have some microbenchmarks in place?
</blockquote></details>

do microbenchmarks catch caching though? :P
(yes, but i'm not fussed enough to do it atm)
___
*[`pkg/util/tochar/tochar.go` line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGI9aMd2zTbaCphiraL:-NGIS3AK6CJXRnNd1OPO:b-udd3qn) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/util/tochar/tochar.go#L401)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what is the DCH mode?
</blockquote></details>

Done. date-char i think, but i just changed the comment
___
*[`pkg/util/tochar/tochar.go` line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGIBlIG15kXYE8KO73m:-NGITwrvCM6oJcBaHoCS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf3616bf2ce7b23e5dabf88a09fe6c095709a26/pkg/util/tochar/tochar.go#L63)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it looks like it's not wrapping it, but instead reimplementing it. could be worth explaining why in the comment
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/timestamp` line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-NGIASBRANDlivyUNDF0:-NGISABM4sUoCFCd6diB:b-s3akkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/57768b962f89ac6afda8019c9b1364f7361c8c73/pkg/sql/logictest/testdata/logic_test/timestamp#L554)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what about these tests and the ones below?

https://github.com/postgres/postgres/blob/0e758ae89a20f233bb1c20a0f52ac7c81b2ef1b8/src/test/regress/expected/timestamptz.out#L2105-L2110
</blockquote></details>

Done.

weird, we don't support naming a column "of" (syntax error), but other than that i copied it.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91382#-:-NGNBbf70lKjVuWfX5dJ:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
