### PR TITLE
syncutil: add tracing and timing to mutex acquisition

### LINKED ISSUE #115506: syncutil: add tracing to mutex acquisition
Mutex contention is invisible in request traces. That's an issue for debugging tail latency, as rarely contended mutexes can cause significant delay in the rare cases where they are contended. Tracking down this source of slowness is currently quite difficult. The only real tool we have for this is `mutex` profiles, but this shows an aggregated view of mutex contention which hides tail events.

A good example of this kind of issue is https://github.com/cockroachdb/cockroach/issues/84943. Typically, an `RLock` attempt on the request hot-path would be granted immediately. However, in the rare cases (~1 in 100) where the write lock was held, requests would be delayed for 10s of milliseconds.

A solution to this would be to integrate tracing into our mutex implementation (and corresponding rwmutex implementation), so that we can add mutex delays to traces. This way, a trace that captures a slow request execution will include the reason for the delay, instead of having opaque delays between trace events which are typically reached in quick succession.

Here's an example of how this might look:

```go
/* pkg/util/syncutil/mutex_sync.go */

type tryLocker interface {
	sync.Locker
	TryLock() bool
}

func tracedLock(ctx context.Context, l tryLocker) {
	if l.TryLock() {
		return // fast-path
	}
	if !log.ExpensiveLogEnabled(ctx, 3) {
		l.Lock()
		return
	}
	start := timeutil.Now()
	l.Lock()
	if dur := timeutil.Since(start); dur > 250*time.Microsecond {
		file, line, _ := caller.Lookup(1)
		log.VWarningf(ctx, 3, "slow mutex acquisition (%s) at %s:%d", dur, file, line)
	}
}

func (m *Mutex) TracedLock(ctx context.Context) { tracedLock(ctx, m) }

func (rw *RWMutex) TracedLock(ctx context.Context)  { tracedLock(ctx, rw) }
func (rw *RWMutex) TracedRLock(ctx context.Context) { tracedLock(ctx, (*rTryLocker)(rw)) }

type rTryLocker RWMutex

func (r *rTryLocker) Lock()         { (*RWMutex)(r).RLock() }
func (r *rTryLocker) Unlock()       { (*RWMutex)(r).RUnlock() }
func (r *rTryLocker) TryLock() bool { return (*RWMutex)(r).TryRLock() }

```

Jira issue: CRDB-34070

Epic CRDB-34227

### PR DESCRIPTION
**Pull request by nvb**
Fixes #115506.
Informs #99473.

The first commit adds a new `TracedLock` (and `TracedRLock`) method to the `Mutex` (and `RWMutex`) type. This method behaves like `Lock`, but it also logs a trace event using the provided context if the lock acquisition is slow (> 250μs).

Slow lock acquisitions that use `TracedLock` will now be surfaced in traces. We can use this to track down slow lock acquisitions on the hot path of request handling. These slow lock acquisitions can often be the source of tail latency, and until now, their effect was entirely opaque when looking at traces.

The second commit adds a new `TimedLock` (and `TimedRLock`) method to the `Mutex` (and `RWMutex`) type. This method behaves like `Lock`, but it also returns the time it took to acquire the lock.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reflecting on this further, I think the need to manually inject otel trace events around specific, known goroutine preemption points is unfortunate. In a more sophisticated world, request tracing and runtime tracing would be married such that any interaction that a request has with the scheduler/gc/mutexes/timers/channels/etc would be surfaced in the request trace. We're not there yet[^1], so this opt-in mutex tracing seems better than nothing. I'd be happy to throw it out if there's a better approach that I haven't considered.

[^1]: unless @andreimatei knows something that I don't, or has been cooking up some magic recently.

**Review by andreimatei — COMMENTED** [review]
You're not happy with the present patch because you had to add a `ctx` arg to `mu.Lock()` ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115521#-:-NlTrXBW-YH18f46lZvx:bnh7ob7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Comment by nvanbenschoten** [comment]
> You're not happy with the present patch because you had to add a ctx arg to mu.Lock() ?

Kind of. I'm not happy with the present patch because it only instruments mutex acquisition, and doesn't handle all of the other reasons why a goroutine might yield or be preempted. For example, I want request traces to tell me "the Go GC ran from this point to this point, and there were stop-the-world pauses from here to here."

**Review by erikgrinaker — APPROVED** [review]
:lgtm: Nice work. I agree that it would be even better if we could integrate with the Go scheduler, but this seems fine in the interim.

This is adjacent to #99473. Should we generalize this by adding a `TimedLock()` method which returns the lock duration, and build `TracedLock()` on top of it?

> Reviewed 7 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115521#-:-NlcrA1n2TLXvIsT2hHo:bjzpx4i)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_send.go` line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115521#-Nlcs5AG4phFW6jAW-wR:-Nlcs5AG4phFW6jAW-wS:b-ui2v8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc96b2380bd38adddb4854daeb8426303ea80ad1/pkg/kv/kvserver/replica_send.go#L149)):*
> ```Go
> 
> 	// If the internal Raft group is quiesced, wake it and the leader.
> 	r.maybeUnquiesce(ctx, true /* wakeLeader */, true /* mayCampaign */)
> ```

It's a bit unfortunate that we have to instrument specific lock acquisitions like this, since we could easily have further `Replica.mu.RLock()` acquisitions during request processing which would contribute to tail latency. But it seems prudent to do a gradual, targeted introduction of this.
___
*[`pkg/util/syncutil/mutex_tracing.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115521#-NlclJFm01IOeTJ3_ShU:-NlclJFm01IOeTJ3_ShV:b-rf9ct4) ([raw file](https://github.com/cockroachdb/cockroach/blob/35c423a06ba88cbec2a7831d8b4475b8d1eee555/pkg/util/syncutil/mutex_tracing.go#L89)):*
> ```Go
> // considered slow enough to log. It is a variable and not constant so that it
> // can be changed in tests.
> var slowLockLogThreshold = 250 * time.Microsecond
> ```

Is this a bit aggressive? This could become quite spammy on an overloaded system with repeated mutex acquisition. Consider something like 1ms.

**Review by nvb — COMMENTED** [review]
> Should we generalize this by adding a `TimedLock()` method which returns the lock duration, and build `TracedLock()` on top of it?

Nice idea. Done in a separate commit. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115521#-:-NleP13v110yvRvB9vhW:b-oxd7s7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker)

___
*[`pkg/util/syncutil/mutex_tracing.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115521#-NlclJFm01IOeTJ3_ShU:-NleOjEA4ggNDBS8yud-:b-3cka1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/35c423a06ba88cbec2a7831d8b4475b8d1eee555/pkg/util/syncutil/mutex_tracing.go#L89)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Is this a bit aggressive? This could become quite spammy on an overloaded system with repeated mutex acquisition. Consider something like 1ms.
</blockquote></details>

Let's compromise at 500µs. This is just going to traces, not logs, so I'm less worried about the spam, and it would be useful to see that we're spending this much time in lock acquisition, even if we also know that the system is overloaded.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 7 of 7 files at r3, 2 of 2 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115521)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`-- commits` line 31 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/115521#-Nlh98Fw0oDa7GWEFOeC):*
Yeah, fine to do that separately. I'll add a comment to #99473. Thanks!
___
*[`pkg/util/syncutil/mutex_tracing.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115521#-NlclJFm01IOeTJ3_ShU:-Nlh7dD976BC-WkEu8hh:b-s8cbvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/35c423a06ba88cbec2a7831d8b4475b8d1eee555/pkg/util/syncutil/mutex_tracing.go#L89)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's compromise at 500µs. This is just going to traces, not logs, so I'm less worried about the spam, and it would be useful to see that we're spending this much time in lock acquisition, even if we also know that the system is overloaded.
</blockquote></details>

Yup. I was thinking it might become an issue if we used it more widely, e.g. for all mutex acquisitions during a request, but it's not a problem at present.

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=erikgrinaker

**Pull request merged**
