### PR TITLE
rangefeed: introduce processor interface

### PR DESCRIPTION
**Pull request by aliher1911**
This PR extracts externally visible processor functions into interface.
This will allow us to provide alternative implementations while keepingan option to fall back to old one.

Release note: None

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-26372

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Do you mind rebasing onto master?

**Comment by aliher1911** [comment]
Done

**Comment by erikgrinaker** [comment]
Ran this through `BenchmarkRangefeed` just to see what the dynamic dispatch cost would be. Appears negligible, as expected:

```
name                                      old time/op  new time/op  delta
Rangefeed/opType=write/numRegs=1-24       1.72µs ± 4%  1.72µs ± 5%    ~     (p=0.922 n=18+19)
Rangefeed/opType=write/numRegs=10-24      9.25µs ± 7%  9.34µs ± 5%    ~     (p=0.428 n=20+19)
Rangefeed/opType=write/numRegs=100-24      126µs ± 1%   127µs ± 5%    ~     (p=0.078 n=18+18)
Rangefeed/opType=commit/numRegs=1-24      4.43µs ± 5%  4.38µs ± 4%    ~     (p=0.138 n=19+19)
Rangefeed/opType=commit/numRegs=10-24     11.7µs ± 7%  11.8µs ± 8%    ~     (p=0.344 n=20+20)
Rangefeed/opType=commit/numRegs=100-24     128µs ± 2%   127µs ± 2%  -0.67%  (p=0.018 n=19+17)
Rangefeed/opType=closedts/numRegs=1-24    1.39µs ± 7%  1.40µs ±10%    ~     (p=0.784 n=20+20)
Rangefeed/opType=closedts/numRegs=10-24   7.94µs ± 6%  8.10µs ± 5%  +1.97%  (p=0.009 n=19+20)
Rangefeed/opType=closedts/numRegs=100-24   118µs ± 1%   117µs ± 2%    ~     (p=0.103 n=17+18)
```

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[`pkg/kv/kvserver/rangefeed/legacy_processor.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbETjF1-J3_sqpMn3qv:-NbETjF1-J3_sqpMn3qw:b-4eure) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/legacy_processor.go#L28)):*
> ```Go
> )
> 
> type LegacyProcessor struct {
> ```

Should we keep this code in its original location, to retain the blame history and such?

If not, it would at least be helpful to do the code movement as a separate commit, so that it's possible to review the code changes.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEUvJDDqAvayH8ZH_3:-NbEUvJDDqAvayH8ZH_4:bcj2qyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor.go#L103)):*
> ```Go
> //  2. it transforms a range-level closed timestamp to a rangefeed-level resolved
> //     timestamp.
> type Processor interface {
> ```

These methods should have comments.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEWMioDhETHLjpyobK:-NbEWMioDhETHLjpyobL:be9av24) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor.go#L107)):*
> ```Go
> 
> 	// Start processor with intent scanner.
> 	// Intent scanner factory should move to config for consistency.
> ```

+1, can we either add on a commit here to do this, or submit a separate PR?
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEWzB_-6ViNuve4K8E:-NbEWzB_-6ViNuve4K8F:b-sdv9k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor.go#L110)):*
> ```Go
> 	Start(stopper *stop.Stopper, rtsIterFunc IntentScannerConstructor) error
> 	Stop()
> 	StopWithErr(pErr *kvpb.Error)
> ```

I wonder if we should merge these two, and have the caller pass a `nil` error for successful stop, to reduce the interface surface. There's only a single `Stop()` caller.
___
*[`pkg/kv/kvserver/rangefeed/task.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEZYGc5Xs3sEf59Kjv:-NbEZYGc5Xs3sEf59Kjw:bmv83w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/task.go#L37)):*
> ```Go
> 
> // ProcessorTaskHelper abstracts away processor for tasks.
> type ProcessorTaskHelper interface {
> ```

Maybe I'm missing something, but I think we can get rid of this interface and the `runnable` interface above, to decouple these from the processor. Instead, we can simply pass in the necessary info to each task.

For example, `initResolvedTSScan` could do something like this:

```go
rtsIter := rtsIterFunc()
initScan := newInitResolvedTSScan(p.span, rtsIter)
err := stopper.RunAsyncTask(ctx, "rangefeed: init resolved ts", func(ctx context.Context) {
	if err := initScan.Run(ctx, p.sendEvent); err != nil {
		log.Errorf(ctx, "%v", err)
		p.StopWithErr(kvpb.NewError(err))
		return
	}
	p.initResolvedTS(ctx)
})
```

Similarly for the others.

I'm fine with deferring that to a follow-up PR, but I think it's worthwhile.
___
*[`pkg/kv/kvserver/rangefeed/legacy_processor_test.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEI9rW78DIxjgq3pMS:-NbEI9rW78DIxjgq3pMT:b8815t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/legacy_processor_test.go#L29)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	ctx := context.Background()
> 	var p *LegacyProcessor
> ```

Instead of making this test specific to `LegacyProcessor`, let's generalize it for all processors:

```
var p Processor = (*LegacyProcessor)(nil)
```

Then we can add a test case for the new scheduler-based processor too.
___
*[`pkg/kv/kvserver/rangefeed/processor_test.go` line 1344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEcNVD-ogV25aKvjwb:-NbEcNVECWWK1GPyuedE:b-hkdib3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor_test.go#L1344)):*
> ```Go
> // We use account and not a monitor for those checks because monitor doesn't
> // necessary return all data to the pool until processor is stopped.
> func requireBudgetDrainedSoon(t *testing.T, s Processor, stream *consumer) {
> ```

nit: why s? p?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[`pkg/kv/kvserver/rangefeed/legacy_processor_test.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEI9rW78DIxjgq3pMS:-NbEdX6L8i4a_0KN8U0X:b-wpcrow) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/legacy_processor_test.go#L29)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Instead of making this test specific to `LegacyProcessor`, let's generalize it for all processors:

```
var p Processor = (*LegacyProcessor)(nil)
```

Then we can add a test case for the new scheduler-based processor too.
</blockquote></details>

Actually, I'm not sure this is testing what we need anymore. These are here to guard against calls on a nil `Replica.rangefeedMu.proc`, but that's now always going to error because we're calling methods on a `nil` interface. I don't see anywhere in `LegacyProcessor` where it sets itself to `nil`, so it must be the `Replica` field that it's guarding against.

We may need to restructure some code to make this safe. Alternatively, make sure `Replica.rangefeedMu.proc` is always set to a non-nil `NoopProcessor` instead of nil -- perhaps more pragmatic, but also more smelly.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEWMioDhETHLjpyobK:-NbPG2OD4i9Lmqhxu0gZ:b-olo0qn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor.go#L107)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

+1, can we either add on a commit here to do this, or submit a separate PR?
</blockquote></details>

I dug into that and iterator function is relying on raftMu lock being held when it is called. So it must be called synchronously inside `Start()`. This is likely the reason it was not put into Config in the first place to avoid misuse. I'll remove my suggestion here and keep as is with a note.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEWzB_-6ViNuve4K8E:-NbPBJrMDJOV8O3uTJ1G:b-qtmb8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor.go#L110)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I wonder if we should merge these two, and have the caller pass a `nil` error for successful stop, to reduce the interface surface. There's only a single `Stop()` caller.
</blockquote></details>

I think they are semantically different. One case is where we want to kill registrations because replica is split, removed etc and the other one is when all replicas were wound down already and we are stopping as a result of all rangefeeds going away from client side. Underlying action is currently the same as you mentioned where we just pass nil error, but in may be different for scheduler.
___
*[`pkg/kv/kvserver/rangefeed/task.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEZYGc5Xs3sEf59Kjv:-NbP8izDCwoAU1WFq_7p:bqw0dyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/task.go#L37)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Maybe I'm missing something, but I think we can get rid of this interface and the `runnable` interface above, to decouple these from the processor. Instead, we can simply pass in the necessary info to each task.

For example, `initResolvedTSScan` could do something like this:

```go
rtsIter := rtsIterFunc()
initScan := newInitResolvedTSScan(p.span, rtsIter)
err := stopper.RunAsyncTask(ctx, "rangefeed: init resolved ts", func(ctx context.Context) {
	if err := initScan.Run(ctx, p.sendEvent); err != nil {
		log.Errorf(ctx, "%v", err)
		p.StopWithErr(kvpb.NewError(err))
		return
	}
	p.initResolvedTS(ctx)
})
```

Similarly for the others.

I'm fine with deferring that to a follow-up PR, but I think it's worthwhile.
</blockquote></details>

It will work for span() and pusher() but we have callbacks to send events, stop processor and initialize resolved timestamp so it is not clear cut. 
___
*[`pkg/kv/kvserver/rangefeed/processor_test.go` line 1344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEcNVD-ogV25aKvjwb:-NbPBCA48hlP_o_-wZRr:b-fn8mpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor_test.go#L1344)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: why s? p?
</blockquote></details>

:facepalm: 
___
*[`pkg/kv/kvserver/rangefeed/legacy_processor_test.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEI9rW78DIxjgq3pMS:-NbJTgC-6AOrDO4kf67e:b-azhdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/legacy_processor_test.go#L29)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Actually, I'm not sure this is testing what we need anymore. These are here to guard against calls on a nil `Replica.rangefeedMu.proc`, but that's now always going to error because we're calling methods on a `nil` interface. I don't see anywhere in `LegacyProcessor` where it sets itself to `nil`, so it must be the `Replica` field that it's guarding against.

We may need to restructure some code to make this safe. Alternatively, make sure `Replica.rangefeedMu.proc` is always set to a non-nil `NoopProcessor` instead of nil -- perhaps more pragmatic, but also more smelly.
</blockquote></details>

I think we can get rid of this test. Prior to extracting interface I checked all the call sites and we always check that processor is not nil after obtaining it from replica under rangeFeedLock. It might be defence in depth, but not sure it is really worth the added complexity if we have interface.

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 4 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[`pkg/kv/kvserver/rangefeed/interface.go` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbPZEXq5a6QLy5tZIf7:-NbPZEXr9KsMV94uF2d0:b6kveo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc4b587fb683abed71390b39e8dace2577b0d5f7/pkg/kv/kvserver/rangefeed/interface.go#L1)):*
> ```Go
> // Copyright 2023 The Cockroach Authors.
> ```

Why the strong desire to shuffle all this stuff around? We're just adding an interface here, and we'll likely remove the old code in 24.2. It'll just make it harder to read history and backport fixes.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEWMioDhETHLjpyobK:-NbP_lHDD1H4Gjss8IsD:b-ktxkcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor.go#L107)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I dug into that and iterator function is relying on raftMu lock being held when it is called. So it must be called synchronously inside `Start()`. This is likely the reason it was not put into Config in the first place to avoid misuse. I'll remove my suggestion here and keep as is with a note.
</blockquote></details>

Now I'm kind of wondering why we don't simply pass in the iterator though. Probably a performance thing, but we call `Register` immediately below to synchronize with it.

Anyway, nbd, we can keep this as-is.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEWzB_-6ViNuve4K8E:-NbPc4XK4oAeFsQA5Tp1:bncip9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor.go#L110)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I think they are semantically different. One case is where we want to kill registrations because replica is split, removed etc and the other one is when all replicas were wound down already and we are stopping as a result of all rangefeeds going away from client side. Underlying action is currently the same as you mentioned where we just pass nil error, but in may be different for scheduler.
</blockquote></details>

Well, the semantics is whether we tear down due to an error or a regular close, which we can signal with pErr. But nbd.
___
*[`pkg/kv/kvserver/rangefeed/task.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEZYGc5Xs3sEf59Kjv:-NbPcQHzDLxkCdGS9Jhd:b-cwnqw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/task.go#L37)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

It will work for span() and pusher() but we have callbacks to send events, stop processor and initialize resolved timestamp so it is not clear cut. 
</blockquote></details>

The example code above handles that. The processor can deal with stopping and resolved TS initialization itself based on the result of the scan. We don't have to pass all this stuff into the task, the processor can do it itself based on the result of the task.
___
*[`pkg/kv/kvserver/rangefeed/legacy_processor_test.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEI9rW78DIxjgq3pMS:-NbPdYCf7VuDLzS-tUyF:b97tute) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/legacy_processor_test.go#L29)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I think we can get rid of this test. Prior to extracting interface I checked all the call sites and we always check that processor is not nil after obtaining it from replica under rangeFeedLock. It might be defence in depth, but not sure it is really worth the added complexity if we have interface.
</blockquote></details>

Yeah, we should get rid of the guards too, as they give a false sense of security: the `proc` field will be an untyped `nil` not `(*LegacyProcessor)(nil)`, so we'll panic before we reach the guards.

You're certain you audited all the relevant code and we're not missing anything here? I can do a pass as well.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @miretskiy)

___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEWMioDhETHLjpyobK:-NbPez2YAO-mV9BY6jg4:b-4jw9t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor.go#L107)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Now I'm kind of wondering why we don't simply pass in the iterator though. Probably a performance thing, but we call `Register` immediately below to synchronize with it.

Anyway, nbd, we can keep this as-is.
</blockquote></details>

I think we can do that, and it was likely done to be able to pass an empty iterator for tests. I don't think we have a case in production to ignore intent scan as it will break resolved timestamps. 
___
*[`pkg/kv/kvserver/rangefeed/legacy_processor_test.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEI9rW78DIxjgq3pMS:-NbVpTjl0l_LuXWCJYl-:b-lzd0pk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/legacy_processor_test.go#L29)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yeah, we should get rid of the guards too, as they give a false sense of security: the `proc` field will be an untyped `nil` not `(*LegacyProcessor)(nil)`, so we'll panic before we reach the guards.

You're certain you audited all the relevant code and we're not missing anything here? I can do a pass as well.
</blockquote></details>

We only care within replica. I did another pass and we always check for nil after we obtain current processor reference so all good.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 1 of 10 files at r2, 2 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @miretskiy)

___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEWMioDhETHLjpyobK:-Nbn72f-69RgIffm-tB5:b-91bk2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/processor.go#L107)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I think we can do that, and it was likely done to be able to pass an empty iterator for tests. I don't think we have a case in production to ignore intent scan as it will break resolved timestamps. 
</blockquote></details>

Probably true, but one could also simply pass in an appropriate iterator.

The performance bit I was alluding to is that this will do the engine seek concurrently with the registration (which requires a syncEventC() and some other coordination). Unclear if that really matters much.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 111 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-Nbn5zQ35Sn4OgwlT6x_:-Nbn5zQ35Sn4OgwlT6xa:b9jk32p) ([raw file](https://github.com/cockroachdb/cockroach/blob/14013762f2ff482c6f5b4b2f911bcdbd84ffeb57/pkg/kv/kvserver/rangefeed/processor.go#L111)):*
> ```Go
> 	// It is ok to start registering streams before background initialization
> 	// completes.
> 	// The provided iterator is used to initialize the rangefeed's resolved
> ```

nit: use blank lines between paragraphs.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 115 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-Nbn6Cwh4JGvCCjBPQ3L:-Nbn6Cwh4JGvCCjBPQ3M:b-i1sjug) ([raw file](https://github.com/cockroachdb/cockroach/blob/14013762f2ff482c6f5b4b2f911bcdbd84ffeb57/pkg/kv/kvserver/rangefeed/processor.go#L115)):*
> ```Go
> 	// initResolvedTSScan. The Processor promises to clean up the iterator by
> 	// calling its Close method when it is finished.
> 	// Note that newRtsIter must be called synchronously within Start by the
> ```

This isn't entirely accurate. It isn't called synchronously in Start, it's called in an async goroutine, and the only reason why that's ok is that the caller synchronizes with it via Register() before releasing raftMu. We should either spell this out, or have the caller construct it ahead of time.
___
*[`pkg/kv/kvserver/rangefeed/processor.go` line 130 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-Nbn9JNPBAJ9WT1rNqhS:-Nbn9JNPBAJ9WT1rNqhT:b8ntj0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/14013762f2ff482c6f5b4b2f911bcdbd84ffeb57/pkg/kv/kvserver/rangefeed/processor.go#L130)):*
> ```Go
> 	// Lifecycle of registrations.
> 
> 	// Register registers the stream over the specified span of keys.
> ```

Thanks for writing these comments. Should we update the comments on LegacyProcessor to just refer to the interface, e.g. "Register implements Processor", so that they don't drift and we don't have to update several comments across interface/implementations?
___
*[`pkg/kv/kvserver/rangefeed/task.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEZYGc5Xs3sEf59Kjv:-Nbn8l_T2IsSPqVeasgG:bqdtsmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/task.go#L37)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

The example code above handles that. The processor can deal with stopping and resolved TS initialization itself based on the result of the scan. We don't have to pass all this stuff into the task, the processor can do it itself based on the result of the task.
</blockquote></details>

We can deal with this later, wrote up https://github.com/cockroachdb/cockroach/issues/108694.
___
*[`pkg/kv/kvserver/rangefeed/legacy_processor_test.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107377#-NbEI9rW78DIxjgq3pMS:-NbnAcc6ADQBal_C16ie:b-o2qupw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a3122ea23fc5b3fd4b1e9d7bf54de5771e649a5/pkg/kv/kvserver/rangefeed/legacy_processor_test.go#L29)):*
>I did another pass and we always check for nil after we obtain current processor reference so all good.

👍

**Comment by aliher1911** [comment]
bors r=erikgrinaker

**Pull request merged**
