### PR TITLE
sql: allow implicit casting of string to more array types

### LINKED ISSUE #54672: sql: allow UUID[] literals to be written as '{uuid-..., uuid-...}'
Postgres emits UUIDs in this format when using pg_dump, and allows users to enter this format in the SQL shell. We should support it too.

Currently, this errors in CockroachDB

```
root@:26257/defaultdb> create table t (a int primary key, b uuid[]);
CREATE TABLE

root@:26257/defaultdb> insert into t values (1, '{18e7b17e-4ead-4e27-bfd5-bb6d11261bb6, 18e7b17e-4ead-4e27-bfd5-bb6d11261bb7}');
ERROR: value type string doesn't match type uuid[] of column "b"
SQLSTATE: 42804
HINT: you will need to rewrite or cast the expression
```

### PR DESCRIPTION
**Pull request by rafiss**
Release note (sql change): A string literal like '{X, Y, Z}'
is now automatically casted to an array when appropriate. Support is
added for UUID, Date, Bool, Time, TimeTZ, Timestamp, TimestampTZ, and
Interval arrays. (Int and Decimal were already supported.)

fixes #54672

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
Should we add some logic tests as part of this change? I see there's an `array` logic test file, which may be a good place? 

Change looks good to me, though it would be nice to get a quick look from @otan as well as he's way more familiar with this stuff.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54709#-:-MIKPHvm7NXMFphj2byh:b-wot56t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @arulajmani, and @solongordon)

**Comment by rafiss** [comment]
added the logic test. @otan would you like to look at this? no need to if you're busy, i feel comfortable going ahead as is.

**Review by otan — APPROVED** [review]
seems fine to me, curious why we can't do the others

**Comment by rafiss** [comment]
ah you mean arrays of other types? we could -- i was just being lazy and sort of deferring to the types that were already tested in constant_test.go. 

well technically, we don't support `json[]` but i can do the other ones and add them to that test.

**Comment by otan** [comment]
happy for that to be a separate PR. just wondering where the line stops :P

**Comment by rafiss** [comment]
It was easy enough to add FloatArray, INetArray, and VarbitArray to this PR.

unfortunately I had trouble with Box2d, Geometry, and Geography arrays, so not including them here.

**Comment by rafiss** [comment]
TFTRs! i'm merging, and will backport to 20.2 after the initial 20.2.0 release goes out

bors r=otan,arulajmani

**Comment by rafiss** [comment]
bors r-

fixing formatting in the logic test

**Comment by rafiss** [comment]
bors r=otan,arulajmani

**Pull request merged**
