### PR TITLE
storage: move OriginID into LDR container in MVCCValueHeader

### PR DESCRIPTION
**Pull request by msbutler**
This patch replaces the OriginID field in the MVCCValueHeader with a pointer to an LDR specific proto message that contains the OriginID. This was done so in future releases, we can easily add more LDR specific fields to the mvcc value header without increasing the on disk or in memory footprint of an mvcc value header that is not used during LDR.

Epic: none

Release note: none

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, @msbutler, and @stevendanna)

___
*[`pkg/storage/enginepb/mvcc3_valueheader.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-O26Cutp4C26IAUeTZqZ:-O26Cutp4C26IAUeTZq_:b-7wg4nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/13e808db15f4a94835378051f3334466a9b009a9/pkg/storage/enginepb/mvcc3_valueheader.go#L21)):*
> ```Go
> }
> 
> func (h *MVCCValueHeader) GetLogicalReplicationOriginID() uint32 {
> ```

[nit] might need a comment for the linter
___
*[`pkg/storage/enginepb/mvcc3_valueheader.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-O26CfBvCYfkhBTHZLuB:-O26CfBvCYfkhBTHZLuC:b5vn9ac) ([raw file](https://github.com/cockroachdb/cockroach/blob/13e808db15f4a94835378051f3334466a9b009a9/pkg/storage/enginepb/mvcc3_valueheader.go#L29)):*
> ```Go
> 
> func (h *LogicalReplicationMetadata) Equal(that *LogicalReplicationMetadata) bool {
> 	return h.OriginID != that.OriginID
> ```

==

Do we need this method?

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, @RaduBerinde, and @stevendanna)

___
*[`pkg/storage/enginepb/mvcc3_valueheader.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-O26CfBvCYfkhBTHZLuB:-O26Ha7C923H0EC6SOxU:b-c51dji) ([raw file](https://github.com/cockroachdb/cockroach/blob/13e808db15f4a94835378051f3334466a9b009a9/pkg/storage/enginepb/mvcc3_valueheader.go#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

==

Do we need this method?
</blockquote></details>

heh, LLM autocomplete did not get that one right.

yeah, the code doesn't compile without this method because MVCCValueHeader has a goproto Equal method

**Comment by msbutler** [comment]
@RaduBerinde hmmm, maybe adding a pointer to MVCCValueHeader has a much larger blast radius than we initially thought? 
https://github.com/msbutler/cockroach/blob/butler-move-origin-id/pkg/storage/enginepb/mvcc3.proto#L151

**Comment by RaduBerinde** [comment]
CC @jbowens @sumeerbhola who might have more context on this code

**Review by sumeerbhola — COMMENTED** [review]
> This was done so in future releases, we can easily add more LDR specific fields to the mvcc value header without increasing the on disk or in memory footprint of an mvcc value header that is not used during LDR.

A zero valued field is not marshaled. That is, if LDR adds more fields and they are zero valued when LDR is not being used, it shouldn't affect the on disk footprint. Regarding in-memory footprint, it will increase, but I don't think the MVCCValueHeader propagates far from the storage layer on a read -- at least for the LocalTimestamp case, I think we check uncertainty immediately after reading, and then don't need the LocalTimestamp again. @arulajmani to confirm this.

We also don't like to have nullable fields, like `LogicalReplicationMetadata`, since it causes allocations in the non-nil case.

Was this motivated mainly by a theoretical concern, or something tangible. If latter, could you elaborate?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-:-O2C0R_L3Gjf9qjagt-M:b-ou1pwv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, @RaduBerinde, and @stevendanna)

**Review by msbutler — COMMENTED** [review]
@sumeerbhola Some background and motivation: one field we'd like to add to `MVCCValueHeader` is the `OriginTimestamp`, the timestamp the kv was originally committed on the LDR source cluster. This new field will be used during conflict resolution. My original PR to add this field is here: https://github.com/cockroachdb/cockroach/pull/127580.  

My first approach in this PR was to simply add a non-nullable hlc.Timestamp to the MVCCValueHeader, but unfortunately the "zero" value of an `hlc.Timestamp` still gets marshalled, as you can see in the diff for TestEncodeDecodeMVCCValue.  To work around this we could:

1. Package all the LDR fields ( OriginTimestamp, OriginID, and maybe one or two more) in a separate proto messsage, and add a nullable entry to the MVCCValueHeader. This would keep the value header disk and memory footprint the same in the default case, but as you say, would lead to an additional allocation in the non nil case. This PR is a first step to this approach, but the code comment here may suggest that this approach is a non-starter? https://github.com/msbutler/cockroach/blob/butler-move-origin-id/pkg/storage/enginepb/mvcc3.proto#L151

2. Keep OriginID as a non-nullable field in the value header, and only add OriginWalltime to the proto. We can do this if we don't care about clock skew comparisons with the source cluster. This is an open question the LDR team needs to think about. These new LDR fields would still lead to a higher in memory footprint in the default case.

3. Conduct some MVCCValueHeader marshalling gymnastics, similar to what's been done for the KVNemesis field (i.e. a key written with LDR metadata data will be marshalled with a variant of the MVCCValueHeader proto message). I have not looked closely into this approach. These new LDR fields would still lead to a higher in memory footprint in the default case. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-:-O2FeptB51hoRECHaYzl:b8kj245)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, @RaduBerinde, and @stevendanna)

**Review by msbutler — COMMENTED** [review]
One more thought on approach 1:  This current PR is a first step to approach 1, but the code comment here may suggest that this approach is a non-starter? [https://github.com/msbutler/cockroach/blob/butler-move-origin-id/pkg/storage/enginepb/mvcc3.proto#L151](https://github.com/msbutler/cockroach/blob/butler-move-origin-id/pkg/storage/enginepb/mvcc3.proto#L151)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-:-O2FlXtz82COlp0JTSJo:b-5i3k5p)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, @RaduBerinde, and @stevendanna)

**Review by RaduBerinde — COMMENTED** [review]
> unfortunately the "zero" value of an `hlc.Timestamp` still gets marshalled, as you can see in the diff for TestEncodeDecodeMVCCValue

I don't think this is true. The existing structure has a non-nullable local timestamop. This is the encoding of a header with a zero local timestamp:
https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/testdata/TestEncodeDecodeMVCCValue/tombstone

And this is the encoding when the local timestamp is non-zero (no other differences):
https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/testdata/TestEncodeDecodeMVCCValue/header_tombstone

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-:-O2G1zKr8OlUAubj6CYh:bd1ho1y)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, and @stevendanna)

**Review by RaduBerinde — COMMENTED** [review]
Sorry, messed up the first link above, it should be:
https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/testdata/TestEncodeDecodeMVCCValue/tombstone

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-:-O2G2bnV9iKE_0-6HEHr:bsq6nbu)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, and @stevendanna)

**Comment by RaduBerinde** [comment]
I don't know why the encodings change in that PR.. But I bet it's not actually encoding the data, if we set the origin timestamp to very large values, is the encoding larger?

**Comment by msbutler** [comment]
> if we set the origin timestamp to very large values, is the encoding larger?
yup, but only for the test cases we would expect: https://github.com/cockroachdb/cockroach/pull/127580/commits/e3e3d4ee23715330fa8ec33c527f89a4151bc826

**Review by RaduBerinde — COMMENTED** [review]
I tried separating the origin_timestamp and origin_id in a separate (non-nullable) message, and the encoding got even bigger, e.g. `header_tombstone`:
```
00000004650a020809 (master)
00000006650a0208093200 (your change)
00000008650a02080932020a00 (my change)
```

This is very strange, probably comes from some obscure details of the encoding.

So I tried going in the other direction: I embedded a int64 and int32 for the timestamp wall time and logical (instead of using hlc.Timestamp) and got the encoded back down to what it was, at least for header_tombstone: https://github.com/cockroachdb/cockroach/commit/0a719204e10417d59ef7b2db72b4c940232d6afc

By the way, this suggests that that `Empty` message might not be free, we should check if the encodings improve if we remove it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-:-O2G3bJgDQe8eHMBIg65:b9wpne7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, and @stevendanna)

**Review by RaduBerinde — COMMENTED** [review]
From what I can tell, the marshaling code doesn't have a concept of an "unset" non-pointer message field. The wiretag and the size of the message gets encoded regardless, even if all its fields are omitted. It's unfortunate that gogoproto doesn't allow omitting messages unless a pointer is used.

It won't help with the current problem but we should investigate newer libraries (gogoproto hasn't been updated since 2021), like https://github.com/planetscale/vtprotobuf or https://github.com/CrowdStrike/csproto

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-:-O2HlPSk7ISVC9_hPSax:bnlsph6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, and @stevendanna)

**Review by RaduBerinde — COMMENTED** [review]
Ok, so here's an idea. We already are doing a hack where we implement our own `MVCCValueHeader.Marshal()` which calls `h.pure().Marshal()`. AFAICT this hack is exactly so that the Empty field doesn't get encoded. So we can build on this and make the origin timestamp field a pointer in `MVCCValueHeaderPure`? The `pure()` method can set it to nil if it is zero, or a pointer to the field in the original message. Then the marshaller will actually omit it altogether when it is zero. We can do this with just the timestamp, or with a message that contains the origin timestamp and the origin id.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-:-O2HqZI9Cfiw9xAHfAmz:b-hhsvby)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, and @stevendanna)

**Review by RaduBerinde — COMMENTED** [review]
Prototyped here: https://github.com/cockroachdb/cockroach/commit/f0593b763f314103c4e008e2f2c19c80fd981fc5

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-:-O2IEQ1iBTFbGWpB6n5T:bqqnsg5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, and @stevendanna)

**Review by RaduBerinde — COMMENTED** [review]
Just realized this is exactly the option 3 Michael proposed above. It's simpler to implement than it sounds.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127465#-:-O2IFGok42eHRMJgNzd2:bjore7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, and @stevendanna)

**Comment by msbutler** [comment]
@RaduBerinde Thanks for the help digging into this!! Your prototype also allows the deep and shallow copy of `MVCCValueHeader` to be the same, so we don't need to worry about this comment I flagged: https://github.com/msbutler/cockroach/blob/butler-move-origin-id/pkg/storage/enginepb/mvcc3.proto#L151

I think it makes more sense to keep `OriginID` and `OriginTimestamp` as first class fields in `MVCCValueHeader` instead of in an LDR container, because the in memory representation `MVCCValueHeader` will potentially require less padding leading to a lower memory footprint. 

If y'all agree, I see the following next steps:
- Keep OriginID as is: a non nullable int
- Add OriginTimestamp using Radu's [prototype](https://github.com/cockroachdb/cockroach/pull/127465#pullrequestreview-2190200633) . 
- No backports to 24.2


Longer term questions:
-[ consider ](https://github.com/cockroachdb/cockroach/pull/127465#pullrequestreview-2190182746)switching to Crowdstrike's proto encoding library 😅 ??? Or some library that doesn't [require](https://github.com/cockroachdb/cockroach/pull/127465#pullrequestreview-2190182746) encoding the size of an arbitrary message field, if it's even possible.

**Comment by RaduBerinde** [comment]
In the shorter term, I can also look at forking gogoproto and adding an `omitempty` option to do this for us. I bet we could use this in many other places.

> I think it makes more sense to keep OriginID and OriginTimestamp as first class fields in MVCCValueHeader instead of in an LDR container, because the in memory representation MVCCValueHeader will potentially require less padding leading to a lower memory footprint.

Unfortunately, as long as the timestamp is in its own struct, we will lose 32 bits to padding. If we want to minimize the memory footprint, we would need to "inline" the `WallTime` and `Logical` values (that also solves the empty marshaling issue without hacks). But this is not consistent with other uses of the `Timestamp` so it seems odd to make an exception here.

We could change `Timestamp` to store three 32-bit integers and use custom Marshal/Unmarshal functions to keep the wire format the same. That would save 4 bytes in all structs where it is used. I like that because it's a self-contained change with benefits wherever `Timestamp` is used.

**Comment by RaduBerinde** [comment]
> it's a self-contained change

Scratch that, we'd need to add a `WallTime()` accessor which would change a ton of code.

**Comment by msbutler** [comment]
> Unfortunately, as long as the timestamp is in its own struct, we will lose 32 bits to padding.
Yeah, i understand that, but I think we'd have even more padding if the LDR fields were in a container. Consider a simple example (i hope my math and mental model of alignment are correct here):

```
MVCCValueHeader{
  OmitInRangeFeeds bool // + 1 byte, 1 bytes total 
  // align originID to 4 byte multiple: + 3 bytes , 4 bytes total
  OriginID uint32 //  + 4 bytes, 8 bytes total
  OriginTimestampWalltime // +8 bytes, 16 bytes total
  OriginTimestampLogical // +4 bytes, 20 bytes total
}
```
Vs:

```
LDR {
  OriginID 4 bytes
  OriginTimestamp 12 bytes, 8 byte alignment
} // LDR struct requires 8 byte alignment, the max alignment of the fields in the struct

MVCCValueHeader{
  OmitInRangeFeeds bool // + 1 byte, 1 bytes total 
  // 7 bytes of padding to align LDR: +7 bytes, 8 bytes total
  LDR {
     OriginID // +4 bytes, 12 bytes total
     // 4 more bytes of padding to align OriginTimestamp, +4 bytes, 16 bytes total
     OriginTimestampWalltime // + 8 bytes, 24 bytes total
     OriginTimestampLogical // + 4 bytes, 28 bytes total
  }
}
```

**Comment by RaduBerinde** [comment]
Good point, the bool and the uin32 pack more tightly together. Yeah, I don't think there would be any advantage to separating them (in fact, there's more encoding overhead).

**Comment by RaduBerinde** [comment]
Adding an `omitempty` to `gogoproto` is not hard. I believe it also removes the need for the `MVCCValueHeader/MVCCValueHeaderPure/MVCCValueHeaderCrdbtest` hack (the `KVNemesisSeq` field would always be empty in non-test builds).

I vote to proceed with your plan for now and we can subsequently clean things up with this new option.

**Comment by msbutler** [comment]
closing in favor of #127668

**Pull request closed without merging**
