### PR TITLE
check-style: add safesql

### PR DESCRIPTION
**Pull request by tamird**
Updates #2485.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7172)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM, but why didn't this catch the very unsafe queries in `cli/sql_util.go`? Did we confuse it with `sqlConnI`?

**Comment by tamird** [comment]
Yep, looks that way :(

**Comment by bdarnell** [comment]
#7139 is about to add a new unsafe query (in a test) that should be caught by `safesql`.

**Comment by tamird** [comment]
OK, I'll merge this and ask @mjibson to rebase

**Comment by mjibson** [comment]
`make check` passes even with this test. So...?

**Comment by tamird** [comment]
that's weird and surprising. maybe safesql doesn't look at test code.

**Pull request merged**
