### PR TITLE
sql/colexec: specialize RangeStats operator to achieve parallelism

### PR DESCRIPTION
**Pull request by ajwerner**
Release justification: This is needed to make new observability features reasonably performant, also sneaking it in under the deadline. 

Release note (performance improvement): The crdb_internal.range_statistics
function now uses a vectorized implementation which allows the lookup of
range metadata to occur in parallel.

### CODE REVIEW

**Comment by ajwerner** [comment]
@yuzefovich this is very unsophisticated but I never found time to make it much better. Can you take a look and see how offensive you find it to be? I'd like to get something in before stability period given we're trying to ship some form of fetching range stats in some observability pages.

**Review by yuzefovich — COMMENTED** [review]
Looks reasonable to me, I have some suggestions and nits.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-:-N8UU9BjEAHRBFp4TGhp:b-q608hd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/colexec/range_stats.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UUSQpDU8eyU1NMP7V:-N8UUSQpDU8eyU1NMP7W:b-ktxr0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L26)):*
> ```Go
> )
> 
> type rangeStatsOperator struct {
> ```

nit: it'd be good to add an `execbuilder` test which verifies (via `EXPLAIN (VEC)`) that the new operator is used.
___
*[`pkg/sql/colexec/range_stats.go` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8USQQ86KPXFmcfDFxN:-N8USQQ86KPXFmcfDFxO:b-sfak4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L43)):*
> ```Go
> 	fetcher eval.RangeStatsFetcher,
> 	allocator *colmem.Allocator,
> 	_ []*types.T,
> ```

nit: remove this argument and an error return parameter if they are unused.
___
*[`pkg/sql/colexec/range_stats.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8USjUi7kV31lFtbbqS:-N8USjUi7kV31lFtbbqT:b-hst7ag) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L74)):*
> ```Go
> 	}
> 	inSel := batch.Selection()
> 	inVec := batch.ColVec(r.argumentCols[0])
> ```

nit: if we always expect a single argument column, it'd be cleaner to pass in just an int then, not a slice.
___
*[`pkg/sql/colexec/range_stats.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8USxMI2DgHYdUSqrDL:-N8USxMI2DgHYdUSqrDM:bfkoyjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L88)):*
> ```Go
> 				}
> 			} else {
> 				keys = make([]roachpb.Key, 0, len(inSel))
> ```

Here we also want to use `batch.Length()` since `len(inSel)` can be larger - `batch.Length()` is the source of truth on the number of rows in the batch.
___
*[`pkg/sql/colexec/range_stats.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UUIty7db_9TwRCh4o:-N8UUIty7db_9TwRCh4p:b-eg8dgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L96)):*
> ```Go
> 			// at least, on average, contain keys so it'll be 2x the size of the
> 			// keys plus some constant multiple.
> 			res, err := r.fetcher.RangeStats(r.Ctx, keys...)
> ```

We don't care about the fetcher using the same txn as the operator, right?
___
*[`pkg/sql/colexec/range_stats.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UTSG_89VebTXON0NU:-N8UTSG_89VebTXON0NV:b-e6at38) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L109)):*
> ```Go
> 					colexecerror.ExpectedError(err)
> 				}
> 				output.JSON().Set(outputIndex, jsonDatum)
> ```

nit: we should extract `output.JSON()` call outside of the `for` loop.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UTyT23BI-CflrPHZw:-N8UTyT23BI-CflrPHZx:b-8rklgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/sem/builtins/builtins.go#L5447)):*
> ```Go
> 			Fn: func(ctx *eval.Context, args tree.Datums) (tree.Datum, error) {
> 				resps, err := ctx.RangeStatsFetcher.RangeStats(ctx.Ctx(),
> 					roachpb.Key(tree.MustBeDBytes(args[0])))
> ```

We should check for `tree.DNull` here.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85442)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/colexec/range_stats.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UVC3c3ps1vF4c-AXA:-N8UVC3c3ps1vF4c-AXB:bvcnmfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L101)):*
> ```Go
> 			}
> 			readResponse := func(resultIndex, outputIndex int) {
> 				jsonStr, err := gojson.Marshal(&res[resultIndex].MVCCStats)
> ```

Do you have a sense how large these JSONs can get?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85442)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/colexec/range_stats.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UUSQpDU8eyU1NMP7V:-N9TyXGxCPiEZzotRo6Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L26)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it'd be good to add an `execbuilder` test which verifies (via `EXPLAIN (VEC)`) that the new operator is used.
</blockquote></details>

Done.
___
*[`pkg/sql/colexec/range_stats.go` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8USQQ86KPXFmcfDFxN:-N9U-dGo3oUuA0Nobiym:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L43)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: remove this argument and an error return parameter if they are unused.
</blockquote></details>

Done.
___
*[`pkg/sql/colexec/range_stats.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8USjUi7kV31lFtbbqS:-N9U-cWlAEhQWtgCHHzr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L74)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: if we always expect a single argument column, it'd be cleaner to pass in just an int then, not a slice.
</blockquote></details>

Done.
___
*[`pkg/sql/colexec/range_stats.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8USxMI2DgHYdUSqrDL:-N9U08-S7vhQ5Kluy5pP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L88)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Here we also want to use `batch.Length()` since `len(inSel)` can be larger - `batch.Length()` is the source of truth on the number of rows in the batch.
</blockquote></details>

Done.
___
*[`pkg/sql/colexec/range_stats.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UUIty7db_9TwRCh4o:-N9Tye-I2exGHc4s_Q3P:b-l4jprd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L96)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We don't care about the fetcher using the same txn as the operator, right?
</blockquote></details>

right.
___
*[`pkg/sql/colexec/range_stats.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UVC3c3ps1vF4c-AXA:-N8UVko92Zhd8MFS6J-z:b-1wr6zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L101)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Do you have a sense how large these JSONs can get?
</blockquote></details>

They have a constant upper bound given all of the entries in that struct are numbers. 
___
*[`pkg/sql/colexec/range_stats.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UTSG_89VebTXON0NU:-N9U05ff6p5kv7JeFSyC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L109)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we should extract `output.JSON()` call outside of the `for` loop.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UTyT23BI-CflrPHZw:-N9Tyoi33SoMSJaUk0fa:b-inhvzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/sem/builtins/builtins.go#L5447)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We should check for `tree.DNull` here.
</blockquote></details>

I don't think we have to do that -- we know we won't get nil here because the function is not marked as `CalledWithNullInputs`

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 14 of 24 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-:-N9UZXdME_rgqb8Dm8ux:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/colexec/range_stats.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8USxMI2DgHYdUSqrDL:-N9UYqM37EjyJGo02iOh:brgpwku) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L88)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: can pull it out of the `if` block where `keys` is defined.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UTyT23BI-CflrPHZw:-N9UZ9vb5DRouh396UXO:b-g7h9n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/sem/builtins/builtins.go#L5447)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think we have to do that -- we know we won't get nil here because the function is not marked as `CalledWithNullInputs`
</blockquote></details>

Ack - although it'd be good to try doing that manually just to double check (my concern that I've seen a few cases where we forgot to have the DNull-check which led to panics, but I don't remember how those builtins were marked).

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-:-N9Uc_HNACw-f2cXbyIi:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`pkg/sql/colexec/range_stats.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8USxMI2DgHYdUSqrDL:-N9Ubzdx2KemISo-SXmU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/colexec/range_stats.go#L88)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: can pull it out of the `if` block where `keys` is defined.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85442#-N8UTyT23BI-CflrPHZw:-N9UcJMy6aeg9DVpZBt2:b-v2fc8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e5a55d7b7275026bfb089d94b5a44c1daa8c33/pkg/sql/sem/builtins/builtins.go#L5447)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Ack - although it'd be good to try doing that manually just to double check (my concern that I've seen a few cases where we forgot to have the DNull-check which led to panics, but I don't remember how those builtins were marked).
</blockquote></details>

I added the defensive check.

**Pull request merged**
