### PR TITLE
Update HLC using received responses.

### LINKED ISSUE #3525: kv: coordinator should update HLC from received responses
Currently, `func (c *Clock) Update(rt roachpb.Timestamp)` only invoked when range node receive request from gateway node. When gateway node receive response from range node, this function doesn't invoked. So, there will be some problem:
1) If HLC for nodeA is '1', for nodeB is '100' now. 
2) nodeB(as gateway node) start a txn to read keyA from nodeB(as range node), then we have read timestamp '100' for keyA in `tsCache` on nodeB. Then the txn commit at once.
3) nodeA(as gateway node) start a txn to write keyA to nodeB(as range node) with timestamp '1'(txn fetch the timestamp from the gateway node: nodeA). We check the read timestamp for keyA from `tsCache` on nodeB, and decide to push the txn timestamp to '101'. Then the txn commit at once.
4) nodeA doesn't invode `func (c *Clock) Update(rt roachpb.Timestamp)` when it receive response from nodeB. Then nodeA start a new txn to read keyA from nodeB with timestamp '2'. So, this new txn can't see the newest value(with timestamp '101') which updated by nodeA self. It's not conform to "program order" rule in "Sequential Consistency"

So, I think we need to invoke `func (c *Clock) Update(rt roachpb.Timestamp)` when gateway node receive response from range node. Then nodeA can read keyA with timestamp '102'.

### PR DESCRIPTION
**Pull request by knz**
Fixes #3525.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5309)

### CODE REVIEW

**Comment by knz** [comment]
@tschottdorf can you briefly check whether I'm working in the right direction?

**Comment by knz** [comment]
Any suggestion as to how to test this?

**Comment by tschottdorf** [comment]
Yep, this looks good. Added some comments.

For testing, do two unit tests: One which checks that the Store sets `Now` on success, failure and independent of whether we're transactional. Probably in `store_test.go`; a very simple unit test. There's one somewhere which tests the stuff in the `defer`, might add to that.

On the `DistSender` side, a small unit test as well - you can mock out `sendOneFn` (or something like that) to basically a noop that populates `.Now` (both for a successful and failed batch) and check that after a call to `DistSender.Send()` the HLC has updated with the timestamp you used. There should be tests that do similar things already.
You won't need to start a whole test server on the KV side at all.

---

Reviewed 11 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[kv/send.go, line 192 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD-qg0ovCEpskQdfjK1:-KD-qg0ovCEpskQdfjK2:-270088250) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a57a4862ffd392fbed9edc136521643b69df04/kv/send.go#L192)):*
Must check for `Error != nil`.

Since you're plumbing something on the context just for this, you should move this up, for example at the end of `sendSingleRange`.

There's a minimal oddity: We have this bit of code

```go
	if localServer := rpcContext.GetLocalInternalServerForAddr(addr); enableLocalCalls && localServer != nil {
		reply, err := localServer.Batch(ctx, &client.args)
		done <- batchCall{reply: reply, err: err}
		return
	}

```

which basically skips the network when sending to the local node anyway. There's no need to update the HLC for those responses. But I think that's safe to ignore - certainly doesn't hurt and getting around it is likely more work than it should be.

---

*[rpc/context.go, line 75 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD-tM0eXJw3IyLfMShX:-KD-tM0eXJw3IyLfMShY:-817530531) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a57a4862ffd392fbed9edc136521643b69df04/rpc/context.go#L75)):*
This can go if you move the update just a little bit as suggested.

---

*[storage/store.go, line 1558 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD-tYuoAN5J3xzL4den:-KD-tYuoAN5J3xzL4deo:1682316313) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a57a4862ffd392fbed9edc136521643b69df04/storage/store.go#L1558)):*
oh, I didn't remember that this defer only ran when transactional. We want to do this in the non-transactional case as well. Just put the `ba.Txn != nil` inside of the defer (it's practically always satisfied anyway) and pull the two `Now` assignments out of the `ba.Txn != nil`.

---

*[storage/store.go, line 1613 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD-ty35a-L5X1tn6b6E:-KD-ty36R15sVyPrHkRh:2127355074) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a57a4862ffd392fbed9edc136521643b69df04/storage/store.go#L1613)):*
this is redundant if the above code in the defer is fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-:-KD-u1RgRccKCvLodzs1:-635412734)*

**Comment by knz** [comment]
I'm working on the DistSender test now.

---

Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[kv/send.go, line 192 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD-qg0ovCEpskQdfjK1:-KD0H8TzoDLgfPoESMpc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a57a4862ffd392fbed9edc136521643b69df04/kv/send.go#L192)):*
Done.

---

*[rpc/context.go, line 75 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD-tM0eXJw3IyLfMShX:-KD0H9eoyNu5jtmEmJho:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a57a4862ffd392fbed9edc136521643b69df04/rpc/context.go#L75)):*
Done.

---

*[storage/store.go, line 1558 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD-tYuoAN5J3xzL4den:-KD0HoWuNcI0m9WjAWVU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a57a4862ffd392fbed9edc136521643b69df04/storage/store.go#L1558)):*
Done.

---

*[storage/store.go, line 1613 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD-ty35a-L5X1tn6b6E:-KD0I5Qr0nBikQV6WsjY:1071020586) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a57a4862ffd392fbed9edc136521643b69df04/storage/store.go#L1613)):*
I don't understand. What do you mean here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-:-KD0NhCM66FW64PhhOW-:1469404812)*

**Comment by tamird** [comment]
Reviewed 8 of 11 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309)*

**Comment by tschottdorf** [comment]
Cool, looks good. @tamird was kind enough to offer to take over the review and land this with you when you've added the test.

---

Reviewed 2 of 2 files at r2, 5 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-:-KD0RSLmFJm3swBcd98q:498388754)*

**Comment by knz** [comment]
Brilliant thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-:-KD0RffCpnKKrTYGAoYP:898422410)*

**Comment by tamird** [comment]
LGTM so far. Let me know when the other test is in.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/store_test.go, line 635 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD0RUMYrfOhR5ZhNp8a:-KD0RUMYrfOhR5ZhNp8b:-1514756289) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b338c0a9269329a2137055609ca7ee04c76b8e/storage/store_test.go#L635)):*
s/bach/batch/

---

*[storage/store_test.go, line 685 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD0SVaZNDpJ5PKCmdsX:-KD0SVa_aSENhbdOA7zO:-1280936503) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b338c0a9269329a2137055609ca7ee04c76b8e/storage/store_test.go#L685)):*
remove

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-:-KD0S_eiGUOXWpJ0bJd7:-472050726)*

**Comment by knz** [comment]
It's in now.

---

Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/store_test.go, line 635 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD0RUMYrfOhR5ZhNp8a:-KD0d14Itv_D8180rWhu:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b338c0a9269329a2137055609ca7ee04c76b8e/storage/store_test.go#L635)):*
Done.

---

*[storage/store_test.go, line 685 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD0SVaZNDpJ5PKCmdsX:-KD0d3jh4Onbtxcq0rrp:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/52b338c0a9269329a2137055609ca7ee04c76b8e/storage/store_test.go#L685)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-:-KD0d8DEjpvIpeQTvzTK:1334744143)*

**Comment by knz** [comment]
I gt a faioture in kv/TestMultiRangeScanReverseScanInconsistent. I think this test is conceptually wrong if we let the DistSender clock move forward with the response. I tried to "fix" the test but I think this fix is also conceptually wrong. Can you advise?

**Comment by tamird** [comment]
The fix definitely looks wrong, but what was the failure you got? Hard to help with so little information.

---

Reviewed 1 of 1 files at r5, 2 of 2 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[kv/dist_sender_test.go, line 876 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD3uA1TDrpRrQHsExMv:-KD3uA1TDrpRrQHsExMw:-384170653) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc1686f0510a6910e800b58e2bdeff38deb8b69/kv/dist_sender_test.go#L876)):*
extract "boom". also i think you can do this without string matching

---

*[kv/dist_sender_test.go, line 881 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD3uKwRLP7y5t3F1d6m:-KD3uKwRLP7y5t3F1d6n:-1892487399) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc1686f0510a6910e800b58e2bdeff38deb8b69/kv/dist_sender_test.go#L881)):*
use a message of the form "expected .... got ..." like we do everywhere else

---

*[kv/dist_sender_test.go, line 883 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD3uIyQ_PPmOwy271WI:-KD3uIyRaQQym8Qfthvx:-1280936503) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc1686f0510a6910e800b58e2bdeff38deb8b69/kv/dist_sender_test.go#L883)):*
remove

---

*[kv/dist_sender_test.go, line 889 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD3uWQLhEFmoY7dhjP_:-KD3uWQLhEFmoY7dhjPa:400398238) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc1686f0510a6910e800b58e2bdeff38deb8b69/kv/dist_sender_test.go#L889)):*
funky line wrapping here. maybe lift this to the line above or extract the function into a local variable?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-:-KD3uqpasj_XBe3OgSaq:-1538866953)*

**Comment by knz** [comment]
The error is:
```
--- FAIL: TestMultiRangeScanReverseScanInconsistent (0.10s)
        dist_sender_server_test.go:319: expected 1 row; got 2
```

That is, ReverseScan (not Scan) retrieved key "b" in addition to "a". Not surprising since the DistSender's timestamp moved forward upon receiving the results for the forward Scan. Not sure how to fix the test though.

---

Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[kv/dist_sender_test.go, line 876 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD3uA1TDrpRrQHsExMv:-KD4-ixNO4f3oxuM5-Z6:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc1686f0510a6910e800b58e2bdeff38deb8b69/kv/dist_sender_test.go#L876)):*
Done.

---

*[kv/dist_sender_test.go, line 881 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD3uKwRLP7y5t3F1d6m:-KD3zyA2ExIxiumsCRxz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc1686f0510a6910e800b58e2bdeff38deb8b69/kv/dist_sender_test.go#L881)):*
Done.

---

*[kv/dist_sender_test.go, line 883 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD3uIyQ_PPmOwy271WI:-KD4-EgJ_5brVkQTY3_v:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc1686f0510a6910e800b58e2bdeff38deb8b69/kv/dist_sender_test.go#L883)):*
Done.

---

*[kv/dist_sender_test.go, line 889 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD3uWQLhEFmoY7dhjP_:-KD4-d_xT-dxvBiqoC-8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fc1686f0510a6910e800b58e2bdeff38deb8b69/kv/dist_sender_test.go#L889)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-:-KD3zh_m16yix-K81C76:343511784)*

**Comment by tamird** [comment]
Ah, I see. I've pulled a modified version of your fixed into #5342 

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[kv/dist_sender_test.go, line 874 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD41JFAqvZxj-GJjm-t:-KD41JFBJ7gsv0h8sfwc:-1470673698) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d2d9a3127eb12577fae22ad06f262ce9bf5cc5/kv/dist_sender_test.go#L874)):*
this type assertion is useless, remove it. I realize you're just following the example set in this file. See https://github.com/cockroachdb/cockroach/pull/5342

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-:-KD43dED3XXXg-NxCysW:-1118286968)*

**Comment by knz** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/dist_sender_test.go, line 874 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-KD41JFAqvZxj-GJjm-t:-KD47w512LFccfIJO0UX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/41d2d9a3127eb12577fae22ad06f262ce9bf5cc5/kv/dist_sender_test.go#L874)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5309#-:-KD4A0E1R79V39wx38IV:1417088721)*

**Pull request merged**
