### PR TITLE
storage/engine: Add PebbleFileRegistry that tracks encrypted files for Pebble

### PR DESCRIPTION
**Pull request by sumeerbhola**
Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Generally looks good to me. 

In your commit message, you can remove the `Release note (<category, see below): ...` template.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-:-LrnWon5AMNQUDnqtuUz:b-c03h7q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/file_registry.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk51VX2uJtuJa8tVFE:-Lrk51VX2uJtuJa8tVFF:b-xoaykj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L1)):*
> ```Go
> package engine
> ```

Nit: you're missing copyright headers on these files.
___
*[pkg/storage/engine/file_registry.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk1sZfCgwVHF4i4qO7:-Lrk1sZg9iw9QEiy21b9:b1xs7hi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L20)):*
> ```Go
> // a registry file did not exist previously, since that would indicate that disabling the registry
> // can cause data loss.
> type FileRegistry struct {
> ```

Should this be `PebbleFileRegistry` (and the file renamed to `pebble_file_registry.go`). If we never use this with RocksDB, I think that delineation would be usefl.
___
*[pkg/storage/engine/file_registry.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk20yX4yxkSUVn0gQk:-Lrk20yYEElMIXEItPj5:babc6e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L38)):*
> ```Go
> 	registryFilename string
> 	mu               sync.Mutex
> 	currProto        *enginepb.FileRegistry // guarded by mu
> ```

A common idiom we use is an unnamed embedded struct:

```
mu struct {
  sync.Mutex
  currProto *enginepb.FileRegistry
}
```

That allows you to do `mu.Lock()`, and makes it clear what `mu` is protecting.
___
*[pkg/storage/engine/file_registry.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk2FUJ3AigDrkJlMYT:-Lrk2FUJ3AigDrkJlMYU:bvsl7sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L42)):*
> ```Go
> 
> const (
> 	kFileRegistryFilename = "COCKROACHDB_REGISTRY"
> ```

The `k` prefix for constants is a Google C++-ism that is not used in Go (at least not in our Go). This can be `fileRegistryFilename`.
___
*[pkg/storage/engine/file_registry.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk2VDqCtJ_dMYJQJsQ:-Lrk2VDqCtJ_dMYJQJsR:bbmukgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L45)):*
> ```Go
> )
> 
> func (r *FileRegistry) Load() error {
> ```

Should you be grabbing `r.mu` here? If not, add a comment to `Load` about its safety for concurrent access.
___
*[pkg/storage/engine/file_registry.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk38bv6b3K9Z0GnRhy:-Lrk38bv6b3K9Z0GnRhz:bletvbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L105)):*
> ```Go
> // Moves the entry under src to dst, if src exists. If src does not exist, but dst exists,
> // dst is deleted. Persists the registry if changed.
> func (r *FileRegistry) EnsureRenameEntry(src, dst string) error {
> ```

The C++ version uses the term `Maybe` rather than `Ensure`. Was the name change intentional? We use both terms in CRDB and either seems appropriate.
___
*[pkg/storage/engine/file_registry.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk3z439YJ2fOniK-iy:-Lrk3z439YJ2fOniK-iz:by6bhv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L147)):*
> ```Go
> 
> func (r *FileRegistry) tryMakeRelativePath(filename string) string {
> 	// Logic copied from file_registry.cc.
> ```

This logic won't work on Windows due to a different path separator (so encryption at rest is probably currently broken on Windows). This seems like a partial version of `filepath.Rel()`, though that won't work on Windows with memory filesystems. I think that is ok and we should just use `filepath.Rel()` here.
___
*[pkg/storage/engine/file_registry_test.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-LrnWIr282mf1jSBnHVE:-LrnWIr282mf1jSBnHVF:bpyyn79) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry_test.go#L24)):*
> ```Go
> }
> 
> func TestFileRegistry(t *testing.T) {
> ```

Does this test mirror the ones in `c-deps/libroach/file_registry_test.cc`. 
___
*[pkg/storage/engine/file_util.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-LrnW7KlA2k1xHYxK9m6:-LrnW7KlA2k1xHYxK9m7:be6mebz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_util.go#L33)):*
> ```Go
> 	}
> 	defer fdir.Close()
> 	if err := fdir.Sync(); err != nil {
> ```

I think this can be simplified to `return fdir.Sync()`.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41763)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/file_util.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-LrnW7KlA2k1xHYxK9m6:-LrnvruY1-EXZV3dblhp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_util.go#L33)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this can be simplified to `return fdir.Sync()`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/file_registry.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk51VX2uJtuJa8tVFE:-Lrnm0hIEYZkbRH4FI1i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L1)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: you're missing copyright headers on these files.
</blockquote></details>

Done.
___
*[pkg/storage/engine/file_registry.go, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-LrnojXj3Ud8mrK4DJis:-LrnojXj3Ud8mrK4DJit:bydg480) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L14)):*
> ```Go
> )
> 
> // FileRegistry keeps track of files for the data-FS and store-FS for Pebble (see encrypted_fs.go
> ```

encrypted_fs.go is not yet submitted, but I figured this dangling comment reference is acceptable for now.
___
*[pkg/storage/engine/file_registry.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk1sZfCgwVHF4i4qO7:-LrnoT0s2-LVoQ4MHMCK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L20)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this be `PebbleFileRegistry` (and the file renamed to `pebble_file_registry.go`). If we never use this with RocksDB, I think that delineation would be usefl.
</blockquote></details>

Done.
___
*[pkg/storage/engine/file_registry.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk20yX4yxkSUVn0gQk:-Lrnp6vL42-OOU7lOHDU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L38)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

A common idiom we use is an unnamed embedded struct:

```
mu struct {
  sync.Mutex
  currProto *enginepb.FileRegistry
}
```

That allows you to do `mu.Lock()`, and makes it clear what `mu` is protecting.
</blockquote></details>

Done.
___
*[pkg/storage/engine/file_registry.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk2FUJ3AigDrkJlMYT:-LrnpCFj6CVMWv4VdDZC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L42)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The `k` prefix for constants is a Google C++-ism that is not used in Go (at least not in our Go). This can be `fileRegistryFilename`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/file_registry.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk2VDqCtJ_dMYJQJsQ:-LrnqETV9VjpPQ2NWUl_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L45)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should you be grabbing `r.mu` here? If not, add a comment to `Load` about its safety for concurrent access.
</blockquote></details>

Done.
___
*[pkg/storage/engine/file_registry.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk38bv6b3K9Z0GnRhy:-LrnqwSwAVWynoIB_Mcd:b-89d40k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L105)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The C++ version uses the term `Maybe` rather than `Ensure`. Was the name change intentional? We use both terms in CRDB and either seems appropriate.
</blockquote></details>

It wasn't too intentional. 
- `Ensure` suggests the work may already be done, so do it only if it is not already done. Doesn't seem quite right for `EnsureRenameEntry` but is reasonable for `EnsureDelete`. Since `EnsureDelete` was the first one I was naming , I went with that.
- I have never used `Maybe`: I assume we use it when it is ok to not return an error in some cases (defined in the function comment) where nothing can be done. 
- I've used`Try` in some cases where the operation may not be able to do what is asked of it, and that noop is ok. `tryMakeRelativePath` fits with that. `Try` and `Maybe` sound similar if we define them in this way.

I'm fine with changing to `Maybe` if you prefer that.
___
*[pkg/storage/engine/file_registry.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk3z439YJ2fOniK-iy:-Lrnuo_XBl1BVo7f-S1w:bw06hk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L147)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This logic won't work on Windows due to a different path separator (so encryption at rest is probably currently broken on Windows). This seems like a partial version of `filepath.Rel()`, though that won't work on Windows with memory filesystems. I think that is ok and we should just use `filepath.Rel()` here.
</blockquote></details>

based on https://golang.org/pkg/path/filepath/#Rel and running the example there when base is `/a` the relative paths for the following are:
```
On Unix:
"/a/b/c": "b/c" <nil>
"/b/c": "../b/c" <nil>
```
We don't want the `../` style paths, since it will break compatibility with our RocksDB implementation.
___
*[pkg/storage/engine/file_registry_test.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-LrnWIr282mf1jSBnHVE:-LrnvRIX2ezX7KrE3B3V:b-irryeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry_test.go#L24)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does this test mirror the ones in `c-deps/libroach/file_registry_test.cc`. 
</blockquote></details>

No. That was partly deliberate (and partly an oversight) since the c++ code 
- exposes things like `Transform` and `GetFileEntry(..., bool relative)` that seemed unnecessary after looking at the callers, so the go code has a smaller interface.
- the c++ test doesn't verify that the file is correct like `checkEquality` does, after each operation.

 I'd looked at coverage of the go code, but now I've added some additional tests based on looking at the c++ code.

**Review by petermattis — APPROVED** [review]
:lgtm: modulo a few small comments.

PS You still have spurious `Release note (<category, see below>): <what> <show> <why>` lines in your commit messages. Those should be removed. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-:-LroO__z4EU_VKAULU_6:br2ngu3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/file_registry.go, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-LrnojXj3Ud8mrK4DJis:-LroNy4gBxZAM9iiozB5:b46dg8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L14)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

encrypted_fs.go is not yet submitted, but I figured this dangling comment reference is acceptable for now.
</blockquote></details>

Ack. That's fine.
___
*[pkg/storage/engine/file_registry.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk38bv6b3K9Z0GnRhy:-LroO9jMD1Csnavx6niW:bf62eem) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L105)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It wasn't too intentional. 
- `Ensure` suggests the work may already be done, so do it only if it is not already done. Doesn't seem quite right for `EnsureRenameEntry` but is reasonable for `EnsureDelete`. Since `EnsureDelete` was the first one I was naming , I went with that.
- I have never used `Maybe`: I assume we use it when it is ok to not return an error in some cases (defined in the function comment) where nothing can be done. 
- I've used`Try` in some cases where the operation may not be able to do what is asked of it, and that noop is ok. `tryMakeRelativePath` fits with that. `Try` and `Maybe` sound similar if we define them in this way.

I'm fine with changing to `Maybe` if you prefer that.
</blockquote></details>

`Try` or `Maybe` feel like a better fit here. I'd go with `Maybe`, but my preference there is weak.
___
*[pkg/storage/engine/file_registry.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk3z439YJ2fOniK-iy:-LroNV2tAv2GDc7S8ZP_:b-e2zpmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L147)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

based on https://golang.org/pkg/path/filepath/#Rel and running the example there when base is `/a` the relative paths for the following are:
```
On Unix:
"/a/b/c": "b/c" <nil>
"/b/c": "../b/c" <nil>
```
We don't want the `../` style paths, since it will break compatibility with our RocksDB implementation.
</blockquote></details>

Does any of our usage actually result in `../` paths? I believe `filename` is always underneath `dbDir`.
___
*[pkg/storage/engine/pebble_file_registry.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-LroNcOZ50NjfLdcVqKE:-LroNcOZ50NjfLdcVqKF:b-l75ted) ([raw file](https://github.com/cockroachdb/cockroach/blob/20aad8f294d55e69eb36d02b9c65a615a8067233/pkg/storage/engine/pebble_file_registry.go#L174)):*
> ```Go
> 		return ""
> 	}
> 	if len(dbDir) > 0 && dbDir[len(dbDir)-1] != '/' {
> ```

`s/'/'/os.PathSeparator/g`
___
*[pkg/storage/engine/pebble_file_registry.go, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-LroNggF1ufiHJ2NvROl:-LroNggF1ufiHJ2NvROm:b-rfj4yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/20aad8f294d55e69eb36d02b9c65a615a8067233/pkg/storage/engine/pebble_file_registry.go#L175)):*
> ```Go
> 	}
> 	if len(dbDir) > 0 && dbDir[len(dbDir)-1] != '/' {
> 		dbDir = dbDir + "/"
> ```

`s/"/"/string(os.PathSeparator)/g` (I think that works)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41763)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/file_registry.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk38bv6b3K9Z0GnRhy:-LroYmQZAXMqg-TmsNGQ:b-c8jqwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L105)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`Try` or `Maybe` feel like a better fit here. I'd go with `Maybe`, but my preference there is weak.
</blockquote></details>

Changed to `Maybe`.
___
*[pkg/storage/engine/file_registry.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk3z439YJ2fOniK-iy:-LroYtIZBFG70QsggI4c:be3q4ad) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L147)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does any of our usage actually result in `../` paths? I believe `filename` is always underneath `dbDir`.
</blockquote></details>

I wasn't able to determine for sure based on looking at the rocksdb code. I've added a TODO here -- is that ok for now?
___
*[pkg/storage/engine/pebble_file_registry.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-LroNcOZ50NjfLdcVqKE:-Lro_7XR2Dz3StdfGsOw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20aad8f294d55e69eb36d02b9c65a615a8067233/pkg/storage/engine/pebble_file_registry.go#L174)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/'/'/os.PathSeparator/g`
</blockquote></details>

Done.
___
*[pkg/storage/engine/pebble_file_registry.go, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-LroNggF1ufiHJ2NvROl:-Lro_88I9O0gyZsPrDkx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20aad8f294d55e69eb36d02b9c65a615a8067233/pkg/storage/engine/pebble_file_registry.go#L175)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/"/"/string(os.PathSeparator)/g` (I think that works)
</blockquote></details>

Done.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41763)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/file_registry.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41763#-Lrk3z439YJ2fOniK-iy:-Lroa_d59gigS2fu3qWA:b9tn7vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b13aceb9eff5e23d678fc432662675a7593a55/pkg/storage/engine/file_registry.go#L147)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I wasn't able to determine for sure based on looking at the rocksdb code. I've added a TODO here -- is that ok for now?
</blockquote></details>

Yep. That's fine.

**Pull request merged**
