### PR TITLE
distsqlrun: make the sorter return trace data on error 

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24373#-:-L8sjoQ9-0ccloTRDyje:bnfp4nl)*

**Comment by andreimatei** [comment]
Turns out that many other processors have the some problem. I'll fix them all; I think I'll move some logic about the buffering and consumption of trailing metadata to `processorBase`. So I cleaned it up a little in sorter first here. Radu, please take another look.

I started looking around this code towards fixing #24304. For that, I need to make `ProcOutputHelper.ProcessRow()` able to return both a row and a signal that no more rows are needed at the same time. Upon seeing that signal, a processor should queue up all the trailing meta, but return the row for the current `Next()` call. So what used to be `producerMeta()` and in this PR becomes `closeAndQueueTrailingMeta()/consumerTrailingMeta()` will get even more modular, offering all options: `closeAndQueueMeta()/consumeMeta()/closeAndQueueAndConsumeOne()`.

cc @petermattis 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24373#-:-L8tESYACdcOS-BIeVKr:bz4zvio)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/sorter.go, line 138 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24373#-L8tNPRT7qBJAzclW0Pl:-L95Zk6K4gQTXtcJrMRc:b-ecwjxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a3983aa19c05290122d4dbbbc40d411875990e8/pkg/sql/distsqlrun/sorter.go#L138)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm pretty sure we've already allocated `sorterBase` at this point, so might as well embed it by pointer everywhere.
</blockquote></details>

Or replace `newSorterBase` with an `init` function

---

*[pkg/sql/distsqlrun/sorter.go, line 104 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24373#-L95aUj39Drf8oRhS_DE:-L95aUj39Drf8oRhS_DF:b8ygv61) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c299f4868a015ad645e76a2aa2166286651b458/pkg/sql/distsqlrun/sorter.go#L104)):*
> ```Go
> 
> // consumeTrailingMeta peels off one piece of trailing metadata.
> func (s *sorterBase) consumeTrailingMeta() *ProducerMetadata {
> ```

[nit] "consume" implies we finish it all. maybe `popTrailingMeta`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24373#-:-L95aBav9uDeouF1z3tw:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsqlrun/sorter.go, line 138 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24373#-L8tNPRT7qBJAzclW0Pl:-L95kN5f6RKpq5A9OE-G:b-k7jotu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a3983aa19c05290122d4dbbbc40d411875990e8/pkg/sql/distsqlrun/sorter.go#L138)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Or replace `newSorterBase` with an `init` function
</blockquote></details>

I've moved to an init func and moved the call to the sorters' ctors. I've also prepended another commit cleaning some other initialization up so that stars align.

---

*[pkg/sql/distsqlrun/sorter.go, line 96 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24373#-L8tQt5M3pMvlBg1dO_F:-L970rem5LYpbs9N4XZd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c299f4868a015ad645e76a2aa2166286651b458/pkg/sql/distsqlrun/sorter.go#L96)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I would naturally expect the error to be sent first. If there is a reason it is being sent after the trace data then that needs to be detailed in a comment so that someone doesn't accidentally "fix" this in the future.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/sorter.go, line 104 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24373#-L95aUj39Drf8oRhS_DE:-L971-er54M9EVowd8oh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c299f4868a015ad645e76a2aa2166286651b458/pkg/sql/distsqlrun/sorter.go#L104)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "consume" implies we finish it all. maybe `popTrailingMeta`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24373)*

**Comment by andreimatei** [comment]
Merging this because the first commits help me do further refactorings.
I'll have a followup that tries to standardize the processors more and fix the same problem that the sorters had everywhere.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24373#-:-L9CCQTT3N6MiDaWlb4G:b-3m4shn)*

**Pull request merged**
