### PR TITLE
sqlbase: split ranges on materialized views

### PR DESCRIPTION
**Pull request by rohany**
Ensure that we split ranges on materialied views like normal tables.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
I tried to write a logictest for this, but the range splits wouldn't show up (though they did in `demo`).

**Review by nvb — APPROVED** [review]
> I tried to write a logictest for this

You should be able to add a test case to `TestShouldSplitAtDesc`.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52902#-:-MEx-Hy_7ZwsP61ttmKp:b-u1zb5m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/sqlbase/system.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52902#-MEx-X7D6owOEhts2BMH:-MEx-X7D6owOEhts2BMI:b1w4j1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1c19fbfd516480e9111ce445ca3e1aaa023e0d8/pkg/sql/sqlbase/system.go#L37)):*
> ```Go
> 	switch t := desc.GetUnion().(type) {
> 	case *descpb.Descriptor_Table:
> 		if t.Table.IsView() && !t.Table.IsMaterializedView {
> ```

Should this use the `MaterializedView()` method?

**Comment by rohany** [comment]
> You should be able to add a test case to TestShouldSplitAtDesc.

Done

> Should this use the MaterializedView() method?

Yup, fixed. I thought that I had implemented that on one of the wrapper structs, not the base descriptor.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52902#-:-MEx2w6J8EOGV5wzTD4n:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by rohany** [comment]
tfw version-upgrade passes on the 15th run

bors r+

**Pull request merged**
