### PR TITLE
kv: collect and propogate all transaction state in DistSender on error

### PR DESCRIPTION
**Pull request by nvb**
Fixes “Bug 2” from https://github.com/cockroachdb/cockroach/issues/36089#issuecomment-499349410.

This commit fixes the bug described in the referenced issue where part of a transaction proto update was lost when combining partial batches with some successes and some failures. This was leading to a state where a transaction restarted with a read timestamp below its maximum write timestamp from the previous epoch.

Fixing this bug resolves the current issue in #36089.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
I'm a bit out of it at the moment so you'll want someone else to also review, but LGTM

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38115#-:-Lgtu9H15eFWNUrgFtFS:b1zf9p6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/roachpb/errors.proto, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38115#-LgttU3f4qBhrnYxTVHi:-LgttU3f4qBhrnYxTVHj:b-fsxq4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9582afc84edeffc4083d3d762fa864514ed6ae4f/pkg/roachpb/errors.proto#L430)):*
> ```protobuf
>   option (gogoproto.equal) = true;
> 
>   reserved 1;
> ```

Based on your argument, you don't need to reserve this, right? Hedging your bet for the case in which someone winds up sending these errors across the network after all?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/roachpb/errors.proto, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38115#-LgttU3f4qBhrnYxTVHi:-LgxqKKP87jUNna3W0uJ:b-l7hepk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9582afc84edeffc4083d3d762fa864514ed6ae4f/pkg/roachpb/errors.proto#L430)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Based on your argument, you don't need to reserve this, right? Hedging your bet for the case in which someone winds up sending these errors across the network after all?
</blockquote></details>

Actually hedging my bet against a case where a reviewer notices that I reused a protobuf field number and calls me out for it :trollface:

**Comment by nvanbenschoten** [comment]
@andreimatei any interest in taking a look at this? No need to if not.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38115#-:-LhfBVv6267R6ZQUjrs1:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/roachpb/errors.go, line 700 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38115#-LhfAi7vADWA0mKbPmcN:-LhfAi7vADWA0mKbPmcO:b-pupmoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9582afc84edeffc4083d3d762fa864514ed6ae4f/pkg/roachpb/errors.go#L700)):*
> ```Go
> 		// If the detail was not an ErrorDetail, store
> 		// it in the unstructured Message field.
> 		m.WrappedMessage = detail.Error()
> ```

how about turning `detail` into an `internalError` and putting that in `m.wrapped` and getting rid of `m.WrappedMessage`?
___
*[pkg/roachpb/errors.proto, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38115#-LgttU3f4qBhrnYxTVHi:-Lhf8fI63vcacukayf_G:b2eoilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9582afc84edeffc4083d3d762fa864514ed6ae4f/pkg/roachpb/errors.proto#L430)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Actually hedging my bet against a case where a reviewer notices that I reused a protobuf field number and calls me out for it :trollface: 
</blockquote></details>

now that the hedge worked, I'd get rid of the reserved noise :)
___
*[pkg/roachpb/errors.proto, line 431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38115#-Lhf8biL2hoLxfLm9tXH:-Lhf8biL2hoLxfLm9tXI:b7zcy4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9582afc84edeffc4083d3d762fa864514ed6ae4f/pkg/roachpb/errors.proto#L431)):*
> ```protobuf
> 
>   reserved 1;
>   optional ErrorDetail wrapped = 2 [(gogoproto.nullable) = false];
> ```

can you explain when wrapped is set and when the msg is set?

**Comment by knz** [comment]
Andrei asked me to share what I just merged into `master`:

- add an `optional errorspb.EncodedError full_error = ...;` in the protobuf def for roachpb.Error, alongside error_detail

- populate both on send

- read the error from `full_error` (`FullError`) if available, otherwise fall back to detail.

**Comment by knz** [comment]
(I did this for distsql, see `sql/distsqlpb/data.go` `NewError()` / `ErrorDetail()`

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/roachpb/errors.go, line 700 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38115#-LhfAi7vADWA0mKbPmcN:-LiF6p7f-LwD4H1BHjkb:bej1so8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9582afc84edeffc4083d3d762fa864514ed6ae4f/pkg/roachpb/errors.go#L700)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how about turning `detail` into an `internalError` and putting that in `m.wrapped` and getting rid of `m.WrappedMessage`?
</blockquote></details>

That seems like the opposite of what I want because `internalError` is a `roachpb.Error` and is treated as one in `Error.SetDetail`. That would break code like `pErr.SetDetail(mse.GetWrapped())`.
___
*[pkg/roachpb/errors.proto, line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38115#-LgttU3f4qBhrnYxTVHi:-LiF79AY6LZAQbWUZDLc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9582afc84edeffc4083d3d762fa864514ed6ae4f/pkg/roachpb/errors.proto#L430)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

now that the hedge worked, I'd get rid of the reserved noise :)
</blockquote></details>

Done.
___
*[pkg/roachpb/errors.proto, line 431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38115#-Lhf8biL2hoLxfLm9tXH:-LiF7OvQEd9iZWpqe64h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9582afc84edeffc4083d3d762fa864514ed6ae4f/pkg/roachpb/errors.proto#L431)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you explain when wrapped is set and when the msg is set?
</blockquote></details>

Done.

**Pull request merged**
