### PR TITLE
server: try re-enable TestAdminDecommissionedOperations

### PR DESCRIPTION
**Pull request by knz**
The test is flaky; sadly, the error does not reproduce locally and the precise cause of the flakiness is obscured by #100796.

This commit re-enables the test with the fix for #100796, so that the next CI failure can reveal more details about what went wrong.

Release note: None
Epic: None

Informs #100791 and #100789.

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/server/admin_test.go` line 3179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100993#-NSVqVWs7ZUBQxGDwGzK:-NSVgs8y3_tt4gNutAQU:b-ogat0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cbd40ca0ad4311969482d86e18c0e5f20f0862a/pkg/server/admin_test.go#L3179)):*
> ```Go
> 				s, ok := status.FromError(errors.UnwrapAll(err))
> 				if s == nil || !ok {
> 					return err
> ```

I'm confused about this clause. It seems like `s == nil` reflects a nil error state while `!ok` reflects a non-nil error.

If `s == nil` and we return `err` then won't that be nil as well? In the previous implementation we always return false.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/server/admin_test.go` line 3179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100993#-NSVqVWs7ZUBQxGDwGzK:-NSeXb1j4wInLQJqkzYg:b-d19zwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cbd40ca0ad4311969482d86e18c0e5f20f0862a/pkg/server/admin_test.go#L3179)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I'm confused about this clause. It seems like `s == nil` reflects a nil error state while `!ok` reflects a non-nil error.

If `s == nil` and we return `err` then won't that be nil as well? In the previous implementation we always return false.
</blockquote></details>

I added more code to clarify. PTAL

**Review by abarganier — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100993#-:-NSffPnk7AlezcXYNNOO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/server/admin_test.go` line 3179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100993#-NSVqVWs7ZUBQxGDwGzK:-NSffIPn8V5SgaH3Ovpy:byxig54) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cbd40ca0ad4311969482d86e18c0e5f20f0862a/pkg/server/admin_test.go#L3179)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I added more code to clarify. PTAL
</blockquote></details>

I understood David's concerns with the previous patch. This clarification LGTM, thanks!

**Comment by knz** [comment]
bors r=abarganier

**Pull request merged**
