### PR TITLE
demo: add --multitenant flag

### PR DESCRIPTION
**Pull request by jordanlewis**
Add a new flag, --multitenant, to cockroach demo. The --multitenant flag
spins up one SQL tenant per node in the cluster, assigning the nth
tenant to the nth demo node.

When running with --multitenant, the demo is automatically connected to
the first tenant, instead of the system tenant.

The system tenant, or any of the other tenants, can be connected to via
/connect.

Release note (cli change): allow demoing of CockroachDB's multitenant
features via the --multitenant flag to cockroach demo.

### CODE REVIEW

**Comment by jordanlewis** [comment]
New UX with `--multitenant --nodes=3`:

```
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB cluster of 3 nodes.
#
# You are connected to tenant 1, but can connect to the system tenant with
# /connect and the SQL url below.
#
# This demo session will attempt to enable enterprise features
# by acquiring a temporary license from Cockroach Labs in the background.
# To disable this behavior, set the environment variable
# COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true.
#
# Reminder: your changes to data stored in the demo session will not be saved!
#
# If you wish to access this demo cluster using another tool, you will need
# the following details:
#
#   - Connection parameters:
#   system tenant
#     (webui)    http://127.0.0.1:8080/demologin?password=demo1555&username=demo
#     (sql)      postgresql://demo:demo1555@127.0.0.1:26257/defaultdb?sslmode=require
#     (sql/jdbc) jdbc:postgresql://127.0.0.1:26257/defaultdb?password=demo1555&sslmode=require&user=demo
#     (sql/unix) postgresql://demo:demo1555@/defaultdb?host=%2Ftmp%2Fdemo676223934&port=26257
#
#   tenant 1:
#     (sql) postgresql://demo:demo1555@127.0.0.1:37745/defaultdb?sslmode=require
#
#   tenant 2:
#     (sql) postgresql://demo:demo1555@127.0.0.1:33143/defaultdb?sslmode=require
#
#   tenant 3:
#     (sql) postgresql://demo:demo1555@127.0.0.1:42805/defaultdb?sslmode=require
#
#   To display connection parameters for other nodes, use \demo ls.
#   - Username: "demo", password: "demo1555"
#   - Directory with certificate files (for certain SQL drivers/tools): /tmp/demo676223934
#
# Server version: CockroachDB CCL v21.2.0-alpha.00000000-4664-g13dd71b2ff-dirty (x86_64-linux-gnu, built , go1.16.5) (same version as client)
# Cluster ID: c346763b-ad2f-41ee-8593-3bbb96e8c5f7
#
# Enter \? for a brief introduction.
#
demo@127.0.0.1:37745/defaultdb>
```

**Review by knz — APPROVED** [review]
:clap: :clap: :clap: 
Maybe replace `/connect` to `\connect` in the PR description & commit message.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-:-Ml0yN9Z0hOrYUrop6qQ:b93dlh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @stevendanna)

___
*[pkg/cli/demo.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0yIAu2eA26bK0mvHi:-Ml0yIAu2eA26bK0mvHj:bwdcq6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/demo.go#L256)):*
> ```Go
> 			cliCtx.PrintfUnlessEmbedded(`#
> # You are connected to tenant 1, but can connect to the system tenant with
> # /connect and the SQL url below.
> ```

I think you mean `\c` here?
___
*[pkg/cli/clierror/check.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0x_vY5QjMCNsFDIq1:-Ml0x_vZ-pXOMWlmvQby:b-vqgtr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/clierror/check.go#L36)):*
> ```Go
> 		cause = ec.Unwrap()
> 	}
> 	debug.PrintStack()
> ```

nit: remove this
___
*[pkg/cli/democluster/demo_cluster.go, line 1380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0xqsjBXh-sLJad7gy:-Ml0xqsk1_1RbCHMGdbe:b-kk2n65) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/democluster/demo_cluster.go#L1380)):*
> ```Go
> 	if c.demoCtx.Multitenant {
> 		for i := range c.servers {
> 			fmt.Fprintf(w, "tenant %d:\n", i+1)
> ```

UX nit: maybe make the tenant number part of the label on the left o the URL, to make the output more compact.
___
*[pkg/cli/democluster/demo_cluster_test.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0xylaBFTQTCf9ZmsX:-Ml0xylaBFTQTCf9ZmsY:b-664x4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/democluster/demo_cluster_test.go#L210)):*
> ```Go
> 	} {
> 		t.Run(tc.desc, func(t *testing.T) {
> 			url, err := c.getNetworkURLForServer(ctx, tc.nodeIdx, true, false)
> ```

I think it's useful to keep the comments that indicate which parameter each boolean value corresponds to.
___
*[pkg/sql/set_cluster_setting.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0yEnY3JN0wUJ3FhIa:-Ml0yEnY3JN0wUJ3FhIb:bta8xu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/sql/set_cluster_setting.go#L289)):*
> ```Go
> 			}
> 
> 			if knobs := params.p.execCfg.TenantTestingKnobs; knobs != nil && knobs.ClusterSettingsUpdater != nil {
> ```

can you explain (to me) why this change was needed?

**Comment by knz** [comment]
This would also benefit from some testing.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml9mN_S1llSJbUe_QRi:-Ml9mN_S1llSJbUe_QRj:beds585) (no related file):*
This will be useful thanks!  Also, the new testing knob on the tenants is a nice alternative to the heavy hammer of log.ClearServerIdentities().

---
___
*[pkg/cli/democluster/demo_cluster.go, line 382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml9lnYD3k1S99Xgp-5U:-Ml9lnYD3k1S99Xgp-5V:b-7op215) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/democluster/demo_cluster.go#L382)):*
> ```Go
> 			c.tenantServers[i] = ts
> 			if err != nil {
> 				c.warnLog(phaseCtx, "failed starting tenant %d", i, err)
> ```

It doesn't matter much. and I'm not sure what the best alternative is, but here we log the array index, in the help output we print to the terminal we use idx+1, and then the actual tenant IDs are idx+2.
___
*[pkg/cli/democluster/demo_cluster.go, line 1020 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml9jXhD5lUuzMg9o5Os:-Ml9jXhD5lUuzMg9o5Ot:b-1era64) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/democluster/demo_cluster.go#L1020)):*
> ```Go
> 			tenantCAKeyPath,
> 			demoCtx.DefaultKeySize,
> 			demoCtx.DefaultCertLifetime+time.Hour,
> ```

A small comment here on why we've gone with `DefaultCertLifetime+time.Hour` (as opposed to  `DefaultCALifetime`) might be useful.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @stevendanna)

___
*[pkg/cli/demo.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0yIAu2eA26bK0mvHi:-MlVqlMq1vLh3RgCRtk3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/demo.go#L256)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you mean `\c` here?
</blockquote></details>

Done.
___
*[pkg/cli/clierror/check.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0x_vY5QjMCNsFDIq1:-MlVqoVg0J6I-XLvIFOl:bohi7pv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/clierror/check.go#L36)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: remove this
</blockquote></details>

Oops, thanks, done.
___
*[pkg/cli/democluster/demo_cluster.go, line 382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml9lnYD3k1S99Xgp-5U:-MlVqsZ-6Ypx5rsxMlBG:bv361sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/democluster/demo_cluster.go#L382)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

It doesn't matter much. and I'm not sure what the best alternative is, but here we log the array index, in the help output we print to the terminal we use idx+1, and then the actual tenant IDs are idx+2.
</blockquote></details>

Bleh, yeah... I have no idea what to do about this but I think I'll just ignore it for now. The log messages are internal and people will have to check the code to figure what is going on with this I think.
___
*[pkg/cli/democluster/demo_cluster.go, line 1020 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml9jXhD5lUuzMg9o5Os:-MlVr2J37tx-VkmB4ZdK:b-dzwcl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/democluster/demo_cluster.go#L1020)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

A small comment here on why we've gone with `DefaultCertLifetime+time.Hour` (as opposed to  `DefaultCALifetime`) might be useful.
</blockquote></details>

Done. To be honest, I don't know why this had to be done, but without it, there were spurious errors.
___
*[pkg/cli/democluster/demo_cluster.go, line 1380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0xqsjBXh-sLJad7gy:-MlVrMneBjU8ga3Uqnzz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/democluster/demo_cluster.go#L1380)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

UX nit: maybe make the tenant number part of the label on the left o the URL, to make the output more compact.
</blockquote></details>

Done.
___
*[pkg/cli/democluster/demo_cluster_test.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0xylaBFTQTCf9ZmsX:-MlVubsX6zDCV2DMqPyB:b6b1a8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/democluster/demo_cluster_test.go#L210)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think it's useful to keep the comments that indicate which parameter each boolean value corresponds to.
</blockquote></details>

Done, they were deleted with an automated refactor by accident, thanks for noticing.
___
*[pkg/sql/set_cluster_setting.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0yEnY3JN0wUJ3FhIa:-MlVv4Nw3ZWiwiDVL9tH:b-k2zhks) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/sql/set_cluster_setting.go#L289)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

can you explain (to me) why this change was needed?
</blockquote></details>

Previously, the only tenant testing knob was this cluster settings updater one, so it was apparent that if the knobs were non-nil then the cluster settings updater would be non-nil. Now, we set testing knobs for other reasons, so both have to be checked.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml9mN_S1llSJbUe_QRi:-MlWRTHj00qhf-mxKF3G:b-w0hkgw) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

This will be useful thanks!  Also, the new testing knob on the tenants is a nice alternative to the heavy hammer of log.ClearServerIdentities().
</blockquote></details>

I added a very basic unit test for the functionality, and a basic CLI TCL test that ensures that the demo can start up in multitenant mode.

I think this is good to go.

@dt makes a good point - we probably want to, over time, make this --multitenant flag both on by default and also only include a single non-system tenant, so that we can have all of this code not use any CCL features at all. But, I'd like to merge as-is so that we can at least get in the building blocks for what we'll eventually need here.

---
___
*[pkg/cli/democluster/demo_cluster.go, line 1380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml0xqsjBXh-sLJad7gy:-MlWRNLw35WWzU8hjEL_:bhnl4qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c32e7fce0b74a036c0789c44191dd4d961d0c67/pkg/cli/democluster/demo_cluster.go#L1380)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I actually left this as-is, I think it's a bit arbitrary and I have support from @dt on this layout... we can always change it.

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @knz, @srosenberg, and @stevendanna)

___
*[pkg/cli/democluster/demo_cluster.go, line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-MlrPyMp7d3XqZvbasUd:-MlrPyMp7d3XqZvbasUe:bvu7c06) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5605b65e5f28c794725a00eb55433314cb89e3/pkg/cli/democluster/demo_cluster.go#L380)):*
> ```Go
> 				},
> 			})
> 			c.tenantServers[i] = ts
> ```

Nit: generally we can't make any assumption about the state of result values in case of error.

**Comment by knz** [comment]
> What are your thoughts on making multitenant the default for cockroach demo?

I'd be in favor in the `master` branch, so as to stimulate exposure of our team internally.
We could then turn it back `off` in the 22.1 branch if we discover in the next few months that it's too hard to bridge the feature gap.

**Review by ajstorm — COMMENTED** [review]
just had a look and a strong :tada: from me!  Thanks for knocking this one out Jordan.  A few nits below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-:-MmU3aTbBgoQ97qaE5lG:bv0gev6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, @jordanlewis, @knz, @srosenberg, and @stevendanna)

___
*[pkg/cli/cliflags/flags.go, line 1214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-MmU-LIQ9uG_TeNfk6C_:-MmU-LIQ9uG_TeNfk6Ca:b-cobxk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5605b65e5f28c794725a00eb55433314cb89e3/pkg/cli/cliflags/flags.go#L1214)):*
> ```Go
> If set, cockroach demo will start separate in-memory KV and SQL servers in multi-tenancy mode.
> The SQL shell will be connected to the first tenant, and can be switched between tenants
> and the system tenant.`,
> ```

Nit: Does it makes sense to say "...and can be switched between the tenants and the system tenant using the \connect command"?  I know it makes the message longer, but seeing as how it's already pretty long, this might be a helpful addition.
___
*[pkg/cli/democluster/demo_cluster.go, line 212 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-MmU0D3uCYLz-MAYIqqf:-MmU0D3uCYLz-MAYIqqg:bxbfsb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5605b65e5f28c794725a00eb55433314cb89e3/pkg/cli/democluster/demo_cluster.go#L212)):*
> ```Go
> 	//    This ensures the node IDs are assigned sequentially.
> 	// 7. wait for the SQL readiness from all nodes.
> 	// 8. Start multitenant SQL servers.
> ```

Nit: Should this say "...if running in multi-tenant mode"?  Also, super-nitty, but should we be using multi-tenant instead of multitenant throughout (with the exception of the actual flag)?
___
*[pkg/cli/democluster/demo_cluster.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-MmU13pb61LggYL3qKGB:-MmU13pb61LggYL3qKGC:btd0qe3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5605b65e5f28c794725a00eb55433314cb89e3/pkg/cli/democluster/demo_cluster.go#L372)):*
> ```Go
> 			c.infoLog(phaseCtx, "starting tenant node %d", i)
> 			ts, err := c.servers[i].StartTenant(ctx, base.TestTenantArgs{
> 				TenantID:      roachpb.MakeTenantID(uint64(i + 2)),
> ```

Does this "+ 2" warrant a comment?
___
*[pkg/cli/democluster/demo_cluster_test.go, line 259 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-MmU2SsgBjQtqfE_TqTl:-MmU2SsgBjQtqfE_TqTm:b-d9eytx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5605b65e5f28c794725a00eb55433314cb89e3/pkg/cli/democluster/demo_cluster_test.go#L259)):*
> ```Go
> 	// This is slow under race as it starts a 9-node cluster which
> 	// has a very high simulated latency between each node.
> 	skip.UnderRace(t)
> ```

I'm wondering if we can remove this?  We're only starting up a 3 node cluster here, so maybe it'll pass under race.  If nothing else, we should remove the comment above, as it's incorrect.
___
*[pkg/cli/interactive_tests/test_demo_multitenant.tcl, line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-MmU32id7RVXtxIwsaWO:-MmU32id7RVXtxIwsaWP:bfx28kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5605b65e5f28c794725a00eb55433314cb89e3/pkg/cli/interactive_tests/test_demo_multitenant.tcl#L18)):*
> ```Tcl
> # generated URL strings, and we also have unit tests exercising that
> # functionality, so for now this is just a smoke test that ensures that
> # the mt demo can at least start up.
> ```

Does this warrant a TODO?  Or are we not doing those anymore?

**Review by ajstorm — COMMENTED** [review]
I'd also be in favour of turning this on by default, but am thinking we should get this PR in first as I'd have to imagine a whole bunch of tests will fail when we make it the default (or maybe not :crossed_fingers: ).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-:-MmU3mFr9vQ1BOdzcDai:b8rbe4e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @knz, @srosenberg, and @stevendanna)

**Review by srosenberg — APPROVED** [review]
> Reviewed 7 of 12 files at r1, 4 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @knz, and @stevendanna)

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, @knz, @srosenberg, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-Ml9mN_S1llSJbUe_QRi:-MmdjDN57-Hzqqawr3BG:byleir8) (no related file):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I added a very basic unit test for the functionality, and a basic CLI TCL test that ensures that the demo can start up in multitenant mode.

I think this is good to go.

@dt makes a good point - we probably want to, over time, make this --multitenant flag both on by default and also only include a single non-system tenant, so that we can have all of this code not use any CCL features at all. But, I'd like to merge as-is so that we can at least get in the building blocks for what we'll eventually need here.
</blockquote></details>

TFTR! Will try to merge this. I think there were some test failures that I've got track down.

---
___
*[pkg/cli/democluster/demo_cluster.go, line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-MlrPyMp7d3XqZvbasUd:-Mmdfumz-SVyi_5RXxTv:beu4u9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5605b65e5f28c794725a00eb55433314cb89e3/pkg/cli/democluster/demo_cluster.go#L380)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: generally we can't make any assumption about the state of result values in case of error.
</blockquote></details>

Good point, Done.
___
*[pkg/cli/democluster/demo_cluster_test.go, line 259 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-MmU2SsgBjQtqfE_TqTl:-MmdhtCe3ts2oA0eudF5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5605b65e5f28c794725a00eb55433314cb89e3/pkg/cli/democluster/demo_cluster_test.go#L259)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I'm wondering if we can remove this?  We're only starting up a 3 node cluster here, so maybe it'll pass under race.  If nothing else, we should remove the comment above, as it's incorrect.
</blockquote></details>

Done.
___
*[pkg/cli/interactive_tests/test_demo_multitenant.tcl, line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71026#-MmU32id7RVXtxIwsaWO:-MmdhxL4A6UgbH8HKIFY:berp1gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5605b65e5f28c794725a00eb55433314cb89e3/pkg/cli/interactive_tests/test_demo_multitenant.tcl#L18)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Does this warrant a TODO?  Or are we not doing those anymore?
</blockquote></details>

Haha, I think we're still doing TODO's... I'm not sure if I'm ever going to come back to this though :grimacing:

**Review by srosenberg — APPROVED** [review]
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, @knz, @srosenberg, and @stevendanna)

**Review by ajstorm — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, @srosenberg, and @stevendanna)

**Pull request merged**
