### PR TITLE
storage: fix TestRangeInfo flake and re-enable follower reads by default

### LINKED ISSUE #35758: teamcity: failed test: TestRangeInfo
The following tests appear to have failed on master (test): TestRangeInfo

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestRangeInfo).

[#1178308](https://teamcity.cockroachdb.com/viewLog.html?buildId=1178308):

```
TestRangeInfo
...:38.655236 524597 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190314 20:14:38.655284 524597 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
I190314 20:14:38.655324 524596 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190314 20:14:38.655353 524596 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_gc_batcher
W190314 20:14:38.656782 524063 storage/raft_transport.go:281  unable to accept Raft message from (n2,s2):2: no handler registered for (n1,s1):1
    client_replica_test.go:1619: on scan reply, expected [{Desc:r1:{/Min-a} [(n1,s1):1, (n2,s2):2, next=3, gen=1] Lease:repl=(n2,s2):2 seq=2 start=0.000000123,258 exp=0.900000123,258 pro=0.000000123,259 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0} {Desc:r2:{a-/Max} [(n1,s1):1, (n2,s2):2, next=3, gen=0] Lease:repl=(n1,s1):1 seq=1 start=0.000000000,0 exp=0.900000123,4 pro=0.000000123,5 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0}]; got [{Desc:r1:{/Min-a} [(n1,s1):1, (n2,s2):2, next=3, gen=1] Lease:repl=(n2,s2):2 seq=2 start=0.000000123,258 exp=0.900000123,258 pro=0.000000123,259 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0} {Desc:r2:{a-/Max} [(n1,s1):1, (n2,s2):2, next=3, gen=0] Lease:repl=(n2,s2):2 seq=2 start=0.000000123,275 epo=1 pro=0.000000123,276 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0}]
------- Stdout: -------
I190314 20:31:51.636370 253710 gossip/gossip.go:392  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:45733" > attrs:<> locality:<> ServerVersion:<major_val:0 minor_val:0 patch:0 unstable:0 > build_tag:"" started_at:0 
W190314 20:31:51.676015 253710 gossip/gossip.go:1496  [n2] no incoming or outgoing connections
I190314 20:31:51.677126 253710 gossip/gossip.go:392  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:35387" > attrs:<> locality:<> ServerVersion:<major_val:0 minor_val:0 patch:0 unstable:0 > build_tag:"" started_at:0 
I190314 20:31:51.678556 253864 gossip/client.go:128  [n2] started gossip client to 127.0.0.1:45733
I190314 20:31:51.701842 253710 storage/store_snapshot.go:775  [s1,r1/1:/M{in-ax}] sending preemptive snapshot 319136ab at applied index 15
I190314 20:31:51.703304 253710 storage/store_snapshot.go:818  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 52, log entries: 5, rate-limit: 8.0 MiB/sec, 0.00s
I190314 20:31:51.705904 253852 storage/replica_raftstorage.go:814  [s2,r1/?:{-}] applying preemptive snapshot at index 15 (id=319136ab, encoded size=8705, 1 rocksdb batches, 5 log entries)
I190314 20:31:51.708342 253852 storage/replica_raftstorage.go:820  [s2,r1/?:/M{in-ax}] applied preemptive snapshot in 2ms [clear=0ms batch=0ms entries=1ms commit=0ms]
I190314 20:31:51.712891 253710 storage/replica_command.go:788  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r1:/M{in-ax} [(n1,s1):1, next=2, gen=0]
I190314 20:31:51.722773 253710 storage/replica_raft.go:372  [s1,r1/1:/M{in-ax},txn=8b246eae] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I190314 20:31:51.889486 253710 storage/replica_command.go:246  [s1,r1/1:/M{in-ax}] initiating a split of this range at key "a" [r2] (manual)
I190314 20:31:51.989037 254219 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190314 20:31:51.989790 254220 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190314 20:31:51.990272 254219 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_gc_batcher
I190314 20:31:51.990564 254220 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_gc_batcher



TestRangeInfo
--- FAIL: test/TestRangeInfo (0.420s)

------- Stdout: -------
I190314 20:14:38.296681 523097 gossip/gossip.go:392  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:35513" > attrs:<> locality:<> ServerVersion:<major_val:0 minor_val:0 patch:0 unstable:0 > build_tag:"" started_at:0 
W190314 20:14:38.303611 523097 gossip/gossip.go:1496  [n2] no incoming or outgoing connections
I190314 20:14:38.303704 523097 gossip/gossip.go:392  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:37511" > attrs:<> locality:<> ServerVersion:<major_val:0 minor_val:0 patch:0 unstable:0 > build_tag:"" started_at:0 
I190314 20:14:38.303821 523346 gossip/client.go:128  [n2] started gossip client to 127.0.0.1:35513
I190314 20:14:38.357833 523097 storage/store_snapshot.go:775  [s1,r1/1:/M{in-ax}] sending preemptive snapshot fc10539a at applied index 15
I190314 20:14:38.358080 523097 storage/store_snapshot.go:818  [s1,r1/1:/M{in-ax}] streamed snapshot to (n2,s2):?: kv pairs: 52, log entries: 5, rate-limit: 8.0 MiB/sec, 0.00s
I190314 20:14:38.358488 523521 storage/replica_raftstorage.go:814  [s2,r1/?:{-}] applying preemptive snapshot at index 15 (id=fc10539a, encoded size=8703, 1 rocksdb batches, 5 log entries)
I190314 20:14:38.358899 523521 storage/replica_raftstorage.go:820  [s2,r1/?:/M{in-ax}] applied preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I190314 20:14:38.359332 523097 storage/replica_command.go:788  [s1,r1/1:/M{in-ax}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r1:/M{in-ax} [(n1,s1):1, next=2, gen=0]
I190314 20:14:38.362879 523097 storage/replica_raft.go:372  [s1,r1/1:/M{in-ax},txn=d0115ce8] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3
I190314 20:14:38.643317 523097 storage/replica_command.go:246  [s1,r1/1:/M{in-ax}] initiating a split of this range at key "a" [r2] (manual)
I190314 20:14:38.655236 524597 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190314 20:14:38.655284 524597 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
I190314 20:14:38.655324 524596 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190314 20:14:38.655353 524596 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_gc_batcher
W190314 20:14:38.656782 524063 storage/raft_transport.go:281  unable to accept Raft message from (n2,s2):2: no handler registered for (n1,s1):1
    client_replica_test.go:1619: on scan reply, expected [{Desc:r1:{/Min-a} [(n1,s1):1, (n2,s2):2, next=3, gen=1] Lease:repl=(n2,s2):2 seq=2 start=0.000000123,258 exp=0.900000123,258 pro=0.000000123,259 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0} {Desc:r2:{a-/Max} [(n1,s1):1, (n2,s2):2, next=3, gen=0] Lease:repl=(n1,s1):1 seq=1 start=0.000000000,0 exp=0.900000123,4 pro=0.000000123,5 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0}]; got [{Desc:r1:{/Min-a} [(n1,s1):1, (n2,s2):2, next=3, gen=1] Lease:repl=(n2,s2):2 seq=2 start=0.000000123,258 exp=0.900000123,258 pro=0.000000123,259 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0} {Desc:r2:{a-/Max} [(n1,s1):1, (n2,s2):2, next=3, gen=0] Lease:repl=(n2,s2):2 seq=2 start=0.000000123,275 epo=1 pro=0.000000123,276 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0}]




```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by ajwerner**
This PR addresses a test flake introduced by enabling follower reads in
conjunction with #35130 which makes follower reads more generally possible
in the face of lease transfer.

Fixes #35758.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35793)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/client_replica_test.go, line 1606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35793#-La2CNza1dB2CzfEgMiR:-La2CNza1dB2CzfEgMiS:bzagedi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4b081d307a3bc9fc1e29b4448cfe071b8452741/pkg/storage/client_replica_test.go#L1606)):*
> ```Go
> 		t.Fatal(pErr)
> 	}
> 	lhsLease, _ = lhsReplica1.GetLease()
> ```

Would an alternative be to change these to `lhsReplica0.GetLease()` and `rhsReplica0.GetLease()`?
___
*[pkg/storage/client_replica_test.go, line 1609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35793#-La29hqJ9cCfkPNFlbOw:-La29hqJ9cCfkPNFlbOx:bomha7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d441ad1a8dd74c6c64c591e8da45389b0f5f221f/pkg/storage/client_replica_test.go#L1609)):*
> ```Go
> 	// triggered above. This is to protect against the case where the lease
> 	// transfer is applied on replica0 but not on replica1 at the time of the
> 	// above query. In this scenario replica0 can serve a follower read which
> ```

"which" what?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35793)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/client_replica_test.go, line 1606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35793#-La2CNza1dB2CzfEgMiR:-La6WhVd6aTHFDl84ggc:b60r506) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4b081d307a3bc9fc1e29b4448cfe071b8452741/pkg/storage/client_replica_test.go#L1606)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Would an alternative be to change these to `lhsReplica0.GetLease()` and `rhsReplica0.GetLease()`?
</blockquote></details>

Yes, done.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35793#-:-LaGD3qwBKZhOYMD7UHT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
