### PR TITLE
ui: cluster-ui global style issues

### PR DESCRIPTION
**Pull request by vladlos**
there is an issue with antd library style overlap in consumers
(crdb and managed service). they both have it own antd style
loaded and additional version from cluster ui build can corrupt
some elements. to avoid that we patched antd css to remove
rules that generate this conflicts, but with moving this big
file in local scss tree buld time become too big for ci tools.
proposed solution: import  prebuilt css in main components
directly.

release note(ui): none

### CODE REVIEW

**Comment by nathanstilwell** [comment]
Vlad, I see what you mean by a less than ideal solution (loading compiled css for antd in every view in cluster-ui). I'm afraid I have lost the plot a little about the original issue. Can you describe where style conflict is occuring in Cluster-ui (specifically which components) and which styles are conflicting from AntD? I am tempted to seek a universal solution for AntD style conflicts, but perhaps a bad localized solution is better than a bad global one.

**Comment by koorosh** [comment]
> Can you describe where style conflict is occuring in Cluster-ui (specifically which components) and which styles are conflicting from AntD?

@nathanstilwell, as I understood, the problem with `antd` global styles that are loaded in both CC and cluster-ui.
Console imports one instance of `antd` (with its global styles) and then customizes these global styles. 
Then `cluster-ui` imports its own version of `antd` global styles that "resets" customization of these styles in CC.

**Comment by elkmaster** [comment]
correct, this reset is a cause of all style issues we had while integrating sessions and statements in managed service and CRDB-6956. So there is some specific cases we can patch item by item like we already do, but it still will produce unexpected results in future. I assume such approach as temporary, until we get rid of antd components in favor of design system ones.

**Comment by koorosh** [comment]
@elkmaster , as an alternative for this change:  https://github.com/cockroachdb/cockroach/pull/66029

it excludes only `antd` global styles from `cluster-ui` bundle.

@nathanstilwell , what do you think about such "hacky" approach?

**Pull request closed without merging**
