### PR TITLE
sql: reference sequences used in views by their IDs

### LINKED ISSUE #61205: Rewrite sequence expressions in views
**Describe the problem**
After https://github.com/cockroachdb/cockroach/pull/59864, we're now rewriting DEFAULT expressions to reference sequences via their IDs. This results in the ability for sequences used in default expressions to be renamed. However, we don't perform this rewrite for views that reference sequences. As a result, we still cannot rename sequences used in views.

**To Reproduce**

```
CREATE SEQUENCE s;
CREATE VIEW v AS SELECT nextval('s');
ALTER SEQUENCE s RENAME TO s2;  // ERROR: cannot rename relation "s" because view "v" depends on it
```

**Expected behavior**
We should rewrite sequence expressions in views to also reference sequences by ID. This will allow us to rename sequences that are used in views.

### PR DESCRIPTION
**Pull request by the-ericwang35**
Followup to https://github.com/cockroachdb/cockroach/pull/59864, fixes https://github.com/cockroachdb/cockroach/issues/61205.
Previously, a change was introduced to store sequences
used in DEFAULT expressions to be referenced by their
IDs instead of their names, to allow sequence renaming.
In this patch, we want to do something similar by
rewriting sequence references in views to be
referenced by their IDs. This allows sequences
used in views to be renamed.

Another thing this PR does is change the output of sequences
to look like `'s'::REGCLASS` rather than `'s':::STRING::REGCLASS`,
since we're no longer type checking them (since it's unnecessary).

Release note (sql change): reference sequences used in views
by their IDs to allow these sequences to be renamed.

### CODE REVIEW

**Comment by the-ericwang35** [comment]
This PR isn't ready to be merged, but is probably ready for an initial review. Additional things that need to be done to have this PR ready to be merged include:
- Add more tests to hit all cases where sequences can be used in views
- Thinking about how to walk (or if they even need to be walked) some additional types of statements, such as `StatementSource`, `TableRef`, etc.
- Passing a flag to `WalkStmt` to only perform the newly added walks if the flag specifies it (for example, walking the `FROM` clause)

**Review by ajwerner — COMMENTED** [review]
nice

> Reviewed 6 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-:-MW-UTEt4uA-xi41YD1O:bb7lbs2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/ccl/backupccl/restore_planning.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-S1hF2Hs2RlG5MHmA:-MW-S1hF2Hs2RlG5MHmB:b-cyzpch) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/ccl/backupccl/restore_planning.go#L128)):*
> ```Go
> // rewriteSequencesInExpr rewrites all sequence IDs in the input expression
> // string according to rewrites.
> func rewriteSequencesInExpr(expr string, rewrites DescRewriteMap) (string, error) {
> ```

did you test this for views? Can you write a test that backs up a view and then restores it? I'm worried we're going to have problems here. 
___
*[pkg/sql/create_view.go, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-QV_GABjhK4hK8luS:-MW-QV_HD6GWEzXSSvUG:bpe71tc) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/sql/create_view.go#L357)):*
> ```Go
> }
> 
> // startViewWalk prepares to walk the given viewQuery by defining the
> ```

this name is weird to me. I'd call it what it does, something about re-writing sequences. 
___
*[pkg/sql/create_view.go, line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-Qi889gXhMeHMGPrF:-MW-Qi889gXhMeHMGPrG:by5m0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/sql/create_view.go#L385)):*
> ```Go
> 	stmt, err := parser.ParseOne(viewQuery)
> 	if err != nil {
> 		return "", err
> ```

nit: wrap this error for easier debugging
___
*[pkg/sql/show_create_clauses.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-QwRdEL0dGm-J0H3U:-MW-QwRdEL0dGm-J0H3V:b5kcosa) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/sql/show_create_clauses.go#L112)):*
> ```Go
> 	decodedViewQuery, err := formatViewQueryForDisplay(ctx, semaCtx, desc)
> 	if err != nil {
> 		f.WriteString(desc.GetViewQuery())
> ```

can you log a warning here?
___
*[pkg/sql/catalog/schemaexpr/column.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-RDh05_rUc3v4K1Bk:-MW-RDh05_rUc3v4K1Bl:b-mhgheg) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/sql/catalog/schemaexpr/column.go#L327)):*
> ```Go
> // GetTypeExprAndSeqID takes an expr and looks for a sequence ID in
> // this expr. If it finds one, it will return that ID as well as the
> // Expr that contains it.
> ```

This API is now weird to me. If it returns a non-nil expr it always returns what it was given. How about just strip the expr return value? Also, it doesn't seem like anybody does anything with it anyway.

**Review by the-ericwang35 — COMMENTED** [review]
> Dismissed @ajwerner from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/ccl/backupccl/restore_planning.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-S1hF2Hs2RlG5MHmA:-MW0lddi2tWDp5ImQnQr:bn33rvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/ccl/backupccl/restore_planning.go#L128)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

did you test this for views? Can you write a test that backs up a view and then restores it? I'm worried we're going to have problems here. 
</blockquote></details>

That's a good point, I've added some additional logic to look for descriptor rewrites in the view query, since it can now contain sequence IDs. I've also added a test to backup and restore a view.
___
*[pkg/sql/create_view.go, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-QV_GABjhK4hK8luS:-MW-ics2CLxGTwllioOZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/sql/create_view.go#L357)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this name is weird to me. I'd call it what it does, something about re-writing sequences. 
</blockquote></details>

Done.
___
*[pkg/sql/create_view.go, line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-Qi889gXhMeHMGPrF:-MW-iZY0A7rY5yFycu2N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/sql/create_view.go#L385)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: wrap this error for easier debugging
</blockquote></details>

Done.
___
*[pkg/sql/show_create_clauses.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-QwRdEL0dGm-J0H3U:-MW-hxHa4wKV9SUnMicC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/sql/show_create_clauses.go#L112)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you log a warning here?
</blockquote></details>

Done.
___
*[pkg/sql/catalog/schemaexpr/column.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-RDh05_rUc3v4K1Bk:-MW-jXCT9Q2cuJT1Vvlu:b-8ep21f) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/sql/catalog/schemaexpr/column.go#L327)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This API is now weird to me. If it returns a non-nil expr it always returns what it was given. How about just strip the expr return value? Also, it doesn't seem like anybody does anything with it anyway.
</blockquote></details>

Good point, removed the `expr` return value.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 3 of 20 files at r1, 3 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @the-ericwang35)

___
*[pkg/ccl/backupccl/restore_planning.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-S1hF2Hs2RlG5MHmA:-MW15Qdd7PToLeMITZFB:bhhqz1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/ccl/backupccl/restore_planning.go#L128)):*
<details><summary><i>Previously, the-ericwang35 (Eric Wang) wrote…</i></summary><blockquote>

That's a good point, I've added some additional logic to look for descriptor rewrites in the view query, since it can now contain sequence IDs. I've also added a test to backup and restore a view.
</blockquote></details>

I saw you added a test for the old views and making sure that that does *not* get upgraded. Can you also test that for these new views that when we back them up and then restore them that everything is happy -- that the references are updated correctly etc. 

I think there are a few versions of that. One is backing up the entire database and restoring it. In that case we'd expect both the sequence and view to get restored and to refer to eachother. Another is restoring the view after dropping it. Another still is restoring both the sequence and the view into an existing database. 
___
*[pkg/sql/show_create_clauses.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW14vUL-WUdCfCDzDLO:-MW14vUM7UR84eCwOysT:bc8i60c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ccd3768a1bb5a1853552c24ea788dd9cc2bc784/pkg/sql/show_create_clauses.go#L112)):*
> ```Go
> 	decodedViewQuery, err := formatViewQueryForDisplay(ctx, semaCtx, desc)
> 	if err != nil {
> 		log.Warningf(ctx, "error converting sequence IDs to names: %+v", err)
> ```

one more, can you put the ID and the name here? If we see this we'll want to be able to figure out which view.

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/ccl/backupccl/restore_planning.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW-S1hF2Hs2RlG5MHmA:-MW1PLgq7oilvrXRJtrq:bvejt9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/485cd4c9293a69ff74ebdf2d66c601552664cf2b/pkg/ccl/backupccl/restore_planning.go#L128)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I saw you added a test for the old views and making sure that that does *not* get upgraded. Can you also test that for these new views that when we back them up and then restore them that everything is happy -- that the references are updated correctly etc. 

I think there are a few versions of that. One is backing up the entire database and restoring it. In that case we'd expect both the sequence and view to get restored and to refer to eachother. Another is restoring the view after dropping it. Another still is restoring both the sequence and the view into an existing database. 
</blockquote></details>

Yep that's a good idea, added `TestBackupRestoreSequencesInViews` in `backup_test.go`. There's already a test called `TestBackupRestoreSequence` that tests this for sequences used in default expressions, so I didn't add any new tests for those cases.
___
*[pkg/sql/show_create_clauses.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW14vUL-WUdCfCDzDLO:-MW1EyRS6QDHknHGFtK1:b-9f087b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ccd3768a1bb5a1853552c24ea788dd9cc2bc784/pkg/sql/show_create_clauses.go#L112)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

one more, can you put the ID and the name here? If we see this we'll want to be able to figure out which view. 
</blockquote></details>

Yep, done.

**Review by ajwerner — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 1 of 20 files at r1, 1 of 14 files at r2, 3 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-:-MW6HCKhDswstE5CuEST:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by RaduBerinde — COMMENTED** [review]
Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-:-MW6ZPfu91XseNLDDOY2:bdtx8r6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @the-ericwang35)

___
*[pkg/sql/sem/tree/walk.go, line 1212 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW6Z03o1NdUbExsA5YO:-MW6Z03p3seZiQTUG-mL:bw77fuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d351819abb99ca27790e238090d6090b0cc2be/pkg/sql/sem/tree/walk.go#L1212)):*
> ```Go
> 		stmtCopy.Limit = &lCopy
> 	}
> 	return &stmtCopy
> ```

Need to make a copy of `stmt.With` - both the slice, and each element (or switch the elements to not be pointers). In general, please double-check that all slices that we're now modifying in walkStmt are getting copied.
___
*[pkg/sql/sem/tree/walk.go, line 1599 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW6Rn0nDmQmJB5FVf8r:-MW6Rn0nDmQmJB5FVf8s:bhcem8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d351819abb99ca27790e238090d6090b0cc2be/pkg/sql/sem/tree/walk.go#L1599)):*
> ```Go
> // called in VisitPre for every node. The visitor stops as soon as an error is
> // returned.
> type SimpleVisitor struct {
> ```

[nit] Why do you need to export this? It's meant to be used via `SimpleVisit()`.

**Review by the-ericwang35 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61439)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/sql/sem/tree/walk.go, line 1212 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW6Z03o1NdUbExsA5YO:-MWA8Byz3xBFkGUSobZB:bug3xel) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d351819abb99ca27790e238090d6090b0cc2be/pkg/sql/sem/tree/walk.go#L1212)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Need to make a copy of `stmt.With` - both the slice, and each element (or switch the elements to not be pointers). In general, please double-check that all slices that we're now modifying in walkStmt are getting copied.
</blockquote></details>

Ah sorry good catch, added code to make a copy.
___
*[pkg/sql/sem/tree/walk.go, line 1599 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61439#-MW6Rn0nDmQmJB5FVf8r:-MWA2_Ox8PXYn6ctjNew:b-ga31ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d351819abb99ca27790e238090d6090b0cc2be/pkg/sql/sem/tree/walk.go#L1599)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Why do you need to export this? It's meant to be used via `SimpleVisit()`.
</blockquote></details>

`SimpleVisit()` takes in a `tree.Expr`, whereas I wanted to pass in a `tree.Statement` to walk the statement. You're right though, there was no need to export `SimpleVisitor`, it makes more sense to create a function similar to `SimpleVisit()` but for statements, so I created a new function `SimpleStmtVisit()` inside of this file so that I no longer need to export `SimpleVisitor`.

**Review by ajwerner — APPROVED** [review]
> Reviewed 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61439)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

**Comment by the-ericwang35** [comment]
TFTRs!

bors r=ajwerner

**Pull request merged**
