### PR TITLE
rangefeed: remove support for inline values

### LINKED ISSUE #69357: kvserver: investigate whether we can remove support for inline values from rangefeeds
Currently, no users of rangefeeds should ever see an inline value as they all operate on normal SQL tables.

If we were to run rangefeed on range with inline values, we have at least a few problems:

- Since inline values do not have associated timestamps, we currently emit all inline values encountered during a catchup scan, even if they have not changed since the given cursor.
- If the inline value changed multiple times since the checkpoint, a catchup-scan will only observe the final value.
- If a TBI is used for the catchup scan we may miss the inline value completely.

Do we have future uses for rangefeeds over ranges with inline values?

Jira issue: CRDB-9556

### LINKED ISSUE #82507: storage: remove inline value support from `MVCCIncrementalIterator`
`MVCCIncrementalIterator` currently allows returning inline values via `MVCCIncrementalIterInlinePolicyEmit`. However, this is not safe to combine with time-bound iterators, which will become enabled by default in #82453 -- these will omit inline values since they do not fall within the time bounds. It is not clear that inline values even make sense for this iterator, since a) they're not MVCC; and b) they don't have timestamps, so we should remove support for them and error if encountered.

The only caller that enables inline values is rangefeeds. It's not clear that they make sense there either. See #69357.

Jira issue: CRDB-16491

### PR DESCRIPTION
**Pull request by erikgrinaker**
**storage: omit inline values from MVCC logical op log**

Inline values were recorded in the MVCC logical op log, which is used
for emitting rangefeed events. However, they were de facto unsupported
by rangefeeds, since they would trigger an assertion panic due to their
(zero-valued) timestamp being below the the rangefeed's resolved
timestamp.

It isn't clear that inline values make sense in rangefeeds. They can't
be ordered, nor checkpointed, and the catchup scan may omit them
entirely due to their use of time-bound iterators.

This patch therefore omits inline values from MVCC logical op logging,
with an assertion to prevent one from being added. The alternative would
have been to include these in the log and then omit them (or error) in
rangefeeds, but this doesn't seem worth the cost or complexity.

Resolves #69357.

Release note: None

**rangefeed: error on inline values in catchup scans**

Inline values have de facto been unsupported in rangefeeds, as they
would trigger an assertion because their zero-valued timestamp was below
the rangefeed's resolved timestamp. Because of this, they were recently
removed from the MVCC logical op log too, which omits them from
rangefeeds entirely.

This patch causes rangefeed catchup scans to error on them -- that is,
unless the time-bound iterator skips them completely. It also documents
this in the rangefeed API documentation.

Resolves #69357.

Release note: None

**storage: remove inline value support from `MVCCIncrementalIterator`**

`MVCCIncrementalIterator` supported emitting inline values via the
option `MVCCIncrementalIterInlinePolicyEmit`. However, time-bound
iterators may entirely omit such values, and there are no remaining
callers making use of this.

This patch therefore removes the support for emitting inline values,
instead always erroring on them (unless TBIs skip them entirely).

Resolves #82507.

Release note: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
:lgtm: Thanks for digging into this.

> Reviewed 4 of 4 files at r1, 8 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82552#-:-N41zqqAB7Q44JoPds2h:b-rks7ym)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, @miretskiy, and @tbg)

___
*[`pkg/storage/mvcc_incremental_iterator_test.go` line 804 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82552#-N41zewF8lKhgyqqSO2g:-N41zewF8lKhgyqqSO2h:b-ya06co) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc483fd3253286d9d306a21118dc6f6f46c26dba/pkg/storage/mvcc_incremental_iterator_test.go#L804)):*
> ```Go
> 		}
> 		t.Run(engineImpl.name, func(t *testing.T) {
> 			t.Run("PolicyError returns error if inline value is found", func(t *testing.T) {
> ```

[nit] We can probably remove the "PolicyError" bits from these descriptions since there is only one policy now.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82552)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911, @miretskiy, @stevendanna, and @tbg)

___
*[`pkg/storage/mvcc_incremental_iterator_test.go` line 804 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82552#-N41zewF8lKhgyqqSO2g:-N421Gr60JUGqNk1dBZQ:b-bxhove) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc483fd3253286d9d306a21118dc6f6f46c26dba/pkg/storage/mvcc_incremental_iterator_test.go#L804)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] We can probably remove the "PolicyError" bits from these descriptions since there is only one policy now.
</blockquote></details>

Ah, yeah, thanks for noticing -- fixed.

**Comment by erikgrinaker** [comment]
CI failures are unrelated. TFTR!

bors r=stevendanna

**Comment by erikgrinaker** [comment]
bors retry

**Pull request merged**
