### PR TITLE
util/log: add http log sink

### PR DESCRIPTION
**Pull request by rauchenstein**
Release note (cli change): Added a new HTTP sink to the logging system.
This can be configured similarly to other log sinks with the new 'http-servers'
and 'http-defaults' sections of the logging config passed via the "--log" or
"--log-config-file" command line flags.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
This looks reasonably good. Thanks for sending it!

what was your idea about using the "context-based" requests?

> Reviewed 3 of 8 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-:-MefQQu2BHmbmLYzTTkJ:b-783ryl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[docs/generated/logsinks.md, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefNgzE7-GR6nYYBBrs:-MefNgzE7-GR6nYYBBrt:b-14njps) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/docs/generated/logsinks.md#L181)):*
> ```Markdown
> as requests to an HTTP server.
> 
> The configuration key under the `sinks` key in teh YAML
> ```

teh -> the
___
*[docs/generated/logsinks.md, line 218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefNmi9-203MoIp86_e:-MefNmi9-203MoIp86_f:b-ady3jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/docs/generated/logsinks.md#L218)):*
> ```Markdown
> |--|--|
> | `channels` | the list of logging channels that use this sink. See the [channel selection configuration](#channel-format) section for details.  |
> | `http-defaults` |  |
> ```

maybe some description here would help
___
*[pkg/util/log/flags.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefO27PEdOJBzl6N6Fa:-MefO27PEdOJBzl6N6Fb:bkvw1rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/flags.go#L126)):*
> ```Go
> 	defer func() {
> 		if err != nil {
> 			cleanupFn()
> ```

Can you double check the Go semantics here: at which point in the control flow is the value of `cleanupFn` (a function pointer) taken into the closure?

The reason why I originally chose the way this was written is that `cleanupFn` is assigned different things throughout the execution of the code below. But maybe that wasn't necessary and what you wrote is correct. I'd just like an explanation in a comment.
___
*[pkg/util/log/http_sink_test.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPqpJ8GWNT7Ia824_:-MefPqpJ8GWNT7Ia824a:b-gzqlfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L42)):*
> ```Go
> 		buf := make([]byte, 5000)
> 		r.Body.Read(buf)
> 		bodyCh <- string(buf)
> ```

you will need a `select` here to ensure that the termination of `testBase` due to some other error (e.g. timeout) does not keep this goroutine blocked on writing on this channel.

something like this:

```go
cancel := make(chan struct{})
defer func() { close(cancel) }()

handler := func ... {
    ...
    select {
       case bodyCh <- string(buf):
       case <-cancel:
   }
}
```
___
*[pkg/util/log/http_sink_test.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPdRD3kqJa_cvvYkf:-MefPdRD3kqJa_cvvYkg:b-17njo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L51)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		port := strings.Split(l.Addr().String(), ":")[1]
> ```

consider `netutil.SplitHostPort()` instead.
___
*[pkg/util/log/http_sink_test.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefQKYb-3ifVREghbVF:-MefQKYb-3ifVREghbVG:b-1rvx2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L57)):*
> ```Go
> 			err := s.Serve(l)
> 			if err != http.ErrServerClosed {
> 				serverErrCh <- err
> ```

ditto, avoid blocking on this write if the test is exiting prematurely
___
*[pkg/util/log/http_sink_test.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPQwu34Mh9gNWgvKq:-MefPQwu34Mh9gNWgvKr:b-tkejg) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L126)):*
> ```Go
> // Test cases:
> // No timeout -- ensure correct behavior.
> // Small timeout -- ensure timeout works.
> ```

missing new line at end of file

also I think you can remove this comment.
___
*[pkg/util/log/logconfig/config.go, line 473 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefOk4i1CChkdhVcc_v:-MefOk4i1CChkdhVcc_w:b-g7wk7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/logconfig/config.go#L473)):*
> ```Go
> 	Channels ChannelList `yaml:",omitempty,flow"`
> 
> 	HTTPDefaults `yaml:",inline"`
> ```

You'll need to modify the doc generator to inline the fields/documentation for this.
___
*[pkg/util/log/logconfig/validate.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPAFF5aq-AOl-G3NV:-MefPAFF5aq-AOl-G3NW:byuaa4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/logconfig/validate.go#L112)):*
> ```Go
> 			c.Sinks.HTTPServers[sinkName] = fc
> 		}
> 		// fc.serverName = serverName
> ```

why don't you need this?

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rauchenstein)

___
*[pkg/util/log/flags.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefO27PEdOJBzl6N6Fa:-MefWEhP01iTEImnixLQ:b-ertr7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/flags.go#L126)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you double check the Go semantics here: at which point in the control flow is the value of `cleanupFn` (a function pointer) taken into the closure?

The reason why I originally chose the way this was written is that `cleanupFn` is assigned different things throughout the execution of the code below. But maybe that wasn't necessary and what you wrote is correct. I'd just like an explanation in a comment.
</blockquote></details>

cleanupFn is resolved when the closure runs.
```
func main() {
	fn := func(){ fmt.Println("one") }
	defer func(){ fn() }()
	fn = func(){ fmt.Println("two") }	
}
```
...prints "two" while just `defer fn()` would evaluate the value of fn at the defer site and print "one".
___
*[pkg/util/log/http_sink_test.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPdRD3kqJa_cvvYkf:-MefVeH19tFCJVQ2rthm:b-wfpzdf) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

consider `netutil.SplitHostPort()` instead.
</blockquote></details>

I did.  This avoided a circular dependency, since netutil evidently does some logging.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[pkg/util/log/flags.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefO27PEdOJBzl6N6Fa:-MefZ2HUExG4gnEaDHjc:bphwxxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/flags.go#L126)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

cleanupFn is resolved when the closure runs.
```
func main() {
	fn := func(){ fmt.Println("one") }
	defer func(){ fn() }()
	fn = func(){ fmt.Println("two") }	
}
```
...prints "two" while just `defer fn()` would evaluate the value of fn at the defer site and print "one".
</blockquote></details>

TIL - Worth outlining in a comment then.
___
*[pkg/util/log/http_sink_test.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPdRD3kqJa_cvvYkf:-MefZ0122hynt25hJrfj:bw2nu9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L51)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

I did.  This avoided a circular dependency, since netutil evidently does some logging.
</blockquote></details>

TIL. Maybe explain this in a comment then.

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rauchenstein)

___
*[docs/generated/logsinks.md, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefNgzE7-GR6nYYBBrs:-Mf-GwnY6Mowelcj1_o5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/docs/generated/logsinks.md#L181)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

teh -> the
</blockquote></details>

Done.
___
*[docs/generated/logsinks.md, line 218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefNmi9-203MoIp86_e:-Mf-GzFcDqe8gW9FLcHK:b-lub2rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/docs/generated/logsinks.md#L218)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe some description here would help
</blockquote></details>

Done.  Fixing the linter's preference of HTTPDefaults over HttpDefaults actually broke this.  Regex assumed one capitalized word before "Defaults."  Made the regex more general and fixed the camel-casing logic to support "words" in all CAPS.
___
*[pkg/util/log/flags.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefO27PEdOJBzl6N6Fa:-Mf-IrcGCVHfvQ1H5gkw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/flags.go#L126)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

TIL - Worth outlining in a comment then.
</blockquote></details>

Done.
___
*[pkg/util/log/http_sink_test.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPqpJ8GWNT7Ia824_:-Mf-KDntEWDNs6P3QHnU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L42)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you will need a `select` here to ensure that the termination of `testBase` due to some other error (e.g. timeout) does not keep this goroutine blocked on writing on this channel.

something like this:

```go
cancel := make(chan struct{})
defer func() { close(cancel) }()

handler := func ... {
    ...
    select {
       case bodyCh <- string(buf):
       case <-cancel:
   }
}
```

</blockquote></details>

Done.
___
*[pkg/util/log/http_sink_test.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPdRD3kqJa_cvvYkf:-Mf-KYfs43Xd359eX9u8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

TIL. Maybe explain this in a comment then.
</blockquote></details>

Done.
___
*[pkg/util/log/http_sink_test.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefQKYb-3ifVREghbVF:-Mf-KyBo0TIwsnLnejSg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto, avoid blocking on this write if the test is exiting prematurely
</blockquote></details>

Done.
___
*[pkg/util/log/logconfig/config.go, line 473 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefOk4i1CChkdhVcc_v:-Mf-L5Q938L92U5gVMst:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/logconfig/config.go#L473)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You'll need to modify the doc generator to inline the fields/documentation for this.
</blockquote></details>

Done.
___
*[pkg/util/log/logconfig/validate.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPAFF5aq-AOl-G3NV:-MfFHB-Y6fPKOlYyeD0w:b-ji4p4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/logconfig/validate.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

why don't you need this?
</blockquote></details>

I had to approach this more as "why do the other sinks need this?" because other than FileSink (for which the sink name affects the file names), the sink name doesn't actually affect functionality.  So I looked into what FluentSink does with it and it appears to only be used for the UML diagram produced by logconfig/export.go.  To some degree, this suggests that using a map instead of a list in the logconfig was probably not the best design (but that would be a breaking change at this point).

But that investigation led me to finding export.go as another place that changes are needed.

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rauchenstein)

___
*[docs/generated/logsinks.md, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefNgzE7-GR6nYYBBrs:-MfFK5Gt9EyUqoFlbPZJ:ba5hr66) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/docs/generated/logsinks.md#L181)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wait, not done?  Let me look again.

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rauchenstein)

___
*[docs/generated/logsinks.md, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefNgzE7-GR6nYYBBrs:-MfFKqDUBazcqm-OmTQA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/docs/generated/logsinks.md#L181)):*
<details><summary><i>Previously, rauchenstein wrote…</i></summary><blockquote>

Wait, not done?  Let me look again.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
Ok this mostly looks good now.

I'd like you to spell out the followup work with contexts in a github issue and refer to it from this PR's description, and possibly as TODOs in the code in relevant locations.

Additionally, I'd like you to explain what your view is on the configuration, see my comment below.

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-:-MfISB0n-9apDkvnHR1r:bsgtnsf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[pkg/util/log/http_sink_test.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MfIRoDE-aKA5QGwTJki:-MfIRoDF-KWQT1o1JWbu:bhe0vjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0a3cffc856bd57acb0fdd4f99c32ad1a430a/pkg/util/log/http_sink_test.go#L57)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		// netutil.SplitHostPort would cause a circular dependency, so just do a string split
> ```

You can use `addr.SplitHostPort` now and avoid a circular dependency.
___
*[pkg/util/log/logconfig/validate.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPAFF5aq-AOl-G3NV:-MfIS1cs6VqiQRXXrIk3:b-jkxkk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/logconfig/validate.go#L112)):*
> it appears to only be used for the UML diagram produced by logconfig/export.go. To some degree, this suggests that using a map instead of a list in the logconfig was probably not the best design

Yes granted, but the diagram *is* valuable.
My position at this point is that regardless of the flaws in the design, we probably want consistent behavior between fluent and http sinks.


> that investigation led me to finding export.go as another place that changes are needed.

What changes?

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rauchenstein)

___
*[pkg/util/log/http_sink_test.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MfIRoDE-aKA5QGwTJki:-MfcwdTD9q-RI3Hd3Txt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0a3cffc856bd57acb0fdd4f99c32ad1a430a/pkg/util/log/http_sink_test.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You can use `addr.SplitHostPort` now and avoid a circular dependency.
</blockquote></details>

Done.
___
*[pkg/util/log/logconfig/validate.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPAFF5aq-AOl-G3NV:-MfcvBxG3B0PaXcT3OIT:b6wbz7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/logconfig/validate.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> it appears to only be used for the UML diagram produced by logconfig/export.go. To some degree, this suggests that using a map instead of a list in the logconfig was probably not the best design

Yes granted, but the diagram *is* valuable.
My position at this point is that regardless of the flaws in the design, we probably want consistent behavior between fluent and http sinks.


> that investigation led me to finding export.go as another place that changes are needed.

What changes?
</blockquote></details>

Presumably we want http sinks to appear in the diagram.

**Review by knz — COMMENTED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[pkg/util/log/http_sink.go, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-Mfg6BUa26-J9SUSLXz_:-Mfg6BUa26-J9SUSLXza:bb6ht36) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5af9d38a8fb17d6b77bdd02d9db49fb2a37f5d/pkg/util/log/http_sink.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

2021
___
*[pkg/util/log/http_sink_test.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPQwu34Mh9gNWgvKq:-Mfg66Uk3yY2_8q43UYM:bcxsidq) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L126)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

missing new line at end of file

also I think you can remove this comment.
</blockquote></details>

This comment is still out of place.
___
*[pkg/util/log/http_sink_test.go, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-Mfg6D_L8UUaKKH3xF0p:-Mfg6D_L8UUaKKH3xF0q:bb6ht36) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5af9d38a8fb17d6b77bdd02d9db49fb2a37f5d/pkg/util/log/http_sink_test.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

2021
___
*[pkg/util/log/http_sink_test.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-Mfg64PI1B_WTT3eVekn:-Mfg64PJEFhoU1pkEfBV:bcxsidq) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5af9d38a8fb17d6b77bdd02d9db49fb2a37f5d/pkg/util/log/http_sink_test.go#L29)):*
> ```Go
> )
> 
> // TODO: HTTP server needs bound to context -- still need to figure out the right context.
> ```

This comment is still out of place.

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/log/http_sink.go, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-Mfg6BUa26-J9SUSLXz_:-MfiJ2_o6xEaeIyvJO1P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5af9d38a8fb17d6b77bdd02d9db49fb2a37f5d/pkg/util/log/http_sink.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[pkg/util/log/http_sink_test.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-MefPQwu34Mh9gNWgvKq:-MfmhME879ZYAJC0qeNd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952254effa066145917e719600ef722870ca5fc6/pkg/util/log/http_sink_test.go#L126)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This comment is still out of place.
</blockquote></details>

Done.
___
*[pkg/util/log/http_sink_test.go, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-Mfg6D_L8UUaKKH3xF0p:-MfiJ47O5N6qBtx2xl0R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5af9d38a8fb17d6b77bdd02d9db49fb2a37f5d/pkg/util/log/http_sink_test.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[pkg/util/log/http_sink_test.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66196#-Mfg64PI1B_WTT3eVekn:-MfmhN1A5K6_pCY0BEsK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5af9d38a8fb17d6b77bdd02d9db49fb2a37f5d/pkg/util/log/http_sink_test.go#L29)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This comment is still out of place.
</blockquote></details>

Done.

**Comment by rauchenstein** [comment]
Having trouble figuring out this leaking goroutine issue.  (See GitHub CI test history.  I've been having to rely on CI, since I've never had this issue locally.)  Initially, I thought allowing mechanisms like cancelCh that allow goroutines to complete would be sufficient.  @itsbilal helped by pointing out that an explicit join using a WaitGroup or ServerClosedCh would be necessary to be sure the goroutines not only terminate, but do so by the time the test checks.  But neither of those seem to have made a difference -- there's still a goroutine leak.

**Comment by knz** [comment]
leakcheck waits for a little bit for lingering goroutines to terminate on their own, so we're not anxious to use wait groups. I'll have a look

**Review by knz — APPROVED** [review]
thank you! :100:

**Pull request merged**
