### PR TITLE
testserver: remove direct casts to `*server.TestServer`

### PR DESCRIPTION
**Pull request by knz**
First 3 commits from #107868.

In a later stage we would like the result of `StartServer` to return different concrete types depending on parameters. Before we can do that however, we need to remove direct casts of that return value to `*server.TestServer`.

Incidentally, this patch improves the APIs as follows:

- the health probe for secondary tenant servers now properly
  includes the draining state of the RPC interface (previously,
  only the SQL draining state was included).

- `ApplicationLayerInterface` now includes `Readiness()` and
  `DefaultZoneConfig()`.

- `StorageLayerInterface` now includes
  `ScratchRangeWithExpirationLease()`, `GetRangeLease()`, `TsDB()`,
  `Locality()` and `DefaultSystemZoneConfig()`.

Epic: CRDB-18499

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Last two commits :lgtm:

> Reviewed 10 of 10 files at r4, 19 of 99 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107866#-:-NahWaulDbYrWkprvsBQ:by4jjvt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @knz, and @stevendanna)

___
*[`-- commits` line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107866#-NahSGdR2KQ0hFIz_ATn):*
Is it because `GossipI` is part of the storage layer interface?
___
*[`pkg/cli/testutils.go` line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/107866#-NahTCis03ST6on04vSb:-NahTCis03ST6on04vSc:b-rpdyh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0414edb47511ec7117a4faccf6c6b8ceab1276d2/pkg/cli/testutils.go#L52)):*
> ```Go
> // TestCLI wraps a test server and is used by tests to make assertions about the output of CLI commands.
> type TestCLI struct {
> 	// a copy of the insecure mode parameter.
> ```

nit: should start with the capital letter.

**Review by stevendanna — APPROVED** [review]

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107866)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @yuzefovich)

___
*[`-- commits` line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107866#-NahSGdR2KQ0hFIz_ATn):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is it because `GossipI` is part of the storage layer interface?
</blockquote></details>

It's more because `GossipI` is an interface method, and `.Gossip` is not (because of package dependency cycle).
Same about `.Stores` vs `.GetStores` which the next commit also simplifies.
___
*[`pkg/cli/testutils.go` line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/107866#-NahTCis03ST6on04vSb:-Nahg7nyB6AneDy3l-bc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0414edb47511ec7117a4faccf6c6b8ceab1276d2/pkg/cli/testutils.go#L52)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should start with the capital letter.
</blockquote></details>

Done.

**Comment by knz** [comment]
bors r=yuzefovich,stevendanna

**Comment by knz** [comment]
bors r=yuzefovich,stevendanna

**Comment by knz** [comment]
bors r=yuzefovich,stevendanna

**Pull request merged**
