### PR TITLE
sql: add cluster settings for a PRIMARY REGION and blocking PRIMARY REGION drops

### LINKED ISSUE #65115: multiregion: default "PRIMARY REGION" / zone config for tenants
It is likely in serverless cluster with multiple tenants to have multiple regions (we're talking 20+!).

The default zone configs at this stage would mean that data on these clusters with be geo-distributed by default, which is not a great situation for latency.

# Solution 1: default PRIMARY REGION

Every database created in a tenanted setup will have a PRIMARY REGION which defaults to some value (arguably the region the user signed up for). This will automatically make every database have the correct zone configuration by default, and every table is correctly LOCALITY REGIONAL BY TABLE IN PRIMARY REGION so everything inherits well.

This can be stored on some metadata table on each tenant, or as a CLUSTER SETTING which can be controlled by the developer.

The downside with this approach for me is that we're forcing the user to immediately pickup multi-region abstractions. We still don't have that much data on whether these localities affect ORMs for me to be confident everything will play out nicely, but I trust it'll be mostly fine. However, the implicit behaviour is still a little iffy for me (and users may be confused why this is happening automatically with no opt-out).

# Solution 2: default zone config

Instead of making each database have a default PRIMARY REGION, just give them a zone configuration that defaults to being localised to the region they signed up for.

This means we don't "multi-region up" the user by default. A user can also change this DEFAULT zone config to whatever they want, instead of needing to learn about a new cluster setting.

### PR DESCRIPTION
**Pull request by otan**
Restore is not yet handled.

See individual commits for details.

Refs CRDB-2514
Resolves #65115

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Nice!  Mostly minor stuff.

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67168#-:-MdrDYEy5oESHNwjl3lt:buil1di)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[docs/generated/settings/settings.html, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67168#-MdrCCTY4xUACo6mJCIU:-MdrCCTY4xUACo6mJCIV:b-f8swjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecf123fc14bb3903380ad05cbad6c090f5ecc1a/docs/generated/settings/settings.html#L118)):*
> ```HTML
> <tr><td><code>sql.metrics.statement_details.threshold</code></td><td>duration</td><td><code>0s</code></td><td>minimum execution time to cause statement statistics to be collected. If configured, no transaction stats are collected.</td></tr>
> <tr><td><code>sql.metrics.transaction_details.enabled</code></td><td>boolean</td><td><code>true</code></td><td>collect per-application transaction statistics</td></tr>
> <tr><td><code>sql.multiregion.drop_final_region.enabled</code></td><td>boolean</td><td><code>true</code></td><td>allows dropping the last region of a database</td></tr>
> ```

Nit: to mirror the terminology used in the other cluster variable, we might want to change this to `drop_primary_region`.  That way, talking about the two of them together is clearer.
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67168#-MdrAIlP5pXmbKtBqXZO:-MdrAIlP5pXmbKtBqXZP:bhczpr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f68b4d084aa70d4816a87435a87134158b5a4be/pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region#L34)):*
> ```
> 
> query TTBT colnames
> SHOW REGIONS FROM DATABASE db_explicit_primary_region
> ```

Can you add a test here where we set this differently for two tenants and validate that it sets the `PRIMARY REGION` appropriately for both of them?
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67168#-MdrCodNA5lXMkqVkQDj:-MdrCodNA5lXMkqVkQDk:b-czr8q2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecf123fc14bb3903380ad05cbad6c090f5ecc1a/pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region#L52)):*
> ```
> ALTER DATABASE db_explicit_primary_region DROP REGION "ap-southeast-2"
> 
> statement error databases in this cluster must have at least 1 region
> ```

Can we add a test where we set this value differently for different tenants and validate that one can drop the primary region while the other one can't?
___
*[pkg/sql/descriptor.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67168#-MdrAYaJ-sgZMer63MyC:-MdrAYaJ-sgZMer63MyD:b-hlnasj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f68b4d084aa70d4816a87435a87134158b5a4be/pkg/sql/descriptor.go#L269)):*
> ```Go
> const DefaultPrimaryRegionClusterSettingName = "sql.defaults.primary_region"
> 
> // DefaultPrimaryRegion is a cluster setting that containns the default primary region.
> ```

nnit:  too manny nn's

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67168)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67168#-MdrAIlP5pXmbKtBqXZO:-MdsZmvh8UOxGM_V3iep:br0ir8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f68b4d084aa70d4816a87435a87134158b5a4be/pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region#L34)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can you add a test here where we set this differently for two tenants and validate that it sets the `PRIMARY REGION` appropriately for both of them?
</blockquote></details>

not yet, because tenants can't use multi-region cause of the zone config work.
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67168#-MdrCodNA5lXMkqVkQDj:-MdsZnKN-LcN_4LcR6Zc:br0ir8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecf123fc14bb3903380ad05cbad6c090f5ecc1a/pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region#L52)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can we add a test where we set this value differently for different tenants and validate that one can drop the primary region while the other one can't?
</blockquote></details>

not yet, because tenants can't use multi-region cause of the zone config work.

**Review by ajstorm — APPROVED** [review]
All good here.  If you can open an issue to track the test cases changes, that would be awesome.

> Reviewed 5 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67168#-:-MdsckRU03hCmjVsg9NQ:b-cdtphc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67168#-MdrAIlP5pXmbKtBqXZO:-MdscQR6CNoxXmgYa6Qd:b-rj5wt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f68b4d084aa70d4816a87435a87134158b5a4be/pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region#L34)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

not yet, because tenants can't use multi-region cause of the zone config work.
</blockquote></details>

Oh, right.  :facepalm: 

Can you open an issue for such a test?

**Comment by otan** [comment]
ya #67236 

bors r=ajstorm

**Pull request merged**
