### PR TITLE
sql: don't allocate initial cap of 10000 rows for returning DML stmts

### PR DESCRIPTION
**Pull request by nvb**
Before this change we would initialize RowContainers with an
initial capacity of `10000` rows for DML statements that had
a `RETURNING` clause. This was absolutely insane because most
`DML` statements that return rows return only a few. This change
fixes this mistake so that the RowContainers are now initialized
without an initial capacity (which means that a single "chunk" is
allocated to begin).

I initially saw this pop up in a CPU profile of `adriatic`, which
was running TPC-C. In the profile I saw that `updateNode's` use
of `RowContainer.AddRow` was accounting for **1.59%** of system-wide
CPU utilization.

After making this change I tested it out against TPC-C, which is
a good generator to experiment with for this change because it uses
DML statements with RETURNING clauses in 3 of its 5 txn types.
On my laptop this change improved throughput by **13.8%** and
reduced average latency by **12.3%**.

Release note (performance improvement): Avoid allocating large row
buffer for DML statements with RETURNING clauses.

### CODE REVIEW

**Comment by knz** [comment]
LGTM

but you're not doing this PR justice by leaving out the release note...

**Review by a-robinson — APPROVED** [review]
I see you've already started on improving throughput :)

**Comment by nvanbenschoten** [comment]
TFTRs! 

> but you're not doing this PR justice by leaving out the release note...

Done.

**Review by knz — APPROVED** [review]

**Pull request merged**
