### PR TITLE
sql: fix ALTER DEFAULT PRIVILEGES for procedures

### PR DESCRIPTION
**Pull request by mgartner**
This commit fixes a minor bug with `ALTER DEFAULT PRIVILEGES` for
procedures and adds related tests.

Epic: CRDB-25388

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first 5 commits are from #111808.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, 7 of 7 files at r2, 11 of 11 files at r3, 31 of 31 files at r4, 41 of 41 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111950#-:-Ng5klBZ69dg_kcYhkep:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @rharding6373)

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111950#-:-Ng6TxhF1n8FqNaHmYKw:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @dt, and @miretskiy)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
