### PR TITLE
cli: use order by primary key in dump

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by knz — COMMENTED** [review]
The idea for ORDER BY is OK.
However I see that all the names are inlined in the SQL query without proper escaping. Instead of `"%s", name` you should do `"%s", parser.Name(name)`.

**Comment by knz** [comment]
(Check what happens if you have a table / index / columns named `";"` which is a valid identifier.

**Comment by mjibson** [comment]
Ah. I think I'll let this PR sit until yours lands and just do all these changes at the same time.

**Comment by mjibson** [comment]
Closing in favor of #17581

**Pull request closed without merging**
