### PR TITLE
sql,stmtdiagnostics: fix startup bug, extract subpackage for stmtdiagnostics

### PR DESCRIPTION
**Pull request by ajwerner**
This PR comes in 2 commits. The first is a critical bug fix for #46410 whereby queries could be issued before the server has started up. The second is aesthetic. The statement diagnostics registry deserves its own package; sql is a mess already, no need to make it worse. 

Release justification: bug fixes and low-risk updates to new functionality

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
Good catch, thanks for the fix.

LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-:-M36yIjd7VM87GD595By:b14kyc9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @RaduBerinde)

___
*[pkg/server/server.go, line 893 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36vFEd9-5w-uzVK7_p:-M36vFEd9-5w-uzVK7_q:b-7blzcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/server/server.go#L893)):*
> ```Go
> 	s.internalExecutor = internalExecutor
> 	execCfg.InternalExecutor = internalExecutor
> 	// TODO(ajwerner): Do we definitely know our node ID yet? Should we take a
> ```

luckily I think the `nodeID` is not actually used, so let's get rid of it.
Otherwise, it's indeed not known at this point, I don't think.
___
*[pkg/server/server.go, line 895 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36uMsUBrSKO5PW84Rv:-M36uMsUBrSKO5PW84Rw:b-9ztidg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/server/server.go#L895)):*
> ```Go
> 	// TODO(ajwerner): Do we definitely know our node ID yet? Should we take a
> 	// node id container instead?
> 	execCfg.StmtInfoRequestRegistry = sql.NewStmtDiagnosticsRequestRegistry(internalExecutor, s.db, s.gossip, s.NodeID())
> ```

long line :)
___
*[pkg/sql/exec_util.go, line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36ucay9edPr5gyIMUP:-M36ucay9edPr5gyIMUQ:b-jy93f2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/sql/exec_util.go#L591)):*
> ```Go
> 	ProtectedTimestampProvider protectedts.Provider
> 
> 	// StmtInfoRequestRegistry
> ```

sup with the comment?
___
*[pkg/sql/exec_util.go, line 602 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36yyxLCiPiUdjyTFrM:-M36yyxLCiPiUdjyTFrN:b-ck4uyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b8fafd8372e95b3405b76df2c797c2afe42db91/pkg/sql/exec_util.go#L602)):*
> ```Go
> // StmtDiagnosticsTracker is the interface into *stmtdiagnostics.Registry to
> // record statement diagnostics.
> type StmtDiagnosticsRecorder interface {
> ```

the comment name is wrong; the struggle is real. How about `StmtDiagnoser`
___
*[pkg/sql/statement_diagnostics.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36y1XL0amRWR2R6XVP:-M36y1XL0amRWR2R6XVQ:bdgja52) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/sql/statement_diagnostics.go#L59)):*
> ```Go
> 	gossip           *gossip.Gossip
> 	nodeID           roachpb.NodeID
> 	gossipUpdateChan chan stmtDiagRequestID
> ```

pls add a comment to this
___
*[pkg/sql/statement_diagnostics.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36vg530T5T1CTVULR2:-M36vg530T5T1CTVULR3:b-v44os1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/sql/statement_diagnostics.go#L86)):*
> ```Go
> }
> 
> func (r *stmtDiagnosticsRequestRegistry) run(ctx context.Context) {
> ```

I'd call this `poll()`.
___
*[pkg/sql/statement_diagnostics.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36x06jCw3UlzmOo3Nx:-M36x06jCw3UlzmOo3Ny:b4c2hal) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/sql/statement_diagnostics.go#L88)):*
> ```Go
> func (r *stmtDiagnosticsRequestRegistry) run(ctx context.Context) {
> 	var timer timeutil.Timer
> 	// TODO(ajwerner): Make this polling interval a cluster setting.
> ```

nit: my opinion is that a TODO like this doesn't serve any purpose; it's not telling me any interesting information. You're just washing you conscience (or, rather, mine), at the expense of noise :)
I haven't done it because doing it would mean intercepting events when it changed and acting on them.

**Review by ajwerner — COMMENTED** [review]
Seems like maybe you missed some of the second commit?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-:-M371xQ0CRYPsdP4vBoG:b-nihbs9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/server/server.go, line 893 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36vFEd9-5w-uzVK7_p:-M36zkBhEn36ZPUmZMi3:bnt63pk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/server/server.go#L893)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

luckily I think the `nodeID` is not actually used, so let's get rid of it.
Otherwise, it's indeed not known at this point, I don't think.
</blockquote></details>

I did that in the next commit. 
___
*[pkg/server/server.go, line 895 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36uMsUBrSKO5PW84Rv:-M371pwC85lhxmxKKk9h:bnpf0uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/server/server.go#L895)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line :)
</blockquote></details>

Fixed in the second commit (at least, shortened to 92). Folded in the 3rd commit.
___
*[pkg/sql/exec_util.go, line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36ucay9edPr5gyIMUP:-M36zrfQAZDioUH6uxx1:b-c2mezy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/sql/exec_util.go#L591)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

sup with the comment?
</blockquote></details>

Cleaned up a tad? It was a bit stale. I need a comment on this field now that it's public. I do see that in the first commit it was incomplete.
___
*[pkg/sql/exec_util.go, line 602 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36yyxLCiPiUdjyTFrM:-M37-53vABBa1SlN3_bo:b-87pyh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b8fafd8372e95b3405b76df2c797c2afe42db91/pkg/sql/exec_util.go#L602)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

the comment name is wrong; the struggle is real. How about `StmtDiagnoser`
</blockquote></details>

Meh on `Diagnoser`, it doesn't really diagnose anything. `StmtDiagnosticsCollector` I'd buy. 
___
*[pkg/sql/statement_diagnostics.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36y1XL0amRWR2R6XVP:-M3740Un8hhWSF2WwqtT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/sql/statement_diagnostics.go#L59)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls add a comment to this
</blockquote></details>

Done.
___
*[pkg/sql/statement_diagnostics.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36vg530T5T1CTVULR2:-M374GzZ8Pa4CZoF5fmB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/sql/statement_diagnostics.go#L86)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd call this `poll()`.
</blockquote></details>

Done.
___
*[pkg/sql/statement_diagnostics.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M36x06jCw3UlzmOo3Nx:-M37-A_i079Esq5ZBRjR:bx9pcqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c96849808648d5346169d78dc6298c92b97a1b/pkg/sql/statement_diagnostics.go#L88)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: my opinion is that a TODO like this doesn't serve any purpose; it's not telling me any interesting information. You're just washing you conscience (or, rather, mine), at the expense of noise :)
I haven't done it because doing it would mean intercepting events when it changed and acting on them.
</blockquote></details>

Ha I actually intended to fix it in this PR and left the TODO for me to come back to later. Done in the 3rd commit.

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-:-M37KAR06rbDlUHtfjOl:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46411)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @RaduBerinde)

___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 39 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M37fxtX0g1COBCG1OWY:-M37fxtX0g1COBCG1OWZ:bkoufk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/582453d94362d19434b16dea1f111e2dda42a4b2/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L39)):*
> ```Go
> var stmtDiagnosticsPollingInterval = settings.RegisterDurationSetting(
> 	"sql.stmt_diagnostics.poll_interval",
> 	"rate at which the stmtdiagnostics.Registry polls for requests, set to non-positive to disable",
> ```

[nit] "set to zero to disable", what's the point in encouraging non-sensical usage
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics_test.go, line 229 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M37gJFq984tY_ZJWk42:-M37gJFq984tY_ZJWk43:b6imyz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/582453d94362d19434b16dea1f111e2dda42a4b2/pkg/sql/stmtdiagnostics/statement_diagnostics_test.go#L229)):*
> ```Go
> 	_, err := db.Exec("SET CLUSTER SETTING sql.stmt_diagnostics.poll_interval = '1ms'")
> 	require.NoError(t, err)
> 	waitForScans(3) // ensure several scans occurs
> ```

[nit] "occur"
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics_test.go, line 229 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M37gKuP5imy7QJ7O10_:-M37gKuP5imy7QJ7O10a:b-khskco) ([raw file](https://github.com/cockroachdb/cockroach/blob/582453d94362d19434b16dea1f111e2dda42a4b2/pkg/sql/stmtdiagnostics/statement_diagnostics_test.go#L229)):*
> ```Go
> 	_, err := db.Exec("SET CLUSTER SETTING sql.stmt_diagnostics.poll_interval = '1ms'")
> 	require.NoError(t, err)
> 	waitForScans(3) // ensure several scans occurs
> ```

I think this would still pass even if it didn't work, SucceedsSoon waits for 45s. Maybe make it 10.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46411)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 39 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M37fxtX0g1COBCG1OWY:-M37wq3845FVzlSGzUMd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582453d94362d19434b16dea1f111e2dda42a4b2/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L39)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "set to zero to disable", what's the point in encouraging non-sensical usage
</blockquote></details>

Done.
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics_test.go, line 229 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M37gKuP5imy7QJ7O10_:-M37rVRo7yFKdaCcKz9a:b-7qmo62) ([raw file](https://github.com/cockroachdb/cockroach/blob/582453d94362d19434b16dea1f111e2dda42a4b2/pkg/sql/stmtdiagnostics/statement_diagnostics_test.go#L229)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think this would still pass even if it didn't work, SucceedsSoon waits for 45s. Maybe make it 10.
</blockquote></details>

Good point. Done
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics_test.go, line 229 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46411#-M37gJFq984tY_ZJWk42:-M37wr2DBbrGD_aX6GJJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582453d94362d19434b16dea1f111e2dda42a4b2/pkg/sql/stmtdiagnostics/statement_diagnostics_test.go#L229)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "occur"
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
