### PR TITLE
sql, update: collect and report per-app txn statistics

### PR DESCRIPTION
**Pull request by knz**
Informs #21241.

This patch extends the infrastructure responsible for collecting
per-statement statistics to also collect transaction latencies.

The count and latency of autocommit (single-statement) and explicit
transactions are collected separately, and also separately for each
application.

The new data can be queried from `crdb_internal.node_txn_statistics`.

The combined latency histogram is also collected and exposed as the
two new per-node metrics `sql.txn.autocommit.latency` and
`sql.txn.explicit.latency`.

Release note: some preliminary, experimental transaction latency
statistics are now collected and reported. Their reporting is
controlled by the same session settings as per-statement statistics.

cc @petermattis

### CODE REVIEW

**Comment by dt** [comment]
:lgtm:

---

Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/app_stats.proto, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21351#-L2zrGonVUPSYYIpMPb1:-L2zrGonVUPSYYIpMPb2:by6fkfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0159d8e76734b3d4c6fa8d300e1ed1ffb204c2/pkg/roachpb/app_stats.proto#L104)):*
> ```protobuf
>   optional string app = 1 [(gogoproto.nullable) = false];
>   optional ApplicationStatistics stats = 2 [(gogoproto.nullable) = false];
> }
> ```

nit: newline

---

*[pkg/sql/app_stats.go, line 287 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21351#-L2zr-lvukRVu5glkpjZ:-L2zr-lvukRVu5glkpj_:b-webcef) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0159d8e76734b3d4c6fa8d300e1ed1ffb204c2/pkg/sql/app_stats.go#L287)):*
> ```Go
> 		log.Errorf(ctx, "error while marshaling txn stats for %q: %v", appName, err)
> 	} else {
> 		log.Infof(ctx, "Transaction statistics for %q: %s", json)
> ```

was this supposed to have `appName` handed to it too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21351#-:-L2zs2J9DPnVNhd5Gk1V:bnfp4nl)*

**Comment by knz** [comment]
@dt I just noticed that I never went ahead to merge this PR. And now it's stale... :sob: 

@piyush-singh @jordanlewis do you think this is still relevant?

**Comment by dt** [comment]
@knz coming up on year 2 -- should we go ahead and close this as stale?

**Comment by piyush-singh** [comment]
Probably safe to close as so many things have changed; I know that Jordan and Andy are revisiting txn metrics in 20.2, but imagine they will have their own approach.

**Comment by knz** [comment]
I have peace with this.

**Pull request closed without merging**
