### PR TITLE
opt: Change how Any operator is represented and flattened

### PR DESCRIPTION
**Pull request by andy-kimball**
The Any operator currently takes a single input rowset, and expects
it to return a single boolean column. The hoister flattens the Any
operator by testing and projecting that boolean column. The problem
is that this representation cannot easily be decorrelated. Example:

   z = ANY(SELECT x FROM xy)

This is currently represented as:

  (Any (Project xy [ z=x ]))

The z=x projection field cannot easily be hoisted over a left join.
This commit uses an alternate representation:

  (Any xy z EqOp)

The new representation keeps the input, scalar, and comparison op
components separate, so they can be combined in ways that it easier
to decorrelate.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 21 of 26 files at r1, 15 of 17 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-LCOWvu41Hi6Dk792JIi:-LCOWvu41Hi6Dk792JIj:bqnfuhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7580cc4d2a19769ee8748b7bb41660f721b9ab05/pkg/sql/opt/memo/logical_props_builder.go#L549)):*
> ```Go
> 		logical.Scalar.OuterCols = ev.childGroup(0).logical.Relational.OuterCols
> 
> 		// Any has additional scalar value that can contain outer reference.
> ```

nit: references

---

*[pkg/sql/opt/norm/decorrelate.go, line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-LCOXYPA8bsjtlx_vcJB:-LCOXYPA8bsjtlx_vcJC:b5597to) ([raw file](https://github.com/cockroachdb/cockroach/blob/7580cc4d2a19769ee8748b7bb41660f721b9ab05/pkg/sql/opt/norm/decorrelate.go#L442)):*
> ```Go
> //
> //                  | before  | after   | after
> //   subquery       | BOOL_OR | BOOL_OR | CASE
> ```

[nit] I would put x and the subquery in a separate column (and maybe add the cases when the subquery is `1, null`)

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 223 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-LCOYpp8-L8ca36JgOTW:-LCOYpp8-L8ca36JgOTX:b-fzlir3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f776092d20b9c44482f3e86b9c3f1d1ca914a4d5/pkg/sql/opt/norm/rules/decorrelate.opt#L223)):*
> ```
>                     $input
>                     (Filters
>                         [ (IsNot (ConstructAnyCondition $input $value $cmp) (False)) ]
> ```

Are there restrictions here in the case where `value` returns different values when evaluated multiple times? For example `(100*random())::int > (SUBQUERY)` and the subquery has 100 rows (say with the same value): after the transformation, it's ~100 times more likely that the result is `true`. Not sure if that's something we should care about (or if there are similar cases that are more important).

It's interesting that it works in cases like value = `SELECT x FROM t LIMIT 1` which in principle can return any `x` in the table (if EXISTS finds one entry, it's as if we evaluated the original query once and happened to get that particular result).

---

*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 1744 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-LCOildHDECVVU2R-rxK:-LCOildHDECVVU2R-rxL:b-t5c0k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f776092d20b9c44482f3e86b9c3f1d1ca914a4d5/pkg/sql/opt/norm/testdata/rules/decorrelate#L1744)):*
> ```
>            └── false [type=bool]
> 
> # NOT ANY is one of several conjuncts.
> ```

[nit]: add a comment mentioning that `i > ALL` gets built as `NOT i <= ANY`. (I misread `ALL` as `ANY` in the query and was confused)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-:-LCOiw8P8qWMPhMcTCMy:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-LCOWvu41Hi6Dk792JIi:-LCRK1Sq2Ed56D7KnIjg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7580cc4d2a19769ee8748b7bb41660f721b9ab05/pkg/sql/opt/memo/logical_props_builder.go#L549)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

nit: references
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/decorrelate.go, line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-LCOXYPA8bsjtlx_vcJB:-LCRKSzy-A6thKEI91yc:bs7zgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7580cc4d2a19769ee8748b7bb41660f721b9ab05/pkg/sql/opt/norm/decorrelate.go#L442)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would put x and the subquery in a separate column (and maybe add the cases when the subquery is `1, null`)
</blockquote></details>

I'm not sure I understand what you're asking for. Can you give an example? I do have the cases `(1, null)` and `(null, 1)` cases already.

---

*[pkg/sql/opt/norm/rules/decorrelate.opt, line 223 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-LCOYpp8-L8ca36JgOTW:-LCRKoK4ERKHvfFSLPm5:bjr18x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f776092d20b9c44482f3e86b9c3f1d1ca914a4d5/pkg/sql/opt/norm/rules/decorrelate.opt#L223)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Are there restrictions here in the case where `value` returns different values when evaluated multiple times? For example `(100*random())::int > (SUBQUERY)` and the subquery has 100 rows (say with the same value): after the transformation, it's ~100 times more likely that the result is `true`. Not sure if that's something we should care about (or if there are similar cases that are more important).

It's interesting that it works in cases like value = `SELECT x FROM t LIMIT 1` which in principle can return any `x` in the table (if EXISTS finds one entry, it's as if we evaluated the original query once and happened to get that particular result).
</blockquote></details>

In general, our rules assume that there are no side effects in expressions. Once we start handling side effects, we'll likely only respect them in a small number of well-defined places (like `Case` and possibly `Project`). That said, if we're noting performance issues with this approach (because $value is a complex expression), we'd need to look at caching the calculation of `$value` once and then reusing it.

---

*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 1744 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-LCOildHDECVVU2R-rxK:-LCRMfHyAuexz5SemCFT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f776092d20b9c44482f3e86b9c3f1d1ca914a4d5/pkg/sql/opt/norm/testdata/rules/decorrelate#L1744)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit]: add a comment mentioning that `i > ALL` gets built as `NOT i <= ANY`. (I misread `ALL` as `ANY` in the query and was confused)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25434)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/norm/decorrelate.go, line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-LCOXYPA8bsjtlx_vcJB:-LCTlDdc2olJVp2VOXuW:b4b9ufi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7580cc4d2a19769ee8748b7bb41660f721b9ab05/pkg/sql/opt/norm/decorrelate.go#L442)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'm not sure I understand what you're asking for. Can you give an example? I do have the cases `(1, null)` and `(null, 1)` cases already.
</blockquote></details>

```
//        |           | before  | after   | after
//    z   | subquery  | BOOL_OR | BOOL_OR | CASE
//  ------+-----------+---------+---------+-------
//    1   | (1)       | true    | true    | true
//    1   | (1, null) | true    | true    | true
//    1   | (null)    | false   | false   | null
//   null | (1)       | true    | true    | null
//   null | (1, null) | true    | true    | null
//   null | (null)    | false   | false   | null
//    2   | (1)       | (empty) | null    | false
//  *any* | (empty)   | (empty) | null    | false
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25434)*

**Comment by andy-kimball** [comment]
Review status: 20 of 40 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/norm/decorrelate.go, line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25434#-LCOXYPA8bsjtlx_vcJB:-LCUiwD27oFHBhZuzSj-:beijx6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7580cc4d2a19769ee8748b7bb41660f721b9ab05/pkg/sql/opt/norm/decorrelate.go#L442)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

```
//        |           | before  | after   | after
//    z   | subquery  | BOOL_OR | BOOL_OR | CASE
//  ------+-----------+---------+---------+-------
//    1   | (1)       | true    | true    | true
//    1   | (1, null) | true    | true    | true
//    1   | (null)    | false   | false   | null
//   null | (1)       | true    | true    | null
//   null | (1, null) | true    | true    | null
//   null | (null)    | false   | false   | null
//    2   | (1)       | (empty) | null    | false
//  *any* | (empty)   | (empty) | null    | false
```
</blockquote></details>

Ah, got it. I made that change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25434)*

**Pull request merged**
