### PR TITLE
sql, json, opt: make zigzag join use type Bytes for virtual inverted columns

### PR DESCRIPTION
**Pull request by rytaft**
**sql,json: add uniqueOnly parameter to EncodeContainingInvertedIndexSpans**

This commit adds a new parameter `uniqueOnly` to the function
`EncodeContainingInvertedIndexSpans`. If `uniqueOnly` is false, the function
has the old behavior and produces spans for all paths through the given JSON
or Array. If `unqiueOnly` is true, however, `EncodeContainingInvertedIndexSpans`
only produces spans that are guaranteed not to produce duplicate primary
keys. For JSON, this equates to removing all JSON paths that end in a
container leaf (i.e., empty object or array). For Array, no change is
required as a non-empty array will produce all unique spans. If there are
no paths through the JSON or Array that satisfy the uniqueness requirement,
`EncodeContainingInvertedIndexSpans` returns `unique=false`.

This commit also subtly changes the meaning of the `unique` return parameter for
`EncodeContainingInvertedIndexSpans`. Previously, `unique` was always false if more
than one span slice was returned (indicating an `INTERSECTION` was required). Now
`unique` is true if every span slice returned is itself unique.

To match this behavior, when `SpanExpression`s are intersected (combined with
`And`), the resulting `SpanExpression` is unique if both its children are unique.
The union of `SpanExpressions` (combined with `Or`) is still not guaranteed to be
unique, however, even if its children are.

These changes are necessary in order to be able to use this infrastructure for
planning zigzag joins in a future commit.

**sql,opt: make zigzag join use type Bytes for virtual inverted columns**

This commit updates `GenerateInvertedIndexZigzagJoins` in the optimizer to
make use of the new code that is already being used for planning inverted
constrained scans in `GenerateInvertedIndexScans`. This will be necessary to
support multi-column inverted indexes and brings us closer to being able
to remove inverted indexes from the `idxconstraint` library.

This commit also updates the way the zigzag joiner handles inverted indexes.
the processor now expects the fixed values for the inverted key column
to have type bytes instead of JSON or Array. Instead of attempting to
encode the inverted index key, it now assumes the key has already
been encoded and is stored as a `DBytes`.

### CODE REVIEW

**Comment by rytaft** [comment]
Please ignore the first commit; it's from #58241.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
(I haven't yet read the last commit)

> Reviewed 5 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-:-MQEHkMv-Kzr7C4HmVgS:b87jirm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/expression.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQEEBjmE8N1FHNOEGdG:-MQEEBjnEnYsXwQOGUeN:b-ki7izh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b490b6664d32070d450425a79e448fa5980d058/pkg/sql/opt/invertedexpr/expression.go#L366)):*
> ```Go
> 	// primary keys. Otherwise, Unique is false. Unique may be true for certain
> 	// JSON or Array SpanExpressions, and it holds when SpanExpressions are
> 	// combined with And. It does not hold when these SpanExpressions are
> ```

With this change aren't we also requiring that each span has PKs in sorted order, for the zig-zag join?
___
*[pkg/sql/opt/invertedexpr/json_array_expression.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQEEsNv1T4pWqhOetJL:-MQEEsNv1T4pWqhOetJM:b-2bfcth) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b490b6664d32070d450425a79e448fa5980d058/pkg/sql/opt/invertedexpr/json_array_expression.go#L29)):*
> ```Go
> 	var b []byte
> 	spansSlice, tight, unique, err := rowenc.EncodeContainingInvertedIndexSpans(
> 		evalCtx, d, b, descpb.EmptyArraysInInvertedIndexesVersion, false, /* uniqueOnly */
> ```

nit: move comma after comment
___
*[pkg/sql/rowenc/index_encoding.go, line 856 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQEFCkT2Ag2cMaA42rE:-MQEFCkT2Ag2cMaA42rF:b-ienmux) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b490b6664d32070d450425a79e448fa5980d058/pkg/sql/rowenc/index_encoding.go#L856)):*
> ```Go
> //
> // If the parameter uniqueOnly is true, only unique spans will be returned
> // if possible. If this is not possible, returns unique=false. This is
> ```

What does it mean for `uniqueOnly=true` and `unique=false` -- does it mean that the callee has returned the full spans?
___
*[pkg/util/json/json.go, line 924 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQEGqP850M_AteCXZ7W:-MQEGqP99wx7tsf8J5aO:b6lqdxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b490b6664d32070d450425a79e448fa5980d058/pkg/util/json/json.go#L924)):*
> ```Go
> 	if uniqueOnly && len(spans) == 0 {
> 		// We couldn't find any unique spans.
> 		unique = false
> ```

I think some of the code comments that discuss (uniqueOnly=false,unique=false) should mention that `unique` in this context is used in the sense of "ok" -- if false, the result does not represent a super-set of the desired set.

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/invertedexpr/json_array_expression.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQEEsNv1T4pWqhOetJL:-MQO1GFKA9wsIKiK-Dfr:bos33ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b490b6664d32070d450425a79e448fa5980d058/pkg/sql/opt/invertedexpr/json_array_expression.go#L29)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: move comma after comment
</blockquote></details>

I think the crlfmt forces this, unfortunately. One option is to put each argument on its own line. The comma would still precede the comment, but it might be more aesthetically pleasing.

**Review by mgartner — COMMENTED** [review]
> Reviewed 7 of 10 files at r2, 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58385)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/xform/select_funcs.go, line 1285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQOjQVs8NUwEeOGpFXi:-MQOjQVs8NUwEeOGpFXj:b-1hn0sk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b439fcca65e6086507014d02617a506d1f8ce2/pkg/sql/opt/xform/select_funcs.go#L1285)):*
> ```Go
> 		if index.NonInvertedPrefixColumnCount() > 0 {
> 			// We don't yet support using multi-column inverted indexes with zigzag
> 			// joins.
> ```

[nit] make this a "TODO(mgartner): ..."
___
*[pkg/sql/opt/xform/select_funcs.go, line 1314 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQOl_1X-xgIArGQ8H9Y:-MQOl_1X-xgIArGQ8H9Z:b-oof16e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b439fcca65e6086507014d02617a506d1f8ce2/pkg/sql/opt/xform/select_funcs.go#L1314)):*
> ```Go
> 
> 			if len(spanExprLocal.SpansToRead) == 1 && spanExprLocal.SpansToRead[0].IsSingleVal() {
> 				vals = append(vals, spanExprLocal.SpansToRead[0].Start)
> ```

should we stop recursing if `vals` already has 2 values? if so, an explanation of why we pick just the first two would be helpful, something similar to what was here before:

		// In theory, we could explore zigzag joins on all constraint pairs.
		// However, in the absence of stats on inverted indexes, we will not
		// be able to distinguish more selective constraints from less
		// selective ones anyway, so just pick the first two constraints.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1351 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQOl98O0TFkiSVAFKuW:-MQOl98PDSxQEOejyWhz:b-1ksswt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b439fcca65e6086507014d02617a506d1f8ce2/pkg/sql/opt/xform/select_funcs.go#L1351)):*
> ```Go
> 		//  columns here.
> 
> 		idx := index.NonInvertedPrefixColumnCount()
> ```

[nit] rename `idx` or add a comment mentioning that this is the ordinal of the inverted column in the index's list of columns.

Another idea is to add a function to the index catalog like `InvertedColumnOrdinal()` which is an alias of `NonInvertedPrefixColumnCount`.
___
*[pkg/sql/rowenc/index_encoding.go, line 856 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQEFCkT2Ag2cMaA42rE:-MQO2-Gv6T2iiXNgnjD-:b-9gl3nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b490b6664d32070d450425a79e448fa5980d058/pkg/sql/rowenc/index_encoding.go#L856)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What does it mean for `uniqueOnly=true` and `unique=false` -- does it mean that the callee has returned the full spans?
</blockquote></details>

@sumeerbhola mentioned in another comment about `unique=false` being used in some contexts like `ok=false`, which I agree causes some confusion.

It's not clear to me how to remedy this though... Does this zigzag code path deserve its own API here? It might simplify this `uniqueOnly` bit. Another reason it might make sense is that it seems weird to build up an inverted expression tree just to recurse through it in GenerateInvertedIndexZigzagJoins and pick out just 2 unique spans. Would it be a lot of work to only generate 2 unique spans from the get-go?

**Review by rytaft — COMMENTED** [review]
TFTRs, and sorry for the super slow reply.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-:-MQyCgTL4aLJXySrhzIH:b-x6gwna)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/expression.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQEEBjmE8N1FHNOEGdG:-MQxZNSiEs__pq-_pS4p:b1zcw2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b490b6664d32070d450425a79e448fa5980d058/pkg/sql/opt/invertedexpr/expression.go#L366)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

With this change aren't we also requiring that each span has PKs in sorted order, for the zig-zag join?
</blockquote></details>

Yes, this definition of `Unique` doesn't exactly line up with what's required for zig zag joins. `GenerateInvertedIndexZigzagJoins` in `select_funcs.go` eliminates results that have multiple spans (in the second commit).
___
*[pkg/sql/opt/invertedexpr/json_array_expression.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQEEsNv1T4pWqhOetJL:-MQxaah5DM9zPX7l-MkW:b6dkkej) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b490b6664d32070d450425a79e448fa5980d058/pkg/sql/opt/invertedexpr/json_array_expression.go#L29)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think the crlfmt forces this, unfortunately. One option is to put each argument on its own line. The comma would still precede the comment, but it might be more aesthetically pleasing.
</blockquote></details>

This is removed in the second commit, so not going to make a change here.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1285 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQOjQVs8NUwEeOGpFXi:-MQxarEkBF1vTaleIJVE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b439fcca65e6086507014d02617a506d1f8ce2/pkg/sql/opt/xform/select_funcs.go#L1285)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] make this a "TODO(mgartner): ..."
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1314 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQOl_1X-xgIArGQ8H9Y:-MQxavChApumqeN4DbLF:bz88dwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b439fcca65e6086507014d02617a506d1f8ce2/pkg/sql/opt/xform/select_funcs.go#L1314)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

should we stop recursing if `vals` already has 2 values? if so, an explanation of why we pick just the first two would be helpful, something similar to what was here before:

		// In theory, we could explore zigzag joins on all constraint pairs.
		// However, in the absence of stats on inverted indexes, we will not
		// be able to distinguish more selective constraints from less
		// selective ones anyway, so just pick the first two constraints.

</blockquote></details>

Done. Changed the comment slightly since we do have those stats now -- we just need to actually use them.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1351 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQOl98O0TFkiSVAFKuW:-MQxdOQC1fB16RwcZKhM:bkwckbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b439fcca65e6086507014d02617a506d1f8ce2/pkg/sql/opt/xform/select_funcs.go#L1351)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] rename `idx` or add a comment mentioning that this is the ordinal of the inverted column in the index's list of columns.

Another idea is to add a function to the index catalog like `InvertedColumnOrdinal()` which is an alias of `NonInvertedPrefixColumnCount`.
</blockquote></details>

Changed the name and added a comment.
___
*[pkg/sql/rowenc/index_encoding.go, line 856 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQEFCkT2Ag2cMaA42rE:-MQxeiUZ070pafl6UT39:b-gzo8y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b490b6664d32070d450425a79e448fa5980d058/pkg/sql/rowenc/index_encoding.go#L856)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

@sumeerbhola mentioned in another comment about `unique=false` being used in some contexts like `ok=false`, which I agree causes some confusion.

It's not clear to me how to remedy this though... Does this zigzag code path deserve its own API here? It might simplify this `uniqueOnly` bit. Another reason it might make sense is that it seems weird to build up an inverted expression tree just to recurse through it in GenerateInvertedIndexZigzagJoins and pick out just 2 unique spans. Would it be a lot of work to only generate 2 unique spans from the get-go?
</blockquote></details>

Yea, you're both right that it's a bit confusing to have the `unique` return parameter function differently depending on whether `uniqueOnly` was set to `true`. Perhaps for the sake of clarity it's worth just having an additional boolean parameter `ok`? I made the change in a third commit -- let me know if you think this makes sense and I'll apply it as a fixup to the first commit.

I don't see an easy way to avoid generating more than 2 spans here, but also, since we do have inverted index stats now, we should be able to choose the 2 most selective spans in a future PR. I'd rather not do work here to limit to 2 spans when we'll just need to undo it later (I did limit to 2 spans higher up the stack based on your suggestion, but that's much easier to revert later).

I see your point about creating a separate API for zigzag joins, but I think it will be a lot of code duplication. The `uniqueOnly` param felt like the lesser of two evils, but I'm open to other suggestions...
___
*[pkg/util/json/json.go, line 924 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58385#-MQEGqP850M_AteCXZ7W:-MQxwzCzB-Lrd61I7pD7:b-myvwzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b490b6664d32070d450425a79e448fa5980d058/pkg/util/json/json.go#L924)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think some of the code comments that discuss (uniqueOnly=false,unique=false) should mention that `unique` in this context is used in the sense of "ok" -- if false, the result does not represent a super-set of the desired set.
</blockquote></details>

Added a top-level comment -- let me know if you think it needs more.

**Comment by rytaft** [comment]
Been thinking about this and I believe I have a better solution (although it will require a bit of a refactor). Please hold off on reviewing for now.

**Comment by rytaft** [comment]
Closing this in favor of #59074.

**Pull request closed without merging**
