### PR TITLE
upgrades,backupccl: audit mixed version and upgrade tests

### PR DESCRIPTION
**Pull request by adityamaru**
Please see individual commits.

Informs: #100552

### CODE REVIEW

**Comment by dt** [comment]
can you refresh my memory why we use X_Start instead of X-1?

**Comment by adityamaru** [comment]
`beforeVersion` does end up using X-1 where X is whatever we listed in front of that option. So in this case it'll be `23_1Start` - 1.

**Comment by dt** [comment]
Ugh, we should get rid of that X-1 and just have it specify the V22_2

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=dt

**Comment by adityamaru** [comment]
> we should get rid of that X-1 and just have it specify the V22_2

Yeah that test should just always use binary min supported version

**Pull request merged**
