### PR TITLE
rpc: Revert change to dialer (and test skips)

### PR DESCRIPTION
**Pull request by bdarnell**
This change made several tests flaky (and its effects are not limited to these tests). Revert it until I can figure out what's going on.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
Is the plan to fix this by the code freeze?

**Comment by bdarnell** [comment]
Based on my investigation so far it looks like this change caused some strange behavior in the lease/liveness machinery. I think it may be a bug in error handling in that code (it's getting an ambiguous error where it may not have before), but it's hard to tell exactly what's going on. I'm going to spend some more time on this but I don't know if I'll be able to figure it out before the freeze.

**Comment by bdarnell** [comment]
I've removed the "unskip TestVersionUpgrade" change from this PR - I had three consecutive acceptance test timeouts with it, so apparently that test was not made flaky by the change being reverted here.

**Comment by bdarnell** [comment]
Note that since the TestVersionUpgrade failures appear to be unrelated, I'm more optimistic that I'll be able to re-enable this (and the CLI `quit` test which is definitely related) before the freeze. But we need to figure out what's going on with TestVersionUpgrade before I can do so with confidence.

**Pull request merged**
