### PR TITLE
release-2.1: add EXPLAIN(DISTSQL) support for subqueries; don't write/parse exprs in local mode

### PR DESCRIPTION
**Pull request by jordanlewis**
I had to also backport "don't write/parse exprs in local mode" to get this to apply cleanly. I'm a little nervous about that, as it's a bit of a hefty change. That being said, it's a very good change that removes some of the last extra overhead that the DistSQL merge added - local expressions are no longer pointless serialized and re-parsed from text.

Backport:
  * 1/1 commits from "sql: don't write/parse exprs in local mode" (#30464)
  * 1/1 commits from "sql: add EXPLAIN(DISTSQL) support for subqueries" (#30857)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by asubiotto** [comment]
What's up with the TC failures?

**Comment by jordanlewis** [comment]
Glad you asked. I think I'm missing a backport. It's unfortunate that this backport required the local exprs branch in the first place. It would be much better to not require that, but unfortunately the patch doesn't cleanly apply or work without it. I'm going to get back to this today.

**Comment by asubiotto** [comment]
How important is `EXPLAIN (DISTSQL)` support for subqueries in 2.1?

BTW re: `EXPLAIN ANALYZE` failures, the expected url seems wrong: https://cockroachdb.github.io/distsqlplan/decode.html#eJyckEFLxDAQhe_-ivBOCgHba0DYRRAKS5XdepIess2wBNKmzKSoLPnv0uYg3mSP772ZNx9zxRQdtXYkgflAjV5j5jiQSOTVKgON-4KpNPw0L2m1e40hMsFckXwKBIPOngMdyTrixwoajpL1Yaud2Y-Wv3f2PEDjxYdEbNSuVk_qeX_q7tv3w0HtT6ppuwdocPwUxWSdUWuRJBuCSn4koypBnzXikn5BJNkLwdRZ_x_2SDLHSegv522Hq9xrkLtQ-ZfEhQd64zhsFEW-bnub4UhSSesimqlEuc93PwEAAP__33uBjw==. I'm confused as to why we expect the `Result` to have stats. This doesn't seem to be the same expected string as on master.

**Comment by jordanlewis** [comment]
This isn't going to happen without a significant amount of extra work, and it'll be fixed in 2.2. Closing.

**Pull request closed without merging**
