### PR TITLE
server: emit empty fields when rendering protos as JSON 

### LINKED ISSUE #6927: ui: overview looks garbled
Version (local build, no local modifications):
```
build:     beta-20160526-47-gd2db320 @ 2016/05/26 18:31:42 (go1.6.2)
admin:     http://cdo-cockroach.local:8080
sql:       postgresql://root@cdo-cockroach.local:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
```

Steps to repro:
1. `rm -rf cockroach-data && make install && cockroach start --insecure`
2. Go to admin UI

I see this:
screenshot 2016-05-26 14 34 10

Also tried `make clean` in top-level and `ui` directories before building, to no avail.

Not sure who to assign this to, so assigning to Max as a starting point. cc @tamird @mrtracy

### PR DESCRIPTION
**Pull request by tamird**
Fixes #6927.

cc @maxlang

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6945)

### CODE REVIEW

**Comment by maxlang** [comment]
Why remove gulp? It's still useful for stylus at least

**Comment by tamird** [comment]
I updated dependencies and we're no longer developing in this directory, so I thought it was OK to remove it?

**Comment by maxlang** [comment]
Leave it in for now. I'll probably build a gulp file for the ui/next code anyway, and it's currently the only way to recompile stylus on the fly, even though I haven't been doing much style work recently.

To test that this works you could probably take down your node for a minute or so and then bring it back up. I'm guessing the intermediate values will be empty?

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I updated dependencies and we're no longer developing in this directory, so I thought it was OK to remove it?
</details>


---

Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[ui/styl/partials/layout.styl, line 540 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImpL0JyjPwrB_mOEOw:-KImpL0JyjPwrB_mOEOx:-783790295) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/styl/partials/layout.styl#L540)):*
> ```Stylus
> .section
>   .node-info, .store-info
>     padding-bottom 20px
> ```

Do you know whether these were overriding other paddings?

---

*[ui/ts/models/metrics.ts, line 411 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImq6QEzFGMOVyNqzSf:-KImq6QEzFGMOVyNqzSg:2046339639) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/ts/models/metrics.ts#L411)):*
> ```XML
>                         datapoints: _.map(r.datapoints || [], (datapoint) => {
>                           // HACK: Convert string to long
>                           datapoint.timestamp_nanos = Long.fromString(datapoint.timestamp_nanos as any);
> ```

I'm not convinced this will get us the behavior we want. When I run this in the console I get:

```
Long.fromString("12345678901234567890").toNumber()
-6101065172474983000
```

---

*[ui/ts/models/metrics.ts, line 413 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImrnpNUtXx0WpBuc9Y:-KImrnpNUtXx0WpBuc9Z:1508886879) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/ts/models/metrics.ts#L413)):*
> ```XML
>                           datapoint.timestamp_nanos = Long.fromString(datapoint.timestamp_nanos as any);
>                           // HACK: Convert undefined to number
>                           datapoint.value = datapoint.value || 0;
> ```

Can we create an issue to resolve this on the backend?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-:-KIms4E5bXWMPqtgU8M0:-927625702)*

**Comment by tamird** [comment]
What am I testing by bringing the node down? I've pulled out the gulp/whatever changes - will submit in a separate PR.

<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Leave it in for now. I'll probably build a gulp file for the ui/next code anyway, and it's currently the only way to recompile stylus on the fly, even though I haven't been doing much style work recently.
> 
> To test that this works you could probably take down your node for a minute or so and then bring it back up. I'm guessing the intermediate values will be empty?
</details>


---

Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[ui/styl/partials/layout.styl, line 540 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImpL0JyjPwrB_mOEOw:-KImxiT30mhMLsL8Lnzx:1928486946) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/styl/partials/layout.styl#L540)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Do you know whether these were overriding other paddings?
</details>
Not sure what you're asking - these changes were made because stylint was complaining that they could be made more succinct.

---

*[ui/ts/models/metrics.ts, line 411 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImq6QEzFGMOVyNqzSf:-KImxoxD1jbmshaWFv9S:2028729905) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/ts/models/metrics.ts#L411)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I'm not convinced this will get us the behavior we want. When I run this in the console I get:
> 
> ```
> Long.fromString("12345678901234567890").toNumber()
> -6101065172474983000
> ```
</details>
Right, that Long is out of bounds for a number. This behaviour is by definition broken, but that's what you get for trying to fit a Long into a Number.

This is beyond what I'm prepared to fix in the old UI.

---

*[ui/ts/models/metrics.ts, line 413 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImrnpNUtXx0WpBuc9Y:-KImy0l_cGrZPRX-fVg3:-2134407419) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/ts/models/metrics.ts#L413)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Can we create an issue to resolve this on the backend?
</details>
No. I looked at the code, the omission of zero values is intentional. Besides, the new code in ui/next does the right thing without the need for these hacks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-:-KImy7I6l8mfvinz3TmP:1106040941)*

**Comment by maxlang** [comment]
I was just thinking of ways to find missing values.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> What am I testing by bringing the node down? I've pulled out the gulp/whatever changes - will submit in a separate PR.
</details>


---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[ui/ts/models/metrics.ts, line 411 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImq6QEzFGMOVyNqzSf:-KIn5BpM-AEF4q_k8jny:2106072754) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/ts/models/metrics.ts#L411)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Right, that Long is out of bounds for a number. This behaviour is by definition broken, but that's what you get for trying to fit a Long into a Number.
> 
> This is beyond what I'm prepared to fix in the old UI.
</details>
I guess I'm unclear what this gets us that `parseInt` doesn't. And `parseInt` doesn't have the indirection and failure cases of `Long.fromString(...).toNumber()`.

---

*[ui/ts/models/metrics.ts, line 413 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImrnpNUtXx0WpBuc9Y:-KIn5O9GmmIPPkZQQMTb:460465295) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/ts/models/metrics.ts#L413)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> No. I looked at the code, the omission of zero values is intentional. Besides, the new code in ui/next does the right thing without the need for these hacks.
</details>
Yeah but the API is something I'd like to eventually expose. I think it's surprising to omit values that are not `null`. These values should be nullable. If we don't have data for a certain time period we should return `null` or no value. If we have a value of `0` we should return `0`.

---

*[ui/styl/partials/layout.styl, line 540 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImpL0JyjPwrB_mOEOw:-KIn5hv_GREbhBXtUz7a:-901609234) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/styl/partials/layout.styl#L540)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Not sure what you're asking - these changes were made because stylint was complaining that they could be made more succinct.
</details>
I'm saying this isn't equivalent. For example, if `.section` has `padding-top: 50px` the old code would override this, whereas the simplified code wouldn't.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-:-KIn4nfS26eVSsjPkEDl:2001495982)*

**Comment by tamird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[ui/ts/models/metrics.ts, line 411 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImq6QEzFGMOVyNqzSf:-KInLAk2WzYZ6KLwrE1N:-1160034364) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/ts/models/metrics.ts#L411)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I guess I'm unclear what this gets us that `parseInt` doesn't. And `parseInt` doesn't have the indirection and failure cases of `Long.fromString(...).toNumber()`.
</details>
What failure cases does Long.fromString have? parseInt also does not produce the correct result from your example above.
```
parseInt("12345678901234567890")
12345678901234567000
```

This code is slightly more correct in that it calls attention to the fact that this number can exceed the range of javascript numbers, while parseInt does not. It's definitely broken though, and that's just a fact of life in this case.

---

*[ui/ts/models/metrics.ts, line 413 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImrnpNUtXx0WpBuc9Y:-KInLDzbHZHTVvRw2c5B:1976674068) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/ts/models/metrics.ts#L413)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Yeah but the API is something I'd like to eventually expose. I think it's surprising to omit values that are not `null`. These values should be nullable. If we don't have data for a certain time period we should return `null` or no value. If we have a value of `0` we should return `0`.
</details>
Turns out this behaviour is configurable! Made the server emit zero values.

---

*[ui/styl/partials/layout.styl, line 540 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImpL0JyjPwrB_mOEOw:-KInN7054J_o2enzcK-R:1686763119) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/styl/partials/layout.styl#L540)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I'm saying this isn't equivalent. For example, if `.section` has `padding-top: 50px` the old code would override this, whereas the simplified code wouldn't.
</details>
This is moot in this PR - let's discuss in the PR to follow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945)*

**Comment by maxlang** [comment]
:lgtm:

<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I was just thinking of ways to find missing values.
</details>


---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/ts/models/metrics.ts, line 413 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-KImrnpNUtXx0WpBuc9Y:-KInPhvt1Ul7L7XwSY_h:677247605) ([raw file](https://github.com/cockroachdb/cockroach/blob/67f2b1f5d4702e6b8a244bb9d6307cce0b0c2eef/ui/ts/models/metrics.ts#L413)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Turns out this behaviour is configurable! Made the server emit zero values.
</details>
Yay!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6945#-:-KInS4jh5CSgzbI4reSZ:1417088721)*

**Pull request merged**
