### PR TITLE
roachtest: import-cancellation: use a fixed seed; smaller import

### LINKED ISSUE #90510: roachtest: import-cancellation failed
roachtest.import-cancellation [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7070913?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7070913?buildTab=artifacts#/import-cancellation) on master @ [a3b578466bcdcc5d2bbea628d33c337d87b9f4b8](https://github.com/cockroachdb/cockroach/commits/a3b578466bcdcc5d2bbea628d33c337d87b9f4b8):

```
test artifacts and logs in: /artifacts/import-cancellation/run_1
(import_cancellation.go:170).func2: output in run_132432.856474893_n1_workload_run_querybench: ./workload run querybench --db=csv --concurrency=1 --query-file=tpch --num-runs=3 --max-ops=66 {pgurl:1-6} --histograms=perf/stats.json --histograms-max-latency=8m20s returned: SSH_PROBLEM: exit status 255
(monitor.go:127).Wait: monitor failure: monitor task failed: t.Fatal() was called
(test_runner.go:1062).teardownTest: test timed out (4h0m0s)
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=32</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #90434 roachtest: import-cancellation failed [C-test-failure O-roachtest O-robot T-storage branch-release-22.2]
</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*import-cancellation.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20809

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, due to the randomness present in the test, there may be significant variance in test runs. In some situations, the nature of the random import cancellations may result in the test timing out. This makes the test flaky.

Use a fixed seed for the test's PRNG to make the test more deterministic.

Additionally, reduce the size of the overall import by lowering the number of files used to generate the `lineitem` table. This should also help stabilize the runtime.

Fix #90510.

Release note: None.

### CODE REVIEW

**Comment by nicktrav** [comment]
I've run this manually a couple times, and the runtime is ~3-3.5h.

**Comment by nicktrav** [comment]
The majority of the 3-3.5h runtime appears to be in the TPC-H query workload phase.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90547#-:-NFF3HuY2_vsgNuH9HOU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nicktrav)

___
*[`pkg/cmd/roachtest/tests/import_cancellation.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90547#-NF9ccUsyAWSmTLv8Qmd-r1-86:-NFF3IMA7-n2nKhhRXGS:b9b0xzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a09f8410bacfec27feee41770d950c3e6904bedc/pkg/cmd/roachtest/tests/import_cancellation.go#L86)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

It would be nice to revert this eventually. For now, I was hoping to get the test stable, and then we can dig into the query runtime issue.
</blockquote></details>

With this seed, do we get several import cancellations?

**Comment by nicktrav** [comment]
> With this seed, do we get several import cancellations?

We do. Here's an example run: https://teamcity.cockroachdb.com/viewLog.html?buildId=7134798&buildTypeId=Cockroach_Nightlies_RoachtestStress&tab=buildLog

I also just pushed another change to compute the table stats.

**Comment by nicktrav** [comment]
Pushed one more small tweak to reduce the number of TPC-H query runs. With that value at `3` (prior value), there were still some runs clipping the 4 hour timeout.

**Comment by nicktrav** [comment]
I kicked off three runs at this SHA [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=7153154&buildTypeId=Cockroach_Nightlies_RoachtestStress&tab=buildLog#_state=11178).

**Comment by nicktrav** [comment]
The two CI failures look unrelated. Landing.

TFTR!

bors r=jbowens

**Pull request merged**
