### PR TITLE
ccl, sql: add authZ handler for ldap groups retrieval

### PR DESCRIPTION
**Pull request by souravcrl**
informs https://github.com/cockroachdb/cockroach/issues/125087
fixes CRDB-39227
Epic CRDB-33829

This PR adds support for fetching LDAP groups info for sql user which is trying
to gain authorization for cockroach cluster via LDAP. This change will enable us
to assign appropriate role privileges for user on CRDB.

Release note(enterprise, security): We add support for authorization to CRDB
cluster via LDAP retrieving AD groups membership information for LDAP user to
enable us to appropriately assign role privileges on CRDB.

Example hba conf entry to support LDAP authZ configuration:
```
 # TYPE    DATABASE      USER           ADDRESS             METHOD             OPTIONS
 # Allow all users to connect to using LDAP authentication with search and bind
   host    all           all            all                 ldap               ldapserver=ldap.example.com ldapport=636 "ldapbasedn=ou=users,dc=example,dc=com" "ldapbinddn=cn=readonly,dc=example,dc=com" ldapbindpasswd=readonly_password ldapsearchattribute=uid "ldapsearchfilter=(memberof=cn=cockroachdb_users,ou=groups,dc=example,dc=com)" "ldapgrouplistfilter=(objectClass=groupOfNames)"
 # Fallback to password authentication for the root user
   host    all           root           0.0.0.0/0          password
```
Example to use for azure AD server:
```
SET cluster setting server.host_based_authentication.configuration = 'host    all           all            all                 ldap ldapserver=azure.dev ldapport=636 "ldapbasedn=OU=AADDC Users,DC=azure,DC=dev" "ldapbinddn=CN=Some User,OU=AADDC Users,DC=azure,DC=dev" ldapbindpasswd=my_pwd ldapsearchattribute=sAMAccountName "ldapsearchfilter=(memberOf=CN=azure-dev-domain-sync-users,OU=AADDC Users,DC=crlcloud,DC=dev)" "ldapgrouplistfilter=(objectCategory=CN=Group,CN=Schema,CN=Configuration,DC=crlcloud,DC=dev)"
host    all           root           0.0.0.0/0          password';
```

Post configuration CRDB cluster should be able to authorize users via LDAP
server if:
1. Users LDAP authentication attempt is successful, and it has the user's DN for
LDAP server.
2. `ldapgrouplistfilter` is properly configured, and it successfully syncs
groups of the user.

### CODE REVIEW

**Review by souravcrl — COMMENTED** [review]
I have moved some code from `authentication_ldap.go` to `pkg/ccl/ldapccl/ldap.go` and `authentication_ldap_test.go` to `ldap_test_util.go`. Hence number of lines are more than 1000 but total change is about 400 lines.

`ldapgrouplistfilter` is being used as HBA conf option. LMK if this works or we should go with `crdbgroupserachfilter` as discussed in here https://cockroachlabs.slack.com/archives/C06S9FMQKK9/p1722958194654509?thread_ts=1722856335.176709&cid=C06S9FMQKK9

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128498#-:-O458SPKBHE00zX5OmkD:bec8ate)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

**Review by pritesh-lahoti — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128498)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — COMMENTED** [review]
nice work! most of this looks good to me, but i just had a question: is there remaining work to hook up the LDAP groups to the privileges that are defined within CRDB?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128498#-:-O4lhGb74pZw-tBRVhTk:b-c139w1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`pkg/ccl/ldapccl/authentication_ldap.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128498#-O4lecFI9i0H2egHg9NU:-O4lecFJBcZfjarlbifW:b-lt0axy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a348e14c145add6c4976d26f24184d0e561a4998/pkg/ccl/ldapccl/authentication_ldap.go#L73)):*
> ```Go
> 	entry *hba.Entry,
> 	_ *identmap.Conf,
> ) (retrievedUserDN string, detailedErrorMsg redact.RedactableString, authError error) {
> ```

just wondering: should the retrievedUserDN by a `username.SQLUsername`, or is `string` ok?
___
*[`pkg/ccl/ldapccl/authentication_ldap.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128498#-O4ldvpe7F4sW-60h1GR:-O4ldvpe7F4sW-60h1GS:b-tlu685) ([raw file](https://github.com/cockroachdb/cockroach/blob/a348e14c145add6c4976d26f24184d0e561a4998/pkg/ccl/ldapccl/authentication_ldap.go#L106)):*
> ```Go
> 
> 	if err := authManager.validateLDAPAuthNOptions(); err != nil {
> 		return "", redact.Sprintf("error validating authN hba conf options for LDAP: %v", err),
> ```

super nit: for user-facing messages/errors like this, let's use `authentication` instead of `authN`. some of our users may not know the abbreviation.
___
*[`pkg/ccl/ldapccl/authorization_ldap.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128498#-O4leK_W4YBDPMMJ8Jlp:-O4leK_W4YBDPMMJ8Jlq:b-4z9pz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a348e14c145add6c4976d26f24184d0e561a4998/pkg/ccl/ldapccl/authorization_ldap.go#L73)):*
> ```Go
> 		return nil, "", err
> 	}
> 	if !st.Version.IsActive(ctx, clusterversion.V24_2) {
> ```

for authz, should this version be 24.3? we aren't backporting the authz changes for LDAP

**Review by souravcrl — COMMENTED** [review]
Thank you for reviewing this. Yes, we would need to fetch privileges for retrieved LDAP groups. I wasn't sure whether we wanted to do them during authN or later on. This would need changes to systemIdentity to be set to retrieved DN and making calls to FetchLDAPGroups whenever we want to resolve privileges via ldap groups. https://cockroachlabs.atlassian.net/browse/CRDB-41549 tracks next set of planned work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128498#-:-O4tPRxW10Sa0ACgfgO0:b8sjuv4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti and @rafiss)

___
*[`pkg/ccl/ldapccl/authentication_ldap.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128498#-O4lecFI9i0H2egHg9NU:-O4tR6zM1KL2WUazTe2-:b-jdoa0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a348e14c145add6c4976d26f24184d0e561a4998/pkg/ccl/ldapccl/authentication_ldap.go#L73)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just wondering: should the retrievedUserDN by a `username.SQLUsername`, or is `string` ok?
</blockquote></details>

I am now verifying the returned LDAP DN from LDAP server. I would be moving this code to another utility `FetchLDAPDN` to do this in authLDAP itself before verifier call and set the replacement Identity in line with other auth methods resolving the external system identity. This would need changing `authPipe.authDetails.SystemIdentity`. More on this in this comment https://github.com/cockroachdb/cockroach/blob/2aaeeb706cd706fe5dae79dba491c88d05ad6ce5/pkg/sql/pgwire/auth_methods.go#L809-L815
___
*[`pkg/ccl/ldapccl/authentication_ldap.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128498#-O4ldvpe7F4sW-60h1GR:-O4oTtRB-on40EcwFKXH:boz25d2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a348e14c145add6c4976d26f24184d0e561a4998/pkg/ccl/ldapccl/authentication_ldap.go#L106)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: for user-facing messages/errors like this, let's use `authentication` instead of `authN`. some of our users may not know the abbreviation.
</blockquote></details>

updated to use authentication for authN and authorization for authZ
___
*[`pkg/ccl/ldapccl/authorization_ldap.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128498#-O4leK_W4YBDPMMJ8Jlp:-O4tSkQBBj7cmbn1MBo3:b1gz55b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a348e14c145add6c4976d26f24184d0e561a4998/pkg/ccl/ldapccl/authorization_ldap.go#L73)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

for authz, should this version be 24.3? we aren't backporting the authz changes for LDAP
</blockquote></details>

updated to 24_3 for authZ changes for LDAP
___
*[`pkg/ccl/ldapccl/authorization_ldap.go` line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128498#-O4thyzZC-GtyEAIon6Y:-O4thyzZC-GtyEAIon6Z:b-ecdap0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bba84967781532c27d2618bf8b872ad9a223f00f/pkg/ccl/ldapccl/authorization_ldap.go#L73)):*
> ```Go
> //	 } else {
> //		  log.Infof(ctx, "LDAP authorization: retrieved ldap groups are %+v", ldapGroups)
> //	 }
> ```

This may always fail if retrieved user DN is not conforming to SqlUsername format. This currently works for and we are able to get the retrieved groups
```
cn=sourav sarangi (cb73d0a1),ou=aaddc users,dc=crlcloud,dc=dev
```

**Review by rafiss — APPROVED** [review]

**Comment by souravcrl** [comment]
TFTR!

bors r=pritesh-lahoti,rafiss

**Pull request merged**
