### PR TITLE
server: hash tenantID into ClusterID used in SQL exec

### LINKED ISSUE #74480: server: ClusterID non-unique for tenants
`ClusterID` is used in various places to distinguish separate clusters, such as when joining gossip, making RPCs, or when interacting with persisted state, including in external locations such as backups. For example, if a BACKUP that is backing up "table 53" resumes and finds some partially written files at the destination location, it needs to verify that those files were written by the same cluster, and thus contain data for the same "table 53" that it will be reading from.

Currently, tenant SQL pods are initialized with the host cluster's ClusterID, meaning all tenants hosted on the same cluster believe they have the same cluster ID. This is unfortunate, as means that it fails to distinguish those tenants from each other; we would not want one tenant resuming another's backup, or joining another's DistSQL flow. 

Fixing this isn't _quite_ as simple as just changing the value to which `ClusterID` is set in the pod process, since when interacting with the host cluster, such as when making KV requests, the tenant should still be using that host's ID, so we'll want a separate `ClusterID` used at the SQL level, which can be initialized from the host cluster ID, but made unique using the tenant's ID (e.g. by adding it or hashing it into the host's ID). We don't want to just use the tenant's ID on its own though, both because it isn't globally unique, but even if were, it might not be at times, e.g. if a tenant is restored on a second cluster, thus we want something that is unique to that tenant on that host cluster, such a generating a new random ID each time a tenant is created or restored in a host cluster, or just by hashing the numeric tenant ID into the host cluster ID.

Jira issue: CRDB-12101

### PR DESCRIPTION
**Pull request by dt**
Fixes #74480.

Prior to this patch, in a multi-tenant deployment the ClusterID value
visible to tenans was the same as the ClusterID for the storage
cluster.

This original design was defective because it prevented the
backup/restore subsystem from distinguishing backups made for
different tenants.

In this commit, we change the ClusterID for tenants to become a new
UUID that is the storage cluster's ClusterID with a hash of the
tenant's ID added to the lower 64 bits. This makes it so that two
tenants on the same storage cluster will observe different values when
calling ClusterID().

Release note (bug fix): Separate tenants now use unique values for the
internal field ClusterID. Previously separate tenants that
were hosted on the same storage cluster would be assigned the same
ClusterID.

Jira issue: CRDB-14750

### CODE REVIEW

**Comment by dt** [comment]
I looked at who all uses ClusterID in pkg/sql and it looks like there are really just two classes of use:
a) returning it in crdb_internal debugging/introspection builtins/tables, and
b) passing it to license checks for ccl features (partitioning, MR, etc) since license can be cluster-id scoped.

Case (a) seems ambivalent to what the value it -- it just shows you it.
Case (b) would potentially be interesting if tenants were checking license keys against specific cluster IDs during SQL feature usage calls, but they don't -- they toggle a licensed status once at startup using a separate mechanism and then the checks take a fast path seeing the toggle on (we should maybe do this everywhere, instead of needing to plumb around a cluster id to every check site).

Looking at pkg/ccl, it has a bunch more cases of (b) and then there's backup's case, where we really do need the semantics described here i.e. no two tenants ever have same value.

**Review by knz — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @RaduBerinde)

___
*[pkg/server/server_sql.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsdxbNQ2mF4fYr69wj1:-MsdxbNQ2mF4fYr69wj2:bv9ys49) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d0ad54b135dd55c55d288536618eb0991eaa188/pkg/server/server_sql.go#L528)):*
> ```Go
> 	// hash of tenant ID achieves this.
> 	if !codec.ForSystemTenant() {
> 		clusterIDForSQL = &base.ClusterIDContainer{}
> ```

Can you change this mechanism to switch to writing to `cfg.ClusterIDContainer`, thanks

**Review by knz — COMMENTED** [review]
It also might be worth adding a unit test that checks that for a single host cluster with two tenants, all 3 things (system tenant plus each of the two non-system tenants) see different cluster IDs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-:-MsdzC--DL1SlnDPqrZ8:b-lcb0pt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @RaduBerinde)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @RaduBerinde)

___
*[pkg/server/server_sql.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsdxbNQ2mF4fYr69wj1:-MsdzKha134juINCCf3V:b-6r9h88) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d0ad54b135dd55c55d288536618eb0991eaa188/pkg/server/server_sql.go#L528)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you change this mechanism to switch to writing to `cfg.ClusterIDContainer`, thanks
</blockquote></details>

Hm actually, can we talk about this, I don't exactly understand what is going on here.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/server/server_sql.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsdxbNQ2mF4fYr69wj1:-Mseb7NGB9dn93AuqMHp:bmcu0p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d0ad54b135dd55c55d288536618eb0991eaa188/pkg/server/server_sql.go#L528)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Hm actually, can we talk about this, I don't exactly understand what is going on here.
</blockquote></details>

I expanded the comment a bit as a starting point, since if it isn't clear to someone who talked it through previously from the diff, then I clearly needed to do more for future readers too. Does the expanded comment help at all?

**Review by knz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @RaduBerinde)

___
*[pkg/server/server_sql.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsdxbNQ2mF4fYr69wj1:-MsfYiX84zQ_5ysvm_f-:b-169klk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d0ad54b135dd55c55d288536618eb0991eaa188/pkg/server/server_sql.go#L528)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I expanded the comment a bit as a starting point, since if it isn't clear to someone who talked it through previously from the diff, then I clearly needed to do more for future readers too. Does the expanded comment help at all?
</blockquote></details>

yep that is good, thanks
___
*[pkg/server/server_sql.go, line 525 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsfXTDc3QmuJsxK2tGX:-MsfXTDc3QmuJsxK2tGY:b-8n97fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/197e58f8dd7f896c81b44e14d45ed5059de6c14d/pkg/server/server_sql.go#L525)):*
> ```Go
> 	// clusterIDForSQL is the cluster ID that SQL processes use.
> 	//
> 	// Not that this is separate from, but sometimes pointed at, the ClusterID in
> ```

nit: _Note_
___
*[pkg/server/server_sql.go, line 539 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsfXbLj1J52RqNsWZ61:-MsfXbLj1J52RqNsWZ62:b-1ez7tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/197e58f8dd7f896c81b44e14d45ed5059de6c14d/pkg/server/server_sql.go#L539)):*
> ```Go
> 	// interacting with processes on the same cluster or not. For example, when a
> 	// BACKUP job resumes writing to some external files, it is vital that be able
> 	// to verify that the data in those files what wriitten by the same cluster,
> ```

nit: _written_
___
*[pkg/server/server_sql.go, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsfXswm9nHpHKAgwd45:-MsfXswm9nHpHKAgwd46:bn0rjyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/197e58f8dd7f896c81b44e14d45ed5059de6c14d/pkg/server/server_sql.go#L545)):*
> ```Go
> 	// Thus for the non-system tenant, this ClusterID is derived from the unique
> 	// host cluster's ID, but with the TenantID hased into its lower bits to make
> 	// an ID that is unique to this tenant on this host cluster.
> ```

Can you also add:

```
Note: we are careful not to populate this per-tenant cluster ID into the
ClusterIDContainer referenced to by cfg.rpcContext, which is also the same
one referenced to by cfg.ClusterIDContainer, cfg.idProvider and several other places.
There are two reasons for this. The main reason is that these references to the
host cluster's cluster ID are used in logging and telemetry to ensure that
log/telemetry entries from tenants connected to the same host cluster
are identified as such, using a common cluster ID.
```

And I'd like to see these various assertions exercised in unit tests:
- check that the SQL idea of cluster ID indeed ends up different
-  check that cluster IDs included in the log entries (esp with output format JSON) remain the same

**Comment by knz** [comment]
@dt: can you file an issue and link it from the PR, then ping @mwang1026 on it? Michael and Jon need it for accounting purposes.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @RaduBerinde)

___
*[pkg/server/server_sql.go, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsfXswm9nHpHKAgwd45:-MsgOi-oB62NFZ2xC8Y4:byi7218) ([raw file](https://github.com/cockroachdb/cockroach/blob/197e58f8dd7f896c81b44e14d45ed5059de6c14d/pkg/server/server_sql.go#L545)):*
> main reason is that these references to the host cluster's cluster ID are used in logging and telemetry

er, I think the _main_ reason is that that rpcContext is what we use to make RPCs _to the host cluster_, so it needs to have a matching cluster ID in it. any logging / telemetry usage is secondary.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @RaduBerinde)

___
*[pkg/server/server_sql.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsdxbNQ2mF4fYr69wj1:-MsgQD9o5Pw6iR6UpiqP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d0ad54b135dd55c55d288536618eb0991eaa188/pkg/server/server_sql.go#L528)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yep that is good, thanks
</blockquote></details>

Done.
___
*[pkg/server/server_sql.go, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsfXswm9nHpHKAgwd45:-MsgQWQ5D7amuQTlsStb:bo9k769) ([raw file](https://github.com/cockroachdb/cockroach/blob/197e58f8dd7f896c81b44e14d45ed5059de6c14d/pkg/server/server_sql.go#L545)):*
> check that cluster IDs included in the log entries (esp with output format JSON) remain the same

Hm, I think we should log them both, separately. The tenant cluster -- that is, the sql pods -- have their cluster ID, and then they're hosted by/connected to some kv host cluster to provide their storage. We should log both of those, not just the latter.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @RaduBerinde)

___
*[pkg/server/server_sql.go, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-MsfXswm9nHpHKAgwd45:-MsicPjsE7A8JwwF5lbY:brapava) ([raw file](https://github.com/cockroachdb/cockroach/blob/197e58f8dd7f896c81b44e14d45ed5059de6c14d/pkg/server/server_sql.go#L545)):*
> I think the main reason is that that rpcContext is what we use to make RPCs to the host cluster

Yes you're right. Note I wrote "there are two reasons" but I only wrote one. You can insert the other first :)

> I think we should log them both, separately

What you did for the messages at server startup is a-ok :100: 

However this comment here (and the reason for me to insist this be documented) is that _separately_ we _also_ log the host cluster ID _on every log entry, all the time_ for the purpose of routing log data to the right collection point. That value needs to be correct and not tweaked. And that's also what deserves being validated in a unit test.

Maybe you can phrase this better than I did in the comment?

**Comment by knz** [comment]
Do you need help with moving this forward?

**Comment by dt** [comment]
Yeah, I had to push this to the back burner for some more urgent bug fixes and backports over the last couple weeks so I haven't gotten around to writing the relevant tests.

One thing to note: this currently _does_ change the cluster ID reported by a pod when it sends its usage telemetry, to the new tenant-unique cluster ID. I'm of two minds on this. 

On the one hand, I think this is Good/Ideal/Correct from an ideological point. Tenant A and Tenant B are distinct two distinct clusters from the point of view of using sql features, making tables, running types of queries, etc, and being on the same host cluster or not is irrelevant to that, so when reporting and collecting telemetry on that sql usage, reporting it under and tracking it under their separate cluster IDs, the same as if they were two separate dedicated clusters, seems most correct to me. If you want to know how many clusters have more than 1000 tables, counting up the distinct cluster IDs that reported >1k table count should tell you the right answer regardless of how many were dedicated, serverless on separate hosts, or serverless but on same host.  Now of course we might also want to look for trends correlated to host clusters -- does a certain host cluster skew some reported metric or something -- so we'd also want to include new, separate hostClusterID field in from serverless clusters, but from a principled view on what a unique cluster is, I think I like each tenant sending its telemetry using its individual cluster ID as its "cluster". 

On the other hand, the existing reporting has already been extended to handle distinct serverless clusters _not_ reporting under distinct cluster IDs, and instead has started treating the pair of `<cluster id, tenant id>` as a unique identifier for a logical cluster (perhaps the fact we had to go do that was a signal we actually should have been doing something like this PR, to give individual clusters their own IDs?). Thus, a more practical answer is to just have the telemetry reporter grab the _host_ cluster ID when generating reports to continue to conform to the existing expectation. This certainly seems expedient, if maybe less ideologically pure?

**Comment by knz** [comment]
let's ask @thtruo what a good design would be here.

**Comment by knz** [comment]
Discussed with @thtruo . 
For telemetry, we're moving away from the crdb-known ClusterID to identify clusters. 
Instead, (my understanding is that) the log collection pipeline is _adding_ the control plane's idea of the cluster's identity in the envelope of log messages. We also populate the tenant ID, and there may even be an "org ID" in the future.

If that is correct, then we're in the clear with making the cluster ID work the way you've defined here.

**Comment by dt** [comment]
Thanks for resolving that!

I feel like there's a similar argument to the one I made above to be made about the cluster ID in structured logging messages as well -- that each serverless tenant cluster should emit log messages tagged with its own unique cluster ID as the cluster, rather than the cluster ID of the host cluster it is attached to (which could go in a separate field, or be determined by looking at the high bits), but I see you implied otherwise in earlier comments here. I don't think I feel strongly enough to argue the point though, so I think I'd like to also leave that determination to server folks.

**Comment by pransudash** [comment]
Quick question here for my clarity: Is the proposed solution then to have clusterId be the same as the unique id used across the control plane and in crdb intrusion tables? Or would this hash of clusterId and tenantId result in a new id? If it's the latter, then telemetry logging will not be able to link events to specific clusters.

**Comment by knz** [comment]
> I feel like there's a similar argument to the one I made above to be made about the cluster ID in structured logging messages as well -- that each serverless tenant cluster should emit log messages tagged with its own unique cluster ID as the cluster, rather than the cluster ID of the host cluster it is attached to (which could go in a separate field, or be determined by looking at the high bits), but I see you implied otherwise in earlier comments here.

Yes, this flows from the discussion with Tommy, and invalidates my earlier arguments.

This makes me wonder how much we need to preserve the ~~host~~ storage cluster ID in SQL instances at all.

>  Is the proposed solution then to have clusterId be the same as the unique id used across the control plane and in crdb intrusion tables?

no, the opposite, however...

> If it's the latter, then telemetry logging will not be able to link events to specific clusters.

This is mistaken, if my understanding of the logging pipeline is right. @thtruo or @logston should be able to confirm this: I believe that the cluster ID of the underlying storage cluster is _added_ to telemetry messages alongside whichever value crdb has chosen.  (This addition is a feature I've requested a few months ago, due to a bug in crdb: it's possible for _some_ logging messages to fail to include a cluster ID when it originates in crdb, so we really appreciate that the log collector re-adds it regardless of what crdb does).

**Comment by knz** [comment]
@dt in light of these findings, how much remains on this PR?

**Comment by knz** [comment]
The remarks above were directed at @pransudash, not you. 

The PR as-is seems ok to me now, thanks to clarifying convos with @thtruo .  I was wondering how much work is needed to complete it (which, at this point, amounts mostly to making CI happy?)

**Comment by pransudash** [comment]
Got it, thanks for the clarification @knz and apologies if I caused any confusion @dt 😅 

I don't think I've ever seen the cluster id added to the envelope of any log events that are exported to the cockroach-telemetry-production GCP bucket (the cluster_id and crdb_cluster_id fields are always the same value), but if @thtruo is confident that we will be fine downstream, I will trust in that :)

**Comment by logston** [comment]
Pardon the delay here. 

> @thtruo or @logston should be able to confirm this: I believe that the cluster ID of the underlying storage cluster is added to telemetry messages alongside whichever value crdb has chosen

Correct, the host cluster ID is added to the message envelope. See here: -
- https://github.com/cockroachlabs/managed-service/blob/master/pkg/kube/kubecreate/logging/fluentbit/fluentbit.go#L262-L269
- https://github.com/cockroachlabs/managed-service/blob/master/pkg/kube/kubecreate/logging/fluentbit/fluentbit.go#L603-L604
- https://github.com/cockroachlabs/managed-service/blob/master/pkg/kube/kubecreate/logging/upsert.go#L66
- https://github.com/cockroachlabs/managed-service/blob/master/pkg/models/intrusion_crdb_cluster.go#L100

> We also populate the tenant ID

We _do not_ add the tenant id/name/etc to the telemetry envelope in the same way. We depend on a unique identifier for each tenant being present in the envelope produced before it exits CRDB (the SQL pod) via TCP logging. 

I'm not sure how the data is joined downstream (@pransudash for details) but replacing the UUID for the `cluster_id` field with a UUID of the logical tenant sounds like the correct move. @pransudash, Are you joining on `tenant_id`? If we are joining on `tenant_id` and that field is not going to be removed, I think you pipeline wouldn't need any changes, correct?

**Comment by pransudash** [comment]
@logston I agree that the `cluster_id` being a UUID is the right thing, I was just hoping that the UUID would match the one created by intrusion here (from the same model you linked): https://github.com/cockroachlabs/managed-service/blob/master/pkg/models/intrusion_crdb_cluster.go#L39

Downstream data consumption will not be affected as long as the `crdb_cluster_id` and `tenant_id` still come through. It would just be an added bonus for us if the UUID was same across logs and the IntrusionCrdb struct.

**Comment by knz** [comment]
The formula used by @dt here (adding storage cluster ID + tenant ID together as a uint128) can be replicated in the CC control plane, I think.

**Comment by logston** [comment]
@pransudash Ah, that's the PK for the model and is a purely intrusion concept. The CRDB pods (KV or SQL) do not know about that value and thus can not export it. But I can add that to the envelope in the same way that we add `crdb_cluster_id`. I'll try to do that in the same pass as adding the OrgID. Please note that adding the host cluster's intrusion PK to the envelope will be easy. But add the tenant cluster's PK (from `intrusion_tenant_clusters`) will be very difficult and we should use another means of identifying tenant clusters (which we already do via the `tenant_id` field in the logging envelope). 

> The formula used by @dt here (adding storage cluster ID + tenant ID together as a uint128) can be replicated in the CC control plane, I think.

Great point. We could use the same tooling that we use to populate `crdb_cluster_id` to populate it with the joined ID.

**Comment by knz** [comment]
rebased. will now wait to see what CI says before merging.

**Review by knz — APPROVED** [review]
Ok so as per my tweaks to the code:

- the fields "storage cluster ID" and "logical cluster ID" are now properly named throughout the code, especially in the locations where both are important side-by-side.

- the diagnostic upload via HTTP (not telemetry logging) now uses the storage-level cluster ID in the `uuid` query parameter, and the per-tenant cluster ID in the (new) `logical_uuid` query parameter.

  I am not sure the PM team actually cares about this (I don't think we do HTTP diagnostics report for multitenant) so I won't make more noise on this topic.

> Reviewed 1 of 3 files at r4, 40 of 48 files at r5, 17 of 17 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74005#-:-MzuqbZo0OFOZV990lK_:b-js3b6l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @stevendanna)

**Comment by knz** [comment]
all right, this seems good to go now.

bors r+

**Comment by knz** [comment]
@dt I assume we want this backported to 22.1?

**Comment by dt** [comment]
Yep, that'd be my vote (the linked issue is marked GA blocker)

**Comment by dt** [comment]
Also, thank you for taking this over!!!

**Comment by knz** [comment]
blathers backport 22.1

**Pull request merged**
