### PR TITLE
sql: add tracing span for index recommendation

### PR DESCRIPTION
**Pull request by rytaft**
Informs #131544

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135188#-:-OBl59q599eRlv7Xqm-j:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by michae2 — COMMENTED** [review]
I think starting at https://github.com/cockroachdb/cockroach/blob/34442261e321be0582f48371fd1d345a8c0c65d3/pkg/sql/plan_opt.go#L1039 you'll need to use the old ctx from before the call to `EnsureChildSpan` to avoid the new ctx leaking out of `makeQueryIndexRecommendation`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135188#-:-OBlTe7o3ev6DRxyeyPz:bj3rzu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — COMMENTED** [review]
Nice find, thanks @michae2! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135188#-:-OBlplO5AcyAT6A9kLkW:ba27npn)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135188#-:-OBmPL4aBoyGrsqnOovv:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Comment by rytaft** [comment]
TFTRs!

bors r+

**Pull request merged**
