### PR TITLE
sql: disable READ COMMITTED syntax by default

### LINKED ISSUE #107980: sql: add a cluster setting to opt into read committed syntax
In v23.1, using READ COMMITTED would always be implicitly promoted to SERIALIZABLE.

After the v23.2 changes for READ COMMITTED, we should make sure that this is still the case, since it is still a preview feature. An example for why we need it is since we have banned schema changes under READ COMMITTED, statements that previously worked in 23.1 could suddenly start failing once the upgrade is finalized and READ COMMITTED transactions are used.

Some tools (e.g. DMS in https://github.com/cockroachdb/cockroach/issues/107683), use READ COMMITTED.

To support them, we will add a new cluster setting that preserves the 23.1 behavior of automatically promoting READ COMMITTED to SERIALIZABLE. That setting should be on by default.

** Example of what this setting would do **
```
-- name of the setting to be determined later.
SET CLUSTER SETTING sql.txn.always_use_serializable = true;

BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
SHOW transaction_isolation;
-- returns SERIALIZABLE. this is the 23.1 behavior.
COMMIT;


SET CLUSTER SETTING sql.txn.always_use_serializable = false;

BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
SHOW transaction_isolation;
-- returns READ COMMITTED.
COMMIT;
```

Jira issue: CRDB-30278

Epic CRDB-26546

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/107980

Release note (sql change): The cluster setting
sql.txn.read_committed_syntax.enabled was added. It defaults to false. When set to true, the following statements will configure transactions to run under READ COMMITTED isolation, rather than being automatically interpeted as SERIALIZABLE.
- BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED
- SET TRANSACTION ISOLATION LEVEL READ COMMITTED
- SET default_transaction_isolation = 'read committed'
- SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED

This setting is added since READ COMMITTED transactions are a preview
feature, so usage of it is opt-in for v23.2. In a future CockroachDB major
version, this setting will change to default to true.

### CODE REVIEW

**Review by chrisseto — APPROVED** [review]
LGTM! Would we want to add a note in the commit message that this is primarily for backward compatibility? The referenced issue notes so but it may be more difficult to follow anywhere but github.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110624#-:-NeJ4FWZ6jDEjE95Phx_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @michae2, @rachitgsrivastava, and @rafiss)

___
*[`pkg/sql/conn_executor.go` line 3422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110624#-NeJ3u79BmBG2OM_WmHS:-NeJ3u79BmBG2OM_WmHT:b-tf9090) ([raw file](https://github.com/cockroachdb/cockroach/blob/479df9a955c5e338d94ed2a3e24bc34a060d1028/pkg/sql/conn_executor.go#L3422)):*
> ```Go
> var allowReadCommittedIsolation = settings.RegisterBoolSetting(
> 	settings.TenantWritable,
> 	"sql.txn.read_committed_syntax.enabled",
> ```

Should this just be "sql.txn.read_committed.enabled" to parallel the setting above?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110624)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @michae2, @nvanbenschoten, and @rachitgsrivastava)

___
*[`pkg/sql/conn_executor.go` line 3422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110624#-NeJ3u79BmBG2OM_WmHS:-NeJBA7k4FtUPF9Uy6rG:betz489) ([raw file](https://github.com/cockroachdb/cockroach/blob/479df9a955c5e338d94ed2a3e24bc34a060d1028/pkg/sql/conn_executor.go#L3422)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this just be "sql.txn.read_committed.enabled" to parallel the setting above?
</blockquote></details>

i think the `syntax` in the name might make it more clear that this setting is just influencing how syntax is interpreted. i will change the snapshot setting name to match. (nb: that snapshot setting is non-public)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110624#-:-NeJSUAZDGUi5GsdSAB6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @michae2, and @rachitgsrivastava)

**Comment by rafiss** [comment]
> LGTM! Would we want to add a note in the commit message that this is primarily for backward compatibility? The referenced issue notes so but it may be more difficult to follow anywhere but github.

missed that comment before. i have added a sentence mentioning that RC is a preview feature.

tftrs!

bors r=chrisseto,nvanbenschoten

**Comment by rafiss** [comment]
NB: the name was changed in https://github.com/cockroachdb/cockroach/pull/112920

**Pull request merged**
