### PR TITLE
backupccl: support BACKUP to multiple destinations by locality

### PR DESCRIPTION
**Pull request by thoszhang**
This PR adds support for specifying multiple backup destinations in `BACKUP`
with a mapping of node locality to destination, allowing for partitioned
backups where each node writes files only to the destination store that matches
its locality. It also adds support for `RESTORE` to read these partitioned
backups, given a list of URIs that together contain all files for a single
backup (which may be different from the original URIs).

A partitioned backup is specified by a list of URIs, each of which has a
`COCKROACH_LOCALITY` URL param whose value is either `default` or a
(URL-encoded) locality KV such as `region=us-east`. At least one
`COCKROACH_LOCALITY` must be `default`. Example:
```
BACKUP DATABASE foo TO ('s3://us-east-bucket?COCKROACH_LOCALITY=default', 's3://us-west-bucket?COCKROACH_LOCALITY=region%3Dus-east')
```
Nodes will write files to the store whose locality value matches their own node
localities, with a preference for more specific values in the locality
hierarchy, and fall back to `default` if there is no match. The `BACKUP`
manifest is written to the "default" export destination. The same backup can be
restored with
```
RESTORE DATABASE foo FROM ('s3://us-east-bucket', 's3://us-west-bucket')

```
Note that the first URI supplied must be for the store containing the `BACKUP`
manifest.

A list of multiple URIs (surrounded by parentheses) specifying a partitioned
backup can also be used in place of any incremental backup URI in `RESTORE`. If
the original backup was an incremental backup, it can be restored using
```
RESTORE DATABASE foo FROM 's3://other-full-backup-uri', ('s3://us-east-bucket', 's3://us-west-bucket')
```
A new symbol in the grammar, `partitioned_backup`, corresponding
to one or more URIs, was added to replace the previous single URI in the
`BACKUP` and `RESTORE` statements.

In a partitioned backup, a mapping of locality KV to export destination config
is sent in a new field in `ExportRequest`, `storage_by_locality_kv`. When
`ExportRequest`s are evaluated, if the mapping is set, the file will be written
to the matching export destination. `ExportResponse_File`s now also contain the
matching locality KV, which uniquely maps to an export destination. That
locality KV is stored on `File`s in the `BackupDescriptor`.

In addition to the main `BACKUP` manifest, at the end of the backup, a file
(named `BACKUP_PART_<id>_<key=value>`) containing a serialized
`GeodistributedPartialBackupDescriptor` is written to every other export
destination, containing the corresponding locality KV that was specified for
the backup. For the above example, the file structure will look like
```
- s3://us-east-bucket
    - BACKUP
    - 1.sst (and so on)
- s3://us-west-bucket
    - BACKUP_PART_1_region=us-east
    - 2.sst (and so on)
```
A list of these `BACKUP_PART_something` filenames is also stored on the
`BackupDescriptor`.

On `RESTORE`, we try to read the main `BACKUP` manifest from each supplied URI,
then try to read and locate each `BACKUP_PART` file based on the list in
`BackupDescriptor`. From that search, we recover the mapping of original
locality KVs to current file URIs. Since each `File` in the `BackupDescriptor`
has its original locality KV, we can determine the URIs at which to find each
file. The locality-to-URI maps (one per full/incremental backup) are used to
specify the correct URI for `ImportRequest`s.

Further work needs to be done to support a true locality-aware `RESTORE` where
each node reads only from a store matching its locality. This might also
involve backing up zone configurations and taking those into account when
restoring.

Release note (enterprise change): Add support for locality-aware backups across
multiple backup destinations.

### CODE REVIEW

**Comment by lucy-zhang** [comment]
I still need to write unit tests for some of the more complicated logic, like the functions that build the locality mapping, the locality kv matching, etc.

I also don't have tests yet that check that SSTs actually get written to where we expect (though I've done things like manually set zone configs to put the entire database in one zone and then ensure that nothing gets written elsewhere).

**Review by dt — APPROVED** [review]
Nice! Exciting stuff!

:lgtm: overall.

A few *minor* bikeshed-y naming nits, a couple inline, plus one general one: I might suggest we should refer to it as "Partitioned" backup instead of "Geodistributed" backup in the code/comments/protos, just since the partitioning isn't necessarily geographic (could just be separate AZ, DCs or data-value/latency hardware tiers).

> Reviewed 19 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-:-LlEUGre9-uD34dbVQpD:b8yrpgx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)

___
*[pkg/ccl/backupccl/backup.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlEUwNMBLi8a3QI55-G:-LlEUwNMBLi8a3QI55-H:b-h6up1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup.go#L65)):*
> ```Go
> const (
> 	backupOptRevisionHistory = "revision_history"
> 	localityURLParam         = "LOCALITY"
> ```

I wonder if, since this is going in the actual URI, if we should prefix it? I guess it might get a little clunky.
___
*[pkg/ccl/backupccl/backup.go, line 822 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlH8hIDEwHaLkejgXyV:-LlH8hIDEwHaLkejgXyW:b1tn237) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup.go#L822)):*
> ```Go
> 			backupDesc.LocalityKVs = append(backupDesc.LocalityKVs, kv)
> 			// TODO (lucy): hash/escape these filenames
> 			filename := fmt.Sprintf("%s_%s", BackupDescriptorName, kv)
> ```

we could throw a `PARTIAL_` prefix or `_PART_`in the middle here just to make it a little clearer what we're looking at.
___
*[pkg/ccl/backupccl/backup.go, line 1396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlEVn8P3gZQ-OhH_1x6:-LlEVn8P3gZQ-OhH_1x7:b-w7bedr) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup.go#L1396)):*
> ```Go
> 				localityURLParam,
> 			)
> 		}
> ```

should we reset `uri` to be the string serialization of `parseURI` _after deleting the locality parameter?_  I could imagine the export storage providers might not all like the extra parameter (e.g. the HTTP one?)

that makes me wonder if we use use a cockroach-specific parameter name to make a collision less likely, but I guess that could get clunky.
___
*[pkg/ccl/backupccl/backup.proto, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlEYHVD5BJ9nBeo0OWT:-LlEYHVD5BJ9nBeo0OWU:b-w4bkea) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup.proto#L99)):*
> ```protobuf
> 
>   bytes geodistributed_backup_id = 18 [(gogoproto.nullable) = false,
>                                       (gogoproto.customname) = "GeodistributedBackupID",
> ```

I think this could just be "ID" and we could just always set it -- in regular and partitioned backups. I don't know exactly everywhere it might be useful but I imagine it could have broader use.
___
*[pkg/ccl/backupccl/backup_test.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlImISs8V6NBwZjeXJ5:-LlImISs8V6NBwZjeXJ6:bqthil6) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup_test.go#L257)):*
> ```Go
> 		localFoo2,
> 		localFoo3,
> 	}
> ```

Do we need to do some lease transfers here to ensure we actually have leaseholders in each locality?

It might also be nice to go ahead and bind the path the tempdir that `backupRestoreTestSetup` is returning above, and then assert that each of the subdirs is has an SST in it.
___
*[pkg/ccl/backupccl/backup_test.go, line 1755 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlEfa7XDvhrPqams0xQ:-LlEfa7XDvhrPqams0xR:b-4hegep) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup_test.go#L1755)):*
> ```Go
> 			sqlDBRestore.Exec(t, fmt.Sprintf(`RESTORE data.bank FROM %s`, from.String()))
> 
> 			testutils.SucceedsSoon(t, func() error {
> ```

huh, just curious: I'd have expected it to work as soon as the restore finished, on which the line above blocked? any idea why we need the loop?
___
*[pkg/ccl/backupccl/restore.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlEiQ7x3YncEJEqBX6k:-LlEiQ7x3YncEJEqBX6l:b-4a7ql9) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/restore.go#L119)):*
> ```Go
> 	}
> 	if defaultURI == "" {
> 		return "", info, errors.Errorf("%s file not found", BackupDescriptorName)
> ```

hm, I think this could be confusing -- if your AWS keys are wrong, every request will fail, but we'll assume it was just missing and then this error won't really help you find the problem. 

I wonder if we should require that the first bucket is the default and just look for the desc there (and only there)?

**Review by thoszhang — COMMENTED** [review]
I updated the code/protos to use `partitioned` everywhere. I also updated the commit message to fix some errors (e.g., there's no `BACKUP_default` file).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-:-LlYmHCp1fiUwhyfU5fW:b-a26y15)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt)

___
*[pkg/ccl/backupccl/backup.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlEUwNMBLi8a3QI55-G:-LlYEKBc1oP_gH3NLwWP:bdmno8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup.go#L65)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I wonder if, since this is going in the actual URI, if we should prefix it? I guess it might get a little clunky.
</blockquote></details>

I renamed it `COCKROACH_LOCALITY`. Is that what you had in mind?
___
*[pkg/ccl/backupccl/backup.go, line 822 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlH8hIDEwHaLkejgXyV:-LlYEbUCClVhiGeYpPUD:b-zbtm2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup.go#L822)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

we could throw a `PARTIAL_` prefix or `_PART_`in the middle here just to make it a little clearer what we're looking at.
</blockquote></details>

Done. (I also updated the filename format).
___
*[pkg/ccl/backupccl/backup.go, line 1396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlEVn8P3gZQ-OhH_1x6:-LlYEewK1EC8RhnBwBNf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup.go#L1396)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

should we reset `uri` to be the string serialization of `parseURI` _after deleting the locality parameter?_  I could imagine the export storage providers might not all like the extra parameter (e.g. the HTTP one?)

that makes me wonder if we use use a cockroach-specific parameter name to make a collision less likely, but I guess that could get clunky.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup.proto, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlEYHVD5BJ9nBeo0OWT:-LlYEquS1zuB2rEDrnKC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup.proto#L99)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think this could just be "ID" and we could just always set it -- in regular and partitioned backups. I don't know exactly everywhere it might be useful but I imagine it could have broader use.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_test.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlImISs8V6NBwZjeXJ5:-LlYa5l81wpqmXIinoeT:b-brgcej) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup_test.go#L257)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Do we need to do some lease transfers here to ensure we actually have leaseholders in each locality?

It might also be nice to go ahead and bind the path the tempdir that `backupRestoreTestSetup` is returning above, and then assert that each of the subdirs is has an SST in it.
</blockquote></details>

Currently `backupRestoreTestSetup` is creating 10 splits and scattering the ranges. Will that randomly select a node for each range leaseholder, or is there something that tries to distribute the leaseholders evenly?

I did add a check that at least 1 SST exists in each subdirectory, but it might be too flaky as is.
___
*[pkg/ccl/backupccl/backup_test.go, line 1755 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlEfa7XDvhrPqams0xQ:-LlYPnrL2lVbl_qybwBa:b-pwc69e) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup_test.go#L1755)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

huh, just curious: I'd have expected it to work as soon as the restore finished, on which the line above blocked? any idea why we need the loop?
</blockquote></details>

Yeah, I think you're right (I copied this from the other incremental backup test, but I don't see any reason why we need it in either place). I removed both usages.
___
*[pkg/ccl/backupccl/restore.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlEiQ7x3YncEJEqBX6k:-LlYVk6h81uLXyN4b5I-:b1c5j0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/restore.go#L119)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

hm, I think this could be confusing -- if your AWS keys are wrong, every request will fail, but we'll assume it was just missing and then this error won't really help you find the problem. 

I wonder if we should require that the first bucket is the default and just look for the desc there (and only there)?
</blockquote></details>

Yeah, that's reasonable. Done.

**Review by dt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39250)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @lucy-zhang)

___
*[pkg/ccl/backupccl/backup_test.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlImISs8V6NBwZjeXJ5:-LlYoT_H-q2oNZ6ZbxzT:b1hbwx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup_test.go#L257)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Currently `backupRestoreTestSetup` is creating 10 splits and scattering the ranges. Will that randomly select a node for each range leaseholder, or is there something that tries to distribute the leaseholders evenly?

I did add a check that at least 1 SST exists in each subdirectory, but it might be too flaky as is.
</blockquote></details>

I'm not sure -- I think you might need to `ALTER TABLE RELOCATE`  to ensure at least one leaseholder ends up on each node, but I'm not positive. Could try running stress to confirm, though IIRC the test setup alone is pretty slow. See what the CI that stresses new tests thinks of it I guess?

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39250)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt)

___
*[pkg/ccl/backupccl/backup_test.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39250#-LlImISs8V6NBwZjeXJ5:-Llc2NTM1yGgOnz0Ru_e:b-bjppue) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e1f7c3777359b0d40d82f2fc6b5af7be02e64b/pkg/ccl/backupccl/backup_test.go#L257)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm not sure -- I think you might need to `ALTER TABLE RELOCATE`  to ensure at least one leaseholder ends up on each node, but I'm not positive. Could try running stress to confirm, though IIRC the test setup alone is pretty slow. See what the CI that stresses new tests thinks of it I guess?
</blockquote></details>

I added some `ALTER TABLE RELOCATE`s.

**Pull request merged**
