### PR TITLE
stats: implement SHOW STATISTICS

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: implement SHOW STATISTICS statement

Updates #20323.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @knz, @lego for the grammar part and delayedNode usage

**Comment by lego** [comment]
Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/show_stats.go, line 59 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DcIurIiMz6WMg6Mxy:-L-DcIurIiMz6WMg6Mxz:b-1a9ifd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L59)):*
> ```Go
> 
> 			ie := InternalExecutor{LeaseManager: p.LeaseMgr()}
> 			rows, err := ie.QueryRowsInTransaction(
> ```

I believe you can use `p.queryRows(ctx, query, args...)` instead :). I think this is more appropriate here, but I'm no expert.

---

*[pkg/sql/show_stats.go, line 76 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-D_38zPISW_HSJBxN3:-L-D_38zPISW_HSJBxN4:b8ytvqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L76)):*
> ```Go
> 				return nil, err
> 			}
> 			v := p.newContainerValuesNode(columns, 0)
> ```

While I see how you've achieved what you wanted to do, post-process results, I'm not quite sure if this is the best way to do it. It certainly works but all of the row fetching and gathering is happening during the final steps of query planning as opposed to during execution (and it won't stream results?). I'm certainly not the one to call the shots on what is most appropriate here though. Looks good otherwise :)

And to clarify, the post-processing your doing is:
1) You're translating the column IDs to human readable column names
2) Getting the histogram column iff it is not null.

Correct? I'd add a comment above the `delayedNode` explaining why and what is being done here.

---

*[pkg/sql/show_stats.go, line 100 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-Da5Z3mUjuQ2B5sKpV:-L-Da5Z3mUjuQ2B5sKpW:b66ocjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L100)):*
> ```Go
> 				histogram := tree.DNull
> 				if r[7] == tree.DBoolTrue {
> 					histogram = r[0]
> ```

I don't quite follow this. If `HISTOGRAM IS NOT NULL` is true, we set `histogram` to be `statisticID`? Where is the histogram coming from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360)*

**Comment by RaduBerinde** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/show_stats.go, line 59 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DcIurIiMz6WMg6Mxy:-L-DdS-yQgkpeeqKA8IM:b-k5iea7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L59)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

I believe you can use `p.queryRows(ctx, query, args...)` instead :). I think this is more appropriate here, but I'm no expert.
</blockquote></details>

Ah, cool. Fixed the place I copied it from too.

---

*[pkg/sql/show_stats.go, line 76 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-D_38zPISW_HSJBxN3:-L-DdxNB08wZ6iOOKeQI:bgd5z8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L76)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

While I see how you've achieved what you wanted to do, post-process results, I'm not quite sure if this is the best way to do it. It certainly works but all of the row fetching and gathering is happening during the final steps of query planning as opposed to during execution (and it won't stream results?). I'm certainly not the one to call the shots on what is most appropriate here though. Looks good otherwise :)

And to clarify, the post-processing your doing is:
1) You're translating the column IDs to human readable column names
2) Getting the histogram column iff it is not null.

Correct? I'd add a comment above the `delayedNode` explaining why and what is being done here.
</blockquote></details>

Added a comment. Yeah, I'm not very sure this is the right way, but I definitely see other `delayedNode`s running queries in the constructor.

---

*[pkg/sql/show_stats.go, line 100 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-Da5Z3mUjuQ2B5sKpV:-L-De6awYYOH5rWIzVca:bk7flqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L100)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

I don't quite follow this. If `HISTOGRAM IS NOT NULL` is true, we set `histogram` to be `statisticID`? Where is the histogram coming from?
</blockquote></details>

Yeah, we return a "handle" that can be used with a SHOW HISTOGRAM command (TBD)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360)*

**Comment by lego** [comment]
:lgtm:

---

Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/show_stats.go, line 76 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-D_38zPISW_HSJBxN3:-L-Dj_y5NR2LtPJfFISr:brenj9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L76)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Added a comment. Yeah, I'm not very sure this is the right way, but I definitely see other `delayedNode`s running queries in the constructor.
</blockquote></details>

Thanks for doing that!

I'm not too concerned with using `delayedNode` at the moment as it's something that we can easily change down the road.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-:-L-DjmjBhP6dPIkJ9LjK:bnfp4nl)*

**Comment by knz** [comment]
Overall approach OK, but you're leaking memory on errors.

---

Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 4 of 5 files at r3.
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/show_stats.go, line 54 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DlNB7a3TV08zrIpAx:-L-DlNB7a3TV08zrIpAy:bi9lplq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L54)):*
> ```Go
> 				return nil, err
> 			}
> 			if err := p.CheckAnyPrivilege(desc); err != nil {
> ```

move the descriptor extraction and privilege check in the constructor above

---

*[pkg/sql/show_stats.go, line 76 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DlT7QKCu2MB7a8jj9:-L-DlT7QKCu2MB7a8jjA:biuiw7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L76)):*
> ```Go
> 				return nil, err
> 			}
> 			v := p.newContainerValuesNode(columns, 0)
> ```

You must ensure that `v.Close(ctx)` is called on every error return path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-:-L-Dlb68IScUrBlO2ERd:b-6vptpy)*

**Comment by knz** [comment]
Also I think you need to squash the last 2 commits into one.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-:-L-DlmX1Qo5CA2nCShaI:bupkpaf)*

**Comment by rytaft** [comment]
Reviewed 5 of 5 files at r2, 4 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/show_stats.go, line 43 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DlVGAj2vVqgfZz6RM:-L-DitHAtPf8GGYgvdCo:b4pp194) ([raw file](https://github.com/cockroachdb/cockroach/blob/73b3573ac9dfb206c1d57b347a5b95e1d5849af7/pkg/sql/show_stats.go#L43)):*
> ```Go
> 		{Name: "Distinct Count", Typ: types.Int},
> 		{Name: "Null Count", Typ: types.Int},
> 		{Name: "Histogram", Typ: types.Int},
> ```

Do we really want to hide the Statistic ID if there is no histogram?  Are there any scenarios where someone would want to know this ID without the histogram?

Maybe instead of calling the field Histogram, call it "Histogram ID" or something like that.

---

*[pkg/sql/show_stats.go, line 81 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-Dk87nXkRmz68TJGeS:-L-Dk87nXkRmz68TJGeT:b-dmu791) ([raw file](https://github.com/cockroachdb/cockroach/blob/73b3573ac9dfb206c1d57b347a5b95e1d5849af7/pkg/sql/show_stats.go#L81)):*
> ```Go
> 			v := p.newContainerValuesNode(columns, 0)
> 			for _, r := range rows {
> 				if len(r) != 8 {
> ```

Would be nice to name the indices and length of results to avoid magic numbers, here and below.  E.g.:

```
const (
	statisticsIDIndex = iota
	nameIndex
	columnIDsIndex
	createdAtIndex
	rowCountIndex
	distinctCountIndex
	nullCountIndex
	hasHistogramIndex
	statsLen
)
```

Feel free to shorten the names....

---

*[pkg/sql/logictest/testdata/logic_test/distsql_stats, line 50 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DmmxYYPB24BD6nVGR:-L-DmmxYYPB24BD6nVGS:bmiifu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/73b3573ac9dfb206c1d57b347a5b95e1d5849af7/pkg/sql/logictest/testdata/logic_test/distsql_stats#L50)):*
> ```
> 
> query TTIII colnames
> SELECT "Name", "Columns", "Row Count", "Distinct Count", "Null Count" FROM [SHOW STATISTICS FOR TABLE data]
> ```

Can you add test cases for multiple columns, no name, and has/does not have histogram?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/show_stats.go, line 40 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-Dok5VWI4aaM3ItjLb:-L-Dok5VWI4aaM3ItjLc:b7hz5jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/73b3573ac9dfb206c1d57b347a5b95e1d5849af7/pkg/sql/show_stats.go#L40)):*
> ```Go
> 		{Name: "Columns", Typ: types.String},
> 		{Name: "Created At", Typ: types.Timestamp},
> 		{Name: "Row Count", Typ: types.Int},
> ```

oh man I totally missed that the first time:

no no no no please no spaces and if possible no capitals in the column names. It hurts soo much the usability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/show_stats.go, line 40 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-Dok5VWI4aaM3ItjLb:-L-DpMeXwdJyL-PHmN1E:b-hcilgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/73b3573ac9dfb206c1d57b347a5b95e1d5849af7/pkg/sql/show_stats.go#L40)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

oh man I totally missed that the first time:

no no no no please no spaces and if possible no capitals in the column names. It hurts soo much the usability.
</blockquote></details>

Fixing, I went by some existing example (show constraints). Should I also rename the columns of the system table (they're camelCased)? Though other system tables have them camelCased. Is there some general guidance on these things?

---

*[pkg/sql/show_stats.go, line 43 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DlVGAj2vVqgfZz6RM:-L-DocY3OzTnfMcflO3y:b-adks8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/73b3573ac9dfb206c1d57b347a5b95e1d5849af7/pkg/sql/show_stats.go#L43)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do we really want to hide the Statistic ID if there is no histogram?  Are there any scenarios where someone would want to know this ID without the histogram?

Maybe instead of calling the field Histogram, call it "Histogram ID" or something like that.
</blockquote></details>

The command is intended for visual inspection, I figured the stat ID doesn't help. It's still available from the system table if really necessary.

Good idea, renaming the column

---

*[pkg/sql/show_stats.go, line 81 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-Dk87nXkRmz68TJGeS:-L-DqQ-pRZ8eH3pnP_5-:b-5cxqva) ([raw file](https://github.com/cockroachdb/cockroach/blob/73b3573ac9dfb206c1d57b347a5b95e1d5849af7/pkg/sql/show_stats.go#L81)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Would be nice to name the indices and length of results to avoid magic numbers, here and below.  E.g.:

```
const (
	statisticsIDIndex = iota
	nameIndex
	columnIDsIndex
	createdAtIndex
	rowCountIndex
	distinctCountIndex
	nullCountIndex
	hasHistogramIndex
	statsLen
)
```

Feel free to shorten the names....
</blockquote></details>

Nice, I like it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/show_stats.go, line 40 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-Dok5VWI4aaM3ItjLb:-L-DskAZtBlx8WdzoF3w:b-kaohwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/73b3573ac9dfb206c1d57b347a5b95e1d5849af7/pkg/sql/show_stats.go#L40)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Fixing, I went by some existing example (show constraints). Should I also rename the columns of the system table (they're camelCased)? Though other system tables have them camelCased. Is there some general guidance on these things?
</blockquote></details>

system tables are still free-for-all with casing, although we've been disciplined to avoid spaces.

SHOW tables *should* avoid spaces and capitals, but we've only decided so relatively recently (1.1 release) and some older SHOW outputs are already legacy (used in ORM drivers we've already let loose) so we can't change them any more. We should be careful for the new ones though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360)*

**Comment by RaduBerinde** [comment]
Review status: 9 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/show_stats.go, line 54 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DlNB7a3TV08zrIpAx:-L-DrXkgQk_Fsx73jXeV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L54)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

move the descriptor extraction and privilege check in the constructor above
</blockquote></details>

Done.

---

*[pkg/sql/show_stats.go, line 76 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DlT7QKCu2MB7a8jj9:-L-Drj3O5wU7uTPP_x0p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d144893f019311420ef0f60ac358406c15a0c/pkg/sql/show_stats.go#L76)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You must ensure that `v.Close(ctx)` is called on every error return path.
</blockquote></details>

Done.

---

*[pkg/sql/show_stats.go, line 40 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-Dok5VWI4aaM3ItjLb:-L-Dtlm3T7Fbu1DJISCh:bcilue1) ([raw file](https://github.com/cockroachdb/cockroach/blob/73b3573ac9dfb206c1d57b347a5b95e1d5849af7/pkg/sql/show_stats.go#L40)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

system tables are still free-for-all with casing, although we've been disciplined to avoid spaces.

SHOW tables *should* avoid spaces and capitals, but we've only decided so relatively recently (1.1 release) and some older SHOW outputs are already legacy (used in ORM drivers we've already let loose) so we can't change them any more. We should be careful for the new ones though.
</blockquote></details>

:+1: Updated to lower_case. Thanks!

---

*[pkg/sql/logictest/testdata/logic_test/distsql_stats, line 50 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DmmxYYPB24BD6nVGR:-L-DrpgZ4fzs55jHncO2:b859ffg) ([raw file](https://github.com/cockroachdb/cockroach/blob/73b3573ac9dfb206c1d57b347a5b95e1d5849af7/pkg/sql/logictest/testdata/logic_test/distsql_stats#L50)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add test cases for multiple columns, no name, and has/does not have histogram?
</blockquote></details>

We don't yet support multiple columns in the internal implementation, and we have no way of creating a single-column stat without a histogram. Will add them when they're supported. Added a test with no name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/show_stats.go, line 116 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DxHVbKcaGrrXyVbNs:-L-DxHVbKcaGrrXyVbNt:b-gztiw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfec917c989757030a418dd87dc2dd7e8dde2df9/pkg/sql/show_stats.go#L116)):*
> ```Go
> 				colNames := tree.NewDString(buf.String())
> 
> 				histogram := tree.DNull
> ```

nit - change variable name to `histogramID`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-:-L-DyAJj-csbR7A22Sb3:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/show_stats.go, line 116 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360#-L-DxHVbKcaGrrXyVbNs:-L-DzT6VEpYqyaKKbCkz:b-dtkdrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfec917c989757030a418dd87dc2dd7e8dde2df9/pkg/sql/show_stats.go#L116)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

nit - change variable name to `histogramID`
</blockquote></details>

Done, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20360)*

**Pull request merged**
