### PR TITLE
 workload: add schemachange/large-schema-benchmark

### LINKED ISSUE #123757: roachtest: add a new large schema benchmark which can be used to explore object limits
Start by adding a basic benchmark which will create a large number of objects and determine the performance characteristics by running a mix of ORM queries (from rttanalysis) and TPCC queries 

- [ ] Create a new roachtest that will create multiple instances of the TPCC database.
- [ ] Setup data at different scales within the TPCC templates.
- [ ] Have connection workers which focus on "primary" database and runs lighter work across the tertiary databases. These will execute a mix of TPCC and ORM queries (pg_catalog) or similar.
- [ ] Determine metrics for determining throughput in a statistically stable way.

Epic: CRDB-37483

Jira issue: CRDB-38529

### PR DESCRIPTION
**Pull request by fqazi**
Previously, we had no benchmark to measure the performance of ORM queries and a common workload together. This patch adds a new benchmark, schemachange/large-schema-benchmark, which runs a mix of TPCC and ORM queries. To support this, the patch includes the following:

- Updates the tpccmultidb workload to label its metrics correctly with the workload name.
- Fixes the import fixture logic to rate-limit imports when dealing with a large number of tables.
- Updates the TPCC helper library to support using tpccmultidb.
- Updates the TPCC workload to subtract any executed queries from individual operation times.
- Updates the tpccmultidb workload to support creating schemas.
- Adds the schemachange/large-schema-benchmark for the following scales: 500 tables, 1,000 tables, 10,000 tables, 25,000 tables, and 40,000 tables.

Fixes: #123757

### CODE REVIEW

**Review by spilchen — APPROVED** [review]
Looks good. I didn't have any blocking comments. Just a few suggestions.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 7 of 7 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-:-O0OdiGKA65mKZW7iVyQ:b-nygjco)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @nameisbhaskar, and @vidit-bhat)

___
*[`pkg/ccl/workloadccl/fixture.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0OVdur87JJEmlNNnSL:-O0OVdur87JJEmlNNnSM:b-fr6nom) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c90797ce4bdad2f96b3317c61e59ba1b83f239f/pkg/ccl/workloadccl/fixture.go#L408)):*
> ```Go
> 	}
> 
> 	concurrentImportLimit := limit.MakeConcurrentRequestLimiter("workload_import", 32)
> ```

Do you think it is worthwhile to add a knob to tune this?
___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0OY4w1C_xdq2CaorCd:-O0OY4w1C_xdq2CaorCe:b-odojtf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a9f76a6d23756e4d1f0a964beb479fdc2ffeb9/pkg/cmd/roachtest/tests/tpcc.go#L71)):*
> ```Go
> 	DB                 string // database name
> 	Warehouses         int
> 	WorkloadCmd        string
> ```

nit: would it be worthwhile to include a comment indicating that the default name is 'tpcc' if omitted? Since this struct is initialized in many places, it might be helpful to mention that this can be left out.
___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0OYmbL8PwzEcRJl_8g:-O0OYmbL8PwzEcRJl_8h:b-rhuq1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a9f76a6d23756e4d1f0a964beb479fdc2ffeb9/pkg/cmd/roachtest/tests/tpcc.go#L139)):*
> ```Go
> 
> // tpccImportCmd see tpccImportCmdWithCockroachBinary, this variant is set up to
> // invoke  the default tpcc subcommand
> ```

nit: extra space



_Suggestion:_
```Go
// invoke the default tpcc subcommand
```
___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 339 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0O_mrJAJg9o1gLH-Z_:-O0O_mrJAJg9o1gLH-Za:bghmflq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a9f76a6d23756e4d1f0a964beb479fdc2ffeb9/pkg/cmd/roachtest/tests/tpcc.go#L339)):*
> ```Go
> 
> 	if !opts.SkipPostRunCheck {
> 		cmd := roachtestutil.NewCommand("%s workload check tpcc", test.DefaultCockroachPath).
> ```

Should we replace "tpcc" here with the workload command?
___
*[`pkg/workload/tpcc/tpcc.go` line 1017 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0ObOmy2v8MQhrOHoVP:-O0ObOmy2v8MQhrOHoVQ:b-11h1tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af5e1074f457d051389f9796f249053330d0463/pkg/workload/tpcc/tpcc.go#L1017)):*
> ```Go
> func (w *tpcc) executeTx(
> 	ctx context.Context, conn crdbpgx.Conn, fn func(pgx.Tx) error,
> ) (onTxnStartTime time.Duration, err error) {
> ```

nit: Sort of a general comment because the variable name is used in a lot of places. But I don't understand the name. It's a duration, but the name implies it is a point in time. Maybe something like `onTxnStartDuration`?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nameisbhaskar, @spilchen, and @vidit-bhat)

___
*[`pkg/ccl/workloadccl/fixture.go` line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0OVdur87JJEmlNNnSL:-O0UaRry8-DUnrzKKL3s:b1qqcb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c90797ce4bdad2f96b3317c61e59ba1b83f239f/pkg/ccl/workloadccl/fixture.go#L408)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Do you think it is worthwhile to add a knob to tune this?
</blockquote></details>

Done.

Good point.
___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 339 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0O_mrJAJg9o1gLH-Z_:-O0UaZplBBZXXlwbT5Uv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a9f76a6d23756e4d1f0a964beb479fdc2ffeb9/pkg/cmd/roachtest/tests/tpcc.go#L339)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Should we replace "tpcc" here with the workload command?
</blockquote></details>

Done.

**Comment by fqazi** [comment]
@spilchen TFTR!

bors r+

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @nameisbhaskar, @spilchen, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/large_schema_benchmark.go` line 29 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0V3SMT3TyaFXMax0Jr:-O0V3SMT3TyaFXMax0Js:b-s5lcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e4cf17381f7774bed2e9f75f2cf5da0975f70a/pkg/cmd/roachtest/tests/large_schema_benchmark.go#L29)):*
> ```Go
> func registerSchemaChangeBenchmarkLargeSchema(r registry.Registry, numTables int) {
> 	r.Add(registry.TestSpec{
> 		Name:      fmt.Sprintf("schemachange/large-schema-benchmark/tables=%d", numTables),
> ```

hm, it's not really testing schemachanges, so maybe the name should be `tpcc/large-schema-benchmark/tables=%d`?
___
*[`pkg/cmd/roachtest/tests/large_schema_benchmark.go` line 165 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0V3hWmBKsiMq9T4hB8:-O0V3hWmBKsiMq9T4hB9:bq6v3qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e4cf17381f7774bed2e9f75f2cf5da0975f70a/pkg/cmd/roachtest/tests/large_schema_benchmark.go#L165)):*
> ```Go
> // LargeSchemaOrmQueries is extracted from the round trip analysis tests for
> // ORM queries.
> const LargeSchemaOrmQueries = `
> ```

this is just using one of the ORM queries. maybe we could have two types - one that's run only on connection init, and another that's run more frequently during workload operations.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nameisbhaskar, @rafiss, @spilchen, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/large_schema_benchmark.go` line 29 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0V3SMT3TyaFXMax0Jr:-O0V55LSByPV63piaaaD:b1qqcb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e4cf17381f7774bed2e9f75f2cf5da0975f70a/pkg/cmd/roachtest/tests/large_schema_benchmark.go#L29)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, it's not really testing schemachanges, so maybe the name should be `tpcc/large-schema-benchmark/tables=%d`?
</blockquote></details>

Done.

Good point.
___
*[`pkg/cmd/roachtest/tests/large_schema_benchmark.go` line 165 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/126006#-O0V3hWmBKsiMq9T4hB8:-O0V57Qy6DKgP9xlJfZS:b-y93m7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e4cf17381f7774bed2e9f75f2cf5da0975f70a/pkg/cmd/roachtest/tests/large_schema_benchmark.go#L165)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is just using one of the ORM queries. maybe we could have two types - one that's run only on connection init, and another that's run more frequently during workload operations.
</blockquote></details>

The connection stay open a long time. I think as a follow on I'm tempted to just simulate connection init queries multiple times through the workload and measure them (just at some fixed paced, like every 5 minutes).

**Comment by fqazi** [comment]
@rafiss TFTR!

**Pull request merged**
