### PR TITLE
Roachtest: Fix decommission roachtest check

### PR DESCRIPTION
**Pull request by kaavee315**
The decommission test currently waits till all the
ranges which are not replicated on the decommissioned node
to be fully replicated. This passes trivially. This commit
changes the check to wait till all the ranges don't have
the decommissioned node as replica and all the ranges are
replicated fully.

Release note: none

### CODE REVIEW

**Comment by tschottdorf** [comment]
Thanks! Just some minor comments, and we need the CLA signed.

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[pkg/cmd/roachtest/decommission.go, line 61 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24984#-LAnHYnd2f71xQYM2T5q:-LAnHYnd2f71xQYM2T5r:berv8qs) ([raw file](https://github.com/cockroachdb/cockroach/blob/02dcd31d03e713ee80f46fd4a2b2c2d75891ee9d/pkg/cmd/roachtest/decommission.go#L61)):*
> ```Go
> 		defer db.Close()
> 
> 		for _, fullReplicated := 0, false; !fullReplicated; {
> ```

drop the `_, ` and the `0,`.

---

*[pkg/cmd/roachtest/decommission.go, line 63 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24984#-LAnHtuv6A_lh_TcnJl-:-LAnHtuv6A_lh_TcnJl0:byqm1ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/02dcd31d03e713ee80f46fd4a2b2c2d75891ee9d/pkg/cmd/roachtest/decommission.go#L63)):*
> ```Go
> 		for _, fullReplicated := 0, false; !fullReplicated; {
> 			var count int
> 			if err := db.QueryRow(
> ```

// Check if the down node has any replicas.

---

*[pkg/cmd/roachtest/decommission.go, line 70 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24984#-LAnI-Td39ZBLGtSmVFZ:-LAnI-Td39ZBLGtSmVF_:bk88vb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/02dcd31d03e713ee80f46fd4a2b2c2d75891ee9d/pkg/cmd/roachtest/decommission.go#L70)):*
> ```Go
> 			}
> 			if count != 0 {
> 				continue
> ```

This will spin in a hot loop. Make sure to also sleep here. To get to that elegantly, I think you can run both SQL queries first and then sleep if either condition fails. This likely means that you'll make the `for` loop a plain `for { ... }`.

---

*[pkg/cmd/roachtest/decommission.go, line 72 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24984#-LAnHxbO9qA-IVwrSuNv:-LAnHxbO9qA-IVwrSuNw:b36h7va) ([raw file](https://github.com/cockroachdb/cockroach/blob/02dcd31d03e713ee80f46fd4a2b2c2d75891ee9d/pkg/cmd/roachtest/decommission.go#L72)):*
> ```Go
> 				continue
> 			}
> 			if err := db.QueryRow(
> ```

// Check if all ranges are fully replicated.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24984#-:-LAnIA8zD1VOQETu7ZXN:b-y387ku)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24984)*

**Comment by kaavee315** [comment]
@tschottdorf, could you have another look?

**Comment by tschottdorf** [comment]
:lgtm:, thanks!

bors r+

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24984#-:-LAxvDWE1-mZR9WRmiiE:b77mee0)*

**Pull request merged**
