### PR TITLE
pkg/sql/sqlstats: move failures out of stmt key/meta, into stats

### PR DESCRIPTION
**Pull request by abarganier**
Addresses: https://github.com/cockroachdb/cockroach/issues/97176
Epic: CRDB-24527

In the SQL stats feature, we consider whether the statement failed as part of the statement key/statement fingerprint ID, which is used to bucket statement statistics aggregations.

This contributes to the cardinality of statement statistics by a constant factor of 2x. A statement that has failed will show up twice in the SQL Activity page, once for the successful executions, and once for the failed executions. Despite not being very useful, the contributions it makes to cardinality are detrimental to the SQL activity feature, as it has a non-negligible impact on data volume.

To improve upon this, we should remove the failure bool from the statement key, and instead include failure counts as part of the statistics object.

This patch does the following:
* Removes the failure boolean from the statement key
* Removes failure counts from the statement statistics metadata
* Moves the failure counts into the aggrgeated statement statistics
* Updates the Statement Details page to display "Failure Count" instead of "Failed?", with the associated numeric count instead of a bool val.

Release note (ui change): In the DB Console's SQL Activity page, the Statement Details page will now show "Failure Count" in place of "Failed?", showing the number of failed executions for the given statement fingerprint instead of a "Yes"/"No" value. Furthermore, previously in the SQL Activity table the same statement fingeprint would appear twice - once for failed executions, and once for successful executions. With these changes, we no longer consider these to be separate rows. Instead, we combine them into a single statement fingerprint.

Release note (sql change): A new column has been added to `crdb_internal.node_statement_statistics`, `failure_count INT NOT NULL`. It represents the number of recorded statement execution failures for the given statement, as a new component of the overall statistics.

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
I wanted to point out a few conditionals below that deserve a look, as we're switching away from the `failed` bool in the stmt key, meaning conditionals that used the old boolean had to be reworked. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-:-Nsj28aP8GZxMF3EM14t:b-jv2b5p)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, and @xinhaoz)

___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-Nsj3KtOCG70dDjB2Avb:-Nsj3KtOCG70dDjB2Avc:b-n1ufa2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3756c819059e26d788028536b7b36c15e3cfcff3/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L252)):*
> ```Go
> 		if stmtStats.mu.data.SensitiveInfo.LastErr == "" && statistics[i].Stats.SensitiveInfo.LastErr != "" {
> 			stmtStats.mu.data.SensitiveInfo.LastErr = statistics[i].Stats.SensitiveInfo.LastErr
> 		}
> ```

NB: Without `key.Failed`, this seemed to me like an appropriate way to rework the conditional. PTAL.



_Code quote:_
```Go
		// Setting all metadata fields.
		if stmtStats.mu.data.SensitiveInfo.LastErr == "" && statistics[i].Stats.SensitiveInfo.LastErr != "" {
			stmtStats.mu.data.SensitiveInfo.LastErr = statistics[i].Stats.SensitiveInfo.LastErr
		}
```
___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-Nsj3UPa-KmJhrE9QVKy:-Nsj3UPa-KmJhrE9QVKz:bpdcgox) ([raw file](https://github.com/cockroachdb/cockroach/blob/3756c819059e26d788028536b7b36c15e3cfcff3/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L446)):*
> ```Go
> 	if s.mu.data.SensitiveInfo.LastErr == "" && statistics.Stats.SensitiveInfo.LastErr != "" {
> 		s.mu.data.SensitiveInfo.LastErr = statistics.Stats.SensitiveInfo.LastErr
> 	}
> ```

Same as above, LMK if anyone disagrees with this reworked conditional.



_Code quote:_
```Go
	// Setting all metadata fields.
	if s.mu.data.SensitiveInfo.LastErr == "" && statistics.Stats.SensitiveInfo.LastErr != "" {
		s.mu.data.SensitiveInfo.LastErr = statistics.Stats.SensitiveInfo.LastErr
	}
```
___
*[`pkg/server/application_api/sql_stats_test.go` line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-Nsj4hbOEkiKmJyzC6sV:-Nsj4hbOEkiKmJyzC6sW:b-rdq3i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3756c819059e26d788028536b7b36c15e3cfcff3/pkg/server/application_api/sql_stats_test.go#L453)):*
> ```Go
> 		var statementsInResponse []string
> 		for _, respStatement := range resp.Statements {
> 			if respStatement.Stats.FailureCount > 0 {
> ```

In this instance, instead of looking at `Failed` in the key, we replace with a check against the failure count.



_Code quote:_
```Go
		if respStatement.Stats.FailureCount > 0 {
```
___
*[`pkg/server/application_api/sql_stats_test.go` line 799 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-Nsj4nzxEw5gIN2Q0GXv:-Nsj4nzxEw5gIN2Q0GXw:bgul5s6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3756c819059e26d788028536b7b36c15e3cfcff3/pkg/server/application_api/sql_stats_test.go#L799)):*
> ```Go
> 			// to avoid counting such failures. If a statement that we expect to be
> 			// successful is not found in the response, the test will fail later.
> 			if respStatement.Key.KeyData.App == testAppName && respStatement.Stats.FailureCount == 0 {
> ```

Ditto as above - we use failure count instead of the old `Failed` bool from the key as a replacement.



_Code quote:_
```Go
		if respStatement.Key.KeyData.App == testAppName && respStatement.Stats.FailureCount == 0 {
```

**Comment by abarganier** [comment]
Ah... A bunch of tests need to be updated because the fingerprint hashes have changed with the removal of the `failure` component. Working on updating them now.

**Review by koorosh — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120236)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @xinhaoz)

___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-Nsj3KtOCG70dDjB2Avb:-NslhNbB2spy40_-U8Mf:b6bgyd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3756c819059e26d788028536b7b36c15e3cfcff3/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L252)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

NB: Without `key.Failed`, this seemed to me like an appropriate way to rework the conditional. PTAL.
</blockquote></details>

I would omit this check `&& statistics[i].Stats.SensitiveInfo.LastErr != ""` for simplicity reasons. In case `statistics[i].Stats.SensitiveInfo.LastErr` is empty then it will reassign empty string with another empty string and preserve the same logic.
___
*[`pkg/server/application_api/sql_stats_test.go` line 799 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-Nsj4nzxEw5gIN2Q0GXv:-NsljUut2uW_UyDMOINS:bvyycba) ([raw file](https://github.com/cockroachdb/cockroach/blob/3756c819059e26d788028536b7b36c15e3cfcff3/pkg/server/application_api/sql_stats_test.go#L799)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Ditto as above - we use failure count instead of the old `Failed` bool from the key as a replacement.
</blockquote></details>

Curious, if it makes sense to have `.Stats.HasFailures` bool stat?

**Review by abarganier — COMMENTED** [review]
Okay, the majority of tests have been cleaned up! RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-:-NsoOgL23o5oeppVeml6:b5jpkvc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, and @xinhaoz)

___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-Nsj3KtOCG70dDjB2Avb:-NsoOorb1qzooD8358tx:bz5py0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3756c819059e26d788028536b7b36c15e3cfcff3/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L252)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I would omit this check `&& statistics[i].Stats.SensitiveInfo.LastErr != ""` for simplicity reasons. In case `statistics[i].Stats.SensitiveInfo.LastErr` is empty then it will reassign empty string with another empty string and preserve the same logic.
</blockquote></details>

Good idea! Done.
___
*[`pkg/server/application_api/sql_stats_test.go` line 799 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-Nsj4nzxEw5gIN2Q0GXv:-NsoOrReC101w2aINHRD:b-qlipn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3756c819059e26d788028536b7b36c15e3cfcff3/pkg/server/application_api/sql_stats_test.go#L799)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Curious, if it makes sense to have `.Stats.HasFailures` bool stat?
</blockquote></details>

I think it would be duplicate information that's already represented by `Stats.FailureCount`, no?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120236)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @xinhaoz)

___
*[`pkg/server/application_api/sql_stats_test.go` line 799 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-Nsj4nzxEw5gIN2Q0GXv:-NssP58g9vGOfUaIHhmw:b6c3muc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3756c819059e26d788028536b7b36c15e3cfcff3/pkg/server/application_api/sql_stats_test.go#L799)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

I think it would be duplicate information that's already represented by `Stats.FailureCount`, no?
</blockquote></details>

You're right, my initial thoughts were to avoid checks like this and above with dedicated prop, but it definitely duplicates logic.

**Review by dhartunian — APPROVED** [review]
:lgtm: nice work on this. lots of details to manage. Might be worth keeping as a single commit to keep it all in sync.

> Reviewed 23 of 27 files at r1, 4 of 4 files at r2, 13 of 13 files at r5, 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-:-NsxMgig8mplNwvhETBh:b6yf5vo)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`pkg/sql/crdb_internal.go` line 1811 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-NssBOvU9xPk1c_o6EOU:-NssBOvU9xPk1c_o6EOV:b-pntkyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8774e473c38f8c9ebf1b8e3c1b17f3589dc98e3/pkg/sql/crdb_internal.go#L1811)):*
> ```Go
>   latency_seconds_p90 FLOAT,
>   latency_seconds_p99 FLOAT,
>   failure_count INT NOT NULL                                                   
> ```

nit: trailing whitespace
___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 845 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-NsxMOB7DiHZmPfRxBY8:-NsxMOB7DiHZmPfRxBY9:b42qfhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa18f90faec0845160e520773c11540c1ce8f9c8/pkg/sql/logictest/testdata/logic_test/crdb_internal#L845)):*
> ```
> # - one for the DROP SEQUENCE statement.
> #
> # We expect the SELECT entry to have max_retries > 0 because auto-retries
> ```

nit: there are two select entires below.

**Comment by abarganier** [comment]
TFTR! 

bors r=dhartunian

**Review by abarganier — COMMENTED** [review]
Ah, forgot to submit my replies to your comments before I `bors`'d :sweat_smile: 

Good call squashing the commits, I went ahead and did so.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-:-Nt1ytQM9KyV0NaCR-Mq:b-yvqw8x)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @xinhaoz)

___
*[`pkg/sql/crdb_internal.go` line 1811 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-NssBOvU9xPk1c_o6EOU:-Nt1yLGj5cguIrosNgNw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8774e473c38f8c9ebf1b8e3c1b17f3589dc98e3/pkg/sql/crdb_internal.go#L1811)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: trailing whitespace
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 845 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/120236#-NsxMOB7DiHZmPfRxBY8:-Nt1yZxD3o0HwvBAcCda:bf7khcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa18f90faec0845160e520773c11540c1ce8f9c8/pkg/sql/logictest/testdata/logic_test/crdb_internal#L845)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: there are two select entires below.
</blockquote></details>

Thanks for the catch. Fixed.

**Pull request merged**
