### PR TITLE
sql/stats: fix inject/restore of partial stats not creating merged stats

### LINKED ISSUE #94101: sql/stats: after inject or restore of partial statistics, cannot create merged statistics
Now that users can collect partial statistics at the extremes of columns using `CREATE STATISTICS ON <col_name> FROM <table_name> USING EXTREMES`, ensure that statements bundles include both full statistics and partial statistics.

The other thing we need to be sure of is that merged statistics are correctly created when injecting statment bundle stats so that we can mimic customer behavior.

Jira issue: CRDB-22695

Epic CRDB-25383

### PR DESCRIPTION
**Pull request by Uzair5162**
Previously, JSON statistics would not include the statistic ID. This meant that restoring statement bundles would recreate stats with new IDs, breaking the statisticID/fullStatisticID relationship between full & partial stats and fail to recreate merged stats as a result. This commit adds the statistic ID to JSONStatistic and recreates stats with the same ID if present when injected. Allows for merged stats to be correctly recreated following inject/restore of full and partial stats.

Fixes: #94101

See also: #125950

Release note (bug fix): Fixed a bug that prevented merged stats from being created after injecting stats or recreating statement bundles. This would occur when the injected stats/statement bundle contained related full and partial statistics.

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127252)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @Uzair5162)

___
*[`pkg/sql/stats/json.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1wBezO9Lj9NtsfCwRk:-O1wBezPDieQPtEpBy3L:bwm7ymr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f0bcfc9649e1192d07bf3b788c58825e98bce/pkg/sql/stats/json.go#L31)):*
> ```Go
> // See TableStatistic for a description of the fields.
> type JSONStatistic struct {
> 	StatisticID   uint64   `json:"statistic_id,omitempty"`
> ```

nit: Should this be just `ID`? Or is `StatisticID` easier to understand because we use that naming elsewhere?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1wCf29-TJ4sEdvShPO:-O1wCf29-TJ4sEdvShPP:bc3upq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f0bcfc9649e1192d07bf3b788c58825e98bce/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L167)):*
> ```
> 
> query IITTTIIII colnames
> SELECT histogram_id, full_histogram_id, statistics_name, column_names, created, row_count, distinct_count, null_count, avg_size
> ```

What's the relationship between `full_statistic_id` and `full_histogram_id`, and `histogram_id` and `statistic_id`?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1wCxN49TN0IidCgNdH:-O1wCxN49TN0IidCgNdI:bs1du4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f0bcfc9649e1192d07bf3b788c58825e98bce/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L497)):*
> ```
>            "partial_predicate": "(h < 10:::INT8) OR ((h > 40:::INT8) OR (h IS NULL))",
>            "row_count": 0,
>            "full_statistic_id": 1
> ```

I don't see any tests where `full_statistic_id` is included in the stats output—I only see it being included in the injected stats. Should we add some tests for that?

**Review by Uzair5162 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127252)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @michae2)

___
*[`pkg/sql/stats/json.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1wBezO9Lj9NtsfCwRk:-O1wPluZEj4LFWRCCUni:bom6jur) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f0bcfc9649e1192d07bf3b788c58825e98bce/pkg/sql/stats/json.go#L31)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Should this be just `ID`? Or is `StatisticID` easier to understand because we use that naming elsewhere?
</blockquote></details>

Done, I think `ID` is better.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1wCf29-TJ4sEdvShPO:-O1wS3l-D8cWKI1osTP-:beeieem) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f0bcfc9649e1192d07bf3b788c58825e98bce/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L167)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What's the relationship between `full_statistic_id` and `full_histogram_id`, and `histogram_id` and `statistic_id`?
</blockquote></details>

(`full_statistic_id`/`full_histogram_id`) and (`histogram_id`/`statistic_id`) are interchangeable AFAIK. `full_statistic_id`/`full_histogram_id` is the ID of the full table statistic that the partial statistic was derived from and is null for full statistics (see https://github.com/cockroachdb/cockroach/pull/93751/commits/aab61b678b3af17a5e221e85ccbfa2118183d789).
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1wCxN49TN0IidCgNdH:-O1wVd9R23aTigTT30Ac:b6xxdx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f0bcfc9649e1192d07bf3b788c58825e98bce/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L497)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't see any tests where `full_statistic_id` is included in the stats output—I only see it being included in the injected stats. Should we add some tests for that?
</blockquote></details>

Done, added checking stats json output for `full_statistic_id` to an existing test [here](https://github.com/Uzair5162/cockroach/blob/4ece712579fd4a86506cd741fa04a9611113aa0c/pkg/sql/logictest/testdata/logic_test/distsql_stats#L2391-L2401).

**Review by DrewKimball — APPROVED** [review]
:lgtm: Once Marcus's comments are addressed.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-:-O1xSwbh4kKN9kYoEpSy:b-c1ii26)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-:-O1xUzt12ypWmrwlYzTc:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2 and @Uzair5162)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 2397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1xUVpM1yimpgXVye6Z:-O1xUVpM1yimpgXVye6_:b59fpyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ece712579fd4a86506cd741fa04a9611113aa0c/pkg/sql/logictest/testdata/logic_test/distsql_stats#L2397)):*
> ```
>   FROM [SHOW STATISTICS USING JSON FOR TABLE xy]
> )
> WHERE stat->>'full_statistic_id' = '$statistics_id'
> ```

nit: does this need to change to `id`?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1wCf29-TJ4sEdvShPO:-O1xUbROBDFJpQCSqVGQ:b-5yocqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f0bcfc9649e1192d07bf3b788c58825e98bce/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L167)):*
<details><summary><i>Previously, Uzair5162 (Uzair Ahmad) wrote…</i></summary><blockquote>

(`full_statistic_id`/`full_histogram_id`) and (`histogram_id`/`statistic_id`) are interchangeable AFAIK. `full_statistic_id`/`full_histogram_id` is the ID of the full table statistic that the partial statistic was derived from and is null for full statistics (see https://github.com/cockroachdb/cockroach/pull/93751/commits/aab61b678b3af17a5e221e85ccbfa2118183d789).
</blockquote></details>

Something to think about, maybe outside of this PR: Should we make an effort to make the names consistent? Is it possible to do so without breaking stats during an upgrade of CRDB versions?

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-:-O1xcJRF-XvM6OM2CbVQ:b-8gk8uj)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @mgartner and @Uzair5162)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1wCf29-TJ4sEdvShPO:-O1xaETu4ubVED0-6e0n:b-chw2r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f0bcfc9649e1192d07bf3b788c58825e98bce/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L167)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Something to think about, maybe outside of this PR: Should we make an effort to make the names consistent? Is it possible to do so without breaking stats during an upgrade of CRDB versions?
</blockquote></details>

I believe `histogram_id` and `full_histogram_id` are only used in `SHOW STATISTICS` output, everywhere else uses "statistics ID". Maybe it was done this way to indicate a connection with `SHOW HISTOGRAM` (which also uses the statistics ID)?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1xbwcf47oPRJrjs8AH:-O1xbwcf47oPRJrjs8AI:b-9ivcmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d7cc7fdad28049677a31ffbd8d45e20705f7620/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L56)):*
> ```
>     "null_count": 0,
>     "row_count": 3,
>     "statistics_id": 1
> ```

Huh, that's interesting. I wonder if we started down this route and forgot to remove this?

**Review by Uzair5162 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127252)* status: <span>:shipit:</span> complete! 3 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 2397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1xUVpM1yimpgXVye6Z:-O1xXsPVEJosOIqvlF4R:bvyyxe6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ece712579fd4a86506cd741fa04a9611113aa0c/pkg/sql/logictest/testdata/logic_test/distsql_stats#L2397)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: does this need to change to `id`?
</blockquote></details>

Don't think so, statistics_id here is referring to the `$statistics_id` logic test variable and not the stat JSON field.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1xbwcf47oPRJrjs8AH:-O2-ynIQAWaBUL62gSrf:b-e5wuxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d7cc7fdad28049677a31ffbd8d45e20705f7620/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L56)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Huh, that's interesting. I wonder if we started down this route and forgot to remove this?
</blockquote></details>

Likely that was the case since this was the only place that had `statistics_id`.

**Comment by mgartner** [comment]
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 2397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127252#-O1xUVpM1yimpgXVye6Z:-O21R2af0MhxRTYge8sQ:b-1br0vh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ece712579fd4a86506cd741fa04a9611113aa0c/pkg/sql/logictest/testdata/logic_test/distsql_stats#L2397)):*
<details><summary><i>Previously, Uzair5162 (Uzair Ahmad) wrote…</i></summary><blockquote>

Don't think so, statistics_id here is referring to the `$statistics_id` logic test variable and not the stat JSON field.
</blockquote></details>

Sorry, I was referring to `full_statistic_id`. Hasn't that been replaced with `id`?

**Pull request merged**
