### PR TITLE
server: pretty-print statement trace for the StatementDiagnostics RPC

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None
Release justification: big usability improvement for viewing traces; low
risk

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Comment by dhartunian** [comment]
@andreimatei just want to confirm that this JSON is no longer directly accessible in the UI (since only the bundle can be downloaded) so the use here would be if someone made the API call directly.

**Comment by RaduBerinde** [comment]
Yeah, I think Andrei had the code done already so why not merge it.

**Review by dhartunian — APPROVED** [review]

**Comment by andreimatei** [comment]
Right. I'm not gonna backport this. But I hope we'll use this json endpoint again when we get the fancy trace visualizer :)

LGTM

**Pull request merged**
