### PR TITLE
Makefile,ui: simplify bindata processing

### PR DESCRIPTION
**Pull request by benesch**
Simplify injection of an init hook into bindata.go by using goimports.
Previously goimports could not handle files with lines as long as
bindata.go's, but that was fixed in https://go-review.googlesource.com/93439.

Release note: None

### CODE REVIEW

**Comment by mrtracy** [comment]
Did you mean to make all of those changes from "fmt" to "strconv"?

**Comment by benesch** [comment]
Yeah, sadly. Those files are autogenerated by stringer, and goimports lives
in the same repo as stringer. Can’t get one update without the other.

**Comment by mrtracy** [comment]
Alright then, LGTM!

**Comment by couchand** [comment]
LGTM.  Way to upstream!

nit: it would be nice to split up the dep bump/stringer change into a separate commit from the build change.

**Comment by benesch** [comment]
Done!

**Pull request merged**
