### PR TITLE
builtins: introduce builtins for some binary predicates

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): Add support for ST_Covers, ST_CoveredBy,
ST_Contains, ST_Crosses, ST_Equals, ST_Intersects, ST_Overlaps,
ST_Touches and ST_Within for Geometry geospatial types.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47584)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[docs/generated/sql/functions.md, line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-M5HujpWAqVX1l_zfHKc:-M5HujpWAqVX1l_zfHKd:b2r4qc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c1dde4ea631a9eefb02c38e8a71682af6b546ea/docs/generated/sql/functions.md#L513)):*
> ```Markdown
> <table>
> <thead><tr><th>Function &rarr; Returns</th><th>Description</th></tr></thead>
> <tbody>
> ```

I think we need a code comment somewhere in geo that defines interior, boundary and exterior, for point, polygon, ...
___
*[docs/generated/sql/functions.md, line 526 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-M5HvAEo8qZn-5pTf5TP:-M5HvAEo8qZn-5pTf5TQ:bors2xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c1dde4ea631a9eefb02c38e8a71682af6b546ea/docs/generated/sql/functions.md#L526)):*
> ```Markdown
> <p>This function will automatically use any available index.</p>
> </span></td></tr>
> <tr><td><a name="st_crosses"></a><code>st_crosses(geometry_a: geometry, geometry_b: geometry) &rarr; <a href="bool.html">bool</a></code></td><td><span class="funcdesc"><p>Returns true if geometry_a has some - but not all - points in common with geometry_b.</p>
> ```

I think this is defined in terms of "interior points".
___
*[docs/generated/sql/functions.md, line 538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-M5Hvj311-lhGqro2f7y:-M5Hvj32777dOfvRyhbR:b-f5045z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c1dde4ea631a9eefb02c38e8a71682af6b546ea/docs/generated/sql/functions.md#L538)):*
> ```Markdown
> <p>This function will automatically use any available index.</p>
> </span></td></tr>
> <tr><td><a name="st_overlaps"></a><code>st_overlaps(geometry_a: geometry, geometry_b: geometry) &rarr; <a href="bool.html">bool</a></code></td><td><span class="funcdesc"><p>Returns true if geometry_a intersects but does not completely contain geometry_b, or vice versa.</p>
> ```

Perhaps add that "does not completely" is equivalent to ST_Within(a, b) and ST_Within(b, a) will both be false.
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-M5Hx2Ih8KUoR_T5YooS:-M5Hx2Ih8KUoR_T5YooT:bdvhddu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c1dde4ea631a9eefb02c38e8a71682af6b546ea/pkg/sql/logictest/testdata/logic_test/geospatial#L76)):*
> ```
> 
> statement ok
> INSERT INTO geom_binary_predicates_test VALUES
> ```

can you add a high-level comment about the shapes chosen here and what relatonships they have, that serves as a guide to how to read the output matrix below?
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-M5HxpNfComYwzaoD_Qv:-M5HxpNfComYwzaoD_Qw:b-csccia) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c1dde4ea631a9eefb02c38e8a71682af6b546ea/pkg/sql/sem/builtins/geo_builtins.go#L85)):*
> ```Go
> 			geomfn.Crosses,
> 			infoBuilder{
> 				info:        "Returns true if geometry_a has some - but not all - points in common with geometry_b.",
> ```

interior points

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47584)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[docs/generated/sql/functions.md, line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-M5HujpWAqVX1l_zfHKc:-M5I4mNO1CcbTYKUdiLZ:b-udp00r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c1dde4ea631a9eefb02c38e8a71682af6b546ea/docs/generated/sql/functions.md#L513)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we need a code comment somewhere in geo that defines interior, boundary and exterior, for point, polygon, ...
</blockquote></details>

Hmm, maybe define this in some overarching doc?
Note this is automatically generated from the "geo_builtins.go" below, anything overarching needs to be somewhere else.
___
*[docs/generated/sql/functions.md, line 526 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-M5HvAEo8qZn-5pTf5TP:-M5I5O1dE6OQhBAy4lN1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c1dde4ea631a9eefb02c38e8a71682af6b546ea/docs/generated/sql/functions.md#L526)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this is defined in terms of "interior points".
</blockquote></details>

Done.
___
*[docs/generated/sql/functions.md, line 538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-M5Hvj311-lhGqro2f7y:-M5I5OSA4PE-UAlOh6nf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c1dde4ea631a9eefb02c38e8a71682af6b546ea/docs/generated/sql/functions.md#L538)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Perhaps add that "does not completely" is equivalent to ST_Within(a, b) and ST_Within(b, a) will both be false.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-M5Hx2Ih8KUoR_T5YooS:-M5I4hFJE9KlXID2SPsG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c1dde4ea631a9eefb02c38e8a71682af6b546ea/pkg/sql/logictest/testdata/logic_test/geospatial#L76)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a high-level comment about the shapes chosen here and what relatonships they have, that serves as a guide to how to read the output matrix below?
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-M5HxpNfComYwzaoD_Qv:-M5I5oh8AktNgl6OGTWx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c1dde4ea631a9eefb02c38e8a71682af6b546ea/pkg/sql/sem/builtins/geo_builtins.go#L85)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

interior points
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47584#-:-M5Swmp41_pqVCQGtfZZ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
