### PR TITLE
server,storage: plumb more contexts, set node/store log tags

### PR DESCRIPTION
**Pull request by RaduBerinde**
See individual commits for descriptions.

@petermattis Do you think having `node=xx`  show up in logs is distracting in production? Or it could potentially be useful there too? (could help not having to keep track of what log file came from which node)  I could plumb a `TestingKnob` to only enable it on test clusters if we don't want it.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8715)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Ah, unfortunately the various components start doing stuff asynchronously by the time we call `SetNodeID` which leads to data races, how annoying. I'll think of a way to fix this. @andreimatei any ideas?

**Comment by petermattis** [comment]
Heh, I was about to ask if `SetNodeID` needed synchronization and I see you've already determined it does. Also see `DistSender.getNodeDescriptor` which asynchronously fills in the node descriptor (and node ID) when requested. I feel that is a wart that should be fixed separately from this PR.

This approach looks good to me, but note my caveat below about needing to also clean up the log messages. 

---

Reviewed 5 of 5 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender.go, line 235 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8715#-KPeUHN5ZXyCRWPgrJny:-KPeUHN5ZXyCRWPgrJnz:b-130ve4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8a5eed755e3c5b09c20604542ec8df8cedb4da/kv/dist_sender.go#L235)):*
> ```Go
> }
> 
> // SetNodeID sets the node ID (for logging contexts).
> ```

Comment that it is expected this is called only once.

---

*[kv/dist_sender.go, line 237 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8715#-KPeULplWvYyzUnyuoho:-KPeULplWvYyzUnyuohp:b-i9by69) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8a5eed755e3c5b09c20604542ec8df8cedb4da/kv/dist_sender.go#L237)):*
> ```Go
> // SetNodeID sets the node ID (for logging contexts).
> func (ds *DistSender) SetNodeID(nodeID roachpb.NodeID) {
> 	ds.Ctx = log.WithLogTagInt(ds.Ctx, "node", int(nodeID))
> ```

I think we should use abbreviations for these tags as they'll be extremely common in the logs. My suggestions: `node == n`, `range == r`, `store == s`, `transaction == t`. 

---

*[storage/store.go, line 857 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8715#-KPeW5IyTzf0dWVqxany:-KPeW5IyTzf0dWVqxanz:buwnums) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f1b816b640949a9c893420deb1713e180f6a187/storage/store.go#L857)):*
> ```Go
> 
> 	s.ctx.Ctx = log.WithLogTagInt(s.ctx.Ctx, "node", int(s.Ident.NodeID))
> 	s.ctx.Ctx = log.WithLogTagInt(s.ctx.Ctx, "store", int(s.Ident.StoreID))
> ```

Per my earlier suggestion: `s/node/n/g`, `s/store/s`. 

---

*[storage/store.go, line 1898 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8715#-KPeV_vhR73E-TvojIDu:-KPeV_vhR73E-TvojIDv:b-rhwwo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f1b816b640949a9c893420deb1713e180f6a187/storage/store.go#L1898)):*
> ```Go
> 	// Attach any log tags from the store to the context (which normally
> 	// comes from gRPC).
> 	ctx = log.WithLogTagsFromCtx(ctx, s.Ctx())
> ```

I'm not sure about this pattern. I'd prefer something similar to Toby's previous effort:

```
func (s *Store) logContext(ctx context.Context) context.Context {
	ctx = log.WithLogTagInt(ctx, "node", int(s.Ident.NodeID))
	ctx = log.WithLogTagInt(ctx, "store", int(s.Ident.StoreID))
        return ctx
}
```

Then the above would turn into: `ctx = s.logContext(ctx)`.

If the request has a transaction, I think we should also add the short txn-id as a log tag.

Lastly, we manually prepend the node and store ID to a lot of log messages by either outputting `Store.String()` or `Replica.String()` as a prefix of the message. It is burdensome, but we should clean up those log messages at the same time we add the log tags or our logging will have redundant information.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8715#-:-KPeUzS_yvWZlEfLT87X:bgx1jd7)*

**Comment by RaduBerinde** [comment]
Yeah the tricky thing is that Context is an interface, so I would need to store an atomic pointer to the interface.. There's`atomic.Value` but it won't work as the underlying type isn't consistent in general. Or I could store two Contexts and an atomic flag. I don't like either of these :/

I don't have a good idea how this general problem could be cleanly fixed. We would need a separate init phase to just figure out the NodeID but it feels like a complicated change.

There's also the possibility that there are only a couple of races, given that we call SetNodeID very early - I could try to track those down and work around them but it feels fragile.

---

Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender.go, line 237 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8715#-KPeULplWvYyzUnyuoho:-KPedd2iX4ooOyf5cfs5:b-e655bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c8a5eed755e3c5b09c20604542ec8df8cedb4da/kv/dist_sender.go#L237)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I think we should use abbreviations for these tags as they'll be extremely common in the logs. My suggestions: `node == n`, `range == r`, `store == s`, `transaction == t`. 
</details>
Should I also suppress the `=`, at least if the tag is a single character (so we have `n1,s5,t123`?

---

*[storage/store.go, line 1898 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8715#-KPeV_vhR73E-TvojIDu:-KPed7XUpJYY2AcqiHrB:b-9zpi10) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f1b816b640949a9c893420deb1713e180f6a187/storage/store.go#L1898)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm not sure about this pattern. I'd prefer something similar to Toby's previous effort:
> 
> ```
> func (s *Store) logContext(ctx context.Context) context.Context {
> 	ctx = log.WithLogTagInt(ctx, "node", int(s.Ident.NodeID))
> 	ctx = log.WithLogTagInt(ctx, "store", int(s.Ident.StoreID))
>         return ctx
> }
> ```
> 
> Then the above would turn into: `ctx = s.logContext(ctx)`.
> 
> If the request has a transaction, I think we should also add the short txn-id as a log tag.
> 
> Lastly, we manually prepend the node and store ID to a lot of log messages by either outputting `Store.String()` or `Replica.String()` as a prefix of the message. It is burdensome, but we should clean up those log messages at the same time we add the log tags or our logging will have redundant information.
</details>
Yeah I was thinking that got a bit too complicated for what we need, it's simpler the way you suggest.

Regarding the log messages - I mentioned this in a commit too, I want to make sure we have the tags in the all the code paths before I remove it from the messages - the redundancy is mildly annoying, but having a log that misses the information would be worse. I'll take a more careful look at logs from tests and if it looks good I'll work on removing the Store info from logs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8715#-:-KPegn3s-vaEbO-fEazm:bbpyonn)*

**Comment by RaduBerinde** [comment]
I have an idea - I can include a node log tag in the context very early on but with a "dynamic" value - the value can be an arbitrary type with a `String` function. That type can read the node ID from an atomic or whatever. This will also simplify a bunch of the code, since `NewServer` can do this once instead of every component worrying about the log tag.

A pattern like this will be necessary for `Range` anyway (the key interval is dynamic).

---

Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8715#-:-KPn0E6DdON2UETmnA8c:bxsrujq)*

**Comment by RaduBerinde** [comment]
I'm reworking the change so I'm closing this for now.

**Pull request closed without merging**
