### PR TITLE
Use jemalloc by default, but allow disabling

### PR DESCRIPTION
**Pull request by mberhault**
See related changes in `c-lz4,c-protobuf,c-rocksdb,c-snappy`

I have not enabled profiling by default (using `MALLOC_CONF` or `/etc/malloc.conf` is more configurable, but I may once I add hooks to grab profiles dynamically).

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7006)

### CODE REVIEW

**Comment by mberhault** [comment]
FYI: this PR will have to wait for other repos to be merged and updated in `GLOCK`

**Comment by petermattis** [comment]
:lgtm:

Do we still need to build the `stdmalloc` binaries and tests? Seems like jemalloc is strictly better.

<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> FYI: this PR will have to wait for other repos to be merged and updated in `GLOCK`
</details>


---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-:-KJGNVcaAFls9izYN_8i:-247432182)*

**Comment by mberhault** [comment]
not strictly, but I'd like to keep it for now as backup, and in-code documentation of how to revert to the standard allocator. It will probably go away very soon (at least the circleci rule)

<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> :lgtm:
> 
> Do we still need to build the `stdmalloc` binaries and tests? Seems like jemalloc is strictly better.
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-:-KJGVgTN8DhT214L1bb6:1099635191)*

**Comment by bdarnell** [comment]
LGTM

<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> not strictly, but I'd like to keep it for now as backup, and in-code documentation of how to revert to the standard allocator. It will probably go away very soon (at least the circleci rule)
</details>


---

Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[main_jemalloc.go, line 26 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHHpwOylJRBanz-pA4:-KJHHpwPQELr1At9QHa5:933193438) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/main_jemalloc.go#L26)):*
> ```Go
> // #cgo linux LDFLAGS: -Wl,-unresolved-symbols=ignore-all
> //
> // #include <jemalloc/jemalloc.h>
> ```

These comments have no effect with the `import "C"` removed. Either remove this file or re-add `import "C"`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-:-KJHI7G5oTEaeIEqsrLB:676834233)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[main_jemalloc.go, line 26 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHHpwOylJRBanz-pA4:-KJHLRYoo3HoaPIZHjIw:951041911) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/main_jemalloc.go#L26)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> These comments have no effect with the `import "C"` removed. Either remove this file or re-add `import "C"`.
</details>
+1 remove this file

---

*[server/status/runtime_jemalloc.go, line 21 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHLEQvjYax19Bh7FoT:-KJHLEQvjYax19Bh7FoU:955396467) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/server/status/runtime_jemalloc.go#L21)):*
> ```Go
> package status
> 
> // #cgo darwin CPPFLAGS: -I../../../c-jemalloc/darwin_includes/internal/include
> ```

i dont think this is kosher - we need to use the right jemalloc.h for the platform.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[main_jemalloc.go, line 26 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHHpwOylJRBanz-pA4:-KJHOkPHm3BpeCcFOT8W:1232154423) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/main_jemalloc.go#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> +1 remove this file
</details>
so here's a question. If I don't have those in, how is anything that does not import server/status/ getting jemalloc linked in?

---

*[server/status/runtime_jemalloc.go, line 21 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHLEQvjYax19Bh7FoT:-KJHOeyHcoLyMwEblP6-:296986106) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/server/status/runtime_jemalloc.go#L21)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i dont think this is kosher - we need to use the right jemalloc.h for the platform.
</details>
how is this not the right one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[main_jemalloc.go, line 26 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHHpwOylJRBanz-pA4:-KJHPwn6N8Yjp4jQUSe6:880332154) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/main_jemalloc.go#L26)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> so here's a question. If I don't have those in, how is anything that does not import server/status/ getting jemalloc linked in?
</details>
linking of jemalloc is controlled by the go import of c-jemalloc. these lines don't do that, so anything that does not import server/status is indeed not going to have jemalloc linked in

---

*[server/status/runtime_jemalloc.go, line 21 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHLEQvjYax19Bh7FoT:-KJHQ8JleXUsMJ0d9esK:-1846744076) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/server/status/runtime_jemalloc.go#L21)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> how is this not the right one?
</details>
because you're giving it both paths? i don't know which file it's picking, but the fact that it works is an accident

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/status/runtime_jemalloc.go, line 21 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHLEQvjYax19Bh7FoT:-KJHQO7y642by36g-uAF:-721349102) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/server/status/runtime_jemalloc.go#L21)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> because you're giving it both paths? i don't know which file it's picking, but the fact that it works is an accident
</details>
they're different targets, one for linux, one for darwin. or am I missing something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/status/runtime_jemalloc.go, line 21 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHLEQvjYax19Bh7FoT:-KJHVtxTwNCvah6Lxon8:730637832) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/server/status/runtime_jemalloc.go#L21)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> they're different targets, one for linux, one for darwin. or am I missing something?
</details>
both directories are present and checked in - you need to use a build tag here to switch between the two.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[main_jemalloc.go, line 26 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHHpwOylJRBanz-pA4:-KJHcPqRWMYJY8V8VKAW:864118702) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/main_jemalloc.go#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> linking of jemalloc is controlled by the go import of c-jemalloc. these lines don't do that, so anything that does not import server/status is indeed not going to have jemalloc linked in
</details>
But nothing else depends on cockroachdb/cockroach, so importing c-jemalloc here doesn't really help either. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/status/runtime_jemalloc.go, line 21 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHLEQvjYax19Bh7FoT:-KJHiDMX03XHW9LKTEVh:1660313408) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/server/status/runtime_jemalloc.go#L21)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> both directories are present and checked in - you need to use a build tag here to switch between the two.
</details>
I do already. there's a "cgo linux" line and a "cgo darwin" line. I think one of us is confused, and at this point, I'm pretty sure it isn't me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/status/runtime_jemalloc.go, line 21 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHLEQvjYax19Bh7FoT:-KJHicKXHdU9Ujk2OktM:485285763) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/server/status/runtime_jemalloc.go#L21)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> I do already. there's a "cgo linux" line and a "cgo darwin" line. I think one of us is confused, and at this point, I'm pretty sure it isn't me.
</details>
Yup, it's me! :tired_face: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[main_jemalloc.go, line 26 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHHpwOylJRBanz-pA4:-KJHjTLJMU_fvRg1lfUf:-2044909949) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/main_jemalloc.go#L26)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> But nothing else depends on cockroachdb/cockroach, so importing c-jemalloc here doesn't really help either. 
</details>
Yeah, agreed. What purpose is this file serving?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Comment by mberhault** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[main_jemalloc.go, line 26 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006#-KJHHpwOylJRBanz-pA4:-KJI2SnmTiOxmUUmPNqj:-683409897) ([raw file](https://github.com/cockroachdb/cockroach/blob/42cc2c3356075e08c4d01f8cf992e2acef52ad14/main_jemalloc.go#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, agreed. What purpose is this file serving?
</details>
yeah, none anymore. C stuff will pick jemalloc through rocksdb. It would be nice to have a base package of sorts used by everything (tests included), but I supposed it's not particularly necessary. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7006)*

**Pull request merged**
