### PR TITLE
sql: refactor and simplify the expandPlan() recursion.

### PR DESCRIPTION
**Pull request by knz**
This patch collapses the myriad of expandPlan() methods on planNodes
into a (simpler) single expandPlan() recursive function. This also
migrates the "interesting" work performed by `expandPlan` on
`selectNode` and `selectTopNode` (namely, index expansion and
ordering-based simplifications), previously spread over 4 source
files, into a single source file which will improve readability and
maintainability.

As a side effect this improvement also causes nearly all the
expressions in planNodes to be traversed only once instead of three
times for sub-query initialization. The only remaining exception is
the CHECK expressions for UPSERT/INSERT/UPDATE which will be captured
under the same mechanism when #12599 is resolved.

This patch also introduces a new top-level `optimizePlan` function
which factors calls to `expandPlan` and `setNeededColumns`.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12605)

### CODE REVIEW

**Comment by knz** [comment]
Needed for #10633

**Comment by RaduBerinde** [comment]
:lgtm: :gift:

---

Review status: 0 of 41 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/expand_plan.go, line 42 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-K_D3dyOPAOWRYYbWHj-:-K_D3dyOPAOWRYYbWHj0:b78sw3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a91a753743b7d6eafa21b8c0cd23befc200ced8/pkg/sql/expand_plan.go#L42)):*
> ```Go
> 
> 	case *updateNode:
> 		return n.run.expandEditNodePlan(&n.editNodeBase, &n.tw)
> ```

Maybe expandEditNodePlan belongs in this file as well (as a planner method)?

---

*[pkg/sql/expand_plan.go, line 126 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-K_Czeb_sZQHvbtPACRR:-K_Czeb_sZQHvbtPACRS:beftlmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a91a753743b7d6eafa21b8c0cd23befc200ced8/pkg/sql/expand_plan.go#L126)):*
> ```Go
> 		}
> 
> 	case *limitNode:
> ```

these can all be one case
```go
case *limitNode, *sortNode, *windowNode, ...:
  panic(fmt.Sprintf("expandPlan for %T ..", n))
```

---

*[pkg/sql/optimize.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-K_D0-chXumTotHXzfiJ:-K_D0-chXumTotHXzfiK:b-lu0hpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a91a753743b7d6eafa21b8c0cd23befc200ced8/pkg/sql/optimize.go#L26)):*
> ```Go
> // call optimizePlan(). This is called automatically by makePlan().
> func (p *planner) optimizePlan(plan planNode, needed []bool) error {
> 	// We propagate the needed columns a first time. This will remove
> ```

Very nice step by step explanation, this is great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-:-K_D0pPcTuCeFDvjLRW7:bcd4h8f)*

**Comment by knz** [comment]
Review status: 0 of 41 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/expand_plan.go, line 42 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-K_D3dyOPAOWRYYbWHj-:-K_DhL8yD5Jd9XHWxMRD:b-fwuqjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a91a753743b7d6eafa21b8c0cd23befc200ced8/pkg/sql/expand_plan.go#L42)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe expandEditNodePlan belongs in this file as well (as a planner method)?
</blockquote></details>

It will go away with #12599.

---

*[pkg/sql/expand_plan.go, line 126 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-K_Czeb_sZQHvbtPACRR:-K_DhNAF-fjxXeAUt0e_:b2q8cxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a91a753743b7d6eafa21b8c0cd23befc200ced8/pkg/sql/expand_plan.go#L126)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

these can all be one case
```go
case *limitNode, *sortNode, *windowNode, ...:
  panic(fmt.Sprintf("expandPlan for %T ..", n))
```
</blockquote></details>

Woo I didn't know you could do that!
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605)*

**Comment by RaduBerinde** [comment]
Reviewed 2 of 4 files at r1, 36 of 39 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/create.go, line 1583 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-K_Fr2PE9hAyXNweBq5i:-K_Fr2PE9hAyXNweBq5j:bmz4ii8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3413c98daaaf9182c7f8f5de6e9f8cf3e39a2d8/pkg/sql/create.go#L1583)):*
> ```Go
> 			ColumnIDs: make([]sqlbase.ColumnID, 0, len(scan.cols)),
> 		}
> 		if scan.index != nil && scan.isSecondaryIndex {
> ```

what's the deal with this change? Is `scan.index` set only if an index is forced through a hint? Otherwise, we don't want to create a reference, do we?

---

*[pkg/sql/index_selection.go, line 200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-K_FqOWMwREnd_HuX0Gt:-K_FqOWMwREnd_HuX0Gu:b-76ov1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3413c98daaaf9182c7f8f5de6e9f8cf3e39a2d8/pkg/sql/index_selection.go#L200)):*
> ```Go
> 	c := candidates[0]
> 	s.index = c.index
> 	s.specifiedIndex = nil
> ```

how come this was needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-:-K_FuHo8skqUET-9eDre:bnfp4nl)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/create.go, line 1583 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-K_Fr2PE9hAyXNweBq5i:-K_K-Y_DwOAhoiX4ZlD8:b-vh0m2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3413c98daaaf9182c7f8f5de6e9f8cf3e39a2d8/pkg/sql/create.go#L1583)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's the deal with this change? Is `scan.index` set only if an index is forced through a hint? Otherwise, we don't want to create a reference, do we?
</blockquote></details>

`scan.index` is always initialized to the primary index, before index selection consumes the hint and resets it.

---

*[pkg/sql/index_selection.go, line 200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605#-K_FqOWMwREnd_HuX0Gt:-K_K-v4fSG09yTgfOH5N:bfpr66y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3413c98daaaf9182c7f8f5de6e9f8cf3e39a2d8/pkg/sql/index_selection.go#L200)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come this was needed?
</blockquote></details>

Otherwise the output of EXPLAIN will be polluted with a hint "force index: @blah" even after the hint was consumed and the desired index already properly appears on the first line of the scan's description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12605)*

**Pull request merged**
