### PR TITLE
colserde: optimize the arrow batch converter

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR contains several commits that optimize the arrow batch converter (mostly in the batch-to-arrow direction). Please see each commit for details.

The comparison of all benchmarks in `colserde` package between the second and the last commits is [here](https://gist.github.com/yuzefovich/97c514b772e5bf1bc63f584203e6deaf).

Epic: CRDB-14837

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
:lgtm: Nice improvements! I'll defer to @michae2 for final approval.

> Reviewed 8 of 8 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 9 of 9 files at r4, 8 of 8 files at r5, 9 of 9 files at r6, 2 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-:-NKLJH8lCgM7T7Sp7sZH:b-tsse4k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/col/coldata/bytes.go` line 599 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKLIYVl606VAvv7NFGf:-NKLIYVl606VAvv7NFGg:b6ez2s6) ([raw file](https://github.com/cockroachdb/cockroach/blob/84be9b530e80e9f7b04a4f7e196e981baa7c3405/pkg/col/coldata/bytes.go#L599)):*
> ```Go
> 
> 	// Now populate the offsets slice which conforms to the arrow format and has
> 	// the correct length.
> ```

What breaks without the padding? On the face of it it seems like we should be able to "trick" the arrow format into behaving as if there are always just two elements.
___
*[`pkg/col/colserde/arrowbatchconverter.go` line 224 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKLC8Vp6xvS3vSq0wXF:-NKLC8Vp6xvS3vSq0wXG:b-fcn7zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/34975bf489ed0fd7abd2b0a59c5564df2c3a0f88/pkg/col/colserde/arrowbatchconverter.go#L224)):*
> ```Go
> 				intervalSize := int(memsize.Int64) * 3
> 				if cap(values) < intervalSize*n {
> 					values = make([]byte, intervalSize*n)
> ```

[nit] For symmetry, can we set the length to zero here as in the other cases?
___
*[`pkg/col/colserde/arrowbatchconverter.go` line 536 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKLGe5n7drb7cGxvhMJ:-NKLGe5n7drb7cGxvhMK:bbbs2b8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4098f183c2f1695cf8bcc078ac00f224c0f429c7/pkg/col/colserde/arrowbatchconverter.go#L536)):*
> ```Go
> 	}
> 	offsets := bytesArr.ValueOffsets()
> 	return valueBytes, offsets[:batchLength+1]
> ```

Why do we no longer need to cap the slices?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94191)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/col/coldata/bytes.go` line 599 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKLIYVl606VAvv7NFGf:-NKLNlLw3ibWzn4tMb5K:b-8bfde5) ([raw file](https://github.com/cockroachdb/cockroach/blob/84be9b530e80e9f7b04a4f7e196e981baa7c3405/pkg/col/coldata/bytes.go#L599)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

What breaks without the padding? On the face of it it seems like we should be able to "trick" the arrow format into behaving as if there are always just two elements.
</blockquote></details>

Indeed, in isolation, it would work. However, then the question is what length do we use for this arrow vector? We'd use the length of 2, and then we might end up in a situation where vectors in `[]array.Data` have different lengths. This makes `RecordBatchSerializer` complain that the vectors are of unexpected length. We could remove that assertion, but it doesn't seem worth it to make this "arrow-like" format even more hacky and we'd probably have to teach `RecordBatchSerializer` about these possibly different lengths.
___
*[`pkg/col/colserde/arrowbatchconverter.go` line 224 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKLC8Vp6xvS3vSq0wXF:-NKLL1eECecQ_5R3YZFq:bsg8gga) ([raw file](https://github.com/cockroachdb/cockroach/blob/34975bf489ed0fd7abd2b0a59c5564df2c3a0f88/pkg/col/colserde/arrowbatchconverter.go#L224)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] For symmetry, can we set the length to zero here as in the other cases?
</blockquote></details>

No, not easily at least - unlike for other types where we append the serialized versions, for intervals we write directly into the byte slice with `PutUint64`.
___
*[`pkg/col/colserde/arrowbatchconverter.go` line 536 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKLGe5n7drb7cGxvhMJ:-NKLLk4hBP-D2ut_tjeM:bnlulnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4098f183c2f1695cf8bcc078ac00f224c0f429c7/pkg/col/colserde/arrowbatchconverter.go#L536)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Why do we no longer need to cap the slices?
</blockquote></details>

This is no longer needed since we changed how `coldata.Bytes` vector works. Up until about a year ago we had an implementation that was effectively how the Arrow implements it (large `[]byte` and `offsets []int32`), so when converting from the arrow format, we'd just use these two slices directly. However, there was a possible corruption scenario as described in the comment that is being removed here, so we needed the explicit capping.

Now we have a different implementation of the Bytes vector, and we never just use the slices as is - we always have to copy out the data from the arrow format into our own `coldata.Bytes` implementation. The last commit in this PR changed things to our "arrow-like" format for serialization, but we still perform the copy out of the values and the offsets slices. Thus, the memory corruption is not possible.

That memory corruption _is_ possible for "simple" types where we cast the slices directly (bools, ints, and floats), and there we do have to set the capacity. There is a brief mention of this in a comment:
```
			// However, we have to be careful to set the capacity on each slice
			// explicitly to protect memory regions that come after the slice
			// from corruption in case the slice will be appended to in the
			// future.
```
but I decided not to adjust an example of how that corruption could previously occur in bytes to how it can still occur in ints.

**Comment by DrewKimball** [comment]
Thanks for the explanations!

**Review by michae2 — COMMENTED** [review]
:lgtm: Very nice! Some questions but I couldn't find anything wrong, this looks great!

> Reviewed 8 of 8 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 2 of 9 files at r4, 17 of 17 files at r9, 3 of 3 files at r10, 2 of 2 files at r11, 9 of 9 files at r12, 8 of 8 files at r13, 9 of 9 files at r14, 2 of 2 files at r15, 3 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-:-NKsfBtFC6TgTl8OpYk1:b-4i31b4)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/col/coldata/bytes.go` line 596 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKVY6blEm4scpCB_2en:-NKVY6blEm4scpCB_2eo:b-5lz9dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa5f4ff384333c8e7b9e841d41d6e0b97e0cf50/pkg/col/coldata/bytes.go#L596)):*
> ```Go
> 	}
> 	data = append(data, bytes...)
> 	data = append(data, b.buffer...)
> ```

Random though (I think you had this thought too): after lots of calls to `Set` the buffer could be very fragmented, and maybe a defragmented and sorted `buffer` might speed up later operations.

But on the other hand, that isn't a sure thing, and it requires walking all elements, just like before, so it wouldn't have the same speedup. (And maybe it could be accomplished more easily by performing a defragment after set-heavy operations, rather than here.) What you have here seems better.
___
*[`pkg/col/coldata/bytes.go` line 602 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKscfAnCAxopeG3qyrm:-NKscfAnCAxopeG3qyrn:bpagzpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa5f4ff384333c8e7b9e841d41d6e0b97e0cf50/pkg/col/coldata/bytes.go#L602)):*
> ```Go
> 	offsets = append(offsets, int32(len(bytes)))
> 	for i := 2; i <= n; i++ {
> 		offsets = append(offsets, int32(len(data)))
> ```

It might be slightly faster to put 0 for all of the offsets except the last two (instead of `len(data)` for all of the offsets except the first two).
___
*[`pkg/col/coldata/bytes.go` line 611 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKseA3s5GAayRf4Bdtr:-NKseA3s5GAayRf4Bdts:b-5i4yf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa5f4ff384333c8e7b9e841d41d6e0b97e0cf50/pkg/col/coldata/bytes.go#L611)):*
> ```Go
> func (b *Bytes) Deserialize(data []byte, offsets []int32) {
> 	n := len(offsets) - 1
> 	b.elements = b.elements[:n]
> ```

Is `elements` guaranteed to have length >= n?
___
*[`pkg/col/coldatatestutils/random_testutils.go` line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKK8ht22PSWBCNqbNlR:-NKK8ht22PSWBCNqbNlS:b-ao26sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce0db8eb98088d234a95a864d613196e48078d7b/pkg/col/coldatatestutils/random_testutils.go#L238)):*
> ```Go
> 
> // RandomBatch returns a batch with a capacity of capacity and a number of
> // random elements equal to length (capacity if length is 0).
> ```

nit: Might be nice to say in this comment that `args.N` and `args.Vec` are ignored.
___
*[`pkg/col/colserde/arrowbatchconverter.go` line 290 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKQ2-tH4BnApBqSa_aG:-NKQ2-tH4BnApBqSa_aH:b-xqu8yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f32f935e5e11092dc6e97ecff9b14f20a1505df/pkg/col/colserde/arrowbatchconverter.go#L290)):*
> ```Go
> // ArrowToBatch converts []*array.Data to a coldata.Batch. There must not be
> // more than coldata.BatchSize() elements in data. It's safe to call ArrowToBatch
> // concurrently.
> ```

Is this not true any more? (That `ArrowToBatch` can be called concurrently?) Seems like this commit (4th) wouldn't have changed this.
___
*[`pkg/col/colserde/arrowbatchconverter.go` line 74 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKPyGjQ--4RsXwz7i4x:-NKPyGjQ--4RsXwz7i4y:bkpy6yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/840c5cbf1a7880d4bdfb6b4bb79bea682b0a694a/pkg/col/colserde/arrowbatchconverter.go#L74)):*
> ```Go
> 			c.scratch.buffers[i][j] = &buffers[buffersIdx]
> 			buffersIdx++
> 		}
> ```

~nit: Maybe I'm not understanding something, but it seems like there is an extra layer of indirection here. Could `buffers` be `[][]memory.Buffer` instead of `[][]*memory.Buffer`? Then maybe we could do something like `c.scratch.buffers[i] = buffers[j:k]` where j and k are computed in this loop over `typs`? Then we don't need to allocate space for the pointers.~

EDIT: never mind, I see that `array.Data.Reset` wants a slice of pointers. Oh well. Maybe we could pre-allocate the pointers, too?
___
*[`pkg/col/colserde/arrowbatchconverter.go` line 496 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKQ2wmABAzR5lrivIL8:-NKQ2wmABAzR5lrivIL9:b-13ck0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/840c5cbf1a7880d4bdfb6b4bb79bea682b0a694a/pkg/col/colserde/arrowbatchconverter.go#L496)):*
> ```Go
> 		// Eagerly release our data references to make sure they can be collected
> 		// as quickly as possible as we copy each (or simply reference each) by
> 		// coldata.Vecs below.
> ```

nit: remove "below"
___
*[`pkg/sql/execinfra/version.go` line 80 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKVB_2k-3kfDtXMlV7N:-NKVB_2k-3kfDtXMlV7O:b-xs4af0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9740d540b40516f5bccc8eda04ce93e46d0633/pkg/sql/execinfra/version.go#L80)):*
> ```Go
> 
> - Version: 71 (MinAcceptedVersion: 71)
>   - On-wire representation of booleans in the Arrow format has changed.
> ```

You've told me this before (sorry!), but how do distsql upgrades work again? Do we disallow distsql programs spanning versions? Do we disallow distsql completely during upgrades?
___
*[`pkg/col/colserde/conversion_test.go` line 76 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKPn2cz-raDfD-qkWT7:-NKPn2cz-raDfD-qkWT8:b9ibarh) ([raw file](https://github.com/cockroachdb/cockroach/blob/525b9cd70a390b34c24656e2408b939c49ed4fb9/pkg/col/colserde/conversion_test.go#L76)):*
> ```Go
> 			require.NoError(b, err)
> 			s, err := colserde.NewRecordBatchSerializer([]*types.T{typ})
> 			require.NoError(b, err)
> ```

~nit: Why not use `createSerializer` again here? (Am I missing something obvious?)~

EDIT: oh, because of the direction of the conversion, never mind.

**Review by michae2 — APPROVED** [review]

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-:-NKtC-1REVRlDGiAIDZd:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/col/coldata/bytes.go` line 596 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKVY6blEm4scpCB_2en:-NKshfxP2yembKWKxQUf:brg2rc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa5f4ff384333c8e7b9e841d41d6e0b97e0cf50/pkg/col/coldata/bytes.go#L596)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Random though (I think you had this thought too): after lots of calls to `Set` the buffer could be very fragmented, and maybe a defragmented and sorted `buffer` might speed up later operations.

But on the other hand, that isn't a sure thing, and it requires walking all elements, just like before, so it wouldn't have the same speedup. (And maybe it could be accomplished more easily by performing a defragment after set-heavy operations, rather than here.) What you have here seems better.
</blockquote></details>

I thought about spending more time to optimize this fragmented case but decided not to since it doesn't seem worth it - my intuition says that the cases when the Bytes vector ends up being very fragmented are quite rare since we generally perform Sets in increasing order of indices. (I think the main case when out-of-order Sets can happen is for top K sort.)
___
*[`pkg/col/coldata/bytes.go` line 611 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKseA3s5GAayRf4Bdtr:-NKsn0ak2REMexjVcoSd:b7yrj8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa5f4ff384333c8e7b9e841d41d6e0b97e0cf50/pkg/col/coldata/bytes.go#L611)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is `elements` guaranteed to have length >= n?
</blockquote></details>

I think in practice this is always the case, but it's better to be safe here (previously we did have the capacity check, so I added it back).
___
*[`pkg/col/coldatatestutils/random_testutils.go` line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKK8ht22PSWBCNqbNlR:-NKst9HY63cufLR0uuUY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce0db8eb98088d234a95a864d613196e48078d7b/pkg/col/coldatatestutils/random_testutils.go#L238)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Might be nice to say in this comment that `args.N` and `args.Vec` are ignored.
</blockquote></details>

Done.
___
*[`pkg/col/colserde/arrowbatchconverter.go` line 290 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKQ2-tH4BnApBqSa_aG:-NKst_ii2iyddczG1JEF:b4rae8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f32f935e5e11092dc6e97ecff9b14f20a1505df/pkg/col/colserde/arrowbatchconverter.go#L290)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is this not true any more? (That `ArrowToBatch` can be called concurrently?) Seems like this commit (4th) wouldn't have changed this.
</blockquote></details>

I think it is still true, but we don't use this anywhere, so when I was modifying the code, I decided to remove the mention of concurrency-safety to avoid possible confusion (initially, I was confused where we needed this concurrency-safety).
___
*[`pkg/col/colserde/arrowbatchconverter.go` line 74 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKPyGjQ--4RsXwz7i4x:-NKtB0srDNO6RpVHteNi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/840c5cbf1a7880d4bdfb6b4bb79bea682b0a694a/pkg/col/colserde/arrowbatchconverter.go#L74)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

~nit: Maybe I'm not understanding something, but it seems like there is an extra layer of indirection here. Could `buffers` be `[][]memory.Buffer` instead of `[][]*memory.Buffer`? Then maybe we could do something like `c.scratch.buffers[i] = buffers[j:k]` where j and k are computed in this loop over `typs`? Then we don't need to allocate space for the pointers.~

EDIT: never mind, I see that `array.Data.Reset` wants a slice of pointers. Oh well. Maybe we could pre-allocate the pointers, too?
</blockquote></details>

Done.
___
*[`pkg/sql/execinfra/version.go` line 80 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/94191#-NKVB_2k-3kfDtXMlV7N:-NKtBTMd5rpERJrcx6Oz:b-gpy4jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba9740d540b40516f5bccc8eda04ce93e46d0633/pkg/sql/execinfra/version.go#L80)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

You've told me this before (sorry!), but how do distsql upgrades work again? Do we disallow distsql programs spanning versions? Do we disallow distsql completely during upgrades?
</blockquote></details>

The gateway node of a distributed plan specifies the DistSQL version that the plan has and attempts to only use the nodes in the cluster that match that version. If it ever happens that a remote node receives `SetupFlowRequest` with a DistSQL version different from what the flow spec is asking for, then the query errors out (this could happen during upgrades). In other words, if we ever actually get to executing the plan on a particular node, then we know for sure that we're using the correct DistSQL version.

**Pull request merged**
