### PR TITLE
lint: change vet -shadow to subtest calling -vettool=shadow

### PR DESCRIPTION
**Pull request by dt**
-shadow was removed in go 1.12.

Release note: None

### CODE REVIEW

**Comment by dt** [comment]
looks like opt and exec both have some shadowing in generated code that we might want to either ignore or fix.

staticcheck also failed for me with some unexpected errors like `identical expressions on the left and right side of the '==' operator` pointing to lines that didn't have comparisons on them, so I might just need to clean or something, but I suspect that is unrelated to vet change.

**Review by bdarnell — APPROVED** [review]
LGTM. I assume this version works for both go 1.11 and 1.12?

The "identical expressions" thing is https://github.com/dominikh/go-tools/issues/430

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36486#-:-LbYg_nc3Gfj3egNvLcB:b-gtjyxr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by dt** [comment]
I checked that `build/builder`'s `go` had the `vettool` flag, and it looks like the CI, running 1.11, ran it so I think so.

I need to check with opt and exec about those shadowing errors, then I think this is okay for master / go 1.11 as is, and I'll file a separate issue for the assignment thing.

**Comment by dt** [comment]
I fixed the filtering of shadowing errors from generated code (it has started including line offset in with line number which broke the regex).

**Review by nvb — APPROVED** [review]
:lgtm: thanks!

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36486#-:-LbZX1rC1Z-gkVZLyPxH:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/testutils/lint/lint_test.go, line 1301 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36486#-LbZWxel7n5qNGFIw_gr:-LbZWxem17WaeRwcfgyE:bd1tye7) ([raw file](https://github.com/cockroachdb/cockroach/blob/af626c40eaa62a57cafe1d80abb6c896b2134764/pkg/testutils/lint/lint_test.go#L1301)):*
> ```Go
> 				stream.GrepNot(`\.[eo]g\.go:[0-9:]+: declaration of ".*" shadows`),
> 				stream.GrepNot(`^#`), // comment line
> 				// Upstream compiler error. See: https://github.com/golang/go/issues/23701
> ```

Can we get rid of this now that https://github.com/golang/go/issues/23701 is closed?
___
*[pkg/testutils/lint/lint_test.go, line 1346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36486#-LbZWe57-v0owGcYdflL:-LbZWe57-v0owGcYdflM:b-1t783f) ([raw file](https://github.com/cockroachdb/cockroach/blob/af626c40eaa62a57cafe1d80abb6c896b2134764/pkg/testutils/lint/lint_test.go#L1346)):*
> ```Go
> 		}, ",")
> 
> 		// unfortunately if an analyzer is passed via -vettool like shadow, it seems
> ```

Capital "unfortunately"

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36486)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/testutils/lint/lint_test.go, line 1301 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36486#-LbZWxel7n5qNGFIw_gr:-LbZdJmW9rTtOj0URAFR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af626c40eaa62a57cafe1d80abb6c896b2134764/pkg/testutils/lint/lint_test.go#L1301)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we get rid of this now that https://github.com/golang/go/issues/23701 is closed?
</blockquote></details>

Done.
___
*[pkg/testutils/lint/lint_test.go, line 1346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36486#-LbZWe57-v0owGcYdflL:-LbZeh5A5bmAJMrP179S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af626c40eaa62a57cafe1d80abb6c896b2134764/pkg/testutils/lint/lint_test.go#L1346)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Capital "unfortunately"
</blockquote></details>

Done.

**Comment by dt** [comment]
@bdarnell should we backport this and #36527 to linting on release branch also happy on 1.12? the CI will stay on go 1.11 I assume thanks to the builder, so it'd mostly be for local dev once people have upgraded to 1.12, but personally, I don't usually run `lint` on release branches so don't know how important that actually would be. I guess it'd stave off `vendor` ref diverging and making dep backports harder, but that seems inevitable so I don't know if that's really a motivating factor.

**Comment by bdarnell** [comment]
I think the frozen builder is good enough for when we're working on older branches, so I wouldn't backport this (but I also wouldn't object to backporting it).

**Pull request merged**
