### PR TITLE
sql: Adding support for show indexes from database command

### PR DESCRIPTION
**Pull request by rohany**
As requested in #37270, support for a show indexes from database command would be helpful. This PR includes support for the command in the parser. Future PR's will implement the functionality of the parsed results.

### CODE REVIEW

**Comment by rohany** [comment]
I updated the command to be `SHOW DBINDEXES`, as opposed to `SHOW INDEXES FROM DATABASE <database>`, due to some parsing issues for error messages.

**Review by solongordon — CHANGES_REQUESTED** [review]
Hm, to be honest I don't love `SHOW DBINDEXES`, I think because it implies that a `DBINDEX` is something different from an `INDEX`. If `SHOW INDEXES FROM DATABASE` is definitely unworkable, maybe we could go with `SHOW DATABASE INDEXES` or `SHOW ALL INDEXES`? @knz might have an opinion about this.

Also we probably want to support the same aliases that `SHOW INDEXES` does, namely `SHOW INDEX` and `SHOW KEYS`. See https://www.cockroachlabs.com/docs/stable/show-index.html.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-:-LgSeyFp9MduVQ9AVsRq:bq44am3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187 and @solongordon)

**Comment by rohany** [comment]
I like show all indexes, i think that makes alot of sense.

**Comment by knz** [comment]
I don't understand what problem you are encountering. The following patch works fine for me:

```diff
modified   pkg/sql/parser/sql.y
@@ -3347,7 +3347,7 @@ show_grants_stmt:

 // %Help: SHOW INDEXES - list indexes
 // %Category: DDL
-// %Text: SHOW INDEXES FROM <tablename>
+// %Text: SHOW INDEXES FROM { <tablename> | DATABASE <databasename> }
 // %SeeAlso: WEBDOCS/show-index.html
 show_indexes_stmt:
   SHOW INDEX FROM table_name
@@ -3359,6 +3359,10 @@ show_indexes_stmt:
   {
     $$.val = &tree.ShowIndexes{Table: $4.unresolvedObjectName()}
   }
+| SHOW INDEXES FROM DATABASE database_name
+  {
+    $$.val = &tree.ShowIndexes{}
+  }
 | SHOW INDEXES error // SHOW HELP: SHOW INDEXES
 | SHOW KEYS FROM table_name
   {
```

What's the problem?

(I also think that `SHOW INDEXES` without a `FROM` should be equivalent to `SHOW INDEXES FROM DATABASE` applied to the current database.)

**Comment by rohany** [comment]
I was trying to display a different help message for the show indexes from database command. If I did the above and try and show a different message then I ran into issues differentiating the two.

**Comment by knz** [comment]
Keep the single error message, using the diff above -- this will be sufficient.

**Review by knz — COMMENTED** [review]
Good progress. Next step is to update the parser tests.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-:-LgSvs0B3wjU7Cg1lvIi:b-smgnyd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187)

**Comment by rohany** [comment]
I'm just pulling in changes from the backend implementation as well, this way I can include the tests there. Overall its a small change, so no point in splitting it up into multiple PRs.

**Review by knz — COMMENTED** [review]
Good progress. Next step is to properly handle more complex database names.

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-:-LgT2cK711RarsowsEex:b5wo108)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187 and @rohany)

___
*[pkg/sql/delegate/show_table.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-LgT24O56tG6Gentj6cz:-LgT24O56tG6Gentj6d-:b-ak453b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba3800f590bbc015179ef232fb467b2fb2c9f9aa/pkg/sql/delegate/show_table.go#L48)):*
> ```Go
>            implicit::BOOL
>     FROM %s.information_schema.statistics`
> 	return parse(fmt.Sprintf(getAllIndexesQuery, n.Database))
> ```

This `Sprintf` is suspicious. Please consider how `showTableDetails` injects the database name and verify the same is done here.

Also please add a test with a database name containing special characters.
___
*[pkg/sql/logictest/testdata/logic_test/show_source, line 350 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-LgT1v1PEcElwZNW8MuH:-LgT1v1PEcElwZNW8MuI:bc72dcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba3800f590bbc015179ef232fb467b2fb2c9f9aa/pkg/sql/logictest/testdata/logic_test/show_source#L350)):*
> ```
> ----
> table1 primary false 1 key1 ASC false false
> table2 primary false 1 key2 ASC false false
> ```

nit: missing newline at end of file
___
*[pkg/sql/sem/tree/show.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-LgT1drp5eH2UQ_32r0-:-LgT1drq36eKUxzwepkl:b-ses46x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba3800f590bbc015179ef232fb467b2fb2c9f9aa/pkg/sql/sem/tree/show.go#L159)):*
> ```Go
> 
> // ShowDbIndexes represents a SHOW INDEXES FROM DATABASE statement.
> type ShowDbIndexes struct {
> ```

style: the word is not so long that an abbreviation is warranted here. You can spell `ShowDatabaseIndexes` in full.
___
*[pkg/sql/sem/tree/show.go, line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-LgT2Q3L4qvVGGLpfhS0:-LgT2Q3L4qvVGGLpfhS1:b-7gard) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba3800f590bbc015179ef232fb467b2fb2c9f9aa/pkg/sql/sem/tree/show.go#L160)):*
> ```Go
> // ShowDbIndexes represents a SHOW INDEXES FROM DATABASE statement.
> type ShowDbIndexes struct {
> 	Database string
> ```

This is not a `string`, it should be a `Name`. You can imitate `DropDatabase`.
___
*[pkg/sql/sem/tree/show.go, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-LgT2WFD9EADJ-q8iP_P:-LgT2WFD9EADJ-q8iP_Q:bh2tjsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba3800f590bbc015179ef232fb467b2fb2c9f9aa/pkg/sql/sem/tree/show.go#L166)):*
> ```Go
> func (node *ShowDbIndexes) Format(ctx *FmtCtx) {
> 	ctx.WriteString("SHOW INDEXES FROM DATABASE ")
> 	ctx.WriteString(node.Database)
> ```

`ctx.FormatNode`; again imitate `DropDatabase`.
___
*[pkg/sql/sem/tree/stmt.go, line 697 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-LgT1ouXEW6NZ81IvmRi:-LgT1ouXEW6NZ81IvmRj:b-ak1poj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba3800f590bbc015179ef232fb467b2fb2c9f9aa/pkg/sql/sem/tree/stmt.go#L697)):*
> ```Go
> 
> // StatementTag returns a short string identifying the type of statement.
> func (*ShowIndexes) StatementTag() string { return "SHOW INDEXES" }
> ```

maybe change this to add `FROM TABLE`

**Comment by rohany** [comment]
@knz I addressed your comments. Regarding the Sprintf, the way I have done it is how showTableDetails substitutes in the database name as well.

**Review by knz — APPROVED** [review]
LGTM. You may want to configure your editor to apply `crlfmt` automatically upon saving a file.

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-:-LgTK15_2a3clRil19a8:b-4uwkpr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187 and @rohany)

___
*[pkg/sql/delegate/show_table.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-LgT24O56tG6Gentj6cz:-LgTJcER5nGjpbempRPi:bvurlgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba3800f590bbc015179ef232fb467b2fb2c9f9aa/pkg/sql/delegate/show_table.go#L48)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This `Sprintf` is suspicious. Please consider how `showTableDetails` injects the database name and verify the same is done here.

Also please add a test with a database name containing special characters.
</blockquote></details>

Yes this works now because `Database` has become a `Name`. IF you had kept it a `string`, then the `Sprintf` would be inappropriate as-is.
___
*[pkg/sql/parser/parse_test.go, line 414 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37942#-LgTJlWV8FXquvAnyx3I:-LgTJlWV8FXquvAnyx3J:b-9esluz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb6b6d6502c6fd75ce97724e38a37d4f137d4da/pkg/sql/parser/parse_test.go#L414)):*
> ```Go
> 		{`SHOW INDEXES FROM a.b.c`},
> 		{`SHOW INDEXES FROM DATABASE a`},
> 		{`SHOW INDEXES FROM DATABASE "$speci@ltest"`},
> ```

nit: this is OK but we typically don't test special characters throughout the parser tests

**Pull request merged**
