### PR TITLE
workload: cache DNS lookups by default

### PR DESCRIPTION
**Pull request by sean-**
By default, DNS lookups used by jackc/pgx are now cached for 30s.  A negative duration will disable the caching behavior.

While performing load testing, at higher connection counts with lower connection rates, it was possible to overwhelm the default environment DNS resolvers.

Epic: none
Release note: None

### CODE REVIEW

**Review by srosenberg — COMMENTED** [review]
> By default, DNS lookups used by jackc/pgx are now cached for 30s. A negative duration will disable the caching behavior.

What was the previous default? 30s for DNS seems way too frequent, why do we need to refresh DNS so often?

> While performing load testing, at higher connection counts with lower connection rates, it was possible to overwhelm the default environment DNS resolvers.

What were the default environment DNS resolvers? What was the connection count and frequency of resets. I guess I am surprised that DNS is implicated, considering we're nowhere near its limits afaik.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108378#-:-NbLzjhP7pHtera2JFaq:bo0utpl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @rachitgsrivastava)

**Review by sean- — COMMENTED** [review]
> What was the previous default? 30s for DNS seems way too frequent, why do we need to refresh DNS so often?

No caching.  Every DNS lookup would reach out to the host's resolver, in this case AWS Route53.  I vacillated between 5s, 30s, and 60s, but went with 30s since that matches AWS's Route53 default health check interval.

https://aws.amazon.com/blogs/aws/route-53-health-check-improvements-faster-interval-and-configurable-failover/

> What were the default environment DNS resolvers? What was the connection count and frequency of resets. I guess I am surprised that DNS is implicated, considering we're nowhere near its limits afaik.

AWS recursive DNS resolver.

It doesn't take much to get to 10K queries per second when every new connection is a new DNS lookup.

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-entities-resolver

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108378#-:-NbM7HLH4D1FMX-sSxmC:b-qk55yx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @rachitgsrivastava)

**Review by srosenberg — APPROVED** [review]
I kicked off a [smoke test](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11242698?buildTab=log&focusLine=2505&logView=linear). Once it's green, this should be ok to merge. Since roachtests use internal ips (see
`maybeExpandPgURL`) by default, this shouldn't have any effect on them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108378#-:-NbMBVAYEdQmrwN4nN2N:b2tufre)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @rachitgsrivastava)

**Review by fqazi — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108378)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @rachitgsrivastava)

**Pull request merged**
