### PR TITLE
kv: assorted client optimizations

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

This PR increases throughput on a single node kv-95 workload as follows (measured on a 96-core GCE machine and running the client with concurrency=48).
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1257869        12578.5      2.8      3.3      5.5      7.1     48.2  read
  100.0s        0          66469          664.7     19.5     19.9     31.5     35.7     60.8  write
```
to
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1369178        13691.4      2.5      2.8      5.2      6.8    503.3  read
  100.0s        0          71850          718.5     18.3     18.9     28.3     33.6    520.1  write
```

The PR also takes away about 3/4 of the performance regression introduced in #28185. See #30208 for more.

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @jordanlewis

**Comment by jordanlewis** [comment]
Nice! But where do you get the 3/4 number? The delta I observed before and after the linked PR was very high - the runs were variable, but up to about 50% (13k -> 20k). I can show you how to reproduce that if you like. It's true that it's hard to benchmark, but averages of repeated, interleaved runs don't lie.

**Comment by andreimatei** [comment]
Jordan, replied in https://github.com/cockroachdb/cockroach/issues/30208#issuecomment-423245107

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30448)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/txn.go, line 520 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-LMsFkeW-tTQYOZ5SU_t:-LMsFkeW-tTQYOZ5SU_u:b-xkd6gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/154e79dd23dc7eb3188eeb08ddcb3bc2d53b0411/pkg/internal/client/txn.go#L520)):*
> ```Go
> 	// ba.Add(endTxnReq(true /* commit */, txn.deadline(), txn.systemConfigTrigger))
> 	_, pErr := txn.Send(ctx, *ba)
> 	commitReqPool.Put(ba)
> ```

Is this safe? We should be clearing the `ba` before adding it to the `sync.Pool`, not after. Will that cause issues with `raceTransport`?
___
*[pkg/kv/txn_coord_sender.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-LMsFcWF7zdSAN8N0gb2:-LMsFcWF7zdSAN8N0gb3:bgplwbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d2942c508f2486a75c7727f35692d810c4635ee/pkg/kv/txn_coord_sender.go#L585)):*
> ```Go
> 	defer tc.mu.Unlock()
> 
> 	if ba.IsSingleEndTransactionRequest() && !tc.interceptorAlloc.txnHeartbeat.mu.everSentBeginTxn {
> ```

Does this need to be after `maybeRejectClientLocked`?

**Review by andreimatei — COMMENTED** [review]
Removed the commit about the reuse of EndTxn requests until #30485 settles.



TPAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-:-LNByl3KBA6OyY-bqKrp:boanj61)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_coord_sender.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-LMsFcWF7zdSAN8N0gb2:-LMyGGCC0M_1wtz_bUY_:b-ygle90) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d2942c508f2486a75c7727f35692d810c4635ee/pkg/kv/txn_coord_sender.go#L585)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to be after `maybeRejectClientLocked`?
</blockquote></details>

I guess that's safer indeed. done
___
*[pkg/internal/client/txn.go, line 520 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-LMsFkeW-tTQYOZ5SU_t:-LMyFkEi-pWHVT_o9wu5:bwg0iug) ([raw file](https://github.com/cockroachdb/cockroach/blob/154e79dd23dc7eb3188eeb08ddcb3bc2d53b0411/pkg/internal/client/txn.go#L520)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this safe? We should be clearing the `ba` before adding it to the `sync.Pool`, not after. Will that cause issues with `raceTransport`?
</blockquote></details>

reworked

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r5, 3 of 3 files at r6, 3 of 3 files at r7, 2 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30448)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_interceptor_metrics.go, line 99 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-LNFLN9j3yoJiGBI9Vqw:-LNFLN9j3yoJiGBI9Vqx:bkcc753) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5faebc1d3bfe49bbbad90df4aa37008151627d1/pkg/kv/txn_interceptor_metrics.go#L99)):*
> ```Go
> 	// it artificially (in the parallel execution queue).
> 	if restarts > 0 {
> 		m.metrics.Restarts.RecordValue(restarts)
> ```

Won't this mess up the histogram by skewing its distribution away from 0? How much of an effect does this have on performance?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30448)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_interceptor_metrics.go, line 99 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-LNFLN9j3yoJiGBI9Vqw:-LNGmvwx0cAX9gBbIA49:b-u67v9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5faebc1d3bfe49bbbad90df4aa37008151627d1/pkg/kv/txn_interceptor_metrics.go#L99)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Won't this mess up the histogram by skewing its distribution away from 0? How much of an effect does this have on performance?
</blockquote></details>

yes, it will skew the histogram. I've added a TODO to optimize the histogram code so we don't have to do this.

Here's some results with this PR backported on top of the commit that introduced the perf regression (69fa9f7cff371ce00594770cebf772886ff9d445). `backport` is the PR as is, `record_all_backports` is if we record the restarts for all txns. There appears to be a pretty significant difference.

```
Tuesday, 24 core
backport:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1801235        18012.2      1.9      1.5      4.5      6.0     37.7  read
  100.0s        0          94877          948.8     14.4     13.6     25.2     29.4     48.2  write
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1862335        18623.2      1.8      1.4      4.5      5.8     35.7  read
  100.0s        0          97708          977.1     13.9     13.6     24.1     28.3     48.2  write
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1881041        18810.0      1.8      1.4      4.5      5.8     41.9  read
  100.0s        0          98603          986.0     13.8     13.6     24.1     28.3     48.2  write
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1859887        18598.7      1.8      1.4      4.5      5.8     33.6  read
  100.0s        0          97774          977.7     14.0     13.6     24.1     29.4     50.3  write

backport-record_all_backports:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1818145        18181.3      1.9      1.5      4.5      5.8    436.2  read
  100.0s        0          95332          953.3     14.3     13.6     24.1     29.4    453.0  write
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1819280        18192.7      1.9      1.4      4.5      6.0     31.5  read
  100.0s        0          95799          958.0     14.5     14.2     25.2     30.4     50.3  write
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1791759        17917.4      1.9      1.5      4.5      6.0     48.2  read
  100.0s        0          94375          943.7     14.7     14.2     25.2     30.4     50.3  write

96 core
backport:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1670523        16705.1      2.1      1.7      4.7      6.0    130.0  read
  100.0s        0          88173          881.7     15.4     14.7     26.2     30.4    234.9  write

backport-record_all_backports:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1596959        15969.5      2.2      1.8      4.7      6.3    142.6  read
  100.0s        0          84326          843.3     16.0     15.7     27.3     31.5    226.5  write
```

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-:-LNGsIVkEg_6h4gu5yaX:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/kv/txn_interceptor_metrics.go, line 99 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-LNFLN9j3yoJiGBI9Vqw:-LNGsJ1K0fcnJtOuRjQd:bnr258z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5faebc1d3bfe49bbbad90df4aa37008151627d1/pkg/kv/txn_interceptor_metrics.go#L99)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

yes, it will skew the histogram. I've added a TODO to optimize the histogram code so we don't have to do this.

Here's some results with this PR backported on top of the commit that introduced the perf regression (69fa9f7cff371ce00594770cebf772886ff9d445). `backport` is the PR as is, `record_all_backports` is if we record the restarts for all txns. There appears to be a pretty significant difference.

```
Tuesday, 24 core
backport:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1801235        18012.2      1.9      1.5      4.5      6.0     37.7  read
  100.0s        0          94877          948.8     14.4     13.6     25.2     29.4     48.2  write
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1862335        18623.2      1.8      1.4      4.5      5.8     35.7  read
  100.0s        0          97708          977.1     13.9     13.6     24.1     28.3     48.2  write
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1881041        18810.0      1.8      1.4      4.5      5.8     41.9  read
  100.0s        0          98603          986.0     13.8     13.6     24.1     28.3     48.2  write
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1859887        18598.7      1.8      1.4      4.5      5.8     33.6  read
  100.0s        0          97774          977.7     14.0     13.6     24.1     29.4     50.3  write

backport-record_all_backports:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1818145        18181.3      1.9      1.5      4.5      5.8    436.2  read
  100.0s        0          95332          953.3     14.3     13.6     24.1     29.4    453.0  write
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1819280        18192.7      1.9      1.4      4.5      6.0     31.5  read
  100.0s        0          95799          958.0     14.5     14.2     25.2     30.4     50.3  write
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1791759        17917.4      1.9      1.5      4.5      6.0     48.2  read
  100.0s        0          94375          943.7     14.7     14.2     25.2     30.4     50.3  write

96 core
backport:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1670523        16705.1      2.1      1.7      4.7      6.0    130.0  read
  100.0s        0          88173          881.7     15.4     14.7     26.2     30.4    234.9  write

backport-record_all_backports:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  100.0s        0        1596959        15969.5      2.2      1.8      4.7      6.3    142.6  read
  100.0s        0          84326          843.3     16.0     15.7     27.3     31.5    226.5  write
```
</blockquote></details>

Thanks for taking the measurements. I don't want to hold this PR up any longer and I think I'm ok with an incorrect metric, but please open an issue to correct this historgram and also to explore optimizing other histograms that have a very common bucket.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30448)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/kv/txn_interceptor_metrics.go, line 99 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-LNFLN9j3yoJiGBI9Vqw:-LNGvJ583WbKXyqtzfMp:b67ldz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5faebc1d3bfe49bbbad90df4aa37008151627d1/pkg/kv/txn_interceptor_metrics.go#L99)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Thanks for taking the measurements. I don't want to hold this PR up any longer and I think I'm ok with an incorrect metric, but please open an issue to correct this historgram and also to explore optimizing other histograms that have a very common bucket.
</blockquote></details>

Is the `txn.restarts` histogram even used?

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30448)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/kv/txn_interceptor_metrics.go, line 99 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-LNFLN9j3yoJiGBI9Vqw:-LNGyY9j5yODfRQNMRNR:bht3sh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5faebc1d3bfe49bbbad90df4aa37008151627d1/pkg/kv/txn_interceptor_metrics.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is the `txn.restarts` histogram even used?
</blockquote></details>

To my knowledge, it's not used by the admin ui in any of the dashboards. However, I have found it useful as a custom graph. I don't know any way to track the frequency of txn restarts with respect to a single txn, as opposed to aggregated across all txns.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30448)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/kv/txn_interceptor_metrics.go, line 99 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-LNFLN9j3yoJiGBI9Vqw:-LNH076QEixM7Ipoqah0:blh7tdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5faebc1d3bfe49bbbad90df4aa37008151627d1/pkg/kv/txn_interceptor_metrics.go#L99)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

To my knowledge, it's not used by the admin ui in any of the dashboards. However, I have found it useful as a custom graph. I don't know any way to track the frequency of txn restarts with respect to a single txn, as opposed to aggregated across all txns.
</blockquote></details>

I've opened #30644 and referenced it in the code.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30448#-:-LNH0Hfo26mcwNNJqhtP:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by nvb — APPROVED** [review]

**Pull request merged**
