### PR TITLE
sql: implement ConstructRender and ConstructSimpleProject in the new factory

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql,ccl: clean up adding "no input" stage of processors**

This commit adds a helper method `PhysicalPlan.AddNoInputStage` that
plans a new stage of the processors that don't have any input streams
with the specified cores on the corresponding nodes, and then it
reuses it in several places simplifying the code a bit.

Release note: None

**sql: move distribution info into `physicalplan.PhysicalPlan`**

This commit moves the information about plan distribution from
`planMaybePhysical` into `physicalplan.PhysicalPlan`. This allows us to
simplify the logic that updates the distribution info - the update can
be done whenever a new stage of the processors is added.

However, there is a complication that `NewStage` method needs to know
whether the new stage has at least one remote processor - simply
checking whether there is more than one node participating is not
sufficient because when we have a single processor planned on a remote
node, such stage is still considered "distributed". This commit adds the
plumbing to be able to figure this out.

Release note: None

**sql,server: minor cleanup around the gateway node ID in DistSQLPlanner**

This commit makes a tiny step towards removing a dependency of
`DistSQLPlanner` on node descriptor - by switching to using
`roachpb.NodeID` instead.

It also changes `distSQLSpecExecFactory` to use
`DistSQLPlanner.gatewayNodeID` field so that tests on `3node-tenant`
config are happy.

Release note: None

**sql: implement ConstructRender and ConstructSimpleProject in the new factory**

This commit adds implementations of `ConstructRender` and
`ConstructSimpleProject` methods to the new factory. One thing worth
calling out is the way the new factory handles updating the merge
ordering when `reqOrdering` is `nil` (which is the case when we have a
top-level projection) - we're merging all streams of the plan according
to the old merge ordering on the gateway node. This comes from the fact
that we cannot simply reset the merge ordering that is currently set on
the plan.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
cc @rytaft

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rytaft, and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MA6idzh12Wql2b5Dn61:-MA6idzh12Wql2b5Dn62:b-8ipgve) ([raw file](https://github.com/cockroachdb/cockroach/blob/244f9afc6c5c4a6eb4558fb6a86d166f3a41865d/pkg/sql/distsql_spec_exec_factory.go#L267)):*
> ```Go
> 		return nil, err
> 	}
> 	plan.updateDistribution()
> ```

This feels brittle because it seems easy to forget to call this. Can we design this in a way that this doesn't need to be called? Maybe by either pushing the `distribution` field to the physical plan struct or having some way to lazily evaluate distribution?
___
*[pkg/sql/plan.go, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MA6kW9s0UuPWWpFLWbL:-MA6kW9t0H3nxQx19UhY:b9e1m8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/244f9afc6c5c4a6eb4558fb6a86d166f3a41865d/pkg/sql/plan.go#L339)):*
> ```Go
> // updateDistribution updates the distribution of the plan with the
> // distribution of the last stage. It assumes that p.physPlan is non-nil.
> func (p planMaybePhysical) updateDistribution() {
> ```

I'm pretty sure this should be a pointer receiver otherwise the distribution field won't be updated. Can you please add a test that would catch this?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @dt, and @rytaft)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MA6idzh12Wql2b5Dn61:-MA8gGeM52J55qjD7kGy:b-rkehme) ([raw file](https://github.com/cockroachdb/cockroach/blob/244f9afc6c5c4a6eb4558fb6a86d166f3a41865d/pkg/sql/distsql_spec_exec_factory.go#L267)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This feels brittle because it seems easy to forget to call this. Can we design this in a way that this doesn't need to be called? Maybe by either pushing the `distribution` field to the physical plan struct or having some way to lazily evaluate distribution?
</blockquote></details>

Good idea. I decided to move the field into the physical plan, so I added two preliminary commits to this PR.
___
*[pkg/sql/plan.go, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MA6kW9s0UuPWWpFLWbL:-MA7GOAD1q56m33fqdEf:bdc0gz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/244f9afc6c5c4a6eb4558fb6a86d166f3a41865d/pkg/sql/plan.go#L339)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm pretty sure this should be a pointer receiver otherwise the distribution field won't be updated. Can you please add a test that would catch this?
</blockquote></details>

Indeed, nice catch. I refactored the code but added a test that would have caught this issue.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, and @rytaft)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 281 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MAHc3CW7ooYUJvqqu81:-MAHc3CXCpYJ1Wi91Qh8:b-cgzguc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c540b91964b6066ce72fdd980adc16471698406/pkg/sql/distsql_spec_exec_factory.go#L281)):*
> ```Go
> 	physPlan.ResultColumns = getResultColumnsForSimpleProject(cols, colNames, physPlan.ResultTypes, physPlan.ResultColumns)
> 	physPlan.PlanToStreamColMap = identityMap(physPlan.PlanToStreamColMap, len(cols))
> 	// TODO(yuzefovich): I think it is wrong that a "simple projection" can
> ```

I ran into this problem in one of the logic tests, and I'm not sure how I should solve it. As the TODO describes, there is a difference in how `reqOrdering` property is stored in the old and the new factories, and without this `if` check the new factory can produce a physical plan with incorrect results.

For example, consider the following scenario: we have a 3 node cluster with a table defined `t` with schema `(a INT PRIMARY KEY, b INT)`. The leaseholders for the ranges of `t` live on all 3 nodes, and we want to run the following query `SELECT b FROM t ORDER BY a`. The builder will construct a scan with `reqOrdering = {a}`, and we create table readers on all 3 nodes, with `PhysicalPlan.MergeOrdering = {a}`. Then the builder calls `applyPresentation` with `nil` ordering; however, we cannot naively unset `physPlan.MergeOrdering` because we haven't merged the streams. At the same time, I'm not sure that we want to merge the streams yet. There are also other callers of `ConstructSimpleProject` with some passing-in `nil` ordering and others non-`nil`.

I feel like a "simple projection" should not care about `reqOrdering` since it simply rearranges the columns (it might need to update already present `reqOrdering` according to the rearrangement though). Thoughts? Is there something I'm missing? @rytaft @raduberinde

**Review by yuzefovich — COMMENTED** [review]
First commit is in a separate PR, please ignore it here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-:-MAI6TvA5pAopluGuTBh:bns49r0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, and @rytaft)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 281 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MAHc3CW7ooYUJvqqu81:-MAI1UH7CQ-WI4r05ogn:b6600v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c540b91964b6066ce72fdd980adc16471698406/pkg/sql/distsql_spec_exec_factory.go#L281)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I ran into this problem in one of the logic tests, and I'm not sure how I should solve it. As the TODO describes, there is a difference in how `reqOrdering` property is stored in the old and the new factories, and without this `if` check the new factory can produce a physical plan with incorrect results.

For example, consider the following scenario: we have a 3 node cluster with a table defined `t` with schema `(a INT PRIMARY KEY, b INT)`. The leaseholders for the ranges of `t` live on all 3 nodes, and we want to run the following query `SELECT b FROM t ORDER BY a`. The builder will construct a scan with `reqOrdering = {a}`, and we create table readers on all 3 nodes, with `PhysicalPlan.MergeOrdering = {a}`. Then the builder calls `applyPresentation` with `nil` ordering; however, we cannot naively unset `physPlan.MergeOrdering` because we haven't merged the streams. At the same time, I'm not sure that we want to merge the streams yet. There are also other callers of `ConstructSimpleProject` with some passing-in `nil` ordering and others non-`nil`.

I feel like a "simple projection" should not care about `reqOrdering` since it simply rearranges the columns (it might need to update already present `reqOrdering` according to the rearrangement though). Thoughts? Is there something I'm missing? @rytaft @raduberinde 

</blockquote></details>

I opened up another PR to remove `reqOrdering` argument.

Here is the TODO I had in the code:
```
	// TODO(yuzefovich): I think it is wrong that a "simple projection" can
	// change the required ordering. This condition is put in place temporarily
	// so that applyPresentation call didn't unset the merge ordering currently
	// set on the plan. In the old factory every planNode has their own
	// reqOrdering field, so it was ok to set a nil ordering in
	// ConstructSimpleProject because it would not modify the ordering on
	// already present planNodes. However, in this new factory the merge
	// ordering is the property of the whole physical plan built so far, and we
	// cannot simply unset it without possibly merging the streams.
```

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 40 of 40 files at r5, 7 of 7 files at r6, 21 of 21 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, @rytaft, and @yuzefovich)

___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 182 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MARRny89qGwkskv6sbD:-MARRny89qGwkskv6sbE:buolbud) ([raw file](https://github.com/cockroachdb/cockroach/blob/950b19fd2ad311a5a3b693fd615c8476471e7cb9/pkg/ccl/changefeedccl/changefeed_dist.go#L182)):*
> ```Go
> 	)
> 
> 	p.ResultTypes = changefeedResultTypes
> ```

Is this `ResultTypes` omission a problem?
___
*[pkg/sql/physicalplan/physical_plan.go, line 165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MARTdS72KQ9P6SpdTTK:-MARTdS72KQ9P6SpdTTL:b9t4fhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9d8e7a2176046f2941d42bee174590c927d909/pkg/sql/physicalplan/physical_plan.go#L165)):*
> ```Go
> // mapping so that a particular processor core is planned on the appropriate
> // node.
> func (p *PhysicalPlan) AddNoInputStage(
> ```

I'm confused by the inclusion of this commit in this PR. Should it be in its own PR?
___
*[pkg/sql/physicalplan/physical_plan.go, line 167 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MART6JzD3EYz4QiDIp6:-MART6JzD3EYz4QiDIp7:bxkg28k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9d8e7a2176046f2941d42bee174590c927d909/pkg/sql/physicalplan/physical_plan.go#L167)):*
> ```Go
> func (p *PhysicalPlan) AddNoInputStage(
> 	nodes []roachpb.NodeID,
> 	cores []execinfrapb.ProcessorCoreUnion,
> ```

If cores and nodes is a 1:1 mapping it would probably be better to enforce this using a slice of
```
struct{
    id NodeID
    core ProcessorCoreUnion
}
```
___
*[pkg/sql/physicalplan/physical_plan.go, line 247 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MARmthtDjAh3ZIjfGbW:-MARmthuBg-odL-uu-f8:b-g5irp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dc3b06a2ee75c9592f9736b438bd859da466c9d/pkg/sql/physicalplan/physical_plan.go#L247)):*
> ```Go
> 	outputTypes []*types.T,
> 	newOrdering execinfrapb.Ordering,
> 	gatewayNodeID roachpb.NodeID,
> ```

It feels like this should be part of the physical plan (i.e. a field) rather than an argument passed in to each method.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, and @rytaft)

___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 182 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MARRny89qGwkskv6sbD:-MARoJl5ChfK3iMhDZXS:b94gay5) ([raw file](https://github.com/cockroachdb/cockroach/blob/950b19fd2ad311a5a3b693fd615c8476471e7cb9/pkg/ccl/changefeedccl/changefeed_dist.go#L182)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is this `ResultTypes` omission a problem?
</blockquote></details>

This line was redundant - `ResultTypes` are set by `AddSingleGroupStage`.
___
*[pkg/sql/distsql_spec_exec_factory.go, line 253 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MASTmnd4Jg_CP_2-emt:-MASTmnd4Jg_CP_2-emu:bz1e13k) ([raw file](https://github.com/cockroachdb/cockroach/blob/abc49d3c74e3610df55ebb06cb4300c2c70c5353/pkg/sql/distsql_spec_exec_factory.go#L253)):*
> ```Go
> 	oldMergeOrdering := physPlan.MergeOrdering
> 	newMergeOrdering := e.dsp.convertOrdering(ReqOrdering(reqOrdering), physPlan.PlanToStreamColMap)
> 	if len(oldMergeOrdering.Columns) > 0 && !oldMergeOrdering.Equal(newMergeOrdering) {
> ```

@raduberinde you mentioned that checking whether the new ordering is `nil` should be sufficient to decide whether we need to merge the streams. Why is it so? Is it possible that the old and the new orderings are different but we don't need to merge streams?
___
*[pkg/sql/physicalplan/physical_plan.go, line 165 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MARTdS72KQ9P6SpdTTK:-MARoScgCY80BzKhs0Jf:b-ujd8e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9d8e7a2176046f2941d42bee174590c927d909/pkg/sql/physicalplan/physical_plan.go#L165)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm confused by the inclusion of this commit in this PR. Should it be in its own PR?
</blockquote></details>

The only reason that prompted me to add this commit is to reduce the number of `NewStage` calls, so this commit paves the way for the following commit. I think it is ok to keep it in the same PR but can extract it in a separate one if you think it's worth it.
___
*[pkg/sql/physicalplan/physical_plan.go, line 167 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MART6JzD3EYz4QiDIp6:-MARsifg76euqQyNJtBI:bjai75v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9d8e7a2176046f2941d42bee174590c927d909/pkg/sql/physicalplan/physical_plan.go#L167)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

If cores and nodes is a 1:1 mapping it would probably be better to enforce this using a slice of
```
struct{
    id NodeID
    core ProcessorCoreUnion
}
```
</blockquote></details>

I also thought about this initially but decided not to add such struct because in some call sites we already have `nodes` slice populated, so I was thinking about not introducing extra allocations. But those somewhat redundant allocations aren't that important after all, so I added a helper struct.
___
*[pkg/sql/physicalplan/physical_plan.go, line 247 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MARmthtDjAh3ZIjfGbW:-MAS1q-T4lQux-diakkD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dc3b06a2ee75c9592f9736b438bd859da466c9d/pkg/sql/physicalplan/physical_plan.go#L247)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It feels like this should be part of the physical plan (i.e. a field) rather than an argument passed in to each method.
</blockquote></details>

Done.

**Review by pbardea — APPROVED** [review]
Bulk IO changes LGTM.

> Reviewed 2 of 40 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-:-MASdLuV1e1m3dFkqBxj:bqyy4ks)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, @rytaft, and @yuzefovich)

___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 131 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MASd5603pBRByYV2Yr4:-MASd5603pBRByYV2Yr5:boy353d) ([raw file](https://github.com/cockroachdb/cockroach/blob/be3502bb2679d15cc14cdfa9676e4bf4c5bdc72e/pkg/ccl/changefeedccl/changefeed_dist.go#L131)):*
> ```Go
> 
> 	corePlacement := make([]physicalplan.ProcessorCorePlacement, len(spanPartitions))
> 	for i, sp := range spanPartitions {
> ```

Could we either rename this `i`, or the `i` in the inner loop to avoid shadowing and general confusion?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, @rytaft, and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 253 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MASTmnd4Jg_CP_2-emt:-MASduLV54DhAwJQ7Vi0:boaa91d) ([raw file](https://github.com/cockroachdb/cockroach/blob/abc49d3c74e3610df55ebb06cb4300c2c70c5353/pkg/sql/distsql_spec_exec_factory.go#L253)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

@raduberinde you mentioned that checking whether the new ordering is `nil` should be sufficient to decide whether we need to merge the streams. Why is it so? Is it possible that the old and the new orderings are different but we don't need to merge streams?
</blockquote></details>

Because we only need to merge the streams when we are projecting away an ordering column and that only happens for the "top" ConstructSimpleProject. Checking for `nil` helps detect that special case. I would actually consider moving that check up into `ConstructSimpleProject` and just calling `EnsureSingleStreamOnGateway()` there directly. There is no reason why other code paths should check for this case.

It is possible for the old and the new ordering to "look" different but they would have the same effect in practice (like the example I mentioned before where we have `a,b,c` ordered by `a+` and we project away `a` but the optimizer knows that `a=c` so the new ordering would have `c+`). The factory should trust the optimizer that the given ordering is how the streams should be ordered if they need to merge into the next operator.

**Review by yuzefovich — COMMENTED** [review]
@asubiotto I needed to add another commit to make `3node-tenant` config happy on `experimental_distsql_planning` test. I described the problem in the commit message, but I'm not sure whether that commit makes sense and such change is desirable. I feel like we should skip 3node-tenant config because of missing distsql support.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-:-MAT6euG4m-CYbWUUaMu:b-mss77v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, @RaduBerinde, and @rytaft)

___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 131 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MASd5603pBRByYV2Yr4:-MASfh01-fn6wLITR0fM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be3502bb2679d15cc14cdfa9676e4bf4c5bdc72e/pkg/ccl/changefeedccl/changefeed_dist.go#L131)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Could we either rename this `i`, or the `i` in the inner loop to avoid shadowing and general confusion?
</blockquote></details>

Done.
___
*[pkg/sql/distsql_spec_exec_factory.go, line 253 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MASTmnd4Jg_CP_2-emt:-MASjPYi0GAiw3eK4QRv:bkglji8) ([raw file](https://github.com/cockroachdb/cockroach/blob/abc49d3c74e3610df55ebb06cb4300c2c70c5353/pkg/sql/distsql_spec_exec_factory.go#L253)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Because we only need to merge the streams when we are projecting away an ordering column and that only happens for the "top" ConstructSimpleProject. Checking for `nil` helps detect that special case. I would actually consider moving that check up into `ConstructSimpleProject` and just calling `EnsureSingleStreamOnGateway()` there directly. There is no reason why other code paths should check for this case.

It is possible for the old and the new ordering to "look" different but they would have the same effect in practice (like the example I mentioned before where we have `a,b,c` ordered by `a+` and we project away `a` but the optimizer knows that `a=c` so the new ordering would have `c+`). The factory should trust the optimizer that the given ordering is how the streams should be ordered if they need to merge into the next operator.
</blockquote></details>

Thanks, makes sense, implemented your suggestion.

**Comment by yuzefovich** [comment]
> I described the problem in the commit message, but I'm not sure whether that commit makes sense and such change is desirable. I feel like we should skip 3node-tenant config because of missing distsql support.

Changed the new factory to use `DistSQLPlanner.gatewayNodeID` so that it is aligned with the rest of the physical planning.

**Review by asubiotto — COMMENTED** [review]
We shouldn't be adding new skips of the `3node-tenant` configuration because that would imply introducing new uses of components that aren't available to a tenant and must be removed later on. I think what you did is fine (use a SQLInstanceID cast to a NodeID for now) but I'm not sure I follow exactly why we needed to swap out the node descriptor for a node ID since you can directly access the node ID through it.

> Reviewed 1 of 40 files at r9, 23 of 23 files at r12, 19 of 19 files at r13, 16 of 16 files at r14, 7 of 7 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-:-MAVKb4B1PQj2nrcpvN6:b-69p4he)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 74 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MAVL0HB1G6ZpwCrV4r9:-MAVL0HB1G6ZpwCrV4rA:bcz4a15) ([raw file](https://github.com/cockroachdb/cockroach/blob/404afe6c3804a366c127de3f3bd4edc0a2c6408c/pkg/sql/distsql_physical_planner.go#L74)):*
> ```Go
> 	st *cluster.Settings
> 	// The node descriptor for the gateway node that initiated this query.
> 	nodeDesc     roachpb.NodeDescriptor
> ```

I'm confused as to why this change is needed. Couldn't you just access the nodeID in places that will use this `gatewayNodeID` directly?

**Review by yuzefovich — COMMENTED** [review]
> We shouldn't be adding new skips of the 3node-tenant configuration because that would imply introducing new uses of components that aren't available to a tenant and must be removed later on.

Ok, it is not needed.

> use a SQLInstanceID cast to a NodeID for now

The thing that makes the tests happy is actually the opposite - a switch from SQLInstanceID to NodeID in `newDistSQLSpecExecFactory`. The problem with 3node-tenant config was that when the new factory is used, the physical planning process would fool itself - the factory would think that "gatewayNodeID" is the tenant's ID whereas the physical planner would think it is the "deprecated nodeID" which would cause confusion.

> I'm not sure I follow exactly why we needed to swap out the node descriptor for a node ID since you can directly access the node ID through it

It is not needed, but I took a quick stab at removing the gateway nodeID from DistSQLPlanner (which wasn't it easy) and decided to keep the switch since it does take us slightly further (I think) in supporting multitenancy by the distsql. If you think it's not worth, I can remove that commit, but we do need to keep the change in `newDistSQLSpecExecFactory`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-:-MAWMhn38gqKSCDnAr-U:b-avje3b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, @RaduBerinde, and @rytaft)

___
*[pkg/sql/distsql_physical_planner.go, line 74 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-MAVL0HB1G6ZpwCrV4r9:-MAWNvksE_-AOOE5dtbj:b-g89jbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/404afe6c3804a366c127de3f3bd4edc0a2c6408c/pkg/sql/distsql_physical_planner.go#L74)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm confused as to why this change is needed. Couldn't you just access the nodeID in places that will use this `gatewayNodeID` directly?
</blockquote></details>

It is not needed, described above.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-:-MAWe26Q-XExLWX94wXf:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, @RaduBerinde, and @rytaft)

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50374#-:-MAWeyoV1iv7YM20MiY2:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, @RaduBerinde, and @rytaft)

**Pull request merged**
