### PR TITLE
sql: fix a couple of memory leaks around memory monitors

### PR DESCRIPTION
**Pull request by yuzefovich**
See individual commits for details.

Epic: None

Release note (bug fix): A slow memory leak that can accumulate when opening many new connections has been fixed. The bug is present in 22.2.9+ and 23.1+ versions.

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119799)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-Nrt4kcGA5ERVH85uR1I):*
Why is it ok to remove these closures? Are they getting stopped elsewhere, or is it ok to not stop monitors as long as the connection is closing?
___
*[`pkg/sql/explain_vec.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-Nrt78rs1gRG69A-7d16:-Nrt5vTdBWl9y1unEtkM:b-j85gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ca5563f9a3b452d38c462bb3e1713811eefcee/pkg/sql/explain_vec.go#L106)):*
> ```Go
> 	// the components that use them). This also allows us to not close this
> 	// monitor.
> 	monitor.Start(ctx, nil /* pool */, mon.NewStandaloneBudget(math.MaxInt64))
> ```

I'm confused by this - won't the child monitors be linked to the one started here, rather than the planner monitor? And so, shouldn't the reference to those child monitors be released after this monitor is closed? Maybe we could also have `doStop` reset all the linked list pointers to help with GC.
___
*[`pkg/sql/backfill/mvcc_index_merger.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-Nrt5UzOBeYQYt-YvTX4:-Nrt5UzOBeYQYt-YvTX5:b-drvad9) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ca5563f9a3b452d38c462bb3e1713811eefcee/pkg/sql/backfill/mvcc_index_merger.go#L106)):*
> ```Go
> // Run runs the processor.
> func (ibm *IndexBackfillMerger) Run(ctx context.Context, output execinfra.RowReceiver) {
> 	mergerMon := execinfra.NewMonitor(ctx, ibm.flowCtx.Cfg.BackfillerMonitor, "index-backfiller-merger-mon")
> ```

[nit] Can you add a comment to explain that this method waits until all workers have finished, so the monitor won't be used after it returns?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119799)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`-- commits` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-Nrt4kcGA5ERVH85uR1I):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Why is it ok to remove these closures? Are they getting stopped elsewhere, or is it ok to not stop monitors as long as the connection is closing?
</blockquote></details>

I define "long-living monitors" as such that are used throughout the lifetime of the server, i.e. they could only be stopped on the node shutdown, at which point it actually doesn't matter whether they are stopped or not. I removed this minor improvement since it's orthogonal to the fix.
___
*[`pkg/sql/explain_vec.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-Nrt78rs1gRG69A-7d16:-NrukNOL3lIHDeI6D0JE:b-3va3we) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ca5563f9a3b452d38c462bb3e1713811eefcee/pkg/sql/explain_vec.go#L106)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I'm confused by this - won't the child monitors be linked to the one started here, rather than the planner monitor? And so, shouldn't the reference to those child monitors be released after this monitor is closed? Maybe we could also have `doStop` reset all the linked list pointers to help with GC.
</blockquote></details>

Yes, all those monitors will be linked to the one we just created, but importantly this "explain" tree of monitors won't be linked to the main tree of monitors rooted in the RootSQLMonitor. As a result, whenever the flow ctx is no longer used, the whole explain tree of monitors can be garbage collected. Extended the comment a bit. (Note that _most_ monitors will still be closed in this subtree in the cleanup function of `convertToVecTree`.)
___
*[`pkg/sql/backfill/mvcc_index_merger.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-Nrt5UzOBeYQYt-YvTX4:-NrulXtm2COtEKO1lnz9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ca5563f9a3b452d38c462bb3e1713811eefcee/pkg/sql/backfill/mvcc_index_merger.go#L106)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Can you add a comment to explain that this method waits until all workers have finished, so the monitor won't be used after it returns?
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119799)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`-- commits` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-Nrup6Y052oBgsNEadE3):*
BTW I'm working on this in #119794.

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119799)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/explain_vec.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-Nrt78rs1gRG69A-7d16:-NrvXQyI4aMbKPRcokqX:b5dntwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ca5563f9a3b452d38c462bb3e1713811eefcee/pkg/sql/explain_vec.go#L106)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yes, all those monitors will be linked to the one we just created, but importantly this "explain" tree of monitors won't be linked to the main tree of monitors rooted in the RootSQLMonitor. As a result, whenever the flow ctx is no longer used, the whole explain tree of monitors can be garbage collected. Extended the comment a bit. (Note that _most_ monitors will still be closed in this subtree in the cleanup function of `convertToVecTree`.)
</blockquote></details>

What I'm not understanding is why it's a problem for the explain monitors to be linked to `RootSQLMonitor`, when stoping this monitor should be enough to sever that link. We can guarantee that this monitor at least is closed on time, right?
If the concern is that some reference to this monitor is being kept alive or something, why not just also reset the `head` pointer so that the children can be GC'd?

It just seems better to leave these allocations visible from the root monitor if we have another option.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119799)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/explain_vec.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-Nrt78rs1gRG69A-7d16:-NrvcPRvCjpWPXLkVjez:b-c0a9tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ca5563f9a3b452d38c462bb3e1713811eefcee/pkg/sql/explain_vec.go#L106)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

What I'm not understanding is why it's a problem for the explain monitors to be linked to `RootSQLMonitor`, when stoping this monitor should be enough to sever that link. We can guarantee that this monitor at least is closed on time, right?
If the concern is that some reference to this monitor is being kept alive or something, why not just also reset the `head` pointer so that the children can be GC'd?

It just seems better to leave these allocations visible from the root monitor if we have another option.
</blockquote></details>

Ok, I removed the part of the EXPLAIN (VEC) fix from the commit that I want to backport.

~Let me provide a bit more background on the problem. We can have a memory leak if a monitor is a descendant of the root SQL monitor, and neither the monitor itself nor at east two of its "consecutive parents" (up to the root monitor) are stopped. In case of the memory leak that the customer run into (with txn fingerprint ID cache), we had roughly the following chain: `root` -> `sql` -> `session root` -> `txn fingerprint ID cache`. (We need two "consecutive parents" (i.e. parent and grandparent) because we store links between monitors in two directions.) Even though we stopped the `session root` monitor when closing the connection, `sql` monitor still stored the link to `session root`, and `session root` kept the link to `txn fingerprint ID cache` monitor, which kept two monitors alive.~ This is mostly incorrect.

In this EXPLAIN (VEC) path we guarantee that we close the monitor in this scope, but currently we don't stop all of its descendants (mostly row-based components) - those monitors are created when creating the flow but are not stopped on flow cleanup. One concrete example is `fetcher-mem` monitor. So in theory, we can have the following chain: `root` -> `sql` -> `session root` -> `flow` -> `explain` -> `join-reader` -> `fetcher-mem`. The last two will not be stopped, but `flow` and `explain` will, so I think it is safe to revert the change to EXPLAIN (VEC). In other PR on master I'll think more about this.

**Comment by yuzefovich** [comment]
Actually, hold off on reviewing this. I want to double check my understanding from my last comment first.

**Comment by yuzefovich** [comment]
Hm, I'm quite confused right now - either I'm missing something (perhaps obvious), or there is a bug in how Go runtime detects that a particular object is no longer reachable (i.e. garbage) in presence of cyclical references. (Typing this out made me think that maybe the latter is not that unlikely.)

----

We already do delete the monitor from its parent list of children on `Stop`, so in theory stopping the `session root` monitor should remove it from its parent `sql`'s list of children, and then we should lose the only reference to `session root`'s subtree, which includes `txn fingerprintID cache`. (I did reread the logic for maintaining the list of children and didn't find any issues.)

When looking at the `inuse_objects` heap profile from the customer ticket that prompted this investigation, there are three objects that are being accumulated with each new connection:
- `session root` monitor
- `txn fingerprintID cache` monitor
- `tenantReserved` memory account that is passed as "reserved" into `session root` in `Start`.

`conn_executor.go`:
```
         .    1720687    983:	sessionRootMon := mon.NewMonitor(
...
         .    1659819   1053:		txnFingerprintIDCache:     NewTxnFingerprintIDCache(s.cfg.Settings, sessionRootMon),
```
`pgwire/server.go`
```
   1867861    1867861    802:	tenantReserved, err := s.tenantSpecificConnMonitor.TransferAccount(ctx, &preServeStatus.Reserved)
```

According to the goroutine dump from the node that this heap profile belongs to (and according to metrics as well as open sessions), there were about 500 open connections, so we'd expect that only about 500 of the objects mentioned above would be live. (The customer does open like a million of new connections daily.)

Because we don't see `connExecutor` objects themselves being live and don't see extra goroutines, I think connections are closed correctly, so the link keeping these 3 types of objects live must be the memory accounting system.

We have the following references to these objects (let's ignore `txn fingerprint ID cache` since it's only connected to `session root` and is actually not used at all (!!!)):
- `sql` -> `session root` via `mu.head` list of children
- `sql` -> `conn` (`tenantSpecificConnMonitor`) via `mu.head` list of children
- `session root` -> `sql` via `mu.curBudget.mon`
- `conn` -> `sql` via `mu.curBudget.mon`
- `session root` -> `conn` (`tenantSpecificConnMonitor`) via `reserved` which is `tenantReserved`.

When `session root` is being `Stop`ped, it removes itself from `sql` list of children, which is the only reference to `session root` from long-living monitors, so the whole monitor tree, rooted in `session root`, should be garbage collected.

Instead, it appears as if somehow the link from `session root` to `conn` via `tenantReserved` keeps `session root` live (`conn` is singleton that is never stopped). The complication here is that both `session root` and `conn` are children of `sql`, so they are stored in the doubly-linked list of children where each child has reference to "previous" and "next" siblings. Perhaps this complication is what's tripping up garbage collector.

----

Curious whether y'all see issues with my writeup or what I'm missing.

**Comment by yuzefovich** [comment]
Hm, I tried to reproduce the memory leak in a unit test [here](https://github.com/yuzefovich/cockroach/commit/e6553a392374e3414e36d8f25a948bd8a5603bef) but that was unsuccessful. Perhaps there is some other condition that is necessary for a repro - simply opening up new connections and simulating usage of `tenantReserved` is insufficient.

**Review by yuzefovich — COMMENTED** [review]
I refactored this PR a bit. In particular, the first commit now removes the txn fingerprint ID cache monitor altogether (as well as fixes the accounting around it), and the second commit is hypothetical fix that should resolve the leak for good. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-:-NsGrFNL0nYEZbpyzSn4:b-rf90)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

**Comment by yuzefovich** [comment]
Updated the second commit with Drew's suggestion to lose the reference to the head of list of children as well as to break the references between unstopped children.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for working through this one!

> Reviewed 4 of 8 files at r4, 5 of 5 files at r7, 1 of 1 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-:-Nsiifqu93DdylXZWNxt:b-kfvxrg)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by yuzefovich — COMMENTED** [review]
Thanks for the careful review and the discussion!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119799#-:-Nsikvlu8_RWC-HchSqk:b-69isnu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @michae2)

**Pull request merged**
