### PR TITLE
sql: only hook up database cache to gossip if system tenant

### PR DESCRIPTION
**Pull request by ajwerner**
We won't have access to gossip on secondary tenants. This database cache should
be gone in the next week but this should unblock progress.

Touches #47150

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51836#-:-MCwIh7b0WSQNliq_i9C:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
bors r=nvanbenschoten

**Comment by ajwerner** [comment]
cli flake of some sort?

bors r+

**Comment by ajwerner** [comment]
Maybe?

bors r+

**Pull request merged**
