### PR TITLE
schemachanger: eager statement phase

### PR DESCRIPTION
**Pull request by postamar**
This commit reworks how the declarative schema changer performs DROPs by
removing support for synthetic descriptors in the statement transaction.
In-transaction operations are now executed eagerly in the statement
phase instead of being deferred to the pre-commit phase.

The most significant change this entails is to the rules definitions,
since we now no longer have the TXN_DROPPED status. I have taken this
opportunity to rewrite them in a way that involves more element set
definitions, whose properties are enforced by init-time assertions.

The operation implementations in scexec have been simplified somewhat,
not having to concern ourselves with synthetic descriptors any more.
The opgen definitions are also simplified now that they are no longer
peppered with pre-commit phase constraints. Instead, phase constraints
are implied by the number of transitions: more than 1 and those other
than the first are implied to be restricted to post-commit. This makes
all phase constraints implicit.

This commit improves the graph validation logic to detect all cycles,
not just dep-edge cycles, and renders any detected cycle in the detail
of the resulting error.

This commit makes some changes in the test dependencies which mock the
catalog API, as this now has to support both the in-txn and committed
state of the catalog. In the process this commit adds better support for
descriptor modification times.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
This could certainly be broken up into multiple commits, but I don't have time to break it down before going away, so I'm putting this here in the meantime.

**Review by ajwerner — APPROVED** [review]
:lgtm:

This was a deeply pleasant change. There's a rttanalysis to rewrite. Just little things from me. Any rough edges introduced seem smoother than the ones they replace. Thank you for doing this!

> Reviewed 89 of 90 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-:-N4EQxgED_6sr_j18L6O:b-nbuqkx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[`pkg/sql/schemachanger/scdeps/sctestdeps/test_state.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4EM0wPCAEtfxS56Gkj:-N4EM0wPCAEtfxS56Gkk:b-u3sqap) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scdeps/sctestdeps/test_state.go#L41)):*
> ```Go
> // purpose of facilitating end-to-end testing of the declarative schema changer.
> type TestState struct {
> 	committed, uncommitted  nstree.MutableCatalog
> ```

can you comment about what this is? what does it mean for something to be `committed` or `uncomitted`?
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/graph.go` line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4EQiaQ8kt8tWM6kNY-:-N4EQiaQ8kt8tWM6kNY0:bbu62wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scplan/internal/scgraph/graph.go#L359)):*
> ```Go
> 	sb.WriteString("cycle:\n")
> 	for _, e := range collectCycle(edge) {
> 		sb.WriteString(screl.NodeString(e.From()))
> ```

I feel like this should end up printing the other side of the edge, it currently only prints the From if I read it correctly. The test might fool you becuase the depEdge `rule` field has a to and from. 
___
*[`pkg/ccl/schemachangerccl/testdata/end_to_end/drop_multiregion` line 1996 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4EP2gV--otd5fz2S6V:-N4EP2gV--otd5fz2S6W:b9gp6mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/ccl/schemachangerccl/testdata/end_to_end/drop_multiregion#L1996)):*
> ```
> # end PreCommitPhase
> notified job registry to adopt jobs: [1]
> commit transaction #1
> ```

the inversion here seems bad. I don' think we can send the notification until after the commit 



_Code quote:_
```
notified job registry to adopt jobs: [1]
commit transaction #1
```
___
*[`pkg/sql/schemachanger/scplan/internal/rules/testdata/deprules` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4EPHs86RwndpcPq3lp:-N4EPHs86RwndpcPq3lq:b-yhprhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbf9b70bd2b9adfa77e0f3aebca4ae51a2d9a50d/pkg/sql/schemachanger/scplan/internal/rules/testdata/deprules#L1)):*
> ```
> rules
> ```

wanna add this part back?



_Code quote:_
```
rules
----
joinTarget(element, target):
```

**Review by chengxiong-ruan — COMMENTED** [review]
Really like this change :thumbsup: :thumbsup: :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-:-N4FHpPB0o8QQ5G39cWZ:bqyxrjl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[`pkg/sql/schemachanger/scdeps/sctestdeps/test_state.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4F9vOWAQ8Tnr2U8Nsu:-N4F9vOWAQ8Tnr2U8Nsv:bro2eu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scdeps/sctestdeps/test_state.go#L122)):*
> ```Go
> 
> func (s *TestState) mvccTimestamp() hlc.Timestamp {
> 	return hlc.Timestamp{WallTime: defaultOverriddenCreatedAt.UnixNano() + int64(s.txnCounter)}
> ```

simple and smart :)
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/column.go` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4FAkeV-hzSZtlRpuUK:-N4FAkeV-hzSZtlRpuUL:b2kg8ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scexec/scmutationexec/column.go#L170)):*
> ```Go
> 	col.Type = types.Any
> 	if col.IsComputed() {
> 		null := tree.Serialize(tree.DNull)
> ```

May I ask why this is necessary?
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/target.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4FBq0yDvArL2ske1TC:-N4FBq0yDvArL2ske1TD:b1tpqsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scplan/internal/opgen/target.go#L78)):*
> ```Go
> 			t.from = tbs.from
> 			t.to = s.to
> 			if err := tbs.withTransition(s, i == 0); err != nil {
> ```

nit, even it seems obvious that `i == 0` means `is first`, but adding `/* isFirst */` note is appreciated.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_drop.go` line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4FGbutDl0Kd8aWdzrR:-N4FGbutDl0Kd8aWdzrS:breqv7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scplan/internal/rules/dep_drop.go#L263)):*
> ```Go
> 			return rel.Clauses{
> 				elementTypes(from, isDescriptor),
> 				elementTypes(to, func(e scpb.Element) bool {
> ```

this is awesome
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/graph.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4F1q0_7GpwLxfPaifv:-N4F1q0a82dtkXC9ksTq:bs0wy05) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scplan/internal/scgraph/graph.go#L319)):*
> ```Go
> 	pred := make(map[*screl.Node]Edge, order)
> 	var visit func(n *screl.Node, in Edge)
> 	visit = func(n *screl.Node, in Edge) {
> ```

small improvement, feel free to ignore... but feels like `visit` should return an error so that we can check `if err := visit(n, e); err != nil` and return early, otherwise it won't return until visiting all remain edges, though it's cheap since each visit would return immediately without going further.
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/graph.go` line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4EQiaQ8kt8tWM6kNY-:-N4F75wX9_XtGEIU4Jkx:b-5lf6uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scplan/internal/scgraph/graph.go#L359)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like this should end up printing the other side of the edge, it currently only prints the From if I read it correctly. The test might fool you becuase the depEdge `rule` field has a to and from. 
</blockquote></details>

It seems lgtm since it begins from the `edge` with `target` as `from`, and ends at `edge` with `target` as `to`... maybe I misunderstood what andrew said heh.

**Review by postamar — COMMENTED** [review]
Thanks for the kind words. I'll bors as soon as able.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-:-N4SCVRU4U_t5szBmE9h:b-6os18s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[`pkg/sql/schemachanger/scdeps/sctestdeps/test_state.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4EM0wPCAEtfxS56Gkj:-N4SC_8C0ojp3wjxMioR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scdeps/sctestdeps/test_state.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you comment about what this is? what does it mean for something to be `committed` or `uncomitted`?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/column.go` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4FAkeV-hzSZtlRpuUK:-N4SCeDoEVp1X4ouzbRB:b-ddyshj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scexec/scmutationexec/column.go#L170)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

May I ask why this is necessary?
</blockquote></details>

Added a comment to explain, you're right it's not obvious at all.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/target.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4FBq0yDvArL2ske1TC:-N4SCiPY9s4sMmKb6Trl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scplan/internal/opgen/target.go#L78)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

nit, even it seems obvious that `i == 0` means `is first`, but adding `/* isFirst */` note is appreciated.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/graph.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4F1q0_7GpwLxfPaifv:-N4SCkR1EYO-vGq-4iCM:br5r5rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scplan/internal/scgraph/graph.go#L319)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

small improvement, feel free to ignore... but feels like `visit` should return an error so that we can check `if err := visit(n, e); err != nil` and return early, otherwise it won't return until visiting all remain edges, though it's cheap since each visit would return immediately without going further.
</blockquote></details>

You're right. The newest code is also a bit cleaner. I think the previous code was the way it was because we originally did a topological sort here, but that was removed when I rewrote the stage builder.
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/graph.go` line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4EQiaQ8kt8tWM6kNY-:-N4SDDrK5lFHkO9dx44y:b-2n98l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/sql/schemachanger/scplan/internal/scgraph/graph.go#L359)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

It seems lgtm since it begins from the `edge` with `target` as `from`, and ends at `edge` with `target` as `to`... maybe I misunderstood what andrew said heh.
</blockquote></details>

Yes, that's what I was thinking too. There's a couple of examples of this output in the scgraph test assertions and they lgtm.
___
*[`pkg/ccl/schemachangerccl/testdata/end_to_end/drop_multiregion` line 1996 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4EP2gV--otd5fz2S6V:-N4SDWswD_WfEOi3wrHC:b-kn1ilq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f825ee4c6387c0d107342d2f6e1e236259208e0f/pkg/ccl/schemachangerccl/testdata/end_to_end/drop_multiregion#L1996)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

the inversion here seems bad. I don' think we can send the notification until after the commit 
</blockquote></details>

Fixed. It was only inverted in the test deps implementation, thankfully.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/testdata/deprules` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-N4EPHs86RwndpcPq3lp:-N4SDfzz5yeAGJLjXiiY:b-45jxv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbf9b70bd2b9adfa77e0f3aebca4ae51a2d9a50d/pkg/sql/schemachanger/scplan/internal/rules/testdata/deprules#L1)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

wanna add this part back?
</blockquote></details>

Whoops. That's what happens when you `git checkout --theirs` willy-nilly to resolve merge conflicts, I guess.

**Comment by ajwerner** [comment]
Both of those build failures are flakes which seem unrelated:

```
docker: Error response from daemon: Head "https://registry-1.docker.io/v2/library/golang/manifests/stretch": received unexpected HTTP status: 500 Internal Server Error.
```

```
Service 'kdc' failed to build: Head "https://registry-1.docker.io/v2/library/alpine/manifests/3.14": received unexpected HTTP status: 500 Internal Server Error
```

I think this is ready to go. Enjoy your vacation.

bors r+

**Review by ajwerner — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82749#-:-N4T0oEw-938VKp3cqke:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

**Pull request merged**
