### PR TITLE
descpb: add Region as a type

### PR DESCRIPTION
**Pull request by otan**
For the sake of code readability, make region its own type in the
descpb package and change the regions and primary_region field to be
cast to this type.

Release note: None

### CODE REVIEW

**Review by ajstorm — COMMENTED** [review]
Nice!

:lgtm: 

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57105#-:-MN-j1DCE0Ci38tQ4dPU:bd6o4lx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/descriptor.go, line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57105#-MN-icsmDus0H67el4ln:-MN-icsn29vVDyTiao1k:btlnoqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccc6ec237ed9f30296ccf1923a266ae354afb05/pkg/sql/descriptor.go#L297)):*
> ```Go
> 				)
> 			}
> 			sort.Slice(regionConfig.Regions, func(i, j int) bool {
> ```

Nit: Do we want SliceStable here?

**Review by ajstorm — APPROVED** [review]
:lgtm:

Weird that the first one didn't approve.  Trying again.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57105#-:-MN-jEhk2ufN4BkjB9_x:bxgontc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

**Comment by otan** [comment]
cheers

bors r=ajstorm

**Comment by nvanbenschoten** [comment]
@otan @ajstorm Do you think we should keep the door open for (backwards compatible) per-region metadata by creating a `DatabaseRegion` proto message and maintaining a slice of these messages in the `DatabaseRegionConfig.regions`?

**Comment by otan** [comment]
not opposed, can do later!

**Pull request merged**
