### PR TITLE
sql: Remove Cockroach extension errors

### PR DESCRIPTION
**Pull request by nvb**
Both of the previous errors could be replaced by standard PG errors:

```
RetriableError:CR000            -> SerializationFailureError:40001
TransactionCommittedError:CR001 -> InvalidTransactionStateError:25000
```

This was a pretty straightforward change, but may deserver some discussion. It will
also require an update to the docs.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6797)

### CODE REVIEW

**Comment by bdarnell** [comment]
It also requires changes to https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go#L82.

**Comment by nvanbenschoten** [comment]
Is there any way we can version our `crdb` library to support this change without making it incompatible with old releases of CockroachDB?

**Comment by bdarnell** [comment]
In this case it's pretty easy; we just need to check for `pqErr.Code == "CR000" || pqErr.Code == "new code here"`. If the change were more involved we'd probably need to ask the server for its version and branch accordingly.

**Comment by andreimatei** [comment]
I'll throw another irresponsible opinion: I don't think anybody's using this library yet. How about we just handle the new code, and log a warning for a while if we see the old code. And after a while we remove the warning.

**Comment by andreimatei** [comment]
btw a bunch of the examples need to be changed too unfortunately

**Comment by nvanbenschoten** [comment]
Corresponding changes:
- `crdb` - https://github.com/cockroachdb/cockroach-go/pull/14
- `docs` - https://github.com/cockroachdb/docs/pull/315

**Comment by andreimatei** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Corresponding changes:
> 
> - `crdb` - https://github.com/cockroachdb/cockroach-go/pull/14
> 
> - `docs` - https://github.com/cockroachdb/docs/pull/315
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/errors.go, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6797#-KIYzP1HMtJDPbEyqbn3:-KIYzP1HMtJDPbEyqbn4:-966101015) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb28e1ab481c9cf2c475b85f55081e42ba851f5/sql/errors.go#L34)):*
> ```Go
> 
> // Cockroach error extensions:
> const (
> ```

btw I'm about to add another cockroach specific one - where do you think it should go? It's a "data unavailable" error, about not finding replicas ready to serve a range. I'm using a pg error class, but our own code.

---

*[sql/errors.go, line 75 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6797#-KIYzECcrhdpahSGqp3j:-KIYzECcrhdpahSGqp3k:-293939758) ([raw file](https://github.com/cockroachdb/cockroach/blob/04326b52166212c8f8e0cde6338bda0f75f853cf/sql/errors.go#L75)):*
> ```Go
> // errRetry means that the transaction can be retried. It signals to the user
> // that the SQL txn entered the RESTART_WAIT state after a serialization error,
> // and that a RESTART statement should be issued.
> ```

... and that a ROLLBACK TO SAVEPOINT COCKROACH_RESTART should...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6797#-:-KIYzeM-8kX9G5-_tu4v:1417088721)*

**Comment by nvanbenschoten** [comment]
TFTR! @bdarnell, should I merge this now, but wait until this weeks release to merge the other two changes?

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/errors.go, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6797#-KIYzP1HMtJDPbEyqbn3:-KIZ9H6gk9bMeiNp_RbK:-2048053974) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb28e1ab481c9cf2c475b85f55081e42ba851f5/sql/errors.go#L34)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> btw I'm about to add another cockroach specific one - where do you think it should go? It's a "data unavailable" error, about not finding replicas ready to serve a range. I'm using a pg error class, but our own code.
</details>
I think here is fine, unless you think we should create an `extensions.go` file in `pgwire/pgerror`.

---

*[sql/errors.go, line 75 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6797#-KIYzECcrhdpahSGqp3j:-KIZ9f5r9b8Ifi_U8JxB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/04326b52166212c8f8e0cde6338bda0f75f853cf/sql/errors.go#L75)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> ... and that a ROLLBACK TO SAVEPOINT COCKROACH_RESTART should...
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6797#-:-KIZ9ffjW8ZeRi6Wmehs:1681529348)*

**Comment by bdarnell** [comment]
LGTM. Merge this and the cockroach-go change now; merge the docs tomorrow night or thursday morning so they'll go live at the same time as the beta release. 

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> TFTR! @bdarnell, should I merge this now, but wait until this weeks release to merge the other two changes?
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/errors.go, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6797#-KIYzP1HMtJDPbEyqbn3:-KIZbZcc6xSnVuCUaFqi:-2084910305) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb28e1ab481c9cf2c475b85f55081e42ba851f5/sql/errors.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I think here is fine, unless you think we should create an `extensions.go` file in `pgwire/pgerror`.
</details>
Similar to deleting proto fields, we should have comments indicating that `CR000` and `CR001` have been used and can't be used again for another purpose. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6797#-:-KIZbLBgwEKB3b6h6Z7C:-1509415308)*

**Pull request merged**
