### PR TITLE
jobs: add a span to resumed jobs (for /debug/requests goodness)

### PR DESCRIPTION
**Pull request by danhhz**
Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27422#-:-LHBJwkY6aaFvbNjJ_hw:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/jobs/registry.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27422#-LHBJC8F-aH923jqX7K5:-LHBJC8F-aH923jqX7K6:b-nglut1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d54942d8f9e0b9eb04e4406c97df4c6b539c297a/pkg/sql/jobs/registry.go#L23)):*
> ```Go
> 	"time"
> 
> 	"github.com/cockroachdb/cockroach/pkg/settings"
> ```

If you happen to go through CI again, the pkg/settings import should be in the next block.

**Review by danhhz — COMMENTED** [review]
Thanks for the review! 

bors r=benesch

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27422#-:-LHBXto7B6hcyQ1kt6Go:b-xlzkds)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/jobs/registry.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27422#-LHBJC8F-aH923jqX7K5:-LHBXrLbB-J7dpxYoAmL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d54942d8f9e0b9eb04e4406c97df4c6b539c297a/pkg/sql/jobs/registry.go#L23)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

If you happen to go through CI again, the pkg/settings import should be in the next block.
</blockquote></details>

Done.

**Review by benesch — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27422)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/jobs/registry_external_test.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27422#-LHBZm7M4aDk-EM1r8Qa:-LHBZm7M4aDk-EM1r8Qb:b-ewzvd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3ab84a31bb16cb70487fc0a8567f7a768f5ec92/pkg/sql/jobs/registry_external_test.go#L89)):*
> ```Go
> 		const adoptInterval = time.Nanosecond
> 
> 		ac := log.AmbientContext{Tracer: tracing.NewTracer()}
> ```

Doesn't this need to be `r.settings.Tracer`? At least, it is in every other non-test AmbientContext. I'm not familiar with tracing at all though to know exactly what might go wrong if you create a fresh tracer.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27422)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/jobs/registry_external_test.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27422#-LHBZm7M4aDk-EM1r8Qa:-LHBiy-Z5bxeSCG4izRx:b-mqoxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3ab84a31bb16cb70487fc0a8567f7a768f5ec92/pkg/sql/jobs/registry_external_test.go#L89)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Doesn't this need to be `r.settings.Tracer`? At least, it is in every other non-test AmbientContext. I'm not familiar with tracing at all though to know exactly what might go wrong if you create a fresh tracer.
</blockquote></details>

Argh, sorry. I'd kicked off bors and didn't see this before it merged. There's quite a bit of precedent for `log.AmbientContext{Tracer: tracing.NewTracer()}` in tests and I only added this to fix a panic.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27422)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/jobs/registry_external_test.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27422#-LHBZm7M4aDk-EM1r8Qa:-LHBklDa9rR923rXb_En:b-ox61cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3ab84a31bb16cb70487fc0a8567f7a768f5ec92/pkg/sql/jobs/registry_external_test.go#L89)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Argh, sorry. I'd kicked off bors and didn't see this before it merged. There's quite a bit of precedent for `log.AmbientContext{Tracer: tracing.NewTracer()}` in tests and I only added this to fix a panic.
</blockquote></details>

No worries! It didn't seem like a serious enough problem to cancel your merge! I'm not even sure if it's a problem at all.

**Pull request merged**
