### PR TITLE
Remove Timestamp from (individual) ResponseHeader

### PR DESCRIPTION
**Pull request by tbg**
- drop ResponseHeader.Timestamp
- re-add Timestamp field on BatchResponse_Heaeder; it is set only for a batch
  of non-transactional writes.
- minor cleanups in executeBatch (more to come, in particular copy-on-write for
  the Txn)

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5228)

### CODE REVIEW

**Comment by tamird** [comment]
in commit message `s/Heaeder/Header/`

:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[roachpb/api.proto, line 695 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228#-KCq1WMpL8QZP3eXQMxD:-KCq1WMqivNqKdhu-mf9:1028556946) ([raw file](https://github.com/cockroachdb/cockroach/blob/a28ee6ddef553f1c416916080a90842d2b7da139/roachpb/api.proto#L695)):*
can you expand this comment to include an explanation of where this is used? it's likely to rot, but this comment leaves me wondering.

---

*[storage/replica.go, line 1643 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228#-KCq1xcQzRYaHYYoLl_N:-KCq1xcQzRYaHYYoLl_O:-1783916834) ([raw file](https://github.com/cockroachdb/cockroach/blob/a28ee6ddef553f1c416916080a90842d2b7da139/storage/replica.go#L1643)):*
s/ on//

---

*[storage/replica.go, line 1647 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228#-KCq25GDbw-ZML59zk-n:-KCq25GExVsPDjb8XSpa:35079676) ([raw file](https://github.com/cockroachdb/cockroach/blob/a28ee6ddef553f1c416916080a90842d2b7da139/storage/replica.go#L1647)):*
can you explain what this is actually doing?

---

*[storage/replica_test.go, line 1356 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228#-KCq2MEWJ-1DY-KsvRKu:-KCq2MEWJ-1DY-KsvRKv:-1870391584) ([raw file](https://github.com/cockroachdb/cockroach/blob/a28ee6ddef553f1c416916080a90842d2b7da139/storage/replica_test.go#L1356)):*
is client.SendWrapped still used, or was it supplanted by this method?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228#-:-KCq1Ire5GYQjLSXE7Uw:-180362119)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228#-:-KCqSlCjYHX5qY1kDOiT:676834233)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[roachpb/api.proto, line 695 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228#-KCq1WMpL8QZP3eXQMxD:-KCqZY5qNQJJkzscNNwR:-1063059654) ([raw file](https://github.com/cockroachdb/cockroach/blob/a28ee6ddef553f1c416916080a90842d2b7da139/roachpb/api.proto#L695)):*
Hmm. It's not used for anything, purely informational (I'd drop it, but tests need it). Updated.

---

*[storage/replica.go, line 1643 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228#-KCq1xcQzRYaHYYoLl_N:-KCq_d-qBgf28jKYLc_q:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a28ee6ddef553f1c416916080a90842d2b7da139/storage/replica.go#L1643)):*
Done.

---

*[storage/replica.go, line 1647 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228#-KCq25GDbw-ZML59zk-n:-KCq_dLU3dCYZe-9vSLz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a28ee6ddef553f1c416916080a90842d2b7da139/storage/replica.go#L1647)):*
Done.

---

*[storage/replica_test.go, line 1356 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228#-KCq2MEWJ-1DY-KsvRKu:-KCq_s_a_yDfjih0b0BK:-1097578109) ([raw file](https://github.com/cockroachdb/cockroach/blob/a28ee6ddef553f1c416916080a90842d2b7da139/storage/replica_test.go#L1356)):*
still used, 26 references. Would be nice to boil this down at some point, TODO added.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5228)*

**Pull request merged**
