### PR TITLE
storage: avoid per-kv allocations during consistency checks

### PR DESCRIPTION
**Pull request by nvb**
I noticed in an `alloc_objects` heap profile on a 3-node cluster restoring tpcc that more than 46% of all allocations were made in `computeChecksumPostApply`. Specifically, these allocations were all made in `Replica.sha512`. 28% of allocations were due to protobuf marshaling of `hlc.LegacyTimestamp`. 
The other 18% was in `encoding/binary.Write`.

This removes both of these sources of per-key allocations. The first allocation was avoided by sharing a byte buffer across protobuf marshals. The second was avoided by removing the call to `binary.Write` (see https://github.com/golang/go/issues/27403). I confirmed that this is no longer an issue by looking at heap profiles from before and after in a test that performed a consistency check.

I plan to follow up on https://github.com/golang/go/issues/27403 and search for any other offenders in our codebase. I already see a few.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
screen shot 2018-08-31 at 2 51 38 am

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29419#-:-LLEh7xg5yxDnf29wszM:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by jordanlewis** [comment]
Excellent! I've noticed these too - glad you figured out how to zap them.

**Comment by nvanbenschoten** [comment]
TFTRs.

bors r+

**Pull request merged**
