### PR TITLE
sql: mark SET LOCAL as unimplemented.

### LINKED ISSUE #6149: sql: separate SET LOCAL from SET SESSION
From the postgres documentation:

LOCAL
Specifies that the command takes effect for only the current transaction. After COMMIT or ROLLBACK, the session-level setting takes effect again. Note that SET LOCAL will appear to have no effect if it is executed outside a BEGIN block, since the transaction will end immediately.

We should either fix it or remove it from the grammar.

### PR DESCRIPTION
**Pull request by knz**
Fixes #6149.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10289)

### CODE REVIEW

**Review by madelynnblue — COMMENTED** [review]
Why keep SET SESSION?

**Comment by knz** [comment]
Because we still support SET SESSION.

**Comment by mjibson** [comment]
Jesse reported in the bug that session didn't appear to do anything. Is it
supposed to be an optional keyword like that?

**Comment by knz** [comment]
Yes "SET" without either LOCAL or SESSION is equivalent to "SET SESSION".

**Review by madelynnblue — APPROVED** [review]

**Pull request merged**
