### PR TITLE
opt: improve opt-tester ddl support

### PR DESCRIPTION
**Pull request by cucaroach**
Add support for enum's appearing in stats and add preliminary support
for indexes on materialized views, it doesn't do anything but doesn't
panic because it can't find the table.

Epic: none
Release note: None
Informs: #100510

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: This is so cool!

> Reviewed 6 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100655#-:-NSmMnhL1Jc42dA2eh4P:bj2ibg7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[`pkg/sql/opt/testutils/testcat/create_view.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100655#-NSmMVZQ1BW18bq0b-6W:-NSmMVZQ1BW18bq0b-6X:b-doe2eg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3beadc827f418b05f798fc167a336f95dc27b71/pkg/sql/opt/testutils/testcat/create_view.go#L38)):*
> ```Go
> 
> func (*View) addIndex(stmt *tree.IndexTableDef) {
> 	// TODO(cucaroach): implement
> ```

Unless we're planning on fixing this soon, would it be better to error?
___
*[`pkg/sql/opt/testutils/testcat/test_catalog.go` line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100655#-NSmMCBC6xOiTQSt1wKp:-NSmMCBC6xOiTQSt1wKq:bpthefy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3beadc827f418b05f798fc167a336f95dc27b71/pkg/sql/opt/testutils/testcat/test_catalog.go#L347)):*
> ```Go
> 
> // Table returns the test table that was previously added with the given name.
> func (tc *Catalog) LookupTable(name *tree.TableName) (*Table, error) {
> ```

[nit] comment needs updating.
___
*[`pkg/sql/opt/testutils/opttester/testdata/statement-bundle` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100655#-NSmL7WvAJrqDG317UEM:-NSmL7Ww4C1PJTlsXrR7:b-p33c4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5a2ff1543f16b25e410457a5e2918480d44e89/pkg/sql/opt/testutils/opttester/testdata/statement-bundle#L6)):*
> ```
> opt
> SELECT * FROM a WHERE a > 10 AND b < 5
> ---
> ```

[nit] what's up with the extra `---`?

Also, could you do `opt format=show-stats` to verify that stats were correctly loaded?

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100655)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/testutils/testcat/create_view.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100655#-NSmMVZQ1BW18bq0b-6W:-NSqTA4y3letkSGT9Bkn:b-pxurry) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3beadc827f418b05f798fc167a336f95dc27b71/pkg/sql/opt/testutils/testcat/create_view.go#L38)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Unless we're planning on fixing this soon, would it be better to error?
</blockquote></details>

Yeah, I'm just gonna split this up and push the enum fix and keep working on the view/index stuff until its actually working.  We'll just have to keep converting indexed MATERIALIZED views  into real tables for the time being which is fine.

**Comment by cucaroach** [comment]
bors r+
TFTRs!

**Comment by cucaroach** [comment]
blathers backport 23.1

**Pull request merged**
