### PR TITLE
vendor: bump Pebble to b958d9a7760b

### PR DESCRIPTION
**Pull request by bananabrick**
b958d9a7 sstable: add a writeQueue to the sstable writer
c8dad06c db: disable automatic compactions in `MetricsTest`
015f5e38 internal/rangekey: fix range key iteration bug

Release note: None

### CODE REVIEW

**Review by nicktrav — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @nicktrav)

___
*[DEPS.bzl, line 1221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75665#-MuX9u0FA_fsg80uWo-E:-MuX9u0FA_fsg80uWo-F:b-xvv836) ([raw file](https://github.com/cockroachdb/cockroach/blob/b227912091824a6f62d84aa9a173c8ffa1ccaec8/DEPS.bzl#L1221)):*
> ```Starlark
>         build_file_proto_mode = "disable_global",
>         importpath = "github.com/cockroachdb/pebble",
>         # TODO: mirror this repo (to fix, run `./dev generate bazel --mirror`)
> ```

If you pull the latest master and run this script again, it should take care of the TODO here. Or, run `./dev generate --mirror`. See #75254.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nicktrav)

___
*[DEPS.bzl, line 1221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75665#-MuX9u0FA_fsg80uWo-E:-MuXBkr4CarcEzYPsXix:bk1diw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b227912091824a6f62d84aa9a173c8ffa1ccaec8/DEPS.bzl#L1221)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

If you pull the latest master and run this script again, it should take care of the TODO here. Or, run `./dev generate --mirror`. See #75254.
</blockquote></details>

Aah, I am on the latest master, but don't use the `dev` tool.

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75665#-:-MuXCuNDDJg-JMGPG5m7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick)

**Comment by bananabrick** [comment]
tftr!

bors r+

**Pull request merged**
