### PR TITLE
docs: document the architecture of the SQL layer.

### PR DESCRIPTION
**Pull request by knz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14262)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Awesome, thanks for taking the time to do this! This would have been immensely useful when I first started (and it was a somewhat simpler time!) :)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-:-KfgK0niu63iIXwc83pV:b-cbcqcr)*

**Comment by eisenstatdavid** [comment]
:lgtm: fwiw from me

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-:-KfgtcpLY527C2PFtB9D:bxvvgpo)*

**Comment by nvanbenschoten** [comment]
This is awesome @knz, thanks for putting it together!

I'm curious how you envision us maintaining documentation like this to prevent it from rotting, since it's so specific to the details of our code base. Is this something we should be updating whenever a change affects it, or is it something we should be periodically auditing?

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[docs/tech-notes/sql.md, line 671 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-KfjOeW4MOCdmmscMsVU:-KfjOeW5RDwQjCXmp_z_:btdcel6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7917405f420431b8686521d283052ec9870c7d/docs/tech-notes/sql.md#L671)):*
> ```Markdown
> 
> (This code has become unwieldy and is ripe for refactoring and
> extensive re-documentatoin.)
> ```

`documentatoin`... didn't realize you spoke French.

Anyway, this section might need a decent rewrite if b5c8acd gets merged. I'd be happy to help.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-:-KfjPXUwknw5WAkFJVu0:b-vqdwql)*

**Comment by danhhz** [comment]
:lgtm_strong:  so good! thanks for doing this

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[docs/tech-notes/sql.md, line 392 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-Kfmah27oQB7dgigla5P:-Kfmah28mBdgA6j4ybo4:b-xgmgq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7917405f420431b8686521d283052ec9870c7d/docs/tech-notes/sql.md#L392)):*
> ```Markdown
> - `resolveNames`: knz
> - `TypeCheck`: nathan, jordan, knz
> - `NormalizeExpr`: peter, radu, nathan, knz
> ```

should we be using github usernames?

---

*[docs/tech-notes/sql.md, line 625 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-KfqhFQtgMuvtoc0zuHJ:-KfqhFQu7spehHU4I2wa:b-yw7q3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7917405f420431b8686521d283052ec9870c7d/docs/tech-notes/sql.md#L625)):*
> ```Markdown
>   nodes involved, manages the data "flows" and gathers the results.
> 
> See the distSQL RFC and "Life of a SQL query" for details.
> ```

link these please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-:-Kfqi2WIIfpWF-nPMOr9:b-2sypvi)*

**Comment by knz** [comment]
> @nvanbenschoten I'm curious how you envision us maintaining documentation like this to prevent it from rotting

My guiding principles: 1) old/outdated documentation is better than no documentation 2) internal documentation "tends to happen" on its own once its consumers start to realize its benefits. 

From there my expectation is that at the beginning some of us will update the docs every now and then "after the fact" but after a while it will become more common to start major changes by first updating the doc and submitting the change in a PR before the remainder of the patches.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[docs/tech-notes/sql.md, line 392 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-Kfmah27oQB7dgigla5P:-Kg9ppUbXEr1bG2K0NmQ:bf4qqcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7917405f420431b8686521d283052ec9870c7d/docs/tech-notes/sql.md#L392)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

should we be using github usernames?
</blockquote></details>

Not fond of it. I'm keen on using the handles by which we converse every day, and these tend to be both the email and slack aliases.

---

*[docs/tech-notes/sql.md, line 625 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-KfqhFQtgMuvtoc0zuHJ:-Kg9pzls4hBUuAfKzIqw:b-w0uvna) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7917405f420431b8686521d283052ec9870c7d/docs/tech-notes/sql.md#L625)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

link these please
</blockquote></details>

will submit separate PR to merge before the link can go in

---

*[docs/tech-notes/sql.md, line 671 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-KfjOeW4MOCdmmscMsVU:-Kg9q2KP-r0CJQNN5n33:bkt5drs) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7917405f420431b8686521d283052ec9870c7d/docs/tech-notes/sql.md#L671)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`documentatoin`... didn't realize you spoke French.

Anyway, this section might need a decent rewrite if b5c8acd gets merged. I'd be happy to help.
</blockquote></details>

Sure, thanks :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-:-Kg9pAlDi5Vox-pXeG4T:bq8zynj)*

**Comment by danhhz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[docs/tech-notes/sql.md, line 392 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-Kfmah27oQB7dgigla5P:-KgFEpfc7pwy-Ti372uz:b-2q96w7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7917405f420431b8686521d283052ec9870c7d/docs/tech-notes/sql.md#L392)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Not fond of it. I'm keen on using the handles by which we converse every day, and these tend to be both the email and slack aliases.
</blockquote></details>

The counter argument is that this is less useful for outside contributors, who tend to communicate with us via github or gitter and not email or slack. That's the last I'll say on this though, so if you feel strongly, feel free to leave this as is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262)*

**Comment by knz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/tech-notes/sql.md, line 625 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-KfqhFQtgMuvtoc0zuHJ:-KiGROG6RXViRrFjx6JG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7917405f420431b8686521d283052ec9870c7d/docs/tech-notes/sql.md#L625)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

will submit separate PR to merge before the link can go in
</blockquote></details>

Done.

---

*[docs/tech-notes/sql.md, line 671 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262#-KfjOeW4MOCdmmscMsVU:-KiGRReDGlOWcesF6mQ-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7917405f420431b8686521d283052ec9870c7d/docs/tech-notes/sql.md#L671)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Sure, thanks :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14262)*

**Pull request merged**
