### PR TITLE
sql: move parallelize scans control in the execbuilder

### PR DESCRIPTION
**Pull request by RaduBerinde**
Parallel scans refers to disabling scan batch limits, which allows the
distsender to issue requests to multiple ranges in parallel. This is
only safe to use when there is a known upper bound for the number of
results.

Currently we plumb maxResults to the scanNode and TableReader, and
each execution component runs similar logic to decide whether to
parallelize.

This change cleans this up by centralizing this decision inside the
execbuilder. In the future, we may want the coster to be aware of this
parallelization as well.

For simplicity, we drop the cluster setting that controls this (it was
added for fear of problems but it has been on by default for a long
time).

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51121#-MBjUQP1224VpyfwoOJe:-MBjUQP1224VpyfwoOJf:b-8xmsdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/878dc05303a49527cede5686b00ee81dca9d227a/pkg/sql/distsql_spec_exec_factory.go#L207)):*
> ```Go
> 	}
> 
> 	// TODO(yuzefovich): scanNode adds "parallel" attribute in walk.go when
> ```

Do you think this TODO is not necessary because you'll be refactoring EXPLAIN (PLAN) soon?
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51121#-MBjUlmZ6jwocs_6R1Hl:-MBjUlm_1XZcmTnT9OqJ:b-l4yv2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f859e9c008243f62f4cb8254be732dc5cee5b03f/pkg/sql/colfetcher/colbatch_scan.go#L157)):*
> ```Go
> 		rf:          &fetcher,
> 		limitHint:   limitHint,
> 		parallelize: spec.Parallelize && limitHint == 0,
> ```

Hm, is `limitHint == 0` part is necessary? I'd expected the execbuilder to know about the limit hint and set `spec.Parallelize` accordingly. Or is it for backwards-compatibility?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51121#-MBjUQP1224VpyfwoOJe:-MBjbmu0D2ahSVxaPgV5:bqf4ywl) ([raw file](https://github.com/cockroachdb/cockroach/blob/878dc05303a49527cede5686b00ee81dca9d227a/pkg/sql/distsql_spec_exec_factory.go#L207)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do you think this TODO is not necessary because you'll be refactoring EXPLAIN (PLAN) soon?
</blockquote></details>

I may be misunderstanding the TODO, but now this information is plumbed in the parallelize field. In any case, I am indeed working on EXPLAIN (this change is fallout from that work), but it seems like it's a pretty big project :)
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51121#-MBjUlmZ6jwocs_6R1Hl:-MBjcA1u86F9vnrMhhNC:b-m6ujvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f859e9c008243f62f4cb8254be732dc5cee5b03f/pkg/sql/colfetcher/colbatch_scan.go#L157)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, is `limitHint == 0` part is necessary? I'd expected the execbuilder to know about the limit hint and set `spec.Parallelize` accordingly. Or is it for backwards-compatibility?
</blockquote></details>

It shouldn't be necessary.. I put it there just in case the upper layers messed up. Maybe I should remove it.. In principle maybe the upper layers could decide it's better to parallelized even if there's a limit (e.g. there are 100 single-key spans and the limit it 90).

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51121#-:-MBkTYb75lJ1NYfF2JjB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51121#-MBjUQP1224VpyfwoOJe:-MBkSNl-7aosC3XIOrjO:b-s0amxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/878dc05303a49527cede5686b00ee81dca9d227a/pkg/sql/distsql_spec_exec_factory.go#L207)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I may be misunderstanding the TODO, but now this information is plumbed in the parallelize field. In any case, I am indeed working on EXPLAIN (this change is fallout from that work), but it seems like it's a pretty big project :)
</blockquote></details>

This TODO comes from the fact that with the new factory we don't have a `planNode` tree, and "parallel" attribute could added in `EXPLAIN (PLAN)` because there is a `scanNode` with `parallelize==true` which is not the case in this factory. I'd keep this TODO as a reminder that the new factory needs to somehow propagate information about `parallize` flag to `EXPLAIN (PLAN)` (refactoring of each is, indeed, quite a big lift).
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51121#-MBjUlmZ6jwocs_6R1Hl:-MBkT2Rz36Dx2Id8EDNi:bal9aup) ([raw file](https://github.com/cockroachdb/cockroach/blob/f859e9c008243f62f4cb8254be732dc5cee5b03f/pkg/sql/colfetcher/colbatch_scan.go#L157)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It shouldn't be necessary.. I put it there just in case the upper layers messed up. Maybe I should remove it.. In principle maybe the upper layers could decide it's better to parallelized even if there's a limit (e.g. there are 100 single-key spans and the limit it 90).
</blockquote></details>

I see, it might be worth keeping it but also please add a comment for why we still check the limit hint.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51121)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51121#-MBjUQP1224VpyfwoOJe:-MBkUiST4k3V7woLpFoH:b-rcvuyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/878dc05303a49527cede5686b00ee81dca9d227a/pkg/sql/distsql_spec_exec_factory.go#L207)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This TODO comes from the fact that with the new factory we don't have a `planNode` tree, and "parallel" attribute could added in `EXPLAIN (PLAN)` because there is a `scanNode` with `parallelize==true` which is not the case in this factory. I'd keep this TODO as a reminder that the new factory needs to somehow propagate information about `parallize` flag to `EXPLAIN (PLAN)` (refactoring of each is, indeed, quite a big lift).
</blockquote></details>

But (after my change)  how is `parallelize` different than any other property passed to `ConstructScan`? In principle, we could check the field from the TableReader specs if we wanted to extract this information.
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51121#-MBjUlmZ6jwocs_6R1Hl:-MBkVVLYDbetb7M6hp5B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f859e9c008243f62f4cb8254be732dc5cee5b03f/pkg/sql/colfetcher/colbatch_scan.go#L157)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I see, it might be worth keeping it but also please add a comment for why we still check the limit hint.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51121)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51121#-MBjUQP1224VpyfwoOJe:-MBkVq2i2tUFvmjGfNKV:btjampl) ([raw file](https://github.com/cockroachdb/cockroach/blob/878dc05303a49527cede5686b00ee81dca9d227a/pkg/sql/distsql_spec_exec_factory.go#L207)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

But (after my change)  how is `parallelize` different than any other property passed to `ConstructScan`? In principle, we could check the field from the TableReader specs if we wanted to extract this information.
</blockquote></details>

Good point, let's remove it then.

**Pull request merged**
