### PR TITLE
sql: version gate idx recommendations in insert-stmt-stats

### LINKED ISSUE #88140: sql: insert-stmt-stats is not version gated and fails in mixed-version state
**Describe the problem**

In a mixed-version state (with nodes running the 22.2 binary but still on a 22.1 cluster version), I see a number of log lines such as:

```
W220912 15:21:54.889174 398 sql/sqlstats/persistedsqlstats/flush.go:117 ⋮ [n1] 2118  ‹failed to flush statement statistics›: flush statement ‹738159740542152745›'s statistics: ‹insert-stmt-stats›: ‹INSERT› has more ‹expressions› than ‹target columns›, 11 expressions for 10 targets
```

This is the result of an insert statement that requires a newly added column but which doesn't use a version gate to ensure that the column was added.

https://github.com/cockroachdb/cockroach/blob/fc308c1bf97c42af6f175723d78011c1bb1b0f72/pkg/sql/sqlstats/persistedsqlstats/flush.go#L475-L481

To avoid this, we likely need to conditionally insert the index recommendations based on a version gate on https://github.com/cockroachdb/cockroach/blob/fc308c1bf97c42af6f175723d78011c1bb1b0f72/pkg/clusterversion/cockroach_versions.go#L219

We simply log this failure, so the only impact is that the stats we had hoped to persist are not persisted and some log spam.

**To Reproduce**

This can be seen in the `import/mixed-versions` roachtest.

Jira issue: CRDB-19707

### PR DESCRIPTION
**Pull request by ericharmeling**
This commit version gates index recommendation insert in insert-stmt-stats.

Fixes #88140.

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88165#-:-NCNXHtlCqzFQnV4Jft5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by stevendanna — APPROVED** [review]
Thanks!

**Comment by ericharmeling** [comment]
TFTRs!

**Comment by ericharmeling** [comment]
bors +

**Comment by ericharmeling** [comment]
bors retry

**Comment by ericharmeling** [comment]
blathers backport release-22.2

**Pull request merged**
