### PR TITLE
sql/catalog/*desc: add redacted log support

### LINKED ISSUE #51239: sql/catalog: implement log redaction on sqlbase types
**Is your feature request related to a problem? Please describe.**

With the new PII redaction logging framework we now should both adopt it and augment our logging of catalog structure, especially in error scenarios. This is something of a placeholder issue to appropriately implement `SafeValue` and `SafeFormat` on various descriptor types and their members.

### PR DESCRIPTION
**Pull request by ajwerner**
See individual commits. This PR ended up being much more toil that I had anticipated. I generally regret having done it and fear that I've missed some things. That being said, I think it's a valuable contribution even if we ultimately do replace it with something more reflective and programmatic.

Fixes #51239. 

Release note: None.

### CODE REVIEW

**Review by thoszhang — APPROVED** [review]
I see what you mean about the level of toil but I agree this is an improvement.

What are you worried about with regards to testing? I feel like even if we make some errors here we'll still be able to generate human-readable output, and it's probably not too bad if we generate some invalid YAML.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55308#-:-MJ47IZq0rxrSBsJ3B9k:b-fl8iz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/tabledesc/safe_format.go, line 266 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/55308#-MJ4ARZO6s2d7pIEtMro:-MJ4ARZP893UHH9xESLs:bbigask) ([raw file](https://github.com/cockroachdb/cockroach/blob/4153fb69bf2db03cc20321ad6fd669896296f030/pkg/sql/catalog/tabledesc/safe_format.go#L266)):*
> ```Go
> 	mutations := make([]*descpb.DescriptorMutation, len(checks))
> 	checks = checks[:len(checks):len(checks)] // copy on append
> 	for i := range allMutations {
> ```

Don't you end up with duplicates here if we're validating the constraint (meaning it's already in `TableDescriptor.Checks`)? Same goes for other constraints.

I think I might prefer the mutations just being listed separately (so we'd call separate functions to format an individual check constraint, etc., inside the mutation). It would make it easier to see when mutations are backed up behind other mutations, and it would also be a more natural way to include the mutations that aren't really schema elements (like `PrimaryKeySwap`). I also think for simplicity we should try to just match the structure of the proto message as much as possible so we don't have to think about the details of the formatter too much. But I'm also fine with this change as is.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55308)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/catalog/tabledesc/safe_format.go, line 266 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/55308#-MJ4ARZO6s2d7pIEtMro:-MJDKj1Q15oOYLlrrd-g:b-kymqcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4153fb69bf2db03cc20321ad6fd669896296f030/pkg/sql/catalog/tabledesc/safe_format.go#L266)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Don't you end up with duplicates here if we're validating the constraint (meaning it's already in `TableDescriptor.Checks`)? Same goes for other constraints.

I think I might prefer the mutations just being listed separately (so we'd call separate functions to format an individual check constraint, etc., inside the mutation). It would make it easier to see when mutations are backed up behind other mutations, and it would also be a more natural way to include the mutations that aren't really schema elements (like `PrimaryKeySwap`). I also think for simplicity we should try to just match the structure of the proto message as much as possible so we don't have to think about the details of the formatter too much. But I'm also fine with this change as is.
</blockquote></details>

Okay, I've added code to additional produce the mutations as a section.

**Review by thoszhang — APPROVED** [review]
> Reviewed 13 of 13 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55308)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/tabledesc/safe_format.go, line 79 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/55308#-MJDQTfm5CPNNKNjUlVL:-MJDQTfm5CPNNKNjUlVM:b-ny4rso) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d563cd734815a7f96e5a9d936a38083c7fef762/pkg/sql/catalog/tabledesc/safe_format.go#L79)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	for i := range td.Mutations {
> 		if c := td.Mutations[i].GetColumn(); c != nil {
> 			formatColumn(c, &td.Mutations[i])
> 		}
> 	}
> ```
</details>

I'd kind of prefer we also stopped including mutations with the public schema elements. But I don't feel strongly either way.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55308)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/catalog/tabledesc/safe_format.go, line 79 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/55308#-MJDQTfm5CPNNKNjUlVL:-MJDgq6uCPWZ-0ZbiVX5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d563cd734815a7f96e5a9d936a38083c7fef762/pkg/sql/catalog/tabledesc/safe_format.go#L79)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

> ```
> 	for i := range td.Mutations {
> 		if c := td.Mutations[i].GetColumn(); c != nil {
> 			formatColumn(c, &td.Mutations[i])
> 		}
> 	}
> ```
I'd kind of prefer we also stopped including mutations with the public schema elements. But I don't feel strongly either way.
</blockquote></details>

Done.

**Review by thoszhang — APPROVED** [review]
> Reviewed 7 of 7 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55308)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Comment by ajwerner** [comment]
TFTR!

bors r=lucy-zhang

**Pull request merged**
