### PR TITLE
kv: clean up cluster setting handling in `DB` and `Txn`

### PR DESCRIPTION
**Pull request by nvb**
This PR contains a series of 3 commits which make it easier to deal with cluster settings in `pkg/kv`.

Epic: None
Release note: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
Looks good overall to me.

**Review by arulajmani — APPROVED** [review]
Reviewed while looking at https://github.com/cockroachdb/cockroach/pull/119482. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118978#-:-NrGrpVBAlBL3YRcQtBm:bc94k06)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Comment by nvanbenschoten** [comment]
```
Failed to perform checkout on agent: Cannot find commit 79d9d40efc179e582426936db399ab6eaa9ff23b in the https://github.com/cockroachdb/cockroach repository, possible reason: refs/heads/staging branch was updated and the commit selected for the build is not reachable anymore
```
CI flake.

bors r+

**Pull request merged**
