### PR TITLE
cli/demo: sanitize the creation of secondary tenants

### LINKED ISSUE #94315: cli/demo: `cockroach demo --multitenant=true --nodes N` generates too many tenants
Currently `cockroach demo --multitenant=true --nodes N` generates N different secondary tenants, instead of just 1 secondary tenants across N different nodes. This is nonsensical!

It also makes multi-tenant `demo` unncessarily complex to use.

Epic: CRDB-22814.

Jira issue: CRDB-22825

### LINKED ISSUE #94391: cli/demo: autologin for secondary tenants is broken
What the title says.

 Epic: CRDB-22814

Jira issue: CRDB-22869

### PR DESCRIPTION
**Pull request by knz**
Fixes: #94315
Fixes: #94391
Epic: CRDB-22814

Prior to this patch, `cockroach demo --multitenant=true --nodes N` was
creating N different secondary tenants, with one SQL server per
tenant.

This was totally besides the point -- to show multi-node scalability,
we want N different SQL servers _for the same tenant_.

This commit fixes that.

For example:
```
     Application tenant:
      (webui)    http://127.0.0.1:8080/demologin?password=demo41322&username=demo
      (sql)      postgresql://demo:demo41322@127.0.0.1:26257/movr?sslmode=require&sslrootcert=%2Ftmp%2Fdemo3364057791%2Fca-client-tenant.crt
      (sql/jdbc) jdbc:postgresql://127.0.0.1:26257/movr?password=demo41322&sslmode=require&sslrootcert=%2Ftmp%2Fdemo3364057791%2Fca-client-tenant.crt&user=demo

     System tenant:
      (webui)    http://127.0.0.1:8083/demologin?password=demo41322&username=demo
      (sql)      postgresql://demo:demo41322@127.0.0.1:26260/defaultdb?sslmode=require&sslrootcert=%2Ftmp%2Fdemo3364057791%2Fca.crt
      (sql/jdbc) jdbc:postgresql://127.0.0.1:26260/defaultdb?password=demo41322&sslmode=require&sslrootcert=%2Ftmp%2Fdemo3364057791%2Fca.crt&user=demo
      (sql/unix) postgresql://demo:demo41322@/defaultdb?host=%2Ftmp%2Fdemo3364057791&port=26260
```

Note: this output will be further simplified once we use a single SQL
listener for multiple tenants; see https://github.com/cockroachdb/cockroach/pull/92580; and also when we support
using a shared HTTP listener for the demo servers (i.e. when the work
from PR https://github.com/cockroachdb/cockroach/pull/91744 is extended to `cockroach demo`).

(no release note since this functionality is not yet exposed to end-users)

### CODE REVIEW

**Comment by knz** [comment]
@aadityasondhi you will need this. feel free to review.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, 4 of 4 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/clisqlshell/sql.go` line 112 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94321#-NKOXJwk32CJcDMSKAsC:-NKOXJwk32CJcDMSKAsD:b-kzema0) ([raw file](https://github.com/cockroachdb/cockroach/blob/77afcd2eb830fa2f826a2793b3685e4a654bcd71/pkg/cli/clisqlshell/sql.go#L112)):*
> ```Go
> Commands specific to the demo shell (EXPERIMENTAL):
>   \demo ls                     list the demo nodes and their connection URLs.
>   \demo shutdown <idx>         stop a demo server.
> ```

This appears to add confusion to the user. Why would shutdown use serverIDs while decom/recom commands just below use nodeIDs?

I'd like the preserve the common use-case here and keep referring to "nodes". is that not possible? I know there's no guarantee that the sequences match, but it sounds like they have ended up matching for a while, so what's the harm?
___
*[`pkg/cli/democluster/demo_cluster.go` line 828 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94321#-NKOYMuNA3T0KoSi3y8W:-NKOYMuNA3T0KoSi3y8X:b-pbattc) ([raw file](https://github.com/cockroachdb/cockroach/blob/77afcd2eb830fa2f826a2793b3685e4a654bcd71/pkg/cli/democluster/demo_cluster.go#L828)):*
> ```Go
> 	}
> 
> 	serverIdx := int(userFriendlyServerIndex - 1)
> ```

It appears that server indexes are zero-indexed so why subtract 1?
___
*[`pkg/cli/democluster/demo_cluster.go` line 937 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94321#-NKOYSuQ5L0bJbUsZ6Jy:-NKOYSuR3s1_tSPPigh9:bj8bld6) ([raw file](https://github.com/cockroachdb/cockroach/blob/77afcd2eb830fa2f826a2793b3685e4a654bcd71/pkg/cli/democluster/demo_cluster.go#L937)):*
> ```Go
> // The node will restart, connecting to the same in memory node.
> func (c *transientCluster) RestartNode(ctx context.Context, userFriendlyServerIndex int32) error {
> 	serverIdx := int(userFriendlyServerIndex - 1)
> ```

same as above.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/cli/clisqlshell/sql.go` line 112 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94321#-NKOXJwk32CJcDMSKAsC:-NKOdJl_1NLIDCBBV-MS:b-t4e77l) ([raw file](https://github.com/cockroachdb/cockroach/blob/77afcd2eb830fa2f826a2793b3685e4a654bcd71/pkg/cli/clisqlshell/sql.go#L112)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This appears to add confusion to the user. Why would shutdown use serverIDs while decom/recom commands just below use nodeIDs?

I'd like the preserve the common use-case here and keep referring to "nodes". is that not possible? I know there's no guarantee that the sequences match, but it sounds like they have ended up matching for a while, so what's the harm?
</blockquote></details>

If you decommission a server, then restart it, it will get a new node ID.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/cli/clisqlshell/sql.go` line 112 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94321#-NKOXJwk32CJcDMSKAsC:-NKOdb-7DDXU-3v14TIq:b-oeq67x) ([raw file](https://github.com/cockroachdb/cockroach/blob/77afcd2eb830fa2f826a2793b3685e4a654bcd71/pkg/cli/clisqlshell/sql.go#L112)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

If you decommission a server, then restart it, it will get a new node ID.
</blockquote></details>

I will change the code to do a nodeID lookup instead, stay tuned

**Review by dhartunian — COMMENTED** [review]
I think somewhere the `EnableDemoLoginEndpoint` flag gets lost on the tenant, the login link doesn't work for me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94321#-:-NKOeCb27ccedVcQEsdB:bk550of)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/clisqlshell/sql.go` line 112 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94321#-NKOXJwk32CJcDMSKAsC:-NKOe9mfET6H25X-eq9b:b-pmfw02) ([raw file](https://github.com/cockroachdb/cockroach/blob/77afcd2eb830fa2f826a2793b3685e4a654bcd71/pkg/cli/clisqlshell/sql.go#L112)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I will change the code to do a nodeID lookup instead, stay tuned
</blockquote></details>

Gotcha. thanks.

**Review by knz — COMMENTED** [review]
RFAL.

> I think somewhere the EnableDemoLoginEndpoint flag gets lost on the tenant, the login link doesn't work for me.

That was a separate issue (#94391) but I'm adding a commit here to fix it. No unit tests yet since we're going to refactor this heavily in your other PR to use the server controller.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94321#-:-NKPbnX23cWCy7F6c4EH:b-pu58hs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/cli/clisqlshell/sql.go` line 112 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/94321#-NKOXJwk32CJcDMSKAsC:-NKPZpFzC6U177exQb24:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77afcd2eb830fa2f826a2793b3685e4a654bcd71/pkg/cli/clisqlshell/sql.go#L112)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Gotcha. thanks.
</blockquote></details>

Done.

**Pull request merged**
