### PR TITLE
sql: add `pg_backend_pid` column to `crdb_internal.{node,cluster}_sessions`

### LINKED ISSUE #98581: sql: add pg_backend_pid column to crdb_internal.{node, cluster}_sessions
I don't believe we currently have a way to look at a registry of sessions and their corresponding backend PIDs. If that's correct, we should expose the `pg_backend_pid` in the `crdb_internal.node_sessions` and `crdb_internal.cluster_sessions` system tables.

This will be helpful for https://github.com/cockroachdb/cockroach/issues/95771.

Jira issue: CRDB-25576

### PR DESCRIPTION
**Pull request by nvb**
Fixes #98581.
Informs #95771.

This commit adds a new `pg_backend_pid` column to the `crdb_internal.node_sessions` and `crdb_internal.cluster_sessions` tables.

Release note (sql change): A pg_backend_pid column was added to crdb_internal.node_sessions and crdb_internal.cluster_sessions. This value corresponds to the numerical ID returned from pg_backend_pid().

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice! just had suggestions for the comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116673#-:-NlyOU4p5wd020NS0Kf_:byz9s0j)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/server/serverpb/status.proto` line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116673#-NlyO86b3xgqI3QObPQp:-NlyO86b3xgqI3QObPQq:buqbg3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a95753b35ce59472f77330045081cec30eaac06/pkg/server/serverpb/status.proto#L1052)):*
> ```proto
>     (gogoproto.stdduration) = true];
> 
>   // The Postgres backend PID of the session.
> ```

it might be useful to document the ways this differs from the Postgres PID. The following comments have more info, which might be useful to include here too so that people don't think this is actually a PID.

https://github.com/cockroachdb/cockroach/blob/6581b3642e2b63ba4c619903b07c0e3971709250/pkg/sql/sem/builtins/pg_builtins.go#L591-L594

https://github.com/cockroachdb/cockroach/blob/343335ada6d05016b26dc20c2aa1bcebe71d351d/pkg/sql/pgwire/pgwirecancel/backend_key_data.go#L19-L27
___
*[`pkg/sql/crdb_internal.go` line 2813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116673#-NlyOKZE4vDtTEwTSWyK:-NlyOKZE4vDtTEwTSWyL:b-84fyha) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a95753b35ce59472f77330045081cec30eaac06/pkg/sql/crdb_internal.go#L2813)):*
> ```Go
>   status             STRING,         -- the status of the session (open, closed)
>   session_end        TIMESTAMPTZ,    -- the time when the session was closed
>   pg_backend_pid     INT             -- the postgres backend PID of the session
> ```

same for the comment here; it feels misleading to just say this is the same as the postgres backend PID.

**Review by nvb — COMMENTED** [review]
I'm actually not going to add this column to `node_queries`, `cluster_queries`, `node_transactions`, or `cluster_transactions`. It has such a specialized role and including it more widely might promote confusion or abuse.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116673#-:-NlybcK38Gg97G1a65Cg:b-poc2zy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/server/serverpb/status.proto` line 1052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116673#-NlyO86b3xgqI3QObPQp:-NlybHAq87lXcyyRcF-T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a95753b35ce59472f77330045081cec30eaac06/pkg/server/serverpb/status.proto#L1052)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it might be useful to document the ways this differs from the Postgres PID. The following comments have more info, which might be useful to include here too so that people don't think this is actually a PID.

https://github.com/cockroachdb/cockroach/blob/6581b3642e2b63ba4c619903b07c0e3971709250/pkg/sql/sem/builtins/pg_builtins.go#L591-L594

https://github.com/cockroachdb/cockroach/blob/343335ada6d05016b26dc20c2aa1bcebe71d351d/pkg/sql/pgwire/pgwirecancel/backend_key_data.go#L19-L27
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal.go` line 2813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116673#-NlyOKZE4vDtTEwTSWyK:-Nlybb4qAztabP7ljVZl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a95753b35ce59472f77330045081cec30eaac06/pkg/sql/crdb_internal.go#L2813)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

same for the comment here; it feels misleading to just say this is the same as the postgres backend PID.
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
TFTR!

**Comment by nvanbenschoten** [comment]
bors r=rafiss

**Pull request merged**
