### PR TITLE
roachpb,rowenc: remove geo dep from roachpb

### PR DESCRIPTION
**Pull request by ajwerner**
This dep was transitively bringing in pebble and cgo.

Release note: None

### CODE REVIEW

**Review by otan — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by jordanlewis** [comment]
Nice! Can you add a case for this into the `dep_test.go` file in `roachpb`? It's meant to help us avoid unwanted imports like this.

**Comment by ajwerner** [comment]
> Nice! Can you add a case for this into the dep_test.go file in roachpb? It's meant to help us avoid unwanted imports like this.

Doing it now. Turns out `dep_test` is totally busted :(.

**Comment by otan** [comment]
can we solve these with bazel visibility rules

**Comment by otan** [comment]
alternative, use `bazel query 'somepath(...)'` as a test, heh.

**Comment by ajwerner** [comment]
> can we solve these with bazel visibility rules

I'll play around

What I want to point out is that this line where we say `FindOnly` means that we never check any imports; `pkg.Imports` is always empty.

https://github.com/cockroachdb/cockroach/blob/1d0597990de15fc7722d288a4a3ebd50cf06b50a/pkg/testutils/buildutil/build.go#L54

>	// If FindOnly is set, Import stops after locating the directory
	// that should contain the sources for a package. It does not
	// read any files in the directory.
	FindOnly ImportMode = 1 << iota

**Comment by ajwerner** [comment]
Unsetting that flag makes this test insanely slow.

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/pull/64450 is well on its way.

**Pull request merged**
