### PR TITLE
ui: address some remaining 1.1 bugs

### PR DESCRIPTION
**Pull request by benesch**
screenshot 2017-09-01 10 32 47

/cc @dianasaur323 

@BramGruneir or @mrtracy either of you have the bandwidth to review this?

### CODE REVIEW

**Comment by dianasaur323** [comment]
Ok, showing the job id makes sense to me, although one concern is that we might not want to reveal that information before having user login? I believe that surfacing more admin like capabilities was dependent on login, which didn't make it into 1.1. The tooltip text looks good to me, although one thought is, should we just straight up say backup / restore, since those are the only jobs you can cancel? Either way, stylistic choice, so your call on that one.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-:-KsxrTOYqhjlvAVoBWWr:bw3oab1)*

**Comment by benesch** [comment]
Oh, are we not going to have user login before 1.1? Immaterial either way; the ID is actually far less sensitive than the description, which can reveal where this data is going in cloud storage. If we're comfortable showing the description I think we should definitely be comfortable showing the ID.

I was vague about which jobs are pausable/cancelable since I have a feeling we'll forget to update that tooltip when schema changes/import supports P/R/C. The way it's worded at the moment means it will never be wrong. :)

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-:-Ksxt2_DBXV5ZNehkrcq:bjub5vu)*

**Comment by dianasaur323** [comment]
Got it - your rationale regarding job ID makes sense. I mean, they can't make any changes without having access to the cluster anyway. 

Lol, ok - in that case, tool tip sounds fine to me. 

Thanks!! 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-:-Ksxv0Kzifb977N-FtWd:b-mffnjo)*

**Comment by BramGruneir** [comment]
Can you post a before/after for the nodes page?  Ideally showing the decommissioning changes?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-:-Ksy1esFP7v4BWVx3qYs:bwzybr2)*

**Comment by BramGruneir** [comment]
Reviewed 1 of 1 files at r2, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/ui/src/util/docs.ts, line 6 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy1E8iiHoY_na9WRfb:-Ksy1E8jV3XqjoBbBujT:befscok) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/util/docs.ts#L6)):*
> ```XML
> const docsURLBase = "https://www.cockroachlabs.com/docs/v1.1";
> 
> export function docsURL(pageName: string): string {
> ```

might as well just make this the default export

---

*[pkg/ui/src/views/jobs/index.tsx, line 52 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy2uUOSHfWmQbqU1to:-Ksy2uUOSHfWmQbqU1tp:b-hgwoxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/views/jobs/index.tsx#L52)):*
> ```XML
> 
> const showOptions = [
>   { value: "50", label: "Newest 50" },
> ```

Nit: I think `Latest` is more correct here.  They both work I think.

---

*[pkg/ui/src/views/jobs/index.tsx, line 168 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy2DXR_sMrhp_vztnF:-Ksy2DXR_sMrhp_vztnG:be5en1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/views/jobs/index.tsx#L168)):*
> ```XML
>   Some jobs can be paused or canceled through SQL. For details, view the docs
>   on the <a href={docsURL("pause-job.html")}><code>PAUSE JOB</code></a> and <a
>   href={docsURL("cancel-job.html")}><code>CANCEL JOB</code></a> statements.
> ```

use <link> instead of <a>

---

*[pkg/ui/styl/base/typography.styl, line 67 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy3Ke9eN5ip7LsmcZV:-Ksy3Ke9eN5ip7LsmcZW:b-rdfxjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/styl/base/typography.styl#L67)):*
> ```Stylus
>   font-weight 600
> 
> code
> ```

Why are you changing fonts?

---

*[pkg/ui/styl/layout/layout.styl, line 60 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy3SK-Jh7OcMffBkEA:-Ksy3SK-Jh7OcMffBkEB:b-2s2apv) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/styl/layout/layout.styl#L60)):*
> ```Stylus
>   letter-spacing 5px
> 
>   &__tooltip
> ```

We use too many px measurements.  Ugh.  Not that you should change this, but we should move to relative sizes soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137)*

**Comment by mrtracy** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/ui/src/views/jobs/index.tsx, line 168 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy2DXR_sMrhp_vztnF:-KsyuWpm98xy25csUH9d:byf8tzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/views/jobs/index.tsx#L168)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

use <link> instead of <a>
</blockquote></details>

These are multi-line JSX, so they should go in a set of parenthesis.  Like:

```typescript
const titleTooltip = (
  <span>
    lots of words...
  </span>
);
```

We're up against the 1.1 deadline so I won't hold you to all this, because we are going to start linting for it in 1.2.   However, just something to be aware of if you continue working on UI pages in the future.

---

*[pkg/ui/styl/layout/layout.styl, line 60 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy3SK-Jh7OcMffBkEA:-KsyuzARJFu56zCOfOsD:be84aux) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/styl/layout/layout.styl#L60)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

We use too many px measurements.  Ugh.  Not that you should change this, but we should move to relative sizes soon.
</blockquote></details>

We explicitly moved from relative sizes to px.  Every designer i've worked with has preferred px, and I don't believe that using relative units confers *any* accessibility benefit anymore; all browsers can just zoom in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137)*

**Comment by mrtracy** [comment]
Just FYI, I just merged #17673, which is an older PR that should have been merged quite a while ago.  It alters the appearance of the Tooltip icon on graphs, and I see in this PR that you are adding a tooltip icon on the Jobs page.  You should double check that the newly merged PR doesn't mess up your CSS for that icon.  If y'u

I apologize for this, it's my bad; should have had that PR merged a while ago, I just forgot to press "merge".

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-:-KsyxBoFku1i8VshftTk:b-jbcm8p)*

**Comment by benesch** [comment]
No worries @mrtracy! The rebase went smoothly!

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/ui/src/util/docs.ts, line 6 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy1E8iiHoY_na9WRfb:-KsysvNdtt9H5LaGEoON:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/util/docs.ts#L6)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

might as well just make this the default export
</blockquote></details>

Done.

---

*[pkg/ui/src/views/jobs/index.tsx, line 52 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy2uUOSHfWmQbqU1to:-KsyueW2adIC--CI9iXd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/views/jobs/index.tsx#L52)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Nit: I think `Latest` is more correct here.  They both work I think.
</blockquote></details>

Done.

---

*[pkg/ui/src/views/jobs/index.tsx, line 168 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy2DXR_sMrhp_vztnF:-KsysRYB0Xa2GTbpQxqj:b2jx0rc) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/views/jobs/index.tsx#L168)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

use <link> instead of <a>
</blockquote></details>

I'm afraid I don't understand. instead of?

---

*[pkg/ui/styl/base/typography.styl, line 67 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy3Ke9eN5ip7LsmcZV:-KsysUXyboR7iFf8EjYE:bixa038) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/styl/base/typography.styl#L67)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why are you changing fonts?
</blockquote></details>

When displaying code elsewhere, we use `Inconsolata-Regular` instead of whatever the browser chooses for `monospace`. This style simply wasn't applied to <code> elements. Just keeping things consistent.

---

*[pkg/ui/styl/layout/layout.styl, line 60 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy3SK-Jh7OcMffBkEA:-KsysdtVLLcHi7JrumCd:bgc2iqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/styl/layout/layout.styl#L60)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

We use too many px measurements.  Ugh.  Not that you should change this, but we should move to relative sizes soon.
</blockquote></details>

Yup, agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-:-KsywTe-2AQumGAhzQbU:b-w30yuf)*

**Comment by benesch** [comment]
Here's the new nodes overview page @BramGruneir:



Previously, both tables called the rightmost column "Downtime" and didn't include the word "ago" in the rows beneath.

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/views/jobs/index.tsx, line 168 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy2DXR_sMrhp_vztnF:-Ksz0eJp0vD5Ootnm7df:b-8wgbvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/views/jobs/index.tsx#L168)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I'm afraid I don't understand. instead of?
</blockquote></details>

@mrtracy, easy enough. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-:-Ksz0K9QHlEhXnobItxt:bkj2sev)*

**Comment by BramGruneir** [comment]
:lgtm: Only one nit.

---

Reviewed 1 of 7 files at r5, 1 of 1 files at r6, 4 of 6 files at r8, 1 of 1 files at r9.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/views/jobs/index.tsx, line 168 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy2DXR_sMrhp_vztnF:-Ksz-j8AHuEdPiF9xtx6:b-ekejk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/views/jobs/index.tsx#L168)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I'm afraid I don't understand. instead of?
</blockquote></details>

I wonder what happen, I wrote this out correctly. 
Use `Link` instead of `a`.   And I think we have a style to go with the link already, so you don't need to make one.

---

*[pkg/ui/styl/layout/layout.styl, line 60 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy3SK-Jh7OcMffBkEA:-Ksz0bgmt06LpFItSzjG:bifgfv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/styl/layout/layout.styl#L60)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yup, agreed.
</blockquote></details>

Really?  I thought the push was to move to relative measurements.  Reactive design and all.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-:-Ksz12Dl4wLUB5EiFHGn:byhaws4)*

**Comment by BramGruneir** [comment]
Reviewed 1 of 6 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/views/jobs/index.tsx, line 168 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy2DXR_sMrhp_vztnF:-Ksz1rwEZNd13d-DO1Cq:b-maugau) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/views/jobs/index.tsx#L168)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I wonder what happen, I wrote this out correctly. 
Use `Link` instead of `a`.   And I think we have a style to go with the link already, so you don't need to make one.
</blockquote></details>

I thought `<Link>` was just for internal links?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/views/jobs/index.tsx, line 168 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy2DXR_sMrhp_vztnF:-Ksz1xB6PnWOa1jwoHMV:bvz01ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/views/jobs/index.tsx#L168)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I thought `<Link>` was just for internal links?
</blockquote></details>

Correct, Link is only needed for internal links because it interacts with the router.  External links can just be normal anchors.

---

*[pkg/ui/styl/layout/layout.styl, line 60 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy3SK-Jh7OcMffBkEA:-Ksz1hFmSqk7zLaB8NgP:b6c5xpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/styl/layout/layout.styl#L60)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Really?  I thought the push was to move to relative measurements.  Reactive design and all.  
</blockquote></details>

That was the push in 2010, when browsers couldn't easily just zoom in.  Now it's a cargo culted idea, and I was part of that cult when we started building the UI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-:-Ksz1bxDCTvDcRbGRIO5:bnfp4nl)*

**Comment by BramGruneir** [comment]
Reviewed 1 of 7 files at r10, 1 of 1 files at r11, 6 of 6 files at r13.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ui/src/views/jobs/index.tsx, line 168 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137#-Ksy2DXR_sMrhp_vztnF:-Ksz3a63rJhyCYznIWTD:b80ek3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcf338389ee966f63e48ec1a240ffc9c0c13e207/pkg/ui/src/views/jobs/index.tsx#L168)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Correct, Link is only needed for internal links because it interacts with the router.  External links can just be normal anchors.
</blockquote></details>

Ah, well there we go.  All good then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18137)*

**Comment by benesch** [comment]
Thanks for the reviews! Merging on green.

**Pull request merged**
