### PR TITLE
sqlstats: record idle latency for statements

### PR DESCRIPTION
**Pull request by matthewtodd**
Part of https://github.com/cockroachdb/cockroach/issues/86667

In an attempt to identify application callsites holding transactions open while doing adjacent work, we measure a per-statement fingerprint "idle latency" and surface it in the sqlstats tables.

Developers may then search for statements with higher-than-usual idle latencies to find slow spots in their applications.

Release note (sql change): A new NumericStat, `idleLat`, was introduced to the statistics column of `crdb_internal.statement_statistics`, reporting the time spent waiting for the client to send the statement while holding a transaction open. Developers may use this stat to identify opportunities for restructuring their apps (perhaps moving unrelated work out of the transaction or splitting it into smaller transactions) to reduce contention.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
the approach looks good to me! i had a few nits, and also i think we should expose this in the transaction stats in the DB internals as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-:-NFsrMib-l-nCwTpUTci:b-awetl7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @matthewtodd)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFsg_dh4nkSalibYlek):*
nit: it should be `Release note (sql change)` and include something about how a user can access this new data
___
*[`pkg/roachpb/app_stats.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFsqc_i2j_X0sQmxJSy:-NFsqc_i2j_X0sQmxJSz:b9xmvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/roachpb/app_stats.go#L122)):*
> ```Go
> 
> // Add combines other into TransactionStatistics.
> func (t *TransactionStatistics) Add(other *TransactionStatistics) {
> ```

shouldn't this new metric be in TransactionStatistics instead of (or maybe in addition to) StatementStatistics?
___
*[`pkg/roachpb/app_stats.proto` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFsomIA0TQImQ6w-oST:-NFsomIA0TQImQ6w-oSU:bgq8e5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/roachpb/app_stats.proto#L65)):*
> ```protobuf
> 
>   // ClientLat is the time spent waiting for the client to send the statement.
>   optional NumericStat client_lat = 28 [(gogoproto.nullable) = false];
> ```

nit: i think "client latency" might be a bit confusing to understand. to me, it sounds like "total latency as experienced by the client."

what about a name like "idle latency" or "statement wait latency"

also, here and in the release note, do we need some clarification that this really is only meaningful for explicit transactions?
___
*[`pkg/sql/executor_statement_metrics.go` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFsqt6g4024WqV5V8YZ:-NFsqt6g4024WqV5V8Y_:b-puyw3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/sql/executor_statement_metrics.go#L127)):*
> ```Go
> 
> 	// Collect the statistics.
> 	clientLatRaw := phaseTimes.GetClientLatency(ex.statsCollector.PreviousPhaseTimes())
> ```

this step will compute the "client latency" for the current statement. i couldn't find the place where we compute the running total and show the total "client latency" for the transaction. is that what the frontend `aggregateNumericStats` function does?
___
*[`pkg/sql/sessionphase/session_phase.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFspH7h72mIpB_UgYvD:-NFspH7h72mIpB_UgYvE:b-hgzuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/sql/sessionphase/session_phase.go#L215)):*
> ```Go
> 
> // GetClientLatency deduces the rough amount of time spent waiting
> // for the client while the transaction is open.
> ```

nit: can the comment specify what the behavior is for implicit transactions? it should just return 0 right?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @matthewtodd)

___
*[`pkg/sql/sessionphase/session_phase.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFt509o20x5sP41NQUt:-NFt509o20x5sP41NQUu:bnsl8vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/sql/sessionphase/session_phase.go#L226)):*
> ```Go
> 	}
> 
> 	// In general, we have been waiting for the client since the end
> ```

I'm curious how accurate will this be if the previous statement returned a lot of data (i.e. the query resulted in millions of rows that were communicated to the client)?

**Review by matthewtodd — COMMENTED** [review]
Thanks, Rafi! Agreed re: transaction stats. I'll be adding those in a second PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-:-NFsuxve6iXy9WsC3NLb:be02uec)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @rafiss)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFsg_dh4nkSalibYlek):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: it should be `Release note (sql change)` and include something about how a user can access this new data
</blockquote></details>

Oops, thanks, I forgot `crdb_internal.statement_statistics` was one of [the documented ones](https://www.cockroachlabs.com/docs/stable/crdb-internal.html#statement_statistics).
___
*[`pkg/roachpb/app_stats.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFsqc_i2j_X0sQmxJSy:-NFsu8y0Cx6IZjsMDngG:b-jbek32) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/roachpb/app_stats.go#L122)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

shouldn't this new metric be in TransactionStatistics instead of (or maybe in addition to) StatementStatistics?
</blockquote></details>

It will be, coming in a second PR. Per @bobvawter, the per-statement timings were the most interesting for his approach.
___
*[`pkg/roachpb/app_stats.proto` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFsomIA0TQImQ6w-oST:-NFsuQt-43fNNMVl1TXs:bab858t) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/roachpb/app_stats.proto#L65)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think "client latency" might be a bit confusing to understand. to me, it sounds like "total latency as experienced by the client."

what about a name like "idle latency" or "statement wait latency"

also, here and in the release note, do we need some clarification that this really is only meaningful for explicit transactions?
</blockquote></details>

That's good, I do like "idle latency" better. And will clarify the explicit transaction bit.
___
*[`pkg/sql/executor_statement_metrics.go` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFsqt6g4024WqV5V8YZ:-NFsugzZ3DPIu3oIwiVY:b-msldg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/sql/executor_statement_metrics.go#L127)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this step will compute the "client latency" for the current statement. i couldn't find the place where we compute the running total and show the total "client latency" for the transaction. is that what the frontend `aggregateNumericStats` function does?
</blockquote></details>

The transaction-level aggregation will come in a second PR.
___
*[`pkg/sql/sessionphase/session_phase.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFspH7h72mIpB_UgYvD:-NFsuqvoEVnDPFEVtfJx:b-c68nqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/sql/sessionphase/session_phase.go#L215)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can the comment specify what the behavior is for implicit transactions? it should just return 0 right?
</blockquote></details>

Good idea, will change.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @matthewtodd, and @rafiss)

___
*[`pkg/sql/sessionphase/session_phase.go` line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFtsABhEKUu6lKhY34V:-NFtsABhEKUu6lKhY34W:biiay37) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f5cd7d951637a66f0b5a9397e3c41a9d11fa5ff/pkg/sql/sessionphase/session_phase.go#L228)):*
> ```Go
> 	// In general, we have been waiting for the client since the end
> 	// of the previous execution.
> 	waitingSince := previous.times[PlannerEndExecStmt]
> ```

Is the IdleLatency alway the time before the statement? If so how does it track the latency between the last statement and the commit?

**Comment by j82w** [comment]
*[`pkg/sql/sqlstats/sslocal/sql_stats_test.go` line 1218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFtsnTbDpWJ52OP8lp8:-NFtsnTbDpWJ52OP8lp9:b-o4arep) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f5cd7d951637a66f0b5a9397e3c41a9d11fa5ff/pkg/sql/sqlstats/sslocal/sql_stats_test.go#L1218)):*
> ```Go
> 		},
> 		{
> 			name: "multiple transactions",
> ```

How about adding a test scenario with 'select pg_sleep(1)' to verify it doesn't include the execution time of the previous statement?

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @rafiss, and @yuzefovich)

___
*[`pkg/sql/sessionphase/session_phase.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFt509o20x5sP41NQUt:-NFt6Xnn7xnoYF3fkYhM:b-dq8vqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/sql/sessionphase/session_phase.go#L226)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm curious how accurate will this be if the previous statement returned a lot of data (i.e. the query resulted in millions of rows that were communicated to the client)?
</blockquote></details>

That's a good question! Let me look back at `SessionQueryServiced` to see (a) if it might give us better accuracy and (b) if it's available when we need it.

I had also spent some time looking into [Jordan's suggestion](https://github.com/cockroachdb/cockroach/issues/86667#issuecomment-1224402371) of measuring the wait time for pgwire messages, but the mapping from those up to actual SQL executions felt hard to get (and keep?) right. That may be worth revisiting if we're not able to get satisfying accuracy this way.

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @j82w, @rafiss, and @yuzefovich)

___
*[`pkg/sql/sessionphase/session_phase.go` line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFtsABhEKUu6lKhY34V:-NFtuq2mDqfaxrQvTAkC:b-ujc2q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f5cd7d951637a66f0b5a9397e3c41a9d11fa5ff/pkg/sql/sessionphase/session_phase.go#L228)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Is the IdleLatency alway the time before the statement? If so how does it track the latency between the last statement and the commit?
</blockquote></details>

Yes, it is. We don't yet track the latency between the last statement and the commit; that'll be for the PR that introduces the transaction-level stat.
___
*[`pkg/sql/sqlstats/sslocal/sql_stats_test.go` line 1218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFtsnTbDpWJ52OP8lp8:-NFtvBksDMRLNCHa4U91:b-6zujaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f5cd7d951637a66f0b5a9397e3c41a9d11fa5ff/pkg/sql/sqlstats/sslocal/sql_stats_test.go#L1218)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

How about adding a test scenario with 'select pg_sleep(1)' to verify it doesn't include the execution time of the previous statement?
</blockquote></details>

Good idea, will do.

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @j82w, @rafiss, and @yuzefovich)

___
*[`pkg/sql/sessionphase/session_phase.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFt509o20x5sP41NQUt:-NGI66tt9skSpdW56Rg-:bjp0y4) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/sql/sessionphase/session_phase.go#L226)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

That's a good question! Let me look back at `SessionQueryServiced` to see (a) if it might give us better accuracy and (b) if it's available when we need it.

I had also spent some time looking into [Jordan's suggestion](https://github.com/cockroachdb/cockroach/issues/86667#issuecomment-1224402371) of measuring the wait time for pgwire messages, but the mapping from those up to actual SQL executions felt hard to get (and keep?) right. That may be worth revisiting if we're not able to get satisfying accuracy this way.
</blockquote></details>

`SessionQueryServiced` does happen slightly later, so I've switched to using it.

And I've gone down a bit of a rabbit hole looking for how this'll behave in the context of large result sets:

As far as I can tell, `SessionQueryServiced` won't be set until all of the results have been pushed down into to the network stack, at which point the "idle" clock will start ticking for the next query. (@yuzefovich, could you check me here?)

If that assessment is correct, then this idle clock will effectively penalize the client (i.e. mark its next query as having a large idle latency) for the essential overhead in handling these large responses.

...and I think we're okay with that? Since the intent of this feature is to identify unnecessarily long-running transactions that could be candidates for breaking apart, I think we do want these large responses to stand out.

---

I did find the [results_buffer_size](https://github.com/cockroachdb/cockroach/blob/0becdf9b7a46369d077877e9ee850698fedf7d70/pkg/sql/vars.go#L1068-L1074) session var, hoping to use it to somehow expose some synchronous interaction with the client (wondering if it would behave like the [defaultRowFetchSize](https://jdbc.postgresql.org/documentation/use/) connection parameter to the pg jdbc driver), but it only appears to affect flushing frequency.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @j82w, and @yuzefovich)

___
*[`pkg/sql/sessionphase/session_phase.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFt509o20x5sP41NQUt:-NGIDK9p7rxRxDqKFqW3:bw0o17n) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/sql/sessionphase/session_phase.go#L226)):*
> If that assessment is correct, then this idle clock will effectively penalize the client (i.e. mark its next query as having a large idle latency) for the essential overhead in handling these large responses.
> 
> ...and I think we're okay with that? Since the intent of this feature is to identify unnecessarily long-running transactions that could be candidates for breaking apart, I think we do want these large responses to stand out.

I also agree that this behavior sounds good and it's useful to track as part of this metric

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @j82w, @matthewtodd, and @rafiss)

___
*[`pkg/sql/sessionphase/session_phase.go` line 226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFt509o20x5sP41NQUt:-NGIQhouD_3CkrMc4LjL:bpalkr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a448dcdab2388e6bb4b0ca22ff3d51c5a372f2/pkg/sql/sessionphase/session_phase.go#L226)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> If that assessment is correct, then this idle clock will effectively penalize the client (i.e. mark its next query as having a large idle latency) for the essential overhead in handling these large responses.
> 
> ...and I think we're okay with that? Since the intent of this feature is to identify unnecessarily long-running transactions that could be candidates for breaking apart, I think we do want these large responses to stand out.

I also agree that this behavior sounds good and it's useful to track as part of this metric
</blockquote></details>

Sounds good to me too, thanks for checking!

**Comment by matthewtodd** [comment]
Thanks, everyone! The failing test here is #91420, to be fixed by #91421. I'll rebase and ping you all for the :lgtm: when that lands.

**Comment by jordanlewis** [comment]
> If that assessment is correct, then this idle clock will effectively penalize the client (i.e. mark its next query as having a large idle latency) for the essential overhead in handling these large responses.

I'm not sure that this is a good idea. I think it could lead to confusing outcomes - people look at statements in isolation, and they might see a large idle team and won't know what to make of it.

A related question - are we measuring the delay in between two statements within a transaction with this PR? And, how would that delay show up in the UI?

I think it might be good to do some basic testing of different scenarios so we can figure out how this stat maps to common user behaviors.

cc @kevin-v-ngo for any thoughts as well.

**Comment by jordanlewis** [comment]
(My comment isn't blocking for merging the PR)

**Comment by bobvawter** [comment]
> A related question - are we measuring the delay in between two statements within a transaction with this PR? And, how would that delay show up in the UI?

The questions that I want to answer for customers are:
1) Are transaction times long because there's an excessive amount of "think time" in the workload?
1) Which statement(s) in the transaction have the biggest think-time gaps?
1) If possible, identify cases where draining a large result set back to the client takes a non-trivial amount of time.

The goal of the above is to let us make specific recommendations to customers about where the biggest wins in breaking up transactions would be or where a workload isn't keeping up with CRDB.

**Comment by rafiss** [comment]
> are we measuring the delay in between two statements within a transaction with this PR? 

According to https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFsqt6g4024WqV5V8YZ:-NFsugzZ3DPIu3oIwiVY:b-msldg1 and https://reviewable.io/reviews/cockroachdb/cockroach/91098#-NFtsABhEKUu6lKhY34V:-NFtuq2mDqfaxrQvTAkC:b-ujc2q9, that is coming in a future commit

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91098#-:-NGO5Km--6ZaVByhz0YA:b-7nbn20)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter, @j82w, and @matthewtodd)

**Comment by rafiss** [comment]
> accurate when running queries in `psql` but zero-ish in `cockroach sql`

I would guess that this is because `psql` _only_ executes the query you type in, where as `cockroach sql` runs additional things such as `SHOW DATABASE`, and `SHOW LAST QUERY STATISTICS`.

**Comment by matthewtodd** [comment]
> I'm going to wire in a `pgx` variant of the tests to investigate.

I did do this locally, and all the tests passed, as expected. So it's not `pgx`.

>> accurate when running queries in psql but zero-ish in cockroach sql
>
> I would guess that this is because psql only executes the query you type in, where as cockroach sql runs additional things such as SHOW DATABASE, and SHOW LAST QUERY STATISTICS.

Thanks, @rafiss, that was it! :tada:

Poking around, I can now get accurate idle latencies from `cockroach sql` sessions by running `\set check_syntax = false` in those sessions. I think we're good to merge here!

bors r+

**Pull request merged**
