### PR TITLE
settings: Add syntax for cluster settings

### PR DESCRIPTION
**Pull request by ajstorm**
Before this commit, there was no syntax to SET or SHOW cluster settings which
exist for a given tenant. This commit adds the following syntax:

* ALTER TENANT <id> SET CLUSTER SETTING <setting> = <value>
* ALTER TENANT ALL SET CLUSTER SETTING <setting> = <value>
* ALTER TENANT <id> RESET CLUSTER SETTING <setting>
* ALTER TENANT ALL RESET CLUSTER SETTING <setting>
* SHOW CLUSTER SETTING <setting> FOR TENANT <id>
* SHOW [ALL] CLUSTER SETTINGS FOR TENANT <id>

Note that the syntax is added but the underlying commands are currently
unimplemented. The implementation of these commands will come with a subsequent
commit.

Release note (sql change): Added syntax for modifying cluster settings at the
tenant level.

Informs: #73857.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
just had nits and needs tests!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-:-MwbVLYk3Z9omNUWgOF_:b-umd5wy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @dt, and @RaduBerinde)

___
*[pkg/sql/set_cluster_setting.go, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-MwbTyzsCBkDZ4o1cJey:-MwbTyzsCBkDZ4o1cJez:bndvoxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb5bc5b32f0488865aab37c3548e0e10399bdc8/pkg/sql/set_cluster_setting.go#L178)):*
> ```Go
> 
> 	if n.tenantID.IsSet() || n.tenantAll {
> 		return errors.UnimplementedError(
> ```

nit: use `unimplemented.NewWithIssue`
___
*[pkg/sql/show_cluster_setting.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-MwbUEkN63OSIPccy-Gl:-MwbUEkN63OSIPccy-Gm:bndvoxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb5bc5b32f0488865aab37c3548e0e10399bdc8/pkg/sql/show_cluster_setting.go#L122)):*
> ```Go
> ) (planNode, error) {
> 	if n.TenantID.IsSet() {
> 		return nil, errors.UnimplementedError(
> ```

nit: use `unimplemented.NewWithIssue`
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-MwbUI075cba0lQyAYY_:-MwbUI075cba0lQyAYYa:bndvoxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb5bc5b32f0488865aab37c3548e0e10399bdc8/pkg/sql/delegate/show_all_cluster_settings.go#L26)):*
> ```Go
> ) (tree.Statement, error) {
> 	if stmt.TenantID.IsSet() {
> 		return nil, errors.UnimplementedError(
> ```

nit: use `unimplemented.NewWithIssue`
___
*[pkg/sql/sem/tree/set.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-MwbUnL97t4i1INP4gtj:-MwbUnL97t4i1INP4gtk:by62cg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb5bc5b32f0488865aab37c3548e0e10399bdc8/pkg/sql/sem/tree/set.go#L81)):*
> ```Go
> 
> // Format implements the NodeFormatter interface.
> func (node *SetClusterSetting) Format(ctx *FmtCtx) {
> ```

we should test this formatting logic as well. could you add test cases to `pkg/sql/parser/testdata/show` and `pkg/sql/parser/testdata/set` (or a new test file if you like)

**Review by ajstorm — COMMENTED** [review]
Thanks Rafi.

I've addressed your comments, but you might want to have another full look.  I reworked things considerably due to @raduberinde's suggestion that we create a new tree node for alter tenant.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-:-Mwgxe-V6u11EQJJSFEO:b-d7bq7v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @RaduBerinde, and @rafiss)

___
*[pkg/sql/sem/tree/set.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-MwbUnL97t4i1INP4gtj:-MwgxanY0oPPqrNc0U12:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb5bc5b32f0488865aab37c3548e0e10399bdc8/pkg/sql/sem/tree/set.go#L81)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we should test this formatting logic as well. could you add test cases to `pkg/sql/parser/testdata/show` and `pkg/sql/parser/testdata/set` (or a new test file if you like)
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
looks good overall! just one comment on the formatting

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-:-Mwn4EZ53uX4OxPO3DlT:b-dlhh9c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @dt, @RaduBerinde, and @rafiss)

___
*[pkg/sql/sem/tree/alter_tenant.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-Mwn2y8W28ra_wRRkzcz:-Mwn2y8W28ra_wRRkzd-:b-frtdvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d03126077801d385de0ef22f3c1f33a246559a/pkg/sql/sem/tree/alter_tenant.go#L33)):*
> ```Go
> 		ctx.WriteString("ALTER TENANT ALL ")
> 	} else if node.TenantID.IsSet() {
> 		s := fmt.Sprintf("ALTER TENANT %d ", node.TenantID.ToUint64())
> ```

i don't think we should make the TenantID skip the FmtCtx flags (unless there's a specific reason?)

so we'd want:
```
ctx.WriteString("ALTER TENANT ")
ctx.FormatNode(node.TenantID)
ctx.WriteString(" ")
```

(same goes for SHOW formatting)
___
*[pkg/sql/parser/testdata/alter_tenant, line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-Mwn2asD7UCm56Bc5Jy3:-Mwn2asG37XghyDzM4ju:bhecnf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d03126077801d385de0ef22f3c1f33a246559a/pkg/sql/parser/testdata/alter_tenant#L6)):*
> ```
> ALTER TENANT 1 SET CLUSTER SETTING a = 3
> ALTER TENANT 1 SET CLUSTER SETTING a = (3) -- fully parenthesized
> ALTER TENANT 1 SET CLUSTER SETTING a = _ -- literals removed
> ```

i would expect the `1` to be removed in the "literals removed" step.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @dt, @RaduBerinde, and @rafiss)

___
*[pkg/sql/sem/tree/alter_tenant.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-Mwn2y8W28ra_wRRkzcz:-Mx029fi3G5Wm3ex4dXh:bc6mqbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d03126077801d385de0ef22f3c1f33a246559a/pkg/sql/sem/tree/alter_tenant.go#L33)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think we should make the TenantID skip the FmtCtx flags (unless there's a specific reason?)

so we'd want:
```
ctx.WriteString("ALTER TENANT ")
ctx.FormatNode(node.TenantID)
ctx.WriteString(" ")
```

(same goes for SHOW formatting)
</blockquote></details>

I was thinking that the tenant ID would never contain PII, but could be useful in debugging in all cases?  Is this the proper justification for having it skip the flags?

**Comment by rafiss** [comment]
> I was thinking that the tenant ID would never contain PII, but could be useful in debugging in all cases? Is this the proper justification for having it skip the flags?

It's a good intuition, but our formatting logic has two separate notions:
```
	// FmtHideConstants instructs the pretty-printer to produce a
	// representation that does not disclose query-specific data. It
	// also shorten long lists in tuples, VALUES and array expressions.
	FmtHideConstants

	// FmtAnonymize instructs the pretty-printer to remove
	// any name but function names.
	FmtAnonymize
```

`FmtHideConstants` only hides literal constants, but not identifiers. It is used, for example, (1) in the DB console statements page, to group statements together to be able to view query stats and (2) by the optimizer to cache query plans. (Neither (1) nor (2) seem that important for `ALTER TENANT ... SET`, but it's worth using the same formatting principles across our entire SQL syntax.)

`FmtAnonymize` is used to hide PII like names and identifiers, but not literal constants. For logging and telemetry, I believe `FmtAnonymize` **and** `FmtHideConstants` are both used.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @RaduBerinde, and @rafiss)

___
*[pkg/sql/sem/tree/alter_tenant.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-Mwn2y8W28ra_wRRkzcz:-Mx0TEwQ-dmzWiZmxGsf:boicqze) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d03126077801d385de0ef22f3c1f33a246559a/pkg/sql/sem/tree/alter_tenant.go#L33)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I was thinking that the tenant ID would never contain PII, but could be useful in debugging in all cases?  Is this the proper justification for having it skip the flags?
</blockquote></details>

As mentioned on Slack, I'm going to leave this as-is for now, pending the broader investigation as to what to do here.
___
*[pkg/sql/parser/testdata/alter_tenant, line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-Mwn2asD7UCm56Bc5Jy3:-Mx0TWoTArofsTPfNtyx:bnqe4pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d03126077801d385de0ef22f3c1f33a246559a/pkg/sql/parser/testdata/alter_tenant#L6)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i would expect the `1` to be removed in the "literals removed" step.
</blockquote></details>

Does this key off of the Format function?  If so I think we're stuck with showing this literal pending the investigation mentioned above.

**Review by ajstorm — COMMENTED** [review]
I'm going to hold off on that change to the TenantID formatting.  This should be RFAL now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-:-Mx0Trb01GQanj4_vvxd:b-ue9fty)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @RaduBerinde, and @rafiss)

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-:-Mx0bBm5-aPFXMsi73rB:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @dt, @RaduBerinde, and @rafiss)

___
*[pkg/sql/parser/testdata/alter_tenant, line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-Mwn2asD7UCm56Bc5Jy3:-Mx0b1Mi0pEGNsjm4WGv:bizoheh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d03126077801d385de0ef22f3c1f33a246559a/pkg/sql/parser/testdata/alter_tenant#L6)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Does this key off of the Format function?  If so I think we're stuck with showing this literal pending the investigation mentioned above.
</blockquote></details>

yeah, this is the result of formatting with `FmtHideConstants`. we can address it during the stability period

**Review by RaduBerinde — APPROVED** [review]
:lgtm: modulo one comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-:-Mx0tv4S6jpY8IaBxUJ0:bghmtuy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @dt, and @rafiss)

___
*[pkg/sql/alter_tenant.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-Mx0tZ3WDO4C7Zz2iAkJ:-Mx0tZ3WDO4C7Zz2iAkK:b-xlwvmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e6c2cfd5d882f8ecb3416bd40015eea0c61a67a/pkg/sql/alter_tenant.go#L60)):*
> ```Go
> 	}
> 
> 	if setting.Class() == settings.SystemOnly && !p.execCfg.Codec.ForSystemTenant() {
> ```

Here we need to error out if it is a SystemOnly setting. For all others, we need to check `ForSystemTenant()` and only allow that (I think that should be the first thing to check - this is a "system/operator only" statement).

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @ajwerner, @dt, @RaduBerinde, and @rafiss)

___
*[pkg/sql/alter_tenant.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-Mx0tZ3WDO4C7Zz2iAkJ:-Mx1P8tp-z5ZhXoADyOc:bcx5s8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e6c2cfd5d882f8ecb3416bd40015eea0c61a67a/pkg/sql/alter_tenant.go#L60)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Here we need to error out if it is a SystemOnly setting. For all others, we need to check `ForSystemTenant()` and only allow that (I think that should be the first thing to check - this is a "system/operator only" statement).
</blockquote></details>

@raduberinde I don't think I fully appreciated how we should error out here from a first read of the RFC.  I took another crack at this logic based on your comments and I _think_ I've got it right now.  PTAL (assuming you're still checking email) and let me know what you think.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @ajwerner, @dt, @RaduBerinde, and @rafiss)

___
*[pkg/sql/alter_tenant.go, line 67 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-Mx6-wuB6dxRG1SSJ5lv:-Mx6-wuB6dxRG1SSJ5lw:b-qgv530) ([raw file](https://github.com/cockroachdb/cockroach/blob/382c4da8329470014739d7cadcefdb5449846674/pkg/sql/alter_tenant.go#L67)):*
> ```Go
> 			"%s is a system-only setting and must be set using SET CLUSTER SETTING", name)
> 	}
> 	if !p.execCfg.Codec.ForSystemTenant() && setting.Class() != settings.TenantWritable {
> ```

This should just be `if !ForSystemTenant() and I'd move it to be the first check.

ALTER TENANT should only be runnable by the system tenant. Non-system tenants can only use `SET CLUSTER SETTING` to change their settings. `ALTER TENANT` is only about operator-set overrides. It's very similar to calling `crdb_internal.create_tenant()` from the standpoint of who can run it.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @ajwerner, @dt, @RaduBerinde, and @rafiss)

___
*[pkg/sql/alter_tenant.go, line 67 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-Mx6-wuB6dxRG1SSJ5lv:-Mx7GJ0_1kAWuWw4tep_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/382c4da8329470014739d7cadcefdb5449846674/pkg/sql/alter_tenant.go#L67)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should just be `if !ForSystemTenant() and I'd move it to be the first check.

ALTER TENANT should only be runnable by the system tenant. Non-system tenants can only use `SET CLUSTER SETTING` to change their settings. `ALTER TENANT` is only about operator-set overrides. It's very similar to calling `crdb_internal.create_tenant()` from the standpoint of who can run it.
</blockquote></details>

Done.

**Comment by ajstorm** [comment]
TFTR!

bors r=raduberinde,rafiss

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76929#-:-MxD88Bv-VwryNfNs1ww:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
