### PR TITLE
vecindex: support deleting vectors from C-SPANN index

### PR DESCRIPTION
**Pull request by andy-kimball**
Add Delete method to the vector index, which attempts to remove a vector from the index, given its value and primary key. Delete may not be able to locate the vector in the index, leaving a "dangling vector" reference which other methods need to take care not to ignore.

Epic: CRDB-42943

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135230#-:-OBj1T_6ATT-AFpND2Is:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @mw5h)

___
*[`pkg/sql/vecindex/vector_index.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135230#-OBitSv0Du3dDlI_t30q:-OBitSv0Du3dDlI_t30r:bx7ht5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec4c4ee048ffb4f943549eb492692d284eb516c/pkg/sql/vecindex/vector_index.go#L244)):*
> ```Go
> 		defer searchCtx.Workspace.FreeVector(tempRandomized)
> 		vi.quantizer.RandomizeVector(ctx, vector, tempRandomized, false /* invert */)
> 		searchCtx.Randomized = tempRandomized
> ```

[nit] Is it possible to move some of this logic above the loop?
___
*[`pkg/sql/vecindex/vector_index.go` line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135230#-OBiuATW8YU0mAgIqH2u:-OBiuATW8YU0mAgIqH2v:bspraag) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec4c4ee048ffb4f943549eb492692d284eb516c/pkg/sql/vecindex/vector_index.go#L255)):*
> ```Go
> 			// Retry search with significantly higher beam size.
> 			if baseBeamSize == vi.options.BaseBeamSize {
> 				baseBeamSize *= 8
> ```

If `vi.options.BaseBeamSize` was somehow zero, we'd have an infinite loop, right?
___
*[`pkg/sql/vecindex/vecstore/search_set.go` line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135230#-OBivQ3_1zqQf_mKVbBE:-OBivQ3aBiCsSowNYcN7:bn2nnvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec4c4ee048ffb4f943549eb492692d284eb516c/pkg/sql/vecindex/vecstore/search_set.go#L174)):*
> ```Go
> 	// MatchKey, if non-nil, filters out all search candidates that do not have
> 	// a matching primary key.
> 	MatchKey PrimaryKey
> ```

Think we could make this more general down the line? For example, simple filters on the primary key columns or stored columns.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135230)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/vecindex/vector_index.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135230#-OBitSv0Du3dDlI_t30q:-OBjf3FK2BXcLDeH9guD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec4c4ee048ffb4f943549eb492692d284eb516c/pkg/sql/vecindex/vector_index.go#L244)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Is it possible to move some of this logic above the loop?
</blockquote></details>

Done.
___
*[`pkg/sql/vecindex/vector_index.go` line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135230#-OBiuATW8YU0mAgIqH2u:-OBjf5Tg95UseRu6BSxO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec4c4ee048ffb4f943549eb492692d284eb516c/pkg/sql/vecindex/vector_index.go#L255)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

If `vi.options.BaseBeamSize` was somehow zero, we'd have an infinite loop, right?
</blockquote></details>

Done.
___
*[`pkg/sql/vecindex/vecstore/search_set.go` line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135230#-OBivQ3_1zqQf_mKVbBE:-OBjf6ze5myJ3AOKiAYx:b-12jk2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ec4c4ee048ffb4f943549eb492692d284eb516c/pkg/sql/vecindex/vecstore/search_set.go#L174)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Think we could make this more general down the line? For example, simple filters on the primary key columns or stored columns.
</blockquote></details>

In other prototypes, I've had other kinds of filters here. Never anything so general, but I have found it useful to have the flexibility.

**Comment by andy-kimball** [comment]
bors r=drewkimball

**Comment by andy-kimball** [comment]
bors r=drewkimball

**Pull request merged**
