### PR TITLE
storage/engine: support StorageConfig.MustExist for pebble

### PR DESCRIPTION
**Pull request by hueypark**
Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: modulo a small comment on the test.

Thanks for the contribution!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42346#-:-LtLXm-t82bgFmGI6l3B:b-k480z0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @hueypark)

___
*[pkg/storage/engine/engine_test.go, line 495 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42346#-LtLXPTn5xgeGBTL22_Y:-LtLXPTn5xgeGBTL22_Z:b4fxbwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c9ff72639c1c61bd6a2f356256dd96671ddb441/pkg/storage/engine/engine_test.go#L495)):*
> ```Go
> 
> 	test := func(engineType enginepb.EngineType) {
> 		tempDir, dirCleanupFn := testutils.TempDir(t)
> ```

Does this need to run on disk? I would think in-memory engines would be sufficient.

Would be good to use the `for _, engineImpl := range mvccEngineImpls {` pattern here if an in-memory engine is possible.
___
*[pkg/storage/engine/engine_test.go, line 505 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42346#-LtLXib51A48DxVeSdWf:-LtLXib51A48DxVeSdWg:bic6xuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c9ff72639c1c61bd6a2f356256dd96671ddb441/pkg/storage/engine/engine_test.go#L505)):*
> ```Go
> 			})
> 		if err == nil {
> 			t.Fatal("expected errors related to missing directory")
> ```

Nit: `s/errors/error/g`

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42346)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/engine/engine_test.go, line 495 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42346#-LtLXPTn5xgeGBTL22_Y:-LtPj4ce6EzbCFaByRBq:b-ks5rsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c9ff72639c1c61bd6a2f356256dd96671ddb441/pkg/storage/engine/engine_test.go#L495)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does this need to run on disk? I would think in-memory engines would be sufficient.

Would be good to use the `for _, engineImpl := range mvccEngineImpls {` pattern here if an in-memory engine is possible.
</blockquote></details>

Currently, `engineImpl` is not available because` StorageConfig` is not taken as an argument.
___
*[pkg/storage/engine/engine_test.go, line 505 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42346#-LtLXib51A48DxVeSdWf:-LtPgs_A6mHoaGfaz4cE:b-aceu90) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c9ff72639c1c61bd6a2f356256dd96671ddb441/pkg/storage/engine/engine_test.go#L505)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `s/errors/error/g`
</blockquote></details>

Done. And I fix the error check issue in the test.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42346)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @hueypark)

___
*[pkg/storage/engine/engine_test.go, line 495 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42346#-LtLXPTn5xgeGBTL22_Y:-LtQJIwCEAMvuzmkRn2A:bltxo4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c9ff72639c1c61bd6a2f356256dd96671ddb441/pkg/storage/engine/engine_test.go#L495)):*
<details><summary><i>Previously, hueypark (Jaewan Park) wrote…</i></summary><blockquote>

Currently, `engineImpl` is not available because` StorageConfig` is not taken as an argument.
</blockquote></details>

Ah, good point. 
___
*[pkg/storage/engine/engine_test.go, line 505 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42346#-LtLXib51A48DxVeSdWf:-LtQJMoR05G85mHv4B7v:bw9x0ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c9ff72639c1c61bd6a2f356256dd96671ddb441/pkg/storage/engine/engine_test.go#L505)):*
<details><summary><i>Previously, hueypark (Jaewan Park) wrote…</i></summary><blockquote>

Done. And I fix the error check issue in the test.
</blockquote></details>

Did you forget to push this change? The message still contains `errors`.

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42346)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @hueypark)

___
*[pkg/storage/engine/engine_test.go, line 505 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42346#-LtLXib51A48DxVeSdWf:-LtRajg8-qFHRb_AJo74:br95qwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c9ff72639c1c61bd6a2f356256dd96671ddb441/pkg/storage/engine/engine_test.go#L505)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Did you forget to push this change? The message still contains `errors`.
</blockquote></details>

Done. Thanks again.

**Review by petermattis — COMMENTED** [review]
Thanks for the contribution.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42346#-:-LteHiil-CfX2uRhk1gL:bkltj39)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
