### PR TITLE
roachtest: add hotspot load roachtest

### LINKED ISSUE #24341: roachtest: add a hotspot workload
#21357 added a mechanism to backpressure writes if splits are not able to keep up. As part of our push for improved testing infrastructure, we should perform testing that attempts to create large ranges by writing lots of data to a hotspot. We should verify that splits are able to keep up with the directed load. This also includes bursty workloads.

### PR DESCRIPTION
**Pull request by m-schneider**
Adding a test that runs a load that will force a range to grow very
fast. We then see if backpressure throttles further writes.

Closes #24341

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---

*[pkg/cmd/roachtest/hssplits.go, line 21 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOluaLADeIl3ry3rGe:-LAOluaLADeIl3ry3rGf:b2jryb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L21)):*
> ```Go
> func init() {
> 	// This test sets up a cluster and runs kv on it with high concurrency and a large block size
> 	// to force a large range. We then make sure that the largest range isn't larger than 196mb and
> ```

No need to explicitly write out the threshold we're testing for in this comment. We don't want it to rot.

---

*[pkg/cmd/roachtest/hssplits.go, line 28 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOmHByDh2ICRBF6CiZ:-LAOmHByDh2ICRBF6Ci_:bpz30mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L28)):*
> ```Go
> 		c.Start(ctx, c.All())
> 
> 		c.Run(ctx, c.Node(nodes), `./workload init kv --drop`)
> ```

Do we need the `--drop`?

---

*[pkg/cmd/roachtest/hssplits.go, line 34 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnxzgCEQkBM4Fwanj:-LAOnxzgCEQkBM4Fwank:b-zczzfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L34)):*
> ```Go
> 
> 		m.Go(func() error {
> 			t.Status("starting load generator")
> ```

`t.WorkerStatus(...`

---

*[pkg/cmd/roachtest/hssplits.go, line 41 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOmQJq1DRr--f0EKNh:-LAOmQJq1DRr--f0EKNi:bina1rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L41)):*
> ```Go
> 			}
> 			return c.RunL(ctx, quietL, c.Node(nodes), fmt.Sprintf(
> 				"./workload run kv --read-percent=0 --splits=0 --concurrency=%d --min-block-bytes=1024000 --duration %s --max-block-bytes=1024001 {pgurl:1} &",
> ```

Let's pull the block size into a constant as well so that it can be more easily parameterized later, if necessary.

`const blockSize = 2 << 20 // 1 MB`

---

*[pkg/cmd/roachtest/hssplits.go, line 41 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOmh0I6-X_0UCkW_xa:-LAOmh0I6-X_0UCkW_xb:bm74y91) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L41)):*
> ```Go
> 			}
> 			return c.RunL(ctx, quietL, c.Node(nodes), fmt.Sprintf(
> 				"./workload run kv --read-percent=0 --splits=0 --concurrency=%d --min-block-bytes=1024000 --duration %s --max-block-bytes=1024001 {pgurl:1} &",
> ```

Why send queries to only one node? Does `{pgurl:1-3}` work?

---

*[pkg/cmd/roachtest/hssplits.go, line 41 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOmqgEA8mbku7OYJ0F:-LAOmqgEA8mbku7OYJ0G:bfycetk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L41)):*
> ```Go
> 			}
> 			return c.RunL(ctx, quietL, c.Node(nodes), fmt.Sprintf(
> 				"./workload run kv --read-percent=0 --splits=0 --concurrency=%d --min-block-bytes=1024000 --duration %s --max-block-bytes=1024001 {pgurl:1} &",
> ```

Why run this process in the background?

---

*[pkg/cmd/roachtest/hssplits.go, line 45 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnnMR4ql856Ux2u5H:-LAOnnMR4ql856Ux2u5I:b-z4v9ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L45)):*
> ```Go
> 		})
> 
> 		m.Go(func() error {
> ```

`t.Status(` ...

---

*[pkg/cmd/roachtest/hssplits.go, line 62 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOn0fr32ToVDIPipsI:-LAOn0fr32ToVDIPipsJ:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L62)):*
> ```Go
> 			for tBegin := timeutil.Now(); timeutil.Since(tBegin) <= duration; {
> 				if err := db.QueryRow(
> 					`select max(bytes_per_replica->'PMax') from crdb_internal.kv_store_status;`,
> ```

Nice!

---

*[pkg/cmd/roachtest/hssplits.go, line 67 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOm4So-SzM1w7AtQgV:-LAOm4So-SzM1w7AtQgW:b-9rynb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L67)):*
> ```Go
> 				}
> 
> 				// 196mb in bytes
> ```

`const sizeLimit = 3 * (2 << 26) // 196 MB`

---

*[pkg/cmd/roachtest/hssplits.go, line 93 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnS517SJlZZF0oxNR:-LAOnS517SJlZZF0oxNS:b-b8ddi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L93)):*
> ```Go
> 
> 	tests.Add(testSpec{
> 		Name:  fmt.Sprintf("hssplits/duration=%d/nodes=%d", minutes, numNodes),
> ```

Are we abbreviating "hotspot" because this name grew too large? I think it's more valuable to spell it all out than to include the duration in the name.

---

*[pkg/cmd/roachtest/hssplits.go, line 98 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnIN29DWw9wegavv8:-LAOnIN29DWw9wegavv9:b-yyn2z3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L98)):*
> ```Go
> 			if local {
> 				fmt.Printf("running with duration=%s in local mode\n", minutes)
> 				concurrency = 10
> ```

We still fail this test in local mode without backpressure, right?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/roachtest/hssplits.go, line 93 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnS517SJlZZF0oxNR:-LAOqxsN5NmkAqcSfyxs:b-p5v8id) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L93)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we abbreviating "hotspot" because this name grew too large? I think it's more valuable to spell it all out than to include the duration in the name.
</blockquote></details>

:thumbsup: (in the filename too). 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-:-LAOrUIwBdHvscCoiOtO:bnfp4nl)*

**Comment by m-schneider** [comment]
Review status: 6 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/cmd/roachtest/hssplits.go, line 21 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOluaLADeIl3ry3rGe:-LAOo__91LPFKibYg1DW:b-4hvi0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L21)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No need to explicitly write out the threshold we're testing for in this comment. We don't want it to rot.
</blockquote></details>

Got it!

---

*[pkg/cmd/roachtest/hssplits.go, line 28 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOmHByDh2ICRBF6CiZ:-LAOogYc4YlQypagBpJf:bfbgrr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L28)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need the `--drop`?
</blockquote></details>

Probably not, though if something was a bit off in the setup, like a previous store wasn't destroyed correctly, it'll guarantee a new table.

---

*[pkg/cmd/roachtest/hssplits.go, line 34 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnxzgCEQkBM4Fwanj:-LAOpDBL230CLpruuV39:btu68gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`t.WorkerStatus(...`
</blockquote></details>

That adds pretty weird logging:

[   2] hotspotsplits/nodes=4: max range size 66 MiB (0s), starting load generator (1m58s)

Just printing it once at the top seems a lot cleaner.

---

*[pkg/cmd/roachtest/hssplits.go, line 41 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOmQJq1DRr--f0EKNh:-LAOpXKu9uGzHO89iDhN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's pull the block size into a constant as well so that it can be more easily parameterized later, if necessary.

`const blockSize = 2 << 20 // 1 MB`
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/hssplits.go, line 41 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOmqgEA8mbku7OYJ0F:-LAOpW7q06CfRTA73FZf:bfx84jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why run this process in the background?
</blockquote></details>

Copy, paste, fail.

---

*[pkg/cmd/roachtest/hssplits.go, line 41 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOmh0I6-X_0UCkW_xa:-LAOsIUjEeXOr1EIWhb-:b-vli7xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why send queries to only one node? Does `{pgurl:1-3}` work?
</blockquote></details>

Yep, changed.

---

*[pkg/cmd/roachtest/hssplits.go, line 45 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnnMR4ql856Ux2u5H:-LAOqWpw4iIgim8nz5bY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`t.Status(` ...
</blockquote></details>

Done.

---

*[pkg/cmd/roachtest/hssplits.go, line 67 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOm4So-SzM1w7AtQgV:-LAOpsgc3KCMATFYFydg:bjovaa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`const sizeLimit = 3 * (2 << 26) // 196 MB`
</blockquote></details>

That's 384mb, but changed.

---

*[pkg/cmd/roachtest/hssplits.go, line 93 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnS517SJlZZF0oxNR:-LAOptmDClG2h0IXyr91:b-v8isnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L93)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we abbreviating "hotspot" because this name grew too large? I think it's more valuable to spell it all out than to include the duration in the name.
</blockquote></details>

Yep it wasn't running on roachprod. Got rid of the duration.

---

*[pkg/cmd/roachtest/hssplits.go, line 98 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnIN29DWw9wegavv8:-LAOq8vm76f-BtwU6x9h:bmhjt9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L98)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We still fail this test in local mode without backpressure, right?
</blockquote></details>

Not with 10.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905)*

**Comment by nvanbenschoten** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/cmd/roachtest/hssplits.go, line 98 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnIN29DWw9wegavv8:-LAPWGia9akHOImEEBv3:b4lr61d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L98)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Not with 10.
</blockquote></details>

Even if we turn backpressure off?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905)*

**Comment by m-schneider** [comment]
*[pkg/cmd/roachtest/hssplits.go, line 98 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-LAOnIN29DWw9wegavv8:-LATT-myCEm7vFClULSu:bu70ujd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8ff9ee668c8892c4eaebaf19cc5e7fe61a935d/pkg/cmd/roachtest/hssplits.go#L98)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Even if we turn backpressure off?
</blockquote></details>

Changed to 50 because that will fail when turning backpressure off, but not all the time.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24905#-:-LATWXd62THx_wG-_xZa:bnfp4nl)*

**Comment by tschottdorf** [comment]
@m-schneider the merge failed because your code doesn't compile:

```
[18:35:05]# github.com/cockroachdb/cockroach/pkg/cmd/roachtest
[18:35:05]pkg/cmd/roachtest/hotspotsplits.go:110:2: undefined: tests
```

Please don't retry builds without first investigating the failure.

**Pull request merged**
