### PR TITLE
Use pgwire instead of the cockroach https driver.

### PR DESCRIPTION
**Pull request by petermattis**
The https driver is particularly inefficient.

name    old time/op  new time/op  delta
Bank-8   267µs ± 2%    96µs ± 1%  -64.25%  (p=0.000 n=10+7)

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4084)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/bank_test.go, line 62 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4084#-K9YA2Fg5gc55ufSFy5i:-K9YA2Fg5gc55ufSFy5j:-814960272) ([raw file](https://github.com/cockroachdb/cockroach/blob/f68894beed619552a682bb154d34df08460daf63/sql/bank_test.go#L62)):*
Why the removal of placeholders? Don't they work?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4084)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/bank_test.go, line 62 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4084#-K9YA2Fg5gc55ufSFy5i:-K9YAM6exlnI_NhBZt1F:1559163756) ([raw file](https://github.com/cockroachdb/cockroach/blob/f68894beed619552a682bb154d34df08460daf63/sql/bank_test.go#L62)):*
No. Meant to ping you. Please fix! :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4084)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/bank_test.go, line 62 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4084#-K9YA2Fg5gc55ufSFy5i:-K9YAhbyd0AwRq7Q5GOg:1085483994) ([raw file](https://github.com/cockroachdb/cockroach/blob/f68894beed619552a682bb154d34df08460daf63/sql/bank_test.go#L62)):*
Will do.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4084)*

**Comment by vivekmenezes** [comment]
LGTM

**Pull request merged**
