### PR TITLE
importccl: pipeline EXPORT string encoding and csv writing

### PR DESCRIPTION
**Pull request by dt**
This adds some parallelism to the EXPORT processor, namely splitting it into two
parts, the first which reads and decodes incoming rows and formats them into the
strings that will be placed the CSV cells, and then a second phase that receives
batches of those strings from the first half and writes them to CSVs that it then
uploads to cloud storage. This hopefully improves performance of EXPORTs of data
that is expensive to encode as strings, such as JSON, which can then be expensive
to write as (compressed) CSV. A subsequent change could stream or parallelize the
actual upload to external storage relatively easily in the second phase with this
split.

Release note (performance improvement): EXPORT encodes exported rows in parallel with writing them to CSVs.

### CODE REVIEW

**Comment by dt** [comment]
I tried to get the diff here to be remotely readable by splitting out the de-dent of the run func into doRun, but to no avail. oh well.

**Review by adityamaru — APPROVED** [review]
LGTM! Thanks for breaking it up.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68183)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/importccl/exportcsv.go, line 225 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68183#-Mfk5Dit6nvvDl6NZW8G:-Mfk5Dit6nvvDl6NZW8H:bwvk4li) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba24b759c2061308f07e96a72cbdbe85df0c340f/pkg/ccl/importccl/exportcsv.go#L225)):*
> ```Go
> 	for {
> 		// TODO(dt): pool these.
> 		batch := make([][]string, 0, batchSize)
> ```

Sorry to invoke the dread beast, but don't you think that this code needs memory accounting? At minimum, wouldn't it be reasonable to ask the csvWriter to just pre-reserve the max batch size worth of bytes? Or maybe 2x that, I can't tell exactly how the memory is being shipped around here.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68183)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/ccl/importccl/exportcsv.go, line 225 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68183#-Mfk5Dit6nvvDl6NZW8G:-MfkKvYpA2TuWDdw_nEx:b9vf4zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba24b759c2061308f07e96a72cbdbe85df0c340f/pkg/ccl/importccl/exportcsv.go#L225)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Sorry to invoke the dread beast, but don't you think that this code needs memory accounting? At minimum, wouldn't it be reasonable to ask the csvWriter to just pre-reserve the max batch size worth of bytes? Or maybe 2x that, I can't tell exactly how the memory is being shipped around here.
</blockquote></details>

oh, for sure -- all of this processor probably wants monitoring, probably especially the 128mb []byte below that the actual csv "file" is written to before it gets flushed to cloud storage ...but I don't think _this_ is the change to add monitoring, since there there some chance a customer demands a backport of this and backporting new mem monitoring is usually a bad idea. Next to the unmonitored whole-file []byte, I'm not super-worried about the 1k row batch (lack of) monitoring, at least while all of EXPORT is still under the "you just have to have enough headroom" implicit rules.

**Comment by dt** [comment]
@adityamaru heh, sorry but after you reviewed this, I went and reworked almost the entire diff to put the new code (that you reviewed) side-by-side with the old code instead of editing the old code in-place, and added a setting to pick which one we want to run

(I also added pooling of the batches while I'm at)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68183)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @jordanlewis)

___
*[pkg/ccl/importccl/exportcsv.go, line 225 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68183#-Mfk5Dit6nvvDl6NZW8G:-MfnXrCSAerGvMozDE7H:b-jtenqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba24b759c2061308f07e96a72cbdbe85df0c340f/pkg/ccl/importccl/exportcsv.go#L225)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

oh, for sure -- all of this processor probably wants monitoring, probably especially the 128mb []byte below that the actual csv "file" is written to before it gets flushed to cloud storage ...but I don't think _this_ is the change to add monitoring, since there there some chance a customer demands a backport of this and backporting new mem monitoring is usually a bad idea. Next to the unmonitored whole-file []byte, I'm not super-worried about the 1k row batch (lack of) monitoring, at least while all of EXPORT is still under the "you just have to have enough headroom" implicit rules.
</blockquote></details>

OK @jordanlewis, added a commit to limit the batch to 8mb worth of strings, and reserve 16mb from the monitor before we start.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68183)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @jordanlewis)

___
*[pkg/ccl/importccl/exportcsv.go, line 225 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68183#-Mfk5Dit6nvvDl6NZW8G:-MfnYH35ACCSw4aL4mFA:b-4wwqkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba24b759c2061308f07e96a72cbdbe85df0c340f/pkg/ccl/importccl/exportcsv.go#L225)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

OK @jordanlewis, added a commit to limit the batch to 8mb worth of strings, and reserve 16mb from the monitor before we start.
</blockquote></details>

(there's still like, 128mb of un-monitored mem in the files, but gotta start somewhere I suppose)

**Comment by adityamaru** [comment]
LGTM! Whether we want to keep the cluster setting or not is still an open question. I'm leaning towards no if we are fairly certain that we aren't backporting. We can always checkout prior to this change when benchmarking 🤷  Also, I remember a mention of changing the compression speed, will that be a follow-up?

**Pull request closed without merging**
