### PR TITLE
sql: add a default AOST option to CREATE STATISTICS

### LINKED ISSUE #72719: sql: consider prohibiting CREATE STATISTICS without specifying AOST option
For `CREATE STATISTICS` statement we get a different internal behavior depending on whether `AS OF SYSTEM TIME` option is specified or not:
- if it isn't, then we perform a regular scan that might contend with concurrent txns (which might have a performance hit, but also might "starve" the stats job)
- if it is, then we do an "inconsistent" scan.

We've seen multiple cases when users didn't know about this difference and shot themselves in the foot. I think that it might be a good idea to error out if AOST is not specified and give a hint to use AOST `-0.001s` (as we already do for `ANALYZE`).

Jira issue: CRDB-11266

### PR DESCRIPTION
**Pull request by Uzair5162**
Using CREATE STATISTICS without an AOST option results in a regular scan which could contend with concurrent transactions. This commit adds a default AOST option of -1us to the CREATE STATISTICS command to avoid this.

Fixes: #72719

Release note (sql change): using the CREATE STATISTICS command without the AS OF SYSTEM TIME option could contend with concurrent transactions and cost performance. Running CREATE STATISTICS without specifying AS OF SYSTEM TIME now uses a default of -1us.

### CODE REVIEW

**Review by michae2 — COMMENTED** [review]
Nice PR! It looks great!

This is a straightforward change, and the motivation makes sense to me. But I wonder if anyone has written a script that is calling `CREATE STATISTICS` manually which will be broken by this new requirement (as our tests were)? Maybe it would be better to add a default AOST if one isn't provided?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-:-NyR2wjKA8nMmsjRHG5J:b-lvmxt9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @Uzair5162)

___
*[`pkg/sql/create_stats.go` line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-NyR2sD25XmoCYONUliY:-NyR2sD25XmoCYONUliZ:bpthjtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/990b896b500d6d36c2c3c2e76f0d3615373e4d20/pkg/sql/create_stats.go#L234)):*
> ```Go
> 
> 	if n.Options.AsOf.Expr == nil {
> 		return nil, pgerror.New(pgcode.Syntax,
> ```

Instead of returning an error, what would you think of adding a default AOST of -1μs, like we do for `ANALYZE`?

Here's where that happens:

https://github.com/cockroachdb/cockroach/blob/d146ecff6f687e438706cf63591cafca60cc116d/pkg/sql/opt/optbuilder/builder.go#L429-L444

**Comment by mgartner** [comment]
>Maybe it would be better to add a default AOST if one isn't provided?

I like that idea. Is there any reasonable use case for running CREATE STATISTICS without AOST? If not, I think we should do this. If there is some need, maybe we need some setting to allow it for certain cases.

**Review by michae2 — COMMENTED** [review]
> Is there any reasonable use case for running CREATE STATISTICS without AOST?

Not that I can think of that wouldn't also work for \-1μs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-:-NyS0xDkAn4sCVy1NZ9z:b-bijgbk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @Uzair5162)

**Review by Uzair5162 — COMMENTED** [review]
Thanks for the suggestion! I've changed it to apply a default AOST instead.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-:-NyVzqQH0LpgVT4NOF7N:b-r8c58n)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — COMMENTED** [review]
This is great work!

> Reviewed 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-:-NyWVTonD1lBqmOPEE9y:bkm56jo)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Uzair5162)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-NyWU2Ie-GWlvKhBc5Wz):*
[nit] `Implements a default AOST of` -> `This commit adds a default AOST option of`
___
*[`pkg/sql/opt/optbuilder/testdata/misc_statements` line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-NyW_hYUDE4ldZs-Htld:-NyW_hYUDE4ldZs-Htle:bdazgrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/696d48d4f5eed455617b582f241e1ecb8b4b2ae1/pkg/sql/opt/optbuilder/testdata/misc_statements#L186)):*
> ```
> ----
> create-statistics
>  └── CREATE STATISTICS foo FROM ab WITH OPTIONS AS OF SYSTEM TIME '-1us'
> ```

A few other tests might be a good idea here:
1. Make sure that a user-specified AOST doesn't get over-ruled.
2. Make sure this works even if a non-AOST option is specified (like `THROTTLING 0.3`)

**Review by Uzair5162 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124488)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-NyWU2Ie-GWlvKhBc5Wz):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `Implements a default AOST of` -> `This commit adds a default AOST option of`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/testdata/misc_statements` line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-NyW_hYUDE4ldZs-Htld:-NyWg7Am3RSwU3me2vA2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/696d48d4f5eed455617b582f241e1ecb8b4b2ae1/pkg/sql/opt/optbuilder/testdata/misc_statements#L186)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

A few other tests might be a good idea here:
1. Make sure that a user-specified AOST doesn't get over-ruled.
2. Make sure this works even if a non-AOST option is specified (like `THROTTLING 0.3`)
</blockquote></details>

Done.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice!

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-:-NyWiLzwAEEqUS9xX4hc:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Uzair5162)

**Review by michae2 — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 1 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-:-NyWk-kYBOUjf-GMcrRA:bcmw7ss)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @Uzair5162)

___
*[`pkg/sql/opt/optbuilder/misc_statements.go` line 152 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-NyWjSHT2g33-Lky9tgp:-NyWjSHT2g33-Lky9tgq:b-4sap59) ([raw file](https://github.com/cockroachdb/cockroach/blob/937da4cc06a8c7eb5b43af34a3bafab6906ddc55/pkg/sql/opt/optbuilder/misc_statements.go#L152)):*
> ```Go
> 	outScope = inScope.push()
> 
> 	if n.Options.AsOf.Expr == nil {
> ```

nit: it might be nice to add a short comment here explaining why the AOST is helpful. (Totally ok to copy the comment from ANALYZE.)
___
*[`pkg/sql/opt/optbuilder/testdata/misc_statements` line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-NyW_hYUDE4ldZs-Htld:-NyWjoioDZ3Yfrct4DHh:bogm3im) ([raw file](https://github.com/cockroachdb/cockroach/blob/696d48d4f5eed455617b582f241e1ecb8b4b2ae1/pkg/sql/opt/optbuilder/testdata/misc_statements#L186)):*
<details><summary><i>Previously, Uzair5162 (Uzair Ahmad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm curious, does `AS OF SYSTEM TIME '0s'` work? That might be a good testcase as well.

**Review by Uzair5162 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124488)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/opt/optbuilder/testdata/misc_statements` line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124488#-NyW_hYUDE4ldZs-Htld:-NyWx03Y8QJUL-fuh4Rs:b-uhwtwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/696d48d4f5eed455617b582f241e1ecb8b4b2ae1/pkg/sql/opt/optbuilder/testdata/misc_statements#L186)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I'm curious, does `AS OF SYSTEM TIME '0s'` work? That might be a good testcase as well.
</blockquote></details>

We require the AOST interval to be >= 1µs:
https://github.com/cockroachdb/cockroach/blob/d146ecff6f687e438706cf63591cafca60cc116d/pkg/sql/sem/asof/as_of.go#L266

**Comment by mgartner** [comment]
Great work @Uzair5162!

**Pull request merged**
