### PR TITLE
storage: apply lease change side-effects on snapshot recipients

### LINKED ISSUE #30886: roachtest: tpcc/nodes=3/w=max failed
SHA: https://github.com/cockroachdb/cockroach/commits/0f5a289d49105cd317a2713b71546d84c25547f6

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=tpcc/nodes=3/w=max PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=937459&tab=buildLog

```
The test failed on master:
	test.go:500,cluster.go:890,tpcc.go:78,cluster.go:1199,errgroup.go:58: /home/agent/work/.go/bin/roachprod run teamcity-937459-tpcc-nodes-3-w-max:4 -- ./workload run tpcc --warehouses=1400 --duration=120m {pgurl:1-3} --histograms=logs/stats.json returned:
		stderr:
		
		stdout:
		ckLevel
		    3m6s        0            0.0           23.5      0.0      0.0      0.0      0.0 delivery
		    3m6s        0            0.0          221.1      0.0      0.0      0.0      0.0 newOrder
		    3m6s        0            0.0           24.3      0.0      0.0      0.0      0.0 orderStatus
		    3m6s        0            0.0          243.9      0.0      0.0      0.0      0.0 payment
		    3m6s        0            0.0           23.8      0.0      0.0      0.0      0.0 stockLevel
		    3m7s        0            0.0           23.4      0.0      0.0      0.0      0.0 delivery
		    3m7s        0            0.0          219.9      0.0      0.0      0.0      0.0 newOrder
		    3m7s        0            0.0           24.2      0.0      0.0      0.0      0.0 orderStatus
		    3m7s        0            0.0          242.6      0.0      0.0      0.0      0.0 payment
		    3m7s        0            0.0           23.7      0.0      0.0      0.0      0.0 stockLevel
		Error: error in delivery: pq: context deadline exceeded
		Error:  exit status 1
		: exit status 1
	test.go:500,cluster.go:1220,tpcc.go:81,tpcc.go:95: Goexit() was called

```

### LINKED ISSUE #32813: roachtest: cdc/tpcc-1000 failed
SHA: https://github.com/cockroachdb/cockroach/commits/e6cb0c5c329617b560eee37527248171b5e06382

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=cdc/tpcc-1000 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1038478&tab=buildLog

```
The test failed on master:
	test.go:630,cluster.go:1141,cdc.go:531,cdc.go:103,cluster.go:1467,errgroup.go:58: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1038478-cdc-tpcc-1000:4 -- ./workload run tpcc --warehouses=1000 --duration=120m --tolerate-errors {pgurl:1-3}  returned:
		stderr:
		
		stdout:
		: signal: killed
	test.go:630,cluster.go:1488,cdc.go:179,cdc.go:319: pq: AS OF SYSTEM TIME: cannot specify timestamp in the future

```

### LINKED ISSUE #33149: roachtest: scrub/all-checks/tpcc-1000 failed
SHA: https://github.com/cockroachdb/cockroach/commits/859214b81838a4ba33048b81497442ce5774baa7

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=scrub/all-checks/tpcc-1000 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1053297&tab=buildLog

```
The test failed on master:
	test.go:630,schemachange.go:329,scrub.go:75,cluster.go:1465,errgroup.go:57: dial tcp 35.232.175.103:26257: connect: connection refused
	test.go:630,cluster.go:1486,tpcc.go:120,scrub.go:71: Goexit() was called

```

### LINKED ISSUE #33151: roachtest: scrub/index-only/tpcc-1000 failed
SHA: https://github.com/cockroachdb/cockroach/commits/859214b81838a4ba33048b81497442ce5774baa7

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=scrub/index-only/tpcc-1000 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1053297&tab=buildLog

```
The test failed on master:
	test.go:630,schemachange.go:329,scrub.go:75,cluster.go:1465,errgroup.go:57: dial tcp 104.154.79.202:26257: connect: connection refused
	test.go:630,cluster.go:1486,tpcc.go:120,scrub.go:71: signal: interrupt

```

### LINKED ISSUE #33335: roachtest: schemachange/indexrollback/tpcc-1000 failed
SHA: https://github.com/cockroachdb/cockroach/commits/98ef7abf32784b8e837d18d10173ef083010ad45

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=schemachange/indexrollback/tpcc-1000 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1067238&tab=buildLog

```
The test failed on master:
	test.go:703,cluster.go:1137,tpcc.go:110,cluster.go:1463,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1067238-schemachange-indexrollback-tpcc-1000:5 -- ./workload run tpcc --warehouses=1000 --histograms=logs/stats.json --wait=false --tolerate-errors --ramp=5m0s --duration=2h0m0s {pgurl:1-4} returned:
		stderr:
		
		stdout:
		l
		_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
		   9m29s       69            2.0            3.6   2952.8   8589.9   8589.9   8589.9 delivery
		   9m29s       69           29.9           32.2   5905.6  85899.3 103079.2 103079.2 newOrder
		   9m29s       69            3.0            3.5    671.1   2415.9   2415.9   2415.9 orderStatus
		   9m29s       69           39.8           27.7  11274.3 103079.2 103079.2 103079.2 payment
		   9m29s       69            5.0            3.5   3758.1   4160.7   4160.7   4160.7 stockLevel
		   9m30s       69            2.0            3.6   4831.8   6979.3   6979.3   6979.3 delivery
		   9m30s       69           77.3           32.3   6979.3 103079.2 103079.2 103079.2 newOrder
		   9m30s       69            4.0            3.5   3892.3   4831.8   4831.8   4831.8 orderStatus
		   9m30s       69           59.2           27.8   5100.3 103079.2 103079.2 103079.2 payment
		   9m30s       69            8.0            3.5    192.9   3489.7   3489.7   3489.7 stockLevel
		: signal: killed
	test.go:703,cluster.go:1484,tpcc.go:120,schemachange.go:375: got non-success terminal status "failed"

```

### LINKED ISSUE #33624: roachtest: schemachange/index/tpcc-1000 failed
SHA: https://github.com/cockroachdb/cockroach/commits/5cb2c3803d0ea3342415ab1a72ed86d356510e0b

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=schemachange/index/tpcc-1000 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1086773&tab=buildLog

```
The test failed on master:
	test.go:696,schemachange.go:441,schemachange.go:313,cluster.go:1490,errgroup.go:57: pq: span /Table/56/1/{480/5/-1640/0-514/3/-368/0} not found among [/Table/56/1/{250/8/-1804/0-311/4/-1760} /Table/56/1/3{11/4/-1760/0-48/3/-1159} /Table/56/1/385/2/-558{-/0} /Table/56/1/4{27/4/-448/0-59/1/-2302} /Table/56/1/47{1/5/-2277/0-7/4/-969} /Table/56/{1/480/8/-1399/0-2}]
	test.go:696,cluster.go:1164,tpcc.go:110,cluster.go:1490,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1086773-schemachange-index-tpcc-1000:5 -- ./workload run tpcc --warehouses=1000 --histograms=logs/stats.json --wait=false --tolerate-errors --ramp=5m0s --duration=2h0m0s {pgurl:1-4} returned:
		stderr:
		
		stdout:
		     745            0.0            2.3      0.0      0.0      0.0      0.0 stockLevel
		1h59m47s      745            5.0            2.3   3623.9   3892.3   3892.3   3892.3 delivery
		1h59m47s      745           52.1           23.0   2550.1  26843.5 103079.2 103079.2 newOrder
		1h59m47s      745            4.0            2.3    402.7    453.0    453.0    453.0 orderStatus
		1h59m47s      745           43.1           22.6   1610.6 103079.2 103079.2 103079.2 payment
		1h59m47s      745            1.0            2.3    419.4    419.4    419.4    419.4 stockLevel
		1h59m48s      745            0.0            2.3      0.0      0.0      0.0      0.0 delivery
		1h59m48s      745            9.0           23.0   3355.4   5100.3   5100.3   5100.3 newOrder
		1h59m48s      745            2.0            2.3   1275.1   1677.7   1677.7   1677.7 orderStatus
		1h59m48s      745            2.0           22.6   2684.4   2684.4   2684.4   2684.4 payment
		1h59m48s      745            1.0            2.3    906.0    906.0    906.0    906.0 stockLevel
		: signal: killed
	test.go:696,cluster.go:1511,tpcc.go:120,schemachange.go:309: Goexit() was called

```

### LINKED ISSUE #34025: roachtest: tpcc-1000 roachtests have failing checks
Some roachtests that involve running tpcc-1000 are failing the tpcc checks at the end, e.g.:

```
		I190114 15:41:47.835436 1 workload/tpcc/tpcc.go:290  check 3.3.2.1 took 162.495391ms
		Error: check failed: 3.3.2.1: 12 rows returned, expected zero
```
The tests affected by this:

- #33624 (schemachange/index/tpcc-1000)
- #33335 (schemachange/indexrollback/tpcc-1000)
- #33151 (scrub/index-only/tpcc-1000)
- #33149 (scrub/all-checks/tpcc-1000)
- https://github.com/cockroachdb/cockroach/issues/32813#issuecomment-453920621 (cdc/tpcc-1000) is potentially related

https://teamcity.cockroachdb.com/viewLog.html?buildId=1085451&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=buildResultsDiv seems to be the first test failure of this kind. I reproduced this failure on `scrub/index-only/tpcc-1000` on a separate roachprod cluster, and ran SCRUB on the entire tpcc database, which did not turn up any anomalies.

It's not clear whether this is a schema change problem, a problem with the tests, or something else. Some next steps would be to determine whether this occurs when just running tpcc-1000 by itself, and look at what the anomalous rows are in the results of the check query.

### LINKED ISSUE #34159: roachtest: schemachange/indexrollback/tpcc-1000 failed
SHA: https://github.com/cockroachdb/cockroach/commits/89ce71e9b733df3855b370aa20bb809db3d4362c

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=schemachange/indexrollback/tpcc-1000 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1103150&tab=buildLog

```
The test failed on provisional_201901161553_v2.1.4:
	test.go:1133: test timed out (1h0m0s)
	test.go:727,cluster.go:1203,tpcc.go:118,cluster.go:1541,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1103150-schemachange-indexrollback-tpcc-1000:5 -- ./workload run tpcc --warehouses=1000 --histograms=logs/stats.json --wait=false --tolerate-errors --ramp=5m0s --duration=30m0s {pgurl:1-4} returned:
		stderr:
		
		stdout:
		       0            9.0            6.5    125.8  27917.3  27917.3  27917.3 stockLevel
		   2m58s        0            2.0            6.5     67.1    104.9    104.9    104.9 delivery
		   2m58s        0            6.0           57.4    453.0    570.4    570.4    570.4 newOrder
		   2m58s        0            2.0            6.3     37.7    503.3    503.3    503.3 orderStatus
		   2m58s        0            0.0           43.1      0.0      0.0      0.0      0.0 payment
		   2m58s        0            1.0            6.5    113.2    113.2    113.2    113.2 stockLevel
		   2m59s        0            0.0            6.5      0.0      0.0      0.0      0.0 delivery
		   2m59s        0           11.0           57.2    285.2  25769.8  40802.2  40802.2 newOrder
		   2m59s        0            2.0            6.2     28.3     31.5     31.5     31.5 orderStatus
		   2m59s        0            1.0           42.8  15569.3  15569.3  15569.3  15569.3 payment
		   2m59s        0            4.0            6.4     96.5    109.1    109.1    109.1 stockLevel
		: signal: killed
	test.go:727,cluster.go:1562,tpcc.go:128,schemachange.go:375: Goexit() was called
	asm_amd64.s:523,panic.go:513,log.go:219,test.go:1097,asm_amd64.s:522,panic.go:397,test.go:728,cluster.go:1562,tpcc.go:128,schemachange.go:375: write /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190121-1103150/schemachange/indexrollback/tpcc-1000/test.log: file already closed

```

### LINKED ISSUE #34228: Frequent errors when running tpc-c on six node cluster
**Describe the problem**

While running tpc-c on six node clusters, I see repeated failures of:
```
Error: error in newOrder: ERROR: duplicate key value (o_w_id,o_d_id,o_id)=(1794,10,3002) violates unique constraint "primary" (SQLSTATE 23505)
Error:  exit status 1
```

Note, I've observed this on multiple separate nodes.

**To Reproduce**

1. export CLUSTER=andy-base
2. roachprod create $CLUSTER -n 7 --clouds=aws  --aws-machine-type-ssd=c5d.4xlarge
3. roachprod run $CLUSTER:1-6 -- 'sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier /dev/nvme1n1 /mnt/data1/; mount | grep /mnt/data1'
4. roachprod stage $CLUSTER:1-6 cockroach
5. roachprod stage $CLUSTER:7 workload
6. roachprod start $CLUSTER:1-6
7. roachprod adminurl --open $CLUSTER:1
8. roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=5000 --db=tpcc"
9. roachprod run $CLUSTER:7 "./workload run tpcc --ramp=5m --warehouses=4000 --duration=15m --split --scatter {pgurl:1-3}"

**Expected behavior**
TPC-C compelte without an error.

**Environment:**
v2.2.0-alpha.20181217-820-g645c0c9

### LINKED ISSUE #34293: roachtest: tpcc/w=100/nodes=3/chaos=true failed
SHA: https://github.com/cockroachdb/cockroach/commits/9f084ad576e85756c5c5a7e41335d9aa2d3eee30

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=tpcc/w=100/nodes=3/chaos=true PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1112101&tab=buildLog

```
The test failed on master:
	test.go:743,cluster.go:1195,tpcc.go:130,tpcc.go:182: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1112101-tpcc-w-100-nodes-3-chaos-true:4 -- ./workload check tpcc --warehouses=100 {pgurl:1} returned:
		stderr:
		
		stdout:
		I190128 15:31:29.230660 1 workload/tpcc/tpcc.go:288  check 3.3.2.1 took 29.119545ms
		I190128 15:31:32.440868 1 workload/tpcc/tpcc.go:288  check 3.3.2.2 took 3.21016191s
		Error: check failed: 3.3.2.2: inequality at idx 435: order: 3010.000000, newOrder: 3010.000000, district-1: 3009.000000
		Error:  exit status 1
		: exit status 1

```

### LINKED ISSUE #34321: jepsen: bank/majority-ring failed with `wrong-total`
SHA: https://github.com/cockroachdb/cockroach/commits/e10fb557b11b5ff1b8609aa963da23c37a1143c8

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=jepsen-batch1/bank/majority-ring PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1113854&tab=buildLog

```
The test failed on master:
	test.go:743,jepsen.go:247,jepsen.go:308: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1113854-jepsen-batch1:6 -- bash -e -c "\
		cd /mnt/data1/jepsen/cockroachdb && set -eo pipefail && \
		 ~/lein run test \
		   --tarball file://${PWD}/cockroach.tgz \
		   --username ${USER} \
		   --ssh-private-key ~/.ssh/id_rsa \
		   --os ubuntu \
		   --time-limit 300 \
		   --concurrency 30 \
		   --recovery-time 25 \
		   --test-count 1 \
		   -n 10.128.0.70 -n 10.128.0.92 -n 10.128.0.78 -n 10.128.0.29 -n 10.128.0.88 \
		   --test bank --nemesis majority-ring \
		> invoke.log 2>&1 \
		" returned:
		stderr:
		
		stdout:
		Error:  exit status 1
		: exit status 1

```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #34025.
Fixes #33624.
Fixes #33335.
Fixes #33151.
Fixes #33149.
Fixes #34159.
Fixes #34293.
Fixes #32813.
Fixes #30886.
Fixes #34228.
Fixes #34321.

It is rare but possible for a replica to become a leaseholder but not learn about this until it applies a snapshot. Immediately upon the snapshot application's `ReplicaState` update, the replica will begin operating as a standard leaseholder.

Before this change, leases acquired in this way would not trigger in-memory side-effects to be performed. This could result in a regression in the new leaseholder's timestamp cache compared to the previous leaseholder's cache, allowing write-skew like we saw in #34025. This could presumably result in other anomalies as well, because all of the steps in `leasePostApply` were skipped (as theorized by https://github.com/cockroachdb/cockroach/issues/34025#issuecomment-460393818).

This PR fixes this bug by detecting lease updates when applying snapshots and making sure to react correctly to them. It also likely fixes the referenced issue. The new test demonstrates that without this fix, the serializable violation speculated about in the issue was possible.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm_strong: thank you for getting that in place so quickly. The code changes LGTM, and the comments on the test are minor. (Please check that it's not flaky though if you haven't already).

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-:-LXxioup4D8KJaEjSi3v:bi9kyqt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/client_replica_test.go, line 1855 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-LXxhrULAHZM61Oj_hY9:-LXxhrULAHZM61Oj_hYA:bfeuyja) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74eb2627dfaf2c2abc51b77b8d248dabda36ceb/pkg/storage/client_replica_test.go#L1855)):*
> ```Go
> 		t.Fatal(pErr)
> 	}
> 	incArgs = incrementArgs(keyC, 2)
> ```

Mind renaming this `incC` so that the later use at the bottom is more obvious?
___
*[pkg/storage/client_replica_test.go, line 1876 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-LXxh1NG45eMYdsEgSBr:-LXxh1NG45eMYdsEgSBs:b-xi4o2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74eb2627dfaf2c2abc51b77b8d248dabda36ceb/pkg/storage/client_replica_test.go#L1876)):*
> that will
___
*[pkg/storage/client_replica_test.go, line 1908 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-LXxhNjDAt5xhURap2Ee:-LXxhNjDAt5xhURap2Ef:b1hglt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74eb2627dfaf2c2abc51b77b8d248dabda36ceb/pkg/storage/client_replica_test.go#L1908)):*
> ```Go
> 	// ensures that that when node 2 comes back up it will require a snapshot
> 	// from Raft.
> 	mtc.transport.GetCircuitBreaker(mtc.idents[2].NodeID).Break()
> ```

Won't it possibly reset? I think the merge tests do something with the Raft transport to achieve the desired effect. Mind looking into whether that is more appropriate? There's a chance what you're doing is actually better. Not sure.
___
*[pkg/storage/replica_proposal.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-LXxiM8B-bNneUvmq7nx:-LXxiM8B-bNneUvmq7ny:bz9xki2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74eb2627dfaf2c2abc51b77b8d248dabda36ceb/pkg/storage/replica_proposal.go#L203)):*
`prevLease` isn't necessarily the previous lease. I would like this to be obvious, maybe `somePreviousLease` with a comment

> if permitJump is true, we only know that prevLease is some previous lease on the range, but it may not be the one in place before newLease became known to this replica. This typically happens when a snapshot is applied.

Open to better ideas.

**Review by bdarnell — APPROVED** [review]
:lgtm: 

Should we also optimistically mark this as fixing #34321?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-:-LXyNFijCLipXkcgodve:bereh8n)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> Please check that it's not flaky though if you haven't already

 I stressed for about 10 minutes without a flake.

> Should we also optimistically mark this as fixing #34321?

Done. And for a few more issues.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-:-LXyjrVd1XxEXGzLmgcx:bxl90on)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @tbg)

___
*[pkg/storage/client_replica_test.go, line 1855 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-LXxhrULAHZM61Oj_hY9:-LXykFDq4t4LhGdJ2wYm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74eb2627dfaf2c2abc51b77b8d248dabda36ceb/pkg/storage/client_replica_test.go#L1855)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Mind renaming this `incC` so that the later use at the bottom is more obvious?
</blockquote></details>

Done.
___
*[pkg/storage/client_replica_test.go, line 1876 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-LXxh1NG45eMYdsEgSBr:-LXykHdC54S_98uwfgdW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74eb2627dfaf2c2abc51b77b8d248dabda36ceb/pkg/storage/client_replica_test.go#L1876)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> that will
</blockquote></details>

Done.
___
*[pkg/storage/client_replica_test.go, line 1908 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-LXxhNjDAt5xhURap2Ee:-LXyph7jAX8C-HO83yom:b-gawe1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74eb2627dfaf2c2abc51b77b8d248dabda36ceb/pkg/storage/client_replica_test.go#L1908)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Won't it possibly reset? I think the merge tests do something with the Raft transport to achieve the desired effect. Mind looking into whether that is more appropriate? There's a chance what you're doing is actually better. Not sure.
</blockquote></details>

I don't think it could reset because it's not just tripped, but the `unreliableRaftHandler` is much better! Done here and in another test that was using breakers.
___
*[pkg/storage/replica_proposal.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34548#-LXxiM8B-bNneUvmq7nx:-LXymWES5hzRwiZ56aL6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74eb2627dfaf2c2abc51b77b8d248dabda36ceb/pkg/storage/replica_proposal.go#L203)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

`prevLease` isn't necessarily the previous lease. I would like this to be obvious, maybe `somePreviousLease` with a comment

> if permitJump is true, we only know that prevLease is some previous lease on the range, but it may not be the one in place before newLease became known to this replica. This typically happens when a snapshot is applied.

Open to better ideas.
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
bors crashed

bors r-

**Pull request merged**
