### PR TITLE
workload/schemachange: create composite type in RSW

### LINKED ISSUE #126007: workload/schemachange: create composite type in random schemachange workload (Missing test)
**Is your feature request related to a problem? Please describe.**
Currently in our random schemachange workload we only test enum types via createEnum in operation_generator.go

**Describe the solution you'd like**
Similars tests for composite types as we have for enum types.

Jira issue: CRDB-39723

Epic CRDB-19168

### PR DESCRIPTION
**Pull request by Dedej-Bergin**
This is the addition of missing tests with composite types, with the newly added COMMENT ON TYPE functionality we now test for comment on composite types as well with the RSW (Random Schemachanger Workload).

Fixes: #126007

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice! i just had some minor comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-:-O1riJLq5HqMsuD2GZWf:b-ww99c6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @Dedej-Bergin, @michae2, @nameisbhaskar, and @spilchen)

___
*[`pkg/internal/sqlsmith/alter.go` line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1rf8E54YNIkQz33wLG:-O1rf8E613AYPX9f1LuX:b-k2xhvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/internal/sqlsmith/alter.go#L423)):*
> ```Go
> func makeCreateType(s *Smither) (tree.Statement, bool) {
> 	name := s.name("typ")
> 	return randgen.RandCreateEnumType(s.rnd, string(name), letters), true
> ```

nit: this should be generating both enum and composite types. this can be changed to have a 50/50 chance of calling RandCreateEnumType or RandCreateCompositeType
___
*[`pkg/internal/sqlsmith/setup.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1rfX9z04-X6BeX4dLm:-O1rfX9z04-X6BeX4dLn:b-k2xhvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/internal/sqlsmith/setup.go#L153)):*
> ```Go
> 	for i := 0; i < numTypes; i++ {
> 		name := fmt.Sprintf("rand_typ_%d", i)
> 		stmt := randgen.RandCreateEnumType(r, name, letters)
> ```

nit: this should be generating both enum and composite types. this can be changed to have a 50/50 chance of calling RandCreateEnumType or RandCreateCompositeType
___
*[`pkg/sql/randgen/schema.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1rg58R7T_3wi_aGYMx:-O1rg58R7T_3wi_aGYMy:b-2bhgl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/sql/randgen/schema.go#L89)):*
> ```Go
> 	for i := 0; i < numTypes; {
> 		randomName := util.RandString(rng, rng.Intn(6)+1, alphabet)
> 		randomType := getType(i)
> ```

instead of using round-robin, i think we should use a random type here. use: `RandTypeFromSlice(rng, types.Scalar)`
___
*[`pkg/workload/schemachange/operation_generator.go` line 1248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1ri4I1A14LIeY-FFWT:-O1ri4I1A14LIeY-FFWU:bowc7io) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/workload/schemachange/operation_generator.go#L1248)):*
> ```Go
> 
> func (og *operationGenerator) createType(
> 	ctx context.Context, tx pgx.Tx, prefix string,
> ```

nit: rather than making the caller pass in a prefix, which is easy to mess up and pass in the wrong thing, it would be better to make this a boolean. the prefix should be determined inside this function with:
```
if isEnum {
  prefix = "enum_"
else {
  prefix = "composite_"
}
```
___
*[`pkg/workload/schemachange/operation_generator.go` line 3499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1riCzo8UEWIn-6rX0g:-O1riCzo8UEWIn-6rX0h:bjng62m) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/workload/schemachange/operation_generator.go#L3499)):*
> ```Go
> 
> func (og *operationGenerator) randTypeName(
> 	ctx context.Context, tx pgx.Tx, pctExisting int, prefix string,
> ```

this should also use a boolean rather than taking a string as an argument
___
*[`pkg/workload/schemachange/optype.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1rhL-c9zW-ak7JfV13:-O1rhL-c9zW-ak7JfV14:b-7vr5he) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/workload/schemachange/optype.go#L142)):*
> ```Go
> 	dropView     // DROP VIEW <view>
> 
> 	createTypeComposite
> ```

nit: keep this grouped with the other `CREATE` operations, which are a few lines above this

**Review by Dedej-Bergin — COMMENTED** [review]
tftr

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-:-O1sDjkN3otSSxbsmE4P:bb7p3w5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @michae2, @nameisbhaskar, @rafiss, and @spilchen)

___
*[`pkg/internal/sqlsmith/alter.go` line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1rf8E54YNIkQz33wLG:-O1s9ihEEe7r7pp21BW4:b-n1g5ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/internal/sqlsmith/alter.go#L423)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this should be generating both enum and composite types. this can be changed to have a 50/50 chance of calling RandCreateEnumType or RandCreateCompositeType
</blockquote></details>

Thanks Rafi, I added a coin toss to it.
___
*[`pkg/internal/sqlsmith/setup.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1rfX9z04-X6BeX4dLm:-O1s9qV74-GkvpwwTMjO:b-qabnrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/internal/sqlsmith/setup.go#L153)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this should be generating both enum and composite types. this can be changed to have a 50/50 chance of calling RandCreateEnumType or RandCreateCompositeType
</blockquote></details>

Thanks Rafi, I added a check for this.
___
*[`pkg/sql/randgen/schema.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1rg58R7T_3wi_aGYMx:-O1sB5DN7kGNo32GBTAa:b-z5978c) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/sql/randgen/schema.go#L89)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of using round-robin, i think we should use a random type here. use: `RandTypeFromSlice(rng, types.Scalar)`
</blockquote></details>

Very nice, thanks Rafi! I went ahead and did this.
___
*[`pkg/workload/schemachange/operation_generator.go` line 1248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1ri4I1A14LIeY-FFWT:-O1sBvLG3HNA6j5bp55L:b-inly2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/workload/schemachange/operation_generator.go#L1248)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: rather than making the caller pass in a prefix, which is easy to mess up and pass in the wrong thing, it would be better to make this a boolean. the prefix should be determined inside this function with:
```
if isEnum {
  prefix = "enum_"
else {
  prefix = "composite_"
}
```
</blockquote></details>

Sounds good, I went ahead and made this change. Thanks Rafi!
___
*[`pkg/workload/schemachange/operation_generator.go` line 3499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1riCzo8UEWIn-6rX0g:-O1sD3TB5B2hlhnHILir:b-inly2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/workload/schemachange/operation_generator.go#L3499)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this should also use a boolean rather than taking a string as an argument
</blockquote></details>

Sounds good, I went ahead and made this change. Thanks Rafi!
___
*[`pkg/workload/schemachange/optype.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-O1rhL-c9zW-ak7JfV13:-O1sDVPi4qIS8zDZ9pFu:b-t03dwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/47608536a37c920d4c0a39deb4809ed5b8318582/pkg/workload/schemachange/optype.go#L142)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: keep this grouped with the other `CREATE` operations, which are a few lines above this
</blockquote></details>

Yes, just added it, thanks Rafi!

**Review by rafiss — APPROVED** [review]
lgtm! nice work

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127185#-:-O218_M947mPq2NBt1N3:b-m0nb8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @michae2, @nameisbhaskar, and @spilchen)

**Comment by renatolabs** [comment]
Friendly reminder/request to double check this doesn't need any version gates please. Running `acceptance/version-upgrade` on the branch 20-30 times should be a good signal.

**Comment by rafiss** [comment]
bors retry

**Pull request merged**
