### PR TITLE
build: remove .gitkeep file

### PR DESCRIPTION
**Pull request by benesch**
This file appears to have been unnecessarily added by 85771ba4.

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by benesch** [comment]
Loving these Friday night CRs 😄

**Comment by tschottdorf** [comment]
What's a CR? CL+PR?

**Comment by benesch** [comment]
Heh, I meant it as "code review."

**Comment by benesch** [comment]
Thanks for the CR! ;)

**Pull request merged**
