### PR TITLE
docs: improve cloud-resources.md doc

### PR DESCRIPTION
**Pull request by jienius**

### CODE REVIEW

**Review by otan — APPROVED** [review]

**Comment by otan** [comment]
thanks for fixing these typos!

bors r+

**Comment by otan** [comment]
strange, not sure why bors isn't taking it

**Comment by otan** [comment]
it looks like it's because it can't find the branch this is based off. can you make sure this is a commit from a SHA?

**Comment by jienius** [comment]
> it looks like it's because it can't find the branch this is based off. can you make sure this is a commit from a SHA?

I deleted my fork. Opened another one: https://github.com/cockroachdb/cockroach/pull/50722
Sorry about this....

**Pull request closed without merging**
