### PR TITLE
gossip: lock down the protocol to prevent illegal joining of multiple clusters

### LINKED ISSUE #3583: gossip: joining two initialized clusters
we have some checks in place to prevent a node from joining a Gossip network it doesn't belong to, but it gets more difficult when two initialized nodes happen to be put in the same Gossip network.
#3236 treats one instance of this, but an actual solution should happen on the connection level.

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #3583

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14475)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[build/protobuf.mk, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14475#-KgUx-qCkK0lMV73_NpW:-KgUx-qCkK0lMV73_NpX:b-dqhnfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2d0e7814740a23d74533967b48d0033aac8585/build/protobuf.mk#L76)):*
> ```Makefile
> CPP_SOURCES := $(subst ./,$(NATIVE_ROOT)/,$(CPP_PROTOS:%.proto=%.pb.cc))
> 
> # Tell Make to delete the target if its recipe fails. Otherwise, if a recipe
> ```

call this out in the commit message

---

*[pkg/gossip/gossip_test.go, line 486 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14475#-KgUxY24r5nv_NSqygSb:-KgUxY24r5nv_NSqygSc:bwjfh9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2d0e7814740a23d74533967b48d0033aac8585/pkg/gossip/gossip_test.go#L486)):*
> ```Go
> 	// first of its bootstrap hosts.
> 	for i := 0; i < 3; i++ {
> 		stoppers = append(stoppers, stop.NewStopper())
> ```

defer something here to to ensure cleanup in the failure case
maybe
```
defer func() {
  select {
  case <-stopper.ShouldQuiesce():
  default:
    stopper.Stop()
  }
}()
```

---

*[pkg/gossip/server.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14475#-KgUwvDIeEYiHnIDaFbn:-KgUwvDJrmOhner96wTQ:b-3n4nis) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac919e6607935c73ab388ebe690996d56ae9d0e3/pkg/gossip/server.go#L132)):*
> ```Go
> 	}
> 	if args.ClusterID != s.GetClusterID() {
> 		return errors.Errorf("gossip connection refused from different cluster %s", args.ClusterID)
> ```

consider including our own cluster ID

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14475#-:-KgUx42Gkw2_3lCSYEIw:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 6 of 8 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14475#-:-KgV2ixa_vwyOW_N2eN0:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[build/protobuf.mk, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14475#-KgUx-qCkK0lMV73_NpW:-KgV69hSf1Cgv6pFUcar:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2d0e7814740a23d74533967b48d0033aac8585/build/protobuf.mk#L76)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

call this out in the commit message
</blockquote></details>

Done.

---

*[pkg/gossip/gossip_test.go, line 486 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14475#-KgUxY24r5nv_NSqygSb:-KgV5ij1SXQnOR8zrdpG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c2d0e7814740a23d74533967b48d0033aac8585/pkg/gossip/gossip_test.go#L486)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

defer something here to to ensure cleanup in the failure case
maybe
```
defer func() {
  select {
  case <-stopper.ShouldQuiesce():
  default:
    stopper.Stop()
  }
}()
```
</blockquote></details>

Done.

---

*[pkg/gossip/server.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14475#-KgUwvDIeEYiHnIDaFbn:-KgV5kUiQsTNqMuLEgIP:b-wk2ak8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac919e6607935c73ab388ebe690996d56ae9d0e3/pkg/gossip/server.go#L132)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

consider including our own cluster ID
</blockquote></details>

It doesn't strike me as terribly worthwhile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14475)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14475)*

**Comment by spencerkimball** [comment]
@tamird any ideas about the failing acceptance test?

**Comment by tamird** [comment]
No, sorry. Looks like the flakiest one at the moment.

**Pull request merged**
