### PR TITLE
cloud: update Kubernetes config files for 19.2.

### PR DESCRIPTION
**Pull request by jordanlewis**
Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
I don’t feel particularly qualified to review this. I’ll 🔬 🐶 stamp this because it looks sane but don’t put much trust in that. Maybe @joshimhoff 

:lgtm:  

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42396#-:-LtUa8UB7N6HN2zAHuNa:b75yrqu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell)

**Review by bdarnell — APPROVED** [review]

**Comment by joshimhoff** [comment]
@DuskEagle and I are happy to review changes like this. With that said, the whole thing is sketchy regardless of who reviews. IIUC no real testing of k8s config files/helm charts, even though our customers depend critically on them. And no in the company except for SE really uses the config files/helm charts directly. Def something to think about improving.

**Comment by joshimhoff** [comment]
Perhaps a medium to long term solution is an operator, which we develop actively (and possibly even use in CC) and thus has actual testing.

**Review by joshimhoff — APPROVED** [review]

**Comment by mtparet** [comment]
@joshimhoff do you mean you are actually developing an operator for cockroachdb ? Would be awesome.

**Comment by joshimhoff** [comment]
Ya this is something that @vladdy has been advocating for and has more details about!

**Comment by bobvawter** [comment]
[CLA assistant check](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=42396) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=42396) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=42396) it.</sub>

**Pull request closed without merging**
