### PR TITLE
mt_start_sql: enable enterprise features for multitenant sql servers

### PR DESCRIPTION
**Pull request by jeffswenson**
Enterprise features are controlled by the enterprise.license setting.
Currently this setting applies only to the host tenant cluster. This
change enables enterprise features for all tenant clusters. Enabling
enterprise features for all tenants is reasonable, because multi
tenant deployments are an enterprise feature.

Release note: None

### CODE REVIEW

**Comment by JeffSwenson** [comment]
More context is available on slack: https://cockroachlabs.slack.com/archives/C01CDD4HRC5/p1628542467012900

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69115#-:-MhRKtU36zpZaoNc08eE:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @JeffSwenson)

___
*[pkg/ccl/utilccl/license_check.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69115#-MhY4G_LD4JcJQJyW2YE:-MhY4G_M3GK-rx_MOXwm:b-b3gz40) ([raw file](https://github.com/cockroachdb/cockroach/blob/7850559d4c0274d080033e1b4d32ab84a8a6a215/pkg/ccl/utilccl/license_check.go#L118)):*
> ```Go
> 	base.LicenseType = getLicenseType
> 	base.TimeToEnterpriseLicenseExpiry = TimeToEnterpriseLicenseExpiry
> 	server.EnableEnterpriseForTenant = EnableEnterpriseWithImpliedLicense
> ```

This does not sound right. 
With this change, any person who downloads the source code from github, builds their own CCL binary and starts a crdb cluster with a tenant pod can use enterprise features without a license, **and claim they are legally entitled to do so because the product did not prompt for anything**.

IMHO this mode of operation should be opt-in; for example using a serverless-specific license key that we would set using an env var in the k8s pods in the CC infra.

**Comment by andy-kimball** [comment]
@knz, who owns these decisions? We're willing to do whatever should be done, but who decides what should be done?

**Comment by knz** [comment]
That's a product decision, from someone close to our licensing goals. I'm not sure who exactly is currently closest to licensing, but Nate would know.

That being said the engineering viewpoint (from my perspective) is to follow established semantics, where a valid license key should be supplied externally to the process to enable licensing features. It ensures that the decision to enable remains in the hands of the operator for the particular deployment of crdb, and does not automatically extend to all users who happen to have a similar execution script.

**Comment by kannanlakshmi** [comment]
@piyush-singh owns this from the Product side but he is out, so @mwang1026 is filling in for the next month till Piyush is back.

**Comment by andy-kimball** [comment]
Can we check the license in these situations:

1. When a new tenant is created (in KV processes).
2. When a KV process is started and at least one active tenant exists.

If we did this, then there'd be no need to recheck the license repeatedly in the SQL tenant processes.

**Comment by JeffSwenson** [comment]
@knz are you okay with this change if the KV layer checks for the enterprise license on tenant creation and connection? Or do think there should be an explicit setting to enable enterprise features at the tenant level?

**Comment by knz** [comment]
At a basic level we're evolving crdb to offer multi-tenant servers for all deployments, so we'll want the ability to run mon-enterprise tenants.

My intuition is that this can be done using the logic you have implemented here but extend it with an env var that accepts a license and validates it upon process initialization (eg in an init function) and turns it into a boolean fed into the code you wrote already. Any obstacles to this?

**Comment by mwang1026** [comment]
My 2c: MT is right now for CockroachCloud only. If in the future we want to evolve the licensing story to allow non-enterprise MT deployments we can solve that problem then.

For now, I think (in Piyush's absence) it's fine to be more strict about those checks since the goal right now is to unblock CC Serverless users' access to enterprise features.

I'll leave it to eng to figure out best implementation re: not locking us in against future rolling back of said license check.

Based on ^ I think it's reasonable to check for license upon startup of a tenant.

**Comment by knz** [comment]
ok let us know when you have implemented step 1 as part of this PR

**Comment by JeffSwenson** [comment]
I've changed course to align with knz@'s original suggestion. I added the COCKROACH_TENANT_LICENSE environment variable and check for its presence. I think we should replace the environment variable as soon as there is support in the tenant for reading settings from the host cluster.

**Review by knz — APPROVED** [review]
nice :100: 
LGTM modulo a nit

> I think we should replace the environment variable as soon as there is support in the tenant for reading settings from the host cluster.

Agreed

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69115#-:-Mia7JPjC17jAvusCARF:btpjhlw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @JeffSwenson)

___
*[pkg/util/envutil/env.go, line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69115#-Mia7-9V5j2pTt2J3Eth:-Mia7-9V5j2pTt2J3Eti:b90ebqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e596d27a94adc6e8e967c0d6afc46d389e59d4ed/pkg/util/envutil/env.go#L367)):*
> ```Go
> // TestSetEnv sets an environment variable and the cleanup function
> // resets it to the original value.
> func TestSetEnv(name string, value string) func() {
> ```

if this is meant only for use in tests, you can accept a `testutils.TB` as argument here and use `t.Fatal` instead of `panic` below to get cleaner test errors.

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[pkg/util/envutil/env.go, line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69115#-Mia7-9V5j2pTt2J3Eth:-Miax3Fo8BaAxXMiFnDK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e596d27a94adc6e8e967c0d6afc46d389e59d4ed/pkg/util/envutil/env.go#L367)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

if this is meant only for use in tests, you can accept a `testutils.TB` as argument here and use `t.Fatal` instead of `panic` below to get cleaner test errors.
</blockquote></details>

Done.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/envutil/env.go, line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69115#-Mia7-9V5j2pTt2J3Eth:-Mr-l2kM0zfDYOdbzHlU:b75oodb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e596d27a94adc6e8e967c0d6afc46d389e59d4ed/pkg/util/envutil/env.go#L367)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@knz wait, really? we used to have a pretty strict rule about _not_ importing "testing" in non _test.go files... did that change?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/envutil/env.go, line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69115#-Mia7-9V5j2pTt2J3Eth:-Mr1kMBt-Wjux2YOeOcJ:b4dbbtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e596d27a94adc6e8e967c0d6afc46d389e59d4ed/pkg/util/envutil/env.go#L367)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

@knz wait, really? we used to have a pretty strict rule about _not_ importing "testing" in non _test.go files... did that change? 
</blockquote></details>

I said `testutils.TB`. Jeff just made a mistake and I didn't notice during the review. Let's patch this.

**Pull request merged**
