### PR TITLE
roachpb: use EncodedError in Error

### LINKED ISSUE #54939: roachpb: use cockroachdb/errors.EncodedError inside of internalError
**Is your feature request related to a problem? Please describe.**

roachpb.Error is a wrapper around a number of concrete error types important for the cockroach transactional model. The object can be constructed from any go error. Go errors which are themselves implementations of the relevant concrete errors are properly wrapper for serialization. All other errors, however, are captured as just a string inside of the `roachpb.internalError` struct. The problem with this error is that it represents the errors used to construct it as a string, throwing away all structured information. This further means that any structured information will not be transmitted over the network.

This is not obviously a big problem today. The most important errors to detect programtically (in my opinion) which are today lost are `context.Canceled` and `context.DeadlineExceeded`. However, it may not be so important to detect these errors coming from remote procedure calls as the errors should be reproduced on the client-side as most of these deadlines and cancelations should flow from the client anyway. Unfortunately, there is no gaurantee that the context error will always be checked or that it will be preferred over the returned error from the RPC. In fact, we generally go out of our way to prefer the error being propagated from the call path.

**Describe the solution you'd like**

I'd like to see the `roachpb.internalError` adopt the `cockroachdb/errors.EncodedError` for its representation of the error used to construct it (when not a roachpb defined error). This would allow structure to be preserved.

**Additional context**

This approach was utilized for `execinfrapb.Error` in https://github.com/cockroachdb/cockroach/pull/37121.

### PR DESCRIPTION
**Pull request by tbg**
roachpb: use EncodedError in Error

`roachpb.Error` has long been poor to work with. It could only transport
structured errors for a hard-coded enum message (`ErrorDetail`) and had
a complex and circuituous interaction with the standard library's
`error` type: `pErr.GoError()` would return an `error` that was
sometimes just `pErr` itself (hidden behind an identical type); other
times it was an `UnhandledRetryableError` wrapping `pErr`, and then
of course sometimes it would be the structured error from which `pErr`
was created in the first place.

Thanks to `cockroachdb/errors`, there's a much better option around,
namely `errorspb.EncodedError` which has powerful capabilities to
essentially carry any error across RPC boundaries (and notably does so
"out of the box" for protobuf-backed errors) while retaining its
original structure, as long as the error type is known on both sides of
the RPC.

The simplifications that result from this primitive would be enough to
motivate this change in itself, but additionally after this change we
will be able to reliably detect context cancellations, etc, without
relying on error-prone and insecure string matching.

Going into more detail, this commit makes the following changes:

- adds an `EncodedError` to `Error`
- deprecates the following fields on `Error`, which are henceforth
  deduced from the `EncodedError` where present:
  - `transaction_restart`
  - `message`
  - `detail`
  These fields are populated for the time being so that 20.2 nodes
  understand the errors emitted by 21.1 nodes. In 21.2, we can drop
  them all.
- deprecates `(*Error).SetDetail`, which has only one real caller
  anyway (and that caller will be able to replace EncodedError instead
  once 21.2 comes around).
- makes `(*Error).SafeFormat` redact properly based on `EncodedError`
  (yay!), though there's a larger TODO that's left for a follow-up
  change (around the fact that error details can depend on the
  surrounding Error for rendering, particularly relevant when SetTxn
  is called)

We can capitalize on EncodedError before the 21.2 cycle, but this
is left for future PRs.

Fixes #54939.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Re the several initial commits:

> if `Error` has `Equal()` codegen'ed for it, it needs to be present
on `EncodedError` as well, which it isn't.

It should! there's no obstacle against it. I would rather go that route and trim these commits. reflect.DeepEqual is fraught with peril.

Regarding the rest: I see you are keeping the `roachpb.Error` a protobuf message. This blocks you from embedding a  Go `error` field inside. This also prevents you from implementing the `Cause()` / `Unwrap()` interface. That makes me sad somewhat. Is this really what we want?

I could see a world where the `roachpb.Error` *message* is renamed `roachpb.ErrorProto`, and `roachpb.Error` becomes a regular go struct, which embeds its details as an `error`, and only translate to/from `roachpb.ErrorProto` at RPC boundaries. What do you think?

> Reviewed 7 of 7 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 14 of 14 files at r5, 6 of 6 files at r6, 9 of 9 files at r7, 1 of 1 files at r8, 16 of 17 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-:-MLwuO4_9ohC_Y0VcQaP:bh0gv9f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/ccl/backupccl/backup_processor.go, line 227 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLwvVZsBWjWn2LR8Y7O:-MLwvVZsBWjWn2LR8Y7P:bfl2np5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb09a7b8597d48a62fca1c631b2c89e14a001a20/pkg/ccl/backupccl/backup_processor.go#L227)):*
> ```Go
> 				rawRes, pErr := kv.SendWrappedWith(ctx, flowCtx.Cfg.DB.NonTransactionalSender(), header, req)
> 				if pErr != nil {
> 					if _, ok := pErr.GetDetail().(*roachpb.WriteIntentError); ok {
> ```

`errors.As`?
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 611 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLww46i4oTU2Bz8G2uW:-MLww46i4oTU2Bz8G2uX:b39ahtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb09a7b8597d48a62fca1c631b2c89e14a001a20/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L611)):*
> ```Go
> 			ctx, abortedErr, roachpb.NormalUserPriority, tc.clock)
> 		return roachpb.NewError(roachpb.NewTransactionRetryWithProtoRefreshError(
> 			abortedErr.String(), tc.mu.txn.ID, newTxn))
> ```

are we comfortable embedding the string, and not the full error object?
___
*[pkg/roachpb/errors.go, line 334 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLwwfIQAv7YC_OkTaeP:-MLwwfIQAv7YC_OkTaeQ:bfl2np5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb09a7b8597d48a62fca1c631b2c89e14a001a20/pkg/roachpb/errors.go#L334)):*
> ```Go
> 	if e.EncodedError != (errorspb.EncodedError{}) {
> 		err := errors.DecodeError(context.Background(), e.EncodedError)
> 		if iface, ok := err.(transactionRestartError); ok {
> ```

`errors.As`?
___
*[pkg/sql/execinfra/processorsbase.go, line 670 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLwwqsq3NAKUqI4YFLC:-MLwwqsq3NAKUqI4YFLD:bfl2np5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb09a7b8597d48a62fca1c631b2c89e14a001a20/pkg/sql/execinfra/processorsbase.go#L670)):*
> ```Go
> 				// TransactionRetryWithProtoRefreshErrors) don't have any uncertainty.
> 				if ure := (*roachpb.UnhandledRetryableError)(nil); errors.As(err, &ure) {
> 					if _, uncertain := ure.PErr.GetDetail().(*roachpb.ReadWithinUncertaintyIntervalError); uncertain {
> ```

`errors.As`?

**Comment by knz** [comment]
https://github.com/cockroachdb/errors/pull/57

**Review by tbg — COMMENTED** [review]
> It should! there's no obstacle against it. I would rather go that route and trim these commits. reflect.DeepEqual is fraught with peril.

I don't mind adding `gogoproto.equal` to `errors`, but I still want to remove all of this useless codegen. It actually makes me uneasy for quite some of the structs that someone should want to compare them. If a struct legit needs to be compared - sure, no problem, but I haven't found that to be true for any of the ones removed in that PR.

> Reviewed 6 of 7 files at r1, 1 of 3 files at r2, 2 of 2 files at r4, 10 of 14 files at r5, 4 of 6 files at r6, 9 of 9 files at r7, 1 of 1 files at r8, 17 of 17 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-:-MLxAk6k1epUdsDME6qf:bghygf9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/ccl/backupccl/backup_processor.go, line 227 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLwvVZsBWjWn2LR8Y7O:-MLx9x7308LmleL-2oxj:b-tbhyb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb09a7b8597d48a62fca1c631b2c89e14a001a20/pkg/ccl/backupccl/backup_processor.go#L227)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`errors.As`?
</blockquote></details>

I want to do a full pass against `GetDetail()` to make it return an `error` (instead of an `ErrorDetail`). Then your error linter will kick in and I'll fix the 5000 other instances of this that aren't captured in this diff. Not in this PR though.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 611 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLww46i4oTU2Bz8G2uW:-MLxABcn66-arKQmHAet:b-bmjlw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb09a7b8597d48a62fca1c631b2c89e14a001a20/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L611)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

are we comfortable embedding the string, and not the full error object?
</blockquote></details>

What do you mean? The message is identical to `String()` at the time of writing. I don't like that we're stuffing it in that way, but it's the old behavior and I don't want to solve all of the paper cuts in this PR. Note that I left a TODO on NewTransactionRetryWithProtoRefreshError about this, curious what you think of it.
___
*[pkg/roachpb/errors.go, line 334 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLwwfIQAv7YC_OkTaeP:-MLxAXDc3JbuQesXDUe3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb09a7b8597d48a62fca1c631b2c89e14a001a20/pkg/roachpb/errors.go#L334)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`errors.As`?
</blockquote></details>

Done.
___
*[pkg/sql/execinfra/processorsbase.go, line 670 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLwwqsq3NAKUqI4YFLC:-MLxAZJlB6z4kmuXoGjD:brrs14f) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb09a7b8597d48a62fca1c631b2c89e14a001a20/pkg/sql/execinfra/processorsbase.go#L670)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`errors.As`?
</blockquote></details>

See other comment, keeping it mechanical for now

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/kv/kvserver/store_send.go, line 247 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLxBCXrESY6YUSbK-MC:-MLxBCXrESY6YUSbK-MD:bpn1lys) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2196b51b919c7f8b1705f612fe590fa9d86bf0/pkg/kv/kvserver/store_send.go#L247)):*
> ```Go
> 			}
> 			t.AppendRangeInfo(ctx, desc, l)
> 			// We have to write `t` back to `pErr` so that it picks up the changes.
> ```

This was made obvious to me through a test failure. I will need to run a full audit (yikes) before merging.
Essentially, we were mutating something returned from `GetDetail()` and expecting that to affect the backing `pErr`. But now with `EncodedError` `GetDetail()` basically makes a fresh copy for you. Which - maybe that is bad and we'll want to look into it for perf reasons, but I still think that pattern remains bad and we need to be explicit about mutating the original `pErr` through it and not through some handle into its innards.

**Review by knz — COMMENTED** [review]
>  don't mind adding gogoproto.equal to errors, but I still want to remove all of this useless codegen

Discussed offline - yes, agreed. However I think we should then have some rule that reflect.DeepEqual should not be used throughout production code, just in tests.

LGTM otherwise - modulo completion of your investigation about interior mutability of the error detail.

> Reviewed 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-:-MLxCbJ7D44s2FeSSfIq:bqwbhod)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 611 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLww46i4oTU2Bz8G2uW:-MLxCXyPCHnrMFkE870L:b-gqqr63) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb09a7b8597d48a62fca1c631b2c89e14a001a20/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L611)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

What do you mean? The message is identical to `String()` at the time of writing. I don't like that we're stuffing it in that way, but it's the old behavior and I don't want to solve all of the paper cuts in this PR. Note that I left a TODO on NewTransactionRetryWithProtoRefreshError about this, curious what you think of it.
</blockquote></details>

Understood thanks.
___
*[pkg/kv/kvserver/store_send.go, line 247 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLxBCXrESY6YUSbK-MC:-MLxCPy01qIKJcIx-EYq:b-ii8pl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2196b51b919c7f8b1705f612fe590fa9d86bf0/pkg/kv/kvserver/store_send.go#L247)):*
> I still think that pattern remains bad and we need to be explicit about mutating the original pErr through it and not through some handle into its innards.

Agreed. Thanks for figuring it out.

**Review by tbg — COMMENTED** [review]
> Discussed offline - yes, agreed. However I think we should then have some rule that reflect.DeepEqual should not be used throughout production code, just in tests.

I am not opposed to that, though it's somewhat orthogonal here. Even if `.Equal` is defined, someone might use `DeepEqual` in production.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-:-MLxDenEAVMNWxQKI2tG:b-c76muy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/kv/kvserver/store_send.go, line 247 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-MLxBCXrESY6YUSbK-MC:-MLxG4SV4OEJVZFAmExy:bm3x41j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad2196b51b919c7f8b1705f612fe590fa9d86bf0/pkg/kv/kvserver/store_send.go#L247)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> I still think that pattern remains bad and we need to be explicit about mutating the original pErr through it and not through some handle into its innards.

Agreed. Thanks for figuring it out.
</blockquote></details>

I did do the audit (at least for the ~40 or so prod callers) and this was the one bad apple.

**Review by knz — APPROVED** [review]
> I am not opposed to that, though it's somewhat orthogonal here

ok works for me!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-:-MLxGJlzAUbB86rZCeQN:b5r4nyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by tbg — COMMENTED** [review]
> Regarding the rest: I see you are keeping the roachpb.Error a protobuf message. This blocks you from embedding a  Go error field inside. This also prevents you from implementing the Cause() / Unwrap() interface. That makes me sad somewhat. Is this really what we want?

I haven't thought this far ahead, but generally speaking I would like that. A separation at the RPC boundaries makes sense and by having a bare struct everywhere else we can avoid the repeated calls to `DecodeError` that the current implementation incurs. I'll save it for another PR, though. Also, I might be missing something, but I don't see why we can't implement `Cause` and `Unwrap` as is.

I've also started thinking about pulling the protos apart a little bit. Ideally, you would have a `kvpb` package that has all the possible structured errors that `kv` can emit. I think there is a big migration snag here though, in that the current errors would need to be kept in two locations for the time being, which I don't love. Given that and the limited mandate for making something happen here, I'll probably stop short of that, especially since a lot of actual code cleanup remains to be done. But I wanted to dream at least for a second!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-:-MLxGEwc8voSpa6ek-5f:b7pk8ck)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — COMMENTED** [review]
>  I don't see why we can't implement Cause and Unwrap as is.

The only way to implement them in your current framework would be to re-instantiate an `error` every time  they are called, via `Decode`. This is rather expensive - these functions are called all over the place in error predicates.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56603#-:-MLxQqYo7jGKUhrjrUBG:blnqbv9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

**Review by knz — APPROVED** [review]
> Reviewed 14 of 14 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56603)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @tbg)

**Comment by tbg** [comment]
bors r=knz

**Pull request merged**
