### PR TITLE
sql/row: reduce allocations in initialization functions

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/row: reduce allocations initializing txnKVFetcher and txnKVStreamer

The `kvBatchFetcherHelper` no longer implements the `NextBatch` method
for the `txnKVFetcher` and `txnKVStreamer`. The latter two implement
this method themselves, eliminating an allocation of the `nextBatch`
closure. The `kvBatchFetcherHelper` has been renamed to `kvBatchMetrics`
now that its only concern is recording and providing metrics.

Release note: None

#### sql/row: reduce allocations in newTxnKVFetcher

Two heap-allocated integers are now allocated together in a two-field
struct.

Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
```
name                                        old time/op    new time/op    delta
EndToEnd/kv-read/vectorize=off/Prepared-16     141µs ± 1%     140µs ± 1%  -0.58%  (p=0.004 n=9+9)
EndToEnd/kv-read/vectorize=on/Prepared-16      147µs ± 1%     146µs ± 1%  -0.58%  (p=0.005 n=10+10)
EndToEnd/kv-read/vectorize=on/Simple-16        216µs ± 1%     215µs ± 1%    ~     (p=0.218 n=10+10)
EndToEnd/kv-read/vectorize=off/Simple-16       209µs ± 2%     209µs ± 1%    ~     (p=0.315 n=10+9)

name                                        old alloc/op   new alloc/op   delta
EndToEnd/kv-read/vectorize=on/Simple-16       31.3kB ± 0%    31.2kB ± 0%  -0.30%  (p=0.000 n=10+10)
EndToEnd/kv-read/vectorize=on/Prepared-16     19.4kB ± 0%    19.4kB ± 0%    ~     (p=1.000 n=10+10)
EndToEnd/kv-read/vectorize=off/Simple-16      31.6kB ± 0%    31.6kB ± 0%    ~     (p=0.287 n=10+9)
EndToEnd/kv-read/vectorize=off/Prepared-16    20.6kB ± 0%    20.6kB ± 0%    ~     (p=0.815 n=9+9)

name                                        old allocs/op  new allocs/op  delta
EndToEnd/kv-read/vectorize=on/Prepared-16        194 ± 0%       192 ± 0%  -1.03%  (p=0.002 n=8+10)
EndToEnd/kv-read/vectorize=on/Simple-16          287 ± 0%       285 ± 0%  -0.80%  (p=0.000 n=10+10)
EndToEnd/kv-read/vectorize=off/Prepared-16       186 ± 0%       185 ± 0%  -0.54%  (p=0.000 n=9+9)
EndToEnd/kv-read/vectorize=off/Simple-16         273 ± 0%       272 ± 0%  -0.37%  (p=0.001 n=8+9)
```

**Review by yuzefovich — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137525#-:-OEFsxKY4rnRWk90aYe6:b-g2a5fb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137525#-:-OEFwM541Wf82WQzqyge:b-8gk8uj)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
