### PR TITLE
cli: enhance the `cockroach connect` command

### PR DESCRIPTION
**Pull request by knz**
Puts pieces together for #60632. 

See individual commits for details.

Release justification: low risk, high benefit changes to existing functionality

### CODE REVIEW

**Comment by knz** [comment]
@itsbilal this PR is not necessarily meant for merging separately from yours. Feel free to absorb it into #60766 if it makes your life easier. But I need to start from there to connect the `start` command to the logic here.

**Review by itsbilal — APPROVED** [review]
:lgtm: thanks!

> Reviewed 5 of 5 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60854#-:-MUQ-pEV-D3tZ38vNXxu:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl)

**Review by aaron-crl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60854)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/base/config.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60854#-MUQ3QfF8KhufsJzsucc:-MUQ3QfF8KhufsJzsucd:bjxh4xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/01fd091148b88a5a5d4d135bf06f0c346388f74e/pkg/base/config.go#L172)):*
> ```Go
> 	// InitToken is a shared initialization token for generating TLS certificates
> 	// across multiple nodes.
> 	InitToken string
> ```

Looks like this might clobber the InitToken in the Config struct. Is that ok?

**Comment by itsbilal** [comment]
___
*[pkg/base/config.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60854#-MUQ3QfF8KhufsJzsucc:-MUQcc7l1ZrOG-XqjPgu:bpza692) ([raw file](https://github.com/cockroachdb/cockroach/blob/01fd091148b88a5a5d4d135bf06f0c346388f74e/pkg/base/config.go#L172)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Looks like this might clobber the InitToken in the Config struct. Is that ok?
</blockquote></details>

That got moved to `startCtx` as it is probably a more appropriate place for it anyway.

**Review by aaron-crl — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60854#-:-MUTUJ7I242d8iSXkNZk:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/base/config.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60854#-MUQ3QfF8KhufsJzsucc:-MUTULnW173XVoRO76H2:bticcva) ([raw file](https://github.com/cockroachdb/cockroach/blob/01fd091148b88a5a5d4d135bf06f0c346388f74e/pkg/base/config.go#L172)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

That got moved to `startCtx` as it is probably a more appropriate place for it anyway.
</blockquote></details>

Thanks! I missed that.

**Review by aaron-crl — APPROVED** [review]
Thank you! :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60854#-:-MUdH4g-59RWwIB9bb4c:bcjrjzl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal)

**Comment by knz** [comment]
TFYR!

I even added a (preliminary) unit test using TCL that exercises the new `connect` command.

bors r=aaron-crl,itsbilal

**Pull request merged**
