### PR TITLE
clusterversion: remove old gates

### PR DESCRIPTION
**Pull request by RaduBerinde**
Remove 24.3 gates and corresponding code that is now obsolete.

Epic: REL-1292
Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: for the storage changes and the kvserver changes related to V24_3_UseRACV2*

> Reviewed 11 of 69 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136545#-:-ODSXhxABpovZU0JkZ4C:b-xsa8y)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons, @csgourav, @jeffswenson, @rytaft, and @shailendra-patel)

**Review by rail — APPROVED** [review]
🔥

**Review by celiala — APPROVED** [review]
LGTM - Thank you!  :pray: :100: 

> Reviewed 67 of 69 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136545#-:-ODgAku80LHLio-ux0_E:b4zsdt1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons, @csgourav, @jeffswenson, @rytaft, and @shailendra-patel)

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
