### PR TITLE
 sql: run schema changes after CREATE TABLE in txn

### PR DESCRIPTION
**Pull request by vivekmenezes**
Includes a commit from #25362 and should be reviewed after that change.

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCA_aVEYeGz94rLLEdS-r2-135:-LCe5J8hDaJXVKGm7tPh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb08c2a516cc7b1cfa267e9883e7f3bdd41982ca/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L135)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This data should be different from the first CREATE just so we can verify it's indeed the second CREATE that is being queried.
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCA_aVEYeGz94rLLEdS-r2-159:-LCe5L58AJrOqygHSGSJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb08c2a516cc7b1cfa267e9883e7f3bdd41982ca/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L159)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

same: change the data here
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCA_aVEYeGz94rLLEdS-r2-177:-LCe5Oc0-7jTl531eQIR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb08c2a516cc7b1cfa267e9883e7f3bdd41982ca/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L177)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I would like to see a few more tests in the error case to make sure we handle those correctly:

- CREATE TABLE; add some data, add unique index that fails due to uniqueness violations
- CREATE TABLE; add computed column that fails due to an error during computation (like a divide by 0)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25410)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCA_aVEYeGz94rLLEdS-r2-177:-LCe87a635mO-OUNuQSL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb08c2a516cc7b1cfa267e9883e7f3bdd41982ca/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L177)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25410)*

**Comment by mjibson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/backfill.go, line 621 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeOQGs6YYwl7ZBOnit:-LCeOQGs6YYwl7ZBOniu:b3mq71q) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/backfill.go#L621)):*
> ```Go
> 	}
> 
> 	if len(tableDesc.Mutations) == 0 {
> ```

nit: this block can be removed

---

*[pkg/sql/backfill.go, line 625 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeP9EvB4Y4s3INq6oS:-LCeP9EvB4Y4s3INq6oT:b-g051td) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/backfill.go#L625)):*
> ```Go
> 	}
> 
> 	for len(tableDesc.Mutations) > 0 {
> ```

Why does this line need to be here? Can we just range over tableDesc.Mutations? I don't see how this loop would ever run more than once.

---

*[pkg/sql/table.go, line 458 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeJXQF5Wde0Ldfl0PF:-LCeJXQF5Wde0Ldfl0PG:bonn4x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/table.go#L458)):*
> ```Go
> 
> func (tc *TableCollection) isCreatedTable(id sqlbase.ID) bool {
> 	if tc.createdTables == nil {
> ```

No need for this if block. Code is clearer without it.

---

*[pkg/sql/table.go, line 511 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeMrv96rxCd6Z9_Zm3:-LCeMrv96rxCd6Z9_Zm4:bcgjvre) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/table.go#L511)):*
> ```Go
> 	dbID sqlbase.ID, tn *tree.TableName, required bool,
> ) (refuseFurtherLookup bool, table *sqlbase.TableDescriptor, err error) {
> 	// Walk latest to earliest.
> ```

Why this change?

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCA_aVEYeGz94rLLEdS-r2-138:-LCeG4BsDY48mVgYOtMA:bs75l5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb08c2a516cc7b1cfa267e9883e7f3bdd41982ca/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L138)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I don't believe that's necessary right?
</blockquote></details>

SQL can return data in any order if an ORDER BY is not specified. See https://github.com/cockroachdb/cockroach/issues/24223. Or you can use the rowsort flag in the logictest.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeGmCX6m8fPxVCzW65:-LCeGmCX6m8fPxVCzW66:b-fk1twb) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L235)):*
> ```
> 
> statement ok
> COMMIT
> ```

You can run a `COMMIT` after a statement with an error? I thought you had to run ROLLBACK in this case. TIL.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25410)*

**Comment by vivekmenezes** [comment]
TFTR! Ready for another viewing. Thanks

---

Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/sql/backfill.go, line 621 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeOQGs6YYwl7ZBOnit:-LCiUmgB89BHTlA_dog0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/backfill.go#L621)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

nit: this block can be removed
</blockquote></details>

Done.

---

*[pkg/sql/backfill.go, line 625 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeP9EvB4Y4s3INq6oS:-LCiVCQiASMnyRSS_Ydi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/backfill.go#L625)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why does this line need to be here? Can we just range over tableDesc.Mutations? I don't see how this loop would ever run more than once.
</blockquote></details>

Done.

---

*[pkg/sql/table.go, line 458 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeJXQF5Wde0Ldfl0PF:-LCiZ1kVAz9YScGB9u2M:b-63d84k) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/table.go#L458)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

No need for this if block. Code is clearer without it.
</blockquote></details>

Good point. I didn't know a nil map was readable!

---

*[pkg/sql/table.go, line 511 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeMrv96rxCd6Z9_Zm3:-LCidBJ63wULAt6fSZWW:b-e9lczy) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/table.go#L511)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

I've added a comment to explain the need to traverse both uncommitted databases and tables in the reverse order. This is tested i this PR.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCA_aVEYeGz94rLLEdS-r2-135:-LCie3utBf-Rl6yDbckc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb08c2a516cc7b1cfa267e9883e7f3bdd41982ca/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L135)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCA_aVEYeGz94rLLEdS-r2-138:-LCi_B3SCygMsz76AMVC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb08c2a516cc7b1cfa267e9883e7f3bdd41982ca/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L138)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

SQL can return data in any order if an ORDER BY is not specified. See https://github.com/cockroachdb/cockroach/issues/24223. Or you can use the rowsort flag in the logictest.
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCA_aVEYeGz94rLLEdS-r2-159:-LCi_CSx-cS-9-rLDfNZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb08c2a516cc7b1cfa267e9883e7f3bdd41982ca/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L159)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCA_aVEYeGz94rLLEdS-r2-162:-LCi_DXqDIErgWun36jl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb08c2a516cc7b1cfa267e9883e7f3bdd41982ca/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L162)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

ORDER BY, ditto below
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeGmCX6m8fPxVCzW65:-LCiU7tT0my913sxW66I:balau5) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L235)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

You can run a `COMMIT` after a statement with an error? I thought you had to run ROLLBACK in this case. TIL.
</blockquote></details>

In order to be postgres compliant a COMMIT after a statement that returns an error doesn't return an error (apparently it returns an error code somewhere else in the protocol). Anyway to make this more readable I've changed all the COMMIT following an error to ROLLBACK.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-:-LCidwhm-tAkRwavJzgQ:br0zmb)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/schema_change_in_txn, line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-LCeGmCX6m8fPxVCzW65:-LCjPKbd8qKh48OMDuiE:b-hxhhlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/256826e25a1fe95d13f21adb924b864886952872/pkg/sql/logictest/testdata/logic_test/schema_change_in_txn#L235)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

In order to be postgres compliant a COMMIT after a statement that returns an error doesn't return an error (apparently it returns an error code somewhere else in the protocol). Anyway to make this more readable I've changed all the COMMIT following an error to ROLLBACK.
</blockquote></details>

Oh neat. If that's the case I think it should be changed back to COMMIT to verify that behavior otherwise we could accidentally regress and COMMIT even in the face of an error.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25410#-:-LCjQEMBDEF54il2RLhM:bnfp4nl)*

**Pull request merged**
