### PR TITLE
sql: reuse TableCollection.tables between statements

### PR DESCRIPTION
**Pull request by petermattis**
```
name                  old time/op    new time/op    delta
KV/Scan/SQL/rows=1-8     181µs ± 1%     181µs ± 1%    ~     (p=0.796 n=9+10)

name                  old alloc/op   new alloc/op   delta
KV/Scan/SQL/rows=1-8    21.1kB ± 0%    20.5kB ± 0%  -3.04%  (p=0.000 n=9+10)

name                  old allocs/op  new allocs/op  delta
KV/Scan/SQL/rows=1-8       283 ± 0%       282 ± 0%  -0.35%  (p=0.000 n=10+9)
```

### CODE REVIEW

**Comment by petermattis** [comment]
I'm not sure this is worthwhile. On the other hand, almost every query touches at least 1 table and many touch exactly 1.

**Comment by vivekmenezes** [comment]
The table descriptors are already allocated within tableVersionState so the better thing to do here is to change the type of tables to []*sqlbase.TableDescriptor . After that it might be worth using 
```tc.tables = tc.tables[:0]```  in releaseTables instead of assigning nil to it.

**Comment by petermattis** [comment]
> The table descriptors are already allocated within tableVersionState so the better thing to do here is to change the type of tables to []*sqlbase.TableDescriptor. 

I'm nervous about making this change as I'm not sure that the users of `getTableVersion` are strict about not modifying the returned `*TableDescriptor`. Let me explore this in a separate PR.

> After that it might be worth using tc.tables = tc.tables[:0] in releaseTables instead of assigning nil to it.

Ah, that's a good point. No need for the 1 element buffer we can just reuse the already allocated space for `tc.tables` when resetting. Done.

**Comment by vivekmenezes** [comment]
I can make that PR and send it to you for review. This PR is good to merge

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17130#-:-KpVQBG79_ld9a0m90rh:b-akyvu0)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17130#-:-KpVQNZWIvw3CbwOYS25:bnfp4nl)*

**Pull request merged**
