### PR TITLE
docs: Add proto deletion ban to style guide

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6565)

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[STYLE.md, line 70 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6565#-KH6n1LRcOPq-2sFEUah:-KH6n1LRcOPq-2sFEUai:-1619731973) ([raw file](https://github.com/cockroachdb/cockroach/blob/978b34bed7ad0fda3c74119eef0cae525d413e57/STYLE.md#L70)):*
Open Question: maybe just no exceptions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6565)*

**Comment by RaduBerinde** [comment]
Instead of the OBSOLETE_ or the bytes thing, can we recommend using `reserved` for the id? Seems cleaner to me if it's the same functionally. I believe it is, but we should get confirmation from others.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6565#-:-KH7okvK3R8EYhVBFINC:-1404173977)*

**Comment by bdarnell** [comment]
Cool, I didn't know the `reserved` option had been added. That's probably better in most cases, but if we are deleting a field that was ever written to disk, renaming is a little better: this ensures that the field can be printed correctly if we come across any old data that still contains it. 

I would mention one exception to the type rule, that a `message` type may freely be changed to `bytes`. (but other than that I prefer the no-exceptions r2 to the version in r1)

LGTM

**Comment by dt** [comment]
Done.

**Comment by RaduBerinde** [comment]
LGTM

**Comment by nvanbenschoten** [comment]
LGTM. I didn't know about `reserved` either, but I'm glad to see it's been added.

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> LGTM</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[STYLE.md, line 62 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6565#-KHE8YTgy6-lrIqEB4Xx:-KHE8YTgy6-lrIqEB4Xy:1317744747) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3bd20c30b43fbf55a9f7414a1408c21e866d01e/STYLE.md#L62)):*
> ```Markdown
> See Google's [suggested rules](https://developers.google.com/protocol-buffers/docs/proto#updating)
> when modifying protos, namely:
>   * Never change the type in place
> ```

`s/type/type of a field/`

---

*[STYLE.md, line 66 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6565#-KHE8_Tr50-nsyoazqn5:-KHE8_Tr50-nsyoazqn6:-1380919913) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3bd20c30b43fbf55a9f7414a1408c21e866d01e/STYLE.md#L66)):*
> ```Markdown
>   * As an alternative to replacing a field with `reserved`, prefixing the name with `OBSOLETE_`
>   can be used to signal deprecation (while still allowing printing in debugging, etc).
>   When doing so, it is safe to change the type of an embedded message to `bytes`,
> ```

Seems like this is a contradiction of the absolute stance of rule #1. Maybe move the exception up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6565#-:-KHE8gkqg659A6JAsGhn:1413730718)*

**Comment by tamird** [comment]
what's the status of this?

**Pull request closed without merging**
