### PR TITLE
kvnemeses: add support for testing client.Txn.CommitInBatch

### PR DESCRIPTION
**Pull request by danhhz**
This should exercise the 1pc fastpath as well as parallel commits.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
@nvanbenschoten this is occasionally flaking because the txn writes are showing up but it considers that invalid because the transaction got an error of type "TransactionStatusError: already committed (REASON_TXN_COMMITTED)". Thoughts on what's the right thing to do here?

```
  db.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
    txn.Put(ctx, /Table/50/"e14094f1", v-15) // nil
    b := &Batch{}
    b.Get(ctx, /Table/50/"0b10b00b") // (nil, TransactionStatusError: already committed (REASON_TXN_COMMITTED))
    b.Get(ctx, /Table/50/"0b10b00b") // (nil, TransactionStatusError: already committed (REASON_TXN_COMMITTED))
    txn.CommitInBatch(ctx, b) // TransactionStatusError: already committed (REASON_TXN_COMMITTED)
    return nil
  }) // TransactionStatusError: already committed (REASON_TXN_COMMITTED)
```

**Comment by nvanbenschoten** [comment]
Could you check whether the transaction has performed any retries (is in epoch > 0)? We don't expect to see that error, so you may be seeing a bug.

**Comment by danhhz** [comment]
Looks like no retries: `txn.Epoch()` is 0

**Comment by danhhz** [comment]
Rebased this on top of #44608. @nvanbenschoten this is ready for a look

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44229#-:-M-GZdI43w1wJAEboXN2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by danhhz** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
