### PR TITLE
sql: assign incremental OIDs to builtin functions

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
With UDFs being introduced, getting OIDs by hashing on function
signature could cause conflicts. In this commit, fixed OIDs are
assigned to builtin functions during init time.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: with some questions

are the OIDs deterministic? If so, should we make them stable? cc @rafiss this is a change you should know about. 

> Reviewed 6 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85340#-:-N8PoSaz3R8Qras1fJxl:bi1t3ms)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/sql/sem/builtins/builtins.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85340#-N8Pp0EQ19oAXAotElp0:-N8Pp0EQ19oAXAotElp1:bumejji) ([raw file](https://github.com/cockroachdb/cockroach/blob/321d18c33b5917a0b497ed43e5a9192afdddc1e7/pkg/sql/sem/builtins/builtins.go#L178)):*
> ```Go
> 		if builtinFuncOIDCnt > oidext.CockroachPredefinedOIDMax {
> 			panic(
> 				fmt.Sprintf(
> ```

`errors.AssertionFailedf`?

**Comment by chengxiong-ruan** [comment]
@ajwerner I like this question. The OIDs are deterministic if no overloads are added in the future. I saw we have a bunch of builtin functions are unimplemented but has issues tracking them. So if the new overloads got construct somewhere in the middle of current builtin functions herd, OIDs would change :( One thing we could do is to add a test which breaks if max builtin OID changed, and have another test to assert the function name with maximum OID. But I don't know how necessary this would be since we won't reference builtin functions by OID in the future.

**Comment by ajwerner** [comment]
Another thing we could do -- which would be painful initially -- would be to have a giant list of oids for each builtin and if you want to add a new builtin you have to add new entries.

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/sem/builtins/builtins.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85340#-N8Pp0EQ19oAXAotElp0:-N8Pv_gX6-pd5pp4ugwn:b5xmra6) ([raw file](https://github.com/cockroachdb/cockroach/blob/321d18c33b5917a0b497ed43e5a9192afdddc1e7/pkg/sql/sem/builtins/builtins.go#L178)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`errors.AssertionFailedf`?
</blockquote></details>

good point. fixed.

**Comment by chengxiong-ruan** [comment]
> Another thing we could do -- which would be painful initially -- would be to have a giant list of oids for each builtin and if you want to add a new builtin you have to add new entries.

Good idea! for now, I added the test I mentioned with a comment explaining what's implication of if the test failed. Also added a TODO for what you suggested (I like it more).

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
