### PR TITLE
release-23.1: roachtest: randomly run with runtime assertions by default

### LINKED ISSUE #86678: enable running non-perf roachtests with runtime assertions (crdb_test build tag)
Recent PR [1] added the ability to run roachtests with runtime assertions enabled. TC will now produce `cockroach-short-ea`. This binary can be staged (instead of `cockroach`) with the default probability of .5 by invoking `maybeUseBuildWithEnabledAssertions`.

Let's try to enable this for all non-perf roachtests and conditionally opt out those if the assertions result in longer timeouts.

[1] https://github.com/cockroachdb/cockroach/pull/86625

Jira issue: CRDB-18869

### PR DESCRIPTION
**Pull request by DarrylWong**
Backport 2/2 commits from #111949.

/cc @cockroachdb/release

Release justification: test-only changes

---

This changes the semantics of `t.Cockroach()` to use a binary with runtime assertions enabled by default. Performance tests (indicated by the benchmark TestSpec) will be able to continue using the standard binary, without runtime assertions or metamorphic constants, as usual.

This commit also opts-out other tests that cannot easily be run with runtime assertions or metamorphic constants enabled, most often due to timeouts or metamorphic constant incompatibility.

Resolves #86678.
Informs #94986.

Epic: none

Release note: None

### CODE REVIEW

**Comment by DarrylWong** [comment]
[0.1 select probability test run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12539342?hideProblemsFromDependencies=false&hideTestsFromDependencies=false)

**Review by renatolabs — APPROVED** [review]
We'll need to delete the `lint:ignore SA1019 deprecated` comment since 23.1 is still on Go 1.19.

Thanks for backporting!

**Comment by yuzefovich** [comment]
Should we hold off on backporting this for now? Let's give it a couple of weeks on master and 23.2 to stabilize first (ideally, we would have done this only on master) so that we can shake issues like #113816 out.

**Comment by renatolabs** [comment]
> ideally, we would have done this only on master

Yep, we can wait longer; it was my idea to backport given that we had run all tests extensively during development of this feature. Let's wait until next week to merge this backport.

**Pull request merged**
