### PR TITLE
vendor: bump Pebble to bd92c6f1b074

### PR DESCRIPTION
**Pull request by bananabrick**
2dde123d pebble: Make the table cache shareable among stores
0c4d6563 testdata: remove values from deletes
Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70166#-:-MjWEfcyDpESUTb7B6tD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by bananabrick** [comment]
TFTR!

bors r+

**Pull request merged**
