### PR TITLE
sql: new heuristic-based completion engine

### LINKED ISSUE #37355: cli: tab complete in cockroach CLI
I'd like to be able to tab complete in the CLI terminal so that I can save time as I'm working with my database. 

Postgres offers tab completion.

```
root@cockroachdb-public:26257/defaultdb> use reg
tab completion not supported; append '??' and press tab for contextual help

use registration;
SET

Time: 464.478µs
```
Epic: CRDB-12860

Jira issue: CRDB-6345

### PR DESCRIPTION
**Pull request by knz**
This PR extends the server-side completion logic available under SHOW COMPLETIONS.

Epic: CRDB-22182
Fixes #37355.
Intended for use together with #86457.

The statement now returns 5 columns: completion, category, description, start, end.
This change is backward-compatible with the CLI code in previous versions, which was not checking the number of columns.

It works roughly as follows:

1. first the input is scanned into a token array.

2. then the token array is translated to a *sketch*: a string with the
   same length as the token array, where each character corresponds to an
   input token and an extra character indicating where the completion was
   requested.

3. then the completion rules are applied in sequence. Each rule
   inspects the sketch (and/or the token sequence) and decides whether
   to do nothing (skip to next rule), or to run some SQL which will
   return a batch of completion candidates.

   Each method operates exclusively on the token sequence, and does
   not require the overall SQL syntax to be valid or complete.

Also, the completion engine executes in a streaming fashion, so that
there is no need to accumulate all the completion candidates in RAM
before returning them to the client. This prevents excessive
memory usage server-side, and offers the client an option to cancel
the search once enough suggestions have been received.

Code organization:

- new package `sql/compengine`: the core completion engine, also
  where sketches are computed.

  Suggested reading: `api.go` in the new package.

- new package `sql/comprules`: the actual completion
  methods/heuristics, where sketches are mapped into SQL queries
  that provide the completion candidates.

  Suggested reading: the test cases under `testdata`.

Some more words about sketches:

For example, `SHOW COMPLETIONS AT OFFSET 10 FOR 'select myc from
sc.mytable;'` produces the sketch `"ii'ii.i;"` where `i` indicates an
identifier-like token and `'` indicates the cursor position.

The purpose of the sketch is to simplify the pattern matching
performed by the completion heuristics, and enables the application of
regular expressions on the token sequence.

For example, a heuristic to complete schema-qualified relations in
the current database, or a database-qualified relation, would use
the regexp `[^.;]i\.(['_]|i')`: an identifier not following a
period or a semicolon, followed by a period, followed by the
completion cursor (with the cursor either directly after the period
or on an identifier after the period).

Supersedes #45186.

### CODE REVIEW

**Comment by knz** [comment]
@rickystewart when you get a chance (NOT URGENT) could you help with this?

I've defined a new generator rule in pkg/sql/scanner that generates `token_names_test.go`.

Because it's generated, I'm not adding it to the `srcs` in the `go_test()` invocation.

However every time I run `dev generate bazel`, bazel/gazelle auto-adds it to the `srcs` list. Then if I run `generate go` the build starts failing because the file exists both in my work tree and in the sandbox.

Do you know how I can prevent `dev generate bazel` from adding the generated file to `srcs`?

**Comment by rickystewart** [comment]
> Do you know how I can prevent dev generate bazel from adding the generated file to srcs?

Yes -- add a comment to `BUILD.bazel` (probably the one in your package subdirectory) like `# gazelle:exclude token_names_test.go`.

**Comment by knz** [comment]
thank you!

**Comment by knz** [comment]
@rickystewart hi, for when you have time (NOT URGENT), this PR could use some help:

There is a new generated file in sql/scanner (token_names_test.go). 
The linter is now complaining that it cannot build/lint the code because this generated file is missing.

How can I add the generation of this file to the dependencies for the linter?

**Comment by knz** [comment]
Oh nvm, found it -- it's because I forgot to update the Makefile.

**Comment by knz** [comment]
This is now rebased, with more tests added, ready for review.

**Review by rytaft — COMMENTED** [review]
Very cool! I just looked at the second commit (the one that updates the optimizer)

> Reviewed 27 of 27 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-:-NIXuKFlBMqEz9jRk_XB:bg8nrc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @ZhouXing19)

___
*[`pkg/sql/opt/exec/factory.opt` line 730 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NIXrhOg9tRwWKg6zl_S:-NIXrhOg9tRwWKg6zl_T:bm6h474) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed6b0cee635df01c7cae2caaff77d57eb2b41887/pkg/sql/opt/exec/factory.opt#L730)):*
> ```
> define ShowCompletions {
>     Command *tree.ShowCompletions
> }
> ```

I think this needs to go to the end of this file to avoid causing problems with gists (see the comment on line 39 of plan_gist_factory.go)
___
*[`pkg/sql/opt/exec/execbuilder/statement.go` line 321 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NIXrKac65344unlDqtR:-NIXrKad6tou6vdxHO3l:b5k8fqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed6b0cee635df01c7cae2caaff77d57eb2b41887/pkg/sql/opt/exec/execbuilder/statement.go#L321)):*
> ```Go
> 		return execPlan{}, err
> 	}
> 	// ControlSchedules returns no columns.
> ```

nit: update comment
___
*[`pkg/sql/opt/exec/explain/testdata/gists` line 1012 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NIXtVq4Bdn6zoFgj0YE:-NIXtVq4Bdn6zoFgj0YF:b-943e9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed6b0cee635df01c7cae2caaff77d57eb2b41887/pkg/sql/opt/exec/explain/testdata/gists#L1012)):*
> ```
> 
> # cancelQueriesOp
> gist-explain-roundtrip
> ```

Can you please add a test in this file for SHOW COMPLETIONS and make sure that none of these other tests change? Thank you!

**Review by ZhouXing19 — APPROVED** [review]
This is so COOL! :lgtm_strong: Thanks for adding such comprehensive tests as well.
Most of my comments are just for nits.

> Reviewed 8 of 8 files at r1, 27 of 27 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 23 of 23 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-:-NI_yowQ6yz8yX-cmKgK:b-ftl4k5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/sql/conn_executor_exec.go` line 2007 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_xjfq69j4wr_g-19Q:-NI_xjfq69j4wr_g-19R:b-ypvf1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/conn_executor_exec.go#L2007)):*
> ```Go
> ) error {
> 	res.SetColumns(ctx, colinfo.ShowCompletionsColumns)
> 	log.Warningf(ctx, "COMPLETION GENERATOR FOR: %+v", *n)
> ```

I'm a bit concerned about the usage of the internal executor here (see https://github.com/cockroachdb/cockroach/issues/91004 if you're curious). Could you add a comment: 
```
TODO(janexing): better bind the internal executor with the txn.
```
Thanks!
___
*[`pkg/sql/compengine/sketch.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_on7--UoXyXoSR0os:-NI_on7--UoXyXoSR0ot:bpl3g30) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/compengine/sketch.go#L54)):*
> ```Go
> 	var buf strings.Builder
> 	if offset < int(tokens[0].Start) {
> 		buf.WriteByte('_')
> ```

nit: change it to `buf.WriteByte(byte(MarkCursorInSpace))`
___
*[`pkg/sql/compengine/sketch.go` line 76 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_cmOa7VhY5xNZHkiQ:-NI_cmOa7VhY5xNZHkiR:b-ox48ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/compengine/sketch.go#L76)):*
> ```Go
> 
> 	// Requested offset at or beyond EOF.
> 	if cursorPosition == 0 && offset >= int(tokens[len(tokens)-1].Start) {
> ```

nit: iiuc, the last token is always the EOF, so the start and the end indexes are the same. It may be easier to understand if we have ` >= nt(tokens[len(tokens)-1].End)`.
___
*[`pkg/sql/compengine/sketch.go` line 82 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_dI_XCuGWaKs4hVI0:-NI_dI_XCuGWaKs4hVI1:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/compengine/sketch.go#L82)):*
> ```Go
> 		// outside of the string, so that indexing using them is always
> 		// possible.
> 		offset = int(tokens[len(tokens)-1].Start)
> ```

ditto
___
*[`pkg/sql/compengine/sketch.go` line 144 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_or14DxpyBbRbj7B-:-NI_or14DxpyBbRbj7B0:b-84q7ts) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/compengine/sketch.go#L144)):*
> ```Go
> 			pos, len(sketch), sketch)
> 	}
> 	if sketch[pos] != '_' && sketch[pos] != '\'' {
> ```

nit: change it to `if sketch[pos] != MarkCursorInSpace && sketch[pos] != MarkCursorInToken `
___
*[`pkg/sql/comprules/rules.go` line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_qYckD1929-s4sUKr:-NI_qYckD1929-s4sUKs:b836zdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/comprules/rules.go#L156)):*
> ```Go
> 
> 	c.Trace("completing for %q (%d,%d)", prefix, start, end)
> 	// TODO(knz): use the comment system instead of crdb_internal.
> ```

Just out of curiosity -- could you say more about the "comment system"?
___
*[`pkg/sql/comprules/rules.go` line 174 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_riJE0GeZYmkVz5sw:-NI_riJE0GeZYmkVz5sx:bhbfec5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/comprules/rules.go#L174)):*
> ```Go
> 
> // A database name can only occur after a keyword or a comma (,).
> var compDbRe = regexp.MustCompile(`i(i'|_)|,(['_]|i')`)
> ```

nit: For this regex, seems that sketches `,'`, `,_` and `,i` also match. Is this expected? Should we ask for an identifier token at the beginning?
___
*[`pkg/sql/compengine/sketch_test.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_Vauo2-wX4GPyw7n0:-NI_Vauo2-wX4GPyw7n1:b-msi5hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/compengine/sketch_test.go#L54)):*
> ```Go
> 			fmt.Fprintln(tw, "--")
> 			c := completions{tokens: tokens, sketch: sketch, queryTokIdx: pos}
> 			for i := -2; i <= 2; i++ {
> ```

nit: could you add a comment for this? IIUC we're printing out the token corresponding to the current cursor, and also its surrounding tokens.
___
*[`pkg/sql/completions.go` line 41 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NIYs4C_4Mg9RDOLIhHI:-NIYs4C_4Mg9RDOLIhHJ:bl5gei) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/completions.go#L41)):*
> ```Go
> 	txn := params.p.Txn()
> 	queryIterFn := func(ctx context.Context, opName string, stmt string, args ...interface{}) (sqlutil.InternalRows, error) {
> 		return ie.QueryIteratorEx(ctx, opName, txn,
> ```

We can just use `params.p.QueryIteratorEx()` here.
`initInternalExecutor()` is expected to be used only in `planner.WithInternalExecutor()` or query/exec functions such as `planner.ExecEx()`. 
___
*[`pkg/sql/completions_test.go` line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NIYo65l-WtXyX65Yawz:-NIYo65l-WtXyX65Yax-:baxcs4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/fabe0a626c544e1e67dfd18a3a9348dcfbfa9cfb/pkg/sql/completions_test.go#L1)):*
> ```Go
> // Copyright 2022 The Cockroach Authors.
> ```

nit: We can remove this file.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87606)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @ZhouXing19)

___
*[`pkg/sql/conn_executor_exec.go` line 2007 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_xjfq69j4wr_g-19Q:-NId1fXoB3UWwRqkHOVG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/conn_executor_exec.go#L2007)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

I'm a bit concerned about the usage of the internal executor here (see https://github.com/cockroachdb/cockroach/issues/91004 if you're curious). Could you add a comment: 
```
TODO(janexing): better bind the internal executor with the txn.
```
Thanks!
</blockquote></details>

Done.
___
*[`pkg/sql/compengine/sketch.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_on7--UoXyXoSR0os:-NId2NgM0pHLL7osKkxH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/compengine/sketch.go#L54)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: change it to `buf.WriteByte(byte(MarkCursorInSpace))`
</blockquote></details>

Done.
___
*[`pkg/sql/compengine/sketch.go` line 76 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_cmOa7VhY5xNZHkiQ:-NId5GkcEoow5WLJ1roy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/compengine/sketch.go#L76)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: iiuc, the last token is always the EOF, so the start and the end indexes are the same. It may be easier to understand if we have ` >= nt(tokens[len(tokens)-1].End)`.
</blockquote></details>

Done.
___
*[`pkg/sql/compengine/sketch.go` line 82 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_dI_XCuGWaKs4hVI0:-NId5HEcDSW_H9JhUbyt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/compengine/sketch.go#L82)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/sql/compengine/sketch.go` line 144 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_or14DxpyBbRbj7B-:-NId2Q5j3L9Tsr620AR_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/compengine/sketch.go#L144)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: change it to `if sketch[pos] != MarkCursorInSpace && sketch[pos] != MarkCursorInToken `
</blockquote></details>

Done.
___
*[`pkg/sql/comprules/rules.go` line 156 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_qYckD1929-s4sUKr:-NId2bx71hWpcAspabtH:bousot) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/comprules/rules.go#L156)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Just out of curiosity -- could you say more about the "comment system"?
</blockquote></details>

Things from pg_catalog. Explained in comment.
___
*[`pkg/sql/comprules/rules.go` line 174 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_riJE0GeZYmkVz5sw:-NId43vl-jo7MSRVcExV:b-axvudb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/comprules/rules.go#L174)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: For this regex, seems that sketches `,'`, `,_` and `,i` also match. Is this expected? Should we ask for an identifier token at the beginning?
</blockquote></details>

matching on `,'`  doesn't seem right, good catch. Modified.

`,_` is expected, because we have `select * from db1.t1, db2.t2`, we want to see databases listed after the comma.
___
*[`pkg/sql/opt/exec/factory.opt` line 730 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NIXrhOg9tRwWKg6zl_S:-NIcw6Ql1ywwE9c5SU6V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed6b0cee635df01c7cae2caaff77d57eb2b41887/pkg/sql/opt/exec/factory.opt#L730)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think this needs to go to the end of this file to avoid causing problems with gists (see the comment on line 39 of plan_gist_factory.go)
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/statement.go` line 321 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NIXrKac65344unlDqtR:-NIcwPH43xiPahFSAXLi:b6zrrkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed6b0cee635df01c7cae2caaff77d57eb2b41887/pkg/sql/opt/exec/execbuilder/statement.go#L321)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: update comment
</blockquote></details>

Good catch.
___
*[`pkg/sql/opt/exec/explain/testdata/gists` line 1012 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NIXtVq4Bdn6zoFgj0YE:-NIcwvOeCSqgsIPKph5x:b-r0wp3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed6b0cee635df01c7cae2caaff77d57eb2b41887/pkg/sql/opt/exec/explain/testdata/gists#L1012)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you please add a test in this file for SHOW COMPLETIONS and make sure that none of these other tests change? Thank you!
</blockquote></details>

Good idea. Done.
___
*[`pkg/sql/compengine/sketch_test.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NI_Vauo2-wX4GPyw7n0:-NId4SFqE3GASP3QwX68:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/compengine/sketch_test.go#L54)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: could you add a comment for this? IIUC we're printing out the token corresponding to the current cursor, and also its surrounding tokens.
</blockquote></details>

Done.
___
*[`pkg/sql/completions.go` line 41 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87606#-NIYs4C_4Mg9RDOLIhHI:-NId1XlW3dnpPynZhtyM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1fd215025fc6f727621eba949d773170401f3ec/pkg/sql/completions.go#L41)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

We can just use `params.p.QueryIteratorEx()` here.
`initInternalExecutor()` is expected to be used only in `planner.WithInternalExecutor()` or query/exec functions such as `planner.ExecEx()`. 
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYRs!

bors r=rytaft,ZhouXing19

**Pull request merged**
