### PR TITLE
storage: prevent command reproposal with new lease index after application

### LINKED ISSUE #37810: roachtest: cdc/tpcc-1000/rangefeed=true failed
SHA: https://github.com/cockroachdb/cockroach/commits/fc7e48295cd05f94fd2883498d96d91ad538e559

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=cdc/tpcc-1000/rangefeed=true PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1308263&tab=buildLog

```
The test failed on branch=master, cloud=gce:
	cluster.go:1516,cdc.go:747,cdc.go:135,cluster.go:1854,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1308263-cdc-tpcc-1000-rangefeed-true:4 -- ./workload run tpcc --warehouses=1000 --duration=120m --tolerate-errors {pgurl:1-3}  returned:
		stderr:
		
		stdout:
		l
		   1m32s       60           19.0            9.0  18253.6  34359.7  38654.7  38654.7 delivery
		   1m32s       60          159.0           76.6  27917.3  77309.4  77309.4  77309.4 newOrder
		   1m32s       60           14.0            9.4  19327.4  24696.1  34359.7  34359.7 orderStatus
		   1m32s       60          150.0           90.1  24696.1  45097.2  73014.4  77309.4 payment
		   1m32s       60            7.0            9.4  19327.4  33286.0  33286.0  33286.0 stockLevel
		_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
		   1m33s       60            9.0            9.0  19327.4  34359.7  34359.7  34359.7 delivery
		   1m33s       60          172.9           77.6  24696.1  62277.0  77309.4  77309.4 newOrder
		   1m33s       60           25.0            9.6  20401.1  38654.7  40802.2  40802.2 orderStatus
		   1m33s       60          158.9           90.9  24696.1  49392.1  57982.1  64424.5 payment
		   1m33s       60           18.0            9.5  20401.1  31138.5  31138.5  31138.5 stockLevel
		: signal: killed
	cluster.go:1875,cdc.go:223,cdc.go:475,test.go:1251: unexpected status: failed

```

### LINKED ISSUE #39018: roachtest: cdc/ledger/rangefeed=true failed
SHA: https://github.com/cockroachdb/cockroach/commits/1ad0ecc8cbddf82c9fedb5a5c5e533e72a657ff7

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=cdc/ledger/rangefeed=true PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1399000&tab=buildLog

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190722-1399000/cdc/ledger/rangefeed=true/run_1
	cluster.go:1726,cdc.go:767,cdc.go:150,cluster.go:2069,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1563776264-11-n4cpu16:4 -- ./workload run ledger --mix=balance=0,withdrawal=50,deposit=50,reversal=0 {pgurl:1-3} --duration=30m returned:
		stderr:
		
		stdout:
		 0.0 withdrawal
		  22m33s        0            0.0          689.3      0.0      0.0      0.0      0.0 deposit
		  22m33s        0            0.0          689.3      0.0      0.0      0.0      0.0 withdrawal
		  22m34s        0            1.0          688.8   7784.6   7784.6   7784.6   7784.6 deposit
		  22m34s        0            0.0          688.8      0.0      0.0      0.0      0.0 withdrawal
		  22m35s        0           10.0          688.3    486.5   9663.7   9663.7   9663.7 deposit
		  22m35s        0            7.0          688.3   9126.8   9663.7   9663.7   9663.7 withdrawal
		  22m36s        0          198.0          687.9     14.7    125.8    503.3    570.4 deposit
		  22m36s        0          188.0          688.0     14.2     56.6    113.2    570.4 withdrawal
		  22m37s        0          321.0          687.7     14.7     24.1     33.6     58.7 deposit
		  22m37s        0          315.0          687.7     14.2     24.1     27.3     30.4 withdrawal
		Error: error in withdrawal: driver: bad connection
		Error:  exit status 1
		: exit status 1
	cluster.go:2090,cdc.go:224,cdc.go:566,test_runner.go:691: Goexit() was called

```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #39018.
Fixes #37810.
May fix other tests.

This commit fixes a bug introduced in e4ce717 which allowed a single Raft proposal to be applied multiple times at multiple applied indexes. The bug was possible if a raft proposal was reproposed twice, once with the same max lease index and once with a new max lease index. Because there are two entries for the same proposal, one necessarily has to have an invalid max lease applied index (see the invariant in https://github.com/cockroachdb/cockroach/blob/5cbc4b50712546465de75dba69a1c0cdd1fe2f87/pkg/storage/replica_raft.go#L1430) If these two entries happened to land in the same application batch on the leaseholder then the first entry would be rejected and the second would apply. The replicas LeaseAppliedIndex would then be bumped all the way to the max lease index of the entry that applied. The bug occurred when the first entry (who must have hit a proposalIllegalLeaseIndex), called into tryReproposeWithNewLeaseIndex. The ProposalData's MaxLeaseIndex would be equal to the Replica's LeaseAppliedIndex because it would match the index in the successful entry. We would then repropose the proposal with a larger lease applied index. This new entry could then apply and result in duplicate entry application.

Luckily, rangefeed's intent reference counting was sensitive enough that it caught this duplicate entry application and panicked loudly. Other tests might also be failing because of it but might not have as obvious symptoms when they hit the bug.

In addition to this primary bug fix, this commit has a secondary effect of fixing an issue where two entries for the same command could be in the same batch and only one would be linked to its ProposalData struct and be considered locally proposed (see the change in retrieveLocalProposals). I believe that this would prevent the command from being properly acknowledged if the first entry was rejected due to its max lease index and the second entry had a larger max lease index and applied. I think the first entry would have eventually hit the check in tryReproposeWithNewLeaseIndex and observed that the linked ProposalData had a new MaxLeaseIndex so it would have added it back to the proposal map, but then it would have had to wait for refreshProposalsLocked to refresh the proposal, at which point this refresh would have hit a lease index error and would be reproposed at a higher index. Not only could this cause duplicate versions of the same command to apply (described above), but I think this could even loop forever without acknowledging the client. It seems like there should be a way for this to cause #39022, but it doesn't exactly line up.

Again, these kinds of cases will be easier to test once we properly mock out these interfaces in #38954. I'm working on that, but I don't think it should hold up the next alpha (#39036). However, this commit does address a TODO to properly handle errors during tryReproposeWithNewLeaseIndex reproposals and that is properly tested.

My debugging process to track this down was to repeatedly run a set of 10 `cdc/ledger/rangefeed=true` roachtests after reducing its duration down to 5m. Usually, at least one of these tests would hit the `negative refcount` assertion. I then incrementally added more and more logging around entry application until I painted a full picture of which logical ops were being consumed by the rangefeed processor and why the same raft command was being applied twice (once it became clear that one was). After a few more rounds of fine-tuning the logging, the interaction with reproposals with a new max lease index became clear.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: just suggestions on comments from me. Good catch and nice fix. 

> Reviewed 3 of 3 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-:-LkXCEeLBrXrXPm-bQw_:bspjhfa)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/storage/replica_application.go, line 388 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkX7Em5D9jYxJWYcP9Y:-LkX7Em7DRfKK_MwFxeZ:bkoms5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/15b0521e67ebf67882bcf2eabcf46f4e6b3087ff/pkg/storage/replica_application.go#L388)):*
> ```Go
> 	// Provide the command's corresponding logical operations to the Replica's
> 	// rangefeed. Only do so if the WriteBatch is non-nil, otherwise it's valid
> 	// for the logical op log to be nil, which would shut down all rangefeeds.
> ```

nit: I get that this is moved code but the second sentence here is a little difficult to understand. Any chance you could add some more words?
___
*[pkg/storage/replica_application_result.go, line 319 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkXEzeV9UkXJPqGUsgx:-LkXEzeV9UkXJPqGUsgy:brw8k65) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application_result.go#L319)):*
> ```Go
> 
> 	var pErr *roachpb.Error
> 	if filter := r.store.cfg.TestingKnobs.TestingPostApplyFilter; filter != nil {
> ```

nit: TestingPostApplyFilter might benefit from a comment update that it will only be called on the proposing replica and will have no impact on follower. There's only one user and this PR doesn't change the behavior with regard to what happens to the return values but it does change how often it will be called. It wasn't totally obvious from the old code that setting pErr wouldn't do anything if the command wasn't proposed locally. 
___
*[pkg/storage/replica_application_result.go, line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkX8JEq2-OeYFPrMHLi:-LkX8JEs5_L6KAG4YC2u:b-d9ady) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application_result.go#L353)):*
> ```Go
> 			// a new one. This is important for pipelined writes, since they
> 			// don't have a client watching to retry, so a failure to
> 			// eventually apply the proposal would be a uservisible error.
> ```

nit: `user visible` or `user-visible`

**Review by tbg — APPROVED** [review]
:lgtm: 


I'd love to hear a little bit about how you repro'ed and zero'ed in on this, perhaps even in the commit message.

> Reviewed 3 of 3 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-:-LkYfC8_7iLiegR9LZ56:b-8jg586)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_application.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYRBqeCqLKWaUDu9JK:-LkYRBqeCqLKWaUDu9JL:b-dbivlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/15b0521e67ebf67882bcf2eabcf46f4e6b3087ff/pkg/storage/replica_application.go#L391)):*
> ```Go
> 	// If no rangefeed is running, this call will be a noop.
> 	if cmd.raftCmd.WriteBatch != nil {
> 		r.handleLogicalOpLogRaftMuLocked(ctx, cmd.raftCmd.LogicalOpLog, batch)
> ```

You mention in the commit message that the lookup operates directly on the WriteBatch, but this is still operating on `batch`. This is probably more efficient than hitting the engine directly if and only if the read is satisfied from what's in the batch. Additionally, reading from the bash may flush some stuff down and be extra expensive? Anyway, reading from the batch is all good because that's the only safe thing to do, but I'm not convinced this improves performance. Unless somehow the fixed overhead of opening a handle into the DB is the main cost here.
If we wanted to go all in we could probably read directly from the WriteBatch first, and fall back to the engine (in approximately 100% of cases). But likely none of that is ever worth it, see if you want to adjust any of the wording though.
___
*[pkg/storage/replica_application.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYX6ff1Nowv5feFiyE:-LkYW7Nh7aBc4UUKxJ3m:b-f47604) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application.go#L159)):*
> , in which case the proposal was reproposed (either under its original or a new MaxLeaseIndex) which we handle in a second pass below.
___
*[pkg/storage/replica_application.go, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYWkGKESJV_Qi9P6yb:-LkYWkGKESJV_Qi9P6yc:b-71ozie) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application.go#L173)):*
> ```Go
> 	for ok := it.init(&b.cmdBuf); ok; ok = it.next() {
> 		cmd := it.cur()
> 		if !cmd.proposedLocally() {
> ```

This is not a PR for silly micro-optimizations, but usually you have only a single proposer, so you could populate a bool `anyProposedLocally` in the previous loop and skip this whole second loop on the followers most of the time.
___
*[pkg/storage/replica_application.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYXh9n4ibxI6eZKpFW:-LkYXh9n4ibxI6eZKpFX:bu66bh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application.go#L179)):*
> reproposed with a higher lease index.
___
*[pkg/storage/replica_application.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYYPpZ9OEo7IVuKBRS:-LkYYPpZ9OEo7IVuKBRT:bksp3y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application.go#L188)):*
> If tryReproposeWithNewLeaseIndex picks up the proposal on failure, it will re-add the proposal to the proposal map, but this won't affect anything in this cmdAppBatch.
___
*[pkg/storage/replica_application_result.go, line 391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYZKk_3_uARXV2BRF0:-LkYZKk_3_uARXV2BRF1:b-1ua3vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application_result.go#L391)):*
> ```Go
> // has already been successfully applied or has been reproposed here or by a
> // different entry for the same proposal that hit an illegal lease index error.
> func (r *Replica) tryReproposeWithNewLeaseIndex(
> ```

Pure movement, correct?

**Review by nvb — COMMENTED** [review]
TFTRs!

> I'd love to hear a little bit about how you repro'ed and zero'ed in on this, perhaps even in the commit message.

I added a bit about this to the commit message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-:-LkZ2DkP8-63h4k6TYWU:b-q4jyaa)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @tbg)

___
*[pkg/storage/replica_application.go, line 388 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkX7Em5D9jYxJWYcP9Y:-LkZ4kGFC-ko4bs-eDtD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/15b0521e67ebf67882bcf2eabcf46f4e6b3087ff/pkg/storage/replica_application.go#L388)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: I get that this is moved code but the second sentence here is a little difficult to understand. Any chance you could add some more words?
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYRBqeCqLKWaUDu9JK:-LkZ4puC-pWMJqtrTR37:bvfcr2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/15b0521e67ebf67882bcf2eabcf46f4e6b3087ff/pkg/storage/replica_application.go#L391)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

You mention in the commit message that the lookup operates directly on the WriteBatch, but this is still operating on `batch`. This is probably more efficient than hitting the engine directly if and only if the read is satisfied from what's in the batch. Additionally, reading from the bash may flush some stuff down and be extra expensive? Anyway, reading from the batch is all good because that's the only safe thing to do, but I'm not convinced this improves performance. Unless somehow the fixed overhead of opening a handle into the DB is the main cost here.
If we wanted to go all in we could probably read directly from the WriteBatch first, and fall back to the engine (in approximately 100% of cases). But likely none of that is ever worth it, see if you want to adjust any of the wording though.
</blockquote></details>

Clarified. You're right that the read will be satisfied from the batch for `MVCCWriteValueOps` but not for `MVCCCommitIntentOps`.
___
*[pkg/storage/replica_application.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYX6ff1Nowv5feFiyE:-LkZ0NoK6gU8eCCeyIoP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application.go#L159)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> , in which case the proposal was reproposed (either under its original or a new MaxLeaseIndex) which we handle in a second pass below.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYWkGKESJV_Qi9P6yb:-LkZ0VlwCTxlOrf6UpbC:b2wm1h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application.go#L173)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This is not a PR for silly micro-optimizations, but usually you have only a single proposer, so you could populate a bool `anyProposedLocally` in the previous loop and skip this whole second loop on the followers most of the time.
</blockquote></details>

Something like https://github.com/cockroachdb/cockroach/pull/38954/files#diff-5bbfc08e6144696413cb26f2de677022R275? Since I'm planning on adding it there, I might as well make the change now. Done.
___
*[pkg/storage/replica_application.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYXh9n4ibxI6eZKpFW:-LkZ0pnF2U50pMr5hxm8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application.go#L179)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> reproposed with a higher lease index.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYYPpZ9OEo7IVuKBRS:-LkZ162k0yK_FDW7i0PB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application.go#L188)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> If tryReproposeWithNewLeaseIndex picks up the proposal on failure, it will re-add the proposal to the proposal map, but this won't affect anything in this cmdAppBatch.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application_result.go, line 319 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkXEzeV9UkXJPqGUsgx:-LkZ27Jq3juO84i_3OHU:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application_result.go#L319)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: TestingPostApplyFilter might benefit from a comment update that it will only be called on the proposing replica and will have no impact on follower. There's only one user and this PR doesn't change the behavior with regard to what happens to the return values but it does change how often it will be called. It wasn't totally obvious from the old code that setting pErr wouldn't do anything if the command wasn't proposed locally. 
</blockquote></details>

Good point. Done.
___
*[pkg/storage/replica_application_result.go, line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkX8JEq2-OeYFPrMHLi:-LkZ1Cmp1Wm6wrTYKqHX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application_result.go#L353)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: `user visible` or `user-visible`
</blockquote></details>

Done.
___
*[pkg/storage/replica_application_result.go, line 391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39064#-LkYZKk_3_uARXV2BRF0:-LkZ1E4_8DPnFyz4ZZdo:boju2lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/01757dc8cbafade5954116f91c76d59c2f984bbf/pkg/storage/replica_application_result.go#L391)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Pure movement, correct?
</blockquote></details>

No, this is completely rewritten to be a lot cleaner, to no longer need the replica mutex, and to properly handle errors. This was all made possible by the `if cmd.raftCmd.MaxLeaseIndex != cmd.proposal.command.MaxLeaseIndex {` check in `retrieveLocalProposals`.

**Comment by nvanbenschoten** [comment]
```
F190724 13:56:46.869487 538738 storage/replica_proposal.go:131  [n1,s1,r16/1:/Table/2{0-1}] proposal already applied: &{ctx:0xc011aabd40 sp:<nil> idKey:N��9�Wi_ proposedAtTicks:5 command:0xc022707900 encodedCommand:[0 78 136 220 57 189 87 105 95 18 6 8 1 16 1 24 1 48 1 106 19 66 10 8 147 148 240 195 128 142 151 218 21 146 1 4 96 116 104 2 114 75 10 73 0 0 0 0 0 0 0 0 1 0 0 0 1 29 1 107 18 156 0 1 113 108 112 116 99 111 110 115 105 115 116 101 110 99 121 67 104 101 99 107 101 114 0 29 18 4 8 0 16 0 24 0 32 0 40 0 50 15 54 176 12 30 3 8 178 152 233 195 128 142 151 218 21 32 13] quotaSize:108 tmpFooter:{MaxLeaseIndex:13} ec:{repl:0xc005727800 lg:0xc00e41fd60} applied:true doneCh:<nil> Local:LocalResult (reply: (err: <nil>), *roachpb.PutResponse, #intents: 0, #endTxns: 0 #updated txns: 0, GossipFirstRange:false MaybeGossipSystemConfig:false MaybeAddToSplitQueue:false MaybeGossipNodeLiveness:<nil> MaybeWatchForMerge:false Request:Put [/Local/Range/Table/20/QueueLastProcessed/"consistencyChecker",/Min)}
```

This might be good.

**Comment by nvanbenschoten** [comment]
The assertion I added to detect duplicate command application wasn't ignoring expected errors on the second application attempt. With that added, the test stresses without issue.

bors r+

**Pull request merged**
