### PR TITLE
distsqlrun: refactor the ridiculous processor.Run() interface

### PR DESCRIPTION
**Pull request by andreimatei**
The Run() method was optionally taking a WaitGroup, to signal before
returning. The method is synchronous; the caller can signal whatever it
wants after the callee returns.

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
Great, thanks for the change.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 25 of 25 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33411#-:-LVDnWls6lvCgh1Yzr6x:b-hrqelf)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33411#-:-LVDs90MA5BSnMPW9gGs:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
TFTRs

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33411#-:-LVFdAjk0XezvwJ_hDS6:b-6rbzir)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
