### PR TITLE
sql: prevent a constant stream of lease acquires from starving a deletion

### PR DESCRIPTION
**Pull request by andreimatei**
Fail acquires after a table has been marked for deletion.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6360)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/drop_test.go, line 362 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6360#-KGPfI-YzqBx2640_FTL:-KGPfI-YzqBx2640_FTM:-1971901477) ([raw file](https://github.com/cockroachdb/cockroach/blob/96a16fe0c59e4b14dfa647b7d829a8e74c3fdc5d/sql/drop_test.go#L362)):*
I don't think you need the lock nor the boolean.

---

*[sql/drop_test.go, line 433 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6360#-KGPf6jL1fsP2rbTyAUE:-KGPf6jMn39khYOMvEwC:1214376733) ([raw file](https://github.com/cockroachdb/cockroach/blob/96a16fe0c59e4b14dfa647b7d829a8e74c3fdc5d/sql/drop_test.go#L433)):*
Can you add another insert after the commit to show that it will fail.

---

*[sql/lease.go, line 464 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6360#-KGPfvHXsZ9pBfV4a_jZ:-KGPfvHXsZ9pBfV4a_j_:-1516723697) ([raw file](https://github.com/cockroachdb/cockroach/blob/96a16fe0c59e4b14dfa647b7d829a8e74c3fdc5d/sql/lease.go#L464)):*
how about t.deleted && version == 0

---

*[sql/lease_test.go, line 530 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6360#-KGPdgZWpP5aF2agQ8gH:-KGPddGcmVXuo73efodp:28836671) ([raw file](https://github.com/cockroachdb/cockroach/blob/96a16fe0c59e4b14dfa647b7d829a8e74c3fdc5d/sql/lease_test.go#L530)):*
why the temp?

---

*[sql/lease_test.go, line 548 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6360#-KGPdsIIbOvGKP4TQ2sW:-KGPdsIIbOvGKP4TQ2sX:501214319) ([raw file](https://github.com/cockroachdb/cockroach/blob/96a16fe0c59e4b14dfa647b7d829a8e74c3fdc5d/sql/lease_test.go#L548)):*
what do you mean by the above comment? I think you want to say 

// Check that there are no outstanding leases for the table in the system.lease table.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6360)*

**Comment by tamird** [comment]
What's up with this?

**Comment by vivekmenezes** [comment]
I can review it once you rebase

**Comment by tamird** [comment]
@andreimatei this needs a rebase - it has been idle for quite some time.

**Pull request closed without merging**
