### PR TITLE
Add a test case where offset errors are bigger than the max offset

### PR DESCRIPTION
**Pull request by kkaneda**
This kind of scenarios could happen when heartbeat messages to the node are having high latency. The computed cluster offset interval becomes a wide range, and it might be considered healthy even when the clock offset is bigger than maxOffset.

Not totally sure it's worth adding this test, but it was useful for me to understand how the system works..

### CODE REVIEW

**Comment by spencerkimball** [comment]
LGTM. @embark, care to take a look?

**Comment by tschottdorf** [comment]
LGTM.

**Comment by kkaneda** [comment]
One question I have is whether a node should commit a suicide when it sees a large interval error. It cannot correctly estimate the cluster time, so it might be better to kill itself?

**Comment by tschottdorf** [comment]
That's what it's currently doing. I had reservations about it because it could lead to spontaneous cluster death if you think of leap seconds and such, but we decided to leave it as is for now.

**Comment by tschottdorf** [comment]
Hey @kkaneda, feel free to merge this at any time.

**Comment by kkaneda** [comment]
Sure, @tschottdorf ! Merging.

Hmm, My understanding of how currently the system works is that a node does not commit a suiciden as long as a clock offset overlaps with [-maxOffset, maxOffset] (default: [-200ms, 200ms]). When a node is having large RPC latency, we take that into account as "error" and compute a offset with [offset - error - maxOffset, offset + error + maxOffset). So, if the offset is 200ms and the error is 1000ms, we get [-1000ms, 1400ms], which still overlaps with [-200ms, 200ms].

We also use `maximumClockReadingDelay` (= 1.5esc) to ignore heartbeats and mark a node unhealthy when the RPC round-trip time is bigger. Maybe we should make `maximumClockReadingDelay` more aggressive (e.g., 100ms) so that nodes that might have a large clock offset are marked unhealthy.

**Pull request merged**
