### PR TITLE
rangefeed: unconditionally use rangefeed scheduler

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvserver: enable rangefeed scheduler by default**

Touches #113029.
Epic: none
Release note (performance improvement): rangefeeds, the infrastructure used for changefeeds, now use a more efficient engine that reduces the number of goroutines and the associated Go scheduler pressure and latency.

**rangefeed: unconditionally use rangefeed scheduler**

This patch unconditionally uses the new rangefeed scheduler. This has no mixed-version concerns, since the scheduler is internal to each node and uses the same client protocol.

Epic: none
Release note (ops change): the setting `kv.rangefeed.scheduler.enabled` has been removed, as the rangefeed scheduler is now unconditionally enabled.

**rangefeed: remove `LegacyProcessor`**

The rangefeed scheduler is now used unconditionally.

**rangefeed: remove `Config.PushTxnsInterval`**

This has no effect for scheduler-based processors, which is now the only processor type. Instead, the `RangeFeedPushTxnsInterval` testing knob is now propagated to the store's rangefeed txn pusher loop.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 9 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvserver/rangefeed/processor_test.go` line 333 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114410#-NjDZIx1-EMgnoM5Gvl4:-NjDZIx1-EMgnoM5Gvl5:b1bvdlr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8809b507560b2672567837cbe5eb08373f928d/pkg/kv/kvserver/rangefeed/processor_test.go#L333)):*
> ```Go
> 
> 	sch := NewScheduler(SchedulerConfig{
> 		Workers:         1,
> ```

do we have tests that spin use multiple workers?
Does it make sense to just throw some metamorphic constant here and for the priority workers below?

**Comment by miretskiy** [comment]
@erikgrinaker  -- what's left for this PR? (other than CI)?
You might need to change mixed_version_cdc.go

**Comment by erikgrinaker** [comment]
Nothing really, just wanted to wait for 23.2 to firm up a bit first, to make it easier to backport fixes.

I'll address your comments and merge this when I have time.

**Review by erikgrinaker — COMMENTED** [review]
>You might need to change mixed\_version\_cdc.go

Thanks, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114410#-:-Nn9zBzy0CAsyUb_-IJ0:b6t3ojw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @miretskiy)

___
*[`pkg/kv/kvserver/rangefeed/processor_test.go` line 333 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114410#-NjDZIx1-EMgnoM5Gvl4:-Nn9y0vC-B76X9DohRac:b-kkvdsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8809b507560b2672567837cbe5eb08373f928d/pkg/kv/kvserver/rangefeed/processor_test.go#L333)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we have tests that spin use multiple workers?
Does it make sense to just throw some metamorphic constant here and for the priority workers below?
</blockquote></details>

It won't make any difference here. There's only a single range, which can only be processed by a single worker at a time by definition. Multiple workers are only relevant with multiple ranges, and these are covered by integration and end-to-end tests.

**Pull request merged**
