### PR TITLE
storage: update confusing comment

### PR DESCRIPTION
**Pull request by tamird**
From the graveyard. Originally intended as work towards #7619.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8106)

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/store.go, line 2404 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8106#-KNxpgF67uPChv4gvqs-:-KNxpgF67uPChv4gvqs0:906740312) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b30cc2583c9322b40b3b67d88dd134f089bb5f2/storage/store.go#L2404)):*
> ```Go
> 	r.mu.Unlock()
> 
> 	if replicaID == 0 {
> ```

This isn't equivalent; it may send preemptive snapshots down the "regular" code path. I had originally asked for this change in #7619 , but @tschottdorf convinced me that it's better to be cautious and reject preemptive snapshots if there is an existing raft group, so this condition needs to be based on `req.ToReplica.ReplicaID` instead of `r.mu.replicaID`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8106)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/store.go, line 2404 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8106#-KNxpgF67uPChv4gvqs-:-KNxsZ9-TMNxEBgE7CwC:-1477741547) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b30cc2583c9322b40b3b67d88dd134f089bb5f2/storage/store.go#L2404)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This isn't equivalent; it may send preemptive snapshots down the "regular" code path. I had originally asked for this change in #7619 , but @tschottdorf convinced me that it's better to be cautious and reject preemptive snapshots if there is an existing raft group, so this condition needs to be based on `req.ToReplica.ReplicaID` instead of `r.mu.replicaID`. 
</details>
Can you point me to that discussion? I couldn't find it in #7619 or the PR that closed it.

You're implying that a call to to `getOrCreateReplicaLocked` with `replicaID = 0` can return a replica with a non-zero ID, but I don't see how that can happen. What's more, if it does happen, then don't we want that snapshot to go through the regular code path? We got a pre-emptive snapshot for a replica that is already a member of the raft group, which means we want it to be discarded (which is what I expect will happen on the regular code path).

What am I missing here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8106)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/store.go, line 2404 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8106#-KNxpgF67uPChv4gvqs-:-KO2Axk7bh7A7YylzXAb:1378439943) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b30cc2583c9322b40b3b67d88dd134f089bb5f2/storage/store.go#L2404)):*
> the semantics we're looking for in this condition are "is the incoming message a preemptive snapshot", not "do we already have an initialized replica"

The comment just two lines down seems to indicate the opposite, and that was also my understanding when making this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8106)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/store.go, line 2404 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8106#-KNxpgF67uPChv4gvqs-:-KO2Ex-JNTe2ZPLq4QT7:-1739809646) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b30cc2583c9322b40b3b67d88dd134f089bb5f2/storage/store.go#L2404)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> > the semantics we're looking for in this condition are "is the incoming message a preemptive snapshot", not "do we already have an initialized replica"
> 
> The comment just two lines down seems to indicate the opposite, and that was also my understanding when making this change.
</details>
The original intention was that preemptive snapshots could be applied through the usual mechanisms, but we changed our minds in #7833: the artificial nature of preemptive snapshots makes it too risky to pass them into the real raft group. Some comments may need updates to reflect this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8106)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/store.go, line 2404 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/8106#-KNxpgF67uPChv4gvqs-:-KWFPDnN7VXnJx9V-XCu:brj127z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b30cc2583c9322b40b3b67d88dd134f089bb5f2/storage/store.go#L2404)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The original intention was that preemptive snapshots could be applied through the usual mechanisms, but we changed our minds in #7833: the artificial nature of preemptive snapshots makes it too risky to pass them into the real raft group. Some comments may need updates to reflect this. 
</details>
Changed this to update the comment instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8106)*

**Review by bdarnell — APPROVED** [review]

**Pull request merged**
