### PR TITLE
storage: indicate when a split causes a Raft snapshot

### PR DESCRIPTION
**Pull request by tbg**
Touches #31409.

Release note: None

### CODE REVIEW

**Review by petermattis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32588)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica_command.go, line 314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32588#-LSFbx_H2t4AMSTIcf6D:-LSFbx_H2t4AMSTIcf6E:b-tg2pjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a7747b05e356cf9b458fa6aade8fb5a6c7bce9/pkg/storage/replica_command.go#L314)):*
> ```Go
> 				continue
> 			}
> 			if pr.State == raft.ProgressStateReplicate {
> ```

Did you mean `!=`? I would think `ProgressStateReplicate` is the good state that is likely not going to cause a Raft snapshot.

**Review by tbg — COMMENTED** [review]
Thanks for catching that. Fixed and added a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32588#-:-LSFhszTDXYJwYDfT58u:b-e2kzup)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32588#-:-LSFiENyA5EEojVcjiTY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
bors r=petermattis

**Pull request merged**
