### PR TITLE
status: add total memory to runtime metrics

### PR DESCRIPTION
**Pull request by tbg**
For graphing memory usage percent, we need to know how much memory is available
on a node.

Epic: none
Release note: None

### CODE REVIEW

**Review by aadityasondhi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101542#-:-NTu4EJe5h8bDByPHC01:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
bors r=aadityasondhi
TFTR!

**Comment by healthy-pod** [comment]
bors retry

**Comment by healthy-pod** [comment]
bors retry

**Pull request merged**
