### PR TITLE
Remove error "no txn persisted, yet intent has heartbeat"

### PR DESCRIPTION
**Pull request by thschroeter**
#2111, is this correct?

### CODE REVIEW

**Comment by thschroeter** [comment]
Since the test fails, I'm assuming I should ignore the "no txn persisted, yet intent has heartbeat" error in `acceptance/single_key_test.go` by matching on the error message? Instead of removing the error from `PushTxn`?

**Comment by thschroeter** [comment]
What is the recommended way to run the acceptance tests on OS X?

Thanks!

**Comment by tschottdorf** [comment]
Why did you close this?

I think the correct fix (for now) is completely removing the `if args.PusheeTxn.LastHeartbeat != nil` branch (maybe leave a comment about the earlier code in its place, in case we want to backtrack), see also my comment in #2062. If you want to get fancy, you could make sure the push always goes back successful to the caller, but no `ABORTED` entry is written (I don't think it's worth it at this stage though).

`make acceptance` should run fine if you have `boot2docker` set up. Doesn't that work?

**Comment by thschroeter** [comment]
I wasn't sure it was the right approach, so I've abandoned it. Reopening now.

**Comment by thschroeter** [comment]
`make acceptance` works, thanks!

**Pull request closed without merging**
