### PR TITLE
opt: add rule to convert semi-join to inner-join

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds a new rule to convert semi joins to inner
joins: `ConvertSemiToInnerJoin`. This rule is similar to `CommuteSemiJoin`,
but applies in the cases where `CommuteSemiJoin` does not: when the `ON`
condition is not a simple equality. In this case, we must perform a `DistinctOn`
operation *after* the `InnerJoin`, followed by a `Project` to remove the
right-side columns.

Similar to `CommuteSemiJoin`, this rule allows semi joins to be
commuted. This rule is also useful because it allows us to
generate lookup joins and inverted lookup joins for cases where the
index is not covering.

Informs #48223

Release note (performance improvement): The optimizer can now
convert semi joins to inner joins in more cases, which may allow
the optimizer to produce more efficient query plans.

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @mjibson, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/xform/testdata/rules/join, line 3563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-MFWylCR6Om00E-pLBob:-MFWylCR6Om00E-pLBoc:b-jyqws9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ade8c6bb4beb1f643f9830b81f12cd65d5063f81/pkg/sql/opt/xform/testdata/rules/join#L3563)):*
> ```
>     └── aggregations
>            ├── const-agg [as=blkid:2, outer=(2)]
>            │    └── blkid:2
> ```

Could you explain what this is doing -- it is unfamiliar to me?

Also, I don't quite see why we need an aggregation and distinct-on. Once we have the output of the lookup join, isn't it sufficient to project away the right-side and then do DISTINCT?

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @mjibson, and @sumeerbhola)

___
*[pkg/sql/opt/xform/testdata/rules/join, line 3563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-MFWylCR6Om00E-pLBob:-MFX18PXCUqXUHxqnYCU:b-yoxppk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ade8c6bb4beb1f643f9830b81f12cd65d5063f81/pkg/sql/opt/xform/testdata/rules/join#L3563)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
>     └── aggregations
>            ├── const-agg [as=blkid:2, outer=(2)]
>            │    └── blkid:2
> ```

Could you explain what this is doing -- it is unfamiliar to me?

Also, I don't quite see why we need an aggregation and distinct-on. Once we have the output of the lookup join, isn't it sufficient to project away the right-side and then do DISTINCT?
</blockquote></details>

As part of the `DISTINCT ON`, we have to create an aggregate for any column that is not one of the grouping columns (the only grouping column here is the key, `c.gid`). The aggregate doesn't do anything, though: "const-agg" means we know that the column is constant within each group, so we can just take the first value.

So we're only applying a single `DISTINCT ON` operation -- there's no separate aggregation operator.

We apply the `Project` after the `DISTINCT ON`, since we may need to project away the grouping key.

**Review by mgartner — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1950 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-MFX55paDUAEYCsw8ui9:-MFX55paDUAEYCsw8uiA:bayk7uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc6dea43fe37b4dd575e107d20366cdaee7c9c9/pkg/sql/opt/xform/custom_funcs.go#L1950)):*
> But in that case, we would already have an inner join here.

[nit] This wording is confusing to me. Maybe something like this is more clear:

"Any semi join that could use an inverted index would already be transformed into an inner join by ConvertSemiToInnerJoin, so semi joins can be ignored here."

**Review by mgartner — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-:-MFX81NQ3FXSb6YkVyZS:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson, @rytaft, and @sumeerbhola)

**Comment by rytaft** [comment]
TFTR!

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53337)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @mjibson, and @sumeerbhola)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1950 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-MFX55paDUAEYCsw8ui9:-MFX9g6O9smQ9r0Bwc1O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc6dea43fe37b4dd575e107d20366cdaee7c9c9/pkg/sql/opt/xform/custom_funcs.go#L1950)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> But in that case, we would already have an inner join here.

[nit] This wording is confusing to me. Maybe something like this is more clear:

"Any semi join that could use an inverted index would already transformed into an inner join by ConvertSemiToInnerJoin, so semi joins can be ignored here."
</blockquote></details>

Done.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53337)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @mjibson, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/xform/rules/join.opt, line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-MFXKTgdBWBijGcSf9me:-MFXKTgdBWBijGcSf9mf:b-2l1oyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b11813519b032277d4a5fde56a094bc0c82f2907/pkg/sql/opt/xform/rules/join.opt#L100)):*
> ```
> [ConvertSemiToInnerJoin, Explore]
> (SemiJoin
>     $left:* & (HasStrictKey $left)
> ```

Should we consider removing the `HasStrictKey` condition and using `EnsureKey` instead, so that we handle more cases?

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/xform/rules/join.opt, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-MFXKkxH2U3lEl6NO_0c:-MFXR1Nf0pJ4SODTvlo_:b-r6wcgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b11813519b032277d4a5fde56a094bc0c82f2907/pkg/sql/opt/xform/rules/join.opt#L118)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Ah, I hadn't looked further down when I made the above comment. I think `EnsureKey` does what you want with less trouble and only one rule.
</blockquote></details>

Good call - thanks. I'll make that change.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53337)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, @mjibson, and @sumeerbhola)

___
*[pkg/sql/opt/xform/rules/join.opt, line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-MFXKTgdBWBijGcSf9me:-MFXYpM63eCrklN2kGm3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b11813519b032277d4a5fde56a094bc0c82f2907/pkg/sql/opt/xform/rules/join.opt#L100)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Should we consider removing the `HasStrictKey` condition and using `EnsureKey` instead, so that we handle more cases?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/join.opt, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-MFXKkxH2U3lEl6NO_0c:-MFXYq7c4ggSpZ-VEKu5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b11813519b032277d4a5fde56a094bc0c82f2907/pkg/sql/opt/xform/rules/join.opt#L118)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Good call - thanks. I'll make that change.
</blockquote></details>

Done.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-:-MFXZT3F3E1LmX26mj7y:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, @mjibson, and @sumeerbhola)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53337)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, @mjibson, and @sumeerbhola)

___
*[pkg/sql/opt/xform/rules/join.opt, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-MFXKkxH2U3lEl6NO_0c:-MFX_V3GCHCG1TSk25mW:b-i1ka52) ([raw file](https://github.com/cockroachdb/cockroach/blob/b11813519b032277d4a5fde56a094bc0c82f2907/pkg/sql/opt/xform/rules/join.opt#L118)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is cool. I just tried to do the same with with `SplitDisjunction`/`SplitDisjunctionAddKey`, but in that case an unnecessary project is added when there is already a key on the input scan (which isn't removed due to normalization rules not applying at the root).

So maybe `EnsureKey` is best for now in places where there is a `Project` regardless of whether or not there is a key.

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53337#-:-MFYKLT67cnGyb1GxI8s:b-tlx7ko)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, @mjibson, and @sumeerbhola)

**Pull request merged**
