### PR TITLE
sql: initialize the cluster version early

### LINKED ISSUE #119431: multi-tenant: SQL server fails to start up if cluster.preserve_downgrade_option is set
**Describe the problem**

We fail with a fatal error:

```
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16  version not initialized
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 !goroutine 83 [running]:
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 !runtime/debug.Stack()
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 ! GOROOT/src/runtime/debug/stack.go:24 +0x5e
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(_, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...})
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 ! github.com/cockroachdb/cockroach/pkg/util/log/clog.go:280 +0xe7
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x7777a30, 0xc184940}, 0x2, 0x4, 0x0, 0x0?, {0x6112a45, 0x17}, {0x0, 0x0, ...})
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 ! github.com/cockroachdb/cockroach/pkg/util/log/channels.go:109 +0x585
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 ! github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 ! github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/util/log/log_channels_generated.go:848
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 !github.com/cockroachdb/cockroach/pkg/clusterversion.(*clusterVersionSetting).activeVersion(0x0?, {0x7777a30, 0xc184940}, 0x0?)
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 ! github.com/cockroachdb/cockroach/pkg/clusterversion/pkg/clusterversion/setting.go:125 +0x85
F240218 04:19:31.384608 83 clusterversion/setting.go:125 ⋮ [-] 16 
```

Jira issue: CRDB-36194

### PR DESCRIPTION
**Pull request by stevendanna**
In secondary tenants, we previously did not initialize the cluster version until we received it via the initial rangefeed scan in the settings watcher.

The cluster.preserve_downgrade_option is almost surely going to arrive in our initial scan before the version setting. The setter for that option has validation that requires the cluster version setting is initialized. Similarly, if cluster.preserve_downgrade_option is set via an override that validation will be hit before the cluster version is initialized)

Here, we read the setting directly from storage before starting the settings watcher to initialize the setting.

Fixes #119431

Release note: None

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
Side note: we really should deprecate the `cluster.preserve_downgrade_option` now that we have `cluster.auto_upgrade.enabled`, including because this "validation" stuff is a mess.

**Comment by JeffSwenson** [comment]
> 
Side note: we really should deprecate the cluster.preserve_downgrade_option now that we have cluster.auto_upgrade.enabled (and just make it being empty/non-empty be OR'ed with the auto one for some long deprecation period), in no small part because this "validation" stuff here is a mess.

I find it's often useful to have a slightly different set of validation when admitting state to a system vs when the state is deserialized. E.g. we should validate preseve_downgrade when someone attempts to set it, but it doesn't actually matter if we deserialize a non-sensical value.

**Comment by dt** [comment]
> we should validate preseve_downgrade when someone attempts to set it

We could, but even better would be to not have it, and the need to validate it, at all in its current form, right?

As currently implemented with a named version, it isn't actually more powerful than a bool since you can't set it to future versions, and is indeed worse: you can't have it off but take explicit control. We already determined we'd be better served by a bool and added `cluster.auto_upgrade.enabled` but just didn't finish that by deprecating the string one.

**Review by jaylim-crl — APPROVED** [review]

**Comment by dt** [comment]
> prevent tenants from finalizing their cluster

Ah, interesting this is an explicit non-goal of the `auto_upgrade` setting. Maybe this suggests we want an extra setting that is exclusively used via overrides to block `SET CLUSTER SETTING version` but doesn't mess with the actual version setting or anything in validation. But anyway, this isn't a concern for this PR so I'll stop my rambling.

**Comment by stevendanna** [comment]
bors r=dt,jaylim-crl

**Comment by stevendanna** [comment]
bors cancel

**Comment by stevendanna** [comment]
bors r=dt,jaylim-crl

**Pull request merged**
