### PR TITLE
skip  TestLogic_mixed_version_external_connections_owner_id

### PR DESCRIPTION
**Pull request by msbutler**
Epic: none

Informs #98424

Release note: None

### CODE REVIEW

**Comment by msbutler** [comment]
usure if this is the proper way to skip a logic test.

**Comment by andyyang890** [comment]
I think this test should be less flaky after https://github.com/cockroachdb/cockroach/pull/98401 merges

**Comment by rafiss** [comment]
We should also change the test so it doesn't rely.on the IDs being consecutive. (or stop looking at the IDS)

**Comment by msbutler** [comment]
i will hold off on merging this!

**Comment by mgartner** [comment]
I don't think https://github.com/cockroachdb/cockroach/pull/98401 fixed this flake. Just saw it again here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9043994?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by rafiss** [comment]
I've made https://github.com/cockroachdb/cockroach/pull/98538 which should get to all the flakiness.

**Pull request closed without merging**
