### PR TITLE
sql/logictest: skip crdb_internal_tenant

### PR DESCRIPTION
**Pull request by andrewbaptist**
ref #89230

Test is flaky.

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
As this was a generated test, there was no easy way to skip it. I renamed the file to prepend the dot(.) for now.

**Comment by yuzefovich** [comment]
How about this diff instead?
```
diff --git a/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant b/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
index ac54bdffee..9e5ca90c8f 100644
--- a/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
+++ b/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
@@ -5,6 +5,7 @@ SELECT count(distinct(node_id)), count(*)  FROM crdb_internal.node_runtime_info
 ----
 1 12
 
+skipif config 3node-tenant
 query IT
 SELECT node_id, name FROM crdb_internal.leases ORDER BY name
 ----
```

Also, it looks like @ajwerner is actively working on a fix in #89293, so maybe let's hold off on the skip for a bit?

**Comment by ajwerner** [comment]
Any of y'all want to give https://github.com/cockroachdb/cockroach/pull/89293 a stamp?

**Comment by andrewbaptist** [comment]
Sounds good - closing this.

**Pull request closed without merging**
