### PR TITLE
sql: miscellaneous cleanup

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: don't make a redundant copy of the SetupFlowRequest for local flow**

We can just use the setup request directly since all remote requests (if
any) did make copies of the original request.

Release note: None

**colbuilder: don't create a copy of the eval context in most cases**

Previously, on every `NewColOperator` call we would create a copy of the
eval context. This was copied over from the row engine where making
a copy was needed since the row-by-row processors use `ProcOutputHelper`
which might modify the eval context when evaluating the expresssions. In
the vectorized engine we almost never modify the eval context, so there
is no reason to make a copy.

Release note: None

**colflow: minor optimization to the setup of inputs**

Release note: None

**colcontainer: make ReuseCache the default cache mode**

Previously, the uninitialized disk queue cache mode was the mode that
allowed the intertwined calls to Enqueue and Dequeue. However, such mode
of operation is only used by the hash routers and the buffered windower,
so this commit switches the uninitialized mode to be the "reuse cache"
mode (which is used by most components). This commit additionally cleans
up the way the mode is updated.

Release note: None

**colexecargs: remove no longer useful testing knob**

This commit removes a testing knob that tells the colbuilder to use
a streaming memory account for the buffering operations. The idea behind
this knob was to reduce the boilerplate of managing the memory
monitoring infrastructure in tests, and with the recent cleanup in that
area it is now easy to do properly. Thus, the knob seems no longer
needed and is now removed.

Release note: None

**colbuilder: instantiate a streaming allocator lazily**

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
```
name                                          old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24      239µs ± 5%     236µs ± 4%  -1.18%  (p=0.046 n=30+30)
FlowSetup/vectorize=true/distribute=false-24     234µs ± 4%     231µs ± 4%  -1.24%  (p=0.048 n=30+30)

name                                          old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24     33.2kB ± 2%    31.6kB ± 1%  -4.78%  (p=0.000 n=25+24)
FlowSetup/vectorize=true/distribute=false-24    31.2kB ± 1%    29.7kB ± 1%  -4.89%  (p=0.000 n=25+25)

name                                          old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24        268 ± 0%       264 ± 0%  -1.51%  (p=0.000 n=25+25)
FlowSetup/vectorize=true/distribute=false-24       255 ± 2%       251 ± 1%  -1.63%  (p=0.000 n=29+28)
```

**Review by rharding6373 — APPROVED** [review]
Cool! :lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72705#-:-MoaOy-T4exMmwF6SLYJ:b-dp13x5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 361 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72705#-MoaMs-x0vRclUIw4q0I:-MoaMs-yB_b9kvkiD5He:b72f4s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd9e949d4f56c9ebdce56f9d9be6e9e53ee8460c/pkg/sql/colexec/colbuilder/execplan.go#L361)):*
> ```
> "topk-sort"
> ```
nit: use an enum or constants instead of hand-crafted strings.

It seems like each case of the switch statement is only one line, though, so why not instantiate the inMemorySorter in the if/else statements and avoid using `sortType` and the extra switch statement altogether?
___
*[pkg/sql/colexec/colexecwindow/window_framer_test.go, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72705#-MoaJkHE7D9c3YNeRERw:-MoaJkHE7D9c3YNeRERx:bhgrchc) ([raw file](https://github.com/cockroachdb/cockroach/blob/728726cdce49f53b13e3d87c209fae628d441290/pkg/sql/colexec/colexecwindow/window_framer_test.go#L62)):*
> ```Go
> 	factory := coldataext.NewExtendedColumnFactory(evalCtx)
> 	allocator := colmem.NewAllocator(evalCtx.Ctx(), &memAcc, factory)
> 	queueCfg.CacheMode = colcontainer.DiskQueueCacheModeClearAndReuseCache
> ```

This isn't the default mode `DiskQueueCacheModeReuseCache`, so should this mode should be explicitly set?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72705#-:-MoatwYZ1_bq3S_dxMH5:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

**Review by cucaroach — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 10 of 10 files at r2, 1 of 1 files at r3, 17 of 17 files at r4, 7 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72705#-:-MoawzhVEyc_eZ3Bxngm:bnfp4nl)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72705#-:-Moo9r5Q3RF0cajjmaNp:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @cucaroach and @rharding6373)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 361 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72705#-MoaMs-x0vRclUIw4q0I:-Moo3k5YE6Qn-OTvrD--:b7i3vm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd9e949d4f56c9ebdce56f9d9be6e9e53ee8460c/pkg/sql/colexec/colbuilder/execplan.go#L361)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

> ```
> "topk-sort"
> ```
nit: use an enum or constants instead of hand-crafted strings.

It seems like each case of the switch statement is only one line, though, so why not instantiate the inMemorySorter in the if/else statements and avoid using `sortType` and the extra switch statement altogether?
</blockquote></details>

Reverted this change.

IIRC I wanted to remove some function calls around creating some memory monitoring components, but I agree that the change wasn't particularly clean, and it might be better to just keep things as they were.
___
*[pkg/sql/colexec/colexecwindow/window_framer_test.go, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72705#-MoaJkHE7D9c3YNeRERw:-Moo8P6i1aLrqt5wMPuS:bso4ibx) ([raw file](https://github.com/cockroachdb/cockroach/blob/728726cdce49f53b13e3d87c209fae628d441290/pkg/sql/colexec/colexecwindow/window_framer_test.go#L62)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

This isn't the default mode `DiskQueueCacheModeReuseCache`, so should this mode should be explicitly set?
</blockquote></details>

Good catch, fixed.

I tried to remove `DiskQueueCacheModeClearAndReuseCache` entirely, but ran into some performance regressions, and decided to keep the uncontroversial bits in this PR and continue the removal investigation in #72707. Not putting this back was an oversight.

**Pull request merged**
