### PR TITLE
cli: debug zip uses read-only range probe

### PR DESCRIPTION
**Pull request by dhartunian**
To reduce the chance of corruption issues when run against older clusters, the recently added use of `crdb_internal.probe_ranges` is modified to use a `read` probe instead of a `write` probe.

See discussion in #107720

Release note: None
Epic: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
:lgtm: - just one nit re: an important comment that I think we should have. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108313#-:-NbGYq5VAQw-nIjao7P8:biavzyl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @j82w, @joshimhoff, @nvanbenschoten, and @Santamaura)

___
*[`pkg/cli/zip_table_registry.go` line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108313#-NbGYiP5CkGP5Z9wmNT4:-NbGYiP5CkGP5Z9wmNT5:b-ynce4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d89c92be8e7d6636a0b88e4aefc67efc105f8a05/pkg/cli/zip_table_registry.go#L233)):*
> ```Go
> 	"crdb_internal.probe_ranges_1s_read_limit_100": {
> 		customQueryRedacted:   `SELECT * FROM crdb_internal.probe_ranges(INTERVAL '1000ms', 'read') WHERE error != '' ORDER BY end_to_end_latency_ms DESC LIMIT 100;`,
> 		customQueryUnredacted: `SELECT * FROM crdb_internal.probe_ranges(INTERVAL '1000ms', 'read') WHERE error != '' ORDER BY end_to_end_latency_ms DESC LIMIT 100;`,
> ```

nit: is it worth putting a comment here noting the potential dangers of using `write` here, so future maintainers have that context?

**Review by joshimhoff — APPROVED** [review]
LGTM! Thanks. I agree with @abarganier that we should add a comment about the corruption bug.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108313)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w, @nvanbenschoten, and @Santamaura)

___
*[`pkg/cli/zip_table_registry.go` line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108313#-NbGYiP5CkGP5Z9wmNT4:-NbI77mAAuXVZbsW9G4U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d89c92be8e7d6636a0b88e4aefc67efc105f8a05/pkg/cli/zip_table_registry.go#L233)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: is it worth putting a comment here noting the potential dangers of using `write` here, so future maintainers have that context? 
</blockquote></details>

Done.

**Comment by dhartunian** [comment]
bors r=joshimhoff

**Review by joshimhoff — APPROVED** [review]
LGTM

**Comment by joshimhoff** [comment]
thx for the fix!

**Review by j82w — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108313#-:-NbLfytQ4yOe2yzqOABP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @Santamaura)

**Pull request merged**
