### PR TITLE
sql: remove the heuristic planner

### PR DESCRIPTION
**Pull request by RaduBerinde**
These changes are intended for 20.1 and will not be merged until after branching.

#### sql: make COPY IN use the optimizer

The COPY IN implementation creates and executes an insertNode plan.
We change this code to use the optimizer and execute the plan
correctly (with the new FK checks, there could be postqueries).

Added a test that verifies we check foreign keys. I verified that the
test passes if we enable the optimizer FK checks.

Release note: None

#### sql: remove the heuristic planner

This change removes the bulk of the heuristic planner (as well as
supporting code that becomes unused).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @andreimatei for the first commit.

And CC @knz - no need to review, just wanted to share the joy :).

**Comment by knz** [comment]
I thought this had been done already? Oh well better now than after the branch split.

**Comment by RaduBerinde** [comment]
Note: I am working on a bunch of follow-up clean-up changes and further code removal but they will be separate PRs.

**Comment by RaduBerinde** [comment]
@knz Previous change removed the "optimization" part of the HP: https://github.com/cockroachdb/cockroach/pull/39766

**Comment by knz** [comment]
Oh I see. :+1:

**Review by rytaft — APPROVED** [review]
:lgtm_strong: 

> Reviewed 5 of 5 files at r1, 44 of 44 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40794#-:-Lp4zy95A8YAc_v7JNtY:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @RaduBerinde)

___
*[pkg/sql/copy.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40794#-Lp4oTCGBamSK3Gl_xZq:-Lp4oTCGBamSK3Gl_xZr:b-ljltb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/015e8fcd24a1bc72a3b974c3377335e16b9668f0/pkg/sql/copy.go#L72)):*
> ```Go
> 	resetPlanner func(p *planner, txn *client.Txn, txnTS time.Time, stmtTS time.Time)
> 
> 	// execInsertPlan is a function that can be used to execute an insert plan.
> ```

[nit] it's not obvious what an "insert plan" is... Maybe say this executes a plan for an INSERT statement?
___
*[pkg/sql/copy_in_test.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40794#-Lp4qNrt8g5hDtsSRrAe:-Lp4qNrt8g5hDtsSRrAf:b3vr8sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/015e8fcd24a1bc72a3b974c3377335e16b9668f0/pkg/sql/copy_in_test.go#L453)):*
> ```Go
> 		CREATE TABLE t (
> 		  a INT PRIMARY KEY,
> 			p INT REFERENCES p(p)
> ```

[nit] the indentation is off

**Review by andreimatei — COMMENTED** [review]
First commit looks good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40794#-:-Lp9nmqF4DWJcwJbExlM:b-xjsi7j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/copy.go, line 500 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40794#-Lp9n_L92X_kUizuaxA4:-Lp9n_L92X_kUizuaxA5:bkknfg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf75dcfa217fc14920aa3b9d5c16d14a98071ed5/pkg/sql/copy.go#L500)):*
> ```Go
> // insertResult is a simple implementation of RestrictedCommandResult which
> // can be used to execute an INSERT.
> type insertResult struct {
> ```

we have some other dummy implementations of CommandResult (for example the one used by the `InternalExecutor`). Did you look at those?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40794)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @justinj, and @rytaft)

___
*[pkg/sql/copy.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40794#-Lp4oTCGBamSK3Gl_xZq:-Lp9lzULBNSXRWJewH8i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/015e8fcd24a1bc72a3b974c3377335e16b9668f0/pkg/sql/copy.go#L72)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] it's not obvious what an "insert plan" is... Maybe say this executes a plan for an INSERT statement?
</blockquote></details>

Done.
___
*[pkg/sql/copy.go, line 500 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40794#-Lp9n_L92X_kUizuaxA4:-Lp9ro5Y1wDpTePlsQjs:b-e4im5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf75dcfa217fc14920aa3b9d5c16d14a98071ed5/pkg/sql/copy.go#L500)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

we have some other dummy implementations of CommandResult (for example the one used by the `InternalExecutor`). Did you look at those?
</blockquote></details>

Hm, yeah, we can use `bufferedCommandResult`, I must have missed it. Done.
___
*[pkg/sql/copy_in_test.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40794#-Lp4qNrt8g5hDtsSRrAe:-Lp9mBSp5Em3q6Oa2U1C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/015e8fcd24a1bc72a3b974c3377335e16b9668f0/pkg/sql/copy_in_test.go#L453)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] the indentation is off
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 46 files at r3, 1 of 1 files at r4, 44 of 44 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40794)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, and @justinj)

**Pull request merged**
