### PR TITLE
Fix a tiny grammar mistake in Ping()'s comment

### PR DESCRIPTION
**Pull request by kkaneda**
Hi, I just found a small grammar bug in a comment while randomly reading the code. Could you take a look and see if the change makes sense?

Thanks,
-Kenji

### CODE REVIEW

**Comment by tschottdorf** [comment]
Looks good, but could you also fix the typo ("requester", not "reqeuster" or whatever it says). Thanks.

**Comment by kkaneda** [comment]
Thanks for the review, Tobias! Sure, updated.

**Comment by spencerkimball** [comment]
LGTM

**Comment by spencerkimball** [comment]
Feel free to merge this.

**Comment by kkaneda** [comment]
Hmm, I don't have the write permission?

**Comment by spencerkimball** [comment]
I invited you to the developers team...and it looks like you accepted. Do you still not see the option to merge the PR?

**Comment by kkaneda** [comment]
No, I can do that now. Thank you!

**Pull request merged**
