### PR TITLE
sql: support prepare for subqueries

### PR DESCRIPTION
**Pull request by madelynnblue**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4149)

### CODE REVIEW

**Comment by andreimatei** [comment]
What exactly didn't work before this PR? Does that shortcircuit in the subquery visitor change behavior?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4149#-:-K9i2d4WO2HthDrK1bxG:2077062724)*

**Comment by mjibson** [comment]
Without the fix, the test added in this PR fails with:

panic: interface conversion: parser.Datum is parser.DValArg, not parser.DInt

```
goroutine 375 [running]:
github.com/cockroachdb/cockroach/sql/parser.glob.func108(0x1, 0xece45b26d, 0x34929958, 0x21e6520, 0xece45b26d, 0x34929958, 0x21e6520, 0xc820506c00, 0xc8204bc280, 0xc8201681e0, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:150 +0xb5
github.com/cockroachdb/cockroach/sql/parser.(*BinaryExpr).Eval(0xc820620060, 0x1, 0xece45b26d, 0x34929958, 0x21e6520, 0xece45b26d, 0x34929958, 0x21e6520, 0xc820506c00, 0xc8204bc280, ...)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:816 +0x35f
github.com/cockroachdb/cockroach/sql.(*selectNode).renderRow(0xc820154480)
	/go/src/github.com/cockroachdb/cockroach/sql/select.go:481 +0x17f
github.com/cockroachdb/cockroach/sql.(*selectNode).Next(0xc820154480, 0x7f0bc5128320)
	/go/src/github.com/cockroachdb/cockroach/sql/select.go:125 +0x1ef
github.com/cockroachdb/cockroach/sql.(*subqueryVisitor).Visit(0xc8201af5b0, 0x7f0bc69b2ea8, 0xc8204bc720, 0xc8204bc901, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/subquery.go:122 +0x100d
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x7f0bc40a8b98, 0xc8201af5b0, 0x7f0bc69b2ea8, 0xc8204bc720, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:210 +0x50
github.com/cockroachdb/cockroach/sql.(*planner).expandSubqueries(0xc8201ab000, 0x7f0bc69b2ea8, 0xc8204bc720, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/subquery.go:26 +0xf1
github.com/cockroachdb/cockroach/sql.(*selectNode).addRender(0xc820154360, 0x7f0bc69b2ea8, 0xc8204bc720, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/select.go:424 +0xc3b
github.com/cockroachdb/cockroach/sql.(*selectNode).initTargets(0xc820154360, 0xc82062a140, 0x1, 0x1, 0xc820168210)
	/go/src/github.com/cockroachdb/cockroach/sql/select.go:307 +0xf2
github.com/cockroachdb/cockroach/sql.(*planner).initSelect(0xc8201ab000, 0xc820154360, 0xc8202e4140, 0x0, 0x0, 0xc8201bc780)
	/go/src/github.com/cockroachdb/cockroach/sql/select.go:168 +0x122
github.com/cockroachdb/cockroach/sql.(*planner).Select(0xc8201ab000, 0xc8202e4140, 0x0, 0x0, 0x7ffce386ec84)
	/go/src/github.com/cockroachdb/cockroach/sql/select.go:158 +0x7f
github.com/cockroachdb/cockroach/sql.(*planner).prepare(0xc8201ab000, 0x7f0bc40a8ac8, 0xc8202e4140, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/plan.go:167 +0x384
github.com/cockroachdb/cockroach/sql.(*Executor).Prepare(0xc8200c4000, 0xc82048800d, 0x4, 0xc82048904b, 0x14, 0xc8201681e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/executor.go:240 +0x4d8
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleParse(0xc820676380, 0xc8206763b8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:322 +0x537
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc820676380, 0xc82062a000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:247 +0xf24
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serveConn(0xc8203ed4c0, 0x7f0bc40ecdb0, 0xc8204ee000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:219 +0xa15
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serve.func1(0xc8203ed4c0, 0x7f0bc5128ad8, 0xc8201ec2b8)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:126 +0x90
created by github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serve
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:131 +0x20a
```

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4149#-:-K9i3yUx02x56uPRInS7:1756585305)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4149)*

**Comment by andreimatei** [comment]
Man this `prepareOnly` is not great. I'll try to get rid of it.
Do you understand why this `subqueryVisitor` exists? Why do we need so much special code for subqueries? 

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4149#-:-K9j0tYL32O04E0RcSp4:643192792)*

**Comment by petermattis** [comment]
LGTM

Subqueries require special treatment. That's all there is to it. In fact, we only partially support subqueries. The more interesting case of correlated subqueries is not handled. See #3288.

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/bank_test.go, line 66 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4149#-K9j2nS-Mf5ogF7aOivA:-K9j2nS-Mf5ogF7aOivB:-1274278398) ([raw file](https://github.com/cockroachdb/cockroach/blob/69ba7492dd5f376b97beb8f8a5d6aec88e867866/sql/bank_test.go#L66)):*
`s/update := /const update =`. Once it is a `const`, I think it is safe to move this back to directly before its usage.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4149#-:-K9j38koaZT1fU8U7BGW:591716629)*

**Pull request merged**
