### PR TITLE
concurrency: misc cleanup related to multiple transactions holding locks on a single key

### PR DESCRIPTION
**Pull request by arulajmani**
Cleanup following-on from https://github.com/cockroachdb/cockroach/pull/109049. See individual commits for details.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109177)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-NcPpy067h0YYU2YH9xp):*
Did you mean to include this in the commit message?
___
*[`pkg/kv/kvserver/concurrency/concurrency_control.go` line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-NcPon2fD9PTMbgDjUfH:-NcPon2fD9PTMbgDjUfI:b-jsplq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2bc8a44406a0a72fca985a66095d417ff4af36e/pkg/kv/kvserver/concurrency/concurrency_control.go#L90)):*
> ```Go
> //	|         | [ lockTable ]                                     |  |  |
> //	|         | [    key1   ]    -------------+-----------------+ |  ^  |
> //	|         | [    key2   ]  /  keyLocks:  | lockWaitQueue:   |----<---<---<----+
> ```

Looks like the spacing on these diagrams got messed up.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1931 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-NcPo4AY6NyfhK162oAL:-NcPo4AY6NyfhK162oAM:b-y0wldt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7970632606ab960eb4f18a871d7ccffb754be471/pkg/kv/kvserver/concurrency/lock_table.go#L1931)):*
> ```Go
> // part of the specified transaction.
> // REQUIRES: l.mu is locked.
> func (l *lockState) releaseWritersFromTxn(txn *enginepb.TxnMeta) {
> ```

I'm not sure about these changes to pass `enginepb.TxnMeta` by value in more places. The type is still quite large (~120 bytes) and will only grow larger over time, so I think we'll still want to prefer passing it by reference through functions, even if we store it by value in the data-structure.

My suggestion would be to revert the change to all of the function/method signatures but keep the change to the `txnLock` struct.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-NcPqBj_E-wZALzRdQ2_:-NcPqBj_E-wZALzRdQ2a:b-hcq4kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8bee1667740b0c075c9d1b98616eff13dd8c48d/pkg/kv/kvserver/concurrency/lock_table.go#L264)):*
> ```Go
> 	// lockAddMaxLocksCheckInterval, locks will be cleared.
> 	//
> 	// [1] Simply put, the number of keyLocks objects in the request's lock table
> ```

Why specifically reference "the request's lock table snapshot" instead of just "the lockTable btree"?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3668 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-NcPqPGfEx5tX_iJM87v:-NcPqPGfEx5tX_iJM87w:b-rcj12f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8bee1667740b0c075c9d1b98616eff13dd8c48d/pkg/kv/kvserver/concurrency/lock_table.go#L3668)):*
> ```Go
> }
> 
> // checkMaxNumKeysLockedAndTryClear checks if the request is tracking more lock
> ```

Should we remove "Num" to mirror the field name directly?

**Review by arulajmani — COMMENTED** [review]
TFTR, RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-:-NcSdeLnDMYZ27VwDzIs:b-qrbqp3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/concurrency_control.go` line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-NcPon2fD9PTMbgDjUfH:-NcSbOSBBsWXibxLoKDd:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2bc8a44406a0a72fca985a66095d417ff4af36e/pkg/kv/kvserver/concurrency/concurrency_control.go#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like the spacing on these diagrams got messed up.
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 1931 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-NcPo4AY6NyfhK162oAL:-NcSazJ17P99csdb5ve4:b-fk0e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7970632606ab960eb4f18a871d7ccffb754be471/pkg/kv/kvserver/concurrency/lock_table.go#L1931)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm not sure about these changes to pass `enginepb.TxnMeta` by value in more places. The type is still quite large (~120 bytes) and will only grow larger over time, so I think we'll still want to prefer passing it by reference through functions, even if we store it by value in the data-structure.

My suggestion would be to revert the change to all of the function/method signatures but keep the change to the `txnLock` struct.
</blockquote></details>

That makes sense; took your suggestion and reverted all changes to function/method signatures.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-NcPqBj_E-wZALzRdQ2_:-NcSXWJq5AsydYr1OXTG:b-c13egw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8bee1667740b0c075c9d1b98616eff13dd8c48d/pkg/kv/kvserver/concurrency/lock_table.go#L264)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why specifically reference "the request's lock table snapshot" instead of just "the lockTable btree"?
</blockquote></details>

My bad, I thought I was working with a `lockTableGuardImpl` instead of a `lockTableImpl`; fixed.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 3668 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-NcPqPGfEx5tX_iJM87v:-NcSXpYi-41N2S3Hz-gM:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8bee1667740b0c075c9d1b98616eff13dd8c48d/pkg/kv/kvserver/concurrency/lock_table.go#L3668)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we remove "Num" to mirror the field name directly?
</blockquote></details>

Fixed.

**Review by nvb — APPROVED** [review]
:lgtm: mod the formatting issue in the concurrency_control.go diagram.

> Reviewed 9 of 9 files at r5, 8 of 8 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-:-NcSnjMc0tap_0_TY3ob:b-ifchla)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/concurrency_control.go` line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-NcPon2fD9PTMbgDjUfH:-NcSnP906jMjgb8RgIZ2:bp1lgz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2bc8a44406a0a72fca985a66095d417ff4af36e/pkg/kv/kvserver/concurrency/concurrency_control.go#L90)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Looks like there's also the same issue in the diagram below:
`// lockTable holds a collection of locks`

**Review by arulajmani — COMMENTED** [review]
Fixed the formatting. 

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109177#-:-NcStMfj2iLtZkEwBNtG:b-bjtp3e)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
