### PR TITLE
storage: fix GC of subsumed replicas

### PR DESCRIPTION
**Pull request by benesch**
When a range is subsumed, there is a chance that it leaves behind
replicas that are marked as destroyed with reason "merge pending." The
replica GC queue was previously misinterpreting this to mean that the
range had already been GC'd and thus the range would never get GC'd,
resulting in a proliferation of intersecting snapshot errors.

Additionally take the opportunity to teach the replica GC queue to
proactively queue a replica's left neighbor when that left neighbor is
blocking the replica from being GC'd.

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
:lgtm: but I might split the two non-test changes into separate commits (so that we have separate bisection targets in case one of them has unexpected consequences)

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31988#-:-LQ0yDF7-aE0-atoJkwF:bw1i1ux)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by benesch** [comment]
> but I might split the two non-test changes into separate commits (so that we have separate bisection targets in case one of them has unexpected consequences)

Ack, will do after this CI cycle.

**Comment by benesch** [comment]
Ok, this is split into two separate commits. The test ended up being flaky (because of course it did). I'm going to merge with the flaky test skipped and fix and unskip it in a future commit so that this lands in time for the nightly roachtest run.

bors r=bdarnell

**Review by tbg — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31988)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
