### PR TITLE
distsql: introduce an "auto" mode

### PR DESCRIPTION
**Pull request by RaduBerinde**
In "auto" mode, we run a subset of the queries that are supported. The
current heuristics run distributed queries that have:
 - joins with equality columns, or
 - scans with filter expressions (in addition to any spans)
 - sorting

This is just a starting point - if you have any ideas that are easy to implement at this stage, fire away.
CC @knz, @andreimatei, @irfansharif

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12357)

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357#-KZ1zV9t1PznMZKskVNw:-KZ1zV9uDsoT5bvG6mQd:bl7w6un) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c738ba802a7fc69560deff478e3c0b8af5714be/pkg/sql/distsql_physical_planner.go#L140)):*
> ```Go
> //    returned).
> //  - whether it is recommended that the query be run with DistSQL.
> func (dsp *distSQLPlanner) CheckSupport(tree planNode) (shouldRunDist bool, notSuppErr error) {
> ```

You're always returning (true, nil), or (false, !nil) so I don't see why you have the two return arguments. But if you are leaving it as is, you should not rely on the knowledge that the outputs are restricted to this space (see comment below).

---

*[pkg/sql/distsql_physical_planner.go, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357#-KZ1yk_lSUXAjtZNaK9O:-KZ1yk_mtv32Vy6kRKg0:b-zgit9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c738ba802a7fc69560deff478e3c0b8af5714be/pkg/sql/distsql_physical_planner.go#L197)):*
> ```Go
> 			return false, err
> 		}
> 		shouldRunDist = shouldRunDistLeft || shouldRunDistRight
> ```

I know `CheckSupport` does not ever return (false, nil), so this line does the right thing, but it is weird to see `||` when really the intention is `&&`. Or am I mistaken in what the intention is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357#-KZ1zV9t1PznMZKskVNw:-KZ2BRlCgoFvO6kaVXyj:ba3uq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c738ba802a7fc69560deff478e3c0b8af5714be/pkg/sql/distsql_physical_planner.go#L140)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

You're always returning (true, nil), or (false, !nil) so I don't see why you have the two return arguments. But if you are leaving it as is, you should not rely on the knowledge that the outputs are restricted to this space (see comment below).
</blockquote></details>

It does return `(false, nil)` (scanNode with no filter).

---

*[pkg/sql/distsql_physical_planner.go, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357#-KZ1yk_lSUXAjtZNaK9O:-KZ2BUX-h1Pivud2s-Ow:bgswxuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c738ba802a7fc69560deff478e3c0b8af5714be/pkg/sql/distsql_physical_planner.go#L197)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I know `CheckSupport` does not ever return (false, nil), so this line does the right thing, but it is weird to see `||` when really the intention is `&&`. Or am I mistaken in what the intention is?
</blockquote></details>

The intention is OR. If either the left or the right plan warrants distribution, then we should distribute.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357)*

**Comment by arjunravinarayan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357#-KZ1zV9t1PznMZKskVNw:-KZ2KBpfkwtkbsTKfi3y:b-xqs6w2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c738ba802a7fc69560deff478e3c0b8af5714be/pkg/sql/distsql_physical_planner.go#L140)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It does return `(false, nil)` (scanNode with no filter).
</blockquote></details>

Sounds good. My mistake.

---

*[pkg/sql/distsql_physical_planner.go, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357#-KZ1yk_lSUXAjtZNaK9O:-KZ2KGg_7m3f5e81SpcQ:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c738ba802a7fc69560deff478e3c0b8af5714be/pkg/sql/distsql_physical_planner.go#L197)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The intention is OR. If either the left or the right plan warrants distribution, then we should distribute.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357)*

**Comment by irfansharif** [comment]
LGTM, hopefully aggregations & multi-stage `DISTINCT` as soon as I have them up haha.

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 179 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357#-KZ2SzPG7k5OSDp6P2LQ:-KZ2SzPG7k5OSDp6P2LR:bb7lbs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/69467fff290de24bdf9172bbb0d8eba6777550a3/pkg/sql/distsql_physical_planner.go#L179)):*
> ```Go
> 		}
> 		// If we have to sort, distribute the query.
> 		shouldDistribute = shouldDistribute || (n.top.sort != nil && n.top.sort.needSort)
> ```

nice

---

*[pkg/sql/distsql_physical_planner.go, line 205 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357#-KZ2VYK_1KBA_tBZkqTP:-KZ2VYK_1KBA_tBZkqTQ:brd80ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/69467fff290de24bdf9172bbb0d8eba6777550a3/pkg/sql/distsql_physical_planner.go#L205)):*
> ```Go
> 
> 	case *scanNode:
> 		// We recommend running scans distributed only if we have a filtering
> ```

how about if we'd also recommend distribution if it is a full table scan? Then we might get some admission control that sounds good...

---

*[pkg/sql/distsql_physical_planner.go, line 220 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357#-KZ2WRzE234nuIIYtWrG:-KZ2WRzE234nuIIYtWrH:ba69as7) ([raw file](https://github.com/cockroachdb/cockroach/blob/69467fff290de24bdf9172bbb0d8eba6777550a3/pkg/sql/distsql_physical_planner.go#L220)):*
> ```Go
> 			return false, err
> 		}
> 		shouldRunDistTable, err := dsp.CheckSupport(n.table)
> ```

I'm confused... Didn't follow too much about how `indexJoinWorks`, but `n.table` is not in its final state here, obviously. Right? We keep modifying its spans. So how can we ask it if it recommends distribution?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12357#-:-KZ2WlBXVrT6kC0soGdw:bg7igk9)*

**Comment by RaduBerinde** [comment]
Good points, see #12417.

**Comment by jseldess** [comment]
@RaduBerinde, when should we start thinking about docs for distsql?

**Comment by RaduBerinde** [comment]
@jseldess I think we are still in an early stage and we have quite a few things that are not supported yet which would be annoying to document. I would hold off on adding anything to the docs for now (though of course it's never to early to start working on them..)

**Pull request merged**
