### PR TITLE
idxrecs: add datadriven test to IndexRecCache

### LINKED ISSUE #116896: increase test coverage of IndexRecCache
Increase test coverage of IndexRecCache, including test such as limit being reached, eviction, etc.

Changes on the functions will likely be required, for example injecting the time function so that a test can control how time advances.

Jira issue: CRDB-34835

### PR DESCRIPTION
**Pull request by dhartunian**
This test exercises the basic contract that IndexRecCache advertises regarding when the cache is full, cleared, etc.

A number of constants were made configurable for convenience.

Resolves: #116896
Epic: None

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118876)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/sql/idxrecommendations/testdata/index-rec-cache` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-Nq3AWbODsuZAsWZU8fL:-Nq3AWbODsuZAsWZU8fM:bxcd6nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/71feb15b9d41cabb03d5574276ebc47a52ddf5d1/pkg/sql/idxrecommendations/testdata/index-rec-cache#L9)):*
> ```
> false
> 
> # DDL is ignored.
> ```

can you add one more test just confirming you don't generate for internal statements, no matter how many executions
(I see you already created the code to get the value)
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-Nq3AwpxBxNKO857Cs93:-Nq3AwpxBxNKO857Cs94:b-hh49ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/71feb15b9d41cabb03d5574276ebc47a52ddf5d1/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L177)):*
> ```Go
> 		planHash     uint64
> 		database     string
> 		updateCount  int
> ```

you're not using updateCount anywhere
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-Nq3B6j89X70r_g9IfcD:-Nq3B6j89X70r_g9IfcE:b-8b2573) ([raw file](https://github.com/cockroachdb/cockroach/blob/71feb15b9d41cabb03d5574276ebc47a52ddf5d1/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L178)):*
> ```Go
> 		database     string
> 		updateCount  int
> 		setCacheSize int
> ```

you're not using setCacheSize anywhere

**Review by petermattis — COMMENTED** [review]
Love to see some more datadriven testing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-:-Nq5kRgY3D3AaukUhDsC:b-frqj9h)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[`pkg/sql/idxrecommendations/testdata/index-rec-cache` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-Nq5jqHi5bLwG5RfuIHo:-Nq5jqHi5bLwG5RfuIHp:bocftq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/71feb15b9d41cabb03d5574276ebc47a52ddf5d1/pkg/sql/idxrecommendations/testdata/index-rec-cache#L3)):*
> ```
> update fingerprint=f1 planHash=123 database=db stmtType=DML
> ----
> ok
> ```

I think `update` should print out the index recommendations that `UpdateIndexRecommendations` returns. That way you can see what update is doing. When this is done, some of the test cases should use different `planHash` and `database` values so we can see that `update` is actually caching state correctly.

Hmm, I'm not sure if printing out the returned index recommendations is sufficient. Perhaps there should be a separate `get` command that gets the index recommendations for a fingerprint/database combo.
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-Nq5j7Jb7lngOIdcafw0:-Nq5j7Jb7lngOIdcafw1:bgep86f) ([raw file](https://github.com/cockroachdb/cockroach/blob/71feb15b9d41cabb03d5574276ebc47a52ddf5d1/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L186)):*
> ```Go
> 		repeat := int64(1)
> 		tc := testCase{}
> 		for _, ca := range d.CmdArgs {
> ```

I thought `datadriven` had convenience routines for extracting `key=value` data from the command. I'm hoping those can simplify this parsing.

**Review by dhartunian — COMMENTED** [review]
Added more test cases for various cache key combinations as well as verifying what's inside the cache with various keys.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-:-NqER6je-xh-hzotyPjy:bgp256p)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @petermattis)

___
*[`pkg/sql/idxrecommendations/testdata/index-rec-cache` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-Nq5jqHi5bLwG5RfuIHo:-NqER-9GEMpcf6Kj0RaM:b4t6hd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/71feb15b9d41cabb03d5574276ebc47a52ddf5d1/pkg/sql/idxrecommendations/testdata/index-rec-cache#L3)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think `update` should print out the index recommendations that `UpdateIndexRecommendations` returns. That way you can see what update is doing. When this is done, some of the test cases should use different `planHash` and `database` values so we can see that `update` is actually caching state correctly.

Hmm, I'm not sure if printing out the returned index recommendations is sufficient. Perhaps there should be a separate `get` command that gets the index recommendations for a fingerprint/database combo.
</blockquote></details>

Every `update` now returns the result of a `get` on the same key to verify the cache state.
___
*[`pkg/sql/idxrecommendations/testdata/index-rec-cache` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-Nq3AWbODsuZAsWZU8fL:-NqDb8_C2FOcZEbKQYwE:b-9ab581) ([raw file](https://github.com/cockroachdb/cockroach/blob/71feb15b9d41cabb03d5574276ebc47a52ddf5d1/pkg/sql/idxrecommendations/testdata/index-rec-cache#L9)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you add one more test just confirming you don't generate for internal statements, no matter how many executions
(I see you already created the code to get the value)
</blockquote></details>

This one has a repeat of 6, which should otherwise be enough to get it over the threshold.

Added separate case at the bottom after the cache is cleared, where we also test inserting a rec for a DDL which does not result in anything being persisted.
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-Nq3AwpxBxNKO857Cs93:-NqD_47U0b365Fbpt72h:b-wnfmk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/71feb15b9d41cabb03d5574276ebc47a52ddf5d1/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L177)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you're not using updateCount anywhere
</blockquote></details>

Done. Removed.
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-Nq3B6j89X70r_g9IfcD:-NqD_3zgBZYyPCepa9ts:b-wnfmk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/71feb15b9d41cabb03d5574276ebc47a52ddf5d1/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L178)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you're not using setCacheSize anywhere
</blockquote></details>

Done. Removed.
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-Nq5j7Jb7lngOIdcafw0:-NqD_6B06dt0W7LNeKb4:byxhm32) ([raw file](https://github.com/cockroachdb/cockroach/blob/71feb15b9d41cabb03d5574276ebc47a52ddf5d1/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L186)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I thought `datadriven` had convenience routines for extracting `key=value` data from the command. I'm hoping those can simplify this parsing.
</blockquote></details>

Yep, using `Scan` API. Done.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118876)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache.go` line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqInce80H-pRGoO9GJv:-NqInce80H-pRGoO9GJw:b-1bqgit) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/idx_recommendations_cache.go#L36)):*
> ```Go
> }
> 
> func (i indexRecInfo) Recommendations() []indexrec.Rec {
> ```

If you're just using these from tests, the accessors are a bit overkill. It is fine for the test of a data structure to reach inside its internals to verify state.
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache.go` line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqInjak-sXeFImvb7Vk:-NqInjal5Fm9beUMWFUU:b9z5gkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/idx_recommendations_cache.go#L88)):*
> ```Go
> const defaultTimeThresholdForDeletion = 24 * time.Hour
> 
> func (idxRec *IndexRecCache) SetRecTimeoutDurationForTest(recTimeoutDuration time.Duration) {
> ```

If these are only used by tests, it is fine to omit the setters and set the tunables directly.
___
*[`pkg/sql/idxrecommendations/testdata/index-rec-cache` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqIoPhlANc5tXP5M3WK:-NqIoPhlANc5tXP5M3WL:bgdr311) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/testdata/index-rec-cache#L21)):*
> ```
> update fingerprint=f2 planHash=123 database=db stmtType=DML repeat=4
> ----
> recs=[] execCount=4 found=true cacheSize=2
> ```

The `found=true` and `cacheSize=2` makes me think that a recommendation was stored. Is the comment above this test case out of date?
___
*[`pkg/sql/idxrecommendations/testdata/index-rec-cache` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqIoXYIEtvySNNfQUPc:-NqIoXYIEtvySNNfQUPd:b5bropk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/testdata/index-rec-cache#L28)):*
> ```
> 
> # 5 repeats triggers recommendation generation.
> update fingerprint=f3 planHash=123 database=db stmtType=DML repeat=5
> ```

Should this specify a `rec=` argument to make it clear that a recommendation was stored.
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqIpa6s5vAZk6r34Pij:-NqIpa6s5vAZk6r34Pik:b-g7r2wt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L174)):*
> ```Go
> 	var cacheUnderTest = idxrecommendations.NewIndexRecommendationsCache(st)
> 
> 	type testCase struct {
> ```

I'm not sure this struct is actually doing anything useful. You could just as easily define its member variables inside the `RunTest` closure instead of the `tc := testCase{}` declaration.
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqIpJtw2yYIaE1RiRyt:-NqIpJtw2yYIaE1RiRyu:beligk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L218)):*
> ```Go
> 		case "update":
> 			for i := int64(0); i < repeat; i++ {
> 				var recs []indexrec.Rec = nil
> ```

Go initializes variables to their zero value automatically. So this is equivalent to:

```
var recs []indexrec.Rec
```

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118876)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @petermattis)

___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache.go` line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqInce80H-pRGoO9GJv:-NrfL4ru6__ZzoQrkLZH:bfpf6t1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/idx_recommendations_cache.go#L36)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If you're just using these from tests, the accessors are a bit overkill. It is fine for the test of a data structure to reach inside its internals to verify state.
</blockquote></details>

Done. Split this test into separate file that can share the package. The other tests need to be in separate package to avoid circular dep.
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache.go` line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqInjak-sXeFImvb7Vk:-Nrfv4jKDoqJeepWhWJA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/idx_recommendations_cache.go#L88)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If these are only used by tests, it is fine to omit the setters and set the tunables directly.
</blockquote></details>

Done.
___
*[`pkg/sql/idxrecommendations/testdata/index-rec-cache` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqIoPhlANc5tXP5M3WK:-NrfzxtF4h4vbF8cqQAn:b-7zlc5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/testdata/index-rec-cache#L21)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The `found=true` and `cacheSize=2` makes me think that a recommendation was stored. Is the comment above this test case out of date?
</blockquote></details>

`found` is telling us whether the fingerprint is being tracked in the cache. it's only `false` when we update it with an "ignored" statement.
The `should` calls are the ones that check whether an index recommendation should be generated. That's only when the count is high enough.
___
*[`pkg/sql/idxrecommendations/testdata/index-rec-cache` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqIoXYIEtvySNNfQUPc:-Nrg-KvD7qy_NydrEy1V:b6sn8y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/testdata/index-rec-cache#L28)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this specify a `rec=` argument to make it clear that a recommendation was stored.
</blockquote></details>

Not here. The `update` test case below is the one that stores a recommendation.

The user of the cache always calls `should` after each execution to check and see if a fingerprint has met the necessary thresholds, and then always calls `update`. 

If the `should` told us to generate a recommendation, we call `update` with a rec. This is mirrored in the 3 cases for fingerprint `f3` here and below. We update `f3` to meet the threshold, check that we return `true` on the `should` call, and the update it again with a recommendation.
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqIpa6s5vAZk6r34Pij:-Nrg1-gz4HwlHv-ZICaY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L174)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure this struct is actually doing anything useful. You could just as easily define its member variables inside the `RunTest` closure instead of the `tc := testCase{}` declaration.
</blockquote></details>

Done.
___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NqIpJtw2yYIaE1RiRyt:-Nrg0R8IAla2HIsvX3Wm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b21902092607066ce9956cdf8d9d7516d7cecb8/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L218)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Go initializes variables to their zero value automatically. So this is equivalent to:

```
var recs []indexrec.Rec
```
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-:-NrlOlxJ7vy4rD_HYI0_:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @maryliag)

___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NrlOaoqEJoEXIFxXo5k:-NrlOaoqEJoEXIFxXo5l:b-ala8vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/be4c9d70f224dd88224cfc55b460b5210a2d7bab/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L46)):*
> ```Go
> 	var cacheUnderTest = NewIndexRecommendationsCache(st)
> 
> 	type testCase struct {
> ```

Looks like you can remove this type now.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118876)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @maryliag, and @petermattis)

___
*[`pkg/sql/idxrecommendations/idx_recommendations_cache_test.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118876#-NrlOaoqEJoEXIFxXo5k:-NrlptlED3XzaovfT3e5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be4c9d70f224dd88224cfc55b460b5210a2d7bab/pkg/sql/idxrecommendations/idx_recommendations_cache_test.go#L46)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Looks like you can remove this type now.
</blockquote></details>

Done.

**Review by abarganier — APPROVED** [review]
LGTM

**Comment by dhartunian** [comment]
TFTRs

bors r+

**Pull request merged**
