### PR TITLE
geomfn: apply bounding box checks for DWithin/DFullyWithin

### PR DESCRIPTION
**Pull request by otan**
We are able to optimize DWithin/DFullyWithin by extended the bounding
box for geometry types by distance units in each direction and
checking if they intersect / covers.

Also implement cartesian bounding box covers and use it for other
relevant operations.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geomfn/distance.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50654#-MAw3XMR2CYaPzkweSEt:-MAw3XMR2CYaPzkweSEu:bhloanu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e22b96c3ad93dbaa35a6d3cc0783c3a926c947c/pkg/geo/geomfn/distance.go#L62)):*
> ```Go
> 		return false, errors.Newf("dwithin distance cannot be less than zero")
> 	}
> 	if !a.SpatialObject().BoundingBox.Buffer(d).Intersects(b.SpatialObject().BoundingBox.Buffer(d)) {
> ```

why is this extending both bounding boxes? Isn't is sufficient to extend only one? Same for DFullyWithin below.

Also looking at some earlier bbox acceleration code, why is Covers using intersection of bboxes instead of covering of bboxes. Isn't it true that covers implies bounding boxes also cover? So !bbox.covers => !covers
Which would mean that DFullyWithin can do better than intersection.

**Comment by otan** [comment]
___
*[pkg/geo/geomfn/distance.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50654#-MAw3XMR2CYaPzkweSEt:-MB07I0E9L53akcSOnWF:b-17ktf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e22b96c3ad93dbaa35a6d3cc0783c3a926c947c/pkg/geo/geomfn/distance.go#L62)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is this extending both bounding boxes? Isn't is sufficient to extend only one? Same for DFullyWithin below.

Also looking at some earlier bbox acceleration code, why is Covers using intersection of bboxes instead of covering of bboxes. Isn't it true that covers implies bounding boxes also cover? So !bbox.covers => !covers
Which would mean that DFullyWithin can do better than intersection.
</blockquote></details>

Yep. Done both!

**Comment by otan** [comment]
i've rebased this on top of the other bounding box PR. only second commit relevant here!

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50654#-:-MB1f4gP2XVmT8qXfmSo:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geomfn/binary_predicates.go, line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50654#-MB1ehwe4O3tZL10omRH:-MB1ehwe4O3tZL10omRI:b-hg62jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c699e3e8c7fa29bfd3f52b5f0db4436cd0c9413a/pkg/geo/geomfn/binary_predicates.go#L86)):*
> ```Go
> 	if !a.CartesianBoundingBox().Covers(b.CartesianBoundingBox()) {
> 		return false, nil
> 	}
> ```

how about doing bounding box equality instead?

**Comment by otan** [comment]
___
*[pkg/geo/geomfn/binary_predicates.go, line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50654#-MB1ehwe4O3tZL10omRH:-MB1fwlA6L-ZtNL0g0sk:b-k1lsr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c699e3e8c7fa29bfd3f52b5f0db4436cd0c9413a/pkg/geo/geomfn/binary_predicates.go#L86)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about doing bounding box equality instead?
</blockquote></details>

Could do, but scared of floating point errors enough such that I'll keep it as this for now :P

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
