### PR TITLE
storage: fix a series of intent resolution bugs with ignored seq nums

### LINKED ISSUE #117553: storage: intent resolution incorrectly updates intents with ignored seq nums
**Describe the problem**

The logic in mvccResolveWriteIntent was structured in such a way that if an intent contained both ignored and non-ignored seq nums in its intent history, the intent may end up being updated instead of aborted or unmodified.

**To Reproduce**

For the following examples, assume the intent has a history ["a", "b"] where "a" is written first, and "b" is ignored.

1. The intent resolution has status aborted. Instead of aborting the intent, it is modified to have value "a" and an empty intent history.

2. The intent resolution has status pending, and the intent has a lower epoch than the resolution. The intent should be aborted because the new epoch may not write it again. Instead, it is updated with value "a" and an empty intent history.

3. Same as 2 but the intent resolution has status committed.

4. The intent resolution has status pending, the intent is not pushed and has a higher epoch than the resolution. The intent should not be updated because the intent history is updated only when the epochs match. Instead, it is updated with value "a" and an empty intent history.

5. Same as 4 but the intent is pushed. The intent should be updated to bump its timestamp in order to unblock the pusher. The intent history should not be updated for the same reason as in 3. Instead, the intent is updated with value "a" and an empty intent history.

Additionally, in cases 1, 2, 3 and 4 above, the resulting intent is not committed but a MVCCCommitIntentOp is logged erroneously.

**Additional context**
This has most likely been an issue since the ignored seq nums were introduced into the MVCC code in https://github.com/cockroachdb/cockroach/commit/f6a4dc5aa6cd21f535336580f0c8282a9f208a77.

Jira issue: CRDB-35245

### PR DESCRIPTION
**Pull request by miraradeva**
Previously, the logic in mvccResolveWriteIntent was structured in such a
way that if an intent contained both ignored and non-ignored seq nums
in its intent history, the intent may end up being updated instead of
aborted or unmodified (see examples in 9f00f2a5505).

This commit fixes the bugs by ensuring that the intent history is
modified only when an intent resolution update is not aborted, and the
update and the actual intent have the same epoch.

Fixes: https://github.com/cockroachdb/cockroach/issues/117553

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117541#-:-NnjJdfA88MWPGRJM33j:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @miraradeva)

___
*[`pkg/storage/mvcc.go` line 5183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117541#-NnjFRIW6Im5Umso1d0h:-NnjFRIW6Im5Umso1d0i:br7l7nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0a8c67461cc9ef27f93be989f94c86d8ae7c364/pkg/storage/mvcc.go#L5183)):*
> ```Go
> 	iter MVCCIterator,
> 	ms *enginepb.MVCCStats,
> 	update roachpb.LockUpdate,
> ```

Should we perform this same rename in `MVCCResolveWriteIntent` and `MVCCResolveWriteIntentRange`?
___
*[`pkg/storage/mvcc.go` line 5440 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117541#-NnjJ7FS1_OoYO2L3EIR:-NnjJ7FS1_OoYO2L3EIS:bnyi3zh) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e51fbb0f4d539ff5fc06bb8704bebddda23448/pkg/storage/mvcc.go#L5440)):*
> ```Go
> 		// Update or remove the metadata key.
> 		var metaKeySize, metaValSize int64
> 		var logicalOp MVCCLogicalOpType
> ```

Nice additional find!

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117541)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @nvanbenschoten)

___
*[`pkg/storage/mvcc.go` line 5440 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117541#-NnjJ7FS1_OoYO2L3EIR:-NnjMKt63WZ_I5-k3yEJ:b68cvxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e51fbb0f4d539ff5fc06bb8704bebddda23448/pkg/storage/mvcc.go#L5440)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice additional find!
</blockquote></details>

Forgot to mention, this change around the logical op type was not necessary. The logical op inconsistency was fixed by the `(commit || inProgress) && epochsMatch` condition above. But I think the change here makes it less likely that we'll end up in an inconsistent state in the future.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, 3 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117541#-:-Nnj_pCvD8QeYVrAoiAB:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by miraradeva** [comment]
bors r=nvanbenschoten

**Pull request merged**
