### PR TITLE
exec: add "auto" vectorize setting and make it default

### LINKED ISSUE #38620: exec: finalize vectorize setting name and behavior
Currently, the `experimental_vectorize` flag has 3 values: off, on and always. Off means never run with vectorize, and is the default. On means run everything that vectorized supports with vectorized. Always means run everything with vectorized, even the things that vectorized doesn't support.

This issue tracks changing this setting to what it will look like in 19.2.

We need to change the name of the setting to remove the `experimental_` prefix, since anything that's going to be enabled by default shouldn't have `experimental` in its name.
Then, we need to add a new setting (maybe called on? auto? streaming?) that encodes the behavior of planning vectorized only if all operators are streaming operators.

### LINKED ISSUE #38920: exec: tracking issue for turning on "auto" by default
- [x] [exec: tracking issue for unit test failures ](https://github.com/cockroachdb/cockroach/issues/38935)

- [x] unordered synchronizer is blocked forever #39092

This is an incomplete list of failing logic tests when attempting to turn streaming operators through vectorized engine by default.

- [x] #38995

Failures on `local` config:
- [x] #38807
- [x] #38858
- [x] #38775

Failures on `fakedist` config:
- [x] `EXISTS` hanging #38919 (on `fakedist-opt` this problem occurs on `explain_analyze` logic test)
- [x] #38651
- [x] a crash due to incorrect type conversion #38918
- [x] mismatched batch width and schema length (I, @asubiotto can take this one) #38970
- [x] no output
  **Update: I haven't seen this issue after #38992, so I'm marking it as resolved here.**
  - `alter_table:742: SELECT * from default_err_test ORDER BY foo`
  - `distinct_on:132: SELECT DISTINCT ON (c, a) b, c, a FROM abc ORDER BY c, a, b DESC`
  - **`optimizer:30: SELECT * FROM test.t ORDER BY 1-t.k`**
  - `order_by:22: SELECT c FROM t ORDER BY c`
  - `ordinal_references:35: SELECT b, a FROM foo ORDER BY @1`
  - `suboperators:86: SELECT * FROM abc WHERE a = ANY(ARRAY[1,3]) ORDER BY a`
  - *this also occured on `5node-dist` config on `distsql_agg:419: SELECT c, count(*) FROM nullables GROUP BY c;`*
  - (an example failure):
```
                    testdata/logic_test/alter_table:742: SELECT * from default_err_test ORDER BY foo
                    expected:
                        bar
                        baz
                        foo
                        
                    but found (query options: "") :
                        
```
- [x] probably a problem with some nodes running vectorized while others running row execution
  **Update: I haven't seen this issue after #38992, so I'm marking it as resolved here. I believe the hypothesis about some nodes running vectorized while others running row execution was correct.**
  - **`join:12: SELECT * FROM onecolumn AS a(x) CROSS JOIN onecolumn AS b(y)`**
  - **`srfs:210: SELECT t.*, u.*, generate_series(1,2), generate_series(3, 4) FROM t, u`**
  - **`union:264: SELECT a FROM (SELECT a FROM a UNION ALL SELECT a FROM c) ORDER BY a`**
  - **`window:53: SELECT avg(k) OVER () FROM kv ORDER BY 1`**
  - *this also occurred on `5node-dist` config on `explain_analyze_plans:91: SELECT url FROM [EXPLAIN ANALYZE (DISTSQL) SELECT avg(k) OVER () FROM kv]`*
  - (an example failure):
```
                testdata/logic_test/join:12: SELECT * FROM onecolumn AS a(x) CROSS JOIN onecolumn AS b(y)
                expected success, but found
                (XXUUU) [n2] decoding error: received data before header and/or typing info
                stream_decoder.go:79: in AddMessage()
```
 - [x] partial output
  **Update: I haven't seen this issue after #38992, so I'm marking it as resolved here (although I observed a similar issue in #38994).**
```
                    testdata/logic_test/upsert:77: SELECT * from no_unique ORDER BY a, b
                    expected:
                        a  b
                        1  2
                        1  2
                        1  2
                        1  3
                        3  2
                        
                    but found (query options: "colnames") :
                        a  b
                        
```
 - [x] slice out of bounds
  **Update: I haven't seen this issue after #38992, so I'm marking it as resolved here.**
  - `views:117: SELECT * FROM v1 AS v1 INNER JOIN v2 AS v2 ON v1.a = v2.x`
  - `optimizer:54: SELECT * FROM t WHERE EXISTS(SELECT * FROM xy WHERE x=t.k)`
```
                testdata/logic_test/with:12: WITH t AS (SELECT a FROM y WHERE a < 3)
                  SELECT * FROM x NATURAL JOIN t
                expected success, but found
                (XXUUU) unexpected error from the vectorized runtime: unexpected error from the vectorized runtime: runtime error: slice bounds out of range
                error.go:56: in func1()
```

Interestingly, adding `5node-dist-vec` config to some of these logic tests and running them on master doesn't trigger the same issues (some succeed, some fail on a different query).

### PR DESCRIPTION
**Pull request by yuzefovich**
First commit renames Vectorize to VectorizeMode and removes
"experimental_" prefix of vectorize setting.

Second commit adds a fourth option "auto" to vectorize execution mode setting
which plans the queries containing only streaming operators via the
vectorized engine. This option is made a default one. Other options
have been renamed: "on" -> "experimental_on" and "always" ->
"experimental_always" to highlight for users the risk of using them.

Fixes: #38620.
Fixes: #38920.

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

___
*[pkg/sql/exec_util.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38777#-LjNT8l5BIRWK8Xljv6f:-LjNT8l5BIRWK8Xljv6g:bq7epx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2792fd3ad5bf93c959e353bda7c53af37d331/pkg/sql/exec_util.go#L157)):*
> ```Go
> 		int64(sessiondata.VectorizeOff):       "off",
> 		int64(sessiondata.VectorizeOn):        "on",
> 		int64(sessiondata.VectorizeAlways):    "always",
> ```

i think one of the things we had discussed was to rename the "always" value to something like "experimental_on" (and maybe something similar for the current "on" setting?) so that it's more clear to users that it's likely broken. i'm not sure if we reached a firm conclusion, but just wondering if you had considered that.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

___
*[pkg/sql/exec_util.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38777#-LjNT8l5BIRWK8Xljv6f:-LjNTuyW7haLmJNCbH-d:btdhzew) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2792fd3ad5bf93c959e353bda7c53af37d331/pkg/sql/exec_util.go#L157)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think one of the things we had discussed was to rename the "always" value to something like "experimental_on" (and maybe something similar for the current "on" setting?) so that it's more clear to users that it's likely broken. i'm not sure if we reached a firm conclusion, but just wondering if you had considered that.
</blockquote></details>

I was actually hoping to reach a consensus about the naming while reviewing this PR, so thanks for starting up the discussion :)

I agree with your point, and I think I'm leaning towards `on -> experimental_all` and `always -> experimental_forced`, but I'm definitely open to suggestions so that it's clear that both can be broken and that choosing the latter sounds harsh.

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

___
*[pkg/sql/exec_util.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38777#-LjNT8l5BIRWK8Xljv6f:-LjRSVpW-SrA-Kk4d8Mv:bwbsujv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2792fd3ad5bf93c959e353bda7c53af37d331/pkg/sql/exec_util.go#L157)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I was actually hoping to reach a consensus about the naming while reviewing this PR, so thanks for starting up the discussion :)

I agree with your point, and I think I'm leaning towards `on -> experimental_all` and `always -> experimental_forced`, but I'm definitely open to suggestions so that it's clear that both can be broken and that choosing the latter sounds harsh.
</blockquote></details>

I like that, though it might also be nice to mirror the `distsql` setting's options: https://github.com/cockroachdb/cockroach/blob/813b0146e763e8f44c4cb45e498e68e6ace9bc2d/pkg/sql/sessiondata/session_data.go#L206-L216
So we could do `off`, `auto`, `experimental_on`, and `experimental_always`

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38777)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec_util.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38777#-LjNT8l5BIRWK8Xljv6f:-LjRWpGO9stRWNi0MDBo:b-2p8wi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2792fd3ad5bf93c959e353bda7c53af37d331/pkg/sql/exec_util.go#L157)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I like that, though it might also be nice to mirror the `distsql` setting's options: https://github.com/cockroachdb/cockroach/blob/813b0146e763e8f44c4cb45e498e68e6ace9bc2d/pkg/sql/sessiondata/session_data.go#L206-L216
So we could do `off`, `auto`, `experimental_on`, and `experimental_always`
</blockquote></details>

Aside from just using consistent language, I think it would be nice to use `auto` rather than `streaming` because later we might want to start gradually enabling non-streaming operators by default. So it could be nice to have a more generic term like "auto" which represents everything we're comfortable enabling by default.

**Comment by yuzefovich** [comment]
Here is an updated performance hit on KV99 workload:
```
name             old ops/s   new ops/s   delta
KV99-throughput  20.7k ± 5%  17.7k ± 2%  -14.54%  (p=0.016 n=5+4)

name             old ms/s    new ms/s    delta
KV99-P50          19.3 ± 8%   21.5 ± 2%  +11.51%  (p=0.016 n=5+4)
KV99-Avg          4.70 ± 0%   5.57 ± 4%  +18.62%  (p=0.029 n=4+4)
```

**Comment by yuzefovich** [comment]
I like Solon's suggestion about `off`, `auto`, `experimental_on`, and `experimental_always`.

**Comment by jordanlewis** [comment]
Yeah, I agree - I like that suggestion too.

**Comment by yuzefovich** [comment]
Alright, finally this is RFAL.

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: let's get this baby in!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38777#-:-LlIg7ZTDIx2ASg0CWpB:bwxkala)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Comment by asubiotto** [comment]
Should we wait until Monday to enable this so that we don't feel pressured to address any fallout?

**Comment by jordanlewis** [comment]
I think I'd prefer to see this go in so that the nightlies can fail over the weekend and we'll have a fresh crop of stuff to look in by Monday :) Just don't check your work email til next week.

**Comment by yuzefovich** [comment]
I ran KV99 tests again:
```
name             old ops/s   new ops/s   delta
KV99-throughput  21.1k ± 3%  17.5k ± 1%  -17.14%  (p=0.008 n=5+5)

name             old ms/s    new ms/s    delta
KV99-P50          16.7 ± 7%   19.9 ± 0%  +19.16%  (p=0.008 n=5+5)
KV99-Avg          5.12 ± 2%   6.00 ± 0%  +17.19%  (p=0.016 n=5+4)
```
so a slightly bigger performance hit than we observed previously (probably because of the enhanced `SupportsVectorized` check).

I agree with Jordan, let's merge it now, and we will see the fresh fallout on Monday.

Thanks for the review and the inputs!

bors r+

**Pull request merged**
