### PR TITLE
kv,quotapool,stopper: make the DistSender async concurrency limit configurable

### PR DESCRIPTION
**Pull request by ajwerner**
This PR has the high level goal of making the DistSender concurrency limit configuable. To achieve this goal it changes `stop.Stopper.RunLimitedAsyncTask` to take a quotapool rather than a raw channel to act as the semaphore. It additionally extends the quotapool to both have a non-blocking `Try` variant and to have a resizable capacity. It then adopts this quotapool in place of the old channels. The first commit adds benchmarking to demonstrate that the cost of switching to a quotapool isn't too high.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 13 of 13 files at r4, 2 of 2 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45452)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/dist_sender.go, line 1278 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16b88iCfFM6OrVGFxH:-M16b88j3PBVnFFEUbdC:bmfakzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/291f89d083de26ba19e9a56aa453446c1e634a7c/pkg/kv/dist_sender.go#L1278)):*
> ```Go
> 	responseCh chan response,
> ) bool {
> ```

Stray line.
___
*[pkg/server/status.go, line 1645 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16bOCi5yAPq9YT6p03:-M16bOCi5yAPq9YT6p04:bw2zy44) ([raw file](https://github.com/cockroachdb/cockroach/blob/291f89d083de26ba19e9a56aa453446c1e634a7c/pkg/server/status.go#L1645)):*
> ```Go
> 
> 	// Issue the requests concurrently.
> 	sem := quotapool.NewIntPool("node status", maxConcurrentRequests)
> ```

Do you need to `defer sem.Close(...)` in these cases?
___
*[pkg/util/quotapool/intpool.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16abzU1WL7_YLN_8xC:-M16abzVCcleA1NR8uiu:blqmjbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1cb3e76c2ce52601db9bfeb495c9feac8c51494/pkg/util/quotapool/intpool.go#L125)):*
> ```Go
> }
> 
> // TryAcquire is like Acquire but if there is insufficient quota to acquire
> ```

s/acquire immediately will/acquire immediately the method will/
___
*[pkg/util/quotapool/intpool.go, line 213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16aiIN0YBrmDKjZXqT:-M16aiIO-4oNZliecljh:b-iqnqyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1cb3e76c2ce52601db9bfeb495c9feac8c51494/pkg/util/quotapool/intpool.go#L213)):*
> ```Go
> }
> 
> // TryAcquireFunc is like AcquireFunc but if insufficient quota exists will
> ```

s/exists will/exists the method will/
___
*[pkg/util/quotapool/intpool.go, line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16aTiJ-FJ_eOyAPUkl:-M16aTiJ-FJ_eOyAPUkm:b-2ak45s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1cb3e76c2ce52601db9bfeb495c9feac8c51494/pkg/util/quotapool/intpool.go#L358)):*
> ```Go
> }
> 
> func (r *intRequestNoWait) ShouldWait() bool { return false }
> ```

nit: why is the one above wrapped but this one is not?
___
*[pkg/util/quotapool/intpool.go, line 352 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16dBJm80p10AoMEcQ3:-M16dBJm80p10AoMEcQ4:bqhqgrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6227972e4c4ffa08bcf8f4727a2c505990b97c08/pkg/util/quotapool/intpool.go#L352)):*
> ```Go
> // affected. When the capacity is increased, new quota will be added. In the
> // case of rapid fluctuations in capacity, much more quota may be outstanding
> // than was ever the limit.
> ```

Could you say something about when this converges to the capacity value that was last set? Is it guaranteed to?
___
*[pkg/util/quotapool/intpool.go, line 358 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16dXxj3FacsRfqXgaI:-M16dXxj3FacsRfqXgaJ:byyng8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6227972e4c4ffa08bcf8f4727a2c505990b97c08/pkg/util/quotapool/intpool.go#L358)):*
> ```Go
> // the capacity back to 100, we can hand out 99 new alloc to be acquired.
> // This could be mitigated with additional bookkeeping but the complexity is not
> // obviously worth it.
> ```

What extra bookkeeping would it take? We know the current quota capacity and the amount of quota available, right? Would we need to track the maximum outstanding quota as well, since that's no longer exactly `capacity - available` immediately after the capacity is dropped?

Would allowing for negative capacity solve this issue without extra bookkeeping?
___
*[pkg/util/quotapool/intpool.go, line 367 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16eIWq0mjvkhqJjfBt:-M16eIWq0mjvkhqJjfBu:b-heg3aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/6227972e4c4ffa08bcf8f4727a2c505990b97c08/pkg/util/quotapool/intpool.go#L367)):*
> ```Go
> 		toRelease = newCapacity - oldCapacity
> 	}
> 	ia := p.newIntAlloc(toRelease)
> ```

This can and probably should be moved into the condition.
___
*[pkg/util/quotapool/intpool_test.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16_Utb5aLZx98ykIEj:-M16_Utb5aLZx98ykIEk:b-h70n43) ([raw file](https://github.com/cockroachdb/cockroach/blob/039f78f13780be737fe1555fa4ee9f9785203a53/pkg/util/quotapool/intpool_test.go#L425)):*
> ```Go
> }
> 
> func BenchmarkChannelSemaphore(b *testing.B) {
> ```

Do you mind adding this benchmark and the one above to the commit message as well? Also, please leave it as a comment on this thread.
___
*[pkg/util/quotapool/intpool_test.go, line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16_N6A6CRkRpyl_qRo:-M16_N6B7w6VQGXhFzgU:bgcvcgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/039f78f13780be737fe1555fa4ee9f9785203a53/pkg/util/quotapool/intpool_test.go#L519)):*
> ```Go
> // workers with the IntPool.
> func BenchmarkConcurrentIntPool(b *testing.B) {
> 	// test returns the arguments to b.Run for a given number of workers and
> ```

"returns the arguments"

Is that what you meant to say?
___
*[pkg/util/stop/stopper.go, line 357 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16caBo5ipa8MQWZnnn:-M16caBo5ipa8MQWZnno:b-pndk07) ([raw file](https://github.com/cockroachdb/cockroach/blob/291f89d083de26ba19e9a56aa453446c1e634a7c/pkg/util/stop/stopper.go#L357)):*
> ```Go
> 	}
> 	defer func() {
> 		if alloc != nil && err != nil {
> ```

Why don't you want to release if `err == nil`? If we want to find a condition that is only hit on the following two return paths then I'd suggest we either:
1. don't defer and go back to what we had before.
2. set `alloc = nil` in the `defer alloc.Release()` below.

**Review by ajwerner — COMMENTED** [review]
TFTR! I've made the behavior of UpdateCapacity work more as you might hope. On the whole, I'm pretty happy with how it turned out. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-:-M1By0vK53v5-UWWWumU:b7y53aa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/dist_sender.go, line 1278 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16b88iCfFM6OrVGFxH:-M17H-ct12S88-k7fLKF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/291f89d083de26ba19e9a56aa453446c1e634a7c/pkg/kv/dist_sender.go#L1278)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Stray line.
</blockquote></details>

Done.
___
*[pkg/server/status.go, line 1645 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16bOCi5yAPq9YT6p03:-M175Rpd1KlcdGQdrLyd:b-l37lnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/291f89d083de26ba19e9a56aa453446c1e634a7c/pkg/server/status.go#L1645)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you need to `defer sem.Close(...)` in these cases?
</blockquote></details>

I think instead I'm going to attach the context to the stopper. Then it will have roughly the behavior as before this change. Defer close is what it is but the more worrying case is that we block in the below loop when the stopper is stopped. 
___
*[pkg/util/quotapool/intpool.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16abzU1WL7_YLN_8xC:-M17GMi66LbBMsf-O-18:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1cb3e76c2ce52601db9bfeb495c9feac8c51494/pkg/util/quotapool/intpool.go#L125)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/acquire immediately will/acquire immediately the method will/
</blockquote></details>

Done.
___
*[pkg/util/quotapool/intpool.go, line 213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16aiIN0YBrmDKjZXqT:-M178hCt29z1C-U4KEnj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1cb3e76c2ce52601db9bfeb495c9feac8c51494/pkg/util/quotapool/intpool.go#L213)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/exists will/exists the method will/
</blockquote></details>

Done.
___
*[pkg/util/quotapool/intpool.go, line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16aTiJ-FJ_eOyAPUkl:-M176CWD8tKYwt4PN2CO:bf706uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1cb3e76c2ce52601db9bfeb495c9feac8c51494/pkg/util/quotapool/intpool.go#L358)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: why is the one above wrapped but this one is not?
</blockquote></details>

Done.

A point of interest is that all of these calls get inlined so this should be much better than having a boolean on the `intRequest`
___
*[pkg/util/quotapool/intpool.go, line 352 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16dBJm80p10AoMEcQ3:-M1BxmEF3kVZSi9CzKMU:b-ozssfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6227972e4c4ffa08bcf8f4727a2c505990b97c08/pkg/util/quotapool/intpool.go#L352)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you say something about when this converges to the capacity value that was last set? Is it guaranteed to?
</blockquote></details>

The behavior here has changed.
___
*[pkg/util/quotapool/intpool.go, line 358 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16dXxj3FacsRfqXgaI:-M17830y-IZ8C0zld-d6:bc745gm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6227972e4c4ffa08bcf8f4727a2c505990b97c08/pkg/util/quotapool/intpool.go#L358)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What extra bookkeeping would it take? We know the current quota capacity and the amount of quota available, right? Would we need to track the maximum outstanding quota as well, since that's no longer exactly `capacity - available` immediately after the capacity is dropped?

Would allowing for negative capacity solve this issue without extra bookkeeping?
</blockquote></details>

Yes I think it would. Probably a good enough justification to move from `uint64` to `int64`. It needed some synchronization but this altogether worked brilliantly. 
___
*[pkg/util/quotapool/intpool.go, line 367 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16eIWq0mjvkhqJjfBt:-M175yTsB1NFrsnpMQLW:b-jfmi3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6227972e4c4ffa08bcf8f4727a2c505990b97c08/pkg/util/quotapool/intpool.go#L367)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This can and probably should be moved into the condition.
</blockquote></details>

I initially typed it that way but I don't think it's right. I want to wake the head of the queue to inform it that the capacity has changed. Releasing a value of 0 will do that. 
___
*[pkg/util/quotapool/intpool_test.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16_Utb5aLZx98ykIEj:-M176d1O59mZliV_cTe6:btpyhnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/039f78f13780be737fe1555fa4ee9f9785203a53/pkg/util/quotapool/intpool_test.go#L425)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you mind adding this benchmark and the one above to the commit message as well? Also, please leave it as a comment on this thread.
</blockquote></details>

I thought it was in the commit message? Copied from the first commit:

```
$ go test ./pkg/util/quotapool/ --run '^$' --bench 'Concurrent'  --benchmem --count 10 2>&1 > out
$ benchstat <(cat out | grep -v Int | sed 's/ChannelSemaphore/IntPool/') <(cat out | grep -v Chan)
name                                         old time/op    new time/op    delta
ConcurrentIntPool/workers=1,quota=1-8           217ns ± 5%     278ns ± 3%   +27.85%  (p=0.000 n=10+10)
ConcurrentIntPool/workers=2,quota=2-8           260ns ± 4%     286ns ± 3%   +10.29%  (p=0.000 n=10+10)
ConcurrentIntPool/workers=8,quota=4-8           858ns ± 1%    2567ns ±19%  +199.23%  (p=0.000 n=9+10)
ConcurrentIntPool/workers=128,quota=4-8         840ns ± 1%    2743ns ±26%  +226.41%  (p=0.000 n=9+10)
ConcurrentIntPool/workers=512,quota=128-8      1.33µs ± 1%    4.93µs ±14%  +270.42%  (p=0.000 n=10+9)
ConcurrentIntPool/workers=512,quota=513-8       485ns ± 5%     572ns ± 4%   +17.84%  (p=0.000 n=10+10)
ConcurrentIntPool/workers=512,quota=511-8       492ns ± 4%    2133ns ±40%  +333.98%  (p=0.000 n=10+9)
ConcurrentIntPool/workers=1024,quota=4-8        814ns ± 1%    2905ns ±34%  +256.93%  (p=0.000 n=8+10)
ConcurrentIntPool/workers=1024,quota=4096-8     475ns ± 5%     574ns ± 9%   +20.83%  (p=0.000 n=10+10)
```
___
*[pkg/util/quotapool/intpool_test.go, line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16_N6A6CRkRpyl_qRo:-M177Owq7x9Fkc9xnsP_:b-f5ivjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/039f78f13780be737fe1555fa4ee9f9785203a53/pkg/util/quotapool/intpool_test.go#L519)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"returns the arguments"

Is that what you meant to say?
</blockquote></details>

It's a stale comment. Removed.
___
*[pkg/util/stop/stopper.go, line 357 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16caBo5ipa8MQWZnnn:-M178wNa7FgM1n3YT_J6:b384iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/291f89d083de26ba19e9a56aa453446c1e634a7c/pkg/util/stop/stopper.go#L357)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why don't you want to release if `err == nil`? If we want to find a condition that is only hit on the following two return paths then I'd suggest we either:
1. don't defer and go back to what we had before.
2. set `alloc = nil` in the `defer alloc.Release()` below.
</blockquote></details>

The idea is that we only want to release the alloc on the caller's goroutine if we don't start the async task. We only return a nil error if we launch the async task. I can remove the `alloc != nil` case (it shouldn't happen as written) and I've added a comment to clarify that `err != nil` implies that we did not launch the async task.

**Comment by ajwerner** [comment]
Hold off on looking at this. I think there might be a problem.

**Comment by ajwerner** [comment]
Alright, problem solved. RFAL.

**Review by nvb — COMMENTED** [review]
> Reviewed 19 of 19 files at r7, 2 of 2 files at r8, 3 of 3 files at r9, 13 of 13 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 2 of 2 files at r13, 6 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45452)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/util/quotapool/intpool.go, line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16aTiJ-FJ_eOyAPUkl:-M1CkRrw-z4q172MHG-x:b-e6tv7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1cb3e76c2ce52601db9bfeb495c9feac8c51494/pkg/util/quotapool/intpool.go#L358)):*
> A point of interest is that all of these calls get inlined so this should be much better than having a boolean on the intRequest

Don't they require dynamic dispatch? How are they being inlined?
___
*[pkg/util/quotapool/intpool.go, line 41 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M1ClQM83UWQEt5XMrkj:-M1ClQM83UWQEt5XMrkk:big2dpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/affd63837ed910835c1b546554369703aef4affa/pkg/util/quotapool/intpool.go#L41)):*
> ```Go
> // IntAlloc is an allocated quantity which should be released.
> type IntAlloc struct {
> 	alloc int64
> ```

`// can be negative`

or something?
___
*[pkg/util/quotapool/intpool.go, line 103 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M1ClbLEEYkGukCKDtdH:-M1ClbLEEYkGukCKDtdI:b-oedlet) ([raw file](https://github.com/cockroachdb/cockroach/blob/affd63837ed910835c1b546554369703aef4affa/pkg/util/quotapool/intpool.go#L103)):*
> ```Go
> // is math.MaxInt64. If the capacity argument exceeds that value, this function
> // will panic.
> func NewIntPool(name string, capacity uint64, options ...Option) *IntPool {
> ```

Did you consider just changing this to an `int64` here and throughout?
___
*[pkg/util/quotapool/intpool_test.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16_Utb5aLZx98ykIEj:-M1CjnxFELtHKYY1N2JX:b-oy3gk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/039f78f13780be737fe1555fa4ee9f9785203a53/pkg/util/quotapool/intpool_test.go#L425)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I thought it was in the commit message? Copied from the first commit:

```
$ go test ./pkg/util/quotapool/ --run '^$' --bench 'Concurrent'  --benchmem --count 10 2>&1 > out
$ benchstat <(cat out | grep -v Int | sed 's/ChannelSemaphore/IntPool/') <(cat out | grep -v Chan)
name                                         old time/op    new time/op    delta
ConcurrentIntPool/workers=1,quota=1-8           217ns ± 5%     278ns ± 3%   +27.85%  (p=0.000 n=10+10)
ConcurrentIntPool/workers=2,quota=2-8           260ns ± 4%     286ns ± 3%   +10.29%  (p=0.000 n=10+10)
ConcurrentIntPool/workers=8,quota=4-8           858ns ± 1%    2567ns ±19%  +199.23%  (p=0.000 n=9+10)
ConcurrentIntPool/workers=128,quota=4-8         840ns ± 1%    2743ns ±26%  +226.41%  (p=0.000 n=9+10)
ConcurrentIntPool/workers=512,quota=128-8      1.33µs ± 1%    4.93µs ±14%  +270.42%  (p=0.000 n=10+9)
ConcurrentIntPool/workers=512,quota=513-8       485ns ± 5%     572ns ± 4%   +17.84%  (p=0.000 n=10+10)
ConcurrentIntPool/workers=512,quota=511-8       492ns ± 4%    2133ns ±40%  +333.98%  (p=0.000 n=10+9)
ConcurrentIntPool/workers=1024,quota=4-8        814ns ± 1%    2905ns ±34%  +256.93%  (p=0.000 n=8+10)
ConcurrentIntPool/workers=1024,quota=4096-8     475ns ± 5%     574ns ± 9%   +20.83%  (p=0.000 n=10+10)
```
</blockquote></details>

Isn't that only listing the `concurrentBenchSpec` benchmarks? I think the issue is that the benchmark above this is called `BenchmarkIntQuotaPool` and not `BenchmarkIntPool`.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-:-M1CqxXiASYSD8hkILJ7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/util/stop/stopper.go, line 357 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16caBo5ipa8MQWZnnn:-M1Cqscr7rTKftxluH8k:b-5kkjx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/291f89d083de26ba19e9a56aa453446c1e634a7c/pkg/util/stop/stopper.go#L357)):*
> I can remove the alloc != nil case

That and a comment would make this easier to understand.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45452)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/util/quotapool/intpool.go, line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16aTiJ-FJ_eOyAPUkl:-M1CtLAx6noqAtw8X25l:b-vfzreq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1cb3e76c2ce52601db9bfeb495c9feac8c51494/pkg/util/quotapool/intpool.go#L358)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> A point of interest is that all of these calls get inlined so this should be much better than having a boolean on the intRequest

Don't they require dynamic dispatch? How are they being inlined?
</blockquote></details>

I got too excited about `can inline` and then stopped thinking I suppose. I still think this is better than making the object bigger but it's premature optimization for sure. 
___
*[pkg/util/quotapool/intpool.go, line 41 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M1ClQM83UWQEt5XMrkj:-M1CuFSy-SiM42lKDbxS:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/affd63837ed910835c1b546554369703aef4affa/pkg/util/quotapool/intpool.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`// can be negative`

or something?
</blockquote></details>

Done. 
___
*[pkg/util/quotapool/intpool.go, line 103 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M1ClbLEEYkGukCKDtdH:-M1CswIMCTCckiLhRNQY:b7c922b) ([raw file](https://github.com/cockroachdb/cockroach/blob/affd63837ed910835c1b546554369703aef4affa/pkg/util/quotapool/intpool.go#L103)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you consider just changing this to an `int64` here and throughout?
</blockquote></details>

I did. Would you prefer that and then disallowing negative values? I really didn't want to expose the concept of negative quota to the interfaces. It felt weird to make the constructor take an int64 and then have all of the introspection return uint64. 
___
*[pkg/util/quotapool/intpool_test.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16_Utb5aLZx98ykIEj:-M1CseOc-_qsGdlPeuhH:bc9m60h) ([raw file](https://github.com/cockroachdb/cockroach/blob/039f78f13780be737fe1555fa4ee9f9785203a53/pkg/util/quotapool/intpool_test.go#L425)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Isn't that only listing the `concurrentBenchSpec` benchmarks? I think the issue is that the benchmark above this is called `BenchmarkIntQuotaPool` and not `BenchmarkIntPool`.
</blockquote></details>

Here's the output of those benchmarks:

```
name                time/op
IntQuotaPool-8      220ns ±23%
IntQuotaPoolFunc-8  268ns ±24%

name                alloc/op
IntQuotaPool-8      0.00B     
IntQuotaPoolFunc-8  16.0B ± 0%

name                allocs/op
IntQuotaPool-8       0.00     
IntQuotaPoolFunc-8   1.00 ± 0%
```

Are you asking me to additionally augment the other benchmarks to have channel variants? I didn't change anything about those functions.
___
*[pkg/util/stop/stopper.go, line 357 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16caBo5ipa8MQWZnnn:-M1Cunjy8Vi2b-6AsQay:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/291f89d083de26ba19e9a56aa453446c1e634a7c/pkg/util/stop/stopper.go#L357)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> I can remove the alloc != nil case

That and a comment would make this easier to understand.
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45452)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/util/quotapool/intpool_test.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45452#-M16_Utb5aLZx98ykIEj:-M1D1SJbB-oYs-BcFfao:b-j1oer7) ([raw file](https://github.com/cockroachdb/cockroach/blob/039f78f13780be737fe1555fa4ee9f9785203a53/pkg/util/quotapool/intpool_test.go#L425)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Here's the output of those benchmarks:

```
name                time/op
IntQuotaPool-8      220ns ±23%
IntQuotaPoolFunc-8  268ns ±24%

name                alloc/op
IntQuotaPool-8      0.00B     
IntQuotaPoolFunc-8  16.0B ± 0%

name                allocs/op
IntQuotaPool-8       0.00     
IntQuotaPoolFunc-8   1.00 ± 0%
```

Are you asking me to additionally augment the other benchmarks to have channel variants? I didn't change anything about those functions.

</blockquote></details>

Okay I see, sorry about the confusion. Updated the commit message. Here's the missing row:

`IntPool-8                                      94.5ns ± 5%   193.1ns ± 3%  +104.24%  (p=0.000 n=20+18) `

**Comment by ajwerner** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
