### PR TITLE
roachtest: increase parallelism of the jepsen tests

### PR DESCRIPTION
**Pull request by petermattis**
Divide the 7 jepsen tests into 3 roachtests. Each roachtest has 10
subtests: 1 for each nemeses. The 3 top-level roachtests each get their
own cluster which allows for parallelism.

See #28646

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28797)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/jepsen.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28797#-LKE4-9BAU9szo0dQl5x:-LKE4-9CBafwOP4-6rlI:bff8qqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9f1f9dde4fc8f461777176b729d1fc5dfb659/pkg/cmd/roachtest/jepsen.go#L279)):*
> ```Go
> 		jepsenTests[2:4],
> 		jepsenTests[4:],
> 	}
> ```

nit: I think this layer of indirection harms readability. Optional suggestion:

```go
// N.B. The "comments" test is not included because it requires linearizability.
groups := [][]string{
	{"bank", "bank-multitable"},
	{"g2", "monotonic"},
        {"register", "sequential", "sets"},
}
```

**Review by benesch — APPROVED** [review]
If you wind up going through CI: s/nemeses/nemesis.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28797#-:-LKE519h0rcmZ93Eukkz:b-1qsgtq)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28797)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/jepsen.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28797#-LKE4-9BAU9szo0dQl5x:-LKEAuwn2cVtsy8cItuB:b38hgtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c9f1f9dde4fc8f461777176b729d1fc5dfb659/pkg/cmd/roachtest/jepsen.go#L279)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

nit: I think this layer of indirection harms readability. Optional suggestion:

```go
// N.B. The "comments" test is not included because it requires linearizability.
groups := [][]string{
	{"bank", "bank-multitable"},
	{"g2", "monotonic"},
        {"register", "sequential", "sets"},
}
```
</blockquote></details>

That is nicer. Done.

**Comment by petermattis** [comment]
bors r=benesch

**Pull request merged**
