### PR TITLE
opt: misc cleanup after HP removal

### PR DESCRIPTION
**Pull request by RaduBerinde**
These changes are on top of #40794. They are meant to be merged after branching.

#### opt: pass required ordering to distinctNode

Pass the required output ordering of `distinctNode` instead of letting
the legacy code figure it out.

Release note: None

#### sql: clean up index join

The `indexJoinNode` only supports a `scanNode` input. This leads to
some hacks inside the optimizer to make sure we aren't doing any
sorting before the join (which would actually be preferable).

This change relaxes this limitation and cleans up the construction of
`indexJoinNode`.

Release note: None

#### sql: simplify sortNode

In the heuristic planner, `sortNode` had to provide more functionality
(pass through already sorted data; possibly project some columns
away). This is no longer needed and the code can be simplified.

Release note: None

#### opt: clean up segmented sort logic

Segmented sort is when we already have an ordering on a prefix of the
desired ordering (and we can thus sort each "segment").

Currently the distsql physical planner figures this out based on the
orderings in the plan nodes. Now that the optimizer knows about
segmented sort, we can plumb down the value from the optimizer and
simplify the distsql planner. We can now also show the relevant
information in EXPLAIN.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: nice cleanup!!

> Reviewed 13 of 13 files at r1, 17 of 17 files at r2, 8 of 8 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-:-LpUZnYv3zX1uQgir6EJ:b-yt5vyo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/distinct.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-Lp5Uu9t9DwvMo9zs91v:-Lp5Uu9u3sQPtz0CSJcp:b28bwvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/39db72ac604d30bb36693636a375d20376271b82/pkg/sql/distinct.go#L37)):*
> ```Go
> 	columnsInOrder util.FastIntSet
> 
> 	props physicalProps
> ```

this could use a comment for why distinct node needs physical props
___
*[pkg/sql/distsql_physical_planner.go, line 1855 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-LpUSesC5WaOPkZZSc3J:-LpUSesD8pFHRVfjJr5h:b-l3nvpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bdc59a55468e6bf8ab949e3dbb42ecc4a983bf7/pkg/sql/distsql_physical_planner.go#L1855)):*
> ```Go
> 	// In "index-join mode", the join reader assumes that the PK cols are a prefix
> 	// of the input stream columns (see #40749). We need a projection to make that
> 	// happen. Node of the other columns are used by the join reader.
> ```

Node -> None (?)
___
*[pkg/sql/opt_limits.go, line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-LpUWqNR0hDQ-PeuMTkL:-LpUWqNR0hDQ-PeuMTkM:b-7y5dxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a9be1cff43493d1370957f15185e7a3d96bc1c/pkg/sql/opt_limits.go#L77)):*
> ```Go
> 		// potentially needs all rows.
> 		numRows = math.MaxInt64
> 		soft = true
> ```

seems like you don't need `numRows` or `soft` anymore
___
*[pkg/sql/sort.go, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-LpUXvvh889dLWXYU6MK:-LpUXvvh889dLWXYU6ML:bxlzvvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c4b9596d4ff7ed9286c6bf43b1537d470cd877b/pkg/sql/sort.go#L26)):*
> ```Go
> 	ordering sqlbase.ColumnOrdering
> 	// When alreadyOrderedPrefix is non-zero, the input is already ordered on
> 	// theprefix ordering[:alreadyOrderedPrefix].
> ```

theprefix -> the prefix
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-LpUZHqh8sy7IrgEcra8:-LpUZHqh8sy7IrgEcra9:b-duipck) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c4b9596d4ff7ed9286c6bf43b1537d470cd877b/pkg/sql/opt/exec/execbuilder/relational.go#L1155)):*
> ```Go
> 	alreadyOrderedPrefix := 0
> 	for i := range inputOrdering {
> 		if inputOrdering[i] != ordering[i] {
> ```

Can we always guarantee that `ordering` is at least as long as `inputOrdering`? (Perhaps it's worth adding an assertion?)

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-:-LpYoijj3EQIq_SIfI5f:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/distinct.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-Lp5Uu9t9DwvMo9zs91v:-LpYlr7J9L66eJSdodgY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39db72ac604d30bb36693636a375d20376271b82/pkg/sql/distinct.go#L37)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this could use a comment for why distinct node needs physical props
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 1855 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-LpUSesC5WaOPkZZSc3J:-LpYm7_D5MuW3uzuErGI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bdc59a55468e6bf8ab949e3dbb42ecc4a983bf7/pkg/sql/distsql_physical_planner.go#L1855)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Node -> None (?)
</blockquote></details>

Done.
___
*[pkg/sql/opt_limits.go, line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-LpUWqNR0hDQ-PeuMTkL:-LpYmQMYBrEKiTxEuXJP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a9be1cff43493d1370957f15185e7a3d96bc1c/pkg/sql/opt_limits.go#L77)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

seems like you don't need `numRows` or `soft` anymore
</blockquote></details>

Done.
___
*[pkg/sql/sort.go, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-LpUXvvh889dLWXYU6MK:-LpYmZ6HBORL5pQxr1mg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c4b9596d4ff7ed9286c6bf43b1537d470cd877b/pkg/sql/sort.go#L26)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

theprefix -> the prefix
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-LpUZHqh8sy7IrgEcra8:-LpYmpmy6WmOAJj2TQv-:bcb092e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c4b9596d4ff7ed9286c6bf43b1537d470cd877b/pkg/sql/opt/exec/execbuilder/relational.go#L1155)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can we always guarantee that `ordering` is at least as long as `inputOrdering`? (Perhaps it's worth adding an assertion?)
</blockquote></details>

Good catch, added an assertion error.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 23 files at r5, 9 of 17 files at r6, 4 of 8 files at r7, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40825#-:-Lp_1Fnp9xvr3D0zgpFs:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

**Comment by RaduBerinde** [comment]
Closing this, opened a new PR against `master` (#41431).

**Pull request closed without merging**
