### PR TITLE
storage: disable blind cput 

### PR DESCRIPTION
**Pull request by danhhz**
See #6487 for details.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6534)

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/testdata/insert, line 440 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6534#-KH14ZMXe9LttKD-Y4uG:-KH14ZMXe9LttKD-Y4uH:894257871) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced158af98edf4cc4e69b9659384f61845e73e50/sql/testdata/insert#L440)):*
I think the extra indexes make it a harder to follow repro... what about just inserting 11 things in a simpler table?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6534)*

**Comment by paperstreet** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/testdata/insert, line 440 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6534#-KH14ZMXe9LttKD-Y4uG:-KH179d2leg-hh9TXruX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced158af98edf4cc4e69b9659384f61845e73e50/sql/testdata/insert#L440)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6534)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6534#-:-KH17aIuF2aZgst8ntlt:1417088721)*

**Comment by tamird** [comment]
:lgtm: though i wouldn't call it a workaround - this is just disabling that optimization, right?

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6534#-:-KH184eanOiATcIXXcoZ:422843480)*

**Comment by paperstreet** [comment]
Yup. Edited the commit title

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6534#-:-KH19SvD3i2ecQL8hUGd:660040660)*

**Pull request merged**
