### PR TITLE
roachprod-stress: request traceback from all goroutines

### PR DESCRIPTION
**Pull request by benesch**
This makes debugging much easier.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]

**Review by petermattis — APPROVED** [review]

**Comment by benesch** [comment]
(This PR was approved but the message was lost in the outage.)

bors r=petermattis

**Comment by benesch** [comment]
(This PR was approved but the message was lost in the outage.)

bors r=petermattis

**Comment by benesch** [comment]
One more try.

bors r+

**Pull request merged**
