### PR TITLE
roachtest: use import instead of load on AWS for tpcc

### PR DESCRIPTION
**Pull request by ajwerner**
`workload fixtures load` restores from google storage. This is both an expensive due to the network traffic and problematic due to authentication. Instead we generate and load the data using `workload fixtures import` on AWS.

### CODE REVIEW

**Review by danhhz — APPROVED** [review]
fixtures import is not available in 2.1 binaries and we can't backport it, so you may have to add a MinVersion if cloud is aws : - /

**Comment by ajwerner** [comment]
TFTR! Updated the code to enforce a MinVersion when the cloud is "aws"

**Review by danhhz — APPROVED** [review]
one suggestion but still :lgtm: if you don't feel like doing it

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33625#-:-LVsd5HN1fDphgNaw9kd:b7d3k53)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33625#-LVsbYKQA3HQAXkOhbVz:-LVsbYKQA3HQAXkOhbW-:b3oko5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/405bdad7a15aed7b711ec522f9d41343f39e58fb/pkg/cmd/roachtest/tpcc.go#L151)):*
> ```Go
> 		{
> 			Name:  "tpcc-nowait/nodes=3/w=1",
> 			Nodes: nodes(4, cpu(16)),
> ```

IMO it's cleaner to do something like `MinVersion: maybeMinVersionForFixturesImport(cloud)` here instead of this array of specs and then pass them each to a function dance. You could add a second arg to it for this `tpcc/nodes=3/w=max` special case, or maybe just do my TODO by adding a function that maps version to max supported warehouses (should be easy enough to figure out what number to return for earlier versions by asking @nvanbenschoten)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33625)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/tpcc.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33625#-LVsbYKQA3HQAXkOhbVz:-LVsgaAv7zcWx_ubbwuf:bc2ctw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/405bdad7a15aed7b711ec522f9d41343f39e58fb/pkg/cmd/roachtest/tpcc.go#L151)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

IMO it's cleaner to do something like `MinVersion: maybeMinVersionForFixturesImport(cloud)` here instead of this array of specs and then pass them each to a function dance. You could add a second arg to it for this `tpcc/nodes=3/w=max` special case, or maybe just do my TODO by adding a function that maps version to max supported warehouses (should be easy enough to figure out what number to return for earlier versions by asking @nvanbenschoten)
</blockquote></details>

did mostly what you suggested, just didn't resolve the TODO.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33625)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/tpcc.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33625#-LVsbYKQA3HQAXkOhbVz:-LVslK4i5lLf9cHiqm9J:bbssnaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/405bdad7a15aed7b711ec522f9d41343f39e58fb/pkg/cmd/roachtest/tpcc.go#L151)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

did mostly what you suggested, just didn't resolve the TODO.
</blockquote></details>

ooh nice, i like this

**Comment by ajwerner** [comment]
bors r=danhhz

**Pull request merged**
