### PR TITLE
roachtest: assorted debuggability improvements

### PR DESCRIPTION
**Pull request by tbg**
roachtest: fix some Fatal-on-goroutine offenders

    Not all of them. There are more than I have time for right now.

    Release note: None

    roachtest: complain about invalid calls off main goroutine

    Until https://go-review.googlesource.com/c/sync/+/131815 merges
    (if if ever does) an errgroup will not cancel the context when one of its
    goroutines Goexit's. This means it remains a bad idea to call `c.Run` and
    friends from within `m.Go`, as it'll hold back the error until everything
    has "naturally" terminated, which may never happen (since a goroutine just
    stopped doing its work).

    Put annoying warnings in the logs that should be good enough to deter
    anyone developing tests locally from committing these faux-pas.

    I'd rather remove `c.Run` and friends completely, but it's a bigger
    project.

    roachtest: observe ctx cancellation in Run

    Before this patch, roachprod invocations would not observe ctx
    cancellation. Or rather they would, but due to the usual obscure passing of
    Stdout into the child process of roachprod the Run call would not return
    until the child had finished. As a result, the test would continue running,
    which is annoying and also costs money.

Release note: None

### CODE REVIEW

**Review by petermattis — CHANGES_REQUESTED** [review]
Thanks for the work here, though I'm questioning the approach of disallowing calling `t.Fatal` from other goroutines. Since we control the closures passed to `errgroup.Go`, it seems feasible to catch panics and calls to `runtime.Goexit` and translate them into errors. Or we could fork `errgroup`. 

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29174#-:-LL-pKx1-yzFsALNMRVB:b-dh66bk)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/allocator.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29174#-LL-pBj2DNBH6tNhk9T9:-LL-pBj2DNBH6tNhk9TA:b-qrjn5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3337c9c83f2e3ba56dfa9d28029f0c4e496dc1ba/pkg/cmd/roachtest/allocator.go#L68)):*
> ```Go
> 				defer l.close()
> 				if err := execCmd(ctx, c.l, roachprod, "ssh", c.makeNodes(c.Node(node)), "--", cmd); err != nil {
> 					panic(err)
> ```

Won't this call the entire `roachtest` execution? That seems bad.
___
*[pkg/cmd/roachtest/cluster.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29174#-LL-nYsZ0WcU7hz22AbF:-LL-nYs_47pvvpWQTW9U:be21h5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f356e004f27532485d20dbc8ee170cc1bdabbb81/pkg/cmd/roachtest/cluster.go#L252)):*
> ```Go
> 		go func() {
> 			defer wg.Done()
> 			_, _ = io.Copy(l.stdout, rOut)
> ```

`l.stdout` is not necessarily `os.Stdout`. Just pointing that out in case it wasn't obvious. Seems ok to be using the pipe regardless.

More interestingly is whether there is a difference here if `l.stdout == l.stderr`. Now you're separating them in the child process and recombining them here which might produce weird interleaving. Not sure if this should be addressed or not. 
___
*[pkg/cmd/roachtest/cluster.go, line 1150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29174#-LL-o02d6l_egcs0mnzR:-LL-o02d6l_egcs0mnzS:b-ag8phq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f356e004f27532485d20dbc8ee170cc1bdabbb81/pkg/cmd/roachtest/cluster.go#L1150)):*
> ```Go
> 			if r := recover(); r != nil || !returned {
> 				if !returned {
> 					fmt.Println("runtime.Goexit was called from a monitor goroutine. Don't do this.")
> ```

Why not? That is, please add a comment why this is bad.

Also, could we allow this by returning an error when we detect this has occurred?
___
*[pkg/cmd/roachtest/test.go, line 582 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29174#-LL-ooGrBxRvDsFDFZHs:-LL-ooGrBxRvDsFDFZHt:b809tl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29a17a432d79857a9ce640fad25cbf9c128fd5a/pkg/cmd/roachtest/test.go#L582)):*
> ```Go
> }
> 
> func (t *test) AssertMainGoroutine() {
> ```

I'd rather figure out a way to allow `t.Fatal` to work on non-main goroutines. The intention was that it would work. I don't see a fundamental reason it can't work within `monitor.Go`.

**Review by tbg — COMMENTED** [review]
You can't recover from `runtime.Goexit()`, and in particular you can't communicate a sensible error to the `errgroup` (all it sees is a `recover() == nil`). roachtest failures are terrible to debug at the moment, and returning a sensible error from `t.Wait()` is the bare minimum I'd like to see in the future. We could `panic(err)` instead, which seems more reasonable. Is this what you're suggesting?

> I'd rather figure out a way to allow t.Fatal to work on non-main goroutines. The intention was that it would work. I don't see a fundamental reason it can't work within monitor.Go.

I share your distaste for the `err := nil` dance, but I really dislike how messy and workaround-piled-on-workaround our current code is. It's really a bad copy of the Go testing framework, and that framework breaks when you use `t.Fatal` on a goroutine, too. It'd be unfortunate to mess it up further.

I'll take another look here at how this can work if we `panic(err)` instead, but in my heart I wish `t.Fatal` had never been introduced and we'd just write idiomatic Go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29174#-:-LL-rBMD5YUPEtjfpJ3q:b-tkw6fa)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by tbg — COMMENTED** [review]
Looks like we can do something about `Goexit` by escalating it to a panic (which can then be recovered from): https://play.golang.com/p/0WUEJCAr0su

Sounds like a terrible hack, but hey, I hear the Go folks like not breaking such assumptions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29174#-:-LL-wheo5-Nt9u1aSjMC:bl8rmko)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tschottdorf** [comment]
Obsolete, please refer to #29178 instead.

**Pull request closed without merging**
