### PR TITLE
cli: move the range/kv commands under debug

### LINKED ISSUE #4751: cli: move range & kv commands under debug command
range and kv commands on the main binary are not fit for beta usage. Let's move them under the debug command.

### PR DESCRIPTION
**Pull request by petermattis**
Remove the "range merge" command which is not fully supported on the
server side.

Fixes #4751.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4812)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/kv.go, line 380 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4812#-KBwzqVkUjY1vGFlgPnA:-KBwzqVkUjY1vGFlgPnB:1249844311) ([raw file](https://github.com/cockroachdb/cockroach/blob/79788a85f6a0935b0432b61cf2c963c6618219ae/cli/kv.go#L380)):*
team oxford comma

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4812)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/kv.go, line 380 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4812#-KBwzqVkUjY1vGFlgPnA:-KBx-N7bxriK98H_pWPh:309529858) ([raw file](https://github.com/cockroachdb/cockroach/blob/79788a85f6a0935b0432b61cf2c963c6618219ae/cli/kv.go#L380)):*
Heh, I didn't even do that consciously.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4812)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4812)*

**Comment by petermattis** [comment]
Does this LGTY?

**Comment by tamird** [comment]
Yeah, sorry.

**Pull request merged**
