### PR TITLE
sql: move a single remote flow to the gateway in some cases

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: show distribution info based on actual physical plan in EXPLAIN**

Previously, the `distribution` info in `EXPLAIN` output was printed
based on the recommendation about the distribution of the plan. For
example, if the plan is determined as "should be distributed", yet
it only contains a single flow on the gateway, we would say that the
plan has "full" distribution.

This commit updates the code to print the distribution based on the
actual physical plan (in the example above it would say "local"),
regardless of the reason - whether it is the recommendation to plan
locally or the data happened to be only on the gateway.

I think it makes more sense this way since now DISTSQL diagram
consisting of a single flow on the gateway more appropriately
corresponds to "local" distribution. Additionally, this change is
motivated by the follow-up commit which will introduce changes to the
physical plan during the plan finalization, and we want to show the
correct distribution in the EXPLAIN output for that too.

Release note: None

**sql: move a single remote flow to the gateway in some cases**

This commit updates the physical planner to move a single remote flow
onto the gateway in some cases, namely when
- the flow contains a processor that might increase the cardinality of
the data flowing through it or that performs the KV work
- we estimate that the whole flow doesn't reduce the cardinality when
compared against the number of rows read by the table readers.
To be conservative, when there is no estimate, we don't apply this
change to the physical plan.

The justification behind this change is the fact that we're pinning the
whole physical planning based on the placement of table readers. If the
plan consists only of a single flow, and the flow is quite expensive,
then with high enough frequency of such flows, the node having the
lease for the ranges of the table readers becomes the hot spot (we have
seen this in practice a few months ago). In such a scenario we might now
choose to run the flow locally to distribute the load on the cluster
better (assuming that the queries are issued against all nodes with
equal frequency).

The EXPLAIN output will correctly say "distribution: local" if the flow
is moved to the gateway.

Informs: #59014.

Release note (bug fix): Some query patterns that previously could cause
a single node to become a hot spot have been fixed so that the load is
evenly distributed across the whole cluster.

### CODE REVIEW

**Comment by yuzefovich** [comment]
This PR is like an extension to #68524 (which was meant to resolve the hot spot scenario for one of our largest customers). I have also seen this hot spot pattern when running TPCH workload with high concurrency, and I believe that this PR should be generally a beneficial change (and might be justifiable to backport for 21.2.1).

My main questions are:
- I picked a subset of processors that could cause the hot spot scenario and don't reduce the cardinality of the data. An alternative is to move the flow back to the gateway by default, except for limited subset of plans (like a scan with a filter and nothing else).
- what do we want the EXPLAIN to say in case the single flow is moved back to the gateway? I'm probably leaning towards saying "distribution: local".

Curious about opinions from @cockroachdb/sql-queries.

**Review by rytaft — COMMENTED** [review]
This is cool! This is definitely the kind of decision that the optimizer should be making eventually, but I think it makes sense to do this as a stopgap for now. But I'm also a bit worried that this could cause us to send a lot more data over the network than we would otherwise. Maybe you could take advantage of the optimizer row count estimates to make the decision? e.g., if the output row count from the remote flow is significantly lower than the scan row counts, you might want to leave the remote flow as-is. Otherwise, you can move it to the gateway.

> I picked a subset of processors that could cause the hot spot scenario and don't reduce the cardinality of the data. An alternative is to move the flow back to the gateway by default, except for limited subset of plans (like a scan with a filter and nothing else).

I'd start with a smaller change that you know is likely to be beneficial.

> what do we want the EXPLAIN to say in case the single flow is moved back to the gateway? I'm probably leaning towards saying "distribution: local".

The plan is effectively local in this case, right? If so, I think I agree that we should say "distribution: local".

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-:-MkcewtL9KYADRMvFfxV:b-j0x92u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[-- commits, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-Mkcfa_M7uP0Fj1v9KZ8):*
nit: node become -> node to become
___
*[pkg/sql/distsql_physical_planner.go, line 4088 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkcgF_G0U5dqNtFcjof:-MkcgF_G0U5dqNtFcjog:b-l198sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8327a5d6454328d947e2d922e16f44b2178cce/pkg/sql/distsql_physical_planner.go#L4088)):*
> ```Go
> 				// or that performs the KV work.
> 				moveFlowToGateway = true
> 			}
> ```

what if there is also a Select / InvertedFilter / group by somewhere in the flow? wouldn't that possibly make the distributed plan better?

**Review by yuzefovich — COMMENTED** [review]
> Maybe you could take advantage of the optimizer row count estimates to make the decision?

Thanks, I like this idea, implemented. I also updated the EXPLAIN output to show the actual distribution.

I think I only want to add some tests to make sure that
1) if there are no stats, the flow is not moved
2) if the data cardinality is reduced significantly, then the flow is also not moved.

But otherwise, RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-:-MkrE8sK6oXPlu-VNhEn:bbmbleo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/distsql_physical_planner.go, line 4088 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkcgF_G0U5dqNtFcjof:-MkrDxr73DKi_I6_-eGc:bsqs4h5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8327a5d6454328d947e2d922e16f44b2178cce/pkg/sql/distsql_physical_planner.go#L4088)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

what if there is also a Select / InvertedFilter / group by somewhere in the flow? wouldn't that possibly make the distributed plan better?
</blockquote></details>

Yes, it might. I think now that we rely on the estimation of "row reduction ratio", it should cover those cases.

**Review by yuzefovich — COMMENTED** [review]
Added some tests, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-:-MkxH6mB3-xm1tdUe8yT:b18cwoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_single_flow, line 15 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxGLncCJEKzEEmCS5A:-MkxGLncCJEKzEEmCS5B:b9lxkwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a543f7bb2d91b404b09aae728273359e3ba3b46/pkg/sql/opt/exec/execbuilder/testdata/distsql_single_flow#L15)):*
> ```
> # There are no stats on the table, so the single flow should stay on the remote
> # node.
> # TODO(yuzefovich): currently the optimizer assumes that t has 1000 rows, so it
> ```

Can the optimizer tell us whether the stats are missing?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_single_flow, line 15 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxGLncCJEKzEEmCS5A:-MkxQMxa0GYIMszIWExH:bs4mjn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a543f7bb2d91b404b09aae728273359e3ba3b46/pkg/sql/opt/exec/execbuilder/testdata/distsql_single_flow#L15)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Can the optimizer tell us whether the stats are missing?
</blockquote></details>

nvm, I see where to check for this.

**Review by yuzefovich — COMMENTED** [review]
Alright, done updating, sorry for the noise. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-:-MkxUrsRE96u6o_lsibV:b-3s9tng)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 2035 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxUoiZ7qEc_Koq4mn-:-MkxUoiZ7qEc_Koq4mn0:b-4io24i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a5c87607c4ed34d003802556efe4ee752081bfb/pkg/sql/opt/exec/execbuilder/relational.go#L2035)):*
> ```Go
> 			return nil, err
> 		}
> 		// TODO: I'm not sure whether this is correct.
> ```

Not sure about this one.

**Review by rytaft — COMMENTED** [review]
Nice!

> Reviewed 17 of 30 files at r2, 24 of 24 files at r4, 15 of 26 files at r5, 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-:-MkxrLj9CsMJiJpyK3X9:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 4077 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxnqpP-vYaIoTHcnPt:-MkxnqpP-vYaIoTHcnPu:bc0wabj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a5c87607c4ed34d003802556efe4ee752081bfb/pkg/sql/distsql_physical_planner.go#L4077)):*
> ```Go
> 		const rowReductionRatio = 10
> 		keepPlan := rowCount <= 0 || float64(plan.TotalEstimatedScannedRows)/float64(rowCount) >= rowReductionRatio
> 		if !keepPlan {
> ```

nit: you could just return here if `keepPlan` is true
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 2035 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxUoiZ7qEc_Koq4mn-:-Mkxp_gW2GDMt-Odl9NG:bt93et7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a5c87607c4ed34d003802556efe4ee752081bfb/pkg/sql/opt/exec/execbuilder/relational.go#L2035)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Not sure about this one.
</blockquote></details>

I would think it should be `rec.Recursive`, since that's what is used to build the plan here.
___
*[pkg/sql/physicalplan/physical_plan.go, line 1243 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxmaXZ4IOP0fTDbGQq:-MkxmaX_B9O-jvyRM58-:bwrzwan) ([raw file](https://github.com/cockroachdb/cockroach/blob/348987d9093f00d0cc79c81c39b3c308e91f56c5/pkg/sql/physicalplan/physical_plan.go#L1243)):*
> ```Go
> // two parts of it.
> func (a PlanDistribution) compose(
> 	b PlanDistribution, allowPartialDistribution bool,
> ```

I'm struggling to understand the need for this parameter. Seems like you had to update a lot of code to include it, and I still don't quite see why it's necessary. Is there any way to simplify this?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/physicalplan/physical_plan.go, line 1243 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxmaXZ4IOP0fTDbGQq:-MlBPoAb513W6vucQ3y6:b-f7hboc) ([raw file](https://github.com/cockroachdb/cockroach/blob/348987d9093f00d0cc79c81c39b3c308e91f56c5/pkg/sql/physicalplan/physical_plan.go#L1243)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm struggling to understand the need for this parameter. Seems like you had to update a lot of code to include it, and I still don't quite see why it's necessary. Is there any way to simplify this?
</blockquote></details>

The idea behind "partial distribution" is to show that a part of the plan is fully distributed whereas another part of the plan couldn't be distributed, so the latter is executed locally. For example, we could plan table readers on multiple nodes for a single scan (i.e. "full" distribution), but then if we have a render expression involving a function that is Distsql-blocklisted, we have to evaluate that render on the gateway; such a plan with the new distsql spec factory would get "partial distribution".

The need for `allowPartialDistribution` argument came from the desire to not change "distribution" info for plans created by the old exec factory. If we were to keep the previous code of `compose`, then we would often see "partial" distribution when we have a stage of multiple remote processors and then we have a noop processor on the gateway - we would misleadingly say that we couldn't distribute the last stage, so we got the "partial" distribution. However, we actually don't want to "distribute" the last noop processor that is placed on the gateway simply to propagate the result to the client.

I think we have several options:
- plumb `allowPartialDistribution` parameter here (what I'm currently proposing) - this mostly preserves the existing behavior of the old exec factory and the new distsql spec factory
- disallow the "partial" distribution entirely - this will change the behavior of the new distsql spec factory and would call some plans as "fully" distributed when there are parts that have to only run on the gateway
- allow the "partial" distribution for the old exec factory - this will likely be confusing to users.

I've just added a temporary third commit that shows the change to the existing tests for the third option from above.

**Review by rytaft — COMMENTED** [review]
> Reviewed 27 of 27 files at r8, 25 of 25 files at r9, 18 of 18 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/experimental_distsql_planning_5node, line 145 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MlC0wtT5uviimYbr5_2:-MlC0wtT5uviimYbr5_3:b3acsx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ad693113fb36dbf2015507a12a0e8369f436f1a/pkg/sql/opt/exec/execbuilder/testdata/experimental_distsql_planning_5node#L145)):*
> ```
> SET disable_partially_distributed_plans = true
> 
> # TODO(yuzefovich): for some reason the plan below is not local, figure it out.
> ```

can you remove this TODO now?
___
*[pkg/sql/physicalplan/physical_plan.go, line 1243 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxmaXZ4IOP0fTDbGQq:-MlC1Q2gA1x4LfihL427:b-50wuyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/348987d9093f00d0cc79c81c39b3c308e91f56c5/pkg/sql/physicalplan/physical_plan.go#L1243)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The idea behind "partial distribution" is to show that a part of the plan is fully distributed whereas another part of the plan couldn't be distributed, so the latter is executed locally. For example, we could plan table readers on multiple nodes for a single scan (i.e. "full" distribution), but then if we have a render expression involving a function that is Distsql-blocklisted, we have to evaluate that render on the gateway; such a plan with the new distsql spec factory would get "partial distribution".

The need for `allowPartialDistribution` argument came from the desire to not change "distribution" info for plans created by the old exec factory. If we were to keep the previous code of `compose`, then we would often see "partial" distribution when we have a stage of multiple remote processors and then we have a noop processor on the gateway - we would misleadingly say that we couldn't distribute the last stage, so we got the "partial" distribution. However, we actually don't want to "distribute" the last noop processor that is placed on the gateway simply to propagate the result to the client.

I think we have several options:
- plumb `allowPartialDistribution` parameter here (what I'm currently proposing) - this mostly preserves the existing behavior of the old exec factory and the new distsql spec factory
- disallow the "partial" distribution entirely - this will change the behavior of the new distsql spec factory and would call some plans as "fully" distributed when there are parts that have to only run on the gateway
- allow the "partial" distribution for the old exec factory - this will likely be confusing to users.

I've just added a temporary third commit that shows the change to the existing tests for the third option from above.
</blockquote></details>

Hmm... so basically with this change we would never show `distribution: full`, either in the new or old exec factory? Doesn't seem ideal...

Is there a way to just make an exception for the final noop processor? Seems like we'd need that exception anyway to get the desired behavior for the new exec factory.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @rytaft, and @yuzefovich)

___
*[pkg/sql/physicalplan/physical_plan.go, line 1243 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxmaXZ4IOP0fTDbGQq:-MlCCbHu2q2-OXdJbXeQ:b-iao8d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/348987d9093f00d0cc79c81c39b3c308e91f56c5/pkg/sql/physicalplan/physical_plan.go#L1243)):*
> Hmm... so basically with this change we would never show `distribution: full`, either in the new or old exec factory?

Yeah, that was pretty much the case with the previous version of the third commit.

I adjusted the last commit to implement your suggestion. Things are better, but there are still some plans that are called "partial" that I'd like to be called "full". For example 

We have a couple of stages of TableReaders that are planned on the gateway because they read from a single range that lives on the gateway, however, we call such distribution as "local", so when composing things, we'll end up with "partial" which is confusing.

We currently don't have enough expressivity for an example from above. I think I prefer my original approach of essentially disabling "partial" distribution for the old factory so that we mostly keep the existing behavior unchanged (given that we might backport this to 21.2) and that we could think through things better during the distsql spec work.

**Review by rytaft — COMMENTED** [review]
> Reviewed 21 of 21 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/physicalplan/physical_plan.go, line 1243 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxmaXZ4IOP0fTDbGQq:-MlCF2hS-1tHEWq8uokL:bqm5lrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/348987d9093f00d0cc79c81c39b3c308e91f56c5/pkg/sql/physicalplan/physical_plan.go#L1243)):*
> I think I prefer my original approach...

Ok, that sounds fine

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/experimental_distsql_planning_5node, line 145 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MlC0wtT5uviimYbr5_2:-MlCbRxxCK7zG_8gUnAm:b9cfrjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ad693113fb36dbf2015507a12a0e8369f436f1a/pkg/sql/opt/exec/execbuilder/testdata/experimental_distsql_planning_5node#L145)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you remove this TODO now?
</blockquote></details>

No, but I don't think it's critical to figure this out since this only matters with the experimental settings enabled.
___
*[pkg/sql/physicalplan/physical_plan.go, line 1243 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-MkxmaXZ4IOP0fTDbGQq:-MlCbZnH2NQ5SfAkvRSI:bc58tgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/348987d9093f00d0cc79c81c39b3c308e91f56c5/pkg/sql/physicalplan/physical_plan.go#L1243)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> I think I prefer my original approach...

Ok, that sounds fine
</blockquote></details>

Removed the third commit, PTAL.

**Review by rytaft — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70648#-:-MlLi3jr3BXRLkfCNxJU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Pull request merged**
