### PR TITLE
logictest: disable gc job; print statement timings

### PR DESCRIPTION
**Pull request by jordanlewis**
- Disable the GC job in logic tests, which was using up to 1/6th of the CPU time in a DDL-heavy test
- Print statement timings in -show-sql

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
I'm okay with this but would slightly prefer the more targetted knob. This is just going to disable cleaning up data and what not. I get that that's fine, I'm just being nitpicky. 

I'm cool with this if you like what you've got. 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47310#-:-M4WP8iT69pC0Jc9shtE:b-hy1695)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @lucy-zhang, and @RaduBerinde)

___
*[pkg/sql/schema_changer.go, line 1424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47310#-M4WOqT6C3MIzmURp2Jh:-M4WOqT703uyTrEjC4NB:b-sg1c0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/788adb9058b1038407d3b938cec7bc8f22d8987b/pkg/sql/schema_changer.go#L1424)):*
> ```Go
> 	RunBeforeResume func(jobID int64) error
> 	// Disable disables the GC Job from running altogether.
> 	Disable bool
> ```

How do you feel about just disabling the checking for updates? The jobs are only terrible because any time anything happens to the system config span all dropped tables get a message and do something. 
___
*[pkg/sql/logictest/logic.go, line 2118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47310#-M4WPMT8E9SvIb95M_1H:-M4WPMT8E9SvIb95M_1I:b-lbw4h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/08469da8f32488f2e62e83ce940f485c7aaf6c9e/pkg/sql/logictest/logic.go#L2118)):*
> ```Go
> 	}
> 	execSQL, changed := mutations.ApplyString(t.rng, stmt.sql, mutations.ColumnFamilyMutator)
> 	n := time.Now()
> ```

timeutil or the linter will yell 
___
*[pkg/sql/logictest/logic.go, line 2121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47310#-M4WPOPm6O5JCUPxSmDq:-M4WPOPm6O5JCUPxSmDr:b1uqfro) ([raw file](https://github.com/cockroachdb/cockroach/blob/08469da8f32488f2e62e83ce940f485c7aaf6c9e/pkg/sql/logictest/logic.go#L2121)):*
> ```Go
> 	res, err := t.db.Exec(execSQL)
> 	if *showSQL {
> 		t.outf("%s; -- %s", stmt.sql, time.Since(n))
> ```

timeutil

**Review by thoszhang — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/schema_changer.go, line 1424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47310#-M4WOqT6C3MIzmURp2Jh:-M4WVDoh6Z5OeSyPyp2h:b-y1oa33) ([raw file](https://github.com/cockroachdb/cockroach/blob/788adb9058b1038407d3b938cec7bc8f22d8987b/pkg/sql/schema_changer.go#L1424)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How do you feel about just disabling the checking for updates? The jobs are only terrible because any time anything happens to the system config span all dropped tables get a message and do something. 
</blockquote></details>

I think this is a good idea.

**Comment by lucy-zhang** [comment]
I tried this (`make testbaselogic FILES=fk_opt TESTCONFIG=local TESTFLAGS='-test.v -show-sql`) with #47313 and the GC job was negligible in the CPU profile, so I think we should be fine without skipping the GC job in the logic tests.

**Comment by jordanlewis** [comment]
Awesome! I'll back that part of this change out.

**Comment by jordanlewis** [comment]
This is super out of date, so closing.

**Pull request closed without merging**
