### PR TITLE
storage, server: remove allocator options and the balancer

### PR DESCRIPTION
**Pull request by BramGruneir**
Allocator options are no longer needed since use_rule_balancer and enable_rebalancing are both on by default. The balancer is also no longer used except for 2 functions which were moved to rule_solver.go.
This also cleans up all the tests that were duplicated to run with and without the rule solver.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13282)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/node_test.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-KbkxwIRSn7KiXlWbjNo:-KbkxwISEqnZSDYXdztj:b-ew98hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f3ab6b1db33aa0168655e4406a4dbe2a1dd8b8/pkg/server/node_test.go#L99)):*
> ```Go
> 	cfg.Transport = storage.NewDummyRaftTransport()
> 	cfg.MetricsSampleInterval = metric.TestSampleInterval
> 	active, renewal := storage.NodeLivenessDurations(
> ```

how come this is now required but wasn't previously?

---

*[pkg/testutils/localtestcluster/local_test_cluster.go, line 120 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-Kbkxyh6JLlsQGbTP5Pb:-Kbkxyh6JLlsQGbTP5Pc:b-ew98hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f3ab6b1db33aa0168655e4406a4dbe2a1dd8b8/pkg/testutils/localtestcluster/local_test_cluster.go#L120)):*
> ```Go
> 	cfg.DB = ltc.DB
> 	cfg.Gossip = ltc.Gossip
> 	active, renewal := storage.NodeLivenessDurations(
> ```

how come this is now required but wasn't previously?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-:-Kbky1Hs9ZDkqqDnEsj8:bnfp4nl)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/node_test.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-KbkxwIRSn7KiXlWbjNo:-KbkzUCj912tcIcjN-Br:b-aq9dam) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f3ab6b1db33aa0168655e4406a4dbe2a1dd8b8/pkg/server/node_test.go#L99)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come this is now required but wasn't previously?
</blockquote></details>

In both of these cases, if there was no store pool, the allocator would just ignore most values.  This used allocator options and just defaulted to no rebalancing.  Since this is a very artificial scenario and gossip already exists in both of these scenarios, it seemed prudent to add the store pool and liveness instead of adding special cases in the main code to deal with a few tests.

---

*[pkg/testutils/localtestcluster/local_test_cluster.go, line 120 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-Kbkxyh6JLlsQGbTP5Pb:-Kbl-P7D7H6uoAo8c2Qm:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f3ab6b1db33aa0168655e4406a4dbe2a1dd8b8/pkg/testutils/localtestcluster/local_test_cluster.go#L120)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come this is now required but wasn't previously?
</blockquote></details>

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/node_test.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-KbkxwIRSn7KiXlWbjNo:-Kbl-ePOcS6gIJvhfvax:b-69y86i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f3ab6b1db33aa0168655e4406a4dbe2a1dd8b8/pkg/server/node_test.go#L99)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

In both of these cases, if there was no store pool, the allocator would just ignore most values.  This used allocator options and just defaulted to no rebalancing.  Since this is a very artificial scenario and gossip already exists in both of these scenarios, it seemed prudent to add the store pool and liveness instead of adding special cases in the main code to deal with a few tests.
</blockquote></details>

What I'm asking is: "where is the code that changed that made this fail without this addition"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 501 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-Kbl-x30zAy-CE012qMt:-Kbl-x31vKHnPxsDvN6-:by2es68) ([raw file](https://github.com/cockroachdb/cockroach/blob/272007b0b5d72549f7e47be7406b2e56994ef354/pkg/storage/allocator.go#L501)):*
> ```Go
> 	rangeID roachpb.RangeID,
> ) bool {
> 	if !a.options.AllowRebalance {
> ```

Here's an example where it would fail.  Actually, any of these AllowRebalance checks would fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/server/node_test.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-KbkxwIRSn7KiXlWbjNo:-Kbl04lykuyFow1yyxxt:b-u9x3h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f3ab6b1db33aa0168655e4406a4dbe2a1dd8b8/pkg/server/node_test.go#L99)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

What I'm asking is: "where is the code that changed that made this fail without this addition"?
</blockquote></details>

See my other comment in one of the locations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/allocator.go, line 501 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-Kbl-x30zAy-CE012qMt:-Kbl0H4R0aAA4dV5xNCZ:b-15pqun) ([raw file](https://github.com/cockroachdb/cockroach/blob/272007b0b5d72549f7e47be7406b2e56994ef354/pkg/storage/allocator.go#L501)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Here's an example where it would fail.  Actually, any of these AllowRebalance checks would fail.
</blockquote></details>

Ah, I see; the default was false.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282)*

**Comment by BramGruneir** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/storage/allocator.go, line 501 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-Kbl-x30zAy-CE012qMt:-Kbl0brsmgeHBdKtD_uH:b-1vijnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/272007b0b5d72549f7e47be7406b2e56994ef354/pkg/storage/allocator.go#L501)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Ah, I see; the default was false.
</blockquote></details>

Exactly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store_pool.go, line 299 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-Kbl4o96k2sdadBB4JKV:-Kbl4o96k2sdadBB4JKW:b-muvgtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f3ab6b1db33aa0168655e4406a4dbe2a1dd8b8/pkg/storage/store_pool.go#L299)):*
> ```Go
> func (sp *StorePool) getStoreDescriptor(storeID roachpb.StoreID) (roachpb.StoreDescriptor, bool) {
> 	// If during testing you get a panic from this function, it typically means
> 	// that no store pool was created but one was required.
> ```

We could insert this same comment in a ton of code. I realize you ran into this problem while developing this PR, but do you think this specific instance is useful to comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282)*

**Comment by BramGruneir** [comment]
*[pkg/storage/store_pool.go, line 299 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-Kbl4o96k2sdadBB4JKV:-KblAkniW0OyyC58cfnK:b5tgmki) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f3ab6b1db33aa0168655e4406a4dbe2a1dd8b8/pkg/storage/store_pool.go#L299)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We could insert this same comment in a ton of code. I realize you ran into this problem while developing this PR, but do you think this specific instance is useful to comment.
</blockquote></details>

I do.  I tried to add a condition to store, in `Valid()`, but since a number of tests start stores without gossip, that wasn't possible.  And in two separate instances, not having a store pool caused a panic exactly here.  I can remove the comment if you feel strongly, but the failures were cryptic enough that it wasn't clear what the root cause was immediately.  I'd seen this before, but someone writing a new test may be confused by it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store_pool.go, line 299 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-Kbl4o96k2sdadBB4JKV:-KblDOKoOl7krF2T6Hfo:bukhcrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f3ab6b1db33aa0168655e4406a4dbe2a1dd8b8/pkg/storage/store_pool.go#L299)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I do.  I tried to add a condition to store, in `Valid()`, but since a number of tests start stores without gossip, that wasn't possible.  And in two separate instances, not having a store pool caused a panic exactly here.  I can remove the comment if you feel strongly, but the failures were cryptic enough that it wasn't clear what the root cause was immediately.  I'd seen this before, but someone writing a new test may be confused by it.
</blockquote></details>

And the panic led easily to a fix, right? What makes this instance of a nil-pointer dereference worth commenting vs the 1000s of other possibilities in the code base?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282)*

**Comment by BramGruneir** [comment]
*[pkg/storage/store_pool.go, line 299 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282#-Kbl4o96k2sdadBB4JKV:-KblEJqs-GmSuODEgeHG:b23xb5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f3ab6b1db33aa0168655e4406a4dbe2a1dd8b8/pkg/storage/store_pool.go#L299)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

And the panic led easily to a fix, right? What makes this instance of a nil-pointer dereference worth commenting vs the 1000s of other possibilities in the code base?
</blockquote></details>

It's just very far removed from where the test clusters are setup is all.  Clearly you feel strongly about this, I'll remove the comment in an upcoming PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13282)*

**Pull request merged**
