### PR TITLE
sql/stats: turn forecasting constants into cluster settings

### PR DESCRIPTION
**Pull request by michae2**
Turn three constants used for statistics forecasting into cluster settings. (These must be cluster settings rather than session variables because forecasting happens when reloading table statistics in the stats cache, which can be independent of any session.)

Informs: #119967

Release note (sql change): Introduce three new cluster settings for controlling table statistics forecasting:

1. `sql.stats.forecasts.min_observations` is the minimum number of observed statistics required to produce a forecast.

2. `sql.stats.forecasts.min_goodness_of_fit` is the minimum R² (goodness of fit) measurement required from all predictive models to use a forecast.

3. `sql.stats.forecasts.max_decrease` is the most a prediction can decrease, expressed as the minimum ratio of the prediction to the lowest prior observation.

### CODE REVIEW

**Comment by michae2** [comment]
Opening this so that the backports of https://github.com/cockroachdb/cockroach/pull/122273 can be behind some settings.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122779#-:-Nw5jfgXDeu6KqBl3n61:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122779#-:-Nw6J_caELQFkvnnJ87c:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2)

**Comment by michae2** [comment]
Thanks!

bors r=yuzefovich,mgartner

**Comment by michae2** [comment]
bors r=yuzefovich,mgartner

**Pull request merged**
