### PR TITLE
sql: populate information_schema.table_privileges.with_hierarchy

### PR DESCRIPTION
**Pull request by knz**
Pg doc says:

*In the SQL standard, WITH HIERARCHY OPTION is a
separate (sub-)privilege allowing certain operations on table
inheritance hierarchies. In PostgreSQL, this is included in the SELECT
privilege, so this column shows YES if the privilege is SELECT, else
NO.*

https://www.postgresql.org/docs/9.5/infoschema-table-privileges.html

Release note: None

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35578#-:-L_YSA3g-p2giawi08ix:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter and @mjibson)

**Comment by knz** [comment]
TFYR!

bors r+

**Comment by knz** [comment]
requeue after #35583

**Comment by knz** [comment]
requeue after #35583 merges

**Pull request merged**
