### PR TITLE
sql: fixed flakey tests for cancelled/errored schema changes

### LINKED ISSUE #31175: sql: TestBackfillErrors failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/ac2f39fcc6be7366bc786d231890ee91e84f1c3c

Parameters:
```
TAGS=
GOFLAGS=
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=TestBackfillErrors PKG=github.com/cockroachdb/cockroach/pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=955282&tab=buildLog

```
I181010 05:20:26.294912 117836 util/stop/stopper.go:537  quiescing; tasks left:
4      [async] closedts-subscription
1      [async] storage.Replica: computing checksum
1      [async] closedts-rangefeed-subscriber
W181010 05:20:26.294957 115844 gossip/gossip.go:1496  [n4] no incoming or outgoing connections
W181010 05:20:26.295006 115395 gossip/gossip.go:1496  [n2] no incoming or outgoing connections
W181010 05:20:26.295010 116077 gossip/gossip.go:1496  [n5] no incoming or outgoing connections
I181010 05:20:26.295133 117836 util/stop/stopper.go:537  quiescing; tasks left:
4      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
W181010 05:20:26.295250 116646 storage/raft_transport.go:583  [n1] while processing outgoing Raft queue to node 3: EOF:
W181010 05:20:26.295303 116597 storage/raft_transport.go:583  [n5] while processing outgoing Raft queue to node 1: EOF:
W181010 05:20:26.295348 116508 storage/raft_transport.go:583  [n4] while processing outgoing Raft queue to node 1: EOF:
W181010 05:20:26.295424 116659 storage/raft_transport.go:583  [n2] while processing outgoing Raft queue to node 1: EOF:
W181010 05:20:26.295469 116543 storage/raft_transport.go:583  [n1] while processing outgoing Raft queue to node 4: rpc error: code = Canceled desc = context canceled:
W181010 05:20:26.295641 116606 storage/raft_transport.go:583  [n1] while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = context canceled:
I181010 05:20:26.295787 117838 util/stop/stopper.go:537  quiescing; tasks left:
4      [async] closedts-subscription
I181010 05:20:26.295803 117838 util/stop/stopper.go:537  quiescing; tasks left:
3      [async] closedts-subscription
I181010 05:20:26.295917 117836 util/stop/stopper.go:537  quiescing; tasks left:
3      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181010 05:20:26.295939 117836 util/stop/stopper.go:537  quiescing; tasks left:
2      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181010 05:20:26.296020 117838 util/stop/stopper.go:537  quiescing; tasks left:
2      [async] closedts-subscription
I181010 05:20:26.296035 117838 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-subscription
I181010 05:20:26.296300 117836 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181010 05:20:26.296315 117836 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-subscription
I181010 05:20:26.296413 117835 util/stop/stopper.go:537  quiescing; tasks left:
3      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181010 05:20:26.296494 117835 util/stop/stopper.go:537  quiescing; tasks left:
2      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181010 05:20:26.296606 117835 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181010 05:20:26.296621 117835 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
I181010 05:20:26.296944 117837 util/stop/stopper.go:537  quiescing; tasks left:
4      [async] closedts-subscription
I181010 05:20:26.296971 117837 util/stop/stopper.go:537  quiescing; tasks left:
3      [async] closedts-subscription
I181010 05:20:26.297048 117834 util/stop/stopper.go:537  quiescing; tasks left:
3      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181010 05:20:26.297068 117837 util/stop/stopper.go:537  quiescing; tasks left:
2      [async] closedts-subscription
I181010 05:20:26.297068 117834 util/stop/stopper.go:537  quiescing; tasks left:
3      [async] closedts-subscription
I181010 05:20:26.297158 117834 util/stop/stopper.go:537  quiescing; tasks left:
2      [async] closedts-subscription
I181010 05:20:26.297245 117834 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-subscription
I181010 05:20:26.297379 117837 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-subscription
--- FAIL: TestBackfillErrors (2.36s)
	schema_changer_test.go:937: got err=%!s(<nil>)

```

### PR DESCRIPTION
**Pull request by eriktrinh**
TestBackfillError had the async schema changer execute immediately,
before the synchronous one could see the error.

TestCancelSchemaChange had the GC TTL set to 0 during the SELECT.

Fixes #31175, #31177

Release note: None

### CODE REVIEW

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31195)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer_test.go, line 943 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31195#-LOTvH6G3iOUY_diEr0d:-LOTvH6HALsOcR8QaJ7U:b-pkj8dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ace102c5daa34e0372795fd46ae2ff55cab2e74/pkg/sql/schema_changer_test.go#L943)):*
> ```Go
> 	}
> 
> 	atomic.StoreUint32(&enableAsyncSchemaChanges, 1)
> ```

We're going to hit the same problem with the other schema change failures below; as in they might no error.

I think it's best to not use checkTableKeyCount() in this test and used something more specialized and sprinkle that whereever we use checkTableKeyCount() and *not* turn on the quick async schema changer. In other words, the key count checker can count the non GC-ed index data.

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31195)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer_test.go, line 943 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31195#-LOTvH6G3iOUY_diEr0d:-LOUdZLK0eVLCIbxTPlp:b6245y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ace102c5daa34e0372795fd46ae2ff55cab2e74/pkg/sql/schema_changer_test.go#L943)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

We're going to hit the same problem with the other schema change failures below; as in they might no error.

I think it's best to not use checkTableKeyCount() in this test and used something more specialized and sprinkle that whereever we use checkTableKeyCount() and *not* turn on the quick async schema changer. In other words, the key count checker can count the non GC-ed index data.
</blockquote></details>

Done, as discussed there is a more generic keycount checker for the garbage index data.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31195)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
this may need a backport

**Comment by vivekmenezes** [comment]
This is for 2.2

**Pull request merged**
