### PR TITLE
sql: fixup ALTER's handling of various constraint types

### LINKED ISSUE #8724: sql: dropping constraint drops unrelated index instead
```
root@:26257> CREATE TABLE t (id int primary key, email STRING, INDEX email (email), CONSTRAINT email CHECK (STRPOS(email, '@') > 0));
CREATE TABLE
root@:26257> SHOW CONSTRAINTS FROM t;
+-------+---------+-------------+-----------+------------------------+
| Table |  Name   |    Type     | Column(s) |        Details         |
+-------+---------+-------------+-----------+------------------------+
| t     | email   | CHECK       | NULL      | STRPOS(email, '@') > 0 |
| t     | primary | PRIMARY KEY | [id]      | NULL                   |
+-------+---------+-------------+-----------+------------------------+
root@:26257> ALTER TABLE t DROP CONSTRAINT email;
ALTER TABLE
root@:26257> SHOW CREATE TABLE t;
+-------+------------------------------------------------------+
| Table |                     CreateTable                      |
+-------+------------------------------------------------------+
| t     | CREATE TABLE t (␤                                    |
|       |     id INT NOT NULL,␤                                |
|       |     email STRING NULL,␤                              |
|       |     CONSTRAINT "primary" PRIMARY KEY (id),␤          |
|       |     FAMILY "primary" (id, email),␤                   |
|       |     CONSTRAINT email CHECK (STRPOS(email, '@') > 0)␤ |
|       | )                                                    |
+-------+------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by dt**
sql: auto-generate CHECK constraint names
this means that all table-level constraints (i.e. which can only be dropped with `ALTER TABLE DROP CONSTRAINT`) have names and can thus be referred to.

sql: refactor gathering constraint info into common helper
having each callsite that has to handle listing/checking all constraints for a table extract them itself
seems like a recipe for mistakes -- somewhere someone will forget to check an index for an FK. 

sql: add handling of CHECK and FK to ALTER..DROP CONSTRAINT
Uses the common constrtaint colleting to handle attempts at dropping constraints by name, and correctly handle attempts to drop CHECK or FOREIGN KEY constraints. Attempts to drop UNIQUE constraints now result in an error, since the only possible implementation currently would be to drop the index but doing that implicitly could easily be a nasty operational surprise.

Named (NOT) NULL and DEFAULT constraints aren't handled -- they're already handled by dedicated grammar for alter column, and potentially should be included in named table constraints at all?

Fixes #8724.

Also error when trying to add a column with an unsupported constraint -- CHECK and FK refs generally need to be validated as rows are written, but for new columns where a DEFAULT might backfill violating values, we'd need to special handling during add. Until that is implemented, we should explicitly reject 

sql: mark ALTER col TYPE unimplemented ( currently shows up in grammar but returns 'unknown alter cmd: <nil>' at runtime)

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8747)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 4 of 4 files at r1, 8 of 8 files at r2, 2 of 2 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/alter_table.go, line 179 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3RGse4870rzglzBEY:-KQ3RGse4870rzglzBEZ:b-eqensh) ([raw file](https://github.com/cockroachdb/cockroach/blob/87873e86c337097ab7a9032217edea4f3e625cee/sql/alter_table.go#L179)):*
> ```Go
> 			}
> 			switch details.Kind {
> 			case "PRIMARY KEY":
> ```

If we're going to switch to an approach like this, it seems appropriate that these strings be enumerated somewhere.

---

*[sql/create.go, line 844 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3Njk_pUVWvxr591-L:-KQ3Njk_pUVWvxr591-M:byevl7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/83e4682b581ab7ba1bf360bbba359ad3d2e6c434/sql/create.go#L844)):*
> ```Go
> 			var nameBuf bytes.Buffer
> 			name := string(d.Name)
> 			if name == "" {
> ```

nit: I think it would be slightly clearer how this all works if you did something like `generateName := name == ""` and then used that variable below in place of all the `if name == "" {` checks.

---

*[sql/sqlbase/table.go, line 1382 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3QYuunX4SZJC3BRCy:-KQ3QYuunX4SZJC3BRCz:b-5fn17d) ([raw file](https://github.com/cockroachdb/cockroach/blob/481fbb94c9777eebeabff70865e4f74019749a60/sql/sqlbase/table.go#L1382)):*
> ```Go
> 
> // GetConstraintInfo returns a summary of all constraints on the table
> // If `full` is false, it
> ```

it what? The suspense is killing me :)

---

*[sql/sqlbase/table.go, line 1387 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3QLZZg9hYEE00dTro:-KQ3QLZ_EFISN_IbZ9gO:b-tsavlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/481fbb94c9777eebeabff70865e4f74019749a60/sql/sqlbase/table.go#L1387)):*
> ```Go
> }
> 
> // CheckUniqueConstraints returns a non-nil error if a descriptor contains two
> ```

Seems like you might want to make this comment and method name a little more general because it's doing more than just checking for duplicate constraint names.

---

*[sql/testdata/table, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3O_gKoLzSamvKD9Om:-KQ3O_gLL-nSAuT4rMdU:bt1ecxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/83e4682b581ab7ba1bf360bbba359ad3d2e6c434/sql/testdata/table#L197)):*
> ```
> )
> 
> statement error duplicate constraint name: "check_foo"
> ```

I'm a little curious if this is desirable behavior. If a user doesn't care what the constraint name is, why throw a duplicate name error instead of just calling it `check_foo2` or something. I looks like Postgres will create `duple_generated_foo_check`, `duple_generated_bar_check`, and `duple_generated_foo_check1` from the following statement without throwing an error.

```
postgres=# CREATE TABLE duple_generated (
  foo INT CHECK (foo > 1),
  bar INT CHECK (bar > 2),
  CHECK (foo > 2)
);
CREATE TABLE
postgres=# select constraint_name from information_schema.table_constraints WHERE table_name = 'duple_generated';
      constraint_name
----------------------------
 duple_generated_foo_check
 duple_generated_bar_check
 duple_generated_foo_check1
(3 rows)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/alter_table.go, line 179 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3RGse4870rzglzBEY:-KQKe4Y_4ncq2dSgiKXl:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/87873e86c337097ab7a9032217edea4f3e625cee/sql/alter_table.go#L179)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> If we're going to switch to an approach like this, it seems appropriate that these strings be enumerated somewhere.
</details>
+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747)*

**Comment by dt** [comment]
Review status: 0 of 18 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/alter_table.go, line 179 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3RGse4870rzglzBEY:-KQMwEu8nQ8TOH9SAFjJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87873e86c337097ab7a9032217edea4f3e625cee/sql/alter_table.go#L179)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> +1
</details>
Done.

---

*[sql/create.go, line 844 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3Njk_pUVWvxr591-L:-KQMwfd50sytrkaFbGHL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83e4682b581ab7ba1bf360bbba359ad3d2e6c434/sql/create.go#L844)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> nit: I think it would be slightly clearer how this all works if you did something like `generateName := name == ""` and then used that variable below in place of all the `if name == "" {` checks.
</details>
Done.

---

*[sql/sqlbase/table.go, line 1382 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3QYuunX4SZJC3BRCy:-KQMxN4L_dayQCBGW5So:b-kxsp7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/481fbb94c9777eebeabff70865e4f74019749a60/sql/sqlbase/table.go#L1382)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> it what? The suspense is killing me :)
</details>
whoops, left over from prev draft, before I split out the separate public methods for check vs summary.

---

*[sql/sqlbase/table.go, line 1387 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3QLZZg9hYEE00dTro:-KQMwmPW0co1QcyBz50x:b-zgaib2) ([raw file](https://github.com/cockroachdb/cockroach/blob/481fbb94c9777eebeabff70865e4f74019749a60/sql/sqlbase/table.go#L1387)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Seems like you might want to make this comment and method name a little more general because it's doing more than just checking for duplicate constraint names.
</details>
this one shouldn't be doing anything else since it passes a nil txn into the collectConstraintInfo.

---

*[sql/testdata/table, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQ3O_gKoLzSamvKD9Om:-KQNDgEDYwNTS_PPgJnE:bo3xv26) ([raw file](https://github.com/cockroachdb/cockroach/blob/83e4682b581ab7ba1bf360bbba359ad3d2e6c434/sql/testdata/table#L197)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I'm a little curious if this is desirable behavior. If a user doesn't care what the constraint name is, why throw a duplicate name error instead of just calling it `check_foo2` or something. I looks like Postgres will create `duple_generated_foo_check`, `duple_generated_bar_check`, and `duple_generated_foo_check1` from the following statement without throwing an error.
> 
> ```
> postgres=# CREATE TABLE duple_generated (
>   foo INT CHECK (foo > 1),
>   bar INT CHECK (bar > 2),
>   CHECK (foo > 2)
> );
> CREATE TABLE
> postgres=# select constraint_name from information_schema.table_constraints WHERE table_name = 'duple_generated';
>       constraint_name
> ----------------------------
>  duple_generated_foo_check
>  duple_generated_bar_check
>  duple_generated_foo_check1
> (3 rows)
> ```
</details>
added a best-effort at unique-ing generated names as described.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 2 of 16 files at r5, 1 of 4 files at r6, 8 of 11 files at r7, 5 of 6 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 1015 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQRSKa1Wt1C_y87L99-:-KQRSKa1Wt1C_y87L990:bnarq9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5459abc70a896f4927a80dbac3b30551efd212/sql/create.go#L1015)):*
> ```Go
> 				if _, ok := generatedNames[name]; ok {
> 					i := 1
> 					for {
> ```

Nice. We can probably do better than this `O(n^2)` solution, but I doubt it's worth the effort.

---

*[sql/sqlbase/table.go, line 130 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQRSzXzF_1FQmYpXnyk:-KQRSzXzF_1FQmYpXnyl:b4mha7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5459abc70a896f4927a80dbac3b30551efd212/sql/sqlbase/table.go#L130)):*
> ```Go
> 
> 	if d.CheckExpr.Expr != nil {
> 		// Should never happen since `hoistConstraints` moves these to table level
> ```

Will this create any migration issues?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-:-KQRTF5p8N3hV2pFKTJD:bnfp4nl)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 1015 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQRSKa1Wt1C_y87L99-:-KQRWwJBaSG8RFe9YeLS:bpkmd8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5459abc70a896f4927a80dbac3b30551efd212/sql/create.go#L1015)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Nice. We can probably do better than this `O(n^2)` solution, but I doubt it's worth the effort.
</details>
yeah, not worth it imo since this is only run during create.

---

*[sql/sqlbase/table.go, line 130 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQRSzXzF_1FQmYpXnyk:-KQRX4HcK_rM426SUPLc:b-q77k02) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5459abc70a896f4927a80dbac3b30551efd212/sql/sqlbase/table.go#L130)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Will this create any migration issues?
</details>
don't think so? this only looking at AST, not protos.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/table.go, line 130 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747#-KQRSzXzF_1FQmYpXnyk:-KQRiYOaJKuPXTLKq8lG:b-ly03p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5459abc70a896f4927a80dbac3b30551efd212/sql/sqlbase/table.go#L130)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> don't think so? this only looking at AST, not protos.
</details>
specifically: `hoistConstraints` moves the column-level constraints to table level in the parsed AST for `CREATE TABLE`, so we should never see one here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8747)*

**Comment by dt** [comment]
@vivekmenezes did you get a chance to look at this yet?

**Pull request merged**
