### PR TITLE
roachtest/mixed-versions-compat: use corpus for master

### PR DESCRIPTION
**Pull request by fqazi**
Informs: #91350

The CI build scripts take advantage of the branch name to uplaod the corpus to GCS. Unfortunately, we have no way of know if the current build is master inside the roachtest. To address this, this patch supports fetching the master corpus as a fallback.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91458#-:-NGMbPbDA5NA-MZw7hcX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by fqazi** [comment]
@ajwerner I'm going to bors this to have the test functional again, but we do have a compatibility issue between master and 22.2 in the mixed version state (which is planning related)

**Pull request merged**
