### PR TITLE
sql/*: fix improperly wrapped errors

### PR DESCRIPTION
**Pull request by rafiss**
refs #42510

I'm working on a linter that detects errors that are not wrapped
correctly, and it discovered these.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: mod the comments

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72350#-:-MnXQh7M7x4TS8DjZk-G:b-r2y7ow)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/alter_column_type.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72350#-MnXQ1YE3cmI84No5sn5:-MnXQ1YE3cmI84No5sn6:b33f1fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/659fb680acd1fe8a9ea4d4d4f60384bdc504b5e6/pkg/sql/alter_column_type.go#L410)):*
> ```
> var x = `se
> `
> ```
what's this about?
___
*[pkg/sql/type_change_test.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72350#-MnXQ71U52OvTtwlvUFt:-MnXQ71U52OvTtwlvUFu:b-c23edu) ([raw file](https://github.com/cockroachdb/cockroach/blob/659fb680acd1fe8a9ea4d4d4f60384bdc504b5e6/pkg/sql/type_change_test.go#L585)):*
> ```Go
> 					}
> 					if !testutils.IsError(err, "invalid input value for enum") {
> 						return errors.AssertionFailedf("expected invalid input for enum error, found %v", err)
> ```

I think you've got another case to add to your linter. Shouldn't this use `errors.NewAssertionErrorWithWrappedErrf`

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72350)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/alter_column_type.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72350#-MnXQ1YE3cmI84No5sn5:-MnXQwpiCq2oRc0ZgcNa:b2c85ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/659fb680acd1fe8a9ea4d4d4f60384bdc504b5e6/pkg/sql/alter_column_type.go#L410)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> var x = `se
> `
> ```
what's this about?
</blockquote></details>

no idea; nice catch
___
*[pkg/sql/type_change_test.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72350#-MnXQ71U52OvTtwlvUFt:-MnXR1vr65Y3DwoAewrB:bil254k) ([raw file](https://github.com/cockroachdb/cockroach/blob/659fb680acd1fe8a9ea4d4d4f60384bdc504b5e6/pkg/sql/type_change_test.go#L585)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think you've got another case to add to your linter. Shouldn't this use `errors.NewAssertionErrorWithWrappedErrf`
</blockquote></details>

hm so this one i wasn't quite sure what to do. not wrapping the error here made sense to me since the problem in this case is that an error was expected, but it was the wrong type. but `NewAssertionErrorWithWrappedErrf` seems like the best of both worlds; didn't know about that.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72350)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/type_change_test.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72350#-MnXQ71U52OvTtwlvUFt:-MnXSqiz8WAzaJVU06Wd:bsyu1gk) ([raw file](https://github.com/cockroachdb/cockroach/blob/659fb680acd1fe8a9ea4d4d4f60384bdc504b5e6/pkg/sql/type_change_test.go#L585)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm so this one i wasn't quite sure what to do. not wrapping the error here made sense to me since the problem in this case is that an error was expected, but it was the wrong type. but `NewAssertionErrorWithWrappedErrf` seems like the best of both worlds; didn't know about that.
</blockquote></details>

and i'll make sure my linter looks for this function too. (will send that PR up once these fix PRs are in)

**Comment by rafiss** [comment]
bors r=ajwerner

**Comment by rafiss** [comment]
bors r=ajwerner

**Comment by rafiss** [comment]
bors r=ajwerner

**Pull request merged**
