### PR TITLE
sql: write backward-comptatible data using colfamilies

### PR DESCRIPTION
**Pull request by danhhz**
This commit replaces the column-based kv writing code with the family-based
version. No reading code is changed, but the tests and reading code are left
unchanged to verify backward compatibility of the new code and the way
MaybeUpgradeFormatVersion configures the ColumnFamilyDescriptors.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7122)

### CODE REVIEW

**Comment by paperstreet** [comment]
Note to self: benchmark this to make sure nothing changed

**Comment by paperstreet** [comment]
Seems like I introduced one alloc per row in the Insert benchmark. I've been pprof-ing it but I don't see where, does anyone else?

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> #### sql: write backward\-comptatible data using colfamilies
> 
> This commit replaces the column-based kv writing code with the family-based
> 
> version. No reading code is changed, but the tests and reading code are left
> 
> unchanged to verify backward compatibility of the new code and the way
> 
> MaybeUpgradeFormatVersion configures the ColumnFamilyDescriptors.
> 
> 
> 
</details>


---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-:-KJqZb6MuNY3PZTGcVAg:-945030764)*

**Comment by paperstreet** [comment]
Fixed the benchmarks. This is ready for review

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Seems like I introduced one alloc per row in the Insert benchmark. I've been pprof-ing it but I don't see where, does anyone else?
</details>


---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-:-KJr5wI7omDfOmm76OZS:1727129128)*

**Comment by RaduBerinde** [comment]
:lgtm: modulo one thing for MakeFamilyKey

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Fixed the benchmarks. This is ready for review
</details>


---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[keys/keys.go, line 506 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-KJuZhfp318nGngFXCTI:-KJuZhfp318nGngFXCTJ:1458027867) ([raw file](https://github.com/cockroachdb/cockroach/blob/14fc4d4e92584c1eee63188f0b0180901c1c435b/keys/keys.go#L506)):*
> ```Go
> 
> // MakeFamilyKey returns the key for the family in the given row.
> func MakeFamilyKey(rowKey []byte, famID uint32) []byte {
> ```

What are the semantics of this function w.r.t to rowKey? Specifically - do we append to it or always make a copy? (Explain in the function comment)

The implementation is inconsistent - we append in the `famId == 0` case, we make a copy otherwise..

Perhaps we need two versions of the function?

---

*[keys/keys.go, line 510 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-KJuZP7XCfxQ7y1dZ9NB:-KJuZP7XCfxQ7y1dZ9NC:-1518389882) ([raw file](https://github.com/cockroachdb/cockroach/blob/14fc4d4e92584c1eee63188f0b0180901c1c435b/keys/keys.go#L510)):*
> ```Go
> 		return encoding.EncodeUvarintAscending(rowKey, 0)
> 	}
> 	key := append([]byte(nil), rowKey...)
> ```

Here we could do `key := make([]byte, len(key), len(key) + 8` (or whatever) to avoid reallocations when we append the varints

---

*[sql/rowwriter.go, line 256 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-KJu_El8_vLb2CUJsU2a:-KJu_El8_vLb2CUJsU2b:-843651031) ([raw file](https://github.com/cockroachdb/cockroach/blob/14fc4d4e92584c1eee63188f0b0180901c1c435b/sql/rowwriter.go#L256)):*
> ```Go
> 				}
> 				// Skip primary key columns as their values are encoded in the key of
> 				// each family. Family 0 is guaranteed to exist and acts as a sentinal.
> ```

sentinel

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-:-KJu_X6SDll2WS9FXFsf:1854904687)*

**Comment by paperstreet** [comment]
RFAL. base..r5 is the current version of the original commit. r6 is a new commit that adds a hack to keep us at the same number of allocs as before

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> :lgtm: modulo one thing for MakeFamilyKey
</details>


---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[keys/keys.go, line 506 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-KJuZhfp318nGngFXCTI:-KKAfZIQZPMPN2fO13ao:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/14fc4d4e92584c1eee63188f0b0180901c1c435b/keys/keys.go#L506)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> What are the semantics of this function w.r.t to rowKey? Specifically - do we append to it or always make a copy? (Explain in the function comment)
> 
> The implementation is inconsistent - we append in the `famId == 0` case, we make a copy otherwise..
> 
> Perhaps we need two versions of the function?
</details>
Done.

---

*[keys/keys.go, line 510 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-KJuZP7XCfxQ7y1dZ9NB:-KKAes1EjA_SEUmg0Shi:163355108) ([raw file](https://github.com/cockroachdb/cockroach/blob/14fc4d4e92584c1eee63188f0b0180901c1c435b/keys/keys.go#L510)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Here we could do `key := make([]byte, len(key), len(key) + 8` (or whatever) to avoid reallocations when we append the varints
</details>
I'm going to do a followup that switches to something like engine.ChunkAllocator, which avoids all these allocations.

---

*[sql/rowwriter.go, line 256 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-KJu_El8_vLb2CUJsU2a:-KKAfw9y1QjbSPT78o-7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/14fc4d4e92584c1eee63188f0b0180901c1c435b/sql/rowwriter.go#L256)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> sentinel
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-:-KKAg0LXoIWkO61TJtyG:2022641038)*

**Comment by RaduBerinde** [comment]
:lgtm:

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> RFAL. base..r5 is the current version of the original commit. r6 is a new commit that adds a hack to keep us at the same number of allocs as before
</details>


---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-:-KKAtsV6Rgt_qOIHSChE:1417088721)*

**Comment by dt** [comment]
Looks like this wants a quick rebase to pickup the recent npm stuff?

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> :lgtm:
</details>


---

Reviewed 3 of 6 files at r1, 1 of 3 files at r5, 1 of 2 files at r6.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-:-KKAw5ywUMpmQzwlfVLK:1229372596)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1, 1 of 3 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[keys/keys.go, line 526 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-KKBFnj1-VCnE4XWsrWV:-KKBFnj1-VCnE4XWsrWW:-2087502070) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cfb33f86cbe3c4d7116090b652d60a904fe202/keys/keys.go#L526)):*
> ```Go
> // MakeNonColumnKey creates a non-column key for a row by appending a 0 column
> // ID suffix size to rowKey.
> // TODO(dan): Delete this in favor of MakeFamilyKey(0) once the allocation
> ```

i think you can do this now, yeah?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122)*

**Comment by tamird** [comment]
Reviewed 2 of 4 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/backfill.go, line 353 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-KKEAMejqvVbGH2rosM3:-KKEAMejqvVbGH2rosM4:160895864) ([raw file](https://github.com/cockroachdb/cockroach/blob/8edc1b587be57c4f7815197cf555bc6dca2e2ebc/sql/backfill.go#L353)):*
> ```Go
> 
> 			copy(oldValues, row)
> 			for j := len(row); j < len(oldValues); j++ {
> ```

that's random - why'd this go from `i` to `j`? oh - it's because there's an outer `i`. perhaps the same treatment should apply to the two preceding `for` loops.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122)*

**Comment by paperstreet** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[keys/keys.go, line 526 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-KKBFnj1-VCnE4XWsrWV:-KKEEGn5lKQRuSEm2hG3:-1024767824) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5cfb33f86cbe3c4d7116090b652d60a904fe202/keys/keys.go#L526)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i think you can do this now, yeah?
</details>
Yup! Will do in a fast follow

---

*[sql/backfill.go, line 353 \[r9\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122#-KKEAMejqvVbGH2rosM3:-KKEDjwp_RTMqyh2l8DV:-349260986) ([raw file](https://github.com/cockroachdb/cockroach/blob/8edc1b587be57c4f7815197cf555bc6dca2e2ebc/sql/backfill.go#L353)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> that's random - why'd this go from `i` to `j`? oh - it's because there's an outer `i`. perhaps the same treatment should apply to the two preceding `for` loops.
</details>
Huh. This was because of a linter error. Strange it didn't pick up the others. Will do in a fast follow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7122)*

**Pull request merged**
