### PR TITLE
sql: enable 1PC optimization for UPSERT

### PR DESCRIPTION
**Pull request by petermattis**
When an UPSERT is being run as part of an auto-commit transaction,
commit the transaction when running the batch.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13500)

### CODE REVIEW

**Comment by petermattis** [comment]
Do we have any tests for the auto-commit code path for INSERT? A quick scan didn't reveal anything, but perhaps I just missed it.

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/tablewriter.go, line 466 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-KcVo8lJujfMsPMtNmeN:-KcVo8lKztfGgm3N4b3B:b-tn2zjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e308de18252bf569d97ab1ccc3bf8d6c60cf4f81/pkg/sql/tablewriter.go#L466)):*
> ```Go
> 		}
> 		if err != nil {
> 			return sqlbase.ConvertBatchError(tu.ri.helper.tableDesc, tu.fastPathBatch)
> ```

Noticed we had this in `tableInserter.finalize`. Is it needed here too? I suppose for the upsert fast-path we can't get conditional put errors because we're not performing conditional puts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500)*

**Comment by knz** [comment]
No we don't have separate tests for the INSERT auto-commit apparently.

:lgtm: for the rest.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/tablewriter.go, line 466 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-KcVo8lJujfMsPMtNmeN:-KcYRQIomAuHqkfGpceW:b-fpx6yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e308de18252bf569d97ab1ccc3bf8d6c60cf4f81/pkg/sql/tablewriter.go#L466)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Noticed we had this in `tableInserter.finalize`. Is it needed here too? I suppose for the upsert fast-path we can't get conditional put errors because we're not performing conditional puts.
</blockquote></details>

yeah as long as we don't allow upsert/update to update the PKs this check here is not strictly necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-:-KcYRtvKzxdIiDOMzr-u:bebciqw)*

**Comment by danhhz** [comment]
:lgtm:

my upsert test is going in as soon as teamcity finishes if you want to piggy back on that test. seems like that would work

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/tablewriter.go, line 466 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-KcVo8lJujfMsPMtNmeN:-KcYUdIlf2IiMeayOOwh:b-ygrgaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e308de18252bf569d97ab1ccc3bf8d6c60cf4f81/pkg/sql/tablewriter.go#L466)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yeah as long as we don't allow upsert/update to update the PKs this check here is not strictly necessary.
</blockquote></details>

correct. the fast path doesn't use cput and can't change a pk

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-:-KcYVN0KWFsBtCrcnlDk:b-6z41ua)*

**Comment by petermattis** [comment]
Enhanced `TestUpsertFastPath` to check for 1PC transactions and enabled 1PC transactions for slow-path UPSERT (found by the test!).

PTAL

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/tablewriter.go, line 466 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-KcVo8lJujfMsPMtNmeN:-KcYiNC4e5zWfmW8oXg7:b-kh69w2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e308de18252bf569d97ab1ccc3bf8d6c60cf4f81/pkg/sql/tablewriter.go#L466)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

correct. the fast path doesn't use cput and can't change a pk
</blockquote></details>

Ok, the call to `sqlbase.ConvertBatchError` was removed here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-:-KcYiRPtvpH72iCqcOET:bo7r89h)*

**Comment by danhhz** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/tablewriter.go, line 335 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-KcYj9AL7yAEHmU5sZ7g:-KcYj9AL7yAEHmU5sZ7h:ba2f6zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c0c38388a2be0e81bd1ffb75757d236703f0ea/pkg/sql/tablewriter.go#L335)):*
> ```Go
> 	}
> 
> 	if tu.autoCommit {
> ```

I think this one is not safe. In theory, flush is called once per N rows processed by upsert (though it seems actually doing this got left as a TODO). This would commit the txn and then try to keep using it, which IIUC is not okay

---

*[pkg/sql/upsert_test.go, line 105 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-KcYjz38ZoUJWvbOyNzi:-KcYjz38ZoUJWvbOyNzj:b4lim52) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c0c38388a2be0e81bd1ffb75757d236703f0ea/pkg/sql/upsert_test.go#L105)):*
> ```Go
> 	}
> 	if s := atomic.LoadUint64(&beginTxn); s != 0 {
> 		t.Errorf("expected no begin-txn (1PC) but got %d", s)
> ```

we should probably add one that _does_ expect a begin-txn

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500)*

**Comment by petermattis** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/tablewriter.go, line 335 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-KcYj9AL7yAEHmU5sZ7g:-Kc_abxPm7MaevfczUZq:b-kf7eg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c0c38388a2be0e81bd1ffb75757d236703f0ea/pkg/sql/tablewriter.go#L335)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I think this one is not safe. In theory, flush is called once per N rows processed by upsert (though it seems actually doing this got left as a TODO). This would commit the txn and then try to keep using it, which IIUC is not okay
</blockquote></details>

I've added a `finalize` parameter to `flush` and set it to true from the one call site. Hopefully this will future proof the code here.

---

*[pkg/sql/upsert_test.go, line 105 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-KcYjz38ZoUJWvbOyNzi:-Kc_akXF3_54iPycuWzb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8c0c38388a2be0e81bd1ffb75757d236703f0ea/pkg/sql/upsert_test.go#L105)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

we should probably add one that _does_ expect a begin-txn
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13500#-:-Kc_dK4pevnqxIx-31lU:bnfp4nl)*

**Pull request merged**
