### PR TITLE
colexechash: introduce a type alias for keyID

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Review by michae2 — CHANGES_REQUESTED** [review]
Thanks for doing this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75595#-:-MuRl1ox9hsTkbhQEVmW:bxgavm9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/colexec/colexechash/hashtable.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75595#-MuRk06D1l0L7pA97vl_:-MuRjyZvDJ1J3PFFE2z5:bia5sva) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5887ce40c70eba14266ec654bac5a9c81e668bd/pkg/sql/colexec/colexechash/hashtable.go#L73)):*
> ```Go
> //
> // keyID of 0 is reserved to indicate the end of the hash chain.
> type keyID uint64
> ```

Ah, crap, I misled you. I was wrong, this should probably be a "type alias declaration" not a "type definition" (TIL they are different in go!). In other words, this should probably be:

```
type keyID = uint64
```

And by adding that equals sign, we should be able to use `[]uint64` as `[]keyID` and vice-versa (even without explicit casts). Then you won't need the `unsafe.Pointer` stuff and in general that will make life much easier. Sorry about that!



_Code quote:_
```Go
type keyID uint64
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[pkg/sql/colexec/colexechash/hashtable.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75595#-MuRk06D1l0L7pA97vl_:-MuRnKQM5ZDeOQpLxj99:b-75s7u6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5887ce40c70eba14266ec654bac5a9c81e668bd/pkg/sql/colexec/colexechash/hashtable.go#L73)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Ah, crap, I misled you. I was wrong, this should probably be a "type alias declaration" not a "type definition" (TIL they are different in go!). In other words, this should probably be:

```
type keyID = uint64
```

And by adding that equals sign, we should be able to use `[]uint64` as `[]keyID` and vice-versa (even without explicit casts). Then you won't need the `unsafe.Pointer` stuff and in general that will make life much easier. Sorry about that!
</blockquote></details>

Oops, this makes sense, I don't know why I didn't think of this myself right away, I guess I wasn't consciously aware of these differences too. PTAL.

**Review by michae2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75595#-:-MuRndhV1T02LroOXCIM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
