### PR TITLE
server: export node ID gauge with advertised RPC and HTTP address labels

### LINKED ISSUE #8674: monitoring: export node ID / hostname
Having the node ID and hostname available for use by external monitoring makes it much simpler to link back to actual nodes or the admin UI.
We would need to export the hostname as a label.
The node ID can be its own metric, I don't think it's worth it to add it as a label to all metrics for that node.

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #8674

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14544)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/status/recorder.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544#-Kgo5LftPPCaKqGFpDpq:-Kgo5LftPPCaKqGFpDpr:b-lmymn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4ae559b55ff9b98074b48f5b3d5882dd585f27/pkg/server/status/recorder.go#L50)):*
> ```Go
> 	nodeTimeSeriesPrefix = "cr.node.%s"
> 
> 	advertiseAddrLabelKey = "advertiseAddr"
> ```

@mberhault Is there a standard for label names? Should this be lowercase-with-hyphens?

---

*[pkg/server/status/recorder.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544#-Kgo5IQDM81SzipbnlRK:-Kgo5IQDM81SzipbnlRL:b69esob) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4ae559b55ff9b98074b48f5b3d5882dd585f27/pkg/server/status/recorder.go#L145)):*
> ```Go
> 	// Create node ID gauge metric with host as a label.
> 	metadata := metric.Metadata{
> 		Name: "node_id",
> ```

We use lowercase-with-hyphens for other metric names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544)*

**Comment by spencerkimball** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/status/recorder.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544#-Kgo5LftPPCaKqGFpDpq:-KgonjT1VujMTgMTU10b:b-q1mqcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4ae559b55ff9b98074b48f5b3d5882dd585f27/pkg/server/status/recorder.go#L50)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@mberhault Is there a standard for label names? Should this be lowercase-with-hyphens?
</blockquote></details>

In their documentation they seem to use lowercase with underscores, so I changed these to follow that pattern.

---

*[pkg/server/status/recorder.go, line 145 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544#-Kgo5IQDM81SzipbnlRK:-KgonnNDLhCF1MlEPmMU:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4ae559b55ff9b98074b48f5b3d5882dd585f27/pkg/server/status/recorder.go#L145)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We use lowercase-with-hyphens for other metric names.
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/status/recorder.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544#-Kgo5LftPPCaKqGFpDpq:-Kgp9tzsxH4dOGBgkq66:bnlo0xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4ae559b55ff9b98074b48f5b3d5882dd585f27/pkg/server/status/recorder.go#L50)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

In their documentation they seem to use lowercase with underscores, so I changed these to follow that pattern.
</blockquote></details>

We rewrite label and metric names for prometheus export. See `util/metric.exportedLabel`. Perhaps these keys should use hyphens to match our metric names. @mberhault?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544)*

**Comment by mberhault** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/status/recorder.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544#-Kgo5LftPPCaKqGFpDpq:-Kgt3pHbeIxvYG8kPuDS:boklvik) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4ae559b55ff9b98074b48f5b3d5882dd585f27/pkg/server/status/recorder.go#L50)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We rewrite label and metric names for prometheus export. See `util/metric.exportedLabel`. Perhaps these keys should use hyphens to match our metric names. @mberhault?
</blockquote></details>

the metric name and label regexps are the following:
```
names: [a-zA-Z_:][a-zA-Z0-9_:]
labels: [a-zA-Z_][a-zA-Z0-9_]
```
everything else gets replaced by an underscore.
We already use underscores in label names (eg: `build_timestamp{tag="428c862",go_version="go1.8"}`)  and we've so far avoided uppercase.

I would suggest the following:
```
Name: node-id
advertiseAddrLabelKey: advertise-addr
httpAddrLabelKey: http-addr
```

this will turn into: `node_id{advertise_address="foo:26257",http_address="bar:8080"}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544)*

**Comment by spencerkimball** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/status/recorder.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544#-Kgo5LftPPCaKqGFpDpq:-KgtGb2e614xLWWyX9r5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4ae559b55ff9b98074b48f5b3d5882dd585f27/pkg/server/status/recorder.go#L50)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

the metric name and label regexps are the following:
```
names: [a-zA-Z_:][a-zA-Z0-9_:]
labels: [a-zA-Z_][a-zA-Z0-9_]
```
everything else gets replaced by an underscore.
We already use underscores in label names (eg: `build_timestamp{tag="428c862",go_version="go1.8"}`)  and we've so far avoided uppercase.

I would suggest the following:
```
Name: node-id
advertiseAddrLabelKey: advertise-addr
httpAddrLabelKey: http-addr
```

this will turn into: `node_id{advertise_address="foo:26257",http_address="bar:8080"}`

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14544)*

**Comment by spencerkimball** [comment]
Someone please LGTM

**Comment by mberhault** [comment]
LGTM. Can you check `/_status/vars` just to make sure it's behaving as expected?

**Comment by spencerkimball** [comment]
I did of course!

**Pull request merged**
