### PR TITLE
changefeedccl: delete dead code in `*changeFrontier.forwardFrontier`

### PR DESCRIPTION
**Pull request by andyyang890**
Epic: None

Release note: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
Maybe it is obvious, but could we add some commentary on how this is dead code because it doesn't look dead to me? `checkpointed` and `frontierChanged` aren't necessarily the same.

**Comment by andyyang890** [comment]
> Maybe it is obvious, but could we add some commentary on how this is dead code because it doesn't look dead to me? `checkpointed` and `frontierChanged` aren't necessarily the same.

It looks to me that the `emitResolved` variable is first assigned to `frontierChanged` but this value is never read before `emitResolved` is reassigned to `checkpointed`. I don't believe there are any other side effects from this assignment, but maybe I'm wrong?

**Comment by stevendanna** [comment]
🤦 I'll blame pre-coffee review. Completely just missed that re-assignment. Sorry for the noise.

**Review by wenyihu6 — APPROVED** [review]

**Review by rharding6373 — APPROVED** [review]
:lgtm: Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125887#-:-O-qMNtSChBlJPTPETJ0:b-g2a5fb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by andyyang890** [comment]
TFTRs!

bors r=wenyihu6,rharding6373

**Pull request merged**
