### PR TITLE
storage/engine: improve MVCCScan

### PR DESCRIPTION
**Pull request by benesch**
See commits for details. The primary goal was to make these code paths understandable enough that we can realize the perf gains from #31909. I accidentally knocked out #32239 in the process.

Note that the perf gains are currently somewhat offset by returning a struct instead of separate values (see this commit: https://github.com/cockroachdb/cockroach/commit/952bbc0ea3dadad544574d72ea87e2ceee640a94). Still trying to figure out why that has such a performance hit.

### CODE REVIEW

**Comment by benesch** [comment]
I backed out the bit where I returned a struct from rocksDBIterator.MVCCScan, since that caused a performance hit of a few percentage points on single-key scans. The new numbers are positive for large scans and in the noise for small scans:

```
name                                                  old time/op    new time/op    delta
MVCCScan_RocksDB/rows=10000/versions=1/valueSize=8-8    2.14ms ± 3%    2.00ms ± 1%  -6.48%  (p=0.000 n=9+9)

name                                                  old speed      new speed      delta
MVCCScan_RocksDB/rows=10000/versions=1/valueSize=8-8  37.4MB/s ± 3%  40.0MB/s ± 1%  +6.92%  (p=0.000 n=9+9)

name                                                  old alloc/op   new alloc/op   delta
MVCCScan_RocksDB/rows=10000/versions=1/valueSize=8-8    1.04MB ± 0%    1.04MB ± 0%    ~     (p=0.955 n=10+10)

name                                                  old allocs/op  new allocs/op  delta
MVCCScan_RocksDB/rows=10000/versions=1/valueSize=8-8      3.00 ± 0%      3.00 ± 0%    ~     (all equal)


name                                              old time/op    new time/op    delta
MVCCScan_RocksDB/rows=1/versions=1/valueSize=8-8    5.60µs ± 3%    5.73µs ± 4%    ~     (p=0.053 n=9+10)

name                                              old speed      new speed      delta
MVCCScan_RocksDB/rows=1/versions=1/valueSize=8-8  1.43MB/s ± 3%  1.39MB/s ± 4%  -2.52%  (p=0.029 n=9+10)

name                                              old alloc/op   new alloc/op   delta
MVCCScan_RocksDB/rows=1/versions=1/valueSize=8-8      117B ± 0%      117B ± 0%    ~     (all equal)

name                                              old allocs/op  new allocs/op  delta
MVCCScan_RocksDB/rows=1/versions=1/valueSize=8-8      2.00 ± 0%      2.00 ± 0%    ~     (all equal)
```

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, 6 of 6 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32298)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/mvcc.h, line 56 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/32298#-LRIwscF3M6F5ovxFNwx:-LRIwscF3M6F5ovxFNwy:b-urbaij) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46fd108f7fdc577688829de30189afba1d37b01/c-deps/libroach/mvcc.h#L56)):*
> ```objc
>       : iter_(iter),
>         iter_rep_(iter->rep.get()),
>         start_key_(ToSlice(start)),
> ```

Do we even need these anymore, now that we're relying on the iterator's bounds?
___
*[pkg/storage/engine/rocksdb.go, line 2307 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32298#-LRIx2M79JyNSX07QKL1:-LRIx2M79JyNSX07QKL2:buh1ulz) ([raw file](https://github.com/cockroachdb/cockroach/blob/20892c1b67f22b5624c76473cae3f4766230e31d/pkg/storage/engine/rocksdb.go#L2307)):*
> ```Go
> 		return nil, 0, nil, nil, emptyKeyError()
> 	}
> 	if max == 0 {
> ```

I know you just copied this, but it seems like the semantics here are subtly wrong, or at least inconsistent. Usually, the resume key corresponds to the _next_ key in the scan bounds. Here, we haven't found the next key. That's probably fine, but it might be worth mentioning in a comment or something. I'd hate for someone to rely on that property.

**Review by petermattis — APPROVED** [review]
:lgtm: This is a nice series of cleanups. 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, 6 of 6 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32298#-:-LRJ-aq6EyrSFy66mUuD:b5vkrnm)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32298)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[c-deps/libroach/mvcc.h, line 56 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/32298#-LRIwscF3M6F5ovxFNwx:-LRJ1qKY45e8b0ft6lcG:b-3iuy02) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46fd108f7fdc577688829de30189afba1d37b01/c-deps/libroach/mvcc.h#L56)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we even need these anymore, now that we're relying on the iterator's bounds?
</blockquote></details>

We don't need the end key, but we still need the start key in order to be able to seek to the right place. I have a plan to remove this but it might slow things down so I think it deserves its own PR.
___
*[pkg/storage/engine/rocksdb.go, line 2307 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32298#-LRIx2M79JyNSX07QKL1:-LRJ0n9S4FqImQdrCkT9:b-4kj0uy) ([raw file](https://github.com/cockroachdb/cockroach/blob/20892c1b67f22b5624c76473cae3f4766230e31d/pkg/storage/engine/rocksdb.go#L2307)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I know you just copied this, but it seems like the semantics here are subtly wrong, or at least inconsistent. Usually, the resume key corresponds to the _next_ key in the scan bounds. Here, we haven't found the next key. That's probably fine, but it might be worth mentioning in a comment or something. I'd hate for someone to rely on that property.
</blockquote></details>

Yeah, agreed, it's weird. I don't understand why scanning or deleting zero keys would ever be a useful thing to do.

Mind if I file an issue and leave to another PR? I'm trying to avoid any behavioral changes in this PR since it's already kinda sizable.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32298#-:-LRK70h-76JZrSmbbabO:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[c-deps/libroach/mvcc.h, line 56 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/32298#-LRIwscF3M6F5ovxFNwx:-LRK719m5ZqDd4N0Ep0q:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46fd108f7fdc577688829de30189afba1d37b01/c-deps/libroach/mvcc.h#L56)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

We don't need the end key, but we still need the start key in order to be able to seek to the right place. I have a plan to remove this but it might slow things down so I think it deserves its own PR.
</blockquote></details>

:thumbsup: 
___
*[pkg/storage/engine/rocksdb.go, line 2307 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32298#-LRIx2M79JyNSX07QKL1:-LRK737JAIkPVLdkYZ0v:b-duehwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/20892c1b67f22b5624c76473cae3f4766230e31d/pkg/storage/engine/rocksdb.go#L2307)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, agreed, it's weird. I don't understand why scanning or deleting zero keys would ever be a useful thing to do.

Mind if I file an issue and leave to another PR? I'm trying to avoid any behavioral changes in this PR since it's already kinda sizable.
</blockquote></details>

No need to even do that, but perhaps leave a comment?

**Comment by benesch** [comment]
bors r=petermattis,nvanbenschoten

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32298)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/storage/engine/rocksdb.go, line 2307 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32298#-LRIx2M79JyNSX07QKL1:-LRKpuOm0vvAUTAqK38D:b-xlu3od) ([raw file](https://github.com/cockroachdb/cockroach/blob/20892c1b67f22b5624c76473cae3f4766230e31d/pkg/storage/engine/rocksdb.go#L2307)):*
I opened a separate PR to improve the commentary here generally: https://github.com/cockroachdb/cockroach/pull/32376

I'm not actually sure that there's anything wrong here, now that I've dug in. Here's what the function doc has to say:

> If it hits max, it returns a "resume span" to be used in the next call to this function. If the limit is not hit, the resume span will be nil. Otherwise, it will be the sub-span of [key, endKey) that has not been scanned.

I don't think that's incompatible with the current behavior. If you specify a limit of 0, the entire scan region has not been scanned, so that's what we give you back.

**Pull request merged**
