### PR TITLE
changefeedccl: add full support for the parquet format

### LINKED ISSUE #99028: cdc: add new parquet library
This issue tracks progress for adding the apache arrow parquet library and integrating it into changefeeds.

https://github.com/apache/arrow/

I'll be working on the following items roughly in order
- Install dependency (coded ✅  merged ⛔)
- Create writer library  (coded ✅ merged ⛔)
- Add support for tpcc types  (coded ✅ merged ⛔)
- Integrate writer with cdc  (coded ⛔ merged ⛔)
- Benchmark parquet with tpcc roachtest  (results ⛔)
- Implement reader library and tests for tpcc types (coded ⛔ merged ⛔)
- Update relevant cdc tests (coded ⛔ merged ⛔)
- Add support for all types (coded ⛔ merged ⛔)

### LINKED ISSUE #103129: changefeedccl: remove limitations for parquet format
https://github.com/cockroachdb/cockroach/issues/99028 tracks all the steps required to add the apache arrow parquet library and remove the old one. This issue tracks changefeed options which are not supported by parquet (these are the same as the options not supported by initial scan)

- [x] updated https://github.com/cockroachdb/cockroach/pull/104407
- [x] mvcc_timestamp https://github.com/cockroachdb/cockroach/pull/104407
- [ ] diff
- [ ] key in value
- [ ] end_time
- [ ] topic in value
- [x] resolved https://github.com/cockroachdb/cockroach/pull/104283

Jira issue: CRDB-27845

### PR DESCRIPTION
**Pull request by jayshrivastava**
### changefeedccl: support key_in_value with parquet format

Previously, the option `key_in_value` was disallowed with
`format=parquet`. This change allows these settings to be
used together. Note that `key_in_value` is enabled by
default with `cloudstorage` sinks and `format=parquet` is
only allowed with cloudstorage sinks, so `key_in_value` is
enabled for parquet by default.

Informs: https://github.com/cockroachdb/cockroach/issues/103129
Informs: https://github.com/cockroachdb/cockroach/issues/99028
Epic: [CRDB-27372](https://cockroachlabs.atlassian.net/browse/CRDB-27372)
Release note: None

---

### changefeedccl: add test coverage for parquet event types

When using `format=parquet`, an additional column is produced to
indicate the type of operation corresponding to the row: create,
update, or delete. This change adds coverage for this in unit
testing.

Additionally, the test modified in this change is made more simple
by reducing the number of rows and different types because this
complexity is unnecessary as all types are tested within the
util/parquet package already.

Informs: https://github.com/cockroachdb/cockroach/issues/99028
Epic: [CRDB-27372](https://cockroachlabs.atlassian.net/browse/CRDB-27372)
Release note: None
Epic: None

---

### util/parquet: support tuple labels in util/parquet testutils

Previously, the test utilities in `util/parquet` would not reconstruct
tuples read from files with their labels. This change updates the
package to do so. This is required for testing in users of this
package such as CDC.

Informs: https://github.com/cockroachdb/cockroach/issues/99028
Epic: [CRDB-27372](https://cockroachlabs.atlassian.net/browse/CRDB-27372)
Release note: None

---

### changefeedccl: support diff option with parquet format

This change adds support for the `diff` changefeed
options when using `format=parquet`. Enabling `diff` also adds
support for CDC Transformations with parquet.

Informs: https://github.com/cockroachdb/cockroach/issues/103129
Informs: https://github.com/cockroachdb/cockroach/issues/99028
Epic: [CRDB-27372](https://cockroachlabs.atlassian.net/browse/CRDB-27372)
Release note: None

---

### changefeedccl: support end_time option with parquet format

This change adds support for the `end_time` changefeed
options when using `format=parquet`. No significant code
changes were needed to enable this feature.

Closes: https://github.com/cockroachdb/cockroach/issues/103129
Closes: https://github.com/cockroachdb/cockroach/issues/99028
Epic: [CRDB-27372](https://cockroachlabs.atlassian.net/browse/CRDB-27372)
Release note (enterprise change): Changefeeds now officially
support the parquet format at specificiation version 2.6.
It is only usable with the cloudstorage sink.

The syntax to use parquet is like the following:
`CREATE CHANGEFEED FOR foo INTO `...` WITH format=parquet`

It supports all standard changefeed options and features
including CDC transformations, except it does not support the
`topic_in_value` option.

---

### changefeedccl: use parquet with 50% probability in nemeses test

Informs: https://github.com/cockroachdb/cockroach/issues/99028
Epic: [CRDB-27372](https://cockroachlabs.atlassian.net/browse/CRDB-27372)
Release note: None

---

### do not merge: force parquet cloud storage tests

This change forces all tests, including tests for `diff` and `end_time`
to run with the `cloudstorage` sink and `format=parquet` where possible.

Informs: https://github.com/cockroachdb/cockroach/issues/103129
Informs: https://github.com/cockroachdb/cockroach/issues/99028
Epic: [CRDB-27372](https://cockroachlabs.atlassian.net/browse/CRDB-27372)
Release note: None

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, 2 of 5 files at r4, 1 of 1 files at r5, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104528)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/parquet.go` line 74 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104528#-NXRYW604aPJAzagjI7Z:-NXRYW604aPJAzagjI7_:b1iyadn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab7b696a996ae86ef3321f7b88a4a701bb9b4b5/pkg/ccl/changefeedccl/parquet.go#L74)):*
> ```Go
> const parquetOptUpdatedTimestampColName = metaSentinel + changefeedbase.OptUpdatedTimestamps
> const parquetOptMVCCTimestampColName = metaSentinel + changefeedbase.OptMVCCTimestamps
> const parquetOptDiffColName = metaSentinel + changefeedbase.OptDiff
> ```

should it be "prev" instead of diff? Or "_before" -- which is pretty standard name too?
___
*[`pkg/ccl/changefeedccl/parquet.go` line 174 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104528#-NXRYrg2DQ8M9RszpXjF:-NXRYrg2DQ8M9RszpXjG:b-mn2ylq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab7b696a996ae86ef3321f7b88a4a701bb9b4b5/pkg/ccl/changefeedccl/parquet.go#L174)):*
> ```Go
> 				return nil
> 			})
> 			valueBuilder, err := json.NewFixedKeysObjectBuilder(keys)
> ```

you definitely want to construct this value builder once.
___
*[`pkg/ccl/changefeedccl/parquet.go` line 180 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104528#-NXRZ0cpB2uGLG07REeA:-NXRZ0cpB2uGLG07REeB:blw6fd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab7b696a996ae86ef3321f7b88a4a701bb9b4b5/pkg/ccl/changefeedccl/parquet.go#L180)):*
> ```Go
> 
> 			if err := prevRow.ForEachColumn().Datum(func(d tree.Datum, col cdcevent.ResultColumn) error {
> 				j, err := tree.AsJSON(d, sessiondatapb.DataConversionConfig{}, time.UTC)
> ```

Why do we need to convert each datum to JSON? Couldn't we just valueBuilder.Set(col, d)?

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104528)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/parquet.go` line 74 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104528#-NXRYW604aPJAzagjI7Z:-NXpDRZM9nsM7euL6HB1:blznzvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab7b696a996ae86ef3321f7b88a4a701bb9b4b5/pkg/ccl/changefeedccl/parquet.go#L74)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should it be "prev" instead of diff? Or "_before" -- which is pretty standard name too?
</blockquote></details>

Renamed to "before".
___
*[`pkg/ccl/changefeedccl/parquet.go` line 174 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104528#-NXRYrg2DQ8M9RszpXjF:-NXpDUaO8kk8D-nn3jI9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab7b696a996ae86ef3321f7b88a4a701bb9b4b5/pkg/ccl/changefeedccl/parquet.go#L174)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

you definitely want to construct this value builder once.
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/parquet.go` line 180 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104528#-NXRZ0cpB2uGLG07REeA:-NXpD9o0B4Zn85nNTlZ2:b1c90az) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab7b696a996ae86ef3321f7b88a4a701bb9b4b5/pkg/ccl/changefeedccl/parquet.go#L180)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Why do we need to convert each datum to JSON? Couldn't we just valueBuilder.Set(col, d)?
</blockquote></details>

Looks like `tree.Datum` does not implement `json.JSON`. We do a similar thing in the JSON encoder https://github.com/cockroachdb/cockroach/blob/07101ad7c1c185f5a2e99d2000a70a303d614ef7/pkg/ccl/changefeedccl/encoder_json.go#L212-L216

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 6 files at r8, 1 of 1 files at r9, 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104528)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

**Comment by jayshrivastava** [comment]
bors r=miretskiy

**Pull request merged**
