### PR TITLE
kv: exempt tenant from KV-side limiting based on capability

### PR DESCRIPTION
**Pull request by stevendanna**
The KV-side rate limiting can, by design, substantially limit the performance of a tenant.  For UA clusters, we want the ability to designate a cluster exempt from the rate limiting.

Note that we still pass all requests through the limiter and keep statistics.

Epic: none

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-:-NPx2F2h8081z8f4i8I2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @knz, and @stevendanna)

___
*[`pkg/multitenant/tenantcapabilities/capabilities.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPx0ZzREFKHEZvwc6tl:-NPx0ZzREFKHEZvwc6tm:b-dcrsri) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3bbb84e596e8e72b3d05e78ebe1546627e7cc3/pkg/multitenant/tenantcapabilities/capabilities.go#L76)):*
> ```Go
> 	// IsNotRateLimited returns true of the tenant should not be subject to rate
> 	// limiting.
> 	IsNotRateLimited(ctx context.Context, tenID roachpb.TenantID) bool
> ```

[nit] I'd call this `IsExemptFromRateLimiting` or `IsRateLimitExempt` to avoid double negatives.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPx1Nh31sYaxuCm_bYu:-NPx1Nh31sYaxuCm_bYv:b1yeykh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3bbb84e596e8e72b3d05e78ebe1546627e7cc3/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.go#L68)):*
> ```Go
> 	// NotRateLimited, if set to true, exempts the tenant from the KV-side tenant
> 	// rate limiter.
> 	NotRateLimited // not_rate_limited
> ```

[nit] RateLimitExempt or ExemptFromRateLimiting

**Review by arulajmani — COMMENTED** [review]
Do we need to add some logic in `pkg/sql/tenant_capability.go` as well, so that we can grant/revoke this capability? Could we also add some logic tests that alter this capability as well?

> Reviewed 16 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-:-NPx5Ncq32TZMzKWeXWN:b69ql89)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @RaduBerinde, and @stevendanna)

___
*[`pkg/multitenant/tenantcapabilities/capabilities.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPx0ZzREFKHEZvwc6tl:-NPx5dzN9Q_-kn2klJM_:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3bbb84e596e8e72b3d05e78ebe1546627e7cc3/pkg/multitenant/tenantcapabilities/capabilities.go#L76)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd call this `IsExemptFromRateLimiting` or `IsRateLimitExempt` to avoid double negatives.
</blockquote></details>

+1
___
*[`pkg/sql/crdb_internal.go` line 7617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPx3YRK3jyZhg67m2eB:-NPx3YRK3jyZhg67m2eC:b2ztabk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3bbb84e596e8e72b3d05e78ebe1546627e7cc3/pkg/sql/crdb_internal.go#L7617)):*
> ```Go
> 				return err
> 			}
> 			if err := addRow(
> ```

Are there logic tests we need to add/update for this? 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/testdata/basic` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPx3j_w5zGbPYbq4sGb:-NPx3j_w5zGbPYbq4sGc:bnphk03) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3bbb84e596e8e72b3d05e78ebe1546627e7cc3/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/testdata/basic#L68)):*
> ```
> tenant 11 does not have capability to query timeseries data
> 
> upsert ten=11 not_rate_limited=true
> ```

nit: let's add a test for the default case as well? (e.g `is-not-rate-limited ten=10`)
___
*[`pkg/kv/kvserver/tenantrate/limiter_test.go` line 688 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPx4DeX7azUys8aEAU6:-NPx4DeX7azUys8aEAU7:b-kzulvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3bbb84e596e8e72b3d05e78ebe1546627e7cc3/pkg/kv/kvserver/tenantrate/limiter_test.go#L688)):*
> ```Go
> 
> func (ts *testState) IsNotRateLimited(_ context.Context, tenID roachpb.TenantID) bool {
> 	return ts.capabilities[tenID].CanViewTSDBMetrics
> ```

Should this be `IsNotRateLimited`?

**Review by stevendanna — COMMENTED** [review]
> Do we need to add some logic in pkg/sql/tenant_capability.go as well, so that we can grant/revoke this capability? Could we also add some logic tests that alter this capability as well?

Done. There might be a few more tests that need to be rewritten, we'll see what CI says.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-:-NPxHw7SEo86qDKnTbom:b-nxbz1z)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @knz, and @RaduBerinde)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPx1Nh31sYaxuCm_bYu:-NPxI4ig6I-0jwQ1782w:bo5rgn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3bbb84e596e8e72b3d05e78ebe1546627e7cc3/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.go#L68)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] RateLimitExempt or ExemptFromRateLimiting
</blockquote></details>

Another suggestion was Unmetered. But since the rest of the capabilities currently say exactly what they allow, I like ExemptFromRateLimiting. I'll do the rename once I've sorted through the test failures.
___
*[`pkg/sql/crdb_internal.go` line 7617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPx3YRK3jyZhg67m2eB:-NPxIJSV3sVo8Gu3P7uw:b70s3pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3bbb84e596e8e72b3d05e78ebe1546627e7cc3/pkg/sql/crdb_internal.go#L7617)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Are there logic tests we need to add/update for this? 
</blockquote></details>

:man_facepalming: Thanks forgot to git-add some files.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/testdata/basic` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPx3j_w5zGbPYbq4sGb:-NPxINj0Cm99ZuWdWXyG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3bbb84e596e8e72b3d05e78ebe1546627e7cc3/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/testdata/basic#L68)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: let's add a test for the default case as well? (e.g `is-not-rate-limited ten=10`)
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/tenantrate/limiter_test.go` line 688 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPx4DeX7azUys8aEAU6:-NPxIPfgCioyUpN7shma:boyexbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3bbb84e596e8e72b3d05e78ebe1546627e7cc3/pkg/kv/kvserver/tenantrate/limiter_test.go#L688)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this be `IsNotRateLimited`? 
</blockquote></details>

Done. Thanks.

**Review by knz — APPROVED** [review]
> Reviewed 13 of 18 files at r1, 10 of 11 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98148)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @RaduBerinde)

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 9 of 11 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-:-NPxX-VO3nUC-Cq9h9gI:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @stevendanna)

___
*[`pkg/kv/kvserver/tenantrate/limiter.go` line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPxWr_zBvt9XkWxalTs:-NPxWr_zBvt9XkWxalTt:b-15jceb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e300e208b22b889de8adce2308d8c0c712cddc6/pkg/kv/kvserver/tenantrate/limiter.go#L163)):*
> ```Go
> }
> 
> // Releaes cleans up resources reserved for this limiter.
> ```

nit: s/Releaes/Release/g
___
*[`pkg/kv/kvserver/tenantrate/limiter.go` line 169 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NPxWqgD1AUVUq88Dbyn:-NPxWqgD1AUVUq88Dbyo:by7uiwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e300e208b22b889de8adce2308d8c0c712cddc6/pkg/kv/kvserver/tenantrate/limiter.go#L169)):*
> ```Go
> }
> 
> // Releaes is part of the Limiter interface.
> ```

nit: stale comment?

**Comment by knz** [comment]
Given how much work @ecwall has already poured into #97469 I would like to give him the courtesy of not having to rebase that PR. Please rebase this one on top instead.

**Comment by stevendanna** [comment]
@knz Yup, will do!

**Review by benbardin — COMMENTED** [review]
Approved for backupccl

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-:-NQ16JueBDvrMBHZVvsW:bqjkhtb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @knz, @RaduBerinde, and @stevendanna)

**Comment by stevendanna** [comment]
I believe the test failure here is a flake: TestLogic_mixed_version_external_connections_owner_id. Will spend a few minutes digging in.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98148)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz, @RaduBerinde, and @stevendanna)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 195 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98148#-NQRNZE646Y-L7WfgO5y:-NQRNZE646Y-L7WfgO5z:b-6oe8ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/42b4ee6427a4facd9928972d059e9d33d86f2d9c/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L195)):*
> ```Go
> // IsExemptFromRateLimiting returns true if the tenant is not subject to rate limiting.
> func (a *Authorizer) IsExemptFromRateLimiting(ctx context.Context, tenID roachpb.TenantID) bool {
> 	if tenID.IsSystem() {
> ```

Now that https://github.com/cockroachdb/cockroach/pull/98274 has landed, should we replace this with `elideCapabilityChecks` method?

**Pull request merged**
