### PR TITLE
AUTHORS: misc adjustments

### PR DESCRIPTION
**Pull request by knz**
Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]

**Comment by knz** [comment]
Thanks!

bors r=jordanlewis

**Review by RichardJCai — APPROVED** [review]

**Comment by knz** [comment]
bors r=jordanlewis,RichardJCai

**Comment by knz** [comment]
bors r=jordanlewis,RichardJCai

**Comment by knz** [comment]
bors r=jordanlewis,RichardJCai

**Pull request merged**
