### PR TITLE
[workload] expose pprof http endpoints

### LINKED ISSUE #30810: workload: expose pprof http endpoints
`workload` should expose [pprof http endpoints](https://golang.org/pkg/net/http/pprof/) so that it can be debugged in a similar manner to the main CockroachDB process. This is important because performance problems can often be due to client-side issues, so when debugging performance degredations we'll want to confirm that `workload` is behaving correctly.

While doing so, we should make sure to:
- set the mutex profile fraction to have access to mutex profiles: [`runtime.SetMutexProfileFraction`](https://golang.org/pkg/runtime/#SetMutexProfileFraction)
- set the blocking profile fraction to have access to blocking profiles: [`runtime.SetBlockProfileRate`](https://golang.org/pkg/runtime/#SetBlockProfileRate)
- expose a flag to adjust the http server port so that it can be put on port 26258 by roachprod (or some other port that's whitelisted in GCE)

### PR DESCRIPTION
**Pull request by m-schneider**
closes: #30810

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
Thanks for getting this out so quickly! This looks like the right place to make the change, but I'll wait on @danhhz to weigh in.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-:-LNlKNPRCkcvmLugcDZp:b5bk6h1)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/cli/run.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-LNlKHE2BloT2I3T1IA4:-LNlKHE2BloT2I3T1IA5:b-o428nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee254ede9580bcd4f49726a6c921e68dc07f687/pkg/workload/cli/run.go#L254)):*
> ```Go
> 	ctx := context.Background()
> 
> 	b := envutil.EnvOrDefaultInt64("COCKROACH_BLOCK_PROFILE_RATE",
> ```

Let's pull this all out into a separate function. It might also be useful to call it from `runInit`.
___
*[pkg/workload/cli/run.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-LNlKJqT24MNPKRATxRf:-LNlKJqT24MNPKRATxRg:bpxth70) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee254ede9580bcd4f49726a6c921e68dc07f687/pkg/workload/cli/run.go#L262)):*
> ```Go
> 	runtime.SetMutexProfileFraction(int(m))
> 
> 	go http.ListenAndServe(":"+strconv.Itoa(*pprofport), nil)
> ```

I think the linter is going to yell at you because `http.ListenAndServe` returns an error. You'll probably need to handle that.

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30847)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/cli/run.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-LNlKHE2BloT2I3T1IA4:-LNlZESH8tMFdPFoz9KS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee254ede9580bcd4f49726a6c921e68dc07f687/pkg/workload/cli/run.go#L254)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's pull this all out into a separate function. It might also be useful to call it from `runInit`.
</blockquote></details>

Done.
___
*[pkg/workload/cli/run.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-LNlKJqT24MNPKRATxRf:-LNlZFzE3xgcftCSP51T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee254ede9580bcd4f49726a6c921e68dc07f687/pkg/workload/cli/run.go#L262)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think the linter is going to yell at you because `http.ListenAndServe` returns an error. You'll probably need to handle that.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm: but @danhhz should also take a look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-:-LNlaqqd-4iB4962syK_:b-hm0914)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/cli/run.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-LNlaoKr3_jJXB9FxrR2:-LNlaoKr3_jJXB9FxrR3:bwrx16v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a06f1f30469b8e20e4bcd8b593afbeeca3a1746a/pkg/workload/cli/run.go#L23)):*
> ```Go
> 	"encoding/json"
> 	"fmt"
> 	"github.com/cockroachdb/cockroach/pkg/util/envutil"
> ```

nit: these imports got messed up.

**Review by danhhz — COMMENTED** [review]
:lgtm: modulo the flag set stuff

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-:-LNpPYnc3preFm8VWH97:b-8bmbdg)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/cli/run.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-LNpPJBv3PsFlUstUmR-:-LNpPJBv3PsFlUstUmR0:b-x2rj79) ([raw file](https://github.com/cockroachdb/cockroach/blob/a06f1f30469b8e20e4bcd8b593afbeeca3a1746a/pkg/workload/cli/run.go#L57)):*
> ```Go
> var initFlags = pflag.NewFlagSet(`init`, pflag.ContinueOnError)
> var drop = initFlags.Bool("drop", false, "Drop the existing database, if it exists")
> var pprofport = initFlags.Int("pprofport", 26258, "Port for pprof endpoint.")
> ```

I don't think initFlags is what you want here. those get special treatment when included in `workload run`. probably best to make a third flag set that's shared by both init and run
___
*[pkg/workload/cli/run.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-LNpPEV9405ifaTs8Rmj:-LNpPEVA50JaI6-ZueLG:b-4tnx5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a06f1f30469b8e20e4bcd8b593afbeeca3a1746a/pkg/workload/cli/run.go#L252)):*
> ```Go
> }
> 
> func initPProfEndPoint(ctx context.Context) {
> ```

nit: init already means something else in this file. how about start?

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30847)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/workload/cli/run.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-LNpPJBv3PsFlUstUmR-:-LNqDOvm4DYi07xDHu5Q:b-imacg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a06f1f30469b8e20e4bcd8b593afbeeca3a1746a/pkg/workload/cli/run.go#L57)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I don't think initFlags is what you want here. those get special treatment when included in `workload run`. probably best to make a third flag set that's shared by both init and run
</blockquote></details>

Added another flagset.
___
*[pkg/workload/cli/run.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30847#-LNpPEV9405ifaTs8Rmj:-LNqDMPu1WCFmyQn9hpp:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/a06f1f30469b8e20e4bcd8b593afbeeca3a1746a/pkg/workload/cli/run.go#L252)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: init already means something else in this file. how about start?
</blockquote></details>

Done!

**Comment by m-schneider** [comment]
Actually before I merge, I'm just wondering if it makes sense to use port 26258 as the default? It won't be able to bind it if there's a cockroach instance running on the same machine.

**Comment by petermattis** [comment]
> Good point. Let's use 26259 instead.

FYI, `roachprod local` uses the ports 26257, 26258, 26259, etc. I'd recommend using something completely different, like 33333.

**Comment by m-schneider** [comment]
> 33333
Changed to the example.

**Pull request merged**
