### PR TITLE
sql: add syntax for experimental domiciling

### PR DESCRIPTION
**Pull request by pawalt**
This commit adds the PLACEMENT [RESTRICTED | DEFAULT] flag to CREATE
DATABASE and adds the ALTER DATABASE PLACEMENT statement. These will
be used to support #59756.

Release note: None

This PR was split out from #67946.

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @pawalt)

___
*[pkg/sql/parser/sql.y, line 8398 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYnt4_6IJeXROGHsmL:-MfYnt4_6IJeXROGHsmM:b-8tjlxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/parser/sql.y#L8398)):*
> ```Yacc
> | /* EMPTY */
>   {
>     $$.val = tree.DataPlacementUnspecified
> ```

Could we just make this `tree.DataPlacementDefault`? Having a separate `Unspecified` type doesn't add much, does it?
___
*[pkg/sql/parser/testdata/create_database, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYpIAY524BAxMERwYW:-MfYpIAY524BAxMERwYX:bbtakqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/parser/testdata/create_database#L350)):*
> ```
> CREATE DATABASE IF NOT EXISTS _ PRIMARY REGION _ -- identifiers removed
> 
> error
> ```

Let's add some parser tests here too?  

Also, in the `alter_database` file as well.
___
*[pkg/sql/sem/tree/data_placement.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYoEgiEsmjitlHeGVu:-MfYoEgiEsmjitlHeGVv:b-cetgfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/sem/tree/data_placement.go#L27)):*
> ```Go
> 	case DataPlacementDefault:
> 		ctx.WriteString("PLACEMENT DEFAULT")
> 	default:
> ```

You're missing a case for `DtaPlacementUnspecified`, but I think we should just get rid of it altogether.

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/parser/sql.y, line 8398 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYnt4_6IJeXROGHsmL:-MfZ1HE-9Lh9smNFyim2:br04ckj) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/parser/sql.y#L8398)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could we just make this `tree.DataPlacementDefault`? Having a separate `Unspecified` type doesn't add much, does it?
</blockquote></details>

I did this the same way survival goals are implemented; having an unspecified type lets us know if the user tried to use `PLACEMENT` on a database that isn't multi-region. The naming is a bit weird because survival goals can use `SurvivalGoalDefault` but here `DataPlacementDefault` would be ambiguous, but it's the same effect.
___
*[pkg/sql/parser/testdata/create_database, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYpIAY524BAxMERwYW:-MfZ3-P6E9AuUqQ_1n6l:bofbi3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/parser/testdata/create_database#L350)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's add some parser tests here too?  

Also, in the `alter_database` file as well.
</blockquote></details>

Added the create tests. I can't add the alter tests yet as it throws unimplemented errors. I'll add alter tests in the PR that stitches the syntax together with the logic.
___
*[pkg/sql/sem/tree/data_placement.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYoEgiEsmjitlHeGVu:-MfZ293K8c033dpACqMc:bga3qf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/sem/tree/data_placement.go#L27)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

You're missing a case for `DtaPlacementUnspecified`, but I think we should just get rid of it altogether. 
</blockquote></details>

Added a section for unspecifed pending talk about using it.

**Review by arulajmani — COMMENTED** [review]
I'd encourage you to add support for parsing for `ALTER DATABASE` in this PR as well, but if you'd rather do it in a followup that's fine too. Looks like a few tests need a re-write, but other than that this PR looks good to me. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-:-MfZRGQt31O2MGYTV6nW:bvk778p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @otan, and @pawalt)

___
*[pkg/sql/parser/sql.y, line 8398 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYnt4_6IJeXROGHsmL:-MfZQH09-UQApRbMKZKt:b-hm1yuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/parser/sql.y#L8398)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I did this the same way survival goals are implemented; having an unspecified type lets us know if the user tried to use `PLACEMENT` on a database that isn't multi-region. The naming is a bit weird because survival goals can use `SurvivalGoalDefault` but here `DataPlacementDefault` would be ambiguous, but it's the same effect.
</blockquote></details>

That makes sense, didn't realize we actually needed it late. 
___
*[pkg/sql/parser/testdata/create_database, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYpIAY524BAxMERwYW:-MfZQwEZD9CoQnPKM5Xl:b6dhwny) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/parser/testdata/create_database#L350)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Added the create tests. I can't add the alter tests yet as it throws unimplemented errors. I'll add alter tests in the PR that stitches the syntax together with the logic.
</blockquote></details>

Is it worth tackling both the parsing of `ALTER DATABASE` and `CREATE DATABASE` in this PR? Or would you rather do the `ALTER` in a separate one?

**Review by otan — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @pawalt)

___
*[pkg/sql/parser/sql.y, line 1657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfZS1HnAxCGClbMhXpL:-MfZS1Ho-D2QUcJ5PuJF:b-9lbi1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/af6652cefec22196c384fb5dadb660f3ec1c9bd8/pkg/sql/parser/sql.y#L1657)):*
> ```Yacc
>   }
> 
> alter_database_placement_stmt:
> ```

add `/* SKIP DOC */` here to hide it.
___
*[pkg/sql/sem/tree/create.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfZSwlQBj_2l3OgzV6D:-MfZSwlQBj_2l3OgzV6E:b-n0c60d) ([raw file](https://github.com/cockroachdb/cockroach/blob/af6652cefec22196c384fb5dadb660f3ec1c9bd8/pkg/sql/sem/tree/create.go#L117)):*
> ```Go
> 	// Only want to print if the user has turned on restricted so that
> 	// SHOW CREATE DATABASE doesn't expose PLACEMENT.
> 	if node.Placement == DataPlacementRestricted {
> ```

should this be `!= DataPlacementDefault`
___
*[pkg/sql/sem/tree/data_placement.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYoEgiEsmjitlHeGVu:-MfZT2oo1c2Yk1u0NIx2:b4hqxok) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/sem/tree/data_placement.go#L27)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Added a section for unspecifed pending talk about using it.
</blockquote></details>

unspecified should just return early and not print imo.

**Comment by otan** [comment]
___
*[pkg/sql/sem/tree/create.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfZSwlQBj_2l3OgzV6D:-Mf_FIw1BGoDxyJqY0w_:bufg004) ([raw file](https://github.com/cockroachdb/cockroach/blob/af6652cefec22196c384fb5dadb660f3ec1c9bd8/pkg/sql/sem/tree/create.go#L117)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

should this be `!= DataPlacementDefault`
</blockquote></details>

oops, `!= DataPlacementUnspecified`

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/parser/sql.y, line 8398 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYnt4_6IJeXROGHsmL:-MfZi2HP2o1NYyJA_T9M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/parser/sql.y#L8398)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

That makes sense, didn't realize we actually needed it late. 
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 1657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfZS1HnAxCGClbMhXpL:-MfZiHAREkE-o17IIdNf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af6652cefec22196c384fb5dadb660f3ec1c9bd8/pkg/sql/parser/sql.y#L1657)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

add `/* SKIP DOC */` here to hide it.
</blockquote></details>

Done.
___
*[pkg/sql/parser/testdata/create_database, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYpIAY524BAxMERwYW:-MfcGTBB-Q61WIFjNyF4:b-6viey0) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/parser/testdata/create_database#L350)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is it worth tackling both the parsing of `ALTER DATABASE` and `CREATE DATABASE` in this PR? Or would you rather do the `ALTER` in a separate one? 
</blockquote></details>

Makes sense to do both here. I had it in my head that if I created a `tree.AlterDatabasePlacement`, I'd have to fill in the `alterDatabasePlacementNode` and implementation, but realize that I can just parse now.
___
*[pkg/sql/sem/tree/create.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfZSwlQBj_2l3OgzV6D:-MfcC6WM2vgxMGEBSSd3:b-kz25em) ([raw file](https://github.com/cockroachdb/cockroach/blob/af6652cefec22196c384fb5dadb660f3ec1c9bd8/pkg/sql/sem/tree/create.go#L117)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

oops, `!= DataPlacementUnspecified`
</blockquote></details>

I don't think so because if we want to use the formatting from `tree` to generate `SHOW CREATE DATABASE`, we don't know if the placement policy we're reading off the table descriptor is "manually-input default" or "unspecified default". Since we don't want to expose PLACEMENT unless we're sure the user knows about it, we only want to write out PLACEMENT if we're in restricted mode.
___
*[pkg/sql/sem/tree/data_placement.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfYoEgiEsmjitlHeGVu:-MfcByF43JKAGrZdzSpD:b-hq78dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3f985a44fb63a4df28deab8a1d6306a42c75f5/pkg/sql/sem/tree/data_placement.go#L27)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

unspecified should just return early and not print imo.
</blockquote></details>

Yeah just made another case for it.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-:-MfckkmW7iWxhjaoeHVZ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/sem/tree/create.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfZSwlQBj_2l3OgzV6D:-MfcjeoV-6bSjR8YbPKW:b-1cqyrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/af6652cefec22196c384fb5dadb660f3ec1c9bd8/pkg/sql/sem/tree/create.go#L117)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I don't think so because if we want to use the formatting from `tree` to generate `SHOW CREATE DATABASE`, we don't know if the placement policy we're reading off the table descriptor is "manually-input default" or "unspecified default". Since we don't want to expose PLACEMENT unless we're sure the user knows about it, we only want to write out PLACEMENT if we're in restricted mode.
</blockquote></details>

I think in general we expand out things that would "have the same effect". For example, even if the Survival Goal wasn't explicitly set to "Zone", we'd expand it out to say so. 

That being said, if we want to hide this feature as much as possible from our users, I think the conditional as is is fine.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @arulajmani, @otan, and @pawalt)

___
*[pkg/sql/parser/sql.y, line 1668 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfeAVcB6fPXjZzbrS1J:-MfeAVcB6fPXjZzbrS1K:b-bel853) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c6bedb8745b24a1d16688babb309eb1d3282cc/pkg/sql/parser/sql.y#L1668)):*
> ```Yacc
> 
> /* SKIP DOC */
> alter_database_placement_stmt:
> ```

it's still showing up in the documentation. i think it has to be after the line.
___
*[pkg/sql/parser/sql.y, line 8431 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfeAkqf4cDSh6o5jzV7:-MfeAkqf4cDSh6o5jzV8:bsl5d2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c6bedb8745b24a1d16688babb309eb1d3282cc/pkg/sql/parser/sql.y#L8431)):*
> ```Yacc
>   }
> 
> opt_placement_clause:
> ```

we should place a SKIP DOC here too to hide it from appearing in documentation
___
*[pkg/sql/sem/tree/create.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfZSwlQBj_2l3OgzV6D:-MfeAu8a0KEuyU9Q2bc9:bbo7inp) ([raw file](https://github.com/cockroachdb/cockroach/blob/af6652cefec22196c384fb5dadb660f3ec1c9bd8/pkg/sql/sem/tree/create.go#L117)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think in general we expand out things that would "have the same effect". For example, even if the Survival Goal wasn't explicitly set to "Zone", we'd expand it out to say so. 

That being said, if we want to hide this feature as much as possible from our users, I think the conditional as is is fine. 
</blockquote></details>

i'd rather hide it if the user did not specify it on the AST. This is what we did for survive (which is why we have unspecified in the first place).

**Comment by otan** [comment]
___
*[pkg/sql/sem/tree/create.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfZSwlQBj_2l3OgzV6D:-MfeB6hQ7vp6kaStc_K5:b-dhti07) ([raw file](https://github.com/cockroachdb/cockroach/blob/af6652cefec22196c384fb5dadb660f3ec1c9bd8/pkg/sql/sem/tree/create.go#L117)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i'd rather hide it if the user did not specify it on the AST. This is what we did for survive (which is why we have unspecified in the first place).
</blockquote></details>

If we're not showing PLACEMENT DEFAULT if the user specifies it (which I am not advocating for), we should get rid of DataPlacementUnspecified.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @otan, and @pawalt)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2287 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-Mfh8cFK3Sfqe6pvDSGj:-Mfh8cFK3Sfqe6pvDSGk:bf9ihjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c6bedb8745b24a1d16688babb309eb1d3282cc/docs/generated/sql/bnf/stmt_block.bnf#L2287)):*
> ```
> placement_clause ::=
> 	'PLACEMENT' 'RESTRICTED'
> 	| 'PLACEMENT' 'DEFAULT'
> ```

See my comment on the other PR.  I'm wondering if we should move away from using DEFAULT here.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @otan, and @pawalt)

___
*[pkg/sql/sem/tree/create.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfZSwlQBj_2l3OgzV6D:-MfhHnzDBebQOMjnjSau:b-58six8) ([raw file](https://github.com/cockroachdb/cockroach/blob/af6652cefec22196c384fb5dadb660f3ec1c9bd8/pkg/sql/sem/tree/create.go#L117)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

If we're not showing PLACEMENT DEFAULT if the user specifies it (which I am not advocating for), we should get rid of DataPlacementUnspecified.
</blockquote></details>

I thought we needed unspecified for survive because we need the distinction between unspecified and default in CREATE DATABASE here: https://github.com/cockroachdb/cockroach/blob/0388efe861e1824a0130a1b1c3cc2efddec07586/pkg/sql/create_database.go#L89. We'll want something similar for this `PLACEMENT` syntax, right?

Regardless, I don't have strong opinions here. If we care about `SHOW CREATE DATABASE` not expanding placement in the default case we can do it in other ways as well.

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @arulajmani, and @otan)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2287 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-Mfh8cFK3Sfqe6pvDSGj:-MfhTah_-xJnRbpuBzXX:bqgpoex) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c6bedb8745b24a1d16688babb309eb1d3282cc/docs/generated/sql/bnf/stmt_block.bnf#L2287)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

See my comment on the other PR.  I'm wondering if we should move away from using DEFAULT here.
</blockquote></details>

I don't have strong opinions on it, but I don't think DEFAULT that confusing, especially if PLACEMENT is a feature hidden behind a cluster setting. EVERYWHERE/ALL_REGIONS seems ambiguous (everywhere in db or everywhere in cluster?).

This is very subjective, though, so if people feel strongly about this and we can find syntax that means "every database region", I'm happy to change.
___
*[pkg/sql/parser/sql.y, line 1668 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfeAVcB6fPXjZzbrS1J:-MfhT17L8_5VAtmXLrzg:b-y208nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c6bedb8745b24a1d16688babb309eb1d3282cc/pkg/sql/parser/sql.y#L1668)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it's still showing up in the documentation. i think it has to be after the line.
</blockquote></details>

I think it worked this time.
___
*[pkg/sql/parser/sql.y, line 8431 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfeAkqf4cDSh6o5jzV7:-MfhT0me96v1HsrET_0W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c6bedb8745b24a1d16688babb309eb1d3282cc/pkg/sql/parser/sql.y#L8431)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

we should place a SKIP DOC here too to hide it from appearing in documentation
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/create.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-MfZSwlQBj_2l3OgzV6D:-MfhRN6DAmaIVSgrZWEp:b-7a483q) ([raw file](https://github.com/cockroachdb/cockroach/blob/af6652cefec22196c384fb5dadb660f3ec1c9bd8/pkg/sql/sem/tree/create.go#L117)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I thought we needed unspecified for survive because we need the distinction between unspecified and default in CREATE DATABASE here: https://github.com/cockroachdb/cockroach/blob/0388efe861e1824a0130a1b1c3cc2efddec07586/pkg/sql/create_database.go#L89. We'll want something similar for this `PLACEMENT` syntax, right?

Regardless, I don't have strong opinions here. If we care about `SHOW CREATE DATABASE` not expanding placement in the default case we can do it in other ways as well. 
</blockquote></details>

Yep we need unspecified for checking "was PLACEMENT used with no primary region" and "was PLACEMENT used with the cluster setting not set".

I've made the modification to print on either DEFAULT or RESRICTED, and I've got another path I can go down to make sure we don't expose PLACEMENT on SHOW CREATE DATABASE.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @otan, and @pawalt)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2287 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-Mfh8cFK3Sfqe6pvDSGj:-MfhXt4EBVL0bq2xte4Z:b-apm7yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c6bedb8745b24a1d16688babb309eb1d3282cc/docs/generated/sql/bnf/stmt_block.bnf#L2287)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I don't have strong opinions on it, but I don't think DEFAULT that confusing, especially if PLACEMENT is a feature hidden behind a cluster setting. EVERYWHERE/ALL_REGIONS seems ambiguous (everywhere in db or everywhere in cluster?).

This is very subjective, though, so if people feel strongly about this and we can find syntax that means "every database region", I'm happy to change.
</blockquote></details>

I agree with you that the hiddenness helps with the risk.  My main concern is that if we want to change the "default" behaviour at some point, DEFAULT becomes a bit problematic.

I do agree with you on the ambiguity of the options I suggested.  What about something super descriptive like REPLICAS_IN_ALL_REGIONS?  It does leave RESTRICTED as feeling a bit underdescribed though.  TBH, I don't have a good solution here, but DEFAULT leaves me a bit uneasy.

**Review by arulajmani — APPROVED** [review]
Talked offline, the use of "DEFAULT" in this context is probably not right but we can (and will) come back to change the exact syntax later. For now, to unblock the other PRs on top of it, let's merge this in as is. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68068#-:-Mfig3G6EAERzhVUs9WY:b-ewkcxb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @otan, and @pawalt)

**Review by otan — APPROVED** [review]

**Comment by pawalt** [comment]
bors r=otan,arulajmani

**Pull request merged**
