### PR TITLE
roachtest: skip initialization on failure restarts

### PR DESCRIPTION
**Pull request by andrewbaptist**
Previously a node restart in the failover code would pass SkipInit = false. This resulted in re-issuing grants which cause a schema change. By passing SkipInit this code is bypassed.

Informs: #119347

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
Thanks, we should do the same in `runFailoverLiveness`, `runFailoverNonSystem`, and `runFailoverSystemNonLiveness`. We could consider moving this into `makeFailer()` and simply adjust the given options.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119655#-:-Ns9NMK1CYj1EwFJK-ln:b8jx04a)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @srosenberg)

**Comment by andrewbaptist** [comment]
We don't strictly need this change, however it helps speed up the restart process after the failures. Rather than trying to thread this through all the places in this file since all the start and restart options are the same, I just created two utility methods for the start and restart options. This will also help reduce any errors from additional tests that are created.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119655)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 1756 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119655#-NvIkzO78MLv8Hw710Nk:-NvIkzO78MLv8Hw710Nl:bvsz6uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c21c562c61cc8e5b862d28fb42ac2a640095d7/pkg/cmd/roachtest/tests/failover.go#L1756)):*
> ```Go
> }
> 
> func startOps() option.StartOpts {
> ```

The functions have fairly general names and are in the namespace of `pkg/cmd/roachtest/tests`, which includes 100s of other tests. Should we give them more specific names? Something like `failoverStartOpts` and `failoverRestartOpts`?

Also, notice `s/ops/opts/` to match `option.StartOpts`.

**Review by andrewbaptist — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119655)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @nvanbenschoten, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 1756 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119655#-NvIkzO78MLv8Hw710Nk:-NvImZPr-Z_RrFPQ4SI2:bolej8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c21c562c61cc8e5b862d28fb42ac2a640095d7/pkg/cmd/roachtest/tests/failover.go#L1756)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The functions have fairly general names and are in the namespace of `pkg/cmd/roachtest/tests`, which includes 100s of other tests. Should we give them more specific names? Something like `failoverStartOpts` and `failoverRestartOpts`?

Also, notice `s/ops/opts/` to match `option.StartOpts`.
</blockquote></details>

Good catch on the naming. Updated!

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119655#-:-NvJ3PKA87JglCf2WYit:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong and @srosenberg)

**Comment by andrewbaptist** [comment]
bors r=nvanbenschoten 

TFTR!

**Comment by nvanbenschoten** [comment]
blathers backport 23.2

**Pull request merged**
