### PR TITLE
kvserver,roachpb,storage: add IsSpanEmptyRequest to check for any data

### LINKED ISSUE #85726: kv: add command to check whether a span is empty
**Is your feature request related to a problem? Please describe.**
Issue https://github.com/cockroachdb/cockroach/issues/70427 asks that the GC job wait until the data in the relevant spans has been GC'd by the MVCC GC queue before removing the descriptor and zone configs for that table. In the case where a range contains multiple tables, or in the case where a GC job is removing data from an index, it's not clear how to check whether GC has occurred. If we were to wait on a GC threshold, we might be waiting forever, or not long enough. 

One approach might be to use an `ExportRequest` and wait until that comes back empty. Sadly, the `ExportRequest` has no way to return zero bytes while indicating whether data exists (the `ScanRequest` does have such functionality). We'd need to rely on the `ExportRequest` because there's no way to ask a `ScanRequest` to look at all versions/

**Describe the solution you'd like**
A simple, read-only request which would be relatively cheap to issue which can discern whether there exists any versions of any keys, live or dead in some key span. The DistSender should not parallelize this, as we'd expect the relevant ranges to be merged together if they are empty. The latching doesn't really matter because we expect these spans to be empty and unaccessed.

Jira issue: CRDB-18402

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by ajwerner**
This commit adds a new request, `IsSpanEmptyRequest`, which checks to see if
there is any data in a key span of any kind. It ignore the GC threshold, and
operates across all versions.

Fixes #85726

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
Overall looks good, thanks!

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-:-N911bHP5K48ljklJXh9:bd684tf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/kv/kvserver/batcheval/cmd_is_span_empty_test.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N910hVcBO78WYz0U4_G:-N910hVcBO78WYz0U4_H:b-xufzi9) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/kv/kvserver/batcheval/cmd_is_span_empty_test.go#L56)):*
> ```Go
> 	checkIsEmpty := func(t *testing.T, exp bool, from, to roachpb.Key) {
> 		var ba kv.Batch
> 		ba.Header.MaxSpanRequestKeys = 1
> ```

This is the only reason the DistSender isn't parallelizing the request. So if we don't set this, we'll get back the number of non-empty ranges, scanned in parallel. I suppose that might make sense, in a way, and we could extend it to also count the number of keys (I think David mentioned wanting this for some purpose). We should mention this in the request comment.
___
*[`pkg/roachpb/api.proto` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N911MFYCub1ZdCLJ7MR:-N911MFYCub1ZdCLJ7MS:b-gijgrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/roachpb/api.proto#L203)):*
> ```protobuf
> }
> 
> // IsSpanEmptyResponse is the response to an IsSpanEmptyRequest.
> ```

Let's mention that `NumKeys` is what callers want.
___
*[`pkg/storage/mvcc.go` line 5285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N90zx431RoR3uZEQ2Oe:-N90zx431RoR3uZEQ2Of:bkxy96m) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/storage/mvcc.go#L5285)):*
> ```Go
> 	// If we're not exporting all revisions then we can mask point keys below any
> 	// MVCC range tombstones, since we don't care about them.
> 	var rangeKeyMasking hlc.Timestamp
> ```

We don't really need this.
___
*[`pkg/storage/mvcc.go` line 5294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N91-1k_8U9v6P4B8soV:-N91-1k_8U9v6P4B8soW:b-7sot0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/storage/mvcc.go#L5294)):*
> ```Go
> 		EndTime:              opts.EndTS,
> 		RangeKeyMaskingBelow: rangeKeyMasking,
> 		IntentPolicy:         MVCCIncrementalIterIntentPolicyEmit,
> ```

Let's surface inline values too, rather than error on them.
___
*[`pkg/storage/testdata/mvcc_histories/clear_range` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N91-i2S9m4LuvWZw8C4:-N91-i2S9m4LuvWZw8C5:be4bqbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/storage/testdata/mvcc_histories/clear_range#L41)):*
> ```
> 
> run ok
> is_span_empty k=a end=+a
> ```

We could have some more test cases here (e.g. range keys, time spans etc), but no need to spend time on that now. The implementation is trivial, and `MVCCIncrementalIterator` itself has plenty of coverage.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @erikgrinaker)

___
*[`pkg/kv/kvserver/batcheval/cmd_is_span_empty_test.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N910hVcBO78WYz0U4_G:-N91juQkCrGCNUSKh5D4:b-6bjm42) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/kv/kvserver/batcheval/cmd_is_span_empty_test.go#L56)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This is the only reason the DistSender isn't parallelizing the request. So if we don't set this, we'll get back the number of non-empty ranges, scanned in parallel. I suppose that might make sense, in a way, and we could extend it to also count the number of keys (I think David mentioned wanting this for some purpose). We should mention this in the request comment.
</blockquote></details>

Yeah, correct. One thing I did is changed the `combine` method to set the `NumKeys` back to 1. 
___
*[`pkg/roachpb/api.proto` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N911MFYCub1ZdCLJ7MR:-N91kv3PCMzEO9BB0N92:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/roachpb/api.proto#L203)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Let's mention that `NumKeys` is what callers want.
</blockquote></details>

Done.
___
*[`pkg/storage/mvcc.go` line 5281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N91jmgb5fo1FP6aFgQ_:-N91jmgb5fo1FP6aFgQa:bam2kvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/storage/mvcc.go#L5281)):*
> ```Go
> 	var span *tracing.Span
> 	ctx, span = tracing.ChildSpan(ctx, "MVCCIsSpanEmpty")
> 	defer span.Finish()
> ```

I removed this tracing span too; don't think we need it 



_Code quote:_
```Go
	ctx, span = tracing.ChildSpan(ctx, "MVCCIsSpanEmpty")
	defer span.Finish()
```
___
*[`pkg/storage/mvcc.go` line 5285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N90zx431RoR3uZEQ2Oe:-N91jjoDBd_ly6X9TuUp:b-nol5w0) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/storage/mvcc.go#L5285)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

We don't really need this.
</blockquote></details>

copy-pasta, removed
___
*[`pkg/storage/mvcc.go` line 5294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N91-1k_8U9v6P4B8soV:-N91jBSPC2q7YDAFs-UP:b-u38rfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/storage/mvcc.go#L5294)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Let's surface inline values too, rather than error on them.
</blockquote></details>

Isn't that what this is doing? What is this comment asking for?

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/storage/mvcc.go` line 5294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-N91-1k_8U9v6P4B8soV:-N91mbDiD-190tuZmUi4:b-m997wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f578dcbe97a520579a8a9908f049913d171861/pkg/storage/mvcc.go#L5294)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Isn't that what this is doing? What is this comment asking for?
</blockquote></details>

Oh, sorry. We used to have `InlinePolicy` too, but we now unconditionally error on inline values -- the TBI will skip over inline values most of the time anyway, so this really shouldn't be used with spans that can have inline values at all. May want to call that out on the request.

**Comment by ajwerner** [comment]
@erikgrinaker anything else you want on this?

**Review by erikgrinaker — APPROVED** [review]
Nah, this looks good. I assume we don't need a version gate because it'll be gated by the broader schema GC version gate?

> Reviewed 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85798#-:-N92sd3XDlcTCN6HHs3y:b-1txiu6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
TFTR!

bors r=erikgrinaker

>Nah, this looks good. I assume we don't need a version gate because it'll be gated by the broader schema GC version gate?

Correct.

**Pull request merged**
