### PR TITLE
Return (response, error) #3

### PR DESCRIPTION
**Pull request by tamird**
More work toward #1400.

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM. Is the end goal to move away from the `(request, response)` signature everywhere? Otherwise there will always be one awkward copy/merge. It sounds that for #1400 all you're really changing is that you're always returning the error and setting it later along with an assertion, and that the (request,response) change is technically separate. Were you hoping to implement a solution that precludes lower-level actors from even setting an error, and if so which one?

**Comment by tamird** [comment]
> Is the end goal to move away from the (request, response) signature everywhere?
Yeah, all the way up to the sender. Note @bdarnell already did this on the method registration side, so it's a natural end state.

> It sounds that for #1400 all you're really changing is that you're always returning the error and setting it later along with an assertion, and that the (request,response) change is technically separate.
Yep, totally orthogonal changes that happen to be really convenient to do simultaneously.

> Were you hoping to implement a solution that precludes lower-level actors from even setting an error, and if so which one?
I'd like to eventually remove `SetGoError` and just have the various senders deal with boxing/unboxing the errors.

**Comment by tschottdorf** [comment]
sounds good :+1:

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
