### PR TITLE
cli: Make clear in startup logs if any env vars were used

### PR DESCRIPTION
**Pull request by a-robinson**
Help make situations like #8876 easier to debug

@tschottdorf

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9069)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9069#-:-KQgKRgbUXzTHVwQRI9-:bnfp4nl)*

**Comment by tamird** [comment]
Should this be on master?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9069#-:-KQgKTbAUOsYov9aZN2r:b-1s5u01)*

**Comment by a-robinson** [comment]
Well, it's neither hurting nor particularly helping stability. What would you say?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9069#-:-KQgN2AYGZA2VcW-jYPA:b-86tydp)*

**Comment by tamird** [comment]
Hm. It's probably OK on develop.

Note that in all likelihood it won't make the next beta.

**Comment by a-robinson** [comment]
Eh, on second thought, if this'll help anyone out at all with debugging, it may as well go in master rather than waiting for a month or more given the lack of risk. I'll move it over.

**Comment by a-robinson** [comment]
Switched

**Comment by tamird** [comment]
LGTM

**Pull request merged**
