### PR TITLE
geo: fix BoundingBox for Geography types

### PR DESCRIPTION
**Pull request by otan**
Our previous assumption that bounding boxes for geography types was
wrong -- we assumed that we can just compare min / max coordinates, but
for spherical geometries bounding boxes can traverse latitude/longitude
bounds and these min / max checks do not hold.

As such, we need to replace these bounding boxes with the s2.Rect
representation, which has complex logic that accounts for this
behaviour. This means bounding boxes are different between GEOMETRY and
GEOGRAPHY types.

The following changes have been made:
* Rename BoundingBox vars to Lo/Hi instead of Min/Max, to be more true
  to the name.
* Move BoundingBox comparison logic to the geo package from the geopb
  package, using CartesianBoundingBox as the name for GEOMETRY types.
* Change logic that converts between GEOMETRY and GEOGRAPHY types to
  change cached bounding boxes.
* Add SpatialObjectType to the SpatialObject protobuf. This allows us to
  differentiate geo vs geom types (PostGIS does this too). We in theory
  don't need this, but I think it stops programmer error so I'd rather
  keep it around.
* Added regression tests for this observed behaviour in the geogfn
  package.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50765#-:-MB1PnEbChxLlmbSzLbl:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geogfn/covers_test.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50765#-MB1OzV02ux8ddVqKxhe:-MB1OzV02ux8ddVqKxhf:bic4dsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f61d31bd53929c98ddff3991b1ffa8b286caf0/pkg/geo/geogfn/covers_test.go#L389)):*
> ```Go
> 		{
> 			"LINESTRING does not cover POINT with linestring crossing the longitudinal boundary but POINT on the other side",
> 			"LINESTRING(179 0, -179 0)",
> ```

this is different than LINESTRING(-179 0, 179 0), yes?
Or are we doing some normalization that is preventing us from representing this longer line (like the polygon normalization that prevents a polygon like (earth - california))?

**Review by otan — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50765#-:-MB2DWFP5NEhEFGDpxGv:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geogfn/covers_test.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50765#-MB1OzV02ux8ddVqKxhe:-MB2CUos2SGp-P6wszT-:b-5e4sox) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f61d31bd53929c98ddff3991b1ffa8b286caf0/pkg/geo/geogfn/covers_test.go#L389)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is different than LINESTRING(-179 0, 179 0), yes?
Or are we doing some normalization that is preventing us from representing this longer line (like the polygon normalization that prevents a polygon like (earth - california))?
</blockquote></details>

It's the same.
The libraries seem to handle this, but it seems to me it is implied the shortest line drawn from A to B is the line to be used.
Added some tests.

**Comment by otan** [comment]
bors r=sumeerbhola

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50765)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geogfn/covers_test.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50765#-MB1OzV02ux8ddVqKxhe:-MB3v-Tx-gxedfQdUTFj:bajd0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f61d31bd53929c98ddff3991b1ffa8b286caf0/pkg/geo/geogfn/covers_test.go#L389)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

It's the same.
The libraries seem to handle this, but it seems to me it is implied the shortest line drawn from A to B is the line to be used.
Added some tests.
</blockquote></details>

Does PostGIS allow both lines to be represented?

**Comment by otan** [comment]
___
*[pkg/geo/geogfn/covers_test.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50765#-MB1OzV02ux8ddVqKxhe:-MB4VmSQDd_kHb61X7uU:b-a2smwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f61d31bd53929c98ddff3991b1ffa8b286caf0/pkg/geo/geogfn/covers_test.go#L389)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does PostGIS allow both lines to be represented?
</blockquote></details>

Don't think so.

**Pull request merged**
