### PR TITLE
sql: add parens when stringifying expressions

### LINKED ISSUE #4305: sql: expression conversion to string doesn't add parens
Parsing an expression like ``(NOT (a = 1 AND b = 5)) OR (a = 2 AND b = 6)``, normalizing and printing it results in an ambiguous expression `NOT a = 1 AND b = 5 OR a = 2 AND b = 6`.

Ideally the string conversion code would be smart enough to add parens when necessary without polluting with parens everywhere.

### PR DESCRIPTION
**Pull request by RaduBerinde**
We don't add any parens when converting expressions to strings. The resulting
expression can be incorrect, e.g. the trees representing `(1+2)*3` and `1+(2*3)`
both are represented as `1+2*3`.

This is currently a cosmetic issue but it will be a problem if we want to
serialize and deserialize expressions as strings. To fix this we add parens
whenever an operator ordering can be ambiguous; we don't take operator
precedence into account as we don't have that data anywhere in the code (it's
part of the grammar). The resulting expressions are easier to read anyway.

Fixes #4305.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6155)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/expr.go, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6155#-KFjl4JSewd4nkmhfRZw:-KFjl4JSewd4nkmhfRZx:-1789997681) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d3721562faf18972275bcadfe661995ba90c4f8/sql/parser/expr.go#L60)):*
Rather than explicitly looking for the types which needs parens, we could distribute this knowledge by adding a new interface:

```
type operatorExpr interface {
  operatorExpr()
}
```

Then the types which need parens can add a `func (*AndExpr) operatorExpr() {}` marker and you would check here if `e` can be cast to the `operatorExpr` type:

```
if _, ok := e.(operatorExpr); ok {
  return fmt.Sprintf("(%s)", e)
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6155#-:-KFjlulltR3_51AOqzZ7:1417088721)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/expr.go, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6155#-KFjl4JSewd4nkmhfRZw:-KFjmJwjsMrKsaxR2JdB:-1821117831) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d3721562faf18972275bcadfe661995ba90c4f8/sql/parser/expr.go#L60)):*
Yeah that thought crossed my mind as well.. I don't have a strong preference for either method - do you have any intuition about which might be faster? (though any difference here might not be significant)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6155)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/expr.go, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6155#-KFjl4JSewd4nkmhfRZw:-KFjrsp0o1O7e7nt-5lW:-1901004945) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d3721562faf18972275bcadfe661995ba90c4f8/sql/parser/expr.go#L60)):*
I just tried out a benchmark, looks like a type assertion is faster than a type switch, esp. when there are many types. Will switch to that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6155)*

**Comment by petermattis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/expr.go, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6155#-KFjl4JSewd4nkmhfRZw:-KFjv-opmXmWJLhXKfiV:-1034209485) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d3721562faf18972275bcadfe661995ba90c4f8/sql/parser/expr.go#L60)):*
Looks good. Something else to keep in mind if optimizing `String()` every becomes important: the current implementation of `String()` for the expression nodes is very allocation heavy. We should be formatting the statement/expressions into a `bytes.Buffer` instead of concatenating strings. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6155)*

**Pull request merged**
