### PR TITLE
sql: More descriptive error messages in show partitions

### LINKED ISSUE #39476: sql: improve error message for show partitions from index
In running Movr, I partition an index:
```SQL
ALTER INDEX vehicles_auto_index_fk_city_ref_users PARTITION BY LIST (city) ( PARTITION new_york VALUES IN ('new york'), PARTITION chicago VALUES IN ('chicago'), PARTITION seattle VALUES IN ('seattle') );
```
I want to see how that index works:
```
root@10.142.0.78:26257/movr> show partitions from index vehicles_auto_index_fk_city_ref_users;
pq: relation "" does not exist
```
Since indexes can have the same name on different tables, we can't identify which index to report on. Instead, we assume that their is an imaginary table in front of this index. 
Users need to use the index hint syntax to find a result:
```
root@10.142.0.78:26257/movr> show partitions from index vehicles@vehicles_auto_index_fk_city_ref_users;
  database_name | table_name | partition_name | parent_partition | column_names |                   index_name                   | partition_value | zone_constraints
+---------------+------------+----------------+------------------+--------------+------------------------------------------------+-----------------+------------------+
  movr          | vehicles   | new_york       | NULL             | city         | vehicles@vehicles_auto_index_fk_city_ref_users | ('new york')    | NULL
  movr          | vehicles   | chicago        | NULL             | city         | vehicles@vehicles_auto_index_fk_city_ref_users | ('chicago')     | NULL
  movr          | vehicles   | seattle        | NULL             | city         | vehicles@vehicles_auto_index_fk_city_ref_users | ('seattle')     | NULL
(3 rows)

Time: 453.712389ms
```
We should improve upon the previous error message to say something like "no table specified. Specify a table by using the hint syntax of foo@foo_index"

### PR DESCRIPTION
**Pull request by rohany**
The show partitions statement suggests use of the index
hint syntax if the user does not use it.

Fixes #39476.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
```
root@127.0.0.1:50708/movr> create table t (x int, index i(x));
CREATE TABLE

Time: 2.789ms

root@127.0.0.1:50708/movr> show partitions from index i;
pq: no table specified. Specify a table using the hint syntax of table@index
root@127.0.0.1:50708/movr>
```

**Comment by awoods187** [comment]
Excited about this!

**Comment by rohany** [comment]
bump

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39543)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/delegate/show_partitions.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39543#-LnConTyCMzrSYF2FAWW:-LnConTyCMzrSYF2FAWX:b-pof8e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf4dc5a616ee87b2484cee985d431471e4c3ae1/pkg/sql/delegate/show_partitions.go#L95)):*
> ```Go
> 	// Throw a more descriptive error if the user did not use the index hint syntax.
> 	if tn.TableName == "" {
> 		return nil, errors.New("no table specified. Specify a table using the hint syntax of table@index")
> ```

You might want to take a look at the `errors.WithHint` function to get slightly nicer output. Also it might be nice to attach a pg error code. Here is an example of both: https://github.com/cockroachdb/cockroach/blob/497167b1c596eda2b70bed91c51ebf39b4356c33/pkg/sql/set_zone_config.go#L476-L480

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39543)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/delegate/show_partitions.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39543#-LnConTyCMzrSYF2FAWW:-LnDbS_A55V8wBHnTLqH:b-mqjz0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf4dc5a616ee87b2484cee985d431471e4c3ae1/pkg/sql/delegate/show_partitions.go#L95)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

You might want to take a look at the `errors.WithHint` function to get slightly nicer output. Also it might be nice to attach a pg error code. Here is an example of both: https://github.com/cockroachdb/cockroach/blob/497167b1c596eda2b70bed91c51ebf39b4356c33/pkg/sql/set_zone_config.go#L476-L480
</blockquote></details>

Oh, I see. Let me do what this does.

**Review by solongordon — APPROVED** [review]
Yup, lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39543#-:-LnDnOqM2VD8P9n7_jAd:b9n96h6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

**Pull request merged**
