### PR TITLE
sqlbase: add a test for MaybeUpgradeFormatVersion

### PR DESCRIPTION
**Pull request by danhhz**
cc @tamird

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8261)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/structured_test.go, line 985 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBg1v8v49QWTL5oSDt:-KOBg1v976jwjotJI6oz:-1188709860) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L985)):*
> ```Go
> func TestMaybeUpgradeFormatVersion(t *testing.T) {
> 	tests := []struct {
> 		shouldUpgrade bool
> ```

s/should/exp/ also this field should come after the desc, i think.

---

*[sql/sqlbase/structured_test.go, line 987 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBfvcZh74czHRWdsaH:-KOBfvc_7mAjtqSMZSU_:-1484173712) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L987)):*
> ```Go
> 		shouldUpgrade bool
> 		desc          TableDescriptor
> 		verify        func(i int, desc *TableDescriptor) // nil means no extra verification.
> ```

nit: unname the args here =/

---

*[sql/sqlbase/structured_test.go, line 997 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBgprXlPSSa_BfHyXk:-KOBgprXlPSSa_BfHyXl:-405750650) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L997)):*
> ```Go
> 				},
> 			},
> 			verify: func(i int, desc *TableDescriptor) {
> ```

why does this take a pointer? seems random.

---

*[sql/sqlbase/structured_test.go, line 1018 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBgPBUwbt-2DPbGZ71:-KOBgPBUwbt-2DPbGZ72:-1694633017) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L1018)):*
> ```Go
> 		desc := test.desc
> 		upgraded := desc.MaybeUpgradeFormatVersion()
> 		if test.shouldUpgrade && !upgraded {
> ```

```go
if upgraded != test.expUpgrade {
  t.Fatalf("%d: expected upgraded=%t, but got upgraded=%t", test.expUpgrade, upgraded)
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-:-KOBgtOC4j0nws0qCqlo:1417088721)*

**Comment by paperstreet** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/structured_test.go, line 985 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBg1v8v49QWTL5oSDt:-KOBi11tJ9xF4pNvRb0L:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L985)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/should/exp/ also this field should come after the desc, i think.
</details>
Done.

---

*[sql/sqlbase/structured_test.go, line 987 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBfvcZh74czHRWdsaH:-KOBi1Tppoy8_hwzsifz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L987)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: unname the args here =/
</details>
Done.

---

*[sql/sqlbase/structured_test.go, line 997 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBgprXlPSSa_BfHyXk:-KOBi9akT2lylYnb8b5x:460538563) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L997)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why does this take a pointer? seems random.
</details>
Okay, I've been working here for a while now and I still can't say I'm confident on when to use a pointer vs not. I've been trying to pay attention when I get it wrong, but I don't think it's always obvious. Are all the various rules & tradeoffs written up in one place somewhere? If they're not, could you do that sometime?

---

*[sql/sqlbase/structured_test.go, line 1018 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBgPBUwbt-2DPbGZ71:-KOBi51e5djnGSao9aOE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L1018)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> ```go
> if upgraded != test.expUpgrade {
>   t.Fatalf("%d: expected upgraded=%t, but got upgraded=%t", test.expUpgrade, upgraded)
> }
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261)*

**Comment by paperstreet** [comment]
Thanks for the Review!

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-:-KOBkLyMWmgC_T9p-soy:1076148785)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-:-KOBlsja48gp-IDnu5Is:1417088721)*

**Comment by paperstreet** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/structured_test.go, line 997 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBgprXlPSSa_BfHyXk:-KOBmUyJDsv92p4-tgnR:-569271253) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L997)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Okay, I've been working here for a while now and I still can't say I'm confident on when to use a pointer vs not. I've been trying to pay attention when I get it wrong, but I don't think it's always obvious. Are all the various rules & tradeoffs written up in one place somewhere? If they're not, could you do that sometime?
</details>
There's https://golang.org/doc/faq#Pointers, but it still doesn't feel comprehensive. For example, how large does a struct have to be before it's cheaper to use a pointer? How does heap allocation play into that tradeoff?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/sqlbase/structured_test.go, line 997 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBgprXlPSSa_BfHyXk:-KOBnKuXJQDgXU4J11KV:20044727) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L997)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> There's https://golang.org/doc/faq#Pointers, but it still doesn't feel comprehensive. For example, how large does a struct have to be before it's cheaper to use a pointer? How does heap allocation play into that tradeoff?
</details>
Yes, that doc is not comprehensive. My typical decision is always use a value unless:
 - nullability is needed (even here, sometimes you can use a bool)
 - mutability is needed
 - you're implementing an interface (pointers are more type-safe when implementing interfaces)

I think that's about it, plus the obvious stuff where go vet complains.

I have no idea about speed tradeoffs, but I'd always prefer to pay for the copy than to increase GC pressure until evidence is available that the latter is better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261)*

**Comment by paperstreet** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/sqlbase/structured_test.go, line 997 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261#-KOBgprXlPSSa_BfHyXk:-KOBz8m-I4NxC1NLN-yA:-32326507) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a90ee3612b09e754c73315567edd4e0eb152feb/sql/sqlbase/structured_test.go#L997)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yes, that doc is not comprehensive. My typical decision is always use a value unless:
>  - nullability is needed (even here, sometimes you can use a bool)
>  - mutability is needed
>  - you're implementing an interface (pointers are more type-safe when implementing interfaces)
> 
> I think that's about it, plus the obvious stuff where go vet complains.
> 
> I have no idea about speed tradeoffs, but I'd always prefer to pay for the copy than to increase GC pressure until evidence is available that the latter is better.
</details>
Huh. Maybe I've been making it too difficult ¯\_(ツ)_/¯

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8261)*

**Pull request merged**
