### PR TITLE
acceptance,deps: use `moby/moby` instead of `docker/docker`

### LINKED ISSUE #54193: *: avoid direct syscalls on darwin
Support for direct syscalls was dropped from the golang.org/x/sys package: https://github.com/golang/sys/commit/6fcdbc0bbc04dcd9e7dc145879ceaf9bf1c6ff03#diff-4913a9178621eadcdf191db17915fbcb

This causes compilation failures when `go get` pulls in the current version of sys.

```
# github.com/docker/docker/pkg/term
vendor/github.com/docker/docker/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
# github.com/cockroachdb/cockroach/pkg/util/log [github.com/cockroachdb/cockroach/pkg/util/timeutil.test]
pkg/util/log/stderr_redirect_unix.go:35:32: undefined: unix.SYS_FCNTL
# github.com/cockroachdb/cockroach/pkg/util/log [github.com/cockroachdb/cockroach/pkg/util/caller.test]
pkg/util/log/stderr_redirect_unix.go:35:32: undefined: unix.SYS_FCNTL
# github.com/cockroachdb/cockroach/pkg/util/log
pkg/util/log/stderr_redirect_unix.go:35:32: undefined: unix.SYS_FCNTL
# github.com/cockroachdb/cockroach/pkg/util/log [github.com/cockroachdb/cockroach/pkg/util/log.test]
pkg/util/log/stderr_redirect_unix.go:35:32: undefined: unix.SYS_FCNTL
```

Go 1.11 release notes:
>   On macOS and iOS, the runtime now uses libSystem.dylib
>    instead of calling the kernel directly. This should make
>    Go binaries more compatible with future versions of
>    macOS and iOS. The syscall package still makes direct
>    system calls; fixing this is planned for a
>    future release.

Jira issue: CRDB-3788

### PR DESCRIPTION
**Pull request by knz**
The Docker APIs have been renamed to "moby".

Fixes #54193

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
@otan I would sincerely welcome your help here. There's something very broken

First I encountered this when I ran `go mod tidy`:

```
go: github.com/Sirupsen/logrus@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
command failed (1); temp files in /tmp/tmp.Ab9q1sXL
```

This is because the canonical package name is `github.com/sirupsen/logrus` (note: lowercase), however throughout the `moby` code it is imported as `github.com/Sirupsen/logrus`

In fact, it looks like half our dependencies depend on it as `sirupsen` and the other half as `Sirupsen`.

So I pretend I want to be clever so I write this in `go.mod`:

```
replace github.com/Sirupsen/logrus => github.com/sirupsen/logrus v1.7.0
```

This gets me one step forward: then `go mod tidy` works, as well as `build/vendor_rebuild.sh`, however I now run into this:

```
gazelle: imports github.com/Sirupsen/logrus and github.com/sirupsen/logrus resolve to the same repository rule name com_github_sirupsen_logrus
gmake: *** [Makefile:332: vendor_rebuild] Error 1
```

Can you advise further?

**Comment by otan** [comment]
i'm kind of surprised the uppercase version considering https://github.com/sirupsen/logrus/blob/master/go.mod has the lowercase version.

can we fork the dependencies that depend on the uppercase version instead and replace with the lowercase version? how many dependencies are affected?

**Comment by knz** [comment]
at least all of `moby` I haven't checked the rest yet

**Comment by otan** [comment]
ah, looks like https://github.com/moby/moby doesn't have a go.mod yet...

**Comment by knz** [comment]
@srosenberg i just noticed i still have this pr open. Do you want it or should I close?

**Comment by srosenberg** [comment]
> @srosenberg i just noticed i still have this pr open. Do you want it or should I close?

It looks like `v20.10.22` is the latest release from moby (previously docker :). I think it's worth a shot. Thanks @knz!

**Pull request closed without merging**
