### PR TITLE
cloud,build: bump images to 1.0.5

### PR DESCRIPTION
**Pull request by jordanlewis**
Bump RHEL Dockerfile and Kubernetes examples.

### CODE REVIEW

**Comment by m-schneider** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17900#-:-KsKYiKAj10eelUTiWTi:bnfp4nl)*

**Review by a-robinson — APPROVED** [review]

**Comment by jordanlewis** [comment]
@a-robinson please rubberstamp the RHEL change I pushed and we'll be good.

**Comment by a-robinson** [comment]
The RHEL change isn't quite so straightforward since it has to be pushed to their container registry, not just changed in the file. I'll take care of it, but I need to get it hooked into our teamcity release workflow if we think it's worth keeping it up to date (cc @nstewart on whether we're seeing any use of the RHEL container image).

**Comment by nstewart** [comment]
We definitely want to keep our RHEL container up to date. We've only gotten 70 pulls so far but we haven't done any of our marketing activities yet.

**Comment by jordanlewis** [comment]
ping @a-robinson?

**Review by a-robinson — APPROVED** [review]
Sorry, this is good to go. I pushed it to the RHEL container registry last week.

**Comment by jordanlewis** [comment]
Thanks!

**Pull request merged**
