### PR TITLE
sqlliveness: session expiry callbacks must be async

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, the sqlliveness session expiry callbacks were called in the
heartbeatLoop thread which executed the renew/expiry logic. This could
cause deadlock since session expiration is used to trigger a shutdown of
the SQL instance via `stopper.Stop()`. The stopper would wait for all
async tasks to quiesce, but the `heartbeatLoop` would continue, waiting
for the callbacks to finish running. In addition, this task would hold a
lock on `l.mu` while waiting for the callbacks to run causing other
threads to wait if they needed to retrieve the session.

This change invokes each callback in its own goroutine to prevent this
deadlock.

Resolves #71292

Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
Appreciate the quick turnaround @ajwerner 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-:-Mll9KgV2lzmwiaP6-Ti:bb6lcwh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jaylim-crl)

___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-Mll0FR6USEPJg0DFgSQ-r1-48:-Mll9K1d5Rm-qkiE2gl5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/561958597475eacf5131f1b8cab33d32f2f43b45/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L48)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

rather than setting this, I think it's be sufficient to just reach into the `fakeStorage` and delete the record after you set up the callback. That will simulate the session expiring and being removed. 

```go
require.NoError(t, fakeStorage.Delete(ctx, session.ID()))
```
</blockquote></details>

Done.
___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-Mll0FR6USEPJg0DFgSQ-r1-65:-Mll6BM28Af0PeG0MQXu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/561958597475eacf5131f1b8cab33d32f2f43b45/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L65)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you shouldn't need to call this. The underlying `sqlliveness` infra should call `clearSession` when it fails to heartbeat. It'd be nice to confirm that. 
</blockquote></details>

Done.
___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-Mll0FR6USEPJg0DFgSQ-r1-71:-Mll7BnCBF5SwSKAZAKD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/561958597475eacf5131f1b8cab33d32f2f43b45/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L71)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

uber-nit that in some ways is worse but I prefer because it will log as we wait for it to stop. 

```go
testutils.SuceedsSoon(t, func() error {
   select {
   case <-stopper.IsStopped():
       return nil
   default:
       errors.New("not stopped") 
   }
})
```

</blockquote></details>

Done.
___
*[pkg/sql/sqlliveness/sqlliveness.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-Mll0FR6USEPJg0DFgSR-r1-100:-Mll5lPR78fGs2gJTCJq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/561958597475eacf5131f1b8cab33d32f2f43b45/pkg/sql/sqlliveness/sqlliveness.go#L100)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't love this because it these knobs are more for external users rather than internal users. I think we have the tools to write this test without this. 
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71419)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @jaylim-crl)

___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-MllEvkC3CSOYdVgNDj6:-MllEvkC3CSOYdVgNDj7:b-w2x63o) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb9824f6c45d970b3b9030880002163c6937bb2/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L37)):*
> ```Go
> 
> 	ctx, stopper := context.Background(), stop.NewStopper()
> 	defer stopper.Stop(ctx)
> ```

Seems like you don't need to do this. 
___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-MllES7hCVTNrXrzHQUK:-MllES7hCVTNrXrzHQUL:b-45n3ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb9824f6c45d970b3b9030880002163c6937bb2/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L39)):*
> ```Go
> 	defer stopper.Stop(ctx)
> 
> 	mClock := hlc.NewManualClock(hlc.UnixNano())
> ```

You could set this to some constant time and this test would become deterministic. Maybe:

```
t0 := time.Date(2000, time.January, 1, 0, 0, 0, 0, time.UTC)
mClock := hlc.NewManualClock(t0.UnixNano())
// ...
require.NoError(t, fakeStorage.Delete(ctx, session.ID()))
mClock.Advance(10 * time.Minute)
```
___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-MllE75_1YA_vNFSxuC-:-MllE75_1YA_vNFSxuC0:bdssad7) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb9824f6c45d970b3b9030880002163c6937bb2/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L66)):*
> ```Go
> 	// wait for async tasks to stop. The async tasks include the
> 	// sqlInstance `heartbeatLoop` function.
> 	require.NoError(t, fakeStorage.Delete(ctx, session.ID()))
> ```

I wonder if this is going to end up being racy with the set and the deletion. Should we first delete and then advance the clock? Also, seems like you may as well advance the clock by a duration rather than setting it to the current wall time. If you didn't override any of the settings, you could just advance the manual clock to the default TTL setting or whatever and shorten the test a tad.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71419)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jaylim-crl)

___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-MllEvkC3CSOYdVgNDj6:-MllJRpl3x8TwhiE3xdx:bb4ti0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb9824f6c45d970b3b9030880002163c6937bb2/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L37)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Seems like you don't need to do this. 
</blockquote></details>

True! Done.
___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-MllES7hCVTNrXrzHQUK:-MllK-fXDCeci8ge28nz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb9824f6c45d970b3b9030880002163c6937bb2/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L39)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

You could set this to some constant time and this test would become deterministic. Maybe:

```
t0 := time.Date(2000, time.January, 1, 0, 0, 0, 0, time.UTC)
mClock := hlc.NewManualClock(t0.UnixNano())
// ...
require.NoError(t, fakeStorage.Delete(ctx, session.ID()))
mClock.Advance(10 * time.Minute)
```
</blockquote></details>

Done.
___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-MllE75_1YA_vNFSxuC-:-MllK0hI3sTLPcADpp9Z:b10wh7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb9824f6c45d970b3b9030880002163c6937bb2/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L66)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I wonder if this is going to end up being racy with the set and the deletion. Should we first delete and then advance the clock? Also, seems like you may as well advance the clock by a duration rather than setting it to the current wall time. If you didn't override any of the settings, you could just advance the manual clock to the default TTL setting or whatever and shorten the test a tad. 
</blockquote></details>

I think you're right. If we advance the clock first, `extendSession` may get called. I reversed them.

**Review by jaylim-crl — APPROVED** [review]
:lgtm: with one small stopper comment. And I'd imagine the test fails with the changes reverted (i.e. running the callbacks synchronously)?

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-:-MllR0wM2qxMu777ZpuD:b-439cx2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @dhartunian)

___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-MllEvkC3CSOYdVgNDj6:-MllQ3Qg2GrYILBue4u3:b-mbf94z) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb9824f6c45d970b3b9030880002163c6937bb2/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L37)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

True! Done.
</blockquote></details>

How come we don't close the stopper here, i.e. `defer stopper.Stop(ctx)`? If the callbacks don't get invoked, the stopper wouldn't be stopped.

**Review by ajwerner — APPROVED** [review]
:lgtm: mod the `cluster.MakeTestingClusterSettings()` nit. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-:-MllZoce7yzo30k3Xj17:b563ixj)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @dhartunian and @jaylim-crl)

___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-MllEvkC3CSOYdVgNDj6:-MllZYbg4MbZSIOrZ9pr:b-byk536) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb9824f6c45d970b3b9030880002163c6937bb2/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L37)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

How come we don't close the stopper here, i.e. `defer stopper.Stop(ctx)`? If the callbacks don't get invoked, the stopper wouldn't be stopped.
</blockquote></details>

Because the callback below which we're testing calls `Stop`. 
___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-MllZcHe13n07cm5QV5_:-MllZcHe13n07cm5QV5a:b-kyn8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/add662b1bae2d37a6797fbf23bae69c230c9f31b/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L44)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	settings := cluster.MakeTestingClusterSettingsWithVersions(
> 		clusterversion.TestingBinaryVersion,
> 		clusterversion.TestingBinaryMinSupportedVersion,
> 		true /* initializeVersion */)
> ```
</details>

this can be `cluster.MakeTestingClusterSettings()` no?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71419)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @dhartunian, and @jaylim-crl)

___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 53 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-Mlldk1cBBJwn29K6dFY:-Mlldk1cBBJwn29K6dFZ:bkojdin) ([raw file](https://github.com/cockroachdb/cockroach/blob/35862914f53e30e7e3b36cf110bec432ac7172bb/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L53)):*
> ```
> 	session.RegisterCallbackForSessionExpiry(func(ctx context.Context) {
> 		stopper.Stop(ctx)
> 	})
> ```
oh, one more absolutely tiny nit that you don't need to do. `stopper.Stop` is already a `func(context.Context)`. You could make this:
```go
session.RegisterCallbackForSessionExpiry(stopper.Stop)
```

**Review by dhartunian — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-:-MlliG2ZEf1C5z9nFZ4I:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @jaylim-crl)

___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-MllZcHe13n07cm5QV5_:-Mlli03a1QQbxyW9_PrK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/add662b1bae2d37a6797fbf23bae69c230c9f31b/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L44)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	settings := cluster.MakeTestingClusterSettingsWithVersions(
> 		clusterversion.TestingBinaryVersion,
> 		clusterversion.TestingBinaryMinSupportedVersion,
> 		true /* initializeVersion */)
> ```
this can be `cluster.MakeTestingClusterSettings()` no? 
</blockquote></details>

Done.
___
*[pkg/sql/sqlliveness/slinstance/slinstance_test.go, line 53 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71419#-Mlldk1cBBJwn29K6dFY:-Mlli4HrCQ004kS6Juok:bpcfzuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/35862914f53e30e7e3b36cf110bec432ac7172bb/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L53)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	session.RegisterCallbackForSessionExpiry(func(ctx context.Context) {
> 		stopper.Stop(ctx)
> 	})
> ```
oh, one more absolutely tiny nit that you don't need to do. `stopper.Stop` is already a `func(context.Context)`. You could make this:
```go
session.RegisterCallbackForSessionExpiry(stopper.Stop)
```
</blockquote></details>

ah! great to know! Don't think I have the patience for one more TeamCity iteration today.

**Pull request merged**
