### PR TITLE
exec: add interface skeletons

### PR DESCRIPTION
**Pull request by jordanlewis**
Add the interface skeletons for column vector operators.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
Nice. Are these interfaces so we can start working independently or are you planning on keeping them as interfaces?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-:-LOUJ4k28iy1ZFSkbibR:b9c4eal)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colbatch.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOTT8PxA1tuhjiAEF-S:-LOTT8PxA1tuhjiAEF-T:b6f9c0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colbatch.go#L39)):*
> ```Go
> 	// slice of columns in this batch.
> 	b      []ColVec
> 	useSel bool
> ```

What about getting rid of this boolean and checking `if sel != nil` for the cases you would want to use the selection vector.
___
*[pkg/sql/exec/colbatch.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOTT3b3Ety3-J7XlWBX:-LOTT3b3Ety3-J7XlWBY:bucx7dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colbatch.go#L41)):*
> ```Go
> 	useSel bool
> 	// if useSel is true, a selection vector from upstream. a selection vector is
> 	// a list of selected column indexes in this dataFlow's columns.
> ```

I think the term `dataFlow` is undefined here?
___
*[pkg/sql/exec/colvec.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOUGjrs44gH3cdCuyzi:-LOUGjrs44gH3cdCuyzj:b8z9t2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colvec.go#L19)):*
> ```Go
> // ColVec is an interface that represents a column vector that's accessible by
> // Go native types.
> type ColVec interface {
> ```

Do we also want to have a `Type() byte` method?
___
*[pkg/sql/exec/colvec.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOUIIyA7XD_EAvbi5qv:-LOUIIyA7XD_EAvbi5qw:b-8uasec) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colvec.go#L22)):*
> ```Go
> 	Nulls
> 
> 	// TODO(jordan): is a bitmap or slice of bools better?
> ```

I'm wondering about this too. Why is it an interface?
___
*[pkg/sql/exec/colvec.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOUIVC_DHED8CcQBT0r:-LOUIVC_DHED8CcQBT0s:beji6t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colvec.go#L130)):*
> ```Go
> 
> type memBytes struct {
> 	col [][]byte
> ```

We might want to actually make this a single slice of `[]byte` with associated offsets. I guess this is fine for now and you're doing this for simplicity.

**Review by jordanlewis — COMMENTED** [review]
These will stay interfaces. It's okay to have interfaces at this level of the code - as long as they spit out the actual data vectors for the operators to operate on. It's also useful to have multiple implementations of at least `ColBatch` - one is this simple, in-memory slices one, which is convenient for testing, and one is the `ptable` block format which is more memory efficient but harder to use.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-:-LOUJvxW0OTTsHJakizI:bqwrnys)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colbatch.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOTT8PxA1tuhjiAEF-S:-LOULA3z7MLDGT99s8QD:bltxb6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colbatch.go#L39)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What about getting rid of this boolean and checking `if sel != nil` for the cases you would want to use the selection vector.
</blockquote></details>

That won't work - you need to pass along the selection vector memory so downstream operators can set and edit it. So you do need the boolean.
___
*[pkg/sql/exec/colbatch.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOTT3b3Ety3-J7XlWBX:-LOUL8p-9FxmI9fCDRws:bw10jn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colbatch.go#L41)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think the term `dataFlow` is undefined here?
</blockquote></details>

Oops, done.
___
*[pkg/sql/exec/colvec.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOUGjrs44gH3cdCuyzi:-LOUKjJO1mTGEL5JKlar:b-2gnz14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colvec.go#L19)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we also want to have a `Type() byte` method?
</blockquote></details>

Good question. I don't think it's necessary to keep a type in this interface, because every operator will statically know the type of all of its columns. Maybe it'll be convenient to have it later, but for now it's not necessary.
___
*[pkg/sql/exec/colvec.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOUIIyA7XD_EAvbi5qv:-LOUK9P95XwqsElzJrZ-:bg6psde) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colvec.go#L22)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm wondering about this too. Why is it an interface?
</blockquote></details>

I'm copying this from Peter's code in pebble. It's possible that this should just be a slice of bools, but then that doesn't let us use a bitmap if that's faster. I'm not sure - but this will give us a place to start. It'll be easy enough to change later.
___
*[pkg/sql/exec/colvec.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOUIVC_DHED8CcQBT0r:-LOUKFIa5pr9u7NME8o1:b-ycfkm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colvec.go#L130)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We might want to actually make this a single slice of `[]byte` with associated offsets. I guess this is fine for now and you're doing this for simplicity.
</blockquote></details>

Yeah, the `memFoo` structures are not intended to be the efficient ones. I'm going to add that in soon - it'll be accessors to the `ptable` block format in pebble.

It remains to be seen via benchmarking and experimentation whether we want to abandon any function calls for accessing the varlen datatypes. exectoy didn't have any of that stuff, so we'll have to start somewhere. This interface is copied from pebble - it's a place to start.

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31185)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colbatch.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31185#-LOTT8PxA1tuhjiAEF-S:-LOZEa2j3uWHH31_9VzJ:b-wv2sxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c976fbdd97199eb0bddefdccf2f779fa644b190/pkg/sql/exec/colbatch.go#L39)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

That won't work - you need to pass along the selection vector memory so downstream operators can set and edit it. So you do need the boolean.
</blockquote></details>

As discussed in slack, this might not be necessary but you think it's clearer. I personally think that removing this boolean is clearer than not doing so and avoids the possibility of weird states (i.e. what does it mean when `useSel` is false but `sel` is a slice). Do whatever you think is right, don't want this to block the PR.

**Comment by jordanlewis** [comment]
> (i.e. what does it mean when useSel is false but sel is a slice)

You're right, but it's hard to figure out what to do one way or the other until we actually have operators to look at. Going to merge as-is just as a straw man.

bors r+

**Pull request merged**
