### PR TITLE
sql: do not plan zig-zag joins with implicit, nullable equality columns

### PR DESCRIPTION
**Pull request by mgartner**
Zig-zag joins are no longer planned with implicit equality columns that
are nullable. For example:

    CREATE TABLE t (
        k INT PRIMARY KEY,
        a INT,
        b INT,
        c INT,
        d INT NOT NULL,
        INDEX ac (a, c),
        INDEX bc (b, c),
        INDEX ad (a, d),
        INDEX bd (b, d)
    )

    SELECT k FROM t WHERE a = 1 AND b = 2

Prior to this commit, the optimizer would generate a zig-zag join using
indexes `ac` and `bc`, with `a` and `b` as fixed columns and `c` and `k`
as implicit equality columns. This zig-zag join incorrectly discards any
rows where the value of `c` is `NULL` because `NULL != NULL`.

Now the optimizer only generates a zig-zag join if the implicit equality
columns are non-nullable. In the example above a zig-zag join using `ad`
and `bd` can be generated with `d` and `k` as implicit equality columns
because they are guaranteed to not contain `NULL` values.

Fixes #71655

Release note (bug fix): A bug has been fixed which caused incorrect
results for some queries that utilized a zig-zag join. The bug could
only reproduce on tables with at least two multi-column indexes with
nullable columns. The bug was present since version 19.2.0.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Should you add "Fixes #71655"?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-:-MmTdQWN3YaYx7qV0zFQ:bsrysvr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTd35P3SMNf70gZEPf:-MmTd35P3SMNf70gZEPg:b-s1a7sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L86)):*
> ```
> INSERT INTO t71655 VALUES (2, 10, 20, NULL, 12)
> 
> # An zig-zag join is not performed here with ac and bc because c is nullable and
> ```

nit: An zig-zag -> A zig-zag
___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTeVDz-sI_yz-BIuc3:-MmTeVDz-sI_yz-BIuc4:b-1xzj7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L88)):*
> ```
> # An zig-zag join is not performed here with ac and bc because c is nullable and
> # cannot be an implicit equality column.
> query I
> ```

I think you need `rowsort`
___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTd8C499XlsB98QHXS:-MmTd8C499XlsB98QHXT:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L98)):*
> ```
> CREATE INDEX bd ON t71655 (b, d)
> 
> # An zig-zag join is performed here with ad and bd because d is non-nullable and
> ```

ditto
___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTeYIn6FS0R2rIjYSM:-MmTeYIn6FS0R2rIjYSN:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L100)):*
> ```
> # An zig-zag join is performed here with ad and bd because d is non-nullable and
> # can be an implicit equality column.
> query I
> ```

ditto
___
*[pkg/sql/opt/xform/select_funcs.go, line 1227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTepzy5ZF3pwfcjyBD:-MmTepzy5ZF3pwfcjyBE:b-kytohp) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/opt/xform/select_funcs.go#L1227)):*
> ```Go
> 				continue
> 			}
> 		}
> ```

nit: why did you move this block down? I'd just leave it where it was before

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71758)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTeVDz-sI_yz-BIuc3:-MmTqyC9E-SCDwVUNpF2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L88)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you need `rowsort`
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTd8C499XlsB98QHXS:-MmTqvJt7fYZRO9OZuAe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L98)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTeYIn6FS0R2rIjYSM:-MmTqycG14QZwbTI7m2c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L100)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTepzy5ZF3pwfcjyBD:-MmTrA8a8Xn9Mr1GI8mB:b-nb1ypg) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/opt/xform/select_funcs.go#L1227)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: why did you move this block down? I'd just leave it where it was before
</blockquote></details>

It made more sense to me to take care of explicit equality columns first (because nullability does not matter for them), then handle implicit equality columns (in which case nullability does matter).

In theory, you could have explicit equality columns with the same ID (e.g., `WHERE a = 1 AND b = 2 AND c = c`), in which case nullability would not matter and you'd have to put the explicit logic before the implicit logic to generate a zig-zag join. In practice, something like `c = c` is normalized to `c IS NOT NULL` so it doesn't end up being necessary. But I still think this flows better, unless you see a problem with it.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71758)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/xform/select_funcs.go, line 1227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTepzy5ZF3pwfcjyBD:-MmUGeCi2RgZWL7j5109:b-fhx1kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/opt/xform/select_funcs.go#L1227)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It made more sense to me to take care of explicit equality columns first (because nullability does not matter for them), then handle implicit equality columns (in which case nullability does matter).

In theory, you could have explicit equality columns with the same ID (e.g., `WHERE a = 1 AND b = 2 AND c = c`), in which case nullability would not matter and you'd have to put the explicit logic before the implicit logic to generate a zig-zag join. In practice, something like `c = c` is normalized to `c IS NOT NULL` so it doesn't end up being necessary. But I still think this flows better, unless you see a problem with it.
</blockquote></details>

I suppose just because `Find` could theoretically be slightly more expensive and in the spirit of "changing as little code as possible" for the backport, but it's probably fine -- your call.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71758)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/select_funcs.go, line 1227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmTepzy5ZF3pwfcjyBD:-MmV1N9M9l7O0iQ2nPl2:bix218q) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ed1175ad8641f6b2797ff67acc4f48da5f42e8/pkg/sql/opt/xform/select_funcs.go#L1227)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I suppose just because `Find` could theoretically be slightly more expensive and in the spirit of "changing as little code as possible" for the backport, but it's probably fine -- your call.
</blockquote></details>

I reverted the ordering.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71758)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/xform/select_funcs.go, line 1210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmVbOzJET-RE1vlkO2c:-MmVbOzK9PFUFdEHSpFX:b-6hossw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b574088d49eff7fb03e1355132b4719749db558e/pkg/sql/opt/xform/select_funcs.go#L1210)):*
> ```Go
> 		// true if they are non-nullable because NULL != NULL. See issue #71655.
> 		if leftColID == rightColID {
> 			leftCol := tab.Column(tabID.ColumnOrdinal(leftColID))
> ```

As @srosenberg pointed out to me offline, we only need to make this call once, since `leftColID` is equal to `rightColID` (and we also only need to check `IsNullable()` once below).

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71758)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rytaft, and @srosenberg)

___
*[pkg/sql/opt/xform/select_funcs.go, line 1210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71758#-MmVbOzJET-RE1vlkO2c:-MmY0-ZcEmtnC-Yy4LrF:b1paqxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b574088d49eff7fb03e1355132b4719749db558e/pkg/sql/opt/xform/select_funcs.go#L1210)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

As @srosenberg pointed out to me offline, we only need to make this call once, since `leftColID` is equal to `rightColID` (and we also only need to check `IsNullable()` once below).
</blockquote></details>

Ah... Great point! Fixed

**Pull request merged**
