### PR TITLE
opt: fix show_trace_nonmetamorphic test

### LINKED ISSUE #58989: sql/opt/exec/execbuilder: TestExecBuild failed
[(sql/opt/exec/execbuilder).TestExecBuild failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2582270&tab=buildLog) on [master@5bd34572e489dea0fa67feedd7c499f0ad9f9ebd](https://github.com/cockroachdb/cockroach/commits/5bd34572e489dea0fa67feedd7c499f0ad9f9ebd):

```
=== RUN   TestExecBuild
    test_log_scope.go:72: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestExecBuild204570820
    test_log_scope.go:73: use -show-logs to present logs inline
=== CONT  TestExecBuild
    logic.go:3294: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestExecBuild204570820
--- FAIL: TestExecBuild (51.97s)
=== RUN   TestExecBuild/local/show_trace_nonmetamorphic
=== PAUSE TestExecBuild/local/show_trace_nonmetamorphic
=== CONT  TestExecBuild/local/show_trace_nonmetamorphic
=== CONT  TestExecBuild/local/show_trace_nonmetamorphic
    logic.go:2258: 
         
        testdata/show_trace_nonmetamorphic:30: SELECT operation, regexp_replace(message, 'create_as_of_time:<[^>]+>', 'create_as_of_time:<...>') as message
          FROM [SHOW KV TRACE FOR SESSION]
        WHERE message NOT LIKE '%Z/%'
          AND operation NOT LIKE 'kv.DistSender: sending partial batch%'  -- order of partial batches is not deterministic
          AND message NOT SIMILAR TO '%(PushTxn|ResolveIntent|SystemConfigSpan)%'
          AND tag NOT LIKE '%intExec=%'
          AND tag NOT LIKE '%scExec%'
          AND tag NOT LIKE '%IndexBackfiller%'
          AND operation != 'dist sender send'
        expected:
            flow       CPut /NamespaceTable/30/1/53/29/"kv"/4/1 -> 54
            flow       CPut /Table/3/1/54/2/1 -> table:<name:"kv" id:54 version:1 modification_time:<> parent_id:53 unexposed_parent_schema_id:29 columns:<name:"k" id:1 type:<InternalType:<family:IntFamily width:64 precision:0 locale:"" visible_type:0 oid:20 time_precision_is_set:false > TypeMeta:<Version:0 > > nullable:false hidden:false virtual:false pg_attribute_num:0 alter_column_type_in_progress:false system_column_kind:NONE > columns:<name:"v" id:2 type:<InternalType:<family:IntFamily width:64 precision:0 locale:"" visible_type:0 oid:20 time_precision_is_set:false > TypeMeta:<Version:0 > > nullable:true hidden:false virtual:false pg_attribute_num:0 alter_column_type_in_progress:false system_column_kind:NONE > next_column_id:3 families:<name:"primary" id:0 column_names:"k" column_names:"v" column_ids:1 column_ids:2 default_column_id:2 > next_family_id:1 primary_index:<name:"primary" id:1 unique:true version:2 column_names:"k" column_directions:ASC column_ids:1 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 on_delete:NO_ACTION on_update:NO_ACTION match:SIMPLE > interleave:<> partitioning:<num_columns:0 num_implicit_columns:0 > type:FORWARD created_explicitly:false encoding_type:0 sharded:<is_sharded:false name:"" shard_buckets:0 > disabled:false geo_config:<> predicate:"" > next_index_id:2 privileges:<users:<user_proto:"admin" privileges:2 > users:<user_proto:"root" privileges:2 > owner_proto:"root" version:1 > next_mutation_id:1 format_version:3 state:PUBLIC offline_reason:"" view_query:"" is_materialized_view:false drop_time:0 replacement_of:<id:0 time:<> > audit_mode:DISABLED drop_job_id:0 create_query:"" create_as_of_time:<> temporary:false >
            exec stmt  rows affected: 0
            
        but found (query options: "") :
            flow       CPut /NamespaceTable/30/1/53/29/"kv"/4/1 -> 54
            flow       CPut /Table/3/1/54/2/1 -> table:<name:"kv" id:54 version:1 modification_time:<> parent_id:53 unexposed_parent_schema_id:29 columns:<name:"k" id:1 type:<InternalType:<family:IntFamily width:64 precision:0 locale:"" visible_type:0 oid:20 time_precision_is_set:false > TypeMeta:<Version:0 > > nullable:false hidden:false virtual:false pg_attribute_num:0 alter_column_type_in_progress:false system_column_kind:NONE > columns:<name:"v" id:2 type:<InternalType:<family:IntFamily width:64 precision:0 locale:"" visible_type:0 oid:20 time_precision_is_set:false > TypeMeta:<Version:0 > > nullable:true hidden:false virtual:false pg_attribute_num:0 alter_column_type_in_progress:false system_column_kind:NONE > next_column_id:3 families:<name:"primary" id:0 column_names:"k" column_names:"v" column_ids:1 column_ids:2 default_column_id:2 > next_family_id:1 primary_index:<name:"primary" id:1 unique:true version:2 column_names:"k" column_directions:ASC column_ids:1 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 on_delete:NO_ACTION on_update:NO_ACTION match:SIMPLE > interleave:<> partitioning:<num_columns:0 num_implicit_columns:0 > type:FORWARD created_explicitly:false encoding_type:0 sharded:<is_sharded:false name:"" shard_buckets:0 > disabled:false geo_config:<> predicate:"" > next_index_id:2 privileges:<users:<user_proto:"admin" privileges:2 > users:<user_proto:"root" privileges:2 > owner_proto:"root" version:1 > next_mutation_id:1 format_version:3 state:PUBLIC offline_reason:"" view_query:"" is_materialized_view:false drop_time:0 replacement_of:<id:0 time:<> > audit_mode:DISABLED drop_job_id:0 create_query:"" create_as_of_time:<> temporary:false partition_all_by:false >
            exec stmt  rows affected: 0
--- done: testdata/show_trace_nonmetamorphic with config local: 4 tests, 1 failures
E210114 05:44:48.556397 108 sql/logictest/logic.go:3526  testdata/show_trace_nonmetamorphic:45: too many errors encountered, skipping the rest of the input
    logic.go:3084: 
        testdata/show_trace_nonmetamorphic:45: error while processing
    logic.go:3084: testdata/show_trace_nonmetamorphic:45: too many errors encountered, skipping the rest of the input
E210114 05:44:48.578278 5353 sql/stats/automatic_stats.go:302  failed to refresh stats: node unavailable; try another peer
--- done: testdata/window with config local: 22 tests, 0 failures
        --- FAIL: TestExecBuild/local/show_trace_nonmetamorphic (1.97s)
=== RUN   TestExecBuild/local
    --- FAIL: TestExecBuild/local (0.01s)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestExecBuild PKG=./pkg/sql/opt/exec/execbuilder TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestExecBuild.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by RaduBerinde**
This test was broken but it wasn't obvious because it only runs 20% of
the time (when the build happens to not be metamorphic). It can be
forced to run using `TAGS=crdb_test_off`.

Fixes #58989.

Release note: None

### CODE REVIEW

**Review by otan — APPROVED** [review]
i'm guesing some logic underneath accepts both with and without partition_all_by =false?

**Comment by RaduBerinde** [comment]
No, the subtest is skipped altogether if the global metamorphic build flag is set, which happens 80% of the time. So the overall test passes 80% of the time even if there is garbage in the file.

**Comment by yuzefovich** [comment]
A flake.

bors r+

**Comment by otan** [comment]
bors success rate is like 20% these days

bors r+

**Comment by RaduBerinde** [comment]
> bors success rate is like 20% these days

I'm doing the best I can!! :) (I'm the test infra engineer this week)

**Comment by otan** [comment]
good luck! i hope you see green salad with no tomatoes!

**Pull request merged**
