### PR TITLE
sql/schemachanger: add dep rules between trigger element and its dependents

### PR DESCRIPTION
**Pull request by DrewKimball**
This commit adds a set of dependency rules to the declarative schemachanger to ensure that triggers and their dependent elements (name, references etc.) are added and removed in the correct order.

Informs #126359

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
This is follow-up for #128540 mentioned [here](https://github.com/cockroachdb/cockroach/pull/128540#pullrequestreview-2358760576).

**Review by rafiss — COMMENTED** [review]
i believe we will need these rules in `pkg/sql/schemachanger/scplan/internal/rules/release_24_3` on the master branch. (but when we do the backport, that directory won't exist.)

anything else to think about here @fqazi ?

**Review by fqazi — CHANGES_REQUESTED** [review]
Might be good to add a test inside: pkg/sql/schemachanger/scplan/testdata with add/drop trigger

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133512#-:-OAU76ro1EG-JmSuaNrT:b-hc9fxu)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_trigger.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133512#-OAU6aMtAqLs4SJWX3ob:-OAU6aMtAqLs4SJWX3oc:b-4n17ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/b810c0a5ba0e9a8d5f652a9d0238612e018856e1/pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_trigger.go#L39)):*
> ```Go
> 				from.TypeFilter(rulesVersionKey, isTriggerDependent),
> 				to.Type((*scpb.Trigger)(nil)),
> 				JoinOnIndexID(from, to, "table-id", "trigger-id"),
> ```

JoinOnTriggerID?
___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_trigger.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133512#-OAU6Z-N9Y0rkdrI0umQ:-OAU6Z-N9Y0rkdrI0umR:b-4n17ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/b810c0a5ba0e9a8d5f652a9d0238612e018856e1/pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_trigger.go#L27)):*
> ```Go
> 				from.Type((*scpb.Trigger)(nil)),
> 				to.TypeFilter(rulesVersionKey, isTriggerDependent),
> 				JoinOnConstraintID(from, to, "table-id", "trigger-id"),
> ```

JoinOnTriggerID?
___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_trigger.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133512#-OAU6_KY8Wwbdo_9zsQr:-OAU6_KZ31SEBzCYVvud:b-4n17ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/b810c0a5ba0e9a8d5f652a9d0238612e018856e1/pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_trigger.go#L40)):*
> ```Go
> 				from.TypeFilter(rulesVersionKey, isTriggerDependent),
> 				to.Type((*scpb.Trigger)(nil)),
> 				JoinOnConstraintID(from, to, "table-id", "trigger-id"),
> ```

JoinOnTriggerID?

**Review by DrewKimball — COMMENTED** [review]
TRTRs!

>i believe we will need these rules in `pkg/sql/schemachanger/scplan/internal/rules/release_24_3` on the master branch. (but when we do the backport, that directory won't exist.)

I'll add a second commit that moves the rules to `release_24_3`, and then will just backport the first commit.

> Might be good to add a test inside: pkg/sql/schemachanger/scplan/testdata with add/drop trigger

Done. I've also removed `trigger dependents exist before trigger becomes public` and `trigger no longer public before dependents` because I think they were incorrect.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133512#-:-OAVDgczBz66AD9PDy6d:bbounw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_trigger.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133512#-OAU6aMtAqLs4SJWX3ob:-OAVJd5zAIYEHmFTGdUq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b810c0a5ba0e9a8d5f652a9d0238612e018856e1/pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_trigger.go#L39)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

JoinOnTriggerID?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_trigger.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133512#-OAU6Z-N9Y0rkdrI0umQ:-OAVJduVELjZiJ0U-1o-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b810c0a5ba0e9a8d5f652a9d0238612e018856e1/pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_trigger.go#L27)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

JoinOnTriggerID?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_trigger.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133512#-OAU6_KY8Wwbdo_9zsQr:-OAVJeaLCVM40X4vmLLY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b810c0a5ba0e9a8d5f652a9d0238612e018856e1/pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_trigger.go#L40)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

JoinOnTriggerID?
</blockquote></details>

Done.

**Review by fqazi — APPROVED** [review]
Great work Drew! :lgtm_strong: 

> Reviewed 6 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133512#-:-OAXbEOe2yj3PE17KLHr:bt4gyrq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Pull request merged**
