### PR TITLE
liveness: run sync disk write in a stopper task

### LINKED ISSUE #81511: kv/kvserver: TestReplicaDrainLease failed
kv/kvserver.TestReplicaDrainLease [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5203810&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5203810&tab=artifacts#/) on master @ [ce66acdbba801de88f1dd645eaedeb3834f23dbd](https://github.com/cockroachdb/cockroach/commits/ce66acdbba801de88f1dd645eaedeb3834f23dbd):

```
=== RUN   TestReplicaDrainLease
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/751d67000aac5f3394c2369309253f02/logTestReplicaDrainLease1320269877
    test_log_scope.go:80: use -show-logs to present logs inline
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestReplicaDrainLease.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-15111

### LINKED ISSUE #81827: kvserver: pebble panic from WriteSyncNoop
**Describe the problem**

In [a recent CI failure](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/5272407?buildTab=overview&showRootCauses=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) a number of TestExecBuild tests failed to return results; however the root cause seems to be a panic from the liveness system:

```
panic: pebble: closed

goroutine 97893 [running]:
github.com/cockroachdb/pebble.(*DB).Apply(0x0, 0x56fb700, 0xc006fa6000)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:717 +0x3c9
github.com/cockroachdb/pebble.(*Batch).Commit(...)
	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:932
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit(0xc01a0959e0, 0x0)
	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:495 +0x3c
github.com/cockroachdb/cockroach/pkg/storage.WriteSyncNoop({0x57cd8f8, 0xc01a0959e0})
	github.com/cockroachdb/cockroach/pkg/storage/engine.go:938 +0xba
github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1()
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1274 +0x25
github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall(0xc0291f7890, 0xc02ef44a50, {0x42b9a51, 0x1}, 0xc033470bd0)
	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128 +0x3b
created by github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).DoChan
	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:121 +0x2f1
I220525 12:35:49.000498 1 (gostd) testmain.go:78  [-] 1  Test //pkg/sql/opt/exec/execbuilder:execbuilder_test exited with error code 2
```

### PR DESCRIPTION
**Pull request by erikgrinaker**
**liveness: move stopper to `NodeLivenessOptions`**

Release note: None

**liveness: run sync disk write in a stopper task**

This patch runs the sync disk write during node heartbeats in a stopper
task. The write is done in a goroutine, so that we can respect the
caller's context cancellation (even though the write itself won't).
However, this could race with engine shutdown when stopping the node,
violating the Pebble contract and triggering the race detector.  Running
it as a stopper task will cause the node to wait for the disk write to
complete before closing the engine.

Of course, if the disk stalls then node shutdown will now never
complete. This is very unfortunate, since stopping the node is often
the only mitigation to recover stuck ranges with stalled disks. This is
mitigated by Pebble panic'ing the node on stalled disks, and Kubernetes
and other orchestration tools killing the process after some time.

Touches #81786.
Resolves #81511.
Resolves #81827.

Release note: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
Thanks for jumping on this!  I suppose if we were worried about the impact of a disk stall on shutdown, we could do something where we give up on the operation after some amount of time. But, I buy the paragraph you wrote about mitigations.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81813#-:-N2vVyIg-jz1fPcj4h7Z:b-777gvf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @stevendanna, and @tbg)

___
*[`pkg/kv/kvserver/liveness/liveness.go` line 1277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81813#-N2vVj4ZAEWlOAp4-UXq:-N2vVj4ZAEWlOAp4-UXr:b-8pk2nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/acc87551793aa62177b1bc5fc13342bbc5708ffc/pkg/kv/kvserver/liveness/liveness.go#L1277)):*
> ```Go
> 			resultCs[i], _ = nl.engineSyncs.DoChan(strconv.Itoa(i), func() (interface{}, error) {
> 				var taskErr error
> 				if err := nl.stopper.RunTask(ctx, "liveness-hb-diskwrite", func(ctx context.Context) {
> ```

Looks like there is also `RunTaskWithErr`  that would cut down on some of the boilerplate here, but it's fine as is.

**Review by stevendanna — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81813#-:-N2vWiGu6k177oCvWdeS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker, @stevendanna, and @tbg)

**Review by nicktrav — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81813#-:-N2vX1MTEMuGpZr0uHLc:b-g2a5fb)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @erikgrinaker and @tbg)

**Review by erikgrinaker — COMMENTED** [review]
> I suppose if we were worried about the impact of a disk stall on shutdown, we could do something where we give up on the operation after some amount of time. But, I buy the paragraph you wrote about mitigations.

Yeah, but I don't know if that's always going to be safe -- for example, in this case that means that we'll be closing Pebble while we still have in-flight writes, which is what prompted this in the first place. There's no way to cancel these writes afaik.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81813#-:-N2vbAkEDHMD0qV8iw8y:bzif2lk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @nicktrav, @stevendanna, and @tbg)

___
*[`pkg/kv/kvserver/liveness/liveness.go` line 1277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81813#-N2vVj4ZAEWlOAp4-UXq:-N2vayHO-uWFlqhT2bKC:byr5zhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/acc87551793aa62177b1bc5fc13342bbc5708ffc/pkg/kv/kvserver/liveness/liveness.go#L1277)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Looks like there is also `RunTaskWithErr`  that would cut down on some of the boilerplate here, but it's fine as is.
</blockquote></details>

Oh nice, that's better -- thanks! Definitely not "fine" as is, more like functional. :)

**Comment by erikgrinaker** [comment]
> > respect the caller's context cancellation (even though the write itself won't)
> 
> the write can't? I think go supports this via deadlines on the os.File handle.

Yes, but that applies to all writes, not just this one. We'd also have to propagate that through Pebble. Adding deadlines for all Pebble writes is a riskier change than I want to make here.

**Pull request merged**
