### PR TITLE
catalog/lease: avoid using context.Background directly

### PR DESCRIPTION
**Pull request by knz**
First commit from #72651
Informs #58938.

- `(*AmbientContext).AnnotateCtx()` - takes care of connecting the
  context to the tracer
- `logtags.FromContext` / `logtags.WithTags` - reproduces the logging
  tags on the child context.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
@tbg is there some pre-defined API in the stopper that would simplify/automate this pattern?

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72638#-:-MoEBoc7CrlXnDOHp9sq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
No, we don't. Isn't the eventual end point here that we'd lint against use of `context.Background` and make the `Stopper` own the background context? So you would write `s.RunAsyncTask(s.Background(), ...`).

**Comment by knz** [comment]
>  Isn't the eventual end point here that we'd lint against use of context.Background and make the Stopper own the background context?

Something like that, yes.
Before we go there however I want to get more experience with this pattern to see if it fits our other use cases. Once I have a sequence of PRs all doing something similar, I'll track back and do an abstraction.

**Comment by knz** [comment]
TFYR

bors r=ajwerner

**Comment by knz** [comment]
TFYR

bors r=ajwerner

**Pull request merged**
