### PR TITLE
RFCs: Proposal for maintaining leaseholder locality with clients

### PR DESCRIPTION
**Pull request by a-robinson**
This could use some additional input from you guys. I'll think about it more tomorrow, but it feels like it may turn out to be somewhat fragile as currently designed.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13233)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: 

I think we need to brainstorm more about how to incorporate load and latency into the existing lease rebalancing heuristics. As I mention below, there is likely a bunch of experimentation to do here as well. But I think we can get started on some of the mechanism here: tracking inter-{node,locality} latencies, adding `origin_node_id`, etc.

---

Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/RFCS/leaseholder_locality.md, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjYt3PhL_yWJfTYMHx:-KbjYt3PhL_yWJfTYMHy:bpei3np) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L11)):*
> ```Markdown
> 
> Enable range leaseholders to move closer to their clients, which reduces the
> number of round trips needed to serve KV requests.
> ```

The round trips are the same, but the latency of the requests is reduced.

---

*[docs/RFCS/leaseholder_locality.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjZ6OrOZkqg4AVjw9b:-KbjZ6OrOZkqg4AVjw9c:b-51tzv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L22)):*
> ```Markdown
> happens to be halfway around the world from where the request originated, the
> network round trip time that gets added to the request latency by this can be
> quite high.
> ```

Perhaps with elaborating that this affects both reads and writes. The writes still suffer the latency to a quorum of nodes, but you avoid the additional latency of a long round trip to the leaseholder.

---

*[docs/RFCS/leaseholder_locality.md, line 79 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjZ_aVGrX4Q-CuiVP-:-KbjZ_aVGrX4Q-CuiVP0:bbu6mg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L79)):*
> ```Markdown
> `origin_node_id` field that gets filled in by the client kv transport.
> 
> ### Alternatives for tracking request origins
> ```

Add the `origin_node_id` seems like the obvious direction to go.

---

*[docs/RFCS/leaseholder_locality.md, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjZlTOvRIPam3ryalj:-KbjZlTOvRIPam3ryalk:b-b3ad6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L100)):*
> ```Markdown
> ## Recording request origins
> 
> Each leaseholder replica will maintain a map from `NodeID` to the number of
> ```

Perhaps the leaseholder should maintain a map from locality to the number of requests received from that locality. The number of localities should be significantly less than the number of nodes making this more palatable in a larger cluster.

---

*[docs/RFCS/leaseholder_locality.md, line 222 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbj_hWdPZS7WU6OoFZO:-Kbj_hWdPZS7WU6OoFZP:buoue8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L222)):*
> ```Markdown
> making allocation decisions. While we don't currently have this (as far as I'm
> aware), measuring it wouldn't be very hard, so I suggest that we do so and use
> it to help tune lease allocations. We'll have to make sure that this can't lead
> ```

No, we don't have such RTT measurements. We do measure clock skews between nodes. Adding per-node RTT measurement there seems appropriate and the per-node measurements can be folded into inter-localities RTT stats.

@tamird It would be interesting to visualize the inter-{node,locality} RTT on the gossip debug page you've been thinking of.

---

*[docs/RFCS/leaseholder_locality.md, line 270 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjaHPngSmKihfpp6Yg:-KbjaHPngSmKihfpp6Yh:b92bfxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L270)):*
> ```Markdown
>   configurations with the new latency knob.
> * Extending (or forking) `allocsim` to send load against the specific
>   nodes/localities and measure the resulting throughput and latency.
> ```

The intention was for `allocsim` to be extended to allow such testing.

---

*[docs/RFCS/leaseholder_locality.md, line 277 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbjaxj-_FKabJEbPGpm:-Kbjaxj-_FKabJEbPGpn:b2q1e2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L277)):*
> ```Markdown
> find that we have to introduce a tuning knob of some sort to shift the balance
> one way or another. Either way, it's tough for us to know exactly what'll work
> without a testing tool like this.
> ```

I imagine there will be a significant amount of iteration on the heuristic to use during testing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-:-KbjjCMrjbB5kPavcr75:b-57d5in)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 15 unresolved discussions.

---

*[docs/RFCS/leaseholder_locality.md, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbk6-KcesK-EBUaFKmO:-Kbk6-KcesK-EBUaFKmP:b-kjn5l9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L62)):*
> ```Markdown
> In order to have any idea where to rebalance leases to, we first need to track
> where the requests for a given range are coming from. To that end, we can add
> request origin information to the `Header` that's included in all
> ```

We already use ["origin" in the storage layer](https://github.com/cockroachdb/cockroach/blob/4c53128707d07d268833ff5ccb5acee9d8720544/pkg/storage/storagebase/proposer_kv.proto#L115-L134) to refer to the KV node that is proposing the command. Is there another term we could use here? 

---

*[docs/RFCS/leaseholder_locality.md, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjZlTOvRIPam3ryalj:-Kbk74IHH0_LGysy7jLN:bb64izo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L100)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Perhaps the leaseholder should maintain a map from locality to the number of requests received from that locality. The number of localities should be significantly less than the number of nodes making this more palatable in a larger cluster.
</blockquote></details>

Especially since each range (probably) only has one replica per locality. We need to be careful about how much data we keep in memory per replica.

---

*[docs/RFCS/leaseholder_locality.md, line 115 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbk7eveChSr2cbdnzGz:-Kbk7eveChSr2cbdnzH-:b-s7y6eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L115)):*
> ```Markdown
> It's not obvious whether we should count each BatchRequest as a single request
> or if we should instead count the number of non-noop subrequests in each
> BatchRequest. The latter would likely be a better estimate of load, so we can
> ```

The latter is a better approximation of load, but the former is a better approximation of the RTT metric we're trying to optimize.

---

*[docs/RFCS/leaseholder_locality.md, line 151 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbk9IrgFVqrGPXe4Vse:-Kbk9IrgFVqrGPXe4Vsf:bg0t4e0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L151)):*
> ```Markdown
> 
> Of course, there is a risk that moving all the hottest ranges to the same
> locality will could have a worse effect on throughput if those nodes get
> ```

This could be worthwhile for many applications. We're likely going to need to expose some sort of knob for trading off latency vs throughput. 

---

*[docs/RFCS/leaseholder_locality.md, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbkAVUKh-QRkFv_6_lV:-KbkAVULYff9sW1goI55:b-539l7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L206)):*
> ```Markdown
> As mentioned above, our goals in this RFC come into fairly direct conflict with
> the goals of the [lease rebalancing RFC](leaseholder_rebalancing.md). If all the
> requests are coming from a single locality, it would be ideal from a performance
> ```

s/performance/latency/

---

*[docs/RFCS/leaseholder_locality.md, line 210 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbkAcFb6waLdTXiD1Cg:-KbkAcFb6waLdTXiD1Ch:b-ik7exg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L210)):*
> ```Markdown
> overload the nodes with too much work. However, it's possible that putting all
> the leases into that locality will overload the nodes such that overall cluster
> throughput is worse than it would be if the leases were properly balanced.
> ```

In extremely imbalanced cases, it can even be a net negative for latency. 

---

*[docs/RFCS/leaseholder_locality.md, line 292 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbkCquhITCafRSfRfd9:-KbkCquhITCafRSfRfdA:b-26llke) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L292)):*
> ```Markdown
>   node, either as a collection of measurements or as some combination of CPU
>   utilization, memory pressure, and disk I/O utilization. This would make
>   improving locality and balancing load significantly easier and more effective.
> ```

It would also be useful to separate load which is cause by being a lease holder from load which is shared across all replicas (disk writes are generally the same for all replicas, read load falls entirely on the lease holder, etc)

---

*[docs/RFCS/leaseholder_locality.md, line 296 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbkDIIMynoYlESeQKVJ:-KbkDIIMynoYlESeQKVK:bbj8v1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L296)):*
> ```Markdown
> * It's possible that this work will actually be harmful in certain cluster
>   configurations. For example, if a range has two replicas in different parts of
>   Europe and only a single replica in Australia, then it'd typically be better
> ```

This depends on the mix of reads vs writes. Putting the lease in Australia would improve read latency at the expense of writes. If you'd constrain the lease to Europe in this case, why have an Australian replica at all, instead of a third European replica? (the high write performance when the lease is in Europe is somewhat misleading - if one of the European datacenters goes down, write performance will plummet as Australia is added to the critical path. This could lead to cascading failures)

---

*[docs/RFCS/leaseholder_locality.md, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbkE__HmvHhpyVceL0Y:-KbkE__HmvHhpyVceL0Z:b-txr3fq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L305)):*
> ```Markdown
> # Drawbacks
> 
> * This approach does not have any true safeguards against overloading nodes in
> ```

We're going to need to do some sort of flow control to prevent overloading even when leases are balanced across nodes. Once we have that mechanism, we could probably use it here as a limit for load-based lease transfers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-:-KbkES4vkGwpyyyWK42c:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 15 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/leaseholder_locality.md, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjYt3PhL_yWJfTYMHx:-KbkVh602lBx_i7IROZS:b17x5b1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L11)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The round trips are the same, but the latency of the requests is reduced.
</blockquote></details>

Right, I had used "round trips" here to mean cross-locality round trips, which is far from clear. Fixed.

---

*[docs/RFCS/leaseholder_locality.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjZ6OrOZkqg4AVjw9b:-KbkX7a2a5eO3XWlWQVY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L22)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Perhaps with elaborating that this affects both reads and writes. The writes still suffer the latency to a quorum of nodes, but you avoid the additional latency of a long round trip to the leaseholder.
</blockquote></details>

Done.

---

*[docs/RFCS/leaseholder_locality.md, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbk6-KcesK-EBUaFKmO:-KblVEAa-uRhFUAF9Iai:bw2aqdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L62)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We already use ["origin" in the storage layer](https://github.com/cockroachdb/cockroach/blob/4c53128707d07d268833ff5ccb5acee9d8720544/pkg/storage/storagebase/proposer_kv.proto#L115-L134) to refer to the KV node that is proposing the command. Is there another term we could use here? 
</blockquote></details>

It's a shame that isn't referred to as the "proposer", given that origin seems to make more sense for this usage (it's truly where the KV request originated if you exclude the external client). I'm also not sure it needs to be changed given that the context it'll be appearing in (`BatchRequest.header`) should make things fairly clear. What do you think? We could switch to something like `forwarding_node`or `source_node` if the conflict is an issue.

---

*[docs/RFCS/leaseholder_locality.md, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjZlTOvRIPam3ryalj:-KblVSMGylFzCtZWbJwp:b-9loyjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L100)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Especially since each range (probably) only has one replica per locality. We need to be careful about how much data we keep in memory per replica.
</blockquote></details>

I was hoping to avoid the need to do a lookup from node to locality in the serving path of every request, but I suppose a RW mutex on a lookup map would be less overhead than the memory cost otherwise. Done.

---

*[docs/RFCS/leaseholder_locality.md, line 115 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbk7eveChSr2cbdnzGz:-KblVWc8LGHRKYFBqYN-:b8a8f7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L115)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The latter is a better approximation of load, but the former is a better approximation of the RTT metric we're trying to optimize.
</blockquote></details>

You're right, done.

---

*[docs/RFCS/leaseholder_locality.md, line 151 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbk9IrgFVqrGPXe4Vse:-KblVZGsHMcusXwknY7B:bt3p7ew) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L151)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This could be worthwhile for many applications. We're likely going to need to expose some sort of knob for trading off latency vs throughput. 
</blockquote></details>

Yeah, it seems likely. Made a note of that.

---

*[docs/RFCS/leaseholder_locality.md, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbkAVUKh-QRkFv_6_lV:-KblVaBWvNfSzUFcu_BD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L206)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/performance/latency/
</blockquote></details>

Done.

---

*[docs/RFCS/leaseholder_locality.md, line 210 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbkAcFb6waLdTXiD1Cg:-KblVafnvehQTLkNZ8cw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L210)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In extremely imbalanced cases, it can even be a net negative for latency. 
</blockquote></details>

Done.

---

*[docs/RFCS/leaseholder_locality.md, line 270 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjaHPngSmKihfpp6Yg:-KbkYf792SWG3WWb4BSS:b-ml9rs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L270)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The intention was for `allocsim` to be extended to allow such testing.
</blockquote></details>

Ack, removed the reference to forking.

---

*[docs/RFCS/leaseholder_locality.md, line 277 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbjaxj-_FKabJEbPGpm:-KbkZ4p0dtORUfUnEjDA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L277)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I imagine there will be a significant amount of iteration on the heuristic to use during testing. 
</blockquote></details>

Done.

---

*[docs/RFCS/leaseholder_locality.md, line 292 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbkCquhITCafRSfRfd9:-KblW7O5IoiqUYb8y6QV:b2mua1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L292)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It would also be useful to separate load which is cause by being a lease holder from load which is shared across all replicas (disk writes are generally the same for all replicas, read load falls entirely on the lease holder, etc)
</blockquote></details>

Made a note of this.

---

*[docs/RFCS/leaseholder_locality.md, line 296 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbkDIIMynoYlESeQKVJ:-KblWZm6gNOSvcKEjPyk:bbmv7dn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L296)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This depends on the mix of reads vs writes. Putting the lease in Australia would improve read latency at the expense of writes. If you'd constrain the lease to Europe in this case, why have an Australian replica at all, instead of a third European replica? (the high write performance when the lease is in Europe is somewhat misleading - if one of the European datacenters goes down, write performance will plummet as Australia is added to the critical path. This could lead to cascading failures)
</blockquote></details>

Thanks for calling that out, I should have been more specific. I've also called out that this is a bad configuration.

---

*[docs/RFCS/leaseholder_locality.md, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbkE__HmvHhpyVceL0Y:-KblX34wyBiIaaCcTPSi:bb8syyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L305)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We're going to need to do some sort of flow control to prevent overloading even when leases are balanced across nodes. Once we have that mechanism, we could probably use it here as a limit for load-based lease transfers.
</blockquote></details>

Added a sentence about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/leaseholder_locality.md, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbk6-KcesK-EBUaFKmO:-Kbp_LmFAyxosgGqLveO:bbydxge) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L62)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It's a shame that isn't referred to as the "proposer", given that origin seems to make more sense for this usage (it's truly where the KV request originated if you exclude the external client). I'm also not sure it needs to be changed given that the context it'll be appearing in (`BatchRequest.header`) should make things fairly clear. What do you think? We could switch to something like `forwarding_node`or `source_node` if the conflict is an issue.
</blockquote></details>

I don't think `BatchRequest.Header` is far enough away to avoid confusion. But I think it'd be OK to rename the current storage-level use of "origin" to "proposer" and free up "origin" for this use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233)*

**Comment by a-robinson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/leaseholder_locality.md, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbk6-KcesK-EBUaFKmO:-Kbpx1Y5tyomfpeFPuhA:b-1b867a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L62)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think `BatchRequest.Header` is far enough away to avoid confusion. But I think it'd be OK to rename the current storage-level use of "origin" to "proposer" and free up "origin" for this use.
</blockquote></details>

Ok, sent out #13320. Alternatively, I've realized that `gateway_node_id` might actually be more clear than `origin_node_id` anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233)*

**Comment by RaduBerinde** [comment]
:lgtm:

It would be helpful to expose (in the UI) the stats used by the heuristic so when a rebalancing decision happens, it is easy to tell why it happened. This will help improve the heuristics, especially in conditions seen by our users.

---

Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/leaseholder_locality.md, line 79 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-KbjZ_aVGrX4Q-CuiVP-:-KbtyrC4wLgjlA6q-Vqw:berlemi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L79)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Add the `origin_node_id` seems like the obvious direction to go.
</blockquote></details>

+1. To put another nail in the coffin of "rely on IP address", for DistSQL we will be making Batch requests on the leaseholder node, but these requests are "on behalf" of the gateway node. So we will need to set `origin_node_id` to the gateway node, not to the node making the request.

---

*[docs/RFCS/leaseholder_locality.md, line 124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbu3nrP94R5Po9coDkc:-Kbu3nrP94R5Po9coDkd:b-qj4nbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/987ae50ce5ec54c566f2815bc53b1167c0bf88c3/docs/RFCS/leaseholder_locality.md#L124)):*
> ```Markdown
> BatchRequest. The latter would likely be a better estimate of load, but a worse
> measure of the number of requests suffering from high latency round trips, so
> we'll try the former first.
> ```

The number of KVs scanned by the request is probably an even better metric (or a linear combination of the two, `cost of request = 1 + alpha * <numKVs>`).

---

*[docs/RFCS/leaseholder_locality.md, line 227 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbu1WjRXywZJhtb0Y0D:-Kbu1WjRXywZJhtb0Y0E:b-mzfb5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/987ae50ce5ec54c566f2815bc53b1167c0bf88c3/docs/RFCS/leaseholder_locality.md#L227)):*
> ```Markdown
> clear what metric to use for this, though, so for now we will leave it out of
> allocation decisions (suggestions welcome -- perhaps a rather naive load
> measurement can go a long way here).
> ```

You already mentioned keeping track of load per range (which is a good idea). Why do we need another metric? (the load of a node can be simply the sum of the loads of its ranges).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-:-KbtzEVvZQ_p53_oeKgl:bh0cwih)*

**Comment by a-robinson** [comment]
Great point, @raduberinde. Added a point about exposing information in the UI in the future work section and opened #13339.

---

Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/leaseholder_locality.md, line 124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbu3nrP94R5Po9coDkc:-KbuLjq-MWSNX76Lp-TU:b-pi5t83) ([raw file](https://github.com/cockroachdb/cockroach/blob/987ae50ce5ec54c566f2815bc53b1167c0bf88c3/docs/RFCS/leaseholder_locality.md#L124)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The number of KVs scanned by the request is probably an even better metric (or a linear combination of the two, `cost of request = 1 + alpha * <numKVs>`).
</blockquote></details>

I think we're going to end up with separate metrics for the requests to and load on a replica. As @bdarnell noted, the amount of work done to serve the request isn't what we really care about when optimizing for latency network. The number of requests that suffer from the RTT is the more important metric.

---

*[docs/RFCS/leaseholder_locality.md, line 227 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbu1WjRXywZJhtb0Y0D:-KbuMfDiw7lh4Xiw9WGj:b-am5ao9) ([raw file](https://github.com/cockroachdb/cockroach/blob/987ae50ce5ec54c566f2815bc53b1167c0bf88c3/docs/RFCS/leaseholder_locality.md#L227)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

You already mentioned keeping track of load per range (which is a good idea). Why do we need another metric? (the load of a node can be simply the sum of the loads of its ranges).
</blockquote></details>

Sorry for the lack of clarity here. I mean load percentage or utilization percentage, not a raw load number. Loading nodes close to where the requests are coming from is a good thing so long as we aren't overloading them to the point of performance degradation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-:-KbuNVwD0VYrJ_cY1Isy:bx8jnur)*

**Comment by bdarnell** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/leaseholder_locality.md, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbk6-KcesK-EBUaFKmO:-KbvB5JEGZuQVjhDzT5X:b-ydpla6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L62)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Ok, sent out #13320. Alternatively, I've realized that `gateway_node_id` might actually be more clear than `origin_node_id` anyway.
</blockquote></details>

Yeah, "gateway" works too. Maybe we should use that and reserve "origin" to refer to the external-to-cockroach client (when/if we have the ability to do anything useful with that)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233)*

**Comment by a-robinson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[docs/RFCS/leaseholder_locality.md, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-Kbk6-KcesK-EBUaFKmO:-KbvFduHPPJBbz1Aayqx:b-5fk6y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada0c24f457a6536eec558d6c13836c3253e9766/docs/RFCS/leaseholder_locality.md#L62)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, "gateway" works too. Maybe we should use that and reserve "origin" to refer to the external-to-cockroach client (when/if we have the ability to do anything useful with that)
</blockquote></details>

Yeah, I think so too. I've been using gateway in my separate branch where I'm implementing some of this, so now I've switched this text too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233)*

**Comment by andreimatei** [comment]
Sorry for being late to this party.
I think two things should at least be mentioned somewhere:

1. how does (or doesn't) the desire for leases to handle the sun deal with the situation where a range doesn't have any replicas in the desired locality?
2. we should have a mention of DistSQL in the text somewhere saying that DistSQL can "spoof" the origin of a KV batch request

---

Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13233#-:-KcJ_5hQVXjC2ddwE50r:b-7yd3oc)*

**Pull request merged**
