### PR TITLE
settings: add change callbacks

### PR DESCRIPTION
**Pull request by dt**
First commit is a refactor to the settings registry to invert wrapping/embedding of the common helpers (previously `wrappedSetting`) and the individual concrete impls.

My kingdom for generics in the second commit -- having to override the common helper just to return the concrete impl type is kinda gross.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice! :lgtm:

---

Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/settings/bool.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-KlPyIjEjJAchcB0s5L5:-KlPyIjF1GcFwzEljAGl:b-2v8wzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b4e1e5739d419551127df0baa64011d7ed6052/pkg/settings/bool.go#L27)):*
> ```Go
> 	defaultValue bool
> 	v            int32
> 	common
> ```

[nit] we usually put the embedded fields first

---

*[pkg/settings/bool.go, line 89 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-KlPyV6ooO06F09GRKXJ:-KlPyV6ooO06F09GRKXK:b49irib) ([raw file](https://github.com/cockroachdb/cockroach/blob/280ab6504e701ef2aa75fbf2528d08aa71cb672a/pkg/settings/bool.go#L89)):*
> ```Go
> 
> // OnChange registers a callback to be called when the setting changes.
> // This overrides the `common`` impl to return the concrete impl type.
> ```

I would remove the second sentence (this comment is of interest to the external user of this package which doesn't need to know what 'common' is).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-:-KlPyvYLuqoUdD94DiH0:be8rotp)*

**Comment by dt** [comment]
@RaduBerinde this looks pretty similar to your approach in #16215 with a couple differences:
1) I went ahead and pulled all the common functionality that was in `wrappedSetting` into the embedded common helper.
2) I only allowed up-to-one callback.
3) I went with a chainable-pattern to add callbacks, at the expense of some gross repeated overloads (i miss generics sometimes)
4) I didn't use atomic swaps -- there's only one writer thread calling `update`, so it probably doesn't matter.

**Comment by RaduBerinde** [comment]
Yes, I agree this is better.
The atomic swaps weren't adding any semantic guarantees, this should be fine.

**Comment by dt** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/settings/bool.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-KlPyIjEjJAchcB0s5L5:-KlPzHkf2Mdvc_SZndGD:b-6uwjq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b4e1e5739d419551127df0baa64011d7ed6052/pkg/settings/bool.go#L27)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] we usually put the embedded fields first
</blockquote></details>

Done.

Though, since, field order affects memory layout and alignment, IIRC you are always supposed to put anything to which you want to have atomic access first since structs themselves are always aligned but there contents is not ensured to be... so really `v` should come first?

---

*[pkg/settings/bool.go, line 89 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-KlPyV6ooO06F09GRKXJ:-KlQ-JM9-vmBtvzFaXOZ:b-9ryhzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/280ab6504e701ef2aa75fbf2528d08aa71cb672a/pkg/settings/bool.go#L89)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would remove the second sentence (this comment is of interest to the external user of this package which doesn't need to know what 'common' is).
</blockquote></details>

well, the `OnChange` method on `common` that this is overriding is exported too, but fair enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214)*

**Comment by BramGruneir** [comment]
:lgtm:  Thanks for adding these!

---

Reviewed 15 of 15 files at r1, 2 of 9 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-:-KlQ1qsdAULHCkORfJBa:b-4zxu3k)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/settings/bool.go, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-KlPyIjEjJAchcB0s5L5:-KlQ1Vw2oUNsaZepougV:b-k3hpwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b4e1e5739d419551127df0baa64011d7ed6052/pkg/settings/bool.go#L27)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done.

Though, since, field order affects memory layout and alignment, IIRC you are always supposed to put anything to which you want to have atomic access first since structs themselves are always aligned but there contents is not ensured to be... so really `v` should come first?
</blockquote></details>

Good point. Structs are padded so I don't think `common` can cause misalignment, but also ok to put `v` first (with a comment).

---

*[pkg/settings/bool.go, line 89 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-KlPyV6ooO06F09GRKXJ:-KlQ0nPoVp2tmzghfA9G:b56n885) ([raw file](https://github.com/cockroachdb/cockroach/blob/280ab6504e701ef2aa75fbf2528d08aa71cb672a/pkg/settings/bool.go#L89)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

well, the `OnChange` method on `common` that this is overriding is exported too, but fair enough.
</blockquote></details>

Why is `common.OnChange` also exported? I don't see how an external user would be able to call it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/settings/bool.go, line 89 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-KlPyV6ooO06F09GRKXJ:-KlQ2hgTBmeqRNJJhJ9s:b-746xzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/280ab6504e701ef2aa75fbf2528d08aa71cb672a/pkg/settings/bool.go#L89)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why is `common.OnChange` also exported? I don't see how an external user would be able to call it.
</blockquote></details>

If a Setting impl ever doesn't override it to provide one with a chain-able return type, it's fine to use it directly, -- it'd just look more like the `.Hide()` calls, where you just need some sort of block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/settings/bool.go, line 89 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-KlPyV6ooO06F09GRKXJ:-KlQ46c7lEjbdiUN-BD8:b-9psdi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/280ab6504e701ef2aa75fbf2528d08aa71cb672a/pkg/settings/bool.go#L89)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

If a Setting impl ever doesn't override it to provide one with a chain-able return type, it's fine to use it directly, -- it'd just look more like the `.Hide()` calls, where you just need some sort of block.
</blockquote></details>

Meh, they should all use the same pattern. If a future setting misses `OnChange()` and someone needs to call it, they should have to add the function rather than having the option of using one with a different signature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214)*

**Comment by knz** [comment]
The 2nd commit seems logically incorrect. There's a race condition.
If you want the proper behavior you'd need to use `atomic.Swap*` instead of separate load/store calls.
Otherwise I must require that you extend the commit message and the documentation for the onchange helper to explain/highlight that the user should not expect reliable change notifications.

The rest LGTM

---

Reviewed 15 of 15 files at r1, 8 of 9 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-:-KlQ6JSfJMAazOmZaLZ0:b-54hae7)*

**Comment by dt** [comment]
@knz: there's only one updater thread per server.

---

Review status: 9 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/settings/bool.go, line 89 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-KlPyV6ooO06F09GRKXJ:-KlQBG_IwgE_brVuxuVc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/280ab6504e701ef2aa75fbf2528d08aa71cb672a/pkg/settings/bool.go#L89)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Meh, they should all use the same pattern. If a future setting misses `OnChange()` and someone needs to call it, they should have to add the function rather than having the option of using one with a different signature.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-:-KlQ7157ZgBqHro04pQ2:be0hesl)*

**Comment by RaduBerinde** [comment]
How do you define "reliable change notifications"? It always fires on changes so it is reliable in that sense. With respect to spurious calls - even with atomic swaps, if there were multiple threads, the option could change back before the callback gets to run so we can't guarantee that the value is actually different when the callback runs.

---

Review status: 9 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-:-KlQD_FbDLLQOQqe255I:b-chkio8)*

**Comment by dt** [comment]
@knz: I switched it to use `atomic.Swap*` since, even though I'm pretty sure it is a non-issue in practice (there's only one thread calling `set` in any given server), it's easier just to make it obviously correct, even if its slower, than explain why its correct anyway. RFAL.

---

Review status: 9 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-:-KlQpKmRXI8mheCwWETV:b-ntmlt0)*

**Comment by knz** [comment]
My apologies for the late reaction. :lgtm_strong: 

---

Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16214#-:-KlR8d0hwfmjUlX2laNq:b-qzu64f)*

**Pull request merged**
