### PR TITLE
ui: Node List view redesign

### PR DESCRIPTION
**Pull request by koorosh**
Changes for node list mostly related to the usage of the Table component from And design system.
Following reusable components are added:
- Table: is a styled wrapper for and design table component
- TableSection: responsible for displaying table header and footer and allowing expand/collapse section with a table.
- Tooltip: also a styled wrapper around ant design Tooltip component

The layout of Cluster Overview page is changed to improve correct behavior for fixed and UI elements and those which have to be scrollable.

Cluster Overview section header is removed to comply with the next changes related to the redesign of Navigation panel and adding a separate section with section name.

Screenshot 2019-12-30 at 10 17 19

Screenshot 2019-12-30 at 10 17 30

### CODE REVIEW

**Comment by knz** [comment]
@Koorosh this change is awesome. However this is a large-ish project and it partially overlaps with some other release plans we may have.

@piyush-singh can you look at the description of the proposed approach above? I think it solves many woes we have seen reported throughout the last year. I do not recall whether we already had plans to redesign this and/or where these other plans are being executed. If you think the contributor's proposal is acceptable, please let us know.

**Comment by piyush-singh** [comment]
@knz this PR was actually opened by one of our contractors on the Observability team! We're coordinating updates to the UI :)

**Comment by Koorosh** [comment]
PR is extended with following changes: 
Node List / Node Map switcher has to be redesigned according to design-system styles. 
- Button, and Dropdown components are added to design-system;

**Review by dhartunian — APPROVED** [review]

**Pull request merged**
