### PR TITLE
kv: remove unused RETRY_POSSIBLE_REPLAY

### PR DESCRIPTION
**Pull request by andreimatei**
This reason for TransactionRestartError has been unused for a while.
Removing it and the associated metric.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Did you mean to name this PR and commit "remove unused RETRY_POSSIBLE_REPLAY"?

> Reviewed 1 of 1 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43117#-:-LvquvhC6y33PojYdZH7:b-qfdph1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/roachpb/errors.proto, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43117#-Lvqv201CxRX4lMFNURP:-Lvqv201CxRX4lMFNURQ:b30b3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7fe53099030b1f5f02776ba89e6c0883325083d/pkg/roachpb/errors.proto#L195)):*
> ```protobuf
>   // A concurrent writer finished first, causing restart.
>   RETRY_WRITE_TOO_OLD = 1;
>   reserved 2;
> ```

Why are we getting rid of reserved variants?
___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43117#-Lvqv7sn4MZXb2ZjpGvB:-Lvqv7sn4MZXb2ZjpGvC:bjpdv63) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7fe53099030b1f5f02776ba89e6c0883325083d/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx#L58)):*
> ```XML
>         <Metric name="cr.node.txn.restarts.writetoooldmulti" title="Write Too Old (multiple)" nonNegativeRate />
>         <Metric name="cr.node.txn.restarts.serializable" title="Forwarded Timestamp (iso=serializable)" nonNegativeRate />
>         <Metric name="cr.node.txn.restarts.possiblereplay" title="Possible Replay" nonNegativeRate />
> ```

We don't expose this in the UI, do we?

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43117)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43117#-Lvqv7sn4MZXb2ZjpGvB:-LwEgiM73HsVRncUUbfs:bv8ldyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7fe53099030b1f5f02776ba89e6c0883325083d/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx#L58)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We don't expose this in the UI, do we?
</blockquote></details>

@nvanbenschoten You'd see it on the Node-specific "Distributed" graph as one of the lines under KV Transaction Restarts

**Review by andreimatei — COMMENTED** [review]
> Did you mean to name this PR and commit "remove unused RETRY_POSSIBLE_REPLAY"?

Yes, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43117#-:-Lx7slzd5cT2GCzaoR8i:brrwbsu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/errors.proto, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43117#-Lvqv201CxRX4lMFNURP:-Lx7pOoi0wePmHC-k1LG:b-lb9ew3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7fe53099030b1f5f02776ba89e6c0883325083d/pkg/roachpb/errors.proto#L195)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why are we getting rid of reserved variants?
</blockquote></details>

Because they're not needed. We don't save these protos anywhere.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r3, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43117#-:-Lx8I1eR1eTvXpytmYxU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/roachpb/errors.proto, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43117#-Lvqv201CxRX4lMFNURP:-Lx8HnGhEZCITj3xZsV3:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7fe53099030b1f5f02776ba89e6c0883325083d/pkg/roachpb/errors.proto#L195)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Because they're not needed. We don't save these protos anywhere.
</blockquote></details>

Ack.
___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43117#-Lvqv7sn4MZXb2ZjpGvB:-Lx8Hy1k33l__wRWsjAQ:bcr5s31) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7fe53099030b1f5f02776ba89e6c0883325083d/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx#L58)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

@nvanbenschoten You'd see it on the Node-specific "Distributed" graph as one of the lines under KV Transaction Restarts



</blockquote></details>

Got it, thanks.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43117#-:-LxDGEJzEAoSaXiu-6kR:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

**Pull request merged**
