### PR TITLE
server/debug: expose panicparse's UI at /debug/pprof/goroutineui

### PR DESCRIPTION
**Pull request by tbg**
All but last commit is https://github.com/cockroachdb/cockroach/pull/35147.

----

[panicparse] is a nifty tool that preprocesses goroutine dumps with the
goal of making them more digestible. To do so, it groups "similar" stacks
and tries to highlight system vs user code.

The grouping in particular is helpful since the situations in which we
stare at goroutine dumps are often the same situations in which there are
tons of goroutines all over the place. And even in a happy cluster, our
thread pools show up with high multiplicity and occupy enormous amounts of
terminal real estate.

The UI sets some defaults that are hopefully sane. First, it won't try to
let panicparse rummage through the source files to improve the display of
arguments, as the source files won't be available in prod
(and trying to find them pp will log annoying messages). Second, we operate
at the most lenient similarity where two stack frames are considered
"similar" no matter what the arguments to the method are. This groups most
aggressively which I think is what we want, though if we find out otherwise
it's always easy to download the raw dump and to use panicparse locally.
Or, of course, we can plumb a GET parameter that lets you chose the
similarity strategy.

[panicparse]: https://github.com/maruel/panicparse/

Here's a sample:

image

Release note (admin ui change): Provide a colorized and aggregate overview over
the active goroutines (at /debug/pprof/goroutineui), useful for internal
debugging.

### CODE REVIEW

**Comment by tbg** [comment]
PS @jordanlewis I have a WIP change that tags some of our standard goroutines so that they show up last when sorting by blocked-duration. But it's invasive enough to polish and send out separately later.

**Comment by tbg** [comment]
Friendly ping, @jordanlewis.

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35148#-:-LZeBpCEAvxFAyKbGJRZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @tbg)

___
*[pkg/server/debug/goroutineui/dump.go, line 33 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35148#-LZeAokaBMScUdmPfaYj:-LZeAokaBMScUdmPfaYk:b-b1dteo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d7ca0ffa5f55fd5121bb2c50ee03724e181dc07/pkg/server/debug/goroutineui/dump.go#L33)):*
> ```Go
> 	// We don't know how big the traces are, so grow a few times if they don't fit. Start large, though.
> 	var trace []byte
> 	for n := 1 << 20; /* 1mb */ n <= (1 << 29); /* 512mb */ n *= 2 {
> ```

512 mb seems giant, but maybe this really does happen in practice?

**Comment by tbg** [comment]
TFTR!

I hope we won't see 512mb in practice, but one user has repeatedly seen 500k goroutines due to some fast-acting leak. It's unclear that this endpoint will do anything but kill the server in that case anyway, though. I'm open to changing that limit, but will merge for now.

bors r=jordanlewis

**Pull request merged**
