### PR TITLE
sqlmigrations: remove 19.2 -> 20.1 schema change migration

### PR DESCRIPTION
**Pull request by thoszhang**
This commit removes the async migration that upgrades schema change jobs
started prior to 20.1, and other related logic no longer relevant for
20.2. This is in anticipation of marking all remaining pre-20.1 jobs as
failed during a startup migration for 20.2. The prohibition on adopting
jobs with an older format version remains.

Release note (general change): As part of the transition to 20.2, the
migration to upgrade schema change jobs started prior to 20.1 is no
longer run.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

**Review by pbardea — APPROVED** [review]

**Comment by lucy-zhang** [comment]
bors r-

This is hitting #53000.

**Comment by lucy-zhang** [comment]
???

bors r+

**Pull request merged**
