### PR TITLE
sql: allow for primary key dropping if alter primary key is present

### PR DESCRIPTION
**Pull request by rohany**
This PR allows for primary keys to be dropped and added, given
that the drop and add are within the same transaction.

For example, the two commands below are now valid to execute
to change the primary key of a table _without_ causing a rewrite
of the old primary index (which the `ALTER PRIMARY KEY` command does).

```
ALTER TABLE t DROP CONSTRAINT "primary", ADD CONSTRAINT "primary" PRIMARY KEY (x)
```
and
```
BEGIN;
  ALTER TABLE t DROP CONSTRAINT "primary";
  ALTER TABLE t ADD CONSTRAINT "primary" PRIMARY KEY (x);
COMMIT;
```

This PR disallows use of `DROP CONSTRAINT "primary"` without
a following `ADD PRIMARY KEY` within the same transaction. Additionally,
`ADD PRIMARY KEY` is not permitted if it is not preceted by a
`DROP CONSTRAINT "primary"` within the same transaction.

Release note (sql change): This PR allows for users to drop their
primary keys as long as they add another primary key within the same
transaction. This feature is intended to be used when users do not
want the existing primary key to be rewritten as a secondary index
by `ALTER PRIMARY KEY`.

### CODE REVIEW

**Comment by rohany** [comment]
This is a draft PR (with a good amount of holes), but I wanted to get some initial feedback on the approach before polishing up the PR. 

This PR supports the following right now:

```
CREATE TABLE t (x INT PRIMARY KEY, y INT NOT NULL);

ALTER TABLE t DROP CONSTRAINT "primary"; -- this will error out

BEGIN TRANSACTION
  ALTER TABLE t DROP CONSTRAINT "primary";
  ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (x, y)
COMMIT -- this will succeed.

BEGIN TRANSACTION
  ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (x, y)
  ALTER TABLE t DROP CONSTRAINT "primary";
COMMIT -- this will error.

ALTER TABLE t DROP CONSTRAINT "primary", ALTER PRIMARY KEY USING COLUMNS (x, y); -- this will succeed

ALTER TABLE t  ALTER PRIMARY KEY USING COLUMNS (x, y), DROP CONSTRAINT "primary"; -- this will not
```

If this looks like behavior we want, I'll then also add the `ADD CONSTRAINT "primary" (...)` syntax.

**Comment by wzrdtales** [comment]
looking forward to this, recreating the whole table b/c of primaryKey changes is a bit much.

**Comment by knz** [comment]
let me know when/if you want me to have a look too

**Comment by rohany** [comment]
This is ready for a look, I cleaned up the various rough edges in the original draft.

**Review by solongordon — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44511)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @lucy-zhang, and @rohany)

___
*[pkg/sql/alter_table.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kh7YQCM00ggmi3GGI:-M-kh7YQCM00ggmi3GGJ:badjqw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L108)):*
> ```Go
> 	var droppedViews []string
> 	tn := params.p.ResolvedName(n.n.Table)
> 	for i := 0; i < len(n.n.Cmds); i++ {
> ```

Nit: Could also just write `for i := range n.n.Cmds`
___
*[pkg/sql/alter_table.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-khLYV-8vxswxFw2ig:-M-khLYV-8vxswxFw2ih:b-enwsp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L207)):*
> ```Go
> 					// If a primary key was requested to be added, insert an AlterPrimaryKey statement
> 					// to be processed after this constraint addition. However, only succeed if the primary key
> 					// has been dropped before this command.
> ```

Nit: Wrap comments at 80 chars please
___
*[pkg/sql/alter_table.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kkhM-EF2j7FCAflPi:-M-kkhM-EF2j7FCAflPj:b-tpbaqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L215)):*
> ```Go
> 						}
> 					}
> 					if !foundDropPK {
> ```

It would be nice to also support this if the table didn't have a primary key to begin with, i.e. it's using the hidden `rowid` key. Feel free to do this in a separate PR though.
___
*[pkg/sql/alter_table.go, line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kkS2m00uusWrhPgFH:-M-kkS2m00uusWrhPgFI:b-jwlujv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L217)):*
> ```Go
> 					if !foundDropPK {
> 						return errors.Errorf(
> 							"cannot add primary key to table %s without preceding drop of primary key", n.tableDesc.Name)
> ```

I like the Postgres error better: `"multiple primary keys for table %s are not allowed"` (with the invalid_table_definition pgcode)
___
*[pkg/sql/alter_table.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kmeDE5A_G_QFiPiTY:-M-kmeDE5A_G_QFiPiTZ:bgxk439) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L223)):*
> ```Go
> 						Interleave: d.Interleave,
> 					}
> 					// Slice n.n.Cmds to capacity i+1 to avoid the addition of alterPK overwriting other commands in the slice.
> ```

Nit: long comment
___
*[pkg/sql/alter_table.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-km3feApAWUw7Jkt2n:-M-km3feApAWUw7Jkt2o:b-du2qnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L224)):*
> ```Go
> 					}
> 					// Slice n.n.Cmds to capacity i+1 to avoid the addition of alterPK overwriting other commands in the slice.
> 					n.n.Cmds = append(append(n.n.Cmds[:i+1:i+1], alterPK), n.n.Cmds[i+1:]...)
> ```

May I recommend this instead?
```
n.n.Cmds = append(n.n.Cmds, nil)
copy(n.n.Cmds[i+1:], n.n.Cmds[i:])
n.n.Cmds[i] = alterPK
```
I think it's both more straightforward and more efficient.
___
*[pkg/sql/alter_table.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kpWyB8080J1v7u7k0:-M-kpWyB8080J1v7u7k1:bo9zxtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L417)):*
> ```Go
> 			}
> 
> 			foundDropPK := false
> ```

Could you add a comment to the effect that we don't rebuild the former primary key as a secondary index if the primary key was dropped earlier in the transaction?
___
*[pkg/sql/schema_changer.go, line 1953 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kqDc1-EBrsXnhLnKS:-M-kqDc1-EBrsXnhLnKT:b-lz6ln0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/schema_changer.go#L1953)):*
> ```Go
> // mutation then the DROP PRIMARY KEY mutation is enclosed by an ADD PRIMARY KEY mutation.
> // This is validated before txn commit to ensure that there are no tables in a state
> // without a primary key.
> ```

Nit: Long comment lines

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44511)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @lucy-zhang, and @solongordon)

___
*[pkg/sql/alter_table.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kh7YQCM00ggmi3GGI:-M-l8qKW13pdid_5DUAM:b-arh7si) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L108)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: Could also just write `for i := range n.n.Cmds`
</blockquote></details>

I'm not sure if that works if the list being iterated over is changing.
___
*[pkg/sql/alter_table.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kkhM-EF2j7FCAflPi:-M-lGGHBE_CQYe1bGg_F:by04gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L215)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

It would be nice to also support this if the table didn't have a primary key to begin with, i.e. it's using the hidden `rowid` key. Feel free to do this in a separate PR though.
</blockquote></details>

I see -- that could be neat. I'll do that in a follow up PR for sure though.
___
*[pkg/sql/alter_table.go, line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kkS2m00uusWrhPgFH:-M-lG2PBDqKJ81mdCi3u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L217)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I like the Postgres error better: `"multiple primary keys for table %s are not allowed"` (with the invalid_table_definition pgcode)
</blockquote></details>

Done.
___
*[pkg/sql/alter_table.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-km3feApAWUw7Jkt2n:-M-lFLYa-QLsOnzcgGxN:byp8qzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L224)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

May I recommend this instead?
```
n.n.Cmds = append(n.n.Cmds, nil)
copy(n.n.Cmds[i+1:], n.n.Cmds[i:])
n.n.Cmds[i] = alterPK
```
I think it's both more straightforward and more efficient.
</blockquote></details>

I did something else to clean it up -- i don't find the copying very clear.
___
*[pkg/sql/alter_table.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kpWyB8080J1v7u7k0:-M-lDkqo2Bwm7DmQGJ-C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L417)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Could you add a comment to the effect that we don't rebuild the former primary key as a secondary index if the primary key was dropped earlier in the transaction?
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 1953 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kqDc1-EBrsXnhLnKS:-M-lCfqn5U5wZEQsfNCX:bqd3kvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/schema_changer.go#L1953)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: Long comment lines
</blockquote></details>

ah i didn't know htere was a different line length for code and comments.

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44511)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @lucy-zhang, and @solongordon)

___
*[pkg/sql/alter_table.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-kh7YQCM00ggmi3GGI:-M-oqLC97OhvhiU0D3S1:bdcv6l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L108)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I'm not sure if that works if the list being iterated over is changing.
</blockquote></details>

Good point.
___
*[pkg/sql/alter_table.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-km3feApAWUw7Jkt2n:-M-oq_8r8ae8QlPp2yTE:b-2hh0yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c65d10b91eae61a61d0f16343074e55b0053580/pkg/sql/alter_table.go#L224)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I did something else to clean it up -- i don't find the copying very clear.
</blockquote></details>

That's fair, though note that it's one of the standard "slice tricks": https://github.com/golang/go/wiki/SliceTricks

If you're going to use your new approach you might as well allocate `newCmds` with an initial capacity of `len(n.n.Cmds) + 1`.

**Comment by rohany** [comment]
@knz can you take a quick look as well?

**Review by knz — CHANGES_REQUESTED** [review]
nit: commit msg: "preceted" -> "preceded"

I have a few more nits on the code, nothing major, see below.

A question however: how much is allowed *between* the DROP CONSTRAINT and the ADD CONSTRAINT?

I can do (theoretically):
```
ALTER TABLE x
   DROP CONSTRAINT "primary",
   ADD COLUMN xxx ...,
   DROP CONTRAINT "otherconstraint",
   ... more table commands here ...
   ADD CONSTRAINT "primary" ...
```

Are all the table commands allowed in-between? Are there restrictions?
In either case (everything is allowed or there are restrictions):
- this needs to be explained in the PR rescription  to help the doc writer
- there needs to be some unit tests with combinations table commands in-between

Also:

```
BEGIN;
ALTER TABLE x DROP CONSTRAINT "primary";
SELECT * FROM x;
ALTER TABLE x ADD CONSTRAINT "primary" ...
```

Does this SELECT make sense? Do we want to allow anything that queries a table without a PK?
If it makes sense, what are clients expected to see? What if they do CREATE INDEX in-between?
If there are restrictions, where are these restrictions implemented?

In any case (restrictions or not) where are the unit test that do stuff "in-between"?

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-:-M-vL1P23O5F8QFCUhTo:brd7q43)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @rohany)

___
*[pkg/sql/alter_table.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vLKG0A6fI9gM79rgU:-M-vLKG0A6fI9gM79rgV:bisu6vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/alter_table.go#L111)):*
> ```Go
> 	tn := params.p.ResolvedName(n.n.Table)
> 
> 	for i := 0; i < len(n.n.Cmds); i++ {
> ```

```go
  for i := range n.n.Cmds {
      cmd := n.n.Cmds[i]
```

(maybe `cmd := &n.n.Cmds[i]`? if it's not mutated in-place that will avoid you a heap alloc)
___
*[pkg/sql/alter_table.go, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vL_7B4dO7nyIEIbc5:-M-vL_7B4dO7nyIEIbc6:bwigzux) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/alter_table.go#L228)):*
> ```Go
> 					}
> 					if !foundDropPK {
> 						return errors.Errorf("multiple primary keys for table %s are not allowed", n.tableDesc.Name)
> ```

`pgerror.Newf` with sqlstate 42P16 please (look up which one it is in `pgcode` first)

```
kena=> alter table t add constraint q primary key(x);
ERROR:  multiple primary keys for table "t" are not allowed
kena=> \errverbose
ERROR:  42P16: multiple primary keys for table "t" are not allowed
LOCATION:  index_check_primary_key, index.c:234
```
___
*[pkg/sql/alter_table.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vLrx71Ldsbape3MBJ:-M-vLrx71Ldsbape3MBK:b-tzv67a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/alter_table.go#L236)):*
> ```Go
> 
> 					// Move n.n.Cmds into a new array to avoid overwriting existing commands.
> 					newCmds := make(tree.AlterTableCmds, 0, len(n.n.Cmds)+1)
> ```

only create a new array if a copy was not done before. Here's the Go idiom:

```go
sliceCopy := yourslice
copied := false
for i := range yourslice {
   curElem := sliceCopy[i]
   ...
   if .... {
         // need to overwrite the elem here.
         if !copied {
             sliceCopy = append([]xxx, sliceCopy...)
             copied = true
         }
         sliceCopy[i] = newvalue
    }

}
```
___
*[pkg/sql/create_table.go, line 1383 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vMWsy-TFJ4xz8kEIm:-M-vMWsy-TFJ4xz8kEIn:bhegble) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/create_table.go#L1383)):*
> ```Go
> 			if d.PrimaryKey {
> 				if d.Interleave != nil {
> 					return desc, errors.New("interleave not supported in primary key constraint definition")
> ```

add some pgcode in here thanks
___
*[pkg/sql/schema_changer.go, line 1952 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vMTM76yRtCBCj2yt4:-M-vMTM76yRtCBCj2yt5:b3buklo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/schema_changer.go#L1952)):*
> ```Go
> 
> // validateTablePrimaryKeys ensures that if this schema changer points to a
> // DROP PRIMARY KEY mutation then the DROP PRIMARY KEY mutation is enclosed
> ```

"enclosed" seems suspicious. Statements don't "enclose" each other.
___
*[pkg/sql/sqlbase/structured.go, line 2654 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vMaxtBD711q6EDWQC:-M-vMaxtBD711q6EDWQD:b-tn5eat) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/sqlbase/structured.go#L2654)):*
> ```Go
> 		for _, mut := range desc.Mutations {
> 			if mut.MutationID == currentMutationID && mut.GetDropPrimaryKey() != nil {
> 				return errors.New("cannot drop the primary key of a table multiple times in a transaction")
> ```

`return unimplemented.XXX(...)`

**Comment by rohany** [comment]
> A question however: how much is allowed between the DROP CONSTRAINT and the ADD CONSTRAINT?

For DDLs at least, we're considering disallowing any other schema change operations preceeding an alter primary key anyway, so we might not have to worry about this.

RE the select in the middle -- thats a great question... I feel like we should really disallow anything other than DROP PRIMARY KEY followed by an ADD PRIMARY KEY. If we view DROP PRIMARY KEY as really dropping the primary key of the table, then the state following DROP PRIMARY KEY is not valid for anything to take place other than an ADD PRIMARY KEY, though I'm not sure how to validate this. However, if we view DROP PRIMARY KEY as simply setting a flag in the transaction for ALTER PRIMARY KEY to not rebuild a primary index, then all sorts of statements are allowed and will behave normally between the two statements.

**Comment by knz** [comment]
> For DDLs at least, we're considering disallowing any other schema change operations preceeding an alter primary key anyway, so we might not have to worry about this.

Works for me! but then make this happen and add the tests :)

> RE the select in the middle -- thats a great question... I feel like we should really disallow anything other than DROP PRIMARY KEY followed by an ADD PRIMARY KEY.

That makes sense to me. Then you can do that and also add those tests.

> If we view DROP PRIMARY KEY as really dropping the primary key of the table, then the state following DROP PRIMARY KEY is not valid for anything to take place other than an ADD PRIMARY KEY

yep I agree with this interpretation.

> if we view DROP PRIMARY KEY as simply setting a flag in the transaction for ALTER PRIMARY KEY to not rebuild a primary index, then all sorts of statements are allowed and will behave normally between the two statements.

That seems complicated to explain to a user in docs. The restriction above is both simpler to implement and to document.

**Comment by rohany** [comment]
Coming back to this (its been some time!)

I'm having a some trouble coming up with a good implementation of these semantics:

"If we view DROP PRIMARY KEY as really dropping the primary key of the table, then the state following DROP PRIMARY KEY is not valid for anything to take place other than an ADD PRIMARY KEY"

Given the variety of ways of accessing tables (by name, by id, with/without cache), there doesn't seem like a good place to check "does the descriptor i read have a primary key" without introducing special cases at numerous places in the code. How we enforce that there are not any DML statements followed by DDL statements doesn't seem to be applicable in this case either. 

> That seems complicated to explain to a user in docs. The restriction above is both simpler to implement and to document.

I was wondering what you had in mind that made this idea simpler to implement (i agree it is easier to document).

> if we view DROP PRIMARY KEY as simply setting a flag in the transaction for ALTER PRIMARY KEY to not rebuild a primary index, then all sorts of statements are allowed and will behave normally between the two statements.

This is much simpler to implement, or rather nothing really needs to change to allow this.

**Comment by awoods187** [comment]
Whats the downside of the later approach?

**Comment by knz** [comment]
If that's ok I'd like to pick this up on Monday when I am back.

**Comment by rohany** [comment]
of course! please enjoy your time off

**Review by knz — COMMENTED** [review]
So the main issue I have is the following: after DROP CONSTRAINT "primary", the primary index is supposed to **not exist** any more.

If we do what you say then the primary index is in a zombie state, being both living (for query planning, EXPLAIN and possibly some pg_catalog/info_schema requests) and dead (for further DDL, and possibly some other pg_catalog/info_schema requests).

I am not very keen on release a database product that delivers zombie abstractions as a matter of course. The task to document zombie abstractions properly is an act of advanced necromancy and I would not wish it on my worst enemy.

So I'd like to do as much homework as humanely possible to avoid releasing a product for necromancers.

As to how to get there. I can see several strategies:

- adding a boolean "disabled" on index descriptors and have every loop / comparison over index descriptors ignore "disabled" indexes
- adding a boolean "PrmaryIndexDisabled" on the `MutableTableDescriptor` in the tablecollection, and make any  statement (both DDL and non-DDL) fail planning altogether when it attempts to use/access a table with that boolean set, *except* the `ADD CONSTRAINT "primary"` DDL specifically

We can schedule some time together this week to explore options if you don't feel inspired by the above.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-:-M1RE4gm4mv_n1nLPT1I:b72pres)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @rohany)

**Review by knz — COMMENTED** [review]
I also observe I still have reviewble comments open on this PR. As far as I can see they are still relevant.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-:-M1RFppA5MtKkVMl04bV:bi2hcmc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @rohany)

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44511)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @lucy-zhang, and @rohany)

___
*[pkg/sql/alter_table.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vLKG0A6fI9gM79rgU:-M1SO0dZ5wTuqaTqvBMu:bngsi7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/alter_table.go#L111)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

```go
  for i := range n.n.Cmds {
      cmd := n.n.Cmds[i]
```

(maybe `cmd := &n.n.Cmds[i]`? if it's not mutated in-place that will avoid you a heap alloc)
</blockquote></details>

n.n.Cmds[i] is already a pointer type, so we don't need to take a pointer to it
___
*[pkg/sql/alter_table.go, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vL_7B4dO7nyIEIbc5:-M1SOUa38_i7Gq321L-g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/alter_table.go#L228)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`pgerror.Newf` with sqlstate 42P16 please (look up which one it is in `pgcode` first)

```
kena=> alter table t add constraint q primary key(x);
ERROR:  multiple primary keys for table "t" are not allowed
kena=> \errverbose
ERROR:  42P16: multiple primary keys for table "t" are not allowed
LOCATION:  index_check_primary_key, index.c:234
```

</blockquote></details>

Done.
___
*[pkg/sql/alter_table.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vLrx71Ldsbape3MBJ:-M1SOZTl9FGuYdlRq3L-:b-rs4xib) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/alter_table.go#L236)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

only create a new array if a copy was not done before. Here's the Go idiom:

```go
sliceCopy := yourslice
copied := false
for i := range yourslice {
   curElem := sliceCopy[i]
   ...
   if .... {
         // need to overwrite the elem here.
         if !copied {
             sliceCopy = append([]xxx, sliceCopy...)
             copied = true
         }
         sliceCopy[i] = newvalue
    }

}
```

</blockquote></details>

I think we always need to copy in this case though
___
*[pkg/sql/create_table.go, line 1383 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vMWsy-TFJ4xz8kEIm:-M1SOqc38BlDmIBlzJNV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/create_table.go#L1383)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

add some pgcode in here thanks
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 1952 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vMTM76yRtCBCj2yt4:-M1SOrcoCWplNlizOGDM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/schema_changer.go#L1952)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"enclosed" seems suspicious. Statements don't "enclose" each other.
</blockquote></details>

Done.

**Comment by rohany** [comment]
This is RFAL.

I went ahead and tried the approach to edit the table collection. Originally, I was a bit overwhelmed with trying to filter out _all_ the places that a table could come into memory, like the various "get table by id" methods. But I guess we really only want to block this kind of behavior during planning. Additionally, I tried something like this last week and got stuck, where for some reason the later planning stages weren't seeing the updates made by the DROP PRIMARY KEY statement, but I seem to have gotten around that now.

I decided to not use a mutation here, as it doesn't really feel like theres any need for it.

**Review by knz — COMMENTED** [review]
Woah very nice result. Such elegance, few code. Wow amaze :dog: 

A little thing though. What do you have for this statement:

```
ALTER TABLE t
     DROP CONSTRAINT "primary",
     ADD COLUMN x INT AS (rowid+2),
     ADD CONSTRAINT "primary" ...
```

i.e. alter commands in-between a drop PK and add PK?

> Reviewed 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-:-M1XyghZ94JNxXo2zhg1:bvt5ykj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @rohany)

___
*[pkg/sql/alter_table.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vLrx71Ldsbape3MBJ:-M1Xxqx01CKwimoBIoPf:bi90px3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/alter_table.go#L236)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I think we always need to copy in this case though
</blockquote></details>

I don't fully understand why, but ok
___
*[pkg/sql/alter_table.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M1XxUh3EzsSG0-c98CK:-M1XxUh3EzsSG0-c98CL:b9250tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a81374cd2f39b132a5aaf6b200a9553c0b7954/pkg/sql/alter_table.go#L54)):*
> ```Go
> 		ctx, n.Table, !n.IfExists, ResolveRequireTableDesc,
> 	)
> 	if err == errNoPrimaryKey {
> ```

`if errors.Is(err, errNoPrimaryKey)`
___
*[pkg/sql/create_table.go, line 1393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M1XxyCB-j7n6MGC7i4j:-M1XxyCB-j7n6MGC7i4k:b23pj4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a81374cd2f39b132a5aaf6b200a9553c0b7954/pkg/sql/create_table.go#L1393)):*
> ```Go
> 				if d.Interleave != nil {
> 					return desc, pgerror.New(
> 						pgcode.FeatureNotSupported, "interleave not supported in primary key constraint definition")
> ```

`unsupported.NewWithIssue` plz for telemetry.

**Review by rohany — COMMENTED** [review]
It now handles that!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-:-M1aPfgo7J--ladzyGOb:b-ccop05)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @lucy-zhang)

___
*[pkg/sql/alter_table.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vLrx71Ldsbape3MBJ:-M1aLEJ-7xsrEYErZfc1:b-p8y4p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/alter_table.go#L236)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't fully understand why, but ok
</blockquote></details>

We are inserting a new element at index i+1 in the slice, so we always need to shift over the elements at i+1..len(list). 
___
*[pkg/sql/alter_table.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M1XxUh3EzsSG0-c98CK:-M1aS4d37r7EUhISd18B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a81374cd2f39b132a5aaf6b200a9553c0b7954/pkg/sql/alter_table.go#L54)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`if errors.Is(err, errNoPrimaryKey)`
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M1XxyCB-j7n6MGC7i4j:-M1aLjEk9KejjltJPi-z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a81374cd2f39b132a5aaf6b200a9553c0b7954/pkg/sql/create_table.go#L1393)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`unsupported.NewWithIssue` plz for telemetry.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: nice :100: 

> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-:-M1aV9Co6KHYkCmIF6x5:b-kvvavj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/alter_table.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44511#-M-vLrx71Ldsbape3MBJ:-M1aV268D9lRypIkmyVG:b-7lpcgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e240675256fa352bbac638291317b732e431ac3/pkg/sql/alter_table.go#L236)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

We are inserting a new element at index i+1 in the slice, so we always need to shift over the elements at i+1..len(list). 
</blockquote></details>

oh ok

**Comment by rohany** [comment]
bors r=knz

**Comment by rohany** [comment]
bors r=knz

**Comment by rohany** [comment]
Flake

bors r=knz

**Pull request merged**
