### PR TITLE
cli: add limit statment_statistics to debug zip

### LINKED ISSUE #108180: debug.zip: add limited statistics tables
The debug zip currently records in [memory statistics](https://github.com/cockroachdb/cockroach/blob/142b97139aa2da78eb2b7d2ffdf6209ccae1e9cc/pkg/cli/zip_table_registry.go#L825), but this is only has very limited information. 

To improve debugging the following changes should be made.
1. Record top 500 fingerprints based on CPU usage.
2. Record all fingerprints in the transaction_contention_events.

### PR DESCRIPTION
**Pull request by j82w**
This adds statement_statistics to the debug zip. It is limited to the transaction fingerprint ids in the the transaction_contention_events table. This is because the statement_statistics table maps the fingerprint to the query text. It also adds the top 100 statements by cpu usage.

closes: https://github.com/cockroachdb/cockroach/issues/108180

Release note (cli change): Added limited statement_statistics to the debug zip.

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
small nit in the comments, otherwise :lgtm: 

> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108210#-:-Nb_1qRK7vqqlsI8juUk:b26ujwb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w and @nkodali)

___
*[`pkg/cli/zip_table_registry.go` line 1240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108210#-Nb_1g8V3QTIDCqKOQIC:-Nb_1g8V3QTIDCqKOQID:b-j0u1tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4bc0944b1d4317dd80d6bdeb5b70c6a6881a44/pkg/cli/zip_table_registry.go#L1240)):*
> ```Go
> 	},
> 	// statement_statistics can have over 100k rows in just the last hour.
> 	// Only select the top 100 by cpu usage, and the transaction fingerprints
> ```

here you mean the top 100 transactions? Can you clarify that, because it sounds like is the statements, but you can return up to 5k statements on this query.

**Comment by j82w** [comment]
*[`pkg/cli/zip_table_registry.go` line 1240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108210#-Nb_1g8V3QTIDCqKOQIC:-Nb_dsGX7Sfp92mS-7dw:bmig2mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4bc0944b1d4317dd80d6bdeb5b70c6a6881a44/pkg/cli/zip_table_registry.go#L1240)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

here you mean the top 100 transactions? Can you clarify that, because it sounds like is the statements, but you can return up to 5k statements on this query.
</blockquote></details>

Correct, I'll update the description.

**Comment by j82w** [comment]
blathers backport 22.2 23.1

**Pull request merged**
