### PR TITLE
descpb: make Region a message in the RegionConfig

### PR DESCRIPTION
**Pull request by otan**
As discussed sometime last year, this will allow us at some point to
extend region with extra data (e.g. fallover info)

----

descpb: make Region a message in the RegionConfig

This allows us to attach more per-region metadata if we decide we want
to do that at a later stage.

Release note: None

descpb: rename Region to RegionName

With the previous commit making Region an object that may contain more
metadata, change the Region type to RegionName.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58629#-:-MQV7b2Y9sNAz8sYhANK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58629#-MQV7YTT7YKbvNvFgl_l:-MQV7YTU28efoL0zuBhe:b-152c9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a876e98bdaf23a2709c0f7d79a7829b1b5d2084b/pkg/sql/catalog/dbdesc/database_desc.go#L225)):*
> ```Go
> 		regions[i] = region.Name
> 	}
> ```

nit: potentially a stray line, or not.

**Comment by otan** [comment]
thanks!

bors r=nvanbenschoten

**Comment by otan** [comment]
urgh flake!

bors r+

**Comment by otan** [comment]
only last shot....

bors r+

**Review by ajstorm — COMMENTED** [review]
Might be too late for this PR, but do we also want to do this for Primary Region?  I would think that at some point down the road we might want to allow for users to specify a failover primary region distinct from the failover region.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58629#-:-MQYAMSfC9WpZCOMWQbK:bazkhik)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @nvanbenschoten, and @otan)

**Comment by otan** [comment]
I think PRIMARY REGION is ok, because there is only one we can encode that on the RegionConfig itself.

The reason we'd want this for per-region is because otherwise we'd have to (grossly) have a 1:1 index to other metadata, e.g.

```
repeated string regions = 1;
repeated string failover_info = 2; // same indexes as 1...
```

Let's try merge agian...


bors r=nvanbenschoten

**Pull request merged**
