### PR TITLE
storage: delete a bad test

### PR DESCRIPTION
**Pull request by andreimatei**
The test in question says:
// TestStoreRangeSplitConcurrent verifies that concurrent range splits
// of the same range are executed serially, and all but the first fail
// because the split key is invalid after the first split succeeds.

I can't tell what it is that this test is trying to test although I've
studied it. I suspect the test is thoroughly confused and confusing.
It's in my way for #33150 because I can't easily get it to pass reliably
with various changes there. So I'd like to just delete it unless someone
can represent the test's intention to me.

The test spawns a bunch of splits on the same key and assert that all
but one get RangeMismatchError. These errors are produced in two ways,
depending on the timing of the split goroutines:
1) a request that has already made it to the replica before the first
split completed will produce the error here:
https://github.com/cockroachdb/cockroach/blob/3b0ea90eac2d94aba4d96537dbcc175707ebd259/pkg/storage/replica_command.go#L292
after possibly encountering a retry here:
https://github.com/cockroachdb/cockroach/blob/3b0ea90eac2d94aba4d96537dbcc175707ebd259/pkg/storage/replica_command.go#L154

2) a request that is routed to the replica after the first split
completed is rejected here (assuming it was routed using the pre-split
range keys):
https://github.com/cockroachdb/cockroach/blob/3b0ea90eac2d94aba4d96537dbcc175707ebd259/pkg/storage/replica.go#L2628

If the request is routed to the correct post-split range, it will
*succeed* because of this code:
https://github.com/cockroachdb/cockroach/blob/3b0ea90eac2d94aba4d96537dbcc175707ebd259/pkg/storage/replica_command.go#L321
This fact seems to invalidate the premise of the test.

The test is currently passing because the test sender used
sender used the test is always routing all requests to range 1,
arbitrarily. The otherwise unrelated #33150 makes the routing for this
test store more real, and so this test becomes flaky.

In theory the test could control the timing of the requests better as to
ensure that all requests make it to the (pre-split) replica before any
of the splits are executed. But even so I remain confused about what the
intention here is / if verifying the mismatch errors is a good thing.
It seems to me that we'd like these splits to succeed as much as
possible, not to fail.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
The test may be confused (it is 4 years old and has seen a lot of tweaks), but the comment describing what it is trying to do seems valid to test: send a bunch of concurrent `AdminSplit` requests to a range and verify that only one succeeds. The original version of the test seems like it would still be valid: https://github.com/cockroachdb/cockroach/commit/0187440452b73830c73c24d12c59080827f116e3#diff-45eb8112c777da1544e7c52576091117R97.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33378#-:-LUl_drB-2bQOebJmJaG:b-jenpsl)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by andreimatei** [comment]
But, as I was trying to explain, we've written explicit code to ensure that, sometimes, all splits "succeed" - in the sense that redundant ones don't always get errors.
So the only argument for the test is if you insist on the "send... *to a range*"  part (i.e. make sure that all requests are "queued up" on a replica before allowing the first one to go through). But is that worth insisting on? Ideally, the redundant split requests would always succeed (after all, what they wanted to happen happened) regardless of the timing, so the test kinda fundamentally doesn't make sense to me because I fail to see the hazard it's trying to protect against.

**Comment by petermattis** [comment]
> But, as I was trying to explain, we've written explicit code to ensure that, sometimes, all splits "succeed" - in the sense that redundant ones don't always get errors.

That's fine. I think we still want to test that a bunch of concurrent split operations to the same range at the same split key produce a sensical result: at least one of the splits should succeed and no error should occur.

**Comment by petermattis** [comment]
> I fail to see the hazard it's trying to protect against.

Think of it as trying to blackbox verify that concurrent split operations are handled properly. I think you're arguing that the test isn't useful because you know the internals of the split implementation and concurrent splits turn into no-ops. What would you be testing if you didn't know those internals?

**Review by bdarnell — COMMENTED** [review]
> Think of it as trying to blackbox verify that concurrent split operations are handled properly.

Right. The test is still useful, at least in theory, although the bogus test sender means that I'm not sure it ever tested exactly what it said it did. Ever since #14273 it's had a couple of bugs cancelling each other out: It *should* have changed to expect all the splits to pass, but instead it rotted and continued to get the key mismatch errors because the splits were sent to the wrong range. 

I think we probably want to keep this test, but change it to expect *all* the splits to succeed once it's using the more realistic routing. But if that doesn't just work, I would delete the test instead of continuing to dig. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33378#-:-LUmieud1LzxznK9YQ0T:b-chghai)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
> I think we probably want to keep this test, but change it to expect all the splits to succeed once it's using the more realistic routing. But if that doesn't just work, I would delete the test instead of continuing to dig.

That doesn't "just work" because the timing matters. With realistic routing, if requests arrive to the pre-split range, then they fail. If they arrive to the post-split one, they succeed. So, to succeed reliably, the 2nd split can only be sent once the first one is known to have succeeded. At which point... we're not really testing much and I've become disillusioned with the test.

> What would you be testing if you didn't know those internals?

I'd test nothing, because the black-box contract doesn't let me make assumptions about what would succeed and what would fail.

I'd... just delete the test if I can get a stamp :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33378#-:-LVK4MffAPgiynt-PSbM:b-e43seh)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by bdarnell — APPROVED** [review]
> With realistic routing, if requests arrive to the pre-split range, then they fail.

Oh, this is still below the level of the automatic retries on key mismatch errors? Just delete it, then. Not worth rewriting to use higher levels.

**Review by andreimatei — COMMENTED** [review]
yes, the test doesn't use a DistSender, which would retry the key mismatch errors

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33378#-:-LVKJLxoDIssPG2htYiM:b-6hn59q)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
