### PR TITLE
Replace replica descriptor cache with last-seen sender and recipient fields.

### LINKED ISSUE #7694: storage: move Store.replicaDescCache into Replica
From this [TODO](https://github.com/cockroachdb/cockroach/blob/master/storage/store.go#L370-L384):

```
// TODO(peter): The replica descriptor cache is a historical artifact from
// the multiraft era. It might be preferrable to move this cache to Replica
// and change it to a map keyed by replicaID. The question then becomes
// how/when to expire old entries from the cache. Presumably we could hook
// into Replica.setDesc to notice when a replicaID has been removed. It is
// possible we could get away with a single entry cache as we only need to
// be able to respond to the last replica that talked to us.
//
// There is a potential downside to this move: removing a replica from
// Store.mu.replicas will remove cached replica descriptor
// information. @bdarnell Thinks this won't be a problem: When a replica is
// completely removed, it won't be recreated until there is another event
// that will repopulate the cache. When it is temporarily dropped and
// recreated, the newly recreated replica will have a complete range
// descriptor so it won't need to rely on this cache.
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Replace the replica descriptor cache that used to live on Store with a
pair of fields on Replica that keep track of the most recently seen
sender and recipient replica descriptors from Raft.

This change is possible because the cache was only necessary in the
situations when the replica is trying to send a Raft-initiated message
and its Range does not have an accurate or present replica descriptor
for either the sender (itself) or the recipient - but in all of these
situations, the recipient and sender replica descriptors are guaranteed
to be the same as the sender and recipient (respectively) of the
Replica's most recently recieved Raft message. So, we can simply store
those 2 replica descriptors on the replica, updating them every time we
get a Raft message, and use them when sending Raft messages when the
Replica's Range doesn't have present or accurate descriptors for the
sender or recipient.

The comments for the replica descriptor cache have been moved to the new
fields in Replica, and contain further justification for why this change
works.

Resolves #7694.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8125)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 266 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125#-KNrc6RK-Jp1E2oyhHM1:-KNrc6RK-Jp1E2oyhHM2:69497900) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d142dcc401ab495a676bdc1127d8479c3eb153/storage/replica.go#L266)):*
> ```Go
> 		// the replica has a range descriptor but it is out of date. Note that a
> 		// replica being removed from a node and then quickly re-added before the
> 		// replica has been GC'd will also utilize the replica descriptor cache. In
> ```

"replica descriptor cache"

---

*[storage/replica.go, line 278 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125#-KNrcE7Le3D-mlkJ5whd:-KNrcE7Le3D-mlkJ5whe:1440666194) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d142dcc401ab495a676bdc1127d8479c3eb153/storage/replica.go#L278)):*
> ```Go
> 		// Removing a replica from Store.mu.replicas is not a problem because
> 		// When a replica is completely removed, it won't be recreated until
> 		// there is another event that will repopulate the replicas map.
> ```

there's no map

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125#-:-KNrblt_Z2m-PPxphtzz:1417088721)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 266 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125#-KNrc6RK-Jp1E2oyhHM1:-KNrdg22lnBX0enUfGkI:-813025496) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d142dcc401ab495a676bdc1127d8479c3eb153/storage/replica.go#L266)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "replica descriptor cache"
</details>
I'll fix this.

---

*[storage/replica.go, line 278 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125#-KNrcE7Le3D-mlkJ5whd:-KNrdiM3WGrl9YWiq4TT:-133824389) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d142dcc401ab495a676bdc1127d8479c3eb153/storage/replica.go#L278)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there's no map
</details>
I was referencing the Store.mu.replicas map.

`		replicas       map[roachpb.RangeID]*Replica // Map of replicas by Range ID`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 3 of 5 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica.go, line 1735 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125#-KNy5vhhTemmlQjWC85O:-KNy5vhhTemmlQjWC85P:-2130678887) ([raw file](https://github.com/cockroachdb/cockroach/blob/29e7a257ab57f6b33290b10aa208defbd5fd6952/storage/replica.go#L1735)):*
> ```Go
> 		return repDesc
> 	}
> 	return fallback
> ```

I don't like the possibility of this method returning a replica descriptor whose ID doesn't match the input. I think this method should perform the checks you added to `sendRaftMessage` and return an error if it doesn't match.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125#-:-KNy6JLvPoLPgtnzHa3o:1417088721)*

**Comment by jordanlewis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica.go, line 1735 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125#-KNy5vhhTemmlQjWC85O:-KO5rVvMCzov4H7HKZX9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/29e7a257ab57f6b33290b10aa208defbd5fd6952/storage/replica.go#L1735)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I don't like the possibility of this method returning a replica descriptor whose ID doesn't match the input. I think this method should perform the checks you added to `sendRaftMessage` and return an error if it doesn't match.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r7, 5 of 5 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 1737 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125#-KO67FpKiG9Vd_b2fsR9:-KO67FpLX1RngDW2icgm:-948117884) ([raw file](https://github.com/cockroachdb/cockroach/blob/3189f57eff64215a1299771b9667fe203c083c5f/storage/replica.go#L1737)):*
> ```Go
> 	var err error
> 	if fallback.ReplicaID != replicaID {
> 		err = errors.Errorf("fallback replica %+v doesn't match input replica id %v", fallback, replicaID)
> ```

this path should not return `fallback`.

```go
if fallback.ReplicaID == replicaID {
  return fallback, nil
}
return roachpb.ReplicaDescriptor{}, errors.Errorf("replica %d not present in %v, %v", replicaID, fallback, r.mu.state.Desc.Replicas)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 1737 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125#-KO67FpKiG9Vd_b2fsR9:-KO68AnEBwqM2KtZjN1U:775486668) ([raw file](https://github.com/cockroachdb/cockroach/blob/3189f57eff64215a1299771b9667fe203c083c5f/storage/replica.go#L1737)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this path should not return `fallback`.
> 
> ```go
> if fallback.ReplicaID == replicaID {
>   return fallback, nil
> }
> return roachpb.ReplicaDescriptor{}, errors.Errorf("replica %d not present in %v, %v", replicaID, fallback, r.mu.state.Desc.Replicas)
> ```
</details>
Makes sense. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8125)*

**Comment by tschottdorf** [comment]
Late to the party, but good to see this 👍

**Pull request merged**
