### PR TITLE
kv: collect hot ranges per tenant on store

### PR DESCRIPTION
**Pull request by koorosh**
The main goal of this change is to provide ability to request hot ranges info per tenant (as part of changes for UA). To track down hot ranges per tenant, `ReplicaRankingMap` struct is added that works almost identically as existing `ReplicaRankings` struct with only difference that hottest replicas are stored in an underlying map structure to keep separately ranges for every tenant. Also, it was decided to not extend existing `ReplicaRankings` functionality because it is used for replica rebalancing that doesn't need to know about tenants.

This change might bring small overhead for self-hosted clusters as it will accumulate same hot ranges in both `replRankings` and `replRankingsByTenant` fields in Store.

Changes in next PRs are supposed to rely on this change.

Release note: None

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-19124

### CODE REVIEW

**Review by kvoli — CHANGES_REQUESTED** [review]
There are a few diffs which look out of place.

A few comments:

- The ReplicaRankings struct is currently overloaded. The dual use for the store rebalancers decreasing first fit and also for updating hot ranges isn't as well separated as it should be. While it is useful from an obs perspective for these to remain the same, the datastructure (CandidateReplica) and replica rankings generally isn't well suited as a middle ground imo. It has been overloaded to accommodate allocation. 
   - This doesn't necessarily affect this change, however I'm cautious of this usecase for RR.
- The choice to reuse 128 hottest replicas per tenant seems costly. In the case where there are many tenants, it introduces mem/cycle overhead in the multi-map RR by tenant tracking. Would it be possible to bench the overhead with many tenants (serverless usecase), where most are quiescent.
  - A small change here would be to introduce minimums to track. Below which we ignore adding them to the map.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-:-NHTr-hcCfXwAFodw7_B:b-xi5tmt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @koorosh)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-NHTpz4d7lmQMVJrlNqL:-NHTpz4d7lmQMVJrlNqM:bqftfd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/11030f1be9682e87b583250456c589055b416359/pkg/kv/kvserver/replica_rankings.go#L244)):*
> ```Go
> 
> // RRAccumulatorByTenant accumulates replicas per tenant to update the replicas tracked by ReplicaRankingMap.
> // It should be used in the same way as RRAccumulator (see doc string)
> ```

nit: Period required.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-NGXfo3i0lRYTBQUQyKb:-NGXfo3i0lRYTBQUQyKc:bxmds0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/11030f1be9682e87b583250456c589055b416359/pkg/kv/kvserver/replica_rankings.go#L264)):*
> ```Go
> 	}
> 
> 	if r.Len() < numTopReplicasToTrack {
> ```

This is 128. Should it also be 128 for each tenant? It seems like a waste of memory and compute to track 128 for every tenant in the case where most of them are quiescent.
___
*[`pkg/kv/kvserver/store.go` line 718 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-NHTp_tM7Q7iF-qb6eCa:-NHTp_tM7Q7iF-qb6eCb:b-one475) ([raw file](https://github.com/cockroachdb/cockroach/blob/11030f1be9682e87b583250456c589055b416359/pkg/kv/kvserver/store.go#L718)):*
> ```Go
> 	tsCache              tscache.Cache           // Most recent timestamps for keys / key ranges
> 	allocator            allocatorimpl.Allocator // Makes allocation decisions
> 	replRankings         *ReplicaRankings
> ```

Should these other diffs be here? Shouldn't only `replyRankingsByTenant` be added?



_Code quote:_
```Go
	tsCache              tscache.Cache           // Most recent timestamps for keys / key ranges
	allocator            allocatorimpl.Allocator // Makes allocation decisions
	replRankings         *ReplicaRankings
	replRankingsByTenant *ReplicaRankingMap
```

**Review by koorosh — COMMENTED** [review]
> A small change here would be to introduce minimums to track. Below which we ignore adding them to the map.
Added additional validation to track only replicase with non-zero QPS.

TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-:-NHijUTf2flHCZlx6-79:b-6gkdmk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @kvoli)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-NHTpz4d7lmQMVJrlNqL:-NHihVQ92sMWeH2jijRO:b-dtkds3) ([raw file](https://github.com/cockroachdb/cockroach/blob/11030f1be9682e87b583250456c589055b416359/pkg/kv/kvserver/replica_rankings.go#L244)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: Period required.
</blockquote></details>

Done, thanks!
___
*[`pkg/kv/kvserver/replica_rankings.go` line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-NGXfo3i0lRYTBQUQyKb:-NHigy6zEmGy7_Albjqm:b-njhv7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/11030f1be9682e87b583250456c589055b416359/pkg/kv/kvserver/replica_rankings.go#L264)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This is 128. Should it also be 128 for each tenant? It seems like a waste of memory and compute to track 128 for every tenant in the case where most of them are quiescent.
</blockquote></details>

Maybe it's worth to add only replicas with QPS > 0? Then it would resolve this problem? What do you think?
___
*[`pkg/kv/kvserver/store.go` line 718 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-NHTp_tM7Q7iF-qb6eCa:-NHig8rUCOcP1-92IgTl:bo1q9qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/11030f1be9682e87b583250456c589055b416359/pkg/kv/kvserver/store.go#L718)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should these other diffs be here? Shouldn't only `replyRankingsByTenant` be added?
</blockquote></details>

It's formatting, spacing between field names and types are aligned,.

**Review by kvoli — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90097)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @koorosh)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-NGXfo3i0lRYTBQUQyKb:-NIZZqKz7J1rZuaLBZdb:beow8g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/11030f1be9682e87b583250456c589055b416359/pkg/kv/kvserver/replica_rankings.go#L264)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Maybe it's worth to add only replicas with QPS > 0? Then it would resolve this problem? What do you think?
</blockquote></details>

That seems reasonable. Perhaps set it to 1 to avoid (0,1) vals. This is to avoid a common case where there are a couple of requests in the last 30 minutes that bump it above 0.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90097)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @kvoli)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-NGXfo3i0lRYTBQUQyKb:-NIaqxgvEmSW4CM9P27I:b-a36jdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/11030f1be9682e87b583250456c589055b416359/pkg/kv/kvserver/replica_rankings.go#L264)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

That seems reasonable. Perhaps set it to 1 to avoid (0,1) vals. This is to avoid a common case where there are a couple of requests in the last 30 minutes that bump it above 0.
</blockquote></details>

Agree, done.

**Review by kvoli — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90097#-:-NId6BVA5MPYEJSCy7I9:b-uwkowz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Pull request merged**
