### PR TITLE
sql: hang planner from Session and keep track of the SchemaChangers throughout a txn

### PR DESCRIPTION
**Pull request by andreimatei**
the commits can be reviewed one at a time.

I still need to figure out how to test the schema change improvement.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5409)

### CODE REVIEW

**Comment by tamird** [comment]
Sigh. There's a ton of code movement between files here that, because it's not called out in a separate commit, makes it extremely difficult to review this without pouring over every line of code. I'll revisit this on Monday because I need more display real estate than I have available at present.

---

Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parser/scan.go, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDGPEdT53RcToyaCNN2:-KDGPEdT53RcToyaCNN3:1313663657) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5fa6daf980f98ae743544221cdc2203a5a36c38/sql/parser/scan.go#L43)):*
what's this about?

---

*[sql/pgwire/v3.go, line 133 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDGP3Xh0SU9F_OMWNBv:-KDGP3XiUKQQG3J-ntMQ:-392764241) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5fa6daf980f98ae743544221cdc2203a5a36c38/sql/pgwire/v3.go#L133)):*
this is the zero value, you can omit this

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-:-KDGRYpmd5KY_7WswJSx:-1477207533)*

**Comment by andreimatei** [comment]
@tamird added a separate commit for the code that moved with no changes

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-:-KDHaUjvjsPL0og4btZU:378382192)*

**Comment by tamird** [comment]
Reviewed 8 of 8 files at r3, 8 of 8 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/executor.go, line 237 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHdJtJ4Lnd8c49GAbG:-KDHdJtJ4Lnd8c49GAbH:-1979242991) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/executor.go#L237)):*
it's OK - i think you can remove this

---

*[sql/executor.go, line 256 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHd7m_Lh64GvUxw2Jv:-KDHd7m_Lh64GvUxw2Jw:639136607) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/executor.go#L256)):*
why have the panic in `initPlanner` if you're just checking the inverse condition here? perhaps just check for initialization in `initplanner` and noop if initialized?

---

*[sql/executor.go, line 362 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHfLaA3INYvIfpi1MZ:-KDHfLaA3INYvIfpi1M_:-1888353805) ([raw file](https://github.com/cockroachdb/cockroach/blob/036d1b86e0c919ad97d5d28c1d2307419e95af3d/sql/executor.go#L362)):*
s/can/cannot/?

---

*[sql/plan.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHe8KpBxrDygHO_BpK:-KDHe8KpBxrDygHO_BpL:59283066) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/plan.go#L60)):*
this should be the in function's doc comment

---

*[sql/plan.go, line 135 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHejEzfN4seBN3rMYU:-KDHejEzfN4seBN3rMYV:575877990) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/plan.go#L135)):*
this function (and a number of others used with it) is only called from one place. Personally, I find this style harder to read than having this code inline at the caller as I believe was once the case.

Nothing necessarily actionable here, just food for thought.

---

*[sql/session.go, line 70 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHcZRD5o9zbofcTKbK:-KDHcZRD5o9zbofcTKbL:426047301) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/session.go#L70)):*
since the lifetime of this planner now matches the lifetime of the session, why not make this a value member (as opposed to a pointer)? You can still prevent double initialization by comparing to the empty value, if you wanted.

---

*[sql/parser/scan.go, line 43 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHbqBZGihPHApO-NI9:-KDHbqBZGihPHApO-NIA:1313663657) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/parser/scan.go#L43)):*
what's this about?

---

*[sql/pgwire/v3.go, line 133 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHbmTJRUmzlVgXz15Z:-KDHbmTKppWVG91MLW0o:-392764241) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/pgwire/v3.go#L133)):*
this is the zero value, you can omit this

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/executor.go, line 237 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHdJtJ4Lnd8c49GAbG:-KDOeZyH7VPWdQbYC7Rz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/executor.go#L237)):*
Done.

---

*[sql/executor.go, line 256 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHd7m_Lh64GvUxw2Jv:-KDOnWU--FugX6rieDqd:-923826693) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/executor.go#L256)):*
I prefer this pattern; a noop in an `init` function would be surprising. It'd have to be called `initMaybe` and that's unusual.
In any case, I've made `planner` not be a pointer as you suggested elsewhere. But I've had to make the `Session` a pointer inside the  `v3conn`, because the `Session` needs a constructor and is not shallow-copiable (because its `planner` has a pointer back it). Still got cleaner code this way, because we avoid `init` methods.

---

*[sql/executor.go, line 362 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHfLaA3INYvIfpi1MZ:-KDPNXV2SzIrVDxbn9La:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/036d1b86e0c919ad97d5d28c1d2307419e95af3d/sql/executor.go#L362)):*
Done.

---

*[sql/plan.go, line 60 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHe8KpBxrDygHO_BpK:-KDPOIhByjmZnf802y_N:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/plan.go#L60)):*
Done.

---

*[sql/plan.go, line 135 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHejEzfN4seBN3rMYU:-KDPNb1gZQVUgWwCZIYG:-1808039115) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/plan.go#L135)):*
IMHO the caller is already a very long function.

---

*[sql/session.go, line 70 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHcZRD5o9zbofcTKbK:-KDOf7qqs_GDnkW5Ex7E:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/session.go#L70)):*
Done.

---

*[sql/parser/scan.go, line 43 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHbqBZGihPHApO-NI9:-KDPOoRl30DkJ2dlITPQ:-793663831) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/parser/scan.go#L43)):*
used to verify that `Parse` is not called twice on the same scanner. That doesn't work, as I was surprised to find out.

---

*[sql/pgwire/v3.go, line 133 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHbmTJRUmzlVgXz15Z:-KDPOWrOdtQLOiB_FPya:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/pgwire/v3.go#L133)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409)*

**Comment by tamird** [comment]
The circular reference from planner to session is pretty uncomfortable. Can it be avoided?

---

Reviewed 8 of 8 files at r6, 11 of 11 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/plan.go, line 135 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHejEzfN4seBN3rMYU:-KDPUaG_iQt0ut4VBVA-:-183477043) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/plan.go#L135)):*
Might be (I haven't looked), but the context switch is not free either.

---

*[sql/session.go, line 76 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDPUy37KeQdayrCm0eA:-KDPUy37KeQdayrCm0eB:2096106379) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba3751c913473fbbd274fde5943725e630f08b10/sql/session.go#L76)):*
call this `NewSession` since it returns a pointer.

---

*[sql/parser/scan.go, line 43 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHbqBZGihPHApO-NI9:-KDPSbX8ZouV4s4ao72-:1747366737) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/parser/scan.go#L43)):*
OK. Seems odd to group it with the stuff you grouped it with.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-:-KDPW_E0xyKIwjx0REb0:-1933868095)*

**Comment by andreimatei** [comment]
At the very least, the planner is accessing the (name of the) current database from the Session. And I think that's reasonable.

---

Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/session.go, line 76 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDPUy37KeQdayrCm0eA:-KDPXnbkujzY7cMVaAPr:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba3751c913473fbbd274fde5943725e630f08b10/sql/session.go#L76)):*
Done.

---

*[sql/parser/scan.go, line 43 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDHbqBZGihPHApO-NI9:-KDPXA8ebmaRi6cwrXDZ:-1874690800) ([raw file](https://github.com/cockroachdb/cockroach/blob/e77e19f4509ad3e69bc51334e9dd358b31da5927/sql/parser/scan.go#L43)):*
You mean the commit? Before it there was no possibility of reusing the parser, since we created new planners every time.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-:-KDPXpOXKRLjl_2AkqqN:-1009246106)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r9, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409)*

**Comment by andreimatei** [comment]
@tamird I've removed `session.opts` and added a new commit which unifies `session.user` and `planner.user`

---

Review status: 3 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-:-KDPauurVz3TYoWpTPQV:378197649)*

**Comment by tamird** [comment]
OK. Can you add a TODO to move the database name onto the planner, and invert the ownership between the two? That would allow us to remove the circular reference.

---

Reviewed 5 of 5 files at r11, 3 of 3 files at r12, 3 of 3 files at r13, 3 of 3 files at r14, 10 of 10 files at r15.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[security/auth.go, line 74 \[r15\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDPiXf3w_rS9L9b5YWd:-KDPiXf3w_rS9L9b5YWe:596695271) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cd6bf53f944fdc4c86696d9176906118b3455c9/security/auth.go#L74)):*
too much grep?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-:-KDPhwg8FPoTw4Bd_8-S:1668949152)*

**Comment by andreimatei** [comment]
added the TODO

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-:-KDPv7lMqn7S7fAL-03q:1944696314)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r16, 4 of 11 files at r17, 1 of 3 files at r18, 11 of 11 files at r19.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-:-KDPwVRWopoB0LC56hDA:1417088721)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[security/auth.go, line 74 \[r15\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409#-KDPiXf3w_rS9L9b5YWd:-KDPwVy9dvNknusnAUxp:-2024284950) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cd6bf53f944fdc4c86696d9176906118b3455c9/security/auth.go#L74)):*
too little grep! Thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r20.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5409)*

**Pull request merged**
