### PR TITLE
syncutil: make IntMap generic, rename to Map

### LINKED ISSUE #103147: syncutil: generic `IntMap`
Would be nice to make this generic, unless there's already a good/better implementation upstream. It might hamper performance though, since it prevents some compiler optimizations.

Jira issue: CRDB-27851

### PR DESCRIPTION
**Pull request by nvb**
Closes #103147.

Will help #120597, so that it does not need to use the interface-heavy stdlib `sync.`Map just because its key is not an `int64`.

This PR makes `syncutil.IntMap` (renamed to `syncutil.Map`) generic, so that it can be used with keys other than `int64`. This restores some of the generality lost when the standard library's `sync.Map` was specialized in our `IntMap` fork in 8340120c. It does so without losing the performance benefits that specialization provided, because we use generics instead of interface objects. This limited use of generics with no virtual function calls performs identically to the hand-specialized version.

The use of generics also provides type safety. Callers no longer need to cast int-like keys to and from `int64`. They also no longer need to cast typed-pointers to and from `unsafe.Pointer`.

Benchmark performance is meaningfully unchanged:
```
name                                        old time/op    new time/op    delta
LoadMostlyHits/*syncutil.IntMap-10            2.05ns ± 6%    2.33ns ± 4%  +14.01%  (p=0.000 n=10+10)
LoadMostlyMisses/*syncutil.IntMap-10          1.82ns ± 5%    2.00ns ± 7%   +9.88%  (p=0.000 n=10+9)
LoadOrStoreBalanced/*syncutil.IntMap-10        206ns ± 1%     208ns ± 2%     ~     (p=0.059 n=8+8)
LoadOrStoreUnique/*syncutil.IntMap-10          394ns ± 3%     410ns ±10%     ~     (p=0.203 n=9+10)
LoadOrStoreCollision/*syncutil.IntMap-10      1.33ns ± 5%    1.54ns ± 4%  +16.20%  (p=0.000 n=10+10)
LoadAndDeleteBalanced/*syncutil.IntMap-10     2.41ns ± 4%    2.66ns ± 2%  +10.14%  (p=0.000 n=10+10)
LoadAndDeleteUnique/*syncutil.IntMap-10       0.65ns ±41%    0.70ns ±44%     ~     (p=0.143 n=10+10)
LoadAndDeleteCollision/*syncutil.IntMap-10    0.84ns ± 3%    0.78ns ±44%     ~     (p=0.481 n=10+10)
Range/*syncutil.IntMap-10                      982ns ± 5%    1022ns ± 1%   +4.05%  (p=0.001 n=10+10)
AdversarialAlloc/*syncutil.IntMap-10           158ns ± 0%     157ns ± 1%     ~     (p=0.722 n=7+10)
AdversarialDelete/*syncutil.IntMap-10         30.6ns ±10%    29.2ns ± 5%   -4.60%  (p=0.004 n=10+9)
DeleteCollision/*syncutil.IntMap-10           0.65ns ±56%    0.88ns ±47%  +35.02%  (p=0.007 n=10+10)

name                                        old alloc/op   new alloc/op   delta
LoadMostlyHits/*syncutil.IntMap-10             0.00B          0.00B          ~     (all equal)
LoadMostlyMisses/*syncutil.IntMap-10           0.00B          0.00B          ~     (all equal)
LoadOrStoreBalanced/*syncutil.IntMap-10        49.3B ± 8%     49.2B ± 8%     ~     (p=0.854 n=10+9)
LoadOrStoreUnique/*syncutil.IntMap-10           101B ± 5%       67B ± 6%  -33.64%  (p=0.000 n=8+9)
LoadOrStoreCollision/*syncutil.IntMap-10       0.00B          0.00B          ~     (all equal)
LoadAndDeleteBalanced/*syncutil.IntMap-10      0.00B          0.00B          ~     (all equal)
LoadAndDeleteUnique/*syncutil.IntMap-10        0.00B          0.00B          ~     (all equal)
LoadAndDeleteCollision/*syncutil.IntMap-10     0.00B          0.00B          ~     (all equal)
Range/*syncutil.IntMap-10                      0.00B          0.00B          ~     (all equal)
AdversarialAlloc/*syncutil.IntMap-10           27.0B ± 0%     27.0B ± 0%     ~     (all equal)
AdversarialDelete/*syncutil.IntMap-10          8.40B ±19%     8.00B ± 0%     ~     (p=0.211 n=10+10)
DeleteCollision/*syncutil.IntMap-10            0.00B          0.00B          ~     (all equal)

name                                        old allocs/op  new allocs/op  delta
LoadMostlyHits/*syncutil.IntMap-10              0.00           0.00          ~     (all equal)
LoadMostlyMisses/*syncutil.IntMap-10            0.00           0.00          ~     (all equal)
LoadOrStoreBalanced/*syncutil.IntMap-10         0.00           0.00          ~     (all equal)
LoadOrStoreUnique/*syncutil.IntMap-10           1.00 ± 0%      1.00 ± 0%     ~     (all equal)
LoadOrStoreCollision/*syncutil.IntMap-10        0.00           0.00          ~     (all equal)
LoadAndDeleteBalanced/*syncutil.IntMap-10       0.00           0.00          ~     (all equal)
LoadAndDeleteUnique/*syncutil.IntMap-10         0.00           0.00          ~     (all equal)
LoadAndDeleteCollision/*syncutil.IntMap-10      0.00           0.00          ~     (all equal)
Range/*syncutil.IntMap-10                       0.00           0.00          ~     (all equal)
AdversarialAlloc/*syncutil.IntMap-10            0.00           0.00          ~     (all equal)
AdversarialDelete/*syncutil.IntMap-10           0.00           0.00          ~     (all equal)
DeleteCollision/*syncutil.IntMap-10             0.00           0.00          ~     (all equal)
```

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Thanks!

We saw a more significant performance penalty over in https://github.com/cockroachdb/cockroach/issues/103147#issuecomment-1562338132, although small in absolute terms (similarly to this PR). Any thoughts on why the penalty appears smaller in this case?

> Reviewed 22 of 22 files at r10, 2 of 5 files at r11, 13 of 13 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-:-NtBv2Jx6HsFd8wpnduK:bju0hmt)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

___
*[`pkg/util/syncutil/int_map.go` line 24 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-NtBwFgV8pcwGzAu7RHE:-NtBwFgV8pcwGzAu7RHF:bxnbau6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ee2339fc19ff705b91ce065f8e73b48b554f25e/pkg/util/syncutil/int_map.go#L24)):*
> ```Go
> )
> 
> // IntMap is like a Go map[K]*V but is safe for concurrent use by multiple
> ```

Is there a strong reason why this stores `*V` rather than `V`, instead of letting the caller choose? Is it to keep the same expunged handling?

**Review by petermattis — APPROVED** [review]
:lgtm:

I wonder if switching to `swiss.Map` can recover any of the performance penalty.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-:-NtC30Bi3A_59zm-rmaC:b-pq90z)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/util/syncutil/int_map.go` line 423 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-NtC0WBaAsJH-D1Ieb5-:-NtC0WBaAsJH-D1Ieb50:b-39t73i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ee2339fc19ff705b91ce065f8e73b48b554f25e/pkg/util/syncutil/int_map.go#L423)):*
> ```Go
> // deleted from the dirty map.
> func (e *entry[V]) expunged() *V {
> 	return (*V)(expunged)
> ```

I'm surprised this doesn't run afoul the checkptr checks performed by the Go runtime that take place under race. Those checks try to verify that the memory pointed to by the start of `expunged` and `uintptr(expunged)+sizeof(V)-1` are part of the same memory allocation.

**Review by pav-kv — APPROVED** [review]
LGTM for raft bits.

**Review by nvb — COMMENTED** [review]
TFTRs!

> We saw a more significant performance penalty over in [#103147 (comment)](https://github.com/cockroachdb/cockroach/issues/103147#issuecomment-1562338132), although small in absolute terms (similarly to this PR). Any thoughts on why the penalty appears smaller in this case?

No, I'm not sure. I wouldn't expect this change to have such a large impact. I can't locate the code that was used for those tests.

> I wonder if switching to `swiss.Map` can recover any of the performance penalty.

I was thinking we would just pick that up when https://github.com/golang/go/issues/54766 lands.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-:-Nto0CVd1TE8zY09f81I:b-27i1qk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker, @pav-kv, and @petermattis)

___
*[`pkg/kv/kvserver/raft_transport.go` line 405 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120604#gh-1527634676:-Nto3Ds_6cvAmyKIHwJW:b-6c9w64) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ee2339fc19ff705b91ce065f8e73b48b554f25e/pkg/kv/kvserver/raft_transport.go#L405)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Can this now be squashed to `return t.incomingMessageHandlers.Load(storeID)`, and optionally inlined (`getIncomingRaftMessageHandler` would be trivial now)?

Same below, for `getOutgoingMessageHandler`.
</blockquote></details>

The map needs to store a pointer value (see discussion with Erik below), so its value type is a `*IncomingRaftMessageHandler`, not a `IncomingRaftMessageHandler`. So we unfortunately can't perform the simplification.
___
*[`pkg/util/syncutil/int_map.go` line 24 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-NtBwFgV8pcwGzAu7RHE:-Nto1MfS-GAVltkJ8UqR:b-9my5v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ee2339fc19ff705b91ce065f8e73b48b554f25e/pkg/util/syncutil/int_map.go#L24)):*
> Is it to keep the same expunged handling?

Yes, that's correct. The map relies on being able to perform atomic swaps of values in the `entry` struct. That requires an 8-byte value size, so to keep this generic (not assume <= 8 byte sized values), `sync.Map` adds indirection through an `any` interface. @petermattis recognized in 8340120c that the use of an `atomic.Pointer[any]` (`atomic.Value` at the time) had a runtime cost that was unnecessary for majority of cases that were already storing pointer values. So to avoid the double pointer indirection, we store `*V` instead of `V`.
___
*[`pkg/util/syncutil/int_map.go` line 423 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-NtC0WBaAsJH-D1Ieb5-:-Nto0xJ6E7-9uYGdRwzt:bxy0em) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ee2339fc19ff705b91ce065f8e73b48b554f25e/pkg/util/syncutil/int_map.go#L423)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm surprised this doesn't run afoul the checkptr checks performed by the Go runtime that take place under race. Those checks try to verify that the memory pointed to by the start of `expunged` and `uintptr(expunged)+sizeof(V)-1` are part of the same memory allocation.
</blockquote></details>

Good catch. It actually does when the `V` type is larger than an `int64`. I've updated this to construct and use a different `*V` for each map, which is a bit more verbose but should have a negligible runtime cost (confirmed with benchmarks). I'd happily take suggestions if you know of a better way to accomplish this.

**Review by petermattis — APPROVED** [review]
> > I wonder if switching to `swiss.Map` can recover any of the performance penalty.
> 
> I was thinking we would just pick that up when [golang/go#54766](https://github.com/golang/go/issues/54766) lands.

That might take a while. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-:-NtpeGO71eNtqdXQXtoA:b7xxlvu)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker, @nvanbenschoten, and @pav-kv)

___
*[`pkg/util/syncutil/int_map.go` line 423 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-NtC0WBaAsJH-D1Ieb5-:-NtpeqCXCbZIiOt1FLOH:bshtmmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ee2339fc19ff705b91ce065f8e73b48b554f25e/pkg/util/syncutil/int_map.go#L423)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Good catch. It actually does when the `V` type is larger than an `int64`. I've updated this to construct and use a different `*V` for each map, which is a bit more verbose but should have a negligible runtime cost (confirmed with benchmarks). I'd happily take suggestions if you know of a better way to accomplish this.
</blockquote></details>

I don't think you ever dereference the expunged sentinel, so you could use a `//go:nocheckptr` declaration on the previous implementation. This is what the `swiss.Map` implementation does for a similar issue. See https://github.com/cockroachdb/swiss/blob/main/map.go#L1692-L1703. Not sure it matters much in this case.

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r=petermattis,pav-kv,erikgrinaker

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-:-O1NO0794sVPMKZ8w9mU:b-2whc31)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker, @pav-kv, and @petermattis)

___
*[`pkg/util/syncutil/int_map.go` line 423 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120604#-NtC0WBaAsJH-D1Ieb5-:-O1NNxe8APWvcgHhkAmm:b-95zmqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ee2339fc19ff705b91ce065f8e73b48b554f25e/pkg/util/syncutil/int_map.go#L423)):*
> I don't think you ever dereference the expunged sentinel, so you could use a `//go:nocheckptr` declaration on the previous implementation.

Done. Thanks for the tip.

**Pull request merged**
