### PR TITLE
vendor: glide up

### PR DESCRIPTION
**Pull request by dt**
No scary changes -- mostly docs and comment changes.
etcd *does* include [a raft change](https://github.com/coreos/etcd/compare/d844440ffbf5e88c3d3d3e18fc80d184156696f9...cfd10b4bbfc6a9a1cf2d3f5ec8e31dae31e15122#diff-11229a7d1667ed7dbb08201d40f8e600): ben's[ `raft: Export Progress.IsPaused`](https://github.com/coreos/etcd/pull/6938)

Changed:
    github.com/google/go-github: dccec7b5 -> 171a9316
        https://github.com/google/go-github/compare/dccec7b5f17234b8219494c2b5b03af034e08c04...171a9316fc826fdb616072bd967483452eb1e2cf
    github.com/pborman/uuid: 3d4f2ba2 -> 5007efa2
        https://github.com/pborman/uuid/compare/3d4f2ba23642d3cfd06bd4b54cf03d99d95c0f1b...5007efa264d92316c43112bc573e754bc889b7b1
    github.com/cockroachdb/cockroach-go: 31611c05 -> 2c874f13
        https://github.com/cockroachdb/cockroach-go/compare/31611c0501c812f437d4861d87d117053967c955...2c874f130e4765aea4655923ff11c4c111397a41
    honnef.co/go/staticcheck: 333d80cd -> 86601649
        https://github.com/dominikh/go-staticcheck/compare/333d80cd...86601649
    github.com/dustin/go-humanize: 2064d2b8 -> ef638b6c
        https://github.com/dustin/go-humanize/compare/2064d2b8b5e33b3e5d175b3d9c5b90ba7b212665...ef638b6c2e62b857442c6443dace9366a48c0ee2
    github.com/coreos/etcd: d844440f -> cfd10b4b
        https://github.com/coreos/etcd/compare/d844440ffbf5e88c3d3d3e18fc80d184156696f9...cfd10b4bbfc6a9a1cf2d3f5ec8e31dae31e15122
    github.com/docker/distribution: c5999557 -> 67095fbc
        https://github.com/docker/distribution/compare/c59995570762ec8ef1b1d5a0b147600622979cb1...67095fbce3e4b079c3db62d08836548854a4b7ad
    golang.org/x/sys: ca83bd2c -> 478fcf54
        https://github.com/golang/sys/compare/ca83bd2c...478fcf54
    github.com/opencontainers/runc: 4271a8b5 -> 5974b4c7
        https://github.com/opencontainers/runc/compare/4271a8b5aec07d69f128df5474dea064d4694832...5974b4c7a1a4d4579c0c25cbb01b0070d1285bbc
    golang.org/x/tools: 366e2704 -> ae1141fc
        https://github.com/golang/tools/compare/366e2704...ae1141fc

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12116)

### CODE REVIEW

**Comment by tamird** [comment]
You have much to learn, young padawan. Please include links to relevant upstream changes, for I am lazy.

**Comment by dt** [comment]
https://github.com/cockroachdb/cockroach/pull/12116/files#diff-7c3613dba5171cb6027c67835dd3b9d4

**Comment by tamird** [comment]
Actually, please include links to all the changes you included in the commit message, because you're otherwise making work for the reviewer (me).

**Comment by tamird** [comment]
...that's useless. I want to see upstream's commit messages, not review their code.

**Comment by dt** [comment]
(i don't have the yams-diff-to-upstream-`compare`-links thing done yet)

**Comment by tamird** [comment]
Yeah, that's fine, so do it by hand like I do.

**Comment by dt** [comment]
added some detail to the PR desc -- I'll amend it into the commit too when I fix the LogEvent deprecation issues.

**Comment by dt** [comment]
after chatting with @RaduBerinde about the opentracing deprecation warnings that are now caught by staticcheck, I added all those to the metacheck ignores -- the internal representation of a LogEvent and a LogFields is different and any implementations, like lightstep or testTracer, that match on that, need to be updated before we can change what we're calling.

**Comment by tamird** [comment]
please link to the etcd PR, not just a vague description of the change. LGTM otherwise.

**Pull request merged**
