### PR TITLE
sql: Link unimplemented errors back to GitHub issues where possible

### PR DESCRIPTION
**Pull request by nvb**
This change adds functionality to allow us to link unimplemented
behavior back to GitHub issues. It then uses this error handling to
improve the errors displayed by a few commonly requested features,
including:
- Joins
- Arrays
- SERIAL types
- COLLATE clauses

This was inspired by the Rust compiler, which will display errors like:

```
Nathans-MacBook-Pro:cockroach_example$ cargo build
   Compiling cockroach_example v0.1.0 (file:///Users/nathan/Rust/cockroach_example)
src/main.rs:52:27: 52:32 error: box pattern syntax is experimental (see issue #29641)
src/main.rs:52             Err(Error::Db(box e)) => {
```

I found this extremely helpful, as it directed me to exactly where I wanted to go.
I imagine doing the same thing will reduce the number of questions we get about 
a few commonly requested features.

@mjibson Do we need to modify your railroad diagram generator to ignore
`unimplementedWithIssueError` as well?

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6761)

### CODE REVIEW

**Comment by tamird** [comment]
consider emitting URIs so they can be cmd-clicked

LGTM but someone who lives in this code should review

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> #### sql: Link unimplemented errors back to GitHub issues where possible
> 
> This change adds functionality to allow us to link unimplemented
> 
> behavior back to GitHub issues. It then uses this error handling to
> 
> improve the errors displayed by a few commonly requested features,
> 
> including:
> 
> - Joins
> 
> - Arrays
> 
> - SERIAL types
> 
> - COLLATE clauses
> 
> 
> 
> This was inspired by the Rust compiler, which will display errors like:
> 
> ```
> 
> Nathans-MacBook-Pro:cockroach_example$ cargo build
> 
>    Compiling cockroach_example v0.1.0 (file:///Users/nathan/Rust/cockroach_example)
> 
> src/main.rs:52:27: 52:32 error: box pattern syntax is experimental (see issue #29641)
> 
> src/main.rs:52             Err(Error::Db(box e)) => {
> 
> ```
> 
> I found this extremely helpful, as it directed me to exactly where I wanted to go.
> 
> I imagine doing the same thing will reduce the number of questions we get about 
> 
> a few commonly requested features.
> 
> 
> 
> @mjibson Do we need to modify your railroad diagram generator to ignore
> 
> `unimplementedWithIssueError` as well?
> 
> 
> 
</details>


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-:-KI0ns_PxIZnzjD_hhtm:-1556530442)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/select.go, line 384 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3IhKrPHfKFi4DM8Ca:-KI3IhKsG8I0DXMC-tjG:-144612405) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0fd1733c915dd40b537c324660a25e23f8b5f1/sql/select.go#L384)):*
> ```Go
> 		ate, ok := from[0].(*parser.AliasedTableExpr)
> 		if !ok {
> 			return util.Errorf("TODO(pmattis): unsupported FROM: %s (see issue #2970)", from)
> ```

the TODO can be removed. Maybe just use the same "JOINs and SELECTs from multiple tables are not  yet supported" message.

---

*[sql/select.go, line 409 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3IO1ZQPMoxLsloYev:-KI3IO1ZQPMoxLsloYew:305243793) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0fd1733c915dd40b537c324660a25e23f8b5f1/sql/select.go#L409)):*
> ```Go
> 
> 		default:
> 			panic(fmt.Sprintf("unexpected SimpleTableExpr type: %T", expr))
> ```

Ah lol, I put the "multiple tables" message in the wrong `default`. This message should go into the `default:` case below, and we should add the issue number too.

---

*[sql/parser/parse.go, line 73 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3J-aH1Js-D4ZBKZCt:-KI3J-aH1Js-D4ZBKZCu:285841412) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0fd1733c915dd40b537c324660a25e23f8b5f1/sql/parser/parse.go#L73)):*
> ```Go
> 		case errUnimplemented:
> 			err = errUnimplemented
> 		default:
> ```

why not a `case unimplementedWithIssueError`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761)*

**Comment by nvanbenschoten** [comment]
Yeah I was going back and forth between URIs and just the issue numbers. As long as the links are stable, they should be fine.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> consider emitting URIs so they can be cmd-clicked
> 
> LGTM but someone who lives in this code should review
</details>


---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/select.go, line 384 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3IhKrPHfKFi4DM8Ca:-KI3PW1BNPXUTtk0K3JT:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0fd1733c915dd40b537c324660a25e23f8b5f1/sql/select.go#L384)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> the TODO can be removed. Maybe just use the same "JOINs and SELECTs from multiple tables are not  yet supported" message.
</details>
Done.

---

*[sql/select.go, line 409 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3IO1ZQPMoxLsloYev:-KI3PViRriOpEFeTwikN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0fd1733c915dd40b537c324660a25e23f8b5f1/sql/select.go#L409)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah lol, I put the "multiple tables" message in the wrong `default`. This message should go into the `default:` case below, and we should add the issue number too.
</details>
Done.

---

*[sql/parser/parse.go, line 73 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3J-aH1Js-D4ZBKZCt:-KI3NRr9JHCJdnrNVna5:612284871) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0fd1733c915dd40b537c324660a25e23f8b5f1/sql/parser/parse.go#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> why not a `case unimplementedWithIssueError`?
</details>
Unfortunately value switches and type switches don't play well together. If you have ideas to make this less ugly though, I'm all ears. Maybe a full blown type switch in the default block, so that it's at least fully extensible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-:-KI3Pj1kxi_ctvG3xpZO:76625186)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/parse.go, line 73 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3J-aH1Js-D4ZBKZCt:-KI3Rmmypb1qNiRg42Xy:-1092782033) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0fd1733c915dd40b537c324660a25e23f8b5f1/sql/parser/parse.go#L73)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Unfortunately value switches and type switches don't play well together. If you have ideas to make this less ugly though, I'm all ears. Maybe a full blown type switch in the default block, so that it's at least fully extensible.
</details>
Ah, I see. We could simplify to:
```
if r := recover(); r != nil {
   // Panic on anything except unimplemented errors.
   if _, ok := r.(unimplementedWithIssueError); !ok && err != errUnimplemented {
      panic(r)
   }
   err = r.(error)
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/select.go, line 418 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3TvnDdSL8VouBo0bF:-KI3TvnDdSL8VouBo0bG:-2136033512) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68b9879a487e1f7ce50fe800c853e5308eedc6c/sql/select.go#L418)):*
> ```Go
> 		colAlias = ate.As.Cols
> 	default:
> 		s.err = fmt.Errorf("JOINs and SELECTs from multiple tables are not yet supported: %s",
> ```

add issue # here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761)*

**Comment by tamird** [comment]
Why not reuse the unimplementedWIthIssueError type in the sql package? This type can live in util.

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Yeah I was going back and forth between URIs and just the issue numbers. As long as the links are stable, they should be fine.
</details>


---

Reviewed 5 of 5 files at r4, 1 of 1 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-:-KI3U11ZkgHSj71iXT6H:-467808793)*

**Comment by RaduBerinde** [comment]
^That would be nice, especially is we want URLs in the message. We can have the type include a string msg as well and have a `UnimplementedWithIssueErrorf(issue, fmt, args...)` function.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Why not reuse the unimplementedWIthIssueError type in the sql package? This type can live in util.
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-:-KI3UvfvOXQBSb2WI7ER:876246537)*

**Comment by nvanbenschoten** [comment]
Done.

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> ^That would be nice, especially is we want URLs in the message. We can have the type include a string msg as well and have a `UnimplementedWithIssueErrorf(issue, fmt, args...)` function.
</details>


---

Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/select.go, line 418 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3TvnDdSL8VouBo0bF:-KI3VVWb_JvciL76RxL9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68b9879a487e1f7ce50fe800c853e5308eedc6c/sql/select.go#L418)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> add issue # here
</details>
Done.

---

*[sql/parser/parse.go, line 73 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3J-aH1Js-D4ZBKZCt:-KI3_WIYWT9FcD7B9r2g:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0fd1733c915dd40b537c324660a25e23f8b5f1/sql/parser/parse.go#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah, I see. We could simplify to:
> ```
> if r := recover(); r != nil {
>    // Panic on anything except unimplemented errors.
>    if _, ok := r.(unimplementedWithIssueError); !ok && err != errUnimplemented {
>       panic(r)
>    }
>    err = r.(error)
> }
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-:-KI3ccmKwTSXhiEsUkBt:-499146009)*

**Comment by RaduBerinde** [comment]
Awesome! :lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Done.
</details>


---

Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[util/error.go, line 51 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3hoShsUV6Cz7xTEHu:-KI3hoShsUV6Cz7xTEHv:160409987) ([raw file](https://github.com/cockroachdb/cockroach/blob/975208f14f2cabdf73d702ae06b34911307c54d4/util/error.go#L51)):*
> ```Go
> 
> // UnimplementedWithIssueError is an error that links unimplemented functionality back
> // to it's issue on GitHub.
> ```

its

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-:-KI3hs-RhFsw0MWZHImg:934438921)*

**Comment by bdarnell** [comment]
+1 to urls instead of issue numbers. It would be good to be able to include links in error messages even when the content lives in the docs or wiki instead of the issue tracker.

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/sql.go, line 17 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3iQGXazJNz5d2DmYO:-KI3iQGYyVXL08KjHPSD:-1871755087) ([raw file](https://github.com/cockroachdb/cockroach/blob/975208f14f2cabdf73d702ae06b34911307c54d4/sql/parser/sql.go#L17)):*
> ```Go
> )
> 
> var errUnimplemented = errors.New("unimplemented")
> ```

in a follow-up, it'd be good to get rid of this and make all unimplemented bits refer to issues

---

*[util/error.go, line 68 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3ipYn4EGBnW3UaKdH:-KI3ipYn4EGBnW3UaKdI:1674495597) ([raw file](https://github.com/cockroachdb/cockroach/blob/975208f14f2cabdf73d702ae06b34911307c54d4/util/error.go#L68)):*
> ```Go
> // UnimplementedWithIssueErrorf constructs an UnimplementedWithIssueError with the
> // provided issue and formatted message.
> func UnimplementedWithIssueErrorf(issue int, msg string, args ...interface{}) error {
> ```

you should add this method to the list of things `vet` checks for us (in check-style.sh).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761)*

**Comment by mjibson** [comment]
The diagram generator can easily adapt to this. Don't worry about it.

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> +1 to urls instead of issue numbers. It would be good to be able to include links in error messages even when the content lives in the docs or wiki instead of the issue tracker. 
</details>


---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-:-KI3rrukWownfBJlCKMR:-805020819)*

**Comment by nvanbenschoten** [comment]
@bdarnell: I agree, but let's save those for a different PR.

@mjibson Thanks!

<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> The diagram generator can easily adapt to this. Don't worry about it.
</details>


---

Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/sql.go, line 17 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3iQGXazJNz5d2DmYO:-KI4D-nm15QjexkkqrBv:-791314142) ([raw file](https://github.com/cockroachdb/cockroach/blob/975208f14f2cabdf73d702ae06b34911307c54d4/sql/parser/sql.go#L17)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> in a follow-up, it'd be good to get rid of this and make all unimplemented bits refer to issues
</details>
I agree. 

---

*[util/error.go, line 51 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3hoShsUV6Cz7xTEHu:-KI4FUm3164dJaN5aonn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/975208f14f2cabdf73d702ae06b34911307c54d4/util/error.go#L51)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> its
</details>
Done.

---

*[util/error.go, line 68 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3ipYn4EGBnW3UaKdH:-KI4FlNxG1Y-NGQGlZcU:455311657) ([raw file](https://github.com/cockroachdb/cockroach/blob/975208f14f2cabdf73d702ae06b34911307c54d4/util/error.go#L68)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> you should add this method to the list of things `vet` checks for us (in check-style.sh).
</details>
What do you want to check? That this is always used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-:-KI4GHx8t0m4HYloGu-G:45391491)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[util/error.go, line 68 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3ipYn4EGBnW3UaKdH:-KI4JHM2J5OnEQYpYDjD:1874464477) ([raw file](https://github.com/cockroachdb/cockroach/blob/975208f14f2cabdf73d702ae06b34911307c54d4/util/error.go#L68)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> What do you want to check? That this is always used?
</details>
No, that this is used correctly. see the -printfuncs argument to vet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/error.go, line 68 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3ipYn4EGBnW3UaKdH:-KI4QQD__3hKPYj7hOJk:-1562673301) ([raw file](https://github.com/cockroachdb/cockroach/blob/975208f14f2cabdf73d702ae06b34911307c54d4/util/error.go#L68)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> No, that this is used correctly. see the -printfuncs argument to vet
</details>
Neat! I didn't know about that.

I'm not sure it's usable with functions that take other parameters though, as I get the error
```
sql/select.go:384: constant 2970 not a string in call to UnimplementedWithIssueErrorf
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/error.go, line 68 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-KI3ipYn4EGBnW3UaKdH:-KI4exwWRhmiWdEAoVie:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/975208f14f2cabdf73d702ae06b34911307c54d4/util/error.go#L68)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Neat! I didn't know about that.
> 
> I'm not sure it's usable with functions that take other parameters though, as I get the error
> ```
> sql/select.go:384: constant 2970 not a string in call to UnimplementedWithIssueErrorf
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761)*

**Comment by RaduBerinde** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> @bdarnell: I agree, but let's save those for a different PR.
> 
> @mjibson Thanks!
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6761#-:-KI4kNDJey6IkDV34iIy:1417088721)*

**Pull request merged**
