### PR TITLE
roachtest: port rebalance/by-load/*/mixed-version to new framework

### LINKED ISSUE #115134: roachtest: port rebalance/by-load/leases/mixed-version to the new mixed-version framework
See the parent issue [1] for details.

[1] https://github.com/cockroachdb/cockroach/issues/110528

Jira issue: CRDB-33906

### LINKED ISSUE #115135: roachtest: port rebalance/by-load/replicas/mixed-version to the new mixed-version framework
See the parent issue [1] for details.

[1] https://github.com/cockroachdb/cockroach/issues/110528

Jira issue: CRDB-33904

### PR DESCRIPTION
**Pull request by kvoli**
Port `rebalance/by-load/leases/mixed-version` and
`rebalance/by-load/replicas/mixed-version` to the new mixed-version
framework as described in https://github.com/cockroachdb/cockroach/issues/110528.

Part of: https://github.com/cockroachdb/cockroach/issues/110528
Resolves: https://github.com/cockroachdb/cockroach/issues/115134
Resolves: https://github.com/cockroachdb/cockroach/issues/115135
Release note: None

---

`ts_util.go` provides helper functions for querying the cluster
timeseries database over http. These methods previously made use of
`httputil.PostJSON` for requesting timeseries. This commit updates to
use `httputil.PostProtobuf`, in order to allow ignoring optional fields
when the server doesn't support them; namely `TenantID`.

Epic: none
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
<details><summary>Passes remote run</summary>

```
$ roachtest run 'rebalance/by-load/'
...
=== RUN   rebalance/by-load/replicas/mixed-version  [metrics: https://go.crdb.dev/roachtest-grafana/kvoli-1701725271/rebalance-by-load-replicas-mixed-version/1701725437558/1701727237558]
=== RUN   rebalance/by-load/leases  [metrics: https://go.crdb.dev/roachtest-grafana/kvoli-1701725271/rebalance-by-load-leases/1701725441471/1701727241471]
=== RUN   rebalance/by-load/leases/mixed-version  [metrics: https://go.crdb.dev/roachtest-grafana/kvoli-1701725271/rebalance-by-load-leases-mixed-version/1701725458329/1701727258329]
=== RUN   rebalance/by-load/replicas/ssds=2  [metrics: https://go.crdb.dev/roachtest-grafana/kvoli-1701725271/rebalance-by-load-replicas-ssds-2/1701725496171/1701727296171]
=== RUN   rebalance/by-load/replicas  [metrics: https://go.crdb.dev/roachtest-grafana/kvoli-1701725271/rebalance-by-load-replicas/1701725528188/1701727328188]
--- PASS: rebalance/by-load/leases (106.38s)
--- PASS: rebalance/by-load/replicas/ssds=2 (109.96s)
No work remaining; runWorker is bailing out...
--- PASS: rebalance/by-load/replicas (148.87s)
No work remaining; runWorker is bailing out...
No work remaining; runWorker is bailing out...
--- PASS: rebalance/by-load/leases/mixed-version (1222.12s)
No work remaining; runWorker is bailing out...
--- PASS: rebalance/by-load/replicas/mixed-version (1785.40s)
No work remaining; runWorker is bailing out...
PASS

```
<p>



</p>
</details>

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115559#-:-Nkw8QL-BZafIi1T_uyE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @kvoli, and @srosenberg)

___
*[`-- commits` line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115559#-Nkw6s9m7tIOzkSTjTcf):*
nit: missing space between Port and `rebalance/...
___
*[`pkg/cmd/roachtest/tests/rebalance_load.go` line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115559#-Nkw8E084nuTsKHV_hGi:-Nkw8E084nuTsKHV_hGj:b-8s37yo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf85d3a03eebc19335c66b6b013c0b6f968d1255/pkg/cmd/roachtest/tests/rebalance_load.go#L249)):*
> ```Go
> 	require.NoError(t, WaitFor3XReplication(ctx, t, db))
> 
> 	var m *errgroup.Group // see comment in version.go
> ```

What comment is this referring to?

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115559#-:-NkwJEX3-kddTeSZpbn4:b-80sls6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @nvanbenschoten, and @srosenberg)

___
*[`-- commits` line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115559#-Nkw6s9m7tIOzkSTjTcf):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: missing space between Port and `rebalance/...
</blockquote></details>

Added a space here.
___
*[`pkg/cmd/roachtest/tests/rebalance_load.go` line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115559#-Nkw8E084nuTsKHV_hGi:-NkwInzO3_n_7FxKOajX:b-gqwbr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf85d3a03eebc19335c66b6b013c0b6f968d1255/pkg/cmd/roachtest/tests/rebalance_load.go#L249)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What comment is this referring to?
</blockquote></details>

Comes from 094bf14008ea48bdb60bce024c1d939c0dddee6e.

Probably referring to deficiency of monitors for workload runners (5 years ago)?
https://github.com/cockroachdb/cockroach/blob/094bf14008ea48bdb60bce024c1d939c0dddee6e/pkg/cmd/roachtest/version.go#L101

I removed the comment here, but will leave the errgroup to not shuffle around too much in this PR.

**Comment by kvoli** [comment]
TYFTR

bors r=nvanbenschoten

**Comment by renatolabs** [comment]
👋 backport reminder -- would be nice to have this in 23.2 and even in 23.1 if applicable.

**Pull request merged**
