### PR TITLE
storage: support per-store IO metrics with fine granularity

### LINKED ISSUE #104114: storage: investigate host-level I/O metrics; consider pre-store
Cockroach services a few host-level I/O timeseries metrics, (eg, `sys.host.disk.read.bytes`).

These metrics are maintained on the  `pkg/server/status.RuntimeStatSampler` type, and updated here.: 
https://github.com/cockroachdb/cockroach/blob/b5feced9eff45e55d65f2ebbceef1839ae4f1278/pkg/server/status/runtime.go#L515-L533

This logic sums these disk stats across all visible devices.

https://github.com/cockroachdb/cockroach/blob/b5feced9eff45e55d65f2ebbceef1839ae4f1278/pkg/server/status/disk_counters.go#L24-L48

https://github.com/cockroachdb/cockroach/blob/b5feced9eff45e55d65f2ebbceef1839ae4f1278/pkg/server/status/runtime.go#L707-L724

The stats come from `gopsutil`, which on Linux reads `/proc/diskstats`:
https://github.com/shirou/gopsutil/blob/32e8a92ad6ba363a9cbc05ea9e284c11c723efe3/disk/disk_linux.go#L389-L483

We should
- [ ] double check that these `sys.host.disk.*` metrics are not currently reported per store.
- [ ] consider reporting per-store metrics that only reflect each individual store's I/O. Note that admission control already collects per-store metrics for its purposes through maintaining a mapping between device name and store ID [pkg/server/node.go#L867-L896](https://github.com/cockroachdb/cockroach/blob/473b460cfdb2ab8b0d52e887a14ac1e6899496b6/pkg/server/node.go#L867-L896). Maybe these could be unified? (cc @irfansharif)

### LINKED ISSUE #112898: storage: granular IO metrics
Our existing timeseries metrics are collected on a 10s interval. This coarse granularity makes it impossible to detect events of high variance within the 10s interval. A momentary spike of 16k IO operations in 1 second can be presented as 1.6k IOPS over the 10s interval. A spike like this could force IO operations to queue, inducing latency beyond what our customers consider acceptable, without leaving a trace of the latency's source.

We should collect finer, per-second metrics for select metrics. We shouldn't wait for our timeseries infrastructure to support finer resolution for some metrics. We can surface these metrics through a few strategies:

- Export timeseries metrics that compute aggregation function over the per-second deltas: For example, the maximum delta between per-second measurements would be enough to give us a much better view into a momentary IOPS spike.
- Write these metrics to the Pebble logs every N-seconds and include each of the per-second measurements over the past N seconds.
- Write finer metrics to logs only once there's a significant change (defining this may be tricky, and probably needs to be done per-metric)

Jira issue: CRDB-32668

### PR DESCRIPTION
**Pull request by CheranMahalingam**
Currently, timeseries metrics are collected on a 10s interval which hides momentary spikes in IO. This commit introduces a central disk monitoring system that polls for disk stats at a 100ms interval. Additionally, the current system accumulates disk metrics across all block devices which includes noise from unrelated processes. This commit also adds support for exporting per-store IO metrics (i.e. IO stats for block devices that map to stores used by Cockroach).

These changes will be followed up by a PR to remove the need for customers to specify disk names when setting the provisioned bandwidth for each store as described in #109350.

Fixes: #104114, #112898.
Informs: #89786.

Epic: None.
Release note: None.

### CODE REVIEW

**Comment by CheranMahalingam** [comment]
These changes were verified e2e by running a 3-node cluster, each with additional ebs volumes to run 2 stores.
```
roachprod create $CLUSTER -n=3 --clouds=aws \
--aws-zones=us-east-1b:6 \
--aws-machine-type-ssd=i4i.8xlarge \
--aws-enable-multiple-stores=true \
--aws-ebs-volume='{"VolumeType":"gp3","VolumeSize":5000,"Iops":16000,"Throughput":1000}' \
--aws-ebs-volume='{"VolumeType":"gp3","VolumeSize":5000,"Iops":16000,"Throughput":1000}'

roachprod put $CLUSTER artifacts/cockroach
roachprod start $CLUSTER --store-count=2
```

**Review by abarganier — COMMENTED** [review]
Cool! At first glance, from an observability perspective, the overall idea looks sound to me. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-:-Nsn7X5vCvOrq1oz6j72:b-lceznd)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @CheranMahalingam, @itsbilal, and @jbowens)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-Nsn5Qq_BuZqxlvBAbeg):*
The diff is quite large though, which makes it a big task to review. Any chance we can break it up into a few smaller commits to make it easier to review? For example:

> This commit introduces a central disk monitoring system that polls for disk stats at a 100ms interval.

This could be one commit.

> Additionally, the current system accumulates disk metrics across all block devices which includes noise from unrelated processes.

And maybe this could be another commit.

>  This commit adds support for exporting per-store IO metrics

And this could be the final commit.

It also creates an opportunity to provide better documentation about each change via separate commit messages. 



_Code quote:_
```
  Currently, timeseries metrics are collected on a 10s interval which
  hides momentary spikes in IO operations. This commit introduces a
  central disk monitoring system that polls for disk stats at a 100ms
  interval. Additionally, the current system accumulates disk metrics
  across all block devices which includes noise from unrelated processes.
  This commit adds support for exporting per-store IO metrics (i.e. IO
  stats for block devices that map to stores used by Cockroach).
```
___
*[`pkg/storage/disk/monitor.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-Nsn5ye62_VuuTJLDKKc:-Nsn5ye62_VuuTJLDKKd:b-w07gmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/930890a8ad039662290157a9cca43bc3f1a2722f/pkg/storage/disk/monitor.go#L38)):*
> ```Go
> }
> 
> // MonitorManager provides observability into a pool of disks.
> ```

nit: More information about how it provides o11y/how it's intended to be used/etc would be helpful here.



_Code quote:_
```Go
// MonitorManager provides observability into a pool of disks.
```
___
*[`pkg/storage/disk/monitor.go` line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-Nsn7Prs2Wn6lNOG1EpQ:-Nsn7Prs2Wn6lNOG1EpR:bp2xbls) ([raw file](https://github.com/cockroachdb/cockroach/blob/930890a8ad039662290157a9cca43bc3f1a2722f/pkg/storage/disk/monitor.go#L166)):*
> ```Go
> 	// the count is zero, the MonitorManager no longer needs to collect stats
> 	// for this device.
> 	refCount int // protected by manager.mu
> ```

nit: Is there a reason it can't be protected by the `monitoredDisk`'s own mutex? 



_Code quote:_
```Go
	refCount int // protected by manager.mu
```

**Review by jbowens — COMMENTED** [review]
> Reviewed 5 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119885)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @CheranMahalingam, and @itsbilal)

___
*[`pkg/kv/kvserver/store.go` line 3350 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-NsoWzsYEEOWiggoNh3d:-NsoWzsYEEOWiggoNh3e:b328y67) ([raw file](https://github.com/cockroachdb/cockroach/blob/930890a8ad039662290157a9cca43bc3f1a2722f/pkg/kv/kvserver/store.go#L3350)):*
> ```Go
> 	// Get disk stats for the disk associated with this store.
> 	if s.diskMonitor != nil {
> 		diskStats, err := s.diskMonitor.IncrementalStats()
> ```

I think in this instance we should report the cumulative stats and the client can take the rate if they're interested in that
___
*[`pkg/storage/disk/monitor.go` line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-NsoVuQ7DmhfeaZvQJOk:-NsoVuQ7DmhfeaZvQJOl:bk6ten8) ([raw file](https://github.com/cockroachdb/cockroach/blob/930890a8ad039662290157a9cca43bc3f1a2722f/pkg/storage/disk/monitor.go#L118)):*
> ```Go
> 		}
> 	}
> 	//nolint:deferunlockcheck
> ```

rather than disabling the lint, I think we should use a defer but within an anonymous function, eg:

```
func() {
    m.mu.Lock()
    defer m.mu.Unlock()
    // ...
}()

if stop != nil {
    stop <- struct{}{}
}

```
___
*[`pkg/storage/disk/monitor.go` line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-Nsn7Prs2Wn6lNOG1EpQ:-NsoWN-69KpAoyyeRX2j:bhypsrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/930890a8ad039662290157a9cca43bc3f1a2722f/pkg/storage/disk/monitor.go#L166)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: Is there a reason it can't be protected by the `monitoredDisk`'s own mutex?
</blockquote></details>

the manager is responsible for ensuring the `monitoredDisk` is a singleton, which requires atomicity over the ref count. this would be good to include in the comment above refCount

**Review by CheranMahalingam — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-:-NsoKfQH-HAmi8lOZT5q:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @itsbilal, and @jbowens)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-Nsn5Qq_BuZqxlvBAbeg):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

The diff is quite large though, which makes it a big task to review. Any chance we can break it up into a few smaller commits to make it easier to review? For example:

> This commit introduces a central disk monitoring system that polls for disk stats at a 100ms interval.

This could be one commit.

> Additionally, the current system accumulates disk metrics across all block devices which includes noise from unrelated processes.

And maybe this could be another commit.

>  This commit adds support for exporting per-store IO metrics

And this could be the final commit.

It also creates an opportunity to provide better documentation about each change via separate commit messages.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/store.go` line 3350 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-NsoWzsYEEOWiggoNh3d:-NssvNsP7YG2J8D6Kg8f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/930890a8ad039662290157a9cca43bc3f1a2722f/pkg/kv/kvserver/store.go#L3350)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think in this instance we should report the cumulative stats and the client can take the rate if they're interested in that
</blockquote></details>

Done.
___
*[`pkg/storage/disk/monitor.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-Nsn5ye62_VuuTJLDKKc:-NsoH3NCCBKHMF5nkQzg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/930890a8ad039662290157a9cca43bc3f1a2722f/pkg/storage/disk/monitor.go#L38)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: More information about how it provides o11y/how it's intended to be used/etc would be helpful here.
</blockquote></details>

Done.
___
*[`pkg/storage/disk/monitor.go` line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-NsoVuQ7DmhfeaZvQJOk:-NssVQg27PaoEheqOYOK:b-54e74h) ([raw file](https://github.com/cockroachdb/cockroach/blob/930890a8ad039662290157a9cca43bc3f1a2722f/pkg/storage/disk/monitor.go#L118)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

rather than disabling the lint, I think we should use a defer but within an anonymous function, eg:

```
func() {
    m.mu.Lock()
    defer m.mu.Unlock()
    // ...
}()

if stop != nil {
    stop <- struct{}{}
}

```
</blockquote></details>

Nice, I didn't think about that.
___
*[`pkg/storage/disk/monitor.go` line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-Nsn7Prs2Wn6lNOG1EpQ:-NssqxvM1-DPyeha60Ly:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/930890a8ad039662290157a9cca43bc3f1a2722f/pkg/storage/disk/monitor.go#L166)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

the manager is responsible for ensuring the `monitoredDisk` is a singleton, which requires atomicity over the ref count. this would be good to include in the comment above refCount
</blockquote></details>

Done.

**Review by jbowens — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 4 files at r4, 1 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119885#-:-NsyJbb63t730BKUxsuG:b-uwkowd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @itsbilal)

**Comment by CheranMahalingam** [comment]
bors r=jbowens,abarganier

**Comment by jbowens** [comment]
bors r-

@CheranMahalingam I think you need to rebase over master.

**Comment by CheranMahalingam** [comment]
bors r=jbowens,abarganier

**Pull request merged**
