### PR TITLE
schemachanger: check explain diagrams during rollback test

### PR DESCRIPTION
**Pull request by postamar**
This commit enriches the declarative schema changer integration tests by
making data-driven EXPLAIN output assertions easier to add as
a complement to otherwise unrelated tests. In particular, this commit
improves the rollback test to check the explained rollback plan for each
post-commit revertible stage. This should make it easier to debug bad
rule definitions which otherwise would manifest themselves as causing
the schema change to hang during the rollback.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
I was trying to rewrite some rules and struggled to debug them without any clear idea of what the expected plan was at rollback time. We also need more testing hooks inside the rollback test to catch planning errors like circular graphs etc but that's out of scope for this already considerable change (in terms of test artifacts at least).

**Comment by postamar** [comment]
This is ready for review. CI failures seem to be unrelated flakes.

**Review by ajwerner — APPROVED** [review]
:lgtm: I had hoped for this as an outcome after we made it one directive per test. Thanks for making it happen. 

> Reviewed 4 of 183 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85406#-:-N8P7SFE1Fpz-OSgjsoM:b-j7ktvh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[`pkg/sql/schemachanger/sctest/end_to_end.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85406#-N8P784zApeQu__usqbU:-N8P785-9azGoQEWFUcs:bb6snpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/04769dabebd926f8bacf202d47df0f2b6456271b/pkg/sql/schemachanger/sctest/end_to_end.go#L206)):*
> ```Go
> 		_, err := file.Write(prefixBuf.Bytes())
> 		require.NoError(t, err)
> 		_, err = fmt.Fprintf(file, "EXPLAIN (%s) %s;\n----\n", tag, explainedStmt)
> ```

Something rubs me the wrong way about using SQL syntax in `EXPLAIN (ddl, verbose) rollback at post-commit stage 1 of 7;` but not enough to block this strictly positive PR. I think I'd prefer if this was somehow a SQL-level comment, but I don't care that much.

**Comment by postamar** [comment]
Thanks for the review!

> Something rubs me the wrong way about using SQL syntax in EXPLAIN (ddl, verbose) rollback at post-commit stage 1 of 7; but not enough to block this strictly positive PR. I think I'd prefer if this was somehow a SQL-level comment, but I don't care that much.

I know, right? I don't like it either. I'm left with the feeling we're lacking some jobs abstractions here, something to trigger a job failure when a particular condition is met. A bit like pausepoints; "failpoints" perhaps?

**Pull request merged**
