### PR TITLE
tracing: add options to crash on use-after-Finish 

### PR DESCRIPTION
**Pull request by andreimatei**
Currently, uses of a Span after it has been Finish()ed are tolerated,
even though they're not supposed to be allowed. In the future, I want to
pool and reuse spans, so not using them after Finish() becomes more
important. The plans is to have such uses lead to trace corruption in
production. This patch adds detection of use-after-Finish() and makes
tests crash on it. Hopefully I've fixed all the bad code.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Only the last 3 commits are to be reviewed here. The rest are in different other PRs.

**Review by andreimatei — COMMENTED** [review]
> Only the last 3 commits are to be reviewed here. The rest are in different other PRs.

Rebased; all commits are original now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-:-Mqt9k4t9A-EKrOLhpkX:b2eagi1)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by dhartunian — APPROVED** [review]
:lgtm: a few nits and more questions.

> Reviewed 4 of 4 files at r2, 18 of 18 files at r8, 2 of 7 files at r9, 11 of 11 files at r10, 10 of 10 files at r11, 1 of 15 files at r12, 13 of 13 files at r13, 7 of 7 files at r14, 6 of 12 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-:-MqzDsvk68A23YpHE9Vo:bgpwvgz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @dhartunian)

___
*[pkg/util/tracing/span.go, line 67 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqygjT-A9l5W0Anmp7R:-MqygjT-A9l5W0Anmp7S:b-i7zo1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/span.go#L67)):*
> ```Go
> // net.Trace.
> //
> // As opposed to other spans, a noop span can be used after Finish(). In
> ```

Question: why is it necessary to allow this? Don't you want to catch all cases w/ post-Finish use and any noop span could easily be marked otherwise.
___
*[pkg/util/tracing/span.go, line 82 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqygzAmAktNWcUiiA1L:-MqygzAmAktNWcUiiA1M:b232ztk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/span.go#L82)):*
> ```Go
> 		return true
> 	}
> 	alreadyFinished := atomic.LoadInt32(&sp.finished) != 0
> ```

is it good practice to wrap the atomics in a getter/setter?
___
*[pkg/util/tracing/span.go, line 92 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqyhLXe-tRqGfFXr9st:-MqyhLXe-tRqGfFXr9su:b-g9kl53) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/span.go#L92)):*
> ```Go
> 			finishStack = sp.finishStack
> 		}
> 		panic(fmt.Sprintf("use of Span after Finish. Span: %s. Finish previously called at: %s",
> ```

Is the plan to eventually remove this? Just trying to understand if the code will stay forever because it's a bit odd to have a potential panic in a `done() bool` which looks on the surface like a benign state check.
___
*[pkg/util/tracing/span.go, line 117 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqyiiGq-L2DsZSFbbjc:-Mqyhkgf5Tz1mkzMLjfy:b-xcaer7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/span.go#L117)):*
> ```Go
> // Finishing a nil *Span is a noop.
> func (sp *Span) Finish() {
> 	if sp == nil || sp.IsNoop() || sp.done() {
> ```

The new code in `sp.done()` implies that calling `Finish()` twice is "bad". My instinct is that it should be ok to do. What am I missing?
___
*[pkg/util/tracing/span_test.go, line 434 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqzD59p6BTt1_hzv42K:-MqzD59p6BTt1_hzv42L:bvux3a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/span_test.go#L434)):*
> ```Go
> 				for i := 0; i < 20; i++ {
> 					t.Run("invoke", func(t *testing.T) {
> 						if i == 9 {
> ```

sorry, unrelated q: what is the purpose of this `if`?
___
*[pkg/util/tracing/tracer.go, line 504 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqywQzk9L6Y6hfYcJpm:-MqywQzl8tM1ay0QREaD:b-wq0tks) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/tracer.go#L504)):*
> ```Go
> // Span.Finish() call. These are presented when the finished span is reused.
> // This option is expensive.
> // It's invalid to set this is panicOnUseAfterFinish is not set.
> ```

nit: s/is/if/g

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73479)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

___
*[pkg/util/tracing/span.go, line 67 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqygjT-A9l5W0Anmp7R:-Mr-6Non3bcqZX6Tz9vz:b2hbjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/span.go#L67)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Question: why is it necessary to allow this? Don't you want to catch all cases w/ post-Finish use and any noop span could easily be marked otherwise.
</blockquote></details>

Well, the point of the noop spans is to be shared. Being shared, use-after-Finish is expected: everybody calls into and finishes the same noop span (Finish needs to be a no-op, like everything else). So use-after-Finish detection is fundamentally incompatible with the tracing mode where we don't actually create spans (i.e. `TracingModeOnDemand`)).

But the good news is that I hope there we won't use noop spans any more (we already don't in unit tests). `TracingModeOnDemand` will be dead, long live `TracingModeActiveSpansRegistry`.
___
*[pkg/util/tracing/span.go, line 82 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqygzAmAktNWcUiiA1L:-Mr-It31915jWBgKTqHF:b15yl44) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/span.go#L82)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is it good practice to wrap the atomics in a getter/setter?
</blockquote></details>

I'd say sometime, but not always. There's a navigability cost to making accessors - it takes extra steps to discover all the uses of a field. This particular field is only read in one place and written in one place, so I don't think there's much reason for accessors.
___
*[pkg/util/tracing/span.go, line 92 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqyhLXe-tRqGfFXr9st:-Mr-CNxI3txzTienQEWQ:bfys9jw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/span.go#L92)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Is the plan to eventually remove this? Just trying to understand if the code will stay forever because it's a bit odd to have a potential panic in a `done() bool` which looks on the surface like a benign state check.
</blockquote></details>

Crashing on use-after-Finish is intended to stay. I've renamed the function `detectUseAfterFinish()` to suggest that it can be more than a state check.
___
*[pkg/util/tracing/span.go, line 117 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqyiiGq-L2DsZSFbbjc:-Mr-Cq5NDjaphJCz9Ovd:b5p0t73) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/span.go#L117)):*
> My instinct is that it should be ok to do.

Why does your instinct say this? Allowing `Finish()` to be called multiple times is a sign that the respective object does not have clear ownership and lifetime. There are things and situations where it is reasonable to not require great control over the lifetime, and when you want to have some relaxed shared-ownership model, but these are more exceptions than the default. In the case of the Span, the lifetime is important because I want to reuse them. Once a Span is Finish()ed, I want to reuse it (technically it's more complicated than that; PR about it coming soon). If someone tries to Finish() a span a 2nd time, they'll end up finishing the wrong thing.

In the case of the Span, I've dug into the history of `Finish()` idempotency, cause one wonders why did anyone ever need it. I wish I hadn't dug.

Tobi made `Finish()` idempotent in https://github.com/cockroachdb/cockroach/pull/59992/commits/f93e92b19b4d14dc815106de31957f2050337d7a because he wanted to introduce a double-Finish in https://github.com/cockroachdb/cockroach/commit/3ae0f0638a7a8e2b5911ef57f88aa8494f2ac06c for (bad) reasons described in https://github.com/cockroachdb/cockroach/issues/60671.
Lucy then removed that double-Finish crap in https://github.com/cockroachdb/cockroach/pull/60714/commits/ffe4a45e9f164a13e2b0a030f902f07e77d57a41, but nobody reverted the idempotency.
___
*[pkg/util/tracing/span_test.go, line 434 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqzD59p6BTt1_hzv42K:-Mr-JUIyEHko5fOVwkn_:b-jk4kos) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/span_test.go#L434)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

sorry, unrelated q: what is the purpose of this `if`?
</blockquote></details>

The comment above tries to explain something about how the 10th call on a net.Trace is special and provokes a deadlock. So I think the author wanted to get a different stack for exactly the 10th call. It's kind of lol, don't know if I love it or hate it.
___
*[pkg/util/tracing/tracer.go, line 504 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-MqywQzk9L6Y6hfYcJpm:-Mr-K24355Pq6KrN05y7:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a2fa5d596370d5e9d981564fec5f3f7589677a4/pkg/util/tracing/tracer.go#L504)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: s/is/if/g
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73479#-:-Mr-Y3imEtDmN89QcjU8:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

**Pull request merged**
