### PR TITLE
roachtest: refactor tpchvec and add tpchvec/smallbatchsize

### LINKED ISSUE #46498: colexec: run tpchvec roachtest with batch size of 1

### PR DESCRIPTION
**Pull request by asubiotto**
The first commit is the refactor, the second is the test addition.

Release note: None (test changes)

Closes #46498

### CODE REVIEW

**Comment by asubiotto** [comment]
q9 with a batch size of 1 makes this take around 9min instead of 2. I still think the runtime is reasonable for a roachtest though. Might try slightly increasing the batch size.

**Review by yuzefovich — APPROVED** [review]
Very nice refactor! :lgtm:

23 minutes sounds reasonable to me, so I wouldn't worry about that.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47514#-:-M4yHfVVD167Qy3HYwIZ:b-uycdz4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpch_utils.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47514#-M4yA-7D6kmFBb68KOmv:-M4yA-7D6kmFBb68KOmw:b-viqu00) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f8f89e853dcb6ddbb9e1b6a8d13cbd202a2541/pkg/cmd/roachtest/tpch_utils.go#L50)):*
> ```Go
> 		// factor.
> 		expectedSupplierCardinality := 10000 * sf
> 		if supplierCardinality >= expectedSupplierCardinality {
> ```

~Do we want to be exact here (i.e. `==` instead of `>=`)? I'd expect this function to make sure that the "exact" dataset for the requested `sf` exists in the cluster. If you decide to keep this "compatible" behavior, I think it deserves more explicit call out in the comment to the function.~

Oh, just saw that this code already existed. Please expand the comment then.
___
*[pkg/cmd/roachtest/tpchvec.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47514#-M4yD6ZQEWbQhAToJzK-:-M4yD6ZQEWbQhAToJzK0:b-ufumy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f8f89e853dcb6ddbb9e1b6a8d13cbd202a2541/pkg/cmd/roachtest/tpchvec.go#L29)):*
> ```Go
> 
> const (
> 	nodeCount      = 3
> ```

nit: I'd rename the constants and variables that are specific to this test to include "tpchVec" into their names so that there would be no confusion inside `roachtest` package.
___
*[pkg/cmd/roachtest/tpchvec.go, line 569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47514#-M4yCocG0lw6zhqZRrOi:-M4yCocG0lw6zhqZRrOj:b-fkyal5) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f8f89e853dcb6ddbb9e1b6a8d13cbd202a2541/pkg/cmd/roachtest/tpchvec.go#L569)):*
> ```Go
> func (p *tpchVecPerfTest) postTestRunHook(t *test, version crdbVersion) {
> 	queriesToSkip := queriesToSkipByVersion[version]
> 	// We are only interested in comparison with 'perf' run option.
> ```

nit: this comment should be removed.
___
*[pkg/cmd/roachtest/tpchvec.go, line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47514#-M4yHnjhBGVBkXltxbGF:-M4yHnjhBGVBkXltxbGG:blqquur) ([raw file](https://github.com/cockroachdb/cockroach/blob/c45cbcc2da0cadb99d9767b636a083575520b653/pkg/cmd/roachtest/tpchvec.go#L643)):*
> ```Go
> func (b tpchVecSmallBatchSizeTest) preTestRunHook(t *test, conn *gosql.DB) {
> 	b.tpchVecTestCaseBase.preTestRunHook(t, conn)
> 	const batchSize = 1
> ```

I think it'd be beneficial to randomize it in small range (maybe `[1, 4)`).

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47514)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/tpch_utils.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47514#-M4yA-7D6kmFBb68KOmv:-M56Ky6s21EKuiI8fE8q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/75f8f89e853dcb6ddbb9e1b6a8d13cbd202a2541/pkg/cmd/roachtest/tpch_utils.go#L50)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

~Do we want to be exact here (i.e. `==` instead of `>=`)? I'd expect this function to make sure that the "exact" dataset for the requested `sf` exists in the cluster. If you decide to keep this "compatible" behavior, I think it deserves more explicit call out in the comment to the function.~

Oh, just saw that this code already existed. Please expand the comment then.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tpchvec.go, line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47514#-M4yHnjhBGVBkXltxbGF:-M56L-0O-ufNm9zWZctX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c45cbcc2da0cadb99d9767b636a083575520b653/pkg/cmd/roachtest/tpchvec.go#L643)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think it'd be beneficial to randomize it in small range (maybe `[1, 4)`).
</blockquote></details>

Done.

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Pull request merged**
