### PR TITLE
sql: add some logging for DistSQLReceiver transitions

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds some logging around the status changes of
DistSQLReceiver as well as reduces verbosity of the existing log
messages.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-:-MXhyLWA9Ifc7k6f51YR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 608 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-MXhxEyK2wlWSah-_9jT:-MXhxEyK2wlWSah-_9jU:bf42160) ([raw file](https://github.com/cockroachdb/cockroach/blob/45319d5a2b347c5b83b30896d61691773c5b8329/pkg/sql/distsql_running.go#L608)):*
> ```Go
> 	// canceled.
> 	if r.ctx.Err() != nil {
> 		log.VEventf(r.ctx, 1, "%v encountered, so transition to shutting down", r.ctx.Err())
> ```

[nit] This might be hard to read if the error is large or is on multiple lines (like an internal error). Maybe `encountered error (transitioning to shutting down): %v`
___
*[pkg/sql/distsql_running.go, line 722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-MXhxcPp0F7ulmqn_QYR:-MXhxcPp0F7ulmqn_QYS:b-pi8j6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/45319d5a2b347c5b83b30896d61691773c5b8329/pkg/sql/distsql_running.go#L722)):*
> ```Go
> 	}
> 
> 	// If no columns are needed by the output, the consumer is only looking for
> ```

[nyc] `noColsRequired` is a very poor name. You can have rows with no columns and still care about how many there are. Consider renaming, e.g. `existsMode`.
___
*[pkg/sql/distsql_running.go, line 727 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-MXhy7pHCyS6q1KqXdDF:-MXhy7pHCyS6q1KqXdDG:b-5owjaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/45319d5a2b347c5b83b30896d61691773c5b8329/pkg/sql/distsql_running.go#L727)):*
> ```Go
> 	if r.noColsRequired {
> 		r.row = []tree.Datum{}
> 		log.VEvent(r.ctx, 1, "a single row is pushed and no columns are needed, so transition to draining")
> ```

[nit] I'd say `a row is pushed in "exists" mode, so ..`
___
*[pkg/sql/distsql_running.go, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-MXhyF4w8Bk4CFGLswCH:-MXhyF4xE5_qF2YnG7GH:b-xvvh4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/45319d5a2b347c5b83b30896d61691773c5b8329/pkg/sql/distsql_running.go#L748)):*
> ```Go
> 			// errors, it is a signal to stop distsql and return success to the
> 			// client (that's why we don't set the error on the resultWriter).
> 			log.VEvent(r.ctx, 1, "either ErrLimitedResultClosed or errIEResultChannelClosed was encountered, so transition to draining")
> ```

You can split the `if` into two branches and be more specific in the error.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-:-MXibnOODjjJZy-7bksh:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/distsql_running.go, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-MXhyF4w8Bk4CFGLswCH:-MXib_Og9VLvjIJAPQY9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/45319d5a2b347c5b83b30896d61691773c5b8329/pkg/sql/distsql_running.go#L748)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

You can split the `if` into two branches and be more specific in the error.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
bors r-

Need to update a comment a bit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-:-MXj0pvfBoguFUNpQtms:b-x8r1xo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63249)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/distsql_running.go, line 726 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-MXj0wpoDvwZBla-Ww4E:-MXj0wpoDvwZBla-Ww4F:bisnwpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9559945ba62b6a331b18bea0a87eb0619eaee0ad/pkg/sql/distsql_running.go#L726)):*
> ```Go
> 		// row is pushed or not, so the contents do not matter.
> 		r.row = []tree.Datum{}
> 		log.VEvent(r.ctx, 1, `a row is pushed in "exists" mode, so transition to shutting down`)
> ```

Note to myself: this should be "transition to draining".

**Comment by yuzefovich** [comment]
@RaduBerinde I also adjusted the verbosity of the existing logging, please take a quick look.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-:-MYDPJKN5BHzQlSfvWhz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 1112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-MYDP4LS5vp8khaH709j:-MYDP4LS5vp8khaH709k:bql9i8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ae6200dec38d487094d8477d2b9410f4d8b25b3/pkg/sql/distsql_running.go#L1112)):*
> ```Go
> 
> 	for i := range plan.checkPlans {
> 		log.VEventf(ctx, 3, "executing check query %d out of %d", i+1, len(plan.checkPlans))
> ```

What's the reasoning for making this less visible? It's a pretty high level log.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-:-MYGOvLS3HIFa4yUcLw3:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/sql/distsql_running.go, line 1112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63249#-MYDP4LS5vp8khaH709j:-MYGO45zEEceQj_dyCdf:b4h8eyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ae6200dec38d487094d8477d2b9410f4d8b25b3/pkg/sql/distsql_running.go#L1112)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What's the reasoning for making this less visible? It's a pretty high level log.
</blockquote></details>

Bumped it back up to level 2. I think now the verbosity levels adhere to the following reasoning:
- level 1 is for erroneous cases when a flow is shutdown. IMO this is the most interesting part when debugging things.
- level 2 is for indication when the execution of a flow starts
- level 3 is for some additional logging.

**Pull request merged**
