### PR TITLE
roachpb: add StoreCapacity.LeaseCount

### PR DESCRIPTION
**Pull request by petermattis**
Add StoreCapacity.LeaseCount and populate this field before gossiping
the StoreDescriptor.

Remove the unused StoreList.{count,used} fields. Add
StoreList.candidateLeases.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10439)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: but this will conflict with #10404.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store.go, line 2172 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-KVfHAkamVPj1xAi7CaP:-KVfHAkbucGOw83BHjaf:b-igki8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d900ebd68d9e889d9c03bbac389400e43fb4624/pkg/storage/store.go#L2172)):*
> ```Go
> 	now := s.cfg.Clock.Now()
> 
> 	s.mu.Lock()
> ```

any reason not to use `storeReplicaVisitor` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-:-KVfHL8trldsEB-dWmC5:b-8fnv0u)*

**Comment by BramGruneir** [comment]
Do we keep any time series stats on lease counts?  Could we leverage those?  If not, perhaps we should add them.

---

Reviewed 1 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-:-KVfkwPOYr27KqDk-fXI:bktylsb)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439)*

**Comment by BramGruneir** [comment]
Reviewed 8 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439)*

**Comment by petermattis** [comment]
> Do we keep any time series stats on lease counts? 

Yes we do.

> Could we leverage those?

I don't think we should. Seems better to have an up to date count than to rely on the time series metrics which are computed periodically.

---

Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/store.go, line 2172 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-KVfHAkamVPj1xAi7CaP:-KVfm413XVXTNJORcPVW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d900ebd68d9e889d9c03bbac389400e43fb4624/pkg/storage/store.go#L2172)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> any reason not to use `storeReplicaVisitor` here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-:-KVfm57vDrOzkQZNUZH4:b-ozkgpi)*

**Comment by BramGruneir** [comment]
Might as well update the time series metrics with these freshly calculated values.

:lgtm: 

---

Reviewed 1 of 2 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-:-KVfndnL492iRyARFC1A:brcklg5)*

**Comment by BramGruneir** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store_pool.go, line 466 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-KVfoCdU0sMYaA44G3A0:-KVfoCdU0sMYaA44G3A1:bv04cu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34be88abd5deb9669c754adb79dae32fdc714fe/pkg/storage/store_pool.go#L466)):*
> ```Go
> 	sl := StoreList{stores: descriptors}
> 	for _, desc := range descriptors {
> 		sl.count.update(float64(desc.Capacity.RangeCount))
> ```

bad rebase?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439)*

**Comment by petermattis** [comment]
> Might as well update the time series metrics with these freshly calculated values.

In `Store.Descriptor()`. That seems odd. Or did you have something different in mind? 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store_pool.go, line 466 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-KVfoCdU0sMYaA44G3A0:-KVfoMavgchkwmQUNS79:b-275sle) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34be88abd5deb9669c754adb79dae32fdc714fe/pkg/storage/store_pool.go#L466)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> bad rebase?
</details>
No, these fields are gone. Or am I not seeing what you're seeing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-:-KVfoTaKCBe0XE0L_veh:b98tq3c)*

**Comment by petermattis** [comment]
That was supposed to be "In `StoreDescriptor()`?".

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-:-KVfplrZGl4eeZv6qdJ2:b6ww465)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store_pool.go, line 466 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-KVfoCdU0sMYaA44G3A0:-KVfptejTYBUfhYsSSr-:b8fnocz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34be88abd5deb9669c754adb79dae32fdc714fe/pkg/storage/store_pool.go#L466)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> No, these fields are gone. Or am I not seeing what you're seeing?
</details>
Oh, duh. carry on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439)*

**Comment by BramGruneir** [comment]
Ah, yeah, we need that to be super quick.  I think you're right.  Just leave it as is.

However, maybe locking twice in row in descriptor() isn't a great idea either.  Once for range count, and once for the list of ranges.  I think it's good for now, just something to think about.  I'd also like to limit the calls to engine.capacity() as well at some point.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-:-KVfpLAP-h3D5RhvAtFX:bhm85ao)*

**Comment by petermattis** [comment]
> However, maybe locking twice in row in descriptor() isn't a great idea either.  Once for range count, and once for the list of ranges.  I think it's good for now, just something to think about.  

I doubt that extra locking will be noticeable. 

> I'd also like to limit the calls to engine.capacity() as well at some point.

Only after that shows up in profiling please. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10439#-:-KVfqgO0ngPhvMCUCdY7:bk39x0c)*

**Pull request merged**
