### PR TITLE
sql: introduce a new predicate structure to replace usingPredicate

### LINKED ISSUE #10630: sql: introduce a new predicate structure to replace usingPredicate
There needs to be a new join predicate structure to replace usingPredicate that describes a join using an equality relation between columns on the left and right. The new predicate, let's call this the  `equalityPredicate` extends `usingPredicate` by allowing the *names* of the join columns on the left and right to differ.

Once this predicate exists, the following needs to happen:
1. the constructor for USING must be changed to use `equalityPredicate`
2. after #10618 is merged, the hash join must be used for `equalityPredicate` as well.

for the purpose of EXPLAIN we can then describe the equalityPredicate using the following syntax: `ON EQUALS(left columns..., right columns...)`

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #10630.
cc @knz.
I plumb `makeUsingPredicate` using `makeEqualityPredicate`.Please help me review if I have done it right.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10672)

### CODE REVIEW

**Comment by knz** [comment]
Thanks for your help! A few minor comments.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/table_join.go, line 253 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-KWXaZs8Oot_kSZdRLIF:-KWXaZs9W6qoXquFzFMb:b-36lo73) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8e97f402c19daa07c0c0c57666943ca7e8c89b/pkg/sql/table_join.go#L253)):*
> ```Go
> func (p *equalityPredicate) format(buf *bytes.Buffer) {
> 	buf.WriteString(" ON EQUALS(")
> 	p.leftColNames.Format(buf, parser.FmtSimple)
> ```

If you wish to keep this simple invocation of Format, then I would recommend the following output syntax:

ON EQUALS((a,b,c), (x, y, z))

---

*[pkg/sql/table_join.go, line 337 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-KWXb0l33spdWCtbDsxl:-KWXb0l4gKBfLSmXenMM:b6yxwnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8e97f402c19daa07c0c0c57666943ca7e8c89b/pkg/sql/table_join.go#L337)):*
> ```Go
> ) (joinPredicate, *dataSourceInfo, error) {
> 	if len(leftColNames) != len(rightColNames) {
> 		return nil, nil, fmt.Errorf("left columns' length %q doesn't match right columns' length %q in EqualityPredicate",
> ```

That's a panic not an error.

---

*[pkg/sql/table_join.go, line 441 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-KWXau_W1lIAqpmn2Nat:-KWXau_W1lIAqpmn2Nau:b245tow) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8e97f402c19daa07c0c0c57666943ca7e8c89b/pkg/sql/table_join.go#L441)):*
> ```Go
> }
> 
> // makeUsingyPredicate constructs a joinPredicate object for joins with
> ```

Typo in first word.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-:-KWXbEgjbVNU4Wl1YdPz:bt1xqro)*

**Comment by a6802739** [comment]
@knz, Thanks for your review.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/table_join.go, line 253 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-KWXaZs8Oot_kSZdRLIF:-KWXfNNqGxHWxhcHHi4e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8e97f402c19daa07c0c0c57666943ca7e8c89b/pkg/sql/table_join.go#L253)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> If you wish to keep this simple invocation of Format, then I would recommend the following output syntax:
> 
> ON EQUALS((a,b,c), (x, y, z))
</details>
Done.

---

*[pkg/sql/table_join.go, line 337 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-KWXb0l33spdWCtbDsxl:-KWXfg5-OrMmDZJb83a7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8e97f402c19daa07c0c0c57666943ca7e8c89b/pkg/sql/table_join.go#L337)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> That's a panic not an error.
</details>
Done.

---

*[pkg/sql/table_join.go, line 441 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-KWXau_W1lIAqpmn2Nat:-KWXfjE-wL3SozWMDUAi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8e97f402c19daa07c0c0c57666943ca7e8c89b/pkg/sql/table_join.go#L441)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Typo in first word.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-:-KWXfFN3TQSPpMKRkEUt:b-8v71mh)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/table_join.go, line 255 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-KWXjBxGpnHPCEpULEXR:-KWXjBxHRUGooc9MRi5c:bza8vtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a58b61e860c41b57efad294748b414c4f66664/pkg/sql/table_join.go#L255)):*
> ```Go
> 	p.leftColNames.Format(buf, parser.FmtSimple)
> 	p.rightColNames.Format(buf, parser.FmtSimple)
> 	buf.WriteString("),(")
> ```

No that's not correct.

Also please add an EXPLAIN test for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672)*

**Comment by a6802739** [comment]
@knz, yeah, I made a mistake there.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/table_join.go, line 255 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-KWXjBxGpnHPCEpULEXR:-KWXqJxEr3WU2fft4MzK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a58b61e860c41b57efad294748b414c4f66664/pkg/sql/table_join.go#L255)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> No that's not correct.
> 
> Also please add an EXPLAIN test for this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-:-KWXqCZowotb6ndaIFc-:bflcmq0)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10672#-:-KWXq_S09k-4FHpIVjIA:bnfp4nl)*

**Comment by a6802739** [comment]
@knz, when could I merge this PR?

**Comment by knz** [comment]
now

**Pull request merged**
