### PR TITLE
sql: add the `GENERATED ALWAYS` alias for computed columns

### LINKED ISSUE #42418: sql: support GENERATED ALWAYS AS syntax for computed columns
CockroachDB currently supports stored computed columns, as described here: https://www.cockroachlabs.com/docs/v19.2/computed-columns.html
```
CREATE TABLE users (
        first_name STRING,
        last_name STRING,
        full_name STRING AS (CONCAT(first_name, ' ', last_name)) STORED,
```

This differs from the Postgres syntax a bit, which requires a few more keywords: https://www.postgresql.org/docs/current/ddl-generated-columns.html
```
CREATE TABLE users (
        first_name STRING,
        last_name STRING,
        full_name STRING GENERATED ALWAYS AS (CONCAT(first_name, ' ', last_name)) STORED
```

We should also add support for using the Postgres syntax, and it should just be an alias for the existing behavior.

NB: Postgres just added this feature/syntax in v12 (released October 2019), which is why our original syntax does not already match Postgres.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #42418.

This PR adds an alias to create computed columns with the Postgres
syntax that uses `GENERATED ALWAYS`. Due an unfortunate ambiguity caused
by the `CREATE FAMILY` column qualifications, the parser cannot tell
with a single lookahead token what to do in the case of

```
CREATE TABLE t (x INT CREATE FAMILY GENERATED...)
```

Here, with only 1 token of lookahead, we don't know whether GENERATED is
that start of the generated computed clause, or the name of the family.
To rectify this, we use the same trick used in other cases, where the
lexer will generate a new `GENERATED_ALWAYS` token that allows us to get
past the ambiguity here.

Release note (sql change): Add the Postgres syntax `GENERATED ALWAYS`
alias for computed column construction.

### CODE REVIEW

**Comment by rohany** [comment]
Not sure what our feelings are on adding more cases to this extra lexer lookahead stuff.

**Review by knz — APPROVED** [review]
nice

**Comment by rohany** [comment]
bors r=knz

**Comment by rohany** [comment]
bors r=knz

**Comment by rafiss** [comment]
Are syntax additions like this eligible for backporting?

**Comment by knz** [comment]
They are eligible if we announced compatibility with some tools in v20.1 and they are blocked on this addition. Otherwise, not

**Comment by knz** [comment]
What we can do in 20.1 is add the parsing rule with an unimplemented error link that points to the issue (#42418)

**Comment by rafiss** [comment]
We claim support for SQLAlchemy, I believe: https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-sqlalchemy.html

SQLAlchemy [supports computed columns](https://docs.sqlalchemy.org/en/13/changelog/changelog_13.html#change-391a646c5fe982f3e30903cf6aae06b3). The current version of our SQLAlchemy dialect implements this by using the `GENERATED ALWAYS AS ... STORED` syntax. We could update the dialect so it doesn't create the `GENERATED ALWAYS AS` part of that expression, or we could backport, or both. I'm unsure how to make this decision.

**Comment by knz** [comment]
if we claim the support then that's the reason you need. But I'd defer to Jordan to arbitrate here.

**Pull request merged**
