### PR TITLE
storage: fix RaftTransport breaker

### PR DESCRIPTION
**Pull request by petermattis**
A closed breaker returns true from CircuitBreaker.Ready() once per
backoff period. We were doing the equivalent of two consecutive calls to
CircuitBreaker.Ready() and requiring both to return true, which is
clearly going to be problematic.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10642)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM, I guess. So the only thing the breaker is gating now is sending of snapshots?

**Comment by petermattis** [comment]
No, the breaker is still used for all Raft messages. Take a closer look at the code (not just the diff). We call `CircuitBreaker.Ready()` in `RaftTransport.SendAsync()`.

**Comment by tamird** [comment]
Ah, fooled by the lack of local variable named `breaker`. Objection withdrawn, though it would be good to have some kind of test here.

**Comment by petermattis** [comment]
Any ideas on how to test this? I'm going to merge for now.

**Comment by tamird** [comment]
Probably with a fairly narrow unit test; trip the breaker and then confirm that connectAndProcess still does its thing.

**Pull request merged**
