### PR TITLE
sql: add visibility column to virtual tables and SHOW output

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds a new column `visibility` to `crdb_internal.table_indexes`
and `information_schema.statistics`. It also adds a new column `visibility`
to the output of following SQL statements:

```
SHOW INDEX FROM (table_name)
SHOW INDEXES FROM (table_name)
SHOW KEYS FROM (table_name)
SHOW INDEX FROM DATABASE (database_name)
SHOW INDEXES FROM DATABASE (database_name)
SHOW KEYS FROM DATABASE (database_name)
```

To minimize changes to the existing functionality, the existing columns
"is_visible", "visible" remain there. They are only set to true if the index
is fully visible. Any index with visibility [0.0, 1.0) would be false.

Informs #82363

Release note (sql change): Added a new column `visibility` to
`crdb_internal.table_indexes` and `information_schema.statistics`. Also added
a new column `visibility` to the output of following SQL statements:

```
SHOW INDEX FROM (table_name)
SHOW INDEXES FROM (table_name)
SHOW KEYS FROM (table_name)
SHOW INDEX FROM DATABASE (database_name)
SHOW INDEXES FROM DATABASE (database_name)
SHOW KEYS FROM DATABASE (database_name)
```
This new column contains a floating point number specifying the level of
visibility of the index, from 0 (not visible) to 1 (fully visible). If
the value is between 0 and 1, the index will be visible to the corresponding
fraction of queries.

Co-authored-by: wenyihu3 <wenyi.hu@cockroachlabs.com>

### CODE REVIEW

**Comment by rytaft** [comment]
First commit is https://github.com/cockroachdb/cockroach/pull/87259

**Review by rytaft — COMMENTED** [review]
I've rebased off of master and it looks like all tests are passing now. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101334#-:-NSw1dh3E7GgI3TdjCRK:balv2hh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @mgartner, @rharding6373, and @srosenberg)

**Review by rharding6373 — CHANGES_REQUESTED** [review]
Looks great! My main question is how to use the fractional visibility feature.

> Reviewed 21 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101334#-:-NTF_EPa3dW_96FWx0V1:b5lk5uu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @mgartner, @rytaft, and @srosenberg)

___
*[`-- commits` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101334#-NTFVWhl1DjaS0ey5kd3):*
It doesn't look like there are test examples of fractional visibility. How do we create indexes with fractional visibility?
___
*[`pkg/util/log/eventpb/ddl_events.proto` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101334#-NTFVvNmCOuA-nIJl7lj:-NTFVvNmCOuA-nIJl7lk:bz3t8uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/767567947661267dbcd3f666d45d2a72210b9b44/pkg/util/log/eventpb/ddl_events.proto#L342)):*
> ```protobuf
>   bool not_visible = 5 [(gogoproto.jsontag) = ",omitempty", deprecated = true];
>   // The new invisibility of the affected index.
>   double invisibility = 6 [(gogoproto.jsontag) = ",omitempty"];
> ```

I'm a bit confused by the mix of `invisibility` and `visibility` in this PR. Could you elaborate on what the difference is and why we choose to use one name over another?

**Review by rharding6373 — APPROVED** [review]
Found the follow-up PR! Ignore my previous comment :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101334#-:-NTFb8Ui7Xe6XCdD4FxY:b-yqv4lw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @mgartner, @rytaft, and @srosenberg)

___
*[`-- commits` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101334#-NTFVWhl1DjaS0ey5kd3):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It doesn't look like there are test examples of fractional visibility. How do we create indexes with fractional visibility?
</blockquote></details>

Whoops, didn't realize the PR order was switched and the other PR wasn't merged yet and addresses this. I'll review that now.

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101334#-:-NTG5zCv7xNdSnyCN3Kc:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @mgartner, @rharding6373, and @srosenberg)

___
*[`pkg/util/log/eventpb/ddl_events.proto` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101334#-NTFVvNmCOuA-nIJl7lj:-NTG5KkB3_7Qf7i45uhd:b-yzpk03) ([raw file](https://github.com/cockroachdb/cockroach/blob/767567947661267dbcd3f666d45d2a72210b9b44/pkg/util/log/eventpb/ddl_events.proto#L342)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I'm a bit confused by the mix of `invisibility` and `visibility` in this PR. Could you elaborate on what the difference is and why we choose to use one name over another?
</blockquote></details>

The user-facing feature is described as "visibility" (since that's more intuitive), but in the codebase we use "invisibility" for the most part since we want the default to be that all indexes are visible, and therefore have invisibility=0.

**Pull request merged**
