### PR TITLE
kvserver/rangefeed: introduce StreamManager 

### PR DESCRIPTION
**Pull request by wenyihu6**
This patch introduces StreamManager, which should be created and persisted for
the lifetime of each node.MuxRangefeed call. It will handle starting and
stopping the underlying wrapped sender, as well as managing individual
streams/rangefeeds. While currently unused, future commits will refactor 
the unbuffered sender to use it.

Part of: https://github.com/cockroachdb/cockroach/issues/110432
Release note: none

Co-authored-by: Steven Danna danna@cockroachlabs.com

### CODE REVIEW

**Comment by wenyihu6** [comment]
I added more tests for StreamManager in https://github.com/cockroachdb/cockroach/pull/135075. I found it a bit challenging to test StreamManager without a real UnbufferedSender implementation. Creating a mock sender started to feel like reinventing the wheel of an UnbufferedSender. That said, we can add more simple tests for StreamManager without relying on actual senders. Wdyt?

**Review by tbg — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjwKmwA5hrYm8gZtJQ:-OBjwKmwA5hrYm8gZtJR:b-ixe7bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L76)):*
> ```Go
> 	// run is the main loop for the sender. It is expected to run in the
> 	// background until a node level error is encountered which would shut down
> 	// all streams in StreamManager.
> ```

speaking from the point of view of this being an interface, is `run()` supposed to launch a goroutine and then return? And should the lifetime of that goroutine be governed by the lifetime of `ctx`? Or is it supposed to die with `cleanup`?

Does `run` even need to be in the interface? IMO it's a bit of an oddity to have a "launcher" method. Could whatever gives us the sender (`NewUnbufferedSender()` or whatever) kick it off instead?

A similar comment could be made for `cleanup`. Can the sender clean itself up when it is tearing down its `run`? In other words, can we start and stop the sender before making the surrounding StreamManager?


Btw I'm happy for all of this to be revisited down the road. These are not blocking comments.
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjyoaj8_KVV3gn5yXC:-OBjyoaj8_KVV3gn5yXD:b9gwatn) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L83)):*
> ```Go
> 	// sendIsThreadSafe is a no-op declaration method. It is a contract that
> 	// sendUnbuffered and sendBuffered should be thread-safe.
> 	sendIsThreadSafe()
> ```

I've never seen a marker method like this before. Does this add anything over adding comments to `send{UnB,unb}uffered`?
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjzUV79uGJ-rdkgJkP:-OBjzUV86oj7T2Rs71Rw:bd983i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L113)):*
> ```Go
> }
> 
> // DisconnectStream disconnects the stream with the given streamID.
> ```

Can you add some words here that explain who calls this (the mux, right?) and why? And why we are leaving the stream in the map. Is the idea that when we call `Disconnect` the registration will bubble up an error and we get a subsequent call to `OnError` which then will remove the stream?
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjyzbpDpiG5PEcon7E:-OBjyzbpDpiG5PEcon7F:b-qnj8mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L193)):*
> ```Go
> 		sm.metrics.UpdateMetricsOnRangefeedDisconnect()
> 	}
> 	sm.streams.m = make(map[int64]Disconnector)
> ```

I assume you're worried about someone calling `AddStream` after `Stop`? Can we make it a part of the contract that this does not happen? 
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjzzGfCvTUjdQQbKKE:-OBjzzGfCvTUjdQQbKKF:b-wduvm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L198)):*
> ```Go
> // Error returns a channel that can be used to receive errors from sender.run.
> // Only non-nil errors are sent on this channel.
> func (sm *StreamManager) Error() chan error {
> ```

I think you want to return `<-chan error` (caller can't write to it).
Also, I think only one error is ever received, and only on true error (nothing may ever be sent on this channel). It helps to be specific about the semantics.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @tbg and @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjwKmwA5hrYm8gZtJQ:-OBkjg4vCllrFvmpA9aB:bv6ojrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L76)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

speaking from the point of view of this being an interface, is `run()` supposed to launch a goroutine and then return? And should the lifetime of that goroutine be governed by the lifetime of `ctx`? Or is it supposed to die with `cleanup`?

Does `run` even need to be in the interface? IMO it's a bit of an oddity to have a "launcher" method. Could whatever gives us the sender (`NewUnbufferedSender()` or whatever) kick it off instead?

A similar comment could be made for `cleanup`. Can the sender clean itself up when it is tearing down its `run`? In other words, can we start and stop the sender before making the surrounding StreamManager?


Btw I'm happy for all of this to be revisited down the road. These are not blocking comments.
</blockquote></details>

:+1: Let's definitely follow up here.  
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjyoaj8_KVV3gn5yXC:-OBklHy22KPv2NqBwC6E:bryt5l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L83)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I've never seen a marker method like this before. Does this add anything over adding comments to `send{UnB,unb}uffered`?
</blockquote></details>

I think this has gotten copy/pasta'd around between a few implementations. I suppose one benefit is that when making a new implementation, you have to type out this method name and perhaps then you think about whether your Send method is in fact thread safe.
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjzUV79uGJ-rdkgJkP:-OBklzdf21w8V3E_v2oD:b-4fr4az) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L113)):*
> And why we are leaving the stream in the map. Is the idea that when we call `Disconnect` the registration will bubble up an error and we get a subsequent call to `OnError` which then will remove the stream?

Yes. We could remove it here as well without much harm if we wanted some defense in depth against the registration somehow never sending us the event. 
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBknqwu0NE2OdclK4xx:-OBknqwu0NE2OdclK4xy:b-5n6xyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L143)):*
> ```Go
> 	}
> 	if _, ok := sm.streams.m[streamID]; ok {
> 		log.Fatalf(context.Background(), "stream %d already exists", streamID)
> ```

I kinda wonder if some of these are really halt-the-process level bugs vs having this return an error and changing this to an AssertionFailedf.
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBknTZI4gmISab_3GHW:-OBknTZI4gmISab_3GHX:bfjnjz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L163)):*
> ```Go
> 	sm.wg.Add(1)
> 	ctx, sm.taskCancel = context.WithCancel(ctx)
> 	if err := stopper.RunAsyncTask(ctx, "buffered stream output", func(ctx context.Context) {
> ```

s/buffered stream out/stream manager SOMETHING/

But, this goes to Tobi's point that perhaps the sender should be responsible for the actual launching of this task.
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBkn5_OCa2ePL8SwSt0:-OBkn5_OCa2ePL8SwSt1:b9fevwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L190)):*
> ```Go
> 		// terminate.
> 		disconnector.Disconnect(
> 			kvpb.NewError(kvpb.NewRangeFeedRetryError(kvpb.RangeFeedRetryError_REASON_RANGEFEED_CLOSED)))
> ```

One would hope the compiler would do this for you, but we could move this error construction out of the loop.
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBknLAz-aqq9SnOvL4M:-OBknLAz-aqq9SnOvL4N:b-7nqpqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L191)):*
> ```Go
> 		disconnector.Disconnect(
> 			kvpb.NewError(kvpb.NewRangeFeedRetryError(kvpb.RangeFeedRetryError_REASON_RANGEFEED_CLOSED)))
> 		sm.metrics.UpdateMetricsOnRangefeedDisconnect()
> ```

If we gave this an argument, we could call it once with len(sm.streams.m)

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @tbg)

___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjwKmwA5hrYm8gZtJQ:-OBlimDb5REO1Mk81SPI:b-eoo9gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L76)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

:+1: Let's definitely follow up here.
</blockquote></details>

Agreed, I recall Steven has mentioned something similar before. Definitely looks like something we should revisit - filed an issue to track these targeted follow ups https://github.com/cockroachdb/cockroach/issues/135332.
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjyoaj8_KVV3gn5yXC:-OBliw_rBZCqu3ba170e:b-dqzkn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L83)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I think this has gotten copy/pasta'd around between a few implementations. I suppose one benefit is that when making a new implementation, you have to type out this method name and perhaps then you think about whether your Send method is in fact thread safe.
</blockquote></details>

I added them when I was reading this review https://reviewable.io/reviews/cockroachdb/cockroach/125872#-OBPgnLn2srEopeTC53V and thought this method would give us a nice comment/place to discuss thread-safety for the implementations. I've removed this from the interface and added two comments for the send{UnB,B} instead. 
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjzUV79uGJ-rdkgJkP:-OBlm0Ea6LCtwuv5Ws0w:bft5j2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L113)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

> And why we are leaving the stream in the map. Is the idea that when we call `Disconnect` the registration will bubble up an error and we get a subsequent call to `OnError` which then will remove the stream?

Yes. We could remove it here as well without much harm if we wanted some defense in depth against the registration somehow never sending us the event.
</blockquote></details>

+1, we're relying on the `r.Disconnect` method to handle de-dup and ensure this is idempotent. It checks whether r.mu.disconnected is set. 
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBknqwu0NE2OdclK4xx:-OBlmM0z8ktPXEMXAHiv:buxoomt) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L143)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I kinda wonder if some of these are really halt-the-process level bugs vs having this return an error and changing this to an AssertionFailedf.
</blockquote></details>

Agreed, we have a few log.Fatal here which may worth a second though - tracked here https://github.com/cockroachdb/cockroach/issues/135332 as well. 
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBknTZI4gmISab_3GHW:-OBlmVdrAhD6XGMCXXrG:bm1hbui) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L163)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

s/buffered stream out/stream manager SOMETHING/

But, this goes to Tobi's point that perhaps the sender should be responsible for the actual launching of this task.
</blockquote></details>

Renamed to `stream-manager-sender`. I will address the second part of the comment here https://github.com/cockroachdb/cockroach/issues/135332.
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBkn5_OCa2ePL8SwSt0:-OBln9Is2BpBPV9IT8Y3:b-m46eme) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L190)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

One would hope the compiler would do this for you, but we could move this error construction out of the loop.
</blockquote></details>

Good point, done. 
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 191 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBknLAz-aqq9SnOvL4M:-OBloT1-1FNGzx_gWT2A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L191)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

If we gave this an argument, we could call it once with len(sm.streams.m)
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjyzbpDpiG5PEcon7E:-OBloXwJ3fS6NfiZcAIH:b-op3mgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L193)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I assume you're worried about someone calling `AddStream` after `Stop`? Can we make it a part of the contract that this does not happen?
</blockquote></details>

It should be impossible to call `AddStream` or `DisconnectStream` after `Stop`, as this could lead to incomplete cleanup of metrics and rangefeeds. `Stop` is only called during the defer of `node.MuxRangefeed`. Once `Stop` is called, no additional calls to `AddStream` or `DisconnectStream` should occur. https://github.com/wenyihu6/cockroach/blob/6db61edc4668f63a396ff1e9e7cd001e20b13c28/pkg/server/node.go#L2164 I only cleaned up the map because it seemed like the right thing to do, ensuring the map is cleaned up after the rangefeeds have been disconnected.
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjzzGfCvTUjdQQbKKE:-OBlq6l84BbwQfBaCxjm:b-xr5081) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L198)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think you want to return `<-chan error` (caller can't write to it).
Also, I think only one error is ever received, and only on true error (nothing may ever be sent on this channel). It helps to be specific about the semantics.
</blockquote></details>

Clarified the semantics. How does the comment look now?

**Review by tbg — APPROVED** [review]
> Reviewed 7 of 7 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjyzbpDpiG5PEcon7E:-OBz54XJ2FSHXNXzYZ8X:b-8cjt54) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L193)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

It should be impossible to call `AddStream` or `DisconnectStream` after `Stop`, as this could lead to incomplete cleanup of metrics and rangefeeds. `Stop` is only called during the defer of `node.MuxRangefeed`. Once `Stop` is called, no additional calls to `AddStream` or `DisconnectStream` should occur. https://github.com/wenyihu6/cockroach/blob/6db61edc4668f63a396ff1e9e7cd001e20b13c28/pkg/server/node.go#L2164 I only cleaned up the map because it seemed like the right thing to do, ensuring the map is cleaned up after the rangefeeds have been disconnected.
</blockquote></details>

But it's also making a new map which seems odd. Then set the map to nil and we'll see a crash if there is in fact a stray call to AddStream or Disconnect Stream? 
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjzzGfCvTUjdQQbKKE:-OBz5ETm-SS2avhF25LE:b-w11lrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L198)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Clarified the semantics. How does the comment look now?
</blockquote></details>

The comment looks good, but still needs `<-chan error`.

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @tbg)

___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjyzbpDpiG5PEcon7E:-OBzc_Wi6liVtZcsBpSQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L193)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

But it's also making a new map which seems odd. Then set the map to nil and we'll see a crash if there is in fact a stray call to AddStream or Disconnect Stream?
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/rangefeed/stream_manager.go` line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134958#-OBjzzGfCvTUjdQQbKKE:-OBzca6R5SyhH0FjZp3J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39afe4eeae0ef4161930d6525fec42b18f85ba56/pkg/kv/kvserver/rangefeed/stream_manager.go#L198)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The comment looks good, but still needs `<-chan error`.
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by wenyihu6** [comment]
TFTR! @stevendanna lmk if you have any further comments, and I will address in future patches. 

bors r=tbg

**Pull request merged**
