### PR TITLE
geo: add unimplemented messaging for XYZ/XYM/XYZM types

### PR DESCRIPTION
**Pull request by otan**
Release justification: low risk updates to new functionality

Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53748#-:-MG9JFFg0U4fL9L5QVky:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
