### PR TITLE
*: s/rng/rep/ for vars of type Replica

### PR DESCRIPTION
**Pull request by jordanlewis**
It's confusing to have variables named `rng` when their type is `Replica` and not `Range` or similar. This is a large cosmetic change that fixes a lot of those occurrences.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10421)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM without reviewing

**Comment by RaduBerinde** [comment]
LGTM

Nit: I've usually seen `repl` for Replica vars.. But feel free to ignore, unless you want to try to do it automatically (e.g generate a diff, `s/\<rep\>/repl/g` in the patch, then reapply).

**Comment by jordanlewis** [comment]
There unfortunately seems to be a mix of both, but `repl` wins out by a bit so I've gone ahead and taken your suggestion.
```
[21:29]% ag " repl[ \.]" | wc -l
84
[21:30]% ag " rep[ \.]" | wc -l
69
```

**Comment by petermattis** [comment]
We also use `r` for `*Replica` vars. And that is the receiver name for all of the methods on `*Replica`. I personally prefer `rep` for such vars, but that preference is not strong.

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10421#-:-KVimGrHs-POWMujaQCs:bnfp4nl)*

**Comment by tschottdorf** [comment]
LGTM but please don't merge before #10327.

**Comment by jordanlewis** [comment]
@petermattis `r` seems a bit terse outside of the method receiver context. I hear your preference for `rep` but it does seem like there are already more instances of `repl` - considering the inconsistency here I'm just going to go ahead and merge this, since either one is strictly better than the incorrect `rng` naming.

**Pull request merged**
