### PR TITLE
Improve error checking and validations in logic test parser

### PR DESCRIPTION
**Pull request by nvb**
See #3139 and #2867

Changes to note:
- commands are now verified
- type-string characters are now verified
- sort-mode is now verified
- type-string column count is now verified with query result column count
- _hash-threshold_ added as a valid command to avoid breaking sqllogictest bigtest
- all sql/testdata sqllogictest files fixed to pass new requirements

Questions:
- I have added **_B**_ as a valid type-string type for booleans because we were using this throughout our tests, even though it is not standard sqllogictest syntax. I wanted to double check that this is ok.
- I added some verification for type-string column count, but would we ever want to do full type checking on the returned columns based on this type-string?

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3204)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM.

> I have added B as a valid type-string type for booleans because we were using this throughout our tests, even though it is not standard sqllogictest syntax. I wanted to double check that this is ok.

I think this is fine.

> I added some verification for type-string column count, but would we ever want to do full type checking on the returned columns based on this type-string?

Yes, we do.

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3204#-:-K3pcxhWDBmq77THyWlj:676834233)_

**Comment by nvanbenschoten** [comment]
Just added type-string based type checking for query results in Sqllogictests. The change pointed out a bunch of issues in our current testdata, which I went back and fixed. PTAL

**Comment by tamird** [comment]
LGTM

**Pull request merged**
