### PR TITLE
ui: add table index details page

### LINKED ISSUE #67647: Surface index usage statistics in the CC/DB console: Table overview
We are capturing index usage statistics: https://github.com/cockroachdb/cockroach/issues/64740. This issue tracks building an experience around this view on the table overview page. 

Figma mockups: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=3498%3A33376

CC @Annebirzin 

Epic: CRDB-9075

### LINKED ISSUE #72133: Surface index usage statistics in the CC/DB console: Table index details
We are capturing index usage statistics: #64740. This issue tracks building an experience around this view for an index details page.

Figma mockups: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=3498%3A33376

Epic: CRDB-9075

### PR DESCRIPTION
**Pull request by lindseyjin**
Resolves #72133

Previously, there was no Index Details page on the db console frontend.
This commit adds in an Index Details page which surfaces detailed
information for each table's indexes. This new page can be found by
clicking an index on the Index Stats table on the Table Overview page.

To show the CREATE INDEX statement, this commit also modifies the
TableIndexStats API endpoint to return a create statement as well. We
currently read this statement directly from the pg_indexes table,
although a future PR will add a SHOW CREATE INDEX statement to allow
this information to be surfaced in the SQL shell as well.

Release note (ui change): Add new Index Details page, which exists for
each index on a table.

### CODE REVIEW

**Review by lindseyjin — COMMENTED** [review]
Screen recording:

https://www.loom.com/share/3a11179875be4b7a8ebf23c67db85c38

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-:-MpsX3MM8k-IvFVROBGD:bnatmj8)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73178)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/index_usage_stats.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MpsXgSkE2g8BQTKCfJ5:-MpsXeQ9EdFgSpM12t_m:boxwnlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/462d4768251715bbb8f6a99661de18e55377cada/pkg/server/index_usage_stats.go#L373)):*
> ```Go
> 	fqtName string,
> ) (string, error) {
> 	// TODO(#73361): Add SHOW CREATE statement for indexes and refactor to use that instead.
> ```

Created an issue https://github.com/cockroachdb/cockroach/issues/73361 to implement a SHOW CREATE statement for indexes, and refactor this code to use that instead.

**Review by matthewtodd — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-:-MpvlynIDUI8j0L-jUhL:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lindseyjin and @rafiss)

___
*[pkg/server/index_usage_stats.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-Mpw1KYL2rKYdQaxk1cq:-Mpw1KYL2rKYdQaxk1cr:b-fc57gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/35fefd03909ea05d297e10be930914c2db215108/pkg/server/index_usage_stats.go#L224)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 	// Fully qualified table name is either database.table or database.schema.table
> 	fqtName, err := getFullyQualifiedTableName(req.Database, req.Table)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	tableID, err := getTableIDFromDatabaseAndTableName(ctx, req.Database, ie, userName, fqtName)
> 
> ```
</details>


It'd be really good to test this against various forms of user-defined schemas. I don't see any testing of these endpoints and that worries me. 
___
*[pkg/server/index_usage_stats.go, line 242 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-Mpw0yagB0NeoVki8fZ4:-Mpw0yagB0NeoVki8fZ5:b-wj3ht7) ([raw file](https://github.com/cockroachdb/cockroach/blob/35fefd03909ea05d297e10be930914c2db215108/pkg/server/index_usage_stats.go#L242)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> 
> 			ti.index_id,
> 			ti.index_name,
> 			ti.index_type,
> 			total_reads,
> 			last_read
> 		FROM crdb_internal.index_usage_statistics AS us
> 		JOIN crdb_internal.table_indexes ti
> 		ON us.index_id = ti.index_id
> 		AND us.table_id = ti.descriptor_id
> 		WHERE ti.descriptor_id = $`,
> ```
</details>

The suggestion made by @rafiss is to change this query to:

```sql
SELECT ti.index_id,
       ti.index_name,
       ti.index_type,
       total_reads,
       last_read,
       indexdef
  FROM crdb_internal.index_usage_statistics AS us
  JOIN crdb_internal.table_indexes AS ti ON us.index_id = ti.index_id
                                        AND us.table_id = ti.descriptor_id
  JOIN pg_catalog.pg_index AS pgidx ON indrelid = us.table_id
  JOIN pg_catalog.pg_indexes AS pgidxs ON pgidxs.crdb_oid = indexrelid
                                      AND indexname = ti.index_name
 WHERE ti.descriptor_id = '$1'::REGCLASS;
```

Where I _think_ you can just pass `req.Table` as the first arg here without the need for the above shenanigans.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lindseyjin, and @rafiss)

___
*[pkg/server/index_usage_stats.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-Mpw1KYL2rKYdQaxk1cq:-MpwPuLo7UzVl5B5kbTY:b-xw6sob) ([raw file](https://github.com/cockroachdb/cockroach/blob/35fefd03909ea05d297e10be930914c2db215108/pkg/server/index_usage_stats.go#L224)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// Fully qualified table name is either database.table or database.schema.table
> 	fqtName, err := getFullyQualifiedTableName(req.Database, req.Table)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	tableID, err := getTableIDFromDatabaseAndTableName(ctx, req.Database, ie, userName, fqtName)
> 
> ```

It'd be really good to test this against various forms of user-defined schemas. I don't see any testing of these endpoints and that worries me. 
</blockquote></details>

+1 on adding tests for user-defined schemas. Just an FYI that make sure to rebase off #73363 since that PR has made some big changes to the test framework. 
___
*[pkg/ui/workspaces/db-console/src/views/databases/utils.ts, line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MpwPBrC1BXSzpjZWF6Q:-MpwPBrC1BXSzpjZWF6R:b-k8c8rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/35fefd03909ea05d297e10be930914c2db215108/pkg/ui/workspaces/db-console/src/views/databases/utils.ts#L14)):*
> ```XML
> // based on the nodes list provided and nodeRegions, which is a full
> // list of node id to the region it resides.
> import * as protos from "oss/src/js";
> ```

nit: possbily remove the `oss` reference in the import path?

**Review by lindseyjin — COMMENTED** [review]
Updated screen recording:

https://www.loom.com/share/1c3853a28f83430ca5d25cca6c3b3dd2

@annebirzin I've replaced all instances of "clear" with "reset", as discussed on Figma. Lmk if that looks good to you, or if there's anything else you'd like me to change!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-:-Mq1AZEB15i5drKc1ydd:be3hpny)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, and @rafiss)

___
*[pkg/server/index_usage_stats.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-Mpw1KYL2rKYdQaxk1cq:-Mq1AizOAmlQe5zcWhXF:b-ldv1oe) ([raw file](https://github.com/cockroachdb/cockroach/blob/35fefd03909ea05d297e10be930914c2db215108/pkg/server/index_usage_stats.go#L224)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

+1 on adding tests for user-defined schemas. Just an FYI that make sure to rebase off #73363 since that PR has made some big changes to the test framework. 
</blockquote></details>

Updated my test in `tenant_status_test.go` to test create statement as well, and I've also added a test in `index_usage_stats_test.go` to test the `getTableIDFromDatabaseAndTableName()` helper function
___
*[pkg/server/index_usage_stats.go, line 242 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-Mpw0yagB0NeoVki8fZ4:-MpxFAAcBiS3duUn9NxR:b-7ebmsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/35fefd03909ea05d297e10be930914c2db215108/pkg/server/index_usage_stats.go#L242)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 			ti.index_id,
> 			ti.index_name,
> 			ti.index_type,
> 			total_reads,
> 			last_read
> 		FROM crdb_internal.index_usage_statistics AS us
> 		JOIN crdb_internal.table_indexes ti
> 		ON us.index_id = ti.index_id
> 		AND us.table_id = ti.descriptor_id
> 		WHERE ti.descriptor_id = $`,
> ```
The suggestion made by @rafiss is to change this query to:

```sql
SELECT ti.index_id,
       ti.index_name,
       ti.index_type,
       total_reads,
       last_read,
       indexdef
  FROM crdb_internal.index_usage_statistics AS us
  JOIN crdb_internal.table_indexes AS ti ON us.index_id = ti.index_id
                                        AND us.table_id = ti.descriptor_id
  JOIN pg_catalog.pg_index AS pgidx ON indrelid = us.table_id
  JOIN pg_catalog.pg_indexes AS pgidxs ON pgidxs.crdb_oid = indexrelid
                                      AND indexname = ti.index_name
 WHERE ti.descriptor_id = '$1'::REGCLASS;
```

Where I _think_ you can just pass `req.Table` as the first arg here without the need for the above shenanigans. 
</blockquote></details>

Done, thanks for the query!
___
*[pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.spec.ts, line 92 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-Mq1BPn82YZqhr6aAEDq:-Mq1BPn82YZqhr6aAEDr:b-132chg) ([raw file](https://github.com/cockroachdb/cockroach/blob/958adb0a7a19cde2881dc30b4cb6d7118f06b761/pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.spec.ts#L92)):*
> ```XML
>   assertProperties(
>     expected: IndexDetailsPageData,
>     compareTimestamps: boolean = true,
> ```

I realized that the timestamp comparison tests are sometimes flaky, since the timestamp is equal to the current time by default while the page is loading, but sometimes those end up slightly off for expected and actual values. Adding in this check to skip timestamp comparison while the page is loading.

**Review by maryliag — COMMENTED** [review]
> Reviewed 9 of 19 files at r5, 5 of 10 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, @lindseyjin, and @rafiss)

___
*[pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.module.scss, line 77 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFKx7pE-lwJ622r6PO:-MqFKx7pE-lwJ622r6PP:bc8sie8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.module.scss#L77)):*
> ```SCSS
>     font-size: 14px;
>     font-weight: $font-weight--bold;
>     line-height: 1.57;
> ```

nit: we also have parameter for line-height, you can use those here (same thing for font-size just above)
___
*[pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.module.scss, line 88 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFL9RB4h3SX7Lqgyn0:-MqFL9RB4h3SX7Lqgyn1:b51l13j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.module.scss#L88)):*
> ```SCSS
>   &--value {
>     font-family: $font-family--base;
>     font-size: 14px;
> ```

nit: same as above
___
*[pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.stories.tsx, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFLHHgEfCOsVDGt7qV:-MqFLHHgEfCOsVDGt7qW:b-dnb6kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.stories.tsx#L1)):*
> ```XML
> // Copyright 2021 The Cockroach Authors.
> ```

add actual stories to this file or remove the file, since it's not doing anything
___
*[pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.spec.ts, line 87 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFMOi8D-uDcyD-oBU3:-MqFMOi8D-uDcyD-oBU4:b-3zpajq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.spec.ts#L87)):*
> ```XML
>     compareTimestamps: boolean = true,
>   ) {
>     // Assert moments are equal if not pre-loading state.
> ```

nit: if not *in* pre-loading state.
___
*[pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.spec.ts, line 110 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFMUji2EoLzEK3xH1V:-MqFMUji2EoLzEK3xH1W:b-3zpajq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.spec.ts#L110)):*
> ```XML
>     compareTimestamps: boolean = true,
>   ) {
>     // Assert moments are equal if not pre-loading state.
> ```

nit: if not *in* pre-loading state.
___
*[pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.ts, line 66 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFN-Ce18A7Z0FkIvJb:-MqFN-Ce18A7Z0FkIvJc:b3dc7jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.ts#L66)):*
> ```XML
>     return refreshIndexStats(new TableIndexStatsRequest({ database, table }));
>   },
> ```

nit: remove empty line
___
*[pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.ts, line 68 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFN0tx3TFve416nIDC:-MqFN0tx3TFve416nIDD:b3dc7jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.ts#L68)):*
> ```XML
> 
>   resetIndexUsageStats: resetIndexUsageStatsAction,
> ```

nit: remove empty line
___
*[pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.spec.ts, line 94 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFNB0P1hnDuUUQ41i5:-MqFNB0P1hnDuUUQ41i6:b8iokeo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.spec.ts#L94)):*
> ```XML
>     compareTimestamps: boolean = true,
>   ) {
>     // Assert moments are equal if not pre-loading state.
> ```

nit: if for *in* pre-loading state.

**Review by Annebirzin — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-:-MqFkCGk-d9ZmTwM5mNQ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, @lindseyjin, and @rafiss)

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @Azhng, @maryliag, and @rafiss)

___
*[pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.module.scss, line 77 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFKx7pE-lwJ622r6PO:-MqFqoucA9lWQqRILWr-:bt2vr0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.module.scss#L77)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: we also have parameter for line-height, you can use those here (same thing for font-size just above)
</blockquote></details>

Fixed!
___
*[pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.stories.tsx, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFLHHgEfCOsVDGt7qV:-MqFqrS48AsZ8w_3B0Zr:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.stories.tsx#L1)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

add actual stories to this file or remove the file, since it's not doing anything
</blockquote></details>

Done!
___
*[pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.ts, line 66 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-MqFN-Ce18A7Z0FkIvJb:-MqFr8hd1cCW8XD5VdUF:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/3db75b8040659ec82f5eac961f60c3664d4b98e3/pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.ts#L66)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: remove empty line
</blockquote></details>

Done!

**Review by maryliag — APPROVED** [review]
great job! :lgtm: 

> Reviewed 3 of 3 files at r8, 3 of 3 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73178#-:-MqPcxBG5FuILn3EmDl5:bkn1jlc)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @Azhng, @maryliag, and @rafiss)

**Pull request merged**
