### PR TITLE
roachtest/cdc: minor refactor

### PR DESCRIPTION
**Pull request by andreimatei**
Trying to untangle a cluster from a test.

Release note: None

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
:LGTM: but it'd be lovely if the commit message was more specific about the motivations for this

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31139#-:-LOTRPDwDoTZw20ZvZll:bazhihe)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by andreimatei — COMMENTED** [review]
The motivation is that I'm trying to get rid of `c.t` - it should have never existed.
But also this patch is good at face value too. For the most part, calls to `t.Fatal` should be kept at high levels unless ergonomics really really mandate otherwise (e.g. with go's `testing.T` you can't even call Fatal() on another goroutine). And if a call to `Fatal` is to be delegated, at the very least it should be delegated to a `t` that's plumbed explicitly and not one that's randomly captured in some struct.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31139#-:-LOTacu81s07ivmvoPi6:b-ogsh3m)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31139#-:-LOTdIcPC16XiFR1PuLb:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by danhhz** [comment]
Not to put too fine a point on it, but that info is exactly what I was asking to be in the commit message (not a comment on the PR).

**Pull request merged**
