### PR TITLE
kvserver: read lease under mutex when switching lease type

### LINKED ISSUE #123998: roachtest: lease-preferences/manual-violating-transfer failed
roachtest.lease-preferences/manual-violating-transfer [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15224239?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15224239?buildTab=artifacts#/lease-preferences/manual-violating-transfer) on master @ [4c2e7761acd050aaee565443932b6b0eca55620b](https://github.com/cockroachdb/cockroach/commits/4c2e7761acd050aaee565443932b6b0eca55620b):

```
(test_runner.go:1237).runTest: test timed out (30m0s)
test artifacts and logs in: /artifacts/lease-preferences/manual-violating-transfer/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-15224239/lease-preferences-manual-violating-transfer/1715509077751/1715511026681)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*lease-preferences/manual-violating-transfer.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38653

### PR DESCRIPTION
**Pull request by kvoli**
A race could occur when a replica queue and post lease application both attempted to switch the lease type. This race would cause the queue to not process the replica because the lease type had already changed. As a result, lease preference violations might not have been quickly resolved by the lease queue.

Read the lease under the same mutex used for requesting the lease, when possibly switching the lease type.

Resolves: #123998
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
This passes 10/10 tests for `lease-preferences/manual-violating-transfer`. Previously, it would fail 1/3 of the time.

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124223#-:-Ny15QNBE_0E2fvCY8v-:b-uwkowd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124223#-Ny15_QZCnYHJBvvPVhz:-Ny15_QZCnYHJBvvPVi-:b-h6yjzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d08fe81c90bb73831f7827051eafe5d8dda6a6ce/pkg/kv/kvserver/replica_range_lease.go#L1621)):*
> ```Go
> 		defer r.mu.Unlock()
> 
> 		st := r.leaseStatusAtRLocked(ctx, r.store.Clock().NowAsClockTimestamp())
> ```

We should pull the `r.store.Clock().NowAsClockTimestamp()` outside of the replica mutex.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124223#-Ny15eEo-Re9cap_5cUb:-Ny15eEo-Re9cap_5cUc:beypsuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d08fe81c90bb73831f7827051eafe5d8dda6a6ce/pkg/kv/kvserver/replica_range_lease.go#L1627)):*
> ```Go
> 
> 		if !r.hasCorrectLeaseTypeRLocked(st.Lease) {
> 			return r.requestLeaseLocked(ctx, st, nil /* limiter */)
> ```

ignorable nit: consider structuring this to separate the no-op cases from the switch lease case:
```
if !st.OwnedBy(r.store.StoreID()) {
    return nil
}
if r.hasCorrectLeaseTypeRLocked(st.Lease) {
    return nil
}
return r.requestLeaseLocked(ctx, st, nil /* limiter */)
```

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124223#-:-Ny1Pe-XEn9IoZZZq9fX:bzftgo7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124223#-Ny15_QZCnYHJBvvPVhz:-Ny1PJHl2EDBQkePifBr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d08fe81c90bb73831f7827051eafe5d8dda6a6ce/pkg/kv/kvserver/replica_range_lease.go#L1621)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should pull the `r.store.Clock().NowAsClockTimestamp()` outside of the replica mutex.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124223#-Ny15eEo-Re9cap_5cUb:-Ny1PbNI4QcyKvGzjjMl:bm83bv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d08fe81c90bb73831f7827051eafe5d8dda6a6ce/pkg/kv/kvserver/replica_range_lease.go#L1627)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

ignorable nit: consider structuring this to separate the no-op cases from the switch lease case:
```
if !st.OwnedBy(r.store.StoreID()) {
    return nil
}
if r.hasCorrectLeaseTypeRLocked(st.Lease) {
    return nil
}
return r.requestLeaseLocked(ctx, st, nil /* limiter */)
```
</blockquote></details>

This is easier to follow, updated.

**Comment by kvoli** [comment]
bors r=nvanbenschoten

**Review by nvb — APPROVED** [review]

**Pull request merged**
