### PR TITLE
cmd/roachprod,cmd/roachtest: automatic core dump generation and collection

### LINKED ISSUE #32921: roachtest: make it easy to enable and gather core dumps
https://github.com/cockroachdb/cockroach/issues/32708 shows a test failure with a crash deep inside RocksDB. The stack trace is not enough to Go on, but a core dump would allow us to do post-mortem debugging. Roachtest should provide a facility for making it easy to create and gather core dumps from a cluster. This involves running `cockroach` with the `GOTRACEBACK=crash` env variable, running `ulimit -c unlimited`, and making sure the system is configured to do something sensical with core dumps when they are generated (both kernel config and roachtest gathering the resulting dumps).

### LINKED ISSUE #34680: roachtest: set up machines and env to collect core dumps
Relevant for random crashes as well as #34241. This rando script might be helpful. I remember spending way too much time to actually get this to work.
Additionally we want `GOTRACEBACK=crash` for all `roachprod run/start` invocations.

```
#!/usr/bin/env bash
CMD_USAGE=""
source "$(dirname "$0")/config.sh"

CORE_PATTERN="/tmp/core.%e.%p.%h.%t"

ssh_task "
  set -euo pipefail
  echo -e '
  * soft core unlimited
  * hard core unlimited
  root soft core unlimited
  root hard core unlimited
  ' | sudo tee /etc/security/limits.d/core_unlimited.conf > /dev/null
  echo '$CORE_PATTERN' | sudo tee /proc/sys/kernel/core_pattern > /dev/null
  sudo sed -i'~' 's/enabled=1/enabled=0/' /etc/default/apport
  sudo sed -i'~' '/.*kernel\\.core_pattern.*/c\\' /etc/sysctl.conf
  echo 'kernel.core_pattern=$CORE_PATTERN' | sudo tee -a /etc/sysctl.conf > /dev/null
  echo 'Done. Make sure cockroach is started through ulimit -c unlimited, or it will run with a soft limit of zero and still not create core dumps.'
"


```

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #32921
Fixes #34680

### CODE REVIEW

**Comment by petermattis** [comment]
I tested this works, both by manually creating a cluster, and by tweaking the `kv0` roachtest to run `killall -ABRT cockroach` instead of running the workload.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35311#-:-LZuMJX2-3dApEKfVgPs:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @petermattis, and @tbg)

___
*[pkg/cmd/roachprod/vm/aws/support.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35311#-LZuLj9m-eCwTlEUmTyZ:-LZuLj9m-eCwTlEUmTy_:bpgmr8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/41029433c3dc35eceb63cc505b80a827cd7f0736/pkg/cmd/roachprod/vm/aws/support.go#L101)):*
> ```Go
> EOF
> 
> mkdir -p /tmp/cores
> ```

please sprinkle some comments

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35311)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/cmd/roachprod/vm/aws/support.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35311#-LZuLj9m-eCwTlEUmTyZ:-LZuOrHi5QQCHi5Ws-HU:bvznsfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/41029433c3dc35eceb63cc505b80a827cd7f0736/pkg/cmd/roachprod/vm/aws/support.go#L101)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please sprinkle some comments
</blockquote></details>

Heh, I agree with the sentiment, but I'm not quite sure what all this is about either. I copied these lines from a script @tbg provided. I would bet he copied them from stackoverflow or elsewhere on the internet.

**Comment by petermattis** [comment]
bors r=andreimatei

**Pull request merged**
