### PR TITLE
logictest: make local-legacy-schema-changer a default config

### PR DESCRIPTION
**Pull request by mgartner**
#### logictest: make local-legacy-schema-changer a default config

The `local-legacy-schema-changer` config was never run in CI because it
was not added to the list of default configs. This commit fixes that.
Some instructions for adding new configs have been added above the list
of configs.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
I don't really love this solution, but it was the quickest one I could see. The assumption introduced in #84221 that a logic test config package should only be generated if there is at least one test file that explicitly mentions the config in a `# Logic: <config>` directive seems incorrect. I'd love to hear better ideas for fixing this.

I also noticed that no tests are generated for the `multiregion-invalid-locality` too, but a quick fix was less obvious there.

**Review by ajwerner — APPROVED** [review]
:lgtm: just missing some sort of generation

> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85384#-:-N8Ofk_jCZ-nWQwpE09L:b-69og9g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
> The assumption introduced in https://github.com/cockroachdb/cockroach/pull/84221 that a logic test config package should only be generated if there is at least one test file that explicitly mentions the config in a # Logic: <config> directive seems incorrect.

I'll look at this, I thought I kept the logic identical but clearly I missed something.

**Review by rickystewart — APPROVED** [review]
`dev generate bazel` is necessary I think.

**Comment by mgartner** [comment]
> I'll look at this, I thought I kept the logic identical but clearly I missed something.

AFAIK the previous logic would run all configurations for files which had no `# LogicTest: ...` directive. But the logic below won't create an entry in `configPaths` for a config if it is not mentioned explicitly in at least one directive:

https://github.com/cockroachdb/cockroach/blob/f124604581f883c4087dedc248f0df8e1c3b078e/pkg/sql/logictest/logictestbase/logictestbase.go#L804-L820

Any ideas about the `multiregion-invalid-locality` config?

I'm wondering if there's a smart way to audit the CI output to check that all config/file variations that were previously tested are still tested.

**Comment by rickystewart** [comment]
> Any ideas about the multiregion-invalid-locality config?

Not yet, I'm looking at this now.

> I'm wondering if there's a smart way to audit the CI output to check that all config/file variations that were previously tested are still tested.

I'm not sure. I did a spot check with the refactor but obviously missed some cases.

**Comment by rickystewart** [comment]
> I also noticed that no tests are generated for the `multiregion-invalid-locality` too, but a quick fix was less obvious there.

Hmm. I'm not seeing a problem here. Looking at a [test run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/5859989?buildTab=tests&name=multiregion-invalid) from before the refactor, the only test running with that config is `
TestLogic/multiregion-invalid-locality/multiregion-invalid-locality`, which is captured after the refactor as `pkg/sql/logictest/tests/multiregion-invalid-locality.TestLogic_multiregion_invalid_locality`.

**Comment by rickystewart** [comment]
Searching in that list of tests, I'm not seeing any `local-legacy-schema-changer` tests at all. Did you validate that #84221 *regressed* this, or is it possible tests with these configs were not running at all prior to it?

**Comment by rickystewart** [comment]
I checked a few older unit test runs, none of which had a `local-legacy-schema-changer` logic test either.

**Comment by mgartner** [comment]
> I checked a few older unit test runs, none of which had a local-legacy-schema-changer logic test either.

Weird. I don't understand how this config would ever run then. There are a couple tests that appear to specifically rely on the `local-legacy-schema-changer` config:

https://github.com/cockroachdb/cockroach/blob/e7dd7b2a95b0b16df6859604b9d67c207bd3f3d2/pkg/sql/logictest/testdata/logic_test/views#L336

https://github.com/cockroachdb/cockroach/blob/9e6ab9df9c0132ebb6999391c9a648f619ce506b/pkg/sql/logictest/testdata/logic_test/fk#L666-L676

https://github.com/cockroachdb/cockroach/blob/f517d5d12bb06a1fc0e47c899cf257ad547b5383/pkg/sql/logictest/testdata/logic_test/virtual_columns#L1333

https://github.com/cockroachdb/cockroach/blob/c53b60671bc2ad685daf5c4c52dca11ec4ca8db1/pkg/sql/logictest/testdata/logic_test/privileges_comments#L26-L38

Maybe someone from @cockroachdb/sql-schema can chime in. Was `local-legacy-schema-changer` meant to be part of the default logic test configs?

**Comment by ajwerner** [comment]
@fqazi added this test here; https://github.com/cockroachdb/cockroach/pull/81528

Maybe it needed to be added a default configuration? Does it not run unless specifically requested?

**Comment by mgartner** [comment]
So it sounds like it should have been added as a default config, but never was. I updated the commit message to reflect this, and I added some instructions for adding a new config above the list of configs.

**Comment by fqazi** [comment]
Yes, it was meant to be part of the default config. This was a gap on my part when adding the new config in here, good find!

**Review by fqazi — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85384)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @fqazi)

**Comment by mgartner** [comment]
@fqazi some tests are failing with the `local-legacy-schema-changer` config. Let me know if I should disable that config for those tests, or if it's actually a bug that needs to be fixed.

**Comment by fqazi** [comment]
Sorry, this fell off my radar looking into the failures now

**Pull request closed without merging**
