### PR TITLE
split: add additional lb split tests and fix decider weight

### LINKED ISSUE #102132: split: decider does not pass weight into key finder
The load based split decider controls the lifecycle of finding split points based on load. 

The weight being passed in to the key finder is currently always 1, regardless of whether the weighted or unweighted finder is being used.

https://github.com/cockroachdb/cockroach/blob/2c098556b2965b5e73d652579c328823a57df254/pkg/kv/kvserver/split/decider.go#L232-L232

This is fine for the unweighted finder, however defeats the purpose of the weighted finder.

We turned on the weighted finder by default for [CPU](https://github.com/cockroachdb/cockroach/pull/96128) [here](https://github.com/cockroachdb/cockroach/pull/97424).

We should update the decider code to pass in the weight, which is given on Record.

Jira issue: CRDB-27299

### PR DESCRIPTION
**Pull request by kvoli**
This PR adds additional testing for load based splits, correctly passes in the weight into the weighted finder and makes the weighted finder only retain safe split keys, as opposed to all keys.

The additional testing consists of:
- Extending to the existing experimental tests to be datadriven and asserted on
- Roachtests for CPU load based splits

The behavior changes are:
- Only row-prefixes are retained in the samples of the weighted finder, as opposed to full keys.
- The weight is used in the weighted finder - previously CPU load based splitting was acting as a hybrid between QPS splitting and CPU.

Touches: #102136
Resolves: #102132

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Flushing comments before going into a series of meetings. I still need to look at the last commit here.

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-:-NTyviD84hPgxA2r0yvn:b77nhrd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @kvoli, and @smg260)

___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTyu5TbAbOJ9Jd1ceNn):*
Not doing this feels like it's changing the behavior of the weighted finder. Most user request keys are not safe split keys because they include a column family suffix. As a result, we're now comparing a pre-safe request key with a post-safe candidate key. So if a user is hitting a single key with a column family suffix, we'll consider this to be an access to the right of the corresponding candidate key. Is that ok? If so, is it ok because `Case key >= f.samples[i].Key` treats a direct access the same as an access to the right of a candidate key?
___
*[`pkg/cmd/roachtest/tests/split.go` line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTyvVem52nf0sgOXMz-:-NTyvVem52nf0sgOXMz0:b-l829vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f77df2cbfac142e3732b6a09e2a121c71a93191/pkg/cmd/roachtest/tests/split.go#L171)):*
> ```Go
> 			}
> 			if _, err := db.ExecContext(ctx, fmt.Sprintf("SET CLUSTER SETTING kv.range_split.load_cpu_threshold = '%s'",
> 				params.cpuThreshold.String())); err != nil {
> ```

nit: `.String()` is unnecessary.
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 599 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTytRsH-VwwiPI8od6-:-NTytRsH-VwwiPI8od60:b-r21i8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa104daabb938eb829fd7bcf4e304217d09a702/pkg/kv/kvserver/split/load_based_splitter_test.go#L599)):*
> ```Go
> // To test multiple concurrent splitters in a cluster, see
> // asim/tests/testdata/example_splitting, which enables larger testing.
> func TestDataDriven(t *testing.T) {
> ```

Consider splitting this new testing into an initial commit, so that the git history reflects the impact that passing the weight to the splitFinder has.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-:-NTzR22O67fYKSmimno8:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @kvoli, and @smg260)

___
*[`pkg/cmd/roachtest/tests/split.go` line 284 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTzQqKS0DgxjnM6_p8m:-NTzQqKS0DgxjnM6_p8n:b-s5z4bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3510f12b5a53e6c8dfb443fabe0ef4e2d111b32/pkg/cmd/roachtest/tests/split.go#L284)):*
> ```Go
> 				maxSize:      10 << 30,               // 10 GB
> 				cpuThreshold: 100 * time.Millisecond, // 1/10th of a CPU per second.
> 				// We expect 1-4 splits. There isn'have the same requirement for
> ```

"isn'have"

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102291)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @kvoli, and @smg260)

___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 131 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTz_oX2EwAGtDFJoSVY:-NTz_oX2EwAGtDFJoSVZ:b-qiqkah) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3510f12b5a53e6c8dfb443fabe0ef4e2d111b32/pkg/kv/kvserver/split/weighted_finder.go#L131)):*
> ```Go
> 	// key, it is possible for all sample keys to map to the same split key
> 	// implicitly with column families.
> 	if safeKey, err := keys.EnsureSafeSplitKey(key); err == nil {
> ```

Is the error case rare, in that this will usually do the transformation to a `safeKey`?


Also, I don't understand how the problem mentioned in the commit comment is solved:
"Previously, the weighted load split finder could retain samples for any
  key that was a start key of a request span.

  This was problematic as the split key which is used, always has user
  column suffixes removed by calling `keys.EnsureSafeSplitKey` - meaning
  that it was possible for every sampled key to refer to the same key
  after this call."

Now, won't we just have the same safe key be in all the samples? We don't seem to dedup the keys in the `samples` array.
What am I missing?

**Review by kvoli — COMMENTED** [review]
I'm going to update the data driven test request generators to apply a different weight distribution than the access, over the keyspace. I realized the actual weight per key was highly correlated to access, since we were applying the weight independently onto a key generator. 

I'll ping one more time to double check that, tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-:-NU-8EU-C0-kntuLA6fu:b-9whoml)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @nvanbenschoten, @smg260, and @sumeerbhola)

___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTyu5TbAbOJ9Jd1ceNn):*
> Is that ok? If so, is it ok because Case key >= f.samples[i].Key treats a direct access the same as an access to the right of a candidate key?

It is okay for the reason you mentioned. `key >= f.samples[i].Key`  implies `key >= safe(f.samples[i].Key)`, as the safe split key can only ever be ordered before the pre-safe split key.
___
*[`pkg/cmd/roachtest/tests/split.go` line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTyvVem52nf0sgOXMz-:-NTz1XekEz6Sq2Bego2H:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f77df2cbfac142e3732b6a09e2a121c71a93191/pkg/cmd/roachtest/tests/split.go#L171)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `.String()` is unnecessary.
</blockquote></details>

Removed.
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 131 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTz_oX2EwAGtDFJoSVY:-NTzexFL-hPHlyl91YOK:bkjm3et) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3510f12b5a53e6c8dfb443fabe0ef4e2d111b32/pkg/kv/kvserver/split/weighted_finder.go#L131)):*
> Is the error case rare, in that this will usually do the transformation to a safeKey?

I think so but I also don't have data for it.

> Now, won't we just have the same safe key be in all the samples? We don't seem to dedup the keys in the samples array.

We don't de-dupe. The problem still exists in that the start key will be a popular key, however now we wouldn't suggest the start key as a potential split point as all sampled requests would be to the RHS of the start key.

We now would log it as imbalanced and a popular key, like it is. 

The finder will remain around, not suggesting a split key, instead of suggesting the start key. This is still a problem that we could address.

I suppose my commit message is a bit misleading in what is actually be solved here, I will update.

My aim was to stop the split finder suggesting the start key and log/bump metrics that a key is popular instead.
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 599 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTytRsH-VwwiPI8od6-:-NTz1jc2CG-ieUURMr56:b-mbql1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa104daabb938eb829fd7bcf4e304217d09a702/pkg/kv/kvserver/split/load_based_splitter_test.go#L599)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider splitting this new testing into an initial commit, so that the git history reflects the impact that passing the weight to the splitFinder has.
</blockquote></details>

Sounds good, will do.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102291)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @kvoli, @nvanbenschoten, and @smg260)

___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 131 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTz_oX2EwAGtDFJoSVY:-NU-XS0zAwh77B0HLnIb:bfpllo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3510f12b5a53e6c8dfb443fabe0ef4e2d111b32/pkg/kv/kvserver/split/weighted_finder.go#L131)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> Is the error case rare, in that this will usually do the transformation to a safeKey?

I think so but I also don't have data for it.

> Now, won't we just have the same safe key be in all the samples? We don't seem to dedup the keys in the samples array.

We don't de-dupe. The problem still exists in that the start key will be a popular key, however now we wouldn't suggest the start key as a potential split point as all sampled requests would be to the RHS of the start key.

We now would log it as imbalanced and a popular key, like it is. 

The finder will remain around, not suggesting a split key, instead of suggesting the start key. This is still a problem that we could address.

I suppose my commit message is a bit misleading in what is actually be solved here, I will update.

My aim was to stop the split finder suggesting the start key and log/bump metrics that a key is popular instead.
</blockquote></details>

Got it. Thanks for the clarification.
This could definitely use a more explanatory code comment.

**Review by kvoli — COMMENTED** [review]
I pushed the testing into an initial commit. I also updated the datadriven generators to allow mixing different request configs - before we ended up with a pretty high correlation between weight and access. This method seemed the simplest to accomplish some skew between the two.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-:-NU2n04KEKgEwiFJ65Db:b-3drh3d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @nvanbenschoten, @smg260, and @sumeerbhola)

___
*[`pkg/cmd/roachtest/tests/split.go` line 284 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTzQqKS0DgxjnM6_p8m:-NU2m84-5Brs2_fok-6p:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3510f12b5a53e6c8dfb443fabe0ef4e2d111b32/pkg/cmd/roachtest/tests/split.go#L284)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"isn'have"
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 131 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-NTz_oX2EwAGtDFJoSVY:-NU2mBhS-30bcROrUReZ:b-jcwt1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3510f12b5a53e6c8dfb443fabe0ef4e2d111b32/pkg/kv/kvserver/split/weighted_finder.go#L131)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Got it. Thanks for the clarification.
This could definitely use a more explanatory code comment.
</blockquote></details>

Added a more explanatory comment here.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102291#-:-NU3-ros0Kn2t6yJ5QvJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @sumeerbhola)

**Comment by kvoli** [comment]
TYFTR

bors r=nvanbenschoten

**Pull request merged**
