### PR TITLE
sql: maintain leases minutely in background loop during dist backfill

### PR DESCRIPTION
**Pull request by dt**
Extending the lease in the same loop as the distsql flow means it relies on that flow to finish promptly --
if it runs long (waiting on a flush or something), the loop is blocked and may fail loop around and extend
the lease in time.

This moves the lease extending to a separate, background loop, removing the strict time concerrn from the distsql flow.
As structured, job progress information is still only updated one per loop, so the flow should still attempt to be
bounded in execution time to avoid blocking the loop too long, but at least now if it does, it should not risk the
schema change lease being lost.

This opens the possibility of raising the default backfill run duration -- it was conservatively set lower since if
it ran over for any reason -- i.e. blocked on a single slow request -- it could cause the problems described above, so
as a result its default had to be *much* lower than the lease time.

Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
based on what Lucy saw, we suspect we're running many copies of the same job, which seems easy to explain if a batch in this loop -- prior to this change -- blocked the loop for more than the lease time (5min), causing a second node to grab the lease and start another copy of the schema change. Eventually this appears to lead to so many copies running that the nodes OOM.

If that's true, this change is a bug fix and will want a back port, so I'll follow up on any review comments as soon as I get them and try to get this merged promptly.

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36641)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/sql/backfill.go, line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36641#-Lc2Wyxv6r-IJgyCOyp3:-Lc2Wyxw05pxNWS-UJXj:bfv22l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e07b126e4e3f8c2e24cf409fa1df44796c091f/pkg/sql/backfill.go#L561)):*
> ```Go
> 	g := ctxgroup.WithContext(ctx)
> 	g.GoCtx(func(ctx context.Context) error {
> 		tick := time.NewTicker(time.Minute)
> ```

please use the timeutil.newTicker() also set it to schemachanger.lease.duration * 0.2. Thanks

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36641)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @vivekmenezes)

___
*[pkg/sql/backfill.go, line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36641#-Lc2Wyxv6r-IJgyCOyp3:-Lc2aFPg4efBIrQqIhXm:b-4b1gil) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e07b126e4e3f8c2e24cf409fa1df44796c091f/pkg/sql/backfill.go#L561)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

please use the timeutil.newTicker() also set it to schemachanger.lease.duration * 0.2. Thanks
</blockquote></details>

we don't wrap ticker in timeutil -- ticker is fine _if you stop it_.
Added the Stop() and switched to the lease duration / 4.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36641)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Comment by dt** [comment]
🥐 flake is ChangefeedMonitoring, which I don't _think_ is related.

bors r=vivekmenezes

**Pull request merged**
