### PR TITLE
storage: properly cleanup intentResolver's inFlight refcount

### PR DESCRIPTION
**Pull request by vivekmenezes**

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
The logic here :lgtm: but could you explain the problem in the commit message for posterity? Was there a corresponding issue for this problem?

@tschottdorf should still take a look.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/intent_resolver_test.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19138#-Kw229d5xAa0Ip0gNBlU:-Kw229d5xAa0Ip0gNBlV:b-4rwo9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/99351daba4fbed6804d7028d7e723137d960628e/pkg/storage/intent_resolver_test.go#L41)):*
> ```Go
> 	intents := []roachpb.Intent{
> 		{Span: roachpb.Span{Key: roachpb.Key("a")}, Status: roachpb.PENDING},
> 		{Span: roachpb.Span{Key: roachpb.Key("b")}, Status: roachpb.ABORTED},
> ```

Should we assert that we see this behavior when the status is COMMITTED as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19138#-:-Kw231cr3P2uWJfNHx3E:bny7ca)*

**Comment by vivekmenezes** [comment]
There is no issue. In fact I'm not even sure if this code path can even get traversed based on the comment there. I made this commit while reading the code.

**Comment by tschottdorf** [comment]
Good catch, :lgtm: mod @nvanbenschoten's comments.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/intent_resolver.go, line 165 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19138#-Kw9eh4JgDo3EPP-rfAF:-Kw9eh4JgDo3EPP-rfAG:b-54ckim) ([raw file](https://github.com/cockroachdb/cockroach/blob/99351daba4fbed6804d7028d7e723137d960628e/pkg/storage/intent_resolver.go#L165)):*
> ```Go
> 	// TODO(tschottdorf): can optimize this and use same underlying slice.
> 	var pushIntents []roachpb.Intent
> 	cleanupPushIntents := func() {
> ```

`cleanupPushIntentsLocked`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19138#-:-Kw9fSaZfyZ_oTvZv5E5:b-1k4lfv)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/intent_resolver.go, line 165 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19138#-Kw9eh4JgDo3EPP-rfAF:-KwAqeT0DRSRBPoydnLd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30facc2a5609a6d2ee58a244178c43c325f73a8a/pkg/storage/intent_resolver.go#L165)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`cleanupPushIntentsLocked`
</blockquote></details>

Done.

---

*[pkg/storage/intent_resolver_test.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19138#-Kw229d5xAa0Ip0gNBlU:-KwAqfa0ZPiprYg1EfxY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30facc2a5609a6d2ee58a244178c43c325f73a8a/pkg/storage/intent_resolver_test.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we assert that we see this behavior when the status is COMMITTED as well?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19138)*

**Pull request merged**
