### PR TITLE
clusterversion: bump version to 24.1

### PR DESCRIPTION
**Pull request by RaduBerinde**
This commit enacts the following steps:
 - add `V23_2` release version key
 - add `V24_1Start` version key
 - add `V24` version key alias
 - add `local-mixed-23.2` logictest config
 - create new bootstrap files (from the testdata), add to initial
   values map
 - update `pkg/build/version.txt` to `v24.1.0-alpha.00000000`
 - update releases file:
```
  bazel build //pkg/cmd/release:release
  _bazel/bin/pkg/cmd/release/release_/release update-releases-file
```

We also make a small cleanup change to remove
`firstUpgradesAfterPreExistingReleases` and instead use a helper
function for first upgrades (and check that all `Start` versions have
the expected description).

Epic: none
Release note: None

### CODE REVIEW

**Review by celiala — APPROVED** [review]
The mapping for cockroach_releases.yaml should instead be:
* 23.2 --> predecessor: 23.1  
* 24.1 --> predecessor: 23.2  
i.e. so leave existing one, but add a new key/value for 24.1

Otherwise, LGTM! Thanks for all the work!

> Reviewed 19 of 59 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112271#-:-Nh7YoiG07J1RMN2GVQ3:b9l4g5u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msbutler, and @RaduBerinde)

___
*[`pkg/testutils/release/cockroach_releases.yaml` line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112271#-Nh7XuRRDpB7moQ26iTn:-Nh7XuRRDpB7moQ26iTo:by6kfzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ee2c728597c21753663666ba1bccb27a5fa77c0/pkg/testutils/release/cockroach_releases.yaml#L21)):*
> ```YAML
>   - 23.1.0
>   predecessor: "22.2"
> "24.1":
> ```

This should be:
23.2 --> predecessor: 23.1
24.1 --> predecessor: 23.2

**Review by celiala — COMMENTED** [review]
We synced offline about cockroach_releases.yaml:
- change in PR is autogenerated + expected
- script that updates it will make it look as expected once we publish 23.2.0-beta.1 (as part of the runbook for publishing releases)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112271#-:-Nh83w4YDP46txYincyl:b6xkmne)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msbutler, and @RaduBerinde)

**Comment by RaduBerinde** [comment]
Thank you!

bors r+

**Pull request merged**
