### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by tamird**
Minor followup to #1760.

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by MBerhault** [comment]
this seems like exactly the kind of place where we want pointers. Could you explain your reasoning?

**Comment by tamird** [comment]
Why do we want pointers?

**Comment by tamird** [comment]
My reasoning is that values should be used by default, and pointers should be used only when:
- we want to mutate a function argument
- we want to make the binding `nil`able

Since neither of those is needed here, we should use values.

**Comment by tschottdorf** [comment]
I'm with @tamird. What's your reasoning @MBerhault?

**Comment by MBerhault** [comment]
I'm fine with the arg being passed by value given the lack of const reference in go. However, returning the response by value makes no sense. We're owning it, and we're returning it. There is no confusion about ownership or disallowing mutation.

**Comment by tamird** [comment]
What is the value of returning a pointer? Returning by value makes it impossible to accidentally return nil.

**Comment by MBerhault** [comment]
Returning a pointer is one less copy. Returning nil with an error is perfectly acceptable. If you want to make sure we don't return nil,nil, you can panic on it.
However, I don't really want to see us moving towards extra copies just because, we'll just have to change it all back when we start worrying about memory churn.

**Comment by tamird** [comment]
> Returning a pointer is one less copy.

This is not true. The Go compiler does RVO which makes this moot [0].

[0] https://groups.google.com/forum/#!topic/golang-nuts/LvIAEj7pUF8

**Comment by MBerhault** [comment]
ah. I keep forgetting about that. nevermind then.

**Pull request merged**
