### PR TITLE
roachtest: update blacklist for hibernate 5.4.7

### PR DESCRIPTION
**Pull request by rafiss**
Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
This should help #41751

**Review by yuzefovich — APPROVED** [review]
:lgtm:

Should this PR close #41751?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42002#-:-LsNsHAu4GLdEmNkIOfg:bw77lbg)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
