### PR TITLE
rpc: use grpc.Chain{Unary,Stream}Interceptor

### PR DESCRIPTION
**Pull request by tbg**
These were not available when the code was first written but they are
very helpful for keeping things tidy.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
(I'm touching the interceptors both for pprof-across-RPC-boundaries and multi-tenant reasons, which is why this PR is happening)

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51025#-:-MBjICpcCmkghpnLihKR:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/rpc/context.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51025#-MBjHt3DCI7-bAKQV6QI:-MBjHt3EAdr3pnDiuP2A:bc66bnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0aa53c554f9f2b124738b28bcfdc61672051020/pkg/rpc/context.go#L187)):*
> ```Go
> 	}
> 
> 	var unaryInterceptor []grpc.UnaryServerInterceptor
> ```

Add a comment above this explaining how the order in this slice translates to execution order. Something along the lines of the `// Execution is done in left-to-right order` comment on `grpc.ChainUnaryServer`.

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51025#-:-MBjJr5h2prYvwKhIrp4:bb6ywmx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

**Comment by tbg** [comment]
bors r=nvanbenschoten,andreimatei

**Pull request merged**
