### PR TITLE
distsql: wait for flows to finish when draining and avoid planning on draining nodes

### PR DESCRIPTION
**Pull request by asubiotto**
This change adds a graceful draining mode to the distsql server which causes a draining node to wait for all running flows to finish and gossip its draining state to the cluster, so that nodes do not plan flows on a draining node. Note that all of this is still best effort, as a gateway could not receive the gossip info in time or a flow could not be registered yet, and thus not waited for, while draining.

Release note (sql): Wait for queries to finish up to some timeout when draining gracefully and avoid planning queries on draining nodes.

### CODE REVIEW

**Comment by andreimatei** [comment]
apparently release notes have to be in all commits

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/server.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L-YI1YzY5RAS52hpAZl:-L-YI1YzY5RAS52hpAZm:b-j147ja) ([raw file](https://github.com/cockroachdb/cockroach/blob/75cd05ef8c7bfa50954fbf444e0d923e38ebc6ae/pkg/sql/distsqlrun/server.go#L83)):*
> ```Go
> // flowDrainMaxWait is the amount of time a draining server gives to flows to
> // finish work before proceeding.
> const flowDrainMaxWait = 10 * time.Second
> ```

isn't there a higher-level global for this (across the drains of all the sub-systems)?

---

*[pkg/sql/distsqlrun/server.go, line 199 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L-YIG3T626eWvOenMFN:-L-YIG3T626eWvOenMFO:b-tw7aoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/75cd05ef8c7bfa50954fbf444e0d923e38ebc6ae/pkg/sql/distsqlrun/server.go#L199)):*
> ```Go
> // SetDraining (when called with 'true'), waits for currently running flows to
> // finish up to flowDrainMaxWait. It is a noop if called with false.
> func (ds *ServerImpl) SetDraining(drain bool) {
> ```

return error if the timeout is hit?

---

*[pkg/sql/distsqlrun/server.go, line 207 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L-YJUboEZ_-UlEnrXAo:-L-YJUboEZ_-UlEnrXAp:b3nlkj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/75cd05ef8c7bfa50954fbf444e0d923e38ebc6ae/pkg/sql/distsqlrun/server.go#L207)):*
> ```Go
> 		return
> 	}
> 	// There is a possibility that there are flows not yet registered that we
> ```

this seems funky to me. If I remember correctly, the plan was for the registry to stop accepting flows some time after draining started.
And then I think the waiting logic should move to the flowRegistry directly; that guy hopefully can do something better than spawn one go-routine per flow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-:-L-YHmxXSwQTFRzKZuRU:b-61a6nv)*

**Comment by asubiotto** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsqlrun/server.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L-YI1YzY5RAS52hpAZl:-L-hBbGOSUoryZAs9yCY:b-bpng0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/75cd05ef8c7bfa50954fbf444e0d923e38ebc6ae/pkg/sql/distsqlrun/server.go#L83)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

isn't there a higher-level global for this (across the drains of all the sub-systems)?
</blockquote></details>

There is now (new commit)

---

*[pkg/sql/distsqlrun/server.go, line 199 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L-YIG3T626eWvOenMFN:-L-msjRbc3kY-b-YXqgg:bccfthe) ([raw file](https://github.com/cockroachdb/cockroach/blob/75cd05ef8c7bfa50954fbf444e0d923e38ebc6ae/pkg/sql/distsqlrun/server.go#L199)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

return error if the timeout is hit?
</blockquote></details>

Per our discussion on errors, with the crux of it being that an error returned with our current code interrupts our draining process, I won't return any errors from this `SetDraining` method. Future work should be done to ensure that errors do not interrupt the draining process.

---

*[pkg/sql/distsqlrun/server.go, line 207 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L-YJUboEZ_-UlEnrXAo:-L-mrHP7ZNgaMRWbLf-0:b-gzvs6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/75cd05ef8c7bfa50954fbf444e0d923e38ebc6ae/pkg/sql/distsqlrun/server.go#L207)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this seems funky to me. If I remember correctly, the plan was for the registry to stop accepting flows some time after draining started.
And then I think the waiting logic should move to the flowRegistry directly; that guy hopefully can do something better than spawn one go-routine per flow.
</blockquote></details>

Moved the waiting logic to the flowRegistry. I'm not sure how to avoid spawning a goroutine per flow due to the blocking `Wait()` call. I also added the behavior of rejecting flows once the `flowRegistry` starts draining. I know we talked about keeping on accepting flows up to the timeout but I think that this behavior paired with the addition of `gossipDrainWait` (to wait for nodes to receive the message that we are draining) results in not really needing to accept flows up to the timeout. There is still a possibility that flows could slip through but I think this change would be more of an enhancement than a necessity and can be implemented in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450)*

**Comment by andreimatei** [comment]
Reviewed 1 of 6 files at r2.
Review status: 1 of 13 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/flow_registry.go, line 95 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0AYKjMTXKRpydJj_Yb:-L0AYKjMTXKRpydJj_Yc:bxoprvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b863624ef53a331eaf50f1c022677dc8f893ce/pkg/sql/distsqlrun/flow_registry.go#L95)):*
> ```Go
> 	flows map[FlowID]*flowEntry
> 
> 	// draining specifies whether the flowRegistry is draining. If it is, the
> ```

When we were talking, I think the idea was to continue accepting flows while draining.
At the very least, we need to accept them for a little while, to avoid the ugly `time.Sleep(gossipDrainWait)` in your next commit.
But really the point of always accepting is that rejecting them is no better, and likely worse, than accepting them and then terminating the connection when the drain period expires.
Any reason you changed that?

---

*[pkg/sql/distsqlrun/flow_registry.go, line 290 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0AazMWjuaQuaUrctkA:-L0AazMWjuaQuaUrctkB:b8aswqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b863624ef53a331eaf50f1c022677dc8f893ce/pkg/sql/distsqlrun/flow_registry.go#L290)):*
> ```Go
> 	// This helper function sets the flowRegistry draining state and returns
> 	// any flows to wait on.
> 	flows := func() []*flowEntry {
> ```

instead of all this, have you considered adding a cond var to `flowRegistry` and signaling it whenever the contents of `fr.flows` changes? When signaled, the drainer can look at the count of `fr.flows` and return if == 0. 
This would also work for accepting flows after the draining started.

---

*[pkg/sql/distsqlrun/server.go, line 218 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0Abks7cUnjhmO_O8tH:-L0Abks7cUnjhmO_O8tI:b-r940od) ([raw file](https://github.com/cockroachdb/cockroach/blob/2121771d22defab7482edd19bdd4b9f3d8f0c84d/pkg/sql/distsqlrun/server.go#L218)):*
> ```Go
> 		0, // ttl - no expiration
> 	); err != nil {
> 		log.Warningf(context.TODO(), "unable to gossip distsql draining state: %s", err)
> ```

no more TODOs :)

---

*[pkg/sql/pgwire/server.go, line 218 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0AXlbkzY1RGNsjx0Wx:-L0AXlbkzY1RGNsjx0Wy:bx84q6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b7db1d105e1c1f2539c4d3ec0a6604a9ec1bef5/pkg/sql/pgwire/server.go#L218)):*
> ```Go
> // what will happen to connections in different states:
> // https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20160425_drain_modes.md
> func (s *Server) SetDraining(drain bool, drainWait time.Duration) error {
> ```

nit: with the 2nd arg, the interface became kinda ugly. The 2nd argument only makes sense for a value of true. Also, because of the 2nd arg, the meaning of the first bool is not as clear as it used to be when the method looked like a setter - and so if it doesn't look like a setter any more (and in earnest it was never a setter), then ideally the bool would be an enum (at least I've stopped writing methods that take bools as a consequence of the whole inline comments style guide discussion).
I suggest StartDraining()/StopDraining().

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450)*

**Comment by asubiotto** [comment]
Review status: 0 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/distsqlrun/flow_registry.go, line 95 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0AYKjMTXKRpydJj_Yb:-L0ebPwRIUHMmB4IuWAI:b-gywgev) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b863624ef53a331eaf50f1c022677dc8f893ce/pkg/sql/distsqlrun/flow_registry.go#L95)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

When we were talking, I think the idea was to continue accepting flows while draining.
At the very least, we need to accept them for a little while, to avoid the ugly `time.Sleep(gossipDrainWait)` in your next commit.
But really the point of always accepting is that rejecting them is no better, and likely worse, than accepting them and then terminating the connection when the drain period expires.
Any reason you changed that?
</blockquote></details>

Yes, the reason I changed it is because I considered it an enhancement rather than necessary behavior after adding the `time.Sleep(gossipDrainWait)`. Changed it to accept flows while draining.

---

*[pkg/sql/distsqlrun/flow_registry.go, line 290 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0AazMWjuaQuaUrctkA:-L0eZWSEiuIDuKIzXJlm:bvf3ujr) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b863624ef53a331eaf50f1c022677dc8f893ce/pkg/sql/distsqlrun/flow_registry.go#L290)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

instead of all this, have you considered adding a cond var to `flowRegistry` and signaling it whenever the contents of `fr.flows` changes? When signaled, the drainer can look at the count of `fr.flows` and return if == 0. 
This would also work for accepting flows after the draining started.
</blockquote></details>

That's a great idea, done.

---

*[pkg/sql/distsqlrun/server.go, line 218 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0Abks7cUnjhmO_O8tH:-L0inGDUKAnPI7H7dnZm:biqam5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2121771d22defab7482edd19bdd4b9f3d8f0c84d/pkg/sql/distsqlrun/server.go#L218)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

no more TODOs :)
</blockquote></details>

Done. Added another commit that passes down the RPC's context and removed another `context.TODO()` while I was at it.

---

*[pkg/sql/pgwire/server.go, line 218 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0AXlbkzY1RGNsjx0Wx:-L0j3gHs50za5O8OIGvJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b7db1d105e1c1f2539c4d3ec0a6604a9ec1bef5/pkg/sql/pgwire/server.go#L218)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: with the 2nd arg, the interface became kinda ugly. The 2nd argument only makes sense for a value of true. Also, because of the 2nd arg, the meaning of the first bool is not as clear as it used to be when the method looked like a setter - and so if it doesn't look like a setter any more (and in earnest it was never a setter), then ideally the bool would be an enum (at least I've stopped writing methods that take bools as a consequence of the whole inline comments style guide discussion).
I suggest StartDraining()/StopDraining().
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450)*

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/issues/20968 to address the wait for gossip propagation period. That's a bigger project

**Comment by andreimatei** [comment]
> #20968 to address the wait for gossip propagation period. That's a bigger project

Sorry, I don't follow. I'm not suggesting any leasing mechanism to guarantee that anybody has heard about us draining or anything like that (like, I don't think it'd be a good idea for a node to block another node from draining). I'm just saying we should continue accepting streams for like a second. I don't think anything more complicated is needed.

**Comment by vivekmenezes** [comment]
Waiting for a second sounds fine for now. I added the issue in case we want to make this more predictable in the future. That work if needed is not a part of this PR.

---

Review status: 0 of 16 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-:-L0uOk5pC5Gvb9nnxR5K:b-omei89)*

**Comment by asubiotto** [comment]
Updated, PTAL. There is some stuff I still have to work on (i.e. getting number of nodes differently and adding tests) but I wanted to see what you thought of the flowRegistry stuff before doing that

---

Review status: 0 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/cli/start.go, line 739 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0p88WIPQsExUDq7yTh:-L3Zy389hLU3kvPQ9iA9:b-60uklt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a8537e0503c3957ba556d2450ef574123d58fe5/pkg/cli/start.go#L739)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: add a logging tag to this ctx
</blockquote></details>

Done. Not sure I did what I'm supposed to do. Should there be a span as well?

---

*[pkg/sql/distsql_physical_planner.go, line 598 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0pD6Rn1kTTIE3oTtTj:-L3ZyUSB6AYet0bAjbNU:b-ib2wwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6462af9610bb0fbd95f1ddf697cf0dd632d9d67b/pkg/sql/distsql_physical_planner.go#L598)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

VEventf
</blockquote></details>

I want to reuse `errMsg` as the returned error as well.

---

*[pkg/sql/distsqlrun/flow_registry.go, line 96 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0p97yAEI-2tTUbl1KZ:-L3YnT7lLcWMyLsJv7T0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d97b21785cf3d723f4097071693d656174987709/pkg/sql/distsqlrun/flow_registry.go#L96)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

perhaps `flowDone` would be a better name
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/flow_registry.go, line 280 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0pCtvktDzqc6yZ2wtV:-L3Tv4ZnJKqD6GL9fCWq:b-of0b1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d97b21785cf3d723f4097071693d656174987709/pkg/sql/distsqlrun/flow_registry.go#L280)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm confused. I think the behavior we want is:
1) Wait for some gossip propagation period, no matter what (unless single node cluster).
2) Wait until `len(fr.flows) == 0 or flowDrainWait`, whichever comes first.

1) seems to be missing, and I think it's quite important. Otherwise, if drain is called when there's no flows in the registry, it'll finish immediately - too soon for anybody else to get the drain message. No?

Also, I have a question: what error does a consumer get if a producer goes down after its `flowDrainWait` expires?  It currently would be a network error, right? That's not ideal; it'd be nice to get a "producer node drained; query took too long" error. So the registry would explicitly close all the outbound streams when the `flowDrainWait` expires.

And another one: I think we should add a point in time when the registry stops accepting new flows, to prevent different nodes from blocking for many seconds waiting for a flow to connect that is not coming because the producer node went down. This should be quite late (I stand by what I said before - refusing a flow is quite pessimistic, but there's a point where the benefits of avoiding the consumer blocking for a long time outstrip the diminishing chances of the flow finishing if it is allowed to register). 
I'm thinking it could work like this:
- every time a flow is accepted while we're draining, we extend the period we're willing to wait by `expectedConnectionTime` - a short period of time in which we hope that the new flow will be able to establish connections to all its consumers.
- At`flowDrainWait - expectedConnectionTime` we stop accepting any more flows and start returning a "node is shutting down imminently" error from the registry.

This last one is a nice to have, cause if everybody stops scheduling on the draining node because of gossip, it should not be triggered.

What do you think?
</blockquote></details>

I'm onboard with all of this apart from extending our wait time by `expectedConnectionTime` every time a flow is registered. I think it's enough to wait for an extra `expectedConnectionTime` if we have any flows left after all the draining logic. Take a look at the change I made and if you're onboard with it I'll add some more tests.

I believe a consumer currently gets a context canceled error since the flow context gets canceled through the stopper after draining. The error might not be nice but I don't want to add any more changes than necessary in this PR.

---

*[pkg/sql/distsqlrun/flow_registry.go, line 288 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0p9igwH9JUims9So9T:-L3ZV-raHV6yztLLtyFV:bi10qxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d97b21785cf3d723f4097071693d656174987709/pkg/sql/distsqlrun/flow_registry.go#L288)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

TIL that in Go you can signal without holding the mutex.
</blockquote></details>

You can, but I was getting a data race error because of `stopWaiting` so I wrapped this in the same mutex that is used to read.

---

*[pkg/sql/distsqlrun/server.go, line 196 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L0pBKLNoAeqvWe4RUdR:-L3Zuwkqw8FwyUvw9ulZ:b32n8ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/d97b21785cf3d723f4097071693d656174987709/pkg/sql/distsqlrun/server.go#L196)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Sorry, I don't understand what this comment is trying to tell me.
It seems to say that Draining doesn't wait for flows it doesn't know about. Which seems obvious... Am I missing something?
If not, I'd remove it because a) it suggests that we could implement some other behavior and b) it can confuse people on differences between registered flows and connected streams.
</blockquote></details>

Removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-:-L3d3XBVq8dbfS249vDL:b-s2p1aj)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/flow_registry.go, line 327 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L3iqqPUmD5B_ch3EusD:-L3iqqPUmD5B_ch3EusE:bygjph3) ([raw file](https://github.com/cockroachdb/cockroach/blob/60908e1aeb826c4133c24723327b4d13c42bfd8c/pkg/sql/distsqlrun/flow_registry.go#L327)):*
> ```Go
> 	}()
> 
> 	for !(stopWaiting || len(fr.flows) == 0) {
> ```

data race on stopWaiting with the goroutine above?

---

*[pkg/sql/distsqlrun/flow_registry.go, line 349 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L3irhq08fNZBiHvTaom:-L3irhq08fNZBiHvTaon:bke5e0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/60908e1aeb826c4133c24723327b4d13c42bfd8c/pkg/sql/distsqlrun/flow_registry.go#L349)):*
> ```Go
> 	// give any flows that were registered in the
> 	// flowDrainWait - expectedConnectionTime window enough time to establish
> 	// connections to their consumers so that these do not block for a long time
> ```

s/these/the consumers

---

*[pkg/sql/distsqlrun/server.go, line 83 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L3ise1bAcySRwzEh0v1:-L3ise1bAcySRwzEh0v2:b-bssvtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/60908e1aeb826c4133c24723327b4d13c42bfd8c/pkg/sql/distsqlrun/server.go#L83)):*
> ```Go
> const MinAcceptedVersion DistSQLVersion = 6
> 
> // minDrainWait is the minimum amount of time the server allows for any incoming
> ```

this comment is not very clear. Say something about draining and about gossip propagation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-:-L3ispjYuttR0t3Trapb:bnfp4nl)*

**Comment by asubiotto** [comment]
Review status: 0 of 15 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/sql/distsqlrun/flow_registry.go, line 327 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L3iqqPUmD5B_ch3EusD:-L41qNLvcCA9HL7y8W1r:b6dqmz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/60908e1aeb826c4133c24723327b4d13c42bfd8c/pkg/sql/distsqlrun/flow_registry.go#L327)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

data race on stopWaiting with the goroutine above?
</blockquote></details>

Done. Somehow the change hadn't made it in...

---

*[pkg/sql/distsqlrun/flow_registry.go, line 349 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L3irhq08fNZBiHvTaom:-L41pCPZtrsom9GpeQAR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60908e1aeb826c4133c24723327b4d13c42bfd8c/pkg/sql/distsqlrun/flow_registry.go#L349)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/these/the consumers
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/server.go, line 83 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450#-L3ise1bAcySRwzEh0v1:-L41dld94yDSiie5qNOz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60908e1aeb826c4133c24723327b4d13c42bfd8c/pkg/sql/distsqlrun/server.go#L83)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this comment is not very clear. Say something about draining and about gossip propagation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20450)*

**Comment by asubiotto** [comment]
Thanks for your review andrei! I'm planning on merging this this evening if there aren't any objections.

**Pull request merged**
