### PR TITLE
sql: allow resolution of object names under schemas

### LINKED ISSUE #50872: sql: allow for creation and resolution of objects under user defined schemas
Since we can now create schemas, we should be able to create objects in them.

### PR DESCRIPTION
**Pull request by rohany**
This PR allows creation of objects (types, tables, views, ...) in
schemas, and allows for resolution of those objects during query
planning.

Fixes #50872.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Second commit please.

This is is still a WIP, but I've done some API changing to allow for resolution of schemas when we actually need the descriptor, so I'd like some feedback there.

**Comment by rohany** [comment]
Hmm, i meant to open this as a draft, and can't go back.

**Review by ajwerner — COMMENTED** [review]
Nice. Not quite there yet. To what extent are you trying to get this merged ahead of leasing? 

> Reviewed 21 of 31 files at r2, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-:-MB4TESNCikhjQmKejgl:ba57re7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @lucy-zhang, and @rohany)

___
*[pkg/sql/create_table.go, line 191 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4QxoH1q6FPH_anrQZ:-MB4QxoH1q6FPH_anrQ_:b-i9e2yp) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/sql/create_table.go#L191)):*
> ```Go
> 			schemaID = keys.PublicSchemaID
> 		} else if isVirtualSchema(tableName.Schema()) {
> 			return nil, 0, pgerror.Newf(pgcode.InvalidName, "schema cannot be modified: %q", tableName.Schema())
> ```

nit: is this the right error code? 
___
*[pkg/sql/create_type.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4RJio1J38-5XxR3jx:-MB4RJio1J38-5XxR3jy:b-z8mc3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/sql/create_type.go#L80)):*
> ```Go
> 	params runParams, name *tree.TypeName, db *sqlbase.ImmutableDatabaseDescriptor,
> ) (sqlbase.DescriptorKey, sqlbase.ID, error) {
> 	// Get the ID of the schema the type is being created in.
> ```

It feels like there could be a function to extract here as this seems almost identical to the code in `create_table.go`
___
*[pkg/sql/catalog/accessor.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4SCnn1kzIFh9kCIxe:-MB4SCnn1kzIFh9kCIxf:b-j1we20) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/sql/catalog/accessor.go#L31)):*
> ```Go
> 	GetDatabaseDesc(ctx context.Context, txn *kv.Txn, codec keys.SQLCodec, dbName string, flags tree.DatabaseLookupFlags) (sqlbase.DatabaseDescriptorInterface, error)
> 
> 	// GetSchema returns true and a ResolvedSchema object if the target schema
> ```

:raised_hands: 
___
*[pkg/sql/catalog/catalogkv/physical_accessor.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4SOLwBmr9bUK0lhxA:-MB4SOLx0rzPsBFaaqH3:b-avlbtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/sql/catalog/catalogkv/physical_accessor.go#L80)):*
> ```Go
> 	ctx context.Context, txn *kv.Txn, codec keys.SQLCodec, dbID sqlbase.ID, scName string,
> ) (bool, sqlbase.ResolvedSchema, error) {
> 	// Fast path public schema, as it is always found.
> ```

What's the plan here for allowing permissions on the public schema in a database?
___
*[pkg/util/hlc/timestamp.pb.go, line 0 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4TBPW3PIjyubmK4S-:-MB4TBPW3PIjyubmK4S0:b-j8digb) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/util/hlc/timestamp.pb.go#L0)):*
I don't think you intended to modify this or mvcc.pb.go

**Review by rohany — COMMENTED** [review]
> To what extent are you trying to get this merged ahead of leasing?

No rush, this is still a WIP. I don't imagine that this interacts too much with leasing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-:-MB4afRWBZTyzuyz-1p6:b-3bbuje)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @rohany)

___
*[pkg/sql/create_table.go, line 191 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4QxoH1q6FPH_anrQZ:-MB4ahsUB-1LZS3yM6mw:bk5bwg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/sql/create_table.go#L191)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: is this the right error code? 
</blockquote></details>

Good eye, updated to `pgcode.InsufficientPrivilege` (in line with pg)
___
*[pkg/sql/create_type.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4RJio1J38-5XxR3jx:-MB4bFm6DqxOUdj1hyR0:b-k5u0c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/sql/create_type.go#L80)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It feels like there could be a function to extract here as this seems almost identical to the code in `create_table.go`
</blockquote></details>

They are pretty similar, but slightly different. I'll see what can be pulled out.
___
*[pkg/sql/catalog/catalogkv/physical_accessor.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4SOLwBmr9bUK0lhxA:-MB4bMDz2XlHfjckodbb:bbl23v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/sql/catalog/catalogkv/physical_accessor.go#L80)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What's the plan here for allowing permissions on the public schema in a database?
</blockquote></details>

I was playing around with schema permissions in PG + looking at the PG source, and here's what I collected:
* In PG, the public schema by default has no permission restrictions -- anyone can do anything. For us, we treat the database's permissions as the public schemas permissions (which I think we need to keep doing to avoid breaking existing workloads).
* Creation of objects within schemas only looks at the schema's permissions.

I think the approach will be to not worry about permissions in the accessors, and let the callers check.

Because we only look at the permissions in this way, I think that we can use the same `optSchema` struct as before, and just resolve permissions like this:
* If the resolved schema actually has a descriptor, check permissions on that.
* Else, check permissions on the database descriptor.
___
*[pkg/util/hlc/timestamp.pb.go, line  at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4TBPW3PIjyubmK4S-:-MB4bmar9YYBfTpVfYg9:b-v125mi) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/util/hlc/timestamp.pb.go#L)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think you intended to modify this or mvcc.pb.go
</blockquote></details>

grr go1.14

**Comment by rohany** [comment]
@solongordon might want to take a look at this too -- there are a lot of your TODO's sitting around near these codepaths.

**Review by ajwerner — COMMENTED** [review]
This is looking good. I would like to be darn sure we understand the permission model before we merge this. 

> Reviewed 29 of 31 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-:-MBZlZGt0AZVK1NQbsW7:b-fbcros)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @rohany)

___
*[pkg/sql/create_table.go, line 154 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MBZhu8i1t1njQRRlifQ:-MBZhu8jCr7yvffiH4f8:b-4gyvpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/53969416dd5f8dd5baa89a26de3207f08de6e4b6/pkg/sql/create_table.go#L154)):*
> ```Go
> func (n *createTableNode) ReadingOwnWrites() {}
> 
> func (p *planner) getSchemaIDForCreate(
> ```

Is this what we want? At the very least this deserves some good commentary. The ways in which mutation operations completely bypass the lookup infrastructure continues to alarm me. Commentary is probably the best defense we have for now. 
___
*[pkg/sql/opt_catalog.go, line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MBZjKYNBZMjQbutup1X:-MBZjKYNBZMjQbutup1Y:b-7ger2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/53969416dd5f8dd5baa89a26de3207f08de6e4b6/pkg/sql/opt_catalog.go#L136)):*
> ```Go
> }
> 
> func (os *optSchema) getDescriptorForPermissionsCheck() sqlbase.DescriptorInterface {
> ```

:thinking: how does this work. Say you don't have permissions from the schema descriptor but you do from the database?

We can have the discussion on the other comment. 
___
*[pkg/sql/catalog/catalogkv/physical_accessor.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4SOLwBmr9bUK0lhxA:-MBZjlVcBusORrwi-erI:bbyyyhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/sql/catalog/catalogkv/physical_accessor.go#L80)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I was playing around with schema permissions in PG + looking at the PG source, and here's what I collected:
* In PG, the public schema by default has no permission restrictions -- anyone can do anything. For us, we treat the database's permissions as the public schemas permissions (which I think we need to keep doing to avoid breaking existing workloads).
* Creation of objects within schemas only looks at the schema's permissions.

I think the approach will be to not worry about permissions in the accessors, and let the callers check.

Because we only look at the permissions in this way, I think that we can use the same `optSchema` struct as before, and just resolve permissions like this:
* If the resolved schema actually has a descriptor, check permissions on that.
* Else, check permissions on the database descriptor.
</blockquote></details>

I'm perplexed here. This seems like a wild permissions model. In postgres when you create a schema, what permissions are on it?

**Comment by ajwerner** [comment]
I've been mucking around in postgres and this permission stuff is wild.

**Comment by rohany** [comment]
> I've been mucking around in postgres and this permission stuff is wild.

Yeah... I've been reading some articles but not making too much progress.

> 🤔 how does this work. Say you don't have permissions from the schema descriptor but you do from the database?

The cases where we don't have permissions from the schema descriptor are virtual schemas, the public schema, and temporary schemas. The virtual and public schema permission can be resolved by looking at the database. For temporary tables, we know whether we can access it or not based on our session ID.

> In postgres when you create a schema, what permissions are on it?

A look at the pg docs and code aren't revealing much. I'm just seeing that new schemas start out with an empty permissions set?

**Comment by rohany** [comment]
> Is this what we want? At the very least this deserves some good commentary. The ways in which mutation operations completely bypass the lookup infrastructure continues to alarm me. Commentary is probably the best defense we have for now.

Updated this to use the accessors -- not sure why I didn't do it initially.

**Comment by rohany** [comment]
@ajwerner have your investigations into permissions given us some idea on what to do with this PR?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50664)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @rohany)

___
*[pkg/sql/catalog/catalogkv/physical_accessor.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MB4SOLwBmr9bUK0lhxA:-MCOTAOZBWp7reyNDUuO:b-i4cmh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/af481a92bbd8810d09ad5cd2d1173ad186003149/pkg/sql/catalog/catalogkv/physical_accessor.go#L80)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm perplexed here. This seems like a wild permissions model. In postgres when you create a schema, what permissions are on it?
</blockquote></details>

Yeah this seems right. My current thinking is that we will want to initialize the privilege descriptor in the schema descriptor with that of the database for now. It's not what postgres does but we differ in a number of ways and it's the most consistent thing I think we could do today. Furthermore, we'll want to copy from schemas to tables when tables are created under a UDS. Will type it all up somewhere.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 20 of 22 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-:-MCqu-5P6kMfOWIGff9b:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @rohany)

___
*[pkg/sql/create_table.go, line 184 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MCqtIOf294FtZIKAT6e:-MCqtIOg02T8hv8sui0N:b-706ew4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e5693e241cb545a85377d0d65fc2963ea130879/pkg/sql/create_table.go#L184)):*
> ```Go
> func getTableCreateParams(
> 	params runParams, dbID sqlbase.ID, isTemporary bool, tableName *tree.TableName,
> ) (sqlbase.DescriptorKey, sqlbase.ID, error) {
> ```

super nit but how do you feel about naming the return params instead? I think it'll make the definition clearer

**Comment by rohany** [comment]
> super nit but how do you feel about naming the return params instead? I think it'll make the definition clearer

done

**Comment by rohany** [comment]
@RaduBerinde can you take a look at the opt changes here? I'm not sure if I did that adding a new type to the generated code correctly.

**Review by RaduBerinde — COMMENTED** [review]
opt part LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-:-MCxCzGEAkczQfb4DpLe:b-33fro1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @rohany)

___
*[pkg/sql/opt/optbuilder/create_view.go, line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50664#-MCxC4jAA1sT6fDeDqPW:-MCxC4jAA1sT6fDeDqPX:b-ao7kv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2471f97035fb29c74eca972184b7262e42677feb/pkg/sql/opt/optbuilder/create_view.go#L24)):*
> ```Go
> 	sch, resName := b.resolveSchemaForCreate(&cv.Name)
> 	schID := b.factory.Metadata().AddSchema(sch)
> 	cv.Name.ObjectNamePrefix = resName
> ```

Do we need to modify the AST here? We could just copy the name to a local var.

**Comment by rohany** [comment]
> Do we need to modify the AST here? We could just copy the name to a local var.

Done, made a local variable instead.

**Comment by rohany** [comment]
TFTRs!

bors r+

**Pull request merged**
