### PR TITLE
distsqlrun: avoid flow.Waiting if called after a panic

### LINKED ISSUE #39779: exec: calling defer f.Wait() could block indefinitely when panicking
We call `defer f.Wait` in `Flow.Run` when running a flow. If a materializer experiences a non-vectorized panic, it will panic itself without performing any cleanup (i.e. canceling the flow context to notify components they should exit). This defer will then get executed, causing us to wait indefinitely for components to exit. We should decide to either perform some kind of cleanup on a panic or never call `defer f.Wait` (which we might also then want to write a linter for). Another option would be to `recover()` in the `defer`.

### PR DESCRIPTION
**Pull request by asubiotto**
If a panic occurred in a flow, flow.Wait() would still be called since
it was deferred in Run. This would result in unnecessarily Waiting for
components that would never be signalled to exit through context
cancellation (since the panicking goroutine could be the one responsible
to do so).

Release note: None

Closes #39779

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40630)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/flow.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40630#-LoQvmci-j0VbcQPGUsG:-LoQvmcj52CZqMe0Yfv4:bp2xmcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae143ad309eb59d040730ef3aebd24f054e21024/pkg/sql/distsqlrun/flow.go#L593)):*
> ```Go
> 	if err := recover(); err != nil {
> 		// Skip any waiting and propagate panic if Wait is executed after a panic.
> 		// TODO(asubiotto): I wonder if we should just f.cancel() and wait anyway?
> ```

I think I like this idea of properly canceling the flow, waiting for all the goroutines to exit, and then propagating the error. Wouldn't we use `f.ctxCancel()` for the cancelation though?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40630)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsqlrun/flow.go, line 593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40630#-LoQvmci-j0VbcQPGUsG:-LoRHnwNAX0Q830XQkXX:b-73f53s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae143ad309eb59d040730ef3aebd24f054e21024/pkg/sql/distsqlrun/flow.go#L593)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think I like this idea of properly canceling the flow, waiting for all the goroutines to exit, and then propagating the error. Wouldn't we use `f.ctxCancel()` for the cancelation though?
</blockquote></details>

Yeah, same. Done.

**Review by yuzefovich — APPROVED** [review]
Thanks! :lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40630#-:-LoRL8gH-aZEFj5uGf76:b-ftzx47)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Pull request merged**
