### PR TITLE
sql: implement postgres format_type() function

### PR DESCRIPTION
**Pull request by jordanlewis**
`format_type(oid, typmod)` returns the SQL standard name of the type
corresponding to the input OID. Postgres uses the `typmod` field to
augment the name when types have modifiers, such as the length of a
VARCHAR field. We don't support such type modifiers at the moment, so
`typmod` is ignored.

For complete postgres compatibility, users must be able to pass NULL as
the `typmod` field. We don't yet support nullable function arguments, so
`format_type` will need to be updated once we do.

Updates #12151.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12967)

### CODE REVIEW

**Comment by cuongdo** [comment]
:lgtm: w/ one comment

---

Reviewed 1 of 1 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/testdata/builtin_function, line 1373 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967#-KamI5jQExR4Mg2uvEQL:-KamI5jQExR4Mg2uvEQM:b-ts1ye8) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fe6570d3c1c18a6805bf2093eaed802f442298/pkg/sql/testdata/builtin_function#L1373)):*
> ```
> 
> query T
> VALUES (format_type('anyelement'::regtype, 0)),
> ```

It looks like we always return `-1` for `pg_attribute.atttypmod`, which is the second parameter being passed in by the query in #12151. So, should the tests use `-1` for the second parameter as well?

Can you also test the query in #12151 directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967#-:-KamIbtHt_4eZ8Qd8g19:b-p76xf8)*

**Comment by jordanlewis** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/testdata/builtin_function, line 1373 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967#-KamI5jQExR4Mg2uvEQL:-KamIvRkQuwaTfbObHFB:bflfi8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/96fe6570d3c1c18a6805bf2093eaed802f442298/pkg/sql/testdata/builtin_function#L1373)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

It looks like we always return `-1` for `pg_attribute.atttypmod`, which is the second parameter being passed in by the query in #12151. So, should the tests use `-1` for the second parameter as well?

Can you also test the query in #12151 directly?
</blockquote></details>

Good points. For some reason I thought that #12151 passed NULL as the second argument, but as you point out it does indeed pass -1 so we can test it directly.

Done - I've added a new test file for ORM queries that we can use as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3.
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/builtins.go, line 1577 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967#-Kamdwr_hon5_V_eRCG7:-KamdwraNEhE8iwfCWqN:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/23365770b38d432044d7fa4bede4679acf5453ba/pkg/sql/parser/builtins.go#L1577)):*
> ```Go
> 			},
> 			category: categoryCompatibility,
> 			Info: "format_type returns the SQL name of a data type that is identified by its type OID and possibly a type" +
> ```

long line

---

*[pkg/sql/parser/type.go, line 41 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967#-Kamf07WQbUM9cDgy0kH:-Kamf07WQbUM9cDgy0kI:b-i9gvwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e361fd5ed8deb1afa98fd33fd88a2203f2d2f864/pkg/sql/parser/type.go#L41)):*
> ```Go
> 	// Oid returns the type's Postgres object ID.
> 	Oid() oid.Oid
> 	// SQLName returns the type's SQL standard name. This can be looked up for a
> ```

Should we be using this new method in `pg_catalog.pg_type` as well?

---

*[pkg/sql/testdata/orms, line 1 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967#-Kamelvt0FkytDvkb5p0:-Kamelvt0FkytDvkb5p1:b-qg8zad) ([raw file](https://github.com/cockroachdb/cockroach/blob/da8911e7b6f5d865ce0d5d0db77dd71fb0d755a4/pkg/sql/testdata/orms#L1)):*
> ```
> ## This test file contains various complex queries that ORMs issue during
> ```

Good idea :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967#-:-Kameq1gNWjtqHKt4bH6:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/builtins.go, line 1577 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967#-Kamdwr_hon5_V_eRCG7:-Kamn3TRZonwrCoZVdcx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/23365770b38d432044d7fa4bede4679acf5453ba/pkg/sql/parser/builtins.go#L1577)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.

---

*[pkg/sql/parser/type.go, line 41 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967#-Kamf07WQbUM9cDgy0kH:-KamnRt0vgaEAQrNSYYz:bmlsjhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e361fd5ed8deb1afa98fd33fd88a2203f2d2f864/pkg/sql/parser/type.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we be using this new method in `pg_catalog.pg_type` as well?
</blockquote></details>

I don't believe so - `pg_type.typname` contains postgres internal names for all types.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12967)*

**Comment by jordanlewis** [comment]
TFTRs!

**Pull request merged**
