### PR TITLE
auditloggingccl: migrate role-based audit logging as a CCL feature

### PR DESCRIPTION
**Pull request by THardy98**
Part of: https://github.com/cockroachdb/cockroach/issues/100467

This change moves the existing role-based audit logging logic to be
consumed as a CCL (enterprise) feature.

The notable changes here are:
- moving the audit logging cluster settings (i.e. `sql.log.user_audit`
  and `sql.log.user_audit.reduced_config.enabled`) to the `ccl` package.
Consequently, these cluster settings will only exist when the use has a
CCL license (free or paid)
- gating the `sql.log.user_audit` cluster setting behind the enterprise
  CCL license. This was done by adding an enterprise CCL license check
in the `sql.log.user_audit` validation function. Users will be unable to
change this cluster setting (and thereby will not be able to enable/configure
role-based audit logging) unless they have an enterprise CCL license
-  the addition of function hooks to be used at CCL initialization,
   namely:
   - `ConfigureRoleBasedAuditClusterSettings`: used to add a
     `SetOnChange` hook to `sql.log.user_audit`
   - `UserAuditLogConfigEmpty`: used to check whether the audit logging
     cluster setting is empty
   - `UserAuditReducedConfigEnabled`: used to check whether the reduced
     audit configuration is enabled (note: regular users are still able
to enable/disable this cluster setting, but it will take no effect as
they will have no way to enable role-based audit logging)
   - `UserAuditEnterpriseParamsHook`: used to retrieve parameters
     necessary for enterprise license checks within the the
`sql.log.user_audit` cluster setting validation function

Release note (sql change): Role-based audit logging is now a CCL
(enterprise) feature. Only enterprise CCL users will be able to
configure role-based audit logging using the `sql.log.user_audit`
cluster setting.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104383)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXDozw0DBB1jbVqlROV):*
make sure to fix the commit message
___
*[`pkg/sql/auditlogging/audit_log.go` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXDofZI583u5lHng_qP:-NXDofZI583u5lHng_qQ:bivxxws) ([raw file](https://github.com/cockroachdb/cockroach/blob/c921005eb2f702a6ea0d3c6576a16e51314269bd/pkg/sql/auditlogging/audit_log.go#L17)):*
> ```Go
> 	"fmt"
> 	"github.com/cockroachdb/cockroach/pkg/settings"
> 	"github.com/cockroachdb/cockroach/pkg/settings/cluster"
> ```

nit: location of these should be below
___
*[`pkg/ccl/auditloggingccl/audit_log_config.go` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXDoY5v4YjmLPTTHSTY:-NXDoY5v4YjmLPTTHSTZ:b-7diteo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c921005eb2f702a6ea0d3c6576a16e51314269bd/pkg/ccl/auditloggingccl/audit_log_config.go#L15)):*
> ```Go
> import (
> 	"context"
> 	"github.com/cockroachdb/cockroach/pkg/sql/auditlogging"
> ```

nit: the location of the import needs to be aligned with other imports

**Comment by THardy98** [comment]
Tagged @dhartunian based on our discussion this morning. I added the enterprise check such that one can change the cluster setting but it won't affect the underlying config if you do not have the paid enterprise license.

@HonoreDB mentioned that an enterprise check is indeed what's needed to gate the paid license.

**Review by maryliag — COMMENTED** [review]
> Reviewed 4 of 9 files at r2, 5 of 10 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104383)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, and @THardy98)

___
*[`pkg/ccl/auditloggingccl/audit_logging_test.go` line 9 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXL1Ksa68YGFrF5wqFL:-NXL1Ksa68YGFrF5wqFM:bdqlt0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ddaf8fe20a3d632f0510339b4530215183bd176/pkg/ccl/auditloggingccl/audit_logging_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package auditloggingccl
> ```

any test that can be added to confirm the license?

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104383)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @knz, and @maryliag)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXDozw0DBB1jbVqlROV):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

make sure to fix the commit message
</blockquote></details>

Done.
___
*[`pkg/sql/auditlogging/audit_log.go` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXDofZI583u5lHng_qP:-NXLEYp55SKdH5Zxia_a:behufu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c921005eb2f702a6ea0d3c6576a16e51314269bd/pkg/sql/auditlogging/audit_log.go#L17)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: location of these should be below
</blockquote></details>

As in the import order? If so, done.
___
*[`pkg/ccl/auditloggingccl/audit_log_config.go` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXDoY5v4YjmLPTTHSTY:-NXLEYAR9m6oQGYSz1EF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c921005eb2f702a6ea0d3c6576a16e51314269bd/pkg/ccl/auditloggingccl/audit_log_config.go#L15)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: the location of the import needs to be aligned with other imports
</blockquote></details>

Done.
___
*[`pkg/ccl/auditloggingccl/audit_logging_test.go` line 9 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXL1Ksa68YGFrF5wqFL:-NXLEdZ4AyteKzo6ewP2:b-fn12ml) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ddaf8fe20a3d632f0510339b4530215183bd176/pkg/ccl/auditloggingccl/audit_logging_test.go#L9)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

any test that can be added to confirm the license?
</blockquote></details>

Added `TestRoleBasedAuditEnterpriseGated`

**Review by dhartunian — APPROVED** [review]
code :lgtm: 

Just have some nits/questions which are non-blocking.

> Reviewed 1 of 6 files at r1, 2 of 9 files at r2, 4 of 10 files at r3, 4 of 8 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-:-NXMm7xCClMikr0eAuAl:bkgthms)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @maryliag, and @THardy98)

___
*[`pkg/ccl/auditloggingccl/audit_log_config.go` line 46 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXMhDecDSKGvWc0gLzH:-NXMhDecDSKGvWc0gLzI:b-cj6dho) ([raw file](https://github.com/cockroachdb/cockroach/blob/530e2ef6d3e974202b2015c22c7ea9eb1c20a29e/pkg/ccl/auditloggingccl/audit_log_config.go#L46)):*
> ```Go
> 		"Users will need to start a new session to see these changes in their auditing behaviour.",
> 	false,
> ).WithPublic()
> ```

is there a reason these are no longer public? I assume we do want them to be documented and available for CCL users to use.
___
*[`pkg/ccl/auditloggingccl/audit_log_config.go` line 57 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXMlxRa8EVHACjx08M1:-NXMlxRa8EVHACjx08M2:b-pxv6zd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b46781f94e2931287fab576c82bfb332b751d9d3/pkg/ccl/auditloggingccl/audit_log_config.go#L57)):*
> ```Go
> 		return nil
> 	}
> 	st, clusterID, err := auditlogging.UserAuditEnterpriseParamsHook()
> ```

nit: not blocking but maybe in a follow-up you can use the `*settings.Values` that's being ignored up above in the function args instead of the one from this call.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104383)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dhartunian, @knz, and @maryliag)

___
*[`pkg/ccl/auditloggingccl/audit_log_config.go` line 46 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104383#-NXMhDecDSKGvWc0gLzH:-NXPoAy16SKaQgHryGmg:b7lwcbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/530e2ef6d3e974202b2015c22c7ea9eb1c20a29e/pkg/ccl/auditloggingccl/audit_log_config.go#L46)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is there a reason these are no longer public? I assume we do want them to be documented and available for CCL users to use.
</blockquote></details>

No, forgot I had removed this during revisions. Added back.

**Comment by THardy98** [comment]
TYFR

**Pull request merged**
