### PR TITLE
roachtest: disentangle cluster creation

### PR DESCRIPTION
**Pull request by andreimatei**
... from attaching to an existing cluster.
Also removes testingSkipValidation and limits the use of some other
globals.

Release note: none

### CODE REVIEW

**Comment by andreimatei** [comment]
poking at the ankle of the beast. Let me know if you like it.

**Review by andreimatei — COMMENTED** [review]
I meant to ask - how does one use/test the roachtest run --cluster option? Is there an easy way to create a cluster that matches a particular test's expectation? Am I supposed to cause a test to fail and use the --debug option to leave a cluster around?
Also, is the roachtest invocation supposed to take ownership of such a cluster? Like, is it supposed to destroy it at the end?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-:-LO4IZcB-BQqVT9DBE3Y:b-2btcrt)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by petermattis — APPROVED** [review]
:lgtm:

Aren't you afraid that the beast is going to step on you?

I've looked at the source to find the correct shape for a cluster to use with `--cluster`. Certainly seems worthwhile to provide a better way to see that. Perhaps `run --list` (or `list`) should show the cluster config (machine spec).

> Also, is the roachtest invocation supposed to take ownership of such a cluster? Like, is it supposed to destroy it at the end?

No, it is not. If `--cluster` is specified `roachtest` should definitely not destroy the cluster.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-:-LO4LwAd-107xgOqGPse:bgh23ee)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cluster.go, line 688 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-LO4PX4w8siNMAJn8hvG:-LO4PX4w8siNMAJn8hvH:bwn3wzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b103c6460f77397e2e8aa5c8e394eeadd3ca9621/pkg/cmd/roachtest/cluster.go#L688)):*
> ```Go
> 
> 	// TODO(andrei): This doesn't seem like it belongs in this "validation"
> 	// function and that it should be subject to testingSkipValidation.
> ```

Agreed. We'd want to stop and wipe the cluster regardless of whether we validate the cluster machines.
___
*[pkg/cmd/roachtest/test.go, line 751 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-LO4PEHr2tQs2DNqJA_N:-LO4PEHr2tQs2DNqJA_O:b-t09qz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b103c6460f77397e2e8aa5c8e394eeadd3ca9621/pkg/cmd/roachtest/test.go#L751)):*
> ```Go
> 					} else {
> 						opt = remoteCluster
> 					}
> ```

You could simplify the above to `opt := clusterOpt(local)`. And then the local variable isn't too useful, so just pass `clusterOpt(local)` as the parameter to `newCluster`.

**Review by andreimatei — COMMENTED** [review]
> Aren't you afraid that the beast is going to step on you?

Terrified, actually.


> No, it is not. If --cluster is specified roachtest should definitely not destroy the cluster.

That's what I thought, but I hadn't seen how that was accomplished. But now I do - the global name variable is inspected deep in the guts of `cluster.destroy()`. Expect some more de-globalization :).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-:-LO4Y2lZDiefrEUTslPW:bxajghc)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cluster.go, line 688 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-LO4PX4w8siNMAJn8hvG:-LO4_Bpb82iBa7f0drXK:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b103c6460f77397e2e8aa5c8e394eeadd3ca9621/pkg/cmd/roachtest/cluster.go#L688)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Agreed. We'd want to stop and wipe the cluster regardless of whether we validate the cluster machines.
</blockquote></details>

done
___
*[pkg/cmd/roachtest/test.go, line 751 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-LO4PEHr2tQs2DNqJA_N:-LO4Z-xCATcGc0NMXClT:b-gnku3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b103c6460f77397e2e8aa5c8e394eeadd3ca9621/pkg/cmd/roachtest/test.go#L751)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You could simplify the above to `opt := clusterOpt(local)`. And then the local variable isn't too useful, so just pass `clusterOpt(local)` as the parameter to `newCluster`.
</blockquote></details>

I like to treat the assignment of true/false values to these binary flags as arbitrary; I wouldn't rely on `localCluster` to be `true`.
But I've cut a few lines but treating one of the cases as default.

**Review by petermattis — APPROVED** [review]
> Terrified, actually.

You can't make an omelet without breaking a few eggs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-:-LO4cyta76WvspLJZYOP:bhp9qb3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by andreimatei — COMMENTED** [review]
I learned the hard way that cluster validation and wiping were tangled for the benefit of a rando test. Untangled further. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-:-LOJLf6r2-qh7talB8Wl:b2zvoo3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31016)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/test.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-LOJdUKf8g-rLjvtAYn_:-LOJdUKf8g-rLjvtAYna:bci1xlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/16bfe9f5446deaab3cb80d3200c86312562c9335/pkg/cmd/roachtest/test.go#L122)):*
> ```Go
> 		// the registry uses for running tests.
> 		skipClusterValidationOnAttach bool
> 		// skipClusterStoponAttach skips stopping existing clusters that
> ```

`s/Stopon/StopOn/g`

**Review by andreimatei — COMMENTED** [review]
bors r+

TFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-:-LOJh_De84982LbDma0m:b2jgkuu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/test.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31016#-LOJdUKf8g-rLjvtAYn_:-LOJgcL68KR_-r48xfLV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/16bfe9f5446deaab3cb80d3200c86312562c9335/pkg/cmd/roachtest/test.go#L122)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/Stopon/StopOn/g`
</blockquote></details>

Done.

**Pull request merged**
