### PR TITLE
colexec: rename vectorize setting 192auto to auto and make it the default

### PR DESCRIPTION
**Pull request by asubiotto**
This PR will be backported to 20.1. A followup PR will make "on" the default for master. Check the commits for more details.

This PR also disables processor wrapping for all processors when `vectorize=auto` apart from the JoinReader, since this is in line with 19.2 behavior.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 30 of 30 files at r1, 20 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46845#-:-M3qCN-y7-tpC-fuCOKm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/sessiondata/session_data.go, line 270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46845#-M3qA_cR8I5xv3ZvpBQN:-M3qA_cR8I5xv3ZvpBQO:b-dx463c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0626f18cad05ea2b8658264a66d7231224b7df/pkg/sql/sessiondata/session_data.go#L270)):*
> ```Go
> 	// streaming operators (i.e. those that do not require any buffering) will
> 	// be run using the columnar execution. If any part of a query is not
> 	// supported by the vectorized execution engine, the whole query will fall
> ```

nit: this comment is slightly misleading since we're wrapping index and lookup joins, but I'm not sure whether it's worth calling out. Probably not. Never mind.

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Comment by asubiotto** [comment]
The failure seems like a hard to hit float precision issue that we've run into before: https://github.com/cockroachdb/cockroach/pull/37600/files. We should probably take care of that in a separate PR.

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Pull request merged**
