### PR TITLE
changefeedccl: Cleanup and refactor sink construction.

### PR DESCRIPTION
**Pull request by miretskiy**
Cleanup sink construction factory method to take fewer arguments.
Refactor and move non-trivial sinks (kafka and sql) into standalone
files.

Release Notes: none

### CODE REVIEW

**Review by stevendanna — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63964)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYnTznwDefSm72BqmUZ:-MYnTznwDefSm72BqmU_:b-px006q) (no related file):*
Overall, I like this cleanup and think it will encourage future cleanups as well.

I've left some inline comments but many are nits on the pre-existing code that we can defer until later if you'd like. 

There are a couple of issues blocking the tests passing:

- Looks like you'll need `make bazel-generate` since you've added some new files
- We've changed some error messages related to unknown query parameters. Those changes need to be reflected in the tests

I think the `sinkDialer` interface could use some more thought, but am OK with merging it as is. Namely, it seems mildly odd that the kafka and the cloud sinks _don't_ have a Dial function while they certainly also have connections to initialize under the hood. Perhaps Dial should be part of the Sink interface with no-op implementations for sinks that don't need it.

---
___
*[pkg/ccl/changefeedccl/sink.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYnpKa0B6HjhrCxoB1d:-MYnpKa0B6HjhrCxoB1e:bhxqiv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/af96138fe979d69469ef4574ac3419e081902d6c/pkg/ccl/changefeedccl/sink.go#L93)):*
> ```Go
> 			)
> 		case u.Scheme == changefeedbase.SinkSchemeExperimentalSQL:
> 			return makeSQLSink(u, sqlSinkTableName, feedCfg.Targets)
> ```

Interesting that this sink doesn't take a context. 
___
*[pkg/ccl/changefeedccl/sink_kafka.go, line 473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYnfCqO39gKcgrGc7Th:-MYnfCqO39gKcgrGc7Ti:bik7qu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/af96138fe979d69469ef4574ac3419e081902d6c/pkg/ccl/changefeedccl/sink_kafka.go#L473)):*
> ```Go
> 		b, err := strconv.ParseBool(saslParam)
> 		if err != nil {
> 			return nil, errors.Wrapf(err, `param %s must be a bool:`, changefeedbase.SinkParamSASLEnabled)
> ```

existing problem: the `:` in the string here isn't required as Wrapf already adds that
___
*[pkg/ccl/changefeedccl/sink_kafka.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYne2hcC39iEZLvC22o:-MYne2hcC39iEZLvC22p:bgcc5cv) ([raw file](https://github.com/cockroachdb/cockroach/blob/af96138fe979d69469ef4574ac3419e081902d6c/pkg/ccl/changefeedccl/sink_kafka.go#L476)):*
> ```Go
> 		}
> 		dialConfig.saslEnabled = b
> 	}
> ```

nit: we could make this consistent with the style above:

```go
if saslParam := u.consumeParam(changefeedbase.SinkParamSASLEnabled); saslParam != `` {
	var err error
        if dialConfig.saslEnabled, err = strconv.ParseBool(saslParam); err != nil {
		return nil, errors.Wrapf(err, `param %s must be a bool`, changefeedbase.SinkParamSASLEnabled)
 	}
}
```

I wonder what you would think of a helper function that would maybe make this and the two cases above. Perhaps something like

```
func consumeBoolParam(u *sinkURL, param string, dest *bool) error {
	if paramVal := u.consumeParam(param); paramVal != "" {
		b, err := strconv.ParseBool(paramVal)
		if err != nil {
			return errors.Wrapf(err, "param %s must be a bool", param)
		}
		*dest = b
	}
	return nil
}
```

(or as a method on sinkURL itself)
___
*[pkg/ccl/changefeedccl/sink_kafka.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYnd9UN5lPC3jR0Eiru:-MYnd9UN5lPC3jR0Eirv:b3rk99v) ([raw file](https://github.com/cockroachdb/cockroach/blob/af96138fe979d69469ef4574ac3419e081902d6c/pkg/ccl/changefeedccl/sink_kafka.go#L566)):*
> ```Go
> 	} else if dialConfig.clientKey != nil {
> 		return nil, errors.Errorf(`%s requires %s to be set`, changefeedbase.SinkParamClientKey, changefeedbase.SinkParamClientCert)
> 	}
> ```

This isn't a thing you introduced, but something like

```go
	if dialConfig.tlsEnabled {
		config.Net.TLS.Enable = true
		config.Net.TLS.Config = &tls.Config{
			InsecureSkipVerify: dialConfig.tlsSkipVerify,
		}

		if dialConfig.caCert != nil {
			caCertPool := x509.NewCertPool()
			caCertPool.AppendCertsFromPEM(dialConfig.caCert)
			config.Net.TLS.Config.RootCAs = caCertPool
		}

		if dialConfig.clientCert != nil && dialConfig.clientKey == nil {
			return nil, errors.Errorf(`%s requires %s to be set`, changefeedbase.SinkParamClientCert, changefeedbase.SinkParamClientKey)
		} else if dialConfig.clientKey != nil && dialConfig.clientCert == nil {
			return nil, errors.Errorf(`%s requires %s to be set`, changefeedbase.SinkParamClientKey, changefeedbase.SinkParamClientCert)
		}

		if dialConfig.clientCert != nil && dialConfig.clientKey != nil {
			cert, err := tls.X509KeyPair(dialConfig.clientCert, dialConfig.clientKey)
			if err != nil {
				return nil, errors.Errorf(`invalid client certificate data provided: %s`, err)
			}
			config.Net.TLS.Config.Certificates = []tls.Certificate{cert}
		}
	} else {
		if dialConfig.caCert != nil {
			return nil, errors.Errorf(`%s requires %s=true`, changefeedbase.SinkParamCACert, changefeedbase.SinkParamTLSEnabled)
		}
		if dialConfig.clientCert != nil {
			return nil, errors.Errorf(`%s requires %s=true`, changefeedbase.SinkParamClientCert, changefeedbase.SinkParamTLSEnabled)
		}
	}
```

while a little longer reads a bit better to me than the current layout. WDYT?
___
*[pkg/ccl/changefeedccl/sink_sql.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYnmLUe2Z_oNaEQHI14:-MYnmLUe2Z_oNaEQHI15:b-b46rxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/af96138fe979d69469ef4574ac3419e081902d6c/pkg/ccl/changefeedccl/sink_sql.go#L82)):*
> ```Go
> 	u.consumeParam(`sslkey`)
> 	u.consumeParam(`sslmode`)
> 	u.consumeParam(`sslrootcert`)
> ```

Are these consumeParam's happening too early?  In the old code we consumed these after calling `u.String()` because we assume that the pg client library will deal with them if they are there.  Here we are consuming them before we call u.String() which seems to mean we won't be able to connect to sql sinks that require those ssl options.

If this is correct, a comment explaining why might be good.

**Comment by stevendanna** [comment]
If we have the time today, let's err on the side of getting this in quickly since it'll be conflict-city if we wait a while.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63964)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYnTznwDefSm72BqmUZ:-MYo2ChV8h7fa6Qj_9Nd:bkv8d0s) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Overall, I like this cleanup and think it will encourage future cleanups as well.

I've left some inline comments but many are nits on the pre-existing code that we can defer until later if you'd like. 

There are a couple of issues blocking the tests passing:

- Looks like you'll need `make bazel-generate` since you've added some new files
- We've changed some error messages related to unknown query parameters. Those changes need to be reflected in the tests

I think the `sinkDialer` interface could use some more thought, but am OK with merging it as is. Namely, it seems mildly odd that the kafka and the cloud sinks _don't_ have a Dial function while they certainly also have connections to initialize under the hood. Perhaps Dial should be part of the Sink interface with no-op implementations for sinks that don't need it.
</blockquote></details>

Ack.  Re sinkDialier -- i was going back and forth on that -- because some sinks do have "dial" and others don't (btw, you're right -- I forgot to add dial to kafka). initially, I wanted to avoid touching too much code -- but, ultimately, I touched most of the sink releated code anyway... So, just going to add Dial.

---
___
*[pkg/ccl/changefeedccl/sink.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYnpKa0B6HjhrCxoB1d:-MYo6bNx0I13F26UmNA7:b-sdoswb) ([raw file](https://github.com/cockroachdb/cockroach/blob/af96138fe979d69469ef4574ac3419e081902d6c/pkg/ccl/changefeedccl/sink.go#L93)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Interesting that this sink doesn't take a context. 
</blockquote></details>

Yeah -- consistency wasn't much of a forte here.
___
*[pkg/ccl/changefeedccl/sink_kafka.go, line 473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYnfCqO39gKcgrGc7Th:-MYo6gSYAzSQotwrpL0f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af96138fe979d69469ef4574ac3419e081902d6c/pkg/ccl/changefeedccl/sink_kafka.go#L473)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

existing problem: the `:` in the string here isn't required as Wrapf already adds that
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_kafka.go, line 476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYne2hcC39iEZLvC22o:-MYo6lkZ2FvytVJAurWa:bvjvpaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/af96138fe979d69469ef4574ac3419e081902d6c/pkg/ccl/changefeedccl/sink_kafka.go#L476)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

nit: we could make this consistent with the style above:

```go
if saslParam := u.consumeParam(changefeedbase.SinkParamSASLEnabled); saslParam != `` {
	var err error
        if dialConfig.saslEnabled, err = strconv.ParseBool(saslParam); err != nil {
		return nil, errors.Wrapf(err, `param %s must be a bool`, changefeedbase.SinkParamSASLEnabled)
 	}
}
```

I wonder what you would think of a helper function that would maybe make this and the two cases above. Perhaps something like

```
func consumeBoolParam(u *sinkURL, param string, dest *bool) error {
	if paramVal := u.consumeParam(param); paramVal != "" {
		b, err := strconv.ParseBool(paramVal)
		if err != nil {
			return errors.Wrapf(err, "param %s must be a bool", param)
		}
		*dest = b
	}
	return nil
}
```

(or as a method on sinkURL itself)
</blockquote></details>

Yup -- I didn't realize we have multiple bools.. Too much copy/pasting.  Done.
___
*[pkg/ccl/changefeedccl/sink_kafka.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYnd9UN5lPC3jR0Eiru:-MYoHf9B-wntXimCNOEu:b8pds3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/af96138fe979d69469ef4574ac3419e081902d6c/pkg/ccl/changefeedccl/sink_kafka.go#L566)):*
> config.Net.TLS.Enable = true
> 		config.Net.TLS.Config = &tls.Config{
> 			InsecureSkipVerify: dialConfig.tlsSkipVerify,
> 		}
> 
> 		if dialConfig.caCert != nil {
> 			caCertPool := x509.NewCertPool()
> 			caCertPool.AppendCertsFromPEM(dialConfig.caCert)
> 			config.Net.TLS.Config.RootCAs = caCertPool
> 		}
> 
> 		if dialConfig.clientCert != nil && dialConfig.clientKey == nil {
> 			return nil, errors.Errorf(`%s requires %s to be set`, changefeedbase.SinkParamClientCert, changefeedbase.SinkParamClientKey)
> 		} else if dialConfig.clientKey != nil && dialConfig.clientCert == nil {
> 			return nil, errors.Errorf(`%s requires %s to be set`, changefeedbase.SinkParamClientKey, changefeedbase.SinkParamClientCert)
> 		}
> 
> 		if dialConfig.clientCert != nil && dialConfig.clientKey != nil {
> 			cert, err := tls.X509KeyPair(dialConfig.clientCert, dialConfig.clientKey)
> 			if err != nil {
> 				return nil, errors.Errorf(`invalid client certificate data provided: %s`, err)
> 			}
> 			config.Net.TLS.Config.Certificates = []tls.Certificate{cert}
> 	}
I like it
___
*[pkg/ccl/changefeedccl/sink_sql.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYnmLUe2Z_oNaEQHI14:-MYoHnkM-L43kiMNrmFX:b9dxscn) ([raw file](https://github.com/cockroachdb/cockroach/blob/af96138fe979d69469ef4574ac3419e081902d6c/pkg/ccl/changefeedccl/sink_sql.go#L82)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Are these consumeParam's happening too early?  In the old code we consumed these after calling `u.String()` because we assume that the pg client library will deal with them if they are there.  Here we are consuming them before we call u.String() which seems to mean we won't be able to connect to sql sinks that require those ssl options.

If this is correct, a comment explaining why might be good.
</blockquote></details>

sigh... You're right.  In general, i'm almost inclined to drop this consume and check ... but on the other hand, I guess, the desire was to check for invalid url params... 
This stuff is very error prone.  And entirely inconsistent with other sinks (null?)

**Review by stevendanna — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63964)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/63964#-MYpA5Op65-tRXv1TmFT:-MYpA5Op65-tRXv1TmFU:bg7igkv) (no related file):*
:lgtm: 

---

**Comment by miretskiy** [comment]
tftr
bors r=stevendanna

**Pull request merged**
