### PR TITLE
build,ui: update dependencies

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8374)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: 

We might want to get out of the habit of upgrading all of the dependencies when we're trying to pick up a fix for just one. 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8374#-:-KOecbWrgqA-MYrmXSB6:bv79kui)*

**Comment by tamird** [comment]
Picking up two fixes here, though.

**Comment by petermattis** [comment]
> Picking up two fixes here, though.

My point still stands. I think it would be better to separate regular dependency upgrades from ones which are being forced due to picking up upstream fixes.

**Comment by tamird** [comment]
Previous build flaked on github in circle. God merging.

**Pull request merged**
