### PR TITLE
kvserver: allow enabling rac pull mode with a send queue 

### LINKED ISSUE #132115: kvflowcontrol: enable rac2 pull mode when kvflowcontrol mode is apply_to_all
There are two places where RACv2 pull mode (send queue) is currently disabled, even if the settings[^1] that enable pull mode are set:

(1) https://github.com/cockroachdb/cockroach/blob/fba8c117122b256371279883168093ad1c379020/pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go#L158-L166

(2) https://github.com/cockroachdb/cockroach/blob/0ce38176c1c290f5d3208ad53434d4eece088230/pkg/kv/kvserver/replica_proposal_quota.go#L118-L125

Once there is sufficient testing [#128040](https://github.com/cockroachdb/cockroach/issues/128040), allow these settings to actually enable RACv2 pull-mode with a send queue by removing the hardcoded  code currently preventing enablement.

[^1]: The default settings are `kvadmission.flow_control.enabled = true` `kvadmission.flow_control.mode = "apply_to_elastic"`. `kvadmission.flow_control.mode = "apply_to_all"` is required to enable RACv2 pull mode with a send queue. By default RACv2 is enabled (upon finalizing upgrade and passing V2 with V2 encoding version gate) in push mode (24.3) because `apply_to_elastic` maps to push mode. 

Jira issue: CRDB-42839

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by kvoli**
1-4 commits from https://github.com/cockroachdb/cockroach/pull/132344

---

By default,`kvadmission.flow_control.mode = "apply_to_elastic"`
replication admission control operates in push mode, where Raft has its
own flow control machinery in operation and controls sending messages to
replicas.

In pull mode, which could not be enabled prior to this commit (outside
of tests), replication flow control (v2) maintains its own machinery
(send queue) and controls when to send a message to a replica.

Previously, when `kvadmission.flow_control.mode = "apply_to_all"`,
replication admission control would remain in push mode.

Allow replication flow control to run in pull mode outside of tests, by
setting both:

```
kvadmission.flow_control.enabled = true (default true)
kvadmission.flow_control.mode = "apply_to_all" (default "apply_to_elastic")
```

And running a cluster which has finalized its upgrade to `v24.3`.

We omit a release note, as this functionality is disabled by default and
we wish to retain the ability to selectively suggest enabling pull mode
to users, as the feature is (1) newly introduced, (2) on the critical
path for all replication and (3) subject to change.

Part of: #128040
Resolves: #132115
Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132125#-:-O8whmM7E0nhwsL7FSJC:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 98 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132125#-O8wgmJ68sYKCZssJxbB):*
nit: deterministically

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132125)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`-- commits` line 98 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132125#-O8wgmJ68sYKCZssJxbB):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: deterministically
</blockquote></details>

Fixed.

**Comment by kvoli** [comment]
I'm going to merge this now. The `TestFlowControl.*` tests are now disabled under duress, tracked in:

- #132310
- #132272

The failures for the v2 tests are most likely fixed by #132499, while the v1 failures tracked by #132272 are due to resource exhaustion causing timeouts. Something that was likely recently introduced, but not in this PR.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Pull request merged**
