### PR TITLE
sql/opt: Refactor and add regnamespace to foldOIDFamilyCast

### PR DESCRIPTION
**Pull request by e-mbrown**
Part of: #91022

**sql/opt: Refactor foldOIDFamilyCast to use PerformCast**
This commit simplifies the switch used to handle each cast
to the OID family.

Release note: None

**sql/opt: Add regnamespace to foldOIDFamilyCast**
Adds regnamespace to foldOIDFamilyCast. Due to there being
no index on pg_namespace at this time, this change is a
no-op.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93221)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93221#-NItDUtn3h9ahP_gJ2K-):*
This commit seems to have gotten a bit mixed up with the first since some code that was removed in the previous commit was added back here. Can you please clean up these commits so they correspond to the commit message?
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 369 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93221#-NItDucuEIa3oXtTsluB:-NItDucuEIa3oXtTsluC:b-4s9e42) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f53330344f8d4f80b0350f902e399177409fd00/pkg/sql/opt/norm/fold_constants_funcs.go#L369)):*
> ```Go
> 			return nil, false, nil
> 		}
> 	case oid.T_regtype, oid.T_regnamespace:
> ```

Since this case is doing the same thing as the first one, is it possible to combine them into one case? If not, can you please add a comment to explain?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93221)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rytaft)

___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 369 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93221#-NItDucuEIa3oXtTsluB:-NJBPCmaArB1AnKX2yms:bimg57a) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f53330344f8d4f80b0350f902e399177409fd00/pkg/sql/opt/norm/fold_constants_funcs.go#L369)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Since this case is doing the same thing as the first one, is it possible to combine them into one case? If not, can you please add a comment to explain?
</blockquote></details>

i agree, let's combine the cases
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 416 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93221#-NJBPHKB-WBVcxlnzbue:-NJBPHKB-WBVcxlnzbuf:b-e5ehp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/40962888583d5eaca008cc8367ae2c2935182ad0/pkg/sql/opt/norm/fold_constants_funcs.go#L416)):*
> ```Go
> 	case oid.T_regproc, oid.T_regprocedure:
> 		switch inputFamily {
> 		case types.StringFamily, types.OidFamily, types.IntFamily:
> ```

why were OidFamily and IntFamily removed?

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93221)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rytaft)

___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93221#-NItDUtn3h9ahP_gJ2K-):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This commit seems to have gotten a bit mixed up with the first since some code that was removed in the previous commit was added back here. Can you please clean up these commits so they correspond to the commit message?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 369 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93221#-NItDucuEIa3oXtTsluB:-NJGV0NB5ITZ0hM1q1o2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f53330344f8d4f80b0350f902e399177409fd00/pkg/sql/opt/norm/fold_constants_funcs.go#L369)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i agree, let's combine the cases
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 416 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93221#-NJBPHKB-WBVcxlnzbue:-NJGQQ9e1MYJmTMu0M_O:b-sxxh3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/40962888583d5eaca008cc8367ae2c2935182ad0/pkg/sql/opt/norm/fold_constants_funcs.go#L416)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why were OidFamily and IntFamily removed?
</blockquote></details>

Those cases were for `regproc` and `regprocedure`, I dont think the original pr had a case for oidFamily and IntFamily under `regtype`. I'll group `regtype` with `oid` and test.

**Review by rytaft — APPROVED** [review]
:lgtm: once @rafiss signs off

> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93221#-:-NJGZ_b-ECVpU9Yy0-SW:bna7jqf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]
lgtm after fixing the test

TestLogic_record is failing
```
.../logic_test/record:98: SELECT pg_typeof(ARRAY[(1, 3)::a, (1, 2)::a])::regtype::oid::regtype
        expected:
            _record
        but found (query options: "") :
            a[]
```
this seems fine. it's what postgres returns too.

TestTenantLogic_new_schema_changer/add_multiple_columns_in_transaction looks flaky. i don't think it's caused by your change.

**Comment by e-mbrown** [comment]
Thanks!

bors r+

**Pull request merged**
