### PR TITLE
tracing: add LogStructured API

### PR DESCRIPTION
**Pull request by tbg**
This allows attaching arbitrary protobuf payloads to Spans, even when
background tracing. SpanStats, a SQL concept, are also tracked via this
newly introduced `LogStructured` call, though due to cross-version
compat we also still populate the old field.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
:microscope: :dog: 
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58180#-:-MPAtKVlB0pOoYXJfWtC:byi7kal)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/util/tracing/span.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58180#-MPAt0Eo6Guxof-oq1HA:-MPAt0Ep67zzvfOHJU4O:blz5vdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b662a2d2214ae070108738dbf9f361633640fb29/pkg/util/tracing/span.go#L85)):*
> ```Go
> // `trace.mode = background`.
> type Structured interface {
> 	proto.Message
> ```

maybe protoutil.Message here.

**Comment by tbg** [comment]
bors r=knz

**Comment by tbg** [comment]
bors r=knz

> maybe protoutil.Message here.

Done, TFTR!

**Comment by irfansharif** [comment]
Asking here because slack is down. I'm not sure I fully understand how this `Any` type is meant to be used. Are we expecting the component that actually renders traces for end-user consumption to type switch on all possible structured event types? Or will it suffice for them to opaquely call a `.String()` (or equivalent) on the individual payloads.

**Comment by tbg** [comment]
You iterate through all of them and pick the ones you like, like here:

https://github.com/cockroachdb/cockroach/blob/e12153cbe82035fbfbdfe45121a8973e95fafd5c/pkg/sql/execinfrapb/component_stats.go#L348-L359

The main new payload we'll be adding is contention metadata (https://github.com/cockroachdb/cockroach/issues/55583), see https://github.com/cockroachdb/cockroach/pull/57736 for the SQL side of this work.

**Pull request merged**
