### PR TITLE
cli,ts: add tsdump command

### PR DESCRIPTION
**Pull request by mrtracy**
Added a `debug tsdump` command which allows dumping all of the raw
timeseries data from a cluster. This is being used for some
experimentation into whether we can dump all of the timeseries data from
a baseline run of a test and then compare that against a new run to look
for anomalies or unexpected behavior.

Release note: None

Co-authored-by: Matt Tracy <matt@cockroachlabs.com>

### CODE REVIEW

**Review by petermattis — CHANGES_REQUESTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27869#-:-LIBcLG1AWmZwGaYuZcn:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ts/tspb/timeseries.proto, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27869#-LIBc4vZ6ifrmfp2sYwp:-LIBc4vZ6ifrmfp2sYwq:bka75ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7cb9e3151d693618fe5e30de4e1c1a7ef3b2e2f/pkg/ts/tspb/timeseries.proto#L157)):*
> ```protobuf
>   // server. Only data from the 10-second resolution is returned - rollup data is
>   // not returned. Data is returned in the order it is read from disk, and will
>   // not be totally organized by series.
> ```

`totally organized` is difficult for me to reason about. Perhaps `data from different series will be interleaved` or something like that.

**Review by mrtracy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27869)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ts/tspb/timeseries.proto, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27869#-LIBc4vZ6ifrmfp2sYwp:-LIK0kVQAr1dI29tiqfg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7cb9e3151d693618fe5e30de4e1c1a7ef3b2e2f/pkg/ts/tspb/timeseries.proto#L157)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`totally organized` is difficult for me to reason about. Perhaps `data from different series will be interleaved` or something like that.
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27869#-:-LIagDBd0dyJFJO2sgvQ:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
