### PR TITLE
util/log/logtags: move to separate repo

### PR DESCRIPTION
**Pull request by knz**
I found use of this package in `github.com/cockroachdb/errors`
and another pet project. It is good to keep it apache-licensed.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Shouldn't we remove `pkg/util/log/logtags` ?

**Comment by knz** [comment]
> Shouldn't we remove pkg/util/log/logtags ?

Yeah the linter had the same opinion. Done.

**Review by RaduBerinde — APPROVED** [review]

**Comment by knz** [comment]
thanks!

bors r+

**Comment by andreimatei** [comment]
Moving this to a separate repo seems dubious to me. It's a very specific piece of code that only makes sense with our logging library. Does the world really want this? I really doubt it. I think there should be a higher bar for moving things out of our repo, since it introduces a bunch of friction.
For the use of the errors library, I'd say that we'd want to cut that library's dependency on this code - since that too is something that only cockroach would want. I think it'd probably be a better idea to add a hook to the error library for extracting some strings from the context and have crdb tie that to the logtags code.

**Comment by knz** [comment]
> For the use of the errors library, I'd say that we'd want to cut that library's dependency on this code - since that too is something that only cockroach would want.

I have counter-evidence already. I have built a tool which productively uses this functionality already.

**Pull request merged**
