### PR TITLE
storage/engine: fix reading from a distinct write-only batch

### LINKED ISSUE #13402: stability: segfault at startup
`cyan` was just restarted, going from 5f693cd to 6581990 (single change).

Within seconds, two nodes segfaulted with:
```
I170203 22:00:54.317491 2036 storage/raft_transport.go:437  [n5] raft transport stream to node 6 established
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13ce992]

runtime stack:
runtime.throw(0x1a94eef, 0x2a)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 148 [syscall, locked to thread]:
runtime.cgocall(0x13634e0, 0xc422760130, 0x0)
        /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc4227600d0 sp=0xc422760090
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBIterSeek(0x0, 0xc4209ca720, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        ??:0 +0x73 fp=0xc422760130 sp=0xc4227600d0
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).Seek(0xc422a65980, 0xc4209ca720, 0x12, 0x20, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1205 +0x39f fp=0xc4227603d8 sp=0xc422760130
github.com/cockroachdb/cockroach/pkg/storage/engine.mvccGetMetadata(0x2672ca0, 0xc422a65980, 0xc4209ca720, 0x12, 0x20, 0x0, 0x0, 0xc422c7ad80, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:624 +0x87 fp=0xc422760520 sp=0xc4227603d8
github.com/cockroachdb/cockroach/pkg/storage/engine.mvccPutInternal(0x7f1fc92dd840, 0xc422a9ff50, 0x7f1fc932e8e0, 0xc422a65978, 0x2672ca0, 0xc422a65980, 0xc422760cc0, 0xc4209ca720, 0x12, 0x20, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:999 +0x271 fp=0xc422760a48 sp=0xc422760520
github.com/cockroachdb/cockroach/pkg/storage/engine.mvccPutUsingIter(0x7f1fc92dd840, 0xc422a9ff50, 0x7f1fc932e8e0, 0xc422a65978, 0x2672ca0, 0xc422a65980, 0xc422760cc0, 0xc4209ca720, 0x12, 0x20, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:968 +0x15a fp=0xc422760b28 sp=0xc422760a48
github.com/cockroachdb/cockroach/pkg/storage/engine.MVCCPut(0x7f1fc92dd840, 0xc422a9ff50, 0x2671ae0, 0xc422a65978, 0xc422760cc0, 0xc4209ca720, 0x12, 0x20, 0x0, 0xc400000000, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/mvcc.go:903 +0x181 fp=0xc422760c00 sp=0xc422760b28
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).append(0xc420d20c00, 0x7f1fc92dd840, 0xc422a9ff50, 0x2671ae0, 0xc422a65978, 0x8b38f, 0x0, 0xc422a93220, 0x1, 0x1, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raftstorage.go:456 +0x607 fp=0xc422760d78 sp=0xc422760c00
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc420d20c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2694 +0x1071 fp=0xc422761690 sp=0xc422760d78
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc420a1c380, 0x7f1fc92dd840, 0xc422a9fbf0, 0xc422350b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3080 +0xc63 fp=0xc422761db8 sp=0xc422761690
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc420a1c380, 0x134)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3313 +0x17d fp=0xc422761ec0 sp=0xc422761db8
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42029e210, 0xc420463830)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:240 +0x267 fp=0xc422761f28 sp=0xc422761ec0
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:180 +0x33 fp=0xc422761f48 sp=0xc422761f28
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420463830, 0xc4211074e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d fp=0xc422761f70 sp=0xc422761f48
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc422761f78 sp=0xc422761f70
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
```

@petermattis:
The call site in `storage/replica.go:2694` uses the newly-introduced NewWriteOnlyBatch
```
	// Use a more efficient write-only batch because we don't need to do any
	// reads from the batch. Any reads are performed via the "distinct" batch
	// which passes the reads through to the underlying DB.
	batch := r.store.Engine().NewWriteOnlyBatch()
	defer batch.Close()

	// We know that all of the writes from here forward will be to distinct keys.
	writer := batch.Distinct()
	if len(rd.Entries) > 0 {
		// All of the entries are appended to distinct keys, returning a new
		// last index.
		var err error
L2694:	if lastIndex, raftLogSize, err = r.append(ctx, writer, lastIndex, raftLogSize, rd.Entries); err != nil {
			return stats, err
		}
	}
```

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #13402

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13403)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: but I'd be ok with a little more detail in the commit message.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/engine/batch_test.go, line 883 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13403#-Kc5HMuTy_6yLCYrwlTU:-Kc5HMuTy_6yLCYrwlTV:b-s1wq3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/de01ca6487f94ef1efefd5d39539f34c3148929e/pkg/storage/engine/batch_test.go#L883)):*
> ```Go
> 		t.Fatal(err)
> 	} else if string(v) != "b" {
> 		t.Fatalf("expected b, but got %s", v)
> ```

probably want `%v` in case it's nil

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13403#-:-Kc5HQRpLv_ldyEju3Be:b-j52bti)*

**Comment by mberhault** [comment]
LGTM. Though I'm obviously not familiar with this code at all.

**Comment by petermattis** [comment]
Expanded the commit message.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/engine/batch_test.go, line 883 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13403#-Kc5HMuTy_6yLCYrwlTU:-Kc5ITbwCvkscXxGBMXT:bfxcdy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/de01ca6487f94ef1efefd5d39539f34c3148929e/pkg/storage/engine/batch_test.go#L883)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

probably want `%v` in case it's nil
</blockquote></details>

`%v` formats `[]byte("b")` as `[118]`.  `%s` formats `[]byte(nil)` as the empty string. The latter seems preferable here, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13403#-:-Kc5JcIeU4EyqW4nKsEh:b14lqlb)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/engine/batch_test.go, line 883 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13403#-Kc5HMuTy_6yLCYrwlTU:-Kc5P0UAYCUiTKD3tXkT:b2nhswv) ([raw file](https://github.com/cockroachdb/cockroach/blob/de01ca6487f94ef1efefd5d39539f34c3148929e/pkg/storage/engine/batch_test.go#L883)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`%v` formats `[]byte("b")` as `[118]`.  `%s` formats `[]byte(nil)` as the empty string. The latter seems preferable here, right?
</blockquote></details>

Yep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13403)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13403#-:-Kc5PdZN9l-lMtveXYnK:bnfp4nl)*

**Pull request merged**
