### PR TITLE
cli: update tags in datadog tsdump upload

### PR DESCRIPTION
**Pull request by aa-joshi**
Previously, we were uploading metrics to datadog with cluster name as tag. Since this is a static field, we won't be able to differentiate between multiple uploads. To address this, we have introduced a tag with uuid. This would help us in differentiating between multiple uploads for same cluster.

Epic: CC-28996
Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127822)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi and @arjunmahishi)

___
*[`pkg/cli/tsdump.go` line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127822#-O2ydrOu9zdnyD_UOcmA:-O2ydrOu9zdnyD_UOcmB:bq3itp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/32605c9323a61e2fa777f79f21386330d157f3a1/pkg/cli/tsdump.go#L432)):*
> ```Go
> 	}
> 
> 	tags = append(tags, makeDDTag(uuidTag, d.uploadID))
> ```

I'm confused about what tags we expect to see in the final output, can you clarify that intent in the commit message as well?

Why do we use the tag `uuid`? It is never assigned a UUID as far as I can tell. I would call it `upload_id` or something like that.

**Review by arjunmahishi — COMMENTED** [review]
The changes :lgtm: overall. Will wait for the conversation about UUID to conclude. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127822#-:-O36EY0f6gvtaxTkRwwq:b1wfxqm)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi and @dhartunian)

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127822)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

___
*[`pkg/cli/tsdump.go` line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127822#-O2ydrOu9zdnyD_UOcmA:-O36Qgxc7fVeMnBiYy5h:b-zgjfa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/32605c9323a61e2fa777f79f21386330d157f3a1/pkg/cli/tsdump.go#L432)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I'm confused about what tags we expect to see in the final output, can you clarify that intent in the commit message as well?

Why do we use the tag `uuid`? It is never assigned a UUID as far as I can tell. I would call it `upload_id` or something like that.
</blockquote></details>

Thanks for pointing it out! We are generating uuid with format `clusterName-UUID{4}`. I thought we have standardised as part of profile upload merged PR. I have updated it now to make it as `upload_id` across tsdump, profile upload.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127822#-:-O388ue719MSXtvaBXPp:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by aa-joshi** [comment]
TFTR!

bors r+

**Pull request merged**
