### PR TITLE
opt: Hoist Exists operator and try to decorrelate

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR has two commits for easier review. The first adds support for OuterCols as a relational property. The second uses that to implement transforming the Exists operator into a SemiJoinApply operator, and then attempting to decorrelate that.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/norm/rules/join.opt, line 114 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAm_Y5qAjTK8Iziu3k0:-LAm_Y5qAjTK8Iziu3k1:bhi2mtv) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/rules/join.opt#L114)):*
> ```
> # operator.
> #
> # Citations: [3]
> ```

I believe the transformation in [3] is `apply(R, select(E)) -> select(apply(R, E))`. You're doing something slightly different here by tacking the selection filters onto the join condition. This is what I did in `opttoy` and it seemed to work ok, though it might be worthwhile to call out this difference in the comment here. 

---

*[pkg/sql/opt/norm/rules/select.opt, line 234 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAmagfF8MV-Zqgbm_zv:-LAmagfF8MV-Zqgbm_zw:b-qf0qxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/rules/select.opt#L234)):*
> ```
>     $input:*
>     $filter:(Filters
>         $list:[ ... $exists:(Not (Exists $subquery:* & (IsCorrelatedSubquery $subquery))) ... ]
> ```

Nice! These transformations are quite pleasant to read. 

---

*[pkg/sql/opt/norm/testdata/join, line 304 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAmZcup4eGo9qGzb9kG:-LAmZcup4eGo9qGzb9kH:bnjzbbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/join#L304)):*
> ```
> SELECT * FROM a WHERE EXISTS(SELECT * FROM b WHERE x=k)
> ----
> semi-join
> ```

:tada:

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969)*

**Comment by RaduBerinde** [comment]
Great stuff!

---

Review status: 14 of 25 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 130 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAmzLcA845U3u7FDtok:-LAneVJ6DMJmzF6rQH7z:b2hz8qk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d13e289c43a5692a636adf0f6336e5bd6e71561/pkg/sql/opt/memo/logical_props_factory.go#L130)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should this line be outside of the `if` statement? (Also, the `if` may not be needed at all -- `Difference` should handle it.)
</blockquote></details>

Note that `OuterCols` is `inputProps.OuterCols` already here (which is not ok to modify)

---

*[pkg/sql/opt/norm/factory.go, line 187 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAmxYvy7D_9kOQWlC3c:-LAmxYvy7D_9kOQWlC3d:b-hljcyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/factory.go#L187)):*
> ```Go
> 		}
> 
> 		newList[i] = item
> ```

[nit] add a comment saying that if the list doesn't contain the element, we panic here

---

*[pkg/sql/opt/norm/testdata/select, line 821 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAnvEAb8NbGVtLpQtVf:-LAnvEAb8NbGVtLpQtVg:b-pbt99k) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/select#L821)):*
> ```
>            └── variable: a.k [type=int, outer=(1)]
> 
> # Ensure that EXISTS is hoisted even when one of several conjuncts.
> ```

[nit] it is one of

---

*[pkg/sql/opt/norm/testdata/select, line 827 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAnvbyR7aF6HKjn1FSE:-LAnvbyR7aF6HKjn1FSF:b-hddlt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/select#L827)):*
> ```
> semi-join
>  ├── columns: k:1(int!null) i:2(int) f:3(float) s:4(string) j:5(jsonb)
>  ├── scan a
> ```

What is missing for `s=foo and i > 1` to be pushed down? I guess `PushFilterIntoJoinLeft` should be enabled on semi-join?

---

*[pkg/sql/opt/norm/testdata/select, line 918 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAnxDpT85dnvRKAdM00:-LAnxDpT85dnvRKAdM01:btoohhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/select#L918)):*
> ```
>  │    ├── columns: b.x:6(int!null) b.y:7(int)
>  │    └── keys: (6)
>  └── filters [type=bool, outer=(1,2,4,6), constraints=(/2: [/2 - ]; /4: [/'foo' - /'foo'])]
> ```

I don't think this is correct. This will for example output all rows where `s <> 'foo'` (it's similar to the behavior of ON with outer joins).

The filters should stay inside the left input. We could do that by adjusting the rule:
```
(AntiJoinApply
    (Select $input (Filters (RemoveListItem $list $exists)))
    $subquery
)
```

---

*[pkg/sql/opt/ops/scalar.opt, line 66 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAnwDR6CoEpACtmM4Ag:-LAnwDR6CoEpACtmM4Ah:beav52k) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/ops/scalar.opt#L66)):*
> ```
> #     (IsNull (Variable 1))
> #   )
> #
> ```

[nit] maybe mention that this is equivalent to `(IsNull (Subquery (Select .. )))`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-:-LAnyXAU7-MhmftV2RXL:b-8o237f)*

**Comment by rytaft** [comment]
This is exciting to see!

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[pkg/sql/opt/norm/rules/select.opt, line 178 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAny5P7B08JZ-MTcXVi:-LAny5P7B08JZ-MTcXVj:b7evcsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/rules/select.opt#L178)):*
> ```
> # PushSelectIntoGroupBy pushes a Select condition below a GroupBy in the case
> # where it does not reference any of the aggregation columns. This only works
> # if this is an instance of the "scalar" GroupBy, which returns only one row,
> ```

I think you meant -- this only works if this is *not* an instance of the scalar GroupBy

---

*[pkg/sql/opt/norm/rules/select.opt, line 228 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAnywNE-gSUFQWCWgs9:-LAnywNE-gSUFQWCWgsA:b-438hl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/rules/select.opt#L228)):*
> ```
> 
> # HoistSelectNotExists extracts non-existential subqueries from Select filters,
> # turning them into semi-joins. This eliminates the subquery, which is often
> ```

semi-joins -> anti-joins

---

*[pkg/sql/opt/norm/testdata/join, line 367 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAo-EVF25G02e2ccowd:-LAo-EVF25G02e2ccowe:b-1fw9mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/join#L367)):*
> ```
>  ├── values
>  │    ├── columns: column1:6(int)
>  │    ├── outer: (1)
> ```

why does this only show outer=(1) instead of outer=(1, 2)? 

---

*[pkg/sql/opt/norm/testdata/scalar, line 450 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-LAo-jNt2ld3jpcnuRkf:-LAo-jNt2ld3jpcnuRkg:b-3lcu84) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/scalar#L450)):*
> ```
> # --------------------------------------------------
> opt
> SELECT * FROM a WHERE EXISTS(SELECT MAX(s) FROM a GROUP BY i)
> ```

maybe also add a test for scalar group by to show that it doesn't get eliminated?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24969#-:-LAo2Xsd3LxtII2o8DWO:b54yo1f)*

**Comment by andy-kimball** [comment]
TFTR, I've made quite a few changes in response to comments, and fixed a few additional bugs that I found while making all the changes as well.

---

Review status: 12 of 25 files reviewed at latest revision, 18 unresolved discussions.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAmzLcA845U3u7FDtok:-LAnsCc1EWXlLFrRgp0v:bgv4tu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d13e289c43a5692a636adf0f6336e5bd6e71561/pkg/sql/opt/memo/logical_props_factory.go#L130)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should this line be outside of the `if` statement? (Also, the `if` may not be needed at all -- `Difference` should handle it.)
</blockquote></details>

This is a small optimization to avoid an allocation in the >64 cols case. We inherit the `OuterCols` of the input. The only time we have to modify them is if the filter is adding new outer cols (which is very unusual). `Difference` will allocate a map if there are >64 cols, so it seemed good to avoid that in the common case.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAn0XO66lNacq1DeH5i:-LAnsqxRDTIhr1kMG2hE:bsjte78) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d13e289c43a5692a636adf0f6336e5bd6e71561/pkg/sql/opt/memo/logical_props_factory.go#L155)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't think this check is necessary -- `Difference` will handle it.
</blockquote></details>

See above comment.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAn0Im22HNNPYQCk_WD:-LAnssEl-qwOiQlVwUjc:bsjte78) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d13e289c43a5692a636adf0f6336e5bd6e71561/pkg/sql/opt/memo/logical_props_factory.go#L209)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't think this check is necessary -- `Difference` will handle it.
</blockquote></details>

See above comment.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAn1Lv26VP12F6ZhozH:-LAntBb_6GeTiYPOT2eS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d13e289c43a5692a636adf0f6336e5bd6e71561/pkg/sql/opt/memo/logical_props_factory.go#L252)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] to make this match the logic above, you could just do

`props.Relational.OuterCols = aggProps.OuterCols.Difference(inputProps.OuterCols)`
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAn20zC1_NUKdL05hrX:-LAntEA87nvj8Pjj5rvs:b-h13gh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d13e289c43a5692a636adf0f6336e5bd6e71561/pkg/sql/opt/memo/logical_props_factory.go#L343)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

you miss the inputProps outer cols if there are no outer cols in the limit.
</blockquote></details>

They're copied from the input in that case. No need for an extra allocation in that 99% case.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAn25i-6gijKYfP64MX:-LAntQ28237d0Ph9pfTA:bsjte78) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d13e289c43a5692a636adf0f6336e5bd6e71561/pkg/sql/opt/memo/logical_props_factory.go#L362)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ditto 
</blockquote></details>

See above comment.

---

*[pkg/sql/opt/norm/factory.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAmxYvy7D_9kOQWlC3c:-LAp2zcL1VgPdwrk9LsB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/factory.go#L187)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a comment saying that if the list doesn't contain the element, we panic here
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/join.opt, line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAm_Y5qAjTK8Iziu3k0:-LAp3-nW262Q7xe0HqXV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/rules/join.opt#L114)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I believe the transformation in [3] is `apply(R, select(E)) -> select(apply(R, E))`. You're doing something slightly different here by tacking the selection filters onto the join condition. This is what I did in `opttoy` and it seemed to work ok, though it might be worthwhile to call out this difference in the comment here. 
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/select.opt, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAny5P7B08JZ-MTcXVi:-LAp3BE98aC_PjQdyc7k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/rules/select.opt#L178)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you meant -- this only works if this is *not* an instance of the scalar GroupBy
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/select.opt, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAnywNE-gSUFQWCWgs9:-LAp3FJ09qM_PKiIJHZG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/rules/select.opt#L228)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

semi-joins -> anti-joins
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/testdata/join, line 367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAo-EVF25G02e2ccowd:-LAoLt7c2Zl6ARtrnBju:b-t9erkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/join#L367)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why does this only show outer=(1) instead of outer=(1, 2)? 
</blockquote></details>

This is a bug in `LogicalPropsFactory.constructValuesProps`, which I just fixed. Good catch!

---

*[pkg/sql/opt/norm/testdata/scalar, line 450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAo-jNt2ld3jpcnuRkf:-LAoOwwZ2XX4PDE0HuDq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/scalar#L450)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

maybe also add a test for scalar group by to show that it doesn't get eliminated?
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/testdata/select, line 821 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAnvEAb8NbGVtLpQtVf:-LAoVZXf42yAD0MBBwNh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/select#L821)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] it is one of
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/testdata/select, line 827 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAnvbyR7aF6HKjn1FSE:-LAoV_I6A5nQ1vT3mtdU:b6yi7zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/select#L827)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What is missing for `s=foo and i > 1` to be pushed down? I guess `PushFilterIntoJoinLeft` should be enabled on semi-join?
</blockquote></details>

I added this case to this rule as well as the `JoinRight` variant. I also discovered a possible cycle that I need to detect, so there are a number of changes I made overall.

---

*[pkg/sql/opt/norm/testdata/select, line 918 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAnxDpT85dnvRKAdM00:-LAoYagZ9RNdooaIB3gm:b-vwf6uc) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/norm/testdata/select#L918)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think this is correct. This will for example output all rows where `s <> 'foo'` (it's similar to the behavior of ON with outer joins).

The filters should stay inside the left input. We could do that by adjusting the rule:
```
(AntiJoinApply
    (Select $input (Filters (RemoveListItem $list $exists)))
    $subquery
)
```
</blockquote></details>

You're right. I just pulled this rule from opttoy (where it wasn't tested) and didn't think about it enough. I modified this rule according to your suggestion and added some more tests as well.

---

*[pkg/sql/opt/ops/scalar.opt, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAnwDR6CoEpACtmM4Ag:-LAp2iJO9awZTT2GsIJ8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e5213380864a8388588f4792ef269e4e640edb/pkg/sql/opt/ops/scalar.opt#L66)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe mention that this is equivalent to `(IsNull (Subquery (Select .. )))`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-:-LAp4CrR0_gWfNYshyyh:b-hg7mvh)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 12 of 25 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-:-LAsEDOZ2gy327PLZBq0:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 1 of 13 files at r3, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/memo/logical_props_factory.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAmzLcA845U3u7FDtok:-LAsWqHaAMNZ4OJZnqam:bh5p8q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d13e289c43a5692a636adf0f6336e5bd6e71561/pkg/sql/opt/memo/logical_props_factory.go#L130)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This is a small optimization to avoid an allocation in the >64 cols case. We inherit the `OuterCols` of the input. The only time we have to modify them is if the filter is adding new outer cols (which is very unusual). `Difference` will allocate a map if there are >64 cols, so it seemed good to avoid that in the common case.
</blockquote></details>

Oops missed the assignment above. Thanks for the explanation!

---

*[pkg/sql/opt/norm/rules/join.opt, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-LAsa42X7PkLE4L9YoFK:-LAsa42X7PkLE4L9YoFL:bjic0db) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0440623e8821dbb529dd47bd53d98e786251884/pkg/sql/opt/norm/rules/join.opt#L54)):*
> ```
> # Citations: [1]
> [PushFilterIntoJoinLeft, Normalize]
> (InnerJoin | InnerJoinApply | RightJoin | RightJoinApply | SemiJoin | SemiJoinApply
> ```

Can you update the comment to explain why semi-joins are eligible but anti-joins are not?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24969#-:-LAsdx7U8O7ufmo7KaYm:bnfp4nl)*

**Pull request merged**
