### PR TITLE
log: AmbientContext helper for annotating contexts

### PR DESCRIPTION
**Pull request by RaduBerinde**
This helper will be stored in various server components and will replace the
"background" contexts we use directly. See #9807 for more information.

Posting this before actually changing anything else to nail down the details before modifying too much code.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9893)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM (but let the others take a look).

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[util/log/ambient_context.go, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmXKqvjONebTLgQ0E:-KTpmXKqvjONebTLgQ0F:bp7ify) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L22)):*
> ```Go
> 	opentracing "github.com/opentracing/opentracing-go"
> 	"golang.org/x/net/trace"
> ```

nit: remove

---

*[util/log/ambient_context.go, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmlu8L_mCRgU8Q8SE:-KTpmlu8L_mCRgU8Q8SF:bhs70ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L26)):*
> ```Go
> )
> 
> // AmbientContext is a helper type used to "annotate" context.Contexts with log tags
> ```

this line looks long but i'm eyeballing

---

*[util/log/ambient_context.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmctjWb39-VvL5AIU:-KTpmctjWb39-VvL5AIV:b-it2crq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L30)):*
> ```Go
> type AmbientContext struct {
> 	// Tracer is used to open spans (see AnnotateCtxWithSpan).
> 	Tracer opentracing.Tracer
> ```

:100: this is awesome. I'm very excited for tracers to stop being embedded in contexts.

---

*[util/log/ambient_context.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmvWOzOl_kj1rPSzc:-KTpmvWPfWeggux3WoRm:bho9nhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L46)):*
> ```Go
> 
> // EmptyAmbientContext creates an empty ambient context.
> func EmptyAmbientContext() AmbientContext {
> ```

Hm. Can we force the caller to pass a context.Context?

---

*[util/log/ambient_context_test.go, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmYL3K44YGlRnAkZP:-KTpmYL3K44YGlRnAkZQ:bp7ify) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context_test.go#L23)):*
> ```Go
> 
> 	opentracing "github.com/opentracing/opentracing-go"
> ```

nit: remove

---

*[util/log/trace_test.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpm0hv6ih8pHKwPmvC:-KTpm0hwh-Qwjmx-KBYm:btacazw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/trace_test.go#L38)):*
> ```Go
> 	opts.ShouldSample = func(_ uint64) bool { return true }
> 	opts.NewSpanEventListener = func() func(basictracer.SpanEvent) {
> 		var op string
> ```

neat trick, but add a comment

---

*[util/log/trace_test.go, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmEM99C5G4_bWN09k:-KTpmEM99C5G4_bWN09l:btnss04) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/trace_test.go#L68)):*
> ```Go
> 		//   span:path/file:line msg
> 		// to:
> 		//   span:event
> ```

s/event/msg/

---

*[util/log/trace_test.go, line 69 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmHRt8Q44GX-XX5Eq:-KTpmHRt8Q44GX-XX5Er:b-iwdbe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/trace_test.go#L69)):*
> ```Go
> 		// to:
> 		//   span:event
> 		groups := regexp.MustCompile(`^(.*):.*:[0-9]* (.*)$`).FindStringSubmatch(actual[i])
> ```

nit: consider extracting these regexps to package-level so they panic at init time

---

*[util/log/trace_test.go, line 185 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmRn66zJZvZJaZwmv:-KTpmRn66zJZvZJaZwmw:b8ftqh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/trace_test.go#L185)):*
> ```Go
> 	expected := events{"test1", "testerr(err)", "test2", "log", "errlog1(err)", "finish"}
> 	if !compareTraces(expected, el.ev) {
> 		t.Errorf("expected events '%s', got '%v'", expected, el.ev)
> ```

%v because it can be nil?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-:-KTsh44cx9XJJ1dJv6LQ:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[util/log/ambient_context.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmvWOzOl_kj1rPSzc:-KTtJvYCioK52pkgVTLY:b-9610t4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L46)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Hm. Can we force the caller to pass a context.Context?
</details>
What would that context be used for? We would copy the tags from it? (seems backward compared to what we're trying to do)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[util/log/ambient_context.go, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmXKqvjONebTLgQ0E:-KTtKTIX6Nry6v1LojaP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L22)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: remove
</details>
Done.

---

*[util/log/ambient_context.go, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmlu8L_mCRgU8Q8SE:-KTtKTr5UJ2bTXtFmEol:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this line looks long but i'm eyeballing
</details>
Done.

---

*[util/log/ambient_context_test.go, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmYL3K44YGlRnAkZP:-KTtL2lW70mkBCw_BOh3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context_test.go#L23)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: remove
</details>
Done.

---

*[util/log/trace_test.go, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmEM99C5G4_bWN09k:-KTtLYk8fB5mNV_ehiIA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/trace_test.go#L68)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/event/msg/
</details>
Done.

---

*[util/log/trace_test.go, line 185 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmRn66zJZvZJaZwmv:-KTtLd66VQ2b7wiNazQC:bwxis0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/trace_test.go#L185)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> %v because it can be nil?
</details>
It's not a Stringer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[util/log/ambient_context.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmvWOzOl_kj1rPSzc:-KTtNqo9H_I7a6vU0_El:b-w8vw8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L46)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> What would that context be used for? We would copy the tags from it? (seems backward compared to what we're trying to do)
</details>
I was thinking it would just be stored in the AmbientContext. The point is to force the caller to "find" a suitable context (usually by calling context.Background() but probably not always).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[util/log/ambient_context.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmvWOzOl_kj1rPSzc:-KTtOT8rKeQudFx6u4xZ:bczzjg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L46)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I was thinking it would just be stored in the AmbientContext. The point is to force the caller to "find" a suitable context (usually by calling context.Background() but probably not always).
</details>
And what would it be used for? By definition it can't affect what `AnnotateCtx` does

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[util/log/ambient_context.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmvWOzOl_kj1rPSzc:-KTtP1Lq13myE7MCjcca:b1misym) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L46)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> And what would it be used for? By definition it can't affect what `AnnotateCtx` does
</details>
Ah, I think we're imagining different use patterns. I was imagining something like:

```
ctx := context.Background()
ctx = context.WithValue(ctx, key1, value1)
...
ctx = context.WithValue(ctx, keyN, valueN)
myStructure := myStruct{
  ambientCtx: log.MakeAmbientContext(ctx)
}
```

Looks like you went the other way, where the mutation methods are on the ambient context. Can you help me understand why you chose to put the mutation on the ambient?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[util/log/ambient_context.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmvWOzOl_kj1rPSzc:-KTtQ9IduFF0ymK7eLvl:bnljp8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L46)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Ah, I think we're imagining different use patterns. I was imagining something like:
> 
> ```
> ctx := context.Background()
> ctx = context.WithValue(ctx, key1, value1)
> ...
> ctx = context.WithValue(ctx, keyN, valueN)
> myStructure := myStruct{
>   ambientCtx: log.MakeAmbientContext(ctx)
> }
> ```
> 
> Looks like you went the other way, where the mutation methods are on the ambient context. Can you help me understand why you chose to put the mutation on the ambient?
</details>
Why would we want to go through a `Context` to do that? Seems like it would unnecessarily confuse things. Also, we need to be able to start with an `AmbientContext` (from a "parent", e.g. `server`) and then add log tags to it. With your proposal, you would need to create a Context, annotate it using the parent's `AmbientContext`, add a log tag, and then convert it back into an `AmbientContext`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[util/log/ambient_context.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmvWOzOl_kj1rPSzc:-KTtZr5qiil8LV0q14Lx:b-3axozi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L46)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Why would we want to go through a `Context` to do that? Seems like it would unnecessarily confuse things. Also, we need to be able to start with an `AmbientContext` (from a "parent", e.g. `server`) and then add log tags to it. With your proposal, you would need to create a Context, annotate it using the parent's `AmbientContext`, add a log tag, and then convert it back into an `AmbientContext`
</details>
BTW I'm wondering if it would be better if we made the zero value work. We'd just have to add `if backgroundCtx == nil` checks in a few places. The way it is right now, we would need to check if it's initialized correctly in various places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893)*

**Comment by andreimatei** [comment]
:lgtm: awesome stuff

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[util/log/ambient_context.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmctjWb39-VvL5AIU:-KTtgWBR3lIzEL_5r2W5:b-85owmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L30)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> :100: this is awesome. I'm very excited for tracers to stop being embedded in contexts.
</details>
yeah, tracers in contexts were redundant, because you can get one from the Span. We have places in the code though that assert that one is present. Should we change them to assert that one is *not* present?

---

*[util/log/ambient_context.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTtgLyiEBOqnSnH6Lpz:-KTtgLyiEBOqnSnH6Lq-:b6t1o2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/68e0f825e64c0d970e5aa02ca51b8afe39db9124/util/log/ambient_context.go#L26)):*
> ```Go
> 
> // AmbientContext is a helper type used to "annotate" context.Contexts with log
> // tags or a Tracer or EventLog.
> ```

the "or a Tracer" part is wrong, isn't it? It should be "and/or a Span"

---

*[util/log/ambient_context.go, line 27 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTtfNCusaYdH-e83mE9:-KTtfNCusaYdH-e83mEA:b-63xsv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/68e0f825e64c0d970e5aa02ca51b8afe39db9124/util/log/ambient_context.go#L27)):*
> ```Go
> // AmbientContext is a helper type used to "annotate" context.Contexts with log
> // tags or a Tracer or EventLog.
> type AmbientContext struct {
> ```

pls add a usage example

---

*[util/log/ambient_context.go, line 38 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTtendfTmxswbKVq1bj:-KTtendgXrjJ7LRArVA1:bps4hdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/68e0f825e64c0d970e5aa02ca51b8afe39db9124/util/log/ambient_context.go#L38)):*
> ```Go
> 	// context.Background or context.TODO.
> 	//
> 	// It is also used to store the log tags. TODO(radu): going through this
> ```

any reason for not addressing the todo now? 

---

*[util/log/ambient_context.go, line 100 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTtib9aMQG2N9cy4N58:-KTtib9aMQG2N9cy4N59:b-wtmslg) ([raw file](https://github.com/cockroachdb/cockroach/blob/68e0f825e64c0d970e5aa02ca51b8afe39db9124/util/log/ambient_context.go#L100)):*
> ```Go
> 	ctx context.Context, opName string,
> ) (context.Context, opentracing.Span) {
> 	ctx = ac.AnnotateCtx(ctx)
> ```

like we discussed, let's clear the EventLog here to avoid confusion about what's gonna happen when you have both

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-:-KTtk_i8iWH5CiGKXYAJ:bqbhcko)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[util/log/ambient_context.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmctjWb39-VvL5AIU:-KTtlSYWazEtfnOIQu9f:bv0gheu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L30)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> yeah, tracers in contexts were redundant, because you can get one from the Span. We have places in the code though that assert that one is present. Should we change them to assert that one is *not* present?
</details>
Well they are still necessary right now, as that is the only way the `Tracer` is plumbed through to the various server components. Once we use AmbientContext everywhere I think we can remove the "infrastructure" for embedding a `Tracer` altogether.

---

*[util/log/ambient_context.go, line 38 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTtendfTmxswbKVq1bj:-KTtlmsqi-WwiWeF3DcK:b4exgdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/68e0f825e64c0d970e5aa02ca51b8afe39db9124/util/log/ambient_context.go#L38)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> any reason for not addressing the todo now? 
</details>
I'll do it soon in a separate PR, wanted to get the API nailed down first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[util/log/ambient_context.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmvWOzOl_kj1rPSzc:-KTtzylGKBStuMfeoI0H:b-fo89j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L46)):*
> Why would we want to go through a Context to do that? Seems like it would unnecessarily confuse things. Also, we need to be able to start with an AmbientContext (from a "parent", e.g. server) and then add log tags to it. With your proposal, you would need to create a Context, annotate it using the parent's AmbientContext, add a log tag, and then convert it back into an AmbientContext

How would you do it with your proposal? Starting with an `AmbientContext`, how do you make another `AmbientContext` that can be handed down into a subcomponent?

The summary of my proposal is that I would like `AmbientContext` to be immutable, so the embedded context must be fully specified by the caller.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[util/log/ambient_context.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmvWOzOl_kj1rPSzc:-KTu22dX_bTOUCMNXAKe:bd67c2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L46)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> > Why would we want to go through a Context to do that? Seems like it would unnecessarily confuse things. Also, we need to be able to start with an AmbientContext (from a "parent", e.g. server) and then add log tags to it. With your proposal, you would need to create a Context, annotate it using the parent's AmbientContext, add a log tag, and then convert it back into an AmbientContext
> 
> How would you do it with your proposal? Starting with an `AmbientContext`, how do you make another `AmbientContext` that can be handed down into a subcomponent?
> 
> The summary of my proposal is that I would like `AmbientContext` to be immutable, so the embedded context must be fully specified by the caller.
</details>
I would just copy it and call `AddLogTag` on the copy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893)*

**Comment by RaduBerinde** [comment]
Updated. We now operate on logTags directly.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[util/log/ambient_context.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTtgLyiEBOqnSnH6Lpz:-KTu4chzKVos8mYMI1bz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68e0f825e64c0d970e5aa02ca51b8afe39db9124/util/log/ambient_context.go#L26)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> the "or a Tracer" part is wrong, isn't it? It should be "and/or a Span"
</details>
Done.

---

*[util/log/ambient_context.go, line 27 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTtfNCusaYdH-e83mE9:-KTu4d1X1tIumcGDKb11:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68e0f825e64c0d970e5aa02ca51b8afe39db9124/util/log/ambient_context.go#L27)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> pls add a usage example
</details>
Done.

---

*[util/log/ambient_context.go, line 38 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTtendfTmxswbKVq1bj:-KTu4eJlMIQfApz0aYLj:b-cpg244) ([raw file](https://github.com/cockroachdb/cockroach/blob/68e0f825e64c0d970e5aa02ca51b8afe39db9124/util/log/ambient_context.go#L38)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I'll do it soon in a separate PR, wanted to get the API nailed down first.
</details>
Actually, it was easier than I thought, done.

---

*[util/log/ambient_context.go, line 100 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTtib9aMQG2N9cy4N58:-KTu4iEU5sbUJsE9t9Jg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68e0f825e64c0d970e5aa02ca51b8afe39db9124/util/log/ambient_context.go#L100)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> like we discussed, let's clear the EventLog here to avoid confusion about what's gonna happen when you have both
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-:-KTu64M2hYSLN6BG5tik:b7b1hac)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[util/log/ambient_context.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTpmvWOzOl_kj1rPSzc:-KTu6dOdtT8xiRP9nSQB:blfjfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9270931982da5a6215afe042a4ec6e33f8789fa/util/log/ambient_context.go#L46)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I would just copy it and call `AddLogTag` on the copy.
</details>
Well looks like the zero value works now, so LGTM.

---

*[util/log/log_context.go, line 149 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-KTu6xV2_mTvaL3xHPkv:-KTu6xV2_mTvaL3xHPkw:btg7oeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a018a43f3fcfd2319c69073bb945113a73c9c653/util/log/log_context.go#L149)):*
> ```Go
> }
> 
> // WithLogTagsFromCtx returns a context based on ctx with fromCtx's log tags
> ```

nit: you'd get a smaller diff if this function went above `copyTagChain`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9893#-:-KTu74KUvLfFulYVz0nH:bnfp4nl)*

**Pull request merged**
