### PR TITLE
engineccl/mvcc: fix time-bound iterator's interaction with moving intents

### LINKED ISSUE #34819: ccl/changefeedccl: TestAvroEncoder failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/965525a5deb3c4fab5ab232e069846ecc08f632d

Parameters:
```
TAGS=
GOFLAGS=-race
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=TestAvroEncoder PKG=github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1133737&tab=buildLog

```
I190212 07:34:23.816867 39761 sql/event_log.go:135  [n1,intExec=create-default-db] Event: "create_database", target: 51, info: {DatabaseName:postgres Statement:CREATE DATABASE IF NOT EXISTS postgres User:root}
I190212 07:34:23.843475 39528 server/server.go:1645  [n1] done ensuring all necessary migrations have run
I190212 07:34:23.843592 39528 server/server.go:1648  [n1] serving sql connections
I190212 07:34:23.870680 39789 sql/event_log.go:135  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:127.0.0.1:44729 Attrs: Locality: ServerVersion:2.1-6 BuildTag:v2.2.0-alpha.20190211-59-g965525a StartedAt:1549956863221167191 LocalityAddress:[] XXX_NoUnkeyedLiteral:{} XXX_sizecache:0} ClusterID:0767d590-e3a2-4b92-839a-d55b5e214481 StartedAt:1549956863221167191 LastUp:1549956863221167191}
I190212 07:34:23.873853 39786 server/server_update.go:67  [n1] no need to upgrade, cluster already at the newest version
I190212 07:34:23.916926 39497 sql/event_log.go:135  [n1,client=127.0.0.1:52492,user=root] Event: "set_cluster_setting", target: 0, info: {SettingName:kv.rangefeed.enabled Value:true User:root}
I190212 07:34:23.945303 39497 sql/event_log.go:135  [n1,client=127.0.0.1:52492,user=root] Event: "set_cluster_setting", target: 0, info: {SettingName:kv.closed_timestamp.target_duration Value:00:00:01 User:root}
I190212 07:34:23.982669 39497 sql/event_log.go:135  [n1,client=127.0.0.1:52492,user=root] Event: "set_cluster_setting", target: 0, info: {SettingName:changefeed.experimental_poll_interval Value:00:00:00.01 User:root}
I190212 07:34:24.009996 39497 sql/event_log.go:135  [n1,client=127.0.0.1:52492,user=root] Event: "create_database", target: 52, info: {DatabaseName:d Statement:CREATE DATABASE d User:root}
I190212 07:34:24.045299 39497 sql/event_log.go:135  [n1,client=127.0.0.1:52492,user=root] Event: "set_cluster_setting", target: 0, info: {SettingName:changefeed.push.enabled Value:false User:root}
I190212 07:34:24.077778 39497 sql/event_log.go:135  [n1,client=127.0.0.1:52492,user=root] Event: "set_cluster_setting", target: 0, info: {SettingName:changefeed.experimental_poll_interval Value:00:00:00.01 User:root}
I190212 07:34:24.105689 39497 sql/event_log.go:135  [n1,client=127.0.0.1:52492,user=root] Event: "create_table", target: 53, info: {TableName:d.public.foo Statement:CREATE TABLE foo (a INT8 PRIMARY KEY, b STRING) User:root}
I190212 07:34:24.120701 39912 storage/replica_command.go:245  [n1,split,s1,r20/1:/{Table/24-Max}] initiating a split of this range at key /Table/53 [r21] (zone config)
I190212 07:34:24.474823 39528 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] transport racer
1      [async] storage.IntentResolver: cleanup txn records
1      [async] intent_resolver_batcher
1      [async] closedts-rangefeed-subscriber
1      [async] changefeed-poller
1      [async] async-rollback
I190212 07:34:24.485080 39528 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] transport racer
1      [async] storage.IntentResolver: cleanup txn records
1      [async] closedts-rangefeed-subscriber
W190212 07:34:24.485542 39896 storage/intentresolver/intent_resolver.go:721  failed to gc transaction record: could not GC completed transaction anchored at /Local/Range/Table/24/RangeDescriptor: node unavailable; try another peer
I190212 07:34:24.485810 39528 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] transport racer
1      [async] closedts-rangefeed-subscriber
I190212 07:34:24.486039 39528 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] transport racer
I190212 07:34:24.570205 39659 kv/transport_race.go:113  transport race promotion: ran 12 iterations on up to 604 requests
    --- FAIL: TestAvroEncoder/poller (1.49s)
        <autogenerated>:1: expected
              foo: {"a":{"long":3}}->{"after":{"foo":{"a":{"long":3},"b":{"string":"baz"}}},"updated":{"string":"1549956864460181344.0000000000"}}
            got
              foo: {"a":{"long":3}}->{"after":{"foo":{"a":{"long":3},"b":{"string":"baz"}}},"updated":{"string":"1549956864451566598.0000000001"}}

```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #34819.

349ff61 introduced a workaround for #28358 into MVCCIncrementalIterator.
This workaround created a second (non-time-bound) iterator to verify
possibly-phantom MVCCMetadata keys during iteration.

We found in #34819 that it is necessary for correctness that sanityIter
be created before the original iter. This is because the provided Reader
that both iterators are created from may not be a consistent snapshot, so
the two iterators could end up observing different information. The hack
around sanityCheckMetadataKey only works properly if all possible
discrepancies between the two iterators lead to intents and values falling
outside of the timestamp range **from the time-bound iterator's perspective**.
This allows us to simply ignore discrepancies that we notice in advance().

This commit makes this change. It also adds a test that failed regularly
before the fix under stress and no longer fails after the fix.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

It would be nice if we could actually use the same iterator for the sanity and timebound iterators, instead of two separate ones. I think that can actually be made to work as the iterator options we pass to RocksDB can be mutated to clear out the table filter. Quite a bit more plumbing to accomplish it, though. The approach in this PR is likely safer at this point in the release cycle.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35682#-:-L_rH-pA98uSk4EqwoQB:b-laqts8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/ccl/storageccl/engineccl/mvcc_test.go, line 632 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35682#-L_rHfC40ShkouIMG9Kf:-L_rHfC40ShkouIMG9Kg:b-6xamuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c22f3091e66ee99522ef272f677a844236772d5b/pkg/ccl/storageccl/engineccl/mvcc_test.go#L632)):*
> ```Go
> // properly handles cases where an intent originally in a time-bound iterator's
> // time range is rewritten at a timestamp outside of its time range.
> func TestMVCCIncrementalIteratorIntentRewrittenConcurrently(t *testing.T) {
> ```

Did this fail reliably prior the fix, or only under stress? Adding a test synchronization point right before the sanity iter is created seems like it would allow a more deterministic reproduction.

**Review by nvb — COMMENTED** [review]
> It would be nice if we could actually use the same iterator for the sanity and timebound iterators, instead of two separate ones. I think that can actually be made to work as the iterator options we pass to RocksDB can be mutated to clear out the table filter.

I was thinking along the same lines, but accomplishing this by enforcing that both iterators use the same sequence number (same implicit snapshot) instead of by mutating table filters on a single iterator. Based on `rocksdb::ReadOptions` and `DBImpl::NewIterators`, it doesn't look like this is easily possible.

> The approach in this PR is likely safer at this point in the release cycle.

Agreed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35682#-:-L_rIaj713yx3rq2pOpW:b-iq364)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @petermattis)

___
*[pkg/ccl/storageccl/engineccl/mvcc_test.go, line 632 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35682#-L_rHfC40ShkouIMG9Kf:-L_rILxKDe9tz3SMO1sp:b5hjot7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c22f3091e66ee99522ef272f677a844236772d5b/pkg/ccl/storageccl/engineccl/mvcc_test.go#L632)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Did this fail reliably prior the fix, or only under stress? Adding a test synchronization point right before the sanity iter is created seems like it would allow a more deterministic reproduction.
</blockquote></details>

It failed within 100 iterations each time.

**Comment by petermattis** [comment]
> I was thinking along the same lines, but accomplishing this by enforcing that both iterators use the same sequence number (same implicit snapshot) instead of by mutating table filters on a single iterator. Based on rocksdb::ReadOptions and DBImpl::NewIterators, it doesn't look like this is easily possible.

The implicit snapshot is more than just a sequence number, it is a reference to the RocksDB `SuperVersion`. I've periodically wanted an `Iterator::Clone(*ReadOptions)` method, which creates a new iterator from an existing iterator using new options. Cc @ajkr.

**Comment by danhhz** [comment]
@nvanbenschoten I just realized that since we long ago backported the workaround into 2.1, we need to backport this, too. Would you mind doing that or would you prefer I do it?

**Comment by nvanbenschoten** [comment]
Done #35971.

**Pull request merged**
