### PR TITLE
pkg: skip TestCheckConsistencyInconsistent on short

### PR DESCRIPTION
**Pull request by andreimatei**
Takes 30s on my machine.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Couldn't resist looking:

> I200721 10:33:10.102640 22 testutils/testcluster/testcluster.go:762  WaitForFullReplication took: 27.519587s

This happens only when I use the on-disk stores. In-memory this finishes immediately.

I see that we spend ~.8s in `(*replicateQueue).process`.

**Comment by tbg** [comment]
Ugh, this is painful to look into more. I'm running out of time, https://github.com/tbg/cockroach/tree/TestCheckConsistencyInconsistent has my WIP

In short I have no idea. But it's having real disks that makes it a mess.

**Comment by lunevalex** [comment]
@tbg I believe the test has real disks to verify that the kill files are written when the inconsistency is found and that checkpoints are created.

**Comment by tbg** [comment]
@lunevalex I know why it has real disks, but what I don't understand is why it takes 30s if and only if it has real disks

**Review by andreimatei — COMMENTED** [review]
will someone give me a stamp on this if I file an issue saying something about disks vs mem?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51561#-:-MF73-cw2N48oWbGxPny:bfv06ys)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
I'm even fine with just a note in the test

**Review by tbg — APPROVED** [review]

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51561#-:-MFWp4L95z7rBKSj9hNt:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
