### PR TITLE
*: make the "TODO" syntax consistent.

### PR DESCRIPTION
**Pull request by knz**
(And add a linter.)

Requested by @dt.

### CODE REVIEW

**Review by dt — APPROVED** [review]
"Requested"

**Comment by tamird** [comment]
:lgtm: love me some linters

---

Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/style_test.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430#-KilJL9nRDxfEv6oaQQQ:-KilJL9o6F8_5fOui0VM:bcvnpq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8996046b0014edb98fbd0301f60989e6ca10c2e6/build/style_test.go#L189)):*
> ```Go
> 	t.Run("TestTodoStyle", func(t *testing.T) {
> 		t.Parallel()
> 		cmd, stderr, filter, err := dirCmd(pkg.Dir, "git", "grep", "-nE", `// TODO\([^)]*\)[^:]`, "--", "*.go")
> ```

why only Go files? also, do you want to look for other things as well, such as FIXME and others? How about a TODO that doesn't start at the beginning of the line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430#-:-KilJhdmWm04OHVZHk3-:b-7ojun4)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/style_test.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430#-KilJL9nRDxfEv6oaQQQ:-KilK1DvcFJt8gqkV1lk:b-2wliyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8996046b0014edb98fbd0301f60989e6ca10c2e6/build/style_test.go#L189)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why only Go files? also, do you want to look for other things as well, such as FIXME and others? How about a TODO that doesn't start at the beginning of the line?
</blockquote></details>

I don't think this is beginning of line only?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/style_test.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430#-KilJL9nRDxfEv6oaQQQ:-KilKgJAfGdQDufA2SlF:b-5ju9ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/8996046b0014edb98fbd0301f60989e6ca10c2e6/build/style_test.go#L189)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I don't think this is beginning of line only?
</blockquote></details>

Isn't it? "// TODO"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/style_test.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430#-KilJL9nRDxfEv6oaQQQ:-KilL_e6RzpaRgC36tLW:bkosxsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8996046b0014edb98fbd0301f60989e6ca10c2e6/build/style_test.go#L189)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Isn't it? "// TODO"
</blockquote></details>

A `//` comment can appear on the same line as other stuff.
I don't know what you have in mind? Do you have a regexp to suggest? This is the best I could come up with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/style_test.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430#-KilJL9nRDxfEv6oaQQQ:-KilLgjyWdKPxOncXV0_:b-v2wwb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8996046b0014edb98fbd0301f60989e6ca10c2e6/build/style_test.go#L189)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

A `//` comment can appear on the same line as other stuff.
I don't know what you have in mind? Do you have a regexp to suggest? This is the best I could come up with.
</blockquote></details>

(I tried `TODO\([^)]*\)[^:]` (to capture them anywhere) but we have a bunch of `context.TODO()` that match!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/style_test.go, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430#-KilJL9nRDxfEv6oaQQQ:-KilPB35p6mSyOySvMcg:b4k0kxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8996046b0014edb98fbd0301f60989e6ca10c2e6/build/style_test.go#L189)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

(I tried `TODO\([^)]*\)[^:]` (to capture them anywhere) but we have a bunch of `context.TODO()` that match!)
</blockquote></details>

Oh, yikes! Maybe `[^.]TODO`? Anyway, this is fine too, just saying it's not necessarily complete. Slap a TODO on it and move on :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15430)*

**Comment by knz** [comment]
I went for `\sTODO`. Your proposal hit a metric called `"TODO(marc)"`.

**Pull request merged**
