### PR TITLE
sql: check CHECK constraints during UPDATE too

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6753)

### CODE REVIEW

**Comment by paperstreet** [comment]
:lgtm:

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> #### sql: check CHECK constraints during UPDATE too
> 
> 
> 
> 
> </details>


---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/update.go, line 323 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6753#-KHzvVnJZEW-_h5VwSju:-KHzvVnJZEW-_h5VwSjv:2139562696) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be6bf6ce671a57efc8d522a5dac63281b9b99c6/sql/update.go#L323)):*
> ```Go
> 
> 	u.checkHelper.loadRow(u.tw.ru.fetchColIDtoRowIndex, oldValues, false)
> 	u.checkHelper.updateRow(u.updateCols, updateValues)
> ```

make checkHelper.updateRow take the map[ColumnID]int and cache it somewhere instead of computing it once per row.

maybe have makeRowUpdater compute it and put it on rowUpdater?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6753#-:-KHzwU37KWSrT4qj_-ek:1417088721)*

**Comment by vivekmenezes** [comment]
I haven't been following these CHECK constraint PRs. Just checking if we
are rolling out these constraints properly like a schema change? The F1
paper talks about rolling them out using an intermediate WRITE_ONLY state.
Feel free to create an issue we aren't

**Comment by dt** [comment]
They're not checking schema changes at all right now. The last couple PRs were refactors/cleanups of the initial impl, but I'll look at handling schema changes in a follow-up.

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/update.go, line 323 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6753#-KHzvVnJZEW-_h5VwSju:-KI-9Gmgs2_PfM8Wc1MZ:-970045554) ([raw file](https://github.com/cockroachdb/cockroach/blob/7be6bf6ce671a57efc8d522a5dac63281b9b99c6/sql/update.go#L323)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> make checkHelper.updateRow take the map[ColumnID]int and cache it somewhere instead of computing it once per row.
> 
> maybe have makeRowUpdater compute it and put it on rowUpdater?</details>
Done.

Left it on updateNode for now though I imagine it's long-term home will become clearer once we see how this looks in UPSERT.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6753)*

**Pull request merged**
