### PR TITLE
opt: allow ON CONFLICT to reference UNIQUE WITHOUT INDEX constraints

### LINKED ISSUE #58246: sql, opt: allow ON CONFLICT to reference columns with a UNIQUE WITHOUT INDEX constraint
Currently, `ON CONFLICT` clauses in an `INSERT` statement are only allowed to reference columns that are the keys of a unique index. Otherwise, the error is returned: `there is no unique or exclusion constraint matching the ON CONFLICT specification`. In order to ensure that applications will continue to work correctly when users upgrade from a single region table to a `REGIONAL BY ROW` table, we will need to allow `ON CONFLICT` to reference columns that have a `UNIQUE WITHOUT INDEX` constraint defined.

### PR DESCRIPTION
**Pull request by rytaft**
Prior to this commit, attempting to specify an `ON CONFLICT` clause referencing
a `UNIQUE WITHOUT INDEX` constraint caused an error "there is no unique or
exclusion constraint matching the ON CONFLICT specification".

This commit allows `ON CONFLICT` clauses to reference these constraints, and
also ensures that the unique constraints are checked for `ON CONFLICT DO NOTHING`
clauses when there are no columns specified.

Fixes #58246

There is no release note since `UNIQUE WITHOUT INDEX` is still gated behind the
`experimental_enable_unique_without_index_constraints` session variable.

Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
> Reviewed 19 of 19 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/insert.go, line 690 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQwXEB8SxAHHidJxUV:-MRQwXEB8SxAHHidJxUW:behkanf) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L690)):*
> ```Go
> 	mb.outScope.ordering = nil
> 
> 	buildInputForArbiter := func(
> ```

[nit] I think a comment here explaining the arguments would be helpful, especially functions `colOrdinal` and `projectPartialIndexDistinctCol`.
___
*[pkg/sql/opt/optbuilder/insert.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQwsyK7kjhi3egBf5c:-MRQwsyK7kjhi3egBf5d:birsg1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L763)):*
> ```Go
> 		var partialIndexDistinctCol *scopeColumn
> 		if isPartial {
> 			partialIndexDistinctCol = projectPartialIndexDistinctCol()
> ```

Why did this need to change? I think you could revert this and not require the `projectPartialIndexDistinctCol` function as an argument.
___
*[pkg/sql/opt/optbuilder/insert.go, line 795 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQxacq7NBIhYOLVHM_:-MRQxacq7NBIhYOLVHMa:b-jggqhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L795)):*
> ```Go
> 	for idx, idxCount := 0, mb.tab.IndexCount(); idx < idxCount; idx++ {
> 		// Skip non-arbiter indexes.
> 		if !arbiterIndexes.Contains(idx) {
> ```

I realize I was probably the one who originally wrote this loop, but I'm curious if there's a reason to loop over all indexes rather than iterate over each value within `arbiterIndexes`? Same with `arbiterConstraints` below.
___
*[pkg/sql/opt/optbuilder/insert.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQvhqq6UdNXEOBWCJp:-MRQvhqrB-yV08F6vroj:brnh0v9) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L824)):*
> ```Go
> 		buildInputForArbiter(uniqueConstraint.ColumnCount(), func(i int) int {
> 			return uniqueConstraint.ColumnOrdinal(mb.tab, i)
> 		}, false /* isPartial */, nil, nil)
> ```

[nit] you may not need to pass an `isPartial` boolean—the `buildInputForArbiter can just check if the `predExpr` argument is `nil`. But if you think this is clearer to read, then leave as-is.

[nit] add comments for the `nil` argument names here.
___
*[pkg/sql/opt/optbuilder/insert.go, line 860 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQxHx7DStLRceuwDVP:-MRQxHx7DStLRceuwDVQ:bj0b66w) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L860)):*
> ```Go
> 	mb.outScope.ordering = nil
> 
> 	buildInputForArbiter := func(
> ```

[nit] add comment to explain the arguments to this function.
___
*[pkg/sql/opt/optbuilder/insert.go, line 1022 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQzJXy0RPs424N9RqQ:-MRQzJXy0RPs424N9RqR:b-7fv955) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L1022)):*
> ```Go
> 			// of the primary keys.
> 			return &mb.fetchScope.cols[findNotNullIndexCol(mb.tab.Index(cat.PrimaryIndex))]
> 		}, false /* isPartial */, nil, nil)
> ```

[nit] ditto about commenting the `nil` arguments and maybe you don't need to pass in `isPartialIndex` or a `partialIndexDistinctCol` function at all.
___
*[pkg/sql/opt/optbuilder/insert.go, line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRR-GTaEekpbJq4xUxy:-MRR-GTaEekpbJq4xUxz:bnh4aza) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L1231)):*
> ```Go
> //
> // An arbiter constraint must have columns that match the columns in
> // conflictOrds.
> ```

[nit] might be worth clarifying that a unique constraint, which is created by `UNIQUE WITHOUT INDEX`, cannot be "partial", so it has no predicate to check for implication with arbiterPredicate.
___
*[pkg/sql/opt/optbuilder/insert.go, line 1352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRR9v8168q0ejVcYe7D:-MRR9v8168q0ejVcYe7E:b-2vrfin) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L1352)):*
I'm not convinced you can return early in this case. We err if more than 1 unique constraint or index matches the on conflict specification:

> there are multiple unique or exclusion constraints matching the ON CONFLICT specification

I guess it's a contrived case, but wouldn't we expect an error in this case:

```
CREATE TABLE t (
  i INT
  UNIQUE INDEX (i),
  UNIQUE WITHOUT INDEX (i)
)

INSERT INTO t VALUES (1) ON CONFLICT (i) DO UPDATE SET i = 2
```

I don't think an error will occur if you return an empty arbiter constraints whenever you have one or more arbiter indexes.

If we don't want to error in this case, we should add a test to assert the desired behavior.

**Review by rytaft — COMMENTED** [review]
TFTR! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-:-MRV_ByUEPX0yQkk-K6x:b-p0fj95)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/insert.go, line 690 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQwXEB8SxAHHidJxUV:-MRVMtKv0wduXhWRP8la:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L690)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] I think a comment here explaining the arguments would be helpful, especially functions `colOrdinal` and `projectPartialIndexDistinctCol`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQwsyK7kjhi3egBf5c:-MRVJGNN-Y85I4R2Q_ax:b-20s260) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L763)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why did this need to change? I think you could revert this and not require the `projectPartialIndexDistinctCol` function as an argument.
</blockquote></details>

I think this is fixed by the new `buildDistinctOnForArbiter` function -- but let me know if I misunderstood
___
*[pkg/sql/opt/optbuilder/insert.go, line 795 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQxacq7NBIhYOLVHM_:-MRVMut7CoxdPcjJkKb7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L795)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I realize I was probably the one who originally wrote this loop, but I'm curious if there's a reason to loop over all indexes rather than iterate over each value within `arbiterIndexes`? Same with `arbiterConstraints` below.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQvhqq6UdNXEOBWCJp:-MRVNvqv3u9GNaNaG7Xb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L824)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] you may not need to pass an `isPartial` boolean—the `buildInputForArbiter can just check if the `predExpr` argument is `nil`. But if you think this is clearer to read, then leave as-is.

[nit] add comments for the `nil` argument names here.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 860 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQxHx7DStLRceuwDVP:-MRVOjmnBoaLL4GZCAh_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L860)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] add comment to explain the arguments to this function.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 1022 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRQzJXy0RPs424N9RqQ:-MRVOkva6pZfhEcOauD2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L1022)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] ditto about commenting the `nil` arguments and maybe you don't need to pass in `isPartialIndex` or a `partialIndexDistinctCol` function at all.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRR-GTaEekpbJq4xUxy:-MRVRSZm9le-281DluG0:b-34stvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L1231)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] might be worth clarifying that a unique constraint, which is created by `UNIQUE WITHOUT INDEX`, cannot be "partial", so it has no predicate to check for implication with arbiterPredicate.
</blockquote></details>

Done. But I also realized that we might need to support this later, so added a TODO + issue.
___
*[pkg/sql/opt/optbuilder/insert.go, line 1352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRR9v8168q0ejVcYe7D:-MRVToucB659XeA0n8yg:bp1xec8) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L1352)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm not convinced you can return early in this case. We err if more than 1 unique constraint or index matches the on conflict specification:

> there are multiple unique or exclusion constraints matching the ON CONFLICT specification

I guess it's a contrived case, but wouldn't we expect an error in this case:

```
CREATE TABLE t (
  i INT
  UNIQUE INDEX (i),
  UNIQUE WITHOUT INDEX (i)
)

INSERT INTO t VALUES (1) ON CONFLICT (i) DO UPDATE SET i = 2
```

I don't think an error will occur if you return an empty arbiter constraints whenever you have one or more arbiter indexes.

If we don't want to error in this case, we should add a test to assert the desired behavior.
</blockquote></details>

We return on line 1326 as soon as a non-partial index is found, so I don't think your test case would find an issue. But this case is relevant:

```
CREATE TABLE t (
  i INT,
  CONSTRAINT i1 UNIQUE (i) WHERE i > 0,
  CONSTRAINT i2 UNIQUE WITHOUT INDEX(i)
);

INSERT INTO t VALUES (1) ON CONFLICT (i) WHERE i > 0 DO UPDATE SET i = 2;
```

That currently doesn't cause an error, but this does:

```
CREATE TABLE t1 (
  i INT,
  CONSTRAINT i1 UNIQUE (i) WHERE i > 0,
  CONSTRAINT i2 UNIQUE (i) WHERE i > 0
);

INSERT INTO t1 VALUES (1) ON CONFLICT (i) WHERE i > 0 DO UPDATE SET i = 2;
```

So I'm not sure what the desired behavior is in the first example (one partial index and one unique constraint). It seems to me like we'd always prefer to use an index if it's available, and it doesn't seem like it could lead to incorrect behavior, could it?

I've added these as test cases.

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/insert.go, line 1352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRR9v8168q0ejVcYe7D:-MRVfwAM5J8rKuQJpXhy:b-jdpxen) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L1352)):*
I guess the question to ask is: do we expect `UNIQUE WITHOUT INDEX` to result in logically equivalent behavior as `UNIQUE` during inserts/upserts? I think the answer is *yes*.

If the answer is *yes*, then I think you've pointed out a crucial detail, which might lead to incorrect behavior:

> We return on line 1326 as soon as a non-partial index is found

The result of the early return on line 1326 is that the arbiter predicate given in the `INSERT` is "ignored". Using Postgres as an oracle, notice how the conflict outside the unique partial index is detected, and the update applied (`i` is set to 2), despite the `i > 0` arbiter predicate in the `INSERT` statement:

```
marcus=# create table t (i INT UNIQUE);
CREATE TABLE

marcus=# create index i on t (i) where i > 0;
CREATE INDEX

marcus=# insert into t values (-1) on conflict (i) where i > 0 do update set i = 1;
INSERT 0 1

marcus=# insert into t values (-1) on conflict (i) where i > 0 do update set i = 2;
INSERT 0 1

marcus=# select * from t;
 i
---
 2
```

I would expect that in CRDB if we replaced `i INT UNIQUE` with `i INT UNIQUE WITHOUT INDEX`, the behavior would be the same. Which means if we've found partial index arbiters, we still need to check for a unique constraint that would be the sole arbiter.

A logic test like this might be good to add:

```
statement ok
CREATE TABLE t (
  i INT,
  UNIQUE WITHOUT CONSTRAINT (i),
  INDEX (i) WHERE i > 0
);
INSERT INTO t VALUES (-1) ON CONFLICT (i) WHERE i > 0 DO UPDATE SET i = 1;
INSERT INTO t VALUES (-1) ON CONFLICT (i) WHERE i > 0 DO UPDATE SET i = 2;

query I
SELECT i FROM t
----
2
```
___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-upsert, line 1420 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRVrQtE7Pw5gcLIaVpg:-MRVrQtE7Pw5gcLIaVph:b28ajtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f826f4396b80d90c44cf741691298ea02de5b1/pkg/sql/opt/optbuilder/testdata/unique-checks-upsert#L1420)):*
> ```
>                      └── column2:6 = uniq_fk_parent.a:7
> 
> # Check that we don't error here even though there are multiple arbiters.
> ```

[super pedantic nit] in the test immediately below, there's only 1 arbiter. there are "multiple potential arbiters". 
___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-upsert, line 1510 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRVkAEz41qpJ1zoEBzE:-MRVkAF-28h48yidJyYp:b-53zrx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f826f4396b80d90c44cf741691298ea02de5b1/pkg/sql/opt/optbuilder/testdata/unique-checks-upsert#L1510)):*
> ```
>                      └── upsert_rowid:16 != rowid:18
> 
> # Multiple partial index arbiters does cause an error, though.
> ```

[super nit] there's already a test for this in `upsert`, but feel free to leave this if you'd like.

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/optbuilder/insert.go, line 1352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRR9v8168q0ejVcYe7D:-MRVuwZr1TCDVWi7tUSv:b-4zohuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L1352)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I guess the question to ask is: do we expect `UNIQUE WITHOUT INDEX` to result in logically equivalent behavior as `UNIQUE` during inserts/upserts? I think the answer is *yes*.

If the answer is *yes*, then I think you've pointed out a crucial detail, which might lead to incorrect behavior:

> We return on line 1326 as soon as a non-partial index is found

The result of the early return on line 1326 is that the arbiter predicate given in the `INSERT` is "ignored". Using Postgres as an oracle, notice how the conflict outside the unique partial index is detect, and the update applied (`i` is set to 2), despite the `i > 0` arbiter predicate in the `INSERT` statement:

```
marcus=# create table t (i INT UNIQUE);
CREATE TABLE

marcus=# create index i on t (i) where i > 0;
CREATE INDEX

marcus=# insert into t values (-1) on conflict (i) where i > 0 do update set i = 1;
INSERT 0 1

marcus=# insert into t values (-1) on conflict (i) where i > 0 do update set i = 2;
INSERT 0 1

marcus=# select * from t;
 i
---
 2
```

I would expect that in CRDB if we replaced `i INT UNIQUE` with `i INT UNIQUE WITHOUT INDEX`, the behavior would be the same. Which means if we've found partial index arbiters, we still need to check for a unique constraint that might would the sole arbiter.

A logic test like this might be good to add:

```
statement ok
CREATE TABLE t (
  i INT,
  UNIQUE WITHOUT CONSTRAINT (i),
  INDEX (i) WHERE i > 0
);
INSERT INTO t VALUES (-1) ON CONFLICT (i) WHERE i > 0 DO UPDATE SET i = 1;
INSERT INTO t VALUES (-1) ON CONFLICT (i) WHERE i > 0 DO UPDATE SET i = 2;

query I
SELECT i FROM t
----
2
```


</blockquote></details>

Apologies for the garbled sentences (I know you're already aware of my skill in producing typos :laughing: ).

"notice how the conflict outside the unique partial index is detect"
=>
"notice how the conflict outside the unique partial index is **detected**"

"we still need to check for a unique constraint that might would the sole arbiter"
=>
"we still need to check for a unique constraint that **would be** the sole arbiter"

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/insert.go, line 1352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRR9v8168q0ejVcYe7D:-MReD0Yh3xruJ6OXtMYA:b-n9xajd) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L1352)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Apologies for the garbled sentences (I know you're already aware of my skill in producing typos :laughing: ).

"notice how the conflict outside the unique partial index is detect"
=>
"notice how the conflict outside the unique partial index is **detected**"

"we still need to check for a unique constraint that might would the sole arbiter"
=>
"we still need to check for a unique constraint that **would be** the sole arbiter"
</blockquote></details>

Ah nice catch! I changed the test case a bit, since I'm guessing this is what you meant (one unique without index constraint and one partial unique index on the same column):
```
CREATE TABLE t (
  i INT,
  UNIQUE WITHOUT INDEX (i),
  UNIQUE INDEX (i) WHERE i > 0
)
...
```
Updated the logic to ensure that the unique without index constraint is used as the arbiter in this case.
___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-upsert, line 1420 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRVrQtE7Pw5gcLIaVpg:-MReJ10A1hKJ0bAEtynL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f826f4396b80d90c44cf741691298ea02de5b1/pkg/sql/opt/optbuilder/testdata/unique-checks-upsert#L1420)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[super pedantic nit] in the test immediately below, there's only 1 arbiter. there are "multiple potential arbiters". 
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-upsert, line 1510 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRVkAEz41qpJ1zoEBzE:-MReJ2edApAwB5lCpwH1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19f826f4396b80d90c44cf741691298ea02de5b1/pkg/sql/opt/optbuilder/testdata/unique-checks-upsert#L1510)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[super nit] there's already a test for this in `upsert`, but feel free to leave this if you'd like.
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
Very nice! :lgtm: 

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-:-MRf9nNE963r2mziWtKB:bup7q37)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/insert.go, line 1352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-MRR9v8168q0ejVcYe7D:-MRf961I8uHNTLBrqS_H:b-clagmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/597a0c26526b71fe6b8b7382370f0ff5135d324d/pkg/sql/opt/optbuilder/insert.go#L1352)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ah nice catch! I changed the test case a bit, since I'm guessing this is what you meant (one unique without index constraint and one partial unique index on the same column):
```
CREATE TABLE t (
  i INT,
  UNIQUE WITHOUT INDEX (i),
  UNIQUE INDEX (i) WHERE i > 0
)
...
```
Updated the logic to ensure that the unique without index constraint is used as the arbiter in this case.
</blockquote></details>

Great! And yes, that's exactly what I meant.

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59135#-:-MRfM0LZ2BzcQ0NongEt:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
