### PR TITLE
sql/stats: add table setting to disable generation of stats forecasts

### LINKED ISSUE #86353: sql/opt: add table setting to disable statistics forecasting
Follow up from #79872: now that statistics forecasts are enabled for all tables, we should add a table setting to disable forecasting, similar to #78110. We already have some of this in place from #79025.

Jira issue: CRDB-18709

### PR DESCRIPTION
**Pull request by michae2**
Add a new storage parameter (a.k.a. table setting) which can be used to
override cluster setting `sql.stats.forecasts.enabled`. This builds on
work done earlier in #79025 and #86932 so we don't have to do much, just
wire it all together.

Fixes: #86353

Release justification: Low-risk update to new functionality.

Release note (sql change): Add a new table setting
`sql_stats_forecasts_enabled` which controls whether statistics
forecasts are generated for a specific table. When set, this overrides
cluster setting `sql.stats.forecasts.enabled`.

### CODE REVIEW

**Comment by michae2** [comment]
Note that the first commit is from #86932 and can be ignored.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86986#-:-NAW07oC2To4s17LbJhq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @msirek)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/forecast` line 743 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86986#-NAW0EMtE6Nwwpc296M3:-NAW0EMtE6Nwwpc296M4:b-4d9qux) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef464465aed263857ade16f337915ad56db231d2/pkg/sql/opt/exec/execbuilder/testdata/forecast#L743)):*
> ```
> statement ok
> CREATE TABLE d (d DATE PRIMARY KEY)
> WITH (sql_stats_automatic_collection_enabled = false, sql_stats_forecasts_enabled = false)
> ```

Is it worth also testing the other direction, that we can explicitly enable stats on a table even if the cluster setting is false?

**Comment by rytaft** [comment]
*[`pkg/sql/opt/exec/execbuilder/testdata/forecast` line 743 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86986#-NAW0EMtE6Nwwpc296M3:-NAW0UkMEaLFuXf90VXh:b-gv9poy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef464465aed263857ade16f337915ad56db231d2/pkg/sql/opt/exec/execbuilder/testdata/forecast#L743)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is it worth also testing the other direction, that we can explicitly enable stats on a table even if the cluster setting is false?
</blockquote></details>

(by stats I mean forecasts)

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86986#-:-NAWZr8R60pTTJHLX8C2:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2)

**Review by michae2 — COMMENTED** [review]
Thank you for the Saturday reviews!

bors r=rytaft,msirek

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86986#-:-NAXmRmO2tuHESAZZFJM:b-c6gxar)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/forecast` line 743 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86986#-NAW0EMtE6Nwwpc296M3:-NAXm4C42bcZ4zWEFccO:b9hqhfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef464465aed263857ade16f337915ad56db231d2/pkg/sql/opt/exec/execbuilder/testdata/forecast#L743)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

(by stats I mean forecasts)
</blockquote></details>

Yes, definitely worth testing, and good news is that I did sneakily include a test like this by adding `sql_stats_forecasts_enabled = true` to `CREATE TABLE c` up above. But that was too subtle, so I've moved it to an `ALTER TABLE c` down below with a comment.

**Pull request merged**
