### PR TITLE
cli/start: fix the selection of directories for temp storage and external I/O

### LINKED ISSUE #62357: cli/start: initExternalIODir() called with first store as arg, not first *disk* store
All the other logic in the startup routine first seek which of the store configs designates a disk (on-disk directory). It's possible to start a server with some stores in RAM.

However initExternalIODir() does not do this like the rest and fixates on the first store directory.

IT should do the same as the rest instead.

### PR DESCRIPTION
**Pull request by knz**
Fixes #62357.

See the individual commits for details.

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94985#-:-NLR9YGJ3XERQmDFjbzy:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
bors r=jbowens single on

**Comment by knz** [comment]
bors r=jbowens single on

**Comment by knz** [comment]
bors r=jbowens single on

**Comment by rail** [comment]
bors single on

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Pull request merged**
