### PR TITLE
roachtest: add pebble write-throughput benchmark

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, roachtest is used to run the YCSB benchmarks on Pebble. The
results are collected and pushed to an S3 bucket for rendering on the
[Pebble Benchmarks][1] page.

A write-throughput benchmark was [recently added to Pebble][2] to aid in
identifying the maximum sustainable write throughput for a Pebble
instance and identify potential bottlenecks.

Add to the existing Pebble roachtest to register a new test similar to
the YCSB test that runs `./pebble bench write ...` on instances in the
test cluster.

The initial implementation of the write-throughput benchmark only runs a
single variant (`values=1024`) of the benchmark on GCE nodes with 16
local SSDs in a RAID 0 configuration. The test runs for eight hours. A
follow up change will add additional configurations once the new
roachtest starts consistently producing results.

Split out the common functionality from the existing
`teamcity-nightly-pebble.sh` script into a separate script that can be
sourced by the YCSB- and write-throughput-specific scripts.

Create a symlink with the exiting script name pointing to the more
specific YCSB benchmark script. This allows the existing TeamCity
configuration to continue to reference the expected file. Once TeamCity
has been updated to point at the source, this symlink can be removed.

Create a write-throughput-specific script that executes the
write-throughput benchmarks and merges the output data using `mkbench`,
similar to the YCSB script. Using separate scripts for the two benchmark
types allows the benchmark clusters to be spawned by TeamCity in
parallel, rather than serially.

Release note: None

[1]: https://cockroachdb.github.io/pebble/

[2]: cockroachdb/pebble#1345

### CODE REVIEW

**Comment by nicktrav** [comment]
I tested that both a) the existing TeamCity entrypiont script `./build/teamcity-nightly-pebble.sh` (which is now a symlink to `./build/teamcity-nightly-pebble-ycsb.sh`), and b) the new script `./build/teamcity-nightly-pebble-write-throughput.sh`, ran tom completion and generated the expected outputs with some minimal local changes on top of this patch (detailed [here](https://gist.github.com/nicktrav/e71665a9c3754e3dc706520b3f00b7f8)).

Everything looked as expected, so I'm fairly confident this will not break the existing Pebble nightly benchmark runs.

If there is any additional testing that we typically do for these script changes, please let me know.

**Review by bananabrick — COMMENTED** [review]
Nice work wiring this up. At a high level, I think this should be in its own file, separate from the pebble ycsb roachtest in pebble.go. What do you think?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72632#-:-MoCMR3b5Hc4TJzilzcw:b-bl6ix0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Review by nicktrav — COMMENTED** [review]
I split the existing `pebble.go` into two files that export their respective tests in the latest diff. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72632#-:-MoEwMwpAhJvGm2ufL1g:b-jajycq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Review by bananabrick — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72632)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @nicktrav)

___
*[pkg/cmd/roachtest/tests/pebble_ycsb.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72632#-MoF15hs89DsRUhU9Jua:-MoF15hs89DsRUhU9Jub:b4ntoo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f3c5b39915cfc28b4aee6a90cc26a1c4bb97492/pkg/cmd/roachtest/tests/pebble_ycsb.go#L49)):*
> ```Go
> 			if dur != 90 {
> 				tag = "pebble"
> 				name += "-short"
> ```

nit: This was probably changed in the other pr, but can we make this `/duration=10`? I haven't seen a `-` used in roachtest names before.

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72632)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[pkg/cmd/roachtest/tests/pebble_ycsb.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72632#-MoF15hs89DsRUhU9Jua:-MoF7g9W2gtro2IH-EJw:b-6dwx2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f3c5b39915cfc28b4aee6a90cc26a1c4bb97492/pkg/cmd/roachtest/tests/pebble_ycsb.go#L49)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: This was probably changed in the other pr, but can we make this `/duration=10`? I haven't seen a `-` used in roachtest names before.
</blockquote></details>

Done.

```
$ ./bin/roachtest list tag:pebble$ | grep -v skipped
pebble/ycsb/size=1024/duration=10 [storage]
pebble/ycsb/size=64/duration=10 [storage]
```

**Comment by nicktrav** [comment]
bors retry

**Comment by nicktrav** [comment]
bors retry

**Comment by nicktrav** [comment]
TFTR!

**Pull request merged**
