### PR TITLE
ccl: regionless restores with rbr table(s) fail fast, add version gate

### LINKED ISSUE #111348: sql-foundations: tweak regionless restore syntax and semantics
#110606 Added the new `strip_localities` option to `RESTORE`. The DR team thinks two small things should change before this feature is released into the wild. I apologize for overlooking these during the review!!

1. we should change `strip_localities` to `remove_regions` (or something similar), because 1) `strip_localities` sounds too similar to the existing `skip_localities` option and 2) and "localities" (e.g. [locality aware backups](https://www.cockroachlabs.com/docs/stable/take-and-restore-locality-aware-backups#:~:text=Locality%2Daware%20backups%20allow%20you,locality%20configured%20at%20node%20startup.)) are slightly different from "regions". This feature strips _regions_ from sql descriptors.
2. this is more philosophical: the restore cmd has a contract that all tables must be available to serve writes once the restore command finishes. Currently, an rbr table restored via this command is unavailable for writes. The DR team thinks an unavailable table, even if there is a post restore workaround, is worse than a failed Restore. To that end, the DR team proposes:
  - a quick fix that @dt will comment about in issue
  - if this workaround is a no go, regionless restores that contain an rbr table should fail.

3. since the plan is for this to be backported to 23.1, we should add mixed-version testing

Jira issue: CRDB-31866

### PR DESCRIPTION
**Pull request by annrpom**
### ccl: regionless restores with regional by row table(s) fail fast

Previously, backing up an MR cluster/db/table that had a regional by row table did not work out-of-the-box (users could not write to said table without performing some operations to ensure hidden column added by regional by row enablement, `crdb_region`, and zone config behaved according to the target RESTORE cluster. This was inadequate because we allowed users to perform a RESTORE where some tables were not "available" right away. This patch addresses this by making sure we "fail fast" if users do decide to attempt a RESTORE where the BACKUP object has a regional by row table.

Also: tests. A small amount of tests were fixed to separate the behavior of restoring a database vs a table (just dropping a table after we performed a db restore to test table restore is not a properly isolated test of behavior). Mixed-version tests were added as well.

Epic: CRDB-27601
Informs: #111348

Release note (sql change): Users are not able to perform a `remove_regions` RESTORE if the object being restored contains a regional by row table.

---
### ccl: add 23.2 version gate to regionless restore

This patch adds a >= 23.2 version gate to the `remove_regions`
RESTORE option, in addition to a mixed-version test to ensure
that RESTORE fails fast if it is on a cluster version < 23.2.

Epic: CRDB-27601
Fixes: https://github.com/cockroachdb/cockroach/issues/111348

Release note: None

### CODE REVIEW

**Review by msbutler — APPROVED** [review]
Thanks for doing this!

**Review by msbutler — APPROVED** [review]
LGTM modulo a review from foundations on cross version descriptor checks as we discussed.

**Review by fqazi — APPROVED** [review]
:LGTM: just some minor nits on the commit messages only

The main part of stripping localities should be safe to backport since none of the fields were are stripping are new here.

> Reviewed 4 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111443#-:-NfvCyorCbToGb1K7OBz:bxou6s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @herkolategan, @rafiss, and @renatolabs)

___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111443#-NfvCgno1J3SrXkQx47C):*
This feature hasn't been released yet, so a release note isn't warranted.
___
*[`-- commits` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111443#-NfvCp15-c47Hkk_aGBg):*
23.2
___
*[`-- commits` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111443#-NfvCrHXE05RwZ9AqTtC):*
Again similar to above

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111443)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, @rafiss, and @renatolabs)

___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111443#-NfvCgno1J3SrXkQx47C):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This feature hasn't been released yet, so a release note isn't warranted.
</blockquote></details>

This one is more for docs - a merged PR specified the behavior of this restore option if the object being restored does have a rbr table & this is just here to document that such behavior has changed
___
*[`-- commits` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111443#-NfvCp15-c47Hkk_aGBg):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

23.2
</blockquote></details>

ah rip - thank you
___
*[`-- commits` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111443#-NfvCrHXE05RwZ9AqTtC):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Again similar to above
</blockquote></details>

done!

**Comment by annrpom** [comment]
TFTR! ('-')7 

bors r=msbutler

**Pull request merged**
