### PR TITLE
roachtest: avoid prereleases in MinVersion

### LINKED ISSUE #32250: roachtest: splits/load/uniform/nodes=3 failed
SHA: https://github.com/cockroachdb/cockroach/commits/b01468f592f6b12ba147e1c19ea6d8ad7484ff6e

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stressrace TESTS=splits/load/uniform/nodes=3 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1007980&tab=buildLog

```
The test failed on release-2.1:
	test.go:639,cluster.go:1461,split.go:138,split.go:42: pq: unknown cluster setting 'kv.range_split.by_load_enabled'

```

### PR DESCRIPTION
**Pull request by tbg**
Fixes #32250.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32266#-:-LRCl36d7pYg_1su9XJt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32266#-LRCkqJFAUFIgh_jv3p-:-LRCkqJGAEpZDXePuXNF:b-nvu8rv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e4fb19621b377e0776724a2e762aa9ddd2294e3/pkg/cmd/roachtest/test.go#L279)):*
> ```Go
> 			// Specifying a prerelease version as a MinVersion is too confusing
> 			// to be useful. The comparison is not straightforward.
> 			return fmt.Errorf("invalid version %s, cannot specify a prerelease (-xxx)", spec.minVersion)
> ```

Please add a test case to `TestRegistryPrepareSpec`.

**Review by ridwanmsharif — APPROVED** [review]

**Comment by tbg** [comment]
Fixed a buglet.

bors r=petermattis,ridwanmsharif

**Comment by tbg** [comment]
Flake in Examples-ORMs:

```
docker: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/85/85df28c0821c7ec6c7724ac051be8319466659b2b112784c3c346919a25fdc46/data?verify=1542206176-7DXeNEqPyPEVGFaSo01%2BdigixsU%3D: net/http: TLS handshake timeout.
```

bors r=petermattis,ridwanmsharif

**Comment by tbg** [comment]
```
[16:20:26]
cc -std=gnu11 -Wall -Werror=declaration-after-statement -Wshorten-64-to-32 -Wsign-compare -pipe -g3 -fvisibility=hidden -O3 -funroll-loops -g1 -c -D_GNU_SOURCE -D_REENTRANT -I/go/src/github.com/cockroachdb/cockroach/c-deps/jemalloc/include -Iinclude -o src/prng.o /go/src/github.com/cockroachdb/cockroach/c-deps/jemalloc/src/prng.c
[16:20:26]
The build Unit Tests::testrace #51501 {buildId=1011848} has been running for more than 60 minutes. Terminating...
[16:20:26]
Execution timeout
[16:20:26]
[ 18%] Building CXX object CMakeFiles/cryptopp-object.dir/ripemd.cpp.o
[16:20:26]
cc -std=gnu11 -Wall -Werror=declaration-after-statement -Wshorten-64-to-32 -Wsign-compare -pipe -g3 -fvisibility=hidden -O3 -funroll-loops -g1 -c -D_GNU_SOURCE -D_REENTRANT -I/go/src/github.com/cockroachdb/cockroach/c-deps/jemalloc/include -Iinclude -o src/quarantine.o /go/src/github.com/cockroachdb/cockroach/c-deps/jemalloc/src/quarantine.c
[16:20:26]
[ 19%] Building CXX object CMakeFiles/cryptopp-object.dir/eccrypto.cpp.o
[16:20:27]
Dumping threads before termination:
[16:20:27]
PID: 4943, PPID: 1823, Command line: bash /home/agent/work/.go/src/github.com/cockroachdb/cockroach/build/teamcity-testrace.sh
[16:20:27]
Failed to locate jps tool. No thread dump information is available
[16:20:27]
[16:20:27]
PID: 5574, PPID: 4943, Command line: bash build/builder.sh make -Otarget c-deps GOFLAGS=-race
[16:20:27]
Failed to locate jps tool. No thread dump information is available
[16:20:27]
[16:20:27]
PID: 5599, PPID: 5574, Command line: docker run --init --privileged -i --rm -u 1002:1003 --volume=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/build/builder_home:/home/roach --volume=/home/agent/.yarn-cache:/home/roach/.yarn-cache --volume=/home/agent/system/git/cockroach.git/objects:/home/agent/system/git/cockroach.git/objects --volume=/home/agent/work/.go/src/github.com/cockroachdb/cockroach:/go/src/github.com/cockroachdb/cockroach --volume=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin.docker_amd64:/go/src/github.com/cockroachdb/cockroach/bin --volume=/home/agent/work/.go/docker/bin:/go/bin --volume=/home/agent/work/.go/docker/native:/go/native --volume=/home/agent/work/.go/docker/pkg:/go/pkg --workdir=/go/src/github.com/cockroachdb/cockroach --env=TMPDIR=/go/src/github.com/cockroachdb/cockroach/artifacts --env=PAGER=cat --env=GOTRACEBACK=all --env=COCKROACH_BUILDER_CCACHE --env=COCKROACH_BUILDER_CCACHE_MAXSIZE cockroachdb/builder:20181019-161416 make -Otarget c-deps GOFLAGS=-race
[16:20:27]
Failed to locate jps tool. No thread dump information is available
[16:20:27]
[16:20:27]
cc -std=gnu11 -Wall -Werror=declaration-after-statement -Wshorten-64-to-32 -Wsign-compare -pipe -g3 -fvisibility=hidden -O3 -funroll-loops -g1 -c -D_GNU_SOURCE -D_REENTRANT -I/go/src/github.com/cockroachdb/cockroach/c-deps/jemalloc/include -Iinclude -o src/rtree.o /go/src/github.com/cockroachdb/cockroach/c-deps/jemalloc/src/rtree.c
[16:20:27]
Process exited with code 137
[16:20:27]
Process exited with code 137 (Step: make testrace (Command Line))
[16:20:27]
Step make testrace (Command Line) interrupted
```

Unclear. Never seen this before.

bors r=petermattis,ridwanmsharif

**Pull request merged**
