### PR TITLE
acceptance: infra for mixed version tests

### PR DESCRIPTION
**Pull request by tbg**
Allow tests to specify the binaries they want the nodes to run at. The
version specified for the first node becomes the bootstrap version.

Add a basic test that doesn't do much else than verify the harness does
what's advertised above, but demonstrates what's possible.

Also includes assorted cleanups:

- `cluster.Create{Local->Docker}`
- remove `StoreConfig.Count`
- support `-l` log dir flag in `LocalCluster`
- `{bare->run}Test`

### CODE REVIEW

**Comment by tamird** [comment]
Didn't review the meat of commit 2, assumed it was movement.

:lgtm:

---

Reviewed 9 of 9 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/mixed_version_test.go, line 33 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-Ksfhdw_ozt2gCuBEH6y:-Ksfhdw_ozt2gCuBEH6z:bntm6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/78673f9a628a245f00ab9585127d52d4d6bb2b05/pkg/acceptance/mixed_version_test.go#L33)):*
> ```Go
> 	ctx := context.Background()
> 	cfg := readConfigFromFlags()
> 	RunLocal(t, func(t *testing.T) {
> ```

wrong commit

---

*[pkg/acceptance/util_binary.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfgcnxBthgbm38lZvq:-KsfgcnxBthgbm38lZvr:b-m2bp0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/59056f7d9e95fca0049be49a684eadcd8689d83e/pkg/acceptance/util_binary.go#L41)):*
> ```Go
> 	switch goOs {
> 	case "darwin":
> 		goOs = "darwin-10.9"
> ```

nit: goos and goarch i think are customary

also nit: goos+="-10.9"?

---

*[pkg/acceptance/util_binary.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfgoigQv7p2tzsu5Ab:-KsfgoigQv7p2tzsu5Ac:bppxsjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/59056f7d9e95fca0049be49a684eadcd8689d83e/pkg/acceptance/util_binary.go#L52)):*
> ```Go
> 
> 	v := url.Values{}
> 	v.Add("ci", "true")
> ```

what does this do?

---

*[pkg/acceptance/cluster/dockercluster.go, line 367 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfcVNeo4PRilIbxKKm:-KsfcVNeo4PRilIbxKKn:b1xzu8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/59056f7d9e95fca0049be49a684eadcd8689d83e/pkg/acceptance/cluster/dockercluster.go#L367)):*
> ```Go
> 		}
> 		nodeCount++
> 		var storeCount int
> ```

why is this not just a loop variable? `for i, sc := range nc.Stores`?

---

*[pkg/acceptance/cluster/dockercluster.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfhWAm2v04uGlWP_U8:-KsfhWAm2v04uGlWP_U9:b-m36ybc) ([raw file](https://github.com/cockroachdb/cockroach/blob/78673f9a628a245f00ab9585127d52d4d6bb2b05/pkg/acceptance/cluster/dockercluster.go#L155)):*
> ```Go
> }
> 
> // CreateDocker creates a Docker-based cockroach cluster. The stopper is used to
> ```

this edit is in the wrong commit?

---

*[pkg/acceptance/localcluster/cluster.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfbsRTdyx9UaQTg9Z1:-KsfbsRTdyx9UaQTg9Z2:bbue9nl) ([raw file](https://github.com/cockroachdb/cockroach/blob/59056f7d9e95fca0049be49a684eadcd8689d83e/pkg/acceptance/localcluster/cluster.go#L80)):*
> ```Go
> 	NumNodes    int                // number of nodes in the cluster
> 	DataDir     string             // nodes will use storage DataDir/<i>
> 	LogDir      string             // defaults to DataDir/<i>/logs
> ```

what is `i`? i think you meant to put this comment on the node, not the cluster config.

---

*[pkg/acceptance/zchaos_test.go, line 402 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfcMGDDQVsvLMrnRnm:-KsfcMGE0GU38F230BYo:bpujdt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1baa4fa73d0fe84d1e23db2646088a565fa8e9d/pkg/acceptance/zchaos_test.go#L402)):*
> ```Go
> // The test measures read/write performance in the presence of restarts.
> func TestNodeRestart(t *testing.T) {
> 	s := log.Scope(t)
> ```

?

---

heh, this is restored in the second commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-:-Ksfhn65gyG319Tuc_7y:b-1u7rao)*

**Comment by tschottdorf** [comment]
TFTR! Cleaned up the hot mess that was the commit history.

---

Review status: 4 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/acceptance/mixed_version_test.go, line 33 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-Ksfhdw_ozt2gCuBEH6y:-Ksfwfu70Ba2bWFz8kwI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78673f9a628a245f00ab9585127d52d4d6bb2b05/pkg/acceptance/mixed_version_test.go#L33)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

wrong commit
</blockquote></details>

Done.

---

*[pkg/acceptance/util_binary.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfgcnxBthgbm38lZvq:-Ksfwsz9GOacOdDrbnm2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59056f7d9e95fca0049be49a684eadcd8689d83e/pkg/acceptance/util_binary.go#L41)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: goos and goarch i think are customary

also nit: goos+="-10.9"?
</blockquote></details>

Done.

---

*[pkg/acceptance/util_binary.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfgoigQv7p2tzsu5Ab:-KsfwtdtG0RYhv7pp7fC:b-4fh6t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/59056f7d9e95fca0049be49a684eadcd8689d83e/pkg/acceptance/util_binary.go#L52)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what does this do?
</blockquote></details>

Want to make sure there's a way to distinguish those from "real" downloads. Not sure if we have a standard way for this already. @mberhault?

---

*[pkg/acceptance/cluster/dockercluster.go, line 367 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfcVNeo4PRilIbxKKm:-KsfxLC2lrHSeJHyueQR:b-ej4t9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/59056f7d9e95fca0049be49a684eadcd8689d83e/pkg/acceptance/cluster/dockercluster.go#L367)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why is this not just a loop variable? `for i, sc := range nc.Stores`?
</blockquote></details>

Lots of :poop:, I think I also messed up `nodeCount` in an earlier commit so that it was never incremented? Fixed now.

---

*[pkg/acceptance/cluster/dockercluster.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfhWAm2v04uGlWP_U8:-Ksfx2aU2Y2MiYg4-oWc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78673f9a628a245f00ab9585127d52d4d6bb2b05/pkg/acceptance/cluster/dockercluster.go#L155)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this edit is in the wrong commit?
</blockquote></details>

Done.

---

*[pkg/acceptance/localcluster/cluster.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfbsRTdyx9UaQTg9Z1:-Ksfxc30X9p3bn51ec_x:b9z4kwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/59056f7d9e95fca0049be49a684eadcd8689d83e/pkg/acceptance/localcluster/cluster.go#L80)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what is `i`? i think you meant to put this comment on the node, not the cluster config.
</blockquote></details>

The cluster initializes the default for the node, so I think this is the right place -- made the comment clearer.

---

*[pkg/acceptance/zchaos_test.go, line 402 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfcMGDDQVsvLMrnRnm:-Ksfxxf0dCDjpQIbug7f:bqs4vaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1baa4fa73d0fe84d1e23db2646088a565fa8e9d/pkg/acceptance/zchaos_test.go#L402)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

?

---

heh, this is restored in the second commit.
</blockquote></details>

Done. :see_no_evil: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-:-Ksfy7wBGXhmhC9zhHzx:b-98qu5r)*

**Comment by tamird** [comment]
Reviewed 11 of 11 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/util_binary.go, line 106 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-Ksg-bDt75q7fIFRaxW3:-Ksg-bDuAG2PkgpuCZqv:bypxxt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb728cea9700522a002756067835b37709659698/pkg/acceptance/util_binary.go#L106)):*
> ```Go
> 			base := filepath.Base(header.Name)
> 			if base != "cockroach" {
> 				log.Warningf(ctx, "skipping file %s", header.Name)
> ```

did you mean to actually skip the file?

---

*[pkg/acceptance/util_binary.go, line 109 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-Ksg-wgUCu3DapO9acKo:-Ksg-wgUCu3DapO9acKp:b-h2si2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb728cea9700522a002756067835b37709659698/pkg/acceptance/util_binary.go#L109)):*
> ```Go
> 			}
> 			if _, err := io.Copy(destFile, tarReader); err != nil {
> 				return "", errors.Wrapf(err, "while downloading %s to %s", u, binary)
> ```

"binary" is really far from here; can you make this destFile.Name() or something?

---

*[pkg/acceptance/util_cluster.go, line 15 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-Ksg0ZbjBg0H07PdYOEg:-Ksg0ZbjBg0H07PdYOEh:b5e2h59) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb728cea9700522a002756067835b37709659698/pkg/acceptance/util_cluster.go#L15)):*
> ```Go
> // permissions and limitations under the License.
> 
> package acceptance
> ```

this whole file is in the wrong commit now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/util_binary.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfgoigQv7p2tzsu5Ab:-Ksgwq2CK6_O3xp74psO:bvfbbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/59056f7d9e95fca0049be49a684eadcd8689d83e/pkg/acceptance/util_binary.go#L52)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Want to make sure there's a way to distinguish those from "real" downloads. Not sure if we have a standard way for this already. @mberhault?
</blockquote></details>

we don't look at request parameters, but that could be easily added. It doesn't hurt either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982)*

**Comment by tschottdorf** [comment]
Review status: 6 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/acceptance/util_binary.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-KsfgoigQv7p2tzsu5Ab:-KsiP7kHDXBaRQpKw59K:b-79uymz) ([raw file](https://github.com/cockroachdb/cockroach/blob/59056f7d9e95fca0049be49a684eadcd8689d83e/pkg/acceptance/util_binary.go#L52)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

we don't look at request parameters, but that could be easily added. It doesn't hurt either way.
</blockquote></details>

Ok. I'll leave as-is. Should we filter them out in stats right away? How to go about that?

---

*[pkg/acceptance/util_binary.go, line 106 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-Ksg-bDt75q7fIFRaxW3:-KsiKkP73iXQ1bLDa2LQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb728cea9700522a002756067835b37709659698/pkg/acceptance/util_binary.go#L106)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

did you mean to actually skip the file?
</blockquote></details>

Done.

---

*[pkg/acceptance/util_binary.go, line 109 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-Ksg-wgUCu3DapO9acKo:-KsiL_q9nN_nwmJd1kj8:b65uwi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb728cea9700522a002756067835b37709659698/pkg/acceptance/util_binary.go#L109)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"binary" is really far from here; can you make this destFile.Name() or something?
</blockquote></details>

the variable is used so many times that it makes it awkward to use `destFile.Name()` repeatedly. I renamed `binary` to `destFileName`.

---

*[pkg/acceptance/util_cluster.go, line 15 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-Ksg0ZbjBg0H07PdYOEg:-KsiP6dj89vTPfKo8s5R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb728cea9700522a002756067835b37709659698/pkg/acceptance/util_cluster.go#L15)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this whole file is in the wrong commit now?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r5, 7 of 7 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17982#-:-KsiQEPGcAHANPhMc8ms:bnfp4nl)*

**Pull request merged**
