### PR TITLE
admission: include more work queue info in tracing and errors

### PR DESCRIPTION
**Pull request by aadityasondhi**
See individual commits.

---
admission: inject queue kind into work queue tracing

This patch plumbs down a queue type identifier (`QueueKind`) into the
`WorkQueue` to help track down the origin of items in the queue.

Informs: #113990

Release note: None

---
admission: include work priority in trace and errors

This patch now includes work priority in the `WorkQueue` traces and
error messages to better help track where work items originate from.

Informs #113990.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114664)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`pkg/util/admission/admission.go` line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NjmLTCi5ad7tBX8TA-x:-NjmLTCi5ad7tBX8TA-y:bdf7w5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/97ca2e32878c49d712de3f38aaf416a1f5aaf5fa/pkg/util/admission/admission.go#L553)):*
> ```Go
> 
> const (
> 	KVAdmissionQueue QueueKind = iota
> ```

- Should we just do`type QueueKind string`, since all we care about is the string representation. The indirection just seems to add code.
- We can leave it as the empty string for WorkKinds `SQLKVResponseWork` and `SQLSQLResponseWork` since there is only one queue each for those. Then `work %s deadline expired while waiting in queue: %s` would use the QueueKind if non-empty, else fallback to using the WorkKind.String().
- The strings we need are "kv-regular-cpu-queue", "kv-elastic-cpu-queue", "kv-regular-store-queue", "kv-elastic-store-queue".

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114664)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/util/admission/admission.go` line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NjmLTCi5ad7tBX8TA-x:-NkR4_VI6mCnN1gnE-m0:b-ns008o) ([raw file](https://github.com/cockroachdb/cockroach/blob/97ca2e32878c49d712de3f38aaf416a1f5aaf5fa/pkg/util/admission/admission.go#L553)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

- Should we just do`type QueueKind string`, since all we care about is the string representation. The indirection just seems to add code.
- We can leave it as the empty string for WorkKinds `SQLKVResponseWork` and `SQLSQLResponseWork` since there is only one queue each for those. Then `work %s deadline expired while waiting in queue: %s` would use the QueueKind if non-empty, else fallback to using the WorkKind.String().
- The strings we need are "kv-regular-cpu-queue", "kv-elastic-cpu-queue", "kv-regular-store-queue", "kv-elastic-store-queue".
</blockquote></details>

Done. PTAL

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114664)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`pkg/util/admission/admission.go` line 555 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkSt-ICCEmAtTpdF8P4:-NkSt-ICCEmAtTpdF8P5:b-um3ztz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9032f3fbf6cee61936010580ce68eded60a74004/pkg/util/admission/admission.go#L555)):*
> ```Go
> //
> // It is left empty for SQL types of WorkKind.
> type QueueKind string
> ```

do we need to mark this by implementing `SafeValue` so that it plays well with redaction?
___
*[`pkg/util/admission/work_queue.go` line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkSsKjzDMeqelQSdSU6:-NkSsKk-AtS8HCJzEqz_:btq3ag5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9032f3fbf6cee61936010580ce68eded60a74004/pkg/util/admission/work_queue.go#L380)):*
> ```Go
> 	ambientCtx log.AmbientContext,
> 	workKind WorkKind,
> 	queueKind QueueKind,
> ```

in `initWorkQueue` if the `queueKind` is empty, let's initialize `q.queueKind` to `workKind.String()`. Then we don't need the if-else block when doing the logging and tracing.
___
*[`pkg/util/admission/work_queue.go` line 815 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkSscH05m1uPOOppQeI:-NkSscH05m1uPOOppQeJ:b248yzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9032f3fbf6cee61936010580ce68eded60a74004/pkg/util/admission/work_queue.go#L815)):*
> ```Go
> 		recordAdmissionWorkQueueStats(span, waitDur, q.workKind, q.queueKind, true)
> 		log.Eventf(ctx, "deadline expired, waited in %s queue for %v",
> 			q.workKind, waitDur)
> ```

The `log.Eventf` should also use the queueKind.
___
*[`pkg/util/admission/admissionpb/admission_stats.proto` line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkStFWB4H3WESVIe9NN:-NkStFWB4H3WESVIe9NO:bvdeqbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9032f3fbf6cee61936010580ce68eded60a74004/pkg/util/admission/admissionpb/admission_stats.proto#L23)):*
> ```proto
>   int64 wait_duration_nanos = 1 [(gogoproto.casttype) = "time.Duration"];
>   // String representation of admission work kind.
>   string work_kind = 2;
> ```

we could just rename this as `queue_kind` and use the same tag number. The `queue_kind` subsumes the information provided by `work_kind`.

**Review by aadityasondhi — COMMENTED** [review]
Made the changes PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-:-Nkvzh0O6ok4lO3r3CTj:be4nxf1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/util/admission/admission.go` line 555 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkSt-ICCEmAtTpdF8P4:-NkvzFnJ8GigKss1KpPN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9032f3fbf6cee61936010580ce68eded60a74004/pkg/util/admission/admission.go#L555)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do we need to mark this by implementing `SafeValue` so that it plays well with redaction?
</blockquote></details>

Done.
___
*[`pkg/util/admission/work_queue.go` line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkSsKjzDMeqelQSdSU6:-NkvzNVDA4pyYf9GKLvY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9032f3fbf6cee61936010580ce68eded60a74004/pkg/util/admission/work_queue.go#L380)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

in `initWorkQueue` if the `queueKind` is empty, let's initialize `q.queueKind` to `workKind.String()`. Then we don't need the if-else block when doing the logging and tracing.
</blockquote></details>

Done.
___
*[`pkg/util/admission/work_queue.go` line 815 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkSscH05m1uPOOppQeI:-NkvzaUH4Qp7EAjDkpqC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9032f3fbf6cee61936010580ce68eded60a74004/pkg/util/admission/work_queue.go#L815)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The `log.Eventf` should also use the queueKind.
</blockquote></details>

Done.
___
*[`pkg/util/admission/admissionpb/admission_stats.proto` line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkStFWB4H3WESVIe9NN:-Nkvzch9-PYPACVL_EEX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9032f3fbf6cee61936010580ce68eded60a74004/pkg/util/admission/admissionpb/admission_stats.proto#L23)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we could just rename this as `queue_kind` and use the same tag number. The `queue_kind` subsumes the information provided by `work_kind`.
</blockquote></details>

Done.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114664)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`pkg/util/admission/work_queue.go` line 815 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkSscH05m1uPOOppQeI:-NkwOQpi6t0fMi1qqmPR:b2ev7ni) ([raw file](https://github.com/cockroachdb/cockroach/blob/9032f3fbf6cee61936010580ce68eded60a74004/pkg/util/admission/work_queue.go#L815)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was suggesting the same string as prior to this PR:  "deadline expired, waited in %s queue for %v" with the queueKind. The workKind is always inferrable from the queue kind.
___
*[`pkg/util/admission/work_queue.go` line 850 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkwODPV66J86okqVQ2X:-NkwODPV66J86okqVQ2Y:b-w5zw3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa9b348662cc45352ceefda8e0c40bcfd73f392d/pkg/util/admission/work_queue.go#L850)):*
> ```Go
> 	}
> 	if queueKind == "" {
> 		queueKind = QueueKind(workKind.String())
> ```

why do we need this if WorkQueue.queueKind is always being passed here and it is already initialized?

**Review by aadityasondhi — COMMENTED** [review]
Made the changes requested, PTAL again.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-:-NkxANDe-Pfl81XFv6_y:b-vsrvgx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/util/admission/work_queue.go` line 815 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkSscH05m1uPOOppQeI:-NkwzQIID44nov_0aUWR:b-3wjceo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9032f3fbf6cee61936010580ce68eded60a74004/pkg/util/admission/work_queue.go#L815)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I was suggesting the same string as prior to this PR:  "deadline expired, waited in %s queue for %v" with the queueKind. The workKind is always inferrable from the queue kind.
</blockquote></details>

Ah I miss understood, yeah makes sense.
___
*[`pkg/util/admission/work_queue.go` line 850 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-NkwODPV66J86okqVQ2X:-NkwzI-R3uDm1dJGFEtp:b-8ahc53) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa9b348662cc45352ceefda8e0c40bcfd73f392d/pkg/util/admission/work_queue.go#L850)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why do we need this if WorkQueue.queueKind is always being passed here and it is already initialized?
</blockquote></details>

Sorry, that was me just being hasty. You are right, we always set this in `initWorkQueue`.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-:-Nl-uGtIClYl4yEwivft:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi)

**Review by aadityasondhi — COMMENTED** [review]
TFTR!

bors r=sumeerbhola

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114664#-:-Nl1_Fir7YSlwJRP3Lw_:b-6zs9ju)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Pull request merged**
