### PR TITLE
distsqlpb: rename protos back to distsqlrun

### PR DESCRIPTION
**Pull request by jordanlewis**
The move of code to the `distsqlpb` package also inadvertently renamed
the actual protobuf service endpoints and messages, which represented an
accidental breaking change between 2.1 and 19.1 and would result in
errors in mixed clusters.

This commit reverts that change, restoring harmony for mixed-version
clusters.

This needs a backport and we can't release without that backport.

Touches #36565.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
LGTM though you may want to add a comment because it'll look inviting for someone passing by to "harmonize" the package and directory name again.

**Review by asubiotto — APPROVED** [review]
LGTM. I assume you tested with #36565? I wonder if we could also add a service name unit-test to avoid having to rely on that.

**Comment by jordanlewis** [comment]
Added a comment. I did manual testing to ensure that a mixed-version cluster still works - I think this will be caught by @tbg's roachtest.

TFTR!

bors r+

**Comment by jordanlewis** [comment]
Notice me, bors!

bors r+

**Pull request merged**
