### PR TITLE
ui: more clusterviz map cleanup

### PR DESCRIPTION
**Pull request by couchand**
Just a handful of little cleanups that I noticed while working on #22469.  Mostly moving around which components are responsible for which parts of the logic, which I think makes things more sensible and decreases the number of props that need to be passed around all over the place.

### CODE REVIEW

**Comment by mrtracy** [comment]
That's an :lgtm:. These highly granular commits make it very easy to follow your intent and review.

---

Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 5 of 5 files at r7, 3 of 3 files at r8, 2 of 2 files at r9, 7 of 7 files at r10.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22509#-:-L4qhClHwyktZXxzJgH1:b-7fvx6s)*

**Comment by vilterp** [comment]
Code looks good; I appreciate the small commits.

We also need to think about:
- fixing the flicker on data reload caused by the way we're using the <Loading> component
- using `components` and `containers` directories correctly and getting rid of the `map` directory

**Comment by vilterp** [comment]
K, I think I have a solution to (1) (the flicker) that will apply cleanly on top of this. Will open a PR when you merge this.

**Comment by couchand** [comment]
TFTRs!

@vilterp we've already got cards for both of those 😉 thanks for looking into the flickering.  moving stuff around is a good idea, perhaps it will bug me and i'll do it, but i think i've done enough at the moment and should probably get to actually doing stuff.

**Pull request merged**
