### PR TITLE
workload/schemachange: misc fixes

### PR DESCRIPTION
**Pull request by annrpom**
See individual commits for specific details. This is a group of various workload deflakes

Informs: https://github.com/cockroachdb/cockroach/issues/122249

Release note: None

### CODE REVIEW

**Review by spilchen — APPROVED** [review]
I went through the changes and they all looked good to me.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-:-O25EQWm38MvEiRU0FLs:b5dib1l)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @nameisbhaskar)

**Review by fqazi — APPROVED** [review]
@annrpom Great work! :lgtm_strong: 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-:-O25KOr65QNSajtQLscv:b-e2b2i9)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, and @nameisbhaskar)

___
*[`pkg/workload/schemachange/operation_generator.go` line 1572 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25JskK1Qy8JRvYzKXk:-O25JskK1Qy8JRvYzKXl:b-e8dya6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b50b389eff78c33982d11e81a5a20e8c50e5a7/pkg/workload/schemachange/operation_generator.go#L1572)):*
> ```Go
> 	// us to use, we add an internal crdb_internal_idx_expr prefixed column to
> 	// the table.
> 	stmt.potentialExecErrors.add(pgcode.InvalidColumnReference)
> ```

I think this would be similar to: getUniqueConstraintsForTable and the whole unique constraint logic that detects column references.

**Review by rafiss — CHANGES_REQUESTED** [review]
nice work! i just have a few more nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-:-O25NGL-3nAuM-NOArPV:bkv75it)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, @fqazi, and @nameisbhaskar)

___
*[`pkg/workload/schemachange/operation_generator.go` line 1572 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25JskK1Qy8JRvYzKXk:-O25LbCg-b9qWNdtwXsX:b-lhhmyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b50b389eff78c33982d11e81a5a20e8c50e5a7/pkg/workload/schemachange/operation_generator.go#L1572)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think this would be similar to: getUniqueConstraintsForTable and the whole unique constraint logic that detects column references.
</blockquote></details>

what does it mean if the error is in `potentialExecErrors`? does that mean every DROP COLUMN operattion could fail with this error code, and the workload would not consider that a failure?
___
*[`pkg/workload/schemachange/operation_generator.go` line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25M0945_MsI45agpmd:-O25M0945_MsI45agpme:b-saxh6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/29cb7e99b1ca828dccb91f9a86e5a142c5380d2d/pkg/workload/schemachange/operation_generator.go#L258)):*
> ```Go
> 
> 	def := &tree.ColumnTableDef{
> 		Name: tree.Name(lexbase.EscapeSQLIdent(columnName)),
> ```

interesting, i would have thought that the `Name` should not include the outer double quotes. (in other words, why not use `FmtBareIdentifiers` here?)
___
*[`pkg/workload/schemachange/operation_generator.go` line 304 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25MI8_6xDGyvUBFHoV:-O25MI8_6xDGyvUBFHoW:brmnwk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/29cb7e99b1ca828dccb91f9a86e5a142c5380d2d/pkg/workload/schemachange/operation_generator.go#L304)):*
> ```Go
> 		},
> 	})
> 	op.sql = fmt.Sprintf(`ALTER TABLE %s ADD COLUMN %s`, tableName, tree.AsStringWithFlags(def, tree.FmtBareIdentifiers))
> ```

in this case, i thought we would actually want the double quotes for the column name. could you explain why not (add a comment in the code)?
___
*[`pkg/workload/schemachange/operation_generator.go` line 1094 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25MTDb-KPAfvU1DO1w:-O25MTDb-KPAfvU1DO1x:bpyfhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/29cb7e99b1ca828dccb91f9a86e5a142c5380d2d/pkg/workload/schemachange/operation_generator.go#L1094)):*
> ```Go
> 	}
> 
> 	stmt.sql = tree.AsStringWithFlags(def, tree.FmtBareIdentifiers)
> ```

could you also add a comment in the code why FmtBareIdentifiers is correct here?
___
*[`pkg/workload/schemachange/operation_generator.go` line 1022 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25MjvGCI8eXLxgcr8u:-O25MjvGCI8eXLxgcr8v:bf9linq) ([raw file](https://github.com/cockroachdb/cockroach/blob/243c949cf02538498dda3a4d18d62a364636c91f/pkg/workload/schemachange/operation_generator.go#L1022)):*
> ```Go
> 			// Virtual computed columns are not allowed to be indexed
> 			if columnNames[i].generated && !virtualComputedStored {
> 				isStored, err := og.columnIsStoredComputed(ctx, tx, tableName, columnNames[i].name)
> ```

it looks like `isStored` should actually be named `isStoredComputed`. could you rename the variable?

also, given that, could you explain more why it's correct to set `virtualComputedStored` to true if `isStoredComputed` is true?

actually i'm pretty confused; `virtualComputedStored` sounds like a conflict in terms to me. a computed column can _either_ be `virtual` or `stored`, but not both. see https://www.cockroachlabs.com/docs/stable/computed-columns

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127271)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, @nameisbhaskar, @rafiss, and @spilchen)

___
*[`pkg/workload/schemachange/operation_generator.go` line 1572 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25JskK1Qy8JRvYzKXk:-O26G5g35DSkDenhj2t5:bc16009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6b50b389eff78c33982d11e81a5a20e8c50e5a7/pkg/workload/schemachange/operation_generator.go#L1572)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what does it mean if the error is in `potentialExecErrors`? does that mean every DROP COLUMN operattion could fail with this error code, and the workload would not consider that a failure?
</blockquote></details>

yes -- it's a blanket statement to cover this mode of failure for now until #126967 is resolved
___
*[`pkg/workload/schemachange/operation_generator.go` line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25M0945_MsI45agpmd:-O26GQzW0tnqnC-SM-XC:byrq2m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/29cb7e99b1ca828dccb91f9a86e5a142c5380d2d/pkg/workload/schemachange/operation_generator.go#L258)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

interesting, i would have thought that the `Name` should not include the outer double quotes. (in other words, why not use `FmtBareIdentifiers` here?)
</blockquote></details>

see below
___
*[`pkg/workload/schemachange/operation_generator.go` line 304 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25MI8_6xDGyvUBFHoV:-O26GS2224xsrabD91ur:b-qy7k43) ([raw file](https://github.com/cockroachdb/cockroach/blob/29cb7e99b1ca828dccb91f9a86e5a142c5380d2d/pkg/workload/schemachange/operation_generator.go#L304)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in this case, i thought we would actually want the double quotes for the column name. could you explain why not (add a comment in the code)?
</blockquote></details>

i tried fiddling with the suggestion we spoke offline about, but i think that the problem here might not be coming from randType, but how our ColumnTableDef is formatted

https://github.com/cockroachdb/cockroach/blob/a9af2c7c83534f5b843f0d02e00859df93fe0c12/pkg/sql/sem/tree/name_part.go#L38

https://github.com/cockroachdb/cockroach/blob/1ea9ba643e28caf5ba32c902c8695bcc0593d2b7/pkg/sql/lexbase/encode.go#L68

So I do think applying bare identifiers format will fix the types issue, but I am open to other ways of doing it!

For now, I'll just leave a comment to justify this
___
*[`pkg/workload/schemachange/operation_generator.go` line 1094 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25MTDb-KPAfvU1DO1w:-O268UWJ6l_cm1o_hNYf:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/29cb7e99b1ca828dccb91f9a86e5a142c5380d2d/pkg/workload/schemachange/operation_generator.go#L1094)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you also add a comment in the code why FmtBareIdentifiers is correct here?
</blockquote></details>

done
___
*[`pkg/workload/schemachange/operation_generator.go` line 1022 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-O25MjvGCI8eXLxgcr8u:-O25yifb8_rDoW8qxZda:b9u6lgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/243c949cf02538498dda3a4d18d62a364636c91f/pkg/workload/schemachange/operation_generator.go#L1022)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it looks like `isStored` should actually be named `isStoredComputed`. could you rename the variable?

also, given that, could you explain more why it's correct to set `virtualComputedStored` to true if `isStoredComputed` is true?

actually i'm pretty confused; `virtualComputedStored` sounds like a conflict in terms to me. a computed column can _either_ be `virtual` or `stored`, but not both. see https://www.cockroachlabs.com/docs/stable/computed-columns
</blockquote></details>

sure -- renamed isStored to isStoredComputed

i believe what `virtualComputedStored` is trying to get at is "isstoringVirtualComputed"? or something like that, but essentially this case:

```
CREATE TABLE public.table\_w1\_31 (
...
col7 PG_LSN NOT NULL,
col11 STRING NOT NULL AS (lower(CAST(col7 AS STRING))) VIRTUAL,
...
);

CREATE UNIQUE INDEX index_col2_col13 ON public.table_w1_31 (col2 ASC, col13) STORING (col11);
```

also, right i think with my change, we should actually be calling on `columnIsVirtualComputed`.
thanks for the catch

**Comment by annrpom** [comment]
i have disabled a few other optypes and added their tracking issue


bors r+

**Comment by annrpom** [comment]
ah @rafiss would you like to take another look?

**Review by rafiss — APPROVED** [review]
thanks for finding all these incorrectly handled cases!

unfortunate we had to turn off INSERTs for now. i'll try to look at that next so we can re-enable them

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127271#-:-O3ESphD2z4jApAnIZE-:b2tznnr)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, @nameisbhaskar, and @spilchen)

**Comment by annrpom** [comment]
hopefully it's something simple like formatting, but lmk if that is more involved

tftrs!

bors r+

**Comment by annrpom** [comment]
blathers backport 24.2 24.1 23.2 23.1

**Pull request merged**
