### PR TITLE
sql: release note for ZONECONFIG

### PR DESCRIPTION
**Pull request by knz**
This PR has no code change and exists only to insert a release note.

Release note (security update): the SQL privilege model is extended
with the new ZONECONFIG bit. This can be granted by admin users to
non-admin users on specific SQL objects (databases/tables). When set,
the user gets authorized to modify that object's zone configuration
and decide data placement on specific nodes or groups thereof.

### CODE REVIEW

**Comment by knz** [comment]
@solongordon can you remind us whether a non-admin user can grant ZONECONFIG to other users for objects on which they have GRANT privilege on?

**Comment by solongordon** [comment]
Yes, as it stands a non-admin user with GRANT can grant ZONECONFIG.

**Comment by knz** [comment]
Quoting pg's docs:

> When a non-owner of an object attempts to GRANT privileges on the object, the command will fail outright if the user has no privileges whatsoever on the object. As long as some privilege is available, the command will proceed, but it will grant only those privileges for which the user has grant options. 

I think it's quite important that users with GRANT can only grant privileges that **they already have**. This should be true of ZONECONFIG, and, if you don't mind double-checking, of other privileges as well.

**Comment by solongordon** [comment]
As far as I can tell this is not the case with any privileges right now. I'll open a separate issue about it and ask Product to weigh in.

**Comment by solongordon** [comment]
Opened #45211.

**Comment by aaron-crl** [comment]
How does the backup logic interact with this setting? Is regionally zoned data only backed up to its respective zone?

**Comment by solongordon** [comment]
It's not exactly related to this setting, but the BACKUP command does provide support for "locality-aware" backups. https://www.cockroachlabs.com/docs/stable/backup.html#create-locality-aware-backups

**Comment by aaron-crl** [comment]
> It's not exactly related to this setting, but the BACKUP command does provide support for "locality-aware" backups. https://www.cockroachlabs.com/docs/stable/backup.html#create-locality-aware-backups

Ah, thanks, I conflated replication ZONEs with locality settings. Please disregard.

**Review by RichardJCai — APPROVED** [review]
Thanks for adding the release note, I think we can continue the discussion for GRANTING privileges they don't have in the github issue. https://github.com/cockroachdb/cockroach/issues/45211, LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45201#-:-M0sxr153tMMB1mK2bd3:b-ugsk68)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @RichardJCai, and @solongordon)

**Comment by knz** [comment]
thanks

bors r=RichardJCai

**Pull request merged**
