### PR TITLE
sql: add support for FILTER clause with window functions

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds support for optional FILTER clause for aggregate
window functions.

Incremental change towards: #27100:

Release note (sql change): CockroachDB now supports
optional FILTER clause with aggregates when used as
window functions.

### CODE REVIEW

**Review by knz — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28357)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_plan_window.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOUxOTBYbuGP4OF587:-LJOUxOTBYbuGP4OF588:b-203qee) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/distsql_plan_window.go#L247)):*
> ```Go
> 		funcInProgressSpec.Frame = &frameSpec
> 	}
> 	if funcInProgress.filterColIdx != nil {
> ```

make the field be `int32` not `*int32` and use a special value (-1) to indicate it is not set.
___
*[pkg/sql/window.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOUoCo4L88hsIZeNtU:-LJOUoCo4L88hsIZeNtV:b-f1zr02) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/window.go#L306)):*
> ```Go
> 				tree.SelectExpr{Expr: filterExpr}, types.Bool, s.sourceInfo, s.ivarHelper,
> 				autoGenerateRenderOutputName,
> 			)
> ```

Check the resolved type to be bool here, so you don't have to check at execution time.
___
*[pkg/sql/distsqlrun/processors.proto, line 913 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOV5zO1wnrP-ry1L4W:-LJOV5zO1wnrP-ry1L4X:b-q49okj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/distsqlrun/processors.proto#L913)):*
> ```protobuf
>     optional Frame frame = 5;
>     // Optional index of a column over which filtering of rows will be done.
>     optional uint32 filterColIdx = 6;
> ```

`int32` not `uint32` and use -1 as special value
___
*[pkg/sql/distsqlrun/windower.go, line 560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOVB2T8cQZgt-l5pYm:-LJOVB2UDEiKZXZQR4-S:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/distsqlrun/windower.go#L560)):*
> ```Go
> 	argCount     int
> 	frame        *WindowerSpec_Frame
> 	filterColIdx *int
> ```

ditto
___
*[pkg/sql/logictest/testdata/logic_test/window, line 2278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOVCex-YkTU0OiIMzN:-LJOVCex-YkTU0OiIMzO:b-9r3j29) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/logictest/testdata/logic_test/window#L2278)):*
> ```
> 737.50                 NULL     575.00                 350.00
> 737.50                 NULL     575.00                 150.00
> 737.50                 NULL     500.00                 175.00
> ```

Add examples where the filter has the wrong type.
___
*[pkg/sql/sem/tree/window_funcs.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOVLGmEGTpN0hbbVoq:-LJOVLGmEGTpN0hbbVor:b-lqsv6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/sem/tree/window_funcs.go#L43)):*
> ```Go
> 	StartBoundOffset Datum
> 	EndBoundOffset   Datum
> 	FilterColIdx     *int
> ```

ditto type

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28357)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_plan_window.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOUxOTBYbuGP4OF587:-LJPGMms1VbT-hhPK0zj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/distsql_plan_window.go#L247)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

make the field be `int32` not `*int32` and use a special value (-1) to indicate it is not set.
</blockquote></details>

Done.
___
*[pkg/sql/window.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOUoCo4L88hsIZeNtU:-LJP9DCG8ivT-PTUhCfL:b-9xgqp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/window.go#L306)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Check the resolved type to be bool here, so you don't have to check at execution time.
</blockquote></details>

Great suggestion, done.
___
*[pkg/sql/distsqlrun/processors.proto, line 913 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOV5zO1wnrP-ry1L4W:-LJPAMwGDBsY8wPREDPe:bi7zcpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/distsqlrun/processors.proto#L913)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`int32` not `uint32` and use -1 as special value
</blockquote></details>

Great idea, thanks. Erroneously, I thought that protobuf could only pass around `uint32` and -1 would not have worked.

As a side note: I followed an example from aggregation, maybe we should switch pointers there to value type as well?
___
*[pkg/sql/distsqlrun/windower.go, line 560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOVB2T8cQZgt-l5pYm:-LJPCVvQDKWOFsh_6mFm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/distsqlrun/windower.go#L560)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/window, line 2278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOVCex-YkTU0OiIMzN:-LJPbGGu0ti6gefOz8AZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/logictest/testdata/logic_test/window#L2278)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add examples where the filter has the wrong type.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/window_funcs.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOVLGmEGTpN0hbbVoq:-LJPGKiT0Mey4NBMNGIV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/sem/tree/window_funcs.go#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto type
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: with nit

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-:-LJSbVbC9k7tNYokTNLX:b-xv64lu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/window.go, line 319 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJSbATvCbfgBBs-ZhCw:-LJSbATvCbfgBBs-ZhCx:b2fz1s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d0e3190b531e444d3fa59c973809f9b1eb3c89c/pkg/sql/window.go#L319)):*
> ```Go
> 			}
> 			if renderExpr.ResolvedType() != types.Bool {
> 				return errors.Errorf(
> ```

pgerror.NewErrorf with suitable error code
___
*[pkg/sql/distsqlrun/processors.proto, line 913 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJOV5zO1wnrP-ry1L4W:-LJSbFzq1teG5YL1ATJ_:b-5sclfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2942eb1cb9e1338eccfb375f8e7b5f273b9d097/pkg/sql/distsqlrun/processors.proto#L913)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Great idea, thanks. Erroneously, I thought that protobuf could only pass around `uint32` and -1 would not have worked.

As a side note: I followed an example from aggregation, maybe we should switch pointers there to value type as well?
</blockquote></details>

I don't know; ask Alfonso.

**Review by knz — COMMENTED** [review]
huh sorry :lgtm_cancel: until you explain what's with the CI failure

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-:-LJSbdct-rz9qQwJ46yb:bugyv8z)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
The explanation is simple: I forgot to set special value of -1 in the unit tests (with a pointer `nil` was the default, so I didn't set it explicitly). Now the build should - hopefully - succeed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-:-LJU7Cqk0hLy0bGFlwdf:bbmfnve)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 319 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJSbATvCbfgBBs-ZhCw:-LJU5nwP3FOh2obPHTXY:b-2uipmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d0e3190b531e444d3fa59c973809f9b1eb3c89c/pkg/sql/window.go#L319)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

pgerror.NewErrorf with suitable error code
</blockquote></details>

Done.

However, I wonder when would this error occur? With simple filter expressions, it errors out during type checking; I guess maybe if I had a complex query in the filter (not sure what that would look like).

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-:-LJUcWtE2IQkAMP-Mrm_:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/window.go, line 319 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28357#-LJSbATvCbfgBBs-ZhCw:-LJUc4F_6ZQ6wh-b4-7q:b-xqiqno) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d0e3190b531e444d3fa59c973809f9b1eb3c89c/pkg/sql/window.go#L319)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done.

However, I wonder when would this error occur? With simple filter expressions, it errors out during type checking; I guess maybe if I had a complex query in the filter (not sure what that would look like).
</blockquote></details>

prepared queries with placeholders.

**Comment by yuzefovich** [comment]
Thanks for the review!

bors r+

**Pull request merged**
