### PR TITLE
sql: parser support for GENERATED {ALWAYS | BY DEFAULT} AS IDENTITY syntax

### PR DESCRIPTION
**Pull request by ZhouXing19**
This commit is to allow the parser to support
the `GENERATED {ALWAYS | BY DEFAULT} AS IDENTITY` syntax
under `CREATE TABLE` statement.

Release note (sql change): Added support for `GENERATED {ALWAYS | BY DEFAULT} AS IDENTITY`
syntax in a column definition. This will automatically create
a sequence for the given column.
This matches PostgreSQL syntax and functionality.
See https://www.postgresql.org/docs/current/sql-createtable.html

### CODE REVIEW

**Review by mgartner — CHANGES_REQUESTED** [review]
Great work! I think it's almost there - I left a few minor comments and questions.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-:-MgpyCDTB4TGo2oMzc4l:b-uijn2x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[pkg/sql/parser/testdata/create_table, line 2268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgpxTi-4bOHxhZYNiLx:-MgpxTi-4bOHxhZYNiLy:b7rl3dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/parser/testdata/create_table#L2268)):*
> ```
>   a INT UNIQUE,
>   b INT GENERATED ALWAYS AS IDENTITY,
>   c INT GENERATED BY DEFAULT AS IDENTITY
> ```

nit: add a column with `NOT NULL` and `GENERATED ... AS IDENTITY` to ensure that it is allowed.
___
*[pkg/sql/sem/tree/create.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-Mgpv9rC0pVc3MmMbl2G:-Mgpv9rC0pVc3MmMbl2H:b-a0rcfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L407)):*
> ```Go
> 
> // GeneratedIdentityType represents either GENERATED ALWAYS AS IDENTITY
> // or GENERATED BY DEFAULT AS IDENTITY
> ```

 nit: end comment sentences with a period `.`
___
*[pkg/sql/sem/tree/create.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgpvD1GEyLNiq6oBlwb:-MgpvD1GEyLNiq6oBlwc:b-549yuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L410)):*
> ```Go
> type GeneratedIdentityType int
> 
> // The values of GeneratedIdentity.GeneratedAsIdentityType
> ```

nit: add `.` to the end of the sentence
___
*[pkg/sql/sem/tree/create.go, line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgpxuNg903pVh379hfX:-MgpxuNg903pVh379hfY:b-b2f6pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L553)):*
> ```Go
> 			}
> 			d.GeneratedIdentity.IsGeneratedAsIdentity = true
> 			d.GeneratedIdentity.GeneratedAsIdentityType = GeneratedAlways
> ```

It looks like Postgres automatically marks `GENERATED [ALWAYS | BY DEFAULT] AS IDENTITY` columns as `NOT NULL`. Should we be doing the same?

In Postgres:

```
marcus=# CREATE TABLE t (a INT GENERATED ALWAYS AS IDENTITY);
CREATE TABLE

marcus=# \d t
                            Table "public.t"
 Column |  Type   | Collation | Nullable |           Default
--------+---------+-----------+----------+------------------------------
 a      | integer |           | not null | generated always as identity
````
___
*[pkg/sql/sem/tree/create.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgpwBdXBQ5VP4YTFSS6:-MgpwBdXBQ5VP4YTFSS7:b-grprg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L554)):*
> ```Go
> 			d.GeneratedIdentity.IsGeneratedAsIdentity = true
> 			d.GeneratedIdentity.GeneratedAsIdentityType = GeneratedAlways
> 		case *GeneratedByDefAsIdentity:
> ```

nit: I think there's only 1 line that is different between these two cases, so you could combine them a bit. Up to you.

```
case *GeneratedAlwaysAsIdentity, *GeneratedByDefAsIdentity:
    // Do the error checks...

    d.GeneratedIdentity.IsGeneratedAsIdentity = true
    switch t := c.Qualification.(type) {
    case *GeneratedAlwaysAsIdentity:
        d.GeneratedIdentity.GeneratedAsIdentityType = GeneratedAlways
    case *GeneratedByDefAsIdentity:
        d.GeneratedIdentity.GeneratedAsIdentityType = GeneratedByDefault
    }
```
___
*[pkg/sql/sem/tree/create.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgpvITC-vCA8YQBRHvd:-MgpvITC-vCA8YQBRHve:b-qemtjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L824)):*
> ```Go
> }
> 
> // GeneratedAlwaysAsIdentity represents a column generated always as identity
> ```

nit: `.`
___
*[pkg/sql/sem/tree/create.go, line 827 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgpvJFU8umI3fOzEmPk:-MgpvJFU8umI3fOzEmPl:b-qemtjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L827)):*
> ```Go
> type GeneratedAlwaysAsIdentity struct{}
> 
> // GeneratedByDefAsIdentity represents a column generated by default as identity
> ```

nit: `.`

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68711)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/parser/testdata/create_table, line 2268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgpxTi-4bOHxhZYNiLx:-MgqBODT0YQke7cQybBV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/parser/testdata/create_table#L2268)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add a column with `NOT NULL` and `GENERATED ... AS IDENTITY` to ensure that it is allowed.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/create.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-Mgpv9rC0pVc3MmMbl2G:-MgqBPlaCdw1pV--ElOg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L407)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

 nit: end comment sentences with a period `.`
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/create.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgpvD1GEyLNiq6oBlwb:-MgqBZNA8m05H6hGs5wQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L410)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add `.` to the end of the sentence
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/create.go, line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgpxuNg903pVh379hfX:-MgqBSz_0j9-eK2NepCk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L553)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It looks like Postgres automatically marks `GENERATED [ALWAYS | BY DEFAULT] AS IDENTITY` columns as `NOT NULL`. Should we be doing the same?

In Postgres:

```
marcus=# CREATE TABLE t (a INT GENERATED ALWAYS AS IDENTITY);
CREATE TABLE

marcus=# \d t
                            Table "public.t"
 Column |  Type   | Collation | Nullable |           Default
--------+---------+-----------+----------+------------------------------
 a      | integer |           | not null | generated always as identity
````
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-:-MgqCogh60kqW6A8az_-:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[pkg/sql/sem/tree/create.go, line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgqC2oY86vBzwn2x8oO:-MgqC2oY86vBzwn2x8oP:b-fhp5s6) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L579)):*
> ```Go
> 			d.Nullable.ConstraintName = c.Name
> 		case NullConstraint:
> 			if d.Nullable.Nullability == NotNull || d.GeneratedIdentity.IsGeneratedAsIdentity {
> ```

I think the `|| d.GeneratedIdentity.IsGeneratedAsIdentity` is still needed here because `a INT NULL GENERATED ALWAYS AS IDENTITY` is not allowed, correct? Maybe a test with the order of qualifications switched would catch it, like: `a INT GENERATED ALWAYS AS IDENTITY NULL`.
___
*[pkg/sql/sem/tree/create.go, line 544 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgqCHYuAf9jXfrnQaje:-MgqCHYuAf9jXfrnQajf:b-27nuvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/731df210309d5e54bdf4145b47cf5e17e5b6ebbc/pkg/sql/sem/tree/create.go#L544)):*
> ```Go
> 					"multiple identity specifications for column %q", name)
> 			}
> 			d.GeneratedIdentity.IsGeneratedAsIdentity = true
> ```

super nit: move this after the checks for computed columns and null columns

**Comment by ZhouXing19** [comment]
___
*[pkg/sql/sem/tree/create.go, line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgqC2oY86vBzwn2x8oO:-MgqE_1u0BAvSF1-WolG:b-dyxq3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L579)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think the `|| d.GeneratedIdentity.IsGeneratedAsIdentity` is still needed here because `a INT NULL GENERATED ALWAYS AS IDENTITY` is not allowed, correct? Maybe a test with the order of qualifications switched would catch it, like: `a INT GENERATED ALWAYS AS IDENTITY NULL`.
</blockquote></details>

We've restrict that the a NULL token will raise error if this column has been marked as NOT NULL by other qualification (check [here](https://github.com/cockroachdb/cockroach/blob/731df210309d5e54bdf4145b47cf5e17e5b6ebbc/pkg/sql/sem/tree/create.go#L569-L573)), and we [mark](https://github.com/cockroachdb/cockroach/blob/731df210309d5e54bdf4145b47cf5e17e5b6ebbc/pkg/sql/sem/tree/create.go#L553) a `GeneratedAsIdentity` column as `NOT NULL`. 

So even without `|| d.GeneratedIdentity.IsGeneratedAsIdentity`, I think neither `a INT NULL GENERATED ALWAYS AS IDENTITY` nor `a INT GENERATED ALWAYS AS IDENTITY NULL` will work, right?

**Review by mgartner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-:-MgqLRqa7u57yTDnacKb:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[pkg/sql/sem/tree/create.go, line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68711#-MgqC2oY86vBzwn2x8oO:-MgqLAOm92Oc0Sjl_gkK:b-5bdnkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/29219698f060d648af1835a975e7f0c557a7e88f/pkg/sql/sem/tree/create.go#L579)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

We've restrict that the a NULL token will raise error if this column has been marked as NOT NULL by other qualification (check [here](https://github.com/cockroachdb/cockroach/blob/731df210309d5e54bdf4145b47cf5e17e5b6ebbc/pkg/sql/sem/tree/create.go#L569-L573)), and we [mark](https://github.com/cockroachdb/cockroach/blob/731df210309d5e54bdf4145b47cf5e17e5b6ebbc/pkg/sql/sem/tree/create.go#L553) a `GeneratedAsIdentity` column as `NOT NULL`. 

So even without `|| d.GeneratedIdentity.IsGeneratedAsIdentity`, I think neither `a INT NULL GENERATED ALWAYS AS IDENTITY` nor `a INT GENERATED ALWAYS AS IDENTITY NULL` will work, right?
</blockquote></details>

Oh right! Thanks for adding the tests.

**Pull request merged**
