### PR TITLE
opt: improve functional dependency documentation

### PR DESCRIPTION
**Pull request by andy-kimball**
Improve the descriptions of:

  1. Constant lax and strict functional dependencies.
  2. Lax keys.
  3. Empty keys.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Me likey

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44360#-:-LzNxIW82cEy-uk-UP2x:b-9s4fq9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/props/func_dep.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44360#-LzNwJ6TBARKOs9Dk-hC:-LzNwJ6TBARKOs9Dk-hD:b-s27l7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/096df41a45077651a68acd1740eba9427110446f/pkg/sql/opt/props/func_dep.go#L57)):*
> ```Go
> // are constant:
> //
> //   a1 a2    b  c
> ```

need to mention here somewhere that `A = (a1,a2)` in this example, or better yet just show the fd `()-->(a1,a2)`.
___
*[pkg/sql/opt/props/func_dep.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44360#-LzNwnEj6LZyvA2Hh9A6:-LzNwnEj6LZyvA2Hh9A7:b-w6jopc) ([raw file](https://github.com/cockroachdb/cockroach/blob/096df41a45077651a68acd1740eba9427110446f/pkg/sql/opt/props/func_dep.go#L201)):*
> ```Go
> //   A~~>B
> //
> // In contrast to strict dependencies, lax dependencies treat NULLs as distinct
> ```

treat NULLs on determinant columns

**Review by rytaft — APPROVED** [review]
:lgtm: once you address Radu's comments. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44360#-:-LzbQm8eC97dl58_pdUd:bd65zz1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

**Review by justinj — CHANGES_REQUESTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44360#-:-LzbqWfd6Vl3TUW8K1ya:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[pkg/sql/opt/props/func_dep.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44360#-LzbnoyREo8tcbsC_0yW:-LzbnoyREo8tcbsC_0yX:b-3kcbye) ([raw file](https://github.com/cockroachdb/cockroach/blob/096df41a45077651a68acd1740eba9427110446f/pkg/sql/opt/props/func_dep.go#L311)):*
> ```Go
> //
> // FuncDepSet tracks whether at least one key (whether it be strict or lax)
> // exists for the relation. If this is true, then all possible keys for the
> ```

Consider being more explicit here: if we do not know for sure that there is a key, then the closure containing all columns is insufficient to be a key due to the possibility of duplicate rows. I've confused myself here in the past because it's tempting to define "key" as "closure contains all columns," which works with set semantics but not multiset semantics (as in SQL). Unless this is mentioned somewhere I didn't see?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44360)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/props/func_dep.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44360#-LzNwJ6TBARKOs9Dk-hC:-LzcK4IjAVtPgwN2FwC8:bwplwl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/096df41a45077651a68acd1740eba9427110446f/pkg/sql/opt/props/func_dep.go#L57)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

need to mention here somewhere that `A = (a1,a2)` in this example, or better yet just show the fd `()-->(a1,a2)`.
</blockquote></details>

I added some text at the top, just before my first example. I'll assume the reader sees that pattern (capital letters = sets of columns, lowercase letters = columns), so I can use it later on.
___
*[pkg/sql/opt/props/func_dep.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44360#-LzbnoyREo8tcbsC_0yW:-LzdPqVq4P3twj1KZvSF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/096df41a45077651a68acd1740eba9427110446f/pkg/sql/opt/props/func_dep.go#L311)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Consider being more explicit here: if we do not know for sure that there is a key, then the closure containing all columns is insufficient to be a key due to the possibility of duplicate rows. I've confused myself here in the past because it's tempting to define "key" as "closure contains all columns," which works with set semantics but not multiset semantics (as in SQL). Unless this is mentioned somewhere I didn't see?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44360)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44360#-:-LzgnveYB7J7yFqkxdAx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj)

**Pull request merged**
