### PR TITLE
kvserver: do IO before in-memory Replica creation

### PR DESCRIPTION
**Pull request by pav-kv**
This commit moves the storage IO before newUnloadedReplica invocation. This allows returning early if storage invariants do not hold, and also simplifies error handling and mutex locking when instantiating a Replica.

Touches #93898
Epic: CRDB-220
Release note: none

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
I recommend reviewing with "Hide whitespace changes".

**Review by tbg — APPROVED** [review]
Nice!

**Comment by pavelkalinnikov** [comment]
bors r=tbg

**Comment by pavelkalinnikov** [comment]
bors retry

**Comment by pavelkalinnikov** [comment]
Caught another pre-existing failure: #95286

**Comment by pavelkalinnikov** [comment]
bors retry

**Pull request merged**
