### PR TITLE
storageccl: add azure store support

### PR DESCRIPTION
**Pull request by dt**
originally authored by mjibson on the backup branch but lost in the first cherry-pick of cloud ExportStorage providers until the azure libs could be added to vendor.

Changes in glide.lock since HEAD~
Added:
 - github.com/Azure/azure-sdk-for-go
Changed:
 - cloud.google.com/go: 5c2083b3 -> 493be1e0
   - https://github.com/GoogleCloudPlatform/google-cloud-go/compare/5c2083b3...493be1e0

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13520)

### CODE REVIEW

**Comment by danhhz** [comment]
sciencedog on the details of the azure api, but lgtm

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup_test.go, line 242 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13520#-KcZSqdF5r279yN88EIa:-KcZSqdF5r279yN88EIb:bfb8cac) ([raw file](https://github.com/cockroachdb/cockroach/blob/988589c32d75b076fa0aa8ffe486941af73d3279/pkg/ccl/sqlccl/backup_test.go#L242)):*
> ```Go
> }
> 
> func TestBackupRestoreAzure(t *testing.T) {
> ```

Add a function level comment here similar to the s3/gcs ones

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13520#-:-KcZTaFzOvyDgPD5-cUD:b7v5mgz)*

**Comment by mjibson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/export_storage.go, line 621 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13520#-Kc_hCdqJUrxT7A-CKeI:-Kc_hCdqJUrxT7A-CKeJ:b-3h2e0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/988589c32d75b076fa0aa8ffe486941af73d3279/pkg/ccl/storageccl/export_storage.go#L621)):*
> ```Go
> 	var blocks []azr.Block
> 	i := 1
> 	if err := chunkReader(f, fourMiB, func(b []byte) error {
> ```

Can we put a SSTable > 4MB in a test so we can verify that this function works correctly? I'm ok adding a TODO instead for that if you want to merge this as is since it's a nice cherry pick.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13520)*

**Comment by dt** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup_test.go, line 242 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13520#-KcZSqdF5r279yN88EIa:-Kcsg1hYCgHIbGIutQLB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/988589c32d75b076fa0aa8ffe486941af73d3279/pkg/ccl/sqlccl/backup_test.go#L242)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Add a function level comment here similar to the s3/gcs ones
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/export_storage.go, line 621 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13520#-Kc_hCdqJUrxT7A-CKeI:-Kcsg3gPT8wMeY9Y1qND:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/988589c32d75b076fa0aa8ffe486941af73d3279/pkg/ccl/storageccl/export_storage.go#L621)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Can we put a SSTable > 4MB in a test so we can verify that this function works correctly? I'm ok adding a TODO instead for that if you want to merge this as is since it's a nice cherry pick.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13520)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13520#-:-KcskGsHUdOtZv58EtLJ:bnfp4nl)*

**Pull request merged**
