### PR TITLE
kv: perform range lookups optimistically on followers

### LINKED ISSUE #91432: kv: look up range descriptors from followers
**Is your feature request related to a problem? Please describe.**
We should be able to warm the range descriptor cache from followers. Range descriptors change relatively slowly, and particularly in the case where we do not have any knowledge of where a range is located, we should be able to use followers to bootstrap the information.

This comes up in the context of server cold start.

**Describe the solution you'd like**
We ought to be able to followers to serve at least the initial request for range descriptors.

**Additional context**

Some discussion internally [here](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1667839442101949).

Epic: CRDB-18596

Jira issue: CRDB-21258

### PR DESCRIPTION
**Pull request by ajwerner**
This change exposes the choice of consistency level to the `RangeDescriptorDB`,
and to ensure that the `kv.RangeLookup` code sets the `RoutingPolicy`
appropriately.

The change adopts the INCONSISTENT consistency level in the `RangeCache` when
performing lookups. The commentary in the change explains the logic. The gist
is that we're going to first try to read from a follower, and, when we know
the result we read is too stale, we'll try again from the leaseholder.

One short-coming of this approach is that we won't get intents on the
optimistic reads. The reason we don't is because the INCONSISTENT
ReadConsistencyType won't return intents.

Fixes https://github.com/cockroachdb/cockroach/issues/91432

#### kvclient: make EvictionToken contract more strict

We should only pass an eviction token which corresponds to the key being looked
up. Prior to this change, there was a scenario when iterating whereby we'd pass
the eviction token from the previous range. It's possible in some cases this
might have helped to pipeline lookups in the case of rapid splits. Hopefully
the work to do optimistic follower lookups will make any of that moot.

Release note (performance improvement): In some cases, the key-value store client needs to look up where to send requests. Prior to this change, such lookup requests were always routed to the leaseholder of the metadata range storing that information. Now the client can attempt to look up this metadata from followers. This can improve tail latency in multi-region clusters in cases where the range addressing cache is cold.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91638)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NGZRHth4T-pCH0t0hFO:-NGZRHth4T-pCH0t0hFP:b-5lpzwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6803689aa85b6805b87be0bbf798ae9bbbda22/pkg/kv/kvclient/rangecache/range_cache.go#L86)):*
> ```Go
> 	// ReadFromLeaseholder is the RangeLookupConsistency used to read from the
> 	// leaseholder.
> 	ReadFromLeaseholder = roachpb.READ_UNCOMMITTED
> ```

We made an attempt at decomposing the notions of consistency and isolation when introducing bounded staleness. In that work, we introduced a `RoutingPolicy` field on the BatchRequest header and then also the `BoundedStaleness` specification. I wonder if we can avoid introducing some of these new concepts by extending the bounded staleness consistency level to support a `READ_UNCOMMITTED` isolation level.

I think the way that this would work is that bounded staleness negotiation would be extended to support `READ_UNCOMMITTED`. This would instruct the negotiation phase (see `executeServerSideBoundedStalenessNegotiation`) to ignore intents when computing the timestamp to run the rest of the operation. For a single-range bounded staleness request, this would mean `resolved_timestamp = closed_timestamp`. The scan would then evaluate at this timestamp, obeying the existing rules for `READ_UNCOMMITTED` requests.

If we made such a change, then it may allow us to further clean up the confusing `ReadConsistencyType` spectrum. We could first rename it to `ReadIsolationLevel`. We would then replace `CONSISTENT` with `SNAPSHOT`. Finally, `INCONSISTENT` would go away. All existing use cases of it would perform `READ_UNCOMMITTED` reads with (un)-bounded staleness and a `NEAREST` routing policy. Or we could keep `INCONSISTENT` if reading above the closed timestamp is important, but we'd move it into its own consistency spectrum of [`INCONSISTENT`, `BOUNDED_STALENESS`, `CONSISTENT`].

If I squint, that's close to what you're trying to introduce here, except you're having to introduce a new `ReadConsistencyType` because consistency and isolation are still jumbled in that enum. `STALE_READ_UNCOMMITTED` is equivalent to a `ReadIsolationLevel` of `READ_UNCOMMITTED` and a `ReadConsistencyLevel` of `INCONSISTENT`.

**Comment by ajwerner** [comment]
That's fine. That's nice cleanup. Do you have any concerns about the mechanics of the change? Part of it feels a little implicit and magical reliance on some action at a distance. I can take a stab at reworking the interfaces to either decouple it more or more tightly seal the coupling between rangecache behavior and the distsender. 

Do you have correctness or liveness concerns?

**Comment by ajwerner** [comment]
Mulling this a bit more, I like what you're getting at regarding decomposing isolation from consistency. I think the question to consider is whether we actually want to put the closed timestamp into play? 

It feels like there's sort of three dimensions:
1) Can the request be evaluated on a follower?
2) If yes, what data should be read? Should it be a stale snapshot or an inconsistent read?
3) Should intents be returned?

I think the current hodge-podge of an enum is providing a desirable answer: (yes, inconsistent latest, yes). 

As you've laid out a path, it does not seem obvious that this would be supported. I think if I had no choice between 2 and 3, my hunch is that a more fresh view is more important than seeing the intent. A lot of changes can happen in 3s.

**Review by nvb — COMMENTED** [review]
It sounds like we're in rough agreement about what these requests should look like (nearest, inconsistent, read_uncommitted), so we can table that part of the discussion for now.

> Do you have any concerns about the mechanics of the change? Part of it feels a little implicit and magical reliance on some action at a distance. I can take a stab at reworking the interfaces to either decouple it more or more tightly seal the coupling between rangecache behavior and the distsender.

At a high level, I think this approach is sound. We use descriptor generations as a form of domain-specific bounded staleness built on top of inconsistent reads and then ensure forward progress from there.

My primary concern is that it promotes an optional optimization (passing in an EvictionToken) into a required component of correctness, and in a subtle way. We can't rely on the local follower ever receiving the updated descriptor because it may have been removed from the range and just doesn't know yet (or its replication stream paused, etc.), so we need to ensure that in all cases, there's some way to detect staleness from a prior iteration and then retain that context through to the next lookup so that we route to the leaseholder. That may already be the case today, but code like the  `RangeIterator` case casts some doubts.

I'm also curious whether you see any issues with this approach when recursing up the meta tree. Would anything bad happen if our meta1 follower was badly out of date?

> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-:-NGbjSR38xKZ2N7TWQhP:blmhexy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 622 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NGbfGeoB_Rw1a8UK4jv:-NGbfGeoB_Rw1a8UK4jw:b-c41bfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6803689aa85b6805b87be0bbf798ae9bbbda22/pkg/kv/kvclient/rangecache/range_cache.go#L622)):*
> ```Go
> // This method is called with a non-zero evictToken in two cases:
> //
> //  1. When iterating through a range iterator, it is called with a token
> ```

I wasn't aware that we did this. Do you know whether it is intentional? It seems mildly problematic that a singleflight group pointing at key "a" can refer to a lookup in "a"'s range and also a lookup in "a"'s RHS neighbors range.

**Review by ajwerner — COMMENTED** [review]
> We use descriptor generations as a form of domain-specific bounded staleness built on top of inconsistent reads and then ensure forward progress from there.

Precisely. I can add more commentary around that fact.

> My primary concern is that it promotes an optional optimization (passing in an EvictionToken) into a required component of correctness, and in a subtle way. We can't rely on the local follower ever receiving the updated descriptor because it may have been removed from the range and just doesn't know yet (or its replication stream paused, etc.), so we need to ensure that in all cases, there's some way to detect staleness from a prior iteration and then retain that context through to the next lookup so that we route to the leaseholder. That may already be the case today, but code like the RangeIterator case casts some doubts.

Yeah, this makes me uneasy too. My impression is that the best thing to do is to rework the symbols in the RangeCache to make the contracts more explicit. I think the singleflight behavior of the range iterator is an accident that works out most of the time, but it should be handled differently. 

>I'm also curious whether you see any issues with this approach when recursing up the meta tree. Would anything bad happen if our meta1 follower was badly out of date?

Is there a hazard that's on your mind? I think any failures to read from meta2 will get handled appropriately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-:-NGbp6E-ECqEK6wtu0Ja:ba3rr7s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 622 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NGbfGeoB_Rw1a8UK4jv:-NGbotAJ2n2eSRAxrzkV:ben23p2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6803689aa85b6805b87be0bbf798ae9bbbda22/pkg/kv/kvclient/rangecache/range_cache.go#L622)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I wasn't aware that we did this. Do you know whether it is intentional? It seems mildly problematic that a singleflight group pointing at key "a" can refer to a lookup in "a"'s range and also a lookup in "a"'s RHS neighbors range. 
</blockquote></details>

It's definitely not ideal. We'll end up retrying if it happens because of the retry loop and the bounds check.

**Comment by ajwerner** [comment]
@nvanbenschoten I simplified this for a first pass. I'll follow-up with a later PR to tame the consistency/isolation story as we discussed. Let me know what other testing scenarios interest you. I started down a path towards a datadriven test but it got too fiddly to construct the requests and responses so I walked back towards this testing approach.

**Comment by ajwerner** [comment]
@nvanbenschoten gentle nudge. I'd like to get something here merged before thanksgiving if this isn't too offensive. The flake is unrelated.

**Review by nvb — COMMENTED** [review]
> Reviewed 11 of 12 files at r2, 10 of 12 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91638)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/kv/kvclient/kvcoord/range_iter.go` line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NH5Ig7A2S9cBaNGy68E:-NH5Ig7A2S9cBaNGy68F:b-jj2hzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3510cb083c61d83830fd313253d69a562a360275/pkg/kv/kvclient/kvcoord/range_iter.go#L201)):*
> ```Go
> 		var rngInfo rangecache.EvictionToken
> 		rngInfo, err = ri.ds.getRoutingInfo(
> 			ctx, ri.key, rangecache.EvictionToken{}, ri.scanDir == Descending,
> ```

Do you mind adding a comment here that mentions that we aren't passing in an eviction token because the only one we have is for the previous range?
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 624 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NH5L2I715XupNUaMM0i:-NH5L2I715XupNUaMM0j:boc096t) ([raw file](https://github.com/cockroachdb/cockroach/blob/657f4603bb9d393866b2f7236409218cb1bcbf87/pkg/kv/kvclient/rangecache/range_cache.go#L624)):*
> ```Go
> // returned from (*DistSender).sendToReplicas. In this case, the eviction
> // token from the previous iteration of the sendPartialBatch loop (the one
> // that failed) is provided. In this case, the method willl ensure that the
> ```

"willl"
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 803 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NH5LJ0C96OMwT9UyLoo:-NH5LJ0C96OMwT9UyLop:bd3qwfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/657f4603bb9d393866b2f7236409218cb1bcbf87/pkg/kv/kvclient/rangecache/range_cache.go#L803)):*
> ```Go
> 			// result is too old for the leader of this group, then we'll fall back
> 			// to reading from the leaseholder. Note that it's possible that the
> 			// leader will have no freshness constraints on its view of the range
> ```

"singleflight leader", to avoid ambiguity.
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 882 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NH5MFWx7PPueN8mpBnR:-NH5MFWx7PPueN8mpBnS:biyzhzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/657f4603bb9d393866b2f7236409218cb1bcbf87/pkg/kv/kvclient/rangecache/range_cache.go#L882)):*
> ```Go
> 		// have exhausted sending to the replicas at the generation in our
> 		// EvictionToken.
> 		(res.Shared && lookupResultIsStale(lookupRes)) {
> ```

How will this behave in the case where a stale committed descriptor is returned and a new intent descriptor is returned? Ideally, we'd want to immediately step to the intent. As written, will this spin until the intent is resolved? Are we only not seeing that problem because of the `res.Shared` condition?
___
*[`pkg/kv/kvclient/kvcoord/testdata/rangelookups/basic` line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NH5MzRqC47n7q6d4lrx:-NH5MzRqC47n7q6d4lry:bxqw1h0) ([raw file](https://github.com/cockroachdb/cockroach/blob/657f4603bb9d393866b2f7236409218cb1bcbf87/pkg/kv/kvclient/kvcoord/testdata/rangelookups/basic#L1)):*
> ```
> send-get key=a
> ```

Where is the harness for this datadriven test? Was that ripped out? If so, should we delete this file?

**Review by ajwerner — COMMENTED** [review]
TFTR! RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-:-NH6RRZZAFd9OZTQgnsW:b-qoyhu5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/range_iter.go` line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NH5Ig7A2S9cBaNGy68E:-NH5R3D73HjnB1fRYhrz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3510cb083c61d83830fd313253d69a562a360275/pkg/kv/kvclient/kvcoord/range_iter.go#L201)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you mind adding a comment here that mentions that we aren't passing in an eviction token because the only one we have is for the previous range?
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 624 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NH5L2I715XupNUaMM0i:-NH5R7ZRA2qZ2CILNpHd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/657f4603bb9d393866b2f7236409218cb1bcbf87/pkg/kv/kvclient/rangecache/range_cache.go#L624)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"willl"
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 803 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NH5LJ0C96OMwT9UyLoo:-NH5Rc-_5PJkd1-4q28H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/657f4603bb9d393866b2f7236409218cb1bcbf87/pkg/kv/kvclient/rangecache/range_cache.go#L803)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"singleflight leader", to avoid ambiguity.
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 882 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NH5MFWx7PPueN8mpBnR:-NH5RfwZCxSUnRZS4oN_:b-vnd29u) ([raw file](https://github.com/cockroachdb/cockroach/blob/657f4603bb9d393866b2f7236409218cb1bcbf87/pkg/kv/kvclient/rangecache/range_cache.go#L882)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How will this behave in the case where a stale committed descriptor is returned and a new intent descriptor is returned? Ideally, we'd want to immediately step to the intent. As written, will this spin until the intent is resolved? Are we only not seeing that problem because of the `res.Shared` condition?
</blockquote></details>

I've been chewing on this throughout the day. It feels to me like the best thing to do is to track whether the lookup was optimistic and only retry if it's stale and it's optimistic. I tried to do something about stepping right to the intent but it started to get more complex than I was ready for. I changed the logic to only retry if the lookup which is too stale was from a follower. This is no worse than where we were before this change.
___
*[`pkg/kv/kvclient/kvcoord/testdata/rangelookups/basic` line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-NH5MzRqC47n7q6d4lrx:-NH6RMIA492WwkNLJGgh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/657f4603bb9d393866b2f7236409218cb1bcbf87/pkg/kv/kvclient/kvcoord/testdata/rangelookups/basic#L1)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Where is the harness for this datadriven test? Was that ripped out? If so, should we delete this file?
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r6, 1 of 1 files at r7, 10 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91638#-:-NH6a44P-rJAQW8eqBOz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Pull request merged**
