### PR TITLE
rfcs: draft cluster-to-cluster streaming replication RFC

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Comment by shermanCRL** [comment]
A few thoughts in no particular order.

- In the case of a presumably-temporary network partition between primary and secondary, changes will accumulate, perhaps unbounded, on the primary, yes? Seems similar to the buffering concerns on the secondary. Or, do we protect timestamps on the primary during the partition?

- I infer that each secondary will require its own unique stream, yes? Can a new secondary get backfill by any other means?

- It might be helpful to see some proposed syntax. (Maybe out of scope on this doc.)

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56932)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @HonoreDB, @miretskiy, and @pbardea)

___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqz67Q5dJW2GDR1Cfq:-MMqz67Q5dJW2GDR1Cfr:b-83s0q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L19)):*
> ```Markdown
> ## Motivation
> 
> Cluster-to-cluster replication or "streaming backup/restore" is an often requested feature, particularly for primary/secondary deployments. In such deployments the secondary would provide an option of **rapid failover** (RTO) compared to waiting for a full RESTORE, as well as **minimal data loss** (RPO), compared to taking periodic backups.
> ```

Can you provide an estimate of the target recovery point/time for this design? 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqKhh177JrAmYWsG-F:-MMqKhh177JrAmYWsG-G:b-yewbkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L44)):*
> ```Markdown
> Additionally, most applications interact with multiple tables at once, and may rely on transactions across them being consistent. To be a drop-in replacement, to which that application could cut over, a secondary standby cluster needs to have all the tables, consistent with each other, as well as the cluster's configuration: the same users, granted the same privileges, configured with the same settings, etc.
> 
> Thus, in most deployments, the span that makes the most sense to replicate is that which encapsulates all the table data and all the metadata. Given the metadata is stored in system tables, this is the entire SQL table key-span.
> ```

Is "the span" necessarily singular, or could there be multiple non-contiguous spans? (i.e. would the non-contiguous spans pose any difficulties for syncing things up at the end)  I see you're mostly using the singular here (except for the first sentence in this section), but it's unclear whether that's a hard requirement or if a single span just turned out to be the most useful. 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqLXDIBINmp7PUgjVq:-MMqLXDIBINmp7PUgjVr:bnfww6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L83)):*
> ```Markdown
> Whereas the previous paradigm, of online host clusters replicating offline guest tenants, might be compared to or thought of in terms of OS virtualization and moving and resuming guest image snapshots, this pattern is conceptually more similar to booting a computer to a separate recovery or maintenance partition, from which one can then act on, upgrade or alter the OS installed on the main or root partition while it is safely offline.
> 
> While there will certainly be subtleties to resolve in this configuration that will be addressed in its own design document, this approach should be able to utilize the same stream format, job, helpers, producer/ingestion components, etc as steaming a tenant. Other than being run in a cluster that is booted in this special mode, wherein it stores its SQL state within a special prefix, the rest of the process is the same -- it just is streaming the whole SQL key span of the source cluster, rather than the key-span of a tenant within it.
> ```

Which use cases are covered by this design doc? The title says "cluster-to-cluster" but this paragraph sounds like we're just doing tenant-to-tenant (and maybe cluster-to-tenant?) first. 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqOUsD0ZXDSy18VylQ:-MMqOUsD0ZXDSy18VylR:bqf8ht7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L124)):*
> ```Markdown
> Operators may wish to stream directly between clusters, either to reduce operational complexity and costs by eliminating the need to have an external storage intermediary or to minimize latency associated with buffering and flushing to storage.
> 
> To stream directly between clusters, nodes in the producing cluster can allocate "outboxes" or fixed size buffers of emitted stream entries. It can then provide the addresses of these outboxes and expose them via an API so that the consuming cluster can dial them directly to fetch their contents. A consumer connected to a given outbox could hold its connection open and receive emitted events with minimal latency.
> ```

So this is basically introducing a "pull" model to CDC in contrast to the current "push" model, right?

What happens when these outboxes reach their maximum size? 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqQ1jG73AvtFr7c-LW:-MMqQ1jG73AvtFr7c-LX:bbpw2lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L133)):*
> ```Markdown
> The intermediary buffer can be considered like a file-system, such as S3. In this case, the stream client needs to provide a stream of changes on a per-generation basis, as well as the ability to start emitting changes from a particular timestamp. The streaming client should be able to determine the topology of a generation efficiently based on the files in the buffer.
> 
> The proposed format for the files produced by a stream is:
> ```

We should think about garbage collection policies here. If I only want to keep X hours of stream logs, which files are safe to delete? 

For example, should the timestamp prefix come before partition ID? 

If the latest generation ID is more than X hours old am I guaranteed safe to delete everything from all past generations, or could some fresher data still need to be retained in the previous generation?

How disruptive is a generation rollover? If it's not disruptive, forcing a periodic generation change could make this easier. (and if it is disruptive, could generation changes put strict RPO objectives in jeopardy?)
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqSp9D7zIZl7YSqug7:-MMqSp9D7zIZl7YSqug8:bs0wvu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L133)):*
> ```Markdown
> The intermediary buffer can be considered like a file-system, such as S3. In this case, the stream client needs to provide a stream of changes on a per-generation basis, as well as the ability to start emitting changes from a particular timestamp. The streaming client should be able to determine the topology of a generation efficiently based on the files in the buffer.
> 
> The proposed format for the files produced by a stream is:
> ```

How similar/different is this to the scheme used for CDC HTTP sinks? 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqSdFWDPsqlCq7U4_Q:-MMqSdFWDPsqlCq7U4_R:b-h6ta1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L135)):*
> ```Markdown
> The proposed format for the files produced by a stream is:
> 
> `<cluster_id>/<generation_id>/TOPOLOGY`: Describes the number and locations of the partitions for this generation.
> ```

Which node is responsible for writing the topology file for a new generation?
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMr0qItC6Qd3rBnBRwp:-MMr0qItC6Qd3rBnBRwq:b-xps2s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L218)):*
> ```Markdown
> Both approaches may experience spikes in utilization of storage resources if one or more partitions falls far behind.
> 
> In the case of buffered ingestion, the partitions that are caught up will need to buffer the data they cannot yet flush to disk. Although these partitions will be writing to the on-disk buffer rather than the main store, the write load on the standby cluster will mirror that of the source cluster. When the lagging partition catches up to the resolved timestamp, a large storage spike is expected in flushing all of the buffered data to the main store. In summary, these storage utilization spikes are expected whenever we catch up on a stream that has fallen behind.
> ```

These spikes also imply spikes in the RP+RT if a failure were to occur at that moment. Direct ingestion should be smoother and keep the RP closer to the resolved timestamps. 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMr0WWJ312OQAHm9UQ5:-MMr0WWJ312OQAHm9UQ6:b-me60wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L222)):*
> ```Markdown
> In the case of direct ingestion and rollback, during the rollback phase, a spike in storage resources is expected. In order to rollback, RevertRange needs to locate the SSTs which contain relevant data and perform point deletes over all values which have changed since the rollback time. Before the cut-over, all of the data received by the standby cluster will be ingested identically to the source cluster. Although this spike is only expected to occur once, _it will occur at a critical time for the user_: when they are cutting over to the standby cluster.
> 
> With either approach, in order to properly support a partition falling arbitrarily behind, it is important to ensure that appropriate back pressure systems are in place to avoid overloading the storage layer, regardless of when the spike is expected to occur.
> ```

What sort of backpressure are you thinking here? 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqvnbd-V7lQqLh9K4a:-MMqvnbd-V7lQqLh9K4b:b-wdnjm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L229)):*
> ```Markdown
> With the buffering solution, performing a cut-over should be a constant time operation since it has only ingested data that is known to be consistent, as long as all buffers have had a chance to flush.
> 
> Rolling back to the low-water mark time with the direct ingestion approach is potentially a function of how far behind one stream is. Notably, this means that the **RTO will be a function of the RPO**. However, this makes observability into how far behind each stream all the more critical so that the operator can ensure that the streams don’t fall too far behind.
> ```

Nit/peeve: Remove the 'O's: The recovery time will be a function of the recovery point (whether that RP is within its Objective or not). 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqzoypBT6oKZ-hGCen:-MMqzoypBT6oKZ-hGCeo:b-y9mofq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L232)):*
> ```Markdown
> 
> 
> ##### Tradeoff: Node Failure Relisancy
> ```

Resiliency
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMr-31p867gI4JUCAe4:-MMr-31p867gI4JUCAe5:b-qhwfm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L236)):*
> ```Markdown
> Since these ingestion jobs are expected to be very long running, they should be resilient to node failures. This failure mode is fairly well handled by the direct ingestion approach since all ingested data is already replicated and low-watermark calculations can be based off of ingested data. Recovery looks like restarting the ingestion job from the latest low-watermark resolved timestamp.
> 
> However, the node failure case is more interesting when considering the buffered ingestion implementation. As previously mentioned, since flushing is not atomic, during a flush there will be some time where the ingested data is not in a consistent state. If a cut-over were to happen at this time, we would need to wait for all nodes to finish flushing. However, if a node were to become unavailable, the nodes that have flushed need to rollback to the last timestamp at which all partitions successfully flushed. **This leads to the realization that to fully support the buffering ingestion implementation we'll need to be able to support running a RevertRange in any case.**
> ```

If we were streaming to/from files instead of directly cluster-to-cluster, we could roll forward instead of backward. If we initiated a flush, we know that all of the data up to the next resolved timestamp is available, so a restarted job could pick up from their and complete the process (assuming the KV writes here are idempotent). So that's one option for a RevertRange-free mode of operation, although I don't think it's worth making the intermediate files mandatory. 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMr2I8T6Yr_J0FhbpJU:-MMr2I8T6Yr_J0FhbpJV:bqae3z3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L252)):*
> ```Markdown
> Given the motivation for cluster-to-cluster replication is to have a warm standby cluster, it seems likely that minimizing ongoing cost at the expense of cutover time is not the preferred trade, and instead it would be preferable to pay the extra write-amplification as we go to minimize RTO. It offers benefits such as no resource utilization spike during cut over and constant RTO in the happy case of no node-failures.  However, given the non-atomic nature of the flush across nodes, and the fact it still needs to support rolling back partial flushes, the buffered approach is actually a superset of the direct-ingest approach, and the buffering is just an optimization.
> 
> Thus the *proposed approach is start with the direct-ingestion approach with rollback* and pursue buffering as an optimization later.
> ```

:thumbsup: 

When buffering is just an optimization, some other points in the design space become available. For example, instead of spilling to disk to ensure sufficient buffer capacity (and paying the associated write-amp), we could flush (inconsistent) data whenever we run out of memory and rely on the revert to clean it up if necessary. 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMr2k3DDjXOZmv6_vo8:-MMr2k3DDjXOZmv6_vo9:b-txgyo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L256)):*
> ```Markdown
> **Observability Considerations**
> 
> It is important to provide metrics for monitoring the health of the replicating stream. Important metrics include:
> ```

Note that many metrics need to be collected on both the source and target clusters (especially for the case when we're streaming to/from files). 
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMr31Fj7SAQ8_88cEgS:-MMr31Fj7SAQ8_88cEgT:bihdei8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L257)):*
> ```Markdown
> 
> It is important to provide metrics for monitoring the health of the replicating stream. Important metrics include:
> - RPO: how far back is the latest ingested timestamp? This is the timestamp we would rollback to on cut-over.
> ```

Metrics
- Size of buffered logs/outboxes
- Age of current generation

Non-metric observability: When RPO increases, we need to be able to see which range(s)/node(s) are keeping timestamps from closing/resolving.
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMr3zFE31nmDSZf9I42:-MMr3zFE31nmDSZf9I43:bo9lvop) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L263)):*
> ```Markdown
> **Version-Upgrade Considerations**
> 
> In order to support version upgrades while maintaining the replication stream, the clusters should be upgraded in a particular order. The source cluster cannot finalize its upgrade before the nodes on the standby cluster is upgraded and finalized, since otherwise the source cluster could send backwards-incompatible data to the standby cluster.
> ```

Yuck. You're right, but this is going to be a pain. This requires the use of preserve_downgrade_option on the source cluster and coordination between the two. This has implications for multi-tenancy since tenants won't have access to do things like this (and will have to instead rely on things like a policy to leave the upgrade unfinalized for N days)
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMr4hbE6JjgHV-jRdk9:-MMr4hbE6JjgHV-jRdkA:b2hhc77) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L266)):*
> ```Markdown
> 
> 
> ## Drawbacks and Limitations
> ```

We should make explicit one of our key design tradeoffs: If one range/node is having trouble and can't close its timestamps in a timely fashion, we let the cluster-wide recovery point fall behind instead of allowing inconsistent replication.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56932)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, @dt, @HonoreDB, @miretskiy, and @pbardea)

___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqKhh177JrAmYWsG-F:-MMr7xoG025N7i21mO9Y:b-y70cyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L44)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Is "the span" necessarily singular, or could there be multiple non-contiguous spans? (i.e. would the non-contiguous spans pose any difficulties for syncing things up at the end)  I see you're mostly using the singular here (except for the first sentence in this section), but it's unclear whether that's a hard requirement or if a single span just turned out to be the most useful. 
</blockquote></details>

I don't think we have a hard req in theory but I think in practice we're expecting a single Span from [TableDataMin, TableDataMax) as encoded either by the system codec (for raw cluster streams) or a specific tenant codec for tenant-to-tenant streams.
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqLXDIBINmp7PUgjVq:-MMrFWBLDsQQTQKxLxzo:b-bi5boe) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L83)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Which use cases are covered by this design doc? The title says "cluster-to-cluster" but this paragraph sounds like we're just doing tenant-to-tenant (and maybe cluster-to-tenant?) first. 
</blockquote></details>

the initial use-case is replicating the span of tenant X from cluster A to cluster B. This section was intended to explain that the same tool -- replicate a given span from one cluster to another -- could be used when the span is _the whole cluster_ iff the destination cluster is "offline", and that this inverted boot -- booting just the recovery tenant and *not* the host cluster -- could be a way to use the same tool for the use-case of replicating all-of-cluster-a from cluster a to cluster b. However the specific design of that is left mostly to a follow up work, with the primary goals for now being the replicate tenant x from cluster a to cluster b use-case, albeit with an eye towards that making sure what we build will indeed slot into that follow-up.
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqOUsD0ZXDSy18VylQ:-MMr9CdH9C3MQ_fNcART:basfrub) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L124)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

So this is basically introducing a "pull" model to CDC in contrast to the current "push" model, right?

What happens when these outboxes reach their maximum size? 
</blockquote></details>

Sort of: it's pull-based from our new consumer, but I think it'd still be "push" from the point of view of the CDC producer -- it is just "pushing" to these new outbox buffers, from which our consumer can pull. 

If the consumer goes away / doesn't drain the outbox and it fills, our current plan is to just return an error that will kill the producer changefeed job -- if the consumer does comes back later and wants to resume, they'll need to create a new producer changefeed using a cursor to pick up where they left off (if it is still within GC period). Our thinking here is that an outage of the second/standby should not be able to affect the primary, so we can't slow down/buffer more/etc. Similarly not protecting timestamps to prevent GC either -- if you're gone so long we fall out of GC, that's on you, but we don't want to affect primary's scan perf. If you really need durability of every single write, use the stream to a durable bucket like s3, either in addition, or tail it from the secondary instead if you can afford the latency. As a later optimization maybe we could make a outbox that can both be tailed over gRPC *and* flushes to s3.
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqQ1jG73AvtFr7c-LW:-MMrB8267yp0aIbwGUjJ:b-mxevzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L133)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We should think about garbage collection policies here. If I only want to keep X hours of stream logs, which files are safe to delete? 

For example, should the timestamp prefix come before partition ID? 

If the latest generation ID is more than X hours old am I guaranteed safe to delete everything from all past generations, or could some fresher data still need to be retained in the previous generation?

How disruptive is a generation rollover? If it's not disruptive, forcing a periodic generation change could make this easier. (and if it is disruptive, could generation changes put strict RPO objectives in jeopardy?)
</blockquote></details>

I think we should be able to make generation changes smooth (that's how we handle the source cluster topology changing after all) in which case I'd vote for GC on generation boundaries only. Given that a generation is just the (raw) output of a cdc job we can also start them at whatever time we want with a cursor, so it is also pretty easy to have generation that picks up where a BACKUP ends for a RESTORE+play log style solution, so you could, if you wanted, bump your generation at 00:00:00 and replace it with a backup of same.
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqSp9D7zIZl7YSqug7:-MMrBOlG8HldtSrk47q9:bgbms2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L133)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

How similar/different is this to the scheme used for CDC HTTP sinks? 
</blockquote></details>

I believe the big departure is a) explicitly partitioning it b) having the top-level dividing into generations within which the partitioning is static. This felt important to us so that our consumer knew exactly how many partitions it *needs* to read changes from -- i.e. we if there are four partitions, we *must* to get to/above the same resolved time _in all four_.
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMqSdFWDPsqlCq7U4_Q:-MMrBd9m7vI5KEcivOa4:b-lcyzje) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L135)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Which node is responsible for writing the topology file for a new generation?
</blockquote></details>

the node planning the flow
___
*[docs/RFCS/20201119_streaming_cluster_to_cluster.md, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56932#-MMr-31p867gI4JUCAe4:-MMrBsWI84APR-CutB3q:b-tn8y0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c24bb7984521d7331a4dd387c95f44259f05135/docs/RFCS/20201119_streaming_cluster_to_cluster.md#L236)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If we were streaming to/from files instead of directly cluster-to-cluster, we could roll forward instead of backward. If we initiated a flush, we know that all of the data up to the next resolved timestamp is available, so a restarted job could pick up from their and complete the process (assuming the KV writes here are idempotent). So that's one option for a RevertRange-free mode of operation, although I don't think it's worth making the intermediate files mandatory. 
</blockquote></details>

yeah, I don't want to make files mandatory as that likely adds significant latency. I think once we start ingesting, above one time, we need to get to the next one everywhere or else we'll need to rollback. With files, we could delay ingesting above one time until we know the files are available to get to the next time in every partition, so that becomes unlikely, but a) I still think we want non-file option b) I'm not sure if we want to be able to complete cutover if we lose access to some or all files, in which case we may have a partial ingestion we can't complete.

**Comment by ajwerner** [comment]
This document does not make any mention of re-writing prefixes. I suspect there are a number of cases where we'll want to do this. tenant IDs are not globally unique. Also, I can very much see wanting to clone a tenant into the same cluster.

**Comment by dt** [comment]
TenantID currently are externally controlled and, at the moment, are being kept globally unique. Tenant BACKUP/RESTORE also relies on this, as we currently cannot re-key tenants during RESTORE either. Both are planned, but are out of scope for now.

**Comment by dt** [comment]
We're going to merge this and then open another PR with some edits and learnings and new questions from the implementation, unless someone objects.

**Comment by dt** [comment]
Okay, as mentioned, merging this draft for now, with an amendment currently planned as a follow-up to discuss non-mvcc operations (addsstable and clear/revertrange).

TFTRs!

bors r+

**Comment by tbg** [comment]
When starting to stream a tenant, do we expect (& is it very important) that the tenant's MVCC history is also streamed over? This came up in (internal) [gdoc](https://docs.google.com/document/d/179PYb9EYryBQ9-nX2OJBlDxbdrJ9ZTHiXZmm8-d-LaE/edit?disco=AAAANSwvroQ).

**Comment by ajwerner** [comment]
> When starting to stream a tenant, do we expect (& is it very important) that the tenant's MVCC history is also streamed over? This came up in (internal) [gdoc](https://docs.google.com/document/d/179PYb9EYryBQ9-nX2OJBlDxbdrJ9ZTHiXZmm8-d-LaE/edit?disco=AAAANSwvroQ).

I would think it would be pretty important, otherwise changefeed jobs would be toast.

**Pull request merged**
