### PR TITLE
spanconfig: improve use of commit ts validity intervals

### LINKED ISSUE #73789: spanconfig: ensure safety without mutual exclusion in the reconciliation job
**Describe the problem**

We introduced a singleton `AUTO SPAN CONFIG RECONCILATION` job in #68522. We use this per-tenant job to drive the reconciliation process between a tenant's SQL config state (zone configs) with the cluster's KV state (span configs) -- more details found in the [accompanying RFC](#66348). The RFC relies on strict mutual exclusion guarantees, needing to ensure that at a given point in time, only a single reconciliation instance is up and running. We're currently failing to provide this guarantee as described in the thread here: https://github.com/cockroachdb/cockroach/pull/71994#pullrequestreview-831032004. This issue tracks fixing this bug.

Jira issue: CRDB-11751

### PR DESCRIPTION
**Pull request by irfansharif**
- Fix a bug where the sqlliveness session was incorrectly returning
  hlc.MinTimestamp when asking for the start timestamp of the underlying
  lease;
- Drop the "lease" verbiage from KVAccessor, instead talk about the
  valid commit timestamp interval. Not all uses of the KVAccessor plumb
  in lease timestamps;
- Check whether the max commit timestamp is non-empty (possible if the
  lease has already expired) before issuing the RPC, saves an extra
  round trip;
- Unify handling of commit timestamp interval -- we were previously
  checking properties only in codepaths where the txn was not already
  scoped;
- Move the retryable commit-timestamp-out-of-bounds error out to the
  base spanconfig package (breaking the dependency between
  spanconfigreconciler and spanconfigkvaccessor);
- Re-write a test to use manual clocks, and use it to test the scenario
  where a txn's timestamp is bumped past the maximum commit timestamp
  (can happen for large kvaccessor batches, we should observe an
  internal retry);
- Remove an extraneous goroutine from a test checking whether ctx
  cancellation is respected.

(re-) Fixes #73789.

Release note: None
Release justification: low risk, high benefit change

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80196#-:-N076LsJ7zSLTqowTTFi:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @irfansharif)

___
*[pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80196#-N07577z6TEGl3Mrg7x8:-N07577z6TEGl3Mrg7x9:b-mjewga) ([raw file](https://github.com/cockroachdb/cockroach/blob/26466fc82b1e065cf4bf330e7a3a9fd4a1d64cbb/pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go#L289)):*
> ```Go
> 	}
> 
> 	if maxCommitTS.Less(txn.ReadTimestamp()) {
> ```

should this check `ProvisionalCommitTimestamp` instead of `ReadTimestamp`? I know that the below code does the check based on the `ReadTimestamp`. I guess I'm wondering whether that's correct.
___
*[pkg/spanconfig/errors.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80196#-N074p_E6tZZG3Dk0l8I:-N074p_E6tZZG3Dk0l8J:b-yr7z5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/26466fc82b1e065cf4bf330e7a3a9fd4a1d64cbb/pkg/spanconfig/errors.go#L22)):*
> ```Go
> // CommitTimestampOutOfBoundsError is returned when it's not possible to commit
> // an update within the specified time interval.
> type CommitTimestampOutOfBoundsError struct{}
> ```

I'm 50/50 on exporting this. I don't know that it adds any value, but I don't feel strongly.

**Review by irfansharif — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80196#-:-N07DM2H2oI_Ge9j8Bjr:b-voiyyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @arulajmani)

___
*[pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80196#-N07577z6TEGl3Mrg7x8:-N077ViVC5bf_0ncrJVr:baok2ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/26466fc82b1e065cf4bf330e7a3a9fd4a1d64cbb/pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go#L289)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should this check `ProvisionalCommitTimestamp` instead of `ReadTimestamp`? I know that the below code does the check based on the `ReadTimestamp`. I guess I'm wondering whether that's correct.
</blockquote></details>

Yea I was wondering the same. I also found #76727 earlier today which fires the assertion under `txn.UpdateDeadline`, but doesn't look directly relevant. Looks like the check below dates back to https://github.com/cockroachdb/cockroach/commit/6acbe92757b8c2db40e3c795bc84ba1abe722138 and was pointing to the txn's (static?) original timestamp. I'm not sure what would break if we only allowed deadlines to be set if under the provisional timestamp. 

Back to this PR: if we're comparing the maxCommitTS against ReadTimestamp here, and if that's different from the ProvisionalCommitTimestamp, we can have the following scenarios (given ReadTimestamp <= ProvisionalTimestamp <= FinalCommitTS):
a. maxCommitTS < ReadTimestamp implies maxCommitTS < ProvisionalTimestamp
b. maxCommitTS >= ReadTimestamp
  i.  maxCommitTS <= ProvisionalTimestamp
  ii. maxCommitTS > ProvisionalTimestamp

For both (b.i) and (b.ii) we can set the deadline without error-ing and will retry if maxCommitTS > FinalCommitTS. I'll keep the patch as is for now.
___
*[pkg/spanconfig/errors.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80196#-N074p_E6tZZG3Dk0l8I:-N077mTqEtz8S1-UkpcF:b65sivr) ([raw file](https://github.com/cockroachdb/cockroach/blob/26466fc82b1e065cf4bf330e7a3a9fd4a1d64cbb/pkg/spanconfig/errors.go#L22)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm 50/50 on exporting this. I don't know that it adds any value, but I don't feel strongly. 
</blockquote></details>

With NewCommitTimestampOutOfBoundsError, the linter'll complains if it's unexported; I also wanted to avoid the reconciler -> kvaccessor dependency. But most of all I wanted to refer to a public symbol in various comments (KVAccessor, the RPCs).

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80196)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/spanconfig/errors.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80196#-N074p_E6tZZG3Dk0l8I:-N07O4hk5XKFRfnt42GF:b-xqe6jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/26466fc82b1e065cf4bf330e7a3a9fd4a1d64cbb/pkg/spanconfig/errors.go#L22)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

With NewCommitTimestampOutOfBoundsError, the linter'll complains if it's unexported; I also wanted to avoid the reconciler -> kvaccessor dependency. But most of all I wanted to refer to a public symbol in various comments (KVAccessor, the RPCs).
</blockquote></details>

I don't follow. I'd just have `NewCommitTimestampOutOfBoundsError` return `error`

**Review by irfansharif — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80196#-:-N07Q2qp-Q9ghE0Qf_zd:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @arulajmani)

___
*[pkg/spanconfig/errors.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80196#-N074p_E6tZZG3Dk0l8I:-N07Q0Bq4e-Ixzebw6Mc:bqjnfuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/26466fc82b1e065cf4bf330e7a3a9fd4a1d64cbb/pkg/spanconfig/errors.go#L22)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't follow. I'd just have `NewCommitTimestampOutOfBoundsError` return `error`
</blockquote></details>

Doh, done.

**Comment by irfansharif** [comment]
Bouncing the CLA bot.

bors r+

**Pull request merged**
