### PR TITLE
kv/kvclient: add distinct metric for each RPC method

### PR DESCRIPTION
**Pull request by nvb**
This commit adds a new counter metric for each of the 44 request methods. It then updates DistSender to track the use of these methods in their associated counters.

The goal of this is to provide observability into the types of RPCs that are being sent in a cluster. We've seen a few cases in the past month where a cluster was sending more local and remote RPCs than expected, and being able to easily see what operations these RPCs were performing would have been a significant help to debugging.

Release note (admin ui change): A collection of new metrics were added that track the method of requests that are sent as RPCs between nodes in a cluster. These metrics are named `distsender.rpc.<method>.sent`, with examples of `<method>` being "scan" and "conditionalput".

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
These metrics already paid dividends in https://github.com/cockroachdb/cockroach/issues/46752.

**Comment by ajwerner** [comment]
FWIW I'm a big fan of this. I'm also interested in adding this sort of counter on the server side.

**Comment by nvanbenschoten** [comment]
> I'm also interested in adding this sort of counter on the server side.

Agreed. I'm surprised we have absolutely nothing for this. I opened https://github.com/cockroachdb/cockroach/issues/50660 to track this.

I've rebased this and removed the WIP label, since I'm also more convinced something like this should exist. PTAL!

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46747#-:-MAl8iKC1Z7Du2wwUQDD:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

**Review by ajwerner — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46747#-:-MAld48Z6HPgDMFuN4w1:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Pull request merged**
