### PR TITLE
server: plumb contexts to various ops

### PR DESCRIPTION
**Pull request by RaduBerinde**
Plumbing contexts to various server ops (status, summaries, ID allocation, range cache, queue) so it is visible in the traces/logs where the operation is coming from.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9463)

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by tamird** [comment]
:lgtm: but will conflict with #9416

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[kv/dist_sender.go, line 261 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9463#-KS7Lup8VZksi5VKEJr-:-KS7Lup8VZksi5VKEJr0:b-7m74ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/d899c39a0b102abc85c760536956487efbc41337/kv/dist_sender.go#L261)):*
> ```Go
> 	replicas := newReplicaSlice(ds.gossip, desc)
> 	replicas.Shuffle()
> 	// TODO(tschottdorf): Ideally we would use the trace of the request which
> ```

nice!

---

*[kv/range_cache.go, line 456 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9463#-KS7M2pKyfv_Yb4c-Z5S:-KS7M2pKyfv_Yb4c-Z5T:b-bj6e1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1646bd3b74c9f890ea82e85cb923073adf9648b1/kv/range_cache.go#L456)):*
> ```Go
> 	ctx = log.WithLogTag(ctx, "range-lookup", nil)
> 	descs, prefetched, pErr :=
> 		rdc.db.RangeLookup(ctx, metadataKey, desc, considerIntents, useReverseScan)
> ```

optional nit:
```
foo, bar, baz := call(
  arg1, arg2, arg3
)
```

---

*[server/updates.go, line 216 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9463#-KS7Ir1oWbpap20c-poa:-KS7Ir1oWbpap20c-pob:b6ueu0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e24cdd5033ed0a92cd279595e54f68492b073c9/server/updates.go#L216)):*
> ```Go
> func (s *Server) usageReportingEnabled() bool {
> 	// Grab the optin value from the database.
> 	ctx := s.Ctx()
> ```

nit: maybe just remove this local?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9463#-:-KS7MAONmMcMMkbdW5dP:b-fj4vgp)*

**Comment by RaduBerinde** [comment]
Thanks! I will wait for that to go in. I was waiting for #9461 to go in first anyway, so I could do a merge to develop with this as soon as it goes in.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9463#-:-KS81yP4S0PaOtvpVRbs:be11hty)*

**Comment by tamird** [comment]
Reviewed 1 of 11 files at r7, 2 of 2 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, 5 of 5 files at r12.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9463)*

**Pull request merged**
