### PR TITLE
sql/mutations: stats histograms

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
plz review commit #X:
@rohany 1
@rytaft 2
@jordanlewis 3

**Comment by rohany** [comment]
First commit LGTM, but why haven't you moved the other mutators over to sqlbase as well? It feels strange for them not to all be in the same place.

**Comment by mjibson** [comment]
Yeah that's a good question. I want them all to live in mutations, because that's what they are and otherwise there's no need to have a separate package. However since RandCreateTable needs to make random column families, it needs this one. Some of the other mutations need sqlbase.RandDatum, so my choices are:

1) do this
2) put everything in sqlbase, no mutations package
3) have the mutations package set a global variable in the sqlbase package that points to the rand col family mutation

Of those I think 1 is the best. Do you have other thoughts or ideas? Am I missing a cleaner solution?

**Review by rytaft — COMMENTED** [review]
Excited to see this!

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-:-LvMQI1C7dNBHfe88aBO:b-k12pfo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mjibson, and @rohany)

___
*[pkg/sql/mutations/mutations.go, line 114 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMMpJZ-vxOwmpiNkzK:-LvMMpJZ-vxOwmpiNkzL:b4fijjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L114)):*
> ```Go
> 	var v int64
> 	if n := rng.Intn(20); n == 0 {
> 		// ignore
> ```

[nit] So in this case you return 0? seems more like `randNonNegInt` rather than `randPosInt`
___
*[pkg/sql/mutations/mutations.go, line 145 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMNdOs1kSbIBHYvlvO:-LvMNdOs1kSbIBHYvlvP:b-9fnixo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L145)):*
> ```Go
> 			}
> 			for i := 0; i < n; i++ {
> 				upper := sqlbase.RandDatumWithNullChance(rng, col.Type, 0)
> ```

Is there a version of this function that doesn't return null?
___
*[pkg/sql/mutations/mutations.go, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMOD66Ckpy7TqpQAtG:-LvMOD67Bf8hEsPSKevp:bhtxej8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L162)):*
> ```Go
> 					NumEq:         randPosInt(rng),
> 					NumRange:      randPosInt(rng),
> 					DistinctRange: float64(randPosInt(rng)),
> ```

This won't make much sense unless `DistinctRange` is <= `NumRange`. I guess it's not a bad idea to test that things don't blow up, but the results might be weird....
___
*[pkg/sql/mutations/mutations.go, line 194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMPRvVAhI_6M4xy7uf:-LvMPRvW7Pp-Tb_oDRdB:boe6eq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L194)):*
> ```Go
> 					makeHistogram(def)
> 				}
> 			case *tree.IndexTableDef:
> ```

Do all the column defs always come before all the index or unique constraint defs?

**Comment by rohany** [comment]
I talked to Matt offline about this, and I think doing 1) makes sense.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42973)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @rytaft)

___
*[pkg/sql/mutations/mutations.go, line 114 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMMpJZ-vxOwmpiNkzK:-LvMsmivB7ab9sKWDtdQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L114)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] So in this case you return 0? seems more like `randNonNegInt` rather than `randPosInt`
</blockquote></details>

Done.
___
*[pkg/sql/mutations/mutations.go, line 145 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMNdOs1kSbIBHYvlvO:-LvMjp1E9fJ04B0NeQRr:b-z5m0hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L145)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is there a version of this function that doesn't return null?
</blockquote></details>

The `0` here makes it never return null.
___
*[pkg/sql/mutations/mutations.go, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMOD66Ckpy7TqpQAtG:-LvMtziW0iizER8EXHfJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L162)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This won't make much sense unless `DistinctRange` is <= `NumRange`. I guess it's not a bad idea to test that things don't blow up, but the results might be weird....
</blockquote></details>

Done.
___
*[pkg/sql/mutations/mutations.go, line 194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMPRvVAhI_6M4xy7uf:-LvMsiQG52hK_Dzt5sly:bi3ue0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L194)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do all the column defs always come before all the index or unique constraint defs?
</blockquote></details>

nope, they can appear in any order

**Review by rytaft — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42973)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mjibson, and @rohany)

___
*[pkg/sql/mutations/mutations.go, line 145 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMNdOs1kSbIBHYvlvO:-LvMug4i7eEaTcM2ssQU:blohsjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L145)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

The `0` here makes it never return null.
</blockquote></details>

Then do you need the check below for null?
___
*[pkg/sql/mutations/mutations.go, line 194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMPRvVAhI_6M4xy7uf:-LvMvVen3AAx5x2C74ZM:blcq581) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L194)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

nope, they can appear in any order
</blockquote></details>

Then it seems like you might get a nil reference error when you access the stat that doesn't exist yet (line 180)?
___
*[pkg/sql/mutations/mutations.go, line 109 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMuaTZEdlor6DjWKlV:-LvMuaT_25Gpcd1mULhP:b-sq8d2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/87a72a9e731809e13b66424215c83d7bef2fde0f/pkg/sql/mutations/mutations.go#L109)):*
> ```Go
> }
> 
> // randNonNegInt returns a random positive integer. It attempts to distribute it
> ```

[nit] random non-negative integer

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42973)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @rytaft)

___
*[pkg/sql/mutations/mutations.go, line 145 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMNdOs1kSbIBHYvlvO:-LvN-DpcBEgB7sD_o-Kw:bx7tiqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L145)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Then do you need the check below for null?
</blockquote></details>

Yes, because it can be returned for error paths or if a type it doesn't know about was requested.
___
*[pkg/sql/mutations/mutations.go, line 194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMPRvVAhI_6M4xy7uf:-LvN-gDZ4p4tMporisHN:b-fk5wgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1a9295de7f7116463787b6229af755319ef8d3d/pkg/sql/mutations/mutations.go#L194)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Then it seems like you might get a nil reference error when you access the stat that doesn't exist yet (line 180)?
</blockquote></details>

Ooh good catch. Added a check for that in makeHistogram.
___
*[pkg/sql/mutations/mutations.go, line 109 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LvMuaTZEdlor6DjWKlV:-LvN-DFH8csHaoDxjkzK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87a72a9e731809e13b66424215c83d7bef2fde0f/pkg/sql/mutations/mutations.go#L109)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] random non-negative integer
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
third commit :lgtm: 

> Reviewed 4 of 4 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-:-LvN1kL5D_CIT1S26E4A:b-jrgltj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42973)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mjibson, @rohany, and @rytaft)

___
*[pkg/sql/sem/tree/parse_string.go, line 80 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LwF0hqq1S2VEPsk4Dfd:-LwF0hqq1S2VEPsk4Dfe:b46c1xa) ([raw file](https://github.com/cockroachdb/cockroach/blob/38e674d625e5790e82fb2088b8327f47f4098fab/pkg/sql/sem/tree/parse_string.go#L80)):*
> ```Go
> 		return ParseDJSON(s)
> 	case types.OidFamily:
> 		// TODO(mjibson): Is it possible to create OID types with
> ```

No, it's not possible. The only way is via cast, like 34343::regclass will become an oid with a name, but it'll start life as either a DInt or a DOid without a name.
___
*[pkg/sql/sem/tree/testdata/eval/oid, line 12 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LwF0ra63b0Nfq3V-gl9:-LwF0ra63b0Nfq3V-glA:b-bu21v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/38e674d625e5790e82fb2088b8327f47f4098fab/pkg/sql/sem/tree/testdata/eval/oid#L12)):*
> ```
> 
> eval
> 3:::REGCLASS
> ```

This is kind of weird. It's probably an edge case. If you had a table 'foo' with id 100, and did `100:::regclass`, you'd get `100`, but you'd really want to have gotten 'foo'? Or maybe it doesn't matter since there wasn't a cast. I'm not sure if it really matters that much though.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42973)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mjibson, @rohany, and @rytaft)

___
*[pkg/sql/sem/tree/parse_string.go, line 80 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42973#-LwF0hqq1S2VEPsk4Dfd:-LwF8Jx2-BrYLWzgl4sS:bcdmmux) ([raw file](https://github.com/cockroachdb/cockroach/blob/38e674d625e5790e82fb2088b8327f47f4098fab/pkg/sql/sem/tree/parse_string.go#L80)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

No, it's not possible. The only way is via cast, like 34343::regclass will become an oid with a name, but it'll start life as either a DInt or a DOid without a name.
</blockquote></details>

thanks. removed the todo.

**Pull request merged**
