### PR TITLE
sql: make column family allocation more aggressive

### PR DESCRIPTION
**Pull request by danhhz**
We have seen a number of potential customers try loading data into a
table with many small TEXT columns. Our initial column family heuristics
are conservative in this case and it appears may be too conservative.
This commit introduces new heuristics that assume STRING, CHAR, VARCHAR,
TEXT are small and BLOB, BYTES, BYTEA are big.

New heuristics:
- If the column is bounded size (int, float, duration, date,
  timestamp, bool, or user bounded string/decimal), put it in family 0.
- If the column is unbounded size and string or decimal, put it in family 0.
- If the column is unbounded size and bytes, put it in a new family.

```
name                                    old time/op    new time/op    delta
WideTable_Cockroach/10-8                  5.67ms ± 2%    4.53ms ± 5%  -20.16%  (p=0.008 n=5+5)
WideTable_Cockroach/100-8                 6.08ms ± 5%    4.66ms ± 1%  -23.28%  (p=0.008 n=5+5)
WideTable_Cockroach/1000-8                7.45ms ± 1%    6.28ms ± 2%  -15.68%  (p=0.008 n=5+5)
WideTable_Cockroach/10000-8               20.5ms ± 5%    21.6ms ± 6%     ~     (p=0.095 n=5+5)
WideTable_Cockroach/100000-8               138ms ± 1%     150ms ± 4%   +8.84%  (p=0.008 n=5+5)
WideTable_Cockroach/1000000-8              1.34s ± 3%     1.59s ± 2%  +18.32%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/10-8         7.89ms ± 1%    6.74ms ±10%  -14.58%  (p=0.016 n=4+5)
WideTableMultinode_Cockroach/100-8        8.14ms ± 3%    6.72ms ± 4%  -17.44%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/1000-8       10.5ms ±12%     9.7ms ± 9%     ~     (p=0.310 n=5+5)
WideTableMultinode_Cockroach/10000-8      25.9ms ± 8%    29.1ms ± 4%  +12.61%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/100000-8      168ms ± 9%     213ms ± 6%  +27.12%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/1000000-8     1.66s ± 5%     2.24s ± 5%  +35.35%  (p=0.008 n=5+5)

name                                    old alloc/op   new alloc/op   delta
WideTable_Cockroach/10-8                  1.35MB ± 0%    0.73MB ± 0%  -45.46%  (p=0.008 n=5+5)
WideTable_Cockroach/100-8                 1.39MB ± 0%    0.82MB ± 0%  -41.21%  (p=0.008 n=5+5)
WideTable_Cockroach/1000-8                1.92MB ± 1%    1.60MB ± 1%  -16.38%  (p=0.008 n=5+5)
WideTable_Cockroach/10000-8               7.12MB ± 1%    9.29MB ± 1%  +30.47%  (p=0.008 n=5+5)
WideTable_Cockroach/100000-8              61.8MB ± 2%    86.2MB ± 2%  +39.60%  (p=0.008 n=5+5)
WideTable_Cockroach/1000000-8              695MB ± 1%     922MB ± 4%  +32.64%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/10-8         2.51MB ± 1%    1.27MB ± 1%  -49.44%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/100-8        2.59MB ± 1%    1.45MB ± 0%  -44.11%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/1000-8       3.63MB ± 1%    3.25MB ± 2%  -10.59%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/10000-8      13.6MB ± 3%    20.4MB ± 3%  +49.88%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/100000-8      120MB ± 3%     185MB ± 1%  +54.26%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/1000000-8    1.48GB ± 2%    2.70GB ± 7%  +82.65%  (p=0.008 n=5+5)

name                                    old allocs/op  new allocs/op  delta
WideTable_Cockroach/10-8                   9.35k ± 4%     7.48k ± 1%  -20.07%  (p=0.008 n=5+5)
WideTable_Cockroach/100-8                  9.23k ± 3%     7.53k ± 1%  -18.37%  (p=0.008 n=5+5)
WideTable_Cockroach/1000-8                 9.24k ± 6%     7.52k ± 0%  -18.63%  (p=0.008 n=5+5)
WideTable_Cockroach/10000-8                9.60k ± 2%     7.80k ± 1%  -18.75%  (p=0.008 n=5+5)
WideTable_Cockroach/100000-8               11.6k ± 3%      9.7k ± 1%  -15.99%  (p=0.008 n=5+5)
WideTable_Cockroach/1000000-8              30.4k ± 2%     28.5k ± 2%   -6.19%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/10-8          16.2k ±10%     11.5k ± 0%  -28.97%  (p=0.016 n=5+4)
WideTableMultinode_Cockroach/100-8         15.9k ± 8%     11.5k ± 0%  -27.36%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/1000-8        16.4k ± 7%     11.9k ± 1%  -27.13%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/10000-8       17.1k ± 9%     12.9k ± 2%  -24.42%  (p=0.008 n=5+5)
WideTableMultinode_Cockroach/100000-8      22.8k ± 6%     23.3k ± 2%     ~     (p=1.000 n=5+5)
WideTableMultinode_Cockroach/1000000-8     86.0k ± 5%    100.9k ± 8%  +17.36%  (p=0.008 n=5+5)
```

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13198)

### CODE REVIEW

**Comment by danhhz** [comment]
cc @bdarnell 

Tests aren't passing but they're annoying to fix (schema change tests count kv entries) so I wanted to get some initial feedback before I do it.

**Comment by bdarnell** [comment]
Instead of drawing the line between text and binary columns, we could draw a line between the different types which are currently synonyms: BLOB and TEXT are big, the others are small. This would be similar to the way these types are used in other databases (where BLOB and TEXT often imply out-of-line storage). Small binary columns are fairly common (it's how we recommend storing UUIDs, for example. UUIDs have a known size, but I wouldn't expect people to apply that limit consistently), and I don't think we should assume that binary columns are fundamentally more likely to be huge than text ones.

**Comment by petermattis** [comment]
> where BLOB and TEXT often imply out-of-line storage

The motivating use case has a table with lots of `TEXT` columns. I'm tempted to make the heuristic "only place BLOB in a separate column family".

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13198#-:-KbW606nKSlAUq1I061W:b-egg0xt)*

**Comment by bdarnell** [comment]
It's probably worth asking why they chose TEXT - did they know TEXT and STRING/VARCHAR are synonymous in cockroachdb, or were they carrying over expectations from other databases? I believe TEXT often performs worse than VARCHAR in other databases too. 

I'd still vote against treating bytes and text differently (i'm thinking of systems I've worked on that habitually gzipped all non-indexed text content and stored it in BLOBs instead of TEXT columns). You shouldn't be putting huge data in a row even if it's in a BLOB type. Maybe we should just put everything in family zero unless the user explicitly opts in to doing otherwise.

**Comment by petermattis** [comment]
> Maybe we should just put everything in family zero unless the user explicitly opts in to doing otherwise.

I'd be ok with that too. More than ok if we also implemented: https://github.com/cockroachdb/cockroach/issues/13195. But even without implementing #13195 it seems reasonable.

**Comment by danhhz** [comment]
Unless I'm missing something, at the point this decision is made we can't tell the difference between BLOB and BYTES (similarly TEXT and VARCHAR). I can obviously plumb that down, but if we're okay with putting everything in family 0 by default, that's obviously easier.

Also interesting to note is that when the benchmark gets to 1MB, the new heuristic is 33% slower than the old one, but queries are already quite slow at that point (b.N only gets up to 1), so that's pretty supportive of Ben's "You shouldn't be putting huge data in a row even if it's in a BLOB type."

**Comment by danhhz** [comment]
Updated to put everything in family 0 and updated tests. RFAL

**Comment by petermattis** [comment]
This seems fine by me, but let's let this marinate for a while.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sqlbase/structured.go, line 1101 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13198#-KbWfAFmjns0KkYtfXU5:-KbWfAFqq3syxRZvXRnv:bhprvmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/838ffdd82e838b4d74d6b6aa87ff87aa1fb467aa/pkg/sql/sqlbase/structured.go#L1101)):*
> ```Go
> // - Put all columns in family 0.
> func fitColumnToFamily(desc TableDescriptor, col ColumnDescriptor) (int, bool) {
> 	return 0, true
> ```

Heh, that's boring.  We should add a bit more explanation for the rationale behind this heuristic (if we decide to adopt it).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13198#-:-KbWfNP_BRJCKAaB4Fzy:bo3y6ia)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13198#-:-KbafR29znjqv9FUaHPH:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sqlbase/structured.go, line 1101 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13198#-KbWfAFmjns0KkYtfXU5:-KbpS2s_lTCUhW_syUBD:b8zl69o) ([raw file](https://github.com/cockroachdb/cockroach/blob/838ffdd82e838b4d74d6b6aa87ff87aa1fb467aa/pkg/sql/sqlbase/structured.go#L1101)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Heh, that's boring.  We should add a bit more explanation for the rationale behind this heuristic (if we decide to adopt it).
</blockquote></details>

I don't like that we're throwing away the previous code. I am ok with the new heuristic but it would be nice to know we could revert to the old one easily (if need be). Can we keep both and have a flag that select between them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13198)*

**Comment by danhhz** [comment]
After letting this sit in the background over the weekend, I still think this is the right thing to do. @petermattis?

---

Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sqlbase/structured.go, line 1101 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13198#-KbWfAFmjns0KkYtfXU5:-Kbpc-6vrRdL2JiKpO1m:b-xpocxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/838ffdd82e838b4d74d6b6aa87ff87aa1fb467aa/pkg/sql/sqlbase/structured.go#L1101)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't like that we're throwing away the previous code. I am ok with the new heuristic but it would be nice to know we could revert to the old one easily (if need be). Can we keep both and have a flag that select between them?
</blockquote></details>

Added a comment.

@RaduBerinde, that's what git's history is for. : - ) I disagree that we should keep around code that we don't intend to run

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13198#-:-KbpcKRmy0zcvGA6Rlkm:b-h7exez)*

**Comment by petermattis** [comment]
> After letting this sit in the background over the weekend, I still think this is the right thing to do. @petermattis?

I'm still good with this too.

---

Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13198#-:-KbpeSTXDLuBIVVcaEiT:b-53xf93)*

**Pull request merged**
