### PR TITLE
kvserver: enable stricter lease acquisition check

### PR DESCRIPTION
**Pull request by andrewbaptist**
Previously we added a flag RejectLeaseOnLeaderUnknown to reject lease attempts if the leader was unknown. There were a number of failing unit tests that needed to be fixed to fully enable this. This PR addresses all the unit test failures and enables the setting by default.

Epic: none

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
@pav-kv I'm working through to see if I can fix most of the test cases. I think with the simple RF=1 patch (which could probably be made cleaner) it addresses most of the remaining issues but there are still a few failures left.

**Comment by pav-kv** [comment]
I've done some test fixing too in #121128, consider if we need anything from there.

**Comment by andrewbaptist** [comment]
@pav-kv - with the changes to the Test ProposalBuffer, there are only two remaining tests that fail.

This is a definite change in behavior and the one that Erik was worried about changing the behavior for. I'm not sure it is salvageable.
```
    client_replica_circuit_breaker_test.go:321: 
        	Test:       	TestReplicaCircuitBreaker_Follower_QuorumLoss
        	Messages:   	[NotLeaseHolderError] refusing to acquire lease on follower; r68: replica (n1,s1):1 not lease holder; lease holder unknown
```
This is test is validating the new behavior, so probably a change in what it is asserting:
```
    client_raft_test.go:1311:
          Test:         TestRequestsOnLaggingReplica
          Messages:     expected NotLeaseholderError with a lease, got: [NotLeaseHolderError] refusing to acquire lease on follower; r68: replica (n1,s1):1 not lease holder; lease holder unknown
```

I'd be OK skipping the `QuorumLoss` test and fixing the lagging replica assertion. I don't remember exactly what we decided we wanted to do with these tests.

**Comment by andrewbaptist** [comment]
We decided it is too late in the cycle to try and get this in 24.1, but we should still merge this to master. The only remaining failures is `TestRequestsOnLaggingReplica`

**Pull request closed without merging**
