### PR TITLE
sql: wait for local orchestrator during ALTER TENANT SERVICE

### LINKED ISSUE #112554: streamingccl: TestTenantStreamingFailback timed out
Seen in https://teamcity.cockroachdb.com/viewLog.html?buildId=12221602&buildTypeId=Cockroach_BazelExtendedCi

Jira issue: CRDB-32491

### PR DESCRIPTION
**Pull request by stevendanna**
Similar to SET CLUSTER SETTING, this waits for the local server orcehstrator to start or stop a server before returning from an ALTER TENANT command that modifies the service_mode.

As a result, you can no longer issue ALTER TENANT inside anything but an implicit transaction.

Epic: none

Fixes #112554

### CODE REVIEW

**Review by msbutler — COMMENTED** [review]
thanks for doing this! I left a bunch of questions, probably because I'm not very familiar with this code.

**Review by yuzefovich — COMMENTED** [review]
I already gave a quick look earlier, had only one comment at the time, and will review more carefully after Michael is happy with the change :)

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115094#-:-NkSVZ2t3IfdKmwNyGUS:b-q8r1vp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msbutler and @stevendanna)

___
*[`pkg/server/serverorchestrator/orchestrator.go` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115094#-NkHXTWCCyn2Vui_LIxv:-NkHXTWCCyn2Vui_LIxw:b56btr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/02f6fccf04cd9327d7948feca53c517b196808e7/pkg/server/serverorchestrator/orchestrator.go#L19)):*
> ```Go
> 
> var (
> 	// ErrTenantServerNotReady is returned from GetServer when the
> ```

nit: maybe `s/GetServer/serverController.getServer/`? Relatedly, should that method be a part of `ServerOrchestrator` interface?

**Review by msbutler — APPROVED** [review]
LGTM! thanks for answering my questions! I am a bit worried about the [TestServerControllerMultiNodeTenantStartup](https://teamcity.cockroachdb.com/viewLog.html?buildId=12929114&buildTypeId=Cockroach_BazelExtendedCi#testNameId-172456610560303082) failure under stress race though.

**Review by yuzefovich — COMMENTED** [review]
I got one more question.

> Reviewed 7 of 10 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115094#-:-Nkc7CeqEh0n4xtWI33D:b-55nlfd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msbutler and @stevendanna)

___
*[`pkg/configprofiles/profiles.go` line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/115094#-Nkc5MJq208dRlewl8Py:-Nkc5MJq208dRlewl8Pz:b-u6w8kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/137ada3006326262a8a2153065c6b960e3561f2b/pkg/configprofiles/profiles.go#L141)):*
> ```Go
> 			"ALTER VIRTUAL CLUSTER application START SERVICE SHARED",
> 		},
> 		nil, /* txnSQL */
> ```

Apologies if this has already been mentioned, but why is this moved from `txnSQL` to `nonTxnSQL`? (I think the answer is that we now require `ALTER VIRTUAL CLUSTER` stmt to be in an implicit txn but thought I'd double check. But then there are some bits about the internal executor, so I'm confused...) What effects does it have? Do we have at least some test coverage using config profiles that would sanity-check this change?

**Pull request closed without merging**
