### PR TITLE
tests: support float approximation in roachtest query comparison utils

### LINKED ISSUE #95665: Order of evaluation of aggregations causes precision issues for float
roachtest.unoptimized-query-oracle/disable-rules=half/seed-multi-region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8403709?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8403709?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=half/seed-multi-region) on master @ [b21379bb56dd206e6f63cc7d07ca72e85db7a4c4](https://github.com/cockroachdb/cockroach/commits/b21379bb56dd206e6f63cc7d07ca72e85db7a4c4):

```
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=half/seed-multi-region/run_1
(query_comparison_util.go:251).runOneRoundQueryComparison: failed to set random seed. 1026 statements run: dial tcp 34.138.224.32:26257: connect: connection refused
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=half/seed-multi-region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23664

### PR DESCRIPTION
**Pull request by rharding6373**
tests, logictest, floatcmp: refactor comparison test util functions
    
This commit moves some float comparison test util functions from
logictest into the floatcmp package. It also moves a query result
comparison function from the tlp file to query_comparison_util in the
tests package.
    
This commit also marks roachtests as testonly targets.
    
Epic: none
    
Release note: None

tests: support float approximation in roachtest query comparison utils
    
Before this change unoptimized query oracle tests would compare results
using simple string comparison. However, due to floating point precision
limitations, it's possible for results with floating point to diverge
during the course of normal computation. This results in test failures
that are difficult to reproduce or determine whether they are expected
behavior.
    
This change utilizes existing floating point comparison functions used
by logic tests to match float values only to a specific precision. Like
the logic tests, we also have special handling for floats and decimals
under the s390x architecture (see #63244). In order to avoid costly
comparisons, we only check floating point precision if the naiive string
comparison approach fails and there are float or decimal types in the
result.
    
Epic: None
Fixes: #95665
    
Release note: None

### CODE REVIEW

**Review by michae2 — COMMENTED** [review]
Thank you for doing this!

> Reviewed 9 of 9 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-:-N__APq53Bv1fP5NCvLQ:bff479j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @rharding6373)

___
*[`pkg/cmd/roachtest/BUILD.bazel` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N__8_8Q8fM5b37M-zKi:-N__8_8Q8fM5b37M-zKj:b7tj9g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/35fb0d3355f05d50425fafa8ac955e11d3126ed5/pkg/cmd/roachtest/BUILD.bazel#L73)):*
> ```Starlark
>     name = "roachtest_test",
>     size = "small",
>     testonly = 1,
> ```

TIL about testonly, nice!
___
*[`pkg/cmd/roachtest/tests/query_comparison_util.go` line 406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N__A0J43_V_ZP1ZEc6p:-N__A0J43_V_ZP1ZEc6q:bw6edzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c36d5d394952d51c7237a3e8c31bf476a968fa1/pkg/cmd/roachtest/tests/query_comparison_util.go#L406)):*
> ```Go
> 	// comparison, so that we can split the sorted rows if we need to make
> 	// additional comparisons.
> 	sep := ",unsortedMatricesDiffWithFloatComp separator,"
> ```

This is a nice technique for splitting again, but won't it also show up in the error message? Maybe the reported diff should be calculated again, without this separator, to make it easier to read?
___
*[`pkg/cmd/roachtest/tests/unoptimized_query_oracle.go` line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N__9AEe9DoFYKQIvJva:-N__9AEe9DoFYKQIvJvb:b-nsetya) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c36d5d394952d51c7237a3e8c31bf476a968fa1/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go#L177)):*
> ```Go
> 		return nil
> 	}
> 	diff, err := unsortedMatricesDiffWithFloatComp(unoptimizedRows, optimizedRows, h.colTypes)
> ```

Nice! I think we also want this in costfuzz and tlp, right?
___
*[`pkg/testutils/floatcmp/floatcmp.go` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N__7kFkA_Cpel1czN4U:-N__7kFl-eGb5J9w7VYZ:bkes3zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/35fb0d3355f05d50425fafa8ac955e11d3126ed5/pkg/testutils/floatcmp/floatcmp.go#L127)):*
> ```Go
> 	// normalize converts f to base * 10**power representation where base is in
> 	// [1.0, 10.0) range.
> 	normalize := func(f float64) (base float64, power int) {
> ```

I know this is how the code was before, but I think it would be more accurate to use `math.Frexp` to get the power-of-2 normalization. (I think the power-of-10 normalization might itself introduce floating-point error.)

**Review by rharding6373 — COMMENTED** [review]
TFTR! PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-:-N_aE9-ZBp2mUA0jI97G:b-qozhfh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @michae2, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/query_comparison_util.go` line 406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N__A0J43_V_ZP1ZEc6p:-N__npf_3CfqIX2R-zbw:b-lcptmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c36d5d394952d51c7237a3e8c31bf476a968fa1/pkg/cmd/roachtest/tests/query_comparison_util.go#L406)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

This is a nice technique for splitting again, but won't it also show up in the error message? Maybe the reported diff should be calculated again, without this separator, to make it easier to read?
</blockquote></details>

You're right. I redid the join/sort if there is an error and there are floats instead.
___
*[`pkg/cmd/roachtest/tests/unoptimized_query_oracle.go` line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N__9AEe9DoFYKQIvJva:-N__rTHQ8wr_AFhGVb0m:bx13ozm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c36d5d394952d51c7237a3e8c31bf476a968fa1/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go#L177)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Nice! I think we also want this in costfuzz and tlp, right?
</blockquote></details>

I modified costfuzz to use this. For tlp, we expect a diff because we already did a sql comparison that failed, so I think that using the old diff method is ok.
___
*[`pkg/testutils/floatcmp/floatcmp.go` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N__7kFkA_Cpel1czN4U:-N__seuE4yChb0tB_sgS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/35fb0d3355f05d50425fafa8ac955e11d3126ed5/pkg/testutils/floatcmp/floatcmp.go#L127)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I know this is how the code was before, but I think it would be more accurate to use `math.Frexp` to get the power-of-2 normalization. (I think the power-of-10 normalization might itself introduce floating-point error.)
</blockquote></details>

Done.

**Review by michae2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/query_comparison_util.go` line 478 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N_aFPMF7uuhBnfnpRH4:-N_aFPMF7uuhBnfnpRH5:b6amvq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c821d5c0de3e9daa5ef666ca757751c181c401c9/pkg/cmd/roachtest/tests/query_comparison_util.go#L478)):*
> ```Go
> 		}
> 	}
> 	return "", nil
> ```

Do we also need to confirm that the rest of the columns are equal? (In other words, if the result contains float columns, and those are equal, but some other non-float column is not equal, will this catch that?)

It might be good to add some testcases with both float and non-float columns.
___
*[`pkg/cmd/roachtest/tests/query_comparison_util_test.go` line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N_aGhsH7ONzm_YwvXDg:-N_aGhsH7ONzm_YwvXDh:bt1vi3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c821d5c0de3e9daa5ef666ca757751c181c401c9/pkg/cmd/roachtest/tests/query_comparison_util_test.go#L56)):*
> ```Go
> 		{
> 			name:        "multi float approx match",
> 			colTypes:    []string{"FLOAT8"},
> ```

Should this slice have two values?

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106552)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @michae2, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/query_comparison_util.go` line 478 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N_aFPMF7uuhBnfnpRH4:-N_dwgzF7eGjJ_SKHbNn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c821d5c0de3e9daa5ef666ca757751c181c401c9/pkg/cmd/roachtest/tests/query_comparison_util.go#L478)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Do we also need to confirm that the rest of the columns are equal? (In other words, if the result contains float columns, and those are equal, but some other non-float column is not equal, will this catch that?)

It might be good to add some testcases with both float and non-float columns.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/query_comparison_util_test.go` line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-N_aGhsH7ONzm_YwvXDg:-N_dwrP8Co40Wd2COhXF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c821d5c0de3e9daa5ef666ca757751c181c401c9/pkg/cmd/roachtest/tests/query_comparison_util_test.go#L56)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should this slice have two values?
</blockquote></details>

Done.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106552#-:-N_t_dkQD9Nkw_-sZbOQ:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

**Comment by rharding6373** [comment]
The test failure is unrelated. I opened https://github.com/cockroachdb/cockroach/issues/107455 to address it.

TFTRs!

bors r+

**Pull request merged**
