### PR TITLE
sqlccl: add a function to presplit ranges for ingest

### PR DESCRIPTION
**Pull request by danhhz**
presplitRanges creates multiple splits at once. It does this by finding
the middle range, splitting at the Start key and recursively
presplitting the resulting left and right hand ranges.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13150)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup.go, line 428 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNQzpEZdFuOiQ57CCS:-KbNQzpEZdFuOiQ57CCT:bv3984w) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L428)):*
> ```Go
> 
> // presplitRanges creates multiple splits at once. It does this by finding the
> // middle range, splitting at the Start key and recursively presplitting the
> ```

should mention somewhere that the ranges are the ones described by `input` (or rename `input` to `ranges`)

---

*[pkg/ccl/sqlccl/backup.go, line 432 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNRpZiCc_NJMhWq0GU:-KbNRpZiCc_NJMhWq0GV:bplcs00) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L432)):*
> ```Go
> // is the smaller, so normally you'd split from the left, but this method should
> // only be called on empty keyranges, so it's okay.
> //
> ```

It's not specified if we split at the very first key and/or at the very last (seems like only the first one, do we not care about the last one?)

---

*[pkg/ccl/sqlccl/backup.go, line 433 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNQjMQ0JJetwPRdAJW:-KbNQjMRGcqKCl1fydwx:bwxp2uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L433)):*
> ```Go
> // only be called on empty keyranges, so it's okay.
> //
> // The `input` parameter is expected to be sorted by start key.
> ```

I assume they also expected to exactly "touch" (EndKey = next Key)? I know the code doesn't care, but that's the only way having input as `[]Span` makes sense.. Seems like it would be more natural to just pass a list of keys (and the keys could be already rewritten for that matter, rewriting the keys would be done beforehand as it doesn't have much to do with splitting)

---

*[pkg/ccl/sqlccl/backup.go, line 434 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNTSUYj6PMpFTnbiaj:-KbNTSUYj6PMpFTnbiak:b1ozfee) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L434)):*
> ```Go
> //
> // The `input` parameter is expected to be sorted by start key.
> func presplitRanges(
> ```

Seems like there should be a limit on the number of `AdminSplit` we run in parallel, no? If we have 10k ranges, not sure if having 5000 goroutines all doing `AdminSplit` on the last level is a good idea.

Easiest would be to use a semaphore to limit the number of parallel operations, though it still leaves the memory usage of the goroutines (I think something like 4Kb for stack) as a potential issue.

---

*[pkg/ccl/sqlccl/backup.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNRKlMwrzo5j76Qz12:-KbNRKlMwrzo5j76Qz13:bm9kkev) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L477)):*
> ```Go
> 		}
> 		if len(rangesRight) > 0 {
> 			wg.Add(1)
> ```

we could just call `splitFn()` and exit here (and ~halve the number of goroutines we spawn)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-:-KbNUfnNGoQEq7Lfpoa0:bnfp4nl)*

**Comment by danhhz** [comment]
Thanks for the review! I did some decent surgery, so probably worth taking another quick look

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 428 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNQzpEZdFuOiQ57CCS:-KbQO1zTdxSH-tVYH_WH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L428)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

should mention somewhere that the ranges are the ones described by `input` (or rename `input` to `ranges`)
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup.go, line 432 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNRpZiCc_NJMhWq0GU:-KbQS6GUkjJiHgtDVMGm:bginovp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L432)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's not specified if we split at the very first key and/or at the very last (seems like only the first one, do we not care about the last one?)
</blockquote></details>

Did your next comment.

---

*[pkg/ccl/sqlccl/backup.go, line 433 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNQjMQ0JJetwPRdAJW:-KbQSEH_RFSVRdjVyhdI:bvrddms) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L433)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I assume they also expected to exactly "touch" (EndKey = next Key)? I know the code doesn't care, but that's the only way having input as `[]Span` makes sense.. Seems like it would be more natural to just pass a list of keys (and the keys could be already rewritten for that matter, rewriting the keys would be done beforehand as it doesn't have much to do with splitting)
</blockquote></details>

You're right. The interface to this was awkward. Switched to a slice of keys that are already rewritten.

---

*[pkg/ccl/sqlccl/backup.go, line 434 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNTSUYj6PMpFTnbiaj:-KbQSU07rpzqikwWdDz2:b-5rtef4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L434)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Seems like there should be a limit on the number of `AdminSplit` we run in parallel, no? If we have 10k ranges, not sure if having 5000 goroutines all doing `AdminSplit` on the last level is a good idea.

Easiest would be to use a semaphore to limit the number of parallel operations, though it still leaves the memory usage of the goroutines (I think something like 4Kb for stack) as a potential issue.
</blockquote></details>

I'm a little scared of adding complexity to this before we see it be necessary. This is a good point though, so I left it as a TODO.

---

*[pkg/ccl/sqlccl/backup.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNRKlMwrzo5j76Qz12:-KbQTba6RU5KaZQzogNh:bc4omgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L477)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

we could just call `splitFn()` and exit here (and ~halve the number of goroutines we spawn)
</blockquote></details>

Heh, fun. I think it's more like log(n) though, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-:-KbQW4jKixVBBoVO5V-p:bhhcx2h)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 433 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNQjMQ0JJetwPRdAJW:-KbR4liOEGKuPUEN4eYl:bldrt07) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L433)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

You're right. The interface to this was awkward. Switched to a slice of keys that are already rewritten.
</blockquote></details>

Nice, thanks, this is much cleaner!

---

*[pkg/ccl/sqlccl/backup.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNRKlMwrzo5j76Qz12:-KbR3SPUhL-JfiaJFRNP:b-ruew8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L477)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Heh, fun. I think it's more like log(n) though, no?
</blockquote></details>

Every internal node of the binary tree (there are ~N/2 of them) used to spawn 2 goroutines, now it spawns one. Or, in other words, we used to have one goroutine per node (internal or leaf), now we have one per leaf.

I was thinking we could remove the `wg.Add(1)` and do `return` after calling `splitFn`. Probably not important, not sure how much tail recursion optimization Go does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-:-KbR4nFL9o-8w6fJvh8y:bnfp4nl)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup_test.go, line 181 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbR5fs7UJK5U-96fy_5:-KbR5fs8Wt1R8fdy_7CA:bkq2fc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/17abba30df2de4cad3338641dda5357597e66568/pkg/ccl/sqlccl/backup_test.go#L181)):*
> ```Go
> 		}
> 		for _, split := range bankSplitStmts(numAccounts, backupRestoreDefaultRanges) {
> 			_, _ = sqlDB.DB.Exec(split)
> ```

Why did this change? Do the splits fail? Add a comment if it needs to be this way for a specific reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150)*

**Comment by danhhz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbNRKlMwrzo5j76Qz12:-KbR5HBmlNVsgpSl9Dof:b-yrbmkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6fc1c0ed9b123fee09d530adc502d897999cde/pkg/ccl/sqlccl/backup.go#L477)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Every internal node of the binary tree (there are ~N/2 of them) used to spawn 2 goroutines, now it spawns one. Or, in other words, we used to have one goroutine per node (internal or leaf), now we have one per leaf.

I was thinking we could remove the `wg.Add(1)` and do `return` after calling `splitFn`. Probably not important, not sure how much tail recursion optimization Go does.
</blockquote></details>

Yup, you're totally right, it's about half. The explicit return version is correct, but it takes me a lot longer to convince myself that it's correct when reading it, so I think I'll leave it this way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150)*

**Comment by danhhz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup_test.go, line 181 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150#-KbR5fs7UJK5U-96fy_5:-KbR6SSWOhdZ0GuSL5S8:b-2vltn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/17abba30df2de4cad3338641dda5357597e66568/pkg/ccl/sqlccl/backup_test.go#L181)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why did this change? Do the splits fail? Add a comment if it needs to be this way for a specific reason.
</blockquote></details>

Done. It's flaky sometimes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13150)*

**Comment by danhhz** [comment]
Thanks for the reviews, y'all!

**Pull request merged**
