### PR TITLE
ui: upgrade antd to v5 in cluster-ui and db-console

### PR DESCRIPTION
**Pull request by koorosh**
This change upgrades antd package in Cluster UI and Db Console up to 5.x version to match
the version in CC Console and make it easier to extract components.

It is preferable to review those changes per commit where some commits 
include mostly configuration changes and other - resolved conflicts in changed
components interfaces.

- update `antd` version to match the version as in CC Console.
- updated dependencies in `package.json` files and removed redundant `antd` configs in babel files
- remove all `antd` style imports from the code. 

Release note: None

Epic: https://cockroachlabs.atlassian.net/browse/CC-26102

Loom video with latest changes: https://www.loom.com/share/d0e116876d184678becae30e32430cf1?sid=d750fc2e-b268-4932-9b10-457ca8990f1b

### CODE REVIEW

**Comment by laurenbarker** [comment]
This is sooo exciting! @koorosh have you tried to adjust the dropdown styles by changing the theme? I don't see where you added the antd theme in this PR.

**Comment by koorosh** [comment]
> What's the difference in font size?

For some components font size is changed to `16px` instead of `14px` as it was before change. Agree, that it should be fixed as well.

**Review by laurenbarker — COMMENTED** [review]
Thanks @koorosh! This is incredible! I flagged some things for us to go over in an in person review, but I don't have any major concerns. I just want to give things a last look together before it gets merged :)

> Reviewed 7 of 8 files at r1, 29 of 41 files at r2, 14 of 16 files at r3, 1 of 1 files at r4, 2 of 3 files at r5, 2 of 2 files at r6, 8 of 8 files at r7, 2 of 2 files at r8, 28 of 28 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-:-O-N_n5A3KcQPbvdllMD:b-pvp6m4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/jest.config.js` line 49 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-MVUOT402ZNvQI7Jcs:-O-MVUOT402ZNvQI7Jct:b-c5tra) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d9eaa7939e4fb5aa0518ba7e19750a55c93cf11/pkg/ui/workspaces/cluster-ui/jest.config.js#L49)):*
> ```JavaScript
>   },
>   transformIgnorePatterns: [
>     "node_modules/(?!(.*crdb-protobuf-client.*))",
> ```

Is this related to the antd change?
___
*[`pkg/ui/workspaces/cluster-ui/tsconfig.json` line 17 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-MVd0tAnPaeBmiXtXt:-O-MVd0tAnPaeBmiXtXu:b-c5tra) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d9eaa7939e4fb5aa0518ba7e19750a55c93cf11/pkg/ui/workspaces/cluster-ui/tsconfig.json#L17)):*
> ```jsonc
>     "skipLibCheck": true,
>     "sourceMap": false,
>     "baseUrl": ".",
> ```

Is this related to the antd change?
___
*[`pkg/ui/workspaces/cluster-ui/src/antdTheme.ts` line 28 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-MVr_r0OCMMW-6fvnp:-O-MVr_r0OCMMW-6fvnq:b-1ncb3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdd57cd769f3ab843161ad3d30e445860618e20/pkg/ui/workspaces/cluster-ui/src/antdTheme.ts#L28)):*
> ```XML
>  *
>  * For global overrides that cannot be configured with tokens, please
>  * put styles in `assets/css/global/_overrides.scss`.
> ```

Is this path correct for cluster-ui?
___
*[`pkg/ui/workspaces/cluster-ui/src/search/search.tsx` line 125 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-NRGzdCNtqKQ0uNitW:-O-NRGzdCNtqKQ0uNitX:b-54l8zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdd57cd769f3ab843161ad3d30e445860618e20/pkg/ui/workspaces/cluster-ui/src/search/search.tsx#L125)):*
> ```XML
> 
>     return (
>       <ConfigProvider theme={crlTheme}>
> ```

For in person review: Let's go over where the theme is used.
___
*[`pkg/ui/workspaces/cluster-ui/src/search/search.tsx` line 127 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-NR-muCiJkMjcgVlh_:-O-NR-muCiJkMjcgVlha:b-yt61so) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdd57cd769f3ab843161ad3d30e445860618e20/pkg/ui/workspaces/cluster-ui/src/search/search.tsx#L127)):*
> ```XML
>       <ConfigProvider theme={crlTheme}>
>         <Input
>           className={cx("root")}
> ```

For in person review: This was "submitted" when the component was submitted. Can you point me to where the styles for "root" are coming from.
___
*[`pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/activateStatementDiagnosticsModal.tsx` line 150 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-NRaq65hTAZFND5y3V:-O-NRaq65hTAZFND5y3W:bb07f3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdd57cd769f3ab843161ad3d30e445860618e20/pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/activateStatementDiagnosticsModal.tsx#L150)):*
> ```XML
>         className={cx("modal-body")}
>       >
>         <ConfigProvider theme={crlTheme}>
> ```

For in person review: Should look at before and after of this page.
___
*[`pkg/ui/workspaces/db-console/src/views/shared/components/alertMessage/alertMessage.tsx` line 103 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-NUyXpDDCyk60n8pHj:-O-NUyXpDDCyk60n8pHk:b-al24ow) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d9eaa7939e4fb5aa0518ba7e19750a55c93cf11/pkg/ui/workspaces/db-console/src/views/shared/components/alertMessage/alertMessage.tsx#L103)):*
> ```XML
>             type={iconType}
>             theme="filled"
>             className="alert-massage__icon"
> ```

For in person review: It looks like this class was making it green. Let's check if it's still green.
___
*[`pkg/ui/workspaces/cluster-ui/src/dateRangeMenu/dateRangeMenu.module.scss` line 33 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-NVHD700IIe9lM5D6r:-O-NVHD83jVPEcnfvu9x:b-mtomvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdd57cd769f3ab843161ad3d30e445860618e20/pkg/ui/workspaces/cluster-ui/src/dateRangeMenu/dateRangeMenu.module.scss#L33)):*
> ```SCSS
>   }
> 
>   :global(.ant-picker) {
> ```

For in person review: Let's look at the time picker width.
___
*[`pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.spec.tsx` line 229 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-NVqUd6QBw3F-SN4Qv:-O-NVqUd6QBw3F-SN4Qw:bbd8hzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdd57cd769f3ab843161ad3d30e445860618e20/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.spec.tsx#L229)):*
> ```XML
>     getByText(expectedText[0]);
>     // userEvent.click(getByText(expectedText[0]));
>     // userEvent.click(getByTestId("dropdown-button"));
> ```

Should these be included in the test?

**Review by koorosh — COMMENTED** [review]
> Reviewed 1 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124100)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @laurenbarker and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/jest.config.js` line 49 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-MVUOT402ZNvQI7Jcs:-O-_Avhl8GGzZFgUfP2n:b-iu8bhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d9eaa7939e4fb5aa0518ba7e19750a55c93cf11/pkg/ui/workspaces/cluster-ui/jest.config.js#L49)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Is this related to the antd change?
</blockquote></details>

It caused test runner to fail as it couldn't properly resolve `pnpm` dependencies when either some pattern specified or `transformIgnorePatterns` property removed entirely. 
___
*[`pkg/ui/workspaces/cluster-ui/tsconfig.json` line 17 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-MVd0tAnPaeBmiXtXt:-O-_BwlK-9CPo8T0c5Ud:bujgj9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d9eaa7939e4fb5aa0518ba7e19750a55c93cf11/pkg/ui/workspaces/cluster-ui/tsconfig.json#L17)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Is this related to the antd change?
</blockquote></details>

`baseUrl` was specified twice, so just cleaned up. Doesn't related to main change.
___
*[`pkg/ui/workspaces/cluster-ui/src/antdTheme.ts` line 28 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-MVr_r0OCMMW-6fvnp:-O-_CM-e-24CdyW2_uFl:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdd57cd769f3ab843161ad3d30e445860618e20/pkg/ui/workspaces/cluster-ui/src/antdTheme.ts#L28)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Is this path correct for cluster-ui?
</blockquote></details>

Fixed.
___
*[`pkg/ui/workspaces/cluster-ui/src/search/search.tsx` line 127 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-NR-muCiJkMjcgVlh_:-O-_EUz91sHwdtmsWkHQ:b-smf43q) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdd57cd769f3ab843161ad3d30e445860618e20/pkg/ui/workspaces/cluster-ui/src/search/search.tsx#L127)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

For in person review: This was "submitted" when the component was submitted. Can you point me to where the styles for "root" are coming from.
</blockquote></details>

Styles for this component were re-written entirely.
"root" class contains adjusted styles that work with upgraded and's  <Input> component.
___
*[`pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.spec.tsx` line 229 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-NVqUd6QBw3F-SN4Qv:-O-_FHIO8vJvkhSy47ni:b28afxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fdd57cd769f3ab843161ad3d30e445860618e20/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.spec.tsx#L229)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Should these be included in the test?
</blockquote></details>

Cleaned up.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124100)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @laurenbarker and @xinhaoz)

___
*[`pkg/ui/workspaces/db-console/src/views/shared/components/alertMessage/alertMessage.tsx` line 103 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-NUyXpDDCyk60n8pHj:-O-aREQj13o1Ljwjj8W4:b-lxd37l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d9eaa7939e4fb5aa0518ba7e19750a55c93cf11/pkg/ui/workspaces/db-console/src/views/shared/components/alertMessage/alertMessage.tsx#L103)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

For in person review: It looks like this class was making it green. Let's check if it's still green.
</blockquote></details>

Good catch, just checked and the vertical alignments of icon and text was broken while colors are the same.
Added storybook to make it easier to test visual change of <AlertMessage> component.

**Comment by laurenbarker** [comment]
Thank you! Let's go over the pages I called out during our 1-1 tomorrow.

**Comment by koorosh** [comment]
Based on last discussion, following fixes included in PR:
- DatePicker component restyled to look as before (wider and higher input boxes)
- Increased spacing under Search input field on Databases page
- Fixed AlertMessage component styles
- Regarding wrapping all Antd components in Cluster UI, I assumed it might be better to wrap top level <App> component in Db Console (since it also relies on updated version of `Antd` package) cc @laurenbarker 

 
**Alert Message:**
Screenshot 2024-06-20 at 11 37 28

**DatePicker**
Screenshot 2024-06-20 at 16 47 04

**Search component on Databases page**
Screenshot 2024-06-20 at 16 56 54

**Statement Diagnostics modal:**
Screenshot 2024-06-20 at 19 19 20

**Review by laurenbarker — COMMENTED** [review]
Thank you! LGTM! :tada: 

> Reviewed 1 of 91 files at r19, 93 of 93 files at r32, 28 of 41 files at r33, 15 of 18 files at r34, 1 of 1 files at r35, 3 of 4 files at r36, 2 of 2 files at r37, 8 of 8 files at r38, 2 of 2 files at r39, 29 of 30 files at r40, 3 of 3 files at r41, 2 of 2 files at r42, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-:-O-wlBcZ2myC7IXrJLYj:bg7obsk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @xinhaoz)

___
*[`pkg/ui/workspaces/db-console/.storybook/main.js` line 20 at r42](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-wkdQj8et0yEeXE7Az:-O-wkdQj8et0yEeXE7B-:b36rqv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a44d86e02eb7c48aed87f6eb0b270e234d02b00/pkg/ui/workspaces/db-console/.storybook/main.js#L20)):*
> ```JavaScript
>   // addons: ["@storybook/addon-actions", "@storybook/addon-links"],
>   typescript: { reactDocgen: false },
>   // webpackFinal: async config => {
> ```

nit: Should the commented out code be removed?

**Review by laurenbarker — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-:-O-wlFPe5CWT_-J4-7iS:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @koorosh and @xinhaoz)

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124100)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @laurenbarker and @xinhaoz)

___
*[`pkg/ui/workspaces/db-console/.storybook/main.js` line 20 at r42](https://reviewable.io/reviews/cockroachdb/cockroach/124100#-O-wkdQj8et0yEeXE7Az:-O07yfMG6ZQsHqkZ8hjB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a44d86e02eb7c48aed87f6eb0b270e234d02b00/pkg/ui/workspaces/db-console/.storybook/main.js#L20)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

nit: Should the commented out code be removed?
</blockquote></details>

Done.

**Pull request merged**
