### PR TITLE
engineccl: Support JWKS for encryption-at-rest keys and hook up v2

### LINKED ISSUE #119767: engineccl: Support JWKS format for encryption-at-rest keys
**Is your feature request related to a problem? Please describe.**

The enterprise encryption flag contains support for key rotation, but not for migrating to new encryption algorithms. We need to introduce new configurability to select an encryption algorithm. This could be done as a part of the command line flag, but it would be even better to attach algorithm information to the key files themselves to take advantage of the ability to reload keys without restarting the server. 

**Describe the solution you'd like**

Replace our current non-standard key file format with the JWKS format (specified in RFC 7517 and already used elsewhere in CRDB for SSO protocols). The `key` file must be a JWKS object that contains exactly one key, while the `old-key` file could optionally gain the ability to contain multiple keys (to facilitate frequent key rotations without waiting for data to be rewritten). (Is there a better or more JWKS-standard way to designate one active key out of a key set?)

Our current key files are a concatenation of a binary key id and the raw key data. The new key files would look like
```
{
    "keys": [
        {
            "kty": "oct",  // "octets", indicates that this is a single blob as opposed to e.g. a pub/priv pair
            "kid": "base64'd key id",
            "k": "base64'd key data",
            "alg": "cockroach-aes-ctr-v1",
        }
    ],
}
```

The point of the new format is the "alg" field, where we would define identifiers for our encryption-at-rest algorithms. Unfortunately we'd have to define our own algorithm IDs, since none of the standardized ones are suitable for our purpose (they are all designed for messages small enough to be decrypted all at once, and not for large files like our sstables). While cockroach-aes-ctr-v1 is something that should remain cockroach-specific (aes-ctr-v2 is a little better but still not AEAD), we could consider in the future advocating for standardization of a better seekable algorithm/format (i.e. one that divides the data stream into equal-sized chunks and applies AES-GCM on a per-chunk basis). 

Concretely, this means the following changes:
- `cockroach gen encryption-key` gains the option to generate the new format
- The key loading code learns to recognize the new format. Unfortunately the old format doesn't contain any version marker, but since it contains purely random data it's safe to assume that any key file that parses as json is in the new format. 
- The `alg` field is used to select between encryption implementations, and is persisted in the per-file EncryptionSettings in the registry. 

**Describe alternatives you've considered**

The `--enterprise-encryption` flag could gain a new `alg` argument and leave the key files unchanged. But this means that changing algorithms requires a node restart, and we'd probably have to build some more observability tools to track the progress of the change.

The JWKS format in theory makes it possible to use off-the-shelf tools instead of writing our own, but the need to use custom `alg` values limits the applicability of existing tools. If the JWKS format had notable drawbacks this might be a reason to design our own, but I don't see any reason to do so. 

Other key file formats are in use in the public-key crypto world (PEM, etc), but as far as I can tell there's not much besides JWKS that is widely used for symmetric keys. 

Integrating encryption into the pebble WAL and SST format at a higher level would be a better way to use AEAD algorithms. If we went that route the existing encryption at rest code could become obsolete. 

**Additional context**

This is the replacement for https://github.com/cockroachdb/cockroach/pull/118824

Open question: Is the "alg" `aes-ctr` and it supports multiple key sizes, or are there separate algs for each key size? The standard JWKS algorithms include the key size in the alg name, and I have a slight preference for following that pattern going forward. 

CCing some folks who have reviewed previous PRs in this series: @RaduBerinde @sumeerbhola @rsevinsky-cr 

Jira issue: CRDB-36304

### PR DESCRIPTION
**Pull request by bdarnell**
The JWKS format for key files is now supported in addition to the legacy format (which was just raw key bytes). Keys in JWKS format can request the faster V2 encryption implementation, supporting graceful rotation into the new implementation.

Fixes #119767

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 4 of 4 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-:-NsJCA0uArFx50afP1Aa:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @jbowens)

___
*[`-- commits` line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJ95YC4fUsSy0si4rh):*
[nit] left over
___
*[`pkg/ccl/cliccl/gen.go` line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJA3lbBv3TpSbn9oij:-NsJA3lbBv3TpSbn9oik:biga1et) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a22e178b90be32c30b5ba87318ca05f0464bc69/pkg/ccl/cliccl/gen.go#L60)):*
> ```Go
> 		case 256:
> 			et = enginepbccl.EncryptionType_AES_256_CTR_V2
> 		}
> ```

default: return error?
___
*[`pkg/ccl/storageccl/engineccl/pebble_key_manager.go` line 183 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJBEg20pdMFMEc3b4c:-NsJBEg20pdMFMEc3b4d:babhd7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a22e178b90be32c30b5ba87318ca05f0464bc69/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L183)):*
> ```Go
> 			key.Info.EncryptionType = enginepbccl.EncryptionType_AES256_CTR
> 		default:
> 			return nil, errors.Wrapf(jwkErr, "could not parse store key. Key length %d is not valid for old-style key", keyLength)
> ```

[nit] If there is a bug when generating a JWK key (or it becomes corrupted for whatever reason), we will get this error. It would be nice to also show the `jwkErr` in the message.
___
*[`pkg/ccl/storageccl/engineccl/enginepbccl/key_registry.go` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJCDvy7El-huvVEmWt:-NsJCDvy7El-huvVEmWu:b-78b4ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a22e178b90be32c30b5ba87318ca05f0464bc69/pkg/ccl/storageccl/engineccl/enginepbccl/key_registry.go#L11)):*
> ```Go
> package enginepbccl
> 
> import fmt "fmt"
> ```

[nit] the `fmt` is unnecessary
___
*[`pkg/ccl/storageccl/engineccl/enginepbccl/key_registry.go` line 17 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJCv_oCXuXff8vBmXs:-NsJCv_oCXuXff8vBmXt:b-tzdndu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a22e178b90be32c30b5ba87318ca05f0464bc69/pkg/ccl/storageccl/engineccl/enginepbccl/key_registry.go#L17)):*
> ```Go
> 	switch e {
> 	case EncryptionType_AES128_CTR:
> 		return "cockroach-aes-128-ctr-v1", nil
> ```

[nit] it's unfortunate (error prone) that we have multiple instances of these string constants. Consider defining them only once in a `[...]string{EncryptionType_AES128_CTR: "cockroach-aes-128-ctr-v1", ..}` or adding a roundtripping test.

We could also make use of `e.String()` which is already defined (e.g. return `"COCKROACH_" + e.String()`).

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119913)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @RaduBerinde)

___
*[`-- commits` line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJ95YC4fUsSy0si4rh):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] left over
</blockquote></details>

Fixed
___
*[`pkg/ccl/cliccl/gen.go` line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJA3lbBv3TpSbn9oij:-NsMrkAb6iQtySqJaKVY:b-xhak5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a22e178b90be32c30b5ba87318ca05f0464bc69/pkg/ccl/cliccl/gen.go#L60)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

default: return error?
</blockquote></details>

Sure. It's redundant since we also checked at the top of the function, but it doesn't hurt. 
___
*[`pkg/ccl/storageccl/engineccl/pebble_key_manager.go` line 183 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJBEg20pdMFMEc3b4c:-NsMrscnEPBCWIa1Eetp:bpwdd5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a22e178b90be32c30b5ba87318ca05f0464bc69/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L183)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] If there is a bug when generating a JWK key (or it becomes corrupted for whatever reason), we will get this error. It would be nice to also show the `jwkErr` in the message.
</blockquote></details>

jwkErr is there as the wrapped error, which I think is the right way to model this in our errors library (I also considered CombineErrors with both jwkErr and a new fmt.Errorf for the old-style key case). 

With a small tweak here's what it looks like:
```
Received unexpected error:
                                could not parse store key. Key length 17 is not valid for old-style key. Parse error for new-style key: failed to unmarshal JWK set: error reading token: EOF
```
___
*[`pkg/ccl/storageccl/engineccl/enginepbccl/key_registry.go` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJCDvy7El-huvVEmWt:-NsMubJ3-2jaA96eDLd3:bj8j3y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a22e178b90be32c30b5ba87318ca05f0464bc69/pkg/ccl/storageccl/engineccl/enginepbccl/key_registry.go#L11)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] the `fmt` is unnecessary
</blockquote></details>

Weird, I wonder why goimports did that. 
___
*[`pkg/ccl/storageccl/engineccl/enginepbccl/key_registry.go` line 17 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJCv_oCXuXff8vBmXs:-NsMvXPT20IbJZzb7PwT:b88utsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a22e178b90be32c30b5ba87318ca05f0464bc69/pkg/ccl/storageccl/engineccl/enginepbccl/key_registry.go#L17)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] it's unfortunate (error prone) that we have multiple instances of these string constants. Consider defining them only once in a `[...]string{EncryptionType_AES128_CTR: "cockroach-aes-128-ctr-v1", ..}` or adding a roundtripping test.

We could also make use of `e.String()` which is already defined (e.g. return `"COCKROACH_" + e.String()`).
</blockquote></details>

Meh, I feel better about our ability to manually keep two short lists in sync than to write something clever to avoid the duplication.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, 6 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-:-NsONJE13x_K72FYvXcQ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

___
*[`pkg/ccl/storageccl/engineccl/pebble_key_manager.go` line 183 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119913#-NsJBEg20pdMFMEc3b4c:-NsOMq9C5RVbw4yL_-45:b9bkkp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a22e178b90be32c30b5ba87318ca05f0464bc69/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L183)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

jwkErr is there as the wrapped error, which I think is the right way to model this in our errors library (I also considered CombineErrors with both jwkErr and a new fmt.Errorf for the old-style key case). 

With a small tweak here's what it looks like:
```
Received unexpected error:
                                could not parse store key. Key length 17 is not valid for old-style key. Parse error for new-style key: failed to unmarshal JWK set: error reading token: EOF
```
</blockquote></details>

Looks great!

**Comment by bdarnell** [comment]
bors r=RaduBerinde

**Pull request merged**
