### PR TITLE
workloadccl: inject table statistics during fixtures load

### PR DESCRIPTION
**Pull request by nvb**
See #39103.

Release note: None

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39106#-:-Lkep6Ou1hvSxShj2EyL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/ccl/workloadccl/fixture.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39106#-LkeopTG3-f2Wgx0mgOC:-LkeopTG3-f2Wgx0mgOD:bxobkes) ([raw file](https://github.com/cockroachdb/cockroach/blob/05ca887878f68df1164e54ebb38dbe6af8448e45/pkg/ccl/workloadccl/fixture.go#L546)):*
> ```Go
> 	if injectStats && tablesHaveStats(tables) {
> 		// Turn off automatic stats temporarily so we don't trigger stats creation
> 		// after the IMPORT. We will inject stats inside importFixtureTable.
> ```

nit: RESTORE
___
*[pkg/ccl/workloadccl/fixture.go, line 550 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39106#-Lkeor2eEjsZw2kKhs7_:-Lkeor2eEjsZw2kKhs7a:b-5obi51) ([raw file](https://github.com/cockroachdb/cockroach/blob/05ca887878f68df1164e54ebb38dbe6af8448e45/pkg/ccl/workloadccl/fixture.go#L550)):*
> ```Go
> 		// just trigger a no-op if there are new stats available so we wouldn't
> 		// have to disable and re-enable automatic stats here.
> 		enableFn := disableAutoStats(ctx, sqlDB)
> ```

this `disableAutoStats` and the defer need to go before the RESTORE jobs get kicked off, otherwise you have a race here where the auto stats could start up after the restore finishes but before this line

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39106)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/ccl/workloadccl/fixture.go, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39106#-LkeooV8032EERGVYEJz:-LkeooV8032EERGVYEK-:bdg26lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/05ca887878f68df1164e54ebb38dbe6af8448e45/pkg/ccl/workloadccl/fixture.go#L545)):*
> ```Go
> 	tables := fixture.Generator.Tables()
> 	if injectStats && tablesHaveStats(tables) {
> 		// Turn off automatic stats temporarily so we don't trigger stats creation
> ```

I don't think this comment is accurate here.

In the existing code, we disabled auto stats before the import and ran the `enableFn` after the injection. I think we should do the same here (by the time this code runs, we may have started an auto stats job).

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39106)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/workloadccl/fixture.go, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39106#-LkeooV8032EERGVYEJz:-LkeqDlA63n4hXzGVdKo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05ca887878f68df1164e54ebb38dbe6af8448e45/pkg/ccl/workloadccl/fixture.go#L545)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think this comment is accurate here.

In the existing code, we disabled auto stats before the import and ran the `enableFn` after the injection. I think we should do the same here (by the time this code runs, we may have started an auto stats job).
</blockquote></details>

Done.
___
*[pkg/ccl/workloadccl/fixture.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39106#-LkeopTG3-f2Wgx0mgOC:-LkeqEUE1A-QRXwpgO9A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05ca887878f68df1164e54ebb38dbe6af8448e45/pkg/ccl/workloadccl/fixture.go#L546)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: RESTORE
</blockquote></details>

Done.
___
*[pkg/ccl/workloadccl/fixture.go, line 550 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39106#-Lkeor2eEjsZw2kKhs7_:-LkeqEwtEm_WlDpPdbSB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05ca887878f68df1164e54ebb38dbe6af8448e45/pkg/ccl/workloadccl/fixture.go#L550)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this `disableAutoStats` and the defer need to go before the RESTORE jobs get kicked off, otherwise you have a race here where the auto stats could start up after the restore finishes but before this line
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39106#-:-LkerFrTE-iMfbvz9l77:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by danhhz — APPROVED** [review]

**Pull request merged**
