### PR TITLE
parser: validate privilege name when parsing

### LINKED ISSUE #109549: sql/tests: TestRandomSyntaxSelect failed
sql/tests.TestRandomSyntaxSelect [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11499588?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11499588?buildTab=artifacts#/) on release-23.1 @ [e9a99ca5edea2d3f838467323355be76d9d3ec92](https://github.com/cockroachdb/cockroach/commits/e9a99ca5edea2d3f838467323355be76d9d3ec92):

```
    rsg_test.go:862: 2m0s of 5m0s: 15421 executions, 318 successful
    rsg_test.go:862: 2m5s of 5m0s: 15934 executions, 330 successful
    rsg_test.go:862: 2m10s of 5m0s: 16451 executions, 344 successful
    rsg_test.go:862: 2m15s of 5m0s: 17025 executions, 358 successful
    rsg_test.go:862: 2m20s of 5m0s: 17565 executions, 375 successful
    rsg_test.go:862: 2m25s of 5m0s: 18094 executions, 390 successful
    rsg_test.go:862: 2m30s of 5m0s: 18634 executions, 407 successful
    rsg_test.go:862: 2m35s of 5m0s: 19203 executions, 417 successful
    rsg_test.go:862: 2m40s of 5m0s: 19731 executions, 423 successful
    rsg_test.go:862: 2m45s of 5m0s: 20291 executions, 448 successful
    rsg_test.go:862: 2m50s of 5m0s: 20804 executions, 468 successful
    rsg_test.go:862: 2m55s of 5m0s: 21330 executions, 482 successful
    rsg_test.go:862: 3m0s of 5m0s: 21876 executions, 496 successful
    rsg_test.go:862: 3m5s of 5m0s: 22394 executions, 509 successful
    rsg_test.go:862: 3m10s of 5m0s: 22902 executions, 522 successful
    rsg_test.go:862: 3m15s of 5m0s: 23388 executions, 532 successful
    rsg_test.go:862: 3m20s of 5m0s: 23938 executions, 548 successful
    rsg_test.go:862: 3m25s of 5m0s: 24420 executions, 557 successful
    rsg_test.go:862: 3m30s of 5m0s: 24894 executions, 566 successful
    rsg_test.go:862: 3m35s of 5m0s: 25440 executions, 580 successful
    rsg_test.go:862: 3m40s of 5m0s: 25957 executions, 589 successful
    rsg_test.go:862: 3m45s of 5m0s: 26471 executions, 600 successful
    rsg_test.go:862: 3m50s of 5m0s: 27003 executions, 614 successful
    rsg_test.go:862: 3m55s of 5m0s: 27528 executions, 628 successful
    rsg_test.go:862: 4m0s of 5m0s: 28028 executions, 640 successful
    rsg_test.go:862: 4m5s of 5m0s: 28567 executions, 651 successful
    rsg_test.go:862: 4m10s of 5m0s: 29067 executions, 660 successful
    rsg_test.go:862: 4m15s of 5m0s: 29582 executions, 674 successful
    rsg_test.go:862: 4m20s of 5m0s: 30100 executions, 688 successful
    rsg_test.go:862: 4m25s of 5m0s: 30630 executions, 698 successful
    rsg_test.go:862: 4m30s of 5m0s: 31120 executions, 706 successful
    rsg_test.go:862: 4m35s of 5m0s: 31631 executions, 718 successful
    rsg_test.go:862: 4m40s of 5m0s: 32151 executions, 730 successful
    rsg_test.go:862: 4m45s of 5m0s: 32651 executions, 743 successful
    rsg_test.go:862: 4m50s of 5m0s: 33127 executions, 759 successful
    rsg_test.go:862: 4m55s of 5m0s: 33621 executions, 769 successful
    rsg_test.go:862: 5m0s of 5m0s: 34162 executions, 781 successful
    rsg_test.go:211: Context cancelled while executing: "SELECT ~ DEFAULT IS TRUE IS TRUE FROM ident "
    rsg_test.go:211: Context cancelled while executing: "SELECT - TRUE IS OF ( ident . FAMILY ARRAY [ -54 ] ) IS NOT UNKNOWN , * FROM ident "
    rsg_test.go:211: Context cancelled while executing: "SELECT FAMILY . FAMILY . * FROM INDEX_BEFORE_PAREN @ [ 41 ] TREAT WHERE UNIQUE ( error IS FALSE TYPEANNOTATE ident . GEOGRAPHY ARRAY [ -283 ]"
    rsg_test.go:211: Context cancelled while executing: "SELECT - DEFAULT ISNULL AS AS , * FROM ident "
    rsg_test.go:211: Context cancelled while executing: "SELECT - ARRAY [ ] IS NOT NULL AS SKIP_MISSING_UDFS , * FROM ROWS FROM ( [ FUNCTION 355 ] ( error NOCREATEDB ) WITH ORDINALITY WHERE + @ -300"
    rsg_test.go:211: Context cancelled while executing: "SELECT EXISTS ( TABLE [ SHOW ENUMS FROM ident ] ORDER BY PRIMARY KEY INDEX_AFTER_ORDER_BY_BEFORE_AT DESC , INDEX_AFTER_ORDER_BY_BEFORE_AT INDEX_AFTER_ORDER_BY_BEFORE_AT @ COST ) ident FROM [ 482 ( -200 , -241 , 124 , 31 , -43 ) AS CHANGEFEED ] @ { NO_ZIGZAG_JOIN } WITH ORDINALITY AS GEOMETRYM WHERE DEFAULT IS UNKNOWN IS OF ( ident . TIES [ ] [ error )"
    rsg_test.go:211: Context cancelled while executing: "SELECT * , DEFAULT FORCE_NOT_NULL FROM ( ( ( LATERAL CURRENT_TIMESTAMP WITH ORDINALITY AS WITHIN NATURAL RIGHT OUTER INVERTED JOIN ( FAMILY @ [ 40 ] JOIN USER WITH ORDINALITY ident ( POINTZ , LIST , ident POINT error , BETWEEN , ident , CALLED ) USING ( ident , PLACEMENT , REPLACE , TABLES , ident ) ) WITH ORDINALITY ANNOTATE_TYPE ) ) CONSTRAINTS FULL JOIN [ UPSERT INTO FAMILY . VARCHAR DEFAULT VALUES ] WITH ORDINALITY USING ( LABEL , OVERLAY , ident , ident ) ) AS STRING AS OF SYSTEM TIME DEFAULT WHERE ROW ( ) OVERLAPS ( ) TYPEANNOTATE @ -223 [ 497 ] [ error"
    rsg_test.go:211: Context cancelled while executing: "SELECT * , * , DEFAULT REDACT FROM LATERAL ( ( WITH ident ( ident , STABLE ) AS MATERIALIZED ( ALTER VIRTUAL CLUSTER 'string' GRANT error ) ( error ORDER BY INDEX_AFTER_ORDER_BY_BEFORE_AT INDEX_AFTER_ORDER_BY_BEFORE_AT . NOTNULL @ FAMILY ASC ) ) WITH ORDINALITY AS ident ( FLOAT ) WHERE UNIQUE ( error IS FALSE GREATER_EQUALS ROW ( ) OVERLAPS ROW ( ) IS FALSE COLLATE CONCURRENTLY"
    rsg_test.go:898: 34170 executions, 781 successful
    rsg_test.go:906: cannot parse output of Format: sql="SELECT DEFAULT IS NOT FALSE AS MULTIPOINTZM FROM FAMILY @ FAMILY WITH ORDINALITY , GREATEST . ident . BOX2D . ident ( ) WITH ORDINALITY WHERE EXISTS ( ( WITH MODIFYCLUSTERSETTING AS ( ALTER DEFAULT PRIVILEGES FOR ALL ROLES GRANT CREATE , CREATE , CREATE , SELECT , ident ON TYPES TO SESSION_USER WITH GRANT OPTION ) , ident AS NOT MATERIALIZED ( DROP SCHEMA error ) TABLE error ) ) IS NOT OF ( INTERVAL DAY TO MINUTE ARRAY [ 140 ] )", formattedSQL="SELECT DEFAULT IS NOT false AS multipointzm FROM \"family\"@family WITH ORDINALITY, ROWS FROM (greatest.ident.box2d.ident()) WITH ORDINALITY WHERE EXISTS ((WITH modifyclustersetting AS (ALTER DEFAULT PRIVILEGES FOR ALL ROLES GRANT CREATE, CREATE, CREATE, SELECT, Kind(0) ON TYPES TO SESSION_USER WITH GRANT OPTION), ident AS NOT MATERIALIZED (DROP SCHEMA error) TABLE error)) IS NOT OF (INTERVAL DAY TO MINUTE[])": at or near "(": syntax error
    rsg_test.go:339: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/d437d2c847dfedbc4972f231c3331c8e/logTestRandomSyntaxSelect2017057422
--- FAIL: TestRandomSyntaxSelect (301.05s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #109399 sql/tests: TestRandomSyntaxSelect failed [inverted columns have no StableID] [C-test-failure O-robot O-rsg T-sql-queries branch-release-23.1.9-rc]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxSelect.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30979

### LINKED ISSUE #109559: sql/tests: TestRandomSyntaxFuncCommon failed
sql/tests.TestRandomSyntaxFuncCommon [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11508337?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11508337?buildTab=artifacts#/) on master @ [0a895777f13e48209c8cd23f1b304d33f7e1cea1](https://github.com/cockroachdb/cockroach/commits/0a895777f13e48209c8cd23f1b304d33f7e1cea1):

```
    rsg_test.go:860: 1m55s of 5m0s: 75231 executions, 505 successful
    rsg_test.go:860: 2m0s of 5m0s: 78301 executions, 527 successful
    rsg_test.go:860: 2m5s of 5m0s: 81368 executions, 542 successful
    rsg_test.go:860: 2m10s of 5m0s: 84386 executions, 555 successful
    rsg_test.go:860: 2m15s of 5m0s: 87399 executions, 566 successful
    rsg_test.go:860: 2m20s of 5m0s: 90464 executions, 586 successful
    rsg_test.go:860: 2m25s of 5m0s: 93552 executions, 609 successful
    rsg_test.go:860: 2m30s of 5m0s: 96529 executions, 628 successful
    rsg_test.go:860: 2m35s of 5m0s: 99525 executions, 648 successful
    rsg_test.go:860: 2m40s of 5m0s: 102386 executions, 662 successful
    rsg_test.go:860: 2m45s of 5m0s: 105456 executions, 681 successful
    rsg_test.go:860: 2m50s of 5m0s: 108560 executions, 699 successful
    rsg_test.go:860: 2m55s of 5m0s: 111528 executions, 710 successful
    rsg_test.go:860: 3m0s of 5m0s: 114475 executions, 723 successful
    rsg_test.go:860: 3m5s of 5m0s: 117481 executions, 740 successful
    rsg_test.go:860: 3m10s of 5m0s: 120399 executions, 747 successful
    rsg_test.go:860: 3m15s of 5m0s: 123382 executions, 770 successful
    rsg_test.go:860: 3m20s of 5m0s: 126299 executions, 793 successful
    rsg_test.go:860: 3m25s of 5m0s: 129129 executions, 804 successful
    rsg_test.go:860: 3m30s of 5m0s: 132056 executions, 820 successful
    rsg_test.go:860: 3m35s of 5m0s: 134997 executions, 835 successful
    rsg_test.go:860: 3m40s of 5m0s: 137861 executions, 844 successful
    rsg_test.go:860: 3m45s of 5m0s: 140759 executions, 854 successful
    rsg_test.go:860: 3m50s of 5m0s: 143720 executions, 873 successful
    rsg_test.go:860: 3m55s of 5m0s: 146607 executions, 883 successful
    rsg_test.go:860: 4m0s of 5m0s: 149442 executions, 899 successful
    rsg_test.go:860: 4m5s of 5m0s: 152329 executions, 916 successful
    rsg_test.go:860: 4m10s of 5m0s: 155195 executions, 936 successful
    rsg_test.go:860: 4m15s of 5m0s: 158019 executions, 954 successful
    rsg_test.go:860: 4m20s of 5m0s: 160877 executions, 968 successful
    rsg_test.go:860: 4m25s of 5m0s: 163806 executions, 982 successful
    rsg_test.go:860: 4m30s of 5m0s: 166560 executions, 992 successful
    rsg_test.go:860: 4m35s of 5m0s: 169368 executions, 1009 successful
    rsg_test.go:860: 4m40s of 5m0s: 172231 executions, 1017 successful
    rsg_test.go:860: 4m45s of 5m0s: 175034 executions, 1036 successful
    rsg_test.go:860: 4m50s of 5m0s: 177981 executions, 1051 successful
    rsg_test.go:860: 4m55s of 5m0s: 180859 executions, 1062 successful
    rsg_test.go:209: Context cancelled while executing: "SELECT COLLATION FOR ( UNIQUE ( error IS NOT OF ( @ -147 ARRAY [ 188 ] [ error , POLYGON error ARRAY [ -497 ] , POINT error [ ] [ error ) IS NAN )"
    rsg_test.go:209: Context cancelled while executing: "SELECT CAST ( - SQRT UNIQUE ( error IS NOT UNKNOWN IS NAN AS @ 472 ARRAY [ 368 ] )"
    rsg_test.go:209: Context cancelled while executing: "SELECT CAST ( DEFAULT AS ILIKE . TIMESTAMP . INCLUDING ARRAY )"
    rsg_test.go:209: Context cancelled while executing: "SELECT ANNOTATE_TYPE ( - UNIQUE ( error , ident [ -166 ] )"
    rsg_test.go:209: Context cancelled while executing: "SELECT COALESCE ( EXISTS ( ( error ORDER BY PRIMARY KEY INDEX_BEFORE_PAREN ASC ) , ( ) OVERLAPS ( ) )"
    rsg_test.go:209: Context cancelled while executing: "SELECT TREAT ( VARBIT ( -199 ) 'string' AS @ -369 [ ] )"
    rsg_test.go:209: Context cancelled while executing: "SELECT CAST ( UNIQUE ( error AS @ 349 ARRAY [ 466 ] )"
    rsg_test.go:209: Context cancelled while executing: "SELECT CAST ( DEFAULT AS INTERVAL ARRAY [ 228 ] )"
    rsg_test.go:896: 183738 executions, 1082 successful
    rsg_test.go:904: cannot parse output of Format: sql="SELECT CAST ( EXISTS ( WITH RECURSIVE QUERIES ( VARBIT , ident , VIEWCLUSTERMETADATA ) AS ( TRUNCATE TABLE STATEMENTS . DEC RESTRICT ) , PLANS AS MATERIALIZED ( ALTER DEFAULT PRIVILEGES FOR ALL ROLES IN SCHEMA ident , ident . PRECISION GRANT ident ON TABLES TO CURRENT_USER WITH GRANT OPTION ) TABLE error ORDER BY PRIMARY KEY INDEX_BEFORE_PAREN ASC , PRIMARY KEY INDEX_BEFORE_NAME_THEN_PAREN . PRIOR . PARTIAL , INDEX_AFTER_ORDER_BY_BEFORE_AT FAMILY @ ident ASC FOR READ ONLY ) AS VARCHAR ARRAY )", formattedSQL="SELECT CAST(EXISTS (WITH RECURSIVE queries (\"varbit\", ident, viewclustermetadata) AS (TRUNCATE TABLE statements.\"dec\" RESTRICT), plans AS MATERIALIZED (ALTER DEFAULT PRIVILEGES FOR ALL ROLES IN SCHEMA ident, ident.\"precision\" GRANT Kind(0) ON TABLES TO CURRENT_USER WITH GRANT OPTION) TABLE error ORDER BY PRIMARY KEY \"index_before_paren\" ASC, PRIMARY KEY \"index_before_name_then_paren\".prior.partial, INDEX \"family\"@ident ASC) AS VARCHAR[])": at or near "(": syntax error
    rsg_test.go:460: -- test log scope end --
--- FAIL: TestRandomSyntaxFuncCommon (300.97s)
test logs left over in: /artifacts/tmp/_tmp/d437d2c847dfedbc4972f231c3331c8e/logTestRandomSyntaxFuncCommon65457063
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxFuncCommon.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30986

### PR DESCRIPTION
**Pull request by rafiss**
Now we differentiate between parsing a privileges name from user input versus from a system table. This allows us to validate names, but still backport names to older branches without causing errors.

No release note, since the user-facing change here is just a better error message.

fixes https://github.com/cockroachdb/cockroach/issues/109549
fixes https://github.com/cockroachdb/cockroach/issues/109559
Release note: None

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/privilege/privilege.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109595#-NcztkRc6NhELN1q8YWL:-NcztkRc6NhELN1q8YWM:b-vqebww) ([raw file](https://github.com/cockroachdb/cockroach/blob/c78d56b0e8f17c6d80778051435c5dd56a430ccc/pkg/sql/privilege/privilege.go#L342)):*
> ```Go
> // Purpose indicates the purpose of the resulting
> // privilege in ListFromStrings.
> type Purpose bool
> ```

nit: this seems like it is more of an `Origin` than a `Purpose`
___
*[`pkg/sql/parser/testdata/grant_revoke` line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109595#-NczuQQvAy80Y7dZvII2:-NczuQQvAy80Y7dZvII3:b-2q84wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c78d56b0e8f17c6d80778051435c5dd56a430ccc/pkg/sql/parser/testdata/grant_revoke#L601)):*
> ```
> 
> error
> GRANT CREATE, UNKNOWN_PRIV ON TABLE foo TO testuser
> ```

Do we also want to have a logic test to the same effect?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/sql/privilege/privilege.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109595#-NcztkRc6NhELN1q8YWL:-Nd1OejM9fPK76-gM7Xh:bjbhydv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c78d56b0e8f17c6d80778051435c5dd56a430ccc/pkg/sql/privilege/privilege.go#L342)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: this seems like it is more of an `Origin` than a `Purpose`
</blockquote></details>

good point, fixing
___
*[`pkg/sql/parser/testdata/grant_revoke` line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109595#-NczuQQvAy80Y7dZvII2:-Nd1OX0c9QbjVEhPVZWe:bgqtn5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c78d56b0e8f17c6d80778051435c5dd56a430ccc/pkg/sql/parser/testdata/grant_revoke#L601)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Do we also want to have a logic test to the same effect?
</blockquote></details>

IMO there's no need, since this test shows that the command is a syntax error, so that means it will never be executed by CRDB.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/parser/sql.y` line 6399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109595#-Nd1TyEN3s0kioez3tdM:-Nd1TyEN3s0kioez3tdN:b-wn2110) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfd9a8591363dcdca5355bb459f0f84d137d18b2/pkg/sql/parser/sql.y#L6399)):*
> ```Yacc
> | privilege_list
>   {
>      privList, err := privilege.ListFromStrings($1.nameList().ToStrings(), privilege.PurposeFromUserInput)
> ```

this needs to use the new name too
___
*[`pkg/sql/privilege/privilege.go` line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109595#-Nd1TvkA-IoyGSImnTrX:-Nd1TvkA-IoyGSImnTrY:bsas5tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfd9a8591363dcdca5355bb459f0f84d137d18b2/pkg/sql/privilege/privilege.go#L359)):*
> ```Go
> // If an entry is not found in ByName, it is either ignored or reports an error
> // depending on the purpose.
> func ListFromStrings(strs []string, purpose Origin) (List, error) {
> ```

nit: should rename variable name to `origin` too
___
*[`pkg/sql/parser/testdata/grant_revoke` line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109595#-NczuQQvAy80Y7dZvII2:-Nd1U68w3-2j7qLlKX9D:bwdbn7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c78d56b0e8f17c6d80778051435c5dd56a430ccc/pkg/sql/parser/testdata/grant_revoke#L601)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

IMO there's no need, since this test shows that the command is a syntax error, so that means it will never be executed by CRDB.
</blockquote></details>

Ah got it, sounds good.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109595)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/sql/parser/sql.y` line 6399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109595#-Nd1TyEN3s0kioez3tdM:-Nd1pTXs3_h7fYcVcw_X:b8tzu6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfd9a8591363dcdca5355bb459f0f84d137d18b2/pkg/sql/parser/sql.y#L6399)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

this needs to use the new name too
</blockquote></details>

fixed; i guess the IDE rename tool isn't smart enough
___
*[`pkg/sql/privilege/privilege.go` line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109595#-Nd1TvkA-IoyGSImnTrX:-Nd1pk-fC3iqQWCJMId6:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfd9a8591363dcdca5355bb459f0f84d137d18b2/pkg/sql/privilege/privilege.go#L359)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: should rename variable name to `origin` too
</blockquote></details>

fixed

**Review by andyyang890 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109595#-:-Nd1zlFqEVxC8QS3BwOG:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
