### PR TITLE
sql: extend EXPLAIN ANALYZE for follower reads and AOST

### LINKED ISSUE #99984: sql: add the AOST timestamp to the output of EXPLAIN
The AOST can make a big impact on the performance of a query. It should be included in the explain to avoid confusion.

Jira issue: CRDB-26164
Epic CRDB-37757

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: extend EXPLAIN ANALYZE to indicate that follower reads were used**

This commit extends EXPLAIN ANALYZE output for KV-reading operators to indicate whether the follower reads were used. This is achieved by reusing existing `ScanStats` infrastructure by adding a "marker" protobuf message. Note that we couldn't directly reuse the same `kvpb.ScanStats` object as the one we create in `evaluateBatch` since the determination whether the follower reads are eligible is done at a different point in time. We could have extended that protobuf and created a fresh object, but that seems a bit wrong.

Co-authored with @Uzair5162.

Release note (sql change): New field "used follower read" is added to EXPLAIN ANALYZE output to SQL operators whenever their reads were served by the follower replicas (previously, this information was only available in the trace).

**sql: extend EXPLAIN ANALYZE for "historical" reads**

This commit adds `historical: AS OF SYSTEM TIME ...` top-level attribute to EXPLAIN ANALYZE whenever the txn is historical (meaning AS OF SYSTEM TIME was specified either in the stmt or at the txn level).

Release note (sql change): New attribute `historical: AS OF SYSTEM TIME ...` is now included into EXPLAIN ANALYZE output whenever the query performs historical reads.

Fixes: #99984.

### CODE REVIEW

**Review by michae2 — COMMENTED** [review]
Nice! This will come in handy.

> Reviewed 10 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-:-NzeZnX20Lo3Yks61UVg:b-xyu2nk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Uzair5162 and @yuzefovich)

___
*[`pkg/sql/instrumentation.go` line 860 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-NzeZFNg1Ek1b9HWWozu:-NzeZFNg1Ek1b9HWWozv:b-989efc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6530d80ac54e9e58f80c02ceb9f96a713904d2f5/pkg/sql/instrumentation.go#L860)):*
> ```Go
> 		qos = ih.evalCtx.QualityOfService()
> 		iso = ih.evalCtx.TxnIsoLevel
> 		txnIsHistorical = ih.evalCtx.TxnIsHistorical.Load()
> ```

Is there a way to get this from `p.extendedEvalCtx.AsOfSystemTime`?
___
*[`pkg/sql/opt/exec/explain/output.go` line 437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-NzeY4kN0eJAfg70qHdx:-NzeY4kN0eJAfg70qHdy:bz52bd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6530d80ac54e9e58f80c02ceb9f96a713904d2f5/pkg/sql/opt/exec/explain/output.go#L437)):*
> ```Go
> 	ob.AddTopLevelField("quality of service", txnQoSLevel.String())
> 	if txnIsHistorical {
> 		ob.AddTopLevelField("historical (AOST)", "")
> ```

suggestion: it might be worth quantifying the field with the value used for AOST (and whether bounded staleness is used as well)
___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go` line 1022 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-NzeXrLJ8uP_HQ7Cs0ZS:-NzeXrLJ8uP_HQ7Cs0ZT:bjx8xnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/438863418cef2b7c07acc84d7044663f33056a14/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L1022)):*
> ```Go
> 	skip.UnderDeadlock(t)
> 
> 	rng, _ := randutil.NewPseudoRand()
> ```

nit: should this be `NewTestRand()`?

**Review by yuzefovich — COMMENTED** [review]
I added backend changes needed to show "UsedFollowerRead" boolean on the DB Console (per Glenn's [request](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1717628294318879?thread_ts=1717538188.924209&cid=C0KB9Q03D)).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-:-Nzkh09A9hpOwltXyMKT:bvs4pwa)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @Uzair5162)

___
*[`pkg/sql/instrumentation.go` line 860 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-NzeZFNg1Ek1b9HWWozu:-NzkcA0t1hsi8xFVzx5g:b-lvbhof) ([raw file](https://github.com/cockroachdb/cockroach/blob/6530d80ac54e9e58f80c02ceb9f96a713904d2f5/pkg/sql/instrumentation.go#L860)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is there a way to get this from `p.extendedEvalCtx.AsOfSystemTime`?
</blockquote></details>

Good question. I originally thought about it too and took a casual look, and it _seemed_ that `AsOfSystemTime` might not be set when AOST is set at the txn level (based on the comment). I took a closer look after your question, and now I think that it is always set (which makes sense), so I updated the comment and adjusted the code too.
___
*[`pkg/sql/opt/exec/explain/output.go` line 437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-NzeY4kN0eJAfg70qHdx:-NzkhDES5IUzWyOsed81:b-4af2p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6530d80ac54e9e58f80c02ceb9f96a713904d2f5/pkg/sql/opt/exec/explain/output.go#L437)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

suggestion: it might be worth quantifying the field with the value used for AOST (and whether bounded staleness is used as well)
</blockquote></details>

Good point, extended the message. Right now it is of the form
```
historical: AS OF SYSTEM TIME 1717730496750634000.0000000000
-- or
historical: AS OF SYSTEM TIME 1717730496750634000.0000000000 (bounded staleness)
```
Does this seem reasonable? I'm a bit concerned that this will be too eye-catching and won't be immediately useful to the users. Thoughts?
___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go` line 1022 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-NzeXrLJ8uP_HQ7Cs0ZS:-NzkRS6O6kb1zTPa7jn0:b-rpd28p) ([raw file](https://github.com/cockroachdb/cockroach/blob/438863418cef2b7c07acc84d7044663f33056a14/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L1022)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: should this be `NewTestRand()`?
</blockquote></details>

Yes, totally, nice catch.

**Review by michae2 — APPROVED** [review]
:lgtm: This is really nice!

> Reviewed 28 of 28 files at r3, 1 of 1 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-:-O-3H1x48PH57ZBsxkqt:b-jh1cwe)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Uzair5162 and @yuzefovich)

___
*[`pkg/sql/opt/exec/explain/output.go` line 437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-NzeY4kN0eJAfg70qHdx:-O-3G3tV3VTVxwFOjFkt:bz7wsto) ([raw file](https://github.com/cockroachdb/cockroach/blob/6530d80ac54e9e58f80c02ceb9f96a713904d2f5/pkg/sql/opt/exec/explain/output.go#L437)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good point, extended the message. Right now it is of the form
```
historical: AS OF SYSTEM TIME 1717730496750634000.0000000000
-- or
historical: AS OF SYSTEM TIME 1717730496750634000.0000000000 (bounded staleness)
```
Does this seem reasonable? I'm a bit concerned that this will be too eye-catching and won't be immediately useful to the users. Thoughts?
</blockquote></details>

It does seem rather frightening. Maybe we could print something friendlier using `asOfSystemTime.Timestamp.GoTime()`?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-:-O-3LBkA4bjRjPNNKc8Q:b-oduykh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @Uzair5162)

___
*[`pkg/sql/opt/exec/explain/output.go` line 437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-NzeY4kN0eJAfg70qHdx:-O-3Kts7A6jE4iDlcWbe:b-hs1bqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6530d80ac54e9e58f80c02ceb9f96a713904d2f5/pkg/sql/opt/exec/explain/output.go#L437)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

It does seem rather frightening. Maybe we could print something friendlier using `asOfSystemTime.Timestamp.GoTime()`?
</blockquote></details>

Good point, it'll be of the form:
```
historical: AS OF SYSTEM TIME 2024-06-10 22:48:31.26764 +0000 UTC
```
Done.

**Review by yuzefovich — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-:-O-3N5DeBEIkGXRfPXVk:b-ydi9ay)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @Uzair5162)

___
*[`pkg/sql/opt/exec/explain/output.go` line 437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125152#-NzeY4kN0eJAfg70qHdx:-O-3N1tbCVWxVJ-9qcAo:bhapv39) ([raw file](https://github.com/cockroachdb/cockroach/blob/6530d80ac54e9e58f80c02ceb9f96a713904d2f5/pkg/sql/opt/exec/explain/output.go#L437)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good point, it'll be of the form:
```
historical: AS OF SYSTEM TIME 2024-06-10 22:48:31.26764 +0000 UTC
```
Done.
</blockquote></details>

Actually, I'll use pgwire formatter to get:
```
historical: AS OF SYSTEM TIME 2024-06-10 22:58:08.987714
```

**Pull request merged**
