### PR TITLE
storage/bulk: use slab buffer for kv pairs

### PR DESCRIPTION
**Pull request by dt**
Currently the BufferingAdder uses a slice kvPair to buffer key value
pairs, where each element has a key and value byte slice. These two
slices mean the overhead per buffered pair is 48 bytes.

This overhead is actually a significant faction -- or even multiple --
of the total size of the buffered data in some cases, particularly in
index encoded data where values are often nil.

This adds a new slab-backed buffer, replacing the key and value slices
in each entry with key and value uint64s, which each index into the
single slab. Each uint64 contains the offset into the slab and legtht of
the key/value, packed together into the high and low bits of the uint64.

This buffer only adds 16b of overhead per k/v pair stored compared to
the 48b of keeping individual slices, and is still sortable by sorting
the slice of offset/len pairs.

The packed offset and len impose a maximum size on those fields -- in
our case the total buffer cannot be more than 32gb and the length of any
single key or value cannot exceed 512mb.

The batcher already needs to track its last key added and takes sorted input,
making checking for duplicates there easy.

While I'm here, given that it takes sorted input, we don't need to be comparing
the key to start and end key to decide if we should update start and end -- if
start is not set, it is the first key and is by definition (given the sorted
input) the start key, and the most recent key is similarly by definition also
the end key.

This uses the slab-backed key/value buffer to store the buffered kvs
instead of individual slices. This cuts the per-pair overhead from 48b
to 16b.

Release note (performance improvement): improved memory efficiency of
bulk ingestion and index backfills buffing.

### CODE REVIEW

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @lucy-zhang, and @vivekmenezes)

___
*[pkg/storage/bulk/kv_buf.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36743#-LcBfSq16zNyUx8fF-dA:-LcBfSq16zNyUx8fF-dB:b-56w36l) ([raw file](https://github.com/cockroachdb/cockroach/blob/700b7b979e6e5943db8cbda7b857f647d3aaa28a/pkg/storage/bulk/kv_buf.go#L29)):*
> ```Go
> 	keySpan uint64
> 	valSpan uint64
> }
> ```

I believe you need three fields (location, key-length, value-length):  (36, 28, 28 bits) < 12 bytes. I'd argue that the key length can be smaller but I see no space savings from that. So perhaps 

type kVBufEntry struct {
    keySpan uint64
    valLength uint32
}

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @lucy-zhang, and @vivekmenezes)

___
*[pkg/storage/bulk/kv_buf.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36743#-LcBfSq16zNyUx8fF-dA:-LcBpy-oA9yHJqVL4oi8:bjnu8tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/700b7b979e6e5943db8cbda7b857f647d3aaa28a/pkg/storage/bulk/kv_buf.go#L29)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I believe you need three fields (location, key-length, value-length):  (36, 28, 28 bits) < 12 bytes. I'd argue that the key length can be smaller but I see no space savings from that. So perhaps 

type kVBufEntry struct {
    keySpan uint64
    valLength uint32
}


</blockquote></details>

Yeah, I thought about that, but I don't know if it is quite that easy: AFAIK, the compiler will just pad the struct up to a multiple of the size of the largest element -- so if we shrink `val` to 4 while `key` is still 8, I think the compiler pads us up to 16.

We could potentially do 3 x uint32, and even pretty simply if we just wanted to trade away buffer size, but I figured I wanted to start simple and we could pursue further optimizations if it actually yields significant return and indicates this is a good place to invest more effort.

**Comment by vivekmenezes** [comment]
thanks will take a look. I see it's not compiling

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @lucy-zhang)

___
*[pkg/storage/bulk/buffering_adder.go, line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36743#-LcXMps56t1nVdlklowS:-LcXMps56t1nVdlklowT:b-y3ssc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c489cbd63bac1f1c60b19a8d905ca2f26db566a1/pkg/storage/bulk/buffering_adder.go#L104)):*
> ```Go
> // Flush flushes any buffered kvs to the batcher.
> func (b *BufferingAdder) Flush(ctx context.Context) error {
> 	if len(b.curBuf.entries) == 0 {
> ```

b.curbuf.Len()
___
*[pkg/storage/bulk/kv_buf.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36743#-LcXK0WK6CSYk_ixwJzG:-LcXK0WK6CSYk_ixwJzH:bk1omyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c489cbd63bac1f1c60b19a8d905ca2f26db566a1/pkg/storage/bulk/kv_buf.go#L52)):*
> ```Go
> )
> 
> func (b *kvBuf) append(k, v []byte) {
> ```

I think we should have this method return an error and not panic within this code.
___
*[pkg/storage/bulk/kv_buf.go, line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36743#-LcXLQAx5iMSHfaigSBo:-LcXLQAx5iMSHfaigSBp:b-gwffzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c489cbd63bac1f1c60b19a8d905ca2f26db566a1/pkg/storage/bulk/kv_buf.go#L97)):*
> ```Go
> // Less implements sort.Interface.
> func (b *kvBuf) Less(i, j int) bool {
> 	return bytes.Compare(b.read(b.entries[i].keySpan), b.read(b.entries[j].keySpan)) < 0
> ```

return b.Key(i).Less(b.Key(j))
___
*[pkg/storage/bulk/sst_batcher.go, line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36743#-LcXNVVg6lhLxf-BMRYA:-LcXNVVg6lhLxf-BMRYB:bl8c0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c489cbd63bac1f1c60b19a8d905ca2f26db566a1/pkg/storage/bulk/sst_batcher.go#L90)):*
> ```Go
> 		err.Value = append(err.Value, value...)
> 		return err
> 	}
> ```

return storagebase.DuplicateKeyError{Key: key.key, Value: value}

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @lucy-zhang, and @vivekmenezes)

___
*[pkg/storage/bulk/buffering_adder.go, line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36743#-LcXMps56t1nVdlklowS:-LcYEkLy2g80CPxZa-1e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c489cbd63bac1f1c60b19a8d905ca2f26db566a1/pkg/storage/bulk/buffering_adder.go#L104)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

b.curbuf.Len()
</blockquote></details>

Done.
___
*[pkg/storage/bulk/kv_buf.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36743#-LcXK0WK6CSYk_ixwJzG:-LcYEya63m_h9Qgd-u7X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c489cbd63bac1f1c60b19a8d905ca2f26db566a1/pkg/storage/bulk/kv_buf.go#L52)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I think we should have this method return an error and not panic within this code.
</blockquote></details>

Done.
___
*[pkg/storage/bulk/kv_buf.go, line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36743#-LcXLQAx5iMSHfaigSBo:-LcYFgue-oIU9hH1ZX0P:b5vj0ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/c489cbd63bac1f1c60b19a8d905ca2f26db566a1/pkg/storage/bulk/kv_buf.go#L97)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

return b.Key(i).Less(b.Key(j))
</blockquote></details>

I was thinking it wouldn't inline those and this gets called _a lot_ in during Sort... but I guess we can wait to see how long the sort takes in profiling to mess with it.
___
*[pkg/storage/bulk/sst_batcher.go, line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36743#-LcXNVVg6lhLxf-BMRYA:-LcXObeC5wOpkMnNwbLB:b62hj51) ([raw file](https://github.com/cockroachdb/cockroach/blob/c489cbd63bac1f1c60b19a8d905ca2f26db566a1/pkg/storage/bulk/sst_batcher.go#L90)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

return storagebase.DuplicateKeyError{Key: key.key, Value: value}
</blockquote></details>

we can't use the slices directly, so we need usual append copy pattern, and it gets pretty long for one line so I broke it up like this.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

**Pull request merged**
