### PR TITLE
Convert gossip's `capacity` key to `store` key

### PR DESCRIPTION
**Pull request by BramGruneir**
We actually gossip the full store.description (which includes the capacity), so there's no reason to call it only capacity.

This also includes
- Change the key suffix from nodeID-storeID to just storeID
- Renaming of the gossip capacity functions to gossip store

### CODE REVIEW

**Comment by tamird** [comment]
Looks like the word "convert" snuck into the commit message one time too many. LGTM

**Comment by BramGruneir** [comment]
It did indeed.  Fixed.

**Comment by tamird** [comment]
You didn't change the commit message, though.

**Comment by BramGruneir** [comment]
You're too fast for me.

**Comment by tamird** [comment]
zoom

**Pull request merged**
