### PR TITLE
cmd/roachtest: add support for reporting results to slack

### LINKED ISSUE #23177: roachtest: report success failure to slack
In addition to the normal teamcity reporting, `roachtest` can/should send a summary of results to a slack channel. https://github.com/cockroachdb/roachprod/pull/94 shows that doing this is relatively easy. Nightly test failures have often fallen through the cracks. This would ensure that we're aware and annoyed by the failures.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #23177

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@benesch I'll need help passing the slack token to `build/roachtest-nightly.sh`. I know the token, but not the teamcity side of how to pass it to the nightly test.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cmd/roachtest/slack.go, line 75 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-L6gVGD1-1Feu6dpcy3F:-L6gVGD1-1Feu6dpcy3G:b34vys3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d1f5bb7e997534378897331b032bf24cb9dd48/pkg/cmd/roachtest/slack.go#L75)):*
> ```Go
> 			Color:     status,
> 			Title:     message,
> 			TitleLink: "", // TODO(peter): link to teamcity build
> ```

Can this be derived from TC_BUILD_ID? Is there another teamcity env var I can get this from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-:-L6gVP_CAi_neTgimEzs:b-8sm43i)*

**Comment by benesch** [comment]
:lgtm: modulo unnecessary Gopkg.toml constraint

Add the token as an env var here: https://teamcity.cockroachdb.com/admin/editBuildParams.html?id=buildType:Cockroach_Nightlies_WorkloadNightly

You'll want to set the spec to `password display='hidden'` so that TeamCity does its best to scrub it from the build log if you accidentally print its value. (Happens more than you think with `set -x`.)

---

Reviewed 2 of 3 files at r1, 4 of 4 files at r3.
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[Gopkg.lock, line 12 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-L6hqA8GP2eYvPrZkR_Y:-L6hqA8GP2eYvPrZkR_Z:bnbmpr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ab8b5182d192809781951e78dea60be6ad58fa/Gopkg.lock#L12)):*
> ```
>     "internal/optional",
>     "internal/version",
>     "storage",
> ```

You seem to be using a version of `dep` that likes trailing commas. How odd. If you feel like it, try regenerating with `bin/dep` (i.e., the repo-local copy). Or perhaps that's what you did? *shrug* As long as CI is happy, I guess.

---

*[Gopkg.toml, line 98 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-L6hp5b55QGylXKQF-X7:-L6hp5b55QGylXKQF-X8:b-e1qzk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ab8b5182d192809781951e78dea60be6ad58fa/Gopkg.toml#L98)):*
> ```TOML
> [[constraint]]
>   name = "github.com/nlopes/slack"
>   version = "0.2.0"
> ```

We don't include constraints unless you need to override dep's default behavior. In this case 0.2.0 is the latest version so this constraint is a no-op, unless I'm mistaken. 

(Since `dep ensure -update JUSTONEPACKAGEHERE` actually works with dep, it's not important to pin everything the way we did with Glide.)

---

*[pkg/cmd/roachtest/slack.go, line 75 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-L6gVGD1-1Feu6dpcy3F:-L6horQs4oxbMNDOXIua:b1y4hy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d1f5bb7e997534378897331b032bf24cb9dd48/pkg/cmd/roachtest/slack.go#L75)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can this be derived from TC_BUILD_ID? Is there another teamcity env var I can get this from?
</blockquote></details>

Yep. `https://teamcity.cockroachdb.com/viewLog.html?buildId=$TC_BUILD_ID&buildTypeId=Cockroach_Nightlies_WorkloadNightly`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-:-L6hpX8Ul_t9Jc_xqeZj:b30z479)*

**Comment by petermattis** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[Gopkg.toml, line 98 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-L6hp5b55QGylXKQF-X7:-L6hqoJEEIQA6s0QOWO2:b-ohqb0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ab8b5182d192809781951e78dea60be6ad58fa/Gopkg.toml#L98)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

We don't include constraints unless you need to override dep's default behavior. In this case 0.2.0 is the latest version so this constraint is a no-op, unless I'm mistaken. 

(Since `dep ensure -update JUSTONEPACKAGEHERE` actually works with dep, it's not important to pin everything the way we did with Glide.)
</blockquote></details>

I didn't do this intentionally. I did `dep ensure -add github.com/nlopes/slack`. Is that not correct?

---

*[pkg/cmd/roachtest/slack.go, line 75 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-L6gVGD1-1Feu6dpcy3F:-L6hqvkQ_R2YlFaIqnfc:b-553h0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d1f5bb7e997534378897331b032bf24cb9dd48/pkg/cmd/roachtest/slack.go#L75)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yep. `https://teamcity.cockroachdb.com/viewLog.html?buildId=$TC_BUILD_ID&buildTypeId=Cockroach_Nightlies_WorkloadNightly`
</blockquote></details>

Thanks. I'll try that out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343)*

**Comment by petermattis** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[Gopkg.lock, line 12 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-L6hqA8GP2eYvPrZkR_Y:-L6hsMBR9F-9HHoKLngA:b-ei167l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ab8b5182d192809781951e78dea60be6ad58fa/Gopkg.lock#L12)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

You seem to be using a version of `dep` that likes trailing commas. How odd. If you feel like it, try regenerating with `bin/dep` (i.e., the repo-local copy). Or perhaps that's what you did? *shrug* As long as CI is happy, I guess.
</blockquote></details>

Btw, I did generate this using `bin/dep`. I even rebuilt `bin/dep` because I noticed this difference. CI wasn't happy earlier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343)*

**Comment by benesch** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[Gopkg.lock, line 12 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-L6hqA8GP2eYvPrZkR_Y:-L6hsrpZLpIXofFRwsxy:b-rowugw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ab8b5182d192809781951e78dea60be6ad58fa/Gopkg.lock#L12)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Btw, I did generate this using `bin/dep`. I even rebuilt `bin/dep` because I noticed this difference. CI wasn't happy earlier.
</blockquote></details>

Very weird. CI looks happy now, so I guess just leave as is!

---

*[Gopkg.toml, line 98 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-L6hp5b55QGylXKQF-X7:-L6hsv903webZbxT_jbB:b-jdap6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ab8b5182d192809781951e78dea60be6ad58fa/Gopkg.toml#L98)):*
Yeah, `dep ensure -add` is kind of dumb. From the help text:

> dep ensure -add github.com/pkg/foo
>
> Append version constraints to Gopkg.toml for one or more packages, if no such rules already exist.
>
> If the named packages are not already imported, also ensure they are present in Gopkg.lock and vendor/. As in the preceding example, packages introduced in this way will disappear on the next "dep ensure" if an import statement is not added first.

You're better off using `dep ensure` after you've added the import statement to at least one file to avoid the unnecessary constraint:

> dep ensure
>
> Solve the project's dependency graph, and place all dependencies in the vendor folder. If a dependency is in the lock file, use the version specified there. Otherwise, use the most recent version that can satisfy the constraints in the manifest file.

In this case you can just delete the constraint from Gopkg.toml and everything will be fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343)*

**Comment by petermattis** [comment]
TFTR!

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[Gopkg.toml, line 98 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-L6hp5b55QGylXKQF-X7:-L6huMF5arWLdz4LZLpv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ab8b5182d192809781951e78dea60be6ad58fa/Gopkg.toml#L98)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, `dep ensure -add` is kind of dumb. From the help text:

> dep ensure -add github.com/pkg/foo
>
> Append version constraints to Gopkg.toml for one or more packages, if no such rules already exist.
>
> If the named packages are not already imported, also ensure they are present in Gopkg.lock and vendor/. As in the preceding example, packages introduced in this way will disappear on the next "dep ensure" if an import statement is not added first.

You're better off using `dep ensure` after you've added the import statement to at least one file to avoid the unnecessary constraint:

> dep ensure
>
> Solve the project's dependency graph, and place all dependencies in the vendor folder. If a dependency is in the lock file, use the version specified there. Otherwise, use the most recent version that can satisfy the constraints in the manifest file.

In this case you can just delete the constraint from Gopkg.toml and everything will be fine.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-:-L6huRkRDYCm-l1eLP9h:b-814g8k)*

**Comment by petermattis** [comment]
PTAL at the 3rd commit which passes `SLACK_TOKEN` to `roachtest`.

**Comment by benesch** [comment]
:lgtm:

By the way, any idea what's gone wrong here? https://teamcity.cockroachdb.com/viewLog.html?buildId=544542&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_WorkloadNightly

---

Reviewed 5 of 5 files at r5, 3 of 3 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23343#-:-L6hyGxaJ6xSI3pbXCm1:b-b1pxzs)*

**Comment by petermattis** [comment]
Wedged retrieving logs.

> [22:22:59][Run roachtest] [ 914] backup2TB: retrieving logs (2h22m44s)
[22:23:59][Run roachtest] [ 915] backup2TB: retrieving logs (2h23m44s)
[22:24:59][Run roachtest] [ 916] backup2TB: retrieving logs (2h24m44s)
[22:25:59][Run roachtest] [ 917] backup2TB: retrieving logs (2h25m44s)
[22:26:59][Run roachtest] [ 918] backup2TB: retrieving logs (2h26m44s)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23343#-:-L6hyb0Y7DfwzK3Uz2iR:b-2zyp2w)*

**Comment by petermattis** [comment]
The cluster didn't even exist any longer. I failed the run.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23343#-:-L6hysig6E1JzTQgKnzk:b-54x8k6)*

**Comment by benesch** [comment]
Yeah, I noticed that. I wonder if there's something broken in our SCP implementation.

**Pull request merged**
