### PR TITLE
cli: remove auto-init with `cockroach start` without `--join`

### LINKED ISSUE #44116: cli: remove auto-init for `start` without `--join`.
The auto-init behavior of `cockroach start` without `--join` was marked as deprecated in 19.2. Remove it in 20.1.

Informs (and simplifies) #26722

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #44116. Informs #24118. Reviving #44112.

Release note (backward-incompatible change): A CockroachDB node
started with cockroach start without the --join flag no
longer automatically initializes the cluster. The cockrach init
command is now mandatory. The auto-initialization behavior had
been deprecated in version 19.2.

### CODE REVIEW

**Comment by irfansharif** [comment]
Will have to change `roachprod` to start using `init`, hm, that'll be a bit tedious.

**Comment by irfansharif** [comment]
Updated roachprod to use explicit `init`, tested against v19.1-v20.2; cockroachdb/cockroach-go PR is https://github.com/cockroachdb/cockroach-go/pull/81 (and I'll bump examples-orm after that lands).

**Review by tbg — APPROVED** [review]
I'll defer to @knz for final LGTM.

I checked out your PR to see what would happen if I run

```
./cockroach start --insecure
```

without a join flag. It does not error out. Do we already consider this a footgun? `./cockroach sql --insecure` will simply hang forever. Should we force a join flag to be supplied, even if it is empty (`--join=`)? I expect without some additional change here we will get lots of users starting a node that waits for init but without users realizing (maybe most of these users will be CRDB engineers but still, it's a potential issue).

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-:-MBsJP8z1TcMguySPLyK:b-xfgvku)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

___
*[pkg/acceptance/cluster/dockercluster.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsBLVa0V4r5xd0o0yQ:-MBsBLVbDuADa5oNWyas:b-kpl0s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa5bc1005b33bcfbfc65a517bef328b5114b7a6/pkg/acceptance/cluster/dockercluster.go#L488)):*
> ```Go
> 		firstNodeAddr = l.Nodes[0].nodeStr
> 	}
> 	cmd = append(cmd, "--join="+net.JoinHostPort(firstNodeAddr, base.DefaultPort))
> ```

Why give the first node `--join=:26257` instead of `l.Nodes[0].nodeStr`? Is `Nodes[0]` still unavailable at this point? Is this join flag useful?
___
*[pkg/base/test_server_args.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsCGFrBLt_urv-g1eF:-MBsCGFrBLt_urv-g1eG:b-y2d288) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa5bc1005b33bcfbfc65a517bef328b5114b7a6/pkg/base/test_server_args.go#L95)):*
> ```Go
> 	// their config. If WaitForBootstrap is set, that behavior is disabled
> 	// and the test becomes responsible for initializing the cluster.
> 	WaitForBootstrap bool
> ```

might be easier to understand what this does if you named it `NoAutoInitializeCluster` but your call.
___
*[pkg/cli/init.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsCYtQ8xBuimPUcs_K:-MBsCYtQ8xBuimPUcs_L:b-a3ot28) ([raw file](https://github.com/cockroachdb/cockroach/blob/492cde299282cafcdbcbef8bfcef47333fc35aac/pkg/cli/init.go#L62)):*
> ```Go
> 
> 	if _, err = c.Bootstrap(ctx, &serverpb.BootstrapRequest{}); err != nil {
> 		if strings.Contains(err.Error(), server.ErrClusterInitialized.Error()) {
> ```

Why did this check go away? Idempotency of `init`?
___
*[pkg/cmd/roachprod/install/cockroach.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsD4HoD-zb8wOxcrsZ:-MBsD4HoD-zb8wOxcrs_:b-5514x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa5bc1005b33bcfbfc65a517bef328b5114b7a6/pkg/cmd/roachprod/install/cockroach.go#L306)):*
> ```Go
> 		var initOut string
> 		display = fmt.Sprintf("%s: bootstrapping cluster", c.Name)
> 		c.Parallel(display, 1, 0, func(i int) ([]byte, error) {
> ```

Wait, why `c.Parallel()`? This is just hitting a single node, no?
___
*[pkg/server/server.go, line 1293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsDZwW8iBwMVReXyQ5:-MBsDZwW8iBwMVReXyQ6:b-75zm3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa5bc1005b33bcfbfc65a517bef328b5114b7a6/pkg/server/server.go#L1293)):*
> ```Go
> 		switch {
> 		case err == nil:
> 			log.Infof(ctx, "**** add additional nodes by specifying --join=%s", s.cfg.AdvertiseAddr)
> ```

Maybe just remove this log now that it's not prod code any more.
___
*[pkg/server/server.go, line 1300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsDXbI-X2MYwHgNlRN:-MBsDXbI-X2MYwHgNlRO:bwr3bn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa5bc1005b33bcfbfc65a517bef328b5114b7a6/pkg/server/server.go#L1300)):*
> ```Go
> 	}
> 
> 	log.Info(ctx, "awaiting init command or join with an already initialized node.")
> ```

`} else {`?

**Review by irfansharif — COMMENTED** [review]
I'm not sure what to do with the lone`cockroach start --insecure`, it does seem annoying. But forcing an empty join seems bad too? I wonder if it's possible/good enough to have `cockroach sql` prompt a warning asking the operator to ensure that the cluster is initialized, or the fact that it's waiting for initialization. @knz, thoughts?

---

I’m not sure how to work around https://github.com/cockroachdb/cockroach/issues/42083 to make sure my changes in https://github.com/cockroachdb/cockroach-go/pull/81 and https://github.com/cockroachdb/examples-orms/pull/109 all work for this branch, without me pushing to examples-orm master and letting CI pick that up. Is that the only way? Seems unwieldy.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-:-MBv1SBa6vRIoI_U6RfD:bfu2m2l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/acceptance/cluster/dockercluster.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsBLVa0V4r5xd0o0yQ:-MBuinmx0Vz9lnDCLcur:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa5bc1005b33bcfbfc65a517bef328b5114b7a6/pkg/acceptance/cluster/dockercluster.go#L488)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why give the first node `--join=:26257` instead of `l.Nodes[0].nodeStr`? Is `Nodes[0]` still unavailable at this point? Is this join flag useful?
</blockquote></details>

Done.
___
*[pkg/base/test_server_args.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsCGFrBLt_urv-g1eF:-MBuUU_g6kAsuSz8OYqf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa5bc1005b33bcfbfc65a517bef328b5114b7a6/pkg/base/test_server_args.go#L95)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

might be easier to understand what this does if you named it `NoAutoInitializeCluster` but your call.
</blockquote></details>

Done.
___
*[pkg/cli/init.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsCYtQ8xBuimPUcs_K:-MBuZLXT0-2ZeNWXUayw:b-k4zapf) ([raw file](https://github.com/cockroachdb/cockroach/blob/492cde299282cafcdbcbef8bfcef47333fc35aac/pkg/cli/init.go#L62)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why did this check go away? Idempotency of `init`?
</blockquote></details>

`init` is not idempotent, we still want to surface ErrClusterInitialized but I pulled the error message generated to to MaybeDecorateGRPCError, where we seem to do a lot of the same.
___
*[pkg/cmd/roachprod/install/cockroach.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsD4HoD-zb8wOxcrsZ:-MBuZnZl9K0My78YpU1P:b-bkupqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa5bc1005b33bcfbfc65a517bef328b5114b7a6/pkg/cmd/roachprod/install/cockroach.go#L306)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Wait, why `c.Parallel()`? This is just hitting a single node, no?
</blockquote></details>

It's hitting a single node, yup. Was cargo culting here from the setting of cluster settings in the block below, it nicely captures command process/failure outputs.
___
*[pkg/server/server.go, line 1293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsDZwW8iBwMVReXyQ5:-MBu_Y7h3v8YpfK7aY7B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa5bc1005b33bcfbfc65a517bef328b5114b7a6/pkg/server/server.go#L1293)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Maybe just remove this log now that it's not prod code any more.
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 1300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MBsDXbI-X2MYwHgNlRN:-MBu_kcA12RBUQq6ocg5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aa5bc1005b33bcfbfc65a517bef328b5114b7a6/pkg/server/server.go#L1300)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

`} else {`?
</blockquote></details>

Done.

**Comment by irfansharif** [comment]
> I checked out your PR to see what would happen if I run ./cockroach start --insecure without a join flag. It does not error out.

It now errors out. We apparently already emitted a warning earlier deprecating usage of `cockroach start` without `--join`, so no we can remove it entirely.

**Comment by irfansharif** [comment]
Ignore the first commit in this PR, I've sent it out in #51329.

**Comment by irfansharif** [comment]
Went ahead and merged https://github.com/cockroachdb/cockroach-go/pull/81 + https://github.com/cockroachdb/examples-orms/pull/109, which clears out the example-orm test suite run against this branch (and master). Should be reflected in the now green CI.

**Review by knz — COMMENTED** [review]
code LGTM, just minor concerns on the error objects

> Reviewed 1 of 18 files at r1, 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-:-MCLn7b_0hvv2h0ZzZCG:b-n0suxc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/cli/start.go, line 544 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MCLmVkEDiEZFqYIgG3O:-MCLmVkEDiEZFqYIgG3P:b98kri2) ([raw file](https://github.com/cockroachdb/cockroach/blob/506042b6c23b1ad926bf897c707f4d9e99c65d8d/pkg/cli/start.go#L544)):*
> ```Go
> 	// Check the --join flag.
> 	if !flagSetForCmd(cmd).Lookup(cliflags.Join.Name).Changed {
> 		err := errors.New("no --join flags provided to 'cockroach start'\n" +
> ```

Please consider using an error hint for the second sentence instead. This presents better on the console.
___
*[pkg/server/init.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MCLmsCrBytKTOxGK7yR:-MCLmsCrBytKTOxGK7yS:binkj0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/506042b6c23b1ad926bf897c707f4d9e99c65d8d/pkg/server/init.go#L34)):*
> ```Go
> // ErrClusterInitialized is reported when the Bootstrap RPC is run on
> // a node that is already part of an initialized cluster.
> var ErrClusterInitialized = fmt.Errorf("cluster has already been initialized")
> ```

Can  you add the error hint here too. Especially if the CLI code now returns `ErrClusterInitialized` without adding the hint itself.

**Review by irfansharif — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-:-MCSUprw2TnJvZadxZqf:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/cli/start.go, line 544 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MCLmVkEDiEZFqYIgG3O:-MCSUt5_B7LB_K-zLpEc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/506042b6c23b1ad926bf897c707f4d9e99c65d8d/pkg/cli/start.go#L544)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please consider using an error hint for the second sentence instead. This presents better on the console.
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51245#-MCLmsCrBytKTOxGK7yR:-MCSUzNX79MyBMiWkSPt:b4armfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/506042b6c23b1ad926bf897c707f4d9e99c65d8d/pkg/server/init.go#L34)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can  you add the error hint here too. Especially if the CLI code now returns `ErrClusterInitialized` without adding the hint itself.
</blockquote></details>

Discussed offline, decided to skip the hint here as the error is self-explanatory.

**Pull request merged**
