### PR TITLE
kvserver/loqrecovery: persist new replica ID in `RaftReplicaID`

### LINKED ISSUE #75133: cli: TestRemoveDeadReplicas failed
cli.TestRemoveDeadReplicas [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4149951&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4149951&tab=artifacts#/) on master @ [912964e02ddd951c77d4f71981ae18b3894e9084](https://github.com/cockroachdb/cockroach/commits/912964e02ddd951c77d4f71981ae18b3894e9084):

```
replica has lost quorum, recovering: r2:/System/NodeLiveness{-Max} [(n1,s1):1, (n3,s3):2, (n2,s2):3, (n4,s4):4, next=5, gen=6] -> r2:/System/NodeLiveness{-Max} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r3:/System/{NodeLivenessMax-tsd} [(n1,s1):1, (n3,s3):2, (n4,s4):3, (n2,s2):4, next=5, gen=6] -> r3:/System/{NodeLivenessMax-tsd} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r4:/System{/tsd-tse} [(n1,s1):1, (n3,s3):2, (n2,s2):3, (n4,s4):4, next=5, gen=6] -> r4:/System{/tsd-tse} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r5:/{Systemtse-Table/SystemConfigSpan/Start} [(n1,s1):1, (n4,s4):2, (n3,s3):3, (n2,s2):4, next=5, gen=6] -> r5:/{Systemtse-Table/SystemConfigSpan/Start} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r6:/Table/{SystemConfigSpan/Start-11} [(n3,s3):4, (n4,s4):2, (n2,s2):3, (n1,s1):5, next=6, gen=10] -> r6:/Table/{SystemConfigSpan/Start-11} [(n2,s2):6, next=7, gen=10]
replica has lost quorum, recovering: r7:/Table/1{1-2} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n3,s3):4, next=5, gen=6] -> r7:/Table/1{1-2} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r8:/Table/1{2-3} [(n3,s3):4, (n2,s2):2, (n4,s4):3, (n1,s1):5, next=6, gen=10] -> r8:/Table/1{2-3} [(n2,s2):6, next=7, gen=10]
replica has lost quorum, recovering: r9:/Table/1{3-4} [(n1,s1):1, (n2,s2):2, (n3,s3):3, (n4,s4):4, next=5, gen=6] -> r9:/Table/1{3-4} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r10:/Table/1{4-5} [(n1,s1):1, (n3,s3):2, (n2,s2):3, (n4,s4):4, next=5, gen=6] -> r10:/Table/1{4-5} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r11:/Table/1{5-6} [(n1,s1):1, (n2,s2):2, (n3,s3):3, (n4,s4):4, next=5, gen=6] -> r11:/Table/1{5-6} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r12:/Table/1{6-7} [(n1,s1):1, (n4,s4):2, (n3,s3):3, (n2,s2):4, next=5, gen=6] -> r12:/Table/1{6-7} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r13:/Table/1{7-8} [(n1,s1):1, (n4,s4):2, (n3,s3):3, (n2,s2):4, next=5, gen=6] -> r13:/Table/1{7-8} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r14:/Table/1{8-9} [(n1,s1):1, (n3,s3):2, (n2,s2):3, (n4,s4):4, next=5, gen=6] -> r14:/Table/1{8-9} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r15:/Table/{19-20} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n3,s3):4, next=5, gen=6] -> r15:/Table/{19-20} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r16:/Table/2{0-1} [(n1,s1):1, (n3,s3):2, (n4,s4):3, (n2,s2):4, next=5, gen=6] -> r16:/Table/2{0-1} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r17:/Table/2{1-2} [(n1,s1):1, (n3,s3):2, (n2,s2):3, (n4,s4):4, next=5, gen=6] -> r17:/Table/2{1-2} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r18:/Table/2{2-3} [(n1,s1):1, (n2,s2):2, (n4,s4):3, (n3,s3):4, next=5, gen=6] -> r18:/Table/2{2-3} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r19:/Table/2{3-4} [(n1,s1):1, (n4,s4):2, (n3,s3):3, (n2,s2):4, next=5, gen=6] -> r19:/Table/2{3-4} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r20:/Table/2{4-5} [(n1,s1):1, (n3,s3):2, (n4,s4):3, (n2,s2):4, next=5, gen=6] -> r20:/Table/2{4-5} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r21:/Table/2{5-6} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n3,s3):4, next=5, gen=6] -> r21:/Table/2{5-6} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r22:/Table/2{6-7} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n3,s3):4, next=5, gen=6] -> r22:/Table/2{6-7} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r23:/Table/2{7-8} [(n1,s1):1, (n4,s4):2, (n3,s3):3, (n2,s2):4, next=5, gen=6] -> r23:/Table/2{7-8} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r24:/Table/2{8-9} [(n3,s3):4, (n2,s2):2, (n4,s4):3, (n1,s1):5, next=6, gen=10] -> r24:/Table/2{8-9} [(n2,s2):6, next=7, gen=10]
replica has lost quorum, recovering: r25:/{Table/29-NamespaceTable/30} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n3,s3):4, next=5, gen=6] -> r25:/{Table/29-NamespaceTable/30} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r26:/NamespaceTable/{30-Max} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n3,s3):4, next=5, gen=6] -> r26:/NamespaceTable/{30-Max} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r27:/{NamespaceTable/Max-Table/32} [(n1,s1):1, (n2,s2):2, (n4,s4):3, (n3,s3):4, next=5, gen=6] -> r27:/{NamespaceTable/Max-Table/32} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r28:/Table/3{2-3} [(n1,s1):1, (n2,s2):2, (n3,s3):3, (n4,s4):4, next=5, gen=6] -> r28:/Table/3{2-3} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r29:/Table/3{3-4} [(n1,s1):1, (n3,s3):2, (n2,s2):3, (n4,s4):4, next=5, gen=6] -> r29:/Table/3{3-4} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r30:/Table/3{4-5} [(n1,s1):1, (n2,s2):2, (n4,s4):3, (n3,s3):4, next=5, gen=6] -> r30:/Table/3{4-5} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r31:/Table/3{5-6} [(n1,s1):1, (n3,s3):2, (n2,s2):3, (n4,s4):4, next=5, gen=6] -> r31:/Table/3{5-6} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r32:/Table/3{6-7} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n3,s3):4, next=5, gen=6] -> r32:/Table/3{6-7} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r33:/Table/3{7-8} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n3,s3):4, next=5, gen=6] -> r33:/Table/3{7-8} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r34:/Table/3{8-9} [(n1,s1):1, (n2,s2):2, (n3,s3):3, (n4,s4):4, next=5, gen=6] -> r34:/Table/3{8-9} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r35:/Table/{39-40} [(n1,s1):1, (n2,s2):2, (n3,s3):3, (n4,s4):4, next=5, gen=6] -> r35:/Table/{39-40} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r36:/Table/4{0-1} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n3,s3):4, next=5, gen=6] -> r36:/Table/4{0-1} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r37:/Table/4{1-2} [(n1,s1):1, (n4,s4):2, (n3,s3):3, (n2,s2):4, next=5, gen=6] -> r37:/Table/4{1-2} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r38:/Table/4{2-3} [(n1,s1):1, (n3,s3):2, (n4,s4):3, (n2,s2):4, next=5, gen=6] -> r38:/Table/4{2-3} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r39:/Table/4{3-4} [(n1,s1):1, (n2,s2):2, (n3,s3):3, (n4,s4):4, next=5, gen=6] -> r39:/Table/4{3-4} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r40:/Table/4{4-5} [(n2,s2):4, (n4,s4):2, (n3,s3):3, (n1,s1):5, next=6, gen=10] -> r40:/Table/4{4-5} [(n2,s2):6, next=7, gen=10]
replica has lost quorum, recovering: r41:/Table/4{5-6} [(n1,s1):1, (n4,s4):2, (n3,s3):3, (n2,s2):4, next=5, gen=6] -> r41:/Table/4{5-6} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r42:/Table/4{6-7} [(n1,s1):1, (n3,s3):2, (n4,s4):3, (n2,s2):4, next=5, gen=6] -> r42:/Table/4{6-7} [(n2,s2):5, next=6, gen=6]
replica has lost quorum, recovering: r43:/{Table/47-Max} [(n1,s1):1, (n3,s3):2, (n4,s4):3, (n2,s2):4, next=5, gen=6] -> r43:/{Table/47-Max} [(n2,s2):5, next=6, gen=6]
aborting intent: /Local/Range/System/tsd/RangeDescriptor (txn 4435d938-2f83-426c-a270-6aff4c966650)
Scanning replicas on store cluster_id:00578a7c-aef7-4181-b427-3f8d8aaa401a node_id:2 store_id:2  for dead peers []

id	is_live	replicas	is_decommissioning	membership	is_draining
3	false	43	true	decommissioning	false
4	false	43	true	decommissioning	false
    debug_test.go:391: expected replicas on {1,2,5,6} but got {1,2,5}
    --- FAIL: TestRemoveDeadReplicas/2/4/r=4 (26.39s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/server @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRemoveDeadReplicas.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-12480

### LINKED ISSUE #79074: kvserver: cli.TestRemoveDeadReplicas is flakey
**Describe the problem**

`F220330 17:00:53.520379 753692 kv/kvserver/replica_init.go:344 ⋮ [n2,s2,r10/5:‹/Table/1{4-5}›,raft] 3293  attempted to change replica's ID from 5 to 3`
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4735844?buildTab=artifacts#%2Ftest%2FlogTestRemoveDeadReplicas2006013815;%2Ftest%2FTestRemoveDeadReplicas_2_4_r%3D42995832643

Jira issue: CRDB-14534

### PR DESCRIPTION
**Pull request by erikgrinaker**
I'm not certain that this is the cause of #75133 (wasn't able to reproduce), but it seems plausible. I think it's something that we'd need to fix anyway, but I'm not familiar with all of the nuance here, so I'd appreciate careful reviews.

For reference, this was introduced in #75761.

---

**cli: persist new replica ID in `unsafe-remove-dead-replicas`**

The recently introduced local `RaftReplicaIDKey` was not updated when
`unsafe-remove-dead-replicas` changed the replica's ID. This could lead
to assertion failures.

Touches #75133.
Touches #79074.

Release note: None

**kvserver/loqrecovery: persist new replica ID in `RaftReplicaID`**

The recently introduced local `RaftReplicaIDKey` was not updated when
loss of quorum recovery changed the replica's ID. This could lead to
assertion failures.

Release note: None

### CODE REVIEW

**Review by aliher1911 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80470)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @sumeerbhola, and @tbg)

___
*[`pkg/kv/kvserver/loqrecovery/recovery_env_test.go` line 219 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80470#-N0aHf0kCTijMT64PzXq:-N0aHf0kCTijMT64PzXr:b-8kxkq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c98606e1f8c77e1d021da73692681f806ebed94/pkg/kv/kvserver/loqrecovery/recovery_env_test.go#L219)):*
> ```Go
> 		if err := sl.SetHardState(ctx, eng, hardState); err != nil {
> 			t.Fatalf("failed to save raft hard state: %v", err)
> 		}
> ```

We need to add:

		if err := sl.SetRaftReplicaID(ctx, eng, localReplicaID); err != nil {
			t.Fatalf("failed to set raft replica ID: %v", err)
		}

so that we could have initial store in line with expectations and not have replicaID = 0 for unchanged replicas.
We can return that value from buildReplicaDescriptorFromTestData where all data is prepared based on test structs.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80470)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @sumeerbhola)

___
*[`pkg/kv/kvserver/loqrecovery/recovery_env_test.go` line 219 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80470#-N0aHf0kCTijMT64PzXq:-N0e9BX_2-b2Q39LyXdN:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c98606e1f8c77e1d021da73692681f806ebed94/pkg/kv/kvserver/loqrecovery/recovery_env_test.go#L219)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

We need to add:

		if err := sl.SetRaftReplicaID(ctx, eng, localReplicaID); err != nil {
			t.Fatalf("failed to set raft replica ID: %v", err)
		}

so that we could have initial store in line with expectations and not have replicaID = 0 for unchanged replicas.
We can return that value from buildReplicaDescriptorFromTestData where all data is prepared based on test structs.
</blockquote></details>

Good call, done.

**Review by aliher1911 — APPROVED** [review]
🕺 🎉

**Comment by erikgrinaker** [comment]
bors r=aliher1911

**Pull request merged**
