### PR TITLE
workload/tpcc: expose tpc-c ops and duration as prometheus metrics

### PR DESCRIPTION
**Pull request by otan**
This commit adds prometheus metrics to the workload binary, exposing it
on port 2112 by default (configurable by CLI flag).

We also add some sample metrics to test the machinery:
* all histogram metrics are automatically added
* success and failure rate of tpc-c operations

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-:-MbjmRsNEndjurr7B7DR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — CHANGES_REQUESTED** [review]
Thank you for getting this started! I have a few suggestions that I think we should get to. Broadly this is avoiding singletons, and integrating the histograms with the existing histograms. By the end of this no particular workload should need to define prometheus histograms explicitly, they should exist as a byproduct of the calls to `hist.Get()` that are already present in the workloads (but workloads can go wild with additional pure prometheus metrics where desired).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-:-Mbk9y6-DvR8e_cOL2f3:betts7n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/workload/tpcc/worker.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-Mbk9UlB3I6RmqTX7f98:-Mbk9UlB3I6RmqTX7f99:b-c0zj7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L52)):*
> ```Go
> 
> 	// successCounter measures the number of successes for the given tx.
> 	successCounter prometheus.Counter
> ```

I don't think you need that, since you have 
___
*[pkg/workload/tpcc/worker.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-MbjySLB5cNB0eCF-fJW:-MbjySLB5cNB0eCF-fJX:b-jue2f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L94)):*
> ```Go
> func init() {
> 	for i, tx := range allTxs {
> 		allTxs[i].successCounter = prometheusMetrics.NewCounter(
> ```

This is too much singleton - `allTxs` is shared because it's all stateless, but now we're essentially adding state to it. We shouldn't do that, it is perfectly reasonable to want to invoke multiple copies of a workload in a single test and get dedicated stats for each. Maybe this doesn't work now for other reasons (we have a unit test for this workload so probably it does or at least almost should) but we should move things in the right direction. I think this would naturally fall out of my other comment below about unifying both versions of histograms we have here now. 

It's also worth thinking about how we'll distinguish metrics from different workloads all scraped by the same prometheus instance. `kv` and `bank` might both end up with a metric named `op_success`; how do they get ambiguated? Perhaps by convention the metric for workload `x` should be named `x_...`; I don't think we need to quite bake that into the framework (would lead to lots of annoying wrapping) but we should start it off that way.
___
*[pkg/workload/tpcc/worker.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-Mbk9hDz2ZzzzJO3MH_1:-Mbk9hDz2ZzzzJO3MH_2:b4m58w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L96)):*
> ```Go
> 		allTxs[i].successCounter = prometheusMetrics.NewCounter(
> 			prometheus.CounterOpts{
> 				Name: fmt.Sprintf("op_%s_success", tx.name),
> ```

I don't think you need a success counter, since you already have a success durations histogram. Histograms contain a count.
___
*[pkg/workload/tpcc/worker.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-Mbjy-284FCryD4EJZxd:-Mbjy-284FCryD4EJZxe:b-1oty9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L107)):*
> ```Go
> 		)
> 		allTxs[i].durationHistogram = prometheusMetrics.NewHistogram(
> 			prometheus.HistogramOpts{
> ```

I think you want to populate `HistogramOpts.Bucket` with some invocation of `ExponentialBuckets` or even more hand-crafted buckets. As is this is a very low-res histogram and as such not very useful.
I think we also want built-in parity between any of the existing histograms, i.e. when you define one of the ones we have now (`workload/histogram`) you also get a prometheus one (& have to pass a suitable registry in). We can't "just" rip out the existing histograms because they're windowed (i.e. they forget their history, so that we can produce printouts with "recent latency distributions"); they're serving different purposes. But we should unify them. I'm less bullish on making the prometheus histogram buckets match exactly the bucket boundaries of the hdrhistogram. I originally chose those and I don't think there's any reason to assume that I did a particularly good job. Maybe we can lean on @joshimhoff and @nvanbenschoten (with their SRE and Perf, respectively) hats on to tell us what good bucket boundaries are. We don't have many histograms here so we can afford a lot of buckets, but there's also no particular reason to go overboard. We can start with https://play.golang.org/p/TEUs4Vw7Z5e (start=0.5ms, factor=1.5, count=25) but it seems a little low-res in the hundreds-of-ms range; it does feel like the hdrhistogram approach is better since it scales more naturally but either way that bikeshed can also wait until we've landed the first cut.

I think my impl approach would be to make make `histogram.NewRegistry` also take a `prometheus.Registry` and to populate it when initializing the instance of the workload (not in the `init` function). As an exception, we'll create histograms as a byproduct of `hist.Get("newOrder")` and hist.Get("foo").RecordValue` will tee to both histograms. We'll expose the `prometheus.Registry` from the `hist` handle so we can add any additional metrics we care about (like the error count you have here, that's a good one).
___
*[pkg/workload/tpcc/worker.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-Mbk9aI56gvh41h2B_zB:-Mbk9aI56gvh41h2B_zC:bbpblyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L108)):*
> ```Go
> 		allTxs[i].durationHistogram = prometheusMetrics.NewHistogram(
> 			prometheus.HistogramOpts{
> 				Name: fmt.Sprintf("op_%s_durationMS", tx.name),
> ```

I read through https://prometheus.io/docs/practices/naming/ and https://prometheus.io/docs/instrumenting/writing_exporters/#target-labels-not-static-scraped-labels and I *think* this should be called `workload_tpcc_%s_success_seconds_bucket` with the `newOrder` etc camel case lowercased or snake-cased. This will also, in the common case, avoid a need to disambiguate metrics from multiple workloads when collected on a single prometheus instance (except when you're running multiple instances of TPCC).

**Review by tbg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66224)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/workload/tpcc/worker.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-Mbk9UlB3I6RmqTX7f98:-MbkDV8x95SXyViE3SH7:b-ewsx1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L52)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't think you need that, since you have 
</blockquote></details>

... a success histogram already. See other comment below.
___
*[pkg/workload/tpcc/worker.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-Mbjy-284FCryD4EJZxd:-MbkDQwP1Y9ByGaQXBC-:b-ati1xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L107)):*
> I think my impl approach would be to make make histogram.NewRegistry also take 

I meant that `histogram.NewRegistry` would also *make* a prometheus one.

**Review by otan — COMMENTED** [review]
We need singletons as we can only have one unique name for a metric per prometheus registry.
I've added the histogram to be default, and remove the hooks to make workload contain the prometheus registry. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-:-MbnxMoS99YuL1RV2lvB:b-cyh7y3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/workload/tpcc/worker.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-MbjySLB5cNB0eCF-fJW:-MbnYj-0AB4j2X2cwENN:b-x4rv9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L94)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This is too much singleton - `allTxs` is shared because it's all stateless, but now we're essentially adding state to it. We shouldn't do that, it is perfectly reasonable to want to invoke multiple copies of a workload in a single test and get dedicated stats for each. Maybe this doesn't work now for other reasons (we have a unit test for this workload so probably it does or at least almost should) but we should move things in the right direction. I think this would naturally fall out of my other comment below about unifying both versions of histograms we have here now. 

It's also worth thinking about how we'll distinguish metrics from different workloads all scraped by the same prometheus instance. `kv` and `bank` might both end up with a metric named `op_success`; how do they get ambiguated? Perhaps by convention the metric for workload `x` should be named `x_...`; I don't think we need to quite bake that into the framework (would lead to lots of annoying wrapping) but we should start it off that way.
</blockquote></details>

you can only initialize one counter with that name, which is why i've done it this way.
i'll apply the naming changes.
___
*[pkg/workload/tpcc/worker.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-Mbk9hDz2ZzzzJO3MH_1:-MbnYgv_-WWzcceElhEZ:bn9np9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L96)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't think you need a success counter, since you already have a success durations histogram. Histograms contain a count.
</blockquote></details>

i like having it explicit (more obvious to search + use). the histogram byproduct is nice, but it's nice having a clear "success" and "error" message.
in other words, how strongly do you feel about this?
___
*[pkg/workload/tpcc/worker.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-Mbk9aI56gvh41h2B_zB:-MbnYO70Ew0FyiZF4nYF:bwkapwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L108)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I read through https://prometheus.io/docs/practices/naming/ and https://prometheus.io/docs/instrumenting/writing_exporters/#target-labels-not-static-scraped-labels and I *think* this should be called `workload_tpcc_%s_success_seconds_bucket` with the `newOrder` etc camel case lowercased or snake-cased. This will also, in the common case, avoid a need to disambiguate metrics from multiple workloads when collected on a single prometheus instance (except when you're running multiple instances of TPCC).
</blockquote></details>

the `_bucket` is already added automatically when you run it, but renamed to `_duration_milliseconds`:


i prefer `ms` as the unit of measurement, as most operations are in the scale.

**Comment by otan** [comment]
___
*[pkg/workload/tpcc/worker.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-Mbk9aI56gvh41h2B_zB:-MboVgx2518SUHV7TrUT:b9mr98q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L108)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

the `_bucket` is already added automatically when you run it, but renamed to `_duration_milliseconds`:


i prefer `ms` as the unit of measurement, as most operations are in the scale.

</blockquote></details>

hmm, nvm, i'll do seconds

**Comment by otan** [comment]
In case it's helpful, here's how the metrics currently look:

```
# HELP workload_tpcc_delivery_duration_seconds 
# TYPE workload_tpcc_delivery_duration_seconds histogram
workload_tpcc_delivery_duration_seconds_bucket{le="0.005"} 0
workload_tpcc_delivery_duration_seconds_bucket{le="0.01"} 0
workload_tpcc_delivery_duration_seconds_bucket{le="0.025"} 0
workload_tpcc_delivery_duration_seconds_bucket{le="0.05"} 1
workload_tpcc_delivery_duration_seconds_bucket{le="0.1"} 2
workload_tpcc_delivery_duration_seconds_bucket{le="0.25"} 2
workload_tpcc_delivery_duration_seconds_bucket{le="0.5"} 2
workload_tpcc_delivery_duration_seconds_bucket{le="1"} 2
workload_tpcc_delivery_duration_seconds_bucket{le="2.5"} 2
workload_tpcc_delivery_duration_seconds_bucket{le="5"} 2
workload_tpcc_delivery_duration_seconds_bucket{le="10"} 2
workload_tpcc_delivery_duration_seconds_bucket{le="+Inf"} 2
workload_tpcc_delivery_duration_seconds_sum 0.117479
workload_tpcc_delivery_duration_seconds_count 2
# HELP workload_tpcc_delivery_error The total number of error delivery events.
# TYPE workload_tpcc_delivery_error counter
workload_tpcc_delivery_error 0
# HELP workload_tpcc_delivery_success The total number of successful delivery events.
# TYPE workload_tpcc_delivery_success counter
workload_tpcc_delivery_success 2
# HELP workload_tpcc_newOrder_duration_seconds 
# TYPE workload_tpcc_newOrder_duration_seconds histogram
workload_tpcc_newOrder_duration_seconds_bucket{le="0.005"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="0.01"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="0.025"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="0.05"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="0.1"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="0.25"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="0.5"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="1"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="2.5"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="5"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="10"} 0
workload_tpcc_newOrder_duration_seconds_bucket{le="+Inf"} 0
workload_tpcc_newOrder_duration_seconds_sum 0
workload_tpcc_newOrder_duration_seconds_count 0
# HELP workload_tpcc_newOrder_error The total number of error newOrder events.
# TYPE workload_tpcc_newOrder_error counter
workload_tpcc_newOrder_error 0
# HELP workload_tpcc_newOrder_success The total number of successful newOrder events.
# TYPE workload_tpcc_newOrder_success counter
workload_tpcc_newOrder_success 0
# HELP workload_tpcc_orderStatus_duration_seconds 
# TYPE workload_tpcc_orderStatus_duration_seconds histogram
workload_tpcc_orderStatus_duration_seconds_bucket{le="0.005"} 1
workload_tpcc_orderStatus_duration_seconds_bucket{le="0.01"} 1
workload_tpcc_orderStatus_duration_seconds_bucket{le="0.025"} 1
workload_tpcc_orderStatus_duration_seconds_bucket{le="0.05"} 4
workload_tpcc_orderStatus_duration_seconds_bucket{le="0.1"} 4
workload_tpcc_orderStatus_duration_seconds_bucket{le="0.25"} 4
workload_tpcc_orderStatus_duration_seconds_bucket{le="0.5"} 4
workload_tpcc_orderStatus_duration_seconds_bucket{le="1"} 4
workload_tpcc_orderStatus_duration_seconds_bucket{le="2.5"} 4
workload_tpcc_orderStatus_duration_seconds_bucket{le="5"} 4
workload_tpcc_orderStatus_duration_seconds_bucket{le="10"} 4
workload_tpcc_orderStatus_duration_seconds_bucket{le="+Inf"} 4
workload_tpcc_orderStatus_duration_seconds_sum 0.127844
workload_tpcc_orderStatus_duration_seconds_count 4
# HELP workload_tpcc_orderStatus_error The total number of error orderStatus events.
# TYPE workload_tpcc_orderStatus_error counter
workload_tpcc_orderStatus_error 0
# HELP workload_tpcc_orderStatus_success The total number of successful orderStatus events.
# TYPE workload_tpcc_orderStatus_success counter
workload_tpcc_orderStatus_success 4
# HELP workload_tpcc_payment_duration_seconds 
# TYPE workload_tpcc_payment_duration_seconds histogram
workload_tpcc_payment_duration_seconds_bucket{le="0.005"} 0
workload_tpcc_payment_duration_seconds_bucket{le="0.01"} 1
workload_tpcc_payment_duration_seconds_bucket{le="0.025"} 4
workload_tpcc_payment_duration_seconds_bucket{le="0.05"} 4
workload_tpcc_payment_duration_seconds_bucket{le="0.1"} 4
workload_tpcc_payment_duration_seconds_bucket{le="0.25"} 4
workload_tpcc_payment_duration_seconds_bucket{le="0.5"} 4
workload_tpcc_payment_duration_seconds_bucket{le="1"} 4
workload_tpcc_payment_duration_seconds_bucket{le="2.5"} 4
workload_tpcc_payment_duration_seconds_bucket{le="5"} 4
workload_tpcc_payment_duration_seconds_bucket{le="10"} 4
workload_tpcc_payment_duration_seconds_bucket{le="+Inf"} 4
workload_tpcc_payment_duration_seconds_sum 0.052997
workload_tpcc_payment_duration_seconds_count 4
# HELP workload_tpcc_payment_error The total number of error payment events.
# TYPE workload_tpcc_payment_error counter
workload_tpcc_payment_error 0
# HELP workload_tpcc_payment_success The total number of successful payment events.
# TYPE workload_tpcc_payment_success counter
workload_tpcc_payment_success 4
# HELP workload_tpcc_stockLevel_duration_seconds 
# TYPE workload_tpcc_stockLevel_duration_seconds histogram
workload_tpcc_stockLevel_duration_seconds_bucket{le="0.005"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="0.01"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="0.025"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="0.05"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="0.1"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="0.25"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="0.5"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="1"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="2.5"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="5"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="10"} 0
workload_tpcc_stockLevel_duration_seconds_bucket{le="+Inf"} 0
workload_tpcc_stockLevel_duration_seconds_sum 0
workload_tpcc_stockLevel_duration_seconds_count 0
# HELP workload_tpcc_stockLevel_error The total number of error stockLevel events.
# TYPE workload_tpcc_stockLevel_error counter
workload_tpcc_stockLevel_error 0
# HELP workload_tpcc_stockLevel_success The total number of successful stockLevel events.
# TYPE workload_tpcc_stockLevel_success counter
workload_tpcc_stockLevel_success 0
```

**Review by tbg — COMMENTED** [review]
Thanks! That looks a lot better. I added a commit that does a bit more work to streamline things, let me know if I've accidentally regressed on anything. The singleton is gone and the way TPCC adds extra prometheus metrics is, for my taste, now idiomatic.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-:-MbpruBP7ckCKKHZtHPv:b-pnu093)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @otan)

___
*[pkg/workload/tpcc/worker.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-MbjySLB5cNB0eCF-fJW:-Mbpd-HaBP6EE-sgq2nE:boe5lh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L94)):*
> you can only initialize one counter with that name, which is why i've done it this way.

Sharing the registry across workloads using a singleton is part of the problem. I added a commit that un-singletonizes everything. WDYT?
___
*[pkg/workload/tpcc/worker.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66224#-Mbk9hDz2ZzzzJO3MH_1:-MbpoeCT9PHqjpw05ph3:b-wo65qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b653666bcb5d965e6f6a7c01c4fceda5a4d23d86/pkg/workload/tpcc/worker.go#L96)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i like having it explicit (more obvious to search + use). the histogram byproduct is nice, but it's nice having a clear "success" and "error" message.
in other words, how strongly do you feel about this?
</blockquote></details>

I'm not going to push back more since it's not consequential, but I can't really say that I see your point - look, they're even right next to each other. To me this duplication adds confusion, if anything. The only value is in the HELP text and we could give the histograms a better help text; they're "helpless" right now because we haven't gone through the trouble of improving the `w.hists.Get()` thing but we could (not saying we should at this point). I guess I feel strongly but I'm willing to drop it regardless :smile: 

```
# HELP workload_tpcc_delivery_success_duration_seconds 
# TYPE workload_tpcc_delivery_success_duration_seconds histogram
workload_tpcc_delivery_success_duration_seconds_bucket{le="0.005"} 0
[...]
workload_tpcc_delivery_success_duration_seconds_sum 0.059154021
workload_tpcc_delivery_success_duration_seconds_count 2
# HELP workload_tpcc_delivery_success_total The total number of successful delivery transactions.
# TYPE workload_tpcc_delivery_success_total counter
workload_tpcc_delivery_success_total 2
```

**Review by tbg — APPROVED** [review]

**Comment by tbg** [comment]
Hrm, I don't seem to be able to push to your branch (did you perhaps disable that? I generally find it useful). Here are my commits:

https://github.com/cockroachdb/cockroach/pull/66313

**Pull request closed without merging**
