### PR TITLE
issues: fixes and improvements

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### issues: make IssueFormatter an interface

Epic: none
Release note: None

#### issues: use a bullet list for parameters

Change the formatting of parameters to use a bullet list.

Epic: none
Release note: None

#### issues: add top-level notes

Add functionality to optionally include a top-level note in the issue
description.

Epic: none
Release note: None

#### roachtest: clean up TestCreatePostRequest

Clean up this test to use explicit field keys when initializing
structs, otherwise changing the fields is a nightmare.

Epic: none
Release note: None

#### issues: fix and clean up label logic

This change cleans up the logic around the labels of issues. We now
have an explicit list of labels in `PostRequest`, which defaults to
`C-test-failure,release-blocker` if not set. This makes things easier
and fixes a current bug where roachtest issues have `release-blocker`
even when the test spec has `NoReleaseBlocker` set.

We add functionality for requiring a set of labels to match before
adopting queries. This will be used in an upcoming roachtest change to
separate issues filed in coverage or metamorphic build modes.

We also simplify the logic to always require `O-robot, C-test-failure`
in order to adopt an existing issue.

Epic: none
Release note: None

### CODE REVIEW

**Review by renatolabs — COMMENTED** [review]
In hindsight, I wish we had chosen an approach where we had `B-coverage-enabled` and `B-coverage-disabled` tags instead of relying on presence/absence. Would make the behaviour more explicit (no one would ever ask "wait, is coverage enabled here?"), and would also simplify our life by removing the mustHave / mustNotHave logic.

But overall, the cleanups in the commits here are very appreciated, thank you!

> Reviewed 2 of 2 files at r1, 31 of 31 files at r2, 11 of 11 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-:-NkbJunK-sc8JoPbdnOt:b-cv3mw0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @srosenberg)

___
*[`pkg/cmd/bazci/githubpost/githubpost.go` line 717 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbHFAH33JXMCypme0l:-NkbHFAH33JXMCypme0m:bqidqll) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/bazci/githubpost/githubpost.go#L717)):*
> ```Go
> 		Artifacts:   "meta",
> 		HelpCommand: issues.ReproductionCommandFromString(repro),
> 		Labels:      []string{issues.TestFailureLabel, issues.ReleaseBlockerLabel, "metamorphic-failure"},
> ```

Any reasons for not using `DefaultLabels`?
___
*[`pkg/cmd/internal/issues/issues.go` line 324 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbIrO374o4n05lXAg9:-NkbIrO374o4n05lXAgA:bkqe46) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/internal/issues/issues.go#L324)):*
> ```Go
> 		// We want to at least require the one label to avoid pathological
> 		// situations in which a test name is so generic that it matches lots of
> 		// random issues.
> ```

This logic is unexpected to me. Why special-case `TestFailureLabel`? Why not _always_ add `RobotLabel` to `mustHave`? IMO, robot issues should never comment on user-created issues anyway (I thought that was existing behaviour).
___
*[`pkg/cmd/internal/issues/issues.go` line 510 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbJJqU1aTW0nH2WNQE:-NkbJJqU1aTW0nH2WNQF:b-c7alox) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/internal/issues/issues.go#L510)):*
> ```Go
> 	Labels []string
> 	// AdoptIssueLabelMatchSet is the set of labels whose presence or absence must
> 	// match in order to adopt an issue.
> ```

Adopt as in "comment on"? Not sure we I have seen the "adopt" terminology used before.
___
*[`pkg/cmd/internal/issues/issues.go` line 514 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbJRD4-A3TRAcVTOEX:-NkbJRD4-A3TRAcVTOEY:b-zhp0ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/internal/issues/issues.go#L514)):*
> ```Go
> 	// For each label l in this set: if l is part of Labels, then any adopted
> 	// issue must also have this label set; it l is not part of Labels, than any
> 	// adopted issue must also NOT have this label set.
> ```

I'm unsure about the semantics about this field. So, if I understand it right, roachtest would _always_ need to set (for example): B-coverage to `AdoptIssueLabelMatchSet` to encode that it should or should not exist? The fact that the meaning of the tag is indirect and relative to `Labels` is a confusing.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/bazci/githubpost/githubpost.go` line 717 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbHFAH33JXMCypme0l:-NkcHkrq7U-a9CM9vXnV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/bazci/githubpost/githubpost.go#L717)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Any reasons for not using `DefaultLabels`?
</blockquote></details>

Done.
___
*[`pkg/cmd/internal/issues/issues.go` line 324 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbIrO374o4n05lXAg9:-NkcHtpV6YgfvaPhw5yG:bb7kqez) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/internal/issues/issues.go#L324)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

This logic is unexpected to me. Why special-case `TestFailureLabel`? Why not _always_ add `RobotLabel` to `mustHave`? IMO, robot issues should never comment on user-created issues anyway (I thought that was existing behaviour).
</blockquote></details>

This is existing behavior, I don't have more context than the existing code. The comment does say `Sometimes users open issues about flakes and don't assign all the labels`; it sounds like we do want to adopt issues without the `O-robot` label.
___
*[`pkg/cmd/internal/issues/issues.go` line 510 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbJJqU1aTW0nH2WNQE:-NkcIVxfAeaG9WuunptR:b1rz2t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/internal/issues/issues.go#L510)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Adopt as in "comment on"? Not sure we I have seen the "adopt" terminology used before.
</blockquote></details>

I got it from an existing comment, `adopt` does seem appropriate to me. Maybe "reuse" would be better?
```
	// We carry out two searches below, one attempting to find an issue that we
	// adopt (i.e. add a comment to) and one finding "related issues", i.e. those
	// that would match if it weren't for their branch label.
```
___
*[`pkg/cmd/internal/issues/issues.go` line 514 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbJRD4-A3TRAcVTOEX:-NkcIh3q4hOgb_r22tdf:b-dmv821) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/internal/issues/issues.go#L514)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I'm unsure about the semantics about this field. So, if I understand it right, roachtest would _always_ need to set (for example): B-coverage to `AdoptIssueLabelMatchSet` to encode that it should or should not exist? The fact that the meaning of the tag is indirect and relative to `Labels` is a confusing.
</blockquote></details>

The semantics are non-trivial but I couldn't find any easier way. The alternative is to have two pairs of labels "must-have" and "must-not-have", but then the logic of building those must move up in the caller. It seemed cleaner to pass the set of labels that we care about, for the purposes of saying that issues are "duplicates".

**Review by srosenberg — APPROVED** [review]
>  I wish we had chosen an approach where we had `B-coverage-enabled` and `B-coverage-disabled` tags instead of relying on presence/absence.

I agree that's a more precise encoding of a boolean build feature. Why don't we rename to `B-coverage-enabled` but keep the mustHave/mustNotHave logic since that's also dependent on renaming pre-existing labels?

Radu, thanks for all the improvements!

:lgtm: 

> Reviewed 1 of 37 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-:-Nl4i9X-7Ai5fIWfSJJ3:byz1bri)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)

___
*[`pkg/cmd/internal/issues/issues.go` line 324 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbIrO374o4n05lXAg9:-Nl4hBp71-uBHa6qXTij:bniqc4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/internal/issues/issues.go#L324)):*
> IMO, robot issues should never comment on user-created issues anyway (I thought that was existing behaviour).

The separation makes sense to me. Should we reflect this change in this PR? The worst-case scenario is we end up creating a new issue instead of posting on the existing one (assuming it didn't have `RobotLabel` before the aforementioned change).

**Review by RaduBerinde — COMMENTED** [review]
The rename sounds fine to me.

Thea idea of having to put `B-coverage-disabled` (and `B-metamorphic-disabled`, and who knows what else in the future) on ALL issues seems daunting to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-:-Nl4mNEh6XJVuK8VjSB0:b-qnh9wg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)

**Comment by RaduBerinde** [comment]
I will go ahead and rename the B-coverage and B-metamorphic to B-coverage-enabled and B-metamorphic-enabled. I will update this PR with these new label and change the issue adopting behavior as suggested.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115302)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/internal/issues/issues.go` line 324 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbIrO374o4n05lXAg9:-Nl5c4nx23Mt3OfCpCtI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/internal/issues/issues.go#L324)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

> IMO, robot issues should never comment on user-created issues anyway (I thought that was existing behaviour).

The separation makes sense to me. Should we reflect this change in this PR? The worst-case scenario is we end up creating a new issue instead of posting on the existing one (assuming it didn't have `RobotLabel` before the aforementioned change).
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115302)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/internal/issues/issues.go` line 324 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115302#-NkbIrO374o4n05lXAg9:-Nl5cJQa4jx5cGX4aBMe:bda883f) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e6f434a1fcc424814e41b4ba610d077d373172/pkg/cmd/internal/issues/issues.go#L324)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'll wait for someone to take a quick look over r7 -> r12

**Review by srosenberg — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 38 of 38 files at r8, 31 of 31 files at r9, 11 of 11 files at r10, 1 of 1 files at r11, 37 of 37 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115302)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs)

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
