### PR TITLE
kv,storage: persist gateway node id in transaction intents

### LINKED ISSUE #72303: sql, kv: KV to provide an interface for SQL to provide identifiers to be stored in Txn Intent
Related to #71965

SQL would like KV to store SQL-provided identifiers (e.g. gateway node's NodeID/SQLInstanceID) in the Txn Intent. This means we need to introduce a KV interface that is consumed by SQL to provide such identifier to be stored.

This is really useful for SQL to collect rich contention event information.

### PR DESCRIPTION
**Pull request by AlexTalks**
This change augments the `TxnMeta` protobuf structure to include the
gateway node ID (responsible for initiating the transaction) when
serializing the intent.  By doing so, this commit enables the Contention
Event Store proposed in #71965, utilizing option 2.

Release note: None

### CODE REVIEW

**Review by Azhng — COMMENTED** [review]
Thanks for working on this and this is awesome! I just have some minor style nits and rest looks all good from SQL Obs :+1: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-:-MqtsJ0s8Hyw1GePIe9A:b-glrht2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @lidorcarmel, and @nvanbenschoten)

___
*[pkg/kv/txn.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MqtjBM779xe1KpVoPTi:-MqtjBM8BqRA_PewezuU:b-psvisu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/kv/txn.go#L128)):*
> ```Go
> 	now := db.clock.NowAsClockTimestamp()
> 	kvTxn := roachpb.MakeTransaction("unnamed", nil, roachpb.NormalUserPriority, now.ToTimestamp(),
> 		db.clock.MaxOffset().Nanoseconds(), int32(db.ctx.NodeID.SQLInstanceID()))
> ```

nit: let's keep the original formatting here? 

``` golang
	kvTxn := roachpb.MakeTransaction(
		"unnamed",
		nil, // baseKey
		roachpb.NormalUserPriority,
		now.ToTimestamp(),
		db.clock.MaxOffset().Nanoseconds(),
                int32(db.ctx.NodeID.SQLInstanceID()),
	)

```
___
*[pkg/kv/kvclient/kvcoord/dist_sender_test.go, line 2171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MqtjcWtEjh4GdPuh6WC:-MqtjcWuDMg1uNfY03rr:b-1c26t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L2171)):*
> ```Go
> 	ds := NewDistSender(cfg)
> 
> 	txn := roachpb.MakeTransaction("foo", nil, 1.0, clock.Now(), 0, 1)
> ```

nit: let's add the inline `/* sqlNodeID */` comment here 
___
*[pkg/kv/kvserver/replica_test.go, line 4552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-Mqtk0YsBUBZyyjt-d0U:-Mqtk0YsBUBZyyjt-d0V:b-wtq1yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/kv/kvserver/replica_test.go#L4552)):*
> ```Go
> 	keyB := roachpb.Key("b")
> 	// Start a transaction early to get a low timestamp.
> 	txn := roachpb.MakeTransaction("test", keyA, roachpb.NormalUserPriority, tc.Clock().Now(), 0 /* maxOffsetNs */, 0 /* sqlNodeID */)
> ```

small nit: wrap the long line here ?

**Review by nvb — COMMENTED** [review]
Nice! I haven't made my way through all of the files that changed yet, but left a few comments on the important ones.

> Reviewed 13 of 51 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-:-MquPHHr8Y0QyG3WI_Xe:b-p722v7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @Azhng, and @lidorcarmel)

___
*[pkg/kv/txn.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MquLPiy2itBHsBUH-Kj:-MquLPiy2itBHsBUH-Kk:b-nhdvgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/kv/txn.go#L120)):*
> ```Go
> //
> // See also db.NewTxn().
> func NewTxn(ctx context.Context, db *DB, gatewayNodeID roachpb.NodeID) *Txn {
> ```

We had discussed not needing this `gatewayNodeID` param anymore in any of these constructors if/when we make it possible to determine whether `SQLInstanceID` is a reference to a KV node or to a SQL tenant node. Do you mind opening an issue to track that refactor?
___
*[pkg/kv/txn.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MqtjBM779xe1KpVoPTi:-MquL2668VexfLU84lEI:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/kv/txn.go#L128)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: let's keep the original formatting here? 

``` golang
	kvTxn := roachpb.MakeTransaction(
		"unnamed",
		nil, // baseKey
		roachpb.NormalUserPriority,
		now.ToTimestamp(),
		db.clock.MaxOffset().Nanoseconds(),
                int32(db.ctx.NodeID.SQLInstanceID()),
	)

```
</blockquote></details>

+1
___
*[pkg/roachpb/data.go, line 916 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MquOt_T35X8GaiL8T_h:-MquOt_T35X8GaiL8T_i:bnbhall) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/roachpb/data.go#L916)):*
> ```Go
> // write conflicts in a way that avoids starvation of long-running
> // transactions (see Replica.PushTxn).
> // TODO(sarkesian): Write comment about sqlNodeID
> ```

Do you mind addressing this TODO in this PR?
___
*[pkg/sql/logictest/logic.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MquKUMUD1_EWGYf4I3N:-MquKUMUD1_EWGYf4I3O:b-kj931i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/sql/logictest/logic.go#L281)):*
> ```Go
> //    Introduces a sleep period. Example: sleep 2s
> //
> //  - user <username> <nodeidx=N>
> ```

nit: `[nodeidx=N]`
___
*[pkg/storage/enginepb/mvcc3.proto, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MquMBCE3ap6tvdfYWmC:-MquMBCE3ap6tvdfYWmD:b-63j7nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/storage/enginepb/mvcc3.proto#L126)):*
> ```protobuf
>   reserved 8;
> 
>   // The node ID of the SQL node where this transaction originated.
> ```

What do you think about calling this either `CoordinatorNodeID` or `GatewayNodeID`? I'm not sure that `SQLNodeID` implies the right thing if this is a transaction that is being started by a KV node.

This actually raises a few interesting questions. What exactly is this representing? And what should it represent?

Currently, the transaction coordinator (`TxnCoordSender`) is always the same as the SQL gateway that uses the transaction. But you could imagine an architecture where this is not the case. For instance, in a reimagined architecture, it could be possible for the SQL executor to use a remote `TxnCoordSender`. So if these were decoupled, which component would this be a reference to? I think the answer is the "gateway" and not the "coordinator", because that's what houses the transaction's SQL metadata.

However, you could also imagine an architecture where the KV layer might want to know about the coordinator node ID of a given transaction, because it might want to talk to it directly. For instance, we may want a transaction that aborts some other transaction to reach out to its coordinator and inform it directly, instead of waiting an arbitrary amount of time for the aborted transaction to find out that it's aborted. So this might be an opportune time to begin storing the coordinator ID in intents.

What do you think?
___
*[pkg/storage/enginepb/mvcc3.proto, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MquMrD8EvZS9Jtz1RVX:-MquMrD8EvZS9Jtz1RVY:bj0lhma) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/storage/enginepb/mvcc3.proto#L130)):*
> ```protobuf
>   // representing either a SQLInstanceID of a SQL pod or a gateway NodeID,
>   // and is utilized for SQL Observability.
>   // TODO(sarkesian): Refactor/include gogoproto.casttype when #73309 completes.
> ```

Do you mind mentioning which type we plan to use? Is it `GenericNodeID`?

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73500)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @lidorcarmel, and @nvanbenschoten)

___
*[pkg/kv/txn.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MquLPiy2itBHsBUH-Kj:-MqzjEcDBAIuXRa1FBT1:bco2ey9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/kv/txn.go#L120)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We had discussed not needing this `gatewayNodeID` param anymore in any of these constructors if/when we make it possible to determine whether `SQLInstanceID` is a reference to a KV node or to a SQL tenant node. Do you mind opening an issue to track that refactor?
</blockquote></details>

OK - created #73871.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73500)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @Azhng, @lidorcarmel, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_test.go, line 4552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-Mqtk0YsBUBZyyjt-d0U:-Mqzs6On1TCsILRZeI4o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/kv/kvserver/replica_test.go#L4552)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

small nit: wrap the long line here ?
</blockquote></details>

Done.
___
*[pkg/roachpb/data.go, line 916 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MquOt_T35X8GaiL8T_h:-MqzsGst14gFGJ5ibCFc:bm70rpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/roachpb/data.go#L916)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you mind addressing this TODO in this PR?
</blockquote></details>

Ha!  Thanks for catching, I forgot to come back to this.
___
*[pkg/storage/enginepb/mvcc3.proto, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MquMBCE3ap6tvdfYWmC:-Mr-2-wt6GkEcKfx79f5:bavbbt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/storage/enginepb/mvcc3.proto#L126)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What do you think about calling this either `CoordinatorNodeID` or `GatewayNodeID`? I'm not sure that `SQLNodeID` implies the right thing if this is a transaction that is being started by a KV node.

This actually raises a few interesting questions. What exactly is this representing? And what should it represent?

Currently, the transaction coordinator (`TxnCoordSender`) is always the same as the SQL gateway that uses the transaction. But you could imagine an architecture where this is not the case. For instance, in a reimagined architecture, it could be possible for the SQL executor to use a remote `TxnCoordSender`. So if these were decoupled, which component would this be a reference to? I think the answer is the "gateway" and not the "coordinator", because that's what houses the transaction's SQL metadata.

However, you could also imagine an architecture where the KV layer might want to know about the coordinator node ID of a given transaction, because it might want to talk to it directly. For instance, we may want a transaction that aborts some other transaction to reach out to its coordinator and inform it directly, instead of waiting an arbitrary amount of time for the aborted transaction to find out that it's aborted. So this might be an opportune time to begin storing the coordinator ID in intents.

What do you think?
</blockquote></details>

After speaking directly we agreed to use `CoordinatorNodeID` as the field name... it should be noted that if we do have a scenario in which a SQL executor uses a remote `TxnCoordSender`, it would be necessary (for the purposes of SQL Observability) to have this field represent the node of the SQL executor, and if we wanted to keep track of the KV coordinator node, we'd need a separate field.  It sounds like this scenario has been discussed and decided against previously, however, so using the more generic name `CoordinatorNodeID` should be fine.
___
*[pkg/storage/enginepb/mvcc3.proto, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-MquMrD8EvZS9Jtz1RVX:-Mr-2mnw9wQT5SOVR8uY:b-4le9vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e61aad61368d031364479d41670a5a307a076bf1/pkg/storage/enginepb/mvcc3.proto#L130)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you mind mentioning which type we plan to use? Is it `GenericNodeID`?
</blockquote></details>

Also followed up on this directly - we agreed this would be a `GenericNodeID`.

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 27 of 51 files at r1, 1 of 3 files at r2, 18 of 20 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-:-Mr38m5gEpJWZOJzSWhW:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @Azhng, and @lidorcarmel)

___
*[pkg/sql/logictest/testdata/logic_test/contention_event, line 80 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/73500#-Mr38hnaBwX9UyVgbvLR:-Mr38hnaBwX9UyVgbvLS:bdmbd8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a741d85bf79a8ecfbd73f9a89aefa301bee3d80/pkg/sql/logictest/testdata/logic_test/contention_event#L80)):*
> ```
> true
> 
> # check that the sql instance id / gateway node id is properly stored with the contention event
> ```

nit: this comment needs a small update to use the new name.

**Comment by ajwerner** [comment]
Seems like maybe this and some other change skew: https://teamcity.cockroachdb.com/viewLog.html?buildId=3932844&buildTypeId=Cockroach_UnitTests
`roachvet: pkg/kv/kvserver/client_replica_test.go:547:64: not enough arguments in call to roachpb.MakeTransaction`

bors r-

sorry @AlexTalks

**Comment by AlexTalks** [comment]
Ack!  Thanks for catching, will rebase.

**Pull request merged**
