### PR TITLE
vendor: Bump pebble to 488fb5bfea764c8ba7f77b279d4faf6724939839

### PR DESCRIPTION
**Pull request by itsbilal**
Things of note:
- internal/intern: add string interning facility
- internal/record: fix blockage when using min-sync-interval
- internal/manifest: add FileMetadata.CreationTime
- db: force flush of queued memtables when manually compacting
- open: Add helper to get version of pebble last used to write

Release note: None.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

You didn't like https://github.com/cockroachdb/cockroach/pull/45458? I see that you picked up another commit here. I'll go ahead and close my PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45499#-:-M16lN2g6970E6NiObh-:b4yo06f)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis and @sumeerbhola)

**Comment by itsbilal** [comment]
Haha, my bad. I didn't realize that one was open - got buried in my inbox. Today's been an interesting day.

Thanks for the review!

**Comment by itsbilal** [comment]
Wow, something's really cursed with this commit and bors.

bors r+

**Pull request merged**
