### PR TITLE
cli: Open RocksDB in ReadOnly mode for debug commands

### PR DESCRIPTION
**Pull request by pocockn**
https://github.com/cockroachdb/cockroach/issues/21130

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Thanks @pocockn! This is looking good. I just have a few critiques that should be quick to address.

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/db.cc, line 1649 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3ineul6XMS755RoPCT:-L3ineul6XMS755RoPCU:bga22nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/c-deps/libroach/db.cc#L1649)):*
> ```cpp
> 
>   rocksdb::Status status;
>   if(db_opts.read_only) {                   
> ```

This line looks incorrectly formatted. Could you run `make c-deps-fmt`? You may need to install `clang-format` to do so (http://brewformulas.org/ClangFormat on mac)

---

*[pkg/cli/debug.go, line 142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3imq5LW_UWypfWtTzN:-L3imq5LW_UWypfWtTzO:brji4ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/pkg/cli/debug.go#L142)):*
> ```Go
> 	}
> 
> 	db, err := openExistingStore(args[0], stopper, true)
> ```

Per our [style guide](https://github.com/cockroachdb/cockroach/blob/master/docs/style.md#inline-comments-for-arguments-to-function-calls), could you change each `true` and `false` argument you added to have an inline comment like `,true /* readOnly */)`

---

*[pkg/cli/debug.go, line 809 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3inAq1Oa5UHEzA3KmH:-L3inAq1Oa5UHEzA3KmI:b-qnxg0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/pkg/cli/debug.go#L809)):*
> ```Go
> 	}
> 
> 	db, err := openExistingStore(args[0], stopper, false)
> ```

Do any tests fail (`make test`) if you change this to `true`?

---

*[pkg/cli/debug_test.go, line 71 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3inGurYGdtBstVLP68:-L3inGurYGdtBstVLP69:b-hrhy4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/pkg/cli/debug_test.go#L71)):*
> ```Go
> 		},
> 	} {
> 		_, err := openExistingStore(test.dir, stopper, false)
> ```

Same thing with the inline comment.

---

*[pkg/storage/engine/rocksdb.go, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3ilsseZ179bLHhe1jZ:-L3ilssfMPHbgAI-egQq:b-c06dks) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/pkg/storage/engine/rocksdb.go#L445)):*
> ```Go
> 	// to C CCL code.
> 	ExtraOptions []byte
> 	// ReadOnly will open the database in read only mode if set to true
> ```

Two nits here:
1. move this up right below `MustExist`
2. add a period at the end of the comment

---

*[pkg/storage/engine/rocksdb.go, line 597 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3im3AJ79OqCnzbE8zq:-L3im3AJ79OqCnzbE8zr:b-9h84ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/pkg/storage/engine/rocksdb.go#L597)):*
> ```Go
> 			must_exist:        C.bool(r.cfg.MustExist),
> 			extra_options:     goToCSlice(r.cfg.ExtraOptions),
> 			read_only:         C.bool(r.cfg.ReadOnly),
> ```

Same, move this right below `must_exist`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-:-L3io1NpE4afB5BxuURG:b116yr4)*

**Comment by pocockn** [comment]
Regarding line 809 in debug.go, if I change it to true tests still pass, is this what you would expect?

**Comment by pocockn** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/db.cc, line 1649 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3ineul6XMS755RoPCT:-L3tKYFIFFavKoseIRUi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/c-deps/libroach/db.cc#L1649)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This line looks incorrectly formatted. Could you run `make c-deps-fmt`? You may need to install `clang-format` to do so (http://brewformulas.org/ClangFormat on mac)
</blockquote></details>

Done.

---

*[pkg/cli/debug.go, line 142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3imq5LW_UWypfWtTzN:-L3tKOp4fXH8UW7PJ1tm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/pkg/cli/debug.go#L142)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Per our [style guide](https://github.com/cockroachdb/cockroach/blob/master/docs/style.md#inline-comments-for-arguments-to-function-calls), could you change each `true` and `false` argument you added to have an inline comment like `,true /* readOnly */)`
</blockquote></details>

Done.

---

*[pkg/cli/debug.go, line 809 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3inAq1Oa5UHEzA3KmH:-L3tKQzlLkitKJamEoqV:b-9ukwr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/pkg/cli/debug.go#L809)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do any tests fail (`make test`) if you change this to `true`?
</blockquote></details>

Tests still all pass

---

*[pkg/cli/debug_test.go, line 71 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3inGurYGdtBstVLP68:-L3tKUuejfl0gSSZ4Jtl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/pkg/cli/debug_test.go#L71)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same thing with the inline comment.
</blockquote></details>

Done.

---

*[pkg/storage/engine/rocksdb.go, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3ilsseZ179bLHhe1jZ:-L3tKVUdvcz4olO4Po8F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/pkg/storage/engine/rocksdb.go#L445)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Two nits here:
1. move this up right below `MustExist`
2. add a period at the end of the comment
</blockquote></details>

Done.

---

*[pkg/storage/engine/rocksdb.go, line 597 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-L3im3AJ79OqCnzbE8zq:-L3tKVzgFF1pGbVBb2oT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30bbc9cf48ecf73c6e78c1babfe3b9c3fb14b07c/pkg/storage/engine/rocksdb.go#L597)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same, move this right below `must_exist`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778)*

**Comment by nvanbenschoten** [comment]
:lgtm: thanks for help with this @pocockn! This is a nice improvement. I'll merge this once all tests pass on CI.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21778#-:-L4NXQST5v7Tarl2GtFe:bc8ib63)*

**Pull request merged**
