### PR TITLE
storage: Reset leaseholder's request stats on split

### PR DESCRIPTION
**Pull request by a-robinson**

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16574#-:-KmoE7cUhiKmokHMsm9o:bnfp4nl)*

**Comment by BramGruneir** [comment]
hmm... not sure if there's a good way to test this.  Perhaps something in `client_split_test`? 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16574#-:-KmoEBKeU0zXT2GwX59L:b-ab0ta4)*

**Comment by a-robinson** [comment]
I'll try to squeeze this into a test if you think it's worth it, but I was just going to skip it since it's not critical for correctness. The only thing that would happen if we didn't reset the stats is that might make a rebalancing decision that assumes a bit too much load on the range, but if we make the wrong decision it'll be undone afterwards anyways. Let me know what you think.

**Comment by BramGruneir** [comment]
SGTM, I was just thinking if it was easy to squeeze in there, it wouldn't hurt.  But no need to create a new test or force it.

**Pull request merged**
