### PR TITLE
sql: fix two problems with groupNode optimization for MIN/MAX 

### LINKED ISSUE #15725: sql: incorrect aggregations for MIN/MAX with an index
When we are able to optimize a `SELECT MIN(k)` by reading just one row from an index, we have to add a `k IS NOT NULL` constraint to skip any `NULL`s. 

Unfortunately, the code only does this when there is an existing filter:
```go
  if where != nil && where.filter != nil && group != nil {
    // Allow the group-by to add an implicit "IS NOT NULL" filter.
    where.filter = where.ivarHelper.Rebind(group.isNotNullFilter(where.filter), false, false)
  }
```
```
root@:26257/test> SELECT * FROM kv;
+---+------+
| k |  v   |
+---+------+
| 1 | NULL |
| 2 |    2 |
| 3 |    3 |
+---+------+
(3 rows)
root@:26257/test> SELECT min(v) FROM kv;
+--------+
| min(v) |
+--------+
| NULL   |
+--------+
(1 row)
root@:26257/test> SELECT min(v) FROM kv@primary;
+--------+
| min(v) |
+--------+
|      2 |
+--------+
(1 row)
```

Another problem is that we apply this optimization even if there is a `GROUP BY`, which is incorrect.

```
root@:26257/test> SELECT min(v) FROM kv GROUP BY k;
+--------+
| min(v) |
+--------+
| NULL   |
+--------+
(1 row)
root@:26257/test> SELECT min(v) FROM kv@primary GROUP BY k;
+--------+
| min(v) |
+--------+
| NULL   |
|      2 |
|      3 |
+--------+
(3 rows)
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
This PR fixes the two problems described in #15725:
 - we don't always apply the IS NOT NULL constraint when we use the single-row
   optimization.
 - we incorrectly use the optimization when there is a GROUP BY.

Fixes #15725.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
*[pkg/sql/group.go, line 505 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15735#-KjStoZuluqnUxRS338x:-KjStoZuluqnUxRS338y:b-b402f5) ([raw file](https://github.com/cockroachdb/cockroach/blob/69c4ee8c52c24d016e84138bedaad357ad5b854e/pkg/sql/group.go#L505)):*
> ```Go
> 	}
> 
> 	if len(n.funcs) != 1 {
> ```

NB: this is not a new restriction - the old code would never accept multiple functions either (it was just obfuscated).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15735)*

**Comment by RaduBerinde** [comment]
This fix is something we should consider for 1.0.1.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15735#-:-KjSuSn6NfhxnuIPkbAF:bexnrxj)*

**Comment by knz** [comment]
Oh, my. What a bug, subtle and hidden in plain sight.
Nicely spotted, and a good and elegant fix.
:lgtm: and I concur this is high priority.

---

Reviewed 3 of 4 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15735#-:-KjT61s9C5ZIEaXi7NAE:b6ex7l3)*

**Comment by knz** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15735)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/render.go, line 287 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15735#-KjTBZfLTrt4y1mUc8GM:-KjTBZfMhqIXBNaGpMTN:b-ko3oxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7527de6f9110736357f0b61b9f9ed71b513312b7/pkg/sql/render.go#L287)):*
> ```Go
> 
> 	if group != nil && group.requiresIsNotNullFilter() {
> 		if where == nil {
> ```

Oops, I had forgotten this check. It was still working ok because it just added fiterNode on top of filterNode and it all got optimized later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15735)*

**Pull request merged**
