### PR TITLE
sql: scaffolding for db metadata update job

### LINKED ISSUE #127891: sql: add scaffolding for job to compute table metadata and insert into system table
A new job will be used to fetch table metadata for all user and system tables in the cluster, and update those records in a newly created system table. This issue just tracks adding the boilerplate required for the new job.

Job type: forever running bg job

Next: https://github.com/cockroachdb/cockroach/issues/128993

Jira issue: CRDB-40655

Epic CRDB-37558

### PR DESCRIPTION
**Pull request by xinhaoz**
This commit creates a new forever running BG job called UpdateCachedTableMetadata. This is just some scaffolding - the job doesn't do anything right now but it will be used to populate the system table storing cached table metadata used by obs surfaces.

Epic: CRDB-37558
Fixes: #127891

Release note: None

### CODE REVIEW

**Review by kyle-a-wong — APPROVED** [review]
Just had a comment about the epic in the commit message, but otherwise, :lgtm:

> Reviewed 8 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128470#-:-O5E2Fp-4EwxPMOtnpF6:b-do79w2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @stevendanna and @xinhaoz)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128470#-O5Dzn3p-Fvnjb8lSeI6):*
nit: This should be CRDB-37558 right?



_Code quote:_
```
Epic: none
```

**Comment by xinhaoz** [comment]
@kyle-a-wong Just renamed some stuff (updateCachedTableMetadata -> updateTableMetadataCache), can you re-approve if that looks good? Also added git issue and epic link!

**Review by kyle-a-wong — APPROVED** [review]
> Reviewed 9 of 17 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128470)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna and @xinhaoz)

___
*[`pkg/upgrade/upgradebase/testing_knobs.go` line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128470#-O5Ej_i4C4JYg_ndlUT3:-O5Ej_i4C4JYg_ndlUT4:b17lvjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2a8b1357ae6b6c5942f9de62799482189ff7c7d/pkg/upgrade/upgradebase/testing_knobs.go#L77)):*
> ```Go
> 	SkipMVCCStatisticsJobBootstrap bool
> 
> 	SkipUpdateCachedTableMetadataBootstrap bool
> ```

nit: Should this be updated too, or was it left out intentionally?



_Code quote:_
```Go
SkipUpdateCachedTableMetadataBootstrap 
```

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Pull request merged**
