### PR TITLE
gcjob,partitionccl: fixes for gcjob and zone configs on enum-partitioned tables

### LINKED ISSUE #62029: sql: Drop zone configurations on indexes that will be GCed, to avoid problems in the GC path
#61751 identified an issue where indexes which were queued for GC (in that case, because of a PK change) would still have their zone configs intact.  This caused a problem in the index GC code as the necessary infrastructure wasn't in-place to drop the zone configurations at GC time and a panic ensued.  #61751 addressed this problem, specifically for REGIONAL BY ROW tables, by cleaning up the zone configurations as part of the schema change job which queued up the index for GC.  

We need a more general fix however, for tables which can get into this state organically (i.e. not through the use of the new MR abstractions).  

Since this issue has the potential to bring down a node in the index GC job, I'm marking it as a 21.1 GA blocker.

### PR DESCRIPTION
**Pull request by ajwerner**
See individual commits. This ends up being two problems, neither of which are solved the way that was originally discussed in #62029. The hydration issue is easily side-stepped (as it should be). The dropped table issue as well. 

Fixes #62029.

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
Nice!  Makes me wonder if we want to revert parts of https://github.com/cockroachdb/cockroach/pull/62034 which solved this problem specific to REGIONAL BY ROW tables.  I'm assuming your general solution here would fix that case too.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-:-MWVbTuk322PXi3r0EpT:b-ii9yvp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

___
*[pkg/ccl/partitionccl/drop_test.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVdCRNCt6YGoyCBSiv:-MWVdCRNCt6YGoyCBSiw:b-ocr78y) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca364f4835a52c60e2f0831d32d95b3c4c4c9ea/pkg/ccl/partitionccl/drop_test.go#L224)):*
> ```Go
> 		//  * Drop the type.
> 		//  * Wait for the index to be cleaned up, which would have crashed before the
> 		//    this fix
> ```

Nit: It's not clear here the fix to which you're referring.  Might be good to include the PR number.
___
*[pkg/ccl/partitionccl/drop_test.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVdM-d5kWqqlKVOxzH:-MWVdM-d5kWqqlKVOxzI:bmmrt2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca364f4835a52c60e2f0831d32d95b3c4c4c9ea/pkg/ccl/partitionccl/drop_test.go#L225)):*
> ```Go
> 		//  * Wait for the index to be cleaned up, which would have crashed before the
> 		//    this fix
> 		//  * Set a short GC TTL on everything
> ```

Nit: this list isn't exactly ordered.  Might want to think about ordering it. (e.g. GC setting occurs before dropping the index).
___
*[pkg/ccl/partitionccl/drop_test.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVdfI_C6igC8Eeb7b-:-MWVdfI_C6igC8Eeb7b0:b-mewb10) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca364f4835a52c60e2f0831d32d95b3c4c4c9ea/pkg/ccl/partitionccl/drop_test.go#L255)):*
> ```Go
> 	  ALTER INDEX t@idx CONFIGURE ZONE USING gc.ttlseconds = 1;
> 	  DROP INDEX t@idx;
> 	  SET sql_safe_updates = false;
> ```

Nit: Is this strictly necessary?  I thought that sql_safe_updates defaulted to true if you're not in the CLI.
___
*[pkg/sql/gcjob/index_garbage_collection.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVcKnOAuMVHRWBemzF:-MWVcKnP3Asj2bjBcgO7:b-z30u9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffcafad9221a81018dbd2986069a4d2af322a6/pkg/sql/gcjob/index_garbage_collection.go#L71)):*
> ```Go
> 		// zone configs for the dropped indexes, if any.
> 		if err := descs.Txn(
> 			ctx, execCfg.Settings, execCfg.LeaseManager, execCfg.InternalExecutor, execCfg.DB, func(
> ```

Nit: might be slightly more readable if we define this func as a variable above this if branch, and call the variable.
___
*[pkg/sql/gcjob/index_garbage_collection.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVbzEk84BgSO9xEHuu:-MWVbzEk84BgSO9xEHuv:b-9e3h42) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffcafad9221a81018dbd2986069a4d2af322a6/pkg/sql/gcjob/index_garbage_collection.go#L77)):*
> ```Go
> 					ctx, txn, parentID, tree.ObjectLookupFlags{
> 						CommonLookupFlags: tree.CommonLookupFlags{
> 							Required:       true,
> ```

Do we need AvoidCached here?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/ccl/partitionccl/drop_test.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVdCRNCt6YGoyCBSiv:-MWZHH-qACJENt6vpHhl:bi2kpra) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca364f4835a52c60e2f0831d32d95b3c4c4c9ea/pkg/ccl/partitionccl/drop_test.go#L224)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: It's not clear here the fix to which you're referring.  Might be good to include the PR number.
</blockquote></details>

There's mixed feelings about that in the codebase. I've heard it both ways. The main argument against such things is that it's GitHub clickbait and git holds the history via blame. 
___
*[pkg/ccl/partitionccl/drop_test.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVdM-d5kWqqlKVOxzH:-MWZN_vED1iU-in6verS:btcmi4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca364f4835a52c60e2f0831d32d95b3c4c4c9ea/pkg/ccl/partitionccl/drop_test.go#L225)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: this list isn't exactly ordered.  Might want to think about ordering it. (e.g. GC setting occurs before dropping the index).
</blockquote></details>

That's there...

```
		//  * Set a short GC TTL on the index.
		//  * Drop the index.
```
___
*[pkg/ccl/partitionccl/drop_test.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVdfI_C6igC8Eeb7b-:-MWZNhmt6tYhduips52S:b-hwnhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca364f4835a52c60e2f0831d32d95b3c4c4c9ea/pkg/ccl/partitionccl/drop_test.go#L255)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Is this strictly necessary?  I thought that sql_safe_updates defaulted to true if you're not in the CLI.
</blockquote></details>

No, this is leftover from an older version where I was dropping a column. Also, it was there because I was just copying these commands into a shell to exercise reproductions. Removed. 
___
*[pkg/sql/gcjob/index_garbage_collection.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVcKnOAuMVHRWBemzF:-MWZYN4x1ed45dTXeUOK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffcafad9221a81018dbd2986069a4d2af322a6/pkg/sql/gcjob/index_garbage_collection.go#L71)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: might be slightly more readable if we define this func as a variable above this if branch, and call the variable.
</blockquote></details>

Done.
___
*[pkg/sql/gcjob/index_garbage_collection.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVbzEk84BgSO9xEHuu:-MWZHXFP1x5SFGKcqD9j:btin4mj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffcafad9221a81018dbd2986069a4d2af322a6/pkg/sql/gcjob/index_garbage_collection.go#L77)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Do we need AvoidCached here?
</blockquote></details>

I don't see a reason not to. We're in an async job so latency really doesn't matter. If I were to revamp these flags, I'd make this the default. I may well do just that later in the 21.2 cycle. Reasoning about an inconsistent view is fundamentally difficult and bug prone. Avoiding the cache is always valid. Anything that isn't on the hot path shouldn't use the leased descriptors.
___
*[pkg/sql/gcjob/index_garbage_collection.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWZOdJM45RYDaQ_yXo5:-MWZOdJM45RYDaQ_yXo6:bjmfteu) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca364f4835a52c60e2f0831d32d95b3c4c4c9ea/pkg/sql/gcjob/index_garbage_collection.go#L90)):*
> ```Go
> 		}
> 
> 		if err := completeDroppedIndex(ctx, execCfg, parentTable, index.IndexID, progress); err != nil {
> ```

If you want to get annoyed about unnecessary round-trips, this thing does another transaction. Could be refactored. As it's all an async job, I'm really not worried about it.

**Review by ajstorm — APPROVED** [review]
A couple more nits below, but other than that, :lgtm: 

> Reviewed 4 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-:-MWdtB1e4rRwaVpiTy78:b-addekp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

___
*[pkg/ccl/partitionccl/drop_test.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVdM-d5kWqqlKVOxzH:-MWdqtHtDjeAYdCYJMX9:brnl351) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca364f4835a52c60e2f0831d32d95b3c4c4c9ea/pkg/ccl/partitionccl/drop_test.go#L225)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

That's there...

```
		//  * Set a short GC TTL on the index.
		//  * Drop the index.
```

</blockquote></details>

Could be missing something, but I don't see where you're setting a short GC TTL on the index.
___
*[pkg/sql/gcjob/index_garbage_collection.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVbzEk84BgSO9xEHuu:-MWdshEw5NYZRwrQ8o38:b-cbf9wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffcafad9221a81018dbd2986069a4d2af322a6/pkg/sql/gcjob/index_garbage_collection.go#L77)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't see a reason not to. We're in an async job so latency really doesn't matter. If I were to revamp these flags, I'd make this the default. I may well do just that later in the 21.2 cycle. Reasoning about an inconsistent view is fundamentally difficult and bug prone. Avoiding the cache is always valid. Anything that isn't on the hot path shouldn't use the leased descriptors.
</blockquote></details>

Nit: Piotr from Reviewable is guaranteeing me that I'm not missing anything.  Looks like this AvoidCached still isn't being set.  Was that the intention?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62421)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @otan)

___
*[pkg/ccl/partitionccl/drop_test.go, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVdM-d5kWqqlKVOxzH:-MWdxZ-28Ayg7Ch9llAv:b-alzbvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca364f4835a52c60e2f0831d32d95b3c4c4c9ea/pkg/ccl/partitionccl/drop_test.go#L225)):*
> ```
> ALTER INDEX t@idx CONFIGURE ZONE USING gc.ttlseconds = 1;
> ```
___
*[pkg/sql/gcjob/index_garbage_collection.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62421#-MWVbzEk84BgSO9xEHuu:-MWdzIPg1CQ4EfAZ40FT:b-fn8mpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffcafad9221a81018dbd2986069a4d2af322a6/pkg/sql/gcjob/index_garbage_collection.go#L77)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Piotr from Reviewable is guaranteeing me that I'm not missing anything.  Looks like this AvoidCached still isn't being set.  Was that the intention?
</blockquote></details>

:facepalm:

**Pull request merged**
