### PR TITLE
storage/engine: optionalize + document MVCCGet

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: modulo small comment about the extra allocation caused by transforming the pointer to a slice.

> Reviewed 34 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-:-LTyx-mP9cXN6K3GygSD:b-60ji4f)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_get.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-LTywSi80gtZuJLDfeZz:-LTywSi80gtZuJLDfe_-:b-7r2isr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e30c912935c359b4e218be196173f9927239165/pkg/storage/batcheval/cmd_get.go#L47)):*
> ```Go
> 	var intents []roachpb.Intent
> 	if intent != nil {
> 		intents = append(intents, *intent)
> ```

This results in an extra allocation as we allocated once to return the `*intent` and again here to create the backing array for the slice. Is this worth worry about? Probably not.
___
*[pkg/storage/engine/engine.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-LTyvS884_tPi_9Gnazh:-LTyvS895UDztfU1-WPZ:b-ezartc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd790ac4b5a0bf65a55e336913a4d185ee365f3/pkg/storage/engine/engine.go#L107)):*
> ```Go
> 	// MVCCGet is the internal implementation of the family of package-level
> 	// MVCCGet functions. The notable difference is that key/value pairs are
> 	// returned raw, as a buffer of varint-prefixed slices, alternating from key
> ```

This doesn't look accurate. `Iterator.MVCCGet` has the same interface as the package-level `MVCCGet`.
___
*[pkg/storage/engine/mvcc.go, line 681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-LTyvgPe8h0ZlfUTAHxi:-LTyvgPe8h0ZlfUTAHxj:b-ql76nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a833d5c9c9f18648cd4e2c714667c36531d6047/pkg/storage/engine/mvcc.go#L681)):*
> ```Go
> // ...
> // keyA_Timestamp_0 : value of version_0
> // keyB : MVCCMetadata of keyB
> ```

Is there a documentation comment elsewhere about the MVCC key structure? Seems a shame to remove this if this is the only comment describing the structure.
___
*[pkg/storage/engine/rocksdb.go, line 2257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-LTyvzx987c0AYZlJ-GW:-LTyvzx987c0AYZlJ-GX:b-gf97ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd790ac4b5a0bf65a55e336913a4d185ee365f3/pkg/storage/engine/rocksdb.go#L2257)):*
> ```Go
> 	state := C.MVCCGet(
> 		r.iter, goToCSlice(key), goToCTimestamp(timestamp),
> 		goToCTxn(opts.Txn), C.bool(!opts.Inconsistent), C.bool(opts.Tombstones),
> ```

I wonder if you should go the extra mile and change the `libroach` `MVCCGet` function parameter from `consistent` to `inconsistent`. It will be a bit confusing in the future to stumble across that polarity change.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33213)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/batcheval/cmd_get.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-LTywSi80gtZuJLDfeZz:-LTzhrjo9iYRTMpfQlIf:b-iulmdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e30c912935c359b4e218be196173f9927239165/pkg/storage/batcheval/cmd_get.go#L47)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This results in an extra allocation as we allocated once to return the `*intent` and again here to create the backing array for the slice. Is this worth worry about? Probably not.
</blockquote></details>

Yeah, I figured it was safe because nothing perf-sensitive uses the Get API AFAIK. (E.g., result.FromIntents allocates again to construct the result.)
___
*[pkg/storage/engine/engine.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-LTyvS884_tPi_9Gnazh:-LTzhd-zCWwukqf_5wsj:b-9o38d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd790ac4b5a0bf65a55e336913a4d185ee365f3/pkg/storage/engine/engine.go#L107)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This doesn't look accurate. `Iterator.MVCCGet` has the same interface as the package-level `MVCCGet`.
</blockquote></details>

Oops, thanks for the fact check. Done.
___
*[pkg/storage/engine/mvcc.go, line 681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-LTyvgPe8h0ZlfUTAHxi:-LTzheaw7LRHv3KwTev7:buwbh3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a833d5c9c9f18648cd4e2c714667c36531d6047/pkg/storage/engine/mvcc.go#L681)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there a documentation comment elsewhere about the MVCC key structure? Seems a shame to remove this if this is the only comment describing the structure.
</blockquote></details>

Good point. Not that I can find. I've moved the diagram to the doc.go in this package.
___
*[pkg/storage/engine/rocksdb.go, line 2257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-LTyvzx987c0AYZlJ-GW:-LTzjWof425ZQnnGhXXm:b9dlmbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd790ac4b5a0bf65a55e336913a4d185ee365f3/pkg/storage/engine/rocksdb.go#L2257)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if you should go the extra mile and change the `libroach` `MVCCGet` function parameter from `consistent` to `inconsistent`. It will be a bit confusing in the future to stumble across that polarity change. 
</blockquote></details>

Yeah, I'd been thinking about that. Done. Thanks for the push.

**Review by petermattis — APPROVED** [review]
:shipit:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-:-LU0gwgO31QO8WxmPK59:b-xr9eiq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/batcheval/cmd_get.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33213#-LTywSi80gtZuJLDfeZz:-LU0grBq9S0z6WNmo6-i:b-1a2qpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e30c912935c359b4e218be196173f9927239165/pkg/storage/batcheval/cmd_get.go#L47)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, I figured it was safe because nothing perf-sensitive uses the Get API AFAIK. (E.g., result.FromIntents allocates again to construct the result.)
</blockquote></details>

Yeah, I'm ok with this.

**Comment by benesch** [comment]
TFTR!

bors r=petermattis

**Pull request merged**
