### PR TITLE
*: give better name to certain cluster settings

### PR DESCRIPTION
**Pull request by knz**
Follows #109048.
Epic: CRDB-29380

The following settings have been renamed so they group together under a common prefix:

| Previous name                                                | New name                                               |
|--------------------------------------------------------------|--------------------------------------------------------|
| `tenant_external_io_default_bytes_allowed_before_accounting` | `tenant_cost_control.external_io.byte_usage_allowance` |
| `tenant_external_io_ru_accounting_mode`                      | `tenant_cost_control.external_io.ru_accounting_mode`   |
| `tenant_cost_control_period`                                 | `tenant_cost_control.token_request_period`             |
| `tenant_cpu_usage_allowance`                                 | `tenant_cost_control.cpu_usage_allowance`              |
| `tenant_usage_instance_inactivity`                           | `tenant_cost_control.instance_inactivity.timeout`      |

Similarly:

| Previous name                                                       | New name                                                          |
|---------------------------------------------------------------------|-------------------------------------------------------------------|
| `sql.multi_region.allow_abstractions_for_secondary_tenants.enabled` | `sql.virtual_cluster.feature_access.multiregion.enabled`         |
| `sql.zone_configs.allow_for_secondary_tenant.enabled`               | `sql.virtual_cluster.feature_access.zone_configs.enabled`         |
| `sql.split_at.allow_for_secondary_tenant.enabled`                   | `sql.virtual_cluster.feature_access.manual_range_split.enabled`   |
| `sql.scatter.allow_for_secondary_tenant.enabled`                    | `sql.virtual_cluster.feature_access.manual_range_scatter.enabled` |

The following setting have been renamed because they are not specific to multi-tenancy:

| Previous name                                   | New name                                                  |
|-------------------------------------------------|-----------------------------------------------------------|
| `sql.tenant_ru_estimation.enabled`              | `sql.explain_analyze.include_ru_estimation.enabled`       |
| `server.secondary_tenants.redact_trace.enabled` | `trace.redact_traces_at_virtual_cluster_boundary.enabled` |
| `server.secondary_tenants.authorization.mode`   | `server.virtual_cluster_authorization.mode`               |
| `spanconfig.tenant_coalesce_adjacent.enabled`   | `spanconfig.range_coalescing.application.enabled`         |
| `spanconfig.storage_coalesce_adjacent.enabled`  | `spanconfig.range_coalescing.system.enabled`              |
| `spanconfig.tenant_limit` | `spanconfig.virtual_cluster.max_spans` |

The following have been renamed to e-emphasize "tenants" and for
coherence with the use of the key `cluster` in SQL and HTTP requests:

| Previous name                                            | New name                                                         |
|----------------------------------------------------------|------------------------------------------------------------------|
| `server.controller.default_tenant`                       | `server.controller.default_target_cluster`                       |
| `server.controller.default_tenant.check_service.enabled` | `server.controller.default_target_cluster.check_service.enabled` |

The following has been renamed for coherence with the SQL syntax:

| Previous name                        | New name                                      |
|--------------------------------------|-----------------------------------------------|
| `sql.create_tenant.default_template` | `sql.create_virtual_cluster.default_template` |

The following settings are also now marked as non-public, since they
were not meant for use by end-users yet:

- `server.controller.default_tenant`
- `trace.redact_traces_at_virtual_cluster_boundary.enabled`
- `admission.kv.tenant_weights.enabled`
- `admission.kv.stores.tenant_weights.enabled`

Release note (cli change): The following cluster settings have been
renamed. The previous names are available for backward-compatibility.

| Previous name                                  | New name                                          |
|------------------------------------------------|---------------------------------------------------|
| `spanconfig.tenant_coalesce_adjacent.enabled`  | `spanconfig.range_coalescing.application.enabled` |
| `spanconfig.storage_coalesce_adjacent.enabled` | `spanconfig.range_coalescing.system.enabled`      |

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
These looks good to me, but would also be interested in @yuzefovich's thoughts.

**Review by yuzefovich — APPROVED** [review]
:lgtm: to me too.

> Reviewed 36 of 94 files at r2, 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109077#-:-NcOMluG-KlPSqp2DNSN:b-corklw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/server/node.go` line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109077#-NcOKfZn-yFWwz3cdBKt:-NcOKfZn-yFWwz3cdBKu:b-y0u2ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3cc92c66bfd9e231f8001d0d4d53f269ca2c80/pkg/server/node.go#L246)):*
> ```Go
> 		settings.SystemOnly,
> 		"server.secondary_tenants.redact_trace.enabled",
> 		"if enabled, storage/KV trace results are rediacted when returned to a virtual cluster",
> ```

nit: `s/rediacted/redacted/`.
___
*[`pkg/sql/exec_util.go` line 237 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109077#-NcOL9x48P_PLfjsRn_G:-NcOL9x48P_PLfjsRn_H:b27vjwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3cc92c66bfd9e231f8001d0d4d53f269ca2c80/pkg/sql/exec_util.go#L237)):*
> ```Go
> 	settings.TenantReadOnly,
> 	"sql.scatter.allow_for_secondary_tenant.enabled",
> 	"allow secondary tenants to run ALTER TABLE/INDEX ... SCATTER commands; does not affect the system tenant",
> ```

nit: should this also be reworded to use "virtual clusters"?

**Comment by knz** [comment]
TFYR!

bors r=stevendanna,yuzefovich

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109077)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/server/node.go` line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109077#-NcOKfZn-yFWwz3cdBKt:-NcR4q_s3HqKkpUNrZNq:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3cc92c66bfd9e231f8001d0d4d53f269ca2c80/pkg/server/node.go#L246)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/rediacted/redacted/`.
</blockquote></details>

Fixed.
___
*[`pkg/sql/exec_util.go` line 237 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109077#-NcOL9x48P_PLfjsRn_G:-NcR521UC0XU0ow1x8i0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a3cc92c66bfd9e231f8001d0d4d53f269ca2c80/pkg/sql/exec_util.go#L237)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should this also be reworded to use "virtual clusters"?
</blockquote></details>

Done.

**Pull request merged**
