### PR TITLE
vecstore: move methods from Store to Txn

### PR DESCRIPTION
**Pull request by andy-kimball**
Move all Store methods that take a Txn parameter to the Txn interface. This
cleans up the interface and prepares the way to have a Txn implementation
that buffers up changes rather than actually writing them to the store.

Epic: CRDB-42943

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
This is largely a mechanical change. Reviewers should review commits separately, since the 2nd commit is purely mechanical code movement from one file to another.

**Review by mw5h — APPROVED** [review]
:lgtm:

I just have questions about the semantics of GetPartition()

> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136942#-:-ODXYx3_54BjoX0Ey63H:b-pw4s9i)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/vecindex/vecstore/store.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136942#-ODXWijH3-hG7CiPYPp1:-ODXWijH3-hG7CiPYPp2:b-ljzrfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9357ffc834385a6067abd578ebc1791cb306d17d/pkg/sql/vecindex/vecstore/store.go#L78)):*
> ```Go
> 	// ErrPartitionNotFound if the key cannot be found. The returned partition
> 	// can be modified by the caller in the scope of the transaction with a
> 	// guarantee it won't be changed by other agents.
> ```

What types of modifications are we talking here? Method-mediated changes via partition methods? It seems like we might want an update partition method to re-serialize and write back a partition. Are we also implying that this will block vector inserts into this partition?

**Review by mw5h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136942)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/vecindex/vecstore/store.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136942#-ODYQcEiB0SQUQ_8_-BT:-ODYQcEiB0SQUQ_8_-BU:b-o32ica) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a283a97b1d9652366f5043a25d0d3a33bfa0c49/pkg/sql/vecindex/vecstore/store.go#L52)):*
> ```Go
> 	// CommitTransaction commits a transaction previously started by a call to
> 	// BeginTransaction.
> 	CommitTransaction(ctx context.Context, txn Txn) error
> ```

Maybe consider giving Commit()/Abort() methods to Txn, to more closely match kv.Txn.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136942)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/vecindex/vecstore/store.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136942#-ODXWijH3-hG7CiPYPp1:-ODYuLR97c4tfCq3Q4nf:b-788lzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9357ffc834385a6067abd578ebc1791cb306d17d/pkg/sql/vecindex/vecstore/store.go#L78)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

What types of modifications are we talking here? Method-mediated changes via partition methods? It seems like we might want an update partition method to re-serialize and write back a partition. Are we also implying that this will block vector inserts into this partition?
</blockquote></details>

The Split/Merge operations are the only ones that use `GetPartition`, and we know in those cases we don't want other transactions causing conflicts that might trigger unnecessary txn aborts. We will want to use a SELECT FOR UPDATE style lock when we read the rows in the partition in order to minimize the possibility of conflicts and subsequent aborts. Vector inserts/deletes should block, as in many cases the entire partition will be deleted after reading it. That should force an abort or timestamp push of its entire owner transaction. Unfortunately, splits/merges are likely to cause a non-trivial number of aborts/retries of user transactions that are not a thing with forward/inverted indexes.
___
*[`pkg/sql/vecindex/vecstore/store.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136942#-ODYQcEiB0SQUQ_8_-BT:-ODYtBCK7bIDc13aEKor:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a283a97b1d9652366f5043a25d0d3a33bfa0c49/pkg/sql/vecindex/vecstore/store.go#L52)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

Maybe consider giving Commit()/Abort() methods to Txn, to more closely match kv.Txn.
</blockquote></details>

Good idea, done.

**Comment by andy-kimball** [comment]
bors r=mw5h

**Pull request merged**
