### PR TITLE
util/syncutil: don't unconditionally allocate in IntMap.Range

### PR DESCRIPTION
**Pull request by nvb**
The method was letting its `read` variable escape to the heap, which meant
that the allocation that should have only occurred on the uncommon path where
the dirty map is promoted was being hit on all paths. The effect of this was
that even calls to IntMap.Range on stable maps would allocate.

```
name                       old time/op    new time/op    delta
Range/*syncutil.IntMap-16    1.70µs ±11%    1.65µs ± 9%    -3.15%  (p=0.247 n=10+10)

name                       old alloc/op   new alloc/op   delta
Range/*syncutil.IntMap-16     16.0B ± 0%      0.0B       -100.00%  (p=0.000 n=10+10)

name                       old allocs/op  new allocs/op  delta
Range/*syncutil.IntMap-16      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=10+10)
```

It looks like this is just an issue with our fork of sync.Map, and it was
introduced when we moved from the use of a `atomic.Value` to an `unsafe.Pointer`
to store the Map's atomically-accessed readOnly struct. Before, the allocation
would be scoped to just the paths that needed to wrap the `readOnly` in an
`interface{}`.

I noticed that the map was the third most frequent source of memory allocation
in a sysbench `oltp_update_non_index` run on a 3x cluster of `r5d.16xlarge` VMs:
```
----------------------------------------------------------+-------------
                                          38371913   100% |   github.com/cockroachdb/cockroach/pkg/storage.(*RaftTransport).queuedMessageCount /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go:276
  38371913  1.24%  7.50%   38371913  1.24%                | github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:326
----------------------------------------------------------+-------------
```

Release justification: This is about as safe as performance optimizations come.
Others may disagree though, so we can sit on this.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

Let's let this sit to avoid a slippery slope, though I agree that this doesn't break anything.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41015#-:-LpXp9dp05-x8BIT02CY:blonr7t)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis)

**Review by petermattis — APPROVED** [review]
I'll defer to Tobi's more conservative voice. Did this actually move the needle on any high-level (roachtest) perf numbers?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41015#-:-LpYIoDv705MCvue_D77:b-wsnlpn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/util/syncutil/int_map.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41015#-LpYITyz6ULnc-c4Q2D_:-LpYITyz6ULnc-c4Q2Da:b-2vuhm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3e456cc6a3083dad6e81ace93e78a3bed87004e/pkg/util/syncutil/int_map.go#L338)):*
> ```Go
> 			// when read.amended is false. Instead, constrain the allocation to
> 			// just this branch.
> 			newRead := &readOnly{m: m.dirty}
> ```

I really wish the compiler could do this transformation automatically. It seems to happen with some regularity.

**Comment by nvanbenschoten** [comment]
> Did this actually move the needle on any high-level (roachtest) perf numbers?

I didn't measure, but I'm pretty sure it will be in the noise on anything at that level. Still, a 1.24% reduction in memory allocations, especially on the hot path in the Raft ready loop isn't negligible. 

This is such a small and safe change that I'm tempted to merge it with the release justification that we'd feel comfortable backporting it. Any objections?

**Comment by tbg** [comment]
No, after our discussion on the weekly today I also think we should merge.

**Comment by nvanbenschoten** [comment]
👍 

bors r+

**Pull request merged**
