### PR TITLE
changefeedccl: Rework error handling

### LINKED ISSUE #63317: changefeedccl: transient schemafeed errors are not retried
**Describe the problem**

In https://github.com/cockroachdb/cockroach/issues/63282 we saw that a clock drift issue led to one node being terminated.  This then resulted in a changefeed failure because the node termination led to a failure to fetch a table descriptor during schema polling.

It appears that _all_ errors from the schemafeed are treated as fatal, even though they might be caused by transient communication issues. 

We may want identify which of the many error returns in fetchDescriptorVersions may be retriable.  It seems likely that at least this ought to be:

```go
	res, pErr := kv.SendWrappedWith(ctx, db.NonTransactionalSender(), header, req)
	if log.V(2) {
		log.Infof(ctx, `fetched table descs (%s,%s] took %s`, startTS, endTS, timeutil.Since(start))
	}
	if pErr != nil {
		err := pErr.GoError()
		return nil, errors.Wrapf(err, `fetching changes for %s`, span)
	}
```

Note that`pErr.GoError()` will return an UnhandledRetriableError in some cases, but the rest of the changefeed code doesn't look for that particular type. And, it is isn't clear to me without further verification that that will cover all of the transient errors the function could return.

Jira issue: CRDB-6524

### LINKED ISSUE #71341: changefeedccl: Do not thrash jobs table when retrying transient errors
Changfeeds retries transient errors -- that's good.
However, if these transient errors happens rapidly, we will wind up writing to the jobs
table without any throttling: https://github.com/cockroachdb/cockroach/blob/ec530a3ac1b04629d9a203d2d2ebe610c564064b/pkg/ccl/changefeedccl/changefeed_stmt.go#L746

That's not ideal, and may even cause problems where the job row exceeds range size limits (and cannot be split).

- [ ] Throttle the rate of such error messages being written to the jobs table
- [ ] Truncate excessively verbose and long error messages

We should probably backport this to 21.2

Jira issue: CRDB-10519

### LINKED ISSUE #73016: changefeedccl: Changefeeds fail due to Replica.Send error
Customer reported changefeeds terminating with `aborted during Replica.Send: context deadline exceeded` error.
This shouldn't really happen.  It's not clear exactly where this error is coming from; but we ought to handle it
like we handle any other network related issues.

Epic CRDB-11783

Jira issue: CRDB-11384

### LINKED ISSUE #77549: changefeedccl: Support non-retryable errors in sinks
Currently, any error returned form the sink is treated as a retryable error
because we wrap the sink with "error sink".

This may not be desirable at all times.  For example, if we somehow managed
to generate 2GB size message in kafka, there is simply *no* way we will be able
to send such a message because it will be rejected by sarama.  There are other
cases like this, I suppose.

Jira issue: CRDB-13648

### LINKED ISSUE #90320: changefeedccl: Tests fail on mac
Recent go changes https://github.com/golang/go/issues/52010, cause
test that generate crypto certs to fail on Mac's because the error
message returned is different from the one expected:
TestAvroEncoderWithTLS
TestWebhookSink

Jira issue: CRDB-20695

### PR DESCRIPTION
**Pull request by miretskiy**
Prior to this PR, changefeeds would rely on a white list
approach in order to determine which errors were retryable.
All other errors would be deemed terminal, causing changefeed
to fail.

The above approach is brittle, and causes unwanted
changefeed termination.

This PR changes this approach to treat all errors as retryable,
unless otherwise indicated.  Errors that are known by changefeed
to be fatal are handled explicitly, by marking such errors
as terminal.  For example, changefeeds would exit
if the targeted table is dropped.  On the other hand, inability
to read this table for any reason would not be treated as
terminal.

Fixes https://github.com/cockroachdb/cockroach/issues/90320
Fixes https://github.com/cockroachdb/cockroach/issues/77549
Fixes https://github.com/cockroachdb/cockroach/issues/63317
Fixes https://github.com/cockroachdb/cockroach/issues/71341
Fixes https://github.com/cockroachdb/cockroach/issues/73016
Informs CRDB-6788
Informs CRDB-7581

Release Note (enterprise change): Changefeed will now treat
all errors, unless otherwise indicated, as retryable errors.

### CODE REVIEW

**Review by HonoreDB — COMMENTED** [review]
Thanks for doing this, I agree it's a good idea. I do think if we're defaulting to retryable, we need to make that conditional on the feed having already checkpointed at least once. Otherwise, too many problems that require manual intervention will manifest as a changefeed that is always running but never makes progress. A changefeed that's never made progress isn't worth saving--the rare case that you get a transient error right away isn't worth it.

> Reviewed 4 of 4 files at r1, 5 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-:-NFU3_tN6svMsZJ2BwpR:b-7mhjg0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/avro.go` line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-NFU0EMhCf4P98Di3u3v:-NFU0EMhCf4P98Di3u3w:b-5dgqjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/875666b22c35202a40da7f4f5c9062ceaf2499ce/pkg/ccl/changefeedccl/avro.go#L412)):*
> ```Go
> 				date := *d.(*tree.DDate)
> 				if !date.IsFinite() {
> 					return nil, changefeedbase.WithTerminalError(errors.Errorf(
> ```

Might be better to have all errors raised out of an encoder be marked terminal unless marked retryable, the only retryable error I can think of that can come out of an encoder is a schema registry connectivity failure.
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1042 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-NFU18KC4kFlRzeUcg6E:-NFU18KC4kFlRzeUcg6F:bzfb95w) ([raw file](https://github.com/cockroachdb/cockroach/blob/875666b22c35202a40da7f4f5c9062ceaf2499ce/pkg/ccl/changefeedccl/changefeed_processors.go#L1042)):*
> ```Go
> 				if cf.frontier.boundaryType == jobspb.ResolvedSpan_EXIT {
> 					err = changefeedbase.WithTerminalError(errors.Wrapf(err,
> 						"shut down due to schema change and %s=%q",
> ```

Is this always a schema change or can it be end time/initial scan only?
___
*[`pkg/ccl/changefeedccl/retry.go` line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-NFU1fyWEb_buHf22QiZ:-NFU1fyWEb_buHf22Qi_:b-7iwvfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/875666b22c35202a40da7f4f5c9062ceaf2499ce/pkg/ccl/changefeedccl/retry.go#L51)):*
> ```Go
> const resetRetryAfter = 10 * time.Minute
> 
> // Retry is a think wrapper around retry.Retry which
> ```

thin?
___
*[`pkg/sql/catalog/lease/lease.go` line 1019 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-NFU3LA3-I-0J4XVHM-x:-NFU3LA3-I-0J4XVHM-y:b-mxhgr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/875666b22c35202a40da7f4f5c9062ceaf2499ce/pkg/sql/catalog/lease/lease.go#L1019)):*
> ```Go
> }
> 
> // IsDraining returns true if this nodes lease manager is draining.
> ```

node's

**Review by miretskiy — COMMENTED** [review]
Hmm... I'm not sure I agree with this.  I'm all for detecting errors, doing sanity checking during
changefeed creation.   The reality is that changefeed may run for a while w/out checkpoint -- i.e. during initial scan.
Having some arbitrary logic that effectively says that "we will retry, but only if changefeed ran for 10 or more minutes" seems
to be rather arbitrary and not that great either.  Lots of things can happen in the cluster during that time.

None of those heuristics would replace the need to proper monitoring and observability.
So.. I'd rather improve those areas if needed, vs above.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-:-NFkRLXiEtiSmWnNFm1Q:b-osv5r5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB)

___
*[`pkg/ccl/changefeedccl/avro.go` line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-NFU0EMhCf4P98Di3u3v:-NFkTDuH-NSTdyEA1MMl:b-bq7i3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/875666b22c35202a40da7f4f5c9062ceaf2499ce/pkg/ccl/changefeedccl/avro.go#L412)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Might be better to have all errors raised out of an encoder be marked terminal unless marked retryable, the only retryable error I can think of that can come out of an encoder is a schema registry connectivity failure.
</blockquote></details>

These are the only two cases that exist today where this happpens.  If we get into situation where we are returning majority of those errors -- then perhaps we can reconsider.
Do you feel strongly?
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1042 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-NFU18KC4kFlRzeUcg6E:-NFkR0FL6WEP2KtswJKB:b-r364nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/875666b22c35202a40da7f4f5c9062ceaf2499ce/pkg/ccl/changefeedccl/changefeed_processors.go#L1042)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Is this always a schema change or can it be end time/initial scan only?
</blockquote></details>

I believe so; we check for endTime.Empty above or if we haven't reached end time
___
*[`pkg/ccl/changefeedccl/retry.go` line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-NFU1fyWEb_buHf22QiZ:-NFkRAHeAMBLwhJmGvAm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/875666b22c35202a40da7f4f5c9062ceaf2499ce/pkg/ccl/changefeedccl/retry.go#L51)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

thin?
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/lease/lease.go` line 1019 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-NFU3LA3-I-0J4XVHM-x:-NFkRAqx2SPk7yaMgBnD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/875666b22c35202a40da7f4f5c9062ceaf2499ce/pkg/sql/catalog/lease/lease.go#L1019)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

node's
</blockquote></details>

Done.

**Review by HonoreDB — APPROVED** [review]
Should we really go for 10 minutes without an initial scan checkpoint? It feels like there's some kind of missing communication, anyway, if it's ever possible for a healthy changefeed to make progress for 10 minutes without reporting it. Maybe we should, say, have special-case logic that if you're a changefeed aggregator on the same node as the changefeed frontier/coordinator, you immediately flush and checkpoint (or initial-scan-checkpoint) after your first successful emit.

> Reviewed 1 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-:-NFs_5Z849MvhKBZ_blG:b-mym5w3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/avro.go` line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90810#-NFU0EMhCf4P98Di3u3v:-NFsZZoo0ClDAmWfMcTs:b-zbz2ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/875666b22c35202a40da7f4f5c9062ceaf2499ce/pkg/ccl/changefeedccl/avro.go#L412)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

These are the only two cases that exist today where this happpens.  If we get into situation where we are returning majority of those errors -- then perhaps we can reconsider.
Do you feel strongly?
</blockquote></details>

I guess if it's just these two and we have the possibility of retryable schema registry errors, this seems fine as is.

**Comment by miretskiy** [comment]
> Should we really go for 10 minutes without an initial scan checkpoint?

Yeah -- absolutely; initial scan checkpoints are expensive, and, by default are set to happen every 10 minutes.

**Comment by samiskin** [comment]
@miretskiy do we plan on backporting this change to 22.1?

**Comment by miretskiy** [comment]
22.1? Probably not.  22.2.x -- maybe?

**Comment by amruss** [comment]
Let me know if we change our minds on backporting this to 22.2.1 -> going to include it in the docs as a breaking change

**Comment by miretskiy** [comment]
blathers backport 22.2

**Pull request merged**
