### PR TITLE
roachtest: support running steps in the background in `mixedversion`

### PR DESCRIPTION
**Pull request by renatolabs**
This adds a `BackgroundFunc` API to the `mixedversion` package in
roachtest, allowing test writers to run tasks in the background during
an upgrade test. The most common use-case for this functionality is
running a workload while the cluster upgrades (other similar use-cases
exist in a variety of tests); for this reason, a `Workload`
convenience function is added that allows tests to add a workload to a
mixed-version test with one function call.

Currently, each test needs to devise their own mechanism to: spawn the
background task; monitor its execution; and terminate the test on
error.

The current API aims to reduce copying and pasting of such logic,
making for a more declarative test. In the future, the test planner
itself could decide to run some steps in the background and it should
be able to leverage the mechanisms introduced in this commit.

Epic: [CRDB-19321](https://cockroachlabs.atlassian.net/browse/CRDB-19321)

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Update:

1. ~~https://github.com/cockroachdb/cockroach/pull/96989~~ (merged!)
2. https://github.com/cockroachdb/cockroach/pull/96990 **(this one!)**
3. https://github.com/cockroachdb/cockroach/pull/96991

To be reviewed: **all changes in the PR**.

**Review by srosenberg — COMMENTED** [review]
Nice work! I'll take another pass tomorrow.

> Reviewed 4 of 4 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-:-NPuxT5bAs3qJr5AFGJ2:bzi0cyk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/roachtestutil/commandbuilder.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPulePTExClf5Sp4dUm:-NPulePUCeZ-s97SMbth:b5u4ikh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31f893c8f62cb6f6a616fffb8703f3b5903d6b2/pkg/cmd/roachtest/roachtestutil/commandbuilder.go#L65)):*
> ```Go
> func (c *Command) MaybeFlag(condition bool, name string, val interface{}) *Command {
> 	if condition {
> 		return c.Flag(name, fmt.Sprint(val))
> ```

Double-formatting; `Flag` already applies `Sprint`.
___
*[`pkg/cmd/roachtest/roachtestutil/commandbuilder.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPumI1-0OnShtH2IA1s:-NPumI1-0OnShtH2IA1t:bk2tdjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31f893c8f62cb6f6a616fffb8703f3b5903d6b2/pkg/cmd/roachtest/roachtestutil/commandbuilder.go#L96)):*
> ```Go
> }
> 
> // String returns the string representation of the command, which can
> ```

It's a _canonical_ representation, right? (Since it's ordered by flag names.)
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuonJH14zYtqHplo8w:-NPuonJH14zYtqHplo8x:b5yf44x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L299)):*
> ```Go
> // background during the test. Background functions are kicked off
> // once the cluster has been initialized (i.e., after all startup
> // steps have finished).
> ```

When do they stop normally?
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 328 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuph6Z0xbycI1otdCA:-NPuph6Z0xbycI1otdCB:bphvkj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L328)):*
> ```Go
> 	addSeed := func(cmd *roachtestutil.Command) {
> 		if !cmd.HasFlag("seed") {
> 			cmd.Flag("seed", seed)
> ```

Why not use different seeds if neither `initCmd` nor `runCmd` has specified it?
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPurcif0Blm9JEU50dF:-NPurcif0Blm9JEU50dG:bmhaw5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L252)):*
> ```Go
> 		var delayStr string
> 		if s.delay.Milliseconds() > 0 {
> 			delayStr = fmt.Sprintf("after %s delay", s.delay)
> ```

The original version is debug-friendlier than the optimized one. E.g., if we see "0 delay" frequently, that may indicate a biased PRNG. 
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPusXfxCixaLqlV-qAJ:-NPusXfxCixaLqlV-qAK:b-1p38d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L42)):*
> ```Go
> 		ctx             context.Context
> 		testContext     *Context
> 		backgroundCount int64
> ```

Maybe rename to `bgCount` and describe that it denotes the number of created background steps; it's not immediately clear.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPutp7L31bmfobb1_DC:-NPutp7L31bmfobb1_DD:b-6ez111) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L61)):*
> ```Go
> 
> 	testFailure struct {
> 		displayed             bool
> ```

Methinks `summarized` might be better.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPutUr5A444RIqGLSWn:-NPutUr5A444RIqGLSWo:bnq9daj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L65)):*
> ```Go
> 		seed                  int64
> 		binaryVersions        []roachpb.Version
> 		clusterVersionsBefore []roachpb.Version
> ```

Before and after what? One is read from the cache, the next one after refresh. It's worth a comment.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuuYQ42FVOWUNDDt7C:-NPuuYQ42FVOWUNDDt7D:bps20r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L116)):*
> ```Go
> // each step in sequence.
> func (tr *testRunner) run() error {
> 	defer tr.closeConnections()
> ```

What's the default timeout for `db.Close()` and hence the upper-bound for defers?
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPutzXtCLBEQTTeYSKU:-NPutzXtCLBEQTTeYSKV:b-texdm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L121)):*
> ```Go
> 		tr.cancel()
> 		// Wait for some time so that any background tasks are properly
> 		// canceled and their cancelation messages are displayed in the
> ```

Nit: `cancellation`
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuu1nk2-mv9Nha6B_0:-NPuu1nk2-mv9Nha6B_1:b-tomj3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L123)):*
> ```Go
> 		// canceled and their cancelation messages are displayed in the
> 		// logs accordingly.
> 		time.Sleep(5 * time.Second)
> ```

This is only best-effort, right? We know that no magic sleep value will suffice in the worst-case :)
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuvOeK0yKXnZgaD8EA:-NPuvOeK0yKXnZgaD8EB:beh5jmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L147)):*
> ```Go
> 			}
> 
> 			return fmt.Errorf("background step `%s` returned error: %w", event.Name, event.Err)
> ```

What if a background step fails concurrently with some other step? The error(s) in the `stepsErr` won't be reported.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 249 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuwit7Cpe62xmjm4Zr:-NPuwit8B0kQDJ6Usiq8:b-f16g68) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L249)):*
> ```Go
> }
> 
> // stepError augments generates a `testFailure` error by augmenting
> ```

Nit: remove `augments`
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuwueN7J60yXwXRaNx:-NPuwueN7J60yXwXRaNy:befxjpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L434)):*
> ```Go
> }
> 
> func (br *backgroundRunner) Events() <-chan backgroundEvent {
> ```

`CompletedEvents` seems more precise.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 484 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuxAE6EC8jIhYC8N4a:-NPuxAE72_6cF3LSdjBN:bs161jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L484)):*
> ```Go
> }
> 
> // Background allows test writers to create functions that run in the
> ```

Nit: `writers` --> `author`

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96990)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuonJH14zYtqHplo8w:-NPv0Sg90Z3bTgiF5aMs:b98w1vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L299)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

When do they stop normally?
</blockquote></details>

It's worth clarifying that `userFunc` itself is executed locally, i.e., same node where `runner` is executing. However, it may end up executing commands on remote nodes. Note, this is a confounding factor for the API user; i.e., does the framework ensure my closure runs remotely, or am I responsible for it?
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 680 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuzsPQ7a6iCIHWWCNL:-NPuzsPQ7a6iCIHWWCNM:b-kw68a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L680)):*
> ```Go
> 	idGen func() int,
> 	prng *rand.Rand,
> 	nodes option.NodeListOption,
> ```

`nodes` is unused

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96990)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPwQULDEjwnuUripyqt:-NPwQULDEjwnuUripyqu:bemqegd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L412)):*
> ```Go
> 
> func newBackgroundRunner(ctx context.Context) *backgroundRunner {
> 	g, _ := errgroup.WithContext(ctx)
> ```

I had to pause here to confirm the right context is passed below. Have you considered using `ctxgroup.WithContext(ctx)` instead? The wrapper makes juggling of parent and child contexts less error-prone.

**Review by renatolabs — COMMENTED** [review]
RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-:-NQ2AR2O0BMtPlfBR_jZ:b-828fna)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/commandbuilder.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPulePTExClf5Sp4dUm:-NQ26ER01OrtFvouWp4B:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31f893c8f62cb6f6a616fffb8703f3b5903d6b2/pkg/cmd/roachtest/roachtestutil/commandbuilder.go#L65)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Double-formatting; `Flag` already applies `Sprint`.
</blockquote></details>

Fixed.
___
*[`pkg/cmd/roachtest/roachtestutil/commandbuilder.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPumI1-0OnShtH2IA1s:-NQ26FH752t4TtmmeZ5R:be5ifg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e31f893c8f62cb6f6a616fffb8703f3b5903d6b2/pkg/cmd/roachtest/roachtestutil/commandbuilder.go#L96)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

It's a _canonical_ representation, right? (Since it's ordered by flag names.)
</blockquote></details>

Indeed. Comment updated.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 299 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuonJH14zYtqHplo8w:-NQ26IMEAs0MCXRby03l:b-xqm9bi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L299)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

It's worth clarifying that `userFunc` itself is executed locally, i.e., same node where `runner` is executing. However, it may end up executing commands on remote nodes. Note, this is a confounding factor for the API user; i.e., does the framework ensure my closure runs remotely, or am I responsible for it?
</blockquote></details>

Added words to this function's documentation and also to the `userFunc` type.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 328 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuph6Z0xbycI1otdCA:-NQ26NA10Tj9iXjfA-0L:b-k40pk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L328)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Why not use different seeds if neither `initCmd` nor `runCmd` has specified it?
</blockquote></details>

I'm not sure I understand the suggestion.

The idea here is that if the user provided a specific seed, they probably have good reason to do it (e.g., reading fixtures from a bucket). If there's no seed in either of these commands, it means the caller is fine with arbitrary seeds (since they are now random by default), so we can set anything we want. 
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 680 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuzsPQ7a6iCIHWWCNL:-NQ27DwD1n3IQ5uXRsks:b-t8ti48) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L680)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

`nodes` is unused
</blockquote></details>

Huh, I guess _that's_ something we'll miss from `golint`. Thanks for catching.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPurcif0Blm9JEU50dF:-NQ27Mc_9X_TM7m0CPiG:b-6ati51) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L252)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

The original version is debug-friendlier than the optimized one. E.g., if we see "0 delay" frequently, that may indicate a biased PRNG. 
</blockquote></details>

I was thinking people could be confused when reading "with 0s delay", but I also see your point. Added the delay message unconditionally.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPusXfxCixaLqlV-qAJ:-NQ27b1c1JJ796ygY0It:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L42)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Maybe rename to `bgCount` and describe that it denotes the number of created background steps; it's not immediately clear.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPutp7L31bmfobb1_DC:-NQ27cB22PGJDgkevzVI:bt1b19p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L61)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Methinks `summarized` might be better.
</blockquote></details>

Renamed.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPutUr5A444RIqGLSWn:-NQ27d6F-pbNulJSL7lK:b-2gwiq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L65)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Before and after what? One is read from the cache, the next one after refresh. It's worth a comment.
</blockquote></details>

Added comment to explain.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuuYQ42FVOWUNDDt7C:-NQ27fIU04uo6RodGw88:bmu2f1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L116)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

What's the default timeout for `db.Close()` and hence the upper-bound for defers?
</blockquote></details>

I did a quick search and didn't find anything conclusive; I don't think that call has a builtin timeout mechanism (?). That said, the old mixed-version framework (`newMixedVersionTest` and friends) have the same `db.Close()` loop at the end of the test and I don't remember that being a source of headaches in the past, so I'm thinking we can leave this as-is until it becomes a problem.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPutzXtCLBEQTTeYSKU:-NQ285b5AuqvONXGbJEC:b-lzjdpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L121)):*
So... I'm mostly used to spell `cancelled` and `cancellation` myself, but I noticed Go uses `context.Canceled` so I started using `canceled` and `cancelation` here. If we are to trust `sapling.ai` (first result on a Google search):

> Cancelation is predominantly used in 🇺🇸 American (US) English (en-US) while cancellation is predominantly used in 🇬🇧 British English (used in UK/AU/NZ) (en-GB).

https://sapling.ai/usage/cancelation-vs-cancellation

:shrug: I'm fine either way but opted for consistency.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuu1nk2-mv9Nha6B_0:-NQ28lbqDXRYUO7-2aH4:b9ulwov) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L123)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

This is only best-effort, right? We know that no magic sleep value will suffice in the worst-case :)
</blockquote></details>

Yep, it's here just for convenience and does not impact correctness. The main goal, as the comment says, is to allow the context cancelation to be observed by any other background functions so that they log their termination appropriately.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuvOeK0yKXnZgaD8EA:-NQ29HHG1XO0PdYOSOCk:b-7sh4mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L147)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

What if a background step fails concurrently with some other step? The error(s) in the `stepsErr` won't be reported.
</blockquote></details>

It won't be reported in the main `test.log`, but the failure won't be lost -- it should still be captured in the step's logger:

https://github.com/cockroachdb/cockroach/pull/96990/files#diff-6976b20431cd2998815618de4e9abcc6cf7d05a6c009a642821d1eef440de7cfR295
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 249 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuwit7Cpe62xmjm4Zr:-NQ29gpS133sm2lU4s8j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L249)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: remove `augments`
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPwQULDEjwnuUripyqt:-NQ29iOa0fHQEiVa7hc0:bz0jolg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L412)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

I had to pause here to confirm the right context is passed below. Have you considered using `ctxgroup.WithContext(ctx)` instead? The wrapper makes juggling of parent and child contexts less error-prone.
</blockquote></details>

I was on the edge of restructuring how these contexts are handled so this comment was the push I needed to actually do it. Test runner now uses `ctxgroup`; downside is that `userFunc` now takes a `context.Context` parameter (another one), but I think things are much better now: the test runner's context is the parent context of every mixed-version related context.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuwueN7J60yXwXRaNx:-NQ2ANCS1fZyCrt1GxD3:bt1b19p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L434)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

`CompletedEvents` seems more precise.
</blockquote></details>

Renamed.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 484 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuxAE6EC8jIhYC8N4a:-NQ2AOHL6hSvyc0a_EmC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L484)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: `writers` --> `author`
</blockquote></details>

Done.

**Review by srosenberg — APPROVED** [review]
Thanks for addressing all comments! I clarified the thing about using different PRNG seeds for init and load, but it's a super minor point. Otherwise, this looks great!

> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-:-NQ2kkcI-duzL-LkjdD4:bkmcyeu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 328 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuph6Z0xbycI1otdCA:-NQ2iSnyEqRVE5dntnkm:bccfln2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L328)):*
>  If there's no seed in either of these commands, it means the caller is fine with arbitrary seeds

Right. My suggestion is why not use _different_ seeds in this case? `seed` is the same in both calls to `addSeed`
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPutzXtCLBEQTTeYSKU:-NQ2j7lCEMEYduwYSad8:bak9qla) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L121)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

So... I'm mostly used to spell `cancelled` and `cancellation` myself, but I noticed Go uses `context.Canceled` so I started using `canceled` and `cancelation` here. If we are to trust `sapling.ai` (first result on a Google search):

> Cancelation is predominantly used in 🇺🇸 American (US) English (en-US) while cancellation is predominantly used in 🇬🇧 British English (used in UK/AU/NZ) (en-GB).

https://sapling.ai/usage/cancelation-vs-cancellation

:shrug: I'm fine either way but opted for consistency.
</blockquote></details>

Hehe, I didn't know if was a chiefly British thing :) Personally, I prefer British English, it's so more nuanced; let's stick with that.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96990)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPutzXtCLBEQTTeYSKU:-NQ5b6GR-gvPMuIz7YON:b3wj7wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L121)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Hehe, I didn't know if was a chiefly British thing :) Personally, I prefer British English, it's so more nuanced; let's stick with that.
</blockquote></details>

I'm chuffed with the outcome of this comment :smile:

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96990)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 328 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96990#-NPuph6Z0xbycI1otdCA:-NQ5l7UGAhMzU4yJ3sOL:b9wze01) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70dac8ba14fc983bbc81ac1e33b6b9cc19602dd/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L328)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

>  If there's no seed in either of these commands, it means the caller is fine with arbitrary seeds

Right. My suggestion is why not use _different_ seeds in this case? `seed` is the same in both calls to `addSeed`
</blockquote></details>

Oh, right! The reason I'm using the same seed is that some workloads rely on the same seed being passed to both `init` and `run` (admittedly, `rand` is the only one that comes to mind where that dependency exists, but there could be others). Using the same seed is a safe choice.

**Comment by renatolabs** [comment]
bors r=srosenberg

TFTR!

**Pull request merged**
