### PR TITLE
ccl/gssapiccl: add GSS authentication support on Linux

### PR DESCRIPTION
**Pull request by madelynnblue**
GSS support uses the same logic from postgres. It works by calling a C
method statically compiled into cockroach in a loop, passing back and
forth various GSS tokens until a completed authentication is done.

Enterprise license checks are done at the end of a GSS auth session. This
allows administrators to test and verify their GSS setup before needing
to buy an enterprise license.

We directly include the krb5 library so we can statically compile an
exact version into the binary. The builder image has been changed to add
(well, keep) bison/yacc which is needed to build krb5.

Testing is done by using a docker-compose file. It defines containers
for the kdc, cockroach server, and psql binary. This has proven to be
the easiest way to get a correct test written.

We support (and require) the include_realm=0 option to be present, which
strips the realm from the GSS username. This removes the immediate need to
either add user identity mapping or for allowing additional characters in
usernames. The krb_realm option is also supported, with the addition that
it can be specified more than once to support multiple realms at once.

Release note (enterprise change): Add a GSS auth method configurable by
the server.host_based_authentication.configuration cluster setting.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Instead, we check for the license whenever the HBA conf is changed.

So in my opinion the "problem 1" is actually not a problem and instead a very good feature. In fact, I absolutely want my security feature to continue blocking user access even after the license expires. Even after nodes reboot.

It would be absolutely **terrible** PR if a legit customer lets their license expire *by accident* and discovers that their users suddenly can log in because their auth method was disabled, and there was a "old" entry in system.users that lets them log in with some old/outdated credentials.

I would say, if the HBA conf is set, then let it be used even when there is no license. However, *after* the user is authenticated, possibly immediately close the session with a pg error "authentication denied for administrative reasons".

Once you do it like that, problem 2 disappears too.

@rolandcrosby feel free to chime in on my reasoning.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-:-LYRR0g46xVZ0Dpd-qKJ:b-iuazqa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @mjibson)

___
*[Makefile, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRPud-13sTSaFXDof1:-LYRPud-13sTSaFXDof2:btdjejz) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/Makefile#L451)):*
> ```Makefile
> C_LIBS_CCL = $(C_LIBS_COMMON) $(LIBCRYPTOPP) $(LIBROACHCCL)
> 
> # We only include krb5 on linux.
> ```

just curious: why opt-in and not opt-out?
___
*[Makefile, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRQ3YkDGqRz08TeN2P:-LYRQ3YkDGqRz08TeN2Q:bmd5190) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/Makefile#L491)):*
> ```Makefile
> 	@echo 'package $(notdir $(@D))' >> $@
> 	@echo >> $@
> 	@echo '// #cgo CPPFLAGS: -I$(JEMALLOC_DIR)/include $(if $(findstring linux,$(TARGET_TRIPLE)),-I$(KRB5_DIR)/include)' >> $@
> ```

Extract these two if expressions into two variables KRB_CPPFLAGS and KRB_LDFLAGS
___
*[pkg/sql/pgwire/server.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRQiXgDX7FYLMiQ3BS:-LYRQiXgDX7FYLMiQ3BT:b2vb0zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/pkg/sql/pgwire/server.go#L240)):*
> ```Go
> 		// in the same way.
> 		for ie, entry := range conf.Entries {
> 			// Check for an invalid conf method (for instance one that require an //
> ```

nit: trailing `//`
___
*[pkg/sql/pgwire/server.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRQbDj8RNlKE0CjrQt:-LYRQbDk2FZpLyH8vaaZ:b-k4z2bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/pkg/sql/pgwire/server.go#L247)):*
> ```Go
> 			// way to do this.
> 			if canFn := hbaCanAuthMethods[entry.Method]; canFn != nil {
> 				fmt.Println("YES CANFN", entry.Method)
> ```

nit: I think you'll be able to remove this `fmt.Println` before this merges.

**Review by knz — COMMENTED** [review]
Another advantage of this is that it lets users pre-test the feature (let them configure it and check that cockroachdb indeed connects to their auth server -- they'll know that "it works" because the error "administrative reasons" basically tells them "everything's OK except for your license") -  before they commit to the sales process.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-:-LYRS4o23KT2AmfJcE3F:b-ktkgn2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @mjibson)

**Review by petermattis — COMMENTED** [review]
Generally looks good to me on the Cgo side of things. Just some small comments.

How does postgres test kerberos authentication? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-:-LYSstZp-fybtm2WPf19:b9ylec7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @mjibson)

___
*[pkg/ccl/gssapiccl/gssapi.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYSsL0UDBVr15_dzVWZ:-LYSsL0UDBVr15_dzVW_:bjvkjum) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/pkg/ccl/gssapiccl/gssapi.go#L60)):*
> ```Go
> 
> 			gbuf.length = C.ulong(len(token))
> 			gbuf.value = C.CBytes([]byte(token))
> ```

I'm not sure you need to perform this copy here. Can't you assign `&token[0]` to `gbuf.value` (perhaps with an `unsafe.Pointer` cast)? Possibly that runs afoul of the Cgo pointer passing constraints.
___
*[pkg/ccl/gssapiccl/gssapi.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYSrRC_Daz3n1t_Gapi:-LYSrRC_Daz3n1t_Gapj:bahlgus) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/pkg/ccl/gssapiccl/gssapi.go#L97)):*
> ```Go
> 			return gss_error("retrieving GSS user name failed", maj_stat, min_stat)
> 		}
> 		gssUser := string(C.GoBytes(gbuf.value, C.int(gbuf.length)))
> ```

Does `C.GoStringN` work here? That seems more idiomatic.
___
*[pkg/ccl/gssapiccl/gssapi.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYSs2mYAgLtA4UMA7CC:-LYSs2mYAgLtA4UMA7CD:b-2fpw0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/pkg/ccl/gssapiccl/gssapi.go#L108)):*
> ```Go
> }
> 
> func gss_error(msg string, maj_stat, min_stat C.OM_uint32) error {
> ```

`s/gss_error/gssError/g`

**Comment by rolandcrosby** [comment]
Don't know if you'd prefer a separate issue for this, since this code isn't in master yet, but I just ran into a panic when running a roachprod cluster with a build of your branch at 5d8e66e. In my cluster, I ran CockroachDB with the `KRB5_KTNAME=/path/to/keytab` env variable, and enabled GSSAPI auth through the HBA cluster setting, but didn't install a `krb5.conf` file because I wanted to see what happened. What happened was:

```
E190212 19:31:43.832349 6609 util/log/crash_reporting.go:202
[n1] a panic has occurred!
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
panic: runtime error: cgo argument has Go pointer to Go pointer
goroutine 6609 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000b12000, 0x3990b80, 0xc0064bd3b0)
/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0x11f
panic(0x2e056c0, 0xc009744ca0)
/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/ccl/gssapiccl.authGSS.func1.1(0xc006f00078, 0xc00653adb0, 0x0, 0xc00942dee0, 0x0, 0xc00653adb8, 0x0, 0xc00942def0, 0xc006f00090, 0x0, ...)
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/gssapiccl/gssapi.go:71 +0x136
github.com/cockroachdb/cockroach/pkg/ccl/gssapiccl.authGSS.func1(0xc00862600d, 0x6, 0xc02f00010301, 0x0, 0x0)
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/gssapiccl/gssapi.go:71 +0x273
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).handleAuthentication(0xc008636000, 0x3990ac0, 0xc0084fa580, 0x0, 0xc000098e40, 0xc0061730e0, 0xc0000ee000, 0x4000, 0xc000035248)
/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:1384 +0x347
github.com/cockroachdb/cockroach/pkg/sql/pgwire.serveConn(0x3990ac0, 0xc0084fa580, 0x39b48a0, 0xc00728f880, 0xc00862600d, 0x6, 0xc00860c5d0, 0x396e900, 0xc00860c2d0, 0x4000, ...)
/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:160 +0x133
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc000035200, 0x3990ac0, 0xc0084fa580, 0x39b48a0, 0xc00728f880, 0x0, 0x0)
/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:517 +0x8c5
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func20.1(0x39b5320, 0xc008445220)
/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1708 +0x180
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc000b12000, 0x3990b80, 0xc0064bd3b0, 0xc00000e400, 0x39b5320, 0xc008445220, 0xc0064bd3e0)
/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:139 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x226
```

**Comment by mjibson** [comment]
Good find. Thanks for the report.

**Review by madelynnblue — COMMENTED** [review]
Added tests via docker-compose. Probably some fallout there but appears to work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-:-LY_pY1XAkjTEtKq_w5N:b-cnboxu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, @mjibson, and @petermattis)

___
*[Makefile, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRPud-13sTSaFXDof1:-LYTS4us2pNx7x0vWw2H:behu2k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/Makefile#L451)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

just curious: why opt-in and not opt-out?
</blockquote></details>

Because this is the only thing I'm testing? Just seemed like the safer thing to do than maybe break esoteric builds like openbsd, freebsd, or maybe even darwin. I'm not comfortable swapping this until I actually know it'll build there.
___
*[pkg/ccl/gssapiccl/gssapi.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYSsL0UDBVr15_dzVWZ:-LYTUW2UE9TNcqBKyyZJ:bugfxu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/pkg/ccl/gssapiccl/gssapi.go#L60)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure you need to perform this copy here. Can't you assign `&token[0]` to `gbuf.value` (perhaps with an `unsafe.Pointer` cast)? Possibly that runs afoul of the Cgo pointer passing constraints.
</blockquote></details>

Doing this produced some panics (or maybe I did it wrong?). Keeping it as is for now.
___
*[pkg/ccl/gssapiccl/gssapi.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYSrRC_Daz3n1t_Gapi:-LYTWPp35740KGYSAqTo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/pkg/ccl/gssapiccl/gssapi.go#L97)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does `C.GoStringN` work here? That seems more idiomatic.
</blockquote></details>

Done.
___
*[pkg/ccl/gssapiccl/gssapi.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYSs2mYAgLtA4UMA7CC:-LYTWQ9q754IxeB_jmWg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/pkg/ccl/gssapiccl/gssapi.go#L108)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/gss_error/gssError/g`
</blockquote></details>

Done.

**Comment by mjibson** [comment]
RFAL. New changes are support for include_realm and krb_realm (see https://www.postgresql.org/docs/11/gssapi-auth.html).

**Comment by mjibson** [comment]
Hold off. Apparently I messed up my git repo and lost some changes. Will have to check if they are on my work laptop on Tuesday.

**Comment by mjibson** [comment]
Ok RFAL for reals now.

**Comment by knz** [comment]
I'll have a look later today or tomorrow when I'm done traveling.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by knz** [comment]
Would like to know what you think about my comment I left here: https://github.com/cockroachdb/cockroach/pull/34772#pullrequestreview-202070904

**Comment by mjibson** [comment]
I forgot to respond to that. I agree with your thoughts and changed the implementation to do the license check at the end of the GSS auth like you advised. (I assume that's the comment you meant?)

**Review by bobvawter — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r2, 23 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @mjibson, and @petermattis)

___
*[pkg/acceptance/compose_test.go, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGVIuS6wVjfG_bF-zC:-LZGVIuS6wVjfG_bF-zD:bqjq3ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/compose_test.go#L1)):*
> ```Go
> // Copyright 2017 The Cockroach Authors.
> ```

Copyright year.
___
*[pkg/acceptance/compose/gss/docker-compose.yml, line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGXAimCPwg5PsKHUSF:-LZGXAimCPwg5PsKHUSG:buvi35) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/compose/gss/docker-compose.yml#L18)):*
> ```YAML
>       - ../../.localcluster.certs:/certs
>       - keytab:/keytab
>       - ../../../../cockroach-linux-2.6.32-gnu-amd64:/cockroach/cockroach
> ```

This path seems quite specific.  Where's it coming from?
___
*[pkg/acceptance/compose/gss/psql/gss_test.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGXtVsAsxKQU6jQJKZ:-LZGXtVsAsxKQU6jQJK_:bw8vaxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/compose/gss/psql/gss_test.go#L33)):*
> ```Go
> )
> 
> func TestGSS(t *testing.T) {
> ```

Is there a test which does succeed in connecting?  It would be instructive to have a demonstration of a go GSS client successfully connecting.

**Comment by knz** [comment]
> I forgot to respond to that. I agree with your thoughts and changed the implementation to do the license check at the end of the GSS auth like you advised. (I assume that's the comment you meant?)

Thank you but then please update the toplevel PR description accordingly (that's what will be included in the git history).

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, @mjibson, and @petermattis)

___
*[pkg/acceptance/compose/gss/docker-compose.yml, line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGXAimCPwg5PsKHUSF:-LZGaNS2-FKHNxicY7pX:b-v1qf7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/compose/gss/docker-compose.yml#L18)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

This path seems quite specific.  Where's it coming from?
</blockquote></details>

This happens to be where `make acceptance` generates a binary. This path is already hard coded in various parts of the system. But since docker-compose is executed with a cwd of this directory, we have to have the ../../s. https://github.com/cockroachdb/cockroach/search?q=cockroach-linux-2.6.32-gnu-amd64&unscoped_q=cockroach-linux-2.6.32-gnu-amd64
___
*[pkg/acceptance/compose/gss/psql/gss_test.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGXtVsAsxKQU6jQJKZ:-LZGacSk7PsgtOUmkBOC:bi3q41g) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/compose/gss/psql/gss_test.go#L33)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Is there a test which does succeed in connecting?  It would be instructive to have a demonstration of a go GSS client successfully connecting.
</blockquote></details>

That would require a valid enterprise license in the test container and I'm not sure how to do that without exposing a key. In other parts of the system we are able to poke the cockroach enterprise stuff from within memory and test it like that. I think this is the first enterprise acceptance test which is why we haven't hit exactly this problem before.

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 16 files at r2, 23 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @mjibson, and @petermattis)

___
*[Makefile, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRQ3YkDGqRz08TeN2P:-LZGbJI9EMK37NFCGSl1:bg5hn6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/Makefile#L491)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Extract these two if expressions into two variables KRB_CPPFLAGS and KRB_LDFLAGS
</blockquote></details>

i think this comment is still applicable
___
*[pkg/acceptance/cluster/certs.go, line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGbTLB2uf2k6NEwwiS:-LZGbTLB2uf2k6NEwwiT:bguczke) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/cluster/certs.go#L51)):*
> ```Go
> 		512, 48*time.Hour, false, "testuser", true /* generate pk8 key */))
> 
> 	maybePanic(security.CreateNodePair(
> ```

maybe add a comment here and above to explain what the various pairs are for. This will make maintenance easier.

Also maybe explain how the key size was chosen.
___
*[pkg/acceptance/compose/gss/psql/gss_test.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGXtVsAsxKQU6jQJKZ:-LZGbmMG6cMEvPa_qIXc:b-33mwko) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/compose/gss/psql/gss_test.go#L33)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

That would require a valid enterprise license in the test container and I'm not sure how to do that without exposing a key. In other parts of the system we are able to poke the cockroach enterprise stuff from within memory and test it like that. I think this is the first enterprise acceptance test which is why we haven't hit exactly this problem before.
</blockquote></details>

Maybe with your new change you can have a test that shows the module authenticates and then expects the error "you need an enterprise license to go further."

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, and @petermattis)

___
*[Makefile, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRQ3YkDGqRz08TeN2P:-LYTTxdW1ZCO52SBQ_OD:b-556ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/Makefile#L491)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

i think this comment is still applicable
</blockquote></details>

Yeah I just have to figure out how to do it. I don't know make, bash, or C that well so it's a lot of indirection.
___
*[pkg/acceptance/compose_test.go, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGVIuS6wVjfG_bF-zC:-LZH3o7e0WL2rmqAG24x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/compose_test.go#L1)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Copyright year.
</blockquote></details>

Done.
___
*[pkg/acceptance/cluster/certs.go, line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGbTLB2uf2k6NEwwiS:-LZH5zvbA0Jl9K9eIuFS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/cluster/certs.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe add a comment here and above to explain what the various pairs are for. This will make maintenance easier.

Also maybe explain how the key size was chosen.
</blockquote></details>

Done.
___
*[pkg/acceptance/compose/gss/psql/gss_test.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGXtVsAsxKQU6jQJKZ:-LZH4TBUEzMCTkWt8cOB:b-lvqxy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/compose/gss/psql/gss_test.go#L33)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe with your new change you can have a test that shows the module authenticates and then expects the error "you need an enterprise license to go further."
</blockquote></details>

It already does this. See the expected error messages "use of GSS authentication requires an enterprise license".

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, @mjibson, and @petermattis)

___
*[Makefile, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRQ3YkDGqRz08TeN2P:-LZH7Djl-L-xHyHKGqmR:b-51j6yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/Makefile#L491)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Yeah I just have to figure out how to do it. I don't know make, bash, or C that well so it's a lot of indirection.
</blockquote></details>

Oh I can explain. Earlier in the Makefile, do this:

```
KRB_CPPFLAGS = $(if $(findstring linux,$(TARGET_TRIPLE)),-I$(KRB5_DIR)/include)
```

then here:

```
@echo '// #cgo CPPFLAGS: -I$(JEMALLOC_DIR)/include $(KRB_CPPFLAGS)
```

ditto for KRB_LIBDIR (not LDFLAGS as I initially suggested: you'd be using that variable inside the $(addprefix ...) expression.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, @mjibson, and @petermattis)

___
*[Makefile, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRQ3YkDGqRz08TeN2P:-LZH7g146oDN-OyQ7GLC:b-gss8rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/Makefile#L491)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Oh I can explain. Earlier in the Makefile, do this:

```
KRB_CPPFLAGS = $(if $(findstring linux,$(TARGET_TRIPLE)),-I$(KRB5_DIR)/include)
```

then here:

```
@echo '// #cgo CPPFLAGS: -I$(JEMALLOC_DIR)/include $(KRB_CPPFLAGS)
```

ditto for KRB_LIBDIR (not LDFLAGS as I initially suggested: you'd be using that variable inside the $(addprefix ...) expression.
</blockquote></details>

You can even do `KRB_CPPFLAGS := ...` to optimize the assignment to be done just once.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, and @mjibson)

___
*[Makefile, line 1442 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZI2NkW3ESJkNdgAK5b:-LZI2NkW3ESJkNdgAK5c:b-qnta1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e90c3a312ee1f00cfe910ff7d1f2f98acaf86af/Makefile#L1442)):*
> ```Makefile
> 	git -C $(SNAPPY_SRC_DIR)   clean -dxf
> 	git -C $(LIBROACH_SRC_DIR) clean -dxf
> 	git -C $(KRB5_SRC_DIR)/..  clean -dxf
> ```

That looks really odd. I'd prefer if `KRB5_SRC_DIR` was set to the top-level dir, and any time you needed `/src` you did `$(KRB5_SRC_DIR)/src`. That is a few more uses of `/src`, but I'm fine with that.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, and @petermattis)

___
*[Makefile, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRQ3YkDGqRz08TeN2P:-LZIsQ9M1N-5cgcvEEuh:bihvzwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/Makefile#L491)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You can even do `KRB_CPPFLAGS := ...` to optimize the assignment to be done just once.
</blockquote></details>

I did CPPFLAGS. I'm not sure what you are talking about with KRB_LIBDIR, especially since you said don't do LDFLAGS? Did I miss something?
___
*[Makefile, line 1442 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZI2NkW3ESJkNdgAK5b:-LZIsZPu-LKSN0J2bbXN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e90c3a312ee1f00cfe910ff7d1f2f98acaf86af/Makefile#L1442)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

That looks really odd. I'd prefer if `KRB5_SRC_DIR` was set to the top-level dir, and any time you needed `/src` you did `$(KRB5_SRC_DIR)/src`. That is a few more uses of `/src`, but I'm fine with that.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @knz, @mjibson, and @petermattis)

___
*[Makefile, line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LYRQ3YkDGqRz08TeN2P:-LZKQnoB5PGP9qMRUsR0:bthtb77) ([raw file](https://github.com/cockroachdb/cockroach/blob/60bd8d9d04f11714799ced45cc11f568ada44eaa/Makefile#L491)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I did CPPFLAGS. I'm not sure what you are talking about with KRB_LIBDIR, especially since you said don't do LDFLAGS? Did I miss something?
</blockquote></details>

So you can write above:

```
KRB_DIR := $(if $(findstring linux,$(TARGET_TRIPLE)),$(KRB5_DIR)/lib)
```

Then here below:

```
@echo '// #cgo LDFLAGS: $(addprefix -L,$(CRYPTOPP_DIR) $(PROTOBUF_DIR) $(JEMALLOC_DIR)/lib $(SNAPPY_DIR) $(ROCKSDB_DIR) $(LIBROACH_DIR) $(KRB_DIR))
```

**Review by knz — COMMENTED** [review]
LGTM modulo resolution of the other reviewers' comments.

> Reviewed 3 of 4 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-:-LZKRRrT2Xt-v5PtX7SH:b3a8jpm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @mjibson, and @petermattis)

___
*[pkg/acceptance/compose/gss/psql/gss_test.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-LZGXtVsAsxKQU6jQJKZ:-LZKRNBBDU2L171KEs_s:b-ucfkn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaaa8fd36e431281bda4e1726a1d177e0e01dd80/pkg/acceptance/compose/gss/psql/gss_test.go#L33)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

It already does this. See the expected error messages "use of GSS authentication requires an enterprise license".
</blockquote></details>

Thanks.

**Review by bobvawter — APPROVED** [review]
> Reviewed 24 of 24 files at r6, 25 of 25 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @mjibson, and @petermattis)

**Review by bobvawter — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34772#-:-LZa-j3I9jifSZMsRmxq:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter, @mjibson, and @petermattis)

**Pull request merged**
