### PR TITLE
sqlbase: improve the documentation of IndexDescriptor

### LINKED ISSUE #12594: sqlbase: clarify the semantics of the IndexDescriptor protobuf
Reported/requested by @RaduBerinde in #12583:

https://github.com/cockroachdb/cockroach/pull/12583#issuecomment-269426725

> Does index.ColumnIDs include the "stored columns"? Not obvious from the comments in structured.proto, IndexDescriptor comments need improving (maybe with a couple of examples).

https://github.com/cockroachdb/cockroach/pull/12583#issuecomment-269517841

> Not to me.. Implicit columns are the PK columns that are not part of the index (so they are always a subset of the PK columns). Stored columns can be any columns, and it's not clear from anywhere if column_ids includes those or not. In fact the comment suggest that it does not (column_ids "parallels the column_names list"), unless those columns show up in both column_names and store_column_names (which seems odd).

> So take an example: PK columns are k1, k2 and we have some columns v1, v2. We have an index on (v1,k1) which also stores v3. Implicit columns would be k2. It's unclear to me if column_names includes v3, and if column_ids includes its id. If yes, then is the only way to distinguish between a column that is part of the index or one that is merely stored cross-referencing column_names with stored_column_names?

> In fact I'm looking at EncodeSecondaryIndex and can't really find any code that deals with STORING columns. It may be the case that we treat (v1,k1) storing v3 as just (v1,k1,v3) but that seems incorrect for unique indexes.

https://github.com/cockroachdb/cockroach/pull/12583#issuecomment-269520311

> Or are the stored columns part of the implicit columns? In that case the explanation for implicit columns is incorrect ("The extra column IDs is computed as PrimaryIndex.column_ids - column_ids")..

### PR DESCRIPTION
**Pull request by RaduBerinde**
The example was verified (by dumping an actual table descriptor).

Fixes #12594.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12607)

### CODE REVIEW

**Comment by knz** [comment]
:lgtm:
Thanks!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12607#-:-K_DgFCckLSvFHetd8Px:b-aw02zl)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sqlbase/structured.proto, line 233 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12607#-K_Fo3G575WmPUmXwcca:-K_Fo3G6Vf9yNc36r8R2:b46znj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f215d4ac1c3bf1d20654d2251639a319eb692ba/pkg/sql/sqlbase/structured.proto#L233)):*
> ```protobuf
>   // Note: for non-unique indexes, the stored columns could be part of the
>   // value rather than the key, but we don't currently do this.
>   repeated uint32 implicit_column_ids = 7 [(gogoproto.customname) = "ImplicitColumnIDs",
> ```

since you've discovered that this includes the stored cols, the name "implicit" doesn't mean anything.
How about renaming it to... `available_columns`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12607#-:-K_FoWsZ8QnVONJRKo5Z:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Or extra_columns?

**Comment by a-robinson** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/sqlbase/structured.proto, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12607#-K__-9A9FyNxmTY6BIZC:-K__-9A9FyNxmTY6BIZD:b-rzoj3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f215d4ac1c3bf1d20654d2251639a319eb692ba/pkg/sql/sqlbase/structured.proto#L158)):*
> colunn ID: 2
> //     u INT NULL,        // colunn ID: 3
> //     v INT NULL,        // colunn ID: 4
> //     w INT NULL,        // colunn ID: 5

s/colunn/column

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12607#-:-K__-PAuWl1tIHw_i4jp:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Renamed to ExtraColumnIDs (including related variables, comments).

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/sqlbase/structured.proto, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12607#-K__-9A9FyNxmTY6BIZC:-K__fEqPxbwa_3NzI8Mw:bj3eodx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f215d4ac1c3bf1d20654d2251639a319eb692ba/pkg/sql/sqlbase/structured.proto#L158)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

> colunn ID: 2
> //     u INT NULL,        // colunn ID: 3
> //     v INT NULL,        // colunn ID: 4
> //     w INT NULL,        // colunn ID: 5

s/colunn/column
</blockquote></details>

Fixed, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12607#-:-K__f9DB_U3LLceRPh8E:b-sum6rw)*

**Review by knz — APPROVED** [review]

**Pull request merged**
