### PR TITLE
sql: rename experimental_uuid_v4 to uuid_v4

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5886)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by bdarnell** [comment]
We should probably leave an alias for the old name for a while. My biggest concern is for a table that is using `experimental_uuid_v4` as a default value for a column. We don't support changing defaults yet, do we?

**Comment by petermattis** [comment]
I was hoping that the `experimental_` in the name gave us license to change the name without worrying about backward compatibility. No, we don't support changing defaults yet.

**Comment by bdarnell** [comment]
True. I'm fine with this change being somewhat disruptive, e.g. requiring the user to manually alter their table. But until we support changing defaults the only recourse is to drop and recreate the table, which is unnecessarily harsh when keeping an alias is so cheap. 

Our own photos example app uses this function as a default, and while this isn't being used for any non-throwaway data it would still be nice to not have to wipe out our accumulated data and start over.

**Comment by petermattis** [comment]
Ugh, I grep'ed for existing uses of this function, but didn't `grep -i`. I'll send another PR to maintain an alias.

**Comment by JackKrupansky** [comment]
+1 for Adding ALTER TABLE t ALTER COLUMN c SET DEFAULT uuid_v4(), but...

If the user upgrades the software and some INSERTs occur before the ALTER, the old expressions will fail (panic?).

**Pull request merged**
