### PR TITLE
roachtest: adjust tpchvec test

### LINKED ISSUE #44108: roachtest: tpchvec failed
[(roachtest).tpchvec failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1695949&tab=buildLog) on [release-19.2@e00e840cad174e32112fac28e8b2264723997759](https://github.com/cockroachdb/cockroach/commits/e00e840cad174e32112fac28e8b2264723997759):

```
The test failed on branch=release-19.2, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20200117-1695949/tpchvec/run_1
	cluster.go:1296,context.go:135,cluster.go:1285,test_runner.go:753: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1695949-1579246502-18-n3cpu4 --oneshot --ignore-empty-nodes: exit status 1 1: 9398
		3: 19835
		2: dead
		Error:  2: dead
```

<details><summary>Repro</summary><p>

Artifacts: [/tpchvec](https://teamcity.cockroachdb.com/viewLog.html?buildId=1695949&tab=artifacts#/tpchvec)
```
make stressrace TESTS=tpchvec PKG=./pkg/roachtest TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit creates a separate "skip" map for 19.2 release so that fatal
OOM errors do not occur (19.2 doesn't have memory monitoring in place).

Also, now the test will fail if the vec ON time is at least 1.5 times
slower than vec OFF time. Currently this will only occur on queries that
ran at least 3 times to remove the outliers and reduce the noise.

Fixes: #44108.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44143)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/tpchvec.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44143#-Lz7U8fV2JjwyiNvTH0N:-Lz7U8fV2JjwyiNvTH0O:bpadvd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/37566526c4f70550a2d81809091ab7efb63811c8/pkg/cmd/roachtest/tpchvec.go#L100)):*
> ```Go
> 		}
> 		toSkip := queriesToSkip
> 		if strings.Contains(version, "19.2") {
> ```

I think this check should be stronger and be `HasPrefix`, similar to our ORM tests (the version string will probably need to be `v19.2`. We'll probably also want to extract this out into a mini helper for the future.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44143)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44143#-Lz7U8fV2JjwyiNvTH0N:-Lz8EWqE-zFyeyejJJqg:bqtyuzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/37566526c4f70550a2d81809091ab7efb63811c8/pkg/cmd/roachtest/tpchvec.go#L100)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this check should be stronger and be `HasPrefix`, similar to our ORM tests (the version string will probably need to be `v19.2`. We'll probably also want to extract this out into a mini helper for the future.
</blockquote></details>

Refactored.

Not sure what you're suggesting to extract into a helper.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44143#-:-Lz8muazEnxBjLnrO64h:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/cmd/roachtest/tpchvec.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44143#-Lz7U8fV2JjwyiNvTH0N:-Lz8mi333Pq5I6OOhPIs:bfpt1te) ([raw file](https://github.com/cockroachdb/cockroach/blob/37566526c4f70550a2d81809091ab7efb63811c8/pkg/cmd/roachtest/tpchvec.go#L100)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Refactored.

Not sure what you're suggesting to extract into a helper.
</blockquote></details>

I was just suggesting that we write something like `getBlacklistForVersion`

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44143#-:-Lz8nlsE70-QJ_Z4k2JN:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44143#-Lz7U8fV2JjwyiNvTH0N:-Lz8nnaA8c_rOwjpENuZ:b-gbdn8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/37566526c4f70550a2d81809091ab7efb63811c8/pkg/cmd/roachtest/tpchvec.go#L100)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I was just suggesting that we write something like `getBlacklistForVersion`
</blockquote></details>

Oh, yeah, that would be beneficial.

**Pull request merged**
