### PR TITLE
sql: use IndexFetchSpec in TableReader

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### row: replace fetcher args with IndexFetchSpec

This commit replaces the row fetcher table args with IndexFetchSpec.

Release note: None

#### sql: use IndexFetchSpec in TableReader

This commit removes the table descriptor from TableReader and replaces
it with an IndexFetchSpec.

Eventually, we will use the same `IndexFetchSpec` to form the columnar
batch directly in KV.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76394)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/catalog/descpb/index_fetch.proto, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_DSaD5MTTg8YNqRvf:-Mv_DSaD5MTTg8YNqRvg:b-akvm8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b955f0dbf8dbaeda3541cbdd8a50f0aa27a4a4f7/pkg/sql/catalog/descpb/index_fetch.proto#L81)):*
> ```protobuf
>   // TableModificationTime is the timestamp of the transaction which last
>   // modified the table descriptor.
>   // TODO(radu, otan): take this into account during planning and remove it from
> ```

CC @otan

**Review by yuzefovich — COMMENTED** [review]
Nice!

> Reviewed 11 of 11 files at r1, 29 of 29 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-:-Mv_QFUC6QOC3wiijfwr:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @RaduBerinde)

___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_MhNR8sfPct-cQf9I:-Mv_MhNR8sfPct-cQf9J:b-ohrf7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa55a793ecc10261524273d9ef4e9e2409d34a56/pkg/ccl/changefeedccl/rowfetcher_cache.go#L168)):*
> ```Go
> 	// TODO(dan): Allow for decoding a subset of the columns.
> 	publicCols := tableDesc.PublicColumns()
> 	colIDs := make([]descpb.ColumnID, len(publicCols))
> ```

nit: are there many places where we need IDs of all public columns? It might be worth introducing a method on the table descriptor for it.
___
*[pkg/ccl/cliccl/debug_backup.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_MyPzEfPChgBvtLZd:-Mv_MyPzEfPChgBvtLZe:b-7za8c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa55a793ecc10261524273d9ef4e9e2409d34a56/pkg/ccl/cliccl/debug_backup.go#L566)):*
> ```Go
> 	ctx context.Context, entry backupccl.BackupTableEntry, codec keys.SQLCodec,
> ) (row.Fetcher, error) {
> 	colIDs := make([]descpb.ColumnID, len(entry.Desc.PublicColumns()))
> ```

nit: looks like here we could reuse the new method.
___
*[pkg/sql/catalog/descpb/index_fetch.proto, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_ORNUDWR_AdOvZELO:-Mv_ORNUDWR_AdOvZELP:b-gbioa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b955f0dbf8dbaeda3541cbdd8a50f0aa27a4a4f7/pkg/sql/catalog/descpb/index_fetch.proto#L72)):*
> ```protobuf
>   }
> 
>   optional uint32 version = 1 [(gogoproto.nullable) = false];
> ```

nit: can you add some words for why we need versioning in this spec, separate from the DistSQL versions?
___
*[pkg/sql/execinfrapb/flow_diagram.go, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_Oy1g7aD_jshTlmle:-Mv_Oy1g7aD_jshTlmlf:bowzpz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b955f0dbf8dbaeda3541cbdd8a50f0aa27a4a4f7/pkg/sql/execinfrapb/flow_diagram.go#L170)):*
> ```Go
> 		for i := range keyDirs {
> 			keyDirs[i] = encoding.Ascending
> 			if tr.FetchSpec.KeyAndSuffixColumns[i].Direction == descpb.IndexDescriptor_ASC {
> ```

Shouldn't we use `DESC` in the conditional?
___
*[pkg/sql/row/fetcher_mvcc_test.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_NVWS-Kua60rnN35e:-Mv_NVWS-Kua60rnN35f:b-iipjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa55a793ecc10261524273d9ef4e9e2409d34a56/pkg/sql/row/fetcher_mvcc_test.go#L86)):*
> ```Go
> 	desc := desctestutils.TestingGetPublicTableDescriptor(kvDB, keys.SystemSQLCodec, `d`, `parent`)
> 	var colIDs []descpb.ColumnID
> 	for _, col := range desc.PublicColumns() {
> ```

nit: ditto
___
*[pkg/sql/row/fetcher_test.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_NalN4xomBYicyBoc:-Mv_NalN4xomBYicyBod:b-iipjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa55a793ecc10261524273d9ef4e9e2409d34a56/pkg/sql/row/fetcher_test.go#L55)):*
> ```Go
> 		}
> 	} else {
> 		for _, col := range publicCols {
> ```

nit: ditto

**Comment by otan** [comment]
___
*[pkg/sql/catalog/descpb/index_fetch.proto, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_DSaD5MTTg8YNqRvf:-Mv_W2Hu6nRtddB_ISKQ:b4vec7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b955f0dbf8dbaeda3541cbdd8a50f0aa27a4a4f7/pkg/sql/catalog/descpb/index_fetch.proto#L81)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

CC @otan 
</blockquote></details>

ack, sorry i haven't had time recently to take a deeper look.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-:-Mv_eXyxCIvItnDW4YV2:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/execinfrapb/flow_diagram.go, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_Oy1g7aD_jshTlmle:-Mv_Y3OJ3XuizxQwy_Ux:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b955f0dbf8dbaeda3541cbdd8a50f0aa27a4a4f7/pkg/sql/execinfrapb/flow_diagram.go#L170)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Shouldn't we use `DESC` in the conditional?
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 35 of 35 files at r3, 54 of 54 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-:-Mv_mYJoAknInxP2aV0b:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/execinfrapb/flow_diagram.go, line 147 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_ktc32RYUrh_hpgDr:-Mv_ktc32RYUrh_hpgDs:b-pk00jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9555cb5d9a50a550e1714c34a066eecd2a471e79/pkg/sql/execinfrapb/flow_diagram.go#L147)):*
> ```Go
> func (tr *TableReaderSpec) summary() (string, []string) {
> 	details := make([]string, 0, 3)
> 	details = append(details, indexDetail(&tr.Table, tr.IndexIdx))
> ```

nit: it could have been cleaner to refactor `indexDetail` in a separate commit (to print out the actual name of the primary index rather than "primary"). Then there would be less changes in the main commit of this PR. I guess at this point it's probably not worth the effort. It might be a good idea to still make such a change.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76394)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/execinfrapb/flow_diagram.go, line 147 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_ktc32RYUrh_hpgDr:-Mv_t0qj6nqqogeYXm2w:b-nrucnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9555cb5d9a50a550e1714c34a066eecd2a471e79/pkg/sql/execinfrapb/flow_diagram.go#L147)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it could have been cleaner to refactor `indexDetail` in a separate commit (to print out the actual name of the primary index rather than "primary"). Then there would be less changes in the main commit of this PR. I guess at this point it's probably not worth the effort. It might be a good idea to still make such a change.
</blockquote></details>

I'll try to do that and open a separate PR, then rebase this one.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/execinfrapb/flow_diagram.go, line 147 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_ktc32RYUrh_hpgDr:-Mv_vgb96R6LfMDpWLv_:b-yt038) ([raw file](https://github.com/cockroachdb/cockroach/blob/9555cb5d9a50a550e1714c34a066eecd2a471e79/pkg/sql/execinfrapb/flow_diagram.go#L147)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'll try to do that and open a separate PR, then rebase this one.
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/76406

**Review by yuzefovich — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76394)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/execinfrapb/flow_diagram.go, line 147 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-Mv_ktc32RYUrh_hpgDr:-MvaApqwAL1JueatC3qP:b-k6rpao) ([raw file](https://github.com/cockroachdb/cockroach/blob/9555cb5d9a50a550e1714c34a066eecd2a471e79/pkg/sql/execinfrapb/flow_diagram.go#L147)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/pull/76406
</blockquote></details>

Sounds good, thanks!

**Review by RaduBerinde — COMMENTED** [review]
Rebased after merging the separate change to flow diagrams.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-:-MvdXxZX-E-ZL53-A5Yh:bi2843v)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jordanlewis, @RaduBerinde, and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
> Reviewed 62 of 62 files at r6, 62 of 62 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76394)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @jordanlewis)

**Review by RaduBerinde — COMMENTED** [review]
I made a small change to put the descriptor modification time directly in `TableReaderSpec` instead of `IndexFetchSpec`. This keeps the `IndexFetchSpec` smaller and will reduce the churn if we remove it later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76394#-:-MveE72K9vPrdsljXF-f:bonwfk7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jordanlewis, and @yuzefovich)

**Pull request merged**
