### PR TITLE
opt: support ORDER BY in window functions

### PR DESCRIPTION
**Pull request by justinj**
This required being able to re-use window function columns so there's
also a bit of moving stuff around to accomodate that.

Release note: None

### CODE REVIEW

**Comment by justinj** [comment]
ping!

**Review by yuzefovich — COMMENTED** [review]
Awesome stuff! It :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-:-LdoRbbRBq2B5nQtP96X:b-9os3n4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/window.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-LdoQjFGAg9YL2WgJAy1:-LdoQjFH2GwPxcOuXRGL:b-li8ytp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6fcc1d0cdc0095526b704e4d612c10f4ec835c1/pkg/sql/opt/optbuilder/window.go#L82)):*
> ```Go
> 	// would be good if the windower supported being specified with constant
> 	// values.
> 	// TODO(justin): it's possible we could reuse some projections here, if a
> ```

[nit]: this TODO has been done, right? I'm interpreting this as being able to reuse the same projections by multiple window functions, and we're doing it with `findExistingCol`. Or am I reading this wrong?
___
*[pkg/sql/opt/optbuilder/testdata/window, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-LdoRH_h2gOYA5zFExU8:-LdoRH_h2gOYA5zFExU9:bncceb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6fcc1d0cdc0095526b704e4d612c10f4ec835c1/pkg/sql/opt/optbuilder/testdata/window#L361)):*
> ```
> ----
> project
>  ├── columns: k:1(int!null) rank:8(int) rank:8(int)
> ```

So this means that `rank` will need to be computed once, right?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37185)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-Lde6Qr37t__gNxnKBv5:-Lde6Qr37t__gNxnKBv6:bsrjcag) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6fcc1d0cdc0095526b704e4d612c10f4ec835c1/pkg/sql/opt/ops/relational.opt#L869)):*
> ```
>     # Ordering is the ordering that the window function is computed relative to
>     # within each partition.
>     Ordering OrderingChoice
> ```

We need a normalization rule to simplify this according to the input's FDs (and some tests around that). See the `SimplifyGroupByOrdering` rule for an example.

Sorry I wrote this a while back but forgot to publish.

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37185)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/ops/relational.opt, line 869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-Lde6Qr37t__gNxnKBv5:-LdomRON8zb_P_wCq2AQ:bjdvxup) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6fcc1d0cdc0095526b704e4d612c10f4ec835c1/pkg/sql/opt/ops/relational.opt#L869)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We need a normalization rule to simplify this according to the input's FDs (and some tests around that). See the `SimplifyGroupByOrdering` rule for an example.

Sorry I wrote this a while back but forgot to publish.
</blockquote></details>

I have a branch locally that adds this (and also reduction of the partition cols), it's not a correctness issue in the meantime, so I figured it made sense to do a bunch of the "standard" norm rules together in one PR. 
___
*[pkg/sql/opt/optbuilder/window.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-LdoQjFGAg9YL2WgJAy1:-LdommAF3TpmGT98-s8A:br0da5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6fcc1d0cdc0095526b704e4d612c10f4ec835c1/pkg/sql/opt/optbuilder/window.go#L82)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: this TODO has been done, right? I'm interpreting this as being able to reuse the same projections by multiple window functions, and we're doing it with `findExistingCol`. Or am I reading this wrong?
</blockquote></details>

Yes, you're right! Fixed.
___
*[pkg/sql/opt/optbuilder/testdata/window, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-LdoRH_h2gOYA5zFExU8:-Ldomf-yCvy1WtwU_VeJ:bot3qw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6fcc1d0cdc0095526b704e4d612c10f4ec835c1/pkg/sql/opt/optbuilder/testdata/window#L361)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

So this means that `rank` will need to be computed once, right?
</blockquote></details>

Yup, it gets re-used.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-:-LdpNUVd8A4HD7i6lnUd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/window.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-LdpL9LBD7zZrdHBhyAa:-LdpL9LBD7zZrdHBhyAb:b-ypaif2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d7f25d19811a4fe663d5d5fc85a8fda94930492/pkg/sql/opt/optbuilder/window.go#L136)):*
> ```Go
> 						expr,
> 					)
> 				}
> ```

This code is basically the same as the code in the for-loop above for partitions. Not sure if it's possible, but maybe you could create a helper function?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-:-LdpW1b_70SVeF4qHRu1:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @yuzefovich)

___
*[pkg/sql/opt/ops/relational.opt, line 869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-Lde6Qr37t__gNxnKBv5:-LdpVjPP49uLOPe1QpaT:b-k6rpao) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6fcc1d0cdc0095526b704e4d612c10f4ec835c1/pkg/sql/opt/ops/relational.opt#L869)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I have a branch locally that adds this (and also reduction of the partition cols), it's not a correctness issue in the meantime, so I figured it made sense to do a bunch of the "standard" norm rules together in one PR. 
</blockquote></details>

Sounds good, thanks!

**Review by justinj — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-:-LdtFARyCSKSIPim9s1z:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/window.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-LdpL9LBD7zZrdHBhyAa:-LdtDp7O7pUB-7Jr4nYl:b5tb0lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d7f25d19811a4fe663d5d5fc85a8fda94930492/pkg/sql/opt/optbuilder/window.go#L136)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This code is basically the same as the code in the for-loop above for partitions. Not sure if it's possible, but maybe you could create a helper function?
</blockquote></details>

I spent some time thinking about this and I couldn't come up with a way that felt clearer than what was here. I think you'd need to pass a function around or something to maintain the direction of the ordering, and it just gets kind of messy. Open to suggestions to make this better though! While attempting to unify them I did take the opportunity to flatten partition tuples as well, though.

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/optbuilder/window.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37185#-LdpL9LBD7zZrdHBhyAa:-Ldu2kI4CAXU8zAkq39N:b7wmf9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d7f25d19811a4fe663d5d5fc85a8fda94930492/pkg/sql/opt/optbuilder/window.go#L136)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I spent some time thinking about this and I couldn't come up with a way that felt clearer than what was here. I think you'd need to pass a function around or something to maintain the direction of the ordering, and it just gets kind of messy. Open to suggestions to make this better though! While attempting to unify them I did take the opportunity to flatten partition tuples as well, though.
</blockquote></details>

Ok thanks for looking into it!

**Pull request merged**
