### PR TITLE
sql: fix bugs in adding foreign keys

### LINKED ISSUE #57592: sql: concurrent FK constraint addition and unique index deletion can result in FKs with no unique constraint
```
demo@127.0.0.1:26257/defaultdb> create table t1(a int);
CREATE TABLE
demo@127.0.0.1:26257/defaultdb> create unique index idx on t1(a);
CREATE INDEX
demo@127.0.0.1:26257/defaultdb> create table t2(a int);
CREATE TABLE
demo@127.0.0.1:26257/defaultdb> begin;
BEGIN
demo@127.0.0.1:26257/defaultdb  OPEN> alter table t2 add foreign key (a) references t1(a);
ALTER TABLE
demo@127.0.0.1:26257/defaultdb  OPEN> drop index idx;
NOTICE: the data for dropped indexes is reclaimed asynchronously
HINT: The reclamation delay can be customized in the zone configuration for the table.
DROP INDEX
demo@127.0.0.1:26257/defaultdb  OPEN> commit;
COMMIT
```

At this point, column `a` on `t2` is being referenced as a foreign key, but there's no unique index on it:

```
demo@127.0.0.1:26257/defaultdb> show create t2;
  table_name |                          create_statement
-------------+----------------------------------------------------------------------
  t2         | CREATE TABLE public.t2 (
             |     a INT8 NULL,
             |     CONSTRAINT fk_a_ref_t1 FOREIGN KEY (a) REFERENCES public.t1(a),
             |     FAMILY "primary" (a, rowid)
             | )
(1 row)
demo@127.0.0.1:26257/defaultdb> show create t1;
  table_name |        create_statement
-------------+----------------------------------
  t1         | CREATE TABLE public.t1 (
             |     a INT8 NULL,
             |     FAMILY "primary" (a, rowid)
             | )
(1 row)
```

In this invalid state, updates sort of work as you'd expect:

```
demo@127.0.0.1:26257/defaultdb> insert into t1 values (1), (1);
INSERT 2
demo@127.0.0.1:26257/defaultdb> insert into t2 values (1);
INSERT 1
demo@127.0.0.1:26257/defaultdb> insert into t2 values (2);
ERROR: insert on table "t2" violates foreign key constraint "fk_a_ref_t1"
SQLSTATE: 23503
DETAIL: Key (a)=(2) is not present in table "t1".
CONSTRAINT: fk_a_ref_t1
demo@127.0.0.1:26257/defaultdb> select rowid, a from t1;
        rowid        | a
---------------------+----
  612959199124815873 | 1
  612959199124848641 | 1
(2 rows)
demo@127.0.0.1:26257/defaultdb> update t1 set a = 3 where rowid = 612959199124815873;
ERROR: update on table "t1" violates foreign key constraint "fk_a_ref_t1" on table "t2"
SQLSTATE: 23503
DETAIL: Key (a)=(1) is still referenced from table "t2".
CONSTRAINT: fk_a_ref_t1
demo@127.0.0.1:26257/defaultdb> delete from t1 where rowid = 612959199124815873;
ERROR: delete on table "t1" violates foreign key constraint "fk_a_ref_t1" on table "t2"
SQLSTATE: 23503
DETAIL: Key (a)=(1) is still referenced from table "t2".
CONSTRAINT: fk_a_ref_t1
```

The problem is that we don't update the referenced table with the backreference until later in the job, so the index drop proceeds without knowing about the index, but we only check for the presence of a unique index in the user transaction when creating the FK. This can happen across two concurrent schema changes initiated in different sessions, too.

### LINKED ISSUE #57596: sql: overly strict validation while rolling back constraint schema changes causes failures
If the addition of a foreign key fails (in the below repro, it's initiated in the same transaction as attempting to a invalid unique index) and is rolled back before the backreference is added, we won't be able to roll back the schema change:

```
root@127.0.0.1:64580/defaultdb> create table t(a int); insert into t values (1), (1);
INSERT 2
root@127.0.0.1:64580/defaultdb> create table t2(a int primary key);
CREATE TABLE
root@127.0.0.1:64580/defaultdb> begin;
BEGIN
root@127.0.0.1:64580/defaultdb  OPEN> create unique index on t(a);
CREATE INDEX
root@127.0.0.1:64580/defaultdb  OPEN> alter table t add foreign key (a) references t2;
ALTER TABLE
root@127.0.0.1:64580/defaultdb  OPEN> commit;
ERROR: transaction committed but schema change aborted with error: (23505): duplicate key value (a)=(1) violates unique constraint "t_a_key"
SQLSTATE: XXA00
HINT: Some of the non-DDL statements may have committed successfully, but some of the DDL statement(s) failed.
Manual inspection may be required to determine the actual state of the database.
--
See: https://github.com/cockroachdb/cockroach/issues/42061
root@127.0.0.1:64580/defaultdb> show jobs;
        job_id       |     job_type     |                                                           description                                                           | statement | user_name |  status   | running_status |             created              |             started              |             finished             |             modified             | fraction_completed |                                                                            error                                                                             | coordinator_id
---------------------+------------------+---------------------------------------------------------------------------------------------------------------------------------+-----------+-----------+-----------+----------------+----------------------------------+----------------------------------+----------------------------------+----------------------------------+--------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------
...
  612970272619069441 | SCHEMA CHANGE    | CREATE UNIQUE INDEX ON defaultdb.public.t (a);ALTER TABLE defaultdb.public.t ADD FOREIGN KEY (a) REFERENCES defaultdb.public.t2 |           | root      | failed    | NULL           | 2020-12-05 02:07:27.666965+00:00 | 2020-12-05 02:08:16.618272+00:00 | 2020-12-05 02:08:16.646791+00:00 | 2020-12-05 02:08:16.635816+00:00 |                  0 | job 612970272619069441: cannot be reverted, manual cleanup may be required: there was no foreign key backreference for constraint "fk_a_ref_t2" on table "t" |           NULL
...
```

That error in the job while reverting comes from here:

https://github.com/cockroachdb/cockroach/blob/510d541a1fa3de372aa3b788388e837971c6cb93/pkg/sql/schema_changer.go#L1573-L1575

`removeFKBackReferenceFromTable` returns an assertion error if the backreference can't be found, which we should not return here.

### PR DESCRIPTION
**Pull request by thoszhang**
See individual commits for details.

Fixes #57592.
Fixes #57596.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57598)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/backfill.go, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57598#-MO7c0eV9DmcCzgaBsqc:-MO7c0eX-cNVTIbn2QXV:buj6433) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff9f098a49b60443fd5fb96754c731d7e3ba886/pkg/sql/backfill.go#L552)):*
> ```Go
> 					}
> 					// Check that a unique constraint for the FK still exists on the
> 					// referenced table. It's possible for the unique index found during
> ```

This might break some existing corrupted descriptors, right? I think that's fine but maybe we'll want to encourage people to run the doctor tool with the new version before upgrading. 
___
*[pkg/sql/schema_changer.go, line 1576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57598#-MO7bllR-q_qPm-5lowb:-MO7bllR-q_qPm-5lowc:bu909te) ([raw file](https://github.com/cockroachdb/cockroach/blob/61b05be2ad51469fb0e4ec91c81cd350be1b00fa/pkg/sql/schema_changer.go#L1576)):*
> ```Go
> 						// The function being called will return an assertion error if the
> 						// backreference was not found, but it may not have been installed
> 						// during the incomplete schema change, so we swallow the error.
> ```

log the error too? It doesn't hurt and in cases where there's an unexpected error here, it'll be good to see it.
Also, I don't expect this to be a common occurrence, why wrap it in a `log.V`?

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57598)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/backfill.go, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57598#-MO7c0eV9DmcCzgaBsqc:-MO9Jt90AZxGAky4nMxt:b-a9zxx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff9f098a49b60443fd5fb96754c731d7e3ba886/pkg/sql/backfill.go#L552)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This might break some existing corrupted descriptors, right? I think that's fine but maybe we'll want to encourage people to run the doctor tool with the new version before upgrading. 
</blockquote></details>

I haven't made any changes to validation for existing descriptors (and wasn't intending to do it in a point release). Are you specifically referring to this check that happens during the schema change itself?
___
*[pkg/sql/schema_changer.go, line 1576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57598#-MO7bllR-q_qPm-5lowb:-MO9MU8o-q7Z6IaXAIdV:b-kkt96b) ([raw file](https://github.com/cockroachdb/cockroach/blob/61b05be2ad51469fb0e4ec91c81cd350be1b00fa/pkg/sql/schema_changer.go#L1576)):*
Done.

> Also, I don't expect this to be a common occurrence, why wrap it in a log.V?

No good reason.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57598#-:-MOESKEm8EAkwYxoziyE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/backfill.go, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57598#-MO7c0eV9DmcCzgaBsqc:-MOESHxw9g6zg7pLXNV8:b-dmm5nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ff9f098a49b60443fd5fb96754c731d7e3ba886/pkg/sql/backfill.go#L552)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I haven't made any changes to validation for existing descriptors (and wasn't intending to do it in a point release). Are you specifically referring to this check that happens during the schema change itself?
</blockquote></details>

whoops.
___
*[pkg/sql/schema_changer.go, line 1576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57598#-MO7bllR-q_qPm-5lowb:-MOESBA89TPUGg3eHNzz:b-7xdugw) ([raw file](https://github.com/cockroachdb/cockroach/blob/61b05be2ad51469fb0e4ec91c81cd350be1b00fa/pkg/sql/schema_changer.go#L1576)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Done.

> Also, I don't expect this to be a common occurrence, why wrap it in a log.V?

No good reason.
</blockquote></details>

It's still wrapped in a V. This feels like a regular old `log.Infof` to me. That's my only remaining nit.

**Review by thoszhang — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57598#-:-MOEi1ueBTJEIuH90XY8:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/schema_changer.go, line 1576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57598#-MO7bllR-q_qPm-5lowb:-MOEi03g0mxxDHQpYCvE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61b05be2ad51469fb0e4ec91c81cd350be1b00fa/pkg/sql/schema_changer.go#L1576)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It's still wrapped in a V. This feels like a regular old `log.Infof` to me. That's my only remaining nit. 
</blockquote></details>

Done.

**Pull request merged**
