### PR TITLE
*: update gofmt to 1.11

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change updates the `cockroachdb/gostdlib` dependency which
vendors `gofmt`/`goimports` and is used by `crlfmt`.

There were changes to `gofmt` in go1.11 which results in some diffs
(included in the change).

Note: it's recommended to configure your editor to use
`crlfmt/gofmt/goimports` in the `cockroachdb/bin` directory. If you
see unexpected diffs, try `rm bin/.bootstrap; make` to force a rebuild
of the binaries.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

I'm hoping https://github.com/cockroachdb/cockroach/pull/33282 will be merged by the time you get around to bors'ing this, so you'll have to bump the vendor. Sorry about that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34076#-:-LWPrnowB67M6AJzZ2lb:b-alfo2a)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by petermattis** [comment]
LGTM

You should send an email to eng@ and a short message to #engineering about this change.

**Comment by RaduBerinde** [comment]
> You should send an email to eng@ and a short message to #engineering about this change.
Yeah, I have it written down, will send when this merges.

**Pull request merged**
