### PR TITLE
More cleanup and simplification of the kv.send interface.

### PR DESCRIPTION
**Pull request by petermattis**
Besides the simplification, this is a (very) small performance win. I
Need to figure out what is causing the variation in the Bank benchmark
timings. It definitely didn't get slower due to this change. Perhaps
transaction restarts when operations collide.

```
name                   old time/op    new time/op    delta
Bank_Cockroach-8          166µs ±15%     177µs ±14%    ~      (p=0.079 n=10+9)
Insert1_Cockroach-8       382µs ± 1%     376µs ± 1%  -1.47%  (p=0.000 n=10+10)
Insert10_Cockroach-8      775µs ± 2%     760µs ± 2%  -1.90%  (p=0.003 n=10+10)
Insert100_Cockroach-8    4.11ms ± 1%    4.07ms ± 1%  -1.08%   (p=0.003 n=10+9)
Update1_Cockroach-8       870µs ± 1%     855µs ± 1%  -1.73%  (p=0.000 n=10+10)
Update10_Cockroach-8     4.75ms ± 1%    4.59ms ± 1%  -3.22%   (p=0.000 n=9+10)
Update100_Cockroach-8    42.8ms ± 1%    40.9ms ± 0%  -4.52%   (p=0.000 n=10+8)
Delete1_Cockroach-8      1.20ms ± 1%    1.18ms ± 1%  -2.15%  (p=0.000 n=10+10)
Delete10_Cockroach-8     1.93ms ± 1%    1.91ms ± 2%  -1.28%  (p=0.004 n=10+10)
Delete100_Cockroach-8    10.7ms ± 1%    10.7ms ± 2%    ~      (p=0.182 n=9+10)
Scan1_Cockroach-8         187µs ± 1%     183µs ± 1%  -2.14%  (p=0.000 n=10+10)
Scan10_Cockroach-8        228µs ± 1%     224µs ± 1%  -1.93%  (p=0.000 n=10+10)
Scan100_Cockroach-8       612µs ± 4%     598µs ± 2%  -2.28%  (p=0.002 n=10+10)

name                   old allocs/op  new allocs/op  delta
Bank_Cockroach-8            624 ± 1%       617 ± 1%  -1.17%   (p=0.000 n=9+10)
Insert1_Cockroach-8         486 ± 0%       481 ± 0%  -1.07%   (p=0.000 n=6+10)
Insert10_Cockroach-8      1.13k ± 0%     1.12k ± 0%  -0.49%  (p=0.000 n=10+10)
Insert100_Cockroach-8     7.32k ± 0%     7.32k ± 0%  -0.08%  (p=0.000 n=10+10)
Update1_Cockroach-8       1.10k ± 0%     1.08k ± 0%  -1.37%  (p=0.000 n=10+10)
Update10_Cockroach-8      7.36k ± 0%     7.26k ± 0%  -1.43%    (p=0.000 n=9+8)
Update100_Cockroach-8     69.9k ± 0%     68.9k ± 0%  -1.45%  (p=0.000 n=10+10)
Delete1_Cockroach-8       1.05k ± 0%     1.03k ± 0%  -1.37%   (p=0.000 n=7+10)
Delete10_Cockroach-8      2.53k ± 0%     2.51k ± 0%  -0.63%  (p=0.000 n=10+10)
Delete100_Cockroach-8     16.6k ± 0%     16.6k ± 0%  -0.08%   (p=0.000 n=10+8)
Scan1_Cockroach-8           297 ± 0%       292 ± 0%  -1.75%  (p=0.000 n=10+10)
Scan10_Cockroach-8          388 ± 0%       383 ± 0%  -1.24%  (p=0.000 n=10+10)
Scan100_Cockroach-8       1.12k ± 0%     1.12k ± 0%  -0.40%   (p=0.000 n=10+8)
```

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4167)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

---

Reviewed 6 of 6 files at r1, 8 of 8 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4167#-:-K9mzJ3dc_q6nV3mDOfv:676834233)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[kv/dist_sender.go, line 254 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4167#-K9mzXNl-qzYYlkbEEYF:-K9mzXNl-qzYYlkbEEYG:1104543763) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ed2831a8ef873594e2bac671a157142741f4553/kv/dist_sender.go#L254)):*
empty trailing comment

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4167)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/dist_sender.go, line 254 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4167#-K9mzXNl-qzYYlkbEEYF:-K9n-qRwy4jezceG3s6A:1281768999) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ed2831a8ef873594e2bac671a157142741f4553/kv/dist_sender.go#L254)):*
Where did that come from? Fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4167)*

**Comment by tschottdorf** [comment]
LGTM. I like the additional clarity. We should continue to seek out places which modify their arguments non-shallowly and replace the parts modified with a new copy. I believe we only have a small number of those.

---

Reviewed 6 of 6 files at r1, 8 of 8 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4167#-:-K9n1nxNV50-bShtFCPL:1902058083)*

**Comment by petermattis** [comment]
@tschottdorf Agreed.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4167#-:-K9n39xpZa_t9ipifsia:-157179387)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4167)*

**Pull request merged**
