### PR TITLE
telemetry: don't resample transaction for telemetry on restart

### LINKED ISSUE #119284: telemetry: don't resample transactions on retry
Currently for transaction logging to telemetry we resample transaction executions on automatic retries. We shouldn't do that since they are part of the same execution. The sampling decision should just occur once at the start of the transaction.

Jira issue: CRDB-36126

### PR DESCRIPTION
**Pull request by xinhaoz**
### telemetry: don't resample transaction for telemetry on restart

We will only attempt to sample the transaction once at the
start of its execution.

Additional changes:
- Move the sampling decision for transactions to be closer to section
updating `extraTxnState`
- Use the concrete statement types in `shouldForceLogStatement` to
prevent force logging on BEGIN and COMMIT statements.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/119284

Release note: None

### eventpbgen: rename Nullable property to NotNullable

Let's rename the `Nullable` field to `NotNullable` for the
`fieldInfo` struct used in generating json encoding functions
for protobuf definitons. Note this field currently only applies to
`nestedMessage` types.

Epic: none

Release note: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
Code changes :lgtm_strong:! Just some requests for improvements to docs/comments/etc for clarity.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-:-NrkTKXrE3ZR91PMLyuz:b-sqhy91)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-NrkLbbv5Jx7X33owsDK):*
nit: I am having a bit of trouble understanding the meaning of "modifies" here, can we reword a bit for clarity? 



_Code quote:_
```
  - Move the sampling decision for transactions to be closer to section
  updating `extraTxnState` and modifies
```
___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-NrkSpRiEEO7vFCgP1y8):*
nit: can we provide more info about the motivation for this change? 

At a first glance, changing `{{ if .Nullable -}}` to `{{ if not .NotNullable -}}` feels more difficult to read. 



_Code quote:_
```
  Let's rename the `Nullable` field to `NotNullable` for the
  `fieldInfo` struct used in generating json encoding functions
  for protobuf definitons. Note this field currently only applies to
  `nestedMessage` types.
```
___
*[`pkg/sql/testdata/telemetry_logging/logging/transaction_mode` line 302 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-NrkSLkU9dUS6RXklSQt:-NrkSLkV9iW2TI8XjPN0:bc0dlzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b95d132f28478ec04fd7286d5d635c3deac2a4a/pkg/sql/testdata/telemetry_logging/logging/transaction_mode#L302)):*
> ```
> # Execute a query at time=1 so that the the next txn is not sampled.
> # Retries of that txn should also not be sampled, even if those executions meet
> # the sampling criteria.
> ```

nit: here, and for the reverse scenario below, it'd be helpful for someone new to these tests to provide a bit more context as to *why* the txn is expect to be sampled/not sampled, given these params .  



_Code quote:_
```
# Execute a query at time=1 so that the the next txn is not sampled.
# Retries of that txn should also not be sampled, even if those executions meet
# the sampling criteria.
```
___
*[`pkg/sql/testdata/telemetry_logging/logging/transaction_mode` line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-NrkMoaADO_gBLI0sWw6:-NrkMoaADO_gBLI0sWw7:b-dl6y13) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b95d132f28478ec04fd7286d5d635c3deac2a4a/pkg/sql/testdata/telemetry_logging/logging/transaction_mode#L335)):*
> ```
> }
> 
> # The stub time be advanced in the retry - even though enough time has elapsed for the
> ```

nit: "will be"



_Code quote:_
```
The stub time be advanced in the retry
```

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119481)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-NrkLbbv5Jx7X33owsDK):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: I am having a bit of trouble understanding the meaning of "modifies" here, can we reword a bit for clarity?
</blockquote></details>

Oops that does not make sense bc it should have been deleted :sweat_smile: - done.
___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-NrkSpRiEEO7vFCgP1y8):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can we provide more info about the motivation for this change? 

At a first glance, changing `{{ if .Nullable -}}` to `{{ if not .NotNullable -}}` feels more difficult to read.
</blockquote></details>

Ah yeah it was a follow up to this comment - https://github.com/cockroachdb/cockroach/pull/118432#pullrequestreview-1872799993.
___
*[`pkg/sql/testdata/telemetry_logging/logging/transaction_mode` line 302 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-NrkSLkU9dUS6RXklSQt:-NrkWqu23OYtIxgPI-Io:b-kthot) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b95d132f28478ec04fd7286d5d635c3deac2a4a/pkg/sql/testdata/telemetry_logging/logging/transaction_mode#L302)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: here, and for the reverse scenario below, it'd be helpful for someone new to these tests to provide a bit more context as to *why* the txn is expect to be sampled/not sampled, given these params .
</blockquote></details>

Edited comments to be more clear - lmk if the changes help clarify the scenario here!
___
*[`pkg/sql/testdata/telemetry_logging/logging/transaction_mode` line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-NrkMoaADO_gBLI0sWw6:-NrkWPm9DdlpVBB8tSU8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b95d132f28478ec04fd7286d5d635c3deac2a4a/pkg/sql/testdata/telemetry_logging/logging/transaction_mode#L335)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: "will be"
</blockquote></details>

Done.

**Review by abarganier — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-:-NsEFxBd0EsyAmysWp0Y:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-NrkSpRiEEO7vFCgP1y8):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Ah yeah it was a follow up to this comment - https://github.com/cockroachdb/cockroach/pull/118432#pullrequestreview-1872799993.
</blockquote></details>

Gotcha, makes sense. Thanks!
___
*[`pkg/sql/testdata/telemetry_logging/logging/transaction_mode` line 302 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119481#-NrkSLkU9dUS6RXklSQt:-NsEFmFR1pHI0-D87hI9:b62l9es) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b95d132f28478ec04fd7286d5d635c3deac2a4a/pkg/sql/testdata/telemetry_logging/logging/transaction_mode#L302)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Edited comments to be more clear - lmk if the changes help clarify the scenario here!
</blockquote></details>

It definitely does, thank you for adding more clarification :pray:

**Comment by xinhaoz** [comment]
tftr!
bors r+

**Pull request merged**
