### PR TITLE
Revert "pkg/cli: Refactor CLI to support streaming formatted results"

### PR DESCRIPTION
**Pull request by madelynnblue**
Reverts cockroachdb/cockroach#15277

This broke the master build:

```
pkg/cli/cert.go:189: cannot use rows (type [][]string) as type rowStrIter in argument to printQueryOutput:
	[][]string does not implement rowStrIter (missing Next method)
make: *** [build] Error 2
```

### CODE REVIEW

**Comment by richardartoul** [comment]
Sorry about that, I can rebase and make a new pull request. I thought the C.I would make sure it worked with the latest commits.

**Comment by tamird** [comment]
Is there a hurry to fix this? I was planning to resolve the conflict without reverting, but I won't be home for a few hours. @richardaroul maybe you could send a PR to resolve the conflict?

**Comment by mjibson** [comment]
If a real fix can be produced soon that's fine. Just thought we might want to have a non-broken build until then. If it'll only take a few hours then no need to merge this, it's fine to wait for it to be fixed instead of reverted.

**Comment by richardartoul** [comment]
Almost have the fix ready.

**Comment by richardartoul** [comment]
https://github.com/cockroachdb/cockroach/pull/15526

**Comment by knz** [comment]
Yes, the `master` build is fixed now.

**Pull request closed without merging**
