### PR TITLE
cli: fix inconsistent db admin-ui naming

### LINKED ISSUE #56993: DB Console naming is incorrect in a few places
**Describe the problem**

In 20.2, we renamed the Admin UI to DB Console. However, we missed a few places:

- In the standard output printed by `cockroach start` and `cockroach start-single-node`, we still use `webui`:

```
CockroachDB node starting at 2020-11-21 12:03:17.861953 +0000 UTC (took 1.5s)
build:               CCL v20.2.1 @ 2020/11/20 18:37:02 (go1.13.14)
webui:               http://Jesses-MBP-2:8080
sql:                 postgresql://root@Jesses-MBP-2:26257?sslmode=disable
RPC client flags:    ./cockroach <client cmd> --host=Jesses-MBP-2:26257 --insecure
logs:                /Users/jesseseldess/cockroach-v20.2.1.darwin-10.9-amd64/cockroach-data/logs
temp dir:            /Users/jesseseldess/cockroach-v20.2.1.darwin-10.9-amd64/cockroach-data/cockroach-temp909902347
external I/O path:   /Users/jesseseldess/cockroach-v20.2.1.darwin-10.9-amd64/cockroach-data/extern
store[0]:            path=/Users/jesseseldess/cockroach-v20.2.1.darwin-10.9-amd64/cockroach-data
storage engine:      pebble
status:              initialized new cluster
clusterID:           2ddf8604-983c-462a-a592-2e62a232bd4c
nodeID:              1
```

That contrasts with `cockroach demo`, which uses `console`:

```
# Connection parameters:
#   (console) http://127.0.0.1:60288
#   (sql)     postgres://root:admin@?host=%2Fvar%2Ffolders%2Fk1%2Fr048yqpd7_9337rgxm9vb_gw0000gn%2FT%2Fdemo441370957&port=26257
#   (sql/tcp) postgres://root:admin@127.0.0.1:60290?sslmode=require
```

- When in the DB Console, the title field in the html header is "Cockroach Console", and that shows on tabs:

Screen Shot 2020-11-21 at 7 05 58 AM

Please describe the issue you observed, and any steps we can take to reproduce it:

Jira issue: CRDB-2884

### PR DESCRIPTION
**Pull request by tharun208**
Release justification: non-production code changes

making admin-ui name to be consistent across
start and demo commands

Resolves #56993 #47977

Release note: None

Signed-off-by: Tharun <rajendrantharun@live.com>

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thanks for your offered change

unfortunately we found that the word "console" doesn't work well for the web UI, because for many folk the word "console" also designates the text terminal. Also there is confusion with the CockroachCloud console which is agains something different.

So maybe "web ui" or "web console" work better in the end, in which case we'll also want the indicator in demo_cluster.go to be changed accordingly.

@thtruo can you remind us what is the latest recommended terminology?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61253#-:-MUi-HAE3mLA-PzhnIpB:bj63re0)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tharun208** [comment]
just a thought , WDYT about `gui` ?

**Comment by knz** [comment]
we've never used the word "gui" elsewhere.

**Comment by tharun208** [comment]
so, can I change it to `web-console` at both UI and cli?

**Comment by knz** [comment]
best wait until @thtruo tells us what is best

**Comment by thtruo** [comment]
Apologies for the delayed response. Thanks @tharun208 for contributing! `web-console` looks reasonable - we'd welcome that naming change

**Pull request closed without merging**
