### PR TITLE
rowexec: make batch size of join reader ordering strategy a setting

### PR DESCRIPTION
**Pull request by yuzefovich**
Three different strategies of the join reader have different batch sizes
(which determine how many input rows are buffered to perform a lookup)
with the ordering strategy having the smallest size of 10KiB. This
commit introduces a private cluster setting (as well as the
corresponding session variable that will be propagated to the remote
flows) that determines that batch size but keeps 10KiB as the default
value.

Touches: #72857.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
Thanks!

**Review by yuzefovich — COMMENTED** [review]
Added the corresponding session variable too, please take another look :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72921#-:-MooY0Mo-qP4gPxY9ch0:b-n4k78f)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72921#-:-Mooftnw5Le6kDtAlLj0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
Made a minor change to appease the tests.

TFTR!

bors r+

**Pull request merged**
