### PR TITLE
sql: hard limit for scan in EXPLAIN + removing single-key optimization

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6911)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/scan.go, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6911#-KIehLrbzzIumefpUsKX:-KIehLrbzzIumefpUsKY:1358532541) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a24d7f9d61a5b393ee4c40bcf9b12e8818de2/sql/scan.go#L112)):*
> ```Go
> 	if numRows != math.MaxInt64 {
> 		n.limitHint = numRows
> 		n.limitSoft = soft || n.filter != nil
> ```

can you add a comment about the nil check?

---

*[sql/scan.go, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6911#-KIehQgLfqbk-G6z3ykV:-KIehQgLfqbk-G6z3ykW:1834351777) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a24d7f9d61a5b393ee4c40bcf9b12e8818de2/sql/scan.go#L142)):*
> ```Go
> 
> 	limitHint := n.limitHint
> 	if limitHint != 0 && n.limitSoft {
> ```

what's the point of the non-zero check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6911)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/scan.go, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6911#-KIehQgLfqbk-G6z3ykV:-KIelqd5uNmQ8Ic7bkBh:908985112) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a24d7f9d61a5b393ee4c40bcf9b12e8818de2/sql/scan.go#L142)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what's the point of the non-zero check?
</details>
limitHint = 0 is a special "no limit" value. I wanted to be consistent in handling it even if the math works out without the check (might help if we change the formula later). I can replace with a comment if you think that's better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6911)*

**Comment by RaduBerinde** [comment]
Updated - latest versions are r3 and r4.

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> #### sql: hard limit for scan in EXPLAIN \+ removing single\-key optimization
</details>


---

Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6911#-:-KIemdEekHTbJNjnHfQq:-787002727)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/scan.go, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6911#-KIehQgLfqbk-G6z3ykV:-KIeo_P1JcXNp9x8Tnvt:-1989063253) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f2a24d7f9d61a5b393ee4c40bcf9b12e8818de2/sql/scan.go#L142)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> limitHint = 0 is a special "no limit" value. I wanted to be consistent in handling it even if the math works out without the check (might help if we change the formula later). I can replace with a comment if you think that's better.
</details>
Nah, that's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6911)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Updated - latest versions are r3 and r4.
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6911#-:-KIeodO2dd423hyNcGdS:1417088721)*

**Comment by RaduBerinde** [comment]
TFTR!

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6911#-:-KIeqF2So68GpN8p_1MH:-485616692)*

**Pull request merged**
