### PR TITLE
hlc: micro-optimize hlc CAS

### PR DESCRIPTION
**Pull request by andreimatei**
This patch saves an atomic load after a successful CAS.
Two readers have suggested it before (me and Ben), so let's do it even
if it doesn't move any needles.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Addressing @bdarnell's comments on https://github.com/cockroachdb/cockroach/pull/47140

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48610)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48610#-:-M7I_ZGq3A-FImYl-rAR:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp)

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48610#-:-M7JYi2z6-lsGldkeBAC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @darinpp)

___
*[pkg/util/hlc/hlc.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48610#-M7JWr7H6mlTQFqWlc_E:-M7JWr7I-gu33F5C-FfA:b6ll1c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/27d25f3c2003f1d875d6b621b3e107b9e29d66bf/pkg/util/hlc/hlc.go#L226)):*
> ```Go
> // also checks for backwards and forwards jumps, as configured.
> func (c *Clock) getPhysicalClockAndCheck(ctx context.Context) int64 {
> 	oldTime := atomic.LoadInt64(&c.lastPhysicalTime)
> ```

This structure is a little unusual. Most CAS loops are implemented with all atomic accesses inside the loop like:
```
for {
    v := atomic.Load()
    if v ... some condition to check for concurrent changes {
        break
    }
    if atomic.CompareAndSwap(v) {
        break
    }
}
```
This reveals a bug / change in behavior here that I don't think was intentional - we're now relying on `physicalClock` to be monotonic in order for `getPhysicalClockAndCheck` to be monotonic because we don't compare `oldTime` and `newTime` on the first iteration. Since we're here, I'd recommend we switch around the structure here a bit.

**Review by darinpp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48610)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/util/hlc/hlc.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48610#-M7JWr7H6mlTQFqWlc_E:-M7JkVUnBnaTCXswL29f:b-edk6fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/27d25f3c2003f1d875d6b621b3e107b9e29d66bf/pkg/util/hlc/hlc.go#L226)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This structure is a little unusual. Most CAS loops are implemented with all atomic accesses inside the loop like:
```
for {
    v := atomic.Load()
    if v ... some condition to check for concurrent changes {
        break
    }
    if atomic.CompareAndSwap(v) {
        break
    }
}
```
This reveals a bug / change in behavior here that I don't think was intentional - we're now relying on `physicalClock` to be monotonic in order for `getPhysicalClockAndCheck` to be monotonic because we don't compare `oldTime` and `newTime` on the first iteration. Since we're here, I'd recommend we switch around the structure here a bit.
</blockquote></details>

If I understand correctly - you are suggesting that we call `physicalClock` within the loop. This is slow when using the high precision clock and doing this exacerbates the contention under load. My first implementation of this code was a single `CompareAndSwap` and no loop. This eliminates the monotonicity problem at the expense of not capturing every last `lastPhysicalTime`

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48610)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @darinpp)

___
*[pkg/util/hlc/hlc.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48610#-M7JWr7H6mlTQFqWlc_E:-M7K2-Fa4Ve9JEyp_IbB:bdyoq5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/27d25f3c2003f1d875d6b621b3e107b9e29d66bf/pkg/util/hlc/hlc.go#L226)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

If I understand correctly - you are suggesting that we call `physicalClock` within the loop. This is slow when using the high precision clock and doing this exacerbates the contention under load. My first implementation of this code was a single `CompareAndSwap` and no loop. This eliminates the monotonicity problem at the expense of not capturing every last `lastPhysicalTime`
</blockquote></details>

No, I'm not saying we need to call `physicalClock` within the loop, just that we shouldn't have two separate calls to `atomic.LoadInt64(&c.lastPhysicalTime)`. We can still call `physicalClock` once. So to make the example from before more clear, something like:
```
new := physicalClock()
for {
    v := atomic.Load()
    if v >= new {
        break
    }
    if atomic.CompareAndSwap(v, new) {
        break
    }
}
```

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48610)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @darinpp and @nvanbenschoten)

___
*[pkg/util/hlc/hlc.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48610#-M7JWr7H6mlTQFqWlc_E:-M7K3jWI20_DPioAO-9z:b-kpsb9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/27d25f3c2003f1d875d6b621b3e107b9e29d66bf/pkg/util/hlc/hlc.go#L226)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No, I'm not saying we need to call `physicalClock` within the loop, just that we shouldn't have two separate calls to `atomic.LoadInt64(&c.lastPhysicalTime)`. We can still call `physicalClock` once. So to make the example from before more clear, something like:
```
new := physicalClock()
for {
    v := atomic.Load()
    if v >= new {
        break
    }
    if atomic.CompareAndSwap(v, new) {
        break
    }
}
```
</blockquote></details>

The thing is that the `checkPhysicalClock()` below needs a value from before `c.physicalClock()`, otherwise races will trigger spurious backwards jumps.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48610)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @darinpp)

___
*[pkg/util/hlc/hlc.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48610#-M7JWr7H6mlTQFqWlc_E:-M7OQ2Tv5H-U6Lj1iRnK:b3k6su7) ([raw file](https://github.com/cockroachdb/cockroach/blob/27d25f3c2003f1d875d6b621b3e107b9e29d66bf/pkg/util/hlc/hlc.go#L226)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

The thing is that the `checkPhysicalClock()` below needs a value from before `c.physicalClock()`, otherwise races will trigger spurious backwards jumps.
</blockquote></details>

Then what about:
```
var old, new int64
for {
    v := atomic.Load()
    if new == 0 {
        old = v
        new = physicalClock()
    }
    if v >= new {
        break
    }
    if atomic.CompareAndSwap(v, new) {
        break
    }
}
checkPhysicalClock()
```
We are sitting on a bug without this, right? We don't expect `lastPhysicalTime` to regress even if `physicalClock` does.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48610)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @darinpp and @nvanbenschoten)

___
*[pkg/util/hlc/hlc.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48610#-M7JWr7H6mlTQFqWlc_E:-M7clx4YAVIh6B_2hDLV:b-opd18u) ([raw file](https://github.com/cockroachdb/cockroach/blob/27d25f3c2003f1d875d6b621b3e107b9e29d66bf/pkg/util/hlc/hlc.go#L226)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Then what about:
```
var old, new int64
for {
    v := atomic.Load()
    if new == 0 {
        old = v
        new = physicalClock()
    }
    if v >= new {
        break
    }
    if atomic.CompareAndSwap(v, new) {
        break
    }
}
checkPhysicalClock()
```
We are sitting on a bug without this, right? We don't expect `lastPhysicalTime` to regress even if `physicalClock` does.


</blockquote></details>

I think we do want `lastPhysicalTime` to regress. If it doesn't, then `monotonicityErrorsCount` would be incremented over and over again for a `physicalClock` regression.
Note that `lastPhysicalTime` doesn't play a role in the HLC's monotonicity - that's `mu.timestamp`.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48610#-:-M8H6nDA3ibpWXaQfIrz:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @darinpp and @nvanbenschoten)

**Pull request merged**
