### PR TITLE
colexec: fix TestRouterOutputNext flake

### LINKED ISSUE #44120: sql/colexec: TestRouterOutputNext failed
[(sql/colexec).TestRouterOutputNext failed](https://viewLog.html?buildId=1697835&tab=buildLog) on [master@13af75f3d1376fff31d1419df2951c2d8a810efd](https://github.com/cockroachdb/cockroach/commits/13af75f3d1376fff31d1419df2951c2d8a810efd):

```
=== RUN   TestRouterOutputNext
--- FAIL: TestRouterOutputNext (0.01s)
=== RUN   TestRouterOutputNext/AddBatchDoesntBlockWhenOutputIsBlocked
    --- FAIL: TestRouterOutputNext/AddBatchDoesntBlockWhenOutputIsBlocked (0.00s)
        routers_test.go:283: unexpectedly still unblocked

```

<details><summary>Repro</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestRouterOutputNext PKG=./pkg/sql/colexec TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestRouterOutputNext.%2A&sort=title&restgroup=false&display=lastcommented+project)

<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by asubiotto**
TestRouterOutputNext/AddBatchDoesntBlockWhenOutputIsBlocked expects and input
of coldata.BatchSize to be split into at least two batches of smallBatchSize
(a constant used in the test). It was possible to generate a random value of
coldata.BatchSize == smallBatchSize, which would result in the test failing.

Release note: None (test fix)

Fix #44120

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
[nit]: in commit message `s/and input/an input/g`.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44362#-:-LzO61z7EUTnq79jtqfd:b-8xadb4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/routers_test.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44362#-LzO6Qz--2SL_aZWQKX_:-LzO6Qz--2SL_aZWQKXa:b17kb9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e88ba158866f940dc4c59a23bcd1a4467db439be/pkg/sql/colexec/routers_test.go#L252)):*
> ```Go
> 		// checked on the first run whereas the condition might not longer hold on
> 		// consequent runs. That's why we have this "data dependency" on the slice.
> 		if len(fullSelection) < blockThreshold {
> ```

I don't understand why this condition wasn't enough? It seems to me that the cases that the new code allows were previously skipped, no?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44362)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/routers_test.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44362#-LzO6Qz--2SL_aZWQKX_:-LzbNhqC2LaR1_GeCF3V:b-lyzy3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e88ba158866f940dc4c59a23bcd1a4467db439be/pkg/sql/colexec/routers_test.go#L252)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't understand why this condition wasn't enough? It seems to me that the cases that the new code allows were previously skipped, no?
</blockquote></details>

This condition isn't enough because the important part is that `fullSelection` needs to be greater than `smallBatchSize` (not `blockThreshold`). If not, the `opTestInput` returns only one batch. So you could get into cases where `len(fullSelection) = 8`, `smallBatchSize = 8`, `blockThreshold = 4`, which was valid according to this check, but only one batch of 8 was returned. This new check just updates all those cases where `len(fullSelection) <= 8` to be valid to run in this test.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44362#-:-Lzbz6L3-FNdYXnC5Pik:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/routers_test.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44362#-LzO6Qz--2SL_aZWQKX_:-LzbyR8lBXEID8PrLo5n:b-kufkx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e88ba158866f940dc4c59a23bcd1a4467db439be/pkg/sql/colexec/routers_test.go#L252)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This condition isn't enough because the important part is that `fullSelection` needs to be greater than `smallBatchSize` (not `blockThreshold`). If not, the `opTestInput` returns only one batch. So you could get into cases where `len(fullSelection) = 8`, `smallBatchSize = 8`, `blockThreshold = 4`, which was valid according to this check, but only one batch of 8 was returned. This new check just updates all those cases where `len(fullSelection) <= 8` to be valid to run in this test.
</blockquote></details>

I see, thanks.

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Pull request merged**
