### PR TITLE
opt: move interleaved fast delete logic to the optimizer

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: move delete fast path tests to logictests

Rewrite the interleaved fast path tests as logic/execbuilder tests, so that they
continue to work when the fast path is reimplemented in the optimizer.

Release note: None

#### opt: move interleaved fast delete logic to the optimizer

DeleteRange is used as a fast path for delete when it is safe to simply delete
an entire range of keys. There are two separate paths, depending if the table
has interleaved children. The non-interleaved path is implemented in the
optimizer, but the interleaved path is legacy code called from the exec factory.

This change moves the interleaved fast path to the optimizer. This is necessary
to allow use of the fast path when opt-driven cascades are enabled.

The conditions for using DeleteRange on an interleaving are quite strict - there
must be foreign key with ON DELETE cascade set up for all tables in the
interleaving.

The existing path did not check the columns of the foreign keys; in principle
we could set up foreign keys between the expected tables but on columns that
don't match the interleaving. This is not a problem in practice right now
because any of those cases would result in secondary indexes, which prevent the
fast path regardless. But this won't be the case once we relax the index
requirements, so the new path checks the columns as well.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-:-M7cMaRv23R4vI4yaqZu:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/delete, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-M7cC0jfCurxGA8Ih-_a:-M7cC0jfCurxGA8Ih-_b:b9eldaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0be7cca2ba29f7c81f8205a898e9250d8e9006/pkg/sql/logictest/testdata/logic_test/delete#L285)):*
> ```
> DELETE FROM family USING family, other_table WHERE x=2
> 
> # Verify that the fast path does its deletes at the expected timestamp.
> ```

Cool tests!
___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 527 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-M7cFpQgDYgpTzL_C4VL:-M7cFpQgDYgpTzL_C4VM:b643dnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/27def16ceccb42d0650672ec3d7ea3db40f944de/pkg/sql/opt/exec/execbuilder/mutation.go#L527)):*
> ```Go
> //
> // We can use DeleteRange only when foreign keys are set up such that a deletion
> // of a row cascades into deleting all interleaved rows with the same prefix:
> ```

[nit] I feel like this comment is missing something. Maybe it just needs a simple intro to the bullet points such as "the following conditions must apply:"
___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-M7cGosk3zOdWZzdWjCu:-M7cGosk3zOdWZzdWjCv:bn81n2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/27def16ceccb42d0650672ec3d7ea3db40f944de/pkg/sql/opt/exec/execbuilder/mutation.go#L557)):*
> ```Go
> 			// have any secondary indexes anyway.
> 			tableID, _ := currIdx.InterleavedBy(i)
> 			if _, ok := tables[tableID]; ok {
> ```

Do you have any tests where the same table would appear multiple times? If not, maybe this should be an assert?
___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 646 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-M7cJy6YBzrPtMd8Sad0:-M7cJy6YBzrPtMd8Sad1:bdkhjol) ([raw file](https://github.com/cockroachdb/cockroach/blob/27def16ceccb42d0650672ec3d7ea3db40f944de/pkg/sql/opt/exec/execbuilder/mutation.go#L646)):*
> ```Go
> 	// Note that we can ignore any FK checks or cascades w.r.t allowAutoCommit -
> 	// if we got this far, we already determined that the FKs match an
> 	// interleaving hierarchy and a delete range is sufficient.
> ```

This comment is kind of confusing -- it implies the decision to use delete range and auto commit are the same. I think what's more relevant is the fact that maxKeys=0 if there are any interleaved tables, which will ensure that auto commit is not used by the factory.
___
*[pkg/sql/opt/exec/execbuilder/testdata/delete, line 405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-M7cDDQb7W5aeWRWT9rn:-M7cDDQb7W5aeWRWT9ro:b-ctrrtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0be7cca2ba29f7c81f8205a898e9250d8e9006/pkg/sql/opt/exec/execbuilder/testdata/delete#L405)):*
> ```
> DROP TABLE child_without_cascade
> 
> statement ok
> ```

This looks like a duplicate

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-:-M7cduLM1dCRxfYm81Y2:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 527 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-M7cFpQgDYgpTzL_C4VL:-M7cahboDEzs8kezg-_u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27def16ceccb42d0650672ec3d7ea3db40f944de/pkg/sql/opt/exec/execbuilder/mutation.go#L527)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I feel like this comment is missing something. Maybe it just needs a simple intro to the bullet points such as "the following conditions must apply:"
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-M7cGosk3zOdWZzdWjCu:-M7card-0vtBwNCsHLbS:b-6q2lqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/27def16ceccb42d0650672ec3d7ea3db40f944de/pkg/sql/opt/exec/execbuilder/mutation.go#L557)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you have any tests where the same table would appear multiple times? If not, maybe this should be an assert?
</blockquote></details>

Since each table has a single interleave parent this should not be possible. I switched to an assertion error.
___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 646 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-M7cJy6YBzrPtMd8Sad0:-M7cbW8F2jWPytaTkzqp:b13ln4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/27def16ceccb42d0650672ec3d7ea3db40f944de/pkg/sql/opt/exec/execbuilder/mutation.go#L646)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This comment is kind of confusing -- it implies the decision to use delete range and auto commit are the same. I think what's more relevant is the fact that maxKeys=0 if there are any interleaved tables, which will ensure that auto commit is not used by the factory.
</blockquote></details>

Yeah.. The reason I wanted to comment here was that all other mutations use `b.allowAutoCommit && len(ins.Checks) == 0 && len(ins.FKCascades) == 0` and I wanted it to make it clear that this is not an omission. You're right that we won't autocommit anyway but that decision is in some other code and could in principle be changed. I rephrased a bit, let me know if this is better.
___
*[pkg/sql/opt/exec/execbuilder/testdata/delete, line 405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-M7cDDQb7W5aeWRWT9rn:-M7cdqz29RxgOowDaqyA:b-j8tput) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0be7cca2ba29f7c81f8205a898e9250d8e9006/pkg/sql/opt/exec/execbuilder/testdata/delete#L405)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This looks like a duplicate
</blockquote></details>

Good catch, I meant to remove the FK reference. Fixed.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-:-M7crVwy9lysXFRnEGKE:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 646 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-M7cJy6YBzrPtMd8Sad0:-M7cr5dD5fGLaZlXLMDe:byxnpsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/27def16ceccb42d0650672ec3d7ea3db40f944de/pkg/sql/opt/exec/execbuilder/mutation.go#L646)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah.. The reason I wanted to comment here was that all other mutations use `b.allowAutoCommit && len(ins.Checks) == 0 && len(ins.FKCascades) == 0` and I wanted it to make it clear that this is not an omission. You're right that we won't autocommit anyway but that decision is in some other code and could in principle be changed. I rephrased a bit, let me know if this is better.
</blockquote></details>

Yep, this makes more sense. Thanks!

**Review by RaduBerinde — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49163#-:-M7cyCwv5TbeJ2DolIac:b-voiyyw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

**Pull request merged**
