### PR TITLE
ttljob: plumb in admission priority for row level TTL

### PR DESCRIPTION
**Pull request by otan**
Use the TTL admission priority for SELECT and DELETE.

Release note: None

Release justification: low risk high benefit changes to new
functionality

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm! i wonder if there's a way to test it

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-:-MwlUzLHBDrrBcLvBkgw:bsyyts1)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @otan)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-MwlV_tS6-FKySCZHgVW:b-rp8x9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
> ```Go
> 		sessiondata.InternalExecutorOverride{
> 			User:             security.RootUserName(),
> 			QualityOfService: &qosLevel,
> ```

Passing the qosLevel here will have no effect when txn is non-nil.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-MwlcTpB92Dgyzg93Nts:bfqnc3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Passing the qosLevel here will have no effect when txn is non-nil.
</blockquote></details>

ah nice catch! in general, it seems like we've been hitting lots of unintuitive behavior when using a non-nil txn with the internal exec. (https://github.com/cockroachdb/cockroach/issues/76764 is another one)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-Mwlcku80dfLSOJTTVzT:b-2y1lva) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah nice catch! in general, it seems like we've been hitting lots of unintuitive behavior when using a non-nil txn with the internal exec. (https://github.com/cockroachdb/cockroach/issues/76764 is another one)
</blockquote></details>

maybe we should add a `SET TRANSACTION QUALITY OF SERVICE` command, similar to `SET TRANSACTION AS OF SYSTEM TIME`

or would `SET LOCAL quality_of_service` work to change it inside an explicit txn?

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-MwldlIr7u8y0Lu2Mdzd:b-87tkx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe we should add a `SET TRANSACTION QUALITY OF SERVICE` command, similar to `SET TRANSACTION AS OF SYSTEM TIME`

or would `SET LOCAL quality_of_service` work to change it inside an explicit txn?
</blockquote></details>

There is this issue which would cover it: https://github.com/cockroachdb/cockroach/issues/76624
Technically your wouldn't need to tie the external feature to this internal override. Each could be implemented separately.  It was my understanding that overriding QoS of a pre-existing txn isn't needed at this time.  If it's needed, here's where you'd add it:
https://github.com/cockroachdb/cockroach/blob/2a75254d37a9704adc6b34ec2133755bc9fd0119/pkg/sql/txn_state.go#L207-L212

**Comment by otan** [comment]
___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-MwmWAVj5VCedePo5jUE:bq8tj49) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
i just won't put a priority on the select; it was never needed in my prototype

> Passing the qosLevel here will have no effect when txn is non-nil.

if that's the case, setting qosLevel should error in the InternalExecutor.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @otan, and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-Mwmd7qZ6ai0sOltk5-w:bytce60) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i just won't put a priority on the select; it was never needed in my prototype

> Passing the qosLevel here will have no effect when txn is non-nil.

if that's the case, setting qosLevel should error in the InternalExecutor.
</blockquote></details>

The select isn't the problem, it's the delete.
In the code block I quoted above you could add something like:
`txn.admissionHeader.Priority = int32(qualityOfService)`
But this may need to be done in a function in `txn.go` because admissionHeader is not exported.



_Code quote:_
```Go
QualityOfService
```

**Comment by otan** [comment]
___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-MwmeTEU2DeeHL-FZU2e:b-axxupw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

The select isn't the problem, it's the delete.
In the code block I quoted above you could add something like:
`txn.admissionHeader.Priority = int32(qualityOfService)`
But this may need to be done in a function in `txn.go` because admissionHeader is not exported.
</blockquote></details>

oh, urgh! that's not intuitive

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @otan, and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwmgB9S4v9SDMxCkJon:-MwmgB9S4v9SDMxCkJoo:b-mdo3tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6be4b3566a77dea2c3d55636ee5d1d0702b78b7/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L206)):*
> ```Go
> 	// queryCache is the cached query, which stays the same as long as we are
> 	// deleting up to deleteBatchSize elements.
> 	queryCache string
> ```

unrelated nit: this sounds like it should be named `cachedQuery`

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @otan, and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-MwmgFR-8U-MjApCxRwy:b-4859nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

oh, urgh! that's not intuitive
</blockquote></details>

Sorry, I had previously asked this question, if passing a nil `txn` was fine, and you seemed to indicate it was.
https://app.slack.com/client/T03GD9U3D/C01SRKWGHG8/thread/C01SRKWGHG8-1643000425.006100

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @otan, and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-MwmgkTp8i_1UZWih8KZ:bxvx3ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Sorry, I had previously asked this question, if passing a nil `txn` was fine, and you seemed to indicate it was.
https://app.slack.com/client/T03GD9U3D/C01SRKWGHG8/thread/C01SRKWGHG8-1643000425.006100
</blockquote></details>

hm, well it's seeming more important now that we should be able to test that the quality_of_service is set as we want when the DELETE actually runs. do we have any way of doing that?

IMO i'd rather spend the time in stability period to implement #76624 rather than do the odd `txn.admissionHeader.Priority = int32(qualityOfService)` hack

or is there some way we can teach `db.Txn()` about quality of service?

**Comment by otan** [comment]
___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-MwmhraG1oMS6_3kSgvK:b73o22n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, well it's seeming more important now that we should be able to test that the quality_of_service is set as we want when the DELETE actually runs. do we have any way of doing that?

IMO i'd rather spend the time in stability period to implement #76624 rather than do the odd `txn.admissionHeader.Priority = int32(qualityOfService)` hack

or is there some way we can teach `db.Txn()` about quality of service?
</blockquote></details>

i've added a new method `TxnWithSteppingEnabled`

**Comment by otan** [comment]
___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-Mwmi9hdBb4JnBHXxi-L:b-14xmnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
> if passing a nil txn was fin

it was before i introduced this schema change checking thing :) i still find it a big gotcha that setting the override does nothing for a non-nil txn.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @otan, and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-Mwmi3BI8vuFOctA6E07:b-j0pfph) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

> if passing a nil txn was fin

it was before i introduced this schema change checking thing :) i still find it a big gotcha that setting the override does nothing for a non-nil txn.
</blockquote></details>

Is it a requirement that the delete use the pre-existing `txn`, or can you pass `nil` and let it create a new one?

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @otan, and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-MwmiZhd3Rb2hcyVhRUK:bpteyft) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Is it a requirement that the delete use the pre-existing `txn`, or can you pass `nil` and let it create a new one?
</blockquote></details>

@otan This is an override for the default_transaction_quality_of_service setting, which only takes effect when a new transaction is created.  The issue dealing with a pre-existing transaction is https://github.com/cockroachdb/cockroach/issues/76624.  It would not have been a good idea to introduce an override for a feature not yet implemented.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @otan, and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob_query_builder.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-MwlV_tS6-FKySCZHgVV:-MwmtS1q3vu1n0G8HTJb:bttbw23) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9991c972e7a6d644fc8efb93ec8af428d006019/pkg/sql/ttl/ttljob/ttljob_query_builder.go#L284)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

@otan This is an override for the default_transaction_quality_of_service setting, which only takes effect when a new transaction is created.  The issue dealing with a pre-existing transaction is https://github.com/cockroachdb/cockroach/issues/76624.  It would not have been a good idea to introduce an override for a feature not yet implemented.  
</blockquote></details>

would like to use the same one as we use the txn to check the schema is the same (and if we use different ones it doesnt auto retry the txn and might delete using an older version of the query on a new schema)

**Review by rafiss — APPROVED** [review]
lgtm, though still am curious about if there is any option for testing

> Reviewed 1 of 2 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76966#-:-Mx6h2fP0J68ubcvBZmj:b-p4s7zo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @otan)

**Comment by otan** [comment]
[i asked a while back](https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1643000487006900) and there is no clear way of doing so atm :( 

bors r=rafiss

**Comment by otan** [comment]
bors r-

merge conflict sigh

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
