### PR TITLE
storage:pretty print value for consistency diffs

### PR DESCRIPTION
**Pull request by a6802739**
@tschottdorf, please see #9554  and let me know if I have done it right.

If it's okay, I will add some test and remove tryX function in cli/debug.go.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10081)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Sorry for the late review, @songhao. I added some comments - there's more work to do here.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_command.go, line 2169 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-KVSJnBGzyW9PS5W4Xoi:-KVSJnBGzyW9PS5W4Xoj:bz7zdg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/876600780839704054b90a52899632c0be794e79/pkg/storage/replica_command.go#L2169)):*
> ```Go
> %s  raw_key:%x raw_value:%x
> `
> 		// TODO(tschottdorf): add pretty-printed value. We have the code in
> ```

TODO should be addressed in this PR.

---

*[pkg/storage/engine/mvcc.go, line 162 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-KVSKY5hl7RSJKkTEtpp:-KVSKY5hl7RSJKkTEtpq:b-v8ctpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/876600780839704054b90a52899632c0be794e79/pkg/storage/engine/mvcc.go#L162)):*
> ```Go
> func (m *MVCCKeyValue) PrettyPrintValue() string {
> 	prettys := []func() (string, error){
> 		m.prettyPrintRaftLogEntry,
> ```

This logic is too simple. Consider a key which has an empty value - you will be able to unmarshal it into any proto. You can't decide from the value what proto type it belongs to, that's why I suggested making this a kv-pretty printer - the key must decide (at least to some extent) what the value is. For example, if it's a key that looks like a `TransactionKey`, the value would have to be unmarshaled into a `&roachpb.Transaction{}`. That suggests that you should weave this logic into `keys/printer.go` so that for a kv pair, you pretty-print the key which gives you not only a string, but also a value to unmarshal into.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-:-KVSLP7bfMjKBwOWcoHb:b-ej7q3f)*

**Comment by a6802739** [comment]
@tschottdorf, I have move all the code to `keys/printer` now, please help me see if it's in a right direction.

I will then modify the test in `printer_test.go` and remove the code in `cli/debug.go`.

**Comment by tamird** [comment]
@a6802739 this commit doesn't compile, so it's pretty hard to review. For example, I don't understand how you plan to integrate the pretty printer (which now takes two arguments) into `roachpb.Key.String()`. Please ping this PR when you have a proposal that compiles; otherwise this is quite hard to review.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-:-KW8iHgoZDSlOToG7YcH:b-arhwfl)*

**Comment by a6802739** [comment]
@tamird, got it. 

thanks for your review.

`roachpb.Key.String()` invoke `PrettyPrintKey` which will be `NULL` now, because I add a new func `PrettyPrintKeyValue func(key Key, value []byte) (string, string)` will assign to `PrettyPrint` in `keys/printer.go`, So it's my mistake.

**Comment by a6802739** [comment]
@tamird, I can run command `make build` in my local environment. I'm not quite sure what I have done  
satisfy the issue in  #9554.

I still need to  modify the test in printer_test.go and remove the code in cli/debug.go. But I want to  know what I have done in `keys/printer.go` is all right.

cc @tschottdorf .

**Comment by tamird** [comment]
`make build` works because the failure will come at runtime. Please confirm that `make test` passes locally.

**Comment by a6802739** [comment]
@tamird, thanks a lot. I will first pass all the tests.

**Comment by a6802739** [comment]
@tamird , what do you think now, I haven't remove the code in `cli/debug.go`.

**Comment by tamird** [comment]
Sorry for the long delay here. @a6802739 could you rebase? I'll take a look then.

**Comment by a6802739** [comment]
@tamird, I have rebased it now. Please have a look then.

**Comment by tamird** [comment]
Could you add some tests for this new stuff? Generally looking good, and ready for the code in cli to be removed.

---

Reviewed 7 of 8 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/keys/printer.go, line 191 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-KZ8sqvhlUvUHqbXfBdb:-KZ8sqvhlUvUHqbXfBdc:b-4j421m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b7456dd316318124e873501a368b302fc5988/pkg/keys/printer.go#L191)):*
> ```Go
> }
> 
> func localStoreKeyPrint(key roachpb.Key, valueBytes []byte) (string, string) {
> ```

did you want to rename all these functions?

---

*[pkg/keys/printer.go, line 199 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-KZ8suodjMIYDJw2nqhI:-KZ8suodjMIYDJw2nqhJ:b-l8kqmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b7456dd316318124e873501a368b302fc5988/pkg/keys/printer.go#L199)):*
> ```Go
> 	}
> 
> 	return fmt.Sprintf("%q", []byte(key)), fmt.Sprintf("%q", valueBytes)
> ```

this should probably be `%x` (and everywhere else)

---

*[pkg/keys/printer.go, line 463 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-KZ8tU56dGgXWqjc9kfq:-KZ8tU56dGgXWqjc9kfr:b-nr6223) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b7456dd316318124e873501a368b302fc5988/pkg/keys/printer.go#L463)):*
> ```Go
> // if the key don't march any prefix in keyDict, return its byte value with quotation and false,
> // or else return its human readable value and true.
> func prettyPrintInternal(key roachpb.Key, valueBytes []byte) (bool, string, string) {
> ```

why move the bool to the front?

---

*[pkg/keys/printer_test.go, line 35 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-KZ8s-ggRVJNm19FMT20:-KZ8s-ggRVJNm19FMT21:b-tnt89i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b7456dd316318124e873501a368b302fc5988/pkg/keys/printer_test.go#L35)):*
> ```Go
> 
> func TestPrettyPrintKeyOnly(t *testing.T) {
> ```

remove this while here

---

*[pkg/storage/replica_command.go, line 2169 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-KVSJnBGzyW9PS5W4Xoi:-KW8gZrQe90TlkrzWs7p:b-yiirh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/876600780839704054b90a52899632c0be794e79/pkg/storage/replica_command.go#L2169)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

TODO should be addressed in this PR.
</blockquote></details>

@a6802739 remove this TODO?

---

*[pkg/storage/replica_test.go, line 6089 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-KZ8sTVngCv426pHdmu_:-KZ8sTVngCv426pHdmua:b28xck4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b7456dd316318124e873501a368b302fc5988/pkg/storage/replica_test.go#L6089)):*
> ```Go
> -  ts:1970-01-01 00:00:00.000001729 +0000 UTC
> -  value:"foo"
> -  raw_key:"a" raw_value:22666f6f22
> ```

why did these change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10081#-:-KZ8tO97sBeyzlNCDpga:b-rvje3g)*

**Comment by tamird** [comment]
@a6802739 do you plan to address the remaining comments?

**Comment by a6802739** [comment]
@tamird, I almost forgot this. Yes, I will try to fix the remaining comments.

**Comment by irfansharif** [comment]
ping.

**Pull request closed without merging**
