### PR TITLE
sql: ensure that the plan is closed in apply joins in some error cases

### LINKED ISSUE #82705: release-22.1: roachtest/sqlsmith: leftover bytes on the txn cleanup
roachtest.sqlsmith/setup=empty/setting=no-ddl [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5431532&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5431532&tab=artifacts#/sqlsmith/setup=empty/setting=no-ddl) on release-22.1 @ [e73379784b9f8921d116dc1ad0d2fd8a6256ff9f](https://github.com/cockroachdb/cockroach/commits/e73379784b9f8921d116dc1ad0d2fd8a6256ff9f):

```
					JOIN (VALUES ('14:54:42.42701':::TIME)) AS tab_130099 (col_218773) ON
							(tab_130098.col_218772) = (tab_130099.col_218773)
					FULL JOIN (VALUES (tab_130094.col_218765)) AS tab_130100 (col_218774) ON NULL
				WHERE
					NULL
				GROUP BY
					tab_130098.col_218772, tab_130100.col_218774
				ORDER BY
					tab_130098.col_218772 ASC, tab_130098.col_218772 DESC, tab_130098.col_218772 DESC
				LIMIT
					1:::INT8
			)
				AS col_218776
		FROM
			(
				VALUES
					('-20 years -4 mons -960 days -17:43:54.228946':::INTERVAL, NULL),
					(
						'21 years 10 mons 899 days 17:53:39.838878':::INTERVAL,
						(
							SELECT
								e'{";z>gyrXH``$": {}, "X,!6@?[,H": null, "b": "\\"7i?^K[JB>o", "foobar": "b"}':::JSONB
									AS col_218764
							FROM
								(
									VALUES
										(0:::INT8),
										(1809420385:::INT8),
										((-531379822):::INT8),
										(1887639644:::INT8),
										((-1):::INT8),
										(1671078266:::INT8)
								)
									AS tab_130093 (col_218763)
							LIMIT
								1:::INT8
						)
					),
					('1 day':::INTERVAL, '[{"-biIz<Ge|Wnf": [null], "baz": true}, null, true]':::JSONB),
					('-58 years -7 mons -835 days -13:46:16.380848':::INTERVAL, NULL),
					(
						'-60 years -6 mons -921 days -13:36:39.76583':::INTERVAL,
						'[{"OD}_yC": {}, "bar": {"Zkm3=(b~": {}, "a": {}}}, null, [], {}, [], [], []]':::JSONB
					)
			)
				AS tab_130094 (col_218765, col_218766)
		WHERE
			true
		LIMIT
			95:::INT8;
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=empty/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16619

### LINKED ISSUE #83368: roachtest/sqlsmith: leftover bytes on the txn cleanup
roachtest.sqlsmith/setup=empty/setting=no-mutations [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5558662?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5558662?buildTab=artifacts#/sqlsmith/setup=empty/setting=no-mutations) on master @ [fc7ae339c3f85ad2a2b28643e47d7c20768fe237](https://github.com/cockroachdb/cockroach/commits/fc7ae339c3f85ad2a2b28643e47d7c20768fe237):

```
							VALUES
								(
									'01030000400100000006000000604DBD5DDC12EE41E7F92AFA7236F5C1C806EE05E20FF8C1AE0EC58E089AF041037B428FCC74F4C1105BADD850C1FC41407E0CD5F406FC416C6E81576649F5C1A88849CFCCB2E7413DF8A105E4DBF9C1C05FB16532DADCC15BB2F12004BA00C2E0F5EDCFFDD8F5C114735FD70C27E2C188A7663531A5E0C1604DBD5DDC12EE41E7F92AFA7236F5C1C806EE05E20FF8C1':::GEOMETRY
								),
								(
									st_translate('010700000000000000':::GEOMETRY::GEOMETRY, atan2d(cosh((-1.7130878673648953):::FLOAT8::FLOAT8)::FLOAT8::FLOAT8, (-0.004513979274377716):::FLOAT8::FLOAT8)::FLOAT8::FLOAT8, 0.4371603268852574:::FLOAT8::FLOAT8, (-0.29366208391016146):::FLOAT8::FLOAT8)::GEOMETRY
								)
						)
							AS tab_397811 (col_664945) ON (tab_397806.col_664940) = (tab_397811.col_664945)
					JOIN (
							VALUES
								(
									(
										SELECT
											'01050000C00400000001020000C0040000007063C043D22ACCC130475EEF7C9A02C2677C6220BBBDFFC15E2E2C26A469FA4120F86F4F89ABC0C1E08590241BA1D4C1A8EDC2F1F8C9E74190057ADAEDAEC64110151420690CEC41A6C78051B8C3F94120D69F6ABE2602427497785A4931FA4120CE91C58CC0B0C1B84611CDD8B3FB41E42E4977FB240042A6B0F5B66E8DFBC101020000C002000000F5A865364AB200C208A688717882F2C1B87223099D2BFB41C09E5CF2DFA5E1417BD088CF2542F8C1CC4FEEB43088D9C17E50B17E6F59FFC1B49D7CD4D69CD9C101020000C003000000D15AF2CD722201C2AEA731D9250A00C20635FE345101F341F85C8EFC1A00FC4140B3D5A9A618B5C12A1D69C7B35EF8C1D2D0E5A7628402C2DCB40488CA8EE6C1C802F209EA63EC418F52817AF609F1C1BC3EC2D384BDFF41C72E42149FA8F4C101020000C0030000003C98FA504EDEE64112CFCDC0ADD9EFC14D43A09C231400C288DF1A5F3D02D3C1B83E0EA09845E641E41438A0AA9AE8C1267F0E438B69F941747EF1AF2E22D8C1E8B9F02AC250E64138744AF60587DE4114E20CDAC0C0FE418E29AA0DD9FD0042':::GEOMETRY
												AS col_664947
										FROM
											(
												VALUES
													('1992-07-21 10:54:10.000045+00:00':::TIMESTAMPTZ),
													(follower_read_timestamp()::TIMESTAMPTZ),
													('2001-05-14 09:39:42.000775+00:00':::TIMESTAMPTZ)
											)
												AS tab_397812 (col_664946)
										WHERE
											false
										LIMIT
											1:::INT8
									),
									NULL
								),
								(
									'0107000080040000000104000080080000000101000080605B6191C57AF3C1A0DFB38236B6BEC15473AF9C01E0FE410101000080740EA6F60382ED41E6C6DEFABE4DF7418086DF8B1DECC6C101010000803E64A168DCF8FAC1C87E769DF1D4DB4164512A3F9F710042010100008040117F9FE38FEAC1C2BBBD1FE74501426558BB08489BFAC101010000800E71C5887A47F5C15202BACB9992F9C1CF8218433AC1F0C101010000805CAD8471CFA8E2412B8D2279A109FFC112D7662D62F4FFC1010100008060FDA1D79E3AC741407DF3BA242DF941A8653F3B8DA9D4410101000080BAC29E606BBFE4C1A3467126B213F3C1DCEFA1880198F941010500008001000000010200008003000000F8F4EC911DFAF141C4451C8E1630E1C1425F59A992FCF9419E7A3FE71CAEF7410859BF4B7C87DD4100C0E4E502058041D807F148C8AADB41805BAF98FD04B5C1FE7F5800DE5FE5C1010500008007000000010200008009000000A2781438D268F4C1E0921FCDE949C6C1E06C2B922C7BFE4198C500B2D347D3413DBA6DA3A5F601C2614249D6DC0702C238C0E1AE41CCE841B068E94859F6CDC1206AB2A826B1FF41E06B40E86DE1EF4112E41A6C0D43E6C160C965460320C241AEC512CCE0980042609E92CA4D64DCC178ABE67EBD71EE41C4BAFF3D2499FD4120A1D7E18515B941A01978079661E641FA3CF59BD4390042C87C534DEED0E041892894EF3D04FEC1724B13C79D1D00424237E4908DC30042D0C9FF08602101424042D207B49BC54184A08865D90FFD41ECE6CDBE2315E7410102000080020000009471A0BF8363E8C1401D6A93EBA8C641F2EB3EF9F39D01C25CC73BBDC00C01C2806076F8E169D7C1E0DC6C2485B4CAC1010200008002000000DF9C498D09AAF4C1005815A1AFFFCA4184904B4DC07CEA41F856F535C117E441A82C4AFF6978D8418ACF00688509E2C1010200008002000000D698F2EF8CF9F141F2D214A5D1C0FEC190A7C80B15F3DAC156331475E442F541CED733343C19F4C100688D4F26B57341010200008004000000B207A21341FAF441E0D5F204C025DDC1F0AF9E0A8C17C0C1B2FCFE099CB301420893C99E1FF1F841EC4494F628D6FE415C95F6AEEE48ED41080D726358FBFA410E50F0E7F0E0F241402A8CE46DBFB04164370E47688802420A6BE5598432F741010200008004000000D029A3EF0EE9D1418C9B3F14F96DE1C130B7E1F872CFF54177A1A4271F8CFEC131ACCCE5C9A800C244A3C0DC35F4E241C0B0D29DF72FBB4106F87564FB28EAC18898FCE4D7B9ED41507102ADAE8CD6C1677DBD28F941FCC1A09665B5277EB0C10102000080020000005AADCEDA8044E4C1B225E5FC1458F141B062BDCA7237E741EC84C85A8238EAC1E604BE0C2B9BF041D84AC0574F20EF41010200008006000000C450FF663AC1D9C186A9424E746002C266DAFBD7F06FF8C110BDE4789E5DE44108D1C40BA124FAC1B0E5943A2B6EC6412081860B0CABE641C88916960F37EF4140A39C602A2DF8C154FA7FCDF7A2F041CA3A7D7AE40CF541C4FCFB0C19ACFCC1A8B7C553E19EDA41A0DC990E2510F94143319994DD8D00C26C73C2FAB51EEBC1DEEBB0C6708301424000086D7DF3F5C1':::GEOMETRY,
									NULL
								),
								(
									'0105000080030000000102000080020000005815AB9CA02EFD418A62B4D90D47FA411C81B0625EEDEA41B4A3F2F01CDEFAC1B28DADD0E1DF01421828B463FE52D6C101020000800300000090BA7156E31FCBC138ED53761B8EEB41B69D1E893034F341C887135538B9D0C11C215672AA65E941CC5E7459EE4FF7C1CE07DAA9DCD0ECC134C355C3C207ED4178A281C13FECD3410102000080030000001A4894B4A2AAEEC1BE1C45840D15FEC170113FBD1CB0E3414E7477CF58ADF841FA9631702A7BF7C1C06DD44EA605B1C154FAF1F87849FC41147370821DCCEA41942E895E2E45EAC1':::GEOMETRY,
									ARRAY[2834432470:::OID,1285215016:::OID,2816797228:::OID]
								)
						)
							AS tab_397813 (col_664948, col_664949) ON (tab_397806.col_664940) = (tab_397813.col_664948)
				ORDER BY
					tab_397813.col_664949 ASC
				LIMIT
					25:::INT8
			)
		GROUP BY
			cte_ref_33032.col_664924
		LIMIT
			51:::INT8;
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=empty/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-17026

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, it was possible for the apply join's plan to be left
unclosed when an error is encountered during the physical planning of
the main query, and this has now been fixed. We do so by explicitly
closing the plan in such a scenario.

Fixes: #82705.
Fixes: #83368.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I feel like this is an edge case, so it's not worth the risk of backporting to 22.1 or prior, thus I didn't add a backport label.

**Review by msirek — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83559)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/distsql_running.go` line 1455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83559#-N5gziXA0dJjC_D8ln8h:-N5gziXA0dJjC_D8ln8i:bmnqhgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd7682653ada030dec81624f3dba7cdc91c8d1b6/pkg/sql/distsql_running.go#L1455)):*
> ```Go
> 			// planning error. Usually, this is done in runCleanup() below, but
> 			// we won't get to that point, so we have to do so here.
> 			planCtx.planner.curPlan.close(ctx)
> ```

I like the safeguard to always make sure the plan is closed. If there is no impact by having an extra call to `close`, to make sure there are no more cases where we're not closing the plan (wherever createPhysPlan is called, now or in the future), maybe we should add this as one of the functions called by `physPlanCleanup` (append it to `planCtx.onFlowCleanup`).  What do you think?



_Code quote:_
```Go
dsp.createPhysPlan(ctx, planCtx, plan)
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83559)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @msirek)

___
*[`pkg/sql/distsql_running.go` line 1455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83559#-N5gziXA0dJjC_D8ln8h:-N5hFTJjEJUI7jm4cVoo:b-8zto3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd7682653ada030dec81624f3dba7cdc91c8d1b6/pkg/sql/distsql_running.go#L1455)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I like the safeguard to always make sure the plan is closed. If there is no impact by having an extra call to `close`, to make sure there are no more cases where we're not closing the plan (wherever createPhysPlan is called, now or in the future), maybe we should add this as one of the functions called by `physPlanCleanup` (append it to `planCtx.onFlowCleanup`).  What do you think?
</blockquote></details>

Hm, this "just to be safe" closing in the apply join case led to correctness issues (probably because we were closing some `planNode`s too early - they might be reused between different runs of the apply join or something like that), so I ended up reverting the change partially.

What you're suggesting on the surface seems like a good change, but this whole infrastructure is extremely fragile (as the CI failure on `subquery_correlated` file showed), so I'm afraid of introducing more "safeguards"  by closing the plan explicitly elsewhere.

In this particular code path, we know for sure that `PlanAndRun` is expected to return a closure that will close the AST, so the change here seems reasonable according to the contract. I'm leaning on the side of caution, i.e. modifying the least amount of code while fixing the issue. I'm also keeping my fingers crossed that CI will be happy now.

Thoughts?

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83559)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/distsql_running.go` line 1455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83559#-N5gziXA0dJjC_D8ln8h:-N5hHITFE6QKgHlVoMVF:bjb0k3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd7682653ada030dec81624f3dba7cdc91c8d1b6/pkg/sql/distsql_running.go#L1455)):*
> this "just to be safe" closing in the apply join case led to correctness issues

So this was a useful experiment at least. Could it be that `planCtx.planner.curPlan` refers to the top-level plan, but what we wanted to close here was just `plan`, which does seem to be rebuilt for each left row:
https://github.com/cockroachdb/cockroach/blob/9e4364a78bc8a1943902fd6f1a95e09835f53f44/pkg/sql/apply_join.go#L214-L220

I don't see a call to `close` for this locally built plan.  Do you know if it's done elsewhere in the non-error case?  If there is none, perhaps modifying your safeguard code to close this one instead would be useful.  For the error case, I guess we'd want to make sure the top-level plan is closed, but not in the non-error case.  Please correct me if my understanding is not accurate.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83559)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @msirek)

___
*[`pkg/sql/distsql_running.go` line 1455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83559#-N5gziXA0dJjC_D8ln8h:-N5hQRQwAK6qJbMnD2Mf:b1xc4z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd7682653ada030dec81624f3dba7cdc91c8d1b6/pkg/sql/distsql_running.go#L1455)):*
> which does seem to be rebuilt for each left row

I think it is possible that `planRightSideFn` internally is reusing some of the `planNode`s, so although the plan is rebuilt for every left row, parts of different plans might be shared. I'm not sure whether it's true though.

> Do you know if it's done elsewhere in the non-error case?

Yeah, this is done automatically as part of `runCleanup` call in the closure returned by `Run` below (which will be called right away, after the execution finished, in case of the apply join). If we had forgotten to close the plan in the non-error case with the apply join, we'd have seen these "leftover bytes" errors constantly.

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83559#-:-N5i8VpAEq82NaL67gsv:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[`pkg/sql/distsql_running.go` line 1455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83559#-N5gziXA0dJjC_D8ln8h:-N5i8G1j1Iu6dlNlZbZb:bmxyqkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd7682653ada030dec81624f3dba7cdc91c8d1b6/pkg/sql/distsql_running.go#L1455)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> which does seem to be rebuilt for each left row

I think it is possible that `planRightSideFn` internally is reusing some of the `planNode`s, so although the plan is rebuilt for every left row, parts of different plans might be shared. I'm not sure whether it's true though.

> Do you know if it's done elsewhere in the non-error case?

Yeah, this is done automatically as part of `runCleanup` call in the closure returned by `Run` below (which will be called right away, after the execution finished, in case of the apply join). If we had forgotten to close the plan in the non-error case with the apply join, we'd have seen these "leftover bytes" errors constantly.
</blockquote></details>

OK, thanks for the explanation.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
