### PR TITLE
pkg/server/structlogging: support hot ranges stats with diagnostic reporting disabled

### LINKED ISSUE #122977: `diagnostics.reporting.enabled` cluster setting is required to enable `server.telemetry.hot_ranges_stats.enabled`.
Customer cannot enable hot ranges stats in their logs without also enabling diagnostic reporting. These options should be independent since diagnostic reporting could be something the customer wants to enable independently of hot ranges stats.

Jira issue: CRDB-38152

### PR DESCRIPTION
**Pull request by kyle-a-wong**
Previously, enable hot ranges stats also required the enabling of diagnostic reporting. Hot ranges stats doesn't need to be dependent on diagnostic reporting and someone might want to enable hot ranges stats without enabling diagnostic reporting.

Now, server.telemetry.hot_ranges_stats.enabled can be set to true while without setting diagnostics.reporting.enabled

Epic: none
Fixes: #122977
Part of: https://cockroachlabs.atlassian.net/browse/CRDB-38152

Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124425)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @kyle-a-wong, and @xinhaoz)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124425#-NyMA75KAOWr_WX-T2hN):*
nit: just `structlogging` is fine here. this line is probably too long also.
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124425#-NyMADzv9U58HYJiLN2T):*
nit: grammar "while without"
___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124425#-NyMAKu-BVh43PfhjBmx):*
nit: no need to repeat the ticket that 122977 is already linked to. They're identical and once the github ticket is closed, the Jira ticket will get closed automatically.
___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124425#-NyMAFYJ2563jPg-GsuN):*
This change should have a release note explaining the modified behavior.

**Review by kyle-a-wong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124425)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @xinhaoz)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124425#-NyMAFYJ2563jPg-GsuN):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This change should have a release note explaining the modified behavior.
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124425#-:-NyQ_0w9COO0VSfx71SQ:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

**Pull request merged**
