### PR TITLE
stats: add support for most common values in histograms

### LINKED ISSUE #71828: opt: collect heavy hitters in table statistics
When the optimizer calculates the selectivity of an equality filter (e.g. `a = 1`) with a value that is contained in the range of a histogram bucket, it assumes that the values in the histogram bucket are evenly distributed. For example, given these histogram buckets for the column `c UUID`:

```
{
    "distinct_range": 10_000,
    "num_eq": 5000,
    "num_range": 1_000_000,
    "upper_bound": "10000000-0000-0000-0000-000000000000"
},
{
    "distinct_range": 10_000,
    "num_eq": 5000,
    "num_range": 1_000_000,
    "upper_bound": "20000000-0000-0000-0000-000000000000"
},
```

The optimizer would calculate the selectivity of the filter `c = '15000000-0000-0000-0000-000000000000'` to be `1,000,000 / 10,000 = 100` rows.

If the distribution of values within buckets is very uneven, then we can vastly underestimate row counts. For example, imagine that within the second bucket above, there are actually 300,000 rows with a value of `'15000000-0000-0000-0000-000000000000'`, and the other 700,000 rows are evenly distributed among the 9999 other distinct values in the bucket - our estimate of 100 rows is off by 3000x. This has come up a few times recently in real-world deployments.

We should collect heavy hitters. We could either:

1. Store heavy hitter separately from the histogram and somehow incorporate them during statistics building.
2. Use the heavy hitters as `upper_bound` values in histograms. The corresponding `num_eq` will be a more accurate estimate of the cardinality of heavy hitters.

Epic: CRDB-34173

Jira issue: CRDB-10787

### PR DESCRIPTION
**Pull request by rytaft**
Fixes https://github.com/cockroachdb/cockroach/issues/71828

Release note (sql change): Added a new cluster setting to control
whether most common values are collected as part of histogram collection
for use by the optimizer. The setting is called
`sql.stats.histogram_buckets.include_most_common_values.enabled`. When enabled,
the histogram collection logic will ensure that the most common sampled values
are represented as histogram bucket upper bounds. Since histograms in
CockroachDB track the number of elements equal to the upper bound in addition
to the number of elements less, this allows the optimizer to identify the most
common values in the histogram and better estimate the rows processed by a
query plan. To set the number of most common values to include in a histogram,
a second setting `sql.stats.histogram_buckets.max_fraction_most_common_values`
was added. Currently, the default is 0.1, or 10% of the number of buckets. So
with a 200 bucket histogram, by default, at most 20 buckets may be adjusted to
include a most common value (or "heavy hitter") as the upper bound.

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Really nice and simple! Looks great!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-:-O5-W6TW88XWDliQDJ0v:b-16rs09)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)

___
*[`pkg/sql/stats/histogram.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-O5-Vv4391mARS2MLvM5:-O5-Vv4391mARS2MLvM6:brvk40u) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f097f6efbc28d31a4aad4ed3af83d060d2f6e5/pkg/sql/stats/histogram.go#L70)):*
> ```Go
> 	settings.ApplicationLevel,
> 	"sql.stats.histogram_buckets.max_most_common_values",
> 	"maximum number of most common values to include as histogram buckets",
> ```

I wonder if this would make more sense as a proportion (defaulting to 0.1) than as an absolute number?
___
*[`pkg/sql/stats/histogram.go` line 841 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-O5-OJ841XFRhNj9qIiR:-O5-OJ841XFRhNj9qIiS:b-7g1cma) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f097f6efbc28d31a4aad4ed3af83d060d2f6e5/pkg/sql/stats/histogram.go#L841)):*
> ```Go
> 	}
> 	// Add the last value.
> 	heap.Push[MCV](&h, MCV{
> ```

Not sure how much it matters, but I think if `len(samples) == 0` this is incorrect.
___
*[`pkg/sql/stats/most_common_values.go` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-O5-Q3B_ARDiAvR7q1Fy:-O5-Q3Ba9xQXTkY_fr2y:bnslp8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f097f6efbc28d31a4aad4ed3af83d060d2f6e5/pkg/sql/stats/most_common_values.go#L13)):*
> ```Go
> package stats
> 
> // MCV contains an index into a slice of samples, and the count of values equal
> ```

bikeshedding: maybe clarify that it's a count of samples and not a count of rows represented by the samples?

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-:-O5-dp9kDUpuwW65ssuZ:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @mgartner, and @michae2)

___
*[`pkg/sql/stats/histogram.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-O5-Vv4391mARS2MLvM5:-O5-b3G0A3upWg8xzpb2:bnk51jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f097f6efbc28d31a4aad4ed3af83d060d2f6e5/pkg/sql/stats/histogram.go#L70)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I wonder if this would make more sense as a proportion (defaulting to 0.1) than as an absolute number?
</blockquote></details>

I could see it going both ways... but I feel like it's a bit clearer as an absolute count. This way the number of MCVs collected is also independent from the number of buckets, which I think is a good thing.

In general I'm hoping people won't touch this setting at all. I was thinking about making it private (essentially only for testing purposes), but decided in the end to make it public since it was easier to explain what `sql.stats.histogram_buckets.include_most_common_values` meant when I could refer to `sql.stats.histogram_buckets.max_most_common_values`. 

What do you think?
___
*[`pkg/sql/stats/histogram.go` line 841 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-O5-OJ841XFRhNj9qIiR:-O5-dH-2-IpiXT0JJZG0:buqrazf) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f097f6efbc28d31a4aad4ed3af83d060d2f6e5/pkg/sql/stats/histogram.go#L841)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Not sure how much it matters, but I think if `len(samples) == 0` this is incorrect.
</blockquote></details>

Added an assertion failure at the top
___
*[`pkg/sql/stats/most_common_values.go` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-O5-Q3B_ARDiAvR7q1Fy:-O5-de8_AlyTY4UMWsJG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f097f6efbc28d31a4aad4ed3af83d060d2f6e5/pkg/sql/stats/most_common_values.go#L13)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

bikeshedding: maybe clarify that it's a count of samples and not a count of rows represented by the samples?
</blockquote></details>

Done.

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-:-O50-o5L-vWOt33icwgc:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)

___
*[`pkg/sql/stats/histogram.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-O5-Vv4391mARS2MLvM5:-O50-pFv8hNHRgsKKo_S:bdmrjhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f097f6efbc28d31a4aad4ed3af83d060d2f6e5/pkg/sql/stats/histogram.go#L70)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I could see it going both ways... but I feel like it's a bit clearer as an absolute count. This way the number of MCVs collected is also independent from the number of buckets, which I think is a good thing.

In general I'm hoping people won't touch this setting at all. I was thinking about making it private (essentially only for testing purposes), but decided in the end to make it public since it was easier to explain what `sql.stats.histogram_buckets.include_most_common_values` meant when I could refer to `sql.stats.histogram_buckets.max_most_common_values`. 

What do you think?
</blockquote></details>

I don't feel too strongly, I think what you have is fine and would work well. Up to you.

The best argument I can come up with for a proportion is: if someone does need to adjust it, a proportion might work better for a mix of table sizes where we're already setting sample count and bucket count differently for different tables.

(But if MCV count were also a per-table setting, that would also handle a mix of table sizes.)

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129378)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @mgartner, and @michae2)

___
*[`pkg/sql/stats/histogram.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-O5-Vv4391mARS2MLvM5:-O50uL0Q8CAnwl6mSP1t:bryb2qn) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f097f6efbc28d31a4aad4ed3af83d060d2f6e5/pkg/sql/stats/histogram.go#L70)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I don't feel too strongly, I think what you have is fine and would work well. Up to you.

The best argument I can come up with for a proportion is: if someone does need to adjust it, a proportion might work better for a mix of table sizes where we're already setting sample count and bucket count differently for different tables.

(But if MCV count were also a per-table setting, that would also handle a mix of table sizes.)
</blockquote></details>

I think I was resisting this because I thought we might use a different formula at some point (similar to Postgres) to dynamically determine the number of MCVs, but realistically I don't see that happening any time soon.

And I don't really have any other good argument for keeping this as an absolute count. You make a good point about different table sizes, and I don't think it's worth adding this as a table-level setting yet. 

Anyway, I went ahead and made the change. Thanks!

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129378#-:-O5Erw7T704zdt092OJQ:b-ydi9ay)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @mgartner, and @michae2)

**Pull request merged**
