### PR TITLE
stop: annotate tasks with `trace.Region`

### PR DESCRIPTION
**Pull request by tbg**
From the docs[^1]:

> A region is for logging a time interval during a goroutine's
> execution. By definition, a region starts and ends in the same
> goroutine. Regions can be nested to represent subintervals.

`StartRegion` is a no-op when no execution trace is ongoing[^2]. It does
make one small allocation otherwise, which is a little silly since a
better API could have avoided it.

The result of this change is that execution traces are easier
to inspect visually, as many goroutines in the system will
now state their purpose (the task name) as opposed to looking
like yet another opaque "(*Stopper).RunAsyncTaskEx.func2".

Sadly, goroutines that tagged their region before the execution
trace begins will not reflect their region. So, for example, a
`(*raftSchedulerShard).worker`, despite running inside of a task,
will not have a region attached to it (since the `StartRegion`
call happened at server start,  before the execution trace began).

[^1]: https://pkg.go.dev/runtime/trace#hdr-User_annotation
[^2]: https://cs.opensource.google/go/go/+/refs/tags/go1.23.1:src/runtime/trace/annotation.go;l=144-159

Epic: none
Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130397#-:-O6Wd-hV-OB3-QWRTd4v:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130397)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/util/stop/stopper.go` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130397#-O6Wfa5X-X3pmKwqAnAU:-O6Wfa5X-X3pmKwqAnAV:b1kisys) ([raw file](https://github.com/cockroachdb/cockroach/blob/0afe71c4cdb43747353afe3b13760cdfb0393315/pkg/util/stop/stopper.go#L326)):*
> ```Go
> 
> func (s *Stopper) startRegion(ctx context.Context, taskName string) *trace.Region {
> 	return trace.StartRegion(ctx, taskName)
> ```

Did we want to gate this behind a `trace.IsEnabled`?

**Comment by tbg** [comment]
> Did we want to gate this behind a trace.IsEnabled?

Yeah - why not. I originally figured it would be nice to always eat the overhead on the assumption that it needs to be very small anyway, lest execution tracing becomes yet another thing we're afraid of turning on. But I agree we should avoid allocations where we easily can, and this is such a case.

I added a commit, once you've taken a look and if you find nothing you'd like to see changed, would you "bors r+" this for me?

**Comment by nvanbenschoten** [comment]
LGTM!

bors r=nvanbenschoten

**Pull request merged**
