### PR TITLE
sql: use Latest[Non]PrimaryIndexDescriptorVersion constants in more places

### PR DESCRIPTION
**Pull request by mgartner**
These constants have been moved from tabledesc to descpb to avoid import
cycles.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72818#-:-ModPibOAHFyd1ClCV44:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @postamar)

___
*[pkg/sql/doctor/doctor_test.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72818#-ModPVrm0092wvuUExkM:-ModPVrm0092wvuUExkN:bl3mbbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/26be46acf23f3b3becef556e3e992b34bbd550f1/pkg/sql/doctor/doctor_test.go#L56)):*
> ```
> 				Version:             descpb.PrimaryIndexWithStoredColumnsVersion,
> ```
This one I could see wanting to leave as the fixed value. :shrug:

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72818)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)

___
*[pkg/sql/doctor/doctor_test.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72818#-ModPVrm0092wvuUExkM:-Mod_36M2uqXVvZa023a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26be46acf23f3b3becef556e3e992b34bbd550f1/pkg/sql/doctor/doctor_test.go#L56)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 				Version:             descpb.PrimaryIndexWithStoredColumnsVersion,
> ```
This one I could see wanting to leave as the fixed value. :shrug: 
</blockquote></details>

Done.

**Comment by mgartner** [comment]
@ajwerner mind taking another quick look? I had to move the constants to avoid a cycle.

**Review by postamar — APPROVED** [review]
All good!

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
