### PR TITLE
build: interpret all protoc warnings as errors

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM. I'm sad to see there is no `-Werror` for protoc.

**Comment by benesch** [comment]
Indeed. If I had to guess, the problem is that protoc has no concept of warnings, so gogoproto prints directly to stderr: https://github.com/gogo/protobuf/blob/a11c89fbb0ad4acfa8abc4a4d5f7e27c477169b1/plugin/defaultcheck/defaultcheck.go#L102

I'll file a bug there. Thanks for the review!

**Review by dt — APPROVED** [review]
Thanks!

**Comment by benesch** [comment]
uggg, blocked on https://github.com/gogo/protobuf/issues/207. Nothing is ever easy.

**Comment by benesch** [comment]
Well, that was a stupid amount of yak shaving. I've submitted a request for a -Werror into the upstream void (https://github.com/google/protobuf/issues/3980), but this should do for now.

TFTRs!

**Pull request merged**
