### PR TITLE
util: add FastIntMap.MaxValue

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: 

What is the use for this?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/util/fast_int_map.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422#-L4g4n93Va7pI7tpk0eb:-L4g4n93Va7pI7tpk0ec:b-r4zor8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ace81ba480d0bf52da599093e9020ead419a0c8/pkg/util/fast_int_map.go#L108)):*
> ```Go
> 	if m.large == nil {
> 		// TODO(radu): we could skip words that are 0
> 		// and use bits.LeadingZeros64.
> ```

The word skipping seems worthwhile to do. Also, you can walk the vals from back to front returning the first value found. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422#-:-L4g4zfglOfdRe6FXgsQ:bz2ktyx)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/util/fast_int_map.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422#-L4g4n93Va7pI7tpk0eb:-L4g5MUsV1TYq1MNxcyD:by2e1o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ace81ba480d0bf52da599093e9020ead419a0c8/pkg/util/fast_int_map.go#L108)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The word skipping seems worthwhile to do. Also, you can walk the vals from back to front returning the first value found. 
</blockquote></details>

Err, nix that part about returning the first value found. This is an `IntMap`, not an `IntSet`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422)*

**Comment by RaduBerinde** [comment]
I'm using it in the opt exec building code. I have a map from variable index to resultcolumn index and need to know how many `IndexedVar`s I need. This seemed easier than keeping track of the number of columns.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/fast_int_map.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422#-L4g4n93Va7pI7tpk0eb:-L4gF98G1d4GnEDD9YYg:b-j7u3dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ace81ba480d0bf52da599093e9020ead419a0c8/pkg/util/fast_int_map.go#L108)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Err, nix that part about returning the first value found. This is an `IntMap`, not an `IntSet`. 
</blockquote></details>

Done (and for MaxKey).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422#-:-L4gC_JtxpjCrWcGu9si:b-c3ulss)*

**Comment by RaduBerinde** [comment]
*[pkg/util/fast_int_map.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422#-L4g4n93Va7pI7tpk0eb:-L4gRJZ1X74qDrLxMi2r:bu35jjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ace81ba480d0bf52da599093e9020ead419a0c8/pkg/util/fast_int_map.go#L108)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done (and for MaxKey).
</blockquote></details>

Further improved this to skip the high unset groups.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/util/fast_int_map.go, line 120 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422#-L4gSH0EM_U4rAPyawd-:-L4gSH0EM_U4rAPyawd0:bx05u6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/aee36a2ea5e9851feedbf2e6b3c84d0de488f8bb/pkg/util/fast_int_map.go#L120)):*
> ```Go
> 				for i := 0; i < numVals; i++ {
> 					val := int(m.getSmallVal(uint32(w*numValsPerWord + i)))
> 					if val != -1 && (!ok || max < val) {
> ```

nit: when `m.large == nil`, we know all of the values are greater than 0 so we could init `max == -1` and avoid the conditional on `!ok`.

---

*[pkg/util/fast_int_map.go, line 130 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422#-L4gSPpQ7kadjKcYZWBZ:-L4gSPpQ7kadjKcYZWB_:b-txv6q6) ([raw file](https://github.com/cockroachdb/cockroach/blob/aee36a2ea5e9851feedbf2e6b3c84d0de488f8bb/pkg/util/fast_int_map.go#L130)):*
> ```Go
> 	for _, v := range m.large {
> 		if !ok || max < v {
> 			max, ok = v, true
> ```

nit: you only need to set `max` here. Before the loop, you could do `if len(m.large) == 0; return 0, false`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/fast_int_map.go, line 120 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422#-L4gSH0EM_U4rAPyawd-:-L4gU4aF0iXuZ5Q1mCaP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aee36a2ea5e9851feedbf2e6b3c84d0de488f8bb/pkg/util/fast_int_map.go#L120)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

nit: when `m.large == nil`, we know all of the values are greater than 0 so we could init `max == -1` and avoid the conditional on `!ok`.
</blockquote></details>

Done.

---

*[pkg/util/fast_int_map.go, line 130 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422#-L4gSPpQ7kadjKcYZWBZ:-L4gU5MCyWW4tfcvCMD-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aee36a2ea5e9851feedbf2e6b3c84d0de488f8bb/pkg/util/fast_int_map.go#L130)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

nit: you only need to set `max` here. Before the loop, you could do `if len(m.large) == 0; return 0, false`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22422)*

**Pull request merged**
