### PR TITLE
roachpb, server, storage, ui: move locality from store to node descriptor

### LINKED ISSUE #9782: storage: locality should be on the NodeDescriptor, not StoreDescriptor
https://github.com/cockroachdb/cockroach/pull/8676 appears to have put it on the StoreDescriptor for no good reason (that I can see).

This should get done before next week's beta to avoid subsequently breaking compatibility.

### PR DESCRIPTION
**Pull request by BramGruneir**
There is no reason for it to be on the store but this will interfere with
reapplying the zone config changes (see #9336).

Fixes #9782.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9860)

### CODE REVIEW

**Comment by BramGruneir** [comment]
I'm working on a unit test as well that will make sure that the node descriptor and store descriptors do indeed get the locality info.  I'll add that commit when it's ready.

But I wanted this to get in asap before we cut the release.

**Comment by tamird** [comment]
Tests failed? Looks good so far, let's wait until the test is ready or we're really under the gun to cut the beta to merge this.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/node.go, line 279 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9860#-KTl-YPRfIkqvNyY9aN3:-KTl-YPRfIkqvNyY9aN4:b-qxaeo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/beeb6f722f7f381808f607ef803e9434b8488be3/server/node.go#L279)):*
> ```Go
> 
> // initDescriptor initializes the node descriptor with the server
> // address, the node attributes and locality.
> ```

oxford comma plz

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9860#-:-KTl-hjEn2u6DwnCnQro:bg3ocso)*

**Comment by BramGruneir** [comment]
It was a make check failure.  Hopefully that's gone away with the rebase.

Also, I added a unit test to ensure that the locality is indeed propagated correctly..

---

Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/node.go, line 279 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9860#-KTl-YPRfIkqvNyY9aN3:-KToRJsFvbhHyWcv2Qe2:b-31xcd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/beeb6f722f7f381808f607ef803e9434b8488be3/server/node.go#L279)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> oxford comma plz
</details>
No.  Not a fan of them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9860#-:-KToRULT7-KcudBV7LlO:b-3f159r)*

**Comment by paperstreet** [comment]
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/node.go, line 279 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9860#-KTl-YPRfIkqvNyY9aN3:-KToTjv4kfFYIgeJp0PZ:bt3f4y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/beeb6f722f7f381808f607ef803e9434b8488be3/server/node.go#L279)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> No.  Not a fan of them.
</details>
Wow, don't think I've ever met an oxford comma hater before

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9860)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/node_test.go, line 654 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9860#-KTojefchkSeY7ZCQTHa:-KTojefdZ3pn1ozGD3ji:b-7bx54) ([raw file](https://github.com/cockroachdb/cockroach/blob/283d04e51f0db0aeeeb05a2e0c7c67be1536d405/server/node_test.go#L654)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		engines := []engine.Engine{e}
> ```

not need for this local

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9860#-:-KTojXM84bgGhDDhF12E:bnfp4nl)*

**Comment by BramGruneir** [comment]
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[server/node_test.go, line 654 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9860#-KTojefchkSeY7ZCQTHa:-KTokWE0o_YKkKHh_ucF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/283d04e51f0db0aeeeb05a2e0c7c67be1536d405/server/node_test.go#L654)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> not need for this local
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9860)*

**Pull request merged**
