### PR TITLE
build: add java to builder

### PR DESCRIPTION
**Pull request by dt**
needed for #18981 but pushing now to facilitate some unrelated, concurrent changes.

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM!

**Review by jordanlewis — APPROVED** [review]
👍 sorry this was such a pain

**Review by benesch — APPROVED** [review]

**Comment by knz** [comment]
yay it's green

**Comment by dt** [comment]
Thanks @knz for saving me from re-building that!

**Pull request merged**
