### PR TITLE
sql/sem: pull cast and volatility out of tree

### PR DESCRIPTION
**Pull request by ajwerner**
This PR contains some preliminary code movement in anticipation of https://github.com/cockroachdb/cockroach/pull/80504. Each of the commits were mechanical and done with automated code movement. The first commit, creating the `volatility` package, is the important one. The creation of the `cast` package is more opportunistic. 

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Looks great! My only nit is that I think it's weird that cast logic is now split between two packages, with the execution of casts remaining in `tree`. @otan and I eventually wanted to keep the functions to perform each cast in the cast map, but we'd be unable to do so if there's a reason that logic can't be moved to the `cast` package. But I wouldn't hold up the PR for it.

FYI you might have a slightly painful rebase after https://github.com/cockroachdb/cockroach/pull/79537 is merged.

> Reviewed 59 of 59 files at r1, 4 of 4 files at r2, 23 of 23 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80546#-:-N0apVtiD9zW6oWPcwd2:bld5rfe)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

___
*[`pkg/sql/sem/tree/cast_map_test.go` line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80546#-N0aq-vy3MjyfJpOYAXP:-N0aq-vy3MjyfJpOYAXQ:b-x8234b) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4df9aae8a49b446c9d461f7baa02a63185b71f/pkg/sql/sem/tree/cast_map_test.go#L33)):*
> ```Go
> // TestCastMap tests that every cast in tree.castMap can be performed by
> // PerformCast.
> func TestCastMap(t *testing.T) {
> ```

Should we move this file to `pkg/sql/sem/cast/`?
___
*[`pkg/sql/sem/volatility/volatility.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80546#-N0aoT0U1-C2611mMOhb:-N0aoT0U1-C2611mMOhc:bfxgej2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f551eab5c98e3a1834f40ba544fbb97855843f5a/pkg/sql/sem/volatility/volatility.go#L27)):*
> ```Go
> // must be labeled volatile to ensure they will not get optimized away,
> // even if the actual return value is not changeable.
> type Volatility int8
> ```

Do you think it would be more idiomatic to name this `volatility.V`? I'm thinking of similar examples like `testing.T` and `types.T`. We can always do that in a future PR too if we want.

**Review by ajwerner — COMMENTED** [review]
> FYI you might have a slightly painful rebase after #79537 is merged.

:partying_face: 

> @otan and I eventually wanted to keep the functions to perform each cast in the cast map, but we'd be unable to do so if there's a reason that logic can't be moved to the cast package. But I wouldn't hold up the PR for it.

The challenge here is that we need to know about the available casts in type checking but the cast operations themselves need things from the eval context. This package only has the descriptive logic to talk about what casts are valid and it doesn't have any logic to talk about how to do the casts. I think that's fine. You'll see in #80504 that `PerformCast` and friends move to the `eval` package. We can further extract interfaces there later. 

Until we sort out type checking's relationship with `tree` I want to keep this below tree and the evaluation above tree. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80546#-:-N0axP0o7V59oVuV6-nL:b-m3qryh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, and @otan)

___
*[`pkg/sql/sem/tree/cast_map_test.go` line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80546#-N0aq-vy3MjyfJpOYAXP:-N0ay6QC2ljWk3YAfHub:bcho7z4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4df9aae8a49b446c9d461f7baa02a63185b71f/pkg/sql/sem/tree/cast_map_test.go#L33)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should we move this file to `pkg/sql/sem/cast/`?
</blockquote></details>

I wanted to keep the cast package out of the business of evaluating casts. I'll add more words to the doc comment.

**Review by ajwerner — COMMENTED** [review]
Alright, I've rebased on top of #79537. Will bors when green 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80546#-:-N0bTaYH9CEUX928swZK:bvbcdux)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @otan)

___
*[`pkg/sql/sem/volatility/volatility.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80546#-N0aoT0U1-C2611mMOhb:-N0bT_NiEqK_S2BB71fK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f551eab5c98e3a1834f40ba544fbb97855843f5a/pkg/sql/sem/volatility/volatility.go#L27)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do you think it would be more idiomatic to name this `volatility.V`? I'm thinking of similar examples like `testing.T` and `types.T`. We can always do that in a future PR too if we want.
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
I don't think you intended to include the `sql: Populate pg_cast` commit.

> Reviewed 39 of 39 files at r5, 1 of 1 files at r6, 8 of 8 files at r7, 29 of 29 files at r8, 10 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80546#-:-N0bVs8S2HMirlGQFnfB:btkmaw0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan)

___
*[`pkg/sql/sem/tree/cast_map_test.go` line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80546#-N0aq-vy3MjyfJpOYAXP:-N0bUxKt7Aca2WZCvr78:b-z0x99p) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4df9aae8a49b446c9d461f7baa02a63185b71f/pkg/sql/sem/tree/cast_map_test.go#L33)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I wanted to keep the cast package out of the business of evaluating casts. I'll add more words to the doc comment. 
</blockquote></details>

Make sense. :+1:

**Comment by ajwerner** [comment]
> I don't think you intended to include the sql: Populate pg_cast commit.

Fixed. Thanks!

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Review by otan — APPROVED** [review]

**Pull request merged**
