### PR TITLE
sql: prepare framework for table generators, provide generate_series()

### LINKED ISSUE #10520: sql: add support for Set Returning (Generator) Functions
See https://www.postgresql.org/docs/9.6/static/functions-srf.html.

`generate_series` is needed for Hibernate.

@knz you mentioned you had thought of this before. Any thoughts here?

### PR DESCRIPTION
**Pull request by knz**
This patch introduces the following:

- `TTable`: a new SQL type for table objects (pg calls this "setof").
- `DTable`: a Datum that can hold a table constructor.
- `pg_catalog.generate_series`: a new built-in function that returns a `DTable`.
- support for `DTable`-returning expressions in FROM positions.

Plug this all together and you can do:

```
  SELECT * FROM generate_series(1, 3);
  +-----------------+
  | generate_series |
  +-----------------+
  |               1 |
  |               2 |
  |               3 |
  +-----------------+
  (3 rows)
```

Fixes #10520.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11214)

### CODE REVIEW

**Comment by knz** [comment]
Needed for #11214.

**Comment by nvanbenschoten** [comment]
Nice, this is really cool!

---

Reviewed 2 of 2 files at r1, 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/generator.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP5InzYqWTZvALo0hx:-KXP5InzYqWTZvALo0hy:b-neat9) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/generator.go#L26)):*
> ```Go
> )
> 
> type valueGenerator struct {
> ```

This could use a comment.

---

*[pkg/sql/generator.go, line 43 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP5kYRE1i9FXe2M6lL:-KXP5kYRE1i9FXe2M6lM:bnqtgg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/generator.go#L43)):*
> parser.TypeAny

#10717 isn't merged yet. Please use `NoTypePreference` for now.

---

*[pkg/sql/parser/generator_builtins.go, line 30 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP6XHa9QAdeNSSmwoz:-KXP6XHa9QAdeNSSmwp-:bol8mtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L30)):*
>  (this is a new Datum type)

not in a year it wont be! Let's avoid dating the comment like this.

---

*[pkg/sql/parser/generator_builtins.go, line 32 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP6gb6zTpn-Rx7Tuxy:-KXP6gb6zTpn-Rx7Tuxz:b1qokyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L32)):*
> ```Go
> //   return values of type DTable (this is a new Datum type).
> //
> // - the return type of generators is a new TTable type. This
> ```

Same issue: `s/new TTable type/TTable type/`

---

*[pkg/sql/parser/generator_builtins.go, line 40 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP6uijnbKYdCUXzpx0:-KXP6uijnbKYdCUXzpx1:bnf27x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L40)):*
> ```Go
> //
> // - ValueGenerator is an interface that offers a
> //   Start/Next/Values/Stop API similar to planNode.
> ```

`s/planNode/sql.planNode/` since we're in a different package.

---

*[pkg/sql/parser/generator_builtins.go, line 44 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP76UL_SbsQBok4VoM:-KXP76UL_SbsQBok4VoN:b-un059z) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L44)):*
> ```Go
> // - because generators are regular functions, it is possible to use
> //   them in any expression context. This is useful to e.g
> //   pass an entire table as argument to the ARRAY( ) conversion
> ```

Does this actually work?

---

*[pkg/sql/parser/generator_builtins.go, line 57 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP7QWokbRlvZJv2I1a:-KXP7QWokbRlvZJv2I1b:b-zl2tv) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L57)):*
> ```Go
> 
> // ValueGenerator is the interface provided by the object
> // held by a DTable.
> ```

ValueGenerator is the interface provided by the object held by a DTable... which does what? 

---

*[pkg/sql/parser/generator_builtins.go, line 81 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP7uFt2Xr9n8KFme2S:-KXP7uFt2Xr9n8KFme2T:b-11jh29) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L81)):*
> ```Go
> var _ ValueGenerator = &seriesValueGenerator{}
> 
> var errStepCannotBeZero = errors.New("step cannot be 0")
> ```

I'd move this above `seriesValueGenerator`, since it only seems relevant to that one type.

---

*[pkg/sql/parser/generator_builtins.go, line 104 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP8vwivjjlcuyfmo1J:-KXP8vwivjjlcuyfmo1K:bmbwr9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L104)):*
> ```Go
> 
> var generators = map[string][]Builtin{
> 	"pg_catalog.generate_series": {
> ```

Is this part of the pg_catalog namespace? Is everything part of the pg_catalog namespace?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-:-KXP9cV-ZMeEvxWdocL-:b16y2gd)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/generator.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP5InzYqWTZvALo0hx:-KXS5g97CEMAmHgLufU7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/generator.go#L26)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> This could use a comment.
</details>
Done.

---

*[pkg/sql/generator.go, line 43 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP5kYRE1i9FXe2M6lL:-KXS5geJtnZe9LWVvjGr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/generator.go#L43)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> > parser.TypeAny
> 
> #10717 isn't merged yet. Please use `NoTypePreference` for now.
</details>
Done.

---

*[pkg/sql/parser/generator_builtins.go, line 30 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP6XHa9QAdeNSSmwoz:-KXS5npufJ4yTlZk60UZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L30)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> >  (this is a new Datum type)
> 
> not in a year it wont be! Let's avoid dating the comment like this.
</details>
Done.

---

*[pkg/sql/parser/generator_builtins.go, line 32 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP6gb6zTpn-Rx7Tuxy:-KXS5oWV4HY4hFJ2Axt8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L32)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Same issue: `s/new TTable type/TTable type/`
</details>
Done.

---

*[pkg/sql/parser/generator_builtins.go, line 40 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP6uijnbKYdCUXzpx0:-KXS5u6YwKUwTU0g3wZ0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L40)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `s/planNode/sql.planNode/` since we're in a different package.
</details>
Done.

---

*[pkg/sql/parser/generator_builtins.go, line 44 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP76UL_SbsQBok4VoM:-KXS65OWjUH-LvwT_QhE:b-uk15dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L44)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Does this actually work?
</details>
Not yet, but we have an open issue for this already:  #10763.

---

*[pkg/sql/parser/generator_builtins.go, line 57 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP7QWokbRlvZJv2I1a:-KXS6OgDc408PnhyenXe:b-uyf7ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L57)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> ValueGenerator is the interface provided by the object held by a DTable... which does what? 
</details>
Clarified in comment.

---

*[pkg/sql/parser/generator_builtins.go, line 81 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP7uFt2Xr9n8KFme2S:-KXS6SQEPk54i9zmVbNs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L81)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I'd move this above `seriesValueGenerator`, since it only seems relevant to that one type.
</details>
Done.

---

*[pkg/sql/parser/generator_builtins.go, line 104 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP8vwivjjlcuyfmo1J:-KXS6T3ceH59AYLFQJ3w:b-tlk25a) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L104)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Is this part of the pg_catalog namespace? Is everything part of the pg_catalog namespace?
</details>
1) no, not everything is in pg_catalog, I'd say only those functions that are expected to be there for pg compatibility should be there.

2) I am putting this in the pg_catalog namespace because the demand from it came from ORM use cases that tend to prefix a lot of things with " `pg_catalog.` ". But if we're confident `generate_series` is usually not prefixed by clients, I'd be glad to get it out of that namespace.

3) (contradicting myself, I realize) there may be a case that all functions also implemented by postgres could be put in the pg_catalog namespace, since if we want compatibilty we should support calls of the form `pg_catalog.xxx` for any `xxx` from postgres which we support, and that includes more or less everything we support for now. *but* that said I would also be OK with a special-casing of function lookups where anything looked up explicitly in namespace `pg_catalog` is searched in the global namespace too. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214)*

**Comment by knz** [comment]
Note that I am getting the following panic on a `pg_proc` test:
```
panic: programmer error: could not find referenced type setof tuple{int} on builtin {int, int setof tuple{int} false true 3   <nil> <nil> 0x8d5b90 0x970140} [recovered]
        panic: SELECT proname, pronamespace, proowner, prolang, procost, prorows, provariadic
FROM pg_catalog.pg_proc
WHERE proname='substring';: programmer error: could not find referenced type setof tuple{int} on builtin {int, int setof tuple{int} false true 3   <nil> <nil> 0x8d5b90 0x970140}
```

any suggestions?

**Comment by knz** [comment]
I also modified the pg_proc code. PTAL.

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 1 of 17 files at r4.
Review status: 2 of 19 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/generator_builtins.go, line 104 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-KXP8vwivjjlcuyfmo1J:-KXb74eUlW8H-7rUbE6_:bacr497) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e8de39c7939c0b3c7087e116d23fa92479bf19/pkg/sql/parser/generator_builtins.go#L104)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> 1) no, not everything is in pg_catalog, I'd say only those functions that are expected to be there for pg compatibility should be there.
> 
> 2) I am putting this in the pg_catalog namespace because the demand from it came from ORM use cases that tend to prefix a lot of things with " `pg_catalog.` ". But if we're confident `generate_series` is usually not prefixed by clients, I'd be glad to get it out of that namespace.
> 
> 3) (contradicting myself, I realize) there may be a case that all functions also implemented by postgres could be put in the pg_catalog namespace, since if we want compatibilty we should support calls of the form `pg_catalog.xxx` for any `xxx` from postgres which we support, and that includes more or less everything we support for now. *but* that said I would also be OK with a special-casing of function lookups where anything looked up explicitly in namespace `pg_catalog` is searched in the global namespace too. What do you think?
> 
> 
</details>
I think it's safe to keep this in `pg_catalog` becaause of the reasons you listed. The following query is blowing my mind though:

```
nathan=# SELECT pg_catalog.now();
              now
-------------------------------
 2016-11-27 13:51:00.511014-05
```

It looks like every function in Postgres (that isn't a user defined function) is under the `pg_catalog` namespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11214#-:-KXbEmHgR4XAbSD-yKsa:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
