### PR TITLE
workload: remove NumTotal field from BatchedTuples

### PR DESCRIPTION
**Pull request by danhhz**
It didn't turn out to be useful for anything and at times it's been
confusing to people.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Is there really (now or later) a workload that can't populate NumRows? Because if there isn't, it seems good to keep that around. LGTM either way.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38207#-:-LhezjFU9zjmrBOrfFjX:b-3zerb7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/ccl/changefeedccl/bench_test.go, line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38207#-LheyVsP-rP71J2avRbo:-LheyVsQE3LicwY8FLFN:b-kjoo7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e0b328d31bb7381917b1c16527d062a4d0c207f/pkg/ccl/changefeedccl/bench_test.go#L312)):*
> ```Go
> 		return nil, 0, err
> 	}
> 	// There happens to be 1 row per batch in bank.
> ```

Am I missing some context that makes this ... ok? Nothing about this method is specific to `bank` (though maybe that's the only use for it right now). Aren't you iterating over everything above? You can just compute the running total.
___
*[pkg/ccl/workloadccl/workload_test.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38207#-Lheyw7V6Btq1o99ubFf:-Lheyw7V6Btq1o99ubFg:b-j4qeso) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e0b328d31bb7381917b1c16527d062a4d0c207f/pkg/ccl/workloadccl/workload_test.go#L75)):*
> ```Go
> 				var c int
> 				sqlDB.QueryRow(t, fmt.Sprintf(`SELECT count(*) FROM "%s"`, table.Name)).Scan(&c)
> 				// There happens to be 1 row per batch in roachmart.
> ```

Meh, also not great, but I guess I don't see a good workaround here. I guess if you were trying to really clean this up you'd put a `validate: func() error` on each test case that can then do something meaningful, but meh.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38207)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/ccl/changefeedccl/bench_test.go, line 312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38207#-LheyVsP-rP71J2avRbo:-Lhfqm203Ni-3ZGc_qYl:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e0b328d31bb7381917b1c16527d062a4d0c207f/pkg/ccl/changefeedccl/bench_test.go#L312)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Am I missing some context that makes this ... ok? Nothing about this method is specific to `bank` (though maybe that's the only use for it right now). Aren't you iterating over everything above? You can just compute the running total.
</blockquote></details>

Done
___
*[pkg/ccl/workloadccl/workload_test.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38207#-Lheyw7V6Btq1o99ubFf:-Lhft0rdC2LzZd24Yzot:b-5i11kj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e0b328d31bb7381917b1c16527d062a4d0c207f/pkg/ccl/workloadccl/workload_test.go#L75)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Meh, also not great, but I guess I don't see a good workaround here. I guess if you were trying to really clean this up you'd put a `validate: func() error` on each test case that can then do something meaningful, but meh.
</blockquote></details>

Deleted this test in favor of making roachmart work (somewhat) in TestAllRegisteredSetup

**Review by danhhz — COMMENTED** [review]
> Is there really (now or later) a workload that can't populate NumRows?

Whoops, forgot to reply to this. The tpcc order_line table can't, because the number of rows in each batch is pseudo-random (seeded from the batch index).

The field really hasn't proved useful for anything though. I was originally thinking you could use it to pre-size things, but that just hasn't come up anywhere

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38207#-:-LhftUYO22BdqBRlBmfX:bcpynkx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38207)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by danhhz** [comment]
Thanks for the review!

bors r=tbg

**Pull request merged**
