### PR TITLE
sql: fix typing of subqueries

### PR DESCRIPTION
**Pull request by petermattis**
Subqueries in "table" contexts (e.g. the right hand side of an IN) were
previously being given an incorrect type in some instances. For example:

  `SELECT (1, 2) in (SELECT 1, 2)`

The subquery was being given the type `tuple{int,int}`. We were then
type checking `<tuple{int,int}> IN <tuple{int,int>}`. This was
succeeding because of special code (a bug) in
`typeCheckSubqueryWithin`. The subquery in the above example is now
given the tuple `tuple{tuple{int,int}}` which makes the comparison
expression match the parameterization `U in tuple{U}`.

The two bugs above cancelled each other out for query execution. A
difference can be seen in the output of `EXPLAIN (TYPES)`.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
FYI, this is independent of #21075. Consider it in isolation

**Comment by petermattis** [comment]
I added a second commit which addresses crashes with edge case subqueries such as `SELECT (SELECT (1, 2)) IN (SELECT (1, 2))` while both simplifying the code and expanding our subquery type checking to handle queries like `SELECT (SELECT 1, 2) = (SELECT 1 2)`.

**Comment by knz** [comment]
First commit LGTM.
2nd commit - general idea LGTM, but I think the code will trip on ParenExpr.

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/subquery.go, line 292 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076#-L1RqEXOith0IzoIY14G:-L1RqEXOith0IzoIY14H:b-tpmudz) ([raw file](https://github.com/cockroachdb/cockroach/blob/134a9d5ebe59a1297ba68c3f521b086a3cac14a5/pkg/sql/subquery.go#L292)):*
> ```Go
> 	switch t := expr.(type) {
> 	case *tree.ArrayFlatten:
> 		if sub, ok := t.Subquery.(*tree.Subquery); ok {
> ```

As long as we do not desugar grouping parentheses during parsing, this code needs to deal with `tree.ParenExpr`  - e.g. `array( ( ( select 1 ) ) )` should be handled too.
Maybe you want to use `StripParens()` here and below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076#-:-L1Rqbqe2nZJKSs6PJIs:bmsczg)*

**Comment by knz** [comment]
Thanks for the fix!

**Comment by petermattis** [comment]
> but I think the code will trip on ParenExpr.

I'm not sure why the previous code had `ParenExpr` in there. It wasn't necessary. If you comment it out, all of the tests still pass. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/subquery.go, line 292 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076#-L1RqEXOith0IzoIY14G:-L1SMKGv-bUPnYpZe5ua:bddgpsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/134a9d5ebe59a1297ba68c3f521b086a3cac14a5/pkg/sql/subquery.go#L292)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

As long as we do not desugar grouping parentheses during parsing, this code needs to deal with `tree.ParenExpr`  - e.g. `array( ( ( select 1 ) ) )` should be handled too.
Maybe you want to use `StripParens()` here and below.
</blockquote></details>

This isn't actually a problem. I already had a test case demonstrating this for subqueries on the right-hand side of `IN` expressions. Added another one for subqueries within `ARRAY`. Why isn't this a problem? The parens are associated with the subquery, not the scalar expression, and thus become part of a `ParenSelect`, not a `ParenExpr`.

```
// There is an ambiguity when a sub-SELECT is within an a_expr and there are
// excess parentheses: do the parentheses belong to the sub-SELECT or to the
// surrounding a_expr?  We don't really care, but bison wants to know. To
// resolve the ambiguity, we are careful to define the grammar so that the
// decision is staved off as long as possible: as long as we can keep absorbing
// parentheses into the sub-SELECT, we will do so, and only when it's no longer
// possible to do that will we decide that parens belong to the expression. For
// example, in "SELECT (((SELECT 2)) + 3)" the extra parentheses are treated as
// part of the sub-select. The necessity of doing it that way is shown by
// "SELECT (((SELECT 2)) UNION SELECT 2)". Had we parsed "((SELECT 2))" as an
// a_expr, it'd be too late to go back to the SELECT viewpoint when we see the
// UNION.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076#-:-L1SMii2cmdUCXdnPZQ8:b8tk2km)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/subquery.go, line 292 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076#-L1RqEXOith0IzoIY14G:-L1TIKE5nlvd8exziSSQ:b5n2csa) ([raw file](https://github.com/cockroachdb/cockroach/blob/134a9d5ebe59a1297ba68c3f521b086a3cac14a5/pkg/sql/subquery.go#L292)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This isn't actually a problem. I already had a test case demonstrating this for subqueries on the right-hand side of `IN` expressions. Added another one for subqueries within `ARRAY`. Why isn't this a problem? The parens are associated with the subquery, not the scalar expression, and thus become part of a `ParenSelect`, not a `ParenExpr`.

```
// There is an ambiguity when a sub-SELECT is within an a_expr and there are
// excess parentheses: do the parentheses belong to the sub-SELECT or to the
// surrounding a_expr?  We don't really care, but bison wants to know. To
// resolve the ambiguity, we are careful to define the grammar so that the
// decision is staved off as long as possible: as long as we can keep absorbing
// parentheses into the sub-SELECT, we will do so, and only when it's no longer
// possible to do that will we decide that parens belong to the expression. For
// example, in "SELECT (((SELECT 2)) + 3)" the extra parentheses are treated as
// part of the sub-select. The necessity of doing it that way is shown by
// "SELECT (((SELECT 2)) UNION SELECT 2)". Had we parsed "((SELECT 2))" as an
// a_expr, it'd be too late to go back to the SELECT viewpoint when we see the
// UNION.
```
</blockquote></details>

All right, thanks for reminding me about this parser oddity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076#-:-L1TIOn-YHbi4ZkzGOQ6:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Nice simplification to `subqueryVisitor`!

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/subquery, line 82 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076#-L1TflvpaJPpzW6kce7W:-L1TflvpaJPpzW6kce7X:b-st51xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ddba85dd0aa801d45ea5c764519b7e032b8021/pkg/sql/logictest/testdata/logic_test/subquery#L82)):*
> ```
> 
> query error unsupported comparison operator: <tuple{int, int}> IN <tuple{tuple{tuple{int, int}}}>
> SELECT (SELECT (1, 2)) IN (SELECT (1, 2))
> ```

Postgres seems to handle this query without issue but doesn't handle the following (the query two above):

```
postgres=# SELECT (SELECT (1, 2)) IN (SELECT 1, 2);
ERROR:  subquery has too many columns
```

Is this inconsistency expected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076#-:-L1TeSZbzjanSywgAOsa:b-6eimej)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/subquery, line 82 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076#-L1TflvpaJPpzW6kce7W:-L1Tk5WOZ7YwZPKk2Jfs:b5cu1l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ddba85dd0aa801d45ea5c764519b7e032b8021/pkg/sql/logictest/testdata/logic_test/subquery#L82)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Postgres seems to handle this query without issue but doesn't handle the following (the query two above):

```
postgres=# SELECT (SELECT (1, 2)) IN (SELECT 1, 2);
ERROR:  subquery has too many columns
```

Is this inconsistency expected?
</blockquote></details>

Postgres seems bizarre here. `(SELECT (1, 2))` in a single-row context returns `ROW(1,2)`. I see the following set of behavior from postgres, which seems inconsistent:

```
pmattis=# select (1, 2) in ((1, 2));
 ?column?
----------
 t
(1 row)

pmattis=# select (1, 2) in (select 1, 2);
 ?column?
----------
 t
(1 row)

pmattis=# select (select (1, 2)) in ((1, 2));
 ?column?
----------
 t
(1 row)

pmattis=# select (select (1, 2)) in (select 1, 2);
ERROR:  subquery has too many columns
LINE 1: select (select (1, 2)) in (select 1, 2);
                               ^

pmattis=# select (1, 2) in (select (1, 2));
ERROR:  subquery has too few columns
LINE 1: select (1, 2) in (select (1, 2));
                      ^
pmattis=# select (select (1, 2)) in (select (1, 2));
 ?column?
----------
 t
(1 row)
```

The CRDB behavior is more consistent. Thoughts on what to do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/subquery, line 82 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076#-L1TflvpaJPpzW6kce7W:-L1TxjbAGJr0cjBJalpi:b-4mzxxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/80ddba85dd0aa801d45ea5c764519b7e032b8021/pkg/sql/logictest/testdata/logic_test/subquery#L82)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I've been pretty conditioned to say "do whatever Postgres does, we'll eventually have to do it anyway", but in this case, CRDB's behavior really does seem to be a lot more consistent. I think I agree with the way we're doing it here.

For reference, CockroachDB accepts the first four of those queries:
```
root@:26257/> select (1, 2) in ((1, 2));
+--------------------+
| (1, 2) IN ((1, 2)) |
+--------------------+
| true               |
+--------------------+
(1 row)

root@:26257/> select (1, 2) in (select 1, 2);
+-------------------------+
| (1, 2) IN (SELECT 1, 2) |
+-------------------------+
| true                    |
+-------------------------+
(1 row)

root@:26257/> select (select (1, 2)) in ((1, 2));
+-----------------------------+
| (SELECT (1, 2)) IN ((1, 2)) |
+-----------------------------+
| true                        |
+-----------------------------+
(1 row)

root@:26257/> select (select (1, 2)) in (select 1, 2);
+--------------------------------+
| (SELECT (1, 2)) IN (SELECT 1, 2) |
+--------------------------------+
| true                           |
+--------------------------------+
(1 row)

root@:26257/> select (1, 2) in (select (1, 2));
pq: unsupported comparison operator: <tuple{int, int}> IN <tuple{tuple{tuple{int, int}}}>
root@:26257/> select (select (1, 2)) in (select (1, 2));
pq: unsupported comparison operator: <tuple{int, int}> IN <tuple{tuple{tuple{int, int}}}>
```

And MySQL only accepts the first two:
```
mysql> select (1, 2) in ((1, 2));
+--------------------+
| (1, 2) in ((1, 2)) |
+--------------------+
|                  1 |
+--------------------+
1 row in set (0.03 sec)

mysql> select (1, 2) in (select 1, 2);
+-------------------------+
| (1, 2) in (select 1, 2) |
+-------------------------+
|                       1 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select (select (1, 2)) in ((1, 2));
ERROR 1241 (21000): Operand should contain 1 column(s)
mysql> select (select (1, 2)) in (select 1, 2);
ERROR 1241 (21000): Operand should contain 1 column(s)
mysql> select (1, 2) in (select (1, 2));
ERROR 1241 (21000): Operand should contain 1 column(s)
mysql> select (select (1, 2)) in (select (1, 2));
ERROR 1241 (21000): Operand should contain 1 column(s)
```

One case where we agree with MySQL but differ from Postgres is `select (select 1, 2) in (select 1, 2);`.
</blockquote></details>

I'm going to add some of the commentary to the `subquery` test file so that whoever encounters this next can know about our learnings. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21076)*

**Pull request merged**
