### PR TITLE
deps: switch over from raven-go to sentry-go

### PR DESCRIPTION
**Pull request by knz**
This removes the raven-go dependency, which was both obsolete and
incompatible with Go modules, and replaces it with the sentry-go
dependency.

Requires https://github.com/cockroachlabs/registration/pull/235.

NB: sentry-go insists on a specific URL format, an I believe our Sentry gateway doesn't understand that new format. Will need to fix that before this merges.

### CODE REVIEW

**Comment by knz** [comment]
Biggest obstacle now is that the raven packets are decoded in the reg server database, using a format that's incompatible with the new API.

**Review by tbg — APPROVED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[Gopkg.toml, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49321#-M8FL7Fs32TcxECqCUyR:-M8FL7Fs32TcxECqCUyS:b-w3yozz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6841cc02dcb247dff55a7092386a7c6135674a/Gopkg.toml#L71)):*
> ```TOML
> 
> [[override]]
>   name = "github.com/getsentry/sentry-go"
> ```

Why can't we use upstream now? The commits on https://github.com/cockroachdb/sentry-go/commits/master seem to all be on master as well.
___
*[Gopkg.toml, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49321#-M8FLHhL5tGmHI-igSsI:-M8FLHhL5tGmHI-igSsJ:b-9xqren) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6841cc02dcb247dff55a7092386a7c6135674a/Gopkg.toml#L73)):*
> ```TOML
>   name = "github.com/getsentry/sentry-go"
>   source = "https://github.com/cockroachdb/sentry-go"
>   branch = "master"
> ```

They don't do releases?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[Gopkg.toml, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49321#-M8FL7Fs32TcxECqCUyR:-M8FkLHfA4Zgiypl6SdJ:b-8lxdjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6841cc02dcb247dff55a7092386a7c6135674a/Gopkg.toml#L71)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why can't we use upstream now? The commits on https://github.com/cockroachdb/sentry-go/commits/master seem to all be on master as well.
</blockquote></details>

Added a comment to explain.
___
*[Gopkg.toml, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49321#-M8FLHhL5tGmHI-igSsI:-M8FkMb40RzbeDLJT2pS:b-szxjmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6841cc02dcb247dff55a7092386a7c6135674a/Gopkg.toml#L73)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

They don't do releases?
</blockquote></details>

Oops, that was an oversight. Fixed.

**Review by tbg — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by knz** [comment]
bors r=tbg

**Pull request merged**
