### PR TITLE
kv: log when SST ingestion takes a long time

### PR DESCRIPTION
**Pull request by tbg**
This may help with issues such as #63305.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63468#-:-MY4sQOi6xejcvfcfMb5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by dt** [comment]
huh, I'm curious: what's the advantage of looking at the clock a couple times to time how long the delay took vs just logging the calculated delay inside `PreIngestDelay` (we already pass it a ctx and it already had a veventf with the timing and cause which is arguably more useful ?).

**Comment by dt** [comment]
I think where we might really want this logging is around the Store.Send for AddSSTable requests, since I suspect they also often a) wait on the limiter and b) wait on quota pool?

**Comment by tbg** [comment]
I just wasn't aware of it, I'm open to anything that will expose this. I got an issue put into the KV project just because AddSSTable was slow, which I thought wasn't reasonable, and there wasn't anything in the logs.

**Comment by tbg** [comment]
Hmm, maybe, but wouldn't it be better to have a separate threshold around the quota pool then? If it says "hanging on the quota pool or replication or application" that doesn't really get KV off the hook, and we do want to distinguish between a slow disk and a slow KV.

**Comment by tbg** [comment]
actually the quota pool is under replication, so the "have been waiting" message for replication would fire if the quota pool fills up. Not saying this is good enough, but it would've helped in the original issue. We didn't have any slow proposals there.

**Pull request merged**
