### PR TITLE
kvserver: introduce cpu load based splits

### LINKED ISSUE #83519: kvserver: load based splitting should be on a more granular metric
Currently we load based split when the number of requests (requests in all batch requests) exceeds the qps split threshold (default 2500). 

Requests are not uniform however and may be orders of magnitude more expensive than each other e.g. scan of 3k rows vs point read. 

We should split on a more [granular metric than requests per second](https://github.com/cockroachdb/cockroach/blob/443c4d51b9f64067161d9c5510206bcd8408c1b4/pkg/kv/kvserver/split/decider.go#L80-L81). Such as the number of bytes read + written to a range per second. 

The threshold should also be adjusted with testing to a new suitable default.

One alternative is to use the number of key accesses as opposed to the number of bytes. This method would not account for large values being read or written, however would set each access at a fixed cost.

Jira issue: CRDB-17122

Epic CRDB-18661

### LINKED ISSUE #95377: kvserver: cpu based load splitting
In https://github.com/cockroachdb/cockroach/issues/90574 we added support for finding a split point of a range based on a weighted midpoint. Previously, only unweighted midpoints e.g. all queries=1 was supported.

This issue is to integrate this weighted split finder with request cpu and instrument cpu based load splitting.

**additional considerations**

The merge queue uses with the load of a range and the load split threshold when deciding whether to merge two adjacent ranges. These are collected via [RPC](https://github.com/cockroachdb/cockroach/blob/0f6333cbd6c78264a59dc435324c0c33d75ea148/pkg/kv/kvserver/merge_queue.go#L185). This presents an issue in

1. mixed version

Additional fields may not be populated for CPU, so a fallback is needed.

2. in-between or shortly after switching cpu/qps based load splitting

Similar issue to above.

Jira issue: CRDB-23491

### PR DESCRIPTION
**Pull request by kvoli**
This PR adds the ability to perform load based splitting with replica
cpu usage rather than queries per second. Load based splitting now will
use either cpu or qps for deciding split points, depending on the
cluster setting `kv.allocator.load_based_rebalancing.objective`.

When set to `qps`, qps is used in deciding split points and when
splitting should occur; similarly, `cpu` means that request cpu against
the leaseholder replica is to decide split points.

The split threshold when using `cpu` is the cluster setting
`kv.range_split.load_cpu_threshold` which defaults to `250ms` of cpu
time per second, i.e. a replica using 1/4 processor of a machine
consistently.

The merge queue uses the load based splitter to make decisions on
whether to merge two adjacent ranges due to low load. This commit also
updates the merge queue to be consistent with the load based splitter
signal. When switching between `qps` and `cpu`, the load based splitter
for every replica is reset to avoid spurious results.

image

resolves: https://github.com/cockroachdb/cockroach/issues/95377
resolves: https://github.com/cockroachdb/cockroach/issues/83519
depends on: https://github.com/cockroachdb/cockroach/pull/96127

Release note (ops change): Load based splitter now supports using request
cpu usage to split ranges. This is introduced with the previous cluster
setting `kv.allocator.load_based_rebalancing.objective`, which when set
to `cpu`, will use request cpu usage. The threshold above which
CPU usage of a range is considered for splitting is defined in the
cluster setting `kv.range_split.load_cpu_threshold`, which has a default
value of `250ms`.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 7 of 7 files at r4, 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96128)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`-- commits` line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd6Hk376y32QMhFZCP):*
How was the 250ms number evaluated? Should we run an experiment like Andrew did in https://github.com/cockroachdb/cockroach/pull/39687 to tune it to find the right balance between batching and concurrency?
___
*[`pkg/kv/kvserver/batcheval/cmd_range_stats.go` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd5mYsA74YjjQzIT0k:-NNd5mYsA74YjjQzIT0l:b-5klftf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23943c2ab92fd8a7fd60e9195b96c6fc04dec94/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L54)):*
> ```Go
> 		reply.MaxQueriesPerSecond = -1
> 	}
> 	reply.MaxQueriesPerSecondSet = true
> ```

Do we need to keep setting this to true for another release?
___
*[`pkg/kv/kvserver/batcheval/cmd_range_stats.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd763XDanIdRcB--4q:-NNd763XDanIdRcB--4r:b-tpp7m6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L54)):*
> ```Go
> 	reply.MaxCPUPerSecond, reply.MaxQueriesPerSecond = -1, -1
> 	if qpsOK && cpuOK {
> 		return result.Result{}, errors.AssertionFailedf("unexpected both QPS and CPU range statistics set")
> ```

Is this possible if the cluster switched from QPS-based splitting to CPU-based splitting between the calls to `GetMaxSplitQPS` and `GetMaxSplitCPU` above?
___
*[`pkg/kv/kvserver/batcheval/eval_context.go` line 92 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd7PXa0w9ZyYD5cUSh:-NNd7PXa0w9ZyYD5cUSi:bpc9w16) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/batcheval/eval_context.go#L92)):*
> ```Go
> 	GetMaxSplitQPS(context.Context) (float64, bool)
> 
> 	// GetMaxSplitCPU returns the Replicas maximum request cpu/s rate over a
> ```

"Replica's"

Same thing above as well, I guess.
___
*[`pkg/kv/kvserver/split/decider.go` line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd7chr1EOTyC3KPYtB:-NNd7chr1EOTyC3KPYtC:b-zggfqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/split/decider.go#L59)):*
> ```Go
> 	// NewLoadBasedSplitter returns a new LoadBasedSplitter that may be used to
> 	// find the midpoint based on recorded load.
> 	NewLoadBasedSplitter(time.Time) LoadBasedSplitter
> ```

nit: if this can construct LoadBasedSplitters it feels more like a "factory" than a "config".
___
*[`pkg/roachpb/api.proto` line 2119 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd7tSlCRwZd8kjKgXW:-NNd7tSlCRwZd8kjKgXX:b-z51ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/roachpb/api.proto#L2119)):*
> ```protobuf
>   // replica serving the RangeStats request has not been the leaseholder long
>   // enough to have recorded CPU rates for at least a full measurement period.
>   // In such cases, the reciipient should not consider the CPU value reliable
> ```

`s/reciipient/recipient/`

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96128)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`-- commits` line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd6Hk376y32QMhFZCP):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How was the 250ms number evaluated? Should we run an experiment like Andrew did in https://github.com/cockroachdb/cockroach/pull/39687 to tune it to find the right balance between batching and concurrency?
</blockquote></details>

Mostly eyeballed this one whilst running allocbench. I tried a few different values and looked at the this metric: https://github.com/kvoli/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/store_rebalancer.go#L48-L48 which indicates that there weren't any available actions but the store was overfull.  I verified the number was "reasonable" by using it for tpcc and tpce - where the 

Note the 250ms number is only for request cpu (not raft). Here's a comparison of splits running TPCE between master/this branch with 250ms:



The same for allocbench (5 runs of each type, order is `r=0/access=skew`, `r=0/ops=skew`, `r=50/ops=skew`, `r=95/access=skew`, `r=95/ops=skew`.



I added a todo for now with the intention to address this in the next 2 weeks.
___
*[`pkg/kv/kvserver/batcheval/cmd_range_stats.go` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd5mYsA74YjjQzIT0k:-NNidwKl3dlezzI4w1Lf:bn0db0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b23943c2ab92fd8a7fd60e9195b96c6fc04dec94/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L54)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to keep setting this to true for another release?
</blockquote></details>

Probably, If a <23.1 node sees this flag not being set (default=false?), I'm guessing that range merging will occur until the version is finalized.

Updated this to be set. Updated the TODO to stop setting the field in 23.2.
___
*[`pkg/kv/kvserver/batcheval/cmd_range_stats.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd763XDanIdRcB--4q:-NNiYGM03BR_lw2aHLXl:b-ka6e6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L54)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this possible if the cluster switched from QPS-based splitting to CPU-based splitting between the calls to `GetMaxSplitQPS` and `GetMaxSplitCPU` above?
</blockquote></details>

It is possible. However in that case, there is a "warmup" period for the decider stats so they would both be !OK.

When the objective changes, every decider is reset. It will then be 5 minutes before the max value returned from a decider is ok. So I think this should be okay.


https://github.com/kvoli/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/kvserverbase/base.go#L207-L209
___
*[`pkg/kv/kvserver/batcheval/eval_context.go` line 92 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd7PXa0w9ZyYD5cUSh:-NNiXwZj6SwbNfsMGk57:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/batcheval/eval_context.go#L92)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"Replica's"

Same thing above as well, I guess.
</blockquote></details>

Updated
___
*[`pkg/kv/kvserver/split/decider.go` line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd7chr1EOTyC3KPYtB:-NNidZsiBSk8tXKn8vJK:bqlgdif) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/split/decider.go#L59)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: if this can construct LoadBasedSplitters it feels more like a "factory" than a "config".
</blockquote></details>

That's fair - it seemed convenient to bundle these methods into a config. I'm not sure if factory suits either here due to the config methods also being present.
___
*[`pkg/roachpb/api.proto` line 2119 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd7tSlCRwZd8kjKgXW:-NNiY9ucD-NLvcZ3_8-3:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/roachpb/api.proto#L2119)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/reciipient/recipient/`
</blockquote></details>

Updated

**Review by nvb — APPROVED** [review]
:lgtm: once [the prereq PR](https://github.com/cockroachdb/cockroach/pull/96127) is merged.

> Reviewed 1 of 3 files at r7, 18 of 22 files at r8, 21 of 21 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-:-NNnisd82fn3zjw_haHL:b-erou6e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`-- commits` line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd6Hk376y32QMhFZCP):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Mostly eyeballed this one whilst running allocbench. I tried a few different values and looked at the this metric: https://github.com/kvoli/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/store_rebalancer.go#L48-L48 which indicates that there weren't any available actions but the store was overfull.  I verified the number was "reasonable" by using it for tpcc and tpce - where the 

Note the 250ms number is only for request cpu (not raft). Here's a comparison of splits running TPCE between master/this branch with 250ms:



The same for allocbench (5 runs of each type, order is `r=0/access=skew`, `r=0/ops=skew`, `r=50/ops=skew`, `r=95/access=skew`, `r=95/ops=skew`.



I added a todo for now with the intention to address this in the next 2 weeks.

</blockquote></details>

Do you mind opening a github issue that follows from the TODO, just so that we can tag something as a release blocker?
___
*[`pkg/kv/kvserver/batcheval/cmd_range_stats.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd763XDanIdRcB--4q:-NNnhyQi7GMmyvhfWtsW:b8e09jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L54)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It is possible. However in that case, there is a "warmup" period for the decider stats so they would both be !OK.

When the objective changes, every decider is reset. It will then be 5 minutes before the max value returned from a decider is ok. So I think this should be okay.


https://github.com/kvoli/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/kvserverbase/base.go#L207-L209
</blockquote></details>

I guess it still seems strange that we try to assert this. Would there be a downside to letting both be set in the rare case of an (absurdly long) race? Is it important that we promise to consumers of this API that only one value will be set? Or is it only important that we promise that at least one will be set (unless both are warming up)?
___
*[`pkg/kv/kvserver/split/decider.go` line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd7chr1EOTyC3KPYtB:-NNnibE6Ak0_BqsQ0Pe3:by694g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/split/decider.go#L59)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

That's fair - it seemed convenient to bundle these methods into a config. I'm not sure if factory suits either here due to the config methods also being present.
</blockquote></details>

Ack. Config seems fine then. Unless `LoadSplitThing` strikes your fancy.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96128)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`-- commits` line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd6Hk376y32QMhFZCP):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you mind opening a github issue that follows from the TODO, just so that we can tag something as a release blocker?
</blockquote></details>

Opened issue https://github.com/cockroachdb/cockroach/issues/96869 and linked in the TODO.
___
*[`pkg/kv/kvserver/batcheval/cmd_range_stats.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd763XDanIdRcB--4q:-NNqW2OL2ALI8vBz8iRT:bthoyn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L54)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I guess it still seems strange that we try to assert this. Would there be a downside to letting both be set in the rare case of an (absurdly long) race? Is it important that we promise to consumers of this API that only one value will be set? Or is it only important that we promise that at least one will be set (unless both are warming up)?
</blockquote></details>

I think the promise that **at most one** will be set is important to the merge queue, I don't think it is that important to other consumers of the API. Perhaps it is fine to just have the assertion on the other side. There is a sort of liveness property that eventually a value must be set for merges to make progress.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96128)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/batcheval/cmd_range_stats.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd763XDanIdRcB--4q:-NNrQ0Cd-SdSEfo3NWuF:b-an0nqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L54)):*
> Perhaps it is fine to just have the assertion on the other side.

Yeah, that's kind of what I was getting at. But even then, why assert? I would expect the logic to be something like the following, but I'm probably missing some complexity:
```go
switch rebalance_objective:
case qps:
    if !lhsQPS.ok || !rhcQPS.ok {
        return // don't merge
    }
    ...
case cpu:
    if !lhsCPU.ok || !rhcCPU.ok {
        return // don't merge
    }
    ...
}
```

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96128)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvserver/batcheval/cmd_range_stats.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-NNd763XDanIdRcB--4q:-NNrby3a4yL0TCtLthGg:b-7ko1w8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7206595e95e40b107755180a9438dd9b8bf0fd9/pkg/kv/kvserver/batcheval/cmd_range_stats.go#L54)):*
> Yeah, that's kind of what I was getting at. But even then, why assert? I would expect the logic to be something like the following, but I'm probably missing some complexity:

I think the scenario I'm trying to avoid is the upgrade case, where some node doesn't populate CPU because it is running an earlier version but it then passes the >= 0 check by being the default value (0). This problem seems solved by first checking the split objective. It was also a bit cumbersome to have two stats for each side moving around in the process loop - for formatting and resetting after merge.

I've updated to remove the assertions and just check the objective manager to ensure things work.

**Review by nvb — COMMENTED** [review]
:lgtm:

> Reviewed 21 of 21 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96128#-:-NNs8RBh0EiWuNAfGdVQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Comment by kvoli** [comment]
rebased with https://github.com/cockroachdb/cockroach/pull/96921 to fix CI.

**Comment by kvoli** [comment]
rebased with #96946 to fix extended CI

**Comment by kvoli** [comment]
bors r=nvanbenschoten

**Pull request merged**
