### PR TITLE
ui: Upgrade to Webpack@^4 and babel@^7 versions

### PR DESCRIPTION
**Pull request by koorosh**
Depends on PR: https://github.com/cockroachdb/yarn-vendored/pull/12

With these changes, webpack and related dev dependencies are upgraded to the latest versions.
Introduced changes do not affect build process but has made one change for development 'watch' mode to optimize building speed.

- Upgrade to ver 4 requires to specify explicitly 'mode' option to improve
performance for dev environment, because it is falls to 'production' mode
in case nothing is specified.
- Add ignore paths (node_modules) for processing .ts because 'include' path
is the top level directory (not 'src').

Release note: None

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43685)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto, @Koorosh, and @vilterp)

___
*[pkg/ui/package.json, line 96 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43685#-LyVRa146LqGZ1tUTs6K:-LyVRa15CLtZRkjg4ozY:bszwzpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5004973a53caa4667391e7a534abca50308bc96/pkg/ui/package.json#L96)):*
> ```JSON
>     "karma-sinon": "^1.0.5",
>     "karma-sourcemap-loader": "^0.3.7",
>     "karma-webpack": "^4.0.2",
> ```

@koorosh I'm having issues running `yarn run karma start` locally after pulling down this change. Does it run on your machine? Or am I missing another karma step?

**Comment by Koorosh** [comment]
Fixed test runner by downgrading `karma-webpack` version due to existing issues in latest versions: https://github.com/webpack-contrib/karma-webpack/issues/382

**Comment by dhartunian** [comment]
I just retriggered a build on this PR with the updated Node 12 Docker builder image. Let's see if that helps it pass.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43685)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto, @dhartunian, and @vilterp)

___
*[pkg/ui/package.json, line 96 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43685#-LyVRa146LqGZ1tUTs6K:-LzGwXhD4-u9HxLaJuTp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5004973a53caa4667391e7a534abca50308bc96/pkg/ui/package.json#L96)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

@koorosh I'm having issues running `yarn run karma start` locally after pulling down this change. Does it run on your machine? Or am I missing another karma step?
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]
> Reviewed 1 of 1 files at r9, 1 of 3 files at r11, 1 of 1 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43685)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto, @dhartunian, and @vilterp)

**Pull request merged**
