### PR TITLE
[WIP] COCKROACH_TRACE_SQL

### PR DESCRIPTION
**Pull request by petermattis**
Add support tracing all SQL statements via the COCKROACH_TRACE_SQL env
variable. When the transaction associated with the statement commits or
aborts the trace is output to the log file.

In the logs this looks like:

```
I160731 21:57:58.740716 sql/session.go:227  b85d7043-27e9-47df-8813-6f1d775be699
     0.021ms      0.000ms    executing 1/1: BEGIN TRANSACTION
     0.027ms      0.006ms    BEGIN done
     0.300ms      0.273ms    executing 1/1: SAVEPOINT cockroach_restart
     0.447ms      0.147ms    preparing: SELECT id, balance FROM accounts WHERE id IN ($1, $2)
     0.777ms      0.330ms    executing 1/1: SELECT id, balance FROM accounts WHERE id IN ($1, $2)
     0.877ms      0.100ms    meta descriptor lookup
     0.881ms      0.005ms    looked up range descriptor from cache
     0.894ms      0.012ms    sending RPC to [/Table/50, /Max)
     1.104ms      0.211ms    reply error: key range /Table/51/1/526-/Table/51/1/527 outside of bounds of range /Table/50-/Table/51
     1.130ms      0.025ms    evicting cached range descriptor with 2 replacements
     1.132ms      0.003ms    meta descriptor lookup
     1.135ms      0.003ms    looked up range descriptor from cache
     1.145ms      0.010ms    sending RPC to [/Table/51, /Max)
     1.228ms      0.083ms        node 1
     1.232ms      0.003ms        read has no clock uncertainty
     1.238ms      0.006ms        executing 2 requests
     1.245ms      0.007ms        read-only path
     1.247ms      0.002ms        command queue
     1.485ms      0.239ms    SELECT 0 done
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8166)

### CODE REVIEW

**Comment by petermattis** [comment]
Turning this on causes a 10-15% slowdown in `zerosum`, though it was very useful in tracking down the performance problems I was debugging recently.

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[util/tracing/format.go, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO5ZX0ByTdPVl_3AC-z:-KO5ZX0ByTdPVl_3AC0-:-555908896) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/util/tracing/format.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

s/2015/2016/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-:-KO5_PcvEnNLpkt3ULQw:676834233)*

**Comment by petermattis** [comment]
Added another commit which introduces `log.Tracef`.

---

Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[util/tracing/format.go, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO5ZX0ByTdPVl_3AC-z:-KO5vn4eBjVU3FH-5lgE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/util/tracing/format.go#L1)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/2015/2016/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-:-KO5vny5Kdqjrww_z_qh:-249089993)*

**Comment by andreimatei** [comment]
LGTM

---

Review status: 0 of 18 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/session.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO5q_8_vMkTiaLYNqag:-KO5q_8aQ7IJwS3qkLlh:1517041400) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/sql/session.go#L40)):*
> ```Go
> )
> 
> var traceSQL = envutil.EnvOrDefaultBool("trace_sql", false)
> ```

can we make this a session member? Even if we still initialize it from an env var.

---

*[sql/session.go, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO5qkTU7HZLE7jYBaRa:-KO5qkTU7HZLE7jYBaRb:-1104435896) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/sql/session.go#L60)):*
> ```Go
> 	Trace                 trace.Trace
> 	context               context.Context
> 	cancel                func()
> ```

please comment this `cancel`. Or rename to `finalizeContext`?

---

*[sql/session.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO66M6asy53OQvDQGXl:-KO66M6asy53OQvDQGXm:1323253084) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/sql/session.go#L113)):*
> ```Go
> // transaction it returns the transaction context, otherwise it returns the
> // session context.
> func (s *Session) Context() context.Context {
> ```

it seems funky to me to reach inside the KV txn to get a context. Why isn't `s.context` always good?

---

*[util/log/trace.go, line 39 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO67c8bTyzyvlgHASMK:-KO67c8cQSiDGwe6za3L:-1604599895) ([raw file](https://github.com/cockroachdb/cockroach/blob/857a54a470a13247a872d3170551af3a0cf64a3d/util/log/trace.go#L39)):*
> ```Go
> // Tracef looks for an opentracing.Trace in the context and formats and logs
> // the given message to it on success.
> func Tracef(ctx context.Context, format string, args ...interface{}) {
> ```

I'm behind on the evolution of our logging, but should all logging methods (that now take a context) call this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-:-KO67DqWUy8slnBpDHAk:676834233)*

**Comment by petermattis** [comment]
Review status: 0 of 18 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/session.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO5q_8_vMkTiaLYNqag:-KO68u-EPtTCFfFA5Lig:1072973360) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/sql/session.go#L40)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> can we make this a session member? Even if we still initialize it from an env var.
</details>
Not in this PR are some instances of `if traceSQL` that don't have a session context. But 

---

*[sql/session.go, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO5qkTU7HZLE7jYBaRa:-KO69Dwa99m2kp-TbJFA:-192125188) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/sql/session.go#L60)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> please comment this `cancel`. Or rename to `finalizeContext`?
</details>
How about `cancelContext`?

---

*[sql/session.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO66M6asy53OQvDQGXl:-KO69Gzw1ZSKnot1K7y6:755929952) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/sql/session.go#L113)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> it seems funky to me to reach inside the KV txn to get a context. Why isn't `s.context` always good?
</details>
`s.context` won't include the trace (if one exists). The interesting path here is in `Executor.Prepare` where we have a session but not a txn.

---

*[util/log/trace.go, line 39 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO67c8bTyzyvlgHASMK:-KO68gL2m0O1Ha9lwmN0:-591080566) ([raw file](https://github.com/cockroachdb/cockroach/blob/857a54a470a13247a872d3170551af3a0cf64a3d/util/log/trace.go#L39)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I'm behind on the evolution of our logging, but should all logging methods (that now take a context) call this?
</details>
They do. `log.Trace{,f}` are useful when you want to add to the trace but not output to the log.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Comment by tamird** [comment]
Review status: 0 of 18 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/session.go, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO5qkTU7HZLE7jYBaRa:-KO6FUg6sgTcFlyWpbZt:549678071) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/sql/session.go#L60)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> How about `cancelContext`?
</details>
I think `cancel` is fine, but the type should be `context.CancelFunc`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Comment by petermattis** [comment]
Review status: 0 of 18 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/session.go, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO5qkTU7HZLE7jYBaRa:-KO6M2vVBS4GxQ7RQPO4:370089077) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/sql/session.go#L60)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I think `cancel` is fine, but the type should be `context.CancelFunc`
</details>
I don't particularly care about the name. Changed the type to `context.CancelFunc`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Comment by andreimatei** [comment]
Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/session.go, line 113 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO66M6asy53OQvDQGXl:-KO6Qxcmh3AKCiMMxlgb:-1042916880) ([raw file](https://github.com/cockroachdb/cockroach/blob/b194fe1b51c4ae55c8681b66cec7cfb139c22b76/sql/session.go#L113)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s.context` won't include the trace (if one exists). The interesting path here is in `Executor.Prepare` where we have a session but not a txn.
</details>
oh, right, I see.

---

*[util/log/trace.go, line 39 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO67c8bTyzyvlgHASMK:-KO6RE1JGgcXUuhfRwVQ:677880290) ([raw file](https://github.com/cockroachdb/cockroach/blob/857a54a470a13247a872d3170551af3a0cf64a3d/util/log/trace.go#L39)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> They do. `log.Trace{,f}` are useful when you want to add to the trace but not output to the log.
</details>
nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Comment by petermattis** [comment]
Review status: 4 of 18 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[kv/dist_sender.go, line 750 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6MwNj5_DM8Q_LcckV:-KO6_io-8xYgzMW9BPnk:1176054235) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b1d1d50a51489fb740cc33b43e0c6f37a6111d/kv/dist_sender.go#L750)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> does this want to be under an `else`? seems like we'll double-trace at V(1).
</details>
Yep. Done.

---

*[sql/executor.go, line 305 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6N6Xp43SJaMpGXA_L:-KO6aBdXgamA4-wFAMrR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b1d1d50a51489fb740cc33b43e0c6f37a6111d/sql/executor.go#L305)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this should take session.Context() as well, and the below trace call should be in an else to avoid double tracing.
> 
> this pattern seems to repeat in a few places.
</details>
Done.

---

*[sql/executor.go, line 662 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6X4_ycIWGQ42lPTBy:-KO6aDAoJU3-jTY6Mca-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b1d1d50a51489fb740cc33b43e0c6f37a6111d/sql/executor.go#L662)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> another
</details>
Done.

---

*[sql/executor.go, line 940 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6X8yGVfvFfLkwcDC8:-KO6aEDaGX_rMYQppQRi:-333818515) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b1d1d50a51489fb740cc33b43e0c6f37a6111d/sql/executor.go#L940)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what's the story with txnState.tr now?
</details>
That's `x/net/trace` which still exists. This PR isn't addressing that.

---

*[storage/replicate_queue.go, line 153 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6WtGU5JejTccsb7KA:-KO6agkgagj74fq_uWBn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b1d1d50a51489fb740cc33b43e0c6f37a6111d/storage/replicate_queue.go#L153)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> the aforementioned pattern here
</details>
Done.

---

*[storage/split_queue.go, line 117 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6WvRsHT-6uwPtKnfP:-KO6ak0uXSXPKwd8xy8C:542939253) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b1d1d50a51489fb740cc33b43e0c6f37a6111d/storage/split_queue.go#L117)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is just straight up double tracing?
</details>
Only if I replace `s/context.TODO()/ctx/g`. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Comment by tamird** [comment]
Reviewed 8 of 13 files at r7, 5 of 5 files at r8.
Review status: 17 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[kv/dist_sender.go, line 747 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6eFBCJk2TBOq3k-aj:-KO6eFBCJk2TBOq3k-ak:1804753647) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8fd56be2e027eb6bb7a8ca598c51cce06a48610/kv/dist_sender.go#L747)):*
> ```Go
> 			}
> 
> 			log.VTracef(1, ctx, "reply error %s: %s", ba, pErr)
> ```

this now logs as info rather than warning.

---

*[sql/executor.go, line 940 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6X8yGVfvFfLkwcDC8:-KO6dwoCSaBWb98b9_Lp:-299728620) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b1d1d50a51489fb740cc33b43e0c6f37a6111d/sql/executor.go#L940)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> That's `x/net/trace` which still exists. This PR isn't addressing that.
</details>
I know, I was just asking. It's ripe for removal, yeah?

---

*[sql/executor.go, line 663 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6eVWPU2leCpEpJB7t:-KO6eVWPU2leCpEpJB7u:-1996476905) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8fd56be2e027eb6bb7a8ca598c51cce06a48610/sql/executor.go#L663)):*
> ```Go
> 		if log.V(2) {
> 			log.Infof(ctx, "executing %d/%d: %s", i+1, len(stmts), stmt)
> 		} else if traceSQL && txnState.txn != nil {
> ```

no longer need this nil check, i think. perhaps you mean to use txnState.txn.Context though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Comment by petermattis** [comment]
Review status: 16 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[kv/dist_sender.go, line 747 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6eFBCJk2TBOq3k-aj:-KO6gyEKmNWKDbvDKnIT:1401030393) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8fd56be2e027eb6bb7a8ca598c51cce06a48610/kv/dist_sender.go#L747)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this now logs as info rather than warning.
</details>
Yeah, but is that problematic? I'm not quite sure what the point of logging at warning underneath a `log.V(1)` is. I suppose it outputs to a different file, but that didn't seem to justify leaving it.

---

*[sql/executor.go, line 940 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6X8yGVfvFfLkwcDC8:-KO6hLu468hQYidmLXsI:-1300085490) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8b1d1d50a51489fb740cc33b43e0c6f37a6111d/sql/executor.go#L940)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I know, I was just asking. It's ripe for removal, yeah?
</details>
Not quite. `txnState.tr` lives for the lifetime of the session and captures events that occur outside the tracing performed when `traceSQL` is true. We do need to figure out the story with this two tracing systems.

---

*[sql/executor.go, line 663 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6eVWPU2leCpEpJB7t:-KO6hF29ioimC41jTPMa:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8fd56be2e027eb6bb7a8ca598c51cce06a48610/sql/executor.go#L663)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> no longer need this nil check, i think. perhaps you mean to use txnState.txn.Context though.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r9.
Review status: 17 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[kv/dist_sender.go, line 747 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KO6eFBCJk2TBOq3k-aj:-KO6jG6s0xohkv8onRR3:1299762347) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8fd56be2e027eb6bb7a8ca598c51cce06a48610/kv/dist_sender.go#L747)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Yeah, but is that problematic? I'm not quite sure what the point of logging at warning underneath a `log.V(1)` is. I suppose it outputs to a different file, but that didn't seem to justify leaving it.
</details>
Seems fine to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-:-KO6jU-5w5QchWcmiuqr:1417088721)*

**Comment by RaduBerinde** [comment]
*[sql/executor.go, line 327 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KOAay3gKs0sLumyb_-E:-KOAay3hWLpw_ZtnchnF:1856863945) ([raw file](https://github.com/cockroachdb/cockroach/blob/541d0bbed82c51a139a0d3ea0e8e05c49f333e3b/sql/executor.go#L327)):*
> ```Go
> 	// Prepare needs a transaction because it needs to retrieve db/table
> 	// descriptors for type checking.
> 	txn := client.NewTxn(session.Context(), *e.ctx.DB)
> ```

Hm, I had #8147 out where I was plumbing all the logs to use `ctx` - using `ctx` here did not work properly? If we are not passing a useful `ctx`, should we remove it as an argument for the function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Comment by RaduBerinde** [comment]
*[sql/executor.go, line 327 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KOAay3gKs0sLumyb_-E:-KOAdpp-ljQMdmuwKdxa:-884973963) ([raw file](https://github.com/cockroachdb/cockroach/blob/541d0bbed82c51a139a0d3ea0e8e05c49f333e3b/sql/executor.go#L327)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Hm, I had #8147 out where I was plumbing all the logs to use `ctx` - using `ctx` here did not work properly? If we are not passing a useful `ctx`, should we remove it as an argument for the function?
</details>
Though we're still using the passed `ctx` (and not `session.Context()`) in `ExecuteStatements` so I'm a bit confused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Comment by RaduBerinde** [comment]
*[sql/pgwire/v3.go, line 192 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KOAeb6TtrJ1ExnVWhSb:-KOAeb6TtrJ1ExnVWhSc:191445395) ([raw file](https://github.com/cockroachdb/cockroach/blob/541d0bbed82c51a139a0d3ea0e8e05c49f333e3b/sql/pgwire/v3.go#L192)):*
> ```Go
> 
> func (c *v3Conn) serve(authenticationHook func(string, bool) error) error {
> 	ctx := c.session.Context()
> ```

Ah, I believe this change means that this context will eventually make it to functions like `Prepare`, `ExecuteStatements`. So `ctx` should be the same with `session.Context()` in these functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Comment by petermattis** [comment]
Review status: 4 of 18 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/executor.go, line 327 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KOAay3gKs0sLumyb_-E:-KOAqeJhtNCXwfsUhiMO:-1580904630) ([raw file](https://github.com/cockroachdb/cockroach/blob/541d0bbed82c51a139a0d3ea0e8e05c49f333e3b/sql/executor.go#L327)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Though we're still using the passed `ctx` (and not `session.Context()`) in `ExecuteStatements` so I'm a bit confused
</details>
I probably didn't plumb usage of `session.Context()` enough. Our usage of contexts in SQL seemed a bit haphazard. I haven't taken a look at your new PR yet, though.

---

*[sql/pgwire/v3.go, line 192 \[r12\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166#-KOAeb6TtrJ1ExnVWhSb:-KOAqzUSGeaowKNQayQa:-435504834) ([raw file](https://github.com/cockroachdb/cockroach/blob/541d0bbed82c51a139a0d3ea0e8e05c49f333e3b/sql/pgwire/v3.go#L192)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah, I believe this change means that this context will eventually make it to functions like `Prepare`, `ExecuteStatements`. So `ctx` should be the same with `session.Context()` in these functions.
</details>
Most of the time. `session.Context()` either returns the pgwire context or the transaction context if a transaction is active. The transaction context is preferable so that any log writes will get traced appropriately. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8166)*

**Pull request merged**
