### PR TITLE
authors: add nickvigilante to authors

### PR DESCRIPTION
**Pull request by nickvigilante**
Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm! to merge this, write a new comment with a line containing `bors r+`

**Comment by jlinder** [comment]
bors r+

fyi @rafiss, our practice now is to give bors ability to engineers only. We request that others ask an engineer to merge the PR for them.

**Comment by rafiss** [comment]
Thanks @jlinder I didn't realize that!

**Comment by jlinder** [comment]
No worries. I don't think we really announced it per-se, though we've been doing that for at least a year.

**Comment by jlinder** [comment]
bors r+

logictest failures. this PR doesn't change any of them. Must be a flake.

**Pull request merged**
