### PR TITLE
sql: support deadlock_timeout session variable

### LINKED ISSUE #116305: sql/kv: implement `deadlock_timeout` session variable
Postgres exposes a session variable called `deadlock_timeout`, which is described here: https://www.postgresql.org/docs/10/runtime-config-locks.html#GUC-DEADLOCK-TIMEOUT.

> This is the amount of time, in milliseconds, to wait on a lock before checking to see if there is a deadlock condition. The check for deadlock is relatively expensive, so the server doesn't run it every time it waits for a lock. We optimistically assume that deadlocks are not common in production applications and just wait on the lock for a while before checking for a deadlock. Increasing this value reduces the amount of time wasted in needless deadlock checks, but slows down reporting of real deadlock errors. The default is one second (1s), which is probably about the smallest value you would want in practice. On a heavily loaded server you might want to raise it. Ideally the setting should exceed your typical transaction time, so as to improve the odds that a lock will be released before the waiter decides to check for deadlock. Only superusers can change this setting.

CockroachDB has a similar configuration (`kv.lock_table.deadlock_detection_push_delay`), but it is only exposed as a cluster setting.

We should add support for the session variable as well, to provide more configurability at a per-session level and for PG compatability.

The implementation work will roughly mirror 38da713040a9f19f994420f73d11bc36caf73379. Namely, we'll add the session variable with a default value of 0, plumb it down to the `lockTableWaiter`, and use it instead of the cluster setting when configured.

----

This is related to https://github.com/cockroachdb/cockroach/issues/95771, as a handful of the `pg_isolation_regress` tests attempt to configure the `deadlock_timeout` session variable.

Jira issue: CRDB-34567

Epic CRDB-37617

### PR DESCRIPTION
**Pull request by iskettaneh**
This commit introduces a new `deadlock_timeout` field to the sql session If set, it will be used as the time to wait on a lock before pushing the lock holder for deadlock detection. If not set, the cluster-wide setting:
kv.lock_table.deadlock_detection_push_delay will be used as the timeout.

Based on: #127430

Fixes: #116305

Release note (sql change): The deadlock_timeout session variable is now supported. The configuration can be used to specify the time to wait on a lock before pushing the lock holder for deadlock detection. It can be set at session granularity.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128506)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh)

___
*[`pkg/sql/exec_util.go` line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3nE3Q23YD3MG-qrij6:-O3nE3Q23YD3MG-qrij7:b-py68l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a061452e7769eba7cd0103035a4298e0d2df7cfc/pkg/sql/exec_util.go#L478)):*
> ```Go
> 	settings.WithPublic)
> 
> var clusterDeadlockTimeout = settings.RegisterDurationSetting(
> ```

I think someone from SQL foundations can help confirm, but I think we no longer have these cluster wide settings associated with session variables anymore. Instead, the idea is you configure such defaults on a per-role basis. 

cc @rafiss
___
*[`pkg/sql/tests/deadlock_test.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3nEwBy-qcoF-TuSwRj:-O3nEwBy-qcoF-TuSwRk:b-3b2stv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a061452e7769eba7cd0103035a4298e0d2df7cfc/pkg/sql/tests/deadlock_test.go#L32)):*
> ```Go
> // and the cluster setting `deadlock_detection_push_delay` work as expected in
> // case there was a deadlock.
> func TestDeadlockDetection(t *testing.T) {
> ```

Instead of this, can we write this as a logic test instead? 
___
*[`pkg/sql/tests/deadlock_test.go` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3nF2GG5ETssJ6zUa36:-O3nF2GG5ETssJ6zUa37:bluq7qd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a061452e7769eba7cd0103035a4298e0d2df7cfc/pkg/sql/tests/deadlock_test.go#L124)):*
> ```Go
> 		}
> 
> 		require.GreaterOrEqual(t, t2.Sub(t1), tc.minDeadlockDetectionDuration)
> ```

Instead of this, we should turn on tracing these the test and assert on the trace instead. This should be doable in a logic test, I think.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128506)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/sql/tests/deadlock_test.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3nEwBy-qcoF-TuSwRj:-O3nGCks2YnARfWzGujb:bcn8xa2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a061452e7769eba7cd0103035a4298e0d2df7cfc/pkg/sql/tests/deadlock_test.go#L32)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of this, can we write this as a logic test instead?
</blockquote></details>

Do you have an example of a logic test that causes a deadlock at the SQL level? I kinda struggled with that because when a transaction blocks, I didn't know how to switch to another transaction and cause a deadlock.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128506)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[`pkg/sql/exec_util.go` line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3nE3Q23YD3MG-qrij6:-O3rOHSBBBPHurXxZ6dB:b-od74a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a061452e7769eba7cd0103035a4298e0d2df7cfc/pkg/sql/exec_util.go#L478)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think someone from SQL foundations can help confirm, but I think we no longer have these cluster wide settings associated with session variables anymore. Instead, the idea is you configure such defaults on a per-role basis. 

cc @rafiss
</blockquote></details>

I removed this and added the default directly in the vars.go file. I believe this is what you meant?
___
*[`pkg/sql/tests/deadlock_test.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3nEwBy-qcoF-TuSwRj:-O3rOOHN1Y-GEj0N_WTe:b-euxgf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a061452e7769eba7cd0103035a4298e0d2df7cfc/pkg/sql/tests/deadlock_test.go#L32)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

Do you have an example of a logic test that causes a deadlock at the SQL level? I kinda struggled with that because when a transaction blocks, I didn't know how to switch to another transaction and cause a deadlock.
</blockquote></details>

Since we need two transactions, and we don't know which one of them will be aborted, I did it as a normal test to make it easy to succeed regardless of which transaction was aborted.
___
*[`pkg/sql/tests/deadlock_test.go` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3nF2GG5ETssJ6zUa36:-O3rOd5_DnRGzNXzKcwt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a061452e7769eba7cd0103035a4298e0d2df7cfc/pkg/sql/tests/deadlock_test.go#L124)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of this, we should turn on tracing these the test and assert on the trace instead. This should be doable in a logic test, I think.
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
the SQL parts of the change lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-:-O3rQOfdDjnyy3ffxx4w:b7cdu9b)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`docs/generated/settings/settings.html` line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3rQHab1eLjOT52EaK9:-O3rQHac98k2CfMJCfez:b-tas91q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9d6e442e451a4e1a3b5d963a83386d281202af1/docs/generated/settings/settings.html#L215)):*
> ```HTML
> <tr><td><div id="setting-sql-defaults-cost-scans-with-default-col-size-enabled" class="anchored"><code>sql.defaults.cost_scans_with_default_col_size.enabled</code></div></td><td>boolean</td><td><code>false</code></td><td>setting to true uses the same size for all columns to compute scan cost<br/>This cluster setting is being kept to preserve backwards-compatibility.<br/>This session variable default should now be configured using <a href="alter-role.html"><code>ALTER ROLE... SET</code></a></td><td>Serverless/Dedicated/Self-Hosted</td></tr>
> <tr><td><div id="setting-sql-defaults-datestyle" class="anchored"><code>sql.defaults.datestyle</code></div></td><td>enumeration</td><td><code>iso, mdy</code></td><td>default value for DateStyle session setting [iso, mdy = 0, iso, dmy = 1, iso, ymd = 2]<br/>This cluster setting is being kept to preserve backwards-compatibility.<br/>This session variable default should now be configured using <a href="alter-role.html"><code>ALTER ROLE... SET</code></a></td><td>Serverless/Dedicated/Self-Hosted</td></tr>
> <tr><td><div id="setting-sql-defaults-deadlock-timeout" class="anchored"><code>sql.defaults.deadlock_timeout</code></div></td><td>duration</td><td><code>0s</code></td><td>default value for the deadlock_timeout; default value for the deadlock_timeout session setting; controls the duration to wait on a lock before pushing the lock holder for deadlock detection<br/>This cluster setting is being kept to preserve backwards-compatibility.<br/>This session variable default should now be configured using <a href="alter-role.html"><code>ALTER ROLE... SET</code></a></td><td>Serverless/Dedicated/Self-Hosted</td></tr>
> ```

nit: these cluster settings docs should be reverted now that we've removed the cluster setting from this PR

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-:-O3sspMECS9q5d8E-s9x:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @iskettaneh and @rafiss)

___
*[`pkg/sql/exec_util.go` line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3nE3Q23YD3MG-qrij6:-O3sruDKEnGm_qqXqEYl:b-6meuio) ([raw file](https://github.com/cockroachdb/cockroach/blob/a061452e7769eba7cd0103035a4298e0d2df7cfc/pkg/sql/exec_util.go#L478)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

I removed this and added the default directly in the vars.go file. I believe this is what you meant?
</blockquote></details>

Yup, that's what I meant. Thanks!
___
*[`pkg/sql/tests/deadlock_test.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3nEwBy-qcoF-TuSwRj:-O3ssM6o2ZRXUvAv-ckt:b-oobamw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a061452e7769eba7cd0103035a4298e0d2df7cfc/pkg/sql/tests/deadlock_test.go#L32)):*
> Do you have an example of a logic test that causes a deadlock at the SQL level? I kinda struggled with that because when a transaction blocks, I didn't know how to switch to another transaction and cause a deadlock.

Discussed offline. 

> Since we need two transactions, and we don't know which one of them will be aborted, I did it as a normal test to make it easy to succeed regardless of which transaction was aborted.

That's a good point. Not super important, but I think there's ways to use regex in logic tests to account for this. 
___
*[`pkg/sql/tests/deadlock_test.go` line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128506#-O3ss5TNCqm08FZxQj_P:-O3ss5TO8oFuOTHpLedm:bei02dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43d7f07ecbcfd2ea76e8c34d591d86c84f10bf2/pkg/sql/tests/deadlock_test.go#L89)):*
> ```Go
> 		require.NoError(t, err)
> 
> 		sql.Exec(t, "SET tracing = kv")
> ```

nit: Instead of doing this, consider using the `WithStatementTrace` testing knob instead. A bunch of tests in `followerreads_test.go` make use of this, if you're looking for an inspiring example.

**Pull request merged**
