### PR TITLE
roachprod: remove support for spinning up cassandra clusters

### PR DESCRIPTION
**Pull request by alan-mas**
When working on #47567, we discovered that the cassandra cluster support is no longer used and can be removed. This commit removes cassandra cluster support. 

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
I think we could safely remove `cassandra.go` and everything that depends on it. I doubt anyone has used it in a long time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-:-MYtSbWS7ENlJVzViLMq:b-w66cr1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder)

**Review by jlinder — CHANGES_REQUESTED** [review]
Suggestion for the commit message (and the PR title + description):

```
roachprod: remove support for spinning up cassandra clusters

When working on #47567, we discovered that the cassandra cluster support is no longer used and can be removed. This commit removes cassandra cluster support.
```

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-:-MZTJApLCO6DjSML0tUg:b-2v52j6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alan-mas)

___
*[pkg/cmd/roachprod/main.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-M_TK9a11rf6_zLriG7a:-M_TK9a11rf6_zLriG7b:bzh2spt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9652313e313ee14ccf123d04700eecbdf5bdf9/pkg/cmd/roachprod/main.go#L173)):*
> ```Go
> 			}
> 		}
> 	case "cassandra":
> ```

With removing `cassandra` as a cluster type, there is no need for the `switch clusterType` statement and no need for the `clusterType` field (defined on about line 90 above). 
___
*[pkg/testutils/lint/lint_test.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-M_TLmle8qDEd_fcGTvQ:-M_TLmle8qDEd_fcGTvR:b-7kckm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e775292782e401f5281d52bc322870b9144e1ec9/pkg/testutils/lint/lint_test.go#L215)):*
> ```
> 			stream.GrepNot(`cassandra\.go`),
> 			stream.GrepNot(`cassandra_yaml\.go`),
> ```
Why are these lines necessary?
___
*[pkg/testutils/lint/lint_test.go, line 1650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-M_TLRR4160YNpMy-nyB:-M_TLRR4160YNpMy-nyC:b-lqvpig) ([raw file](https://github.com/cockroachdb/cockroach/blob/e775292782e401f5281d52bc322870b9144e1ec9/pkg/testutils/lint/lint_test.go#L1650)):*
> ```Go
> 				// TODO (alanmas): Remove this line after refactoring ssh.go
> 				// as now it is produccing "func is unused" errors.
> 				stream.GrepNot(`pkg/cmd/roachprod/ssh/ssh.go`),
> ```

I'd recommend just removing the functions that are unused from `pkg/cmd/roachprod/ssh/ssh.go` in this PR.

**Comment by alan-mas** [comment]
> _[pkg/testutils/lint/lint_test.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-M_TLmle8qDEd_fcGTvQ:-M_TLmle8qDEd_fcGTvR:b-7kckm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e775292782e401f5281d52bc322870b9144e1ec9/pkg/testutils/lint/lint_test.go#L215)):_
> 
> > ```
> > 			stream.GrepNot(`cassandra\.go`),
> > 			stream.GrepNot(`cassandra_yaml\.go`),
> > ```
> 
> Why are these lines necessary?

If I do not add those lines go lint test failed as it goes and checks if the file exists:
```
=== CONT  TestLint/TestCopyrightHeaders
    lint_test.go:229: open /Users/admin/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/install/cassandra.go: no such file or directory
    lint_test.go:229: open /Users/admin/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/install/cassandra_yaml.go: no such file or directory
```
It might be a better way to avoid this issue that I am missing here.

This is also happening with `pkg/cmd/roachprod/ssh/ssh.go` as we are changing his name to `io.go` with the refactor.

**Review by jlinder — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64029)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alan-mas and @jlinder)

___
*[pkg/testutils/lint/lint_test.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-M_TLmle8qDEd_fcGTvQ:-M_YQ5UQ2HdpNfVYjNHZ:bpoe00p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e775292782e401f5281d52bc322870b9144e1ec9/pkg/testutils/lint/lint_test.go#L215)):*
<details><summary><i>Previously, alan-mas (alanmas) wrote…</i></summary><blockquote>

If I do not add those lines go lint test failed as it goes and checks if the file exists:
```
=== CONT  TestLint/TestCopyrightHeaders
    lint_test.go:229: open /Users/admin/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/install/cassandra.go: no such file or directory
    lint_test.go:229: open /Users/admin/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/install/cassandra_yaml.go: no such file or directory
```
It might be a better way to avoid this issue that I am missing here. @jlinder 

This is also happening with `pkg/cmd/roachprod/ssh/ssh.go` as we are changing his name to `io.go` with the refactor.

</blockquote></details>

I don't know much about how this linter works, but this does not seem like the right fix. Removing files should not make the linter fail. And this particular linter test is for validating files contain the correct copyright headers. My guess would be there is an ordering problem here. Let's look at this together.

**Comment by alan-mas** [comment]
> I don't know much about how this linter works, but this does not seem like the right fix. Removing files should not make the linter fail. And this particular linter test is for validating files contain the correct copyright headers. My guess would be there is an ordering problem here. Let's look at this together.

Just took away the `cassandra`  lines and it is working (not sure why it was failing before):
```
stream.GrepNot(`cassandra\.go`),
stream.GrepNot(`cassandra_yaml\.go`),
```			
The ones related to `ssh.go` it is still failing, but my guess is that, when the PR related to `ssh.go` refactor got approved we can safely remove this line within that PR: `stream.GrepNot(pkg/cmd/roachprod/ssh/ssh.go)`

**Review by jlinder — CHANGES_REQUESTED** [review]
On the `cassandra` lines: excellent.

On the `ssh.go` line, please see my comments in the line in `lint_test.go`.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-:-M_fEdma1ts4XaSd4TNf:b-n35r4o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alan-mas)

___
*[pkg/testutils/lint/lint_test.go, line 1650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-M_TLRR4160YNpMy-nyB:-M_fC3NM1nfPySvaN-IE:bhffpvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e775292782e401f5281d52bc322870b9144e1ec9/pkg/testutils/lint/lint_test.go#L1650)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

I'd recommend just removing the functions that are unused from `pkg/cmd/roachprod/ssh/ssh.go` in this PR.
</blockquote></details>

The intent of `TestStaticCheck` is to tell the developer when code is no longer used so it can be removed. This helps us keep the code base clean. And it's particularly helpful for PRs like this one where we are removing code so we can be sure we remove all the related unused code too. Thus, this PR should remove any functions in `pkg/cmd/roachprod/ssh/ssh.go` that are no longer in use.

**Review by knz — APPROVED** [review]
I rebased the branch manually and fixed up the vendor update for Alan.
I think the PR is fine now. @jlinder do you agree?
I think if we agree it's fine we should merge this soon to prevent another vendor bump from "under" the PR, which would require one of us to re-do the vendor thing again.

> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-:-MacBSmQ8jMxylk3cqKj:b23ghod)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alan-mas)

**Review by jlinder — APPROVED** [review]
Yes, this is ready. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64029#-:-MadSpUX5RJZVOMTlv0E:b-imch1z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @alan-mas)

**Comment by jlinder** [comment]
Thank you for your help with this @knz!

**Comment by alan-mas** [comment]
> Thank you for your help with this @knz!

Agree with James, thank you so much @knz !

**Pull request merged**
