### PR TITLE
workload/ycsb: fix key acknowledgement race conditions

### LINKED ISSUE #37955: roachtest: ycsb/D/nodes=3/cpu=32 failed
SHA: https://github.com/cockroachdb/cockroach/commits/a059c2ed6edf59894885af9371c584b155d5e8f1

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=ycsb/D/nodes=3/cpu=32 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1317022&tab=buildLog

```
The test failed on branch=master, cloud=aws:
	cluster.go:1516,ycsb.go:41,cluster.go:1854,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1317022-ycsb-d-nodes-3-cpu-32:4 -- ./workload run ycsb --init --initial-rows=1000000 --splits=100 --workload=D --concurrency=64 --histograms=logs/stats.json --ramp=1m --duration=10m {pgurl:1-3} returned:
		stderr:
		
		stdout:
		88138.9        88884.0      0.7      1.0      2.2      6.0 read
		   7m25s        0         4623.9         4674.2      1.4      2.0      3.8      5.8 insert
		   7m25s        0        87477.1        88880.8      0.7      1.0      2.1      5.2 read
		   7m26s        0         4528.1         4673.9      1.4      2.0      3.7     10.5 insert
		   7m26s        0        87235.4        88877.1      0.7      1.0      2.2      5.2 read
		   7m27s        0         4586.2         4673.7      1.4      1.9      3.8      6.6 insert
		   7m27s        0        88658.0        88876.7      0.7      1.0      2.1      6.3 read
		   7m28s        0         4654.9         4673.7      1.3      1.8      3.7      6.3 insert
		   7m28s        0        88052.3        88874.8      0.7      1.0      2.1      5.2 read
		Error: Number of pending acknowledgements exceeded window size: 3260932 has been acknowledged, but 2212355 is not acknowledged
		Error:  ssh verbose log retained in /root/.roachprod/debug/ssh_18.216.138.68_2019-05-31T09:25:35Z: exit status 1
		: exit status 1
	cluster.go:1875,ycsb.go:44,ycsb.go:60,test.go:1251: Goexit() was called

```

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
Determining how many times to increment the request generator was
previously a race condition because querying the previous row counter
and the current row counter is not atomic. This logic has been moved
into Acknowledge.

There was a race condition with ramping up workers. If worker that was
ramping up queried and incremented the next row key to insert, but never
inserted it because the ramp context was finished, the row is not
inserted and the row index is not acknowledged. This race condition
causes insert workloads to fail hard because of the addition of
AcknowledgedCounter. Workers will reattempt to insert its previous row
index if the row is not acknowledged.

Release note: None

Fixes: #37955, #37928

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> If worker that was
> ramping up queried and incremented the next row key to insert, but never
> inserted it because the ramp context was finished, the row is not
> inserted and the row index is not acknowledged.

Interesting. Nice find.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-:-LgEUy-H2xfQiBSkp_4f:b-vt1e9k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, @nvanbenschoten, and @petermattis)

___
*[pkg/workload/ycsb/ycsb.go, line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEVguv7tap7He8VPWc:-LgEVguv7tap7He8VPWd:bihv4c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/909f1a368715541e9089da5c681c4b7c9d75947d/pkg/workload/ycsb/ycsb.go#L449)):*
> ```Go
> 	} else if yw.rowCounter.IsAcknowledged(*yw.lastRowIndex) {
> 		*yw.lastRowIndex = atomic.AddUint64(yw.rowIndex, 1) - 1
> 	}
> ```

I found this a bit confusing to understand, though I think it is a correct. Another approach would be for a worker to keep track of a cached insert index to use on the next call to `nextInsertKeyIndex` if a previous insert had failed. Specifically, I'm imagining that you replace `lastRowIndex` with a `nextInsertIndex *uint64 // next insert index to use if non-nil`. The code here would become something like:

```
  if yw.nextInsertIndex != nil {
    result := *yw.nextInsertIndex
    yw.nextInsertIndex = nil
    return result
  }
  return atomic.AddUint64(yw.rowIndex, 1) - 1
```

Then in `doInsert`:

```
	if _, err := yw.insertStmt.ExecContext(ctx, args...); err != nil {
		yw.nextInsertIndex = new(uint64)
		*yw.nextInsertIndex = keyIndex
		return err
	}
```

This seems somewhat more understandable to me, but perhaps that is because it is how I would have done it. Push back if you disagree.

It is unfortunate that this is necessary. I took a quick look at the ramp code and didn't see an easy way to avoid this need, though.
___
*[pkg/workload/ycsb/ycsb.go, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEWkZM-BoJR2-vdlg6:-LgEWkZM-BoJR2-vdlg7:b-f14xlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/909f1a368715541e9089da5c681c4b7c9d75947d/pkg/workload/ycsb/ycsb.go#L480)):*
> ```Go
> 		}
> 		for count > 0 {
> 			if err := yw.requestGen.IncrementIMax(); err != nil {
> ```

This is the only call to `IncrementIMax`. Perhaps adjust the API to take `count` as a parameter. If you look at the implementation you'll see it already has a loop so this works naturally.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37958)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @petermattis)

___
*[pkg/workload/ycsb/ycsb.go, line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEVguv7tap7He8VPWc:-LgEb56p5V_N1spZzITW:bq1t72d) ([raw file](https://github.com/cockroachdb/cockroach/blob/909f1a368715541e9089da5c681c4b7c9d75947d/pkg/workload/ycsb/ycsb.go#L449)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I found this a bit confusing to understand, though I think it is a correct. Another approach would be for a worker to keep track of a cached insert index to use on the next call to `nextInsertKeyIndex` if a previous insert had failed. Specifically, I'm imagining that you replace `lastRowIndex` with a `nextInsertIndex *uint64 // next insert index to use if non-nil`. The code here would become something like:

```
  if yw.nextInsertIndex != nil {
    result := *yw.nextInsertIndex
    yw.nextInsertIndex = nil
    return result
  }
  return atomic.AddUint64(yw.rowIndex, 1) - 1
```

Then in `doInsert`:

```
	if _, err := yw.insertStmt.ExecContext(ctx, args...); err != nil {
		yw.nextInsertIndex = new(uint64)
		*yw.nextInsertIndex = keyIndex
		return err
	}
```

This seems somewhat more understandable to me, but perhaps that is because it is how I would have done it. Push back if you disagree.

It is unfortunate that this is necessary. I took a quick look at the ramp code and didn't see an easy way to avoid this need, though.
</blockquote></details>

Yeah I think your way makes more sense. It also saves a call to `AcknowledgedCounter`. I wasn't too fond with how I did.
___
*[pkg/workload/ycsb/ycsb.go, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEWkZM-BoJR2-vdlg6:-LgEbI0L8cMpqTA7GwHC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/909f1a368715541e9089da5c681c4b7c9d75947d/pkg/workload/ycsb/ycsb.go#L480)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is the only call to `IncrementIMax`. Perhaps adjust the API to take `count` as a parameter. If you look at the implementation you'll see it already has a loop so this works naturally.
</blockquote></details>

Done.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37958)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, @nvanbenschoten, and @petermattis)

___
*[pkg/workload/ycsb/acknowledged_counter.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEc5tuCPMKyjCO8TIS:-LgEc5tuCPMKyjCO8TIT:bjhh105) ([raw file](https://github.com/cockroachdb/cockroach/blob/54397fa5792bf7a255e4f89ded3adcc34018a3a3/pkg/workload/ycsb/acknowledged_counter.go#L76)):*
> ```Go
> 
> // IsAcknowledged returns true if v is acknowledged, false otherwise.
> func (c *AcknowledgedCounter) IsAcknowledged(v uint64) bool {
> ```

This is now unused.
___
*[pkg/workload/ycsb/ycsb.go, line 341 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEc9fgAGd8XwQVpSQH:-LgEc9fgAGd8XwQVpSQI:b-50231k) ([raw file](https://github.com/cockroachdb/cockroach/blob/54397fa5792bf7a255e4f89ded3adcc34018a3a3/pkg/workload/ycsb/ycsb.go#L341)):*
> ```Go
> 			rowIndex:        rowIndex,
> 			rowCounter:      rowCounter,
> 			nextInsertIndex: nil,
> ```

Technically unnecessary as `nextInsertIndex` will default to `nil`. Doesn't hurt, though.
___
*[pkg/workload/ycsb/zipfgenerator.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEcID40KaEi9hcVxVw:-LgEcID52uiF6Im2xj0L:b-fgauur) ([raw file](https://github.com/cockroachdb/cockroach/blob/54397fa5792bf7a255e4f89ded3adcc34018a3a3/pkg/workload/ycsb/zipfgenerator.go#L164)):*
> ```Go
> 		return errors.Errorf("Could not incrementally compute zeta: %s", err)
> 	}
> 	eta := (1 - math.Pow(2.0/float64(z.zipfGenMu.iMax+1-z.iMin), 1.0-z.theta)) / (1.0 - z.zeta2/zetaN)
> ```

Hmm, I think we might need to be doing `iMax += count` before this line. I think I got this wrong in the pebble fork of this code too. Looking at the YCSB official code, the `+1` looks spurious to me. Both here and in `NewZipfGenerator`.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37958)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, @nvanbenschoten, and @petermattis)

___
*[pkg/workload/ycsb/zipfgenerator.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEcID40KaEi9hcVxVw:-LgEe-rUAfHh3f6agTCd:blk6hja) ([raw file](https://github.com/cockroachdb/cockroach/blob/54397fa5792bf7a255e4f89ded3adcc34018a3a3/pkg/workload/ycsb/zipfgenerator.go#L164)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Hmm, I think we might need to be doing `iMax += count` before this line. I think I got this wrong in the pebble fork of this code too. Looking at the YCSB official code, the `+1` looks spurious to me. Both here and in `NewZipfGenerator`. 
</blockquote></details>

`iMax` is inclusive. That explains the `+1`. My other comment still stands. We definitely need to be incrementing `iMax` before the recalculation of `eta`.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37958)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @petermattis)

___
*[pkg/workload/ycsb/acknowledged_counter.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEc5tuCPMKyjCO8TIS:-LgEjZdN-PmIw9WNwK57:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54397fa5792bf7a255e4f89ded3adcc34018a3a3/pkg/workload/ycsb/acknowledged_counter.go#L76)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is now unused.
</blockquote></details>

Done.
___
*[pkg/workload/ycsb/ycsb.go, line 341 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEc9fgAGd8XwQVpSQH:-LgEjfcF8UdYdnb_4g1W:b-vk4q8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/54397fa5792bf7a255e4f89ded3adcc34018a3a3/pkg/workload/ycsb/ycsb.go#L341)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Technically unnecessary as `nextInsertIndex` will default to `nil`. Doesn't hurt, though.
</blockquote></details>

I'll include it for clarity since there's a lot of fields on worker.
___
*[pkg/workload/ycsb/zipfgenerator.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEcID40KaEi9hcVxVw:-LgEjpws5Wx5Wbg_LCPN:b-x3gtbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/54397fa5792bf7a255e4f89ded3adcc34018a3a3/pkg/workload/ycsb/zipfgenerator.go#L164)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`iMax` is inclusive. That explains the `+1`. My other comment still stands. We definitely need to be incrementing `iMax` before the recalculation of `eta`.
</blockquote></details>

Thanks for catching this!

**Review by petermattis — APPROVED** [review]
:lgtm: modulo additional fixes to `IncrementIMax`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-:-LgEoDun0ypgPN-HD8Zp:baq3gte)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/workload/ycsb/zipfgenerator.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEcID40KaEi9hcVxVw:-LgEo4cLAxU0ew39Jum1:b-bp3oxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/54397fa5792bf7a255e4f89ded3adcc34018a3a3/pkg/workload/ycsb/zipfgenerator.go#L164)):*
<details><summary><i>Previously, jeffrey-xiao (Jeffrey Xiao) wrote…</i></summary><blockquote>

Thanks for catching this!
</blockquote></details>

See the pebble PR I just opened for another correction here regarding the call to `computeZetaIncrementally`.

**Review by petermattis — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37958)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/workload/ycsb/zipfgenerator.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgIQHkd8J96bl_wCw5S:-LgIQHkd8J96bl_wCw5T:b-lzwdob) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b39d7d0f2434842b48890a7c3ab82085da54407/pkg/workload/ycsb/zipfgenerator.go#L141)):*
> ```Go
> 	if uz < 1.0 {
> 		result = z.iMin
> 	} else if uz < 1.0+math.Pow(0.5, z.theta) {
> ```

`1.0+math.Pow(0.5, z.theta)` is constant for a particular `ZipfGenerator` instance. I just happened to notice this in passing. Using a pre-computed constant here doubles the speed of `ZipfGenerator.Uint64()`.

@jeffrey-xiao I also started to try and understanding the difference between this zipf generator and the one in `math/rand`. The brief reading I've done suggests that the technique used in `math/rand` is a more recent advancement and preferable. The biggest irritation with `math/rand.Zipf` is that you can only adjust the max value via `NewZipf`. We could fork the code and provide a different interface. The advantages to `math/rand.Zipf` are that it is marginally faster (a benchmark demonstrates this) and adjustment of the bounds by more than one value is a constant time operation. Another advantage is the `v` parameter which allows flattening of the zipf distribution (my understanding is that `ZipfGenerator` has `v == 1`, larger `v` values result in a flatter distribution). There isn't any urgency to switch, but it is sort of a fun side project that I'm hoping you might tackle.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37958)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @nvanbenschoten, and @petermattis)

___
*[pkg/workload/ycsb/zipfgenerator.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgEcID40KaEi9hcVxVw:-LgSg9PbDL0cXQtiEjDM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54397fa5792bf7a255e4f89ded3adcc34018a3a3/pkg/workload/ycsb/zipfgenerator.go#L164)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

See the pebble PR I just opened for another correction here regarding the call to `computeZetaIncrementally`.
</blockquote></details>

Done.
___
*[pkg/workload/ycsb/zipfgenerator.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37958#-LgIQHkd8J96bl_wCw5S:-LgSg9sfDZ1LXuC4Ulft:bxnfdmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b39d7d0f2434842b48890a7c3ab82085da54407/pkg/workload/ycsb/zipfgenerator.go#L141)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`1.0+math.Pow(0.5, z.theta)` is constant for a particular `ZipfGenerator` instance. I just happened to notice this in passing. Using a pre-computed constant here doubles the speed of `ZipfGenerator.Uint64()`.

@jeffrey-xiao I also started to try and understanding the difference between this zipf generator and the one in `math/rand`. The brief reading I've done suggests that the technique used in `math/rand` is a more recent advancement and preferable. The biggest irritation with `math/rand.Zipf` is that you can only adjust the max value via `NewZipf`. We could fork the code and provide a different interface. The advantages to `math/rand.Zipf` are that it is marginally faster (a benchmark demonstrates this) and adjustment of the bounds by more than one value is a constant time operation. Another advantage is the `v` parameter which allows flattening of the zipf distribution (my understanding is that `ZipfGenerator` has `v == 1`, larger `v` values result in a flatter distribution). There isn't any urgency to switch, but it is sort of a fun side project that I'm hoping you might tackle.
</blockquote></details>

I've added a commit for pre-computing `halfPowTheta`. I'll also look into how `math/rand` creates a zipfian generator in a future PR. I'll merge this in for now to fix the failing ycsb roachtests.

**Pull request merged**
