### PR TITLE
sql/parser: add a missing contextual help annotation

### PR DESCRIPTION
**Pull request by knz**
Release note: None

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35573#-:-L_YOSHl-J8qoDTPXawk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter and @mjibson)

**Comment by knz** [comment]
TFYR!

bors r+

**Comment by knz** [comment]
requeue after #35583

**Pull request merged**
