### PR TITLE
sql: disable the streamer for queries which might use internal executor

### LINKED ISSUE #99093: kvclient: v22.2.6: attempting to append refresh spans after the tracked timestamp has moved forward
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://cockroach-labs.sentry.io/issues/4023271542/?referrer=webhooks_plugin

Panic message:

>txn_interceptor_span_refresher.go:687: log.Fatal: attempting to append refresh spans after the tracked timestamp has moved forward. batchTimestamp: 1679379412.106937991,0 refreshedTimestamp: 1679379412.122678360,2
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).importLeafFinalState
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:687
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).UpdateRootWithLeafFinalState
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:1259
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).UpdateRootWithLeafFinalState
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1345
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).pushMeta
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1129
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).Push
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1253
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:189
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:729
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:480
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:307
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:731
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1698
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1421
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1587
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1201
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:696
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2428
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:220
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2050
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2052
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1898
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:857
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | attempting to append refresh spans after the tracked timestamp has moved forward. batchTimestamp: 1679379412.106937991,0 refreshedTimestamp: 1679379412.122678360,2
  | (1) assertion failure
  | Wraps: (2) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).assertRefreshSpansAtInvalidTimestamp
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:646
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).importLeafFinalState
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:686
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).UpdateRootWithLeafFinalState
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:1259
  |   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).UpdateRootWithLeafFinalState
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1345
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).pushMeta
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1129
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).Push
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1253
  |   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:189
  |   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:729
  |   | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:480
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:307
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:731
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1698
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1421
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1587
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1201
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:696
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2428
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:220
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2050
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2052
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1898
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:857
  |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  |   | runtim...

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L686-L688 in pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).importLeafFinalState
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1258-L1260 in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).UpdateRootWithLeafFinalState
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/txn.go#L1344-L1346 in pkg/kv.(*Txn).UpdateRootWithLeafFinalState
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/distsql_running.go#L1128-L1130 in pkg/sql.(*DistSQLReceiver).pushMeta
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/distsql_running.go#L1252-L1254 in pkg/sql.(*DistSQLReceiver).Push
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/execinfra/base.go#L188-L190 in pkg/sql/execinfra.Run
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/execinfra/processorsbase.go#L728-L730 in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/flowinfra/flow.go#L479-L481 in pkg/sql/flowinfra.(*FlowBase).Run
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/colflow/vectorized_flow.go#L306-L308 in pkg/sql/colflow.(*vectorizedFlow).Run
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/distsql_running.go#L730-L732 in pkg/sql.(*DistSQLPlanner).Run
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/distsql_running.go#L1697-L1699 in pkg/sql.(*DistSQLPlanner).PlanAndRun
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/distsql_running.go#L1420-L1422 in pkg/sql.(*DistSQLPlanner).PlanAndRunAll
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L1586-L1588 in pkg/sql.(*connExecutor).execWithDistSQLEngine
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L1200-L1202 in pkg/sql.(*connExecutor).dispatchToExecutionEngine
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L695-L697 in pkg/sql.(*connExecutor).execStmtInOpenState
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L130-L132 in pkg/sql.(*connExecutor).execStmt.func1
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L2427-L2429 in pkg/sql.(*connExecutor).execWithProfiling
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L129-L131 in pkg/sql.(*connExecutor).execStmt
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L219-L221 in pkg/sql.(*connExecutor).execPortal
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L2049-L2051 in pkg/sql.(*connExecutor).execCmd.func2
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L2051-L2053 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1897-L1899 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L856-L858 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/pgwire/conn.go#L727-L729 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
GOROOT/src/runtime/asm_amd64.s#L1593-L1595 in runtime.goexit
</details>

```
pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go in pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).importLeafFinalState at line 687
pkg/kv/kvclient/kvcoord/txn_coord_sender.go in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).UpdateRootWithLeafFinalState at line 1259
pkg/kv/txn.go in pkg/kv.(*Txn).UpdateRootWithLeafFinalState at line 1345
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLReceiver).pushMeta at line 1129
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLReceiver).Push at line 1253
pkg/sql/execinfra/base.go in pkg/sql/execinfra.Run at line 189
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 729
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 480
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 307
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 731
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1698
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1421
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 1587
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1201
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 696
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2428
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 130
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 220
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2050
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2052
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1898
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 857
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 728
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.2.6` |
| Cockroach SHA: | d5a076f2953c0712193b8cbe08bbb682563c5675 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v22.2.6 |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-25797

### LINKED ISSUE #99330: sql: internal error with range lookup joins when streamer is disabled
```sql
CREATE TABLE abc (a INT, b INT, c INT, PRIMARY KEY (a, c));
INSERT INTO abc VALUES (1, 1, 2), (2, 1, 1), (2, NULL, 2);
SET CLUSTER SETTING sql.distsql.use_streamer.enabled = false;
SELECT * FROM (SELECT * FROM (VALUES (-1::INT), (1::INT))) v(x) LEFT LOOKUP JOIN abc ON a < x;
```
on 22.2.6 results in
```
ERROR: unordered spans (/Table/104/1/{!NULL--1} /Table/104/1/{!NULL-1})
```
(this test case is present in `lookup_join` logic test).

This was introduced in 22.2 cycle in #85597, cc @DrewKimball 

Jira issue: CRDB-25820

### PR DESCRIPTION
**Pull request by yuzefovich**
**row: allow for overlapping spans for range lookups**

This commit fixes a bug with range lookup joins when the streamer is disabled. Previously, we could hit an error about "unordered spans" when initializing the fetch for range lookups if batch limits are used. Overlapping and unordered spans are actually expected for range lookups, so this commit simply disables the error check. It also adds an extensive comment for how exactly the fetcher will behave in such scenario.

There is no regression test because it'll be introduced in the following commit (implicitly) and no release note since for the bug to occur the streamer must be disabled (and on 22.2 it would mean non-default config).

Fixes: #99330.

Release note: None

**sql: disable the streamer for queries which might use internal executor**

This commit fixes a possible violation of `kv.Txn` API that was introduced when we enabled the usage of the streamer by default in 22.2.0. Namely, the problem is as follows: the streamer requires the LeafTxn to be used since it can perform reads concurrently with other parts of the execution flow; however, if the flow contains a wrapped `planNode` which is using the internal executor, the query issued by the IE might use the RootTxn. As a result, we might have concurrency between the LeafTxn of the "outer" query and the RootTxn of the "inner" query which is not allowed.

The fix in this commit is "quick" and is disallowing the usage of the streamer in more cases than strictly necessary. In particular: 1) it makes it so that the streamer is not used by the flow that has any `planNode`s (even if they don't use the IE at all and don't interact with the `kv.Txn` otherwise either). Auditing each `planNode` implementation is error-prone, and this "quick" fix should be more reliable. 2) it makes it so that the streamer is disabled for all queries issued by the IE.

The thinking behind the second change is as follows: if the query issued by the IE uses the streamer, then it'll use the LeafTxn. The IE exposes the iterator API, so it might be possible for the user of the IE to keep the iterator "open" while returning the control flow back to the "outer" flow. If that "outer" flow is using the RootTxn, we can have the same concurrency violation with the "paused" IE iterator performing some reads in the streamer.

Overall, this is "not terrible, not great" - we effectively fallback to the pre-22.2 behavior for some types of queries. For the queries that do process a lot of data, the streamer is likely to still be enabled.

Fixes: #99093.
Informs: #99209.

Release note (bug fix): Since 22.2.0 CockroachDB could crash with "attempting to append refresh spans after the tracked timestamp has moved forward" error in some rare cases (most likely when querying `pg_catalog` and `crdb_internal` virtual tables), and this has now been fixed. The workaround before upgrading would be to run `SET CLUSTER SETTING sql.distsql.use_streamer.enabled = false;`.

### CODE REVIEW

**Review by cucaroach — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-:-NRD_lL944dc9LmmX1Ug:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/internal.go` line 722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NRD_DZjCS2Dly2wd7fa:-NRD_DZjCS2Dly2wd7fb:bgxw2dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e47dcf6079878ee9dbc70bb5656ae8453af9036/pkg/sql/internal.go#L722)):*
> ```Go
> 	// executor to avoid possible concurrency with the "outer" query (which
> 	// might be using the RootTxn).
> 	sd.LocalOnlySessionData.StreamerEnabled = false
> ```

Note that even if we remove this internal executors probably won't start using the streamer because the session defaults are init'd properly in all cases until #70888 is fixed.
___
*[`pkg/sql/execinfra/readerbase.go` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NRDZyG6Ao8HSHTuYnZd:-NRDZyG6Ao8HSHTuYnZe:b-jvgu91) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f527aa983114aa3310823e8a4a07894a14649a/pkg/sql/execinfra/readerbase.go#L231)):*
> ```Go
> 
> // useStreamerEnabled determines whether the Streamer API should be used.
> // TODO(yuzefovich): remove this in 23.1.
> ```

Should we add a comment that this now only serves as the default for the session variable?
___
*[`pkg/sql/logictest/testdata/logic_test/lookup_join` line 1104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NRDZEc65pD22O3lo4HM:-NRDZEc65pD22O3lo4HN:b-gzmqit) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e47dcf6079878ee9dbc70bb5656ae8453af9036/pkg/sql/logictest/testdata/logic_test/lookup_join#L1104)):*
> ```
> 1  1  2  1     1  2
> 
> # TODO(yuzefovich): uncomment four queries below once #99330 is resolved.
> ```

Can we add a comment why these don't work w/o streamer?

**Review by yuzefovich — COMMENTED** [review]
I added another commit (because skipping a couple of test cases in `lookup_join` logic test file was insufficient), PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-:-NRESYqPCp4sTfNA0-n2:bta1jeg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @DrewKimball, and @michae2)

___
*[`pkg/sql/internal.go` line 722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NRD_DZjCS2Dly2wd7fa:-NREPqMy0DH2GTFu578b:bc3t9i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e47dcf6079878ee9dbc70bb5656ae8453af9036/pkg/sql/internal.go#L722)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Note that even if we remove this internal executors probably won't start using the streamer because the session defaults are init'd properly in all cases until #70888 is fixed.
</blockquote></details>

Hm, if I uncomment this line, then `TestStreamerDisabledWithInternalExecutorQuery` does find a couple of streamer spans. In particular, this is from the "double-nested" internal query (i.e. the virtual table `crdb_internal.jobs` issues an internal query `crdb-internal-jobs-table`, which on its own issues another internal query `system-jobs-scan`, and it's the latter that is actually using the streamer with this line uncommented out). So perhaps #70888 is only applicable to the first level of nestedness (?).
___
*[`pkg/sql/execinfra/readerbase.go` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NRDZyG6Ao8HSHTuYnZd:-NRERcrp1bwt0LTcYwJB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7f527aa983114aa3310823e8a4a07894a14649a/pkg/sql/execinfra/readerbase.go#L231)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Should we add a comment that this now only serves as the default for the session variable?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/lookup_join` line 1104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NRDZEc65pD22O3lo4HM:-NREP1r3CCC0H0JDA3t_:b9lg7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e47dcf6079878ee9dbc70bb5656ae8453af9036/pkg/sql/logictest/testdata/logic_test/lookup_join#L1104)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Can we add a comment why these don't work w/o streamer?
</blockquote></details>

Added another commit to address the bug.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice fix!

> Reviewed 19 of 19 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-:-NREXlwa5XyribTNdWqi:b-46lt7k)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @michae2, and @yuzefovich)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NRESpEf9-AeayyH8QjH):*
Thanks for fixing this! More motivation to improve range lookup de-duplication for lookup joins, I guess.
___
*[`pkg/sql/row/fetcher.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NREUfLf3d9lwngpulyz:-NREUfLf3d9lwngpulz-:b-95xge9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f9e041594835ebb1c8dcdf6279259a805ddb432/pkg/sql/row/fetcher.go#L113)):*
> ```Go
> 	//
> 	// NOTE: if spansCanOverlap is true and a single span can touch multiple
> 	// ranges, then fetched rows can be intertwined. See the comment on
> ```

[nit] Maybe something like `then fetched rows from different spans can be interspersed with one another` (I was initially confused whether this meant KVs for different rows could be intertwined).
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NREV-6M51RnY4PnXCc-:-NREV-6M51RnY4PnXCc0:bw4xrs8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f9e041594835ebb1c8dcdf6279259a805ddb432/pkg/sql/row/kv_batch_fetcher.go#L323)):*
> ```Go
> // - a single span touches multiple ranges
> // - batch limits are used,
> // then the fetched rows can be intertwined.
> ```

[nit] Similar clarification as above.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-:-NREcZrq-pjsn9j6Gx4p:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach, @DrewKimball, and @michae2)

___
*[`pkg/sql/row/fetcher.go` line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NREUfLf3d9lwngpulyz:-NREcFYj-J9Z3RSACrjw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f9e041594835ebb1c8dcdf6279259a805ddb432/pkg/sql/row/fetcher.go#L113)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Maybe something like `then fetched rows from different spans can be interspersed with one another` (I was initially confused whether this meant KVs for different rows could be intertwined).
</blockquote></details>

Done.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99325#-NREV-6M51RnY4PnXCc-:-NREcMKfDHyVzw606_Mj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f9e041594835ebb1c8dcdf6279259a805ddb432/pkg/sql/row/kv_batch_fetcher.go#L323)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Similar clarification as above.
</blockquote></details>

Done.

**Pull request merged**
