### PR TITLE
rsg: add other kinds of NULL to func args

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

### CODE REVIEW

**Review by rjnn — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29821#-:-LLpgwag8aN7dLtpmv68:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/internal/rsg/rsg.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29821#-LLpgjYYAatu51z4T7ll:-LLpgjYYAatu51z4T7lm:b-4mzg0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a45b80492f9164071c50485129f595b7439d33/pkg/internal/rsg/rsg.go#L240)):*
> ```Go
> 	case 1:
> 		return fmt.Sprintf("NULL::%s", typ)
> 	case 2:
> ```

if it were up to me, I'd up the probability of this one. I honestly think its even more interesting than the bare `NULL` case due to the typechecker folding constants that have NULLs in them, and how important it is to test NULL errors. I'd do 50/50, rather than a 10% chance. But I leave it up to you.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29821)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/internal/rsg/rsg.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29821#-LLpgjYYAatu51z4T7ll:-LLphiTH5CeU5rdQ5l22:b-a54rvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a45b80492f9164071c50485129f595b7439d33/pkg/internal/rsg/rsg.go#L240)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

if it were up to me, I'd up the probability of this one. I honestly think its even more interesting than the bare `NULL` case due to the typechecker folding constants that have NULLs in them, and how important it is to test NULL errors. I'd do 50/50, rather than a 10% chance. But I leave it up to you.
</blockquote></details>

I have https://github.com/mjibson/cockroach/commit/03f508e6fca5130c602356ee0b3a7ba5b0126164 queued up as soon as we fix #29695 which should explicitly address the NULL arguments stuff. I think that will make it ok to leave this at 10% for the `SELECT NULL` case.

**Comment by arjunravinarayan** [comment]
sgtm, you're the expert here!

**Review by rjnn — APPROVED** [review]

**Pull request merged**
