### PR TITLE
json: implement Format on jsonEncoded, fused with decoding

### LINKED ISSUE #119542: json: implement Format directly on jsonEncoded, fused with decoding
`jsonEncoded.Format` currently decodes a `jsonEncoded` format into a `jsonObject` tree and then calls Format on this inflated object. This creates a large amount of short-lived garbage, which we've seen cause performance problems (see profile below).

This shouldn't be necessary. We can implement Format directly on the jsonEncoded object to write into the `*bytes.Buffer` while decoding. Doing so would eliminate the intermediate `JSON` objects. It would also avoid needing to pass through `jsonString` objects, which mandate a []byte->string re-alloc + memcpy.

Screenshot 2024-02-22 at 4 37 28 PM

While here, we may also want to switch the json package from operating on `*bytes.Buffer` to operating on `io.Writer`. We can then use a `*strings.Builder` in `jsonEncoded.String` to avoid a heap alloc. Or not, as the indirect function calls may cause a performance problem.

Jira issue: CRDB-56283

### PR DESCRIPTION
**Pull request by nvb**
Fixes #119542.

This commit implement `Format` directly on the `jsonEncoded` type, writing into the `*bytes.Buffer` at the same time as decoding. It replaces an implementation which decoded the full JSON object first into an intermediate JSON tree and then formatted that JSON tree into a `*bytes.Buffer` before discarding it.

As a result, this avoids the cost of constructing the intermediate JSON objects. It also avoids needing to pass through `jsonString` objects, which previously caused `[]byte->string` re-allocations and memcpys.

The improvement on the new `FormatJSON` benchmark is as follows:
```
name                   old time/op    new time/op    delta
FormatJSON/encoded-10    2.29µs ± 1%    0.95µs ± 1%  -58.55%  (p=0.000 n=10+9)

name                   old alloc/op   new alloc/op   delta
FormatJSON/encoded-10    2.98kB ± 0%    0.85kB ± 0%  -71.51%  (p=0.000 n=10+10)

name                   old allocs/op  new allocs/op  delta
FormatJSON/encoded-10      68.0 ± 0%       3.0 ± 0%  -95.59%  (p=0.000 n=10+10)
```

The test coverage here is pretty good, as indicated by code coverage and by the failures I encountered in `TestJSONRoundTrip` while making this change.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I ran a quick test with a [modified version of kv99](https://github.com/nvanbenschoten/cockroach/commit/89e428b8dce2b2d64bc7212ec10a0db9bfe5662d) which uses an 8KB blobs of JSONB data as each row's value.

I compared before yesterday's initial JSON PR (#119539) with after this one. Note that the before binary is running master with Go 1.21, which we know has better GC behavior than earlier versions of Go, so this may be even more impactful if backported to early versions of crdb that use previous versions of Go.

### Top-level results:
- 26% increase in throughput
- 10% reduction in p50 latency
- 24% reduction in p99 latency
- 26% reduction in GC runs

#### Script:
```bash
roachprod create nathan-json --nodes=2 --gce-machine-type='n2-standard-4'
roachprod stage nathan-json:1 cockroach
roachprod put nathan-json:2 ./artifacts/cockroach

roachprod start nathan-json:1
roachprod run nathan-json:2 -- "./cockroach workload init kv --splits=10 {pgurl:1}"
roachprod run nathan-json:2 -- "./cockroach workload run kv --read-percent=99 --ramp=1m --duration=4m {pgurl:1}"

roachprod stop nathan-json:1
roachprod put nathan-json:1 ./artifacts/cockroach
roachprod start nathan-json:1
roachprod run nathan-json:2 -- "./cockroach workload run kv --read-percent=99 --ramp=1m --duration=4m {pgurl:1}"
```

#### Raw results:
```
# Before:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  240.0s        0        1588246         6617.7      1.2      1.0      2.2      3.4     27.3  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  240.0s        0          16017           66.7      3.2      2.9      5.0     10.0     50.3  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  240.0s        0        1604263         6684.4      1.2      1.0      2.4      3.7     50.3

# After:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  240.0s        0        1994773         8311.6      0.9      0.9      1.6      2.6     37.7  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  240.0s        0          20358           84.8      2.7      2.5      3.9      5.8     23.1  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  240.0s        0        2015131         8396.4      1.0      0.9      1.8      2.8     37.7
```

Screenshot 2024-02-23 at 11 09 12 AM
Screenshot 2024-02-23 at 11 09 16 AM
Screenshot 2024-02-23 at 11 09 34 AM

#### CPU profiles:

Before:
Screenshot 2024-02-23 at 10 59 54 AM

After:
Screenshot 2024-02-23 at 11 06 36 AM

**Review by yuzefovich — APPROVED** [review]
Very nice! :lgtm:

The only difference I can think of is that previously in case of a corrupt JSON we'd only write `<corrupt JSON data: %s>` into the `bytes.Buffer`, but now we might write partial decoding followed by the same message. This seems acceptable.

> Reviewed 1 of 1 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119564#-:-NrLsKR46W9l7g3h7cd2:b-e4sgvg)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @nvanbenschoten)

___
*[`pkg/util/json/encoded_format.go` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119564#-NrLq2m_9Nw_TZ4__8Zf:-NrLq2m_9Nw_TZ4__8Zg:b-4od8ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0bab16bcf8505ffdc2e3ef566e3ef09a329ecc/pkg/util/json/encoded_format.go#L94)):*
> ```Go
> 		// Decode and ignore.
> 		var ent jEntry
> 		valB, ent, err = decodeJEntry(valB, valOff)
> ```

nit: since we don't need the full `jEntry` here, do you think it'd be worth introducing `decodeJEntryLength` method that would only return the length?
___
*[`pkg/util/json/encode_test.go` line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119564#-NrLmFPI7skpz2DIHIZb:-NrLmFPI7skpz2DIHIZc:b4qfw3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a7937d0333f4bcd88ce0b5937fd89589d81fb95/pkg/util/json/encode_test.go#L286)):*
> ```Go
> 
> 	b.Run("decoded", func(b *testing.B) {
> 		for i := 0; i < b.N; i++ {
> ```

nit: should we do `b.ResetTimer()` right before the loop?

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119564#-:-NrLtITI8fPVB3F3ogiU:b-814g8k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/util/json/encoded_format.go` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119564#-NrLq2m_9Nw_TZ4__8Zf:-NrLtJuR5-Rm-wQR8-Bd:bmjjnij) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0bab16bcf8505ffdc2e3ef566e3ef09a329ecc/pkg/util/json/encoded_format.go#L94)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: since we don't need the full `jEntry` here, do you think it'd be worth introducing `decodeJEntryLength` method that would only return the length?
</blockquote></details>

`decodeJEntry` is quite cheap and the returned `jEntry` is only 8 bytes large. We could avoid a few instructions by only returning the length and not computing the `typCode`, but I don't think that's worth the extra code.
___
*[`pkg/util/json/encode_test.go` line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119564#-NrLmFPI7skpz2DIHIZb:-NrLtl-P4l3_Y0MXD0A0:bjrsgl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a7937d0333f4bcd88ce0b5937fd89589d81fb95/pkg/util/json/encode_test.go#L286)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we do `b.ResetTimer()` right before the loop?
</blockquote></details>

My understanding is that `b.Run` starts the subbenchmark with a fresh timer that does not inherit the duration or allocation counters from the parent benchmark. I might be wrong about that though and I see some other subbenchmarks doing this, so I made the change.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 6 of 6 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119564)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
:fire: :lgtm: 

> The only difference I can think of is that previously in case of a corrupt JSON we'd only write `<corrupt JSON data: %s>` into the `bytes.Buffer`, but now we might write partial decoding followed by the same message. This seems acceptable.

Can't we revert to this behavior by adding a `buf.Clear()` before we write `"<corrupt JSON data: %s>"` to the buffer?

> Reviewed 6 of 6 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119564#-:-NrLywqU-35_WenhMj1K:b-cifuee)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Comment by mgartner** [comment]
I guess we can't clear the whole buffer, but we can remember the previous size and `buf.Truncate`, right?

**Comment by nvanbenschoten** [comment]
> I guess we can't clear the whole buffer, but we can remember the previous size and buf.Truncate, right?

Good idea, done.

**Review by mgartner — APPROVED** [review]
:lgtm: 

nit: If you felt inclined you could write a test for the corrupt JSON case to prevent future breakage, but up to you.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119564#-:-NrM8pbs3dohPEP_0QJ3:bq6t0h4)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Pull request merged**
