### PR TITLE
ui: update not found page

### PR DESCRIPTION
**Pull request by maryliag**
Previously the Not Found page was just a text,
now this page is aligned with the page from CC Console.

Before
Screen Shot 2021-11-12 at 10 45 59 AM

After
Screen Shot 2021-11-12 at 10 07 04 AM

Release note (ui change): Updated Not Found page

### CODE REVIEW

**Review by lindseyjin — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72689)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin and @maryliag)

___
*[pkg/ui/workspaces/db-console/assets/sleepy-moon.svg, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72689#-MoJvyQw9rIXXmQV8Brq:-MoJvyQw9rIXXmQV8Brr:b-ptkds7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d262aa446dc3bc221415d42c2b5761c0344efbea/pkg/ui/workspaces/db-console/assets/sleepy-moon.svg#L1)):*
> ```SVG
> <svg width="280" height="178" viewBox="0 0 280 178" fill="none" xmlns="http://www.w3.org/2000/svg">
> ```

Just curious, where is this file being used? 
Are we just adding it in as an asset for future use? 
___
*[pkg/ui/workspaces/db-console/src/components/core/typography.styl, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72689#-MoJzNsT5PiAAk81kjMj:-MoJzNsT5PiAAk81kjMk:bqw17xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d262aa446dc3bc221415d42c2b5761c0344efbea/pkg/ui/workspaces/db-console/src/components/core/typography.styl#L24)):*
> ```Stylus
> $font-family--monospace = SFMono-Regular, RobotoMono-Medium
> $font-family--lato-regular = Lato-Regular
> $font-family--sans-serif = "Source Sans Pro", sans-serif
> ```

Hmm is this new font different from SourceSansPro-Regular? I thought the font itself was already sans-serif, and they both seem to render the same for me?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72689)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin)

___
*[pkg/ui/workspaces/db-console/assets/sleepy-moon.svg, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72689#-MoJvyQw9rIXXmQV8Brq:-MoK86xI3I4luPEaQQwj:b-x71tdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d262aa446dc3bc221415d42c2b5761c0344efbea/pkg/ui/workspaces/db-console/assets/sleepy-moon.svg#L1)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Just curious, where is this file being used? 
Are we just adding it in as an asset for future use? 
</blockquote></details>

I added because I'm using in another page that will be another PR, it was added here by mistake. I'll remove it and add it back on the other PR
___
*[pkg/ui/workspaces/db-console/src/components/core/typography.styl, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72689#-MoJzNsT5PiAAk81kjMj:-MoKAzHpDlxjTN9W-zI8:b-ie553x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d262aa446dc3bc221415d42c2b5761c0344efbea/pkg/ui/workspaces/db-console/src/components/core/typography.styl#L24)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Hmm is this new font different from SourceSansPro-Regular? I thought the font itself was already sans-serif, and they both seem to render the same for me?


</blockquote></details>

When I tested I had the impression that they looked different, checking again, indeed they look the same. I moved back to the base font family and removed some other references to this font of other places

**Review by lindseyjin — APPROVED** [review]
LGTM :) :cockroach: :tada:

> Reviewed 1 of 5 files at r1, 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72689#-:-MoKJT9LDw6f1vUv8oLb:bqwud35)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin)

**Pull request merged**
