### PR TITLE
sql: exclude Bulk IO operations from service latency metrics

### LINKED ISSUE #42174: ui: exclude backups from the "Service Latency: SQL, 99th percentile" graph
**Is your feature request related to a problem? Please describe.**
Currently, in the service latency graph, we include backups. This can be confusing to users who expect this only to include queries from the application. The information window from the service latency graph states: “Over the last minute, this node executed 99% of queries within this time. This time does not include network latency between the node and client.” Here is a graph of a cluster performing 15 incremental backups every hour, they take a few seconds to run, so they spike the graph: 
image (4)

**Describe the solution you'd like**
I would like to see backups removed from this graph, they could be included elsewhere, but I believe on this graph, they should be removed to help users focus on their queries and not admin tasks.

### PR DESCRIPTION
**Pull request by Azhng**
Previously, we included Bulk IO operations such as BACKUP
in our service latency metrics. This caused spikes in our time
series graph for service latency, which can lead to confusion.

Closes #42174

Release note (sql change): Bulk IO operations will no longer be included
 in service latency metrics.

### CODE REVIEW

**Review by maryliag — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64442)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/executor_statement_metrics.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64442#-MZXvFz5DWFrQQ9iA3-a:-MZXvFz65hd973Vzdb0f:bymfe1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10b68bb98129f308541b60af4dcc2fede610faf/pkg/sql/executor_statement_metrics.go#L268)):*
> ```Go
> // Bulk IO operations cause spikes in our time series chart for service latency. We exclude them from the service
> // latency metrics to avoid confusions.
> // https://github.com/cockroachdb/cockroach/issues/42174
> ```

I think adding the issue is more when we have a TODO. Any particular reason why adding the issue here?

**Comment by Azhng** [comment]
Hmm ran some test and realized this fix is not going to completely address the problem. We are still seeing latency spikes from statements that manages job system tables. 

Back to drawing board.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64442)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/sql/executor_statement_metrics.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64442#-MZXvFz5DWFrQQ9iA3-a:-MZo435f03KiPRtOcWJK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f10b68bb98129f308541b60af4dcc2fede610faf/pkg/sql/executor_statement_metrics.go#L268)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I think adding the issue is more when we have a TODO. Any particular reason why adding the issue here?
</blockquote></details>

Done.

**Review by maryliag — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64442#-:-MZoIx9A83LSwz50NfBi:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Comment by Azhng** [comment]
TFTR!

bors y=maryliag

**Comment by Azhng** [comment]
Seems like I have made a typo in the bors command.

bors r=maryliag

**Comment by Azhng** [comment]
@dt I filed #64741, and I will send a follow up PR soon.

**Comment by pingxianga** [comment]
> 

Hello sir, why don't we add other statements besides DMl statements, such as DQL statements

**Pull request merged**
