### PR TITLE
util: make CombineUnique generic, clarify semantics

### PR DESCRIPTION
**Pull request by pav-kv**
This PR replaces two identical `CombineUnique<Type>` functions (only the input type differs) with a generic. It also clarifies the semantics of the function, adds a few tests, and improves formatting.

Release note: none
Epic: none

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
@maryliag @yuzefovich tagging you since you modified/reviewed this function recently.

**Review by maryliag — APPROVED** [review]
Nice! Generics FTW! :smile: 

> Reviewed 11 of 11 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101359#-:-NSqq8rq6r_ogisSSRIt:b-mbka13)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by pavelkalinnikov** [comment]
bors r=maryliag

**Review by yuzefovich — COMMENTED** [review]
Nice! :lgtm:

> Reviewed 11 of 11 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101359#-:-NSrVJAp0_1Xm4p_wbxz:be8rotp)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
