### PR TITLE
sql: add crdb_internal.kv_protected_ts_records virtual table

### LINKED ISSUE #104161: jobs: PTS Record virtual table
We should provide more PTS obersvability by adding a virtual tale that provides a view into PTS records: job/schedule owner, number of ranges protected, etc. That would be queriable and could be used to when problems like this come up: https://github.com/cockroachdb/cockroach/issues/103855. 

Jira issue: CRDB-28380

### PR DESCRIPTION
**Pull request by jayshrivastava**
This change adds a new virtual table `crdb_internal.kv_protected_ts_records` which provides better visability into PTS records than `system.protected_ts_records`. This virtual table includes all columns from the system table and adds the following columns:
- `num_ranges INT`: the number of ranges protected by the PTS record. Note this does not
  count ranges when the PTS record is protecting a database, cluster, or tenant. It
  only counts ranges protected by tables. Adding support for databases, clusters,
  and tenants is left as a TODO.
- `decoded_meta JSON`: the decoded `meta` column from the system table. For the jobs `meta_type`,
  this contains the job ID. For the schedules `meta_type`, this is contains the schedule ID.
- `decoded_target JSON`: the decoded `ptpb.Target` field.
- `internal_meta JSON`: any additional metadata added by this table. For the jobs `meta_type`,
  this contains the job owner. For the schedules `meta_type`, this contains the schedule label
  and owner.

This change also adds this table to the debug zip.

Release note: None
Closes: https://github.com/cockroachdb/cockroach/issues/104161
Epic: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: for sql queries

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105577#-:-N_AKopC1eRskSae9YxB:bcq9lgu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava, @miretskiy, and @rhu713)

___
*[`pkg/sql/crdb_internal.go` line 1536 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105577#-NZCzCxt8hLT1T-5Ko5k:-NZCzCxt8hLT1T-5Ko5l:bkqob7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb256757419ace2f2bef3bed3bd19b8564f7bfaf/pkg/sql/crdb_internal.go#L1536)):*
> ```Go
> 			// decoded.
> 			numRanges = tree.NewDInt(-1)
> 			// Before 22.2, there was no target column in the system table. PTS records created before then which have
> ```

nit: wrap comments throughout this file
___
*[`pkg/sql/crdb_internal.go` line 1454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105577#-N_AJnj-D0dSeWXmB-k6:-N_AJnj-D0dSeWXmB-k7:bodnrmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5dad0a6e7c74108db89395fe8442056078436b5b/pkg/sql/crdb_internal.go#L1454)):*
> ```Go
> 		cleanup := func(ctx context.Context) {
> 			if err := it.Close(); err != nil {
> 				// TODO(yuzefovich): this error should be propagated further up
> ```

nit: s/yuzefovich/#61123

**Comment by jayshrivastava** [comment]
@kevin-v-ngo I want to revisit this PR in the future - I'm not sure if its the best way to go about things. I believe the `system.protected_ts_meta` table has a column for the number of bytes protected by a timestamp already, making my range estimation in this PR less useful. I don't know if this number represents live, non-live, or both.

 In terms of deocding the jobid and meta, I could just make some builtins for us to use instead - I don't know if the whole virtual table is needed. 

I'm not sure how to calculate live vs non-live bytes. Maybe we can add a builtin fcn or update `system.protected_ts_meta` to show that info.

**Comment by shermanCRL** [comment]
Do we intend to merge this, or are we re-thinking it?

**Comment by jayshrivastava** [comment]
I think I'll merge this after rebasing.

**Pull request merged**
