### PR TITLE
Check for nil response before using the value.

### PR DESCRIPTION
**Pull request by jamesgraves**
Small bug fix for server cli.

I don't view a key not existing as an error, so I also removed the os.Exit(1).

### CODE REVIEW

**Comment by BramGruneir** [comment]
Could you add a unit test for this?

**Comment by bdarnell** [comment]
A key not found is not an error, but it's not really a success either. I think we should exit with a non-zero status when the key isn't found, although it should probably be a different status than we use for real errors (e.g. grep returns 0 if there were matches, 1 if there were no matches, and any other value indicates an error)

**Comment by spencerkimball** [comment]
LGTM

It would be nice to write a unittest for this. The best way to do it would be to create an "Example" type unittest and verify the expected output. See server/zone_test.go for examples of this style.

**Comment by jamesgraves** [comment]
I'll start creating unit tests next.  Since we have commands that will have different exit codes, I guess I'll have to actually run the commands like `cockroach get foobar` and check the exit status.

**Comment by petermattis** [comment]
@jamesgraves not sure what you're imagining, but running `cockroach get foobar` does not sound like it will integrate nicely with `go test`. I would build a bit of test harness that starts up a local cockroach cluster and then allows easy invocation of commands in `server/cli`. Something that just took a string, split it on whitespace and fed that into the command processing sounds pretty straightforward. Heck, I'd even start the local cluster using the `init` command.

**Comment by bdarnell** [comment]
Instead of going through the full command-line stack, we could refactor the commands to not call os.Exit directly (i.e. do most of the work in a normal function that returns an error, and then wrap it in something that calls os.Exit at the end) to make them more easily testable in normal go tests.

Alternately, the acceptance test (`run/local-cluster.sh`) would be a good place to run shell-style commands against a real cluster (although I think I'm going to rework that to run a go program so we don't have to do everything in shell).

**Comment by tschottdorf** [comment]
Hey @jamesgraves, I'll close this for now since it's been inactive for a while, but please reopen it when needed.

**Pull request closed without merging**
