### PR TITLE
Update link to cloud deployment instructions

### PR DESCRIPTION
**Pull request by mberhault**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3588)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM, but add a comment about this being for testing only.

**Comment by mberhault** [comment]
how about "For a sample configuration to deploy ...." ?

**Comment by tschottdorf** [comment]
I don't know. That still doesn't sound a lot more production-ready than it is (with exposing an unsecured supervisord and all). How about:

To run an unsecured, testing-only CockroachDB cluster on AWS using [Terraform](https://terraform.io/), see [cloud deployment](https://github.com/cockroachdb/cockroach/tree/master/cloud/aws).

**Comment by mberhault** [comment]
changed to "For a sample configuration to run an insecure CockroachDB cluster on AWS using ..."

**Comment by tschottdorf** [comment]
Don't want to be a heckler, but when we talked about exposing supervisord your point was "it's for testing only" and now your point is "it's not for testing only". LGTM but not sure what the hold-up is.

**Comment by mberhault** [comment]
removed. it's not actually used by anything, only in benchmarks and logictests.
Still, at some point I'd like everyone to get it into their heads that this isn't meant to be used in anyone's production environment, this is an example of how things can be setup. We'll never provide real production configuration, just docs and examples.

**Comment by tschottdorf** [comment]
You didn't have to remove it for me, but still LGTM.
BTW, I have pretty firmly in my head what you were talking about. But our README is talking to the internet and if we give something as an example, it should demonstrate good practices or be clear about the lack thereof.

**Pull request merged**
