### PR TITLE
sql/schemachanger: fix a misattributed metric and noisy log

### PR DESCRIPTION
**Pull request by rafiss**
### sql: only increment sql.ddl.count for DDL operations

This was leasing to a highly inflated count of the metric due to TCL
statements such as DISCARD ALL. Those are not DDL statements, but they
can modify schema by dropping temporary sequences. Using the statement
return type is a more accurate way to check.

Release note (bug fix): Fixed a minor bug where DISCARD ALL statements
were counted under the sql.ddl.count metric. Now these will be counted
under the sql.misc.count metric.

### sql: move a spammy log to a higher verbosity level

This was getting logged too frequently, since the function is called during the
planning phase to check if a statement works in the declarative schema
changer. This would get logged even if the statement does not use the
declarative schema changer, which is a little misleading.

Epic: None
Release note: None

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134377)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/conn_executor.go` line 4622 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134377#-OB2Dz77ADGETKIiD8qZ:-OB2Dz77ADGETKIiD8q_:b386n0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/926a81d37a93afcb4ba8e81bfa19d96dacfa4c18/pkg/sql/conn_executor.go#L4622)):*
> ```Go
> 		}
> 	default:
> 		if stmt.StatementReturnType() == tree.DDL || stmt.StatementType() == tree.TypeDDL {
> ```

The description for `tree.DDL` says that it won't be returned for `CREATE TABLE AS`. That seems like a problem.
```
	// DDL indicates that the statement mutates the database schema.
	//
	// Note: this is the type indicated back to the client; it is not a
	// sufficient test for schema mutation for planning purposes. There
	// are schema-modifying statements (e.g. CREATE TABLE AS) which
	// report RowsAffected to the client, not DDL.
	// Use CanModifySchema() below instead.
	DDL
```

Should we just special case for `DISCARD`?
___
*[`pkg/sql/schemachanger/scerrors/errors.go` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134377#-OB2EabVAYvKd2rrNglp:-OB2EabVAYvKd2rrNglq:b-a0e5vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/011a5ea5c87324aa637a33abd557ec78d0fff9d7/pkg/sql/schemachanger/scerrors/errors.go#L39)):*
> ```Go
> func StartEventf(ctx context.Context, format string, args ...interface{}) EventLogger {
> 	msg := redact.Safe(fmt.Sprintf(format, args...))
> 	if log.ExpensiveLogEnabled(ctx, 1) {
> ```

Is this really the intent of this function? The log message is inexpensive to generate—it’s just overly verbose. Should we consider adjusting the log level instead?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134377)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/conn_executor.go` line 4622 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134377#-OB2Dz77ADGETKIiD8qZ:-OB2LczwAdhWgBjBuIXo:boiks09) ([raw file](https://github.com/cockroachdb/cockroach/blob/926a81d37a93afcb4ba8e81bfa19d96dacfa4c18/pkg/sql/conn_executor.go#L4622)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

The description for `tree.DDL` says that it won't be returned for `CREATE TABLE AS`. That seems like a problem.
```
	// DDL indicates that the statement mutates the database schema.
	//
	// Note: this is the type indicated back to the client; it is not a
	// sufficient test for schema mutation for planning purposes. There
	// are schema-modifying statements (e.g. CREATE TABLE AS) which
	// report RowsAffected to the client, not DDL.
	// Use CanModifySchema() below instead.
	DDL
```

Should we just special case for `DISCARD`?
</blockquote></details>

that comment is from 2017 and seems to no longer be correct. `CREATE TABLE AS` does use a DDL statement type:
https://github.com/cockroachdb/cockroach/blob/4c25d09d2a7a60be1396116e0ab9fd7194238f0e/pkg/sql/sem/tree/stmt.go#L972-L976

nice catch on the comment though. i have fixed it now.
___
*[`pkg/sql/schemachanger/scerrors/errors.go` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134377#-OB2EabVAYvKd2rrNglp:-OB2LquTBzjl__JbdBK8:bsppuxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/011a5ea5c87324aa637a33abd557ec78d0fff9d7/pkg/sql/schemachanger/scerrors/errors.go#L39)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is this really the intent of this function? The log message is inexpensive to generate—it’s just overly verbose. Should we consider adjusting the log level instead?
</blockquote></details>

hm the issue is that there doesn't seem to be a version of `	log.InfofDepth` that accepts a level. let me search a bit more for anything similar.

**Review by spilchen — APPROVED** [review]
:lgtm: Thanks for making the additional changes.

> Reviewed 2 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134377#-:-OB5_zZq18eNZhC-EuuV:bspkxxb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
