### PR TITLE
sql: enhance readability of builder tests in new schema changer

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the new schema changer builder tests had readability
issues trying to figure out the elements getting made. This was
inadequate because the builder tests results were hard to read.
To address this, this patch changes the format for the builder
tests to be easier to read.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66192#-:-MbgTLNm9d4hq2QOMAyx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66192#-MbgQChx3UNjN_le7GLp:-MbgQChx3UNjN_le7GLq:b-ionhlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/38eb3e3190071d170fcc44259531fdf71c6b96b5/pkg/sql/schemachanger/scbuild/builder_test.go#L123)):*
> ```Go
> // indentText indents text for formatting out marshaled data.
> func indentText(input string, tab string) (final string) {
> 	split := strings.Split(input, "\n")
> ```

nit: strings.Builder

Or, better yet, how about using regexp replace?

```
var newlineFollowedByNonEmptyLineRE = regexp.MustCompile("(?s)\n([^\n]*\\S+[^\n]*)")

func indentText(input, tab string) (fina string) {
	return newlineFollowedByNonEmptyLineRE.ReplaceAllString(input, "\n"+tab+"$1")
}
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66192)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66192#-MbgQChx3UNjN_le7GLp:-Mbgd7pRBlmWWMvIAGxs:b9l0izd) ([raw file](https://github.com/cockroachdb/cockroach/blob/38eb3e3190071d170fcc44259531fdf71c6b96b5/pkg/sql/schemachanger/scbuild/builder_test.go#L123)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: strings.Builder

Or, better yet, how about using regexp replace?

```
var newlineFollowedByNonEmptyLineRE = regexp.MustCompile("(?s)\n([^\n]*\\S+[^\n]*)")

func indentText(input, tab string) (fina string) {
	return newlineFollowedByNonEmptyLineRE.ReplaceAllString(input, "\n"+tab+"$1")
}
```

</blockquote></details>

Done. Switched to the string builder. I tried the regex approach, but there can be multiple lines or a lack of new lines. Which breaks doing just a simple replace, you'll get multiple match groups.

**Comment by fqazi** [comment]
bors r=ajwerner

**Review by ajwerner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66192)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66192#-MbgdSWQEq6TvyKZymms:-MbgdSWQEq6TvyKZymmt:b48nf2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d865fbe93287d9f39154620130f3b3d97c218949/pkg/sql/schemachanger/scbuild/builder_test.go#L124)):*
> ```Go
> func indentText(input string, tab string) string {
> 	result := strings.Builder{}
> 	split := strings.Split(input, "\n")
> ```

FYI: perf does not matter here so this is good. If it did, I'd use `bufio.Scanner` for splitting.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66192)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66192#-MbgdSWQEq6TvyKZymms:-MbghKcHB17wC446gy60:bv2544x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d865fbe93287d9f39154620130f3b3d97c218949/pkg/sql/schemachanger/scbuild/builder_test.go#L124)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

FYI: perf does not matter here so this is good. If it did, I'd use `bufio.Scanner` for splitting. 
</blockquote></details>

Done, it's a good excuse to learn. So changed it over.

**Comment by fqazi** [comment]
bors r=ajwerner

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66192)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66192#-MbgpsTe7vMxMJ76usg1:-MbgpsTe7vMxMJ76usg2:bhgx3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1fffab107b207dba3016d347f72efaa79f9e5bb/pkg/sql/schemachanger/scbuild/builder_test.go#L129)):*
> ```
> 		line := scanner.Text()
> 		if len(line) == 0 {
> ```
Is the intended behavior to skip blank lines? If so, add that to the comment.
___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66192#-Mbgq3mI4ARvZmXbRjxV:-Mbgq3mI4ARvZmXbRjxW:b-a2u1xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1fffab107b207dba3016d347f72efaa79f9e5bb/pkg/sql/schemachanger/scbuild/builder_test.go#L134)):*
> ```Go
> 		result.WriteString(tab)
> 		result.WriteString(line)
> 		result.WriteString("\n")
> ```

Did you want to always add a trailing newline? The old code didn't, did it? If not, you could do `if result.Len() > 0 { result.WriteString("\n") }` at the top of the loop. I guess this combines with the logic to skip the newline at the top of the loop.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66192)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66192#-MbgpsTe7vMxMJ76usg1:-MbgsH8pEE45d2RDovd6:beygsph) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1fffab107b207dba3016d347f72efaa79f9e5bb/pkg/sql/schemachanger/scbuild/builder_test.go#L129)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		line := scanner.Text()
> 		if len(line) == 0 {
> ```
Is the intended behavior to skip blank lines? If so, add that to the comment.
</blockquote></details>

That shouldn't be needed, I'll drop this in a separate pull request. I kicked off bors on it and it got merged.
___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66192#-Mbgq3mI4ARvZmXbRjxV:-Mbgs_PT8zvwXtp6-myS:bpllpfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1fffab107b207dba3016d347f72efaa79f9e5bb/pkg/sql/schemachanger/scbuild/builder_test.go#L134)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Did you want to always add a trailing newline? The old code didn't, did it? If not, you could do `if result.Len() > 0 { result.WriteString("\n") }` at the top of the loop. I guess this combines with the logic to skip the newline at the top of the loop.
</blockquote></details>

I think it's better to just always add one and assume the input has one. I think it was only there for some edge case, so I cleaned it up.

**Pull request merged**
