### PR TITLE
colexec: release in-memory resources after spilling to disk

### LINKED ISSUE #60022: colexec: clean up buffered state when operators spilled to disk
Currently, when buffering in-memory operator exports its buffered tuples in `ExportBuffered`, we still keep references to all of that buffered state (thus prohibiting it from being GCed) as well as we don't clear the corresponding memory accounts. In all cases except for the unordered distinct, we actually can lose those references and we should update the memory accounting accordingly.

Jira issue: CRDB-3198
Epic: CRDB-34180

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexecagg: remove redundant NewAggregatorArgs.MemAccount field**

This field is supposed to be the same memory account as used by the allocator (which wasn't the case in one spot), but we can easily access the account through the allocator wherever needed.

**colexec: release in-memory resources after spilling to disk**

This commit audits all operators that can spill to disk. In almost all cases, once the export of buffered tuples is complete, we no longer need resources used by the in-memory operator, so this commit eagerly loses references to them while adjusting the memory accounting system accordingly.

There are two exceptions though:
- the unordered distinct keeps on using the in-memory hash table even after having spilled to disk (the hashtable is probed to remove duplicates of the rows that were emitted before disk spilling occurred)
- when the disk-backed sort is used in the fallback strategy in the hash-based partitioner, the sort can be reused multiple times (for each partition in the worst case).

The first exception is very easy to handle, but handling the second one was a bit tricky and required some plumbing. Namely, we now mark each disk-backed operator to indicate what "reuse mode" of the buffering operator is required; if no reuse occurs, then the operator is free to lose all the references; if reuse can happen, then we effectively preserve the behavior before this change.

We extend the `BufferingInMemoryOperator` interface to include two new methods to allow operators to release resources before and after the export.

Fixes: #60022.

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
This looks alright to me, but I have a suggestion that you can ignore if you want: instead of passing an extra argument to `ExportBuffered`, could we add a new method to the `BufferingInMemoryOperator` interface called `DetachForExport` or `ReleaseForExport` (or something), which handles releasing unused allocations. Then, the caller can decide whether or not to call that method before exporting tuples.

> Reviewed 8 of 8 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127093#-:-O21fbMh8C0qlqAlqXnZ:benacil)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
I like this suggestion. I just pushed another commit that I plan to squash and would appreciate another look. I added two methods to the interface since in some cases the resources could be released before the export, but in most cases we need to release the resources after the export. WDYT about this?

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice!

> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127093#-:-O24H5tQ7ZKJIla1shBI:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/colexec/colexecdisk/disk_spiller.go` line 359 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/127093#-O245vc11Kc8hIBL3HzL:-O245vc11Kc8hIBL3HzM:b-8yj7nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbdd311dc39796b8e0e70aa44d9ca7425fa6c405/pkg/sql/colexec/colexecdisk/disk_spiller.go#L359)):*
> ```Go
> 	if b.firstSourceDone {
> 		if !b.firstSourceReleasedAfter && b.firstSourceReuseMode == colexecop.BufferingOpNoReuse {
> 			b.firstSourceReleasedAfter = true
> ```

Would it be easier to require that `ReleaseBeforeExport` and `ReleaseAfterExport` are idempotent?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127093)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/colexec/colexecdisk/disk_spiller.go` line 359 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/127093#-O245vc11Kc8hIBL3HzL:-O25W3HLBdvatVaJWE6h:bwmmw6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbdd311dc39796b8e0e70aa44d9ca7425fa6c405/pkg/sql/colexec/colexecdisk/disk_spiller.go#L359)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Would it be easier to require that `ReleaseBeforeExport` and `ReleaseAfterExport` are idempotent?
</blockquote></details>

They are already idempotent, but this property isn't used. My thinking is that `bufferExportingOperator.Next` will be called for each batch of an input throughout the whole disk-spilled operation (i.e. if we need to sort 1B batches, then it'll be called 1B times), so having an extra function call that is a no-op would add a little latency, and given that it's quite easy to avoid it, we should do so. (True, this function call overhead is probably a drop in the ocean when comparing to other work done when spilling to disk overall, yet this little bit of code ugliness is very limited and localized.)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
