### PR TITLE
raft: disarm inHeartbeatLease when appropriate for leader leases

### PR DESCRIPTION
**Pull request by iskettaneh**
We need to disarm the inHeartbeatLease where appropriate when using leader leases.

This PR does the following:

1) Whenever a peer is de-fortifying a leader, it advances its electionElapsed to electionTimeout. This means that (A) The peer can immediately vote in elections, and (B) The peer can attempt to call elections `electionTimeout` faster.

2) If a follower fortified a leader, its inHeartbeatLease is basically disabled and we just rely on the store liveness signal using `inFortifyLease()`

Epic: None

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134211)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`pkg/raft/raft.go` line 1169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134211#-OAy35RL0sNbrHeXur7j:-OAy35RL0sNbrHeXur7k:bysecvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e8c697432208051638ea87b90481798830b4cb7/pkg/raft/raft.go#L1169)):*
> ```Go
> 		// re-fortified, which means we'll only ever skip the initial part of the
> 		// election timeout once per fortified -> no longer fortified transition.
> 		r.deFortify(r.id, r.Term)
> ```

Could we add a comment around here about how this call will impact `r.leadEpoch` and `r.electionElapsed`, and what that means for future calls to this function?
___
*[`pkg/raft/raft.go` line 2430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134211#-OAy2u1M7SZvciRupRAn:-OAy2u1M7SZvciRupRAo:b-fcg18b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e8c697432208051638ea87b90481798830b4cb7/pkg/raft/raft.go#L2430)):*
> ```Go
> 	assertTrue(
> 		// We're not currently fortified, so de-fortification is a no-op...
> 		r.leadEpoch == 0 ||
> ```

nit: consider just early returning if `r.leadEpoch == 0`, bypassing this assertion and the conditional logic below.
___
*[`pkg/raft/raft.go` line 2455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134211#-OAy3Oaf25vEu5wiG6e5:-OAy3Oaf25vEu5wiG6e6:b8nvxm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e8c697432208051638ea87b90481798830b4cb7/pkg/raft/raft.go#L2455)):*
> ```Go
> 			r.id, r.electionTimeout,
> 		)
> 		r.electionElapsed = r.electionTimeout
> ```

When I had mocked out something similar, I only made this change to `r.electionElapsed` when `r.state != pb.StateLeader`. The reason being that the `r.electionElapsed == 0 if r.leadEpoch != 0` invariant only holds for followers and I had wanted to add an `assertTrue(r.electionElapsed == 0)` call right before this line. Leaders use `r.electionElapsed` for something different.

I'm not quite convinced that we want to make this conditional, but could you think through the implications of this being run on a leader?
___
*[`pkg/raft/raft.go` line 1507 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134211#-OAy4YcECMC7INUpaIvx:-OAy4YcECMC7INUpaIvy:b-u211li) ([raw file](https://github.com/cockroachdb/cockroach/blob/acdc048af6aaecfab742afd888e86fbdc7389fa8/pkg/raft/raft.go#L1507)):*
> ```Go
> 					}
> 					if inFortifyLease && inHeartbeatLease {
> 						sep = " and "
> ```

Now that these conditions are mutually exclusive, we can clean up this logging code.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134211)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 2455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134211#-OAy3Oaf25vEu5wiG6e5:-OAyB0FF8qx3jHm18Unh:b9ug9h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e8c697432208051638ea87b90481798830b4cb7/pkg/raft/raft.go#L2455)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

When I had mocked out something similar, I only made this change to `r.electionElapsed` when `r.state != pb.StateLeader`. The reason being that the `r.electionElapsed == 0 if r.leadEpoch != 0` invariant only holds for followers and I had wanted to add an `assertTrue(r.electionElapsed == 0)` call right before this line. Leaders use `r.electionElapsed` for something different.

I'm not quite convinced that we want to make this conditional, but could you think through the implications of this being run on a leader?
</blockquote></details>

The only interaction I found was when a leader receives a message that indicates another leader. It steps down, but before it becomes a Follower, it defortifies itself. That shouldn't cause any problem since becoming a follower will reset the electionElapsed anyways.

That being said, I think we can be defensive and wrap it with a condition that it's not currently a leader. What do you think?

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134211#-:-OB2m2Bm0LTOJdXQ4vcD:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`pkg/raft/raft.go` line 2455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134211#-OAy3Oaf25vEu5wiG6e5:-OB2lc8j6qGDIuaOwzWy:bkd8r3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e8c697432208051638ea87b90481798830b4cb7/pkg/raft/raft.go#L2455)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

The only interaction I found was when a leader receives a message that indicates another leader. It steps down, but before it becomes a Follower, it defortifies itself. That shouldn't cause any problem since becoming a follower will reset the electionElapsed anyways.

That being said, I think we can be defensive and wrap it with a condition that it's not currently a leader. What do you think?
</blockquote></details>

This seems reasonable to me.

**Pull request merged**
