### PR TITLE
ui: require yarn >= 1.7.0

### PR DESCRIPTION
**Pull request by tbg**
Builds before the upgrade failed mysteriously.
@benesch (cc) suspects a bug in older versions of yarn.

```
$ make build
Running make with -j8
GOPATH set to /Users/tschottdorf/go
build/node-run.sh -C pkg/ui yarn install --offline
(echo "// Code generated by goyacc. DO NOT EDIT."; \
     echo "// GENERATED FILE DO NOT EDIT"; \
     cat pkg/sql/parser/gen/sql.go.tmp | \
     sed -E 's/^const ([A-Z][_A-Z0-9]*) =.*$/const \1 = lex.\1/g') > pkg/sql/parser/sql.go.tmp || rm pkg/sql/parser/sql.go.tmp
(echo "// Code generated by make. DO NOT EDIT."; \
     echo "// GENERATED FILE DO NOT EDIT"; \
     echo; \
     echo "package lex"; \
     echo; \
     grep '^const [A-Z][_A-Z0-9]* ' pkg/sql/parser/gen/sql.go.tmp) > pkg/sql/lex/tokens.go.tmp || rm pkg/sql/lex/tokens.go.tmp
mv -f pkg/sql/lex/tokens.go.tmp pkg/sql/lex/tokens.go
mv -f pkg/sql/parser/sql.go.tmp pkg/sql/parser/sql.go
yarn install v1.6.0
(node:50064) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/5] Validating package.json...
go install -v docgen
bin/prereqs ./pkg/cmd/docgen > bin/docgen.d.tmp
[2/5] Resolving packages...
mv -f bin/docgen.d.tmp bin/docgen.d
[3/5] Fetching packages...
build/node-run.sh pkg/ui/bin/gen-protobuf-cli-deps.js > pkg/ui/node_modules/protobufjs/cli/package.json
bash: pkg/ui/node_modules/protobufjs/cli/package.json: No such file or directory
make: *** [pkg/ui/yarn.installed] Error 1
make: *** Waiting for unfinished jobs....
```

Release note (general change): the build now requires yarn at version
1.7.0 or above, to work around https://github.com/yarnpkg/yarn/issues/5761.

### CODE REVIEW

**Comment by benesch** [comment]
LGTM! I think this deserves a shoutout on the mailing list though. (Feel
free to leave that for me if you’d prefer. I can do it when I get home
tonight EST.)

**Comment by tschottdorf** [comment]
I think we also need to build a new builder image -- at least all of CI is red because of the version bump. I won't get to this tonight, so do with this PR what you please!

**Comment by benesch** [comment]
Yeah there’s a new version of Yarn shipping with the updated builder in
https://github.com/cockroachdb/cockroach/pull/27115, so we can just wait
for that to land.

**Comment by couchand** [comment]
LGTM pending the builder and mailing list updates.  Thanks fellas!

**Comment by tschottdorf** [comment]
Sent an update to the mailing list and will bors it when teamcity looks happy.

**Comment by tschottdorf** [comment]
Done.

**Comment by benesch** [comment]
The version of Node is pinned by Ubuntu, but Yarn is not. We get whatever the latest version of Yarn is at the time the builder image is built. This works well enough since we don't enforce a maximum version of Yarn.

**Comment by tschottdorf** [comment]
bors r=benesch,vilterp

**Pull request merged**
