### PR TITLE
jobs: refresh job details before removing protected timestamps

### LINKED ISSUE #92493: logictest: protected timestamp record does not exist
pkg/sql/logictest/tests/fakedist/fakedist_test.TestLogic_alter_primary_key [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7691493?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7691493?buildTab=artifacts#/) on master @ [b5be006bedd7d3cedc3fb3d2248df168e3d64be2](https://github.com/cockroachdb/cockroach/commits/b5be006bedd7d3cedc3fb3d2248df168e3d64be2):

```
=== RUN   TestLogic_alter_primary_key
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/d549810e45034f43a9494d02b085e623/logTestLogic_alter_primary_key1996763357
    test_log_scope.go:79: use -show-logs to present logs inline
=== CONT  TestLogic_alter_primary_key
    logic.go:4129: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/d549810e45034f43a9494d02b085e623/logTestLogic_alter_primary_key1996763357
--- FAIL: TestLogic_alter_primary_key (7.53s)
=== RUN   TestLogic_alter_primary_key/index_rewrites
    logic.go:3182: 
        
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2386/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/alter_primary_key:258: 
        expected success, but found
        (XXUUU) job 816917427264749569: protected timestamp record does not exist
        protectedts.go:31: in init()
    logic.go:2144: 
         pq: job 816917427264749569: protected timestamp record does not exist
[10:56:54] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2386/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/alter_primary_key with config fakedist: 60 tests, 2 failures
[10:56:55] --- total progress: 60 statements
--- total: 60 tests, 2 failures
    --- FAIL: TestLogic_alter_primary_key/index_rewrites (0.92s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_alter_primary_key.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21810

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #92493

Previously, we added the protected timestamps manager into the jobs frame work, which made it easier to automatically add and remove protected timestamps for jobs. Unfortunately, the Unprotect API when invoked from a clean up function never properly refreshed the job. Which could lead to a race condition trying to remove protected timestamps for schema changes. To address this, the Unprotect function will take advantage of the job update function to confirm that a refreshed copy does have protected timestamps set.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go` line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92586#-NHzBV2tADWwVKTtjUqG:-NHzBV2tADWwVKTtjUqH:b-wr34v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ca05a879ebce6696fce15a113eb6e8f0ff2158b/pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go#L205)):*
> ```Go
> // executing.
> func (p *Manager) Unprotect(ctx context.Context, job *jobs.Job) error {
> 	return p.db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> ```

I think you can simplify this to:

```
return job.Update(ctx, nil /* txn */, func(txn *kv.Txn, md jobs.JobMetadata, ju *jobs.JobUpdater) error {
   // check the job details here etc
})
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go` line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92586#-NHzBV2tADWwVKTtjUqG:-NHzCcC_1j89oSJkXVl0:b-yg72bz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ca05a879ebce6696fce15a113eb6e8f0ff2158b/pkg/jobs/jobsprotectedts/jobs_protected_ts_manager.go#L205)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think you can simplify this to:

```
return job.Update(ctx, nil /* txn */, func(txn *kv.Txn, md jobs.JobMetadata, ju *jobs.JobUpdater) error {
   // check the job details here etc
})
```

</blockquote></details>

Yes good point, should have done this much earlier

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92586#-:-NHzOwWzCbJx0JFoOWLv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Pull request merged**
