### PR TITLE
sqlsmith: Add aggregation TLP testing

### PR DESCRIPTION
**Pull request by nehageorge**
Previously, TLP testing included JOINS and WHERE clauses. In
this PR, this is expanded to include MAX and MIN based testing.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70494#-:-MkCrgPD4kgwMw2Ebawr:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nehageorge)

___
*[pkg/internal/sqlsmith/tlp.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70494#-MkCr1sEBVL3Sqhz_5wr:-MkCr1sEBVL3Sqhz_5ws:b871583) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb35048984d83d534f5388e27161332014c5d024/pkg/internal/sqlsmith/tlp.go#L278)):*
> ```Go
> // that are supported are MAX() and MIN(), although SUM(), AVG(), and COUNT()
> // are also valid TLP aggregations.
> ```

nit: add `//` on this line so it's obvious the comment is continuous
___
*[pkg/internal/sqlsmith/tlp.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70494#-MkCrLycEE0ilX-mtElC:-MkCrLycEE0ilX-mtElD:b-l0c697) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb35048984d83d534f5388e27161332014c5d024/pkg/internal/sqlsmith/tlp.go#L303)):*
> ```Go
> //
> // If the resulting counts of the two queries are not equal, there is a logical
> // bug.
> ```

Are we interested in counts in this case? Or rather the value of min/max?

If the value of min/max, what happens if `first` is not an integer column? Won't `runTLPQuery` fail since it expects an int?

**Review by nehageorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70494)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nehageorge and @rytaft)

___
*[pkg/internal/sqlsmith/tlp.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70494#-MkCrLycEE0ilX-mtElC:-MkCw_mhEJKF-OFfKHtW:b-monb65) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb35048984d83d534f5388e27161332014c5d024/pkg/internal/sqlsmith/tlp.go#L303)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Are we interested in counts in this case? Or rather the value of min/max?

If the value of min/max, what happens if `first` is not an integer column? Won't `runTLPQuery` fail since it expects an int?
</blockquote></details>

Good catch on the comment, thanks! Yep, you're right about the second part. I thought of changing this but I decided that it's not worth it since in the PR I'm working on effectively reverses this change. In that PR, the counts are no longer compared and instead the results are compared directly with everything cast to a string. So it will be cast to a string in the future. For now, the scan will fail for non-numerical results. But in that PR, the scan will always succeed since it's a string being scanned into a string type variable. Let me know what you think of this.

**Comment by rytaft** [comment]
___
*[pkg/internal/sqlsmith/tlp.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70494#-MkCrLycEE0ilX-mtElC:-MkD-HWvDHsNB2oVsMUv:b-1zfhb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb35048984d83d534f5388e27161332014c5d024/pkg/internal/sqlsmith/tlp.go#L303)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

Good catch on the comment, thanks! Yep, you're right about the second part. I thought of changing this but I decided that it's not worth it since in the PR I'm working on effectively reverses this change. In that PR, the counts are no longer compared and instead the results are compared directly with everything cast to a string. So it will be cast to a string in the future. For now, the scan will fail for non-numerical results. But in that PR, the scan will always succeed since it's a string being scanned into a string type variable. Let me know what you think of this.
</blockquote></details>

Ok, that sounds fine, since it looks like `runTLPQuery` would just ignore the error. I just wouldn't want you to merge this and have it cause a bunch of spurious test failures, but it looks like that won't be a problem.

**Review by nehageorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70494)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/internal/sqlsmith/tlp.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70494#-MkCr1sEBVL3Sqhz_5wr:-MkD8VweDfRUgM5sbvv1:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb35048984d83d534f5388e27161332014c5d024/pkg/internal/sqlsmith/tlp.go#L278)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: add `//` on this line so it's obvious the comment is continuous
</blockquote></details>

Done
___
*[pkg/internal/sqlsmith/tlp.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70494#-MkCrLycEE0ilX-mtElC:-MkD8WsI02wX3R7KZW2o:b1ubcge) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb35048984d83d534f5388e27161332014c5d024/pkg/internal/sqlsmith/tlp.go#L303)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ok, that sounds fine, since it looks like `runTLPQuery` would just ignore the error. I just wouldn't want you to merge this and have it cause a bunch of spurious test failures, but it looks like that won't be a problem.
</blockquote></details>

Makes sense

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70494#-:-MkD9r93Cgy1-QMfF2gJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nehageorge)

**Pull request merged**
