### PR TITLE
go.mod: bump grpc to v1.39.1

### PR DESCRIPTION
**Pull request by adityamaru**
Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
I'll follow this up with a bump of the google storage SDK. I ran `TestClientNodeID` just to sanity check and it is passing under stressrace.

**Review by knz — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=knz

**Comment by adityamaru** [comment]
bors r=knz

**Comment by adityamaru** [comment]
Rebasing in the hope that some of the bors flakes go away!

**Comment by adityamaru** [comment]
bors r=knz

**Pull request merged**
