### PR TITLE
acceptance: bump flyway versions

### PR DESCRIPTION
**Pull request by madelynnblue**
The flyway test has been failing stress. Bump its version to see if
that helps?

Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
See https://github.com/cockroachdb/cockroach/issues/47789

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47792)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47792)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/acceptance/compose/flyway/docker-compose.yml, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47792#-M5TocdOAf53Aw3Bcsco:-M5TocdOAf53Aw3Bcscp:bw8dxgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d62642c2f0dff83e606372448557b7ba49381ef/pkg/acceptance/compose/flyway/docker-compose.yml#L11)):*
> ```YAML
>     depends_on:
>       - cockroach
>     image: flyway/flyway:6
> ```

we could consider pinning this to 6.4.0 so that it doesn't change out from under us. though always testing the latest could be worthwhile too ... i don't feel strongly.

**Comment by mjibson** [comment]
The GSS compose test wasn't pinned to a specific version and a bug was uncovered in cockroach when it got bumped. I think it's worth it deal with the pinning fallout in acceptance tests.

**Pull request merged**
