### PR TITLE
ui: fix typo on "Help Us" page

### PR DESCRIPTION
**Pull request by tbg**
I'm not online much, so feel free to merge this (or fix it up).

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13472)

Jira issue: CRDB-14718

Jira issue: CRDB-14720

### CODE REVIEW

**Comment by tamird** [comment]
Needs `go generate ./pkg/...` to regenerate the UI assets

**Comment by tschottdorf** [comment]
Thanks, done. `yarn.lock` changed considerably and I suspect that's due to cruft on my branch, but I'll push and see what happens.

**Comment by tamird** [comment]
More likely it's due to your machine having an older version of yarn.

**Comment by tschottdorf** [comment]
Well, build is green, does that mean it's all good or should I keep poking locally?

**Comment by tamird** [comment]
LGTM

**Comment by tschottdorf** [comment]
TFTR, for the record I just updated my yarn and re-ran it, without incurring further changes.

**Pull request merged**
