### PR TITLE
vecstore: add per-partition locking to InMemoryStore

### PR DESCRIPTION
**Pull request by andy-kimball**
Previously, the in-memory store only supported locking the entire store
using a read-write lock. This meant that split/merge transactions could
never run concurrently with insert or search transactions. In addition,
even insert and search operations were serialized with a mutex.

This PR adds per-partition locking capability to the in-memory store. Now,
each partition has its own read-write lock. Split, merge, and insert
operations acquire a write lock before modifying a partition. Search
operations can run in parallel on a partition.

While only one split or merge operation can run at a time, it can run in
parallel with insert and search operations. Because of this, and because
insert and search operations acquire at most one partition lock at a time,
deadlocks are not possible.

Epic: CRDB-42943

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-:-ODP3fUj-jvm0QNPr1B8:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @mw5h)

___
*[`pkg/sql/vecindex/fixup_processor.go` line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODOr1cmBPlt1HoAjIWK:-ODOr1cmBPlt1HoAjIWL:b-3i6tl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5787aa18d77397b97ec17b7da1a85c00e6934c4/pkg/sql/vecindex/fixup_processor.go#L442)):*
> ```Go
> 		// not delete data or metadata in the partition.
> 		childKey := vecstore.ChildKey{PartitionKey: partitionKey}
> 		if !parentPartition.ReplaceWithLastByKey(vecstore.ChildKey{PartitionKey: partitionKey}) {
> ```

[nit] Can we just reference `childKey` here?
___
*[`pkg/sql/vecindex/fixup_processor.go` line 443 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODOqjq19nPsjNWIciSc:-ODOqjq202qPis5dAMO8:b-9kmem8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5787aa18d77397b97ec17b7da1a85c00e6934c4/pkg/sql/vecindex/fixup_processor.go#L443)):*
> ```Go
> 		childKey := vecstore.ChildKey{PartitionKey: partitionKey}
> 		if !parentPartition.ReplaceWithLastByKey(vecstore.ChildKey{PartitionKey: partitionKey}) {
> 			return errors.Wrapf(err, "removing splitting partition %d from its in-memory parent %d",
> ```

Is the idea behind this that we can filter some of the cases where the parent partition was concurrently removed without having to go to the store?
___
*[`pkg/sql/vecindex/vecstore/in_memory_lock.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODKJWgkBb9JnPp_gNsT:-ODKJWglDHxRAYiJ3_iw:bmund50) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc41bd9d235fea9f7a4a931adfe62b38316db58d/pkg/sql/vecindex/vecstore/in_memory_lock.go#L31)):*
> ```Go
> 
> // IsAcquiredBy returns the current exclusive owner of the lock, or zero if
> // there is currently no exclusive owner.
> ```

[nit] Looks like the comment is stale.
___
*[`pkg/sql/vecindex/testdata/search-features.ddt` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODOsqXH7ZNw5vgxPTsm:-ODOsqXH7ZNw5vgxPTsn:b2qld6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5787aa18d77397b97ec17b7da1a85c00e6934c4/pkg/sql/vecindex/testdata/search-features.ddt#L9)):*
> ```
> 3 levels, 91 partitions, 12.91 vectors/partition.
> CV stats:
>   level 2 - mean: 0.1306, stdev: 0.0340
> ```

Do you know what's causing the changes in the existing tests?
___
*[`pkg/sql/vecindex/vecstore/in_memory_store.go` line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODP1K1UDrBucmP3Nv2F:-ODP1K1UDrBucmP3Nv2G:b9mwf0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5787aa18d77397b97ec17b7da1a85c00e6934c4/pkg/sql/vecindex/vecstore/in_memory_store.go#L353)):*
> ```Go
> 	ctx context.Context, txn Txn, partition *Partition,
> ) (PartitionKey, error) {
> 	s.mu.Lock()
> ```

Should we assert that we're holding the structure lock?

**Review by mw5h — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136784)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[`pkg/sql/vecindex/vecstore/in_memory_lock.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODSTDOG1ORJhVbbZojf:-ODSTDOG1ORJhVbbZojg:b-s429gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc41bd9d235fea9f7a4a931adfe62b38316db58d/pkg/sql/vecindex/vecstore/in_memory_lock.go#L27)):*
> ```Go
> 	// exclusiveOwner is the id of its current exclusive owner, or zero if it
> 	// has not been acquired, or if it has only been acquired for shared access.
> 	exclusiveOwner atomic.Uint64
> ```

Why not just protect this with RWMutex? Atomics aren't free! :)
___
*[`pkg/sql/vecindex/vecstore/in_memory_lock.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODSTvRfD0Xen2bwuSAi:-ODSTvRfD0Xen2bwuSAj:bn6hahb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc41bd9d235fea9f7a4a931adfe62b38316db58d/pkg/sql/vecindex/vecstore/in_memory_lock.go#L68)):*
> ```Go
> // a call to Acquire. If the same owner made multiple Acquire calls, the lock
> // isn't released until Release is called the same number of times.
> func (pl *inMemoryLock) Release() {
> ```

Do you want to check owner here to see if the caller actually owns the lock? Seems weird that you're checking on acquisition but not on release.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136784)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/vecindex/fixup_processor.go` line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODOr1cmBPlt1HoAjIWK:-ODT90ip3qNhL6ncSKIz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5787aa18d77397b97ec17b7da1a85c00e6934c4/pkg/sql/vecindex/fixup_processor.go#L442)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Can we just reference `childKey` here?
</blockquote></details>

Done.
___
*[`pkg/sql/vecindex/fixup_processor.go` line 443 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODOqjq19nPsjNWIciSc:-ODT99P77mGgqv5JgoVc:b-zcm2cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5787aa18d77397b97ec17b7da1a85c00e6934c4/pkg/sql/vecindex/fixup_processor.go#L443)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Is the idea behind this that we can filter some of the cases where the parent partition was concurrently removed without having to go to the store?
</blockquote></details>

I just moved it down here from farther up. I want to remove the vector from the in-memory `Partition` so that it's consistent with with what will be in the Store once we call `removeFromPartition`. This prevents the `moveVectorsToSiblings` code from finding it when searching for sibling partitions. I could do that in other ways, but this way changes the in-memory `Partition` in the same way as we change it in the Store, which makes things easier to reason about.
___
*[`pkg/sql/vecindex/vecstore/in_memory_lock.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODSTDOG1ORJhVbbZojf:-ODTAUgr-zqQqdvOLRJf:bro1j2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc41bd9d235fea9f7a4a931adfe62b38316db58d/pkg/sql/vecindex/vecstore/in_memory_lock.go#L27)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

Why not just protect this with RWMutex? Atomics aren't free! :)
</blockquote></details>

Because it would cause a deadlock in the case where an owner already has the lock. RWMutex does not allow reentrancy, so trying to lock the mutex in order to then read the owner field will just lock up.
___
*[`pkg/sql/vecindex/vecstore/in_memory_lock.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODKJWgkBb9JnPp_gNsT:-ODTCW9v0utcoDOL2APu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc41bd9d235fea9f7a4a931adfe62b38316db58d/pkg/sql/vecindex/vecstore/in_memory_lock.go#L31)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Looks like the comment is stale.
</blockquote></details>

Done.
___
*[`pkg/sql/vecindex/vecstore/in_memory_lock.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODSTvRfD0Xen2bwuSAi:-ODTCZYKALf1CkR1Q5tk:b-1j8xbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc41bd9d235fea9f7a4a931adfe62b38316db58d/pkg/sql/vecindex/vecstore/in_memory_lock.go#L68)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

Do you want to check owner here to see if the caller actually owns the lock? Seems weird that you're checking on acquisition but not on release.
</blockquote></details>

On acquisition, I have to check it for the reentrancy check. Checking it on `Release` would just amount to an assertion where we panic if the owners don't match. Callers should never call `Release` with a different owner, after all. I don't think that assertion will catch much in the way of bugs, though, and it makes interface usage a bit more clunky, so I didn't add it.
___
*[`pkg/sql/vecindex/vecstore/in_memory_store.go` line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODP1K1UDrBucmP3Nv2F:-ODTD9268sXE9zT_3lF2:b-zf3vir) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5787aa18d77397b97ec17b7da1a85c00e6934c4/pkg/sql/vecindex/vecstore/in_memory_store.go#L353)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Should we assert that we're holding the structure lock?
</blockquote></details>

It's OK to call `InsertPartition` without the structure lock because there's no existing partition that might have been updated by other callers. That's not the case for `SetRootPartition` or `DeletePartition`, so I did check there. The danger in those cases is that we replace/delete a partition that was concurrently changed by another caller, such that we have "lost updates".
___
*[`pkg/sql/vecindex/testdata/search-features.ddt` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODOsqXH7ZNw5vgxPTsm:-ODTDceT4j2iCCuNyRJp:b-8i04jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5787aa18d77397b97ec17b7da1a85c00e6934c4/pkg/sql/vecindex/testdata/search-features.ddt#L9)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Do you know what's causing the changes in the existing tests?
</blockquote></details>

Yes, just slightly different sequences of operations. It's still deterministic, but even changes like reordering Store calls can cause different results.

**Comment by andy-kimball** [comment]
*[`pkg/sql/vecindex/vecstore/in_memory_store.go` line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODP1K1UDrBucmP3Nv2F:-ODTSN_-AQqdtnuEr3uE:b-96bj68) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5787aa18d77397b97ec17b7da1a85c00e6934c4/pkg/sql/vecindex/vecstore/in_memory_store.go#L353)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

It's OK to call `InsertPartition` without the structure lock because there's no existing partition that might have been updated by other callers. That's not the case for `SetRootPartition` or `DeletePartition`, so I did check there. The danger in those cases is that we replace/delete a partition that was concurrently changed by another caller, such that we have "lost updates".
</blockquote></details>

Actually, my comment was about partition locks. I went ahead and asserted that we have the structure lock for each of the methods that modify the structure of the tree.

**Review by mw5h — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136784)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/vecindex/vecstore/in_memory_lock.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-ODSTDOG1ORJhVbbZojf:-ODT_CTS7katTsfPJz9S:b1lzou6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc41bd9d235fea9f7a4a931adfe62b38316db58d/pkg/sql/vecindex/vecstore/in_memory_lock.go#L27)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Because it would cause a deadlock in the case where an owner already has the lock. RWMutex does not allow reentrancy, so trying to lock the mutex in order to then read the owner field will just lock up.
</blockquote></details>

You read to ensure you're not owner, then lock, then update. There shouldn't be any danger of another thread making you the owner.

**Review by mw5h — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136784#-:-ODTcdJ6EPBcpM8r1M_w:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @DrewKimball)

**Comment by andy-kimball** [comment]
bors r=drewkimball,mw5h

**Comment by andy-kimball** [comment]
bors r=mw5h

**Pull request merged**
