### PR TITLE
plpgsql: add support for CALL statements

### LINKED ISSUE #120818: plpgsql: add support for CALL statements
This issue tracks adding support for CALL statements within a PL/pgSQL routine. Here are the postgres docs: https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-STATEMENTS-RETURNING-PROCEDURE

Note that PL/pgSQL CALL statements have an interesting behavior for out parameters - the user supplies variables from the enclosing routine as arguments in the OUT parameter positions, and then the CALL statement assigns to those variables.

Jira issue: CRDB-36880
Epic: CRDB-34165

### LINKED ISSUE #121316: opt/optbuilder: building context needs to be reset when building a routine body
While the optbuilder is building a routine, it keeps track of the calling context. For example, `insideDataSource` indicates whether the routine is being used as a data source (e.g. `SELECT FROM udf();`). Currently, we don't reset `insideDataSource` when building the body of the routine, which may have nested routine calls. This changes the behavior of those nested routine calls, which can lead to internal errors / incorrect behavior. We should make sure to reset `insideDataSource` correctly, and also audit other context-like fields for similar bugs.

Example:
```
# Test nested function calls in a data source.
statement ok
CREATE TYPE typ AS (x INT, y INT);

statement ok
CREATE FUNCTION f_nested(a INT) RETURNS typ AS $$
  SELECT a * 2;
  SELECT ROW(1, 2)::typ;
$$ LANGUAGE SQL;

statement ok
CREATE FUNCTION f(a INT) RETURNS INT AS $$
  SELECT (f_nested(a)).y;
$$ LANGUAGE SQL;

query I
SELECT f(2);
----
2

query I
SELECT * FROM f(2);
----
2
```
The second query shown here should output `2`, but instead results in `invalid memory address or nil pointer dereference`.

Jira issue: CRDB-37183

### PR DESCRIPTION
**Pull request by DrewKimball**
#### opt/optbuilder: reset builder context for nested routines

This commit resets the `Builder.insideDataSource` field in the optbuilder
when building the body of a routine. This is necessary since a nested
routine is not (necessarily) inside a data source, even if its parent it.

Fixes #121316

Release note: None

#### plpgsql/parser: add parser support for CALL statements

This commit adds support in the PL/pgSQL parser for CALL statements
within a PL/pgSQL routine.

Informs #120818

Release note: None

#### plpgsql: implement CALL statements

This commit adds support for the PL/pgSQL CALL statement. This allows
a PL/pgSQL routine to execute a stored procedure. Note that there is
a behavior difference vs SQL CALL statements: if the stored procedure
has OUT parameters, the surrounding routine passes variables in each
OUT parameter position, and the result of the procedure is assigned to
those variables.

Fixes #120818

Release note (sql change): Added support for PL/pgSQL CALL statements.
It is now possible to call a stored procedure from a PL/pgSQL routine.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

I included some commented out tests in `procedure_plpgsql` recently (grep for `TODO(120818)`). We should either uncomment or remove them (your tests seem like a super set of what I added, so I'm ok with either option).

> Reviewed 3 of 3 files at r1, 4 of 4 files at r2, 20 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-:-NuAJNHzDhblh9tqYr8H:bbu27ec)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/optbuilder/routine.go` line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuAE96e0GOtn50iiWAs:-NuAE96e0GOtn50iiWAt:b-kh4inn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7c95955b9ce79b6098d3932e2db726838ba5db/pkg/sql/opt/optbuilder/routine.go#L289)):*
> ```Go
> 	oldInsideUDF := b.insideUDF
> 	oldInsideDataSource := b.insideDataSource
> 	defer func() {
> ```

nit: we can shorten this a bit like
```
	defer func(trackSchemaDeps, insideUDF, insideDataSource bool) {
		b.trackSchemaDeps = trackSchemaDeps
		b.insideUDF = insideUDF
		b.insideDataSource = insideDataSource
	}(b.trackSchemaDeps, b.insideUDF, b.insideDataSource)
```
___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call` line 278 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuAI7UXArJ_tUSaTfN4:-NuAI7UXArJ_tUSaTfN5:b-85u7a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/67858158068bc4b486f19549782c280513037f7c/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call#L278)):*
> ```
> subtest errors
> 
> # Recursive CALL is not possible.
> ```

Let's also add a test that creating a self cycle is not possible:
```sql
CREATE PROCEDURE p() AS $$                                                   
  BEGIN
    RAISE NOTICE 'p';
  END
$$ LANGUAGE PLpgSQL;
CREATE OR REPLACE PROCEDURE p() AS $$                                                   
  BEGIN
    CALL p();
  END
$$ LANGUAGE PLpgSQL;
```
Creation succeeds in PG but then invocation reaches the stack depth limit - we should fail the second creation stmt.
___
*[`pkg/sql/plpgsql/parser/testdata/stmt_call` line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuAFFU_26Zjj5qMSsVy:-NuAFFU_26Zjj5qMSsVz:b-lkxwhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c475cacdc95b5db9e93136d83c8f2230b7436cef/pkg/sql/plpgsql/parser/testdata/stmt_call#L80)):*
> ```
> CALL _(_, _);
> END;
>  -- identifiers removed
> ```

nit: should we also have a test case where we get something other than `FuncExpr` after `CALL` (i.e. the error case)?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121319)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuAKQVC-PpPCdokR5EX:-NuAKQVC-PpPCdokR5EY:blca8np) ([raw file](https://github.com/cockroachdb/cockroach/blob/67858158068bc4b486f19549782c280513037f7c/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call#L25)):*
> ```
> 
> statement ok
> DROP PROCEDURE p;
> ```

nit: what happens if we attempt to drop `p_nested` first? I'd expect that we'd get an error since CASCADE wasn't specified (and we currently don't support that).

Interestingly, postgres allows that which I think is a bug:
```
yuzefovich=# CREATE PROCEDURE p_nested() AS $$
  BEGIN
    RAISE NOTICE 'p_nested';
  END
$$ LANGUAGE PLpgSQL;
CREATE PROCEDURE
yuzefovich=# CREATE PROCEDURE p() AS $$
  BEGIN
    CALL p_nested();
    RAISE NOTICE 'p';
  END
$$ LANGUAGE PLpgSQL;
CREATE PROCEDURE
yuzefovich=# DROP PROCEDURE p_nested;
DROP PROCEDURE
yuzefovich=# CALL p();
ERROR:  42883: procedure p_nested() does not exist
LINE 1: CALL p_nested()
             ^
HINT:  No procedure matches the given name and argument types. You might need to add explicit type casts.
QUERY:  CALL p_nested()
CONTEXT:  PL/pgSQL function p() line 3 at CALL
LOCATION:  ParseFuncOrColumn, parse_func.c:627
```

**Review by DrewKimball — COMMENTED** [review]
>I included some commented out tests in `procedure_plpgsql` recently (grep for `TODO(120818)`). We should either uncomment or remove them (your tests seem like a super set of what I added, so I'm ok with either option).

Nice, I added some of those to the `plpgsql_call` test file.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-:-NuCpezM-69SlCT0wA-2:bq08cyy)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/routine.go` line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuAE96e0GOtn50iiWAs:-NuClPYzCAogR5ucSoA8:b-574kmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b7c95955b9ce79b6098d3932e2db726838ba5db/pkg/sql/opt/optbuilder/routine.go#L289)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we can shorten this a bit like
```
	defer func(trackSchemaDeps, insideUDF, insideDataSource bool) {
		b.trackSchemaDeps = trackSchemaDeps
		b.insideUDF = insideUDF
		b.insideDataSource = insideDataSource
	}(b.trackSchemaDeps, b.insideUDF, b.insideDataSource)
```
</blockquote></details>

Nice, Done.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuAKQVC-PpPCdokR5EX:-NuClRrY8SIBoRDMQC_V:b-ibxmx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/67858158068bc4b486f19549782c280513037f7c/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call#L25)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: what happens if we attempt to drop `p_nested` first? I'd expect that we'd get an error since CASCADE wasn't specified (and we currently don't support that).

Interestingly, postgres allows that which I think is a bug:
```
yuzefovich=# CREATE PROCEDURE p_nested() AS $$
  BEGIN
    RAISE NOTICE 'p_nested';
  END
$$ LANGUAGE PLpgSQL;
CREATE PROCEDURE
yuzefovich=# CREATE PROCEDURE p() AS $$
  BEGIN
    CALL p_nested();
    RAISE NOTICE 'p';
  END
$$ LANGUAGE PLpgSQL;
CREATE PROCEDURE
yuzefovich=# DROP PROCEDURE p_nested;
DROP PROCEDURE
yuzefovich=# CALL p();
ERROR:  42883: procedure p_nested() does not exist
LINE 1: CALL p_nested()
             ^
HINT:  No procedure matches the given name and argument types. You might need to add explicit type casts.
QUERY:  CALL p_nested()
CONTEXT:  PL/pgSQL function p() line 3 at CALL
LOCATION:  ParseFuncOrColumn, parse_func.c:627
```
</blockquote></details>

Yeah, we get an error - I'll add as a test. I think postgres allows it because of early vs late [binding behavior](https://dba.stackexchange.com/questions/300507/what-does-begin-atomic-mean-in-a-postgresql-sql-function-procedure). I actually don't think it's possible to get a PL/pgSQL routine to resolve dependencies during creation. But, our decision to have early-binding behavior was intentional. Here's some related discussion: https://cockroachlabs.slack.com/archives/C036BQTUJ9Z/p1676397226215059
___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call` line 278 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuAI7UXArJ_tUSaTfN4:-NuCnNVPDYh5_yC2f0cg:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/67858158068bc4b486f19549782c280513037f7c/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call#L278)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Let's also add a test that creating a self cycle is not possible:
```sql
CREATE PROCEDURE p() AS $$                                                   
  BEGIN
    RAISE NOTICE 'p';
  END
$$ LANGUAGE PLpgSQL;
CREATE OR REPLACE PROCEDURE p() AS $$                                                   
  BEGIN
    CALL p();
  END
$$ LANGUAGE PLpgSQL;
```
Creation succeeds in PG but then invocation reaches the stack depth limit - we should fail the second creation stmt.
</blockquote></details>

Good idea, done.
___
*[`pkg/sql/plpgsql/parser/testdata/stmt_call` line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuAFFU_26Zjj5qMSsVy:-NuCnoei0QI3JTyN9S8e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c475cacdc95b5db9e93136d83c8f2230b7436cef/pkg/sql/plpgsql/parser/testdata/stmt_call#L80)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we also have a test case where we get something other than `FuncExpr` after `CALL` (i.e. the error case)?
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 24 of 24 files at r4, 4 of 4 files at r5, 21 of 21 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121319)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call` line 355 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuQeyRNBb942dapjwXF:-NuQeyRNBb942dapjwXG:bu0x4av) ([raw file](https://github.com/cockroachdb/cockroach/blob/daf93ce728846318076b0abb5415c71f643677c7/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call#L355)):*
> ```
> # Try making a recursive CALL using REPLACE syntax.
> statement ok
> CREATE PROCEDURE p() AS $$                                                   
> ```

nit: dangling spaces on the first line here and in the next test case.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121319)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @yuzefovich)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call` line 355 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuQeyRNBb942dapjwXF:-NuR6Mmb60PlQGW1uDCx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/daf93ce728846318076b0abb5415c71f643677c7/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call#L355)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: dangling spaces on the first line here and in the next test case.
</blockquote></details>

Done.

**Review by mgartner — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 25 of 25 files at r7, 4 of 4 files at r8, 18 of 21 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121319)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 753 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuUh7NE7Jfff6SKZCn9:-NuUh7NE7Jfff6SKZCnA:bz1lwbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ace92e27cdb65873dccf1c25421233d84fd8438/pkg/sql/plpgsql/parser/plpgsql.y#L753)):*
> ```Yacc
>       return setErr(plpgsqllex, err)
>     }
>     proc, ok := expr.(*tree.FuncExpr)
> ```

I think we might need to set `proc.InCall` to true for correct formatting of the function expression. That's why this logic exists:
https://github.com/cockroachdb/cockroach/blob/c20e8c4bcc3dc3842c6adc64de37085beffd3605/pkg/sql/sem/tree/format.go#L481-L490

It prevents the function from being wrapped in parens, which is a syntax error. See my comment below.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call` line 89 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuUj9UB7OEQsC_RKQvb:-NuUj9UB7OEQsC_RKQvc:b-lzhlkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a497d2c25313a381312131c4976767c02c326b82/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call#L89)):*
> ```
>     foo INT := 100;
>     a INT;
>     b INT;
> ```

nit: is it worth adding a test where this are initialized or do you think the INOUT test below covers this case well enough?
___
*[`pkg/sql/plpgsql/parser/testdata/stmt_call` line 33 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuUhk4FCj-fFjT3hnOg:-NuUhk4FCj-fFjT3hnOh:b-1l2x6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ace92e27cdb65873dccf1c25421233d84fd8438/pkg/sql/plpgsql/parser/testdata/stmt_call#L33)):*
> ```
>  -- normalized!
> BEGIN
> CALL (p((1), (2)));
> ```

This shouldn't round-trip because the parens around the function are not allowed. I'm surprised it doesn't cause the test to fail.

In Postgres:

```
CREATE FUNCTION f() RETURNS VOID LANGUAGE plpgsql AS 'BEGIN CALL (p()); END';
ERROR:  42601: syntax error at or near "("
LINE 1: ... f() returns void language plpgsql as 'begin call (p()); end...
```

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 21 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-:-NuVdKxFBdtZLGaPiEBZ:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1906 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuVdD5q5etytNxh9LGF:-NuVdD5q5etytNxh9LGG:blksikh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a497d2c25313a381312131c4976767c02c326b82/pkg/sql/opt/optbuilder/plpgsql.go#L1906)):*
> ```Go
> 
> // checkDuplicateTargets checks for duplicate variables that are targets for
> // assignment, which currently isn't supported.
> ```

Is this a PG limitation too, or just an initial limitation for us?

**Review by DrewKimball — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-:-NuYIRlOCpENho-gsC3X:bz5mair)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1906 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuVdD5q5etytNxh9LGF:-NuYCHYT9HDntGS2Vc1-:b54f7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a497d2c25313a381312131c4976767c02c326b82/pkg/sql/opt/optbuilder/plpgsql.go#L1906)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is this a PG limitation too, or just an initial limitation for us?
</blockquote></details>

This is just an initial limitation. I opened an issue here to track: https://github.com/cockroachdb/cockroach/issues/121605 and added it to the error message.
___
*[`pkg/sql/plpgsql/parser/plpgsql.y` line 753 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuUh7NE7Jfff6SKZCn9:-NuY9gYuCFSavyTWVk6G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ace92e27cdb65873dccf1c25421233d84fd8438/pkg/sql/plpgsql/parser/plpgsql.y#L753)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think we might need to set `proc.InCall` to true for correct formatting of the function expression. That's why this logic exists:
https://github.com/cockroachdb/cockroach/blob/c20e8c4bcc3dc3842c6adc64de37085beffd3605/pkg/sql/sem/tree/format.go#L481-L490

It prevents the function from being wrapped in parens, which is a syntax error. See my comment below.
</blockquote></details>

Done.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call` line 89 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuUj9UB7OEQsC_RKQvb:-NuY9wFG9j3eppaLZ4ML:bz2b1ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/a497d2c25313a381312131c4976767c02c326b82/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_call#L89)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: is it worth adding a test where this are initialized or do you think the INOUT test below covers this case well enough?
</blockquote></details>

I'll initialize `a` to add some coverage.
___
*[`pkg/sql/plpgsql/parser/testdata/stmt_call` line 33 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/121319#-NuUhk4FCj-fFjT3hnOg:-NuYAgwO0_FQnhwF-LqT:bka82jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ace92e27cdb65873dccf1c25421233d84fd8438/pkg/sql/plpgsql/parser/testdata/stmt_call#L33)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This shouldn't round-trip because the parens around the function are not allowed. I'm surprised it doesn't cause the test to fail.

In Postgres:

```
CREATE FUNCTION f() RETURNS VOID LANGUAGE plpgsql AS 'BEGIN CALL (p()); END';
ERROR:  42601: syntax error at or near "("
LINE 1: ... f() returns void language plpgsql as 'begin call (p()); end...
```
</blockquote></details>

Looks like we don't actually verify that the parenthesized output round-trips anywhere except the very limited `TestParseTree` test. Adding it in with a patch like this:
```
diff --git a/pkg/testutils/sqlutils/parse.go b/pkg/testutils/sqlutils/parse.go
index ef9b330f207..f322415ab39 100644
--- a/pkg/testutils/sqlutils/parse.go
+++ b/pkg/testutils/sqlutils/parse.go
@@ -77,7 +77,22 @@ func VerifyParseFormat(t *testing.T, input string, plpgsql bool) string {
        // Check roundtrip and formatting with flags.
        var buf bytes.Buffer
        fmt.Fprintf(&buf, "%s%s\n", ref, note)
-       fmt.Fprintln(&buf, stmts.StringWithFlags(tree.FmtAlwaysGroupExprs), "-- fully parenthesized")
+       groupedExprs := stmts.StringWithFlags(tree.FmtAlwaysGroupExprs)
+       fmt.Fprintln(&buf, groupedExprs, "-- fully parenthesized")
+
+       reparsedStmts, err := parse(t, groupedExprs, plpgsql)
+       if err != nil {
+               t.Fatalf("unexpected error when reparsing with grouped expressions: %+v", err)
+       } else {
+               reparsedStmtsS := reparsedStmts.String()
+               if reparsedStmtsS != groupedExprs {
+                       t.Fatalf(
+                               "mismatched AST when reparsing with grouped expressions:\noriginal: %s\nexpected: %s\nactual:   %s",
+                               input, groupedExprs, reparsedStmtsS,
+                       )
+               }
+       }
+
        constantsHidden := stmts.StringWithFlags(tree.FmtHideConstants)
        fmt.Fprintln(&buf, constantsHidden, "-- literals removed")

@@ -85,7 +100,7 @@ func VerifyParseFormat(t *testing.T, input string, plpgsql bool) string {
        // first the literals are removed from statement to form a stat key,
        // then the stat key is re-parsed, to undergo the anonymization stage.
        // We also want to check the re-parsing is fine.
-       reparsedStmts, err := parse(t, constantsHidden, plpgsql)
+       reparsedStmts, err = parse(t, constantsHidden, plpgsql)
        if err != nil {
                t.Fatalf("unexpected error when reparsing without literals: %+v", err)
        } else {
```
causes the existing tests to fail, so CALL statements aren't unique here (though I'll set `InCall` either way).

**Pull request merged**
