### PR TITLE
distsql: benchmark valuesProcessor

### PR DESCRIPTION
**Pull request by solongordon**
Added a benchmark for valuesProcessor for various row counts with two
int columns.

Release note: None

### CODE REVIEW

**Comment by solongordon** [comment]
```
BenchmarkValues/rows=16-4         	  300000	      3934 ns/op	  65.06 MB/s
BenchmarkValues/rows=256-4        	   30000	     42594 ns/op	  96.16 MB/s
BenchmarkValues/rows=4096-4       	    2000	    654630 ns/op	 100.11 MB/s
BenchmarkValues/rows=65536-4      	     100	  11271856 ns/op	  93.03 MB/s
```

**Comment by jordanlewis** [comment]
:lgtm: although I'm not sure how much more than a benchmark of StreamDecoder this is. Should we try varying the chunk size? What does the actual Values code do?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/distsqlrun/values_test.go, line 126 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24834#-LALdfZr6AbnVRMzT-gS:-LALdfZr6AbnVRMzT-gT:b8glnzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a95e738d4d9ab728d35f9ded5e4d4d6d9fa6dc3f/pkg/sql/distsqlrun/values_test.go#L126)):*
> ```Go
> }
> 
> func BenchmarkValues(b *testing.B) {
> ```

minor: I'd call this `BenchmarkValuesProcessor` (I think the test above should also be called that)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24834#-:-LALepJY-VX7bIiL87p3:b-no99t7)*

**Comment by solongordon** [comment]
Yeah, the Values code doesn't seem to do much more than pass raw data to StreamDecoder and output it as rows. I'll add a few more chunk sizes in. It looks to me like we only ever do one row per chunk in practice, but would be good to know if that should change. Though I wonder if the number of VALUES rows is ever high enough for this to matter.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24834#-:-LATXu2B4pEkSL3nHK7r:b-ay8dji)*

**Pull request merged**
