### PR TITLE
Add mikeCRL to AUTHORS

### PR DESCRIPTION
**Pull request by mikeCRL**
Adding per onboarding call with @irfansharif.

### CODE REVIEW

**Comment by irfansharif** [comment]
yo, glad you were able to get further along. I'll just suggest one more change to the commit message before I rubber stamp it here. We'd want it to be of the form:
```
authors: add Mike Lewis to authors

Release note: None
```

You'll be able to edit it by using `git commit --amend`, and then pushing out those changes using `git push <remote name> <branch name> -f`.

**Comment by irfansharif** [comment]
Clearing out my review queue before pre-vacation, so just going to rubber stamp this away.

**Review by irfansharif — APPROVED** [review]

**Comment by mikeCRL** [comment]
Thanks, @irfansharif!

**Pull request merged**
