### PR TITLE
release-23.1: stats: more conservative lower bound for downward-trending forecasts

### PR DESCRIPTION
**Pull request by michae2**
Backport:
  * 1/1 commits from "stats: more conservative lower bound for downward-trending forecasts" (#122273)
  * 1/1 commits from "sql/stats: turn forecasting constants into cluster settings" (#122779)

/cc @cockroachdb/release

---

**stats: more conservative lower bound for downward-trending forecasts**

Instead of 0 as a lower bound for predictions, use 1/3 times the lowest prior observation. This will avoid predicting zero rows for a statistic unless we really observed zero rows somewhat recently.

Fixes: #119967

Release note (bug fix): Statistics forecasts of zero rows can cause bad plans. This commit changes forecasting to avoid predicting zero rows for most downward-trending statistics.

**sql/stats: turn forecasting constants into cluster settings**

Turn three constants used for statistics forecasting into cluster settings. (These must be cluster settings rather than session variables because forecasting happens when reloading table statistics in the stats cache, which can be independent of any session.)

Informs: #119967

Release note (sql change): Introduce three new cluster settings for controlling table statistics forecasting:

1. `sql.stats.forecasts.min_observations` is the minimum number of observed statistics required to produce a forecast.

2. `sql.stats.forecasts.min_goodness_of_fit` is the minimum R² (goodness of fit) measurement required from all predictive models to use a forecast.

3. `sql.stats.forecasts.max_decrease` is the most a prediction can decrease, expressed as the minimum ratio of the prediction to the lowest prior observation.

---

Release justification: specially-requested fix for plan regression bug.

### CODE REVIEW

**Comment by michae2** [comment]
There's no `slices` package in Go 1.19, so I had to add my own `slices.Min` calculation. Otherwise the backport was clean.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122594)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

**Comment by michae2** [comment]
(Hold off on reviewing until I also backport https://github.com/cockroachdb/cockroach/pull/122779.)

**Comment by michae2** [comment]
This is RFAL.

**Review by mgartner — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122594)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

**Comment by michae2** [comment]
Gah, hit merge too early without changing the 1/3 to 0. I'll open another PR for 23.1.

**Comment by michae2** [comment]
> Gah, hit merge too early without changing the 1/3 to 0. I'll open another PR for 23.1.

Opened https://github.com/cockroachdb/cockroach/pull/123036

**Pull request merged**
