### PR TITLE
server: Tenant pods fan out to cancel SQL queries

### PR DESCRIPTION
**Pull request by matthewtodd**
Partially addresses #70832.

Previously, the tenant `/_status/cancel_query` endpoint was not
available over HTTP and could not cancel a query not running locally.
This change opens it up, so that we can call it from the cloud console,
and makes sure that that we can cancel queries when a tenant has more
than one SQL pod running.

Release note (api change): The tenant `/_status/cancel_query` endpoint
was made available over HTTP and augmented to fan out requests in a
multi-pod world.

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
as long as the tests are fixed :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71503#-:-MltsQiM96tGWuSY0PXR:b-9nzp39)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @rafiss)

**Review by Azhng — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71503)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @matthewtodd, and @rafiss)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 600 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71503#-Mlu9mQA5pd3xIqBcrKa:-Mlu9mQA5pd3xIqBcrKb:bv1y1fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/307d8f9fa267f8d9cfd51c7d2fab6a94fde9a177/pkg/ccl/serverccl/tenant_status_test.go#L600)):*
> ```Go
> 	cancelQueryReq := serverpb.CancelQueryRequest{QueryID: query.ID}
> 	cancelQueryResp := serverpb.CancelQueryResponse{}
> 	err = httpPod1.PostJSON("/_status/cancel_query/"+session.NodeID.String(), &cancelQueryReq, &cancelQueryResp)
> ```

hmm, is the `NodeID` args here necessary? We would just fanout the RPC anyway right ? 
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 602 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71503#-Mlu8nW24TQ5uifyQiPZ:-Mlu8nW24TQ5uifyQiP_:bfbej2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/307d8f9fa267f8d9cfd51c7d2fab6a94fde9a177/pkg/ccl/serverccl/tenant_status_test.go#L602)):*
> ```Go
> 	err = httpPod1.PostJSON("/_status/cancel_query/"+session.NodeID.String(), &cancelQueryReq, &cancelQueryResp)
> 	require.NoError(t, err)
> 	require.Equal(t, true, cancelQueryResp.Canceled, cancelQueryResp.Error)
> ```

super small nit: perhaps we can format the error message a bit, e.g. "expected query to be cancelled, but encountered unexpected error %s"

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71503)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @dhartunian, and @rafiss)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 600 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71503#-Mlu9mQA5pd3xIqBcrKa:-Mluk74U916p6abAeHGY:b-sxbqeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/307d8f9fa267f8d9cfd51c7d2fab6a94fde9a177/pkg/ccl/serverccl/tenant_status_test.go#L600)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

hmm, is the `NodeID` args here necessary? We would just fanout the RPC anyway right ? 
</blockquote></details>

Good call. It had been necessary before I switched to fanout (I was jamming a SQLInstanceID into that field), but, yes, now that we're fanning out, I've replaced it with a `0` here.
___
*[pkg/ccl/serverccl/tenant_status_test.go, line 602 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71503#-Mlu8nW24TQ5uifyQiPZ:-MlukOCJ94_RLkw-77oI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/307d8f9fa267f8d9cfd51c7d2fab6a94fde9a177/pkg/ccl/serverccl/tenant_status_test.go#L602)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

super small nit: perhaps we can format the error message a bit, e.g. "expected query to be cancelled, but encountered unexpected error %s"
</blockquote></details>

Done.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71503)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @dhartunian, @matthewtodd, and @rafiss)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 600 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71503#-Mlu9mQA5pd3xIqBcrKa:-MlukkwR2woERvZxAbiL:bocnj17) ([raw file](https://github.com/cockroachdb/cockroach/blob/307d8f9fa267f8d9cfd51c7d2fab6a94fde9a177/pkg/ccl/serverccl/tenant_status_test.go#L600)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Good call. It had been necessary before I switched to fanout (I was jamming a SQLInstanceID into that field), but, yes, now that we're fanning out, I've replaced it with a `0` here.
</blockquote></details>

Ah nice. Hmm just wondering is it possible we can just leave it blank? I think `0` is an invalid SQLInstanceID right ?

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71503)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @dhartunian, and @rafiss)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 600 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71503#-Mlu9mQA5pd3xIqBcrKa:-MlulyhQ0a4jp08BSkgq:b1433f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/307d8f9fa267f8d9cfd51c7d2fab6a94fde9a177/pkg/ccl/serverccl/tenant_status_test.go#L600)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Ah nice. Hmm just wondering is it possible we can just leave it blank? I think `0` is an invalid SQLInstanceID right ? 
</blockquote></details>

Good question! I just looked, and the grpc gateway [won't let us leave it blank](https://github.com/cockroachdb/cockroach/blob/c7bfb49cb9d5453037fd4bcbea187de463398ba8/pkg/server/serverpb/status.pb.gw.go#L826-L829). I did wonder about putting some "meaningful" value in here, but I didn't have any ideas I liked, since the handler actually ignores this field altogether. Any thoughts?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71503)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @matthewtodd, and @rafiss)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 600 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71503#-Mlu9mQA5pd3xIqBcrKa:-MluniiiE68VaScMcuoZ:b-oj7ajg) ([raw file](https://github.com/cockroachdb/cockroach/blob/307d8f9fa267f8d9cfd51c7d2fab6a94fde9a177/pkg/ccl/serverccl/tenant_status_test.go#L600)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Good question! I just looked, and the grpc gateway [won't let us leave it blank](https://github.com/cockroachdb/cockroach/blob/c7bfb49cb9d5453037fd4bcbea187de463398ba8/pkg/server/serverpb/status.pb.gw.go#L826-L829). I did wonder about putting some "meaningful" value in here, but I didn't have any ideas I liked, since the handler actually ignores this field altogether. Any thoughts?
</blockquote></details>

Oooof :cry: , this is unfortunate. 

Actually, i'm not entirely sure if `node_Id` needs to be in the path param :thinking: . `/_status/resetsqlstats` has `NodeID` in the request payload but it doesn't have it specified in the path param. This is because it's a POST endpoint and we directly pass in the request protobuf from the caller. So perhaps that would be a way for us to drop the `node_id` field from the URL. Also I think for `/_status/statements` endpoint we have been using query params instead of the path params so that `node_id` will become optional. 

I guess that means we also need to update the frontend code to use those as well which can be a bit annoying :sweat_smile: . So I will defer that decision to you

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71503)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @dhartunian, and @rafiss)

___
*[pkg/ccl/serverccl/tenant_status_test.go, line 600 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71503#-Mlu9mQA5pd3xIqBcrKa:-Mluu9kzDD-ilW3xvzl2:b-fxi3ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/307d8f9fa267f8d9cfd51c7d2fab6a94fde9a177/pkg/ccl/serverccl/tenant_status_test.go#L600)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Oooof :cry: , this is unfortunate. 

Actually, i'm not entirely sure if `node_Id` needs to be in the path param :thinking: . `/_status/resetsqlstats` has `NodeID` in the request payload but it doesn't have it specified in the path param. This is because it's a POST endpoint and we directly pass in the request protobuf from the caller. So perhaps that would be a way for us to drop the `node_id` field from the URL. Also I think for `/_status/statements` endpoint we have been using query params instead of the path params so that `node_id` will become optional. 

I guess that means we also need to update the frontend code to use those as well which can be a bit annoying :sweat_smile: . So I will defer that decision to you 
</blockquote></details>

Agreed! Yes, that would work. I don't see a design reason why the `node_id` was put in the URL. But since that's where it also lives for the dedicated (non-tenant) status server, I suggest we not change it in this pull request. SG?

**Review by Azhng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71503#-:-MluwiY71pPSaUoXOcLr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @dhartunian, and @rafiss)

**Pull request merged**
