### PR TITLE
ui: Clarify name of the node count graph

### PR DESCRIPTION
**Pull request by a-robinson**
Addresses #18452 for 1.1

### CODE REVIEW

**Comment by BramGruneir** [comment]
Lgtm

**Comment by dianasaur323** [comment]
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511#-Ku5bOQ_hywFsuex23bA:-Ku5bOQ_hywFsuex23bB:bejeddg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5680ab48d292a72c453f9512ff75ff47a2eb51e1/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx#L12)):*
> ```XML
> 
>   return [
>     <LineGraph title="Live Node Count" tooltip="The number of live nodes in the cluster.">
> ```

Thanks for the quick turnaround on this! One thought is, should we add a small sentence that clarifies that this is the number of live nodes in the cluster from the perspective of the current node? Perhaps something like "The number of live nodes in the cluster from the perspective of the current selected node." or "The number of live nodes in the cluster. Each node should see the same number of live nodes in the cluster."

If you think it's self-explanatory, I'm fine with the tooltip you've added, so it's your call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511)*

**Comment by a-robinson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511#-Ku5bOQ_hywFsuex23bA:-Ku5dhY4B0CSfH3IRo7u:b-ohjsya) ([raw file](https://github.com/cockroachdb/cockroach/blob/5680ab48d292a72c453f9512ff75ff47a2eb51e1/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx#L12)):*
<details><summary><i>Previously, dianasaur323 (Diana Hsieh) wrote…</i></summary><blockquote>

Thanks for the quick turnaround on this! One thought is, should we add a small sentence that clarifies that this is the number of live nodes in the cluster from the perspective of the current node? Perhaps something like "The number of live nodes in the cluster from the perspective of the current selected node." or "The number of live nodes in the cluster. Each node should see the same number of live nodes in the cluster."

If you think it's self-explanatory, I'm fine with the tooltip you've added, so it's your call.
</blockquote></details>

The issue is that the tooltip needs to make sense both in the default view and in the single node view. In the default view we take the max number of live nodes reported by any node in the cluster, so saying "from the perspective of the current selected node" doesn't make a whole lot of sense to me. I'm happy to change the tooltip, I'm just not sure what to. Have any other ideas?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511)*

**Comment by dianasaur323** [comment]
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511#-Ku5bOQ_hywFsuex23bA:-Ku5itb91Iyk083ZFmxW:b-dya7e3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5680ab48d292a72c453f9512ff75ff47a2eb51e1/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx#L12)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The issue is that the tooltip needs to make sense both in the default view and in the single node view. In the default view we take the max number of live nodes reported by any node in the cluster, so saying "from the perspective of the current selected node" doesn't make a whole lot of sense to me. I'm happy to change the tooltip, I'm just not sure what to. Have any other ideas?
</blockquote></details>

You mean that this tooltip is shared with the cluster overview graph? In that case, let's leave as is, and we can document it. I added a note in Amruta's WIP admin UI docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511)*

**Comment by dianasaur323** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511#-:-Ku5lNS86ql7oCiorqVa:bnfp4nl)*

**Comment by dianasaur323** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511#-Ku5bOQ_hywFsuex23bA:-Ku5mA6tFuRHnNPMqzJ6:byph2cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5680ab48d292a72c453f9512ff75ff47a2eb51e1/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx#L12)):*
<details><summary><i>Previously, dianasaur323 (Diana Hsieh) wrote…</i></summary><blockquote>

You mean that this tooltip is shared with the cluster overview graph? In that case, let's leave as is, and we can document it. I added a note in Amruta's WIP admin UI docs.
</blockquote></details>

Yes (note in your screenshot in #18452 that you're still on the "Cluster Overview" page, you've just chosen to only display the graph's from one node's perspective)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511)*

**Comment by dianasaur323** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511#-Ku5bOQ_hywFsuex23bA:-Ku5oHKAeieewQccHbSa:bs4fbu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5680ab48d292a72c453f9512ff75ff47a2eb51e1/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx#L12)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Yes (note in your screenshot in #18452 that you're still on the "Cluster Overview" page, you've just chosen to only display the graph's from one node's perspective)
</blockquote></details>

gotcha, ok. That's an important clarification. Let's just merge this when ready then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18511)*

**Pull request merged**
