### PR TITLE
cli: make --global flag for demo public

### PR DESCRIPTION
**Pull request by otan**
see individual commits for details.
the tests require retries as the KV layer takes some time to put the ranges / leaseholders in the right place.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
The first commit doesn't work for me - time-based tests are much too flaky in our current infra.
I think there are two different issues to cover in tests:

1. check that zone configs can use region identifiers (i.e. the region attributes are properly configured). For this we want to apply zone configs and check there was no error applying them.

2. check that the latencies between nodes are non-trivial i.e. there is a latency simulator in there

For point 1, there is no need for timing test, just  a check that no error was encountered. This could also be checked just by listing the node localities - the relationship between the fact that nodes have localities and the fact that zone configs can use them is exercised by SQL unit tests already hopefully.

For point 2, I am not sure what the best approach is but I wonder if a TCL test is the best way to go about it. Is there a way perhaps to instantiate a demo cluster in-memory in a unit test in the cli package? Then connect to it with a SQL connection and then do similar things to what you have done here, but inside go.
(I would also then recommend use of the SQL query to wait for up-replication and migration of ranges. You can use `(*quitTest) waitForUpReplication()` in `pkg/cmd/roachtest` for inspiration)

2nd commit LGTM

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62226#-:-MW97-2R0oKVdXPjLyfs:btv960r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by otan** [comment]
the request by @ajstorm was a timing test but honestly i'm happy to get rid of it.
not sure how much i'm bothered for #2 atm, but i've spent more time than i should on this. honestly i'm happy to just go with the second commit for now /shrug

**Comment by knz** [comment]
@ajstorm can you spell out in writing what you're aiming for? 
Even the idea to make `--global` advertised is not so trivial to me, since the functionality is not clearly documented in the command line, interacts non-trivially with the other flags etc.

It seems to me we are missing a description of the desired UX journey, and  a double-check that the overall configurability is OK for the UX goals.

**Comment by ajstorm** [comment]
All I was looking for was validation that the latencies are being simulated
(i.e. that they're significantly larger than we'd expect within demo).  I
don't have a strong opinion on the best way to do that though.

**Comment by knz** [comment]
ok well in that case I would stand by my point:

1. use a go unit test
2. use a `show all cluster queries` statement as a measure of latency, and don't even set up zone configs, check range migration etc. `show all cluster queries` forces a fan-out to all the simulated nodes and will pay the latency price.

**Comment by knz** [comment]
Can you also please check #42243  has been fixed before we can be confident to advertise the flag

**Comment by otan** [comment]
alright, deferring this for now

**Pull request closed without merging**
