### PR TITLE
sql: remove depreceted config_yaml field from output

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Since `cockroach zone` is a deprecated command and we
no longer support the YAML method to configure zones, we shouldn't
show the YAML in the output at all for `SHOW ALL ZONE CONFIGURATIONS`
and for `SHOW ZONE CONFIGURATION FOR ...`. For backwards compatibility,
we can not remove the column all together yet so instead make the column
hidden.

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Awesome @ridwansharif! Thanks for taking this on. :lgtm: pending resolution of the admin UI data distribution screen

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30927#-:-LNv6mwJ0tH7c-BehGm_:b-wp9lwm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/server/admin.go, line 1552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30927#-LNv6W-ZAN7OiakwBZSn:-LNv6W-ZAN7OiakwBZSo:b-gbtpvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/67b74e61658ddf03d88d6c4136cffc51925727d3/pkg/server/admin.go#L1552)):*
> ```Go
> 			CliSpecifier: zcCliSpecifier,
> 			Config:       zcProto,
> 			ConfigYaml:   string(zcYaml),
> ```

Shoot, this breaks the admin UI data distribution page. http://localhost:8080/#/data-distribution if you have a local cluster running. We'll need to adjust that to render based on the zone config itself and not the YAML. @vilterp do you have guidance here? The tl;dr is that YAML is now a deprecated syntax for setting/showing zone configs so we want to hide it from users everywhere possible.

**Review by vilterp — COMMENTED** [review]
As long as there is some representation of the zone config on that screen, it's fine. Can we dump the SQL syntax that would create it, like `SHOW CREATE TABLE` but for zone configs?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30927#-:-LNvKnZiECEx-18ZN5Wl:bf5ak72)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by benesch** [comment]
We sure can! That's even readily available in the `config_sql` column. @ridwanmsharif, you up for plumbing that change through the admin UI?

**Comment by vilterp** [comment]
Looks like a reasonable solution! Let me just pull it down and try it locally.

**Review by benesch — COMMENTED** [review]
Wow, that was even simpler than I expected. Nice!

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30927#-:-LNvS2US99L8wc502jbl:byqje6g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/server/serverpb/admin.proto, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30927#-LNvRmF47I89YW9nHTQ8:-LNvRmF47I89YW9nHTQ9:b-2nhz52) ([raw file](https://github.com/cockroachdb/cockroach/blob/977963edf41878335cf5c54039a0cc3ce501be40/pkg/server/serverpb/admin.proto#L545)):*
> ```protobuf
> 
>     // config_sql is the SQL representation of config.
>     string config_sql = 3;
> ```

A good rule of thumb for protobufs is is new meaning, new field. Doesn't matter too much here, since we don't really have version skew between the web client and server, but best to be diligent.

```proto
reserved 3;

// config_sql is the SQL representation of config.
string config_sql = 4;
```

**Review by vilterp — APPROVED** [review]
image
Takes up a lot of space, but this page wasn't winning any awards for beauty anyway (yet). I am fixing a couple things on this page anyway; I can make a couple tweaks in a separate PR.

Someday we'll use the zone config proto in the UI so we can show the config / make it interactive in interesting ways, but that day isn't here yet.

**Review by ridwanmsharif — COMMENTED** [review]
Looks like there's not any objections to this. Merging when the tests pass.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30927#-:-LNvXC9P8sCvGrPzVH4C:b-lnshd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/server/admin.go, line 1552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30927#-LNv6W-ZAN7OiakwBZSn:-LNvX5tr0envSslemhK5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/67b74e61658ddf03d88d6c4136cffc51925727d3/pkg/server/admin.go#L1552)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Shoot, this breaks the admin UI data distribution page. http://localhost:8080/#/data-distribution if you have a local cluster running. We'll need to adjust that to render based on the zone config itself and not the YAML. @vilterp do you have guidance here? The tl;dr is that YAML is now a deprecated syntax for setting/showing zone configs so we want to hide it from users everywhere possible.
</blockquote></details>

Done.
___
*[pkg/server/serverpb/admin.proto, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30927#-LNvRmF47I89YW9nHTQ8:-LNvX6dy0f776lYwRNLe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/977963edf41878335cf5c54039a0cc3ce501be40/pkg/server/serverpb/admin.proto#L545)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

A good rule of thumb for protobufs is is new meaning, new field. Doesn't matter too much here, since we don't really have version skew between the web client and server, but best to be diligent.

```proto
reserved 3;

// config_sql is the SQL representation of config.
string config_sql = 4;
```
</blockquote></details>

Done.

**Review by benesch — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30927)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/server/serverpb/admin.proto, line 547 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30927#-LNvYl6yEaEx4uSs9jQN:-LNvYl6yEaEx4uSs9jQO:bwdwyn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a62292305128eb0de8a0154e3db0c38567291149/pkg/server/serverpb/admin.proto#L547)):*
> ```protobuf
> 
>     // config_sql is the SQL representation of config.
>     string config_sql = 4;
> ```

Don't go back through CI for this, but FYI Go naming convention prefers "SQL" to "Sql", so we like to use the customname option to override the default camel-casing algorithm. The syntax looks something like this: `[(gogoproto.customname) = "ConfigSQL"]`.

**Comment by vilterp** [comment]
Also @ridwanmsharif since you said "merging when the tests pass", Bors will do this for you if you comment here with `bors r+` on its own line. (It also batches your commit with others to save CI time and guard against merge skew)

**Pull request merged**
