### PR TITLE
pkg/util/log: alter bufferedSink to handle writes during sync flush

### LINKED ISSUE #106345: pkg/util/log: flush buffered log sinks on shutdown/panic
**Describe the problem**

Currently, when a cockroach process shuts down, we buffered file log sinks, but we *don't* flush the buffered network sinks (e.g. `fluent-servers`, `http-servers`). This is not only annoying when it comes to missing log lines on shutdown, but even worse, panic logs may not make it to their destination, leaving a gap in observability.

We tried to make this flush happen in the past, but ended up introducing a bug (https://github.com/cockroachdb/cockroach/commit/1629e11a6101cabf5feb3364cc8c2b51c8f8791b, https://github.com/cockroachdb/cockroach/commit/69a6a8f9f433989e8fb5960e7fd87c0d8150b1d5) because the `forceSync` output option used by the buffered sink has a high probability of triggering a panic, which can leave the mutex used in the buffered log sink code locked.

We need to find the right solution to close this observability gap for network logging. 

**Expected behavior**
All logs on shutdown/panic handling should be flushed, including those in buffered network sinks. 

Jira issue: CRDB-29518

### PR DESCRIPTION
**Pull request by abarganier**
Previously, if the bufferedSink had a synchronous flush scheduled, and an additional write (via the `output()` function) was sent to the bufferedSink, the bufferedSink would panic.

After some investigation & analysis of the code, this approach was found to be unnecessary. We can gracefully handle this scenario without panicking. Instead, we can buffer the message to be included in the upcoming flush.

In this scenario, if an additional forceSync output() call is sent to the bufferedSink, when one is already scheduled, we cannot make the call synchronous. Instead, we can buffer the message in the imminent flush, and return.

Because of this, we change the name of the forceSync option to tryForceSync, to indicate that it's best-effort and not an ironclad guarantee.

Release note: none

Fixes: https://github.com/cockroachdb/cockroach/issues/106345

NB: A follow up PR will reintroduce the flush trigger into the crash reporter / process shutdown procedure (similar to https://github.com/cockroachdb/cockroach/pull/101562, which was reverted). This PR focuses on the bufferedSink changes themselves, to keep discussion focused.

### CODE REVIEW

**Comment by abarganier** [comment]
For those interested, a deeper analysis was documented [here](https://docs.google.com/document/d/11ey9EMCU5I73aVvJY2Vo2jbjFHwr_tVoynaKiY-sjfk/edit?usp=sharing).

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108928)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/util/log/buffered_sink.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108928#-NcXpM0RCclvwstIQDZr:-NcXpM0RCclvwstIQDZs:b31z1yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7aaa2036b2af891796fc9934c27285dc69419bc2/pkg/util/log/buffered_sink.go#L227)):*
> ```Go
> 		err := bs.mu.buf.appendMsg(msg)
> 		if err != nil {
> 			if errors.Is(err, errMsgTooLarge) {
> ```

why the error conditional? presumably if an error is returned by `appendMsg`, by API contract the buffer wasn't taken over and can be discarded.

**Review by Santamaura — COMMENTED** [review]
Overall code :lgtm: but I'll let @knz approve it since there was a comment to address

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108928#-:-NcXtaoGB6bJMZogmcso:b-gjwaq8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108928)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @knz, and @Santamaura)

___
*[`pkg/util/log/buffered_sink.go` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108928#-NcXpM0RCclvwstIQDZr:-NcXvNl6-lq2N71lwUuX:b-gqaajg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7aaa2036b2af891796fc9934c27285dc69419bc2/pkg/util/log/buffered_sink.go#L227)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

why the error conditional? presumably if an error is returned by `appendMsg`, by API contract the buffer wasn't taken over and can be discarded.
</blockquote></details>

I guess it was a bit of extra caution on my end, but you're right, if `appendMsg` returns an error it's safe to assume the thing didn't get appended lol.

Removed the conditional.

**Review by Santamaura — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108928)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @knz)

**Comment by abarganier** [comment]
TFTR! 

bors r=knz,Santamaura

**Pull request merged**
