### PR TITLE
pgrepl: allow logging in with `replication` parameter

### PR DESCRIPTION
**Pull request by otan**
This commit adds the `replication=database` connection parameter, which enables certain replication commands to be run.
See: https://www.postgresql.org/docs/current/protocol-replication.html

We do this by making it a session variable instead of a parameter on the connection like PG does. This adds a hidden `replication` connection parameter to accomplish this.

Informs: #105130

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm! just a small comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105400#-:-NZDFKUwEvW80cAU0uKn:bmmgtuz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[`pkg/sql/pgwire/pre_serve_options.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105400#-NZDFAAC8btfvVJihYPA:-NZDFAAC8btfvVJihYPB:bhdvncq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6728de50887012dd862632227bcd26b808a5dd1/pkg/sql/pgwire/pre_serve_options.go#L97)):*
> ```Go
> 
> 		case "replication":
> 			// See session variable comment for the reason behind the remapping.
> ```

nit: could you change  to "behind the error remapping" -- took me a while to understand this comment.
___
*[`pkg/sql/pgrepl/pgrepl_test.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105400#-NZDFTDb1p3m7Qjzjrdm:-NZDFTDb1p3m7Qjzjrdn:b-4qzvz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6728de50887012dd862632227bcd26b808a5dd1/pkg/sql/pgrepl/pgrepl_test.go#L35)):*
> ```Go
> func TestMain(m *testing.M) {
> 	securityassets.SetLoader(securitytest.EmbeddedAssets)
> 	serverutils.InitTestServerFactory(server.TestServerFactory)
> ```

nit: add the leaktest auto generate thingo?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105400)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/pgwire/pre_serve_options.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105400#-NZDFAAC8btfvVJihYPA:-NZPCEhGDf-ttfB8jDju:b3woahh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6728de50887012dd862632227bcd26b808a5dd1/pkg/sql/pgwire/pre_serve_options.go#L97)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: could you change  to "behind the error remapping" -- took me a while to understand this comment.
</blockquote></details>

i've replaced it with an actual comment.

**Comment by otan** [comment]
*[`pkg/sql/pgwire/pre_serve_options.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105400#-NZDFAAC8btfvVJihYPA:-NZPCuIZ8MRAbcUrMSc1:b-ydgm7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6728de50887012dd862632227bcd26b808a5dd1/pkg/sql/pgwire/pre_serve_options.go#L97)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i've replaced it with an actual comment.
</blockquote></details>

sorry, i mean a full comment*

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
