### PR TITLE
colexec: refactor CASE operator to support all types

### LINKED ISSUE #44700: colexec: support CASE operator with Bytes output type
When #44660 merges, we will have disabled planning of CASE operator with Bytes as an output type due to current contradiction between the way CASE operator populates its output (setting values in arbitrary order) and flat bytes that prohibit sets in arbitrary order.

We should fix it. Probably the way to go is to refactor CASE operator to not be so tricky with selection vectors, and, instead, copy the data to select tuples out. This will allows us to remove `SelOnDest` flag from `coldata.CopySliceArgs` as well.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: refactor CASE operator to support all types**

Previously, the CASE operator didn't support Bytes-like output types
because of the mismatch between the desire to do arbitrary SET
operations on the vectors (the way the case operator currently works)
and the flat bytes not supporting such operations. This commit refactors
the case operator in order to lift that restriction.

It is achieved by not populating the output vector directly, but rather
populating a scratch vector first (where all projected tuples matched by
the same WHEN arm are grouped together) and then copying over from the
scratch to the output batch (according to carefully maintained "fake"
selection vector).

However, there is a complication when the original batch has a selection
vector set. In this case we have to be quite tricky. Previously, the
trickiness was handled by using `SelOnDest` flag of `Vec.Copy`; this
commit introduces special `CopyWithReorderedSource` into `coldata.Vec`
interface that performs the needed for us reordering while paying
attention to the original selection vector.

The original idea of this commit was to side-step the complication with
this original selection vector by always planning a deselector on top of
the input to the case operator, but that didn't work out because it
broke the assumptions of the logical AND/OR projection operators.
Refactoring those seems quite hard, so I removed the planning of the
deselector and introduced the new method.

Fixes: #44700.

Release note (sql change): Vectorized engine now supports CASE
expressions that output BYTES-like types.

**colexec: add randomized test of the CASE operator**

This commit adds a randomized test of the CASE vectorized operator. It
creates the expressions like `CASE @1 WHEN 0 THEN @2 WHEN 1 THEN @3 ELSE @4 END`
and populates such an input data set that the first column "partitions"
the data into non-intersecting sets which allows us to easily compute
the expected output. The test also employs the help of the
columnarizer/materializer pair in order to use random datum generation
facilities.

Release note: None

**coldata: remove no longer used SelOnDest flag of Vec.Copy**

Previous commit removed the only usage of `SelOnDest` flag of `Vec.Copy`
method, and this commit removes the no longer used flag. This allows for
a nice cleanup.

Release note: None

### CODE REVIEW

**Review by jordanlewis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66399)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/col/coldata/vec_tmpl.go, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-McGgoES6YvS7n6MGCVu:-McGgoES6YvS7n6MGCVv:bx5f4hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d69e161ee05af620cee0e45ffdb270add8cdccc6/pkg/col/coldata/vec_tmpl.go#L229)):*
> ```Go
> 
> // {{/*
> func _COPY_WITH_REORDERED_SOURCE(_SRC_HAS_NULLS bool) { // */}}
> ```

You should be able to use `//execgen:template<srcHasNulls>` here and remove the need for a custom template and the template comments and so on.
___
*[pkg/sql/colexec/case_test.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-McGhhUO93hzrPKYgSTS:-McGhhUO93hzrPKYgSTT:beqjhaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d69e161ee05af620cee0e45ffdb270add8cdccc6/pkg/sql/colexec/case_test.go#L75)):*
> ```Go
> 			// injection" subtest is skipped.
> 			tuples:     colexectestutils.Tuples{{nil}, {nil}, {nil}, {nil}},
> 			renderExpr: "CASE WHEN @1 = 42 THEN 1 WHEN @1 IS NOT NULL THEN 2 ELSE 42 END",
> ```

Sorry to be a pain. Could we create a randomized test for this operator? It is too complex for the simple testing we are doing right now. We should have longer batches that exercise some of the trickier logic. Not to mention bytes types.
___
*[pkg/sql/colexec/execgen/cmd/execgen/vec_gen.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-McGhXMV1VMQV9Jp7y-o:-McGhXMV1VMQV9Jp7y-p:b-iyy7l9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d69e161ee05af620cee0e45ffdb270add8cdccc6/pkg/sql/colexec/execgen/cmd/execgen/vec_gen.go#L34)):*
> ```Go
> 	s = copyWithSel.ReplaceAllString(s, `{{template "copyWithSel" buildDict "Global" . "SelOnDest" $6}}`)
> 
> 	copyWithReorderedSource := makeFunctionRegex("_COPY_WITH_REORDERED_SOURCE", 1)
> ```

this could be removed as well.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66399)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @michae2)

___
*[pkg/col/coldata/vec_tmpl.go, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-McGgoES6YvS7n6MGCVu:-McHCF_SDjQ7C9R17J6h:bws1u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d69e161ee05af620cee0e45ffdb270add8cdccc6/pkg/col/coldata/vec_tmpl.go#L229)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You should be able to use `//execgen:template<srcHasNulls>` here and remove the need for a custom template and the template comments and so on.
</blockquote></details>

I don't think it is currently possible because we have a template function call in `execgen.SET` below. I believe we currently don't support it, do we?
___
*[pkg/sql/colexec/case_test.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-McGhhUO93hzrPKYgSTS:-McHV7cq9Z7CAsN9IkpQ:b3gu97d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d69e161ee05af620cee0e45ffdb270add8cdccc6/pkg/sql/colexec/case_test.go#L75)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Sorry to be a pain. Could we create a randomized test for this operator? It is too complex for the simple testing we are doing right now. We should have longer batches that exercise some of the trickier logic. Not to mention bytes types.
</blockquote></details>

Good point, added another commit that performs the randomized test.
___
*[pkg/sql/colexec/execgen/cmd/execgen/vec_gen.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-McGhXMV1VMQV9Jp7y-o:-McHCP643k8VDrLdHGTU:b-xcsimm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d69e161ee05af620cee0e45ffdb270add8cdccc6/pkg/sql/colexec/execgen/cmd/execgen/vec_gen.go#L34)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

this could be removed as well.
</blockquote></details>

I'm guessing not yet.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66399)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @michae2)

___
*[pkg/col/coldata/vec_tmpl.go, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-McGgoES6YvS7n6MGCVu:-McKonX_4IMtPEFjKZ8x:b-wbboox) ([raw file](https://github.com/cockroachdb/cockroach/blob/d69e161ee05af620cee0e45ffdb270add8cdccc6/pkg/col/coldata/vec_tmpl.go#L229)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I don't think it is currently possible because we have a template function call in `execgen.SET` below. I believe we currently don't support it, do we?
</blockquote></details>

I opened up a separate PR (#66547) to remove `execgen.SET`, but now the difficulty is that I want `copyWithReorderedSource` to be templated based on the type of the vector, and I don't think it is possible yet. So IMO this PR should proceed as is, and we will need to update all templates at once to the new style once `execgen` is powerful enough.

**Comment by yuzefovich** [comment]
I rebased it on top of #66547 in order to simplify the discussion around `CopyWithReorderedSource` template function.

**Comment by yuzefovich** [comment]
Rebased on top of the merged #66547.

**Comment by yuzefovich** [comment]
@cockroachdb/sql-queries anyone care for a review here? :)

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 10 files at r1, 1 of 5 files at r2, 7 of 35 files at r5, 14 of 14 files at r6, 1 of 1 files at r7, 33 of 33 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-:-MelO6oBAdeptQoTVwqc:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/colexec/case_test.go, line 140 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-MelM4x_-RPROpB7hOQM:-MelM4x_-RPROpB7hOQN:b-80a1kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2687da3a1b63bfb6791fb44a1f8cb9de3504a21b/pkg/sql/colexec/case_test.go#L140)):*
> ```Go
> 	// following numWhenArms columns are the projections for the corresponding
> 	// WHEN "partitions", and then optionally we have an ELSE projection.
> 	caseExpr := "CASE"
> ```

Couldn't we also say `CASE @1 WHEN %d THEN ... WHEN  %d then ... ELSE`? It's the other form for `CASE`.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-:-MelO_k45jicUwidzksp:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @michae2)

___
*[pkg/sql/colexec/case_test.go, line 140 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66399#-MelM4x_-RPROpB7hOQM:-MelObsq6Ilw2kcNWN7C:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2687da3a1b63bfb6791fb44a1f8cb9de3504a21b/pkg/sql/colexec/case_test.go#L140)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Couldn't we also say `CASE @1 WHEN %d THEN ... WHEN  %d then ... ELSE`? It's the other form for `CASE`.
</blockquote></details>

Good point, done.

**Pull request merged**
