### PR TITLE
workload: give roachmart a simple read operation

### PR DESCRIPTION
**Pull request by benesch**
See commits within.

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3mynmUjJFH3-GijnbR:-L3mynmUjJFH3-GijnbS:bgj8mve) ([raw file](https://github.com/cockroachdb/cockroach/blob/38224f01afd3204494011541e15bce210b3aee7a/pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go#L26)):*
> ```Go
> var dataCenters = []string{"us_east", "us_west", "europe"}
> 
> // These need to be kept in sync with dataCenters, above, and the localities
> ```

Let's remove dataCenters so there's one fewer thing to keep in sync (and just use these as the partition names)

---

*[pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go, line 77 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3mz1fZgaHZUA0E9eYm:-L3mz1fZgaHZUA0E9eYn:bdpw0iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/38224f01afd3204494011541e15bce210b3aee7a/pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go#L77)):*
> ```Go
> 		g := &roachmart{flags: pflag.NewFlagSet(`roachmart`, pflag.ContinueOnError)}
> 		g.flags.Int64Var(&g.seed, `seed`, 1, `Key hash seed.`)
> 		g.flags.BoolVar(&g.partition, `partition`, false, `Whether to apply zone configs to the partitions of the users table.`)
> ```

Probably should default true

---

*[pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go, line 102 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3n-_l2Xom4M8SMg65R:-L3n-_l2Xom4M8SMg65S:b-c6zjjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/38224f01afd3204494011541e15bce210b3aee7a/pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go#L102)):*
> ```Go
> 			}
> 			found := false
> 			for _, dc := range dataCenters {
> ```

this could also use a map

---

*[pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go, line 189 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3n-mkRRU59MWRKYLFh:-L3n-mkRRU59MWRKYLFi:b46huod) ([raw file](https://github.com/cockroachdb/cockroach/blob/38224f01afd3204494011541e15bce210b3aee7a/pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go#L189)):*
> ```Go
> 					}
> 				}
> 				fmt.Println(query, dc, email)
> ```

intentional?

---

*[pkg/testutils/workload/workload.go, line 66 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3n-qPUCLYOYRs7sNpk:-L3n-qPUCLYOYRs7sNpl:b-v40j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/38224f01afd3204494011541e15bce210b3aee7a/pkg/testutils/workload/workload.go#L66)):*
> ```Go
> 	Validate func() error
> 	// PreLoad is called after workload tables are created and before workload
> 	// data is loaded.
> ```

mention that this is not called when storing or loading a fixture

---

*[pkg/testutils/workload/kv/kv.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3myWDAnb5wFnE5pYQw:-L3myWDAnb5wFnE5pYQx:b-oqa4xa) ([raw file](https://github.com/cockroachdb/cockroach/blob/45a9c446e433f1a3c95c01fb5673777b3f0d8ac3/pkg/testutils/workload/kv/kv.go#L94)):*
> ```Go
> 			w.maxBlockSizeBytes, w.minBlockSizeBytes)
> 	}
> 	// TODO(dan): Re-enable this check once splits are supported.
> ```

You lost this TODO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-:-L3n04377HMDOOeERzFZ:bnfp4nl)*

**Comment by benesch** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3mynmUjJFH3-GijnbR:-L425DgisC-mo_d14cU0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/38224f01afd3204494011541e15bce210b3aee7a/pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go#L26)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Let's remove dataCenters so there's one fewer thing to keep in sync (and just use these as the partition names)
</blockquote></details>

Done.

---

*[pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go, line 77 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3mz1fZgaHZUA0E9eYm:-L425KgieKO1n_64zEzC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/38224f01afd3204494011541e15bce210b3aee7a/pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go#L77)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Probably should default true
</blockquote></details>

Done.

---

*[pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go, line 102 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3n-_l2Xom4M8SMg65R:-L425Lqil5d3AQz6LVyN:b-sxsrcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/38224f01afd3204494011541e15bce210b3aee7a/pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go#L102)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this could also use a map
</blockquote></details>

Worried that random iteration order will make this less debuggable in the other places we range over `zones`.

---

*[pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go, line 189 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3n-mkRRU59MWRKYLFh:-L425UiSPigpv54TetXi:bu2j3sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/38224f01afd3204494011541e15bce210b3aee7a/pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go#L189)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

intentional?
</blockquote></details>

Nope. Removed.

---

*[pkg/testutils/workload/workload.go, line 66 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3n-qPUCLYOYRs7sNpk:-L425_Zkg1irWq4B7BwV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/38224f01afd3204494011541e15bce210b3aee7a/pkg/testutils/workload/workload.go#L66)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

mention that this is not called when storing or loading a fixture
</blockquote></details>

Done.

---

*[pkg/testutils/workload/kv/kv.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L3myWDAnb5wFnE5pYQw:-L425adcC2Z3IDW3ufRJ:bw552xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/45a9c446e433f1a3c95c01fb5673777b3f0d8ac3/pkg/testutils/workload/kv/kv.go#L94)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

You lost this TODO
</blockquote></details>

Whoops, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762)*

**Comment by danhhz** [comment]
Reviewed 2 of 7 files at r1, 5 of 7 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L42EIN5-13uufiLEloO:-L42EIN5-13uufiLEloP:bq0k2ob) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb7fa04e9c457b3812a9c3b4c7075729c74d45c/pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go#L43)):*
> ```Go
> 			buf.WriteByte(',')
> 		}
> 		buf.WriteString(fmt.Sprintf("\n\tPARTITION %[1]q VALUES IN ('%[1]s')", z))
> ```

don't eat a ci cycle over this, but why is one `q` and the other `s`? (also below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go, line 43 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762#-L42EIN5-13uufiLEloO:-L42G7--En2SGabI_C9H:b-e2krgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb7fa04e9c457b3812a9c3b4c7075729c74d45c/pkg/ccl/testutilsccl/workloadccl/roachmartccl/roachmart.go#L43)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

don't eat a ci cycle over this, but why is one `q` and the other `s`? (also below)
</blockquote></details>

`us-east-1` is not a valid partition name unless it's wrapped in double quotes. I could use `parser.NameString` instead but wasn't sure the dependency was worth it. Thoughts? I have another workload PR in the pipeline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21762)*

**Comment by benesch** [comment]
Merging because green :tada:. Thanks for the review!

**Pull request merged**
